### ISSUE TITLE
Determine form 8 clean up policy

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#10]
When does it get removed?

> Files are now deleted after upload (thanks @alex !). We should still have some kind of cleanup for files that don't get uploaded, but have been generated.

**Comment by plusjeff** [comment]
For context: This would remove Form 8 documents that did not get uploaded to VBMS (i.e. if the user did not complete Caseflow).

@labecker and @Brizzle59 : Is it safe to assume that no one will be actively certifying cases at 2am ET? We could have a script that runs nightly and removes any leftover PDFs that haven't been created within the last hour.

**Comment by labecker** [comment]
Manila Phillipines is 13 hours ahead and we just need to account for them. The nightly script of not removing within last hour should work. Or perhaps last two hours to be safe, just to give Manila some flex.

**Comment by alex** [comment]
I think we shouldn't rely on current time, we can just run a daily script
that deletes any files that have not been accessed in >= 24 hours? There's
no reason for someone to generate a form8 and then come back to it 2 days
later is there?

On Wed, Nov 4, 2015 at 3:25 PM, Lee Becker <notifications@github.com> wrote:

> Manila Phillipines is 13 hours ahead and we just need to account for them.
> The nightly script of not removing within last hour should work. Or perhaps
> last two hours to be safe, just to give Manila some flex.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/10#issuecomment-153852474>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by labecker** [comment]
Great point. I like the >=24 hours. Thank you.
