### ISSUE TITLE
Separate construction of case timeline data and UI presentation

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10004]
Currently we determine what values should populate each field of a case timeline entry at the same place in the code where we determine how those fields should be presented. This causes [the code that does both of these things](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/TaskRows.jsx) to be hard to comprehend and [bug prone](https://github.com/department-of-veterans-affairs/caseflow/issues/9968).

An element of the case timeline has 5 attributes that we determine from characteristics of the related task. We should determine each of these attributes first, then move on to displaying them
<img width="603" alt="case timeline element diagram" src="https://user-images.githubusercontent.com/32683958/54448381-f7e53f80-4721-11e9-8d18-9fc7f6581d89.png">

## Acceptance criteria
* [ ] Create a collection of normalized case timeline elements (on the front-end or back-end)
* [ ] Loop over this collection to determine how to display each element

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | |||||||
5 | 
8 | 
```

Timebox to a 3.

Why 1?

Why 2?
 - Code cleanup

Why 3?
 - Frontend
 
Why 5?
