### ISSUE TITLE
Intake | Sync reviews race condition causes duplicate EPs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#10001]
Today Colin noticed a duplicate EP being created for a Higher Level Review. After digging through the logs, it looks like the there was a `DecisionReviewProcessJob` launched as a result of the of the intake on the main thread.

However, before that job finished, a cron'ed `SyncReviewsJob` noticed an unprocessed Higher Level Review, starting a second `DecisionReviewProcessJob`.

Those two jobs got into a race condition, which ended up creating a duplicate EP.

## Solution
- We are only going to retry never attempted jobs if they were submitted over 3 hours ago

**Comment by pkarman** [comment]
I think this is an argument for only processing jobs via `SyncReviewsJob` and not also calling immediately in the sync flow.

**Comment by shanear** [comment]
That introduces up to an extra 2-3 minute delay for the happy path, which I don't think is great. The business has said often that some CA's want to be able to see the EP very soon after the intake.

I think we can probably change `requires_processing` to put a bigger buffer for `last_attempted_at`. We should only be retrying Asyncables that failed over 30 min to an hour ago. Thoughts?

**Comment by pkarman** [comment]
Maybe we just remove the `never_attempted` condition in the `attemptable` method? That way the cron job would only try things that have failed.

**Comment by pkarman** [comment]
Closing till we see this issue re-emerge.
