### ISSUE TITLE
Styleguide Component | Tabs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1000]
As a developer and designer, I want nav actions in a living style guide built with react components so I can consistently and easily apply nav changes across our Apps. 

# Acceptance Criteria
1. Verify that the title "Tabs" appears
1. Verify that there is a horizontal line above the title
1. Verify that the below copy appears underneath the title 
1. Verify that the "Tabs" appears under the copy with the related react component 
1. Verify that the "Tabs" appears on the left nav and clicking it takes you to the appropriate element 
1. Verify that Tabs with icons is under Tabs, with copy below title
1. Verify that when you click or tab through any of the tabs, it should only be bold when it is selected. 
1. Verify for tabs with icons that icons and tabs and both center aligned horizontally to each other and 6px apart. 
1. Validate that the descriptions from the copy section below are the only texts
1. Validate that when a tab is selected, there isn't a line going across it. 

ex. Correct
![image](https://cloud.githubusercontent.com/assets/13420618/24217804/75ce609c-0f17-11e7-85c5-ba186d80b014.png)

Incorrect
![image](https://cloud.githubusercontent.com/assets/13420618/24217819/809b33d8-0f17-11e7-885f-9c478a3e2ba6.png)

# Mocks
**_Style guide - {Tabs}_**

**Tabs without Icons**
![image](https://cloud.githubusercontent.com/assets/13420618/24217688/162fb294-0f17-11e7-997a-4981aa68e7b2.png)

**Tabs with Icons**
![image](https://cloud.githubusercontent.com/assets/13420618/24217694/1d7c393c-0f17-11e7-9159-67c242f35a26.png)

# Copy

**Tabs without Icons**

The US Web Design doesn’t include tabs so we’ve designed our own. The active tab is highligted with a blue border and blue text. Inactive tabs have grey text.  Disabled tabs are grey, have faded grey text, and cannot be clicked. 

**Tabs with Icons**

Icons are optional on tabs and are set by the designer in the mockup. These icons come from the Font Awesome package, which is set in the U.S. Web Design standards. Here is an example of tabs with icons:

# Related Stories
n/a

# Technical Notes
There should be an example of the component in the styleguide, but the code should be in caseflow commons.

**Comment by gnakm** [comment]
Here is each tab for active (bold), inactive (bold), disabled (regular or 500 weight). 
- File name header should be white when on active tab
- Active icon should always be blue
- Inactive/ disabled text is `dark-grey`

![image](https://cloud.githubusercontent.com/assets/13420618/23626361/97fe2a20-027a-11e7-9ad2-6188da785477.png)

**Comment by mmlumba** [comment]
@gnakm I'm going to add all the pixel specifications you asked me to make from Slack messages to this ticket, but can you also add other specifications that are necessary for validation?

**Comment by mmlumba** [comment]
Specifications (so far):
![pasted image at 2017_03_10 12_36 pm](https://cloud.githubusercontent.com/assets/4773320/24172408/74d52874-0e5e-11e7-9455-eb407f9f912e.png)
disabled background #F1F1F1
disabled foreground (text) #5B616B
-3px is perfect for the :white_check_mark:  
-4pm is perfect for the :x:

**Comment by astewarttistatech** [comment]
The current view of this page doesn't match what is displayed, style-wise. 

Current View:

(insert screenshot here when internet isn't being a dingus)

**Comment by gnakm** [comment]
@astewarttistatech Sorry. This went through some iterations and Marian and I sorta worked on this adhoc via slack. I just updated the first comment to what should be most accurate. 

/cc: @mmlumba

**Comment by astewarttistatech** [comment]
The current view of this page doesn't match what is displayed, style-wise. 

Current View:

(insert screenshot here when internet isn't being a dingus)

**Comment by kierachell** [comment]
**PASSED**
was deployed to `prod` anyway so who cares
