### ISSUE TITLE
Feature Request: Add a field for Mail Team so they can add Type of AOD Motion

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#10016]
## Description
The AOD Team would like to add a field for the Mail Team to complete that indicates what `Type of AOD Motion` a piece of mail is. This is currently an optional field in VACOLS.

The options would be:
- Age
- Financial Hardship
- Serious Illness
- Other: with a text field to fill out

## Work Around
Since this is a nice-to-have for now, the intermediate approach is the AOD Team asking the Mail Team to add this information (along with mail receipt date) to `Task Instructions`.

**Comment by laurjpeterson** [comment]
If an AOD motion is granted, we require users to mark a reason for the AOD which includes those options above. Do AOD users want this for denied motions as well?
