### ISSUE TITLE
Styleguide Component: Loading Button

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1001]
Add the loading button to the style guide. Ideally this would be a react component that captures the functionality of turning a submit button into a loading button when clicked. Confirm the design with @KHarshawat.

# Technical Notes
There should be an example of the component in the styleguide, but the code should be in caseflow commons.

**Comment by gnakm** [comment]
@lakohl @KHarshawat-gov Let's talk about this together!

**Comment by slj** [comment]
Styleguide example is in place, but code still needs to go in commons

**Comment by slj** [comment]
Move to commons will be in another sprint.

**Comment by kierachell** [comment]
**PASSED**
check on styleguide
