### ISSUE TITLE
AMA Hearing details missing hearing location

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10017]
In AMA hearing details page, the hearing location is missing, after it was scheduled for McAllen, TX. 

https://appeals.cf.ds.va.gov/hearings/608e0653-fe08-47b1-a373-7410b20b5ced/details

**Comment by ferristseng** [comment]
I may have fixed this when I did #10073! Can we confirm this is still an issue after that fix goes out @pshahVA?

**Comment by pshahVA** [comment]
Resolved.
