### ISSUE TITLE
Explore process/dev changes needed for Legacy mail tasks to be created in Caseflow

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10014]
Initial exploration of steps required for Legacy tasks to be created in Caseflow. 

1. Legacy appeals need RootTasks - vet whether we should do this for mail tasks or a more efficient approach
   - Are any RootTasks created for Legacy appeals right now?
     - Cases with hearing requests get a RootTask during the job from VACOLS Location 57 to CASEFLOW
   - Does it make sense to add a RootTask for a mail task, or a more coordinated approach after appeals are certified to the Board?
     - How to not interfere with RootTasks added for Legacy hearing cases? Maybe we just add RootTasks to non-hearing request appeals. 
1. Users need to be able to add MailTasks (that have Correspondence Types) to Legacy appeal RootTasks
   - Display the link to `+ create a task` in Currently Active Tasks component of Case Details for Legacy appeals (currently hidden)
1. Confirm all Legacy mail task assignees are prepared to work Legacy mail tasks in Caseflow (many BVA branches are working in multiple systems)
   - Vet idea with Branch chiefs
1. Determine refactoring needs (if it makes sense) prior to adding Legacy cases

### Current process
See AMA appeal mail task creation project - https://github.com/department-of-veterans-affairs/caseflow/issues/7404

Mail comes into the VBA or BVA P.O. Box. Employees in Janesville upload the mail in the Mail Portal. If the mail is for BVA, BVA employees process it in the following way:

- Mail supervisor assigns mail to individual mail staff in the Mail Portal
- Mail employee opens the mail in the mail portal
- Mail employee searches for the Veteran to confirm there is an appeal record.
- Mail employee adds a "mail tab" in VACOLS and assigns it based on routing rules. This is a mail task for someone at the Board to do
- Mail employee uploads the mail to VBMS utilizing centralized mail portal

**Comment by araposo-tistatech** [comment]
@araposo-tistatech before implementing this we would need to ensure the Mail team is prepared or bought into working legacy mail tasks.
