### ISSUE TITLE
Determine process to cancel Evidence Window Submission tasks when Veterans waive their evidence window

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10023]
Based on this [slack thread](https://dsva.slack.com/archives/CA1QBDLEL/p1545148239053500), we know that Veterans will send in correspondence to waive their 90-day evidence window. 

Some approaches:
- If the mail team recognizes that the mail item is a waiver of the evidence window
    - Mail team closes the `EvidenceSubmissionWindow` task that is already assigned to their organization
- If the mail team does not recognize that the mail item was a waiver of the evidence window
    - Mail team creates a general `Correspondence` task

## AC - work in progress
- [ ] A new mail task with Correspondence Type "Waiver of Evidence Window" has been created
- [ ] Routing logic?
- [ ] Content/copy somewhere to explain how to complete this task 

## Open questions:
- Should the EvidenceSubmissionWindow task be completed or cancelled when a waiver occurs?
- Should the mail team be the team assigned and then resolving these tasks?

**Comment by laurjpeterson** [comment]
@allyceh @sneha-pai @marvokdolor-gov @lowellrex @MeredithStewart @ShellySmithDSVA - fyi, a new task we'll need. related to all the task naming work we're doing now.

**Comment by laurjpeterson** [comment]
Per this [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/8333/files) Evidence Window Submission tasks are assigned to the Mail team. This decision was made because, logically, the mail team would receive physical mail with the Veterans' request to waive the Evidence Window, and could fulfill those waiver requests. 

The Evidence Submission Window tasks already have the following actions available to them. 
- Assign to team
- Assign to person
- Mark task complete
- Cancel task

Today, members of the mail team could technically cancel or complete these Evidence Windows in response to a waiver request. However, more discussion with the Board should occur around their policies about who should process these requests, and how they should be tracked.

**Comment by araposo-tistatech** [comment]
@araposo-tistatech Right now, Mail team can cancel & put the reason. This would be an enhancement to clearly distinguish a waived evidence submission task. Would need to inquire with the Board is Mail Team should continue to have this responsibility.
