### ISSUE TITLE
Create organization for acting judges

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10029]
In order to fully support acting judges in a post-VACOLS, Caseflow-only world we need to allow acting judges to have the same assignment and decision review functionality as full-time judges. To accomplish this we will create a new `ActingJudgeTeam` organization that is a subclass of the existing `JudgeTeam` class. For now `ActingJudgeTeam` should have exactly the same capabilities as the `JudgeTeam`, but in the future it may have different functionality (for example, these folks may eventually only be [distributed appeals with hearings they held](https://github.com/department-of-veterans-affairs/caseflow/issues/9998)).

Related to #8436 (Use `JudgeTeam` membership to determine judges and attorneys) but probably not blocked by it.

## Acceptance criteria
* [ ] Create new `ActingJudgeTeam` class
* [ ] Add a button [on the Caseflow Team Management page](https://github.com/department-of-veterans-affairs/caseflow/pull/9663) to create acting judge teams
* [ ] Make sure [automatic case distribution calculations](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/distribution.rb) are not impacted by the addition of `ActingJudgeTeam`s with no no attorneys as members of the team.
* [ ] Make sure acting judges can navigate from their personal queues to the "assign cases" view

**Comment by laurjpeterson** [comment]
Note: acting judges (when they have the judge role in VACOLS) have the functionality they need now to serve as acting judges for AMA cases. they can reassign any judge task assigned to them. and, they can use VACOLS for legacy cases.

**Comment by yoomlam** [comment]
Relevant to #13136

**Comment by araposo-tistatech** [comment]
Closing as this relates to an outdated case distribution algorithm request.
