### ISSUE TITLE
Show Board Grant Effectuations in Appeal search results

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10021]
EPs created as a result of Board decisions on Appeals generate DecisionDocuments in Caseflow, but they are invisible via the UI. That can confuse folks looking to correlate what is in VBMS with Caseflow.

### Acceptance criteria

- [ ] DecisionDocuments should be visible in search results

**Comment by leikkisa** [comment]
One note, the decision document results in the Board Grant Effectuation (not the other way around).

Should we show the decision documents or the Board Grant Effectuations which have the EP?  It sounds like Jane may want Board Grant Effectuations to be editable, so we may want to show those. We don't currently have a UI for those though, so if we have them show up in the search results we won't be able to link them anywhere at first.

**Comment by pkarman** [comment]
It's fine to wait to show them in search results till we have some place to direct users.

**Comment by araposo-tistatech** [comment]
@araposo-tistatech May need design input, touch base w/Peter for better understanding of the context before estimation can occur.

**Comment by hschallhorn** [comment]
> We don't currently have a UI for [editable Board Grant Effectuations] though, so if we have them show up in the search results we won't be able to link them anywhere at first.

> It's fine to wait to show them in search results till we have some place to direct users.

**Comment by araposo-tistatech** [comment]
@hschallhorn since the blocker is the UI piece should this move to Design backlog?

**Comment by hschallhorn** [comment]
The UI doesn't refer to the UI for search results, it's the UI for where the user would be directed to after clicking. This is foxtrot work and would be another ticket.
