### ISSUE TITLE
Bug: Docket won't open

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10026]
Hearing Docket for Indianapolis, IN won't open in either Hearing Schedule or Hearing Prep. 

https://appeals.cf.ds.va.gov/hearings/schedule/docket/94

Related Support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/4524#event-2210420227

We tested a variety of fully scheduled dockets for East Coast/Central/West Coast in Hearing Schedule -- all opened without timeouts.

**Comment by MeredithStewart** [comment]
I've confirmed and had Hearing Branch try, this docket won't open. We get a white screen - maybe a timeout? 

Also, Judge is reporting they can't open the Hearing Prep version of this docket.

**Comment by MeredithStewart** [comment]
We got a timeout in Hearing Prep as well. 
<img width="564" alt="Screen Shot 2019-03-18 at 11 10 20 AM" src="https://user-images.githubusercontent.com/36775274/54540501-7d5d2f80-496e-11e9-9ece-db16eeb8e2e7.png">

**Comment by ShellySmithDSVA** [comment]
This page is intermittently loading. When it does load the docket is missing addresses and representative information for all Veterans on the docket.

**Comment by MeredithStewart** [comment]
Confirmed that this page: https://appeals.cf.ds.va.gov/hearings/schedule/docket/94 still won't open in both Hearing Schedule and Hearing Prep for Judge Wills.

**Comment by MeredithStewart** [comment]
Confirmed work, can close ticket!
