### ISSUE TITLE
When impersonating a user, create a way to log out of user, but not log out of Caseflow

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#10035]
Issue: Right now, when an internal admin user impersonates another user in `/test/users` there is not a good way to log out of impersonating that user (without logging out of Caseflow).  

Here's a suggested flow:
1. After successfully impersonating a user in `/test/user`, let's redirect that user `/help`.  
2. When signed in to an impersonated user and going to `/test/user` this should log the admin user out of the impersonated user and back in to the admin account.

**Comment by nemodjuric** [comment]
And maybe:
3. When clicking on logout while signed in to an impersonated user, log the admin user out of the impersonated user and back in to the admin account and redirect to /test/user page.
