### ISSUE TITLE
Decision issue missing in Caseflow

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#10037]
Opening this ticket so that we can continue to de-bug missing decision issues in Caseflow. 

This case was dispatched from BVA on 3/12. There isn't a decision issue associated with the request issue: https://appeals.cf.ds.va.gov/queue/appeals/55ede599-89bd-46cc-b683-64c4541b173e

**Comment by aroltsch** [comment]
https://appeals.cf.ds.va.gov/queue/appeals/c2b58452-b4ee-4e05-8c6f-a936f86b417b

**Comment by aroltsch** [comment]
Investigation result:

https://appeals.cf.ds.va.gov/queue/appeals/c2b58452-b4ee-4e05-8c6f-a936f86b417b
The appeal has one request issue with a closed status `decided` and closed_at on Thu, 28 Feb 2019 13:45:54 UTC +00:00 even though it was dispatched on 2019-03-12 14:35:23 so the request issue was closed long before it was dispatched. That explains why validation https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/issue_updater.rb#L59 didn't prevent the checkout for a judge.

**Comment by aroltsch** [comment]
This ticket explains the problem in the comments https://github.com/department-of-veterans-affairs/caseflow/issues/10051
