### ISSUE TITLE
Caseworker Landing: Show VBMS File Number instead of VACOLS id

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1003]
As a caseworker, I want to see the VBMS file number in my history instead of the VACOLS id for the appeal, because I don't know what the VACOLS number is.

# Acceptance Criteria
- Verify that on the history page, the VACOLS ids shown in the current state screenshot below, are VBMS ids instead.

<img width="955" alt="screen shot 2017-02-24 at 10 19 29 am" src="https://cloud.githubusercontent.com/assets/1596259/23308919/c12cae6a-fa7a-11e6-8aba-43f1e1812783.png">

**Comment by kierachell** [comment]
**PASSED**
checked in `uat` but I can't show you what it says
<img width="961" alt="screen shot 2017-03-01 at 9 33 00 am" src="https://cloud.githubusercontent.com/assets/18075411/23464284/85952d96-fe62-11e6-92c0-d0d685054531.png">
