### ISSUE TITLE
Add tabs to judges' individual queue table views

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10044]
Judges' individual queues only show a single table that is the equivalent of attorney and generic queues' "assigned" tabs. Judges can navigate to their "assign cases" view [using the dropdown menu](https://github.com/department-of-veterans-affairs/caseflow/blob/38f4036dbedae0fed89bf4eb5c36349c16be9e57/client/app/queue/JudgeDecisionReviewTaskListView.jsx#L71) in the top right of their queue which provides a near-equivalent of the "on hold" tab. However, since judges now have the [ability to assign admin actions](https://github.com/department-of-veterans-affairs/caseflow/issues/8608) directly to the VLJ support staff there are some on hold tasks that are not represented in the "assign cases" view.

This ticket exists to add tabs for "on hold" and "completed" tasks (in addition to the existing "assigned" table view they see now) to judge queues in order to bring the judge queue into parity with the other two individual queues before [unify them](https://github.com/department-of-veterans-affairs/caseflow/issues/10032).

Attorney queue | Judge review cases view | Generic (Colocated) queue
--- | --- | ---
![image](https://user-images.githubusercontent.com/32683958/54545874-ea75c280-4978-11e9-8cc4-c99ed467afb3.png) | ![image](https://user-images.githubusercontent.com/32683958/54544961-08dabe80-4977-11e9-834d-e00b32627e3a.png) | ![image](https://user-images.githubusercontent.com/32683958/54545935-0e390880-4979-11e9-8577-7dc0af2be125.png)

## Acceptance criteria
* [ ] Add tabs to judges' individual queue table views

**Comment by lowellrex** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
      1 | 
      2 | |||
      3 | ||||||
      5 | |||
      8 | 
```

The tasks already exist on the front-end but we don't show them in the judge queue because we don't pick them out of the redux store. This will be a combination of back-end changes (to add the tabs to the queue config we return #11700) and front-end changes (if we need to define new functions to pull the tasks we want for a given tab out of the redux store).

Estimating this at a 3. Possible 2 because we may already have all of the front-end functions we need and all of the work is limited to the back-end. Possible 5 because we may need to add a lot of front-end functions to select the tasks we want, and determining what shows up in each tab could require a lot of interaction with non-developers.

Needs release notes, let the training team know about these changes as well so that training materials can be updated.

**Comment by yoomlam** [comment]
This has been brought up as a result of a Support ticket: https://dsva.slack.com/archives/CHX8FMP28/p1583866360253300.

**Comment by alisan16** [comment]
This was requested by DVC Osborne's team:
"Rank 3 of 20
Cases On Hold Visibility 
Ensure all users have an On Hold cases viewing tab in Caseflow."
