### ISSUE TITLE
Update RequestIssuesUpdate error if contention is not found

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10040]
The processing error on RequestIssueUpdate is not populated if it fails due to the contention not being found.

### Acceptance criteria:
Error is stored in RequestIssuesUpdate table
The RequestIssuesUpdate should ideally not be re-attempted since it is going to have the same issue again.

See #10041

**Comment by pkarman** [comment]
confirmed in prod
