### ISSUE TITLE
EP Creation: Station name disappears for a split second after submission

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1004]
When clicking "Create End Product" on the EP Creation page, the station name in the "Station of Jurisdiction" field disappears while the EP is being created. This is confusing users.

For example "397 - AMC", will change to "397" for a split second. This appears to happen for all EPs.

<img width="1554" alt="screen shot 2017-02-23 at 5 20 53 pm" src="https://cloud.githubusercontent.com/assets/1596259/23309077/53f9ba58-fa7b-11e6-8bd5-d9d2d7b825de.png">

**Comment by kierachell** [comment]
**PASSED**
![peek 2017-03-01 13-35](https://cloud.githubusercontent.com/assets/18075411/23475130/85cfd906-fe84-11e6-907d-48bdf25889a5.gif)
