### ISSUE TITLE
RequestIssuesUpdate saves the wrong contention_reference_id when removing and adding a contention

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10041]
When removing a contention from a decision review during edit, and adding another contention at the same time, the removed contention's ID is saved as the contention ID on the new request issue.

#### Acceptance Criteria
In one edit session, remove a request issue that has a contention in VBMS, and add a new request issue.

The removed issue should have its contention removed from VBMS. The added request issue should have a new contention in VBMS. The correct contention_reference_id for the new request issue should be stored in the Request Issues table. 

Sentry example:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4103/events/277138/

This contention was already removed in RequestIssuesUpdate 132, and was attempted again in 133

**Comment by pkarman** [comment]
See also #9800

**Comment by pkarman** [comment]
these contention ids are being assigned to more than one request issue in production:
`["87456051", "87449256", "87271002", "87130493", "87069181", "87087863", "87252459", "87376149", "87536950", "87378529", "87378528", "87378527"]`

**Comment by pkarman** [comment]
Research on the existing duplicates:

### 87456051 

same rating issue
should be 87559687

### 87449256 

both unidentified, different text
has 2 contentions, one with text of active RI [87559840] but submit date a month earlier, one with UNIDENTIFIED [87559706] with same submit date. both have same start date.

### 87271002

both unidentified, different text
has 3 contentions, one with UNIDENTIFIED [87530886] submit date of first RI, one with different text of active RI [87529397], one with text of removed original [87531629]

### 87130493

same rating issue
should be 87376331

### 87069181

same rating issue
should be 87194298

### 87087863

both unidentified, different text
has 3 contentions, all with "UNIDENTIFIED ISSUE - Please click "
87194818 - 5 march
87194817 - 5 march
87260694 - 7 march

### 87252459

same rating issue (active has value for rating_issue_associated_at)
has 2 contentions
87430458 - has rating text
87536803 - dated 2 days after RI

### 87376149

same rating issue (active has value for rating_issue_associated_at)
should be 87376623

### 87536950

same rating issue (active has value for rating_issue_associated_at)
has 2 contentions
87536948 - different text/date
87550278 - same text/date as rating

### 87378529

same rating issue (active has value for rating_issue_associated_at)
has 6 contentions
should be 87452297

 ### 87378528

same rating issue (active has value for rating_issue_associated_at)
should be 87452298

### 87378527

same rating issue (active has value for rating_issue_associated_at)
has 6 contentions
should be 87452296

**Comment by pkarman** [comment]
Found more and fixed:

* [x] 87395005 -> 87612794
* [ ] 87616524
* [ ] 87377189
* [ ] 87537381

**Comment by pkarman** [comment]
script to find duplicates:
```ruby
def find_dupe_contentions
  cont_ids = {}
  RequestIssue.where.not(contention_reference_id: nil).each do |ri|
    cont_ids[ri.contention_reference_id] ||= 0
    cont_ids[ri.contention_reference_id] += 1
  end
  cont_ids.keys.select { |id| cont_ids[id] > 1 }
end
```
