### ISSUE TITLE
Investigate insertBenefitClaim: City is null

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10059]
We are getting this error on establishing a claim.

```An error occurred while establishing the claim: Unable to establish claim: insertBenefitClaim: City is null```

We believe this is due to there being a non-Veteran claimant on the claim, and that dependent not having an address populated in the database.

Sentry example:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3467/events/277716/

#### Acceptance criteria
If the Veteran chooses a non-Veteran claimant on the review page, we validate the claimant's address and show a descriptive error, and require the address to be valid before allowing the user to proceed.

#### Technical notes
According to VBMS, in the case of the claimants the address validation is just that it exists, and if it exists it assumes that it's valid. It does not necessarily follow the same rules as the Veteran address validation.

**Comment by leikkisa** [comment]
Martina is going to ask the user to update the claimants address for the current case.

**Comment by leikkisa** [comment]
In this specific case, the claimant shows up as one of the Veteran's relationships, but getting the information for the claimant results in:
```{:number_of_award_benes=>"0", :return_code=>"SHAR 0000", :return_message=>"No records found"}```

When I look at a successful call, the address isn't present but there is a mailing and payment address ID (and also, fun, there's a payee code!).

I'm wondering if I should just handle the "No records found" case for now without digging further into the address.

**Comment by leikkisa** [comment]
I handled the nil address, since that was the case for this ticket and VBMS implied that if there's an address at all that is what they look for.  However depending on address validations downstream we may need to do more specific checks since the error we were getting implied it was about the city.  Preferably we could do some UAT testing to determine what is really needed.

**Comment by Sjones352** [comment]
@leikkisa looking at this screenshot, do I create an EP before I can validate the claimant's address in UAT to see  a descriptive error?
<img width="1280" alt="Screen Shot 2019-03-26 at 11 01 36 AM" src="https://user-images.githubusercontent.com/23080951/55008030-c5a3cf80-4fb6-11e9-82d2-fe12f524490e.png">

**Comment by leikkisa** [comment]
Sandra saw this error come up again today, so this requires more investigation still

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4174/events/283038/

**Comment by leikkisa** [comment]
Martina has not heard back from the user.  I sent an email to Jennifer to see if she could add the claimant.

**Comment by leikkisa** [comment]
@Sjones352 The error should happen on this screen after you click "Submit". So you don't have to fully establish the claim, you just have to try to go to the next page.

**Comment by leikkisa** [comment]
It looks like this:

![Screen Shot 2019-03-28 at 2.49.20 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/f66ef8db-965e-4934-96cd-4b0398f57319)

**Comment by Sjones352** [comment]
**Passes UAT**

<img width="1372" alt="Screen Shot 2019-03-28 at 7 22 19 PM" src="https://user-images.githubusercontent.com/23080951/55199044-ec1c6300-518e-11e9-8682-d6c815d4cd01.png">
