### ISSUE TITLE
Intake | Close Appeal request issues only if closed tasks

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10051]
Per @aroltsch 

> for the appeal, we should only close the request issue if the appeal has closed BvaDispatchTask tasks

See thread in https://dsva.slack.com/archives/C754H751T/p1553001634188200

> we should also reopen request issues that were closed and we might need to backfill missing decision issues

**Comment by aroltsch** [comment]
### Appeals that have been dispatched but missing decision issues:

```
Appeal.all.select { |a| a.tasks.where(type: "BvaDispatchTask").map(&:status).uniq == ["completed"] && a.decision_issues.empty? }
```

### Appeals that have not been dispatched but have have `decided` request issues: 

```
Appeal.all.select { |a| a.tasks.where(type: "BvaDispatchTask", status: "completed").empty? && a.request_issues.active.empty? }
```

**Comment by pkarman** [comment]
Clean up included:
```
appeals = Appeal.all.select { |a|
  a.tasks.where(type: "BvaDispatchTask", status: "completed").empty? &&
    a.request_issues.decided.any?
}

appeals.map(&:id)

appeals.map(&:request_issues).flatten.select(&:decided?).each { |r|
  r.update!(closed_status: nil, closed_at: nil) if r.decided?
}
```

**Comment by pkarman** [comment]
this problem was due to #9556 where we should have selectively skipped certain Appeals and not set their request issues to "decided".

**Comment by pkarman** [comment]
We identified further Appeals that require decision issues be re-created.

```
Appeal.all.select { |a| a.tasks.where(type: "BvaDispatchTask", status: ["assigned", "in_progress"]).any? && a.decision_issues.empty? }

Appeal.all.select { |a|
  a.decision_documents.any? && a.decision_issues.empty?
}
```

Affected Appeals: `[1040, 1127, 1203, 1220, 1248, 1296, 1273, 1373, 1394, 534, 1113, 1689, 240, 624, 138, 1096, 1542, 1640, 1082]`

@aroltsch is going to talk with @laurjpeterson about next steps.

**Comment by pkarman** [comment]
@aroltsch can we close this one?

**Comment by aroltsch** [comment]
Yes.
