### ISSUE TITLE
ARC Login doesn't work because we don't have station 397 recorded.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1006]
We need to find out what VACOLS RO # that they are to do this.

**Comment by abbyraskin** [comment]
Emailed George Byrd (coach) to confirm station code.

**Comment by abbyraskin** [comment]
@shanear Jed says AMC's RO is 97 (when all else fails, go straight to the source!)

**Comment by kierachell** [comment]
Not sure how to test this outside of `prod`?

**Comment by shanear** [comment]
@kierachell you can test in demo. Create a test user in station 397 and make sure everything looks good.

**Comment by kierachell** [comment]
**PASSED**

![screenshot_2017-02-27_12-33-21](https://cloud.githubusercontent.com/assets/18075411/23372285/fb1e96ae-fce8-11e6-8670-ce46916a38dc.png)

I'm a monkey, I can go anywhere.
