### ISSUE TITLE
Should we prevent users from assigning a task back to the team that assigned it to them?

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#10061]
@lowellrex originally surfaced an issue where the Privacy team was assigning tasks back to teams who originally assigned the task to them. They were doing this because they didn't have enough information to complete the task and couldn't take action on it. This creates a duplicate task in Caseflow. 

In the short term, we told the Privacy team to reach out to the appropriate team for clarifications via email. Given our user base is growing, I don't think that we can rely on every user remember this step. 

Proposed solution: 
1) In the "Assign to team" drop down, remove the team that originally assigned the task to the user, eliminating the duplication of tasks. This ensures that our users don't make this error. 
2) Is there any way to allow users to assign the task back to the team that assigned it to them, but not duplicate the task? Could we close the original child task that was created? The drawback is that we don't want to make Caseflow a "communication tool".  

cc: @sneha-pai @marvokdolor-gov @laurjpeterson

**Comment by lowellrex** [comment]
I outlined one approach for handling the privacy team duplicate task issue [in a recent ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/10002) in case that informs what we do for this ticket.

**Comment by lowellrex** [comment]
Closing this, will reopen if it comes back. Will be solve by #10002.
