### ISSUE TITLE
Bug: Judge doesn't see all hearing days assigned in Hearing Prep. Hearing Schedule Filter for Judge doesn't show all of Judges hearing days.

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10066]
Judge Michael Herman sees different hearing days in Hearing Prep than we see in Hearing Schedule, even though Veterans are scheduled. One of the hearing days that the Judge was changed to (4/22), is not showing up in the filter for that judge on Hearing Schedule, but does show up inline. 

What Judge Herman can see for upcoming hearing days in Hearing Prep: 
<img width="313" alt="Screen Shot 2019-03-20 at 10 06 26 AM" src="https://user-images.githubusercontent.com/36775274/54693327-cba03900-4afc-11e9-89ce-fb165debdc64.png">

Judge Herman's hearing days in Hearing Schedule: 
<img width="151" alt="Screen Shot 2019-03-20 at 10 06 40 AM" src="https://user-images.githubusercontent.com/36775274/54693329-cba03900-4afc-11e9-81b1-b49fcdf93b71.png">

One we expect to show up: 
* 4/4/19 - https://appeals.cf.ds.va.gov/hearings/schedule/docket/87 - Judge Herman is assigned the Fargo docket, Veterans are scheduled 
* 4/22/19 - Docket for Boston - Judge Herman is on the docket, but this date doesn't appear in the VLJ filter: https://appeals.cf.ds.va.gov/hearings/schedule/docket/225 (this was a date change) 

Dates that should show up when a Veteran is scheduled: 
* 4/10/19 - https://appeals.cf.ds.va.gov/hearings/schedule/docket/131 - Judge Herman is assigned the Houston docket, but no Veterans are yet scheduled (I inquired and they will be postponing Veterans from a snow day to this day) 
* 4/17/19 - https://appeals.cf.ds.va.gov/hearings/schedule/docket/202 - Judge Herman is assigned St. Paul docekt, but not Veterans are scheduled (all postponed)

**Comment by MeredithStewart** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/4531

**Comment by ShellySmithDSVA** [comment]
Judge Kroes is experiencing a similar issue outlined in the ticket below.
https://github.com/department-of-veterans-affairs/appeals-support/issues/4557

Days have been switched and show up correctly on the Daily Docket, but not in the list.
