### ISSUE TITLE
Update hearing location in Hearing Details

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10073]
Hearing location needs to be updated to reflect Washington, DC for Central Office hearings. It was showing the VACOLS RO as hearing location.

<img width="498" alt="Screen Shot 2019-03-20 at 11 56 25 AM" src="https://user-images.githubusercontent.com/36775274/54699551-9d742680-4b07-11e9-845f-41dc89e81cbd.png">

**Comment by lomaxap** [comment]
Could address tech debt with this. Ideally the front end shouldn't have any conditional for displaying hearing location

**Comment by pshahVA** [comment]
![image](https://user-images.githubusercontent.com/49729315/59864920-cf3e9880-9355-11e9-8034-475966f92e3b.png)
