### ISSUE TITLE
Intake | No decision date error on edit

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10070]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4141/events/278262/

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4415/events/291850/

Unable to identify a decision date for a rating issue.

This is a Supplemental Claim with one rating request issue. The rating issue has a profile date.

When fetching the ratings there is a "Locked Rating Detected" error, which seems related to #9817 .

We need a better error message when zero ratings are available on editing an existing Decision Review that has rating request issues.

### Acceptance criteria

* All unlocked ratings should be returned via the `Rating` model.
* Store the rating promulgation date on the `decision_date` column during initial Intake
* If an existing rating request issue refers to a locked rating (not in the returned array from `Rating`) then present the user with an error that "one or more locked ratings may prevent this claim from being viewed" instead of letting the page throw a JS exception about `no decision date`.

**Comment by pkarman** [comment]
another case https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4209/

**Comment by pkarman** [comment]
> Store the rating promulgation date on the `decision_date` column during initial Intake

handled in #10274

**Comment by pkarman** [comment]
> present the user with an error that "one or more locked ratings may prevent this claim from being viewed"

in #10351 and #10380

**Comment by pkarman** [comment]
Validation steps:

* identify a locked rating in UAT
* attempt to edit an existing Claim for the affected veteran
* should receive an error message asking you to try again in 24 hours.

**Comment by Sjones352** [comment]
@pkarman I used this file that has a locked rating to validate `984562385` but I never get the error message. Wondering if I am missing something here

**Comment by leikkisa** [comment]
@Sjones352 I think after re-reading this, we need the rating that is now locked to be one of the ratings that a user added to an intake (so at the time it wasn't locked), and then lock the rating, and then try to edit it.

I think we'll need to enlist Colin's help on this one. Let's first try to find a Decision Review that has a rating issue on it, and then ask Colin if he can "Lock" that specific rating, then try to edit the Decision Review again.  This is when I suspect we should see that error message.

**Comment by Sjones352** [comment]
I have created an Ep on this file`700032062` and added a rating. Asking Colin to lock it so that I can try it again

![Screen Shot 2019-05-03 at 2.36.31 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/3844937c-be09-4bdb-8dbf-70e314707af5)

**Comment by Sjones352** [comment]
Looks like I will have to ask for another file number to have a locked rating

**Comment by Sjones352** [comment]
@leikkisa perhaps you would help me test this issue. Colin locked this rating 700060404 but I still can not recreate the `error message asking you to try again in 24 hours`.

Please view https://appeals.cf.uat.ds.va.gov/higher_level_reviews/c4630181-32aa-472d-843c-542d668badaa/edit
![Screen Shot 2019-05-21 at 3.14.05 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/ebd90ba5-f907-4845-87a9-6765b8733880)

<img width="1680" alt="Screen Shot 2019-05-21 at 3 16 28 PM" src="https://user-images.githubusercontent.com/23080951/58124380-17925b80-7bdc-11e9-9049-72d07dca6800.png">

At this point I see that it is a `backfilled_rating`

code the shows it's a locked rating
```
def fetch_ratings_in_range(participant_id:, start_date:, end_date:)
    ratings = (self.class.rating_records || {})[participant_id]

    # mimic errors
    if participant_id == "locked_rating"
      return { reject_reason: "Locked Rating" }
    elsif participant_id == "backfilled_rating"
      return { reject_reason: "Converted or Backfilled Rating" }
    end```

**Comment by Sjones352** [comment]
@leikkisa perhaps you would help me test this issue. Colin locked this rating 700060404 but I still can not recreate the `error message asking you to try again in 24 hours`.

Please view https://appeals.cf.uat.ds.va.gov/higher_level_reviews/c4630181-32aa-472d-843c-542d668badaa/edit
![Screen Shot 2019-05-21 at 3.14.05 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/ebd90ba5-f907-4845-87a9-6765b8733880)

**Comment by leikkisa** [comment]
@Sjones352 I think the rating is still cached, because veteran.ratings is still returning the rating for me. They get cached for 1 day, so tomorrow the rating will be missing and you should be able to validate.

Backfilled and locked are a little different but I think for validating this ticket it should be okay.

**Comment by leikkisa** [comment]
@Sjones352 Did you mean to close this?

**Comment by Sjones352** [comment]
Nope didn't mean to close it

**Comment by Sjones352** [comment]
This is still not working. veteran.ratings is still returning the rating.

**Comment by leikkisa** [comment]
We haven't been able to get Colin to successfully lock the rating (and for it to stay locked).  We are successfully getting this rating returned in the console, with "N" for the lockedRatingInd.

We are going to close this issue since we can't validate it in UAT.
