### ISSUE TITLE
Intake | UNIDENTIFIED text losing quotation marks

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10089]
Our special phrase `"UNIDENTIFIED ISSUE - Please click \"Edit in Caseflow\" button to fix"` is getting broken somehow en route to/from VBMS API. It ends up as `"UNIDENTIFIED ISSUE - Please click ` instead.

Change the text to not use embedded double quotation marks or use HTML entity instead &amp;quot;. Will require some investigation.

Should also test whether double question marks pose a problem in general, for manually entered description text, e.g.

**Comment by leikkisa** [comment]
I am not sure when this happens, because it doesn't happen when we create the contention, or fetch the contention, at least not in UAT.  I will look for specific examples of this in Prod next.

**Comment by pkarman** [comment]
If you look for contentions with the description `UNIDENTIFIED ISSUE - Please click` that's the clue.

**Comment by pkarman** [comment]
try contention 88716695 in prod

**Comment by pkarman** [comment]
e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4669/events/310224/
