### ISSUE TITLE
EP is canceled before establishment is fully processed

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10088]
When an End Product is canceled before the final step of establishment is completed (associate rated issues), then it can be set to processed so that it does not continue to try to associate rated issues.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3405/events/274042/

This is a manual step currently: calling `.canceled!` on the decision review object. We see that a decision review is stuck in the Async Jobs page. 

We think we want to automate this process. 

## AC
- We should confirm or code it to cancel the asynchronous process
- If all EPs on a decision review were canceled, then we can cancel the decision review

## Note
- If there are multiple EPs on a single decision review (e.g. rating and non-rating) and one of them gets canceled but the other isn't, we wouldn't want to cancel the whole decision review, we just want to ignore the EP that has been canceled.

**Comment by laurjpeterson** [comment]
Moving to backlog. Will revisit if we notice an uptick in these.

**Comment by msj0nes** [comment]
Closing ticket. Issue last seen Jun 15, 2019 6:55:16 PM EDT. Ticket can be reopened if alert resurfaces.
