### ISSUE TITLE
Styleguide | Radio Buttons 

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1008]
As a developer and designer, I want a want a clear and consistent way to implement radio buttons across our apps so our users can select important options.  

# Acceptance Criteria
1.  Verify that in the living style guide there is a section with the title `Radio Buttons`
1. Verify that the correct description appears below `Radio Buttons` (see copy section) 
1. Verify that the horizontal and vertical components appear underneath the copy (see mock ups)
1. Verify that the Error Radio Button component appears beneath the Error Buttons Copy (see mock ups and copy)
1. Verify that `Radio Buttons` is in the styleguide side nav
1. Verify that clicking on `Radio Buttons` in side nav takes you to the write section

# Mocks
_Make sure you are logged into Invision before clicking links_

**Vertical radio button**

[Invision Craft Link - Vertical Radio Buttons](https://projects.invisionapp.com/d/main#/console/10592592/225679057/inspect)

![image](https://cloud.githubusercontent.com/assets/13420618/24341915/3c6aab04-128b-11e7-8ae2-d1935935447a.png)

**Horizontal radio button**

[Invision Craft Link - Horizontal Buttons](https://projects.invisionapp.com/d/main#/console/10592592/225679057/inspect)

![image](https://cloud.githubusercontent.com/assets/13420618/24341918/47300516-128b-11e7-896a-79e5edb68629.png)

**Required  Radio Button Errors**

[Craft Invision Link - Required Button Erros](https://projects.invisionapp.com/d/main#/console/10592592/225744029/inspect)
![image](https://cloud.githubusercontent.com/assets/13420618/24341948/82701e2c-128b-11e7-87a7-a1731836ff13.png)

# Copy

**Title**

Horizontal Checkboxes and Radio Buttons

**Description**

Checkboxes and Radio Button largely follow the same design as those in the US Web Design Standards but we also include horizontal radio buttons. This layout is used when there are at most 2 options. 

**Radio Button Errors** 

In certain circumstances we ask the user to click a radio button agreeing to an action before proceeding. The text here is should be limited to 75 characters and indented so it doesn't flow under the radio buttons. Most of the time these radio buttons should have a required indicator and an error state if a user tries to proceed without making a selection.

**Comment by gnakm** [comment]
<img width="386" alt="screen shot 2017-03-06 at 11 14 47 am" src="https://cloud.githubusercontent.com/assets/13420618/23618372/28a6f844-025e-11e7-95ff-4b3c47c47660.png">
<img width="388" alt="screen shot 2017-03-06 at 11 14 54 am" src="https://cloud.githubusercontent.com/assets/13420618/23618373/28a9a742-025e-11e7-8c23-778685dd5842.png">

**Comment by KHarshawat-gov** [comment]
> In certain circumstances we ask the user to click a checkbox agreeing to an action before proceeding. The text here is longer than normal horizontal text but should be limited to 75 characters. The text should be indented so it doesn't flow under the checkbox. Most of the time these checkboxes should have a required indicator and should result in an error state if not checked and the user tries to proceed. 

![image](https://cloud.githubusercontent.com/assets/25437276/23618792/822db820-025f-11e7-9fd9-97ef39b2bcea.png)

![image](https://cloud.githubusercontent.com/assets/25437276/23618876/d83c463c-025f-11e7-8d7c-a0bbd33ee792.png)

**Comment by Chingujo** [comment]
@gnakm 

Updated AC's, mocks, craft links, and copy

**Comment by kierachell** [comment]
**PASSED**
Looking spiffy!
<img width="826" alt="screen shot 2017-04-03 at 9 02 09 am" src="https://cloud.githubusercontent.com/assets/18075411/24610349/3c034ad8-184c-11e7-8b97-7169fb5f539b.png">
