### ISSUE TITLE
Investigation: Correcting Request & Decision Issues on cases dispatched without any issues

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#10095]
This is a different scenario from #10060 , but some (number unknown) appeals have been dispatched without any request or decision issues. One example:

https://appeals.cf.ds.va.gov/queue/appeals/25fea1a5-e296-487b-b852-55ab4b74cd84

It is unclear why the attorney/judge combo would have not updated the issues, but it has happened at least

**Comment by aroltsch** [comment]
This appeal has no eligible request issues and hence no decision issues. Thread here:

https://dsva.slack.com/archives/C6E41RE92/p1553629472063100

**Comment by aroltsch** [comment]
Nicholas Holtz (he/him, appeals)   [3 days ago]
We need to remove issues from Appeal 2 (https://appeals.cf.ds.va.gov/queue/appeals/f859791a-59b0-483b-b116-a1e102e548a5), and delete that appeal.

Then, we need to go into Appeal 1 (https://appeals.cf.ds.va.gov/queue/appeals/25fea1a5-e296-487b-b852-55ab4b74cd84), which has already been dispatched, and add request issues and decision issues to Appeal 1. These issues will be eligible once they are no longer on Appeal 2.


1. Decision Issues to add for Appeal 1:
[{:request_issue_description=>"Evaluation of bipolar disorder with social anxiety, which was 50 percent prior to March 17, 2015, and which is currently 70 percent disabling, is continued.", :disposition=>"denied", :decision_desciption=>"Entitlement to a rating in excess of 50 percent for bipolar disorder with social anxiety, from December 29, 2011 to March 16, 2015, is denied", :diagnostic_code=>"9413", :request_issue_id=>3315},

{:request_issue_description=>"Evaluation of bipolar disorder with social anxiety, which was 50 percent prior to March 17, 2015, and which is currently 70 percent disabling, is continued.", :disposition=>"denied", :decision_desciption=>"Entitlement to a rating in excess of 70 percent for bipolar disorder with social anxiety after March 17, 2015, is denied", :diagnostic_code=>"9413", :request_issue_id=>3315},

{:request_issue_description=>"Entitlement to individual unemployability prior to March 17, 2015 is denied.", :disposition=>"remanded", :decision_desciption=>"Entitlement to TDIU prior March 17, 2015 is remanded.", :diagnostic_code=>"9413", :request_issue_id=>3314}]

2. Set request issues as decided for appeal 1

3. Soft delete decision issues for appeal 2, set request issues as ineligible for appeal 2, cancel all tasks associated with appeal 2
