### ISSUE TITLE
Change the location pilot notification bar

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#101]
This looks wayy better. Make sure it's 508 compliant.

![image](https://cloud.githubusercontent.com/assets/6335546/10856369/abab09f8-7f1d-11e5-8e59-102043ffe5b7.png)

**Comment by KHarshawat** [comment]
@plusjeff @paultag

**Comment by alex** [comment]
@KHarshawat What's the interplay between this and #106, should we just do this for the short term?
