### ISSUE TITLE
Cannot delete contention connected to an issue in ratings

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10102]
The contention is connected to an issue in ratings and cannot be deleted.  Removing Contention failed. System error.

Sentry alert
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4164/events/279664/

**Comment by leikkisa** [comment]
I looked at one instance of this. The Request Issue does not have any decision issues, and none of the Veteran's rating issues that we're getting back have the same contention_reference_id. So at first glance, it does not seem to be caused by the contention getting a new rating issue, unless it is not getting returned to us.

**Comment by pkarman** [comment]
#10099 improves the error message (one small step)

**Comment by pkarman** [comment]
The case of RequestIssue `11152` on RequestIssuesUpdate `264` is that the issue has a DTA Error disposition on it already.

**Comment by leikkisa** [comment]
The End Product got cleared on the 26th, but the status didn't get synced until the 27th, and the issue removal was on the 26th, so maybe we need to sync the EP before loading the edit page. Once an EP is cleared, they can't edit anymore.

**Comment by pkarman** [comment]
> maybe we need to sync the EP before loading the edit page

yes that makes sense, and is consistent with what we already did at intake start in #9519

**Comment by Sjones352** [comment]
@pkarman can you please provide instructions on how I can test this in UAT?

**Comment by pkarman** [comment]
Validation would be very similar to #9519

* create a claim review.
* look the console for the claim review's UUID
* clear or cancel its EP in VBMS
* attempt to edit the claim review e.g. `/higher_level_reviews/:uuid/edit`
* confirm you get a message saying it cannot be edited.

**Comment by Sjones352** [comment]
Going to wait for the sync job before I can try to edit it
<img width="1678" alt="Screen Shot 2019-04-09 at 6 15 48 PM" src="https://user-images.githubusercontent.com/23080951/55838815-b44cde00-5af3-11e9-9bd2-1d85fb0c6887.png">

**Comment by pkarman** [comment]
@Sjones352 the point is *not* waiting for the sync job. It should sync automatically when you try and edit it.

**Comment by Sjones352** [comment]
This how I did it and it can actually be edited
<img width="1387" alt="Screen Shot 2019-04-09 at 6 55 00 PM" src="https://user-images.githubusercontent.com/23080951/55840309-06dcc900-5af9-11e9-9208-970fafb5711e.png">

<img width="1680" alt="Screen Shot 2019-04-09 at 6 54 43 PM" src="https://user-images.githubusercontent.com/23080951/55840308-06443280-5af9-11e9-9c05-75e2082dd903.png">

<img width="1504" alt="Screen Shot 2019-04-09 at 6 55 55 PM" src="https://user-images.githubusercontent.com/23080951/55840344-25db5b00-5af9-11e9-9b7e-e7ac8d800699.png">

<img width="1450" alt="Screen Shot 2019-04-09 at 6 57 20 PM" src="https://user-images.githubusercontent.com/23080951/55840427-57542680-5af9-11e9-8fb8-b960b4ceeec5.png">

**Comment by pkarman** [comment]
ah ok I was wrong in my validation instructions. I didn't realize that "CAN" and "CLR" are treated differently in Caseflow.

Instead of this step:

> clear or cancel its EP in VBMS

we should

> clear its EP in VBMS

**Comment by Sjones352** [comment]
**Passes UAT** 

<img width="1677" alt="Screen Shot 2019-04-11 at 2 31 16 PM" src="https://user-images.githubusercontent.com/23080951/55982398-d6b33880-5c66-11e9-8439-cb1a2b1d002a.png">
<img width="1436" alt="Screen Shot 2019-04-11 at 2 32 34 PM" src="https://user-images.githubusercontent.com/23080951/55982399-d6b33880-5c66-11e9-8780-af20cf5714ba.png">
