### ISSUE TITLE
Create a Looker alert to alert us when there are no decision issues at Dispatch or Quality Review

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#10107]
AC:
Create a Looker alert to notify when there appeals with BvaDispatchTasks or QualityReviewTasks and have no decision issues
Alert check runs every day at 10am

**Comment by nemodjuric** [comment]
@aroltsch Should alert go to Slack? Which channel?

**Comment by nemodjuric** [comment]
Look and scheduled alert created: https://caseflow-looker.va.gov/looks/174
