### ISSUE TITLE
Intake | Reverse sort intake user stats newest to oldest

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10101]
The /intake/manager page should sort user stats newest to oldest.

**Comment by Sjones352** [comment]
@pkarman this has already been done.
<img width="1533" alt="Screen Shot 2019-04-01 at 6 40 34 PM" src="https://user-images.githubusercontent.com/23080951/55364188-affa4280-54ad-11e9-8fb2-71ab981e088c.png">

**Comment by pkarman** [comment]
![Screen Shot 2019-04-02 at 7 24 16 AM](https://user-images.githubusercontent.com/1205061/55402154-5a0eb480-5518-11e9-8c99-882ab08e2b8c.png)

thanks @Sjones352 -- confirmed in UAT
