### ISSUE TITLE
Motion to Vacate | Backfilling Cases Processed Prior to Release

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10105]
An AMA Motion to Vacate and new decision were issued manually because Caseflow functionality to support motions was not yet ready. When we have that functionality in place, we need to backfill the information for this case - https://appeals.cf.ds.va.gov/queue/appeals/29dc1b65-ebab-4aef-b2bb-0c65af4dd222

**Comment by alisan16** [comment]
cc @msj0nes @leikkisa

**Comment by leikkisa** [comment]
@msj0nes Do you know if there's a person that we can ask more about the case that needs to be backfilled?  I think we'll need information about the issues being vacated, the decisions, the decision documents, etc.  I would suggest including it in the pilot, but not sure if it makes sense to go through the task moving around to attorneys and judges and dispatch new decisions if it's already done.

This is from a year ago too so there may be other cases in this category.

**Comment by msj0nes** [comment]
Closing this ticket until the Board can provide a listing of cases that were processed using a workaround that needs to be backfilled.
