### ISSUE TITLE
Unexpected EP code in VBMS

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10109]
These all have a different claim type code in VBMS than in our End Product Establishments table. We should investigate them to see if we're creating them wrong.   This came about because they have HLR DTA codes, but do not have connected HLRs with DTA dispositions.

This may be getting changed manually by the user in VBMS, but we should confirm that we created the claim with the intended code.  If it is changed by the user, we should think about whether that should bring about any additional action on our end.

70893703 - Created by CSFLOW, Claim source: efolderexpress
70857183 - Created by CSFLOW, claim source: efolderexpress
70930324 - Created by USER, claim source: efolderexpress
71066365 - Created by USER, claim source: efolderexpress

**Comment by leikkisa** [comment]
I believe this is due to user error. The logs do not include the claim_hash sent to VBMS, but I did review the code and the other EPEs with the same codes to make sure it wasn't a systematic error.

While investigating, I noticed that some with the code "040BDE" have changed to "040BDER" which is expected due to the new codes we received, but recent ones should get "040BDER" from the get go in our End Product Establishments table, so I'm going to keep an eye on that.

**Comment by leikkisa** [comment]
For the ones that started as 040BDE, I'm guessing that the user meant to change it to 040BDER or 040BDENR, because we got instructions to stop using 040BDE.

**Comment by pkarman** [comment]
Let's do 2 things:

* [ ] write a script to compare existing EPE and EP codes
* [ ] add a Sentry logging error on sync when we encounter it, to create a little noise for ourselves

**Comment by leikkisa** [comment]
We have confirmed how this is happening.

Closing - A new ticket has been made for this:
https://github.com/department-of-veterans-affairs/caseflow/issues/9784
