### ISSUE TITLE
undefined method `update' for nil:NilClass in app/models/tasks/disposition_task.rb 

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10113]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4160/

**Comment by monfresh** [comment]
This is because the `mark_postponed` method in `DispositionTask` is assuming a DispositionTask will always have a hearing. However, that seems to be contradicted by the fact that we allow nil hearings at the top of the class:
```ruby
delegate :hearing, to: :hearing_task, allow_nil: true
```

**Comment by sharonwarner** [comment]
As these sentry alerts come up, we need to fix the data. It should be same to assume a hearing task has a hearing association at this point.
