### ISSUE TITLE
Add additional backend validation for Veteran validation on Appeals

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10119]
Related: #9871
This applies only to Appeal issues which are eventually processed in VBMS (compensation and pension).

The user is prevented from submitting a review when the Veteran is missing information by disabling the submit button.  In the past, we have had some weird edge cases where that didn't seem like enough.

Appeals will still succeed in being intaken, but if they get to the point where their board grant effectuation is outcoded and the Veteran is invalid, then it could cause an error.

**Comment by leikkisa** [comment]
We already do validation on the front-end, this is to add a second layer on the back end.  We can see if this has been a problem for any board grant effectuations so far, but I haven't heard of any.  I added the tech improvement label.

**Comment by msj0nes** [comment]
Ticket Closure. Will be addressed in a review of VBA and BVA based updates needed .
