### ISSUE TITLE
Bug: Postpone logic moved to 55 (instead of 57)

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10116]
For this case: https://appeals.cf.ds.va.gov/queue/appeals/2916606 It was postponed and the option, "Send back to Schedule Veterans" was selected, but the appeal was sent to VACOLS location 55 instead of VACOLS 57. 

From Sal: 
When sending a Veteran back to the list to be scheduled should the appeal be charged to location 55??  I thought the appeal would remain in CaseFlow.  The Veteran below was scheduled for a CO hearing and requested to be rescheduled for a Video.  I associated the mail, postponed and sent back to schedule list through the search, not on the daily docket, and the appeal moved to 55.  I charged the appeal back to location 57.

**Comment by MeredithStewart** [comment]
Another one from Sal on 4/1/19: I rescheduled the Veteran below immediately and the appeal was charged to loc 55 instead of staying in CaseFlow.  Appeal is currently charged to loc 38.
 
https://appeals.cf.ds.va.gov/cases/172763

**Comment by sharonwarner** [comment]
I've moved both these appeals back to Caseflow. My guess is that these appeals were in the wrong location before postponing, and we didn't move them anywhere while postponing. Following up with Sal next time he tries to postpone a hearing.

**Comment by MeredithStewart** [comment]
Sent an email to the Hearing Branch coordinators and let them know to check the postponement is working correctly now when they send back to the Schedule Veteran lists.

**Comment by MeredithStewart** [comment]
Tamisha confirmed that this was working.
