### ISSUE TITLE
Multiple Phone Number check issue when Veteran is sensitive

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10112]
When checking for multiple phone numbers, checking if there is an access_error on the Veteran is raising an exception for a sensitive Veteran.

For sentry errors:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3908/events/279693/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4849/

**Comment by msj0nes** [comment]
Closing ticket . Last alert was Jul 20, 2019 7:29:49 PM EDT. Reopen ticket if issue resurfaces
