### ISSUE TITLE
Hearing Prep Refactoring - Daily Docket and Schedule View

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10139]
## User Stories
As a judge, I need to see the the Daily Docket listed in a way that is easy to read and lists all the information I need for the day at a glance.

As a judge, I need to be able to see my schedule with a complete list of hearing days. I need the option to focus on my schedule first and then filter to see other judges second. 

As a judge, I need the ability to mark my hearings with dispositions, add notes, and grant AOD status if necessary.

## Mocks
https://va-gov.invisionapp.com/share/PMR1ID7XSHT

## Acceptance Criteria
**Schedule View**
- [x] Verify the Schedule view lists AMA and Legacy video, CO, and travel board hearings that are by default filtered by that judge. 
- [x] Verify the judge has the ability to clear filters and see the entire schedule ahead of time
- [x] Verify judges see all upcoming hearing days even if they are not yet scheduled with Veterans
- [x] Verify judges can download their schedule
- [x] Verify judges can filter their views by date range

**Daily Docket**
- [ ] Verify the header of the Daily Docket matches the header of the Hearings Management Daily Docket and includes hearing location information 
- [ ] Verify the Appellant/Rep and Time/RO information mirror the HM Daily Docket and display if the case is a paper case
- [ ] Verify AMA cases have an AOD and AOD reason drop down
- [ ] Verify Legacy cases have an AOD and AOD reason drop down, and a Hold Open drop down
- [ ] Verify the placement of the drop downs and notes field follow the mocks 

## **Project Justification & Schedule:** 
* Since the introduction of Caseflow Hearing Schedule, there has been increasing issues, support tickets, and issue with VACOLS Travel Board between hearing data between Hearing Prep and Hearing Schedule. Hearing Prep needs to be refactored so that it can match Caseflow Hearing Schedule so that everyone will have the same data and have better stability by using the same code base. Discrepancies between applications will be reduced. 
* Hearing Prep can be refactored quickly and without waiting weeks and months if we can remove support for VACOLS Travel Board Hearing days in Hearing Prep. This is the needed path forward in order to holistically address the problem. 
* **Schedule**: Hearing Prep can be refactored this sprint & next (starting Thurs. April 11), if we can determine that Travel Board can be removed from Hearing Prep. If it can't be removed and we also need to include Travel Board, then it needs to wait until May and would take longer and more planning (because of VACOLS integrations). The user impact during refactor would be minimal, with the exception that when it goes live, they will lose Travel Board.

**Comment by sharonwarner** [comment]
Broke into separate tickets. #10410 #10409
