### ISSUE TITLE
Intake | cannot create decision issue

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10145]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4073/events/281400/

RequestIssue::ErrorCreatingDecisionIssue

Request Issue cannot create decision issue due to not having any matching rating issues or contentions

Affected IDs include:

* 7146
* 10838
* 10440
* 8794
* 7454
* 9311
* 9310
* 9312
* 7144
* 11241

These are all either nonrating or unidentified request issues.

**Comment by pkarman** [comment]
research:

request issue 7146 has contention 87227327 with no disposition on it yet

**Comment by pkarman** [comment]
thread in https://dsva.slack.com/archives/CFBLH2LR4/p1553549625001400

**Comment by pkarman** [comment]
This continues to be an issue https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4073/events/300923/

**Comment by shanear** [comment]
I spoke with Jane about this this morning and she said most of these are claims that had decisions, but were incorrectly cleared, because the RAMP process was to clear the EP and manually create the 040. Because this will cause a good amount of data corruption, She and I both believe we should attempt too backfill them.

**Comment by leikkisa** [comment]
Update: we have delivered a list of these contentions, and Jane is planning on having a special project for DROs to collect data for them and then we'll have them backfilled in VBMS.

**Comment by leikkisa** [comment]
I'm closing this ticket, the ErrorCreatingDecisionIssue is an error we throw every time we check if there are decision issues for a request issue.  See #12792 for silencing the Slack alert, and #12225 for investigating the expired decision issue sync jobs.
