### ISSUE TITLE
Intake | Duplicate EP exists

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10148]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4205/events/281398/

Claim not established. A duplicate claim for this EP code already exists in CorpDB. Please use a different EP code modifier. 

RAMP intake is failing to identify duplicate modifiers during the intake process, and then failing during establishment.

**Comment by pkarman** [comment]
Ramp Refiling 3948 has `nil` modifier on its EPE.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4158/events/281976/

**Comment by pkarman** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4157/events/282034/

Happens during /intake/:id/complete PATCH request

**Comment by leikkisa** [comment]
It looks like we haven't seen this error in a while for RAMP, and we've made some other changes to this code, so I'm going to close this, and we can re-open if it comes up again.
