### ISSUE TITLE
Add protections to ensure that there is a 1:1 association between Hearings and HearingTasks

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10152]
We have a [`has_one` association](https://github.com/department-of-veterans-affairs/caseflow/blob/97fde32d60c9fc2ad64d22c1655f04931a2da655/app/models/hearing.rb#L10) between a `Hearing` and a `HearingTask`. It's not clear how Rails enforces this association and it [doesn't look like a constraint on the database exists](https://github.com/department-of-veterans-affairs/caseflow/blob/97fde32d60c9fc2ad64d22c1655f04931a2da655/db/schema.rb#L517) to enforce this.

Add more conditions to ensure we don't end up in a situation where we have more than one hearing associated with a hearing task, or vice-versa.

**Comment by sharonwarner** [comment]
We should be able to add unique constraints for (hearing & hearing type) & task in the hearing task association table.

**Comment by lomaxap** [comment]
also need to investigate whether or not production data currently violates this constraint

**Comment by tomas-nava** [comment]
Confirmed that no production data would violate this constraint with this query in Looker:

```sql
SELECT hearing_type, hearing_id, hearing_task_id, COUNT(*) AS count FROM hearing_task_associations GROUP BY hearing_type, hearing_id, hearing_task_id ORDER BY count DESC;
```

**Comment by tomas-nava** [comment]
Whoops, @lomaxap pointed out that my constraint was too narrow. There are 17 `LegacyHearing`s that have more than one `HearingTaskAssociation` pointing to them.

```sql
SELECT hearing_type, hearing_id, LISTAGG(id, ', ') AS association_ids, COUNT(*) AS count FROM hearing_task_associations GROUP BY hearing_type, hearing_id HAVING count > 1 ORDER BY hearing_id;
```

| hearing type | hearing id | association ids | count
| --- | --- | --- | --- |
| LegacyHearing | 84987 | 10162, 54 | 2 |
| LegacyHearing | 87462 | 5843, 928 | 2 |
| LegacyHearing | 87522 | 10329, 937 | 2 |
| LegacyHearing | 88564 | 1295, 3628 | 2 |
| LegacyHearing | 88855 | 1990, 1447 | 2 |
| LegacyHearing | 89592 | 1957, 5473 | 2 |
| LegacyHearing | 89601 | 1963, 1962 | 2 |
| LegacyHearing | 92199 | 4255, 3170 | 2 |
| LegacyHearing | 94618 | 4282, 4883 | 2 |
| LegacyHearing | 95069 | 4448, 4447 | 2 |
| LegacyHearing | 96710 | 10942, 5178 | 2 |
| LegacyHearing | 99981 | 6724, 10788 | 2 |
| LegacyHearing | 101424 | 10916, 7354 | 2 |
| LegacyHearing | 107249 | 11931, 9774 | 2 |
| LegacyHearing | 110215 | 11170, 12119 | 2 |
| LegacyHearing | 112616 | 12092, 12093 | 2 |
| LegacyHearing | 112661 | 12113, 12112 | 2 |
