### ISSUE TITLE
Intake | User attempts to edit decision document claim

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10165]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3964/events/282240/

Claim_id is for a decision document https://appeals.cf.ds.va.gov/higher_level_reviews/71111666/edit

**Comment by laurjpeterson** [comment]
We want VBMS to change the Edit in Caseflow link to respect that some things cannot be edited in Caseflow. There is another ticket already for this, so closing.
