### ISSUE TITLE
Intake | Make request_issues.veteran_participant_id not null

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10169]
Prevent nil values in `RequestIssue.veteran_participant_id`.

**Comment by leikkisa** [comment]
Add a database constraint, backfill data before migrating the database

**Comment by leikkisa** [comment]
@pkarman Can we delegate this to the decision_review's Veteran instead, so it'll still be there if you're looking at a request issue in the console, but we don't store it on request_issues?

**Comment by pkarman** [comment]
It's fine with me to drop the column completely, but it was added to support this query:

https://github.com/department-of-veterans-affairs/caseflow/pull/8301/files#diff-c6fb660217091ee173ec081ec17c29e6R180

so we'd need to change any queries that depend on it to use a `join` instead, since `delegate_to` won't work at the SQL level.

**Comment by leikkisa** [comment]
I'm closing this ticket, it hasn't come up as a problem.  It looks like it's only null when there's no decision review (the decision review got deleted).  The few request issues like this that do have created at dates are from 2018, before launch. We might want to ask about removing those separately (there are also claimants that no longer have decision reviews).
