### ISSUE TITLE
Caseflow headers have blue text

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1017]
I'm not positive, but this looks like a bug.

**Comment by cmgiven** [comment]
Link styles taking precedence, perhaps?

**Comment by lakohl** [comment]
Bug!

**Comment by kierachell** [comment]
Not finding any blue headers on `uat`

**Comment by shanear** [comment]
@mdbenjam please add screenshots or more information.

**Comment by mdbenjam** [comment]
Okay, I don't know why I didn't add a screenshot when I filed this. But I think the App Header was a link that was blue. This is no longer the case. Closing.
