### ISSUE TITLE
Handle processed_in_caseflow DTA errors

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10171]
Add "processed_in_caseflow" version of DTA error disposition to list of DTA error dispositions.

There are currently no instances of this in prod.

**Comment by leikkisa** [comment]
Oh, I shouldn't validate this one, but I was trying to validate another one, and created: HLR 1326 with an education issue, and made a decision on it, and it created the remand SC 451

**Comment by Sjones352** [comment]
**Validated in UAT and it passes**
![Screen Shot 2019-03-28 at 8.57.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58209eeb97c65e0e00e4cfa6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456fb6b7191a370f1172c4f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19141c95df348e94f54a41a3364e2772431.png)
