### ISSUE TITLE
Get payee_code from claimant information

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10173]
Currently the payee_code for Appeal DTAs is getting set from decision_issue.prior_payee_code, which uses the payee_code for the same participant from a previous end product.  If the previous end_product is not available, we should check if the claimant has a payee_code available and use that.  If that is not available, the current behavior (the "No payee code" error) should continue.

Currently, BGSService uses fetch_claimant_info_by_participant_id, which calls find_general_information_by_participant_id and returns the relationship, we should add the payee_type_code to the result so that it is available.

**Comment by pkarman** [comment]
@leikkisa ideas on validation steps?

**Comment by leikkisa** [comment]
Lol, I found a test Veteran with 24 relationships (3 spouses, 21 children)
### Validation instructions
Do an appeal intake for:
UAT Veteran: 700013444

Select anyone that is not the Veteran as the claimant.

Then we'll need to create a remand decision on the request issue, and see if the payee_code gets populated on the claimant for the remand Supplemental Claim.

**Comment by leikkisa** [comment]
Colin says that he does not have the ability to do this.

**Comment by leikkisa** [comment]
I am going ahead and closing this - see comment above.
