### ISSUE TITLE
Issues contesting decisions on previous non rating issues show up as rating issues.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#10187]
In the scenario where a veteran contests a decision on a previous nonrating request issue, the resulting request issue will register as a __rating issue__ instead of a __nonrating issue__. We should fix this.

**Comment by Sjones352** [comment]
@leikkisa can you please provide validation instructions

**Comment by leikkisa** [comment]
#### Validation
Hopefully this works

- Do a Supplemental Claim Intake for UAT Veteran 123458318
- Contest the issue with this information:
    - Decision date: 2018-11-19
    - Text: Evaluation of Ptsd, which is currently 30 percent disabling, is continued.

Check the resulting request issue in the console, and check that it's rating.
RequestIssue.find_by(contested_decision_issue_id: 1).rating?
RequestIssue.find_by(contested_decision_issue_id: 1).nonrating?

**Comment by Sjones352** [comment]
**Passes Uat**
The request issue does not register as a rating issue but  a nonrating issue.

![Screen Shot 2019-04-19 at 3.38.17 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/05c7df4f-be7c-4b7b-82a7-4d6b571251ff)
![Screen Shot 2019-04-19 at 3.40.13 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/ca7ec73f-f0d5-4d1a-890b-189f26f0d0ac)
