### ISSUE TITLE
EP Creation | Update EP labels for Partial Grants and Remands - EPs routed to RO

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1018]
As a Caseworker, I would like to have the "EP & Claim Label" value determined by the "Decision Type" and destination, so that partial/remand EPs created at ARC and EPs created at the ROs can be distinguished from one another.

## Acceptance Criteria
1. Verify that the when the value of "Decision Type" is "Full Grant" on the Decision Review page, the "EP & Claim Label" value is set to `172BVAG - BVA Grant` on the End Product page (no change)
1. Verify that the when the value of "Decision Type" is "Remand" on the Decision Review page, and the EP is being routed to an RO station, the "EP & Claim Label" value is set to `170RMD - Remand` on the End Product page.
1. Verify that the when the value of "Decision Type" is "Partial Grant"on the Decision Review page, and the EP is being routed to an RO station, the "EP & Claim Label" value is to `170RBVAG - Remand with BVA Grant` on the End Product page.
1.Verify that the "EP & Claim Label" field cannot be edited and grayed out.

Related stories
https://github.com/department-of-veterans-affairs/caseflow/issues/623
https://github.com/department-of-veterans-affairs/caseflow/issues/1019

**Comment by kierachell** [comment]
**PASSED**
## Remands that turns into a Partial Grant or whatever
![screenshot_2017-03-07_16-01-00](https://cloud.githubusercontent.com/assets/18075411/23678852/b46bebc8-0353-11e7-8605-2e5207cc1da7.png)
## Full Grant
![screenshot_2017-03-07_15-48-16](https://cloud.githubusercontent.com/assets/18075411/23678884/c748a1d2-0353-11e7-9c13-20c658942ca3.png)
## Remand Remand
![screenshot_2017-03-07_16-22-43](https://cloud.githubusercontent.com/assets/18075411/23678895/d22b050e-0353-11e7-8972-40f2b91d1471.png)
