### ISSUE TITLE
BUG: Veteran shows on wrong hearing day in Hearing Prep for 4/2

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10199]
Judge sees a false hearing day in Hearing Prep for 4/2/19 -- https://appeals.cf.ds.va.gov/hearings/dockets/2019-04-02 

This Veteran shows up on Hearing Schedule Daily docket for: https://appeals.cf.ds.va.gov/hearings/schedule/docket/128, which is correct. 

This hearing was previously the one that was Manila RO and was showing up incorrectly. We can't update the time to correctly show.  

Bottom line - Hearing Schedule is correct, but Judge sees this Veteran on the wrong day.

**Comment by MeredithStewart** [comment]
Related support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/4550

**Comment by sharonwarner** [comment]
I updated the hearing in VACOLS so that it's now the correct date. It shouldn't show up on 4/2 for that judge anymore.
