### ISSUE TITLE
EP Creation | Update EP labels for Partial Grants and Remands - EPs created at ARC

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1019]
As a Caseworker, I would like to have the "EP & Claim Label" value determined by the "Decision Type" and destination, so that partial grant/remand EPs created at ARC and EPs created at the ROs can be distinguished from one another.

## Acceptance Criteria
1. Verify that the when the value of "Decision Type" is "Full Grant" on the Decision Review page, the "EP & Claim Label" value is set to `172BVAG - BVA Grant` on the End Product page (no change)
1. Verify that the when the value of "Decision Type" is "Remand" on the Decision Review page, and the EP is created at ARC's station, the "EP & Claim Label" value is set to `170RMDAMC - ARC-Remand` on the End Product page 
1. Verify that the when the value of "Decision Type" is set to "Partial Grant"on the Decision Review page, and the EP is created at ARC's station, the "EP & Claim Label" value is set to `170PGAMC - ARC-Partial Grant` on the End Product page.
1. Verify that the "EP & Claim Label" field cannot be edited and grayed out.

Related stories
https://github.com/department-of-veterans-affairs/caseflow/issues/623
https://github.com/department-of-veterans-affairs/caseflow/issues/1018

**Comment by shanear** [comment]
@tejans24 this is really similar to #1018, I'm going to assign it to you cause you may be able to do both in one swoop.

**Comment by kierachell** [comment]
**PASSED**
## Full Grant
![screenshot_2017-03-07_15-48-16](https://cloud.githubusercontent.com/assets/18075411/23677295/8de7ac86-034d-11e7-926d-dfb18efc7220.png)

## Partial Grant

![screenshot_2017-03-07_16-00-44](https://cloud.githubusercontent.com/assets/18075411/23678065/879fc6c6-0350-11e7-86d2-114851ad934e.png)

## Remand
![screenshot_2017-03-07_16-14-47](https://cloud.githubusercontent.com/assets/18075411/23678583/b9153fb8-0352-11e7-9378-2f0fb1b6dde6.png)


## BONUS: Remand with BVA Grant!
![screenshot_2017-03-07_16-01-00](https://cloud.githubusercontent.com/assets/18075411/23678055/81269068-0350-11e7-9f90-e5ba8c050ec0.png)

## BONUS: Another remand?
![screenshot_2017-03-07_16-22-43](https://cloud.githubusercontent.com/assets/18075411/23678597/c614b158-0352-11e7-9cae-f0ce7df3eae3.png)
