### ISSUE TITLE
Check for Incident Flash on Intake start

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10203]
Incident Flash is a temporary lock on a Veteran record that prevents new claims from being established.

We should check for the presence of that Flash when an intake starts, similar to our checks for other valid Veteran attributes.

## AC

If Veteran has an Incident Flash on their record, halt the intake and present user with error message about contacting {{TODO identify contact}} to remove the incident flash lock.

**Comment by leikkisa** [comment]
We are waiting for an update from Nate about this.

**Comment by leikkisa** [comment]
Notes from an email:
From Colin: We have a case in production with the 2x CADD flash, which prevents address updates. However, claim establishment is allowed. I tested this in prodtest against the record in VBMS and it established properly.

From Peter: Error is coming from VBMS API

From Joe: This is an existing issue in general for VBMS CEST, not specifically the External Claim Service (claims api). There appear to be a variety of downstream address issues between VBMS CEST and FAS which will still trigger this error message.

Existing defect:
BGS GUIDs when attempting to CEST in VBMS.  Failed with Exception!! ( INC1948403 ) (714927)
https://rtc01.aide.oit.va.gov/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/714927

**Comment by leikkisa** [comment]
Script for finding these:
```drs=HigherLevelReview.where.not(establishment_error: nil).select{|dr| dr.establishment_error.include?("Incident")} + SupplementalClaim.where.not(establishment_error: nil).select{|dr| dr.establishment_error.include?("Incident")}.map(&:veteran_file_number)```

**Comment by leikkisa** [comment]
I sent an email for the following Decision Reviews to request to lift the incident flash restriction temporarily.
VAVBAWAS/CO/IncidenteBenefitsNotification
IncidenteBenefitnotification.VBAVACO@va.gov

SCs - [28454, 32159, 18427, 14179, 19915, 31693, 25425, 8660, 5378, 25377, 4465, 31866, 31874, 22006, 17335, 24865]

HLR - 4976

**Comment by leikkisa** [comment]
The actual email to send these to is IncidentTeam.VBASLC@va.gov (VAVBASLC/RO/VBAIncidentTeam), so that an encrypted email with the veteran SSNs can be sent.

The instructions should include the user contacting the veteran to confirm that it's a valid request, because these veteran's have been previous victims of fraud.

[https://app.zenhub.com/files/51449239/32b3602c-a242-4f70-bdb8-a2c37015e995/download](https://app.zenhub.com/files/51449239/32b3602c-a242-4f70-bdb8-a2c37015e995/download)

**Comment by pkarman** [comment]
@leikkisa if you pick this up feel free to push/fork the branch/PR I started. Just added you as a reviewer.

**Comment by Sjones352** [comment]
@leikkisa can you please provide instructions on how I can validate this.

**Comment by leikkisa** [comment]
@Sjones352 We can only validate this in prod. We could validate it by trying to do an intake for for a known veteran with an incident flash. Veteran ID 282884 is one example.  It should prevent continuing with the intake for that veteran with an error message.
