### ISSUE TITLE
Contention not found on RequestIssuesUpdate

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10213]
Examples:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4207/events/286758/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4207/events/286699/

I suspect these are because the contentions are being worked manually in VBMS.

e.g. missing contention `87867502` on request issue `15453` but there is a contention `87869320` with identical text that is not referenced in Caseflow at all but is assigned to the EP for that request issue.

It might be worth automating this kind of investigation in the model itself and displaying some potential fixes when the exception is thrown. That would save us time at least, and might spur some patterns that could be fixed.

**Comment by msj0nes** [comment]
Ticket closure. Sentry alerts for Intake over a yr old will be closed.
