### ISSUE TITLE
Bug: 3 AMA appeals no RO/tasks, but need to be scheduled

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10219]
In the list of AMA Veterans we've provided to the branch to schedule through May 2019, three appeals don't have an RO associated and don't have Schedule Veteran tasks to complete through search:  

1. appeals/cee54423-40ee-4f18-9d0d-3cc1adc96237 (says it's assigned to American Legion) 

2. appeals/2d4dc91d-5393-4d40-9159-94ad95958d87 (says it's in case storage) 

3. Last one doesn't load -- says there's no case for that number in search. (Meredith can provide to whoever picks up this ticket)

**Comment by sharonwarner** [comment]
I found 7 AMA hearings appeals that don't have any distribution task or schedule hearing task. They all have fairly low IDs, my guess is that they were intaked before we had the Schedule Hearing Task logic in place, and the backfill missed them for some reason. Will backfill with the following commands: 

```
appeal_ids = Appeal.includes(:tasks).where(docket_type: "hearing").select { |appeal| !appeal.tasks.pluck(:type).include? DistributionTask.name }.pluck(:id)

appeal_ids.each do |appeal_id|
  appeal = Appeal.find(appeal_id)
  RootTask.create_subtasks!(appeal, appeal.root_task) 
end
```

**Comment by sharonwarner** [comment]
Six out of the 7 AMA appeals that didn't have ScheduleHearingTasks were BEAAM appeals. Chris's script will have to be modified to not return BEAAM appeals. 

The remaining AMA appeal (313) with no ScheduleHearingTask was a duplicate. The duplicate has been deleted, and I created a DistributionTask, HearingTask, and ScheduleHearingTask.

**Comment by MeredithStewart** [comment]
-- Create new ticket, these now have Schedule Veteran tasks, but aren't showing up in list of Veterans to schedule.
