### ISSUE TITLE
Remove improperly intaken appeal

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#10236]
Please remove https://appeals.cf.ds.va.gov/queue/appeals/3d268dff-ebfc-4d4d-9aad-750b620dead0 as it should not have been intaken at the Board.

Please also remove - https://appeals.cf.ds.va.gov/queue/appeals/33ecd291-f482-46e3-ba86-5bf57824c13e
- from support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/4527

**Comment by laurjpeterson** [comment]
Sierra is working on removal and withdrawal of appeals. Since it's closer, can we wait to use that functionality to remove this appeal and its issues?

**Comment by laurjpeterson** [comment]
I'd like @pkarman to weigh in. 

Option 1: delete this improperly intaken appeal now/this week using the method alex has been using
Option 2: remove this improperly intaken appeal using new remove/withdraw functionality

@pkarman - your best guess, when do you think we'd be ready to do option 2? if in longer than 2 weeks, would you be willing to delete this appeal instead?

**Comment by pkarman** [comment]
It's going to be longer than 2 weeks.

Happy to remove according to whatever method @amprokop has been using.

**Comment by laurjpeterson** [comment]
thanks @pkarman. 

@amprokop - can you share your method (or point us to where you shared it before)?

**Comment by laurjpeterson** [comment]
There is another appeal reported in a support ticket that needs to be removed - https://github.com/department-of-veterans-affairs/appeals-support/issues/4527

I've also had email traffic with LRP and the attorney about this.

I asked the attorney to wait until we had the removal functionality in place, but if we are deleting the appeal in the original comment, I'll add this one too.

**Comment by amprokop** [comment]
K, i'll delete both

**Comment by pkarman** [comment]
via DM
```ruby
def destroy_appeal(appeal)
    puts "Deleting appeal with file_number #{appeal.veteran_file_number} and id #{appeal.id}..."
    appeal.appeal_views.destroy_all
    appeal.claims_folder_searches.destroy_all
    appeal.tasks.destroy_all
    appeal.request_issues.destroy_all
    appeal.decision_issues.destroy_all
    appeal.special_issue_list.destroy if appeal.special_issue_list
    appeal.destroy
    puts "Deleted."
end
```

**Comment by amprokop** [comment]
Done
