### ISSUE TITLE
Error getting appeal hearing

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#10230]
There was an error getting a particular appeal's hearing when trying to set the most recently held hearing for that appeal (triggered in HearingBadge component). Here is the link to the Sentry alert for this error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/.

Not sure if it is related to the appeal in question or some other issue, but either way we might want to handle an error response for this request, which we're not doing now: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/HearingBadge.jsx#L48.

**Comment by hschallhorn** [comment]
Did some digging through our aws logs and  found where this 500 came from
`
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] [2019-04-01 10:06:52 -0400] ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use):
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] [2019-04-01 10:06:52 -0400]
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] [2019-04-01 10:06:52 -0400] app/models/user.rb:327:in `find_by_css_id_and_station_id'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] app/models/user.rb:311:in `from_session'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] app/controllers/application_controller.rb:67:in `current_user'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] app/controllers/application_controller.rb:247:in `set_timezone'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] app/middleware/metrics_collector.rb:16:in `call'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] app/middleware/metrics_auth.rb:12:in `call'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] [2019-04-01 10:06:52 -0400] Processing by ErrorsController#show as JSON
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] [2019-04-01 10:06:52 -0400]   Parameters: {"appeal"=>{}, "appeal_id"=>"3181265", "status_code"=>"500", "error"=>{"appeal"=>{}}}
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c6e73023416d6a0c [appeals.cf.ds.va.gov] [ed7534b7-79d0-4d0d-aa1f-769ef924a02a] [172.30.83.17] [VACOPEDENN neely.peden@va.gov] [2019-04-01 10:06:52 -0400]   Rendering errors/500.html.erb within layouts/application`

**Comment by aroltsch** [comment]
Nice find @hschallhorn. Let's close this ticket. We need to implement patch processing for hearings and documents endpoints and see if it helps.

**Comment by annekainicUSDS** [comment]
Just FYI we got another one of these alerts this afternoon: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/activity/

**Comment by hschallhorn** [comment]
`ConnectionTimeoutError`s from Kibana: https://caseflow-kibana.va.gov/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(columns:!(_source),index:'*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:ConnectionTimeoutError)),sort:!('@timestamp',desc)) . Looks like we had a bunch in the last hour
