### ISSUE TITLE
Implement a retry mechanism on BGS transient error 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#10235]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3325/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3171/

Follow the example Intake implemented: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/exceptions/bgs_sync_error.rb#L48

1. Catch TransientBGSSyncError
2. Retry the request

**Comment by monfresh** [comment]
Would it make sense to implement the retries in the BGS gem? Also, do you know what the reasoning is behind a connect timeout of 10 minutes? (https://github.com/department-of-veterans-affairs/ruby-bgs/blob/bc9c89591ac5830939476bd6eb96c1a2b415fdcb/lib/bgs/base.rb#L137) 

That means we are blocking requests for 10 minutes while we try to connect. Typically, connect timeouts should be as small as possible, in seconds. If we can't even connect to the server within a few seconds, we should retry once or twice and then abort and display a message to the user indicating part of the service is down and to  "please try again later".

**Comment by aroltsch** [comment]
Yes, we can implement a retry on the BGS side. I had a similar code in connect_vva which was removed when we implemented Envoy to retry HTTP requests. Here is the PR: https://github.com/department-of-veterans-affairs/connect_vva/pull/15/files. In theory, Envoy should retry 3 times. I know Enrique and Lisa looked into it and said Envoy should be re-trying. You could connect with them to see if there is any new development on that. 

Re: connect timeout of 10 minutes - https://github.com/department-of-veterans-affairs/ruby-bgs/pull/47. From what I remember we needed it higher for Envoy to finish its work.

**Comment by aroltsch** [comment]
Continue debugging Envoy

**Comment by aroltsch** [comment]
Closing in favor of this PR https://github.com/department-of-veterans-affairs/ruby-bgs/pull/77
