### ISSUE TITLE
Cache deceased flag on veteran

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10245]
To avoid hitting BGS during every Intake step (e.g. review) explore caching the veteran attributes we need when Intake starts.

e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4155/

**Comment by leikkisa** [comment]
Closing this ticket, because "caching" date_of_death is now a thing on the Veteran table.
