### ISSUE TITLE
Caseworker Dashboard | Establish Next Claim | Reposition button and change subtext

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1025]
As a Caseworker, I would like the location of the Establish next claim button moved and subtext changed so that it provides better information.

# Acceptance Criteria
1. Verify that the **_Establish next claim_** button has been been moved the right side of the page.
1. Verify that the **_Establish next claim_** button's subtext "[number] of claims in your queue, [number] of claims completed" has been left aligned. 

## Mockups
**_View - Caseworker Dashboard - Before_**
<img width="1029" alt="screen shot 2017-02-26 at 5 43 33 pm" src="https://cloud.githubusercontent.com/assets/4975959/23344487/605ff984-fc4b-11e6-885f-803d86b3d9e8.png">

**_View - Caseworker Dashboard - After_**
<img width="657" alt="screen shot 2017-02-26 at 5 46 02 pm" src="https://cloud.githubusercontent.com/assets/4975959/23344499/94aa0edc-fc4b-11e6-880a-611d58cc3981.png">

# Related Stories
n/a

**Comment by mmlumba** [comment]
@lakohl ,
In #868 the mocks and AC for that issue specified that both the text and the button for the Caseworker Dashboard page are placed to the right side. Would you still like both the text and the button to be on opposite sides?

**Comment by lakohl** [comment]
@mmlumba mock is correct to stay consistent with Manager view styling

**Comment by kierachell** [comment]
**PASSED**

![screenshot_2017-03-16_20-29-09](https://cloud.githubusercontent.com/assets/18075411/24024126/43f7b882-0a87-11e7-8226-316e34685c56.png)
