### ISSUE TITLE
ActiveRecord::ConnectionTimeoutError

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#10255]
This Sentry alert has gone off a few times in the past 24hr: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4040/. The alert says, "could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use". Looks like the request to look up a user by css id and station id is timing out.

**Comment by annekainicUSDS** [comment]
Another related alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4413/

**Comment by annekainicUSDS** [comment]
And this one: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4419/

**Comment by aroltsch** [comment]
Reopening.

**Comment by youngfreezyVA** [comment]
this just happened again: https://dsva.slack.com/archives/C6E41RE92/p1555445007080500

**Comment by monfresh** [comment]
And again: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4706/

**Comment by monfresh** [comment]
@aroltsch Should we try caching the `User.find_by_css_id` method, like you did recently for VACOLS?

**Comment by pkarman** [comment]
I don't think this is a problem with the `User` logic. I think that's just the first place Caseflow needs a db connection on any given request cycle so it's the place the problem shows itself.

The real problem is likely how long other queries are taking that they exhaust the number of available db connections. I will research.

**Comment by pkarman** [comment]
Some stats for Caseflow

* we have average of 150 db connections daily to our db master
* 50 connections from each of 3 instances
* 30 connections from shoryuken (Rails worker), 20 from puma (Rails web)
* max db connections is 800+ configured on the server
* last modified https://github.com/department-of-veterans-affairs/appeals-deployment/commit/85f90013aef36af342e6644de0715eb15242aafa#diff-7bdaf806e56b7fa7285006993e56b782

**Comment by monfresh** [comment]
Another instance in the IDT controller:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3757/

In that controller, we are still finding by `css_id`: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/idt/api/v1/base_controller.rb#L43

Not that it's necessarily the cause, but perhaps worth making our user lookup consistent?

**Comment by monfresh** [comment]
Another one today while fetching document count:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4671/

**Comment by lomky** [comment]
Another today https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4671/

**Comment by pkarman** [comment]
This PR may address this, since IMO this is a larger architectural issue.

https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2092

I think we're blocked on this until we can get some space to consider our AWS provisioning.

**Comment by pkarman** [comment]
this issue seems to have gone away. AWS provisioning is still an issue, and we can probably improve our db connection rate, but this particular issue is no longer of high priority.

**Comment by yoomlam** [comment]
2 occurrences in the last 2 days: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9377
