### ISSUE TITLE
Feedback Deprecation Effort | Change Feedback Behavior 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#10257]
# Proposed Solution – Low effort
The Caseflow team would like to have the Feedback Page updated to make users aware Feedback has been deprecated and the new method of submitted support tickets is via YourIT. 

### **_Proposed Date of Change_**  
May 13th, 2019 

## Acceptance Criteria
**_Introduction Section_**
1. Create a new page at `/appeals.cf.ds.va.gov/feedback`
1. When user clicks "Send feedback" from the upper right corner drop down, they navigate to `/appeals.cf.ds.va.gov/feedback` in a new tab.
1. When user clicks "Send feedback" from the link at the bottom of the page, they navigate to `/appeals.cf.ds.va.gov/feedback` in a new tab.
1. Messaging as written below exists on `/appeals.cf.ds.va.gov/feedback`
1. Verify that the hyperlink within the new messaging opens the `www.yourIT.va.gov/va` in a new window.
1. Decommission Caseflow Feedback and delete all Caseflow Feedback code. 

## Proposed Messaging

**_Having a technical difficulty?_**
Submit a ticket to the Caseflow team using [**_YourIT_**](www.yourit.va.gov/va). The YourIT link is also available on most VA issued workstations. To better assist, please ensure you provide the URL or web address associated to the issue in the ticket.

[insert screenshots of URL and YourIT]

The Caseflow Technical Support Team does **not** issue or manage access to Caseflow. Please do not submit a ticket through YourIT to the Caseflow team if you are looking for access to Caseflow or another VA product.

Access is approved and granted via email through your management team and your local CSEM Information Security Officer (ISO). Please email your management team for access guidance. 

## Mocks
**_Current Feedback Page_**

![image](https://user-images.githubusercontent.com/41164406/56664146-947df400-6675-11e9-9ddf-a039cba5de76.png)

**_Proposed Feedback Page_**
- Use templates we already have
- Use heading sizes we already have

# Related Issue
[Proposal to Transition Caseflow Support Team To ServiceNow YourIT](https://github.com/department-of-veterans-affairs/caseflow/issues/9133)

**Comment by nemodjuric** [comment]
@laurjpeterson Can you please post a mock of Proposed Feedback page?

**Comment by nemodjuric** [comment]
@laurjpeterson
<img width="1433" alt="Screen Shot 2019-05-08 at 2 44 38 PM" src="https://user-images.githubusercontent.com/4960030/57399752-e6f40000-719f-11e9-9236-e6d76d9321f8.png">

**Comment by laurjpeterson** [comment]
@nemodjuric - requesting that we add spaces between the paragraphs.

may 13 is the date we gave to BVA, so let's not deploy this until then.
