### ISSUE TITLE
NCA | Investigate Allowing Non-Veteran Claimants

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10251]
With ruby-bgs right now, we're just getting the dependents. However, for pension burial or accrued issues, the claimant might be someone other than one of the Veteran's dependents.  Update the Veteran's relationships to include other eligible claimants (e.g. nephew filing for a deceased Veteran).

There are claims (Supplemental Claims and Higher Level Reviews) that we cannot process because of this.

## Potential AC
- change ruby-bgs to remove the filter so we retrieve other eligible claimants (note: ticket in ruby-bgs repo)
- selectively apply filters in Caseflow to retrieve eligible claimants for pension burial or accrued issues

**Comment by jimruggiero** [comment]
@leikkisa Can you create two new tickets breaking out the backend work described above, link them to each other, and then we can create a new Epic to link all of these, plus the new frontend tickets (e.g. adding variants of "other" to NCA intake, etc).

**Comment by msj0nes** [comment]
# Update
Closing investigation ticket. Direction on request has been established and can be followed via #11162
