### ISSUE TITLE
Decision Review | Decision Type |  Incorrect styling

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1026]
# Description
On the `Decision Review` page, the "Decision Type" field and label have styling issues:  

1. Label should be in sentence case = "Decision type", not 'Decision Type'

**Environment:**
- [x] Production
- [x] UAT
- [x] Demo
- [x] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1 - Incorrect styling
1. Click on the **_Establish next claim_** button on the `Caseworker Dashboard`.
1. Scroll down to below the decision pdf section.  The field "Decision Type" is displayed with wrong styling.

## Screen shots
**_Scenario 1 - Decision Review page - Current_**
<img width="982" alt="screen shot 2017-02-26 at 6 17 13 pm" src="https://cloud.githubusercontent.com/assets/4975959/23368455/e9ec1896-fcdb-11e6-88c4-e6f0558bf135.png">

**_Scenario 1 - Decision Review page - Desired_**
<img width="685" alt="screen shot 2017-02-27 at 10 58 09 am" src="https://cloud.githubusercontent.com/assets/4975959/23368387/b34b6422-fcdb-11e6-8988-99c264cccc74.png">

# Related Stories
Decision Review | Don't allow changing Decision Type #803

**Comment by ariperez-gov** [comment]
@lakohl , I made changes 1 & 2 on the attached PR.  I would like to bump 3 as it contradicts label to text box spacing on other forms across the site (see pic below).

![image](https://cloud.githubusercontent.com/assets/25468798/23913300/dc5c4190-08b8-11e7-8599-8930eaa01e93.png)


There are other issues we could also address collectively through caseflow-commons.

**Comment by lakohl** [comment]
@ariperez I see your point on 3. I don't think we should start a new style. I'm trying to introduce some continuity between the label and the item(s) below it - be it a text field or checkbox. Interestingly, what's live in Certification looks a bit different spacing-wise from what's live in Dispatch.
<img width="509" alt="screen shot 2017-03-14 at 1 29 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/23913854/93917596-08ba-11e7-8757-c07de9b1c0db.png">

**Comment by ariperez-gov** [comment]
Understood.  I made a ticket for myself in Caseflow Commons and we can discuss further to make sure it's addressed:
https://github.com/department-of-veterans-affairs/caseflow-commons/issues/69

Pushing this forward for Approval and Validation.

**Comment by kierachell** [comment]
So... uh, do you want a shorter text box or no?
Currently on `uat`:
The only thing I can validate is sentence case.
![screenshot_2017-03-16_20-22-16](https://cloud.githubusercontent.com/assets/18075411/24023979/4a05d0ca-0a86-11e7-8b49-f4948e566aa5.png)
IMHO the whole thing is too close to PDF iFrame.

**Comment by lakohl** [comment]
AC Updated

**Comment by ariperez-gov** [comment]
@kierachell , I validated with @lakohl that the length of the text box is correct now, I used `usa-half-width`which lowered it by a few pixels.

that covers points 1 & 2, and we opened a separate issue for 3

**Comment by ariperez-gov** [comment]
Based on our discussion, this only validates a the sentence case.  The previously discussed below items are to be addressed by @tejans24 in https://github.com/department-of-veterans-affairs/caseflow-commons/issues/69 :

1. Text box should be 380px
1. Spacing between the text box label and text box should be increased to match the distance between 'Select Special Issues(s)' and the first special Issue checkbox.
1. There should be a minimum of 30px between the label 'Decision Type' and the Decision .pdf viewer above the label.

**Comment by kierachell** [comment]
**PASSED**
<img width="733" alt="screen shot 2017-03-18 at 7 50 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/24076952/55337af8-0c14-11e7-8483-babef33413f7.png">

**Comment by kierachell** [comment]
@ariperez 
I think I might've forgotten to mention in our discussion that one issue can have multiple pull requests attached to it; so, yes, it is possible that you would have to implement changes in Commons and Dispatch separately to complete the functionality for one issue.
