### ISSUE TITLE
Load Veteran and POA info when case details page loads

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10261]
When we [added POA information](https://github.com/department-of-veterans-affairs/caseflow/pull/7061) to the case details page we introduced a pattern where we asynchronously request information for an appeal that comes from BGS after the case details page loads in order to speed up the initial case details page load. Now that we are [making a request to BGS](https://github.com/department-of-veterans-affairs/caseflow/issues/7922) to confirm that the current user can access the appeal when the case details page loads, we should only make one request to BGS and return all information that we want to get from BGS ([POA](https://github.com/department-of-veterans-affairs/caseflow/blob/d7b2e33d5a6f6a37da92eadb7d3520ab3b84416f/app/controllers/appeals_controller.rb#L45) and [Veteran](https://github.com/department-of-veterans-affairs/caseflow/blob/d7b2e33d5a6f6a37da92eadb7d3520ab3b84416f/app/controllers/appeals_controller.rb#L77)) at the same time that we determine whether the current user has permission to view the case details page. We can do this because underneath it all [`BGSService.can_access?`](https://github.com/department-of-veterans-affairs/caseflow/blob/d7b2e33d5a6f6a37da92eadb7d3520ab3b84416f/app/services/external_api/bgs_service.rb#L176) calls the same BGS endpoint as [`BGSService.fetch_veteran_info`](https://github.com/department-of-veterans-affairs/caseflow/blob/d7b2e33d5a6f6a37da92eadb7d3520ab3b84416f/app/services/external_api/bgs_service.rb#L57).

## Acceptance criteria
* [ ] Return Veteran and POA information with the rest of the initial response to `AppealsController.show`

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||
5 | |||||
8 | 
```


#### Why 3?
- Merging two requests that already occur
- Will have to update front end requests as well

#### Why 5?
- BGS test data is pretty sparse. May be hard to set up tests and dev datas
- External dependecy I'm not very familiar with
