### ISSUE TITLE
Distinguish legacy merged + closed appeals in case timeline

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10278]
If a legacy appeal was merged in VACOLS and therefore one VACOLS record was closed, that closed appeal record's Case Timeline in Casefow is misleading. Caseflow displays the date of that merge as a dispatched BVA decision

https://github.com/department-of-veterans-affairs/appeals-support/issues/4383#event-2243616015

- Investigate if we can distinguish merge from decided appeal / if there is a decision date for this appeal accidentally
- If we can, update logic in Case Timeline (and elsewhere as needed)

**Comment by mbaenatan** [comment]
Per prioritization discussion with engineering and product, we should consolidate all case timeline tickets and create an Epic for case timeline improvements.
