### ISSUE TITLE
Error in `setSavePending`

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#10275]
We got 2 Sentry alerts about an error when trying to dispatch the action for `setSavePending`:

1. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4425/
2. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4426/

It looks like there was a failure to save something, and the response we got back was undefined, so when we check `response.text` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/uiReducer/uiActions.js#L68), it causes an error.

This has only happened twice, so is probably low priority.

**Comment by hschallhorn** [comment]
No new errors in a year
