### ISSUE TITLE
App Actions | Update buttons to sentence case

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1027]
As Product Owner, I would like to update all buttons on the Dispatch pages to sentence case so that they are in compliance with the Caseflow Styling guide.

# Acceptance Criteria
1. Verify that the following buttons have been update to sentence case:

| Page | Current Verbiage | New Button Verbiage |
| --- | --- | --- |
| Caseworker Dashboard | Establish Next Claim | **_Establish next claim_** |
| Decision Review | Route Claim | **_Route claim_** |
| Decision Review | Route Claim for Decision 1 | **_Route claim for Decision 1_** |
| Decision Review | Route claim for Decision 2 | **_Route claim for Decision 2_** |
|EP Creation| Create End Product | **_Create End Product_** |
|Existing EP | Create New EP | **_Create new EP_** |
|Route Claim - VBMS Note| Finish Routing Claim | **_Finish routing claim_** |
|Route Claim - VACOLS Note| Finish Routing Claim | **_Finish routing claim_** |
|Route Claim - Send Email | Finish Routing Claim | **_Finish routing claim_** |
|Route Claim - Unsupported | Finish Routing Claim | **_Release claim_** |
|Confirmation | Establish Next Claim | **_Establish next claim_** |

## Mockup
n/a

# Related Stories
n/a

**Comment by kierachell** [comment]
# Obligatory

![lara_decree](https://cloud.githubusercontent.com/assets/18075411/23364152/d32bb2e8-fccb-11e6-9816-5719c75b89b1.png)

**Comment by astewarttistatech** [comment]
**PASSED**

<img width="1266" alt="screen shot 2017-03-17 at 10 50 10 am" src="https://cloud.githubusercontent.com/assets/23038505/24051290/0be3f42a-0b08-11e7-946c-c15f119d4574.png">
<img width="1242" alt="screen shot 2017-03-17 at 10 50 24 am" src="https://cloud.githubusercontent.com/assets/23038505/24051289/0be2f1d8-0b08-11e7-869c-d20df0acec0d.png">
<img width="1344" alt="screen shot 2017-03-17 at 10 50 39 am" src="https://cloud.githubusercontent.com/assets/23038505/24051291/0be592b2-0b08-11e7-8369-d1901408e1b3.png">
<img width="1284" alt="screen shot 2017-03-17 at 10 53 54 am" src="https://cloud.githubusercontent.com/assets/23038505/24051292/0be66be2-0b08-11e7-941d-ae69c1a9a49b.png">
<img width="1317" alt="screen shot 2017-03-17 at 10 44 52 am" src="https://cloud.githubusercontent.com/assets/23038505/24051327/1c23c0cc-0b08-11e7-95b2-eab33a69cf8b.png">
<img width="1333" alt="screen shot 2017-03-17 at 10 45 02 am" src="https://cloud.githubusercontent.com/assets/23038505/24051326/1c23ac5e-0b08-11e7-93ce-d19e2060b972.png">
<img width="1266" alt="screen shot 2017-03-17 at 10 50 10 am" src="https://cloud.githubusercontent.com/assets/23038505/24051328/1c25f7a2-0b08-11e7-8fb6-159d1b8875d5.png">
