### ISSUE TITLE
Typo in appeals_controller

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#10279]
Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4433/. This alert caught a typo in the appeals_controller. The code should probably be: `Caseflow::Error::ActionForbiddenError`.

**Comment by aroltsch** [comment]
@annekainicUSDS is this related to what Lowell is working on?

**Comment by annekainicUSDS** [comment]
Yep, this is the ticket for the PR he has open now (linked to in this
ticket).

**Comment by aroltsch** [comment]
I missed the link! Great
