### ISSUE TITLE
Bug: Not pulling RAMP contentions into Intake

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#10286]
Case: https://appeals.cf.ds.va.gov/queue/appeals/7faadfaf-05fd-4c17-857b-c7aeeba5bed1

In this case, we are not pulling the issues/contentions from the most recent EP.

- 9/14/2017 - Service connection for PTSD was granted in 9/14/2017 rating decision
- 9/29/2017 - Vet filed appeal for IR PTSD
- 8/9/2018 - RAMP Opt-in for HLR for PTSD
- 12/11/2018 - RAMP Decision denying IR PTSD
- 1/7/2019 - RAMP selection form filing for Direct Review on IR PTSD (but Vet improperly also identifies "stomach" and "back" conditions)
- 3/25/2019 - IHP filed by rep only for IR PTSD condition

The 12/11/18 RAMP decision does not show in the Intake/Add Issues page at all. The Board has selected issues from the 9/14/2017 rating decision on that page, and they are showing up as ineligible bc of timeliness:

![image](https://user-images.githubusercontent.com/16781398/55492881-f793e200-5605-11e9-9c9d-92ba1f611b18.png)

Additionally, when marking these issues as ineligible, Caseflow is incorrectly adding a message about "decision prior to February 14, 2019" (adding the 'before_ama' message) rather than another/accurate ineligibility message:

![image](https://user-images.githubusercontent.com/16781398/55493501-075ff600-5607-11e9-9a49-f3d05934d27d.png)

**Comment by pkarman** [comment]
@shanear discovered that the receipt date was off by one year which was masking any issues that were decided after that.
