### ISSUE TITLE
Issue creating decass record

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#10292]
Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4464/

A decass record failed to be created due to a validation error, where the field `Deatty` was left blank. I don't know much about this issue, but it seems like we're missing some validation to catch that all required fields are not blank.

**Comment by hschallhorn** [comment]
None in a year, closing
