### ISSUE TITLE
Route Claim | VBMS Note | Incorrect "VBMS Note" text box positioning and size

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1029]
# Description
The text box for "VBMS Note" field is sized and positioned incorrectly on the `Route Claim - VBMS Note` page.  It should match the Caseflow styling guidelines for UI Components.

**Environment:**
- [ ] Production
- [x] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
**_Scenario 1 - Full Grant with Special Issue and EP Created_**
1. From the `Casework Dashboard`, click on the **_Establish next claim_** button.
1. Select "U.S. Territory claim - Philippines" as a Special Issue.
1. Click on the **_Route Claim [Decision]_** button.
1. The Route Claim - VBMS Note is rendered.  

_Unexpected Results:_  Text box is too big.
_Expect Results:_  Text box should have matched original mockup and style guide. #873 

## Screenshots
**_Scenario 1 - Route Claim - VBMS Note - Incorrect size/position_**
<img width="1013" alt="screen shot 2017-02-27 at 9 09 36 am" src="https://cloud.githubusercontent.com/assets/4975959/23364414/fbaa0d68-fccc-11e6-8ca9-6e4d802b8542.png">

**_Scenario 1 - Route Claim - VBMS Note - Correct size/position_** 
<img width="549" alt="screen shot 2017-02-27 at 9 14 08 am" src="https://cloud.githubusercontent.com/assets/4975959/23364444/1adc185c-fccd-11e6-88fb-3d88566a1e52.png">

# Related Issues
EP Creation | Page to add VBMS note when creating Full Grant EPs #873

**Comment by shanear** [comment]
@gnakm bump. this is a styleguide thing

**Comment by gnakm** [comment]
@lakohl @abbyraskin What are your thoughts on adding a button that says "copy text" that would automatically copy that text? Abby mentioned a feature like this for reader and I think it would give users more direction on what to do next.

**Comment by lakohl** [comment]
I like it! I believe we have that in Certification for the Vet ID and could use in in Dispatch for the email message as well as the VBMS note. We should make it a Style Guide component.

**Comment by gnakm** [comment]
@lakohl the button situation is now in this issue: https://github.com/department-of-veterans-affairs/caseflow/issues/1400

**Comment by gnakm** [comment]
Closing this because it was fixed in #1400
