### ISSUE TITLE
Bug: Wrong Modal for Reschedule Hearing

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10302]
When a user closes a transcription task with a reschedule hearing option, the wrong modal displays. The modal for cancel hearing request displays. See screenshot. 
![Screen Shot 2019-04-04 at 10 11 45 AM](https://user-images.githubusercontent.com/45463980/55563144-59fee800-56c3-11e9-925a-0994b799e1e2.png)

**Comment by ShellySmithDSVA** [comment]
This modal should be the following: https://va-gov.invisionapp.com/d/main/#/console/16413695/340365288/preview

![Screen Shot 2019-04-05 at 12 33 12 PM](https://user-images.githubusercontent.com/45463980/55642644-095cbd00-579f-11e9-8e4c-0a5bdfa1c803.png)

**Comment by sharonwarner** [comment]
I updated the wording to say, "This will place the case in the list of veterans to be scheduled for a hearing." I'll create another lower priority ticket to add the Admin Action as an option.

**Comment by MeredithStewart** [comment]
Tested and works!
