### ISSUE TITLE
Fix bug: Hearing Transcript Requested for Legacy Cases Appearing in Transcription Queue

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10304]
Legacy cases are appearing in the Transcription queue with a "Generictask" that has details about a transcript being requested by the Veteran. All of these tasks seem to be generated by the same user.  Example case here: https://appeals.cf.ds.va.gov/queue/appeals/3640875. We did not expect these tasks to appear in the Transcription queue. 

Via Slack: We've got transcription tasks showing up in the Hearing Branch's Transcription Queue for legacy appeals. It all seems to be by user J.RETAN and they all seem to be that the Rep has requested a copy of a transcription. We weren't anticipating admin actions being assigned to this queue for legacy cases. I'm assuming the flow here is Judge - attorney - VLJ support creates task. 

<img width="1039" alt="Screen Shot 2019-04-05 at 12 47 24 PM" src="https://user-images.githubusercontent.com/45463980/55644134-fa780980-57a2-11e9-8899-2e97c6dfc238.png">

Meredith and Lauren confirmed with Hearing Branch and VLJ Support Staff that Transcript request tasks should be completed by the Transcription team. However, we do NOT want legacy tasks in team queue's right now, just AMA. **The short-term solution is that VLJ Support/FOIA continue their normal practice of emailing until a longer-term solution is built in Caseflow.**

## AC
- Prevent GenericTasks from being created on Legacy appeals and assigned to Transcription queues
- Investigate if this is possible for other team queues, and if so (likely), prevent that as well

**Comment by MeredithStewart** [comment]
@laurjpeterson and I are talking to figure out path forward on this.

**Comment by sharonwarner** [comment]
Dup of existing ticket.
