### ISSUE TITLE
Rating issue put on nonrating Board DTA EP

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10316]
https://github.com/department-of-veterans-affairs/appeals-support/issues/4841

After investigation, the original Request Issue is a rating issue, with a rating reference ID, so this appears to be a bug.

Appeal: 1040
Remand SC: 4449
Original request issue: 5234

We should switch to previous_request_issue.rating? now that previous_request_issue is available.

There may also be a request for manual clean up.

**Comment by pkarman** [comment]
@leikkisa would you include some validation steps here?

**Comment by leikkisa** [comment]
This might be very similar to 10187, but this is for a DTA Appeal, so I'll modify those steps here in case there is a difference:

Do an Appeal for UAT Veteran 700032874
Contest the issue with this information:
Decision date: 2019-01-25
Text: "Evaluation of PTSD, which is currently 50 percent disabling, is continued."

Take note of the Appeal ID for the Appeal that is created.

Then create a remand decision for the appeal. This script should help:
```
# put the UUID of the Appeal being decided here
uuid = "ed984057-cc2b-473b-a6cf-76b1145667d2"
disposition="remanded"
# the citation number needs to be unique, so it will need to change everytime you run this
citation_number = "A19000200"

a = Appeal.find_by(uuid: uuid.upcase) #or find by the appeal ID
a.tasks.where(type: "BvaDispatchTask").delete_all
RequestStore[:current_user] = User.last
a.request_issues.each do |r|
decision_issue = DecisionIssue.create!(disposition: disposition, description: r.description, benefit_type: r.benefit_type, diagnostic_code: "5000", participant_id: a.veteran.participant_id, decision_review: a, rating_issue_reference_id: r.contested_rating_issue_reference_id)
RequestDecisionIssue.create!(decision_issue: decision_issue, request_issue: r)
end
root_task = a.tasks.find_by(type: "RootTask")
BvaDispatchTask.create_from_root_task(root_task)
u = a.reload.tasks.find_by(type: "BvaDispatchTask", assigned_to_type: "User").assigned_to
file = "1234"
BvaDispatchTask.outcode(a.reload, { citation_number: citation_number, decision_date: Time.zone.now, redacted_document_location: "\\\\bvacofil1.dva.va.gov\\archdata$\\arch1901\\${citation_number}.txt", file: file }, u)
```

Check the resulting request issue in the console, and check that it's rating.  Also check the remand supplemental claim end product code, and that it's a rating code ("040BDER").
```
a.remand_supplemental_claims.first.end_product_establishments.first.code
a.remand_supplemental_claims.first.request_issues.first.rating?
a.remand_supplemental_claims.first.request_issues.first.nonrating?
```

**Comment by Sjones352** [comment]
**Passes UAT** 

<img width="1680" alt="Screen Shot 2019-04-14 at 6 23 29 PM" src="https://user-images.githubusercontent.com/23080951/56100126-4afa1000-5ee3-11e9-9fd3-6958d7690d78.png">

<img width="1680" alt="Screen Shot 2019-04-14 at 6 28 23 PM" src="https://user-images.githubusercontent.com/23080951/56100134-577e6880-5ee3-11e9-963e-e78c375c8d36.png">
