### ISSUE TITLE
Veteran is employed at same station as claim establishment.

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10310]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3467/events/294187/

Error message: An error occurred while establishing the claim: Claim not established; Veteran is employed by this station.

The "station of jurisdiction" is set by us to 499 in this case.  A station ID is also sent with the user who is establishing the claim.

**Comment by pkarman** [comment]
same as #10087?
