### ISSUE TITLE
Bug: Appeals not showing in Schedule Veteran lists, but have open schedule hearing tasks

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10319]
https://appeals.cf.ds.va.gov/queue/appeals/2850494 -- doesn't appear in Togus, ME list or CO 

https://appeals.cf.ds.va.gov/queue/appeals/3031750 - doesn't appear in Phoenix list or CO 

Previously these cases were in 57, but hadn't gotten the tasks they needed to schedule Veterans. Now they have tasks, but aren't showing up in the lists to schedule, so the branch wouldn't see them to schedule unless they looked for them.

**Comment by MeredithStewart** [comment]
Checked on 4/5 and still not seeing these Veterans in the lists of Veterans to schedule for the ROs or CO.

**Comment by ShellySmithDSVA** [comment]
4/8 - This issue persists

**Comment by ShellySmithDSVA** [comment]
https://appeals.cf.ds.va.gov/queue/appeals/2850494 is still having an issue. https://appeals.cf.ds.va.gov/queue/appeals/3031750 now appears properly with an alt location on in the RO list.

**Comment by ShellySmithDSVA** [comment]
https://appeals.cf.ds.va.gov/queue/appeals/2850494 is still having an issue.
