### ISSUE TITLE
Work History | Make values in "Action" column clearer

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#1032]
As a Caseworker, I want to see actions that make sense to me. Currently there are some action names that are awkwardly named. Here is the complete list:

- Completed (means Created ARC EP)
- Released (this never happens anymore)
- Canceled
- Expired (somebody held an issue for too long)
- Routed to Ro (probably should be "Special Issue EP")
- Assigned Existing EP
- Special Issue Emailed
- Special Issue Not Emailed (probably should be "Released")
- Special Issue VACOLS Routed (should be "Routed in VACOLS")

## Notes
Example of an awkwardly named action:
<img width="1138" alt="screen shot 2017-03-22 at 1 47 33 pm" src="https://cloud.githubusercontent.com/assets/4306128/24212564/2446afec-0f06-11e7-99ba-8fc3fcc5a99a.png">

## **AC**
The new list of actions is as follows:

Action | Context | Example
--- | ----|----
 EP created for ARC - 397 | user created EP for ARC, no special issues |
EP created for RO [station] | user created an EP for an RO, tier 1 or 2 special issue | EP created for RO Station 344 - Los Angeles
Emailed - [special issue name] Issue(s) | full grant, tier 3 special issue | Emailed - Radiation; VAMC Issue(s)
Canceled | user canceled out of processing | 
Released to Work Queue | user held claim too long |
Assigned Existing EP | user assigned claim to existing EP |
Routed in VACOLS | partial or remand with tier 3 special issue, no EP created |

**Comment by shanear** [comment]
@sharonwarner can you provide more context on this issue? I'm not sure I understand.

**Comment by sharonwarner** [comment]
<img width="1138" alt="screen shot 2017-03-22 at 1 47 33 pm" src="https://cloud.githubusercontent.com/assets/4306128/24212564/2446afec-0f06-11e7-99ba-8fc3fcc5a99a.png">

Our completion codes are showing up on the Work History page, but some of our codes would be meaningless to the workers.

**Comment by shanear** [comment]
assigning to @abbyraskin and @lakohl for guidance

**Comment by abbyraskin** [comment]
Action | Context
--- | ----
 EP created for ARC - 397 | user created EP for ARC, no special issues |
EP created for RO [station] | user created an EP for an RO, tier 1 or 2 special issue |
Emailed - [special issue name] Special Issue | full grant, tier 3 special issue |
Canceled | user canceled out of processing |
Released to Work Queue | user held claim too long |
Assigned Existing EP | user assigned claim to existing EP |
Routed in VACOLS | partial or remand with tier 3 special issue, no EP created |

**Comment by shanear** [comment]
@abbyraskin need some clarification for "EP created for RO" text formatting

A. "EP created for RO Station 344 - Los Angeles"
B. "EP created for RO Station 344"
C. Something else

**Comment by abbyraskin** [comment]
@shanear I was thinking we'd reuse the format we use elsewhere, e.g., the station field:

EP created for RO 344 - Los Angeles, CA

**Comment by shanear** [comment]
@abbyraskin also, if there are multiple special issues, should we put all of them in seperated by commas?

This is close to what we do on the success page:
"Emailed - Radiation; VAMC Special Issue(s)"

**Comment by shanear** [comment]
@abbyraskin I'll do that. However on the success page we just use the city not the state. That cool?

**Comment by abbyraskin** [comment]
Yes, better without state, especially if it's a pattern from another page 😃 
Separated by semicolons works! Updated the little table above to reflect what we discussed:

Action | Context
--- | ----
EP created for ARC - 397 | user created EP for ARC, no special issues |
EP created for RO [Station - City] | user created an EP for an RO, tier 1 or 2 special issue |
Emailed - [special issue 1; special issue 2] Special Issue(s) | full grant, tier 3 special issue |
Canceled | user canceled out of processing |
Released to Work Queue | user held claim too long |
Assigned Existing EP | user assigned claim to existing EP |
Routed in VACOLS | partial or remand with tier 3 special issue, no EP created |

**Comment by shanear** [comment]
@abbyraskin added examples to the AC up top. Let me know if they are good

**Comment by abbyraskin** [comment]
@shanear they are good!

**Comment by shanear** [comment]
Changing "Special Issue(s)" to "Issue(s)" since that's what we use on the success page.

**Comment by astewarttistatech** [comment]
Test data is currently tied up. So far this is what has been tested in UAT: 

<img width="1324" alt="screen shot 2017-04-12 at 10 31 59 am" src="https://cloud.githubusercontent.com/assets/23038505/24962974/61759106-1f6b-11e7-8444-4c05a8df34bc.png">

Moving into blocked until able to test the rest

**Comment by kierachell** [comment]
<img width="956" alt="screen shot 2017-04-17 at 12 13 23 pm" src="https://cloud.githubusercontent.com/assets/18075411/25094938/4a39a4dc-2367-11e7-91f9-e361ff8a3665.png">
