### ISSUE TITLE
Lit Support Queue: Create "Notify OGC of Pulac-Cerullo" task

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#10323]
## User Story
As a Motions Attorney, I need to assign a case to Kate (i.e. our team liaison between OGC/CAVC) if the Veteran also filed a CAVC appeal so that they can make a determination about who has jurisdiction on the case. 

### Acceptance criteria:
- A new task type is created - "Notify OGC of Pulac-Cerullo"
- "Notify OGC of Pulac-Cerullo" is an action available to Motions Attorneys in the actions drop-down on the Case Details page
- Routing: the task is assigned Kate Sosna
- No feature flag is needed
- Display confirmation modal after user clicks "Notify OGC of Pulac-Cerullo" action
- After user clicks "Submit" on confirmation modal, return user to their individual queue and display a confirmation banner.

## Mocks

**Confirmation modal**

![image](https://user-images.githubusercontent.com/40216950/57148269-41075680-6d97-11e9-9377-3e0a3948abbf.png)

**Confirmation banner**

![image](https://user-images.githubusercontent.com/40216950/57148289-4bc1eb80-6d97-11e9-86ad-0d4046da6e3b.png)

**Comment by aroltsch** [comment]
1. "Notify OGC of Pulac-Cerullo" action should be available when a task is assigned to a litigation support organization and is one of this type:
* ClearAndUnmistakeableErrorMailTask
* ReconsiderationMotionMailTask
* VacateMotionMailTask
1. When a motions attorney selects the action, we should create a new task with the same type and assign it to the pulac-cerullo organization which means we have to add this new organization to the org list
1. Kate Sosna will then use this org view to view assigned tasks

**Comment by youngfreezyVA** [comment]
also, 5. UI confirmation modal when selecting the "Notify OGC of Pulac-Cerullo" option and 6. verifying access to the `pulac-curello` url

**Comment by allyceh** [comment]
@youngfreezyVA @aroltsch and @sneha-pai , I added two mocks to the ticket to round out this flow. I also updated the AC. 

Sneha, if you have feedback on copy for the confirmation modal or banner, feel free to leave it in the ticket.

**Comment by laurjpeterson** [comment]
@youngfreezyVA - let me know when this one has been deployed, because we could reach out to users and train them

**Comment by laurjpeterson** [comment]
Note: need to add Kate to Pulac-Cerullo organization
