### ISSUE TITLE
Motion to Vacate | Allow judges to log motion to vacate decisions

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#10325]
As a judge, I need the ability to log my motion to vacate decision in Caseflow so that we have it on record. 

(Note: the decision that comes as a result of the motion to vacate decision is out of scope for this ticket.)

### Acceptance criteria: 
- Judge can take action - "Determine disposition" - on a Motion to Vacate task when it's assigned to them 
- Judge navigates to another screen where they can determine the disposition for the motion - grant, deny, withdraw/dismiss. On this screen, they can see
    - The notes the motions attorney left them (task instructions)
    - A radio button to select the disposition
    - A radio button to select the next action
- Motion to Vacate task is updated on the Case Timeline

### Designs
https://www.figma.com/proto/GCRmxv1kWxPgLV8ipgD5RJ/VLJ-Flow-with-Actual-Screens

**Comment by aroltsch** [comment]
1. Where do we save dispositions for motion to vacate tasks?
1. Is this decision going to be appealed in the future?
1. If a user should see notes the motions attorney left them, does it mean that this task was under attorney's review first?

**Comment by laurjpeterson** [comment]
1. I'd love to hear a recommendation for this architecture for where motions dispositions should live in our data model. 
2. Potentially, yes.

**Comment by geronimoramos** [comment]
**Outstanding question**
What factors of the decision are we looking to log?

Whether they grant, deny, withdraw or dismiss the motion to vacate AND/OR which issues are granted vacature AND/OR what they decide on those issues?

**Comment by jcq** [comment]
Design for judge task page/modal:
https://www.figma.com/proto/GCRmxv1kWxPgLV8ipgD5RJ/VLJ-Flow-with-Actual-Screens?node-id=12%3A81&viewport=305%2C50%2C0.20774906873703003&scaling=min-zoom

**Comment by aroltsch** [comment]
TODO:
1. Create a post request to save motion dispositions
2. Combine motion dispositions dismiss and withdraw on the BE and save as dismissed.

**Comment by jcq** [comment]
This also connects to https://github.com/department-of-veterans-affairs/caseflow/issues/11253

The judge "Address Motion to Vacate" portion of this is complete, connected via PRs:

- https://github.com/department-of-veterans-affairs/caseflow/pull/12064
- https://github.com/department-of-veterans-affairs/caseflow/pull/12109

There is additional work that needs to be ticketed and done for handling `DeniedMotionToVacateTask`, `DismissedMotionToVacateTask` (both for motions attorney), and `JudgeSignMotionToVacateTask` (VLJ)

**Comment by leikkisa** [comment]
The following tickets have been created to handle the denied, dismissed/withdrawn, and granted motions to vacate.
https://github.com/department-of-veterans-affairs/caseflow/issues/12268
https://github.com/department-of-veterans-affairs/caseflow/issues/12269
https://github.com/department-of-veterans-affairs/caseflow/issues/12270

I am closing this ticket since the scope for this ticket (and then some) is complete.
