### ISSUE TITLE
Appeals with request issues that have status of dismissed_death and dismissed_matter_of_law

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#10321]
https://appeals.cf.ds.va.gov/queue/appeals/8f18d094-ff09-49f5-936d-7d13d05c9351

444fc607-6406-4976-8e6b-df84006c0af5
7883b2bd-917d-42ec-abe7-b204e486812c

**Comment by allyceh** [comment]
UI modifications for this are being discussed in #8936 .

**Comment by hschallhorn** [comment]
#8936
