### ISSUE TITLE
Edit Request Issue title

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10332]
Decision review rating request issues currently have deterministic values for their title text, derived from the contested rating issue. We are now going to give users some editorial control over the title.

This is to allow users to update the contention text of a contention in VBMS.  This should be allowed for rating issues (most importantly), and contestable nonrating issues.

## Definitions

* "original text" here means the generated title text derived from the contested rating issue description.
* "edited text" here means the user-entered title text

## Acceptance criteria

* In the UI, the title will be edited in place (not in a modal).
![Edit title 02](https://user-images.githubusercontent.com/11700545/55116058-53f57f80-50a3-11e9-9541-8db9df364e22.png)
* If the user removes all the text from the textarea box, the HTML field placeholder text should be the original text, to indicate to the user that it will default to that value.
* The "Cancel" button will close the edit component, without applying any changes to the title.
* The "Submit" button will apply changes on the client side only. Any changes should generate the light blue "you have unsaved changes" banner alert (*note* this is not currently in the mocks) and activate the page's "Save" button.

## Mocks

See https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1126

## Technical notes

* Add a new column `edited_description` for storing the user's edited title. Preserve the `contested_issue_description` for the original text, so that the user can "undo" their edits.
* The `description` method in `RequestIssue` should prefer `edited_description` over `contested_issue_description` if `redited_description` is not nil.
* Use a feature toggle `edit_contention_text`.

**Comment by carolaponce** [comment]
Not reflected in the mock - Submit button will be grayed out until the user makes a selection, either delete or edit text.

**Comment by pkarman** [comment]
Some question as to whether this will be applied to Appeals. @carolaponce to work with Allyce.

For now working only on Claim Reviews.

**Comment by pkarman** [comment]
all the issues here are closed so closing this epic.
