### ISSUE TITLE
Create ScheduleHearingTasks for ColocatedTasks with the schedule_hearing action

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10354]
Now that we are scheduling hearings for `LegacyAppeal`s using [the `ScheduleHearingTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb) we should make use of that same task for `ColocatedTask`s with the `schedule_hearing` action instead of [changing the VACOLS location to 57](https://github.com/department-of-veterans-affairs/caseflow/blob/fbde547b958f9a787b23618e1775389fd880457c/app/models/tasks/colocated_task.rb#L126).

`ColocatedTask`s associated with `LegacyAppeal`s with the `schedule_hearing` action are created as children of `AttorneyLegacyTask`s (see the results of the query below), so we will need to make sure that the VACOLS location code remains "CASEFLOW" and that the `ScheduleHearingTask` is created as a child of the `RootTask` for the appeal.

```sql
select coalesce(parent_id, 0)
, count(*)
from tasks
where type = 'ColocatedTask'
  and assigned_to_type = 'Organization'
  and appeal_type = 'LegacyAppeal'
  and action = 'schedule_hearing'
group by 1;
```

## Acceptance criteria
* [ ] Determine what state the task tree after a member of the VLJ support staff has selected the "Hearing does need to be scheduled, send to hearing branch" option
* [ ] Stop changing the VACOLS location codes for these `ColocatedTask`s
* [ ] Create a `ScheduleHearingTask` for these `ColocatedTask`s

**Comment by kevmo** [comment]
@lomaxap @aroltsch When the VLJ support staff needs to schedule an additional hearing after a Judge or Attorney has received a case, should the case be returned to the same judge who initially received the case or go into redistribution?

**Comment by lomaxap** [comment]
When you create a ScheduleHearingTask, the appeal goes back to the hearings branch to be scheduled for a new hearing. The VLJ support staff won't actually do the scheduling. 

I'm not sure how that impacts how other tasks are assigned, though it makes sense to me that you shouldn't need to change any other assignments.

**Comment by lowellrex** [comment]
SMALL.
