### ISSUE TITLE
Transcription users should be able to add admin action to schedule hearing task

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#10359]
![55642644-095cbd00-579f-11e9-8e4c-0a5bdfa1c803](https://user-images.githubusercontent.com/4306128/55740176-8afb5780-59f8-11e9-9b1f-7517053ea0f1.png)

**Comment by laurjpeterson** [comment]
Unclear why they need the add admin action option here. Let's close.
