### ISSUE TITLE
Problems with the FACOLS Setup

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#10355]
#### Error starting up VACOLS_DB-development and VACOLS_DB-test containers
```
OCIError: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
oci8.c:561:in oci8lib_250.bundle
```

Potential fix: 
* increase disk/memory allocation
* `docker system prune --volumes`

#### Oracle credentials error 
```
OCIError: ORA-01017: invalid username/password; logon denied
```

Potential fix: `docker system prune --volumes`

#### ORACLE shutdown error

```
OCIError: ORA-01033: ORACLE initialization or shutdown in progress
oci8.c:603:in oci8lib_250.bundle
```

### Improvement Ideas
1. Combine our development and test FACOLS containers into one container. i.e. have two schemas within the database. I think this will reduce the overhead we experience running two containers.

2. Upgrade Oracle DB image

**Comment by pkarman** [comment]
The "waiting for FACOLS" step on CircleCI takes about 90 seconds for each container (about 10% of total time). If we could improve that, we could improve CI throughput.

**Comment by kevmo** [comment]
### Caseflow Application Architecture & Local Development Environment setup 
I will be editing this comment over time. 

The Caseflow application architecture:
![caseflow-2](https://user-images.githubusercontent.com/1034221/55829486-c66f5200-5adc-11e9-8535-85f671eb8954.png)

Commonly seen errors 
- system hangs on `docker-compose up vacols-db-development`

Pain point: Instant Client download (for Ruby OCI gem?). Manually downloading InstantClient and moving files on computer -- lots of room for error re correct paths and versions. What is proper version? This step should probably be more automated. 

Things that worked:
- Repeatedly running the README setup commands after they failed, sometimes at different steps. 
- `docker system prune --volumes`.  

Potential issues:
- Undocumented dependencies
- Order of setup operations.

Potential improvements for the FACOLS component/image: 
- Polish up `/local/vacols` docker image in general.
- Current container consumes a lot of computing resources. Tinker with Oracle config to get 
- Potentially push`local/vacols` image to Docker Hub, thus removing more of the steps from local development.  Probably has some slight issues re Oracle licenses.
- Do not set up both vacols-db-test and vacols-db-development containers for local dev. Repetitive and costly.
- Improve documentation in general.

Potentially: Dockerize Frontend (Rails + Oracle libraries together?)

**Comment by lomky** [comment]
### Caseflow Application Architecture & Local Development Environment setup, Ubuntu

Same local dev setup as above. Same may-be-edited caveat.

#### Issues Encountered: 

 - Latest Oracle Instaclient (18_5) not functional. Ended up following [ruby-oci8 gem directions](https://github.com/kubo/ruby-oci8/blob/master/docs/install-instant-client.md) and installed v12. 
 - Command `bundle exec rake local:build` not working. Work around involved running each step. Problem seems to come out of `docker-compose up` on the FACOLs containers, specifically [this line grepping a log to determine success](https://github.com/department-of-veterans-affairs/caseflow/blob/6f7f9160e4b9ace479118ce2b6bc37f64d21c2cf/lib/tasks/local/vacols.rake#L47). The log no longer receives any output, even when the container started up fine. Suggest using this health check instead: ``` `docker-compose ps | grep 'health: starting'`.strip.chomp.empty? ```, which [seems to be functional elsewhere](https://github.com/department-of-veterans-affairs/caseflow/blob/062a6a2fb23151175cc770badf2a4f6c0dc7eb7d/lib/tasks/local/build.rake#L14). More tested needed, including ubuntu/fedora/mac behavior differences.
 - Possible memory issues. More testing needed to distinguish from the above case. Limiting Docker memory/cpu resources on linux seems to be non-trivial.
 - Undocumented dependencies. PostgreSQL, Redis, SQLite (Unused?)

**Comment by pkarman** [comment]
Some research on our FACOLS Docker setup:

* we use a distributed base image in the Docker store from Oracle based on version 12.2.0.1-enterprise. There isn't an available source Dockerfile for this that I can find, and the current GH project explicitly says it is old and not maintained. https://github.com/oracle/docker-images/issues/967
* The bug we are seeing with "Waiting for FACOLS" step at CI is that the SID is "BVAP" and the Oracle image has a script of some kind that calls `DBNEWID` to rename the database from the default SID at setup time. This step fails sometimes and so the db instance hangs.
* The script that renames things is called either by the Oracle binary or some script I cannot locate in the Docker image. W/o the Dockerfile it's difficult to pinpoint the origin of that script.
* The [newer GH docker files](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance) have a whole different mechanism for setup and so our existing infra would need to be reworked to support. So it's not a simple matter of "upgrade the Docker image".

**Comment by pkarman** [comment]
@aroltsch should we close this?

**Comment by aroltsch** [comment]
I think we can!
