### ISSUE TITLE
Rename Suggested Location Column

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10352]
In the Schedule Veterans list, re-name the "Suggested Location" column to "Hearing Location." This corrects the issue of these Veterans being on the schedule and therefore assigned locations. See the screenshot below. 
![Screen Shot 2019-04-05 at 3 56 39 PM](https://user-images.githubusercontent.com/45463980/55653184-ba715080-57bb-11e9-9007-5aafbef46bae.png)

**Comment by sharonwarner** [comment]
Captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/10018
