### ISSUE TITLE
At intake confirmation > Edit issue

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#10358]
We heard from pre AMA user feedback - Users wanted a way to review and edit their intakes before continuing to the next intake:
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1049

We also heard they would like a dashboard of all their intakes.  This is a first step to provide users the ability to review and edit issues after intake is finished.

![EditIssues_confirmation](https://user-images.githubusercontent.com/11700545/55740775-a9555900-59e0-11e9-9fe4-bb703f548703.png)

**Comment by leikkisa** [comment]
Putting a note here - will this cause issues if the establishment is still processing and a user attempts to edit their intake?

**Comment by carolaponce** [comment]
@leikkisa I am not sure, does that mean multiple EPs can be created?

**Comment by carolaponce** [comment]
I had a conversation with @shanear about this user need a while back.  A better experience would be if we can provide users a dashboard of their intakes and give them time to make updates before the reviews are processed.  We can further discuss this.

**Comment by leikkisa** [comment]
Closing this issue, thanks to @pkarman 's work here: https://github.com/department-of-veterans-affairs/caseflow/pull/11970
