### ISSUE TITLE
[1] Cancellation Modal | Incorrect styling and punctuation

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1035]
# Description
When canceling a Certification, there are a couple of styling and punctuation issues.  the first question is missing a question mark, radio button text is not aligned.

- Missing a question mark for 1st question and grammar is wrong - the question should read "Why can't this case be certified in Caseflow?"
- Radio button text is not indented/aligned properly.  The text following a radio button should start to the right of the radio button

**Environment:**
- [x] Production
- [x] UAT
- [x] Demo
- [x] Development

**Type of Bug:**
- [ ] Performance
- [X] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [X]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1 - Visit Caseflow Certification and attempt to cancel a certification
1. Log into Certification.
1. Click on the **_Cancel Certification_** link.  
     **_Results:_**  The Cancel Certification modal will be displayed with styling and punctuation issues.

## Screenshots
**_Scenario 1 - Current styling and punctuation issues_**
![image](https://cloud.githubusercontent.com/assets/23063044/23753751/9e33f6f6-04a8-11e7-9ac2-aafb09ab6499.png)

**_Scenario 1 - Expected styling and punctuation_**
![screen shot 2017-03-02 at 12 24 47 pm](https://cloud.githubusercontent.com/assets/1178390/23519022/75e579dc-ff43-11e6-931c-eb730a9c552f.png)

# Related Issues
- [x] Cancellation Modal | Ability to view instructions and report issues #626

**Comment by shellicious** [comment]
![screen shot 2017-03-02 at 12 24 47 pm](https://cloud.githubusercontent.com/assets/1178390/23519022/75e579dc-ff43-11e6-931c-eb730a9c552f.png)

Updated with screenshot. Changes to be made:
- Add question mark to "Why can't this case be certified in Caseflow?"
- Indent radio button text so that text following a radio button starts to the right of the radio button
- Except for the title, "certification" should not be capitalized, so within body text and on the button, the phrase should read: "Caseflow certification" 

@kierachell @nemodjuric

**Comment by nikitarockz** [comment]
@shellicious I added a screen shot of the current Cancellation modal and the issue about certification being  capitalized outside of the title isn't present.  Are you saying that in the last sentence add the phrase "Caseflow certification"?

> Once you click Cancel certification, changes made to this case in Caseflow certification will not be saved.

**Comment by gnakm** [comment]
@nikitarockz Chiming in here. Could you show me the screen shot that you added?

I think Shelly's mock and 3rd change statement are aligned. I don't think she added anything but changed the capitalization in the body copy. I broke it down in this image:

![image](https://cloud.githubusercontent.com/assets/13420618/23768596/97ceb558-04da-11e7-933d-8010cc09175c.png)

**Comment by shellicious** [comment]
thank you for chiming in, @gnakm! Yes, that is what I originally meant. :)

**Comment by shanear** [comment]
This looks well defined. Assigning to alex and shelly for prioritization

**Comment by amprokop** [comment]
We'll make this change and let the style guide folks know, and give them a chance to review it.

**Comment by kierachell** [comment]
actually the radio button might be already fixed

**Comment by kierachell** [comment]
**PASSED**
<img width="499" alt="screen shot 2017-05-26 at 12 38 19 pm" src="https://cloud.githubusercontent.com/assets/18075411/26503848/4f7f302a-4210-11e7-9f93-7bd7822f8731.png">
