### ISSUE TITLE
Mismatched Documents | Incorrect button label

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1036]
# Description
On the missing or mismatched documents page, the **_Refresh Page_** button isn't in the correct style.

_Expected Results_ 
- Uncapitalize the word "page" on the "Refresh Page" button, so that it reads **_Refresh page_**

**Environment:**
- [x] Production
- [x] UAT
- [x] Demo
- [x] Development

**Type of Bug:**
- [ ] Performance
- [X] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [X]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1 - Start a new certification

1. Visit https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/certifications/new/456C

## Screenshots
**_Scenario 1 - Missing Documents - incorrect button label_**
![image](https://cloud.githubusercontent.com/assets/23063044/23778957/6f37bc76-050b-11e7-9176-b9a3f4135163.png)

# Related Issues
Update Missing Documents page #834

**Comment by shellicious** [comment]
The change here is to uncapitalize the word "page" on the "Refresh Page" button, so that it reads "Refresh page."

**Comment by kierachell** [comment]
**PASSED**

good work, comrade:
![screenshot_2017-03-14_19-29-57](https://cloud.githubusercontent.com/assets/18075411/23926785/ac3e7c42-08ec-11e7-8c97-a84b337fe57d.png)
