### ISSUE TITLE
Exclude TrackVeteranTasks from Appeal.assigned_to_location determination

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10368]
The [logic in `Appeal.assigned_to_location`](https://github.com/department-of-veterans-affairs/caseflow/blob/5f441cfaf1aa461df3f849aa828a168eebf7e41d/app/models/appeal.rb#L139) incorrectly includes `TrackVeteranTask`s which is causing confusing values to be displayed in the "assigned to" column of some queue table views (see #10344 for an example). Since `TrackVeteranTask`s do not require their assignees to do any work on the appeal we should exclude them from the `Appeal.assigned_to_location` determination.

## Acceptance criteria
* [ ] Exclude `TrackVeteranTask`s from `Appeal.assigned_to_location` determination

**Comment by MeredithStewart** [comment]
@lowellrex -- do we have a timeframe on this one? I just want to be able to communicate this to the Hearing Branch.

**Comment by lowellrex** [comment]
XS.
