### ISSUE TITLE
Case details contrast and accessibility improvements

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#10373]
We can bump up the contrast (between the gray container and white background) on the Case Details page to make it more accessible. Given the quality of the monitors at BVA, we've also observed that our lightest grays don't show up at all

Places where we can improve the contrast: 
- Case header
- Section titles, like Currently Active Tasks, Issues, POA, Hearings, etc
- Page navigation menu (that contains each section title) 

Designs: TBD

**Comment by laurjpeterson** [comment]
There's an AMA issues component ticket, so closing this one.
