### ISSUE TITLE
Restrict list of users on team admin page for VSOs

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10371]
We will soon be [giving VSOs the ability to manage membership](https://github.com/department-of-veterans-affairs/caseflow/issues/9693#issuecomment-480062104) in their organizations directly in Caseflow's team management interface. The dropdown menu that team admins can use to add users to their team [includes everybody in the `users` table](https://github.com/department-of-veterans-affairs/caseflow/blob/4cc82a2abde93d8991cfa256eb4290e00486b182/app/controllers/organizations/users_controller.rb#L9) who is not already on their team. We want to restrict this set of selectable users for VSO organizations to only users with the VSO role (see [related Slack discussion](https://dsva.slack.com/archives/C6E41RE92/p1554816544206800)).

![image](https://user-images.githubusercontent.com/32683958/55805717-fd2d7400-5aac-11e9-8860-9c5e043004e3.png)

## Acceptance criteria
* [ ] Restrict the options in the dropdown menu on the team management pages for VSO organizations to include only Caseflow users with the "VSO" role.

**Comment by lowellrex** [comment]
SMALL. Should be mostly back-end only filtering, may need to hit a different API endpoint to fetch VSO users only.

**Comment by lomky** [comment]
Lucky us, we already do this!

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/organizations/users_controller.rb#L11

VSO role orgs can only see other VSO role org users. Marking closed.
