### ISSUE TITLE
Bug: Veteran matches to wrong Alt location and has wrong distance

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10387]
The following Veteran matches to the correct RO, but the wrong alternative hearing location. The hearing location distance is also wrong. 
https://appeals.cf.ds.va.gov/queue/appeals/3346867

**Comment by ferristseng** [comment]
@lomaxap and I took a look into this, and found that the hearings facility locator was returning a `200` status code, but a multiple address error in the `messages` field. The response still contained the lat/long for the address, but it looked like it was being set to a default value of (0.0, 0.0). That geocode was being used to find the nearby hearing locations, causing the distances to be incorrect.
