### ISSUE TITLE
Judge unable to self assign a task

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#10386]
[Sentry alrert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3878/events/299711/). [Related logs](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-03c93e3b20accbac9;filter=%2286745ead-16e2-4f2b-a812-bbb0c18d9d34%22;start=2019-04-09T13:08:56Z).

Should this have been fixed in #9117?

**Comment by laurjpeterson** [comment]
I don't think this was fixed in #9117 because Anya just manually moved the case from one judge to another in that case.

**Comment by pkarman** [comment]
Requires some investigation to see whether this is still a problem. Judges can assign tasks to other judges now. Not sure if this got fixed along the way. @lomky do you know?

**Comment by lomky** [comment]
It looks like the problem is the Judge is not an Attorney in our system:

> `[appeals.cf.ds.va.gov] [86745ead-16e2-4f2b-a812-bbb0c18d9d34] [172.30.82.234] [BVAPMLYNCH paula.dilorenzo@va.gov] [2019-04-09 20:10:51 -0400] ActiveRecord::RecordInvalid (Validation failed: Assigned to has to be an attorney):`

**Comment by pkarman** [comment]
@laurjpeterson to help scope the business rules here.

**Comment by hschallhorn** [comment]
Think I linked the wrong issue many moons ago. Should have been fixed with #7612.

**Comment by laurjpeterson** [comment]
I think this is potentially related to https://github.com/department-of-veterans-affairs/caseflow/issues/11368 - AttorneyTask - User attempted to assign to a non-attorney

**Comment by hschallhorn** [comment]
Fixed in #14226
