### ISSUE TITLE
Hearing details | Edit judge for legacy hearings

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#10403]
Currently we only allow users to edit a hearing record from the hearing details page for AMA hearings. We'd like to add functionality such that users can edit the judge at an individual hearing level from the hearing details page for legacy hearings.

AC:
- [ ] Users can edit an individual hearing's judge from the hearing details page for a legacy hearing

Current page view:

<img width="1112" alt="Screen Shot 2019-04-11 at 11 02 43 AM" src="https://user-images.githubusercontent.com/4306128/55968106-5fbb7700-5c49-11e9-8459-417819d34804.png">

New page view:

![Screen Shot 2019-04-11 at 2.11.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582a398e7d9c5f1300c030ee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276455f26b7191a37af1132a4f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df34ee14d53a61a3066e0702431.png)

Engineering notes:
- The frontend code for this logic can be found in `client/app/hearingSchedule/components/Details.jsx`
- The backend code for this logic can be found in `app/controllers/hearings_controller.rb`
- We'll need to ensure we're sending the vacols_attorney_id to VACOLS, not the judge_id from the caseflow database

**Comment by ShellySmithDSVA** [comment]
Design for Hearing Details for legacy hearings is here in the following Invision prototype. 
https://va-gov.invisionapp.com/share/X6RI675QG9M#/357681934_Hearing_Details
