### ISSUE TITLE
create contention fails

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10421]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4602/events/300982/

I have manually set `establishment_last_submitted_at` to `nil` to avoid creating more text-less contentions.

Supplemental Claim 6319

VBMS appears to create the contention but returns no description so it cannot be matched.

VBMS is investigating.

**Comment by pkarman** [comment]
confirmed that VBMS fully supports UTF-8 character set.

**Comment by pkarman** [comment]
We sent a string that was 255 characters but that included a multi-byte codepoint, which made it 256 bytes. Apparently VBMS will silently drop the entire text rather than truncating it.

**Comment by leikkisa** [comment]
Validated in UAT:
![Screen Shot 2019-05-01 at 5.37.32 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/ec3bfe09-d1c0-4e3b-80ba-8571315ccf3d)
