### ISSUE TITLE
Investigate why users get 'additional access needed' error but they have full access to document in VBMS

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#10424]
Support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/4907

Slack thread: https://dsva.slack.com/archives/C2ZAMLK88/p1554918721214300

AC: Investigate why users get 'additional access needed' error but they have full access to document in VBMS

**Comment by pkarman** [comment]
@aroltsch I think this is #10437
