### ISSUE TITLE
Hearing Schedule UI Audit

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#10446]
### Context

Currently, in Caseflow Hearing Schedule, there are a few undstandarized UI elements that do not align with the original design implementation/style guide standards. 

The main reason for making these UI updates is to help the user better navigate and digest the information that they are seeing on the page, especially with the Caseflow Hearing Schedule table, where they are multiple modes of information to analyze. 

### UI Audit of Caseflow Hearing Schedule Table:

- Add white space between the gray box of available hearing days and the scheduling table so users see a clear separation between the two types of information
- Make sure that all entries in the table have a fixed width. 
  - I noticed users squinting when they switch between a wider entry and a smaller entry 
- The Case Details column header should be flushed with the first name of the Veteran name
  - Similarly, the "View hearing docket day" link should be flushed with the above 
- There should be about 5 px of space between the filter icons and their table header 
  - Regional office should be a disabled dropdown instead of read only to better visual continuity between

**Comment by pshahVA** [comment]
Are these still valid in light of the refactor of hearings prep?

**Comment by pshahVA** [comment]
@nicholer, I think we can close this, what do you think?

**Comment by nicholer** [comment]
@pshahVA Looking in demo, it seems most of these have been addressed except for
> The Case Details column header should be flushed with the first name of the Veteran name

That alignment fix could be rolled into the changes we make to add the POA?
