### ISSUE TITLE
Route Claim | Send Email | Email Link | Incorrect "Message" text box positioning and size

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#1044]
# Description
The text box for "Message" field is sized and positioned incorrectly on the `Route Claim - Send Email` page.  It should match the Caseflow styling guidelines for UI Components.

**Environment:**
- [ ] Production
- [x] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
**_Scenario 1 - Full Grant with Special Issue and RO Email_**
1. From the `Casework Dashboard`, access a full grant.
1. Select a Tier 3 Special Issue Category on the Review Decision page
1. Click on the **_Route Claim [Decision]_** button.
1. The `Route Claim - Send Email` page is rendered.  

     _Unexpected Results:_  Text box is too big.
     _Expect Results:_  Text box should have matched original mockup and style guide. #722 

## Screenshots
**_Scenario 1 - Route Claim - Send Email - Incorrect size/position_**
<img width="1003" alt="screen shot 2017-02-27 at 9 15 31 am" src="https://cloud.githubusercontent.com/assets/4975959/23364501/4e47f530-fccd-11e6-8082-cc403ef9c627.png">

@nikitarockz These are the latest mocks!

**_Scenario 1 - Route Claim - Send Email - Correct size/position - Added Requirement text_**

![image](https://cloud.githubusercontent.com/assets/13420618/23915047/48839260-08be-11e7-9b48-2a385c617c25.png)

View when checkbox is selected
![image](https://cloud.githubusercontent.com/assets/13420618/23915260/f1ab4a9a-08be-11e7-80f9-0a1b9857c15f.png)

# Related Issues
Route Claim | Display Informational Route Claim unable to create EP (Full Grants with Special Issues/RO Email) #722

**Comment by gnakm** [comment]
@lakohl Didn't we decide to add a red _Required_ note right after the checkbox message?

**Comment by lakohl** [comment]
yup!

**Comment by gnakm** [comment]
@nikitarockz These are the latest mocks!

**_Scenario 1 - Route Claim - Send Email - Correct size/position - Added Requirement text_**

![image](https://cloud.githubusercontent.com/assets/13420618/23915047/48839260-08be-11e7-9b48-2a385c617c25.png)

View when checkbox is selected
![image](https://cloud.githubusercontent.com/assets/13420618/23915260/f1ab4a9a-08be-11e7-80f9-0a1b9857c15f.png)

**Comment by astewarttistatech** [comment]
Blocked due to VBMS error, see Sentry error: https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/282/

Current view: 
<img width="1114" alt="screen shot 2017-07-31 at 1 35 06 pm" src="https://user-images.githubusercontent.com/23038505/28789971-5a07d682-75f5-11e7-8ef8-53ca4b37459a.png">

**Comment by astewarttistatech** [comment]
Adding the correct SIC for the scenario based on SIC Tiers.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Dispatch as a caseworker
2. Try to establish an EP with a full grant and a 3rd tier SIC (reference: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Special%20Issue%20Tiers.md) 
3. Validate that on the Route Claim: email page that the text field is an appropriate size
3. Validate the view when the checkbox is checked and unchecked, matches what is used for the mocks.  

Screenshots: 
![emaildispatch](https://user-images.githubusercontent.com/23038505/28881229-74d7e066-7775-11e7-9d2e-1a8df8fb662f.png)
![routeclaim checked](https://user-images.githubusercontent.com/23038505/28881228-74c2fca0-7775-11e7-98a6-97ccfb22fd49.png)

P.S. An issue has been created from this
