### ISSUE TITLE
Caseworker Dashboard | Work History | Separation lines are too thick

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#1045]
# Description
The row separation lines within the Work History table are too thick.  The should be the equivalent of 1px thick and USWDS gray-light #D6D7D9 so they are not distracting.

**Environment:**
- [x] Production
- [x] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
1. Log into Dispatch as a Caseworker
1.  The `Caseworker Dashboard` page will be displayed.  The lines are seen in the Work History section's table.

## Screenshots
**_Scenario - Caseworker Dashboard with thick lines_**

![caseworker dashboard - thick lines](https://cloud.githubusercontent.com/assets/23063044/23462084/739cd218-fe5a-11e6-9943-5a5f5a697751.png)

**_Scenario - Caseworker Dashboard with desired lines_**
<img width="657" alt="screen shot 2017-02-26 at 5 46 02 pm" src="https://cloud.githubusercontent.com/assets/4975959/23344499/94aa0edc-fc4b-11e6-880a-611d58cc3981.png">

# Related Issues
n/a

**Comment by astewarttistatech** [comment]
@lakohl the header is the same from the wrong scenario but the lines are okay. Can you give some input. 

Steps to Validate: 
1. Go to Dispatch as a caseworker
2. Go to the Establish Claim homepage

Screenshots: 
<img width="1290" alt="screen shot 2017-03-03 at 3 42 40 pm" src="https://cloud.githubusercontent.com/assets/23038505/23568533/e2199cd8-0028-11e7-8e25-321df4f64462.png">

**Comment by lakohl** [comment]
I believe the line below the button was fixed here: https://github.com/department-of-veterans-affairs/caseflow/pull/1070#event-986018796

All the lines should be color #D6D7D9

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT

Steps to Validate:
1. Go to Dispatch as a caseworker, once a few EPs have been created.
2. Validate work history lines width as well as color in inspector. 

Screenshots: 
<img width="1363" alt="screen shot 2017-03-08 at 9 58 26 am" src="https://cloud.githubusercontent.com/assets/23038505/23709031/10adcc5c-03e6-11e7-8509-b73d701dfb99.png">
