### ISSUE TITLE
Create a link under a document ID that links to the IDT document 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#10479]
Example link: `ms-word:ofe|u|file:////bvacofil.dva.va.gov/dt1/Board/01826/01826-00000162.docx`
Slack discussion: https://dsva.slack.com/archives/CD5DAQNCU/p1554465049013400

AC: Create a link under a document ID that links to the IDT document

**Comment by hschallhorn** [comment]
Ensure we are handling all formats of decision doc ids. Ensure we have the correct document url format. (Dustin).
Run through design to confirm how this should look to the user.

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||||
3 | |||||||||
5 | 
8 |  
```
Really just building a string. Discovery for formatting and design moves this up to a 3. _Some_ people on the team aren't great on css so meeting design reqs might be hard.
