### ISSUE TITLE
`issue` is undefined in AddEditIssueView -> LegacySelectDispositionsView

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10478]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4676/

based on the URL in this sentry error, the issue is undefined on line `148` of `LegacySelectDispositionsView.jsx`

**Comment by jcq** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8224/
