### ISSUE TITLE
RangeError in finding a rating_issue_reference_id

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10477]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4666/events/306554/

https://appeals.cf.ds.va.gov/supplemental_claims/71147733/edit

**Comment by pkarman** [comment]
These appear to come from clicking the "Edit in Caseflow" link in VBMS for Supplemental Claims created for DTA errors. I am ignoring these in Sentry since we already present the appropriate message to the user.
