### ISSUE TITLE
Bug: Overwriting hearing dates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#10476]
We have three support tickets of hearing dates that have been overwritten accidentally. We need to update the hearings in VACOLS to the correct hearing date
- [x] https://github.com/department-of-veterans-affairs/appeals-support/issues/5012
- [x] https://github.com/department-of-veterans-affairs/appeals-support/issues/4991
- [x] https://github.com/department-of-veterans-affairs/appeals-support/issues/4978

We also need to determine where the hearings are being overwritten. I believe it's in the hearing prep daily docket. I've merged a PR to not send hearing date/time information to the backend from the hearing prep daily docket. That will be deployed the morning of 5/18. 

It also might be happening on the hearing schedule daily docket. I have a PR to update that daily docket such that we only send edited fields to the backend. This can be merged once it's approved. 

#10475

**Comment by tomas-nava** [comment]
All the dates in the support tickets have been fixed; we can close this issue when #10475 is merged.
