### ISSUE TITLE
Increasing number of corrupted files in eFolder Express

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#10504]
### Context 
We have been getting increased reports of corrupted files and downloads in eFolder Express. There can be a few reasons for this corruption: 

- Large file sizes
- Access levels
- Tiff files (fillable pdf issues)
- Windows vs mac (mostly Windows but there is a known issue where windows zipping can be the cause)

### For support issues: 
Please work with the user to gather the above information if possible and engineering to get the rest. 

### Support messaging 
Please relay to the user that we are aware and investigating. However, for urgent and semi-urgent files they should revert to the pre efolder express VBMS process as this will not be an immediate fix. 

### List of known appeals: 

Please add the random generated **appeal id in our app URLS** here (please note to **not place the the actual veteran id)**

440433
420989
45681
354125

### Related Issues: 
[#854 in efodler express repo](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/854)

### Related document 
Related document: Please see [this file](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Project%20Folders/Caseflow%20Projects/eFolder%20Express/Maintenance%20Framework%20(eFolder%20Express).MD) for related bugs and research including:

- Total memory usage of EC2 at the time
- Triaging for efolder express bugs

**Comment by msj0nes** [comment]
# Issue Folder

https://efolder.cf.ds.va.gov/downloads/420989
