### ISSUE TITLE
Fix nonrating category scrollbar

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10514]
In the nonrating issues modal, users are experiencing issues with selecting a category using the scrollbar, they are unable to scroll down (it resets and goes back to the top).  

This is being seen in Internet Explorer, which in this case was the default browser used to open up the Edit Page from VBMS.

I'm separating this from the below issue since the scrolling issue described is different, and affected a regular user without a mouse.

Related:
https://github.com/department-of-veterans-affairs/caseflow/issues/9170
https://github.com/department-of-veterans-affairs/caseflow/issues/1792

**Comment by pkarman** [comment]
We don't officially support IE so closing this.
