### ISSUE TITLE
Ability to intake decision reviews with missing ratings/issues 

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10511]
## Background
When a claims assistant is intaking an AMA claim for rating issues, Caseflow present a list of past rating issues to the user to select from.  Caseflow first fetches a list of the veteran's promulgated rating profiles, and then fetches the list of issues on each rating profile.  The issues indicate which issues changed from the previous rating profile (disabilities that were "at issue").

If a rating issue is not found, the user is currently directed to add an "Unidentified issue", which gets added to a rating end product.  The contention created in VBMS does not contain the issue description. Instead it indicates that the issue needs to be edited in Caseflow, where it can be removed and the correct issue can be added in its place if available.

For Supplemental Claims, there is not a timeliness requirement for contentions, so a veteran can submit a supplemental claim for decisions from any time in the past.  Some issue data, particularly for old issues, is not currently available.

Before 5/2/2003, ratings were stored on a user's individual computer.  Ratings created after that were created on the new system.  The old ratings can be backfilled, creating a backfilled rating.  Caseflow does not currently have access to the backfilled ratings, but it is something that can be added.  To do: add information about which backfilled ratings are technically considered promulgated (issues from the old system, issues that didn't result in a rating but were on a cleared EP).

Currently, for non-rating issues, we do not have access to the issue's historical data. We have users add them in Caseflow for the first time.  If that issue comes through AMA again, it is connected to that first issue and its history is tracked from there.

**Examples of missing ratings (to do: find specific examples)**

- Issues from before 2003
- Potentially issues after 2003 (denied issues that didn't result in a rating? Issues that just haven't changed since 2003?)
- Previously denied pension issues that do not have a rating

## Possible solutions 
(to do: add pros and cons, some information about what would be needed from Caseflow/BGS for implementation)

- Allow rating issues that aren't connected to their previous rating issue. We would collect the relevant information for this issue that would allow a VSR to confirm its decision.  Potential option to backfill data if we can get the data needed populated in BGS. **(Recommended)**
- Add rating issues that are connected to a disability if available. Not all missing issues will have this. This will not allow us to track the history of an issue before AMA. More investigation is needed on how to connect these.
- Connect issues to backfilled ratings, but without connecting to a specific issue.  We have heard that backfilled ratings do not have the individual issues on them, but we could potentially still connect the issue to the rating profile without connecting it to the issue. This requires Caseflow to be able to retrieve backfilled ratings.  This will not allow us to track the history of the issue before that rating.
- Investigate whether we can add rating issues to backfilled ratings. (to do: Ask Linda about this, and also for the data from an example backfilled rating so I can look at it)
- Investigate whether it's possible to make a regular promulgated rating profile with the rating issues, whether by creating a new rating profile or converting a backfilled rating to a promulgated rating, with the correct promulgation date from the past. 

---
Original ticket content:

We have seen multiple cases of ratings from 1998 not being returned from BGS. The one specific example we looked into was "denied" on the decision document.  We did not get the "backfilled" error from BGS.

When CAs intake these for a Supplemental Claim, they are often using the nonrating issue modal to intake them, and they are being put on a nonrating EP.  This is preventing further processing on these claims and causes a work stoppage.

Potential areas of investigation:
1. Questions for BGS
    - Why are these ratings not being returned from BGS?
    - At what date does this start happening?
    - Does this only affect denials?
    - Can this be fixed via BGS?  (is there a data record for denials?)

2. Add issues flow adjustments
    - Make it clearer that the middle modal is to add nonrating issues
    - Allow user to add a rating issue that is not connected to a previous rating issue, but is not "Unidentified". This will start the data chain for that issue.
    - How do we prevent folks from using this for issues that could otherwise potentially get returned and properly connected (e.g. locked or backfilled ratings)

3. End Product Code
    - Consider allowing users to edit the End Product Code. Note we do not have the ability to do this with VBMS currently, we would have to cancel and end product and create a new one.  Preference is to not have to do this by resolving the underlying issues.

Potential workaround until final resolution:
- Have users change the End Product Code in SHARE, and manually track all request issues that this happens to so that we can make sure they are correctly designated as rating issues in our system (which affects DTA claims, and request issues on a future AMA claim if the issue is intaken again).  This could be done by detecting the change to the end product code, and designating issues on a rating end product to be rating issues.
- Prefer not to do this if possible to resolve programmatically within an allowable timeframe

**Comment by leikkisa** [comment]
BGS does not have any ratings before 5/3/2003.  If a rating is before that, then a Rater needs to backfill it in a system.  

We should try to talk to Jan Ostrum to get more information about this process (like which system this happens in).

If a rating is backfilled/converted, currently those are not returned to us.  BGS could return those to us with permission from Comp Services, but we have been warned that this could be a lot of data. This could also be part of the conversation about a new service.

One idea we had was to allow a user to add a rated issue without being connected to a previous rating, expecting a rating to be created as part of the decisions, and starting the issue chain there.  Linda said that this would be problematic, because rating data is complicated.  So for the time being, we will continue to have users use the "Unidentified issue" and investigate the backfilled ratings more.

**Comment by leikkisa** [comment]
My proposal is:

Have a place in the UI for a user to enter the information about the rating that is missing, including the decision text and date.  Have it added as a rated issue that is not associated to a rating.  We may want to use the Unidentified issue modal for this.  It seems to me that users would never use this modal for unidentified nonrating issues, since they can just use the nonrating issue modal for that.

Have this somehow kick off a task for a RVSR to backfill the rating based on that data.  This is the big question mark for now in terms of process flow.

Then have the request issue updated to associate it to the rating issue (and the vbms call to associate the rated issue to the contention).

**Comment by laurjpeterson** [comment]
Discussion with Carola and LP 5/22. Will result in additional tickets.

**Comment by leikkisa** [comment]
Adding these notes about missing ratings:
Reporting a couple of pension issues:
1.  Due to the unique workflow of pension work,  the PMCs are experiencing an issue with assigning the correct labels to 040s.  The PMC is unable to establish an 040 with the correct label when no rating was previously completed even if a rating is currently required.  The PMC requires the ability to select the appropriate label to ensure the claim is routed within the station to the appropriate team.  Additionally, this ability is needed to ensure the PMCs receive the proper credit for work done.

One substantial difference between the pension workflow and compensation workflow is that rating EPs may be denied prior to a rating being completed.  When the supplemental claim is received a rating is still required.  Traditionally these “reconsiderations” would be worked under a rating EP (020 for DIC and 120 for pension).  The PMC believes that based on the new EPs and claim labels, these would be worked as “040 - PMC Supplemental Claim Rating”.  Below is a list of common scenarios that necessitate the PMC to have the functionality to decide which label is appropriate.

**Comment by laurjpeterson** [comment]
One scenario we're sure of is ratings are earlier than 2003. We should create a separate ticket for the implementation of this.

**Comment by leikkisa** [comment]
https://dsva.slack.com/archives/CFBLH2LR4/p1557853364144700

**Comment by laurjpeterson** [comment]
[BSE 64638 - Capability to Expand Caseflow Capacity to Additional Decision Types and Dates.docx](https://github.com/department-of-veterans-affairs/caseflow/files/3383366/BSE.64638.-.Capability.to.Expand.Caseflow.Capacity.to.Additional.Decision.Types.and.Dates.docx)

**Comment by pkarman** [comment]
The DRO/RVSR can associate the “unidentified issue” with the appropriate contention under the Issue Management tab from the drop down menu in VBMS-R.  VBMS-R is the program where DROs and RVSRs input the rating dispositions.

![jane-img1](https://user-images.githubusercontent.com/1205061/61491532-12038880-a975-11e9-9a3b-eb605f018bf2.png)

Please see the screenshots.  The Claim ID:  73128154  The example is Veteran is claiming bilateral hearing loss.  The contention of bilateral hearing loss is in the Corporate database but not pulling into Caseflow during Intake.  The claim was established with the correct EP claim label with Rating. 

 
![jane-img2](https://user-images.githubusercontent.com/1205061/61491581-2a73a300-a975-11e9-8f6d-a08f3d1cd6d6.png)


VBMS shows the “unidentified issue”

![jane-img3](https://user-images.githubusercontent.com/1205061/61491604-2f385700-a975-11e9-9e04-a84b000ef42f.jpg)


Even if user tries to edit in Caseflow, they are unable to.  User can proceed to VBMS-R.

![jane-img4](https://user-images.githubusercontent.com/1205061/61491614-38292880-a975-11e9-8cbc-691fac60b25a.png)


In VBMS-R, the “unidentified issue” shows under “Contentions” from there the DRO/RVSR can associate the “unidentified issue” with the appropriate subject as seen in the drop down list.  Here, bilateral hearing loss is available.
VBMS-R pulls from the Corporate database so those contentions that may not be showing in Caseflow, would show here.   The question is by associating the “unidentified issue” to a contention in VBMS-R, will that link it to Caseflow to now start tracking?
 



 

Now the “unidentified issue” is established.
 



 

The only time this would not work is if the contention is not in the Corporate database.  If this is the case, then a backfill rating will need to be done to populate the contention into the Corporate database.  Again, the contention will not show in Caseflow but it will now appear in VBMS-R as it is in the Corporate database.

**Comment by pkarman** [comment]
There are now several YourIT tickets in relation to this bug. https://github.com/department-of-veterans-affairs/appeals-support/issues/5319

@leikkisa and I talked about a possible way forward that involves pulling different categories of data from the BGS API response. I am going to prototype that.

**Comment by leikkisa** [comment]
Hi, the new service is at rating_profile.find_in_date_range, in ruby bgs.

**Comment by leikkisa** [comment]
Adding a note to plan for TDIU issues, which won't have previous ratings, but should be added as rating issues.
https://dsva.slack.com/archives/CFBLH2LR4/p1565639541096200

**Comment by pkarman** [comment]
Good example of pre-2003 BGS response in production
```
bgs.rating_profile.find(participant_id: 4563635, profile_date: "2003-05-03T00:00:00-05:00")
```

**Comment by pkarman** [comment]
I've opened #11840 to specifically track the missing rating decisions from before 2005. First PR in #11813

**Comment by msj0nes** [comment]
# Scenarios With Missing Ratings 
https://github.com/department-of-veterans-affairs/appeals-support/issues/5319#issuecomment-526672743

**Comment by pkarman** [comment]
As noted here https://github.com/department-of-veterans-affairs/caseflow/issues/11840#issuecomment-530372123 we are seeing positive results from including the not service connected rating decisions as part of Intake. Not yet sure if it 100% resolves this problem, but a positive step.

**Comment by leikkisa** [comment]
Created SR-002323 to fix the new ratings endpoint in prod:
https://escp.aac.va.gov/ServiceRequest/Details/13780?isDraft=false

**Comment by leikkisa** [comment]
AMO is having users test taking in unidentified issues that are not connected to a rating, but where the actual description is sent as the contention text.  This is to test a new flow for adding "verified" unidentified issues.

Logging the details of the "test case" here:
https://dsva.slack.com/archives/CFBLH2LR4/p1571395289043600

**Comment by msj0nes** [comment]
## Stakeholder Meeting
**Discussion**: Rating Issue with Promulgation Dates in the Future of Form Receipt Dates
**Proposal AMO Approved**: Modify promulgation use in Caseflow to restore missing ratings.
[Meeting Minutes](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Caseflow%20Projects/Foxtrot/Meeting%20Minutes/AMO/1_6_2020.md)

**Comment by msj0nes** [comment]
# Update 
Caseflow data gathering needed to evaluate missing ratings success.

**Comment by msj0nes** [comment]
Ticket closure - Use #13088 to track requirement 'Missing Ratings'.
