### ISSUE TITLE
RAMP intake referring to wrong user

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10523]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/309792/

For intake 153482 the user is `AMCMAWIL` but the EPE refers to user `AMCAFERG` who is no longer active.

Seems like whatever is associating the Intake with (maybe an existing?) EPE needs to coordinate the `user_id`.

**Comment by leikkisa** [comment]
I'm seeing a couple of recent examples of this for a Supplemental Claim, but no more for RAMP (this fix is specifically for RAMP), and I don't see how we would validate this otherwise. So I'm closing this for now, and if it comes up again we can re-open.
