### ISSUE TITLE
Document User authorization patterns

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10521]
There are multiple ways we authorize users.

* CSUM functions https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/functions-config.yml
* User roles

Create a `docs/user-authorization.md` document describing how/why both patterns exist and the proper one to choose for a particular use case.

**Comment by laurjpeterson** [comment]
This is a good task for product managers to take a first pass at, I think. By user roles, do you mena VACOLS user roles? Moving to define.

**Comment by pkarman** [comment]
> By user roles, do you mena VACOLS user roles?

I meant the roles that appear in a `User` record in Caseflow, however it is that they get there. The motivation for this ticket was understanding the technical mechanics, as well as the history. The specifics of authorization rules (who should get access to what) does seem like a PM thing.

**Comment by ferristseng** [comment]
@pkarman Does the documentation that Lauren wrote up cover this? (https://github.com/department-of-veterans-affairs/caseflow/wiki/User-access-permissions-in-Caseflow)

**Comment by pkarman** [comment]
yup!
