### ISSUE TITLE
Bug: Null hearing dispositions are showing up in the Schedule Veterans List

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10522]
Some null dispositions after the hearing day has passed are showing up in the Schedule Veterans list without the blocking Change Disposition task. These appeals are also not showing up in the Team Queue to be worked. 

There is a Schedule Veteran task and when you try to schedule, it does block you from doing so, instead of the modal appearing, there's a banner at the top of schedule Veteran that shows there's already a scheduled hearing. 

Example:
https://appeals.cf.ds.va.gov/queue/appeals/3150928/?hearingDate=2019-04-25&regionalOffice=RO17&hearingTime=

**Comment by MeredithStewart** [comment]
We looked, but couldn't find another appeal doing the same thing. Tamisha apparently reported this in a support ticket already.

**Comment by lomaxap** [comment]
will be resolved with #10630
