### ISSUE TITLE
Remove VLJ and attorney names from case title for removed appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10547]
When appeals have been removed, also remove attorney and judge names from the case title, to prevent confusion about this appeal.

Here is the case title:
![image](https://user-images.githubusercontent.com/32683958/49970117-5834cd00-fef8-11e8-92c8-9974be445a56.png)

**Comment by pkarman** [comment]
is this the same thing as closing all the tasks? I assume that's where the names derive.

**Comment by laurjpeterson** [comment]
It seems like the tasks are being canceled as it's been implemented today (like the JudgeAssignTask or JudgeDecisionReviewTask or AttorneyTask), but the judge and attorney names in case title aren't. 

I did remove all issues and then the entire appeal, and confirmed that the case no longer showed in the Judge or Attorney's queue.

**Comment by leikkisa** [comment]
@pkarman Do you know if for this ticket if we are just wanting to hide the names on the front end, or unassign the judge/attorney instead?

**Comment by Sjones352** [comment]
@pkarman, @leikkisa  or @aroltsch 
Do you know if for this ticket if we are just wanting to hide the names on the front end, or unassign the judge/attorney instead? if we unassign judge/attorney then that means we have no record of who it was assigned to before it was withdrawn. I also think it will not show up on Judge's queue if it is removed.

Currently this is how I have it on the frontend. Please let me know if I need to adjust it in anyway.
**Added Issues**
<img width="1277" alt="Screen Shot 2019-06-06 at 9 51 50 PM" src="https://user-images.githubusercontent.com/23080951/59076776-bb029200-88a5-11e9-9983-3507198c6e78.png">
**Removed Issues**
<img width="1273" alt="Screen Shot 2019-06-06 at 9 37 11 PM" src="https://user-images.githubusercontent.com/23080951/59076571-c2756b80-88a4-11e9-8290-f5d656c31bf3.png">

**Comment by pkarman** [comment]
I think it's remove the names visually on the frontend. We should preserve data integrity on the backend.
