### ISSUE TITLE
Do not show removed reviews in search results/case list

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10546]
When a user has removed all issues from an appeal/HLR/SC and removed the review entirely, we should not show the appeal/HLR/SC in Caseflow's search results, so we don't confuse users that the appeal is still relevant.

## AC
- Removed appeals/HLRs/SCs do not show in Caseflow search results (or Caseflow case list)

**Comment by leikkisa** [comment]
@laurjpeterson I'm assuming the "Caseflow search results" and the "Caseflow case list" are the same thing, but let me know if there are two places I should check.

**Comment by laurjpeterson** [comment]
@leikkisa - yep, they're the same thing!

**Comment by Sjones352** [comment]
**Fails UAT**

This file had 2 non-ratings removed but when I search the case, I still find it 
![Screen Shot 2019-05-10 at 11.48.55 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/1491c608-6576-4803-816f-a580dd98b10b)![Screen Shot 2019-05-10 at 11.49.15 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/d73068b0-1936-4a9b-baf7-26ecd59211b5)

**Comment by leikkisa** [comment]
@Sjones352 This Veteran has 6 HLRs, and one of them is not showing up (probably the removed one), so I think the issue is the validation approach.

I tried this on the same Veteran with a Supplemental Claim, and it showed up on the Case Search page after creating it (there were two Supplemental Claims) and disappeared after removing all of the issues.

**Comment by Sjones352** [comment]
**Passes UAT*
https://appeals.cf.uat.ds.va.gov/cases/1604. The Supplemental Claim does not show up on search page

![Screen Shot 2019-05-14 at 3.12.05 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/97d09a43-f4c5-4947-a9c6-f09d17b0af03)
![Screen Shot 2019-05-14 at 3.13.26 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/17045f93-81bd-4488-bc87-e2b073265c69)
![Screen Shot 2019-05-14 at 3.13.42 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/9075c2fc-e034-4d3d-a368-3d0b366b7054)
![Screen Shot 2019-05-14 at 3.14.22 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/f903534a-a54e-4286-9f63-ee6944771b04)
![Screen Shot 2019-05-14 at 3.14.58 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/7a8525d8-e353-4532-a031-514d6a752fdd)
