### ISSUE TITLE
Bug: Judge can postpone from case details

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10556]
Judge shouldn't be able to postpone from Case details -- with options. They should only be able to postpone from the daily docket. 

This Veteran: https://appeals.cf.ds.va.gov/queue/appeals/cb64e0f5-2d57-4466-8ae5-14f11e3e6ce6 

Logged in as judge, they have ability to postpone from Case Details (which only the hearing branch should be able to do).

**Comment by MeredithStewart** [comment]
Confirmed, second judge also has these options.

**Comment by ShellySmithDSVA** [comment]
Logged in as a judge, and have Postpone options in case details for case. https://appeals.cf.ds.va.gov/queue/appeals/3691667
