### ISSUE TITLE
Caseflow::Error::DuplicateOrgTask on duplicate ChangeHearingDispositionTasks

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10554]
[Sentry issue](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4673/events/)

The HearingDispositionChangeJob [is pulling in `ChangeHearingDispositionTask`s as well as `DispositionTask`s when collecting tasks to act on](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/hearing_disposition_change_job.rb#L18); it should only pull in `DispositionTask`s.

It's generating errors but leaving tasks in the state they should be in.

**Comment by lomky** [comment]
Looks like we may have already fixed this. This task is now to confirm whether or not that's correct!

**Comment by monfresh** [comment]
Looks like this is still happening: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5946/events/420785/
