### ISSUE TITLE
Does VBMS gender value affect can_access? visibility

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10566]
See https://github.com/department-of-veterans-affairs/appeals-support/issues/4851

**Comment by hschallhorn** [comment]
https://dsva.slack.com/archives/C2ZAMLK88/p1556049156107500

**Comment by yoomlam** [comment]
More notes regarding VSO permissions: https://dsva.slack.com/archives/CJL810329/p1594920673155100

**Comment by hschallhorn** [comment]
Closing. Have not heard of this being an issue since the first instance. If BGS.can_access? is failing, what can we do on the caseflow side?
