### ISSUE TITLE
Filtered Judge View of Hearing Schedule

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10563]
Currently, judge view of the hearing schedule is (1) hearing days that are assigned to them, and (2) hearing days with individual hearings that are assigned to them. We could give judges the entire hearing schedule and allow them to filter. But, they wouldn't be able to see their assigned hearings (as opposed to hearing days), so **we think we should do this filtering for them.**  

## User Stories
As a judge, I need to see my schedule first when I log in so that I can focus on my hearing days and prepare accordingly. 

As a judge, I need to see the entire hearing schedule so that I can easily switch days with other judges. 

## Mocks
Original mocks can be found in Invision here: https://va-gov.invisionapp.com/share/PMR1ID7XSHT#/screens/353826170

![Screen Shot 2019-04-25 at 5 43 25 PM](https://user-images.githubusercontent.com/45463980/56771362-66d3a080-6784-11e9-9c18-73458d677a25.png)

## Acceptance Criteria
- [ ] Verify the Schedule view lists AMA and Legacy video, CO, and travel board hearings that are by default filtered by that judge.
- [ ] Verify the judge has the ability to clear filters and see the entire schedule ahead of time

## Associated Tickets
#10139 - Hearing Prep Refactor

**Comment by sharonwarner** [comment]
This will need more design work. 

Our current judge logic displays all hearing days assigned to a judge and all hearing days with individual hearings assigned to a judge. The frontend filters won't display hearing days with individual hearings assigned to a judge. We'll need a different link to go between the two views.

**Comment by ShellySmithDSVA** [comment]
@Chingujo and @pshahVA will be working on updating this.

**Comment by Chingujo** [comment]
@sharonwarner @pshahVA 

Here is my proposed solution to the filtering. If we a agree, I will clean the AC up and create the relevant ticket for the changes to the other views. 

This is a good opportunity to standardize some of our styles across queue. Queue uses our "download current view" as the toggle for switch views that was added after we implemented ours. We can use that in the hearing table. So judges would see this: 

_Title of this page would "Your Hearing Schedule" 
- Download current view is moved to above the table as a link with the download icon in build schedule and eFolder express. The button is now gone

![Schedule view judges](https://user-images.githubusercontent.com/23316107/57631058-c5fb2880-756c-11e9-978c-cedd3399834c.png)
  
_Switch view toggles the view from their view to the full schedule like in the Queue switch view_
![Schedule view expanded](https://user-images.githubusercontent.com/23316107/57631071-cb587300-756c-11e9-9618-7d108620fd45.png)

_Title of page is now "Hearing Schedule"
![Changed view](https://user-images.githubusercontent.com/23316107/57631144-ec20c880-756c-11e9-9b51-d917a028fd83.png)



_________________
This would mean for hearing coordinators their view would now be the mock below. With VSO and RO views will only have the download. 

![Schedule view for hearing coordinators](https://user-images.githubusercontent.com/23316107/57631249-238f7500-756d-11e9-8fcf-3027bc899a44.png)

**Comment by laurjpeterson** [comment]
talked with @sharonwarner and @pshahVA about this one and learned that @Chingujo is doing the design work for it. 

@Chingujo - If we are auto-filtering, can we include text so judges understand the view that they're looking at? (i.e. This is a view of your hearing days and hearings, not the entire view of the Board's hearing schedule)

Also, Sharon noted that this could require a much larger refactor, so we should vet whether this is absolutely needed/requested by judges.

**Comment by Chingujo** [comment]
It would have been useful to be in this conversation @laurjpeterson @pshahVA @sharonwarner 

So, I could get the feedback first hand. That text can be added and this can be scoped to an easier view

**Comment by lomaxap** [comment]
The [hearing day controller](https://github.com/department-of-veterans-affairs/caseflow/issues/6777) filters hearing days [based on the user's role](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/hearing_day.rb#L157). Would need to either add a parameter to request to bypass this logic, or return all hearing days and filter on the front end.

Inside the daily docket, I think we're also filtering hearings by judge, so the judge only sees hearings assigned to them. We would also need to remove that filter.

**Comment by Chingujo** [comment]
@lomaxap 

For placement, the download current schedule link in the mocks above for the Judge VIew should be in place of the Add hearing date link in the "Build Schedule" role view of the hearing schedule. 

![Screen Shot 2019-07-19 at 7.27.50 AM.png](https://images.zenhubusercontent.com/5cd1c04a562e0605ea3b7719/cb45879b-7eb4-4672-b4b9-ce21cd79e789)

_In the new Judge view_
![Schedule View.png](https://images.zenhubusercontent.com/5cd1c04a562e0605ea3b7719/e48390b2-6fb3-4ffc-ac71-5b5329de188e)
