### ISSUE TITLE
Allow judges to "Correct Issues" from Case Details when they are assigned a hearing

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#10562]
User story: A judge needs to be able to correct AMA issues in advance of or on the day of the hearing. 

This functionality was not deployed prior to checkout to a Judge. An appeal is assigned to a judge in a hearing, but that's prior to checkout for a decision.

Investigate how easy it is to turn the "correct issues" link on for judges/attorneys when they aren't assigned a task.

## Idea
- When a judge is assigned a hearing, they can see the Correct Issues link
   - use `appeal.hearing.last.judge`

**Comment by MeredithStewart** [comment]
Someone should investigate and weigh either doing this for judges through Case details, or just doing this through the Hearing Prep worksheet. We had originally planned (now a backlog ticket) to do this on the worksheet, but had de-prioritized because we thought the correct issues link would be there on Case details for judges for hearings.

**Comment by laurjpeterson** [comment]
Note: could be good for teams who know queue to do so they can get context on hearings

**Comment by lomaxap** [comment]
@laurjpeterson we're not sure how to prioritize this for the next sprint. can you give us a sense? We think this should be ranked pretty

**Comment by pkarman** [comment]
Let's feature flag this with `:allow_judge_edit_issues` so that rollout is in the hands of product folks.

@lomaxap not a high priority.

**Comment by ferristseng** [comment]
## Adding Issues

<img width="1465" alt="Screen Shot 2019-08-12 at 10 44 31 AM" src="https://user-images.githubusercontent.com/1298274/62874581-85d44f00-bcef-11e9-802f-6c4cab615e0f.png">

<img width="1513" alt="Screen Shot 2019-08-12 at 10 45 06 AM" src="https://user-images.githubusercontent.com/1298274/62874608-8ff64d80-bcef-11e9-8e89-e925715bf600.png">

<img width="1513" alt="Screen Shot 2019-08-12 at 10 52 02 AM" src="https://user-images.githubusercontent.com/1298274/62874624-9684c500-bcef-11e9-987e-8fd0c6e887d7.png">

<img width="1513" alt="Screen Shot 2019-08-12 at 10 52 24 AM" src="https://user-images.githubusercontent.com/1298274/62874632-9c7aa600-bcef-11e9-96ff-c2158ea874a6.png">

<img width="1513" alt="Screen Shot 2019-08-12 at 10 52 32 AM" src="https://user-images.githubusercontent.com/1298274/62874642-a0a6c380-bcef-11e9-9428-8ef80f1ac1ca.png">

<img width="1276" alt="Screen Shot 2019-08-12 at 10 52 55 AM" src="https://user-images.githubusercontent.com/1298274/62874656-a7353b00-bcef-11e9-9b62-a2bd5821b1c0.png">

## Removing Issues

<img width="1486" alt="Screen Shot 2019-08-12 at 10 53 10 AM" src="https://user-images.githubusercontent.com/1298274/62874662-aac8c200-bcef-11e9-8e31-fb36408884f9.png">

<img width="1486" alt="Screen Shot 2019-08-12 at 10 53 21 AM" src="https://user-images.githubusercontent.com/1298274/62874668-adc3b280-bcef-11e9-88f7-5987fe7b458a.png">
