### ISSUE TITLE
Distinguish between reassigned and completed tasks in Case Timeline

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10572]
Currently we display all closed tasks with green check marks in the case timeline regardless of whether they were cancelled or completed. When we re-assign a task from one person to another we cancel the original task. This results in the original task being added to the case timeline and suggests that the task was completed when in reality it may not have been (see [a related support issue](https://github.com/department-of-veterans-affairs/appeals-support/issues/5016) highlighting just this issue).

![image](https://user-images.githubusercontent.com/32683958/56822156-35a7ae80-681e-11e9-80e1-0749886e8ca9.png)

A few thoughts off the top of my head on how we could make the distinction between completed and reassigned tasks clear in case timeline:
* Hide cancelled tasks from case timeline
* Change the green check to a red x for cancelled tasks
* Add a note to the instructions field of tasks that are reassigned indicating that they were reassigned

## Acceptance criteria
* [ ] Make a design decision on how to handle this situation

**Comment by hschallhorn** [comment]
This is done!

Place|Before reassign|After reassign
---|---|---
Task Snapshot|![Screen Shot 2020-07-08 at 3 51 45 PM](https://user-images.githubusercontent.com/45575454/86963831-1e0eca00-c133-11ea-8e0e-f0fef1f7e44c.png)|![Screen Shot 2020-07-08 at 3 52 11 PM](https://user-images.githubusercontent.com/45575454/86963840-223ae780-c133-11ea-86fc-f1e9a8a7ab1b.png)
Case Timeline|![Screen Shot 2020-07-08 at 3 51 38 PM](https://user-images.githubusercontent.com/45575454/86963878-3979d500-c133-11ea-86f0-e4248f2243c7.png)|![Screen Shot 2020-07-08 at 3 52 25 PM](https://user-images.githubusercontent.com/45575454/86963893-3e3e8900-c133-11ea-8d22-bd08b05acdb6.png)
