### ISSUE TITLE
VBMS error on Vet and POA establishment

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10574]
```
Unable to establish claim: ORACLE ERROR when attempting to store PTCPNT_RLNSHP 
between the vet and the POA ORA-00001: unique constraint (CORPPROD.PK_PTCPNT_RLNSHP) 
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4403/events/310763/

**Comment by pkarman** [comment]
possible dupe of #10560?

**Comment by leikkisa** [comment]
The Veteran is not deceased, and it's not happening on the relationships call, so this seems like a different issue.  The other ticket might be due to data issues though, so that could be affecting this one as well.

**Comment by leikkisa** [comment]
From Nathan Jolly: This is related to the multiple POA cleanup which is still outstanding.

**Comment by leikkisa** [comment]
This is resolved! Closing.
