### ISSUE TITLE
Date Range Error for VSO Hearing Schedule View

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#10589]
VACOLS can only handle 1000 hearing days requests, so we should show an error to users if they selected a date range that has more than 1000 hearing days.

## Acceptance Criteria

- [ ] Verify that when over 1000 hearing days are queried the error displays asking the user to limit their date range further.

## Mocks
https://va-gov.invisionapp.com/share/QARRMSMUJDW#/360595099_VSO_Over_1000_Error

![Screen Shot 2019-04-29 at 2 09 55 PM](https://user-images.githubusercontent.com/45463980/56917073-84f11780-6a88-11e9-91f6-a3e54ba2a7b1.png)

**Comment by pkarman** [comment]
@carodew you'll likely want to review this to make sure it is consistent with patterns you are considering.

**Comment by nicholer** [comment]
@pshahVA Do you have a sense of priority on this? Fwiw, design level of effort seems low.

**Comment by pshahVA** [comment]
low priority!  Added label.

**Comment by pshahVA** [comment]
No longer an integration with VACOLS.
