### ISSUE TITLE
Fix usage of keys in React

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1058]
In many points in our code, we generate arrays of React components and assign keys to integer index values. This is a bad pattern and can cause performance errors.

http://blog.arkency.com/2014/10/react-dot-js-and-dynamic-children-why-the-keys-are-important/

**Comment by nickheiner-usds** [comment]
I agree that this is generally bad practice. In rare cases, it can be ok. And apparently we are not going to prioritize going through and fixing this for old code. We should be mindful about it going forwards, though.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
