### ISSUE TITLE
Intake | Add reminder to use encrypted email for PII when adding claimants

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10586]
## Description
When users are doing an intake, if they don't see a dependent claimant, they email VACaseflowIntake@va.gov with a request, which is handled by Jennifer Umberhind.

Users have been sending clear text email with PII (names and file numbers).  So we'd like to add some instructions to remind them to use encrypted email.

## Acceptance criteria
- [ ] Update claimant selection help copy (see copy below)
- [ ] Include a screenshot in this GitHub issue

## Copy
Please select the claimant listed on the form. If you do not see the claimant in the options below or if the claimant's information needs to be updated, please email for assistance. **Note: Remember to encrypt any emails that contain PII (such as a veteran or claimant's name, file number or SSN)**.

## Tech notes
See `SelectClaimant.jsx` and `COPY.json`

**Comment by pkarman** [comment]
We should remove vacaseflowintake@va from the bcc list.

**Comment by leikkisa** [comment]
I'd like to suggest directing users to YourIT if that's a viable option.

**Comment by leikkisa** [comment]
Do we want to add any info on how to send encrypted emails? It seems to me like they should know that.

**Comment by rutvigupta-design** [comment]
Noting that from user research, no Intake users actually have access to the Corporate Database. Can we revise the part of this copy that asks them to add a claimant to the Corp DB? My copy suggestion: 

"Please select the claimant listed on the form. If you do not see the claimant in the options below or if the claimant's information needs to be updated, please email for assistance. Note: Remember to encrypt any emails that contain PII (such as a veteran or claimant's name, file number or SSN)."

**Comment by leikkisa** [comment]
Updated and moving to the eng backlog. Thanks Rutvi!

**Comment by wdrougas-tista** [comment]
In the copy above, only half of the text is bolded. Screenshot provided has all text bolded. Does that need to be changed?

[Screen Shot 2020-08-07 at 11.10.49 AM.png](https://images.zenhubusercontent.com/5e976ddfed689a8dc52aee6c/4e2da262-8707-45e8-ba23-ac6094d71600)

**Comment by leikkisa** [comment]
@wdrougas-tista I was trying to highlight the part that changed, but since then more has changed so I can see that it's confusing. You can go ahead and use the copy @rutvigupta-design is suggesting, and don't worry about changing the bolding.

**Comment by rutvigupta-design** [comment]
@leikkisa just confirming that this copy change will be reflected throughout Intake (including attorney fees)?

**Comment by leikkisa** [comment]
@rutvigupta-design I think whether the attorney fees feature toggle is on or off, this text should show. But I can see how it's confusing, because now they can also add a claimant, but only an attorney claimant.  So the instructional text needs to be adapted somehow.

I wonder if we should show a radio button for "Attorney", and if they select that, then show the "Add claimant" button.  Because then "Attorney" shows up in the options below, and the copy is still relevant.

**Comment by rutvigupta-design** [comment]
@leikkisa I agree, I think this is generic text that should be there for now. I think when we do switch the attorney fees feature toggle on, this instruction text should be adapted. Should we open a separate ticket for this?

I would be hesitant to add in a radio button without testing, and think that we can think through this a bit more with non-Veteran claimant work (e.g. perhaps a button for "third parties"?). So for now, I would like to have any larger design considerations out of scope, but I think the instructions are important to address!

**Comment by leikkisa** [comment]
@rutvigupta-design Yeah let's make a ticket for it. I got something started, and moved it into the "Design backlog", here's the link:
https://github.com/department-of-veterans-affairs/caseflow/issues/15001

Please feel free to update it!
