### ISSUE TITLE
New column for edited contention text

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10596]
Step 2 of editing request issue title. In Step 1 we added the UI element. In this step, we add the database column and server-side changes.

## Definitions

* "original text" here means the generated title text derived from the contested rating issue description.
* "edited text" here means the user-entered title text

## Acceptance criteria

* When a new request issue description is sent to the server, save it to a new column on the `RequestIssue` model.
* When creating contentions prefer the edited text if it is defined.

## Technical notes

* Add a new column `rating_issue_description` for storing the user's edited title. Preserve the `contested_issue_description` for the original text, so that the user can "undo" their edits.
* The `description` method in `RequestIssue` should prefer `rating_issue_description` over `contested_issue_description` if `rating_issue_description` is not nil.
* Use a feature toggle `edit_contention_text`.
* For now working only on Claim Reviews.

**Comment by leikkisa** [comment]
When a nonrating issue gets contested again, it shows up as a contestable issue in the same modal as rating issues, which I believe will have the ability to edit the description.

How about naming this updated_description?

**Comment by pkarman** [comment]
How about `user_description` to indicate it was manually edited? Or `manual_description`? or `edited_description`?

`updated_description` implies a timeliness or something SQL-esque which confuses me a little.

**Comment by Sjones352** [comment]
I think I like `edited_description` as it indicates description has been edited
