### ISSUE TITLE
Save edited contention text

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10597]
This is Step 3 of editing contention text. In Step 1 we created the UI, in Step 2 the database and server-side code. In this step, we wire them together by enabling the Submit button.

## Definitions

* "original text" here means the generated title text derived from the contested rating issue description.
* "edited text" here means the user-entered title text

## Acceptance criteria

* In the UI, the title will be edited in place (not in a modal).
![Edit title 02](https://user-images.githubusercontent.com/11700545/55116058-53f57f80-50a3-11e9-9541-8db9df364e22.png)
* If the user removes all the text from the textarea box, the HTML field placeholder text should be the original text, to indicate to the user that it will default to that value.
* The "Cancel" button will close the edit component, without applying any changes to the title.
* The "Submit" button will apply changes on the client side only. Any changes should generate the light blue "you have unsaved changes" banner alert (*note* this is not currently in the mocks) and activate the page's "Save" button.
* Submit button will be grayed out until the user makes a selection, either delete or edit text.

## Mocks

See https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1126

## Technical notes

* Use a feature toggle `edit_contention_text`.
* For now working only on Claim Reviews.

**Comment by leikkisa** [comment]
Validated in UAT, this screenshot is after I saved the description to end with a !
![Screen Shot 2019-06-03 at 1.04.50 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/438920e9-89af-46dc-a9bb-5487f083f6aa)
