### ISSUE TITLE
Add Design Standards to Caseflow

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#106]
Lately I've been getting annoyed that we haven't been using a well thought out design system for Caseflow and have been hacking quick style fixes. Some of the things that have been bugging me in particular:

- Our content widths varies across the app
- We use HRs everywhere to delineate content rather than whitespace.
- There's a general lack of information hierarchy 
- We aren't using the USA Web Design Standards
- The site's visual style is very "spartan" as Jed put it.

Here are some considerations/highlights for this redesign: 

- All page content is much narrower. We don't require a lot of interaction on this pages so there's less of a need to take up the full width.
- The header section (Name, Appeal Type, Folder type, Representative, Appeal ID) is consistent across all pages so that the employee can easily reference it. We must be careful about choosing what information we include here in the future and could consider hiding additional case information behind a click.
- Actions to move forward are on the bottom right actions to move backward or stop are on the bottom left. Creates a better sense of space in the app.
- Aside from the header, content sitting on a white background requires action. Content on the grey background requires review. 
- All fonts are Source Sans Pro. To differentiate supporting labels from their labeled content I use all caps and a lighter grey. 
- Every page has a strong call to action: "Find missing documents", "Complete Electronic 8", etc
- I try to include a brief description of the page in the navbar next to the title. Still not sure if this works.

There's still work to be done.

- [x] Need to verify that the colors we use are 508 compliant - especially stuff not on a white BG.
- [x] Check whether the lighter grey (which is not in the design standards) is a no-no
- [ ] Get feedback on whether all caps are a no-no (I consider this to be a stylistic choice, not one of usability)
- [x] Add feedback button(s) (left align footer and add button on the right)
- [x] Add banner indicating project is in pilot
- [ ] Add a warning dialogue that pops up when user clicks "this case cannot be certified" asking if the user attempted to find the case in VBMS as an extra deterrent 
- [ ] Get feedback about instructions on how to find a missing document in VBMS
- [ ] Figure out if more data needs to be included in the header and if so add it
- [ ] Add a help link/button in the navbar and create help content pages.

- [ ] Get general feedback from other designers.
- [ ] In situations where a user sees the error page, show a green confirmation dialogue on the questions page after page refresh.

![01_errorpage](https://cloud.githubusercontent.com/assets/6335546/10885887/98bfaa92-814d-11e5-9e59-0ce7416e468e.png)
![02_questionspage](https://cloud.githubusercontent.com/assets/6335546/10885890/98c203be-814d-11e5-9a13-1c9eaf1c1cd1.png)
![03_previewform8](https://cloud.githubusercontent.com/assets/6335546/10885889/98c185d8-814d-11e5-9a73-8e7d4932f9b9.png)
![04_congratulations](https://cloud.githubusercontent.com/assets/6335546/10886075/68fc462a-814e-11e5-84dc-f413fa892764.png)

**Comment by alex** [comment]
Why does the question page use a white background, but none of the other pages do?

**Comment by mollieru** [comment]
This looks awesome!  I have zero context on the product, so please take this feedback with a grain of salt; I've tried only to respond to things you called out above:

1. It's not obvious that white background = required action, gray background = review. This could be easily solved w training, but if you need people to know this on their own, you may need some other indicator. 

2. In fact, you do need some other indicator. 508 stipulates that we must always have at least one indicator beyond color for anything that needs differentiation.  In other words, if this visual distinction is important to completion of the tasks, in addition to the gray and white backgrounds, you'll need a symbol, word, pattern, stroke or some other visual indicator to let the user know that different action is needed. 

3. The name dropdown on the top right and the Appeal ID button both feel very prominent to me. W/o knowing anything about the flow, seems like the user should be more drawn to action in the main area of the page, right? 

4. I think you're OK on color contrast -- just be careful w that blue (#0071bc) text on darker shades of gray. You may have better luck going one shade darker in the palette (#205493). _I might be reading your colors wrong, in which case, kindly disregard me._ 

5. Seems like, for layout consistency, you might want to think about pulling the text _*Complete Electronic Form 8"_ and the subsequent guiding copy out of the white box and placing all instructions on gray background. Provides consistency in the way you're displaying information page-to-page (unless I'm misunderstanding what should be clicked on).

**Comment by webinista** [comment]
> Get feedback on whether all caps are a no-no (I consider this to be a stylistic choice, not one of usability)

I vote against doing this in the HTML, but instead using the CSS `text-transform` property.

**Comment by plusjeff** [comment]
+1 on doing it in CSS

**Comment by KHarshawat** [comment]
Oh yea, definitely agree doing it in CSS. Just wondering if there the folks who worked on the design standards felt it was a bad choice.

**Comment by KHarshawat** [comment]
Updating with the latest revs given feedback from other folks:

![01_errorpage](https://cloud.githubusercontent.com/assets/6335546/11064677/afee573c-878c-11e5-863f-65a00ef3cf87.png)
![02_questionpage](https://cloud.githubusercontent.com/assets/6335546/11064676/afebff14-878c-11e5-9dfc-04a49ea2b52e.png)
![03_preview](https://cloud.githubusercontent.com/assets/6335546/11064678/afee9de6-878c-11e5-8c53-7c3bcf9c3798.png)
![04_congrats](https://cloud.githubusercontent.com/assets/6335546/11064679/aff19064-878c-11e5-95bd-a41d55162a22.png)

**Comment by alex** [comment]
Is this completed, besides the fonts issue?

**Comment by webinista** [comment]
It's probably safe to close this issue (and I've done that). Everything here is also tracked by other issues.
