### ISSUE TITLE
Create module for creating root tasks for appeals

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10601]
We currently create `RootTask`s using [a series of class methods](https://github.com/department-of-veterans-affairs/caseflow/blob/254b25166796ebd96cccf586ff1bc88b6a6ee470/app/models/tasks/root_task.rb#L44). In order to reduce the size of that file and more cleanly separate concerns, we should move this set of functions into its own module for creating `RootTask`s from an appeal.

## Acceptance criteria
* [ ] Use new `RootTaskForAppealFactory` (or similar) module for creating `RootTask`s.

**Comment by lomky** [comment]
Remove the reek config ignoring this issue as a part of this ticket.

See #10587

**Comment by lowellrex** [comment]
SMALL.
