### ISSUE TITLE
Prevent MailRoutingErrors from triggering Sentry alerts

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10615]
Longer term fix is #10614, but in the short-term we can prevent `MailRoutingError`s like [this one](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4827/) by catching them in the [`TasksController`](https://github.com/department-of-veterans-affairs/caseflow/blob/8f168920a70b82899c28b4e99e2551774c1c0c64/app/controllers/tasks_controller.rb#L59) (or [`ApplicationController`](https://github.com/department-of-veterans-affairs/caseflow/blob/8f168920a70b82899c28b4e99e2551774c1c0c64/app/controllers/application_controller.rb#L12)) and returning the serialized error without sending it to Sentry.

## Acceptance criteria
* [ ] Prevent `MailRoutingError`s from triggering Sentry alerts

**Comment by lowellrex** [comment]
SMALL.

**Comment by hschallhorn** [comment]
This as well https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6389/
