### ISSUE TITLE
Task model is very coupled to EstablishClaim

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1062]
Right now, a lot of logc inside of `Task` and `TasksController` is very coupled to `EstablishClaim`. This makes sense, because it is the only current task, but it's confusing if you expect `Task` to be more generic.

**Comment by shanear** [comment]
Planned changes:

- Move `Task.hash_with_
- Remove TasksController and move everything their into `EstablishClaimsController`. This might be controversial. But the line is too muddy between them, and I think it's best to drop false pretenses, so we can abstract logic from `EstablishClaimsController` into a real `TasksController` when the second type of task comes up

For example, this method is in TasksController?!
```
  def logo_name
    "Dispatch"
  end
```

Thoughts? @joofsh

**Comment by joofsh** [comment]
Sounds good to me
