### ISSUE TITLE
TypeError thrown when validation for AssignWidget fails on submit

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#10632]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4470/events/316497/).

### Problem
`QueueFlowModal` expects to receive a [`submit()` function that returns a promise](https://github.com/department-of-veterans-affairs/caseflow/blob/8f168920a70b82899c28b4e99e2551774c1c0c64/client/app/queue/components/QueueFlowModal.jsx#L44) from the component it wraps. In the case of `AssignWidget`, the submit function it provides does validation and returns nothing when that validation fails, causing `QueueFlowModal` to throw a TypeError.

### Solution
The submit function in `AssignWidget` should be reworked to only be called once validation passed, rather than performing the validation itself. Validation for components that use `QueueFlowModal` should be broken out into another function and passed to the `QueueFlowModal` as [`validateForm`](https://github.com/department-of-veterans-affairs/caseflow/blob/8f168920a70b82899c28b4e99e2551774c1c0c64/client/app/queue/components/QueueFlowModal.jsx#L98). See [`PostponeHearingModal`](https://github.com/department-of-veterans-affairs/caseflow/blob/8f168920a70b82899c28b4e99e2551774c1c0c64/client/app/queue/components/PostponeHearingModal.jsx#L73) for an example of `validateForm()` with custom error messages. Here are the [three](https://github.com/department-of-veterans-affairs/caseflow/blob/1ec132c7beb861f39a2b9bfa5c90481d41c760d1/client/app/queue/components/AssignWidget.jsx#L37) [different](https://github.com/department-of-veterans-affairs/caseflow/blob/1ec132c7beb861f39a2b9bfa5c90481d41c760d1/client/app/queue/components/AssignWidget.jsx#L45) [validations](https://github.com/department-of-veterans-affairs/caseflow/blob/1ec132c7beb861f39a2b9bfa5c90481d41c760d1/client/app/queue/components/AssignWidget.jsx#L57) that need to be pulled out of the submit function

**Comment by hschallhorn** [comment]
[Another!](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6460/)

**Comment by hschallhorn** [comment]
Few more sentry alerts in #10777

**Comment by jcq** [comment]
[Another!](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6166/)

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||||
2 | |||||||||
3 | 
5 | 
8 |  
```
