### ISSUE TITLE
Record JS errors in Sentry

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1063]
Sometimes Javascript errors can break the entire application. Like this bug:

https://github.com/department-of-veterans-affairs/caseflow/issues/1040

Right now, we won't be able to know about any Javascript errors that happen in production. We should be sending them to Sentry.

**Comment by shanear** [comment]
Because of how Sentry is set up in UAT, this must be validated in Prod.

**Comment by kierachell** [comment]
cool
