### ISSUE TITLE
Security alert for node tar

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10645]
https://github.com/department-of-veterans-affairs/caseflow/network/alert/client/yarn.lock/tar/open

**Comment by lomky** [comment]
[Status](https://dsva.slack.com/archives/C2ZAMLK88/p1556906835212400?thread_ts=1556895841.198400&cid=C2ZAMLK88)

**Comment by pkarman** [comment]
@lomky I am seeing this alert has been re-opened. 😢

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/network/alert/client/yarn.lock/tar/open
