### ISSUE TITLE
Discussion: Foxtrot team

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10655]
Since December 2018/January 2019, Foxtrot has split into two sub teams - Queue and Decisions. The Queue and Decisions teams have been together for some sprint rituals and separate for some others. Starting this sprint (5/6 - 5/17), Team Sierra has joined the Decisions team. 

How should we organize first day of sprint meetings moving forward?

## What is sprint kickoff?
Goals:
* Context sharing about what the team is focused on in the upcoming sprint
* Review of tickets from last sprint so we know what's carrying over

## Notes/caveats
* Queue team does estimation. Estimation gives engineers context about tickets, ensures tickets have enough information to be picked up by engineers (e.g. fleshed out AC, mocks, etc.), allows engineers to brainstorm approaches, and optionally, allows engineers to estimate.
* Sierra team did estimation in the form of story pointing during their first day of sprint meeting. Something to consider.

## Proposal 1
* One sprint kick off for Queue
* Separate sprint kickoff for Decisions
* Agenda
  - Review last sprint's tickets (all)
  - Define goals for this sprint (product)
  - Review this sprint's tickets

## Proposal 2 
* Shared sprint kickoffs for Queue and Decisions
* Same agenda

## Proposal 3
* Shared sprint kickoffs for Queue and Decisions
* Different agenda, to be co-created as a team

**Comment by pkarman** [comment]
+1 for proposal 1. I think separate teams should have independent sprint rituals.

**Comment by laurjpeterson** [comment]
After talking with @lowellrex and @aroltsch - it sounds like they're both down with proposal 1. 

And further, here's what's proposed for sprint rituals:
1. separate sprint kick offs
2. separate sprint estimations (lowell's team does them right now, have not discussed anya's team doing them)
3. shared standups
4. shared retros

lowell and anya suggested to experiment with how this feels this sprint.

note: i worry about 2 out of 3 sprint teams sharing some rituals - rather than all 3 teams or all separate rituals - and what it might do to our team culture. we've had issues with siloing in the past, and lack of comms/cohesion among queue and hearings teams, so i don't want this to perpetuate. posting here so we are all aware of this.

**Comment by pkarman** [comment]
@laurjpeterson that's a legit worry. We've kept 3 teams for now in order to get through some remaining feature work. Let's get alignment on 2 out of 3 and we can re-assess when we are also re-assessing team org in a month.

**Comment by laurjpeterson** [comment]
We've moved to separate sprint kickoffs/plannings. We're experimenting with Caseflow-wide standups for one sprint (starting June 3) and will evaluate whether we should separate into all 3 teams, or stay together. Closing!
