### ISSUE TITLE
Remove feature flag for remove decision reviews.

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10658]
Once this is ready and approved by AMO and we know which users are relevant, remove or turn on the remove_decision_reviews feature flag.

dependency: https://github.com/department-of-veterans-affairs/caseflow/issues/10546

AMO gave us the date of June 9th.

Technical notes
Remove feature flag in code, keep tests for "remove decision reviews"
Remove feature flag here:
appeals-deployment/ansible/vars/features-config.yml

**Comment by leikkisa** [comment]
Moving this to backlog since we decided to wait until the feature toggle has been on for a while.

**Comment by pkarman** [comment]
Month is up! let's do it.

**Comment by leikkisa** [comment]
Sandra merged a PR for this last week. Moving to closed.
