### ISSUE TITLE
`Document#file_name` and `Document#filename`: there can only be one

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1065]
`Document` has both `file_name` and `filename` methods which both do different things. This is deeply confusing and we should refactor it

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet (although it sure seems like we should), so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
