### ISSUE TITLE
VBMS Reader Errors

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10665]
Some of the errors being thrown by VBMS:

- VBMSError::DocumentTooBig
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4396/

- VBMSError::Security
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5132/

- VBMSError::FilenumberDoesNotExist
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4748/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4738/
- Unable to parse SOAP 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3954/

- A JSON text must at least contain two octets!
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4891/

- Disconnect
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3896/

- 500
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4769/

- HTTPClient::KeepAliveDisconnected
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4881/

- Connection refused
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4834/

**Comment by pkarman** [comment]
Depending on what more investigation turns up, some of these could be ignored in Sentry so that we don't see slack alerts any more. Not sure if any of these are actionable.

**Comment by aroltsch** [comment]
Re: VBMSError::DocumentTooBig. We need to use VBMS paginated API. @nemodjuric looked into it. Nemo, could you please update us on the status of that api endpoint, where were you left off?

**Comment by nemodjuric** [comment]
I ran into a bug with this service and I let VBMS team know (you should be in that email thread @aroltsch). This is their response:

> We’re still investigating this issue to try to reproduce it in our lower environments.  It’s probable that we have some scenarios with data that we do not have in the lower environments that is different from PROD.  We’ve created a defect to work it but any code changes will likely not go out and be available to you until the next release. 
> 

The new API endpoint has better performance. I ran some benchmark tests (3 x 1,000 sample) and it seems that FindPagedDocumentSeriesReferences performs on average 5% better.  However it's unreliable to be used as default. We can still try to use it in cases when result size exceeds the limit.

**Comment by ferristseng** [comment]
Another FilenumberDoesNotExist error, but it's being reported as just a VBMSError for some reason.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5254/

**Comment by ferristseng** [comment]
Also a 500 DocumentNotFound error:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/5033/events/407227/

**Comment by nemodjuric** [comment]
VBMS still haven't replied. I just sent another text and email. At this point we might consider making it work the way it is, which is going for pages less than 5,000 in size and see if that’s going to help.

**Comment by msj0nes** [comment]
Associated : #10732 , #6680 , [#1132](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1132)

**Comment by pkarman** [comment]
VBMSError::DocumentTooBig solution is deployed. We need to enable it with a feature toggle `:vbms_pagination`. I am going to test that next week.

**Comment by pkarman** [comment]
The rest of these errors are are similar to those in efolder. I am going to close this ticket and open a separate ticket for each error type.
