### ISSUE TITLE
NoMethodError on find_or_create_decision_issue

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10662]
`undefined method "disposition" for nil:NilClass`

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4841/events/322074/

## Notes
- This is probably generated from a background job when connecting request issues and decision issues. Once a day, we check for rating issues with dispositions that have been created so we can close the loop on that decision review. (If it ends with the word "job" it's not usually user visible.)
- The only user impact would be if there is a subsequent decision review on this issue, and when the user tries to intake it, they can't find this "prior VA decision".
- This indicates that there is a disconnect in expectations from Caseflow and another system (VBMS) - this impacts data integrity

**Comment by leikkisa** [comment]
It looks like this stopped happening, the last instance is on May 20.  In the stacktrace, it looks like contention_disposition was nil.  Master today fails the method if contention_disposition is nil.  Closing!
