### ISSUE TITLE
null safe checks in error handling - Reader

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10663]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3016/ ✅ 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4927/ 

I think what's happening in sentry issue 4927 above is the SET_DOC_SCROLL_POSITION is not defined since there is no throttle on the scroll, so redux can't read the type on that action.  this redux action gets called _every single time_  the `PDfFile` component updates, as well as when this method is called:  `PDFJS.renderTextLayer` (that alone can be thousands of times on a larger document) which is a large number of events being sent to redux. introducing some sort of a throttle on this action (`SET_DOC_SCROLL_POSITION`)  call might solve this, so that action would only be called once every 500 milliseconds or once a second.

**let me know if a new ticket needs to be created for this sentry issue 4927**

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3011/ ✅ 
TypeError: Cannot read property 'type' of undefined
```
  updateWindowTitle = () => {
    document.title = `${this.selectedDoc().type} | Document Viewer | Caseflow Reader`;
  }
```

**Comment by pkarman** [comment]
> let me know if a new ticket needs to be created for this sentry issue 4927

@youngfreezy if you think it will require more than a trivial fix, I would say "yes"
