### ISSUE TITLE
Add date format where applicable

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1066]
Instead of using `strftime` we should be using `to_formatted_s` with a predefinded date format to maintain consistency.

See:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/views/tasks/worker_index.html.erb#L43

**Comment by kierachell** [comment]
**PASSED**
validated proper date formats in VACOLS and reports:
![screenshot_2017-03-14_09-06-52](https://cloud.githubusercontent.com/assets/18075411/23901925/a229a62a-0895-11e7-9d54-857f97891063.png)
