### ISSUE TITLE
Reader errors related to mark-as-read endpoint at capacity

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10664]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3020/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2948/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4834/

## Notes
- We think this is a javascript problem and that it's potentially user visible

**Comment by tomas-nava** [comment]
I opened a separate issue for _3020_, #10813,  as I believe it's not a mark-as-read endpoint issue.
