### ISSUE TITLE
JSON::ParserError 784: unexpected token at '<html>  <head><title>502 Bad Gateway</title></head>  <body bgcolor="white">  <center><h1>502 Bad Gateway</h1></center>  <hr><center>nginx/1.12.2</center>  </body>  </html>  '

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10678]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4893/

new error popping up today. not sure if related to documents endpoint changes.

cc: @lowellrex 

error being thrown is from `generate_efolder_request` at line 21

**Comment by lowellrex** [comment]
This only happened twice and both events were within 30 seconds of one another so I think we can delay looking into this until it comes back.

**Comment by alisan16** [comment]
This error hasn't been seen since it was reported on May 7, 2019 1:48:05 PM EDT. Closing this out.
