### ISSUE TITLE
Add reporting for withdrawn and removed claims

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10677]
For a claim-level withdrawal status, if there was at least one issue withdrawn, and every other issue was withdrawn or removed, we'd consider it withdrawn.  If every issue was removed, we'd consider the claim removed.

If there is at least one issue that was not withdrawn or removed, then it would be neither.  This would happen if an issue is not yet closed, or is closed for any of these other reasons:
 - decided
 - end product canceled (unless it was canceled by us due to withdrawals or removals)
 - dismissed death
 - dismissed matter of law
 - stayed
 - ineligible

Questions:
  - Confirm the above method of calculation with AMO
  - Clarify if this should be at the EP level for decision reviews with EPs, or at the decision review level, or both
  - How do we want the data to be broken up? Do we want a query to list all of the withdrawn claims? Or count by timeframe?  Do we just want to report withdrawn claims, or also remove withdrawn claims from other reported numbers?

Steps
1. Develop a query to calculate withdrawn claims
2. Determine if the above query is sufficient, or if reporting would need a database field for the claim-level or decision-review level status
3. Create a report for these in Looker
4. Let Thomas Boyda (in #appeals-metrics) know, he works on the Tableau reporting

**Comment by leikkisa** [comment]
Andrew Lomax, Nemo or Sunil can help with Looker.

**Comment by leikkisa** [comment]
Contact for AMO Reporting questions: Christopher.Watts@va.gov

**Comment by msj0nes** [comment]
Ticket Closure

AMO reports are provided via third party PAI. Closing ticket at this time. If there are inquiries regarding the data points mentioned this ticket can be reopened.
