### ISSUE TITLE
better regular expression handling - reader

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10698]
invalid regEx being passed here:

`./app/reader/CommentsTable.jsx at line 27:20`

```const query = new RegExp(searchQuery, 'i');```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2032/

**Comment by tomas-nava** [comment]
More specifically, if you type a regex special character like `?`, `*`, `(` into the "Type to search..." field in a claims folder **_while showing all comments_** the page will go blank and throw `Uncaught SyntaxError: Invalid regular expression`

**Comment by monfresh** [comment]
I think this might be related:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5675/

**Comment by hschallhorn** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5025/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5115/
[as well as a slew of others](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/?query=is%3Aunresolved+new+RegExp)
