### ISSUE TITLE
Add ability to pre-fill congresspeople to Congressional Inquiry tasks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10696]
When litigation support or mail team users are adding Congressional Inquiry mail tasks, they need to quickly add the Congresspeople and their address, so they can track who needs to get a copies of decisions (and any other information).

Additional context about Congressional addresses:
- During the kickoff meeting with Lit Support leadership on 04/24/2019, they indicated they wanted to have auto-completion of congressional representatives addresses.

## Mocks (need to be updated)
<img width="254" alt="Screen Shot 2019-05-08 at 12 59 50 PM" src="https://user-images.githubusercontent.com/27704093/57393559-57dfeb80-7191-11e9-8669-11d19e67a91a.png">

## AC
- [ ] When creating a mail task for congressional inquiries, mail team users can search for a congressperson
- [ ] If the congressperson is found in the initial search, populate fields created in #14759 with information from the API

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||
3 | |||||||
5 | |||
8 | 
```

#### Why 2?
* Examples of other APIs that use this information. Gem may already exist

#### Why 3?
* we have several Services like this, but not sure we've done one on Echo?

#### Why 5?
* 

#### Why 8?
*

#### Why 13?
* Snark

 - [ ] Add ability to add congresspeople to a Congressional Inquiry tasks
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

#### Why 2?
* Where will we store this information? Should we store it or rely on calling the API?
* Implement as an object (congressionalinquiry?) associated with a task?
* Could be a field on the task, but would be very sparse

 - [ ] integrate automatically pulling this into our code (fall back to manual input if congressperson not found)
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

#### Why 2?
* tying together previous work
* If ticket 1 is well implemented, only adding a request to the back end that will search and return prefilled values

**Comment by mbaenatan** [comment]
Design questions to think through based on engineering estimation for this ticket and #14759:

- [ ] How should receipt date and source appear to the users (what options should they have? may need to talk to mail or lit support about options)
- [ ] How should this “search for congressperson” appear when creating the task?
- [ ] How should “we were unable to find this congressperson, please enter information manually” appear to the user? Both error and fields for manually entering the information
- [ ] How should prefilled information look to the user when we are able to find the congressperson’s information
- [ ] Are users allowed to update Congressperson's info that is returned from the API?

**Comment by mbaenatan** [comment]
Included in design bonus set for sprint August 10-21. After investigating further decided to keep in backlog as low priority since work has not been prioritized by the Board yet
