### ISSUE TITLE
Add document receipt date and source to Congressional Inquiry tasks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10697]
Lit support employees need to see the source of request (mail, fax, phone, email) because different team members work tasks from the different sources. 

They also need to see the receipt date. 

## Mocks (to be updated)
<img width="254" alt="Screen Shot 2019-05-08 at 12 59 50 PM" src="https://user-images.githubusercontent.com/27704093/57393508-3c74e080-7191-11e9-8fc5-871cc4255afc.png">

**Comment by hschallhorn** [comment]
Replaced with #14759
