### ISSUE TITLE
ActiveRecord::StatementInvalid

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10708]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4940/

<img width="1299" alt="Screen Shot 2019-05-09 at 1 26 48 PM" src="https://user-images.githubusercontent.com/46791771/57473590-241ec780-725e-11e9-9ec9-6fc6855bc1c3.png">

**Comment by pkarman** [comment]
this was due to the VACOLS bug. fixed and deployed in #10706
