### ISSUE TITLE
Backfill data for nonrating request issues missing a decision date

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10713]
The following request issues are missing a decision_date. This is due to the dates entered being invalid dates.

```RequestIssue.where.not(nonrating_issue_category: nil).where(decision_date: nil)```
IDs: [22767, 21616, 27696, 43219, 21619]
Descriptions: [" post traumatic  stress disorder", "foot problems", "reduction of VA disability Compensation based on 39 drill days in USAR for FY 2017", "Service condition left/right knee pain", "foot problems"]

To backfill these - find the decision review that the request issue is on.  Then find the AMA form that was submitted for this decision review either in VBMS or through eFolder.  Find the specific request issue on the form, and backfill the data with that issue's decision date.

Example code to update with the date from the Supplemental Claim form.
```RequestIssue.find(22767).update!(decision_date: Date.new(2019,5,26))```

Related: https://github.com/department-of-veterans-affairs/caseflow/issues/10714

**Comment by Sjones352** [comment]
@leikkisa I have back filled 4 of these issues. IDs: 21616 and 21619 are the same veteran. ID 21616 was  `created_at: "2019-04-08 13:19:11"` and 21619 was `created_at: "2019-04-08 13:19:57"`.  This looks like a user mistake as they were created a few seconds apart.  I also found 2 supplemental claims on this this veteran's file. One was had a decision_date of "2019-03-15" and the other form was a blank form.

**Comment by leikkisa** [comment]
@Sjones352 Thank you Sandra! It looks great. You're right, one of those request issues got removed.  I just checked and they're all good now!  Closing this issue.
