### ISSUE TITLE
Caseflow::Error::VaDotGovMultipleAddressError

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10723]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4974/events/331710/

**Comment by ferristseng** [comment]
For context, we added this error in #10668 for #10387. We were getting a bad result when geocoding an address, and not handling the error message returned by the API (the response was still a `200`).

**Comment by pkarman** [comment]
@ferristseng thanks -- is this a case where we are just throwing the exception and do not intend to seek further solution? if so I will ignore it in sentry so we don't get pinged about it.
