### ISSUE TITLE
Retry VBMSError::FilenumberDoesNotExist with claim number?

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10732]
A common VBMS error we see in Sentry is `VBMSError::FilenumberDoesNotExist`. I see that in one case (in [fetch_documents_for](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/vbms_service.rb#L43)), we are rescuing the error and trying an alternative claim number instead of the SSN. I’m wondering if we should apply the same logic to other methods, like `upload_document_to_vbms`.

From the description of the [PR that added the rescue](https://github.com/department-of-veterans-affairs/caseflow/pull/7755), it sounds like we should be fetching the correct number from BGS every time we send over a potentially incorrect file number:
```
In some situations the file number in VACOLS (the bfcorlid column) is incorrect. 
It will be the SSN where it should be a claim number. When hitting the VBMS 
endpoint to get a list of files, we use the wrong number, and get an error with 
text: "File Number does not exist within the system." To solve this problem we 
can make a call to BGS to find the correct file number and then call VBMS with 
that instead.
```

cc @sharonwarner  and @sunil who participated in the original [issue](https://github.com/department-of-veterans-affairs/caseflow/issues/4567)

**Comment by lomky** [comment]
This is happening a lot over the past month.

**Comment by hschallhorn** [comment]
[Also this dude](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5059/
)

**Comment by pkarman** [comment]
some stats:

```
irb(main):011:0> Veteran.where("file_number = ssn").count
[2019-10-30 11:58:55 -0400]    (510.4ms)  SELECT COUNT(*) FROM "veterans" WHERE (file_number = ssn)
=> 141828
irb(main):012:0> Veteran.where("file_number != ssn").count
[2019-10-30 11:59:01 -0400]    (83.9ms)  SELECT COUNT(*) FROM "veterans" WHERE (file_number != ssn)
=> 34362
irb(main):015:0> Veteran.count
[2019-10-30 11:59:32 -0400]    (72.0ms)  SELECT COUNT(*) FROM "veterans"
=> 485479
irb(main):017:0> Veteran.where("char_length(file_number) = 9").count
[2019-10-30 12:00:43 -0400]    (1089.7ms)  SELECT COUNT(*) FROM "veterans" WHERE (char_length(file_number) = 9)
=> 380899
irb(main):018:0> Veteran.where("char_length(file_number) = 8").count
[2019-10-30 12:00:52 -0400]    (91.1ms)  SELECT COUNT(*) FROM "veterans" WHERE (char_length(file_number) = 8)
=> 104581
```

**Comment by yoomlam** [comment]
FYI: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/7927

**Comment by pkarman** [comment]
We think we've fixed this. Closing until it recurs.
