### ISSUE TITLE
BGS::ShareError - The Tuxedo service is down in fetch_veteran_info

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10739]
A common error in Sentry happens when BGS can't connect to the Benefits Delivery Network. It looks like the End Product Establishment code is [ignoring these errors](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/exceptions/bgs_sync_error.rb), but other parts of the app are not. We should probably handle errors consistently throughout the app, no?

Example: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4545/events/331759/

**Comment by pkarman** [comment]
yes all the Intake-related code ignores transient errors like these. We should ignore them everywhere.

For VBMS we were able to wrap all the errors in a single place https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/vbms_service.rb#L213 but for BGS I think it's been a lot more piecemeal.

**Comment by alisan16** [comment]
This error hasn't been seen for 8 months. Closing out this issue.

**Comment by yoomlam** [comment]
Recurred Sunday during `ETLBuilderJob`: https://dsva.slack.com/archives/CPEMQPVKR/p1604212017033900
