### ISSUE TITLE
Response timeout of 60000ms exceeded (superagent/lib/request-base in u.r._timeoutError)

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10741]
This is one of the most frequent errors in Sentry. Example:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2989/

I think it timed out while fetching document counts.

**Comment by pkarman** [comment]
We have some open tickets to fix this issue:

* https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/1093
* #10717 
* #10716

**Comment by alisan16** [comment]
This error hasn't been seen for 3 months. Closing out this issue.
