### ISSUE TITLE
Savon::SOAPFault Profile Subsystem failed. Persistence exception occurred

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10740]
Example: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4627/

I'm not sure what this means. This happened while fetching veteran info. The full message is:
```
Savon::SOAPFault: (S:Server) ID: 3F10EE77-364F-4477-BC90-26ADBE38CC8A:
Profile Subsystem failed. Persistence exception occurred
```

**Comment by alisan16** [comment]
This error hasn't been seen for 9 months. Closing out this issue.
