### ISSUE TITLE
Handle 503 errors from VBMS more gracefully

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10749]
Here is an example of an error that should probably be retried, or at least excluded from Sentry.  An error with the same message is currently being excluded via our `BGSSyncError` class.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5005/

```
VBMSError: status_code=503, body=upstream connect error or disconnect/reset before 
headers, request=#<VBMS::Requests::FindDocumentVersionReference:0x00007f5e8058cbf0 
@file_number="redacted">
```

**Comment by pkarman** [comment]
bce98ec988499a6e088660f88ad9883d203753c5 will more clearly label these as transient so we can ignore in Sentry.

**Comment by monfresh** [comment]
Sweet. Should we close this?

**Comment by pkarman** [comment]
yes, I think the ticket on the connect_vbms client lib itself expresses the better fix.
