### ISSUE TITLE
Send source contention ID for contentions on DTA claims

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10756]
Required https://github.com/department-of-veterans-affairs/connect_vbms/issues/219

When we create contentions as a result of a DTA error on an HLR, we should send the original contention_ids (from the request issues that got a DTA error) when we create the contentions.

If there are multiple prior contentions resulting in a single contention, send an array of the prior contention IDs.

**Comment by leikkisa** [comment]
This is planned to be available in prod on 8/10.
