### ISSUE TITLE
BusinessLine organizations should redirect from /organizations/:name/tasks

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10752]
The `BusinessLine` Organization type should not have access to any /organizations/:name/tasks. They are designed for `/decision_reviews` only.

If a request comes in for a `/organizations/:name/tasks` and the org is a BusinessLine type, redirect to the `/decision_reviews/:name` URL instead.

**Comment by leikkisa** [comment]
Is this true for appeals?

**Comment by pkarman** [comment]
Do you mean if the BusinessLine org has tasks that relate to Appeals?

I don't think it matters. In this example, the Education LOB has only tasks of type DecisionReviewTask. Would a BusinessLine org ever have tasks that were not of that type? They should not be assigned any afaik.
