### ISSUE TITLE
blank screen when clicking veterans waiting tabs in schedule veterans when an RO has no available hearing days

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10754]
[Sentry error](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5004/events/332926/)

A user loads the _Schedule veterans_ page (`/hearings/schedule/assign`) for an RO that has no available hearing days (`RO13` in this case) and clicks on the _Legacy Veterans Waiting_ or _AMA Veterans Waiting_ tabs. The result is a blank screen and a `TypeError` in the console: "Cannot read property 'scheduledFor' of undefined".

related Sentry errors: [one](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4998/events/331908/), [two](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4998/events/331922/)

**Comment by lomaxap** [comment]
### AC
- [ ] Add a notification on `/hearings/assign/` "There are no upcoming hearing days with open slots for this regional office. Please add a new hearing day"

**Comment by rubaiyat22** [comment]
The PR: https://github.com/department-of-veterans-affairs/caseflow/pull/11057 resolved this issue.
