### ISSUE TITLE
Caseflow::Error::ActionForbiddenError when attempting to update a task's status

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10751]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3678/events/332947/

There are several instances of this error in Sentry, and the first few that I've seen all seem to happen when a user is attempting to update a task's status.

I'm not sure if some of these might be legitimate errors because the user indeed does not have access, or if it's a bug where the app is allowing a user to update a task that they don't have access to.

cc @lowell, @tomas-nava

**Comment by lomky** [comment]
Same error through another call path

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5272/

**Comment by alisan16** [comment]
This error hasn't been seen in 8 - 10 months (depending on call path). Closing out.
