### ISSUE TITLE
Add withdrawn dispositions to request issues in Case Details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10760]
Sometimes, request issues have dispositions. Veterans can opt to withdraw a request issue, or a request issue could be stayed. Judges and other VA employees need to see that request issues already have dispositions, and therefore don't need a decision. 

There are three places where we want to show request issue dispositions, if they exist:
- Case details
- Attorney check out flow
- Judge check out flow

Epic: #8936 
Related: Create AMA issues component - #8591 

## AC

- If a request issue has a closed status  of withdrawn, show that disposition in case details
- If a request issue has a closed status of withdrawn, show that disposition in check out flows
- Require decision issues on withdrawn request issues in check out flow.
- Treat withdrawn decision issues the same way that we treat denied decision issues, but with the disposition of withdrawn. This allows Veterans to appeal their withdrawal (e.g. if the Board misinterpreted that the Veteran wanted to withdraw). 

## Tech notes
- You might hear people say "request issue dispositions". That's referring to request issue closed statuses.
- Contestable issues are our own decision issues + ratings from BGS. If we don't create a new rating with the denial in BGS as a result of the withdrawal, we'd need to create a Caseflow decision issue with a disposition. That decision issue would be contestable, but it wouldn't be connected to a BGS rating. 

### Provocation design for case details view of **single-withdrawn issue**
<img width="812" alt="Screen Shot 2019-05-15 at 11 25 49 AM" src="https://user-images.githubusercontent.com/31224257/57787960-4acc7a80-7704-11e9-980d-3a178e1867b5.png">

**Comment by laurjpeterson** [comment]
note: @laurjpeterson to confirm requirements

**Comment by aroltsch** [comment]
Updated AC:

Request issue closed status:
Tech notes: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issue.rb#L40

Sometimes, request issues have dispositions aka closed_status. Veterans can opt to withdraw a request issue. Judges and other VA employees need to see that request issues already have dispositions, and therefore don't need a decision.

There are three places where we want to show request issue dispositions, if they exist:

Case details
Attorney check out flow
Judge check out flow


AC
If a request issue has a closed status of withdrawn, show that disposition in case details
If a request issue has a closed status of withdrawn, show that disposition in check out flows
Require decision issues on withdrawn request issues in check out flow.

**Comment by monfresh** [comment]
This will require us to modify the appeal serializer to return withdrawn request issues, which it currently excludes via the `active_or_decided` scope: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/serializers/work_queue/appeal_serializer.rb#L11

Would the correct scope be `active or decided or withdrawn`?

**Comment by aroltsch** [comment]
Yes, we should either modify the existing scope if it is not being used anywhere else or create a new one.

**Comment by laurjpeterson** [comment]
AC looks good to me. I updated the main issue above. 

> If request issue is withdrawn, should we only allow a user to add withdrawn disposition to a decision issue when going though a checkout?
- How about we auto-populate it, but not restrict users from choosing others? The reason I'm thinking not to restrict it, is if there is any edge case that requires the decision issue to have something else, users wouldn't have to contact Caseflow to fix it
