### ISSUE TITLE
Reflect withdrawn appeals in Case Timeline (backend)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10762]
When an entire appeal has been withdrawn, users need to be able to see that event reflected in Case Timeline, so they don't add actions to an appeal that are not needed. 

## AC
- If all issues on an appeal are withdrawn, use the maximum withdraw date. Show the withdrawn icon and event in Case Timeline per mocks below
- So, if multiple issues are withdrawn on different dates over time, use the date when all issues were withdrawn, the maximum withdraw date

## Designs
<img width="691" alt="Screen Shot 2019-05-14 at 3 47 00 PM" src="https://user-images.githubusercontent.com/31224257/57727537-c7f1e400-765f-11e9-9819-007564f54acb.png">
_something’s in place for now - part of larger case timeline overhaul work (will provide all context to engineer who will take this on)_

**Comment by aroltsch** [comment]
I think this will be done when this PR gets merged: https://github.com/department-of-veterans-affairs/caseflow/pull/11180
