### ISSUE TITLE
Spike: Allow withdrawn appeals to be distributed to judges as part of automatic case distribution

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10764]
When Veterans have withdrawn their appeal, per Board policy, judges still need to write a decision for that case, so the Veteran get a decision on their appeal. 

Currently, when all issues have been withdrawn and then the entire appeal has been withdrawn, Caseflow cancels all tasks associated with the appeal. 

We need to update this logic such that these withdrawn appeals can be distributed via auto-case distribution to judges. 

## AC
- Technical exploration, suggestion of approach

**Comment by monfresh** [comment]
@laurjpeterson Based on the current algorithm as defined in the [wiki](https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Case-Distribution), do you have any thoughts as to the correct proportion of withdrawn appeals? Would it be considered a priority or nonpriority appeal?

**Comment by monfresh** [comment]
I think that was the wrong question. Here's a better one: if an AOD appeal that would have previously been prioritized is now withdrawn, is it still considered a priority appeal, or should it now become nonpriority? Do all withdrawn appeals automatically become considered nonpriority?

**Comment by laurjpeterson** [comment]
> if an AOD appeal that would have previously been prioritized is now withdrawn, is it still considered a priority appeal
- I think so. @nicholasholtz to confirm

**Comment by nicholasholtz** [comment]
I'm a little confused - who is marking this as withdrawn? Historically, at least in legacy, the case is still active and is assigned to the attorney, and the attorney marks it as withdrawn.

**Comment by laurjpeterson** [comment]
@nicholasholtz - some notes from my last convo's with rachel and jennifer for some context:
https://github.com/department-of-veterans-affairs/caseflow/issues/8936#issuecomment-490526695

they think that the case review / BVA intake team could mark the appeal as withdrawn as soon as the withdrawals come in. 

this is different than today, when withdrawal of appeals mail tasks are assigned to VLJ support

**Comment by nicholasholtz** [comment]
This might be neither here nor there, but this seems like something that, if they are still using the IDT, the IDT could essentially draft on its own and dispatch without having to go to an attorney. That would impact how attorneys got credit, but it would be faster and not waste time on something that is purely mechanical.

**Comment by laurjpeterson** [comment]
i don't think the IDT can automatically add a judge signature though

**Comment by monfresh** [comment]
The current logic for determining whether an appeal is ready for distribution is as follows:
- it has at least one Distribution Task with status `assigned`
AND
- it doesn't have any blocking Mail Tasks where the status is neither `completed` nor `cancelled`.

Another way of saying that last condition is:
- it doesn't have any blocking Mail Tasks where the status is `assigned`, `in_progress`, or `on_hold`.

The current types of blocking Mail Tasks are:
```
"CongressionalInterestMailTask",
 "ExtensionRequestMailTask",
 "FoiaRequestMailTask",
 "HearingRelatedMailTask",
 "PowerOfAttorneyRelatedMailTask",
 "PrivacyActRequestMailTask",
 "PrivacyComplaintMailTask"
```

If the priority of a withdrawn appeal doesn't change, then the solution might be as simple as changing the logic such that withdrawn appeals are also considered ready for distribution. However, that makes certain assumptions that I'm not sure are true. Can someone answer the following questions please?

- Can the Root Task of an appeal get `cancelled` for a reason other than withdrawal? 
- Is there a way to look up withdrawn appeals besides looking at the status of the Root Task?

**Comment by laurjpeterson** [comment]
> Can the Root Task of an appeal get cancelled for a reason other than withdrawal?
- Yes. If a user "removes" the appeal (right now, they remove all issues and choose to remove the entire appeal), all tasks will be canceled

> Is there a way to look up withdrawn appeals besides looking at the status of the Root Task?
- If all request issues on an appeal have the disposition of withdrawn

Adding @leikkisa because she worked on the withdrawn issue disposition stuff

**Comment by leikkisa** [comment]
@laurjpeterson You have the correct answers above. It sounds like we might not want to cancel all tasks as part of withdrawing.  We didn't write the code for appeal level withdrawal status, so we might want to double check with @amprokop.

We can add a method to indicate whether an appeal was withdrawn based on whether the request issues were withdrawn, but there are some cases we'll want to talk about when not all request issues are withdrawn, but there's no more open actions (like if there's an ineligible issue that isn't withdrawn).

**Comment by laurjpeterson** [comment]
Good point, @leikkisa. We'll need to modify what we do when all issues are withdrawn. Started a ticket, here: https://github.com/department-of-veterans-affairs/caseflow/issues/10973. 

I think it'd be the same for appeals with only ineligible issues and the rest being withdrawn. I don't think BVA needs to act on the ineligible issue, and we shouldn't count it being on appeal. 

@monfresh - FYI I also added AC to that ticket saying if an appeal is withdrawn, to add a `DistributionTask` - as a start to the solution you referenced above, changing the logic such that withdrawn appeals are also considered ready for distribution. 

The Board does want withdrawn appeals to be distributed right when they're ready, and I think this can be out of docket order (since the appeal is withdrawn and it's quick). I'll have to double confirm this.
