### ISSUE TITLE
Styleguide Component | Caseflow tables

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1076]
As a designer and developer, I want to able to have tables in a living style guide with react components so I can consistently add tables across apps and easily change them when necessary. 

# Acceptance Criteria
1. Verify that the title Tables appears in the living style guide 
1. Verify that there is a horizontal line that creates a separate section above the table 
1. Verify that the Table copy appears underneath the Table title
1. Verify that the all mocks under Table appears under the Table copy 
1. Verify that there is a "Queue" section within the Tables category
1. Verify that the "Queue" copy below appears underneath the "Queue" title 
1. Verify that the "Queue" mock up appears below the "Queue" copy
1. Verify that the "Ui Name" appears on the left nav and clicking it takes you to the apropriate element 

# Mockups 
**_Style guide - {Tables}_**

![image](https://cloud.githubusercontent.com/assets/13420618/24208622/69051422-0efa-11e7-9cb5-6c5432c51ba2.png)

**Queue**

![image](https://cloud.githubusercontent.com/assets/13420618/24208631/73cb5eac-0efa-11e7-8085-5d75f7ddc620.png)

# Copy: 

"Tables

"We use tables to display information across Caseflow. Most frequently they are used in users’  Queues but we sometimes use them to help users accomplish a specific task. For aesthetic purposes, tables in Caseflow are borderless. 

Table headings should be bold and with a white background.

Often tables will contain an primary action a user can take on the table item. These actions should always be placed in the right most column of the table and should be right aligned with the edge of the table."

"Queues

Tables are most frequently used in users’  Queues or a list of work items for a user to take action on. Queues are shown in the standard App Canvas as tables. A distinct feature of queue tables is the right-aligned actionable link, such as “Assign »,” located on the far right column."

**Comment by shanear** [comment]
These tables all use the same component (there's just different stuff in the cells), so I'm just going to add one. How's that sound?

**Comment by gnakm** [comment]
I think we should have queues #1092 as a subsection under tables. Queues are build the same way but the instructions and purposes are a bit more unique. Could build two tables?

Tables: 
![image](https://cloud.githubusercontent.com/assets/13420618/23675866/c599ef9a-0348-11e7-925d-12db2de27ba9.png)

Queues (under tables): 
![image](https://cloud.githubusercontent.com/assets/13420618/23675886/d4adc556-0348-11e7-93cb-ad8c63961864.png)

**Comment by shanear** [comment]
@gnakm only issue with queues is that we don't actually implement any queues this way. We use tables to show a case workers history, but no assignment is done via the table.

**Comment by gnakm** [comment]
@shanear Gotcha. We should still show all 3 tables. They're all references to show how tables can be used. Going back to your comment, we should not add a queue section.

**Comment by gnakm** [comment]
@shanear let's show 2 tables. I added a description for queues. 

# Tables

We use tables to display information across Caseflow. For aesthetic purposes, tables in Caseflow are borderless. Table headings should be bold but with a white background.

Often tables will contain an primary action a user can take on the table item. These actions should always be placed in the right most column of the table and should be right aligned with the edge of the table.


<img width="499" alt="screen shot 2017-03-06 at 11 05 07 am" src="https://cloud.githubusercontent.com/assets/13420618/23617965/d5a333ca-025c-11e7-8559-33e32b4c6a1d.png">

## Queues

Tables are most frequently they are used in users’  Queues, a list of work items for a user to take action on. Queues are shown in the standard App Canvas and are shown in tables. A distinct feature of queue tables is the right-aligned actionable link, such as “Assign »,” located on the far right column. 

<img width="501" alt="screen shot 2017-03-06 at 11 05 21 am" src="https://cloud.githubusercontent.com/assets/13420618/23617976/dc4df070-025c-11e7-9353-8691001fbe94.png">

**Comment by astewarttistatech** [comment]
Feedback's current view is different from the various images posted. The lines are darker than the hex code used in other parts of Caseflow.

@gnakm can you confirm?

<img width="1270" alt="screen shot 2017-03-20 at 9 53 32 am" src="https://cloud.githubusercontent.com/assets/23038505/24102705/2de41184-0d53-11e7-9ab9-fe8db523f842.png">

**Comment by gnakm** [comment]
@shanear Right now on the styleguide link, the header is padded a little more than the paddings in the rows below. Could you make sure that the headers are also 15px padded so they look just like all the other rows?

![image](https://cloud.githubusercontent.com/assets/13420618/24109844/413628a2-0d68-11e7-989a-0b4fd2a32743.png)

@astewarttistatech You're right. The table currently in caseflow feedback is outdate. It should look like this: https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide with the edit I mentioned to Shane above!

**Comment by shanear** [comment]
The padding issue was addressed.

As for the Feedback table. Can we make another issue about that in `caseflow-feedback`? It is outside the scope of this issue.

**Comment by astewarttistatech** [comment]
The feedback table was used in the AC. If that is not in scope, we need new AC written up for this issue. @shanear @gnakm

**Comment by shanear** [comment]
@astewarttistatech updated

**Comment by astewarttistatech** [comment]
@gnakm @shanear 

Current View of Style Guide: 
![caseflow-tables](https://cloud.githubusercontent.com/assets/23038505/24207214/bdbbe17a-0ef6-11e7-9866-bfc95f4ca16f.png)

**Comment by Chingujo** [comment]
@astewarttistatech @gnakm @shanear 

I edited the above story following the template I created with Gina earlier on how to finalize Style Guide stories. This should be much easier to follow and validate. @gnakm Can you please verify that this is correct. 

The above template is how issues ready to be worked on should look like in the future.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers Validated in: FF and Chrome

Steps to Validate: 
1. Go to the style guide and verify that the mocks in the AC, match what is being displayed for the "Tables" portion. 

Screenshot: (see above)

**Comment by astewarttistatech** [comment]
The copy does not match. @shanear

**Comment by astewarttistatech** [comment]
Associated PR : #1306

**Comment by astewarttistatech** [comment]
**PASSED**

Changes are in. See screenshots for copy change. 
<img width="1399" alt="screen shot 2017-03-24 at 4 07 12 pm" src="https://cloud.githubusercontent.com/assets/23038505/24311805/1be2bec0-10ac-11e7-8647-9a8feb3e3c2c.png">

**Comment by shanear** [comment]
awesome job getting in to the code @astewarttistatech 👊 🎶 🎶 🎶
