### ISSUE TITLE
Change mail task routing for withdrawn appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10766]
When Veterans send in correspondence to withdraw their appeals, we currently route those mail tasks to VLJ Support (see routing [here](https://github.com/department-of-veterans-affairs/caseflow/issues/7906#issuecomment-440442213)). Board policy has changed, and these withdrawal of appeal mail tasks should be routed to a BVA Intake queue for BVA Intake users to process. 

~Note: BVA Intake does not yet have a queue - that will need to be created prior to this ticket being completed.~

## AC
- Withdrawal of appeal tasks are routed to the BVA Intake team queue (`Case Review` team) 
   - See ticket where BVA intake team queue was created: https://github.com/department-of-veterans-affairs/caseflow/issues/10767

**Comment by leikkisa** [comment]
@laurjpeterson 
I started looking into this, and I was wondering if I could ask you more to get a sense of the scope:
```Note: BVA Intake does not yet have a queue - that will need to be created prior to this ticket being completed.```

**Comment by laurjpeterson** [comment]
@leikkisa whoops! Lowell created a queue for the BVA Intake team (Case Review queue) last week.
