### ISSUE TITLE
Cannot read property 'then' of undefined in QueueFlowModal.jsx

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10777]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5019/events/333906/

**Comment by lomky** [comment]
Happening during the `assign_to_attorney` modal. Another similar error.
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5787/

**Comment by hschallhorn** [comment]
Closing in favor of #10632 because I found it first. 🤺

**Comment by hschallhorn** [comment]
Closing in favor of #10632 because I found it first. 🤺
