### ISSUE TITLE
Create retry loop/solid error handling for big writes

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1077]
If any part of actions like certifying an appeal, or establishing a claim fail, we should be able to capture the appropriate exception and retry.

**Comment by joofsh** [comment]
@shanear Do you have a vision for what this would look like?

One of the benefits of the new EP form / review page split is that each page's submit is doing less on the backend, so I don't know if this is really needed anymore for Dispatch (at least in its current variant), but would certainly still be good long-term for other features

**Comment by shanear** [comment]
Yeah, maybe the first step here is to audit any complex transactions and see whether something like this is necessary. I'm not sure if it is or not because I haven't investigated it deeply.

If not, we can punt for now.

**Comment by joofsh** [comment]
Initial thoughts:
- Break a given transaction down into the smallest atomic units (e.g. single VBMS request, single VACOLS insert query)
- Create a sidekiq job for each of these atomic units. When necessary, ensure the jobs are sequentially linked (the first must pass before the next begins execution)

**Comment by nickheiner-usds** [comment]
> If not, we can punt for now.

And that's what we did!

![image](https://user-images.githubusercontent.com/25331532/32747101-bc83ac4a-c885-11e7-8a01-c09192c5e286.png)

This ticket should be handled by our forward proxy, so I'm going to close it.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
