### ISSUE TITLE
Styleguide component | Typography - Spacing

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1078]
As a developer or designer, I want a guideline for typography sizing and spacing, so that it is 
consistent through every app. 

## Note Note Note! 
- We do NOT need to display this in the style guide. This is for the code
- We are retiring the previous h1 (44px). Please check the new heading sizes:

Display 1 - 52px (font-weight: 700)
Display 2 - 44px (font-weight: 400)
Heading 1 - 34px (font-weight: 700)
Heading 2 - 24px (font-weight: 700)
Heading 3 - 19px (font-weight: 700)
Heading 4 - 15 px (font-weight: 700)
Heading 5 - 13px (all caps, font-weight: 400)
Lead paragraph - 22px (font-weight: 400)
Body copy - 24px (font-weight: 400)
Italic body copy - 17px (italic)

## Acceptance Criteria

- Verify that the spacing for every text style is in our code

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25583548/3f3cfa4e-2e60-11e7-8356-3d161070fbbd.png)

**_Note: Character width shown in mock is not in scope of this issue._**

## Related 
#1685

**Comment by gnakm** [comment]
@Sjones352 Hey! I took out the max-width in the AC for this issue. Design team will revisit and probably put it back next sprint.

**Comment by astewarttistatech** [comment]
@Sjones352 where can I access the spacing? Inspector isn't showing it currently.

**Comment by Sjones352** [comment]
@astewarttistatech try Inspector now. It's working right.

**Comment by astewarttistatech** [comment]
**FAILED** 

Spacing found in inspector between elements is incorrect. 

Current view of spacing in inspector:
![sgtypography1](https://cloud.githubusercontent.com/assets/23038505/26109448/9c43cfba-3a1d-11e7-9f3f-5dbba9d5c65f.gif)

**Comment by Sjones352** [comment]
Everything is fixed. 
The italic Body copy inherits its properties from the p tag.

**Comment by astewarttistatech** [comment]
@gina which is correct the copy in the AC or the mocks?

**Comment by gnakm** [comment]
@astewarttistatech The fonts in the mock reflect the AC. The orange bars underneath each header type is the margin-bottom.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access the Style Guide
2. Validate the spacing in the Typography section against the AC and the mocks. 

Screenshots:
![sgtypographyspacing](https://cloud.githubusercontent.com/assets/23038505/26308111/ce4d7b9e-3ec5-11e7-868c-13ae6cc1abc7.gif)
