### ISSUE TITLE
Save edited contention text to server

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10780]
This is step 4 of editing contention title text.

## Acceptance Criteria

* When an issue's title has been edited and the "Submit" button is clicked, the Save button activates if it isn't already active (see #10597).
* When the "Save" button is clicked the edited title text is sent to the server instead of the original text, and is stored in the `edited_description` column on the `RequestIssue`.
* All other UI alerts remain the same.

**Comment by leikkisa** [comment]
@Sjones352 As part of this PR, can we disable the "edit contention text" feature during regular intakes, and only allow it during "edit"?  Thank you.

**Comment by Sjones352** [comment]
@leikkisa not sure what you mean as the feature toggle is only allowed in `edit` but please send me an example where it shows on regular intake. I will also remove it from appeal as it does not apply to appeals. Please let me know if Colin said that this was good to go.

**Comment by leikkisa** [comment]
Validated in UAT:
![Screen Shot 2019-06-03 at 1.02.14 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/23201c8b-8862-41fb-80e2-7c0c36d3b6a8)
