### ISSUE TITLE
Invariant Violation: update(): $merge expects a target of type 'object'; got undefined

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10799]
This is an intermittent error we've seen in Sentry since December. It always happens on the queue URL: https://appeals.cf.ds.va.gov/queue

Here is the latest event:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3177/events/335986/

It looks like the `update` function in app/queue/reducers.js on line 506 is what is causing this.

**Comment by monfresh** [comment]
Here's another instance in a different URL:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3147/events/335842/

This is one is in:
https://appeals.cf.ds.va.gov/queue/appeals/3023721/tasks/3023721/draft_decision/dispositions

This time it's on line 303 of `app/queue/reducers.js`

**Comment by ferristseng** [comment]
Also seeing this on reader:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3045/events/360437

In the `app/reader/Documents/DocumentsReducer.js`

**Comment by lomky** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5281/

**Comment by hschallhorn** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7258/

**Comment by jcq** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7079/

**Comment by ferristseng** [comment]
Here too: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7878/?referrer=webhooks_plugin

**Comment by ajspotts** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9452/

**Comment by yoomlam** [comment]
This happens several times per day and for many users.

**Comment by yoomlam** [comment]
For these: 
> https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9452/
> https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10311

The problem is similar but for different code (`editingIssue` is undefined):
<img width="743" alt="image" src="https://user-images.githubusercontent.com/55255674/82462658-786ba280-9a81-11ea-86bd-28da0dc62438.png">
