### ISSUE TITLE
Styleguide component | Colors

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1079]
As a developer and content writer, I want to see the order of how the color section and subsection will look like in the living style guide.

## Acceptance Criteria

* NOTE: due to several revisions, please refer to the approved [screenshots](https://github.com/department-of-veterans-affairs/caseflow/issues/1079#issuecomment-297414077) during validation.

- [x] Verify that there a title for Colors
- [x] Verify that there is Colors in the side nav of the style guide
- [x] Verify that Colors in the side nav takes you to the section
- [x] Verify that there are 3 subsections: Palette, Logos and Text accessibility
- [x] Verify that Primary colors, Secondary colors are third level in nav under Palette
- [x] Verify that this looks is what side Navigation looks like
- [x] Verify that the all color swatches are 110px x 110px and has a drop shadow (`gray-medium`)
- [ ] Verify that each color swatch has color name and hex number in bold, all text in 19px.

## Mockups

![image](https://cloud.githubusercontent.com/assets/13420618/25246814/d614e8a6-25d6-11e7-8fb2-04529caf0cb0.png)

Details for dropshadow

![image](https://cloud.githubusercontent.com/assets/13420618/23619575/1775617e-0262-11e7-9754-f6740db84931.png)

![image](https://cloud.githubusercontent.com/assets/13420618/23619586/1c6e1bb2-0262-11e7-94aa-51abe693aa0b.png)

## Colors in hex:

**Primary**

#212121
Base

#323a45
Gray-dark

#d6d7d9
Gray-lighter

#0071bc
Primary

#ffffff
White

**Secondary**

#e31c3d
Secondary

#2e8540
Green

#f9dede
secondary-lightest

#e7f4e4
green-lightest

#e1f3f8
primary-alt-lightest

#fff1d2
gold-lightest

**Logos**

#844e9f
Dispatch

#F0835e
eFolder Express

#73e5d4
Feedback

#459fd7
Certification

#417505
Reader

## Copy

**Colors**

**Description**

Caseflow's palette borrows heavily from USWDS to communicate warmth and trustworthiness while meeting the highest standards of 508 color contrast requirements. 

**Primary Colors**
Description: This palette’s primary colors are blue, gray, and white. Blue is commonly associated with trust, confidence, and sincerity; it is also used to represent calmness and responsibility.

**Secondary**
Description: 
These are accent colors to provide additional lightness and style to pages looking for a more modern flair. These colors should be used to highlight important features on a page, such as buttons, or for visual style elements, such as illustrations. They should be used sparingly and never draw the eye to more than one piece of information at a time.

**Logos**
Description:
Logos are the only time Caseflow products use colors outside of Web Design Standards. These unique colors add a layer of modernism and fluidity to the Cashflow's core color themes of of trust, reliability, and transparency. 

**Test and Background**
Description:
WCAG (Web Content Accessibility Guidelines) ensure that content is accessible by everyone, regardless of disability or user device. To meet these standards, text and interactive elements should have a color contrast ratio of at least 4.5:1. This ensures that viewers who cannot see the full color spectrum are able to read the text.

The options below offer color palette combinations that fall within the range of Section 508 compliant foreground/background color contrast ratios. To ensure that text remains accessible, use only these permitted color combinations.

If you choose to customize beyond this palette, this color contrast tool is a useful resource for testing the compliance of any color combination.

**Comment by gnakm** [comment]
@Chingujo to add description

**Comment by Chingujo** [comment]
@gnakm 

Description added above for review =D.

**Comment by slj** [comment]
@gnakm can the boxes be smaller, like 110x110?

**Comment by slj** [comment]
@gnakm here are snapshots with the boxes at 110px x 110px:
<img width="694" alt="screen shot 2017-04-24 at 3 57 03 pm" src="https://cloud.githubusercontent.com/assets/1053255/25356064/e7686f14-2906-11e7-8d2d-a529898de46d.png">
<img width="575" alt="screen shot 2017-04-24 at 3 57 33 pm" src="https://cloud.githubusercontent.com/assets/1053255/25356065/e96159b6-2906-11e7-99e5-64968b6930ad.png">
<img width="680" alt="screen shot 2017-04-24 at 3 57 58 pm" src="https://cloud.githubusercontent.com/assets/1053255/25356069/eab46452-2906-11e7-816a-28133895fcf1.png">

**Comment by slj** [comment]
@gnakm `gray-lighter` was way too light - here's some shots with `gray-medium`:
<img width="466" alt="screen shot 2017-04-24 at 9 42 03 pm" src="https://cloud.githubusercontent.com/assets/1053255/25365489/142df598-2937-11e7-98d2-0571e7ce0c9f.png">
<img width="448" alt="screen shot 2017-04-24 at 9 42 24 pm" src="https://cloud.githubusercontent.com/assets/1053255/25365491/167271ee-2937-11e7-938e-c8e5e888f2d8.png">
<img width="451" alt="screen shot 2017-04-24 at 9 42 42 pm" src="https://cloud.githubusercontent.com/assets/1053255/25365492/1829ab24-2937-11e7-8989-5e87494db179.png">

**Comment by gnakm** [comment]
@slj I didn't even know we had a `grey-medium` but that works!

**Comment by slj** [comment]
As directed by @gnakm, the **Primary** and **Secondary** swatches will also include the USWDS color variables that developers can copy and paste when writing SASS rules.

**Comment by slj** [comment]
Approved Screenshots:
<img width="680" alt="screen shot 2017-04-26 at 9 45 11 am" src="https://cloud.githubusercontent.com/assets/1053255/25437662/1af30bc8-2a65-11e7-8e18-ba9e60e9ef3c.png">

<img width="720" alt="screen shot 2017-04-26 at 9 45 55 am" src="https://cloud.githubusercontent.com/assets/1053255/25437705/3da71c86-2a65-11e7-8558-5cdedb035b44.png">

<img width="725" alt="screen shot 2017-04-26 at 9 47 11 am" src="https://cloud.githubusercontent.com/assets/1053255/25437733/5abc4418-2a65-11e7-9df9-d0cab3202410.png">

<img width="374" alt="screen shot 2017-04-26 at 9 47 49 am" src="https://cloud.githubusercontent.com/assets/1053255/25437760/70aeb076-2a65-11e7-9a79-784671e1a644.png">

**Comment by kierachell** [comment]
**PASSED**
looks smooth!
