### ISSUE TITLE
ama_acd_task feature is still being toggled in tests

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#10792]
Automatic case distribution [has been enabled](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1974/files) since ama day, but we [still have tests](https://github.com/department-of-veterans-affairs/caseflow/search?q=ama_acd_tasks+path%3A%2Fspec&unscoped_q=ama_acd_tasks+path%3A%2Fspec) that rely on enabling and disabling this feature.

## AC
- [ ] Remove all references to the feature flag `ama_acd_task`
- [ ] Remove all references to the feature flag `ama_auto_case_distribution `

**Comment by lowellrex** [comment]
XS. Make sure that all tests assume this flag is on now. Remove old tests that test what happens when it is off (since that won't happen anymore). After this is live let's remove the flag from the config in appeals-deployment (different PR).

**Comment by hschallhorn** [comment]
@lowellrex  noticed `ama_auto_case_distribution` feature references as well which is also enabled in prod. Do we want to loop that feature into this issue as well?

**Comment by lowellrex** [comment]
Yes please! Looks like [we turned this feature toggle on](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1982) on AMA day and we don't expect to ever turn it off so we can go ahead and remove the code that executes in the false condition.

**Comment by monfresh** [comment]
What about the `automatic_case_distribution` flag? That looks to be enabled in prod as well: https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/features-config.yml#L91
