### ISSUE TITLE
Change text "Please contact the Caseflow Team"

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10804]
Since we have disabled the feedback button and Caseflow support phone, we need to change the text in our code that states `Please contact the Caseflow Team` / `please contact Caseflow support` because it very confusing to our users.

**Comment by pkarman** [comment]
@laurjpeterson we should think about how we direct users to contact us now that we have changed to YourIT.

**Comment by laurjpeterson** [comment]
Agree. Can you remind me where this text shows up in the application?

@msj0nes - I'll defer to you on language here. Thinking it could be "Please contact YourIT for support?"

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/search?q=%22Please+contact%22&unscoped_q=%22Please+contact%22

**Comment by msj0nes** [comment]
@laurjpeterson and @pkarman
>Please contact the Caseflow team via the VA Enterprise Service Desk at 855-673-4357 or by creating a ticket via YourIT, if experiencing technical difficulties.

Or something along those lines. If the word YourIT could be hyperlinked to **_https://yourit.va.gov/va_** that would be great.

**Comment by pkarman** [comment]
Include the "Issues not Editable" error message for intake.

**Comment by pkarman** [comment]
done merged and deployed.
