### ISSUE TITLE
Styleguide component | Link button

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1080]
As a user, I want to know that a button is clickable. 

As a developer and designer, I want clear and consistent actions to increase design and development efficiency across apps.

## Acceptance Criteria 
1.  Verify that in the living style guide that there is a title called Link Buttons with description below For visual reference: #1138
1.  On the side navigation, Link buttons will be under Buttons.

## Mockups
![image](https://cloud.githubusercontent.com/assets/13420618/23619668/61543900-0262-11e7-83d3-fd6dbda59ad4.png)

**_Note: Copy should be in sentence case for both buttons and text links_**

## Copy

Title: 
Link button 

Description:
In order to keep links inlined with other button styles, we have these links.
The copy should always be in sentence case unless it contains the name of a product, page title, form name or title of table.

Examples: Caseflow Certification, Review Decisions, Work History, Form 9.

**Comment by kierachell** [comment]
<img width="1228" alt="screen shot 2017-04-16 at 3 32 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/25073704/ed0c7d3c-22b9-11e7-8970-b6e053cdabe4.png">


well, then...

**Comment by kierachell** [comment]
2 things:

- `Signup` vs `Sign Up`
- Underline goes through `g` and `p`
<img width="823" alt="screen shot 2017-04-17 at 3 17 44 pm" src="https://cloud.githubusercontent.com/assets/18075411/25101194/458b5a06-2381-11e7-9128-5467f1d2163e.png">

**Comment by gnakm** [comment]
@tejans24 @kierachell 

Sign up should be two words and underline going through g and p is fine. The sketch version is weird.

**Comment by astewarttistatech** [comment]
Pushing back since no change has been made to the "Sign Up" button

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Access the living style guide.
2. Verify that the buttons match the mocks provided. 

Screenshots:
<img width="853" alt="screen shot 2017-04-26 at 10 44 52 am" src="https://cloud.githubusercontent.com/assets/23038505/25440846/9cdee496-2a6e-11e7-8021-db700fbc2f04.png">
