### ISSUE TITLE
404 not found Frontend errors on various queue pages (superagent/lib/client in u.<anonymous>)

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10802]
These errors happen several times each month, mostly on the `/queue` index page, but also other endpoints, like `organizations/privacy`, `queue/:id/assign`, `queue/appeals/:id`, and others you can see here:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/events/?query=not+found

**Comment by hschallhorn** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5882/ as well!
