### ISSUE TITLE
Styleguide component | Searchable dropdown

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1081]
As a developer and designer, I want clear and consistent actions to increase design and development efficiency across apps. I want to know what the interaction looks like for a searchable dropdown so I know how to implement it. 

# Description
The searchable dropdown has two behaviors -- an option can be picked by either clicking the arrow icon and scrolling through choices or by clicking into the text box and typing in the component like a search box

# Acceptance Criteria

1. Verify that the title "Searchable dropdown" appears
1. Verify that there is a horizontal line above the title
1. Verify that the "Searchable dropdown" appears under the copy with the related react component 
1. Verify that the "Searchable dropdown" appears on the left nav and clicking it takes you to the appropriate element 
1. Verify that a user can click on the dropdown icon and see the list of options in the dropdown
1. Verify that a user can see a type cursor when s/he hovers over the input dropdown.
1. Verify that a user can click in the box and type in his/her own option
1. Verify that the hint text inside box changes colors to 737373 after it's been clicked
1. Verify that a user can see options in dropdown according to what they typed in
1. Verify that the dropdown box size should be always be 180px in height. 
1. Verify that the text box does not have an icons
1. Verify that the color of hover is #5B616B
1. Verify that an option is instantly selected by clicking on the option.

# Mockup

![searchable dropdown](https://cloud.githubusercontent.com/assets/13420618/24341386/4f168538-1287-11e7-8fbd-a3bf58e19c6b.gif)

After an issue is selected or entered, options should show in the styling below. 
![image](https://cloud.githubusercontent.com/assets/13420618/24716767/0ab3b568-19fe-11e7-825d-2540fa79bf8d.png)

# Copy

The searchable dropdown provides more context to users' choices. This is helpful in cases where there is a large dropdown menu with many options. This dual behavior dropdown component make the dropdown easier to use and options more readily available for the user. 

# Related Stories
n/a

**Comment by mdbenjam** [comment]
Before anyone works on this, chat with me. I started doing something like this a while ago, and can provide my code as a starting point.

**Comment by gnakm** [comment]
@tejans24 can you chat up with @mdbenjam so he could share his knowledge with you? 😺

**Comment by gnakm** [comment]
@tejans24 
RE: our convo on having the text input actually in the text box, here are the newer mocks

![image](https://cloud.githubusercontent.com/assets/13420618/24110775/b8c49b54-0d6a-11e7-893d-a74b3eb4d4b7.png)

**Comment by tejans24** [comment]
<img width="765" alt="screen shot 2017-04-05 at 10 48 22 am" src="https://cloud.githubusercontent.com/assets/1976755/24711397/d6d024bc-19ed-11e7-9769-18f0dd68c0db.png">

**Comment by Chingujo** [comment]
@gnakm 

What exists now. The use case here is when a user has already selected an issue and instead of searching they use the dropdown to scroll through the options. 

In the above case there needs to be contrast between the selected and the search as the user moves down the options.

**Comment by gnakm** [comment]
@Chingujo 

I liked the Max width suggestion. As for hover vs. selected, I think having two colors isn't ideal. 
What about keeping the already selected in bold and hover always in #5B616B

ex. https://semantic-ui.com/modules/dropdown.html > Search Dropdown

**Comment by Chingujo** [comment]
nice @gnakm 

Selected: 

<img width="500" alt="screen shot 2017-04-05 at 11 48 16 am" src="https://cloud.githubusercontent.com/assets/23316107/24714442/86b5c85c-19f6-11e7-8f97-8c75d10eccb8.png">

When scroll over selected:

<img width="510" alt="screen shot 2017-04-05 at 11 51 55 am" src="https://cloud.githubusercontent.com/assets/23316107/24714595/f14eebe4-19f6-11e7-84a9-e7db1bdd58c5.png">

**Comment by gnakm** [comment]
Dropping our slack conversation here:
Looks like we may have been communicating through a previous version we had. 
What should happen is an option is selected when it is clicked. Once it is clicked, the option should show below the dropdown. 

With that said, there is no need to show what was previously selected because it will show up as an option in a button style. For reader, we are giving users the option to delete an option by clicking on the next on the right. 

![image](https://cloud.githubusercontent.com/assets/13420618/24716738/f7c288e4-19fd-11e7-8405-eaa58f0fac0e.png)

**Comment by tejans24** [comment]
This only includes the single select dropdown, there is another issue for multi-select

**Comment by astewarttistatech** [comment]
Blocked due to an issue getting working VACOLs IDs in the UAT environment

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in Demo
Validated on FF (Chrome browser is experiencing issues)

Steps to Validate: 
1. Go to Style Guide and verify the section for searchable dropdown 

Screenshots: 
<img width="1286" alt="screen shot 2017-04-12 at 10 42 36 am" src="https://cloud.githubusercontent.com/assets/23038505/24963643/2846c68c-1f6d-11e7-8fac-ce8a5c4e3f26.png">

**Comment by tejans24** [comment]
<img width="496" alt="screen shot 2017-04-12 at 4 05 22 pm" src="https://cloud.githubusercontent.com/assets/1976755/24977179/3533d3f8-1f9a-11e7-956d-faca874399f9.png">

Here is the updated mock for this

**Comment by astewarttistatech** [comment]
@tejans24 I added a header to allow clearer viewing of the comment. In the future, could you add it to the actual AC at the top of the comment.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in Demo
Validated on FF (Chrome browser is experiencing issues)

Steps to Validate:

   1. Go to Style Guide and verify the section for searchable dropdown

Screenshots:
<img width="1347" alt="screen shot 2017-04-13 at 8 48 05 am" src="https://cloud.githubusercontent.com/assets/23038505/25005269/28a4b8b4-2026-11e7-9c35-f1f8cf3916ab.png">
