### ISSUE TITLE
"Loading chunk failed" error from webpack

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10813]
Sentry issue: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3020/events/336094/

Webpack will occasionally throw this error when it has trouble loading a chunk (a part of a bundle); [this appears to be a common error](https://github.com/webpack/webpack/issues/7502) that often corresponds to network issues, though I'm not confident that that's the problem here; it [may also have to do with naming or configuration](https://stackoverflow.com/a/45401738).

**Comment by monfresh** [comment]
Another instance here while fetching efolder:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3020/events/394341/
