### ISSUE TITLE
"bad encoding in flate stream" error from pdf.js with certain documents

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10812]
Sentry error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3013/events/336170/

[pdf.js](https://github.com/mozilla/pdf.js) has trouble rendering some PDFs, [possibly due to incompatible font issues](https://github.com/mozilla/pdf.js/issues/5798), and errors with the message "Bad encoding in flate stream". This doesn't appear to affect the ability of the user to view the document.

**Comment by ferristseng** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5286/

**Comment by jcq** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7897/
