### ISSUE TITLE
Add back-end support for changing Task type

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10826]
#7126 created the front-end for changing `Task` types. This ticket exists to implement the back-end support for this new modal.

## Acceptance criteria
* [ ] Create new endpoint that accepts an existing task ID, a new task type, and any additional instructions we receive from the front-end (We can use the [Tasks/PlaceHoldController](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/tasks/place_hold_controller.rb) as a model here).
* [ ] Add code to duplicate the existing task as a sibling with the new task type and any additional instructions.
* [ ] Turn this feature on by [adding the action to the appropriate tasks](https://github.com/department-of-veterans-affairs/caseflow/pull/10693/files#diff-738d69bc1fa41b93704d5dcc4d805639R83)

**Comment by hschallhorn** [comment]
@laurjpeterson I remember you mentioning a 3rd type of task this issue should cover other than `ColocatedTask` and `MailTask` (which are the only two this covers). What was the third if you don't mind reminding me?

**Comment by lowellrex** [comment]
Maybe [`HearingAdminActionTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/hearing_admin_action_task.rb)?

**Comment by laurjpeterson** [comment]
I'd love @Chingujo and @pshahVA's thoughts on whether HearingAdminActionTasks should be included at this time. 

Phillip - is there ever a time when a user may have accidentally assigned one HearingAdminActionTask and needs to change the task type to another HearingAdminActionTask?
