### ISSUE TITLE
Styleguide component | Date Input

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1082]
As a designer and developer, I want to quickly and consistently create date inputs for apps and understand what the interaction should look like. 

# Description
The date input is currently being used in Caseflow Intake. Currently there are a couple of bugs with the. For best practices, we should always make sure that there is an example with date before the component. 

[Code for date input
](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/DateSelector.jsx)

Example of the funky stuff you can currently do:
![image](https://user-images.githubusercontent.com/13420618/33278430-87771eb2-d369-11e7-91af-fbaa50a7e4fd.png)

# Acceptance Criteria
- [ ] Verify that the width of the date input box is 80px wide
- [ ] Verify that while replacing each corresponding letter, the other hints are still showing
- [ ] Do not accept months > than 12
- [ ] Do not accept dates > than 31
- [ ] Do not accept date > than the present year
- [ ] Verify that a user can tab, arrow, click, or "/" into the appropriate date fields
- [ ]  Verify that an error state pops up when a non-existing month or date, or future year is entered
- [ ]  Verify that there is an example with date like the one shown in mock.

Accessibility testing
1. When using keyboard, user should be able to tab into date input and move between mm/dd/yyyy with arrow. 
Note: For screen readers, the date hint at the top should be audio reference to what the format should be.

# Mocks

![image](https://user-images.githubusercontent.com/13420618/33291073-ace40c9a-d392-11e7-8230-995fbdf4e935.png)

# Copy
Date input allows users to click in the input box and type in a date quickly and in a format that validates each input. Designers and writers are recommended to add an example in the correct format above the component (example: 07/04/1776) so that users have a quick and easy instruction.

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/1997

**Comment by gnakm** [comment]
@Chingujo We should actually hold off on this... this is a 508 issues. I need to think a little more about this but basically, when a user clicks into the text box, you lose the instructions as you type. Also for those who are using screen readers, MM/DD/YYYY will be phonetically read out loud. 

We could either:
1. Go back to the way were were using date input, or
2. Put together better content before the input box

**Comment by mmlumba** [comment]
@gnakm Link to invision doesn't work

**Comment by joofsh** [comment]
@mmlumba @gnakm Is this ticket ready to be worked on? If it's still blocked I'll move it back to triage

**Comment by mmlumba** [comment]
@joofsh The ticket is ready to be worked on

**Comment by gnakm** [comment]
@mmlumba I defer to you!

**Comment by joofsh** [comment]
@mmlumba thanks!

**Comment by nickheiner-usds** [comment]
> @Chingujo We should actually hold off on this... this is a 508 issues.

@gnakm is this ready to be worked on? It looks like the AC still has the 508 issue that you cited.

**Comment by gnakm** [comment]
This is now ready! Note: Whoever picks this up, I would like to do a verbal walk through for 508 reasons.

**Comment by nickheiner-usds** [comment]
> Verify that an error state pops up when a non-existing month or date, or future year is entered

Only future years? Or any future date?

Doesn't our date picker already do this? I haven't checked just now, but the AC sound pretty similar to what we already do. Is this ticket just cover taking the existing date picker and putting it on the styleguide page?

**Comment by gnakm** [comment]
@NickHeiner I might be going crazy but I didn't know one was already built because it isn't on style guide. We always had it in our UI kit as something that will be added. If it already have it, great -- we just need to add it to style guide.

**Comment by gnakm** [comment]
I'm going to kick this back because we might be talking about similar components with two different functions. Let me work on this ticket again. The one existing, which validates dates should be added to style guide. Date input is a different function that we will need but I will punt on it because we are not using it yet.

**Comment by alisan16** [comment]
Closing as this is now obsolete.
