### ISSUE TITLE
Invariant Violation: Objects are not valid as a React child (found: object with keys {}).

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10829]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5055/events/345796/

At /hearings/schedule URL

**Comment by lomaxap** [comment]
Alerts stopped 5/20/2019 around the same time we refactored a lot of hearing prep (https://github.com/department-of-veterans-affairs/caseflow/commits/master/client/app/hearings/reducers/index.js). This is most likely resolved, but will keep an eye out for new error.
