### ISSUE TITLE
task claimant name undefined

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10828]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5114/

Throws JS TypeError on `return task.claimant.name.toLowerCase().includes(lowercaseSearchText)`

**Comment by pkarman** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5135/events/356965/

**Comment by leikkisa** [comment]
I think there was a PR for this, I have fuzzy memories of looking at it with Sandra.  We also haven't seen this since May, so closing.
