### ISSUE TITLE
create new scope  in `Task` that finds actionable tasks  that filters out `on_hold` tasks

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10825]
create a scope in `Task` that finds actionable tasks - this would entail renaming `active` to `open` and use `active` to mean actionable

- update all usages/instances of `tasks.active.where.not(status: :on_hold)` to use this new scope

- update `most_recently_assigned_to_label` in `app/models/appeal.rb ` to use this new scope

- fix the 30+ failing tests as a result of this change

**Comment by lowellrex** [comment]
Could we include renaming `inactive` to `closed` as well? So we end up with the following taxonomy: 
![image](https://user-images.githubusercontent.com/32683958/58029892-880d7f80-7aeb-11e9-9a67-ca95b37580bd.png)

Where we currently have:
![image](https://user-images.githubusercontent.com/32683958/58029962-b25f3d00-7aeb-11e9-9120-9adfe37865bb.png)

**Comment by youngfreezyVA** [comment]
sounds good! that makes sense. i'll also follow the bullet points above and look to replace usages of the old taxomony of closed/inactive
