### ISSUE TITLE
Automatically end IHP tasks after a set period of time

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10824]
Currently, tasks to draft informal hearing presentations (IHPs) are [only completed when the assigned VSO marks them as such](https://github.com/department-of-veterans-affairs/caseflow/blob/cb3cf31bc2e86d418fc45a4fd724adec0585215e/app/models/tasks/informal_hearing_presentation_task.rb#L9). This ticket exists to automatically mark IHP tasks complete after the deadline has passed.

## Acceptance criteria
* [x] Determine what the deadline for IHPs is (see [related Slack discussion](https://dsva.slack.com/archives/CA1QBDLEL/p1558361145003700))
* [ ] Add code to mark IHP tasks complete after the deadline has passed (#11408 undone by #11426)
* [ ] Confirm that `TaskTimer`s are being created from ☝️ this change live in production
* [ ] Backfill `TaskTimer`s for existing IHP tasks.
* [ ] Confirm that IHP tasks that were past their deadlines were closed after their `TaskTimer`s were picked up by the [job that runs at the bottom of every hour](https://github.com/department-of-veterans-affairs/appeals-deployment/blob/61570d9bc78d85d0ec7e0340362c965efa7a80cb/ansible/vars/aws-config.yml#L529).

**Comment by laurjpeterson** [comment]
On 5/18, we heard that the Chairman proposed 30 days for AODs and 120 for all other cases, starting June 1, but we were going to meet with the VSOs again before they finalized it.

**Comment by lomky** [comment]
Would we want these to be marked `completed` or `cancelled` if the date has passed without the task being marked completed?

**Comment by pkarman** [comment]
I would think `cancelled` makes more sense. Maybe even `auto_cancelled` to indicate the "how"?

**Comment by laurjpeterson** [comment]
is `auto_cancelled` already an option? i thought the closed statuses were just `completed` and `cancelled` so far. if we can add another one, that'd be great! it'd be more clear than both

**Comment by lowellrex** [comment]
We will need to backfill timers for a handful of existing IHP tasks. At the time of this writing, [there are 30 IHP tasks](https://caseflow-looker.va.gov/sql/ffhnq8b5mvrqxh) that are past due. We can use the following sql statement to confirm that the addition of the task timers to the existing IHP tasks was successfully by tracking whether these 30 IHP tasks are marked complete.

```sql
select id
, type
, status
, created_at
, appeal_type
, appeal_id
from tasks
where status not in ('completed', 'cancelled')
  and type = 'InformalHearingPresentationTask'
  and created_at < current_date - interval '120 days';
```

**Comment by lowellrex** [comment]
We should be able to use [a query like the following](https://caseflow-looker.va.gov/sql/y8pbqrrnxbv9f9) to confirm that we have successfully started creating the task timers that will close the IHP tasks when they reach their deadline.

```sql
select count(*)
from task_timers
where task_id in (
  select id
  from tasks
  where type = 'InformalHearingPresentationTask'
);
```

**Comment by laurjpeterson** [comment]
@lowellrex - let's still consider this blocked. I spoke with John Gosnell, BVA chief of technical infrastructure, to see if he can help us track down answers. 

I see that we have 3 potential options for the Board to choose from to comply with these IHP turnaround times:
1. When IHP timelines are finished, we **cancel** the task 
1. When IHP timelines are finished, we **complete** the task
1. When IHP timelines are finished, we make changes to ACD to allow them to be distributed. (We were also asked to change the color of the days waiting a while back, documented here - https://github.com/department-of-veterans-affairs/caseflow/issues/8664)

I think the Board will prefer the third one, but John is going to chase this down. I realize this increases the scope of the work.

**Comment by laurjpeterson** [comment]
Got mor information about this today. The Chairman needs to make the decision on whether we "actually take these cases away from VSOs", i.e. that we can complete the task and the IHP task moves from assigned --> completed tabs. She is back on Monday, and can make the decision then.

They would like to see a list of cases and VSOs where the deadline has passed. Your SQL query/Looker repot gets us close to that. Is it possible to add a Veteran File Number column and Assigned to Organization name (to get the VSO)? It would probably also be helpful to include which are AODs or not, because AODs have a 30 day time limit vs. the rest having 120 days.

I can also re-create your report, but I'd need help making the calculation you make in the query.

**Comment by lowellrex** [comment]
Once the code in #11426 that stops automatically creating timers for IHP tasks is in production we will need to remove the task timers that we created while that that code was live. As of this writing [we have created 11 timers](https://caseflow-looker.va.gov/sql/rcchcqhxtvyxsq).

**Comment by lowellrex** [comment]
@laurjpeterson [here is the list of 33 IHP tasks](https://caseflow-looker.va.gov/sql/gqnw7gnngdtrdv) older than 120 days with file number and VSO name:

```sql
select appeals.veteran_file_number
-- , tasks.id
-- , tasks.type
-- , tasks.status
, organizations.name
, tasks.created_at
, current_date - tasks.created_at as days_open
-- , tasks.assigned_to_type
-- , tasks.appeal_type
-- , tasks.appeal_id
from tasks
join appeals
  on appeals.id = tasks.appeal_id
  and tasks.appeal_type = 'Appeal' -- All IHP tasks are for AMA appeals.
join organizations
  on organizations.id = tasks.assigned_to_id
  and tasks.assigned_to_type = 'Organization' -- All IHP tasks are assigned to organizations.
where tasks.status not in ('completed', 'cancelled')
  and tasks.type = 'InformalHearingPresentationTask'
  and tasks.created_at < current_date - interval '120 days'
order by organizations.name, days_open desc;
```

Getting AOD status for these appellants will take a considerable amount more time, but if we want to add that information as well we can do that.

**Comment by laurjpeterson** [comment]
Discussion 7/23/2019:

Option 3:
- After time limit, we could instead of complete/closing the IHP task, we could just say the DistributionTask is ready (assigned/in progress)
- Note added to IHP task, in currently active tasks, like "IHP time limit reached, no need to review IHP when drafting decision"
- Can close the IHP task when the appeal is decided
- Future possibility:
   - Board could have users authorized to cancel IHP tasks on behalf of VSOs

Option 1:
- If we complete task, needs a note "IHP time limit reached, no need to review IHP when drafting decision" or the like...

BVA idea:
- When time limit done, BVA gives warning to VSO. Then, they have to submit within 5 business days, or extension?

**Comment by lowellrex** [comment]
Now that the code in #11426 has been released [we can cancel the timers we created](https://github.com/department-of-veterans-affairs/caseflow/issues/10824#issuecomment-512634137) (we [created 82](https://caseflow-looker.va.gov/sql/rcchcqhxtvyxsq)).

```ruby
  rails c> ihp_task_timers = TaskTimer.where(task_id: InformalHearingPresentationTask.pluck(:id))
  rails c> ihp_task_timers.count
  # 82.
  # Matches the 82 we see in Looker: https://caseflow-looker.va.gov/sql/rcchcqhxtvyxsq
  # Let's cancel them!
  rails c> ihp_task_timers.update_all(canceled_at: Time.zone.now)
  # Done!
```

**Comment by hschallhorn** [comment]
RIP Looker
```ruby
# Let's see how many tasks we have that are older than 120 days
tasks = InformalHearingPresentationTask.open.where(assigned_to_type: Organization.name).where("created_at < ?", 120.days.ago)
tasks.count
=> 1710

# How old is the oldest one?
tasks.order(:created_at).first.created_at
=> Wed, 13 Mar 2019 14:41:54 UTC +00:00

# What VSOs are these assigned to?
pp tasks.group(:assigned_to_id).order(count: :desc).count.map { |id, count| [Organization.find(id).name, count] }.to_h
{"Veterans of Foreign Wars"=>846,
 "American Legion"=>645,
 "Paralyzed Veterans of America"=>127,
 "Military Order of the Purple Heart"=>44,
 "Disabled American Veterans"=>17,
 "Marine Corps League"=>12,
 "Fleet Reserve Association"=>7,
 "American Veterans"=>4,
 "Blinded Veterans Association"=>4,
 "Vietnam Veterans of America"=>3,
 "Armed Forces Services Corporation"=>1}
```
