### ISSUE TITLE
Styleguide component | Required fields

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1083]
![image](https://cloud.githubusercontent.com/assets/13420618/23620098/cb328178-0263-11e7-8aef-29ee69272bb5.png)

![image](https://cloud.githubusercontent.com/assets/13420618/23620470/00f3b5ec-0265-11e7-93a7-827098342e41.png)

**Comment by KHarshawat-gov** [comment]
Similar to the USWDS we mark fields with a “required” or “optional” label to the top fight of the form input type. Our required text has the color `secondary` as we’ve done research showing that this makes the demarcation more noticeable. 

For form fields with radio buttons, checkboxes, or longer text than just a simple label, we place the required indicator immediately after the text in red (`secondary`) italic. For text input fields like short input boxes and long input boxes, the required indicator is aligned to the right of the box.

**Comment by gnakm** [comment]
I am going to close this because required fields are being addressed granularly in form fields. Related to #1412
