### ISSUE TITLE
combine pre-selected org methods in task_action_repository into one method

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#10840]
assign_to_privacy_team_data
assign_to_translation_team_data
assign_to_pulac_cerullo_data 

can be combined into one method with some sort of a check on the task type. code climate picked this up.

**Comment by hschallhorn** [comment]
Could leverage default_assignee to set the selected org.
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||
2 | |||||||||||
3 | 
5 | 
8 |  
```
Sounds FUN! Don't know how that translates into votes, but hey. 2 because it may not be as clean as originally thought.
