### ISSUE TITLE
Styleguide component | Banner Alerts

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1084]
As a developer and designer, I want a consistent and easy way to implement Alert Banners so users can identify if important tasks were completed correctly.   

## Note
The banner alert styles are just like the ones from the USWDS except the title typeface is Source San Pro (bold). Previously, we were using Merriweather but it's not being used anywhere else across out apps.

## Acceptance Criteria

1. Verify that in the living style guide that there is a title called Alerts
1. Verify that the description is under the title
1. Verify that there is a side nav called Alerts
1. Verify that clicking on the side nave takes you to the appropriate section
1. Verify that the styling and padding matches USWDS
1. Verify that the header is in Source Sans Pro in bold, `h2` (24px)
1. Verify that the following alerts are displayed in the `Alerts` section (not necessarily in this order): success, warning, error, info
1. Verify that this change is implemented across all apps.

*NB:* can be seen in action Certification v2, and maybe Dispatch

## Mockup

[Link to USWDS Alerts](https://standards.usa.gov/components/alerts/)

![image](https://cloud.githubusercontent.com/assets/13420618/25502539/f743b58c-2b64-11e7-86a3-5874ac0db8df.png)

## Copy

**Title:** 
Alerts

**Description:** 

Alerts allow us to communicate important changes and time sensitive information. This includes errors, warnings, and general updates. We also use them as a validation message that alerts someone that they just did something that needs to be corrected or as confirmation that a task was completed successfully.

**Comment by gnakm** [comment]
For design review -
- Write specs of how it should be used 
- When it is being used
- Spec template

**Comment by gnakm** [comment]
Could designers edit this comment and write out how the following error messages are being used in every app?

### Dispatch
Success Status (Green) - 
Warning Status (Yellow) - 
Error Status (Red) - 
Informative Status (Blue) -

### Certification
Success Status (Green) - 
Warning Status (Yellow) - 
Error Status (Red) - 
Informative Status (Blue) -

### eFolder Express 
Success Status (Green) - 
Warning Status (Yellow) - 
Error Status (Red) - 
Informative Status (Blue) -

**Comment by lakohl** [comment]
assigning myself to this issue so I remember to update it tomorrow!

**Comment by lakohl** [comment]
In Dispatch, after a user has clicked the 'Finish routing claim' button they land on the Confirmation page. At that point they are done. If they try to move backwards using the browser back button, they get the message below. Wondering if you think it should be yellow or red?

<img width="613" alt="screen shot 2017-03-24 at 6 16 33 pm" src="https://cloud.githubusercontent.com/assets/4975959/24315601/4c68fc5a-10be-11e7-8211-dd151d51c6e3.png">

**Comment by kierachell** [comment]
We have **Download Anyway** page in eFolder:
https://dsva-appeals-efolder-dev-972029178.us-gov-west-1.elb.amazonaws.com
search for `DEMO3`
<img width="1116" alt="screen shot 2017-03-31 at 10 00 37 pm" src="https://cloud.githubusercontent.com/assets/18075411/24574249/80ae5952-165d-11e7-9dcd-55d062b0cad2.png">

**Comment by lakohl** [comment]
Thanks for adding that last one @kierachell

**Comment by gnakm** [comment]
## Lo-fi Error Message Rubric

| Success | Warning | Error | Status | 
| -- | -- | -- | -- |
When a user completes a task and needs a validation that something went through. | When there is a systems error, or user needs to be aware of a task that potentially cannot be done or that it will be done differently than expected. This is to create expectation before the user continues to do something.  | When a user tries to continue or complete a task but they are not able to in Caseflow. | When there is a good opportunity in the flow to provide users with information that may help them through a process or additional information about a similar task. |
_It went through!_   | _Just a heads up_ | _Eek! It didn't go through!_ | _Did you know? FYI..._ |

Note: I wonder if anything action that has to happen outside of caseflow should be in red. 

For all: It is nice to have an actionable button or link  in these statuses so that users know what to do next. This could be a link to continue, refresh a page, link to a website or a phone number. 

## eFolder Express
| Success | Warning | Error | Status | 
| ---------- | -- | -- | -- |
_It went through!_   | _Just a heads up_ | _Eek! It didn't go through!_ | _Did you know? FYI..._ |
| All of the documents in VBMS are ready to download (download button) |  | Some files couldn't be added to eFolder. You can still download the rest (download anyway button) | You can close this folder at any time (while retrieving files)|

Suggestions: Error Download anyway should be yellow because the user can still continue the task.

## Certification 
| Success | Warning | Error | Status | 
| ---------- | -- | -- | -- |
_It went through!_   | _Just a heads up_ | _Eek! It didn't go through!_ | _Did you know? FYI..._ |
| Documents in Check Documents step successfully found. |  TA document labeled as a hearing request or cancellation was found in the eFolder, and RO staff is asked to verify this is the case. | Missing documents in Check Documents step. Some of the files listed in VACOLS could not be found in VBMS." | |

## Dispatch
| Success | Warning | Error | Status | 
| ---------- | -- | -- | -- |
_It went through!_   | _Just a heads up_ | _Eek! It didn't go through!_ | _Did you know? FYI..._ |
| Green alert banner! Here are the things you did (list) |  This step cannot be undone in Caseflow | This claim includes Special Issues that cannot be supported by Caseflow | Missing profile information. In order to process, open VBMS and update Veteran's profile.. We were unable to create an EP for this special issue |

Comment 

- This step cannot be undone warning should stay yellow because the red may make the user feel like they did something wrong. 
- I wonder if the unable to create an EP for this special issue error should be yellow
- This claim includes Special Issues that cannot be supported by Caseflow maybe should be in red

**Comment by Chingujo** [comment]
@gnakm 

Updated the issue with use case, AC, and a description. Can you please put the ready for dev label after review? Thanks =D

**Comment by gnakm** [comment]
That's perfect @Chingujo We can review better descriptions for each once reviewed with whole team.

**Comment by gnakm** [comment]
Add Error lites from reader!

**Comment by gnakm** [comment]
Some thoughts on errors after chatting with @lakohl last week.

- Changed error header title to Source Sans Pro because Merriweather is not being used anywhere else
- Changed font sizes (header = h2, body copy = body copy) so they match with the ones we have in our new typography part of style guide
- Add the rules "add periods at the end of each sentence," Keep the titles short
- Added a lighter version of errors (going in reader) for smaller spaces. 

![image](https://cloud.githubusercontent.com/assets/13420618/25502539/f743b58c-2b64-11e7-86a3-5874ac0db8df.png)

**Error lites**

![image](https://cloud.githubusercontent.com/assets/13420618/25503647/1b6958be-2b69-11e7-9c17-166ae3bab581.png)

**Comment by shellicious** [comment]
+1 to source sans!

**Comment by abbyraskin** [comment]
+2!

**Comment by lakohl** [comment]
@gnakm can you post an example of an error lite versions in context?

**Comment by gnakm** [comment]
@lakohl Right now, this only happens once. We created a mini-alert for reader for times systems might be down from this page 

![image](https://cloud.githubusercontent.com/assets/13420618/25582940/a8f1ebaa-2e5d-11e7-9890-4d848cf0470e.png)

**Comment by mmlumba** [comment]
@gnakm What do you think of this look for the "Technical Notes" section?
<img width="987" alt="screen shot 2017-06-21 at 3 58 43 pm" src="https://user-images.githubusercontent.com/4773320/27404033-9d05bb4a-569a-11e7-927e-9a94504211a8.png">

Basically if a section is <h2>, the "Technical Notes" section is <h3>; if its <h3> then the notes section is <h4>, etc.

**Comment by gnakm** [comment]
@mmlumba This gets tricky because different header levels can have technical notes and it might be confusing for those using screen readers to think that a technical note is another header. 

Could we have it so that we just bold Technical notes instead? That way it feels like it is a part of the body. Also, I don't think it's necessary to italicize the word React. So for this example it would be:

Alerts

Alerts allow us to communicate important changes and time sensitive information. This includes errors, warnings, and general updates. We also use them as a validation message that alerts someone that they just did something that needs to be corrected or as confirmation that a task was completed successfully.

**Technical note**: The React component reference is `Alertbanner.jsx`, and is not to be confused with `Alert.jsx`.

**Comment by mmlumba** [comment]
@gnakm I removed that section from this component since it no longer applies, but I'll keep in mind the feedback for future style guide tickets (and/or current components that need this section). Thanks!

**Comment by mmlumba** [comment]
Original AC for 7:
> Verify that the order of the alerts displayed matches the mocks
