### ISSUE TITLE
Document Hearing models and data flow

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10846]
## Acceptance Criteria

* [x] The `hearing*` models need column comments.
* [x] A narrative description of how the tables are related to one another and data models correspond to business flow. (Document in model files.)

### Notes
- There are differences in legacy vs. AMA cases relating to dates and times

**Comment by aroltsch** [comment]
This hearing task tree example is super helpful:

https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Project%20Folders/Caseflow%20Projects/Hearings/Hearing%20Schedule/Tech%20Specs/HearingTaskFlow.md#task-hierarchy
