### ISSUE TITLE
Hearing schedule index times out loading for VSO users

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10855]
The hearing schedule page has started timing out for VSO users.

[Sentry error example](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5140/events/347499/)  

Related slack threads: [one](https://dsva.slack.com/archives/C42P25D6H/p1557860730271700), [two](https://dsva.slack.com/archives/CHX8FMP28/p1558458958437100)

Closed PRs related to this work: #10796, #10819, #10845, #10850

**Comment by laurjpeterson** [comment]
@pkarman - do you think this ticket can be closed?

**Comment by pkarman** [comment]
closing -- the optimization needed is tracked in other GH issues.
