### ISSUE TITLE
Styleguide component | Introduction to layouts

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1085]
As a developer, I want clear and consistent guideline for how the layout of all Caseflow apps should look like. 

## Acceptance Criteria

- Verify that the description copy is below the title 
- Verify that layouts has the following subsections. **_Note: These sections don't have to be completed but it's good to have the title placeholder._**
  1. Navigation bar 
  1. User dropdown menu
  1. Main content area
  1. App canvas
  1. Footer

## Copy

Any Caseflow app should always follow the same layout and structure shown here. At the top of the application is the Navigation Bar. Next, sitting on the canvass of the application is the main content area. This is where the title of the page, instructions for the user, and detailed interaction should be placed. The primary and secondary actions sit below the main content area. Finally, the Footer should go at the bottom of the app. 

We try to be consistent in this layout across all our applications so that our interface is predictable and familiar to our user. The consistency also helps us reuse common code in Caseflow Commons.

**Comment by mmlumba** [comment]
@gnakm @shanear I was thinking for the entire "Layout" section we could reference the `application.html.erb` file for our "View source code" link: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/views/layouts/application.html.erb

What do you think?

**Comment by gnakm** [comment]
1. To me that makes sense but I defer to @shanear for best answer for devs. 
2. The idea was to have messages as a subsection of layout :)

**Comment by Sjones352** [comment]
@mmlumba Messages will remain a section of it's own.

**Comment by astewarttistatech** [comment]
This component isn't visible currently in UAT. Please move this issue back when it has been deployed. @Sjones352

**Comment by astewarttistatech** [comment]
@gnakm Those mocks are a tad bit confusing, since I really cannot reference that layout. Could you ditch it?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the living style guide
2. Navigate to the layout section
3. Validate the UI and copy against the AC and mocks. 

Screenshots: 
![screen shot 2017-05-31 at 10 27 24 am](https://cloud.githubusercontent.com/assets/23038505/26641485/c0be5860-45f8-11e7-9bd9-b3f9ed799d6d.png)
