### ISSUE TITLE
Show "hearing not found" error when loading hearing details page for a hearing that doesn't exist in VACOLS

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#10852]
Sentry error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4354/events/347479/

**Comment by ferristseng** [comment]
Linking this too: https://github.com/department-of-veterans-affairs/caseflow/issues/11020

**Comment by ferristseng** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/11655 may have resolved this
