### ISSUE TITLE
Support VEText with Caseflow API

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#10851]
## Background
VEText is an application that the VHA is using to send medical appointment reminder text messages to Veterans.  The hearings branch has asked to investigate the use of this system to send appeal hearings appointment reminders to Veterans.

### Hearings Branch Responsibilities
1. Schedule hearings for veterans that have requested them.
2. Gather availability of rooms, judges, as well as VSO's so that a hearings schedule can be build.
3. Build the hearing schedule.
4. Perform tasks in support of hearings such as sending official notices to veterans hearings date letters etc

### About Caseflow's API with VA.gov
[Status API controller](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/api/v2/appeals_controller.rb)

### About Caseflow's API with IDT
[Initial API spec](https://github.com/department-of-veterans-affairs/appeals-design-research/pull/931/files#diff-066279acca3d1275c002c3545fb08908)
[IDT API epic](https://github.com/department-of-veterans-affairs/caseflow/issues/6358)
[IDT API controller](https://github.com/department-of-veterans-affairs/caseflow/tree/master/app/controllers/idt/api/v1)

## Goals
1. Send a reminder to the Veteran about the hearing date, time, and location via VEText so they are more likely to show up for their hearing (increase show rates)
1. Improve the Veteran experience of hearings (increase Veteran satisfaction of appeals process)

## Assumptions
1. The Veteran has already given permission to be reached on their mobile phone
1. The VEText team can interact with our API as it exists today. The only changes we have to make to it are enhancements
1. Veteran phone number exists in BGS

### Requirements/Stories
First, we need to determine which of Caseflow's API's to enhance.

#### Enhance the Caseflow API with Veteran and hearing information
1. Investigate how to retrieve Veteran phone number from BGS
1. Retrieve Veteran phone number from BGS 
1. Add Veteran phone number to Caseflow API
1. Write tech spec to add hearing info to Caseflow API
   1. Add hearing date to Caseflow API
   1. Add hearing location to Caseflow API
   1. Add hearing time to Caseflow API

#### Veteran facing stories 
1.  When Veterans are scheduled for a hearing, they want to receive a text that explains their upcoming hearing appointment sent to me on my mobile device. 
1. When Veterans' hearings are [x weeks/days away], they should receive a text that explains their upcoming hearing appointment sent to me on my mobile device, so they are more likely to attend their hearing. 
1. If Veteran's appointment time changes, or if I cancel I should get an updated text.
 
### Open questions for Board and VEText team
1. Will the VEText team query upcoming appointments? Or does Caseflow push them to VEText?
1. How many text reminders will Veterans get and at what times?
1. What are future features for VEText? e.g. confirm hearing, cancel hearing. This is two way communication, so we'd need to plan to build for this
1. What is the current Veteran show rate for hearings? (This helps us set a baseline)

### Other resources
[Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1557332126066/410fbc0b93a216a335ee550e5d4181f3b346c8e7) to map the Veteran and VEText workflow

**Comment by laurjpeterson** [comment]
Notes from call with VEText team, PIF, the Board, and Caseflow on 5/24:

# VEText

## Requirements:
* One-way communication twice
	* 1 hearing reminder 2 weeks before
	* 2-3 days before
* BVA not open to 2-way communication yet based on law now
	* need to figure out copy/content for the text - telling the Veteran where they need to go to cancel / how they need to communicate

## VEText
* **Context from VHA**
	*  for a certain date range, certain clinic, pull Veterans who have appointments with that clinic 
	* query Caseflow for any upcoming hearings during a certain date range - pass back to us a list of Veterans that do have hearings
	* VEText is directly integrated into VISTA - if cancelled, then VISTA appointment is cancelled
* **VEText suggestions for us**
         * single API endpoint
         * propose - start getting access to the Veterans and pulling them, that will allow us to researching the best way to get phone number data
	         * MVI, Vet360, etc. 
	         * as long as we’re getting back some sort of unique identifier
         * we’ll need to support then giving a date range and us returning Veterans with hearings
* **predicting load**
	* 2 invocations of the API per day, for the dates
* **VEText rollout and testing for VHA**
	* testing with our own phone numbers
	* smaller number of Vets that we used to define requirements with
	* rolled it out to clinics with pre-notification
	* then facility wide?

**Comment by pkarman** [comment]
I need to identify whether BGS has the Veteran ICN id available.

**Comment by pkarman** [comment]
Whomever picks this up should refer to the API doc draft here:

https://github.com/department-of-veterans-affairs/caseflow/blob/pek-api-docs/docs/caseflow-apis.md#vettext--hearings-draft

Veteran ssn is now cached locally in Caseflow so that should help performance.
