### ISSUE TITLE
Styleguide component | Layout section - Navigation bar and Header

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1086]
As a designer and developer, I want to quickly and consistently create navigation bars across our apps.

# Acceptance Criteria
1. Verify that in the living style guide there is a section with the title `Navigation Bar`
1. Verify that the correct description appears below 'Navigation Bar" (see copy section) 
1. Verify that the components appears below the copy (see mocks)
1. Verify that clicking on 'Navigation Bar' in side nav takes you to the right section
1. Verify that the version in style guide has `gray-lighter` border (see mock)

**For the code**:
1. Verify that Caseflow logo has 50px left and right margins.
1. Verify that the header text has 26px top and bottom padding
1. Verify that when clicking on dropdown menu, a dropdown list comes down.
1. Verify that the header has the default logo 

# Mockups

_Make sure you are logged into Invision before clicking the Craft link_

**What the specs should be in the code**
![image](https://cloud.githubusercontent.com/assets/13420618/25237778/9e624790-25b9-11e7-8cc0-62dc332e63ea.png)

**What it should actually look like in the style guide**
![image](https://cloud.githubusercontent.com/assets/13420618/25282289/09576d36-267e-11e7-8af6-901df5ec805d.png)

# Copy:

**Title**

Navigation Bar

**Description**

The Navigation Bar is a simple white bar that sits on top of every application. Our navigation bar is non-sticky and scrolls out of view as the user scrolls down the page. It includes branding for the specific application on the left; a Caseflow logo and application name (see Application Branding for more details). 

The Navigation Bar also includes the user menu on the right. This menu indicates which user is signed in and contains links to submit feedback, view the application’s help page, see newly launched features, and log out.

**Comment by mmlumba** [comment]
@gnakm Just to give background context, we currently have 3 different styles for headers:

[Icon] **Caseflow** `Application Name`

On the work queue page there doesn't need to be a page title.
On workflow pages we have the option of including the page title using the following format (the title should reflect any navigation, like progress bars, that are used in the app)

[Icon] **Caseflow** `Application Name` > `Page Title`

Alternately some pages can include the Veteran for the case that the user is actively working on the title using the following format

[Icon] **Caseflow** `Application Name` | `Veteran Name (Vet ID)` >

This is from a past commons issue I worked on: https://github.com/department-of-veterans-affairs/caseflow-commons/issues/19

Should the style guide component reflect those changes?

**Comment by kierachell** [comment]
## AC 5
Not sure how/if it's implemented:
<img width="1019" alt="screen shot 2017-04-19 at 7 39 40 pm" src="https://cloud.githubusercontent.com/assets/18075411/25206821/40365426-2538-11e7-8635-897cb8eda61c.png">

**Comment by gnakm** [comment]
@mmlumba 
I changed #5 in AC

@kierachell I took out that like of 90px tall. I copied and pasted from the description we had and realized it doesn't make any sense.

**Comment by kierachell** [comment]
**PASSED**
Looks awesome
