### ISSUE TITLE
Refactor automatic case distribution code

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10876]
**Why**: As I'm working with this code, I'm finding it hard to understand and test. In order to improve the readability of this code, I'd like to refactor it in small increments at a time. I typically start by addressing the [Long Method](https://refactoring.guru/smells/long-method) code smells by extracting smaller, well-named methods.

**Comment by hschallhorn** [comment]
More: 
https://github.com/department-of-veterans-affairs/caseflow/pull/14745#discussion_r472325848
https://github.com/department-of-veterans-affairs/caseflow/pull/14745#discussion_r472319423

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1643
