### ISSUE TITLE
Edit contention text confirmation message

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10891]
When an Edit contention text is saved, it returns the the saved alert message. We should return another alert message saying that the contention was edited

## AC
- After a user edits contention text, they should return to the page they came from (e.g. case details) and see the below confirmation message
- Use COPY.json (so these messages can be easily updated later)

## Designs
![image](https://user-images.githubusercontent.com/11700545/58518363-c8ac6f00-8163-11e9-9f7a-dee2d961520d.png)

Notes: The confirmation for a contention title would appear back on the page where the user entered the Edit Issues page. So if the user goes back to Queue the confirmation would show up in Queue, in the same format of the confirmation if you edit a review/withdraw issues or reviews.

## Current state 
![Screen Shot 2019-05-26 at 9.46.49 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/e3306bd0-5b2b-4395-92c4-8c2b0bf9f9f0)

**Comment by carolaponce** [comment]
Short answer yes, the confirmation page would list everything that happened during the intake.  The confirmation for a contention title would appear back on the page where the user entered the Edit Issues page.  So if the user goes back to Queue the confirmation would show up in Queue, in the same format of the confirmation if you edit a review/withdraw issues or reviews.

**Comment by carolaponce** [comment]
![image](https://user-images.githubusercontent.com/11700545/58518340-afa3be00-8163-11e9-804f-8a8c61959b85.png)

**Comment by carolaponce** [comment]
![image](https://user-images.githubusercontent.com/11700545/58518363-c8ac6f00-8163-11e9-9f7a-dee2d961520d.png)

**Comment by laurjpeterson** [comment]
@Sjones352 @carolaponce - i updated the main ticket body with AC and designs. can you review and see if we need to add anything else?

**Comment by Sjones352** [comment]
@carolaponce how about `You have successfully updated  a contention title` or ` `You have successfully edited  a contention title`and that's because we are editing the contention title. Other than it looks good @laurjpeterson and I can work on it next sprint.

**Comment by carolaponce** [comment]
Hi, taking a few steps back: you can add a contention title and you can edit a contention title.  
This is only part of the edit flow - meaning post intake.
Can we have both messages?
**If the user Adds a CT:** You have successfully added...
**If the user Edit a CT:** You have successfully edited...

**Comment by leikkisa** [comment]
Validated:
![Screen Shot 2019-06-17 at 3.26.17 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/da733562-3bab-44c3-bf06-bc3c78954440)
