### ISSUE TITLE
Refactor Edit Contention text Component

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10890]
The Edit contention text component needs to refactored to conform to the set style. 
 ![Edit title 02](https://user-images.githubusercontent.com/11700545/55116058-53f57f80-50a3-11e9-9541-8db9df364e22.png)

**Comment by pkarman** [comment]
@Sjones352 could you expand a little on what needs to happen here? Is this a coding change only? Or will there be user-visible visual changes?

**Comment by Sjones352** [comment]
I think this needs to be closed because the feature is already in existence and it does not need any refactoring. @leikkisa do you think this needs refactoring?
