### ISSUE TITLE
Styleguide component | Layout section - Footer

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1090]
As a developer and designer, I want clear and consistent actions to increase design and development efficiency across apps. 

## Acceptance Criteria 

- [x] Verify that the below copy is beneath the title (see Copy below) 
- [x] Verify that that the living style guide has the correct UI components (see mock)
- [x] Verify that clicking on this takes you to the right section. 
- [x] On the side nav, `Footer` can be found under `Layout`. 

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25051524/0ff853d4-211b-11e7-9157-29cb23e6a7ed.png)

**Close up for specs**
![image](https://cloud.githubusercontent.com/assets/13420618/25051532/1a24b1fe-211b-11e7-9846-80eb49ebe3b3.png)

## Copy

Title: 
Footer

Description:
All of Caseflow Apps feature a minimal footer that contains the text “Built with ♡ by the Digital Service at the VA.” and a “Send Feedback” link. 

 Conveniently, if a developer hover’s over the word “Built” they’ll see a tooltip showing the build date of the app that they are viewing.

### Notes
1. Anchored at the bottom
2. Divided by horizontal line break: `grey-lighter`
3. Minimum of 125 px margin-top

**Comment by tejans24** [comment]
@gnakm For the 150px between the button and the top of the footer, it's hard to know which elements exist on a page and how much margin and padding they can each contain. 

It might be better to have padding-top: 125px to the top of the footer regardless of the content above?

**Comment by gnakm** [comment]
@tejans24 Could we go with 125px? I'll change the above once you give the 👌

**Comment by tejans24** [comment]
@gnakm yea, that works.

**Comment by lakohl** [comment]
@gnakm you are the best!

**Comment by gnakm** [comment]
Add this spec #1523

**Comment by Sjones352** [comment]
- [ ] Verify that the below copy is beneath the title (see Copy below) 
- [ ] Verify that that the living style guide has the correct UI components (see mock)
- [ ] Verify that clicking on this takes you to the right section. 
- [ ] On the side nav, `Footer` can be found under `Layout`. 

<img width="759" alt="screen shot 2017-05-09 at 3 12 10 pm" src="https://cloud.githubusercontent.com/assets/23080951/25868246/0993f940-34ca-11e7-9fea-21f729210075.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the style guide
2. Navigate to the Layout section
3. From Layout section, validate the footer matches the specs found in the AC above. 

Screenshot:
<img width="1375" alt="screen shot 2017-05-12 at 9 14 56 am" src="https://cloud.githubusercontent.com/assets/23038505/25999704/2bd88404-36f4-11e7-8f7e-0148fd5e09b2.png">
