### ISSUE TITLE
Unterminated string constant

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#10909]
Looks like the error is coming from this `RESET_DELETE_SUCCESSFUL` 

Sentry error https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1956/events/356971/

Issue
https://appeals.cf.ds.va.gov/hearings/schedule/docket/538

**Comment by ferristseng** [comment]
Having some trouble finding much about what could cause this. The sentry alert doesn't have a stack trace, which makes it even more difficult. I suspect it could be related to a `JSON.parse` call, but I'm not super certain, and it seems like an Internet Explorer-only issue.

I'm going to try to come up with a way to get more info around this issue.

https://stackoverflow.com/questions/43044844/ie11-edge-12-13-14-random-javascript-parsing-errors-caused-by-very-long-obje

https://stackoverflow.com/questions/13289295/unterminated-string-constant-jquery?rq=1

**Comment by lomaxap** [comment]
this seems like a IE specific issue. Caseflow officially supports chrome only. Closing for now.
