### ISSUE TITLE
Route Missing Hearing Transcript tasks to the Hearing branch

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10915]
When attorneys assign VLJ Support Staff the administrative action (`ColocatedTask`) of Missing Hearing Transcript, these tasks should be routed to the Hearing Management Branch organization, so the Hearing Management Branch can resolve the task. 

## AC
- Missing Hearing Transcript tasks should have the option to assign to Hearing Branch.
- Remove option to assign to Privacy team.

## Current behavior does not include Hearing Branch
<img width="1082" alt="Screen Shot 2019-05-29 at 10 49 13 AM" src="https://user-images.githubusercontent.com/27704093/58579255-7a4cae00-81ff-11e9-8809-2dc197e4efd5.png">

**Comment by lowellrex** [comment]
Could benefit from the task model improvements suggested in #10894 (though `ColocatedTask`s might have to be [refactored to inherit from `GenericTask`](https://github.com/department-of-veterans-affairs/caseflow/issues/9057) before we could do that).

**Comment by lowellrex** [comment]
Closing in favor of #11113.
