### ISSUE TITLE
Styleguide component | Horizontal Rule, Borders, Dividing Lines

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1091]
Story
As a developer or designer, I want to know the specs for the dividers for all of our products. 

## AC
- [x] Make a subsection called "Horizontal Rule" under Layout section
- [x] Color: `grey-lighter`
- [x] 30px `margin-bottom`
- [ ] Verify that the copy is above UI component in style guide

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/23623795/53248588-0271-11e7-8c33-aaca81c6abe5.png)

## Copy

The horizontal line can be used in multiple ways across Caseflow apps. It can be used to separate different sections and UI components and provide space for balance and legibility. There should always be a 30px space between the bottom of the component or text to the top of the horizontal line.

**Comment by gnakm** [comment]
For design meeting:

*Horizontal line*: When is it used? What are the specs?

Things we've discussed: 

- 40px above and below horizontal line? Case by case?
- Is it used to separate sections? What are the use cases?
- Does this affect margins of a canvas?

**Comment by gnakm** [comment]
@shellicious Could you help us put together a story for this, related to certification for style guide?

**Comment by shellicious** [comment]
@gnakm yes!

**Comment by lakohl** [comment]
https://va-gov.invisionapp.com/d/main/#/projects/prototypes/11033393 for mocks

**Comment by gnakm** [comment]
@avrildavid Can you take a pass at this?

The horizontal line can be used in multiple ways across Caseflow apps. It can be used to separate different sections and UI components and provide space for balance and legibility. There should always be a 40px space between the bottom of the component or text to the top of the horizontal line.

**Comment by avrildavid** [comment]
Already looks good, @gnakm. One suggestion:

The horizontal line helps provide clarity and improve legibility for users by separating different sections or UI components on a page. Caseflow horizontal lines should always have 40 px of space between the bottom of the section or component and the top of the horizontal line.

**Comment by Sjones352** [comment]
@gnakm should add this component in the layout section?

**Comment by gnakm** [comment]
@Sjones352 Added instruction in AC!

**Comment by Sjones352** [comment]
<img width="690" alt="screen shot 2017-06-06 at 10 09 45 pm" src="https://user-images.githubusercontent.com/23080951/26859330-ef6bf7c4-4b04-11e7-8334-cedf0d9e1c4c.png">

**Comment by gnakm** [comment]
@Sjones352 Could you change the content to say ...`have 30 px of space between the bottom...`

**Comment by astewarttistatech** [comment]
Current view: 
<img width="1299" alt="screen shot 2017-06-08 at 1 11 08 pm" src="https://user-images.githubusercontent.com/23038505/26941299-0491985a-4c4c-11e7-8b7c-8e181634323e.png">

pushing back because the copy is wrong based on gina's comment

**Comment by Sjones352** [comment]
<img width="685" alt="screen shot 2017-06-08 at 2 13 58 pm" src="https://user-images.githubusercontent.com/23080951/26943802-d10edfa2-4c54-11e7-86aa-429ebc33fa63.png">

**Comment by gnakm** [comment]
@Sjones352 So sleek and elegant. LGTM!

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living style guide 
2. Navigate to the Horizontal Line section 
3. Verify the copy based on AC

Screenshots: 
<img width="1267" alt="screen shot 2017-06-09 at 3 35 31 pm" src="https://user-images.githubusercontent.com/23038505/27033353-f2fea9b8-4f46-11e7-94eb-9755c8c39827.png">
