### ISSUE TITLE
Styleguide component: Queues

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1092]
Copy:

Queues (all cap)

Another common layout in Caseflow is the Queue, a list of work items for a user to take action on. Queues are shown in the standard App Canvas and are shown in tables.

A user picks the next item to work on by using an button at the top of their queue. By using this button, we can dynamically re-assign work items to other users if the user takes too long to work on an item. Next to it, we display the total number of items left in their queue for reference. When there are no more work items left to work on at any given time, the button is disabled and the text next to the button tells the user as much.

A user may have multiple tables with varying titles on this page such as work items they’ve held and historical items they’ve worked on. Some of these tables contain a primary action for each item within them such as “Establish »”. Others may simply indicate status. 

The columns for these table vary by use case and should be researched to find the most useful and relevant information to display. 

At the top right of a queue, we show a “View Dashboard” link that lets the user see their team’s dashboard.

Coaches have a similar view as Caseworkers but they can see the status of all appeals in a queue and who is working on which ones at any given time. This queue also flags cases that have been escalated to the coach for assistance. The coach has the ability to assign and re-assign appeals from this view giving them more power than an average user.

![image](https://cloud.githubusercontent.com/assets/13420618/23623839/85c7d6de-0271-11e7-9034-96609419c121.png)

Note: Queues are tables with Actions right-aligned on the far right, and some have search boxes.

**Comment by gnakm** [comment]
Closing this because we will add the above mock as an example as a table in the table section.

**Comment by nikitarockz** [comment]
@gnakm So, was this issue actually implement by the engineering team?

**Comment by gnakm** [comment]
@nikitarockz I chatted with Kavi and we decided to take this component out of the styleguide and have it under the tables section instead #1076 

@mmlumba @slj I should have checked with you guys first to make sure you didn't start on this.
