### ISSUE TITLE
Create landing page for all Board team queues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10929]
We've created quite a few team queues across the Board. Some employees at BVA need insight into cases in all team queues. What if we created a landing page for all team queues, so "super admins" (like JW, DVCs, DVC admins) could easily navigate to see cases assigned to each team?

We could just add users to each of these organizations. The downside is that the "Switch views" toggle would become very heavy.

**Comment by araposo-tistatech** [comment]
@araposo-tistatech Double check if this feature is something that BVA would still like implemented.
