### ISSUE TITLE
Allow users to navigate from Caseflow products to eFolder express

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10927]
VSOs and private bar attorneys have access to eFolder Express, Queue, and Hearings. Let's make it easier for them to navigate between the apps.

## AC
- Users can use the Switch product toggle to navigate from Caseflow products, like Queue and Hearings, to eFolder express.

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||||
2 | |||||||||
3 | 
5 | 
8 |  
```
Could be a simple addition after a conditional, very straightforward. Unsure what information we have about the user on the front end.
