### ISSUE TITLE
Duplicate Tasks

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#10934]
We've seen this error for several different kinds of tasks:
- [ ] [ChangeHearingDispositionTask](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5237)
- [ ] [PrivacyActTask](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4902/)

**Comment by pshahVA** [comment]
@sharonwarner, does this still happen?  If we can't replicate it, can we close it?
