### ISSUE TITLE
Allow users to search for claim number OR SSN

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10930]
Right now, we only allow users to search for Veterans in Veteran Case Search using the Veteran's SSN. Some Veterans have SSNs, some have claim numbers, and some have both. We should allow users to use any of these numbers to search for Veterans, to have better feature parity with VACOLS.

## AC
- Users can search for Veterans by claims file number, if that claims file number is different than their SSN

**Comment by lomaxap** [comment]
mostly an investigation ticket for now. Create a tech spec detailing how to implement search across multiple ids

**Comment by pkarman** [comment]
I would love to see a `VeteranFinder` service or query class that takes a SSN or file number of any flavor and returns an array of `Veteran` objects that matches. That would be very useful in several contexts. It would wrap around `Veteran.find_by_file_number_or_ssn` https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/veteran.rb#L223 and then double-checks that we might have multiple Veteran records with the same `participant_id`.

See also #10903 and #9298

**Comment by ferristseng** [comment]
Still need to work on the front-end component of this, so reopened it
