### ISSUE TITLE
Styleguide component | Splash page Messages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1093]
As a developer and designer, I want to understand how messages are used and what types of messages we are using across all cashflow apps to clearly communicate task completion and errors. 

# Acceptance Criteria
1. Verify that there is a title for Messages
1. Verify that the below copy is beneath the title Messages
1. Verify that there is Messages in the side nav of the style guide
1. Verify that clicking on Messages in the side nav takes you to the section
1. Verify that there are subsections for the types of messages in this order:

### Alert messages - #1096

# Copy

Messages are a frequent layout used in Caseflow. These messages are shown when the user has completed a task, when there is an error, and to indicate status. 

All messages are shown in the standard App Canvas. The messages contain a `heading 1`, whose colors vary based on context, and `lead` follow-up text. The follow up text often contains context and instructions on what the user can do next.

**Comment by mmlumba** [comment]
Original AC for 5:
1. Verify that there are subsections for the types of messages in this order:

## Messages


### Success messages - #1094


### Alert messages - #1096


### Status messages - #1097

**Comment by astewarttistatech** [comment]
**PASSED**

Verified: Dev
Browsers: FF and Chrome

Steps to Validate: 
1. Access the Style Guide
2. Verify that each section of messages match the tickets found in the AC

Screenshots: 
![sgmessages](https://cloud.githubusercontent.com/assets/23038505/25661100/1fdfcfae-2fdd-11e7-8fa0-b21d91a64a61.gif)
