### ISSUE TITLE
AttorneyJudgeCheckoutError: Diagnostic code is not included in the list

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#10948]
Validation failed: Benefit type is not included in the list

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4971/

**Comment by pkarman** [comment]
possibly connected to #10945

**Comment by pkarman** [comment]
it's the `unidentified` benefit type that's the problem. We should be requiring those issues to be identified first. See #10609

**Comment by pkarman** [comment]
There have not been any `unidentified` errors since 6/7 when we cleaned up #10609 

Instead we see `Diagnostic code is not included in the list` now. Different problem, same exception class.

**Comment by kevmo** [comment]
What is the ask here? The ask is Investigate the issue and stop sending Sentry alerts to Slack -- do this validation elsewhere (so don't do it on backend).  If we find out diagnostic code isn't needed, catch this error instead of sending it to Sentry.

**Comment by kevmo** [comment]
# Estimation: 3

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||
3 | |||||||||||||
5 | 
8 | 
```

Why is this a 3?  Fair amount of investigation - where/why it's happening + intended result.

**Comment by pkarman** [comment]
This is happening again. The error is that a nil `diagnostic_code` is being sent from the front-end.

![Screen Shot 2020-03-31 at 3 40 30 PM](https://user-images.githubusercontent.com/1205061/78073268-2d2cf180-7366-11ea-9154-effc9e1d5df1.png)

See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9479/events/1eefecb7390147b590f3fd1dbe2fede6/

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9479

**Comment by jcq** [comment]
Saw another alert:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9479/

Wonder if there's a chance the user somehow hadn't received the new version of the app...?

**Comment by hschallhorn** [comment]
Looks like 2 were actual non existent diagnostic codes, 7725 and 7630.

**Comment by ajspotts** [comment]
Currently awaiting feedback on user testing to determine whether or not we need to continue to maintain the list of diagnostic code [descriptions](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json).  If we are able to remove these it will prevent a fairly significant lift to prevent further instances of this error. 

Slack convo detailing thought processes [here](https://dsva.slack.com/archives/CQCUMFA0H/p1595431749007500)

**Comment by ajspotts** [comment]
Closing in favor of the following issues which will resolve the error:
#14870
#14871 
#14872
