### ISSUE TITLE
Styleguide component | Messages Splash page  - Success Messages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1094]
As a developer and designer, I want clear and consistent actions to implement success messages across our apps so users can confirm key tasks have been completed correctly. 

## Acceptance Criteria 

1.  Verify that in the living style guide `Success Messages` appears first under the Message section in the style guide. 
1. Verify that the correct description appears below `Success Messages` (see copy section) 
1. Verify that the components appears below the copy (see mocks)
1. Verify that clicking on Messages in the side navigation takes you to `Messages`, and `Success Messages` component appears under `Messages`
1. Verify that the max width of the text in the check list should be 400px wide. If the text exceeds the max width, it should go on a second line and indent so that it is aligned with the text. 

## Mockup

Make sure you are logged onto Invision before clicking the link

[Invision Craft Link - Success Messages](https://projects.invisionapp.com/d/main#/console/10592592/225441382/inspect)

<img width="465" alt="screen shot 2017-03-24 at 4 30 04 pm" src="https://cloud.githubusercontent.com/assets/23316107/24312490/3d0dc84e-10af-11e7-8372-173f1041e8f5.png">

When text length exceeds 400px width
![image](https://cloud.githubusercontent.com/assets/13420618/25146728/fb2134c8-2442-11e7-9787-1b441e018973.png)

## Copy

**Title**

Success Messages

**Description**

Success messages are shown when the user has successfully completed the intended task of the application. The title is green, and these messages contain a checklist confirming the tasks the user has completed and displays actions performed by Caseflow in the background, such as automatically sending a letter or changing the location of a claim.

## Related Issues

#1093: Style Guide Component | Messages

**Comment by Chingujo** [comment]
@gnakm Updated the AC's copy, and added a link

**Comment by mmlumba** [comment]
Original AC for 4 and 5:
Verify that Success Messages has to be under Messages in styleguide side nav
Verify that clicking on Success Messages in side nav takes you to the right section

**Comment by astewarttistatech** [comment]
@mmlumba is this supposed to have both images (from the mocks)?

Current View:
<img width="1026" alt="screen shot 2017-04-28 at 10 41 54 am" src="https://cloud.githubusercontent.com/assets/23038505/25533674/65fe295e-2bff-11e7-83dc-1f7ec4edc8e4.png">
