### ISSUE TITLE
Investigate that Schedulable Manilla Veterans are unblocked

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#10957]
Verify that hearing coordinators can remove "verify address task" to unblock manilla veterans to be scheduled.

**Comment by carodew** [comment]
Curious on the context of this one, is this a research question (aka, should this functionality exist?) or is this checking in Caseflow to see if we've built this correctly? also tagging @pshahVA for awareness.

**Comment by carodew** [comment]
ah .. nevermind! I accidentally clicked on this card in the define column thinking I was in the design backlog. Carry on, nothing to see here.

**Comment by pshahVA** [comment]
I think we can close this.  I believe Manila was already scheduled.
