### ISSUE TITLE
Queue | Add Decisions Flow | Attorney | Highlight unidentified appeal request issues in Case Details

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10950]
## Background
Appeals may have "unidentified" issues associated. These happen when Caseflow Intake users aren't sure what the issue on appeal is. These require further investigation to turn into rating or nonrating issues in order to go through the appeals process. (Note: most Board employees who work appeals do not understand rating vs. non-rating nuances) 

We need to draw attention to them in Caseflow so that the relevant users - attorneys - can act on them before they get further in the queue process. We think these unidentified issues should be corrected before attorneys check draft decision tasks out to their judges. 

The desired behavior is for request issues to be correct before attorneys add decision issues to them. So, we think attorneys should (1) be alerted to these unidentified issues in Case Details so they can (2) follow the "Correct Issues" link and correct the request issues before they (3) start their check out flow. 

#### Current state
If attorneys don't correct an "unidentified issue" in the "Correct issues" flow prior to checkout, they receive an error when they don't remove this issue or add a decision to it. We should be more specific and tell attorneys exactly what they should do with unidentified issues.

![image](https://user-images.githubusercontent.com/40216950/53251432-a13c9680-368a-11e9-8ecc-dcca6a081b7d.png)

## Stories/requirements
- If there is an unidentified request issue, add styling to the issue in the Issues section of Case Details to highlight this to the user
- Display additional instructional copy near unidentified issues so that attorneys are aware that they should use the "Correct issues" flow to correct them. We could use the (i) indicator or hover over pattern we already use to explain what attorneys need to do.  
   - Draft copy: "This request issue was unidentifiable during the intake process. Please review the appellant's documentation, follow the Correct Issues link, and ensure the correct request issue was chosen for this case. You may remove this unidentified issue and add the correct one on the Add/Remove issues page."
- Block attorneys from starting the checkout process until they correct all "unidentified issues" on the case. 
    - Option 1: We could display a modal or error message when they click "Send to judge" in the Actions dropdown of Currently Active Tasks component of Case Details and communicate to them that they must first update all unidentified issues. 
   - Option 2: We could disable the "Send to judge" option and show the error message in the Issues component of Case Details. (LP's preferred option)

## Resources
See https://dsva.slack.com/archives/C754H751T/p1559241257009600
Related issue where we explored unidentified and ineligible issues - #9604

**Comment by rutvigupta-design** [comment]
Tagging @geronimoramos for visibility

**Comment by msj0nes** [comment]
Clarifying

This issue highlighted by Peter above is happening for attorneys on the 'Add Decision' workflow page when 'Decision Ready for Review' task is selected on the Case Details page. 

![image](https://user-images.githubusercontent.com/41164406/78068759-facfc400-7366-11ea-87e1-97557865ddbc.png)

**Comment by hschallhorn** [comment]
Queue related places this would appear:
A. In case details
B. Judge and attorney checkout on the "Review Dispositions" page. 

1. Log in as a judge or an attorney and go to their queue
1. Click on a legacy or ama appeal and scroll down to "Issues"
![Screen Shot 2020-07-08 at 3 47 05 PM](https://user-images.githubusercontent.com/45575454/86963310-4f3aca80-c132-11ea-874a-40acd8cdab8a.png)
(Blank "Benefit type:")
1. Select "Ready for dispatch"
1. Click through the special issues page
![Screen Shot 2020-07-08 at 3 47 56 PM](https://user-images.githubusercontent.com/45575454/86963374-6c6f9900-c132-11ea-83cd-a24408f39058.png)
(again, blank benefit type)

We DO validate this when the user adds a decision, but only for ama appeals
![Screen Shot 2020-07-08 at 3 49 18 PM](https://user-images.githubusercontent.com/45575454/86963503-a2ad1880-c132-11ea-8c10-02e7ca80e9d9.png)
