### ISSUE TITLE
Styleguide component | Messages Splash page - Alert Messages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1096]
As a developer and designer, I want clear and consistent actions to create alert messages across our apps so users can know when tasks were not done correctly, when data is destroyed from canceling a claim, and so forth. 

## Acceptance Criteria 
1.  Verify that in the living style guide that a section called `Alert Messages`appears second after Success Messages in the style guide. 
1. Verify that the correct description appears below `Alert Messages` (see copy section) 
1. Verify that the components appears below the copy (see mocks)
1. Verify that clicking on Messages in the side navigation takes you to `Messages`, and `Alert Messages` component appears under `Messages`

## Mockup

Make sure you are logged into Invision before clicking Invision 

[Invision Craft Link - Alert Message](https://projects.invisionapp.com/d/main#/console/10592592/225525213/inspect)

![image](https://cloud.githubusercontent.com/assets/13420618/24159823/944ae860-0e36-11e7-88c1-30660f9aeff2.png)

## Copy

**Title**

Alert Messages

**Description**

Alert messages are often shown when the user has destroyed data by canceling their work. These messages have red titles to reinforce that the user did not complete the intended task of the application,  a brief explanation of what happened, and next steps.

## Related Issues
#1093 - Style Guide Component | Messages

**Comment by Chingujo** [comment]
@gina 

Updated AC, added mock, craft link, and copy labels

**Comment by lakohl** [comment]
Hey guys, we might want to differentiate between Alert Banners Messages  (see below) 
<img width="740" alt="screen shot 2017-03-24 at 5 53 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/24314999/e64130d0-10ba-11e7-94e0-a29f94e128e2.png">
and other kinds of alerts?

**Comment by Chingujo** [comment]
@lakohl 

Yup =D. We have a separate issue for the above

**Comment by mmlumba** [comment]
@Chingujo What is the ticket for the alert banners? Is it "ready for dev"?

**Comment by Chingujo** [comment]
@mmlumba 

#1084 is the issue for banner alerts. It is in progress and not ready for dev. However, the styling for alerts should be straight from USWDS

**Comment by mmlumba** [comment]
Original AC for 4 and 5:
1. Verify that `Alert Messages` appears below messages in the styleguide side nav
1. Verify that clicking on `Alert Messages` in side nav takes you to the right section

**Comment by astewarttistatech** [comment]
@mmlumba  Based off the AC above, there isn't an "Alert Messages" indicator in the side nav. 

Please see the current functionality and tell me if this is what you meant. 


![sgalerts](https://cloud.githubusercontent.com/assets/23038505/25622495/963caad4-2f22-11e7-93aa-dea250e18153.gif)

**Comment by mmlumba** [comment]
@astewarttistatech The `Alert Messages` indicator isn't in the side nav, its under the main section "Messages"

**Comment by astewarttistatech** [comment]
Based on the thread in this ticket, 

**PASSED**

Validated in: Dev
Browsers: FF and Chrome

Steps to Validate: 
1. Go to the living style guide 
2. Validate the Alert Messages section under the Messages section against the AC listed above

Screenshots: 
see above
