### ISSUE TITLE
Route va.gov alerts in Slack

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10965]
Right now the va_dot_gov_service.rb failures show up unrouted in the #appeals-app-alerts channel. We should

* [ ] Name the exceptions better
* [x] Route them in Slack better

**Comment by nemodjuric** [comment]
Fix to route them to appeals-hearings was added. However, they still need to be named better. The suggestion is to catch JSON::ParserError and throw either VaDotGovServerError or a new VaDotGovTimeoutError. It's left up to hearings team to decide.

**Comment by pkarman** [comment]
@lomaxap is the work you're doing in #11479 related to this?

**Comment by lomaxap** [comment]
incidentally, yes. PR will catch JSONParser errors and `VaDotGovServerError`s are sent for all 5XXs. I haven't changed anything around `HTTPClient::ReceiveTimeoutError`s since that one is descriptive to me.
