### ISSUE TITLE
Fix Motion to Vacate task

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10974]
Litigation Support assigned the Motion to Vacate mail task to "unidentified". Let's investigate where this task now is, and move it back to being assigned to Litigation Support organization.

https://appeals.cf.ds.va.gov/queue/appeals/de87df4e-c8c9-4975-9c47-c862a78e42db

From Lit Support user, answering my question about how they did this:
>  As best I can remember, we did it via assign to team, thinking we would get a list of OAO team members, then unidentified, thinking we could write someone in.  Right now, Mr. Carlson’s vacate task is assigned to “Unidentified” but the record is charged to Nina instead of post-decision.

**Comment by pkarman** [comment]
the task assigned to the “Unidentified” org is a “GenericTask” not specific to Motion to Vacate. It has instructions of “Testing vacate to VLJ” — do we really want to re-assign it? or just cancel it?

**Comment by laurjpeterson** [comment]
I think we want to cancel it! Then, the Motion to Vacate task would return to the Lit Support queue

**Comment by pkarman** [comment]
I cancelled it. However, I think we also want to re-assign it, because we want to be able to delete the "Unidentified" organization completely, and this is the only task remaining on that org.

What org could I re-assign the cancelled task to? The Lit Support org?

**Comment by laurjpeterson** [comment]
Yes, Litigation Support org!

**Comment by pkarman** [comment]
GenericTask id: 216598 assigned to LitigationSupport id: 213
