### ISSUE TITLE
Change which tasks we cancel when appeals are withdrawn

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10973]
Currently, we cancel all open tasks on an appeal when an appeal is withdrawn (all issues are withdrawn). We need to change this logic based on what we've learned about distributing withdrawn appeals to judges for decision. 

## AC
- When all request issues on an appeal are withdrawn, cancel all open tasks except:
   - `RootTask`
   - `TrackVeteranTask`
- Add `DistributionTask` with status assigned

**Comment by monfresh** [comment]
Is there a particular status we want for the `RootTask` and `TrackVeteranTask`, or leave it at the last status it had?

**Comment by monfresh** [comment]
@laurjpeterson I came across one unresolved scenario while working on this. If an appeal has a mixture of eligible and ineligible request issues, and all the eligible ones are withdrawn but the ineligible ones are not changed, the cancellation of active tasks will not be triggered. Is this correct behavior? 

We had discussed that ineligible request issues shouldn't count towards the total. That is, if an appeal has both eligible and ineligible request issues, as long as all the eligible ones are withdrawn, we would consider the appeal withdrawn. Sally was suggesting we go further and define a withdrawn appeal as one that has one or more withdrawn request issues AND the remaining request issues are all closed for whatever reason, not just ineligibility. Is this correct?

**Comment by laurjpeterson** [comment]
> If an appeal has a mixture of eligible and ineligible request issues, and all the eligible ones are withdrawn but the ineligible ones are not changed, the cancellation of active tasks will not be triggered. Is this correct behavior?
I think this is incorrect. I think that if all eligible issues are withdrawn, and the only issues left on appeal are ineligible for appeal, the entire appeal is withdrawn. I'll double check with LRP to confirm what should happen if the only issues left on appeal are ineligible. 

> Sally was suggesting we go further and define a withdrawn appeal as one that has one or more withdrawn request issues AND the remaining request issues are all closed for whatever reason, not just ineligibility. Is this correct?
Can you remind me the reasons for request issues being closed? I know there are:
- withdrawn
- removed
- stayed (to be built)

which ones am i missing?

**Comment by pkarman** [comment]
Valid "closed status" values are listed here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issue.rb#L40

**Comment by laurjpeterson** [comment]
> Sally was suggesting we go further and define a withdrawn appeal as one that has one or more withdrawn request issues AND the remaining request issues are all closed for whatever reason, not just ineligibility. Is this correct?
Yes, I think this is correct. Especially because either way, these cases are going to a judge/attorney for a decision.

**Comment by laurjpeterson** [comment]
Correcting my earlier comment:

> If an appeal has a mixture of eligible and ineligible request issues, and all the eligible ones are withdrawn but the ineligible ones are not changed, the cancellation of active tasks will not be triggered. Is this correct behavior?

Incorrect. If all issues are withdrawn or ineligible, the triggering of cancelling tasks CAN continue. This is because the case needs to go to the judge for decision for the withdrawn issues. The judge will kind of ignore the ineligible issues (they are hidden in Caseflow, though they could see the ineligible issues on the NOD). It's up to the judge to add mention of the ineligible issues in the decision. 

> Sally was suggesting we go further and define a withdrawn appeal as one that has one or more withdrawn request issues AND the remaining request issues are all closed for whatever reason, not just ineligibility. Is this correct?

I just spoke with Rachel. This is incorrect. The only situation where the entire appeal is considered withdrawn is if all issues are withdrawn.

**Comment by monfresh** [comment]
I think that last part might require more changes. From what I can tell, we currently only display [active or ineligible or withdrawn](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/decision_review.rb#L317-L321) request issues on the edit appeal page, which means issues that are closed for other reasons cannot be withdrawn from the UI currently. Am I misunderstanding? Is there another place in the app where a closed request issue can be withdrawn?
