### ISSUE TITLE
Styleguide component | Messages Splash page - Status messages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1097]
As a developer and designer, I want clear and and consistent way to show the Status of our apps to our users. 

## Acceptance Criteria 

1.  Verify that in the living style guide there is a section called `Status Messages`that appears last in the Messages section of the style guide. 
1. Verify that the correct description appears below `Status Messages`(see copy section) 
1. Verify that the components appears below the copy (see mocks)
1. Verify that clicking on Messages in the side navigation takes you to `Messages`, and `Status Messages` component appears under `Messages`

**_NOTE: Invision link has a different color from #323a45. Make sure it is #323a45, `dark-gray`_**

## Mockup

_Make sure you are logged into Invision before clicking link_

**Status Messages**

[Invision Craft Link - Status Message](https://projects.invisionapp.com/d/main#/console/10592592/225525577/inspect)

![image](https://cloud.githubusercontent.com/assets/13420618/24159951/e813ba30-0e36-11e7-83d2-039b3d86c3ff.png)

## Copy

**Title:** 

Status messages

**Description:** 

Status messages are shown when Caseflow encounters an error such as 500 or 400 http error codes. They are also shown when a user doesn’t have access to view a particular page or application. These messages are more neutral with a `dark-grey`title, an explanation of what is going on, and next steps the user can take. 

## Related Issues
#1093 Styleguide component | Messages

**Comment by Chingujo** [comment]
@gnakm 

Updated AC, added craft link and mock image, copy labels

**Comment by mmlumba** [comment]
Original AC for 4 and 5:
1. Verify that `Status Messages` appears below the Messages in styleguide side nav
1. Verify that clicking on `Status Messages` in side nav takes you to the write section

**Comment by astewarttistatech** [comment]
Color isn't the same. @mmlumba 

Current view:
<img width="991" alt="screen shot 2017-05-02 at 9 35 27 am" src="https://cloud.githubusercontent.com/assets/23038505/25619984/c804c982-2f1a-11e7-87ca-af69a363b920.png">

**Comment by astewarttistatech** [comment]
Based on @gnakm 's change to AC, referring to the screenshot above.

**PASSED**

Validated in: Dev
Browsers: Chrome and FF

Steps to Validate: 
1. Go to the living style guide
2. Validate the Message splash page and copy for Status Messages. 

Screenshots: 
see above.
