### ISSUE TITLE
Fix Pulac-Cerullo in Case Timeline

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10975]
Feedback from Lit Support users
> We were able to test and do the Pulac/Cerullo task, but the completed task is then reflected at the bottom in the case timeline in non-chronological order.  It’s showing before the decision dispatch date, even though it is a post-decisional task.  Also, because it’s in the timeline instead of in the task tree, someone else reviewing the motion record (like supervisory senior counsel) will need to scroll down to the bottom to confirm the attorney checked CAVC for filing there.

## AC
- Pulac Cerullo task shows in Case Timeline in chronological order, above the Dispatched from BVA date.

**Comment by youngfreezyVA** [comment]
<img width="1230" alt="Screen Shot 2019-06-05 at 3 44 59 PM" src="https://user-images.githubusercontent.com/46791771/58985260-e9e70e00-87a8-11e9-95e3-9c1101af209d.png">
to confirm, should the "Dispatch from BVA pending" and "PulacCreulloTask Completed" timeline items be swapped? @laurjpeterson @aroltsch I'm not sure if this screenshot reproduces the issue... a screenshot or steps to reproduce would be helpful. Here's what I did:

- logged in as jolly postman, added mail tasks
- found them in lit support users un assigned queue
- selected "notify ogc of pulac curello" for all these tasks
- logged in as kate sosna, and marked all the tasks as complete

then I saw this on the case timeline:
<img width="1230" alt="Screen Shot 2019-06-05 at 3 54 15 PM" src="https://user-images.githubusercontent.com/46791771/58985838-3bdc6380-87aa-11e9-9040-4404c0d86979.png">


-

**Comment by aroltsch** [comment]
This is the case in question: https://appeals.cf.ds.va.gov/queue/appeals/de87df4e-c8c9-4975-9c47-c862a78e42db. It seems as Dispatched from BVA is not showing up in the right chronological order.

![image](https://user-images.githubusercontent.com/3811786/59111375-e5d50080-890e-11e9-863a-95b5e92ff351.png)

**Comment by aroltsch** [comment]
@youngfreezy I think you should try to reproduce this locally first. You need to figure out what determines "Dispatched from BVA" and where this date is coming from.

**Comment by youngfreezyVA** [comment]
ok, I know why this is happening. I made a change a couple of months ago to sort the task list. the decision date is always hardcoded to appear above the task list, so the task list is sorted correctly, but in the decision date isn't since it isn't part of that list. looks like that is incorrect. I'll add the decision date to the task list so that it will be sorted correctly.
