### ISSUE TITLE
Cannot read property 'isLegacyAppeal' of undefined in CaseDetailsView

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#10980]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3630/

We've seen this error previously in another section of code #8229

**Comment by hschallhorn** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6456/

**Comment by kevmo** [comment]
Probably need to check on how Redux is updating, then make the fix from there.

**Comment by kevmo** [comment]
# Estimation: 2

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||
2 | ||||||||
3 | ||||
5 | 
8 | 
```

Why could this be a 1? The most immediate cause is clear - calling a method on a null object!

Why could this be a 3? Could be hard to replicate - what is the order of events causing this?  Tracking and replicating could elevate this to a 3!
