### ISSUE TITLE
Make Automatic Case Distribution code more resilient against 0 values

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#10996]
`DocketCoordinator#interpolated_minimum_direct_review_proportion` crashes if `nonpriority_decisions_per_year` is zero. It's probably not likely that there will be zero nonpriority decisions within a year, but it might still be worth it to make the code more resilient.

**Comment by monfresh** [comment]
Similarly, other parts of the code crash if there aren't any legacy appeals to distribute, which is more likely to happen in the future.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | |||||
3 | ||||||
5 | 
8 | 
```


Why 1?

 - handle zero value in a couple places, add a test case?

Why 2?


Why 3?
 - Unfamiliarity with ACD
 - Investigate why zero and handling it better
 
Why 5?
