### ISSUE TITLE
Styleguide component | Dashboard

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1099]
As a user, I want to be able to track the performance of an application. I want to be able to view it hourly, daily, weekly, and monthly. 

As a developer and designer, I want clear and consistent guidelines for how the dashboard page for our apps should look like and be implemented.

## Acceptance Criteria

- Verify that that title of the Dashboard should always be [App name] Dashboard with the appropriate logo on the left
- Verify that the copy below follows the title
- Verify that the source code follows eFolder Express
- Verify that each table has graphs related to it's tab section
- Verify that all titles are left-aligned and aligned with all graphs, tables and tabs
- Verify that the title is in the new `h1` (34 px)
- Verify that other subtitles are in the new `h3` (19px)
- Verify that the spacing between rows of graphs match mock up

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25279580/ddb722ba-2674-11e7-87c5-f624dcf977dd.png)

## Copy

Each Caseflow application has a business dashboard to help the team and our stakeholders track the performance of the application. Metrics specific to the application are determined by the team before the dashboard is built. These metrics often include basic usage numbers, time to complete task metrics, success rates, and more. 

Dashboards are featured on the standard App Canvas. Data is broken up by tabs so the user can view data by hours, days, weeks, or months.

Each data point has includes the metric title and quantity for the selected time period. It also has a chart displaying historical data for that same data point.  

Users can hover over historical points on the chart to show the data point for that specific time.

**Comment by gnakm** [comment]
Please ignore the graphs. They are inaccurate. 

![dash](https://cloud.githubusercontent.com/assets/13420618/23722637/255a87c0-0414-11e7-9f4c-c40c12a44ea1.png)

**Comment by mmlumba** [comment]
Original AC for 1.2:
Rows of graphs for Activities, Searches, Timing, Errors

**Comment by astewarttistatech** [comment]
@mmlumba The current UI doesn't match the mocks. Currently there is no stats on in the Dashboard section of the style guide. Could you let me know if the current view wasn't supposed to include the mock, referenced above?

Current view: 
<img width="1153" alt="screen shot 2017-05-08 at 11 37 02 pm" src="https://cloud.githubusercontent.com/assets/23038505/25834663/78db408e-3447-11e7-9736-371080bf3b72.png">

**Comment by mmlumba** [comment]
@astewarttistatech The dashboard section of the style guide just contains the description, and the "view source code" button just links to the stats page of eFolder express. The mock just shows what the actual stats pages should look like in terms of header pixel sizes (ie `/dispatch/stats`, `/certification/stats`, `/stats` on eFolder)

**Comment by astewarttistatech** [comment]
Based on above comment, this issue has 

**PASSED**

Validated in: Preprod
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living Style Guide. 
2. Validate the section for "Dashboard" 
3. Validate copy against what is provided in the AC

Screenshot: 
see above
