### ISSUE TITLE
ActiveRecord::StaleObjectError: Attempted to update a stale object: EstablishClaim.

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#10995]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4485/events/360319/

`ActiveRecord::StaleObjectError app/models/dispatch/task.rb in cancel!`

Possibly related to #1466 and #1559. 

Error seen twice this year. Leaving idle, pending more alerts.

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9392
