### ISSUE TITLE
Other explanation box appears far away from other checkbox

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#11]
![image](https://cloud.githubusercontent.com/assets/950486/9045115/15ee085c-39ef-11e5-91e6-42b04af82ccc.png)

Environment:
- IE9

Steps to recreate:

1. Go to Caseflow base URL
1. Enter a BFKEY that for a veteran with missing VBMS details
1. Click Continue twice
1. On question 13, select the checkbox for other

Desired outcome:

Other textbox appears directly under or beside the Other checkbox.

**Comment by plusjeff** [comment]
Awaiting review from @KHarshawat
