### ISSUE TITLE
Make footer sticky

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#110]
The footer of caseflow should stick to the bottom of the viewport or bottom of the content (whichever is lower) rather than always flowing directly under the content. See the attached mock for an example (ignore visual design changes for now).

![04_congratulations](https://cloud.githubusercontent.com/assets/6335546/10892589/59bf36ee-8172-11e5-88a4-aad497bacaa4.png)

**Comment by plusjeff** [comment]
Let's do this after (or as a part of) #106

**Comment by webinista** [comment]
Screenshots of various pages attached.

![stickyfooter-start](https://cloud.githubusercontent.com/assets/354277/12124679/c561a372-b3b4-11e5-8655-7c771b1688e4.png)
![stickyfooter-login](https://cloud.githubusercontent.com/assets/354277/12124677/c56115e2-b3b4-11e5-8976-4460544a7be9.png)
![stickyfooter-form8](https://cloud.githubusercontent.com/assets/354277/12124678/c5616416-b3b4-11e5-88ef-8635e1472428.png)
![stickyfooter404](https://cloud.githubusercontent.com/assets/354277/12124680/c565a5a8-b3b4-11e5-918f-95fd4a77ac53.png)

**Comment by KHarshawat** [comment]
This is actually a mock bug ... not actually a problem in production. Closing issue.
