### ISSUE TITLE
EP Confirmation |  Partial & Remands SIC | Update checklist order

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1100]
As a Product Owner, I would like the checklist updated on the `EP Confirmation` (Assigned/Created flavors) page for Partial Grants and Remands with Special Issues for whom we create an EP so that the list reflects the proper ordering.

# Acceptance Criteria
1. Verify that the checkmarks list the following items as completed:
    >Reviewed decision
    >Established EP
    >Updated VACOLS
    >Added VBMS Note

1. Verify the items are listed in the following order:
    >Reviewed decision
    >Established EP
    >Updated VACOLS
    >Added VBMS Note

## Mocks

**_View - EP Confirmation - Current_**
<img width="688" alt="screen shot 2017-03-06 at 2 36 28 pm" src="https://cloud.githubusercontent.com/assets/4975959/23626288/53eddbb4-027a-11e7-8cf9-73326989fcea.png">

**_View - EP Confirmation - Desired_**
<img width="637" alt="screen shot 2017-03-06 at 2 34 38 pm" src="https://cloud.githubusercontent.com/assets/4975959/23626264/3ff45c3c-027a-11e7-975a-5052a49bc035.png">

# Related Stories
n/a

**Comment by shanear** [comment]
This is a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/1144. Closing
