### ISSUE TITLE
[WIP] Styleguide component: Short Text Input

### ISSUE THREAD

**Issue by KHarshawat-gov** [department-of-veterans-affairs/caseflow#1101]
Sometimes we ask the user to input a very minimal amount of text like the number of employees who are working. Using the normal width of a text input would be too much so we use a short text input. 

![image](https://cloud.githubusercontent.com/assets/25437276/23626380/aa25869e-027a-11e7-9f40-4e1843bce5f6.png)

_Note: Perhaps the width should be adjustable as a part of the react component? @shanear thoughts?_

**Comment by gnakm** [comment]
@shanear Did you get a chance to look at this?

**Comment by gnakm** [comment]
Closing this because we solved this problem with number input inline with text label for dispatch.
