### ISSUE TITLE
Fix 'VACOLS Hearing Record Not Found' Error Routing

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11020]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4909/

This error should be routing to the proper place for Hearings errors. Currently appears in general application alerts.

**Comment by hschallhorn** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5883/ as well?

**Comment by pkarman** [comment]
@hschallhorn since this issue is closed maybe a new issue or just prep a PR yourself?
