### ISSUE TITLE
Styleguide component: Modal copy

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1102]
Edit copy: 

Modals are 490 pixels in width with 30px padding around the border and contain the following: a title, explanation text, a divider, and action buttons. There are modal-specific classes that must be included in your modal (see below code snippets). add: **Whenever possible, use a close link as the left action.**

**Comment by kierachell** [comment]
**PASSED**
looks good
![screenshot_2017-03-08_14-50-19](https://cloud.githubusercontent.com/assets/18075411/23721065/a038e398-040e-11e7-807b-b177dd689719.png)


## bonus feature:
![screenshot_2017-03-08_14-41-23](https://cloud.githubusercontent.com/assets/18075411/23721082/aef6a384-040e-11e7-92e8-8dbf775f7f08.png)
