### ISSUE TITLE
Failed to execute removeChild in Reader

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11023]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3117/events/360708

There's no stack trace unfortunately. Looks like it might be happening after a PDF document is being cleared?

**Comment by jcq** [comment]
Looks like this has happened a couple of times in the past two days with two separate users:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3117/events/

**Comment by yoomlam** [comment]
https://dsva.slack.com/archives/CANGG9BMK/p1597327489020600

**Comment by yoomlam** [comment]
Happens about weekly: https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/3117/events/
