### ISSUE TITLE
HTTPClient::ReceiveTimeoutError in va_dot_gov_service.rb:send_va_dot_gov_request

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11029]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5048/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5050/

**Comment by lomky** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5047/

**Comment by lomky** [comment]
Similiar: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5223/

**Comment by alisan16** [comment]
This was last seen 10 months ago. Closing out
