### ISSUE TITLE
Styleguide component: Modal bug

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1103]
The modal should close when user clicks outside of box. Currently, it remains open. 

![image](https://cloud.githubusercontent.com/assets/13420618/23626795/1a1746ee-027c-11e7-9f51-a57677a74f2b.png)

**Comment by kierachell** [comment]
There's an old #680 issue for this.

**Comment by gnakm** [comment]
I am going to close this issue since there is already an issue for this. Also, I think the x- close icon should be enough to get users to get out of the modal.
