### ISSUE TITLE
VBMS MissingVeteranIdentifier for FetchDocumentForReaderUserJob

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11035]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5274/events/361143/

Looks like this could be happening because the appeal ID that's recorded in the sentry event does not exist. Seeing a `nil` file number in the VBMS request, which is probably why it's getting an error back.

**Comment by monfresh** [comment]
This was fixed in #11326
