### ISSUE TITLE
Upstream Error | Unable to retrieve veteran information

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11042]
ShareException thrown in findRatingData. Claim not established. Unable to retrieve Veteran information.

See Supplemental Claim 10562

Thread started in https://dsva.slack.com/archives/CK466V65V/p1559850750009700

**Comment by leikkisa** [comment]
This was a veteran doing an intake for himself.  The veteran should have received a sensitivity error on searching for the veteran, I am looking into why that might not have happened.

For SC 10562, there was only one request issue on it, and the description was "blah".  I have decided to remove the request issue and cancel the job.

**Comment by leikkisa** [comment]
This was caused because we set a parameter to determine accessibility via veteran.find_by_file_number(ssn).nil?, which works for this veteran. The other option checks claimants.find_flashes(ssn).nil? which would have returned the correct error.

**Comment by leikkisa** [comment]
Re-purposing this ticket to be an upstream error ticket for the "Unable to retrieve  veteran information" error, because it has some useful context.
