### ISSUE TITLE
Caseflow access for private attorneys and claims agents

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11050]
Adding a ticket as a placeholder for this until we know more information.

https://dsva.slack.com/archives/CFBLH2LR4/p1559852446026300

**Comment by leikkisa** [comment]
Note from Geoffrey:
Caseflow is currently testing with the 2nd Attorney.  Working thru some minor issues, but it is moving forward.

**Comment by laurjpeterson** [comment]
closing because this is being captured in #9527
