### ISSUE TITLE
Claim Details | Create new page with the header "Confirm claim details"

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1106]
As an RO Caseworker, I would like the ability to provide information about the appellant's representative on a new page (`Claim Details`) with the Header "Confirm claim details" so that I can make changes if necessary.  

# Acceptance Criteria
1. Verify that after clicking the **_Continue_** button on the `Check Documents` page, the new `Confirm Case Details` page is displayed.

1. Verify that on the `Confirm Case Details` page the following header and instructional subtext is displayed.

     **Header**
     > Confirm Case Details

     **Instructional Subtext**
     > Review data from VBMS about the appellant's representative and make changes if necessary.

1. Verify that the following data elements are displayed with the defined format, validation requirement, and values, if applicable:
     - **_Representative Type_** - Pre- populates with the VBMS Appellant's Representative Type.  _Required. Editable._.  
     _Radio Button Options_
          - Attorney
          - Agent
         - Organization
         - None
         - Other
     - **_Representative Name_** - displays VBMS value for Representative Name. _Editable.  _Required__

1. Verify that the following buttons are displayed:  **_Continue_**

1. Verify that if there is no value for the following fields, the **_Continue_** button is disabled.
     - Representative Type
     - Representative Name

1. Verify that the following link(s) are displayed:  **_Cancel certification_**

1. Verify that when the link **_Cancel certification_** is clicked, the `Certification Cancellation` modal is displayed.
1. Verify that when the button **_Continue_** is clicked, the `Confirm Hearing` page is displayed.

## Mock(s)
View 1 - New Claims Details Page
![image](https://cloud.githubusercontent.com/assets/23063044/23869552/ba1846f2-07f9-11e7-8f3e-4cfef250d27c.png)

# Related Stories
n/a

**Comment by nikitarockz** [comment]
Original Comments
Just show the header of this page. The rest of it will be built out in future tickets. This ticket is so small because we should think through how best to introduce this change, hide it behind a feature flag, and avoid creating a tangle of technical debt.

![image](https://cloud.githubusercontent.com/assets/3781835/23630925/d07bcb36-028a-11e7-8ae7-d63f5e14c575.png)

**Comment by kierachell** [comment]
**PASSED**
however, data is not being pulled from anywhere and _Required_ fields are not preventing me from moving forward.
<img width="1058" alt="screen shot 2017-04-05 at 8 49 15 am" src="https://cloud.githubusercontent.com/assets/18075411/24706157/c44bc726-19dc-11e7-893a-af2d681f64c2.png">
