### ISSUE TITLE
Check Documents | Show page even on a successful documents check

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1107]
As an RO Caseworker, I would like to have the `Check Documents` page to show a successful documents check page when all the required documents are found so that I can see that all required documents have been found.

# Acceptance Criteria
1. Verify that after logging into Certification and the following required documents have been found, the successful version of the `Check Documents` page is displayed.

     - Form 9
     - NOD 
     - SOC
     - SSOCs (if applicable)

1. Verify that the `Check Documents` page is displayed with the following Informational Alert message and subtext:  (Refer to Mockup/Style Guide)

     **Informational Alert Message**

     > All documents detected!

     **Subtext**

     > The Form 9, NOD, SOC, and SSOCs (if applicable) were found in the eFolder.
1. Verify that all forms listed in the Check documents table show a check mark centered in the _"Founded in VBMS?"_ column.
1. Verify that the following buttons are available:  **_Continue_**
1. Verify that the following links are available:  **_Cancel certification_**
1. Verify that after clicking on the **_Continue_** button, the `eForm 8` page is displayed.
1. Verify that after clicking on the **_Cancel certification_** link, the `Certification Cancellation` modal is displayed.

## Mock(s)
**_View - Check Documents - with all required documents found_**
![check documents](https://cloud.githubusercontent.com/assets/23063044/23802115/4f532858-0580-11e7-9eb9-f3ee59900327.PNG)

### Note

- Previously, we were only showing a page like this when one or more documents were missing or mismatched. 
- The values in the the Document column displayed as links will be handled in another story.

# Related Stories
n/a

**Comment by astewarttistatech** [comment]
**PASSED**

Environment Validated In: UAT
Browsers Validated In: FF and Chrome

Steps to Validate: 
1. Go to Dispatch and select the role to certify claims (v2)
2. Use the BFKEY of an applicable veteran to preform the document check. 
3. Validate the success page shown in the AC is also shown when working with Certification V2.

Screenshots: 
![certificationv2](https://cloud.githubusercontent.com/assets/23038505/24404080/bb3f5f12-138d-11e7-8ab5-03ec0df46a5c.png)
