### ISSUE TITLE
Collect network metrics on VBMS

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#11086]
We currently setup VPC peering between Caseflow and VBMS.

Current state of Caseflow to VBMS setup:

caseflow ----- peering ------ VBMS proxies 
      |
      |
    S3 (efolder documents are cached in S3 by the Reader job)

AC:
A short writeup on network metrics on VBMS.
- How much are we querying VBMS, at what time (chart would do best here) in Mbps?
- How much are we caching during business hours vs reaching back to VBMS for it (ratio).
Add documentation to the Wiki page on how to find this info for others.

**Comment by pkarman** [comment]
I think this is all in datadog.

**Comment by aroltsch** [comment]
@pkarman can you help me with Datadog on this? I would this graph to answer the first question https://app.datadoghq.com/dashboard/54w-efy-r5d/va-systems?from_ts=1558984032311&live=true&tile_size=m&to_ts=1561576032311&fullscreen_widget=285792531&fullscreen_section=overview. However, not sure how to answer the second question using Datagog

**Comment by aroltsch** [comment]
And I found this graph in Grafana: 
https://prometheus.ds.va.gov/grafana/dashboard/db/reader?panelId=3&fullscreen&orgId=1

**Comment by aroltsch** [comment]
I think in order for us to generate graphs like that in Datadog, we need to send those events to DD the same way as we do for Prometheus.

**Comment by aroltsch** [comment]
I need to work with Enrique on this.

**Comment by alisan16** [comment]
@aroltsch Is this ticket still relevant or can we close it?
