### ISSUE TITLE
SPIKE | Can POA information be obtained from VBMS via API.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1109]
Investigate whether or not POA information can be obtained from VBMS via API.
Contact the VBMS team.

**Comment by shanear** [comment]
You can get it from BGS, I've actually done this before. It's a tad tricky but I can help show you how it's done.

**Comment by amprokop** [comment]
ok word!

**Comment by amprokop** [comment]
talked with shane about this. will add notes.
