### ISSUE TITLE
Confirm Hearing | Check in a Form 9 to repo and display it only in local dev environments-placeholder

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1110]
As a Developer, I would like to have a fake Form 9 pdf and a fake "Statements in lieu of form 9" pdf stored in the repo that can be displayed on the `Confirm Hearing` page only in the local dev and demo environments so that we have something to work with. 

# Acceptance Criteria
1. Verify that there is a filled out fake Form 9 pdf stored in the repo.
1. Verify that there is a "Statements in lieu of form 9" pdf stored in the repo.
1. Verify that both fake forms display on the `Confirm Hearing` page only in the local dev and demo.

## Mock(s)
n/a
## Notes

- We might download a [Form 9](https://www.va.gov/vaforms/va/pdf/VA9.pdf) and fill it out with stub info. 
- This page should be built using React, and we should ditch the rails pdf viewer. 
- These changes should only affect local and demo environments, the next ticket will be to fetch the real form 9 from VBMS. 
- We should associate this Form 9 with Certification 123C, and make sure that there aren't any other stub certifications that it should be associated with.

We can skip the radio buttons and such for now, this ticket only concerns the PDF display itself.

# Related Stories
Claim Details | Confirm Hearing | Ability to validate details found on Form 9 #1112

**Comment by shellicious** [comment]
@amprokop what does ditching the rails PDF viewer mean? Assuming it's to display the PDF without all the bells and whistles of the current PDF viewer? if so, I 👍

**Comment by nikitarockz** [comment]
Original comments
We might download a Form 9 [here](https://www.va.gov/vaforms/va/pdf/VA9.pdf) and fill it out with stub info. This page should be built using React, and we should ditch the rails pdf viewer. These changes should only affect local and demo environments, the next ticket will be to fetch the real form 9 from VBMS. We should associate this Form 9 with Certification 123C, and make sure that there aren't any other stub certifications that it should be associated with.

We can skip the radio buttons and such for now, this ticket only concerns the PDF display itself.
![wireframes- caseflow certification improvements 3](https://cloud.githubusercontent.com/assets/1178390/23098735/2108be4c-f624-11e6-9ee9-3df573ab6306.png)


We'll hide any new functionality behind a feature flag:
```
if FeatureToggle.enabled(:certification_v2, current_user)`
  # code here
end
```
