### ISSUE TITLE
Bulk assignment in Hearings Management Team Queue

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11106]
1. When I try to select tasks by "Address Verification Task", it doesn't give a count of how many to select.

1. The Regional Office should include the state in the drop down.

![image](https://user-images.githubusercontent.com/49729315/59627964-7a104600-910d-11e9-9e6c-17220942d3c6.png)

**Comment by aroltsch** [comment]
Issues found at testing:
1. If task type is selected, only display regional office list based on the task type selected.
2. Fix blank lines in the dropdown list for regional office, user and task type
3. Do not allow to click assign tasks when required fields are missing
4. It appears, the number of tasks is not showing when there are a lot of tasks (more than a hard coded max value or smth)

**Comment by pshahVA** [comment]
Thank you @aroltsch.  Would this be in this sprint or do we need to prioritize this into the next one.

**Comment by aroltsch** [comment]
I think I've fixed them all. I will create a PR shortly.
