### ISSUE TITLE
Nightly data integrity checks job

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11109]
We are starting to accrue the need for some nightly checks on data integrity. Let's have a single job that runs that performs the relevant queries and sends them to a Slack channel.

**Comment by lomaxap** [comment]
What do you all think of a utility class like [this](https://github.com/department-of-veterans-affairs/caseflow/pull/11169/files) to check for duplicates.

**Comment by pkarman** [comment]
As part of this it would be helpful if the `SlackService` library could route to different channels.

**Comment by pkarman** [comment]
## Proposal

An abstract class called `DataIntegrityChecker`:

```ruby
class DataIntegrityChecker
  def call
  end

  def report?
  end

  def report
  end

  def slack_channel
    "appeals-app-alerts"
  end
end
```

A single job called `DataIntegrityChecksJob` that loads all subclasses of `DataIntegrityChecker` and runs them. E.g.

```ruby
class DataIntegrityChecksJob < CaseflowJob
  def perform
    list_of_data_integrity_checkers.each do |klass|
      checker = klass.new
      checker.call
      if checker.report?
        send_to_slack(checker.slack_channel, checker.report)
      end
    end
  end
end
```

**Comment by pkarman** [comment]
@lomaxap @tomas-nava @lowellrex @aroltsch curious to know what you think of this proposal.

**Comment by lowellrex** [comment]
Makes sense to me. Do we have a list of jobs that this model would replace?

**Comment by pkarman** [comment]
to start,

* UntrackedLegacyAppealsReportJob
* the async job report currently hacked in to PrepareEstablishClaimTasksJob
* some combination of #10925 and #11169

**Comment by aroltsch** [comment]
This looks good to me!
