### ISSUE TITLE
VBMSError::FileNumberNotFoundForClaimId

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11112]
This request issue update is failing on "create_contentions" with the error:
VBMSError::FileNumberNotFoundForClaimId

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5273/events/361997/

The claim shows up as a pending claim in the veteran's end products with the same claim id. I confirmed that the file number is correct.

**Comment by pkarman** [comment]
Similar problem during veteran search during intake. The issue is ultimately upstream with BGS data. https://dsva.slack.com/archives/CHX8FMP28/p1565887240386800

**Comment by leikkisa** [comment]
Closing as dupe of #11787
