### ISSUE TITLE
Add Veterans to the daily docket 

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11111]
## User Story
As a hearings coordinator, there are certain times when I need to add a veteran onto the docket at the last minute. I need certain hearings branch users to have these privileges.  The current docket no longer shows up as an available hearing day if the day is full.  

_TLDR: We need to allow hearing coordinators the ability to schedule outside of a docket limit. This proposes a search way to do this so we don't have to make major changes to the "Schedule Veterans" tables._

## Acceptance criteria:
- [ ] Verify that when a hearing coordinator searches a Veteran the schedule Veterans actions is in the schedule hearing task
- [ ] Verify that the date fields shows the list of available days for that Veteran to be scheduled 
- [ ] Verify that there is an "other" option that when selected lets them enter a custom day
- [ ] Verify that the date entered is a valid hearing day for that Veteran
- [ ] Verify a warning if that day is full with the following copy: 
     - Title: This hearing day is full
     - Body: You are about to schedule this Veteran on a full docket. Please verify before scheduling.
- [ ] Verify that user can confirm the Veteran into that daily docket
- [ ] Verify that the confirmation for schedule veteran is shown at the top of case details
- [ ] Verify that the Veteran shows in the appropriate daily docket

### Mocks
_Other is an an option in hearing date field and when selected a custom date entry appears_
![Search daily docket.png](https://images.zenhubusercontent.com/5cd1c04a562e0605ea3b7719/8dc613e9-8697-4c00-ac09-935cd4c06a38)

_warning pops up if daily docket is full_
![Search daily docket 2.png](https://images.zenhubusercontent.com/5cd1c04a562e0605ea3b7719/071c1664-7bb9-4c56-b7ba-d36593a16f55)
  

_Confirm message is the same_
![Production case details schedule confirmnation.png](https://images.zenhubusercontent.com/5cd1c04a562e0605ea3b7719/406d50f2-aabe-4cf0-883d-a6c05613fcab)

**Comment by Chingujo** [comment]
@nicholer @pshahVA 

Updated the AC on this ticket and added some open questions

**Comment by Chingujo** [comment]
I am putting this in ready for dev to discuss this design possibility during story time. Should give us a work around to having to change major displays or logic (i.e. showing full docket days in the schedule veterans UI)

**Comment by Chingujo** [comment]
@whoever is working on this, as discussed we can do this two wasy: 

- The other date entry
- We can show all of the days in that drop down such as: 

03/21/15 (8/8)
03/23/15(6/8)

To designate full and semi open days. THis would require a change in how we are rendering the hearing days. Currently, we hide all full days in the UI. Then it would be a consideration on whether we want to show all days just when users search or everywhere. 

Will CC whoever this is assigned to so it jumps

**Comment by ferristseng** [comment]
> We can show all of the days in that drop down such as

I think I'm going to take this approach. I started trying to do the manual date entry way, and think there might be some issues if that date doesn't map to a valid hearing day.

**Comment by Chingujo** [comment]
Sounds good @ferristseng 

Let me know if you need anymore design clarity, I'll post updated mocks today as well

**Comment by ferristseng** [comment]
@Chingujo does the user need to explicitly acknowledge the warning? Would they be prompted with a confirm button followed by the schedule button, or is it enough to just have the warning show before they hit the schedule button?

**Comment by ferristseng** [comment]
Attaching a screen cap @pshahVA 

<img width="456" alt="Screen Shot 2019-07-23 at 3 07 02 PM" src="https://user-images.githubusercontent.com/1298274/61740012-9aaa6c00-ad5b-11e9-97e1-5f86c960594b.png">
