### ISSUE TITLE
Change routing of admin actions

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11113]
When attorneys identify admin actions, the VLJ Support Staff and the Board would like them to be routed directly to the team that needs to action on them, rather than going through VLJ Support Staff as a middleman. 

This is different than our first implementation and set of requirements, which required all admin actions to go through VLJ Support Staff. 

## AC
- Update the following `ColocatedTask` routing logic:
   - Missing hearing transcript admin actions should be routed to the Hearing Management Branch queue
   - Schedule hearing admin actions should be routed to the Hearing Management Branch queue
   - FOIA/Privacy Act request admin actions should be routed directly to the Privacy team queue
   - Translation tasks should be routed directly to the Translation team queue
- Update existing data

## Questions
- Is it low effort to update the name of this group of tasks to be `AdminActions` instead of `ColocatedTask`s?

**Comment by laurjpeterson** [comment]
@lowellrex - can echo estimate this ticket during the next session? also, i think it might absorb this ticket which was already estimated - https://github.com/department-of-veterans-affairs/caseflow/issues/10915

I also think that VLJ Support would benefit from us manually moving their existing Missing hearing transcript, FOIA/Privacy Act, and Schedule hearing tasks to the Hearing Branch. Would we be open to doing this only one time, since we'd fix the routing in the above ticket? if so, I'll create another ticket for that transfer to be estimated.

**Comment by lowellrex** [comment]
We can estimate this ticket and we'll decide whether it makes sense to split it out into multiple tickets during estimation and if it does then we'll write those tickets.

**Comment by laurjpeterson** [comment]
@lowellrex - added one more AC. Routing Translation Tasks to Translation team queue.

**Comment by lowellrex** [comment]
Reminder that after we make the code changes for this PR that we should updated existing tasks that would have gotten bypassed had this code been live at the time they were created (the Missing hearing transcript, FOIA/Privacy Act, and Schedule hearing tasks [LP mentions above](https://github.com/department-of-veterans-affairs/caseflow/issues/11113#issuecomment-503206375)). That work can take place as part of a different ticket if it begins to balloon into a big endeavor.

**Comment by hschallhorn** [comment]
I've got a few questions after looking into this. Within Caseflow, it appears that VLJ Support Staff only have the ability to directly act on

1. `translation` tasks, by [sending to the translation team](https://github.com/department-of-veterans-affairs/caseflow/blob/dc0b6c493db899f11e5018e0df4e7eead0344111/client/constants/TASK_ACTIONS.json#L189)
2. `schedule_hearing` tasks, by [sending to the schedule hearing team](https://github.com/department-of-veterans-affairs/caseflow/blob/dc0b6c493db899f11e5018e0df4e7eead0344111/client/constants/TASK_ACTIONS.json#L171). Though this only exists for legacy appeals, not AMA.

### The questions

1. How does VLJ Support Staff normally handle `missing_hearing_transcript` and `foia` tasks?
2. Do we want to extend the ability to send schedule hearing tasks directly to Hearing Management Branch to AMA appeals?

**Comment by laurjpeterson** [comment]
1. VLJ Support Staff typically sends `missing_hearing_transcript` and `foia` tasks to their respective teams, hearing branch and privacy team. We didn't build the ability for them to send `missing_hearing_transcript` tasks to the hearing branch because we didn't have those requirements at the time (and now do!)

2. Yes!

**Comment by hschallhorn** [comment]
@laurjpeterson More questions!

Right now, the implementation we've been running with is to automatically create
  - `TranscriptionTask` for `missing_hearing_transcripts`
  - `ScheduleHearingTask` for `schedule_hearing` (which automatically creates a `HearingTask` as well based on Caseflow's existing logic)
  - `PrivacyActTask` for `foia`
  - `TranslationTask` for `translation`

### The Questions
1. Does this seem like a fair implementation? When these tasks are completed, they will pop back up to whoever assigned the admin action.
2. As all of these tasks are open and being worked on through caseflow, the VACOLS location code for legacy appeals should be 'CASEFLOW' and not schedule hearing or translation, correct?

**Comment by laurjpeterson** [comment]
Can you also add what text the user sees for these tasks?

  -  `TranscriptionTask` for `missing_hearing_transcripts` - I'm not sure about this one. Let's see what @Chingujo's take is. cc: @pshahVA for context
  - `ScheduleHearingTask` for `schedule_hearing` (which automatically creates a `HearingTask` as well based on Caseflow's existing logic) - I think this theoretically makes sense, however I do remember Meredith wanting the hearing branch to double check that these missed hearings (identified as admin actions) were actually missed hearings, so they didn't go back to waiting for a hearing in error, therefore delaying the appeal. Would love @Chingujo's take on this too. and again, cc: @pshahVA for context 
  - `PrivacyActTask` for `foia` - what does the user see? FOIA requests are different than Privacy Act requests, so I don't know if we should conflate the two into one task if the user can't distinguish them
  - `TranslationTask` for `translation` - yes

**Comment by hschallhorn** [comment]
They see the instructions from whoever assigned the admin action. We could also add clarifying instructions if needed.
We can also show the admin action as its parent.

Other than that, I believe that they see would be mostly the same as a task that did not originate from an admin action.

For `schedule_hearing` we can keep the logic that requires additional confirmation before the real ScheduleHearingTask and HearingTask are created.

**Comment by Chingujo** [comment]
@lauren

Here are my thoughts :

- A transcription task for missing transcriptions (if I’m reading right) makes sense. It’ll allow the transcription team to identify appropriate appeals. Would assume based on prior UX they would want to do the same, since these are distributed to ovlj they would work on these.

Two important notes:

- Alerting the hearings team of new tasks so they can be assigned 
- ensuring these tasks show up as selectable on bulk assignments in the hearings org queue 


- I would agree without a Meredith’s concern here but would defer to Sal to see how he would want it. Since they will be the one processing the request. 

Technically, if these appeals were sent to location 57, our job should catch all the related appeals that have an open co or video hearing. However, if they had a cancelled hearing that co located missed in VBMS, then this could add a significant delay 

Sorry for formatting issues on my phone

**Comment by laurjpeterson** [comment]
@hschallhorn - here's what i think makes sense, now:

**Unresolved:**
  - `ScheduleHearingTask` for `schedule_hearing` 
       - Based on Phillip's notes, I wonder if we should actually create a HearingAdmin type of task for this, so the hearing branch can 

**Resolved!**
  - `TranslationTask` for `translation` - yes
  -  `TranscriptionTask` for `missing_hearing_transcripts` - yes

**Open question for you:**
  - `PrivacyActTask` for `foia` - what does the user see in their Task column when the PrivacyActTask is assigned to them? FOIA requests are different than Privacy Act requests, so I don't know if we should conflate the two into one task if the user can't distinguish them

**Comment by lauren** [comment]
@Chingujo: Wrong Lauren!

@laurjpeterson @lowellrex: Hi!

**Comment by laurjpeterson** [comment]
@hschallhorn and i spoke this morning:

**Needs more product/requirements work:**

       - Based on Phillip's notes, I wonder if we should actually create a HearingAdmin type of task for this, so the hearing branch can review them first to differentiate this from normal ScheduleHearingTasks. 

**Resolved!**
  - `TranslationTask` for `translation` - yes
  -  `TranscriptionTask` for `missing_hearing_transcripts` - yes
  - `HearingTask` for `schedule_hearing` - so users have to review that task _before_ it becomes a schedule hearing task
  - 'PrivacyActTask' for 'foia' - yes. And, hide the `foia` colocated task from users, because privacy users will be able to see the attorney's instructions

**Future**
  - It is likely a good idea to refactor the ColocatedTask list, so attorneys can choose PrivacyActTasks or HearingTasks directly.

**Comment by pshahVA** [comment]
@laurjpeterson is this still blocked?

**Comment by laurjpeterson** [comment]
@pshahVA - no! will remove the `blocked` label now
