### ISSUE TITLE
Confirm Details | Confirm Hearing | Fetch and display most recent document labeled "Form 9" in VBMS

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1111]
As an RO Caseworker, I would like the most recent Form 9 for the case retrieved from VBMS and displayed on the `Confirm Hearing` page so that I can validate its contents for accuracy.

# Acceptance Criteria
1. Verify that the Form 9 with the latest date has been retrieved from VBMS.
1. Verify that the retrieved Form 9 is displayed in the Form 9 PDF section on the `Confirm Hearing` page.

### View - Confirm Hearing Form 9 PDF section
![image](https://cloud.githubusercontent.com/assets/23063044/23924503/51b8c7c4-08e1-11e7-85c6-b205a16f873c.png)

## Notes

- Hook the form 9 check page up to VBMS, so it fetches the real Form 9 and displays it on  #UAT/preprod/prod.   
- The developer doing this ticket needs VA network access to test VBMS connection. We should probably test this out on staging. 

# Related Stories

- [ ] Claim Details | Confirm Hearing | Ability to validate details found on Form 9 #1112
- [ ] Confirm Hearing | Check in a Form 9 to the repo and display it only in local dev environments-placeholder #1110

**Comment by nikitarockz** [comment]
**Original Info**
All new functionality should be hidden behind a feature flag like so:
```
if FeatureToggle.enabled(:certification_v2, current_user)`
  # code here
end
```

**Comment by kierachell** [comment]
**PASSED**
got one from VBMS in `uat`
<img width="1002" alt="screen shot 2017-04-04 at 3 52 08 pm" src="https://cloud.githubusercontent.com/assets/18075411/24675895/cf458998-194e-11e7-8205-a42dfbaa4ae8.png">
