### ISSUE TITLE
Attorney feedback from an email to my VA email

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11114]
Here is my personal ask: more colored tabs for discretionary use:
- An over-arching goal for a Decision Writer is to minimize scrolling to hunt for a particular document or group of documents.  With a choice of several identifiers (color tabs and issue labels) I would like to be able to pull up very short lists of suitable documents or just a single document.  The word search feature is great, but often brings up too many extraneous documents.
    - Example: I want the second rating decision that became final on the issue that I am reviewing.  As addressed a little more in the next point, if I had more colored tags to use with discretion, I would be able to identify each grouping of adjudication with a different color (in this example I would want one color for the first time the claim was brought, denied, and not appealed; another color for the second time it was brought, denied, and not appealed, as well as using the current Blue tag for the procedural documents of my current appeal stream), such that I would be able to use a specific period’s color tag and an issue tag of “RD” to pull up that document specifically.
- Many cases have multiple appeal streams (just looked at a case that had three streams total), which may need to be tracked but are not necessarily part of the issues on appeal at a particular time.  They need to be identified but with only the Blue or Green tags, it overburdens and muddies the process of identifying quickly the most pertinent verus secondary documents.
- Having a spare tag to identify documents that need to be reviewed again would be a great help.
- Many cases have been appealed to the Court at least once, if not multiple times, it would be great to have additional colored tags to identify time frames in the procedural history for documents.

Following up on Questions/Suggestions posted to Caseflow:
- Very early after the launch of Caseflow I specifically asked if a feature could be added such that once inside a document the receipt date for that document could be viewed.  Either I was not aware or it was later added, but that information is located inside the Document Information box in the right-hand column.  I discovered this purely by accident only a month or two ago.  Initially, because that box takes up considerable room on the screen and I didn’t have a reason to use it (or so I thought), I had kept this box collapsed.  It would have been nice if I had gotten an email or if a all-out notice had been sent that the receipt date was contained in that box.  Since Caseflow was launched, I had been clicking in and out of documents to get the receipt date from the main page.

Refresher on Features available for use:
- This also concerns the Document Information box.  It was only after I viewed a case that had been already worked by someone else that I realized the Document Description feature was available for us to use in identifying/organizing content.
- I think it would be beneficial if there was some refresher in-servicing as to how the features of Caseflow can be used for enhanced efficiency in identifying/sorting/organizing content.

In-service provided by Accomplished Caseflow user Decision Writers:
- I suggest you reach out to Renee Trotter (I think she is located at 4E.323; renee.trotter@va.gov) to start you in the right direction on this one.  It would be great to hear some Tips & Tricks for maximizing the features of Caseflow for building efficiency in organizing evidence.  Will also capture some of the issues above with broadcasting features available.

**Comment by araposo-tistatech** [comment]
@araposo-tistatech possibly link to Yooms Reader Enhancements.
