### ISSUE TITLE
Make legacy appeals with an S/SOC date before AMA day ineligible

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11125]
### Story
Veterans can only opt-in from an S/SOC if the S/SOC was issued on or after 2/19/2019.

https://dsva.slack.com/archives/C754H751T/p1560861871060000

### Acceptance criteria
1. If a legacy appeal has an S/SOC date before 2/19/2019, it is not eligible to be opted in. If a user selects it, they will get the "legacy_appeal_not_eligible" error message

### Technical notes
See eligible_for_soc_opt_in? on LegacyAppeal

**Comment by Sjones352** [comment]
@leikkisa can you please provide instructions on how this can be validated or rather do you have a file number with an S/SOC date before 2/19/2019 in UAT?
