### ISSUE TITLE
Confirm Hearing | Ability to validate details found on Form 9

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1112]
As an RO Caseworker, I would like to confirm the details about an appellant's hearing captured in the Form 9 so that I can make sure it was filled out correctly.

Refer to https://github.com/department-of-veterans-affairs/appeals-design-research/issues/25 for the most recent mocks (seen near the bottom of the issue)

# Acceptance Criteria
1. Verify that after clicking on the **_Continue_** button on the `Confirm Claim Details` page, the `Confirm Hearing` page is displayed with the following Header and Subtext:
 
     **Header**

     > Confirm Hearing

      **Subtext**

      > Caseflow found the document below from the appellant's eFolder.  

1. Verify that the page contains the following data element(s) with specified format, options, and required indicator (Refer to Mock):

"Was a cancellation or request made after [decision date]?"

Options:
- Yes
- No

If the answer to the eFolder question is "Yes", verify that the following question is then displayed:

"What did the appellant request
in the document you found?"

Options:
- They cancelled their hearing request.
- They requested a board hearing via videoconference.
- They requested a board hearing in Washington, DC.
- They requested a board hearing at a local VA office.

If the answer to the eFolder question is "No", then verify that the page displays other questions:

"What type of form did the appellant submit?"

Options:
- Form 
- Statement in lieu of Form 9

1. Verify that there is a section to display the Form 9 PDF (Refer to Mock).  

1. Verify that when the option "Form 9" has been selected for the question "What type of form did the appellant submit?", the following question (data element) with specified format, options, and required indicator is displayed below the Form 9 PDF section (refer to mockup):  
 
      Which box did the appellant select for the Optional Board Hearing question? Depending on Form 9, this may be Question 8 or Question 10.

Options:
 - A. I do not want an optional board hearing.
 - B. I want a hearing by videoconference at a local VA office.
 - C. I want a hearing in Washington, DC.
 - D. I want a hearing at a local VA office.
 - No box selected.

1. Verify that when the option "Statement in lieu of Form 9" has been selected for the the question "Which box did the appellant select for the Optional Board Hearing question?", the following question (data element) with specified format, options, and required indicator is displayed below the Form 9 PDF section (Refer to Mock):

"What optional board hearing preference,
if any, did the appellant request?"

Options:
- Does not want a board hearing or did not mention a board hearing.
- Wants a board hearing and did not specify what type.
- Wants a board hearing by videoconference.
- Wants a board hearing in Washington, DC.
- Wants a board hearing at their regional office.

1. Verify that the following button(s) are displayed:  **_Continue_**
1. Verify that the following link(s) are displayed:  **_Cancel certification_** — the link itself will not work until we enable it.

### Notes
The contents and rules for the Form 9 PDF will be in another story.

# Related Stories

- Confirm Details | Confirm Hearing | Fetch and display most recent document labeled "Form 9" in VBMS #1111
- Confirm Hearing | Check in a Form 9 to the repo and display it only in local dev environments-placeholder #1110
- Cancellation Modal | Ability to view instructions and report issues #626

**_Successor_**

- Sign & Certify | Remove no longer needed questions and propagate information to PDF #1115

**Comment by nikitarockz** [comment]
**_Original Comments_**

We need to build out the formal/informal Form 9 UI and all the buttons around it.

Full wireframes of the flow here:
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/25

For now, we don't need to associate this with any fields of the DB.

**Comment by amprokop** [comment]
To fully have this match the mocks, we need the `RadioField` component to be able to display buttons vertically. @slj is working on this now, that'll be implemented after his PR is merged.

**Comment by astewarttistatech** [comment]
So... Nothing matches. @amprokop I'm moving this back into "In Progress" for you.

Current View: 
<img width="1040" alt="screen shot 2017-04-05 at 9 49 24 am" src="https://cloud.githubusercontent.com/assets/23038505/24708581/45d17194-19e5-11e7-85d3-fccc4a4819b3.png">

**Comment by amprokop** [comment]
@astewarttistatech — your screenshot is of the "Confirm Case Details" page. The page that this ticket involves is the "Confirm Hearing" page. There was an error at the beginning of this ticket description (it said "Confirm Claim Details") which I have fixed. 

Please take a look at https://github.com/department-of-veterans-affairs/appeals-design-research/issues/25, which describes the overall flow. 

In the future, if there appears to be something contradictory in the ticket, I think it'd be a more productive workflow if QA pings me or the developer involved to get clarifications/corrections rather than just placing it into "validation failed". Can we try that in the future?

**Comment by astewarttistatech** [comment]
@shellicious @amprokop Since this ticket is "stale" can the AC be freshened up with new mocks and scenarios? That'd be great. 

The current view has a scenario is not accounted for. 
<img width="1266" alt="screen shot 2017-04-06 at 2 36 16 pm" src="https://cloud.githubusercontent.com/assets/23038505/24770089/b36542f2-1ad6-11e7-8532-a7cdc3742f4e.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate:
1. Access Certification V2 and go through the flow posted in the AC
2. Verify elements listed, are viewed. 

Screenshots:
![cv2_flow](https://cloud.githubusercontent.com/assets/23038505/25441003/0ef65db6-2a6f-11e7-83d1-bf1735a498ba.gif)
