### ISSUE TITLE
Support Users with both a Judge Queue and a Non-Judge Queue

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11122]
Moving forward we will have users whose work will require them to have both a Judge Queue (Assign/Review options) and a Non Judge Queue (i.e. Attorney - Assigned/On Hold/Completed).

SSCs #11118 and DVC Assistants #10551 are two example use cases.

**Comment by lowellrex** [comment]
Work on this ticket likely will tie in nicely with [the effort to unify](https://github.com/department-of-veterans-affairs/caseflow/issues/10043) the three different flavor of individual queue table view we have in the application at the moment.

**Comment by lomky** [comment]
See lots of discussion about this topic on #5385. Discussion is over a year old at this point, but lots of material points.

**Comment by lowellrex** [comment]
What is the acceptance criteria for this ticket? Do we want to add a dropdown box link to the "Assign Cases" view for SSCs and DVC assistants?
