### ISSUE TITLE
Add unique constraint on AOD

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11124]
Once per claimant per appeal for advance_on_docket_motions.

This can't currently be a db constraint given how schema is built, but could be enforced in code.

See also #11102

**Comment by lomaxap** [comment]
So this means (in the rare scenario) that an AOD was denied, but later granted, we should overwrite the user and data?

**Comment by pkarman** [comment]
I imagine we'd want to prompt the user that an AOD already exists with a different status, and allow them to explicitly override it. The current problem is silently creating a 2nd record.

**Comment by lomaxap** [comment]
@Chingujo I think this needs some design work

**Comment by Chingujo** [comment]
adding @nicholer for awareness.

Looking to sync about this tomorrow (Wednesday June 26th) with Andrew

**Comment by Chingujo** [comment]
#1125 AOD Daily Docket Model

@lomaxap Explained the use case and I wrote it up here along with a design consideration on overwriting a prior AOD. Going to add cc: @pshahVA for any concerns stakeholder wise and will add to the above ticket

**Comment by pkarman** [comment]
@Chingujo Is #1125 the correct link? that looks like a very old (closed) ticket.
