### ISSUE TITLE
Improve Reader error when document cannot be fetched from VVA or VBMS

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11129]
Rather than "technical difficulties" specify the exact error. This can help alleviate user confusion when the document can be viewed natively in VBMS or VVA.

https://dsva.slack.com/archives/CHX8FMP28/p1560880112230100

## Background
- When users click into a document that isn't in VBMS or VVA, they navigate to a page that contains an error message that says "Technical difficulties"
- This is likely one out of many error messages that could be improved.
- Another example is this one, that prompts the user to download
![image (17)](https://user-images.githubusercontent.com/27704093/61248006-331f6b80-a720-11e9-8322-869ca71d1671.png)

**Comment by hschallhorn** [comment]
What are some of the errors we expect to see?
