### ISSUE TITLE
Store claimant first/last name on claimants table

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11135]
To aid reporting, store the first and last name of the claimant on the `claimants` table, in a manner similar to how we store/cache veteran first/last on `veterans` table. This is basically a BGS cache.

**Comment by laurjpeterson** [comment]
Questions:
- Are we going to check if this is stale and refresh it on a regular basis?

**Comment by pkarman** [comment]
Yes, the same kind of `sync_name` logic should be built for this as for the Veteran model.
