### ISSUE TITLE
Integrate virtual hearings into Caseflow

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11132]
## Epic
As a hearings coordinator, I need to schedule Virtual Hearings for Veterans. A new hearing type of Virtual should be fully integrated into Caseflow alongside other Video, Central Office, and Travel Board hearing types so that Veterans may opt-in or request this new type of hearing.

## Background
The Board of Veterans' Appeals would like to introduce and integrate virtual hearings into Caseflow's Hearings product as another means of scheduling and conducting hearings to alleviate hearing room spatial constraints at the Central Office, and alleviate reliance on a Veteran's ability to travel to a designated Regional Office (RO). While there are some virtual hearings being conducted through a previous solution, developed outside of the Caseflow team (Gen1), Caseflow needs to fully support the new virtual virtual type of hearing. Full integration will allow Hearing Coordinators to minimize their dependency on external (non-Caseflow) VA systems, allowing them to improve the speed of scheduling and streamline the accuracy and consistency of virtual hearing communications.

The Board has a large inventory of hearings that are reliant on spatial capacity of hearing rooms in the Washington D.C. offices.

[See tech spec](https://github.com/department-of-veterans-affairs/appeals-team/pull/1201)
The Board would like to introduce Virtual Hearings as another means of conducting hearings.  The Virtual Hearings solution is developed outside the Caseflow team however it needs to be integrated with Caseflow.  

## Goals
- Veterans should:
  - Be able to join their hearing from anywhere, regardless of time zone, or ability to travel.
  - Receive accurate and timely notification of their hearing, along with links to their hearing, instructions, and reminders.
- The Board should be able to increase hearing capacity by overcoming physical limitations of hearing room availability.

- Caseflow users should be able to:
  - Mark that a Veteran has requested or opted-in to a virtual hearing in advance of their hearing
  - Find virtual-eligible Veterans in a scheduling queue
  - Schedule a virtual hearing for a Veteran who has a requested virtual for their hearing type
  - Convert a hearing to virtual for any Veteran who had previously opted for another hearing type
- The HMB should be able to build:
  - Quarterly and yearly expanded schedules that include virtual-only days 
  - One-off virtual only days for a variety of VLJs to be able to pick up capacity

### Measurable goals
- Decrease the No Show, Postponement, and Cancelation rates
- Increase number of held hearings year over year

**Comment by laurjpeterson** [comment]
Email from Tele-hearing team:

Caseflow is projected to replace the current web scheduler.  

The current web scheduler is basically a contractor created a proprietary windows service (no longer supported) that interfaces with IIS for web portion and also sends APIs to the node manager for  VMR creation/deletion—also sends the confirmation/reminder emails to the judge, Veteran’s rep and the Veteran.  Uses MS SQL DB as well.  

Only the designated BVA schedulers have access to the current web scheduler—the windows service does an AD lookup against the following email distribution list to see if access should be permitted or not:  “BVA Hearing Schedule”

Also the judges are presented on the scheduler if they are in the following DL: “BVA Board Members”

The window service will do a periodically AD checks on the DLs to add or remove folks from either scheduler access or adding/removing judges.

Here is what the front end currently looks like:
![telehearing](https://user-images.githubusercontent.com/27704093/59856585-37d14980-9345-11e9-9f47-8cb882a0c34f.png)

**Comment by laurjpeterson** [comment]
Adding more details I find in other email chains about the tele-hearings product

[Highlevel BVA Scheduler.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/3311661/Highlevel.BVA.Scheduler.pdf)

1. Question: From what I understand based on the demo I saw a link was emailed to participants in the conference.  That link was then clicked on by both sides of the conference (called virtual meeting room [VMR] in Pexip) to get to the call. Let’s call this a reservation.  Is this a correct assumption? 
- Answer: Yes, that is a link for that actual conference (using WebRTC)—the host and guest(s) will receive a link and the host will have a separate pin from the guest (host=judge—who controls the conference).  
2. Question: I may need help to go through the API, but I didn’t see a place where we could generate this reservation. API will actually create the VMR and will include the pin embedded in the link.  
Answer: Agree, we (especially Lyn—our Senior Engineer on Pexip deployments) will need to get together and provide overview and  discuss requirements for the VMRs (such as pin length, VMR lifetime, theme usage, alias info, description, etc…)

**Comment by pshahVA** [comment]
https://app.mural.co/t/workqueue2001/m/workqueue2001/1560455344175/baf8551fd0af01cef844f8eba2a72acb61b95dfb

**Comment by carodew** [comment]
## Notes from 7/17 kick off meeting – 
- can we start with the ideal flow and degrade from there? 
- possible option for story mapping

### next steps
- Nichole and Phillip to meet and hash out next steps and ideal journey
- share this with Premal 
- start getting that in ui design, start usability testing
- come up with a few really good options for stakeholders to show
- Carolyn to look into what kinds of content skills we have access to

**Comment by pshahVA** [comment]
@lomaxap The screen shot here is for a no longer supported application that will not be used.  The functionality will be recreated in Caseflow.  Notice how they looked up active directory to get the Veterans email.  I don't think we would have to integrate with AD if we just put the link in the daily docket.

**Comment by carodew** [comment]
Repeating here the links I posted in Slack, so they can be more easily found in relation to this work. 
1. https://www.jpattonassociates.com/wp-content/uploads/2015/01/how_you_slice_it.pdf
2. https://www.jpattonassociates.com/the-new-backlog/
3. http://www.barryovereem.com/the-user-story-mapping-game/

**Comment by nicholer** [comment]
### **Notes from 7/22 User Flow Sync**
Attendees: Premal, Phillip, Carolyn, Nichole

- Aligned on first flow we'll tackle: switching an already-scheduled veteran to a tele-hearing
- Planned course of action:
  - Nichole (and Phillip) to begin mocks for this flow + will look to sync with Lomax asap this week
  - Obtain usability feedback on mocks from hearing coordinators
 - Compile high-level policy questions for DVC, and present questions + mocks for feedback

**Comment by pshahVA** [comment]
Some other thoughts:
1.) Should the hearings branch to update emails of veterans?
2.) Even though the URL will be placed on the docket, does it make sense to still send an email to the judge?

**Comment by pshahVA** [comment]
yea!
