### ISSUE TITLE
Save UI selections on the Confirm Claim Details page to the DB.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1113]
Decide where this data should live— should it be in the certifications table or the form8 table? We should make DB columns, create a migration, and save the UI selections to the DB.

# Acceptance Criteria
When reloading or navigating back to `/certifications/new/123C` (relative to demo), the fields on the Confirm Case Details page should be persisted—these fields should no longer be wiped on reload.

### Validation Notes

We just need to validate that the same data appears in the UI after a certification is resumed.

**Comment by kierachell** [comment]
**PASSED**

```
SQL (1.5ms)  UPDATE "certifications" SET "representative_type" = $1, "updated_at" = $2 WHERE "certifications"."id" = $3  [["representative_type", "ORGANIZATION"], ["updated_at", "2017-04
-21 18:09:19.953740"], ["id", 76]]
```
<img width="766" alt="screen shot 2017-04-21 at 2 10 01 pm" src="https://cloud.githubusercontent.com/assets/18075411/25290570/9e11b1e8-269c-11e7-8f5e-dff05bfcc90d.png">

```
SQL (1.6ms)  UPDATE "certifications" SET "representative_name" = $1, "updated_at" = $2 WHERE "certifications"."id" = $3  [["representative_name", "DANK MEMES"], ["updated_at", "2017-04-21 18:13:25.789030"], ["id", 76]]
```
<img width="691" alt="screen shot 2017-04-21 at 2 13 24 pm" src="https://cloud.githubusercontent.com/assets/18075411/25290605/c3e81e8e-269c-11e7-8897-cd140657e411.png">
