### ISSUE TITLE
Update VACOLS with the hearing request selection on the Confirm Hearings page. [5]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1114]
Update VACOLS based on the selection in the Confirm Hearing page.

Acceptance criteria:
- If the user has a selection for hearing on the Confirm Hearings page that is not a video hearing, after certification is complete and the user has seen the Successful Certification page, `BRIEFF.BFHR` should contain the corresponding value for that hearing choice. (DC/none/travel board).
- If the user selects a video hearing, `BRIEFF.BFDOCIND`should be updated to say so (TODO: add the actual value that should be in BFDOCIND)

**Comment by amprokop** [comment]
@astewarttistatech — yo yo can you add the values that should be in the Vacols fields?

**Comment by cmgiven** [comment]
## BFHR
```
'1' - Central Office
'2' - Travel Board/Video hearing
'3' - deprecated
'4' - deprecated
'5' - None
```

## BFDOCIND
```
'X'  - Video hearing
null - Not video hearing

**Comment by aroltsch** [comment]
@amprokop, could you please map these values to VACOLS values:
VIDEO: 'VIDEO',
TRAVEL_BOARD: 'TRAVEL_BOARD',
WASHINGTON_DC: 'WASHINGTON_DC',
HEARING_TYPE_NOT_SPECIFIED: 'HEARING_TYPE_NOT_SPECIFIED',
NO_HEARING_DESIRED: 'NO_HEARING_DESIRED',
HEARING_CANCELLED: 'HEARING_CANCELLED'

**Comment by amprokop** [comment]
yes—


VIDEO— BFHR: '2' & BFDOCIND: 'X'

**Comment by shellicious** [comment]
Commenting to say that an unspecified hearing request should be a video hearing

**Comment by amprokop** [comment]
Hmm.

I may have goofed.

For the question shown on an informal form 9, `What optional board hearing preference,
if any, did the appellant request?`, one of the answers is `Wants a board hearing and did not specify what type.`, and I mapped that to a constant `HEARING_TYPE_NOT_SPECIFIED`.

For the question for the formal Form 9, `Which box did the appellant select for the Optional
Board Hearing question above? Depending on the Form 9, this may be Question 8
or Question 10.`, one of the answers is `No box selected.`, and I mapped that to the same constant, `HEARING_TYPE_NOT_SPECIFIED`. But I don't think we want to assume that the Veteran wants a video hearing if they didn't select any box on the Form 9, do we? That seems like it could lead to collateral unwanted hearing requests. cc @shellicious and @nicholasholtz — can you advise on what we should do in this situation?

**Comment by shellicious** [comment]
@amprokop I'm thinking "No box selected" = no hearing wanted, or the No Hearing Desired state.

**Comment by amprokop** [comment]
Yep, agreed. @arolsch can we go with this?

**Comment by nicholasholtz** [comment]
Definitely "No box selected" = no hearing wanted :)

**Comment by aroltsch** [comment]
@amprokop these changes https://github.com/department-of-veterans-affairs/caseflow/issues/1114#issuecomment-295902565 will be done as part of this ticket:
https://github.com/department-of-veterans-affairs/caseflow/issues/1642

**Comment by amprokop** [comment]
@kierachell — let's hold off on verifying this til Monday.

**Comment by kierachell** [comment]
**PASSED**
    BFKEY              BF41STAT BFTBIND            BFDCERTOOL
1 2765717 2017-05-08 00:00:00.0    <NA> 2017-05-08 00:00:00.0

Ayyyy
