### ISSUE TITLE
Sign & Certify | Remove no longer needed questions and propagate information to PDF (formerly eForm8)

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1115]
As an RO Caseworker, I would like to have several questions removed from the `eForm 8` page so that it is more focused on my acknowledgement of reviewing the Form 9 details.

# Acceptance Criteria 

- [x] 1. Verify that after the **_Continue_** button has been clicked on the `Confirm Hearing` page, the `Sign & Certify` page  (formerly `eForm 8`) is displayed.
- [x] 2. Verify that the Header and Instructional text has been updated to the following:

      **Header**
 
      > Sign & Certify
       
      **Instructional Text**
 
      > Fill in information about yourself below to sign this certification.
 
- [x] 3. Verify that questions 1-14 have been removed from the `Sign & Certify` page.
- [ ] 4. Verify that all questions removed (1 -14) that are pre-populated are still retrieved for the current case (retrieved and not displayed).
- [x] 5. Verify that the question #s have been removed from the remaining questions (15 - 17C).
- [x] 6. Verify that the button **_Preview Completed Form 8_** label has been changed to **_Certify appeal_**.
- [x] 7. Verify that the link **_Cancel Certification_** label has been changed to **_Cancel certification_**.
- [ ] 8. Verify that when the **_Certify appeal_** button is clicked, all values entered, updated, and retrieved (1 - 14) are saved to the Form 8 PDF.
- [ ] 9. Verify that when the **_Certify appeal_** button is clicked, the `Success` confirmation page is displayed.

### **_View - Current `eForm 8` page_**
![image](https://cloud.githubusercontent.com/assets/23063044/23923591/9cbb76c6-08dd-11e7-9d90-f9a1b3422d47.png)

### **_View - New `Sign & Certify` page_**
![image](https://cloud.githubusercontent.com/assets/23063044/23923648/d3dcbe44-08dd-11e7-8c90-ff9343132ba9.png)

# Related Stories
**_Predecessor_**
- [ ] Claim Details | Confirm Hearing | Ability to validate details found on Form 9 #1112

**Comment by nikitarockz** [comment]
We basically want to remove a lot of the inputs from the form 8 page, while continuing to fetch the information associated with those inputs from VACOLS and send them to the Form 8 PDF. 
![image](https://cloud.githubusercontent.com/assets/3781835/23631334/1ab2aeb2-028c-11e7-8060-9873f6f99cfc.png)

**Comment by ariperez-gov** [comment]
@amprokop , I'm going to grab this one.  Might move a bit slower so if I'm holding up someone just let me know and we can pair or something.

**Comment by amprokop** [comment]
@ariperez-gov — great! i'll sync with you on slack here.

**Comment by ariperez-gov** [comment]
#1129 PR implements the majority of this story.  Can merge and follow up with another PR after Redux is implemented to wrap everything up. 🚀
