### ISSUE TITLE
Fix ColocatedTasks for LegacyAppeals being charged to wrong location in VACOLS

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11152]
`ColocatedTask`s for `LegacyAppeal`s are sometimes being charged to the wrong location in VACOLS when they are marked complete. During initial investigation of this bug [we added a test](https://github.com/department-of-veterans-affairs/caseflow/pull/11134) that sought to confirm the fix deployed in #10853 fixed all scenarios where charging to the wrong location. That test works as expected, but there is still some scenario where this bug still occurs.

The fix in #10853 was deployed on May 24th, but we still see occurrences of this bug after that date.

![image](https://user-images.githubusercontent.com/32683958/59850560-85938500-9338-11e9-831f-3e4975cac42a.png)

The following query (https://caseflow-looker.va.gov/sql/mcfj2dqyssdcgj) reveals an upper bound on the number of `ColocatedTask`s affected by this bug of 281.
```sql
select id
from tasks
where parent_id in ( select parent_id
  from tasks
  where type = 'ColocatedTask'
    and assigned_to_type = 'User'
    and appeal_type = 'LegacyAppeal'
    and status = 'cancelled'
)
  and type = 'ColocatedTask'
  and assigned_to_type = 'User'
  and appeal_type = 'LegacyAppeal'
  and status = 'completed';
```

We can narrow down the number of tasks affected by this bug to just those cases that are still charged to the (presumably) incorrect VACOLS location in the rails console:
```ruby
  rails c> all_potentially_affected_tasks = Task.find_by_sql("select *
from tasks
where parent_id in ( select parent_id
  from tasks
  where type = 'ColocatedTask'
    and assigned_to_type = 'User'
    and appeal_type = 'LegacyAppeal'
    and status = 'cancelled'
)
  and type = 'ColocatedTask'
  and assigned_to_type = 'User'
  and appeal_type = 'LegacyAppeal'
  and status = 'completed';")
  rails c> all_potentially_affected_tasks.count
  # 281
  # The operation below hits vacols for each of the 281 tasks so it might be a little slow
  # to run, 90 seconds or so.
  rails c> still_mischarged_cases = all_potentially_affected_tasks.select { |task| task.assigned_by.vacols_uniq_id == task.appeal.location_code }
  rails c> still_mischarged_cases.count
  # 93 (as of 9am eastern 20 June 2019)
```

I've spot checked a dozen of the task trees for these appeals and cannot see anything obvious that would lead to this bug. This ticket exists to do further investigation and resolve the bug.

For additional background [see the Slack thread](https://dsva.slack.com/archives/CHX8FMP28/p1560874152224100) where this issue was brought to the attention of the development team.

## Acceptance criteria
* [ ] Determine why `ColocatedTask`s for `LegacyAppeal`s are sometimes being charged to the wrong location in VACOLS when they are marked complete
* [ ] Ensure `ColocatedTask`s for `LegacyAppeal`s are always charged to the correct location in VACOLS when they are marked complete

**Comment by hschallhorn** [comment]
- [ ] Confirm that fix in #11177 works
- [ ] Determine if we want to fix cases charged to the wrong location in VACOLS

**Comment by lowellrex** [comment]
#1117 seems to have fixed the problem. #1117 was live in production at [10:48am eastern on 25 June 2019](https://dsva.slack.com/archives/C7VNGMYUQ/p1561473914075100). The one task (ID 152126) that was closed on 25 June and charged to the wrong VACOLS location was closed at 10:12am eastern, before this code was live.

![image](https://user-images.githubusercontent.com/32683958/60437263-fd389e00-9bdb-11e9-826f-13e0c8b7f07f.png)

```ruby
  rails c> all_potentially_affected_tasks = Task.find_by_sql("select *
from tasks
where parent_id in ( select parent_id
  from tasks
  where type = 'ColocatedTask'
    and assigned_to_type = 'User'
    and appeal_type = 'LegacyAppeal'
    and status = 'cancelled'
)
  and type = 'ColocatedTask'
  and assigned_to_type = 'User'
  and appeal_type = 'LegacyAppeal'
  and status = 'completed';")
  rails c> all_potentially_affected_tasks.count
  # 321
  rails c> still_mischarged_cases = all_potentially_affected_tasks.select { |task| task.assigned_by.vacols_uniq_id == task.appeal.location_code }
  rails c> still_mischarged_cases.count
  # 30 (as of 8:30am eastern 1 July 2019)
  rails c> mischarged_cases_closed_at = still_mischarged_cases.map { |task| { task.closed_at => task.id } }
```

Following up to see if we charge the 30 cases that are still in the wrong VACOLS location to the correct VACOLS location.

**Comment by lowellrex** [comment]
We will relay the IDs of legacy appeals that are still charged to the incorrect VACOLS location to Corey and not attempt to change the VACOLS location on our end.
