### ISSUE TITLE
Add Correct Issues link to Case Details for members of the Case Review organization

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11167]
The Case Review team will be processing the withdrawal of appeals tasks for AMA appeals. We've already changed the routing of these tasks to Case Review organization queue (which has been created).

To withdraw appeals, Case Review team users navigate to the edit issues screen to withdraw issues. When all issues are withdrawn, the appeal is considered withdrawn.

This issue will allow the Case Review team to more easily navigate to the Edit Issues screen.

## AC
- Add the `Correct issues` link to Case Details 
- Ensure Case Review team members can view and click that link, and navigate to Edit Issues
- When users finish editing issues, they are sent back to the Case Details screen

**Comment by lowellrex** [comment]
Looks like we should be able to make this happen by adding a check to see if the current user is a member of the Case Review team in the `User.can_edit_request_issues?` method. Perhaps something like the following:

```ruby
def can_edit_request_issues?(appeal)
  return true if BvaIntake.singleton.user_has_access?(self)

  Task.where(
    ...
```
