### ISSUE TITLE
VACOLS Case Cannot Be Found in BGS

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#11175]
https://dsva.slack.com/archives/CHX8FMP28/p1561037045292900

A user was attempting to establish a claim for appeal with `vacols_id` `3858057`, but was unable to because the veteran could not be found in BGS.

As a temporary fix, I removed the claim from the list of claims that are to be completed
```
appeal = LegacyAppeal.find_by(vacols_id: 3858057)
EstablishClaim.find_by(appeal: appeal).update(aasm_state: "unprepared")
```
([see here for context](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/dispatch/task.rb#L74-L76))

Peter and I found that `appeal.claimant` returns a POA with a social security number. Currently unclear how to resolve this.

**Comment by leikkisa** [comment]
Adding a note that the veteran doesn't seem to be missing from BGS altogether (I was able to do another BGS call for them), but they don't have a BIRLs record.  I have added this to the BGS agenda.

Related:
https://github.com/department-of-veterans-affairs/caseflow/issues/3660

**Comment by pkarman** [comment]
I worked around this with #11241 on the Caseflow side. We don't need to consider the file number present in the BGS response to know that a BGS record exists.

**Comment by leikkisa** [comment]
I'm reopening this ticket due to the flurry of activity here:
https://dsva.slack.com/archives/CHX8FMP28/p1562074852159400

**Comment by leikkisa** [comment]
In this case, the veteran's child was erroneously listed as the veteran on the legacy appeal.

I think we've seen this before, so here are two steps to find the veteran
1. BGS find_by_ssn on the legacy appeal's file number, this provided the person's participant id, and indicators that they were not in the military or a veteran.
2. BGS find_all_relationships with the person's participant_id, this provided the veteran who is the parent

**Comment by pkarman** [comment]
Fixed in VACOLS. The steps were:

```
legapp = LegacyAppeal.find_by( vacols_id: 3858057 )
new_vbms_id = parent_veteran_ssn + "S"
legapp.vbms_id = new_vbms_id
legapp.save!
legapp.case_record.update!(bfcorlid: new_vbms_id)
legapp.case_record.folder.update!(titrnum: new_vbms_id)
```

**Comment by yoomlam** [comment]
One exception to the rule: For Spina bifida appeals (check by running legapp.issues, for example see LegacyAppeal.find(1472110)), the appeal is tracked under the child's vbms_id -- this is intentional and should not be changed. From Jed Wagner:

> Spina Bifida, as a result of agent orange exposure, appeals are unique in that they are the only appeals tracked by the SSN of the child and do not use the SSN or Claim# of the Veteran.
