### ISSUE TITLE
[2] FeatureToggle issues

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1118]
We need to be able to run:

`FeatureToggle.enable!(:certification_v2, regional_offices: ["RO1213"])`
and have Certification v2 enabled only for RO 1213.
Then, we need to be able to run `FeatureToggle.disable!(:certification_v2, regional_offices: ["RO1213"])`
and have certification v2 **disabled** globally

**Comment by amprokop** [comment]
Assigning to Alexis and Artem so that they can figure out how to accomplish this between them. We apparently don't have many user accounts from different ROs in UAT or preprod.

**Comment by kierachell** [comment]
- Does not work for individual Regional Offices.
```
irb(main):036:0> FeatureToggle.enable!(:certification_v2, regional_offices: ["RO17"])
=> true
irb(main):037:0> FeatureToggle.details_for(:certification_v2)
=> {:regional_offices=>["RO17"]}
```
<img width="1075" alt="screen shot 2017-04-27 at 8 12 15 am" src="https://cloud.githubusercontent.com/assets/18075411/25482792/40141fb6-2b21-11e7-922b-6789a2755642.png">

- Works when enabled for _all_ locations:
```
irb(main):038:0> FeatureToggle.disable!(:certification_v2)
=> true
irb(main):039:0> FeatureToggle.enable!(:certification_v2)
=> true
```
<img width="1066" alt="screen shot 2017-04-27 at 8 12 58 am" src="https://cloud.githubusercontent.com/assets/18075411/25482818/5db0f33c-2b21-11e7-897c-396b99de3b18.png">

**BONUS**
- Certification does _not_ work for users with only "Certify Appeal" role:
Using the following:
https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/LOGINS.md#preprod
Attempt to login with a User who only has "Certify Appeal" role
<img width="1027" alt="screen shot 2017-04-27 at 8 21 15 am" src="https://cloud.githubusercontent.com/assets/18075411/25483127/8cb7f8e6-2b22-11e7-958d-87fe41a592e2.png">

**Comment by kierachell** [comment]
- Does not work for individual Regional Offices.
```
irb(main):036:0> FeatureToggle.enable!(:certification_v2, regional_offices: ["RO17"])
=> true
irb(main):037:0> FeatureToggle.details_for(:certification_v2)
=> {:regional_offices=>["RO17"]}
```
<img width="1075" alt="screen shot 2017-04-27 at 8 12 15 am" src="https://cloud.githubusercontent.com/assets/18075411/25482792/40141fb6-2b21-11e7-922b-6789a2755642.png">

- Works when enabled for _all_ locations:
```
irb(main):038:0> FeatureToggle.disable!(:certification_v2)
=> true
irb(main):039:0> FeatureToggle.enable!(:certification_v2)
=> true
```
<img width="1066" alt="screen shot 2017-04-27 at 8 12 58 am" src="https://cloud.githubusercontent.com/assets/18075411/25482818/5db0f33c-2b21-11e7-897c-396b99de3b18.png">

**BONUS**
- Certification does _not_ work for users with only "Certify Appeal" role:
Using the following:
https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/LOGINS.md#preprod
Attempt to login with a User who only has "Certify Appeal" role
<img width="1027" alt="screen shot 2017-04-27 at 8 21 15 am" src="https://cloud.githubusercontent.com/assets/18075411/25483127/8cb7f8e6-2b22-11e7-958d-87fe41a592e2.png">

**Comment by amprokop** [comment]
The problem is likely in 

  def toggle_admin_roles(role:, enable: true)
    return if role == "System Admin"
    if role == "CertificationV2"
      enable ? FeatureToggle.enable!(:certification_v2) : FeatureToggle.disable!(:certification_v2)
    end
    enable ? admin_roles << role : admin_roles.delete(role)
  end

**Comment by amprokop** [comment]
The implementation of #1645 might fix this. We should assign this to the same dev.

**Comment by aroltsch** [comment]
##Old Acceptance Criteria:

This task only requires writing code if the dev finds that the current code has a bug.

We need to be able to run:

FeatureToggle.enable!(:certification_v2, ["RO1213"]
and have Certification enabled only for RO 1213.
Then, we need to be able to run FeatureToggle.enable!(:certification_v2)
and have v2 enabled for all ROs.

Acceptance criteria

Enable certification v2 for just one RO, then test that we are routed to Certification V2 if we sign in as a user from that RO.
Enable certification v2 for a few ROs, then test that we are routed to Certification V2 we sign in as a user from those ROs
Enable certification v2 for all ROs, then verify that any user is routed to Certification V2.
Post the commands that you used in this issue.

See discussion here: #941 (comment)

**Comment by aroltsch** [comment]
Hey @kierachell and @astewarttistatech, this ticket will resolve two issues:
1. https://github.com/department-of-veterans-affairs/caseflow/issues/1118#issue-212250976
2. https://github.com/department-of-veterans-affairs/caseflow/issues/1118#issuecomment-297698201

**Comment by kierachell** [comment]
**PASSED**

this API sucks, yo (why `enable!` requires array of strings, `enabled?` takes only models?); but whatever, no my problem.

<img width="1041" alt="screen shot 2017-05-12 at 12 52 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/26008272/06088170-3712-11e7-8966-23792885a2e1.png">

```
irb(main):039:0> FeatureToggle.enabled?(:certification_v2, user: User.where(css_id: 'CASEFLOW1').first)
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["css_id", "CASEFLOW1"]]
[2017-05-12 12:49:11 -0400]   User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["css_id", "CASEFLOW1"]]
=> true
irb(main):040:0> FeatureToggle.enable!(:certification_v2, regional_offices: ["RO97"])
=> true
irb(main):041:0> FeatureToggle.enabled?(:certification_v2, user: User.where(css_id: 'CASEFLOW_397').first)
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["css_id", "CASEFLOW_397"]]
[2017-05-12 12:50:26 -0400]   User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["css_id", "CASEFLOW_397"]]
=> true
irb(main):042:0> FeatureToggle.disable!(:certification_v2, regional_offices: ["RO97"])
=> true
irb(main):043:0> FeatureToggle.enabled?(:certification_v2, user: User.where(css_id: 'CASEFLOW_397').first)
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["css_id", "CASEFLOW_397"]]
[2017-05-12 12:50:47 -0400]   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["css_id", "CASEFLOW_397"]]
=> false
```


<img width="1011" alt="screen shot 2017-05-12 at 12 53 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/26008274/0aa2f922-3712-11e7-8bd7-7f7c32845939.png">
