### ISSUE TITLE
Allow editing contention text on intake

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11188]
### Story
Currently users are only allowed to edit contention text for request issues during the "edit" step.
During the 6/20 AMO meeting, they requested that we allow users to edit contention text during the initial intake as well.

### Acceptance criteria
During intake, for reviews that are processed in VBMS, a user can edit the contention text for a request issue on the add issues page. When the contention is created in VBMS, it reflects the text submitted by the user.

Note - we need to confirm that CAs are the appropriate users for editing the contention text, or whether we want that to only remain on the edit screen which is more likely to be used by VSRs.

**Comment by pkarman** [comment]
Dupe of #11248 ?

**Comment by laurjpeterson** [comment]
@leikkisa - we've completed this, right? if so, let's close it.

**Comment by leikkisa** [comment]
Done! Closing.
