### ISSUE TITLE
MVP 930s| Establish 930 EP + success page

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11191]
Part of the MVP flow for creating 930 EPs epic

## AC
- When user clicks Establish EP, they navigate to the confirmation page that explains they established a Control 930 EP in VBMS and they can make further corrections in VBMS
    - Note: we propose we make them all Control 930 EPs for the MVP
- 930 EP with the claim label from the original EP (030 or 040) is established in VBMS 
- Use confirmation page design + copy changes below

## Copy
Heading: **Establish 930 EP**
Body: You are now creating a [930 EP + claim label] in VBMS.
   - list the request issues that were added to the Control 930 EP

**Comment by leikkisa** [comment]
Example copy:
A Higher-Level Review Rating Control 930 EP is being established

**Comment by leikkisa** [comment]
control, national_quality_error, local_quality_error
