### ISSUE TITLE
Fix bulk assignment page reload on success

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#11190]
Currently, when a bulk assignment is successful, we reload the entire page https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/BulkAssignModal.jsx#L70. It doesn't provide good user experience. Instead we should dispatch a new action to update certain fields on that page. 

### Acceptance Criteria
- [ ] Page does not refresh automaticvally after bulk assigning tasks
- [ ] Task counts in their respective tabs are correct
- [ ] This flake is fixed https://github.com/department-of-veterans-affairs/caseflow/blob/cab5d1d28de8699b78fb693159a042aeca6a8324/spec/feature/queue/bulk_task_assignment_spec.rb#L26

**Comment by kevmo** [comment]
1 |
2 | ||||
3 | |||||||
5 | |
8 |

3.  Could be straightforward.  Featuring testing and other uncertainties could expand this to a 5.  3 feels like a safe estimate.

**Comment by hschallhorn** [comment]
Let's attempt to un-flake this test as well: https://github.com/department-of-veterans-affairs/caseflow/blob/cab5d1d28de8699b78fb693159a042aeca6a8324/spec/feature/queue/bulk_task_assignment_spec.rb#L26
