### ISSUE TITLE
Add HLR and SC 930 claim labels to end product codes

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11193]
### Story
Users will be able to edit DTA claims that are already cleared in order to make corrections. These claims should be established under the appropriate 930 end product codes.

### Acceptance criteria
- The below end product codes are added to the tree of end product codes referenced in request_issue.rb.  This could under "correction", and organized similarly to non-930 codes where dta and original are broken out into separate branches on the tree.
- Logic for choosing the end product code is updated to choose the dta correction end product code.  The review's "decision_review_remanded" will be useful for determining this logic.
- The end product codes should already be added to end_product.rb and end_product_codes.json, but please confirm
- Bonus points: The code for selecting the correct end product code is refactored into a separate workflow, and/or the tree is refactored into another format to make end product code selection simpler.

Please see PR for the actual list of codes - I am removing the short list from here because the actual list is quite long.

**Comment by leikkisa** [comment]
Waiting on a new list of EP codes, it seems like we are missing some

**Comment by jimruggiero** [comment]
@leikkisa can you add a screen shot or gif to this ticket when it's ready to be merged?

**Comment by leikkisa** [comment]
@jimruggiero sure, I can add a screenshot. I think I'll add one of the confirmation screen, because this ticket is all backend.

I am going to keep this in progress until we hear more about some missing dta correction pension codes.

**Comment by leikkisa** [comment]
![Screen Shot 2019-09-20 at 4.52.00 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/03cc355a-9a73-4353-97b1-1a27001064d7)

**Comment by leikkisa** [comment]
I am moving this issue over, because the "missing EP codes" weren't in the original requirements for VBMS, and I think it might take a while to resolve that. I'll open a new (blocked) issue to handle that once we get some answers on it.
