### ISSUE TITLE
Add evidence window submission task to scheduled, then cancelled hearing

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11205]
In this case (https://appeals.cf.ds.va.gov/queue/appeals/967ddcf7-ff07-4ba6-b75b-e00755a37ddd), the Veteran cancelled the hearing request, and the case went right to the judge. It should have gotten the evidence submission task. 

We've now added functionality that automatically adds the evidence submission window task when the hearing has been cancelled, but this occurred before that PR was deployed (see ticket [here](https://github.com/department-of-veterans-affairs/caseflow/issues/10978))

Let's go back and add the evidence submission window task.

## AC
- for this case: https://appeals.cf.ds.va.gov/queue/appeals/967ddcf7-ff07-4ba6-b75b-e00755a37ddd
- create an evidence window submission task
- start the task from the date that the hearing was cancelled

**Comment by msj0nes** [comment]
@laurjpeterson any update on this for VLJ Larkin

**Comment by laurjpeterson** [comment]
@lomaxap's got it!
