### ISSUE TITLE
Proposed API endpoint for submitting Higher-Level Reviews

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/caseflow#11202]
As part of the Lighthouse Appeals API project, we're adding an external API endpoint for submitting a Higher-Level Review (eventually we'll do the same for Supplemental Claims and Board Appeals). The goal is to have this endpoint be a single step--sending all the info needed as JSON in a single post--unlike the intake UI (multi-step with validation and returned populated data between steps). After having gone through the relevant controllers and models for Higher-Level Reviews, here is my proposed openapi spec (linked below) for this endpoint (we're currently still figuring out the URL namespacing, and  directory structure). An easy way to get a nicely formatted view of this spec is to paste it in to editor.swagger.io

Would love to get some feedback on this from all of you intake experts! --things we're missing/not thinking of, stuff we should look out for, misconceptions/bad assumptions we're making --really, anything we should consider. We're certain that we'll need to make tweaks to this spec with your input, and also as we just get more familiar with the codebase (and all the involved services) in general.

The standard for VA.gov APIs is for them to be documented with openapi (swagger), and that the shape of the JSON return should conform to JSON:API ( https://jsonapi.org/ )--which is why this spec isn't more 1-to-1 with the internal API being used by the intake form (and why it's a bit verbose (with types, etc)). A few examples:

* instead of naming the field `veteran_file_number` or `claimant` (or `participantID`) these are the `id` fields of the respective veteran and claimant objects (this fits better with JSON:API)
* no explicit `veteran_is_not_claimant` field - in the proposed spec, a claimant is an optional relationship to specify, and, if it is absent, the veteran is the claimant.

Thank you in advance for taking a look!

(A PR will be made shortly, and will be linked)

[decision_reviews.yaml.txt](https://github.com/department-of-veterans-affairs/caseflow/files/3326347/decision_reviews.yaml.txt)

**Comment by leikkisa** [comment]
Hi Ed! 

The part around starting a higher level review looks good.  The work around the issue selection is the most complicated part.  This looks like it would work for limited cases, such as if a veteran only had eligible nonrating issues that were not previously intaken through Caseflow and not connected to any legacy issues.

Part of what we're doing is creating an issue chain that tracks an issue's journey, so when a user selects an issue we track what issue it comes from previously and what happens to it next.  All rating issues would be connected to a previous rating issue.  They also need to select connected legacy issues (whether or not the veteran is opting in their legacy issues).

The validation is also important and complicated (especially for the issues), so it would be good to understand the plan for that piece.

**Comment by edmangimelli** [comment]
>The validation is also important and complicated (especially for the issues), so it would be good to understand the plan for that piece.

We're still getting familiar with the intake process (as you can tell!), but, something I was already envisioning doing to help an API consumer perform validation was making separate endpoints that would return the range of possible values for certain fields (something like `higher_level_reviews/payee_codes` and `higher_level_reviews/issue_categories`, or maybe just lump it all together as `higher_level_reviews/constants`).

After speaking with you and Peter, it seems that there will need to be an endpoint that returns the majority of a veteran's file from VBMS/VACOLS so that past appeals / benefit awards can be attached to the new decision review. 

>The work around the issue selection is the most complicated part. This looks like it would work for limited cases, such as if a veteran only had eligible nonrating issues that were not previously intaken through Caseflow and not connected to any legacy issues.

^^^ we continued this conversation in slack, and Philip and I will be getting with you (Sally), and hopefully Claims Assistants who use caseflow, to get a better understanding of the "issue chain", and how the entire history of a Veteran's issues / benefits claims/awards tie in to the appeals process.

**Comment by edmangimelli** [comment]
And I just remembered, Philip had a similar idea on how to provide those constants
--was it a `/scopes` endpoint? @erluti

**Comment by erluti** [comment]
It was an `/enums` endpoint, that supported a param for `scopes` so that you could only get back applicable enums

**Comment by leikkisa** [comment]
The validation entails much more than whether a value falls within a set of specific values. It will be easier to describe when we do our walk through.
