### ISSUE TITLE
Add link to decision reviews Edit page on the Case search page

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11206]
### Story
There is currently no way within Caseflow to navigate to the edit page for decision reviews that are processed in VBMS.  The case search page seems like a natural place to add a link.

### Acceptance criteria
1. On the case search page, for higher level reviews and supplemental claims that are listed for a veteran, add a link to the edit page for that higher level review or supplemental claim.

Related: https://github.com/department-of-veterans-affairs/caseflow/issues/10358

**Comment by pkarman** [comment]
Amazed we don't have this yet! Good use case for the UUID in the URL.
