### ISSUE TITLE
DVC Administrative Assistant Capability Design Work 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#11221]
Currently, dvc administrators need a way to move cases to judges for special and escalated cases. 

## To Do's

- [ ] Map out flows (Phillip)
- [ ] Start working on search screens with the following flow
   - DVC admins see assigned version of their queu
    - Use the search feature 
    - Get to case details 
    - Has the ability to assign 
- [x] Meet LRP

**Comment by carodew** [comment]
The first checkbox will be done as part of #11380

**Comment by carodew** [comment]
@Chingujo Will you be able to update the status of this ticket before you disappear? Ty!
