### ISSUE TITLE
New Org & Ability for Special Case Movement

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11230]
After several discussions internally and with stakeholders, it became clear that the capability of special advance on docket movement is a distinct capability not linked strongly to a Board Organization.

This ticket will create a caseflow org to manage the capability (org admin gives control of the membership, membership grants the ability).

See:
 - DVC tech spec
 - #10551
 - #10878
 - Discussion on cases: https://dsva.slack.com/archives/CJL810329/p1561559611094700
 - Discussion with LRP: https://dsva.slack.com/archives/CJL810329/p1561572176104500

The work here consists of three parts, the design of the user interactions, the technical creation of the org, and then the process of creating the majority-of-cases Super AOD.

## AC
- Create Special Case Movement organization
- Finish special case movement for cases that are already ready for distribution

**Comment by laurjpeterson** [comment]
Idea: start with cases that are ready to distribute --> JudgeAssignTask

**Comment by lomky** [comment]
Pulled out the org creation and the simplest case (ready to distribute -> assigned to judge) out into the issue #11263
