### ISSUE TITLE
Update the bulk assignment feature to be compatible with pagination

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11235]
Background:
The bulk assignment was implemented prior to pagination.  However, the functionality needs to still work after pagination is implemented.

Related tickets for reference:
https://github.com/department-of-veterans-affairs/caseflow/issues/9621

## Acceptance criteria

- [ ] Bulk assignment continues to work as is once pagination features are complete

**Comment by laurjpeterson** [comment]
Another potentially relevant ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/10951 - making bulk assignment work for other organizations. 

VLJ Support Staff requested again today. Not urgent - he understands that things take time and would have to be prioritized by BVA.

**Comment by lowellrex** [comment]
Completed by #11349.
