### ISSUE TITLE
Change Geo Matching to ignore state boundaries.

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11233]
Background
Currently the geo matching to veterans allows the hearings team to determine the closest regional office to that veteran. This regional office is usually limited to the same state as the veteran with some exceptions.

Goals
This will keep the existing functionality, but match a Veteran to a regional office that is closest to their physical address, irrespective of state they live in. 

Question: What about the current hard coded rules that we have in the geo matching algorithm?

**Comment by lomaxap** [comment]
As of 07/01/2019, 30,000+ appeals RO distribution 

| RO | # |
|:--:|:--:|
| RO63 | 120 |
| RO62 | 1585 |
| RO29 | 1420 |
| C | 1719 |
| RO19 | 797 |
| RO06 | 415 |
| RO25 | 893 |
| RO13 | 214 |
| RO09 | 1028 |
| RO18 | 1638 |
| RO35 | 592 |
| RO58 | 20 |
| RO27 | 390 |
| RO38 | 119 |
| RO03 | 34 |
| RO07 | 215 |
| RO02 | 161 |
| RO46 | 656 |
| RO77 | 675 |
| RO04 | 105 |
| RO44 | 845 |
| RO52 | 150 |
| RO41 | 60 |
| RO48 | 867 |
| RO51 | 1096 |
| RO23 | 392 |
| RO50 | 389 |
| RO10 | 793 |
| RO08 | 120 |
| RO28 | 867 |
| RO20 | 1072 |
| RO26 | 323 |
| RO73 | 136 |
| RO59 | 199 |
| RO01 | 602 |
| RO39 | 400 |
| RO17 | 2819 |
| RO42 | 29 |
| RO22 | 1137 |
| RO34 | 149 |
| RO55 | 242 |
| RO31 | 411 |
| RO36 | 68 |
| RO33 | 252 |
| RO49 | 1006 |
| RO14 | 353 |
| RO54 | 363 |
| RO40 | 420 |
| RO15 | 553 |
| RO16 | 1610 |
| RO47 | 228 |
| RO37 | 102 |
| RO21 | 530 |
| RO43 | 1102 |
| RO11 | 221 |
| RO30 | 416 |
| RO45 | 773 |
