### ISSUE TITLE
Display Email address of Veteran

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11240]
Background: A hearings coordinator needs to be able to see the Veterans email address as part of scheduling them for a tele hearing.

To do: Display the email address of the veteran in the "about the veteran" section near the address.

**Comment by Chingujo** [comment]
Add at the end of the "About the Veteran Section" in Case Details. 

![Screen Shot 2019-07-15 at 12.21.43 PM.png](https://images.zenhubusercontent.com/5cd1c04a562e0605ea3b7719/c99ae149-ee86-4974-8928-ca1ec7c3fe82)
