### ISSUE TITLE
Allow users to edit contentions when initially establishing a decision review

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11248]
The "sentence" issue text doesn't play well with other VBMS generated tools - like requests for exams or other letters. Users already now have the ability to edit the contention text in Caseflow _after_ an intake has been completed. They also want the ability to edit it as the decision review is being established.

## AC
- Users can edit contention text on the `Add/Remove Issues` screen before an intake is completed

**Comment by pkarman** [comment]
@laurjpeterson is this the same as #11188?

**Comment by laurjpeterson** [comment]
Yes! Closing.
