### ISSUE TITLE
Route Claim | VACOLS Note | Replace numbered list with lettered list

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1124]
As Product Owner, I would like to replace the number step labels with letters so that it reads easier and to be consistent.

# Acceptance Criteria
1 Verify that the numbered labels for the steps are replaced with letters as indicated below:

_A._ replaces _1._
_B._ replaces _2._ 
_C._ replaces _3._ 

## Mocks
**_View - Route Claim -  VACOLS Note - Current_**
![screen shot 2017-03-07 at 12 24 06 pm](https://cloud.githubusercontent.com/assets/4975959/23669096/17a37c92-0331-11e7-91d2-11d3675a0a85.png)

**_View - Route Claim -  VACOLS Note - Desired_**
![screen shot 2017-03-07 at 12 26 08 pm](https://cloud.githubusercontent.com/assets/4975959/23669202/5132d462-0331-11e7-8592-74a5177c4fc0.png)

# Related Stories
n/a

**Comment by ariperez-gov** [comment]
@lakohl , it appears this is already live on production.

![image](https://cloud.githubusercontent.com/assets/25468798/23911643/d0e4b2ca-08b3-11e7-829d-47a05cb02f8a.png)

**Comment by lakohl** [comment]
Great!

**Comment by lakohl** [comment]
But styling is wrong... A. and B. are rendered in bold in the mocks.

**Comment by ariperez-gov** [comment]
Got it, moving back to in progress to make the change.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Validated Browsers: FF, Chrome

Steps to Validate: 
1. As a caseworker, go to dispatch and try to establish a PG or a REM with the appropriate SIC
2. Validate that when the EP gets to the correct routing screen that the numbered bullet points are replaced with letters, as shown in AC. 

Screenshots: 
<img width="1141" alt="screen shot 2017-03-20 at 12 06 31 pm" src="https://cloud.githubusercontent.com/assets/23038505/24109069/f5d6ec90-0d65-11e7-962a-0261bac518b2.png">
