### ISSUE TITLE
CANCELLED | Motion to Vacate | Decisions attorneys can check out drafted decisions back to their judge

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11254]
After decision-drafting attorneys write either the `Straight Vacate and Readjudication` or `Vacate and De Novo` decisions, they need to go through the typical attorney checkout flow to record their new decision (and new issue dispositions). 

Check out consists of
- Action Send to judge
- Add decisions page
- Remand reasons (if applicable)
- Submit

### Straight Vacate and Readjudication (1 document)
1. Attorneys can immediately perform the checkout which send out a decision letter on granting of vactur on select issues and readjudication of those select issues on the same letter

### Vacate and De Novo (2 documents)
1. Attorneys first need to send out the decision letter on the granting of vacatur on select request issues and granting either a hearing or extension request for the veteran
2. After that administrative action is completed, the case returns to the attorney's queue where they can now perform the checkout

## AC
- Introduce "Decision types" data/concept?
  - Date
  - Writer
  - Signer
  - Type
  - Document ID
- Decision types: Original, Vacate and Readjudication, and De Novo
- Review Vacate Decision task, Review De Novo Decision task show up in Judges Review queue. Same task flavor as JudgeDecisionReview tasks.

**Comment by jimruggiero** [comment]
Open question/validation: Is it required that Caseflow support dispositions on issues and not just motions. Need to ensure current checkout flow for adding disposition to issues will be what is re-used.

**Comment by laurjpeterson** [comment]
There are two things:
1. a disposition on the motion to vacate itself
2. for granted motions to vacate, decision issues and their new dispositions

**Comment by leikkisa** [comment]
I believe this ticket can be closed.
