### ISSUE TITLE
Motion to Vacate | Allow judges to assign motion to vacate tasks to decison-drafting attorneys

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11253]
After judges decide to grant the motion to vacate, they can create new tasks and assign them to their chosen their decision-drafting attorneys - either Straight Vacate and Readjudication or Vacate and De Novo.

If the judge chooses either `Straight Vacate and Readjudication` or `Vacate and De Novo`, they create the task as a child of the Judge Review Motion to Vacate task. 

These tasks show in attorney queues. 

## AC
- Ensure that these assigned tasks appear in attorney queues.

**Comment by jimruggiero** [comment]
Jim to create and link new ticket for deny and withdraw/dismiss judge selections. This ticket will also be linked to new ticket to build disposition table. Estimate is for backend only work.

**Comment by jcq** [comment]
This is complete
