### ISSUE TITLE
Veteran missing file number

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11250]
Slack thread:
https://dsva.slack.com/archives/CHX8FMP28/p1561568993027500

A veteran had a record returned when using fetch_veteran_info(file_number), but the record was missing a file_number so we were unable to create the Veteran. This caused a user to not be able to load dispatch/establish-claim

SR-001989
https://escp.aac.va.gov/ServiceRequest/Details/13446?isDraft=false

This requests a manual clean up of veteran records where the file number is missing.

**Comment by pkarman** [comment]
We have worked around this on the Caseflow side with #11241

**Comment by leikkisa** [comment]
This is all the way fixed (the veteran has a file number now too), closing.
