### ISSUE TITLE
Motion to Vacate | Allow motions attorneys to assign Motion to Vacate tasks to judges

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11252]
As a Lit Support team member (commonly Motions Attorney, but keeping Lit Support team member to encompass other Lit Support roles we might not know about yet), I need to be able to assign a task to the judge who will decide the Motion to Vacate decision. 

Here's a picture of what we think the task tree needs to look like:
https://app.mural.co/t/workqueue2001/m/workqueue2001/1564509468995/c8ff610a5ea20cd199284775e969017d389049bb

## AC
- Create a new task called "Review Motion to Vacate"
- Lit Support team member has the action "Send to judge" (existing? Can we update this content to be "Send Motion to Vacate to Judge")
- Create a new modal that displays to the assigned Motions Attorney and provides three radio button options (Grant, Deny, Withdraw/Dismiss)
- When they click "Send to judge", a modal pops up that contains two fields (1) the user that this task is being assigned to (drop down is pre-populated with name of the VLJ that was originally assigned) and (2) notes for that user (more specific content for 1. grants and 2. all other types)
- new content and design updates are in issue #11683 
- In the modal, the user auto-populates with the judge who previously signed the decision. And, the lit support user can "Select a different judge" (just like on the attorney check out flow)
- The lit support user can click Cancel or Submit on the modal 
- When Lit Support team member clicks Submit, task is created and assigned to judge.
- This is behind a feature flag

## Designs

Latest designs here: https://www.figma.com/file/VtOG0hibbyJ6T5UcYnn5EP/Motions-to-Vacate_Phase-II_Epic-8547?node-id=0%3A1

See comment below with gif

Prototype here: https://va-gov.invisionapp.com/d/main#/console/18207659/377984810/comments

https://va-gov.invisionapp.com/freehand/document/9uIQv1t5J
cc: @geronimoramos

**Comment by geronimoramos** [comment]
![LP AC](https://user-images.githubusercontent.com/49766982/60457969-3da31680-9bf2-11e9-9a66-180fa5458886.gif)
Quick mockup to reflect the AC, cc @laurjpeterson

**Comment by laurjpeterson** [comment]
Amazing! Thank you @geronimoramos

**Comment by laurjpeterson** [comment]
Adding blocked label until we know more about whether lit support should close the MTV task or not.

**Comment by laurjpeterson** [comment]
Sally's PR here: #11289

**Comment by aroltsch** [comment]
I think VacateMotionMailTask can stay on hold until judges log their Motion to Vacate decisions/dispositions.

**Comment by geronimoramos** [comment]
Designs for this are here! https://va-gov.invisionapp.com/d/main#/console/18207659/377984810/comments

**Comment by aroltsch** [comment]
FE implementation is here: https://github.com/department-of-veterans-affairs/caseflow/pull/11767

TODO:
1. Implement a POST request to assign the task to a judge 
1. Create a new task called AddressMotionToVacateTask
1. Ensure AddressMotionToVacateTask tasks appear in the judge's queue

**Comment by jcq** [comment]
This is complete
