### ISSUE TITLE
Motion to Vacate | Judge check out

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11255]
Judges can check out `Straight Vacate and Readjudication` or `Vacate and De Novo` decisions to be dispatched by BVA dispatch. 

Checkout flow includes:
- Ready for Dispatch Action
- Special issues (optional)
- Add decisions
- Remand reasons (optional)
- Evaluate decision

## AC
- Ensure these decision types can successfully go through the existing checkout flow

**Comment by leikkisa** [comment]
I believe this ticket can be closed.
