### ISSUE TITLE
Route Claim | VBMS Note | Update instructional text

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1125]
As a Caseworker, I would like to have the instructional text update on the `Route Claim - VBMS Note` page so that it provides better guidance as to what I need to do.

# Acceptance Criteria
1. Verify page title is "Route Claim: Add VBMS Note

1. Verify that the instructional text below the page title displays: 

     > To help better identify this claim, please copy the following note, then open VBMS and attach it to the EP you just created.

## Mock(s)
**_View - Route Claim - VBMS Note - Before_**
<img width="750" alt="screen shot 2017-03-10 at 8 56 04 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819415/07c3c156-05d4-11e7-8f41-a19c890e2fc2.png">

**_View - Route Claim - VBMS Note - After_**
<img width="750" alt="screen shot 2017-03-10 at 8 57 16 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819430/2a94ea70-05d4-11e7-9e94-0f3435d3f6cd.png">

# Related Stories
App Canvas | Header | Update Route Claim page titles #1033

**Comment by lakohl** [comment]
The title may not need updating. May already be right.

**Comment by kierachell** [comment]
The mocks are the same :(

**Comment by kierachell** [comment]
**PASSED**
but the decision type in the note is incorrect :(
![screenshot_2017-03-16_20-38-19](https://cloud.githubusercontent.com/assets/18075411/24024275/89e44864-0a88-11e7-8548-e7d35a1bfe65.png)
