### ISSUE TITLE
Allow "Special case movement" org members to distribute cases out of order

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11263]
Related to #11230. 

## Acceptance criteria
* [ ] Allow cases that are ready for distribution to be distributed to a specific judge if the current user is a member of a `Special case movement` organization

**Comment by lomky** [comment]
Chatted with LP. Going to Name the Org/Ability ExtrodinaryCaseAdvancement, as apparently this is not related to AOD motionss (appellants are often already AOD) and I'd like to avoid conflating real AODs. Instead I'll allow the user to optionally mark AOD as a part of the action. Any current Judge associated with the case will be the default judge selected as the assignee. Instructions will be required.

**Comment by lomky** [comment]
- [ ] Selectable Task Action
  - [ ] Action based on org (see Generic)
  - [ ] TASK ACTION
  - [ ] Router in client app
- [ ] New Action Route (See EndOnHold)
  - [ ] New Modal
    - Judge to assign
    - checkbox for AOD
    - Instructions
  - [ ] new route
    - restricted to org users
- [ ] new org
  - Consider pulling out 'capablity' orgs versus 'structural' orgs oin model?
- [ ] New Task Type
  - [ ] ExtraordinaryCaseAdvancementTask
    - org task, no individual task. 
      - Task in created & completed upon the user submitting the modal
    - shows in case timeline
    - individual acting on the ECA shows as the assigned_by on judge task
