### ISSUE TITLE
hearing days created_by and updated_by should be FKs

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11260]
Right now we store CSS id on the `hearing_days` model for `created_by` and `updated_by`. We should use AR associations instead.

e.g.
```
belongs_to :created_by, class_name: "User", foreign_key: "created_by_id"
```

This will require a schema change and data migration. Also, db seeds will likely need to change.

**Comment by lomaxap** [comment]
Want to confirm the steps here @pkarman. HearingDay has an existing `created_by` column with that uses `css_id`. We want to replace that with a `created_by_id` foreign key column. 

1. schema change
```
add_foreign_key :hearing_days, :users, column: :created_by_id
```
2. migrate day by mapping `css_id` to `user.id` and filling `created_by_id`
3. add AR association and remove `created_by` column

**Comment by pkarman** [comment]
yes that looks correct @lomaxap -- multiple PRs, with the 4th being the column drops

**Comment by tomas-nava** [comment]
may need to consider changes to Tableau and Looker
