### ISSUE TITLE
Refactor SelectDispositionsView.jsx to make it smaller

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#11268]
Our [eslint config](https://github.com/department-of-veterans-affairs/eslint-config-appeals/blob/master/.eslintrc.js#L120) allows JS files to be up to 400 lines long. PR #11231 added one line to `SelectDispositionsView.jsx` that made it 401 lines long. I wasn't sure how to refactor the file, so we disabled the `max-lines` check in that file temporarily, and we are opening this issue to fix it with the help of a frontend person.

**Comment by leikkisa** [comment]
Closing this ticket
