### ISSUE TITLE
Add `Stayed appeal` admin action task for AMA and Legacy appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11278]
VA has issued a stay on blue water navy Veterans. The Board wants to add a `Stayed appeal` admin action task (also called `ColocatedTask`) to capture these appeals.

## AC
- Add `ColocatedTask` called `Stayed appeal`
- This task can be added to both Legacy and AMA appeals
- `Stayed appeal` is routed to VLJ Support Staff organization (which is then auto-routed to an individual on the VLJ Support Staff team)
- Use same actions that are currently available, nothing new

**Comment by laurjpeterson** [comment]
We officially got the go ahead to do this one!

**Comment by lowellrex** [comment]
@laurjpeterson This new `Stayed appeal` admin action should be routed to the VLJ support staff, correct? And the task should not have any special actions beyond what is currently available (start/end timed hold, change type, return to attorney, cancel task), is that also correct?

**Comment by laurjpeterson** [comment]
Correct, correct!
