### ISSUE TITLE
Missing VACOLS hearing record causes page at /tasks/<id> to fail.

### ISSUE THREAD

**Issue by kevmo** [department-of-veterans-affairs/caseflow#11281]
Sometimes VACOLS hearings have been deleted, but a reference to them remains in the Caseflow Postgres database. Then, when the `HearingRepository#load_vacols_data` method is run, the application fails.

This ticket exists to explore whether and how to deal with this situation such that the page still loads, but the missing hearing does not silently fail.

Related Slack messages: https://dsva.slack.com/archives/C6E41RE92/p1562096518147400
Related Sentry Alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5614/

**Comment by kevmo** [comment]
It appears as though this method is also raising errors in the `HearingDispositionChangeJob`.

**Comment by lomaxap** [comment]
also see #10852

**Comment by lomaxap** [comment]
see also #10852

**Comment by lomaxap** [comment]
We need to create front end error message "Hearing cannot be found in VACOLS" on hearing worksheets, (see [sentry error](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3275/)), [hearing details](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4354/events/347479/) and case details pages.

**Comment by sharonwarner** [comment]
I added error pages for hearing details and hearing worksheets so if the hearing is missing in vacols, the user will get an error. 

Case details pulls legacy hearings only from vacols, so we should not see errors on that page. 

The only other place we're seeing errors is in the tasks_controller when users are trying to update hearing dispositions for hearings that have been deleted. This case should go away in the very near future as Jed disabled functionality for deleting hearings in VACOLS. There are a few cases that will require some manual cleanup that I'm tracking [here](https://github.com/department-of-veterans-affairs/caseflow/issues/11660).
