### ISSUE TITLE
Create End Product | Partial Grant modifier out of order?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1129]
# Description
As a Caseworker,
when I am creating a new End Product for a Partial Grant or Remand,
when there are existing End Products for Partial/Remand decisions,
when those End Products have modifiers higher than 170 (e.g. 171,175)
the new End Product I create will have a modifier of 170 and not subsequent higher modifier.

**Environment:**
- [ ] Production
- [X] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [X] Functional
 
# Reproduction Steps
Scenario 1 - Creating a new Partial/Remand EP

1. Go to Dispatch and start creating a new End Product for a Partial/Remand

1. Click *Route Claim*

1. Observe 1-2 existing EPs (check in VBMS that they already have modifiers 171, 175, etc taken, but _not_ 170)

1. Proceed to *Create End Product*

1. Observe that the modifier for the new EP is 170

1. Create new EP

1. Go to VBMS and observe that a new claim 170 was created.

1. Wonder if that's right and ask @lakohl or @abbyraskin 

## Screenshots

need help from VBMS team with this

# Related Issues

**Comment by lakohl** [comment]
@abbyraskin the above sounds right, but can you confirm?

**Comment by abbyraskin** [comment]
@lakohl @kierachell looks good to me too.

**Comment by shanear** [comment]
I believe this is intended functionality

**Comment by kierachell** [comment]
@shanear @abbyraskin 
During testing with VBMS team - I was notified that it was not the expected behavior. I need clarification.

**Comment by shanear** [comment]
@kierachell we still think this is correct. We can chat with VBMS about this if they have an issue. Closing.
