### ISSUE TITLE
Relationship to veteran show correctly throughout Caseflow

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11301]
## Description
All claimants have a relationship to the veteran, whether it's a specific type of dependent (Parent, Child, Spouse), or an Attorney (for both listed and unlisted attorneys).  This is shown to the user on some pages, such as the Add Issues page and the non-compensation line of business queues.

At this point, we have confirmed that the relationship type is showing correctly on Add and Edit Issues and Case Details.

This ticket is for showing relationship type correctly on the non-compensation queue task page.

## Acceptance criteria
- [ ] Relationship type shows up on non-compensation queue task page

## Screenshot of current behavior
![image (6).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/b5a6a46f-909e-42e4-913c-429b87251f8d)

## Background
On the single task page for a non-comp decision review task, the "Relationship to Veteran" display logic is flawed. See e.g. task 248934 where it should display "Child" but instead displays "claimant".

## Tech notes
Previously we match a veteran's "relationships" with the claimant participant ID for the Intake Review and Add Issues page. We want to start getting it directly from the claimant.

A couple of places in the code to get started:
`caseflow/client/app/nonComp/pages/TaskPage.jsx`
`caseflow/app/models/serializers/work_queue/decision_review_task_serializer.rb`

To see a decision review task locally
1. Intake an HLR or SC with a benefit type not processed in VBMS (like Education). 
2. Add a claimant who is NOT the Veteran.
3. After submitting, you should be directed to the queue for that organization and be able to click through to the task. It's URL will look something like:
`/decision_reviews/education/tasks/[task_id]`

**Comment by meckilabritt-navapbc** [comment]
Walking through technical notes, the relationship to Veteran is showing accurately as Spouse, Child, Parent, etc. under **Relationship to Veteran**
<img width="937" alt="Screen Shot 2020-09-10 at 4 35 53 PM" src="https://user-images.githubusercontent.com/68879427/92826170-401c0700-f385-11ea-8a1c-cf3c79d460de.png">
