### ISSUE TITLE
Enable back-end sorting of tasks by assignee name

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11316]
#11247 established the pattern for how the pagination API will sort tasks for the queue on the back-end but did not enable sorting by all fields. This ticket exists to enable sorting by assignee name through the pagination API that mirrors [how we sort by that field on the front-end](https://github.com/department-of-veterans-affairs/caseflow/blob/0377b8d0a0d77a81a070c82c6bd336600885cfa3/client/app/queue/components/TaskTable.jsx#L180).

## Acceptance criteria
* [ ] Enable back-end sorting of tasks by assignee name

**Comment by hschallhorn** [comment]
In search of an answer to the question "Will an organization's queue ever display the name of an org in the Assigned to column"

```ruby
> ignorable_parents = ["RootTask", "TranslationColocatedTask", "MissingHearingTranscriptsColocatedTask", "FoiaColocatedTask", "DistributionTask"]
> ignorable_children = ["TimedHoldTask", "TrackVeteranTask"]
> org_ids = Task.open.where(assigned_to_type: Organization.name).where.not(type: ignorable_parents).pluck(:id)
> org_org_tasks = Task.open.where(assigned_to_type: Organization.name, parent_id: org_ids).where.not(type: ignorable_children)
> task_data = org_org_tasks.map { |t| [t.type, t.parent.type] }.uniq
=> [["HearingAdminActionVerifyAddressTask", "ScheduleHearingTask"],
   ["HearingAdminActionIncarceratedVeteranTask", "ScheduleHearingTask"],
   ["NoShowHearingTask", "AssignHearingDispositionTask"],
   ["HearingAdminActionForeignVeteranCaseTask", "ScheduleHearingTask"],
   ["ScheduleHearingTask", "HearingTask"],
   ["AssignHearingDispositionTask", "HearingTask"],
   ["ChangeHearingDispositionTask", "HearingTask"],
   ["HearingAdminActionVerifyPoaTask", "ScheduleHearingTask"],
   ["HearingAdminActionOtherTask", "ScheduleHearingTask"],
   ["HearingAdminActionMissingFormsTask", "ScheduleHearingTask"],
   ["GenericTask", "GenericTask"],
   ["HearingRelatedMailTask", "HearingRelatedMailTask"],
   ["GenericTask", "HearingRelatedMailTask"],
   ["TranscriptionTask", "AssignHearingDispositionTask"],
   ["EvidenceSubmissionWindowTask", "AssignHearingDispositionTask"],
   ["PowerOfAttorneyRelatedMailTask", "PowerOfAttorneyRelatedMailTask"],
   ["EvidenceOrArgumentMailTask", "EvidenceOrArgumentMailTask"],
   ["NoShowHearingTask", "ChangeHearingDispositionTask"],
   ["ExtensionRequestMailTask", "ExtensionRequestMailTask"],
   ["ReturnedUndeliverableCorrespondenceMailTask", "ReturnedUndeliverableCorrespondenceMailTask"],
   ["AodMotionMailTask", "AodMotionMailTask"],
   ["ReconsiderationMotionMailTask", "ReconsiderationMotionMailTask"],
   ["EvidenceSubmissionWindowTask", "HearingTask"]]
```

**Comment by lomky** [comment]
Discovery from discarded PR #11780.

I initially assumed we wanted to sort by **`Task`** assignee, and implemented 11780 on those lines. This led to the discovery during code review the current listed assignee & thus the front end sorting is based on **`Appeal`** via the function `assigned_to_location` (s/o to @hschallhorn for the great catch). 

Discussing this behavior w/ Lowell & digging into history led me to #9283, where the choice was made to show appeal-level assignee. This makes more sense to our users, who think of Appeals as an entity with a status and assignee, as opposed to having distinct tasks each with a status and assignment.

In this context, it may be worth investigating which tasks we should be showing in the "on_hold" tab for organizations. Right now we show the immediate child of that task, which may or not be the active task (e.g. a Colocated Org Task has an Translation Org Task directly under it, with the Translation User Task obscured one further below).

Tagging off this issue until next week to restart it.
