### ISSUE TITLE
Enable back-end sorting of tasks by regional office

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11313]
#11247 established the pattern for how the pagination API will sort tasks for the queue on the back-end but did not enable sorting by all fields. This ticket exists to enable sorting by closest regional office city through the pagination API that mirrors [how we sort by that field on the front-end](https://github.com/department-of-veterans-affairs/caseflow/blob/0377b8d0a0d77a81a070c82c6bd336600885cfa3/client/app/queue/components/TaskTable.jsx#L130).

This ticket is probably not blocked by #11311, because we should be able to join through the `appeals` and `legacy_appeals` tables to get the regional office for each task, but it may still be worthwhile to cache the values in the table that will be created by #11311 so we should explore doing just that.

## Acceptance criteria
* [ ] Enable back-end sorting of tasks by regional office

**Comment by hschallhorn** [comment]
I'm voting in favor of adding it to the cached table. While `Appeal` and `LegacyAppeal` both have a `closest_regional_office` column, this is stored as the code while we sort (and filter) based on the [associated city](https://github.com/department-of-veterans-affairs/caseflow/blob/77c5a1be45cc026c59a4b369e320049e87fa912e/client/app/queue/utils.js#L562).
