### ISSUE TITLE
Enable back-end sorting of tasks by appeal type

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11315]
#11247 established the pattern for how the pagination API will sort tasks for the queue on the back-end but did not enable sorting by all fields. This ticket exists to enable sorting by appeal type (AOD, CAVC remand, original) through the pagination API that mirrors [how we sort by that field on the front-end](https://github.com/department-of-veterans-affairs/caseflow/blob/0377b8d0a0d77a81a070c82c6bd336600885cfa3/client/app/queue/components/TaskTable.jsx#L158).

## 🚫 Blocked by
* [x] Enable back-end sorting of tasks by docket type and number #11311
  * #11311 [will set up the framework](https://github.com/department-of-veterans-affairs/caseflow/issues/11311#issuecomment-509732409) that this ticket will extend by 1) creating a table that contains the cached attributes, 2) creating the job that runs regularly to populate that table, and 3) establishing the patterns for the statements that shuttle the appropriate data from VACOLS/Caseflow into the cached table.

## Acceptance criteria
* [x] Enable back-end sorting of tasks by appeal type
* [x] Make this the default sorting used by all sets of task returned from the back-end by the queue.

**Comment by lowellrex** [comment]
Run into [the same previously described issue](https://github.com/department-of-veterans-affairs/caseflow/issues/11311#issuecomment-509403176) of needing information from two database systems. `LegacyAppeal`s get AOD and CAVC information from VACOLS's `brieff` table and `Appeal`s get this information from the Postgres database (with a call to BGS that we need to investigate as well). Will need to make a decision about how to handle the two database system problem before continuing.

**Comment by lomky** [comment]
Gathering the AOD status in one fell swoop rather than a record at a time. [SQL notes](https://caseflow-looker.va.gov/sql/ddnwjknzngmvbj)
