### ISSUE TITLE
Enable back-end sorting of tasks by assigner

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11318]
#11247 established the pattern for how the pagination API will sort tasks for the queue on the back-end but did not enable sorting by all fields. This ticket exists to enable sorting by task assigner through the pagination API that mirrors [how we sort by that field on the front-end](https://github.com/department-of-veterans-affairs/caseflow/blob/0377b8d0a0d77a81a070c82c6bd336600885cfa3/client/app/queue/components/TaskTable.jsx#L369).

## Acceptance criteria
* [ ] Enable back-end sorting of tasks by task assigner

**Comment by hschallhorn** [comment]
Note on this. 
We display assigner name as `#{task.assigned_by.full_name.split(' ').first} #{task.assigned_by.full_name.split(' ').last}`, but we have 37 users with `full_name`s like `Joe Dirt ["JR" | "I" | "II" | "III" | "IV" | "V"]` which would display the assigner as `Joe ["JR" | "I" | "II" | "III" | "IV" | "V"]`.  Don't know if we want to address this.

**Comment by lowellrex** [comment]
For this ticket let's just reach parity with the front-end. If the front-end sorts those names incorrectly, let's sort them incorrectly just the same and create a new ticket to fix sorting on both the back- and front-end.
