### ISSUE TITLE
request issue missing benefit type

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11322]
Some request issues are missing a `benefit_type` during intake, which results in a `nil` value for the corresponding `BusinessLine` assignment for non-comp task creation.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5298/events/392841/

**Comment by pkarman** [comment]
Example of what is happening:
```
irb(main):014:0> BusinessLine.find_or_create_by(name: nil)
[2019-07-08 12:24:33 -0400]   BusinessLine Load (2.2ms)  SELECT  "organizations".* FROM "organizations" WHERE "organizations"."type" IN ('BusinessLine') AND "organizations"."name" IS NULL LIMIT $1  [["LIMIT", 1]]
[2019-07-08 12:24:33 -0400]    (0.7ms)  BEGIN
[2019-07-08 12:24:33 -0400]   Organization Exists (0.8ms)  SELECT  1 AS one FROM "organizations" WHERE "organizations"."url" IS NULL LIMIT $1  [["LIMIT", 1]]
[2019-07-08 12:24:33 -0400]    (0.6ms)  ROLLBACK
=> #<BusinessLine id: nil, type: "BusinessLine", name: nil, role: nil, url: nil, participant_id: nil>

```

**Comment by aroltsch** [comment]
I think we had a bug where we didn't send `is_unidentified` flag when the issue was unidentified.

In Kabana, 

`Parameters: {"request_issues"=>[
{"decision_text"=>"Denied: Service connection for hearing loss is denied.", "vacols_id"=>nil, "vacols_sequence_id"=>nil, "withdrawal_date"=>nil}]`

**Comment by pkarman** [comment]
yes @aroltsch I saw similar. Anything around that date suggest if we fixed it as a side-effect of something else?

fwiw, this doesn't happen often and smells to me like an (unknown) specific set of steps on the UI side to trigger a payload w/o the `is_unidentified` flag.

**Comment by aroltsch** [comment]
What's interesting that all these "suspicious" issues have denied, granted in front of the decision text:
`
{
decision_text: Granted: Service connection for pseudofolliculitis barbae is granted with an evaluation of 0 percent effective February 25, 2015., 
vacols_id: None, 
vacols_sequence_id: None, 
withdrawal_date: None
}
`

`{
decision_text: Denied: Service connection for hearing loss is denied., 
vacols_id: None, 
vacols_sequence_id: None, 
withdrawal_date: None
}`

which makes me think that somehow dispositions are added to these?

**Comment by aroltsch** [comment]
I think these two issues are related to the same problem https://github.com/department-of-veterans-affairs/caseflow/issues/10985

**Comment by aroltsch** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/12032
