### ISSUE TITLE
Styleguide component | Button for source code

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1133]
As a developer, I want to have a link to the usage examples of the components in the style guide.

## Acceptance Criteria
- Validate that for each Styleguide section, there is a link in the top right to the source code file (ie: StyleGuideTables.jsx) in Github (see mocks below)
- Bonus Points for a github emoji in the link

## Technical Notes
- We may want to autogenerate this link in a StyleguideSection base class.

**Comment by mmlumba** [comment]
@gnakm can you send me the logo via slack?

**Comment by gnakm** [comment]
@mmlumba It looks like we're going to move forward with embedding a source code for the living styleguide. Since you're away, please confirm when you get back and then we can close out this issue.

**Comment by mmlumba** [comment]
@gnakm This sounds good to me. Closing.

**Comment by mmlumba** [comment]
@shanear Source code ticket for reference

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers Validated in: FF and Chrome

Steps to Verify: 
1. Go to the Style Guide and check the specs of the "View Source Code" button on the tabs section against the AC of this ticket

Screenshot:
<img width="1273" alt="screen shot 2017-03-23 at 1 25 23 pm" src="https://cloud.githubusercontent.com/assets/23038505/24261166/7cddf860-0fcc-11e7-89ad-dfb92d8badcb.png">

**Comment by mmlumba** [comment]
@gnakm The "View Source" button uses color #0071bc with a hover color of #205493. This should be similar to all the other blue action buttons used in Caseflow.

**Comment by gnakm** [comment]
@mmlumba 
RE: The "View Source" button uses color #0071bc with a hover color of #205493. This should be similar to all the other blue action buttons used in Caseflow.

^ This statement is correct.
