### ISSUE TITLE
JSON::ParserError in efolder_service.rb

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#11340]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4891/

At first glance, it looks like code assumes the response will always be a 200 and parseable as JSON. It doesn't handle the case where the request times out or returns some other unsuccessful response.

There are 54 events in Sentry, all in the same line of code when trying to fetch an appeal's documents in Reader. Most of these errors were due to Efolder returning a 502.

**Comment by alisan16** [comment]
This error hasn't been seen in 6 months (since Sep 17, 2019 5:17:26 PM EDT). Closing out the issue
