### ISSUE TITLE
Verify contentions exist in VBMS before allowing editing of request issues

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11348]
The most frequent error in our async job queue for `RequestIssuesUpdate` is the `ContentionNotFound` error. We believe this is because users are manually deleting contentions directly in VBMS, making the reference ids in Caseflow point at non-existing records.

In order to prevent those kinds of errors, we want to (a) limit manual deletion in VBMS (we have an open request for that) and (b) verify that contentions exist before a user starts to edit the request issues on a claim review.

TBD what should happen when a user tries to edit a claim review with missing contentions? Some suggestions:

* automatically mark the request issue as `removed` with a status like `contention_missing`
* visually flag the request issue in the browser with some kind of alert about the missing contention
* both?

**Comment by pkarman** [comment]
@leikkisa @jimruggiero @rutvigupta-design I have started on this in #11466 

Right now I am just raising an error to prevent editing of the issues on the decision review, but this feels inadequate to me, and least useful for the user.

I'm leaning toward the easiest solution in the description of this ticket, which would be marking the troublesome issues as `removed` with a status like `contention_missing`.

Thoughts?

**Comment by leikkisa** [comment]
@pkarman I think that's the best way to go.  They can add the issue again if they need to.  Also it sounds like the VBMS fix for this is in the July release, and that will prevent this more contentions from being deleted in VBMS.

**Comment by pkarman** [comment]
This has been merged. Moving to Validation to make sure we stop seeing those errors.

**Comment by pkarman** [comment]
Most recent incident in Sentry is from 7/25.
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5361/events/406708/

**Comment by pkarman** [comment]
No more in Sentry. Considering this fixed.
