### ISSUE TITLE
new exception class for no end products returned

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11342]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4110/

Create a custom exception class for when zero EPs are returned from BGS `get_end_products`

**Comment by jcq** [comment]
It looks like `ruby-bgs` repo already has the new exception class...?
https://github.com/department-of-veterans-affairs/ruby-bgs/blob/master/lib/bgs/errors.rb#L98

**Comment by pkarman** [comment]
yep this ticket is outdated. feel free to close.
