### ISSUE TITLE
Fix BulkAssignModal when front-end does not have access to all tasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11349]
The `BulkAssignModal` currently [populates values](https://github.com/department-of-veterans-affairs/caseflow/blob/a97f887101a5f6148798584e853b49edcf83c05c/client/app/queue/components/BulkAssignModal.jsx#L222) in the regional office and task type dropdown menus by collecting all unique values for those fields from the set of tasks available in the global redux store.

![image](https://user-images.githubusercontent.com/32683958/60971780-ea684c80-a2f2-11e9-94c0-5c620dac5d83.png)

This approach correctly contains all unique values for the appropriate tasks unless the front-end does not have access to all tasks that should be considered. Since we are limiting the number of tasks returned to the front-end currently with [a hard-limit in `Organizations::TasksController`](https://github.com/department-of-veterans-affairs/caseflow/blob/a97f887101a5f6148798584e853b49edcf83c05c/app/controllers/organizations/tasks_controller.rb#L26) and soon with [the pagination API](https://github.com/department-of-veterans-affairs/caseflow/blob/a97f887101a5f6148798584e853b49edcf83c05c/app/models/queue_config.rb#L49) for the hearings management branch, the list of values in the regional office and task type dropdown menus may exclude some values that should otherwise be included.

Since the `BulkAssignModal` already [makes a request to the back-end](https://github.com/department-of-veterans-affairs/caseflow/blob/a97f887101a5f6148798584e853b49edcf83c05c/client/app/queue/components/BulkAssignModal.jsx#L35) for the list of users who belong to the hearing management branch, we can piggy back off that request to get the complete list of possible hearing locations and task types even when we do not have all tasks available to us on the front-end. As a bonus we can simply move the `Organizations::MembersController` since the `BulkAssignModal` is currently the only place where we make a request to that endpoint (`caseflow $> git grep members client/`).

## Acceptance criteria
* [ ] `BulkAssignModal`'s regional office and task type dropdown menus contain unique values for correct fields for all tasks

**Comment by kevmo** [comment]
2

**Comment by lowellrex** [comment]
Query that will return the cross-section that we want to return to the front-end (https://caseflow-looker.va.gov/sql/rmzbrxwqjskgdd).

```sql
select count(*)
, tasks.type
, closest_regional_office
from tasks
left join (
  select closest_regional_office
  , id
  , 'LegacyAppeal' as type
  from legacy_appeals
  union
  select closest_regional_office
  , id
  , 'Appeal' as type
  from appeals
) all_appeals
  on tasks.appeal_id = all_appeals.id
  and tasks.appeal_type = all_appeals.type
where assigned_to_id = 20
  and assigned_to_type = 'Organization'
  and status in ('assigned', 'in_progress')
group by 2, 3
order by 2, 1 desc;
```
