### ISSUE TITLE
Adding rating issues and unidentified issues to HLR endpoint issue types, and specifying ID for issues that already exist

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/caseflow#11356]
Two things:

As of right now, the HLR endpoint isn't set up for rating issues and unidentified issues (just non-rating issues)
```
    {
      "type": "request_issue",
      "attributes": {
        "decision_text": "string",
        "decision_date": "2019-07-10",
        "withdrawal_date": "2019-07-10",
        "nonrating_issue_category": "Unknown issue category"
      }
    }
```

Also, to make sure we tie issues back to where they already live in DBs, one should be able to optionally specify an ID.
More about this:
https://github.com/department-of-veterans-affairs/caseflow/pull/11330#discussion_r302214605

So I'm thinking that json above should become:
```
    {
      "type": "rating_issue|nonrating_issue|unidentified_issue",
      "attributes": {
        "id": "string", # <-- OPTIONAL (if not specified, creating a new issue)
        "decision_text": "string",
        "decision_date": "2019-07-10",
        "withdrawal_date": "2019-07-10",
        "nonrating_issue_category": "Unknown issue category"
      }
    }
```

@leikkisa  @pkarman 
let me know if you think this approach won't work

@erluti

**Comment by pkarman** [comment]
there are certain combinations of values will not make sense or are ambiguous.

e.g. a payload like:

```json
{
  "type": "rating",
  "attributes": {
    "nonrating_issue_category": "foo"
  }
}
```
is ambiguous. Is it a rating or nonrating issue?

**Comment by edmangimelli** [comment]
Sorry, I should have been more explicit. I'm envisioning that a request issue could take these shapes:

```
    {
      "type": "rating_issue",
      "attributes": {
        "id": "string", # OPTIONAL
        "decision_text": "string",
        "decision_date": "2019-07-10",
      }
    }
```

```
    {
      "type": "nonrating_issue",
      "attributes": {
        "id": "string", # OPTIONAL
        "decision_text": "string",
        "decision_date": "2019-07-10",
        "withdrawal_date": "2019-07-10",
        "nonrating_issue_category": "Unknown issue category"
      }
    }
```

```
    {
      "type": "unidentified_issue",
      "attributes": {
        "id": "string", # OPTIONAL
        "decision_text": "string",
        "decision_date": "2019-07-10",
      }
    }
```

(actually, I'm not sure what the shape of `unidentified_issue` needs to be)

Therefore your example above would be malformed rather than ambiguous.

>Whether we include an id seems to me, philosophically, like the difference between a POST and PUT request. Right now we treat everything as a POST because we have a separate endpoint for editing (or PUTing) an existing HLR (or other decision review). I'm not clear, if this is describing the Intake API for creating a Decision Review, if you're trying to describe how to update one as well as create one?

So I was talking specifically about a POST to either:

```
/decisions_reviews/higher_level_reviews
/decisions_reviews/supplemental_claims
/decisions_reviews/board_appeals
```

to *create* a new decision review.

I was envisioning that, when creating a decision review with a POST, in that same call you would be attaching issues to the DR with an array in the JSON body of the request.
The presence/absence of an issue ID would dictate whether you were intending to create or reference an issue.

**Comment by pkarman** [comment]
When you create a new Decision Review, you always creating new Request Issues to go with it. We never reference existing Request Issues.

**Comment by edmangimelli** [comment]
The new request issues created in caseflow never reference VBMS (or BGS, or whatever outside system) IDs in any way?

**Comment by pkarman** [comment]
References to the contested rating issue are made via the `contested_rating_issue_reference_id`.

See all the attributes here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issue.rb#L188

The confusion can be because the word "issue" is overloaded in this application.

* rating issue
* request issue
* rating request issue
* nonrating request issue
* unidentified issue
* decision issue
* contestable issue

all kinds of issues.

Rating request issues always refer to a `contestable_rating_issue_reference_id`. See e.g. https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issue.rb#L229

**Comment by pkarman** [comment]
The other naming convention that is important to note is that `id` always refers to an internal FK column, while `reference_id` always refers to an external identifier of some kind.

**Comment by edmangimelli** [comment]
ah, ok, so then maybe the create/reference scheme I was thinking of can just be an abstraction for the API consumer. That is, all issues included with the POST request to make a new decision review are new in caseflow, but, if an ID was provided, that's a reference id.

**Comment by pkarman** [comment]
I would not call the API attribute `id`. That will inevitably become ambiguous. Call it the `contested_rating_issue_reference_id` for clarify and accuracy.

**Comment by edmangimelli** [comment]
I need to mull on this and talk to @erluti about it. We're trying to follow JSON:API https://jsonapi.org/ to a T, and it's pretty strict on what things should be called.

**Comment by edmangimelli** [comment]
Technically, I don't think JSON:API even let's you creating multiple resources in one call. I'll talk about this with other lighthouse engineers

**Comment by edmangimelli** [comment]
So how about this:
```

**Comment by edmangimelli** [comment]
So that rating issue was fetched from an outside DB --when creating a new request issue in caseflow from an issue fetched from outside, is the rating issue copied into caseflow exactly with no changes? can the decision review process add or update info so that the issue in caseflow no longer mirrors the issue in the outside DB?

**Comment by pkarman** [comment]
TBH, the `type` is pretty irrelevant to Caseflow. It's all just a `RequestIssue` and the type is derived from the values of the attributes.

We copy just a few attributes from the rating issue to the request issue:

* `decision_date`
* `contested_rating_issue_diagnostic_code`
* `contested_rating_issue_reference_id`
* `contested_issue_description`

Anything else we just look up if necessary via the reference id.

It's important to note that a request issue does not "mirror" a rating issue. A request issue *contests* a rating issue. It's a chain. Look at the abstraction class for `ContestableIssue` https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/contestable_issue.rb

**Comment by alisan16** [comment]
@edmangimelli Is this still needed based on the changes in the Lighthouse project roadmap?

**Comment by edmangimelli** [comment]
>@edmangimelli Do you have any updates on this ticket? Can it be closed?

@alisan16 , let's close this one too!
