### ISSUE TITLE
IDT outcode file name

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11353]
from Paul:

> The outcode API endpoint is assigning a UUID for the file name.  Can that be changed to be of the form "YYYYMMDD BVA Decision VETERAN NAME" to make it easier to identify for people looking at the claims folder
> The document has a separate UUID property, the issue is that it is using the UUID as the description of the file

https://dsva.slack.com/archives/CD5DAQNCU/p1562770182062400

**Comment by BVA-IDT** [comment]
Filename here is the file description in VBMS, not the name of the file when downloaded.  By file description I mean what is shown when browsing the list of cases in Reader.
