### ISSUE TITLE
Hearing Location Dropdown - Error body not always defined

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#11370]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4237/

**Comment by laurjpeterson** [comment]
@sharonwarner - discussing this ticket in some light backlog grooming. Have you opened a PR for this? Peter remembers it came up in bat team last week.

**Comment by alisan16** [comment]
This error hasn't been seen in 9 months. Closing out
