### ISSUE TITLE
Extraordinary case advancement from case distribution

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#11380]
Design ticket for the simplest version of extraordinary case advancement: moving an appeal from the Ready for Distribution task to the Judge Assign task.

**Comment by carodew** [comment]
@laurjpeterson is it correct that this is no longer something that design can support right now? Wondering what I should do with this card. Thx!

**Comment by laurjpeterson** [comment]
We can close this! @stwards11 is going to flesh out the Epic ticket #11397 so we can truly see what user stories might need design work down the line.
