### ISSUE TITLE
Styleguide | Layout UI Tweaks

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1138]
As an engineer, I need to know the specs of the layout of Caseflow commons :)

## Acceptance Criteria 

- When user clicks on a component on the menu, the section should jump to the top. 
- Add source code button next to each title
- Verify that titles are `h1
- Verify that subtitles for sub sections are `h3`
- Verify that body copies are `p`'s

## Mockups

![image](https://cloud.githubusercontent.com/assets/13420618/24280948/36aca18e-102b-11e7-8f04-5df023b14d1c.png)

**Comment by gnakm** [comment]
@tejans24 @mmlumba @shanear @ariperez @slj 

This is reference for how the styleguide should look!

**Comment by shanear** [comment]
This should reference styleguide components like h1's and p's instead of defining px values

**Comment by gnakm** [comment]
new mock and ACs updated above.

**Comment by gnakm** [comment]
Closing this because it's been implemented.
