### ISSUE TITLE
Fix boot up lag when booting up locally

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1141]
The first request when booting up `rails s` locally seems to take 15 seconds to process the first request. This is sort of annoying, and we should look into the cause and try to remove it.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
