### ISSUE TITLE
Assess url pattern for API endpoints

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1142]
We have a handful of JSON API endpoints for the establish claim flow. Right now we sort of just add them as needed in whatever controller that seems right.

We should reassess where these API endpoints should go, and if we should try and make them more widely available.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
