### ISSUE TITLE
TypeError on 403 XHR response

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11434]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5790/

When trying to access a URL from the /queue/appeals/3430012/tasks/262160/modal/assign_to_person modal, a 403 response triggers a JS error.

**Comment by jcq** [comment]
Likely related:
A 403 response after completing the assign_to_person modal results in invalid props for `tasks`, which means that calculating `totalTaskCount` causes an error.

- [Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7728/)
- Error is likely occurring [on line 105](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/OrganizationQueue.jsx#L105) of `OrganizationQueue`

**Comment by jcq** [comment]
Likely same issue as #12297
