### ISSUE TITLE
Refactor and add tests for all special issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1143]
Right now, there is some janky logic to convert DB keys for the special issues into the proper react names. (see: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/EstablishClaimPage/EstablishClaim.jsx#L119)

This almost caused us to mess up some of our special issues in a story. We should make this a lot cleaner and better tested.

**Comment by kierachell** [comment]
Did not find any additional bugs yet; will keep validating for a bit more.

**Comment by kierachell** [comment]
**PASSED**

triple checked on `uat`; no new bugs found
