### ISSUE TITLE
Confirmation | Congratulations | Add more information about the Established Claim

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1144]
As a Product Owner, I would like to have the all of the Congratulation `Confirmation` pages' title, subtext, checklist, and action button subtext updated so that they describe in better detail all of the actions that have occurred during processing the claim.

# Acceptance Criteria 
1. Verify that the title has been changed to "Success!".
1. Verify that the header subtext displays the following:
     
     > [Veteran Name's] (ID#[ID number]) claim has been processed. 
You can now establish the next claim or return to your Work History.

1. Verify that each checklist item contains a check mark for each step the claim has taken (see below for scenarios).
1. Verify that the checklist dynamically changes based on the various following completed scenarios:

     ID|Claim Type and Route Scenario|Mock View
     ---|---|---
     1| Full Grant, No Special Issues, EP Created (for ARC)|View 1
     2 | Partial/Remand, No Special Issues, EP Created (for ARC)|View 2
     3   | Full Grant, w/Special Issue, EP Created, Added VBMS Note|View 3
     4   | Partial/Remand, w/Special Issue, EP Created, VACOLS Updated, VBMS Note Added|View 4
     5   | Full Grant, w/Special Issue, No EP, Email Sent|View 5
     6   | Partial/Remand, w/Special Issue, No EP, VACOLS Updated|View 6
     7   | Unsupported Issue, Processed outside of Caseflow|View 7
     8   | Multiple Decisions|View 8
     9   | Existing EP|View 9

1. Verify that when a claim (_Full Grant, No Special Issues, EP Created (for ARC)_) has been processed, the  following checklist items are displayed (Refer to View 1 Mock):  

     - Reviewed [Decision Type] decision
     - Established EP: [EP Code] for Station [display station]

1. Verify that when a claim (_Partial/Remand, No Special Issues, EP Created (for ARC)_) has been processed, the following checklist items are displayed (refer to View 2 Mock):

     - Reviewed [Decision Type] decision
     - Established EP: [EP Code] for Station [display station]
     - Updated VACOLS: Changed Location to 98

1. Verify that when a claim (_Full Grant, w/Special Issue, EP Created, Added VBMS Note_) has been processed, the following checklist items are displayed (refer to View 3 Mock):

     - Reviewed [Decision Type] decision
     - Established EP: [EP Code] for Station [display station]
     - Added VBMS Note on [Special Issue; Special Issue]

1. Verify that when a claim (_Partial/Remand, w/Special Issue, EP Created, VACOLS Updated, VBMS Note Added_) has been processed, the following checklist items are displayed (refer to View 4 Mock):

     - Reviewed [Decision Type] decision
     - Established EP: [EP Code] for Station [display station]
     - VACOLS Updated: Changed Location to [location code]
     - VACOLS Updated: Added Diary Note on [special issue; special issue]
     - Added VBMS Note on [Special Issue; Special Issue]

1. Verify that when a claim (_Full Grant, w/Special Issue, No EP, Email Sent_) has been processed, the following checklist items are displayed (refer to View 5 Mock):
 
     - Reviewed [Decision Type] decision
     - Sent email to: [RO Email] in [RO City], [RO State] re: [Special Issue] issue(s)

1. Verify that when a claim (_Partial/Remand, w/Special Issue, No EP, VACOLS Updated_) has been processed, the following checklist items are displayed (refer to View 6 Mock - ROJ would not be present):

     - Reviewed [Decision Type] decision
     - VACOLS Updated: Changed Location to [location code]
     - VACOLS Updated: Added Diary Note on [special issue; special issue]

1. Verify that when a claim (_Unsupported Issue, Processed outside of Caseflow_) has been processed, the following checklist items are displayed (refer to View 7 Mock):

     - Reviewed [Decision Type] decision
     - Processed case outside of Caseflow

1. Verify that when a claim (_Multiple Decisions_) has been processed, the first item in the checklist becomes the following item and its subsequent list items display according to the type and route of the claim (View 8 Mock):

     - Reviewed & selected [Decision Type] decision

1. Verify that when a claim (_Existing EP_) has been processed, the following checklist items are displayed (View 9 Mock):

     - Reviewed & selected [Decision Type] decision
     - Assigned existing EP: [EP Label]

1. Verify that the following subtext is displayed to the left of the **_Establish next claim_** button:

     > [TotalCasesAssigned] number of cases assigned, [TotalCasesCompleted] completed

## Mock(s)
**Existing Confirmation page:**
<img width="914" alt="screen shot 2017-03-13 at 9 56 39 am" src="https://cloud.githubusercontent.com/assets/4975959/23857474/cee702b0-07d3-11e7-989f-0a9f4e98696e.png">

**New Versions of Confirmation page:**
 **_View 1 - Full Grant, No Special Issues, EP Created (for ARC)_**
<img width="740" alt="screen shot 2017-03-11 at 6 17 22 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827689/ff0268c0-0686-11e7-81c3-3d8853069dff.png">

**_View 2 - Partial/Remand, No Special Issues, EP Created (for ARC):_**
<img width="710" alt="screen shot 2017-03-11 at 6 10 05 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827663/410a646c-0686-11e7-922a-056bed3fcdc4.png">

**_View 3 - Full Grant, w/Special Issue, EP Created, Added VBMS Note:_**
<img width="683" alt="screen shot 2017-03-11 at 6 18 35 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827693/2ca8f55a-0687-11e7-9209-45c9f9d2be4f.png">

**_View 4 - Partial/Remand, w/Special Issue, EP Created, VACOLS Updated, VBMS Note Added_**
<img width="651" alt="screen shot 2017-03-11 at 6 19 33 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827702/70100f9a-0687-11e7-93b2-1f1be2533dca.png">

**_View 5 - Full Grant, w/Special Issue, No EP, Email Sent:_**
<img width="703" alt="screen shot 2017-03-11 at 6 21 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827708/92b4e20a-0687-11e7-8143-56933a999e2a.png">

**_View - 6 Partial/Remand, w/Special Issue, No EP, VACOLS Updated, ROJ Changed:_**
<img width="716" alt="screen shot 2017-03-11 at 6 22 42 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827721/d5516412-0687-11e7-8050-f6845e40914d.png">

**_View 7 - Unsupported Issue, Processed outside of Caseflow:_**
<img width="708" alt="screen shot 2017-03-11 at 6 24 55 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827731/0daf4f0e-0688-11e7-99ec-20e62f4679b3.png">

**_View 8 - Multiple Decisions Example:_**
<img width="717" alt="screen shot 2017-03-11 at 6 28 14 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827744/ac8aea02-0688-11e7-9077-9ff9379b3eb7.png">

**_View 9 - Existing EPs Example:_**
<img width="695" alt="screen shot 2017-03-11 at 6 30 49 pm" src="https://cloud.githubusercontent.com/assets/4975959/23827760/192f56fc-0689-11e7-9caa-2db2b7348b63.png">

# Related Stories
n/a

**Comment by lakohl** [comment]
will add mock and define AC

**Comment by lakohl** [comment]
Review language

**Comment by nikitarockz** [comment]
# Sprint Planning Notes
Removed the following AC since ROJ is not being handled:
1. Verify that when a claim (_Partial/Remand, w/Special Issue, No EP, VACOLS Updated, ROJ Changed_) has been processed, the following checklist items are displayed (refer to View 6 Mock):

     - Reviewed [Decision Type] decision
     - VACOLS Updated: Changed Location to [location code]
     - VACOLS Updated: Added Diary Note on [special issue; special issue]
     - VACOLS Updated:  Changed ROJ to [New ROJ Code]

**Comment by kierachell** [comment]
**PASSED**
deployed to `prod` without any sort of validation so who cares.

**Comment by kierachell** [comment]
<img width="1071" alt="screen shot 2017-03-28 at 7 31 07 am" src="https://cloud.githubusercontent.com/assets/18075411/24402911/9aad4084-1388-11e7-9c45-42f34107dd7f.png">
for real?

**Comment by lakohl** [comment]
If we are going to go this direction, I don't think we should be so shy about it.
