### ISSUE TITLE
Remove Edit Contention Button on Unidentified issues in UAT

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#11451]
In Intake, we do not edit text on Unidentified issues but in VBMS we instruct user to Edit issue in Caseflow. We should specify that that we do not edit-contention text on unidentified issues.

![Screen Shot 2019-07-18 at 12.58.49 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/e72eb777-85ea-407b-b05c-a0dbbd6a85c2)

I also found a bug in UAT which shows the Edit-Contention-Text on Unidentified issues. We should remove this featuretoggle on Unidentified issues.
![Screen Shot 2019-07-18 at 12.48.45 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/333e4f79-1758-463d-880d-913d6f29b3cd)

**Comment by msj0nes** [comment]
@Sjones352 Is this ticket now safe to close with the merge above or is additional work needed?

**Comment by Sjones352** [comment]
@msj0nes yes
