### ISSUE TITLE
Webpack file-loader error

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#11463]
Certain assets (fonts & images) are failing to load (404) in local dev environment. This includes various sourcesans font files & multiple icons from uswds.

This manifests with errors like this from Rails:
`ActionController::RoutingError (No route matches [GET] "/fonts/sourcesanspro-bold-webfont-86937a00b9e6bd153ddb2d25a296896d.ttf"):`

**Background:**
In the webpack config, we have rules for assets like fonts and images that tells it to use the [url-loader](https://github.com/webpack-contrib/url-loader) if the file size is under the specified limit, and it will fallback to [file-loader](https://github.com/webpack-contrib/file-loader) if it exceeds that limit. 

The other options being provided to url-loader were `outputPath` & `publicPath` — these appear to be causing problems for assets that exceed the limit and fallback to file-loader. Removing them seem to fix the issue in the dev server w/o any negative consequences.

On a related note, the current config has the limit set to 1024 bytes, which seems a bit small. I typically have seen limits in the 5–10KB range, which would allow more of these small SVG and other files to get inlined by url-loader.

**Comment by leikkisa** [comment]
We figured out the issue and closed the PR, closing this issue.
