### ISSUE TITLE
Adjust footer position

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1146]
Footer should be lower than it currently is and consistent in it's positioning.

## **AC**
Footer should start 150px from the lowest element on the page.

**Comment by lakohl** [comment]
@gnakm should we make this a Style Guide component?

**Comment by gnakm** [comment]
@lakohl We have an issue for it. We can bump it up in priority at our 11a meeting. If you agree, I think we can close this issue :) all the power to you!

https://github.com/department-of-veterans-affairs/caseflow/issues/1090

**Comment by lakohl** [comment]
Closing in favor of #1090
