### ISSUE TITLE
Remove unsupported special issue modal code

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1147]
There's a bunch of code related to cancelling unsupported special issues. With new features, like the email page, and VACOLS routing, we don't actually display that modal anymore.

We should delete any code that relates to it:
see: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx#L355

**Comment by joofsh** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/1154

**Comment by kierachell** [comment]
**PASSED**
Didn't totally break Dispatch, so should be ok.
validated on `uat` when trying to create EPs with previously unsupported SIC.
