### ISSUE TITLE
Stop throwing Caseflow::Error::ActionForbiddenError: Current user cannot access this task for Colocated users

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11478]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3678/events/396317/).

This error was thrown because the task is not assigned to the user and CaseDetailsLink attempts to update the task to in_progress when [any colocated user](https://github.com/department-of-veterans-affairs/caseflow/blob/919548d0e91d7b5ed3ea66511d162feada68402b/client/app/queue/CaseDetailsLink.jsx#L19) clicks the link.

### AC

- [ ] Only attempt to update a task to `in_progress` if the task is assigned to the current user

**Comment by hschallhorn** [comment]
TODO: Update with link to offending code when github starts working again

**Comment by alisan16** [comment]
This hasn't been seen in 8 months. Closing.
