### ISSUE TITLE
Null Address Error from VA.gov Validator

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11481]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5084/events/404985/

I think we might be able to handle these errors in the FetchHearingLocationsForVeteransJob like we're doing for VaDotGovLimitErrors. They might not need to be captured in Sentry.

**Comment by alisan16** [comment]
This hasn't been seen in 8 months. Closing.
