### ISSUE TITLE
BSE 64638 - Capability to Expand Caseflow Capacity to Additional Decision Types and Dates

### ISSUE THREAD

**Issue by geoffreystienblock** [department-of-veterans-affairs/caseflow#11489]
**Requirement:**  Caseflow to link with all tables within  Corporate to pull all decisions to display in Caseflow and pull all decisions prior to 2005
**Value Statement:**  As a Caseflow user, I need the Caseflow application to be able to process all the decision types identified in Supporting Artifact 64638, so that I can process the large majority of AMA compensation claims using the Caseflow application.
**Definition of Done:**  1.Caseflow is able to process all claims identified in Supporting Artifact 64638.

**Comment by laurjpeterson** [comment]
We've been tracking this in this ticket, about the ability to intake decision reviews with missing ratings/issues - https://github.com/department-of-veterans-affairs/caseflow/issues/10511

**Comment by laurjpeterson** [comment]
And for the other part, ability to intake more decision types, I've separated it into this ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/11373 - because it's quite separate. Will close this!
