### ISSUE TITLE
BGS::ShareError - Not Unique Result

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11482]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/5136/events/405293/

Looks like multiple records are coming back for `find_by_file_number`.

```
... was configured to have a unique result, but more than one instance matched the query.
```

**Comment by pkarman** [comment]
this is a known VBMS data problem. The issue is multiple phone records, none of which (or all of which) are marked as primary. This is a solved problem in Caseflow but not yet in Efolder.
