### ISSUE TITLE
Unprocessable Entity from POST to /reader/appeal/vacolsId}/claims_folder_searches

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11484]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5807/events/405245/).

Code [literally says](https://github.com/department-of-veterans-affairs/caseflow/blob/919548d0e91d7b5ed3ea66511d162feada68402b/client/app/reader/DocumentListHeader.jsx#L15) to not worry if this fails. Do we want to stop reporting this to sentry then?

**Comment by pkarman** [comment]
Or ignore in Sentry forever? that will keep it from going to slack but we can still have the analytics if we need them.

**Comment by hschallhorn** [comment]
Sounds good to me!

**Comment by hschallhorn** [comment]
Dow we want to close this now that it's been ignored forever?

**Comment by pkarman** [comment]
yes
