### ISSUE TITLE
Duplicate Key Error for Hearing Appeal Stream Snapshots

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11480]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5851/events/405233

Happens in the LegacySerializer in the `current_issue_count` attribute, when getting active appeal streams. It looks like if there are no appeals, it will try to get some from VACOLS.

**Comment by alisan16** [comment]
Closing this as the error hasn't been seen in 8 months
