### ISSUE TITLE
Linters are running twice in CI

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1148]
Linters are running twice in CI. We only need them to run once :smile:

**Comment by kierachell** [comment]
**PASSED**
watched a bunch of recent Travis builds.
Now need to remove double brakeman :D

![screenshot_2017-03-14_11-01-18](https://cloud.githubusercontent.com/assets/18075411/23906986/115ae1de-08a6-11e7-9013-8c324ada00d9.png)
saw only those above
