### ISSUE TITLE
VBMSError - Unable to determine the validity of veteran

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11483]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/5178/events/403017/

Haven't seen this error before, but might be related to

https://github.com/department-of-veterans-affairs/caseflow/issues/10502

```
EFSERR1071
Unable to determine validity of veteran using identifier: FILENUMBER
```

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 8 months
