### ISSUE TITLE
VBMS::SOAPError Unable to parse SOAP message, Nokogiri::XML::SyntaxError

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11496]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5834/events/405073/).

**Nokogiri::XML::SyntaxError**
72:11: FATAL: Input is not proper UTF-8, indicate encoding !
Bytes: 0xEF 0x2F 0x3E 0x0A

and

Bytes: 0xF4 0x2F 0x3E 0x0A

To me this is an error from the building of the request in the [connect_vbms code](https://github.com/department-of-veterans-affairs/connect_vbms/blob/88c3b814729b25ae973e495a9c5db7bb7657df93/lib/vbms/requests/find_document_series_reference.rb)

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 8 months
