### ISSUE TITLE
Use either underscores or hyphens to seperate urls

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1149]
Right now in our URLs, we use underscores sometimes:

`https://appeals.cf.ds.va.gov/admin/establish_claim`

and hyphens sometimes:

`https://appeals.cf.ds.va.gov/dispatch/missing-decision`

We should pick a convention and stick with it. I think underscores might work better with the Rails magic, but might be good to investigate.

**Comment by kierachell** [comment]
**PASSED**

<img width="505" alt="screen shot 2017-03-29 at 12 12 26 pm" src="https://cloud.githubusercontent.com/assets/18075411/24464795/10449554-1479-11e7-987b-92f7359f4fcb.png">
