### ISSUE TITLE
Fix Caseflow timeline for canceled withdrawal of appeals tasks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11498]
A BVA user has canceled a withdrawal of appeal task (because it wasn't a withdrawal of appeal). In the Case Timeline, however, it looks like the mail task was both canceled and completed. 

![withdrawal of appeal](https://user-images.githubusercontent.com/27704093/61735829-bf4e1600-ad52-11e9-8c82-066483342b89.png)

https://appeals.cf.ds.va.gov/queue/appeals/dfe4db42-1792-487a-b343-dfb576a45ec0

## AC
- We should hide the task assigned to Mail team from Case Timeline
- We should mark the task assigned to Mail team as canceled, instead of completed

**Comment by Sjones352** [comment]
@laurjpeterson and @aroltsch I would like some clarity on this ticket. Once user cancels the AppealWithdrawalMailTask, are you saying that they should not be able to complete this task?

**Comment by laurjpeterson** [comment]
I think somehow there are 2 tasks that represent one single mail task, probably because of how our tasks work. Would need to confirm this in the code.

Here's how I think the process should look to or users: Veteran sends in mail --> Mail team user (M. WRIGHT, above) creates Withdrawal of appeal mail task that is auto-assigned to Case Review organization

Versus what might be happening: Mail team user (M. WRIGHT, above) creates Withdrawal of appeal mail task that is assigned to the Mail team --> then, a child task is created and auto-assigned to Case Review organization

If that's what is happening, I think we need to just (1) hide and then (2) mark as cancelled the task that was assigned to the Mail team. Let me know if that helps!

**Comment by aroltsch** [comment]
I don't think we should hide the task assigned to the Mail team because the fact that it was assigned to the mail team is accurate. I agree that the status should be cancelled for the mail team task.

**Comment by Sjones352** [comment]
@laurjpeterson do you want it to look like this? @aroltsch do you want this change to only apply to the AppealWithdrawalMailTask or would you rather I apply the change to all tasks. 
<img width="843" alt="Screen Shot 2019-07-30 at 7 21 10 PM" src="https://user-images.githubusercontent.com/23080951/62177282-5b0ef180-b312-11e9-8cf0-847803cd0c4d.png">

**Comment by aroltsch** [comment]
@Sjones352 the change to update a parent to a cancelled status, should go to the Task.rb model

**Comment by laurjpeterson** [comment]
Both tasks cancelled looks right to me!
