### ISSUE TITLE
Add modal to select correction type for 930s

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11495]
### Story
Corrections to end products can be regular corrections (such as those identified by the user), or the mistake can be discovered after the fact during local or national quality review.  We don't have a way to determine this automatically, so we are asking the user to identify the correction type.

### Acceptance criteria
- When a user corrects an existing issue, or adds a new correction issue, show a modal with a radio button that allows them to select the correction type.
- The correction type gets saved onto the new request issue that gets created in the database

### Copy
Title: 
Correction type

Modal text:
This issue will be added to a 930 EP for correction.  If a mistake was found during quality review, please select whether it was discovered by the local or national quality review team.  Otherwise, select control.

Display text for options:
- Control
- Local quality error
- National quality error

Values for options:
- control
- local_quality_error
- national_quality_error.

**Comment by jcq** [comment]
Should this modal also have a "Cancel" button to reset the status (if they chose "correct" on the wrong issue, for instance)?

**Comment by leikkisa** [comment]
@jcq Yes, that'd be good.

**Comment by jcq** [comment]
@leikkisa For the newly created correction issues, should we insert this modal into the chain when creating? Should it come at the end, and be the thing that ends up with the "Add this Issue" button? Or perhaps have it fire after that flow is finished and essentially update the (new) existing issue item?
