### ISSUE TITLE
VBMS NoSoapBody error

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11493]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/4811/events/405434/

Happening in the V2::SaveFileInS3Job.

The error is: `No SOAP body results found in response`, which looks like it leads to a `NoMethodError`:

```
NoMethodError

undefined method `to_xml' for nil:NilClass
Did you mean?  to_yaml
```

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 8 months
