### ISSUE TITLE
NoMethodError for nil class in S3Service

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11500]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/5849/events/405223/

Seeing this error in `V2::SaveFilesInS3Job`.

Looks like it might be related to creating a Tempfile, but I'm not totally sure since it looks like it's not providing the trace inside of `S3Service.store_file`.

```
NoMethodError

undefined method `close!' for nil:NilClass
```

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 8 months
