### ISSUE TITLE
NoMethodError app/controllers/sessions_controller.rb in update error undefined method `regional_office=' for nil:NilClass

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11507]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3698/events/406368/).

Ok still a fun one even though I read the error wrong in the first place. Has happened to one user 5 separate times.

**Comment by pkarman** [comment]
I wonder if that particular user has something amiss in their CSEM record?

**Comment by yoomlam** [comment]
Popped up again: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6909/
(https://dsva.slack.com/archives/C4JECDLSE/p1580237538068100)
`app/controllers/sessions_controller.rb in update at line 45`
`current_user` is nil.
