### ISSUE TITLE
Invariant Violation in UPDATE_EDITING_APPEAL_ISSUE

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11505]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3147/events/406002/).

Seems that `action.payload.attributes` is undefined. Did some digging and was unable to find a scenario where this would occur.

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 7 months
