### ISSUE TITLE
HearingRepository::HearingDayFullapp/repositories/hearing_repository.rb in create_caseflow_child_video_hearing

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11513]
[Sentry alert 1](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5869/) and [2](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3893/).

Should be be sending these to sentry or handling these errors within the app?

**Comment by alisan16** [comment]
This error hasn't been seen in 6 months. Closing.
