### ISSUE TITLE
NoMethodError in from_css_auth_hash

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11520]
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/5113/events/406407/

Looks like `auth_hash` can be `nil` in `app/models/css_authentication_session.rb`.

```
undefined method `extra' for nil:NilClass
```

**Comment by alisan16** [comment]
This error hasn't been seen in 7 months. Closing.
