### ISSUE TITLE
superagent/lib/client in method Not Found GET /appeals/<id>/hearings [404]

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11534]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5882)

Dug into these. Most of them are 404s caused by nil vacols records for 3 different appeals.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5882/events/407153/
GET /appeals/3620735/hearings [404]
```ruby
> LegacyAppeal.find_by(vacols_id: "3620735").case_record
=> nil
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5882/events/407184/
GET /appeals/3956771/hearings [404]
```ruby
> LegacyAppeal.find_by(vacols_id: "3956771").case_record
=> nil
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5882/events/407201/
GET /appeals/3896163/hearings [404]
```ruby
> LegacyAppeal.find_by(vacols_id: "3896163").case_record
=> nil
```

**Comment by pkarman** [comment]
It's a known issue that VACOLS cases may get removed, resulting in an orphaned `LegacyAppeal` record in Caseflow. So 404 is the proper response. We just need to handle it better.

**Comment by alisan16** [comment]
Closing this as future work to handle deleted VACOLS cases is being tracked in #12791
