### ISSUE TITLE
EP930s | Usability Testing

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#11540]
### Goals: 
To gain user feedback on the current EP930 flow

1. Validate the text "correct issue" is clear to users in the flow
2. Validate user is able to navigate selecting the type of correction
3. Validate user is able to understand a correction has been made
4. Validate a user is able to undo an EP930 correction, if needed
5. Understand if the user is able to differentiate between "correcting" an issue and "removing" an issue
6. Identify any pain points in the current flow

### Protocol: 
Due to time constraints, this will be 1-2 sessions with 1-3 users who are familiar with EP930s. The session will not be a click-through prototype; the team will demo the current flow and follow-up with questions for the users. 

### When user would select "correct issue"
1. If you had to begin the process to create an EP930 from this screen, can you tell me how you would proceed?
2. [If needs prompting] If you selected "select action", what do you think would happen?
3. *Select Action* Here you can see an action of "correct issue" - is this text clear to you? Do you think it should be something else? 
4. Was anything we just did unclear to you?

### When user would choose correction type
1. Are these correction types clear?
2. Is there anything else you would want or need to see at this step? 

### When "This issue will be added to a 930 EP for correction" text appears
1. Was it clear to you that this issue was added to a 930 EP?
2. Do you need anything else to immediately know that this happened?

### Undoing the correction
*Ask questions for this part first, then demo!*
1. If you wanted to undo correcting the issue, how would you proceed?
2. [if needs prompting - demo] - Did this make sense? Was there anything about this action that was confusing? 

### Correcting Issue vs Removing Issue
1. So in this list of issues, you see the option to "correct" an issue and "remove" an issue. Can you walk us through what you think the difference is?
2. [If unclear for user - probe: what do they think would make the most sense?]

*Demo the rest of the flow*

### Wrap-up/General
1. Overall, was there anything in this flow that was confusing for you?
2. If you had a magic wand, is there anything you would want to change in this flow to make your work easier?
3. Any other comments or questions?

**Comment by leikkisa** [comment]
We got some feedback from Colin that the "Number of issues changed" modal seems superfluous since the claim is already decided.  I think it's still serving it's original purpose, since the number of issues really has changed, but it might be good to ask users about that as well.

**Comment by carodew** [comment]
@rutvigupta-design when you're back (and not before!) can you provide an update on the status of this?

**Comment by rutvigupta-design** [comment]
@leikkisa should we keep this issue open?

**Comment by leikkisa** [comment]
@msj0nes Closing this ticket. We never did do usability testing but we did ask for feedback after the VBMS testing and it was positive.
