### ISSUE TITLE
Change `Edit Canceled` page copy for EP 930s

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11554]
If you go into a closed claim, when you select cancel, you get the below message. Since we determined that the way to access 930s wont be via an "edit in Caseflow" method on a closed claim, this should say something different. 

![image (18).png](https://images.zenhubusercontent.com/5a81eda04b5806bc2bc6a201/0197fead-043c-48d2-951a-1538b659661c)

## AC
- Change copy to read: 
(Header) Edit Canceled 
(Message Content) "No changes were made... Go to [Veteran/Claimant Name]'s claim (ID# XXXXXXXXX [link to case]) to review and edit."

**Comment by leikkisa** [comment]
It could say "Search for this Veteran's case in Caseflow to edit", or something along those lines, guiding the user to Case Search.

**Comment by carodew** [comment]
How hard would it be to just link to the veteran's case in caseflow so the user doesn't have to manually search for it, but just click a link to go there? Saves a few steps and removes the chance of human error.

**Comment by jimruggiero** [comment]
@pkarman Is this issue also related to #11970 ?

**Comment by pkarman** [comment]
I can include this change as part of #11970 sure -- it's a different page but similar files to touch.

**Comment by Sjones352** [comment]
@sally what would the title be? Go to `veteran.name's claim` or `veteran.fileNumber's claim`  is too repetitive in the same message. 
<img width="950" alt="Screen Shot 2019-09-09 at 7 24 31 PM" src="https://user-images.githubusercontent.com/23080951/64572968-7b7d9300-d337-11e9-9423-5aa9df98e7da.png">

**Comment by pkarman** [comment]
The text I am using in #11970 is `If needed, you can [correct issues]` with link on "correct issues".

**Comment by Sjones352** [comment]
Going to hold off on this one till #11970 is merged.

**Comment by jimruggiero** [comment]
@Sjones352 can you add a screenshot of the final version of this message to this ticket?

**Comment by Sjones352** [comment]
With cleared Ep
<img width="1186" alt="Screen Shot 2019-09-11 at 3 50 32 PM" src="https://user-images.githubusercontent.com/23080951/64736836-94ae4d00-d4b9-11e9-96f5-3b031deec376.png">

Without cleared Ep
<img width="984" alt="Screen Shot 2019-09-11 at 3 59 08 PM" src="https://user-images.githubusercontent.com/23080951/64736933-c58e8200-d4b9-11e9-8303-d9bb5c645127.png">
