### ISSUE TITLE
Give acting judges dropdown link to assign cases view

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11570]
#10719 unified the way we present queue dropdowns on the judge queue view to use organizations instead of the user's ID. However, one side effect of that change was acting judges no longer being presented with the dropdown if the person is identified as an acting judge in VACOLS but does not have a `JudgeTeam` on the Caseflow side (as discovered in #11567). This ticket exists to make it so that acting judges can navigate to the assign cases view in these circumstances.

## Acceptance criteria
* [ ] Acting judges are presented with a dropdown menu on their queue table view to visit the assign cases page.

**Comment by hschallhorn** [comment]
```
1 | ||||||||||
2 | ||
3 | 
5 | 
8 |
```
This PR should get release notes so notify Shawn when ready to merge.

**Comment by hschallhorn** [comment]
We ok with automatically creating a judge team for users that are a judge in vacols but don't have a judge team?

**Comment by lowellrex** [comment]
> We ok with automatically creating a judge team for users that are a judge in vacols but don't have a judge team?

Maybe. Could we make sure that we remove the `JudgeTeam` once the acting judge is no longer identified as such in VACOLS?

> Double checked vacols and we only have teams for users where `judge_in_vacols?` returns true

This may be because our temporary work-around to support acting judges has been to create `JudgeTeam`s for them. We should be able to identify those `JudgeTeam`s because they should not have any attorneys in them.
