### ISSUE TITLE
Feature Testing by Roles

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#11592]
We've found that it's often difficult to understand exactly how a type of use interacts with Caseflow. For the hearing apps, we have Hearing Coordinators, VLJs, Regional Office staff, and VSOs that all interact with the same sets of pages slightly differently. 

We'd like to experiment with reorganizing our feature tests around user roles rather than simply pages. We could either change the `/spec/feature/hearings` directory to either `<role_name>/<page>` or `<page>/<role_name>`. 

We think this would give folks who have not worked on hearings a better sense of how the app is used across roles while also allowing us to test specific use cases more thoroughly.

**Comment by lomaxap** [comment]
@tomas-nava did I capture what you were thinking here?

**Comment by tomas-nava** [comment]
yes, this is exactly what I had in mind!

**Comment by jimruggiero** [comment]
@lomaxap  - can you bring this up in Tech Leads to vet the idea with other teams and define who can/should do the work near-term?

**Comment by jimruggiero** [comment]
@lomaxap @rubaiyat22 @pshahVA With #11981, #12056 and 12083 now merged, can you clarify what scope remains on this specific ticket?

**Comment by chandracarney** [comment]
These changes involve too much comprehensive work throughout Caseflow so we will close this for now.
