### ISSUE TITLE
Route Claim | Hide ROJ routing notificaiton

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1160]
As a Caseworker, I only want to see the ROJ information on the `Route Claim - VACOLS Update` page when the ROJ is required to be updated so that I am not confused.

# Acceptance Criteria
1. Verify that when the ROJ is not changed, the ROJ update is not updated.
1. Verify that when the ROJ is not changed, the field _"Changed to ROJ"_ (item C.) is always hidden and not displayed.

## **Mocks**
_**Special Issue NOT requiring and ROJ Update**_
<img width="763" alt="screen shot 2017-03-10 at 9 15 50 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819643/193b0c70-05d7-11e7-9bd8-ad2fddf36954.png">

_**Special Issue requiring an ROJ Update**_
<img width="737" alt="screen shot 2017-03-10 at 9 25 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819727/220cc69e-05d8-11e7-84e9-e0f5118f1621.png">

## Technical notes
- We will need this in Dispatch V2, so it may not be best to completely delete it

# Related Stories
SPIKE: Can we change ROJ in VACOLS? #799
EP Creation | Create End Product | Change the VACOLS ROJ value #892

**Comment by kierachell** [comment]
**PASSED**
Not seeing RO in any case.

<img width="1009" alt="screen shot 2017-03-13 at 11 17 28 am" src="https://cloud.githubusercontent.com/assets/18075411/23861371/37a6d896-07e0-11e7-9108-7a1a1faadeea.png">

<img width="1024" alt="screen shot 2017-03-13 at 11 46 04 am" src="https://cloud.githubusercontent.com/assets/18075411/23862171/ba6ea860-07e2-11e7-8ba7-5058ef239dd7.png">
