### ISSUE TITLE
Motion to Vacate | User research to validate motion to vacate designs

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11603]
We want to validate the designs for motion to vacate with 1-2 motions attorneys and 2-3 decision attorneys. 

### Motions Attorneys
- [x] conducted 2 interviews
- [x] extract notes and organize for presentation
- [x] share with the team and review priorities -> dropped diagrams in the comments

### Decisions Attorneys
- [x] draft email 
- [x] reach out / schedule 2-3 decisions attorneys
- [x] conduct interviews
- [x] extract notes and organize for presentation
- [x] share with the team and review priorities

This issue is a subtask of #8547

**Comment by geronimoramos** [comment]
![MTVmotionsattorney#1](https://user-images.githubusercontent.com/49766982/62331336-7f80e000-b470-11e9-8346-1b98770060a7.png)

Stakeholder session #1 included research questions on their current process for motions to vacate and feedback/testing of the UI screens

**Comment by geronimoramos** [comment]
![MotionAttorneySession#2](https://user-images.githubusercontent.com/49766982/62569797-d9542200-b843-11e9-98c3-adfa449d90ff.png)

Stakeholder session 2 included research questions on their current process for motions to vacate and feedback/testing of the UI screens

🔑 **tl;dr**
- Existing screens for motions attorneys have been validated
- Identified key actions they'll need to carry out on Caseflow to complete complex MTV flows

**Comment by jimruggiero** [comment]
Moving into Design Backlog until attorney work is prioritized and/or Judges work is completed.

**Comment by msj0nes** [comment]
Can we close this ticket to indicate the work mentioned is already completed?
