### ISSUE TITLE
EP 930s: When editing claim issues for non veteran claimants, show veteran name

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11623]
UI improvement suggestion: When editing claim issues for non veteran claimants, display a row indicating who the claimant is, not just the veteran (so the user knows the EP 930 will be created for the right claimant)

## AC
- Add a row to the table in the UI
- Display Claimant name

**Comment by jimruggiero** [comment]
@Sjones352 can you add a screenshot to this ticket?

**Comment by Sjones352** [comment]
<img width="1014" alt="Screen Shot 2019-09-11 at 10 30 44 AM" src="https://user-images.githubusercontent.com/23080951/64706862-2e590880-d480-11e9-93a0-ead07e917d7d.png">
