### ISSUE TITLE
Extend the CaseflowJob class with Duration Report Option

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11626]
Extend the CaseflowJob class with the ability to record the runtime of the job and send it to DataDog.

Refactor the places we currently do this with this new class option.

[Existing implementations](https://github.com/department-of-veterans-affairs/caseflow/search?q=job_duration_seconds&unscoped_q=job_duration_seconds)

**Comment by hschallhorn** [comment]
```
1 | |||||||
2 | |||||
3 | 
5 | 
8 |
```
Add start time to parent class. Will only be utilized by the jobs that run `record_runtime`. Refactor testing might get hairy.
