### ISSUE TITLE
Review Decision | Second line of Special Issue names not aligned properly

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1162]
# Description
On the `Review Decision` page, the second line of Special Issue names are not aligned properly under first line.  The names should be indented and not run under the checkbox. 

_Expected Results_ 
- When a Special Issue title spans two lines, the second line of a special issue title is indented to start directly under the first letter of the first line.

**Environment:**
- [x] Production
- [x] UAT
- [x] Demo
- [x] Development

**Type of Bug:**
- [ ] Performance
- [X] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [X]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1
1. Click on the **_Establish next claim_** button on the `Caseworker Dashboard` page.
1. Scroll down to the Special Issue Category section.  Special Issues whose titles span 2 lines are not aligned properly.

## Screen shots
**_Current Styling_**
<img width="938" alt="screen shot 2017-03-10 at 8 41 24 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819292/33a48528-05d2-11e7-97e7-355fd63b8b6e.png">

**_Desired Styling_**
<img width="446" alt="screen shot 2017-03-10 at 8 42 57 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819299/464d5cd6-05d2-11e7-8c4f-070537bbf2d5.png">

# Related Stories
Decision Review | Special Issues | Show all issues regardless Decision Type #715

**Comment by kierachell** [comment]
Seems to be a non-issue
**IE11:**
<img width="485" alt="screen shot 2017-03-27 at 2 35 02 pm" src="https://cloud.githubusercontent.com/assets/18075411/24372090/d21eb3ce-12fa-11e7-86d9-3c54aceed068.png">
**Chrome:**
<img width="998" alt="screen shot 2017-03-27 at 2 35 42 pm" src="https://cloud.githubusercontent.com/assets/18075411/24372091/d226804a-12fa-11e7-9b14-9aa5215af3d7.png">
