### ISSUE TITLE
EP 930s | Correcting incorrect decisions via EP 930s

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11639]
# Background
Establishing EP 930s via Caseflow Intake generally encompasses 3 scenarios:
1. Users accidentally clear/complete an EP (when a decision has not yet been made)
2. Users miss an issue on the EP (when a decision has not yet been made)
3. Users made a mistake on a decision (e.g. granted an issue instead of denied)

#10009 encompassed scenarios 1 and 2. This ticket encompasses the third scenario

# User flow + stories
Bolded items are new engineering scope that needs to be estimated

### Scenario: a user identified a decision was incorrectly made, for example, they granted an issue instead of denying it.

1. Search in Caseflow (development complete)
    **- Enhancement requested: Show receipt date for the claim in search results** #11835 
1. Click link and navigate to Edit issues page (development complete)
1. Click Add issue
1. **Add issue screen shows view the previous decision's ratings - they are now "request issues" (engineering work)** #11836 
      - **Change logic to allow all decisions that are related to this claim to show as options to add to the 930**
      - **Change validation for these issues, so they can be added on a regular, originally intaken claim as well**
1. User can add the issue that needs new decision (development complete)
1. If missed issues as well as an incorrect decision, user can add missed issues (development complete)
1. Establish the 930 (development complete)

### Scenario: a user identified a decision was incorrectly made. For example, they DTA'd an issue instead of denying it. The DTA Supplemental Claim EP was not finalized and decided.
1. Same as above
1. **Ensure DTA supplemental claim EPs can be edited via 930s using above flow** #11837 
1. **When EP 930 was established, remove the incorrectly added issue from the DTA supplemental claim** #11838

**Comment by laurjpeterson** [comment]
This ticket was created so external teams could read this tech spec! Will move to define.

**Comment by jimruggiero** [comment]
Consolidated these requirements into original Epic #10009 to track all stories for all three parts in one place.
