### ISSUE TITLE
Write tech spec describing how to mark Caseflow users as inactive

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11631]
Rows in Caseflow's `users` table should never be deleted* from the database. This allows us to keep a record of users as long as the application lives. However, this practice of persisting `User` records in perpetuity presents some challenges with tasks. Two salient challenges are 1) people who are no longer working on Caseflow (perhaps because they are no longer employed at the VA or at a VSO) can still be assigned tasks and 2) we have no insight into how many active tasks are assigned to people who will never act on those tasks.

These challenges were identified in a [related Slack conversation](https://dsva.slack.com/archives/CHX8FMP28/p1564693034223000) and this ticket exists to explore how we can solve these problems and other problems that stem from the fact that we do not identify inactive Caseflow users.

## Acceptance criteria
* [x] Tech spec that outlines several possible paths forward for how to mark Caseflow users as inactive
* [x] Decision on how to proceed following discussion of the tech spec (which of the paths forward to implement)

Estimating this ticket at a 3 because that is our practice for all tickets where the end result is a tech spec.

*On rare occasions we have deleted rows from the `users` table. One example that comes to mind is [when we consolidated duplicate rows](https://github.com/department-of-veterans-affairs/caseflow/issues/9444) in that table.

**Comment by pkarman** [comment]
fwiw I'd vote for the "soft delete" approach we follow in `HearingDay` with the `acts_as_paranoid` gem. It has some drawbacks, but I would enjoy the consistency of it in the codebase.

**Comment by msj0nes** [comment]
Idea. If it ever boils down to a manual process where the Board has to notify us of staff leaving then it would be cool to have a ‘admin panel’ similar to ‘team management’ where we add the user/CSS ID. 

Adding the user/css ID to the listing would:
- Trigger the return of current cases assigned back to the assigning VLJ. 
- If the ex-attorney case is with admin before departure, the returned case from admin would go back to the VLJ. 
- A popup notification when users try to assign to these specific users. 

The VLJ from there makes the decision on what happens next.

**Comment by hschallhorn** [comment]
### Things we're trying to solve

1. Develop a way to determine if a user is inactive
2. Make sure tasks aren't assigned to inactive users
3. Develop a way to mark a user inactive
4. Handle tasks assigned to user when they become inactive (this is similar to when a user leaves an org, which we also don't handle) (may want to spin out to a different spec to keep this at a 3!)

### Possible Solutions

Add an `active` column to the user's table. When assigning tasks only show active users.  Add a uses management page to show all users and their status (in different sections or sorted by active/inactive) with the option to mark the inactive (or active again).

### What this solution would touch

1. Create a migration to add `active` column to the users table. Mark all users active.
2. Create a scope for users that only returns active users.
Places we would want to filter out inactive users:
 - task_action_repository/assign_to_user_data
 - any assignment that uses Judge.list_all (returns Users, so the scope should work)
 - any assignment that uses Attorney.list_all (returns Users, so the scope should work)
On task creation, validate that the assigned user is active. 
3. Create a new endpoint to manage all users. Users who can access this endpoint should be limited to members of the BVA admin team. Add option is users_controller to fetch all users (this should include both active and inactive users). Add endpoint to users_controller (not within organizations/users_controller) to update the active flag for that user. Add front end page that displays all users and their active status. Add button, confirmation, and success alert that hit the update user's active status endpoint.

### Other actions
Spin out ticket for 4.

**Comment by hschallhorn** [comment]
Compiling a list of places we may want to add an `active` scope to or validation that a user is active:
- task_action_repository.rb > in `users_to_options` as every place it is used would require active scoped users. If not:
  - All instances on `Judge.list_all`
  - All instances of `users`
  - All instances of `attorneys`
- controllers/users_controller.rb > every user returned assuming:
  - We are ok with hiding inactive attorneys in JudgeAssignTaskListView (these attorneys may have cases assigned to them until #11811 is addressed) (result of GET to /users?role=Attorney&judge_id=<judge_id>, which is also used for AssignedCasesPage and AssignWidget)
  - We don't need to lookup participant ids of inactive users in LookupParticipantIdModal
- controllers/organizations/users_controller.rb > returning remaining_users. returning organization_users assuming we are ok with
  -  not listing users of an org that are inactive (this would disallow admins from removing a user from an organization) (could also remove all team memberships when a user is made inactive)
- organization_user.rb > add validation that a user is active before `add_user_to_organization` and `make_user_admin`?
- bva_dispatch_task_distributor.rb > Should initialize with only active BvaDispatch users
- colocated_task_distributor.rb > Should initialize with only active BvaDispatch users
- pulac_cerullo.rb > I have no context on anything about PulacCerullo, but I assume users should also be scoped to active.

Wow bowing out for the day once I decided to look at `organization.users`. Other places I still had yet to glance at:
- organization.users
- signing in

Other finds:
 - [x] RoundRobinTaskAssigner concern is no longer used
 - [ ] Pretty positive we never send options to any of the `next_assignee`s

**Comment by laurjpeterson** [comment]
Next step is to create engineering tickets that spawn from this tech spec cc: @hschallhorn 

Proposed user flow: On Caseflow team management page, team admin searches for user and then marks them inactive.
