### ISSUE TITLE
Aug 9th (Fri) - Turn on edit contention text in prod

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11652]
We have approval from AMO to turn on the "edit_contention_text" feature toggle in Prod. The goal is for this to be turned on by August 12th, to be aligned with other VBMS-related release timing and add it to the same release notes.

It's probably best to turn this on later in the day.

**Comment by pkarman** [comment]
I manually merged https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2175 this morning but it won't be present till the next deploy (probably 8/13).
