### ISSUE TITLE
Implement Release Notes Using Headway App

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11656]
Related to #7954 
## Implement Headway App in production
- Please refer [product website](https://headwayapp.co)
- We will be implenting a widget as indicated in the screenshot
TODO: Add screen mockup
![image](https://user-images.githubusercontent.com/49729315/62488648-c46b8600-b792-11e9-8057-750998e43b01.png)
Note: mock up is concept only, not visual design. Just follow the preexisting Caseflow styles. ;) 

## Acceptance Criteria
- The Headway widget is visible in on the Caseflow app for all users of the application.
- Updates to the headway app are indicated on the widget.
 

## Notes
Contact @pshahVA to create an account to log into the administrator panel of Headway.

**Comment by carodew** [comment]
Given that it's just adding an additional option, I don't think we need a visual mock up. My one question is whether or not it's better here or in the footer near the other build info, but I don't have a strong opinion and given that we're light on designers right now this seems most viable. 

I checked our style guide to see if we had existing guidance on what kinds of links go into that dropdown, and we do, ish – http://www.caseflowdemo.com/styleguide#user-dropdown-menu

It seems appropriate given that guidance. My next question would be – what is the max number of options that would be visible to a user in that drop down? We usually want to cut that off at around seven options, give or take – beyond that it gets unwieldy. 

My next question would be, what does a user see when they click on that option? What happens?

**Comment by pshahVA** [comment]
Thanks for getting back to me.  I don't have a strong preference where it goes, but I wasn't sure from a design perspective, so thanks for confirming.  We can probably revisit this when someone asks to add more options into this task bar.  

This is a widget, so it would open a widget with what's new.
![image](https://user-images.githubusercontent.com/49729315/62545784-583f5f80-b830-11e9-854b-f55ac0dd2d0f.png)

**Comment by carodew** [comment]
Noting that this might flow better if it's a link out to Headway or the release notes, rather than a pop up, which might be a little unexpected for users. I'm happy to do a test click through and make a gut check on weirdness, but I wouldn't raise this to the level of usability testing.

**Comment by pshahVA** [comment]
There is a option to have it point to a page, and not have a widget.  The other option is that we move the link to the widget somewhere it isn't nested.

**Comment by carodew** [comment]
For now I recommend we have it point to a page.

**Comment by lomaxap** [comment]
The release log can be found here https://headwayapp.co/107401-va-updates

**Comment by pkarman** [comment]
the url on that log is `www.va.gov` which might mislead some folks.
