### ISSUE TITLE
Allow VSO Caseflow users to search for Legacy cases

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11650]
### Use Case
As a VSO user of Caseflow, I can see legacy cases in the daily docket.  I should be able to search for all cases that I see in my docket.

### Acceptance Criteria
- [ ] The search functionality across Caseflow should return results from Legacy cases, in addition to the AMA cases that it currently returns.

**Comment by lowellrex** [comment]
There is nothing immediately obvious in the code that should prevent this from working as we expect. Before we estimate or begin work on this ticket, can we get some examples of this failing? Two or three examples of 1) the VSO employee's CSS ID and 2) the URL they were trying to reach but not getting any results (something like `https://appeals.cf.ds.va.gov/search?veteran_ids=1989`)?

**Comment by pshahVA** [comment]
I only have one example so far. VBANASQUINL is the CSS ID.  When you look at the docket on 8/8/19, and then go to queue and search for the first veteran, it shows no results.

**Comment by lowellrex** [comment]
> I only have one example so far. VBANASQUINL is the CSS ID. When you look at the docket on 8/8/19, and then go to queue and search for the first veteran, it shows no results.

That user should be able to access the Veteran in question. This looks like a problem in our code. We'll estimate it!

```ruby
  rails c> veteran = Veteran.find(242423)
  rails c> vso_user = User.find(3910)
  rails c> RequestStore[:current_user] = vso_user
  rails c> BGSService.new.can_access?(veteran.file_number)
  # true
```

**Comment by hschallhorn** [comment]
```
1 | 
2 | |||
3 | ||||
5 | ||||
8 | |
```
Possible 2 if we immediately find the issue and it is an easy fix. Range of estimates based on the number of unknowns.

**Comment by hschallhorn** [comment]
All VSO tasks are `TrackVeteranTask`s ([looker](https://caseflow-looker.va.gov/sql/cbvvvk5v6gj9jm)).

**Comment by hschallhorn** [comment]
Doing some digging!
```ruby
# Grabbing someone we know has access to a veteran in BGS and is in a VSO
> u = User.find_by(css_id: "VACOWENDET")
> u.organizations.first.type
=> "Vso"

# Random task assigned to their VSO
> t = TrackVeteranTask.where(assigned_to: u.organizations.first, appeal_type: LegacyAppeal.name).last

# Let see if they have access to the veteran in BGS
> RequestStore[:current_user] = u
> BGSService.new.can_access?(t.appeal.veteran_file_number)
=> true

# Delightful. This means they should get search results back for this appeal. Lets double check
> result = CaseSearchResultsForVeteranFileNumber.new(file_number_or_ssn: t.appeal.veteran_file_number, user: u).call
> result.extra[:search_results][:appeals].any? || result.extra[:search_results][:claim_reviews].any?
=> true
# Great! This VSO user would rightly see the search results

# Lets check out the provided user and case
> u = User.find_by(css_id: "VBANASQUINL")
> u.organizations.first.type
=> "FieldVso"

# Let see if they have access to the veteran in BGS
> RequestStore[:current_user] = u
> v = Veteran.find(242423)
> BGSService.new.can_access?(v.file_number)
=> true

# Bueno. Lets look at the search results!
> result = CaseSearchResultsForVeteranFileNumber.new(file_number_or_ssn: v.file_number, user: u).call
> result.extra[:search_results][:appeals].any? || result.extra[:search_results][:claim_reviews].any?
=> false
# Uh oh

# Lets see if a normal user would see results for this veteran
> u = JudgeTeam.first.judge
> RequestStore[:current_user] = u
> BGSService.new.can_access?(v.file_number)
=> true
> result = CaseSearchResultsForVeteranFileNumber.new(file_number_or_ssn: v.file_number, user: u).call
> result.extra[:search_results][:appeals].any? || result.extra[:search_results][:claim_reviews].any?
=> true
# Curiouser and curiouser...
```

**Comment by hschallhorn** [comment]
For the veteran above, the search results for the judge returned an appeal, so let's look into [`AppealFinder`](https://github.com/department-of-veterans-affairs/caseflow/blob/2ee8ec755ac2478a2ebac16639d004aa92699719/app/workflows/case_search_results_for_veteran_file_number.rb#L15)! `AppealFinder` has two separate methods for when the user [is a vso employee](https://github.com/department-of-veterans-affairs/caseflow/blob/2ee8ec755ac2478a2ebac16639d004aa92699719/app/services/appeal_finder.rb#L49) and [when they are not](https://github.com/department-of-veterans-affairs/caseflow/blob/2ee8ec755ac2478a2ebac16639d004aa92699719/app/services/appeal_finder.rb#L27). Looking at `Veteran.accessible_appeals_for_poa`, it looks like we [only account for ama appeals](https://github.com/department-of-veterans-affairs/caseflow/blob/2ee8ec755ac2478a2ebac16639d004aa92699719/app/models/veteran.rb#L170)!

**Comment by lowellrex** [comment]
@stwards11 @pshahVA This will be released Monday (~11am) in case this needs to be communicated to VSO folks.

**Comment by pshahVA** [comment]
Thanks.  I'll let them know.
