### ISSUE TITLE
Refactor `TaskTable.jsx` file to be fewer than 400 lines.

### ISSUE THREAD

**Issue by kevmo** [department-of-veterans-affairs/caseflow#11657]
Currently we are disabling the max-lines-length ESlint checkin `TaskTable.jsx`.  Instead of doing that, refact this file to remove all of the pure functions into their own file, perhaps at `client/app/queue/components/TaskTableColumns.jsx`.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
      1 | ||
      2 | ||||||
      3 | |
      5 | 
      8 | 
```

Estimating at a 2. Fear and uncertainty for the possible 3. Possible easy solution for a 1.
