### ISSUE TITLE
Finalize wording on CES Survey

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11668]
## AC
- [x] all comments and feedback have been resolved
- [ ] we've reviewed this version with VA and gotten 👍🏽

**Comment by carodew** [comment]
Verified that all comments from the previous review have been resolved. @laurjpeterson we can probably move forward to review this with the VA, although if you'd rather wait until next week I can continue to flesh out the data analysis section of the research protocol. 

Wouldn't be a bad idea to have a second set of eyes go through [this version](https://www.surveymonkey.com/r/Preview/?sm=qrYXbhmPwRro81vRNdS7xGKxfoG_2BkrrWO4irudc6iZLrfaq5u_2BQHI11Z5PB_2B147K), just in case I introduced errors.

**Comment by carodew** [comment]
Note – we can also send them the link to the preview of the survey if we would rather go that route, however we should be clear that that is not the link that they'll need to send to the listserv, as it's just a preview and won't actually collect any responses.

**Comment by laurjpeterson** [comment]
I think reviewing with VA next week makes sense. Our main stakeholders at the Board, Jennifer White, is back this week, and I plan on meeting with her next week. I’ll take a look through the version you tagged.

I think we can send the preview as a read ahead before it’s discussed with her.

Would you like to meet her and present this? No expectation to, just sharing the opportunity if you would like it!

**Comment by laurjpeterson** [comment]
And by present, I mean discuss in an informal meeting. Not give a presentation.

**Comment by laurjpeterson** [comment]
Reviewed! I don't see any flags. It seems good to go to share with VA!

**Comment by carodew** [comment]
I'd be happy to meet with Jennifer White and talk through this next week.

**Comment by carodew** [comment]
Delayed update – JW objected to the categories in the first question, saying that some users could be in more than one group and that some branches/roles were not represented (but didn't go into details). I think that might be a result of mixing role and branch in one question. I'm loathe to add another question to the survey since each addition reduces the likelihood of folks filling it out. 

I don't have enough context to make corrections but I'm wondering if @laurjpeterson and I can sit down to hash out if we want to do role or branch, or both, and how to make that work. Will set up some time. Otherwise I think there were no other major correction.

Screenshot of the current options –  

![image](https://user-images.githubusercontent.com/10144074/64636066-fa71da80-d3ce-11e9-9e21-e923f4feb79a.png)

**Comment by carodew** [comment]
Here's how I'm interpreting the above in Survey Monkey, noting that we don't have the option to group checkmarks under headings so it looks slightly different – 

![image](https://user-images.githubusercontent.com/10144074/65072893-c7e05880-d95f-11e9-949c-ea29853530de.png)

**Comment by carodew** [comment]
@laurjpeterson if the above screenshot looks good to you, do you think we should schedule another meeting or is this something that would be better resolved via email? I kind of suspect the former but wanted to get your take since we're already asking for a chunk of time for other ventures.

**Comment by laurjpeterson** [comment]
That looks good to me! I think we should email Jennifer and John directing them to look at the survey preview, and offer a meeting time if they'd like to talk through it.

**Comment by carodew** [comment]
Per email thread, Jennifer seems ok with the survey (or at least has not objected) and will need to get it approved by leadership. Since this seems out of our hands for now, shall we mark this issue done but keep the epic open?

**Comment by laurjpeterson** [comment]
Yes, that sounds right
