### ISSUE TITLE
Determine and document how we want to analyze this data

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11672]
## AC 
- [x] we know how we want to analyze this data and it is documented in the [research protocol](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Project%20Folders/Caseflow%20Projects/CES-survey/readme.md)

**Comment by carodew** [comment]
@laurjpeterson I have most of this documented, however one of the things we wanted to track was if Caseflow got easier to use the more time a person spends using it. However, I don't think the original proposal for measuring this can actually be interpreted this way, since it involves comparing the CES responses across different user groups. The thinking is that since each group got access to Caseflow at different points, we could use that to see if it's getting easier over time. The convoluting variable is that these different user groups likely use Caseflow in different ways, which could impact the CES responses and we wouldn't be able to attribute it to changes over time (instead it could be explained as differences between groups). Unless I'm misunderstanding something, in which case I'm happy to chat it out. 

If that question was an internal learning goal, I suggest we strike that part of the data analysis for this survey and design a different research study to answer that question, if we still think that's a priority.

**Comment by laurjpeterson** [comment]
> The convoluting variable is that these different user groups likely use Caseflow in different ways, which could impact the CES responses and we wouldn't be able to attribute it to changes over time (instead it could be explained as differences between groups).
- I think this is true.

Could we measure getting easier over time _within_ user groups instead?

I read through your documentation - looks great! I think a mix of quantitative analysis plus follow up user research is the right way to go.

**Comment by carodew** [comment]
> Could we measure getting easier over time within user groups instead?
 
I believe so, yes. The main impact here is that we wouldn't be able to learn this from this first survey, but I think that's fine.
