### ISSUE TITLE
Sort queue by case type when attempting to sort by case type

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11687]
When somebody clicks on the icon to sort a queue table view by (case) type, [the application currently sorts](https://github.com/department-of-veterans-affairs/caseflow/blob/6e879c39eb3885c69a274a2f55cce3760d9c6040/client/app/queue/components/TaskTable.jsx#L163) by whether a case is AOD and then docket number. This ticket exists to sort by AOD, case type, then docket number. This ticket is for front-end work only. Back-end work will be done as part of #11315.

## Acceptance criteria
* [ ] Include case type in front-end sorting criteria after AOD and before docket number.

**Comment by hschallhorn** [comment]
```
1 | |||
2 | |||||||||
3 | 
5 | 
8 |
```
Fix appears to be pretty straightforward. May be complicated by testing and mocking legacy tasks. Please notify Shawn when this task is ready to merge.
