### ISSUE TITLE
Motion to Vacate Designs

### ISSUE THREAD

**Issue by geronimoramos** [department-of-veterans-affairs/caseflow#11683]
##### This is a subtask of #8547

Motion to Vacates touch 6 types of users:
1. When Motion to Vacates arrive to the Board as mail, the mail team processes them and then send them to the Lit Support team. 

2. Lit support leads then assign these motion mail items to their Motions Attorneys every 2 weeks who then check if these mail items are labeled correctly (Mail team often labels them incorrectly because 1) the mail items can be unclear/vague and 2) the mail team doesn't exactly have special legal training to identify these). 

3. Motions Attorney then carry out the Motion to Vacate process which includes:
- Checking the request for Motion to Vacate for validity - they're checking for due process errors committed by the Board or RO
- Assessing the likelihood of a grant or denial which carries out different processes

4. VLJs then receive the recommendation from the Motions Attorney and make their official decision on whether or not to GRANT or DENY any vacature

5. If any issues are granted, the VLJ send it to their drafting attorney for further processing

6. If denied all together, the VLJ signs a denial ruling letter and send it back to the Motions Attorney who then processes it and send it to the Dispatch team to go out to the Veterabn.

### Mail Team
- [ ] Investigate what their Queue looks like
### Lit Support Leads
- [x] They will be using the generic Litigation Support Team Queue
### Motions Attorneys
- [x] Selection Variation
- [x] Select Direct Issues Variation
- [x] MVP Generic Assign to Judge Variation
### VLJs
- [ ] Figure out from them HOW SPECFIC they want to receive recs from the Motions Attorneys
### Decisions Drafting Attorneys
- [ ] Figure out if the generic checkout flow works for them in re to MTVs
### Dispatch
- [ ] Investigate their Queue and adding Pulac-Cerullo check to them

### All users
- [ ] Add Pulac-Cerullo check banners to all Queues

#### General Design Workboard
https://va-gov.invisionapp.com/freehand/document/9uIQv1t5J

**Comment by geronimoramos** [comment]
### Motions Attorney Flow - Motions for vacate

![MTVmotionsattorneyflow.gif](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/344abb14-92be-438e-8b67-213929e5cf23)

##### Prototype link 
https://va-gov.invisionapp.com/d/main#/projects/prototypes/18207659
cc @jimruggiero

**Comment by carodew** [comment]
We've broken this issue down into multiple other issues, so this is now a duplicate and no longer needed.
