### ISSUE TITLE
Route Claim | Update VACOLS and VBMS | Remands/Partial Grants | Diary note text shows incorrect Decision Type

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1169]
# Description
When Routing Claim for a Remand/Partial decision type;
After selecting a Special Issue that required adding a Diary Note and/or VACOLS note;
I see that Decision Type written does not match the Decision Type for the case I am working on
*Expected behavior* to match the EP&Claim Label of the decision I am working on.

**Environment:**
- [ ] Production
- [X] UAT
- [x] Demo
- [ ] Development

# Reproduction Steps
Scenario 1 - Create an EP for Remand

1. Go to Dispatch

1. Click *Establish next claim*

1. Observe that the Decision Type you got is Remand/Partial Grant

1. Select a special issue that will result in some kind of VBMS note for anything

1. Click *Route claim*

1. Observe that the diary note text we display does not match the Decision Type from the page before

### Expected Behavior
- Note should match the Decision Type
**Add diary note** 

     > The BVA [Decision_Type] decision dated [Decision_Date] for [Veteran_FirstName] [Veteran_LastName], ID [Veteran_ID], was sent to the ARC but cannot be processed here, as it contains [Special_Issue_Category] in your jurisdiction. Please proceed with control and implementation of this grant.

     **VBMS Note**

     > The BVA [Decision_Type] decision dated [Decision_Date] for [Veteran_FirstName] [Veteran_LastName], ID [Veteran_ID], was sent to the ARC but cannot be processed here, as it contains [Special_Issue_Category] in your jurisdiction. Please proceed with control and implementation of this grant.

## Screenshots OF FUCKED UP BEHAVIOR WHICH IS NOT EXPECTED
**_Scenario 1 - Route Remand/Partial Claim_**
<img width="1018" alt="screen shot 2017-03-13 at 11 06 48 am" src="https://cloud.githubusercontent.com/assets/18075411/23862563/b82d5258-07e3-11e7-821c-8ef15a1bbd46.png">
<img width="1009" alt="screen shot 2017-03-13 at 11 17 28 am" src="https://cloud.githubusercontent.com/assets/18075411/23862564/b82e0e46-07e3-11e7-81ac-da016adf9525.png">
<img width="1024" alt="screen shot 2017-03-13 at 11 46 04 am" src="https://cloud.githubusercontent.com/assets/18075411/23862565/b82f675a-07e3-11e7-953f-b1aa4a205a18.png">

# Related Stories
Route Decision | Route Claim | Partial Grants & Remands with no EP | Change Location, Add Diary note #884

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate:
Scenario 1
1. Go to Dispatch as a caseworker and select establish a claim with a full grant. 
2. On the Review Decision page, select "Home Loan Guarantee" as the SIC
3. Validate the Route Claim Page matches mocks displayed in AC

Scenario 2
1. Go to Dispatch as a caseworker and select a establish a claim with a remand or partial grant. 
2. On the Review Decision page, select "Education Bill.." as the SIC
3. Validate the Route Claim Page matches mocks displayed in AC

Screenshots: 
 <img width="1027" alt="screen shot 2017-04-07 at 7 11 26 am" src="https://cloud.githubusercontent.com/assets/23038505/24797959/a7f23548-1b61-11e7-9052-884453a5c793.png">
<img width="1046" alt="screen shot 2017-04-07 at 7 11 43 am" src="https://cloud.githubusercontent.com/assets/23038505/24797960/a7f2b95a-1b61-11e7-8c0b-d0d8f1600e67.png">
<img width="1030" alt="screen shot 2017-04-07 at 7 15 17 am" src="https://cloud.githubusercontent.com/assets/23038505/24798081/2d3bf680-1b62-11e7-913a-992030f656f5.png">
![dispatchemailnotification](https://cloud.githubusercontent.com/assets/23038505/24798089/36997ab8-1b62-11e7-9c15-0cfd827cca9a.png)

**Comment by astewarttistatech** [comment]
**PASSED**

After selecting a second tier Special Issue for a partial grant, the claim was routed properly. Please see screenshots. 

Screenshots: 
<img width="1019" alt="screen shot 2017-04-07 at 8 55 05 am" src="https://cloud.githubusercontent.com/assets/23038505/24801179/149867b2-1b71-11e7-8c1f-7be26a82b401.png">
<img width="1016" alt="screen shot 2017-04-07 at 8 57 20 am" src="https://cloud.githubusercontent.com/assets/23038505/24801178/14943ca0-1b71-11e7-8d5a-285cba4c1cc5.png">
