### ISSUE TITLE
Attorney Fees | Intake users need the ability to add as an issue | Void

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11691]
[Add Attorney Fees.png](https://images.zenhubusercontent.com/5d2748c531297d7d65f8d26b/4c251054-ab3c-4335-854c-91038e598210)

POCs: 
- Brian Cannon 
- VLJ Scire

### User story: 
When Caseflow Intake users intake an appeal, they need the option to add attorney fees as an issue type in the current workflow, so they can properly intake these types of appeals.

## AC: 
1. Add the issue category "Attorney/Agent fees" in the "compensation" category, so that users can select it from the drop down on the 2nd (middle) screen as shown in above .png file, when adding issues. 
 - Assumption: This will be in-taken as a non-rating issue.
2. Caseflow can successfully handle non-dependent claimants. Backend work to build this capability will be tracked in issue XXX.
3. On the first Intake screen, when users select "Yes claimant is not the Veteran", add a radio button, displaying: 
- "[Attorney or Agent name - pulled from CorpDB via BGS], Attorney/Agent", OR
- (If no name is provided from CorpDB via BGS) "Attorney or Agent"
4. On Add non-rating issue screen, add "Denial of attorney or agent fees" as an Issue Category
5. The Denial of attorney or agent fees issue type is only associated with the Compensation benefit type
6. For SCs and HLRs, Caseflow will treat the claim from which the granted veteran/claimant benefit was awarded (and attorney fee generated) as the claim used to populate the claimant database and process these appeals (e.g. the claim ID of the awarded benefit is used to populate the claimant database)

Notes: 
- What happens after an attorney fee appeal gets a decision is out of scope. Current BVA guidance is that these appeals are very rare (two in the last two years) and their decisions being contested (on any claim type, including SC and HLR) is even more rare. If the ability to handle contested decisions becomes a requirement and is prioritized in the future, it will be scoped as an enhancement at that time. 

## Resource: 
All current issue categories are here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/ISSUE_CATEGORIES.json

**Comment by leikkisa** [comment]
@jimruggiero This definitely wouldn't be a rating issue, so I suppose non-rating issues is the proper place.

In this case the attorney represents a different claimant, since they'd presumably be the ones receiving the check.  We don't currently handle non-dependent claimants.  Also for SCs and HLRs, a claimant has to have a previous claim in order to be in the claimant database... so I guess the previous claim would be the original attorney fee something or other.

For appeals, maybe they could handle the attorney as a claimant on an issue like this in their business process.  Then there's what happens after it gets a decision (it becomes contestable on an SC).

Just adding this category to non-rating issues is super easy, so I would estimate a 1.  Jennifer will definitely know more about everything else I noted above!  Those are things I don't feel ready to estimate.

**Comment by jimruggiero** [comment]
Got it. Very helpful! More to come soon. Stay tuned!

**Comment by jimruggiero** [comment]
Additional resource here: https://app.mural.co/t/workqueue2001/m/workqueue2001/1542655242638/5629820b4b2c34a158c9dd7abb78137d0f9b8b74

**Comment by jimruggiero** [comment]
Upon further team discussion on 9/5/2019, this item was deemed an epic because the requirement to ensure nothing related to these appeals surfaces to veteran's, their representatives, appellants or other claimants in any way, requires ENG to draft a tech spec that identifies all of the touch points in intake workflows that surface data to others beyond the attorney or agent claimant. From this research, new tickets and context will be added accordingly.

**Comment by msj0nes** [comment]
# Tech Debt Reminder

What happens after an attorney fee appeal gets a decision is out of scope. Current BVA guidance is that these appeals are very rare (two in the last two years) and their decisions being contested (on any claim type, including SC and HLR) is even more rare. If the ability to handle contested decisions becomes a requirement and is prioritized in the future, it will be scoped as an enhancement at that time.

**Comment by msj0nes** [comment]
# Ticket Closure
The path for attorney fees has changed from this initial request. Changes to the requirement can be followed in #13505
