### ISSUE TITLE
Case Timeline Shows Incorrect Claims Status

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11705]
### Problem: 
Some claims are showing incorrect status in caseflow.  If something has an "A" disposition in VACOLS, that means that the Veteran filed an appeal, but VBA granted it in full before it reached the Board. So appeals with an "A" disposition never get to the Board, and should never display as having a Board decision, or as having a pending VA Form 9.

### AC:
The text should not show that there is a pending VA Form 9, and also not indicate that it was dispatched by the Board as it never actually got to the board.

One example of an appeal that has this error: 
https://appeals.cf.ds.va.gov/queue/appeals/2364226

![image](https://user-images.githubusercontent.com/49729315/62889384-474e8c80-bd0f-11e9-8fa8-0b9564076453.png)

Vacols screenshot:
![image](https://user-images.githubusercontent.com/49729315/62889341-29812780-bd0f-11e9-853e-c8b2b0dc5806.png)

**Comment by pshahVA** [comment]
Can we also let us know how many appeals are effected when the investigation continues.

**Comment by pshahVA** [comment]
@lowellrex, I talked to @lomaxap, and he stated this is an issue that can best be handled by echo.   I can give more details if needed.

**Comment by kevmo** [comment]
1 | 
2 | |
3 | ||||
5 | |||||||
8 |

5.  Potential 2 - if all we want to do is ensure that we don't show _wrong_ info, fairly straightforward. If we need to interrogate VACOLS, potential 5.  Team leaning towards 5.  No logic behind what the disposition of the case is on the frontend --> quite a bit to potentially implement.

**Comment by araposo-tistatech** [comment]
@hschallhorn is there a way to determine if this issue is still occurring?

**Comment by hschallhorn** [comment]
We haven't made any changes around this, so I assume it is still occurring.
