### ISSUE TITLE
Motions to vacate: allow motions attorney to write a deny or withdraw/dismiss recommendation

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11722]
## User story

As a motions attorney, once I've determined that a motions task is a motion to vacate and it's not valid, I write a recommendation to either deny or withdraw/dismiss the motion and send it to the VLJ.

## AC 
- Pulac Cerullo reminder

## Design
Prototype: https://va-gov.invisionapp.com/d/main#/projects/prototypes/18207659

**Comment by carodew** [comment]
@geronimoramos will add the link to the eng ticket for this work and close this ticket.

**Comment by geronimoramos** [comment]
Eng ticket #11252
