### ISSUE TITLE
Motions to vacate: allow motions attorneys to upload dismissal letter and send to dispatch

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11725]
## User story

As a motions attorney, when I receive a deny or withdraw/dismiss decision back from a VLJ on a motion to vacate, I need to upload a dismissal letter and send that to dispatch. 

## Context

- Motions attorneys will upload the deny or withdraw/dismiss letter to VBMS, so we don't need to build upload/storage functionality in Caseflow for this. They just mark it `ready for dispatch`. This work is mostly about asking some questions about process to find out what the flow should be, then incorporating that into designs. 

## Outstanding questions
- Would motions attorneys be passing over the hyperlink in Caseflow to the decision document to dispatch? Would dispatch have access to the folders? 
- Where does dispatch pull this document from? 
- Is this document going to be accessible from Reader? (we think so) 

## AC 
- [ ] Pulac Cerrulo reminder

**Comment by leikkisa** [comment]
I'm checking if this ticket is still relevant, because I think the latest guidance is that dismissal letters do not need to be sent to dispatch.

**Comment by rutvigupta-design** [comment]
@leikkisa correct, this ticket isn't relevant anymore because Motions Attorneys will upload the dismissal letters to VBMS and send them out to the veteran.
