### ISSUE TITLE
Motion to Vacate | Motions attorney relabels type of motion | Change Task Type

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11721]
## User story

As a **motions attorney**, if the mail team has labeled a motion wrong (for example, a motion to reconsider that should be a motion to vacate), I need to relabel it correctly so it can be correctly processed. 

## Context
Designs exist for this already, it's just changing the task type. We just need to understand their process for changing motion labels, see outstanding questions below. We know there are about 10 types of motions / motion labels. We're not supporting all the different types of motions in Caseflow right now. 

## Design/research work 

- [ ] Confirm where we need to go with this with Lit Support team leads. 
- [ ] TBD based on above

## Outstanding questions 

- [ ] - What systems need to be updated? 
- [ ] - Who needs to be notified that the document is mislabeled? 
- [ ] - Once sent to the VLJ, does the task stay in their queue on hold, or does it disappear? 
- [ ] - Do we have backend components in place to build this today, or no? If no, what's needed?

## AC 

- [ ] Pulac-cerrulo reminder

## Scope 

- [ ] This only includes motions to vacate, motions to reconsider, and Clear and Unmistakable Error (CUE). This does not include other types of motions.

**Comment by jimruggiero** [comment]
@geronimoramos to connect with @laurjpeterson to connect on scope of intended motions types for this ticket. Additional motions types will be research under separate tickets at the appropriate time.

**Comment by laurjpeterson** [comment]
What do you both think of the behavior for them to first cancel the wrong motion task, then add the new, correct motion task? That functionality exists today. 

The action to change task type also exists for MailTasks!

**Comment by carodew** [comment]
@laurjpeterson @geronimoramos – IIRC, the question is more about what types of motions we should allow a motions attorney to be able to relabel the motion as, given that we're not going to have the functionality to process all the different types of motions out of the gate. For example, if we release Motions to Vacate first, and an attorney comes across something labeled `motion to vacate` that really is more a `motion to reconsider` – do we allow them to relabel that in Caseflow when they'll still have to process that motion in another system (VACOLs I think?). Does that make sense?

**Comment by laurjpeterson** [comment]
I think we can allow the users to change task type to any of the motions, and they just become the mail tasks, because they already exist in Caseflow. 

E.g. MotionToVacateMailTask --> MotionForReconsiderationMailTask

It's ok that the motions tasks exist in Caseflow, even if the work they do is outside of Caseflow. They could just mark the task complete in Caseflow when that work is done outside of Caseflow.

**Comment by msj0nes** [comment]
# Ticket Closure

Closing ticket. This functionality is already available. 
![image](https://user-images.githubusercontent.com/41164406/73817638-7b37d580-47b9-11ea-92fc-fdceafcdc055.png)
