### ISSUE TITLE
Motions to vacate: allow VLJs to deny or withdraw/dismiss a motion to vacate

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11724]
## User story

As a VLJ, when I receive a motions task with a recommendation from a motions attorney, I review that decision and decide whether to deny or withdraw/dismiss a vacate. 
- review recommendation
- review draft
- sign it
- return to motions att

## Outstanding questions

- [ ] What does the judge see? 
- [ ] Do we also have to track and report on what the initial motions att recommended? We don't think so. Do the people monitoring their work care? probably not.
- [ ] How would they like to receive the deny withdraw/dismiss recommendation from the motions attorney? 

## AC 

- [ ] Pulac Cerullo reminder

## Related 
#11723 – other VLJ MTV user story

**Comment by carodew** [comment]
This story needs some usability testing as well, to be rolled into the usability study supporting #11723

**Comment by leikkisa** [comment]
@rutvigupta-design Can this issue be closed? I believe the deny/dismiss/withdraw workflow is complete.

**Comment by rutvigupta-design** [comment]
@leikkisa yes this can be closed!
