### ISSUE TITLE
Motions to vacate:  As a dispatch worker, when I receive a ruling that a motion to vacate is denied/withdrawn? 

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11727]
## User story 

As a dispatch worker, when I receive a ruling from a decisions attorney that a Veteran's motion to vacate is denied/withdrawn , I ... ??? 

## Oustanding questions 

- [ ] what do they do? 
- [ ] What data is involved? What systems?

## AC 
- ???

**Comment by carodew** [comment]
Duplicate!

**Comment by carodew** [comment]
I'm reopening this to repurpose as a withdraw/deny ruling, which we do need.

**Comment by carodew** [comment]
To be defined by #11830

**Comment by leikkisa** [comment]
I think this is obsolete now that deny/withdrawn don't go to dispatch and can be closed.

**Comment by rutvigupta-design** [comment]
@leikkisa agreed!
