### ISSUE TITLE
User research study | mail team's workflow

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11720]
## User story

As a mail team member, when I receive a Motion to Vacate letter, I need to process that letter and send it to the Lit Support team so they can address it.  

## Design/research work
- [ ] Reach out to a few mail team people who can help us find answers to the outstanding questions. 
- [ ] Create research plan + discussion guide
- [ ] The findings from this issue may result in additional issue to support any design work that may be needed. 

## Outstanding questions 
- In what system is mail labeling things as motions to [vacate, reconsider, etc.]? What systems need to be able to ingest this information? 
- What is mail's thought process to categorize motions? How many on average do they get, what do timelines for evaluation look like? What else are they doing?
- Why is the mail room categorizing motions anyway instead of processing what they can, and leaving it to Lit Support to categorize the type of motion? Is this a result of a software constraint or is there a legitimate business reason (if the former, can we remove that constraint and come up with a better solution?) (@jimruggiero to take point on this question) 

## Acceptance criteria
- tbd

**Comment by carodew** [comment]
@rutvigupta-design we added some bullets for what we _think_ needs to happen with this issue, but you should feel free to edit or revise based on your understanding.

**Comment by leikkisa** [comment]
I think this ticket is dated after the VacateMotionMailTask was created, so I'm not sure if this ticket means there is additional work needed.

However, currently there is an action that mail team members can take to start the motion to vacate flow, so part of me thinks this is complete.

**Comment by rutvigupta-design** [comment]
@leikkisa I'd like to keep this open for us to research further. It's out of scope for current MTV work but I think it can help shed light on the Mail Team's process for future motions.

**Comment by rutvigupta-design** [comment]
Closing for now. Will potentially revisit the need to research and understand this user group in the future.
