### ISSUE TITLE
Motions to vacate: allow VLJs to review recommendations on motions to vacate and grant a vacate

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11723]
## User story

As a VLJ, when I receive a motions task with a recommendation from a motions attorney, I review that decision and decide whether to grant a vacate. 
- review recommendation
- review MTV
- choose grant or partial vacatur and vacate type
- add instructions for issues to vacate
- assign to original drafting attorney

## Outstanding questions

- [x] What part of the motions attorney's recommendation does the judge see?
- [x] How would they like to receive the grant recommendation from the motions attorney? 
- [x] Do we need to track and report on what the initial motions attorney recommended? Do people monitoring their work care? 
    (we think not) 

## Design in Progress
https://www.figma.com/proto/GCRmxv1kWxPgLV8ipgD5RJ/VLJ-Flow-with-Actual-Screens?node-id=0%3A229&viewport=103%2C231%2C0.09255273640155792&scaling=min-zoom

## AC 

- [x] Pulac-cerrulo reminder

**Comment by carodew** [comment]
Relates to #10325

**Comment by carodew** [comment]
@jimruggiero – we feel that the current prototype is pretty close to what we believe will be the final design. We feel we need to do one round of lightweight usability testing on a clickable prototype to better test the interaction design and any gaps, which can be done in this upcoming sprint. 

There are parts of this that still need some research and definition – 
- Difference between straight vacate and re-adjudication, and vacate and de novo
- What happens in the back-end in these two types of vacates? how much is logged in the system? 

Leaving this comment as a placeholder for a conversation about paths forward.

**Comment by geronimoramos** [comment]
![VLJ_grant_sep16.gif](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/2a0763c1-0c08-46fb-bb3f-4a9811596b22)

design as of Sep 16th, 2019

**Comment by leikkisa** [comment]
@geronimoramos I think this is done too - so it can probably be closed (woo!)
