### ISSUE TITLE
Motion to vacate dismissals and denials | Connect frontend and backend for judges to log motions to vacate decisions

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11739]
When judges deny or dismiss a Motion to Vacate, the Motions Attorney receives the case back to outcode and dispatch. We'll do this by logging the judge Motion to Vacate disposition (grant/den/dismiss) and sending the task back to the assigning Motions Attorney.

## AC
- Connect frontend and backend 
   - Front end ticket: #10325
   - Back end ticket: #11707 
- When judges dismiss or denies a motion to vacate, judge motion to vacate (MTV) task is completed and the motions attorney's previous task is put in-progress 

## Out of scope
- Granted motions to vacate - covered in #11253

**Comment by aroltsch** [comment]
There is a WIP in progress PR that should be picked up by another engineer.

**Comment by aroltsch** [comment]
TODO items:

Create attorney tasks if motion is granted
Return task to the motions attorney if motion is not granted
