### ISSUE TITLE
create Higher Level Review API endpoint happy path

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/caseflow#11734]
The happy path is the first iteration on an endpoint for creating higher level reviews via the decision review API.

## Notes on Request Issues
The Higher Level Review Processor takes in request issues in this shape (to both conform to the JSON:API standard and insulate the API consumer from implementation detail):
```
{
  type: "RequestIssue"
    attributes: {
      notes
      decisionIssueId
      ratingIssueId
      legacyAppealId
      legacyAppealIssueId
      category
      decisionDate
      decisionText
    }
  }  
}
```
And transforms them to this shape:
```
{
  notes
  contested_decision_issue_id
  rating_issue_reference_id
  vacols_id
  vacols_sequence_id
  nonrating_issue_category
  decision_date
  decision_text
}
```
(as an ActionController::Parameter) to be consumed by the _complete_ step of the IntakesController.
### Request Issues Approach In-Depth
A request issues may have these attributes:
```
  notes
  decisionIssueId
  ratingIssueId
  legacyAppealId
  legacyAppealIssueId
  category
  decisionDate
  decisionText
```
some of these keys will be (ultimately) transformed:
```
  notes
  decisionIssueId       -> contested_decision_issue_id
  ratingIssueId         -> contested_rating_issue_reference_id
  legacyAppealId        -> vacols_id
  legacyAppealIssueId   -> vacols_sequence_id
  category              -> nonrating_issue_category
  decisionDate
  decisionText
```

All fields are expected to be strings, except for `decisionIssueId` and `legacyAppealIssueId` which can be either a string or an integer (this is an implementation detail. The spec will state that `decisionIssueId` and `legacyAppealIssueId` should be integers).

**Rules:**
(below, _present_ and _blank_ mean the Rails definition of `present?` and `blank?`)

1) No field is required, and therefore not all keys need to be present, but there must be at least one non-blank field. A _blank_ field is treated the same as a field not being included at all.

2) Either both `legacyAppealId` and `legacyAppealIssueId` must be _present_, or both _blank_.

3) If both `legacyAppealId` and `legacyAppealIssueId` are _present_, `legacy_opt_in_approved` must be `true`. _**(For the happy path, `legacy_opt_in_approved` is always true.)**_

4) If `decisionIssueId`, `ratingIssueId`, `legacyAppealId`, `legacyAppealIssueId`, and `category` are all _blank_, the request issue will have `is_unidentified: true`. 

5) Category must be either be A) valid for the specified benefit type or B) _blank_.

6) _**(temporary rule for the happy path)**_ Request issues without any id (decision, rating, legacy, etc.) are invalid.

Beyond this, validation is done by the existing models, validators, etc. Error codes and exceptions are bubbled up to the API consumer in a manner as consistent as possible with how the `IntakesController` behaves.

**Comment by edmangimelli** [comment]
updating this for:
https://dsva.slack.com/archives/C754H751T/p1565635018156500?thread_ts=1565619969.154900&cid=C754H751T
and the thread for this comment:
https://dsva.slack.com/archives/C754H751T/p1565619958154700

**Comment by leikkisa** [comment]
This is nice and easy to understand :-).  

Whether the veteran requests a timeliness exemption is missing. I'm not sure if there is a policy requirement to allow it, but I could see just setting it to false.

Whether a decision was from a RAMP issue also impacts timeliness.  We determine this from the ramp_claim_id on the rating issue.  This is something that can be done in the backend, but right now the code is not set up to handle it that way.

**Comment by edmangimelli** [comment]
@leikkisa 
>This is nice and easy to understand :-).

Yay! 🎉

re: Ramp issues and timeliness:

So, my gut feeling is that maybe we could consider those as outside the scope of the happy path, and come back to them (_Me_ limit the scope of the happy path? lol). That being said, would a veteran ever _not_ want the timeliness exemption? If getting an exemption to be able to include an ineligible issue is as simple as checking a checkbox, wouldn't every veteran just say "Yes."? Could we set the timeliness exemption to always true?

**Comment by pkarman** [comment]
Agree with @leikkisa this is nice and clear.

Also agree about ignoring RAMP and timeliness for this phase.
