### ISSUE TITLE
Form 8 is still viewable w/o user role selected

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1174]
**Description:**
In UAT, logged on as any of the SSO users, the caseworker can navigate to form 8, as to certify an appeal without having had select the certify appeal user role. 

**Expected:** User should have to select a user role corresponding to the function they are trying to do from the "/functions" page before being able to view user-specific pages. User should generally view an error page upon accessing a page without a user role selected. 

**Environment Found:** UAT
**Browser Found:** FF and Chrome

**Steps to Recreate:**
1. Access https://certification.cf.uat.ds.va.gov/certifications/new/2765717
2. Upon CSS prompt, log in with any of the SSO credentials that is not CASEFLOW1.
3.Upon successful sign in, view that the form 8 is visible. 
4. Go to the /functions page to see that none of the user roles are selected
5. Go back to form8 to see that it is still visible

**Screenshots:**
![caseflow certify](https://cloud.githubusercontent.com/assets/23038505/23870645/764b161c-07fd-11e7-91ea-c80c7993ee63.png)

**Associated Issues/Stories:**
**Reported by:** Artem Vovk

**Comment by laurjpeterson** [comment]
Closing, because this ticket is related to Caseflow Certifiacation v1, and we launched v2 fully at end of August 2017.
