### ISSUE TITLE
Add intake user/timestamp to decision review edit page

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11758]
It would help coordinate intake folks if the user who completed the intake were displayed at the top of the edit decision review page.

Background: https://dsva.slack.com/archives/CHX8FMP28/p1565371657304600

## AC

* [x] "Intake completed by <css_id> at <completed_at>" added to the top of the edit page.

**Comment by carodew** [comment]
@pkarman I'm going to bounce this to new ideas for the product team to triage, flesh out, and assign a priority. That said, it sounds like a pretty light design lift.

**Comment by pkarman** [comment]
I started implementing this in #11970 as part of a larger effort. Screenshot in that PR. Happy to change based on design ideas.

**Comment by carodew** [comment]
@pkarman aha, ye olde "You waited too long so I did it anyway" ... no worries! I just have a couple questions that I'll add to the PR if that's ok with you.
