### ISSUE TITLE
Cache job is not updating appeal attributes table

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11756]
[Looker](https://caseflow-looker.va.gov/sql/kh4b6chnwbrdkk)

**Comment by hschallhorn** [comment]
Looks all of the `nil` values for `Appeal`s are due to there not being any open tasks. I assume these `CachedAppeal`s were created when there was an open task, but were not caught when the job was updated with the new attributes because the tasks have since been closed.
```ruby
> CachedAppeal.count
=> 138938
> CachedAppeal.where(issue_count: nil).count
=> 281
> CachedAppeal.where(issue_count: nil).group(:appeal_type).count
=> {"Appeal"=>132, "LegacyAppeal"=>149}
> appeal_ids = CachedAppeal.where(issue_count: nil, appeal_type: Appeal.name).pluck(:appeal_id)
> Task.where(appeal_id: appeal_ids, appeal_type: Appeal.name).open.count
=> 0
```

**Comment by hschallhorn** [comment]
For the `LegacyAppeal`s, it appears that there is not corresponding VACOLS record so we are not able to grab the veteran record or issues
```ruby
> legacy_appeal_ids = CachedAppeal.where(veteran_name: nil, appeal_type: LegacyAppeal.name).pluck(:appeal_id)
> Task.where(appeal_id: legacy_appeal_ids, appeal_type: LegacyAppeal.name).open.count
=> 163
> vacols_ids = CachedAppeal.where(veteran_name: nil, appeal_type: LegacyAppeal.name).pluck(:vacols_id)
> VACOLS::Folder.where(ticknum: vacols_ids).count
=> 0
```

**Comment by lowellrex** [comment]
It appears as if there is a significant replication delay between the database Looker reads from and the master production database that caused us to believe this was a problem. https://dsva.slack.com/archives/CAM9FJ85P/p1565716203089900
