### ISSUE TITLE
Do not create decision review task unless there are eligible request issues

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11754]
Non-comp LOBs get a DecisionReviewTask created automatically. We should not create one if there are zero eligible request issues on the decision review.

## Tech note

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/claim_review.rb#L267

**Comment by leikkisa** [comment]
I think this got fixed incidentally in this PR, or maybe even before.
https://github.com/department-of-veterans-affairs/caseflow/pull/13061/files

I confirmed that a task is not being created with a Fiduciary HLR with only ineligible request issues.

Closing.
