### ISSUE TITLE
Migrate Caseflow to use VBMS eFolder Service Version 1

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#1176]

**Comment by kierachell** [comment]
### Certification
- Upload Document: BFKEY: 2765716 BFCORLID: 516517690
- Upload Document: BFKEY: 2765717 BFCORLID: 516517678
https://10.236.66.247/sentry/caseflow-uat/issues/176/
```
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><fault$
ode>env:Server</faultcode><faultstring>Business Errors GUID: ee3edaeb-136b-4cee-842d-df3cd725a943</faultstring><detail><efc:EFolderFault xmlns:part="http://vbms.vba.va.gov/cdm/participant/v4" xmlns:efu="http://service.efolder.vbms.vba$
va.gov/eFolderUploadService" xmlns:efc="http://service.efolder.vbms.vba.va.gov/common" xmlns:doc="http://vbms.vba.va.gov/cdm/document/v5" xmlns:com="http://vbms.vba.va.gov/cdm/common/v4"><efc:code>EFSERR1013</efc:code><efc:message>Doc$
ment already uploaded.</efc:message><efc:type>Business</efc:type><efc:uuid>ee3edaeb-136b-4cee-842d-df3cd725a943</efc:uuid></efc:EFolderFault></detail></env:Fault></env:Body></env:Envelope>
```

**Comment by kierachell** [comment]
It will be helpful to add a timestamp or some kind of `GUID` to the filename to avoid name clashes.

**Comment by kierachell** [comment]
**PASSED**
<img width="1141" alt="screen shot 2017-04-13 at 9 36 30 am" src="https://cloud.githubusercontent.com/assets/18075411/25007064/14818e14-202d-11e7-9669-67d10a4b7031.png">
uploaded 2 form 8s!

<img width="1412" alt="screen shot 2017-04-13 at 9 39 42 am" src="https://cloud.githubusercontent.com/assets/18075411/25007085/25c5afe8-202d-11e7-92f4-dca836ad3814.png">


EP created:
<img width="1061" alt="screen shot 2017-04-13 at 9 40 35 am" src="https://cloud.githubusercontent.com/assets/18075411/25007112/45dae1e0-202d-11e7-857f-b2777ccae602.png">
