### ISSUE TITLE
Judges cannot assign draft decision tasks to acting judges

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11761]
When judges attempt to assign draft decision `AttorneyTask`s to attorneys who are acting as judges, the application instead reassigns the `JudgeAssignTask`. This ticket exists to fix this bug and allow judges to assign draft decision `AttorneyTask`s to attorneys who are acting as judges.

![image](https://user-images.githubusercontent.com/32683958/62972791-d678a480-bde2-11e9-8b89-d0ba99791e92.png)

## Steps to reproduce locally
* Add an acting judge to AABSHIRE's judge team.
```ruby
rails c> judge = User.find_by(css_id: "BVAAABSHIRE")
rails c> atty = FactoryBot.create(:user, css_id: "BVALODELL", full_name: "Lorena Odell")
rails c> vacols_atty = FactoryBot.create(:staff, :attorney_judge_role, user: atty)
rails c> OrganizationsUser.add_user_to_organization(atty, JudgeTeam.for_judge(judge))
rails c> JudgeTeam.create_for_judge(atty)
```
* Attempt to assign a case to this new attorney through either the judge assign cases view or the case details page and observe that we instead reassigned the `JudgeAssignTask`.

## Acceptance criteria
* [ ] Judges can assign draft decision `AttorneyTask`s to attorneys who are acting judges
* [ ] Judges can still transfer `JudgeAssignTask`s to other judges on the case details page and through the judge assign view

**Comment by lowellrex** [comment]
This appears to have been caused by acting judges being given `JudgeTeam`s as a workaround until #11570 was completed. Now that #11570 is live in production we can remove the `JudgeTeam`s for attorneys acting as judges and they should be able to properly receive draft decision `AttorneyTask`s instead of `JudgeAssignTask`s.

We uncovered another problem here though, that needs to be addressed before we move the identification of acting judges in Caseflow: [the `JudgeAssignTasksController` determines](https://github.com/department-of-veterans-affairs/caseflow/blob/4de6c96e2c293cedcfa3c9ef2480fae310f232e6/app/controllers/judge_assign_tasks_controller.rb#L24) whether we reassign `JudgeAssignTask`s or create `AttorneyTask`s without any way to control that behaviour on the front-end.

**Comment by kevmo** [comment]
1 |
2 | |||
3 | |||||
5 | ||||
8 |

(How do we know someone is a judge? `User.judge_in_vacols?` methods)

Though the votes say "3", subsequent discussion has made this group decide this is a 

# 5

Rant incoming.

**Comment by hschallhorn** [comment]
From the Judge assign page, a judge can select a case and any attorney user (this includes judges and acting judges) and hit "Assign". We determine if the judge meant to reassign the `JudgeAssignTask` to another judge or assign an `AttorneyTask` to an attorney based on [if the assignee is a judge](https://github.com/department-of-veterans-affairs/caseflow/blob/a4bc0aaff66df7a821f30d67dd8eccbf5a9da85f/app/controllers/judge_assign_tasks_controller.rb#L51). Acting judges are both attorneys and judges and need the ability to have judge tasks reassigned to them AND have attorney tasks assigned to them. On the judge assign page, there is no way for judges to stipulate if they are intending to assign or reassign when selecting an acting judge.

One possible solution is to completely remove the ability to reassign tasks to judges on the assign page (regression of #7612 and remove ability to reassign legacy appeals) and to only allow reassigning though the reassign task action on the case details page (which may need to be built out for legacy cases). 

Whatever path we choose, this will need release notes. Please notify Shawn when complete!

**Comment by hschallhorn** [comment]
Unless I'm missing something, as our code currently stands, judges have the ability to reassign any [AMA judge task](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/judge_task.rb#L13), but only have the ability to reassign a `JudgeLegacyAssignTask` via [initialAssignTasksToUser or reassignTasksToUser](https://github.com/department-of-veterans-affairs/caseflow/blob/74980a296d3018021c8df43bc44e482cf03f7c5e/client/app/queue/QueueActions.js#L419) in the [AssignWidget](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/AssignWidget.jsx). For this reason, I'm similarly only going to focus on reassigning `JudgeLegacyAssignTask` and not `JudgeLegacyDecisionReviewTask`

**Comment by hschallhorn** [comment]
@stwards11 and @msj0nes This is closed and ready to go out today. Here are some key changes:

AMA cases cannot be reassigned to a judge from their "Assign cases" page. They will need to use the "Re-assign to judge" dropdown action on the case details screen for that specific case. 

This allows them to stipulate how they would like to assign a case to an acting judge:
1. If the judge would like to assign a case to an acting judge in order for the acting judge to draft a decision, they should assign it to them from their "Assign cases" page or via the "Assign to attorney" dropdown on the case details page.
2. If the judge would like to transfer the case to the acting judge in order for the acting judge to assign the case to an attorney, they should reassign it to them via the "Re-assign to judge" dropdown action on the case details page.

**Comment by hschallhorn** [comment]
@stwards11 and @msj0nes now that #12402 is merged, after deployment tomorrow, the same actions above should be taken for assigning/reassigning **legacy** appeals to acting judges. "Assign cases" page and the "Assign to attorney" dropdown on the case details page will assign the case to them as an attorney and "Re-assign to judge" dropdown action on the case details page will assign the case to them as a judge.
