### ISSUE TITLE
Standardize class structure

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11778]
Per https://github.com/rubocop-hq/ruby-style-guide#consistent-classes and https://github.com/rubocop-hq/ruby-style-guide#def-self-class-methods we should standardize our class layouts so that we consistently order methods.

We should always prefer this style:

```ruby
class Foo
  class << self
    def first_method
      # body omitted
    end

    def second_method_etc
      # body omitted
    end
  end

  def initialize
    # something
  end
end
```

and should group all class methods first in the file, followed by instance methods.

**Comment by monfresh** [comment]
There's also a new more aesthetically-pleasing website for the style guide: https://rubystyle.guide/#classes-modules
