### ISSUE TITLE
The evidence submission window task should start on the receipt date

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#11776]
The "Evidence submission window" task for the mail team should start on an NOD's receipt date.  The case is not eligible to be distributed until the evidence submission window is closed, 90 days after the receipt date.  Having the later start date can delay when the case is distributed if we're behind on intaking mail.

Note: these screenshots are for current behavior, not desired behavior.

![image (1).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/fbc01889-d2db-42ff-b3e8-c51b63d21d2e)

![image (2).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/99b01c78-fb09-4df1-9fd5-e464af2f278c)

**Comment by leikkisa** [comment]
Question - who closes the evidence submission window task? The mail team? Should it automatically be closed since it's a window of time, not a task that gets completed?

**Comment by laurjpeterson** [comment]
Related - https://github.com/department-of-veterans-affairs/caseflow/issues/7916

**Comment by laurjpeterson** [comment]
@leikkisa - I think this ticket can be closed because the evidence window submission task timer already starts on the NOD receipt date. See #7916, and lowell's comment stating that the work was completed with https://github.com/department-of-veterans-affairs/caseflow/issues/9340
