### ISSUE TITLE
When finishing Intake, there is a way to click the browser back button that would take you to the previous page

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#11779]
## Old ticket copy
When finishing Intake, there is a way to click the browser back button that would take you to the previous page to add issues. 

AC:
Redirect to the first page instead.

## User story

As an intake user, when I'm working the intake flow and want to revisit a previous section, I want to go back a step(s) without canceling the whole intake flow so that I can review/edit information. 

## Problem statement

Intake users currently don't have a clear button to go back a step on the page

## Existing design and content

[Design explorations
](https://www.figma.com/file/WvJNWNeZF7piEpln5szzIm/Back-Button?node-id=0%3A1)

## Success criteria

Users are able to move back a step(s) with confidence

**Comment by jimruggiero** [comment]
@carodew passing this to your backlog to confirm that Anya's recommendation is the desired interaction for caseflow reverse navigation. Can you confirm or provide alternate guidance?

**Comment by carodew** [comment]
Best practice is to never break the browser's back button, so without knowing anything else about the workflow this sounds right. 

Is there also a way in the UI to navigate back to add more issues? How many issues is a person likely to add in one go (aka, is there a need for a bulk or multiple add functionality?)

**Comment by jimruggiero** [comment]
Great questions, but all TBD. Currently, there's no way for an intake user
to go back if they make a data entry mistake...happy path only. They
basically have to cancel mid-stream and start over. Others can remove
erroneous issues, if required. Additionally, Sally wants to redesign the
Add Issues portion of the Intake workflow, as the AMA model currently in
Production is no longer sufficient to scale post-AMA workflows that include
productivity features (batch/bulk assignment, etc), or developer's needs.
Redesign work, even high-level thought experiments, were deprioritized in
July/August when EP930's and MTV became things to do now.

**Comment by pkarman** [comment]
Note that the Confirmation page (end of Intake) now has an "Edit issues" link on it that should take the user to the correct page to add/delete/edit the issues.

**Comment by jimruggiero** [comment]
Yep. Thank you, Peter. Forgot about the edit feature.

**Comment by pkarman** [comment]
This is causing production data integrity problems. See https://dsva.slack.com/archives/CHX8FMP28/p1573222890187100

I believe what we should do is invalidate the local redux store on successful confirmation page, and then detect that state on page load, so that the Back button "works" but will give the user a message and a button/link to click indicating they need to "edit" rather than re-use the previous intake session.
