### ISSUE TITLE
Show Certification v2 in deployed environment for testers.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1177]
We need to show Certification v2 to testers so they can validate tickets as they get released. We could create a CertificationV2 role and trigger it on the admin page. Sync with @kierachell and @astewarttistatech to see what would be easier for them.

**Comment by kierachell** [comment]
We have a `/functions` page where you can add/remove extra roles that users have.
Previously, @nemodjuric created two versions of the "Cancel Certification" modal - one was visible to all users, the other only to "System Admin" role. It worked out pretty well. If that is easy to set up for you, then just add an extra "function" called "Certify Appeal v2" or something like that and it can be toggled via `functions_controller`.

**Comment by kierachell** [comment]
**PASSED**

![certv2](https://cloud.githubusercontent.com/assets/18075411/24210800/93c5c1ce-0f00-11e7-8424-460ad1ccf6c5.gif)
