### ISSUE TITLE
Remove getFilterValues Prop from TableFilter

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11775]
`getFilterValues` is marked as a historical prop in `TableFilter`. I tried using it at one point, and parts of the `TableFilter` component do not work well when you specify it, so I think it would be a good idea to just remove it. I don't believe it's being used anywhere currently.

**Comment by hschallhorn** [comment]
Relevant: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueTable.jsx#L113

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||
2 | ||||||
3 | ||
5 | 
8 | 
```

Hunter: Thinks this should be alright to remove. Should check judge assign page (both unassigned and assigned)

#### Why 1?
* delete unused thing, should be easy...?

#### Why 2?
* Pessimism and checking nothing breaks

#### Why 3?
* Filtering is a bit of a tangled mess on the front end.
