### ISSUE TITLE
Intake | Add POA as a claimant option for SC's and HLR's

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11793]
## User Story
As an intake user doing intakes for any appeal, I want the ability to select a Veteran's POA when I answer YES to the question "Is the claimant someone other than the Veteran?", so that I can properly intake these cases without using a work-around. 

## AC
- Intake users see and can select a radio button with "[Attorney Name], Attorney" below the spouse option, if the POA is listed in Corp DB. 

WIP Assumptions:
1. If the claimant is not the Veteran, or their spouse AND the POA name cannot be pulled from Corp DB (via BGS? directly?), then users will complete these intakes via the "None of these match, see more options" Add Issue flow.
2. Allowing users to manually enter POA names may cause data integrity issues; Corp DB must continue to be the single source of truth for this information. 

## Open questions:
1. What is the final language that intake users should use in Caseflow fields, if following the "None of these match..." Add Issues flow? Does Rachel's suggested language ("Improper calculation of attorney's fees") suffice in screenshot below? If not, can Kristy provide recommended language for training guidance/documentation purposes?

## User Story
As an intake user doing intakes for any appeal, I want the ability to select an "Attorney Fee Appeal" as a new issue type in the Add Issue workflow.

## AC
- Intake users see and can select a radio button with "[Attorney Name], Attorney" below the spouse option, if the POA is listed in Corp DB. 

WIP Assumptions:
1. If the claimant is not the Veteran, or their spouse AND the POA name cannot be pulled from Corp DB (via BGS? directly?), then users will complete these intakes via the "None of these match, see more options" Add Issue flow.
2. Allowing users to manually enter POA names may cause data integrity issues; Corp DB must continue to be the single source of truth for this information. 

## Open questions:
1. What is the final language that intake users should use in Caseflow fields, if following the "None of these match..." Add Issues flow? Does Rachel's suggested language ("Improper calculation of attorney's fees") suffice in screenshot below? If not, can Kristy provide recommended language for training guidance/documentation purposes?

**Comment by jimruggiero** [comment]
![image005](https://user-images.githubusercontent.com/52474028/63126467-f55f6e00-bf7d-11e9-93a8-5c5c1bf8b014.jpg)

**Comment by jimruggiero** [comment]
![image006](https://user-images.githubusercontent.com/52474028/63126776-a36b1800-bf7e-11e9-8024-2185f185a89a.jpg)

**Comment by jimruggiero** [comment]
Rachel confirmed that there is no underlying decision issue data that Caseflow could map to, which is why the non-rating issue flow must be used. These decisions are called “Summary of the Case” and they look like letters.
![image007](https://user-images.githubusercontent.com/52474028/63126854-d7ded400-bf7e-11e9-9454-dad90e43605b.png)

**Comment by leikkisa** [comment]
@nanotone This might be a ticket we can clean up as well

**Comment by leikkisa** [comment]
Closing as a dupe, replaced by other attorney fees work
