### ISSUE TITLE
Clean Up & Unignore Issues in UpdateCachedAppealAttributesJob

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11804]
While pushing forward in parallel on the [`update_cached_appeal_attributes_job.rb`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/update_cached_appeals_attributes_job.rb) we sacrificed some code quality to move forward in parallel. This ticket is to reevaluate our rubocop disables in that file and clean up the code.

For context see discussions on #11690

May be related to #11760.

## Acceptance criteria
* [ ] Remove all of the rubocop, reek, and code climate ignores
* [ ] Write tech spec that addresses the following issues (keep in mind #11690):
  * [ ] Consider technique for making sure front- and back-end sorting mechanism and data returning in each field do not drift out of sync with one another
    * E.g. `Appeal.assigned_to`
  * [ ] Consider sensible refactors of this code now that this class has settled down into a steady state
  * [ ] Consider refactoring tests

**Comment by lowellrex** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_

Estimating this at 3 because it is mostly a tech spec.
