### ISSUE TITLE
Hearing API missing facility data for some veterans

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11802]
The Hearings API response is missing some facility information for some veterans.

Example participant ids:

30694233
31153080
35510455
6230049
3236701
23662439
2769203
32626624
8232736
8232736
8710546
34330243
29529926
36464464
38938523
11137301
38494203
12997228
300686
35115929
45123823
7682350
32770898

**Comment by lomaxap** [comment]
For upcoming hearings

`LegacyHearing.where(id: [116731, 120768, 115536, 110825, 121824, 121584, 107827, 122758, 120158, 108901, 121825, 122272, 116322, 117246, 121823])` (15)

There are no `nil` locations for future AMA hearings

We did not make hearing locations a mandatory field until around April. @premal I think we can assume that if a hearing location is nil, then the hearing will be at the RO, but would like to confirm with someone at the branch. Can you reach out?

**Comment by pkarman** [comment]
Possibly related to https://github.com/department-of-veterans-affairs/dsva-vacols/issues/74

**Comment by pshahVA** [comment]
worked with @lomaxap and he determined that the first one above doesn't have a legacy or ama appeal.
