### ISSUE TITLE
Case timeline | Refresh

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11803]
We've had Case Timeline out in Caseflow for a while, and have done some work to refresh it.

This ticket will likely spawn smaller, individual github issues for eng implementation

## New naming conventions for tasks
- Update tasks in Case Timeline with new user-facing task names - https://github.com/department-of-veterans-affairs/caseflow/issues/7508

## Designs
https://app.mural.co/t/workqueue2001/m/workqueue2001/1556035219909/9317bc82fd2cf504e3e8539a172a33750c406a0d

**Comment by alisan16** [comment]
A couple more user requests:
- Upgrade the view of appeal streams to be as user-friendly as VACOLS. 
> This is referring to Case Timeline. Request for a more streamlined view of case history. VACOLS just shows a list of every location the appeal has been. The requestor believes the Caseflow timeline is too detailed
- In the Case Timeline, include the date of claim and date of the rating decision.
> Expand case timeline to go back even further. Currently case timeline starts with filing of NOD. User is requesting the history starting from when the initial claim was filed
