### ISSUE TITLE
Browser compatibility bugs

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1182]
We observed a few browser related bugs during user testing yesterday:

## Internet Explorer
- [x] Unable to open multiple document windows 
- [x] Not pulling documents from cache

## Chrome
- [x] All-text PDFs not displaying properly

Depending on how easily we can resolve IE issues, we may need to explore the possibility of piloting in Chrome or Firefox.

**Comment by nicholasholtz** [comment]
Saw the same issues in IE yesterday when using Decisions.

**Comment by gnakm** [comment]
Related to #1196

**Comment by mdbenjam** [comment]
These issues should all be fixed. Use #1196 to track the only remaining issue.
