### ISSUE TITLE
EP 930s | Edit accidentally cleared SC EPs via 930s

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11837]
**Scenario: 
Decision on an 030 or 040 was incorrect, and award was promulgated **OR** the EP was cleared (when Veteran's benefit is updated via award generated and authorized). 030 and 040 is **NOT** still pending. At least one issue had a DTA error, and therefore, there is a resulting supplemental claim. **That resulting supplemental claim was accidentally cleared.**

Example: DTA instead of granted. That DTA issue is on the Supplemental Claim which was accidentally cleared.

**Story:
As an Intake user processing a DTA SC EP, I identified a decision was incorrectly made and the DTA Supplemental Claim EP was accidentally cleared; I want the ability to edit the accidentally cleared DTA SC EP via the 930 workflow.

![image](https://user-images.githubusercontent.com/3811786/64019281-bba17200-cafc-11e9-8014-b3af8c5be8c3.png)

## AC
- Ensure DTA supplemental claim EPs can be edited via 930s using existing 930s flow.
- Allow DTA page to be editable, but remove the Add Issue button from the screen
- If SC EP is already cleared, there's no need to remove the contention or cancel the EP - see #11838 
- Request issue should be closed with a status (no_decision)

**Comment by laurjpeterson** [comment]
Not needed
