### ISSUE TITLE
EP 930s | Enhanced Search

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11835]
### Scenario: a user identified a decision was incorrectly made, for example, they granted an issue instead of denying it.

Enhancement requested: Show receipt date for the claim in search results

Value to be delivered: This functionality makes it easier to know which claim review require corrections by users.

AC:
1. Add a column to show receipt date for all claim reviews
 
Assumptions: 
1. No change to table schema or data is required beyond adding this column.

**Comment by jimruggiero** [comment]
@Sjones352 can you add a screen shot in the comments for this one?

**Comment by Sjones352** [comment]
Connects  #11835
<img width="1076" alt="Screen Shot 2019-08-27 at 12 18 13 AM" src="https://user-images.githubusercontent.com/23080951/63778991-d634da80-c8b3-11e9-8ff9-50d16c40c607.png">
