### ISSUE TITLE
EP 930s | Show previous decision ratings

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11836]
###Scenario: a user identified a decision was incorrectly made, for example, they granted an issue instead of denying it.

AC:
1. Contestable issue generator: add all decision reviews (display all issues) - finalize_decision_issues_before_receipt_date method should also return decisions issues for that review

Assumptions:
1. Find all and add to list of contestable issues (existing add issues modal)

**Comment by leikkisa** [comment]
Look in `contestable issue generator`

Add the current claim review's decision issues to the list of contestable issues

Currently it only includes these:
`finalized_decision_issues_before_receipt_date`

We want that to include something more like this:
`finalized_decision_issues_before_receipt_date + claim_review_decision_issues`

where the claim_review_decision_issues would equal `review.decision_issues`

**Comment by jimruggiero** [comment]
AHHH
