### ISSUE TITLE
Hearings API regional_office should reflect hearing location

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11834]
The Hearings API returns a record like:

```json
{
  "address":"100 SW Main Street Floor 2",
  "city":"Portland",
  "appeal":"701dc7a2-732e-4eca-9dc5-f024adf0719d",
  "facility_id":"vba_348",
  "participant_id":"31634112",
  "regional_office":"Seattle regional office",
  "room":"7",
  "scheduled_for":"2019-08-23T12:30:00.000-07:00",
  "state":"OR",
  "timezone":"America/Los_Angeles",
  "zip_code":"97204"
}
```

Is this correct?

**Comment by lomaxap** [comment]
The hearing location can be different from the regional office the veteran is assigned to. That address is not the regional office’s address. We should add a something like a “hearing location” property to the response that’s the facility’s name.

**Comment by pkarman** [comment]
For the purposes of the Hearings API, the hearing location is really the only relevant location.

We should use the existing `regional_office` key to name the hearing location.

**Comment by pkarman** [comment]
It was a small fix. Created PR
