### ISSUE TITLE
User research study: Dispatch workers' role in motions to vacate

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11830]
## Background

We need to know more about what Dispatch does with motions to vacate in order to properly define the user stories for this work. This research study aims to gather this information for both grant rulings and withdraw/deny rulings. 

## Learning goals

**UNDERSTAND**
- What is their current process for when they receive a grant ruling on a motion to vacate?
- Who are these humans? Is this their main job? What else are they doing?
- How familiar are they with MTVs?
- How do they get the ruling?
- What happens next?
- What systems do they work in?
- What data are they working with?
- Outcoding - need more clarification from Geronimo around this

**VALIDATE**
- How familiar are they with Pulac-Cerrulo checks? (May be an important user group to get feedback on designs)

**IDENTIFY**

- What do we need to design for them?

## Related issues
- The purpose of this research is to define the requirements and AC for #11726 and #11727 
- Related to #10210
- This research could also inform #11256

**Comment by msj0nes** [comment]
Can we close this ticket to indicate the work mentioned is already completed?

**Comment by rutvigupta-design** [comment]
Removing this from the Motions to Vacate work, but keeping it open to revisit.

**Comment by rutvigupta-design** [comment]
@geronimoramos do you want me to move this over to you? Or would you prefer we close this?

**Comment by rutvigupta-design** [comment]
Closing. Will potentially re-visit the need to research user groups in the future.
