### ISSUE TITLE
Add rating decisions to Intake from before 2005

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11840]
Originating from #10511 this ticket describes older BGS rating data that does not contain rating issue information for older (pre-2005) decisions.

See https://github.com/department-of-veterans-affairs/appeals-support/issues/5319 for support issue and referenced OIT tickets.

These past decisions appear in VBMS under the "Rating Profile" tab but are not populating in the Caseflow Add Issues screen during Intake.

Our current plans involve 2 threads:

* [x] Include the rating decisions currently returned by BGS as part of the rating_profile API response. These include non service connected and service connected decisions. We will include the non service connected decisions that do not have a `rating_issue_id` that are currently not included in the Add Issues Intake screen.
* [ ] Explore a new BGS API endpoint that may contain the missing `rating_issue_id` values for these non service connected decisions. This requires some additional infrastructure work in Caseflow in order to allow us to preview this API endpoint with production-like data while it is in development.

One or both solutions should allow us to include these missing rating decisions in Caseflow Intake and unblock users.

**Comment by pkarman** [comment]
production participant ids to use for development and testing:

33380576
31140273
4563635

**Comment by pkarman** [comment]
Now behind feature toggle. Enable for your user via prod rails console.
```
FeatureToggle.enable!(:contestable_rating_decisions, users: [you.css_id])
```

**Comment by pkarman** [comment]
in production just now:

```
RequestIssue.where.not(contested_rating_decision_reference_id: nil).count
=> 243
```

17 of which have already been decided.

**Comment by pkarman** [comment]
According to https://github.com/department-of-veterans-affairs/appeals-support/issues/5324 we may need to revisit the +/- 10 day date window comparison logic for whether a rating decision is contestable or not. See https://dsva.slack.com/archives/CHX8FMP28/p1568212423253600

**Comment by pkarman** [comment]
New BGS endpoint at

```ruby
BGSService.new.client.rating_profile.find_in_date_range(participant_id: 13774779, start_date: '1999-01-01', end_date: '2019-09-24')
```

but currently returning SOAP error.

**Comment by pkarman** [comment]
Ongoing list of rating issues still missing from intake screen: https://github.com/department-of-veterans-affairs/appeals-support/issues/5319#issuecomment-526672743

**Comment by pkarman** [comment]
As part of this effort we should write a report showing the number of unidentified issues vs rating decision issues week-over-week. That should illustrate whether we are making any progress.

**Comment by pkarman** [comment]
Summary of research based on https://github.com/department-of-veterans-affairs/appeals-support/issues/5319

## Scenarios

### Missing disability_date

Rating Decision relies on an `effective_date` to determine which rating to associate it with (the definition of `contestable?` relies on a date match). We were ignoring the `dis_dt` BGS value. That is now mapped to `disability_date` per https://github.com/department-of-veterans-affairs/caseflow/pull/12229 which hopefully brings a few more rating decisions into the pool.

### Receipt Date Timing

CAs are doing intakes for forms with receipt_date values earlier than the earliest reported rating decisions. Sometimes it is only days earlier, which seems to suggest that the Veteran is aware of the need to submit more evidence via Supplemental Claim, but there's some miscommunication around which date should be on the form.

Should we be showing rating decisions *after* the receipt date and then marking them as ineligible, so that it is more clear to the CA that (a) the decisions exist, and (b) the Veteran could possibly resubmit the form with a different date?

### Which dates are effective?

Currently we capture and prioritize in this order: `original_denial_date`, `converted_begin_date`, and `begin_date` (abbreviated "start dates" here).

When present, these can be many years before the `disability_date`, putting them in the pre-2005 zone. We could:

 * define an observed-but-arbitrary cutoff date. Decisions with start dates before that cutoff date would always prefer the disability_date as the decision_date.
 * always prefer the disability_date
 * ???

### Promulgation vs profile date

We use the promulgation date for the official rating decision date, which determines eligibility. However, in some cases the promulgation date is weeks or months after the disability_date and the profile_date. We could pick the more generous/inclusive match between promulgation and profile date, rather than exclusively using promulgation date. I believe this would be consistent with how VBMS displays denials, which don't seem to have a rating issue date attached and which users are relying on to complain that "VBMS shows it but Caseflow doesn't."

**Comment by pkarman** [comment]
Previous slack discussion of which dates to use https://dsva.slack.com/archives/C754H751T/p1566338841221200

**Comment by dwhitted** [comment]
OIT is requesting a status on this open engineering ticket?

**Comment by dwhitted** [comment]
This relates to INC7951455 do we have an eta on a solution or what's the plan for resolution?

**Comment by dwhitted** [comment]
INC7528208 this SNOw ticket seems to be related and appears to be an open ticket over 30 days

**Comment by pkarman** [comment]
This is a systemic problem we are tackling from a variety of angles, ongoing since April. It is sometimes referred to as the "missing rating data" problem.

We have a number of communication threads going with BGS, AMO and VBMS. For INC7951455 and INC7528208 we do not yet have an ETA, but the plan is to discover how best to provide the missing data for those Intakes (as well as many others).

According to @msj0nes we were able to close several INC tickets recently thanks to changes noted earlier on this ticket. We're continuing that progress (we hope).

**Comment by pkarman** [comment]
@dwhitted we have deployed #12599 which we are hoping will resolve the open INC tickets.

**Comment by pkarman** [comment]
We have included all the rating decision data possible from the existing BGS API endpoint. Closing this ticket and opened #12805 to reflect the yet-untried new endpoint.
