### ISSUE TITLE
Virtual Hearings user research study – Veteran facing

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11859]
Focused on the experience of having a Virtual Hearing, and not on Caseflow UI. 

Final research plan and data is stored at: https://github.com/department-of-veterans-affairs/appeals-team/tree/master/Project%20Folders/Caseflow%20Projects/Hearings/Telehearings/research/research-study-telehearings-pilot

Research was conducted October 2019. Readout to stakeholders completed December 2019.

## Scope

This ticket does not include user research for VLJs, hearings coordinators, and VSOs (in terms of what they see in Caseflow) those will be captured in separate tickets (forthcoming).

**Comment by nicholer** [comment]
- Feedback form was updated for veterans/representatives August 28, 2019 to include interview opt-in
