### ISSUE TITLE
Correctly label DecisionReviewTasks in paginated queue filter dropdowns

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11868]
#11867 introduced a regression in how labels for `DecisionReviewTask`s are displayed in the filter dropdown menus for paginated organization queues. This PR exists to correctly label `DecisionReviewTask`s & its subclasses in paginated queue filter dropdowns (either "Higher-Level Review" or "Supplemental Claim")

## Acceptance criteria
* [ ] Correctly label `DecisionReviewTask`s in paginated queue filter dropdowns.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
      1 | ||||
      2 | |||||
      3 | 
      5 | 
      8 | 
```

Estimating at a 2. Might be a 1 if the labelling and inheritance chain is clear and obvious.

**Comment by hschallhorn** [comment]
Putting this in backlog for reasons that will be outlined shortly, but for now, "woof".

**Comment by kevmo** [comment]
This is a bigger issue than anticipated: 

* DecisionReviewTask labels work differently from other tasks, at least some of them, relying on the appeal state for their evaluation.  As such, some of labels could belong on the `cached_appeal_attributes` table.
* The `/decision_reviews/<org>` views aren't using the queue table infrastructure we built out for pagination in the `/queue` view.
* This involves a refactoring of `DecisionReviewTask` and its subclasses.

After some discussion, we believe this ticket should remain for the future - should the views in which these tasks appear become paginated, this ticket should be included in that work.

**Comment by araposo-tistatech** [comment]
closing based on Kevins comment point 2. decision_reviews/ endpoint doesn’t use pagination.
