### ISSUE TITLE
Update Deprecated React Lifecycle Hooks

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#11866]
Various React lifecycle hooks [have been deprecated in recent versions](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods), and will be removed completely in v17.x.

These include the following throughout the code base:

- componentWillMount (5 instances to fix)
- componentWillReceiveProps (7 instances)
- componentWillUpdate (1 instance)

This PR added the `UNSAFE_` prefix to the deprecated methods, per recommendations:
https://github.com/department-of-veterans-affairs/caseflow/pull/11864

**Comment by alisan16** [comment]
I only see 1 more use of `componentWillMount` in `caseflow-frontend-toolkit`: https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit/blob/master/components/ReduxBase.jsx#L10. Should we create a separate ticket to remove that or continue tracking here?

**Comment by jcq** [comment]
@alisan16 The 5 instances are still present in the `caseflow` repo, but they have been prefixed with `UNSAFE_` by #11864. So they still need to be rewritten, but folks should look for `UNSAFE_componentWillMount`, etc.

**Comment by meckila-navapbc** [comment]
Resolved in #11864

**Comment by jcq** [comment]
@meckila-navapbc I don't think #11864 actually resolved this; that simply prepended `UNSAFE_` but we didn't remove the lifecycle hooks altogether yet, right?

**Comment by meckila-navapbc** [comment]
Ah, good distinction. I'll re-open this one
