### ISSUE TITLE
Seed Option for Realistic Case Quantities

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11878]
It would be very useful to have the option to create a realistic quantity of case data in our dev environments. We have run into issues in testing code due to behavioral differences in there being 5 legacy appeals vs thousands.

Acceptance Criteria:
 - [ ] an option exists to seed thousands of legacy & ama cases in dev
   - [ ] Optional: legacy cases should preferentially be older than ama?
   - this option _should not_ be the default behavior
   - the priority should be speed of creation over realistic or distinctive data
   - running db:reset should remove all this data and restore the 'current' dev data setup

**Comment by hschallhorn** [comment]
the rest of the timebox. 

Fits well with Peter's effort to break out and individually run some seeds (not on reseed). Will be great for dogfooding.

Could just create the structure/infrastructure for creating lots of seed data by reusing the factories and seed methods we have. Can iterate on making dev data better later.

Circulate the design of the implementation with the team before diving in!

Don't forget legacy data!!

Good place to start may be with the realistic appeal task tree factories (:ready_for_distribution, :atty_drafting, etc)

**Comment by hschallhorn** [comment]
Related: #14184

**Comment by hschallhorn** [comment]
Related #9719
