### ISSUE TITLE
Automatic task closure not working for HearingTasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11879]
See related Slack discussion: https://dsva.slack.com/archives/CHX8FMP28/p1566571633072400

**Comment by tomas-nava** [comment]
This was a data problem, not a functionality problem. `HearingTask`s with the following IDs were open, but had no children:

```
[38105, 38733, 42265, 42933, 44906, 47055, 61669, 36705, 39034, 41299, 42792, 117047, 55972, 57123, 111976, 41103, 43608, 40642, 58118, 105364, 142766, 36589, 37600, 52712, 57055, 57463, 62183, 122382, 114033, 36659, 38167, 38764, 40148, 52404, 53510]
```

I modified the `OpenHearingTasksWithoutActiveDescendantsChecker` to report `HearingTask`s in this state in #11957, and have resolved all but three of the related appeals.

Most were resolved by setting the `status` of the childless `HearingTask` to `cancelled` and (when appropriate) calling `when_child_task_completed` on the `HearingTask` that was associated with a held hearing, allowing the case to proceed.
