### ISSUE TITLE
Bug: Receipt Date is 1 day behind

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1187]
**Current** 
The Receipt Date is behind by one day (displays receipt date as one day earlier than date in VBMS).

**Expected**
The Receipt Date should match the document's Receipt Date in VBMS.

**Comment by abbyraskin** [comment]
@nicholasholtz in which direction is it off by one day?

**Comment by nicholasholtz** [comment]
Caseflow Decision is behind by a day.

**Comment by abbyraskin** [comment]
@nicholasholtz obviously it isn't ideal, but what are your thoughts on launching with this bug?

**Comment by nicholasholtz** [comment]
If it was inconsistent, I'd be more concerned, but not fatally so. 

I think it is something we can just be up front about and let them know it is something we are working on, and will let them know if it changes during the pilot.

Launch away.

**Comment by abbyraskin** [comment]
OK, thanks @nicholasholtz!

**Comment by abbyraskin** [comment]
@avrildavid @wturne this is a bug we'll probably want to bring up in training if it still exists when we launch, which it likely will.

**Comment by avrildavid** [comment]
Thanks for the heads up @abbyraskin - we can mention it's a temporary bug in the prototype. For clarification, does this only happen in the document list view or does it happen anywhere else receipt date is shown (if there are any other places, not sure)?

**Comment by nicholasholtz** [comment]
@avrildavid We are probably going to have a small list of identified bugs that will be present, so may want to go ahead and plan in that direction as far as tracking these things goes (but you might already be doing so!). :)

**Comment by abbyraskin** [comment]
@avrildavid good call...it happens everywhere the Receipt Date is shown.

**Comment by avrildavid** [comment]
Thanks, @abbyraskin

**Comment by kierachell** [comment]
**PASSED**
<img width="657" alt="screen shot 2017-05-03 at 12 51 21 pm" src="https://cloud.githubusercontent.com/assets/18075411/25671803/4298fd50-2fff-11e7-9127-6129200e1520.png">
<img width="941" alt="screen shot 2017-05-03 at 12 51 27 pm" src="https://cloud.githubusercontent.com/assets/18075411/25671804/429b81b0-2fff-11e7-83a8-c639d8e25a19.png">

**Comment by nicholasholtz** [comment]
woooohooooooo!
