### ISSUE TITLE
NoMethodError in set_vacols_values for case record

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11889]
Seeing this error in `FetchHearingLocationsForVeteransJob`:

```
NoMethodErrorapp/repositories/power_of_attorney_repository.rb in set_vacols_values
error

undefined method `bfso' for nil:NilClass
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6274/events/447511/

---

It appears to be happening for a specific ID. See https://dsva.slack.com/archives/C42P25D6H/p1565643070101000 for more info.

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 6 months.
