### ISSUE TITLE
NoMethodError in fetch_person_info in BGS service

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11891]
For `WarmBgsCachesJob`, seeing this error:

```
NoMethodErrorapp/services/external_api/bgs_service.rb in fetch_person_info
error

undefined method `[]' for nil:NilClass
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6276/events/447041/

**Comment by alisan16** [comment]
Closing as this hasn't been seen in 7 months.
