### ISSUE TITLE
Wrong number of arguments in hearing_disposition_change_job

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11892]
For the `perform` method in `hearing_disposition_change_job`:

```
ArgumentErrorapp/jobs/hearing_disposition_change_job.rb in perform
error

wrong number of arguments (given 1, expected 0)
```

Looks like it's being passed with an empty object as an argument:

```
[{}]
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6245/events/446324/

**Comment by alisan16** [comment]
Closing as this hasn't been seen in 7 months.
