### ISSUE TITLE
Create JudgeAssignTask for Legacy cases when Judge requests new cases

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#11908]
### Current implementation

When a judge would like to be assigned more cases, they go to their assign page (`/queue/:judge_id/assign`) and click [[Request more cases](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/AssignWidget.jsx#L180-L188)]. This enqueues a distribution request ([controller](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/distributions_controller.rb#L10) | [Distribution#distribute](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/distribution.rb#L44) / [AmaCaseDistribution#distribute_appeals](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/ama_case_distribution.rb#L70-L87)) in a job.

[For AMA cases](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/docket.rb#L46), distribution means a
1. a `JudgeAssignTask` is created for this appeal / judge
2. a `DistributedCase` record is created in caseflow for each case
3. the `DistributionTask` is marked complete

[For Legacy cases](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/dockets/legacy_docket.rb#L45),
1. The VACOLS location for the case is [set the judge's VACOLS `slogid`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/vacols/case_docket.rb#L283) aka their `vacols_uniq_id` (see also [AppealRepository#distribute_priority_appeals](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/appeal_repository.rb#L732]))
2. A `DistributedCase` record is created in Caseflow for each case

### Changes

For judges with `legacy_das_deprecation` feature toggled on, we should create a `JudgeAssignTask` for legacy cases when a case is distributed

### Acceptance Criteria
- [ ] confirm that a `JudgeAssignTask` is created when legacy cases are distributed to a judge
- [ ] confirm that the vacols location for distributed cases is set to `CASEFLOW`

**Comment by ferristseng** [comment]
I think I can pair with @rubaiyat22 on this. We would have to tackle #11906 as a part of this too.
