### ISSUE TITLE
Investigate issue with judge and attorney check out flow | editing decision issue switches task from JudgeDecisionReviewTask to AttorneyTask for acting VLJs

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11917]
First, read this [slack thread](https://dsva.slack.com/archives/CHX8FMP28/p1566936393203700) for context.

## AC
- Investigate why editing decision issues switches task from JudgeDecisionReviewTask to AttorneyTask for acting VLJs
- Create subsequent tickets to fix

**Comment by hschallhorn** [comment]
#11968
