### ISSUE TITLE
Intake NotNullViolation for benefit_type column

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#11925]
Seeing an `ActiveRecord::NotNullViolation` error in `app/models/claim_review.rb` when creating request issues. Looks like `benefit_type` is null, and shouldn't be:

```
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "benefit_type" violates not-null constraint
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6237/events/450808/

**Comment by leikkisa** [comment]
I don't believe this is still a problem, the only claim reviews without benefit types are ones where the review page step hasn't been completed yet. The SC referenced above looks like it got cancelled. Closing.
