### ISSUE TITLE
Show all available hearings days when scheduling for an RO

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#11932]
User story:
When a hearings coordinator tries to schedule a veteran and selects an RO, I should be able to see all days that are available for that RO.

- Current Situation.  When a user tries to schedule a hearing, he sees a subset of all the hearing days.
![image](https://user-images.githubusercontent.com/49729315/64446971-3abc1a80-d0a8-11e9-8a49-e43b48a905d5.png)

- However, when you look at the schedule, you see there are more days available
![image](https://user-images.githubusercontent.com/49729315/64446915-119b8a00-d0a8-11e9-86e9-f57978417f3f.png)

Release notes - n/a
Designs-n/a
Acceptance criteria-the user should see all the available hearings days for the RO they are trying to schedule for.
Feature Toggle-n/a

**Comment by pshahVA** [comment]
@nicholer @lomaxap , do you think we should flag the days that are full as a value added feature.  Right now we only show non full days, but maybe we show them all, but mark them as full?

**Comment by nicholer** [comment]
@pshahVA Can you remind me why it's useful to show full hearing days in the sidebar?

I remember the Hearing Coordinator requesting to see the number of slots left per day.

**Comment by pshahVA** [comment]
So they can see the entire schedule right there, rather then going to the view schedule.

**Comment by nicholer** [comment]
Okay, I'll defer to your/others judgement here, since I don't have the context.

But if we're going to somehow indicate that days are full (i.e. have 0 slots), should we also roll in showing how many slots are remaining?

**Comment by pshahVA** [comment]
I agree, that would also be a nice enhancement.  However, Now that this bug is high visibility, I'm thinking we break it up into two tickets.  One for the initial bug, and then one for improvements.

**Comment by lomaxap** [comment]
@sharonwarner thinks we may have hardcoded a limit for a reason (maybe to ensure they fill earliear hearing days first). @pshahVA to ask around

**Comment by sharonwarner** [comment]
We're currently returning hearing days between the current date and 6 months from now. @pshahVA will reach out to the hearings branch to see if that's sufficient.

**Comment by pshahVA** [comment]
I have emailed the hearings branch, and awaiting a response.

**Comment by pshahVA** [comment]
Hearings branch is OK with the explanation that it only shows 6 months, no action is required.
