### ISSUE TITLE
Board Full Grants VBMS initial status

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11950]
via Jane

These claims come over from the Board (Caseflow Dispatch?) in the Initial Development life cycle (IDEV).  Can the life cycle be changed to Ready for Decision (RFD) for these particular claims?  The reason for this request is for claims routing efficiency.  When the claim comes over in RFD status, then National Work Queue (NWQ) will be able to route that straight to a decision maker (DRO or RVSR) to then process the full grant faster.  Currently, because the claim is in IDEV status, it goes into this particular life cycle inventory and then gets distributed to a VSR who then reviews the claim and then makes it RFD and then it gets routed to the decision maker.  This would potentially cut out 30+days of waiting for these claims to be addressed.

**Comment by leikkisa** [comment]
Closing this ticket - this is a duplicate ticket and this work was already completed (git blame the EstablishClaim request in connect_vbms to find PR).
