### ISSUE TITLE
Board Remands with Grant (or Partial Grants) VBMS initial status

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11951]
via Jane

These claims come over in IDEV status.  Ideally, these should come over in RFD status so then the decision maker can take action to address the Board grant portion first.  After the grant portion is addressed then it would go to a VSR to process the claim for the remand.  Again, it's another time reduction request with the change of the life cycle for these particular claims with regard to the grant portion.

**Comment by leikkisa** [comment]
Closing this, this work was completed.
