### ISSUE TITLE
Change HearingDay.bva_poc to refer to User.id

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#11966]
We inherited from VACOLS using the users `full_name` to populate the hearings/legacy_hearings/hearing_days' `bva_poc`. We should change this to use the User id field

- add a `hearing_coordinator_id` column to `hearing_day` and `hearings` table. `legacy_hearings` uses the `bva_poc` field from VACOLS
- backfill hearing_coordinator field with ids mapped from `bva_poc` (something like `User.find_by(full_name: bva_poc)`)
-  validate that vdbvapoc in VACOLS is equal to User.find_by(hearing_day.hearing_coordinator_id).full_name and update it in VACOLS if it doesn't match
- change every instance of `HearingCoordinator` dropdown to set the user ID as the dropdown's value
-  change hearing_day_controller / hearing_controller to accept `hearing_coordinator_id` parameter
- update `HearingRepository` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/hearing_repository.rb#L47) to save `bva_poc` to VACOLS as the user's full name
- update `HearingRepository` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/hearing_repository.rb#L176) to map `hearing_coordinator` from VACOLS `bva_poc`
- update `HearingMapper` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/mappers/hearing_mapper.rb#L25) to map `bva_poc` from hearing_coordinator_id
- remove `bva_poc` column from `hearing_day` and `hearings`

**Comment by ferristseng** [comment]
I'm wondering how the mapping step would work. Would we need to do a `User.find_by(full_name: bva_poc)` there? Is it possible for a coordinator `User` not to exist yet in Caseflow?

**Comment by lomaxap** [comment]
> Is it possible for a coordinator `User` not to exist yet in Caseflow?

The `HearingCoordinator` dropdown is populated from the [user table](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/users_controller.rb#L14-L15), so they _should_ exist in the database.

It doesn't look like the user's `full_name` stays consistent. @tomas-nava found at least 3 variations for full names for a single user. So it's possible it could change and we're not able to work out the user id from the VACOLS record.

**Comment by chandracarney** [comment]
Changed to low priority as this isn't causing any known issues in Caseflow as it exists.
