### ISSUE TITLE
Unable to add or move comments

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1196]
**Current**
Users are inconsistently able to add notes to documents. Notes are sometimes stuck to the top of the page, or do not appear at all after writing a note. This bug was browser agnostic (I think?).

**Expected**
Users should be able to add notes to any document, and to move the note icon freely across a page after saving a note.

**Comment by abbyraskin** [comment]
@mdbenjam was this fixed already?

**Comment by mdbenjam** [comment]
@abbyraskin Yes, just checked today. It seems to be fixed!

**Comment by abbyraskin** [comment]
wooooo!

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod
Browser: FF and Chrome

Steps to Validate: 
1. In Reader, create comments and move them around on the page. 

Screenshots: 
![reader](https://cloud.githubusercontent.com/assets/23038505/25249529/2104c5bc-25e0-11e7-8589-fee2f35ab7b3.gif)
