### ISSUE TITLE
Litigation Support | Pulac-Cerullo reminders follow-ups

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#11969]
The Pulac-Cerullo reminders enhancement has some follow-up questions that Product and Design want to monitor and potentially revisit with users, depending on user feedback and usage of the Pulac-Cerullo workflow enhancements, as developed in issue #11256  

Current known questions are:
- [ ] Should we introduce more friction by changing the banner to a modal, so that users have to acknowledge it? 
- [ ] Would we need to audit whether or not  a user actually checked for PC? (don't need to track the checks but might be useful to see the last time it would checked)
- [ ] When is the pattern so annoying that people just ignore it, vs. is it a useful reminder? 
- [ ] Is there a way to have a machine ingest this information from the CAVC website for users, instead of them having to check manually (or is that too heavy a lift?)
- [ ] How might we integrate analytics into this process, what would we be measuring and how frequently?

**Comment by leikkisa** [comment]
Checking if this ticket is still relevant. Pulac-Cerullo reminders have been implemented, but this ticket looks like it may be for additional enhancements on top of that.

**Comment by geronimoramos** [comment]
@leikkisa I believe these are future state ideas that could be visited potentially 3-months after everything is launched or if issues arise around PC checks/jurisdictional conflict.

**Comment by geronimoramos** [comment]
Should we keep this open as we hope to revisit this down the road for enhancements if there are any problems? @msj0nes

**Comment by msj0nes** [comment]
Closing @geronimoramos . Pulac Cerullo work  has been completed sometime now. In our continued talks with stakeholders if this is raised we can pursue it at a later date.
