### ISSUE TITLE
Savon::SOAPFault: (S:Server) gov.va.vba.utils.ShareException

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11973]
[Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6449/)

**Comment by pkarman** [comment]
Typically this is caught as a `BGS::ShareError` by the library so maybe this means we need an update to the ruby_bgs lib

**Comment by alisan16** [comment]
Closing as this error hasn't been seen in 7 months with only 2 events
