### ISSUE TITLE
query MOTH cases

### ISSUE THREAD

**Issue by vacohitchs** [department-of-veterans-affairs/caseflow#11978]
We got a request to list MOPH cases in caseflow.  Please advise the query : tables and columns.  
MOPH – Military Order for the Purple Heart. 
Thank you in advance.

**Comment by msj0nes** [comment]
@vacohitchs please provide more info regarding the ticket. The requestor from MOPH requesting. Which team you belong (no full name exist in your Github profile).  How does this involve Caseflow? Is this a dependency, API association? If you have worked with a specific Caseflow group who can shed light on your request please @ them.

**Comment by alisan16** [comment]
Closing as we do not have enough information to complete this ticket. If more information is provided, we can reopen and work the ticket.
