### ISSUE TITLE
EP 930s | When adding decision issues for correction should not make request issues ineligible

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#11984]
Scenario 1: correcting a decision issue with an allowed disposition
Scenario 2: correction a decision issue with a remanded disposition that has a DTA supplemental claim 

![image](https://user-images.githubusercontent.com/3811786/64343198-1550e300-cfba-11e9-9ef3-bd28eb1fef31.png)
None of these messages should be displayed. ^^ 
Correction request issue should not be marked as ineligible in the DB.

AC:
Correction request issue should be eligible if it is a correction to a decision issue

**Comment by jimruggiero** [comment]
Proposed approach: 
1. change validation on the backend when creating a request issue and 
2. either change a response hash for decision issues that are after receipt date, or on the frontend, skip those validations if it has a correction type

**Comment by jimruggiero** [comment]
@leikkisa can you add a screen shot or gif to this ticket when it's ready to be merged (if it differs from the one Anya included above)?
