### ISSUE TITLE
Add positive feedback to attorney evaluation screen for Legacy appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11988]
Related #7929 - Add positive feedback to attorney evaluation screen for AMA appeals.

## AC
Back end:
- Determine whether we should ask Jed to add these checkboxes to VACOLS, so Caseflow can use them/backfill them
- Or, add these positive feedback to the Caseflow database for legacy appeals

Front end:
- Add the below positive feedback/checkboxes to the Evaluate Decision screen in the judge checkout flow, above the other check boxes

## Designs
Heading: Identify positive feedback

- [ ] Responsive to contentions and theories
- [ ] Well-analyzed lay evidence
- [ ] Well-analyzed medical evidence
- [ ] Good hidden issue-spotting and analysis
- [ ] Concise, understandable, Veteran-centric writing
- [ ] Appropriate use of law, precedential opinion and administrative procedure
- [ ] Logically organized
- [ ] No substantive revisions
- [ ] Well proofed (no to minimal typos/grammar errors)
- [ ] Well-annotated file for VLJ review to include appropriate use of tags and comments
- [ ] Remand is concise and provides detailed, understandable directives

**Comment by hschallhorn** [comment]
#11960
