### ISSUE TITLE
Vacols Record Not Found

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#11992]
I was able to find the record ```VACOLS::Case.find_by(bfkey: "681376")``` but wondering why Hearing record with this vacols id is not found
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5883/events/458725/

**Comment by alisan16** [comment]
This looks similar to the investigation here: #12003. Closing this ticket as a duplicate.
