### ISSUE TITLE
BSE 65151 - Capability for Caseflow to Support Undifferentiated Gender

### ISSUE THREAD

**Issue by geoffreystienblock** [department-of-veterans-affairs/caseflow#11999]
**Requirement:**  Users need Caseflow to have an undifferentiated option concerning gender so that it can make the connection with VBMS.

**Value Statement:**  As a Caseflow user, I need for the Caseflow system to be able to establish an AMA claim in VBMS for a claimant who has no assigned gender in VBMS, so that Caseflow will be able to establish the claim in VBMS without any data issue related to the fact that the claimant in VBMS has not been assigned a gender.

**Definition of Done:**  Undifferentiated genders will not prohibit the claim from being established in caseflow, increasing the tracking and reporting of all claims

**Acceptance Criteria:**  The Caseflow system is able to establish a claim in VBMS for claimants who were not assigned a gender in VBMS.

**Comment by pkarman** [comment]
@geoffreystienblock I believe this was already resolved in March with #9709 -- is there some known defect that this new ticket represents?

**Comment by msj0nes** [comment]
COR contacted via email regarding this issue ticket and whether a recent VBA/AMO impacted issue sparked its creation.

**Comment by msj0nes** [comment]
# Ticket Closure
This work was ompleted via https://github.com/department-of-veterans-affairs/caseflow/issues/9709
