### ISSUE TITLE
Investigate Number of LegacyHearings without VACOLS records

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12003]

**Comment by jimruggiero** [comment]
@lomaxap @pshahVA  Can one of you please add a user story and AC's (if appropriate) to this ticket?

**Comment by pshahVA** [comment]
@ferristseng , do you have any context?

**Comment by ferristseng** [comment]
Yes, this has caused a lot of issues while I was on batteam. This was happening when people were deleting hearings in VACOLS. The `LegacyHearing` instances we had would get orphaned, and the application would error out. I don't know if there's a good fix for this outside of making sure that people don't delete hearings in VACOLS.

**Comment by ferristseng** [comment]
Related issues that deal with a similar problem with LegacyAppeal: #12791, #12810
PR to add job to discover LegacyAppeals in the dangling state: #13501

**Comment by tomas-nava** [comment]
related #13208
