### ISSUE TITLE
Investigate Hearings Performance Improvement

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12002]
- Investigate use of New Relic Browser for monitoring Performance
- Audit use of serializers -- are there ways to refactor for specific pages, removing unnecessary data
- Audit API calls / Promise chains -- can we render pieces of the page async rather then waiting for promises to finish

**Comment by ferristseng** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/11882#issuecomment-527646796

**Comment by ferristseng** [comment]
Have we had any specific complaints for pages that have been slow in production?

**Comment by jimruggiero** [comment]
@lomaxap @ferristseng Given the merged PRs noted above, can we tell me if this ticket can be closed? If not, what scope still needs to be done?

**Comment by ferristseng** [comment]
I think this is a very broad tech improvement ticket. I think we should log any specific complaints regarding hearings performance, and we can investigate further, but I don't think there's any specific work to be done for this at the moment.

**Comment by pshahVA** [comment]
closed because this ticket isn't actionable.  More tickets can be opened for specific issues.
