### ISSUE TITLE
Only Return legacy ScheduleHearingTasks where Case location is Caseflow

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12011]
related to #10820

In order to prevent deduped appeals from appearing in the assign hearings list, we should only [query legacy appeals](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L30) that are in `CASEFLOW`. We do this currently only for central office hearings

**Comment by ferristseng** [comment]
The related issue was closed, and it seems like there was some uncertainty as to whether or not this might fix the underlying issue anyways. I'm going to close, but if this comes up in batteam again, feel free to reopen.
