### ISSUE TITLE
Tech Spec for Pexip API Integration

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12012]
See [rough notes](https://www.notion.so/navapbc/pexip-dfe4ca4d04c747e7abf217c1f74eef58)

Pexip provides an API that allows us to create a "meeting room" for a host and multiple guests. Each meeting room has a name, host pin, and guest pin that we are responsible for creating and destroying.

### AC

- Documentation on how to interact with Pexip API 
- Tech spec of a caseflow service to interact with Pexip API (see template [here](https://github.com/department-of-veterans-affairs/appeals-team/blob/113f99bedd608499406488569206365e35267489/Project%20Folders/Caseflow%20Projects/Intake/Tech%20Specs/TECH_SPEC_TEMPLATE.md)). This includes: creating a virtual meeting room with a name, guest pin, and host pin (+ more data?), storing that data and relevant data we receive from Pexip response and related it to an appeal / hearing, destroying the virtual meeting at some interval after hearing date.
- Tech spec on how to implement service with front end requirements #11158, #11952, #12170, #11508

**Comment by ferristseng** [comment]
https://github.com/department-of-veterans-affairs/appeals-team/pull/1201
