### ISSUE TITLE
Auto case distribution | Change direct review distribution date

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#12026]
The Board doesn't have enough cases ready for distribution to a judge. They'd like to change one of the variables for auto case distribution, to allow AMA direct review appeals to be distributed to a judge at 275 days waiting, rather than the current 305 days waiting (-60 days from the 365 day timeliness goal).

## AC
- Direct review docket appeals can be distributed at 275 days (90 days before the 365 day timeliness goal)

## Risks of implementing this
- There is no need to be overly conservative with that approximation (i.e. 90 or 120 days before), as that will lead the algorithm to more aggressively ramp up the number of direct reviews distributed.

## Resources
- [Auto case distribution wiki](https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Case-Distribution)
- [2019-05-10 Levers.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/3595563/2019-05-10.Levers.pdf) of auto-case distribution

**Comment by pkarman** [comment]
Should just be a matter of changing this constant:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/dockets/direct_review_docket.rb#L5

**Comment by pkarman** [comment]
@laurjpeterson should I interpret this as 90 days *or* 120 days is an acceptable change?

**Comment by laurjpeterson** [comment]
This should be 90 days, not 120. They want direct docket appeals to be distributed at 275 days instead of the current 305
