### ISSUE TITLE
Close RootTask for LegacyAppeals on dispatch

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12021]
We close the `RootTask` for AMA `Appeal`s when those appeals are [outcoded by dispatch](https://github.com/department-of-veterans-affairs/caseflow/blob/476ae88ec068fcb3815ad9933e20490b11233b86/app/models/tasks/bva_dispatch_task.rb#L28) (and more precisely [here in `AmaAppealDispatch `](https://github.com/department-of-veterans-affairs/caseflow/blob/476ae88ec068fcb3815ad9933e20490b11233b86/app/workflows/ama_appeal_dispatch.rb#L72)). However, we do not ever close the `RootTask` for `LegacyAppeal`s since the corresponding `LegacyAppealDispatch` model does not include similar logic. As a result we have a ton of `RootTask`s related to `LegacyAppeal`s that should be closed and are instead open. This ticket exists to mark `RootTask`s related to `LegacyAppeal`s as complete when the appeal is outcoded.

![image](https://user-images.githubusercontent.com/32683958/64568280-5897b280-d328-11e9-822d-e564867b0640.png)
_[Source: Looker](https://caseflow-looker.va.gov/sql/xvnpqxsfvqfh6r)_

## Acceptance criteria
* [ ] Mark `RootTask`s related to `LegacyAppeal`s as complete when the appeal is outcoded.
* [ ] Maybe close `RootTask`s associated with dispatched `LegacyAppeal`s (determine if it is easy/worthwhile to make this production data update).

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||
2 | |||||||
3 | |
5 | 
8 | 
```

Could be an easy fix if testing is straightforward.
