### ISSUE TITLE
Improve performance of adding users to organizations

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#12036]
Currently, team/organization admins can navigate tp the URLs: `organizations/<org name>/users` to add users to their team/organization. The dropdown on this page is very slow when users type in names/CSS IDs. This is likely because there are ~18,000 Caseflow users in this dropdown.

## AC
- Investigate slow performance of this dropdown across all organizations in Caseflow (business lines, Board branches, etc.)
- Suggest solutions for improving performance

**Comment by pkarman** [comment]
tech note: I recently changed the /test/users endpoint to get rid of pre-loading all 18k+ users. I suggest we move to a remote autocomplete pattern instead of preloading the entire users table (which also represents a security flaw).

**Comment by msj0nes** [comment]
@laurjpeterson  VHA and OIT is requesting an update on when to expect this to be completed. Related to YourIT ticket INC7193329 opened 2 months ago. 

**Last Follow Up**: Sept 24th 
https://dsva.slack.com/archives/C6E41RE92/p1569349181016500?thread_ts=1569348669.016400&cid=C6E41RE92

**Comment by laurjpeterson** [comment]
Hi there - I don't have a time estimate to share with those stakeholders. Right now, we'll have to respond that it's still in the backlog. Is it possible to close the YourIT ticket because it's in our backlog so it doesn't affect our support team metrics?

**Comment by msj0nes** [comment]
@laurjpeterson unfortunately I can't. 

Any quick fix possibilities?

- Place a condition for add users for business line URLs where the list only populates for users with CSEM function 'Mail Intake' or 'Admin Intake'.  Right now the list just searches everyone with CSEM access. We don't necessarily have to fix the other organizations as they aren't using the add users function themselves (support team does). 

- As Peter prescribed, remove the autocomplete typing feature (or until the user gets to the last name). Currently it starts after the first letter is entered.
