### ISSUE TITLE
Prevent creation of child tasks of TimedHoldTasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12037]
`TimedHoldTask`s [should not have any child tasks](https://caseflow-looker.va.gov/sql/dns58vwdwyszry) (because they themselves are simply indications that the parent task is on hold for some period of time) but that is not strictly enforced in the code anywhere. This ticket exists to add a guardrail to prevent the creation of child tasks of `TimedHoldTask`s in the code. If we come up with a generic solution here, consider reusing it to satisfy #11996 by making the code "self-documenting".

## Acceptance criteria
* [ ] Prevent creation of child tasks of `TimedHoldTask`s in the code

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |
2 | |||||
3 | ||||||
5 | 
8 | 
```

Purely preventative. This has not actually happened. Scope of the ticket is pretty straightforward. Estimating at a three if we attempt to generalize this to the base model early. Also is a different way to restrict parent/child relationships.
