### ISSUE TITLE
Prevent creation of duplicate TrackVeteranTasks in update representation job

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12055]
A [Looker alert](https://caseflow-looker.va.gov/looks/183) notified us that there were two appeals with multiple open `TrackVeteranTask` assigned to the same VSO ([example Slack notification](https://dsva.slack.com/archives/CLRTL92TW/p1568210468097100)). This ticket exists to address the root cause of one of those scenarios (ticket #12054 exists to address the other).

Given the example appeal below, it appears that [the `UpdateAppellantRepresentationJob`](https://github.com/department-of-veterans-affairs/caseflow/blob/6233df2662fb44e736bb7ef2bf88c56be3151b84/app/jobs/update_appellant_representation_job.rb#L5) can create multiple `TrackVeteranTask`s for the same representative. This ticket exists to prevent that from happening.

```ruby
rails c> puts Appeal.find(12618).structure_render(:id, :status, :assigned_to_id, :created_at)
# Appeal 12618
# └── RootTask 286947, on_hold, 2, 2019-07-23 12:22:22 UTC
#     ├── DistributionTask 286948, assigned, 2, 2019-07-23 12:22:22 UTC
#     ├── TrackVeteranTask 342980, in_progress, 4, 2019-08-21 15:08:09 UTC
#     ├── TrackVeteranTask 342981, in_progress, 4, 2019-08-21 15:08:09 UTC
#     ├── InformalHearingPresentationTask 342982, assigned, 4, 2019-08-21 15:08:09 UTC
#     └── InformalHearingPresentationTask 342983, assigned, 4, 2019-08-21 15:08:09 UTC
```

For what it's worth, this ticket is probably not worth prioritizing highly because it appears to happen rarely, does not have a significant negative impact, and is fairly easy to recover from manually.

## Acceptance criteria
* [ ] Determine why the job creates multiple `TrackVeteranTask`s for the same representative
* [ ] Prevent it from happening again

**Comment by lowellrex** [comment]
Resolved the data problem that caused the alert by cancelling the newer task:
```ruby
rails c> TrackVeteranTask.find(342981).update!(status: Constants.TASK_STATUSES.cancelled)
```

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||
2 | ||||
3 | ||||||
5 | 
8 | 
```

Could be a one as this sounds pretty simple. Investigation could take quite a bit of time to track down why this is happening (as a few hours have already been dedicated to investigating this).
