### ISSUE TITLE
VacolsRecordNotFound error

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12053]
Sentry Alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5883/

See this thread for more info: https://dsva.slack.com/archives/C42P25D6H/p1568136245012200

https://github.com/department-of-veterans-affairs/caseflow/blob/3e03aa0d3aa15e13b15ae04b1c8f8eab848ce307/app/models/tasks/generic_task.rb#L102

**Comment by jcq** [comment]
Here's a new Sentry alert (VACOLS ID 677353):
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7089/

**Comment by hschallhorn** [comment]
Here's another flavor of alert due to a deleted appeal in vacols: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7869/?referrer=webhooks_plugin

**Comment by yoomlam** [comment]
Another one (VACOLS ID 715639): https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7890

**Comment by rubaiyat22** [comment]
Another one (vacols_id: 715845): https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7089/?referrer=webhooks_plugin

**Comment by ferristseng** [comment]
Renaming this since the issue on the case details page should be fixed, but it's still causing issues in other areas.

Ticket to investigate how many hearings this affects: #12003
