### ISSUE TITLE
Shows tasks in Attorney queue

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12059]
> Attorney's queue page must pull both types of cases: legacy appeals from Caseflow tasks table and legacy appeals from Vacols that match attorney's location

Ensure that the attorney's queue is returning the newly created `AttorneyTask`s from #12022

`AttorneyLegacyTask` is the old way of tracking the task after it gets assigned to an attorney. We shouldn't return these tasks for the new workflow: 

https://github.com/department-of-veterans-affairs/caseflow/blob/3ad02facb015b7228fb646eb75118546876ba430/app/models/legacy_tasks/attorney_legacy_task.rb#L23-L25

The query to fetch tasks:

https://github.com/department-of-veterans-affairs/caseflow/blob/3ad02facb015b7228fb646eb75118546876ba430/app/models/queues/legacy_work_queue.rb#L22-L37

Here's where it gets called:

https://github.com/department-of-veterans-affairs/caseflow/blob/3ad02facb015b7228fb646eb75118546876ba430/app/controllers/legacy_tasks_controller.rb#L24-L31

If the `FeatureToggle` is enabled, we could utilize the existing `AttorneyQueue` to get tasks for the user.

The request gets routed from `/queue/:user_id`:

https://github.com/department-of-veterans-affairs/caseflow/blob/1bc8f57748b8834d8dadef658715cf1a4904fb63/config/routes.rb#L221

**Comment by ferristseng** [comment]
I think this actually might not require any changes, but the refactors I made might still be useful

**Comment by jimruggiero** [comment]
@ferristseng Given your comment on 9/19/19, can this one be closed? If not, can you work with @pshahVA to update/clarify the current scope of this issue? Also, is there a user story we can add to provide some context? Curious whether this is truly a Tango issue to resolve for hearings cases, or if this is something for Echo? Let me know your thoughts. Thanks!

**Comment by ferristseng** [comment]
I think this should move to Echo since they are taking on implementing DAS deprecation. This ticket was created to address this part of the tech spec (https://github.com/department-of-veterans-affairs/caseflow/issues/9930):

> Attorney's queue page must pull both types of cases: legacy appeals from Caseflow tasks table and legacy appeals from Vacols that match attorney's location

I think the behavior described in the tech spec already happens, and requires no further modification, but someone from Echo will need to confirm.

**Comment by pshahVA** [comment]
Yes, we can move it.  Tango did some preliminary DAS deprecation work when there was a slow period for tango.  @lomaxap did the knowledge transfer on this to Echo.

**Comment by jimruggiero** [comment]
Thank you @pshahVA and @ferristseng !
