### ISSUE TITLE
Manager View | Default "Number of people" to yesterday's value

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1206]
Currently, if the "Number of people" is not manually entered by the manager on a given day, there appear to be no cases in the queue to complete. When processing claims, claim assistants want to know how many cases they need to work that day -- sometimes they need to know this information before a manager has time to log in and manually set the value.

## Acceptance Criteria
- When the "Number of People" field is set, validate that the next day, the "Number of People" field is set to the same value.
- Validate that the "Number of People" field is still changable from that default.

### Current State

(**Claim Assistant view - no workers assigned by manager**)
![0 cases assigned dispatch](https://cloud.githubusercontent.com/assets/4042181/23953325/a5b22c42-096a-11e7-8a8d-65add8af0b34.png)

(**Worker view - default number of people field**)
![screen shot 2017-03-15 at 10 35 01 am](https://cloud.githubusercontent.com/assets/4042181/23953484/163082fc-096b-11e7-8305-9c9b721c69f0.png)

**Comment by abbyraskin** [comment]
@shanear @lakohl re-pinging...this issue came up again this morning. it's confusing for users to have no cases assigned to them at the beginning of the day (may not be as big of an issue when george has access -- though some CAs start earlier than him). can we set this to default to the same # of people assigned the day before?

**Comment by shanear** [comment]
@abbyraskin anything is possible 😄

I think that would be a relatively easy change too.

**Comment by slj** [comment]
@shanear did you address this?  While at ARC George mentioned that the workers count was not 0 this morning.

**Comment by shanear** [comment]
@slj Not that I know of. Might want to continue looking into it

**Comment by abbyraskin** [comment]
@shanear @slj FYI it is still resetting to 0 after all -- just asked George.

**Comment by slj** [comment]
Got it.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers:Chrome and FF

Steps to Validate: 
1. Go to dispatch as a manager and set the number of employees to a value greater than 0
2. Return the next day (24+ hours) to see if the number set on the following day is the same

Value set yesterday: 2
Screenshots: 
<img width="1217" alt="screen shot 2017-04-07 at 7 01 22 am" src="https://cloud.githubusercontent.com/assets/23038505/24797748/ad5f0fac-1b60-11e7-86a1-b09a8b2e17aa.png">
