### ISSUE TITLE
Change claim label depending on the date of the VA decision

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#12072]
When an issue/contention is chosen for a decision review, VBA wants to understand the level of effort for changing which EP claim label we use depending on the date of the decision. 

For example:

If issue A is selected for a Supplemental Claim, that was from a VA decision more than 1 year from today's date, use claim label X.

If issue B is selected for a Supplemental Claim, that was from a VA decision less than 1 year from today's date, use claim label Y.

### Acceptance criteria
- this is behind a feature toggle, so that it can be thoroughly tested in VBMS before using it in prod

Notes:
- Branch off issues into "older than" and "newer than"
- PR to refactor code for selecting EP is related; pass the decision date to EP code selector and add EP codes to multiple places
- Check adding and follow-up touch points for EPs in code
- Checking if there are any side effects of there being a third EP establishment on claim review (likely no, but want to validate this)
- Potential Risk: Historically when receiving claim labels, more than anticipated are received and there's extra work to implement new labels

**Comment by leikkisa** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/13647
