### ISSUE TITLE
Show alert to user if Duplicate Veteran record found

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12077]
### Story
When a veteran has a duplicate record, with a different participant ID, establishing their claim fails.

Related #11742

### Acceptance criteria
1. When a user searches for a veteran in intake, if that veteran has a duplicate record show the user an error alert
1. The error alert should include both participant IDs for the veteran, instructions to create an incident in YourIt, and to try again after that has been resolved

### Copy (draft)
This Veteran has a duplicate record in CorpDB.  Please submit an incident in YourIT requesting that the duplicate record be removed.  Include the veteran's first initial, last name, the last 4 digits of their file number or SSN, and both of the following participant IDs: [participant_id1, participant_id2].

Note, please make YourIT a link.  Feel free to make improvements to the copy.

### Technical notes
- Check if the SSN matches the BGS record soc_sec field
- If they do not match, then you can use BGSService find_by_ssn, to get the other participant ID with the soc_sec number.  If the participant ID does not match the veteran's participant_id in Caseflow, then show the alert

**Comment by tomas-nava** [comment]
This is what the alert looks like:

![Screen Shot 2019-11-01 at 2 34 35 PM](https://user-images.githubusercontent.com/45415133/68143679-cf939680-fee6-11e9-9603-aea6990870f4.png)
