### ISSUE TITLE
Add updated_at to the cached_appeal_attributes table to inform bug investigations

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12070]
While investigating the job failing to run in #12069 we realized it would be nice to have an `updated_at` and `created_at`  value for the rows, especially since some rows get touched twice per run of the job!

This ticket is to add that column & make sure it gets updated appropriately by the job.

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||||||||||
2 | 
3 | 
5 | 
8 | 
```

Simple migration. Not a 0 though. Sorry.
