### ISSUE TITLE
TypeError BULK_ASSIGN_BUTTON_TEXT

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#12081]
[Sentry link](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6539/)

TypeErrorapp/queue/components/BulkAssignButton in BULK_ASSIGN_BUTTON_TEXT
Cannot read property 'map' of undefined

**Comment by hschallhorn** [comment]
Saw only once and have not seen again. Closing.
