### ISSUE TITLE
Filtering by Case Type should be additive

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12082]
![image](https://user-images.githubusercontent.com/32683958/64821899-d99db680-d581-11e9-8ef8-1ff33d69e640.png)

## Acceptance criteria
* [ ] Selecting options in addition to "AOD" in the "Type(s)" column shows those options even if they are not AOD for organization queues using the pagination API

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||||||||
2 | ||
3 | 
5 | 
8 | 
```

Could be a two based on past heartbreak with filtering and sorting flakes. Should be a simple update from an AND to an OR and a quick test.

**Comment by yoomlam** [comment]
@lowellrex and I did a pairing session on Sept 27th for this ticket. The fix for this specific issue was straightforward, but when testing we uncovered a bigger issue that warrants another ticket (something about filtering on multiple columns maybe). Not sure why Lowell didn't assign this ticket to himself and didn't commit his fix.

**Comment by yoomlam** [comment]
To reproduce, http://localhost:3000/organizations/vlj-support as "VLJ_SUPPORT_ADMIN (VACO)".

"AOD" filtering option is only enabled for tables with pagination, which is enabled for organizations.
From Hunter:
> We're attempting to consolidate all the different queue views into one
> relevant tickets:
> https://github.com/department-of-veterans-affairs/caseflow/issues/10032
> https://github.com/department-of-veterans-affairs/caseflow/issues/10044
> https://github.com/department-of-veterans-affairs/caseflow/issues/11698
> and a bunch more!

**Comment by yoomlam** [comment]
Examining React component tree for the page, QueueTable's props.rowObjects always has the same 5 objects, while its child component BodyRows's props.rowObjects changes depending on the filtering selection. Hence, rowObjects are being filtered somewhere in between.

QueueTable's constructor calls requestTasks(), which calls endpointUrl for filtering the tasks, e.g., `/organizations/vlj-support/task_pages?tab=assigned&page=1&filter%5B%5D=col%3DtypeColumn%26val%3Dis_aod`

Route /organizations/{org.url}/task_pages
is controlled by Organizations::TaskPagesController (task_pages_controller.rb:42)
which calls task_pager.rb:39
which calls task_filter.rb:40 and 49  <--- bingo!
