### ISSUE TITLE
Search label text in Queue > Reader reads "Search small" by AT. It should just read "Search"

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12101]
The label for the search element is incorrectly read as Search Small for assistive technology users. Visually the label reads: Type to Search. This defect occurs throughout the web hosted application with the search function improperly being read as Search Small. (New: 08/27/2019) Ensure you can hear what is visually being seen to ensure compliance

Noting – we should also check the search tips and make sure those are also associated with the search input as well.

**Comment by yoomlam** [comment]
Reproduced at http://www.caseflowdemo.com/search using VoiceOver focused on search field, as well as associated label.

https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html:

> In some situations, elements can be given the attribute aria-label to provide an accessible name for situations when there is no visible label due to a chosen design approach or layout but the context and visual appearance of the control make its purpose clear.

**Solution**
Setting the label as an empty string (when a `title` is not specified) causes VoiceOver to skip the label entirely, which makes sense in this case (there’s other perhaps redundant descriptions of the search field).
