### ISSUE TITLE
Create Utility to Enable DAS Deprecation Feature for Judge and Attorney Team

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12108]
Right now, the `FeatureToggle` API is pretty limited with. It can enable a feature for a single user, or an RO, but not for a Judge/Attorney team. Since the DAS deprecation workflow will be piloted with a Judge/Attorney team, we should add an easier way we can enable this in prod. I imagine it can be in the form of something we can run from the rails console.

Something like this?

```
FeatureToggleForJudgeTeam.enable(judge_css_id)
```

It could iterate through the Judge's attorneys and enable the flag for all existing attorneys:

https://github.com/department-of-veterans-affairs/caseflow/blob/155e7a34be411c0cfc8f64904bd019defbbbc7b4/app/models/judge.rb#L9-L11

This would only enable the feature flag for existing attorneys. New attorneys would need to have the flag enabled manually.

**Comment by pkarman** [comment]
Since feature toggles are ultimately controlled via the .yml file in appeals-deployment, how would this feature differ from simply outputting the list of users as .yml for copy/paste into a PR?

**Comment by ferristseng** [comment]
Oops, didn't realize that was how we set feature flags in prod. I think that would work better! Going too close...
