### ISSUE TITLE
Add POA email address to hearings details

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12102]
### User Story:
As a hearings branch member, I need to be able to schedule a virtual hearing.  This requires Caseflow to have the POA email.   Add the POA email to the information that is displayed in the CaseDetails page, similar to how we have it for the Veteran.  In addition, the hearings team needs to be able to update the POA email address just for use with this hearing.

### Designs:
Display-only POA email address on Case Details:
![CaseDetails_POA_email.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/e1cfeb4d-e62d-47ca-810d-151dcd70b22a)

### Acceptance criteria: 
The email is visible if available.
### Feature Toggle: 
no
### Technical notes:  
Please look in the person record in BGS under :email_addr=>

**Comment by pshahVA** [comment]
@lomaxap, the difference here between the veteran email, is that we are adding the capability to change it, so we would have to store it. However, it only makes sense to tie it to a hearing.

**Comment by nicholer** [comment]
@pshahVA I added a visual for the display-only email address in the Power of Attorney section.

Correct me if I'm wrong, but edits will happen from Hearing Details at the time a virtual hearing is scheduled, and therefore won't affect/update the email here on Case Details.

**Comment by lomaxap** [comment]
> won't affect/update the email here on Case Details

Right

@pshahVA, I don't think we should be storing email addresses that conflict with BGS records. It's hard to keep track of which is stale and which is up to date and to know which ones to use where. Since this is only for virtual hearings, when we save the virtual-related data, maybe we can also save along side it the email address *at the time of that hearing*.  

We should set up some time to talk about this more thoroughly. Maybe during design sync?

**Comment by pshahVA** [comment]
@nicholer, you are right, its only where we are scheduling the virtual hearings.
@lomaxap, I was thinking along the same lines as you.  After talking to the hearings branch, nichole, and then a quick call with Peter (as he was helping me find the data), this was the reasoning and the problem I was trying to solve.
1.) Veterans and VSO's may have very old email addresses in the system (ie @aol.com or somthing).  In this case the hearings branch had expressed interest in changing email on the fly.
2.) A veteran already has an email address on file but has the following thought, "I don't understand this virtual hearings stuff so I'll have my daughter handle this for me, can you please send the email to her as she will set this up for me?"
3.) The VSO email is a generic org email, but the invite has to go to the VSO in charge of the hearing.

In the scenarios above, I don't want to change the email of record, but instead have a means of stating that this email you give us "is only for this hearing" and I only want to tie it to the hearing record.  I didn't know how else to make the experience better flowing for the Veteran and the hearings branch.  Let me know if you have any other ideas or thought that can make this better?

**Comment by pshahVA** [comment]
I thought this was complete?
