### ISSUE TITLE
Migrate pending incomplete and uncancelled task timers alert from Looker

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12111]
[Looker is going away](https://github.com/department-of-veterans-affairs/caseflow/issues/12068) and we need to migrate the [pending incomplete and uncanceled task timers alert](https://caseflow-looker.va.gov/looks/199) from Looker into Caseflow application code.

## Acceptance criteria
* [ ] Pending incomplete and uncanceled task timers alert is running in Caseflow application code.

**Comment by kevmo** [comment]
Possibly helpful references:
example SQL: https://github.com/department-of-veterans-affairs/caseflow/pull/12065

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/data_integrity_checks_job.rb

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||
2 | |||||||
3 | ||
5 | 
8 | 
```

Could be a one as we already have the data integrity check written and testing is straightforward. Replicating behavior from one environment to another could introduce unseen bugs.
