### ISSUE TITLE
Allow Judges to Cancel AttorneyTasks & Return Cases to JudgeAssignTask

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12115]
Spun out of this discussion in slack: https://dsva.slack.com/archives/C6E41RE92/p1568660503005300

There's been scenarios where a Judge or SSC wants to take a case back from an attorney while BVA clarifies something. They don't want to reassign to someone else just hold it until clarification is done and then address assigning it to an attorney later. 

This **shouldn't** include any cases with a task created by the Attorney for VLJ support or any other dept opened, but only for cases where the `AttorneyTask` is a leaf node in the task tree, with status either `assigned` or `in progress`

Questions:
  - Should this be available if there are any closed VLJ support tasks under the attorney task?
  - Should this be available for `AttorneyRewriteTasks`, `AttorneyQRTask`, and `AttorneyDRTask`s?

**Comment by kevmo** [comment]
1 |
2 | |||||
3 | ||||||
5 | |
8 |

Answer to first question is probably yes.  Second question - does it matter?  But probably yes.

Make sure you check Slack messages for commands run.

3.  Potential 5 - inserting this into user flow could be more complex than manually changing database.

**Comment by hschallhorn** [comment]
Currently, `AttorneyTask`s are not created in caseflow for legacy appeals, however, there is work to start doing this with the depreciation of DAS in #12022. It seems unwise to attempt to wrestle with vacols and case assignment and reassignments if we are going to be using `AttorneyTask`s in the near future. Also, of all the cases where the Bat Team has manually done this, each appeal has been an AMA appeal. Proposing to either 
1. Call this done once ^ is merged
2. Add #12022 as a blocker

**Comment by kevmo** [comment]
Blocked by #12022. 

Once #12022 is completed and PR #12295 is merged, this functionality described by this ticket _should_ exist.  We are leaving this ticket open as a reminder to check back in and make sure that is actually the case.

**Comment by lomky** [comment]
#12022 is closed & #12295 complete! How's this looking @hschallhorn @kevmo ?

**Comment by hschallhorn** [comment]
<img width="1026" alt="Screen Shot 2019-11-04 at 9 49 55 AM" src="https://user-images.githubusercontent.com/45575454/68129955-82b0bf80-fee8-11e9-8800-86392882f950.png">
🚀
