### ISSUE TITLE
Prevent DecisionReviewTask from work when zero active request issues

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12110]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6584/

If a task's decision review no longer has any active request issues, the task is supposed to be closed (see #11963). However, we are seeing instances where that did not happen.

If a task has zero actionable request issues, it should not show in the LOB noncomp queue for work.

## AC

- [x] Hide noncomp DecisionReviewTasks that cannot be worked on.
- [x] Create DataIntegrityCheck job to proactively close tasks that cannot be worked.

**Comment by leikkisa** [comment]
I canceled the following "DecisionReviewTasks" that were assigned and had no active request issues:
[227629, 171353, 270379, 225103, 225579, 402032, 293867, 336230, 338052, 382189]

All of them had one ineligible request issue

**Comment by pkarman** [comment]
I think we're proactive enough on this now to close.
