### ISSUE TITLE
<<blank>> shows up as a filter option but is not filterable when pagination is enabled

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12129]
<img width="893" alt="Screen Shot 2019-09-17 at 11 46 25 AM" src="https://user-images.githubusercontent.com/45575454/65057591-d5d2b100-d940-11e9-8060-41f70d8c1f2f.png">

This can be caused by two things

### There is a nil value in one of the table columns paged tasks pulls from

This is only slightly handled by [`QueueFilterParameter`](https://github.com/department-of-veterans-affairs/caseflow/blob/ca72dbc018f74e90f64c19fae5710ffc1d89ce70/app/models/queue_filter_parameter.rb#L32) where we convert the `<<blank>>` value to nil, but we cannot filter on it as [SQL ignores](https://www.techrepublic.com/article/oracle-tip-understand-how-nulls-affect-in-and-exists/) `NULL` in `WHERE ... IN` statements, which is the [phrasing we use](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task_filter.rb#L48) for our raw sql to filter tasks.

### There is no cached appeal in the cache_appeals_attributes table for said task

When there is no cached appeal associated with a task's appeal, we don't have anything to filter on if the filter is a column from the cached appeal table. Fixing the above scenario and slightly modifying the type of joins used for filtering should fix this

## AC 

- [ ] Appropriate tasks are returned when filtering on nil values for
  - [ ] nil values in one of the tables
  - [ ] no associated cached appeal

**Comment by hschallhorn** [comment]
Kick this to product to discuss with users if:
- [ ] Blank is being displayed to users at all
- [ ] What they believe it means
- [ ] If just not displaying that filter is an acceptable fix (?)

TODO: Write ticket to create an alert to notify us when something is blank in the cache_appeals_attributes table when we wouldn't expect it to be.

**Comment by lomky** [comment]
@jimruggiero this ticket could use some help from Product! See @hschallhorn comment above.

**Comment by hschallhorn** [comment]
> Kick this to product to discuss with users if:
> 
> * [ ]  Blank is being displayed to users at all
> * [ ]  What they believe it means
> * [ ]  If just not displaying that filter is an acceptable fix (?)

Blank IS being show to users as our cached appeal job fails more regularly (see #15716)
