### ISSUE TITLE
Add medium importance Prometheus metrics

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1213]
Add these metrics to the metrics endpoint.

- [ ] response size of BGS requests [gauge, summary]
- [ ] response size of VBMS requests [gauge, summary]
- [ ] duration of job processed by name [gauge]

Also, can we add them in such a way that they can be added to eFolder too?

see for reference: https://github.com/department-of-veterans-affairs/appeals-deployment/issues/451

**Comment by nickheiner-usds** [comment]
@askldjd @shanear do we still need this ticket?

**Comment by shanear** [comment]
I think we've covered this.
