### ISSUE TITLE
Change Headway App to Widget

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12146]
## User Story
The headway app is implemented in production successfully, however it is hard for the end user to gain visibility into when a change has occurred unless they actively click on the release notes menu item.  If a widget is used instead of a link then it can show an icon when something has changed.

## AC
The widget for headway shows up and it updates when changes are made to the release notes.
Designs
## Feature Toggle
yes
## Release notes
Please include screenshot of this working.

**Comment by jimruggiero** [comment]
@pshahVA should this move to the Backlog?

**Comment by ferristseng** [comment]
Widget: https://docs.headwayapp.co/widget
