### ISSUE TITLE
Investigate Judge Email address

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12147]
### User Story
As part of virtual hearings, the system will need to send an email to a judge.  This ticket is to investigate if that email is available to Caseflow and if it can be accessed at the time of scheduling a virtual hearing.

## AC
The email is available and ready to be used for virtual hearings.

## Feature Toggle
n/a

**Comment by pshahVA** [comment]
@nicholer, do you think we need to display this or allow the user to change it?  I figured these do not change much.

**Comment by nicholer** [comment]
I assumed we wouldn't display it or allow the Hearing Coordinator to change it. I could very well be wrong, but I would expect Caseflow user account emails for VA employees to be their VA email address?

I'd be interested to learn more about what, if any, account management UI exists. I can't tell from demo.

**Comment by pshahVA** [comment]
@lomaxap confirmed that we have this.
