### ISSUE TITLE
Review Decision | Special Issue Categories columns differ in height on IE

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1215]
# Description
When a Caseworker starts a new Task for Establishing a claim and Reviews Decision
And then scrolls down to select a Special Issue categories (on IE11).

**Expected behaviour:** columns to be the same ( or 1>= difference) in height.

**Environment:**
- [ ] Production
- [X] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [X] Design
- [ ] Security
- [ ] Functional
 
# Reproduction Steps
Scenario 1 - Reviewing Decision

1. Got to Dispatch

1. Click **Establish next claim**

1. Scroll down to *Special Issues*

1. Be sad

## Screenshots
**_Scenario 1 - Review Decision in IE11_**
![screenshot_2017-03-16_09-55-42](https://cloud.githubusercontent.com/assets/18075411/23999659/6bb49640-0a2f-11e7-9007-40d9ab95d417.png)

**_But it, should look like this:_**
<img width="1005" alt="screen shot 2017-03-16 at 2 07 08 pm" src="https://cloud.githubusercontent.com/assets/4975959/24015843/166f1aee-0a60-11e7-831a-2dfe7178c114.png">

**Comment by mmlumba** [comment]
Sending back to in-validation since it might be another old ticket

**Comment by kierachell** [comment]
**PASSED**

Will just remake this when someone says "ugh" again
