### ISSUE TITLE
Research: "Withdraw hearing" -> "Cancel hearing request" label change

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12168]
discussion: https://dsva.slack.com/archives/CHX8FMP28/p1568822584039000

https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/TASK_ACTIONS.json#L224

Proposed language change would help clarify for users. UX research needed.

**Comment by msj0nes** [comment]
## Amplifying the need to get the verbiage changed
Conversation with Hearing team member who submitted 3 tickets for one veteran on an action that she can complete herself but was concerned about 'withdrawing' a hearing already held thinking it would edit that hearing detail. 

![image](https://user-images.githubusercontent.com/41164406/65703204-605a9500-e052-11e9-8d83-d98a365e6787.png)

**Comment by pshahVA** [comment]
@nicholer  for awareness
