### ISSUE TITLE
BGS::ShareError No Records Returned

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12166]
## Description
We're getting alerts for BGS::ShareError: No records returned, when syncing an established end product. This may be related to de-duping veteran records. When I looked up the veteran by participant ID, I got a different record for them. The current filenumber and SSN don't match, and no longer return a veteran record.

- [ ] Add an error class to ruby-bgs so that this doesn't come to us as a generic BGS::ShareError, and can be rescued and handled
- [ ] Investigation: Look at Sentry cases and check if we can reliably find a new file number for them.

## Out of scope
There is another ticket that is a partial dupe (for implementing a fix) #7734.  I think it's worth adding the BGS error class, and investigating the solution first, and then moving onto implementation.

## Background/context/resources
Example: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6641/events/570362/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6641/events/482296/

Related: https://github.com/department-of-veterans-affairs/caseflow/issues/7734

**Comment by nanotone** [comment]
Related to #12158

**Comment by nanotone** [comment]
1. PR for the new ShareError subclass: department-of-veterans-affairs/ruby-bgs#86
2. I investigated 5 recent "No records returned" errors, by looking up the participant ID in BGS and seeing if the returned record was usable for each veteran:
- In 4 out of 5 cases, the new record matched our veteran's full name.
  - For 3 of these, the SSN/file number was clearly a corrected typo -- 2 had adjacent digits swapped, 1 was off-by-one).
  - For the last one, the SSN/file number was significantly different, but the birthdate matched so I'm confident it's the same person.
- In 1 case out of 5, the participant ID also didn't exist in BGS.
