### ISSUE TITLE
Support Service Degraded Mode

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#1216]
This issue is created from the [BGS Outage Postmortem](https://github.com/department-of-veterans-affairs/appeals-deployment/issues/531).

During backend outages, we should put up a banner to warn the users that the service quality is degraded.

This is not out-of-service mode where we block all features from the site. Under this mode, the site should continue to operate.

**Comment by laurjpeterson** [comment]
Closing, because we have monitor and Caseflow StatusPage
