### ISSUE TITLE
Allow Hearings Coordinators to sort by POI

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12176]
## User Story: 
When a hearings coordinator schedules a hearing, they want be able to filter by POA (Power of attorney)
## AC
Veterans can be filtered by their POA.

Release notes
Yes

## Feature Flag: 
No

**Comment by pshahVA** [comment]
@alisan16 , I noticed you placed a bug label on this, but this is a new feature that we need to work on.

**Comment by alisan16** [comment]
@pshahVA I was mass migrating `bug-medium-priority` to `bug` and `priority-medium` labels since you originally added `bug-medium-priority`. Feel free to remove if it's not accurate.

**Comment by pshahVA** [comment]
@alisan16 , then I originally mislabeled it.  I just didn't want to break any kind of system you were working on.

**Comment by pshahVA** [comment]
I am closing this as I see it was addressed by #12418
