### ISSUE TITLE
Assign view - do not show "Loading..." if there are no options

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12177]
### Story
When a judge was in their queue in the "assign" view, they could not assign tasks to attorneys.  In the detail view, they could reassign to a judge.

This specific judge didn't have any attorneys on their team.  It would be great if there's a way to indicate to the judge that there are no users on their team instead of "Loading" which could be misleading.

![image (3).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/7a442497-fdb6-4e2d-aec9-dd4783e61442)

![image (4).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/51299303-f317-4629-bd13-af293a6de7a1)

### Context
https://dsva.slack.com/archives/CHX8FMP28/p1568928563074500

**Comment by lomky** [comment]
@leikkisa That is not a list of users on the judge team, but rather a list of all users. Was this behavior you were seeing in production?
