### ISSUE TITLE
Integrate Email Service with Caseflow

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12182]
### User Story:
The caseflow system needs to be able to access the email functionality and build the appropriate methods to call the AWS lambda function.

## Release notes
n/a

## Feature flag
no
## Permissions: 
n/a

**Comment by pkarman** [comment]
which email service is this? AWS SES? https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/setting-up-ses.html or some VA service?
