### ISSUE TITLE
App Canvas | Cancel/Back/Close button incorrect hover and onClick styling; also potential JS error (in IE)

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1219]
# Description
When a Caseworker is working on a Claim;
if a Caseworker attempts to _Cancel_ a claim or _Go Back_ at any point in the process;
The `hover` and `onClick` styling for links turns them into a `btn-primary` styling (see screenshots)
*Expected Behaviour* see Styleguide or Designers.

*NB* Sometimes, it seems, that clicking on the link will freeze the page for several seconds.
JS Error:
```
TypeError: Unable to get value of the property 'getItem': object is null or undefined 
```
**BONUS** JS error:
```
Unhandled promise rejectionTypeError: Object doesn't support property or method 'requestAnimationFrame' 
```

**Environment:**
- [X] Production
- [X] UAT
- [ ] Demo
- [ ] Development

might be Internet Explorer specific

**Type of Bug:**
- [X] Performance
- [X] Design
- [ ] Security
- [ ] Functional
 
# Reproduction Steps
Scenario 1 - Canceling

1. Got to Dispatch

1. Click *Establish next claim*

1. Click _Cancel_ on the bottom of *Review Decision* page

1. Click _Close_ in the modal

## Screenshots
**_Scenario 1 - Dispatch_**
![dispatchcancel](https://cloud.githubusercontent.com/assets/18075411/24013628/6627d1f0-0a58-11e7-8e12-f0445154d8c9.gif)

**Comment by mmlumba** [comment]
@kierachell Which browsers is this reproducible in?

**Comment by kierachell** [comment]
Hah, sorry with late reply @mmlumba I should've mentioned that in the ticket (not just the title).
This is IE11.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers tested: Chrome and FF

Steps to Validate: 
1. Go to Dispatch as a caseworker, establishing a claim
2. Hover over the Cancel button on the Review Decision page
3. Notice that only the color of the text darkens
4. Select the Cancel button
5. On the Stop Processing Claim modal, hover then select the Close button
6. Notice that the text of the button only got darker

Screenshots: 

<img width="1304" alt="screen shot 2017-04-05 at 10 12 21 am" src="https://cloud.githubusercontent.com/assets/23038505/24711365/be53aada-19ed-11e7-9e68-a394341d1951.png">

See the modal in the forefront and the page in the background
