### ISSUE TITLE
Create an alert for nil values in the cache_appeals_attributes table

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12209]
As discussed when estimating #12129, we don't expect any values in `cache_appeals_attributes` to be nil (other than things such as vacols_id for ama appeals). This alert should ignore appeals with no open tasks.

## AC
- [ ] Alert notifies #queue-app-alerts slack channel about nil values in  in the `cache_appeals_attributes` table
- [ ]  Alert should include details about how to fix next.

**Comment by hschallhorn** [comment]
[See this guide](https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/setting-up-a-caseflow-cron-job.md)

**Comment by kevmo** [comment]
1 | |||
2 | ||||||
3 | |||
5 |
8 |

2.  Potential 1 because this seems easy.  Potential 3 because of testing.
