### ISSUE TITLE
Legacy Cases being moved back to Location 55

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12215]
https://dsva.slack.com/archives/CHX8FMP28/p1569353446139100

Investigate this further. @lomaxap suggested it could be caused by the `hearing_disposition_change_job`.

I noticed that one of the tasks seemed like it was modified by the job because the `updated_at` timestamp was a few minutes after the job ran:

```
AssignHearingDispositionTask updated_at

  2019-08-15 05:01:45 UTC


HearingDispositionChangeJob ran at 1:08 AM EST on 08-15

HearingDispositionChangeJob completed after running for 7 minutes. Processed 17 No show hearings. Processed 89 Held hearings. Processed 16 Cancelled hearings. Processed 11 Postponed hearings. Processed 3 Between one and two days old hearings. Processed 1 Stale hearings. Processed 0 Unknown disposition hearings. Encountered errors for 2 hearings.

https://dsva.slack.com/archives/C4JECDLSE/p1565845684086500 


Hearing took place on

  2019-08-13 16:30:00 UTC
```

Every `AssignHearingDispositionTask` for the appeals mentioned in the Slack message has a `cancelled` status:

```
irb(main):020:0> appeals.map { |a| a.tasks }.flatten.select { |t| t.is_a? AssignHearingDispositionTask }.map { |t| t.status }
=> ["cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled", "cancelled"]
```

I'm thinking that this line:

https://github.com/department-of-veterans-affairs/caseflow/blob/17583e6fc78bdfc29494a748b99b8275bc5228a2/app/models/task.rb#L32

ends up executing this:

https://github.com/department-of-veterans-affairs/caseflow/blob/17583e6fc78bdfc29494a748b99b8275bc5228a2/app/models/tasks/hearing_task.rb#L49-L59

**Comment by ferristseng** [comment]
The appeals also are all have a disposition of "Dismissed, Withdrawn" and status of "Complete":

```
=> ["Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn", "Dismissed, Withdrawn"]
irb(main):009:0> appeals.map { |a| a.status }
=> ["Complete", "Complete", "Complete", "Complete", "Complete", "Complete", "Complete", "Complete", "Complete", "Complete"]
```

I think the job can be modified to skip tasks where the appeal is closed to prevent this from happening

**Comment by msj0nes** [comment]
@ferristseng any update on this?

**Comment by jimruggiero** [comment]
@lomaxap @ferristseng Now that #12706 is open, what scope will be worked on this issue?

**Comment by ferristseng** [comment]
I think we will still need to monitor, and see if #12706 actually fixes it. The PR was opened a while ago, so I can't remember what state it was in @lomaxap
