### ISSUE TITLE
Create UI for marking users inactive

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12212]
Spun out of #11631. Team admins need a way to mark users inactive so they do not have tasks assigned to them. 

Create a new endpoint to manage all users. Users who can access this endpoint should be limited to members of the BVA admin team. Add option in users_controller to fetch all users (this should include users of all statuses). Add endpoint to users_controller (not within organizations/users_controller) to update the status and status_updated_at columns for that user. Add front end page that displays all users and their status. Add a button, confirmation, and success alert that hits the update user's status endpoint.

**Comment by kevmo** [comment]
1 |
2 |
3 | |
5 | ||||||||
8 | |||

Involves a lot of F/E and B/E changes.

5.

Look for ways to break this into multiple PRs. If any additional work appears, raise flag early! 🎏

**Comment by hschallhorn** [comment]
@stwards11 This is going live today and has a release notes tag!

**Comment by laurjpeterson** [comment]
@hschallhorn - can you add a screenshot to this? or let me know how i can see it in prod or demo? want to share it with stakeholders. thank you!

cc: @jimruggiero

**Comment by hschallhorn** [comment]
@laurjpeterson Should have some screens on the PR (#12312). In demo, login as TEAM_ADMIN and click the main dropdown to get to "Caseflow user management"

**Comment by laurjpeterson** [comment]
![image (19)](https://user-images.githubusercontent.com/27704093/67219334-d655e000-f3f5-11e9-9760-08183b2c3b70.png)

**Comment by laurjpeterson** [comment]
Thanks @hschallhorn!
