### ISSUE TITLE
Remove use_task_pages_api feature toggle

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12216]
Since [pagination is turned on for all users](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2224), we can remove tests that require pagination be enabled, checks that pagination is enabled for a user, and any other mention of the `use_task_pages_api` feature toggle

## AC
- [ ] All mention of `use_task_pages_api` feature toggle are removed

**Comment by kevmo** [comment]
1 | ||||||||
2 | ||||
3 | 
5 |
8 | 

1.  Because this sounds easy. Potential 2 because "lots of tests blew up the last time I removed a feature toggle."

**Comment by lomky** [comment]
Go ahead and enable for all organizations, while we're at it!
