### ISSUE TITLE
[Tech Spec] Async job notes

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12214]
## Problem

When async claim establishment jobs (for HLR, SC and RequestIssueUpdate) fail with errors, we usually need to create incident tickets in YourIT. We need a reliable way of communicating that a stuck async job is being addressed in an upstream system, so that anyone looking at the job in Caseflow can know that (a) someone has seen the problem, (b) they have created a ticket and (c) what the URL of the ticket is so that they can follow up with our partner services.

## Proposal

Create a new table `job_notes` with a schema like:

```ruby
    create_table :job_notes do |t|
      t.belongs_to :job, polymorphic: true, null: false, comment: "The job to which the note applies"
      t.belongs_to :user, null: false, comment: "The user who created the note"
      t.timestamps null: false, comment: "Default created_at/updated_at"
      t.text :note, null: false, comment: "The note"
      t.boolean :send_to_intake_user, default: false, comment: "Should the note trigger a message to the job intake user"
    end
```

Add a form to the individual async job page that allows any user able to view that page to also add a note.

The form has a checkbox with the label "Send to :username:" where the username is the intake user.

* Notes cannot be edited.
* Notes cannot be deleted.
* Notes may optionally trigger a `Message` to the user who created the Intake (job).

**Comment by leikkisa** [comment]
This looks great!

Should we make "notes" `t.text`, in case people want to write some context in with the URLs?

> Add a form to the individual async job page that allows any user able to view that page to also add a note.
I think access to that page is partially restricted now, my guess on reasoning was that the error can contain veteran information and not everyone can see all veterans.  Should we open it up?

**Comment by pkarman** [comment]
in practice, an AR `string` becomes a postgresql `varchar` which has a limit of 1G. But that's harder to see in a db migration, where we seem to use `text` to mean "a lot of bytes".

See https://stackoverflow.com/questions/4848964/postgresql-difference-between-text-and-varchar-character-varying

**Comment by pkarman** [comment]
> I think access to that page is partially restricted now, my guess on reasoning was that the error can contain veteran information and not everyone can see all veterans. Should we open it up?

I don't want to conflate authorization rules for the job page with the notes. That's why I phrased it as "anyone who can view". Right now it's `Global Admin`, `Admin Intake` and the specific user who created each Intake job.

**Comment by pkarman** [comment]
still todo:

- [ ] Notes may optionally trigger a Message to the user who created the Intake (job).

**Comment by leikkisa** [comment]
Closing this issue, created:
https://github.com/department-of-veterans-affairs/caseflow/issues/12524

As a follow on for the remaining piece (messaging the user)
