### ISSUE TITLE
Dispatched cases still open

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12238]
Investigation and data clean up required.

https://github.com/department-of-veterans-affairs/dsva-vacols/issues/78#issuecomment-534651120

The section "Was distributed to a judge, now already dispatched from the Board" in the link above needs:

* [x] data integrity check(s) to proactively catch these in the future
* [x] investigate the existing cases to determine what manual clean up is necessary
* [x] fix any bugs in the code as we identify them via the above steps
* [ ] perform manual clean up

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/12204 may help address

**Comment by pkarman** [comment]
Need investigation:

- [ ] https://appeals.cf.ds.va.gov/queue/appeals/5f529e50-14e0-4860-9312-107cdf63c64b
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/872846d3-2377-4427-9bd7-b65390d6bd22
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/15135ebf-4ea6-474e-9e1f-40962ca10713
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/6fe29e4a-e3c6-4cfb-a2e6-d1a769257efc
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/566e9b1a-5515-409e-8bf8-bebfbc824b63
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/de87df4e-c8c9-4975-9c47-c862a78e42db
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/db5819d7-7b86-43fb-b874-01ad38bafd89
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/3cc636a2-092e-4664-9558-d4ccc39eff46
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/72ed48a3-ff32-4f7b-82bd-14fd67de3020
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/b198935c-bea9-466e-b322-ac13c99d2a6e

**Comment by D-L-Ware** [comment]
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/5f529e50-14e0-4860-9312-107cdf63c64b 
              has no currently active tasks
              has been signed by a judge and dispatched
              mail tasks were opened post dispatch but have all been completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/872846d3-2377-4427-9bd7-b65390d6bd22
               has no currently active tasks
               has been signed by a judge and dispatched
               reconsideration mail tasks were opened post dispatch but have all been completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/15135ebf-4ea6-474e-9e1f-40962ca10713
              has no currently active tasks
              has been signed by a judge and dispatched
              mail tasks were opened post dispatch but have all been completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/6fe29e4a-e3c6-4cfb-a2e6-d1a769257efc
               has no currently active tasks though it has a CAVC flash
               has been signed by a judge and dispatched
               reconsideration mail tasks and motion to vacate mail tasks were opened post dispatch 
                          but have all been completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/566e9b1a-5515-409e-8bf8-bebfbc824b63
              has no currently active tasks
              has been signed by a judge and dispatched
              mail tasks were opened post dispatch but have all been completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/de87df4e-c8c9-4975-9c47-c862a78e42db
               has no currently active tasks though it has a CAVC flash
               has been signed by a judge and dispatched
               motion to vacate mail tasks were opened post dispatch cancelled reopened then 
                         completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/db5819d7-7b86-43fb-b874-01ad38bafd89 
                 high sensitivity appeal I cannot access
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/3cc636a2-092e-4664-9558-d4ccc39eff46
              has no currently active tasks
              has been signed by a judge and dispatched
              mail tasks were opened post dispatch but have all been completed
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/72ed48a3-ff32-4f7b-82bd-14fd67de3020
               high sensitivity appeal I cannot access
- [ ] https://appeals.cf.ds.va.gov/queue/appeals/b198935c-bea9-466e-b322-ac13c99d2a6e
              has no currently active tasks
              has been signed by a judge and dispatched
              mail tasks were opened post dispatch but have all been completed

**Comment by D-L-Ware** [comment]
I hope the above is helpful.  They all have the same scenario in one way or another.  Judges signs, appeal dispatched, mail tasks assigned post dispatch (general, reconsideration, vacate), all tasks completed at this point.  

I cannot speak to the two sensitive appeals, however, given the consistency of the pattern in the other appeals I expect they are the same.  I can likely reach out to someone at the Board to confirm if necessary.

**Comment by pkarman** [comment]
I have closed all the stuck appeals that I could. These remain for more investigation:

https://appeals.cf.ds.va.gov/queue/appeals/da5cce0c-ea6b-4879-bd61-90bb5e83e711
```
Appeal 6479 [id, status, closed_at]
└── RootTask 220248, on_hold, (closed_at)
    ├── TrackVeteranTask 220249, in_progress, (closed_at)
    ├── DistributionTask 220250, completed, 2019-12-04 12:10:45 UTC
    ├── JudgeAssignTask 550884, completed, 2019-12-18 15:18:26 UTC
    ├── JudgeDecisionReviewTask 581769, completed, 2020-01-02 13:00:56 UTC
    │   └── AttorneyTask 581770, completed, 2019-12-23 16:05:12 UTC
    ├── QualityReviewTask 596835, completed, 2020-01-14 20:36:34 UTC
    │   └── QualityReviewTask 599574, completed, 2020-01-14 20:36:34 UTC
    └── BvaDispatchTask 619502, on_hold, (closed_at)
        └── BvaDispatchTask 619503, assigned, (closed_at)
```

https://appeals.cf.ds.va.gov/queue/appeals/638f2513-7592-42f1-9530-9adff14f8ad0
```
Appeal 312 [id, status, closed_at]
└── RootTask 376, on_hold, (closed_at)
    ├── DistributionTask 48755, completed, 2019-03-21 12:20:45 UTC
    │   └── InformalHearingPresentationTask 377, completed, 2019-03-20 21:58:20 UTC
    ├── TrackVeteranTask 126461, completed, 2019-02-28 21:12:04 UTC
    ├── JudgeDecisionReviewTask 147894, completed, 2019-04-30 18:22:49 UTC
    │   └── AttorneyTask 154660, completed, 2019-04-30 11:29:25 UTC
    ├── BvaDispatchTask 189259, completed, 2019-05-02 12:17:10 UTC
    │   └── BvaDispatchTask 189260, completed, 2019-05-02 12:17:10 UTC
    ├── EvidenceOrArgumentMailTask 279794, completed, 2019-09-19 11:55:29 UTC
    │   └── EvidenceOrArgumentMailTask 279795, completed, 2019-09-19 11:55:29 UTC
    │       └── EvidenceOrArgumentMailTask 279796, completed, 2019-09-19 11:55:29 UTC
    ├── TrackVeteranTask 279873, in_progress, (closed_at)
    └── InformalHearingPresentationTask 279874, on_hold, (closed_at)
        └── InformalHearingPresentationTask 493333, assigned, (closed_at)
```

https://appeals.cf.ds.va.gov/queue/appeals/644f14bd-d319-408f-b0d2-f0b93e0e640c

```
Appeal 7086 [id, status, closed_at]
└── RootTask 233447, on_hold, (closed_at)
    ├── TrackVeteranTask 233448, completed, 2019-06-12 13:31:17 UTC
    ├── DistributionTask 233449, completed, 2019-06-17 13:46:02 UTC
    │   └── InformalHearingPresentationTask 233450, completed, 2019-06-17 13:29:02 UTC
    ├── JudgeDecisionReviewTask 238423, completed, 2019-06-19 16:38:58 UTC
    │   └── AttorneyTask 238430, completed, 2019-06-19 15:50:51 UTC
    ├── BvaDispatchTask 241837, completed, 2019-06-19 18:50:25 UTC
    │   └── BvaDispatchTask 241838, completed, 2019-06-19 18:50:25 UTC
    ├── VacateMotionMailTask 281050, completed, 2019-07-18 17:30:49 UTC
    │   └── VacateMotionMailTask 281051, completed, 2019-07-18 17:30:49 UTC
    │       └── VacateMotionMailTask 281052, completed, 2019-07-18 17:30:49 UTC
    ├── TrackVeteranTask 281255, in_progress, (closed_at)
    └── InformalHearingPresentationTask 281256, assigned, (closed_at)
```

https://appeals.cf.ds.va.gov/queue/appeals/0b47fd5d-9a5e-460b-a9ea-7d59a993a886

```
Appeal 2467 [id, status, closed_at]
└── RootTask 166186, on_hold, (closed_at)
    ├── TrackVeteranTask 166187, in_progress, (closed_at)
    ├── DistributionTask 166188, completed, 2019-11-27 21:22:39 UTC
    │   ├── EvidenceSubmissionWindowTask 166189, completed, 2019-06-16 05:30:07 UTC
    │   └── InformalHearingPresentationTask 237830, completed, 2019-10-28 23:23:54 UTC
    │       └── InformalHearingPresentationTask 409482, completed, 2019-10-28 23:23:54 UTC
    ├── EvidenceOrArgumentMailTask 269357, completed, 2019-07-15 15:43:53 UTC
    │   └── EvidenceOrArgumentMailTask 269358, completed, 2019-07-15 15:43:53 UTC
    │       └── EvidenceOrArgumentMailTask 269359, completed, 2019-07-15 15:43:53 UTC
    ├── JudgeAssignTask 544148, completed, 2019-12-05 21:44:21 UTC
    ├── JudgeDecisionReviewTask 556236, completed, 2019-12-11 15:27:24 UTC
    │   └── AttorneyTask 556237, completed, 2019-12-09 20:15:07 UTC
    ├── QualityReviewTask 567335, completed, 2019-12-20 21:17:29 UTC
    │   └── QualityReviewTask 568171, completed, 2019-12-20 21:17:29 UTC
    └── BvaDispatchTask 587864, on_hold, (closed_at)
        ├── BvaDispatchTask 587865, cancelled, 2019-12-23 12:30:54 UTC
        └── BvaDispatchTask 588303, on_hold, (closed_at)
            └── JudgeDispatchReturnTask 588315, assigned, (closed_at)
```

https://appeals.cf.ds.va.gov/queue/appeals/690a179d-59b3-4317-9883-ee91569254de

```
Appeal 768 [id, status, closed_at]
└── RootTask 1322, on_hold, (closed_at)
    ├── DistributionTask 50114, completed, 2019-05-21 14:15:06 UTC
    │   └── InformalHearingPresentationTask 1323, completed, 2019-04-10 13:58:50 UTC
    ├── TrackVeteranTask 126647, completed, (closed_at)
    ├── JudgeDecisionReviewTask 210192, completed, 2019-07-05 16:22:33 UTC
    │   └── AttorneyTask 218477, completed, 2019-06-13 11:37:07 UTC
    ├── BvaDispatchTask 261651, completed, 2019-07-08 10:34:20 UTC
    │   └── BvaDispatchTask 261652, completed, 2019-07-08 10:34:20 UTC
    ├── AodMotionMailTask 321144, completed, 2019-11-27 12:20:40 UTC
    │   └── AodMotionMailTask 321145, completed, 2019-11-27 12:20:40 UTC
    │       └── AodMotionMailTask 328806, completed, 2019-11-27 12:20:40 UTC
    ├── TrackVeteranTask 321326, in_progress, (closed_at)
    └── InformalHearingPresentationTask 321327, on_hold, (closed_at)
        └── InformalHearingPresentationTask 493350, assigned, (closed_at)
```

**Comment by D-L-Ware** [comment]
I looked at the three remaining and the all had an IHP tasks opened following the appeal being dispatched.  I know of no reason why this should occur so I expect we should cancel the IHP tasks.  I am checking with the Board.

Additionally, of the three, two were assigned by the same person and the third does not list who assigned so this may be a case of user error.

**Comment by pkarman** [comment]
```
Appeal 312 [id, status, closed_at]
└── RootTask 376, completed, 2020-01-21 17:49:40 UTC
    ├── DistributionTask 48755, completed, 2019-03-21 12:20:45 UTC
    │   └── InformalHearingPresentationTask 377, completed, 2019-03-20 21:58:20 UTC
    ├── TrackVeteranTask 126461, completed, 2019-02-28 21:12:04 UTC
    ├── JudgeDecisionReviewTask 147894, completed, 2019-04-30 18:22:49 UTC
    │   └── AttorneyTask 154660, completed, 2019-04-30 11:29:25 UTC
    ├── BvaDispatchTask 189259, completed, 2019-05-02 12:17:10 UTC
    │   └── BvaDispatchTask 189260, completed, 2019-05-02 12:17:10 UTC
    ├── EvidenceOrArgumentMailTask 279794, completed, 2019-09-19 11:55:29 UTC
    │   └── EvidenceOrArgumentMailTask 279795, completed, 2019-09-19 11:55:29 UTC
    │       └── EvidenceOrArgumentMailTask 279796, completed, 2019-09-19 11:55:29 UTC
    ├── TrackVeteranTask 279873, completed, 2020-01-21 17:49:40 UTC
    └── InformalHearingPresentationTask 279874, cancelled, 2020-01-21 17:49:40 UTC
        └── InformalHearingPresentationTask 493333, cancelled, 2020-01-21 17:49:40 UTC
```

```
Appeal 7086 [id, status, closed_at]
└── RootTask 233447, completed, 2020-01-21 17:50:46 UTC
    ├── TrackVeteranTask 233448, completed, 2019-06-12 13:31:17 UTC
    ├── DistributionTask 233449, completed, 2019-06-17 13:46:02 UTC
    │   └── InformalHearingPresentationTask 233450, completed, 2019-06-17 13:29:02 UTC
    ├── JudgeDecisionReviewTask 238423, completed, 2019-06-19 16:38:58 UTC
    │   └── AttorneyTask 238430, completed, 2019-06-19 15:50:51 UTC
    ├── BvaDispatchTask 241837, completed, 2019-06-19 18:50:25 UTC
    │   └── BvaDispatchTask 241838, completed, 2019-06-19 18:50:25 UTC
    ├── VacateMotionMailTask 281050, completed, 2019-07-18 17:30:49 UTC
    │   └── VacateMotionMailTask 281051, completed, 2019-07-18 17:30:49 UTC
    │       └── VacateMotionMailTask 281052, completed, 2019-07-18 17:30:49 UTC
    ├── TrackVeteranTask 281255, completed, 2020-01-21 17:50:46 UTC
    └── InformalHearingPresentationTask 281256, cancelled, 2020-01-21 17:50:46 UTC
```

```
Appeal 768 [id, status, closed_at]
└── RootTask 1322, completed, 2020-01-21 17:51:26 UTC
    ├── DistributionTask 50114, completed, 2019-05-21 14:15:06 UTC
    │   └── InformalHearingPresentationTask 1323, completed, 2019-04-10 13:58:50 UTC
    ├── TrackVeteranTask 126647, completed, (closed_at)
    ├── JudgeDecisionReviewTask 210192, completed, 2019-07-05 16:22:33 UTC
    │   └── AttorneyTask 218477, completed, 2019-06-13 11:37:07 UTC
    ├── BvaDispatchTask 261651, completed, 2019-07-08 10:34:20 UTC
    │   └── BvaDispatchTask 261652, completed, 2019-07-08 10:34:20 UTC
    ├── AodMotionMailTask 321144, completed, 2019-11-27 12:20:40 UTC
    │   └── AodMotionMailTask 321145, completed, 2019-11-27 12:20:40 UTC
    │       └── AodMotionMailTask 328806, completed, 2019-11-27 12:20:40 UTC
    ├── TrackVeteranTask 321326, completed, 2020-01-21 17:51:26 UTC
    └── InformalHearingPresentationTask 321327, cancelled, 2020-01-21 17:51:26 UTC
        └── InformalHearingPresentationTask 493350, cancelled, 2020-01-21 17:51:26 UTC
```
