### ISSUE TITLE
Edit confirmation page bug

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12239]
### Story
This is coming from a batteam support request.

A claim review had an unidentified issue on it, which was on a rating EP. The user removed that issue, and added an ineligible issue.  The EP got canceled, but the confirmation page shows that it was updated instead of removed.

For this issue, please double check that the ineligibility reason is correct on the edit page, and the confirmation page correctly shows the EP is being removed when there are no more issues on it.

### Image of the unexpected behavior
![image (8).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/96eafc25-d21f-49db-a9dc-4ae6a8b4b678)

### Context
https://dsva.slack.com/archives/CHX8FMP28/p1569602631213300

**Comment by msj0nes** [comment]
## YourIT Information

YourIT Ticket   Number | Date Ticket Created | Case Details URL | Missing Contentions/Issues (Separated by   Commas)
-- | -- | -- | --
INC7623133 | 9/25/19 | https://appeals.cf.ds.va.gov/search?veteran_ids=250328 | Sleep Apnea
