### ISSUE TITLE
Logger timestamps are stale

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#1225]
The timestamps below are all marked at `2017-03-16 12:52:17 -0400`. But in reality, the events are second apart.

The `log_tag` is [evaluated as a lambda](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/config/initializers/logger.rb#L10), but do we have any guarantee that it is being called everytime we do `Rails.logger.info`? Based on observation, the `log_tag` is only created per HTTP request (controller initialization?). So during the lifecycle of a HTTP request, all logs from this request will have the same timestamp.

```
12:52:17 -0400] [xxx xxx@va.gov] Started POST "/dispatch/establish-claim/242/perform?xxx" for 127.0.0.1 at 2017-03-16 12:52:17 -0400
^[[32mdsva-appeals-certification-prod^[[0m ^[[36m/opt/caseflow-certification/src/log/caseflow-certification.out^[[0m [appeals.cf.ds.va.gov] [172.30.82.39] [2017-03-16 12:52:17 -0400] [xxx xxx@va.gov] STARTED BGS: fetch_veteran_info xxx
^[[32mdsva-appeals-certification-prod^[[0m ^[[36m/opt/caseflow-certification/src/log/caseflow-certification.out^[[0m [appeals.cf.ds.va.gov] [172.30.82.39] [2017-03-16 12:52:17 -0400] [xxx xxx@va.gov] STARTED fetch veteran info for vbms id: xxx
^[[32mdsva-appeals-certification-prod^[[0m ^[[36m/opt/caseflow-certification/src/log/caseflow-certification.out^[[0m [appeals.cf.ds.va.gov] [172.30.82.39] [2017-03-16 12:52:17 -0400] [xxx xxx@va.gov] STARTED sent VBMS request VBMS::Requests::EstablishClaim for xxxx
```

This bug should be considered high priority because we can not accurately determine event time at the moment. Outages are very difficult pinpoint with this bug.

**Comment by kierachell** [comment]
**PASSED**
was deployed without any sort of validation, so who cares.
