### ISSUE TITLE
Upstream Error | Invalid POA results in DuplicateEP error

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12254]
### Story
When a veteran has an invalid Power of Attorney, establishing a claim for the veteran fails.  For the example that we've dug into, the POA's accreditation had expired.  Upon attempting to establish a claim for the veteran, a PIF will get locked.  One way to identify these is if they get the DuplicateEP error during claim establishment, but their list of end product show no past claims of the same type (for a supplemental claim, they have no claims in the 040 series).  Another example is if attempting to establish a claim with a modifier that has never been used in the past still fails.

What is happening is during claim establishment, the process fails part way through.  In this process, the PIF gets locked, but the full claim establishment does not succeed.

### Veterans/Reviews impacted:
Veteran ID | participant id | review type | review ID | YourIT INC | YourIT INC Link
--- | --- | --- | --- | --- | ---
302002 | 10262339 | SupplementalClaim | 64476 | INC7692982 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=3f844258db1444d4ceac76740f961904
381008 | 20937808 | SupplementalClaim | 187682 | Added to same ticket above
477226 | 580061 | HigherLevelReview | 59821 | Resolved
477226 | 580061 | HigherLevelReview | 60077 | Resolved
563390 | 51669504 | SupplementalClaim | 236465 | TBD
358733 | 29205411 | SupplementalClaim | 292203 | New
563390 | 51669504 | SupplementalClaim | 236465 | New
592551 | 15092514 | SupplementalClaim | 262545 | New
112240 | 10107282 | SupplementalClaim | 291640 | New
850010 | 550209 | SupplementalClaim | 509100 | New
844050 | 31658428 | SupplementalClaim | 501696 | New

### Notes 9/30/2019
Jane Chi with AMO looked into this veteran and let us know that the POA lost their accreditation (on August 23, 2019).  Sally send a follow up on 9/30/2019 to check if we can fix the data.  I believe currently only this one veteran is impacted.

### Related
We get the same DuplicateEP error for other reasons as well. Those are being tracked here:
https://github.com/department-of-veterans-affairs/caseflow/issues/11081

**Comment by leikkisa** [comment]
During the meeting on 1/9/2020, we determined that a user needs to add the same POA information to BIRLS. I sent an email to Jane Chi and John Dell with the veteran file numbers today.

**Comment by msj0nes** [comment]
@leikkisa is this safe to close now. Considering duplicate vets is resolved outside of Caseflow (business process based) and the latest error https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/13240 message provides clear instructions, was there anything additional engineering had remaining to complete.

**Comment by leikkisa** [comment]
I think the way to differentiate these from other DuplicateEP errors is to check if the veteran's end products have any past 030 or 040 claims.
