### ISSUE TITLE
Hearings have empty locations

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12266]
### User Story
Some hearings locations are empty, even thought they are scheduled for an RO.

### Success criteria
Scheduled hearings should not have nil addresses.
Undue the work around in the following PR.  #12265

### Release notes
n/a

Designs
n/a

related to 
#10851
#12265

**Comment by lomaxap** [comment]
is this specifically for VetText @pshahVA ?

**Comment by pshahVA** [comment]
I believe the error is stemming from our data, but it was discovered as part of VetText. Currently, we are filtering these out so they will not get a text message.

**Comment by jimruggiero** [comment]
@pshahVA What is the next step to move this issue forward? Does ENG need to do some investigation?
