### ISSUE TITLE
Send dismissed/withdrawn motions to vacate to BVA dispatch

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12269]
### Story
When a judge dismisses or withdraws a motion to vacate, it creates a DismissedMotionToVacateTask assigned to the motions attorney.  The motion attorney should [TBD] to route the denial to a BVADispatch task.

### Question
- What action does the motions attorney need to take to send the task to BVADispatch?
- What information is needed for for the BVA dispatch task?

### Acceptance criteria
TBD

### Out of scope
Denied motions to vacate - see https://github.com/department-of-veterans-affairs/caseflow/issues/12268
Handling the BVA Dispatch task, this will be handled by https://github.com/department-of-veterans-affairs/caseflow/issues/11727

**Comment by jimruggiero** [comment]
@rutvigupta-design @geronimoramos when you have designs complete for this, can you link them to this ticket?

**Comment by rutvigupta-design** [comment]
@jimruggiero this ticket is no longer needed since dismissed motions to vacate are not sent to BVA Dispatch (they are sent to the veteran by the motions attorney).

**Comment by leikkisa** [comment]
Closing this ticket in favor of: https://github.com/department-of-veterans-affairs/caseflow/issues/12517
