### ISSUE TITLE
Asynchronous Claims | Background Jobs

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12276]
### Description
This epic is here to connect all of the individual upstream error issues and describe the overall process for handling them.

This process is new and evolving, so please feel free to make improvements.

### Goals
1. Identify errors and ensure that they all have Incident reports, GitHub issues and job notes. We will use these as a form of communication to clients and users.
1. Ultimately, solve all of the issues!

### Process
1. Look for asynchronous jobs that haven't been accounted for yet (see code below)
1. Look for the related GitHub issue, which should be tagged with "upstream-error" and part of this epic.
    1. If there is no GitHub issue yet, please create one, connect it to this epic and tag it with "upstream-error" and post it in the #foxtrot channel in Slack
1. Add a note to the asynchronous job notes, referencing the GitHub issue.
1. Add the impacted job to the ticket in a markdown table, with the INC number and the YourIT link
1. If the asynchronous job needs to be cancelled, it can be done so in the Rails console, e.g.:
```
pry> job = HigherLevelReview.find(SOME_ID)
pry> user = User.find(YOUR_USERID)
pry> job.cancel_with_note!(current_user: user, note: "the reason for cancellation")
```

### Finding new errors
```
engineer_user_ids = [11110, 2197, 7850, 1376] # Sally, Peter, Tomas, Sandra
scs=SupplementalClaim.expired_without_processing.where(establishment_canceled_at: nil)
hlrs=HigherLevelReview.expired_without_processing.where(establishment_canceled_at: nil)
reviews = scs + hlrs

# Reviews without a note from one of us
todo = reviews.select{ |r| r.job_notes.select{ |jn| engineer_user_ids.include?(jn.user_id) }.empty? }
```

### Adding notes to errors once you have completed the process for them:
```
# method
def add_job_note(user, job, github_issue_number=nil, user_note=nil)
  github_issue_note = github_issue_number ? "To track progress on this issue, please see: https://github.com/department-of-veterans-affairs/caseflow/issues/#{github_issue_number}" : nil
  note = [user_note, github_issue_note].compact.join("\n")

  fail "Github issue number or user note is required" unless note

  JobNote.create!(
    job: job,
    user: user,
    note: note,
    send_to_intake_user: false
  )
end

# Example using it for a single job
my_user_id=1234
my_user=User.find(my_user_id)
job=todo.first # This is for whatever job you're looking at, such as a specific SC or HLR
github_issue_number=1234
my_note="Optional, additional comments about this job, leave this out if you don't have anything"

add_job_note(my_user, job, github_issue_number, my_note)

# Example using it for a batch of jobs
my_user_id=1234
my_user=User.find(my_user_id)
github_issue_number=1234
error_snippet = "DuplicateEP"

scs=SupplementalClaim.expired_without_processing.where(establishment_canceled_at: nil).where("establishment_error ILIKE '%#{error_snippet}%'")
hlrs=HigherLevelReview.expired_without_processing.where(establishment_canceled_at: nil).where("establishment_error ILIKE '%#{error_snippet}%'")
jobs=scs+hlrs

jobs.each{|job| add_job_note(my_user, job, github_issue_number)}
```

**Comment by msj0nes** [comment]
# Ticket Closure

Marking this work as complete as all related issues are closed. Stakeholder is aware of end product 'background jobs page'.
