### ISSUE TITLE
Motion to Vacate | Granted | After a VLJ signs a granted motion to vacate, send to BVA dispatch

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12270]
### Story
When a motion to vacate is granted it creates either a VacateAndDeNovoTask or a StraightVacateAndReadjudicationTask which is assigned to the drafting attorney.  The drafting attorney does [xyz] to send this to the VLJ to sign.

Once the VLJ signs the motion to vacate, a BVA Dispatch task should get created.

### Questions
* Is the part where the drafting attorney takes action to create the JudgeSignMotionToVacateTask already complete?
* What action does the VLJ need to do in order to sign the motion to vacate?
* What information does BVADispatch need in order to complete their task?

### Out of scope
Handling the BVA dispatch task, see https://github.com/department-of-veterans-affairs/caseflow/issues/11726

### Acceptance criteria
TBD

**Comment by jimruggiero** [comment]
@rutvigupta-design @geronimoramos when you have designs complete for this, can you link them to this ticket?

**Comment by leikkisa** [comment]
Closing this ticket, as it will be handled by appeal-streams
