### ISSUE TITLE
Investigate orphaned ScheduleHearingTasks with cancelled parent HearingTasks for LegacyAppeals

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12288]
[Relevant slack thread](https://dsva.slack.com/archives/CHX8FMP28/p1570018944279700)

3 appeals were brought to the attention of the batteam that were showing up with duplicate schedule hearing tasks. All three appeals had a similar task tree with two `HearingTask`s, one of which was cancelled with an assigned `ScheduleHearingTask` child.
```
LegacyAppeal
├── RootTask on_hold
│   ├── HearingTask cancelled
│   │   └── ScheduleHearingTask assigned
│   └── HearingTask on_hold
│       └── ScheduleHearingTask assigned
└── ScheduleHearingColocatedTask completed
    └── ScheduleHearingColocatedTask completed
```

There are currently a few others in this state as well

```ruby
cancelled_hearing_tasks = HearingTask.cancelled
orphaned_schedule_hearing_tasks = ScheduleHearingTask.active.where(parent_id: cancelled_hearing_tasks.pluck(:id))
orphaned_schedule_hearing_tasks.count
# => 269
orphaned_schedule_hearing_tasks.group(:appeal_type).count
# => {"LegacyAppeal"=>269}
```

**Comment by lomaxap** [comment]
see #10630 for context

**Comment by chandracarney** [comment]
This might have been resolved in another ticket.
