### ISSUE TITLE
Make multiple claims (030 & 040 exist) for the same disability issue to be separate issues so that they can be independently tracked

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#12285]
### User or job story
Job story:
When a veteran submits a claim for higher evaluation, as well as a HLR for an earlier effective date for the same disability, AMO Intake users should be able to select these as two separate issues, so that both can be independently trackable.

###Scenario Context Example:
- Veteran was granted service connection for PTSD
- Veteran submitted Supplemental claim for a higher evaluation (EP 040 Supplemental)
- Veteran submitted HLR claim for an earlier effective date (EP 030 Higher Level Review)

EP 040 established through Caseflow.  EP 030 established through Caseflow, however, cannot add effective date for PTSD to EP 030, as this issue is currently pending under the 040 Supplemental claim as PTSD. We must be able to add effective date for PTSD to the EP 030.

### Acceptance criteria
- Add a screenshot or .gif to this ticket when code is merged.
- Ensure that both subsequent issues (eval/effective date) could also be separated out on a single 030 or 040 (i.e. Vet submits HLR for eval of PTSD AND earlier effective date), because in some cases, AMO may grant a higher evaluation, but deny an earlier effective date.

### Release notes
Users can now add effective dates to EP 030s whose effective dates are earlier than subsequent EP 040s for the same issue, if/when created. 

#### Designs
_Include screenshots or links to designs if applicable._

#### Background/context
_Include as needed, especially for issues that aren't part of epics. Include a value statement - why is this feature being developed?_

#### Success criteria
_Include as needed, especially for issues that aren't part of epics._

#### Technical notes
_Include notes that might help an engineer get started on this more quickly, or potential pitfalls to watch out for._

#### Other notes
N/A

#### Resources/other links
_E.g. links to other issues, PRs, Sentry alerts, or Slack threads, or external service requests._

**Comment by jimruggiero** [comment]
@leikkisa This issue was reported by Jane in the EP 930 slack channel last week. Can I get your input on what additional AC's should be added, if any and whether any new screens would be required from Design in order for the team to estimate this one?

**Comment by msj0nes** [comment]
Being reviewed by engineering
