### ISSUE TITLE
Appeal with no active request issues but with active tasks

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12293]
Should not be creating tasks or dispatching appeals that have zero active request issues (e.g. if they are all ineligible).

Example https://dsva.slack.com/archives/CHX8FMP28/p1570458025367200

## AC

- [ ] Add data integrity check for appeals with zero active request issues and active tasks
- [ ] Prevent tasks from being created on such appeals
  - [ ] Add spec

## Open questions

- Confirm who is responsible for contacting the Claimant in the case of an intake that cannot be processed. Note: this is a business process task done by Claims Assistants. We have no easy way of verifying whether they have done this.
- Double check with Echo that an appeal with only ineligible issues wouldn't need tasks, like the RootTask

## Tech notes
  - Task creation happens via the InitialTaskFactory
  - Add link to example DataIntegrityChecker PR

**Comment by leikkisa** [comment]
Check impact to Appeals Status API.  Check with Queue on what they think the behavior should be. Would we want to create a RootTask and immediately close it?  This might have it match the "Removed" status on the Appeals Status API.

Business process question - do folks actually mail veterans when there are ineligible issues on a review?
