### ISSUE TITLE
NoMethodError in legacy appeal dispatch complete_root_task!

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12299]
#### Background/context

Seeing a `NoMethodError` in `app/workflows/legacy_appeal_dispatch.rb` in `complete_root_task!`. The error is:

```
undefined method `update!' for nil:NilClass
```

Looks like there's a nil `root_task` for an appeal:

```
    @appeal.root_task.update!(status: Constants.TASK_STATUSES.completed)
```

#### Resources/other links

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6924/events/503803/

**Comment by sahalliburton** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10485/?referrer=webhooks_plugin
