### ISSUE TITLE
Litigation Support: Give the attorneys the ability to close denied and dismissed/withdrawn MTV tasks

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#12296]
### User or job story
User story: As a motions attorney, I want the ability to close denied or dismissed/withdrawn motions to vacate tasks, so that these tasks will be removed from my work queue when I've drafted and dispatched a letter to the veteran.

### Acceptance criteria
- The prior motions attorney (or other from their team, if reassigned) can take action to complete the task and dispatch the appropriate letter to the veteran.
- Please include a screenshot or .gif to this ticket when work is complete.

### Release notes
Attorneys can now directly close denied and dismissed/withdrawn motions to vacate tasks that appear in the work queues.

#### Designs
TBD

#### Background/context
Caseflow currently only supports attorneys' ability to assign tasks they've completed to Dispatch to close out. This functionality is intended to give the ability to close out specific tasks in the motions to vacate workflows for which Dispatch is not involved with the work. 

#### Success criteria
See ACs.

#### Technical notes
Include notes that might help an engineer get started on this more quickly, or potential pitfalls to watch out for.

#### Resources/other links
E.g. links to other issues, PRs, Sentry alerts, or Slack threads, or external service requests.

**Comment by leikkisa** [comment]
@jimruggiero @rutvigupta-design I believe this was closed by
https://github.com/department-of-veterans-affairs/caseflow/pull/12638

The above ticket is for "Complete", which I think is the same in closed this case.

So I think we can close this ticket.
