### ISSUE TITLE
TypeError in OrganizationQueue

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12297]
#### Background/context

Seeing a sentry alert for a `TypeError` in the `OrganizationQueue`:

```
Cannot read property 'map' of undefined
```

for this line:

```
const tabNames = config.tabs.map((tab) => {
```

It's happening on this URL: 

https://appeals.cf.ds.va.gov/organizations/vlj-support-staff

#### Resources/other links

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6214/events/503594/

**Comment by hschallhorn** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7647/ as well

**Comment by jcq** [comment]
This seems related to #11434 

And we continue to see sentry alerts on this:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7734/

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9814
`tabs` is undefined:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/55255674/82704811-fb385d00-9c3b-11ea-8a0b-6b5c6472933a.png">
 context:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/55255674/82704833-09867900-9c3c-11ea-86d0-89f42e7cea69.png">
