### ISSUE TITLE
AASM::InvalidTransition error in Dispatch

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12301]
app/models/establish_claim.rb in block in assign_existing_end_product!

AASM::InvalidTransition: Event 'complete' cannot transition from 'completed'. 

complete!(status: :assigned_existing_ep, outgoing_reference_id: end_product_id)

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6695/events/503920/

 - [ ] Timebox ticket to a 5
 - [ ] Investigate cause of alert
 - [ ] Fix by either
   - [ ] Handling this error in the code rather than allowing it to bubble up to sentry
   - [ ] Fixing what causes the error to be thrown
   - [ ] Filing a ticket to do the above

**Comment by pshahVA** [comment]
@alisan16 , I just wanted to confirm that you thought this was a tango error.

**Comment by alisan16** [comment]
This is not a Tango error, this is an error with Dispatch. I must have assigned Tango on accident. I'll remove it!

**Comment by lomky** [comment]
These alerts have been increasing lately. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6695/

![image](https://user-images.githubusercontent.com/6129479/73677048-7b35b980-4683-11ea-9236-bcc3a580f717.png)

**Comment by hschallhorn** [comment]
Timeboxed to a 5 due to unfamiliarity with dispatch. Blocking off time to get spun up on code before even looking into issue.
