### ISSUE TITLE
Caseflow::Error::AttorneyJudgeCheckoutError: Validation failed: Diagnostic code is not included in the list

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12302]
Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6763/

Also thrown with this error: ActiveRecord::RecordInvalid
Validation failed: Diagnostic code is not included in the list

app/models/concerns/issue_updater.rb in rescue in update_issue_dispositions_in_caseflow!

**Comment by pkarman** [comment]
dupe of #10948
