### ISSUE TITLE
BGS | VSOs cannot view case details or hearing info on non-veterans claimants they represent

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12307]
### Description
When a user that is part of a veteran service organization searches for a veteran that has that VSO as their Power of Attorney, they get the following error from BGS: 
Power of Attorney of Folder is none. Access to this record is denied.

The user is the admin for his veteran service organization, which is the VSO that is the Power of Attorney for this veteran.

### Impacted cases
Veteran | User CSS ID | INC number
--- | --- | ---
272634 | vacowendet | INC7600300 (created by support team)

### Technical notes
This error is not part of the asynchronous processing errors.

### Context
https://dsva.slack.com/archives/CHX8FMP28/p1569864376234400

**Comment by msj0nes** [comment]
Ticket INC7600300  is now assigned to BGS PROD SUPP in YourIT for the BGS Team to properly resolve. Will monitor for resolution.

**Comment by msj0nes** [comment]
# Closure
Issue was linked to #12453 . Now resolved via BGS team. 

Engineering: For BGS integration issues, please open a YourIT ticket and assign ticket to "BGS Prod Supp" assignment group. 
> Once you create the ticket just ask support team to change the assignment group to the above.
