### ISSUE TITLE
MTV - Add option for partial grant and select issues

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12318]
### Story
Sometimes, judges partially grant Veterans' motions to vacate. This means that only some, not all, of the issues on the original appeal decision will be vacated and decided again on the new decision.

Judges (or potentially other users, to be determined) need to select some, not all, issues that are vacated, to be decided on the new decision. (And then, follow the typical assign to attorney, draft decision, attorney checkout, judge checkout etc. path.)

### Acceptance criteria
- On the Judge Address Motion to Vacate modal, a new option is available to allow for a partial grant
- When the judge selects the partial grant option, a list of decision issue descriptions from the previous appeal are populated. 
- Users can select from that list of issues

### Out of scope
- Action on submit
- Additional processing on the selected issues
- Connectivity to timeline display data is out of scope
- Vacated issues get a new request issue created for them on the same appeal - https://github.com/department-of-veterans-affairs/caseflow/issues/12373
   - The vacated decisions are connected to the new request issue with vacated_by_request_issue_id
   - The request issues get assigned to a decisions attorney to write, to make new decisions on

### Design
![Screen Shot 2019-10-08 at 11.32.06 AM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/8f955f9a-4aa3-448b-9880-145d075220d4)

### Notes
Ticket to pull motions to vacate issues only into this workflow handled under a separate ticket

**Comment by laurjpeterson** [comment]
@leikkisa @jimruggiero @geronimoramos @rutvigupta-design - i updated this ticket for clarity. 

If a judge selects "partial vacatur", all issues from the previously decided decision (that has the request for vacatur) should show in the checkboxes you display in the design. This way, the judge can choose which of those issues are actually being vacated. 

So the flow would look something like this. Does this make sense?

- An appeal with 4 issues was decided. 
- Veteran sends in a request for motion to vacate.
- Motions attorney assigns MTV to judge
- Judge decides that only 3 of the 4 warrant vacatur - and thus chooses partial vacatur
- Judge selects those 3 issues from the screen above, and only those 3 issues become request issues in the subsequent new decision
- Judge assigns task to attorney (either Vacate and De Novo or Straight Vacate and Readjudication) so a new decision, with just the 3 vacated issues, as request issues

**Comment by leikkisa** [comment]
@laurjpeterson Thanks, that answers a big question of mine. So the veteran can only request to vacate a whole appeal, they can't request to vacate specific issues.  We thought that might be a possibility before.

**Comment by jcq** [comment]
Does the "partial vacatur" option only apply to the judge view, or is there a case where the motions attorney might suggest a partial vactur? (While that is out of scope of this ticket, they currently share the same code/components.)

**Comment by rutvigupta-design** [comment]
@jcq since motions attorneys aren't actually logging their recommended dispositions in the BE, we decided that they didn't need an option to suggest a partial vacatur (they would indicate so in their notes).

**Comment by jcq** [comment]
@rutvigupta-design @geronimoramos Are the "(1 document)" / "(2 document)" labels always the same? I mean, those apply to all instances of their respective type of vacate, not something specific to the given case, right?

**Comment by rutvigupta-design** [comment]
@jcq yes, those labels will be static!

**Comment by rutvigupta-design** [comment]
### Help text styles:
color: 5B616B 
font-family: ‘Source Sans Pro’
font-style: Italic
font-weight: 400
font-size: 17px
line-height: 1.5em/26px

cc @jcq
