### ISSUE TITLE
Create VirtualHearing Class

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12316]
### Background
related to #12315

### Objective
Create an ActiveRecord class that allows us to query virtual_hearings. We should be able to access virtual hearing data from the parent hearing with `hearing.virtual_hearing`. We should also be able to test if a hearing is virtual with `hearing.virtual?` where there is a related `virtual_hearing` record that is `active`

Hearing serializers should return boolean values for `virtual` attribute

`VirtualHearing.active` should [scope](https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html) virtual hearings to those where `active: true` 

For legacy_hearings, after a virtual hearing is created, the `hearing_type` in `VACOLS` should be updated to `VIRTUAL`

**Comment by ferristseng** [comment]
> For legacy_hearings, after a virtual hearing is created, the hearing_type in VACOLS should be updated to VIRTUAL

@lomaxap Testing this, and it looks like `hearing_type` has to be 1 character. Any ideas for what this should be? cc @pshahVA
