### ISSUE TITLE
Get GovDelivery Account

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12329]
see conversation https://dsva.slack.com/archives/C2ZAMLK88/p1564502322130100

We need access to VA's GovDelivery service in order to send emails judges, veterans, and representatives when a virtual hearing is scheduled.

@pshahVA to get in contact with VA contact about getting credentials and specs.

**Comment by pshahVA** [comment]
email sent to Tuscher, Joshua <Joshua.Tuscher@va.gov> on 10/9

**Comment by pshahVA** [comment]
some notes on how to get started:
Add GovDelivery gem:
https://github.com/department-of-veterans-affairs/vets-api/blob/6dafa7bd33645c6e966e0cf933f391ec41dda802/Gemfile#L51
Configure the app to use GovDelivery for emails:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/config_helper.rb
Use config in environment config files.  Production example:
https://github.com/department-of-veterans-affairs/vets-api/blob/6dafa7bd33645c6e966e0cf933f391ec41dda802/config/environments/production.rb#L113
Then just create Rails mailers.
https://guides.rubyonrails.org/action_mailer_basics.html
Here are ours:
https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/mailers
We have two transactional mailers: DirectDepositMailer and HCASubmissionFailureMailer.  They are subclasses of TransactionalEmailMailer.  We use Google Analytics to track the users in those.
The other mailers are used to send reports internally.
If you have any questions, just ask. (edited)

**Comment by pshahVA** [comment]
We have a trial license where we can continue to work.

**Comment by lomaxap** [comment]
can we use that trial license in production?
