### ISSUE TITLE
ActionView::Template::Error: undefined method `ui_hash' for LegacyAppeal

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12320]
ActionView::Template::Error: undefined method `ui_hash' for #<LegacyAppeal:0x00007f718a4ad7a8>

app/views/appeals/edit.html.erb in block in _app_views_appeals_edit_html_erb__2619788785479411407_70063144735820

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6971/

**Comment by pkarman** [comment]
We shouldn't ever be acting on LegacyAppeal instances at that endpoint. I wonder if we just randomly hit a id collision?

**Comment by hschallhorn** [comment]
We've gotten this 7 times on 3 different appeals at this point https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6971/events/latest/
