### ISSUE TITLE
Create ActionMailers for Virtual Hearing Emails

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12330]
### Background
related to: #12329
When a hearing is switched from central or video to virtual, a confirmation email with instructions will need to be sent to veteran, representative, and judge. 

### Objective
Create Mailers and Mailer layouts for 
- Notice that virtual hearing was cancelled to Judge, Veteran, and Representativee
- Confirmation that virtual hearing was scheduled

[reference](https://guides.rubyonrails.org/action_mailer_basics.html)

### Acceptance Criteria
- [ ] Verify that email is sent to test recipient in UAT
- [ ] Verify calendar invite is attached to email

**Comment by lomaxap** [comment]
Question: Should we assume that recipient's email can handle HTML? Do we need to make sure that is accessible?

**Comment by nicholer** [comment]
@lomaxap I'd need to do more research myself (this HHS guide doesn't seem to require a plain text version? https://www.hhs.gov/web/section-508/making-files-accessible/checklist/email-508-checklist/index.html). But it would be good for accessibility if we were able to send a multi-part message with both a text-only version and the HTML version.
