### ISSUE TITLE
Notify Hearing Branch users when virtual hearing emails fail or conference creation fails

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12337]
#### User Story
As a Hearing Coordinator, I need to feel confident that I have Hearings Branch-wide visibility into the status of pending or failed attempts to schedule virtual hearings.

### Background
When a user changes a hearing to Virtual, the VirtualHearingsConferenceJob (#12331) sends a series of emails to the veteran, the representative, and the judge, and creates a conference via the Pexip API. If any of these steps fail, we need a way to signal to Hearing Coordinators that scheduling a virtual hearing was unsuccessful with steps to resolve the issue. This ticket will encompass the research and design work for building the functionality within Caseflow.

Spring 2020: Currently Caseflow doesn't provide visibility to Caseflow users; we monitor internally and alert the Hearing Branch of any issues.

~Fall 2019: For the first iteration of virtual hearings, we're looking to provide this visibility through a Tableau report~ ~the /jobs page, which is only accessible to users with admin privileges~ 
>**Note from Peter**:
>Note that the /jobs page should provide status on all async jobs already. If there is additional functionality needed for Hearings, specifically, we should identify that.
(https://github.com/department-of-veterans-affairs/caseflow/issues/12601#issuecomment-549990205)

**Comment by jimruggiero** [comment]
@lomaxap @pshahVA @nicholer What is the next step to move this one out of Define? Is there Design work to be done to address the "Hearings Branch-wide" piece of the user story, or is there additional ENG work that c/should be completed before that?

**Comment by nicholer** [comment]
From a design perspective, the next steps are: start exploring options for how we might display the status of jobs (in an existing team queue? in a new team queue? somewhere else?); understand the technical feasibility; test/refine with Hearing Branch users.

**Comment by pshahVA** [comment]
Yes, further research has to be done.  For the hearings MVP, we have implemeted

**Comment by lund5000** [comment]
After the shift to vc.va.gov for virtual hearing links the creation of a virtual hearing link is no longer asynchronous and prone to error. The email notification part of this ticket is now covered by https://vajira.max.gov/browse/CASEFLOW-1144.
