### ISSUE TITLE
Add Veteran and POA email fields to Hearing Details

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12339]
Updated designs: https://va-gov.invisionapp.com/d/main#/console/18813206/391798212/preview

### Background
- Once a hearing is switched to virtual, 2 fields appear for the Veteran's and POA's email. 
- Veteran Email field is **required**
- POA/Representative Email field is **not required**
- When the Hearing Type is Virtual, and the Hearing Coordinator changes either the Veteran Email or the POA/Representative Email on **Hearing Details** and selects 'Save', 
- A **confirmation modal** appears, displaying only the updated email address(es) - i.e. it displays either the newly-entered Veteran Email or the POA/Representative Email or both
- When the Hearing Coordinator selects to submit/confirm on the modal, Caseflow attempts to:
  - send email notification(s) to the newly-entered email(s) _(email content will be a separate issue)_
- While the async job for sending the email(s) are in progress: (_Revisions to alert messaging made 11/04_)
  - The **Hearing Details** page displays: 
      - an info alert
      - Hearing Type field is disabled
      - Veteran Email field is disabled
      - POA / Representative Email field is disabled
  - On the **Daily Docket** page, the Time field is disabled
- When the async job is complete: 
  - On the **Hearing Details** page:
      - Hearing Type field is editable
      - Veteran Email field is editable
      - POA / Representative Email field is editable
  - On the **Daily Docket** page, the Time field is editable

**Comment by pshahVA** [comment]
In terms of changing email addresses, it can get tricky because we should ideally:
1.)  Send a meeting cancellation to the old email address
2.) Fire off an email to the new address.  I'm thinking step 1, could be put into a later release if its difficult.
