### ISSUE TITLE
Confirm that Production URL for Pexip Conferences is Accessible Outside of VA network

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12344]
related to #12314 

We need credentials for creating conferences in Pexip for Pexip's Production environment. We also need to confirm that the urls we generate in production will be accessible outside of the VA network

@pshahVA can you follow up with Lynn about production credentials so we can test this / confirm with him that they will be accessible when we start making requests in production?

**Comment by ferristseng** [comment]
https://care.va.gov/vvc-app/#/
