### ISSUE TITLE
Email Copy for Virtual Hearing Confirmations and Updates

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12345]
### User story
As a Veteran / Representative / Judge, I need to receive email notifications when my virtual hearing is scheduled or updated.

This ticket addresses the following 8 use cases:
- 1) When a virtual hearing is scheduled or a new email address is entered on the Hearing Details page:
  - **1a) As a Veteran**, I need an email confirming that I have a virtual hearing scheduled with a date, time, link to conference, and instructions on how to access virtual hearings.
  - **1b) As a Representative**, I need an email confirming that I have a virtual hearing scheduled with a date, time, link to conference, instructions on how to access virtual hearings, _and a Veteran identifier_.
  - **1c) As a Judge**, I need an email confirming that I have a virtual hearing scheduled with a date, time, link to conference, instructions on how to access virtual hearings, _and a Veteran identifier_.
- 2) When a virtual hearing time is changed:
  - **2a) As a Veteran**, I need an email notifying me that the time for a virtual hearing has changed.
  - **2b) As a Representative**, I need an email notifying me that the time for a virtual hearing has changed _and a Veteran identifier_.
  - **2c) As a Judge** I need an email notifying me that the time for a virtual hearing has changed _and a Veteran identifier_.
- 3) When a virtual hearing is changed back to Video:
  - **3a) As a Veteran**, I need an email notifying me of the hearing location change.
  - **3b) As a Representative**, I need an email notifying me of the hearing location change _and a Veteran identifier_.

### Email content
https://docs.google.com/document/d/1u3x6KX5uu7V9G4jjctmuy8-AaXVgzo3t4Nm1C3AzMmE/edit?usp=sharing

### Open questions
1. Now that virtual hearings are visible to Judges in Caseflow on their Daily Docket, how important are the email notifications to the Judge?
1. If the email notifications to Judges continue to be important: Judges previously asked for a Veteran identifier in their virtual email notifications so they can tell which case is virtual (in the first iteration of emails, it was difficult to tell which case on the docket the email referred to). What Veteran information could be included in an email notification? `Representatives will need a Veteran identifier too`

### Related tickets

#12831 Email Copy for Virtual Hearing Cancellations and Reminders

**Comment by pshahVA** [comment]
The email needs to have a calendar invite, so it can be imported into the Judges and Veterans Cal.  Do we want a separate ticket for this or add it to this?

**Comment by lomaxap** [comment]
i'm fine adding it to this ticket

**Comment by pshahVA** [comment]
@nicholer, we will use your rough draft in the upcoming sprint.   Do you want to attach it here?

**Comment by nicholer** [comment]
@pshahVA We need help from the Board determining what Veteran information can be sent via email to Representatives and Judges, who will need some indication of which Veteran the email is referring to. 

We can assume all Judges are Caseflow users. But is that a safe assumption for Representatives?

**Comment by nicholer** [comment]
This work was completed.
