### ISSUE TITLE
Add Virtual Hearing Type to Column on Hearing Schedule List

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12348]
![Screenshot 2019-10-09 16.49.08.png](https://images.zenhubusercontent.com/5cd05a11cdc0ba05ef4f13f6/60a0939a-9835-4a2a-8c96-fb963382e70a)

The Your Hearing Schedule page displays Virtual in the Type column, and Virtual is included as a value in the column filter.
- If there are multiple Hearing Types for one day, all types are listed, separated by a comma.

**Comment by pshahVA** [comment]
@ferristseng, can we please add a screenshot, either in the ticket or the pull request.

**Comment by ferristseng** [comment]
@pshahVA added it to the pull request in the description
