### ISSUE TITLE
Get Range of Numbers that Can Be Used as Conference Ids

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12343]
Lynn informed us that we will need to use a range of 7 digit numbers when generating conference ids (#12314). This will allow veterans to eventually call into a number. 

@pshahVA Can you follow up with Lynn and get these range of numbers?

**Comment by pshahVA** [comment]
Correspondence 

> So the prefix BVA will allow you to use a digits 0-9 for that portion of the call.
> 
> Ex. BVA1234567
> 
> This provides 10M combinations so the randomization should be unique. It might be worth ensuring that the Conference Name and alias are unique against previously scheduled calls that have yet to take place.
> 
> Lyn

**Comment by pshahVA** [comment]
Thanks Lyn,

> Am I correct in assuming we can use any range of numbers as long as we keep them unique?

> Yes, the prefix keeps you unique within our systems and allows for BVA only reporting via our Analytics solution….. so it keeps you clean through our systems.

Lyn

**Comment by pshahVA** [comment]
Is this still blocking?
