### ISSUE TITLE
Update eslint camelcase rules to ignore "UNSAFE_" method names

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12359]
These warnings are useless:
$ eslint --max-warnings 0 --cache $(git diff --name-only --relative $(git merge-base $(git rev-parse --abbrev-ref HEAD) origin/master) *.js *.jsx)

/home/circleci/project/client/app/components/SearchBar.jsx
  45:3  warning  Identifier 'UNSAFE_componentWillReceiveProps' is not in camel case  camelcase

Based on this [eslint PR](https://github.com/eslint/eslint/pull/10783), we should be able to update the [eslint config](https://github.com/department-of-veterans-affairs/eslint-config-appeals/blob/master/.eslintrc.js) to ignore such method names.

**Comment by meckila-navapbc** [comment]
Resolved in #12341
