### ISSUE TITLE
Review Decision | PDF loading indicator is split up in two and overlaps parts of the page

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1235]
# Description
As a Caseworker reviewing a decision
When I go to Dispatch and click **Establish next claim**
When I land on the **Review Decision** page with *multiple documents*
The loading indicator for the PDF is off (see screenshot) and switching between documents causes
"Unexpected server response" error.
also, the procedure is really heavy on the client.

**Environment:**
- [X] Production
- [X] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [X] Performance
- [ ] Design
- [ ] Security
- [ ] Functional
 
# Reproduction Steps
Scenario 1 - Review Decision

1. Find an appeal with multiple decision documents

1. Go to Dispatch and start Establishing a claim

1. On the **Review Decision** page observe the loading indicator

1. Wonder

1. Start switching between the document tabs

1. Get errors

1. Listen to the fans in your computer go haywire

1. Open task monitor and observe CPU load

1. Feel all warmed up because your laptop is almost on fire

1. Or feel very *ventilated*

## Screenshots

**_Scenario 1 - Review Decision with CPU fans.. oh wait, there's no sound.._**
![documenswitchload](https://cloud.githubusercontent.com/assets/18075411/24075993/5fbd8d90-0bfd-11e7-8da0-a3dbd922fd1a.gif)

# Related Issues
**_Engineering_**
#1230 maybe? Cmon, people, write better tickets.

**Comment by shanear** [comment]
This low-ish priority because appeals having multiple decisions is very rare and this is a non-breaking bug.

**Comment by astewarttistatech** [comment]
@shanear the overlapping loading indicator happens wherever PDFs are being loaded, so it isn't as rare as once thought.

**Comment by kierachell** [comment]
**FIXED**
by some other issue
