### ISSUE TITLE
Update the task reassign function

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12365]
[As found](https://github.com/department-of-veterans-affairs/caseflow/issues/12173#issuecomment-541136486) when reassigning tasks in #12173, There are two pitfalls with our current reassign function.
1. If the task to be reassigned has a child `TimedHoldTask`, it will be [cancelled](https://github.com/department-of-veterans-affairs/caseflow/blob/e1a5d717fb51a34aeac10f276fc86a895266969f/app/models/task.rb#L581) before it is [moved under the new task](https://github.com/department-of-veterans-affairs/caseflow/blob/e1a5d717fb51a34aeac10f276fc86a895266969f/app/models/task.rb#L479).
2.  If the task to be reassigned has children, and is therefore on hold, the new task is not put on hold

## AC
- [ ] When a task is reassigned, children `TimedHoldTask`s are correctly moved under the new task
- [ ] When a task is reassigned, children `TimedHoldTask`s are not cancelled
- [ ] When a task with children is reassigned, the new task is put on hold

**Comment by kevmo** [comment]
```
1 | |||||
2 | |||||||||
3 | |
5 | 
8 |
```

Appears that no tests have failed because of this -- i.e. we probably don't have good tests for this.

2.
