### ISSUE TITLE
Fix paginated caching for first response when navigating via a deep link

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12367]
### What currently happens
When navigating to a paginated queue via a deep link, navigating away from the tab and back sends off a request to the pages api, even though we should have cached this result already.

#### Demo
![bug](https://user-images.githubusercontent.com/45575454/66678584-3b614700-ec3a-11e9-8f77-c5d21cc0c063.gif)

#### Steps to reproduce
1. Log in as a VLJ support team member (VLJ_SUPPORT_ADMIN)
2. Navigate to http://localhost:3000/organizations/vlj-support?tab=unassigned&page=1
3. Click on the Assigned tab
4. Click back to the Unassigned tab and notice the loading spinner in the queue table

### What we expect to happen
As occurs when not navigating via a deep link, navigating away from a tab and back does not send a request to the pages api.

#### Demo
![correct](https://user-images.githubusercontent.com/45575454/66678788-aca0fa00-ec3a-11e9-83e7-de0f2451a819.gif)

#### Steps to reproduce
1. Log in as a VLJ support team member (VLJ_SUPPORT_ADMIN)
2. Navigate to http://localhost:3000/organizations/vlj-support
3. Click on the Assigned tab
4. Click back to the Unassigned tab and notice there

## AC
- [ ] Navigating back to a tab that has already been loaded should not trigger a request to the task pages api

**Comment by kevmo** [comment]
```
1 | ||
2 | ||||||||||||
3 | |
5 |
8 |
```
