### ISSUE TITLE
Efolder Not Showing All Docs from VBMS

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12374]
https://dsva.slack.com/archives/CHX8FMP28/p1570803493080500

Efolder shows 0 documents for VBMS
![image](https://user-images.githubusercontent.com/2473869/66685884-b3843880-ec4b-11e9-83a2-05ad2dbdc364.png)

however, initial digging shows that at least some documents exist
```
d = Download.find(70423)
docs = ExternalApi::VBMSService.v2_fetch_documents_for(d.file_number)
docs.count
#=> 468
```

**Comment by alisan16** [comment]
Closing this out unless we get more requests about this issue.
