### ISSUE TITLE
MTV - Save partial grant to database with selected issues

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12370]
### User or job story
This is a backend ticket. This story covers what happens when a Judge "Submits" a partially granted motion to vacate with issues selected.

### Acceptance criteria
- The post decision motion disposition is partial_grant
- When the user submits the Address Motion to Vacate task, the IDs of the selected issues are saved in the post decision motions table
- Document new db column

### Technical notes
- Need to create a new db column

### Out of scope
- Additional processing on the partially granted issues (e.g. creating the new request issues)

### Release notes
See ticket https://github.com/department-of-veterans-affairs/caseflow/issues/11669

#### Designs
Not applicable (backend only).

#### Background/context
Not applicable.

**Comment by jcq** [comment]
The AC on here specifies that the new disposition be `partial_grant`, but all the others are past tense (`granted`, `denied`, etc). I had previously implemented it as just `partial`, which doesn't actually fit that pattern either. Should we match the AC? Should we match the pattern? Is `partially_granted` too long?

**Comment by leikkisa** [comment]
To the extent that I can make it up, I would say partially_granted is fine. We should check with @jimruggiero too, in case there is other disposition-related knowledge I'm not thinking of.

**Comment by jimruggiero** [comment]
partially_granted works
