### ISSUE TITLE
MTV - When mail team creates Motion to Vacate task, select issues the veteran is requesting

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12375]
### User or job story
When a veteran submits a motion to vacate, the specific issues they are requesting need to be selected and stored.  These should be the only issues that appear as selectable for the judge when deciding the disposition for the MTV.

### Acceptance criteria
- On the motion to vacate mail task, all decision issues on the appeal are available to select as options.
- Instructions to select the requested issues are shown.
- When the motion to vacate mail task is created, save the requested issues on the PostDecisionMotion table as requested_decision_issue_ids (please feel free to come up with a better name)
- If this work needs to be behind a feature toggle, included that in the AC. Include the name of the feature toggle.
- Please include a screenshot of the mail motion to vacate task modal

### Release notes
Caseflow now supports the ability to display issues specific to motions to vacate.

#### Designs
TBD

#### Technical notes
If the PostDecisionMotion is not created when the MotionToVacateMailTask is created, we will need to create it at this time in order to store the requested issues

**Comment by leikkisa** [comment]
Hi @rutvigupta-design @geronimoramos, this ticket is requesting a new screen to be designed for the Motion To Vacate flow.  This is the intake workflow screen that will show all of an appeals decision issues when creating the motion to vacate task.  The selected issues will be which issues to vacate.  Can you please let us know when you'll be able to create designs for this so that we can slot it into a near-term sprint?

**Comment by laurjpeterson** [comment]
Hey all - this ticket doesn't need to exist. Mail team members do not choose issues that are vacated. This can only happen after a judge decides to grant the motion to vacate, and as seen in this ticket, judges are going to choose full or partial vacatur. If they choose partial vacatur, then they have to choose which issues to vacate.

This is all captured here! https://github.com/department-of-veterans-affairs/caseflow/issues/12318

Going to close this to prevent further confusion
