### ISSUE TITLE
BSE 66125 – Capability for Caseflow to Track Proposals of Adverse Action Requiring Due Process – Track Claims Under EP600 

### ISSUE THREAD

**Issue by SusanRKagan** [department-of-veterans-affairs/caseflow#12386]
### Requirement
For proposals of adverse action requiring due process, Caseflow needs to be able to track these claims under an EP600 as the final decision is rendered under that EP 

### Value Statement
As a Caseflow user, I need the ability to clear an AMA claim so that the station is still given credit for processing the claim, while also closing the claim without the need to authorize an award, so that I can perform due process actions on AMA claims.

### Definition of Done
Allowing users to clear an AMA claim in Caseflow and reestablish an AMA-related EP600 will protect the rights of Veterans by ensuring that users can properly perform due process actions as defined under the law, and also ensure users are given the proper work credit for their actions.

### Acceptance criteria
1.	Users are able to clear an AMA claim in Caseflow such that the claim is cleared from the Corporate database, but users are still given credit for processing the claim.

Note: AMA claims for the purpose of this requirement are all EP 030s, 040, and AMA-related 930s

Note: The real "ask" here is that the system behave exactly the same way it does when a claim is cleared in VBMS or Share.

### Background

End Product | Claim Label
-- | --
600PREDTAMA | Predetermination Notice - AMA
600PREDTAMA | PMC -Predetermination Notice – AMA
600PRIAMA | Predetermination – Rating Issue – AMA
600PRIPMAMA | PMC – Predetermination – Rating Issue   - AMA
600DICPNPMC | PMC DIC Predetermination Notice - AMA

**Comment by leikkisa** [comment]
Linking a Slack thread with a prod example of this:
https://dsva.slack.com/archives/CFBLH2LR4/p1573509618192600

**Comment by leikkisa** [comment]
Will the EP600 be connected to the cleared claim? If we can reliably detect it, then we can close the issues waiting for an award.  We're already doing that if the AMA EP gets manually changed to a 400 EP.

I'm assuming the EP600 is created by the user in VBMS after they clear the AMA claim, but I want to confirm that the ability to create EP600's in Caseflow isn't part of the ask.
