### ISSUE TITLE
Add checkbox for verifying unidentified issue

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12380]
### User or job story
As a VSR, when I am editing a decision review's unidentified issues, I can click a checkbox to confirm that I verified that the issue is a valid past decision.

### Acceptance criteria
- [ ] This work should be behind a feature toggle: `verify_unidentified_issue`
- [ ] On the edit screen only, the unidentified issues modal shows a checkbox that the user can check to indicate that they've verified the issue has a valid past decision
- [ ] Above the checkbox are instructions to the user (see copy below)
- [ ] When the checkbox is checked, the submit button is disabled until all fields are populated
- [ ] When the checkbox is not checked, only the description is required (current behavior)
- [ ] This version of the modal is not available during regular intake, only on edit
- [ ] Include a screenshot of the new unidentified issues modal

### Copy
**Instructions above checkbox**
Please look for a record of the prior decision matching the description and decision date of the issue that was submitted by the veteran.

If you were unable to find a record of the prior decision, please leave the checkbox unchecked and fill in the description and decision date submitted by the veteran.

If found, use the prior decision's information to enter the description and decision date.  Update the notes with information on where you verified the record, such as VBMS or a decision document.  Please include identifying information for the record, such as a document title, that would allow another user to find it.

**Checkbox label**
Verify record of prior decision

### Out of scope
- Backend processing of the issue
- Eligibility check for issue

### Release notes
Users are able to add verified unidentified issues when editing a decision review, so that the issues can continue to be processed.

#### Designs
TBD

**Comment by Sjones352** [comment]
Current Screenshot
<img width="511" alt="Screen Shot 2020-01-09 at 1 14 47 AM" src="https://user-images.githubusercontent.com/23080951/72080811-673ca900-32cb-11ea-8c30-598e70b3535d.png">
