### ISSUE TITLE
BSE 66141: Capability to Set Status of Grants and Remand Partial Grants to RFD in Caseflow

### ISSUE THREAD

**Issue by SusanRKagan** [department-of-veterans-affairs/caseflow#12384]
### Requirement
Capability to Set Status of Grants and Remand Partial Grants to RFD in Caseflow

### Value Statement
As a Caseflow user, I need the system to automatically set the lifecycle status of Board full grants or remanded partial grants to "Ready for Decision" (RFD), so that the NWQ system can more expeditiously route and distribute the work to the correct decision maker and improve processing time.

### Definition of Done
Presently, whenever the Board send a full grant or remands a partial grant back to VBA, Caseflow is assigning a lifecycle status of "Initial Development" (IDEV).  The Business needs the lifecycle status of full grants or remanded partial grants to be automatically set to "Ready for Decision" (RFD) because this will enable the NWQ system to more expeditiously route and distribute the work to the correct decision maker and improve processing time.

### Acceptance criteria
1.	Whenever the Board sends a full grant back to VBA, Caseflow will automatically assign the corresponding EP with the status of RFD.
2.	Whenever the Board sends a remanded partial grant back to VBA, Caseflow will automatically assign the corresponding EP with the status of RFD.

**Comment by leikkisa** [comment]
Closing - this was completed with #13062
