### ISSUE TITLE
BSE 66139 - Capability to Create Separate Contentions for Effective Date and Evaluation Level

### ISSUE THREAD

**Issue by SusanRKagan** [department-of-veterans-affairs/caseflow#12383]
### Requirement
Capability to Create Separate Contentions for Service Connection, Effective Date and Evaluation Level

### Value Statement
As a Caseflow user, I need the ability to split out a single AMA contention into multiple contentions that track back to the original contention to support the scenario where an appellant disagrees with the service connection, effective date and/or evaluation level of a prior decision, so that I can provide a decision on each individual disagreement rather than lumping them together.

### Definition of Done
An appellant can appeal three different aspects of a decision issued by VBA or the Board: service connection, effective date, and/or the evaluation level assigned.  For decisions resulting in service connection, an appellant will commonly disagree with both the evaluation level and the effective date for the same decision/condition.  When this happens, users need to be able create three separate contentions for the same previously-decided condition.  E.g., a decision is issued in May 2019 for a right knee condition evaluated at 10%, effective March 1, 2019.  In June 2019, the appellant submits an HLR that indicates a disagreement with the service connection, evaluation level and the effective date (appellant says the evaluation level should be 30% and the effective date should be December 2018).  Users need the ability to split both these disagreements out into separate contentions so they can address them individually.

### Acceptance criteria
1.     Users are able to create multiple contentions in Caseflow that track back to a single contention.

**Comment by janechi1** [comment]
Adding a comment to this epic.  The "Definition of Done" considers 3 aspects a Veteran can appeal or request a decision review for service connection, effective date, and/or the evaluation level assigned.  A user should be able to split out these 3 rating issues to address separately in the event all 3 are at issue.  It was noted that it was primarily for effective date and/or evaluation level but service connection should be considered in the build as well.
