### ISSUE TITLE
Claim processing discontinued | Clicking Establish next claim returns JSON instead of HTML

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1238]
# Description
As a Caseworker when I completed a Dispatch task and attempt to **Establish next claim**
from either **Success** or *Discontinued** page
I expect to see **Review Decision** page but I get a JSON back. Workaround - go to **Work History** page first.

**Environment:**
- [ ] Production
- [X] UAT
- [X] Demo
- [ ] Development

**Type of Bug:**
- [X] Performance
- [ ] Design
- [ ] Security
- [X] Functional

# Reproduction Steps
Scenario 1 - Claim establishment discontinued

1. Start establishing a claim and get to **Review Decision** page

1. Click _Cancel_ and fill out the modal

1. Click **Stop establishing claim** button

1. Observe **Claim establishment discontinued** page

1. Click **Establish next claim** and get a JSON

1. Wonder.

1. Go back. Go forth. Go back again.

1. Wonder more...blame JS for all your troubles.

## Screenshots
**_Scenario 1 - Fun!_**
![json](https://cloud.githubusercontent.com/assets/18075411/24085278/4a71a962-0ccf-11e7-91af-b8121357e96b.gif)

**Comment by shanear** [comment]
@lakohl @abbyraskin have yall seen this in production?

**Comment by abbyraskin** [comment]
@shanear i haven't actually seen it myself, but yes, i believe this is an error Larry has previously described. he mentioned that he returns to Work History to continue.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. In Dispatch as a caseworker, cancel an EP during its creation. 
2. On the cancelation page, select "Establish Next Claim" 
3. Validate that Caseflow directs you to the Review Decision page for the next veteran in the queue

Screenshots:
<img width="1075" alt="screen shot 2017-04-04 at 9 13 28 am" src="https://cloud.githubusercontent.com/assets/23038505/24658285/46271b36-1917-11e7-989c-e4c5fddd4395.png">
