### ISSUE TITLE
Deliver Quarterly OIT Metrics Report

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12389]
Deliver quarterly metrics report to the OIT

Metric ID | 2. Metric Description | 3. Unit of Measure | 4. Performance Measurement Category Mapping | 5. Agency Baseline Capability | 6. 2018 Target | 7. 2019 Target | 8. Measurement Condition | 9. Reporting Frequency
-- | -- | -- | -- | -- | -- | -- | -- | --|
1709076052 | Caseflow Dispatch - Percent of non-denial decisions with an EP created within 7 days. Caseflow facilitates the transfer of cases to the Regional Office following issuance of a Board of Veterans’ Appeals decision, with an end product (EP) created to track work. Not creating an EP increases the possibility of miscommunication and slows average processing times, delaying ratings adjustment and working of remand orders. | (Number EPs with date<=7 days after outcoding date/number non-denial decisions) | Strategic and Business Results | 79.6 | 80 | 80 | Over target | Quarterly
1812216039 | Increase Veteran show rates at Board hearings using Caseflow Hearing Schedule, which enables a standardized scheduling process providing the ability to schedule hearings at both regional offices and alternate locations closer to Veterans’ homes. | (Total scheduled meetings held – postposed hearings/total scheduled meetings from Caseflow Hearing Schedule) | Strategic and Business Results |   | N/A | 75 | Over target | Quarterly
1812216044 | Mean (average) time to recovery (minutes) | Outage recovery time minus outage report time | Innovation |   | N/A | 30 minutes or less | Under target | Quarterly

**Comment by lomaxap** [comment]
is there a particular format we need to deliver these metrics to OIT in? And how do they expect to access these reports?

**Comment by alisan16** [comment]
Initially we'll follow the same delivery format as monthly reports, which is simply via email. Fred and I will coordinate delivery of the metrics to OIT, and it consists of an email with basic metrics and an excel spreadsheet attachment with a deeper dive.

In terms of what format we should deliver the metrics in - we have the flexibility to define it. Example output for the monthly appeals established metric: https://dsva.slack.com/archives/CN3FQR4A1/p1569610992036200

**Comment by alisan16** [comment]
Closing to track in #12748 instead
