### ISSUE TITLE
Create method to reassign all open tasks for a given user

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12394]
When a Caseflow user becomes inactive we need some mechanism to reassign the open tasks assigned to that person. This ticket exists to implement the solution [outlined in the tech spec](https://github.com/department-of-veterans-affairs/caseflow/pull/12197/files#diff-33a91cd5134bf0c5a4522e456e900342) from PR #12197.

### Acceptance criteria
* [ ] Create rake task that reassigns open tasks for a given user as described by #12197.

**Comment by kevmo** [comment]
1 | 
2 | ||
3 | |||||||||
5 | |
8 |

3. The big variable here is testing.  Test lightly to begin.  

Note: The scope is limited to only creating the Rake task (and documenting that task for the bat team).  Expect Rake task to be run manually for the time being.

**Comment by kevmo** [comment]
Blocked by https://github.com/department-of-veterans-affairs/caseflow/issues/12365

**Comment by hschallhorn** [comment]
Possible user to test this function on in production once finished:
>We have an employee that has departed the Board of Veteran Appeal and the employee has 225 task assigned to her (BVAHUNTER) Queue, is it possible for your staff to be reassign those task to other members of the Veteran Law Judge Support Staff.  Please advise and thank you in advance
