### ISSUE TITLE
Queue knowledge share

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12392]
This Github issue exists to collect questions about various Queue-related features, implementation characteristics, and decision-making processes so that we can pass on that knowledge and inform decision-making into the future! A lot of information [related to Queue is captured in the wiki](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Queue) (topics covered so far in the wiki include [tasks](https://github.com/department-of-veterans-affairs/caseflow/wiki/Tasks) and [organizations](https://github.com/department-of-veterans-affairs/caseflow/wiki/Organizations)), but if you have questions that are not answered by the content in the wiki, then thread them here and we can respond to them here before adding them to the wiki.

**Comment by lowellrex** [comment]
* [ ] What is the difference between `TimedHoldTask`s, `TimeableTask`s, and `TaskTimers`?

**Comment by lowellrex** [comment]
> * [x]  What is the difference between `TimedHoldTask`s, `TimeableTask`s, and `TaskTimers`?

Added a section to the [tasks wiki page](https://github.com/department-of-veterans-affairs/caseflow/blob/61a87f3b356cfd3d31dbd2be36e0bf311fd66e85/app/models/tasks/evidence_submission_window_task.rb#L6) that links to a dedicated [wiki page for timed tasks](https://github.com/department-of-veterans-affairs/caseflow/wiki/Timed-Tasks).

**Comment by jcq** [comment]
What is the automated behavior regarding tasks when the user to which they are assigned is marked inactive? 

If a user is marked inactive, currently assigned tasks go to the organization?

What happens if you try to create/assign a task to a currently inactive user? Does it automatically go to the org, throw an error, something else...?

**Comment by lowellrex** [comment]
> What is the automated behavior regarding tasks when the user to which they are assigned is marked inactive?
>
> If a user is marked inactive, currently assigned tasks go to the organization?

Great question! This has not yet been implemented (will be implemented by #12394), but [the tech spec has more detail](https://github.com/department-of-veterans-affairs/caseflow/pull/12197/files?short_path=33a91cd#diff-33a91cd5134bf0c5a4522e456e900342) about how the automated re-assignment should behave. I expect the implementation will follow the tech spec. A quick summary of the various outcomes of re-assignment is provided by the table below.

Scenario | Outcome of automatic re-assignment
--- | ---
Task to be reassigned has no parent task | We should never attempt to reassign a task wihtout a parent task. Raise an error if we do.
Task is a `JudgeAssignTask` | Make the case available for distribution again (re-open the parent `DistributionTask`
Task is a `JudgeDecisionReviewTask` | Reassign the task to the drafting attorney's new supervising judge.
Parent task assigned to `Organization` using automatic child task assignment | Use automatic child task assignment to assign the task to a new user.
Parent task assigned to `Organization` without automatic assignment | Activate the parent organizationally-assigned task (AKA assign the case to the organization)
Parent task assigned to `User` | Activate the parent task (e.g. `AttorneyTask` with a parent `JudgeDecisionReviewTask`).

**Comment by lowellrex** [comment]
> What happens if you try to create/assign a task to a currently inactive user? Does it automatically go to the org, throw an error, something else...?

I don't think we currently have any protection in the code that prevents inactive users from receiving tasks. I'd imagine we'll want to exclude them from [automatic task assignment](https://github.com/department-of-veterans-affairs/caseflow/blob/86c848a5a3e5d03e84332b081875593c3bbf656a/app/models/colocated_task_distributor.rb#L4) as well as [receiving tasks directly](https://github.com/department-of-veterans-affairs/caseflow/blob/86c848a5a3e5d03e84332b081875593c3bbf656a/app/controllers/tasks_controller.rb#L67). Perhaps @hschallhorn can confirm my suspicion and maybe point out a ticket that exists to implement this protection.

There are [currently no users in the database](https://caseflow-looker.va.gov/sql/pxgwsnfzyf5dnq) who are inactive.
```sql
sql> select distinct(status) from users;
# active
```

**Comment by yoomlam** [comment]
> > * [x]   What is the difference between `TimedHoldTask`s, `TimeableTask`s, and `TaskTimers`?
> 
> Added a section to the [tasks wiki page](https://github.com/department-of-veterans-affairs/caseflow/blob/61a87f3b356cfd3d31dbd2be36e0bf311fd66e85/app/models/tasks/evidence_submission_window_task.rb#L6) that links to a dedicated [wiki page for timed tasks](https://github.com/department-of-veterans-affairs/caseflow/wiki/Timed-Tasks).

Can a TimeableTask be cancelled?

**Comment by lowellrex** [comment]
> Can a TimeableTask be cancelled?

Yup! Added a [section with more detail](https://github.com/department-of-veterans-affairs/caseflow/wiki/Timed-Tasks#can-a-timeabletask-be-cancelled) to the wiki page for timed tasks.

**Comment by hschallhorn** [comment]
>when a User's status is updated, that user is removed from any teams to which they belong
