### ISSUE TITLE
Create table to connect a request issue to many legacy issues

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12397]
### User or job story
As a user, I would like to be able to connect multiple legacy issues to a request issue.

### Acceptance criteria
- Create a new table called request_legacy_issues
  - Add a table DB comment (see "copy" below)
- Add the following fields to the new table, with DB comments
  - id (primary key)
  - timestamps
  - request_issue_id (required, foreign key)
  - vacols_id (required)
  - vacols_sequence_id (required)
  - legacy_issue_optin_id (optional, foreign key)

**Note - the following two bullets can be separated into a separate chunk of work if desired.**
- the current data from request_issues and legacy_issue_optins is copied to the new table via a migration
- when a new request issue is created and it's connected to a legacy issue, there is a hook that saves a copy of the relevant data to the new table

### Copy
New table comment (feel free to edit):

When a user creates a request issue for a veteran, they have the opportunity to connect it to one or more legacy issues from VACOLS.  If the veteran also chooses to opt their legacy issues into AMA, the issues are closed in VACOLS through a legacy issue opt-in. This table stores the legacy issues connected to each request issue, and the record for opting them into AMA (if applicable).

### Release notes
N/A

#### Designs
N/A

#### Background/context
This is a technical ticket to support a one-to-many relationship between request issues and legacy issues.  

Not all vacols issues that are connected to a request issue get opted-in.  They only get opted in if the veteran selects to have their legacy issues opted in to AMA.

The first step will be creating and maintaining a copy of the current data (in request issues and legacy issue optins) in the new table.  Once that is ready, the next step is to switch the logic to using the the new table.  Then the vacols_id and vacols_sequence_id fields can be removed from the request_issues table.

After the data structure is ready, the final ticket for supporting multiple legacy issues is here:
See: https://github.com/department-of-veterans-affairs/caseflow/issues/11103

#### Technical notes
A before_save or after_save hook will help populate the data not populated during the migration to backfill the data.

The existing table and column comments in the schema may be useful for coming up with the column comments on the new tables.

**Comment by pkarman** [comment]
The story in #11103 says

> As a user, I would like to be able to opt-in multiple legacy issues per request issue.

which seems different than "connecting multiple". AFAIK the current Add Issues flow only gives the modal for connecting legacy issues when the opt-in box is checked, effectively making all connections == opt-ins.

> Not all vacols issues that are connected to a request issue get opted-in.

I'm curious: where did the business requirement originate for connecting legacy issues w/o opting them in? What does it mean, from a business standpoint, to connect issues? And is there a ticket for changing the UI logic to allow connection without opt-in?

**Comment by leikkisa** [comment]
@pkarman There is a front-end ticket coming up once the back end work is complete to allow connecting multiple issues here:
https://github.com/department-of-veterans-affairs/caseflow/issues/12693
If the veteran selects to opt the issues in, then multiple legacy issues will get closed in VACOLS. 

Currently, we connect issues even if they don't get opted in, and if they don't get opted in and are connected then they're not eligible for AMA.  For selecting multiple, if they don't select to opt them in, then it probably doesn't make a difference since the issue would already be ineligible once one issue is connected (I would have to double check eligibility rules, in case one issue was eligible for opt in and a second issue was added that is not eligible).
