### ISSUE TITLE
Create data integrity check for stalled appeals

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12395]
After #12394 is implemented, we will be able to reassign tasks assigned to inactive Caseflow users. While reviewing the tech spec, @yoomlam [identified the possibility](https://github.com/department-of-veterans-affairs/caseflow/pull/12197/files#r329171990) that these tasks may be reassigned to organizations whose queues are not actively monitored and may be ignored for extended periods of time. As a first step in ensuring these appeals continue to progress through the Board, we should create a [data integrity check](https://github.com/department-of-veterans-affairs/caseflow/blob/0170d3e7771d942d2ce788e02e62b20415b0a592/app/jobs/data_integrity_checks_job.rb#L3) to notify us when an appeal's forward progress stalls.

Characteristics of a stalled appeal include:
* Having been distributed to a judge
* Not having been dispatched
* Not having had any tasks acted on in the past month (?)

A sketch of a sql statement that could satisfy this requirement follows:
```sql
select max(updated_at)
from tasks
where appeal_type = 'Appeal'
  and appeal_id in {{ IDs of distributed, non-dispatched Appeals }}
group by appeal_id
  having max(updated_at) < {{ 1 month ago }};
```

### Acceptance criteria
- [ ] Create a data integrity check that checks for stalled appeals

**Comment by hschallhorn** [comment]
Time check should be AT LEAST 120 days to allow for evidence submission. Alert should be used to ensure the appeal is not stuck due to caseflow.

**Comment by hschallhorn** [comment]
@pkarman Is this still echo or is this something for delta to handle?

**Comment by pkarman** [comment]
delta can take this on.
