### ISSUE TITLE
Create stakeholder interview guide

### ISSUE THREAD

**Issue by RyanSibley** [department-of-veterans-affairs/caseflow#12406]
Create an interview guide to use during conversations with stakeholders to help us meet our learning goals. 

The stakeholder interview scratch pad can be found here: 

https://docs.google.com/document/d/1uPOV6PJ3CRLsqYiMPEvHpVWPYNFZ6O08LbfIPDEC0zw/edit#

AC: 

* Interview guide created with input from team Bravo
* Interview guide placed into Eric's template

**Comment by chandracarney** [comment]
Scratchpad and notes were formed into a functional stakeholder interview template. This was reviewed by the direct team along with other Caseflow members before being utilized with stakeholder research sessions. It can be found here: https://docs.google.com/document/d/1ZcMbsU9NBXF5IIh79yHzRXQBIsEuvywpzugfS0-1bHM
