### ISSUE TITLE
Create user interview guide

### ISSUE THREAD

**Issue by RyanSibley** [department-of-veterans-affairs/caseflow#12407]
Create an interview guide to use during conversations with users to help us meet our learning goals.

The user interview scratch pad can be found here:

https://docs.google.com/document/d/1uPOV6PJ3CRLsqYiMPEvHpVWPYNFZ6O08LbfIPDEC0zw/edit#

AC:

Interview guide created with input from team Bravo
Interview guide placed into Eric's template

**Comment by chandracarney** [comment]
Scratchpad and notes were formed into a functional user interview template. This was reviewed by the direct team along with other Caseflow members before being utilized with attorneys and judges. It can be found here: https://docs.google.com/document/d/1VkTmzPiu4pvyXc1kbzfukC5e2is0kFyTDK1NFzGHRqI/edit
