### ISSUE TITLE
Disallow queue deep links that do not exist

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12400]
As brought up in [#12372](https://github.com/department-of-veterans-affairs/caseflow/pull/12372#pullrequestreview-302052309), we should limit deep link parameters to ones that exist. 

### Specifying a higher page number than exists

**Problem**: queue displays no tasks and no way to get to the first page

/organizations/vlj-support?tab=assigned&page=**2**

<img width="909" alt="Screen Shot 2019-10-16 at 8 58 52 AM" src="https://user-images.githubusercontent.com/45575454/66921447-37934300-eff3-11e9-994e-dcfa08b152f6.png">

### Filtering on a column that does not exist

**Problem**: White screen of death

/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3D**INVALID_COLUMN_NAME**%26val%3DArnesonColocatedTask

<img width="881" alt="Screen Shot 2019-10-16 at 9 06 54 AM" src="https://user-images.githubusercontent.com/45575454/66922066-547c4600-eff4-11e9-8355-4d866060d80d.png">

### Filtering with a value that does not exist

**Problem**: Filter indicator and filter summary indicates a column is being filtered, but no filter values are selected and the results are not filtered

/organizations/vlj-support?tab=assigned&page=1&filter%5B%5D=col%3DtaskColumn%26val%3D**INVALID_FILTER_VALUE**

<img width="896" alt="Screen Shot 2019-10-16 at 9 08 49 AM" src="https://user-images.githubusercontent.com/45575454/66922198-9d33ff00-eff4-11e9-822c-ef7532b944c5.png">

### Specifying a tab that does not exist

/organizations/vlj-support?tab=**INVALID_TAB_NAME**

<img width="897" alt="Screen Shot 2019-10-16 at 9 04 13 AM" src="https://user-images.githubusercontent.com/45575454/66921854-f3547280-eff3-11e9-8597-dc7481530578.png">

_Defaults to initial tab_

### Sorting on a column that does not exist

/organizations/vlj-support?tab=assigned&page=1&sort_by=**INVALID_COLUMN**&order=desc

<img width="892" alt="Screen Shot 2019-10-16 at 9 00 43 AM" src="https://user-images.githubusercontent.com/45575454/66921564-80e39280-eff3-11e9-9351-10d1cbd8dd53.png">

_Does not sort on any column_

### Sorting with an order that does not exist

/organizations/vlj-support?tab=assigned&page=1&sort_by=taskColumn&order=**INVALID_SORT_ORDER**

<img width="898" alt="Screen Shot 2019-10-16 at 9 01 47 AM" src="https://user-images.githubusercontent.com/45575454/66921629-9ce73400-eff3-11e9-991d-9122ef2d7615.png">

_Defaults to ascending_

### AC
- [ ] Default deep link parameters to
  - [ ] First page of results if the specified page is greater that the total number of pages
  - [ ] Filtering on no columns if the column does not exist of the specified tab
  - [ ] Not filtering on a column if the filter value does not exist
- [ ] After the page loads, the URL should display corrected query params

### Thoughts
 > Not filtering on a column if the filter value does not exist

What if the filter value is valid, but the set of tasks returned (and therefore the filter values passed in queue_config) do not include that value?
We should also only ignore the column and single value that is incorrect. If other columns with valid values are passed, filtering for those should still be displayed. Same goes for other valid values passed with a column with an invalid value.

**Comment by lowellrex** [comment]
> Specifying a tab that does not exist
> /organizations/vlj-support?tab=INVALID_TAB_NAME

For this example (and the similar sorting scenarios), I think we might want to update the URL to reflect what that default value is (in this case `unassigned`). Though that request may be beyond the scope of this ticket.

**Comment by hschallhorn** [comment]
> I think we might want to update the URL to reflect what that default value is

I agree! This could definitely be within this ticket's scope as it may be easiest to validate and fix the provided params, then pass those to where we update the page and the url

**Comment by kevmo** [comment]
```
1 |
2 | |||||||
3 | ||||||||
5 |
8 |
```

One potential avenue: If invalid URL, backend responds as such, then frontend shows default view instead.

Validate on front-end and back-end. 

The filtering will likely be most difficult.  Look at doing it on the front-end first (may be harder than we initially think), then look at backend. 

Estimating at a 3.
