### ISSUE TITLE
Retry automatically once for document count before returning a 500 error

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#12404]
### Job story
When a user loads a page that shows document counts, they need Caseflow to retry failed requests, so that the counts are accurate. 

Currently if our first request to efolder for document count fails, we return a 500 error. If document requests happen during a server restart, we can get a flurry of failures that trigger alerts.

### Acceptance criteria
- [ ] if a request to efolder for document count request fails, retry immediately; if the retry fails, return a 500 error.

#### Resources/other links
[Related slack thread](https://dsva.slack.com/archives/C4JECDLSE/p1571240279059900)

**Comment by pkarman** [comment]
Search cloudwatch logs with a filter like `[ip, id, user, timestamp, request, status_code=5*, size]`

**Comment by pkarman** [comment]
This turned out to be an ELB config issue.
