### ISSUE TITLE
Serve Raven JS from the VA

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1241]
Right now, we are serving Raven from the Raven CDN. We should move it to a CDN that the VA owns.

See:
https://github.com/department-of-veterans-affairs/caseflow/pull/1240#pullrequestreview-27846214
for info

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
