### ISSUE TITLE
Missing Decisions Page: "Decision Date" displays as "aN/aN/NaN" if outcoding_date is empty

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1242]
A claim on the Claims Missing Decisions page displayed a blank Decision Type, and "aN/aN/NaN" as the Decision Date --@cmgiven can you elaborate on what is going on here if you know more (and any recommendations for handling)?

**Comment by cmgiven** [comment]
This full grant was dispatched (probably mistakenly), and thus placed in history status, and given the decision date of Thursday. On Friday, someone identified an error, and reopened the case, moving it back into active status, and removing the decision date. At no point was the decision uploaded, so despite our failing to catch this exception, it was never shown as ready to be CESTed.

Recommendation for handling is to ensure that all cases that can be shown in the queue must have a decision date, and must be in HIS or REM status. If not, they should be held, as is done with those cases that are awaiting a decision document to be uploaded.

**Comment by kierachell** [comment]
Confirmed that it is possible to pull a HIS/REM status claims without `TIOCTIME` (we only really check for `TIVBMS`)

**Comment by shanear** [comment]
This will be subsumed by:
https://github.com/department-of-veterans-affairs/caseflow/issues/1256

closing
