### ISSUE TITLE
SCM: SCM Team can view Judge's Assign Queue

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12423]
Give SCM Team members the ability to see all Judge assign queues.

### Acceptance Criteria
  - [ ] SCM Team members can view all Judge Assign Queues
![Screenshot from 2019-10-17 16-57-09](https://user-images.githubusercontent.com/6129479/67046903-318a8880-f0ff-11e9-977c-68aa10941b6a.png)
 - [ ] Functionality is tied to the feature flag.
    - Existing JudgeTeams with multiple admins need to be unaffected until we're feature complete

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||
2 | ||||||
3 | ||||||
5 | |||
8 | 
```

Estimate at a 3. Likely need to do some work around finding the judge (judge assign is based on the judge id), and making sure to update the page appropriately

**Comment by hschallhorn** [comment]
This ticket has been re-scoped to just allowing the SCM team to view judge assign queues

**Comment by yoomlam** [comment]
For this ticket, after SCM assigns to judge, user will be redirected to the judges assign queue.
Context: https://dsva.slack.com/archives/CJL810329/p1582728819042700
