### ISSUE TITLE
Styleguide component | Dropdown

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1243]
As a developer and designer, I want a consistent way to incorporate drop downs across our apps so users can easily select relevant options in an easy and accessible way. 

## Acceptance Criteria 

1. Verify that the title "Dropdown" appears
1. Verify that there is a horizontal line above the title
1. Verify that the "Dropdown" appears under the copy with the related react component 
1. Verify that the "Dropdown" appears on the left nav and clicking it takes you to the appropriate element 
1. Verify the the hover color is #5B616B
1. Verify that once the text field is selected, it has the default focus 

## Mockup

**Dropdown**

![image](https://cloud.githubusercontent.com/assets/13420618/26253386/2e431fe6-3c81-11e7-8b30-bbbdefd3afb9.png)

# Copy

This one does not have a copy

# Related Stories
For the regular dropdowns, we will move away from USWDS and use a style that is similar to our searchable dropdown #1081.

**Comment by astewarttistatech** [comment]
@tejans24 This is currently not found in the living style guide. Please put this back into "In Validation" when it is able to be tested.

**Comment by astewarttistatech** [comment]
AC/Mocks need to be updated.

**Comment by tejans24** [comment]
@gnakm do we plan on replacing all dropdowns in caseflow with this dropdown?

**Comment by astewarttistatech** [comment]
@tejans24 Mocks are still not updated. Pushing this back.

**Comment by gnakm** [comment]
@astewarttistatech updated mock.

**Comment by tejans24** [comment]
thanks @gnakm

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living style guide
2. Navigate to the drop down menus
3. Validate UI against mocks

Screenshots: 
<img width="1407" alt="screen shot 2017-05-23 at 11 49 38 am" src="https://cloud.githubusercontent.com/assets/23038505/26363102/1074e49c-3fae-11e7-8bb8-52c7e8f63841.png">
<img width="937" alt="screen shot 2017-05-23 at 11 50 05 am" src="https://cloud.githubusercontent.com/assets/23038505/26363105/119c283a-3fae-11e7-8a7b-1ecd13b96ae0.png">
