### ISSUE TITLE
SCM: Add Judge & Attorney Selectors to JudgeTeam Team Page

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12433]
Give JudgeTeam Admins the ability to flag users as Judge or Attorneys on the JudgeTeam page

### Acceptance Criteria
 - [ ] JudgeTeam page has the ability to flag users as Judge, Attorney.
 - [ ] Functionality is tied to feature flag. 
 - [ ] Please include one or more screenshots when complete.

Part of #11801

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |||
3 | |||||||||||||
5 | ||
8 | 
```

Estimating at a 3. Possibly a 2 as its largely making a front end update to match the back end. Possibly a 5 as it cleaves off a whole new page, and we need new controllers. A lot of code, straightforward, but a lot. This particular component doesn't currently care about what organization it is, possibly keep that knowledge of this being a judgeteam on the backend, rather than having the front end duplicate the knowledge. Possibly duplicate the work frontend/backend now to make this easier for now?

Add copy about what being admin for a JudgeTeam means!

**Comment by jimruggiero** [comment]
@ajspotts Can you attach a screenshot to this ticket?
