### ISSUE TITLE
Enable attorneys to recover from accidental AttorneyTask cancellation

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12443]
An attorney recently accidentally cancelled an `AttorneyTask` ([see Slack conversation](https://dsva.slack.com/archives/CHX8FMP28/p1571669690183100)). Restoring the task tree to the correct state where the attorney could submit their decision via the "attorney checkout" process required developer intervention to correct. Though accidentally cancelling an `AttorneyTask` is a rare event, the implications of this actions are great enough that it should be a user-recoverable mistake.

A few options for how to proceed are outlined below:
1. Add an option for the attorney to undo the cancellation immediately after they took that action.
    * Disadvantages: Attorney may not realize their mistake until hours later.
2. Add a button in the case timeline view to undo this action
    * Disadvantages: The task tree may be in an unexpected state and re-opening the task may be somewhat involved. For now though, cancelling the `AttorneyTask` cascades task closures through the parent `JudgeDecisionReviewTask` and `RootTask`, so I think most forward progress will be halted and we can assume that branch of the task tree will be in that particular state.
3. Remove the ability for attorneys to cancel `AttorneyTask`s.
    * Disadvantages: [Judges and attorneys can cancel `AttorneyTask`s](https://github.com/department-of-veterans-affairs/caseflow/blob/0204db2c531647cc0178df1b3c78e233fe7cae81/app/models/tasks/attorney_task.rb#L19) and may have valid reasons for doing so. Realistically, I don't think this happens very often or we would have heard more complaints about exactly the same problem that triggered this ticket.
4. Use the assigning judge as the back-stop for cancellations. Stop cascading closures of `AttorneyTask`s at the parent task.
    * Disadvantages: Attorney still does not have ability to correct the accidental cancellation themselves and must have the assigning [judge re-assign them the case](https://github.com/department-of-veterans-affairs/caseflow/blob/0204db2c531647cc0178df1b3c78e233fe7cae81/app/models/tasks/judge_decision_review_task.rb#L13).

## A word of caution
This ticket could lead us down the path of exploring a more generic "undo" feature in Caseflow. If we head down that path, I would recommend we spin that exploration out into a dedicated tech spec and conversation.

## Acceptance criteria
* [ ] Ensure that an attorney cancelling an `AttorneyTask` does not prevent progress on an appeal.

**Comment by jimruggiero** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||
2 | ||||
3 | |||||||||
5 | |
8 | 
```
Estimate is specifically for implementing option 4 only. Assuming this is one callback of cancelling the judge root task and that action cascading up. May be a 2 if additional callbacks are found. Bug and testing should be straightforward.

**Comment by lomky** [comment]
I am not immediately able to recreate the failure as we think it happened in the cited case. As best I can tell, option 4 is indeed the current state of the code. I'm going to look more into the production case to see if we have some older task-tree states that led to this issue

Development Appeal state after cancelling Attorney Task:
```
Appeal 101 [id, status]
└── RootTask 326, on_hold
    ├── DistributionTask 327, completed
    ├── JudgeAssignTask 328, completed
    ├── JudgeDecisionReviewTask 900, cancelled
    │   └── AttorneyTask 902, cancelled
    └── JudgeAssignTask 904, assigned
```

Test coverage of this scenario: 
https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/models/tasks/attorney_task_spec.rb#L139

**Comment by lomky** [comment]
Digging further in, it looks like the Attorney cancelled the case by removing the last issue, rather than cancelling their task via the task action. Coordinated with @wturne to clarify how cancel paths work in attorney training docs. Closing issue as a no-op.
