### ISSUE TITLE
undefined method `bfso' for nil:NilClass

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12442]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6649/

appeal with an external id `3606367` does not have a vacols record and is returning this error when attempting to geomatch

```
rep_info = get_poa_from_vacols_poa(
      vacols_code: case_record.bfso,
      representative_record: representative
    )
```

**Comment by hschallhorn** [comment]
Similar: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6988/
Resolution: https://dsva.slack.com/archives/CLRTL92TW/p1572876013003100

**Comment by hschallhorn** [comment]
Had the wrong vacols_id, not resolved

**Comment by pshahVA** [comment]
closing in favor of #12810
