### ISSUE TITLE
VSO is unable to access case details for veteran

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12453]
### User or job story
As a VSO, I need to be able to access the case details page for one of my veterans.  I am also designated as the veteran's POA. I am receiving the error: BGS::ShareError (Power of Attorney of Folder is none. Access to this record is denied.)

### Background/Context
User ID 2124 is the VSO for veteran ID 272634, but is not able to access their bgs record, and therefore cannot see the veteran's case details page.  An ESCP request has been submitted to BGS to resolve this issue.

### Acceptance criteria
- Confirm that while logged in as VACOWENDET, that the following page is accessible:
  - https://appeals.cf.ds.va.gov/queue/appeals/7ca0008e-a077-4d73-af2a-10da32809616

### External requests
SR-002328
https://escp.aac.va.gov/ServiceRequest/Details/13785?isDraft=false

#### Resources/other links
https://dsva.slack.com/archives/CHX8FMP28/p1571764635227200
https://dsva.slack.com/archives/CHX8FMP28/p1571764635227200

**Comment by pkarman** [comment]
According to John Dell this is fixed and we should confirm.

**Comment by leikkisa** [comment]
We are still getting the same error.

**Comment by msj0nes** [comment]
# Per BGS ticket  INC7600300
DEFECT 1188367 was created in RTC and assigned to Cory Easley from BGS Team 1 for resolution. 

BGS is recommending closing the ticket. Data was found out of sync and has been corrected.

**Comment by msj0nes** [comment]
# Resolution Confirmed in Prod
Confirmed via CSS ID  VACOWENDET the following page is NOW accessible:
https://appeals.cf.ds.va.gov/queue/appeals/7ca0008e-a077-4d73-af2a-10da3280961

**Comment by msj0nes** [comment]
@pkarman  and @leikkisa  ready to close when you are

**Comment by leikkisa** [comment]
Thanks @msj0nes ! Closing ticket
