### ISSUE TITLE
Existing EP | Cancel modal does not allow text input

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1247]
When the user clicks Cancel on the Existing EP page the Modal displays but does not allow the user to type an Explanation in the text box. Therefore the user cannot Stop Processing the Claim and is stuck at this step.

Not reproducible except for in IE with specific Full Grant EPs only available in `prod`

**Comment by shanear** [comment]
@lakohl after our deploy this afternoon, we should have a lot better vision into this issue.

**Comment by shanear** [comment]
@lakohl @abbyraskin I haven't seen any errors for this. Is this still happening for people?

**Comment by lakohl** [comment]
I have not, and I asked Support and they have not either. Let's keep this issue open until we do the follow up training/Q & A tomorrow in case it come up. Some folks may not have reported it. If it doesn't appear to be happening anymore I'll close the issue.

**Comment by shanear** [comment]
@lakohl assigning to you to close if we aren't seeing it.

**Comment by lakohl** [comment]
closing until it comes up again
