### ISSUE TITLE
Route Claim: Assign Existing EP | won't assign EP

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1248]
On the Route Claim: Assign Existing EP page, when the user clicks the 'Assign to claim' button, Caseflow displays an Error message. It does not Assign the EP to the claim, and it does not allow the user to move forward.

The user verified that the EP did exist as it was  in VBMS.
<img width="966" alt="screen shot 2017-03-20 at 3 30 43 pm" src="https://cloud.githubusercontent.com/assets/18075411/24128000/629bdc20-0daf-11e7-891e-8f5523e2aae8.png">
<img width="1093" alt="screen shot 2017-03-20 at 7 23 07 pm" src="https://cloud.githubusercontent.com/assets/18075411/24128001/629eb990-0daf-11e7-99e5-6b65f598c87a.png">

That's all the error you'll get.

**Comment by kierachell** [comment]
Has been reported earlier but called a "test data problem", re-reported as #1244

**Comment by shanear** [comment]
this is a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/1254

I will be working on it ASAP
