### ISSUE TITLE
Route Claim: Send Email notification | separate email addresses with a semicolon

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1249]
Send Email Notification page, currently the email addresses are separated by a comma only (with no space). When the user copies & pastes the email addresses into Outlook they don't register properly. We should separate emails with a semicolon followed by a space and verify that when they are copy/pasted into Outlook together they display correctly.

## Acceptance Criteria
- Validate that on the "Route Claim: Send Email Notification", when there are multiple emails (e.g. _DIC - death, or accrued benefits - United States_), the emails are seperated by "; " instead of a comma.

## Additional Information

This is on the Full Grant **Route Claim: Send Email Notification** page
<img width="574" alt="screen shot 2017-03-20 at 7 08 34 pm" src="https://cloud.githubusercontent.com/assets/18075411/24125746/a8dc71a4-0da0-11e7-8b9f-33f2f8baed56.png">

**Expected:**

- Emails separated by semicolon + space

**Comment by kierachell** [comment]
**PASSED**
<img width="787" alt="screen shot 2017-03-29 at 11 46 04 am" src="https://cloud.githubusercontent.com/assets/18075411/24463659/5fe5f5fc-1475-11e7-8d41-92f54b9bfe56.png">
