### ISSUE TITLE
Prevent judges from being removed from their JudgeTeams

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12492]
Right now, any admin of a `JudgeTeam` can remove the judge associated with that `JudgeTeam`. This ticket exists to create a control in the application that prevents folks from doing that.

![remove-aabshire](https://user-images.githubusercontent.com/32683958/67708328-58b04800-f992-11e9-839c-7d02dca130c7.gif)
Admins should not be able to do this ☝️ 

## Acceptance criteria
* [ ] `JudgeTeam` admins can no longer remove the judge of a `JudgeTeam` from that team

**Comment by hschallhorn** [comment]
Did we determine this would be front end or back end or both? I remember discussing it in estimation, but it looks like that did not make it into the ticket

**Comment by lowellrex** [comment]
> Did we determine this would be front end or back end or both? I remember discussing it in estimation, but it looks like that did not make it into the ticket

Definitely on the back-end. Also on the front-end if we're going for extra credit.
