### ISSUE TITLE
Add method to Organizations class to add user to an org

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12496]
Currently, in order to associate a `User` with an `Organization` we call the function `OrganizationsUser.add_user_to_organization` with user and organization instances ([like in `Organization::UsersController`](https://github.com/department-of-veterans-affairs/caseflow/blob/5453cdcfd5d9c1bf283fad51dc92160e4cd29de6/app/controllers/organizations/users_controller.rb#L18) for example). This ticket exists to move control of that operation onto the instance of the `Organization` with an instance method for adding a user. This will allow us to more directly add callbacks to organizations when users are added ([as we'd like to do for `JudgeTeam`s](https://github.com/department-of-veterans-affairs/caseflow/pull/12493#discussion_r339757021)).

## Acceptance criteria
* [ ] Create instance method `add_user` for the `Organization` class
* [ ] References to `OrganizationsUser.add_user_to_organization` have been replaced with `organization.add_user`

**Comment by pkarman** [comment]
I think the built-in associations let you do this:

```ruby
org = Organization.find_by_name_or_url('foobar')
user = User.find_by_css_id 'VACOFOOBAR'
org.users << user
```
