### ISSUE TITLE
SPIKE | Investigate best way to create desktop link for Caseflow Dispatch

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1250]
Create a link (Dispatch Icon with) that users can click on to access Caseflow Dispatch from their desktop.

Options to explore:
- A way to click a button and automatically add the link to their desktop
- A section in the help page describing how to do it.
- Having one of us go to each user and manually make the link on their desktop

# Related Issues
App Shortcut Link | Identify process for enabling and providing link to users [#1291](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1291)
App Shortcut Link | Request a BVA Intranet link for Dispatch [#1296](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1296)
App Shortcut Link | Request a VBA link for Dispatch [#1294](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1294)

**Comment by shanear** [comment]
Hmm... this is a task that has to be done on people's machines. There may be a way to automate it. I can look into that.

**Comment by lakohl** [comment]
Cool. I think this could add a lot of value.

**Comment by nikitarockz** [comment]
At my previous job we used OneClick to remotely install our apps.

**Comment by nikitarockz** [comment]
# Update
There are 3 places for a possible links:

- BVA Intranet Page
- Physical PC (Start Menu/All Programs)
- Citrix Desktops

I have identified the process for getting the **_Physical PC_** (Start Menu/All Programs) option.  It takes about 2 weeks for it to be implemented (process details - [App Shortcut Link | Identify process for enabling and providing link to users #1291](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1291#issuecomment-303523560).   

After speaking with @lakohl, it was decided to go this route. I will be submitting the request.  ([App Shortcut Link | Request a VBA link for Dispatch #1294](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1294)

@lakohl also asked for having the link put on the BVA Intranet.  I will follow up with my contact to have this implemented.

**Comment by nikitarockz** [comment]
# Update
The following links are now available on the BVA intranet. https://vaww.bva.va.gov

ID|Shortcut Name|Shortcut URL
---|---|---|
1|Caseflow Dispatch|https://appeals.cf.ds.va.gov/dispatch/establish-claim
2|Caseflow Dispatch Manager|https://appeals.cf.ds.va.gov/dispatch/establish-claim

**Comment by nikitarockz** [comment]
# Update
This request was passed to another team who specifically hands local station (397 specific) updates, since this is not an enterprise wide change.

**Comment by nikitarockz** [comment]
# Update
The following link and folders are now available to the users at station 397 (AMC).  

Start > All Programs > Local Apps > Caseflow

Here is a screen shot of what it will look like.

![dispatch shortcut link](https://cloud.githubusercontent.com/assets/23063044/26799461/c9b56c2e-4a03-11e7-8a28-fc01d1a36117.png)

**Comment by kierachell** [comment]
**PASSED**
The link is there and was clicked (afaik)
