### ISSUE TITLE
AMO bi-weekly intake numbers

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12510]
### User story

As an AMO member, I need bi-weekly numbers reflecting Intake stats.

### Acceptance criteria
- A new cron job uses the ClaimReviewAsyncStatsReporter to send CSV output to the #caseflow-vbms-intake channel, similar to how MonthlyMetricsReportJob works.
- Job should also report current number of stuck SC and HLR async jobs.

**Comment by pkarman** [comment]
Still needs:

> Job should also report current number of stuck SC and HLR async jobs.

**Comment by pkarman** [comment]
Relevant thread https://dsva.slack.com/archives/CFBLH2LR4/p1571861537093100

**Comment by msj0nes** [comment]
# Status

PI Planning Notes - Caseflow level work is complete via 'AMO metrics job' . OIT is working with BGS on anything additional that may be needed. New work will be addressed via new roadmap entry.
