### ISSUE TITLE
Motions attorney completes Deny or Dismiss motion to vacate

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12518]
### User or job story
As a motions attorney, I want the ability to close a review motion to vacate (denial or dismissal) task, so that I can generate and send a letter to the Veteran.

### Acceptance criteria
- This work is behind a feature toggle: "review_motion_to_vacate".
- Motions attorneys have the action "Mark task as complete" on their Deny or Dismiss Motions to Vacate tasks
- When the Motions attorney completes the motion to vacate, all open parent tasks are also completed
- The user gets routed to their queue with a flash alert indicating that the case has been completed
- Please include final screenshots in the issue

### Open questions
- What happens to the instructions or context the Motions attorney enters?

### Release notes
Caseflow now supports Motions Attorneys' ability to complete denied or dismissed motions to vacate.

#### Designs
![Screen Shot 2019-10-30 at 12.43.35 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/0450ff89-3d06-493a-9f90-ccc2cf5aafa2)

![Screen Shot 2019-10-30 at 12.43.44 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/d1688e41-17c7-4de8-84b1-712996961c85)

![Screen Shot 2019-10-30 at 12.43.58 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/bddb0589-7432-4dce-a1d4-ceb6a85a5f79)

**Comment by jimruggiero** [comment]
@leikkisa @geronimoramos @rutvigupta-design C/Should MTV notes go here?
![MTV_Notes](https://user-images.githubusercontent.com/52474028/67912197-8dbdc580-fb5f-11e9-9284-c1e0fdc4747c.jpg)

**Comment by jimruggiero** [comment]
@rutvigupta-design @geronimoramos Can you confirm that the instructions text box in the modal above is optional (i.e. does not require content) to Mark complete?

**Comment by rutvigupta-design** [comment]
@jimruggiero my understanding was the notes appear as **task instructions** for the judge/attorneys (i.e. under the "assigned by" next to the Actions drop-down. The notes mentioned in the image refer to notes on specific issues that the veteran is requesting, so the pattern of relating that to tasks in this case might be confusing. 

Yes, the Mark complete instructions text box should be optional.

**Comment by leikkisa** [comment]
@jimruggiero @rutvigupta-design I agree, instructions don't go on the issue, they go on the task.

In the past, these modals have resulted in a new "task", which is where the instructions would typically go.  Since this is completing a task, there is no new task to put the instructions.

I think we should either take it away, or we could append it to the instructions that are already there for the task being completed.

**Comment by rutvigupta-design** [comment]
@leikkisa I do think we should keep it just to keep enforcing the user pattern to write out a final note whenever they're taking a major action. If I'm understanding correctly, this would only show up in the task instructions when we are creating a new task but in this case, we are not - correct? 

Little confused about appending it to the existing instructions because that would be the judge's instructions.

I know we give the user a success banner (flash alert) once they have completed this action. Does this show up in the Case Timeline and/or can we append these instructions there?

**Comment by jcq** [comment]
Just to confirm, was this envisioning using the existing "Mark task complete" functionality / modal? Your copy is slightly different (e.g. "Mark task as complete" vs the default w/o "as"), but largely it mimics it. Are we OK just utilizing the existing one (with its copy), or should I hide that one and add a new one that basically does the same thing but has different copy?

And secondly, this fully completes the tree for these paths, right? No other tasks need to be opened after these are completed?

**Comment by leikkisa** [comment]
@jcq Go ahead and use the existing copy

For your second question - yes! Right now our assumption is that the motions attorney will know what to do to complete these (e.g. send a letter to the veteran), and then they'll mark as complete.  We don't need to do anything with decision documents or dispatch, because no decision issues are changing.

**Comment by rutvigupta-design** [comment]
@jcq Echoing what Sally said!

**Comment by jcq** [comment]
## Updated Workflow
![cf-12518-workflow](https://user-images.githubusercontent.com/2581274/68809741-6405a380-0621-11ea-8e8c-b0ee8f1ea53b.gif)
