### ISSUE TITLE
Ignore tasks that are not actionable when determining the assigned to location of an appeal

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12514]
[Related slack thread](https://dsva.slack.com/archives/CJL810329/p1572358195003400).

When [displaying who a case is assigned to](https://github.com/department-of-veterans-affairs/caseflow/blob/20ae9aa3ea0cb77a10b7608db2f481c5dc6aa224/app/models/legacy_appeal.rb#L732) we typically show the assignee of the most [recently assigned task](https://github.com/department-of-veterans-affairs/caseflow/blob/20ae9aa3ea0cb77a10b7608db2f481c5dc6aa224/app/models/task.rb#L140). We currently have some tasks that are used to track veterans of private attorneys (`TrackVeteranTask`s) and tasks that determine if another task is on hold (`TimedHoldTask`s). Neither of these are actionable tasks and should be ignored when determining the most recently assigned tasks. Showing these task assignees as "who is in charge of the case" is jarring for users who do not expect a private attorney to ever be assigned the case, as would be displayed for a `TrackVeteranTasks`

### AC
- [ ] `TimedHoldTask`s and `TrackVeteranTask`s are ignored when determining the `assigned_to_location`

**Comment by yoomlam** [comment]
Approach 1 is to enumerate each task type to be ignored and ignore any tasks in the enumeration when showing the task assignee. Straightforward but not robust.

Approach 2 is to mark/characterize these ignorable task types as 'ignoreForCaseAssignee'. We'll have to describe & distinguish what these characterizations mean to avoid misinterpretation. Any new tasks that should be ignored are more easily incorporated without breaking existing behaviors.

**Comment by jimruggiero** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||||||||
2 | |||||||||
3 | 
5 | 
8 | 
```

**Comment by yoomlam** [comment]
Hunter and Kat recommend Approach 2 and following the pattern used by `hide_from_task_snapshot`.

**Comment by yoomlam** [comment]
Should https://github.com/department-of-veterans-affairs/caseflow/blob/a2866f15b051296d78e3105d6eb084e0a41b6a51/app/models/appeal.rb#L694 be using `:updated_at` like https://github.com/department-of-veterans-affairs/caseflow/blob/a2866f15b051296d78e3105d6eb084e0a41b6a51/app/models/task.rb#L141?

**Comment by yoomlam** [comment]
Do we have a Ruby method or understanding of what an 'actionable' task is? Possibly `Task.actions_available?(user)`.
Do we want to assess 'actionable' task with respect to all possible users? I.e., just because the current user has no available actions doesn't mean another user doesn't have actions, hence making the task actionable by some user.

For this ticket, considering the AC, I'll define actionable task as a non-root task that is not  `TimedHoldTask` or `TrackVeteranTask`.

**Comment by yoomlam** [comment]
> Should
> 
> https://github.com/department-of-veterans-affairs/caseflow/blob/a2866f15b051296d78e3105d6eb084e0a41b6a51/app/models/appeal.rb#L694
> 
> be using `:updated_at` like
> https://github.com/department-of-veterans-affairs/caseflow/blob/a2866f15b051296d78e3105d6eb084e0a41b6a51/app/models/task.rb#L141
> 
> ?

Yes. https://dsva.slack.com/archives/CJL810329/p1573766754082900

**Comment by yoomlam** [comment]
Appeals check that tasks are `visible_in_queue_table_view`:
https://github.com/department-of-veterans-affairs/caseflow/blob/a2866f15b051296d78e3105d6eb084e0a41b6a51/app/models/appeal.rb#L83
whereas LegacyAppeals don't:
https://github.com/department-of-veterans-affairs/caseflow/blob/20ae9aa3ea0cb77a10b7608db2f481c5dc6aa224/app/models/legacy_appeal.rb#L734

Do we want both to have the same behavior? Which is the desired behavior?

**Comment by yoomlam** [comment]
> Appeals check that tasks are `visible_in_queue_table_view`:
> https://github.com/department-of-veterans-affairs/caseflow/blob/a2866f15b051296d78e3105d6eb084e0a41b6a51/app/models/appeal.rb#L83
> 
> 
> whereas LegacyAppeals don't:
> https://github.com/department-of-veterans-affairs/caseflow/blob/20ae9aa3ea0cb77a10b7608db2f481c5dc6aa224/app/models/legacy_appeal.rb#L734
> 
> Do we want both to have the same behavior? Which is the desired behavior?

Hunter says we want `visible_in_queue_table_view` for both appeal types. https://dsva.slack.com/archives/CJL810329/p1573825920099100?thread_ts=1573766754.082900&cid=CJL810329
