### ISSUE TITLE
Motions attorney get assigned Deny or Dismiss MotionToVacateTask

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12517]
### User or job story
As a judge, when I deny or dismiss a motion to vacate, I want the judge address motion to vacate task to be marked as completed, and the prior motions attorney to be assigned a Deny or DismissMotionToVacateTask. 

Note: The motions attorney's subsequent action on this task would be to complete it.

### Acceptance criteria
- This work is behind a feature toggle: "review_motion_to_vacate"
- When a judge denies or dismisses a motion to vacate, a new task assigned to the prior motions attorney is created and appears in their queue - either Deny or DismissMotionToVacate
- The new task is a child of the AbstractMotionToVacateTask
- The new task contains instructions contain:
  - "Please notify the veteran or appellant of the decision on this motion."
  - Link to signed ruling letter
  - "Additional instructions from the judge: " + judge instructions
- Note: these instructions are "draft" and may be further refined with design

### Questions
- Do we want to provide any additional instructions to the motions attorney (e.g. please send a letter to the Veteran)
  - @rutvigupta-design says the motions attorneys should know what they need to do

### Release notes
Caseflow now supports the ability for Judges to deny or dismiss motions to vacate and assign those motions back to attorneys to complete the work in Caseflow and notify Veterans accordingly.

#### Designs
[Use current design](https://www.figma.com/file/VtOG0hibbyJ6T5UcYnn5EP/Motions-to-Vacate_Phase-II_Epic-8547?node-id=0%3A1)

**Comment by jimruggiero** [comment]
Do we want to close all parent tasks for the address motion to vacate? Or keep them open until the full MTV is handled? I believe these should be closed only when the attorney completes the work (i.e. full MTV is handled), which should in turn, enable the original tasks on these issues be able to be worked as they would have been prior to an MTV task being created. 

Do we want to provide any additional instructions to the motions attorney (e.g. please send a letter to the Veteran). Yes, but I'd keep the banner instructions somewhat generic. Something like, (green banner) "Your motion to [deny/dismiss/withdraw] is complete. Please notify the veteran or appellant of your decision on this motion." @geronimoramos @rutvigupta-design Just my thoughts. I defer to you.  

Do we want the task to have an organization task as a parent? My thought here is yes. However, we need to confer with Echo to ensure that VLJs acting as judges, or DVC's overriding judge rulings are associated to organizations currently. If not, we may need to rethink the approach or defer this ticket until they do some additional work to support these scenarios using organization as a parent.

**Comment by jimruggiero** [comment]
Also need to confirm that instructions text boxes to be populated by Judges are not required to advance in the workflow(s).

**Comment by rutvigupta-design** [comment]
For instruction text boxes populated by Judges, I actually think making them required could help in encouraging judges to give attorneys more specific instructions. We learned from users that there's a spectrum of how detailed judges' instructions are, and that may leave some attorneys to "figure it out" in the dark. Thoughts @geronimoramos ?

**Comment by leikkisa** [comment]
@jimruggiero I agree, I took off marking anything as complete from this ticket and it is in the next ticket.

I like the instructions that Jim mentioned.  Note, I was talking about the task instructions though, not the banner after it is complete.  We will need to add some stuff to the instructions anyway (link to the ruling letter).

**Comment by jcq** [comment]
@leikkisa One question on this that also sort of applies to the other tasks that come after `AddressMotionToVacateTask`...
It makes sense to add logic for this stuff into the `PostDecisionMotionUpdater`, since that's where we currently create the new tasks. However, at what point do we decide that's too bloated? It might make sense to pull out some of the code for individual tasks into separate files, but I'm not sure of the proper Rails/Caseflow best practices for doing so. 

We could also just go ahead and implement the logic for this ticket in `PostDecisionMotionUpdater` and then refactor it once we get to the point that we think it's necessary...

**Comment by jcq** [comment]
@jimruggiero @leikkisa @rutvigupta-design 
Just to confirm, are we changing the instruction text just for denied/dismissed dispositions? Does the copy noted above for instructions completely replace the existing copy that we already had (see below)?

**Example:**
```
I am proceeding with a denial of all issues for vacatur.
Here's why I made my decision...

Here is the hyperlink to the signed denial document
https://va.gov/fake-link-to-file
```
(Note that the "Here's why I made my decision..." bit references instructions the judge actually entered into the textarea field)

**Comment by jcq** [comment]
After a chat w/ @rutvigupta-design, we decided to keep the instruction text as it currently is for denied/dismissed. It's possible that there will be some changes to the default instructions for grant-type dispositions, but those will be handled in a future ticket.

As a result, this ticket is likely moot/invalid, as the remaining functionality should already exist.
