### ISSUE TITLE
"Assign Existing End Product" failures in production

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1254]
Larry has been seeing some failures while assigning an existing end product.

They show up in sentry:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/118/

**Comment by kierachell** [comment]
Known issue:

- #1248 
- #1244

**Comment by kierachell** [comment]
**PASSED**

Validated in `uat` with full and partial grants

<img width="1048" alt="screen shot 2017-03-22 at 5 35 13 pm" src="https://cloud.githubusercontent.com/assets/18075411/24221850/56180a00-0f26-11e7-9d43-26b84d838d39.png">
<img width="1093" alt="screen shot 2017-03-22 at 5 37 46 pm" src="https://cloud.githubusercontent.com/assets/18075411/24221849/56176604-0f26-11e7-9b21-f3620bd76b06.png">


Thank you for a quick fix, @sharonwarner
