### ISSUE TITLE
Research - Phase 1

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#12558]
### Research - Phase 1
As a team of IDT researchers, I need to conduct research and market analysis, so that we can create a recommendation for the IDT. 

We will conduct interviews with various types of users and stakeholders, synthesize our findings, checkin with product management, and conduct a readout with stakeholders.

### Acceptance criteria
- Interview 7 attorneys
- Interview 3 judges
- Interview of 2 BVA Dispatch
- Interview 2 DVCs
- Interview 1-2 admin professionals
- Research synthesis (Mural)
- Competitive analysis
- Create deck for stakeholder readout

#### Background/context
As a checkpoint halfway to the final recommendation readout with stakeholders, we will to present our first month's findings to the Board.

#### Resources/other links
https://docs.google.com/document/d/1PnMb510CKApR4VcSzLHE5Ac0fCa0mxIk8Wykc_F5334/edit

**Comment by jimruggiero** [comment]
@chandracarney Is all work on this Epic now complete? Can this be closed?
