### ISSUE TITLE
Monthly Metric: Caseflow certifications percentage of total certifications

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12554]
This metric is required by OIT (Metric ID: 1709076050).

Metric description: Caseflow - Percentage of all cases certified with Caseflow, which assists Agency Original Jurisdiction in uploading all required documents of record to a shared electronic file repository and automatically prepares the Certification of Appeal to transfer the appeal to the Board of Veterans’ Appeals.

Metric definition: (Number of appeals transferred to the Board using Caseflow/Total number of appeals transferred to the Board (manual certifications of paper appeals and Caseflow certifications))

**Comment by alisan16** [comment]
Certification usage notebook from 2017: https://department-of-veterans-affairs.github.io/appeals-data/notebooks/intake/certification-usage.nb.html

**Comment by pkarman** [comment]
Background: https://github.com/department-of-veterans-affairs/appeals-data/blob/master/notebooks/intake/certification-usage.Rmd

**Comment by pkarman** [comment]
#13082 implemented this

documented in https://github.com/department-of-veterans-affairs/caseflow/wiki/Writing-DB-migrations

**Comment by alisan16** [comment]
Based on the comment, I think this was closed on accident. Re-opening cc @pkarman

**Comment by pkarman** [comment]
These ROs are not listed in the [list of ROs](https://github.com/department-of-veterans-affairs/appeals-data/blob/master/data/ro.csv) that the older reporting code used to identify [how VACOLS certifications were measured](https://github.com/department-of-veterans-affairs/appeals-data/blob/master/notebooks/intake/certification-usage.Rmd#L25).

```
RO61 Houston Foreign Cases
RO64 Columbia Fiduciary Hub
RO65 Indianapolis Fiduciary Hub
RO66 Lincoln Fiduciary Hub
RO67 Louisville Fiduciary Hub
RO68 Milwaukee Fiduciary Hub
RO69 Western Area Fiduciary Hub
RO70 Louisville CLCW
RO78 Unknown
RO79 St. Paul Regional Loan Center
RO97 ARC
```

Do they matter? is the list from the original code just out of date?

**Comment by pkarman** [comment]
Run in production:

```
irb(main):142:0> sept = Metrics::DateRange.new('2019-09-01', '2019-09-30')

irb(main):143:0> octo = Metrics::DateRange.new('2019-10-01', '2019-10-31')

irb(main):144:0> nov = Metrics::DateRange.new('2019-11-01', '2019-11-30')

irb(main):145:0> dec = Metrics::DateRange.new('2019-12-01', '2019-12-31')

irb(main):146:0> jan = Metrics::DateRange.new('2020-01-01', '2020-01-31')

irb(main):147:0> months = [sept, octo, nov, dec, jan]

irb(main):148:0> months.each { |range| puts "#{range.start_date} #{Metrics::CertificationUsage.new(range).call}" }

2019-09-01 {:certified_total=>2930, :certified_paperless=>2896, :certified_with_caseflow=>2758, :metric=>94.13}

2019-10-01 {:certified_total=>2903, :certified_paperless=>2866, :certified_with_caseflow=>2441, :metric=>84.09}

2019-11-01 {:certified_total=>2645, :certified_paperless=>2596, :certified_with_caseflow=>2226, :metric=>84.16}

2019-12-01 {:certified_total=>1857, :certified_paperless=>1828, :certified_with_caseflow=>1586, :metric=>85.41}

2020-01-01 {:certified_total=>1199, :certified_paperless=>1158, :certified_with_caseflow=>827, :metric=>68.97}
```

**Comment by D-L-Ware** [comment]
I see some possibilities for why those were excluded.  Those location all handle what, from the perspective of appeals, are edge cases that the Board does not get a lot of.  First, despite having and RO code, in actual business practice none of those locations are actual ROs, they serve a different business function.  Nevertheless, the can certify appeals to the Board.  However, the appeals that come out of those location are more likely to not be in VBMS or, if in VBMS, have some of what certification considers the core documents to be in a format that would not result in a correct label in VBMS, confusing Caseflow certification.  Additionally, I believe Caseflow certification was rolled out RO by RO in phases and it may be that these stations were never contacted about using it for the above reason so a decision was made to leave them out of this metric.

I think, for us, it come down to what we want to measure as a team:

* All certifications no matter what vs. Caseflow Certification certifications (then include the above RO/Stations)

* Only certifications that could potentially be in Caseflow Certification  vs, actual Caseflow Certification certifications

**Comment by pkarman** [comment]
> All certifications no matter what vs. Caseflow Certification certifications 

based on my reading of the VACOLS schema and the existing code, that's what we can do. The numbers I posted earlier all ignore the RO completely. I think the existing RO logic is a `left join` meaning the RO will be included in the summary if present, but not limited to the RO list.

**Comment by pkarman** [comment]
The original code has the concept of "eligible" certifications which seems to mean "paperless". So I am going to adjust the code to report 2 metrics: caseflow certifications as the numerator, and then all certifications and all paperless certifications as 2 different denominators.

**Comment by pkarman** [comment]
Run in production:
```
(1 .. 12).map { |m| Date.parse("2019-#{m}-01") }.map { |first_of_month| "#{first_of_month} #{Metrics::CertificationUsage.new(Metrics::DateRange.new(first_of_month, first_of_month.end_of_month)).call}" }
```

```
["2019-01-01 {:certified_total=>3801, :certified_paperless=>3683, :certified_with_caseflow=>3423, :total_metric=>90.06, :paperless_metric=>92.94}",
 "2019-02-01 {:certified_total=>3906, :certified_paperless=>3742, :certified_with_caseflow=>3508, :total_metric=>89.81, :paperless_metric=>93.75}",
 "2019-03-01 {:certified_total=>4685, :certified_paperless=>4535, :certified_with_caseflow=>4224, :total_metric=>90.16, :paperless_metric=>93.14}",
 "2019-04-01 {:certified_total=>4585, :certified_paperless=>4510, :certified_with_caseflow=>4275, :total_metric=>93.24, :paperless_metric=>94.79}",
 "2019-05-01 {:certified_total=>4052, :certified_paperless=>3967, :certified_with_caseflow=>3768, :total_metric=>92.99, :paperless_metric=>94.98}",
 "2019-06-01 {:certified_total=>3555, :certified_paperless=>3468, :certified_with_caseflow=>3269, :total_metric=>91.95, :paperless_metric=>94.26}",
 "2019-07-01 {:certified_total=>4296, :certified_paperless=>4220, :certified_with_caseflow=>3944, :total_metric=>91.81, :paperless_metric=>93.46}",
 "2019-08-01 {:certified_total=>4202, :certified_paperless=>4104, :certified_with_caseflow=>3860, :total_metric=>91.86, :paperless_metric=>94.05}",
 "2019-09-01 {:certified_total=>2930, :certified_paperless=>2896, :certified_with_caseflow=>2758, :total_metric=>94.13, :paperless_metric=>95.23}",
 "2019-10-01 {:certified_total=>2903, :certified_paperless=>2866, :certified_with_caseflow=>2441, :total_metric=>84.09, :paperless_metric=>85.17}",
 "2019-11-01 {:certified_total=>2645, :certified_paperless=>2596, :certified_with_caseflow=>2226, :total_metric=>84.16, :paperless_metric=>85.75}",
 "2019-12-01 {:certified_total=>1857, :certified_paperless=>1828, :certified_with_caseflow=>1586, :total_metric=>85.41, :paperless_metric=>86.76}"]
```

**Comment by alisan16** [comment]
> based on my reading of the VACOLS schema and the existing code, that's what we can do. The numbers I posted earlier all ignore the RO completely. I think the existing RO logic is a left join meaning the RO will be included in the summary if present, but not limited to the RO list.

Can we refine the metric to remove those ROs? Based on @D-L-Ware's comment it sounds like those ROs may not even be eligible for Caseflow Certification and we should focus on

> Only certifications that could potentially be in Caseflow Certification vs, actual Caseflow Certification certifications 

Which could mean just the paperless certifications in eligible ROs.

**Comment by pkarman** [comment]
Yes, I have ignored RO completely. The original code seemed to use the RO list only for grouping by RO for more granular reporting, not for filtering out cases based on RO. So I think we're ok to ignore them completely for the purposes of this metric.

**Comment by D-L-Ware** [comment]
Looks good to me.  My preliminary analysis of the drop off on the certification usage is the lines of business using Caseflow certification are lines of business more likely to have prepared better for AMA, i.e. they made a concerted effort to certify as many of their legacy appeals pre-AMA as possible.  As such, as the legacy inventory decreases, eventually to zero, Caseflow certification usage as a percentage of all certification will decrease because the non-Caseflow certification users will also be the slowest to work down their legacy invnetory.

**Comment by alisan16** [comment]
@D-L-Ware not urgent, but we should be clear with OIT what direction these metrics should be moving to demonstrate positive impact. In the original definition, the target was 90% (baseline was 85.7%) and the measurement condition was "over target", probably because they were focused on adoption of Caseflow Certification. Now that all eligible ROs have presumably adopted it, what we expect is the metric to go down as the legacy inventory decreases. See #12748

**Comment by D-L-Ware** [comment]
Agree.

**Comment by pkarman** [comment]
Considering this one done.
