### ISSUE TITLE
Synthesize early IDT research learnings

### ISSUE THREAD

**Issue by RyanSibley** [department-of-veterans-affairs/caseflow#12557]
As a team of researchers, to retain and make use of the information we've gathered through interviews done so far in the first round of research, we need to synthesize our findings and takeaways so they can be presented to our stakeholders and considered for our final recommendations to the board. 

### Acceptance criteria

- Complete affinity mapping in Mural for stakeholders and users to to create a list of user needs and concerns. This helps with prioritization and understanding what a path forward should be. 
-  Gather high-level takeaways and insights from teammates based on research and conversations with stakeholders, users, and SMEs.

**Comment by eric-nava** [comment]
@chandracarney are we okay closing this out? I'd be good closing it out once the findings are enshrined in GH later today
