### ISSUE TITLE
Quarterly Metric: Caseflow Dispatch % 7-day non-denial decisions

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12551]
This metric is required by OIT (Metric ID: 1709076052).

Caseflow Dispatch - Percent of non-denial decisions with an EP created within 7 days
Metric description: Caseflow facilitates the transfer of cases to the Regional Office following issuance of a Board of Veterans’ Appeals decision, with an end product (EP) created to track work. Not creating an EP increases the possibility of miscommunication and slows average processing times, delaying ratings adjustment and working of remand orders.

Metric definition: (Number EPs with date<=7 days after outcoding date/number non-denial decisions)

**Comment by pkarman** [comment]
Run in production for 2019-09-01..2019-12-31
```
irb(main):276:0> non_denials.call
=> 0.16069380733944955
```
which I am interpreting as *16%* -- does that seem right @D-L-Ware ?

**Comment by D-L-Ware** [comment]
So looking at some old DS reports that track this metric the goal was 85% but the actual metric fluctuated from close to 85% to as low as 0.5%.  So 16% is within the realm of possibility.  

If correct, it does, however, indicate to me that we are no auto creating these EP as I thought we were following my conversation with Anya.  

If we are not autocreating them this metric is almost solely dependent on VBA's appeals management office's resource allocation.

**Comment by D-L-Ware** [comment]
So dug a little deeper but Anya said that EPs are autocreated for AMA appeals.  Given the majority of appeals decided by the Board are still legacy (that presumably have to have their EPs manually created) 16% is definitely a reasonable result.

**Comment by pkarman** [comment]
I believe this new code is only reporting AMA cases (Appeals) with `BvaDispatchTask` which legacy does not use.

So this number does seem too low.

**Comment by pkarman** [comment]
> I believe this new code is only reporting AMA cases (Appeals) with BvaDispatchTask which legacy does not use.

I am wrong. `BvaDispatchTask` could be assigned either LegacyAppeal or Appeal (AMA). I will modify the code to profile both types to clarify.

**Comment by pkarman** [comment]
but I was incidentally correct:
```
BvaDispatchTask.completed.where(appeal_type: "LegacyAppeal").count
=> 0
```

**Comment by pkarman** [comment]
Found at least one bug. "non-denial decisions" should be case-insensitive because we have dispositions of both "Denied" and "denied". Re-running is now 26%. So I am looking for other bugs.

**Comment by pkarman** [comment]
I also had the date range wrong. Should be Q4 2019-10-01..2019-12-31

Now I get 27%

**Comment by pkarman** [comment]
I get 25% for Q3 (2019-07-01..2019-09-30) so I think we're good with 27% for Q4.

**Comment by pkarman** [comment]
Of note: the 27% is also true when the date range is 2 days, so I think it *is* automated. Why it is not higher then, I do not know, but I think the N-day range is not the determining factor.

**Comment by pkarman** [comment]
I believe the code is accurate and I will merge.

However, this number seems low over all so I think we should investigate why it is so low (is it a tech problem or a business problem).
