### ISSUE TITLE
Invalidate Establish Claim Tasks for Appeals which are no longer ready for Claims Establishment

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1256]
This week we witnessed a situation where:
1. An appeal was ready for claims establishment, and a Establish Claim task was created correctly for it.
2. Someone changed the appeal in VACOLS, removing the outcoding_date and decision_date, rendering that appeal no long ready for claims establishment.
3. The Establish Claim task however, was left behind, causing https://github.com/department-of-veterans-affairs/caseflow/issues/1242

We were lucky this happened to an appeal that was missing a decision document, but it could have happened to an appeal in the queue which would have caused errors and a work stoppage. We should clean up tasks that are no longer ready for claims establishment.

## Acceptance Criteria
- When an Establish Claim task for an appeal that is not ready for Claims Establisment in VACOLS exists in the queue, and a user attempts to assign it to themselves, that appeal is marked as invalid (see technical notes below), taken out of the queue, and not assigned to the user.
- If there are more tasks in the queue, validate that the next task in the queue is assigned to the user afterwards, and they are redirected to the Review Decision page as they normally would be.
- If that task was the last task in the queue, validate that the "Establish Next Claim" button is greyed out on all the pages where it shows up.
- When an Establish Claim task for an appeal that is not ready for Claims Establisment in VACOLS exists, but is missing a decision it is invalidated nightly when EstablishClaims jobs are put into the queue. It should no longer appear in the Missing Decisions page after that.

An appeal that is not ready for claims establishment is defined as either:
- having a null decision date (`BFDDEC`) or
- being currently active at BVA (`BFMPRO` is equal to  `"ACT"`) ,

## Technical Notes
When a Establish Claim task is deemed no longer ready, we should complete it and give it a status of either `expired` or a new status like `stale` or `invalidated`

**Comment by shanear** [comment]
Assigning to @joofsh and @cmgiven  for feedback

**Comment by cmgiven** [comment]
Note that outcoding date (`TICOTIME`) is not nulled by BVA dispatch pulling the case back. I'm watching to see whether it will be updated when the case that flagged this issue is re-dispatched, but my reading of what I think is the relevant part of VACOLS source code is that it is. But if `TIOCTIME` is not updated, we'd need to have a holding pen for such decisions, rather than marking them as invalid, as they wouldn't be re-identified when dispatched a second time.

I'd also note that there are two conditions that should be checked:

1. Whether it has a non-null decision date (`BFDDEC`), as you currently note.
2. Whether `BFMPRO` is not `ACT`, which would indicate that it is currently active at BVA.

**Comment by shanear** [comment]
@cmgiven is there any way we can test this in UAT VACOLS?

**Comment by cmgiven** [comment]
I'm going to just ask Jed. That'll be easiest.

**Comment by cmgiven** [comment]
@shanear: `TIOCTIME` is overwritten when it is dispatched. So yes, we need to invalidate the task.

**Comment by shanear** [comment]
Updating AC for technical reasons:

### Old AC
> - If that task was the last task in the queue, validate that the user is redirected back to the landing page afterwards.
> - When an Establish Claim task for an appeal that is not ready for Claims Establisment in VACOLS exists, but is missing a decision. When the Missing Decision page is visited, validate that that task is not visible there. It should be marked as invalid.

Now tasks are invalidated nightly, instead of when the Missing Decision page is visited, for performance reasons.

**Comment by kierachell** [comment]
So I changed TIOCTIME for a claim that had a task and upon visiting *Decision Review* page I get this:
<img width="1286" alt="screen shot 2017-04-15 at 4 12 37 pm" src="https://cloud.githubusercontent.com/assets/18075411/25066540/5db5f65e-21f6-11e7-8147-3c0d25c994f0.png">


coming from this:
https://github.com/department-of-veterans-affairs/caseflow/blob/2737247bab5440c495bf8b87115bcaa91ec67872/client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx#L168

@shanear is that expected?

**Comment by shanear** [comment]
@kierachell  This code isn't addressing the situation where a task is already assigned. It only will prevent them from being assigned or prepared.

**Comment by kierachell** [comment]
**PASSED**

```
           BFCURLOC = '30',
           BFMPRO = 'ACT',
           BFDDEC = NULL
```
I tested using above values and refreshing *Work History* page and the task was removed. So I guess that works.
