### ISSUE TITLE
Conduct competitive analysis  for phase 1 of IDT research

### ISSUE THREAD

**Issue by RyanSibley** [department-of-veterans-affairs/caseflow#12560]
As a stakeholder I need to understand the options for replacing the IDT with another software solution as well as the implications of maintaining the current IDT. 

###
- Identify potential software solutions that meet the user and stakeholder needs identified through research. 
- Clarify and surface what the Board of Veterans Appeals would need to do to create a sustainable path towards maintaining the IDT.
- Document the competitive analysis in a way that allows for comparisons to be made.

**Comment by chandracarney** [comment]
The IDT research competitive analysis and considerations document is well underway for Phase 1 of the project and is on track to be used for next week's meeting to present at the Board: https://docs.google.com/document/d/1Y060Qplv8H2zXPEupmdSSC1t7RxqB86lkzo4RBnM-e8/edit#
