### ISSUE TITLE
task_classes fails when a VSO attempts to place a task on hold

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12583]
[Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7248/events/536017/).

[`create_params` in PlaceHoldController](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/tasks/place_hold_controller.rb#L19) expects a single task, which overrides [`create_params` in TasksController](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/tasks_controller.rb#L211), which expects multiple tasks.  When the user is a VSO, we check to make sure the VSO is only attempting to [create `InformalHearingPresentationTask`s](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/tasks_controller.rb#L162). This causes a failure at `task_classes` as it expects an [array of tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/tasks_controller.rb#L182) to create.

I also believe the logic to ensure VSOs can only create `InformalHearingPresentationTask`s is incorrect, as this could skip the error if they were creating an `InformalHearingPresentationTask` and any other task type.

### AC
- [ ] `verify_task_access` disallows VSOs from creating other task types
- [ ] VSOs can place Informal Hearing Presentation tasks on hold
- [ ] VSOs can end holds for Informal Hearing Presentation tasks

**Comment by hschallhorn** [comment]
@lowellrex, was about to get started on this. Is it worthwhile? Should VSOs be able to put IHP Tasks on hold?

**Comment by lowellrex** [comment]
If we give them the option to place the task on hold then I think we should make sure it works. And since [we give them that option](https://github.com/department-of-veterans-affairs/caseflow/blob/0984143c50af430785c640867c529bdec1d51eb2/app/models/tasks/informal_hearing_presentation_task.rb#L16) I think this is worthwhile, yeah.
