### ISSUE TITLE
Document Viewer | Rearrange and show/hide toolbar controls

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1259]
The toolbar controls should reflect the most important/necessary tools needed at BVA.

**Top Toolbar**
-  Move the zoom +/- and full screen controls to top toolbar
-  No change: "Back to all documents" link (left aligned) - no change
-  Zoom -, full screen, zoom + (center aligned)
-  Document Type (right aligned) 
- The left of Document Type displays any selected category tag(s) 
- All elements should have hover: hex#3e94cf

**Bottom Toolbar**
- Current page/total pages in doc (center aligned)

New AC:
- Shorten document type name (in both toolbar and sidebar) to 25 characters and add browser default tooltip for full name.
- The Document Type in both the sidebar and top toolbar should have ellipses when it is too long to fit.
- The Back to all documents button should also have ellipses when it is too long to fit.
- The Document Types should have a tooltip with the full name when you hover.

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/24682103/feb991f8-1965-11e7-82cf-d04a99a03bc8.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)

## Acceptance Criteria
- Validate that the zoom and full screen buttons are displayed  in the top toolbar and no other icons
- Validate that all elements in top toolbar has a hover
- Validate that there is a blue download icon next to the file name. The color should be `primary`
- Validate that "Back to all documents" link navigates to the Documents List page
- Validate that the document page count is accurate and displayed on bottom toolbar
- Validate that when a user clicks on any of the category checkboxes on the side, the tag icon and color of selected checkbox shows on the right of the document type name
- Validate that the colored tabs have been removed from the bottom toolbar
- Validate that `Hide menu` link  with carrot is left-aligned in the sidebar

### Related Stories
#1261 | Ability to show/hide comments menu

**Comment by gnakm** [comment]
@abbyraskin yep! it's been edited.

**Comment by abbyraskin** [comment]
@gnakm moving this back to Triage for now until we have category placement nailed down

**Comment by gnakm** [comment]
@abbyraskin please review changes!

**Comment by mdbenjam** [comment]
@gnakm @abbyraskin Can we remove the actually hide/show menu criteria since it seems #1261 has that as well?

**Comment by mdbenjam** [comment]
And what's the gray color behind the Hide Menu button?

**Comment by abbyraskin** [comment]
> Can we remove the actually hide/show menu criteria since it seems #1261 has that as well?

yep, done.

**Comment by gnakm** [comment]
@mdbenjam hex #E4E2E0

**Comment by mdbenjam** [comment]
What should we do with the controls in full screen. Move all the way left and right or like it is here: ![screen shot 2017-04-18 at 2 36 28 pm](https://cloud.githubusercontent.com/assets/3885236/25149813/b8928f8e-244d-11e7-8205-d567410d7121.png)

**Comment by gnakm** [comment]
@mdbenjam Could we have it so that <View all documents is always 30px from the left and the document types are always 30px from the right?

**Comment by mdbenjam** [comment]
Sounds good I'll add that in #1624

**Comment by kierachell** [comment]
- Doesnt play well with long document types.
![toolong](https://cloud.githubusercontent.com/assets/18075411/25204873/981a71b4-252d-11e7-9bfe-4e94cd36dc27.gif)

- Sentence case!
<img width="107" alt="screen shot 2017-04-19 at 6 26 12 pm" src="https://cloud.githubusercontent.com/assets/18075411/25204910/bfcb50ac-252d-11e7-9672-71b2fbe7abd9.png">
<img width="365" alt="screen shot 2017-04-19 at 6 26 57 pm" src="https://cloud.githubusercontent.com/assets/18075411/25204921/cb84d904-252d-11e7-9895-1431ebfe4f84.png">

**Comment by kierachell** [comment]
- What's the final verdict on the `View all documents`? Is it `Back to all documents` or `View all documents`?

**Comment by mdbenjam** [comment]
Nice catch on the long document types. @gnakm What do you think about truncating the doc type after like 30 characters and maybe show the full thing on the sidebar? And I think it is Back to all documents. I'll fix all that.

**Comment by mdbenjam** [comment]
Updated AC:
- The Document Type in both the sidebar and top toolbar should have ellipses when it is too long to fit.
- The `Back to all documents` button should also have ellipses when it is too long to fit.

@gnakm

**Comment by gnakm** [comment]
@mdbenjam 👍 I added it to new AC at the top

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated In: Preprod
Browsers: FF and Chrome

Steps to Validate: 
See AC

Screenshots: 
<img width="978" alt="screen shot 2017-04-27 at 10 33 16 am" src="https://cloud.githubusercontent.com/assets/23038505/25488542/4d88bca6-2b35-11e7-931c-cd915316f4aa.png">
