### ISSUE TITLE
Intake | Upstream Error | Address has invalid character error

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12592]
### Description
When attempting to establish a claim, we are getting the following error:
`An error occurred while establishing the claim: Unable to establish claim: insertBenefitClaim: AddressLine1 has invalid character(s)</ns2:exception><ns2:message>Claim not established. System error with BGS.`

The veteran's address just has regular alphanumeric characters in it.

### Impacted reviews and incident report submitted
Review | Status | YourIT | Link
--- | --- | --- | ---
SC 179780 | Resolved | INC8206255 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=52be5a67db740c54587fff1e0f961995

**Comment by msj0nes** [comment]
This issue is linked to VBMS Defect #751403

**Comment by leikkisa** [comment]
Current cases of this are resolved. We expect more of these, so I'm going to keep this ticket open for now. We have learned that it is due to validation issues with either the veteran's address, or the claimant's address.

The short term fix is to have someone update the invalid address in Share or VBMS, and then re-attempt establishment.

The long term fix it to determine what the rules are so that we can prevent intake for these.

**Comment by leikkisa** [comment]
Closing this ticket because there are no active occurrences of it and validation has been added to prevent it in the future.
