### ISSUE TITLE
"Refresh page" is too inside-basebally

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#126]
On the button in `start.html.erb` we use the text `Refresh Page`, we should try some language out like `Recheck VACOLS and VBMS`.

**Comment by KHarshawat** [comment]
Text ideas...for now. Will take a look a little later:

Re Check VACOLS and VBMS
Look for updated documents
Relook for updated documents
Re-check VACOLS and VBMS
Recheck VACOLS and VBMS
Recheck for documents
Re-check for documents
Scan for new documents
Scan for document updates
Search for new documents
Search for document updates
Search for updates
Look for updates
Scan for updates

**Comment by alex** [comment]
"Scan for updated documents"? "Check for updated documents"

On Thu, Nov 5, 2015 at 10:55 AM, Kavi Harshawat <notifications@github.com>
wrote:

> Text ideas...for now. Will take a look a little later:
>
> Re Check VACOLS and VBMS
> Look for updated documents
> Relook for updated documents
> Re-check VACOLS and VBMS
> Recheck VACOLS and VBMS
> Recheck for documents
> Re-check for documents
> Scan for new documents
> Scan for document updates
> Search for new documents
> Search for document updates
> Search for updates
> Look for updates
> Scan for updates
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/126#issuecomment-154101018>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by KHarshawat** [comment]
@alex during our user interviews this didn't come up at all. In fact people seemed to understand the button quite well. I'm going to close this issue.
