### ISSUE TITLE
Multiple Legacy Issues | Use new table for legacy issue opt ins

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12615]
### User or job story
As a user, I should be able to connect multiple legacy issues to one request issue.

This step is to switch logic to use the new table that was created in #12397

### Acceptance criteria
- First check that the existing legacy issue data has been completely backfilled in the new table
- Add appropriate ActiveRecord associations (each legacy opt in will have a request issue, and a request issue can have many legacy issue optins)
- Update code that currently uses the request_issues table for vacols_id and vacols_sequence_id to use the new table
  - If a veteran chose to opt-in their issues, it should create a legacy issue opt-in record for each eligible legacy issue
- Update code to handle multiple legacy issue opt-ins
  - For example, currently if an opt-in gets rolled back, it just rolls back the one connected to the request issue. Now it should handle all opt-ins connected to the request issue
- Add vacols_id and vacols_sequence_id to RequestIssue's ignored_columns
- Update tests

### Out of scope
Removing request_issue vacols_id and vacols_sequence_id fields

### Release notes
NA - will add release note when feature is fully available

#### Designs
N/A - backend

#### Technical notes
Checking that the data is backfilled may most easily be done using counts.

**Comment by msj0nes** [comment]
This hasn't been prioritized by either stakeholder. We will add to a sprint when time allows.
