### ISSUE TITLE
Identify first Tableau report to port to denormalized schema

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12616]
One action item from the breakout session with B3 the week of 10/22 was to identify the first Tableau report we will port to a new denormalized data source.

Per @D-L-Ware we have some candidates:

> 1. Active Summary – what appears to be a logical mirror of one of the first Looker reports built by Caseflow, it shows where AMA appeals are in the pipeline at the Board.  It is slightly misnamed here as Active Summary as things like ‘Decision Dispatch’ and ‘CANCELLED’ I do not believe fit into the Board’s traditional sense of what it means for an appeal to be active.
> 2. Active Task Detail – appeal by appeal detail of any appeal with a currently open tasks.
> 3. Appeals Status Active Total – a count by lane of what appeals have open tasks.

## Acceptance criteria

* [x] Identify which Tableau report to port
* [x] Obtain the latest Tableau data store SQL used for the report
* [x] Define the ideal schema definition to support this report

**Comment by D-L-Ware** [comment]
[Tableau - Proposed Items to be Prioritized.pptx](https://github.com/department-of-veterans-affairs/caseflow/files/3814519/Tableau.-.Proposed.Items.to.be.Prioritized.pptx)

**Comment by D-L-Ware** [comment]
The above is the proposed Tableau report prioritization for the B3 team to get to production.   This can also be informative on the conversation.

**Comment by D-L-Ware** [comment]
Dustin Ware 
@pkarman do you want to have a call about which report to start with?  I proposed Active Summary
1. Both the SQL and the spreadsheet Juan sent over speak to way to transform the data;
2. It delivers user value while not being too high level;
3. This report categorizes appeals based on caseflow data so it appears there is a clear opportunity to do some transformation.

Peter agreed.
