### ISSUE TITLE
Ensure task paper trails are being saved when AMA appeals are cancelled

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12617]
[Relavent slack](https://dsva.slack.com/archives/CHX8FMP28/p1572990272137100?thread_ts=1572989139.136500&cid=CHX8FMP28).

It appears as if all changes to tasks are not creating a paper trail, specifically when AMA appeals are cancelled by removing the last request issue on the appeal.

#### To reproduce

1. Log in as BVACASPER and find an AMA appeal assigned to you
```ruby
a = Appeal.find_by(uuid: "3f62f5b2-8439-46e5-b097-4043d034d6a9")
puts a.structure_render(:id, :status, :assigned_to_id)
Appeal 60 [id, status, assigned_to_id]
└── RootTask 361, on_hold, 4
    └── JudgeDecisionReviewTask 362, on_hold, 3
        └── AttorneyTask 363, in_progress, 1
Task.find(363).versions
=> []
```
2. Remove the last issue on an AMA appeal at the attorney task (this cancels the whole appeal) and confirm this cancels the parent judge task and the grandparent root task.
```ruby
puts a.structure_render(:id, :status, :assigned_to_id)
Appeal 60 [id, status, assigned_to_id]
└── RootTask 361, cancelled, 4
    └── JudgeDecisionReviewTask 362, cancelled, 3
        └── AttorneyTask 363, cancelled, 1
Task.find(363).versions
=> [] # This should have at least one version but it does not
```

### Notes

Fixing this would allow us to be able to [find all the version records](https://github.com/department-of-veterans-affairs/caseflow/pull/12540) related to this change with the request id that caused it and quickly undo the change with
```ruby
request_id = Task.find(363).versions.last.request_id
previous_tasks = PaperTrail::Version.where(request_id: request_id)
previous_tasks.each { |previous_task_state| previous_task_state.reify.save }
```
This could also support future work to create an undo function and the batteam fields at least one of these undo requests a day

### AC
- [ ] All task changes create a version in the paper trail table

**Comment by hschallhorn** [comment]
Mildly related to #11963

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |
2 | ||||||||
3 | |||||||||
5 | 
8 | 
```

The way we cancel AMA appeals with the ActiveRecord update_all, which skips callbacks. Papertrail uses these callbacks. Do we need only some callbacks, or was this being overly defensive? Unsure, but the update_all was intentional originally.

Can we explicitly save a version in papertrail? We think so, but don't know.

Scope this ticket to this explicit bugfix, but also search for anywhere else we update without callbacks and file follow-on issues to address those, unless the fix is trivial to do here.

Estimating at a 3. Might be a 1 if this is super straightfoward to call papertrail directly.

**Comment by hschallhorn** [comment]
Where [`update_all` is called](https://github.com/department-of-veterans-affairs/caseflow/blob/4f7193226d94b01ea3ba1f2cff61998c4c172b60/app/models/task.rb#L512)

**Comment by lomky** [comment]
[Papertrail: Saving a new version manually](https://github.com/paper-trail-gem/paper_trail#saving-a-new-version-manually)

**Comment by hschallhorn** [comment]
hm. I'm getting a NoMethodError on this

**Comment by lomky** [comment]
We're on PaperTrail 8. We could look into bumping the gem, or using some work arounds others have developed [See StackOverflow](https://stackoverflow.com/questions/27804421/papertrail-manually-create-version)

**Comment by hschallhorn** [comment]
Doesn't seem to be saving the object or the changes
```ruby
tasks.each { |task| task.paper_trail.record_update(force: true, in_after_callback: false) }
tasks.map(&:versions)
=> [[#<PaperTrail::Version:0x00007f9f83348030
   id: 847,
   created_at: Thu, 05 Dec 2019 20:51:25 UTC +00:00,
   event: "update",
   item_id: 1141,
   item_type: "Task",
   object:
    "---\nid: 1141\nappeal_id: 253\nappeal_type: Appeal\nassigned_at: &1 2019-12-05 20:51:25.235971000 Z\nassigned_by_id: 1\nassigned_to_id: 5\nassigned_to_type: Organization\nclosed_at: \ncreated_at: *1\ninstructions:\n- skd;fb\non_hold_duration: \nparent_id: 756\nplaced_on_hold_at: \nstarted_at: \nstatus: assigned\ntype: IhpColocatedTask\nupdated_at: *1\n",
   object_changes:
    "---\nplaced_on_hold_at:\n- \n- 2019-12-05 20:51:25.319857000 Z\nstatus:\n- assigned\n- on_hold\nupdated_at:\n- 2019-12-05 20:51:25.235971000 Z\n- 2019-12-05 20:51:25.320025000 Z\n",
   request_id: "585bdb20-3d73-42c7-9b61-729b399677d6",
   whodunnit: "1">,
  #<PaperTrail::Version:0x00007f9f836565b0
   id: 849,
   created_at: Thu, 05 Dec 2019 20:51:25 UTC +00:00,
   event: "update",
   item_id: 1141,
   item_type: "Task",
   object:
    "---\nid: \nappeal_id: \nappeal_type: \nassigned_at: \nassigned_by_id: \nassigned_to_id: \nassigned_to_type: \nclosed_at: \ncreated_at: \ninstructions: \non_hold_duration: \nparent_id: \nplaced_on_hold_at: \nstarted_at: \nstatus: \ntype: \nupdated_at: \n",
   object_changes: "--- {}\n",
   request_id: nil,
   whodunnit: nil>],
 [#<PaperTrail::Version:0x00007f9f835ed920
   id: 850,
   created_at: Thu, 05 Dec 2019 20:51:25 UTC +00:00,
   event: "update",
   item_id: 1142,
   item_type: "Task",
   object:
    "---\nid: \nappeal_id: \nappeal_type: \nassigned_at: \nassigned_by_id: \nassigned_to_id: \nassigned_to_type: \nclosed_at: \ncreated_at: \ninstructions: \non_hold_duration: \nparent_id: \nplaced_on_hold_at: \nstarted_at: \nstatus: \ntype: \nupdated_at: \n",
   object_changes: "--- {}\n",
   request_id: nil,
   whodunnit: nil>]]
```

**Comment by lomky** [comment]
@hschallhorn Yeah, I'm pretty disappointed with this functionality! digging back in to look for something to actually capture the state change.

**Comment by lomky** [comment]
It looks like the new function will save the `object` field, but not the `object_changes` field, which is a bit of a bummer for ease of analysis purposes. But PaperTrail's functionality does not rely on the `object_changes` field.
