### ISSUE TITLE
Document Viewer | Ability to show/hide comments menu

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1261]
**Story**
When reviewing documents, I want to hide the comments menu, so I can focus on reading the document when I don't need to add a comment.

**Description**
If a user clicks on the `Hide Menu` button, the righthand comments pane hides, and the document is centered on the page. If a user clicks the `Open Menu` button, the comments pane displays and the document adjusts left.

## Acceptance Criteria
- Validate that menu is open by default (`Hide Menu` link displayed)
- Validate that both Hide Menu and Open menu text links are bold
- Validate that Hide Menu link is in a gray, that is the same height as the toolbar in document viewer
- Validate that clicking `Hide Menu` link hides the entire comments pane and switches text link to "Open Menu"
- Validate that only Hide menu text link has a chevron on the right 
- Validate that clicking `Open Menu` link displays the comments pane and switches the text link to `Hide Menu`
- Validate that document is centered on the page after clicking `Hide Menu` link
- Validate that document is adjusted left on the page after clicking `Open Menu` link

## Mock up

![image](https://cloud.githubusercontent.com/assets/13420618/24815495/4606eabc-1ba3-11e7-8a7c-251adda38728.png)

![image](https://cloud.githubusercontent.com/assets/13420618/24815504/4d92ee52-1ba3-11e7-816c-25100715c8fe.png)

## Note
Veteran ID was taken out of header. See [Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)
for updated visual

**Comment by abbyraskin** [comment]
cc: @gnakm

**Comment by NickHeiner** [comment]
> Validate that the placement of the button doesn't change when it's open and hidden

What does "the button" refer to in this AC?

**Comment by gnakm** [comment]
@NickHeiner Button is really a text link 
Hide Menu > and Open Menu

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Click the Hide Menu > button
3. Once the menu disappears, open the menu back up. 
4. Validate behavior against AC

Screenshots: 
![readercommentmenu](https://cloud.githubusercontent.com/assets/23038505/25489235/31bffe10-2b37-11e7-8ac4-04e073c3cb3d.gif)
