### ISSUE TITLE
Port over stub versions of `already_certified`, `not_ready`, and `mismatched_documents` with fake data to React components

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1263]
In the certification controller, we currently only render the case when the appeal can be certified in Certification v2. See the `new` method:

```
   # status == :started means the appeal is ready to certify
   if verify_certification_v2_access && status == :started 
      render "v2", layout: "application"
      return
    end
   
  # but we should also render these other cases in certification v2 if certification v2 is enabled
    case status
    when :already_certified    then render "already_certified"
    when :data_missing         then render "not_ready", status: 409
    when :mismatched_documents then render "mismatched_documents"
    end
```

We should port over the other cases to React components and make sure they can be rendered using fake data.

In `Certification.jsx`, the `EntryPointRedirect` currently redirects to `/certifications/${match.params.vacols_id}/check_documents`. 

We could possibly add new routes to the router for all the new cases, then temporarily change `EntryPointRedirect` to redirect to those new routes just to test. Or do it another way!

**Comment by amprokop** [comment]
See the components in `client/app/certification` for inspiration, and use the components in `client/app/components` to build the new stuff when you can. For now, don't worry about behavior or data. Just make the new pages look identical to the old ones.

**Comment by kierachell** [comment]
It seems like either user authorization has changed or:
```
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Ple
ase note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action afterredir
ecting, you need to do something like "redirect_to(...) and return".):
  app/controllers/certifications_controller.rb:18:in `new'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

1. I am able to see `123C` page _only_ if I enable both Certification functions: Certification and Certification v2

1. I am **Unauthorized** to see any new pages using the Certification v2 function

1. If I enable both Certification (v1 and v2) functions - I receive the error logged above for pages other than `123C1

**Comment by amprokop** [comment]
thanks @kierachell — @nemodjuric this is a bug related to the removal of a return from the certification controller. let's fix it when we can.

**Comment by kierachell** [comment]
**PASSED**
even works on `uat`!!!
<img width="1043" alt="screen shot 2017-04-03 at 2 55 07 pm" src="https://cloud.githubusercontent.com/assets/18075411/24625712/dd692d08-187d-11e7-8c49-6bd0d37155ff.png">
![Uploading Screen Shot 2017-04-03 at 2.57.46 PM.png…]()
