### ISSUE TITLE
ETL Infrastructure for Data Warehouse

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12643]
## Background/context

Caseflow must provide its data to the BVA Data Warehouse (live on demand storage) and Data Lake (persistent long term snapshot storage).

*NOTE*:  The Data Lake work is *not* reflected in this epic; here for context only.

### Data Warehouse

Currently, the Caseflow PostgreSQL db is mirrored once a day, overnight, to a Redshift instance. The Redshift instance is used by Tableau to provide metrics/reporting to BVA. Zero transformation is attempted on the schema, so it is a Extract/Load process (as opposed to Extract/Transform/Load (ETL)).

### Data Lake

The BVA data lake is an S3 bucket where Caseflow needs to deposit CSV files of raw db data.

### Data Warehouse

In its highly normalized structure in Redshift, the schema is slow to query. It is optimized for data integrity, not performance. As a result, Tableau reports are slow to run.

Caseflow requires a true ETL process, which means injecting a layer of transformation logic into the data export flow.

The new Data Warehouse should provide optimal performance for Tableau reporting and denormalized data for other reporting needs.

### Data Lake

Raw db deposits should reflect point-in-time snapshots of Caseflow production data, with enough metadata to support exploration and discovery. The Data Lake work is *not* reflected in this epic; here for context only. See [Data Lake](https://github.com/department-of-veterans-affairs/caseflow/issues/12697) for more details.

## Stakeholders

* BVA
* B3 Tableau team

**Comment by pkarman** [comment]
Rough outline for needed GH issues

* Rails `etl` database provisioning/config
* RDS provisioning
* Rails `etl` models
* Service class to create/update etl rows
* Cron job to call etl service class
* CSV exporter
* Service class to use CSV exporter
* Cron job to call csv service class

**Comment by alisan16** [comment]
Is there a reason why we need a separate ETL for the Data Lake? I was under the assumption that initially, we would just extend the existing Redshift mirroring process to also export the CSVs/load into the Data Lake.

Taking a stab at the open questions:

- What data goes into the data lake?
  Based on the early conversations and timeline (targeting Feb 2020), initially we should start with the existing tables in Redshift. Are there other options?
- How frequently should data snapshots go into the Data Lake?
  Daily sounds reasonable to me, though this should be adjustable based on the actual needs and usage
- How frequently should Data Warehouse be updated?
  What time granularity is used currently for Tableau reports? What is helpful for Board employees?

**Comment by pkarman** [comment]
@alisan16 good questions. I'm going to scope this Epic down to just the Data Warehouse and address the Data Lake as a different set of work.

**Comment by D-L-Ware** [comment]
My thoughts on open questions
* I assume the tables in Redshift but leave it to engineers to articulate a better alternative is there is one.
* I think it makes sense to start with daily for both, however, the Board, long term, will likely want to support some reports being able to be updated more frequently.  Nevertheless, given how much they just want reporting I believe we can get away with daily for a while.
