### ISSUE TITLE
Documents List | Remove "Filename" from table and add "Document Type" link

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1264]
Remove "Filename" from Documents List page, and make "Document Type" a link that navigates to the individual document on click.

## Acceptance Criteria
- Validate that clicking on any "Document Type" link from the Documents List page navigates the user to the first page of the clicked document (mimics current behavior of filename link)

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24181594/3cf55dc8-0e92-11e7-982e-c3485b0f2137.png)

## Notes
- There intentionally aren't any specific measurements for the distance between columns because we're still user testing and we don't know if we may or may not add another column as well. 

cc: @gnakm

**Comment by kierachell** [comment]
**PASSED**
validated on `uat`
![documenttypeview](https://cloud.githubusercontent.com/assets/18075411/24572620/2ca7c358-1648-11e7-931e-ae7cdd9e6abf.gif)
