### ISSUE TITLE
Mail tasks leave Root Task on hold

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12644]
As discovered in #12238 and discussed in https://dsva.slack.com/archives/CJL810329/p1573140116295400 in some cases we appear to be opening Mail Tasks post-dispatch and leaving the Root Task open in `on_hold` status indefinitely. We should fix that.

## AC

- [ ] When all tasks are closed on an Appeal, make sure the Root Task also closes.
- [x] Clean up (close) existing Root Task records that should not be `on_hold`

**Comment by lowellrex** [comment]
As of Tuesday this week (and this PR: https://github.com/department-of-veterans-affairs/caseflow/pull/12576), opening a `MailTask` on a closed `RootTask` no longer changes the status of that `RootTask`.

**Comment by lomky** [comment]
Making it so the last task other than root task closing _also_ closes the root task has some difficulty.

If we close the root task right now it implies the appeal is dispatched. 
If we cancel the root task it implies the appeal was withdrawn.

Until we un-link the status of the appeal from the status of the root task, we are hesitant to make any other task status changes affect the state of the root task.

**Comment by lomky** [comment]
Closing this in favor of a larger conversation about decoupling the appeal state & root task state.

**Comment by pkarman** [comment]
see #12713
