### ISSUE TITLE
Display Veteran's state of residence on Schedule Veterans screen

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12648]
### User story
As a Board Hearing Coordinator, I want to know when a Veteran is being scheduled to a hearing location that's outside the state (or territory) in which they currently reside, so that I can notify all relevant parties and anticipate issues with representatives who will not participate in out-of-state hearings.

### Background / context
After the implementation of geomatching Veterans to their closest hearing location, even if that location is across state lines, there have been problems with (1) some representative organizations having little to no situational awareness that their Veterans have been geomatched across state lines (even letters sent 60 days out are not reaching some organizations collocated at regional offices); and (2) some representative organizations will not represent Veterans across state lines.

Displaying information about the Veteran's current state of residence and their power of attorney (POA) on the Schedule Veterans screen will allow Hearing Coordinators to (1) quickly identify those Veterans who have been scheduled across state lines; (2) ensure the representative organizations for those Veterans are notified; and (3) for those representatives who can’t or won’t cross state borders or won’t be able to do a multipoint Video hearing, send those Veterans to their state of residence for scheduling.

A related ticket (#12927) addresses the problem of representative organizations and regional office Coordinators not having visibility into out-of-state Veterans on their dockets.

### Design (screenshot)
![Caseflow_ScheduleVeteransTable_1440px_withVeteranStateOfResidence_withDocketNumber.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/d387b448-662f-4ab2-a181-1ef9bf4c63a6)

### Acceptance criteria
- [ ] The name of the US state or territory in which the Veteran currently lives is displayed in the Schedule Veterans table under the column heading 'Veteran State of Residence'

### Technical Considerations
A note from @pkarman on a related ticket (#12927)
> tech note: we don't currently cache state from BGS in our db, so unless we are already making a BGS call for this endpoint, this will either (a) have a performance impact or (b) require caching that value in our db.

**Comment by pshahVA** [comment]
@nicholer , I've begun to create this ticket so we can start to formulate our thoughts and begin to think of a design and if this is the correct way to solve this problem.

**Comment by nicholer** [comment]
In a meeting with the Hearings Branch, they suggested that Docket Number is not an important column on the Schedule Veterans screen (the list is already sorted in docket order). Perhaps removing the Docket Number column can create space for an original Regional Office column.

**Comment by nicholer** [comment]
Next steps from 12/10/19 internal sync:
- Determine whether this problem affects only Legacy cases or both AMA and Legacy cases.
  - "Original Regional Office" is not a piece of data we have for AMA cases because they're established differently from Legacy cases
- Confirm what the most important pieces of information are: knowing the Original RO name vs knowing that the original RO state and POA organization are not the same state as the Suggested Hearing Location.

**Comment by pshahVA** [comment]
@nicholer, I will close this since

**Comment by pshahVA** [comment]
@nicholer, I was reviewing this and it seems that I had incorrectly changed the title.  This is on the docket after it is scheduled which I still think is a relevant task.

**Comment by ferristseng** [comment]
@nicholer Would it be fine to use the state abbreviation in the new column? Most, if not all, of the veteran's addresses have state stored as the abbreviated value. We could create a mapping from the abbreviated value to, but just wondering if that's necessary.

**Comment by nicholer** [comment]
@ferristseng Abbreviations are fine!

**Comment by chandracarney** [comment]
We'll pick this work up after the pagination work has been deployed.
