### ISSUE TITLE
Allow Hearing Branch to change docket without cancelling or postponing

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12653]
## User story
As a hearings branch user I need to correct a docket without having to mark the appeal as cancelled, postponed, or withdrawn.

## Background/context
When mistakes are made while scheduling hearings, there is no way to undo a mistake without canceling, postponing, or withdrawing a hearing.
- A cancelation, postponement, or withdraw are recorded in the disposition, even though it is really a clerical error. Users might make notes "scheduled in error."
- If it's the first time a Veteran has postponed their hearing, the hearing can be automatically rescheduled, they don't need a ruling. But If Coordinator postpones due to a scheduling error, that creates burden on the Hearing Coordinators to track if the Veteran is able to reschedule automatically.
- False reporting metrics are being created: high numbers of postponed/cancelled hearings appear even though they are clerical errors.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [hearings_edit]
- [ ] This feature should be accessible to the following user groups: TBD
- [ ] Include screenshot(s) in the Github issue if there are front-end changes TBD

## Release notes
New type of action can be made on a scheduled hearing that doesn't require canceling, postponing, or withdrawing a hearing.

### Technical notes
Create new action that cancels ScheduledHearingTask and doesn't update VACOLS

### Resources/other links

This feels related to #12168 (Research: "Withdraw hearing" -> "Cancel hearing request" label change)

### Open questions
- Do we need to track the "undo/remove/revert" that Hearing Coordinators perform?
  - It will be tracked, but the new type wouldn't perform the VACOLS action(s). There would be a record.

**Comment by pshahVA** [comment]
@ferristseng can you please update this with the database fields to look for?

**Comment by jimruggiero** [comment]
Moving to Define until baseline requirements are complete for Design and/or ENG.

**Comment by lund5000** [comment]
Completed in https://vajira.max.gov/browse/CASEFLOW-132
