### ISSUE TITLE
FNOD flash similar to the Paper Case flash for hearings

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12651]
## User or job story
User story: The hearings branch needs to be made aware when a Veteran is deceased when scheduling or if one that is already scheduled for a hearing is deceased. FNOD=Final Notice of Death

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

**Comment by pshahVA** [comment]
@nicholer, this will need research.

**Comment by D-L-Ware** [comment]
Note, this functionality likely overlaps with functionality that will be need in Queue as more than just the hearing branch needs to know when a final notice of death is logged for a Veteran.

**Comment by jimruggiero** [comment]
Moving to Define until baseline requirements are documented in the ticket for both Design and ENG.

**Comment by pkarman** [comment]
See #13213 and https://github.com/department-of-veterans-affairs/dsva-vacols/issues/100

**Comment by chandracarney** [comment]
This will be resolved by #13699.
