### ISSUE TITLE
Comments | Store user info

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1265]
Since we would like to provide access control to comments down the line, we should start recording which user owns which comments.
AC
- When a user adds a comment, that user's id should be stored with the comment in our DB.

**Comment by abbyraskin** [comment]
@mdbenjam please elaborate :)

**Comment by kierachell** [comment]
**PASSED**
do I get brownie points for validation backend with a GIF!?
![annotationuserinfo](https://cloud.githubusercontent.com/assets/18075411/25392167/f1b4d08a-29a5-11e7-80da-e321ee4a1b3d.gif)
