### ISSUE TITLE
Track Letter sent to Veteran

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12655]
## User or job story
User story: As a Hearings Branch coordinator, I need to track that I sent a letter in Caseflow.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Other notes
Perhaps the initial task would be to provide a way for the Veteran to mark that a letter was sent, rather then trying to generate this letter in Caseflow.

**Comment by pshahVA** [comment]
@nicholer

**Comment by jimruggiero** [comment]
Moving to Define until baseline requirements are complete for Design and/or ENG.

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-1651
