### ISSUE TITLE
Hearings branch case movement

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12654]
This is a placeholder ticket to write down the following request from the hearing branch.  This ticket needs a lot of research and design prior to proceeding.  
> Coordinators need the ability to send and receive cases to other administrative professionals  within the Board
> Enhance tracking and routing of cases that should not be scheduled or that need minor adjustments to schedule	
> Currently this is done through VACOLS and e-mail
> This functionality will increase speed, accuracy and accountability
> One touch cases must have a conduit to be immediately actioned

## User or job story
User story: As a [user], I need [x], so that [y]
Job story: When a [user] does [x], they need [y], so that [z]

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

**Comment by pshahVA** [comment]
@nicholer

**Comment by jimruggiero** [comment]
Moving to Define until baseline requirements are complete for Design and/or ENG.

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-1652
