### ISSUE TITLE
Data-Driven Documentation of Task Trees

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12666]
## Description
Generate documentation of valid appeal states and state transitions based on actual data. Not only will the documentation be useful for onboarding, it will expedite diagnosis and hence remediation of user problems.

Expands https://github.com/department-of-veterans-affairs/caseflow/wiki/Tasks documentation, and validates and exemplifies LP's [Task slide deck](https://docs.google.com/presentation/d/1Cc84GH7giWHTNxUe3zixH7O-QT77STlptYfud9X8P1Y)

## Background/context/resources
See bigger picture in #12645.

## Technical notes
Most of the steps below can be and should be automated.
1. For each valid appeal in the DB, list all tasks in the order they were created.
2. Use this to enumerate possible state transitions, where a transition represents a task being added to the tree. The state transitions can be represented as edges in a network/graph.
3. For each node in the graph, create a web page (e.g., `HearingTask_added.md`). For each state transition, create a web link to between pages. Generate [PlantUML](http://www.plantuml.com/plantuml) diagrams from an example appeal (without PII info), similar to how `structure_render` works. 
4. Document additional information for each web page, such as referencing other documentation or Slack threads.

## Result
Set of web pages, where each page roughly represents an appeal's state and contains links to next possible appeal states. Useful for onboarding and Bat-Teaming.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | |||||||||||
5 | |||||||
8 | 
```

Parallel to #12665.

How many state transitions are there? Each new task creation, possibly also status transitions? Estimate 15-30 state transitions.

Estimating at a 3. Might be a 5 based on uncertainty on how to do step 3. Step 3 could be accomplished by translate the JSON(?) structure to a PlantUML format. 

Maybe useful if structure render could be upgraded or copiedto also output a machine readable format?

**Comment by yoomlam** [comment]
Used something like the following to get appeal data in json format into a file.
```ruby
# suppress output to console
old_logger = ActiveRecord::Base.logger
ActiveRecord::Base.logger = nil

f=File.new('appeals.json', 'w')
Appeal.offset(30460).limit(500).each do |a|
  f << "{ \"appeal_id\":"+a.id&.to_s+", \"docket_type\":\""+a.docket_type&.to_s+"\", \"updated_at\":\""+a.updated_at&.to_s+"\", \"tasks\":"
  f << a.tasks.order(:created_at).to_json( {only: [:type, :assigned_to_type, :status, :id, :parent_id, :created_at, :updated_at]} )
  f << "}\n"
end; nil
f.close
```

**Comment by yoomlam** [comment]
Ran into some issue for appeal retrieved with `Appeal.offset(30459).limit(1)`.
Appeal id 42788 has docket_type=nil.

**Comment by yoomlam** [comment]
30866 total appeals - 1 appeal with nil docket_type - 1 appeal that borked json parsing = 30864 appeals for use in generating documentation.

**Comment by yoomlam** [comment]
Install Conda
https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html
https://docs.conda.io/en/latest/miniconda.html

Initialize project (environment) from scratch
```
conda create --name ttstates
conda env list
vim environment.yml
conda env update --file environment.yml
conda activate ttstates
```

Initialize project from environment.yml
```
conda create --file environment.yml
conda activate ttstates
```

Install JupyterLab using Conda
`conda install -c conda-forge jupyterlab`

Run JupyterLab
`jupyter lab`

**Comment by yoomlam** [comment]
Useful for rendering `md` files locally: https://github.com/joeyespo/grip
