### ISSUE TITLE
UI Bug — "Switch Views" Misaligned when Alert is Present

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12662]
## Description
The "Switch views" dropdown on Queue page is positioned absolutely within its container, placing it in the upper right. While this looks OK in the default state of that page, things get weird when an alert (success, etc) is present (see screeenshot)

## Acceptance criteria
- [ ] Position of "Switch views" dropdown isn't wonky when alert is present (i.e. retains its default state position when banners appear)

### Screenshot of bug
<img width="992" alt="Screen Shot 2019-11-07 at 10 10 48" src="https://user-images.githubusercontent.com/2581274/68515764-dd268480-0236-11ea-8f9a-503919ed6788.png">

**Comment by jimruggiero** [comment]
@jcq Would this be Foxtrot or Echo work?

**Comment by jcq** [comment]
@jimruggiero I labeled it as Foxtrot simply so it didn't get lost. I'd be happy for it to go wherever you think is best.

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```
Could be a one because it could be a one or two line change. Blows up to a two because it may take time to find those two lines. Lotta monkey-ing.
