### ISSUE TITLE
Do not send VBMS 500 errors to Pager Duty

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1267]
We currently get paged whenever VBMS returns a 500. Now that we log these errors in Sentry, we should not be getting paged on them.

**Comment by aroltsch** [comment]
@mdbenjam We get paged when there are two 500 errors within 2 minutes.

**Comment by nickheiner-usds** [comment]
I feel like we've done this, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
