### ISSUE TITLE
Migrate Looker Alert - Pending Decision Documents not uploaded to VBMS

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12686]
This alert shows up Appeals with Pending Decisions not yet uploaded to VBMS.

We determine this in Looker now by finding Decision Documents with `nil` Processed Date and Submitted Date of 2 or more days ago.

Possibly helpful references of other reports we've migrated:
example SQL: #12065
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/data_integrity_checks_job.rb

**Comment by pkarman** [comment]
existing SQL https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Engineering/looker-archive/looks_sqls/Alert%20-%20Pending%20Decision%20Documents%20not%20uploaded%20to%20VBMS.sql
