### ISSUE TITLE
Documents List | Comments: expand/collapse view

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1268]
**Story**
As a user, I want to expand or collapse individual comments so I can read my comments from the Documents List page.

**Description**
A document with one or more comments has a comments count link that expands or collapses on click.

Each comment has an associated:
- Page number 
- "Jump to section" link
- Each comment is right aligned comment header
- Each comment height depends on length of message.

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24778007/4387145e-1af6-11e7-8737-1522694f51e1.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

## Acceptance Criteria
- [x] Validate the number of comments displayed matches the number of comments saved to the individual document
- [x] Verify that max width of comment box is 625px/ 80 characters
- [x] Validate the comments link expands and collapses view to display or hide comment(s); chevron faces upward when expanded, and downward when collapsed
- [x] Validate "Jump to Section" link navigates to doc page containing comment, with comment in selected state
- [ ] All comment boxes should be padded 15px and each box should be 15px away

## Related Stories
#1283
#1431

**Comment by mdbenjam** [comment]
@gnakm What's the max width of these comments?

**Comment by gnakm** [comment]
@mdbenjam max width is 625px. 
This issue is related to: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/158

**Comment by mdbenjam** [comment]
@gnakm @abbyraskin This ticket is already really large and fixing the table header isn't trivial. I'm making  new ticket for it.

**Comment by abbyraskin** [comment]
@mdbenjam there's a ticket for that here #1471

**Comment by abbyraskin** [comment]
I'll remove that piece from the AC so it passes

**Comment by NickHeiner** [comment]
> Validate that all issue tags are visible under issue tag column

Why is this AC on this ticket? It seems unrelated.

**Comment by abbyraskin** [comment]
@NickHeiner it's suggesting the expanded comments view does not include a "see more" link if the issue tags exceed the available space -- instead, all issue tags are shown in the UI, as if the "see more" link had been clicked at the same time as the comments expand link.

this was not super clear in the AC -- we can create a new issue if it wasn't implemented this way.

**Comment by NickHeiner** [comment]
Ok – are there mockups for what you're describing? I want to be sure that we're on the same page. 

I think perhaps this could be a separate issue – what do you think @mdbenjam?

**Comment by abbyraskin** [comment]
#1438 describes the "show more" link, but I'm not seeing a clickthrough describing this exact scenario. I can put one together, just need @gnakm's mocks (when she's feeling better!)

**Comment by gnakm** [comment]
Dropping the mockup here but let me know where is the best place to put it. 
The max height of a row should be 110px max (this should fit about 3 rows of issue tags).
The max width of the issue tags column should be 225px (see #1538)
- When the issue tags cannot fit any more issues within those parameters, there should be a `See more...` (takes up 12 characters) at the end of the 3rd row. 
- When user clicks the link, the row should expand to show ALL details including comments if that document type has saved comments. 

![image](https://cloud.githubusercontent.com/assets/13420618/25142827/5126cfac-2436-11e7-9c33-24c475a2dc14.png)

![image](https://cloud.githubusercontent.com/assets/13420618/25143077/1dcd18ae-2437-11e7-8ee4-d44e6f92d0ec.png)

**Comment by kierachell** [comment]
@gnakm @abbyraskin Still no issue tags implemented. Should I wait for them to exist before validating?

**Comment by kierachell** [comment]
- One picky thing is that the expanded comment boxes in the List View seem to shift based on number of digits in the page #
![comments](https://cloud.githubusercontent.com/assets/18075411/25206039/b3dcf600-2533-11e7-88d0-6b666da1ae9d.gif)

- some comments disappear sporadically, but I think you know that.


Padding looks good.
<img width="878" alt="screen shot 2017-04-19 at 7 02 32 pm" src="https://cloud.githubusercontent.com/assets/18075411/25206063/d460ff52-2533-11e7-8a6a-8317e8cf165f.png">
<img width="859" alt="screen shot 2017-04-19 at 7 11 18 pm" src="https://cloud.githubusercontent.com/assets/18075411/25206115/066dd830-2534-11e7-846d-13e2dd7abfef.png">

**Comment by astewarttistatech** [comment]
@mdbenjam I believe this failed again. Issue tags are not being taken from the pdf viewer on to the expanded view on the documents list page. 

Also there's a couple of bugs that sprouted from this: Once on the document list view, if you expand the view for one of the documents, all other buttons like it, are disabled. (In the licecap, if the cursor was hover for more than a second, I was trying to click a non responsive button). 

Current view: 
![readerexpandview](https://cloud.githubusercontent.com/assets/23038505/25530536/98d52afe-2bf4-11e7-8988-68190a0e6ceb.gif)

**Comment by astewarttistatech** [comment]
@abbyraskin for this ticket, should the 'Expand All' button work?

**Comment by abbyraskin** [comment]
@astewarttistatech no

**Comment by abbyraskin** [comment]
@astewarttistatech no, it's tracked here https://github.com/department-of-veterans-affairs/caseflow/issues/1491

**Comment by mdbenjam** [comment]
@astewarttistatech sorry I didn't see the issue tag AC. Teja is already working on that in #1491. I'm going to move the AC there.

**Comment by astewarttistatech** [comment]
Due to the change in AC, this ticket has **PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader and expand the section in documents that have comments, issue tags, etc. 
2. Validate the behavior based on the AC above. 

Screenshots: 
See above.
