### ISSUE TITLE
Inactive JudgeTeams

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12680]
Right now there are ~25 JudgeTeams with no members. We should implement a way to show these teams are inactive, and when querying JudgeTeams in the app, only request active teams.

# AC
 - [x] The codebase recognizes Inactive JudgeTeams
 - [x] Code requesting lists of JudgeTeams only receives active teams
 - [ ] Existing empty JudgeTeams in prod are fixed
 - [x] File follow on ticket to hook up Inactivation of JudgeTeams linked to Judge inactivation.

**Comment by lomky** [comment]
Fell out from #12421, see output from the run [on slack](https://dsva.slack.com/archives/CJL810329/p1573574528009800)

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||||||||||||
3 | ||||
5 | 
8 | 
```

What's the downside to keeping these? Nothing other than cruft. Maybe we want to keep this, as we just never wanna delete anything. Maybe we do an inactive flag instead.Valuable to mark these different somehow. 

Reworking this ticket to be discovery & implementation of marking JudgeTeams that are currently empty as inactive and updating places that pull JudgeTeams to only pull active JudgeTeams.

Forking off the work to handle inactiving current active JudgeTeams to another ticket.

Default scopes on the Org model could make this really easy.

Estimating at a 2. Might be a 3 because gut feeling, general unfamiliarity.

**Comment by hschallhorn** [comment]
#11810 for reference on adding active status to user

**Comment by kevmo** [comment]
There are 4 teams with 1 member, 25 with 0. Going to mark only those with 0 as `inactive`.

**Comment by hschallhorn** [comment]
@kevmo What's left to do on this ticket?

**Comment by hschallhorn** [comment]
Closing! https://dsva.slack.com/archives/CJL810329/p1587499066010100
