### ISSUE TITLE
Look at jobs page architecture

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12683]
## Description
The jobs page fetches all jobs at `/jobs` which seems to be an alias for `/asyncable_jobs`
specific job class indexes are found at `/asyncable_jobs/:JobClassName/jobs`,
and a specific job "show" at `/asyncable_jobs/:JobClassName/jobs/:id`

These are all handled through the asyncable jobs controller.  This is a discussion/investigation ticket to see if we should consider following a different architecture.

The different job classes are actually different resources, but share some common job-related functionality through the asyncable concern.

## Background/context/resources
Code climate note about current structure:
https://codeclimate.com/github/department-of-veterans-affairs/caseflow/pull/12660#

## Technical notes
I think it is useful to keep the job class name in the URL when looking at a specific job.

**Comment by pkarman** [comment]
Splitting into 2 separate controllers with a controller concern for shared code is fine too.

**Comment by leikkisa** [comment]
Closing this ticket since it hasn't been an issue and it looks like a tech improvement ticket kicked off by early code climate days.
