### ISSUE TITLE
Use asyncable concern for virtual hearings

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12685]
## Background/context/resources

Virtual hearings reaches out to external job to 
1.) Send emails
2.) Connect the Virtual hearings solution (pexip)
The caseflow team has developed   [asyncable concern](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/asyncable.rb) to allow external dependencies that are not reliable to be retried over an extended period of time.  Investigate using them in virtual hearings.

## Technical notes

Related to #12337

**Comment by pshahVA** [comment]
@ferristseng @lomaxap I created a stub tech ticket, please modify as needed.

**Comment by ferristseng** [comment]
Looking into how we can use the `AsyncableConcern`
