### ISSUE TITLE
Refactor | Replace sorted list of documents with sorted list of ids

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1269]
We currently have two lists of documents in DecisionReviewer.jsx. Whenever data is changed in one, it must also be changed in the other... We should consolidate this to one array of documents, and one sorted array of ids that references the main array. This way data is only modified in one place.

**Comment by NickHeiner** [comment]
Is this still relevant?

**Comment by NickHeiner** [comment]
This is not still relevant.
