### ISSUE TITLE
Rewrite Webpack Config

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12708]
## Description
After we've completed the minimal Webpack 4 upgrade, we should rewrite our Webpack configs. 

We can utilize the `devServer` key on normal Webpack config, then change our launch script to simply call `webpack-dev-server`. ([docs](https://webpack.js.org/guides/development/#using-webpack-dev-server))

**Comment by alisan16** [comment]
cc @sahalliburton in case you're interested!

**Comment by meckila-navapbc** [comment]
Resolved in #15856. Replaced React Hot Loader (deprecated) with React Fast Refresh
