### ISSUE TITLE
Route Claim | Send Email Notification | Back button missing

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1270]
When working on a Full Grant, it would be helpful to see a "Back to Decision Review" link for pages where it is possible to do so. 

## Acceptance Criteria
- Validate that when on either the "Send Email Notification" page or the "Process Outside of Caseflow" page, there is a "< Back to Decision Review" link that takes the user back to the Decision Review page (exactly like the one on the "Create EP" page).

## Additional Information
*Route Claim: Send Email Notification only occurs when we cannot create an EP. A back button on the Route Claim: Send Email Notification page is useful bc the caseworker might have accidentally clicked the wrong special issue and thus, might want to go back to the Decision Review page to adjust it.

_Desired:_
<img width="757" alt="screen shot 2017-03-23 at 7 15 00 pm" src="https://cloud.githubusercontent.com/assets/4975959/24274195/1557863a-0ffd-11e7-8aa1-27439211b043.png">

<img width="875" alt="screen shot 2017-03-23 at 7 14 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/24274196/19867310-0ffd-11e7-87f0-40eabf02baa4.png">

**Comment by kierachell** [comment]
Additionally missing here:
<img width="1109" alt="screen shot 2017-03-21 at 4 44 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/24170251/b6792fbc-0e56-11e7-986a-949ac53a86aa.png">

**Comment by kierachell** [comment]
also this:

The page does not have a yellow box until you try to go back.
<img width="1021" alt="screen shot 2017-03-21 at 5 21 18 pm" src="https://cloud.githubusercontent.com/assets/18075411/24171429/d57481a6-0e5a-11e7-967f-24d52c454593.png">

**Comment by lakohl** [comment]
@kierachell I think the screenshot in the comment above might actually show the app working as desired. If they tried to go Back from that screen, that message in yellow would be appropriate.

**Comment by kierachell** [comment]
I think my question is more about the whole flow: is there a warning or something clear indication to the user that they are about to do an operation that cannot be undone?
What I experience is: **Route claim** leads me down a variety of paths (exisitng EPs, creating new EP page, add VBMS note, VACOLS Note, cannot process claim). Some of these allow me do "go back" and some do not. I understand that the progress bar is a kind of indicator, but I can foresee someone selecting a special issue by accident and not be able to "go back". Ultimately this could be a question about performance vs accuracy.

**Comment by lakohl** [comment]
The only time we don't have a back button is on the VACOLS Updated step. This is because it's a step that the system is performing, not the user. The inability to go back was more a technical solution then a design decision. If VACOLS can Update when we leave the Route Claim page then we could pose the VACOLS Update as a question (with a back button). That would be better for the user.

**Comment by sharonwarner** [comment]
I can comment on the issue as well, but there's one more case we need to cover. We should be able to go backwards on the Partial Grant / Remand page for special issues that we don't create an EP for. 

<img width="1225" alt="screen shot 2017-03-29 at 11 47 28 am" src="https://cloud.githubusercontent.com/assets/4306128/24463849/f71ab994-1475-11e7-9397-bebdda3d48f6.png">

**Comment by sharonwarner** [comment]
I think there's one more case we need to cover. We should be able to go backwards on the Partial Grant / Remand page for special issues that we don't create an EP for. 

<img width="1225" alt="screen shot 2017-03-29 at 11 47 28 am" src="https://cloud.githubusercontent.com/assets/4306128/24463849/f71ab994-1475-11e7-9397-bebdda3d48f6.png">

**Comment by ariperez-gov** [comment]
@sharonwarner is this covered by this story?

https://github.com/department-of-veterans-affairs/caseflow/issues/1280

I'm currently working on that one too and struggling on understanding when EPs are created and when they are not as thats still not clear to me at that point.  Might need your help. :)

**Comment by astewarttistatech** [comment]
Based on @lakohl 's comment about the only pages not having the back button is for when VACOLS is updated, this ticket is being pushed back

<img width="1272" alt="screen shot 2017-03-31 at 9 43 47 am" src="https://cloud.githubusercontent.com/assets/23038505/24554191/b306453a-15fa-11e7-8af9-b9daa809ca31.png">
<img width="1181" alt="screen shot 2017-03-31 at 9 43 16 am" src="https://cloud.githubusercontent.com/assets/23038505/24554198/b9954004-15fa-11e7-8019-12f56c49113c.png">

**Comment by slj** [comment]
The alert pages in this issue seem to be deprecated.  I think the buttonLink back to Review Decision is everywhere it needs to be  The acceptance criteria might need an update.

**Comment by kierachell** [comment]
**PASSED**
@slj is right.
The last scenario is covered by #1280
