### ISSUE TITLE
accept contact info for a veteran when intaking a HLR (v3 api)

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/caseflow#12705]
## Description

[Form 20-0996](https://www.va.gov/decision-reviews/forms/higher-level-review-20-0996.pdf) has a section for updating a veteran's contact info. Currently, our only decision review creation endpoint, _create a higher_level_review_, does not support this.

**Comment by pkarman** [comment]
this is going to be tricky. Currently Caseflow does not support writing to BGS, so there is no place for us to store this contact info. If CAs are currently updating CorpDB manually as part of intake, that is not happening via Caseflow.

**Comment by edmangimelli** [comment]
@pkarman from the accompanying PR:

>At this moment, we're going to receive this contact info solely for generating a filled-out pdf of 20-0996, but, in the future, we'll use it to update the veteran's address in vet360.
