### ISSUE TITLE
Research if Code Climate or another tool can detect unused code

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#12728]
## Description

Research to see if Code Climate can detect unused code. We shouldn't spend time maintaining unused code.

See: https://dsva.slack.com/archives/C3EAF3Q15/p1573834819075800

## Background/context/resources

Found an unused class, that might be able to be removed

**Comment by alisan16** [comment]
Looked at this briefly and didn't see any CodeClimate functionality that did this, outside of these Rubocop linters:

- Unreachable Code: https://rubocop.readthedocs.io/en/latest/cops_lint/#lintunreachablecode
- UnusedBlockArgument (scroll down in link above)
- UnusedMethodArgument (^^)

which are all enabled by default. Are we using those?

**Comment by ferristseng** [comment]
Yeah, I think we are using those. I've definitely run into the unreachable code one, and looks like they're also enabled by default.

I tried using this and it turns up some good results: https://github.com/joshuaclayton/unused, but I don't think there's a way to automate it with CodeClimate

**Comment by ferristseng** [comment]
So I read the unused README more closely, and it looks like they re-implemented everything: https://github.com/unused-code/unused.

I compiled and ran it and against Caseflow and this is result:

[unused.txt](https://github.com/department-of-veterans-affairs/caseflow/files/5952506/unused.txt)
