### ISSUE TITLE
Document Viewer | Categories: associate document to category

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1274]
**Story**
When reviewing a document, I want to select a category so I can filter by similar documents when writing a decision.

#### Dev Notes
- Includes persisting category selection to server

## Acceptance Criteria
- Validate that there are 3 category checkboxes with label icons and the words associated with each color under Receipt Date
![image](https://cloud.githubusercontent.com/assets/13420618/24772301/caf106b0-1ade-11e7-8e43-c113df7d917d.png)

  - [Procedural SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20Blue%20category.svg) Hex #4A90E2
  - [Medical SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20Pink%20category.svg) Hex #FF6868
  - [Other evidence SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20Green%20category.svg) Hex #5BD998

- The checkbox styling should reflect the one we have on style guide https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide
- Validate that when clicking on a category checkbox, the color icon associated with the checkbox displays to the left of the Document Type in the top toolbar of the PDF viewer
- Validate by deselecting a checkbox, the label icon is removed from the top toolbar of the document
- Validate that a user can add multiple categories to each document
- Validate that when I navigate to the Documents List page, the category I just associated with a document displays in the Categories column in that document's row 
- Validate that on the document toolbar at the top, the category icons go in the order of procedural (blue), medical (pink), and others (green). 
- Validate that they are always located on the right of the document name and always start there
- Validate that after you set and unset categories for a document, this state persists after you refresh the page.

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/24772352/f5d37c8c-1ade-11e7-9cd9-95b7b8b8a5c3.png)

**For the order of category labels**

![image](https://cloud.githubusercontent.com/assets/13420618/24974869/aaabf718-1f91-11e7-8d8a-7cdea3c513f2.png)

![image](https://cloud.githubusercontent.com/assets/13420618/24974876/b12b66b4-1f91-11e7-9bf7-7670f64e317a.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)

**Comment by gnakm** [comment]
@abbyraskin Please audit + add love !

**Comment by abbyraskin** [comment]
note: we need svgs for category icons

**Comment by NickHeiner** [comment]
> note: we need svgs for category icons

We have those SVGs. 

Does this include the filtering functionality in the PDF List view?

**Comment by NickHeiner** [comment]
![image](https://cloud.githubusercontent.com/assets/829827/24972847/c5348cb4-1f8a-11e7-8b39-ff8148362845.png)

@abbyraskin @gnakm what do you think about this? Do we want the category icons to always appear in the same columns? (eg green is always on the far right, even if there are no other categories.) I can explain in person if this is not making sense.

**Comment by abbyraskin** [comment]
> Does this include the filtering by category functionality in the PDF List view?

@NickHeiner this ticket is only intended to cover adding categories to a PDF - category filtering functionality is documented in #1432

>  Do we want the category icons to always appear in the same columns? (eg green is always on the far right, even if there are no other categories.) I can explain in person if this is not making sense.

Goooood question. I think we'd want each color to have a predefined "position" (e.g., green on the far right) so it's a little easier on the eyes when scanning through a long list. What do you think @gnakm? As to what those specific positions should be, I have zero opinions.

**Comment by abbyraskin** [comment]
Hmm, caveat to suggestion above: I think they will generally only use one category (note: this is an assumption to test in the pilot!), so having them default to one position (e.g., far left) might make more sense. I defer to Gina's wisdom on this one.

**Comment by gnakm** [comment]
@abbyraskin @NickHeiner 

Fun question. I like keeping it in the order so, procedural(blue), med(pink), others(green) but always starting from the far left as Abigail mentioned. The screenshot that Nick posted 3 comments above reflects that!

Could we do the same thing for categories in PDF? 
![image](https://cloud.githubusercontent.com/assets/13420618/24974789/6e14fd18-1f91-11e7-8220-ab4a4b665ef7.png)

I don't think this will really change the UX. This is actually more beneficial to us :)

I will add these changes to the AC across issues now.

**Comment by NickHeiner** [comment]
:+1: sounds good. I already had it in a consistent order, so I'll keep it that way, but I won't worry about making the columns be the same for now.

**Comment by NickHeiner** [comment]
Does this ticket include persisting the category selection for a document to the server?

**Comment by abbyraskin** [comment]
@NickHeiner in my mind, yes. but if you think it should be broken out separately let me know...

**Comment by NickHeiner** [comment]
Nope, that's fine, just wanted to clarify.

**Comment by abbyraskin** [comment]
@NickHeiner I added a dev note at the top

**Comment by NickHeiner** [comment]
👍 sounds good.

Is there a UI spec for what happens if the persisting to the server fails?

**Comment by NickHeiner** [comment]
>  I think they will generally only use one category

@abbyraskin it would make things simpler if each doc could only have a single category. What if we said for now, that's a constraint, and we can open it up to having multiple categories if that need arises?

**Comment by abbyraskin** [comment]
> Is there a UI spec for what happens if the persisting to the server fails? Or an indicator that the save completed successfully?

re: error state...paging @gnakm! 

we should probably have as subtle a handling here as possible, perhaps some sort of inline message/call to retry rather than one of the larger alert messages?

@NickHeiner as far as providing users with feedback it succeeded...is it possible to only show the bookmark in the toolbar (next to the document type) only if/after saving it to the db succeeds? or would that heavily delay things? i don't think we need a separate "success" otherwise, but should definitely consider error scenarios.

**Comment by abbyraskin** [comment]
@NickHeiner just to make sure...we're specifically talking about the call that is made when the category checkbox is selected in the PDF viewer?

**Comment by abbyraskin** [comment]
Wondering if it's enough feedback to just not have the checkboxes select until it sends, or if that could be frustrating...

**Comment by abbyraskin** [comment]
Also, how do we handle this for comments?

**Comment by NickHeiner** [comment]
> we're specifically talking about the call that is made when the category checkbox is selected in the PDF viewer?

Yes.

> Wondering if it's enough feedback to just not have the checkboxes select until it sends, or if that could be frustrating... 

> is it possible to only show the bookmark in the toolbar (next to the document type) only if/after saving it to the db succeeds? or would that heavily delay things?

I would recommend against this. I think you're right that it'll make the UI feel sluggish. The typical best practice is to optimistically update the UI, assuming that the backend call will work.

We could not show anything for success, and just have that be the assumed state. Or we could have a little spinner / checkmark that says something like "saving changes ... all changes saved" that applies to any changes. (This is what Google Docs does.)

**Comment by gnakm** [comment]
I don't think we need to show anything for successes. We tested with users without them and it was the assumed state. For the Categories, success is assumed when user sees the icons change in the toolbar, for issue tags, the issues in a box and for saved comments, a new comment box added to the list. 

I do see that we may need something for latency. :cringe:

As for straight up errors, what about having what Abby and I call, Error Lites pop above each section. 

Ex. If checkbox doesn't work, 

![image](https://cloud.githubusercontent.com/assets/13420618/25024310/6ce5dfea-206b-11e7-9e13-b2d7fea12afc.png)

**Comment by gnakm** [comment]
@NickHeiner I thought about your Google doc "saving..." idea. We currently have loading buttons on the style guide. For Categories and Issues, I wonder if we could have it not in a box and just text with spinner and for the Save button in comment, we can have the button version. 

/cc: @abbyraskin 
![image](https://cloud.githubusercontent.com/assets/13420618/25024719/007cd29e-206d-11e7-8493-48330de1e355.png)

**Comment by NickHeiner** [comment]
I agree with your idea that success is the assumed state. How about we say:

1. User changes the checkbox.
1. Client fires a request to save to the server.
1. Client immediately updates the UI to make it look like the UI succeeded.
1. If the request succeeds: nothing happens
1. If the request fails: the checkbox goes back to its original state, and the Error Lite appears.

**Comment by gnakm** [comment]
I moved the Error Lite issue here #1573

**Comment by kierachell** [comment]
**PASSED**
checked on `preprod`
values persist upon reload
<img width="320" alt="screen shot 2017-04-17 at 2 42 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/25100241/51d56af8-237d-11e7-85da-59567aa9c8a7.png">
<img width="636" alt="screen shot 2017-04-17 at 2 42 59 pm" src="https://cloud.githubusercontent.com/assets/18075411/25100242/51ddf498-237d-11e7-8863-bcb72bc81308.png">
<img width="724" alt="screen shot 2017-04-17 at 2 43 02 pm" src="https://cloud.githubusercontent.com/assets/18075411/25100243/51e93c18-237d-11e7-8665-079d3cd88489.png">
<img width="581" alt="screen shot 2017-04-17 at 2 43 23 pm" src="https://cloud.githubusercontent.com/assets/18075411/25100244/51f2c8fa-237d-11e7-8759-209f06ea51fc.png">

**Comment by kierachell** [comment]
added a related bug issue: #1613
