### ISSUE TITLE
Alias the "Manage Claim Establishme" role to "Manage Claim Establishment"

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1275]
Because of a character limit that we were not aware of, the permission in css roles is "Manage Claim Establishme". We need to add this permission as an alias to all the things "Manage Claim Establishment" allows you to access.

**Comment by astewarttistatech** [comment]
I am not too sure how this should be validated @shanear . Is this a correct way?

Validated in: UAT
Browsers Validated in: FF, Chrome

Steps to Validate: 
1. Go to the Functions page in Caseflow and "Inspect" the user role for "Manage Claim Establishment".
2. Validate that the user role alias is correct.

<img width="1382" alt="screen shot 2017-03-22 at 2 50 38 pm" src="https://cloud.githubusercontent.com/assets/23038505/24215389/feaee2fa-0f0e-11e7-9c58-242d45dc19b6.png">

**Comment by kierachell** [comment]
@abbyraskin 
> claims not claim

**Comment by kierachell** [comment]
Merged to prod last night -
@abbyraskin is a champ!

**Comment by shanear** [comment]
George was able to log into the manager view. Closing this one.
