### ISSUE TITLE
Long-term Data Integrity Planning

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12773]
## Background/context

In Team Echo's sprint retro, we commented on the lack of any single team responsible for the [data integrity](https://en.wikipedia.org/wiki/Data_integrity) of Caseflow's DB. 
Why is this important? 
- Caseflow's DB is the system of record for AMA appeals. 
- The DB schema evolves over time, introducing potential inconsistencies with past data records. 
- Potential mis-interpretation, e.g., a task tree that was once valid is now invalid, which hinders accurate analysis and reporting.

## Goals

Determine what we should do to move towards having and maintaining data integrity for the long-term as Caseflow evolves and matures.

## Success criteria

Create and implement a plan to ensure data integrity.

## Stakeholders

Engineers, end-users, and any roles that report out using Caseflow data records. 

### Some ideas:

1. Get a baseline: Analyze the current data to find anomalies and inconsistencies. Identify what is expected and not expected to be in the DB.
2. Take stock and identify gaps: We currently have data integrity checkers implemented as daily(?) jobs that query the DB. What is their coverage compared to desired coverage? What have they been used for? How would we like to continue to use them?
3. Enact remediations and monitor for data integrity failures: 
   * Create more data integrity checkers
   * Use [Rails model validations](https://guides.rubyonrails.org/active_record_validations.html) to enforce the constraints. Are we using this capability to its fullest?
   * Improve coding practices, e.g., https://dev.to/amplifr/purify-code-with-data-integrity-part-1-defaults-and-not-nulls-492p

## Open questions

Who should be responsible (e.g., data functional lead, data team tech lead) for ensuring data integrity and following up on the plan and suggested ideas, soliciting more ideas, being looped into issues that appear to be caused by data integrity issues, etc.?

**Comment by pkarman** [comment]
IMO the team responsible for data integrity is the new Delta team, with input from the Data Functional Lead.
