### ISSUE TITLE
Establish Claim fails if veteran is missing address info in BGS

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1277]
Every once in a while, a veteran will be missing a piece of their address in BGS. This will cause the establish claim action in VBMS to always fail. We should show them a better error message and ask them to update.

## Acceptance Criteria
- Validate that a claim is able to be established in VBMS for a veteran with an international address

## Technical Notes
- It seems like this error occurs with international veterans. Asking the VBMS team how to deal with this (https://github.com/department-of-veterans-affairs/dsva-vbms/issues/77)

- The implementation here is very similar to https://github.com/department-of-veterans-affairs/caseflow/issues/1281 just with a different VBMS error.

## Additional Information
Our options to solve this are:
1. Explore what they do in VBMS.
2. Maybe we can send some sort of empty default for this?
3. If it requires them to actually fill in the missing information, we have to either:
  A) Show the corresponding personal info fields in the UI (lots of dev work)
  B) Ask the user to update the Veteran's missing information in VBMS/Share/etc.

## Mock
<img width="803" alt="screen shot 2017-03-23 at 7 08 32 pm" src="https://cloud.githubusercontent.com/assets/4975959/24274020/21f4a98c-0ffc-11e7-9b71-9b08a7e72e5f.png">

**Comment by abbyraskin** [comment]
We should also figure out exactly which fields are required (and which are not).

**Comment by abbyraskin** [comment]
R - Sex
R - First name
R - Last name
R - SSN
R - Address, addressLine1
X - Address, addressLine2
X - Address, addressLine3
R - Address, city
R - Address, state
R - Address, zip code

R = required
X = not required

**Comment by abbyraskin** [comment]
George said they currently update the address in VBMS if something is missing -- George advises them to look in VACOLS, where they can usually find the address info (or Share, which is the same db as BGS).

**Comment by abbyraskin** [comment]
We'll work on language for the error message -- I think we can go with Option 2, with guidance on where to update the address and how to find it.

**Comment by lakohl** [comment]
How high a priority is this?/How often does it happen?

**Comment by shanear** [comment]
It's happened 2-3 times with Larry so far @lakohl

**Comment by kierachell** [comment]
Update: this seems to happen when a veteran's mailing address is not within USA. (can be set to international)

**Comment by abbyraskin** [comment]
@kierachell just to clarify...does it also happen if they're missing required address info, or only if it's an international address?

**Comment by kierachell** [comment]
I can only edit VACOLS and VBMS data. No idea how to get into BGS. So that is all I was able to test.

**Comment by mmlumba** [comment]
Update acceptance criteria because these errors are actually happening because we weren't handling international addresses properly. We are fixing that, and will reopen this issue if we see the problem again. Thanks for the find @kierachell 

## Old Acceptance Criteria
- Validate that when there is a VBMS establish claim failure because of missing veteran information, show a more descriptive error message, along with instructions with what to do next. 

Copy:
> Missing profile information
In order to proceed, please open VBMS and update the veteran’s profile. Once VBMS has been updated, you may click the Create End Product button at the bottom of this page to establish the EP.

**Comment by kierachell** [comment]
**PASSED**
It worked!
That veteran was in India
<img width="1123" alt="screen shot 2017-03-30 at 9 24 01 am" src="https://cloud.githubusercontent.com/assets/18075411/24506194/b0182080-152a-11e7-9f70-2ad87e5e612f.png">
