### ISSUE TITLE
Intake | Upstream error | Benefit Type, Payee code or EP Code is not valid

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12776]
## Description
We are getting the following error when trying to establish an EP:
Benefit Type, Payee code or EP Code is not valid.  Benefit Type must be CPD, Payee code must be 00, 10 - 29, 50, 60 or 70 - 78.

However, the veteran does not have a date_of_death so we are not considering the veteran deceased, and we're setting the benefit_type_code to 1 (CPL).

## Background/context/resources
INC Report: INC8567708
https://yourit.va.gov/va?id=ticket&table=incident&sys_id=0eb55decdb2508d4bd33748e0f9619c8

This has been associated with defect 748555 and was targeted for Dec 15th, 2019 in release 18.0.0.

## Impacted reviews
SC 200806
SC 438140
SC 438147
SC 501808
HLR 113018
HLR 112995
DD 88480
DD 118484

**Comment by leikkisa** [comment]
I am closing this ticket. The one incident of this has been resolved, the veteran's data has been updated to reflect that the veteran is now deceased (in late March), and the claim was successfully established with the new benefit type code.  I will note that the veteran also had two participant IDs: 49914409, and 44977887

**Comment by leikkisa** [comment]
We've gotten new instances of this - re-opening.

**Comment by wdrougas-tista** [comment]
Working with VBMS to try to gain access to ProdTest environment to recreate these errors. Background provided [here](https://github.com/department-of-veterans-affairs/appeals-deployment/issues/2794)
