### ISSUE TITLE
Work History | Race condition when working on tasks outside of the assigned quota

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1278]
# Description
Two or more caseworkers might end up working on the same task if it was not assigned to anyone. The latter caseworker will be forced to find his/her way to the Work History page to proceed.

**Environment:**
- [ ] Production
- [X] UAT
- [X] Demo
- [ ] Development

**Type of Bug:**
- [X] Performance
- [ ] Design
- [ ] Security
- [X] Functional
 
# Reproduction Steps
Scenario 1 - Overachievers

1. Caseworker1 starts working on task 4

1. Caseworker2 starts working on task 3

1. Caseworker2 finishes and moves on

1. Caseworker1 still doing his thing

1. Caseworker2 lands in the middle of task 4

1. Caseworker1 finishes task 4

1. Caseworker2 gets 500 errors everywhere - can't Route, can't Release, can't Assign, can't Cancel.

1. Caseworker2 gets mad and breaks the copier;

**Comment by shanear** [comment]
Can you reproduce this. Currently I can't see a way to do so.

**Comment by sharonwarner** [comment]
Users can't pick up more than their assigned tasks anymore, so this case isn't relevant.
