### ISSUE TITLE
Stop sending decision issue sync alerts to Slack

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12792]
## Description
We would like to stop reporting the following Sentry alerts to Slack.

- RequestIssue::NoAssociatedRating
  - https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6648/
- RequestIssue::MissingContentionDisposition
  - https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6647/
- RequestIssue::ErrorCreatingDecisionIssue
  - https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6643/

This is handled in the appeals-lambdas repo (see tech notes).

## Background/context/resources
The Foxtrot team is going to start chipping away at the #appeals-intake-alerts channel, with the goal of reducing unactionable noise, so that we can see more clearly which issues require action.  For issues that do require action, we'll start chipping away at those too.

Once an end product is cleared, we check if there is an associated rating (for rating issues), and a contention disposition (for both rating and nonrating issues).  If there isn't, we try again later.  Some of these also require further investigation and attention, but we do not need to look for them in Slack.

These alerts are being triggered in the RequestIssue model during decision issue syncing.  I would say it's questionable whether we even need them, but let's keep them for now until we dig into decision issue syncing errors more, because I find it useful to get alerts like this when checking things out in prod.

## Technical notes
See `SKIP_EXCEPTION_CLASSES` in `caseflow-other/appeals-lambdas/sentry-to-slack/handler.js`

`Rating::BackfilledRatingError` is an example of one that we've decided to keep in Sentry, but not report to Slack.

**Comment by leikkisa** [comment]
@nanotone I'm still seeing these Sentry alerts in Slack. I'm going to kick it back to in progress and we can investigate more. I don't know much about this code or if we need to do anything extra with appeals-lambdas.

**Comment by nanotone** [comment]
@leikkisa It looks like there is currently no CD in place for lambdas yet. I chatted with @aroltsch but it sounds like we can just deploy it manually by following the repo README: https://dsva.slack.com/archives/CAM9FJ85P/p1576161359012600
