### ISSUE TITLE
Route Claim: Special Issue Not handled by Caseflow, missing back button and Required

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1279]
Route Claim: Special Issue Not handled by Caseflow, missing back button and Required

**AC:**
1. Verify that the link:
> < Back to Decision Review

displays in the bottom right.

1. Verify that the word:
> Required

appears in red italic to the right of the check box label.

_Current:_
<img width="1109" alt="screen shot 2017-03-21 at 4 44 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/24170251/b6792fbc-0e56-11e7-986a-949ac53a86aa.png">

_Desired:_
<img width="737" alt="screen shot 2017-03-21 at 7 48 02 pm" src="https://cloud.githubusercontent.com/assets/4975959/24175909/50ea22a0-0e6f-11e7-9c46-cceb41a47ecc.png">

**Comment by shanear** [comment]
folding this into #1270, closing
