### ISSUE TITLE
MTV - add Straight Vacate option to flow

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12793]
## User or job story
As a judge user, I would like to have the option to vacate decision issues without creating new decisions on them.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] Update copy and code to rename Straight Vacate and Readjudication to Vacate and Readjudication
- [ ] Add a Straight Vacate option to the MTVJudgeDisposition modal
- [ ] When submitted, this creates a post decision motion with the new "straight_vacate" type
- [ ] When submitted, a StraightVacateTask is created (following current structure, as DecidedMotionToVacateTask with parent org task, and assigned to the drafting attorney)
- [ ] Existing pattern is followed for partial/full grant and saving issue ids
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Add topline comments for any new files
       - Are there examples of these; best practices documented?

## Release notes
When a judge is deciding a motion to vacate, they will have the option to Straight Vacate, which will not result in new decisions.

### Out of scope
- The attorney's next step
- Creating any issues

### Designs
![Screen Shot 2019-11-22 at 4.53.29 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/dad39caf-c8d3-44b5-86c0-2df2d2b037d1)

### Background/context
We learned about a new MTV flow. We believe this may be to vacate decision issues that happened in AMA, when the issue was still being processed in the legacy system (and therefore getting decided in the legacy system).

### Technical notes
Some things will need to be renamed - files, class names, variables, in order to update StraightVacateAndReadjudicate to just VacateAndReadjudicate.

**Comment by jcq** [comment]
## Updated Screen Shot
<img width="557" alt="Screen Shot 2019-11-27 at 16 27 24" src="https://user-images.githubusercontent.com/2581274/69767821-e5d1f280-1132-11ea-9e5d-a245a640bb30.png">
