### ISSUE TITLE
Handle Disposition Updating and Saving better

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12797]
### Background

We made the decision to only send changed fields in update requests so we could better implement virtual hearings logic that only happens if a field was changed. In order to do this we could have either:

1. stored updated values in a separate state from initial states on update, something like
```
<input value={hearing.updated.field || hearing.field} update={(val) => update({ field: val }) />
```
2. Store the entire initial state of the hearing and compare the initial value and changed value at the time of the request

We went with option 2 because it was more easily integrated with the various ways we've implemented forms.

### Issue

On the daily docket, the initial state for the hearing is stored on the `DailyDocketRow`
https://github.com/department-of-veterans-affairs/caseflow/blob/1b6879a99a42922cea5940e089e2f5ea510e0576/client/app/hearings/components/dailyDocket/DailyDocketRow.jsx#L62-L64

and then the comparison is done when the hearing is saved
https://github.com/department-of-veterans-affairs/caseflow/blob/1b6879a99a42922cea5940e089e2f5ea510e0576/client/app/hearings/components/dailyDocket/DailyDocketRow.jsx#L156-L174

This works fine except in the instance when the hearing is `cancelled` or `postponed`. "Currently Scheduled" and "Previously Scheduled" split hearings where the dispositions is null, `held` or `no_show` from those that are `cancelled` or `postponed` into separate `DailyDocketRows`:
https://github.com/department-of-veterans-affairs/caseflow/blob/44405358f7fe40e8d8175ad6e655ed21679690ca/client/app/hearings/components/dailyDocket/DailyDocket.jsx#L205-L212
https://github.com/department-of-veterans-affairs/caseflow/blob/44405358f7fe40e8d8175ad6e655ed21679690ca/client/app/hearings/components/dailyDocket/DailyDocket.jsx#L222-L230

This would be fine except the dropdown that controls disposition opens a modal before save:
https://github.com/department-of-veterans-affairs/caseflow/blob/44405358f7fe40e8d8175ad6e655ed21679690ca/client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx#L29-L46

This means that when the currently scheduled hearings are changed to postponed, they are unmounted / removed from the first set of `DailyDocketRows` and mounted on the second, the modal opens, and when the user goes to `saveHearing`, the row no longer exists.

### Solutions
Since this issue only occurs when we're changing the disposition dropdown, we shouldn't complicate the entire save logic for one instance. Let's just change the disposition dropdown to handle this scenario:

```javascript
    onChange={(option) => {
      if (!option) {
        return;
      }

      const fromDisposition = hearing.disposition;
      const toDisposition = option.value;

      openDispositionModal({
        hearing,
        fromDisposition,
        toDisposition,
        onConfirm: saveThenUpdateDisposition
    }}
```
where `saveThenUpdateDisposition` is a slight variation on `saveHearing`, something like
```javascript
// class method on DailyDocketRow.jsx
saveThenUpdateDisposition = (toDisposition) => {
  const hearingWithDisp = { 
    ...this.props.hearing,
    disposition: toDisposition
  };

  const hearing = deepDiff(initialState, hearingWithDisp);

  this.props.saveHearing(hearing.externalId, hearing).then(() => {
    // update redux
    update(hearingWithDisp);
    // only update initialState if hearing isn't postponed or cancelled
    if (['postponed', 'cancelled'].indexOf(toDisp) === -1) {
     this.setState({ initialState: hearingWithDisp });
    }
  });
}
```

**Comment by pshahVA** [comment]
Isn't this done?  How do we close this?
