### ISSUE TITLE
BGS API endpoint for older rating profile data

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12805]
Follow on to #11840 

Explore a new BGS API endpoint that may contain the missing rating_issue_id values for these non service connected decisions. This requires some additional infrastructure work in Caseflow in order to allow us to preview this API endpoint with production-like data while it is in development.

**Comment by msj0nes** [comment]
@pkarman can this be marked closed considering #11840?

**Comment by pkarman** [comment]
@msj0nes #12851 supercedes this.
