### ISSUE TITLE
Route Claim | Confirm VACOLS Update | Allow user to go back without Alert

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1280]
On the `Route Claim: Confirm VACOLS Update` page that's shown when **no EP is created**, when a user attempts to go back to the `Decision Review` page using the browser **_Back_** button, they are presented with an Alert message that isn't accurate. It says that an EP has been created.

## Acceptance Criteria
When on the "Route Claim: Confirm VACOLS Update" page, and no EP has been created for the current task, (Partial/Remand with Level 3 Special Issue)
- Validate that there is a "< Back to Decision Review" link, which takes the user back to the decision review page.
- Validate that when the browser **_Back_** button is pressed, the user is taken back to the Decision Review page.

Here is a [demo](https://github.com/department-of-veterans-affairs/caseflow/issues/1280#issuecomment-293679946) of the [accepted](https://github.com/department-of-veterans-affairs/caseflow/issues/1280#issuecomment-293706210)  behavior.

### Current State:
<img width="1146" alt="screen shot 2017-03-29 at 12 40 12 pm" src="https://cloud.githubusercontent.com/assets/18075411/24465908/e29cd73e-147c-11e7-9bd6-40299d03fae0.png">

**Comment by lakohl** [comment]
@avrildavid any ideas on a better way to express the yellow warning message in the second screenshot above?

**Comment by avrildavid** [comment]
@lakohl 

**A few suggestions if helpful:**
This step/action cannot be reversed in Caseflow
You cannot reverse this step in Caseflow
This step/action is permanent

**Comment by lakohl** [comment]
thanks @avrildavid !

**Comment by lakohl** [comment]
AC needs to be re-written

**Comment by ariperez-gov** [comment]
@avrildavid , can you choose the best text here since Laura is out.  Just add an updated Acceptance criteria to check for new text.

**Comment by avrildavid** [comment]
@ariperez please see the third bullet under acceptance criteria

**Comment by abbyraskin** [comment]
I'm a little confused. Is this supposed to be a scenario where the EP was created? If so, they would be on the` Route Claim: VACOLS Updated, Add VBMS Note` page, I think.

If this is meant to be a scenario where no EP was created, I would not expect the message to say "Cannot edit end product" in the title.

The AC is somewhat contradictory -- are we allowing them to go back to the Decision Review page or not?

**Comment by avrildavid** [comment]
@abbyraskin @ariperez - I'll remove that bullet. It also wasn't clear to me if there was a bug that had to be addressed first (i.e., it was showing an inaccurate warning) or if this was in reference to the right page.

**Comment by kierachell** [comment]
updated AC to match current functionality

**Comment by abbyraskin** [comment]
@ariperez [this document](https://github.com/department-of-veterans-affairs/appeals-design-research/edit/master/Projects/Dispatch/Routing%20EPs/Special%20Issue%20Tiers.md) will help you identify all special issues that do not get EPs.

**Comment by ariperez-gov** [comment]
@joofsh or @sharonwarner , I might need to need to Pair Program with one of you tomorrow on this.  I'm not quite clear programmatically when the EP is created on the above page and when it is not.  Let me know who's best to work with.

**Comment by slj** [comment]
@abbyraskin @lakohl etc Is this the desired behavior?

![vacols-update-back](https://cloud.githubusercontent.com/assets/1053255/24975290/201f7000-1f93-11e7-8670-909b43157af6.gif)

**Comment by lakohl** [comment]
@slj it looks good to me!

**Comment by kierachell** [comment]
**PASSED**
validated in `preprod`
![iroutemyclaimbackandforth](https://cloud.githubusercontent.com/assets/18075411/25150027/8f816434-244e-11e7-8165-35370c9f629c.gif)
