### ISSUE TITLE
Handle VBMS error where there is an existing cancelled EP more gracefully

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1281]
Occasionally there will be a 172 EP that has been cancelled within the last 24 hours for an Appeal for which a claim is being established. As a caseworker, I would like to know that this is the cause of a VBMS claims establishment failure.

## Acceptance Criteria
- Validate that when there is a VBMS establish claim failure because of a conflicting EP that was cancelled within 24-48 hours, show a more descriptive error message, along with instructions with what to do next.

### Message Copy
At this time, we are unable to assign or create a new EP for this claim.
An EP with that modifier was previously created for this claim. Try a different modifier or select Cancel at the bottom of the page to release this claim and proceed to process it outside of Caseflow.

## Technical Information
Here is an example of the error that is raised:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/121/events/2870/

## Additional Information
Occasionally there will be a 172 EP that has been cancelled within the last 24 hours for an Appeal for which a claim is being established.

Right now, this will throw a generic VBMS error message when trying to establish the claim from Caseflow.

We could rescue this error and do something more graceful, like:

1) Postponing the task for 24 hours and then have it reenter the queue. (medium/hard difficulty)

2) Show a more descriptive message about why the failure is happening, and tell them to cancel the EP and how to establish the claim manually. (low/medium difficulty

For the moment we are going with option 2 above.

> At this time, we are unable to assign or create a new EP for this claim.
A 172-BVA Grant EP previously created for this claim was cancelled within the last day, but has not cleared. Please select Cancel at the bottom of the page to Release this claim from Caseflow.

**Comment by abbyraskin** [comment]
I will loop around with George (ARC's manager) on this as a starting point.

My instinct is to push for the first option, as it prevents cases from slipping through the cracks. 

That said, according to George, they really should not be canceling EPs -- we could go with a version of your second option where we specifically tell them to alert their manager so he has visibility into when this happens (and/or display it on the manager dashboard either way -- maybe break out canceled cases from "completed" cases).

**Comment by shanear** [comment]
R - Sex
R - First name
R - Last name
R - SSN
R - Address, addressLine1
X - Address, addressLine2
X - Address, addressLine3
R - Address, city
R - Address, state
R - Address, zip code

R = required
X = not required

@abbyraskin

**Comment by shanear** [comment]
Changed the message copy

### Old Message Copy
At this time, we are unable to assign or create a new EP for this claim.
A 172-BVA Grant EP previously created for this claim was cancelled within the last day, but has not cleared. Please select Cancel at the bottom of the page to Release this claim from Caseflow.

**Comment by kierachell** [comment]
It seems like there's another issue involved here: We are not validating/sending SSN info? Note differing SSNs between VACOLS and VBMS - that is intentional

## Steps:
1. Get a recently cancelled Full Grant like this (VBMS ID 516517673):
<img width="1018" alt="screen shot 2017-04-01 at 11 10 43 am" src="https://cloud.githubusercontent.com/assets/18075411/24579895/6603eada-16cc-11e7-9774-204fc8512167.png">
<img width="375" alt="screen shot 2017-04-01 at 11 11 22 am" src="https://cloud.githubusercontent.com/assets/18075411/24579896/6919bf4c-16cc-11e7-970a-a4b7e044a1a5.png">

1. Attempt to Route it however you want to create a new EP

1. Get error as shown below:
```
status_code=500, body=<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><env:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXdgAB13ZWJsb2dpYy5hcHAudmJtcy1jbXMtYXBwLmVhcgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQAEjEyLjEtMjAxNzAzMjAtMTc0NQAA</work:WorkContext></env:Header><S:Body><ns0:Fault xmlns:ns1="http://www.w3.org/2003/05/soap-envelope" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>ns0:Server</faultcode><faultstring>Error validating ClaimService data input. GUID: be115748-6920-41f4-9a76-a9c48219b0af</faultstring><detail><dataValidationFaultDetailBean xmlns="http://vbms.vba.va.gov/external/ClaimService/v4" xmlns:ns0="http://vbms.vba.va.gov/cdm/claim/v4" xmlns:ns1="http://vbms.vba.va.gov/cdm/common/v4" xmlns:ns2="http://vbms.vba.va.gov/cdm/participant/v4"><formFieldErrors xmlns="http://vbms.vba.va.gov/external/ClaimService/v4"><fieldName xmlns="http://vbms.vba.va.gov/external/ClaimService/v4">PersonalInfo SSN</fieldName><errorType xmlns="http://vbms.vba.va.gov/external/ClaimService/v4">MINIMUM_LENGTH_NOT_SATISFIED</errorType><message xmlns="http://vbms.vba.va.gov/external/ClaimService/v4">The minimum data length for the PersonalInfo SSN within the veteran was not satisfied: The PersonalInfo SSN must not be empty.</message></formFieldErrors></dataValidationFaultDetailBean></detail></ns0:Fault></S:Body></S:Envelope>
```

## Sentry
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/121/

**Comment by kierachell** [comment]
# Partial/Remand Not Working Either

## Steps

1. Grab a Partial/Remand ID where a 170 EP was created then cancelled
  - BFKEY 2734975  BFCORLID	516517671S

1. Attempt to route it again

1. See that default Modifier on **Create End Product** page is 170

1. Attempt to Create New End Product

1. Get an _non-informative error message_

1. Retry with modifier 171

1. Succeed

```
dsva-appeals-certification-uat /opt/caseflow-certification/src/log/caseflow-certification.out [appeals.cf.uat.ds.va.gov] [0e2e7b2f-40c6-48f3-8519-670e4cf1e50d] [172.30.67.198] [CASEFLOW1 ] 
[2017-04-01 1
1:31:35 -0400] VBMS HTTP Error 500 (EstablishClaim) <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:S="http://schemas.xmlsoap.org/soap/envel
ope/">
<env:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXeyAB13ZWJsb2dpYy5hcHAudmJtcy1jbXMtYXBwLmVhcgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQAEjE
yLjEtMjAxNzAzMzAtMTM0NwAdd2VibG9naWMuYXBwLkNvcnBvcmF0ZURhdGFFQVIAAADWAAAAI3dlYmxvZ2ljLndvcmthcmVhLlN0cmluZ1dvcmtDb250ZXh0AAYxMC4yLjAAAA==</work:WorkContext></env:Header><S:Body><ns0:Fault xmlns:ns1="htt
p://www.w3.org/2003/05/soap-envelope" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/">
<faultcode>ns0:Server</faultcode><faultstring>Claim not established. BGS code; PIF is already in use. GUID: 95
b21477-01fa-4076-90b3-5e417f60c265</faultstring><detail><serviceException xmlns="http://vbms.vba.va.gov/external/ClaimService/v4" xmlns:ns0="http://vbms.vba.va.gov/cdm/claim/v4" xmlns:ns1="http://vbms.v
ba.va.gov/cdm/common/v4" xmlns:ns2="http://vbms.vba.va.gov/cdm/participant/v4"/></detail></ns0:Fault></S:Body>
</S:Envelope>
dsva-appeals-certification-uat /opt/caseflow-certification/src/log/caseflow-certification.out 
[appeals.cf.uat.ds.va.gov] [0e2e7b2f-40c6-48f3-8519-670e4cf1e50d] [172.30.67.198] [CASEFLOW1 ] [2017-04-01 1
1:31:35 -0400] status_code=500, body=<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><env:Head
er>
<work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXeyAB13ZWJsb2dpYy5hcHAudmJtcy1jbXMtYXBwLmVhcgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQAEjEyLjEtMjAxNzAzMz
AtMTM0NwAdd2VibG9naWMuYXBwLkNvcnBvcmF0ZURhdGFFQVIAAADWAAAAI3dlYmxvZ2ljLndvcmthcmVhLlN0cmluZ1dvcmtDb250ZXh0AAYxMC4yLjAAAA==</work:WorkContext></env:Header><S:Body><ns0:Fault xmlns:ns1="http://www.w3.org/
2003/05/soap-envelope" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>ns0:Server</faultcode>
<faultstring>Claim not established. BGS code; PIF is already in use. GUID: 95b21477-01fa-407
6-90b3-5e417f60c265</faultstring>
<detail><serviceException xmlns="http://vbms.vba.va.gov/external/ClaimService/v4" xmlns:ns0="http://vbms.vba.va.gov/cdm/claim/v4" xmlns:ns1="http://vbms.vba.va.gov/cdm/c
ommon/v4" xmlns:ns2="http://vbms.vba.va.gov/cdm/participant/v4"/></detail></ns0:Fault></S:Body></S:Envelope>
```

**Comment by shanear** [comment]
Need to add: Claim not established. BGS code; PIF is already in use.

**Comment by shanear** [comment]
added AC:
- Validate that when EPs with modifiers of 170, 171, 175, etc. but with a non-dispatch related EP Code (e.g. "Notice of Disagreement") exist. The EPs are not shown on the "Existing EP" page, but are removed from the options on the "Create EP" page.

**Comment by shanear** [comment]
the AC above is a dup of
https://github.com/department-of-veterans-affairs/caseflow/issues/1406#event-1024717482

**Comment by shanear** [comment]
"RFD" claims also cause the issue. Adding that

**Comment by kierachell** [comment]
RFD = Ready For Decision
RW = Ready to Work

**Comment by kierachell** [comment]
Still ain't working!
https://10.236.66.247/sentry/caseflow-uat/issues/168/
<img width="960" alt="screen shot 2017-04-10 at 11 12 30 am" src="https://cloud.githubusercontent.com/assets/18075411/24868650/afba93d6-1dde-11e7-9f84-f1c1c2dc1251.png">

**Comment by kierachell** [comment]
**PASSED**
AYYY!
