### ISSUE TITLE
Data Integrity Check for Legacy Appeals with No Corresponding Vacols Record

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12810]
On Legacy Appeals, we will occasionally attempt to access a vacols record that has been deleted (example: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7387/). We should create a DataIntegrity job that finds all legacy appeals with active tasks that do not have vacols records.

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8079

**Comment by pkarman** [comment]
What is the LegacyAppeal record has open assigned/active tasks?

**Comment by pkarman** [comment]
What action should be taken on these LegacyAppeal records that are orphaned? Should they just be deleted?
