### ISSUE TITLE
Design for create individual virtual hearing docket days

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12825]
## User story
As a Hearing Branch team member (with the ability to create the hearing schedule), I need the ability to create and view hearing docket days that are virtual-only.

## Problem statement
We think virtual hearings will need to be represented on the Daily Docket differently from how video and central hearings are represented. The aim is to reinforce to users that they're operating in different contexts where some apparently similar functionality works differently. Specific differences we know about now:
- Hearing Time field - The current video Time field represents Regional Office time, and thus has a variable timezone that Caseflow calculates after you make a selection. But for virtual hearings, the Time field should represent Board time, since using veteran time would make it practically impossible to construct a logical virtual docket day potentially composed of veterans throughout the country/world.

## Background/context

- Feedback from usability testing with Hearing Coordinators that virtual hearings should be easier to distinguish from video hearings on the Daily Docket (#12960)

## Open questions
- [ ] Would we have a mix of video and virtual, or just virtual?
  - The Hearing Branch's ideal state is virtual-only docket days. But if a Veteran converts to virtual after they've been notified of their video or central hearing, the Hearing Branch won't have enough lead time to backfill the time slot if the Veteran is moved to a virtual-only docket. So the assumption is that mixed dockets will always exist.
- [ ] Will virtual and video hearing capacity (i.e. number of hearing slots available) be different?
- [ ] Do virtual hearings still need the option to assign a hearing room at the Board?
- [ ] How do virtual-only hearing days display in the Schedule Veterans flow?
- [ ] Might we address this issue with a redesigned Daily Docket: #12927 Display Veteran's state of residence on the daily docket

## Existing design and content

- Current state 'add hearing day' modal available to admin users
<img src="https://user-images.githubusercontent.com/49729315/69758428-7c031a00-112d-11ea-8aad-3aa07a3f79fd.png" width=300 border=1>
- Current state Daily Docket for video and central hearings

## Checklist
- [ ] Research plan for testing with Hearing Coordinators, Judges, and representatives

**Comment by pshahVA** [comment]
@nicholer , a starting ticket for what we talked about last week.

**Comment by nicholer** [comment]
Migrated to Jira ([CASEFLOW-462](https://vajira.max.gov/browse/CASEFLOW-462))
