### ISSUE TITLE
Document Viewer | Update comment icon

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1282]
**Story**
As a user, I want to be able to see a clear comment icon or indicator on the document to annotate my note in a specific section. 

## Mockup 
![image](https://cloud.githubusercontent.com/assets/13420618/24181796/cb81c4fe-0e93-11e7-9107-a3f2fc7cf2db.png)

[SVG file](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20comment.svg)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)

## Acceptance Criteria
- If a user selects the` Add a comment `button while inside a document, the cursor changes to the comment icon, and the user can place the comment anywhere on the document page.
  - The cursor should be the comment icon when in a state of adding a comment. When in a document but not adding a comment, the cursor should be the default cursor icon. 
- When icon is clicked in the document, comment box should jump to top

**Comment by mdbenjam** [comment]
@gnakm Should AC 1 read:
When document reader is open, and we're in the state of adding a note, cursor should be the icon? Or is it just always the icon.

**Comment by gnakm** [comment]
@mdbenjam I think the cursor should be an icon one when it is in a state of adding a note. When it is not in adding state, it should just be the regular, default cursor.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF

Steps to Validate:
1. Go to a valid VACOLS ID for reader (with documents). 
2. Select a document out of the list
3. If there are no comments already, select "Add a Comment" button 
4. Select on the PDF viewer, where you would like to comment
5. Add copy in the Edit Comments section to the right of the PDF viewer.
6. Select Save
7. Validate the icon matches the UI found in the AC of this ticket. 

Screenshots: 
<img width="1340" alt="screen shot 2017-04-13 at 8 34 15 am" src="https://cloud.githubusercontent.com/assets/23038505/25004869/77d2b8ca-2024-11e7-9ae8-3e8f53a319e0.png">

**Comment by abbyraskin** [comment]
I will also move the clarification comments into the description.

The current AC said:
- When document reader is open, cursor should be the icon
- When icon is clicked in the document, comment box should jump to top

**Comment by kierachell** [comment]
The current functionality is still a bit misleading as commented in #1768 
Probably need more detail on the flow. So either update AC here or in #1768

**Comment by mdbenjam** [comment]
I think everything in this ticket has been addressed. Updating the AC in #1768, we'll use that ticket for further tracking.

**Comment by astewarttistatech** [comment]
**PASSED**

Note @abbyraskin the whole PDF viewer is highlighted upon clicking the "Add a Comment" button. I don't know if that was intended

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. While accessing the document viewer, click "Add a Comment" button.
2. Move the cursor to where the comment should be on the document reader (notice that the icon follows the cursor) 
3. Validate that this is the intended functionality and color. 

Screenshots:
![readercomments](https://cloud.githubusercontent.com/assets/23038505/25620422/5672d208-2f1c-11e7-93e9-d3bf8a4fc477.gif)
