### ISSUE TITLE
Document Viewer | Save and edit comment

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1283]
## Story
As a user, I want to be able to save or cancel a comment when I am adding a new comment or editing it. 

## Acceptance Criteria
- Verify that this box comes up when I am both adding a comment or editing a comment. 
- Verify that the outline of the box is hex #323a45 (USWDS gray-dark)
- Verify that there is a blinking cursor inside
- Verify that hitting cancel will go back to save position on page
- Verify that after sitting save, it positioned so that on the comment section, it is on the top of comments and position in the correct page order, so that you can scroll in that section to see other page. ( @mdbenjam if this is confusing, talk to me or @abbyraskin )
- Verify that Edit | Delete links are consistent with how link buttons will be implemented on the style guide https://github.com/department-of-veterans-affairs/caseflow/issues/1080
- Verify that there are 20px between cancel and save. 15px (vertically) between cancel/save and the textbox. And 20px (vertically) between cancel/save and the next comment.

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24372643/9a1d80de-12fc-11e7-8849-8a12fa2a3c22.png)

![image](https://cloud.githubusercontent.com/assets/13420618/24270828/12e672ea-0fed-11e7-98d5-405d6dbc66a1.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)

**Comment by mdbenjam** [comment]
This was mostly completed in: #1380

**Comment by mdbenjam** [comment]
@gnakm I don't think the stuff in #1089 works well for this. It's pretty off from this mock, and would push the cancel/save much further down. Thoughts?

**Comment by mdbenjam** [comment]
@gnakm Also, #4A4A4A is not a USWDS color. Should we use that anyway?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: Preprod
Browsers: FF and Chrome 

Steps to Validate: 
1. Go into reader and create a comment and validate the behavior based on AC

Screenshots:
![readercomment](https://cloud.githubusercontent.com/assets/23038505/25489071/c5376170-2b36-11e7-9849-ead4b558a506.gif)
