### ISSUE TITLE
Sign off from B3 on initial ETL schema

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12834]
Our initial version of an ETL schema is in production. We need B3 to kick the tires on the schema to see whether it will support their efforts.

## AC

- [ ] Populate production ETL data
- [ ] Provide URL to B3
- [x] Designate point of contact for B3 evaluation
- [ ] B3 acceptance

**Comment by D-L-Ware** [comment]
The appeals data working group has indicated that Thomas Boyda, technical, and Ted Mills, buisness, will be doing acceptance of the ETL structure.

**Comment by pkarman** [comment]
The Board decided not to use ODS. Excerpt of their email below.

> our team did review the data available in the Caseflow teams ODS schema and found several issues that include data extracts based on outdated SQL queries (resulting in incorrect data), row counts off on several tables and especially on the task table which was off by hundreds of tasks from the currently used Redshift “public” schema and finally the simple fact that we have no visibility into the process or implementation of the ODS ETL.  The ODS solution will not meet the Boards needs.
