### ISSUE TITLE
Bug: Error Handling for Null Address for Hearings

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12846]
## Description
When fetching hearing locations, we geomatch on vet's address. If that's nil, a `VaDotGovNullAddressError` is created and returned, but not raised. This means that error handling via `rescue` never gets triggered.

## Background/context/resources
- This showed up in a [Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6689/) in Slack, which shouldn't happen if error handling had worked correctly
- The error that showed up in Sentry was a `BGS::ShareError` with this: `TUX-20306 - An unexpected error was encountered`, but was due to earlier error handling not triggering

## Technical notes
- Error is triggered by the geomatch method, and should be getting handled in [rescue block](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/fetch_hearing_locations_for_veterans_job.rb#L42)
- Error is being created [in validations](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/va_dot_gov_address_validator/validations.rb#L42)
- Error is passed upwards, ultimately being added to the `geomatch_result` object
- Ultimately somewhere we should actually raise the error so normal `rescue` handling can take place

**Comment by jcq** [comment]
Closing due to it being invalid (see notes in Slack):
https://dsva.slack.com/archives/CHX8FMP28/p1575396642483500

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6689
Can the Sentry alert message include instruction to ignore this error, if that's desirable?
Otherwise, Bat Team is repeatedly spending time to investigate these Sentry alerts.
