### ISSUE TITLE
Bug: Validation Fails for PreRoutingFoiaColocatedTask

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12856]
## Description
We see an alert indicating that validation failed during task reassignment with this error: 
```Validation failed: Colocated subtype is not included in the list```

## Background/context/resources
- [Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6953/)
- [Code that performs validation](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/colocated_task.rb#L181)
- [PR that *might* be tangentially related](https://github.com/department-of-veterans-affairs/caseflow/pull/11904) (This handles a different circumstance, but implies that `PreRoutingFoiaColocatedTask` should often be handled in the same way that `PreRoutingColocatedTask` does.)

## Technical notes
Using `ColocatedTask.descendants` instead of `ColocatedTask.subclasses` would allow `PreRoutingFoiaColocatedTask` to pass that validation, but might have unintended consequences.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||
2 | ||||||
3 | |||||
5 | ||
8 | 
```
Estimated at a 2.

Lots of uncertainty. Might be easy if JCs solution works. Could have big knock-on affects. Unfamiliarity. This code has given us grief already. Could be a 1 if its as simple as making JC's suggested change and checking we can't create but can reassign. Might already be covered in existing tests.

**Notes**

The suggestion seems correctly scoped, so long as we leave the controller limitation in place to prevent the creation via the front end. This could be a good ticket for dogfooding as a group.

**Comment by hschallhorn** [comment]
## Context
Change routing of admin actions #11113 (Context behind automatic routing)
Skip VLJ support for schedule_hearing, missing_hearing_transcripts, translation, and foia colocated tasks #11467 (implementation of the above)
Properly handle old versions of automatically routed ColocatedTasks #11849 (context behind why "PreRoutingColocatedTasks" were created)
Create pre routed subclass for old style colocated tasks in production #11855 (implementation)
Allow PreRoutingColocatedTasks to be updated #11904 (solving a similar issue with some good ideas on manual testing)
