### ISSUE TITLE
Need to update AMA case QR code so that it replicates Legacy case QR code

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#12867]
## User story
User story: As a member of the Quality Review (QR) team at the Board, I need the AMA quality review monthly limit and selection probability to match was is currently set in Caseflow for Legacy, so that I can reliably receive 130+ AMA cases to review monthly, up to 137 case per month.

130+ of each, both capped at 137...code for legacy and AMA should be identical when this work is complete.

## Acceptance criteria
- [x] The monthly limit of Quality Reviews is set at 137
- [x] The Quality Review selection probability is set at 0.032

## Release notes
Caseflow now supports sending approximately 130+ AMA cases to QR for review monthly.

### Out of scope
1. Changes to legacy QR code.

### Background/context
It is believed that when AMA QR code was initially introduced to Caseflow in early 2019 that there would be a limited "ramp up" period during which AMA inventory would accumulate to levels sufficient enough to facilitate random selection and routing of AMA cases to the QR team at the Board for review at roughly 130+ cases per month, similar to what is currently coded for Legacy. After minimum AMA inventory was high enough to support sending 130+ monthly to QR, it was intended that AMA QR code would be updated to ensure 130+ would be sent each month thereafter. This work didn't happen. No change was made to the initial AMA QR code. As a result, the Board is currently seeing only 40+ cases be randomly selected and routed to QR for review monthly. This ticket is intended to correct this and bring the Board back into compliance with its QR policies ASAP. 

### Resources/other links
Legacy code lives here: https://github.com/department-of-veterans-affairs/caseflow/blob/555ac6727ea665985dd42a2f325cb498686c68f0/app/models/judge_case_review.rb

Current AMA code lives here: https://github.com/department-of-veterans-affairs/caseflow/blob/555ac6727ea665985dd42a2f325cb498686c68f0/app/models/quality_review_case_selector.rb

Relevant Slack thread: https://dsva.slack.com/archives/C2ZAMLK88/p1572561323019500

**Comment by lomky** [comment]
Relevant prior ticket #8320 & PR #8578

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 |
2 | |||||||||||||
3 | ||
5 |
8 |
```

Scoped at a 2.
Scope: This ticket is to adjust the AMA number and implement an AMA cap. We will file a followup to refactor the logic to actually match across Legacy/AMA on the implementation aspect.

Notes
We think the work here is just change the number in the code?

No we also need to implement a capping mechanism. 

We seem to have the cap implemented on Legacy, so we can mirror that.

**Comment by lomky** [comment]
@jimruggiero This is now merged and should be released tomorrow morning!
