### ISSUE TITLE
Add Status API as a Separate Component Called-out on  https://caseflow.statuspage.io/

### ISSUE THREAD

**Issue by D-L-Ware** [department-of-veterans-affairs/caseflow#12863]
## Description
 https://caseflow.statuspage.io/ 
Provides information on Caseflow, specifically calling out the operational status for Reader, Certification, Intake, Hearings, eFolder Express, Dispatch, and Queue.  Additionally, specific incidents are logged and notifications are posted about expected outages.  It would be helpful for some of our dependencies if Status API's operational status was called out as well, incidents specific to API be logged, and notification off expected outages be posted.    

## Background/context/resources
At some point in November Caseflow was down on the weekend for routine maintenance.  This included the Status API.  VA.gov's appeals tracker (one of VA.gov's more heavily trafficked features) is dependent on Status API.  As such, it went down as well.  Their oncall spent some time on the weekend trying to determine if this was a planned outage or not.  To prevent them being caught off guard we proposed they subscribe to  https://caseflow.statuspage.io/ but for this solution to have maximum benefit adding Status API as a specific call out is necessary.

**Comment by D-L-Ware** [comment]
@alisan16 and @pkarman I assigned this to myself but peter suggested one of you could assist me with actually adding Status API to  https://caseflow.statuspage.io/.

**Comment by pkarman** [comment]
I didn't know how to do it till I looked. The admin page is https://manage.statuspage.io/pages/g6mh29rqlfqy/incidents

I went ahead and added the "Caseflow - Status API" component via the "Components" nav menu option on the left.
