### ISSUE TITLE
Caseflow::Error::AttorneyJudgeCheckoutError: Appeal is missing decision issues

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12864]
## Description
A POST to `/case_reviews/501156/complete` yielded this error:
```Caseflow::Error::AttorneyJudgeCheckoutError: Appeal is missing decision issues```

## Background/context/resources
- [Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6987/)

**Comment by jcq** [comment]
## Additional alerts
- [Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7055/)

**Comment by pkarman** [comment]
This is happening frequently. Code is here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/issue_updater.rb#L66

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6987

**Comment by yoomlam** [comment]
```
Caseflow::Error::AttorneyJudgeCheckoutError: Caseflow::Error::AttorneyJudgeCheckoutError
  from app/models/concerns/issue_updater.rb:69:in `fail_if_appeal_has_no_decision_issues!'
  from app/models/concerns/issue_updater.rb:13:in `update_issue_dispositions_in_caseflow!'
  from app/models/attorney_case_review.rb:38:in `update_in_caseflow!'
  from app/models/attorney_case_review.rb:74:in `block in complete'
  from app/models/application_record.rb:29:in `block (2 levels) in multi_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
```
<img width="790" alt="image" src="https://user-images.githubusercontent.com/55255674/84420984-82944300-abe0-11ea-9f09-d531922857f2.png">

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||
3 | ||||||||
5 | 
8 | 
```

If this is indicating a user-addressable error: 
 - If this is alerting both the user and us, we should silence this alert to us.
 - If this isn't telling the user, or isn't telling the user enough to fix the issue, then we need to address that, and then silence the alert to us.
If its a bug in the code, fix that!

#### Why 1?
* 

#### Why 2?
* Might be simple as silencing an extraneous alert

#### Why 3?
* Investigation into what is causing this
* Should this be caught by another validation somewhere or is this error showing in the right place?
