### ISSUE TITLE
Header | Rename "Caseflow Reader" and link to Documents List page

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1287]
Currently, Caseflow Decision links to the Certification Help page. Rename Caseflow Reader and link to the Documents List page for the active case.

## Acceptance criteria
- [ ] Verify that you are you using the Reader logo for the header
You can find the [reader logo in SVG here](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Logo/Caseflow%20Logo%20-%20Reader.svg)
- [ ] Verify that header says `Caseflow Reader`
- [ ] Verify that Veteran name and ID is in font size 19 px and 25 px from Reader
- [ ] Verify that we are following the directions for the header that will soon be in the living style guide:
https://github.com/department-of-veterans-affairs/caseflow/issues/1086

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24620358/694bfb6a-186b-11e7-9be2-181c71d332e9.png)

**Comment by mdbenjam** [comment]
@gnakm I'd like to add the caseflow logo to this as well. Do you have that SVG for me to use?

**Comment by gnakm** [comment]
@mdbenjam I updated the above with link to SVG!

**Comment by astewarttistatech** [comment]
UAT VACOLS IDs are not working in the new UAT link. https://certification.cf.uat.ds.va.gov/reader/appeal/<vacolsid>/documents. Time boxing.

**Comment by astewarttistatech** [comment]
**PASSED**

Tested in: UAT
Browser: FF

Steps to Validate: 
1. Find a valid VACOLS ID and add it to the referenced link above, in between the two forward slashes with space between them. 
2. Validate the UI of the header appears as the AC and mock described. 

Screenshots: 

<img width="1412" alt="screen shot 2017-04-12 at 2 51 46 pm" src="https://cloud.githubusercontent.com/assets/23038505/25004345/efec71c8-2021-11e7-95f0-24a40299c779.png">
