### ISSUE TITLE
Stuck decision issue sync jobs

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12894]
We continue to have 20k+ RequestIssue jobs that cannot sync decision issues. In the past these have required some manual data backfill coordination.

Since we are turning off the alerts about decision issue sync in #12792 this ticket represents the task of identifying any underlying issues between BGS and Caseflow and determining how best to un-stick these RequestIssue jobs.

In the past @pkarman has manually restarted these expired RequestIssue jobs manually in order to catch any decision issues that may have appeared after the initial 30 day window of attempts had passed. That approach does not ultimately work (it's not simply a timing issue, as the number of stuck jobs 90+ days out illustrates).

See Expired Jobs daily alert e.g. https://dsva.slack.com/archives/CN3FQR4A1/p1575626437015500

**Comment by jimruggiero** [comment]
@leikkisa @msj0nes Can we discuss possible options to address this? As we prep for PI planning, I'd like to better understand the work involved for Caseflow and BGS.
