### ISSUE TITLE
Stress test nonrating request issue decision date validation

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12913]
## Description
We had a nonrating issue get saved without a decision date.  This ticket is to stress test the validation, to see if you can manage to save a nonrating request issue where the decision date doesn't get saved.

To do this, start a decision review and add several nonrating request issues where you try creating them with various types of invalid decision dates. They will get saved once you establish the claim.

Check database for nil decision dates on request issues.

## Background/context/resources
Here is the related Slack thread, which came from a batteam request:
https://dsva.slack.com/archives/C54QCEHAL/p1575918470399700

## Technical notes
This can be done locally or in UAT.  Some things to try:
- A decision date where the month is 0 or 13 or a non-month number
- A decision date where the day and year is not normal (such as 19 instead of 2019)
- A decision date that is not populated
- A decision date that is partially populated
- A decision date in the future
- Typing in the decision date versus using the date picker
- Check if YMD is getting confused with MDY, may be due to browser OS settings

After establishing the claim, check if the decision_date on any of them is nil.

**Comment by leikkisa** [comment]
We should add some error handling to prevent request issues from being saved without a decision date.

**Comment by nanotone** [comment]
I'm going to call this ticket done without any code changes, and create a new ticket for future related engineering work.

With guidance from @jcq and @leikkisa, I stress-tested the date picker in the non-rating issue UI, which uses the browser implementation of `<input type="date">`, and am quite certain that any modern version of Chrome, regardless of unusual OS locale settings, will restrict output date values to
- valid `yyyy-mm-dd` strings, correctly excluding dates like non-existent Feb 29's, and
- empty strings, when the picked date is invalid or incomplete.

In the latter case, the `Add this issue` button is disabled to prevent adding the issue, and I have stress-tested this coupling as well. However, this is not a guarantee that the frontend (in the past, present, and future) is incapable of submitting an empty decision date to the endpoint.

Note that the date-picker UI was merged on 2019-10-17 (#12363) but there have been more recent non-rating issues without decision dates:

- `RequestIssue.nonrating.where(decision_date: nil)` ➡️ 5 records, created 2019-09-25 to 2019-11-15
- `RequestIssue.nonrating.active.where(decision_date: nil)` ➡️ 1 record, created 2019-10-22

Thus, to more closely guard against this situation, I propose a backend change to add ActiveRecord validation, which will also be (mostly) effective against nils from other backend code or Rails console accidents.
