### ISSUE TITLE
Update copy for legacy issue opt-in selection

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12917]
## User or job story
As a claims assistant, when I am creating an intake, I sometimes miss checking the option "Did they agree to withdraw their issues from the legacy system?".  It would be clearer what this selection is for if the label were more closely matched to the form.

## Acceptance criteria
- [ ] Update the copy for this selection to `Did the Veteran check the "OPT-IN from SOC/SSOC" box on the form?`

## Release notes
The intake field "Did they agree to withdraw their issues from the legacy system?" has been re-labeled to "Did the Veteran check the "OPT-IN from SOC/SSOC" box on the form?" in order to reduce errors.

### Designs

New copy:
Did the Veteran check the "OPT-IN from SOC/SSOC" box on the form?

Current design:
![image (14).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/6bd31470-33b6-4f47-9b07-ec4baba741b8)

### Technical notes
See the `caseflow/client/app/intake/components/LegacyOptInApproved.jsx` file.

**Comment by jimruggiero** [comment]
@Sjones352 can you provide a screenshot with the new copy? 
@msj0nes Please copy/paste the release note into Headway with the new screenshot Sandra provides.

**Comment by Sjones352** [comment]
<img width="1045" alt="Screen Shot 2019-12-17 at 11 02 21 PM" src="https://user-images.githubusercontent.com/23080951/71055011-15688f00-2122-11ea-800c-b3d7d4a5494b.png">
