### ISSUE TITLE
Remove Congressional Inquiries as a Blocking Task 

### ISSUE THREAD

**Issue by D-L-Ware** [department-of-veterans-affairs/caseflow#12920]
## Description
As a user, I need Congressional Inquiry tasks to not block case distribution or other tasks.  

## Background/context/resources
Congressional Inquiries are requests from a Congressperson or Senator on the status of a constituents claim.  A decision by the Board is actually a response to that inquiry, therefore, Congressional Inquiry tasks need not be blocking tasks as there is nothing legally or procedurally that prevents VA from deciding an appeal while a Congressional Inquiry is outstanding.    

## Technical notes
Tasks that prevent case distribution to judges
Blocking Mail Tasks:
• Congressional Inquiries
• FOIA request
• Privacy act request
• Privacy complaint
• Power of attorney related
• Extension request
• Hearing related

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||
2 | |||||||
3 | |
5 | 
8 | 
```

Delete the function `blocking?` in this mail subtask
Query all open tasks of this type, grab their root task, update all.

Do open mail tasks block dispatch? No.

#### Why 1?
* two easy changes

#### Why 2?
* One line change

#### Why 3?
* Data cleanup in prod

**Comment by hschallhorn** [comment]
Will be completed in #14057
