### ISSUE TITLE
Display Veteran's state of residence on the daily docket

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#12927]
## User story
As an RO Coordinator, I need to be able to quickly identify veterans that are coming from out of state (or were not originally assigned to this RO at intake time) are on my docket. I need to do this so that I can make sure that the out-of-state representative is notified and coordinated with.

## Related ticket
#12648 - Display Veteran's state of residence on Schedule Veterans screen

**Comment by pshahVA** [comment]
@nicholer, I would like to include this in the sprint ending 2/7,  We probably need a small screenshot or design for this.

**Comment by nicholer** [comment]
@pshahVA Design hasn't begun on this ticket yet, so moving to the Design Backlog. It's the other half of displaying Veteran state of residence (related ticket: #12648) - this time on the Daily Docket for representatives and RO Coordinators.

We can discuss where this work should fall in priority.

**Comment by pkarman** [comment]
tech note: we don't currently cache state from BGS in our db, so unless we are already making a BGS call for this endpoint, this will either (a) have a performance impact or (b) require caching that value in our db.

**Comment by chandracarney** [comment]
Closing now that Veterans are matched in-state based on new geo-matching criteria via #14519
