### ISSUE TITLE
Consolidate QR Selection and Limit Code

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12929]
## Description

Refactor the code around Quality Review selection & limit to use shared logic.

## Background/context/resources

In the past we handled Quality Review selection differently for AMA & Legacy appeals. (see  #8320 & PR #8578) We have since updated AMA behavior to match legacy (see #12867 & PR #12915) and do not foresee a future where we want them to behave differently in the future.

Right now [QualityReviewCaseSelector](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/quality_review_case_selector.rb) and [JudgeCaseReview](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/judge_case_review.rb) implement the same selection and cap logic for AMA and Legacy, respectively.

## Stretch / Future work

Right now we have the percentage set based on [an educated calculation to get steady QR throughout the month](https://github.com/department-of-veterans-affairs/caseflow/issues/6407#issuecomment-409271892) without hitting it too early.

It would be lovely if this were user adjustable, such that the admins for Quality Review could adjust this percentage themselves, in an interface that would update with realistic numbers based on real past case numbers.

**Comment by jimruggiero** [comment]
As of today (12/18) I received another request from the Board (specifically Josh Freeman) to again change the AMA probability from .032 to .188, and change the cap/ceiling limit from 137 to 133; official prioritization and approval by Board leadership is pending. Please do not take action on this ticket until I give a green light.
