### ISSUE TITLE
Litigatation Support Team has lost ability to create tasks. 

### ISSUE THREAD

**Issue by kevmo** [department-of-veterans-affairs/caseflow#12935]
## Description

 The litigation team is [reporting that they have lost the ability to add tasks](https://dsva.slack.com/archives/CHX8FMP28/p1575663281058100). 

This ticket exists to re-enable this functionality. 

## Background/context/resources

 Lit Support reports that they lost this ability on 12/2 or 12/3.

**Comment by lomky** [comment]
#12938
