### ISSUE TITLE
Improve performance of veterans list on /test/users

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#12934]
## Description
The `/test/users` page contains a list of all veterans by file number and a description of which artifacts are available for each. However, this causes a pretty significant performance hit (adding 10-20 seconds in local dev) on a page with many other uses, e.g. switching users, toggling features.

## Acceptance criteria
- [ ] Make a `/test/data` page and move the list of veterans to that page
  - Note: engineers choice whether to migrate to another Rails view or handle via front-end routing
- [ ] Link to the test data page from the test users page
- [ ] Check in with Training, announce in appeals-engineering

## Out of scope
- Improving the query performance
- Asynchronously fetching the data

## Background/context/resources
Original Github issue: #12862 and the PR that implemented it: #12895 

## Technical notes
In his initial review, @jcq suggested a few approaches:
1. Move the veterans list to a separate page. This is probably the lowest-hanging fruit. (Check with the Training team). Ideal to use a front-end route.
2. Add pagination to the veterans list. See `PaginationConcern` and note that this would be straightforward if the veterans list had its own controller.
3. Kick of asynchronously on the same page

Additionally, consider that the biggest performance hit comes from the view making eight
```
SELECT COUNT(*) ... WHERE veteran_file_number=X
```
queries for _each_ veteran. As an alternative (or supplement) to pagination, consider restructuring these queries to use only eight
```
SELECT COUNT(*),veteran_file_number ... GROUP BY veteran_file_number
```
queries for the entire page.

**Comment by pkarman** [comment]
try

`touch tmp/caching-dev.txt`

to fix. there's already caching support.

**Comment by lomky** [comment]
[`client/app/queue/OrganizationUsers.jsx`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/OrganizationUsers.jsx#L262) uses the same component (SearchableDropdown) for the same user name/cssId discovery functionality, but in a much faster way
