### ISSUE TITLE
[Sentry Alert] BvaDispatchTaskCountMismatch: Expected 1 BvaDispatchTask received 0

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12931]
## Description
Error:
```Caseflow::Error::BvaDispatchTaskCountMismatch: Expected 1 BvaDispatchTask received 0 tasks for appeal 9550, user 2142```

Looks like the task assigned to the user in question (2142) was cancelled, and another one assigned to user 2120 was completed:

```Appeal 9550 [assigned_to_type, assigned_to_id, status]
└── RootTask Organization, 2, completed
    ├── TrackVeteranTask Organization, 226, completed
    ├── DistributionTask Organization, 2, completed
    │   └── InformalHearingPresentationTask Organization, 226, cancelled
    ├── JudgeAssignTask User, 1612, completed
    ├── JudgeDecisionReviewTask User, 1612, completed
    │   └── AttorneyTask User, 894, completed
    └── BvaDispatchTask Organization, 19, completed
        ├── BvaDispatchTask User, 2142, cancelled
        └── BvaDispatchTask User, 2120, completed
```

## Background/context/resources
- [Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7307/)
- [Possibly related PR](https://github.com/department-of-veterans-affairs/caseflow/pull/12183)

**Comment by ferristseng** [comment]
Happens here too with a similar task tree: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7307/?referrer=webhooks_plugin

```
Appeal 13356 [assigned_to_id, status]
└── RootTask 2, completed
    ├── TrackVeteranTask 295, completed
    ├── DistributionTask 2, completed
    ├── JudgeAssignTask 538, completed
    ├── JudgeDecisionReviewTask 538, completed
    │   └── AttorneyTask 2083, completed
    └── BvaDispatchTask 19, completed
        ├── BvaDispatchTask 10140, cancelled
        └── BvaDispatchTask 2086, completed
```

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||||||
3 | |||||
5 | 
8 | 
```

Looks like this happens after reassigning a bva dispatch task. We're calling `where` on the old assigned user rather than the new assignee

Kat: Not to be confused with `Dispatch::Task`s!!!

#### Why 1?
* 

#### Why 2?
* Spin up on BvaDispatch tasks and logic around why this validation exists
