### ISSUE TITLE
Stop blocking case distribution when a single DistributedCase fails. 

### ISSUE THREAD

**Issue by kevmo** [department-of-veterans-affairs/caseflow#12932]
## Description

All case distribution fails whenever a single attempt to create a new `DistributedCase` model fails.  These new models fail to be created due to a unique constraint on the `case_id` column in the `distributed_cases` table.

Case distribution should not generally fail in the event that a single model creation attempt fails. At the same time, the development team needs to be made aware of any fails attempts, as a case will otherwise be stalled. 

## Background/context/resources
While on Bat Team, we had an urgent error where case distribution was broken for all judges.  Case distribution was broken because [one case](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7549/) the system tried to distribute had already been previously distributed. Redistribution failed because: `DistributedCase`s enforce a unique restraint on their `case_id` field, which is formulaically generated based on appeal data. In the event that a case is distributed more than once, this causes case distribution to break [and no cases get distributed](https://dsva.slack.com/archives/CHX8FMP28/p1575991391112000).

[This is been a known problem ](https://github.com/department-of-veterans-affairs/caseflow/wiki/Bat-Team#if-an-automatic-case-distribution-job-fails-to-run-and-errors-with-activerecordrecordnotunique-how-do-i-fix-it) and was [recently resolved for legacy appeals](https://github.com/department-of-veterans-affairs/caseflow/pull/12190).  It appears that a fix may also be needed for AMA appeals. 

## Acceptance Criteria 
- [x] Case distribution should not fail in the event that a single `DistributedCase` instantiation fails. 
- [x] Development team is still reliably informed of the failure, so that the appeal can be fixed and the case can proceed. 

## Questions
There may be design questions about how to exactly implement this. For example, if a judge normally gets 10 cases, and 1 fails when its turn to be distributed comes up: Do we allocate 10 cases to the judge?  Or do we give the judge 9?  If we give the judge 10, then the judge will be at capacity, and that case that failed to be distributed may be further delayed.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |||
3 | ||||||||||
5 | ||
8 | 
```
Estimated at a 3.

Might be a 2 if all we have to do is catch the error and let it continue. Might be a 5 for code unfamiliarity and uncertainty around the code. Testing might be gross.

**Notes**

We're thinking we distribute the judge 10 cases rather than shorting one. This case is already being delayed by the error, whether the judge gets a tenth case other than it isn't additionally delaying.

Should we show the error happening to the user? Probably not, its not actionable for them.

**Comment by hschallhorn** [comment]
closed in #13019
