### ISSUE TITLE
Upgrade Karma

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12944]
## Description
While we ultimately may want to move ourselves to Jest for frontend testing, we should keep Karma updated until such time as we migrate. 

## Background/context/resources
- Currently running Karma v1.7.x
- Current version of Karma is v4.4.x
- Old version of Karma is responsible for [security vulnerability](https://github.com/department-of-veterans-affairs/caseflow/network/alert/client/yarn.lock/parsejson/open) of `parsejson` package (subdependency)

**Comment by meckila-navapbc** [comment]
Resolved in #16347
