### ISSUE TITLE
Add "Job note with message" method

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12947]
## Description
As an engineer, I often like to add job notes from the console when reviewing stuck claims (instead of in the Caseflow UI).  Adding job notes from here doesn't add the Inbox message though.  It'd be good to make this available through a non-controller method, such as in the JobNote model or a workflow.

## Technical notes
See the AsyncableJobController add_note for current code on how to add a job note with an inbox message.

**Comment by leikkisa** [comment]
Open to conversation on whether we should do this if there's no place we're calling it in the code (I can update my personal script). 

This can potentially be used in the future for handling known upstream errors, I think that depends on whether we need to individually add cases to YourIT tickets, and it'd be good to ask Peter's opinion.

**Comment by msj0nes** [comment]
@nanotone Is this issue fully complete? If so please close the ticket.
