### ISSUE TITLE
Do not show inactive users as options for task assignee

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12949]
When a user sees a selection of other users to assign a task to, they should not see inactive users as an option.

## AC
- [ ] Limit available options of task assignees to active users on the front end

## Notes
[Here's some possible context](https://github.com/department-of-veterans-affairs/caseflow/issues/11631#issuecomment-522193687)

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |||
3 | ||||||||||
5 | ||
8 | 
```
Estimated at a 3. 

Might be a 5 as it will take extensive rspec testing & manual testing, and we're unsure of all the places we have to implement this. Concerned there are places that if we add the active scope, we'll affect other places we actually wanted all the users.

If we get into this and we find out there are huge knock on effects on many unrelated places, maybe we need to refactor the behavior into better isolated code. Might end up needed a new route (one active, one all), and will have to decide which to leave the current as and which to implement the new route (lift to update vs lift to maintain going forward).

A 2 is optimistic, but possible. It will still take a lot of testing even if the implementation is straightfoward.

**Notes**

Limit the round robin assignee pool to the active scope for users.
Limit any manual task assignment list to the list of active users.

Might be able to make this toggle in one place at the user controller, but maybe there are other places. There is some digging and research in this task to confirm we have them all. Some new tests will be needed.

**Comment by kevmo** [comment]
Sticky spots so far:
* Attorneys are now pulled using judge roles - causes internal error when seeking to get user [lack of parity - we are not removing judge team roles when a user becomes inactive]
