### ISSUE TITLE
Contested decisions on unidentified issues should go on rating EPs

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12952]
## Description
When investigating whether there are places in the code where rating issues were being categorized as nonrating issues for EP establishment, we found that contested decision issues on unidentified request issues are not being categorized as rating issues.

## Acceptance criteria
- [ ] If an unidentified issue gets a decision issue, and that decision issue gets contested and added to an End Product, it should get added to a rating end product

## Background/context/resources

For the sake of EP establishment, we've been considering them rating issues when they're originally added since they're most likely to be rating issues.  They shouldn't be getting decision issues, but that's another issue to investigate.

## Technical notes
Check out the code in the DecisionIssue and RequestIssue models for rating?  For the case we investigated, the decision issue returned true for rating?, but the RequestIssue model was not looking at the contested_decision_issue.

**Comment by dwhitted** [comment]
Checking in the status this ticket associated with INC8822007 Where are you with the customer, have they accepted this solution ?

**Comment by tomas-nava** [comment]
@dwhitted work on this ticket is not yet complete, and will not be merged until after the code freeze has lifted.

**Comment by msj0nes** [comment]
# YourIT Tickets Impacted 
 
YourIT Ticket  Number | Date Ticket Created | Case Details URL 
-- | -- | -- 
INC0000000 | 00/00/00 |   Add case details page URL here
