### ISSUE TITLE
Virtual hearings type listed incorrectly on the daily docket

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12968]
Error from UAT
When there is a daily docket with only one virtual hearing it is still showing at the hearing type as Video/Virtual.
https://appeals.cf.uat.ds.va.gov/hearings/schedule/docket/10
![image](https://user-images.githubusercontent.com/49729315/70826851-ecf53380-1db5-11ea-84d4-a1ae7f8a16f6.png)

**Comment by nicholer** [comment]
@pshahVA Should this ticket be moved to Ready for dev, since it's a bug from UAT that doesn't need additional design?

**Comment by pshahVA** [comment]
Did we miss assigning this one? Thanks!  I'll put it in ready for Dev.

**Comment by ferristseng** [comment]
This should be fixed now, but reopen if it pops up again
