### ISSUE TITLE
Intake | Remanded issues should not be contestable

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12967]
## Description
When an issue gets a disposition of "remanded" (for Appeals), or a DTA error (for Higher Level Reviews), those are internal, meaning they aren't final decisions sent back to the veteran, but the decision is to send them back for another review. These are automatically contested on Supplemental Claims.  These issues should not show up as contestable on regular reviews that are initiated from veteran forms.

We would like to show them as options on remand supplemental claims, in case there was a problem in the decision tracking system for automatically generated claims. For example, we have a case where we didn't detect a DTA decision because it was not connected to a request issue.

## Acceptance criteria
- [ ] Decision issues with a disposition of "remanded" or one of the "DTA error" dispositions, or "Difference of Opinion" are not included in contestable issues unless the decision review is a remand supplemental claim
- [ ] These issues _are_ included in the list of contestable issues on remand supplemental claims

## Technical notes
If an SC is a remand supplemental claim, `sc.decision_review_remanded` will be present.

See `ContestableIssueGenerator.contestable_decision_issues`. Currently this prevents decision issues from being contested on remand supplemental claims altogether.  Instead we want to hide remand and DTA issues from regular reviews, and show them for remand SCs.

## Background/context/resources

Related Slack threads:
https://dsva.slack.com/archives/CFBLH2LR4/p1586872950120200
https://dsva.slack.com/archives/CHX8FMP28/p1575397123484000
https://dsva.slack.com/archives/C54QCEHAL/p1585692311101500
https://dsva.slack.com/archives/CHX8FMP28/p1576261336012400?thread_ts=1576176736.208200&cid=CHX8FMP28

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1687
