### ISSUE TITLE
VBMS API Update to Support Correct Display of Labels in Reader

### ISSUE THREAD

**Issue by D-L-Ware** [department-of-veterans-affairs/caseflow#12979]
## Description
As a user, I would like to see the same label displayed for a document in Reader as users see in VBMS.  For the most part this already exists, however, for some recently added document types (specifically AMA documents) they currently default to 'Other' label in Reader despite having a more detailed label in VBMS.

## Background
Caseflow Reader pulls all documents from VBMS.  Each document has a label in VBMS, such as 'Statement of the Case', 'Notice of Disagreement', 'Rating Decision', etc.  This information comes through the API with VBMS.  Most document labels are pulled but not all are.  Reader displays the label 'Other' whenever it encounters a document for which a label is not pulled.  

When it comes to things that currently display 'Other', of particular importance is AMA documents such as the VA Form 20-0995, VA Form 20-0996, and VA Form 10182.  These documents where added post Reader's launch, hence, I believe, why they all currently display other in Reader while displaying a more detailed name in VBMS.

**Comment by D-L-Ware** [comment]
This issue came to the attention of Troy Hamilton and he had this suggestion:

VBMS and the other VBA systems update their document type business data on a quarterly (major release) basis.  This artifact is updated by OBPI a few weeks prior to the beginning of a release with an effective date of the changes that matches the release date.  They do out of cycle changes also but that is limited to emergency cases which have only occurred a couple of times in the last 7 years.  I would recommend that Caseflow include this periodic update of document types into their Program Increment planning and reserve an LOE for it to ensure Caseflow stays in synch with VBMS and other systems that use the e-Folder repository.

**Comment by kevmo** [comment]
Anything Caseflow doesn't recognize is "other" by default.  Supposedly exhaustive list of categories exists in email (cc @jimruggiero) and will be attached to this  ticket. 

No new labels are expected anytime soon (list was made during AMA) - this is about bringing Caseflow into compliance.

**Comment by kevmo** [comment]
# Estimation: 3

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||
2 | ||||
3 | |||||
5 | |
8 | 

Why this could  be a 5? New product - need to get an understanding of the code. Why a 1? Could be just adding some strings to an array/list somewhere.

**Comment by araposo-tistatech** [comment]
Attached is the list of document types that need to be added to Reader. 

[Copy of 64827- Master Document Type Categories R18.1.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/4250606/Copy.of.64827-.Master.Document.Type.Categories.R18.1.xlsx)

**Comment by hschallhorn** [comment]
[Where these types are pulled in in Caseflow](https://github.com/department-of-veterans-affairs/caseflow/blob/43562ed9e75b14c6f949802521da9df6a4214c2b/app/models/document.rb#L91)!
[Where we pull these doc names from](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/app/models/caseflow/document_types.rb)!
These seem to match `<DCMNT_TYPE_LUP_ID> => <DESCRIPTION_TXT>` in `TYPES`
[Example of a PR on how to update this doc](https://github.com/department-of-veterans-affairs/caseflow-commons/commit/0ed68fbda33f72d0c5e0b614ca5a34711652c785#diff-674fb94e2a36b7875f254d84d671d133)!

**Comment by ajspotts** [comment]
> Attached is the list of document types that need to be added to Reader.
> 
> [Copy of 64827- Master Document Type Categories R18.1.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/4250606/Copy.of.64827-.Master.Document.Type.Categories.R18.1.xlsx)

@araposo-tistatech just double checking we want Caseflow to recognize all of the document types listed in this spreadsheet correct? We currently have approx. 500 of them that we recognize so the list you provided just about doubles that amount

**Comment by hschallhorn** [comment]
I assume it's all but the ones that have not been deleted (no strikethrough), but I'll let Ann-Marie confirm

**Comment by araposo-tistatech** [comment]
@ajspotts confirming Caseflow should be able to recognize all the document types

**Comment by ajspotts** [comment]
@araposo-tistatech in the case of encountering a doc type that is in our code but not listed in the spreadsheet (not a strikethrough) what would be your suggestion in terms of leaving or removing it?

**Comment by araposo-tistatech** [comment]
@ajspotts I would suggest leaving it for now and pulling a list of the current documents we have in the system. If we can pull a list I should be able to request if any should be removed during future document updates (as VBMS and the other VBA systems update are updated quarterly).

**Comment by ajspotts** [comment]
@araposo-tistatech This one is just about ready to go, however do you happen to know if any of the labels we added need to also be added to the "Case Summary Types" [here](https://github.com/department-of-veterans-affairs/caseflow/blob/23ef0349257a7d682160436dd2d62e366ec37ef0/app/models/document.rb#L41) similarly to how it was previously done in [this](https://github.com/department-of-veterans-affairs/caseflow/pull/5449/files) PR?

**Comment by ajspotts** [comment]
> @araposo-tistatech This one is just about ready to go, however do you happen to know if any of the labels we added need to also be added to the "Case Summary Types" [here](https://github.com/department-of-veterans-affairs/caseflow/blob/23ef0349257a7d682160436dd2d62e366ec37ef0/app/models/document.rb#L41) similarly to how it was previously done in [this](https://github.com/department-of-veterans-affairs/caseflow/pull/5449/files) PR?

After conferring with @hschallhorn since this wasn't a direct ask of the issue going to overlook for now, doing a follow-up PR to make the change if necessary will be a small fix.
