### ISSUE TITLE
Fix RecordInvalid: Validation failed: Assigned to has to be an attorney

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12982]
## Description

When judge assigns case to user, validation error `Assigned to has to be an attorney` occurs. Judge should not be given an option to choose an invalid user (e.g., a non-attorney).

When `app/controllers/judge_assign_tasks_controller.rb in block (2 levels) in tasks at line 17` is called, `app/workflows/attorney_task_creator.rb in tasks at line 20` raises validation error: `ActiveRecord::RecordInvalid: Validation failed: Assigned to has to be an attorney`

## Background/context/resources
During Bat Teaming, got msg: https://dsva.slack.com/archives/C4JECDLSE/p1576502206014100

Sentry alerts: 
* https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7329/
* https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7547/

## AC
- [ ] Only attys are listed on the judge assign page
- [ ] Jim notified for release notes

**Comment by jcq** [comment]
This occurred again:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7547/?referrer=webhooks_plugin

At @hschallhorn recommendation, I set Sentry to ignore that alert for a couple of months in order to give time to address this ticket.

**Comment by hschallhorn** [comment]
This list of assignable users should also include acting judges (all attorneys, not all "non judges"). `AttorneyRepository.find_all_attorneys` does not solve this as it also returns all judges. We could write a new function in AttorneyRepository to solve this without pinging vacols for every user

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |
2 | |||||||||||||
3 | |
5 | 
8 |  
```
Could just be a different function call. May need a good amount of testing. Release notes to remind users they can only assign to attorneys from the assign page and to reassign to another judge from the case details screen (include screenshots). Need to ensure the fact that end point only returns attorneys does not impact other caseflow functions.

**Comment by yoomlam** [comment]
Any ideas on how to replicate this problem?
I'm assuming the problem occurs on the Assign Cases page when http://localhost:3000/queue/3/assign is being requested, but I can't replicate the problem where non-attorneys are listed in the dropdown.
In https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/users_controller.rb#L47, only the judge's attorneys are returned as long as the `judge_id` parameter is included in the URL, which it is: `/users?role=Attorney&judge_id=3`.

1. Is there a scenario where the `judge_id` parameter is not provided, in the context of replicating the ticket's described problem?

Is there maybe another page that calls `judge_assign_tasks_controller.rb` and doesn't provide the `judge_id`?  
[`initialAssignTasksToUser`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueActions.js#L419) is used by `UnassignedCasesPage.jsx` (which is used in the Assign Cases page that I tested above) and `AssignToAttorneyModalView.jsx`, which is referenced [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueApp.jsx#L207) and activated for URLs matching `/queue/appeals/:appealId/tasks/:taskId/${TASK_ACTIONS.ASSIGN_TO_ATTORNEY.value}` or specifically `/queue/appeals/:appealId/tasks/:taskId/modal/assign_to_attorney` (see [QueueApp](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueApp.jsx#L365) and [ASSIGN_TO_ATTORNEY](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/TASK_ACTIONS.json#L17)).
When I search for that URL (and its substrings), I can't find pages that use the `AssignToAttorneyModalView` component (in order to find other pages that call `judge_assign_tasks_controller.rb`).

2. Where is the `AssignToAttorneyModalView` component being used?

**Comment by hschallhorn** [comment]
I assume this is from either a judge being on another judge's judge team or the user is selecting a judge from the "Other" dropdown. If the user selects "Other", another dropdown of all attorneys and judges pops up.

**Comment by yoomlam** [comment]
Thanks Hunter! An answer to question 3 would also be helpful to check how my changes affect other components.

**Comment by yoomlam** [comment]
@hschallhorn Could `AttorneyRepository.find_all_attorneys - JudgeRepository.find_all_judges` work to populate the "Other" dropdown of attorneys on the Case Assign page?
```
[18] pry(main)> AttorneyRepository.find_all_attorneys.size
=> 845
[19] pry(main)> JudgeRepository.find_all_judges.size
=> 251
nonjudgeattys=(AttorneyRepository.find_all_attorneys - JudgeRepository.find_all_judges)
nonjudgeattys.size
[22] pry(main)> nonjudgeattys.size
=> 623
[23] pry(main)> 845 - 251
=> 594
```

**Comment by hschallhorn** [comment]
3. Occurs from the case details page. It is the modal that pops up after selecting Assign to attorney
