### ISSUE TITLE
Handle undefined tasks in app/queue/OrganizationQueue.jsx

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12988]
## Description

In `app/queue/OrganizationQueue.jsx`, an error occurs when `tasks` is `undefined`. Handle this case better: `OrganizationQueue in length error: Cannot read property 'length' of undefined`

Hunter noted:
> I think we should be more concerned with the fact that tasks is undefined and finding the root cause of that, rather than finding a way to not throw the error. This is a pretty good indication that something is not right on the front end

and
> I’m seeing that `GET /organizations/hearing-admin/tasks` returned a 403. That’s probably why tasks is empty or undefined. We probably aren’t handling the error as well as we should

## Background/context/resources

During Bat Teaming, Sentry alert occurred: https://dsva.slack.com/archives/C4JECDLSE/p1576500167013900

Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7372/

**Comment by hschallhorn** [comment]
None seen in 6 mo
