### ISSUE TITLE
Route Claim: Send Email Notification + VBMS Note

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1299]
Route Claim: Send Email Notification + VBMS Note

Add a VBMS Note to Full Grant claims that we email to ROs.

**Comment by lakohl** [comment]
@abbyraskin Should we do this for all emailed claims or only some? If the latter, could you suggest which ones?

Also trying to thing about what would be the best order of the two actions. Email first, so they really do it? then VBMS Note? Will discuss with devs as well.

**Comment by shanear** [comment]
This has be slated for ARC Dispatch V2

**Comment by gnakm** [comment]
@lakohl Can we close this?

**Comment by lakohl** [comment]
This is still a desire, but not currently in our near term plans. closing.
