### ISSUE TITLE
Investigation: Missing associated ratings

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12997]
## Description

When a rating request issue is processed in VBMS, it gets a contention on an end product.  When it gets decided, the contention gets a disposition, and a new rating should get created that is associated to that end product.  That rating should also have a rating issue that is associated to the contention.

Once we have both the disposition and new rating issue, we create a Caseflow decision issue.  When all of the request issues on the decision review have decision issues, if any of them have a DTA error disposition, it should automatically create a DTA supplemental claim to follow up on those issues.

We have been seeing contentions get dispositions, but not associated rating issues.  This is preventing creating the decision issues, as well as preventing the establishment of follow up DTA supplemental claims.

This ticket is to investigate what the cause of this is, and either how to address it in Caseflow or learn what guidance to give to users so that they can fix the issue in VBMS.

## Background/context/resources
Batteam thread:
https://dsva.slack.com/archives/CHX8FMP28/p1576084245152300
Asking Colin:
https://dsva.slack.com/archives/CK466V65V/p1576604283006500

## Technical notes
```
ri=RequestIssue.find(123)
ri.decision_issues # Is this empty?
ri.contention_disposition # is there a disposition?
epe=ri.end_product_establishment # When did this get cleared?
epe.associated_rating # is there an associated rating?
v=epe.veteran
rs=v.ratings # are there new ratings after the EPE got cleared?  If so do any of its issues match what we're missing?
rs.first.issues
```

**Comment by leikkisa** [comment]
Some theories:
- The award wasn't completed
- A rating has been created but it hasn't been promulgated
- I believe we only look at ratings promulgated after the EP got cleared.  Maybe the ratings can be promulgated before the EP is cleared
- The rating for the request issue's decision got associated to a different end product
- Are there cases where we should not expect users to create new ratings for decisions on rating issues?

**Comment by lomky** [comment]
[Additional Bat Team issue](https://dsva.slack.com/archives/CHX8FMP28/p1592326192031800)
