### ISSUE TITLE
Handle null error.response.body in EstablishClaim.jsx

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12994]
## Description

Update code to handle null `error.response.body` in `app/containers/EstablishClaimPage/EstablishClaim.jsx`.

## Background/context/resources

During Bat Teaming, got Sentry alert Slack msg: https://dsva.slack.com/archives/CAP9C43E2/p1576514628001400

Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7176/

## Technical notes
TypeError: app/containers/EstablishClaimPage/EstablishClaim in error_code
"Cannot read property 'error_code' of null" in `CREATE_EP_ERRORS[error.response.body.error_code]`

Resulted from `POST /dispatch/establish-claim/166778/perform [502]`

**Comment by hschallhorn** [comment]
Fixed in #13407
