### ISSUE TITLE
Handle malformed dates in app/establishClaimAdmin/StuckTasks.jsx

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13005]
## Description

Update code to handle malformed dates in the context of `app/establishClaimAdmin`.
Provide actionable feedback to user.

## Background/context/resources

During Bat Teaming, got Sentry alert Slack msg: https://dsva.slack.com/archives/CAP9C43E2/p1576608327003200

Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7610/

## Technical notes

`./app/util/DateUtil.js` raises error `Passing string without timezone -- try formatDateStr() instead`
Called by: `./app/establishClaimAdmin/StuckTasks.jsx`
Initiated by: `./app/establishClaimAdmin/actions/index.js`

**Comment by leikkisa** [comment]
This is for Dispatch, so updated the labels.
