### ISSUE TITLE
Motion to Vacate | Granted | Review vacated decision issues action

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#13006]
## Story
After a judge addresses a motion to vacate, the decision drafting attorney should be able to review the vacated decision issues.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] After the judge completes the AddressMotionToVacate task, if it is a grant or partial grant, it creates a ReviewVacatedDecisionsTask assigned to the decision attorney
- [ ] ReviewVacatedDecisionsTask should have the action (i.e. task) label in the drop down called "Decision ready for review"
- [ ] Selecting "Decision ready for review" brings users to `/queue/appeals/d99e49ca-0b5a-4235-ba65-4a97045b60b4/tasks/[taskid]/review_vacated_decisions`
- [ ] Include screenshot(s) in the Github issue

##
Should we re-use DraftDecisionTask instead of create ReviewVacatedDecisionsTask?

## Release notes
N/A

### Out of scope
- UI for review vacated decisions screen

### Designs
https://app.mural.co/t/workqueue2001/m/workqueue2001/1573574515518/2c771474e7259260c0ebc68b44c78bb98f295b04

![Screen Shot 2019-12-17 at 3.09.28 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/eaa6ca15-7887-4094-a943-4ce2de66f39a)

### Technical notes
This ticket makes changes to the existing task architecture. 

### Other notes
N/A

### Resources/other links
N/A

**Comment by leikkisa** [comment]
Closing this ticket. On the new appeal streams, this is going to be replaced with the regular JudgeAssignTask.
