### ISSUE TITLE
Motions to Vacate | Motion Attorney | UAT Fix

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13003]
## [Story](https://github.com/department-of-veterans-affairs/caseflow/issues/11252)
**Update to:**
As a Lit Support team member (commonly Motions Attorney, but keeping Lit Support team member to encompass other Lit Support roles we might not know about yet), I need to be able to assign a task to the judge who will decide the Motion to Vacate decision.

**UAT Findings**
[Removed 'A']
- B) Misspelling of 'Review'
- C) Verbiage should change depending on radio selection made "Provide context on which issues should be [user radio button selection]
- D) "Return to motions attorney" should also show when the judge selects "dismiss"

![image](https://user-images.githubusercontent.com/41164406/71034394-54c5ba00-20e7-11ea-97bb-bbc6031142c1.png)

## Acceptance criteria
- [ ] Add header above the context comment/note provided in [A] (ask Rutvi and Geronimo for suggestion)
- [x] Word spelling highlighted in item [B] should be updated to reflect 'Review'
- [x] Upon user radio button selection [grant, deny, dismiss] highlighted in [C] please associate each radio button with copy below
          - For grant "Provide context on which issues should be granted"
          - For deny "Provide context on which issues should be denied"
          - For dismissed "Provide context on which issues should be dismissed"
- [ ] Show "Return to Motions Attorney" options when "dismiss" is selected
- [x] Additional context not required unless granted is selected (submit is not disabled)
- [x] Add "required" label to context field when it is required

## Release notes
N/A
### Out of scope
N/A
### Designs
https://www.figma.com/file/VtOG0hibbyJ6T5UcYnn5EP/Motions-to-Vacate_Phase-II_Epic-8547?node-id=0%3A1

### Background/context
N/A
### Technical notes
N/A

**Comment by jcq** [comment]
@msj0nes @leikkisa
A couple of questions here:
- "Return to Motions Attorney" isn't applicable to this view, right? This is the attorney screen, prior to it getting to the judge
- Are we adding some sort of text (as noted in first AC), or is this stating that we want to leave out the context/instructions from the display (noted as "A" in the image)?

**Comment by msj0nes** [comment]
@jcq 
> "Return to Motions Attorney" isn't applicable to this view, right? This is the attorney screen, prior to it getting to the judge

'Return to motion attorney' is actually after the judge addresses the task, it gets returned to Lit Support (Motion Atty) . The issue is referring to the message seen below. As shown currently the radio button for 'deny' shows the message seen, however for **dismiss** it does not. 


![image](https://user-images.githubusercontent.com/41164406/73024407-87a45180-3dfb-11ea-9701-780a96380306.png)

**Comment by jcq** [comment]
@msj0nes I think that's actually a screen grab from the judge (`AddressMotionToVacate`) task. That is indeed the functionality in the `MTVJudgeDisposition` component. If I'm understanding correctly, we want to display that message for both `denied` and `dismissed` dispositions on the "judge address motion" view. Would it be OK if we split that off into a separate ticket since it's a different component/view?

**Comment by leikkisa** [comment]
@jcq I'm okay with that, do you mind creating the ticket for it?

**Comment by msj0nes** [comment]
@jcq @leikkisa just created a ticket https://github.com/department-of-veterans-affairs/caseflow/issues/13243

**Comment by leikkisa** [comment]
@jcq We want to leave the context/instructions in the display, but make it optional for granted

**Comment by msj0nes** [comment]
@jcq removed 'A' . Its aesthetic and can be dealt with later on.

**Comment by jcq** [comment]
> @jcq We want to leave the context/instructions in the display, but make it optional for granted

Oh, just to be clear I was referring to the context/instructions for the *current* attorney task, not the text field for the attorney to fill out. The context/instructions for the current task are what show at the top (indicated as "A"). I agree that there likely is no reason to have them there, and likely will never exist.

**Comment by jcq** [comment]
Updated UX:

![MotionsAttorneyDisposition-updates](https://user-images.githubusercontent.com/2581274/73029965-75bbb200-3ded-11ea-955c-387f6c8f3447.gif)

**Comment by msj0nes** [comment]
Much appreciated @jcq
