### ISSUE TITLE
Motion to Vacate | Granted | Incorporate "Submit Draft Decision for Review" screen into granted straight vacate MTV workflow

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#13009]
As a decision drafting attorney who has reviewed all issues for vacatur on a given appeal, specifically a straight vacature, I want to be able to draft a decision to send to the judge. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] If vacate type is **Straight Vacate**, clicking Continue creates the DraftVacatureTask, and automatically advances users to the Submit screen 
- [ ] Same behavior if vacate type is **Vacate and De Novo**
- [ ] Ensure that top nav built in issue #13007 is added to the existing code for this screen, but only appears when MTV tasks are being worked
- [ ] If using Document ID (or URL) going forward, Submit is disabled unless document ID/URL form is populated
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Out of scope
- Handling Vacate and Readjudicate

### Designs
https://app.mural.co/t/workqueue2001/m/workqueue2001/1573574515518/2c771474e7259260c0ebc68b44c78bb98f295b04

### Technical notes
1. Check if handling Submit is already implemented.
1. Confirm that Document ID is required

### Other notes
N/A

### Open Questions
1. Since this screen leverages existing workflow code and there is a precedent for attorneys copy/pasting the IDT document ID into this screen instead of copy/pasting a share drive URL, as is called for in the denied/dismissed/withdrawn flows, should we make make these the same data point (Doc ID or URL) in all MTV workflows, or should these be intentionally different? If different, why?

### Resources/other links
N/A

**Comment by jimruggiero** [comment]
![image (10).png](https://images.zenhubusercontent.com/5d2748c531297d7d65f8d26b/8487e1ca-f7a3-40ef-abc4-cf93c606eb08)

**Comment by leikkisa** [comment]
I am going to close this ticket, we'll be using the existing page for this.
