### ISSUE TITLE
Handle undefined submit() return value in app/queue/components/QueueFlowModal.jsx

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13015]
## Description

Update code to handle undefined return value from calling `submit()` in  `app/queue/components/QueueFlowModal.jsx`.

## Background/context/resources

During Bat Teaming, got Sentry alert Slack msg: https://dsva.slack.com/archives/CLRTL92TW/p1576681692019900

Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7614/

## Technical notes

`Cannot read property 'then' of undefined`

```
    this.props.submit().then(() => {
      this.setState({ loading: false });
      if (!this.props.error) {
        this.closeHandler();
      }
```

**Comment by hschallhorn** [comment]
closing in favor of #10632
