### ISSUE TITLE
Investigate and provide actionable error msg for DuplicateUserTask: app/models/tasks/judge_decision_review_task.rb

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13017]
## Description

Is the error msg (or something like it) shown to the user?
`Appeal XXXX already has an open task of type JudgeDecisionReviewTask assigned to User. No action necessary`

Provide user with an actionable error message.

## Background/context/resources

During Bat Teaming, got Sentry alert Slack msg: https://dsva.slack.com/archives/C4JECDLSE/p1576687881042900

Sentry alerts: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7612/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7613/

## Technical notes

Looks like reassignment was attempted:
```json
{
task: {
reassign: {
assigned_to_id: 991, 
assigned_to_type: User, 
instructions: 
avlj
}
}
}
```

**Comment by yoomlam** [comment]
Related to #13018

**Comment by hschallhorn** [comment]
PR that may have solved this: #13100
Action that can be taken by user is refreshing the page.

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||||||||||||||
2 | 
3 | 
5 | 
8 |  
```
One line copy fix.

**Comment by yoomlam** [comment]
`Caseflow::Error::DuplicateUserTask: Appeal 19616 already has an open task of type JudgeDecisionReviewTask assigned to User. No action necessary`

```
app/models/tasks/judge_decision_review_task.rb in verify_user_task_unique at line 32
Called from: active_support/callbacks.rb in block in make_lambda
app/workflows/attorney_task_creator.rb in tasks at line 18
app/workflows/attorney_task_creator.rb in call at line 10
app/controllers/judge_assign_tasks_controller.rb in block (2 levels) in tasks at line 17
```

**Comment by yoomlam** [comment]
Related to #13110.

**Comment by hschallhorn** [comment]
> Appeal 19616 already has an open task of type JudgeDecisionReviewTask assigned to User

NOOOOOO
