### ISSUE TITLE
Styleguide component | Form fields | Text Input

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1302]
As a developer and designer, I want a clear and consistent way to implement text inputs so our users can enter important information in an accessible way across our apps. 

## Acceptance Criteria
1. Verify that this is found in the living style guide there is a subsection titled `Text Input` under `Form Fields`
1. Verify that the description for `Text Input` appears underneath the title (see copy)
1. Verify that the components and sections appear beneath the description for Text Input 
1. Verify that the text input matches the one in USWDS
1. Verify that focus state matches the one in USWDS
1. Verify that text input label is 8px apart from text input field. 
1. Verify that input field will have a `margin-bottom` of 40px

## Mocks
_Make sure you are logged into Invision before you click the craft links_ 

**Text Input Default State**

[Craft Link - Text Input Default](https://projects.invisionapp.com/d/main#/console/10592592/224822870/previe)

<img width="663" alt="screen shot 2017-04-03 at 8 57 35 am" src="https://cloud.githubusercontent.com/assets/23316107/24610192/a74ed9d4-184b-11e7-9d12-761fd4168656.png">

**Text Input Focus State**

[Craft Link - Text Input Focus State](https://projects.invisionapp.com/d/main#/console/10592592/224823899/preview)

<img width="687" alt="screen shot 2017-04-03 at 8 57 21 am" src="https://cloud.githubusercontent.com/assets/23316107/24610303/0da631dc-184c-11e7-9fd0-29f8d7fc200b.png">

## Copy

**Title**

Text Input

**Description**

A text input field in a form that allows the user to enter requested information. It can appear as a field for a single line of text or an area for multiple lines of text. For multiple lines of text we can also include a character limit description below the text area.

Text inputs appear in 3 different formats depending on the status of the user's input: 
- Text Input label (no highlight) indicates that no action has been taken in the text field  
- Text Input Focused (light blue-gray highlight) indicates that the user has selected the input field
- Text Input Error (red highlight) indicates that the user has made an error when entering their text

## Related Issues
#1412 Styleguide | Form fields section overview

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Go to Style Guide
2. Navigate to text field input 
3. Verify the behavior based on AC above

Screenshots:
![sgtextfield](https://cloud.githubusercontent.com/assets/23038505/26011430/121b8a7c-371f-11e7-8c2c-2ccb870105db.gif)
