### ISSUE TITLE
AMA QR code requires a second urgent update

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#13037]
User story: As a member of the Quality Review (QR) team at the Board, I need the AMA quality review monthly limit and selection probability to be updated to .188, so that I can reliably receive 130+ AMA cases to review monthly, up to **133** case per month, not 137 as is currently set.

### Acceptance criteria
- [ ] The monthly limit of Quality Reviews is set at 133
- [ ] The Quality Review selection probability is set at 0.188

### Release notes
Caseflow now supports sending sending up to 133 AMA cases to QR for review monthly.

### Out of scope
Changes to legacy QR code.

### Background/context
It is believed that the prior update made in #12867 was insufficient. The Board on had 7 cases directed to QR last week and was expecting a significantly higher volume. 

### Resources/other links
Legacy code lives here: https://github.com/department-of-veterans-affairs/caseflow/blob/555ac6727ea665985dd42a2f325cb498686c68f0/app/models/judge_case_review.rb

**Comment by hschallhorn** [comment]
#12915 was merged 9 days ago, lets see what the spread looks like in prod
```ruby
week_qr_count  = QualityReviewTask.where(appeal_type: Appeal.name, assigned_to_type: Organization.name, created_at: 7.days.ago..Time.zone.now).count
week_dispatch_count = BvaDispatchTask.where(appeal_type: Appeal.name, assigned_to_type: Organization.name, created_at: 7.days.ago..Time.zone.now).count
week_completed_cases_count = week_qr_count + week_dispatch_count
month_completed_cases_count = week_completed_cases_count / 7.0 * 30
# Let's see what our number should produce
month_completed_cases_count * QualityReviewCaseSelector:: QUALITY_REVIEW_SELECTION_PROBABILITY
=> 31.54285714285714
# Let's see what the new number would give us
month_completed_cases_count * 0.188
=> 185.31428571428572
# Let's confirm this for the last few months
6.times do |number_of_months_ago|
  month = (number_of_months_ago + 1).months.ago
  month_qr_count  = QualityReviewTask.where(appeal_type: Appeal.name, assigned_to_type: Organization.name, created_at: month.beginning_of_month..month.end_of_month).count
  month_dispatch_count = BvaDispatchTask.where(appeal_type: Appeal.name, assigned_to_type: Organization.name, created_at: month.beginning_of_month..month.end_of_month).count
  month_completed_cases_count = month_qr_count + month_dispatch_count
  puts month_completed_cases_count * 0.188
end
145.136
159.8
106.972
68.244
40.232
24.816
```
Looks like .188 is a good number to hit the goal of 137 a month now that we've ramped up.

**Comment by hschallhorn** [comment]
@jimruggiero Ran a bunch of tests with October's number of completed cases (850). 

1% of the time, the monthly limit was not reached with this probability.
The fewest number of cases sent to QR was 131.

Here's how many AMA cases have been completed in the last few months

Month|QR and Dispatch cases created
---|---
Dec (projected) | 977
Nov | 772
Oct | 850
Sept | 569
Aug | 363
Jul | 214
Jun | 132

If we're sure that we will hit October levels of completed cases, this fix is the right choice. If that number ever drops, we should increase the probability.
