### ISSUE TITLE
Update USWDS to 1.6.14

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13043]
## Description
[USWDS 1.6.14](https://github.com/uswds/uswds/releases/tag/v1.6.14) has no known vulnerabilities

## Background/context/resources
We only use USWDS styles, not scripts, so security impact should actually be minimal, so this should be low priority

**Comment by meckila-navapbc** [comment]
As of 6/22/2021, caseflow is on version ^1.6.4

**Comment by jcq** [comment]
@meckila-navapbc I don't actually remember what prompted this, but it looks like there might have been a security issue with older versions? Should we keep this open to remind us to bump the version to latest 1.x?

**Comment by meckila-navapbc** [comment]
> @meckila-navapbc I don't actually remember what prompted this, but it looks like there might have been a security issue with older versions? Should we keep this open to remind us to bump the version to latest 1.x?

You make a good point. I'll updated the version as well
