### ISSUE TITLE
Task Model Callback Untangling

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13058]
## Description

Create a tech spec evaluating the options for reimplementing our domain logic that is currently all captured as ActiveRecord callbacks on Task, its subclasses, and it's related objects.

Goals:
 - Clear & Understandable flow
 - Independently testable behavior
 - Ability to skip domain behavior without losing validation behavior.

## Background/context/resources

 - [Ref in Task Model Frustrations](https://github.com/department-of-veterans-affairs/caseflow/issues/12713#issuecomment-554003931) #12713 
 - [Task Model Callbacks Today](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L28)
 - Example headache, where we are [coding around our callbacks](https://github.com/department-of-veterans-affairs/caseflow/pull/9860/files#diff-c95c9451cf097bdd58f73d0f9b114f97R256), but then [coding around coding around our callbacks](https://github.com/department-of-veterans-affairs/caseflow/pull/13057)
 
## Technical notes

Observer Pattern? Concerns? Callbacks, but more intentional? Does Rails have an established best practice? What does Metz suggest? Where does the domain logic go?!

Fell out of #12617/#13057

**Comment by hschallhorn** [comment]
Include documentation on how current model callbacks work in spec.
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | ||||||||
5 | |||||||
8 | 
```
Although is a tech spec, seems like it requires more research than a normal one. _Untangling_.
