### ISSUE TITLE
Remove Edit in Caseflow button for Board Grant ratings

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#13064]
For Board grant ratings, when user clicks on  Edit in Caseflow button in VBMS, It returns page not found error. We should not set not set the origSrc attribute for Board Grant issues in order to avoid this error. This should also be tested in UAT before it goes into prod. 

![Screen Shot 2019-12-30 at 11.40.38 AM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/df0f38d4-a211-4857-b360-f3b81780446f)

**Comment by pkarman** [comment]
Second guessing myself about the `origSrc` attribute. We might want to set it, but set it to something different than we do for other contentions. Need to confirm this with VBMS.

**Comment by msj0nes** [comment]
@leikkisa considering the future plans to allow user to edit the Board Grant EPs (issue title), should we close this ticket?

**Comment by leikkisa** [comment]
@msj0nes Yes I think we should close this ticket, so that button can be used when we do support editing these.
