### ISSUE TITLE
Remove contestable_rating_decisions feature toggle

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13066]
Our experiment with including rating decisions was successful. Let's remove the feature toggle for `:contestable_rating_decisions`.

**Comment by leikkisa** [comment]
Blocking this PR for now, because adding this was potentially a temporary solution to missing ratings. I am getting asked about the extra options that wouldn't normally be there, so we might eventually want to take them back out.
https://dsva.slack.com/archives/CFBLH2LR4/p1580491161070300

**Comment by leikkisa** [comment]
Closing this ticket - we can revisit it as part of cleaning up feature toggles, but this one in particular should stay for now and the indefinite future.
