### ISSUE TITLE
Business Lines | Report | Export non-comp LOB tasks CSV

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13075]
## User or job story
As an administrator of a non-comp line of business, I need to report regularly on the number and type of completed tasks for my organization.

## Acceptance criteria
- [ ] On my `/decision_reviews/:business_line_slug` page, an "Download completed tasks as CSV" button (similar to asyncable jobs download)
- [ ] The CSV download file should be named in the format `yyyy-mm-dd-business-line-slug-completed-tasks.csv`

**Columns Required**
Claimant Name
URL- `url`
Veteran File Number - `veteran_file_number`
Appeal Type - `appeal_type`
Time Created - `created_at`
Issues Total 
Issue Descriptions - ?
User's CSS ID (Started the form) - 

### Out of scope

* No date selector. Export all completed tasks to date.

### Background/context

https://dsva.slack.com/archives/CFBLH2LR4/p1577735929035600

### Technical notes

Example controller code:

```ruby
csv_export = []
columns = [:id, :type, :appeal_type, :created_at, :closed_at]
csv_export << columns.join(",")
business_line.tasks.completed.order(id: :asc).pluck(columns).each do |t| 
  csv_export << t.join(",")
end
ymd = Time.zone.now.strftime("%Y%m%d")
filename = "#{ymd}-#{business_line.url}-completed-tasks.csv"
send_data csv_export.join("\n"), filename: filename
```

## Open questions
Consider restricting this page to users who have the appropriate permissions relative to each LOB.

**Comment by Sjones352** [comment]
Similar csv code https://github.com/department-of-veterans-affairs/caseflow/pull/12707

**Comment by leikkisa** [comment]
@Sjones352 I found a report created for Loan Guaranty from a batteam request.  It has PII in it, but here's a [Slack thread](https://dsva.slack.com/archives/CHX8FMP28/p1591631037072000?thread_ts=1591619997.067600&cid=CHX8FMP28) with a script:

```ruby
loan = BusinessLine.find_by(url: "loan-guaranty")
	rows = loan.tasks.all.includes(:appeal).order(id: :asc).map do
	  |t| [
	    t.appeal.intake&.user&.css_id, 
	    t.id, 
	    "https://appeals.cf.ds.va.gov/decision_reviews/loan-guaranty/tasks/#{t.id}", 
	    t.appeal_id, 
	    t.appeal_type, 
	    t.appeal.veteran_file_number, 
	    t.created_at,
	    t.appeal.claimant.name,
	    t.appeal.issues.count
	  ]
	end
	rows.each { |r| puts r.join(",") }
```
