### ISSUE TITLE
Motion to Vacate | Success banner after AddressMotionToVacate task is submitted

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13073]
## User or job story
User story: As a Judge, after I submit an AddressMotionToVacate task, when I am redirected to queue I'd like to see a success banner.

## Acceptance criteria
- [ ] The "Disposition saved" success banner shows on the next page after the judge submits an AddressMotionToVacate

## Tech notes
See PostDecisionMotionController.

The banner is currently being displayed elsewhere later (it's shown up in a couple of different pages).  We believe it's because the page is not actually refreshing from the server, which is where the flash message is coming from.

It may be worth having the routing do a fresh refresh when redirecting to the Queue page, or otherwise seeing how these alerts are used elsewhere in the Queue app.

**Comment by leikkisa** [comment]
@geronimoramos @rutvigupta-design Do you have a design for this success banner, or do you have opinions on the copy above?

**Comment by leikkisa** [comment]
I think this banner might exist, but that it wasn't getting triggered at the correct time.

**Comment by jcq** [comment]
@rutvigupta-design What should the "detail" message be for this alert? 

I'm setting the title to "Disposition Saved", but I need to override the detail (smaller text) with something

**Comment by rutvigupta-design** [comment]
Attaching designs for the success banner for denied and dismissed motions. 
![Judge-Deny-Success](https://user-images.githubusercontent.com/51714306/75062620-c97ef100-54a8-11ea-8bf7-d0f9ec2ff1d0.jpg)
![Judge-Dismiss-Success](https://user-images.githubusercontent.com/51714306/75062622-cab01e00-54a8-11ea-8c2d-f26aab8459da.jpg)

**Comment by rutvigupta-design** [comment]
@jcq here is the banner for granted motions (full or partial vacaturs). 
![Judge-Grant-Success](https://user-images.githubusercontent.com/51714306/75063251-1f07cd80-54aa-11ea-8118-ac8dd017d898.jpg)
