### ISSUE TITLE
History: Display most recent search at the top of the list

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1307]
Currently eX History shows the files that have been searched for in order from oldest (at top of the list) to newest (at bottom of the list). It should be the opposite.

**AC**
Verify that the most recently searched efolder shows at the top of the History and the oldest search shows at the bottom of the list.

**Mock**
When this issue is implemented DEMO987 would represent the most recent search and DEMO123 represents the oldest search.
<img width="939" alt="screen shot 2017-03-23 at 12 22 57 pm" src="https://cloud.githubusercontent.com/assets/4975959/24258239/84cb8ba4-0fc3-11e7-80e2-f272bc42137e.png">

**Comment by shanear** [comment]
This should be an efolder express issue 😝

**Comment by shanear** [comment]
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/434

closing
