### ISSUE TITLE
Missing Ratings | Ability to intake decision reviews with missing ratings/issues 

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13088]
## Background/context
We are missing data for some rating issues in BGS. After the release of the new BGSService that should reduce this, we've found that some of the missing ratings are still missing from the new service.

When unidentified issues are added, we do not send the actual contention text to VBMS.  Unidentified issues are not supposed to get decisions and have not been set up to support decisions (such as missing a decision date for the previous issue).

We have proposed to allow users to add unidentified issues and create real contentions for them, which are not connected to the original rating issue.  This will include a checkbox to allow the VSR to verify that they have checked that the decision is a valid decision with a record they can find.

Trying this approach out has been approved by AMO, but they have asked that we wait until the new service is implemented since this is not the preferred way to resolve missing rating issue data.

This is part of the bigger "missing rating" work:
Related: #10511

## Goals
- Allow unidentified issues to have a decision date attached to them
- Allow unidentified issues to have legacy issues connected to them
- Perform the same validations on unidentified issues
- Add a process step to verify the unidentified issues
- Create a contention for the unidentified issue
- Treat the unidentified issue as a rating issue
- Maximize ability to backfill these issues at a later date if possible

## Success criteria
Users are able to add missing rating issues, process them as usual, and make decisions on them
Handle support tickets

## Stakeholders
AMO, the Caseflow Support team, Batteam, and also BVA

## Requirements/stories
See connected tickets

## Open questions

- Stakeholder
  - Impact of having these issues not connected to previous rating
- Technical
  - Identifying duplicates
  - We will not be able to associate these to rating issues

### Business value
- Allows stuck claims to be processed
- Reduces support tickets

### Dependencies
VBMS - for creating contentions

**Comment by msj0nes** [comment]
## Stakeholder Meeting
**Discussion**: Rating Issue with Promulgation Dates in the Future of Form Receipt Dates
**Proposal AMO Approved**: Modify promulgation use in Caseflow to restore missing ratings.
[Meeting Minutes](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Caseflow%20Projects/Foxtrot/Meeting%20Minutes/AMO/1_6_2020.md)

**Comment by msj0nes** [comment]
# Status
CorpDB/BGS contacted for 'Input/Output Spec' document and a meeting to surface Caseflow engineering questions, obtain permission and views from CorpDB/BGS team on any foreseeable issues with Caseflow using the service RatingWebService.findRatingData .

**Comment by msj0nes** [comment]
# Tracker 
 **Key:** <br>
Not Started - ⚪️  
In Progress -  🚧       
Complete -  ✅ 
Blocked - 🔴  
Pending Stakeholder/SME Feedback  ☎️  

## Checklist Items

- Obtain service being used by VBMS - ✅ 
- [Perform engineering assessment of new BGS service](https://github.com/department-of-veterans-affairs/caseflow/issues/13996) - 🚧 
- [Discuss 'Disability Ratings' with AMO]
- Format data in service  - ⚪ 
- Demo service to AMO stakeholder POCs - ⚪ 
- Confirm w/ AMO the need for pilot - ⚪ 
- Add new service in production [Pilot/ Release] -  ⚪ 

----------------------------

GH |Research | Design |  Development | Pilot | Release
-- | -- | -- | -- | -- | -- 
Add New Service in Production (Pending Assessment) |  :white_circle:  | :white_circle:| :white_circle: | :white_circle:   |  :white_circle:

**Comment by msj0nes** [comment]
# Last Status

Caseflow team has supplied BGS team with assessment data required to resolve missing ratings issue. Please contact Jim R. for additional details relating to the development
