### ISSUE TITLE
Investigate why multiple JudgeDecisionReviewTasks are being created

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13086]
Followup to #12802. We've now got [4 sentry alerts](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7612/) of duplicate tasks we blocked the creation of.

## AC
- [x] Determine what is causing caseflow to create duplicate `JudgeDecisionReviewTask`s

**Comment by hschallhorn** [comment]
```ruby
appeals_with_multiple_jdrts_ids = JudgeDecisionReviewTask.group(:appeal_id).count.select { |appeal_id, count| count > 1 }.keys
appeals_with_multiple_jdrts = Appeal.find(appeals_with_multiple_jdrts_ids)
appeals_with_duplicate_jdrts = appeals_with_multiple_jdrts.select do |appeal|
  jdrts = JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at)
  jdrts.first.closed_at.nil? ||  jdrts.first.closed_at.to_i - jdrts.second.created_at.to_i  > 120
end
appeals_with_duplicate_jdrts.count
=> 38

times_created = appeals_with_duplicate_jdrts.map do |appeal|
  JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at).first.created_at
end
pp times_created.sort
[Mon, 08 Jul 2019 11:30:36 EDT -04:00,
 Tue, 09 Jul 2019 15:48:06 EDT -04:00,
 Fri, 02 Aug 2019 15:03:29 EDT -04:00,
 Fri, 16 Aug 2019 12:17:13 EDT -04:00,
 Wed, 28 Aug 2019 09:36:30 EDT -04:00,
 Fri, 30 Aug 2019 12:08:01 EDT -04:00,
 Fri, 30 Aug 2019 12:08:36 EDT -04:00,
 Fri, 30 Aug 2019 12:09:09 EDT -04:00,
 Mon, 16 Sep 2019 09:26:56 EDT -04:00,
 Thu, 19 Sep 2019 09:58:55 EDT -04:00,
 Thu, 19 Sep 2019 16:39:03 EDT -04:00,
 Fri, 20 Sep 2019 12:37:57 EDT -04:00,
 Fri, 20 Sep 2019 12:42:46 EDT -04:00,
 Tue, 24 Sep 2019 06:56:53 EDT -04:00,
 Tue, 24 Sep 2019 11:26:14 EDT -04:00,
 Tue, 24 Sep 2019 11:26:14 EDT -04:00,
 Tue, 24 Sep 2019 11:26:14 EDT -04:00,
 Tue, 24 Sep 2019 11:26:14 EDT -04:00,
 Tue, 24 Sep 2019 11:26:14 EDT -04:00,
 Tue, 24 Sep 2019 11:26:14 EDT -04:00,
 Wed, 25 Sep 2019 08:11:08 EDT -04:00,
 Mon, 30 Sep 2019 16:20:19 EDT -04:00,
 Thu, 03 Oct 2019 07:27:47 EDT -04:00,
 Wed, 09 Oct 2019 11:44:31 EDT -04:00,
 Wed, 09 Oct 2019 15:40:49 EDT -04:00,
 Wed, 16 Oct 2019 18:11:51 EDT -04:00,
 Tue, 22 Oct 2019 10:34:09 EDT -04:00,
 Tue, 22 Oct 2019 12:47:49 EDT -04:00,
 Thu, 31 Oct 2019 15:01:50 EDT -04:00,
 Thu, 07 Nov 2019 11:05:27 EST -05:00,
 Wed, 13 Nov 2019 16:28:14 EST -05:00,
 Thu, 14 Nov 2019 13:40:40 EST -05:00,
 Mon, 18 Nov 2019 14:41:38 EST -05:00,
 Thu, 21 Nov 2019 11:45:54 EST -05:00,
 Mon, 25 Nov 2019 08:07:40 EST -05:00,
 Tue, 26 Nov 2019 13:34:50 EST -05:00,
 Tue, 10 Dec 2019 13:12:12 EST -05:00,
 Thu, 12 Dec 2019 10:02:32 EST -05:00]

time_between_created = appeals_with_duplicate_jdrts.map do |appeal|
  jdrts = JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at)
  jdrts.second.created_at - jdrts.first.created_at
end
pp time_between_created.sort
[0.218621,    <- 0.2 seconds
 9.501548,
 16.828479,
 17.894918,
 18.608637,
 20.319508,
 21.32896,
 22.350396,
 25.835167,
 26.587437,
 28.176916,
 28.335097,
 31.650559,
 36.588806,
 38.465278,
 43.546014,
 43.659093,
 46.161825,
 46.19935,
 60.524763,
 64.242005,
 74.624026,
 77.376698,
 82.880769,
 91.718011,
 98.033942,
 125.674659,
 147.081541,
 150.57926,
 159.011504,
 178.316628,
 193.952997,
 206.087587,
 356.202629,
 529.180295,
 1060.451615,
 1519.055039,
 6633.889308] <- 2 hours
```

**Comment by hschallhorn** [comment]
Now let's look at the sentry alert appeals
```ruby
sentry_alert_appeal_ids = %w"32911 8745 701 8721"
sentry_alert_appeals = Appeal.find(sentry_alert_appeal_ids)
sentry_alert_appeals.count
=> 4

times_created = sentry_alert_appeals.map do |appeal|
  [appeal.id, JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at).first.created_at]
end
pp times_created.sort_by { |appeal| appeal[1] }
[[8721, Tue, 17 Dec 2019 14:52:00 EST -05:00],
 [701, Wed, 18 Dec 2019 13:40:29 EST -05:00],
 [8745, Fri, 27 Dec 2019 15:15:45 EST -05:00],
 [32911, Mon, 30 Dec 2019 07:19:51 EST -05:00]]
```
Sentry alerts occurred at the following times:

Appeal|Original Creation Time|Alert Times| Difference
---|---|---|---
8721 | 7:52:00 | 7:56:58 PM <br> 7:57:11 PM | <5 minutes after original created <br>  >5 minutes
701 | 6:40:29 | 6:40:55 PM <br> 6:41:40 PM | <1 minute <br>  >1 minute
8745 | 8:15:45 | 8:16:15 PM <br> 8:17:45 PM |<1 minute <br>  2 minutes
32911 | 12:19:51 | 12:20:52 PM <br> 12:27:03 PM | 1 minute <br>  >7 minutes

**Comment by hschallhorn** [comment]
[Could not find logs for 32911](https://caseflow-kibana.va.gov/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:'*',interval:auto,query:(language:lucene,query:'%22c9d36ca6-5ed2-4cf1-850a-be129bbd436e%22%20%26%26%20%22570755%22'),sort:!('@timestamp',desc)))
Logs for 8745: [Original task creation](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0b2ca2656b50d4683;filter=%228a95962e-ee9d-479d-aa48-325e7b4b8965%22;start=2019-12-27T00:16:33Z), [1st alert](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0b2ca2656b50d4683;filter=%22dd202867-499f-4c21-828e-11131338ec58%22;start=2019-12-27T00:16:33Z), [2nd alert](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0ae50973bab343e8a;filter=%22f0d4f481-a7cf-45e5-bb6d-7677769259f0%22;start=2019-12-27T00:16:33Z)
[Could not find logs for 701](https://caseflow-kibana.va.gov/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:'*',interval:auto,query:(language:lucene,query:'%225cec2f52-2fd0-4162-8e57-875a11321b1f%22%20%26%26%20%22578861%22'),sort:!('@timestamp',desc)))
[Could not find logs for 8721](https://caseflow-kibana.va.gov/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:'*',interval:auto,query:(language:lucene,query:'%229ebcf526-64e9-44de-94a7-a9ebb4df9164%22%20%26%26%20%22572130%22'),sort:!('@timestamp',desc)))

**Comment by hschallhorn** [comment]
Let's look at the logs for the most recent appeal where a duplicate task was created
```ruby
appeals_with_multiple_jdrts_ids = JudgeDecisionReviewTask.group(:appeal_id).count.select { |appeal_id, count| count > 1 }.keys
appeals_with_multiple_jdrts = Appeal.find(appeals_with_multiple_jdrts_ids)
appeals_with_duplicate_jdrts = appeals_with_multiple_jdrts.select do |appeal|
  jdrts = JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at)
  jdrts.first.closed_at.nil? ||  jdrts.first.closed_at.to_i - jdrts.second.created_at.to_i  > 120
end

appeal = appeals_with_duplicate_jdrts.sort_by do |appeal|
  JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at).first.created_at
end.last
puts appeal.structure_render(:created_at)
Appeal 12416 [created_at]
└── RootTask 2019-07-22 13:19:03 -0400
    ├── TrackVeteranTask 2019-07-22 13:19:04 -0400
    ├── DistributionTask 2019-07-22 13:19:04 -0400
    │   └── InformalHearingPresentationTask 2019-07-22 13:19:04 -0400
    │       └── InformalHearingPresentationTask 2019-11-13 09:21:10 -0500
    ├── JudgeAssignTask 2019-12-09 17:21:38 -0500
    ├── JudgeAssignTask 2019-12-10 11:50:47 -0500
    ├── JudgeDecisionReviewTask 2019-12-12 10:02:32 -0500
    │   ├── AttorneyTask 2019-12-12 10:02:32 -0500
    │   └── OtherColocatedTask 2020-01-02 07:16:46 -0500
    │       └── OtherColocatedTask 2020-01-02 07:16:46 -0500
    └── JudgeDecisionReviewTask 2019-12-12 10:03:18 -0500
        ├── AttorneyTask 2019-12-12 10:03:18 -0500
        └── OtherColocatedTask 2020-01-02 07:15:57 -0500
            └── OtherColocatedTask 2020-01-02 07:15:57 -0500
```
```bash
awslogs get dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out --start='12/12/2019 15:02:30' --end='12/12/2019 15:03:20' | grep '"external_id"=>"e2236018-52ba-4640-99df-bc635b62119e"'

```
Appeal|Original Request|Second Request
---|---|---
12416| [logs](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0fcd430cbbd93af9c;filter=%22fd20598d-f085-4830-808b-2831b81e71e1%22)|[logs](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-04fcdf31d71743f84;filter=%22bb56ae24-f64d-427d-a744-6fe67c7beae1%22)

**Comment by hschallhorn** [comment]
Things I tried in dev to spawn multiple requests:
1. Assign case to atty from case details page
1. Hit back button
1. Assign to same atty again
Result: No update to the task or duplication or duplication error

1. Assign case to atty from case details page
1. Hit back button
1. Assign to different atty again
Result: Task correctly reassigned

1. Assign case to atty from assign page
1. Click into that atty queue
1. Assign to same atty again
Result: No update to the task or duplication or duplication error

1. Assign case to atty from assign page
1. Click into that atty queue
1. Assign to different atty again
Result: Task correctly reassigned

**Comment by hschallhorn** [comment]
[Commits before this first started](https://github.com/department-of-veterans-affairs/caseflow/commits/master?after=dc23a997793fa0989480b884429857755498c165+845)

**Comment by hschallhorn** [comment]
More alerts on 2 other appeals: [Alerts](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7612)

```ruby
sentry_alert_appeal_ids = %w"9647 4378"
sentry_alert_appeals = Appeal.find(sentry_alert_appeal_ids)
sentry_alert_appeals.count
=> 2

times_created = sentry_alert_appeals.map do |appeal|
  [appeal.id, JudgeDecisionReviewTask.where(appeal_id: appeal.id).order(:created_at).first.created_at]
end
pp times_created.sort_by { |appeal| appeal[1] }
[[4378, Fri, 03 Jan 2020 21:47:51 UTC +00:00],
 [9647, Mon, 06 Jan 2020 13:46:50 UTC +00:00]]
```

**Alert Times**

Appeal|Original Creation Time|Alert Times| Difference
---|---|---|---
4378|21:47:51|21:48:12|< 1 minute after original created
9647|13:46:50|13:48:31 <br> 13:48:43 <br> 13:49:02 <br> 13:49:16 | < 2 minutes <br> < 2 minutes <br> > 2 minutes <br> > 2 minutes

**Logs**

Appeal|Original Request|Alerts
---|---|---
4378|logs|logs
9647|logs|logs<br>logs<br>logs<br>logs

**Comment by yoomlam** [comment]
> **Some takeaways so far:**
> These are definitely not duplicate creates from the same request.

This conclusion rules out AWS Lambda retries mentioned here: https://github.com/department-of-veterans-affairs/caseflow/issues/12802#issuecomment-562590900

**Comment by hschallhorn** [comment]
Looks like this may be happening from the judge assign page when multiple cases are assigned to one user. Let's see if we can confirm that

```ruby
appeal_ids = %w"9647 4378 32911 8745 701 8721"
appeals = Appeal.find(appeal_ids)

closely_assigned_atty_tasks = appeals.map do |appeal|
  atty_task = AttorneyTask.find_by(appeal: appeal)
  atty = atty_task.assigned_to
  created_at_range = (atty_task.created_at - 5.seconds)..(atty_task.created_at + 5.seconds)
  tasks = AttorneyTask.where(assigned_to: atty, created_at: created_at_range).order(created_at: :desc)
  tasks.map { |task| [task.appeal_id, task.created_at] }
end

pp closely_assigned_atty_tasks
[[[9647, Mon, 06 Jan 2020 13:46:50 UTC +00:00],
  [11195, Mon, 06 Jan 2020 13:46:49 UTC +00:00]],

 [[4378, Fri, 03 Jan 2020 21:47:52 UTC +00:00],
  [5615, Fri, 03 Jan 2020 21:47:51 UTC +00:00],
  [13050, Fri, 03 Jan 2020 21:47:51 UTC +00:00]],

 [[32911, Mon, 30 Dec 2019 12:19:51 UTC +00:00],
  [32868, Mon, 30 Dec 2019 12:19:51 UTC +00:00]],

 [[8745, Fri, 27 Dec 2019 20:15:45 UTC +00:00],
  [11172, Fri, 27 Dec 2019 20:15:45 UTC +00:00]],

 [[701, Wed, 18 Dec 2019 18:40:29 UTC +00:00],
  [48527, Wed, 18 Dec 2019 18:40:29 UTC +00:00]],

 [[8721, Tue, 17 Dec 2019 19:52:00 UTC +00:00],
  [16835, Tue, 17 Dec 2019 19:51:59 UTC +00:00],
  [33524, Tue, 17 Dec 2019 19:51:59 UTC +00:00]]]
```

Takeaways!
1. Every appeal that created this alert was assigned to an attorney at almost the same time as at least one other appeal. This confirms that the original assignment is being done through the "Assign cases" page
2. Every appeal with the duplicate is the final assigned case

**Comment by hschallhorn** [comment]
Let's look at the logs for the other case assignment to see if we can find anything odd.
[Logs for 8745](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0b2ca2656b50d4683;filter=%228a95962e-ee9d-479d-aa48-325e7b4b8965%22;start=2019-12-27T00:16:33Z) - [Logs for 11172](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0ae50973bab343e8a;filter=%22ce2f9ba3-a098-4c45-9c19-b07bed772ab8%22;start=2019-12-26T00:00:00Z;end=2019-12-28T23:59:59Z)

**Comment by hschallhorn** [comment]
Thoughts on why #13100 may solve this from slack:
> So I have not been able to track down what is causing this or able reproduce the issue. I’ll keep looking, but to me this is feeling like something on the front end is not being updated properly. We know that
> 1. The first request to assign a case is going through correctly (via logs)
> 2. The user (incorrectly) still has the case in their queue to be assigned (via the fact that they submit another request)

> Because this is also happening when multiple cases are assigned, I feel like we may be getting a race condition with creating and returning tasks. A possible timeline of events:
> 1. User selects case A and B to be assigned to an atty
> 1. Front end sends two separate requests, one to assign case A, one to assign case B
> 1. Case A is assigned on the back end. JudgeAssignTask is marked complete. JudgeDecisionReviewTask and AttorneyTask are created.
> 1. New tasks created with case A assignment are selected along with all other tasks assigned to the judge (including the unassigned case B)
> 1. Case B is assigned on the back end. JudgeAssignTask is marked complete. JudgeDecisionReviewTask and AttorneyTask are created
> 1. New tasks created with case B assignment are selected along with all other tasks assigned to the judge (including the now assigned case A)
> 1. Front end receives tasks from 6. and updates the tasks stored and displayed on the front end
> 1. Front end receives tasks from 4. and updates the tasks stored and displayed on the front end
> 1. Front end displays case B as unassigned and in need of assignment as the most recent tasks received claim B is still unassigned

> I’m not entirely sure this is the issue, but this is where the investigation had currently led me.
The good news is that the fix for this is pretty trivial and costs us nothing to deploy and see if it works.

**Comment by hschallhorn** [comment]
### Testing in UAT. 
1. [Login](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Caseflow%20Projects/Intake/Validation.md#caseflow-uat).
1. Sign in as user CF_SCOTTY_283 from https://appeals.cf.uat.ds.va.gov/test/users.
1. Create some cases
```ruby
RequestStore[:current_user] = User.system_user

judge = User.find_by(css_id: "CF_SCOTTY_283")
atty = User.find_by(css_id: "CF_MCCOY_317")

# Run this a few times to make some appeals
appeal = Appeal.create!(veteran_file_number: (SecureRandom.random_number(9e8) + 1e8).to_i.to_s)
appeal.create_tasks_on_intake_success!
distribution_tasks = appeal.tasks.select { |task| task.is_a?(DistributionTask) }
distribution_tasks.each(&:ready_for_distribution!)
JudgeAssignTask.create!(appeal: appeal,
                                parent: appeal.root_task,
                                assigned_at: Time.zone.now,
                                assigned_to: judge)
appeal.tasks.where(type: DistributionTask.name).update(status: :completed)
```
4. Go to https://appeals.cf.uat.ds.va.gov/queue/97/assign
1. Try assigning some cases

**Comment by hschallhorn** [comment]
[This comment](https://github.com/department-of-veterans-affairs/caseflow/issues/13086#issuecomment-572108693) outlines EXACTLY what happened. 

<img width="538" alt="Screen Shot 2020-01-08 at 3 53 05 PM" src="https://user-images.githubusercontent.com/45575454/72015235-6c4c1a80-322f-11ea-87a2-ea5d7310143b.png">

Tasks returned and sent to the redux store from the assignment of case A were received after tasks returned and sent to the redux store from the assignment of case B. The set of tasks from the assignment of case A has task for case B as still "assigned".
