### ISSUE TITLE
Change the "from" email address in virtual hearings

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13093]
## Description
The "from" email that virtual hearings sends doesn't make too much sense, so it needs to be changed to BoardofVeteransAppealsHearings@public.govdelivery.com.   We need to contact granicus support to configure this, prior to making the code change.

**Comment by ferristseng** [comment]
https://support.granicus.com/s/article/Managing-Your-From-Addresses

> Due to the technical nature of From Addresses, adding a new From Address or display name in your account is something that must be completed by Granicus Customer Support. Contact us at support@granicus.com and please include the following:
>
> Your desired From Address 
> The display name(s) you’d like to use 
> Indication of whether you want to restrict the From Address to a specific topic
> Account Administrator approval (if you are not an Account Administrator) 
> Optional:
> Reply forwarding rule
> Custom auto-response
