### ISSUE TITLE
Route Claim | VACOLS Update | Update wording

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1309]
As a caseworker, I'd like to see more clear wording that VACOLS **will** be updated, instead of the current wording which makes it seem like it has already been updated.

## Acceptance Criteria
- Verify that on the "Update VACOLS" page, the heading is changed to "Route Claim: Confirm VACOLS Update"
- Verify that the copy of the directions is changed from:

> To ensure this claim is routed correctly, we will take the following steps in VACOLS:

to

> To ensure this claim is routed correctly, Caseflow will make the following updates to VACOLS:

**Comment by astewarttistatech** [comment]
Blocked by #1369

**Comment by astewarttistatech** [comment]
Screenshot
<img width="1395" alt="screen shot 2017-03-29 at 1 31 39 pm" src="https://cloud.githubusercontent.com/assets/23038505/24467858/2d047f82-1484-11e7-9022-226f85d9c36b.png">
