### ISSUE TITLE
Handle single failure in batch assignment of attorney tasks

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13110]
As noted in [#13100](https://github.com/department-of-veterans-affairs/caseflow/pull/13100#issuecomment-572249616), now that we batch assign ama tasks, to handle when a single case assignment fails we should put the creation of all tasks inside of a transaction to fail when one fails. We should then also show an error that the user can act upon rather than the generic error.

## AC
- [ ] Front end reflects the tasks that have been assigned (and specifically not assigned)
   - [ ] Tasks move/stay in judge assign queue
   - [ ] Tasks counts are updated/stay the same
- [ ] Front end shows actionable error for the failed assignment

**Comment by yoomlam** [comment]
Also, double check the case counts for each person in the upper-left are correct.

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | |||||||||
5 | ||||||
8 |  
```
The way the back end code works is when we have an error on assignment, we return an error, would take a good back end refactor to return the correctly assigned tasks along with the tasks that errored out. Will also take a large front end refactor to handle both the error and the correctly assigned tasks.
