### ISSUE TITLE
Deep dive into limitations of acting judges in caseflow - Queue

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13136]
[Relavent slack thread](https://dsva.slack.com/archives/CJL810329/p1578607001034900)
[Previous acting judge work](https://github.com/department-of-veterans-affairs/caseflow/pulls?utf8=%E2%9C%93&q=is%3Apr++%22Acting+judge%22)
[Batteam](https://dsva.slack.com/archives/CHX8FMP28/p1578069080207800) issues [related](https://dsva.slack.com/archives/CHX8FMP28/p1577821139163100) to [avljs](https://dsva.slack.com/archives/CHX8FMP28/p1570051221294100) from [slack](https://dsva.slack.com/archives/CHX8FMP28/p1567534420110500).

At the board, attorneys rotate through stints as acting judges. These users should have the same functionality as a normal judge (minus maybe having a judge team) while also being able to complete tasks as an attorney. 

To further understand what problems exist within caseflow for AVLJs, we need to
- [ ] Track down all actions on legacy cases a judge can perform in caseflow
- [ ] Track down all actions on ama cases a judge can perform in caseflow
- [ ] Track down all actions on legacy cases an attorney can perform in caseflow
- [ ] Track down all actions on ama cases an attorney can perform in caseflow
- [ ] Check which of the above actions an acting judge can perform

### AC
- [ ] List of limitations acting judges have on performing tasks in caseflow queue

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | ||||||||
5 | |||||||
8 |  
```
Blarg, acting judges making votes skew high.

**Comment by lomky** [comment]
Work is proving to be quite extensive. Splitting out an investigation into the Hearings capabilities of VLJs & Acting VLJs to a follow up.

**Comment by lomky** [comment]
## Summary

In Queue when the AVLJ user is acting in the VLJ or Attorney capacity, they are limited by:

  1. Lack of a Judge Team - No change expected
      - Where a true VLJ could choose an attorney on their team or any attorney when assigning or reassigning an AMA drafting task, AVLJ must to choose from a list of all attorneys
      - When a true VLJ user could assign a redrafting DispatchReturn or QualityReview task to any attorney on their team, AVLJ can onlyreturn to the drafting attorney.
 1. Acting as Attorney while AVLJ
     - VLJs cannot assign Legacy cases to the AVLJ user to draft
         - AVLJs are still listed as assignable attorneys
     - Minor: For Legacy appeals with VLJ Support tasks, the message to complete an admin action always calls the AVLJ a judge, even if they assigned the task in the capability as a drafting attorney
 1. Technical Debt
     - Acting VLJs can Request More Cases, and they are distributed both AMA and Legacy appeals. However the Legacy appeals are in a bad state, and not displayed in their Queue
         - This does not seem to be a flow used by the AVLJs, currently
         - Possible fix: Deactivate the button for AVLJ
     - Acting VLJ have no queue list of legacy cases with an JudgeLegacyAssignTask assigned to them
     - Acting Judges cannot act on JudgeLegacyAssignTask assigned to them, even if they navigate directly to the case

## Full writeup
[VLJ / AVLJ / Atty in Caseflow Queue](https://hackmd.io/dSs1Ly_xT-uYXwU9F-8Q5g?view)


## Follow Up Work
