### ISSUE TITLE
fix FactoryBot's creation of parent tasks assigned to different appeal

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13130]
## Description

In many cases, FactoryBot indirectly creates parent tasks when a test wants to create a particular task. However, the appeal for the parent task is not specified during creation, so the parent task is assigned to a new appeal when it should be assigned to the same appeal as the child task.  

## Technical notes

Child tasks whose parents are in a different appeal in lines like:
https://github.com/department-of-veterans-affairs/caseflow/blob/dc23a997793fa0989480b884429857755498c165/spec/factories/task.rb#L386, 408, 414, and maybe 427, 433, 105, and 109.

Solution: Add a `, appeal: appeal` parameter when creating parent or associated tasks.
Try applying the fix a few lines at a time to see if any tests fail.

Hunter has another idea: https://dsva.slack.com/archives/CQCUMFA0H/p1578610726034800?thread_ts=1578607111.032400&cid=CQCUMFA0H

**Comment by yoomlam** [comment]
Also highly related is invocations like `create(:ama_attorney_task, appeal: appeal)`, which don't set the parent task. For example, in https://github.com/department-of-veterans-affairs/caseflow/blob/dc23a997793fa0989480b884429857755498c165/spec/models/appeal_spec.rb#L157, if you insert `puts appeal.structure_render` within the `it` block, the tasks don't print because a parent task was not set to the root_task of the appeal (Tomas will work on a fix for this). `appeal.tree` will show the 2 AttorneyTask.

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |||||
3 | |||||||||
5 | |
8 |  
```

Could be a 2 because optimism! Echo team is pretty smart tbh. Any issue in tests will be a similar fix everywhere. May break a lot of tests.
