### ISSUE TITLE
Vitrual Hearings Daily Docket - Hearing type not reflecting hearings currently on docket

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13154]
- Description - On the Daily Docket, the "Hearing type" (in the top right corner) is not reflecting the hearings currently on the docket
- Observed - Changed hearing type to virtual. It's the only hearing on the docket. Hearing type displays as 'Video, virtual'. The print view is also affected.
- Expected: Hearing type displays as 'Virtual'

![image](https://user-images.githubusercontent.com/49729315/72379897-57b1cb80-36e2-11ea-9ba8-6294ca62f6be.png)

**Comment by pshahVA** [comment]
@ferristseng, didn't we check this in UAT?  I believe we can close this right?

**Comment by ferristseng** [comment]
Yes, I checked when I was doing setup...closing!
