### ISSUE TITLE
Virtual Hearings incorrect time on email reminder

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13156]
- Observed: Hearing time (5:30pm EST) displayed in Veteran, Judge, and POA emails doesn't match the time (12:30pm EST) displayed in Caseflow. 
- Expected: Hearing time displayed in emails matches the time displayed in Caseflow.

![image](https://user-images.githubusercontent.com/49729315/72380536-a14ee600-36e3-11ea-8d46-f747e233e4ee.png)

**Comment by ferristseng** [comment]
See https://dsva.slack.com/archives/C2ZAMLK88/p1579210928228200 for a lot of context.

This appears to be an issue with how the timezone is configured on the server. The rails server is configured to be EST time, whereas the rails console is loading in UTC time.

**Comment by ferristseng** [comment]
#13302 did not work. The timezone in UAT is still UTC for jobs. I'm wondering if the initializers are not running. Will pick this up the following week

**Comment by tomas-nava** [comment]
#13350 worked; jobs in UAT are now running with the `America/New_York` timezone.
```
[2020-02-11 18:39:05 -0500] Timezones for VirtualHearings::CreateConferenceJob are (zone: America/New_York) (getlocal: EST)
```
