### ISSUE TITLE
Hook up all the pages in the "1. Check Documents" step to live data

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1315]
We send certification data down to the client and store it in the Redux store. We should connect all these pages to the Redux store so we can display live data in them.

To validate this, go to `/certifications/new/XXX`and `/certifications/new/XXX` in UAT and check that the data from VACOLS and VBMS for form9, nod, soc, and ssoc dates are being accurately displayed. We should try scenarios where:

- all the documents match
- some document dates don't match
- the appeal was already certified
- the veteran was not found

**Comment by amprokop** [comment]
These two issues are both components of this issue:

https://github.com/department-of-veterans-affairs/caseflow/issues/1426
https://github.com/department-of-veterans-affairs/caseflow/issues/1424

**Comment by amprokop** [comment]
@nemodjuric, make sure we add the SSOC dates, then we can put this in Validation.

**Comment by kierachell** [comment]
**PASSED**

_Missing Docs_ works
<img width="960" alt="screen shot 2017-04-14 at 8 07 45 pm" src="https://cloud.githubusercontent.com/assets/18075411/25059049/3fdc2a98-214e-11e7-9c73-2d01a08532eb.png">

_Mismatched dates_ works
<img width="956" alt="screen shot 2017-04-14 at 8 33 44 pm" src="https://cloud.githubusercontent.com/assets/18075411/25059332/9fc49fe0-2152-11e7-8fa2-905b3e61c2ba.png">


_All documents_ works
<img width="944" alt="screen shot 2017-04-14 at 8 39 44 pm" src="https://cloud.githubusercontent.com/assets/18075411/25059331/8d7cab7a-2152-11e7-95e3-c8bdbbc1c0c1.png">

_Already certified_ works

<img width="1057" alt="screen shot 2017-04-14 at 8 42 12 pm" src="https://cloud.githubusercontent.com/assets/18075411/25059353/1af5d9ea-2153-11e7-971e-3cc03df50417.png">


_Not found_ works?
<img width="1040" alt="screen shot 2017-04-14 at 8 45 42 pm" src="https://cloud.githubusercontent.com/assets/18075411/25059359/632128f0-2153-11e7-80fb-f8ef9d605565.png">
