### ISSUE TITLE
Api v3 - use a consistent parameter to identify veterans

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/caseflow#13167]
## Description
Update v3 endpoints to use a `ssn` parameter to identify relevant veterans.

## Background/context/resources
API V3 endpoints were identifying veterans through different means.
The current v2 appeals status uses `BGSService`'s `fetch_file_number_by_ssn`, so the new v3 endpoints will use that convention.

**Comment by pkarman** [comment]
I'm not sure this is what we want to do.

The Veteran may be responding to correspondence that reflects a file number (which could be a claim ID or SSN) and IIRC the form instructs them to reference that file number.

I.e. if the form explicitly asks for a SSN, then this change is fine. But if the form asks for a file number, then calling it a SSN will be misleading.

**Comment by erluti** [comment]
The form asks for the SSN and also asks for the `VA File Number (if applicable)`.
