### ISSUE TITLE
ActiveRecord::RecordNotUnique index_hearing_appeal_stream_snapshots_hearing_and_appeal_ids

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13171]
## Description
We're seeing a sentry alert with this error:
```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_hearing_appeal_stream_snapshots_hearing_and_appeal_ids"
DETAIL:  Key (hearing_id, appeal_id)=(150130, 175004) already exists.
: INSERT INTO "hearing_appeal_stream_snapshots" ("hearing_id", "appeal_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4)
```

## Background/context/resources
- [Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7503/)

**Comment by yoomlam** [comment]
Another one: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7503/

<img width="542" alt="image" src="https://user-images.githubusercontent.com/55255674/73211521-0b1eb500-4112-11ea-8bf6-f015b7edfda7.png">
