### ISSUE TITLE
Make the Cancel Certification modal work with Certification v2 [2]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1318]
The link currently does nothing. Sad! Make sure that the modal renders and functions properly in v2. It should function identically to the modal in v1.

**Comment by nemodjuric** [comment]
Right now there is no success page, when you submit cancellation, it takes you to the previous page (similar if you close the modal or click Cancel). However, the certification_cancellation record is created in database. 
For success page refer to: #1603

**Comment by kierachell** [comment]
Pages other than `check_documents` are missing `certification_id` so cannot cancel from there.

<img width="741" alt="screen shot 2017-04-17 at 3 02 21 pm" src="https://cloud.githubusercontent.com/assets/18075411/25100655/e8bb36c2-237e-11e7-9cfa-91c6f73ac22f.png">


<img width="940" alt="screen shot 2017-04-17 at 3 03 29 pm" src="https://cloud.githubusercontent.com/assets/18075411/25100688/0a156d38-237f-11e7-8153-65de1237ad6d.png">

**Comment by kierachell** [comment]
**PASSED**

# From Sign and Certify
```
irb(main):003:0> CertificationCancellation.all[-1]
  CertificationCancellation Load (1.0ms)  SELECT "certification_cancellations".* FROM "certification_cancellations"
[2017-04-25 16:13:40 -0400]   CertificationCancellation Load (1.0ms)  SELECT "certification_cancellations".* FROM "certification_cancellations"
=> #<CertificationCancellation id: 7, certification_id: 96, cancellation_reason: "Other", other_reason: "this vet isHitler, won't certify...", email: "toosoon@jokes.com">
```
<img width="1006" alt="screen shot 2017-04-25 at 4 13 22 pm" src="https://cloud.githubusercontent.com/assets/18075411/25405733/39052ba2-29d2-11e7-910b-8a39dfb7864e.png">

# From Confirm Hearing Details
```
[2017-04-25 16:15:33 -0400]   CertificationCancellation Load (1.0ms)  SELECT "certification_cancellations".* FROM "certification_cancellations"
=> #<CertificationCancellation id: 8, certification_id: 97, cancellation_reason: "VBMS and VACOLS dates didn't match and couldn't be...", other_reason: nil, email: "asd@dank.com">
```

# Confirm Case Details

```
irb(main):007:0> CertificationCancellation.all[-1]
  CertificationCancellation Load (1.0ms)  SELECT "certification_cancellations".* FROM "certification_cancellations"
[2017-04-25 16:22:53 -0400]   CertificationCancellation Load (1.0ms)  SELECT "certification_cancellations".* FROM "certification_cancellations"
=> #<CertificationCancellation id: 10, certification_id: 99, cancellation_reason: "Pending FOIA request", other_reason: nil, email: "asd@asdasdasdasd.gov">
```
