### ISSUE TITLE
Improve error handling for BGS calls in team assignment

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13193]
There is currently no error handling for BGS::ShareError thrown on calls to `BGSService.new.get_participant_id_for_css_id_and_station_id`

This will result in unexpected UX on the client side when support is looking up users.

To replicate the problem, pass in an non-existent CSS id:

```
irb(main):019:0> bgs.get_participant_id_for_css_id_and_station_id('foobar', '354')
[snip]
Traceback (most recent call last):
        5: from (irb):19
        4: from app/services/external_api/bgs_service.rb:275:in `get_participant_id_for_css_id_and_station_id'
        3: from app/services/metrics_service.rb:13:in `record'
        2: from app/services/metrics_service.rb:14:in `block in record'
        1: from app/services/external_api/bgs_service.rb:278:in `block in get_participant_id_for_css_id_and_station_id'
BGS::ShareError (SecurityWebServiceBean-->findPtcpntId-->findPersonScrtyLogByUserIdLctnId-->User foobar is invalid.)
```

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |||||||||
3 | |||
5 | 
8 |  
```
Error is going to be the same 99% of the time (user cannot be found in BGS).Error handling should also be straightforward.
