### ISSUE TITLE
Cannot find issue with vacols ID: and sequence ID: in VACOLS

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13207]
[Sentry alert](http://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7034/events/latest/).

Looks like all of these were spawned from a user deleting an issue in caseflow that does not exist in VACOLS. The question is, why are we displaying issues in caseflow that do not exist in vacols?

**Comment by ajspotts** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9679/
