### ISSUE TITLE
Cannot read property 'disposition' of undefined

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13208]
Sentry Alerts
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7869/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6352/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5299/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5117/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)
[Here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4471/?query=is%3Aunresolved%20%22Cannot%20read%20property%20%27disposition%27%20of%20undefined%22)

Seems to occur both when the [hearing has been deleted in vacols](https://dsva.slack.com/archives/CLRTL92TW/p1579640832010700?thread_ts=1579620081.004800&cid=CLRTL92TW) or the [hearing association on a hearing task does not exist](https://dsva.slack.com/archives/CHX8FMP28/p1575556723017300).

**Comment by yoomlam** [comment]
Found this ticket and the referenced solution for this [Bat Team support ticket](https://dsva.slack.com/archives/CHX8FMP28/p1580416217111100?thread_ts=1580409702.108100&cid=CHX8FMP28)

Thanks Hunter!
