### ISSUE TITLE
Time of virtual hearing is editable after hearing date

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#13219]
### Summary
I noticed in UAT that I'm still able to (1) edit the hearing time and (2) send emails _after_ the date on which the hearing occurred. I would expect that the hearing time would not be editable after the hearing date. (If the hearing was postponed and rescheduled, and therefore the hearing date was in the future, I would expect the time to be editable again.)

### Observed
_(screenshots from UAT)_

1. Log in to UAT as CF_RIKER_317 (a Hearing Coordinator user)
1. Go to the Hearing Schedule overview page and select a Daily Docket with a virtual hearing on a date in the past
1. Edit the hearing time and save.
    ![Screen Shot 2020-01-22 at 2.03.07 PM.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/6ed978c8-3a1e-4ccb-afec-355b8c0221ba)
1. See that the blue info alert displays.
    ![Screen Shot 2020-01-22 at 2.03.30 PM.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/1bc5a74d-0f9b-4ffc-9bc5-1bbfab23155b)
1. See that emails are sent.
    ![Screen Shot 2020-01-22 at 2.04.26 PM.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/41c91062-6560-4b9a-a4ed-7fdc56133011)

### Expected
Hearing time is _not_ editable (field is disabled) for virtual hearing dates that are in the past.

**Comment by pshahVA** [comment]
I thought that this may only be editable until the hearing is locked (24 hours after the hearing) however, I checked a hearing in production from a week ago and the time field is editable.  We need to investigate why this is the case.  It didn't matter until this triggered an email to be sent.
