### ISSUE TITLE
Document Viewer | "Add Comment" button styling

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1321]
As a user, I want to be able to easily find a way to add a comment in the PDF viewer. 

## Note:
In our first iteration, we used a text link for adding a comment and users weren't able to find it easily. We received feedback to make it more prominent. We tried this new style with the button for iteration 2 and users successfully found it.  

## Acceptance Criteria
- Validate that the add comment button is in the styling of [USWDS default primary](https://standards.usa.gov/components/buttons/)
- Validate that the plus SVG is before the `Add comment` in the button 
  [Plus SVG file can be found here!](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Plus%20Icon.svg)
- Validate that it is 12px between Comment header and horizontal line
- Validate that the comments scroll right under the horizontal line.

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25194856/c6ed1286-2509-11e7-9e55-d2ad1cce0e35.png)

**Comment by mdbenjam** [comment]
@abbyraskin The plus icon doesn't seem to be right. Shows up as a box.

**Comment by abbyraskin** [comment]
@mdbenjam hmm, I'll look into it. could you send a screenshot?

**Comment by mdbenjam** [comment]
@abbyraskin You can just click on the svg link above.

**Comment by abbyraskin** [comment]
OK, I did that, but can't see what's causing the problem...I think it's Gina's file. @gnakm can you help diagnose? 🙏

**Comment by abbyraskin** [comment]
hm, it looks correct to me, now that i'm back on a real computer and not my phone...

**Comment by mdbenjam** [comment]
Added the last three AC in response to our Slack conversation

**Comment by kierachell** [comment]
**PASSED**
nice save with the scrollbar, @mdbenjam 
![addcomment](https://cloud.githubusercontent.com/assets/18075411/25243155/16872a28-25ca-11e7-90f9-98fb969f9b1a.gif)
