### ISSUE TITLE
Hearing type dropdown doesn't display after hearing date

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#13218]
### Summary
In UAT, on the Hearing Details page for a hearing (virtual or video) that has a hearing date in the past, the Hearing Type dropdown disappears and instead reverts to a 'label' in the top section of the page. I would expect that the Hearing Type field would always remain in the same position, and the only thing that varies is whether it is enabled / disabled.

### Observed

_(screenshots from UAT)_

1. Log in to UAT as CF_RIKER_317 (a Hearing Coordinator user)
1. Go to the Hearing Schedule overview page and select a Daily Docket with a hearing (virtual or video) on a date in the past
1. Open the Hearing Details for the hearing
1. See that the Hearing Type is a 'label'
    ![Screen Shot 2020-01-22 at 10.58.59 AM.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/04037303-9b7c-462c-ba1c-46681b848051)

### Expected
Hearing Type displays as a disabled dropdown field

**Comment by aplybeah** [comment]
@nicholer just to double check, the desired outcome is something like this:
<img width="979" alt="Screen Shot 2020-01-29 at 3 43 23 PM" src="https://user-images.githubusercontent.com/37313082/73395811-350cde80-42ae-11ea-9868-329d625ab256.png">

**Comment by nicholer** [comment]
@aplybeah Yes, the dropdown looks good on both of those.

On the first image, when the hearing is Video, ideally the Type would never display as a label in that top bar. But that should probably be another (lower priority) ticket, correct?
