### ISSUE TITLE
Motion to Vacate | Granted | Support multiple AMA appeal streams

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13211]
## User or job story
At the board, multiple appeal streams need to be supported in order to support post-decision motions.

## Acceptance criteria
**Docket Number**
- [ ] Create a new field on Appeal, called docket_number
- [ ] Populate docket_number when creating an appeal (at the same time as populating the receipt date), with the current format `"#{receipt_date.strftime('%y%m%d')}-#{id}"`
- [ ] Backfill docket_number for existing appeals
- [ ] Use the new field docket_number, instead of the method
- [ ] Remove the docket_number method in the Appeal model

**Type**
- [ ] Create a new field on Appeal, called type
- [ ] When creating a new appeal from Intake, populate "type" with "Original"
- [ ] Backfill "type" for existing appeals
- [ ] Use new field instead of the method
- [ ] Remove "type" method in Appeal model

### Background/context

Appeal streams indicate work on the same docket number, but happening on different appeals.  This will mimic the structure being used for legacy appeals.  New appeal streams will have a different docket type, depending on the work being done on that appeal.

To see an example of a Legacy Appeal with multiple docket types under the same docket number, see Legacy Appeals with the following vacols_ids:
["3017739", "3703912", "3726007", "3726018", "3996075"]

You can look at the `docket_number` and `type` for these legacy appeals.

### Technical notes
This can be done in multiple PRs
1. Add the new DB fields and backfill them
1. Switch to using the new fields instead of the methods

**Comment by hschallhorn** [comment]
Related! #11678

**Comment by nanotone** [comment]
I'm going to go ahead and call this issue done for the sake of sprint planning; the one remaining open PR is blocked externally, isn't very relevant to upcoming MTV work, and is outside of what we expected with the original 3-point estimate.
