### ISSUE TITLE
Motion to Vacate | Make draft decision URL optional

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13228]
## User or job story
As a motions attorney and a judge user, the draft decision documents are not shared through URL to shared drives. They are typically sent instead through email.

## Acceptance criteria
- [ ] Make the field for submitting a drive URL to the draft decision document optional
- [ ] Add instructions for submitting via email
  - [ ] This is on the "Send to judge" action for the VacateMotionMailTask, as well as on the "AddressMotionToVacateTask"
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

**Note:** making the draft URL optional may be partially done in some places (like for denial but not for dismissal).

## Release notes
N/A (will save these for a bigger feature)

### Designs
TBD

### Background/context
This is an adjustment to the current design from some additional discovery. Martina has discovered through conversations with users that the drive URLs are not what are used or may not work.

**Comment by leikkisa** [comment]
Holding off, Jim is going to suggest a business process change.

Instead, we should not make this mandatory for users who don't know how to use this (in case they are still using email).

**Comment by leikkisa** [comment]
@msj0nes Does the AC for this ticket look correct to you based on what you learned about the MTV decision document process?

**Comment by jcq** [comment]
@rutvigupta-design @leikkisa Do we have designs and/or copy for the instructions for submitting via email?

**Comment by rutvigupta-design** [comment]
Design for VLJ (denied/dismissed)
![Address MTV _ Deny Final](https://user-images.githubusercontent.com/51714306/75580146-3e1bd780-5a35-11ea-8547-8646e394dc2c.jpg)

**Comment by rutvigupta-design** [comment]
Design for motions attorney (denied/dismissed)
![Review Motion _ Revised _ Dismiss](https://user-images.githubusercontent.com/51714306/75582102-da93a900-5a38-11ea-8c04-21ee991027ce.png)
