### ISSUE TITLE
Remove begin_decision_review_phase method from JudgeAddingTask model

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13225]
## Description

Last year we changed how JudgeDecisionReviewTasks are handled, creating them independently rather than transforming the JudgeAssignTask. At the time we left the function `begin_decision_review_phase` in place to alert Sentry if we saw this still happening.

## Background/context/resources

[The code to remove](https://github.com/department-of-veterans-affairs/caseflow/blob/476f506917f03b5140e123000d710d0f87df060a/app/models/tasks/judge_assign_task.rb#L15)
[Why we left this in for a ~month~ bit](https://github.com/department-of-veterans-affairs/caseflow/pull/11140#discussion_r295799101)

## Technical notes

Confirm there are no remaining Appeals in the old state:
```
select count(*)
from tasks atty_tasks
join tasks judge_tasks
  on judge_tasks.id = atty_tasks.parent_id
where atty_tasks.type = 'AttorneyTask'
  and judge_tasks.type = 'JudgeAssignTask'
  and atty_tasks.status not in ('completed', 'cancelled')
  and judge_tasks.status not in ('completed', 'cancelled');
```

## AC
 - [ ] All old-style AMA appeals are through the JudgeAssignTask -> JudgeDecisionReviewTask process
 - [ ] Dead code removed!

**Comment by kevmo** [comment]
# Estimation: 1

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||
2 | |||||||
3 | 
5 | 
8 | 
```

Why is this a 1? This isn't complicated -- the code just had to be left in because production data was in a state that required this code.  Ensure prod data is no longer in this state, then make that change! 🎶
