### ISSUE TITLE
UAT setup for usability testing for virtual hearings

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13238]
#### User Story
Setup the UAT environment to have the proper users, data, and permissions for testing in UAT with Hearing Branch users. (Usability testing is scheduled for 1/29 and 1/30)

##### Data
- [x] At least 5 different hearing docket days (e.g. Mon, Tues, Wed, Thurs, Fri), one for each of the 5 test participants
- [x] Ideally the hearing docket days are for a regional office outside EST (e.g. the Montgomery, Alabama regional office in CST)
- [x] Each hearing docket day has at least 3 Veterans scheduled for the morning (8:30am EST / 9:30AM CST) timeslot
##### User account permissions
- [x] 1 Hearing Coordinator user with admin access to view the /jobs page

**Comment by ferristseng** [comment]
> * [x]  At least 5 different hearing docket days (e.g. Mon, Tues, Wed, Thurs, Fri), one for each of the 5 test participants

|    Day    |        RO        |
|-----------|------------------|
| 2/10/2020 | New York, NY     |
| 2/11/2020 | Montgomery, AL   |
| 2/12/2020 | Oakland, CA      |
| 2/13/2020 | Albuquerque, NM  |
| 2/14/2020 | Boise, ID        |

> ##### User account permissions
> * [x]  1 Hearing Coordinator user with admin access to view the /jobs page

| ID  | CSS ID          | Name                   | Jobs Page |
|-----|-----------------|------------------------|-----------|
| 123 | CF_LAFORGE_317  | CF_LAFORGE_317 TESTING |           |
| 106 | CF_RIKER_317    | CF_RIKER_317 TESTING   |           |
| 399 | MOHI317_CF      | MOHI317_CF TESTING     |           |
| 89  | CF_KHAN_317     | CF_KHAN_317 TESTING    |    YES    |
| 402 | KRIS317_CF      | KRIS317_CF TESTING     |           |

**Comment by ferristseng** [comment]
This is done
