### ISSUE TITLE
Motion to Vacate | Denied | Remove URL Field Requirement Condition 

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13236]
## Description

Currently, the URL field for both the litigation support 'Review Motion to Vacate' and the VLJ (Judge) 'Address Motion to Vacate' task are mandatory to complete each workflow. We need to remove the condition until the Board acknowledges and/or establishes a process for storing denial documents. There is no current process in place to store denial documents in a BVA digital space  and no location identification system for these documents. 

**Acceptance Criteria**

- As a Litigation Support Team Member (Motion Attorney), I can send a task to Judge without the URL field requirement.
- As a VLJ (Judge), I can address a motion to vacate task without the URL field requirement. 

## Background/context/resources
Visual 
![image](https://user-images.githubusercontent.com/41164406/73013614-afd58580-3de6-11ea-9f9f-0d6de8e3b6c1.png)

## Technical notes
N/A

**Comment by jcq** [comment]
Updated UI:

<img width="561" alt="Screen Shot 2020-01-23 at 16 48 14" src="https://user-images.githubusercontent.com/2581274/73036376-3fd3f900-3e00-11ea-8530-f1ce46d6fa2c.png">
<img width="535" alt="Screen Shot 2020-01-23 at 16 48 24" src="https://user-images.githubusercontent.com/2581274/73036377-3fd3f900-3e00-11ea-8e63-727daeb62663.png">
