### ISSUE TITLE
SPIKE: Investigate if any VAMC claims ended up in the wrong location

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1323]
Investigate if any VAMC claims ended up in the wrong location (51 instead of 54)

**Comment by kierachell** [comment]
https://github.com/department-of-veterans-affairs/caseflow/blob/f8d39d6e5c527f6a53f90bbaa83b61e54f29a04e/app/services/appeal_repository.rb#L215

@shanear 
![nich](https://cloud.githubusercontent.com/assets/18075411/24273861/200a0762-0ffb-11e7-8b6a-fa495f048aaf.png)

**Comment by shanear** [comment]
Dug in on this issue. There have been 3 appeals with VAMC special issue checked. 2 Full grants and 1 Remand. The Remand is currently in location 54. We are good.
