### ISSUE TITLE
Duplicate Veteran Records Found | Update Error Message 

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13240]
## Description
The current error message directs users to open a YourIT ticket. The correct next step is for users to contact their local regional office.<br>

>**AMO Approved Replacement Copy**
From: Chi, J 
Sent: Thursday, January 23, 2020 4:17 PM

**Related**
https://github.com/department-of-veterans-affairs/caseflow/issues/11742  
https://github.com/department-of-veterans-affairs/caseflow/issues/12077

### Acceptance Criteria
As an Intake user, when I encounter error associated to a veteran having a duplicate record, show alert with updated copy below. 

**Use:**
_This Veteran has a duplicate record in the Corporate database (CorpDB).  Please follow your locally established procedures for addressing duplicate records to the assigned point-of-contact of the regional office._

#### Current Error Copy
![image](https://user-images.githubusercontent.com/41164406/73031853-4025c180-3e0b-11ea-96ea-04596aff46d5.png)

#### Screenshot of new message
<img width="642" alt="Screen Shot 2020-02-12 at 14 19 56" src="https://user-images.githubusercontent.com/282869/74369598-9ef3b080-4da3-11ea-84ad-b04626a60cf7.png">

## Background/context/resources
BGS Integration **1/23/19 2:30pm call** revealed a different process for VA application users to report 'Duplicate Veteran Records'. From call, per M. Napper [Compensation Service, Business Management Staff], the direction is for users to contact the designated 'Duplicate Record Coordinator' at their local regional office.

**Comment by msj0nes** [comment]
Please provide screenshot of new message once complete.

**Comment by nanotone** [comment]
Edited the issue description with a screenshot of the new error message.

**Comment by msj0nes** [comment]
# Completed 

AMO notified of completion along with screenshots of new error message. 
>Sent: Thursday, February 13, 2020 2:58 PM
Subject: GH 13240 - Caseflow Intake - Duplicate Veteran Record Found | Update to Error Message [Post-BGS Call] - COMPLETE
