### ISSUE TITLE
Capability to Support ITF for Supplemental Claims

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13248]
# Background/Context
For supplemental claims that are received within a year of the initial decision, the effective date of the claim is the same as the effective date of the prior decision.  Thus, the application of Intent to File (ITF) to supplemental claims received within a year is not necessary, as it does not benefit the Veteran (the Veteran's effective date is earlier under AMA/supplemental claim rules than it would be under the ITF rules).  However, if a claim is received more than a year after the prior decision was issued, Veterans benefit from the ITF process, as it provides an earlier effective date.  There is a Business need for the system to recognize when VA receives a supplemental claim that is outside of the one-year window from the prior decision, so an EP 040 with a claim label “Supplemental Claim Rating >year" can be applied to that claim and provide notice to the user that there could be an applicable ITF associated to the claim.  Additionally, when this EP 040 with a claim label “Supplemental Claim Rating >year” is established, and a pending ITF exists for that Veteran, the status of the pending ITF associated to that Veteran should be automatically updated from "Active" to "Claim Received"

# Success Criteria 
 
# Stakeholders- AMO
- Jane Che 
- Keronica Richardson
- Melissa Milenkovic

## User Story
- [As a VBA Caseflow Intake user, I have the ability to establish EP 040 with Claim Label “Supplemental Claim Rating >year”](https://github.com/department-of-veterans-affairs/caseflow/issues/13647)
- [As a VBA Caseflow Intake user, VBMS should reflect an updated status of an existing ITF from "Active" to "Claim Received" whenever Caseflow establishes a EP 040 with claim label  “_Supplemental Claim Rating >year_"](https://github.com/department-of-veterans-affairs/caseflow/issues/13921)

# Designs and Workflow
Not required for this line of work. 

# Prior Research/Reference/Resources

**Comment by leikkisa** [comment]
I think the two things I would need for this are:
1. The new EP codes
1. More information on ITFs:
  - Are these for any supplemental claims a veteran files, or are they for specific issues?
  - If a veteran files an ITF, and then files a SC at the less than a year mark, should the ITF still be marked with "Claim received?"
  - If a veteran files another supplemental claim after an ITF has been marked "Claim received", is there any action necessary?

**Comment by leikkisa** [comment]
[Notes from a working group kickoff meeting and demo on 3/4/2020](https://docs.google.com/document/d/1whjV_lj5SIffyCgs-IZk68lOAKk9kaZm579ZK0hbYR4/edit)

Caseflow's scope is limited to creating the EPs for Supplemental Claims with the right code indicating whether the issues on it were last decided one year before the receipt date.

If multiple issues are on the SC, and any one of them is greater than a year old, then the issues for that EP code should all go onto a "Greater than 1 year" EP code.

**Comment by leikkisa** [comment]
I got information that this was one of the proposed EP codes:
040SCRGTY

**Comment by msj0nes** [comment]
# Tracker 
 **Key:** <br>
Not Started - ⚪️  
In Progress -  🚧       
Complete -  ✅ 
Blocked - 🔴  
Pending Stakeholder/SME Feedback  ☎️  

. |Research | Design |  Development | Pilot | Release
-- | -- | -- | -- | -- | -- 
[As a VBA Caseflow Intake user, I have the ability to establish EP 040 with Claim Label “Supplemental Claim Rating >year”](https://github.com/department-of-veterans-affairs/caseflow/issues/13647)|  :white_circle:  | :white_circle:| :white_circle: | :white_circle:   |  :white_circle: 		
[As a VBA Caseflow Intake user, VBMS should reflect an updated status of an existing ITF from "Active" to "Claim Received" whenever Caseflow establishes a EP 040 with claim label “Supplemental Claim Rating >year"](https://github.com/department-of-veterans-affairs/caseflow/issues/13921)| :white_circle:  | :white_circle:   |  :white_circle: |  :white_circle: |  :white_circle:

**Comment by msj0nes** [comment]
## Stakeholder Provided Information

### User Story 66655 – Ability to Establish EP 040 with Claim Label “Supplemental Claim Rating >year” 

**Value Statement:**
As an authorized user processing a Compensation supplemental claim, whenever VA receives a Compensation supplemental claim more than one year from the date of the prior decision, I need the system to establish an EP 040 and claim label “Supplemental Claim Rating >year”, so that I can use system automation to ensure that I apply the correct effective date to supplemental claims that may also have an applicable, pending ITF.
 
**Acceptance Criteria:**
Whenever VA receives a Compensation supplemental claim that is more than one year from the date of the prior decision, the system will establish an EP 040 with claim label “Supplemental Claim Rating >year”

### User Story 66656 - Ability to Auto-Update the Status of an Existing ITF Based on Receipt of Supplemental Claim 

**Value Statement:**
As an authorized user processing a supplemental claim, I need the system to auto-update the status of an existing ITF from "Active" to "Claim Received" whenever the system establishes a EP 040 with a claim label of label “Supplemental Claim Rating >year”.  

**Acceptance Criteria:**
When the system establishes an EP 040 with a claim label of label “Supplemental Claim Rating >year”, and an active ITF exists for the claimant to whom the EP 040 is associated, the batch process will trigger and the system will auto update the ITF associated to the Veteran from "Active" to "Claim Received."

> Opportunity Score - 9 - High Importance For AMO due to high level of interest this functionality for the Under Secretary of Benefits (USB).

**Comment by leikkisa** [comment]
Closing this in favor of Jira https://vajira.max.gov/browse/CASEFLOW-142
