### ISSUE TITLE
Document Viewer | Comment states: selecting comments

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1324]
## Story

As a user, I want to see which pages each comment on the side are correlated with. 

## Description 
When a user clicks a comment box on the side menu, s/he should see the document on the left with comment icon associated with the comment in the selected state.

## Acceptance Criteria
- Verify that when a comment box is selected, the document viewer displays the page containing the comment, and highlights the the associated comment icon
- Verify that when a comment box is selected, the comment icon have the USWDS focus blue, and comment box has a drop shadow as shown in mockup below

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24973924/8fae094a-1f8e-11e7-8878-c4be2263c215.png)

**Drop shadow for comment box**
![image](https://cloud.githubusercontent.com/assets/13420618/24973910/82a0e682-1f8e-11e7-9e6c-649d1da21c6f.png)

**Comment icon** 
![image](https://cloud.githubusercontent.com/assets/13420618/24973963/b10d858e-1f8e-11e7-94bd-edc39dc74bd4.png)

[Comment icon selected svg
](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20comment%20active.svg)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)

### Related Stories
#1268 | Documents List | Comments: expand/collapse view
#1283 | Save and add comment

**Comment by abbyraskin** [comment]
@mdbenjam here's the story we mentioned -- awesome if you can pull it in to this sprint (or if it logically makes sense to work on next?), but I'll leave it in ready for dev for now

**Comment by abbyraskin** [comment]
Note: this is an outdated mock, so ignore any info in design not related to this specific story.

@gnakm assigning to you to create an svg for the selected comment state.

**Comment by mdbenjam** [comment]
This is probably easiest to do after #1268 is merged

**Comment by NickHeiner** [comment]
Marking as blocked on #1268.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. In Reader, create/select comments
2. Validate the behavior and color against mocks and AC. 

Screenshots:
![readercommentpage](https://cloud.githubusercontent.com/assets/23038505/25489551/25948cea-2b38-11e7-8cad-2abedf180e42.gif)
