### ISSUE TITLE
Write Task Available Actions Tech Spec

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13251]
## Description
We have found a multitude of issues and heartache around the Task model functions [`available_actions_unwrapper`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L279), [`actions_available?`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L288), and [`actions_allowable?`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L294).

 - [The names of the functions are unintuitive](https://github.com/department-of-veterans-affairs/caseflow/issues/9055)
 - [The usage of the functions is inconsistent and buggy in the code](https://github.com/department-of-veterans-affairs/caseflow/issues/12840)
 - Programmers have a hard time generally know what the functions do and when to call them
 - [Different tasks implement the functions to different purposes.](https://github.com/department-of-veterans-affairs/caseflow/issues/12713#issuecomment-554003725)

This tech spec exists to create a small-scale remodel focused on bringing all the existing actions into alignment. Questions to be answered:

 - Are all the functions necessary?
 - When should each of the necessary functions be called?
 - Are there more intuitive names for these functions?
 - What does the breakout of the work look like?
 - How do the existing tickets this is blocking fit in?

This tech spec _does not_ exist to revamp the entire architecture of how we handle task actions. [There is an potential tech spec for that larger effort already](https://github.com/department-of-veterans-affairs/caseflow/issues/10894). This ticket's scope is much smaller, focused on figuring out how to make the existing code architecture consistent, comprehensible, and well-engineered.

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | |||||||||||||
5 | 
8 | 
```

Standard 3 for Tech Spec.

**Comment by araposo-tistatech** [comment]
@lomky I see this one is in the Define pipeline, is there something specific here Product will need to have addressed with Stakeholders?

**Comment by lomky** [comment]
@araposo-tistatech I don't believe so! This should be shovel-ready
