### ISSUE TITLE
Document Viewer | Comment box when selected vs unselected

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1325]
## Story

As a user, I want to know when my comments are selected or unselected so I know where I am in relation to the open document. 

## Acceptance Criteria 

- Verify that an unselect comment has a `grey-lighter` outline
- Verify that a selected comment has USWDS focus blue

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24272039/e41d5442-0ff1-11e7-9f99-4e9160cb2cfe.png)

**Comment by mdbenjam** [comment]
@gnakm What's the radius on the border curve?

**Comment by gnakm** [comment]
@mdbenjam 3 px !

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: UAT
Browsers Checked: FF and Chrome

Steps to Validate: 
1. Go to reader for an appropriate veteran
2. Select one of the documents with comments (without, you have to add them).
3. Select one of the multiple comments and compared the one selected to one that is not
4. Verify that the view matches AC.

Screenshots: 
<img width="1389" alt="screen shot 2017-04-04 at 8 55 52 am" src="https://cloud.githubusercontent.com/assets/23038505/24657549/a9d0f9de-1914-11e7-821a-4d954a1ed1af.png">

**Comment by gnakm** [comment]
@mdbenjam another thing to add is that it looks like there is an active comment box in a comment box. An active comment box should be the same width as a saved comment.
