### ISSUE TITLE
Investigate tasks with type "Task" in production

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13268]
There are currently 54 tasks in production on 34 appeals with a type of "Task"
```ruby
tasks = Task.open.where(type: Task.name)
tasks.count
=> 54
tasks.pluck(:appeal_id).uniq.count
=>34
tasks.order(:created_at).last.created_at
=> Wed, 13 Nov 2019 20:09:07 UTC +00:00
```

## AC
- [ ] Investigate how or why tasks without a more specific type were created
- [ ] File ticket to fix if needed

**Comment by lomky** [comment]
Timeboxing to a 3!
