### ISSUE TITLE
[Sentry alert] Don't alert if RootTask is already on_hold or RootTask should be updated

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13278]
## Description

In `when_child_task_created`, we update the RootTask's status to `on_hold` if the task is active. We alert when the RootTask is not `active?`.

Also Peter suggested to "add logic to `when_child_task_created` to account for a safelist of child task names to actually change the root task status when it is not open."
(See this thread https://dsva.slack.com/archives/CJL810329/p1580232125082100?thread_ts=1580230515.077500&cid=CJL810329)

## Background/context/resources

https://dsva.slack.com/archives/CLRTL92TW/p1580228312051500

See PR #12576 and associated ticket #12574

## Technical notes

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/root_task.rb#L36-L43

```
  # Do not change the status of closed or on_hold RootTasks when child tasks are created for them.
  def when_child_task_created(child_task)
    if active?
      update!(status: :on_hold)
    elsif !self.class.creatable_tasks_types_when_on_hold.include?(child_task.type) && !on_hold?
      Raven.capture_message("Created child task for RootTask #{id} but did not update RootTask status")
    end
  end
```

**Comment by yoomlam** [comment]
Also consider the case where all tasks are not open (https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8012)
```
Appeal 1267 [id, status, updated_at]
└── RootTask 20594, completed, 2019-07-22 12:26:03 UTC
    ├── DistributionTask 50176, completed, 2019-06-11 10:55:15 UTC
    │   └── EvidenceSubmissionWindowTask 50177, completed, 2019-02-15 15:08:51 UTC
    ├── TrackVeteranTask 126846, cancelled, 2019-03-26 04:08:38 UTC
    ├── TrackVeteranTask 151100, cancelled, 2019-06-27 22:07:47 UTC
    ├── TrackVeteranTask 151101, cancelled, 2019-06-27 22:07:47 UTC
    ├── TrackVeteranTask 151102, cancelled, 2019-06-27 22:07:47 UTC
    ├── TrackVeteranTask 151103, cancelled, 2019-06-27 22:07:47 UTC
    ├── JudgeDecisionReviewTask 231628, completed, 2019-07-17 15:10:08 UTC
    │   └── AttorneyTask 237068, completed, 2019-07-08 11:52:48 UTC
    ├── TrackVeteranTask 253907, completed, 2019-07-05 19:20:10 UTC
    ├── InformalHearingPresentationTask 253908, completed, 2019-09-05 12:20:45 UTC
    │   └── InformalHearingPresentationTask 360455, completed, 2019-09-05 12:20:45 UTC
    └── BvaDispatchTask 278320, completed, 2019-07-22 12:26:03 UTC
        └── BvaDispatchTask 278322, completed, 2019-07-22 12:26:03 UTC
``` 
Would be good to include the `child_task.id` in the error message -- What child_task was created in this appeal (can't tell by the dates)?

**Comment by ajspotts** [comment]
If the task that attempts to reopen the root task is a mail task then the root task should remain closed (https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8288)

Background: https://dsva.slack.com/archives/CLRTL92TW/p1573137212057100

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||
3 | ||||||
5 | 
8 | 
```
Investigate root cause and make error msg more actionable.  Could also look into what tasks we do expect do get created after a request has been closed.  Do we expect other mail tasks to be created on appeals that have been dispatched?  Might be a 2 if it turns out to be more straightforward.

**Comment by pkarman** [comment]
More today
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8568/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8567/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8566/

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9402

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9428

**Comment by yoomlam** [comment]
Almost all of these alerts in the last 7 days is due to MailTask creation: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/?query=is%3Aunresolved+did+not+update+RootTask+status.

PR #13844 should drastically reduce the number of these Sentry alerts.
The remaining alerts should be investigated as part of the Bat Team process.

**Comment by yoomlam** [comment]
[Sentry alert 9683](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9683) is odd in that the HTTP request is a PATCH request (for updating tasks), not a POST request (for creating tasks). This alert should only be possible when a task is created.
