### ISSUE TITLE
Do not reset assigned_at when task type is changed

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13272]
As detailed [here](https://github.com/department-of-veterans-affairs/caseflow/issues/12455#issuecomment-577426483), when the type of a task is changed, we should preserve the `assigned_at` timestamp of the original task. This happens in two places, in [ColocatedTasks](https://github.com/department-of-veterans-affairs/caseflow/blob/ae315032af37b69756dddd8533792ad04496c34a/app/models/tasks/colocated_task.rb#L125) and [MailTasks](https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L97)

## AC
- [ ] `assigned_at` timestamp is not reset when task type is changed

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||||
2 | ||||||
3 | 
5 | 
8 | 
```
