### ISSUE TITLE
Reassess default available actions for tasks 

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13284]
Prompted by #13281 "Do not offer "Assign to Team" action for BvaDispatchTask".

The default available actions for a task include "Assign to team". This allows a user to reassign their task or an org's task to another team. Some of these tasks we do not expect to be assigned to another team and our code disallows it (in the case of the BvaDispatchTask reassignment error). We should not be showing  "Assign to team" for tasks that would fail this action.

## Description
Hunter: https://dsva.slack.com/archives/C2ZAMLK88/p1580241695104400?thread_ts=1580233586.100800&cid=C2ZAMLK88
> Reassess what actions should be available by default for any task. Odd that “Assign to team” should be available by default when I don’t think we’d expect a task of a certain types to get moved between teams

## Technical notes

Task classes that do not override `available_actions`
```ruby
Rails.application.eager_load!
Task.subclasses.select { |subclass| subclass.instance_methods(false).exclude?(:available_actions) }.map(&:name)
=> ["EvidenceSubmissionWindowTask",
 "PulacCerulloTask",
 "SpecialCaseMovementTask",
 "TranslationTask",
 "AbstractMotionToVacateTask",
 "DecisionReviewTask",
 "HearingTask",
 "TimedHoldTask"]
```

BvaDispatchTask calls `super` to get its default `available_actions`:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/bva_dispatch_task.rb#L11

So do these tasks:
```
app/models/tasks/decided_motion_to_vacate_task.rb:9:    actions = super(user)
app/models/tasks/vacate_motion_mail_task.rb:5:    actions = super(user)
```

**Comment by yoomlam** [comment]
Related to #13251

**Comment by ajspotts** [comment]
Punting until more information can be gathered.
- How do we split this ticket up?
- Who do we talk to do determine what actions are available for each of these tasks?

**Comment by yoomlam** [comment]
cc @hschallhorn @jimruggiero
