### ISSUE TITLE
Establish Next Claim/ SIC are misaligned

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1329]
**Description:**

After establishing one claim as a caseworker in Dispatch, "Rice Compliance" and "Manlincon" Special Categories shift too close to their corresponding check box and are italicized . 

**Expected:**

Every time a caseworker accesses the Review Decision page, all of the SIC should remain in their original positions. 

**Environment Found:** UAT
**Browsers Found:** FF and Chrome

**Steps to Recreate:**
1. Establish a claim as a caseworker in Dispatch. 
2. On the Success page, select "establish next claim" button
3. On the Review Decision page, view that "Rice Compliance" and "Manlincon" are both italicized and shifted too close to their checkboxes.

**Screenshots**
<img width="1235" alt="screen shot 2017-03-24 at 9 55 32 am" src="https://cloud.githubusercontent.com/assets/23038505/24297763/469c4046-107a-11e7-9415-9ae04fabaabb.png">

**Associated Issues/Stories:**
**Reported By:** Alexis Stewart

**Comment by shanear** [comment]
@astewarttistatech good catch 👍

**Comment by mmlumba** [comment]
@astewarttistatech Sending back to in validation since this was fixed

**Comment by kierachell** [comment]
**PASSED**
OLD AF... HOLYSHIT


<img width="798" alt="screen shot 2017-10-31 at 8 38 45 pm" src="https://user-images.githubusercontent.com/18075411/32255054-876c9cb0-be7b-11e7-9794-89495e399622.png">
