### ISSUE TITLE
[Sentry] Make alert message actionable for AppealNotValidToReopen failures in appeal_repository.rb

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13303]
## Description

Make sentry alert message actionable (or state that alert is simply FYI) or prevent failure from sending a sentry alert.

## Background/context/resources

Got the sentry alert message: `AppealRepository::AppealNotValidToReopen: Appeal id 315333 is not valid to reopen`

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7356

## Technical notes

Several failures are possible:
```
    not_valid_to_reopen_err = AppealNotValidToReopen.new(appeal.id)

    fail not_valid_to_reopen_err unless %w[P W O].include? disposition_code
    fail not_valid_to_reopen_err unless case_record.bfmpro == "HIS"
    fail not_valid_to_reopen_err unless case_record.bfcurloc == LegacyAppeal::LOCATION_CODES[:closed]

    previous_active_location = case_record.previous_active_location

    fail not_valid_to_reopen_err unless %w[50 53 54 62 70 96 97 98].include? previous_active_location
    fail not_valid_to_reopen_err if disposition_code == "P" && %w[53 43].include?(previous_active_location)

    follow_up_appeal_key = "#{case_record.bfkey}P"

    fail not_valid_to_reopen_err unless VACOLS::Case.where(bfkey: follow_up_appeal_key).count == 1
```

## AC
- [ ] actionable sentry alert message 
Also see Estimation comment.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||
3 | |||||
5 | 
8 | 
```

#### Why 2?
- Could provide a clearer "You cannot reopen this appeal"

#### Why 3?
- Investigation
- Providing more specific reasons for why the appeal cannot be reopened
