### ISSUE TITLE
Motion to Vacate | Granted | Add Pulac-Cerrulo Alert to Appeals with "vacate" Stream Type

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13313]
## Description
Attorneys and judges working on "vacate" appeal streams need to be shown the Pulac-Cerrulo alert to be reminded to check CAVC for possible conflicts of jurisdiction.

## Background/context/resources
Current logic displays `PulacCerulloReminderAlert` if the current appeal's task tree includes a `VacateMotionMailTask`. This won't be true of the new appeal stream.

## Technical notes
- The component to display is `PulacCerulloReminderAlert`
- The place with the current display logic is within `TaskSnapshot` component
- This is contingent upon another ticket whereby appeal stream ID and `stream_type` are made available to the frontend code

## Acceptance Criteria
- [ ] Pulac Cerullo alert shows up for all tasks within an appeal stream where the stream type is "vacate"
- [ ] Add "Notify Lit Support" task action to `AttorneyTask` if on vacate stream
- [ ] Add a screenshot to this ticket

**Comment by jcq** [comment]
Screenshot of `PulacCerulloReminderAlert`:

<img width="965" alt="Screen Shot 2020-01-30 at 16 13 52" src="https://user-images.githubusercontent.com/2581274/73501720-a1094880-437b-11ea-86cc-0f5cbcd17fa1.png">

**Comment by leikkisa** [comment]
Make sure the user also has the ability to take the pulac cerrulo action on the appeal

**Comment by jcq** [comment]
## Screenshot
(Attorney checkout is the current live task)

<img width="892" alt="Screen Shot 2020-02-21 at 15 47 41" src="https://user-images.githubusercontent.com/2581274/75080759-ca704c80-54c1-11ea-9740-8f535e6eab65.png">
