### ISSUE TITLE
Create integrity checker to make sure Distribution jobs are not stalled

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13316]
## Description

A judge could not Request more cases because a Distribution job for her was stuck in a 'started' state -- it should have finished in a 'completed' or 'error' state. Not sure why it did not finish. An integrity/liveness checker would detect (and could fix) such problems before the user witnesses the problem.  

## Background/context/resources

From Bat Team issue:
https://dsva.slack.com/archives/CHX8FMP28/p1580442488118900?thread_ts=1580434020.117100&cid=CHX8FMP28

## Technical notes

```
# Check for other incomplete distributions
Distribution.where(status: "started").count
=> 0
Distribution.where(status: "pending").count
=> 0
Distribution.count
=> 5485
# Get all possible values of status of existing distributions
Distribution.pluck(:status).uniq
=> ["completed", "error"]
```

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||
3 | ||||||||
5 | 
8 |  
```
Fear/uncertainty.  Example of previous implementation of a checker can be found here https://github.com/department-of-veterans-affairs/caseflow/issues/12157

**Comment by hschallhorn** [comment]
Not currently affecting any judges
```ruby
Distribution.where(status: "started").count
=> 0
Distribution.where(status: "pending").count
=> 0
```
