### ISSUE TITLE
[Sentry] undefined method `user_represents_claimant_not_veteran'  for Appeal

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13314]
## Description

`NoMethodError: undefined method `user_represents_claimant_not_veteran' for #<Appeal:0x00007fe05a00c890>`

## Background/context/resources

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8059

## AC

- [ ] Add AppealConcern or add `user_represents_claimant_not_veteran` method to AMA appeals?

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |
2 | |||||||||
3 | |
5 | 
8 |  
```
Seems easy, however there is unfamiliarity with this particular bit of code.
