### ISSUE TITLE
Can't change a formerly virtual video hearing back to virtual

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13328]
## Description

Steps to reproduce:

  1. Change video hearing to virtual
  2. Change the hearing back to video
  3. Try changing the video hearing back to virtual, and nothing happens

## Background/context/resources

N/A

## Technical notes

This is an issue with how `deep_diff` interacts with the changes made in #13289. The server now always sends `virtual_hearing` to the frontend even after a virtual hearing was cancelled. This change causes the frontend to send an empty payload to the server when trying to switch a video hearing back to virtual.

This probably won't happen in practice too much, but might affect UAT testing, since it's pretty common to reuse hearings for tests.

**Comment by rubaiyat22** [comment]
@ferristseng Do we want to wait until the refactor of the virtual hearing workflow to do this?

**Comment by ferristseng** [comment]
@rubaiyat22 I'm fine with either fixing it now or later. Either way, I don't see it as being a huge issue for the time being, since it's not a common workflow.

**Comment by tomas-nava** [comment]
may be related to #12765
