### ISSUE TITLE
Scheduling Veterans shows undefined address

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13321]
## User or job story
User story: As a caseflow hearings branch user, I need to be able to see the address of the veteran when I try to schedule. The following error is displayed:

![image](https://user-images.githubusercontent.com/49729315/73570335-3539e500-443a-11ea-957c-50682b453f7d.png)

Link to example:
https://appeals.cf.ds.va.gov/queue/appeals/2732956/?hearingDate=2020-01-31&regionalOffice=RO13

## Acceptance criteria
- [ ] The address should be displayed on the schedule veteran screen.

## Release notes
n/a-bug fix

**Comment by ferristseng** [comment]
Looks like this is being caused by an issue where the appellant's address is not in BGS.

Linking this PR which changed where the appellant's address is populated from

https://github.com/department-of-veterans-affairs/caseflow/pull/11143

**Comment by pshahVA** [comment]
Nice. So the PR above is for POA, do we need to do something similar for the appellant?  This didn't change the geomatching, so I assume that it was pulling the address from another location for that?

**Comment by ferristseng** [comment]
Here's the original issue: https://github.com/department-of-veterans-affairs/caseflow/issues/10473

The PR (#11143) is updating our code to pull both appellant and POA address info from BGS. I think it should've affected geomatching, but not totally sure.
