### ISSUE TITLE
Wrong Loading Icon in Dispatch

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1332]
**Description:**

Now in Dispatch, the "new" loading icon is wrong. 

**Expected:**

Dispatch should have the loading icon found in the style guide. 

**Environment found:** UAT
**Browser  found in:** FF and Chrome

**Steps to Recreate:**
1. Go to Dispatch as a caseworker and try to establish a claim. 
2. On the Review Decision page, after selecting all applicable options, select Route Claim and see that the loading button has changed. 

**Screenshots:**
<img width="308" alt="screen shot 2017-03-24 at 11 45 21 am" src="https://cloud.githubusercontent.com/assets/23038505/24302343/acf541a4-1088-11e7-8b39-8b17ab5f7ac3.png">

**Associated Issues/Stories:**
**Reported By:** Alexis Stewart

**Comment by slj** [comment]
@astewarttistatech is this should be closeable now.

**Comment by mmlumba** [comment]
@astewarttistatech Sending back to in validation since this is fixed

**Comment by kierachell** [comment]
**PASSED**
<img width="368" alt="screen shot 2017-10-31 at 8 38 01 pm" src="https://user-images.githubusercontent.com/18075411/32255040-6bc95c14-be7b-11e7-83d7-79fd6eddd50d.png">
