### ISSUE TITLE
Create better seed data and fakes for BGSService

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13332]
As we extend functionality for VSO users, we need to have better seed data and bgs mock functionality to properly test functionality

### `can_access?`
In `Fakes::BGSService`, we determine if a vso user can [view an appeal's case details](https://github.com/department-of-veterans-affairs/caseflow/blob/821e92c411cbb72778cac5b21fe4ce3ceb670a87/app/controllers/appeals_controller.rb#L95) by checking if the [veteran's file number is in a list of inaccessible appeals](https://github.com/department-of-veterans-affairs/caseflow/blob/4a150bddfd48b51c097f6b38eb93ce3e3b486575/lib/fakes/bgs_service.rb#L196). This list is only populated in tests, meaning that in dev and demo, all VSO users can access all appeals.
```bash
$ git grep --files-with-matches inaccessible_appeal
lib/fakes/bgs_service.rb
lib/generators/legacy_appeal.rb
lib/generators/legacy_appeal_v2.rb
spec/controllers/appeals_controller_spec.rb
spec/feature/dispatch/establish_claim_spec.rb
spec/feature/intake/intake_spec.rb
spec/feature/queue/case_details_spec.rb
spec/feature/queue/search_spec.rb
spec/models/intake_spec.rb
spec/models/veteran_spec.rb
spec/services/veteran_finder_spec.rb
```

#### Replicate

1. Create a VSO user
```ruby
User.create!(station_id: User::BOARD_STATION_ID, full_name: "VSO USER", css_id: "VSOUSER", roles: ["VSO"])
```
2. Sign in as said user and navigate to a case that is represented by another VSO (http://localhost:3000/queue/appeals/fe337914-3c7c-46b5-89d7-eadea36eed24)
```ruby
TrackVeteranTask.last.assigned_to
=> #<FieldVso ... >
TrackVeteranTask.last.appeal.uuid
"fe337914-3c7c-46b5-89d7-eadea36eed24"
```
3. VSOUSER can see the case details even though they are not the POA or a member of the org the TrackVeteranTask is assigned to

### `fetch_poas_by_participant_id` and  `fetch_poa_by_participant_id`
When a user wants to search for an appeal or veteran, `AppealFinder` only searches [appeals the VSO user can access](https://github.com/department-of-veterans-affairs/caseflow/blob/c6f622d00d663a0de21fbef9e91121c57637e8f2/app/services/appeal_finder.rb#L50). This is limited to appeals where the [claimant's POA](https://github.com/department-of-veterans-affairs/caseflow/blob/c6f622d00d663a0de21fbef9e91121c57637e8f2/app/services/appeals_for_poa.rb#L41) [is a](https://github.com/department-of-veterans-affairs/caseflow/blob/c6f622d00d663a0de21fbef9e91121c57637e8f2/app/services/appeals_for_poa.rb#L28) [vso the user represents](https://github.com/department-of-veterans-affairs/caseflow/blob/c6f622d00d663a0de21fbef9e91121c57637e8f2/app/services/appeal_finder.rb#L66). `fetch_poas_by_participant_ids` [returns the same POA](https://github.com/department-of-veterans-affairs/caseflow/blob/4a150bddfd48b51c097f6b38eb93ce3e3b486575/lib/fakes/bgs_service.rb#L243), Attorney McAttorneyFace, for nearly every veteran in dev/demo. `vsos_user_represents` is populated with [default values as well](https://github.com/department-of-veterans-affairs/caseflow/blob/4a150bddfd48b51c097f6b38eb93ce3e3b486575/lib/fakes/bgs_service.rb#L226), but almost all the time, returns nothing at all. This means that AppealFinder will always search no appeals when performing a case search.

AppealFinder is also used to grab "All cases" in case details view and similarly fails

#### Replicate case search
1. Find a case that a VSO user probably should be able to to see
```ruby
user = User.find_by(css_id: "BILLIE_VSO")
appeal = Task.open.find_by(assigned_to: user).appeal
appeal.veteran_file_number
=> => "500000000"
```
2. As a non VSO user (such as BVAAABSHIRE) search for this file number from http://localhost:3000/search and ensure this case assigned to Billie shows up
![Screen Shot 2020-02-03 at 2 00 00 PM](https://user-images.githubusercontent.com/45575454/73682191-dd93b780-468d-11ea-95b3-64e71af368b0.png)
1. Sign in a BILLIE_VSO to perform the search as well and notice no cases are returned
![Screen Shot 2020-02-03 at 2 00 36 PM](https://user-images.githubusercontent.com/45575454/73682216-eb493d00-468d-11ea-9895-7b3eb98f06dd.png)

#### Replicate "All cases"
1. Find a case that a VSO user probably should be able to to see
```ruby
user = User.find_by(css_id: "BILLIE_VSO")
appeal = Task.open.find_by(assigned_to: user).appeal
appeal.uuid
=> => "2a9c683c-936f-46f2-af9f-50d1b199caac"
```
2. As a non VSO user (such as BVAAABSHIRE) go to the case details screen of this appeal (http://localhost:3000/queue/appeals/2a9c683c-936f-46f2-af9f-50d1b199caac) and click "View all cases"
![Screen Shot 2020-02-04 at 10 14 03 AM](https://user-images.githubusercontent.com/45575454/73757483-497e2a80-4737-11ea-915e-06923876190f.png)
1. Sign in a BILLIE_VSO to perform the above
![Screen Shot 2020-02-04 at 10 13 31 AM](https://user-images.githubusercontent.com/45575454/73757501-4e42de80-4737-11ea-91eb-7cce6fc9668e.png)

## AC
- [ ] BGS mocked data and functions reflect expected setup
  - [ ] `fetch_poa_by_participant_id` returns VSOs a user is a member of
  - [ ] `fetch_poas_by_participant_id` returns actual POAs (if there is a task in caseflow assigned to a VSO, that VSO should be the POA for the claimant on the appeal)
  - [ ] `can_access?` actually checks if the current user should be able to access the veteran's information (they are or represent the vet's POA)

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | |||||||
5 | |||||
8 | 
```
Note: demo data = dev data. UAT data = ?

Mock-talking with BGS presents issues.  Doing a complete overhaul of seed data but also updating how Fake BGS responds to functions.

**Comment by pkarman** [comment]
See #13922 for a pattern of prepopulating BGS POA info in seeds if needed.
