### ISSUE TITLE
Adjust Alternate Regional Offices

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13335]
## User or job story
User story: As a hearings branch coordinator,I need to be able to schedule alternate regional offices properly.

Technical Notes:

1. I need to remove the White River Alternate Regional Office (VBA_405) from the Manchester, NH Regional Office so that no Veterans can be scheduled there. (vba_373) 
- Though hearings coordinators haven't been scheduling Veterans here, ensure that no Veterans are scheduled for this office. (White River Alternate Regional Office (VBA_405) )

2. Change the NorthField, NJ (vha_460HE) clinic from the Philadelphia VA Office (vba_310), to the Newark NJ office. (vba_309)

## Acceptance criteria
No feature flag

 ## Release notes
The hearings branch needs to know as soon as this has been implemented so they can plan accordingly.  

### Technical notes
Please let Product know if these changes will effect any existing hearings.

**Comment by ferristseng** [comment]
@pshahVA @chandracarney 

> I need to remove the White River Alternate Regional Office (VBA_273) from the Manchester, NH Regional Office so that no Veterans can be scheduled there. (vba_373)

It looks like this is already the case (and has been for awhile). Can't find `vba_273` being used anywhere. Were there cases of White River being an option recently for scheduling?

```
irb(main):010:0> RegionalOffice.facility_ids_for_ro('RO73')
=> ["vba_405", "vba_373"]
```

No veterans are ready to schedule in RO03 (White River)

```
irb(main):005:0> HearingCoordinatorScheduleQueue.new(nil, regional_office: 'RO03').tasks
...
=> []
```

**Comment by pshahVA** [comment]
I just checked and if you try to schedule a Veteran that is assigned to Manchester, NH, you get the option to assign the Veteran to White River.
