### ISSUE TITLE
Upstream Errors | Resolution Time Reduction and Reporting

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13338]
### Description
This epic is here to connect all of the individual upstream error issues, describe the overall process for handling them, and connect work done regarding manual fixes, engineering tickets, reports, etc.

### Goals
- Identify errors and ensure that they all have Incident reports, GitHub issues and job notes. We will use these as a form of communication to clients and users. Ultimately, solve all of the issues!

## Process
- Look for the related GitHub issue, which should be tagged with "upstream-error" and part of this epic. If there is no GitHub issue yet, please create one, connect it to this epic and tag it with "upstream-error" and post it in the #foxtrot channel in Slack
- Add a note to the asynchronous job notes, referencing the GitHub issue.
- Add the impacted job to the ticket in a markdown table, with the INC number and the YourIT link
If the asynchronous job needs to be cancelled, it can be done so in the Rails console, e.g.:

Related: https://github.com/department-of-veterans-affairs/caseflow/issues/12276

**Comment by msj0nes** [comment]
# YourIT Tickets Impacted 
> For Support Team to Document

YourIT Ticket  Number | Date Ticket Created | Case Details URL 
-- | -- | -- 
INC0000000 | 00/00/00 |   Add case details page URL here

**Comment by msj0nes** [comment]
## Engineering Integration Tickets 

>Corresponds: Add the impacted job to the ticket in a markdown table, with the INC number and the YourIT link. If the asynchronous job needs to be cancelled, it can be done so in the Rails console, e.g.:

YourIT Ticket  Number | Date Ticket Created | Case Details URL | Notes
-- | -- | -- 
INC0000000 | 00/00/00 |   Add case details page URL here | Example

**Comment by leikkisa** [comment]
There is another epic which duplicates this one, but has requirements related to reporting. @wdrougas-tista has started delivering a weekly report and delivering it for review during the weekly integration meeting.  So I am pasting the data from the other epic here to retain it, but closing that issue as a dupe.

## Reporting
In an effort to calculate ROI and properly account for issue resolution time as it relates to 'Asynchronous Claims', the Caseflow team is task with depicting and and highlighting progression via a stakeholder report. 

**Report Content**
_In Progress_
- Async Error Name
- Time between error creation and resolution
- Calculation of total time to resolve over one month
- Historical monthly resolution time 

## Goals
Over a period of time, issues relating to 'asynchronous claims' must show a monthly gradual reduction with regards to resolution time. 

## Stakeholders
AMO

## Requirements/stories

- As an AMO stakeholder, I have access to view and edit the 'async resolution time' report available. 
- As an AMO stakeholder, I can export the 'async resolution time' report in csv format. 

## Open questions
-  Calculation for total resolution time in one month time frame
