### ISSUE TITLE
Allow Webpack Imports of JSON w/o Extension

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13348]
## Description
Webpack defaults allow importing `.json` files w/o extension. This functionality was lost when Caseflow's Webpack config was updated to add `.jsx` as a resolved extension. Given that we import things like COPY.json all over the place, it would be nice to restore this capability.

## Background/context/resources
- [Webpack docs](https://webpack.js.org/configuration/resolve/#resolveextensions)

**Comment by meckila-navapbc** [comment]
Resolved with #13347
