### ISSUE TITLE
Decision Review | Add "Remand BVA or CAVC" as a Document Type in ARC's work queue

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1335]
## Context
Denese noticed that a case with an uploaded decision was showing up on the Missing Decisions page. I looked at the eFolder in VBMS, and noticed it's a Document Type we aren't accounting for in Caseflow. I talked to George he confirmed we should be including these in Caseflow.

## Description
Include "Remand BVA or CAVC" as a Document Type in Caseflow. 

## Related Stories
https://github.com/department-of-veterans-affairs/caseflow/issues/405

**Comment by abbyraskin** [comment]
@shanear @lakohl I'll leave it to you all to figure out if we can fit this in to next sprint. In general, folks are supposed to only use the BVA Decision label, but right now there are still some remands with this label, and I want to make sure these aren't left lingering erroneously on the Missing Decisions page.

**Comment by lakohl** [comment]
If it's not too big a lift, it would be great to get this in this sprint (after ARC Manager View tickets). The BVA Dispatch Manager has access and will be piloting their view this week.

**Comment by kierachell** [comment]
**PASSED**
tested on a few IDs by changing document type

<img width="648" alt="screen shot 2017-04-21 at 1 25 26 pm" src="https://cloud.githubusercontent.com/assets/18075411/25289104/4bb76c2c-2696-11e7-9965-e2091e5b82ba.png">
<img width="705" alt="screen shot 2017-04-21 at 1 26 31 pm" src="https://cloud.githubusercontent.com/assets/18075411/25289105/4bbe116c-2696-11e7-8164-b30b000d18eb.png">
