### ISSUE TITLE
Intake | Restrict Non-BVA MailTeam Members From Starting Board Appeals

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13356]
## Description
Only BVA employees, specifically the BVA Intake Team (MailTeam in Queue) is allowed to intake appeals. To reinforce this rule, an access restriction is needed. Considering the restriction cannot be made at the station or CSEM division level for reasons provided below

Reasons other restriction ideas may have been ruled out:
- **Restrict by Station Number**- There are two station 101 (BVA and other DC-VA entities). Some business line users received access through non-BVA station 101.
- **Restrict by CSEM Division** - Some employees change division or work department within the VA but their local CSEM has not updated their profile information. 

## Background/context/resources
This issue was raised when a case business line user processed an appeal. This highlighted the issue of having both Caseflow Intake business line (Non-comp) and Caseflow Intake (Comp)use the same CSEM functions for access to two different product types. 

## Acceptance Criteria

- Users outside of BVA **MailTeam** [organization](https://appeals.cf.ds.va.gov/organizations/mail/users) cannot start a Board appeal when '_Decision Review Request: Board Appeal (Notice of Disagreement) — VA Form 10182_' is selected.
- Users outside of BVA **MailTeam** attempting to start an appeal, is met with the error message 
> **Not Authorized**
You are not authorized to perform this function. Please contact the BVA Intake department regarding your access permissions.

Sample elsewhere in Intake
>Does require an 'x' or close button.
![image](https://user-images.githubusercontent.com/41164406/75008865-28ac1980-5447-11ea-92bf-b89a57570443.png)
GH: https://github.com/department-of-veterans-affairs/caseflow/issues/13240

**Comment by leikkisa** [comment]
I'm planning on just removing the "Appeal form" option for users who don't have permissions, instead of a having an option that inevitably causes an error.  And I'm going to put it behind a feature toggle for now because I'm concerned about overlimiting it, until we get more information on the other users that are actively using the Appeal form option.

**Comment by leikkisa** [comment]
![Screen Shot 2020-03-03 at 6.30.02 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/a312c192-91b9-47d5-a3ad-774dfbc73c76)

**Comment by leikkisa** [comment]
BvaIntake is in the UI - it's called Case Review

**Comment by leikkisa** [comment]
Add Case Review team to folks who can intake appeals

Get everybody who needs to do Appeal intakes who is not on the Mail team added to the Case Review team before we turn it on.

Change the name of the Case Review team to the Board Intake team.

Hold off on merging this ticket.

**Comment by leikkisa** [comment]
Adding "blocked", I am waiting to hear confirmation from Martina before proceeding.

Current implementation shows an alert and disables the submit button instead of hiding the form type.

Currently it grants access to BvaIntake (Case review) and MailTeam. I'm waiting to hear if we also want to grant access to Intake Admins.

![Screen Shot 2020-03-09 at 2.47.34 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/3078b08a-7ba7-420c-bed0-9401e3f86085)

**Comment by msj0nes** [comment]
# Status
Awaiting finalization details from the Board surrounding this work. A meeting was requested from 3/11/20 to discuss impact. Business line users will be impacted with this change.

**Comment by msj0nes** [comment]
# Tracker 
 **Key:**	
Not Started ⚪️  <br>   In Progress 🚧   <br>    Complete ✅ <br>  Blocked 🔴  

. |Research | Design |  Development | Pilot | Release
-- | -- | -- | -- | -- | -- 
[Create new 'Case Review' team and copy permissions | Update Original 'Case Review' team name to 'Intake' team](https://github.com/department-of-veterans-affairs/caseflow/issues/13865)| :whit: | ✅   |  ✅  |  🚧  |  :white_circle: 		
[Only allow appeal intakes for MailTeam users](https://github.com/department-of-veterans-affairs/caseflow/pull/13603)| :construction: |  n/a |  :white_circle: |  :white_circle: |  :white_circle:

**Comment by msj0nes** [comment]
# Copy Update

**Not Authorized**
You are not authorized to perform this function.  Please take necessary steps to send this form to the Board.

Mail to **425 I St NW, Washington DC, 20001**
Attention: **Case Review and Evaluation Branch**

**Comment by leikkisa** [comment]
New screenshot with updated copy:

<img width="976" alt="Screen Shot 2020-04-06 at 4 46 34 PM" src="https://user-images.githubusercontent.com/6589610/78615616-e5571000-7826-11ea-8452-7cf367add599.png">
