### ISSUE TITLE
Lowercase appeal types

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#13358]
## Description

Update appeal types to be lowercase, and shift the responsibility of making appeal types human-readable to the frontend, at render time.

## Acceptance criteria

- [ ] Appeal types changed from `Original`, `Vacate`, and `De Novo` to `original`, `vacate`, and `de_novo`
- [ ] `original?`, `vacate?`, and `de_novo?` magic methods are available on the Appeal object
- [ ] Frontend has responsibility for capitalizing appeal types 
- [ ] Types are still stored in their current format in the Postgres database

## Context

Currently, appeal types as stored in the `stream_type` database field and returned by the `Appeal#type` method in capitalized format, ready to be displayed on the frontend. The reason is historic: previous to MTV, the only appeal type was "Original" which reflected the corresponding string value in VACOLS (note: legacy appeals have a similar issue).

Now that MTV introduces logic that cares about what type an appeal is, the type values on the backend should be converted to lowercase and use underscores instead of spaces, and sent to the frontend as such. This provides two benefits:
- The magic enum methods generated by ActiveRecord conform to naming style.
- It communicates to developers, especially in the frontend, that the values are suitable for exact string matching but not display.

## Technical notes

This change is minor, but touches a lot of different files, and deserves at least one stand-alone PR to separate the refactor from any business logic changes. One strategy would be to update the `stream_type` enum in the Appeal model to have the desired keys, and follow the flow of logic for everything that touches this (the tests will help immensely).

Three downstream consumers of these values are:
- The frontend: start with the utility function `appealAttributesFromRawTask()`
- The DB and downstream SQL: in order to stay compatible with SQL consumers (e.g. Tableau), do **not** update the format in the database.
- Tasks and task sorting: in Queue, mixed collections (legacy and AMA) of tasks can be sorted by appeal type.

The downstream dependency of sortable tasks raises the issue of whether or not to also propagate this change to legacy appeals. It may be worthwhile to stop at tasks (perhaps with some code to make sorting case-insensitive) and tackle the rest in a future PR.

**Comment by leikkisa** [comment]
@nanotone I believe this is done (prod data currently shows `["original", "vacate"]`).  I just wanted to double check with you before closing the ticket.

**Comment by nanotone** [comment]
@leikkisa I think the bulk of this actually got done in your PR, and everything generally seems to work. But the one unfulfilled AC (and probably a big reason I considered this a "difficult" ticket) is this one:
- [ ] Types are still stored in their current format in the Postgres database

Checking in prod, they're actually stored lowercase currently, which of course makes it easy for the rest of Caseflow code. I wrote that AC because downstream consumers of data might want the casing to stay consistent. No idea how the data is being used, though.

**Comment by leikkisa** [comment]
@nanotone Previously, there was a method called `Appeal.type` that was hardcoded to return "Original".  Now it returns the title-cased stream type, or "Original" as a default.

The title-casing matches how the stream types are stored in VACOLS. From what I can tell, logic in the code referring to "Original" is for legacy appeals. Maybe because AMA appeals were all the same type before, there wasn't a lot of logic built around type besides showing it in the UI.

Reporting might be the other place this is consumed (or eventually consumed). We've talked about making an internal report, but I don't know too much about external reports. As a new column, I'd be surprised if it impacted any existing reports.

I hope that's useful.

**Comment by nanotone** [comment]
Ah, I was misremembering: I thought downstream data consumers depended on stream type because they depended on another attribute that went from Ruby method to new column: docket number -- see this [SQL reimplementation](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/sql/ama-cases.sql#L463-L468).

But it seems that stream type was never reimplemented in SQL. So my worry was moot and this ticket can be closed.
