### ISSUE TITLE
Motion to Vacate | Replicate 'Add New Task' Functionality Available to Mail Team for Litigation Support Org

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13351]
## Description

Currently the BVA Mail Department and Litigation Support share functionality under the 'Mail' team org in Queue. departmentally this is not sustainable. Reasons are provided below. With releasing 'Motion to Vacate' the need for Litigation Support team members to be added to both 'Litigation Support' and 'Mail Team' needs to be eliminated. 

- BVA Departments or leadership did not agree to 'Litigation Support' team sharing 'Mail' department queue.
- Managers for each department (Queue organization) is encouraged to keep their team list current , they do not know team members of other departments. Seeing unfamiliar names in their queue sparks concern.
- With any leadership change this 'sharing a with Mail team' nuance would have to be communicated or issues similar to a BVA Mail Lead removing all unfamiliar users from team list and creating work stoppage for Lit Support will continue. 
- Tableau departmental reports showing task created for Mail team is including task created by Lit support team members, creating issues with productivity reports.

**Story**
- As a Litigation support team member or lead, I am only required to be a member of _litigation support_ (not Mail Team) for full functionality to carry out tasks.

- As a Litigation support team member or lead, I have access to functionality available to 'Mail Team' org, in addition to my Litigation support tasks. 

Related to #12283

**Comment by msj0nes** [comment]
@leikkisa when possible can I hear your insights on this ticket and we can discuss in our next meeting.

**Comment by leikkisa** [comment]
@msj0nes I think it makes sense to discuss in our meeting today. Lit Support users are not also Mail Team users, and do not have the same permissions in general.  Both the Mail Team and the Lit Support team have something called `users_can_create_mail_task?` set to true.

If we want to differentiate those, I would need a list of which Mail Tasks Lit Support should not be able to create.

**Comment by leikkisa** [comment]
After talking yesterday, I think we decided this was no longer needed since their permissions are now separated in Caseflow.
