### ISSUE TITLE
Styleguide component | Checkboxes

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1336]
As a developer and designer, I want a clear and consistent way to implement check boxes across or apps so users can easily make important selections across our Caseflow app. 

## Acceptance Criteria
1. Verify that this is found in the living style guide there is a section titled `Checkboxes`
1. Verify that the description for `Checkboxes` appears underneath the title (see copy)
1. Verify that the components and sections appear beneath the description for horizontal and vertical check boxes (see below)
1. Verify that there is a `Error Checkboxes` section with an appropriate title 
1. Verify that the description for `Error Checkboxes` appears below the title
1. Verify that the component for `Error Checkboxes` appears beneath the description 
1. Verify that there is a Checkboxes section in the left nav of the style guide 
1. Verify that clicking on Checkboxes takes you to the appropriate section

## Mocks

_Make sure you are logged into Invision before clicking the craft link_

**Single Checkbox**
<img width="120" alt="single-checkbox" src="https://cloud.githubusercontent.com/assets/1053255/24709617/78df882a-19e8-11e7-848a-75dff2e6a46e.png">

**Single Checkbox with value set**
<img width="120" alt="single-checkbox-valueon" src="https://cloud.githubusercontent.com/assets/1053255/24709647/914d235e-19e8-11e7-82d4-ef40f265cf04.png">

**Vertical checkboxes**

[Craft Link - Vertical Checkboxes](https://projects.invisionapp.com/d/main#/console/10592592/225515313/inspect)

![image](https://cloud.githubusercontent.com/assets/13420618/24342112/b8c44ce0-128c-11e7-8a16-a73dd4723346.png)

**Horizontal checkboxes**

[Craft Link - Horizontal Checkboxes](https://projects.invisionapp.com/d/main#/console/10592592/225515314/inspect)

![image](https://cloud.githubusercontent.com/assets/13420618/24342096/af80d4b4-128c-11e7-8701-8ec6b3aef60d.png)

**Forced Vertical Checkboxes**
![chk-horiz-forced-vertical](https://cloud.githubusercontent.com/assets/1053255/24709723/e3dc70f2-19e8-11e7-94db-8a1f0618bd96.png)

**Required errors**

[Craft Link - Required Checkboxes](https://projects.invisionapp.com/d/main#/console/10592592/225744029/inspect)

<img width="409" alt="chk-required-error" src="https://cloud.githubusercontent.com/assets/1053255/24709759/fb8dc39a-19e8-11e7-900a-ee037c8383c0.png">

<img width="409" alt="chk-required-noerror" src="https://cloud.githubusercontent.com/assets/1053255/24709767/050c481a-19e9-11e7-88a5-86fcf1f7ccd6.png">

**Acknowledgements**
In certain circumstances we ask the user to click a checkbox agreeing to an action before proceeding. The text here ishould be limited to 75 characters and indented so it doesn't flow under the checkbox. Most of the time these checkboxes should have a required indicator and sand an error state if a user tries to proceed without making a selection.

<img width="434" alt="screen shot 2017-04-05 at 10 20 29 am" src="https://cloud.githubusercontent.com/assets/1053255/24709977/b3519c86-19e9-11e7-9ac8-8842d2ea0a9b.png">
<img width="412" alt="screen shot 2017-04-05 at 10 20 44 am" src="https://cloud.githubusercontent.com/assets/1053255/24709989/b9b34016-19e9-11e7-8800-afcfa42520a5.png">

## Copy

**Title**

Horizontal Checkboxes and Radio Buttons

**Description**

Checkboxes largely follow the same design as those in the US Web Design Standards but we also include horizontal checkboxes. Checkboxes allow an alternative way to selection key responses through out Caseflow Applications. This layout is used when there are at most 2 options. 

**Error Checkboxes** 

In certain circumstances we ask the user to click a checkbox agreeing to an action before proceeding. The text here ishould be limited to 75 characters and indented so it doesn't flow under the checkbox. Most of the time these checkboxes should have a required indicator and sand an error state if a user tries to proceed without making a selection.

**Comment by Chingujo** [comment]
@gnakm 

Updated story, AC, link, added required checkbox, edited copy

**Comment by astewarttistatech** [comment]
Mocks are wrong @slj @gnakm 

Current view:
![buttons](https://cloud.githubusercontent.com/assets/23038505/24657993/59b8081e-1916-11e7-99ec-0a2f21974131.png)

**Comment by gnakm** [comment]
@slj Could we have it so that none of the radio buttons are selected and once one of the buttons are clicked, the required field disappears? The change that has to happen in the living style guide is to take out the red focus outline around the two choices. 

Should look like this:
![image](https://cloud.githubusercontent.com/assets/13420618/24670697/1105c80a-193d-11e7-8387-924c080419c6.png)

Not this:
![image](https://cloud.githubusercontent.com/assets/13420618/24670793/7c985358-193d-11e7-8f22-23c4ca8a46b3.png)

Once you see this, I will update the mockups above. I just wanted you to see the difference. 

/cc: @astewarttistatech for awareness

**Comment by slj** [comment]
The radio buttons are highlighted because the field is in a post-submission invalid state.  Normally, a required field has just *Required* in red to the right (no text in red underneath the label).  But if the user failed to respond, the radios are highlighted and an error message (The field is required) is shown.  Once you click a button the error state goes away.

**Comment by gnakm** [comment]
@slj I get that. I think that the invalid state should still not have the circles highlighted because with radio buttons, users have to choose 1 option and by having both circles highlighted, it looks like both are required.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

1. Go to styleguide and verify the Checkbox section against the mocks and it's copy

Screenshots: 
![styleguide](https://cloud.githubusercontent.com/assets/23038505/24721796/6e6efe12-1a0f-11e7-8470-d7a1796079d4.png)
