### ISSUE TITLE
Reword and Clarify 'Cancel Task' action on AttorneyTask

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13362]
## Description

Several times now we have had users contact support & bat team asking for help returning a case from Attorney Drafting to the assigning VLJ. This is something the attorney user can do! But the action is labelled `Cancel Task` in the actions and is not intuitive for the user. Instead, we should name it based on what will happen to the appeal, something along hte lines of "Cancel this decision drafting and return case to assigning VLJ", but hopefully more succinct?

## AC
  - [ ] The action to move from Drafting Decision -> Back to VLJ Assign is clearly conveyed

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||||||||
3 | ||
5 | 
8 | 
```
"Cancel Task" is used by other views, so may have to create custom button string for different views.  In case we want to update the string to allow interpolation of the user that the task is being sent back to.

**Comment by yoomlam** [comment]
@hschallhorn Why don't AttorneyTasks for Legacy appeals have an option to cancel: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/legacy_tasks/attorney_legacy_task.rb#L12
