### ISSUE TITLE
Manual Fix | Contentions Missing Texts in VBMS

### ISSUE THREAD

**Issue by shahlam636** [department-of-veterans-affairs/caseflow#13377]
## Description
- [x] Find request issues and decision issues that have contentions and that have new line characters in their description 
- [x] Update the contention in VBMS with the newline characters removed

## Background/context/resources
This is the issue for bug fix
https://github.com/department-of-veterans-affairs/caseflow/issues/13311

**Comment by leikkisa** [comment]
A note for data cleanup,  these are also coming from decision issues going onto board grant effectuations.

**Comment by leikkisa** [comment]
https://dsva.slack.com/archives/C54QCEHAL/p1581710985442800

**Comment by leikkisa** [comment]
Script for cleaning up board grant effectuations:
```ruby
# Find potentially problematic Decision Issues
dis=DecisionIssue.where("description LIKE '%\n%' OR description LIKE '%\r%'")

# Get their effectuations
effectuations=dis.map(&:effectuation).compact

# Select only the ones that got created in VBMS with blank text
bges=effectuations.select{ |bge| bge.end_product_establishment.contentions.find { |c| c.id == bge.contention_reference_id }.text.blank? }

# Code to update the contention text
def fix_decision_issue_contention_text(effectuation)
  epe = effectuation.end_product_establishment

  contention = epe.contentions.find { |c| c.id == effectuation.contention_reference_id }
  return unless contention.text.blank?

  contention.text = Contention.new(effectuation.granted_decision_issue.description.gsub(/\s*[\r\n]+\s*/, " ")).text

  VBMSService.update_contention!(contention)
end
```

Two board grant effectuations had their contention text fixed
BGE id:[2535, 1092]

Note: there were 30 other BGEs that had newline characters that were successfully created in VBMS in the first place. I'm not sure what the difference was that caused some of them to succeed and some of them to have blank text.

**Comment by leikkisa** [comment]
Code for cleaning up request issue contentions:
```ruby
potential_ris=RequestIssue.where("(contested_issue_description LIKE '%\n%' OR contested_issue_description LIKE '%\r%') AND contention_reference_id IS NOT NULL")
# Note - in reality, this was batched because fetching the contentions from VBMS is slow
ris=potential_ris.select{|ri| ri.contention&.text&.blank? }

def fix_blank_request_issue_contention(request_issue)
  contention = request_issue.contention

  return unless contention&.text&.blank?

  contention.text = Contention.new(request_issue.description.gsub(/\s*[\r\n]+\s*/, " ")).text

  VBMSService.update_contention!(contention)
end

ris.each{ |ri| fix_blank_request_issue_contention(ri) }
```

Request issues which had their contentions fixed:
IDs:
