### ISSUE TITLE
Same Station Conflict Check | Add CSEM Station 101 Restriction | Feature Toggle to Station Controlled

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13389]
### Description
Apply CSEM access station 101 restriction when handling bypass of same-station conflict check for intaking appeals. 

Currently Caseflow access is managed via CSEM (CSS) and segmented via VA stations. Station 101 is specifically dedicated to cover access for BVA. Per OIT COR, OBPI has approved BVA to bypass the '_[Same-station conflict](https://github.com/department-of-veterans-affairs/caseflow/issues/13165)_' as of 2/11/20 under the condition that the bypass only applies to users belonging to station 101. In addition to the conditions outlined in PR https://github.com/department-of-veterans-affairs/caseflow/commit/4a150bddfd48b51c097f6b38eb93ce3e3b486575, a CSEM station access based restriction needs to be applied to ensure the OBPI agreement is upheld as it relates to the issue. 

**Associated Ticket** https://github.com/department-of-veterans-affairs/caseflow/issues/13165 

### Acceptance Criteria
- [ ] Same-station conflict check remains in place for ClaimReviews (Higher-Level, Supplemental)
- [ ] Same-station conflict check is skipped for Appeals
  - [ ] Same-station conflict check is skipped only for users belonging to CSEM ‘station 101’ and on the MailTeam
- [ ] Remove the feature toggle

### Testing Plan
- [ ] A MailTeam user at station 101 can start an appeal intake, even if `station_conflict?` returns true
- [ ] A user at station 101 that is not a MailTeam user cannot start an appeal intake if `station_conflict?` returns true
- [ ] A MailTeam user not at station 101 user cannot start an appeal intake if `station_conflict?` returns true

### Tech notes
See Intake model validation

**Comment by msj0nes** [comment]
@leikkisa or @nanotone let me know your thoughts on this and if anything additional is needed.

**Comment by leikkisa** [comment]
@msj0nes This looks great! I'll look if there are tech notes regarding BVA permissions and the testing plan which you noted.

**Comment by leikkisa** [comment]
The BvaIntake organization doesn't seem like it's being appropriately used in the code right now. It only has 3 users. I checked the last 1000 Appeals intaken, and it was done by 33 unique users at 14 different stations and 12 different regional offices.

I think before we complete this work, we should make sure that all of the appropriate users are added to the BvaIntake organization.

**Comment by msj0nes** [comment]
@leikkisa can you email me the list showing the employees and their station. BVA users only have one method of obtaining CSEM access and its via station 101 change management, even Ivy is entering station 101 via the CSS login so something is amiss.

**Comment by leikkisa** [comment]
I can confirm that the MailTeam users are all station 101, VACO.  @msj0nes suggests the access be restricted based on being on the MailTeam AND at station 101.

Slack thread for more details:
https://dsva.slack.com/archives/C54QCEHAL/p1581620376416000

**Comment by msj0nes** [comment]
Solution merged.
