### ISSUE TITLE
Update virtual hearing email copy with new test site link

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#13383]
### Story
Update the virtual hearing email notifications with the URL to the new "Test Your Connection" site: `https://vc.va.gov/webapp2/conference/test_call?name=Veteran&join=1`

### Acceptance Criteria
The "Test Your Connection" section of emails to Veterans and Representatives reads as follows:
> #### Test Your Connection
> At least 1 week before your hearing day, test your audio and video connection by visiting the VA Video Connect test site **with the device you plan to use for your hearing:** https://vc.va.gov/webapp2/conference/test_call?name=Veteran&join=1

The update applies to the following emails:

1. Email to Veteran when virtual hearing is scheduled or new email address entered on Hearing Details
2. Email to Representative when virtual hearing is scheduled or new email address entered on Hearing Details
3. Email to Veteran when a virtual hearing time is changed
4. Email to Representative when a virtual hearing time is changed

### Context / Background
Copy document used for prior email iterations: https://docs.google.com/document/d/1u3x6KX5uu7V9G4jjctmuy8-AaXVgzo3t4Nm1C3AzMmE/edit?usp=sharing

**Comment by nicholer** [comment]
@pshahVA Can you confirm this is the correct test site URL: 
https://vc.va.gov/webapp2/conference/test_call?name=Veteran&join=1

Some additional questions:
- Will the videoconference site used for the actual hearings also be moving to this new format? Currently, it's care.va.gov and looks quite different.
- Will these changes affect the Apple App Store download link, currently pointing to https://itunes.apple.com/us/app/va-video-connect/id1224250949?mt=8 ?

@chandracarney for awareness

**Comment by pshahVA** [comment]
I am fairly certain that the test link is correct, but I've asked the Pexip team to confirm one more time on both questions.

**Comment by rubaiyat22** [comment]
> I am fairly certain that the test link is correct, but I've asked the Pexip team to confirm one more time on both questions.

@pshahVA Did the pexip team get back to you on this?
