### ISSUE TITLE
Legacy Appeals: Add special issues

### ISSUE THREAD

**Issue by D-L-Ware** [department-of-veterans-affairs/caseflow#13396]
## User or job story
User story: As a attorney and or/judge, I need to be able to flag the following special issues, so that the data can be captured for reporting purposes: 
- Burn Pit
- Military Sexual Trauma (MST)
- Blue Water
- US Court of Appeals for Veterans Claims (CAVC)

A "No Special Issues" checkbox needs to be added as a selection must be made on this page.

## Acceptance criteria
- [x] Please put this work behind the feature toggle: `:special_issues_revamp`
- [x] This feature should be accessible to the user groups with current access to Special Issues: Judges, Attorneys, & BVA Dispatch
- [x] Attorneys are able to select the above new special issues that apply to a case during the legacy workflow before submitting the case to a judge
- [x] Attorneys are able to select the "No Special Issues" checkbox if no issues apply to the case during the legacy workflow before submitting the case to a judge
- [x] Judges are able to edit/add special issues during the legacy workflow that attorneys identify apply to a case before submitting the case to dispatch
- [x] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: Need to update training documentation
- [x] Special issues data is acceptable for reporting team

### Designs

**UPDATE The below mockup is outdated. Please move the "No Special Issues" checkbox above "About the Appellant"**

![Legacy Appeals_Special Issues](https://user-images.githubusercontent.com/59883609/76991269-acaad180-691f-11ea-9982-d08c093b2a2f.png)

### Background/context
Under law and regulations, a Veteran who served in Vietnam from January 9, 1962, to May 7, 1975 is presumed to have been exposed to herbicides.  Furthermore, a particular set of medical conditions are presumed to be service connected for anyone who has been exposed to herbicide.  Historically, the definition of "served in Vietnam" has been limited to Veterans who served on the landmass of Vietnam or its inland waterways, also know as brown water.  

Last year both a court decision and bill passed by Congress expanded the presumption of exposure to herbicide during that time period to any Veteran who served within not more than 12 nautical miles from the coast of Vietnam, also know as blue water.  

The goal of this project is to provide the Board for the Board of Veterans’ Appeals the ability to flag/mark Blue Water along with MST, Burn PIT, and CAVC contentions in Caseflow for data capture purposes only. 

### Technical notes
This data is needed for reporting purposes in Tableau so both engineering teams will need to synch to ensure the data we are providing is in the format they are requiring. 

Tracking specialty appeals like this was common practice in VACOLS for legacy appeals, see image below.  The Board is likely looking for something similar that would be completed by an attorney at the time they close their writing task and send their appeal to their judge for review.

### Resources/other links
[Product Brief ](https://docs.google.com/document/d/15izpJwUTYP7yE0SHrdLP1tsGmbLGdIOqpEOHDyLwqDo/edit#)

**Comment by D-L-Ware** [comment]
![Special Contentions](https://user-images.githubusercontent.com/23197424/74336999-6fc24c80-4d6d-11ea-8b3e-fa1cb1772ca6.png)

**Comment by araposo-tistatech** [comment]
@D-L-Ware is the board still granting a "stay" on these? I found the the below ticket and was wondering if implementing stays would need to be considered in this request: 

#11288

**Comment by yoomlam** [comment]
> Special issues data is acceptable for reporting team

Who/How should we contact/communicate with the reporting team?

**Comment by araposo-tistatech** [comment]
@yoomlam my understanding is the team member working this ticket will need to connect with @alisan16 for guidance on how to proceed with working with the reporting team.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | ||||||
5 | ||||
8 | 
```

Add some fields/columns in a caseflow model. Add check boxes to Atty/Judge checkout. make those boxes update the caseflow fields. Add to controler flow.

Reporting needs? Hunter to bring up in tech leads. "Data acceptable to reporting team" comes from issue template. 

Why 2?
 - Pretty standard change in both places. 
 - Straightforward
 - Low uncertainty

Why 3?
- Adds to the front end
- Modifies controller, database and model
- Touching Legacy model

Why 5?
- Touches frontend/backend
- Time for updating tests in frontend/backend
- Schema updates

**Comment by araposo-tistatech** [comment]
@lomky please move the "No Special Appeals" checkbox to the above the "About the Appellant" Title instead of the bottom of the page.

**Comment by alisan16** [comment]
@araposo-tistatech For making sure these changes are compatible with the reporting team, you can check with @pkarman by tagging him here or posting in the #appeals-delta channel.

**Comment by lomky** [comment]
@alisan16 Done! [Slack convo](https://dsva.slack.com/archives/CPEMQPVKR/p1585061623033900)

**Comment by lomky** [comment]
@araposo-tistatech @D-L-Ware Questions about each of these new special issues:

 1. Are any of these `unhandled` Special Issues?
    - **Meaning:** do they require specific handling at Dispatch to alert on the case to a specific person/group?   
    - Most Special Issues are *not*. Examples of existing unhandled Special Issues would be:
      - VAMC
      - Pension - United States
      - Nation Cemetary Association
      - Insurance
    - For any of these new ones that are unhandled, Caseflow requires: 
      - an email address to contact at dispatch, 
      - the associated regional office 
 2. . Are any of these `regional` `station of jurisdiction` Special Issues?
    - **Meaning:** The Station of Jurisdiction on these appeals should be set to that _Appeal's_ Regional Office upon dispatch
    - Most Special Issues are *not*. Examples of existing regional Special Issues would be:
      - Spina Bifida
      - Rice Compliance
      - Non-rating Issue
      - Incarcerated Veterans
    - For any of these new ones that are regional, Caseflow requires: 
      - No additional info, just to label them as `regional`
 3. . Are any of these `routed` `station of jurisdiction` Special Issues?
    - **Meaning:** Similar to `regional,` except the Regional Office is set by the Special Issue, and not per appeal
    - Most Special Issues are *not*. Examples of existing routed issues would be:
      - All `U.S. Territory claim` special issues set to the associated Regional Office 
      -  `Mustard Gas` sets to `Muskogee, OK` - `351`
      - `Foreign claim - compensation claims, dual claims, appeals` sets to `Pittsburgh, PA` - `311`
    - For any of these new ones that are routed, Caseflow requires: 
      - location name & key for the routing

**Comment by araposo-tistatech** [comment]
@lomky confirming the new special issues do not require any special handling like those above at the point of dispatch. The designations are solely for reporting purposes at this point.

**Comment by lomky** [comment]
UI Changes (currently behind a feature flag!)

User & Page | Before | After
------------------|----------|--------
Attorney @ Checkout | ![Screenshot_2020-04-03 Draft Decision Select special issues(1)](https://user-images.githubusercontent.com/6129479/78360549-fa147900-7584-11ea-9680-55bed52fbc0b.png)  | ![Screenshot_2020-04-03 Draft Decision Select special issues](https://user-images.githubusercontent.com/6129479/78360441-cc2f3480-7584-11ea-97b7-94424ba4ed0c.png)
Judge @ Checkout | ![Screenshot_2020-04-03 Draft Decision Select special issues(3)](https://user-images.githubusercontent.com/6129479/78360835-62fbf100-7585-11ea-993a-77f6b21e64f0.png)  | ![Screenshot_2020-04-03 Draft Decision Select special issues(2)](https://user-images.githubusercontent.com/6129479/78360855-6b542c00-7585-11ea-8c94-5bda6416d88e.png)  
Dispatch User @ Establish Claim | ![Screenshot_2020-04-03 Caseflow Dispatch(1)](https://user-images.githubusercontent.com/6129479/78360600-11536680-7585-11ea-8183-8955a8a0dd09.png)  | ![Screenshot_2020-04-03 Caseflow Dispatch](https://user-images.githubusercontent.com/6129479/78360144-54610a00-7584-11ea-941c-1cc0ef6fc748.png)

**Comment by lomky** [comment]
@araposo-tistatech 
When an attorney checks 'No Special Issues', do we want that value to: 
 - be preserved and show as checked to the VLJ, or 
 - not be preserved, leaving the VLJ to affirmatively check it again during their checkout?
