### ISSUE TITLE
Intake | Validate claimant address

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13394]
## Description
When a claimant's address is invalid, the claim fails to establish in VBMS.

We'd like to detect these and prevent the user from continuing in intake until they've fixed the address.

## Acceptance criteria
- [ ] If the claimant's address is invalid, return an error asking them to update the claimant's address in VBMS, and prevent them from continuing the intake

# Javascript Regex
AddressLine1/2/3: maxlength 20
```/^(?!.*\s\s)[a-zA-Z0-9+#@%&()_:',.\-/\s]*$/```

City: maxlength 30
```/^[ a-zA-Z0-9`\\'~=+\[\]{}#?\^*<>!@$%&()\-_|;:",.\/]*$/```

## Copy (draft)
The address for the selected claimant is invalid. Please cancel this intake, and try again after updating the claimant's address in VBMS

More copy TBD

## Background/context/resources
related: #13393, #13391
related upstream error: #12592

## Technical notes
See ClaimantValidator

Sandras PR for veteran address validation:
https://github.com/department-of-veterans-affairs/caseflow/pull/13746

## User Facing Changes
Screenshots of the UI changes (non-finalized) as of the latest state of the PR #13779 
<img width="588" alt="Screen Shot 2020-03-23 at 16 23 25" src="https://user-images.githubusercontent.com/282869/77365405-73fa6600-6d2c-11ea-9810-4e884768f5f7.png">
<img width="657" alt="Screen Shot 2020-03-23 at 16 24 56" src="https://user-images.githubusercontent.com/282869/77365413-778ded00-6d2c-11ea-931d-c6b7a490791a.png">

**Comment by leikkisa** [comment]
@rutvigupta-design Can you review the copy in Sandra's PR and lend us your design expertise?

**Comment by nanotone** [comment]
@rutvigupta-design Here are explainers for the two regexes, in case it's helpful for crafting copy.

AddressLine1/2/3:
Max length 20
Cannot contain multiple whitespace characters next to each other.
Must contain only: alphanumerics, whitespaces, and anything in this group `+#@%&()_:',.-/` (excludes some punctuation like `?!";$` which are common in prose)

City:
Max length 30
Seems to allow all printable ASCII characters, along with spaces (but not tabs or newlines)

**Comment by rutvigupta-design** [comment]
@nanotone I may have misinterpreted the regexes, so please correct me if I have missed something/communicated something erroneously. 
@Sjones352 I used your copy as a base, and worked on refining it just a little! 

![Veteran Address Error](https://user-images.githubusercontent.com/51714306/77465798-3c94c380-6dd7-11ea-96b0-67f3d6eec205.jpg)

**Comment by rutvigupta-design** [comment]
Here is a shorter message for city errors: 
![Veteran Address - City Error](https://user-images.githubusercontent.com/51714306/77470192-43730480-6dde-11ea-9c62-7d84156d1dc3.jpg)

**Comment by leikkisa** [comment]
@nanotone Can you add a screenshot of what it looks like now, for reference?  Right now it's an inline error.  I think an alert could be useful too, I think @rutvigupta-design can comment on whether that makes sense or to have one or both.  It will add some complexity to go with a different approach than we're using now.

I think the copy looks good.  It would say the "Claimant's address" instead of "Veteran's address".  I don't know if we need to keep "to create an EP" in the alert.

**Comment by nanotone** [comment]
@leikkisa @rutvigupta-design I updated the issue description above with screenshots from the PR.

**Comment by rutvigupta-design** [comment]
@leikkisa @nanotone I think having an alert along with the inline error would be helpful, if that doesn't add too much complexity. The inline error is helpful for direct context, but in general, I think it would be good to adopt a practice of giving users more context around how to correct the error, which the alert is helpful for. 

I also saw a comment by @leikkisa somewhere else around using "address city" - I think we just can just say city.
