### ISSUE TITLE
Intake | Validate veteran name_suffix

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13391]
## Description
If a veteran's suffix has "JR." with a dot in it, their claims are failing to establish.

## Acceptance criteria
- [ ] During intake when searching for a veteran, if the veteran's suffix has punctuation, return an error to the user asking them to remove the punctuation instead of allowing them to proceed

## Background/context/resources
This is to prevent this upstream error:
https://github.com/department-of-veterans-affairs/caseflow/issues/13148

## Technical notes
This requires adding some validation in the Veteran model.

One approach would be to add invalid_fields to `Intake.veteran_invalid_fields` (in addition to the missing fields).

There is some front-end handling for veteranInvalidFields so that we can show a useful error message to the user.

**Comment by leikkisa** [comment]
@rutvigupta-design Please feel free to suggest copy if you're interested

**Comment by rutvigupta-design** [comment]
@leikkisa here is my suggestion: 
![Suffix Error Message](https://user-images.githubusercontent.com/51714306/77463921-61d40280-6dd4-11ea-882a-edc49058d571.jpg)

**Comment by leikkisa** [comment]
@rutvigupta-design When I first read it, "check and edit the Veteran's suffix for any punctuation (for example: JR.)", was a little confusing to me, I wasn't sure what the correct state was. Surprisingly my eyes went to that text first.  Here's a suggestion (shorter alert title and says to remove in the text).  What do you think?

Invalid Veteran Suffix
Please check the Veteran's name in VBMS or Share, remove any punctuation from the suffix (for example use JR instead of JR.), and try again.

**Comment by rutvigupta-design** [comment]
@leikkisa what do you think of this: 
![Veteran Suffix Error](https://user-images.githubusercontent.com/51714306/77479828-863cd880-6dee-11ea-8891-837dbf6e676b.jpg)


Best practice-wise, I think it would be great to keep the title of the alert user-facing and actionable to avoid making it seem punitive. I also played with the text below the title so that it fits in one line. Removing "to create an EP" to keep alerts consistent.

**Comment by leikkisa** [comment]
@rutvigupta-design That looks good to me!
