### ISSUE TITLE
EstablishClaim returns a TypeError for null error object

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#13405]
EstablishClaim returns `TypeError
Cannot read property 'error_code' of null` when the error object is null.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7176
https://dsva.slack.com/archives/CHX8FMP28/p1581609716309200

**Comment by jjohni** [comment]
YourIT Ticket Number
INC9449308

Product
Dispatch

User Type
Intake VBA User

CSS ID
AMCLWOOD

Urgency
 No Workaround - Medium Priority

What was the user trying to accomplish? 
The user is trying to access dispatch. The product goes in and out for her and she will get an error message with a code.

Issue Description 
I have attached a picture in the thread to display the error message she  is receiving.

Caseflow URL(s) Associated
https://appeals.cf.ds.va.gov/dispatch/establish-claim

**Comment by jjohni** [comment]
![Uploading INC9449308.png…]()

**Comment by jjohni** [comment]
I clicked "close and comment" in error

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

Why 2?
- Could just be add-a-safe-operator `&`

Why 3?
- Maybe this _shouldn't_ be able to be null? In which case, the issue is deeper

**Comment by yoomlam** [comment]
/app/containers/EstablishClaimPage/EstablishClaim.jsx at line 222:67
```ruby
        }
        this.props.performEstablishClaimSuccess();
      },
      (error) => {
        this.props.performEstablishClaimFailure();
        const errorMessage = CREATE_EP_ERRORS[error.response.body.error_code] || CREATE_EP_ERRORS.default;
        const nextModifier = this.validModifiers()[1];
        if (error.response.body.error_code === 'duplicate_ep' && nextModifier) {
          this.props.onDuplicateEP(nextModifier);
```

Navigation:
to | /dispatch/establish-claim/178434#/form
-- | --
from | /dispatch/establish-claim/178434#/decision

**Comment by hschallhorn** [comment]
Last seen 2 months ago, looks like the fix worked!
