### ISSUE TITLE
Show Overtime Cases

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13417]
## User or job story
Job story: When a VLJ or SSC assigns a case to their attorney, they need to see if cases currently part of their attorney's caseload are overtime, so they know they can continue to assign more cases to them.  

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: :overtime_revamp
- [ ] This feature should be accessible to the following user groups: VLJs, SSCs, & Attorneys
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: notify training for training documentation updates
- [ ] If the case has been designated as OT in Caseflow by attorney or #13415 show the OT badge on the 
   - [ ] Judge & SSC "Assign" page
   - [ ] Judge & SSC & the individual attorney "Your Cases"  queues
   - [ ] In the case details view of the case for only attorneys and judges
   - [ ] In search results for only attorneys and judges
- [ ] If the work product field in VACOLS is either - OT DEC, OT VHA, OT IME - show the OT badge on the
   - [ ] Judge & SSC "Assign" page
   - [ ] Judge & SSC & the individual attorney "Your Cases"  queues
   - [ ] In the case details view of the case for only attorneys and judges
   - [ ] In search results for only attorneys and judges

### Designs
![image](https://user-images.githubusercontent.com/59883609/76002956-6001d800-5ed5-11ea-8123-035975972019.png)

### Technical notes

We are currently only tracking when a case was marked as being worked on OT at the time of the attorney. Any changes to OT-related data will need to be captured. 

Overtime data is sent to the following Tableau reporting: 
The Attorney production and DAS ratings and comments workbooks

Engineering should inquire with the team that will actually do the work to update Tableau reports what format the OT data should be formatted in. 

Resources/other links
Product Brief: https://docs.google.com/document/d/1OayEvH7KAAojD9XVHkfUHyLdyECC-PkeIsrEx9krqDA/edit#

**Comment by hschallhorn** [comment]
[Estimating at a 3!](https://github.com/department-of-veterans-affairs/caseflow/issues/5597#issuecomment-582946052)

> Release notes! Ensure users know only legacy cases will have the overtime badge until followup work is done on marking ama cases as overtime. Do we want to put this behind a feature flag until that's done?
> _[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
> ```
> 1 | 
> 2 | |
> 3 | |||||||
> 5 | |||||
> 8 | |
> ```
> Can add a field to the serializer for legacy appeals. Can also replicate design for hearing badge.  Hearing badge column may not be generic enough to accept other badges. Could be a 5 because of translating backend information to the front end and further discrepancies between legacy and ama appeals.

**Comment by hschallhorn** [comment]
Check out this [link](https://github.com/department-of-veterans-affairs/caseflow/issues/13415#issuecomment-595430281) for where we can see if an ama case case been marked overtime by an atty.

**Comment by hschallhorn** [comment]
>  - [ ] In the case details view of the case for only attorneys and judges
>  - [ ] In search results for only attorneys and judges

@araposo-tistatech Can we get clarity on if this is correct, especially given the attorney union discussed today. Do we want to limit this to the assigner, all SSCs, the assigned attorney, etc?

**Comment by geronimoramos** [comment]
OT badge color specs:
/* Gray-dark */

background: #323A45;
border-radius: 4px;
