### ISSUE TITLE
[Documentation] Map Views to Controllers to Tasks

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13414]
## Description

We have an organized listing of task types in the [Tasks Overview page](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md). Now I'd like to know how do steps in the business processes/workflow map to these tasks? What is happening on the users' end that causes a task to be created, completed, and cancelled?
To help answer these questions without any need of business workflow knowledge, this ticket creates documentation that maps Controllers to Task being modified (i.e., created, closed, cancelled, assigned, made in_progress, and put on_hold), as well as Tasks creating/modifying other Tasks.

Doing `git grep -n "Task.create"` would be a good start. If needed, ask Yoom to help create a bash script to extract the mapping and generate a table or listing. Automation will be useful when we need to update the documentation because the code/logic has changed.

## AC
- [ ] Documentation that maps Controllers to Task modifications, for at least the most [popular tasks](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/alltasks.md). 
- [ ] If time permits, documentation that maps Views to Controllers or create a separate ticket. 
Which Views uses which Controllers? (Output from grep could be sufficient to start.)
- [ ] Create follow-on ticket that describes user actions when a View component is pressed or otherwise activated. What are users doing when they create a task? What is the users' workflow and what part of that workflow is each task created.

## Background/context/resources

While we now have some description for the popular tasks and the order in which the tasks are created, we are left at having to guess at the user's workflow and what the user is doing when the tasks are created. Since tasks only reflect changes in user progress (decisions that users' have made), we have an incomplete understanding of the user's decision making or the questions the user is asking.

## Technical notes

In mapping View to Controllers: Besides the obvious `some_name/*.erb` mapping to `some_name_controller.rb`, `client/app/.../SomeView.jsx` also use `ApiUtils` to call other Controllers -- described in [Debugging Tips](https://github.com/department-of-veterans-affairs/caseflow/wiki/Debugging-Tips#how-is-a-web-element-populated).

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | 
3 | |||
5 | ||||||||
8 | |
```

Grepping isn't going to be sufficient due to duck typing.  We don't have one standard way that our Controllers are architected which may pose challenges and different approaches that may have to be taken.  Even if we just keep it at the grepping level of investigation, that would still provide a good wealth of information (if time-boxed to a 3).
