### ISSUE TITLE
`BvaDispatchTask` created before `QualityReviewTask` closes

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13416]
## Description

Immediately after the JudgeDecisionReviewTask was completed at 2020-02-06 14:19:28, a QualityReviewTask was (correctly) created and eventually assigned on 2020-02-10.  Upon completion of the QR on 2020-02-11 21:31:59, a BvaDispatchTask was (correctly) created.
The problem is that a separate BvaDispatchTask was created earlier on 2020-02-06 20:19:36 for some unknown reason; BVALRENE is attributed with completing this BvaDispatchTask on 2020-02-06 20:46:21, which you can see in the Case Timeline that Dustin sent.

Root cause is still unknown after investigation.

## AC
- [ ] job that checks for `BvaDispatchTask` is created before `QualityReviewTask` closes

## Background/context/resources

From Dustin:
> The Board just reached out to me an appeal was assigned a dispatch task and dispatched despite there being open QR review tasks.  There is a concern the QR selection process might have a bug.  Should I just send this to batteam or is their a particular team or engineer with experience with the QR functionality that I should send it to?

https://dsva.slack.com/archives/C7P7M26QM/p1581540877063900?thread_ts=1581514491.056400&cid=C7P7M26QM

From Yoom:
>  I've spent many hours investigating this and also paired with Kevin and Kat looking for possible root causes. We couldn't find any other relevant appeal where a BvaDispatchTask was opened before a QualityReviewTask was closed, so it's not a recurring problem. I'll write up a ticket to create a periodic job that checks for such scenarios so that we can catch these problems hopefully before appeal decisions get dispatched.

## Technical notes

Find appeal where a `BvaDispatchTask` is created before a `QualityReviewTask` closes
```
qrAppIds=QualityReviewTask.all.map(&:appeal).uniq.pluck(:id)
dAppIds=BvaDispatchTask.where(appeal_id: qrAppIds).map(&:appeal).uniq.pluck(:id)
oddAppIds=Appeal.find(dAppIds).select{ |a| 
	qr_ids = a.tasks.where(type: :QualityReviewTask, parent_id: a.root_task.id).pluck(:id)
	d_ids = a.tasks.where(type: :BvaDispatchTask, parent_id: a.root_task.id).pluck(:id)
  id_pairs = qr_ids.product(d_ids)
  id_pairs.select{ |qr_id, d_id|
    Task.find(qr_id).closed_at - Task.find(d_id).created_at > 2
  }.present?
}.pluck(:id)
```

This results in appeals 19 and 12063. Appeal 12063 is the one Dustin brought up.

Appeal 19 is old and the BvaDispatchTask was created correctly after the child QualityReviewTask closed. For some reason, the parent QualityReviewTask closed a little later.

### Some notes from root cause investigation
```
Appeal 12063 (direct_review)                     ID     STATUS    ASGN_BY     ASGN_TO       CREATED_AT              CLOSED_AT
└── RootTask                                     282887 completed             Bva           2019-07-19 14:42:02 UTC 2020-02-06 20:46:21 UTC
    ├── TrackVeteranTask                         282888 completed             Vso           2019-07-19 14:42:03 UTC 2020-02-06 20:46:21 UTC
    ├── DistributionTask                         282889 completed             Bva           2019-07-19 14:42:03 UTC 2020-01-27 21:26:55 UTC
    │   └── InformalHearingPresentationTask      282890 completed             Vso           2019-07-19 14:42:03 UTC 2019-11-08 16:44:52 UTC
    │       └── InformalHearingPresentationTask  508938 completed VACOWENDET  BVAAMONTAGUE  2019-11-07 14:05:59 UTC 2019-11-08 16:44:52 UTC
    ├── JudgeAssignTask                          645151 completed             BVALYASUI     2020-01-27 21:26:55 UTC 2020-01-28 22:08:07 UTC
    ├── JudgeDecisionReviewTask                  649121 completed             BVAGWASIK     2020-01-28 22:08:07 UTC 2020-02-06 14:19:28 UTC
    │   └── AttorneyTask                         649122 completed BVALYASUI   VACOPRINSS    2020-01-28 22:08:07 UTC 2020-02-06 13:54:36 UTC
    ├── QualityReviewTask                        670894 completed             QualityReview 2020-02-06 14:19:29 UTC 2020-02-11 21:31:59 UTC
    │   └── QualityReviewTask                    676752 completed VACOPATRICN VACOPATRICN   2020-02-10 13:26:26 UTC 2020-02-11 21:31:59 UTC
    ├── BvaDispatchTask                          673035 completed             BvaDispatch   2020-02-06 20:19:36 UTC 2020-02-06 20:46:21 UTC
    │   └── BvaDispatchTask                      673036 completed             BVALRENE      2020-02-06 20:19:36 UTC 2020-02-06 20:46:21 UTC
    └── BvaDispatchTask                          683033 on_hold               BvaDispatch   2020-02-11 21:31:59 UTC
        ├── BvaDispatchTask                      683034 cancelled             BVADOSBORNE   2020-02-11 21:31:59 UTC 2020-02-12 15:28:08 UTC
        └── BvaDispatchTask                      684508 assigned  BVADOSBORNE BVAEJAMES     2020-02-12 15:28:08 UTC
```

For more, see [Echo thread](https://dsva.slack.com/archives/CJL810329/p1581541601271200)

Examining versions of each to find a matching timestamp for the errant task.

The task is "assigned_to_id: 19" by nil
`=> #<BvaDispatch id: 19, type: "BvaDispatch", name: "Board Dispatch", role: nil, url: "board-dispatch", participant_id: nil, created_at: nil, updated_at: nil, status: "active", status_updated_at: nil>`
The child task was marked completed by `whodunnit: nil` at 2020-02-06 20:46:21.446796997, 
about 26 minutes after it and its parent was created at 20:19:36.

It is curious to me that a different judge is reviewing the decision than the judge who assigned the case. The assigning judge BVALYASUI has no JudgeTeam.

**Comment by yoomlam** [comment]
We may have detected this earlier if we had data-integrity or state machine checks in place and could have prevented the appeal from being dispatched before all tasks were completed or cancelled. 
Related ticket #12773

**Comment by ajspotts** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |
3 | ||||||||
5 | 
8 | 
```
Seems like a straight forward data integrity check.  Tracking down what is/isn't allowed to be open and determining at what point we want the check to happen could be tricky.

**Comment by hschallhorn** [comment]
Has happened to 3 appeals
```ruby
BvaDispatchTask.not_cancelled.where(assigned_to_type: Organization.name).group(:appeal_id).order(:count).having("count(appeal_id) > 1").count.count
=> 3
```
