### ISSUE TITLE
Schedule Veterans page enhancements

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13421]
## Epic
As a hearings coordinator, I need additional information now that a Veteran is geomatched to help me build a schedule with eligible Veterans.

## Background

Now that Veterans are geomatched to their closest RO or alternate location, there are improvements that can be made to the Schedule Veterans page to give the Hearing Coordinators more information about the Veteran's state of residence to allow them to schedule accordingly.

- Veterans are currently being geomatched to the nearest Regional Office (RO) or alternate office, even if that location is across state lines. 
- Some power of attorneys (POAs) cannot perform hearings out-of-state, meaning they either must be scheduled separately from the Veteran (at an in-state RO or alternate office) or they cannot attend the hearing.
- Veterans are matched by distance as the crow flies rather than by driving distance, meaning they might be closer to their original RO but need to travel to another. 

## Goals

- Hearing Coordinators at the Board can see a Veteran's state of residence to understand if they were scheduled across state lines
- Hearing Coordinators at the Board can identify POAs, which will help them understand if the POA performs hearings out-of-state 

## Success criteria

Veteran state of residence and POA are shown on the Schedule Veterans page.

## Requirements/stories

- Pagination is needed to ensure the page loading performance won't take a hit.
- Include state of residence column on the page
- Include POA column on the page

### Designs and workflows

Included in the associated tickets.

**Comment by rubaiyat22** [comment]
Closing because pagination and adding poa and state of residence column work has been completed
