### ISSUE TITLE
Queue: Legacy Task Investigation

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13430]
## Background/context
Continue work to enhance Caseflow’s ability to manage tasks systems supporting both Legacy and AMA cases, such that the overall volume of issues and types of errors commonly experienced by judges and attorneys can be reduced. 

Investigate Caseflow’s shortcomings regarding legacy task assignment (i.e. legacy appeal case assignment). Do an investigation to determine for legacy cases (due to be closed by 2022), what are the shortcomings of assigning these cases or completing other relevant work in Caseflow for these appeals?

## Stakeholders
Judges & Attorneys

**Comment by jimruggiero** [comment]
@araposo-tistatech Can this epic be closed now?
