### ISSUE TITLE
[Flaky Test] User when the status is updated with a valid status

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13460]
## Background/context/resources

```
1) User when the status is updated with a valid status when the user is a member of many orgs when marking the admin inactive removes admin from all organizations, including JudgeTeam
     Failure/Error: expect(user.selectable_organizations.length).to eq 2

       expected: 2
            got: 3

       (compared using ==)
     # ./spec/models/user_spec.rb:761:in `block (6 levels) in <top (required)>'
```

 - Circle CI Error:  https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/101313/parallel-runs/2?filterBy=FAILED
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [ ] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [x] close this issue

**Comment by pkarman** [comment]
wrapped the test with `ensure_stable` and ran `ENSURE_STABLE=100 bspec spec/models/user_spec.rb:761`

could not induce failure. closing ticket as not reproducable.
