### ISSUE TITLE
[Flaky Test] TaskSorter.sorted_tasks when there are tasks and we specify a column to sort by when sorting by case details link column

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13465]
## Background/context/resources

```
  1) TaskSorter.sorted_tasks when there are tasks and we specify a column to sort by when sorting by case details link column sorts by veteran last and first name
     Failure/Error: expect(subject.map(&:appeal_id)).to eq(expected_order.map(&:appeal_id))

       expected: [252, 245, 247, 253, 246, 249, 248, 251, 256, 254, 244, 250, 255, 257]
            got: [252, 245, 253, 247, 246, 249, 248, 251, 256, 254, 244, 250, 255, 257]

       (compared using ==)
     # ./spec/models/task_sorter_spec.rb:281:in `block (5 levels) in <top (required)>'
```

 - Circle CI Error:  https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/90368
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [ ] Not Skipped
 - Related Flakes
    + [TaskSorter.sorted_tasks when there are tasks and we specify a column to sort by when sorting by case details link column sorts by veteran last and first name](https://circleci.com/gh/department-of-veterans-affairs/caseflow/104030)
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by pkarman** [comment]
https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/30908/workflows/d82299e0-0a53-49c2-942a-5c2313ba90f5/jobs/112899/parallel-runs/3?filterBy=FAILED
