### ISSUE TITLE
[Flaky Test] AmaQueue Judge has a case to assign to an attorney judge can reassign the review judge tasks to another judge

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13468]
## Background/context/resources

```
AmaQueue Judge has a case to assign to an attorney judge can reassign the review judge tasks to another judge - spec.feature.queue.ama_queue_spec
spec/feature/queue/ama_queue_spec.rb
Failure/Error: expect(page).to have_content(judge_user.full_name)
  expected to find text "Anna Juarez" in "CaseflowQueue\nSearch cases\nCSS_ID61 (VACO)\nSubmit Draft Decision for Review\nComplete the details below to submit this Draft Decision request for judge review.\nDocument ID:\nSubmit to judge:\nLoading judges…\nNotes:\nThis work product is overtime\nThe Veteran submitted evidence that is ineligible for review\nWhat is ineligible evidence?\nCancel\nContinue\nBack\nBuilt with ♡ by theDigital Service at VA\nTrack Caseflow Status|Send feedback"
./spec/feature/queue/ama_queue_spec.rb:824:in `block (4 levels) in <top (required)>'
./spec/support/feature_helper.rb:60:in `step'
./spec/feature/queue/ama_queue_spec.rb:779:in `block (3 levels) in <top (required)>'
```

 - Circle CI Error:  https://circleci.com/gh/department-of-veterans-affairs/caseflow/86254
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [ ] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by rubaiyat22** [comment]
Closing because the test file has changed a lot since this ticket was reported. If it flakes again, we can recreate the issue.
