### ISSUE TITLE
[Flaky Test] HearingTimeService with a legacy hearing and a hearing scheduled for 12:00pm PT #local_time returns time object encoded in local time

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13464]
## Background/context/resources

```
Failures:

  1) HearingTimeService with a legacy hearing and a hearing scheduled for 12:00pm PT #local_time returns time object encoded in local time
     Failure/Error: expect(LegacyHearing.first.time.local_time).to eq(expected_time)

       expected: 2019-10-31 12:00:00.000000000 -0700
            got: 2019-11-01 12:00:00.000000000 -0700

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -Thu, 31 Oct 2019 12:00:00 PDT -07:00
       +Fri, 01 Nov 2019 12:00:00 PDT -07:00
     # ./spec/services/hearing_time_service_spec.rb:49:in `block (4 levels) in <top (required)>'
```

 - Circle CI Error:  https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/90781/parallel-runs/1?filterBy=FAILED
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [ ] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by rubaiyat22** [comment]
Closing because this [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15985) should resolve it.
