### ISSUE TITLE
[Flaky Test] AppealTaskHistory#history when Task changes records the changeset

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13466]
## Background/context/resources

```
AppealTaskHistory#history when Task changes records the changeset - spec.services.appeal_task_history_spec
spec/services/appeal_task_history_spec.rb
Failure/Error: expect(appeal_history.events.first.diff).to eq(diff)

  expected: {"placed_on_hold_at"=>[nil, 2019-10-01 15:01:41.695443485 -0400], "status"=>["assigned", "on_hold"]}
       got: {"assigned_to_id"=>[67, 313], "assigned_to_type"=>["Organization", "User"], "status"=>["on_hold", "as...85 -0400], "updated_at"=>[2019-10-01 15:01:41.695443000 -0400, 2019-10-01 15:01:41.695443485 -0400]}

  (compared using ==)

  Diff:
  @@ -1,3 +1,6 @@
  -"placed_on_hold_at" => [nil, 2019-10-01 15:01:41.695443485 -0400],
  -"status" => ["assigned", "on_hold"],
  +"assigned_at" => [2019-10-01 15:01:41.695443000 -0400, 2019-10-01 15:01:41.695443485 -0400],
  +"assigned_to_id" => [67, 313],
  +"assigned_to_type" => ["Organization", "User"],
  +"status" => ["on_hold", "assigned"],
  +"updated_at" => [2019-10-01 15:01:41.695443000 -0400, 2019-10-01 15:01:41.695443485 -0400],
./spec/services/appeal_task_history_spec.rb:42:in `block (4 levels) in <top (required)>'
```

 - Circle CI Error:  https://circleci.com/gh/department-of-veterans-affairs/caseflow/86602?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [ ] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by rubaiyat22** [comment]
Closing because the specific test is no longer in the file.
