### ISSUE TITLE
[Flaky Test] Hearing Schedule Daily Docket for Build HearSched Daily Docket with one AMA hearing User can update fields

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13467]
## Background/context/resources

```
  1) Hearing Schedule Daily Docket for Build HearSched Daily Docket with one AMA hearing User can update fields
     Failure/Error: expect(page).to have_content("This is a note about the hearing!")
       expected to find text "This is a note about the hearing!" in "CaseflowHearings\n  |  Switch product\nBVATWARNER (DSUSER)\nYou have successfully updated Tom Brady's hearing.\nDaily Docket (Tue 10/01/2019)\n\n< Back to schedule  \nEdit Hearing Day  \nLock Hearing Day  \nVLJ: Lauren Roth\nCoordinator:\nHearing type: Central\nRegional office:\nRoom number: 2 (1W200B)\nDownload & Print Page\nAppellant/Veteran ID/RepresentativeTime/RO(s)Actions\n1Tom Brady\n500000577\nH\n190930-1\n\n\n9999 MISSION ST\nSAN FRANCISCO CA 94103\nAttorney McAttorneyFace\n9:00 am EDT\nCentral\nDisposition\nNo Show\nCopy Requested by Appellant/Rep\nTranscript Requested\nHearing Details\nEdit Hearing Details\nNotes\nhis is a note about the hearing!\nRegional Office\nCentral\nHearing Location\nHearing Day\nTue 10/01/2019\n\nTime\n9:00 am\n1:00 pm\nOther\nBuilt with ♡ by theDigital Service at VA\nTrack Caseflow Status|Send feedback"
     # ./spec/feature/hearings/daily_docket/build_hearsched_spec.rb:90:in `block (3 levels) in <top (required)>'
```

 - Circle CI Error:  https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/86543/parallel-runs/1/steps/1-116
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [ ] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by rubaiyat22** [comment]
closing because it looks like a change was this was fixed by this [change](https://github.com/department-of-veterans-affairs/caseflow/pull/12972/files#diff-1e1b3919fb7cdcbc1f7c1b36690c629b1b6762737c60e58d65d94233e85a962a)
