### ISSUE TITLE
Motion to Vacate | Return to Judge front-end

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13474]
## User or job story
User story: As a decision drafting attorney, if I think the Judge made a mistake on his vacate decision, I want to send the AddressMotionToVacate Task back to the judge.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: review_motion_to_vacate
- [ ] Implement the "Return to Judge" banner on the review vacatures page
- [ ] Clicking "Return to Judge" brings up a modal with a place to add instructions, it looks like the JudgeAddressMotionToVacate task assignment modal
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Out of scope

- Submitting the return to judge modal
  - Deleting the vacate stream and Post Decision Motion
  - Creating a new AddressMotionToVacateTask assigned to the judge

## Release notes
A decision drafting attorney can send a vacature back to the judge if they believe there was a mistake.

### Designs
![Screen Shot 2020-02-20 at 7.34.08 AM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/f9ccd5c5-925f-49ef-a6dc-f9f7f32aae70)

TBD: Copy and design for the modal

**Comment by leikkisa** [comment]
@rutvigupta-design Can you add information about the design/copy for the task assignment modal?

**Comment by rutvigupta-design** [comment]
Designs for the banner (the instruction text in the banner has changed slightly) and the modal here: 
![Review Vacated Decision Issues_Return to Judge Banner](https://user-images.githubusercontent.com/51714306/75585898-25b1ba00-5a41-11ea-8fbe-c98aa3bff0b6.jpg)
![Return to Judge](https://user-images.githubusercontent.com/51714306/75585903-28141400-5a41-11ea-988e-50fc29efb38a.jpg)

**Comment by jcq** [comment]
@rutvigupta-design 
Any particular copy desired for a success banner upon submission?

**Comment by rutvigupta-design** [comment]
@jcq did we still need updated copy for this?

**Comment by jcq** [comment]
> @jcq did we still need updated copy for this?

@rutvigupta-design Sorry, I somehow missed this last week. Yeah, if you have any updated copy, we'll get it in there before this gets merged.

**Comment by rutvigupta-design** [comment]
@jcq let's go with this copy, if it isn't too much trouble! 

![Return to Judge success banner](https://user-images.githubusercontent.com/51714306/76902166-63984600-6869-11ea-8fef-913bda16ab6d.jpg)

**Comment by jcq** [comment]
## Final Screenshots
<img width="911" alt="Screen Shot 2020-03-19 at 14 16 53" src="https://user-images.githubusercontent.com/2581274/77115946-8010bb80-69ec-11ea-9eb5-12b0547857dd.png">
<img width="539" alt="Screen Shot 2020-03-19 at 14 17 10" src="https://user-images.githubusercontent.com/2581274/77115951-81da7f00-69ec-11ea-8acf-80a7889e92c9.png">
<img width="917" alt="Screen Shot 2020-03-19 at 14 17 25" src="https://user-images.githubusercontent.com/2581274/77115955-82731580-69ec-11ea-884d-4bedfa96e068.png">
