### ISSUE TITLE
Intake | Add Contention service to ruby-bgs

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13488]
## Description
We cannot delete contentions that have an exam scheduled, but the data returned from VBMS does not have this information. However, there is a BGS service where we can get this information.

- [ ] Add the Contention service to ruby-bgs
  - [ ] Update `ruby-bgs/lib/bgs/services.rb` to include the new service
  - [ ] Add the new service to `appeals-deployment/ansible/vars/va-services.yml`
  - [ ] Update the ruby-bgs gem in Caseflow
- [ ] ~Add the the contention service to Caseflow in BGSService (separate PR)~ Can move to the next ticket

## Out of scope
Implementing checking for whether there is an exam scheduled

## Technical notes
You can use another service in ruby-bgs as a model.  find_claimant_letters in `ruby-bgs/lib/bgs/services/document.rb` is a good example.

bean_name: "ContentionService"
service_name: contention
request_name: findContentions
response_name: findContentionsResponse
input: claimId

Here is the "documentation" for this service:
http://bepdev.vba.va.gov/ContentionService/ContentionService?wsdl
http://bepdev.vba.va.gov/ContentionService/ContentionService?xsd=1

### Testing notes
Here is the current documentation for testing BGS code:
https://github.com/department-of-veterans-affairs/appeals-team/wiki/How-to-test-code-for-VBMS-and-BGS

### Other tech notes
The following gives an idea of the output, but is not information needed for coding this ticket.  It will be more useful in the next ticket, but keeping it here for reference.
```
- <xs:complexType name="contention">
- <xs:complexContent>
- <xs:extension base="tns:compositeTransferObject">
- <xs:sequence>
  <xs:element name="beginDt" type="xs:dateTime" minOccurs="0" /> 
  <xs:element name="clmId" type="xs:string" minOccurs="0" /> 
  <xs:element name="clmntTxt" type="xs:string" minOccurs="0" /> 
  <xs:element name="clsfcnId" type="xs:string" minOccurs="0" /> 
  <xs:element name="clsfcnTxt" type="xs:string" minOccurs="0" /> 
  <xs:element name="cmpltdDt" type="xs:dateTime" minOccurs="0" /> 
  <xs:element name="cntntnId" type="xs:string" minOccurs="0" /> 
  <xs:element name="cntntnStatusTc" type="xs:string" minOccurs="0" /> 
  <xs:element name="cntntnTypeCd" type="xs:string" minOccurs="0" /> 
  <xs:element name="cntntnTypeNm" type="xs:string" minOccurs="0" /> 
  <xs:element name="dgnstcTc" type="xs:string" minOccurs="0" /> 
  <xs:element name="dgnstcTn" type="xs:string" minOccurs="0" /> 
  <xs:element name="medInd" type="xs:string" minOccurs="0" /> 
  <xs:element name="notfcnDt" type="xs:dateTime" minOccurs="0" /> 
  <xs:element name="origSourceTypeCd" type="xs:string" minOccurs="0" /> 
  <xs:element name="specialIssues" type="tns:specialIssue" nillable="true" minOccurs="0" maxOccurs="unbounded" /> 
  <xs:element name="wgAplcblInd" type="xs:string" minOccurs="0" /> 
  </xs:sequence>
  </xs:extension>
  </xs:complexContent>  
```

**Comment by leikkisa** [comment]
@leikkisa to add instructions for testing code

Peter may know how to test this the best.

**Comment by msj0nes** [comment]
**Latest from John Dell**

**_Service Name is:_** ContentionService and web method to use in that service is: findContentions 
<xs:element name="origSourceTypeCd" type="xs:string" minOccurs="0" />  
If it is equal to EXAM

**Comment by msj0nes** [comment]
**Sample Cases w/ Pending Scheduled for Testing**

- https://appeals.cf.ds.va.gov/search?veteran_ids=664326
- https://appeals.cf.ds.va.gov/search?veteran_ids=39881
- https://appeals.cf.ds.va.gov/search?veteran_ids=656869
- Claim ID #77167806
- Claim ID #76150964

**Comment by msj0nes** [comment]
@leikkisa sample case above to test the new data point received.

**Comment by leikkisa** [comment]
I'm inclined to update this to a 5 because the testing itself will take some extra time and it involves multiple PRs in multiple repos, but I'll wait to check in with folks.

**Comment by Sjones352** [comment]
Yes Lets increase it to a 5.
