### ISSUE TITLE
Upgrade raven.js

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13490]
Our raven.js is old and officially deprecated:

https://docs.sentry.io/clients/javascript/

The newer version is 2 major steps away:

https://docs.sentry.io/error-reporting/quickstart/?platform=browser

We should clarify with ourselves if we need to coordinate client JS version with the version of the server we are hosting (9.1.2).

**Comment by jcq** [comment]
It looks like there are some migration tips in this forum post:
https://forum.sentry.io/t/switching-to-sentry-javascript/4732
