### ISSUE TITLE
Contested Claims | Attorney Fees | Ability to Intake Attorney Fees Claims

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13505]
# Background/Context
The Board of Veteran's Intake team requires the ability to intake 'Attorney Fees' contested claims. These claims are submitted by the Veteran's attorney (past or present) for VA legal services rendered, requesting payment. 

**Claimant Type**: Private Attorney

**Contested Claim Types**: Non-Apportionment >  Attorney fees 

# Goals
Caseflow BVA users can intake claims belonging to the 'Attorney Fee' category.

# Supporting Data
- Number of _Attorney Fee_ Caseflow claims processed 2020 (BVA workaround)  -  _Pending #14002_
- Number of _Attorney Fee_ Caseflow claims processed 2019 (BVA workaround) -  _Pending #14002_
- Number of _Attorney Fee_ VACOLS claims processed 2008 - 1079 claims (855 claims were Direct Pay)
> **2008 is the last year tracked in VACOLS per Jed**
- % of _Attorney Fees_ completed via Caseflow with attorney present in database selected for development completion 

# Success Criteria
- The Board of Veterans Intake team can select as claimant the attorney that filed form 10182.
- The Board of Veterans Intake team can select specifically 'Attorney Fees' during the Intake process.
- The appropriate data points are captured for '_future_' or third party reporting
- The necessary tasks or action items are triggered as needed in Queue. Confirm via echo collaboration. [i.e. Sending case to BVA Intake Queue not auto-distribution]

# Stakeholders / POCs
**BVA Stakeholder POCs**
John Gosnell 
George Waddington

**BVA Intake 'Attorney Fees' SMEs**
Kendra Jones - BVA Intake Dept Chief
Ivy Wilson - BVA Intake Lead
Crystal Smith - BVA Intake Team Member
Tony Scire (VLJ) 

# Requirements/Stories

- _[As a BVA Intake user, I need the ability to select an attorney as the claimant in the Intake workflow](https://github.com/department-of-veterans-affairs/caseflow/issues/13806)_ 
- _[As a BVA Intake user, I need the ability to specify issue category as ‘Attorney Fees’ in the Intake workflow](https://github.com/department-of-veterans-affairs/caseflow/issues/13807)_
- _[As a BVA Intake user, if no attorney is available for selection as claimant, a notes field is required to add that attorney information](https://github.com/department-of-veterans-affairs/caseflow/issues/14283)_
- _[As an BVA Intake user, Caseflow should provide an 'Claimant not listed' option when the claimant is not available for selection](https://github.com/department-of-veterans-affairs/caseflow/issues/14107)_

### PHASES
**Phase 1** - Selecting Attorney as the claimant
**Phase 2** - Selecting 'Attorney fees' as the issue category

## Out of Scope
- Handling of attorney fees outside of Caseflow Intake
- Handling categories of contested claims outside of attorney fee

# Designs and Workflows
- Story - [As a BVA Intake user, I need the ability to select an attorney as the claimant in the Intake workflow](https://github.com/department-of-veterans-affairs/caseflow/issues/13775)
- Story - [As a BVA Intake user, I need the ability to specify issue category as ‘Attorney Fees’ in the Intake workflow](https://github.com/department-of-veterans-affairs/caseflow/issues/13745)

- [Design Prototype WIP](https://www.figma.com/proto/HL5muMytaEzO4Li2UJMx9E/Attorney-Fees_March-2020_RG?node-id=193%3A358&viewport=1369%2C177%2C0.14378885924816132&scaling=min-zoom)
- [Discovery Synthesis- MURAL](https://app.mural.co/t/workqueue2001/m/workqueue2001/1584461830155/62b9c582babb829ffcb5996a945950f2eac1f76f)
- [Discovery Research Synthesis - Notion](https://www.notion.so/navapbc/Research-Report-Discovery-6deef807b4a24b85ad0e4a94f50e670f)

# Prior Research/References/Resources
[Product Brief](https://docs.google.com/document/d/1JNRaxpC832JoNcVaCCbLqVhkQ_NylPR-lcwFMyS4j1E/edit)
[Timeline & Index](https://docs.google.com/document/d/1aHisB5KfePwehQvc_hjkWi7FxB4MKeWmkXZ2sQiRjK0/edit#)
[Current Caseflow Issue Categories](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/ISSUE_CATEGORIES.json)
[Contested VA Claims Info](https://www.va.gov/decision-reviews/multiple-party-claims/)
[Contested Claims MVP](https://github.com/department-of-veterans-affairs/caseflow/issues/8660)
[Handling Contested Claimants](https://github.com/department-of-veterans-affairs/appeals-team/issues/995)
[General Contested Claims Information](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657744/General.Information.on.Contested.Claims.pdf)
[Payment of Attorney Fees](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657742/Payment.of.Attorney.or.Agent.Fees.pdf)
[Apportionment Process](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657743/Apportionment.Process.pdf)
[Authorizing and Notifying Claimants](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657761/Authorizing.and.Notifying.Claimants.of.a.Decision.on.a.Contested.Claim.pdf)
[Mural Design - Prior Research 2018/2019](https://app.mural.co/t/workqueue2001/m/workqueue2001/1542655242638/5629820b4b2c34a158c9dd7abb78137d0f9b8b74)

**Comment by msj0nes** [comment]
## Open Questions / Research Required

- [ ] The option would also exist for the BVA user to update this information in VBMS. Do we want to make it editable in Caseflow and would that info update VBMS.
- [ ] What conditions require Caseflow to block or prevent the user from proceeding in the Intake flow ?
>e.g If user enter date prior to XYZ , block from proceeding


### Design / Research Team Findings
[to be added here]

**Comment by msj0nes** [comment]
## Foxtrot 
Showcasing the information with the overall 'Contested Claims' umbrella notion. As a team we can decide whether to pursue the umbrella or just the 'Attorney Fees' provided on our roadmap. Tackling in its entirety now eliminates having to eliminate in the future. If contested claims umbrella becomes the direction, a discussion with stakeholder regarding our timeline will follow.  Timeline is currently mid-March --> mid May.

**Rough Estimate Requiring Engineering+Design Input**
Sprint -> Mar 9 - Mar 20 - Phase 1  - Obtaining from BGS
Sprint -> Mar 23 - Apr 3 - Phase 1 - Free text option
Sprint -> Apr 6 - Apr 17 -  Phase 1 - Free text option
Sprint -> Apr 20 - May 1 - Phase 2 
Sprint -> May 4 - May 15 - Phase 2 
Sprint -> May 18 - May 29 - Phase 3
Sprint -> June 1 - June 12 - Phase 3
Sprint -> June 15 - June 26 - Dogfood Testing Fixes

**Comment by msj0nes** [comment]
## Engineering Research - Sample Cases 

Provided by B. Cannon: I have spoken to two experts.  They have confirmed that attorney fees decisions typically take the form of a “Summary of the Case” document.  These may be titled as “Administrative Decision,” “Notification Letter,” or “Correspondence.”   Some examples below.  Sometimes, a decision will be made in the notice letter following a rating decision, but this is rare, and we were unable to locate any examples.

- https://appeals.cf.ds.va.gov/reader/appeal/3678497/documents/50637452
- https://appeals.cf.ds.va.gov/reader/appeal/3985534/documents/15417086
- https://appeals.cf.ds.va.gov/reader/appeal/3702548/documents/21707465
- https://appeals.cf.ds.va.gov/reader/appeal/3109307/documents/39750335
- https://appeals.cf.ds.va.gov/reader/appeal/3351002/documents/32287962
- https://appeals.cf.ds.va.gov/reader/appeal/3351002/documents/32287976

**Comment by msj0nes** [comment]
## Current Workaround 
> Per user, Woolfolk
- Make sure a notification is in VBMS with something stating Attorney fee
- Go into caseflow intake, ADD, stroll down to none of these match, see more options 
- Click on Compensation
- Then select Contested Claims other than Apportionment (the date will be the date of the letter and the reason should say Improper Calculation fees)

**Comment by msj0nes** [comment]
### Pain Points Surfaced
- VACOLS doesn't flag or indicate 'apportionment' contestant claims so its hard to know when and who needs to be notified. 
- VACOLS overwrites the main root address on a case with the claimant address
- ROs tend to mess up the notification requirements quite often e.g. routinely fail to notify the contested claimants
- A common Privacy violation currently occurring is giving the parties each other's addresses.

### Useful Information
- Contested Claims is what VACOLS does the worst.
- There are contested scenarios when one party is already receiving a benefit and someone else wants some (or all) of the benefit.
- Board accepts evidence from whoever gives it.
- VA can only recognize one surviving spouse
- VACOLS has a Contested Claims field that multiple claimants can be added to.
- VACOLS doesn't flag things like Apportionment that are always Contested Claims.
- Apportionment and Contested Claims (other than apportionment) are always contested
- Caseflow currently has two options already available. **Apportionment** and **Contested Claims (other than apportionment)**
- All level of appeals should be available for 'contesting claims'. 
- If there's a due process problem with CCs it is always prejudicial since someone has to lose.
_Note: Direct Review is the lowest, Evidence Submission is the middle, and Hearing is the highest_
- Spousal benefit is separate from child benefits. Recognition of additional children increases the total but not proportionally so it decreases how much each person gets.
- **Attorney fees are contested claims** and that would be the POA tab in VBMS to see if the person is the POA.
- There are different scenarios. Often, there are two widows claiming the benefits...
- Can happen before or after the NOD
- Apportionment has a specific form you have to fill out.
- Apportionment is where the attorney/vet have agreement to share benefits
- Surviving spouse + apportionment are the most common.
- Claimant information is available via the dependents tab in VBMS or the veteran's eFolder
- For attorney fees, the POA information is available via the my files tab in VBMS or the veteran's eFolder
- Contested claims issues should be **ineligible for HLR and ineligible for Supplemental Claim** (Verification Needed)
- Contested claims for **Remand/DTA error supplemental claims are eligible** as category as they will go to the Board for review and if they remand we will need to correct the actions. So we will have Remand EPs established and worked

**Comment by msj0nes** [comment]
## Caseflow Queue Work  - Echo 

### Next Phase Contested Claims (Queue) - Echo Team
- Update the case details [page](https://github.com/department-of-veterans-affairs/caseflow/issues/8660#issue-398406038) with an indicator highlighting a found contested claim for both legacy cases and new AMA cases. See https://github.com/department-of-veterans-affairs/caseflow/issues/9132
- Create banner to alert BVA intake team a case has a contested claim that requires action https://github.com/department-of-veterans-affairs/caseflow/issues/8451
- About the Appellant section of case details [page](https://github.com/department-of-veterans-affairs/caseflow/issues/8660#issue-398406038)
- Trigger BVAIntakeTeam (to be created) task to notify associated party of claim being contested once an NOD is received (Can be done be searching for active intake issue category). Party has 30 days from notification to respond 'correspondence'
>Certain notices have to go out at the same time to all contested claimants: hearing, docketing,decisions. This is complicated with colocated VSOs: VBMS is getting updated to allow for multiple VSOs for one claim file; this won't impact historic appeals
- Trigger BVAIntakeTeam (to be created) task to send docket letter to all involved parties.

**Comment by msj0nes** [comment]
# Tracker 
 **Key:**	
Not Started ⚪️  <br>   In Progress 🚧   <br>    Complete ✅ <br>  Blocked 🔴  

. |Research | Design |  Development | Pilot | Release
-- | -- | -- | -- | -- | -- 
[Select an attorney as the claimant ](https://github.com/department-of-veterans-affairs/caseflow/issues/13806)|  :construction: | :construction: | :white_circle: | :white_circle:   |  :white_circle: 		
[Specify issue category as ‘Attorney Fees’](https://github.com/department-of-veterans-affairs/caseflow/issues/13807)| :construction: |  :construction: |  :white_circle: |  :white_circle: |  :white_circle:

**Comment by pshahVA** [comment]
@msj0nes  Do we have an idea of the volume of this? How often does this happen?

**Comment by msj0nes** [comment]
@pshahVA due to the fact that BVA has being using a free text method as a workaround in Caseflow for attorney fees providing reporting on how many AMA cases have been specific to attorney fees would be difficult to compute as its dependent on verbiage free texted by BVA users.

**Comment by pshahVA** [comment]
But we know the legacy number correct?  Can help us project? Just good to get a ballpark.

**Comment by nanotone** [comment]
@pshahVA I just created #14002 to investigate current/past volume by consulting Caseflow DB, and expect it to be in the next sprint.

**Comment by alisan16** [comment]
Reopening this as there are a couple issues still open
- https://github.com/department-of-veterans-affairs/caseflow/issues/14503
- https://github.com/department-of-veterans-affairs/caseflow/issues/14505

**Comment by leikkisa** [comment]
Closing, this is completed, and will soon be replaced by Unrecognized Appellants:
https://vajira.max.gov/browse/CASEFLOW-140
