### ISSUE TITLE
Styleguide Component | Caseflow Logos

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#1350]
As a developer and designer, I want a clear and consistent way to implement logos across our applications to increase brand awareness with our users and help them identify the various apps. 

## Acceptance Criteria 
 1. Verify that there is a section titled `Logos`in the style guide
1.  Verify that the description for `Logos` appears underneath the title (see copy)
1.  Verify that the `Logo` component appears under the description (see mockups) 
1.  Verify that `Logo`appears as a section in the left side nav of the style guide
1.  Verify that clicking on `Logo` in the style guide nav takes you to the write direction. 

## Mocks

_Make sure you are logged into Invsion before you click the Craft links_

**e-Folder Express**

[Craft Link - e Folder Express Logo](https://projects.invisionapp.com/d/main#/console/10592592/225844145/inspect)

<img width="146" alt="screen shot 2017-03-27 at 3 23 16 pm" src="https://cloud.githubusercontent.com/assets/23316107/24374039/71d2533e-1301-11e7-8cc4-989ac780ccc4.png">

**Certification**

[Craft Link - Certification Logo](https://projects.invisionapp.com/d/main#/console/10592592/225844168/inspect)

<img width="166" alt="screen shot 2017-03-27 at 3 26 19 pm" src="https://cloud.githubusercontent.com/assets/23316107/24374147/c4dc86a8-1301-11e7-97fe-ec09dcf5b676.png">

**Dispatch**

[Craft Link - Dispatch Logo](https://projects.invisionapp.com/d/main#/console/10592592/225844168/inspect)

<img width="166" alt="screen shot 2017-03-27 at 3 26 57 pm" src="https://cloud.githubusercontent.com/assets/23316107/24374180/e7047c68-1301-11e7-8340-68bffadc7c8e.png">

**Feedback**

[Craft Link - Feedback Logo](https://projects.invisionapp.com/d/main#/console/10592592/225844180/inspect)

<img width="151" alt="screen shot 2017-03-27 at 3 27 52 pm" src="https://cloud.githubusercontent.com/assets/23316107/24374196/f6bc7df4-1301-11e7-9b0c-c789ba7a0b95.png">

**General Logo**

[Craft Link - General Logo](https://projects.invisionapp.com/d/main#/console/10592592/225847846/inspect)

<img width="111" alt="screen shot 2017-04-12 at 2 07 13 pm" src="https://cloud.githubusercontent.com/assets/23316107/24972421/61806018-1f89-11e7-976b-c446e1821a13.png">

## Copy 

**Title**

Caseflow Logos

**Description**

The Caseflow logo, also known as the “Starwave”, is a minmal guilloche pattern that is meant to communicate security, fluidity, integration, dynamism, transparency, intuitiveness, and modernism. 
Each Caseflow application has it’s own unique accent color but the base color remains the same, gray-lighter.

When refering to the whole Caseflow system, you should use the non-colored Caseflow logo.

**Comment by gnakm** [comment]
Note for myself -- Gina to add new one for Reader!

**Comment by slj** [comment]
Screenshot:

<img width="683" alt="screen shot 2017-04-24 at 4 37 58 pm" src="https://cloud.githubusercontent.com/assets/1053255/25363379/04d02f1c-2928-11e7-8bd1-08444bcbefa1.png">

**Comment by kierachell** [comment]
**PASSED**
LOOKING FLY
<img width="728" alt="screen shot 2017-04-25 at 3 12 47 pm" src="https://cloud.githubusercontent.com/assets/18075411/25403252/c6f55602-29c9-11e7-9101-4b2f9429883a.png">
