### ISSUE TITLE
Motion to Vacate | Return to Lit Support Banner

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13518]
## User or job story
When a judge is addressing a Motion to Vacate, if the Lit Support team did not provide their draft decision proposal, the Judge can return the task to them to request it.

Currently, the banner implemented was not implemented according to design and is using a flash message, which doesn't work properly for queue.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] When the Judge selects the option to "Return to Lit Support" during Address Motion To Vacate, their next screen should show the banner in the designs below
- [ ] Previous code using flash message is cleaned up
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

## Release notes
When a Judge returns a Motion To Vacate back to the Litigation Support user, because they didn't receive a draft decision, they will see a success banner on the next screen.

### Designs

![Judge-Return Draft](https://user-images.githubusercontent.com/51714306/75474231-9a62f680-5964-11ea-9d75-2c5281cfb229.jpg)

### Technical notes

Probably best to use JC's PR here as a model:
https://github.com/department-of-veterans-affairs/caseflow/pull/13509

Clean up the code for the flash message in the PostDecisionMotionController.

### Resources/other links

Relevant Slack thread:
https://dsva.slack.com/archives/C54QCEHAL/p1582554855001700?thread_ts=1582306659.030500&cid=C54QCEHAL

**Comment by jcq** [comment]
### Updated screen:
<img width="893" alt="Screen Shot 2020-03-02 at 15 22 42" src="https://user-images.githubusercontent.com/2581274/75727387-aec32e00-5c99-11ea-8e34-a9bfb530edf5.png">
