### ISSUE TITLE
Update Pexip URL and theme ID

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13525]
## Description
Change Pexip URL and theme ID to support the new Pexip updates and changes after they're rolled out by Pexip. Once this work is finished, verify connection and to verify that we can still schedule and break down hearings in the dev environment

## Acceptance criteria
- [ ] ~~Change the API url to use /v2/*~~
- [ ] Update Pexip URL from / webapp to /bva-app
- [ ] Update theme ID

## Background/context/resources
Updates are being made to account for Pexip theme ID, Pexip URL, web app and proxies.

https://dsva.slack.com/archives/C3EAF3Q15/p1583180539111900
https://dsva.slack.com/archives/C3EAF3Q15/p1582140624315100

**Comment by rubaiyat22** [comment]
Since we've already confirmed that the production credentials work in prod, I want to hold off on this until we find out exactly why we need to do this for uat.

**Comment by rubaiyat22** [comment]
Holding off on this until we understand why we need to make these changes on UAT

**Comment by pshahVA** [comment]
@rubaiyat22 One part of the test in production is to test a hearing with the new version of the pexip.  Since we are a little behind schedule in production rollout, I thought it would be good to connect to the prod url create hearing rooms and then actually log in as a Judge and veteran to see how this integration works.  It would also be easier to test with non veterans in uat (edited)

**Comment by rubaiyat22** [comment]
@pshahVA Thanks for clarifying! What does v2 and has changed with v2 for Pexip? Does this also apply to UAT?

**Comment by pshahVA** [comment]
Apparently in production, they want us to use V2, which will change the look and feel for the Veteran and Judge.  They just never told us.

**Comment by chandracarney** [comment]
Updated with new requirements as the Pexip team has additional changes requested to URL, theme ID, and length of PIN, and has removed the v2 update request.
