### ISSUE TITLE
Research retrying for flaky feature tests

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13524]
## Description

From the Backend Workgroup Discussion on Flaky Tests: we discussed potentially adding a retry for flaky feature tests to improve the reliability of the test suite. Adding a retry for feature tests should be OK (won't cause false positives) because flaky feature tests usually fail from timing issues, that already might not be realistic in a non-test environment.

Keep this effort time boxed

## Acceptance criteria
- [ ] Research gems / solutions to add retries for *only* feature tests
- [ ] Keep retry count low (1-2 retries)

## Background/context/resources

https://docs.google.com/document/d/1TvDnY0JQ8T1TK1ccYUhC3o_gVF17xMEihIQekY1IhEo/edit

**Comment by rubaiyat22** [comment]
There's a rspec gem [rspec-repeat](https://github.com/rstacruz/rspec-repeat#attaching-to-features) that allows us to add retries only on feature tests with a retry count. This gem is built on top of another fully featured gem [rspec-retry](https://github.com/NoRedInk/rspec-retry#installation) which allows for the same. You can also retry specific examples with these gems.

Some unknowns about using these gems
- not really well supported
- the last commit to `rspec-repeat` was in Oct, 2018 :crying-emoji:

`rspec-repeat` is more verbose in my opinion but our best bet would be to go with `rspec-retry` as the former was built on top of it and it allows for configuration. It also seems like the author of `rspec-retry` updates the code more frequently.

We should also allow repeats only if we're in CI env that way we don't make tests run even slower in dev.

**Comment by ferristseng** [comment]
> but our best bet would be to go with rspec-retry as the former was built on top of it and it allows for configuration. It also seems like the author of rspec-retry updates the code more frequently.

Agreed. `rspec-retry` looks like it's used by more projects as well.

> We should also allow repeats only if we're in CI env that way we don't make tests run even slower in dev.

Yes, good call on this. Do you want to make a small PR that integrates `rspec-retry` into our test suite?

**Comment by rubaiyat22** [comment]
+1 will work on it in an upcoming PR
