### ISSUE TITLE
Api::V2::HearingsController GET hearings by hearing day with valid API key response for hearing day with hearings ama hearings is virtual returns a 200 and has expected response

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13535]
## Background/context/resources

 - Circle CI Error:  [Api::V2::HearingsController GET hearings by hearing day with valid API key response for hearing day with hearings ama hearings is virtual returns a 200 and has expected response](https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/104233/parallel-runs/4?filterBy=FAILED)
```
Api::V2::HearingsController GET hearings by hearing day with valid API key response for hearing day with hearings ama hearings is virtual returns a 200 and has expected response
     Failure/Error: expect(response_body["hearings"][0]["is_virtual"]).to eq true

       expected: true
            got: false

       (compared using ==)
     Shared Example Group: "hearings api route that serializes virtual hearing" called from ./spec/controllers/api/v2/hearings_controller_spec.rb:127
     # ./spec/controllers/api/v2/hearings_controller_spec.rb:60:in `block (6 levels) in <top (required)>'
```
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by yoomlam** [comment]
Another one: https://app.circleci.com/jobs/github/department-of-veterans-affairs/caseflow/104935/parallel-runs/1/steps/1-120
