### ISSUE TITLE
Create End Product | Duplicate EP modifier error handling

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1354]
# Description
As a Caseworker routing a Partial/Remand thingy,
when creating a New End Product
if there's already an existing EP with a modifier (170-179)
and I attempt to create a new EP with that same modifier
Caseflow shows a not-very-informative _System Error_ alert.

VBMS is kind enough to tell us that we're trying to create a duplicate EP. So maybe we can parse that?
```
<env:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">
rO0ABXeyAB13ZWJsb2dpYy5hcHAudmJtcy1jbXMtYXBwLmVhcgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQAEjEyLjEtMjAxNzAzMjAtMTc0NQAdd2VibG9naWMuYXBwLkNvcnBvcmF0ZURhdGFFQVIAAADWAAAAI3dlYmxvZ2ljLndvcmthcmVhLlN0cmluZ1dvcmtDb250ZXh0AAYxMC4yLjAAAA==
</work:WorkContext>
</env:Header>
<S:Body>
<ns0:Fault xmlns:ns1="http://www.w3.org/2003/05/soap-envelope" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/">
<faultcode>ns0:Server</faultcode>
<faultstring>Claim not established. A duplicate claim for this EP code already exists in CorpDB. Please use a different EP code modifier. GUID: 416c39f3-4a8f-4bac-873c-afbe1e9c2f5c</faultstring>
<detail>
<serviceException xmlns="http://vbms.vba.va.gov/external/ClaimService/v4" xmlns:ns0="http://vbms.vba.va.gov/cdm/claim/v4" xmlns:ns1="http://vbms.vba.va.gov/cdm/common/v4" xmlns:ns2="http://vbms.vba.va.gov/cdm/participant/v4"/></detail>
</ns0:Fault></S:Body></S:Envelope>
```

**Environment:**
- [ ] Production
- [X] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [X] Performance
- [ ] Design
- [ ] Security
- [X] Functional
 
# Reproduction Steps
Scenario 1 - Load up a Remand/Partial Grant

1. Do your thing to get to the Create End Product page

1. Click **Create End Product**

1. See **System Error** alert

1. Wonder what's going on

## Screenshots
**_Scenario 1 - Alert message_**
<img width="1196" alt="screen shot 2017-03-28 at 8 01 00 am" src="https://cloud.githubusercontent.com/assets/18075411/24403842/b2ee1278-138c-11e7-8427-346034800551.png">

**Comment by shanear** [comment]
This is a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/1281

closing
