### ISSUE TITLE
Run through end-to-end virtual hearings flow

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13548]
In advance of pilot, run through the end-to-end virtual hearings flow in UAT to ensure seamless connectivity after adjustments to timezones, Granicus, Pexip, and other integrations. Set up UAT and run through test scripts and dogfooding happy/sad paths.

Test email
- [ ] Confirm "from" address
- [ ] Confirm email is sending with new key
- [ ] Confirm timezones by testing hearing scheduled for another (non-east coast) timezone

Test Pexip
- [ ] Set up UAT
- [ ] Live test with Pexip that the the emails send from Caseflow also allow the judge, user, and POA (using our email addresses for testing) to join the hearing
- [ ] Wait for Pexip's email confirmation the following day that the Caseflow job has deleted the hearing

**Comment by nicholer** [comment]
Here's the test script from our last round of dogfooding / end-to-end testing, for context:
https://github.com/department-of-veterans-affairs/appeals-team/blob/master/qa/test-plans/virtualhearingsDogfooding-2020-01-13.md

**Comment by chandracarney** [comment]
Duplicate of https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/13609
