### ISSUE TITLE
Judges should not receive virtual hearing emails

### ISSUE THREAD

**Issue by rubaiyat22** [department-of-veterans-affairs/caseflow#13564]
### Description
Per feedback from usability testing with Judges (#13374), Judges do not want to receive emails when virtual hearings are scheduled. We need to (1) remove Judges as email recipients and (2) update the copy on modals and alerts.

### Acceptance criteria
- [ ] remove `judge_email` & `judge_email_sent` field from `VirtualHearing` model
- [ ] remove judge as a recipient for emails 

---

- [ ] **Copy Update 1** - change the copy on the Change to Virtual Hearing modal, that appears on Hearing Details after the Hearing Type is changed to virtual: 
  - from the current `Email notifications will be sent to the Veteran, POA / Representative, and VLJ.` 
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/9e90b174-40a2-4e86-a8e5-144844ca45ab" width="350"> 
  - to `Email notifications will be sent to the Veteran and POA / Representative.`
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/cbb9f6f6-582a-4c88-a650-f93ba92372d7" width="350">

---

- [ ] **Copy Update 2** - change the copy on the alert that appears on Hearing Details while the virtual hearing async job is in progress:
  - from the current `Emails to the Veteran, POA / Representative, and VLJ are in progress.` 
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/f1a5ba4d-fce8-465c-b413-5d0a63efc404" width="500">
  - to `Emails to the Veteran and POA / Representative are in progress.`
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/42d64dad-dfb1-4b52-b8cd-7685aba6ad0a" width="500">

---

- [ ] **Copy Update 3** - change the copy on the modal that appears on the Daily Docket when the virtual hearing time is changed:
  - from the current `Email notifications will be sent to the Veteran, POA / Representative, and VLJ.` 
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/cd760405-30b0-4d6a-bd6b-83874440bcba" width="350">
  - to `Email notifications will be sent to the Veteran and POA / Representative.`
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/eb6be1d6-8e49-4bbe-9e35-93368438b7ba" width="350">

---

- [ ] **Copy Update 4** - change the copy on the alert that appears on the Daily Docket while the async job is in progress:
  - from the current `Emails to the Veteran, POA / Representative, and VLJ are in progress.` 
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/401c2d63-6c01-4ef1-8231-32102a79492b" width="500">
  - to `Emails to the Veteran and POA / Representative are in progress.`
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/312094f4-00fe-47a2-bb08-574e185cddf8" width="500">

---

- [ ] **Copy Update 5** - change the copy on the alert that appears on Hearing Details after a hearing has been switched back to Video:
  - from the current `Emails to the Veteran, POA / Representative, and VLJ are in progress.` 
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/b4a43867-71ce-4fc4-8f01-e40a851d7c80" width="500">
  - to `Emails to the Veteran and POA / Representative are in progress.`
    <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/6eb8d37e-f5d4-4847-a886-a45e1a71ceca" width="500">

**Comment by chandracarney** [comment]
Context for closing a re-opening: while we pilot with our first users, it's been decided the emails should remain turned on. We can gather user feedback over time and turn them off, if needed.
