### ISSUE TITLE
eFolder API returning empty/truncated manifest JSON

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#13571]
The eFolder API appears to be occasionally returning empty or truncated JSON from the `/api/v2/manifests` endpoint.

This causes the JSON parser to raise a `JSON::ParserError` (A JSON text must at least contain two octets!) and could probably be interpreted and re-raised as a `Caseflow::Error::DocumentRetrievalError` instead.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6915/

## Technical notes

The JSON parsing happens in `app/services/external_api/efolder_service.rb` in the `generate_efolder_request` method. `DocumentRetrievalError`s get raised in the `check_for_error` method.

**Comment by ajspotts** [comment]
Related: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7118

**Comment by pkarman** [comment]
PR in https://github.com/department-of-veterans-affairs/caseflow/pull/14243

**Comment by pkarman** [comment]
Seems to correlate with EE scaling up/down. E.g. https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/7731/events/f97ac04978a14e6fa40d4f1c36d6a21a/

We've dealt with one instance of this in #14243 and silenced Sentry for the rest. Going to close this until there is something actionable.
