### ISSUE TITLE
Intake | Show original request issue description on add issues page if edited

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13576]
## Description
After a user edits contention text, they are not able to easily see the original contention text.  Sometimes the users make mistakes when editing contention text.

## Acceptance criteria
- [ ] On the "Add issues" page, if a request issue's contention text has been edited, show both the original and new contention text.

## Background/context/resources
In this batteam call, a user edited a contention text but they put the wrong edited description, one that actually matched another request issue.  They were missing one issue, but couldn't re-add it because it appeared to already be added (with the wrong text).

I've noticed other cases where people edited contention text to be something unrelated to the original issue, so it seems worth showing the original text in order to prevent errors and confusion.

Batteam Slack conversation:
https://dsva.slack.com/archives/CHX8FMP28/p1582226165398100

## Technical notes
See AddedIssue.jsx as a starting point

**Comment by jcq** [comment]
@rutvigupta-design Do you have any design suggestions for this? Below is what I have as a starting point:
<img width="793" alt="Screen Shot 2020-04-01 at 12 41 53" src="https://user-images.githubusercontent.com/2581274/78179574-47260d00-7416-11ea-8d03-1545d9ba8e24.png">

**Comment by rutvigupta-design** [comment]
@jcq I like the placement of it and think it makes the most sense to have it there. I also agree with putting it in italics. My only suggestion would be adding parentheses to separate it visually a little bit more (very very minor). Would a user ever edit the contention text more than once? In that case, would "previously" make more sense? 
<img width="382" alt="Screen Shot 2020-04-02 at 8 44 53 AM" src="https://user-images.githubusercontent.com/51714306/78256505-3cbf4e00-74be-11ea-9bdc-8d9684bf6ad7.png">

**Comment by jcq** [comment]
> Would a user ever edit the contention text more than once? In that case, would "previously" make more sense?

@leikkisa It would only ever be "original" vs "edited", right? It never saves a "previous" state other than the original one, to my knowledge.
