### ISSUE TITLE
Case Reassignment

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13583]
Please reassign all of Jasmin Freeman's tasks (no exceptions) to Adrian Odya-Weis.

**Comment by lomky** [comment]
_[What is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||||
2 | |||
3 | 
5 | 
8 | 
```

This is for all active tasks. 
Not just updating the `assigned_to` field, but using the `reassign` logic.

Estimating at a 1. 
Might be a 2 if task trees are weird.

**Comment by lomky** [comment]
Completed. [Slack thread](https://dsva.slack.com/archives/CQCUMFA0H/p1584103109258700)
