### ISSUE TITLE
Remove attorney functionality

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13584]
## User story
User story: As an attorney, I should not have the ability to designate a case as overtime in Caseflow. Only VLJs or SSCs should have the ability to designate or update overtime cases. 

Please remove the "This work product is overtime" checkbox from the submit draft decision for review workflow.

![Attorney OT Functionality](https://user-images.githubusercontent.com/59883609/75810899-76832480-5d59-11ea-8263-63934b5efe1d.jpg)

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: :overtime_revamp
- [ ] This feature should not be accessible to the following user groups: attorneys
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: notify training for documentation updates
- [ ] Attorneys will no longer have the ability to designate OT cases

### Background/context

We are removing this ability for attorneys as we are moving the marking overtime cases functionality to SSCs & VLJs at case assignment. 

Attorneys should no longer be able to designate their own OT cases in Caseflow. 

### Technical notes

Reporting Implications - We are currently only tracking when a case was marked as being worked on OT at the time of the attorney. Any changes to OT-related data will need to be captured. The data will need to be made available for the following Tableau reports: 
The Attorney production and DAS ratings and comments workbooks

Resources/other links
Product Brief: https://docs.google.com/document/d/1OayEvH7KAAojD9XVHkfUHyLdyECC-PkeIsrEx9krqDA/edit#

**Comment by lomky** [comment]
_[What is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | ||||
5 | 
8 | 
```

Estimating at a 2. 
Could be a 3 if we have cleanup on the controller and the backend. Param clean up, routing in code based on it, etc.

**Comment by yoomlam** [comment]
Remember to use `appeal.overtime?` when setting `attorney_case_review.overtime` during checkout. We still want to record the current overtime status at the time of attorney checkout. `appeal.overtime?` is used for displaying the OT badge and could still potentially be toggled, e.g. subsequent rewrites from quality review or dispatch.

**Comment by yoomlam** [comment]
BEFORE|AFTER
 ---|---
<img width="885" alt="image" src="https://user-images.githubusercontent.com/55255674/83075756-fad40380-a039-11ea-87f8-3fc6afc9c3cc.png"> | <img width="862" alt="image" src="https://user-images.githubusercontent.com/55255674/83075492-92852200-a039-11ea-9d9c-baa2bec93846.png">

**Comment by araposo-tistatech** [comment]
@wturne @RTOLSON we are removing the overtime field attorneys would typically see during their checkout process. Can we have the training documents updated?
