### ISSUE TITLE
Put Inactive Users Development behind a feature flag

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13592]
## Description
Put the link to user management behind a feature flag

## Acceptance criteria
- [ ] Users cannot access the user management page without the feature flag enabled

## Technical notes
Change goes [here](https://github.com/department-of-veterans-affairs/caseflow/blob/e21282bd6a16402c20171a6f7f23f29cf360cfdf/app/controllers/application_controller.rb#L47)!

**Comment by lomky** [comment]
_[What is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||||||
2 | 
3 | 
5 | 
8 | 
```

This is a new feature toggle.

Estimating at a 1. We _might_ also have to update a test with the flag.
