### ISSUE TITLE
Remove irrelevant buttons from judge team management pages

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13594]
## Description
Judges cannot be removed from their own team and our definition of what a judge is relies on the judge being the first admin on the team. We should not show "Remove from team" next to the judge as this will always return an error. We should also hide "Remove admin rights" next to the judge as this will mess up the structure and assumptions we make about judge teams. Lastly, we should hide "Add admin rights" next to attorneys as adminship means nothing on judge team and we never expect there to be more than one admin on a team

## Acceptance criteria
- [ ] "Remove from team" button is not shown next to the judge on their judge team page
- [ ] "Remove admin rights" button is not shown next to the judge on their judge team page
- [ ] "Add admin rights" button is not shown next to the attorneys on a judge team page

## Background/context/resources
Disallow judge removal from their own teams #12703
How we determine who is the [judge on a team](https://github.com/department-of-veterans-affairs/caseflow/blob/3ef4ef110b22120124f052642fe8e474dfb62d1c/app/models/organizations/judge_team.rb#L44)

## Technical notes
Much of the logic can be reused from "Alec/12433 add judge and atty selectors to judgeteam page #13191" including
- [ ] [Serializer](https://github.com/department-of-veterans-affairs/caseflow/pull/13191/files#diff-990df726a0da01fdc2ac2d18b609a8c9R9) additions
- [ ] [Org responses](https://github.com/department-of-veterans-affairs/caseflow/pull/13191/files#diff-c6e4fbf60d1477384698268a86cc8858R12)
- [ ] [Button logic](https://github.com/department-of-veterans-affairs/caseflow/pull/13191/files#diff-6d75c558d00a97ea8ec23018bca90b2cR250) and maybe even role labels

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | ||||||||
5 | |
8 | 
```

Estimating this at a 3.

Might be a 5 because we're in a code space that is mid-refactor & rollback. Severe pessimism.
Could be a 2 because we have all the info and just need to shuffle info on the front end.
