### ISSUE TITLE
Create notification to alert admins of attorneys on an inactive judge team

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13591]
## Description
When a judge is made inactive, their judge team is also marked inactive [correction: their attorneys are no longer a part of a judge team]. This could leave attorneys on teams that are inactive. We should alert admins about these orphaned attorneys and instruct them to place the attorneys onto a new judge team.

## Acceptance criteria
- [ ] A notification alerts admins of orphaned attorneys
  - [ ] On the team management page when any attorney in this state exists
  - [ ] When a judge is made inactive with attorneys still on their team
- [ ] Instructions in alerts to place attorneys on a new judge team

## Background/context/resources
- Tie JudgeTeam status to its Judges status #13161

**Comment by geronimoramos** [comment]
#### Some contextual questions

- Do we want this to be a legit notification (such as part of the notification system concept) or an indicator somewhere on the screen?
- Could it potentially be a mini workflow i.e. mark user inactive + assign attorneys to new judge team(s)?

#### Ideas

- A confirmation modal when marking the user inactive that lists the attorneys' names and CSS IDS that will also go inactive (gives them a chance to take note of the information) not the ideal workflow bc it's kind of manual.

**Comment by araposo-tistatech** [comment]
@geronimoramos 

Do we want this to be a legit notification (such as part of the notification system concept) or an indicator somewhere on the screen? _I think an indicator would be sufficient in this case, but @hschallhorn please let us know your thoughts._ 

Could it potentially be a mini workflow i.e. mark user inactive + assign attorneys to new judge team(s)? _We could, but based on some brief context provided by the Board, the admin deactivating the user is often times Mike & John and they do not always know what judge team the attorney should be assigned to. This is something we will want to keep in mind._ 

Would also love to see the interaction to mark a user inactive, if you can show me! This will give me more ideas on potential ideas. _Marking a user inactive is out in production. You can view the functionality in Caseflow demo using the Team_Admin user (not you will need a CSS ID to locate the user to deactivate)._ 

**Ideas**
A confirmation modal when marking the user inactive that lists the attorneys' names and CSS IDS that will also go inactive (gives them a chance to take note of the information) not the ideal workflow bc it's kind of manual, but notifies them. _Note: marking a VLJ inactive will not mark the attorney in active as well it will just leave the attorney orphaned (meaning not assigned to a judge team)._

**Comment by geronimoramos** [comment]
MVP version: Here is the modal for when the user clicks the mark user inactive button -> modal pops up giving them instruction to take note of the attorneys on the team. Let me know your feedback!

![image](https://user-images.githubusercontent.com/49766982/81615087-e3d4b680-9395-11ea-9e43-a53f41604b87.png)

**Comment by hschallhorn** [comment]
My only comment would be to also include atty names/css ids in the alert!
