### ISSUE TITLE
Case Details | Task actions should be alphabetized

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#13612]
## Description
During the Motion to Vacate dogfooding, we discovered that task actions are not alphabetized, it would be good to alphabetize the task actions.

## Acceptance criteria
- [ ] Task actions should be alphabetized

## Background/context/resources
https://docs.google.com/document/d/1IZw48Lby9Ez8MxbXlMv21b9cllpODZOvMT0FiCTsl_k/edit

This will likely impact the rest of queue so it would be good to touch base with them.

## Technical notes

**Comment by leikkisa** [comment]
Tabling this ticket, potentially move to Echo

**Comment by msj0nes** [comment]
@araposo-tistatech this is the ticket I was telling you about. It may very well be a bug, as Jim mentioned it should be alphabetized. Transferring the ticket as low priority to Echo.

**Comment by hschallhorn** [comment]
Better to alphabetize or sort by most used?
