### ISSUE TITLE
Motion to Vacate | Fix Link to Chairman Memorandum and all assets 

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#13611]
## Description
During the Motion to Vacate dogfooding, we discovered that link to chairman memorandum and all assets is broken.

## Acceptance criteria
- [ ] Link to Chairman Memorandum in the yellow CAVC alert opens up the PDF to the Chairman Memorandum
- [ ] Check and fix other assets in the assets folder as well (such as training documents)

## Background/context/resources
This appears to be working on demo.

Please review dogfooding link for screenshots https://docs.google.com/document/d/1IZw48Lby9Ez8MxbXlMv21b9cllpODZOvMT0FiCTsl_k/edit

## Technical notes
The assets seem to need to be linked from the public folder now. It was there once upon a time, and now it has moved back. Might involve interfacing with devops.

**Comment by msj0nes** [comment]
### Status
Ticket is on hold pending BVA SME demo session to discuss with users changes required to this ticket.

**Comment by leikkisa** [comment]
We can move forward with this

**Comment by leikkisa** [comment]
@jcq There's another ticket for the copy of the alert, you can go forward with this one.

**Comment by msj0nes** [comment]
@leikkisa and @jcq closing this ticket. Post-demo with BVA they have proposed their our verbiage for the banner which no longer includes the Chairman's memorandum. 

We are only changing the copy, followed in ticket https://github.com/department-of-veterans-affairs/caseflow/issues/13960


_See BVA proposal below_
![image](https://user-images.githubusercontent.com/41164406/79754880-31558a80-82e6-11ea-876f-5160e7a269af.png)
