### ISSUE TITLE
Handle display of cancelled tasks in VLJ Support completed tab

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#13619]
## Description
Sometimes a cancelled task shows up in the Completed tab for VLJ Support Staff cases, most recently as a result of cleaning up legacy appeals whose VACOLS records have gone missing (although there may be other reasons).

This causes the frontend to try to load the hearings badge, resulting in a 404 alert in Sentry. It is also probably pretty confusing to the user, as nothing can be done or displayed for this task, e.g.:

<img width="812" alt="Screen Shot 2020-03-04 at 17 50 38" src="https://user-images.githubusercontent.com/282869/75930740-4b740000-5e41-11ea-923e-3d4834bfce7b.png">
(clicking on the appeal link leads to a 404 page)

## Background/context/resources
Slack thread with Echo team:
https://dsva.slack.com/archives/CJL810329/p1583273269121300

Original Slack thread for investigating Sentry alerts: https://dsva.slack.com/archives/C4JECDLSE/p1583245052073200

Cleaning up legacy appeals with missing VACOLS records: #12791

**Comment by hschallhorn** [comment]
Note: This is for tasks that were completed before the appeal itself was removed or cancelled. We'd like to continue showing the completed task in this tab so users can accurately measure the tasks that they have completed, regardless of what happened to the appeal after they finished their work.
