### ISSUE TITLE
Test POA flow for pilot

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13613]
## Description
The Power of Attorney (POA) flow needs to be tested and verified before the pilot. Ensure that the POA receives a participant link, rather than the host link.

## Technical considerations
We are only able to test this in the demo environment.

**Comment by ferristseng** [comment]
Just tested in demo, and I'm seeing the right link as VSO:

![Screen Shot 2020-03-10 at 11.22.27 AM.png](https://images.zenhubusercontent.com/569954a5638e718c99601d36/25d39091-6ba9-469f-a4e1-f01656e1362a)
