### ISSUE TITLE
Motion to Vacate | Frontend clean-up

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#13610]
## Description

During the Motion to Vacate dogfooding, we discovered a few front-end bugs in the Vacate and De Novo task and  se Motions to Vacate therefore, it would be good to do an overall clean up of things we missed.

## Acceptance criteria
- [x] On the Motion to vacate task page `provide context on which issues should be null` before clicking on any reviews for the motion, the text should be  `provide context on which issues should be granted`
- [x] On the Address Motion to Vacate page, the instructions from Motions Attorney to Judge would look better if it was on new lines.
- [x] On the Address Motion to Vacate page, the styling of page seems narrow and needs improvement.
- [x] On the Address Motion to Vacate page, when `Grant partial vactatur` is selected, the labels are not bolded. Please bold the labels.
- [x] On the Motions attorney page when grant is selected, it doesn't say "optional". Please add optional to the TextareaField where instructions are entered.
- [x] On the Motions attorney page still says "granting" by instructions when denied or dismissed are selected. Please ensure that the right disposition is shown when denied or dismissed are selected.
- [x] On the Address Motion to Vacate task page, the Dismiss radio button does not show the instructions as optional. Please add optional o the TextareaField where instructions are entered.
- [x] On the Address Motion to Vacate task page, the vacate type label and assign to attorney label not bolded are not bolded. Please bold these labels.
- [x] Add Spacing between button and text for `What is ineligible evidence?`.
- [x] Change button text from "Continue" to "Submit" in `SubmitVacatedDecisionsView` (This can be done by adding ```continueBtnText="Submit"``` as prop to `SubmitVacatedDecisionsView`)
- [x] When a task has been marked complete,  show full name instead of Initial and last name in the success banner “If you've made a mistake, please email Full name to manage any changes”

## Background/context/resources

Please review dogfooding link for screenshots https://docs.google.com/document/d/1IZw48Lby9Ez8MxbXlMv21b9cllpODZOvMT0FiCTsl_k/edit
## Technical notes
Suggestions for files to check out:

- MTVJudgeDisposition
- MotionsAttorneyDisposition

**Comment by leikkisa** [comment]
Check with @rutvigupta-design about bolding labels, especially when working on a component that is used elsewhere.

**Comment by Sjones352** [comment]
@rutvigupta-design and @leikkisa on this success banner, wouldn't it be better to use full name instead of initial and lastname. Also can we change the copy to `if you have made a mistake, please email Full name to manage any changes`. I like spelling out the words `have` 

<img width="1193" alt="Screen Shot 2020-03-12 at 3 46 16 PM" src="https://user-images.githubusercontent.com/23080951/76562967-d7f37380-647c-11ea-96e4-18adb3d4e358.png">

<img width="1185" alt="Screen Shot 2020-03-12 at 3 41 13 PM" src="https://user-images.githubusercontent.com/23080951/76562935-c742fd80-647c-11ea-848a-2ae7ffbac9e5.png">

**Comment by rutvigupta-design** [comment]
@Sjones352 I like the copy changes you suggested (changing you've to you have, and adding in the users first name)!
