### ISSUE TITLE
Adding attorneys to judge team

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13616]
J. Gosnell is unable to add attorneys to J. White's judge team. Problem statement below: 

I created a judge team this morning (456), but then I get the below error when trying to add her attorneys. 

**JudgeTeam in Team Management page**
<kbd>
![image005](https://user-images.githubusercontent.com/45575454/75922822-ccc39680-5e31-11ea-884e-4dcb8a09d3a5.jpg)
</kbd>

**JudgeTeam Management page errors**
<kbd>
![image006](https://user-images.githubusercontent.com/45575454/75922827-cdf4c380-5e31-11ea-9b6b-b20e45de99a1.jpg)
</kbd>

Previous investigation: 
https://hackmd.io/@hschallh/rk5XrD6EI#Investigation

## AC
 - Investigate why user cannot add attorneys to judge team they've created
 - Any bugs found have an issue filed

**Comment by lomky** [comment]
_[What is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

Timebox to a 3. 

Could be a 2 if the impersonation immediately shows the error. General optimism.

**Comment by yoomlam** [comment]
Replicated by:
- Log in as TEAM_ADMIN (VACO)
- Go to http://localhost:3000/team_management
- Create new judge team for BVAKKEELING
- Click "Org admin page", which goes to http://localhost:3000/organizations/bvakkeeling/users and I get the following:
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/55255674/76778899-90206500-6778-11ea-8dd5-6e73f28c9e8b.png">

Immediate cause: 
- The page requests `http://localhost:3000/unauthorized`, which sends back a `{"errors":["Unauthorized"]}` response.
  * Will look into this.

Note: `BVAKKEELING` and `BVAAABSHIRE` return the following:
```
user.judge_in_vacols?
=> false
user.acting_judge_in_vacols?
=> false
```

**Comment by yoomlam** [comment]
@araposo-tistatech Should John be a [System Admin](https://github.com/department-of-veterans-affairs/caseflow/wiki/Admins-in-Caseflow#system-admin)?

Here's a list of current System Admins: https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/functions-config.yml#L113


Also note the **Workaround** in the above comment.

Tech note: We check if user is an `admin?` [here](https://github.com/department-of-veterans-affairs/caseflow/blob/43562ed9e75b14c6f949802521da9df6a4214c2b/app/models/user.rb#L105).

**Comment by yoomlam** [comment]
Hunter will create another ticket to address permission consistency:
> Access to the team management page/access to create a team/access to view that team’s management page/access to modify members of a team should be the same

FYI: John's comment:
> It seems strange that I can create a team for a VLJ but can't add attorneys to it.
