### ISSUE TITLE
Motion to Vacate | Success banner after motions attorney sends recommendation to judge

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13622]
## Description
After a motions attorney clicks "Send to judge", fills out their recommendation, and submits it, there is no success banner.

## Acceptance criteria
- [ ] Add a success banner after the motion attorney sends their recommendation to the judge

## Designs
TBD

**Comment by jcq** [comment]
@rutvigupta-design What do we want the copy to be in the alert? 

Below is what I have as a placeholder:

<img width="981" alt="Screen Shot 2020-03-06 at 11 26 15" src="https://user-images.githubusercontent.com/2581274/76115692-7d01de00-5f9d-11ea-8fda-c6e9c76d90ea.png">

**Comment by rutvigupta-design** [comment]
@jcq here is the success banner. 
![Motions Attorney - Successfully sent review to judge](https://user-images.githubusercontent.com/51714306/76344210-99708400-62d7-11ea-8a8c-65d1a96d218d.jpg)

**Comment by rutvigupta-design** [comment]
UPDATED COPY: Removing (VLJ), so that the success banner reads: "You have submitted your review to [display_name]"
