### ISSUE TITLE
Success! Page | Action list line alignment

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1362]
When completing a task with multiple actions and observing the *Success!* page. The alignment of the 2nd line of the completed action (next to checkmarks) seems off.

_Current:_

<img width="1026" alt="screen shot 2017-03-28 at 11 46 12 am" src="https://cloud.githubusercontent.com/assets/18075411/24421098/10d91cda-13c3-11e7-8188-034e749a7e74.png">
<img width="979" alt="screen shot 2017-03-28 at 3 31 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/24423650/b820305c-13cb-11e7-9cbf-d5c3dbe49ecb.png">
<img width="1037" alt="screen shot 2017-03-28 at 7 19 22 pm" src="https://cloud.githubusercontent.com/assets/18075411/24431688/80aed61c-13eb-11e7-8885-ecadd98fc840.png">
As Kavi would say: "ugh..."

_Desired:_  (red line denotes proper indentation)
<img width="1021" alt="screen shot 2017-03-28 at 2 29 02 pm" src="https://cloud.githubusercontent.com/assets/18075411/24421267/a19baf30-13c3-11e7-9d63-8e54a23dd66f.png">

**Comment by shanear** [comment]
styleguide to the rescue @gnakm

**Comment by gnakm** [comment]
Closing this because I added it to the AC and mock in the style guide issue #1094
