### ISSUE TITLE
Log unsent or bounced emails

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13627]
## Description
Check response from Granicus (through ActionMailer gem) to ensure ability to log and monitor unsent and bounced emails. Log and send alert to Sentry to monitor unsent (and bounced, if possible) Veteran and Representative emails. 

## Out of scope
- Tracking email
- Implement job if email hasn't sent
- Notify hearing coordinator that email didn’t go through

## Background/context/resources
Though we have a current/manual fallback of Hearing Coordinators monitoring an inbox, we need a long-term, scalable solution to log and monitor issues with emails.

**Comment by ferristseng** [comment]
From the GovDelivery docs, when an email gets sent, the API sends back a response like this:

[Reference](https://developer.govdelivery.com/api/tms/tutorial/send_an_email/)

```json
{
  "id": 2715041,
  "subject": "Hello!",
  "body": "Hi!",
  "click_tracking_enabled": true,
  "errors_to": "errors@example.com",
  "from_email": "me@example.com",
  "from_name": "Me",
  "macros": null,
  "open_tracking_enabled": true,
  "reply_to": "reply@example.com",
  "message_type_code": null,
  "created_at": "2016-06-06T15:30:35Z",
  "status": "new",
  "_links": {
    "self": "/messages/email/2715041",
    "recipients": "/messages/email/2715041/recipients",
    "failed": "/messages/email/2715041/recipients/failed",
    "sent": "/messages/email/2715041/recipients/sent",
    "clicked": "/messages/email/2715041/recipients/clicked",
    "opened": "/messages/email/2715041/recipients/opened"
  }
}
```

I think the status will always be `"new"` here, but we can at least check to see if the API accepted our request or not. This ultimately won't give us insight into the delivery status of the email, but we can use the response that the API returns to eventually do that, if we save the appropriate links or message id.

We should be able to query the recipients link that gets returned in the `_links` field, and check the status for all the recipients we sent the email to (there should only be 1 recipient per email for our use-case):

[Reference](https://developer.govdelivery.com/api/tms/resource/messages/email/--email_id--/recipients/)

```json
[
  {
    "email": "test01@test.govdelivery.com",
    "macros": {
    },
    "status": "sent",
    "created_at": "2013-03-15T21:10:30Z",
    "completed_at": "2013-03-15T21:11:02Z",
    "_links": {
      "self": "/messages/email/10507/recipients/364897",
      "email_message": "/messages/email/10507",
      "opens": "/messages/email/10507/recipients/364897/opens",
      "clicks": "/messages/email/10507/recipients/364897/clicks"
    }
  },
  {
    "email": "test02@test.govdelivery.com",
    "macros": {
      "city": "RECIPIENT Saint Paul",
      "address": "RECIPIENT 408 Saint Peter Street",
      "company": "RECIPIENT GovDelivery",
      "url": "RECIPIENT www.govdelivery.com"
    },
    "status": "sent",
    "created_at": "2013-03-15T21:10:30Z",
    "completed_at": "2013-03-15T21:10:32Z",
    "_links": {
      "self": "/messages/email/10507/recipients/364898",
      "email_message": "/messages/email/10507",
      "opens": "/messages/email/10507/recipients/364898/opens",
      "clicks": "/messages/email/10507/recipients/364898/clicks"
    }
  }
]
```
