### ISSUE TITLE
Design and research for marking cases as overtime

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#13645]
# Success criteria for the design phase
We'll know our design is successful when we observe senior counsel members successfully mark a case as overtime and remove over time status without confusion in usability testing. Research participants will be able to articulate what marking a case as overtime means for the business (that is, attorneys can work on the case during over time hours). 

# Timeline (tentative) 

## TBD
- [ ] What is the last date for when designs need to be complete so engineers can start work? 
- [ ] How do we re-scope based on that? 

## Week 1

- [x] 1. Review existing mock ups and compare for compatibility against current designs/workflows. 
- [x] 2. Adjust designs as necessary (with a goal of minimizing changes) 

## Week 2

- [x] 3. write research plan for usability testing (review research plan with product manager and design lead) 
- [x] 4. Create clickable prototype to use in testing. 
- [x] 5. Begin research participant recruitment. 

## Week 3

- [x] 6. Usability testing with 5-7 senior counsel members (need to verify that there are this many to test with) 

## Week 4

- [x] 7. Synthesize and present findings to team Echo, design lead (Decision point: what changes need to be made? Should we do another round of iteration and testing or are we done?)

## Week 5 

- [x] 8. Update designs as agreed upon, other work TBD based on results of usability testing. 

## Resources 

The designs for marking cases as over time are based on the universal case title designs: https://github.com/department-of-veterans-affairs/caseflow/issues/8211

**Comment by geronimoramos** [comment]
All of this work has been completed and design decisions have been made. An additional step may be to monitor and evaluate this iteration as real estate in case title/properties section is valuable and limited in considerations for the need to create additional functionality to alter cases.
