### ISSUE TITLE
Team Management | Need Validation and/or Error Handling on AddPrivateBarModal

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13641]
## Description
It looks like the `team_management/add_private_bar` endpoint will throw errors if `name` or `url` field are empty. However, `AddPrivateBarModal` does not set them to required, and does not gracefully handle error responses (Caseflow renders an empty white page and one needs to inspect the network request log to see what the error was).

## Acceptance criteria
- [ ] Frontend validation are performed in `AddPrivateBarModal`

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | |||||||
3 | |||
5 | 
8 | 
```

Why 1?
- Validation is a very common pattern we use in queue flow modal and can be reused here

Why 2?
- Validating existing UI

Why 3?
- Sometimes our FE state is tricky to validate
