### ISSUE TITLE
Make cancelled appeals more obvious in appeal search

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13654]
## Description
UI problem

At the Board's request, two appeals were modified so that the users will not be able to see or search for them based on the docket number. 
(The original request from Martina was to delete them so that users are not confused about cancelled appeals and their assignment to users -- [screenshots in slack](https://dsva.slack.com/archives/CHX8FMP28/p1583761683209100?thread_ts=1583267009.143600&cid=CHX8FMP28))
* Martina: "This makes it appear its still active and assigned to a user to work" 

Cancelled appeals should be made more obvious in the UI.

Needs Product, Designer, and end-user input.

Per end-user: Show the appeal in search, but show the status as "Cancelled"

## Acceptance criteria
- [ ] Distinguish cancelled appeals in the Case Search Results page
  - [ ] Do not display “assigned to” and indicate that appeal is cancelled/remove/what have you
  - [ ] Display appeals with no issues associated as "cancelled" in the status column of the search page
- [ ] Appeal is still clickable to be able to view the Case Details page

## Background/context/resources
* https://dsva.slack.com/archives/CJL810329/p1583769022223100
* https://dsva.slack.com/archives/CHX8FMP28/p1583764614216100

## Design
![Search Cases_Cancelled Appeals Mockup](https://user-images.githubusercontent.com/59883609/77001985-2a2b0d80-6931-11ea-8c5a-51eed58727c9.png)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | ||||||||||
5 | 
8 | 
```
This is specifically about how appeals appear in the search results page. Later we may want to add something to the Case Details page. Backend change to provide the info that the appeal is changed, but this is mostly front end work

Estimated at a 3.

Backend and frontend changes, with a mild amount of unknown in the AC waiting for final design.

**Comment by yoomlam** [comment]
Ultimately [deleted the two appeals](https://dsva.slack.com/archives/CHX8FMP28/p1583862127248300?thread_ts=1583267009.143600&cid=CHX8FMP28) due to reporting errors.

**Comment by pkarman** [comment]
I highly recommend leveraging the `appeal.status` method to determine the business logic for this, as it is aligned with what BVA users will expect in their reporting.

**Comment by hschallhorn** [comment]
Yep, looks like we just don't serialize ama appeals' status, so that value doesn't exist on the front end. That may be the only change we need to add for the status portion of this.

**Comment by geronimoramos** [comment]
Making the `Canceled` status in red #e31c3d makes a lot of sense to make it obvious for the user. 

And just a thought, do we want it to be more obvious as well to the user from the Case Details page? Not sure if it's a problem, but an idea would be using a Warning Status alert component at the top.

**Comment by pkarman** [comment]
On case details it seemed important to BVA folks to "unassign" the case if it is cancelled, so whatever logic is setting the "assigned to" value should take the status into account.
