### ISSUE TITLE
 Deep dive into limitations of acting judges in caseflow - Hearings

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13652]
Split off of #13136 
[Relavent slack thread](https://dsva.slack.com/archives/CJL810329/p1578607001034900)
[Previous acting judge work](https://github.com/department-of-veterans-affairs/caseflow/pulls?utf8=%E2%9C%93&q=is%3Apr++%22Acting+judge%22)
[Batteam](https://dsva.slack.com/archives/CHX8FMP28/p1578069080207800) issues [related](https://dsva.slack.com/archives/CHX8FMP28/p1577821139163100) to [avljs](https://dsva.slack.com/archives/CHX8FMP28/p1570051221294100) from [slack](https://dsva.slack.com/archives/CHX8FMP28/p1567534420110500).

At the board, attorneys rotate through stints as acting judges. These users should have the same functionality as a normal judge (minus maybe having a judge team) while also being able to complete tasks as an attorney. 

To further understand what problems exist within caseflow for AVLJs, we need to
- [ ] Track down all actions on legacy cases a judge can perform in caseflow
- [ ] Track down all actions on ama cases a judge can perform in caseflow
- [ ] Track down all actions on legacy cases an attorney can perform in caseflow
- [ ] Track down all actions on ama cases an attorney can perform in caseflow
- [ ] Check which of the above actions an acting judge can perform

### AC
- [ ] List of limitations acting judges have on performing tasks in caseflow hearings

**Comment by ferristseng** [comment]
A case where AVLJs want to access the hearing worksheet link but can't see any of the hearings assigned to the judge:

https://dsva.slack.com/archives/C3EAF3Q15/p1604946248043000
