### ISSUE TITLE
[Sentry] Caseflow::Error::QueueRepositoryError: Decass record does not exist for vacols_id

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13653]
## Description

`Caseflow::Error::QueueRepositoryError: Decass record does not exist for vacols_id: 3577463 and date created: 2020-02-13`

Looks like this failure prevents judge from assigning case to attorney.

Not taking any action. Waiting for judge to submit Support request.

## Acceptance criteria
- [ ] Documentation for why this happens
- [ ] Updated failure message that is actionable

## Background/context/resources
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7252

```
LegacyAppeal 998633 (legacy)   ID     STATUS   ASGN_BY ASGN_TO UPDATED_AT
└── RootTask                   743260 assigned         Bva     2020-03-09 11:24:32 UTC

LegacyAppeal.find_by(vacols_id: 3577463).case_record.nil?
=> false
```
Case record exists.

* Error caused by `app/repositories/queue_repository.rb in find_decass_record at line 201`
* Initiated by `app/controllers/legacy_tasks_controller.rb in update at line 77`

## Technical notes
Looks like this failure prevents judge from assigning case to attorney:
```{
tasks: {
appeal_id: 998633, 
assigned_to_id: 1758, 
type: JudgeCaseAssignmentToAttorney
}
}```

**Comment by lomky** [comment]
Putting this at a 2 timebox!

**Comment by yoomlam** [comment]
2 events:

* Mar 9, 2020 10:17:28 AM EDTCaseflow::Error::QueueRepositoryError: Decass record does not exist for vacols_id: 3577463 and date 
* Nov 4, 2019 11:35:02 AM ESTCaseflow::Error::QueueRepositoryError: Decass record does not exist for vacols_id: 3961088 and date
