### ISSUE TITLE
Refactor Hearing Details and Daily Docket page for Virtual Hearings

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13662]
## Description
Refactor virtual hearings front-end in order to prepare for building out virtual hearing dockets.

## Technical notes

![HearingDetailsFlowChart-2](https://user-images.githubusercontent.com/1298274/77795614-3fe0b700-7044-11ea-9b50-a00266cb0f95.png)

**Comment by ferristseng** [comment]
Ideas:

  - Use React contexts to replace repeated props and shared global state in Redux
    - Hearing's user `Context`
    - Hearing's form `Context`
  - Come up with some guidelines with regards to:
    - Component scope: How "far" should a component be able to touch?
  - Thoughts about experimenting with immutability

**Comment by rubaiyat22** [comment]
- Think about how virtual hearing as a hearing type will affect the Details and DailyDocket
- reassess redux state and how it's being used

**Comment by ferristseng** [comment]
> Future work: we'll need to research how to refactor the DailyDocket page too

We want to make similar refactors to the DailyDocket page in preparation for virtual-only dockets:
