### ISSUE TITLE
Add Redux to Dispatch

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#1366]

**Comment by joofsh** [comment]
Redux *has* been added to Dispatch officially (via 2 PRs)
https://github.com/department-of-veterans-affairs/caseflow/pull/1452
https://github.com/department-of-veterans-affairs/caseflow/pull/1413

Will follow up with smaller tickets for others pieces of state that still need to be ported over

**Comment by kierachell** [comment]
**PASSED**
Checked by going back and forth; messing with issues; all the usual weirdness and did not find any new errors.
