### ISSUE TITLE
User Research Study: Contested Claims | Attorney Fees or Full Contested Claims

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#13667]
## User story
BVA Intake users need a way to intake contested claims in Caseflow, starting with attorney fees claims (which may be one of the more frequent claims we see coming in).

## Problem statement
The team needs to establish an understanding of what contested claims are, the various types, and what the general process is for someone to submit such a claim. Via user research, we need to clarify how users are currently processing contested claims, what their workarounds in Caseflow are, and what their pain points and needs are.

## What is out of scope?
- What happens after a user intakes a contested claim (this belongs in Team Echo's territory)

## Background/context
- Contested claims occur when two or more people are fighting over the same benefit (they don't have to be related to the veteran e.g. an attorney, funeral home etc. 
- Some work might have been done on this by a previous Caseflow team, however the functionality does not fully exist in Caseflow and we are unclear what user needs look like

## What are the unknowns?

- Apportionments: issues that are covered, history of apportionments in the dept, more context information 
- Do we need to design for apportionments?
- What does the process of filing such a claim look like? 
- How are issues impacted?
- What use cases do we need to consider?
- What is happening behind the scenes for each contested claim type?

## For research tickets only: What questions do we hope to answer? What are our learning goals?

- What are the various types of contested claims? What is the general process?
- How are users currently processing contested claims? What is working well and what are they struggling with? What are their workarounds?
- What does an ideal future look like? What does success look like to our users?

## Existing design and content

- Currently this functionality exists in VACOLS but the purpose of this research study is to clarify what this looks like 
- Users might have established their own workaround in Caseflow, that we need to learn more about

## Success criteria

- Users can successfully intake attorney fees claims 
- Users can successfully enter a claimant other than current spouse or child and who isn't currently listed in Caseflow (i.e. an attorney, an agent, an ex-spouse, etc.)
- Users can successfully intake all other contested claims 

## Technical/logistical constraints (if known)

- Existing Intake bugs
- Scheduling with intake users

**Comment by jimruggiero** [comment]
Please add this to your success criteria: Users can successfully enter a claimant other than current spouse or child and who isn't currently listed in Caseflow (i.e. an attorney, an agent, an ex-spouse, etc.)

**Comment by rutvigupta-design** [comment]
Discovery Research findings for Attorney Fees [here](https://github.com/department-of-veterans-affairs/appeals-research/issues/14).

**Comment by rutvigupta-design** [comment]
See more on what happens after Intake to process attorney fees claims in #14410
