### ISSUE TITLE
Update `updated_at` when a task is closed

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13676]
## Description
While working on Bat Team and [uncancelling tasks for an attorney](https://github.com/department-of-veterans-affairs/caseflow/wiki/Bat-Team#uncancel-an-appeal-accidentally-closed-by-closing-last-issue), I noticed the `closed_at` and `updated_at` timestamps are not consistent:
```
Appeal 53655 (direct_review)     ID     UPDATED_AT              CLOSED_AT
└── RootTask                     630053 2020-01-21 15:58:00 UTC 2020-02-15 04:26:31 UTC
    ├── DistributionTask         630054 2020-01-22 20:38:47 UTC 2020-01-22 20:38:47 UTC
    ├── JudgeAssignTask          634903 2020-02-07 16:33:56 UTC 2020-02-07 16:33:56 UTC
    └── JudgeDecisionReviewTask  674788 2020-02-07 16:33:56 UTC 2020-02-15 04:26:31 UTC
        └── AttorneyTask         674789 2020-02-07 16:33:56 UTC 2020-02-15 04:26:31 UTC
```

It seems like `updated_at` should be updated when a task is closed.

## Acceptance criteria
- [ ] `updated_at` should be updated when a task is closed

## Background/context/resources
https://dsva.slack.com/archives/CQCUMFA0H/p1583951827205400?thread_ts=1583950753.201600&cid=CQCUMFA0H

**Comment by pkarman** [comment]
`updated_at` is automatically set by ActiveRecord. We should only manually set it when we use `update_all`.  See https://stackoverflow.com/a/18873228

**Comment by hschallhorn** [comment]
https://github.com/department-of-veterans-affairs/caseflow/blob/761e76a628fb5b5a2ea322755d51133d8e33ffe8/app/models/task.rb#L528-L531

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||||
2 | ||
3 | 
5 | 
8 | 
```

When `update_all` is used in our code, follow up with appropriate calls to update timestamps.
Check for similar scenarios elsewhere in the code.

Why 1?
- Manually update `updated_at` when cancelling all tasks on an appeal
