### ISSUE TITLE
Investigation | Contentions missing a new rating in VBMS

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13685]
## Description

Claim ID:73069663.  This was for an EP040 that was cleared on 6/19/2019.  We have received subsequent claim forms (0995 and 0996) but are unable to establish the claim.  Caseflow Queue shows an error message: “Cleared, decision sync failed. Support notified.” The contention was denied, but there’s no rating profile from after the EP was cleared with the new rating issue. The newest rating (from before this EP was cleared) does not show the “Denied” decision. Caseflow is unable to resolve this issue as it appears to be due to a VBMS bug. (Sally thinks this may relate to the previous issue. Will wait for VBMS to address.)

## Background/context/resources
n/a

## Technical notes
n/a

**Comment by Sjones352** [comment]
https://dsva.slack.com/archives/CHX8FMP28/p1595274759474800
