### ISSUE TITLE
Validate document_id when checking if a decision has been written for a case

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13688]
## User story
As an AVLJ, I need to see attorney actions on legacy cases assigned to me, so that I can draft decisions. As of right now, if the [document id on the appeals associated decass record](https://github.com/department-of-veterans-affairs/caseflow/blob/8105d0b15856f67b0db9deda34b45495806b8248/app/models/queues/legacy_work_queue.rb#L34) is anything other than `nil`, acting judges are shown judge actions. On occasion, this value will read "NONE". We should instead validate that the document id is valid, not just that it exists.

## Acceptance criteria
- [ ] Check [document_id](https://github.com/department-of-veterans-affairs/caseflow/blob/8105d0b15856f67b0db9deda34b45495806b8248/app/models/queues/legacy_work_queue.rb#L34) is valid before returning true 

### Out of scope
Further work to better determine what actions to show an AVLJ will be done. This issue is to only solve the issue that arose from invalid document ids.

### Background/context
Allow AVLJs to be assigned legacy cases #11971
Allow AVLJs to perform judge tasks on legacy appeals #11977
Use the presence of a decision doc id to determine if a case has already gone to an attorney #13530

### Technical notes
We already do validation of document ids on attorney checkout [here](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/validators/ama_attorney_case_review_document_id_validator.rb#L18). This could be reused.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||||
5 | 
8 | 
```

Based on when Doc ids are pulled from DAS, which might not be done in Caseflow, so its not validated by us. 
Only affects legacy appeals. Where we pull in cases from vacols for a users legacy queue.

Estimating at a 3.

Might be simple as the location is well known, just have to update the value.
