### ISSUE TITLE
Log video to virtual conversions in Datadog

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13684]
## Description
Log (count or timestamp) when a user successfully and unsuccessfully tries to convert a video hearing into a virtual hearing.

## Acceptance criteria
- [ ] Update documentation: [link]

**Comment by ferristseng** [comment]
FYI: I'm defining a constants file with the metric group for virtual hearings in #13776

The metrics I'm expecting to generate are these:

  - `dsva_appeals.virtual_hearings.deleted_conferences.failed`
  - `dsva_appeals.virtual_hearings.deleted_conferences.successful`
