### ISSUE TITLE
Set up logging for hearing tasks

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13687]
## Description
Track historic, current, and future hearing tasks to chart metrics for hearings. Record when dispositions were set on hearings and what they were. 
- Track No Shows
- Track Cancelations
- Track Postponements

## Acceptance criteria
- [ ] Create query
- [ ] Create chart in Metabase

## Background/context/resources
Decrease No Shows, Cancelations, Postponements by introducing virtual hearings to allow Veterans more flexibility.

**Comment by ferristseng** [comment]
Dashboard with hearings metrics: http://query.prod.appeals.va.gov/dashboard/5
