### ISSUE TITLE
Allow Acting Judges (AVLJs) to be assigned drafting of Legacy Cases

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13680]
## Description
When an attorney on a Judge's team has been tapped to do Acting Judge (AVLJ) work, they still want to be able to accomplish on attorney work. At the moment, these attorneys cannot be assigned Legacy cases to draft decisions for.

## Acceptance criteria
- [ ] Attorneys with AVLJ status can be assigned & work legacy attorney drafting tasks (`AttorneyLegacyTask`s)
- [ ] Create/Update AVLJ documentation (none at time of issue filing)
- [ ] Consult with Training on on updating AVLJ training docs & quick reference sheets

## Background/context/resources
Previous work with AVLJ judge abilities: 
#11971 
#11977 

See [AVLJ DeepDive Summary item 2](https://hackmd.io/dSs1Ly_xT-uYXwU9F-8Q5g?view#Summary). #13136

Potential case of some Support / Bat Team Requests, but not directly implicated!

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||
2 | |||||
3 | ||||
5 | 
8 | 
```
Looks like the UI thinks we're reassigning to a judge.
The problem exists on both the assign page and the case details page.
The front end is giving an error, unknown if the problem is deeper, as well.
Check in both Judge Assign and Case Details pages.

Why 1?
- Pretty sure we throw the error if `judge_in_vacols?` returns true. instead, we should check if the assignee is an attorney in vacols.

Why 3?
- Time to understand what's going on and fix it
- Feature test? One might exist to update?

**Comment by hschallhorn** [comment]
I think the reason we could not assign a legacy case to an avlj is just bad dev data. The deep dive does not list the actual error shown on the front end, but I was able to identify and resolve the 2 errors keeping us from being able to assign a legacy appeal to an acting judge. See "Testing plan" in #15591.

1. There are multiple vacols staff records for BVAAABSHIRE. This results in a "This case is already assigned"
1. The staff record for the acting judge has no stitle (as they do in prod). We use [this value](https://github.com/department-of-veterans-affairs/caseflow/blob/c6d6b98e23d156d5b8fd0e971185a4e74338d316/app/repositories/user_repository.rb#L125-L127) as [`User#vacols_group_id`](https://github.com/department-of-veterans-affairs/caseflow/blob/a21255408f5d6d62f0bed3afcb4c3a557460399e/app/models/user.rb#L139) [`decass_attrs.group_name`](https://github.com/department-of-veterans-affairs/caseflow/blob/96fa3863bd31850bc7deb2b8816f70c3d0cc6926/app/repositories/queue_repository.rb#L141) and [`VACOLS::Decass.deteam`](https://github.com/department-of-veterans-affairs/caseflow/blob/45f40c3aa4b83f90fbebe228cc6052b74702e051/app/mappers/queue_mapper.rb#L16) which is a [required attribute](https://github.com/department-of-veterans-affairs/caseflow/blob/45f40c3aa4b83f90fbebe228cc6052b74702e051/app/models/vacols/decass.rb#L11). This results in a "Deteam cannot be blank" errror

If this is the case (bad dev data) I think we should morph this ticket into a tech improvement to fix our seeds.

**Comment by GabbyTISTA** [comment]
https://vajira.max.gov/browse/CASEFLOW-1619
