### ISSUE TITLE
Research email communications with Veterans

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13686]
## Description
Describe how well the virtual hearing emails and times are working for Veterans, representatives, and judges.

## Problem statement
Historically hearings are held on a rolling docket, meaning that the day's Veterans all arrive for the morning or afternoon and their hearings are held on a first-come-first served basis. Appointment and time-based functionality is new to the Board and is how the new Virtual Hearing emails are set up.

**Comment by nicholer** [comment]
Addressed via #14546
