### ISSUE TITLE
Document All Existing FeatureFlags

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13692]
## Description
Create a wiki page with information on all the current FeatureFlags in the master branch of the Caseflow repo.

## Acceptance criteria
- [ ] Create a wiki page
  - Feature flag name
  - Feature flag proper name, if different
  - Description of the feature
  - Sprint Team that created it [DevOps, Delta, Echo, FoxTrot, Tango, Whiskey]
  - Sprint Team that owns it, if any, if different [None, DevOps, Delta, Echo, FoxTrot, Tango]
  - created date
  - release date [estimated or actual]
  - paused date [if any]
  - state of development [In progress, stalled, in production with some users, fully released]
  - Next step [adopt by a team?, remove as fully released?, etc]
  - Related Epic/Issues
  - Notes

**Comment by jimruggiero** [comment]
This one won't have a Product/Project, so added the team and eng labels in its place.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | |||||||||
5 | 
8 | 
```

Why 2?

Why 3?
- Lots of cross team collaboration
- Reading through closed tickets and PRs to track down to lost context

**Comment by yoomlam** [comment]
Oldie but goodie: https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/docs/FeatureToggle.md#current-features

**Comment by hschallhorn** [comment]
https://github.com/department-of-veterans-affairs/caseflow/wiki/Adding-a-Feature-Flag-with-FeatureToggle#currently-implemented-toggles
