### ISSUE TITLE
Echo Queue: FNOD Notifications

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13699]
## Background/context
A notification that an appellant has died can occur at any point of the appeals process. If a notification is received the case is processed as a death dismissal. 

Currently, in the legacy context, there is a field in VACOLS where an RO or members of the Board can input a FNOD date. When an FNOD date is input an alert pops up (for any user who views the case) indicating the appellant has died and the case should be moved to a VLJ. If the case has not been assigned to a judge/attorney, the case is moved to location 66. Once in location 66 a report is pulled by the SCT team and DVC Staff Assistants to assign the cases to VLJs. Once assigned, VLJs assign the case to an attorney to begin the decision drafting process as a dismissal.
  
There are also cases where an FNOD date was not input into VACOLS, but the appellant has passed. In these cases the death needs to be verified by either the attorneys SSC assigned to the case or VLJ Support using a Social Security Administration system. 

As Caseflow does not support expediting cases for death dismissals the cases are pulled out of Caseflow and moved to location 66. This is currently a manual process for multiple teams (Hearings & VLJ Support) Note: the current VLJ support work around will be addressed once the Death Dismissal thread of work is completed. 

Complete write up of the legacy process located [here](https://app.mural.co/t/workqueue2001/m/workqueue2001/1585592742468/8bb0d9bb40f3d54337faf001c37123e2fc20574d). 

## Goals
The goal of this project is to add a notification in Caseflow when a Final Notice of Death is logged for a Veterans case. 

## Success criteria
Caseflow users are able to immediately see a notification and or flag when a FNOD date is added for the appellant. 

## Stakeholders
Attorneys
VLJ
VLJ Support
Litigation Support
Hearings Branch

## Requirements/stories

User Story: As a an attorney and/or a VLJ I need to see an notification or indicator when a Notice of Death date was added to VBMS or VACOLS so I know what type of decision to draft. 

## Open questions
If the case is not currently distributed, but an FNOD date is added should the case move to the top of the distribution logic (similar to AOD cases)?

Should the Death Dismissals work be opened to up to other organizations not just VLJs? Per the Board, yes any user should be able to trigger the Death Dismissal process. 

Should the Death Dismissals work be included here? The Board has approved completing the VLJ work before this epic. 

Who needs to have the ability to move cases to location 66 (possibly anyone who looks at the case details in caseflow for any one of the following locations 55, 57, 81, & Caseflow)?

Will a case ever go back to VLJ support or lit support after a death dismissal has been drafted?

Aside from getting the case dispatched faster is there any other reason why the case is pulled out of Caseflow? 

## References/Resources
Mural of Process  - https://app.mural.co/t/workqueue2001/m/workqueue2001/1585592742468/8bb0d9bb40f3d54337faf001c37123e2fc20574d

Product Brief - https://docs.google.com/document/d/1jfj4xN5LHq0XQBsR44f0ikAh9hWAwZXForefyv7K-8s/edit#

### Business value
Having the ability to view an indicator of an FNOD will allow users to act on these cases sooner rather then later. This will in turn allow death dismissals to be processed more efficiently.  

### Dependencies
#12211

**Comment by araposo-tistatech** [comment]
Closing, duplicate of #13131

**Comment by hschallhorn** [comment]
Reopening as #13131 is different work!

**Comment by pshahVA** [comment]
Category | Metric | Applicable? | Approx Impact | Notes
-- | -- | -- | -- | --
Reach | Veterans Impacted (annually) |   | 400 |  
Users   Impacted |   |   |  
Technical   Complexity | Level of effort | Medium |   |  
Alignment to Goals and ability to measure success | Increase adoption of caseflow?   (estimated increase in # of users) | x | 5 users |  
Support   more appeal types? (estimated increase in # appeals) | x | 400 |  
Increase   timeliness of claims? |   |   |  
Increase   system ease of use? | x |   |  
Better   Veteran experience? |   |   |  
Increase   accuracy of appeals? |   |   |  
Timeliness | Increase speed of legacy   inventory processing? |   |   |  
Increase   speed of decision processing? (Which docket/lane) |   |   |  
Task   time (how long does the task take today, how much faster could it be?) |   |   |  
Cost   of Inaction | Is there a political impact if   we don’t do this? |   |   |  
Number   of Veterans or claims impacted is low, but the damage is high. |   |   |  
Damage   to VA reputation. |   |   |  
VACOLS | Does this deprecate a feature in   VACOLS? |   |   |

**Comment by pshahVA** [comment]
Category | Metric | Applicable? | Approx Impact | Notes
-- | -- | -- | -- | --
Reach | Veterans Impacted (annually) |   |   |  
Users   Impacted |   |   |  
Technical   Complexity | Level of effort |   | Medium |  
Alignment to Goals and ability to measure success | Increase adoption of caseflow?   (estimated increase in # of users) |   |   |  
Support   more appeal types? (estimated increase in # appeals) |   |   |  
Increase   timeliness of claims? |   |   |  
Increase   system ease of use? | x |   |  
Better   Veteran experience? | x |   |  
Increase   accuracy of appeals? |   |   |  
Timeliness | Increase speed of legacy   inventory processing? | x |   |  
Increase   speed of decision processing? (Which docket/lane) |   |   |  
Task   time (how long does the task take today, how much faster could it be?) |   |   |  
Cost of Inaction | Is there a political impact if   we don’t do this? |   |   |  
Number   of Veterans or claims impacted is low, but the damage is high. | x |   | Veterans should handle NOD with   tact and caution.
Damage   to VA reputation. |   |   |

**Comment by hschallhorn** [comment]
Engineers would love to know if some of this process can be automated by caseflow.
 - [ ] Can certain tasks be automatically cancelled when caseflow notices a veteran has passed
 - [ ] Can we move these cases to a certain user?
 - [ ] Can we do the same for legacy appeals?

**Comment by GabbyTISTA** [comment]
Posting to maintain my access
