### ISSUE TITLE
Caseflow Intake | Design | Current State | User Flow

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13695]
## Problem statement
In stakeholder communications and improving internal understanding of the Caseflow Intake product and functionality available, there is a need for a current state user flow that can be updated and maintained via mural etc.

## Resources
Please use the resources available [here](https://github.com/department-of-veterans-affairs/appeals-team/tree/master/Project%20Folders/Caseflow%20Projects/Foxtrot/Design) to as well as engineering inquiries to formulate the user flow requested.

## Success criteria
- The Caseflow team is able to view a high-level user flow associated to the current state of the Intake product.
- In an exportable format for sharing with stakeholder if need arises and for storage outside of Mural app

## Design Links
V1 User flow in [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1590517475916/a36757fafb632dc75f84de0b7097fe4c737ff07f)

**Comment by rutvigupta-design** [comment]
Closing because V1 of the user flow has been designed in Mural, can be re-visited in the future if a more detailed user flow is required (dependency - generative research with Intake users).
