### ISSUE TITLE
Handle TypeError: Cannot read property 'value' of null in LookupParticipantIdModal.jsx

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13703]
Handle `Cannot read property 'value' of null` error.

`./app/queue/LookupParticipantIdModal.jsx in apply at line 88:47`

https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/LookupParticipantIdModal.jsx#L88

```
    if (this.state.css_id && this.state.station_id) {
      url = `/user_info/represented_organizations?css_id=${this.state.css_id}&station_id=${this.state.station_id}`;
    } else {
      url = `/users/${this.state.selectedUser.value.id}/represented_organizations`;
    }
```

Should `this.state.selectedUser` ever be null?

Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7822

## AC
- [ ] Add validation, if this is the cause

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||
3 | ||||||
5 | 
8 | 
```

Why 1?

Why 2?
- Could be straight-forward diagnostics
- Easy validation on the front end if this is indeed the issue

Why 3?
- Investigation time

Why 5?

**Comment by hschallhorn** [comment]
![Screen Shot 2020-03-19 at 1 53 08 PM](https://user-images.githubusercontent.com/45575454/77098605-03301280-69e9-11ea-8217-39a6f6b8f3bd.png)

Yep, looks like we just need to add validation to the front end 🎉
