### ISSUE TITLE
Handle TypeError: Cannot read property 'reduce' of undefined 

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#13704]
Getting a lot of `TypeError`s during BatTeam: 
```
ReactOnRails encountered an error while rendering component: EstablishClaimPage.
Original message: Cannot read property 'reduce' of undefined
```

```
export const validModifiers = (endProducts) => {
  let modifiers = MODIFIER_OPTIONS;
  let modifierHash = endProducts.reduce((modifierObject, endProduct) => {
    modifierObject[endProduct.end_product_type_code] = true;
    return modifierObject;
  }, {});
```
Called by:
```
export const getEstablishClaimFormInitialState = (props = {}) => {
  let initialModifier;
  if (props.task) {
    initialModifier = validModifiers(props.task.appeal.pending_eps, props.task.appeal.dispatch_decision_type)[0];
  }
  return {
    stationOfJurisdiction: null,
    endProductModifier: initialModifier,
```
Called by:
```
import bootstrapRedux from '../../establishClaim/reducers/bootstrap';
import ReduxBase from '../../components/ReduxBase';
import EstablishClaimContainer from './EstablishClaimContainer';
export const EstablishClaimPage = (props) => {
  const { initialState, reducer } = bootstrapRedux(props);
  return (
    <ReduxBase initialState={initialState} reducer={reducer}>
      <BrowserRouter>
        <EstablishClaimContainer {...props} />
```

Sentry alert:
* https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9379/

Actions:
* Investigate cause
* Fail early and improve error msgs (make them actionable)

**Comment by yoomlam** [comment]
Why caseflow-dispatch and not caseflow-intake?
Because:
```
app/views/dispatch/establish_claims/assigned_existing_ep.html.erb:4:<%= react_component("EstablishClaimPage", props: {
app/views/dispatch/establish_claims/canceled.html.erb:3:<%= react_component("EstablishClaimPage", props: {
app/views/dispatch/establish_claims/canceled_tasks.html.erb:5:  <%= react_component("EstablishClaimPage", props: {
app/views/dispatch/establish_claims/complete.html.erb:3:<%= react_component("EstablishClaimPage", props: {
app/views/dispatch/establish_claims/show.html.erb:3:<%= react_component("EstablishClaimPage", props: {
app/views/dispatch/establish_claims/unprepared_tasks.html.erb:5:        <%= react_component("EstablishClaimPage", props: {
```

**Comment by yoomlam** [comment]
Possibly related [another Sentry alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9425/) that has the same error message about `Cannot read property 'reduce' of undefined` but points to a code block where `reduce` isn't even mentioned.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||||||
5 | 
8 | 
```

Timebox to a 3.

Why 1?

Why 2?


Why 3?
- First ever echo dispatch ticket! Assume it will take some time to ramp up on dispatch code and workflow

Why 5?

**Comment by nanotone** [comment]
I did a little more investigating during my 🦇 shift:

This happens if the corresponding LegacyAppeal is missing a veteran (i.e. `#veteran` returns nil for whatever reason), causing the appeal's serialization to have a null `pending_eps` which results in an error when rendering the React page.

Example: Dispatch::Task 185744 which is associated with LegacyAppeal 1113710.

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9675

**Comment by jcq** [comment]
This was brought up as a 🦇issue:
https://dsva.slack.com/archives/CHX8FMP28/p1587670047431900

This is for `EstablishClaim` 189417, which is associated with `LegacyAppeal` 1132402. The issue here appears to be exactly what was referenced by @nanotone above: for whatever reason the `veteran` returns nil for that `LegacyAppeal`

**Comment by yoomlam** [comment]
Updated link to solution: https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#legacy-appeal-missing-a-veteran
Also tweaked the solution a bit.

**Comment by yoomlam** [comment]
While working on [this Support ticket](https://dsva.slack.com/archives/CHX8FMP28/p1597152784213200), the reason the page doesn't load is due to [Legacy Appeal missing a veteran](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#legacy-appeal-missing-a-veteran). When trying to load the page, the browser errors out when trying to submit a request to https://sentry.ds.va.gov/api/3/store/?sentry_version=7&sentry_client=raven-js%2F3.27.0&sentry_key=0a3d0b0224794c0fbfe59e4e548ba7b8:
![image](https://user-images.githubusercontent.com/55255674/89947519-35394f80-dbea-11ea-91d6-04cc08e9c70a.png)

(The Sentry URL probably needs to be updated to https://sentry.prod.appeals.va.gov/ -- see [slack convo](https://dsva.slack.com/archives/CJL810329/p1597179627218600))

Understandably, I could not find a corresponding Sentry alert but did find similar alerts: https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10241, the latest being on Jul 20.
The error is caused by this (further confirming @nanotone's comment earlier):
`./app/establishClaim/util/index.js` in `validModifiers` at line 51:
```ruby
  let modifierHash = endProducts.reduce((modifierObject, endProduct) => {
    modifierObject[endProduct.end_product_type_code] = true;
    return modifierObject;
  }, {});
```
which is called by https://github.com/department-of-veterans-affairs/caseflow/blob/bbf34fab6cc833bb832037cb1e140259e749343c/client/app/containers/EstablishClaimPage/EstablishClaim.jsx#L298
The error occurs when `task.appeal.pending_eps` returns nil.

We could fix this by handling nil `endProducts` but there should (probably) be an end product (and decision document) by the time an appeal gets to dispatch, so we should display an error because the "Legacy Appeal missing a veteran" or specifically, the appeal is has been disassociated with the Veteran.

Also note that it doesn't seem like the second argument `this.props.task.appeal.dispatch_decision_type` is being used.

Regarding the lack of a decision document and displaying error messages, this piece of code has apparently never been executed by an end-user: https://github.com/department-of-veterans-affairs/caseflow/blob/2b1e85ca9328c6c7697cb4e7a8d5b844a18402ab/app/controllers/dispatch/establish_claims_controller.rb#L29

When forcing that code to execute, there is no `no_decisions` template (which should be in the `app/views/dispatch/establish_claims` directory):
![image](https://user-images.githubusercontent.com/55255674/89955641-1b533900-dbf9-11ea-9b4d-9d55419352e4.png)

Some research is needed to understand the scenario and confirm how Caseflow should respond to the end-user.

**Comment by yoomlam** [comment]
https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10241 continues to occur.
```
GET /dispatch/establish-claim/218913
Referer: https://appeals.cf.ds.va.gov/dispatch/establish-claim/218908
```

**Comment by yoomlam** [comment]
Fixed recurring Sentry alert for Dispatch:
```ruby
id_from_url=218913
legacy_appeal_id=Dispatch::Task.find(id_from_url).appeal_id
legapp=LegacyAppeal.find(legacy_appeal_id);

BGSService.new.fetch_veteran_info(legapp.veteran_file_number)
v = legapp.veteran
=> #<Veteran:0x000000000d0d1f08
 id: 172623,
 file_number: ...,
 participant_id: nil,
 first_name: nil,
 last_name: nil,
 middle_name: nil,
 name_suffix: nil,
 closest_regional_office: nil,
 ssn: nil,
 created_at: nil,
 updated_at: nil,
 date_of_death: nil>

v.stale?
=> true
v.update_cached_attributes!
v.reload
```

and added instructions to https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#legacy-appeal-missing-a-veteran
