### ISSUE TITLE
Motion to Vacate | Update Field Name for Hyperlink in Deny/Dismiss Workflow

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13725]
## Description

BVA stakeholders in a business demo provided feedback on this element and believe this hyperlink should point to the uploaded decision document in Reader in order to be useful to VLJs in the next stage of the workflow. Currently no shared folder environment exist to use the link as currently designed. 

## Acceptance criteria

**1. As a Litigation support team member and VLJ user, the field name below should reflect the below and additional copy removed:** 

> **_Insert Caseflow Reader document hyperlink to denial draft_**

![image](https://user-images.githubusercontent.com/41164406/76883452-8d923e00-6852-11ea-85fe-9d6121febcc9.png)

**2. Make the 'Caseflow Reader' in the field name link to the veterans claims folder. Opening in a new tab**
> this is the same folder with a visible hyperlink accessible on the Case Details page. 
![image](https://user-images.githubusercontent.com/41164406/77099494-6b332880-69ea-11ea-887e-2a7edbf2c005.png)

## Background/context/resources

Current Field Name and Copy Reads

![image](https://user-images.githubusercontent.com/41164406/76882913-b239e600-6851-11ea-8331-8c85f60ff631.png)

## Technical notes
n/a

**Comment by jcq** [comment]
@msj0nes Do these changes apply to the judge ("Address Motion to Vacate") view as well? Currently that has the same field label and help text.

**Comment by msj0nes** [comment]
@jcq It applies to the Judge as well. Please see additional changes as well where the 'Caseflow Reader' is hyperlinked. This is in the event Litigation Support provides the wrong URL the VLJ can easily access the vets claims folder.
