### ISSUE TITLE
Special Issues Page: Add Validation

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13735]
## User or job story
Job story: When an attorney or judge clicks continue on the special issues page, and a special issue is not chosen, they need to see an error message noting a selection needs to be made on the page.   

## Acceptance criteria
- [ ] add error if no issue is selected "Choose at least one. If no special issues apply to this case, please confirm by selecting “No special issues” (Legacy Only)
- [ ] Please put this work behind the feature toggle: `:special_issues_revamp`
- [ ] This feature should be accessible to the following user groups: judges & attorneys
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: training documentation to be updated

### Designs

Legacy: Error message if no option chosen
![Legacy Appeals_Special Issues_error if no option chosen](https://user-images.githubusercontent.com/59883609/76991291-b3d1df80-691f-11ea-8500-d94e38adc752.png)

### Background/context
We are adding a "no special issues" option on the special issues page so validation will need to occur on the page to ensure a selection is being made. 

### Resources/other links
#13396

**Comment by yoomlam** [comment]
@araposo-tistatech 
> We are adding a "no special issues" option on the special issues page
Which ticket is this? Looking at the Legacy checkout screenshot, has a designer reviewed the placement of "No Special Issues"?

**Comment by araposo-tistatech** [comment]
@yoomlam I've had @carodew review the designs and the board has already agreed this is the approach they would like to take design wise. You are correct, I forgot to add the No Special Issues button to the following tickets: 

#13396 
#13736 

Adding now.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||||||
3 | 
5 | 
8 | 
```

Reminder: remove "(Optional)" from heading happening in an earlier ticket.
Recommended: Update FE and BE, if its easily doable.

Why 1?

Why 2?k
- Update tests
- FE only?
- Simple frontend validation

Why 3?

Why 5?

**Comment by yoomlam** [comment]
Actual error banner now looks like this:
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/55255674/77482633-66a8ae80-6df4-11ea-8d28-991939f38793.png">

**Comment by araposo-tistatech** [comment]
@yoomlam updated the AC to reflect legacy only and removed the AMA mockup from the design area.
