### ISSUE TITLE
VHA ODS tables

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13733]
## Description

VHA has reporting needs similar to those of VBA. These include tables:

* HIGHER_LEVEL_REVIEWS: Intake data for Higher level Reviews
* SUPPLEMENTAL CLAIMS: Intake data for Supplemental Claims
* APPEALS: Used to keep track of information for AMA appeals
* DECISION_ISSUES: Issue-level dispositions for AMA claims/appeals
* REMAND_REASONS: Remand reason for decision issues.

In order to make it simple for VHA to pull the data they need, we need a new ODS table `vha_decision_reviews` that is scoped to those Decision Reviews (Appeal, HLR, SC) that have an associated benefit type corresponding to VHA.

## Acceptance criteria

* [x] New `vha_decision_reviews` ODS table with composite schema matching HLR, SC and Appeal.
* [ ] Add `remand_reasons` ODS table
* [x] `ETL::VHADecisionReview` model and syncer added to builder job

## Technical notes

Easiest way to identify VHA-related decision reviews is via the BusinessLine to task association. See #13075 for example.

- [x] Verify that nonrating lines of business that map to VHA are included (does benefit type always == LoB) verified via https://github.com/department-of-veterans-affairs/dsva-vacols/issues/77

**Comment by pkarman** [comment]
in production just now:
```
irb(main):006:0> ETL::VhaDecisionReview.count
[2020-05-15 11:46:36 -0400]    (1.6ms)  SELECT COUNT(*) FROM "vha_decision_reviews"
=> 764
```

**Comment by yoomlam** [comment]
For comparison:
```
irb(main):003:0> HigherLevelReview.processed.where(benefit_type: "vha").count
=> 260
irb(main):004:0> SupplementalClaim.processed.where(benefit_type: "vha").count
=> 367
irb(main):006:0> vha_appeal_ids=RequestIssue.select(:decision_review_id).where(benefit_type: "vha", decision_review_type: :Appeal)
irb(main):007:0> Appeal.established.where(id: vha_appeal_ids).count
=> 137
irb(main):008:0> 260+367+137
=> 764
```

**Comment by pkarman** [comment]
Email sent to stakeholders, scheduling time to review.
