### ISSUE TITLE
Intake | Do not allow removing contentions with exam scheduled

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13738]
## Description
When a contention has an exam scheduled, we should prevent the user from removing the contention.

## Acceptance criteria
- [x] Add data to the request issue serializer that includes whether the request issue contention has an exam scheduled
  - [x] Incorporate the new BGS service (see tech notes), and check if origSourceTypeCd has a value of "EXAM"
- [x] If the contention has an exam scheduled, hide the "Remove" action for the request issue
- [x] Place a note below the request issue saying that it has an exam scheduled, and it cannot be removed
> Copy:  A medical exam is requested. Issues cannot be removed.
- [x] Add the new BGS service to the BGSService fakes

## Background/context/resources
When a contention has an exam scheduled, removing it is destructive. If a user wants to remove it, they should first remove the exam in VBMS before removing the contention via Caseflow.

## Technical notes
Sandra implemented the new BGS service in #13488
RequestIssue.contention gets the contention from the end product establishment's list of contentions, because from VBMS we can only fetch a list based on the claim_id.  We still need the VBMS version of the contention for other interactions, such as updating or removing.

RequestIssueContention is a model for interacting with these contentions.

One approach may be to add the BGS contentions to the EPE as well, and start to differentiate between VBMS and BGS contentions. Another may be just to add it to RequestIssueContention, and finding all of the contentions for the claim and matching it ther.e

**Comment by rutvigupta-design** [comment]
I can help with copy design, if needed!

**Comment by leikkisa** [comment]
![Screen Shot 2020-05-18 at 9.04.38 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/bd129dc4-2f9b-4046-aba5-dc7c36e27d0e)

**Comment by msj0nes** [comment]
# Update

AMO stakeholder is requesting a demo of this work.
