### ISSUE TITLE
AMA: Add Special Issues Page

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13736]
## User or job story
User story: As a attorney and or/judge, I need to be able to flag the following special issues on AMA cases, so that the data can be captured for reporting purposes:
- Burn Pit
- Military Sexual Trauma (MST)
- Blue Water
- US Court of Appeals for Veterans Claims (CAVC)

A "No Special Issues" checkbox needs to be added as a selection must be made on this page. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `:special_issues_revamp`
- [ ] This feature should be accessible to the following user groups: Attorneys & Judges
- [ ]  Attorneys are able to select the above new special issues that apply to a case during the AMA workflow before submitting the case to a judge
- [ ]  Attorneys are able to select the "No Special Issues" checkbox if no issues apply to the case during the AMA workflow before submitting the case to a judge
- [ ]  Judges are able to edit/add special issues (including the "No Special Issues" checkbox) during the AMA workflow that attorneys identify apply to a case before submitting the case to dispatch
- [ ] Update documentation: Need to update training documentation
- [ ] No other special issues should appear for AMA cases other than the ones listed above

### Designs

**UPDATE The below mockup is outdated. Please move the "No Special Issues" checkbox above "Issues On Appeal"**

![AMA Appeals_Special Issues_mockup](https://user-images.githubusercontent.com/59883609/76992473-b46b7580-6921-11ea-9271-b54910ef05c7.png)

AMA: Error message if no option chosen
![AMA Appeals_Special Issues_mockup_error if no option chosen](https://user-images.githubusercontent.com/59883609/76992781-1fb54780-6922-11ea-88ed-94f7ccc5c2f9.png)

### Background/context
The goal of this project is to provide the Board for the Board of Veterans’ Appeals the ability to flag/mark Blue Water along with MST, Burn PIT, and CAVC contentions in Caseflow for data capture purposes only.

### Technical notes
This data is needed for reporting purposes in Tableau so both engineering teams will need to synch to ensure the data we are providing is in the format they are requiring.

Tracking specialty appeals like this was common practice in VACOLS for legacy appeals, see image below. The Board is likely looking for something similar that would be completed by an attorney at the time they close their writing task and send their appeal to their judge for review.

### Resources/other links
[Product Brief](https://docs.google.com/document/d/15izpJwUTYP7yE0SHrdLP1tsGmbLGdIOqpEOHDyLwqDo/edit#)

**Comment by yoomlam** [comment]
Related to #13396

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||
5 | |||||||
8 | 
```

Needs to _create_ a page for special issues on AMA.
And include it in the checkout workflow.
Create tests for new page and workflow.
Update the model and DB.
Think about how we could update this in the future to have issues live on their own model?

Why 1?

Why 2?

Why 3?
- Borrow a lot from #13396

Why 5?
- Adding an entire page into judge and attorney checkout flow
- Will need to fix existing feature tests that don't expect this page to show up
- May need to update how the special issue controller and page function 
- Schema updates

**Comment by yoomlam** [comment]
@araposo-tistatech I ran into [this piece of code](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/task_action_repository.rb#L326), which is relevant when attorneys click on "Decision ready for review". When an appeal's `stream_type` is `vacate` (aka motion-to-vacate or MTV), the line of code causes the user to go to `motion_to_vacate_checkout/review_vacatures` instead of the typical `draft_decision/dispositions`. This ticket will cause the user to go to `dispatch_decision/special_issues` before going to `draft_decision/dispositions`. My question is does this ticket affect the behavior of MTV appeal streams? In other words, should the Special Issues page be shown for an appeal stream that is marked as MTV?

**Comment by yoomlam** [comment]
@araposo-tistatech @geronimoramos Is this layout acceptable? It's closer to the view for legacy appeals but different from the mockup in the ticket description.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/55255674/79257655-8fe6b880-7e4f-11ea-9605-7dd4ff735cd7.png">

**Comment by yoomlam** [comment]
This pop-up appears when clicking "Cancel" during the checkout process.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/55255674/79280079-1497fd80-7e75-11ea-9a04-f1190c4df1cc.png">

It needs to be updated to something like: "All changes made to this page will be lost, except for the selection of special issues and the adding, editing, and deleting of issues."

@geronimoramos Does this copy look acceptable?

**Comment by geronimoramos** [comment]
> @araposo-tistatech @geronimoramos Is this layout acceptable? It's closer to the view for legacy appeals but different from the mockup in the ticket description.
> <img alt="image" width="935" src="https://user-images.githubusercontent.com/55255674/79257655-8fe6b880-7e4f-11ea-9605-7dd4ff735cd7.png">
> 
> With error msg:
> <img alt="image" width="1038" src="https://user-images.githubusercontent.com/55255674/79257852-d805db00-7e4f-11ea-8d19-ed28e17c882a.png">

I lean more towards placing the Issues on Appeal on the left side below the No Special Issues. It makes sense to have it in similar formatting to legacy but It helps to eliminate double columns when possible especially for form design and form controls.

**Comment by yoomlam** [comment]
@araposo-tistatech @geronimoramos 
During Dispatch for legacy appeals, the pages look like this (note that the 4 new special issues are appended to the end, not alphabetized): https://github.com/department-of-veterans-affairs/caseflow/issues/13396#issuecomment-608580299

Should the dispatch page for AMA appeals only have the 4 new special issues plus "No special issues"? In what order?

**Comment by araposo-tistatech** [comment]
Does Dispatch currently have a special issues page for AMA appeals? 

- If it does, then we will just want to add the 4 new issues and "No Special Issues" checkbox. 

- If it does not, then we will only have the 4 new special issues plus "No special issues."

**Comment by yoomlam** [comment]
What I understand at this point (which was conveyed to @araposo-tistatech):
- For Legacy appeals, the Dispatch user works on one case/claim at a time to dispatch the appeal. The Special Issues page is shown during this process. There's no indication in the URL or the UI (without opening devtools) of which appeal is being worked besides the Vet's name and file number.
- For AMA appeals, the Dispatch user can mark their BvaDispatchTask as complete. There is no action that would show a Special Issues page that I can tell. After marking the task complete, the RootTask is still on_hold and there are no open tasks -- what needs to happen to the appeal at this point to close it?

More research is needed to define the desired Dispatch workflow for AMA appeals, so changes to Dispatch will be in a separate ticket.

**Comment by yoomlam** [comment]
User | Before | After
------------------|----------|--------
Attorney | no Special Issues page | <img width="1121" alt="image" src="https://user-images.githubusercontent.com/55255674/79394736-cf8bce00-7f3d-11ea-99a1-cc139c0f8567.png"> |
Judge | no Special Issues page | <img width="1047" alt="image" src="https://user-images.githubusercontent.com/55255674/79394783-e7fbe880-7f3d-11ea-91f7-955361afed3f.png"> |
