### ISSUE TITLE
Do not show VLJ or Attorney for cancelled appeal in case details

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13747]
### Description
When appeals are cancelled, we should not display the judge or attorney that worked on this case in the case title.

![Screen Shot 2020-03-19 at 11 15 52 AM](https://user-images.githubusercontent.com/45575454/77083630-32885480-69d4-11ea-9857-359cbb617f8a.png)

### AC
- [ ] Judge that worked on case is not shown ic case details when the appeal has been cancelled
- [ ] Attorney that worked on case is not shown ic case details when the appeal has been cancelled

### Steps to reproduce
1. Log in as BVAAABSHIRE
2. Cancel all tasks on an appeal with a JudgeDecisionReviewTask assigned to the user
```ruby
user = User.find(3)
appeal = FactoryBot.create(:appeal, :at_judge_review, associated_judge: User.find(3), associated_attorney: User.find(1))
appeal.tasks.open.update_all(status: Constants.TASK_STATUSES.cancelled)
appeal.uuid
=> "405ea3cb-cf69-412e-b550-05bdb2ff38f8"
```
3. Go to the case details screen of this case /queue/appeals/405ea3cb-cf69-412e-b550-05bdb2ff38f8
4. VLJ field is still populated with the judge's name

### Notes
We currently do not display these for cases where every issue has been removed. 
https://github.com/department-of-veterans-affairs/caseflow/blob/0ec98c06bdf3d76d2059f4e94c858b90d3c12eb9/client/app/queue/CaseTitleDetails.jsx#L235
https://github.com/department-of-veterans-affairs/caseflow/blob/0ec98c06bdf3d76d2059f4e94c858b90d3c12eb9/client/app/queue/CaseTitleDetails.jsx#L240
After we add logic to serialize the status in #13654, we can check if the appeal is cancelled here as well.

Users will still be able to see case timeline to see who worked on these cancelled appeals.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||
2 | ||||||
3 | 
5 | 
8 | 
```


Why 1?
 - Should be able to add appeal.status !== "cancelled" in two places

Why 2?
- because FE
- Could create a helper function like `removed?` to be reused in other places now that we're building out cancelled appeal handling on the front end
