### ISSUE TITLE
Sync up permissions for creating a team and modifying a team

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13748]
As found in #13616, BVA admins can [create teams](https://github.com/department-of-veterans-affairs/caseflow/blob/0de710af8150e3f96893efb102f7aded8e14be31/app/controllers/team_management_controller.rb#L4) but they cannot properly [view or modify members of those teams]( https://github.com/department-of-veterans-affairs/caseflow/blob/4f9db9108334a090775f1b4d682665e0c76c55c2/app/controllers/organizations/users_controller.rb#L46) unless they are a [system admin](https://github.com/department-of-veterans-affairs/caseflow/blob/60e89d8252167b59f1a929f9fc2a1a2ecce90b74/app/models/user.rb#L200).

We should discuss with BVA stakeholers about whether or not these permissions are correct. If these are correct and BVA team admins should be able to create new teams, but not modify them, we should not allow them to view an individual org's team management page.
[Confirmed incorrect](https://github.com/department-of-veterans-affairs/caseflow/issues/13748#issuecomment-611701938)

## AC new permissions
- [ ] BVA Admins can
  - [ ] View individual team management pages
  - [ ] Add and remove users
  - [ ] Modify admin rights

**Comment by yoomlam** [comment]
@araposo-tistatech Hit up the Board for a decision on action item.

**Comment by araposo-tistatech** [comment]
Confirmed with the Board, they do not need the ability to modify members of judge teams. They only need to create them.

**Comment by yoomlam** [comment]
Currently, user needs to be System Admin or an org admin to add users to orgs and only the JudgeTeam org has an org admin set.

**Comment by araposo-tistatech** [comment]
Got some clarity! 

We should update the BVA Admin permission set to include creating and viewing teams, as well as, modifying members of those teams. 

The Board has also requested we remove J. White from the BVA admin list.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||
2 | |||||||||
3 | 
5 | 
8 | 
```

Update 2 validations/permissions. See links in description.

Once deployed, have user remove J. White themselves.

Why 1?
- Only 2 locations in the code to update permissions/validation

Why 2?
- Gotta be careful opening up perms
- Add or update specs

**Comment by hschallhorn** [comment]
Should be able to just update this line to include BVA users https://github.com/department-of-veterans-affairs/caseflow/blob/c2a96844a0c8ac2f6fbd7fb771ce381cad6dd7f4/app/models/user.rb#L110
