### ISSUE TITLE
[Flaky Test] UserInfoController.represented_organizations

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13756]
## Background/context/resources

 - Circle CI Error:  [UserInfoController.represented_organizations](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/28802/workflows/4cf3be33-66b4-463f-85b5-d62c0a07fa59/jobs/106353/parallel-runs/4?filterBy=FAILED)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by ajspotts** [comment]
Closing as this was already reported in this [issue](https://github.com/department-of-veterans-affairs/caseflow/issues/13646)
