### ISSUE TITLE
Allow admin to add Veteran to past hearing day

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13750]
## User or job story
User story: As a Hearing Coordinator admin, I need the ability to add a Veteran's appeal to a past docket, so that Veterans who had a hearing are tracked in Caseflow.

## Acceptance criteria
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Technical notes
This might include task types

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-811
