### ISSUE TITLE
Update character limit on hearing Notes field

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#13755]
### Description
Increase the character limit on the hearing Notes field that appears on Daily Docket and Hearing Details pages to 1000 characters.

### Background / context
The hearing Notes field currently has a character limit of 100. Hearing Coordinators have reported in a [design review](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Caseflow%20Projects/Hearings/Telehearings/hearing-coordinator-sessions/hearing-coordinator-session-2020-03-13.md) and in virtual hearings [pilot testing](https://app.mural.co/t/workqueue2001/m/workqueue2001/1584544597569/1176cfc2ece78cefa6ec12a2db52a85deb078541) that this is a pain point because:
1. The field allows input of more than 100 characters and provides no feedback that the limit has been exceeded until the content is clipped on save
2. Hearing Coordinators often need to enter more than 100 characters to provide Judges and each other with important context

_Current state screenshot of content clipped to 100 characters after save_
![hearingNotes_characterLimit.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/768e715a-c6a8-4ffc-8c2d-38f67183a430)

### Acceptance criteria
- [ ] Increase **legacy** hearing notes field to hold 1000 characters; notes are [cropped in HearingMapper#notes_to_vacols_format](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/mappers/hearing_mapper.rb#L88-L93) before they're [used to update the VACOLS hearing record](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/hearing_repository.rb#L34-L37).
- [ ] add a count below the notes field showing how many characters have been entered. _(note: technically, the limit is 1000 bytes; is it possible to do a byte count?)_
- [ ] if the character count reaches 1000, don't allow any further input.
- [ ] update the equivalent `notes1` field in VACOLS for FACOLS in [vacols_copy_2_tables_test.sql](https://github.com/department-of-veterans-affairs/caseflow/blob/master/local/vacols/vacols_copy_2_tables_test.sql#L558) and [vacols_copy_2_tables_dev.sql](https://github.com/department-of-veterans-affairs/caseflow/blob/master/local/vacols/vacols_copy_2_tables_dev.sql#L558); once this change is made and in production, a new version of FACOLS will have to be built. See [this slack thread](https://dsva.slack.com/archives/C2ZAMLK88/p1584556155184000) and [this PR](https://github.com/department-of-veterans-affairs/caseflow/pull/13760) for guidance.

#### Open questions
- The hearing Notes field content appears on the print version of the Daily Docket. How does that affect our approach?
  - We will allow the full note to display on the print version of the Daily Docket.
- Is there a limitation that VACOLS enforces on character count?
  - Yes, and the limitation was mirrored in Caseflow in [HearingRepository#transform_hearing_info](https://github.com/department-of-veterans-affairs/caseflow/pull/2717/files#diff-d6588a709c75c9919e903a69dd86e51eR20) in July 2017.
  **- The limitation has been lifted 7/16/20. The field is now 1000 characters.**

#### Out of scope
  - Prevent users from entering content that exceeds the character limit (no error / warning displayed; no clipping content on print version)
  - Display an error / warning when the character limit has been reached (can be done in addition to the above)
  - Display the character count (can be done in addition to the above)

**Comment by chandracarney** [comment]
@nicholer I emailed Jed about this and he has said the following 🥳 ```We can increase the size of the HEARSCHED.NOTES1 field in VACOLS. It’s currently 100 characters just let me know how big they would like it.```

I seem to recall a request for 500 and a request for 250, perhaps. Do you recall?

**Comment by chandracarney** [comment]
Email from Jed after requesting an increase: `The HEARSCHED.NOTES1 field is now 1000 characters in the VACOLS Dev and Prod databases.`
