### ISSUE TITLE
Documents List | Read/unread indicator: only bold the "Document Type"

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1377]
**Context**
Currently, if a document has not yet been opened in Caseflow, we bold the entire row on the Documents List; however, we received some feedback that it was a bit overwhelming to users, and it was sometimes confused for communicating importance.

**Description**
Bold only the name of the "Document Type" for each unread document.

## Acceptance Criteria
- Validate that any document on the Documents List page that has not yet been opened by the user has its "Document Type" name displayed in bold
- Validate that after clicking on an unread "Document Type" link and returning to the Documents List page, the Document Type is no longer bolded 

<img width="664" alt="screen shot 2017-03-30 at 9 35 38 am" src="https://cloud.githubusercontent.com/assets/4042181/24506682/4e9372a4-152c-11e7-8207-d324175548a9.png">

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

**Comment by mdbenjam** [comment]
This is already fixed.

**Comment by kierachell** [comment]
**PASSED**
![readdoc](https://cloud.githubusercontent.com/assets/18075411/25193660/d7ec3e80-2505-11e7-818e-e31d7b2d33f3.gif)
