### ISSUE TITLE
CM: Allow CM Team to Expedite Cases with Blocking Tasks (Front end) 

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13780]
## User or job story
User story: As a CM team member, I need the ability to cancel blocking tasks (policy permitting), so I can advance cases to a VLJ. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: scm_move_with_blocking_tasks
- [ ] This feature should be accessible to the following user groups: CM Team Members
- CM team members can:
  - [ ] send request to backend to advance a case to a VLJ with blocking tasks that are only blocking dispatch
  - [ ] send request to backend to cancel "blocking tasks" to advance a case to a VLJ 
  - [ ] see info advising which tasks will need to be canceled and which ones cannot. 
  - [ ] see info requesting the reason for the cancellation should include radio button with list for (Dismissal, Withdrawals) 
  - [ ] see an assignment drop down to assign the case to a VLJ
  - [ ] see a confirmation modal for the cancellation & reassignment of the case
  - [ ] open link to email client for user the task is assigned to 
- [ ] Case Timeline is updated noting all task cancellations and assignment to a judge (all should show which CM team user performed the action) as well as include the reason for the cancellation (provided in the cancellation modal). 

## Release notes
Case Movement Users now have the ability to cancel tasks blocking distribution and expedite cases to VLJs . 

## Design/Copy
https://www.figma.com/proto/KrRlTBObGlAUlD78TtAS8N/Case-Movement?node-id=0%3A1&scaling=min-zoom

Technical Notes: 
Implementation for cancellation logic [here](https://github.com/department-of-veterans-affairs/caseflow/issues/14260)

**Comment by araposo-tistatech** [comment]
@hschallhorn when you have a moment can you review this one before I send it to @geronimoramos ? I'm not sure if the Boards logic of the blocking tasks is currently the case in the system. If not, I can create a new ticket for any updates that are needed.

**Comment by geronimoramos** [comment]
![image.png](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/a3432c3c-f542-4050-acd5-11c7d7622cfc)
If it's more critical, we can also use the modal with the warning icon in the heading. Let me know your feedback!

**Comment by araposo-tistatech** [comment]
@geronimoramos this looks good, I do like the addition of the warning icon. I wonder if we can add a list of the blocking task or tasks to the modal itself or would that be too much copy to have in a modal. 

@hschallhorn are all of the blocking tasks listed in the active tasks list or case timeline (I know we limit some of the information in the case timeline) ? If so, then we may not need to add them to the confirmation modal.

**Comment by hschallhorn** [comment]
They should be displayed in the active task list. I am a smidge confused about this though. What should happen to these tasks when the case is "moved"? Can we added the consequences of moving the case to the copy as well?

**Comment by araposo-tistatech** [comment]
@hschallhorn cc: @geronimoramos per the Board, it would be helpful to be able to cancel all tasks if needed. Cancelling tasks could be completed with a safeguard function, like having the Board user click yes or no on each task they are cancelling to be sure they know exactly what they're doing and agree with it before cancelling." 

By "safeguard" John means some sort of confirmation modal. 

I do want to note that tasks that are flagged as "Blocking for Dispatch Only" should not have the ability to be canceled as most have legal implications. They should continue to be active and assigned to the team working the case even after the case is moved (please let me know if this is not clear and further discussion is needed.)

**Comment by geronimoramos** [comment]
@araposo-tistatech do we want to create another user story and/or ticket for deleting blocking tasks?

>  I wonder if we can add a list of the blocking task or tasks to the modal itself or would that be too much copy to have in a modal.
It's no problem we can add more information, it just depends on how much more information we want to include in the modal. It can potentially be a 2-3 step modal to cancel the blocking tasks _potentially_. 

More questions/ideas around that:

1. I imagine we want to notify the users with the active task that it was canceled by a Case Movement user? Including context from CM users such as 'This case is being moved for X reason'
2. If we want to cancel multiple blocking tasks, it may be worthwhile to explore creating a full page rather than a modal.

**Comment by araposo-tistatech** [comment]
@geronimoramos 

1. I imagine we want to notify the users with the active task that it was canceled by a Case Movement user? Including context from CM users such as 'This case is being moved for X reason' - I agree if I'm not mistaken we display cancelled tasks in Case Timeline. Do we want something a bit more visible? 

2. If we want to cancel multiple blocking tasks, it may be worthwhile to explore creating a full page rather than a modal. We do want to cancel each one of the blocking tasks so yes, we may want it to be a full page instead of a modal. 

Also, I agree we should create a separate ticket for canceling blocking tasks.

**Comment by araposo-tistatech** [comment]
@RyanRoyUX leaving a note here, the Board is requiring that all tasks (that are not blocking for dispatch only tasks) be canceled before the case can be moved.

**Comment by araposo-tistatech** [comment]
@RyanRoyUX can we update the designs on this ticket?

**Comment by RyanRoyUX** [comment]
Here is a link to the Figma. Will this work? @araposo-tistatech 
https://www.figma.com/file/KrRlTBObGlAUlD78TtAS8N/Case-Movement?node-id=0%3A1
This is a link to the Prototype too (Same questions as ^)
https://www.figma.com/proto/KrRlTBObGlAUlD78TtAS8N/Case-Movement?node-id=0%3A1&scaling=min-zoom

Also we should put in the ticket the info about making updates to the timeline.

**Comment by araposo-tistatech** [comment]
@lomky do you think I should break out the Case Timeline updates? Not sure what that work looks like for the Engineering team.

**Comment by lomky** [comment]
I think that its fine here - the task will appear in the timeline by default, we're just clarifying the requirements on it

**Comment by yoomlam** [comment]
Be consistent with `canceled` and `cancelled`. Both are present in the mock up.
Also `cancelation` looks odd but seems to be an acceptable.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||
5 | ||||||||||
8 | 
```

#### Why 3?
* AC very well laid out so ask is very understandable

#### Why 5?
* New front end view, along with new frontend tests
* Need to pull all tasks that are blocking an appeal, along with assignee and email
