### ISSUE TITLE
Trigger receipt of completed IHPs (judge/attorney notification)

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13800]
Ticket related to [#14909](https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/14909)

## User story
As a judge or attorney I need to be able to see a notification or indicator when an IHP task is completed so that I know I can proceed with reviewing and processing the case. 

## Problem statement
Per the Board, they do not know when an IHP task is completed in Caseflow. 

## What is out of scope?
There should be no need to change task assignments. The request here is just for a notification. 

## Background/context
IHPs are documents that are filled out by VSOs that include additional information related to veteran's case. 
When a veteran has received assistance from VSO to process their appeal, an IHP is added to the case. 
At this time VSOs will either complete IHP tasks soon after a veteran has used their services, or they will receive an IHP tasks from a judge or an attorney for a Veterans case when it is being reviewed by a judge/attorney. 

Once the task is marked as completed there is no notification or indication in Caseflow shown to the Board members (attorneys & judges) causing delays in case movement.

## What are the unknowns?
Are cases with open IHP tasks put in the "On-Hold" page in judge/attorney queues and then moved out to "Assigned" once completed? Yes, they do. 

Could the "Days Waiting" field be some sort of indicator?

## For research tickets only: What questions do we hope to answer? What are our learning goals?
How often are completed IHP tasks overlooked?
How long of a delay is there between the completion of the IHP task and the attorney or judge picking the case back up? 
Is there any reason why they would not want to see an alert or indicator for completed IHP tasks? (ex. there is another blocking task against the case so the case cannot be worked in any case)
Is there any data we can pull that can possibly decrease the priority of this request? For example, if we find attorneys are picking up these appeals within days of the IHP task being completed is a "notification" really going to make a significant impact? 

## Existing design and content
[Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1595518321333/a3929ce45595dca9177fe2adfd3cb3d6e3203fbd) of research and flows 
[Link to designs](https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=0%3A1) in Figma

## Success criteria
IHP task is created when attorney/judge requests IHP from VSO. 
A child IHP task is automatically created for VLJ support when a judge/attorney requests an IHP task from a VSO. 
Child IHP task is automatically put on hold. 
Child IHP task is completed by VLJ support when VSO completes IHP, is uploaded into V drive and VLJ support reviews. 
Attorney/judge receives notification and can clearly see when an IHP task is completed in their queue.

**Comment by geronimoramos** [comment]
This is super interesting! Conceptually, `Notifications` don't exist (yet) in Caseflow and would change the product/design system considerably cc @carodew

**Comment by carodew** [comment]
@geronimoramos this could be an opportunity to go back and explore/iterate on the 'inbox' concept that team Echo worked on this past fall, unfortunately we didn't have design capacity at that time to provide them with direct support. We have a number of areas in Caseflow where there are things that happen in the background (either an async system task or a process done by someone else), so it may be worth exploring if the 'inbox' pattern would work for this (or not! I honestly do not have a strong opinion). The 'hold' queue could also be an area to explore.

**Comment by carodew** [comment]
The Intake Inbox pattern may be relevant here as well as for FNOD: https://github.com/department-of-veterans-affairs/caseflow/issues/11907

**Comment by ryanroyroy** [comment]
![image](https://user-images.githubusercontent.com/6116023/91901875-d312be00-ec6e-11ea-8fa2-2d41e62fa3a9.png)

**Comment by araposo-tistatech** [comment]
This user story has been split into two (#15404 & 15405), closing.
