### ISSUE TITLE
Intake | COVID-19 Update | Add COVID-19 timeliness exemption checkbox for HLRs

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13809]
## User or job story
User story: As a VBA user (claims assistant, VSR), I need to be able to capture if a timeliness exemption requested by the veteran was related to COVID-19

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [covid_timeliness_exemption]
- [ ] The timeliness exemption modal shows an additional checkbox above the notes (after the user selects "Yes" to indicate that an exemption has been requested)
- [ ] The checkbox value is saved in the database as a boolean on the request issue table
- [ ] Update: This AC has been removed: ~The checkbox only appears for higher level reviews~
- [ ] Include screenshot(s) in the Github issue
- [ ] Update documentation: [Request issue eligibility requirements](https://github.com/department-of-veterans-affairs/caseflow/wiki/Request-issue-eligibility-requirements)

## Release notes
If a veteran requests a timeliness exemption that is related to COVID-19, that is captured when adding the issue so that the data is available for reporting.

### Designs & Copy
![COVID - Checkbox.jpg](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/5c6a75aa-915a-4be9-8332-fe4b8791b12c)

### Background/context
This is being added to facilitate more reliable reporting on whether timeliness exemptions are related to COVID-19. In addition, we may use this to adjust the [eligibility requirements for legacy issue opt-ins](https://github.com/department-of-veterans-affairs/caseflow/wiki/Legacy-issue-opt-in-eligibility-requirements).

### Technical notes
The untimeliness exemption modal component is here:
`caseflow/client/app/intake/components/UntimelyExemptionModal.jsx`

**Comment by rutvigupta-design** [comment]
@jcq here is a design: 
![COVID Extension Modal](https://user-images.githubusercontent.com/51714306/77785355-0f8c1f00-702a-11ea-8692-e141dd7c2c2f.jpg)

**Comment by msj0nes** [comment]
# Tracker 
 
. |Research | Design |  Development | Pilot | Release
-- | -- | -- | -- | -- | -- 
Add COVID-19 timeliness exemption checkbox for HLRs|  :white_circle: |  :white_circle: |  :white_circle: |  :white_circle: |  :white_circle: 		
	


**Key:**	Not Started- ⚪️  In Progress 🚧   Complete -  ✅.  Blocked-🔴

**Comment by jcq** [comment]
## Screenshot of Updated View
<img width="833" alt="Screen Shot 2020-04-01 at 09 07 21" src="https://user-images.githubusercontent.com/2581274/78160140-631ab600-73f8-11ea-8271-288e7600380f.png">
