### ISSUE TITLE
Attorney Fees | Select an available attorney as the claimant

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13806]
## User or job story
As a BVA Intake user, I need the ability to select an available attorney as the claimant in the Intake workflow

## Acceptance criteria 
>Pending design confirmation
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### **[Designs](https://github.com/department-of-veterans-affairs/caseflow/issues/13775)**

![image](https://user-images.githubusercontent.com/41164406/80404729-99304600-888f-11ea-8536-98fd9675bb2e.png)
![image](https://user-images.githubusercontent.com/41164406/80404760-a77e6200-888f-11ea-8520-112e3caac40d.png)

### Background/context
The Board considers the 'Attorney' as the claimant and in order to process this specific claim would require the ability to select/enter the attorney's name. In most cases the attorney is no longer working with the veteran and is therefore not associated to the veteran in VBMS. This means the ability to retrieve attorney information would need to be sourced. Allowing free text would surface issues associated to data integrity.

**Comment by leikkisa** [comment]
@nanotone I think this might be a dupe also - can you confirm?

**Comment by leikkisa** [comment]
Closing this ticket as a dupe
