### ISSUE TITLE
Investigate virtual hearing conference rooms not being cleaned up

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13845]
## Description
The Pexip conference rooms are sticking around in the interface. The job to cleanup the rooms is attempting to run but may not be properly configured.

## Acceptance criteria
- [ ] Update documentation: [link]

## Background/context/resources
https://dsva.slack.com/archives/C3EAF3Q15/p1584716098443500?thread_ts=1584713571.442100
https://dsva.slack.com/archives/C3EAF3Q15/p1584714611442500?thread_ts=1584713571.442100

## Technical notes
[2020-03-19 22:30:58 -0400] Failed to delete conference from Pexip with error: (401) No error message

**Comment by ferristseng** [comment]
The status code indicates an unauthorized exception, which matches with the credentials issue we were seeing in UAT. I'm going to close this, since the credentials issue is now resolved.
