### ISSUE TITLE
Queue Org | Create new 'Case Review' team and copy permissions | Update Original 'Case Review' team name to 'Intake' team

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13865]
## Description
BVA Intake team requires a Queue based team to properly segment functionality in Caseflow. With work requested by BVA to restrict [non-BVA users from starting Board Appeals (NOD)](https://github.com/department-of-veterans-affairs/caseflow/issues/13356) we've noted that their associated teams in Queue require an update before proceeding with the restriction needed. This will ease complexity and potential engineering confusion in the future. 

An Intake team needs to be created in Queue, however team 'Case Review' has backend identifier 'BVAIntake'. To prevent any confusion this may lead to when 'Intake team' is created ~its best to use the team already created with backend identifier 'BVAIntake'.~ this mismatch should be corrected

~A new team should be created for Case Review, where their old permissions are transferred and Intake functionality removed from BVA Mail team. Case Review is allowed to correct issues, remove/withdraw issues.~
A new team should be created for BVA Intake.

## Acceptance criteria
- [ ] The Case Review team exists without reference to any "BVA Intake' names
  - Case Review team members & org permissions are maintained
  - Case Review tasks are maintained
- [ ] Create a BVA Intake team

**Comment by hschallhorn** [comment]
Break this into 2 PRs. 
1. Rename `BvaIntake` model to `CaseReview`
2. Create new BvaIntake team

_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||||||
5 | ||
8 | 
```

Why 3?
 - Unsure if renaming BvaIntake will have any unforseen issues
 - Need to verify and double-check impacts of changes

Why 5?
 - Lots of searches, thorough validating of the state of code, updating docs
 - possible complications around FE-BE communication with name-changing

**Comment by msj0nes** [comment]
@hschallhorn  This looks like it may be a heavy lift. 

If there is a way to reduce the echo effort by creating the 'Intake' team and finding a model name for it that would make clear the differences and engineering believes the model names wont be confusing, I'm open to any easier path you find.

**Comment by lomky** [comment]
@msj0nes I updated the AC to be agnostic to method; please confirm I haven't lost any details?

The old AC, for record:
```

- [ ] A new 'Case Review' team is created
  - [ ] Permissions and functionality of from original 'Case Review' team is transferred to the newly created 'Case Review' team (`can_withdraw_issues?` and [can edit issues](https://github.com/department-of-veterans-affairs/caseflow/blob/cddd5d7730f0225a8e7cb7d1ddb2f10cbf94cd04/app/policies/appeal_request_issues_policy.rb#L18))
  - [ ] The newly created 'Case Review' team has an appropriate backend identifier 'bva_case_review' or similar
  - [ ] Users from `BvaIntake` are moved to `CaseReview`
  - [ ] Tasks assigned to `BvaIntake` are moved to `CaseReview`
- [ ] Name of original 'Case Review' team is changed to 'Intake' team
```

**Comment by msj0nes** [comment]
@lomky looks good!

**Comment by lomky** [comment]
Awaiting resolution of https://github.com/department-of-veterans-affairs/dsva-vacols/issues/116 before this can continue.

Merge Plan:
