### ISSUE TITLE
Motion to Vacate | Include draft hyperlink for all vacate types

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13861]
## User or job story
User story: As a Motions Attorney, I should be able to include a link to a draft document for all vacate types (deny, dismiss, and granted).

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] When a Motions Attorney is making a recommendation for a motion to vacate, they see a text box for entering the draft hyperlink for all vacate types (granted, denied, dismissed)
- [ ] The hyperlink shows up in the instructions to the judge for all vacate types
- [ ] The title for the hyperlink text box is updated to "Relevant documents"
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [Motions to Vacate](https://github.com/department-of-veterans-affairs/caseflow/wiki/Motions-to-Vacate)

### Out of scope
- Adding "Return to Motions Attorney" to all vacate types

### Designs
New title copy for textbox: Relevant documents

### Background/context
This ticket is being created as a result of a demo to stakeholders on March 30, 2020. [See Google Doc with findings](https://docs.google.com/document/d/1w-3MhdJMtGwz9DBEhQC8vgbbgbNHA-Bz_FWqVpMV1pQ/edit#).

**Comment by jcq** [comment]
@leikkisa @rutvigupta-design 
Do we want this to be a simple multiline text field (`TextareaField` component)? Or do you want to have a UI that has them add them one-by-one, maybe specifying the name/type of the document separately from the hyperlink? Obviously the former is easier, but just wanted to check. Are we still OK with simply outputting the contents as part of the larger instructions, or will something change in terms of formatting for that?

**Comment by rutvigupta-design** [comment]
@jcq @leikkisa I am exploring designs for this (the URL title copy, whether we should have any help text to guide users, and whether it should be a multiline text field) but this is blocked right now since we need confirmation from BVA that they can set up shared folders.

**Comment by rutvigupta-design** [comment]
Please find the design prototype for adding an unlimited number of hyperlinks for a **denial/dismissal** 
[here](https://www.figma.com/file/VtOG0hibbyJ6T5UcYnn5EP/Motions-to-Vacate_Phase-II_Epic-8547?node-id=494%3A35). This will be the same for dismissals with the exception of replacing "denial" with "dismissal"

**Note: Copy for the VLJs notes in progress.** 

### Designed screens: 
1. Motions attorney has fields for a denial/dismissal draft and the motion file and can add a hyperlink using the "add hyperlink" button
![URL-1](https://user-images.githubusercontent.com/51714306/78702057-9adc9e80-78cd-11ea-82f3-93dba5e883e1.jpg)

2. A modal pops up and the Motions attorney enters the type and hyperlink to the document
![URL-2](https://user-images.githubusercontent.com/51714306/78702149-c3649880-78cd-11ea-9631-f06513bf5fe4.jpg)

3. Once the Motions Attorney has filled out the fields, their save button becomes active
![URL-3](https://user-images.githubusercontent.com/51714306/78702223-df683a00-78cd-11ea-974e-de7f7a4b472d.jpg)

4. The label (type of the document) and the field (hyperlink) gets added and can be removed. Note: for now, this cannot be edited. 
![URL-4](https://user-images.githubusercontent.com/51714306/78702351-10486f00-78ce-11ea-9928-1498a8e38b89.jpg)

**Comment by rutvigupta-design** [comment]
Here is the design for granted (full and partial) motions. The key difference for these is the **removal of the draft hyperlink field**. Adding a hyperlink follows the same pattern as denials/dismissals. 
![URL - grant](https://user-images.githubusercontent.com/51714306/78703424-bcd72080-78cf-11ea-8bc8-778a53a37a05.jpg)

**Comment by rutvigupta-design** [comment]
### Motion Attorney's notes format

Here is the hyperlink to the draft of the motion: 
_[hyperlink]_

Here is the hyperlink to the draft of the denial/dismissal:
_[hyperlink]_

Here is the hyperlink to the [document type name]:
_[hyperlink]_

**Comment by jcq** [comment]
@rutvigupta-design I think the design of the modal varies a bit from others... Typically the titles aren't centered and there isn't a divider line between the title and the main contents. Should I work to implement those changes (I could do it here w/o affecting other modals)? FWIW, I like your design better. :)

**Comment by rutvigupta-design** [comment]
@jcq thanks for catching that! I re-purposed a modal to design with from Intake and didn't realize it's different from the others. 

For the sake of consistency, let's keep this modal the same as others (i.e. without the divider line and the title left-aligned).

**Comment by leikkisa** [comment]
@rutvigupta-design Since the design doesn't show "optional", does that mean the hyperlinks are required (for the pre-defined ones)?

**Comment by rutvigupta-design** [comment]
@leikkisa SMEs at the demo mentioned making it required - I will verify on Monday, but I think for now, we should make them required. I think overall, having fewer reasons for a judge to need to return the task to Litigation Support is better.

**Comment by jcq** [comment]
@leikkisa @msj0nes From demo feedback, did we settle on all hyperlink fields being optional? That'd be the only remaining code change that would need to be made here, I think.

**Comment by leikkisa** [comment]
@jcq I am sorry to be going back and forth on this particular requirement.  I'm seeing @rutvigupta-design 's previous comment that we wanted it to be required.  Since there is conflicting information on this requirement now, I feel that it's safer to move forward with Rutvi's suggestion, and get more confirmation before doing the extra work to change it.

**Comment by jcq** [comment]
Added [new ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/14036) regarding possibly making the hyperlink fields optional
