### ISSUE TITLE
Motion to Vacate | Allow partial grant option for Motions Attorneys

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13864]
## User or job story
User story: As a motions attorney, I would like to be able to select the "partial grant" recommendation and have that information be available to the judge.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] Motions attorneys have a radio field for "Grant partial vacatur" when selecting a recommendation to send to the judge
  - [ ] Show same help text as judge address motion to vacate task
  - [ ] Do not show issues for selection, just the radio button
- [ ] The partial grant selection is indicated in the instructions to the judge
- [ ] Remove "required" labels from fields in the Motion to Vacate flow (not related to this specific request, but a small adder from dogfooding)
- [ ] Double check that code doesn't have the word "vacature" (with an e) anywhere
- [ ] Include screenshot(s) in the Github issue
- [ ] Update documentation: [Motions to Vacate](https://github.com/department-of-veterans-affairs/caseflow/wiki/Motions-to-Vacate)

### Background/context
This ticket is being created as a result of a demo to stakeholders on March 30, 2020. [See Google Doc with findings](https://docs.google.com/document/d/1w-3MhdJMtGwz9DBEhQC8vgbbgbNHA-Bz_FWqVpMV1pQ/edit#).

### User Facing Changes
<img width="668" alt="Screen Shot 2020-04-09 at 15 27 24" src="https://user-images.githubusercontent.com/282869/78933253-09a92b80-7a77-11ea-876a-fc0d847ce64c.png">

**Comment by leikkisa** [comment]
@rutvigupta-design I don't think this needs any copy or design, but just tagging you in case there's a need to update instructions or anything for the partial grant option.

**Comment by leikkisa** [comment]
Adding a blocked label, it sounds like we're going to wait from approval from BVA before moving forward on this ticket.

**Comment by msj0nes** [comment]
@rutvigupta-design  we'll put this ticket on hold until you get the opportunity to confirm with BVA that this is ok. Just update the ticket once you receive news on this.

**Comment by rutvigupta-design** [comment]
@leikkisa there are two design requirements: 
1. Adding a radio button on the Motion Attorney's page that says "Grant partial vacatur" with help text: "e.g. if you do not want to vacate all the issues the veteran is requesting"
2. When the judge receives their task, the first sentence in the instructions should say "I recommend granting a partial vacatur" for partial grants and "I recommend granting a vacatur" for full grants. 

@msj0nes can you please clarify what feedback we need from BVA? My understanding was that they just wanted the option to select a partial grant.

**Comment by msj0nes** [comment]
@rutvigupta-design commented on wrong ticket, the hold is for https://github.com/department-of-veterans-affairs/caseflow/issues/13862. It's fine to complete this work.
