### ISSUE TITLE
Refactor how VirtualHearingModal is shown

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13869]
## Description

Connected to #13662

Low priority, just a style change to make declaring modals cleaner in the component file.

  - Interesting pattens for handling modal show/hide:
     ```jsx
    <Modal show={show} onHide={handleClose}>
    ```

## Acceptance criteria

Confirm no changes to UI

**Comment by chandracarney** [comment]
Moving out of the current sprint to be addressed by Caseflow-wide refactoring and/or larger front-end working group.
