### ISSUE TITLE
Remove VBMS eDocument v4 requests

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#1388]
As we move forward with the VBMS eFolder v1, we should remove eDocument v4 requests.

Tech details:
1. Look for `FeatureToggle.enabled?(:vbms_efolder_service_v1)`
2. Remove the following calls: 
* VBMS::Requests::ListDocuments
* VBMS::Requests::FetchDocumentById
* VBMS::Requests::UploadDocumentWithAssociations

**Comment by laurjpeterson** [comment]
@aroltsch - is this ticket still relevant?

**Comment by aroltsch** [comment]
It is done.
