### ISSUE TITLE
Determine Veteran's Timezone from Address

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13889]
## Description

For #13804, we need to determine the timezone a veteran is in from their address because the hearing location for central office hearings will always be the same (timezone EST). Because the location is always the same, we won't be able to tell the veteran what time their hearing is in in a user-friendly way.

## Acceptance criteria

- [ ] Get the timezone for an address in US + territories
- [ ] Get the timezone for an address in the Philippines 
- [ ] Get the timezone for an address in a foreign location

## Background/context/resources

Slack conversation: https://dsva.slack.com/archives/C3EAF3Q15/p1585770263131600

Technical options conversation: https://dsva.slack.com/archives/C2ZAMLK88/p1585925436093100

## Technical notes

Possible options: https://github.com/department-of-veterans-affairs/caseflow/issues/13804#issuecomment-608080181

**Comment by ferristseng** [comment]
Research Findings

- We have veterans with foreign addresses (Taiwan, Australia, Columbia, etc.)
- We have veterans with addresses in U.S. territories (Guam, etc.)
- Lots of zip codes (some are 3 digits?)

From these research findings, I think the best approach to automate this would be to do a lat/long lookup. If the address can't be validated, then maybe the TZ could be manually inputted?

**Comment by chandracarney** [comment]
Documenting on the story that we've gotten the go-ahead for [this method](https://dsva.slack.com/archives/C3EAF3Q15/p1586449741282000) of determining the Veteran's timezone from DVC McLeod to unblock us and move quickly on the Central Office and virtual docket use cases.
