### ISSUE TITLE
Create a UI for BVA admins to reassign all tasks of an inactive user

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13909]
When A BVA admin marks a user inactive, they should also be able to trigger the reassignment of all the user's tasks. We currently have a [rake job](https://github.com/department-of-veterans-affairs/caseflow/blob/689164e647ac2508ea2e17761a7e0f4fa3848fe7/lib/tasks/tasks.rake#L152) to do this.

### AC
- [ ] When a user is marked inactive by an admin, an alert shows that they still have tasks assigned to them
- [ ] When an admin searches for a user that is inactive, an alert shows that they still have tasks assigned to them
- [ ] The admin can initiate the reassignment of all these tasks
- [ ] The confirmation modal displays what will happen to all of the tasks (where they will be reassigned to, could leverage the dry run for this)
- [ ] This cannot be performed if the attorneys of the judge's old judge team have not been placed on a new judge team
- [ ] Any other errors are correctly displayed and are actionable

**Comment by geronimoramos** [comment]
This one is challenging. Do we want this alert to work in conjunction with letting the admin know they have to assign the attorneys to a new judge team?

But I see first that the attorneys need to be assigned a judge team before this action can be performed 🤔
**Questions**
> When an admin searches for a user that is inactive, an alert shows that they still have tasks assigned to them

Where is this view happening from? 

> The admin can initiate the reassignment of all these tasks

Will it always be all the tasks or sometimes just some of the tasks?

**Comment by hschallhorn** [comment]
> reassign tasks from the inactive user to an active one

We currently have a function that reassigns all tasks based on a number of conditionals, not necessarily to a specific user. Other than that, 1, 2, 3 look right!

> Where is this view happening from? Search results page, case details, queue? 🤷

The user management page. Log in as TEAM ADMIN and navigate to /user_management

> Will it always be all the tasks or sometimes just some of the tasks?

Alllll the tasks
