### ISSUE TITLE
"Correct Issues" link not loading page correctly

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#13904]
## Description
When logged in as BVAKHADDOCK, navigating to the Case Details page for the appeal with `id: 30847` (`uuid: "146563a9-b88f-405d-bf80-d2c4eb979651"`), and clicking the "Correct issues" link, the page does not load. 

During the course of the investigation of [this](https://dsva.slack.com/archives/CHX8FMP28/p1585233702022400) support issue, it was determined that the `legacyIssue` function in `issues.js` was not correctly returning all of the legacy appeals referenced by the `RequestIssues` causing the `No legacyAppeal found for '${issue.vacolsId}` error to return.

The `legacyAppeals` argument passed in to the `legacyIssue` function [here](https://github.com/department-of-veterans-affairs/caseflow/blob/c98e1c52db30ce0b6cca2a208ea9ca4e27eab9e8/client/app/intake/util/issues.js#L46) is passed down through props from addIssues.jsx [here](https://github.com/department-of-veterans-affairs/caseflow/blob/c98e1c52db30ce0b6cca2a208ea9ca4e27eab9e8/client/app/intake/pages/addIssues.jsx#L414).  For some reason, this is not returning all of the legacyAppeals associated with the RequestIssues as it should be.

## Acceptance criteria
- [ ] "Correct Issues" link for the problematic appeal (with `id: 30847`) should load

## Background/context/resources
The problem was discovered over the course of the investigation of this support issue: 
https://dsva.slack.com/archives/CHX8FMP28/p1585233702022400

**Comment by yoomlam** [comment]
See https://github.com/department-of-veterans-affairs/caseflow/issues/13900#issuecomment-610068930 for the appeal that's causing this problem.
