### ISSUE TITLE
Styleguide component: Change buttons to sentence case

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1390]
**Description**
Buttons displayed in Caseflow Commons buttons should reflect our own pattern for button text capitalization -- sentence case.

**Current State**
<img width="159" alt="screen shot 2017-03-30 at 2 06 05 pm" src="https://cloud.githubusercontent.com/assets/4042181/24519125/2e9fdab6-1552-11e7-8393-9918033e7524.png">

**Expected**
[Sentence case]

## Acceptance Criteria
- Verify that if a button does not contain any titles/proper nouns, the copy on the text displays in sentence case (first word capitalized, the rest are lowercase)
- Verify that if a button contains a title or proper noun, only the first word on the button and those proper nouns are capitalized 
- Verify that if a button contains only one word, that word is capitalized

**Comment by gnakm** [comment]
@mmlumba Could you make this change in our buttons in the style guide?

**Comment by mmlumba** [comment]
I actually did this in a recent PR, so I'm moving this ticket to "In Validation"

**Comment by kierachell** [comment]
**PASSED**
<img width="969" alt="screen shot 2017-04-03 at 8 57 29 am" src="https://cloud.githubusercontent.com/assets/18075411/24610178/96615732-184b-11e7-83fe-ff444b96bf8f.png">
