### ISSUE TITLE
"Correct Issues" not appearing in AMA case for BVA Intake user

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#13900]
## Description
BVA Intake user `BVAASANTIAGO` does not see "Correct Issues" option for an AMA appeal.  According to support a BVA Intake user should always have this appeal on AMA cases regardless of where in the workflow the appeal currently is or which user it is currently assigned to.  This is how the case currently appears to the user: 
<img width="838" alt="Screen Shot 2020-04-06 at 2 30 32 PM" src="https://user-images.githubusercontent.com/18618189/78592550-4248cb00-7813-11ea-8374-2d4f28b5ccca.png">
## Acceptance criteria
- [ ] appeal should correctly display "Correct Issues" like it does below:
<img width="926" alt="Screen Shot 2020-04-06 at 2 30 16 PM" src="https://user-images.githubusercontent.com/18618189/78592592-54c30480-7813-11ea-8b12-640e2e52e9e8.png">

## Background 
https://dsva.slack.com/archives/CHX8FMP28/p1585233702022400

**Comment by yoomlam** [comment]
As stated in https://dsva.slack.com/archives/CHX8FMP28/p1586208275220100?thread_ts=1585233702.022400&cid=CHX8FMP28:

> According to Caseflow's code, a BVA Intake user can only see the "Correct issues" link if the case has yet to be assigned to an attorney (i.e., an AttorneyTask has not been created). This case is currently assigned to BVAKHADDOCK and an AttorneyTask was created:
```
Appeal 30847 (direct_review)     STATUS    ASGN_TO
└── RootTask                     on_hold   Bva
    ├── DistributionTask         completed Bva
    ├── JudgeAssignTask          completed BVAKHADDOCK
    └── JudgeDecisionReviewTask  assigned  BVAKHADDOCK
        └── AttorneyTask         completed BVASMISHA
```

When logged in as BVAKHADDOCK and clicking the "Correct issues" link, the page does not load. Upon [further investigation](https://dsva.slack.com/archives/CJL810329/p1586209772228800), the appeal's `RequestIssue`s refer to legacy appeals:
`appeal.request_issues.map(&:vacols_id) =>  ["3966878", "3966358", "3966358", "3966358"]`. A new ticket was created for Intake to handle: #13904.

**Comment by yoomlam** [comment]
Closing due to [Martina's comment](https://dsva.slack.com/archives/CHX8FMP28/p1586208891221300?thread_ts=1585233702.022400&cid=CHX8FMP28): 

> I'll review with the business if this should stay as is. Shalanda Boykins for now lets alert the user that current Caseflow functionality does not allow for the editing of issues when the case is currently assigned to another user. Let them know they can contact the user in possession to discuss edits required. If there are additional questions or concern let him know to reach out to me
