### ISSUE TITLE
Handle bad css_id when navigating to a judge assign queue

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13911]
As of #13433, when an invalid css_id is used in /queue/<css_id>/assign, the error is not handled.

Correct css_id
![Screen Shot 2020-04-07 at 12 02 33 PM](https://user-images.githubusercontent.com/45575454/78692321-b2b12400-78c7-11ea-87e8-561eef4f7965.png)
Bad css_id
![Screen Shot 2020-04-07 at 12 03 01 PM](https://user-images.githubusercontent.com/45575454/78692350-c2306d00-78c7-11ea-84d5-b0737539d373.png)
```json
// 20200420142400
// http://localhost:3000/queue/BVAAAAAAAABSHIRE/assign

{
  "errors": [
    {
      "status": 400,
      "title": "\"BVAAAAAAAABSHIRE\" is not a valid CSS_ID or user ID",
      "detail": "\"BVAAAAAAAABSHIRE\" is not a valid CSS_ID or user ID"
    }
  ]
}
```

This should instead redirect to our normal 404 page

### AC
- [ ] When the user navigates to an assign queue that does not exist, we should redirect them to our 404 page

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | ||||||||||
3 | 
5 | 
8 | 
```

Why 1?
- Seems straightforward

Why 2?
- I dunno how!
- Assuming I can ask someone how this is done. (fail ActiveRecord::NotFound)

**Comment by yoomlam** [comment]
Should also check https://www.caseflowdemo.com/queue/appeals.
See https://dsva.slack.com/archives/CJL810329/p1587406296458100

**Comment by hschallhorn** [comment]
This is causing a sentry alert as well https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9927/

**Comment by yoomlam** [comment]
Using `ActiveRecord::RecordNotFound` shows this:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/55255674/81010012-415b8700-8e1b-11ea-885f-2b515b35026d.png">

**Comment by yoomlam** [comment]
BEFORE|AFTER
 ---|---
![Screen Shot 2020-04-07 at 12 03 01 PM](https://user-images.githubusercontent.com/45575454/78692350-c2306d00-78c7-11ea-84d5-b0737539d373.png) | <img width="1083" alt="image" src="https://user-images.githubusercontent.com/55255674/81010593-1cb3df00-8e1c-11ea-840a-f9177ee63210.png">
