### ISSUE TITLE
Motion to Vacate | Admin Actions in De Novo flow

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13918]
## User or job story
User story: As a decisions attorney, I would like to be able to add admin actions to a De Novo vacate stream during the decision review flow, instead of from the Case Details page.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [review_motion_to_vacate]
- [ ] On a De Novo Vacate stream, the decisions attorney navigates to an Add Admin Action page after adding decisions, and before submitting the draft to the judge
- [ ] The navigation bar at the top of the De Novo flow indicates the third step
- [ ] The backend creation of adding admin actions occurs when the flow is completed and the draft decision is submitted.
- [ ] Include screenshot(s) in the Github issue
- [ ] Update documentation: [Motions to Vacate](https://github.com/department-of-veterans-affairs/caseflow/wiki/Motions-to-Vacate)

### Designs
![Screen Shot 2020-04-07 at 12.30.13 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/e8b473a0-77fa-4af7-80a3-f510b000e9f2)

### Technical notes

This could probably be broken up into a front end and back end ticket, but it would impact the ability to use the MTV flow in demo or UAT.

The header and submit button text are different than the existing component. The existing component also adds the admin actions upon hitting submit.  When talking to Rutvi, we think the admin actions should get created when the workflow is completed, in case the attorney doesn't finish and re-starts, at least as the first default approach.

- See `AddColocatedTaskView.jsx` to see the current component for adding admin actions.
- See [JC's PR for setting up the container component for the MTV checkout workflow](https://github.com/department-of-veterans-affairs/caseflow/pull/13334/files)

### Resources/other links
[Mural with designs for De Novo flow](https://app.mural.co/t/workqueue2001/m/workqueue2001/1578666564868/a1b0322baefbcc9386858a828e6ab2c071b1a794)

**Comment by jcq** [comment]
@leikkisa 

The behavior in `AddColocatedTaskView` creates new tasks on the given appeal, with the current user's task as the parent task (unless `task.isLegacy` is true). Unless I'm mistaken, that would put the current user's task on hold until the admin actions are completed. 

The description of this implies that we want to submit these admin actions at the same time as the user (attorney) completes their task; in this scenario, what should be the parent task of the admin actions? The current (attorney) task, or the judge task that would be created after the submission?

**Comment by leikkisa** [comment]
@jcq I couldn't find another example in the code where admin actions get added partially through a task.  This is what I'd like to propose:

- set assigned_by to the attorney adding the admin action
- set the colocated org task parent to the JudgeDecisionReviewTask (which would already be on hold).
- double check that the JudgeDecisionReviewTask is still on_hold after completing the AttorneyTask, and that the admin actions(s) are assigned or assignable by the organization.

Even though this is a little bit different, I haven't thought of downsides or things that it would break.

I think this is a better option than having it attached to the AttorneyTask from within the current De Novo design.  They can still do that from the task action menu though.

**Comment by jcq** [comment]
@leikkisa 

I've got things pretty well set up as we wanted (with it set to add admin actions under judge task), but have hit a snag. 

Best I can tell, these two inherent aspects of tasks are causing us trouble:
- A given user can't post to `/tasks` endpoint to create child tasks on a parent to which they don't have access — this means that we get an error when the attorney tries to add admin action tasks as children of the `JudgeDecisionReviewTask`
- A particular task can't have children added to it if it is already complete — this prevents us from adding admin actions to the `AttorneyTask` after the attorney checkout flow is complete

So, it seems that we will need to get around this one of a couple of ways:
- Alter the logic in `SubmitDecisionView` and `QueueFlowPage` to allow for a "beforeSubmit" hook to save the admin actions as children of the attorney task before it completes
  - Unclear if we can actually complete a task that has open children — this would cause the attorney checkout to fail, which... defeats the purpose
- Create another endpoint to use for submission that completes the checkout and creates the new admin actions as children of `JudgeDecisionReviewTask`
  - This should work, but I hate the idea of creating a single-purpose endpoint if it can be avoided
- Something else that is more elegant...?

I'm inclined to solicit advice from Echo to see what might make the most sense...

**Comment by leikkisa** [comment]
@jcq Ooh, the plot thickens.  It doesn't make sense to add them to the AttorneyTask and then to complete the attorney task. I think that creates the risk of them not being completed before the judge checkout flow, since that flow would no longer be waiting for the colocated tasks to be completed before proceeding.

I do think it's a good idea to ask Echo on their opinions, since this flow is a departure from how things are designed now (admin actions not normally happening in the middle of completing a task).

It's probably a good idea to re-evaluate the overall design as well. The problem that this requirement is trying to solve is that the attorneys often forget to add admin actions. There may be other options for addressing this - for example suggesting in the beginning of the Attorney Task flow that they add admin actions first instead of mid-flow, and if they do to put the attorney task on hold until those are complete.  Let's check in with @msj0nes on that.

Let's explore other options before creating another endpoint. Can you also point me to the code where it doesn't allow task permissions on the parent?

**Comment by leikkisa** [comment]
After looking at the code, I think an alternative solution could be to modify `verify_user_can_create!` on ColocatedTask to account for this scenario (attorney creating a colocated task on a judge task on a de novo stream).

**Comment by jcq** [comment]
## Update Screenshots
<img width="978" alt="Screen Shot 2020-05-01 at 14 19 38" src="https://user-images.githubusercontent.com/2581274/80842624-efb2c280-8bb6-11ea-8209-926d38fe800d.png">
