### ISSUE TITLE
Make /queue/<css_id>/assign the default url to reach a judge's assign page

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13913]
In an effort to give judge assign queues human readable urls, we should make these urls the default url for these pages.

### AC
- [ ] When a judge navigates to their assign page from their dropdown, the url uses their css_id
- [ ] When a judge navigates to their assign page using their user id, the url is updated to use their css_id
- [ ] When clicking around the judge assign queue, the URL should not change to use the users id

### Current issues
Incorrect URL
![Screen Shot 2020-04-07 at 12 16 17 PM](https://user-images.githubusercontent.com/45575454/78693743-ad54d900-78c9-11ea-999e-c606e3b43acf.png)
Non updated URL
![Screen Shot 2020-04-07 at 12 17 26 PM](https://user-images.githubusercontent.com/45575454/78693867-d5dcd300-78c9-11ea-83dd-ef8dd78cf4fb.png)
Incorrect change of URL
![ezgif-3-b06003fbb7f9](https://user-images.githubusercontent.com/45575454/78694045-176d7e00-78ca-11ea-8afc-aeda9ab1d607.gif)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||
3 | |||||||
5 | |
8 | 
```

Why 2?
- Can replicate some logic that was implemented in the original PR

Why 3?
- unfamiliar with React routing
- Updates in various places in the code to hit all AC, could be broken out into smaller PRs

Why 5?
- General uncertainty

**Comment by yoomlam** [comment]
Related to #13433
