### ISSUE TITLE
Do not use assigned_to_location to sort and filter by assignee in org queues

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13914]
When implementing back end sorting and filtering by assignee in #11780 for pagination, we noticed our [front end did not](https://github.com/department-of-veterans-affairs/caseflow/pull/11780/files#r314458380) sort or filter with the simple task assignee value. We opted to [match what the front end currently did and fix this later](https://dsva.slack.com/archives/CJL810329/p1565898494290900?thread_ts=1565893728.282400&cid=CJL810329). This is the ticket to fix this!

### AC
 - [ ] Back end sorts and filters based on the name (name for organization and full_name for user) of the assignee of the task

### VLJ support comments
> 1. Appeals are showing in the VLJ Support queue that are assigned to users who are not part of VLJ Support (ex.  484b4e52-1e05-4a81-890c-3408892265fc is assigned to Tecola Plowden, but is showing in VLJ Support’s queue).  While this is also assigned to another user who is part of VLJ Support, they are only able to see that it is assigned to Tecola Plowden). Maria wants the VLJ Support queue to only show tasks that are assigned to her employees so she can provide an accurate accounting of all tasks to her DVC.
> 1. Why are tasks showing as assigned to “VLJ Support” and not an individual user?  Maria mentioned that some tasks in VLJ Support’s queue are shown as assigned to “VLJ Support” when they are in fact assigned to an individual user.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | ||||||
5 | |||||
8 | 
```

Why 2?
- Implementing a more straightfoward approach and undoing the existing

Why 3?
- No new caching code
- Can replicate some of the sorting and filtering logic for the assigneR of tasks

Why 5?
- Undoing a lot of code in caching
- Touching the database

**Comment by hschallhorn** [comment]
@geronimoramos or @RyanRoyUX Right now we're using a gross method to display who the assignee of a task is that hardly has anything to do with the task. This could show a vacols location (sometimes a number), an organization's name, a user's css_id, and for some reason a user's database id.
![Screen Shot 2020-05-12 at 6 23 56 PM](https://user-images.githubusercontent.com/45575454/81751645-d7c42400-947d-11ea-89d3-102092bb0339.png)


In this ticket, we're moving to showing the actual assignee of a task (either an organization or a user) and am wondering what value to display
1. I think name makes the most sense for tasks that are assigned to an organization ("Litigation Support", "Privacy Team", etc)
1. User is a bit more complicated. We could keep using css_id or switch to full name or even "F. Last". May want to keep space in mind, css_ids are usually a set length and pretty small.
    1. If switching to full name or "F. Last", should we sort on the user's first or last name?

Thoughts?

**Comment by hschallhorn** [comment]
Looks like we sort our assigneR column by their last name

**Comment by hschallhorn** [comment]
@RyanRoyUX and @geronimoramos repinging on this. Here's what this would look like with full names as written in #14264
 - [ ] Queues show the name of the user assignee, rather than a mix of user id or css_id?

![Screen Shot 2020-05-12 at 8 56 16 PM](https://user-images.githubusercontent.com/45575454/81759679-5bd4d680-9493-11ea-9bd3-e41a3fc6ebba.png)

**Comment by geronimoramos** [comment]
@hschallhorn CSS ID makes a lot of sense to me especially if it is maintaining consistency - much better than a VACOLs location. I also like the idea of displaying an organization like Lit Support since reaching out to a team lead is more the norm than an individual contributor team member. But happy to experiment with CSS ID first! I don't see any challenges with it.

**Comment by hschallhorn** [comment]
@araposo-tistatech This fix is in and should be out in next deployment. Can we check in with VLJ support to see if this solves their qualms with the "Assigned to" column in their queue?

### User Facing Changes
 - [x] Queues show the actual assignees of each task (no one assignee for all tasks for one case)

 BEFORE|AFTER
 ---|---
![Screen Shot 2020-05-12 at 8 53 39 PM](https://user-images.githubusercontent.com/45575454/81759614-2d56fb80-9493-11ea-9969-35b8a5ba09ff.png)|![Screen Shot 2020-05-12 at 8 52 41 PM](https://user-images.githubusercontent.com/45575454/81759607-292ade00-9493-11ea-984e-54edd4265aa5.png)

 - [x] Queues show the css_id of the user assignee, rather than a mix of user id or css_id?

 BEFORE|AFTER
 ---|---
![Screen Shot 2020-05-12 at 8 55 59 PM](https://user-images.githubusercontent.com/45575454/81759681-5e373080-9493-11ea-958b-b6e9e79e773e.png)|<img width="973" alt="Screen Shot 2020-05-15 at 1 25 39 PM" src="https://user-images.githubusercontent.com/45575454/82078744-a7fc6280-96af-11ea-9e70-a0897a1dd51a.png">



 - [x] Queues do not show "Case Storage" unless they are actually assigned to BVA

 BEFORE|AFTER
 ---|---
![Screen Shot 2020-05-12 at 9 00 31 PM](https://user-images.githubusercontent.com/45575454/81759811-b66e3280-9493-11ea-8e1c-737a69757bb8.png)|<img width="1024" alt="Screen Shot 2020-05-15 at 5 02 39 PM" src="https://user-images.githubusercontent.com/45575454/82095870-ebfe6000-96cd-11ea-8c1d-a0355f150698.png">

**Comment by araposo-tistatech** [comment]
@hschallhorn VLJ Support confirmed this looks good.
