### ISSUE TITLE
Handle mixed case css_ids when navigating to a judge's assign queue

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13912]
As of #13433, when a mixed case css_id is used in /queue/<css_id>/assign, we claim the css_id is incorrect. Instead, we should upcase all requests to find the right user and fix the URL to display correctly

Correct css_id
![Screen Shot 2020-04-07 at 12 02 33 PM](https://user-images.githubusercontent.com/45575454/78693038-b2fdef00-78c8-11ea-8966-f4a6634c595d.png)

Mixed Case css_id
![Screen Shot 2020-04-07 at 12 10 28 PM](https://user-images.githubusercontent.com/45575454/78693103-c7da8280-78c8-11ea-9ab7-2c80029aa8c7.png)
```json
// 20200420142307
// http://localhost:3000/queue/BVAAAbshire/assign

{
  "errors": [
    {
      "status": 400,
      "title": "\"BVAAAbshire\" is not a valid CSS_ID or user ID",
      "detail": "\"BVAAAbshire\" is not a valid CSS_ID or user ID"
    }
  ]
}
```

### AC
- [ ] When a user provides an incorrectly cased css_id, the URL is updated to the all caps css_id
- [ ] When a user provides an incorrectly cased css_id, the back end returns the correct user for the upcased css_id

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||||||
2 | |
3 | 
5 | 
8 | 
```

Why 1?
- javascript must have an `upcase`, right?

Why 2?
- Do we want the back end to be able to accept mixed case as well? (by upcasing the provided param)

**Comment by yoomlam** [comment]
Can't simply upcase the CSS_ID and redirect, as that would cause an infinite redirect loop. The redirect must be conditioned on whether the CSS_ID needs upcasing.

**Comment by yoomlam** [comment]
Definitely more than 1 story point. Two possible implementation options: see https://github.com/department-of-veterans-affairs/caseflow/pull/14064#issuecomment-618037946.
