### ISSUE TITLE
Designs needed for CM Team to view Judge's Assign Queue from their own queue

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13924]
## User story
As a CM user I should have the ability to view a judges assign queue from my own queue without having to modify the URL in Caseflow. 

## Problem statement
Development has been completed to give CM Team members the ability to see all Judge assign queues, currently to navigate to the judges assign queue, the CM team member has to modify the URL using the users CSS ID. Per the Board, this is not optimal as the may not know the users CSS ID. They've requested we have an identifiable way in Caseflow UI to get to a judges queue. 

## What is out of scope?
Should not include any work after the CM user lands on the judges assign queue. 

## What are the unknowns?
The Board has suggested a drop down list with all the judges, but this list will be extensive and may not be the best option in this case. 

Once designs are mocked up we will want to gain approval from stakeholders before moving into development. 

## Success criteria
Looking for a user experience that will allow the CM user to quickly locate a judge and route to their assign queue. 

## New designs and prototype
[Prototype link
](https://www.figma.com/proto/wfzTzSl4yg6vzitkIoXfCr/SCM-Team-to-view-Judge-s-Assign-Queue?node-id=1%3A3&viewport=-1083%2C623%2C0.5255597829818726&scaling=min-zoom
)

**Comment by geronimoramos** [comment]
Questions coming up:

- If they tend to not know the CSS IDs, do they know the judge's name that they're looking for?
     - What are the current ways they are identifying which Judge queue they need to navigate to? Mostly CSS ID, name, etc.?
- And to be more specific, the problem is not to view Judge's queue in their own queue, but to better navigate to a judge's queue rather than modifying the URL? Does that sound more correct?

**Comment by geronimoramos** [comment]
Quick mockup of SCM team UI:

1. Go to switch views and click 'Go to judge queue'
2. Modal pop-ups to go to judge queue
3. Searchable dropdown to find judge by name or CSS ID -- considered that there may be MANY judge names but I liken it to selecting your country when filling out forms

![gotojudgequeue.gif](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/16eaf692-0f30-4e49-8c77-7b83a5a67eec)
