### ISSUE TITLE
Intake | ITF | VBMS reflects updated status of an existing ITF from "Active" to "Claim Received" with Caseflow EP 040 establishment

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13921]
## User or job story
User story:  As a VBA Caseflow Intake user, VBMS should reflect an updated status of an existing ITF from "Active" to "Claim Received" whenever Caseflow establishes a EP 040 with claim label  “_Supplemental Claim Rating >year_"

## Acceptance criteria
- [ ] In VBMS, the existing ITF status changes from "Active" to "Claim Received" when Caseflow establishes a EP 040 with claim label  “_Supplemental Claim Rating >year_"

### Background/context
For supplemental claims that are received within a year of the initial decision, the effective date of the claim is the same as the effective date of the prior decision.  Thus, the application of Intent to File (ITF) to supplemental claims received within a year is not necessary, as it does not benefit the Veteran (the Veteran's effective date is earlier under AMA/supplemental claim rules than it would be under the ITF rules).  However, if a claim is received more than a year after the prior decision was issued, Veterans benefit from the ITF process, as it provides an earlier effective date.  There is a Business need for the system to recognize when VA receives a supplemental claim that is outside of the one-year window from the prior decision, so an EP 040 with a claim label “Supplemental Claim Rating >year" can be applied to that claim and provide notice to the user that there could be an applicable ITF associated to the claim.  Additionally, when this EP 040 with a claim label “Supplemental Claim Rating >year” is established, and a pending ITF exists for that Veteran, the status of the pending ITF associated to that Veteran should be automatically updated from "Active" to "Claim Received"

### Resources/other links
[Capability to Support ITF for Supplemental Claims](https://github.com/department-of-veterans-affairs/caseflow/issues/13248)

**Comment by msj0nes** [comment]
# Status
🔴  - Blocked 

 Pending the completion of [story](https://github.com/department-of-veterans-affairs/caseflow/issues/13647), we can assess whether VBMS needs anything outside of the EP code transmitted to automatically change the status of ITF.  This work will be address in the testing phase of this [story](https://github.com/department-of-veterans-affairs/caseflow/issues/13647)

**Comment by leikkisa** [comment]
Just a note that this isn't for Caseflow engineering, it's more of a "test" ticket, after #13647 is completed, we'd want to test with VBMS.
