### ISSUE TITLE
Clarify language when the last issue is removed on a case

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13925]
## User story
As a user when I remove the last issue on a case I should clearly see a message stating removing the last issue will cancel all tasks and withdraw the case.  

Current language displaying is not clear. 

## Problem statement
Users are mistakenly canceling tasks and withdrawing cases in Caseflow. 

## Background/context
Often times users want to correct issues on a case. Mentally, they want to work from a clean slate and then add the issues they want, but with Caseflow design, you must add what you need first, then delete the what you don't need. 

## New design
![image](https://user-images.githubusercontent.com/49766982/78947488-56423600-7a7a-11ea-97b5-add17b75ab13.png)

## Existing design and content
When an issue has been removed and it was the last issue: 
![image](https://user-images.githubusercontent.com/59883609/78809611-3127c780-7995-11ea-8f56-400bba7ea3ac.png)

## Success criteria
Users clearly understanding removing the last issue on a case will withdraw the appeal and cancel all tasks. 

Decline in Batteam issues related to mistakenly withdrawing cases.

**Comment by yoomlam** [comment]
Should emphasize in the popup that case will be closed and removed from their active queue. They will no longer be able to modify or reopen the case.

**Comment by geronimoramos** [comment]
Made some mockups here, will reach out for feedback.
![image](https://user-images.githubusercontent.com/49766982/78941973-90f1a180-7a6d-11ea-9ce4-68ed000731c6.png)
V1 = normal copy change
v2= copy change with warning icon

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||
2 | |||||
3 | 
5 | 
8 | 
```

Change layout to account for warning icon

Why 1?
- Simple update to copy and addition of an icon

Why 2?
- might have some feature tests to update? a bit of pessimism
- :sparkles: CSS :sparkles:
