### ISSUE TITLE
Give indication of a task with a completed hold in a user's assigned tab

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13929]
Previously, a user was able to see tasks that had an expired or completed hold in their assigned tab, as shown with a red styling. This logic for a completed hold is as follows https://github.com/department-of-veterans-affairs/caseflow/blob/502058571a5d398f413592dfa3e737c2d9ae6515/client/app/queue/utils.js#L536-L543

However, since we began using `TimedHoldTask`s to place another task on hold, the on hold duration for a task looks at the on hold duration of an [_active_ `TimedHoldTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/761e76a628fb5b5a2ea322755d51133d8e33ffe8/app/models/task.rb#L324). We should instead look at the most recently created `TimedHoldTask`, closed or otherwise to determine the on hold duration of a parent task.

### AC
- [ ] A tasks calculated on hold duration is determined by the on hold duration of the more recently created time hold task child

### Notes
We can simply add a unit test here as there is a [JS test for the display of the completed hold](https://github.com/department-of-veterans-affairs/caseflow/blob/4a1fd3cb0864788bb9bba239ed15fe3c6501e40a/client/test/karma/queue/ColocatedTaskListView-test.js#L395)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```

Why 1?
- Straightforward update to how we determine the on hold duration

Why 2?
- We should add a test for this which may be a bit hairy to set up
- Check UI update for all types of users that have a queue

**Comment by yoomlam** [comment]
Should be a backend change.
