### ISSUE TITLE
Do not reset `assigned_at` when changing task type

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13927]
>
![image](https://user-images.githubusercontent.com/45575454/72942308-16a06380-3d41-11ea-968a-258acf8fe074.png)

When we change task type, the [`assigned_at` timestamp](https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L97-L113) is [not provided](https://github.com/department-of-veterans-affairs/caseflow/blob/6e341a64406c9ba78a0f6146dbe1c59bcd61b30b/app/models/tasks/colocated_task.rb#L125-L134), so it is defaulted to the [task `created_at` timestamp](https://github.com/department-of-veterans-affairs/caseflow/blob/761e76a628fb5b5a2ea322755d51133d8e33ffe8/app/models/task.rb#L623).

## Acceptance Criteria
- [ ] `assigned_at` remains unchanged through a change in task type (currently only mail task and colocated tasks have this option)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||||||
2 | 
3 | 
5 | 
8 | 
```

Why 1?
- One line change along with a one line addition to an existing test

**Comment by hschallhorn** [comment]
Closing in favor of #13272
