### ISSUE TITLE
Intake | Update copy on appeal permissions alert

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13948]
# User or job story
As a non-BVA Intake user the error received when attempting to process a NOD should be updated to read

![image](https://user-images.githubusercontent.com/41164406/78943644-43cff880-7a8a-11ea-9d4a-7e3a83ea84c5.png)

**New Copy:** You are not authorized to perform this function. Please take the necessary steps to have the Notice of Disagreement form uploaded to the Centralized Mail Portal application. 

## Acceptance criteria
- [ ] The copy for this permission alert is updated with the copy provided

### Background/context
BVA has decided from the last update to the copy to not allow external entities to mail the NOD forms but instead send the form electronically via the Centralized Mail Portal. 

### Resources/other links
[Only allow appeal intakes for MailTeam users](https://github.com/department-of-veterans-affairs/caseflow/issues/13356)
[Intake | Update copy on appeal permissions alert #13906
](https://github.com/department-of-veterans-affairs/caseflow/pull/13906)

**Comment by leikkisa** [comment]
![Screen Shot 2020-04-10 at 10.06.09 AM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/658f3315-e9bd-404a-889e-a93412854c81)

**Comment by msj0nes** [comment]
@leikkisa is this behind flag or ready to announce as live?
