### ISSUE TITLE
Ability to remove (leave blank) a previously-saved POA email address

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#13945]
## User story
As a Hearing Coordinator, I want to remove (leave blank) the Power of Attorney (POA) / Representative email address for a virtual hearing (or if this is not supported, I don't want to go through the "email update" flow).

## Problem statement
On Hearing Details, when you try to delete (leave blank) a POA / Representative email on an already-created virtual hearing, Caseflow doesn't seem to save the change and goes into a "Loading..." state indefinitely (observed on demo).

**If** we want to allow deleting the POA email while not entering a new one (i.e. leaving POA email blank), we think we'll need to at least design:
- a delete confirmation modal
- appropriate success alert messaging

## Existing design and content
1. A previously-saved POA email on Hearing Details <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/957e39d3-276f-4802-add7-65ae7ce5edda"  border=1>

1.  POA email is deleted <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/ec5c355c-9ffa-4fb8-9589-0d0537529b7e"  border=1>

1. On Save, button stays in Loading state indefinitely <img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/0129dd32-60e3-41d5-916e-018b9258f6b6" border=1>

**Comment by chandracarney** [comment]
Wondering if our move to editing virtual hearing details on a full-page will resolve this issue?

**Comment by nicholer** [comment]
@chandracarney Unfortunately probably not. The problem is that there's no "delete" flow - I think we need at least a confirm modal and appropriate success message from a design perspective. And from an engineering perspective, it needs to actually delete :)

I think this would be good work for the new designer/researcher.
