### ISSUE TITLE
State Machine | Users get error if try to cancel completed task

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1394]
Our AASM setup does not allow tasks to be cancelled once they are completed. We try to prevent a user from doing this on the frontend, but they might still be able to. For example if they have two tabs open with the same task, complete one, and cancel the other. Or if they complete a task, hit back before it's completed and then cancel it.

In any case, we should provide some UI to explain to the user when they try to cancel that the task has already been completed.

See Sentry issue 130.

related: https://github.com/department-of-veterans-affairs/caseflow/issues/2072

**Comment by mmlumba** [comment]
Shade and I worked on an issue that addresses a similar concern: https://github.com/department-of-veterans-affairs/caseflow/issues/1416

The message to handle that exception is here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/EstablishClaimPage/EstablishClaim.jsx#L54

**Comment by kierachell** [comment]
dup of https://github.com/department-of-veterans-affairs/caseflow/issues/2072

**Comment by kierachell** [comment]
**PASSED**

Well, there can be a screenshot of nothing now...
