### ISSUE TITLE
Update Pexip URL and theme ID to use vc.va

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13952]
Change Pexip URL and theme ID to support the new Pexip updates and changes after they're rolled out by Pexip. Once this work is finished, verify connection and verify that we can still schedule and break down hearings in the dev environment.

## Acceptance criteria
- [ ] Change the API url to use /v2/*
- [ ] Update Pexip URL from care.va to vc.va
- [ ] Update theme ID
- [ ] Update emails
  - [ ] Update hearing link to use vc.va
  - [ ] Update test your connection site to use vc.va

## Background/context/resources
Closely related to #13525
After COVID-19 mitigation, updates will be made to account for Pexip theme ID, Pexip URL, web app and proxies to include:
- Easier recording functionality for VLJs
- Smoother user experience

https://dsva.slack.com/archives/C3EAF3Q15/p1583180539111900
https://dsva.slack.com/archives/C3EAF3Q15/p1582140624315100

**Comment by chandracarney** [comment]
Blocked until Pexip can work on new environment for the Board. We will need: new URL, theme ID, and credentials.

**Comment by lund5000** [comment]
Jonathan McNeil from OIT described some updates this morning that will come with the switch to vc.va. Caseflow will no longer connect directly to Pexip to create and delete static VMRs. Instead OIT will give us a shared policy script (which they also referred to as a shared key) that Caseflow can use to generate conference IDs and PINs that will be part of the URLs we send in the emails.

**Comment by lund5000** [comment]
Complete as part of https://vajira.max.gov/browse/CASEFLOW-239
