### ISSUE TITLE
Editing EP Claim Labels | Edit claim label for Caseflow established HLR/SC claims and EP930s

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13951]
## User or job story
As a VBA intake user, I need the ability to update the claim label in Caseflow for AMA claims established in Caseflow, such as HLR, SC, and EP930s.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by leikkisa** [comment]
I'm closing this ticket as a dupe of the epic #11490.  Please see the epic for tickets being broken out for this story.
