### ISSUE TITLE
Research: new hearing type of virtual, compatibility with legacy hearings

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13956]
## Description
The request type for a legacy hearing is stored directly on the hearing, instead of on the hearing day. This means that we could potentially have to introduce a new hearing type to VACOLS, which might not be possible since we won't be able to get a good sense if that would affect logic in VACOLS.

One possible way to work around this is by treating the `HearingDay` as the canonical source for scheduling data if the hearing is in Caseflow past a certain date (see https://github.com/department-of-veterans-affairs/caseflow/issues/13273). If there's a `HearingDay` associated with a legacy hearing, we can have the request type on that day override whatever is in VACOLS.

This ticket is preperation for virtual-only hearing days because there is an indicator in VACOLS regarding what the Veteran has opted in to. 

## Acceptance criteria
- [ ] Tech spec

## Background/context/resources
Information sourced from #13431

## Open questions
- Will adding a new request type have implications on VACOLS? 
- Since it's a new feature on a legacy model, do we want to support that?
- There are VACOLS location codes for legacy appeals (Central Office and video), do we need to add a new code? 
  - Location codes 36 and 38 in this: [VACOLS location codes](https://github.com/department-of-veterans-affairs/appeals-support/wiki/VACOLS-Location-Codes)

**Comment by ferristseng** [comment]
We should formulate a list of questions about this to ask Jed, and shoot him an email

**Comment by ferristseng** [comment]
Emailed Jed with some questions about how we can support virtual hearings in VACOLS (or whether we need to at all)

**Comment by ferristseng** [comment]
Some notes from my email with Jed:

  - The hearings team might not need to see the HEADSCHED data in VACOLS if they're using Caseflow already.
  - We will need to update `BRIEFF.BFHA` with a new code (possibly '7' for virtual hearing)

    > this field determines whether or not the hearing is still pending.  It determines if a case can be activated or not along with the presence of the Hearing Transcript in the ATTACH table.
  - We could add a new location code, but that would be up to the hearings team as well.

It sounds like we might need to get some more requirements around what the hearings team will need

**Comment by chandracarney** [comment]
Emailed the Hearing Management Branch regarding Jed's questions. We're blocked until the Branch makes a decision and the updates are made to VACOLS.
