### ISSUE TITLE
Research: new hearing type of virtual, ensure HearingDay model can accurately represent a virtual hearing

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13955]
## Description
The current `HearingDay` model looks as follows:

```
HearingDay(
  id: integer,
  bva_poc: string,
  created_at: datetime,
  created_by_id: integer,
  deleted_at: datetime,
  judge_id: integer,
  lock: boolean,
  notes: text,
  regional_office: string,
  request_type: string,
  room: string,
  scheduled_for: date,
  updated_at: datetime,
  updated_by_id: integer
)
```

### Open questions
- Should the `room` field be applied? 
There is some automated logic to find an available room in https://github.com/department-of-veterans-affairs/caseflow/blob/1d5bbcf189b2e8c3088ed30da6676fd1b70c8fc0/app/services/hearing_day_room_assignment.rb#L3, which we will need to circumvent for virtual hearings. Outside of that, it doesn't look like `room` is used too much in a way that we'd need to change.

- Does anything additional need to be added to `HearingDay`? 
As far as I can tell, we wouldn't since most of the info we need is tracked per-Hearing.

## Acceptance criteria
- [x] Answer open questions and define new ticket

## Background/context/resources
Information sourced from #13431

**Comment by rubaiyat22** [comment]
closing this in favor of new ticket https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/14431
