### ISSUE TITLE
Special Issues with italics are flush against checkbox

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1395]
Noticed in dispatch - could be a duplicate issue.

This:

<img width="210" alt="screen shot 2017-03-31 at 12 04 16 am" src="https://cloud.githubusercontent.com/assets/1053255/24536007/a91af8b8-15a5-11e7-9994-627ee0aa9989.png">

should look like this:

<img width="213" alt="screen shot 2017-03-31 at 12 03 49 am" src="https://cloud.githubusercontent.com/assets/1053255/24536011/ac0d37c0-15a5-11e7-82f0-429e49844834.png">

Radio buttons have the same problem:

<img width="151" alt="screen shot 2017-03-31 at 12 16 40 am" src="https://cloud.githubusercontent.com/assets/1053255/24536275/5e632780-15a7-11e7-8a87-0413fe824891.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="1013" alt="screen shot 2017-03-31 at 12 44 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/24560209/cb0257e0-160f-11e7-8945-22debe16a8f4.png">
