### ISSUE TITLE
Editing EP Claim Labels | Reflect Caseflow HLR or SC label change in VBMS

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13962]
## User story
As a VBA intake user, when I update the EP claim label in Caseflow for an established AMA claim, it should reflect in VBMS.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by leikkisa** [comment]
Combining this info into #15129, which is the ticket for handling sending the updates to BGS and VBMS. Closing this ticket.
