### ISSUE TITLE
Editing EP Claim Labels | Track Caseflow label changes made to a HLR or SC established in Caseflow

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13963]
## User or job story
As VBA Intake user, I need the ability to track Caseflow label changes made to a HLR or SC established in Caseflow

- Initial label created
- Current label created
- Previous label created 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by msj0nes** [comment]
This is more of a data tracking verification ticket for the team to assess all label changes being reportable.

**Comment by leikkisa** [comment]
We got an email with two reports created, I think they might be related to this ticket

Claim establishments
https://tableau.vba.va.gov/#/views/CaseflowClaimsEstablishmentReport/CaseflowCESTReport

EP changes to pending claims
The system of establishment is now available as a filter in the change details view of the EP change dashboard.
https://tableau.vba.va.gov/#/views/EPChangestoPendingClaims/ChangeDetails?:iid=1

Note:
@RebeccaBaumTT and myself need to get access to Tableau before we can view them.
