### ISSUE TITLE
Non-Veteran Claimants | Ability to edit claimant data for unlisted claimants

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13965]
## User or job story
As a Caseflow Intake user, I should be able to edit claimant data that was manually added for board appeals for claimants not listed in the corporate database, in case there was a mistake.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [non_veteran_claimants]
- [ ] On the Case Details page, where the appeal has an unlisted claimant, show an "Edit information" link (see design)
- [ ] Clicking "Edit information" navigates to the Add Claimant page.
- [ ] On the Add Claimant page, cancelling returns to Case Details without saving, and saving returns with saving
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Open questions
- URL path to edit claimant

### Out of scope
- Ability to edit unlisted claimant's POA information

### Designs
![Screen Shot 2020-11-04 at 3.31.07 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/ca8d2214-5899-42d3-8289-d6cbe3a807dc)

**Comment by leikkisa** [comment]
Closing - moved to Jira
