### ISSUE TITLE
Intake | Docket Switch

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13978]
# Background
## User Story
As an Attorney with the Office of the Clerk of the Board, I want to be able to change the docket type for a claimant's appeal to/from (1. Direct Review, 2. Evidence submission, 3. Hearing Request) for a granted Request to Modify in order to move the claimant's appeal to the requested docket and initiate subsequent tasks.   

## Problem/Pain Points
Currently the Board doesn't have an efficient way to process Requests to Modify submitted by a Veteran or a Non-Veteran Claimant in Caseflow. There is no way for a user to edit the docket type for an appeal and preserve the docket number, history of the appeal, and the associated tasks. 

1. Ideally, the Intake team should catch incoming Requests to Modify, however not all claimants directly indicate that they are requesting a docket change so these can get missed. These appeals get processed but the request to modify may be caught later down the line, which results in a need to backtrack and slows the case down and results in inefficiencies.  
2. Regulations state that a veteran is entitled to the original docket date because it (mostly) correlates to the order in which cases get reviewed. When users are having to re-docket the appeal to accommodate requests to modify, they are unable to edit the docket number to reflect the original one, which can affect the veteran/claimant's timeline.  
3. When users are having to delete and re-docket an appeal, associated tasks are also deleted or lost, which slows the case down and results in inefficiencies. Users may have to coordinate with respective teams (e.g. FOIA/Privacy Team, AOD, Hearings Team) in order to track down tasks. Losing or having to re-do tasks can have an impact on adherence to regulations and ultimately, also affects the veteran/claimant's timeline. 
4. When the appeal is deleted, the history of the appeal (and related context) is also lost which affects compliance with regulations. 

## Current Workaround
Currently attorneys at the Office of the Clerk of the Board are getting rid of the original docket/appeals stream in Caseflow and taking the original docket date and re-docketing with the new docket type. This results in pain points as indicated above and ultimately slows the process down and creates inefficiencies and risks. 

## User's Current Workflow
To understand the end-to-end workflow, please refer to: [this Mural
](https://app.mural.co/t/workqueue2001/m/workqueue2001/1593019961366/87411402f67814c17f01d3feb3a25cd9c41d1f3f)

## Success Criteria/Business Value
1. Increasing efficiency (and agency/autonomy) in Attorneys' workflows in order to remove dependencies and streamline their process.
2. Ensuring a Veteran/Claimant's case is not getting further back by having to re-do tasks. 

## Key Users
**Who should be able to switch docket types:** Specific attorneys at the Office of the Clerk of Board
Note: The Office of the Clerk of the Board is not a specific organization in Caseflow, they are part of the Mail and Intake team.

## Reporting requirements
1. The number of cases moved from one docket to another pursuant to such policy
2. The average time cases were pending prior to moving from one docket to another
3. The average time to adjudicate the cases after so moving
4. _TBD: Complying with regulations and keep history integrity, task trees and maintaining the tasks in order and not disturbing the veteran appeal._ 

Note: This functionality only applies to AMA Board Appeals. 

## Stakeholders

**Subject Matter Experts:** Adrian and Angeline
**Stakeholders:** John Gosnell, Mike Sanford, Judge (VLJ Hachey)

## Designs and workflows

[End-to-end Figma Designs
](https://www.figma.com/file/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=770%3A0)

# Requirements/stories
 🔃= moved to eng/eng in progress
✅= eng complete (Rutvi still has to mark these)

### Creating Mail Task
- [As a BVA Attorney with the Office of the Clerk of the Board, I want to see an option to create a mail task in Caseflow Queue so that I can initiate the process of adding a Docket Switch task #13979](https://github.com/department-of-veterans-affairs/caseflow/issues/13979)  🔃✅
- [As a BVA Attorney with the Office of the Clerk of the Board, I want to be able to create a "docket switch" mail task so that I can initiate switching dockets #15084](https://github.com/department-of-veterans-affairs/caseflow/issues/15084)  🔃✅
- [As a user of the Office of the Clerk of the Board, the "docket switch" task should only be available to me and specified users within my organization #15085](https://github.com/department-of-veterans-affairs/caseflow/issues/15085)  🔃✅
- [As a BVA Attorney with the Office of the Clerk of the Board, when I add a docket switch task, it should automatically be assigned to myself so that I can take the appropriate actions on it #15086](https://github.com/department-of-veterans-affairs/caseflow/issues/15086)   🔃✅
- [As a BVA Attorney with the Office of the Clerk of the Board, when I add a docket switch task, I want to be able to see a success banner so I know I have created a docket switch task #15094](https://github.com/department-of-veterans-affairs/caseflow/issues/15094)   🔃✅

### Sending recommendation to judge 
- [As a BVA Attorney with the Office of the Clerk of the Board, I want to be able to send a docket switch recommendation to a judge so that they can review and rule on it #15331](https://github.com/department-of-veterans-affairs/caseflow/issues/15331)  🔃✅
- [As a BVA Attorney with the Office of the Clerk of the Board, I should be able to see a "Send to judge" action in the action dropdown menu so I can send my recommendation with relevant information #15332](https://github.com/department-of-veterans-affairs/caseflow/issues/15332) 🔃✅
- [As a BVA Attorney with the Office of the Clerk of the Board, I should see a success banner once I have sent my recommendation to a judge so I can know it was successfully sent #15333](https://github.com/department-of-veterans-affairs/caseflow/issues/15333) 🔃

### VLJ receives and rules on recommendation
- [As a VLJ, I should receive the assigned docket switch case (via a Docket Switch Ruling task) in my personal queue so that I can review and rule on a docket switch request #15334](https://github.com/department-of-veterans-affairs/caseflow/issues/15334)  🔃✅
- [As a VLJ, I should be able to see a "Rule on docket switch" action in the action dropdown menu so I can review and rule on the docket switch request #15335](https://github.com/department-of-veterans-affairs/caseflow/issues/15335)  🔃✅
- [As a VLJ, I want to be able to see the docket switch recommendation from the Office of the Clerk of the Board so I can review and rule on the docket switch request #15336](https://github.com/department-of-veterans-affairs/caseflow/issues/15336)  🔃
- _Draft: As a VLJ, I can receive more instructions on adding a hyperlink, so that I can confidently add a hyperlink to the signed ruling letter. (TBD - not critical for MVP)_
- [As a VLJ, I should see a success banner once I have completed my ruling so I can know it was successfully sent back to the Office of the Clerk of the Board #15337](https://github.com/department-of-veterans-affairs/caseflow/issues/15337)  🔃

### Denial flow (Case Details)
- [As a BVA Attorney with the Office of the Clerk of the Board, I should receive the VLJ ruled docket switch case in my personal queue so that I can take the appropriate action #15338](https://github.com/department-of-veterans-affairs/caseflow/issues/15338)  🔃
- [As a BVA Attorney with the Office of the Clerk of the Board to whom a denied docket switch task is assigned, I should be able to see a "Deny Docket Switch" action in my action dropdown menu so I can initiate a docket switch denial.](https://github.com/department-of-veterans-affairs/caseflow/issues/15424)  🔃

### Denial flow (Denial Screen)
- [As a BVA Attorney with the Office of the Clerk of the Board to whom a denied docket switch task is assigned, I should be able to enter in the date and any context for the request so that Caseflow has a record of the denied docket switch.](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15470)  🔃
- [As a BVA Attorney with the Office of the Clerk of the Board, I want to be able to see a success banner when I confirm denying the docket switch so I can know I successfully denied the docket switch. ](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15471)  🔃

### Case Details (Pre-Switch)
- [As a BVA Attorney with the Office of the Clerk of the Board, I should receive the VLJ ruled docket switch case in my personal queue so that I can take the appropriate action #15338](https://github.com/department-of-veterans-affairs/caseflow/issues/15338)  🔃
- [As a BVA Attorney with the Office of the Clerk of the Board to whom a granted docket switch task is assigned, I should have a "Switch Docket" action in my action drop-down menu so that I can initiate switching dockets #15095](https://github.com/department-of-veterans-affairs/caseflow/issues/15095)  🔃✅
- [As a BVA Attorney with the Office of the Clerk of the Board to whom a granted docket switch task is assigned, I should have "Put task on hold, Cancel Task, Assign to Person, Assign to Team" actions in my action drop-down menu so that I can take necessary actions on the task #15096](https://github.com/department-of-veterans-affairs/caseflow/issues/15096)  🔃✅

### Switching Docket
- [As a BVA Attorney at the Office of the Clerk of the Board, I need a way to enter the necessary information from the Veteran's request to switch dockets, so that I best represent the veteran's request to switch dockets #15097](https://github.com/department-of-veterans-affairs/caseflow/issues/15097) 🔃
- [As a BVA Attorney at the Office of the Clerk of the Board, when I select issues to be switched, they should get copied to a new appeals stream and previous issues should get closed so that there aren't any duplicate issues #15098](https://github.com/department-of-veterans-affairs/caseflow/issues/15098) 🔃
- [As a BVA Attorney at the Office of the Clerk of the Board, I need a way to manually close out any tasks that are no longer relevant to the newly selected docket type and shouldn't be switched over so that unnecessary tasks do not remain open #15099](https://github.com/department-of-veterans-affairs/caseflow/issues/15099) 🔃
- [As a BVA Attorney at the Office of the Clerk of the Board, I need a way to manually open any tasks that are relevant to the newly selected docket type so that I can move the appeal forward #15100](https://github.com/department-of-veterans-affairs/caseflow/issues/15100) 🔃
- [When a user confirms switching a docket, tasks that are automatically associated with the previous docket need to be closed out and tasks associated with the new docket need to be automatically opened so that the appeal moves forward correctly #15101] (https://github.com/department-of-veterans-affairs/caseflow/issues/15101) 🔃
- [As a BVA Attorney at the Office of the Clerk of the Board, I need a way to review and confirm my selections so that I can ensure that the right information got entered #15102](https://github.com/department-of-veterans-affairs/caseflow/issues/15102) 🔃
- [As a BVA Attorney at the Office of the Clerk of the Board, I need a way to go back and make any necessary changes so that I can ensure all the information is correct #15103](https://github.com/department-of-veterans-affairs/caseflow/issues/15103) **- closed**

### Case Details (Post-Switch)
- [As a BVA Attorney with the Office of the Clerk of the Board, when I confirm the docket switch, I want to be able to see a success banner so I know I have successfully switched dockets #15104](https://github.com/department-of-veterans-affairs/caseflow/issues/15104) 🔃
- [As a BVA Attorney at the Office of the Clerk of the Board, I should be able to see the docket type change indicated in the veteran's record in Caseflow #13980](https://github.com/department-of-veterans-affairs/caseflow/issues/13980) 
- [As a Caseflow Queue user, I can see a persistent banner informing me of a docket switch so that I can appropriately address the two appeal streams](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15583)
- [When a user confirms switching a docket, all tasks should get routed to the appropriate team/individual's queue based upon the selected docket type, so that the appeal can move forward accurately #15105](https://github.com/department-of-veterans-affairs/caseflow/issues/15105) 

## Acceptance Criteria
1. Attorneys with the Office of the Clerk of the Board can successfully change the docket type for a granted docket switch. 

## References/Resources

[Design/Research Index](https://docs.google.com/document/d/1EIOF9sA82mR418Uxc8C0tcladY3UuGSUWJlyeWovvyE/edit?usp=sharing): This is an index of research and design phases and artifacts. 
[Open Questions Index](https://docs.google.com/document/d/10XvSeDzRhFXyeTzuRoHvLUHAaVMdjV_MjIsbThT1yCY/edit?usp=sharing): This is a list of resolved open questions

## Business value
BVA has noted there are instances in their Intake workflow where there is a need to change the docket type on a veteran. The change of docket types influence mechanisms within both Caseflow Intake and Caseflow Queue. Allowing Caseflow to perform this functionality would require cohesiveness with the associated mechanisms

## Out of Scope
- Attorneys and the Intake team have an external hand-off and reviewing/ruling process outside of Caseflow. We need to determine the scope of the user workflows that we handle within Caseflow. **(UPDATE 9/25: The recommendation and ruling steps are now included in this functionality.)**
- As a BVA Intake user, I need a way to send a request to modify to an attorney at the OCB so that they can get notified and begin to review it (the Intake team currently uses the Mail Portal, and having them do this in Caseflow would be adding to their workload).
- [As a BVA Attorney/VLJ/Hearing Coordinator, I need a way to send a Request to Modify that I noticed, to the Office of the Clerk of the Board, so that they can review it and begin to process the request.](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/14716) - closed
- [As a BVA Attorney at the Office of the Clerk of the Board, I need a way to receive Requests to Modify from Attorneys/VLJs/Hearing Coordinators so that I can review them and if granted, begin processing the request.](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/14717) - closed

## Open Questions
- What does “deleting” mean? What happens to the previous appeal stream? (From Sally: Removed appeals are still there, request issues are removed, cancels tasks.)
- Should we be duplicating the task tree from the previous appeal and remove the old one? 
- Should we be linking the previous appeal stream? 
- What tasks need to get transferred over?
- Should closed tasks still be visible on the case timeline? What should show up on the Case Timeline?
- How do we navigate which issues are being switched?
- Who specifically needs to have user permissions? Could we create a sub-org for the OCB? 

- Should we do anything with the cases that have gone through the workaround? What is the expectation here?
- Docket number - how does this get used in distribution? What are the implications of the docket number?
- How can Caseflow automate the opening and closing of tasks? What actions does a user take?

- If a partial, and they are switching tasks over, we just keep a second one and keep both open? 
- What if tasks are ineligible to be closed, what should happen with those?

**Comment by leikkisa** [comment]
Adding this note from another dupe ticket:
Veterans can choose an appeal lane, but can change their mind at any time; Caseflow should always honor the original docket date (i.e. the very first time the 10182 was submitted) each time a lane change happens.

**Comment by jcq** [comment]
- Can we create a sub-org for the Office of the Clerk of the Board and handle permissions via that?
- What stuff should just be archived, what stuff (tasks, etc) should be copied/preserved? Presumably there will be non-trivial conditional logic for filtering this depending on the original and new docket types

**Comment by RebeccaBaumTT** [comment]
from Mike Sanford:
He thinks of it as merely changing the docket type, not opening a brand new appeal;
He would think that the streams should be the same  only the docket type should change
38 CFR 20.800(a)(2)
"An appeal may be moved from one docket to another only when the Notice of Disagreement has been modified pursuant to Rule 202, paragraph (c)(3) 20.202(c)(3). The request to modify the NOD must reflect that the appellant requests the option listed in 20.202(b) that corresponds to the docket to which the appeal will be moved. An appeal that is moved from one docket to another will retain its original docket date."

**Comment by leikkisa** [comment]
Closing - migrated to Jira:
https://vajira.max.gov/browse/CASEFLOW-283
