### ISSUE TITLE
Intake | Docket Change | Design option to switch the docket type

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13979]
## User story and requirements
As a BVA Attorney with the Office of the Clerk of the Board, I need a way to switch the docket type for a Board appeal in Caseflow Queue so that I can initiate the process of switching docket types. 

For this, I need: 
- an option to switch dockets in my actions drop-down menu
- a way to select this option and see the first screen of switching dockets
- a way to exit this flow by cancelling

## Acceptance criteria
- [ ] Figma File with design(s)
- [ ] Screenshot(s) of design(s)

### Out of scope

Designs beyond the indicated user story

### Designs

- [ ] Figma File with design(s)
- [ ] Screenshot(s) of design(s)

### Background/context

Please see the Mural for the end-to-end user workflow. 
Please see the [epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978) for more background.

### Technical notes

TBD

### Resources/other links
[Epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978)
Mural with user workflow

**Comment by rutvigupta-design** [comment]
Encapsulated in [#15095](https://github.com/department-of-veterans-affairs/caseflow/issues/15095) - closing to avoid duplicate.
