### ISSUE TITLE
Intake UI Error Handling Update

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13988]
## Background/context
Some Intake error messages have the generic 'Something Went Wrong' error without additional context provided to the user on what triggered the error. An update is needed to these error messages that often result in support requests by users hindered by the error but have no direction on how to proceed with processing. 

## Stakeholders
- BVA
- VBA

## Requirements/stories
As a Caseflow Intake user, error messages should show a clear description of the root cause/trigger

## Open questions
- Some errors are triggered from CorpDB requiring users to make an update to the veteran's record in VBMS or SHARE. Stakeholder involvement would be needed to clarify the business process in clearing some errors.

**Comment by janechi1** [comment]
What is this functionality?
