### ISSUE TITLE
Intake | Docket Switch | Make docket type change visible in Caseflow

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13980]
## User story
As a BVA Attorney at the Office of the Clerk of the Board, I should be able to see the docket type change indicated in the veteran's record in Caseflow.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to all users with permission to view the appeal
- [ ] The docket type at the top of Case Details reflects the new docket
- [ ] The Case Timeline reflects that a docket switch occurred (please see designs below) 
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Resources/other links
[Epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978)

**Comment by leikkisa** [comment]
Close as an old story ticket
