### ISSUE TITLE
SPIKE | Investigate why form8 is nil in the certifications controller

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#1398]
Technical details:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/134/

**Comment by amprokop** [comment]
Try to timebox this to an hour— this only happened once according to @aroltsch

**Comment by nemodjuric** [comment]
#<Form8 id: 20634, certification_id: 29434, vacols_id: "3209941", appellant_name: nil, appellant_relationship: nil, file_number: "440702011S", veteran_name: "DAVIS-CARRUTH, STAPHANIE, L", insurance_loan_number: nil, service_connection_for: nil, service_connection_notification_date: "2015-05-22", increased_rating_for: nil, increased_rating_notification_date: "2015-05-22", other_for: nil, other_notification_date: "2015-05-22", representative_name: "Military Order of the Purple Heart", representative_type: "Organization", representative_type_specify_other: nil, power_of_attorney: nil, power_of_attorney_file: nil, agent_accredited: nil, form_646_of_record: nil, form_646_not_of_record_explanation: nil, hearing_requested: "Yes", hearing_held: "No", hearing_transcript_on_file: nil, hearing_requested_explanation: nil, contested_claims_procedures_applicable: nil, contested_claims_requirements_followed: nil, soc_date: "2015-12-16", ssoc_required: "Not required", record_other_explanation: nil, remarks: nil, certifying_office: "St. Paul RACC, MN", certifying_username: "RO76", certifying_official_name: nil, certifying_official_title: nil, certification_date: "2017-03-31", record_cf_or_xcf: nil, record_inactive_cf: nil, record_dental_f: nil, record_r_and_e_f: nil, record_training_sub_f: nil, record_loan_guar_f: nil, record_outpatient_f: nil, record_hospital_cor: nil, record_clinical_rec: nil, record_x_rays: nil, record_slides: nil, record_tissue_blocks: nil, record_dep_ed_f: nil, record_insurance_f: nil, record_other: nil, _initial_appellant_name: nil, _initial_appellant_relationship: nil, _initial_veteran_name: "DAVIS-CARRUTH, STAPHANIE, L", _initial_insurance_loan_number: nil, _initial_service_connection_notification_date: "2015-05-22", _initial_increased_rating_notification_date: "2015-05-22", _initial_other_notification_date: "2015-05-22", _initial_soc_date: nil, _initial_representative_name: "Military Order of the Purple Heart", _initial_representative_type: "Organization", _initial_hearing_requested: "Yes", _initial_ssoc_required: "Not required", created_at: "2017-03-31 14:06:17", updated_at: "2017-03-31 14:06:17", certifying_official_title_specify_other: nil>

**Comment by nemodjuric** [comment]
There were 2 tries created in parallel to certify this appeal. certification_id: 29434 and certification_id: 29435. They were created at the same time: 2017-03-31 14:06:17
29435 was completed, 29434 was not. 
Possible cause - quick reload. @shanear
