### ISSUE TITLE
Intake Decision Types and Dates | Process all AMA claims with most recent decision 2005 and prior

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13983]
## User story
As a Caseflow user, I need the Caseflow application to be able to process all AMA claims for which the most recent decision was prior to the year 2005, so that I can ensure that I am able to process AMA claims pertaining to older decisions

Definition of Done:
1.Caseflow is able to process AMA claims for prior decisions in a date-agnostic manner, i.e.,
regardless of the date of the prior decision was made.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by leikkisa** [comment]
I am closing this ticket, it's out of date.
