### ISSUE TITLE
Validate that the special issues are not selected along with the "No Special Issues"

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13995]
## User or job story
Job story: When a attorney or judge selects the "No Special Issues" option all other options should be unchecked and disabled so the data captured on the page is accurate. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: special_issues_revamp
- [ ] This feature should be accessible to the following user groups: Attorneys & Judges
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] If "No Special Issues" is clicked then all other options are unchecked and disabled

### Background/context
The special issues page allows selecting "No Special Issues" along with others. This should not continue as it will cause the data being captured to be inaccurate leading to potential confusion/issues down the line. 

### Resources/other links
[Slack Conversation](https://dsva.slack.com/archives/CJL810329/p1586876908343800)

**Comment by yoomlam** [comment]
Related to #13735. See its PR for a head start.

**Comment by geronimoramos** [comment]
Switched up the first component to radio buttons to enable/disable the checkboxes. My first thought was to start with No to disable and prevent users from selecting an issue + selecting no issues while still making the options visible versus revealing them.
Alternately, it can start with yes and if users don’t select an issue they get a validation error.
Alternately, the radio buttons can start unselected but still follow the same behaviors listed above.
![image](https://user-images.githubusercontent.com/49766982/79257947-3ecec880-7e3f-11ea-8bce-cc9734044473.png)

**Comment by geronimoramos** [comment]
@araposo-tistatech do we want to park or close this? I took this on a tangent

**Comment by araposo-tistatech** [comment]
@geronimoramos can we just get some copy for the error message to display?

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||
3 | ||||||
5 | 
8 | 
```

Possible fallback to just stopping the user from moving forward with both `None` and another, if the lift looks unmanagable.


#### Why 1?
- 

#### Why 2?
- 

#### Why 3?
- Larger front end lift to implement disabling other buttons and unchecking selected
