### ISSUE TITLE
Codify JudgeTeam one admin limit

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13993]
## Description
We expect JudgeTeams to have one admin user, and that admin to be the Judge on the team. We should codify this expectation into the code and correct any existing issues with production data.

The ability to flag other users as admins existed due to shared code with other organizations, but is not stable or supported by our code.

The correct place to restrict this is to be determined as a part of the work. React, Rails, or PostgreSQL.

The BVA Admins will do the additional admin removal themselves, the engineering team should not. ([see comment](https://github.com/department-of-veterans-affairs/caseflow/issues/13993#issuecomment-613497634))

## Acceptance criteria
- [ ] Confirm existing JudgeTeams only have the Judge as an admin user
- [ ] Attempts to label an additional user as admin are blocked at the appropriate level

## Background/context/resources
Part of #13991, Working to revert now-unneeded architecture changes while improving JudgeTeam architecture to match Board use.

**Comment by araposo-tistatech** [comment]
The following users at the Board have more than one nonjudge user assigned as an admin: 

2 admin users on VACOMCLEOK1
2 admin users on BVAKOSBORNE

This work is blocked by #13748 as BVA Admins will need the ability to view and modify the above judge teams to remove the admin role for one of the nonjudge users.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | |||||||
3 | ||||
5 | 
8 | 
```



Why 1?
- 

Why 2?
- Might just be a new valiadation when trying to add a user to the JudgeTeam, or trying to flag them as Admin

Why 3?
- Figuring out how to enforce one admin limit at the DB level

**Comment by hschallhorn** [comment]
>The following users at the Board have more than one nonjudge user assigned as an admin:

In case this changes in the amount of time it takes to get to this ticket
```ruby
OrganizationsUser.where(organization: JudgeTeam.all, admin: true).group(:organization_id).count.select { |org_id, count| count > 1 }.map { |org_id| Organization.find(org_id.first).name }
=> ["VACOMCLEOK1", "BVAKOSBORNE"]
```
