### ISSUE TITLE
Determine JudgeTeam role via the admin status

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13994]
## Description
We created a new architecture for JudgeTeams to support new roles that were eventually implented a different way. As a part of that we updated all places that determine whether someone is a Judge or Attorney to use this new logic.

This ticket exists to revert the determination of Judge or Attorney in caseflow back to whether the user is the admin of the JudgeTeam (the judge) or a non-admin of the team (an attorney).

## Acceptance criteria
- [ ] Judge & Attorney in Caseflow are determiend via admin status
- [ ] No changes are done to JudgeTeamRoles in this issue - that will be adjusted in follow on work

## Background/context/resources
Part of #13991, Working to revert now-unneeded architecture changes while improving JudgeTeam architecture to match Board use.

## Technical notes
I believe the work for this ticket is largely or wholly reversing the changes made for #12422, but we should proceed with some caution simply do to the 6 months of changes and possible additions since then.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```



Why 1?
- Removing logic from PR

Why 2?
- Hedging
- ACD always gets me nervous

**Comment by yoomlam** [comment]
@lomky 
Since `use_judge_team_roles?` returns false in prod, which means our code is using admins to determine a user's role: https://github.com/department-of-veterans-affairs/caseflow/blob/e6279de98591de6b6a5fa7657c0769c00715b963/app/models/organizations/judge_team.rb#L42-L48
I'm unclear what I need to do for the PR.

In prod:
```ruby
FeatureToggle.enabled?(:judge_admin_scm)
=> false
```
