### ISSUE TITLE
Missing Ratings | Assessment: RatingWebService.findRatingData among current Caseflow BGS services in production

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13996]
## Description
An assessment of Caseflow's current service among RatingComparisonEJBService, RatingInformationService and RatingWebService.findRatingData in populating adequate rating issues should be reviewed in order to consider the addition of RatingWebService.findRatingData to Caseflow production.

## Acceptance criteria
- [ ] Test RatingWebService.findRatingData in UAT
- [ ] Maybe: test RatingManagementService in UAT (awaiting documentation to learn more about the end points)
- [ ] Compare rating issue and disability data with current rating services implemented (produce comparison report)
- [ ] Document if there is improvement with the promulgation date
- [ ] Assess and document known conflict with use of services simultaneously
- [ ] Come up with recommendation on whether or not to implement one of these services

## Background/context/resources
The addition of a new rating service does not yield adequate ratings issues for selection to label 'Missing Ratings' requirement complete. 

## Technical notes
Once we have documentation, these services can be tested against UAT without merging them in the code. This may require use of the UAT jumpbox.

[Instructions for testing can be found in the appeals-deployment wiki](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Local-Testing-of-VBMS-and-BGS).

**Comment by leikkisa** [comment]
I checked out the WSDL for the RatingManagementService and it doesn't have enough information about how to use the service, such as the input field names.  Same for the RatingWebService.

http://bepdev.vba.va.gov/RatingWebServiceBean/RatingWebService?WSDL
http://bepdev.vba.va.gov/RatingManagementService/RatingManagementService?WSDL

I would like to reach out to BGS to ask for more documentation for these services.  I think implicit in that we'll need to ask for permission to use them as well.

**Comment by leikkisa** [comment]
Full documentation is available in the internal [appeals-team](https://github.com/department-of-veterans-affairs/appeals-team/tree/master/Project%20Folders/Caseflow%20Projects/Intake/BGS-VBMS/BGS-API-Docs) repo.

I was not able to find findRatingData in the RatingWebService, but there was only one method available that looked relevant:

Service name: RatingWebService
Method name: findRatingDecnByPtcpntVetId
Input: PtcnptVetId

**Comment by leikkisa** [comment]
The RatingManagementService seems like all of its methods are for working with the current/new/in progress rating, instead of rating profiles.  It is unclear to me if that means returning only the latest rating profile, or if it means returning all issues that are active.

There are many methods available, but I think checking out just one would be valuable for seeing what kind of data it returns.

Service name: RatingManagementService
Method name: getRating

**Inputs**:
veteranId (string)
isBackfill (boolean)

**Comment by leikkisa** [comment]
Here is the link to the [ruby-bgs PR](https://github.com/department-of-veterans-affairs/ruby-bgs/pull/96) being used to look at the services in UAT

**Comment by leikkisa** [comment]
[Link to spreadsheet with comparison analysis](https://docs.google.com/spreadsheets/d/1o-5fd7AMrv7BbDE76MVssyfm2tZ1hiVdfj3uJ8_9-w8/edit#gid=1896162516)
