### ISSUE TITLE
Remove code associated with JudgeTeamRoles

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13999]
## Description
We created a new architecture for JudgeTeams to support new roles that were eventually implented a different way. As a part of that we created the model JudgeTeamRoles and associated them with Users of JudgeTeams.

This is the first of two issues removing JudgeTeamRoles.

This Issue: remove all code references to the model JudgeTeamRole, orphaning them
Issue #14000: remove the model and database entry

## Acceptance criteria
- [ ] References to the JudgeTeamRole have been refactored out of the codebase
- [ ] The models themselves are reduced to a `noop` model, but are not yet removed

## Background/context/resources
Part of #13991, Working to revert now-unneeded architecture changes while improving JudgeTeam architecture to match Board use.

## Technical notes
All changes we're removing here would have been introduced as a part of the SCM epic #11801  before the pivot, so refer to PRs on those issues!

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```

Make models into `dummies` to cause errors/warnings.

Why 1?
- ctrl-f "JudgeTeamRole", "DecisionDraftingAttorney", "JudgeTeamLead" (ignoring the models themselves)

Why 2?
- Pessimism
- Finding references to it can be tricky
- Tracking down test errors thrown by dummy models
