### ISSUE TITLE
JudgeTeam Architecture Cleanup

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13991]
## Background/context
As a part of the effort to implement Special Case Movement abilities around Judge Teams, we created the concept of Judge Team Roles. However, in the end we chose a different implementation of these features that relies on Case Movemnt Organization membership, instead. 

This epic exists to roll back the now unneeded complexity we introduced to the judge team model, along with the removal of related, unreleased features.  

## Goals
Ensure our data model isn't more complex than necessary. 

## Success criteria
 - JudgeTeams can assert their Judges and their Attorneys
 - JudgeTeamRole is retired & removed
 - JudgeTeam Organization Management Page retains its improved layout with corrected wording
 - Judges cannot be removed from their JudgeTeam
 - Admin Rights cannot be toggled for users via Judge Team Management Page

## Stakeholders

 - Current and Future Caseflow Engineers
 - VLJs & Attorneys

## Requirements/stories
 - #13992 Remove unneeded buttons from JudgeTeam Team Management
 - #13993 Codify JudgeTeam one admin limit
 - #13994 Determine JudgeTeam role via the admin status
 - #13999 Remove code associated with JudgeTeamRoles
 - #14000 Remove JudgeTeamRole Model

## References/Resources
SCM Epic: #11801

**Comment by yoomlam** [comment]
@lomky Want to confirm that the UI needs updating too, correct? https://github.com/department-of-veterans-affairs/caseflow/blob/ac3c0ffb364ccce4891444b9f75692504da949eb/app/controllers/organizations/users_controller.rb#L72-L78
