### ISSUE TITLE
Remove unneeded buttons from JudgeTeam Team Management

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#13992]
## Description
JudgeTeams should only have their Judge as the team admin, moving forward, so the button offering to toggle admin should be removed. Judges should not be able to be removed from their JudgeTeams, so remove the "Remove User" button from the Judge User.

Changes should be made locked behind the existing `judge_admin_scm` FeatureToggle that controls the now-defunct changes to Judge Teams.
Changes should not conflict with those linked to `scm_view_judge_assign_queue`, the active work enabling SCM Judge actions via the CaseMovement organization.

## Acceptance criteria
- [ ] JudgeTeam Team Management pages do not show admin toggle button
- [ ] JudgeTeam Team Management pages do not show remove user button for the judge
- [ ] JudgeTeam Team Management Decision Drafting Attorney button is instead a label
- [ ] JudgeTeam Team Management explanatory text is updated
- [ ] Other organization Team Management pages are unaffected
- [ ] Changes are locked to the `judge_admin_scm` FeatureToggle

## Background/context/resources
Part of #13991, Working to revert now-unneeded architecture changes while improving JudgeTeam architecture to match Board use.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||
3 | |||||
5 | 
8 | 
```

Convert attorney toggle into a nonclickable label.
FE change.
Don't conflict with other FeatureToggles.

Why 2?
- Logic already exists to determine which org is a judge team on their team management page
- Logic already exists to determine the role of each user on a judge team team management page

Why 3?
- pessimism
- Testing

**Comment by ajspotts** [comment]
Related PR: https://github.com/department-of-veterans-affairs/caseflow/pull/13191
