### ISSUE TITLE
Remove JudgeTeamRole Model

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14000]
## Description
We created a new architecture for JudgeTeams to support new roles that were eventually implented a different way. As a part of that we created the model JudgeTeamRoles and associated them with Users of JudgeTeams.

This is the second of two issues removing JudgeTeamRoles.

Issue #13999: remove all code references to the model JudgeTeamRole, orphaning them
This Issue: remove the model and database entry

## Acceptance criteria
- [ ] Remove production JudgeTeamRoles data
- [ ] Remove Models & update schema to remove JudgeTeamRoles

## Background/context/resources
Part of #13991, Working to revert now-unneeded architecture changes while improving JudgeTeam architecture to match Board use.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||||||
3 | 
5 | 
8 | 
```

Why 1?
- 

Why 2?
- Touching production data!
- Touching the database!
- Previous migration woes!
