### ISSUE TITLE
App Canvas | Route Claim | Add a "Copy note" button

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1400]
As a user, I want to be able to quickly copy a lot of text and paste it at another application (such as email). 

# Acceptance Criteria

- Verify that the button style is [USWDS secondary button](https://standards.usa.gov/components/buttons/) (blue font on white)
- Verify that it says `Copy note` in sentence case
- Verify that it is located 17 px below the text box and aligned to the left
- Verify that when clicking the button, the note inside the text box is copied
- Verify that icon is on the right of copy
- Verify that the copied text can be pasted somewhere
- Verify that it applies in the follow pages: **Route Claim: Send email notification**,
**Route Claim: VACOLS Updated, Add VBMS Note**, 
- Verify that the text box is on the right of the word `message:` 

# Mockups
**Route Claim: Add VBMS Note**
![image](https://cloud.githubusercontent.com/assets/13420618/24562426/c90ee08a-1618-11e7-9d6b-0819230c9a9f.png)

**Route Claim: VACOLS Updated, Add VBMS Note**
![image](https://cloud.githubusercontent.com/assets/13420618/24809240/e6339f10-1b8c-11e7-8645-a923ba0392eb.png)

**Route Claim: Send email notification**
![image](https://cloud.githubusercontent.com/assets/13420618/24809522/c4e09eb6-1b8d-11e7-88b0-5d75a9aeea87.png)

**Spacing spec for text box**
![image](https://cloud.githubusercontent.com/assets/13420618/25049180/6d05dcc0-210e-11e7-8f3d-d6a71b2e39c3.png)

# Copy

Copy note

# Icon

[Copy icon svg file
](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Copy%20Icon.svg)

# Note
This will be going on the living style guide

**Comment by Sjones352** [comment]
### Tasks
[ ] Verify that the button style is [USWDS secondary button](https://standards.usa.gov/components/buttons/) (blue font on white)
[ ] Verify that it says `Copy note` in sentence case
[ ] Verify that it is located 17 px below the text box and aligned to the left
[ ] Verify that when clicking the button, the note inside the text box is copied
[ ] Verify that icon is on the right of copy
[ ] Verify that the copied text can be pasted somewhere
[ ] Verify that it applies in the follow pages: **Route Claim: Send email notification**,
**Route Claim: VACOLS Updated, Add VBMS Note**, 


<img width="1280" alt="screen shot 2017-04-11 at 9 53 07 am" src="https://cloud.githubusercontent.com/assets/23080951/24912729/03c0c98c-1e9d-11e7-9ea7-0bfbb205cee9.png">

**Comment by gnakm** [comment]
I'm going to close this because this has been fixed and the button is being worked on. Please feel free to open if you feel it's necessary!

**Comment by Sjones352** [comment]
@gnakm re-opening issue as I work off the Acceptance Criteria.

**Comment by Sjones352** [comment]
@gnakm 
currently are positioned on top of the textarea. Do you want them on the left of the textarea. Asking because it is not in acceptance Criteria.  
<img width="582" alt="screen shot 2017-04-14 at 11 56 41 am" src="https://cloud.githubusercontent.com/assets/23080951/25048433/7e78daf6-210a-11e7-9f5c-654ef4a1bcb6.png">

**Comment by gnakm** [comment]
Thanks for bring this to my attention. I fixed it on the AC that message: and the textbox should be side by side.

**Comment by astewarttistatech** [comment]
@Sjones352 

Current View: 
<img width="1190" alt="screen shot 2017-04-21 at 9 43 34 am" src="https://cloud.githubusercontent.com/assets/23038505/25280201/1b14bcf6-2677-11e7-8501-afe57fbfe09b.png">

**Comment by Sjones352** [comment]
@astewarttistatech 
Current view
<img width="1079" alt="screen shot 2017-04-21 at 10 48 18 am" src="https://cloud.githubusercontent.com/assets/23080951/25283129/b0e372e6-2680-11e7-9f0a-cba2e2de3935.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Go to Dispatch as a caseworker and assign a Full Grant to a Tier 1 or Tier 2 special issue. 
2. On the Route Claim page, continue to the next page
3. On the VBMS Note page, verify that the Copy Note button UI matches the mocks displayed above in the AC. 

Screenshots: 
<img width="1197" alt="screen shot 2017-04-21 at 11 42 58 am" src="https://cloud.githubusercontent.com/assets/23038505/25285284/b05d65d2-2687-11e7-8d1f-95a0a6dda53c.png">
