### ISSUE TITLE
Contested Claims | Attorney Fees | Create list of existing attorney-fee cases

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14002]
## Description
Investigate existing cases in the Caseflow database and create a list of ones that appear to be for attorney fees.

## Acceptance criteria
- [x] Create a CSV or other spreadsheet with columns for review type, review id, docket number if appeal, creation date (see attached code for full column list)
- [x] Document the queries in this ticket
- [x] Make sure @msj0nes gets a copy

## Background/context/resources
Intake users currently use a work-around for attorney-fee cases, by adding non-rating issues and noting in the description of the issue that it's related to attorney fees. As part of a shift toward a more data-driven approach to prioritization, the Board would like transparency into when and how frequently attorney-fee cases enter the system.

## Technical notes
One way to start is by applying a text-matching filter on top of the RequestIssue's `nonrating` scope, like

```
> RequestIssue.nonrating.where("nonrating_issue_description LIKE '%ttorney fee%'")
```

and then try different variations on the text-matching. Postgres's ILIKE operator does case-insensitive matching, although it's a bit slower.

**Comment by nanotone** [comment]
The code used to generate the CSV:
```ruby
CSV.generate do |csv|
  csv << %w[issue_id issue_category issue_description review_type review_id receipt_date docket_number veteran_is_not_claimant]
  RequestIssue.nonrating.where("nonrating_issue_description ILIKE '%att%y fee%'").each do |ri|
    dr = ri.decision_review
    csv << [ri.id, ri.nonrating_issue_category, ri.nonrating_issue_description, dr.class.to_s, dr.id, dr.receipt_date, dr.try(:docket_number), dr.veteran_is_not_claimant]
  end
end
```

The issue description is quite valuable for providing context on the case, as users currently have no other way to label a case as an attorney fees case. **However, this means that descriptions must be scrubbed of PII before the CSV is shared.**

Note the Postgres operator `ILIKE '%att%y fee%'` which does a case-insensitive match for "attorney fee(s)", common misspellings such as "attorny fee(s)", and common abbreviations such as "atty fee(s)".

**Comment by alisan16** [comment]
What was the result of this investigation? Is there an estimate of how many existing claims are attorney fee cases? And, were you also able to estimate the size of the wider pool of contested claims? cc @pshahVA
