### ISSUE TITLE
BVA Dispatch: Alphabetize Special Issues 

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14019]
## User or job story
User story: As a BVA Dispatch user, I need to see the special issues on the special issues page during checkout alphabetized, so that I can read and select the options quickly.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: :special_issues_revamp
- [ ] This feature should be accessible to the following user groups: BVA Dispatch
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Special Issues listed on the page are alphabetized including the new contentions added recently (MST, Burn Pit, CAVC, Blue Water)

### Technical notes
The special issues page only appears for Legacy cases at this time.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||||
2 | |||
3 | 
5 | 
8 | 
```

Postpone this ticket until FeatureToggle is made permanent b/c that will make the change a lot easier.

Why 1?
- Easy to do (sort the special issues constant files) in PR that removes special issues feature flag
