### ISSUE TITLE
Header: hide the "S" or "C" in the Veteran ID

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1401]
## Context
Currently, the Vet ID contains an S or a C at the end of the ID, which makes it difficult for users to copy and paste the number as needed. 

## Description
Hide the S (if 9 digits) or the C (if 8 digits) in the UI anywhere a Vet ID is displayed in the application:
- Work History page
- Success page
- Header

## Dev Notes
- Reuse sanitized_vbms_id method from Certification, see [appeal.rb](https://github.com/department-of-veterans-affairs/caseflow/blob/a6883703114d742c04f620510040612ed3fc7169/app/models/appeal.rb)

### Current State
![image](https://cloud.githubusercontent.com/assets/4042181/24560401/aa69745e-1610-11e7-8a51-01160546923a.png)

### Expected
![image](https://cloud.githubusercontent.com/assets/4042181/24560776/1981c908-1612-11e7-9ce1-be610f1beb43.png)

## Acceptance Criteria
- Verify that the Veteran ID displayed in the header contains only digits, and does not contain an S or C and the end
- Verify that the Veteran ID(s) displayed on the Work History page contain only digits, and does not contain an S or C at the end
- Verify that the Veteran ID displayed on the Success page contains only digits, and does not contain an S or C at the end
- Verify that the Veteran ID displayed [anywhere else in application] contains only digits, and does not contain an S or C at the end

**Comment by slj** [comment]
@abbyraskin is it sufficient to treat "application" as dispatch for this issue (for now)?

**Comment by abbyraskin** [comment]
@slj yes, this refers specifically to Caseflow Dispatch -- I believe Certification and eFolder Express have their own handling (though I don't know to what extent they differ).

**Comment by astewarttistatech** [comment]
Hey sorry to be a butthole but what am I checking for by "?" in AC @abbyraskin ?

**Comment by abbyraskin** [comment]
@astewarttistatech sorry, you can remove that if you want. the important part is to make sure the change applies anywhere the Vet ID is shown in the app

**Comment by astewarttistatech** [comment]
The success page is blocking complete verification of this issue in Preprod. 

Current pages based on AC: 
<img width="1058" alt="screen shot 2017-04-18 at 10 39 33 am" src="https://cloud.githubusercontent.com/assets/23038505/25136900/404875ee-2424-11e7-8f2e-c128c5a35a08.png">
<img width="1031" alt="screen shot 2017-04-18 at 10 39 46 am" src="https://cloud.githubusercontent.com/assets/23038505/25136902/40510696-2424-11e7-890a-f43efd42bbee.png">
<img width="964" alt="screen shot 2017-04-18 at 10 41 05 am" src="https://cloud.githubusercontent.com/assets/23038505/25136901/404a707e-2424-11e7-8068-8b975ada85cf.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in : Preprod
Browser: FF 

Steps to Validate: 
1. Go through Dispatch as a caseworker and establish the next claim in the queue.
2. On the Review Decision page, make sure that the Veteran ID on the header does not include a 'S' or a 'C' at the end of the number. 
3. Validate this on all pages in the Dispatch caseworker flow. 
4. Validate that the Veteran ID doesn't include a 'S' or a 'C' at the end of the number on the Success page. 
5. Navigate back to the Work History page
6. Validate that the Veteran ID doesn't include a 'S' or a 'C' at the end of the number in the Work History listing. 

Screenshots: 
See above and below

Success page added: See below
