### ISSUE TITLE
[Flaky Test] Supplemental Claim Edit issues edit_spec.rb:772

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14013]
## Description
```
Supplemental Claim Edit issues when remove decision reviews is enabled for supplemental_claim when review has multiple active tasks cancel all active tasks when all request issues are removed
     Failure/Error: expect(in_progress_task.reload.status).to eq(Constants.TASK_STATUSES.cancelled)

       expected: "cancelled"
            got: "in_progress"

       (compared using ==)
     # ./spec/feature/intake/supplemental_claim/edit_spec.rb:772:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

## Background/context/resources

 - Circle CI Error:  [`Failure/Error: expect(in_progress_task.reload.status).to eq(Constants.TASK_STATUSES.cancelled)`](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/29837/workflows/88ed078e-bbf3-4e22-b572-e48af7a4797f/jobs/109427/parallel-runs/2?filterBy=FAILED)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by yoomlam** [comment]
https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/29880/workflows/00f5e336-8f95-4828-87e3-b27d116a229d/jobs/109569/parallel-runs/2?filterBy=FAILED

**Comment by leikkisa** [comment]
Believe this is fixed, being quite old - closing
