### ISSUE TITLE
BVA Dispatch: Add Validation to Special Issues

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14018]
## User or job story
Job story: When a BVA Dispatch team member clicks continue on the special issues page, and a special issue is not chosen or the "No Special Issues" checkbox is not selected, they need to see an error message noting a selection needs to be made on the page.

## Acceptance criteria
- [x] add error if no issue is selected "Choose at least one. If no special issues apply to this case, please confirm by selecting “No special issues” (Legacy Only)
- [x] Please put this work behind the feature toggle: :special_issues_revamp
- [x] This feature should be accessible to the following user groups: BVA Dispatch
- [x] Include screenshot(s) in the Github issue if there are front-end changes

## Release notes
New special issues were added to the special issues page in Dispatch during the checkout process. Along with the new issues a "No Special Issues" option was added as selection is required on this page.

### Background/context
We are adding a "no special issues" option on the special issues page so validation will need to occur on the page to ensure a selection is being made.

### Resources/other links
Ref: https://github.com/department-of-veterans-affairs/caseflow/issues/13735 for validation completed in Queue.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```

Use same wording as during Judge/Atty checkout.

Why 1?
- Validation already exists elsewhere, can replicate

Why 2?
- Dispatch is laid out differently than Queue, so maybe some ramp up
