### ISSUE TITLE
Mark cases in_progress when a user clicks into a case details

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14023]
Aka fix #6788. 

Currently, we only have 5 task types marked as in_progress
```ruby
pp Task.in_progress.group(:type).count
[2020-04-16 12:39:54 -0400]    (39.7ms)  SELECT COUNT(*) AS count_all, "tasks"."type" AS tasks_type FROM "tasks" WHERE "tasks"."status" = $1 GROUP BY "tasks"."type"  [["status", "in_progress"]]
{"HearingAdminActionOtherTask"=>2,
 "NoShowHearingTask"=>46,
 "HearingAdminActionVerifyAddressTask"=>2,
 "RootTask"=>1,
 "DistributionTask"=>1,
 "TrackVeteranTask"=>46416}
```

The logic to do this is done on the front end
https://github.com/department-of-veterans-affairs/caseflow/blob/0ec98c06bdf3d76d2059f4e94c858b90d3c12eb9/client/app/queue/CaseDetailsLink.jsx#L19-L29

Instead, we should update the task status for all users on the back end

### AC
- [ ] Front end patch to task is removed
- [ ] When a user views case details of an appeal and they are the assignee of a task on that appeal and the task status is "assigned" update the task status to "in_progress"
- [ ] Replicate #5800 for all user queues

Release Notes: 
Cases that have been viewed in Queue by the user that is assigned to the task will mark the task as "In Progress"

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | ||||||||||
5 | |
8 | 
```

`started_at` is updated when status is updated to `in_progress`.

Why 3?
- Moving logic from frontend to backend could be slightly tricky
- Logic around whether or not to bold/not bold a case details link may be hairy

Why 5?
- Mildly intimidated

**Comment by hschallhorn** [comment]
Where we determine bolding (remove role check!) https://github.com/department-of-veterans-affairs/caseflow/blob/0ec98c06bdf3d76d2059f4e94c858b90d3c12eb9/client/app/queue/CaseDetailsLink.jsx#L46
Where we pull all tasks for an appeal for case details (add update status for any tasks with "assigned" status and assigned to the current user) https://github.com/department-of-veterans-affairs/caseflow/blob/befe386da2803738292594f844a7f9fb87317f9e/app/controllers/tasks_controller.rb#L102-L108

**Comment by hschallhorn** [comment]
@araposo-tistatech This has merged and will be released on Monday. Do we want to write something up in headway? For all users, cases assigned to them that they have not clicked into will appear as bolded in their queue. Once they veiw the case, the link will return to a "normal weight" (what the heck is better wording for that?)
![81850269-c0d90c80-9525-11ea-9ad2-10316cb99cf6](https://user-images.githubusercontent.com/45575454/82070867-5352ea80-96a3-11ea-965e-5671274698bb.gif)
