### ISSUE TITLE
Upgrade Storybook and build stories

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#14021]
## Description
The initial setup of Storybook included building stories for some but not all of the core common UI components. The intention was to use that as an example for others to continue the buildout, but with staffing changes, etc that hasn't yet happened. This ticket can be used to track the creation of stories for the remaining core UI components.

## Acceptance criteria
- [ ] Storybook stories are built for all components mentioned in the current Caseflow Styleguide

**Comment by leikkisa** [comment]
JC to own this PR, but we'll all try to contribute at least one storybook story (except maybe Sally).
