### ISSUE TITLE
Contested Claims | Attorney Fees | Add attorney storage in DB

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14020]
## Description
Create a table and model for storing BGS attorneys in Caseflow DB.

## Acceptance criteria
- [ ] The Caseflow Postgres DB is has a new table for BGS attorneys
- [ ] A new ActiveRecord model class is added, to facilitate querying this table from Rails

## Background/context/resources
In order to intake attorney-fee cases properly, Caseflow needs to be able to provide a list of attorneys as possible claimants.

We already cache BGS POAs (#13883) in bgs_power_of_attorneys which has about 55k records and should contain most names that Attorney Fees users need. However, those records are currently a long-term cache, populated only when the attorney is fetched for another purpose, and not unique per-attorney.

## Technical notes
This work will need to add a new table that contains one attorney per record, and a unique index on participant_id -- this suggestion is largely motivated by the performance needs of #14132.

#14294 specifies the second part of this work, which is to actually populate the table in a nightly job.

**Comment by jcq** [comment]
@nanotone Remind me... do we seem to have access to law firm as well, since that *might* be something that they want to use as a discriminator?

**Comment by nanotone** [comment]
@jcq I haven't seen any services that might provide that data, although we can certainly hope that one might pop up at some point.

**Comment by jcq** [comment]
Looks like when we're pulling data using the `find_power_of_attorneys` method, we get records corresponding to these types:
```
["POA State Organization", "POA National Organization", "POA Attorney", "POA Agent", "POA Local/Regional Organization"]
```

I assume for our purposes we want to filter to just those with `"POA Attorney"` in the `:org_type_nm` field.

**Comment by nanotone** [comment]
This could be a question for @msj0nes or @rutvigupta-design. If `POA Agent`s are humans, maybe we should include them too -- it seems better to have people who might never get selected, than to not have people who might get selected.

**Comment by rutvigupta-design** [comment]
I did some quick internet digging, and looks like power of attorney can be held by: national orgs, state orgs, attorneys, and agents (at least evidenced by [this list](http://dvs.ohio.gov/main/library/varo/resources/POA-Codes.pdf) in Ohio). 

I agree with @nanotone in that if it isn't too big of a lift, I would prefer us to include people that may not get selected. So in the scope of Attorney Fees, perhaps attorneys + agents and as the work extends out to other claimants, organizations?

**Comment by jcq** [comment]
So perhaps we sync all records returned from that service, and we can choose to filter those in the responses we give to the Add Claimant select control. That gives us flexibility to change very easily if we decide to allow them for some reason.

**Comment by leikkisa** [comment]
Breaking up into multiple tix
- Create DB table and seed data
- Creating the job
