### ISSUE TITLE
Motion to Vacate | Update 'Notify Pulac Cerullo team' Modal with BVA proposed copy

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14039]
## Description

Post-demo with BVA, the Board expressed concerns with using the term 'Pulac Cerullo' team name within the MTV workflow as their business process does not currently reflect a team with this naming convention, which may create confusion for users.

While the 'Pulac Cerullo' team name can remain visible to the team members using the Queue org to manage cases assign, the Board has requested, users external to the 'Pulac Cerullo' team should view this team as 'Litigation Support' in the UI.

This will require change for areas in the MTV flow where 'Pulac Cerullo' is mentioned. BVA has provided the copy change below. This change was reviewed and approved by Caseflow design team (Carolyn) .

## Acceptance criteria
- [ ] Update modal copy to reflect the BVA proposed copy below.
>**Notify Litigation Support of Possible Conflict of Jurisdiction**

>This case will be assigned to a team who will determine if there is a conflict of jurisdiction.  It will return to your Queue when it can be worked again.

## Background/context/resources

**Current Modal View**
Select 'Notify Pulac Cerullo Team' from Case Details page Actions Menu for modal. 

![image](https://user-images.githubusercontent.com/41164406/79759114-48977680-82ec-11ea-9c64-0080b41edbee.png)

**Comment by jcq** [comment]
## Updated Screenshots
<img width="692" alt="Screen Shot 2020-05-01 at 15 20 20" src="https://user-images.githubusercontent.com/2581274/80846083-090c3c80-8bc0-11ea-9777-f53033269f6a.png">
