### ISSUE TITLE
MTV | Make Attorney Review Hyperlink Fields Optional (?)

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#14036]
## Description
There is conflicting info regarding requirements for making hyperlink fields required (or not) on the attorney review screen. As referenced in [this comment](https://github.com/department-of-veterans-affairs/caseflow/issues/13861#issuecomment-615477873), we decided to merge the existing work and seek confirmation on whether to make changes to validation.

## Acceptance criteria
- [ ] Get final decision on if hyperlink fields should be required
- [ ] If yes, then update validation; if not, close this ticket.

## Background/context/resources
- [Comment re making it required](https://github.com/department-of-veterans-affairs/caseflow/issues/13861#issuecomment-611819105)

## Technical notes
Logic would need to be updated in [`MotionsAttorneyDisposition`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/mtv/MotionsAttorneyDisposition.jsx#L59)

**Comment by leikkisa** [comment]
We haven't gotten any confirmation or indication from the board to move forward with this or that it's a priority. We've heard to deprioritize MTV generally, so closing this ticket.
