### ISSUE TITLE
Motion to Vacate | Update Actions Menu reference from 'Pulac Cerullo' team to 'Litigation Support' team

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14038]
## Description
Post-demo with BVA, the Board expressed concerns with using the term 'Pulac Cerullo' team name within the MTV workflow as their business process does not currently reflect a team with this naming convention, which may create confusion for users. 

While the 'Pulac Cerullo' team name can remain visible to the team members using the Queue org to manage cases assign, the Board has requested, users external to the 'Pulac Cerullo' team should view this team as 'Litigation Support' in the UI. 

This will require change for areas in the MTV flow where 'Pulac Cerullo' is mentioned. 

## Acceptance criteria
- [ ] Replace 'Case Details' action menu item ' Notify Pulac Cerullo' with 
> **'Notify Litigation Support of Possible Conflict of Jurisdiction'**

## Background/context/resources

Current View

Queue 'Case Details' Actions Menu
![image](https://user-images.githubusercontent.com/41164406/79757587-48967700-82ea-11ea-8903-d58bd766dc50.png)

**Comment by jcq** [comment]
@msj0nes  @leikkisa 
Should we also update the url displayed when this is active? Right now it appends `/modal/assign_to_pulac_cerullo` — do we need to change that away from mention of Pulac Cerullo?

**Comment by jcq** [comment]
And just to be clear, this is a global change, right? Not just as it applies within an MTV workflow? (Pulac Cerullo stuff existed before we began MTV work, so we just utilized existing code where appropriate)

**Comment by leikkisa** [comment]
@jcq That's correct!

**Comment by jcq** [comment]
## Updated Screenshot
![Screen Shot 2020-05-01 at 15 50 24](https://user-images.githubusercontent.com/2581274/80847186-88e7d600-8bc3-11ea-946a-bbf6da0508bd.png)
