### ISSUE TITLE
Get stats on how documents are viewed and used in Reader

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14040]
## Description
**High-level GOAL**: Assess current use of Reader by judges and attorneys and identify improvements that will increase timely and accurate appeals decisions.

This is the first step. The intent of this ticket is to get the lay of the land and get a sense of patterns and anomalies in the data.
This ticket will help scope remaining tickets to certain appeals, users, and/or document sets.

Collect "static" info about how documents are viewed and used in Reader:
* stats on document type, categories, tags, comments
* identify correlations between doc.type and categories and tags
* stats on document source, doc.upload_date, first and last DocumentView. (Ignore assessment of individual DocumentViews for this ticket; this will be done in another ticket)
* charts of the above over time

Too challenging; excluded for now:
* group by appeal type, issue types, issue disposition, decision, ...
* presence of certain doc types per appeal type

## Acceptance criteria
- [x] Report containing statistics about document usages
- [x] Identification of a dataset to scope subsequent investigation 

## Background/context/resources
Caseflow Reader has been in operation for about 2 years. We should assess how it's been used and identify any improvements that could be made.

### DB Schema notes

Document
- category_*, description, file_number, received_at, series_id, type, upload_date, vbms_document_id
- versions, file_name, 
- series_id seems to be unique and matches with file_name
- alt_types (if from VBMS and not from eFolder), efolder_id (if from eFolder)
```ruby
fn=leg.veteran.file_number
Document.where(file_number: fn).count
docs.pluck(:received_at).tap{|dates| break [dates.min, dates.max] }
docs.pluck(:upload_date).compact.tap{|dates| break [dates.min, dates.max] }
```

Annotation
- comment, x,y, relevant date?

DocumentView
- first_viewed_at, updated_at

```ruby
docs.map(&:document_views).map(&:count).uniq
users=docs.map(&:document_views).map{|views| views.map(&:user_id)}.flatten.uniq
User.find(users).map{|u| [u.judge?, u.attorney_in_vacols?] }
```

DocumentTags
- versions

Tags
- text

**Comment by pkarman** [comment]
note the `document_views` table is pretty big. we have a ticket to re-evaluate whether we should be storing this data this way, or at all. See #12237

**Comment by hschallhorn** [comment]
Timebox to a 3!
