### ISSUE TITLE
Get stats on user's time spent reviewing documents

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14044]
## Description
Get stats on user's time spent reviewing documents during Case Review and Hearing Prep

## Acceptance criteria
- [x] Report containing stats on time spent reviewing documents

## Background/context/resources
Related tickets: #14040 and #14041

## Technical notes

Steps that involve documents (extracted from [Caseflow Metrics](https://docs.google.com/spreadsheets/d/1Q3GYUu5WGwOZErZqGIwwS4OtWIxqOWKTWxBQVcnQ9mo/edit#gid=0)):
* Judge reviews docs for hearing
  - dvs=DocumentView.where(user: judge); dvs.map{|dv| [dv.document, dv.first_viewed_at] }
  - NEED to filter DocumentViews within hearing time window (between intake and DistributionTask) of case
  - measure time between opening docs
* Judge assigns to atty (may review documents to write notes for atty)
  - NEED to filter DocumentViews within JudgeAssignTask time window (between JudgeAssignTask and AttorneyTask) of case
  - measure time between opening docs
* Atty starts reviewing docs
  - NEED to filter DocumentViews, DocumentTags, Document during AttorneyTask created and completed
  - measure time spent opening, tagging, and categorizing docs
* Atty writes draft decision (in IDT, referencing docs)
  - Is anything recorded in Caseflow when user is using IDT?
* Atty submits draft decision to judge
  - measure time of assigned duration vs actively working on case (in Caseflow)
  - measure time on_hold waiting on VLJ Support
* Judge reads draft (reviewing documents referenced by atty)
  - measure time between opening docs
* Judge ask for rewrite ...(similar to steps above)

To measure time between opening docs
* Within given relevant time window and user, 
  - use DocumentView.created_at, first_viewed_at, updated_at
  - use Document.created_at, updated_at
  - use DocumentTag.created_at, updated_at
  - group by doc.type (time spent on document)
  - return min and max timestamps
  - return tags created

**Comment by hschallhorn** [comment]
(All reports generated are strictly internal reports for the caseflow dev team to identify future development efforts)

Timebox to a 3

**Comment by yoomlam** [comment]
@hschallhorn You mentioned having a list of user types (VSOs, VLJ Support, etc.) who use Reader. Please paste it on this ticket.

**Comment by hschallhorn** [comment]
Addition org users that use reader:
```ruby
users_with_reader_role = User.where(":role = ANY(roles)", role: "Reader")
organizations_with_reader_users = OrganizationsUser.where(user: users_with_reader_role, admin: false).pluck(:organization_id)
pp Organization.where(id: organizations_with_reader_users).where.not(type: JudgeTeam.name).pluck(:type, :name).sort.unshift(["TYPE", "NAME"])
[["TYPE", "NAME"],
 ["AodTeam", "AOD"],
 ["BusinessLine", "Education"],
 ["BusinessLine", "Fiduciary"],
 ["BusinessLine", "Insurance"],
 ["BusinessLine", "National Cemetery Administration"],
 ["BusinessLine", "Pension & Survivor's Benefits"],
 ["BusinessLine", "Veterans Health Administration"],
 ["BusinessLine", "Vocational Rehabilitation and Employment"],
 ["Bva", "Board of Veterans' Appeals"],
 ["BvaDispatch", "Board Dispatch"],
 ["CaseReview", "Case Review"],
 ["Colocated", "VLJ Support Staff"],
 ["HearingAdmin", "Hearing Admin"],
 ["HearingsManagement", "Hearings Management"],
 ["LitigationSupport", "Litigation Support"],
 ["MailTeam", "Mail"],
 ["PrivacyTeam", "Privacy Team"],
 ["PulacCerullo", "Pulac-Cerullo"],
 ["QualityReview", "Quality Review"],
 ["SpecialCaseMovementTeam", "Case Movement Team"],
 ["TranscriptionTeam", "Transcription"],
 ["Translation", "Translation"]]
```

**Comment by yoomlam** [comment]
[Report](https://docs.google.com/document/d/1cD6wzNfew2ueViWAufIH1c4WsgHBzmSd-T2clZQmuzg/edit#)
