### ISSUE TITLE
Identify patterns of how documents are used

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14050]
## Description
Users can be presented with hundreds of documents to review. Is there a pattern to how the documents are reviewed?

Identify patterns of how documents are used (i.e., viewed, tagged, commented, categorized).

Patterns may involve the following:
* ordering of document views (e.g., by type or timestamp)
* time spent on document types
* characteristics of document tags and comments
* group by different contexts (e.g., VLJSupport involvement, holidays, seasonal, COVID-19)
* type of user (e.g., judge vs attorney) or other user characteristics

## Acceptance criteria
- [ ] Report containing patterns of how documents are used

## Background/context/resources
There is potential benefit in automated document organization and tagging based on document metadata. If documents can be organized based on the resulting patterns, then users can be prioritize documents that need to be reviewed to expedite appeal decisions.

**Comment by hschallhorn** [comment]
Timebox to a 3
