### ISSUE TITLE
Route Claim | Inactive Text Input

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1405]
# Description
The route claim text fields all have black borders, which makes it look like they're editable. I want to put in a saved text field that is inactive in the living style guide and make sure that it is consistent throughout all of our products. 

**Environment:**
- [ ] Production
- [x] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

## Screenshots
**_Scenario 1 - Route Claims text fields_**
1. Text box border color is Hex #5B616B

![image](https://cloud.githubusercontent.com/assets/13420618/24566949/9b76cba4-1629-11e7-9078-ae39ac4ea8a7.png)

**_Scenario 2 - Route Claims text fields_**
1. Text box border color is Hex #D6D7D9

![image](https://cloud.githubusercontent.com/assets/13420618/24566971/b0f801c8-1629-11e7-95b5-caca25c86afb.png)

@lakohl Could you take a look at this and let me know if you 👍 or 👎

**Comment by lakohl** [comment]
@gnakm I do like the clean look of the second (Hex #D6D7D9), but the USWD standards use the first pattern for filling in boxes (they don't have a pattern for pre-filled text fields). Let's discuss.

Also, when I look at the decenders, it feels like our labels are tiny bit too close to the top of the field?

**Comment by gnakm** [comment]
@lakohl Let's leave it as it is for now. This is super not urgent. I do agree that labels are too close to the text fields. I think they should be 8px distance from fields. Adding it to [style guide form fields](https://github.com/department-of-veterans-affairs/caseflow/issues/1412). 

![image](https://cloud.githubusercontent.com/assets/13420618/24673611/e9b0bb52-1946-11e7-9058-01e41382f898.png)

**Comment by gnakm** [comment]
Closing this because there is no action item.
