### ISSUE TITLE
Motion to Vacate | Address Motion to Vacate | Update Copy Instructions

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14066]
## Description
Post-demo with BVA , we received feedback around the copy instructions displayed. Caseflow design has presented two paths to move forward. 

1. Release the screen with the instructions in their current location for the pilot (with copy tweaks), then use the pilot as a way to test if this information is useful, read, or skipped

2. Redesign the page before launching the pilot and push back the pilot release date.

The Board has decided path 1 is most appropriate. Caseflow design will finalize the changes needed. 

## Acceptance criteria
- [ ] Copy instructions is updated with design changes

## Background/context/resources
Current Design
![image](https://user-images.githubusercontent.com/41164406/79985296-61cd2e00-8478-11ea-922d-f088bf34f347.png)

**Comment by rutvigupta-design** [comment]
Note from design: a new design has been sent to stakeholders, waiting for approval to proceed.

**Comment by rutvigupta-design** [comment]
Design added here. This has been de-prioritized until the Motions to Vacate pilot has been completed. 

![Address MTV _ May 2020](https://user-images.githubusercontent.com/51714306/83041528-305ef980-a006-11ea-9349-9d9639cee9b9.jpg)

**Comment by leikkisa** [comment]
We are waiting for confirmation from the stakeholder before moving forward on this. @rutvigupta-design to reach out.

**Comment by leikkisa** [comment]
We haven't gotten any confirmation or indication from the board to move forward with this or that it's a priority. We've heard to deprioritize MTV generally, so closing this ticket.
