### ISSUE TITLE
Create End Product | Increment modifier if irrelevant pending EP 170 code exists so it doesn't fail

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1406]
## Context
Only a certain subset of EP 170 labels are relevant to claim establishment (e.g., 170 Remand). We already validate for these when checking for existing EPs. However, there are additional EP 170 claim labels that may be pending on a case for a different reason, and we should still increment the modifier if these exist so the Create EP call doesn't fail.

## Story
If a veteran has a pending EP 170 with any label other than those we are already handling in Caseflow (see list below), increment the modifier value by 1 so the EP can be established. These should _not_ be handled as potential duplicates, as they are unrelated to claim establishment. 

#### EP Codes/Labels we already look for as potential duplicates:
170APPACT
170APPACTPMC
170PGAMC
170RMD
170RMDAMC
170RMDPMC
170RBVAG

## Acceptance Criteria
- Given there's a pending EP 170 [Label not considered duplicate, e.g., Notice of Disagreement] on a veteran ID, when a user arrives on the Create End Product page, the modifier field has been incremented by 1 value higher than the value of the pending EP 170.

**Comment by shanear** [comment]
closing because the AC is captured in #1281
