### ISSUE TITLE
Improve Bat Team Documentation: In Depth Training + QRG

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#14071]
## Description
The [Bat Team wiki ](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team) has a ton of information in it, which is great! But this means it's very difficult to actually use while you're on Bat Team. One potential option is to break out the Bat Team documentation into at least 2:

1. Bat Team In Depth Training: A document that engineers use to onboard initially into Bat Team
that explains all the protocols and should be reviewed every 6 months
2. Bat Team Quick Reference Guide (QRG): A document that a current Bat Team member can use to immediately identify what to do while they're on Bat Team (could include the FAQ, or possibly split the FAQ into a separate doc)

This is a suggested solution, feel free to propose something else!

## Acceptance criteria
- [ ] Update documentation: [Bat Team wiki ](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team)

## Background/context/resources
- [Bat Team wiki ](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team)
- Everything it currently links to, including:
  - [First Responder Manual](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/First-Responder-Manual)
  - [VA API Services](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/VA-API-services)
  - [Escalation Procedure](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Escalation-Procedure)

**Comment by nanotone** [comment]
I just did a quick reorganization of the Bat Team wiki. There is now a [new page](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref) in the appeals-deployment wiki that's essentially the FAQ/QRG. The intention is that this page would be bookmarked by Bat Teamers and serve as the first destination whenever anything happens, optimizing for being informative at-a-glance.

Summary of changes:
- Moved FAQ from the main Bat Team page to the new quick ref
- Added a short bulleted list to the top about production incidents. 
- Added links to every FAQ issue later down on the page
- Migrated content from Kat's hackmd on reassigning inactive judge/attorney users
- Grouped links by product/topic
- Fixed a bunch of broken links all around

Still need to do:
- Add content from (or links to) Sally's intake training for bat team

**Comment by alisan16** [comment]
The deck was updated on April 2, 2021: https://docs.google.com/presentation/d/1D7yYubzwYPc2ctBQJmUJbQM9_wqWSh4PRu_bL-POtb8/edit#slide=id.p

**Comment by alisan16** [comment]
August 2019 deck saved here: https://docs.google.com/presentation/d/1HsVN Gl6EuDf9qtsHLEwfhVKH9QFZt49vcvHdE-PJsoU/edit#slide=id.p
