### ISSUE TITLE
Styleguide component | Form fields | Text Input Error

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1408]
As a developer and designer, I want a clear and consistent way to implement text input errors so our users can clearly know when they missed an important task across our apps. 

## Acceptance Criteria
1. Verify that this is found in the living style guide there is a subsection titled `Text Input Error` under `Form Fields`
1. Verify that the description for `Text Input Error` appears underneath the title (see copy)
1. Verify that the components and sections appear beneath the description for Text Input 
1. Verify that the text input matches the one in USWDS
1. Verify that the text input has a  _Required_ text on the top right corner of the text field
1. Verify that focus state matches the one in USWDS
1. Verify that when a user does not input text in the required text box and clicks the submit button, the error shown in mock shows. 
1. Verify that text input label is 8px apart from text input field. 
1. Verify that input field will have a `margin-bottom` of 40px

## Mocks

**Text Input Default**

<img width="682" alt="screen shot 2017-04-03 at 9 12 28 am" src="https://cloud.githubusercontent.com/assets/23316107/24610725/b7baff8a-184d-11e7-9c18-39f7786c9c86.png">

**Test Input Error**
<img width="691" alt="screen shot 2017-04-03 at 9 12 35 am" src="https://cloud.githubusercontent.com/assets/23316107/24610738/c009f3e4-184d-11e7-9bd5-8d79f50499da.png">

## Copy

**Title**

Text Input Error

**Description**

Similar to the USWDS we mark fields with a “required” or “optional” label to the top fight of the form input type. Our required text is `secondary` as we’ve done research showing that this makes the demarcation more noticeable. Similarly, prompting questions have the “required” text immediately following the text.

## Related Issues
#1412 Styleguide | Form fields section overview

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the style guide 
2. Navigate to the text field error section
3. Validate the behavior based on the AC above

Screenshots: 
![sgtextfielderr](https://cloud.githubusercontent.com/assets/23038505/26011601/c3f138a0-371f-11e7-8df5-fdd19afd299d.gif)
