### ISSUE TITLE
Caseflow user status management allow search by name

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14089]
## User or job story
User story: As an admin, I need the ability to search for a user on the user status management page by their name as well as the CSS ID, so that I can locate and deactivate a user quickly.

## Acceptance criteria
- [x] users with access to the user status management page have the ability to search for a user by name and CSS ID

### Background/context
Often times the admin does not know the users CSS ID nor have access to it after the user they are attempting to deactivate has left the Board. 

### Technical notes
As the user list is extensive it may take some time for the search to populate with names. Would searching with a minimum of 4 or 5 letters help speed up populating the list?

**Comment by pkarman** [comment]
Tech note: `UserFinder` should match on name, so if (a) that class is being used and (b) it is not finding by name, we might have a bug.

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/user_finder.rb#L50

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```

#### Why 1?
- We already have a dropdown that does this. Should be able to hotswap the two components :crossed_fingers: 

#### Why 2?
- Hot swap my not be that straightforward
- Add tests

**Comment by lomky** [comment]
@araposo-tistatech this is set to merge and should go out today or tomorrow. There is a slight user-facing change in appearance and behavior, though only for System Admin users. Probably worth a release note!

**Comment by araposo-tistatech** [comment]
@lomky is there anyway to re-record the gifs you have in the PR without the URL bar included? I would like to add them to the post and would have created some myself, but looks like this change is not in demo yet.

**Comment by lomky** [comment]
@araposo-tistatech if you redeploy our echo demo it will have it now that it merged! We're past the deploy for today so this won't release until tomorrow.

**Comment by lomky** [comment]
Nevermind I found a quick way to crop it!
Before | After
 -- | --
![ezgif com-crop](https://user-images.githubusercontent.com/6129479/81715070-c3fccb80-9445-11ea-98e4-2e67cf6ded8e.gif) | ![ezgif com-crop(1)](https://user-images.githubusercontent.com/6129479/81715067-c3643500-9445-11ea-8551-8ef9461583a9.gif)
