### ISSUE TITLE
AOD Docket for Subsequent Appeals

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14085]
## User or job story
When an appellant/claimant reaches the age of 75 an AOD needs to be applied to the current and all subsequent cases/claims. If an AOD is for any other categories (weather-related, homelessness, financial distress, etc) the AOD should only apply to the current appeal/claim and not any subsequent.

## Acceptance criteria
- [ ] Only age AODs are applied on the claimant level
- [ ] All other categories (weather-related, homelessness, financial distress, etc) should apply the AOD on the appeal/claim level

### Background/context

We've found out policy on AOD. There should be an AOD motion for every case that is to be granted AOD status. In legacy cases (VACOLS), this was done by a manual flip of each case to AOD. Sometimes, after consultation, one motion caused more than one case to be granted AOD status, but only as an exception to policy. Therefore each AOD case should have a unique motion granted.

This excludes AOD for age, which is auto granted AOD status by age of the claimant for all cases associated with that claimant. 

### Resources/other links
Slack [Convo](https://dsva.slack.com/archives/CHX8FMP28/p1585927517182100) related to flagged Batteam issue.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||
5 | |||||
8 | 
```



#### Why 3?
- Investigation and understanding context

#### Why 5?
- Updating database to have aod motions have a related appeal
- Leaving in support for aod motions that were created before this change. Don't think there is a way to backfill these appeals

**Comment by hschallhorn** [comment]
Updated priority to medium as a fix for this bug has already been pushed in #14087. Let reassess if this association change is needed before prioritizing as high.

**Comment by yoomlam** [comment]
A possible solution is described in [this comment](https://github.com/department-of-veterans-affairs/caseflow/issues/14637#issuecomment-662793959).
> One solution to address #14085 is to add an `appeal_id` column to `advance_on_docket_motions` (which will allow many motions to be associated to a single appeal, an n-to-1 relationship). The exception will be age-related AOD motions, where the `appeal_id` will likely be null since age-related AOD motions are applicable to all open and subsequent appeals (setting the `appeal_id` to a single non-null value will be misleading since age-related AOD motions can apply to many appeals).

**Comment by yoomlam** [comment]
@hschallhorn If I understand correctly, we still have a problem where subsequent appeals are being incorrectly indicated as AOD due to a granted motion for a prior appeal, correct? In other words, is the only remaining work for this ticket to address the scenario I described?

**Comment by TedM-BVA** [comment]
You are correct in that we have a problem understanding the status of appeals generated after an AOD motion is granted for a common claimant.  Our understanding is that once an AOD motion is granted, this will not affect subsequently filed appeals under the same claimant.  That is expected policy, but is it reflected in the database?  Shortest version of our question: where do we find the most direct and accurate AOD status for a given appeal?

**Comment by yoomlam** [comment]
Hi @TedM-BVA!
> is it reflected in the database?

No. Currently in Caseflow, AOD motions are associated with the claimant and not with any particular appeal. 

> where do we find the most direct and accurate AOD status for a given appeal?

To determine if an appeal is AOD, Caseflow [checks if a granted AOD motion occurred after the appeal's receipt date](https://github.com/department-of-veterans-affairs/caseflow/blob/b141358f9cd3afa36f2e9c8504ecae9cc427e231/app/models/advance_on_docket_motion.rb#L22-L24). I guess this must have the understanding at the time this was implemented.

Upon completion of this ticket, non-age-related AOD motions will be associated with specific appeals. As a result, you will be able to query the AOD motions table (`advance_on_docket_motions`) to get all non-age-related AOD motions associated with a specific appeal.

**Comment by mikesanford** [comment]
Hi @yoomlam!  So, if an AOD motion is granted, all subsequent appeals are AOD'd in the database, but the AOD designation is not necessarily displayed in the UI?

**Comment by yoomlam** [comment]
Good morning @mikesanford. If an AOD motion is granted, all subsequent appeals is currently presented as AOD in the UI. Let me know if you see otherwise. Once this ticket is completed, non-age-related AOD motions will apply to a single appeal and new subsequent appeals without a granted AOD motions should not be displayed as AOD.

**Comment by yoomlam** [comment]
AOD status can be modified on an appeal by editing an AOD Motion in the Case Details page and clicking Edit under **TYPE**:
![image](https://user-images.githubusercontent.com/55255674/90560165-50650b80-e164-11ea-94da-c06656661f15.png)

Only one AOD motion regardless of 'reason' can be associated with an appeal.

**Comment by hschallhorn** [comment]
Looking into what AOD motions are currently being applied to active appeals and what we might do to link them to their proper appeals
```ruby
aod_motions = AdvanceOnDocketMotion.granted.where.not(reason: :age)
active_appeals = Appeal.active
active_claimants = Claimant.where(decision_review: active_appeals)
active_people = Person.where(participant_id: active_claimants.pluck(:participant_id))
active_aod_motions = aod_motions.where(person: active_people)
active_aod_motions.count
=> 299

aod_motion_people = Person.where(id: active_aod_motions.pluck(:person_id))
aod_motion_claimants = Claimant.where(participant_id: aod_motion_people.pluck(:participant_id))
aod_motion_appeals = Appeal.where(id: aod_motion_claimants.where(decision_review_type: Appeal.name).pluck(:decision_review_id))
aod_motion_appeals.count
=> 472

aod_motion_claimant_appeal_counts = aod_motion_people.map do |person|
  [person.id, Claimant.where(participant_id: person.participant_id, decision_review_type: Appeal.name).count]
end
aod_motion_claimant_appeal_counts.select { |id, count| count > 1 }.count
=> 108
```
So we currently have 
- 299 aod motions that could apply to 472 appeals. 
- 108 people that have a non age based aod motion granted with multiple appeals

How do we backfill these motions with the appeals they apply to?

As we previously did not associate aod motions with specific appeals, if a veteran has 2 appeals active at the board and an AOD motion had previously been granted for _one_ of them, if we do not backfill these motions with the appeal they SHOULD have been associated with, there could be appeals that are AOD that are no longer considered to be AOD by our new logic
- [ ] Should we try to update those motions with the appeal they were most likely granted for?
- [ ] How do we resolve which appeal these should be applied to if the claimant has multiple appeals that were active during that time?

**Comment by hschallhorn** [comment]
Let's pull an actual report on these appeals.
```ruby
uuids = Appeal.
  active.
  joins(claimants: :person).
  joins("LEFT OUTER JOIN advance_on_docket_motions on advance_on_docket_motions.person_id = people.id").
  where("advance_on_docket_motions.created_at > appeals.established_at").
  where("advance_on_docket_motions.granted = ?", true).
  where("advance_on_docket_motions.reason <> ?", :age).
  pluck(:uuid)
uuids.count
=> 271
```
Waiting to hear back on what information we'd like from this

**Comment by hschallhorn** [comment]
One option is to try to track down the original request in our logs to see if the request was made for this appeal. These requests come in as
```
[localhost] [ad581605-1596-4836-ba14-97a912adfc19] [localhost] [AOD_USER ] Started POST "/appeals/bce47518-3e0e-4f68-ae00-38e02d030b55/advance_on_docket_motions" for ::1 at 2020-08-24 16:55:15 -0400
[2020-08-24 16:55:15 -0400] Processing by AdvanceOnDocketMotionsController#create as JSON
[2020-08-24 16:55:15 -0400]   Parameters: {"advance_on_docket_motions"=>{"reason"=>"serious_illness", "granted"=>true}, "appeal_id"=>"bce47518-3e0e-4f68-ae00-38e02d030b55"}
```

**Comment by araposo-tistatech** [comment]
> One option is to try to track down the original request in our logs to see if the request was made for this appeal. These requests come in as
> 
> ```
> [localhost] [ad581605-1596-4836-ba14-97a912adfc19] [localhost] [AOD_USER ] Started POST "/appeals/bce47518-3e0e-4f68-ae00-38e02d030b55/advance_on_docket_motions" for ::1 at 2020-08-24 16:55:15 -0400
> [2020-08-24 16:55:15 -0400] Processing by AdvanceOnDocketMotionsController#create as JSON
> [2020-08-24 16:55:15 -0400]   Parameters: {"advance_on_docket_motions"=>{"reason"=>"serious_illness", "granted"=>true}, "appeal_id"=>"bce47518-3e0e-4f68-ae00-38e02d030b55"}
> ```

I like this idea, can we add this information to the report in Metabase? Something like the following: 

appeal id (not sure if we allow PII in Metabase) 
appellant name
array_agg
motions reason
granted

This should help us identify which appeal was granted a motion for each appellant that we can have the Board verify.

**Comment by hschallhorn** [comment]
Checking our logs to see if we can write a script to see which appeals these motions were created for. 
According to http://query.prod.appeals.va.gov/question/82, appeals with UUIDs of `258d844c-71c0-44c7-b0ea-5e9119d08296` or `1183e71a-3602-4b52-add4-5eac52231f03` could have been the appeal that spawned the AOD request on August 24, 2020 at 5:19 PM
```bash
awslogs get dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out ALL --start='24/8/2020' --end='25/8/2020' --filter-pattern='Started POST "/appeals/258d844c-71c0-44c7-b0ea-5e9119d08296/advance_on_docket_motions"'
# Nada
awslogs get dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out ALL --start='24/8/2020' --end='25/8/2020' --filter-pattern='Started POST "/appeals/1183e71a-3602-4b52-add4-5eac52231f03/advance_on_docket_motions"'
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-08a240446d5b357b7 [appeals.cf.ds.va.gov] [4991abbc-f584-43cd-935f-4fcca586dd5e] [10.247.40.41] [vacoEdwarC1 Courtney.Edwards1@va.gov] [2020-08-24 13:19:29 -0400] Started POST "/appeals/1183e71a-3602-4b52-add4-5eac52231f03/advance_on_docket_motions" for 127.0.0.1 at 2020-08-24 13:19:29 -0400
```
Ohhhhh baby

**Comment by hschallhorn** [comment]
```
AdvanceOnDocketMotion.group(:appeal_type).count
=> {nil=>1707, "Appeal"=>12}
```
Up and running!

**Comment by araposo-tistatech** [comment]
> > One option is to try to track down the original request in our logs to see if the request was made for this appeal. These requests come in as
> > ```
> > [localhost] [ad581605-1596-4836-ba14-97a912adfc19] [localhost] [AOD_USER ] Started POST "/appeals/bce47518-3e0e-4f68-ae00-38e02d030b55/advance_on_docket_motions" for ::1 at 2020-08-24 16:55:15 -0400
> > [2020-08-24 16:55:15 -0400] Processing by AdvanceOnDocketMotionsController#create as JSON
> > [2020-08-24 16:55:15 -0400]   Parameters: {"advance_on_docket_motions"=>{"reason"=>"serious_illness", "granted"=>true}, "appeal_id"=>"bce47518-3e0e-4f68-ae00-38e02d030b55"}
> > ```
> 
> I like this idea, can we add this information to the report in Metabase? Something like the following:
> 
> appeal id (not sure if we allow PII in Metabase)
> appellant name
> array_agg
> motions reason
> granted
> 
> This should help us identify which appeal was granted a motion for each appellant that we can have the Board verify.

@hschallhorn where we able to get the above information added to the report? Would like to get this out to the Board to get us answers on which appeal the AODs should be applied to.

**Comment by hschallhorn** [comment]
JUST updated  http://query.prod.appeals.va.gov/question/84

**Comment by araposo-tistatech** [comment]
@hschallhorn Mike is requesting we add the "file number" (I believe this is the docket number, but I am confirming with him) to the report so he can go through these. Is that something we can add?

**Comment by hschallhorn** [comment]
Added!

**Comment by araposo-tistatech** [comment]
@hschallhorn please see below Mike S. response on the list of appeals with AOD motions applied to multiple appeals: 

"The vase majority are appeals that were cancelled by the Clerk's office and properly redocketed. The others were ones where the Veteran simply had multiple appeals pending at the time the AOD motion was submitted. Since AOD was granted, they should retain their AOD status.

All of that said, all the appeals listed on the spreadsheet should maintain their AOD status. Leaving that status on cancelled appeals will have no practical effect as they aren't really appeals anymore."

**Comment by hschallhorn** [comment]
Let's start associating these motions with appeals!

First question, can aod motions apply to legacy appeals?

No! Here's screenshots of the "Edit" buton an aod team member would hit to create an AOD motion for an appeal. Appears only for ama appeals.

Legacy|AMA
---|---
![Screen Shot 2020-09-14 at 5 30 02 PM](https://user-images.githubusercontent.com/45575454/93140233-17ab4a00-f6b0-11ea-99ef-db47863faed1.png)|![Screen Shot 2020-09-14 at 5 29 52 PM](https://user-images.githubusercontent.com/45575454/93140234-18dc7700-f6b0-11ea-84a8-c6db0cd3ab40.png)

Code that controls this: https://github.com/department-of-veterans-affairs/caseflow/blob/3f79bdf200875a11ca6de1da71afc5bbf274e63f/client/app/queue/CaseTitleDetails.jsx#L166

Let's start by looking at appeals that are 1 to 1 with aod motions.

```ruby
motion_id_to_single_appeal_ids = Appeal.
  joins(claimants: :person).
  joins("LEFT OUTER JOIN advance_on_docket_motions ON advance_on_docket_motions.person_id = people.id").
  where("advance_on_docket_motions.created_at > appeals.established_at").
  group("advance_on_docket_motions.id").
  having("COUNT(appeals.uuid) = 1").
  pluck("advance_on_docket_motions.id, (array_agg(appeals.id))[1]")

motion_id_to_single_appeal_ids.count
=> 1587

# Matches http://query.prod.appeals.va.gov/question/93

motion_id, appeal_id = motion_id_to_single_appeal_ids.first
AdvanceOnDocketMotion.find(motion_id).update!(appeal_id: appeal_id, appeal_type: Appeal.name)
AdvanceOnDocketMotion.find(motion_id).appeal.uuid
=> "4ce40ce4-60d1-4505-b483-704b1ca5535c"

# Also matches http://query.prod.appeals.va.gov/question/93
motion_id_to_single_appeal_ids.each do |motion_id, appeal_id|
  AdvanceOnDocketMotion.find(motion_id).update!(appeal_id: appeal_id, appeal_type: Appeal.name)
end

AdvanceOnDocketMotion.where(appeal_id: nil).count
=> 177

motion_id_to_multiple_appeal_ids = Appeal.
  joins(claimants: :person).
  joins("LEFT OUTER JOIN advance_on_docket_motions ON advance_on_docket_motions.person_id = people.id").
  where("advance_on_docket_motions.created_at > appeals.established_at AND  advance_on_docket_motions.appeal_id IS NULL").
  group("advance_on_docket_motions.id").
  having("COUNT(appeals.uuid) > 1").
  pluck("advance_on_docket_motions.id, array_agg(appeals.id)").
  uniq { |_, appeal_ids| appeal_ids }

motion_id_to_multiple_appeal_ids.count
=> 173

motion_id, appeal_ids =  motion_id_to_multiple_appeal_ids.detect { |id, _| id == 84 }
motion = AdvanceOnDocketMotion.find(motion_id)
motion.update!(appeal_id: appeal_ids.shift, appeal_type: Appeal.name)
appeal_ids.each { |appeal_id| motion.dup.tap { |dupe| dupe.update!(appeal_id: appeal_id) } }

AdvanceOnDocketMotion.where(appeal_id: appeal_ids)
[#<AdvanceOnDocketMotion:0x000000000a78ba68
  id: 84,
  person_id: 1503,
  user_id: 2122,
  reason: "financial_distress",
  created_at: Tue, 28 May 2019 12:56:25 UTC +00:00,
  updated_at: Mon, 14 Sep 2020 22:11:52 UTC +00:00,
  granted: false,
  appeal_type: "Appeal",
  appeal_id: 1672>,
 #<AdvanceOnDocketMotion:0x000000000a78b838
  id: 1799,
  person_id: 1503,
  user_id: 2122,
  reason: "financial_distress",
  created_at: Mon, 14 Sep 2020 22:12:09 UTC +00:00,
  updated_at: Mon, 14 Sep 2020 22:12:09 UTC +00:00,
  granted: false,
  appeal_type: "Appeal",
  appeal_id: 2897>,
 #<AdvanceOnDocketMotion:0x000000000a78b590
  id: 1800,
  person_id: 1503,
  user_id: 2122,
  reason: "financial_distress",
  created_at: Mon, 14 Sep 2020 22:12:09 UTC +00:00,
  updated_at: Mon, 14 Sep 2020 22:12:09 UTC +00:00,
  granted: false,
  appeal_type: "Appeal",
  appeal_id: 1849>]

motion_id_to_multiple_appeal_ids.each do |motion_id, appeal_ids|
  motion = AdvanceOnDocketMotion.find(motion_id)
  motion.update!(appeal_id: appeal_ids.shift, appeal_type: Appeal.name)
  appeal_ids.each { |appeal_id| motion.dup.tap { |dupe| dupe.update!(appeal_id: appeal_id) } }
end

AdvanceOnDocketMotion.where(appeal_id: nil).count
=> 3

leftover_motions = AdvanceOnDocketMotion.where(appeal_id: nil)
leftover_motions.count
=> 3

motion = leftover_motions.first
person = motion.person
claimants = Claimant.where(participant_id: person.participant_id)
=> #<ActiveRecord::Relation []>

motion = leftover_motions.second
person = motion.person
claimants = Claimant.where(participant_id: person.participant_id)
=> #<ActiveRecord::Relation [#<..., decision_review_type: "SupplementalClaim", ...>]

motion = leftover_motions.third
=> #<..., person_id: nil, ...>
```

Down to 3 without an associated appeal. Open to deleting these as they will not affect any appeals' aod status.

**Comment by yoomlam** [comment]
I concur. They can be deleted since their `reason`s are all `nil` and they don't have any affect:
```ruby
leftover_motions.pluck(:id, :reason, :granted)
=> [[93, nil, true], [94, nil, true], [1290, nil, nil]]
```

**Comment by hschallhorn** [comment]
Noticed we have some dupes. Investigating
```ruby
dupe_appeal_ids = AdvanceOnDocketMotion.having("COUNT(appeal_id) > 1").group(:appeal_id).count.keys
dupe_appeal_ids.count
=> 27

id_and_motions = dupe_appeal_ids.map { |id| [id, AdvanceOnDocketMotion.where(appeal_id: id)] }
id_and_motion_attrs =  id_and_motions.map { |id, motions| [id, motions.pluck(:person_id, :granted, :reason)] }
id_and_uniq_motions =  id_and_motion_attrs.map { |id, motion_attrs| [id, motion_attrs.uniq.count] }.sort_by(&:second).to_h
{31548=>1,
 34934=>1,
 43588=>1,
 24833=>1,
 53223=>1,
 4184=>1,
 8530=>1,
 7592=>1,
 17852=>1,
 8932=>1,
 6392=>1,
 34344=>1,
 6829=>1,
 29421=>1,
 54563=>1,
 72484=>1,
 17984=>2,
 9977=>2,
 18821=>2,
 7994=>2,
 872=>2,
 8002=>2,
 9036=>2,
 8007=>2,
 883=>2,
 2958=>2,
 27541=>2}

# Let's delete dupes with the same attrs
uniq_motions_appeal_ids = id_and_uniq_motions.select { |_, uniq_motions_count| uniq_motions_count == 1 }.to_h.keys
uniq_motions_appeal_ids.each { |id| AdvanceOnDocketMotion.where(appeal_id: id).last.destroy! }
AdvanceOnDocketMotion.where(appeal_id: uniq_motions_appeal_ids).having("COUNT(appeal_id) > 1").group(:appeal_id).count.count
=> 0

# Lets see if these fit into the two following scenarios
# 1. One of the motions is denied while the other is granted -> Should keep the newest motion
# 2. Both of the motions are granted for the same person -> Should remove one of the motions
# 3. One of the motions is age based -> Should keep both motions as age will apply to all appeals
# 4. One of the motions is for another person -> Should keep both
dupe_appeal_ids = AdvanceOnDocketMotion.having("COUNT(appeal_id) > 1").group(:appeal_id).count.keys
dupe_appeal_ids.count
=> 11

id_and_motions = dupe_appeal_ids.map { |id| [id, AdvanceOnDocketMotion.where(appeal_id: id)] }
id_and_motion_attrs =  id_and_motions.map { |id, motions| [id, motions.pluck(:person_id, :granted, :reason)] }
id_and_motion_attrs = id_and_motion_attrs.reject { |_, motions| motions.map(&:third).any? { |reason| reason == "age" } }
id_and_uniq_motions =  id_and_motion_attrs.map { |id, motion_attrs| [id, motion_attrs.uniq.count] }.sort_by(&:second).to_h
=> {17984=>2, 7994=>2, 872=>2, 8002=>2, 8007=>2, 883=>2, 2958=>2, 27541=>2}

# 1. One of the motions is denied while the other is granted -> Should keep the newest motion
# Note, both of these went from denied -> granted so the appeals will both retain their aod status
appeals_with_deny_and_grant = id_and_motion_attrs.select { |_, motion_attrs| motion_attrs.first.first == motion_attrs.last.first && motion_attrs.first.second != motion_attrs.last.second }.to_h.keys
appeals_with_deny_and_grant.each { |id| AdvanceOnDocketMotion.order(:id).where(appeal_id: id).first.destroy! }
Appeal.where(id:  appeals_with_deny_and_grant).map(&:aod?).uniq
=> [true]

# 2. Both of the motions are granted for the same person -> Should remove all but one of the motions
appeals_with_both_granted = appeals_with_all_granted = id_and_motion_attrs.select { |_, motion_attrs| motion_attrs.map(&:first).uniq.count == 1 && motion_attrs.map(&:second).uniq.count == 1 }.to_h.keys
appeals_with_both_granted_with_motions = id_and_motions.select { |id, _| appeals_with_both_granted.include? id }
appeals_with_both_granted_with_motions.each do |id, motions|
  motions = motions.to_a
  motions.pop
  motions.each(&:destroy!)
end

dupe_appeal_ids = AdvanceOnDocketMotion.having("COUNT(appeal_id) > 1").group(:appeal_id).count.keys
dupe_appeal_ids.count
=> 1
id_and_motions = dupe_appeal_ids.map { |id| [id, AdvanceOnDocketMotion.where(appeal_id: id)] }
pp  id_and_motions.map { |id, motions| [id, motions.pluck(:person_id, :granted, :reason)] }
=> [[18821, [[117375, false, "other"], [117375, false, "age"]]]]

# 3. One of the motions is age based -> Should keep both motions as age will apply to all appeals
# Nothing to do!
```
