### ISSUE TITLE
Styleguide component | Form fields | Text Area

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1409]
As a developer and designer, I want a clear and consistent way to implement text areas a so our users can accurately input information across our apps. 

## Acceptance Criteria
1. Verify that this is found in the living style guide there is a subsection titled `Text Area` under `Form Fields`
1. Verify that the description for `Text Area` appears underneath the title (see copy)
1. Verify that the components and sections appear beneath the description for Text Area
1. Verify that the text area matches the one in USWDS
1. Verify that the text area focus matches the one in USWDS
1. Verify that text input label is 8px apart from input field. 
1. Verify that input field will have a `margin-bottom` of 40px

## Mocks

_Make sure you are logged into Invision before you click the Craft links_

**Text Area**

[Craft Link - Text Area](https://projects.invisionapp.com/d/main#/console/10592592/224823964/preview)
Yes... check out this innovative box. 

![image](https://cloud.githubusercontent.com/assets/13420618/24569259/5685a10a-1633-11e7-8ff8-095264f03a5a.png)

## Copy

**Title**

Text Area

**Description**

A text area allows multiple lines of text so that users can enter detailed and descriptive requested information. This freeform field allows users to write as much as they need to. When the message is longer than the length of the box, a scroll bar will appear on the side. 

## Related Issues

#1412 Styleguide | Form fields section overview

**Comment by mmlumba** [comment]
@gnakm what should the label be for the text area? so far I have this:
![screen shot 2017-05-10 at 9 37 21 am](https://cloud.githubusercontent.com/assets/4773320/25901278/4a0c99e2-3564-11e7-9621-86d0b92841ee.png)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the living style guide
2. Access the Text Area section 
3. Validate the copy and marginal area against the AC

Screenshots: 
<img width="1432" alt="screen shot 2017-05-11 at 9 32 15 am" src="https://cloud.githubusercontent.com/assets/23038505/25952727/72675352-362f-11e7-9b98-b3d7af38af4c.png">
