### ISSUE TITLE
Contested Claims | Attorney Fees | Add ‘Claimant not listed’ selection when attorney is not available

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14107]
## User story
As a BVA intake user, Caseflow should provide an 'Claimant not listed' option when the claimant is not available for selection. 

## Description
Part 3 of the work on the Add Claimant modal. The Add Claimant modal should include a `Claimant not listed` checkbox, which toggles the presence of an `Add notes` text box for free-text input.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [attorney_fee]
- [ ] Provide checkbox as depicted in finalized design. 
    - [ ] Populate notes field only if 'claimant not listed' checkbox is selected
- [ ] Only option in relationships is the attorney option
- [ ] Added notes get saved in Caseflow DB
- [ ] Please update the instructions copy on the main Review page as depicted in the finalized design.
- [ ] Please update the instructions copy in the modal as depicted in the finalized design.

### Designs
![Review - Selected - Not Veteran-3](https://user-images.githubusercontent.com/51714306/82713901-3b0a3f00-9c52-11ea-9f09-e4b0baefb043.jpg)

![Review - Selected - Not Veteran-4](https://user-images.githubusercontent.com/51714306/82713915-4cebe200-9c52-11ea-85b6-2052d12a5bad.jpg)

![82943052-92fcba80-9f5e-11ea-9ad2-9477325b81e2](https://user-images.githubusercontent.com/51714306/83411860-a8e70100-a3de-11ea-9c71-0d618ec4c641.jpg)

Here is [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1590168724901/e207ffed8f8654a1d454d3938459c9252eeee837) with the user flow and the [Figma Prototype](https://www.figma.com/proto/HL5muMytaEzO4Li2UJMx9E/Attorney-Fees_March-2020_RG?node-id=3117%3A0&viewport=305%2C198%2C0.06350482255220413&scaling=min-zoom). 

Be sure to touch base with @rutvigupta-design as the designs may undergo further minor changes.

## Technical notes
~~A simple database migration for adding the column to store the additional text is needed. Consider, also, whether to add a separate boolean column for the checkbox state, or to capture this "boolean-ness" in the naming of the text column, e.g. `claimant_not_found_notes`.~~

~~The new column[s] will likely go on the `intakes` table, so that it can be applicable not only to Appeals, but to HLRs and SCs as well.~~

See #14380 for related work on the data side.

## Open questions
Considerations to keep in mind, from both a design and frontend eng perspective:
- The checkbox should be clickable even if the searchable dropdown has attorney names to suggest. The user may decide that none of the (small number of) suggestions matches.
- If the typed out attorney name produces zero results, should we nudge the user to click the checkbox, **and/or** check the name for typos/variants?

**Comment by msj0nes** [comment]
# Design Target Completion Date
5/8/20

**Comment by jcq** [comment]
So just to confirm, if the user checks this field, we should unset any incorrect claimant that had been selected from the dropdown ( `setClaimant(null)` in `AddClaimantModal` )? (Note that this requires updating the validation logic in `AddClaimantModal`.)

And @rutvigupta-design, what is the design for the text of the radio button shown after submitting the modal with this "claimant not listed" option selected? Are we writing out all of the notes? Maybe just putting "Other" or something like that?

**Comment by rutvigupta-design** [comment]
@jcq please see the design of the radio button for unlisted claimants below. Did some design exploration but ultimately decided it's better for users to see the full extent of what they wrote out in case they'd like to immediately edit. Please let me know if I can further clarify! 

![Review - Selected - Contested Claimant](https://user-images.githubusercontent.com/51714306/82943052-92fcba80-9f5e-11ea-9ad2-9477325b81e2.jpg)
