### ISSUE TITLE
Styleguide component | Form fields | Character Limit

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1411]
As a developer and designer, I want a clear and consistent way to implement a character limit for form fields to help users input the right information across our apps. 

## Acceptance Criteria
1. Verify that this is found in the living style guide there is a subsection titled `Character Limit` under `Form Fields`
1. Verify that the description for `Character Limit appears underneath the title (see copy)
1. Verify that the components and sections appear beneath the description for Character Limit
1. Verify that the number count at the bottom of the left corner decreases as numbers are characters are being inserted in the box. 
1. Verify that users are unable to insert more characters once the number hits 0. 
1. Verify that text input label is 8px apart from text input field. 
1. Verify that input field will have a `margin-bottom` of 40px under character limit text. 

## Mocks

**Form Fields Character Limits**

[Craft Link - Form Fields Character Limit](https://projects.invisionapp.com/d/main#/console/10592592/224823980/preview)

![image](https://cloud.githubusercontent.com/assets/13420618/24569459/31dfcdde-1634-11e7-9107-80a0808fdec0.png)

**Behavior**

Character limit shows _after_ input 

![image](https://cloud.githubusercontent.com/assets/13420618/24569439/21233828-1634-11e7-925c-43fb5876ca3f.png)

Character limit shows 0 and prevents further typing 

![image](https://cloud.githubusercontent.com/assets/13420618/24569449/266514e6-1634-11e7-9af0-6496fd1187ac.png)

## Copy

**Title**
Character limit

**Description**
Character limits alert users of the maximum possible text input and is used to limit the amount of information a user can provide. This friction helps ensure the user is providing the appropriate information for the text input. As the user types inside the text area, the character number decreases while showing the number of characters remaining. When there are 0 characters remaining, the text box does not allow for more characters to be inserted.

## Related Issues 
#1412 Styleguide | Form fields section overview

**Comment by mmlumba** [comment]
@gnakm Is the number for character limits flexible or will it always be 2000?

**Comment by gnakm** [comment]
@mmlumba Can we keep it flexible?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the living style guide
2. Navigate to the Character Limit section
3. In the text field, max out the text field until the character limit has been reached. 
4. Validate that the behavior matches what is listed in the AC

Screenshots:
![sgcharacterlimit](https://cloud.githubusercontent.com/assets/23038505/25953383/29bd8228-3631-11e7-8da3-6cbd49e3ebab.gif)
