### ISSUE TITLE
Persistent, personal virtual VLJ room

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14110]
## User or job story
User story: As a judge, I need a personal room that I can use, so that I can discuss other cases or matters with a Representative I have another case with.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-944
