### ISSUE TITLE
Queue: Bulk Assignment Functionality All Organizations

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14124]
## User Story
As an admin user of an organization, I should have the ability to bulk assign tasks to myself or other users part of my organization, so that I can quickly and efficiently assign tasks. I should also see a task reassignment confirmation modal as well. 

## Acceptance Criteria
- [x] Enable initially for just: _orgs from ann-marie here_
- [ ] Roll out to all orgs after testing
- [x] Only admin users of organizations are can see bulk assign button
- [x] Only admin users are able to bulk assign tasks to themselves or another team member
- [x] Confirmation Banner displays on the Team cases page once the task assignment action is complete
- [x] If task assignment action cannot be completed an alert message or banner displays stating the tasks could not be assigned with reason

## Background/context
Currently users apart of the hearings branch are able to assign multiple tasks to themselves as well as other members apart of the hearings branch organization. They have the ability to assign tasks by task type or by Regional Office (optional). The number of tasks can be assigned by increments of 5 if more then 5 tasks are available for the given task type and/or RO.  

Multiple organizations at the Board have requested bulk assignment functionality. 

## Goals
Provide allllll organizations (other than judge teams) the ability to bulk assign tasks to themselves as well as other members of their organization. 

## Success criteria
The time it takes to assign a task is decreased by a certain percentage for each organization.  

## Stakeholders
All, per the Board this functionality should be available to all teams/organizations.  

## Open questions
Which organizations should have access to bulk assign tasks? All
Does the current hearings branch bulk assignment UI need to be updated? Would it depend on the organization? No, per the Board the UI design looks good and makes sense for the organizations. 

## References/Resources
Original hearings branch issue [here](https://github.com/department-of-veterans-affairs/caseflow/issues/8620#issuecomment-463414729)

### Designs and workflows

Designs for new organizations should match the current Hearings designs for consistency: 

![Hearings Bulk](https://user-images.githubusercontent.com/59883609/83435369-165c5700-a40a-11ea-98c7-f41c72261df3.png)
![Hearings Bulk Assign Modal](https://user-images.githubusercontent.com/59883609/83435381-1a887480-a40a-11ea-864d-73bd0b4e1ee7.png)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||
2 | ||||||
3 | 
5 | 
8 | 
```

Include screenshots.

#### Why 1?
- Assuming no design changes, very few changes, pulling out `can_bulk_assign?`

#### Why 2?
- Tests!

**Comment by hschallhorn** [comment]
Let's make sure we have good training materials to provide to all admins for this feature. @wturne Do you have materials for bulk assigning tasks?

**Comment by wturne** [comment]
@Hunter Schallhorn<mailto:hschallhorn@tistatech.com>

Sorry it took so long to get back to you.  Hope you're doing well and staying safe!

No, I don't have any training materials on bulk assignment of tasks.  However, if you let me know who the training is for (Mail Intake or VLJ Support Staff or etc.), I can create something.

Respectfully,

William.

________________________________

**Comment by hschallhorn** [comment]
Once this will be implemented, it will be available to all orgs that can be assigned tasks.

```
ids = Task.visible_in_queue_table_view.open.where(assigned_to_type: Organization.name).distinct.pluck(:assigned_to_id)
puts Organization.find(ids).map(&:name).sort

AOD
American Legion
American Red Cross
American Veterans
Armed Forces Services Corporation
Blinded Veterans Association
Board Dispatch
Board of Veterans' Appeals
Case Review
Disabled American Veterans
Education
Fiduciary
Fleet Reserve Association
Hearing Admin
Hearings Management
Insurance
Litigation Support
Loan Guaranty
Mail
Marine Corps League
Maryland Department of Veterans Affairs
Military Order of the Purple Heart
National Cemetery Administration
Paralyzed Veterans of America
Privacy Team
Quality Review
Transcription
Translation
VLJ Support Staff
Veterans Health Administration
Veterans of Foreign Wars
Vietnam Veterans of America
Virginia Department of Veterans Services
Vocational Rehabilitation and Employment
Wounded Warrior Project
```

**Comment by araposo-tistatech** [comment]
@wturne please see above the organizations this functionality will be available for.

**Comment by wturne** [comment]
@araposo-tistatech Will this functionality work the same way for all organizations?  If so, I'm thinking we may be able to create one QRG that specifically covers this functionality.  

cc: @Theresa1976

**Comment by araposo-tistatech** [comment]
@wturne confirming this will work the same for all organizations. I agree one QRG specifically covering this functionality should cover this.

**Comment by araposo-tistatech** [comment]
@hschallhorn below are our pilot users: 

Got our users: 
Disabled American Veteran - Roy Spicer (roy.spicer@va.gov)
American Legion - Marty Callaghan (marty.callaghan@va.gov) 
Veterans of Foreign Wars - Jeff Wishneski (Jeffrey.Wishneski@va.gov) 
Privacy Team - 
Jessie Retan (Jessie.Retan@va.gov) 
Kary Charlebois (Kary.Charlebois@va.gov)
Mail Team - Kendra Jones (Kendra.Jones5@va.gov) 
Transcription Team - Sal Ambriz (Salvador.Ambriz@va.gov) 

I'm hoping to get emails out today to get some availability to begin piloting next week.

**Comment by araposo-tistatech** [comment]
@hschallhorn I checked off the users that are ready for tomorrow at 10am EST above.

**Comment by hschallhorn** [comment]
Roy Spicer is not an admin for Disabled American Veterans and will not be able to see the bulk assign button. THOMAS WENDEL (Thomas.Wendel@va.gov) is the only admin for this VSO.

Similarly, Jeff Wishneski is not an admin for Veterans of Foreign Wars and will not be able to see the bulk assign button. There are no admins for this VSO.

We would either need to make these users admins of their organization or find someone else to demo this with

**Comment by araposo-tistatech** [comment]
@hschallhorn Looks like this was flagged with John as I see he has noted via email that Roy Spicer was added as an admin. 

Also, is there anyway (other than impersonating a user in production as that is something PMs cannot do) that I can determine if a user is an admin myself? That way I can catch this immediately in the future.

**Comment by araposo-tistatech** [comment]
@hschallhorn looks like the list of organizations that will have access to this functionality was too extensive: 

AOD
American Legion
American Red Cross
American Veterans
Armed Forces Services Corporation
Blinded Veterans Association
Board Dispatch
Board of Veterans' Appeals
Case Review
Disabled American Veterans
Education
Fiduciary
Fleet Reserve Association
Hearing Admin
Hearings Management
Insurance
Litigation Support
Loan Guaranty
Mail
Marine Corps League
Maryland Department of Veterans Affairs
Military Order of the Purple Heart
National Cemetery Administration
Paralyzed Veterans of America
Privacy Team
Quality Review
Transcription
Translation
VLJ Support Staff
Veterans Health Administration
Veterans of Foreign Wars
Vietnam Veterans of America
Virginia Department of Veterans Services
Vocational Rehabilitation and Employment
Wounded Warrior Project

During the training call we had users reporting they do not see an "Unassigned" tab and will and I noticed that NCA does not actually use Caseflow queue, but rather Intake. 

Can we get a more refined list of organizations that will actually see this functionality in their queue?

**Comment by hschallhorn** [comment]
let's find some admins!
```ruby
ids = Task.visible_in_queue_table_view.open.where(assigned_to_type: Organization.name).distinct.pluck(:assigned_to_id)
orgs =  Organization.where(id: ids).order(:name)
pp orgs.map { |org| [org.name, org.admins.map { |admin| [admin.full_name, admin.email] }.to_h] }.to_h
```

**Comment by hschallhorn** [comment]
> Can we get a more refined list of organizations that will actually see this functionality in their queue?

Looks like this list includes business lines, which do not use the standard queue

```ruby
ids = Task.visible_in_queue_table_view.open.where(assigned_to_type: Organization.name).distinct.pluck(:assigned_to_id)
orgs =  Organization.where(id: ids).where.not(type: "BusinessLine").order(:name)
pp orgs.select{ |org| org.queue_tabs.any? { |tab| tab.is_a? OrganizationUnassignedTasksTab } }.map(&:name)
["American Legion",
 "American Red Cross",
 "American Veterans",
 "AOD",
 "Armed Forces Services Corporation",
 "Blinded Veterans Association",
 "Board Dispatch",
 "Board of Veterans' Appeals",
 "Case Movement Team",
 "Case Review",
 "Disabled American Veterans",
 "Fleet Reserve Association",
 "Hearing Admin",
 "Hearings Management",
 "Litigation Support",
 "Mail",
 "Marine Corps League",
 "Maryland Department of Veterans Affairs",
 "Military Order of the Purple Heart",
 "Paralyzed Veterans of America",
 "Privacy Team",
 "Quality Review",
 "Transcription",
 "Translation",
 "Veterans of Foreign Wars",
 "Vietnam Veterans of America",
 "Virginia Department of Veterans Services",
 "VLJ Support Staff",
 "Wounded Warrior Project"]
```
Removes the following orgs:
Education
Fiduciary
Insurance
Loan Guaranty
National Cemetery Administration
Veterans Health Administration
Vocational Rehabilitation and Employment

**Comment by hschallhorn** [comment]
@araposo-tistatech This is going to be deployed tomorrow!
