### ISSUE TITLE
Create AttorneyDecisionDraftingTask

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14133]
Similar to how we have an abstracted  `JudgeTask` for all tasks that can be assigned to a judge, we should have an abstracted `AttorneyTask` for all of our attorney tasks and create a task specific to drafting a decision.

```bash
git grep ' < JudgeTask'
app/models/tasks/judge_address_motion_to_vacate_task.rb:class JudgeAddressMotionToVacateTask < JudgeTask
app/models/tasks/judge_assign_task.rb:class JudgeAssignTask < JudgeTask
app/models/tasks/judge_decision_review_task.rb:class JudgeDecisionReviewTask < JudgeTask
app/models/tasks/judge_dispatch_return_task.rb:class JudgeDispatchReturnTask < JudgeTask
app/models/tasks/judge_quality_review_task.rb:class JudgeQualityReviewTask < JudgeTask
git grep ' < AttorneyTask'
app/models/tasks/attorney_dispatch_return_task.rb:class AttorneyDispatchReturnTask < AttorneyTask
app/models/tasks/attorney_quality_review_task.rb:class AttorneyQualityReviewTask < AttorneyTask
app/models/tasks/attorney_rewrite_task.rb:class AttorneyRewriteTask < AttorneyTask
```

### AC
- [ ] Create AttorneyDecisionDraftingTask 
- [ ] Update instances of AttorneyTask to AttorneyDecisionDraftingTask in our code (See notes)
- [ ] Tasks of type "AttorneyTask" are updated to type "AttorneyDecisionDraftingTask" in prod

### Notes
Be wary of the difference between `AttorneyTask.where` and `Task.where(type: AttroneyTask.name`. The first will return all attorney subclasses as well, while the second will _only_ return what we consider the initial attorney drafting task. #12491 is a good example of how we fell prey to this in the past.

We should be sure to update our factories, move attorney tasks out of [`TASK_CLASSES_LOOKUP`](https://github.com/department-of-veterans-affairs/caseflow/blob/befe386da2803738292594f844a7f9fb87317f9e/app/controllers/tasks_controller.rb#L11-L14) and into [`additional_task_classes`](https://github.com/department-of-veterans-affairs/caseflow/blob/befe386da2803738292594f844a7f9fb87317f9e/app/controllers/tasks_controller.rb#L184-L188)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||
3 | ||||||
5 | 
8 | 
```



#### Why 3?
- knock on effects from rename
