### ISSUE TITLE
Contested Claims | Attorney Fees | Update nonrating issue categories

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14137]
## Description
The list of nonrating issue categories needs to be updated so that an Intake user can select an attorney-fee category.

## Acceptance criteria
- [ ] Place behind feature flag [attorney_fees]   **Board still deciding on whether to deploy right away**
- [ ] Compensation Nonrating issue categories updated to reflect attorney fees cases

Potentially break out (leaving here for now as optional)
- [ ] Limit applicable issue categories for attorney fees cases, if possible
  - [ ] Automatically select attorney fees

## Background/context/resources
Design:
<img width="799" src="https://user-images.githubusercontent.com/282869/80642455-830fba80-8a34-11ea-8e2d-cb034c0da6b2.png">

Confirm the final category list with @msj0nes.

Note that the design includes an initial field for `Benefit type`, although it's possible we don't need this even when intaking an appeal, because when the claimant is an attorney, Compensation may be the only applicable type. Double-check with @msj0nes about this.

## Technical notes
The list is stored in `constants/ISSUE_CATEGORIES.json`.

We don't know the full scope of issues types attorneys may be able to select in the future on contested claims.

**Comment by msj0nes** [comment]
@Sjones352 

![image](https://user-images.githubusercontent.com/41164406/81089342-3ca1dc00-8eca-11ea-9589-1fb931a9b8af.png)
