### ISSUE TITLE
Contested Claims | Attorney Fees | Add Claimant modal

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14136]
## Description
Implement a new modal that allows an Intake user to add a claimant, if the claimant is neither the veteran nor in the provided list of close relatives.

## Acceptance criteria
- [ ] Only display button behind a feature toggle: attorney_fees
- [ ] Implement Add Claimant flow as specified in design (see below)
  - [ ] Show a `+ Add Claimant` button if the claimant is specified as not the veteran
  - [ ] Show `Add Claimant` modal when the button is clicked
  - [ ] Show text explaining the attorney-only database, if user specifies not an attorney
- [ ] Add storybook story for this component (optional)
- [ ] Include screenshots of new UI in Github issue and PR

## Background/context/resources
Design:
<img width="1245" alt="Screen Shot 2020-04-29 at 13 59 53" src="https://user-images.githubusercontent.com/282869/80633967-a54f0b80-8a27-11ea-8f0d-470b264c3c92.png">

<img width="792" alt="Screen Shot 2020-04-29 at 14 00 56" src="https://user-images.githubusercontent.com/282869/80633974-a8e29280-8a27-11ea-9ef4-cc0ba12bcc87.png">

<img width="791" alt="Screen Shot 2020-04-29 at 14 01 09" src="https://user-images.githubusercontent.com/282869/80633983-ad0eb000-8a27-11ea-813d-9fe87f32d4cb.png">

## Technical notes
Additional work to hook up this modal to the backend is described in #14153.

**Comment by leikkisa** [comment]
We will be breaking out the interaction piece (fuzzy matching, saving the claimant), as a second ticket pointed at a 3.

**Comment by nanotone** [comment]
The second ticket has been [created](14153) and pointed at a 3.

**Comment by jcq** [comment]
I'm going to get started on the basics of this, but just to confirm, we are likely going to have a few design changes, right @rutvigupta-design?

**Comment by rutvigupta-design** [comment]
Yes @jcq there will likely be design changes in terms of: 
- the instructions copy
- potential removal of the radio buttons section
- the possible addition of displaying attorney data based on search selections
- displaying an alert that is displayed when no search results are found

**Comment by jcq** [comment]
## Screenshots:
![Screen Shot 2020-05-04 at 15 21 40](https://user-images.githubusercontent.com/2581274/81019514-a9aa6880-8e1b-11ea-8a17-5d4bab3e9674.png)
![Screen Shot 2020-05-04 at 15 22 39](https://user-images.githubusercontent.com/2581274/81019515-aadb9580-8e1b-11ea-928c-660c91200de6.png)
