### ISSUE TITLE
Redesign Withdraw Scheduled Hearing workflow and copy

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#14145]
## User story
As a Hearing Coordinator, I want the ability to easily withdraw a scheduled hearing, so that I can efficiently and accurately route an appeal in response to veteran requests.

## Design specs
[Link to Figma file
](https://www.figma.com/proto/h5gRVZxR2vP5gNJy92LfbV/Hearing-Task-Flows-and-Routing?node-id=146%3A18&viewport=459%2C386%2C0.02201613411307335&scaling=min-zoom)

**Workflow updates**
1. The "Withdraw hearing" option appears in the Actions menu for a scheduled hearing
2. On submitting the withdraw modal, the user remains on Case Details and a success alert displays (updated from the current state of routing the user to their individual queue page on submitting the modal)

**Copy updates**
- The withdraw modal title is `Withdraw hearing` (updated from the current state Confirm withdraw hearing)
- The withdraw modal body copy and success alert copy varies depending on how the appeal is routed on withdrawal:
  - _(1) If the appeal is Legacy with a non-colocated POA who is an organization:_
    - Modal body: The appeal will be sent to **Location 81** (Case Storage) to await distribution to a judge because the representative is not a co-located organization.
    - Success alert body: The appeal was sent to **Location 81** (Case Storage) to await distribution to a judge because the representative is not a co-located organization.
  - _(2) If the appeal is Legacy with non-colocated POA who is a private agent:_
    - Modal body: The appeal will be sent to **Location 81** (Case Storage) to await distribution to a judge because the representative is a private attorney.
    - Success alert body: The appeal was sent to **Location 81** (Case Storage) to await distribution to a judge because the representative is a private attorney.
  - _(3) If the appeal is Legacy appeal with no POA:_
    - Modal body: The appeal will be sent to **Location 81** (Case Storage) to await distribution to a judge because the [Veteran / appellant] does not have a representative.
    - Success alert body: The appeal was sent to **Location 81** (Case Storage) to await distribution to a judge because the [Veteran / appellant] does not have a representative.
  - _(4) If the appeal is Legacy with co-located / IHP-writing POA organization:_
    - Modal body: The appeal will be sent to **Location 55** for the representative to write an Informal Hearing Presentation (IHP) because they are a co-located organization.
    - Success alert body: The appeal was sent to **Location 55** for the representative to write an Informal Hearing Presentation (IHP) because they are a co-located organization.
  - _(5) If the appeal is AMA:_
    - Modal body: The appeal will be held open for a 90-day evidence submission period before distribution to a judge.
    - Success alert body: The appeal will be held open for a 90-day evidence submission period before distribution to a judge.

#### (1) Overall flow
We observed that Coordinators cannot directly withdraw a scheduled hearing. A Coordinator must first postpone the hearing on Case Details, creating a false statistic and introducing an unnecessary step that slows their work and causes confusion. After the hearing is postponed, then the option to withdraw the hearing appears in the Case Details actions menu. The copy in the 'Confirm withdraw hearing' modal misstates how the appeal will be subsequently routed (copy is addressed in #14143). After submitting the withdraw action, the Coordinator is automatically taken to their Queue list of assigned cases, instead of remaining on Case Details. ([see Requirements Gathering doc](https://docs.google.com/document/d/1SBDzWO_0P11SiZ3lBbG6ESDn7ZmBP66EojS7kIgKAo0/edit?usp=sharing))

#### (2) Specific copy
We observed that the body copy displayed on the 'Confirm withdraw hearing' modal misstates how the appeal will be subsequently routed. It currently states: `Sending to Schedule Veteran will place this case in the list of Veterans to be scheduled.` Despite the copy, the hearing request is not currently sent back to the scheduling list (that would be a postponement). Here is the current state of the withdraw modal: 
<img src="https://images.zenhubusercontent.com/5ed09e4e871c15615e5dd96f/628aefb6-396e-4335-9119-c7ddd86ac92b" width="300">

The hearing is in fact withdrawn and the appeal is routed to the next phase of the process, although we're also making improvements to this routing logic as described in issue #14129. Engineering investigation is underway to distinguish **co-located** Veteran Service Organizations (VSOs) from other types of organizations.

Some language suggested by a Hearing Coordinator ([see Requirements Gathering doc](https://docs.google.com/document/d/1SBDzWO_0P11SiZ3lBbG6ESDn7ZmBP66EojS7kIgKAo0/edit#)):  "It will send the case to be adjudicated or send the case to the VLJ queue" because it should go to location 81 in VACOLS."

### Existing Design and Content
See "Current State" screenshots section of the [ Figma file](https://www.figma.com/proto/h5gRVZxR2vP5gNJy92LfbV/Hearing-Task-Flows-and-Routing?node-id=146%3A18&viewport=459%2C386%2C0.02201613411307335&scaling=min-zoom)

### What is out of scope?
Revising the flow for editing the hearing disposition on the Daily Docket is addressed by #14127

### Open questions
- [x] Can we display different copy depending upon where the appeal will be routed? Yes, per leads sprint planning 6/11
- [x] What's the right language to describe what happens in each case outlined in issue #14129:
  - 81 / Case Storage (send the case to be adjudicated or send the case to the VLJ queue)
  - 55 / co-located VSO queue to write an informal hearing proposal (IHP) 
  - Mail / EvidenceSubmissionWindowTask for AMA cases
- [x] Depending on the length of engineering's investigation into accurately routing between co-located and non-co-located organizations, what interim language might we implement to provide Hearing Coordinators with clarity into how Caseflow is routing appeals?
  - No interim language is needed, per leads sprint planning 6/11
- [x] Does this only affect already-scheduled hearings? Yes, unscheduled hearings have the withdraw option in the Actions menu.
- [x] Does this affect both Legacy and AMA appeals? Yes, the Actions menu UI for scheduled hearings seems to be the same regardless of appeals stream.

### Success criteria
From a user experience perspective, this redesign will be successful if Hearing Coordinators can quickly and easily (1) withdraw a scheduled hearing without completing unnecessary steps; (2) understand where the appeal will be routed next and why; (3) move on to their next task in Hearings without the disruption of having to navigate back from Queue. We'll know the redesign is working if we observe that Coordinators understand the withdraw flow and copy in usability tests.

Quantitative metrics will focus on successful throughput and the ability of Coordinators to consistently withdraw scheduled hearings, which we hypothesize will result in fewer postponed hearings over time.

### Checklist
- [x] Review requirements and related tickets
- [x] Prototype copy and designs
- [x] Collect user feedback
- [x] Collect engineering feedback (at planning / refinement)
- [x] Iterate (repeat above steps as needed)
- [x] Finalize designs and update ticket

### Research Plan
'[Research Plan Google Doc](https://docs.google.com/document/d/1aqJDXGudeQBOqMKnGoXdIGdU_Tr86Po4mdvwyTks-Gs/edit?usp=sharing)'

The addition of a 'withdraw hearings' and subsequent actions to the dropdown menu were able to successfully aid the hearing coordinator participants in accurately withdrawing hearings. 

It seems that while all the coordinators had different opinions, they shared a lack of trust that Caseflow would send the cases where they were supposed to go. We decided to add in _why and where_ the case was going to the copy (along with a few other copy changes), which the coordinators found helpful.

### Related tickets
#14129 Revise hearing withdraw routing logic (engineering ticket)

**Comment by rishanava** [comment]
Updated ticket; ready for engineering review

**Comment by nicholer** [comment]
Migrated to [Jira](https://vajira.max.gov/browse/CASEFLOW-50)
