### ISSUE TITLE
Contested Claims | Attorney Fees | Hook up Add Claimant modal

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14153]
## Description
This is Part 2 of the work on the Add Claimant modal: hooking it up with the backend search names endpoint, and storing the attorney's participant ID when selected.

## Acceptance criteria
- [ ] Finish implementing Add Claimant flow as specified in design (see below)
  - [ ] Implement searchable dropdown, pulling fuzzy-matched attorney names from backend
  - [ ] Show selected attorney as non-veteran claimant in the original page, when successfully added
  - [ ] Allow selected attorney to be removed as claimant
- [ ] Use the selected attorney's participant ID for `claimant` when subsequently hitting `/intake/ID/review`
- [ ] Include screenshots of new UI in Github issue and PR

**Out of scope**
- Checkbox for `Claimant not listed` and related functionality

## Background/context/resources
Design:
![Review - Selected - Not Veteran-3](https://user-images.githubusercontent.com/51714306/82713901-3b0a3f00-9c52-11ea-9f09-e4b0baefb043.jpg)

![Review - Selected - Not Veteran-4](https://user-images.githubusercontent.com/51714306/82713915-4cebe200-9c52-11ea-85b6-2052d12a5bad.jpg)

Here is [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1590168724901/e207ffed8f8654a1d454d3938459c9252eeee837) with the user flow and the [Figma Prototype](https://www.figma.com/proto/HL5muMytaEzO4Li2UJMx9E/Attorney-Fees_March-2020_RG?node-id=3117%3A0&viewport=305%2C198%2C0.06350482255220413&scaling=min-zoom). 
## Technical notes
See #14132 for the related backend endpoint for providing attorney names based on free-text input.

Because every keystroke in the searchable drop-down can potentially kick off a backend call, it would be nice to employ a few strategies for throttling calls:
- Only fetch options if the user has entered in 3 or more non-space characters
- "Debounce" by instituting a short delay before the fetch, and suppressing earlier fetches when superseded by later keystrokes.

The searchable dropdown component is `app/components/SearchableDropdown.jsx`, and should be wired up to make async calls for a list of options (attorney names) whenever the input changes.

**Comment by rutvigupta-design** [comment]
@jcq added the new designs that are ready for dev.

**Comment by msj0nes** [comment]
Hi @jcq I'm providing sprint updates to Fred. Is this safe to close or is there additional work to be done?

**Comment by rutvigupta-design** [comment]
@jcq indicated the update to the instructions on the main Review page in #14107
