### ISSUE TITLE
NoMethodError: undefined method `complete_establish_claim_path'

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1416]
Seems like this is just a missing method of an untested, low use logic path. Need to investigate.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/139/

**Comment by slj** [comment]
Hey @shanear @mmlumba and I were looking at this yesterday - seems to me the simple fix is change the `verify_not_complete` method of `task_controller.rb` from:
```
  def verify_not_complete
    return true unless task.completed?

    redirect_to complete_establish_claim_path(task)
  end
```

to:
```
  def verify_not_complete
    return true unless task.completed?

    redirect_to perform_establish_claim_path(task)  <------ change
  end
```

And this is probably a temp solution anyway since you're refactoring Dispatch/EstablishClaim, right?

I appreciate your thoughts.

**Comment by kierachell** [comment]
**PASSED**
![precompleted](https://cloud.githubusercontent.com/assets/18075411/24986585/1552653e-1fc9-11e7-862a-1fc2c60f971d.gif)
