### ISSUE TITLE
Better error message for vets that are missing required information like SSN

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1417]
We had an instance occur where the Claims Establishment was blocked because of a vet not having an SSN. We should show a more informative error message for this. Or figure out why a vet would not have an SSN to begin with.

## Acceptance Criteria
- When a user attempts to establish a claim for a veteran with no SSN, a customized error message should show up.

### Error Message Copy:
**Header**: The EP for this claim must be created outside Caseflow.
**Body**: This veteran does not have a social security number, so their claim cannot be established in Caseflow.

Select Cancel at the bottom of the page to release this claim and proceed to process it outside of Caseflow.

## Mock
<img width="755" alt="screen shot 2017-04-13 at 5 21 35 pm" src="https://cloud.githubusercontent.com/assets/4975959/25024868/c55c7236-206d-11e7-8122-95db95df0ce9.png">

## Sentry Error
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/121/events/2972/

**Comment by shanear** [comment]
Asking @nicholasholtz to look this person up and see why they may not have an SSN

**Comment by shanear** [comment]
The mystery is finally solved. Turns out this is a bug in VBMS and these claims can only be established via the UI. We should show an error message to the user notifying them of this.
@lakohl @abbyraskin can you provide copy?

**Comment by shanear** [comment]
Added AC

**Comment by abbyraskin** [comment]
The EP for this claim must be created outside Caseflow.

This veteran does not have a social security number, so their claim cannot be established in Caseflow.

Select Cancel at the bottom of the page to release this claim and proceed to process it outside of Caseflow.

**Comment by lakohl** [comment]
mock added above

**Comment by kierachell** [comment]
Talking with Josh on Monday to recreate the data and get a real test case.

**Comment by kierachell** [comment]
@shanear 
Sample error:
https://10.236.66.249/sentry/caseflow-uat/issues/186/

**Comment by shanear** [comment]
@kierachell That is a different error. This is just when a vet has no SSN. They still have a file number and there record can still be found. We haven't experienced an error of that nature in prod.

**Comment by shanear** [comment]
@kierachell see the error posted in the issue description

**Comment by kierachell** [comment]
**PASSED**

Found one finally...
