### ISSUE TITLE
Update Copy in CM Actions Drop down

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14182]
## Description
Please update the "Special Case Movement: Advance to Judge" copy to "Case Movement: Advance to Judge" in the Actions drop down for an undistributed case. The only users that see this option is Case Movement users. Copy resides [here](https://github.com/department-of-veterans-affairs/caseflow/blob/7f1754a1599e1047dc545c3b9c1c6f3dc2afece1/client/constants/TASK_ACTIONS.json#L168) 

## Acceptance criteria
- [ ] Update documentation: [link]

## Background/context/resources
We are no longer using the word "special" for this functionality and the Board has requested that language be removed.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||||||
2 | 
3 | 
5 | 
8 | 
```


#### Why 1?
- Change them words! :tada:

**Comment by hschallhorn** [comment]
We feel that the Case Movement: prefix is uneeded. Agree/disagree? Any other thoughts?

**Comment by araposo-tistatech** [comment]
@geronimoramos or @RyanRoyUX ensuring you see this one as it is pretty simple for Case Movement. Would like to include it in the next sprint.

**Comment by geronimoramos** [comment]
To clarify:

- Is this implemented yet?
- And is this where it would live? Signed in as a CM user and on a case that has an AssignTask?
![advance to judge](https://user-images.githubusercontent.com/49766982/81839169-097bd000-94fc-11ea-92ba-2b30d09c2547.gif)

**Comment by hschallhorn** [comment]
> Is this implemented yet?
Yes!
> And is this where it would live?
Sign is as a CM user and search for a case with a vet id of 321321321. There should be a "Not Distributed" case. This is where a CM user will see a task dropdown for "Advance to judge".
https://www.caseflowdemo.com/queue/appeals/b768f744-c430-4e5e-822c-a4945f752340
![Screen Shot 2020-05-13 at 12 32 44 PM](https://user-images.githubusercontent.com/45575454/81839689-e100cf80-9515-11ea-8956-417dde8553fa.png)
