### ISSUE TITLE
Intake | Report | PIF-related End Product data

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14183]
## Description
When establishing end products, for each claim type (030 and 040), we also use a modifier. There can be 10 modifiers in use per veteran and per claim type at a given time.  One veteran can have 10 030 claims, using modifiers from 030, 031... 039.  While the claim is active, the modifier is in use.  When the claim is cancelled or cleared, the modifier is supposed to be released so that it can be used on another claim.

Releasing these modifiers happens through a nightly sync job in an external system. There has been a bug in that sync job for releasing modifiers if the claim was manually closed in Share (another external system).

This leads us to try establishing claims with modifiers that are still locked, but we think they're available because they were cleared or cancelled more than a day ago.

The modifiers we use are connected to something called PIFs. This ticket is to try to determine which ones need to be manually cleaned up so that we can use them again.

## Acceptance criteria
- [ ] For the veterans in the linked spreadsheet below, create a report of all of their 030 and 040 end products related to the provided list. Fields to include:
  - [x] end product establishment ID
  - [x] reference_id (claim_id)
  - [x] claim type code (e.g. 030HLRR)
  - [x] status (e.g. CLR, CAN)
  - [ ] veteran participant ID
  - [x] last_action_date (last_synced_at in our EndProductEstablishment table)
  - [x] claim_date
- [x] Dates are converted to strings
- [ ] In the spreadsheet, add a README tab to document a brief description, the date pulled, the person who pulled the data, and the queries used

## Spreadsheet
Here is [a link to a Google spreadsheet](https://docs.google.com/spreadsheets/d/1C5zdDKem22BiFt6JrspcFFJQrcwPZEVPgh9qYbg88Wk/edit#gid=0) that can be used for putting the data.

## Out of scope
There are 030 and 040 claims established outside of Caseflow that we don't have saved in our database.  Let's exclude these from this initial report, however we may want to grab those in the future too. BGS calls are slower so it'll be good to make a practice run.

## Background/context/resources
We will be cross referencing this with a report provided by Martin Menchey. This report currently includes file numbers, so first we'll need to convert that to not include PII.

## Technical notes
TBD

**Comment by wdrougas-tista** [comment]
Hi Sally - When looking at end products that meet the modifier qualification, these objects do not have end product establishment Ids or veteran participant Ids. I see these on end product establishments but not end products.
