### ISSUE TITLE
Update previous distributed case when sending a case back to the distribution pool

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14180]
As [discovered](https://dsva.slack.com/archives/CQCUMFA0H/p1588346839015500?thread_ts=1588346818.015300&cid=CQCUMFA0H) when sending a case back to distribution in our [bulk reassign logic](https://github.com/department-of-veterans-affairs/caseflow/blob/181719c9021f86c63ce7736db413b05234c3b75d/app/workflows/bulk_task_reassignment.rb#L186-L189), we are missing a step and generating an error. As there is a unique requirement on the case id in DistributedCase, we need to update the previous distributed case case id when sending appeals back to the distribution pool.

### AC
- [ ] Add `DistributedCase.find_by(case_id: task.appeal.uuid).update!(case_id: "#{task.appeal.uuid}-#{Time.zone.now}")` to [`reassign_judge_assign_tasks`](https://github.com/department-of-veterans-affairs/caseflow/blob/181719c9021f86c63ce7736db413b05234c3b75d/app/workflows/bulk_task_reassignment.rb#L188)
- [ ] Add helper function to find all distributed cases by case_id `.where("case_id LIKE ?", "%#{case_id}%")`

**Comment by hschallhorn** [comment]
@pkarman This would be yet another place were we sidestep the unique requirement of case_id on distributed cases. Should we maybe update this to uniq on the combination of case id and task id rather than mucking with the case id on previous distributed cases? Other thoughts?

**Comment by pkarman** [comment]
@hschallhorn agreed that the constraint of "unique except for these situations" is not really a valid unique constraint.

I'm not sure if tying it to the task id helps though, since that would (I would imagine) be so sparsely populated as to make the unique constraint pretty meaningless. Unless we are currently attempting re-distribution on the same task and want to prevent that?

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||
2 | |||||
3 | 
5 | 
8 | 
```

Maybe add more context to amended distributed case case_id to indicate that is was due to bulk talk reassignment.


#### Why 1?
- One line insertion

#### Why 2?
- add test
