### ISSUE TITLE
Mysterious React on Rails javascript errors

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1418]
Lots of js errors rolled in today. No clue what the effect, or what's causing them.

They all appear to have happened on the same task. Probably worth looking into whatever is happening with that task.

```
TypeError

ReactOnRails encountered an error while rendering component: BaseContainer.
Original message: Unable to get property 'page' of undefined or null reference
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/137/events/2950/

**Comment by mmlumba** [comment]
@shanear Could it be possible that this claim has no decision documents? The error reminds me of something I'd see often when React tabs fail to render. In Dispatch when a decision only has one document, `page[0]` renders the first (and only) document available.

**Comment by joofsh** [comment]
Perhaps we should more gracefully handle this "bad state" where somehow a task gets in to the prepared state despite not having a decision.  

At the very least, we can show them an warning/error alert that no decision exists and to cancel out of the task

CC @shanear @mmlumba

**Comment by mmlumba** [comment]
@joofsh and I were working on this issue and we added a "state" in which a decision has no document:
<img width="1280" alt="screen shot 2017-04-12 at 1 53 51 pm" src="https://cloud.githubusercontent.com/assets/4773320/24973176/deef5200-1f8b-11e7-9152-5abde901ff77.png">

@lakohl @gnakm Could you create a mock for the copy/style that should be used for this scenario?

**Comment by lakohl** [comment]
@mmlumba I will!

**Comment by mmlumba** [comment]
@lakohl upon further discussion @shanear and I concluded that the error should notify the user that the task has no decisions (or the decisions could not be loaded), and that the user should cancel out of the task

**Comment by lakohl** [comment]
If there is no decision in VBMS the case should never be picked up by Caseflow. So this scenario would cover a scenario when the decision could not be uploaded. I agree let's use an error message (red bar) to indicate this.

**Comment by mmlumba** [comment]
<img width="980" alt="screen shot 2017-04-17 at 11 00 34 am" src="https://cloud.githubusercontent.com/assets/4773320/25092779/25ef2e80-235d-11e7-9dba-81811b334322.png">
This is the more "error-y" message....please specify styles and copy as necessary

**Comment by lakohl** [comment]
@mmlumba wouldn't the .pdf viewer load even if the document fails to load?
I updated the error message to the following:
> Line 1: Unable to load decision document
> Line 2: We were unable to load the decision for the this claim. Please select Cancel below and process it outside of Caseflow.

@avrildavid could you take a look^^? thx

<img width="704" alt="screen shot 2017-04-17 at 12 00 39 pm" src="https://cloud.githubusercontent.com/assets/4975959/25094559/be79f222-2365-11e7-8a97-56e24b1285cd.png">

**Comment by mmlumba** [comment]
@lakohl Is this mock flexible even if the PDF viewer doesn't show up? I'm not sure that the PDF viewer would load if the document doesn't load.

**Comment by lakohl** [comment]
@mmlumba doesn't the .pdf viewer load first and then the document?

**Comment by shanear** [comment]
There are a lot of ways to handle this and we need to go back to the drawing board to decide what to do.

**Comment by lakohl** [comment]
@mmlumba @shanear is this still an issue, or can we close this?

**Comment by mmlumba** [comment]
When I was still working on this @shanear mentioned this is an extreme edge case. I think we can close this.
