### ISSUE TITLE
INTERNAL TESTING ONLY | Missing Ratings | Mitigation 2 | Removing 'Edit Issues' Rating Filter 

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14192]
## User or job story
User story: As a [user], I need [x], so that [y]
Job story: When a [user] does [x], they need [y], so that [z]

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by msj0nes** [comment]
# Test Cases 

**Case**: https://appeals.cf.ds.va.gov/supplemental_claims/42df2938-201a-4e3f-9caa-0088f145897c/edit
**Issue reported**: The 2 contentions that need to be add are (1 )radiculopathy of the femoral nerve, left lower extremity (2) radiculopathy of the femoral nerve, right lower extremity

**Current Production View - VBA CA User**
![image](https://user-images.githubusercontent.com/41164406/81116906-2f99e280-8ef4-11ea-80ba-b2165ba90345.png)

**'Feature Flag' Filter Removal View**
![image](https://user-images.githubusercontent.com/41164406/81117085-869fb780-8ef4-11ea-8618-63ec6f80c6d2.png)


**Case**
**Current Production View - VBA CA User**
**'Feature Flag' Filter Removal View**

**Comment by msj0nes** [comment]
https://appeals.cf.ds.va.gov/supplemental_claims/73613305/edit
https://appeals.cf.ds.va.gov/supplemental_claims/73741063/edit

**Comment by msj0nes** [comment]
Case: https://appeals.cf.ds.va.gov/supplemental_claims/73741063/edit 
Unidentified: Tinnitus

**Comment by leikkisa** [comment]
Adding a link to a spreadsheet with additional analysis:
[Contestable issue comparison](https://docs.google.com/spreadsheets/d/1h5vByO7htBn5uyHujqmZ-C4IvO9FxErtlN92saUoMl4/edit#gid=0)
