### ISSUE TITLE
VACOLS sets the certification date, even if the user doesn't complete Caseflow

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#142]
Steps to reproduce:

1. Launch RO VACOLS
1. Enter a veteran ID that is ready to be certified
1. Click *Update Appeal*
1. Click *Complete Form 8*
1. Choose the VBMS option, then click *Certify*
1. Follow prompts to let Caseflow launch
1. Close Caseflow without completing anything
1. From RO VACOLS, enter the same veteran ID
1. Click *Update Appeal*

Expected:

*Complete Form 8* button is still clickable and the certification date is not set.

Actual:

*Complete Form 8* button is disabled and a certification date has been set prematurely.

**Comment by plusjeff** [comment]
@JedWagner @gmorgana-va : After our chat today, sending this over to Jed.

The ideal behavior is to have VACOLS *not* set the cert date or mail dates for electronic cases during the certification process (Complete Form 8 screens). Caseflow will set them upon successful completion.

After this is completed, it also means that we don't need to clear `BRIEFF.BF41STAT` and the `BRIEFF.BFDM*` fields.

**Comment by plusjeff** [comment]
Change of direction on the solution. (These scenarios only apply to electronic cases)

For the pilot:

- VACOLS will continue to set the certification date, and BFDM* fields
- Caseflow will override these dates (which will likely be the same), but will also set the BFDCERTTOOL field
- Caseflow will allow the user to mark a case as not certifiable, and clear these dates. BFCERTTOOL date will still be set.
- VACOLS will have a report that detects cases that have a certification date, but not a BFDCERTTOOL date for Caseflow enabled ROs

Full rollout:

- VACOLS will not set the certification date, but will set a new field that will indicate that it sent a case to Caseflow
- Caseflow will be responsible for setting certification date, BFDCERTTOOL, and BFDM* fields. It will replace or update the status applied by VACOLS that something was sent to Caseflow to indicate that a case either was certified successfully or marked as uncertifiable
- There will be a report to indicate cases that were sent to Caseflow, but not certified, per RO

@JedWagner and @gmorgana-va : Let me know if I got any of these wrong, or missed a detail. (Meant to add this yesterday, but got busy and may have forgotten something between then and now)

**Comment by plusjeff** [comment]
Taggin' @paultag for FYI

**Comment by paultag** [comment]
Ah, Caseflow was configured to *not* set the cert data when opening -- we hit a bunch of issues during initial user testing, so Jed made a change to not set the cert data when opening caseflow
