### ISSUE TITLE
Case Movement_Non-Blocking Tasks | Screenreader does not interact with actions modal

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14212]
## Description
Screenreader does not interact with actions modal when it is active

## Acceptance criteria
- [ ] Screenreader reads modal as first "component" rather than last.

## Background/context/resources
![Screenreader issue](https://user-images.githubusercontent.com/59883609/81310459-16a74380-9052-11ea-9ae9-44e53543bede.gif)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | ||||||||
5 | |||
8 | 
```

Modal can be interacted with via the screen reader but not until user tabs all the way to the last component.
Could this be a change to how all modals appear in caseflow? We think that this problem occurs with this modal all the time.

May need to add an ARIA hint to make the modal the focal area (`aria-modal=true`). This may be able to be added in QueueApp wrapper for all queue modals.  https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

#### Why 3?
- While this could be a quick fix, digging into how screen readers determine order or what aria semantics to use will take some time
- There _must_ be a best practice for this, right?!?

#### Why 5?
- Tab ordering is notoriously tricky, with many 'wrong' fixes.

**Comment by ajspotts** [comment]
Since #14321 we have replaced the offending `AssignWidget` with `AssignToAttorneyWidget` which means we no longer return the modal in the issues description's gif.  The new modal seems to work correctly with screenreader:

![ezgif com-video-to-gif1](https://user-images.githubusercontent.com/18618189/83048846-3c53b700-a018-11ea-90ca-afb50e2090e9.gif)
