### ISSUE TITLE
Case Movement_Non-Blocking Tasks | Assign Task Modal Selections Persist

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14213]
## Description
If a selection is made on the assign/reassign task modal for an attorney the selections remain persistent even after canceling out of the modal or assigning/reassigning the case to another user

## Acceptance criteria
- [ ] Modal clears after canceling out of the modal or assigning/reassigning the task. 

### When cancelling out of modal
1. Attempt to assign a case to an attorney by selecting a user from the drop down
1. Hit cancel or "x" in
1. Click back into "Assign to attorney"
1. See name is persisted
### After assigning
1. Assign a case to an attorney by selecting a user from the drop down and hitting submit.
1. Hit the back button without refreshing
1. Attempt to assign a case to an attorney again from case details
1. See name is persisted

## Background/context/resources
Bug located during CM Dogfooding
Check the [dogfooding google doc](https://docs.google.com/document/d/1JbCt-TYW3wmLDpFbLoxFxMeX8YAlUauq3viaJm_A_J4/edit?usp=sharing) for screenshots

## Technical notes
Could add the clearing of state changes to close handler.

## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81325338-32b4e000-9066-11ea-891a-49c87c45fa00.png)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | ||||||||
3 | ||
5 | 
8 | 
```

Probably using the `QueueFlowModal`, possibly invoked via `QueueApp`. Should clear selections on "cancel" or hitting "x" in top right corner.

#### Why 1?
- Clear state selections on cancel


#### Why 2?
- Putting a state problem as a 1 has never worked before this
- Could be tricky to know when "x" is hit
