### ISSUE TITLE
Case Movement_Non-Blocking Tasks | Display error when assigning/reassigning a task is unsuccessful

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14216]
## Description
When an assign/reassign task is unsuccessful there should be an error indicating the action was unsuccessful within the assignment modal. This was found when assigning a legacy case to an attorney.

## Acceptance criteria
- [ ] If the assign/reassign action is unsuccessful display an error within the modal

## Background/context/resources
Currently if the action is unsuccessful the user is dropped into their queue and a success banner does not display. 

Check the [dogfooding google doc](https://docs.google.com/document/d/1JbCt-TYW3wmLDpFbLoxFxMeX8YAlUauq3viaJm_A_J4/edit?usp=sharing) for screenshots

## Technical notes

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||||||||
3 | |||
5 | 
8 | 
```

Keep modal open to allow user to fix error.

#### Why 1?
- Show error to user

#### Why 2?
- Always a little worried about VACOLS interaction adding complexity

#### Why 3?
- Unsure why this specific modal does not handle the error. Could require a lot of refactoring
- Could be some redux fun in there
