### ISSUE TITLE
Case Movement_Non-Blocking Tasks | No Sort Order in the Assign Case to Judge Modal Dropdown options

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14215]
## Description
The dropdown options when assigning a case to a judge are not in any particular order. They should be alphabetized by first name for ease when searching for a user. 

## Acceptance criteria
- [ ] Alphabetize judge and attorney list dropdown by first name in the assign and reassign task modal

## Background/context/resources
Bug located during CM dogfooding
Check the [dogfooding google doc](https://docs.google.com/document/d/1JbCt-TYW3wmLDpFbLoxFxMeX8YAlUauq3viaJm_A_J4/edit?usp=sharing) for screenshots

## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81325023-c89c3b00-9065-11ea-8bf9-46d83f76267e.png)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||
2 | ||||
3 | 
5 | 
8 | 
```

Benchmark this sorting on the active record vs array
Sort on how it currently displays
Do for Judge and Attorney lists on assigning/reassign
If we do it on the backend, it should hit every judge/atty dropdown.

#### Why 1?
- Sort data we already have. 
- Not too many items (dozens-hundreds?)
- Could be a simple .order(:full_name) where we query users

#### Why 2?
- General uncertainty
