### ISSUE TITLE
Case Movement_Non-Blocking Tasks | Assigned To Field Not Displaying Correct User

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14214]
## Description
The Assigned To field should display the correct user ID on the search cases page

## Acceptance criteria
- [ ] The assigned to field on the search cases page displays the correct user assigned to the case

## Background/context/resources
During Dogfooding: Assigning a case to an judge (Legacy), reassigning to Burnham assigned case to ID4 instead of CSS_ID29 when searching the case again
Check the [dogfooding google doc](https://docs.google.com/document/d/1JbCt-TYW3wmLDpFbLoxFxMeX8YAlUauq3viaJm_A_J4/edit?usp=sharing) for screenshots

## Technical notes
Reproduce before digging into. Hunter believes that this is due to being unable to assign legacy cases in demo and the lack of an error shown when this occurs. This would leave "Assigned to" unchanged in case search.

## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81325124-ecf81780-9065-11ea-98bc-f3b27c3bcd0e.png)

**Comment by hschallhorn** [comment]
Timeboxing to a 2! Could be an issue with the assigned to label or a non refreshed appeal in redux.

**Comment by lomky** [comment]
Could not replicate. Okay to close @araposo-tistatech ?

![ID changes](https://user-images.githubusercontent.com/6129479/82488604-2bea8c00-9aae-11ea-841f-a06428d558c1.gif)
