### ISSUE TITLE
Case Movement_Non-Blocking Tasks | Assign/Reassign Case to Attorney Banner Inconsistency

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14217]
## Description
The success banner when a case is assigned/reassigned to an attorney should display the same copy as assigning/reassigning a case to a judge

## Acceptance criteria
- [ ] Attorney assign/reassigning displays the following copy in the success banner "Task Assigned To {User} 

## Background/context/resources
Located during CM Dogfooding
Check the [dogfooding google doc](https://docs.google.com/document/d/1JbCt-TYW3wmLDpFbLoxFxMeX8YAlUauq3viaJm_A_J4/edit?usp=sharing) for screenshots
## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81324824-83780900-9065-11ea-9c58-e878d8bf7115.png)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||||||
2 | 
3 | 
5 | 
8 | 
```

#### Why 1?
- Updating text
