### ISSUE TITLE
Case Movement_Non-Blocking Tasks | Make assign/reassign modals consistent

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14210]
## Description
Currently the assign and reassign modals are inconsistent between routing the task to an attorney or judge. 

These should be consistent in copy. The attorney assign/reassign modal should include an instructions field as well. 

## Acceptance criteria
- [ ] Copy on the assign/reassign modals are consistent
- [ ] Instructions field is included in the attorney assign/reassign modal
- [ ] Validation errors occur on the modal itself rather than an alert

## Background/context/resources
Bug found during dogfooding CM (moving unblocked tasks) functionality. 
Check the [dogfooding google doc](https://docs.google.com/document/d/1JbCt-TYW3wmLDpFbLoxFxMeX8YAlUauq3viaJm_A_J4/edit?usp=sharing) for screenshots
## Technical notes
Per Hunter, we may be able to combine the modals to ensure they are consistent. 

## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81325527-7c052f80-9066-11ea-8bf1-89ea2db145cb.png)

![image](https://user-images.githubusercontent.com/59883609/81325617-9f2fdf00-9066-11ea-967f-008a4edae917.png)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||||||
5 | ||
8 | 
```

Make atty assign modal match the judge assign modal. Make 2nd screenshot look like the 1st.
Improve reuse of modal as much as possible.

#### Why 2?
- Quick fixes that are able to be pulled from other instances of modals

#### Why 3?
- a couple relatively straightforward changes, affects tests
- update tests

#### Why 5?
- Attempting to create grand unified assign/reassign modal may send us into the weeds.
