### ISSUE TITLE
Apply VACOLS Merge Actions in Caseflow

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14220]
## User or job story
User story: As a Hearing Management Branch member, I need Caseflow to merge Legacy appeals like VACOLS by routing them to [x], so that I don't schedule a hearing for an appeal that has already been heard in conjunction with another appeal.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Background/context
Merge Actions for legacy cases created in VACOLS don't register in Caseflow. With a Merge Action a VLJ will hear all appeals in one hearing. When an appeal is merged into one docket number in VACOLS but there are multiples for that Veteran remaining in Caseflow, Hearing Coordinators are still able to schedule hearings for remaining appeals, even if they have been resolved together in a single hearing.

### Open questions
- What is the intended user / task flow for merging in Caseflow, and what resulting design work is needed? Is merge an action performed by the Judge when they decide to hear two hearing requests at once, therefore shifting the burden from the Hearing Coordinator?
- Does a Merge Action affect anything else in Caseflow, or is it only for merged hearing requests?
- How are Merge Actions represented?
- How would we fetch this info from VACOLS?
- Can AMA appeals be merged? [Legacy can]
- Where do these need to be routed to?

**Comment by hschallhorn** [comment]
Other types of appeals can be merged in vacols: https://dsva.slack.com/archives/CHX8FMP28/p1592600856091300

**Comment by lund5000** [comment]
If a Veteran has multiple pending appeals and has a hearing held for just one of them, at the hearing the VLJ might decide to hear everything. Afterwards all the heard appeals have to be merged into one big appeal in VACOLS. According to Mike Sanford this only happens from time to time, so while complicated and time-consuming it's relatively low impact.

This is complicated by the fact that only a handful of people can merge appeals. Once you merge in VACOLS you lose the old ones and it's nearly impossible to get them back, making this workflow a higher risk to integrate with or replace entirely.

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-1657
