### ISSUE TITLE
Enabling/Disabling Linting Rules 

### ISSUE THREAD

**Issue by ariperez-gov** [department-of-veterans-affairs/caseflow#1422]
There are often situations where the best option may be disabling a linting rule.  What is the process prior to enabling or disabling a rule?

Example: 
ESLint - Pluggable JavaScript linter

http://eslint.org/docs/rules/no-prototype-builtins

**Comment by shanear** [comment]
I say bring it up in appeals-engineering and get the thumbs up from ppl

**Comment by shanear** [comment]
Also, that lint rule seems fine. There is a work around. Why do you want to remove it?

**Comment by ariperez-gov** [comment]
Bringing it up in #appeals-engineering can just be the process for now. 

It was just really ugly code and @amprokop also recommended turning it off.  As of today it's less relevant as we are writing the code in a different manner.

**Comment by joofsh** [comment]
@ariperez for what it's worth, we've been slowly disabling/enabling rules we dislike as they come up.  They are very much fluid at the moment. Posting them in #appeals-engineering is the best way to get feedback
