### ISSUE TITLE
Use proper reassign params when reassigning an attorney task

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14225]
When we reassign a task, we typically cancel the original task and  open a new one to preserve a record of the previous assignee. This is only different for attorneys, where we update the assignee of the original task. This is due to us not providing [reassign params](https://github.com/department-of-veterans-affairs/caseflow/blob/0ec98c06bdf3d76d2059f4e94c858b90d3c12eb9/client/app/queue/AssignToView.jsx#L126-L134), but [update params](https://github.com/department-of-veterans-affairs/caseflow/blob/b141358f9cd3afa36f2e9c8504ecae9cc427e231/client/app/queue/QueueActions.js#L486-L493)

### Task trees

<table>
  <tr>
    <th></th>
    <th>Before reassign</th>
    <th>After reassign</th>
  </tr>
  <tr>
    <td>Current</td>
    <td>
      <pre>
Appeal 689 (evidence_submission)   STATUS   ASGN_TO
JudgeDecisionReviewTask            on_hold  BVAAABSHIRE
└── AttorneyTask                   assigned BVAEERDMAN
    </td>
    <td>
      <pre>
Appeal 689 (evidence_submission)   STATUS   ASGN_TO
JudgeDecisionReviewTask            on_hold  BVAAABSHIRE
└── AttorneyTask                   assigned BVACASPER1
      </pre>
    </td>
  </tr>
  <tr>
    <td>Intended</td>
    <td>
      <pre>
Appeal 689 (evidence_submission)   STATUS   ASGN_TO
JudgeDecisionReviewTask            on_hold  BVAAABSHIRE
└── AttorneyTask                   assigned BVAEERDMAN
      </pre>
    </td>
    <td>
      <pre>
Appeal 689 (evidence_submission)   STATUS   ASGN_TO
JudgeDecisionReviewTask            on_hold  BVAAABSHIRE
├── AttorneyTask                   cancelled BVAEERDMAN
└── AttorneyTask                   assigned BVACASPER1
      </pre>
    </td>
  </tr>
</table>

### AC
- [ ] Reassigning an attorney task cancels the original task and creates a new one

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||
2 | ||||||||
3 | |
5 | 
8 | 
```

Add a sentry alert to the Queue channel if we every try to Update the 'assigned_to' on any task (we should be cancelling and making anew). Might be in the task.update function, or as a hook as needed.

#### Why 1?
- Fix the call!

#### Why 2?
- tests affected?
- add sentry alert

#### Why 3?
- Add tests

**Comment by hschallhorn** [comment]
Closed in #14452
