### ISSUE TITLE
Searching for a Veteran's appeals using Veteran ID should display cancelled appeals

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14221]
## Description
When a user searches for a Veterans cases using their Veteran ID and not the docket ID, etc. the cancelled appeal should still display in the search results.

## Acceptance criteria
- [ ] Cancelled appeals always show in search results
  - [ ] Cancelled appeals appear in search results when searching via the Veteran ID 
  - [ ] Cancelled appeals appear in search results when searching via the docket ID

## Background/context/resources
https://appeals.cf.ds.va.gov/queue/appeals/5a3c20c5-eb38-42ac-9278-ac600f94d4ec - Completely disappeared from Caseflow after it was deleted. (I looked into this myself and I want to specify that the user is searching using the Veterans ID and the deleted appeal does not display in the cases found list)

https://appeals.cf.ds.va.gov/search?veteran_ids=421632 - Deleted appeal (cancelled one) is not displaying in search results.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||||||||
3 | |||
5 | 
8 | 
```

#### Why 1?
- might just be changing a scope or query

#### Why 2?
- Wariness

#### Why 3?
- Seems like it could be a specific issue with these appeals and not a caseflow related bug (editing vet data in vacols, etc.)

**Comment by lomky** [comment]
Implemented as requested for _Appeals_ - no affect on other Decision Reviews!
