### ISSUE TITLE
Cannot read property 'id' of undefined in EvaluateDecisionView

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14224]
[Cannot read property 'id' of undefined](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10177/?referrer=webhooks_plugin)
_./app/queue/caseEvaluation/EvaluateDecisionView.jsx in nextStepHook at line 128:91_
`attorney_id: appeal.isLegacyAppeal ? task.assignedBy.pgId : appeal.assignedAttorney.id,`

Breadcrumbs don't seem to reveal anything suspicious. Not sure what the fix should be here

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10306
