### ISSUE TITLE
Styleguide | Searches

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#1423]
As a developer and designer, I want to a easy and consistent way to incorporate search bars so users can find and get to important information in an accessible way across our apps. 

## Acceptance Criteria 
1. Verify that this is found in the living style guide there is a section called `Searches` 
1. Verify that the description for `Searches` appears underneath the title (see copy)
1. Verify that the components and sections appear beneath the description for `Searches` 
1. Verify that the `Search Big` match the USWDS
1. Verify that the `Search Small` matches the one in USWDS
1. Verify that the `Loading Spinner` appears during a search 
1. Verify that there is a `Search Bars` in the left style guide nav 
1. Verify that clicking on `Search Bars` in the style guide nav takes you to the right section 

## Mocks

_These are taken straight from [WBDS on Search Bars](https://standards.usa.gov/components/search-bar/)_

<img width="414" alt="screen shot 2017-06-08 at 9 46 52 am" src="https://user-images.githubusercontent.com/23316107/26931785-992e6744-4c2f-11e7-91d0-1aec31271709.png">

<img width="272" alt="screen shot 2017-06-08 at 9 47 45 am" src="https://user-images.githubusercontent.com/23316107/26931792-9ee8643c-4c2f-11e7-953a-837268f24067.png">

**Loading Search**
_Make sure you are logged into Invision_

[Craft Link - Loading Search](https://projects.invisionapp.com/d/main#/console/10592592/227982798/inspect)

<img width="522" alt="screen shot 2017-04-07 at 8 37 54 am" src="https://cloud.githubusercontent.com/assets/23316107/24800305/8f1ddb6a-1b6d-11e7-8901-17a15800030e.png">

## Copy

**Title:**
Search Bar

**Description**

Search bars are a are block that allows users to search for specific content if they know what search terms to use or can’t find desired content in the main navigation. In Caseflow they serve as a vital UI component that allows users to find information necessary in completing their tasks. 

Based on the app there are two sizes: search big and search small. There is also a unique Caseflow search behavior that displays a spinning logo to indicate load times.

**Comment by Chingujo** [comment]
@gnakm 

We didn't have a copy for search bars so just made one for review =D. I also believe we add a spinning icon to our searches.

**Comment by Sjones352** [comment]
<img width="782" alt="screen shot 2017-05-29 at 3 28 08 pm" src="https://cloud.githubusercontent.com/assets/23080951/26560324/886de17c-4483-11e7-8995-549a516cc337.png">

**Comment by gnakm** [comment]
Had a quick chat with Nick. We probably don't have to add any searches that currently don't exist. I rather us be iterative and add more as we go, mostly because we're constantly improve things. 

Caveat, we should add it if an app that is currently being worked on is about to add it. ex. Hearings Prep, Reader

**Comment by Chingujo** [comment]
@gnakm @mmlumba @Sjones352 

AC, Mocks, and Copy changed to reflect the above decision =D

**Comment by Sjones352** [comment]
eFolder uses the big search
<img width="698" alt="screen shot 2017-06-07 at 1 34 15 pm" src="https://user-images.githubusercontent.com/23080951/26892359-095e4fa2-4b86-11e7-9489-a1abb74d2e4b.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living style guide
2. Navigate to the Search section of the style guide
3. Verify the copy and behavior/UI of the search functionality. 

Screenshots: 
![styleguidesearch](https://user-images.githubusercontent.com/23038505/26991094-0a4bbc5e-4d27-11e7-9156-4698c2cf6ee5.gif)
