### ISSUE TITLE
Add momentjs and make dates human-readable!

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1424]
Currently, certification v2 dates are not the prettiest!

![image](https://cloud.githubusercontent.com/assets/3781835/24616698/e44a2956-185f-11e7-9e77-2f77d0a13818.png)

We should use [momentjs](https://momentjs.com/) to make all dates human readable.

How to add momentjs:

```
cd client
npm install --save moment
npm shrinkwrap
```

Then `import moment from 'moment'` when you want to use it.

Make sure to commit the package.json and the shrinkwrap.

**Comment by shanear** [comment]
is this a dup of #964 ?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: Chrome and FF

Steps to Validate: 
1. Go to Certification V2 with a valid veteran's information. 
2. Validate the date format. 

Screenshot: 
<img width="1255" alt="screen shot 2017-04-21 at 10 54 28 am" src="https://cloud.githubusercontent.com/assets/23038505/25283241/16ee3dfa-2681-11e7-839e-d957e6a5073e.png">
