### ISSUE TITLE
Styleguide | Table: Expandable/ Collapsable Tables

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1425]
As a developer and content writer, I want to see what an expandable table will look like in the living style guide

## Acceptance Criteria

- [x] Verify that there is a title for Expandable table
- [x] Verify that there is Expandable table in the side nav of the style guide, under Table
- [x] Verify that the copy below is under the title and above the UI component 
- [ ] Verify that there is a text link or button that will expand a row in a table chevron icon
- [ ] Verify that the expand all button will open all the rows and collapse all button will close all rows

## Mockups

**All closed view**
![image](https://cloud.githubusercontent.com/assets/13420618/25362355/60b3d682-2921-11e7-8cf8-6efb6d074350.png)

**Expand all view**
![image](https://cloud.githubusercontent.com/assets/13420618/25362359/67b09b3c-2921-11e7-836d-dc418efa170c.png)

## Copy

**Table accordion**

The table accordion was initially designed for Caseflow Reader to allow users to see additional information of a specific section. Many times the length of content can break the balance of design and we want to make sure we capture the most important elements in a row. This design cues users to expand a view so that they have enough context to know what to expect.

**Comment by gnakm** [comment]
This is a super WIP issue because the expanded comments like look different based on feedback.

**Comment by Sjones352** [comment]
Currently working on functionality

<img width="760" alt="screen shot 2017-08-21 at 9 29 30 pm" src="https://user-images.githubusercontent.com/23080951/29544725-0c34c824-86b8-11e7-97b3-7b2dfbd58a09.png">

**Comment by mmlumba** [comment]
Based on research from https://github.com/department-of-veterans-affairs/caseflow/issues/3102

We should be able to create this component easily with rc-table: https://github.com/react-component/table

**Comment by nickheiner-usds** [comment]
Do we have a second place, other than Reader, where we're going to use this? Or are we really sure that we eventually will? 

To me, the expandable table functionality feels like a one-off component. I'd rather see how things are used across multiple contexts before trying to generalize them into the styleguide. I'm happy to chat more about this if I'm missing something. :smile:

**Comment by gnakm** [comment]
@NickHeiner I get that. Currently asking the design team if anybody sees a use case for their respective products. I think it came up before but will double check.

**Comment by gnakm** [comment]
Kicking this back for now. Currently, Reader is the only tool using this. It's being fiddled around with in Work Q. Will pull it up again if we find that it is necessary.
