### ISSUE TITLE
Validate against special issue selections made on Review Decision page

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14269]
## User or job story
Job story: When BVA Dispatch selects the "No Special Issues" option all other options should be unchecked and disabled so the data captured on the page is accurate. 

## Acceptance criteria
- [x] Please put this work behind the feature toggle: special_issues_revamp
- [ ] This feature should be accessible to the following user groups: `Establish Claim` role
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Validate that the special issues are not selected along with the "No Special Issues" by un-selecting and disabling  the other options. 

### Background/context
The special issues page allows selecting "No Special Issues" along with others. This should not continue as it will cause the data being captured to be inaccurate leading to potential confusion/issues down the line. 

### Other notes
![Dispatch Error](https://user-images.githubusercontent.com/59883609/81965771-8aaf9180-95e6-11ea-898e-e01108b01366.gif)

### Resources/other links
[Slack Conversation](https://dsva.slack.com/archives/CJL810329/p1586876908343800)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||
3 | ||||||
5 | 
8 | 
```

#### Why 2?
- Borrow solution from #13995

#### Why 3?
- We've probably done it once, but we're in a whole different app (dispatch vs queue)
- State could be different here, hunter remembers it being very straightforward though.
