### ISSUE TITLE
The Queue Table Container bleeds over its containing element

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14266]
## Description
In queue, the queue table bleeds off the container when the window has been resized.

## Acceptance criteria
- [ ] Assigned, On Hold, and Completed Tables are contained within the container and do not spill out
- [ ] When the container is too small to hold the table, a horizontal scrollbar appears to display the rest of the table

## Background/context/resources
Found during dogfooding new contention additions

## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81815625-36c67f00-94f8-11ea-94b2-796fc9e750e8.png)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||
2 | |||||||
3 | ||
5 | 
8 | 
```

Use horizontal scrollbars, which should be provided by the browser.

#### Why 1?
- Should be a one line css fix (BUT WHICH ONE!?!?)

#### Why 2?
- Might be an easy twaek, after a bit of research
