### ISSUE TITLE
Success Message for Add Issues persists after it should have cleared

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14268]
## Description
if an issue is added the success banner persists until the page is refreshed.  

## Acceptance criteria
- [ ] Success banner clears after clicking out of the case to or selecting another action. 

## Screenshots
![image](https://user-images.githubusercontent.com/59883609/81966496-a0718680-95e7-11ea-89a2-2e858e95cf52.png)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||
2 | |||||
3 | 
5 | 
8 | 
```

#### Why 1?
- Should just be clearing state?
- I really wanted a 1 this estimation session

#### Why 2?
- Add a test
- I don't trust a 1 with the word 'state' in it
