### ISSUE TITLE
Case Movement: Implement Backend Logic For Cancellation of Blocking Tasks

### ISSUE THREAD

**Issue by geronimoramos** [department-of-veterans-affairs/caseflow#14260]
## User story

- When a case movement user wants to move an AMA case, they want to be able to cancel blocking tasks that they are allowed to (policy permitting) so that they can move the case accordingly

Front end will be implemented in #13780

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: cm_move_with_blocking_tasks
- [ ] This feature should be accessible to the following user groups: CM Team Members
- [ ] CM team members can cancel "blocking tasks" to advance a case to a VLJ 
- [ ] CM team members cannot cancel "Blocking for dispatch only" tasks 

## What are the unknowns?

- What happens to those canceled blocking tasks? Are they activated again later on?

### Technical notes
Below are the current blocking tasks and the Boards logic behind each: 

**Mail Tasks:** 
•	CongressionalInterestMailTask –  _Blocking for dispatch only_
•	ExtensionRequestMailTask – _Blocking_
•	FoiaRequestMailTask – _Blocking for dispatch only_
•	HearingRelatedMailTask – _Blocking_
•	PowerOfAttorneyRelatedMailTask - _Blocking_
•	PrivacyActRequestMailTask – _Blocking for dispatch only_
•	PrivacyComplaintMailTask – _Blocking for dispatch only_
•	HearingRelatedMailTask – _Blocking_
•	HearingAdminActionMissingFormsTask – _Blocking_
•	EvidenceOrArgumentMailTask - _Blocking_

**ColocatedTasks:** 
•	FoiaColocatedTask - _Blocking for dispatch only_
•	PoaClarificationColocatedTask - _Blocking_
•	ExtensionColocatedTask - _Blocking_
•	HearingClarificationColocatedTask - _Blocking_
•	TranslationColocatedTask - _Blocking_

**Additional Blocking Tasks:** 
•	FoiaTask - _Blocking for dispatch only_
•	PrivacyActTask - _Blocking for dispatch only_
•	HearingAdminActionVerifyPoaTask - _Blocking_
•	HearingTask - _Blocking_
•	ScheduleHearingTask - _Blocking_
•	ChangeHearingDispositionTask - _Blocking_
•	EvidenceSubmissionWindowTask - _Blocking unless waived_
•	TranscriptionTask - _Blocking except for "one-touch" cases_
•	TranslationTask - _Blocking_
•	InformalHearingPresentationTask - _Blocking_

Designs that begin the cancellation process located ] [here](https://github.com/department-of-veterans-affairs/caseflow/issues/13780)

### Other Notes: 
Product Brief - https://docs.google.com/document/d/18CHodW3q-i9Y99JFwujHnoCQQdtB_QXQvzyTnBcW01U/edit#heading=h.5x0d5h95i329

**Comment by hschallhorn** [comment]
Does this ability already exist? Can we just send a request from the front end to cancel each task with the provided instructions?

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||||||
5 | ||
8 | 
```


Potential solutions:
1. Utilize update task endpoint as it already exists
PROs
- minimal eng lift
CONs
- potential edge cases around partial cancellation & testing
2. Create a whole new endpoint
PROs
- could be tested more thoroughly 
- would reduce the lift to the FE implementation
- could also become an "Advance to Judge" endpoint which would include the cancellation of all blocking tasks, closing the distribution task and opening the judge assign task
CONs
- make it

*Hedging towards solution 2 at this point

#### Why 1?
* 

#### Why 2?
* 

#### Why 3?
* Creating a whole new endpoint
* Testing all the things

#### Why 5?
* Testing and transactions
