### ISSUE TITLE
"Back" Button State Issue

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14273]
## Description
Special Issue selections change when the "back" button is clicked during attorney checkout.

## Acceptance criteria
- [ ] Selections are not changed when the back button is clicked
- [ ] Selections made before clicking the continue button should be saved

## Background/context/resources
![Back State Issue](https://user-images.githubusercontent.com/59883609/81965454-107f0d00-95e6-11ea-9e19-883265482652.gif)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

Clarification: Hitting Continue on the Sp. Issues page, then hitting Back shows different selections.


#### Why 2?
- Hopefully just some clearing out on click?

#### Why 3?
- Pessimism
- Could be hairy if we're calling the backend vs state in different places

**Comment by hschallhorn** [comment]
Could not replicate with Kat! Looks like we fixed this one somewhere else!
