### ISSUE TITLE
Dispatch: Error Scrolls to top of the page

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14275]
## Description
“No special issues” error on dispatch scrolls all the way to the top of the page, rather than scrolling to the error itself. 

## Acceptance criteria
- [ ] the page scrolls to the error message itself instead of the top of the page

## Background/context/resources
![ezgif-3-67098d30d0c3](https://user-images.githubusercontent.com/45575454/84414124-85426880-abdf-11ea-8883-d4b6f6961a0f.gif)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||
3 | ||||||||
5 | 
8 | 
```

#### Why 2?
* Could be as simple as moving the error to the component we want to scroll to the top to.

#### Why 3?
* Unfamiliarity around where and why we're scrolling
* Pessimism

**Comment by araposo-tistatech** [comment]
no longer moving forward with adding the new contentions to Dispatch as BVA Dispatch does not interact with Caseflow Dispatch.
