### ISSUE TITLE
Contested Claims | UAT | Attorney Fees | Test attorney claimants in UAT

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14281]
## Description
In order to get ahead of any downstream issues, we should test intaking an appeal in UAT with the claimant set to an attorney's participant ID.

## Acceptance criteria
- [ ]  Verify that an attorney fee appeal can be successfully established, or document the error that occurs.
- [ ] Possibly out of scope: do the same for a HLR and SC. However, we are currently prioritizing attorney fees work in the context of Board intake.

## Technical notes
This might be most easily accomplished by using a combination of the frontend UI and Rails console. The primary lift is swapping an attorney's participant ID into the claimant record.

A possible flow might be:
- Use the frontend UI to create an `Intake` and `Appeal`.
- Use the Rails console to update the corresponding record in the `claimants` table.
- Use the frontend UI to finish selecting issues and establish the appeal.

**Comment by leikkisa** [comment]
- Affects Board Grant Effectuations and Remand Supplemental Claims

**Comment by leikkisa** [comment]
- Currently for board appeals - to be clarified

**Comment by wdrougas-tista** [comment]
```ruby
BGSService.new.client.data.find_power_of_attorneys
epe=EndProductEstablishment.where.not(reference_id: nil)
epe=_.last
epe2=EndProductEstablishment.create(
    source_type: "SupplementalClaim", source_id: 1639, veteran_file_number: "762055447", claim_date: "2020-05-28", code: "930AMASNRC", modifier: "930", station: "373",claimant_participant_id: "600306255", payee_code: "00", doc_reference_id: nil, development_item_reference_id: nil, benefit_type_code: "1", user_id: 401, limited_poa_code: nil, limited_poa_access: nil
)
epe2.establish!
```


**Error when trying to establish EP in VBMS**
`VBMS::MissingData (status_code=500, body=<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Error validating ClaimService data input. GUID: 630a1f27-403f-4796-883c-e8f914494bbc</faultstring><detail><ns2:dataValidationFaultDetailBean xmlns:part="http://vbms.vba.va.gov/cdm/participant/v5" xmlns:ns2="http://vbms.vba.va.gov/external/ClaimService/v5" xmlns:doc="http://vbms.vba.va.gov/cdm/document/v5" xmlns:com="http://vbms.vba.va.gov/cdm/common/v5" xmlns:claim="http://vbms.vba.va.gov/cdm/claim/v5" xmlns:aw="http://vbms.vba.va.gov/cdm/award/v4"><ns2:formFieldErrors><ns2:fieldName>participantPersonId</ns2:fieldName><ns2:errorType>MISSING_REQUIRED_FIELD</ns2:errorType><ns2:message>The establishClaim service endpoint is missing required data: participantPersonId does not match a dependent or an organization..</ns2:message></ns2:formFieldErrors></ns2:dataValidationFaultDetailBean></detail></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::EstablishClaim:0x000000000aeb8cc8 @veteran_record={:sex=>"F", :address_line1=>"202 PARK AVE", :address_line2=>nil, :address_line3=>nil, :city=>"RICHMOND", :state=>"VA", :country=>"USA", :zip_code=>"23237", :service=>[{:short_service_number=>nil, :service_number_fill=>nil, :branch_of_service=>"NAVY", :entered_on_duty_date=>"11282002", :released_active_duty_date=>"01192010", :separation_reason_code=>"SAT", :nonpay_days=>nil, :pay_grade=>"O3 ", :char_of_svc_code=>"HON"}, {:short_service_number=>nil, :service_number_fill=>nil, :branch_of_service=>nil, :entered_on_duty_date=>nil, :released_active_duty_date=>nil, :separation_reason_code=>nil, :nonpay_days=>nil, :pay_grade=>nil, :char_of_svc_code=>nil}, {:short_service_number=>nil, :service_number_fill=>nil, :branch_of_service=>nil, :entered_on_duty_date=>nil, :released_active_duty_date=>nil, :separation_reason_code=>nil, :nonpay_days=>nil, :pay_grade=>nil, :char_of_svc_code=>nil}], :date_of_birth=>"02/08/1981", :email_address=>nil, :file_number=>"762055447", :address_type=>"", :first_name=>"JOHNA", :last_name=>"WOMBACHER", :name_suffix=>nil, :ssn=>"762055447", :date_of_death=>nil}, @claim={:benefit_type_code=>"1", :payee_code=>"00", :predischarge=>false, :claim_type=>"Claim", :end_product_modifier=>"931", :end_product_code=>"930AMASNRC", :end_product_label=>"AMA Supp Non-Rating Control", :station_of_jurisdiction=>"373", :date=>Thu, 28 May 2020, :suppress_acknowledgement_letter=>false, :gulf_war_registry=>false, :claimant_participant_id=>"600306255", :limited_poa_code=>nil, :limited_poa_access=>nil, :status_type_code=>"PEND"}, @v5=true, @send_userid=true>)`
