### ISSUE TITLE
Gather metrics on how many documents show up in reader for a given user

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14289]
In [investigating](https://hackmd.io/9DYl3EwdTqKCpALVbIWnQg?view) #14081, we noticed that there may be a discrepancy between the number of documents we have fetched for a case and the number of documents a user sees in reader.

> Timeline:
> * Mar 23: 421 documents were retrieved by Caseflow
> * Apr 20 Judge assigns to atty
> * Apr 21 Atty starts to view 309 docs on these dates:
> ```
>  [Tue, 21 Apr 2020 00:00:00 UTC +00:00, 303],
>  [Wed, 22 Apr 2020 00:00:00 UTC +00:00, 2],
>  [Mon, 27 Apr 2020 00:00:00 UTC +00:00, 4]]
> ```
> * 5 more documents were retrieved by Caseflow
> ```
> [Fri, 24 Apr 2020, 2],
> [Sun, 26 Apr 2020, 3]
> ```
> * Apr 28 Atty completes AttorneyTask
> * Apr 28 Judge views 32 docs
>  ```
> [[Wed, 29 Apr 2020 00:00:00 UTC +00:00, 22],
>  [Tue, 28 Apr 2020 00:00:00 UTC +00:00, 10]]
> ```
> * Apr 29 Atty assigned AttorneyRewriteTask
> * May 6 Atty views 93 docs for the first time on these dates:
>  ```
>  [Wed, 06 May 2020 00:00:00 UTC +00:00, 21],
>  [Mon, 11 May 2020 00:00:00 UTC +00:00, 71],
>  [Tue, 12 May 2020 00:00:00 UTC +00:00, 1],
>  ```
> * May 12 Atty completed AttorneyRewriteTask
> * Some later date Attorney says that while working the case Reader had the document count at around 311 documents. Upon completion of the decision drafting task and sending the decision to the judge for review the judge saw and reviewed 425 documents in Reader. When the case was routed back to the attorney for a re-write the attorney noticed there were over 100 documents that were not reviewed by him originally on the case. 

## AC
- [ ] Record or log how many documents are shown to a user when viewing reader for future debugging

## Open questions
Don't want to create a new table to add to the *_veiws mess #12237

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

Clarification: Hitting Continue on the Sp. Issues page, then hitting Back shows different selections.


#### Why 2?
- Hopefully just some clearing out on click?

#### Why 3?
- Pessimism
- Could be hairy if we're calling the backend vs state in different places

**Comment by yoomlam** [comment]
Record in DataDog or server logs (to be viewed via AWS or Kibana).
