### ISSUE TITLE
Contested Claims | Attorney Fees | Add note field to Add Claimant modal

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14283]
## Story
As a BVA Intake user, if no attorney is available for selection as claimant, a notes field is required to add that attorney information. 

## Description
Part 3 of the work on the Add Claimant modal. The Add Claimant modal should include a `Claimant not listed` checkbox, which toggles the presence of an `Add notes` text box for free-text input.

## Acceptance criteria
- [ ] Modal is updated to match behavior specified in design (see Background below)
- [ ] Only option in relationships is the attorney option
- [ ] Added notes get saved in Caseflow DB

## Background/context/resources
Designs for when the checkbox is initially unselected, then selected:

![Review - Selected - Not Veteran-3](https://user-images.githubusercontent.com/51714306/82713901-3b0a3f00-9c52-11ea-9f09-e4b0baefb043.jpg)

![Review - Selected - Not Veteran-4](https://user-images.githubusercontent.com/51714306/82713915-4cebe200-9c52-11ea-85b6-2052d12a5bad.jpg)

Here is [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1590168724901/e207ffed8f8654a1d454d3938459c9252eeee837) with the user flow and the [Figma Prototype](https://www.figma.com/proto/HL5muMytaEzO4Li2UJMx9E/Attorney-Fees_March-2020_RG?node-id=3117%3A0&viewport=305%2C198%2C0.06350482255220413&scaling=min-zoom). 

Be sure to touch base with @rutvigupta-design as the designs may undergo further minor changes.

## Technical notes
~~A simple database migration for adding the column to store the additional text is needed. Consider, also, whether to add a separate boolean column for the checkbox state, or to capture this "boolean-ness" in the naming of the text column, e.g. `claimant_not_found_notes`.~~

~~The new column[s] will likely go on the `intakes` table, so that it can be applicable not only to Appeals, but to HLRs and SCs as well.~~

See #14380 for related work on the data side.

## Open questions
Considerations to keep in mind, from both a design and frontend eng perspective:
- The checkbox should be clickable even if the searchable dropdown has attorney names to suggest. The user may decide that none of the (small number of) suggestions matches.
- If the typed out attorney name produces zero results, should we nudge the user to click the checkbox, **and/or** check the name for typos/variants?

**Comment by leikkisa** [comment]
- Notes part of design is currently blocked - Martina is having a meeting on Monday to discuss
- Where do we want to store the notes? Discuss during team sync
- How will the notes be used down the line?
- Where do claimant names show up outside of Intake?
- Ideally it would show on the Case Details page
- Look up example of appeal with a non-veteran claimant to see if it's there

**Comment by nanotone** [comment]
This ticket is now identical to #14107. I've merged any new technical notes from here to the older ticket, and am now closing this one.
