### ISSUE TITLE
Allow all users access to virtual hearings feature 🚀

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14282]
## Description
Open permissions to allow those with scheduling ability to use functionality to schedule and edit virtual hearings for a 5/20/20 national rollout.

## Acceptance criteria
- [ ] Allow all Hearing Coordinators to schedule virtual hearings

## Out of scope
- Remove feature flag entirely. This is a larger update and will be done when confidence is high.

**Comment by tomas-nava** [comment]
closed by [appeals-deployment/pull/2735](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2735)
