### ISSUE TITLE
Investigate what occurs when Reader is refreshed

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14298]
## Description
Please look into what refreshing reader actually does. Does it check VBMS, etc for new documents or is it pulling documents from a cache? 

## Acceptance criteria
- [x] Gather information what occurs when reader is refreshed
- [x] Add wiki page describing startup queries when Reader is refreshed

## Background/context/resources
Related to ticket #14081 

## Technical notes
Per Alisa,  

"Troy has an interesting theory, I think 2 is a potential explanation for the issue. I don’t think this is something we’ll be able to replicate easily (unless we want to do an experiment of loading a Veteran’s documents, waiting 2 weeks, and then checking again?). The best path may be to try to query the logs from this time period and try to see what was being added and removed from the database."

Troy's #2 Theory: 

"I've been told that if a document isn't viewed within 2 weeks of download, it is removed from Caseflow storage. Is it possible another user viewed the documents within the 2 weeks, hence those documents persisted but the others weren't viewed and removed from storage after 2 weeks? And the user failed to hit the refresh button so the missing documents didn't refresh into Caseflow storage, hence the lower # of docs?"

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

#### Why 2?
* No code change; follow code and document

#### Why 3?
* Uncertainty around 
  * Our upstream dependencies 
  * Caching
  * Replicating this in development

**Comment by yoomlam** [comment]
@araposo-tistatech To make sure I'm on the right track, what does "refresh" mean in this ticket?

**Comment by araposo-tistatech** [comment]
@yoomlam it means clicking the refresh button on the browser.

**Comment by yoomlam** [comment]
[WIP notes so far](https://hackmd.io/Dm7cR49cRgycy5g7oHiGwA)

**Comment by yoomlam** [comment]
Result: https://github.com/department-of-veterans-affairs/caseflow/wiki/Reader-Backend

**Comment by yoomlam** [comment]
@araposo-tistatech Is the above wiki page sufficient for closing this ticket?
I describe some potential tickets arising from this investigation in [Slack](https://dsva.slack.com/archives/CJL810329/p1591280243407100).

**Comment by araposo-tistatech** [comment]
@yoomlam closing, thanks!
