### ISSUE TITLE
Intake | Bug | Fix nonrating issue description on Add Issues

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14292]
## Description
On the Add Issues edit page, after a nonrating request issue has been added and saved, its description is showing the non-rating issue category twice.

## Acceptance criteria
- [ ] The nonrating Issue description does not repeat the non-rating issue category on the Add Issues edit page

## Screenshot of bug
![Screen Shot 2020-05-13 at 7.46.24 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/52a7e226-5a85-48af-b947-ea9a1761f974)

## Technical notes
This is likely because the description from the backend includes the nonrating issue category in the description, and the front-end combines the description with the category again.

**Comment by jcq** [comment]
### Previous Behavior
![Screen Shot 2020-05-27 at 15 01 43](https://user-images.githubusercontent.com/2581274/83078102-9ca12380-a02d-11ea-8af8-743640fee093.png)



### Updated Behavior
![Screen Shot 2020-05-27 at 15 01 54](https://user-images.githubusercontent.com/2581274/83078118-a75bb880-a02d-11ea-98e6-2d8a2a5b0703.png)
