### ISSUE TITLE
Set up logging for hearing dispositions

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14299]
## Description
Record when dispositions were set on hearings and what they were

## Acceptance criteria
- [ ] Write query 
- [ ] Set up graphs in Metabase 

## Background/context/resources
Long-term goal: increase hearing capacity
Short-term goal: allow more hearings to be held during Covid-19 stay-at-home orders

**Comment by tomas-nava** [comment]
**[this query may be useful](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/115#issuecomment-614318870)**

**Comment by ferristseng** [comment]
We might be lacking the "what they were" part of this since a hearing can have its disposition changed. We do have the final disposition though, which I think _should_ be enough. My understanding is when a disposition is changed, it's mostly as a corrective measure (?).

**Comment by ferristseng** [comment]
Closing this in favor of #13687, which has points on it
