### ISSUE TITLE
Contested Claims | Attorney Fees | Fetch Attorney Fee Data

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14294]
## Description
Create a nightly job to fetch a list of attorney names from BGS and upsert them in Caseflow Postgres.

## Acceptance criteria
- [ ] The Caseflow DB is populated with BGS attorney data
- [ ] A new job for populating is created and run nightly

## Background/context/resources
In order to intake attorney-fee cases properly, Caseflow needs to be able to provide a list of attorneys as possible claimants. When a previously unknown attorney needs to be added, the user will do this in an external system (we'll have to craft messaging around this) and we are told this process takes 24-48 hours. The new nightly job is intended to pick up any fresh names that have been recently added.

See #14004 for related work on evaluating external systems. For the scope of this ticket, the BGS endpoint `StandardDataWebService.find_power_of_attorneys` is sufficient to get the initial list of attorneys.

See #14020 for work on setting up the database table and ActiveRecord model for BGS attorneys.

## Technical notes
The nightly jobs are specified in `app/jobs/nightly_syncs_job.rb` and tested in `spec/jobs/nightly_syncs_job_spec.rb`. Depending on how complex this job ends up being, it may be worth creating a new service in `app/services/` to house the logic.

Additionally, we've been told by Board Intake that addresses would be their primary disambiguation strategy for duplicate names/surnames. We currently store addresses in Redis, via the `BgsAddressService` class using keys in the form of `bgs-participant-address-#{participant_id}`.

As per @pkarman's advice, there's no need to store addresses in PG. The nightly job should just pre-warm the cache. #14257 has added a multi-fetch method, to do the join for the search endpoint.

**Comment by msj0nes** [comment]
Hi @nanotone  I'm providing sprint updates to Fred. Is this safe to close or is there additional work to be done?

**Comment by nanotone** [comment]
@msj0nes No, this is still in progress.
