### ISSUE TITLE
Introduce granularity between VSOs and state / regional VA organization 

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14297]
## Description
Introduce granularity in Caseflow between _Co-located Veteran Service Organizations (VSOs)_ and _State or Regional VA Organizations_ in order to better route cases to different locations upon hearing withdraw, no-show, etc.

This work should allow Caseflow to perform the following actions, and will allow the work described in #14129 and #12539 to be completed.

If the appeal is Legacy and being withdrawn or canceled, assign it to:
- 55 if the POA / representative type is a Co-located Veteran Service Organization (VSO)
- 81 (Case Storage) if the POA / representative type is any other, including:
  - private agent / attorney
  - state or regional VA organization (e.g. NC Department of Military & Veterans Affairs)
  - no representative
  - a non-co-located Veteran Service Organization (VSO)
- If the appeal is AMA, assign it to Mail (create an EvidenceSubmissionWindow task, which is part of the Mail org)

## Acceptance criteria
- [ ] Update [Hearing Task Flow documentation](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Caseflow%20Projects/Hearings/Hearing%20Schedule/Tech%20Specs/HearingTaskFlow.md)

## Technical notes
TK

## Open questions
- Is there a better way for fetching information from BGS other than the roundabout way of getting info? 
- Once we have it, what do we do with it? Currently don't classify them

## Next steps
- define the research that needs to happen to pull co-located VSO organization list from VACOLS

**Comment by lund5000** [comment]
Estimate of 3pts is to do research to determine a way to introduce this granularity, not yet to implement that granularity.
