### ISSUE TITLE
Intake | Bug | Fix request issue description on Legacy issue opt-in modal

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14293]
## Description
On the legacy issue opt-in modal, the current request issue's description in the "None of these match" option  is showing up as "undefined".

## Acceptance criteria
- [ ] When adding a request issue, if the legacy issue opt-in modal pops up it shows the request issue description in the "None of these match" option (instead of undefined)

![Screen Shot 2020-05-13 at 7.39.37 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/cea71297-6d90-49b5-ae8c-10844226229c)
## Technical notes
This may only be impacting nonrating issues.

**Comment by wdrougas-tista** [comment]
<img width="762" alt="Screen Shot 2020-06-01 at 3 19 04 PM" src="https://user-images.githubusercontent.com/63597932/83446001-f7ff5700-a41b-11ea-8d09-86177e4841e1.png">

Attached is the updated UI
