### ISSUE TITLE
Do not use multiple task serializes for paginated tasks

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14291]
When serializing tasks for pagination, we use two different serializers. The [initial request](https://github.com/department-of-veterans-affairs/caseflow/blob/4a1fd3cb0864788bb9bba239ed15fe3c6501e40a/app/controllers/organizations/tasks_controller.rb#L12) for paginated tasks uses [TaskColumnSerializer](https://github.com/department-of-veterans-affairs/caseflow/blob/27d78c298bdf7ccafb58a8987d051cbe991ced71/app/models/queue_config.rb#L60). [Further requests](https://github.com/department-of-veterans-affairs/caseflow/blob/516b9f47cdbec65f4b88e0ab23d9fec7a7e7915a/app/controllers/organizations/task_pages_controller.rb#L56) for additional pages or sorted or filtered tasks uses task pages controller uses AmaAndLegacyTaskSerializer, combination of [LegacyTaskSerializer](https://github.com/department-of-veterans-affairs/caseflow/blob/94c848010040cca0ed4e7ec2cb926fc88dde9640/app/serializers/ama_and_legacy_task_serializer.rb#L13) with [TaskSerializer](https://github.com/department-of-veterans-affairs/caseflow/blob/94c848010040cca0ed4e7ec2cb926fc88dde9640/app/serializers/ama_and_legacy_task_serializer.rb#L24). 

### Open questions
1. Should paginated organization tasks on legacy appeal use the LegacyTaskSerializer or should only LegacyTasks use this serializer?
2. Can we simply use the TaskColumnSerializer for these paginated responses, perhaps integrating TaskColumnSerializer directly into [TaskPager](https://github.com/department-of-veterans-affairs/caseflow/blob/516b9f47cdbec65f4b88e0ab23d9fec7a7e7915a/app/controllers/organizations/task_pages_controller.rb#L42)

## AC
- [ ] If possible, use only TaskColumnSerializer when returning paged tasks to the front end.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | ||||||||
5 | |
8 | 
```

#### Why 2?
- Should be able to reuse the serializer call in queue config

#### Why 3?
- Time to verify that the serializers are capturing everything needed.

#### Why 5?
- I'm not super familiar with our serializers
