### ISSUE TITLE
Set up report for days waiting in scheduling queue(s)

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14301]
## Questions to answer through looking at data
- Days Veterans wait in scheduling queue per RO (between when first ScheduleHearing task was created and final is ScheduleHearing completed). 
  - End goal with this metric: How directly is a Veteran's physical location correlated to appeal decision timeliness?
- How many Veterans are scheduled on average, per RO, per month/year?
  - How do these dispositions break down: held, canceled, postponed, withdrawn, no show?
- How many Veterans in the scheduling queue?

## Acceptance criteria
- [ ] Days waiting related to RO
- [ ] Historic hearings with different dispositions over time
- [ ] Overall number of Veterans in scheduling queue

**Comment by rubaiyat22** [comment]
** average number of days to close a ScheduleHearingTask by Regional office**
http://query.prod.appeals.va.gov/question/51

** number of hearings scheduled per year by Regional Office **
http://query.prod.appeals.va.gov/question/54

** yearly average of hearings scheduled per Regional Office **
http://query.prod.appeals.va.gov/question/55

** monthly average of hearings scheduled per Regional office **
http://query.prod.appeals.va.gov/question/56

** number of veterans waiting in Regional Office queue **
http://query.prod.appeals.va.gov/question/53

**Comment by chandracarney** [comment]
@rubaiyat22 These look so good! Amazing!

Is there a way to add the RO's city name (Central), along with the code (C) to make it clear to people unfamiliar with RO codes?

**Comment by rubaiyat22** [comment]
I wanted to use human readable names for the RO’s but we don’t store them in our database but I can look into it deeply and see if i can figure out a way
