### ISSUE TITLE
Update address bar for paginated pages, even when pulling from cache

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14300]
### Description
When paginated results are cached, the url bar does not update to reflect anymore changes in queue.

![ezgif-3-39cfac4105c2](https://user-images.githubusercontent.com/45575454/81962600-f5120300-95e1-11ea-9e30-9a94056382ce.gif)

### Steps to reproduce
1. Log in as BVALSPORER
2. Navigate to the vlj support queue /organizations/vlj-support?tab=assigned
3. Click the sort button on the task type column twice, noticing the url bar updates with the sort order each time
4.  Click the sort button again, noticing the url bar now does not update
5. This can be done with changing pages and filters as well

### AC
- [ ] Always update the URL bar in queue when changing filters, sorts, or page numbers, even if these responses are cached.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||||
3 | |||
5 | 
8 | 
```

URL change is occurring in QueueTable

#### Why 1?
* 

#### Why 2?
* A bit of digging to find the right place

#### Why 3?
* May take some unpacking of the link between only updating the address bar any time tasks need to be requested from the back end
* Learning how pagination is related to the URL

**Comment by hschallhorn** [comment]
[Where we update the url after requesting new tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/7270430ceb0dbb64ac7a124f0d83ddda92d8cecc/client/app/queue/QueueTable.jsx#L497)
[Where we exit the function early if we already have the response cached](https://github.com/department-of-veterans-affairs/caseflow/blob/7270430ceb0dbb64ac7a124f0d83ddda92d8cecc/client/app/queue/QueueTable.jsx#L475)

**Comment by hschallhorn** [comment]
Found in  #14468, when switching from the on hold tab for an attorney with user pagination to the assigned tab, the url does not update either.
