### ISSUE TITLE
Navigation | Help |  Create Dispatch help page

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#1430]
As a Caseworker or BVA Manager, I would like to see FAQ help for Dispatch so that when I don't understand and/or need more information I can look it up.

# Acceptance Criteria
1. Verify that a new Dispatch Help page has been created with the following sections and their sub-copy (refer to mockup):

     Section |Header|Sub-copy
     ---|---|---
     Introduction|Welcome to Dispatch Help Page!|Here you will find Training Videos and FAQs for Caseflow Dispatch. If you still need help please contact the Caseflow Product Support Team by calling 1-844-876-5548. We will assist you as quickly as possible.
     Training Videos|Training Videos|Coming Soon.
     FAQ |Frequently Asked Questions|
     FAQ Answers|(No header)|

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "FAQs" is a hyperlink to the Frequently Asked Questions section.
1. Verify in the Frequently Asked Questions section, it contains listing of all questions. (Refer to [Dispatch FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Dispatch/training-materials/FAQs.md))
1. Verify that in the FAQ Answers section, it contains all questions and their answer.  (Refer to [Dispatch FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Dispatch/training-materials/FAQs.md))
1. Verify that each question in the FAQ section is a hyperlink to its answer. 
1. Verify that in the FAQ Answer section for question 1, the text "Caseflow Dispatch Quick Reference Guide" is a link to the [pdf document](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Dispatch/training-materials/Dispatch%20Guidance%20to%20ARC_%203-28.pdf). 
1. Verify that clicking on 'back to top' takes you to the top of the page.
1. Verify that the when the link **_Caseflow Dispatch Quick Reference Guide_** is clicked, a new browser tab is opened with the pdf document.  

## Mock(s)
**_Navigation - {Dispatch Help Page}_**

![dispatch help page](https://cloud.githubusercontent.com/assets/23316107/24629755/2d27b224-1888-11e7-9029-d0a7096c3860.png)

## Note 
eFolder Express Help page is the layout and format to be used for Dispatch.

# Related Stories
Navigation Bar | User Menu | Help link goes to Certification Help page [#1435](https://github.com/department-of-veterans-affairs/caseflow/issues/1435)

**Comment by Chingujo** [comment]
@nikitarockz 

**Dispatch Help Page FAQ Only**
![dispatch help page](https://cloud.githubusercontent.com/assets/23316107/24624549/3cffdc2a-187a-11e7-80b4-7322523b4f6c.png)

**Dispatch Help Page**
(left e-Folder express videos but would be replaced by dispatch ones) 
![dispatch faq](https://cloud.githubusercontent.com/assets/23316107/24624567/48dceb3c-187a-11e7-8356-00c7144a30ed.png)

**Comment by Sjones352** [comment]
**Current Page Developed**

<img width="1280" alt="screen shot 2017-04-11 at 5 02 03 pm" src="https://cloud.githubusercontent.com/assets/23080951/24930762/b56bcc64-1ed8-11e7-8900-05cf43ec3e95.png">

**Comment by Sjones352** [comment]
@nikitarockz @avrildavid @wturne the pdf link takes them to the training repo in github. This poses a question "Do users have github accounts to access it because you have to actually need to be login-ed to access this pdf.

**Comment by avrildavid** [comment]
Hey @Sjones352 @nikitarockz @wturne - was wondering if there's an asset library where we can save the PDF so that users can view it? Or, the eX PDF guide is up on TMS (though I think that's a process to get it to happen), we could maybe look into having it uploaded to TMS and linking to it that way, but our own asset library seems better for managing it internally.

**Comment by Sjones352** [comment]
@Chingujo what is your take on this. I will be changing the icon to show purple caseflow dispatch
<img width="536" alt="screen shot 2017-04-14 at 9 49 04 am" src="https://cloud.githubusercontent.com/assets/23080951/25044963/be28dcf4-20f7-11e7-8421-1f821f20d67a.png">
 the certification help page has the same although it doesn't say certification.
<img width="504" alt="screen shot 2017-04-14 at 9 49 26 am" src="https://cloud.githubusercontent.com/assets/23080951/25044993/d85f2f56-20f7-11e7-8da0-9d480b2999b3.png">
I like this better.
<img width="429" alt="screen shot 2017-04-14 at 9 52 17 am" src="https://cloud.githubusercontent.com/assets/23080951/25045050/2350fb2a-20f8-11e7-96f6-24350f36aec5.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: Chrome and FF

Steps to Validate: 
1. Go to help/dispatch and validate that the help page matches the current Caseflow help page and the distinct factors of this help page  found in the mocks of the AC above. 

Screenshots: 
![help dispatch](https://cloud.githubusercontent.com/assets/23038505/25248573/bdb71e7c-25dc-11e7-8534-3b67bc327778.gif)
