### ISSUE TITLE
Alphabetize user selection dropdowns

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14303]
All dropdowns that display a list of users should be alphabetized for ease of searching. Can be done for all task actions in [users_to_options](https://github.com/department-of-veterans-affairs/caseflow/blob/7f1754a1599e1047dc545c3b9c1c6f3dc2afece1/app/repositories/task_action_repository.rb#L344). This will cover all user dropdowns for task actions, there are a few more floating around in caseflow.

### AC
- [ ] All dropdowns that display users should be alphabetized by first name
- [ ] Sorting should be done on the back end if possible.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||||
3 | |||
5 | 
8 | 
```



#### Why 1?
* 

#### Why 2?
* Find all the user dropdowns
* Sort 'em
* Add tests
