### ISSUE TITLE
Caseflow User Role: Case Movement 

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14319]
## Description
I am working on a matrix for the Case Movement team. The user list consists of members of different teams, but I do not know the exact role they are assigned as in Caseflow. Below is the list of the members and their titles some are self explanatory, like VLJ, but others are not. Please provide the role they are assigned as in Caseflow: 

| {User | Title | Caseflow Role |
| -- | -- | -- |
| Jureka Hightower | Staff Assistant |  
| Wendy Bray | Staff Assistant |  
| Marcus Murray | Staff Assistant |  
| David Dunphy | Sup Program Management SPC |  
| Anthony Scire | Veterans Law Judge |  
| Christopher High | Paralegal Specialist |  
| Charlene Evans | Legal Assistant |  
| Michael Sanford | Associate Counsel |  
| Steven Ginski | Associate Counsel |  
| John Gosnell | Supervisory Computer Engineer |  
| Mary Tang | Attorney Advisor |  
| Scott Toomer | Program Specialist |  
| Salvador Ambriz | Specialty Hearings Coordinator |  
| Lashonda Unseld | Program Specialist |  
| Jennifer White | Veterans Law Judge |  
| Keturah Harley | Chief of Litigation Support |  
| Rodney Anderson | Senior Management Analyst |  
| Allison Highley | Chief Counsel |  
| Bridget Malone | Legal Assistant |  
| Glynda Lilly | Legal Assistant |  
| George Waddington | Executive Assistant to the Chairman |  

## Acceptance criteria
- [ ] Provide the user role in Caseflow for the list of Board members above

## Background/context/resources
Working on building [this](https://docs.google.com/spreadsheets/d/1F70y_OTJewvlZMY-rF68jsbvRtmLCcFSHf3FOT2j68Y/edit#gid=192882657) matrix out to provide to the Board in relation to the Case Movement moving cases with blocking tasks functionality.

**Comment by hschallhorn** [comment]
@araposo-tistatech What do you mean by role here. Some things I can think of are
- [ ] Are they a judge in vacols?
- [ ] Are they an acting judge in vacols?
- [ ] Are the an attorney vacols?
- [ ] Are they a colocated user in vacols?
- [ ] Are they a dispatch user in vacols?
- [ ] Are they an admin of any organizations (including judge teams)
- [ ] Are they a non admin of any organizations (including judge teams)
- [ ] Are they are [granted any functions](https://github.com/department-of-veterans-affairs/caseflow/wiki/Functions) in caseflow (includes system admin and global admin)

**Comment by araposo-tistatech** [comment]
@hschallhorn all items you listed, that is basically what I am trying to base the matrix on, what features/pages are we presenting to them in Caseflow. 

If I know they are a colocated user then I know they see xyz page and can do xyz action. Does that make sense? Regrets, I think my user of the terminology "role" maybe the confusion. It's a bit different in Caseflow so I have to make sure I use the right wording.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||
3 | ||||||||
5 | ||
8 | 
```

Wiki page ref:
* [FeatureToggle](https://github.com/department-of-veterans-affairs/caseflow/wiki/User-access-permissions-in-Caseflow#2-feature-toggles)
* [User access permissions in Caseflow](https://github.com/department-of-veterans-affairs/caseflow/wiki/User-access-permissions-in-Caseflow)
* https://github.com/department-of-veterans-affairs/caseflow/issues/12437
 
#### Why 1?
* 

#### Why 2?
* Once we figure out the commands, should be easy to run them for the list of users :fingers-crossed:

#### Why 3?
* Will take some time to build out checks for each of these, but after that, easy enough to run on all users, output csv, and copy into sheet
* May be some additional work in mapping what _actions_ these roles actually manage. 
 
#### Why 5?
* Updating documentation
