### ISSUE TITLE
Documents List | "View All Comments" tab

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1431]
As a user, I want to be able to see all annotations on documents in a quick and easy way, without having to go through each document. 

## Acceptance Criteria 

- [ ] Verify that the table header is fixed
- [ ] Verify that table header is same as the one in All document list view: **Categories**, **Receipt** **Date**, **Document Type**, **Issue Tags**, **Comments**
- [ ] Verify that user can filter by category and issue tags on this view
- [ ] Verify that filters on different tabs do no carry over when user toggles between both
- [ ] Verify that all Issue tags are displayed
- [ ] Verify that each comment has a Page number
- [ ] Verify that each comment has a "Jump to section" link
- [ ] Verify that max width of comment box is 625px/ 80 characters
- [ ] Verify that each comment height is the length of message.

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/24807448/375b6866-1b86-11e7-8930-0b4e6b69b1fb.png)

**Comment by abbyraskin** [comment]
@gnakm would you mind dropping the most updated mock here and I can work on AC?

**Comment by gnakm** [comment]
@abbyraskin yes and it has been saved in a markdown in case github decides to erase it's memory again.

**Comment by abbyraskin** [comment]
Note: we no longer have any tab navigation on the page

**Comment by abbyraskin** [comment]
Moving to backlog as we are removing this tab for first release...will possibly revisit later

**Comment by abbyraskin** [comment]
Closing this out -- we can revisit if needed but it isn't looking likely.
