### ISSUE TITLE
Documents List | Categories: filter by one or more category

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1432]
**Story**
When looking at the Documents List, I want to sort by document category so I can limit the view to the category/categories relevant to me.

## Dependent Story
#1478 Category filter component

## Acceptance Criteria
- Verify that no categories are selected by default when a user logs in, and the filter icon is set to the unselected state
-  Verify that the selected filter(s) persists if a user opens a document and clicks the "Back to all documents" button on the Document Viewer
    - otherwise, the state is reset on refresh
-  Verify that if I click on a checkbox next to a category, the documents list filters to display only those documents with that filter
-  Verify that the category filter is acting as “or” so that if more than 1 category is selected in the filter, it will show documents including all of the category filters. 
- Verify that when searching with a filter, the search results are within the filter and an alert messages shows below the search bar that explains that the search results are being filtered. See related issue #1780
- Verify that if 1 or more category checkbox is selected, the filter icon is in the selected state, and if no checkboxes are selected, the filter icon is in the unselected state 
-  Verify that the colored category icon displays next to each document row after selecting a filter, and that any additional categories associated with the document that were NOT selected in the filter also display
- Verify that the filter states reflect the specs below
- Verify that the display of category column goes in the following order: procedural (blue), medical (pink), and others (green) and that the icons, whether there are 1, 2 or 3, start from the far left. 
- Verify that "selected" state for the filter icon for when there is a filter applied and when the dropdown filter is open
- Category and issue tags behave with one another as “and” — if I select a medical category filter, then select a “right knee” issue filter, I’ll see every document that contains either a medical filter AND right knee issue tag.

## Mockups

![image](https://cloud.githubusercontent.com/assets/13420618/24776851/a6534cca-1af0-11e7-9a58-b9f1e4624e33.png)

![image](https://cloud.githubusercontent.com/assets/13420618/24776223/e52a8466-1aed-11e7-8e03-14612ae444e4.png)

![image](https://cloud.githubusercontent.com/assets/13420618/24776926/07d27804-1af1-11e7-8990-b462e98570ee.png)

**Category Icon order**

![image](https://cloud.githubusercontent.com/assets/829827/24972847/c5348cb4-1f8a-11e7-8b39-ff8148362845.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

## Designs

**_Note: Filter boxes are same dimensions as checkboxes_** 

| Unselected | Hover | Selected|
|-------------------- | ------ | --- |
![image](https://cloud.githubusercontent.com/assets/13420618/24776590/6df44768-1aef-11e7-99e1-0fce62c0f739.png) | ![image](https://cloud.githubusercontent.com/assets/13420618/24776794/60c1158e-1af0-11e7-83e9-2c9165c62c90.png) | ![image](https://cloud.githubusercontent.com/assets/13420618/24776598/76ec6f94-1aef-11e7-9a20-697ec3567ba5.png)
| Border and icon hex# 212121 | Border and icon  hex#0071BC | Inner shadow with hex#0071BC
[Unselected SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter%20unselected%20Icon.svg) | [Hover SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter%20hover.svg) | [Selected SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter%20selected%20Icon.svg)

## Related issue
https://github.com/department-of-veterans-affairs/caseflow/issues/1780

**Comment by abbyraskin** [comment]
@gnakm would you mind making this AC a little clearer once the interactions are fleshed out (particularly the last bullet and anything I missed)

**Comment by gnakm** [comment]
@abbyraskin 

RE: `- Verify that the colored category icon displays next to each document row after selecting a filter, and that any additional categories associated with the document that were NOT selected in the filter are displayed in an [outline state??]`

I think if there are additional categories associated with the doc that were not selected, we should just show as it is (see mocks above). I'm thinking of the way github labels are sorting.. if we filter only whiskey, we will still see all the other labels associated with the issue.

**Comment by abbyraskin** [comment]
okay, awesome, that makes sense to me (and I like that it avoids adding an unnecessary additional state!). I'll edit the AC.

**Comment by abbyraskin** [comment]
Note: we removed the tabs menu

**Comment by NickHeiner** [comment]
Is the "selected" state for the filter icon for when there is a filter applied, or when the dropdown filter is open, or both?

![image](https://cloud.githubusercontent.com/assets/829827/25252487/2ac00480-25eb-11e7-997c-cdb6055738ee.png)

**Comment by gnakm** [comment]
@NickHeiner Both!

**Comment by NickHeiner** [comment]
:+1: thanks!

**Comment by kierachell** [comment]
## Returning from Document View:
1. Click filter
1. See it work
1. Open document
1. Move to next document
1. Go Back to all documents
1. Click filter
1. Be sad
![buttondies](https://cloud.githubusercontent.com/assets/18075411/25565028/d4530b38-2d8d-11e7-9e77-8c9095bd50e9.gif)

## Dropdown started showing up in weird positions:
### Expected:
<img width="285" alt="screen shot 2017-04-30 at 10 17 21 am" src="https://cloud.githubusercontent.com/assets/18075411/25565048/3f76e862-2d8e-11e7-8c44-9d460c579df0.png">

### Current:
<img width="681" alt="screen shot 2017-04-30 at 10 16 23 am" src="https://cloud.githubusercontent.com/assets/18075411/25565042/23116044-2d8e-11e7-93a4-179728493c3b.png">
<img width="258" alt="screen shot 2017-04-30 at 10 17 04 am" src="https://cloud.githubusercontent.com/assets/18075411/25565051/4665058c-2d8e-11e7-9364-a10af54ae338.png">



## Last AC is not functional?
> Category and issue tags behave with one another as “and” — if I select a medical category filter, then select a “right knee” issue filter, I’ll see every document that contains both a medical filter AND right knee issue tag.

**Comment by mdbenjam** [comment]
@kierachell Ah, good catch. We went back and forth on that AC. It was written as and here, but we later decided on or. @abbyraskin @gnakm 

I've also fixed the weird positioning bug in another merge

**Comment by abbyraskin** [comment]
@mdbenjam this AC is referring to the relationship between issue and category tags, when they're both selected -- I think it's still accurate? i think we decided it's "or" between search and filters, but and between filter types.

**Comment by gnakm** [comment]
^ yes on "we decided it's "or" between search and filters, but "and" between filter types."

**Comment by kierachell** [comment]
**PASSED**

Seems to be working in `preprod`
