### ISSUE TITLE
Document Viewer | Delete comment confirmation

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1433]
**Story**
When clicking "delete" on a document, I want to receive a confirmation message, so I don't delete a comment by accident.

## Acceptance Criteria
- Clicking the "Delete" link on a given comment should launch a cancelation modal
- Clicking the `Confirm delete` button on the modal should close the modal and remove the comment
- Clicking the `Cancel` button on the modal undos the action -- closing the modal and returning the user to the view they were on before clicking the delete link 
- When the modal is active, everything else on the page except the header should be grayed out
- The only way to get out of the modal is by clicking cancel

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24630342/55335992-188a-11e7-8e95-2248ff61afb2.png)

**Comment by abbyraskin** [comment]
@gnakm this needs some mock love when you have a chance

**Comment by abbyraskin** [comment]
Also, does clicking outside the modal (the grayed area) cancel the action as well?

**Comment by gnakm** [comment]
@abbyraskin I answered your questions in AC above.

**Comment by mdbenjam** [comment]
@gnakm Should we have an 'x' in the top right corner to close. The modal in the styleguide has this.

**Comment by mdbenjam** [comment]
@gnakm Question 2: The modal on the styleguide currently grays out the header. Are we changing that behavior here?

**Comment by gnakm** [comment]
@mdbenjam Yes can we add that x ? I can add that to the AC
Let's gray out the header as well. Will change in the mocks as well.

**Comment by kierachell** [comment]
I am...sorry to do this...


but


<img width="1238" alt="screen shot 2017-04-12 at 10 03 42 pm" src="https://cloud.githubusercontent.com/assets/18075411/24987084/ea035b56-1fcb-11e7-8a41-a1a1118de635.png">

please note the verbiage in the document displayed.

**Comment by abbyraskin** [comment]
updated AC. I owe you 🍦@mdbenjam...

**Comment by kierachell** [comment]
<img width="210" alt="screen shot 2017-04-13 at 9 04 47 pm" src="https://cloud.githubusercontent.com/assets/18075411/25029593/dd1a4294-208c-11e7-808a-b54495000dd8.png">
👁 


hmmmmmm.....

**Comment by mdbenjam** [comment]
@abbyraskin wait, what changed? @kierachell there's another ticket for that.

**Comment by abbyraskin** [comment]
@mdbenjam just the "Confirm delete" button text in sentence case

**Comment by mdbenjam** [comment]
Ah okay cool :)

**Comment by kierachell** [comment]
**PASSED**
Checked on preprod.
![deletecomment](https://cloud.githubusercontent.com/assets/18075411/25066060/9c3da7b2-21e9-11e7-92e8-5caebf291f42.gif)


There's only one bug that is captured by: #680
