### ISSUE TITLE
Explore log management tools for Rails logs

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14345]
# Log management tools
Explore log search and log viewer tools.

## Context
We have Kibana and AWS Cloudwatch Logs to search through our Rails server logs and help diagnose problems. [Existing tools here](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#%EF%B8%8F-handy-links-for-diagnosing-issues). However these tools are difficult and/or cumbersome to use, and it's difficult to find the logs we need.

## Overview
There are many tools out there that could improve the way we access and use our logs. The goal of this ticket is to explore log search and viewer tools, such as these:
* https://blog.overops.com/6-log-management-tools-you-need-to-know-and-how-to-use-them/
* https://www.loggly.com/solution/ruby-logger/
* https://gorails.com/tool_categories/logging/tools

End-users are mainly engineers who have to diagnose reported problems based on a user session, sequences of user actions, or UI elements displayed to the user at a specific time or time range.

## Challenges
* Logs are distributed across EC2 instances and are collected by AWS
* Logs are semi-structured. Sentry does a good job of parsing Javascript-based logs.

**Comment by yoomlam** [comment]
Timebox to 3.

**Comment by yoomlam** [comment]
@nanotone Since you have some experience with Kibana and AWS Cloudwatch log tools, please add your input to this ticket.

**Comment by hschallhorn** [comment]
What engineers currently use to parse though these logs: [aws-log-parser.rb](https://dsva.slack.com/archives/C2ZAMLK88/p1592505047301200)
