### ISSUE TITLE
Navigation Bar | User Menu | Help link goes to Certification Help page

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#1435]
# Description
When the user clicks on the Help link in the User Menu, they are taken to the Certification Help page.  This is not helpful.  They should be taken to the Dispatch Help page.

**Validated in the following Environment(s):**
- [ ] Production
- [ ] UAT
- [x] Demo
- [ ] Development

## Reproductive Steps
1. Log into Dispatch.
2. In the User Menu, click on the link "Help".  The Certification Help page is displayed.

## Acceptance Criteria
1. While in Dispatch, open the User Menu and click "Help".  The **Caseflow Dispatch Help** page should be displayed.
2. While in Certification, open the User Menu and click "Help".  The **Caseflow Certification Help** page should be displayed
3. Click on the logo on the far left of the header.  The **Caseflow Help** page should be displayed, containing links to **Caseflow Certification Help** and **Caseflow Dispatch Help**

## Screen Shots
![image](https://cloud.githubusercontent.com/assets/23063044/24628571/e865becc-1884-11e7-9956-89c4f3f7d395.png)

# Related Stories
Navigation | Help | Create Dispatch help page [#1430](https://github.com/department-of-veterans-affairs/caseflow/issues/1430)

**Comment by mmlumba** [comment]
@shanear @lakohl Since there will be more than one help page (and the help page is normally the root of the application), where should the homepage of the app lead to?

**Comment by slj** [comment]
Solution in action:
![context-help](https://cloud.githubusercontent.com/assets/1053255/25281079/3808c480-267a-11e7-9c04-5106df3953a9.gif)

**Comment by slj** [comment]
@marian I spoke with @lakohl, and for now homepage requests will be routed to a Help index page:

<img width="570" alt="screen shot 2017-04-27 at 10 55 27 am" src="https://cloud.githubusercontent.com/assets/1053255/25547336/a3bb0570-2c34-11e7-8c89-a3ff7094e769.png">

**Comment by slj** [comment]
Updated Description with acceptance criteria.

**Comment by kierachell** [comment]
**PASSED**
AYY!
<img width="1052" alt="screen shot 2017-05-02 at 7 39 34 pm" src="https://cloud.githubusercontent.com/assets/18075411/25643736/37f80c0a-2f6f-11e7-8a2a-55f73d2d826d.png">
<img width="1014" alt="screen shot 2017-05-02 at 7 40 15 pm" src="https://cloud.githubusercontent.com/assets/18075411/25643735/37f37ed8-2f6f-11e7-8c69-2d69d5e1863a.png">
