### ISSUE TITLE
Research: options for early conversion of central to virtual hearings

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#14355]
## Description
Research the relative merits of these solutions:

1. Create a new docket day on a nearby location (that is a video location) and transfer veterans there.
2. Make the central office a video location for now?
3. Create a new Washington, DC location with a different name that has video capabilities. There is an unused VACOLS location number 72 (also called 372 in longform) that we could adopt.
    - Would require 1 too (?)

Investigate how many Central Office scheduled Veterans are based outside of ET (can match on postponed + central query)

### Open questions
- For all options, how would we manage timezones for Veterans who are based in non-ET?
- How do users currently transfer Veterans to another location's docket? How often does this happen?

**Comment by ferristseng** [comment]
### Data

> Investigate how many Central Office scheduled Veterans are based outside of ET (can match on postponed + central query)

```
irb(main):036:0> ch.select { |h| h.disposition == 'postponed' }.count
=> 128
```

> For all options, how would we manage timezones for Veterans who are based in non-ET?

- There are non-ET veterans. Majority are in ET, but there are enough that aren't that we shouldn't do it manually.

> How do users currently transfer Veterans to another location's docket? How often does this happen?
- (Ferris) I've done these requests for batteam, so it's a manual process that's not possible from the UI. It only has happened retroactively when a veteran has had a hearing in a place they weren't scheduled for
- We could write a script for that if there is a set way of doing that

### Approaches

*Only will update central + postponed hearings*

 > 1. Create a new docket day on a nearby location (that is a video location) and transfer veterans there.
- How many hearings can we have per-docket?
- Will need a new docket day for each central hearing day

> 2. Make the central office a video location for now?

- Where do we need to make this change for Legacy hearings? Is it on the case record in VACOLS, or the Caseflow hearing day
- Is this too much work?
  - If this requires a code change, what does that look like?
  - Is this too much data to touch?
- What is the impact in other parts of the application for changing this via. console?
- How/when do we change the data back?

> Create a new Washington, DC location with a different name that has video capabilities. There is an unused VACOLS location number 72 (also called 372 in longform) that we could adopt.
>   - Would require 1 too (?)

- Where is this, and what is it used for? `VACOLS location number 72 (also called 372 in longform)`
- Same problems as 1

> Proposal: Write a script to create a virtual hearing for each postponed video hearing, and set it up so it thinks the emails have sent. Ask that the HC manually send out the generated link and time.

**Comment by ferristseng** [comment]
> 1. Create a new docket day on a nearby location (that is a video location) and transfer veterans there.

In dev, we were able to successfully:

  - Move a postponed Central hearing to a video hearing day by updating the `hearing_day_id`
  - Reschedule the postponed hearing to a different video hearing day
  - Change the hearing to a virtual hearing through the UI

The only issue we are having is we aren't able to "reverse" this process to ensure the integrity of the data. Once new hearings are scheduled, we're not confident we can track the data and migrate it back to a Central hearing day. We are thinking that once we make these changes they would be permanent.

**Comment by ferristseng** [comment]
We found an option that is available through the UI to do this. Closing for now unless that option doesn't work in production.
