### ISSUE TITLE
Add reason field to cancel task modal

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14351]
## User or job story
User story: As a user that has the ability to cancel a task, I need to be able to add reasoning as to why I cancelled the task, so that other users can see the reasoning without having to reach out to me outside of Caseflow when necessary.

## Acceptance criteria
- [x] There is an open text box field in the cancellation modal for instructions
- [x] The cancellation reasoning is added to Case timeline
- [x] Field should be required when cancelling a task
- [x] Screenshots provided for UI updates

## Release notes
When cancelling a task, users are now able to add the reason for the cancellation in the cancel task modal. 

### Technical notes
PR as example on how to add instructions to a modal! https://github.com/department-of-veterans-affairs/caseflow/pull/14326

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||||
3 | |||
5 | 
8 | 
```

Should append to the instructions.

#### Why 2?
* Straightforward, acts like most our other modals, have example PR of adding this field to a modal and updating the backend if needed

#### Why 3?
* Maybe a little work to allow different UI title, wording, etc
