### ISSUE TITLE
Change ConfirmScheduleHearing task routing logic to follow routing of ScheduleHearing task

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14363]
## Description
Change routing on `ConfirmScheduleHearing` task to follow the routing of the `ScheduleHearing` task such that the appeal arrives back on the Schedule Veterans page(s). 

If attorneys have the ability to create the `ScheduleHearing` task in their Actions menu, the `ConfirmScheduleHearing` task can be deprecated.

### Alternate (less ideal) options
- Keep both `ConfirmScheduleHearing` task and `ScheduleHearing` task, with existing routing, but expose both in the attorney Actions menu.
- Rename `ConfirmScheduleHearing` task to be more explicit this task will sit in the Hearing Management Branch queues, this could be something like "hearing needs to be scheduled, create schedule hearing task" task. (This is the task that the Hearing Management Branch assigns to route the appeal back to Schedule Hearings.)

## Acceptance criteria
- [ ] Update task documentation

## Background/context/resources
Appeals are sitting in the Hearing Management queue with a `ConfirmScheduleHearing` task. However, none of these appeals intended for scheduling go to Schedule Veterans and instead are held in a management queue for a user to add "hearing needs to be scheduled, create schedule hearing task" (first option in Actions). Attorneys/counsel [and other Board users] think they're sending the appeal to be scheduled for a hearing but instead are sending it to a management team whose members then have to go in and one-by-one clear to route to scheduling.

Since 4/1/2020, roughly 200-250 of these tasks are created a month. The rolling average of time to close these tasks has dropped steadily since then from several weeks to ~2-3 days.

Current Management flow for re-routing appeals for hearing scheduling:
- Select "hearing needs to be scheduled, create schedule hearing task" 
  - Language doesn't make sense since it'll send to charge 57 in VACOLS
- Select "send case"
- Open VACOLS
  - It'll be pulled into VACOLS location 57
- Charge back to Caseflow. It takes ~20-60 minutes to populate back to Caseflow in Schedule Hearings

## Open questions
- How will the HMB catch CAVC cases? Charge back to VACOLS? Will HMB pull a report and route these?
  - These should be weighted in the docket order as they are priority.
- Are they already weighted in docket order? Was it implemented such that CAVC cases show up at the top of the Hearing Schedule queue?

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-1653
