### ISSUE TITLE
Store cancelled_by_id in task table

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14365]
Currently, to show who has cancelled a task in case timeline, we are interrogating papertrail records to find out who cancelled a task
https://github.com/department-of-veterans-affairs/caseflow/blob/660bcf53cec1b933a8041a4955ae345186f84609/app/models/task.rb#L584-L594

Papertrail is a diagnostic and investigation tool, not something we should be using to display information to a user. Instead, we should store the id of the canceler on the actual task.

### AC
- [ ] task.cancelled_by is stored in the task table itself
- [ ] Tasks in prod are updated based on the versions record
- [ ] add a comment to [Create Cancelled_By_ID in Task Table #123](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/123) noting that this ticket is done

### Suggested steps
1. Add cancelled_by_id migration to the tasks table
1. Add association in task model `belongs_to :cancelled_by, class_name: "User"` and remove cancelled_by hacky method
1. Ensure we're saving the canceller id when we cancel tasks. Including 
   1. when the last issue on an appeal is removed (and we cancel all tasks)
   1. when the cancellation of a task cascades up or down a task tree
1. Backfill any nil cancelled_bys on cancelled tasks by checking the paper trail records, if they exist
```ruby
Task.cancelled.each do |task|
  any_status_matcher = Constants::TASK_STATUSES.keys.join("|")
  task_cancelled_version_matcher = "%status:\\n- (#{any_status_matcher})\\n- #{Constants.TASK_STATUSES.cancelled}%"
  record = task.versions.order(:created_at).where("object_changes SIMILAR TO ?", task_cancelled_version_matcher).last

  record&.whodunnit
end
```

### Notes
- [ ] Be sure to add :cancelled_by to [task_includes](https://github.com/department-of-veterans-affairs/caseflow/blob/ba8b8ad060d7d37c1c38a7df1eefd0fc41c411b6/app/workflows/tasks_for_appeal.rb#L61) to ensure we're eager loading these users for all tasks on an appeal

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||
5 | ||||
8 | 
```

Review Bat Team docs and update any reference scripts that cancel to update this field

#### Why 3?
* add column, add code to update column and check column
* straightforward, but a few moving parts

#### Why 5?
*  May be hard to track down all places we cancel tasks. Will we have the cancelling user here as well?

**Comment by pkarman** [comment]
Note that this info should already be available w/o adding a new column.
the task.versions should have record of who changed the status and when.

**Comment by hschallhorn** [comment]
Hacky method pulled from code for reuse in backfill.

```ruby
  def cancelled_by
    return nil unless cancelled?

    any_status_matcher = Constants::TASK_STATUSES.keys.join("|")
    task_cancelled_version_matcher = "%status:\\n- (#{any_status_matcher})\\n- #{Constants.TASK_STATUSES.cancelled}%"
    record = versions.order(:created_at).where("object_changes SIMILAR TO ?", task_cancelled_version_matcher).last

    return nil unless record

    User.find_by_id(record.whodunnit)
  end
```

**Comment by hschallhorn** [comment]
Updating tasks in prod draft. We can only update tasks that were cancelled and have a whodunnit in their versions records

```ruby
any_status_matcher = Constants::TASK_STATUSES.keys.join("|")
task_cancelled_version_matcher = "%status:\\n- (#{any_status_matcher})\\n- #{Constants.TASK_STATUSES.cancelled}%"

Task.cancelled.each do |task|
  whodunnit = task.versions.order(:created_at).where("object_changes SIMILAR TO ?", task_cancelled_version_matcher).where.not(whodunnit: nil).last&.whodunnit
  task.update!(cancelled_by_id: whodunnit) if whodunnit
end
```

**Comment by hschallhorn** [comment]
```ruby
Task.cancelled.where.not(cancelled_by_id: nil).count
=> 886

any_status_matcher = Constants::TASK_STATUSES.keys.join("|")
task_cancelled_version_matcher = "%status:\\n- (#{any_status_matcher})\\n- #{Constants.TASK_STATUSES.cancelled}%"

tasks = Task.cancelled.where(cancelled_by_id: nil)
versions = PaperTrail::Version.where(item: tasks).where("object_changes SIMILAR TO ?", task_cancelled_version_matcher).where.not(whodunnit: nil)

version = versions.limit(1).first
version.item.update!(cancelled_by_id: version.whodunnit)
version.item.cancelled_by_id
=> 11140

versions.each { |version| version.item.update!(cancelled_by_id: version.whodunnit) }
```
