### ISSUE TITLE
Remove OT status for cases that are reassigned

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14366]
## Description
In the following situations the overtime status should be removed from the case: 

Judge or case movement user reassigns case to another judge
Judge or case movement user reassigns attorney task to a new attorney

## Acceptance criteria
- [ ] This is only done for workmodes on an appeal, not updating the vacols decass record or attorney case review
- [ ]  OT status is removed when a judge or case movement user reassigns a case to another judge
   - [ ] Ama
   - [ ] Legacy
- [ ] OT status is removed when a judge or case movement user reassigns an attorney task to another attorney
   - [ ] Ama
   - [ ] Legacy

## Background/context/resources
[Slack Conversation](https://dsva.slack.com/archives/CJL810329/p1589996371093700)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||||||||
5 | 
8 | 
```

might be two PRs, unless the changes are straightforward.

#### Why 1?
* 

#### Why 2?
* 

#### Why 3?
* Unsure of where this should happen. Easy enough to do in the reassign function to do a check on the task type
* Unsure of where this is handled for legacy appeals, probably.
  - can we reassign judges and atty in Caseflow for legacy appeals?
  - Only reassign judge tasks at judge assign, updated AC :ballot_box_with_check: :tada:

**Comment by hschallhorn** [comment]
Closed in #14452

**Comment by hschallhorn** [comment]
Not complete! 
![ezgif-1-b0b5ed2bb8b2](https://user-images.githubusercontent.com/45575454/86835129-aa54ba80-c069-11ea-8b7c-4ab4da5ed28a.gif)

Steps to reproduce:
Mark a legacy appeal as overtime and assign to an attorney
Go to the attorney’s queue in your assign page
Select the overtime legacy case and assign to another attorney
Go to case details of that case
Notice it still has an overtime badge
