### ISSUE TITLE
Documents List | Issue tags: filter Documents List view by issue tag(s)

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1438]
**Story**
When looking at the Documents List, I want to filter by issue tag(s) so I can only see documents relevant to the issue I'm working on.

## Dependent Story
**_Note: For more details and specs about dropdown, check issue on issue filter dropdown_** #1477

## Acceptance Criteria
**Filter Icon and dropdown**
- Validate that when the filter icon is clicked, the filter icon next to the word Issue Tags in column header is in active state and the filter dropdown appears (see #1477)
- Validate that a user can dismiss the filter icon by clicking away or clicking on the filter icon again
- Validate that if a user selects issue filter(s) the filter icon remains in active state
- Validate that if a user does not select any issue filter(s), the filter icon returns to inactive state when dismissed

**Filter behavior**
- Verify that no issues are selected by default when a user logs in, and the filter icon is set to the inactive state 
-  Verify that if a user filters by issue tag, then opens a document, then clicks "Back to all documents" button, the filters persist
   - otherwise the filtered state resets on refresh 
- Validate that the dropdown contains all of the issue types user has entered
- Validate that when an issue is selected (either by clicking the name or specifically the checkbox), the dropdown shows it being checked off and the list then is filtered by the issue type(s)
- Validate that more than 1 issue can be selected, and that the documents list filters to show everything with at least one of the selected issue filters (behaves as "or")
- Validate that when clicking Clear issue filter (option 1 in dropdown), the options that were checked on dropdown uncheck and the document list shows all documents
- Category and issue tags behave with one another as “and” — if I select a medical category filter, then select a “right knee” issue filter, I’ll see every document that contains both a medical filter AND right knee issue tag.

## Mockups

**Document list view**
![image](https://cloud.githubusercontent.com/assets/13420618/25668885/f1420df6-2ff5-11e7-914b-95ec14c5d2c6.png)

**Dropdown**
![image](https://cloud.githubusercontent.com/assets/13420618/25245907/0607eef8-25d4-11e7-9894-4dc011b5aee3.png)

**Max width for fitting in issue tags**
![image](https://cloud.githubusercontent.com/assets/13420618/24775337/602f8dd6-1aea-11e7-812c-726ee56dfaaa.png)

## Note
Veteran ID was taken out of header. See [Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)
for updated visual

## Related issues

Issue tag filter dropdown styling #1477

**Comment by abbyraskin** [comment]
General note: we are no longer using the tabs shown in the mock (everything else is the same though)

**Comment by abbyraskin** [comment]
Note: we made some style changes to the issue tag filter component in #1477

**Comment by gnakm** [comment]
FYI Right now the issue tags dropdown doesn't show a hover. If this is already being address through this issue, please close this: #1809

**Comment by astewarttistatech** [comment]
Blocked by the ability to not create issue tags

**Comment by kierachell** [comment]
<img width="528" alt="screen shot 2017-05-03 at 11 32 29 am" src="https://cloud.githubusercontent.com/assets/18075411/25668347/6f6cd794-2ff4-11e7-90ec-547942ef2905.png">
<img width="359" alt="screen shot 2017-05-03 at 11 32 39 am" src="https://cloud.githubusercontent.com/assets/18075411/25668348/6f6e8b48-2ff4-11e7-9bfa-69dfefccbe5c.png">
<img width="846" alt="screen shot 2017-05-03 at 11 34 16 am" src="https://cloud.githubusercontent.com/assets/18075411/25668359/75491074-2ff4-11e7-83c2-d3fc618f296b.png">

**Comment by gnakm** [comment]
@kierachell We decided to take out `see more...` for the pilot. We adjusted the table so that there is more room for issue tags and because see more is kinda complicated. We will allow the tables to show all issues. Our hypothesis is that users at average won't be putting more than 3, rare use case ~8.

**Comment by abbyraskin** [comment]
#1538 incorporates the new table sizing - removing those AC from this ticket.

**Comment by abbyraskin** [comment]
re: dropdown width, now covered by  #1899

**Comment by kierachell** [comment]
**PASSED**
