### ISSUE TITLE
Store Appellant/Veteran and POA timezone in database

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14386]
## Description

Store Veteran/Appellant and/or POA timezone in database to consider the field when displaying time of hearing.

## Acceptance criteria
- [ ] Ensure some of the existing time logic that pulls from the RO looks
  - [ ] Add unit tests
- [ ] Ensure if the TZ is set, the emails will display the time in the veteran/appellant/POA's timezone

## Background/context/resources

Supports the central office hearing to virtual hearing conversion (and virtual-only dockets in the future).

## Technical notes

  - What format should time timezone be stored in? As a string?
  - Where should the timezone be stored? Storing it on the hearing makes sense, but if a veteran has multiple hearings (common case would be a hearing getting postponed), it would be nice for Caseflow to automatically populate the TZ from historical data. 
  - Store on Veteran object to be applied globally? 
  - Or virtual hearing? Storing on virtual hearing might cause data errors? Or might create a good record regarding the hearing.
- Veteran object is a cached version of data in BGS, traditionally haven't been storing in Caseflow db
- Shouldn't store on Person since that includes POAs and it is definitely a cached object

**Comment by sahalliburton** [comment]
Based on discussion with the team the following was decided as the best approach:

- Add 2 additional fields to the virtual_hearings table
  - poa_tz: 3 character string representation of the  Representative/POAs timezone
  - appellant_tz: 3 character string representation of the Appellant timezone
- Calculate the time on the frontend using MomentJS to parse the date based on the stored timezone

Using this approach, we will be able to set the timezone for the appellant as well as potentially suggest a time based on timezone from previous virtual hearings for the appellant. Additionally, this will allow for correct calculation of the timezone even if the appellant changes address as the data would be collected per virtual hearing as opposed to per appellant.

**Comment by pkarman** [comment]
could we store those tz values on `claimants` and `bgs_power_of_attorneys` instead so they are stored in one place? or is the idea that they might change from hearing to hearing?

**Comment by sahalliburton** [comment]
There is not an indication that I am aware of that they would change from hearing to hearing so that would make sense to me to store it in those places respectively so the data would not be duplicated. @ferristseng and @rubaiyat22 do you have any objections to us taking this approach?

**Comment by ferristseng** [comment]
I think the value can change from hearing to hearing -- for example,  if someone moves. I think it could potentially be useful to have the historical data in that case. If it's useful to track the TZ on the claimant/POA-level too, we could save it in both places.

**Comment by pkarman** [comment]
both/and seems useful. If we have a value on the `claimant` then we can offer that as a default. Same for POA.

**Comment by rubaiyat22** [comment]
I think it might be better to store the timezone as "full name" (not sure what to call it) as opposed to abbreviations like `America/New_York` over`EST` because it's easy to convert time for a specific timezone using ruby `in_time_zone` method which only takes the full string. For example
> '2019-03-01 12:00'.in_time_zone('PST')
ArgumentError (Invalid Timezone: PST)

Mentioned in https://en.wikipedia.org/wiki/Time_zone
> Time zones are often represented by alphabetic abbreviations such as "EST", "WST", and "CST", but these are not part of the international time and date standard ISO 8601 and their use as sole designator for a time zone is discouraged. Such designations can be ambiguous; for example (from List of time zone abbreviations), "CST" can mean China Standard Time (UTC+8), Cuba Standard Time (UTC−5) and (North American) Central Standard Time (UTC−6). It is also a widely used variant of ACST (Australian Central Standard Time, UTC+9:30).

The other option could be to use the offset but that does not account for daylight savings.
