### ISSUE TITLE
Build out feature flag for Central Office-to-virtual conversions

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14387]
## Description

Build out new feature flag for Central Office-to-virtual conversions

Proposed feature flag name: `schedule_virtual_hearings_for_central`

## Acceptance criteria

- [ ] Confirm user with feature flag can see hearing type dropdown for CO hearings
- [ ] Confirm user w/o feature flag _can't_ see hearing type dropdown for CO hearings

## Background/context/resources

N/A

## Technical notes

- This can be incorporated into https://github.com/department-of-veterans-affairs/caseflow/pull/13832.
- IMO, this flag should _only_ control the visibility of the hearing type dropdown for CO hearings

**Comment by rubaiyat22** [comment]
PR for adding new flag in deployment: https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2772

**Comment by rubaiyat22** [comment]
Incorporated the flag https://github.com/department-of-veterans-affairs/caseflow/pull/13832 with this commit https://github.com/department-of-veterans-affairs/caseflow/pull/13832/commits/7e174d2d0fc7aa550e302e0a2cb357e5ea3b5e72

**Comment by rubaiyat22** [comment]
confirm in prod console that feature flag is working
