### ISSUE TITLE
Investigate new path for Convert to Virtual page

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14389]
## Description

There are a couple of options we could take to implement the new convert-to-virtual form. This ticket would be investing those options since this is a new-ish (?) way of going through a multi-step workflow.

- Create a completely new page, with a new route/path. Switching the hearing type dropdown would redirect to a new page
  - Q: Would this lose any current changes the user has?
- Create an alternate view for the existing `HearingDetails` page that is toggled when the hearing type dropdown changes
- Depending on method used, note the requirement in new Convert to Virtual page:
  - If the user has other unsaved changes on the Hearing Details page, `[the browser default "unsaved changes" window appears?]`

## Acceptance criteria

- [ ] Timebox investigation to determine best route for new Convert to Virtual page
- [ ] Update issue with findings for historical context

## Background/context/resources

The print view uses the same component that displays different child component(s) based on state.

## Technical notes

N/A

**Comment by sahalliburton** [comment]
Investigation Notes (also see [writeup](https://hackmd.io/4Wv3uFPKSb6yalrFUD2mqQ)):

- Create a completely new page, with a new route/path. Switching the hearing type dropdown would redirect to a new page
    - Q: Would this lose any current changes the user has?
    - A: If the user is redirected to a new page, this would require a page reload and lose any unsaved changes that might already exist on the page. In order to account for this, we would need to implement a prompt to prevent the user from proceeding if they have unsaved changes
- Create an alternate view for the existing `HearingDetails` page that is toggled when the hearing type dropdown changes

**Recommendation**

Based on the investigation detailed below, it is my recommendation that we take the approach of adding an alternate view to the existing details page. This approach would not require as many changes and it would allow us to reuse a lot of existing code

**Comment by ferristseng** [comment]
@sahalliburton Can we close this since we've started on the implementation?

**Comment by sahalliburton** [comment]
Yeah I will go ahead and close this

**Comment by sahalliburton** [comment]
Closing because implementation has been started as part of ticket #14421
