### ISSUE TITLE
Modify header styles to match designs

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#144]
Also migrating from Bootstrap to Bourbon/Neat/Bitters/Refills as specified by the Web Design Guielines.
Blocks #106

**Comment by webinista** [comment]
Does anyone know off hand whether there's a session variable that contains the name of the application screen? 
![header](https://cloud.githubusercontent.com/assets/354277/11130343/8446e92e-8952-11e5-96b3-f7ea55120c53.png)

**Comment by paultag** [comment]
@webinista I don't think we have that anywhere currently -- mind filing a new bug? We can figure out a way to get that to the view, sure!

**Comment by paultag** [comment]
(Another case where I wish we had the `extend` model from Django/Jinja2)

**Comment by webinista** [comment]
Blocker is resolved and so is this.
