### ISSUE TITLE
Reported virtual hearing emails not received

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14400]
## Story
Some Caseflow users are intermittently letting Caseflow members that virtual hearing email recipients are reporting not receiving emails that are generated by Caseflow.

## Adding information to table 
If an email is reported as not received, please add it to the table below with the status of "New". If you don't know the Hearing Detail or Daily Docket links, please leave that blank.

## Resolving
Please note your first name in `Tango Assignee` along with any notes and status.

Tango assignee | Tango notes | Status | Date reported | Reported issue | Caseflow link 
--- | -------- | ------------ | ---------------- | --- | --- 
Rubaiyat | Both vlj and rep emails had failed to send. Manually restarted the job which successfully sent out the emails | Completed from caseflow's perspective | 05/27/20 | VLJ bvamherman didn't receive email — May 29 hearing | https://appeals.cf.ds.va.gov/hearings/743077/details 
Rubaiyat | According to granicus email was sent out successfully | -- | 05/26/20 | Representative didn't receive email — May 26 hearing | https://appeals.cf.ds.va.gov/hearings/525352a4-fc74-40e8-9ae2-18942b77dadb/details
Rubaiyat | According to granicus email was sent out successfully | -- | 05/26/20 | Representative didn't receive email — May 26 hearing | https://appeals.cf.ds.va.gov/hearings/ac00af2d-f156-4eb3-b53c-299e4f1671d6/details

## Possible resolutions
- Check Granicus status

If VLJ didn't receive email
- Check to see if `BGS VLJ email address` is the same as `VA VLJ email address`. There have been reported cases of mismatching emails to other VA employees, which is resolved by Board members submitting tickets to CSUM/BGS.

**Comment by rubaiyat22** [comment]
https://appeals.cf.ds.va.gov/hearings/743077/details

```
hearing = LegacyHearing.find_by(vacols_id: "743077")
pp hearing.email_events
=> [...,
#<SentHearingEmailEvent:0x000000000c5d87c8
  id: 1389,
  external_message_id: /messages/email/414281100,
  recipient_role: "judge",
  email_type: "confirmation",
  email_address: [redacted],
  sent_at: Tue, 26 May 2020 16:47:20 UTC +00:00,
  sent_by_id: 2199,
  hearing_type: "LegacyHearing",
  hearing_id: 170486>,
...]
```

Checking granicus to see the status of email
```
curl https://tms.govdelivery.com/messages/email/414281100/recipients \
  -L \
  -H 'X-Auth-Token: [redacted]'
=> [..."status":"failed", ..., "error_message":"[Message Expired] Exceeded MaxAttempts - 452 4.3.1 Your message could not be delivered to the intended recipient. This may because your message is characterized to be unsolicited email or from an untrusted mail delivery system.  We sincerely apologize for any inconvenience this may have caused.  If you feel you have received this message in error, please feel free to contact the Department of Veterans Affairs Enterprise Service Desk at 1-855-673-HELP (4357) for assistance.",...]
```
Checking bgs email
```
ExternalApi::BGSService.new.fetch_person_info(hearing.judge.participant_id)
=> {..., :email_address=>nil, ...}
```

will check back tomorrow to see if it has been updated

**Comment by rubaiyat22** [comment]
https://appeals.cf.ds.va.gov/hearings/525352a4-fc74-40e8-9ae2-18942b77dadb/details
https://appeals.cf.ds.va.gov/hearings/ac00af2d-f156-4eb3-b53c-299e4f1671d6/details

both of the representative emails were sent according to grancius
