### ISSUE TITLE
Consolidate all the documents check components under one component and one route

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1440]
We currently have separate routes for already certified, documents check, not ready for certification, etc. These should be consolidated under one `certifications/VACOLS_ID/documents_check` route. We want to allow the user to enter certification, have the documents check fail, go off and modify other documents in VACOLS or VBMS, then reload the page and see the documents check succeed.

# Acceptance Criteria

 The user should be able to enter Certification, have the documents check fail, go off and modify other documents in VACOLS  or in VBMS, then reload the page and see the documents check succeed.

Here is an example of what this page should look like (not shown is the new progress bar above the app canvas):

![mismatcheddocs](https://cloud.githubusercontent.com/assets/1178390/24969879/48122e1c-1f80-11e7-855a-b47400a51abf.png)

**Comment by astewarttistatech** [comment]
@amprokop @shellicious if there are any mocks of the failed scenario to add to AC, that would be helpful.

**Comment by shellicious** [comment]
@astewarttistatech added a mock above, @amprokop let me know if i misinterpreted what you meant by fail state.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in Preprod
Browsers: Chrome and FF

Steps to Validate: 
1. Access Certification V2 (Check Documents page) with a veteran who is missing all or some of their documents
2. Open another window and add the missing documents in the corresponding environment of  VBMS. 
3. Reload the Check Documents page to find that all of the veteran's documentation is now there. 

Screenshots: 
<img width="924" alt="screen shot 2017-04-19 at 9 20 46 am" src="https://cloud.githubusercontent.com/assets/23038505/25247411/b8f769ea-25d8-11e7-808b-a383f38ba451.png">
<img width="1249" alt="screen shot 2017-04-19 at 9 27 58 am" src="https://cloud.githubusercontent.com/assets/23038505/25247410/b8f4627c-25d8-11e7-9ead-a8a7fc3dd589.png">
