### ISSUE TITLE
Intake | Upstream Error | Add error classes (and ignore in Sentry)

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14417]
## Description
For VBMS Upstream Errors we like to add error classes for different causes of the generic HTTP Error.  This allows us to ignore them in Slack.

that do not yet have their own 

## Acceptance criteria
- [ ] Check upstream errors that currently have the generic VBMS HTTP Error class, and add classes for them (detect using a snippet of the error message)
- [ ] Add them to the list of errors we ignore in Slack

## Technical notes
In connect_vbms, see the `connect_vbms/lib/vbms/errors.rb`

In prod, look at "establishment_error" on HLRs and SCs, and look for ones that do not have their own error class to find ones that aren't yet handled.

**Comment by wdrougas-tista** [comment]
## Error Classes Added: 

EmptyContentionTitle
InvalidBenefitTypePayeeCodeOrEPCode
CannotDeleteContention - This error class already existed but the error response of "Retrieving Contention list failed. System error" did not trigger it
InvalidClaimAccess
InvalidClaimModifier
AddressInvalidCharacterError
