### ISSUE TITLE
Cannot read property 'length' of undefined in QueueTableBuilder

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#14439]
## Description
`QueueTableBuilder` returns `Cannot read property 'length' of undefined` on `numberOfPages={tabConfig.task_page_count}` in the `taskTableTabFactory` function

## Background

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10495
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10497

**Comment by ajspotts** [comment]
Related: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10502

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||
3 | |||||||
5 | 
8 | 
```

#### Why 2?
* May just need to identify where the leak in our Redux state is that is causing this and plug that

#### Why 3?
* This this may be related to not having a fresh queue config. Hard to track down the exact scenario where this occurs.
* What is in our react state and when?
* somewhat complex flow in this code
