### ISSUE TITLE
Caseflow Intake | Bug | Fix Debounce for Add Claimant Search

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#14430]
## Description
Looks like we had a reversion that causes debounce to not actually be preventing repeated API calls in `AddClaimantModal`

## Acceptance criteria
- [ ] Async fetch function is properly debounced

**Comment by leikkisa** [comment]
# March Against Fear Sprint Sprint 6/1/2020 - 6/12/2020
Engineering capacity: 73%
- Yang PTO 6/1
- JC Batteam week of 6/1
- Sandra Batteam week of 6/8

## Sprint status
:arrow_right_hook: Carryover: 11
:arrow_right_hook: ✅Carryover completed:
:arrow_right_hook: Remaining:

⭐️ Points pulled in for this sprint: 17
⭐️✅Points from this sprint completed:
⭐️🚫Decided not to do:
⭐️Remaining:
⭐️🛑Blocked for now:

👾Space invaders pulled in: 1
👾✅Space invaders completed:
👾Remaining:

Total to do:
Total points completed:
Decided not to do:
Remaining:  

## Sprint activities

### Intake
1. :arrow_right_hook: (3) Intake | Prevent removing an issue if connected to a rating #13977 (pulled in last sprint as an extra)
1. ⭐️ (2) Intake | Upstream Error | Add error classes (and ignore in Sentry) #14417

### Motions to vacate
- Pilot has started

### Attorney fees
1. :arrow_right_hook: (3) Contested Claims | Attorney Fees | Fetch Attorney Fee Data #14294 (broken out from ticket from last sprint)
1. ⭐️ (2) Contested Claims | Attorney Fees | Unlisted claimant storage #14380
1. ⭐️ (3) Contested Claims | Attorney Fees | Add ‘Claimant not listed’ selection when attorney is not available #14107
1. 👾 (1) Caseflow Intake | Bug | Fix Debounce for Add Claimant Search #14430

### Legacy opt-ins
1. :arrow_right_hook: (3) BVA | Intake | Legacy opt-in | Extend eligibility period that expires during a federal holiday #14285

### Accessibility
1. ⭐️ (3) Intake | The 'enter or select form box' and 'Which form' label is not read by assistive technology (End: 6/12) #14373
1. ⭐️ (2) Dispatch: Special Issues checkboxes are not grouped together (End: 7/10) #12123
1. ⭐️ (2) Demo | Assistive technology does not read the access link for each product in demo (End: 6/12) #14377

### Tech improvement
1. :arrow_right_hook: Investigate Form-Management Libraries #13257
1. :arrow_right_hook: Handling of PDF Files via Webpack #13917
1. :arrow_right_hook: (2) Add one controller schema for validation and documentation #14017
1. ⭐️ (3) Build out Stories for Remaining Common UI Components #14021
