### ISSUE TITLE
Dispatch & Special Issues Investigation

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14433]
While continuing to implement the New Contentions, https://github.com/department-of-veterans-affairs/caseflow/issues/13423, we've discovered some unexpected behavior in how Queue and Dispatch are interacting differently with Special Issues (SI). To proceed, we need to answer several questions so we can clarify the path forward.

**AC:** 
 - [x] Essential questions are answered & documented in a wiki

**Essential Questions:**
- How do cases get to "ready for dispatch", for both AMA and Legacy cases
  - if feasible, create some seed data for both with already selected SIs
- Does Dispatch understand that the SpecialIssuesList object exists
- How does Dispatch interact with LegacyAppeals on-object SpecialIssues
- How does the SpecialIssues information leave caseflow, for AMA and for Legacy
- Does Dispatch handle all Legacy appeals, or just a subject?
- Do users see the Special Issues page in production on AMA?

Helpful Additional Information
 - Why does Dispatch offer all Special Issues on AMA appeals?
 - When can we expect that a legacy case is "Done" in Caseflow, in the happy path?

**Comment by yoomlam** [comment]
Mentioned elsewhere: https://github.com/department-of-veterans-affairs/caseflow/issues/13736#issuecomment-614069364
