### ISSUE TITLE
Remove "Special" copy from Completed Task tab

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14447]
## Description
Now that Special Case Movement has been renamed to Case Movement we will need to ensure the task name is updated on the completed tab of the your cases page for case movement users. 

![image (1)](https://user-images.githubusercontent.com/59883609/83553776-bc2ac700-a4d9-11ea-8e08-a65e8a21de90.png)

## Acceptance criteria
- [ ] Special Case Movement copy is updated to Case Movement on all tabs

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||
2 | ||||
3 | 
5 | 
8 | 
```

run `git grep -i "\<Special"` and check stuff!

#### Why 1?
* Add label to override the task type being displayed

#### Why 2?
* Nvmd: Update frontend to use `label` <- already does
* Update tests

**Comment by yoomlam** [comment]
BEFORE|AFTER
 ---|---
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/55255674/84796771-a380dd80-afbe-11ea-9e38-c92dd203c8ff.png"> | <img width="1000" alt="image" src="https://user-images.githubusercontent.com/55255674/84796343-22c1e180-afbe-11ea-9f09-0a3ebb6f80ff.png">
