### ISSUE TITLE
Figure out how to allow reloads in certification v2

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1444]
Currently, Certification V2 breaks if you reload the page. This is because it's a SPA that modifies the URL bar, but doesn't serve the application on all of those URLS. Make the Rails app serve Certification V2 on all of the routes, and ensure that users can navigate around and reload. 

# Acceptance Criteria
The user should be able to successfully view a veteran's check documents page in Certification V2 (one that is missing all or some documents), upload the missing documents in VBMS, reload the check documents page and see that the missing documents are now accessed by the system.

### Steps to Validate

- Navigate to `/certifications/new/123C` (relative to demo)
- You will be redirected to `/certifications/123C/check_documents`
- Reload and verify that you're on the same page (and not an error page)
- Continue to the Confirm Case Details page
- Reload and verify that you're on the same page (and not an error page)
- Continue to the Confirm Hearing page
- Reload and verify that you're on the same page (and not an error page)
- Continue to the Sign & Certify page
- Reload and verify that you're on the same page (and not an error page)
- Continue to the success page
- Reload and verify that you're on the same page (and not an error page)
- Test the same on the most common version of IE our users use
 
- If the user is starting a new certification, the user should be able to navigate straight to `/certifications/123C/check_documents`successfully.
-  If the user is trying to start a certification for an appeal that can't currently be certified (mismatched docs, already certified, etc)—the user should not be able to skip past the check documents page. Instead, the user should be redirected to the check documents page.

When you reload, the information *may* be wiped out. This is normal for now, we're not persisting data to the DB.

**Comment by astewarttistatech** [comment]
@amprokop could you add Acceptance Criteria in this ticket. What was listed seems to be steps to validate.

**Comment by kierachell** [comment]
@astewarttistatech 
I added the following to test in Preprod:

| BFKEY | BFCORLID/VBMS_ID | First Name | Last Name | Comments |
| ----- | ---------------- | ---------- | --------- | -------- |
| 1010146 | 911011300 | FREDDY | TEST | Ready |
| 1154402 | 123111082 | LYNNE | ROSE | Missing Docs |
| 1499662 | 123111027 | WALSH | MARCIA | Already Certified |
| 1505661 | 123111778 | HARRY | FOSTER | Ready |
| 1520165 | 123111772 | JEROME | HILL | Already Certified |
| 890551 | 123111090 | PATSY | SINCLAIR | Missing Docs |

**Comment by astewarttistatech** [comment]
@amprokop findings show that you cannot "reload" the page because the "/mismatcheddocuments"  gets added to the end of the URL whenever it is missing docs so it will give you a "Page not found" error. Could you change the AC to show when you "revisit the page"?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: FF

Steps to Validate: 
1. In Certification, visit a "/checkdocuments" for a veteran missing all or some of the documents needed to certify an appeal. 
2. In the environment's corresponding, VBMS uploaded the necessary documents based on the VACOLS/VBMS dates. 
3. **Revisit the page** to see that all documents have been loaded and the user is able to move on in the Certification flow. 

Screenshots:
<img width="924" alt="screen shot 2017-04-19 at 9 20 46 am" src="https://cloud.githubusercontent.com/assets/23038505/25182601/259b25a6-24e3-11e7-9e41-5c565b3b5556.png">
<img width="1249" alt="screen shot 2017-04-19 at 9 27 58 am" src="https://cloud.githubusercontent.com/assets/23038505/25182602/259e75b2-24e3-11e7-8c98-cada2d62fda8.png">

**Comment by amprokop** [comment]
@astewarttistatech — can you test this again after https://github.com/department-of-veterans-affairs/caseflow/pull/1621#pullrequestreview-33591062 is merged. That will address the issue you pointed out with the `mismatched_documents` route since we're getting rid of that route.

However, I intentionally left that case out of the acceptance criteria because I knew we would be refactoring that bit. It seems to me that the requirements in the ticket are currently correct, did some step mentioned there not work?

**Comment by astewarttistatech** [comment]
I will re-arrange the ticket for you. @amprokop

**Comment by astewarttistatech** [comment]
Retested on 4/20/17. Reload is now working as expected.
