### ISSUE TITLE
Add Timing Metrics to Queue Loading

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14444]
To keep an eye on how long it takes to load users queue, we should time the load and send this information, properly tagged, to Datadog. This will allow us to keep an eye on load times over time and across users, organizations, & queue types.

## AC
  - [ ] All Queues measure their load time & report it to Datadog
  - [ ] the data points are tagged with user type, organization, pagination_enabled, & queue type
  - [ ] Datadog report/view setup

**Comment by yoomlam** [comment]
Probably use `MetricsService` like https://github.com/department-of-veterans-affairs/caseflow/blob/ff59e90ed10c726493fd463e5035f102a0377102/app/controllers/legacy_tasks_controller.rb#L28-L29 
to get a chart in DataDog: 
<img width="920" alt="image" src="https://user-images.githubusercontent.com/55255674/83531552-bf5e8c80-a4b2-11ea-8199-06a214c96545.png">

May need to update `MetricsService` to allow adding other `attrs` (maybe something like [this](https://github.com/department-of-veterans-affairs/caseflow/blob/d8a7410dabdb0eebec07ca566b4c018e2a6f0156/app/jobs/stats_collector_job.rb#L75)) to distinguish different queues. Description of `attrs` [here](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/caseflow-team/Collecting-Data.md#datadog-custom-metrics).

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||||
5 | |
8 | 
```
#### Why 3?
* As queues load a lot of their information async, it may be tough to get a full picture of how long a user is sitting with a queue loading screen spinner. Can we find a way to link all async requests with a uniq identifier as each request will have its own uuid. Could then pull all requests associated with that identifier and see when the first one kicked off/ last on finished.
* Learning experience for engs implementing metrics
 
#### Why 5?
* maybe need to expand architecture / id-share to capture whole load experience
