### ISSUE TITLE
Appeal Data Logging Audit

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14456]
As the echo team, we want to find and document all the ways the Appeal process logs data along its process through Caseflow, especially Queue. The goal is to be able to utilize logging when reconstructing the history of an appeal.

 - What stages of the process are logged to AWS? Which aren't?
 - How can we reliably query this?
 - What stages/changes are logged into our database versioning, PaperTrail? Which aren't?
 - How can we reliably query this?
 - What stages are logged elsewhere? (to DataDog?) Queries for it?

## AC
 - Write a wiki page capturing what is logged and how to query it 
 - Write tickets to fill in any gaps in the log trail
 - Write any tickets to enhance our logging, based on the audit.

**Comment by yoomlam** [comment]
Related to #14345

**Comment by hschallhorn** [comment]
Timebox to a 3!
