### ISSUE TITLE
Identify ways JudgeTeams have diverged from organizations

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14465]
Although judge teams are an organizations and share many similar workflows, they have their own specific "assign cases" page. This ticket exists to captures all org/judge team differences in order to find ways we can sync up behaviors, workflows, and queues.

Shared Workflow|Organization|JudgeTeam
---|---|---
**Who are members of the org**|There are many users in an org and some can be admins|There are many attorneys on a judge team, but only one judge
**Who can assign tasks to an org's users**|Usually only admins, but some tasks can be assigned by any user of that org|Only judges assign or reassign tasks
**Who can be assigned tasks**|Any organization user can be assigned a task|Only attorneys can be assigned attorney tasks, but they don't necessarily have to be a member of that judge team
**Tasks can move between orgs**|A handful of task types can be reassigned to another organization|Judges can reassign judge assign tasks to another judge/judge team
**Task waiting to be assigned to a user**|A task is created and assigned to an org|A judge assign task is created and assigned to that judge
**Navigate to org queue**|All users in an org have a dropdown in queue to navigate to the organizations queue|Judges have a dropdown in queue to navigate to their judge assign page
**How org queues are built**|Org queues configurations are determined on the back end and built from queue config. They also support pagination|Judge assign pages are built completely on the front end by requesting all tasks and legacy appeals assigned to a judge and all tasks and legacy appeals assigned to the attorneys on their judge team
**View tasks waiting to be assigned to a user**|The "unassigned" tab in an org queue holds all tasks that are assigned to the org|A judge's "Assign cases" page holds all cases waiting to be assigned to an attorney
**Assign tasks to a user**|From case details or with the bulk assignment functionality in the org's "unassigned" tab, admins (and sometimes non admins) can assign tasks to members of that organization|From case details or from the judge's "assign cases" page, judges can assign tasks to attorneys on their judge team or to any attorney.
**View tasks assigned to an org user**|The "assigned" and "on hold" tabs in an org queue show all tasks assigned to the users of the organization|The judge assign page have similar tabs to display the tasks assigned to each attorney on the judge team

Views|Organization|Judge
---|---|---
Unassigned tasks|![Screen Shot 2020-06-04 at 12 34 08 PM](https://user-images.githubusercontent.com/45575454/83785725-c080ec80-a65f-11ea-833e-c4a93ea6fcf7.png)|![Screen Shot 2020-06-04 at 12 30 48 PM](https://user-images.githubusercontent.com/45575454/83785759-caa2eb00-a65f-11ea-9ee9-bc562de2e849.png)
Assigned tasks|![Screen Shot 2020-06-04 at 12 34 19 PM](https://user-images.githubusercontent.com/45575454/83785834-e27a6f00-a65f-11ea-9db1-41b247ef5473.png)|![Screen Shot 2020-06-04 at 12 31 13 PM](https://user-images.githubusercontent.com/45575454/83785842-e4dcc900-a65f-11ea-84e6-32d8ffc8df2b.png)

**Comment by araposo-tistatech** [comment]
@hschallhorn is there something you need product to add here?

**Comment by hschallhorn** [comment]
Nope, will move to backlog!
