### ISSUE TITLE
TrackVeteranTask opened after case is complete

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#14460]
## Description

We have instances where a TrackVeteranTask is opened after a RootTask is closed.

```
q = AppealsWithClosedRootTaskOpenChildrenQuery.new
q.call.select { |appeal| appeal.tasks.open.map(&:type).include?("TrackVeteranTask") }.count
```

We need to either:

* [ ] discover if this is a code bug, fix it and clean up the data
* [ ] or, create an ongoing scheduled job to close these tasks

## Background/context/resources

https://dsva.slack.com/archives/CJL810329/p1591130098371200

See also #14255 #14307 

## Technical notes

For Appeal 25440 the extra task was created a full minute after the root task was closed.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||
3 | |||
5 | 
8 | 
```

Check callbacks being skipped.
Check whether the calls that create TVT aren't properly checking appeal state

#### Why 2?
* Believe this could be related to the (many) open tasks we have on closed root tasks. Could be opening track veteran tasks when these other open tasks are processed (`sync_tracking_tasks` https://github.com/department-of-veterans-affairs/caseflow/blob/d8a7410dabdb0eebec07ca566b4c018e2a6f0156/app/jobs/update_appellant_representation_job.rb#L24
* Limited scope to investigate
