### ISSUE TITLE
Create DVC Teams

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14462]
When VLJs are unavailable, DVCs need the ability to remove the VLJ from the Auto-Case Distribution priority push algorithm. We do not currently have this information in caseflow and have received the go-ahead to track DVC teams like we do judge teams.

Creating DVC teams will also allow us to route tasks of VLJs that have departed the Board to their DVC. 

## AC
- [ ] New organization type is created called DvcTeam which mirrors judges team where 
   - [ ] There can only be one admin (the dcv) which can be queried with `dvc`
   - [ ] All non admins are the team's judges which can be queried with `judges`
   - [ ] DvcTeam can be created for a DVC with method `create_for_dvc`
   - [ ] DvcTeam can be found for a DVC with method `for_dvc`
- [ ] New section on the team management page lists all dvc teams
- [ ] New button on the team management page creates new dvc team
- [ ] New modal allows user to search for a user to make a dvc team for them

## Open questions
- [ ] What should these DVC team management pages look like? Assume they'll end up a lot like judge team management pages, but what should the copy read for what a DVC team is and what each role (DVC/Judge) means
- [ ] What users should be searchable to make a dvc team?

## Current state

(log in a TEAM_ADMIN)

_/team_management_ judge teams
![Screen Shot 2020-06-26 at 4 59 43 PM](https://user-images.githubusercontent.com/45575454/86134817-10649f00-bab8-11ea-90d8-f3e901452230.png)

_/team_management_ create judge team
![Screen Shot 2020-06-04 at 10 29 10 AM](https://user-images.githubusercontent.com/45575454/83769900-6d526e00-a64e-11ea-8022-fe0115985642.png)

_/organizations/<judge>/users_
![Screen Shot 2020-06-04 at 10 29 58 AM](https://user-images.githubusercontent.com/45575454/83769947-793e3000-a64e-11ea-9cdc-463236787010.png)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||
5 | ||||||||
8 | 
```

We don't expect all DVCs to be judges

Do not reimplement the judge team logic that is set to be rolled back.

Be sure that when we exclude judge teams from pulling all orgs, we also exclude dvc teams

Consider implementing this with a superclass shared with JudgeTeam


#### Why 3?
* Lot of replication from judge teams

#### Why 5?
* New model, new views
* slight rearchitecting to share with JudgeTeam
