### ISSUE TITLE
BVA | Intake claims listed with a G code disposition in VACOLS

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14476]
## User or job story
As a BVA Intake user, I need to be able to intake claims listed with a G code disposition in VACOLS

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by RebeccaBaumTT** [comment]
This is a duplicate of #13893. I am closing it as such.
