### ISSUE TITLE
JSON Parser error in HearingsController#show

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14489]
## Description

Caused by an error in eFolder, but not sure what the root cause is

```
JSON::ParserError

783: unexpected token at '<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
'
```

I don't think the request ever reaches the eFolder rails server. I wasn't able to find the same request in the rails log. This could probably fail more gracefully, but it seems mostly like a transient issue.

## Acceptance criteria

N/A

## Background/context/resources

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9725/events/a2f1e05fd0bd4bae9d69d2839f9bf143/

**Comment by pkarman** [comment]
seems related to #13998 and #14243 

the 502 gateway error is from nginx. It may be that rails puma threads are all busy?
