### ISSUE TITLE
Document Viewer | Page number reference for saved comment box

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1450]
As a user, I want to know which page I annotated my comments from that way other attorneys, judges and I can jump back to those pages for reference. 

## Acceptance criteria 
- Verify that the word `Page` and `#` is located at the top left of every comment box after a comment has been saved
- Page # should be in `gray-dark`
- Verify that the page number matches the page where the yellow comment box is located
- Verify that the page and # is aligned with the Delete and Edit links

## Mockup 
![image](https://cloud.githubusercontent.com/assets/13420618/24661888/9f6b4fe6-1921-11e7-8a16-01bb17b4b2ef.png)

## Note

I know that in the previous mockups, we had `Pg. #` instead of writing out the word `Page`. This change to write out Page was made to make this section screen reader friendly.

**Comment by kierachell** [comment]
@gnakm 
- Should the `Page #` be #000000 (true black) or #323A45 (the near black) as referenced here: https://github.com/department-of-veterans-affairs/caseflow-commons/issues/12

- Should it be `Delete | Edit` or `Edit | Delete`?
<img width="130" alt="screen shot 2017-04-19 at 7 24 35 pm" src="https://cloud.githubusercontent.com/assets/18075411/25206425/df213248-2535-11e7-8c1d-1ae33874cc29.png">



<img width="335" alt="screen shot 2017-04-19 at 7 23 19 pm" src="https://cloud.githubusercontent.com/assets/18075411/25206389/bb8b2bcc-2535-11e7-9395-7895344f20e1.png">

**Comment by gnakm** [comment]
Page number should be `gray-dark` @mdbenjam and I confirmed this. Thanks for checking 👍

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Access a document that has multiple pages
3. Add comments to multiple pages
4. Validate that each comment has it's corresponding page number associated with it. 

Screenshots:
![readercommentpage](https://cloud.githubusercontent.com/assets/23038505/25489432/d199832a-2b37-11e7-95ef-6e82910cac47.gif)
