### ISSUE TITLE
V2: "other representative type" is wiped on page navigation

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1451]
After filling our "other representative type", then clicking "Continue", then going back, it's wiped out.

![bug](https://cloud.githubusercontent.com/assets/3781835/24665517/9f889bd2-192b-11e7-9ab9-655509ac6447.gif)

# Acceptance Criteria

- The value in the "Specify other representative type" text field remains out if the user fills it out, then clicks "Continue", then navigates back in the browser.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: FF and Chrome

Steps to Validate: 
1. Go to Certification with a veteran who is ready to certify.
2. On the Confirm Case Details page, select "Other" and fill in the "Other Representative" text field.
3. Select "Continue"
4. From Confirm Hearing page, navigate back to the Confirm Case Details page, via browser, and validate that the value in the Other Representative has remained. 

![1451](https://cloud.githubusercontent.com/assets/23038505/25182962/3d2fac40-24e4-11e7-8df0-f852cae090c7.gif)
