### ISSUE TITLE
DAS Deprecation Deep Dive

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14515]
Last year we began implementing das deprecation based on the tech spec outlined in #9588. This effort was halted by the board due to various reasons. Based on the epic #9930, there is only one ticket remaining to fully implement DAS, #12059. This ticket exists to catch up on the work done and to identify any gaps in implementation.

## Open questions
_Note that this list in non exhaustive_
- [ ] Are we backfilling DAS records so that users still have access to reports?
- [ ] When caseflow encounters a case with a DAS record but no AttorneyTask or JudgeDecisionReviewTask, how is it handled?
- [ ] When caseflow encounters a case with a DAS record and a JudgeAssignTask, AttorneyTask or JudgeDecisionReviewTask, how is it handled?
- [ ] How are appeals handled once decisions are signed? 
- [ ] How will this affect ScheduleHearingColocatedTasks (or any other tasks where we have different workflows based on appeal type)
- [ ] Are legacy colocated tasks handled correctly? (with legacy appeals they update the vacols location to the assigner when completed)
- [ ] Do all judge and attorney task actions work correctly when a JudgeAssignTask, AttorneyTask or JudgeDecisionReviewTask is created for a legacy appeal?
- [ ] Has the implementation deviated now that we're pulling tasks assigned to a user through queue config?

## AC
- [ ] List of tickets/efforts that will need to be written to complete das deprecation effort

**Comment by lomky** [comment]
Timebox investigation to 3.

Document what is currently implements, concerns, what needs to get done to complete this.

AC: document possible new tickets and gaps

Is this a _tech_ spec, or user questions? Informs product

Consider a call with folks with context around DAS deprecation (Ferris, Rubaiyat, Dustin, Anya)
