### ISSUE TITLE
Capture stats on current AMA Automatic Case Distributions

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14541]
The board has requested some changes around how cases are selected for distribution (#14538). Before we work on the implementation of this, we need to provide statistics on current distributions and the affect these changes will have on the distribution of other dockets.

### At what rate are priority appeals "ready" to be distributed?
  - Ama cases are
    - [Ready](https://github.com/department-of-veterans-affairs/caseflow/blob/58dc75e4cec30d12dcd0a3daae269dd6c5262fad/app/models/appeal.rb#L215-L227) if the distribution task has a status of assigned. 
    - [Ready at](https://github.com/department-of-veterans-affairs/caseflow/blob/58dc75e4cec30d12dcd0a3daae269dd6c5262fad/app/models/appeal.rb#L228-L230) the `assigned_at` timestamp of the distribution task
    - [Priority](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket.rb#L87-L94) if the veteran is over 75 years old or has had some other AOD motion granted

### How long do priority cases normally sit?
- Ama appeals are "distributed at" the [time the distribution task is closed](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket.rb#L79) and a [judge assign task is opened](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket.rb#L75)

### What is our current priority target and how many priority cases are we distributing?
[Priority target is calculated](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L112) as the ratio of [sum of priority cases on all dockets](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L88-L93) to [the total number of attorneys in caseflow * 3](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L123-L125). The current priority count and total batch size is stored in [`statistics`](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L57-L58) on our [`Distributions`](https://github.com/department-of-veterans-affairs/caseflow/blob/43562ed9e75b14c6f949802521da9df6a4214c2b/app/models/distribution.rb#L46) table ([metabase](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE1LCJvcmRlci1ieSI6W1siZGVzYyIsWyJmaWVsZC1pZCIsMjk2XV1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)). We can determine the number of distributed priority cases through associated `DistributedCases` for each distribution ([metabase](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NzYsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZC1pZCIsMjg5XSx0cnVlXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==))

### How will adjusting/removing the priority target affect the distribution of other docket types?
The board has set a goal around how long it takes to process direct review dockets. This is worked into the distribution docket proportions with its own [calculated proportion](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L33-L37). These proportions are also captured in the [`Distribution` `statistics`](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE1LCJvcmRlci1ieSI6W1siZGVzYyIsWyJmaWVsZC1pZCIsMjk2XV1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) column. We need to capture how changing the priority factor will change the number of distributed direct review cases.
- If we remove the priority factor all together, how soon will we clear out priority cases to make room for distributing other dockets again?
- If we keep the priority factor, but increase it, what affect will this have on the number of distributed direct review docket in each distribution?

### Are we actually distributing the full number of available non priority cases linked to a judge?
In ["step 2"](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L30-L33) we distribute legacy and hearing dockets associated with a judge. 
- For ama hearing docket cases, a similar query is constructed, by pulling all [hearings held by the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/55b1e7c184adb9147195a5158f526964c5436c29/app/queries/hearing_request_distribution_query.rb#L73) on [appeals that are ready to be distributed](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket.rb#L10-L23)
We can leverage this along with some of the above information (when an appeal is ready to be distributed and what appeals were actually distributed in a request) to determine if we are distributing the full set of appeals related to a judge.

## Acceptance Criteria
- [ ] Stats listed above are compiled into a report
- [ ] Implementations of capturing these stats are moved to the code base to be pulled at anytime (May need to spin out a separate ticket on this one)

**Comment by yoomlam** [comment]
This is a great start! More questions will likely arise during the investigation.

**Comment by yoomlam** [comment]
We should re-run the [simulation](https://github.com/department-of-veterans-affairs/docketeer), updated with the new algorithm.

**Comment by yoomlam** [comment]
Split into 2 tickets: 
* Legacy 
```bash
1 | 
2 | 
3 | ||||
5 | ||||||||
8 | 
```
 - A one-time query, not a job
 - How do we query VACOLS for large things like this?
   - the connection is slow to setup, but runs quickly after that

  
* AMA
```bash
1 | 
2 | ||
3 | ||||||||
5 | ||
8 | 
```
  * A one-time query, not a job

#### Why 1?
* 

#### Why 2?
* 

#### Why 3?
* 

#### Why 5?
* Lot of vacols SQL to fiddle with

**Comment by hschallhorn** [comment]
[Metabase query for first stat ](http://query.prod.appeals.va.gov/question/39#eyJuYW1lIjoiUmVhZHkgQXQgYnkgRG9ja2V0IFR5cGUgYW5kIFByaW9yaXR5IiwiZGVzY3JpcHRpb24iOm51bGwsImRhdGFzZXRfcXVlcnkiOnsibmF0aXZlIjp7InF1ZXJ5IjoiU0VMRUNUXG4gIHRhc2tzLmFzc2lnbmVkX2F0IEFTIHJlYWR5X2F0LFxuICBhcHBlYWxzLmRvY2tldF90eXBlLFxuICBhZHZhbmNlX29uX2RvY2tldF9tb3Rpb25zLmNyZWF0ZWRfYXQgPiBhcHBlYWxzLmVzdGFibGlzaGVkX2F0IEFORCBhZHZhbmNlX29uX2RvY2tldF9tb3Rpb25zLmdyYW50ZWQgPSBUUlVFIEFTIGFvZF9tb3Rpb24sXG4gIHBlb3BsZS5kYXRlX29mX2JpcnRoIDwgdGFza3MuYXNzaWduZWRfYXQgLSBpbnRlcnZhbCAnNzUgeWVhcnMnIEFTIGFvZF9hZ2VcbkZST00gdGFza3NcbklOTkVSIEpPSU4gYXBwZWFscyBPTiB0YXNrcy5hcHBlYWxfaWQgPSBhcHBlYWxzLmlkXG5JTk5FUiBKT0lOIGNsYWltYW50cyBPTiBhcHBlYWxzLmlkID0gY2xhaW1hbnRzLmRlY2lzaW9uX3Jldmlld19pZCBBTkQgY2xhaW1hbnRzLmRlY2lzaW9uX3Jldmlld190eXBlID0gJ0FwcGVhbCdcbklOTkVSIEpPSU4gcGVvcGxlIE9OIGNsYWltYW50cy5wYXJ0aWNpcGFudF9pZCA9IHBlb3BsZS5wYXJ0aWNpcGFudF9pZFxuTEVGVCBPVVRFUiBKT0lOIGFkdmFuY2Vfb25fZG9ja2V0X21vdGlvbnMgb24gYWR2YW5jZV9vbl9kb2NrZXRfbW90aW9ucy5wZXJzb25faWQgPSBwZW9wbGUuaWRcbldIRVJFIHRhc2tzLnR5cGUgPSAnRGlzdHJpYnV0aW9uVGFzaycgQU5EIHRhc2tzLnN0YXR1cyBJTiAoJ2Fzc2lnbmVkJywgJ2NvbXBsZXRlJylcblxuIiwidGVtcGxhdGUtdGFncyI6e319LCJ0eXBlIjoibmF0aXZlIiwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiYXNzaWduZWRfYXQiXSwiZ3JhcGgubWV0cmljcyI6W251bGxdLCJjb2x1bW5fc2V0dGluZ3MiOnsiW1wibmFtZVwiLFwiYXNzaWduZWRfYXRcIl0iOnsiZGF0ZV9hYmJyZXZpYXRlIjp0cnVlfX0sInRhYmxlLnBpdm90X2NvbHVtbiI6ImFvZF9tb3Rpb24iLCJ0YWJsZS5jZWxsX2NvbHVtbiI6ImFvZF9hZ2UifSwib3JpZ2luYWxfY2FyZF9pZCI6Mzl9)

**Comment by araposo-tistatech** [comment]
Per DVC Scharnberger, no longer needed.
