### ISSUE TITLE
Update case orders logic

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14542]
Update case distribution order to:
1. Reduce backlog of legacy hearing cases tied to the judge to 30
1. Continue with current algorithm

<details><summary> Newer old requirements </summary>

User Story: When a Veteran Law Judge requests more cases, the case distribution logic should be as follows to ensure cases are worked in the correct order: 

1. Distribute non-priority cases tied to the judge
    a. Legacy hearing cases tied to the judge - if the judge has more than 30 tied to them, fill their case order with only legacy hearing cases tied to them until the threshold of 30 has been hit or until their case order (batch size) has been met,  whichever comes first.  If the judge has <= 30 legacy hearing cases tied to them continue with the below. Creation of backlog [here](https://github.com/department-of-veterans-affairs/caseflow/issues/14543)
    b. AMA hearing cases with affinity for the judge
    c. Distribute non-priority cases that are general population based on docket proportions using stochastic rounding

We no longer want Priority appeals to be distributed via the Request Cases logic, but instead be automatically distributed when they are ready #14604 

## Current
We limit the number of priority appeals distributed in a distribution by ensuring we do not distribute more priority appeals than our priority target. [Priority target is calculated](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L112) as the ratio of [sum of priority cases on all dockets](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L88-L93) to [the total number of attorneys in caseflow * 3](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L123-L125). This has lead to a steady increase in the number of priority appeals waiting to be distributed (`Distribution.statistics.priority_count` in [Nov 2018](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE1LCJvcmRlci1ieSI6W1siYXNjIixbImZpZWxkLWlkIiwyOTZdXV19fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) vs [now](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE1LCJvcmRlci1ieSI6W1siZGVzYyIsWyJmaWVsZC1pZCIsMjk2XV1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)).

We also fill a distribution with legacy and ama hearing docket cases with [non priority cases associated with the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L30-L33) before we [distribute priority cases that are not associated with the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L38). 

<details><summary>Old requirements, now outdated</summary>
After collecting stats on how the removal of this priority factor will affect other docket distributions and the go-ahead from the board, remove this priority target by replacing `priority_rem` with `@rem`.~

```diff
-     # If we haven't yet met the priority target, distribute additional priority appeals.
-     priority_rem = (priority_target - @appeals.count(&:priority)).clamp(0, @rem)
-     oldest_priority_appeals_by_docket(priority_rem).each do |docket, n|
-       distribute_appeals(docket, n, priority: true)
-     end
+     # If we haven't yet filled the request order, distribute additional priority appeals.
+     oldest_priority_appeals_by_docket(@rem).each do |docket, n|
+       distribute_appeals(docket, n, priority: true)
+     end
```
The priority cases that are **not** associated with the judge should take precedence over the **non-priority** cases associated with the judge, so ensure we move this distribution to before we  [distribute **non-priority** cases that are associated with the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L30-L33), but after we [distribute **priority** cases that are associated with the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L26-L28)
</details>
</details>

## Acceptance Criteria
 - [ ] Please put this work behind the feature toggle: Priority Case Auto-Distribution
 - [ ] Every case order (distribution request) is filled with legacy hearing cases tied to the judge first. If the judge has more than 30 tied to them distribute their legacy hearing cases until the threshold of 30 has been hit or until their case order (batch size) has been met, whichever comes first
 - [ ] Once the judge is down to 30 cases in their backlog, if they have more cases to fill in their request, fill the case order per the original algorithm rules

### To reduce confusion
Move these 3 lines https://github.com/department-of-veterans-affairs/caseflow/blob/6287312416efb2e55988a3d1bf5d69fbfefb235d/app/models/concerns/ama_case_distribution.rb#L32-L34

to before these three lines. https://github.com/department-of-veterans-affairs/caseflow/blob/6287312416efb2e55988a3d1bf5d69fbfefb235d/app/models/concerns/ama_case_distribution.rb#L26-L28

No other changes, do not remove priority

**Comment by yoomlam** [comment]
Looking at `Distribution.statistics.priority_count` in [Nov 2018](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE1LCJvcmRlci1ieSI6W1siYXNjIixbImZpZWxkLWlkIiwyOTZdXV19fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319), why is there a significant drop for `batch_size` and `total_batch_size`? Code correction?

**Comment by pkarman** [comment]
Nov 2018 was when the ACD algorithm was being developed afaik. See https://github.com/department-of-veterans-affairs/caseflow/pull/7692

AMA was then being added in during Jan/Feb in anticipation of Feb 19 launch. https://github.com/department-of-veterans-affairs/caseflow/pull/9046

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||
5 | |||||||
8 | 
```

#### Why 3?
* Simple implementation (Remove priority limit, move current step 2 to step 3)

#### Why 5?
* Writing tests for this may take a lot of time given the current tests not being straightforward
* Verify desired behavior with updated simulation
* Some spinup

**Comment by lomky** [comment]
Re-estimating

_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | |||||||||
5 | 
8 | 
```

Affinity to judge (AMA) != Tied to judge (Legacy)
* Affinity = not necessary to distribute to associated judge; already implemented

We don't have to update distribution logic to implement new functionality. We're updating ordering and removing some criteria.

Implement this assuming the 30 case backlog; implementation of that is elsewhere

#### Why 1?
* 

#### Why 2?
* Just code removal/reordering

#### Why 3?
* Updating tests?
* lots of tests

**Comment by araposo-tistatech** [comment]
@hschallhorn our pilot user BVANDOAN reported the following when requesting more cases: 

"the only thing I’ve noticed so far is a much higher than normal number were CAVC type. These were 6 of the 24 cases, and none of these cases are my hearings or where I made the last decision. Obviously, not a problem, just an observation in case that is something being looked at."

**Comment by araposo-tistatech** [comment]
@hschallhorn from pilot user BVAMTENNER: 

"I just initiated a case request and received 27 cases. It looks like 4 out of the 27 are hearing cases. The remainder are Legacy Post Remand cases."

**Comment by hschallhorn** [comment]
```ruby
judge = User.find_by(css_id: "BVAMTENNER")
FeatureToggle.enabled?(:priority_acd, user: judge)
=> true

JudgeTeam.for_judge(judge)&.attorneys&.size * 3
=> 27

distribution = Distribution.where(judge: judge).order(:created_at).last
distribution.statistics["legacy_hearing_backlog_count"]
=> 30

cases = distribution.distributed_cases
cases.where(docket: "legacy", priority: false, genpop: false, genpop_query: "not_genpop").count
=> 27

cases.pluck(:docket, :priority, :genpop, :genpop_query).uniq
=> [["legacy", false, false, "not_genpop"]]

# Looks like all of these cases were legacy non-priority cases tied to the judge

vacols_ids = cases.pluck(:case_id)
SELECT_APPEALS = "
  select BFKEY, BFDLOOUT, BFMPRO, BFCURLOC, BFAC, BFHINES, TINUM, TITRNUM
  from BRIEFF
  inner join FOLDER on FOLDER.TICKNUM = BRIEFF.BFKEY
  "
query = <<-SQL
  select VLJ
  from (
    select BFKEY, case when BFHINES is null or BFHINES <> 'GP' then VLJ_HEARINGS.VLJ end VLJ
    from (
      #{SELECT_APPEALS}
    ) BRIEFF
    #{VACOLS::CaseDocket::JOIN_ASSOCIATED_VLJS_BY_HEARINGS}
  )
  where (bfkey in (?))
SQL

fmtd_query = VACOLS::CaseDocket.sanitize_sql_array([query, vacols_ids])
VACOLS::CaseDocket.connection.exec_query(fmtd_query).to_hash.uniq
=> [{"vlj"=>"728"}]
VACOLS::Staff.find_by(sattyid: 728).sdomainid
=> "BVAMTENNER"

# Looks like this also brought them down to exactly 30 
VACOLS::CaseDocket.nonpriority_hearing_cases_for_judge_count(judge)
=> 30
```

**Comment by araposo-tistatech** [comment]
@hschallhorn sounds like we are all set with this one as well. Please see the last pilot users response after ordering more cases (BVANDOAN): 

"I just placed a case order. Looks I received all Legacy hearings."
