### ISSUE TITLE
Distribute down to 30 nonpriority legacy hearings before continuing with ACD

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14543]
We [distribute legacy and ama hearing cases that are associated with the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L30-L33). The board would like judges to have no more than s 30 case backlog of legacy hearing cases, meaning before we distribute any cases to a judge, we should check the number of legacy non priority hearing associated with the judge. If there are more than 30, distribute enough to reduce this number to 30.

### Examples
A judge requests 30 cases. The remaining column reflects this requested cases count after distribution occurs for the corresponding row.

Docket|Before|Distributed|After|Remaining
---|---|---|---|---
Priority Legacy Hearing Associated with Judge|5|5|0|25
Priority Ama Hearing Associated with Judge|5|5|0|20
Priority Legacy Hearing NOT Associated with Judge|5|5|0|15
Priority Ama Hearing NOT Associated with Judge|5|5|0|10
Non-Priority Legacy Hearing Associated with Judge|**42**|**10**|32|0

Docket|Before|Distributed|After|Remaining
---|---|---|---|---
Priority Legacy Hearing Associated with Judge|5|5|0|25
Priority Ama Hearing Associated with Judge|5|5|0|20
Priority Legacy Hearing NOT Associated with Judge|5|5|0|15
Priority Ama Hearing NOT Associated with Judge|5|5|0|10
Non-Priority Legacy Hearing Associated with Judge|**32**|**2**|30|8

NOTE: After this step, the algorithm proceeds as normal, first distributing _more_ Non-Priority Legacy Hearing Associated with Judge based on the remaining number of cases requested, legacy docket range, and docket proportions.

## Acceptance Criteria
- [ ] Please put this work behind the feature toggle: priority_acd
- [ ]  When a Veteran Law Judge requests more cases, if the judge has more than 30 legacy hearing cases tied to them, only the legacy hearing cases tied to them should be distributed until the threshold of 30 has been hit or until their case order (batch size) has been met, whichever is first.
- [ ] The rest of the algorithm proceeds as usual with the updated remaining number of cases to fill the order, including distributing more nonpriority legacy cases tied to the judge based on the legacy_docket_range and docket proportions

## References
[Here](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L249-L264) is where we determine non priority legacy hearing cases associated with a judge.

**Comment by yoomlam** [comment]
If a judge has less than 30 legacy hearing cases and no more of such cases come into case storage, then will any of those 30 cases ever get distributed to a judge? For this question, let's assume there are an infinite number of non-priority legacy hearing cases NOT associated with a judge.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |
5 | |||||||||||
8 | 
```

New VACOLS queries!
New tests!

#### Why 3?
* optimism

#### Why 5?
* Lot of vacols sql to muck around with.
* May be hard to set up tests

**Comment by hschallhorn** [comment]
@yoomlam GREAT question. This should be handled by the remaining_docket_proportions part of the code. https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L44-L49

After the backlog hits 30, cases can still be pulled from that backlog in this section

**Comment by hschallhorn** [comment]
Doing a bit of digging before I get into it. 

Noticed `legacy_docket_range` https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L30-L32

This is written up here https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Case-Distribution#legacy-docket-range

The range is calculated here https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L120-L122

What this number would be right now
```ruby
docket_coordinator = DocketCoordinator.new
total_batch_size = DecisionDraftingAttorney.users.size * Distribution::CASES_PER_ATTORNEY
priority_count = docket_coordinator.priority_count
docket_margin_net_of_priority = [total_batch_size - priority_count, 0].max
docket_proportions = docket_coordinator.docket_proportions
legacy_docket_range = (docket_margin_net_of_priority * docket_proportions[:legacy]).round
=> 1247
```
This range limits the number of cases tied to a judge that will be distributed. Not in any meaningful way it seems. 
But my understanding of this request and ticket is that this should also be removed to implement the 30 case backlog.
@alisan16 and @araposo-tistatech does that sound right?

**Comment by hschallhorn** [comment]
Let's look at how we would pull the number of legacy hearing in a judge's backlog

```ruby
judge = User.find_by(css_id: "BVARSCHARNB")
conn = VACOLS::CaseDocket.connection

query = <<-SQL
  select COUNT(*)
  from (
    select case when BFHINES is null or BFHINES <> 'GP' then VLJ_HEARINGS.VLJ end VLJ
    from (
      #{VACOLS::CaseDocket::SELECT_READY_APPEALS}
        and BFAC <> '7' and AOD = '0'
    ) BRIEFF
    #{VACOLS::CaseDocket::JOIN_ASSOCIATED_VLJS_BY_HEARINGS}
  )
  where (VLJ = ?)
SQL

fmtd_query = VACOLS::CaseDocket.sanitize_sql_array([query, judge.vacols_attorney_id])
conn.exec_query(fmtd_query).rows.flatten.first
=> 57
```

**Comment by hschallhorn** [comment]
Let's look at whether or not `legacy_docket_range` actually makes a difference in production
```ruby
docket_coordinator = DocketCoordinator.new
total_batch_size = DecisionDraftingAttorney.users.size * Distribution::CASES_PER_ATTORNEY
priority_count = docket_coordinator.priority_count
docket_margin_net_of_priority = [total_batch_size - priority_count, 0].max
docket_proportions = docket_coordinator.docket_proportions

legacy_docket_range = (docket_margin_net_of_priority * docket_proportions[:legacy]).round
=> 1266

judge = User.find_by(css_id: "BVARSCHARNB")

query = <<-SQL
  select DOCKET_INDEX
  from (
    select BFKEY, BFDLOOUT, rownum DOCKET_INDEX,
      case when BFHINES is null or BFHINES <> 'GP' then VLJ_HEARINGS.VLJ end VLJ
    from (
      #{VACOLS::CaseDocket::SELECT_READY_APPEALS}
        and BFAC <> '7' and AOD = '0'
      order by case when substr(TINUM, 1, 2) between '00' and '29' then 1 else 0 end, TINUM
    ) BRIEFF
    #{VACOLS::CaseDocket::JOIN_ASSOCIATED_VLJS_BY_HEARINGS}
  )
  where VLJ = ?
SQL

fmtd_query = VACOLS::CaseDocket.sanitize_sql_array([query,judge.vacols_attorney_id])

docket_indexes = VACOLS::CaseDocket.connection.exec_query(fmtd_query).to_hash
docket_indexes.map { |h| h["docket_index"] }.sort.last
=> 786
```
For this judge, all cases in their backlog would not be limited by the `legacy_docket_range` as all the docket_indexes of their cases are less than `legacy_docket_range`.

Let's look at the second judge
```ruby
judge = User.find_by(full_name: "REBECCA FEINBERG")
fmtd_query = VACOLS::CaseDocket.sanitize_sql_array([query,judge.vacols_attorney_id])

docket_indexes = VACOLS::CaseDocket.connection.exec_query(fmtd_query).to_hash
docket_indexes.map { |h| h["docket_index"] }.sort.last
=> 1253
```
This judge's cases would just _barely_ not be limited by the legacy docket range.

**Comment by hschallhorn** [comment]
Include 0s in backlog counts (includes AVLJs). Also grab css_ids
```ruby
query = <<-SQL
  select SDOMAINID, nvl(count(VLJ), 0) N
  from (
    select SDOMAINID, case when BFHINES is null or BFHINES <> 'GP' then VLJ_HEARINGS.VLJ end VLJ
    from (
      #{VACOLS::CaseDocket::SELECT_READY_APPEALS}
        and BFAC <> '7' and AOD = '0'
    ) BRIEFF
    #{VACOLS::CaseDocket::JOIN_ASSOCIATED_VLJS_BY_HEARINGS}
    full outer join STAFF on STAFF.SATTYID = VLJ_HEARINGS.VLJ
    where STAFF.SACTIVE = 'A' and (STAFF.SVLJ = 'J' or STAFF.SVLJ = 'A') and STAFF.SATTYID is not null
  )
  group by SDOMAINID
SQL
counts = VACOLS::CaseDocket.connection.exec_query(query).to_hash
```
