### ISSUE TITLE
Populate UAT appeals data

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#14555]
## Description

In order to test reporting performance in our UAT environment, it would be helpful to be able to scale up the amount of data we have available in the Caseflow database. This would be analogous to the `rake db:seed` strategy in local development/demo, but with actual Veteran data from BGS/VBMS in the UAT environment.

According to B3, the relevant tables that would benefit from more data (scale comparable to production) would be:

* appeals
* tasks
* hearings
* hearing_days
* virtual_hearings
* request_issues
* decision_issues
* veterans
* claimants
* judge_case_reviews
* attorney_case_reviews

## Acceptance criteria
- [ ] Create Rake task to populate tables on demand
- [ ] Based on further conversation with TIB to determine the timing and number of records needed, run the Rake task in the UAT environment.

## Background/context/resources

https://github.com/department-of-veterans-affairs/appeals-team/pull/1296

## Technical notes

Using the `db/seeds/` classes as inspiration, and the [list of Veteran file numbers available in the UAT environment](https://github.com/department-of-veterans-affairs/appeals-team/pull/1296), create a Rake task. Usage should be something like:

```
% bundle exec rake data:populate:appeals APPEAL_COUNT=500
```

which would create 500 new appeals for Veteran file numbers pulled randomly from the list. The `receipt_date` values should also be randomized. Use the FactoryBot factories like db seeds does, for re-use and accuracy.

**Comment by yoomlam** [comment]
Where is UAT data populated? What changes need to be made?

**Comment by pkarman** [comment]
By "UAT data" we mean the Caseflow database in the UAT environment. The intent of this ticket is to create a rake task that would act much like `rake db:seed` does: create Caseflow records like https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/seeds/tasks.rb#L270

**Comment by yoomlam** [comment]
Draft steps to complete this ticket.

Create a Rake task that does the following:
1. Copy or get read access to [VBMS UAT file numbers](https://github.com/department-of-veterans-affairs/appeals-team/pull/1296#)#1296 in the UAT env
2. Randomly select specified number of file numbers from the file
3. For each file number, populate the relevant tables in Caseflow's DB. 
   ("generate" means to generate fake data using FactoryBot, 
   whereas "create" means to create records based on specified data):
   * create an associated `veteran` record for the file_number
     * https://github.com/department-of-veterans-affairs/caseflow/blob/b2791b3f1f48768919d4a5604aa97d42a23da1da/db/seeds/intake.rb#L55
   * create associated `request_issue`s retrieved from BGS
     * Ask Foxtrot(Intake) how to do this
   * generate `appeal`(s) for the request issues
   * generate `claimaints` for the Veteran
     * https://github.com/department-of-veterans-affairs/caseflow/blob/58fe66e641d8f89645ab219e29e6c898df181ab3/db/seeds/hearings.rb#L25-L28
   * generate `hearing`(s) with associated `hearing_day`(s)
     * https://github.com/department-of-veterans-affairs/caseflow/blob/58fe66e641d8f89645ab219e29e6c898df181ab3/db/seeds/hearings.rb#L18
     * https://github.com/department-of-veterans-affairs/caseflow/blob/58fe66e641d8f89645ab219e29e6c898df181ab3/db/seeds/hearings.rb#L107
     * some of these should be `virtual_hearing`s
       * https://github.com/department-of-veterans-affairs/caseflow/blob/58fe66e641d8f89645ab219e29e6c898df181ab3/spec/factories/virtual_hearing.rb#L4
   * generate `decision_issue`s for each `request_issue`
     * https://github.com/department-of-veterans-affairs/caseflow/blob/6e92558a43bcf9bc619d5d510ed73d91b5f0743e/db/seeds/tasks.rb#L200-L202
     * generate associated `attorney_case_review` and `judge_case_review` for each appeal
       * https://github.com/department-of-veterans-affairs/caseflow/blob/6e92558a43bcf9bc619d5d510ed73d91b5f0743e/db/seeds/tasks.rb#L372

Test the Rake task locally.

Once this task is available/deployed in UAT and the stakeholder requests this data, run the Rake task and verify data.

**Comment by yoomlam** [comment]
De-escalated and paused until further investigation and decisions are made regarding copying prod data to the pre-prod environment, which should obviate the need for this ticket since stakeholders will then be able to do their testing in pre-prod instead of UAT.
