### ISSUE TITLE
Research Code Organization Patterns in Reader

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14559]
## Description

Pair and research what patterns we have for organizing code in the Reader codebase.

Timebox this ticket

## Acceptance criteria

N/A

## Background/context/resources

The backend workgroup is planning to meet to determine how to organize our codebase after researching existing patterns in our codebase.

See: https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/14563

**Comment by yoomlam** [comment]
Notes: https://hackmd.io/VvDEDsKeRcKG_JbnbW-eEw

**Comment by rubaiyat22** [comment]
closing after giving a final look at notes
