### ISSUE TITLE
Capture stats on current Legacy Automatic Case Distributions

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14554]
Legacy version of #14541

### At what rate are priority appeals "ready" to be distributed?
  - Legacy cases are
    - [Ready](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L62-L74) if the appeal
      1. The appeal is active
      1. Location code is 81 or 83
      1. It is not a special teams case
      1. [There is no blocking mail ](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L15-L37)
      1. [There are no extension requests, hearing clarifications, or POA clarifications](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L39-L60)
    - Ready at the latest date between
      1. The appeal was moved to location 81 or 83 (Can be found though the `location_date_in` of a [`VACOLS::Priorloc`](https://github.com/department-of-veterans-affairs/caseflow/blob/27a56e4f02a2c50d6717e093987c58522566a079/app/models/vacols/priorloc.rb#L3) record where the `location` is 81 or 83)
      1. The date the latest blocking mail was completed (latest `MLCOMPDATE` on [`VACOLS::Mail`](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/vacols/mail.rb#L3) record where type is ['02', '05', '08', or '13'](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L31))
      1. The date the latest blocking diary was completed (latest `TSKDCLS` on a VACOLS::Assign record with [`TSKACTCD` of 'EXT', 'HCL', or 'POA'](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L54))
    - Priority if [BFAC is "7"](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L304) or there is an [AOD diary or hearing](https://github.com/department-of-veterans-affairs/caseflow/blob/840e1047077ca9433fc77af76bd41616e7c450ce/app/models/vacols/case.rb#L130)

### How long do priority cases normally sit?
- Legacy appeals are "Distributed at" the date the case moves from location 81 or 83 to a judge
   - [`VACOLS::Priorloc`](https://github.com/department-of-veterans-affairs/caseflow/blob/27a56e4f02a2c50d6717e093987c58522566a079/app/models/vacols/priorloc.rb#L3) can be used for this as well. How we [update all case](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L336)s location to ["distribute" them](https://github.com/department-of-veterans-affairs/caseflow/blob/27a56e4f02a2c50d6717e093987c58522566a079/app/queries/vacols_location_batch_updater.rb#L13)

### What is our current priority target and how many priority cases are we distributing?
[Priority target is calculated](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L112) as the ratio of [sum of priority cases on all dockets](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L88-L93) to [the total number of attorneys in caseflow * 3](https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket_coordinator.rb#L123-L125). The current priority count and total batch size is stored in [`statistics`](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L57-L58) on our [`Distributions`](https://github.com/department-of-veterans-affairs/caseflow/blob/43562ed9e75b14c6f949802521da9df6a4214c2b/app/models/distribution.rb#L46) table ([metabase](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE1LCJvcmRlci1ieSI6W1siZGVzYyIsWyJmaWVsZC1pZCIsMjk2XV1dfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)). We can determine the number of distributed priority cases through associated `DistributedCases` for each distribution ([metabase](http://query.prod.appeals.va.gov/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NzYsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZC1pZCIsMjg5XSx0cnVlXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==))

### Are we actually distributing the full number of available non priority cases linked to a judge?
In ["step 2"](https://github.com/department-of-veterans-affairs/caseflow/blob/5bbbe90117365a8689e3f894a3cc4223ea229569/app/models/concerns/ama_case_distribution.rb#L30-L33) we distribute legacy and hearing dockets associated with a judge. 
- For legacy appeals, these cases are selected by checking if the [supplied vlj](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L261) is the [vlj on the associated hearing record ](https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L78-L89).
We can leverage this along with some of the above information (when an appeal is ready to be distributed and what appeals were actually distributed in a request) to determine if we are distributing the full set of appeals related to a judge.

## Acceptance Criteria
- [ ] Stats listed above are compiled into a report
- [ ] Implementations of capturing these stats are moved to the code base to be pulled at anytime (May need to spin out a separate ticket on this one)

**Comment by hschallhorn** [comment]
```bash
1 | 
2 | 
3 | ||||
5 | |||||||
8 | 
```
 - A one-time query, not a job
 - How do we query VACOLS for large things like this?
   - the connection is slow to setup, but runs quickly after that

**Comment by hschallhorn** [comment]
[From Yoom](https://github.com/department-of-veterans-affairs/caseflow/issues/14541#issuecomment-645053157):
> This is a fantastic start! More questions will likely arise during the investigation.
> 
> When collecting data, group appeals by these characteristics and their permutations:
> * Priority vs Non-priority
> * AMA vs Legacy
> * Tied to judge vs. genpop
> * Hearing vs Non-hearing (aka docket type)
> * Ready for distribution vs. blocked vs. other
> 
> From Hunter: Where the first in first out ordering happens:
>  * Legacy: https://github.com/department-of-veterans-affairs/caseflow/blob/e135ea3d7bb179f67ec62a85e1531b974c930e4d/app/models/vacols/case_docket.rb#L305 (BFDLOOUT is the timestamp the case was moved to case storage aka is now ready to be distributed) 
>   * Ama: https://github.com/department-of-veterans-affairs/caseflow/blob/57e746e91b91c82c9b5f4edac343bde9688b68d9/app/models/docket.rb#L123 (Case is ready to be distributed when the distribution task comes off of a hold and is “assigned”)

**Comment by araposo-tistatech** [comment]
Per DVC Scharnberger, no longer needed.
