### ISSUE TITLE
Add name of the current screen as a session variable  

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#146]
Just need the name of the screen to be available to the template. (The part circled in purple.) 
![header](https://cloud.githubusercontent.com/assets/354277/11130570/b7caede4-8953-11e5-8e90-14eef075dfc2.png)

Blocks #144

**Comment by alex** [comment]
The text there is specific to which template file is being rendered, so I don't think we need to have a variable for this?

**Comment by webinista** [comment]
We may not. I guess the question now is where does that information live and how can I add it to the HTML header?

**Comment by webinista** [comment]
This actually sits in `app/views/layouts/application.html.rb`, which is used across the application. I think it makes sense to break this into a partial and set the title of each screen that way.

**Comment by alex** [comment]
It shouldn't need to be, there should be a way to have each specific template provide that value for the base. I don't know how to do this in ERB though. Do you @plusjeff ?

**Comment by alex** [comment]
Ok, http://guides.rubyonrails.org/layouts_and_rendering.html#structuring-layouts specifically `content_for` and `yield` is the right way to do this. Thanks @sigmavirus24!

**Comment by sigmavirus24** [comment]
:cake:
