### ISSUE TITLE
Create Front End for adding or removing VLJs from Auto-Distribution of Cases

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14608]
## User or job story
User story: As a DVC, I need the ability to add or remove VLJs from the case auto-distribution feature, so that judges do not receive cases while they are on leave. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: Priority Case Auto-Distribution
- [ ] This feature should be accessible to the following user groups: DVCs
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]
- [ ] DVC have the ability to add or remove judges from the case auto-distribution feature

## Release notes
DVCs ow have the ability to add or remove VLJs from receiving auto-distributed priority cases. 

### Technical notes
Auto-distribution will need to check if VLJ is allowed to receive auto-distributed cases. 

### Resources/other links
Product Brief: https://docs.google.com/document/d/1EjX-tYz0iI1hLP61p2p-O5rLvltj7NmlIofYRRwPMMs/edit#

**Comment by hschallhorn** [comment]
Some places we discussed where this could live!

Where|Current View
---|---
As a button or toggle on the team management page, next to each judge team|![Screen Shot 2020-06-26 at 4 59 43 PM](https://user-images.githubusercontent.com/45575454/85901349-a904d180-b7cf-11ea-9d06-7a2938c8601d.png)
As a button or toggle on the judge team team management page|![Screen Shot 2020-06-26 at 5 05 53 PM](https://user-images.githubusercontent.com/45575454/85901234-51fefc80-b7cf-11ea-957f-4bd9b62126db.png)
As an entirely new organization (Add users to enable automatic push, remove to disable)|![Screen Shot 2020-06-26 at 5 02 34 PM](https://user-images.githubusercontent.com/45575454/85901032-e87eee00-b7ce-11ea-9e5d-60fdbebc6e79.png)

#### Note
To access these pages, log in as TEAM_ADMIN and select "Caseflow team management" from the main caseflow dropdown

![Screen Shot 2020-06-26 at 5 06 34 PM](https://user-images.githubusercontent.com/45575454/85901264-6ba04400-b7cf-11ea-886d-6bb599c9c2d6.png)

**Comment by RyanRoyUX** [comment]
BVA Admins: Some of these are Nava/Tista
JENNIFER WHITE
- MARTINA JONES
JOHN GOSNELL
- RAVEN TOLSON
SHALANDA BOYKIN
MICHAEL SANFORD
WILLIAM TURNER JR
JEROME JOHN
DHONYALE GIBSON-TAYLOR
IGOR GIL

**Comment by araposo-tistatech** [comment]
@RyanRoyUX @hschallhorn I confirmed Jennifer should no longer have access.

**Comment by RyanRoyUX** [comment]
Caseflow ACD - BVA Admins (Full permissions)
https://www.figma.com/proto/Zg5mJV7q5RzvVGeKLpu9Cx/ACD2?node-id=18%3A0&scaling=scale-down-width

Caseflow ACD - DVC's & Assistants (Lite Permissions)
https://www.figma.com/proto/Zg5mJV7q5RzvVGeKLpu9Cx/ACD2?node-id=32%3A2333&scaling=scale-down-width

VLJ's Team Managment Page (VLJ Permissions)
https://www.figma.com/proto/Zg5mJV7q5RzvVGeKLpu9Cx/ACD2?node-id=46%3A0&scaling=scale-down-width

**Comment by araposo-tistatech** [comment]
Confirmed by DVC Scharnberger VLJs should not have the ability to toggle the feature.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||
5 | |||||||||
8 | 
```

NOTE: Does not include "Available on" changes

#### Why 5?
* Additional permissions for viewing the team management page
* Finer permissions to only view the "judge teams" on the team management page
* Even finer permissions to only allow dvcs to view and toggle job

**Comment by araposo-tistatech** [comment]
@hschallhorn I received agreement to remove DVC Staff Assistants from this AC, but we will need to add it later so I have created a separate ticket for that. 

https://github.com/department-of-veterans-affairs/caseflow/issues/14925

**Comment by araposo-tistatech** [comment]
@hschallhorn can you confirm I am able to enable this for DVCs next week for testing?

**Comment by araposo-tistatech** [comment]
@hschallhorn the BVA Admins are reporting they are no longer able to delete judge teams. My assumption is this used to occur via the "Update" button that has now been removed on the page, but please let me know if we never supported deleting judge teams on the Team Management page. 

If we did have that functionality what was the reason for removing it?
