### ISSUE TITLE
Address line and zip code not meeting length requirements

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#1461]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/142/
`>PersonalInfo Address AddressLine1</fieldName><errorType xmlns="http://vbms.vba.va.gov/external/ClaimService/v4">MINIMUM_LENGTH_NOT_SATISFIED</errorType>`
`PersonalInfo Address ForeignMailCode (PostalCode)</fieldName><errorType xmlns="http://vbms.vba.va.gov/external/ClaimService/v4">MINIMUM_LENGTH_NOT_SATISFIED</errorType>`

**Comment by joofsh** [comment]
This one looks more serious. We should move this into the current sprint

**Comment by joofsh** [comment]
Closing this, it's a dup of the connected ticket
