### ISSUE TITLE
Virtual scheduling queue

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#14625]
# Background

> “Trying to ramp up virtual hearings and the [virtual] queue is the answer to increasing our hearing capacity.” – DVC McLeod, 08/25/2020

Until last year, the Board offered three options for hearings: in-person hearings at the Central Office in DC, video hearings at a Veteran’s regional office, or Travel Board hearings where a VLJ tours regional offices across the country for in-person hearings. All three options are constrained by geography, since Veterans are typically scheduled in their regional office queue, and space, requiring rooms in a regional office.

With virtual hearings now partially integrated into Caseflow, we have the potential to remove those constraints. Virtual hearings do not require a room in the Central or a regional office. They also give the Board the opportunity to schedule Veterans on a national level, regardless of geographic location. Veterans that happen to live in states with a long backlog of appeals could be serviced faster in a national queue, providing a better experience for them and potentially reducing those backlogs faster.

# Business value
In the short term, creating a national virtual queue will help rebuild capacity for hearings lost as regional offices remain closed during the COVID-19 pandemic. Over the long term, the virtual queue will allow the Board to increase the number of hearings held year to year and reduce the average days to complete a decision from Notice of Disagreement and the backlog of hearings.

# Acceptance criteria
- Bulk create virtual docket days for a virtual-only queue
- Choose the virtual-only queue when scheduling hearings
- See only virtual hearings in the queue in docket order (specifics on docket order TBD)
- Schedule to a virtual docket day
- Coordinators able to easily work their primary region and assist other coordinators with their regions as time allows
- Analytics and metrics support (TBD)

# Success metrics
- Increase hearings scheduled (averaging \~250-300 virtual hearings/week as of 9/16; was \~550-600 video hearings/week pre-pandemic)
- Maintain ratio of hearings held to hearing scheduled (~20% no show, cancelled, or postponed in Caseflow YTD 2020)

# Assumptions
- This work will fall squarely within the Hearings product and will only require minimal coordination with Queue
- We will always have mixed docket days for multiple reasons
    - "The Hearing Branch's ideal state is virtual-only docket days. But if a Veteran converts to virtual after they've been notified of their video or central hearing, the Hearing Branch won't have enough lead time to backfill the time slot if the Veteran is moved to a virtual-only docket. So the assumption is that mixed dockets will always exist."
    - The "hybrid" option being pursued where where Veterans can potentially go to their RO to join a virtual hearing but the VLJ is remote and in the virtual room is separate work
- Legacy hearings have scheduling priority over AMA hearings right now

# Open questions
- When coordinators are working outside of their primary RO, how do we make sure we don't have multiple coordinators...
    - trying to schedule the same case at the same time?
    - booking (and over-booking) the same docket days?
- How might we improve the scheduling experience so coordinators can more effectively and efficiently use the capacity we'll be adding?

**Comment by lund5000** [comment]
Completed in https://vajira.max.gov/browse/CASEFLOW-48
