### ISSUE TITLE
Unify the many caseflow sort icons!

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14626]
The sort icons in queue and reader are not the same

Order|Queue|Reader
---|---|---
None|<img width="139" alt="Screen Shot 2020-06-30 at 1 53 35 PM" src="https://user-images.githubusercontent.com/45575454/86160015-2cc50380-bad9-11ea-8535-111d400fe88f.png">|<img width="130" alt="Screen Shot 2020-06-30 at 1 53 02 PM" src="https://user-images.githubusercontent.com/45575454/86159999-2898e600-bad9-11ea-98ae-49dbd9c952f1.png">
Asc|<img width="136" alt="Screen Shot 2020-06-30 at 1 53 43 PM" src="https://user-images.githubusercontent.com/45575454/86160046-36e70200-bad9-11ea-9d6a-be2356c8f72b.png">|<img width="139" alt="Screen Shot 2020-06-30 at 1 53 15 PM" src="https://user-images.githubusercontent.com/45575454/86160065-3cdce300-bad9-11ea-9147-05fbc43e58f7.png">
Desc|<img width="142" alt="Screen Shot 2020-06-30 at 1 53 47 PM" src="https://user-images.githubusercontent.com/45575454/86160083-41a19700-bad9-11ea-80f1-76060546ef53.png">|<img width="138" alt="Screen Shot 2020-06-30 at 1 53 10 PM" src="https://user-images.githubusercontent.com/45575454/86160098-47977800-bad9-11ea-8f3c-641d1e55e0d3.png">

## AC
- [x] (Design) Determine which we prefer (neither is an option)
- [ ] (Engineering) Create a shared component that implement's design's choice and reuse for all sorting icons across caseflow

**Comment by geronimoramos** [comment]
My vote is for the Reader style! It is visible and clear, with less opportunity for misinterpretation. The greyed out queue can be perceived as disabled or not as visible to a more color-blind user imo.
