### ISSUE TITLE
Map BGS::ShareErrors to non-500 errors

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14634]
Ensure calls to `BGSService` handle `BGS::ShareError`s so they do not inappropriately return 500 error codes, which can cause PagerDuty alerts.

Search Sentry alerts for `BGS::ShareError` to see instances where a controller returns this error.

Subclasses of `BGS::ShareError` that can be caught and `rescue_from`: https://github.com/department-of-veterans-affairs/ruby-bgs/blob/b6d05017344a861b4b858c037f8b277e25ea84f2/lib/bgs/errors.rb#L98-L103

Selection of status codes to return: https://www.restapitutorial.com/httpstatuscodes.html

See this PR for an example with IDT's controller: _Originally posted by @yoomlam in https://github.com/department-of-veterans-affairs/caseflow/pull/14633_

**Comment by yoomlam** [comment]
Intake:
* https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6641: "BGS::ShareError: No record found for file number"

GET https://appeals.cf.ds.va.gov/appeals
* https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10344: "BGS::ShareError: gov.va.vba.utils.ShareException"

**Comment by ajspotts** [comment]
On 7/16 we experienced ~3.5k of the [BGS::ShareError: No record found for file number errors](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6641/) in a 3 hour time window.  Notified Foxtrot to make them aware.
