### ISSUE TITLE
Build out feature flag for full page video-to-virtual conversions

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14641]
## Description
Build out new feature flag for new full page video-to-virtual conversions

Proposed feature flag name: `full_page_video_to_virtual `

## Acceptance criteria
- [x] Confirm user with feature flag can see new page
- [x] Confirm user w/o feature flag _can't_ see new page, can still see modal
- [ ] Add toggle configuration to [the appeals-deployment repo](https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/features-config.yml)

**Comment by lund5000** [comment]
Outstanding work is adding users to the flag, which I will do in a separate PR when we have the list ready.
