### ISSUE TITLE
End-to-end test Central-to-virtual flow

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14643]
## Description
End-to-end testing for Central-to-virtual flow

## Acceptance criteria
- [ ] [maybe] Reach out to BGS team with data request for VSO user
- [ ] Set up appeal in UAT
- [ ] Set up user data in UAT
  - [ ] VLJ
  - [ ] Hearing Coordinator
- [ ] End-to-end testing scheduled for Caseflow team

## Background/context/resources
https://github.com/department-of-veterans-affairs/appeals-qa/wiki/Creating-dog-food-test-data-for-virtual-hearings

**Comment by rubaiyat22** [comment]
Central to Virtual dogfooding 1 testing plan: https://hackmd.io/K5JJ0MqLQhyk-VMu4KFLXg?view
