### ISSUE TITLE
Difference in "ASSIGNED TO" for legacy and ama judge/attorney tasks

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14656]
The "ASSIGNED TO" label for a legacy task (a legacy case assigned to a judge or an attorney) is listed as the user's `VACOLS::Staff slogid` while the "ASSIGNED TO" label for an ama task shows their `Caseflow::User css_id`

Legacy Task|AMA Task
---|---
![Screen Shot 2020-07-08 at 1 01 58 PM](https://user-images.githubusercontent.com/45575454/86948562-4be81480-c11b-11ea-9498-7e11efbc1991.png)|![Screen Shot 2020-07-08 at 1 02 18 PM](https://user-images.githubusercontent.com/45575454/86948572-4ee30500-c11b-11ea-83a4-8cf95c5c4af2.png)

We should be displaying the same thing in these 2 cases

### AC
- [ ] Design settles on how we should be displaying an assignee (slogid, css_id, full name, "F. Last", etc)
- [ ] The same name format is shown for the assignee of an ama appeal and a legacy appeal

### References
Where we pull [assigneeName](https://github.com/department-of-veterans-affairs/caseflow/blob/660bcf53cec1b933a8041a4955ae345186f84609/client/app/queue/components/TaskRows.jsx#L144-L149) to display in task rows
This is the[ appeal location code](https://github.com/department-of-veterans-affairs/caseflow/blob/ba8b8ad060d7d37c1c38a7df1eefd0fc41c411b6/app/models/serializers/work_queue/legacy_task_serializer.rb#L51-L53) for legacy tasks which is the `VACOLS::Staff slogid` of the assignee
This is the [assignee's css_id](https://github.com/department-of-veterans-affairs/caseflow/blob/660bcf53cec1b933a8041a4955ae345186f84609/app/models/serializers/work_queue/task_serializer.rb#L55-L57) for ama tasks

**Comment by yoomlam** [comment]
Let's also make ASSIGNED_TO and ASSIGNED_BY consistent, regardless of appeal type.
