### ISSUE TITLE
Wrong cases in judge queue after assigning case to an attorney

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14655]
### Steps to reproduce
1. Sign in as a judge with no of few cases in their normal (review) queue.
1. Go to your assign queue and select an ama appeal (request more cases if there are none)
1. Assign the case to an attorney from the case details page
1. Notice the case and a black case show up in the users queue
1. Refresh the page and notice both errant task rows no longer appear (correctly)

After Assign|After Refresh
---|---
![Screen Shot 2020-07-07 at 2 36 18 PM](https://user-images.githubusercontent.com/45575454/86947169-6caf6a80-c119-11ea-93c2-d5a86dab414c.png)|![Screen Shot 2020-07-07 at 2 36 28 PM](https://user-images.githubusercontent.com/45575454/86947183-6faa5b00-c119-11ea-8d76-b0c39f8f6108.png)

### AC
- [ ] When auto-directed to a judge's queue after assigning a case to an attorney, the queue should show an accurate representation of the cases assign to the user (should match the queue loaded on refresh)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||||||
5 | ||
8 | 
```

Fixes:
 - state management tweaks 
   - prone to errors
   - small lift
 - hard refresh when navigating to queue 
   - possible performance issues
   - good path if we can assert the performance won't be hit too much
 - ~full pull of tasks~ 
   - way too much


#### Why 1?
* 

#### Why 2?
* 

#### Why 3?
* Either fiddling around with state or ensuring we aren't introducing degraded performance


#### Why 5?
* Ensuring our tests catch these situations
