### ISSUE TITLE
Create Dispatch Establish Claims controller schema to catch mismatch Special Issues

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14659]
## Description
Read through Yang's documentation [here](https://github.com/department-of-veterans-affairs/caseflow/wiki/Controller-Schemas) and create a controller-schema for the [Dispatch Establish Claims controller update_appeal route](https://github.com/department-of-veterans-affairs/caseflow/blob/7fcfc5d95c89f0efb97f36d5203d88caf8b4603c/app/controllers/dispatch/establish_claims_controller.rb#L16-L19).

## Acceptance criteria
- [ ] Ensure existing tests pass

## Background/context/resources
Followup to #14018 - Caseflow Dispatch front end and back end rely on two sets of Special Issues, so implementing this schema puts some checks in place. Right now mismatching ids are silently discarded. With the schema they will produce a warning

## Technical notes
- [Another schema implementation as a guide ](https://github.com/department-of-veterans-affairs/caseflow/pull/14368/files)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||
3 | ||||||
5 | |||
8 | 
```


#### Why 1?
* God documentation on how to do

#### Why 2?
* Have never done it before!

#### Why 3?
* Well documented and straight forward, but some spin up time for folks who haven't seen the schema work

#### Why 5?
* Ramp-up
