### ISSUE TITLE
Mark Cases as OT | Success Banner Remains Persistent

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14667]
## Description
When a VLJ successfully marks a case as OT the success banner remains persistent even after clicking out of the case details and going to the VLJs Your Cases page. 

It also displays in the modal if the mark cases as OT link is clicked again. 

Screenshot for reference: 
![Success Banner](https://user-images.githubusercontent.com/59883609/87065690-608de080-c1df-11ea-83d8-32098d74eaaf.png)

![Success Banner in Modal](https://user-images.githubusercontent.com/59883609/87066109-00e40500-c1e0-11ea-9636-fd1263d09761.png)

## Acceptance criteria
- [ ] The success banner does not remain after clicking out of the case details page
- [ ] The success banner does not remain after clicking the Mark Case as OT link again. 

## Background/context/resources
Occurred during dogfooding Issues #11 & #13 in [document](https://docs.google.com/document/d/1PA1YUQ7RiP1mOuZShG-Ya4nwooodIXLoVCXDAOrGZhU/edit#)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | ||||||||
3 | ||
5 | 
8 | 
```

See `resetErrorState` or `resetAlerts`.

#### Why 1?
* Clear problem we've solved similar of before

#### Why 2?
* State management is tricksy :myprecious:

#### Why 3?
* Ensure we aren't clearing success banners that should persist

**Comment by lomky** [comment]
SCREEN | BEFORE|AFTER
---|---|---
Overtime Modal | ![OT modal - before](https://user-images.githubusercontent.com/6129479/87686785-ed421c80-c752-11ea-9ca0-d4350ca68c11.gif) | ![OT modal](https://user-images.githubusercontent.com/6129479/87686790-eddab300-c752-11ea-82ef-43a4ef548b7e.gif)
Queue | ![case list - before](https://user-images.githubusercontent.com/6129479/87686805-f4692a80-c752-11ea-9b09-c6f1e83b57f2.gif) | ![case list](https://user-images.githubusercontent.com/6129479/87686809-f59a5780-c752-11ea-85fa-31e98cb6f3a8.gif)
Place On Hold Modal | ![on hold modal - before](https://user-images.githubusercontent.com/6129479/87686835-fd59fc00-c752-11ea-9963-fc0c79874c99.gif) | ![on hold modal](https://user-images.githubusercontent.com/6129479/87686836-fdf29280-c752-11ea-9875-2084f4151835.gif)
