### ISSUE TITLE
Design System - Modal Designs

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#14669]
## Problem statement

There are visual design inconsistencies in modals across Caseflow products, which is causing confusion when new modals need to be designed. There are also two primary use cases for modals (currently) that seem to be appearing: i) alerting users and prompting immediate action and ii) prompting users to complete a flow (ideally with more than 3 steps)

## Current challenges
The Intake modal is not consistent with other modals across Caseflow, and Intake design is seeing the need for modals with a larger width to accommodate user flows. With upcoming functionality on Caseflow products, there is a need to quickly be able to re-use a modal of a larger width. 

## What is out of scope?
- N/A

## Background/context
There is one modal design in the current styleguide, but its width seems to currently not accommodate some larger design needs. 

## What are the unknowns?
Do we need to conduct usability testing in order to test the efficacy of the larger modal design?

## Existing resources

- [Current styleguide modal](https://www.caseflowdemo.com/styleguide#modals) 
- Intake Modal design: 
![Screen Shot 2020-06-23 at 12.00.55 PM.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/e47bb6c0-a663-4478-96d2-726cf338e45a)

## Success criteria

- [x] Modal(s) proposal
- [x] Share at design critique for feedback
- [ ] Iterate on modal
- [ ] Send to engineering

**Comment by rutvigupta-design** [comment]
Based on feedback from the Caseflow design team, Rutvi and Ryan will continue to iterate on this modal, potentially based on a 8-point grid.

**Comment by rutvigupta-design** [comment]
We should probably do something with this (:

**Comment by ryanroyroy** [comment]
We should but I don't know how much has changed since we worked on it last. It may be best to gift this to Geronimo and Carolyn for review.

**Comment by rutvigupta-design** [comment]
Oops I didn't realize you'd get notified! For now, I linked it in a spreadsheet that leads are using to track design system improvements.
