### ISSUE TITLE
use alternate method for saving space when using the paper_trail gem

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#14668]
## Description
The `save_changes` feature [has been deprecated](https://github.com/paper-trail-gem/paper_trail/blob/21ead888296f022ad63d907b4b15ea598596d1e6/CHANGELOG.md#breaking-changes-affecting-fewer-people) in the paper_trail gem as of version 10.0.0 (we use 10.3.1 at the moment). Instead we should take the recommended course of either
 - dropping the `object` column (if we don't need it for the `Task` model) or 
 - writing an `object_changes_adapter`.

## Background/context/resources
The save_changes param is currently used on three models: [Document](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/document.rb#L13), [Annotation](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/annotation.rb#L8), and [DocumentsTag](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/documents_tag.rb#L7)
[PaperTrail gem repo](https://github.com/paper-trail-gem/paper_trail)
[PR that introduced the use of `save_changes`](https://github.com/department-of-veterans-affairs/caseflow/pull/12261)

**Comment by hschallhorn** [comment]
Think it may be worth writing an `object_changes_adapter`. Here's the [original thread](https://dsva.slack.com/archives/C2ZAMLK88/p1569966018070300) where we stopped saving create records.
