### ISSUE TITLE
Allow user to select a room manually when creating a new hearing day

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14674]
## Description

In the add hearing day modal, the user only has the option to automatically assign a room or omit a room entirely. The edit hearing day modal has the option to reselect a room manually. They should have an option to select a room manually. TBD what this option would look like, but here were some options that we discussed:

  1. Moving the dropdown from the edit hearing day modal
  2. Moving the dropdown from the edit hearing day modal, and highlighting the automatically selected option 
  3. Moving the dropdown, removing the checkbox, and having an "Auto" option in the dropdown.

## Acceptance criteria

- [ ] Ensure the user has an additional option to select a hearing room manually

## Background/context/resources

Created out of #14614

**Comment by lund5000** [comment]
Closing as won't fix since virtual hearings have given the VLJs the ability to hold hearings from anywhere, making rooms much less a part of day-to-day operations for the Branch.
