### ISSUE TITLE
Help | Create Reader Help Page

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1467]
**Story**
When I don't understand something or need more information, I want to access a Help page so I can quickly find answers to my questions.

**Description**
Create a Help page, accessed via the Help link in the header menu, that follows the same structure as Help pages for other Caseflow applications. Initially this page will contain FAQ content (training videos TBD in future stories)

## Acceptance Criteria

1. Verify that a new Dispatch Help page has been created with the following sections and their sub-copy (refer to mockup):

     Section |Header|Sub-copy
     ---|---|---
     Introduction|Welcome to the Reader Help Page!|Here you will find Training Videos and FAQs for Caseflow Reader. If you still need help please contact the Caseflow Product Support Team by calling 1-844-876-5548. We will assist you as quickly as possible. _(this text should be a lead-paragraph)_
     Training Videos|Training Videos|Coming Soon. _(this text should be a lead-paragraph)_
     FAQ |Frequently Asked Questions|
     FAQ Answers|(No header)|

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "FAQs" is a hyperlink to the Frequently Asked Questions section.
1. Verify in the Frequently Asked Questions section, it contains listing of all questions. (Refer to [Reader FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader%20FAQs.md))
1. Verify that in the FAQ Answers section, it contains all questions and their answer.
1. Verify that each question in the FAQ section is a hyperlink to its answer.
1. Verify that clicking on 'back to top' takes you to the top of the page.

## Designs
Same as Dispatch mocks, but replace "Dispatch" with "Reader" and refer to [Reader FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader%20FAQs.md) for content.

![dispatch help page](https://cloud.githubusercontent.com/assets/23316107/24629755/2d27b224-1888-11e7-9029-d0a7096c3860.png)

**Comment by abbyraskin** [comment]
on hold until FAQs are complete

**Comment by abbyraskin** [comment]
Might be able to pull in Sandra for dev help on this one, as she created the Dispatch help page.

**Comment by abbyraskin** [comment]
here it is, @Sjones352 😄

**Comment by mmlumba** [comment]
@Sjones352 @abbyraskin I added the AC to have both the "Introduction" and "Training Videos" sub-copy to be lead paragraphs as specified by @gnakm

**Comment by Sjones352** [comment]
### Screenshot


<img width="1280" alt="screen shot 2017-05-12 at 2 21 39 pm" src="https://cloud.githubusercontent.com/assets/23080951/26011262/6580e65e-371e-11e7-8277-c4d6ed9f3819.png">

**Comment by astewarttistatech** [comment]
Hey @Sjones352 the spacing in "Coming Soon" is off. 

Current view: 
![readerhelp](https://cloud.githubusercontent.com/assets/23038505/26065371/b830d2f2-3961-11e7-9877-ed1e73a2271c.png)

**Comment by Sjones352** [comment]
### Fixed 
<img width="1080" alt="screen shot 2017-05-15 at 2 55 15 pm" src="https://cloud.githubusercontent.com/assets/23080951/26074081/9215f5c6-397e-11e7-9960-5bfadde9b305.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access /reader/help
2. Verify UI and copy against mocks

Screenshots:
![readerhelp](https://cloud.githubusercontent.com/assets/23038505/26109918/b75e9f2c-3a1e-11e7-9a2e-444b1d10f2eb.png)
