### ISSUE TITLE
Give HearingsManagement, HearingAdmin, and Transcription admins the ability to reassign tasks

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14676]
Many tasks assigned to hearings management team members do not have an action to reassign the task as we do for many other tasks.

## What tasks are assigned to HearingsManagement users?

```ruby
pp Task.open.where(assigned_to: HearingsManagement.singleton.users).group(:type).order(:count).count
{"HearingAdminActionMissingFormsTask"=>1,
 "HearingAdminActionFoiaPrivacyRequestTask"=>1,
 "HearingAdminActionVerifyPoaTask"=>1,
 "ChangeHearingDispositionTask"=>5,
 "ScheduleHearingColocatedTask"=>6,
 "HearingAdminActionForeignVeteranCaseTask"=>12,
 "HearingRelatedMailTask"=>15,
 "HearingAdminActionIncarceratedVeteranTask"=>81,
 "TranscriptionTask"=>412,
 "HearingAdminActionOtherTask"=>458,
 "HearingAdminActionVerifyAddressTask"=>549,
 "NoShowHearingTask"=>1373}
```

### ChangeHearingDispositionTask
Defined [here](https://github.com/department-of-veterans-affairs/caseflow/blob/4f20149a6dce0d6fd358078296ae96915a42cd80/app/models/tasks/change_hearing_disposition_task.rb#L19-L21)
⛔  Cannot be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
### HearingRelatedMailTask
Not defined. Defaults to default [task available actions](https://github.com/department-of-veterans-affairs/caseflow/blob/69d7138c9afd7b0e3b1cf245b754abe0e506e9e3/app/models/task.rb#L214)
✅   Can be reassigned by the user it is assigned to
✅   Can be reassigned by an admin
### NoShowHearingTask
Defined [here](https://github.com/department-of-veterans-affairs/caseflow/blob/7adbc4bdb0e06b0741e9576d0c682a4a40ae6b92/app/models/tasks/no_show_hearing_task.rb#L25-L27)
⛔  Cannot be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
### ScheduleHearingColocatedTask
Defined [here](https://github.com/department-of-veterans-affairs/caseflow/blob/b30f6c2af75dcedcbe557100644c8744a72228b5/app/models/tasks/schedule_hearing_colocated_task.rb#L17-L19)
⛔  Cannot be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
### TranscriptionTask
Defined [here](https://github.com/department-of-veterans-affairs/caseflow/blob/1b73b88bcc16369d848dae509d441e326d4ce030/app/models/tasks/transcription_task.rb#L29)
⛔  Cannot be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
### HearingAdminActionTask
Base class for all hearing admin task classes
✅  Can be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionFoiaPrivacyRequestTask
Not defined. Defaults to `HearingAdminActionTask.available_actions`
✅  Can be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionForeignVeteranCaseTask
Defined [here](https://github.com/department-of-veterans-affairs/caseflow/blob/3c1a55ffb5b851cde1aeeb7a5416786b0efce18b/app/models/tasks/hearing_admin_action_foreign_veteran_case_task.rb#L12-L16)
⛔  Cannot be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionIncarceratedVeteranTask
Not defined. Defaults to `HearingAdminActionTask.available_actions`
✅  Can be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionMissingFormsTask
Not defined. Defaults to `HearingAdminActionTask.available_actions`
✅  Can be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionOtherTask
Not defined. Defaults to `HearingAdminActionTask.available_actions`
✅  Can be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionVerifyAddressTask
Defined [here](https://github.com/department-of-veterans-affairs/caseflow/blob/121519bf05fd912206e307e052643411104f3f94/app/models/tasks/hearing_admin_action_verify_address_task.rb#L14)
⛔  Cannot be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin
#### HearingAdminActionVerifyPoaTask
Not defined. Defaults to `HearingAdminActionTask.available_actions`
✅  Can be reassigned by the user it is assigned to
⛔  Cannot be reassigned by an admin

### AC
- [x] Gather list of tasks that should have the reassign action (all)
- [ ] Admins of the following orgs can reassign a task assigned to a user in their org
   - [ ] HearingsManagement
   - [ ] Transcription
   - [ ] HearingAdmin

**Comment by chandracarney** [comment]
Thank you for all of the detailed information @hschallhorn! The Hearing Management Branch would like all tasks associated with their queue(s) to follow this pattern: 
“If I am an admin, I should be able to reassign **any** task assigned to my org’s users.”

Along with `HearingsManagement`, the HMB also has the `HearingAdmin` and `Transcription` queues under their purview and would ideally like to follow the pattern there.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||
3 | |||||
5 | 
8 | 
```
#### Why 2?
* Testing should be straightforward

#### Why 3?
* Tracking down all tasks that need this reassign action for admins

**Comment by hschallhorn** [comment]
```ruby
pp Task.open.where(assigned_to: [HearingsManagement.singleton.users, HearingAdmin.singleton.users, TranscriptionTeam.singleton.users].flatten).group(:type).order(:type).count
{"AttorneyTask"=>2,
 "ChangeHearingDispositionTask"=>10,
 "EvidenceSubmissionWindowTask"=>1,
 "HearingAdminActionFoiaPrivacyRequestTask"=>1,
 "HearingAdminActionIncarceratedVeteranTask"=>119,
 "HearingAdminActionMissingFormsTask"=>1,
 "HearingAdminActionOtherTask"=>443,
 "HearingAdminActionVerifyAddressTask"=>61,
 "HearingAdminActionVerifyPoaTask"=>1,
 "HearingRelatedMailTask"=>8,
 "NoShowHearingTask"=>1364,
 "ScheduleHearingColocatedTask"=>3,
 "TimedHoldTask"=>17,
 "TranscriptionTask"=>350}
```

**Comment by hschallhorn** [comment]
What are the parents of these task types and who are they assigned to?

```ruby
task_types = [
        ChangeHearingDispositionTask,
        HearingRelatedMailTask,
        NoShowHearingTask,
        ScheduleHearingColocatedTask,
        TranscriptionTask,
        HearingAdminActionTask.subclasses
      ].flatten.map(&:name)

user_tasks = Task.open.where(assigned_to_type: User.name, type: task_types)
parent_tasks = Task.where(id: user_tasks.pluck(:parent_id))
parent_tasks.group(:assigned_to_type).count
=> {"Organization"=>2438}
pp parent_tasks.group(:type).order(:type).count
{"HearingAdminActionFoiaPrivacyRequestTask"=>1,
 "HearingAdminActionIncarceratedVeteranTask"=>119,
 "HearingAdminActionMissingFormsTask"=>1,
 "HearingAdminActionOtherTask"=>443,
 "HearingAdminActionVerifyAddressTask"=>60,
 "HearingAdminActionVerifyPoaTask"=>1,
 "HearingRelatedMailTask"=>11,
 "HearingTask"=>10,
 "NoShowHearingTask"=>1439,
 "ScheduleHearingColocatedTask"=>3,
 "TranscriptionTask"=>350}
Organization.where(id: parent_tasks.pluck(:assigned_to_id)).pluck(:name)
=> ["Board of Veterans' Appeals", "Hearings Management", "VLJ Support Staff", "Transcription", "Hearing Admin"]
# Concerning. What task types have parents not assigned to hearings orgs?
non_hearing_parent_tasks = parent_tasks.where.not(assigned_to: [HearingsManagement.singleton, HearingAdmin.singleton, TranscriptionTeam.singleton])
pp non_hearing_parent_tasks.group(:type).order(:type).count
=> {"HearingRelatedMailTask"=>3, "HearingTask"=>10}
```
So we cannot rely on list of assignees being `parent.assigned_to.users`, we'll have to make our own task action
