### ISSUE TITLE
Fix issue on assign hearings page where multiple dockets with the same date get highlighted simultaneously

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14673]
## Description

On the schedule veteran's screen, selecting a duplicate/double-booked docket highlights multiple entries on the sidebar. The room displays as null, and there is no way to distinguish multiple dockets on the same day from each other.

## Acceptance criteria
- [ ] Ensure there is more helpful text than `null` if there is no hearing room associated with a hearing date
- [x] Ensure that multiple dockets do not get highlighted together if they have the same room and date
- [ ] Ensure that it's possible to distinguish between multiple dockets on the same day if the room is double-booked

## Background/context/resources

Created out of #14614

<img width="1220" alt="Screen Shot 2020-07-08 at 11 41 12 AM" src="https://user-images.githubusercontent.com/1298274/86939865-17bb2680-c110-11ea-8472-2aa2b7533edd.png">

## Technical notes

Use the ID of the docket to determine which day to highlight in the sidebar

**Comment by ferristseng** [comment]
Looks like I had fixed this already in #14660 

https://github.com/department-of-veterans-affairs/caseflow/blob/17bf10c7169e5c24dd76ffcd8701c5b23f3a1ef8/client/app/hearings/components/assignHearings/AssignHearings.jsx#L49

**Comment by tomas-nava** [comment]
created #14956 to break out the `null` hearing room issue;

I can only find 2 examples of Hearing days on the same date, in the same RO, and with the same room number; both are in the past. If this is a situation that could happen in the future, we'll open a new ticket for the other unchecked AC: "Ensure that it's possible to distinguish between multiple dockets on the same day if the room is double-booked"
