### ISSUE TITLE
handle appeals with null docket_type during ETL

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14685]
## Description
Several Sentry alerts started popping up in Team Delta's Slack channel regarding null docket_type during an ETL job.

@nanotone states:
> it’s entirely normal for an appeal to not have docket_type, docket_number, or receipt_date when intake is just starting. so i’d say it should definitely not trigger a sentry alert

Handle this scenario and at least reduce the alert level.

## Acceptance criteria
- [ ] No more Sentry alerts like this.
- [ ] ETL DB is populated with all other appeals

## Background/context/resources
[Slack convo](https://dsva.slack.com/archives/CPEMQPVKR/p1594386612001300)

## Details

Other options considered:
- Wait until someone sets the docket_type. 1 of the ~2~ 3 was fixed this way.
- Notify the board to set a docket type for the appeal.
- We can update the ETL code to skip appeals with null docket_type, IF we want to stop the alert.
- If not fixed soon, some set of entries in ETL DB is not being sync'd due to several updates being in a single (failed) transaction.

**Comment by rajinderbhanot** [comment]
Exclude the appeal(s) with NULL docket_type value from syncing to ODS.

**Comment by yoomlam** [comment]
Upon further investigation, the ETL syncer that is causing the error processes only `established` appeals, so this is a valid error and should not be silenced.

@nanotone states:
> `docket_type` should be non-nil once an appeal has `established_at`
