### ISSUE TITLE
Display legacy opt-in selection on "Add Issues" page 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#14698]
## User story
As a member of the Intake Team, I would like to be able to see a complete summary of the case I am processing which includes whether the appellant has selected the legacy "opt-in" section, so I can at a glance see the entire details of this case.

## Problem statement
Design should create a quick mockup to demonstrate how the selection of "OPT-IN from SOC/SSOC" can be displayed on the "Add Issues" page which demonstrates a summary of the case. 

## Acceptance criteria
- [ ] Add a row to the table on Add Issues for all decision review types that show the legacy issue opt-in selection from the review page
 - [ ] Row title "SOC/SSOC Opt-in"
 - [ ] Data: Yes or No
- [ ] Add to a feature test

## What is out of scope?

- Redesigning the "OPT-IN from SOC/SSOC" question. 

- Adding in additional information (should be a yes/no question). 

- Displaying any other information

- Redesigning the "Add Issues" page 

## Background/context
This need came out of an internal audit the Foxtrot team conducted in June 2020. 

## What are the unknowns?
N/A

## For research tickets only: What questions do we hope to answer? What are our learning goals?
N/A

## For writing tickets only: Writing guidance, if possible, such as voice and tone desired, relevant styleguides, and who the approvers should be.
Use current "Add/Remove Issues" page styling. 

## Existing design and content
![Screen Shot 2020-07-15 at 6.57.05 AM.png](https://images.zenhubusercontent.com/5ee7e3b72a6c07806d69db7d/b6b6204e-bfa6-4156-a201-1547d3174d25)

## Success criteria
A user can see the "OPT-IN from SOC/SSOC" selection in addition to the veterans name, receipt date, review option and claimant. 

## Technical/logistical constraints (if known)
N/A

**Comment by leikkisa** [comment]
PS - Tag Rutvi when there's a PR with a screenshot for a quick check
