### ISSUE TITLE
Search | Ability to search by issue tag

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1469]
**Story**
When drafting a decision on a case, I want to search by issue tag, so I can filter my list of documents by issue.

**Description**https://github.com/department-of-veterans-affairs/caseflow/issues/1469
- Expands scope of existing search functionality/behavior to include issue tags created by user

## Acceptance Criteria
- Validate that user's issue tags (created per case) are included as valid search criteria
- Validate that the document number reflects the number of documents as a result of search
- Validate that it also picks up comment texts that are the same as issue tags
- Validate that there is a "remove" icon next at the far right of the search box that clears search result [Remove icon svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Remove%20Icon.svg) 

## Mockup

I search for "Knee" and it showed me all the documents with issue tag knee and a document with the word knee in the comment. The table only expanded the row with the word knee in a comment. 

![image](https://cloud.githubusercontent.com/assets/13420618/25044995/da4aa606-20f7-11e7-9be6-42631fd80859.png)

**Comment by astewarttistatech** [comment]
Blocked by the ability to not create issue tags

**Comment by kierachell** [comment]
**PASSED**
<img width="1282" alt="screen shot 2017-05-03 at 12 02 21 pm" src="https://cloud.githubusercontent.com/assets/18075411/25669834/cbc12c3a-2ff8-11e7-8c52-c9d1fb8274ca.png">
<img width="1304" alt="screen shot 2017-05-03 at 12 02 30 pm" src="https://cloud.githubusercontent.com/assets/18075411/25669833/cbc07c22-2ff8-11e7-90e5-ad6e57ad7af9.png">
<img width="1386" alt="screen shot 2017-05-03 at 12 03 16 pm" src="https://cloud.githubusercontent.com/assets/18075411/25669832/cbbf90f0-2ff8-11e7-9638-acbb8e3b8aef.png">
