### ISSUE TITLE
Automatic Case Distribution Reporting

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14706]
## Description
OIT is requesting we provide a weekly report, via Slack or Datadog, after the automatic case distribution job runs for the following data: 

- Number of priority cases distributed
- Number of cases distributed waiting longer than 7 days
- Number of cases not distributed

## Acceptance criteria
- [ ] After the job runs weekly, we need to send a report via Slack or Datadog with the number of priority cases distributed, number of cases distributed waiting longer than 7 days, and the number of cases not distributed.

**Comment by hschallhorn** [comment]
Added as AC to #14604
