### ISSUE TITLE
(2) clean up open hearing tasks with closed parents on legacy appeals

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#14703]
Connects #13438 

## Description
Team Echo identified 5 legacy appeals with open hearing tasks that have closed parents. Investigate and resolve the appeals.

## Acceptance criteria
- [x] investigate and document investigation in the HackMD document linked in [this slack post](https://dsva.slack.com/archives/C3EAF3Q15/p1593010944050400)
- [ ] resolve the issues with the task trees
- [ ] note resolution in the connected issue #13438

**Comment by yoomlam** [comment]
Maybe close #12678 once this ticket is done.
