### ISSUE TITLE
Automate fix for RedistributedCase::CannotRedistribute Sentry alert

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14705]
## Description
So far, Bat Team is responsible for fixing appeals that need to be redistributed when prompted by `RedistributedCase::CannotRedistribute` Sentry alerts. We should automate the fix so that appeals are not stuck/delayed.

The fix is described [here](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#redistributedcasecannotredistribute-sentry-alert), and Hunter provided a snippet to fix several at a time:
```ruby
vacols_ids=%w"0000000 1111111 2222222 3333333"
vacols_ids.size

appeals = vacols_ids.map { |vacols_id| LegacyAppeal.find_by(vacols_id: vacols_id) };
appeals_with_active_tasks = appeals.select do |appeal|
  appeal.tasks.active.where.not(type: [TrackVeteranTask.name, RootTask.name]).any?
end.map(&:vacols_id);

## Fix appeals that should be distributed
appeals_without_active_tasks = vacols_ids - appeals_with_active_tasks
appeals_without_active_tasks.size

appeals_without_active_tasks.map do |vacols_id|
  DistributedCase.find_by(case_id: vacols_id).nil?
end
# Fix the appeals without active tasks
appeals_without_active_tasks.each do |vacols_id|
  DistributedCase.find_by(case_id: vacols_id).update!(case_id: "#{vacols_id}-attempt-#{Time.zone.now}")
end

# Double-check active tasks
appeals_with_active_tasks.map{|id| LegacyAppeal.find_by(vacols_id: id).treee}
appeals_with_active_tasks.map { |vacols_id| LegacyAppeal.find_by(vacols_id: vacols_id).location_code }

appeals_with_active_tasks.each do |vacols_id|
 la=LegacyAppeal.find_by(vacols_id: vacols_id)
 needs_update = la.location_code!=LegacyAppeal::LOCATION_CODES[:caseflow]
 puts (needs_update ? "Updating #{vacols_id}" : "Skipping #{vacols_id}")
 AppealRepository.update_location!(la, LegacyAppeal::LOCATION_CODES[:caseflow]) if needs_update
end

```

## Open Questions
1. The Bat Team instructions and snippet call for some manual inspection, is there anything done during inspection that cannot be automated?
2. What is the impact/harm of redistributing a case without active tasks (ignoring TrackVeteranTasks)? 
3. The snippet allows redistribution of cases with on-hold tasks and not active tasks. Why does this make sense?

Caseflow should probably use a different suffix to differentiate from manual fixes that use suffix '-attempt1'.

## Acceptance criteria
- [ ] Cases that fit the criteria should be automatically redistributed without a Sentry alert occurring
- [ ] Do not redistribute the case if it already at the judge -- see #13596

## Background/context/resources

Also see #13596 and #14597.

## Technical notes

Check for when redistribution can or cannot occur:
https://github.com/department-of-veterans-affairs/caseflow/blob/13b99749f8bac8b6d969f693f1d230f4fb2fa4dd/app/services/redistributed_case.rb#L26-L38

What Caseflow does in each scenario:
https://github.com/department-of-veterans-affairs/caseflow/blob/13b99749f8bac8b6d969f693f1d230f4fb2fa4dd/app/services/redistributed_case.rb#L18-L22

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | ||||||
5 | 
8 | 
```

#### Why 2?
* Already have the code to implement from batteam wiki

#### Why 3?
* Looking into what conditions it is acceptable to redistribute (as there are very few at the moment and they are very specific cases)

**Comment by yoomlam** [comment]
While we're in this part of the code, let's test using `tags` instead of `extra` for fields that we want to search for in Sentry.

In `redistributed_case.rb` around line 63:
```ruby
  def alert_existing_distributed_case_not_unique
    error = CannotRedistribute.new("DistributedCase already exists")
    # Method 1
    Raven.tags_context judge: new_distribution.judge.css_id
    Raven.capture_exception(
      error,
      # Method 2
      tags: { vacols_id: case_id },
      extra: {...}
```

See these references:
* Method 1: https://github.com/getsentry/raven-ruby#context
* https://docs.sentry.io/clients/ruby/#additional-context
* https://docs.sentry.io/clients/ruby/context/#tags

**Comment by ajspotts** [comment]
jobs must have queue_with_priority attribute to run properly
