### ISSUE TITLE
Add CAVC Court Order Button to Case Details

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14708]
## User or job story
User story: As a litigation support user or Lead, I need to be able to create a CAVC Remand Task (root task) from a Veteran's Case Details page for AMA cases. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: CAVC_Remand
- [ ] This feature should only be accessible to the following user groups: Litigation Support 
- [ ] A button displays on the Case Details page of a Dispatched/completed appeal that begins the remand intake workflow and creates a CAVC Remand Root Task
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Start CAVC Remand documentation

## Release notes
The Litigation Support Organization now has the ability to intake a CAVC remanded cases for Dispatched appeals. 

### Designs

![image](https://user-images.githubusercontent.com/49766982/88851382-8afd0900-d1a1-11ea-9d67-bff926a83a37.png)

### Technical notes
This modal will kickoff the workflow here (add link to story). 

### Resources/other links
https://docs.google.com/document/d/1-EzNBC83BjyiRhtBl_s5rrf2Qejp4b7NHsVC7JW4FzA/edit#

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||||
3 | |||
5 | 
8 | 
```

#### Why 2?
* One button, test user permissions

#### Why 3?
* Tests?
* storybook?

**Comment by yoomlam** [comment]
@geronimoramos Please add a mockup of button to shows its location within the Case Details page.

**Comment by araposo-tistatech** [comment]
@araposo-tistatech combine with #14795

**Comment by araposo-tistatech** [comment]
Closing per note that this can be combined with #14795
