### ISSUE TITLE
Search | Search by category label

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1470]
**Story**
When drafting a decision on a case, I want to search by category label, so I can filter my list of documents by category.

**Description**
- Expands scope of existing search functionality/behavior to include category labels

## Acceptance Criteria
- Validate that the three category labels ("Procedural", "Medical", and "Other Evidence") are included as valid search criteria -- searching for any of these words reduces the documents list to only those documents with an associated category (new functionality), comment text (existing functionality), or other document metadata (existing functionality).
- Validate that the document number reflects the number of documents as a result of search
- Validate that it also picks up comment texts that are the same as the category name
- Validate that there is a "remove" icon next at the far right of the search box that clears search result [Remove icon svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Remove%20Icon.svg) 
- When filtered, show an alert below the search bar that documents are filtered and that gives a link to clear the search.

## Mock up

![image](https://cloud.githubusercontent.com/assets/13420618/25045074/3e6c1976-20f8-11e7-8572-626d5f8d8db5.png)

This is example of a search word, where the search results picked up both category and comment text. 
![image](https://cloud.githubusercontent.com/assets/13420618/25045080/477a2440-20f8-11e7-98c8-251ad4ce3959.png)

**Comment by kierachell** [comment]
blocked by bug in #1780

**Comment by kierachell** [comment]
## partial search works inconsistently: 'Evidence' <- "Other Evidence" vs 'cedural' <- "Procedural"
<img width="1278" alt="screen shot 2017-05-03 at 1 02 36 pm" src="https://cloud.githubusercontent.com/assets/18075411/25672261/cffff684-3000-11e7-9ef3-1094fc545980.png">
<img width="1215" alt="screen shot 2017-05-03 at 1 02 44 pm" src="https://cloud.githubusercontent.com/assets/18075411/25672262/d000976a-3000-11e7-94fe-f8cfeabcd12f.png">

## Also, no Alert is displayed

**Comment by abbyraskin** [comment]
> Also, no Alert is displayed 

@kierachell the alert is shown only if a filter has been selected -- it doesn't look like the filters are in the selected state in your screenshot.

**Comment by mdbenjam** [comment]
@kierachell What entries should have been shown for the Evidence search? I just tried partial searching and it worked fine. And as Abby said, there is no alert for searching.

**Comment by mdbenjam** [comment]
NVM I see what you're saying. I don't know that this is a bug. Other evidence is just marked as "other" in the metadata, so it has no concept of evidence. I think it's okay that we don't come up with anything for "evidence". @abbyraskin if you agree, can you move this back to in validation?

**Comment by kierachell** [comment]
**PASSED**
Then it works :D
