### ISSUE TITLE
Rollback new contention additions from Caseflow Dispatch

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14714]
## Description
Rollback https://github.com/department-of-veterans-affairs/caseflow/issues/14018 & the Caseflow Dispatch portion of this one: https://github.com/department-of-veterans-affairs/caseflow/issues/13396

## Acceptance criteria
- [ ] Code adding the new contentions additions is rolled back for Caseflow Dispatch
- [ ] Code validating the special issues is rolled back 

## Background/context/resources
Per Jed & Paul at the Board, Caseflow Dispatch is not used by BVA Dispatch, but rather ~AMO~ OAR. Due to this John G. at the Board has decided this should be pulled back and requested by ~AMO~ OAR if it is needed.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | |||||||
3 | |
5 | 
8 | 
```

Be careful not to affect Queue
* Don't touch SI Frontend components - if you need to, confirm it doesn't break Queue!

#### Why 1?
* revert the PRs? Maybe?

#### Why 2?
* 

#### Why 3?
* Refactor code in dispatch? (probably not as there is planned deprecation?)
