### ISSUE TITLE
Intake | Docket Change | Enter Information

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14719]
As an BVA Attorney with the Office of the Clerk of the Board I want to be able to enter the necessary information so that I best represent the veteran's request.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Covered by #15097 - closing.
