### ISSUE TITLE
Intake | Docket Change | Design a way for OCB to receive Requests to Modify from an Attorney/VLJ/Hearing Coordinator

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14717]
## User story and requirements
As a BVA Attorney at the Office of the Clerk of the Board, I need a way to receive Requests to Modify from Attorneys/VLJs/Hearing Coordinators so that I can review them and if granted, begin processing the request.

## Open Questions
- How can we give users a way to do this in Caseflow without overwhelming the OCB with invalid requests?
- Are there any parallels with MTV we can draw from?
- What if it was a "Review Request to Modify" task that gets sent to OCB?
- Why is the Outlook Inbox easier than doing things in Caseflow? What is the real worry here?
- If NOT granting, what should happen to the case? Get kicked back to the attorney/VLJ/hearing coordinator?

## Acceptance criteria
- [ ] Figma File with design(s)
- [ ] Screenshot(s) of design(s)

### Out of scope

Designs beyond the indicated user story

### Designs

- [ ] Figma File with design(s)
- [ ] Screenshot(s) of design(s)

### Background/context

Please see the Mural for the end-to-end user workflow. 
Please see the [epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978) for more background.

### Technical notes

TBD

### Resources/other links
[Epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978)
Mural with user workflow

**Comment by rutvigupta-design** [comment]
Closing because Board users have determined this to be out of scope (they will continue to handle this via email).
