### ISSUE TITLE
Intake | Docket Change | Design a way for Attorneys/VLJs/Hearing Coordinators to send a Request to Modify to OCB

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14716]
## User story and requirements
As a BVA Attorney/VLJ/Hearing Coordinator, I need a way to send a Request to Modify that I noticed, to the Office of the Clerk of the Board, so that they can review it and begin to process the request.

## Open Questions
- How can we give users a way to do this in Caseflow without overwhelming the OCB with invalid requests?
- Are there any parallels with MTV we can draw from?
- Would this be a "Mail Task"? 
- What if it was a "Review Request to Modify" task that gets sent to OCB?

## Acceptance criteria
- [ ] Figma File with design(s)
- [ ] Screenshot(s) of design(s)

### Out of scope

Designs beyond the indicated user story

### Designs

- [ ] Figma File with design(s)
- [ ] Screenshot(s) of design(s)

### Background/context

Please see the Mural for the end-to-end user workflow. 
Please see the [epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978) for more background.

### Technical notes

TBD

### Resources/other links
[Epic](https://github.com/department-of-veterans-affairs/caseflow/issues/13978)
Mural with user workflow

**Comment by rutvigupta-design** [comment]
Closing because Board users have determined this to be out of scope (they will continue to handle this via email).
