### ISSUE TITLE
Documents List | Top menu: fixed on page

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1471]
**Description**
When scrolling on the Documents List page, I want the column headers to stay fixed on the page, so I don't lose important context about what I'm viewing.

## Acceptance Criteria
- Validate that the header row and everything in it (**Category,** **Receipt Date,** **Document Type**, **Issues**, and **Comments** and filter icons) is visible at all times
- Validate that Search, # of documents and "Expand all" button are visible above the table headers

![image](https://cloud.githubusercontent.com/assets/13420618/24813098/be4a7272-1b9a-11e7-8856-81c779945a34.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

## Note
Veteran ID was taken out of header. See [Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)
for updated visual

## Related issues

#1431

**Comment by abbyraskin** [comment]
@gnakm assigning to you for final review in case the table headers change. and does it make sense to you to keep the tabs fixed as well?

**Comment by gnakm** [comment]
@abbyraskin Yup! I updated the mock so that it is accurate.

**Comment by abbyraskin** [comment]
General note: we are no longer using the tabs shown in the mock, so this will only apply to the  column headers

**Comment by kierachell** [comment]
**PASSED**
it scrolls!
![scrollmeh](https://cloud.githubusercontent.com/assets/18075411/25643184/2a86a750-2f6c-11e7-8a62-1bf707f6f4b4.gif)
