### ISSUE TITLE
Intake | Docket Change | Select Requested Docket Type

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14718]
As a BVA Attorney at the Office of the Clerk of the Board I want to be able to select the requested Docket type so that I process the appeal in the way the veteran has requested.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Covered by #15097 - closing.
