### ISSUE TITLE
Intake | Docket Change | Confirm Selections

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14724]
As an Attorney with the Office of the Clerk of the Board I want to be able to confirm my selections so that I can ensure the right information was entered.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Covered by #15102 - closing.
