### ISSUE TITLE
Intake | Docket Change | Appeal routing

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14726]
As an Attorney with the Office of the Clerk of the Board I want to know that based upon the selected docket type that the appeal will get routed to the proper team/individual's queue.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Covered by #15105 - closing.
