### ISSUE TITLE
Intake | Docket Change | Close out tasks

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14720]
As an Attorney at the Office of the Clerk of the Board I want to be able to close out any tasks that are no longer relevant to the newly selected docket type.

# Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Covered by #15099 and #15101 - closing.
