### ISSUE TITLE
Intake | Docket Change | Open new tasks

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14722]
As an Attorney with the Office of the Clerk of the Board I want to be able to open any tasks that are relevant to the newly selected docket type.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Covered by #15100 and #15101 - closing.
