### ISSUE TITLE
Congressional Inquiries: Backfill Cases Processed Prior to Release

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14721]
Litigation Support has been using VACOLS for AMA Lit Support tasks that Caseflow was not able to support on AMA day 02/15/2019.

These include:
congressional inquiries

Lit Support leadership, have a list of these cases and should be contacted in order to ensure this information is backfilled in Caseflow once Lit Support functionality is available for congressional inquiries.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||
5 | |
8 | 
```

What information does lit support have on cases that need to be backfilled? Do they have all information? Does the API we chose have historical information if lit support does _not_ have all info

Blocked by ticket [TK] where we are creating the congressional fields associated with a task

#### Why 1?
* 

#### Why 2?
* Could be a simple organizing of a speadsheet and running a rails update query
* think most of the work (getting the info) will happen before eng

#### Why 3?
* Doubt information coming from the board will be accurate/complete

#### Why 5?
* Open questions
* Ensuring the information provided is correct?
