### ISSUE TITLE
Intake | Docket Change | OCB can assign tasks to appropriate team

### ISSUE THREAD

**Issue by RebeccaBaumTT** [department-of-veterans-affairs/caseflow#14723]
## User story
As an Attorney with the Office of the Clerk of the Board I want to be able to assign the appeal to the correct individual/team based upon the selected Docket type so that the appeal moves forward correctly and efficiently.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: change_docket_type
- [ ] This feature should be accessible to the following user groups: Office of the Clerk of the Board
- [ ] After changing the docket type on an appeal, OCB has a task to set up the tasks on the appeal with the new docket type
  - [ ] Screen showing the original appeals tasks, with an action to assign them or remove them
  - [ ] The ability to add a new task to the new appeal
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: ()[link]

## Open questions
- Which tasks should be available on the menu?
- 

### Designs
- (Link to Figma file)[]
- Screenshots

### Background/context
When a docket type gets changed on an appeal, the original appeal may have some tasks that need to be copied and assigned, as well as potentially new tasks that need to be added.

Some example of tasks that may need to be assigned or added:
 - FOIA task -> FOIA or privacy team
 - Translation task -> translation

**Comment by rutvigupta-design** [comment]
Covered by #15105 - the routing should happen automatically based on the new docket and tasks associated with it.
