### ISSUE TITLE
Research Granted Subsitutions

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14738]
## User story
 When a death dismissal decision is dispatched and VBA grants a substitution the appeal needs to be sent back to the Board without the need for an NOD.  

## Problem statement

How will we automatically load these into Caseflow? Does it need to be in the state of the previous appeal?

**Comment by hschallhorn** [comment]
Current questions
- [ ] Do hearings need to be rescheduled?
- [ ] Do evidence submission windows need to be reopened?
- [ ] Should cancelled tasks have the ability to be reopened?
- [ ] What state do we expect these appeals to be in?
   - [ ] Cancelled?
   - [ ] Completed decision and dispatched?
   - [ ] Have the issues been modified at all?
