### ISSUE TITLE
Identify Postgres columns lacking foreign key constraints

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14732]
## Description
Write and run a quick DB analysis script that looks at the Postgres table schemas and outputs a list of columns that are candidates for adding foreign key constraints. Depending on what comes up, this could be a good roadmap toward actually adding those constraints.

## Background/context/resources
[Slack thread](https://dsva.slack.com/archives/CQTDX9BF0/p1595253145000700) motivated by automatic schema tooling that misses foreign relationships due to lack of foreign keys.

## Technical notes
There are a few different ways to introspect on Postgres schema:
- Use `db/schema.rb`
- Use ActiveRecord's underlying machinery -- it may look something like [this](https://stackoverflow.com/a/14949277)
- Use Postgres itself. The `information_schema` and `pg_catalog` meta-tables and views are a good way to query Postgres about its own schema. See, for example, the `tables`, `columns`, and `table_constraints` tables under `information_schema`.

Detect columns that might need foreign keys constraints to be added:
- A column named `<somename>_id` probably refers to the `<somename>s` table by primary key.
- But if the column has a sibling column named `<somename>_type`, then this is probably a polymorphic relation where the foreign table is determined on a per-record basis, and cannot accept a foreign key constraint.
- `belongs_to` in model code are a pretty clear indication of a one-to-many relation. `has_one` indicates a one-to-one relation. `has_many` indicates the flip-side of a one-to-many relation, unless it also has a `through:` argument, in which case it indicates a many-to-many relation via an association table.

**Comment by yoomlam** [comment]
Some related links:
* https://stackoverflow.com/questions/922184/why-can-you-not-have-a-foreign-key-in-a-polymorphic-association
* https://stackoverflow.com/questions/2002985/mysql-conditional-foreign-key-constraints#:~:text=You%27re%20attempting%20to%20do%20a%20design%20that%20is,would%20violate%20several%20rules%20of%20relational%20database%20design.
* https://hashrocket.com/blog/posts/modeling-polymorphic-associations-in-a-relational-database#how-to-choose

**Comment by yoomlam** [comment]
[Multi-phase plan](https://hackmd.io/wum2LtUfSHC-1o6-peBseQ) to add missing foreign keys.
Phase 1 will be careful. The remaining phases will be faster. We'll have to be cautious when adding foreign keys to huge tables like `documents`, so saving that for last.

**Comment by yoomlam** [comment]
Resolved with PR #16333 that identifies missing FKs. There is additional follow-on work to address polymorphic associations.
