### ISSUE TITLE
Investigate AOD cases in Case Storage that have not been distributed

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#14752]
We have a request from John Gosnell to investigate 500+ AOD appeals that are in VACOLS case storage and have not been distributed with the Caseflow automatic case distribution algorithm. Based on Mike Sanford's initial manual investigation, some of these cases are tied to AVLJs and are not distributed because AVLJs cannot order cases. The goal of this ticket is to classify why these appeals are not being distributed.

The team may be asked to come up with a Caseflow solution for distributing these cases, but that solution is out of scope of this ticket

- [ ] Ping Alisa to get the spreadsheet of cases (it uses the appeal ID which may have PII)
- [ ] Verify that the appeals are in case storage and [ready](https://github.com/department-of-veterans-affairs/caseflow/blob/af263fa79c217d5bc565cb20e80ae9691ed8b9fa/app/models/vacols/case_docket.rb#L64-L76) to be distributed in VACOLS
- [ ] Figure out why the appeals are not being distributed (reasons could be - they are tied to an AVLJ, there are open tasks, they are in a different VACOLS location, etc.)

Acceptance criteria
- [ ] Spreadsheet or Metabase table with the cases and reasons for why they're not being distributed

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||
5 | |||||||
8 | ||
```


#### Why 1?
* 

#### Why 2?
* 

#### Why 3?
* Very set rules as to why cases are ready and why they cannot be distributed.

#### Why 5?
* 

#### Why 8?
* 500+ cases

**Comment by hschallhorn** [comment]
Noticed a discrepancy between `counts_by_priority_and_readiness` and the number of appeals actually ready to distribute
```ruby
VACOLS::CaseDocket.counts_by_priority_and_readiness
=> [..., {"n"=>766, "priority"=>1, "ready"=>1},...]
```
One thing this method does not take account of are blocking mail tasks and diary entries. [A case is classified as "ready" if the case is in case storage](https://github.com/department-of-veterans-affairs/caseflow/blob/8b0809e9e952228558aab2cc1e9476a6de8ec76d/app/models/vacols/case_docket.rb#L142).

If we filter out these instances, we get down to 661
```ruby
SELECT_PRIORITY_APPEALS = "
    select BFKEY, BFDLOOUT, VLJ
      from (
        select BFKEY, BFDLOOUT,
          case when BFHINES is null or BFHINES <> 'GP' then nvl(VLJ_HEARINGS.VLJ, VLJ_PRIORDEC.VLJ) end VLJ
        from (
          #{VACOLS::CaseDocket::SELECT_READY_APPEALS}
            and (BFAC = '7' or AOD = '1')
          order by BFDLOOUT
        ) BRIEFF
        #{VACOLS::CaseDocket::JOIN_ASSOCIATED_VLJS_BY_HEARINGS}
        #{VACOLS::CaseDocket::JOIN_ASSOCIATED_VLJS_BY_PRIOR_DECISIONS}
      )
  "

VACOLS::CaseDocket.connection.exec_query(SELECT_PRIORITY_APPEALS).count
=> 661
```

This function is used to [count legacy appeal](https://github.com/department-of-veterans-affairs/caseflow/blob/5778ba3372c7de404f6a2f05bb59c7c580902e12/app/models/dockets/legacy_docket.rb#L15-L22) when calculating our [priority count](https://github.com/department-of-veterans-affairs/caseflow/blob/8c11c829045bbcfb5009c07aa1592a67eb89d983/app/models/docket_coordinator.rb#L99-L104) (total number of priority cases available to distribute) and calculate our [docket proportions](https://github.com/department-of-veterans-affairs/caseflow/blob/8c11c829045bbcfb5009c07aa1592a67eb89d983/app/models/docket_coordinator.rb#L21-L55)
