### ISSUE TITLE
Documents List | Issue tags: filter dropdown component

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1477]
When filtering documents by issue tags, I want to see a dropdown that shows all of the issues and choices for filtering, and what it is currently filtered by. 

## Acceptance Criteria
- Validate that the dropdown contains all of the issue types user has entered (see #1437)
- Validate that when an issue is selected (either by clicking the name or specifically the checkbox), the dropdown shows it being checked off
- Validate that when hovering through the options, it is using hex#5B616B
- Validate that the checkboxes next to each option follows the styling on style guide https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide
- Validate that more than 1 issue can be selected 
- Validate that when clicking Clear issue filter (option 1 in dropdown), the options that were checked on dropdown uncheck [Clear issue remove icon](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Remove%20Icon.svg)
- Validate that all functionality is operable via the keyboard

## Mockups

![image](https://cloud.githubusercontent.com/assets/13420618/25250455/a9aae6c8-25e3-11e7-867a-6fb03e7232e6.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

## Designs

| Unselected | Hover | Selected|
|-------------------- | ------ | --- |
![image](https://cloud.githubusercontent.com/assets/13420618/24776590/6df44768-1aef-11e7-99e1-0fce62c0f739.png) | ![image](https://cloud.githubusercontent.com/assets/13420618/24776794/60c1158e-1af0-11e7-83e9-2c9165c62c90.png) | ![image](https://cloud.githubusercontent.com/assets/13420618/24776598/76ec6f94-1aef-11e7-9a20-697ec3567ba5.png)
| Border and icon hex# 212121 | Border and icon  hex#0071BC | Inner shadow with hex#0071BC
[Unselected SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter%20unselected%20icon.svg) | [Hover SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter%20hover.svg) | [Selected SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter%20selected%20Icon.svg)

## Note
Veteran ID was taken out of header. See [Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)
for updated visual

#1438

**Comment by abbyraskin** [comment]
We're moving the checkboxes to the left for consistency, asking Gina for review.

**Comment by gnakm** [comment]
@abbyraskin I added new mock and added the change to the AC. Switching back to ready for dev.

**Comment by NickHeiner** [comment]
Can we update the mock to match what #1478 now looks like?

**Comment by NickHeiner** [comment]
The SVG does not work for me. @gnakm can you re-upload?

![image](https://cloud.githubusercontent.com/assets/829827/25252189/0b8238fa-25ea-11e7-8fc0-3f03eb99439b.png)

**Comment by gnakm** [comment]
@NickHeiner  Updated!

**Comment by astewarttistatech** [comment]
Current view of issue tags:

![readerflow](https://cloud.githubusercontent.com/assets/23038505/25619830/4a00f4f2-2f1a-11e7-9134-27b2899c4866.gif)

**Comment by kierachell** [comment]
Does there need to be a scrollbar for just one tag?
<img width="360" alt="screen shot 2017-05-03 at 9 27 43 am" src="https://cloud.githubusercontent.com/assets/18075411/25662502/c6c08fde-2fe2-11e7-8159-dbcf1684a91f.png">

**Comment by mdbenjam** [comment]
Opened up #1898 to deal with this. Otherwise I think we're good to go here. Moving back to in validation.

**Comment by kierachell** [comment]
**PASSED**
<img width="1143" alt="screen shot 2017-05-08 at 3 18 12 pm" src="https://cloud.githubusercontent.com/assets/18075411/25821057/99c8b1aa-3401-11e7-81b9-2a11ff73e215.png">
