### ISSUE TITLE
AOD Cases should sort to the top of Queues

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14780]
## Description
While investigating a seperate issue in production, I observed that AOD cases are not bubbling up to the top of a users queue, like we want. Specifically, non-original cases were appearing first in a Judges Assign queue.

## Acceptance criteria
- [ ] AOD cases should always sort to the top of a users queue on page load.

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||
3 | |||||
5 | 
8 | 
```

#### Why 2?
* We previously did this? Re-implement

#### Why 3?
* Kind of investigationy
