### ISSUE TITLE
Bulk Assign should prioritize AOD cases

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14781]
## Description
At the moment the Bulk Assign process processes cases based on the oldest available. We want it to consider AOD & CAVC then oldest dated case.

## Acceptance criteria

Cases are prioritized in the following order for Bulk Assign: 
- [ ] CAVC AOD Cases
- [ ] AOD Cases
- [ ] CAVC Cases
- [ ] Regular appeal stream

**Comment by hschallhorn** [comment]
Where this happens (currently distribute oldest cases first https://github.com/department-of-veterans-affairs/caseflow/blob/869db77756025e9e6358f8f861c0eac0729a1bd1/app/workflows/bulk_task_assignment.rb#L40-L42

Other places we sort by aod first on the back end https://github.com/department-of-veterans-affairs/caseflow/blob/55adb2e1f2b0a09e41873c5d8a3d922728d8aa55/app/models/task_sorter.rb#L76-L80

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | ||||
5 | 
8 | 
```

Could cause all AOD cases to go to 1 person. AOD cases may not be worked as quickly compared to distributing across may people.
Users want it this way 
Currently sorted by `created_at`


#### Why 2?
* reasonably straightforward sort we've done before elsewhere

#### Why 3?
* add tests
* sorting tests end up leading to flakes

**Comment by yoomlam** [comment]
Considering this:
> AOD appeals that are remanded by CAVC are tied to the same judge as wrote the original decision.
[ref](https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Case-Distribution#genpop)

Should CAVC AOD Cases be bulk assigned?

**Comment by hschallhorn** [comment]
tasks are not bulk assigned to judges, they are assigned to members of organizations
