### ISSUE TITLE
New Fiduciary 030 and 040 EP and claim labels to be added to Caseflow Intake

### ISSUE THREAD

**Issue by jimruggiero** [department-of-veterans-affairs/caseflow#14789]
## User or job story
User story: As a Fiduciary Caseflow Intake user, I want two new EP/claim labels created for the Fiduciary HLR and Supplemental letters, so that end-to-end processing can be completed in VBMS and Caseflow and the correct letters generated and sent to claimants. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: establish_fiduciary_end_products
- [ ] This feature should be accessible to the following user groups: Fiduciary intake users
- [ ] Add EP codes and labels:
  - [ ] 030HLRFID > FID-Higher Level Review
  - [ ] 040SCRFID > FID-Supplemental Claim Review
- [ ] Update EndProductCodeSelector to use these claims for HLRs and SCs with the fiduciary benefit_type
- [ ] The payee code selector should appear when choosing a non-veteran claimant on fiduciary claims
- [ ] processed_in_vbms and processed_in_caseflow definitions are updated to account for fiduciary claims being processed in VBMS
- [ ] Update documentation wherever is says only compensation and pension claims are processed in VBMS

## Release notes
Caseflow now supports Fiduciary EP claim labels "FID Higher Level Review" and "FID Supplemental Claim Review" that will appear on HLR and Supplemental letters. These new labels are intended to differentiate labels to be used for Fiduciary vs Compensation and Pension processing and letter generation.

## Open questions
 - ~we're asking if there's anything special about claimants and payee codes~ Nope
 - Do we want to add intake permissions per business line?
- ~Is there a backlog to process?~ No

### Designs
N/A

### Background/context
These new labels are being requested to avoid confusion with the existing EP 030 and 040s in use by compensation and pension. Additionally, these new EP and claim labels are being updated in VBMS and need to be supported by Caseflow to ensure end-to-end processing can occur without workarounds be employed by Fiduciary intake users. Work for new labels is approved under _BSE 67120 Capability to manage EP030 FID HLR correspondence_ and _BSE 67138- Capability to manage EP040 FID Supplemental correspondence_ (see links in Resource section below.)

### Technical notes
Note - these are always non-rating

Files to update EP codes in:
- EndProduct
- END_PRODUCT_CODES.json
- EndProductCodeSelector

There may be some updates in RequestIssue as well, as well as the "processed_in_vbms" definition.

### Other notes
N/A

### Resources/other links
[EP 040 FID Supplemental BSE & BUSs](https://drive.google.com/drive/u/0/folders/1V6XeboOlSBy8fpop2fvC0S0C7tP9JbQ4)
[EP 030 FID HLR BSE & BUSs](https://drive.google.com/drive/u/0/folders/1V6XeboOlSBy8fpop2fvC0S0C7tP9JbQ4)

**Comment by leikkisa** [comment]
Hi all - some initial questions/thoughts from me:

1. I'm asking VBMS if they have the actual EP claim type codes for these, because that's what we send when establishing claims (not the labels).
1. Do all issues on fiduciary claims go on these EPs?  Or is it selected individually per claim?
1. When we create an EP for these, does that mean we should _not_ add these to the Fiduciary Queue in Caseflow?
1. Right now it's only non-rating issues. Is there such a thing as fiduciary rating issues?
1. We allow users to manually select the payee code, but ideally it maps somewhat to the claimant. Currently we support dependents of the veteran as claimants for VBA claims. Is this sufficient? Are there other types of claimants for these?

I might have some more questions later on downstream stuff, like if getting decision issues will be the same, but this is all for now.

**Comment by leikkisa** [comment]
Also, here are the current issue categories for fiduciary (they seem to match the requirements in the doc):

1. Appointment of a Fiduciary (38 CFR 13.100)
2. Misuse Determination (38 CFR 13.400)
3. P&F Director's Negligence Determination for Benefits Reissuance (13.410)
4. RO Director Reconsideration of Misuse Determination (13.400(d))
5. Removal of a Fiduciary (38 CFR 13.500)

**Comment by leikkisa** [comment]
Codes from VBMS 🎉 
030HLRFID > FID-Higher Level Review
040SCRFID > FID-Supplemental Claim Review

**Comment by jimruggiero** [comment]
ccing @jessalvesdesa so she's in the loop with real-time updates on this issue, going forward.

**Comment by jimruggiero** [comment]
Per Eric Solon (Eric.Solon@va.gov) on 7/29/2020:

BLUF: The creation of CaseFlow EP’s is essential to achieving the overall project goal of “Complete end to end Fiduciary Case Management: 100% of Fiduciary workload managed in VBMS with 0 reliance on the BFFS System by end of FY 20”.

Background:

Beneficiary Fiduciary Field System (BFFS) is a [new] case and activities management system [aka modules within VBMS] used by Pension and Fiduciary Services (P&F), Fiduciary Program to control and maintain cases for Veterans who are deemed unable to manage their financial affairs. BFFS provides robust tracking of fiduciaries, including their compliance with VA program requirements. BFFS case management will allow Field Examiners to be automatically assigned cases based on zip codes, Federal Information Processing Standard (FIPS) codes and/or previously scheduled dates and provide a workflow capability for improved tracking of cases, due dates, and paperwork. Due to system limitations and  outdated technologies VBMS Fiduciary will be created under the current VBMS Core application.

The major goal stemming from the implementation of VBMS fiduciary is to remove all reliance on the current BFFS system.   **Currently the Fiduciary appeals process, to include assignment of fiduciary appeals, has a reliance of the BFFS system.   Upon receipt of correspondence from a claimant/beneficiary, a Field Service Representative (FSR) will cest a EP 030/040 in Caseflow. Once the appeal has been cested in CaseFlow, the FSR then will need to input the appeal information in the BFFS system to notify the correct individual to work the “appeal”.** Additionally, there are other factors that will not allow for a reasonable workaround to include: Fiduciary Claims are NWQ excluded, the unique division of work based on Zip Code, VBMS Fiduciary automatic routing rules written in code into the system, the inclusion of divisions and the inability to claims assign to a RO’s Division, creation of Letters using the newly created letter generator and Document Manager. Because there will be no reliance on the BFFS system, this will no longer be an option.  

**Currently, the VBMS Fiduciary Development team has already built some functionality in regards to CaseFlow. This will be entering Business Acceptance Testing (BAT) within the next sprint or two using a Soapbox UI to mimic CaseFlow.** As this is a new application and not currently in production, **functionality is delivered after each sprint and deployed into production September 23, 2020.**  BAT is currently being completed as functionality is built after each sprint. **The final development sprint before Implementation will be completed on September 11, 2020.** Once this sprint is completed, there will not be a full sprint before this VBMS Fiduciary Go-Live. **_The testing timeline is already an identified risk and the earlier the CaseFlow EP’s can be created, the better._**

**Comment by leikkisa** [comment]
Got a response from Israel Hendricks on my questions:
- All the fiduciary claims will go onto EPs
- He said there's nothing special about claimants or payee codes
- He said they'll process the previously intaken claims using the legacy process and we don't have to worry about a backlog

**Comment by leikkisa** [comment]
VBMS will be deploying their piece to production on 11/8, and we should plan to turn on the feature toggle then!
