### ISSUE TITLE
Check `Appeal.aod_based_on_age` rather than the claimant.person's age

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14785]
## Description
Check `aod_based_on_age` on an appeal rather than the claimant’s age to determine AOD.

## Acceptance criteria
- [ ] Code does not call `claimant.advanced_on_docket_based_on_age?` or `person.advanced_on_docket_based_on_age?` 
- [ ] Code does not create/use queries that check `75.years.ago` or equivalent

## Background/context/resources
[Slack convo](https://dsva.slack.com/archives/CAM9FJ85P/p1595969050241600?thread_ts=1595968930.241500&cid=CAM9FJ85P)

## Technical notes
```
$ gg advanced_on_docket_based_on_age\?
app/models/etl/appeal.rb:37:      target.aod_due_to_dob = person&.advanced_on_docket_based_on_age? || false
app/models/person.rb:52:    advanced_on_docket_based_on_age? || AdvanceOnDocketMotion.granted_for_person?(id, appeal_receipt_date)
app/models/person.rb:104:  def advanced_on_docket_based_on_age?
```

**Comment by hschallhorn** [comment]
We should also look for places we do this with raw sql. 

```bash
git grep 75.years.ago
app/models/docket.rb:          .where("people.date_of_birth <= ?", 75.years.ago))
app/models/docket.rb:        .where("people.date_of_birth > ?", 75.years.ago)
app/models/person.rb:    date_of_birth && date_of_birth < 75.years.ago
app/services/etl/builder.rb:      .where("claimant_dob <= ?", 75.years.ago)
```

**Comment by hschallhorn** [comment]
found another
```bash
git grep "75 years"
app/jobs/update_cached_appeals_attributes_job.rb:      "or people.date_of_birth < (current_date - interval '75 years')"
```

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||||
5 | ||||
8 | 
```

search terms: aod, aod?, advance_on_docket, advanced_on_docket, AdvanceOnDocket, AdvancedOnDocket


#### Why 3?
* Tech debt-y. If we miss an instance it's not a huge deal

#### Why 5?
* Want to triple check we are not breaking anything as this is how we determine what cases are priority

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1698
