### ISSUE TITLE
Documents List | Categories: dropdown filter component

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1478]
**Story**
When filtering documents by categories, I want to see a dropdown that shows all the category options, and what it is currently filtered by.

## Acceptance Criteria

- Validate that the dropdown contains **Clear category filter**, **Procedural**, **Medical** and **Other evidence** 
  - [Procedural SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20Blue%20category.svg) Hex #4A90E2
  - [Medical SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20Pink%20category.svg) Hex #FF6868
  - [Other evidence](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Reader%20-%20Green%20category.svg) Hex #5BD998
- Validate that Clear category filter option, resets the filters and clicking outside of dropdown options should exit dropdown

- Validate that Clear category filter has a horizontal gray-lighter line underneath it so that it divides that rest of the categories from it
- Validate that when a category or categories are selected (either by clicking the name of option or specifically the checkbox), the dropdown shows it being checked off
- Validate that when hovering through the options, it is using hex#5B616B, text and check box is hex#ffffff
- Validate that the checkboxes next to each option follows the styling on style guide https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide
- Validate that more than 1 category can be selected
- Validate that a user can open dropdown by tabbing on keyboard

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/25245858/e3129ad8-25d3-11e7-88c3-ba93b4c32378.png)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

## Related Stories
#1432 | Filter by one or more category
#1274 | Associate document to category

**Comment by abbyraskin** [comment]
@gnakm another call for svgs please! :-D

**Comment by NickHeiner** [comment]
If we want to be accessible, everything needs to be operable via the keyboard. We should be writing ACs that either are input agnostic, or if they're going to specifically call out clicking, should also specifically call out keyboard usage.

**Comment by NickHeiner** [comment]
![checkboxes](https://cloud.githubusercontent.com/assets/13420618/24911812/3e0db210-1e9a-11e7-9900-523f91abb95f.png)

![image](https://cloud.githubusercontent.com/assets/829827/25100681/02daadf8-237f-11e7-8019-25d323c516ef.png)

Do we care about the position of the checkboxes relative to the labels being consistent?

**Comment by NickHeiner** [comment]
Clicking on either of these things resets the filters, right?

![image](https://cloud.githubusercontent.com/assets/829827/25103505/d3d02e14-238a-11e7-9d34-bd91fdc9b247.png)

Or did you want the "x" to make the dropdown go away?

**Comment by NickHeiner** [comment]
If the user clicks outside of the dropdown filter, should it be closed?

**Comment by NickHeiner** [comment]
Also, am I correct that this ticket doesn't cover actually filtering the list of documents?

**Comment by NickHeiner** [comment]
Can you give me a mockup of what the hover state is supposed to be? This doesn't seem right:

![image](https://cloud.githubusercontent.com/assets/829827/25104730/786b1700-238f-11e7-8a9b-816e16c83567.png)

**Comment by NickHeiner** [comment]
ping @abbyraskin @gnakm on the questions above.

**Comment by gnakm** [comment]
@NickHeiner Thank you for your patience!

- I will add to AC that all drop downs should be keyboard accessible by tabbing through
- The clear category filter should reset filter and clicking outside of dropdown options should exit dropdown 
- Yes this ticket isn't for actually filtering but for the visual and UX of the dropdown
- Here is the mock for dropdown with hover. I will add specs and detail in AC.

**Comment by NickHeiner** [comment]
Ok, that's great, thanks. So just to confirm, you're saying that clicking on the `x` clears the filter?

**Comment by gnakm** [comment]
@nicholasholtz 

Yes. It should hover the same way as the other options. All text and icon should be white.
![image](https://cloud.githubusercontent.com/assets/13420618/25144881/5726511e-243d-11e7-8662-763db7153259.png)

**Comment by nicholasholtz** [comment]
I think you meant @NickHeiner

**Comment by NickHeiner** [comment]
Also @gnakm can I get an answer to this question?

![image](https://cloud.githubusercontent.com/assets/829827/25156249/7591aaca-2467-11e7-9e85-d4c8b597e11f.png)

**Comment by NickHeiner** [comment]
Are you sure the SVG you linked to is correct? It just looks like a box to me.

![image](https://cloud.githubusercontent.com/assets/829827/25156345/f6102460-2467-11e7-905f-f6089393c7fe.png)

**Comment by NickHeiner** [comment]
> Validate that when hovering through the options, it is using hex#5B616B, text and check box is hex#ffffff

Can you be a little more specific about this? How does the checkbox change on hover?

**Comment by gnakm** [comment]
I uploaded new link! It should work!

**Comment by gnakm** [comment]
@NickHeiner I just want to make sure that the hover doesn't have a 0 fill and that at hover, if the checkbox is unchecked, the empty box shows as white.

**Comment by NickHeiner** [comment]
Ok, great. I've added that SVG, and it looks good, and I believe I have the hover matching what you want. Also, when you get a chance, it would be nice to get confirmation on the following:

![image](https://cloud.githubusercontent.com/assets/829827/25200641/0f89a636-251d-11e7-973e-800b15356fb5.png)

**Comment by abbyraskin** [comment]
@NickHeiner just chatted with Gina, and we're weighing whether the use cases are different enough to warrant inconsistent positioning...We're going to bring it up in our design team meeting tomorrow and will circle back!

**Comment by abbyraskin** [comment]
@NickHeiner we are good with keeping the checkbox are the lefthand side. @gnakm has some slight edits to make to the "clear category filter" section that came out of our discussions -- given that this is already in progress, but for the sake of keeping everything in one place...are you cool with us making those changes/updating the mocks in this ticket directly?

**Comment by gnakm** [comment]
I updated the mock above and adjusted the AC to match it.

**Comment by gnakm** [comment]
@NickHeiner 

1. Right now, when you click on categories and click/unclick an option, there is a slight glitch where it looks like it is being double clicked. Could you take a look at that?

2. This is a cosmetic fix but could you add a little more padding for each option in the dropdown menu? Right now it is looking a bit tight. 14px margin for each option?
![image](https://cloud.githubusercontent.com/assets/13420618/25436465/55b43768-2a61-11e7-9ecb-d77809a264a7.png)

**Comment by gnakm** [comment]
FYI
@kierachell I'm creating a separate ticket for flickering category thing and putting it in the backlog. As for the specs, I'll make a separate ticket for that as well and for best practices will add them from the beginning to the AC moving forward.

**Comment by kierachell** [comment]
**PASSED**
![filtermeh](https://cloud.githubusercontent.com/assets/18075411/25507922/d3107a98-2b7c-11e7-86b0-c029602f0214.gif)
