### ISSUE TITLE
CAVC Remand: Create New Appeal Stream

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14792]
## User or job story
Job story: When a JMR/JMPR CAVC Remand is initiated via the court order form a new appeal stream should be created and linked to the Boards previous decision docket number so that a new decision can be issued. 

## Acceptance criteria
- [ ] If anything would show to users before CAVC Remands enter the system, lock that behind FeatureToggle: cavc_remand
- [ ] New appeal stream is created when Litigation Support team chooses a JMR or JMPR and clicks submit on the court order form
- [ ] New appeal stream is linked to the existing docket number at the Board
- [ ] Create Root Case, Distribution Task and CavcTask
- [ ] Add instances of new appeal stream to seed data
- [ ] Verify the original and new appeal appears when searching for original Docket # 

### Technical notes
Motions to Vacate currently links to the docket number so this is something we should be able to reuse. 

### Resources/other links
https://github.com/department-of-veterans-affairs/caseflow/issues/10991#issuecomment-613095262

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||
5 | |||||||
8 | 
```

Refer to MTV's way of creating a new appeal stream. 


A new `Appeal` record with tasks should be created.
* Update CAVC Remand to create appeal
* Create appeal of CAVC type with tasks
* Create tasks on the appeal

#### Why 3?
* 

#### Why 5?
* New feature test
* Unfamiliarity with creating a new appeal stream
* New appeal stream, non-trivial
* we've never done new appeal flows

**Comment by lomky** [comment]
Existing `new stream` behavior on appeal

https://github.com/department-of-veterans-affairs/caseflow/blob/d59e33969aabc14494ac834e4e84eeb8722ef1b6/app/models/appeal.rb#L92-L112

**Comment by yoomlam** [comment]
@araposo-tistatech Consider breaking up into a 2-point documentation + 3-point implementation tickets.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||||
5 | |
8 | 
```

Existing code, used in multiple places to create the new appeal stream.
 - We can use this preexisting method to create the appeal
 - We'll need to add handling into the InitialTasksFactory:create_subtasks to specify the CAVC tree
 - don't have to rearchitect anything major to the CAVC appeal to go!

@ajspotts  to post notes from spike!

#### Why 3?
* Uses existing functionality
* New tests for this new workflow


#### Why 5?
* Still a little wary!

**Comment by ajspotts** [comment]
Findings from spike [ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/15366) located [here](https://hackmd.io/mLXFsygJThW9Rd8i5T2a6w)
