### ISSUE TITLE
CAVC Remand: Litigation Support Form (Front End)

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14795]
## User or job story
Job story: A a Litigation Support user I need the ability to start and add data for a CAVC Remand to Caseflow so that a new appeal stream can be created and decided by the Board. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: CAVC_Remand
- [ ] This feature should be accessible to the following user groups: CAVC Litigation Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Start CAVC Remand Documentation to describe what cavc remand features caseflow supports (to be updated as more cavc functionality is added)
- [ ] Add CAVC Court Order Button to Case Details page of a Dispatched/Completed appeal that presents the form in a new top section
- [ ] CAVC Litigation Support user can select a cavc judge from a prepopulated dropdown
- [ ] CAVC Litigation Support user can add receipt date to the form
- [ ] CAVC Litigation Support user can designate the type of remand (JMR, JMPR) on the form 
- [ ] CAVC Litigation Support user can enter dates for
  - [ ] Court decision
  - [ ] Judgement 
  - [ ] Mandate
- [ ] Confirmation Modal appears with the following copy when the form is completed & submitted (confirmation message may not be true at the end of this ticket until new appeal stream and 90 day letter task portions have been implemented): 
        - You have successfully created a CAVC Remand case
           This has generated a Send 90 Day Letter task in your team's queue

## Testing
- [ ] Ensure users can copy and paste values from the cavc website without modifying data (see [here](https://github.com/department-of-veterans-affairs/caseflow/issues/14795#issuecomment-722592391) for how to get to the publicly available records)

## Release notes
The Litigation Support Organization now has the ability to intake JMR & JMPR CAVC remanded cases for previously dispatched appeals.

### Designs

[➡️ UI designs and flow ⬅️
](https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=891%3A0)

![Case Details without task v2](https://user-images.githubusercontent.com/49766982/93249738-9eab0180-f746-11ea-9614-615cd0652a0a.png)

### Resources/other links
https://docs.google.com/document/d/1-EzNBC83BjyiRhtBl_s5rrf2Qejp4b7NHsVC7JW4FzA/edit#

[How to view a CAVC public docket case
](https://www.loom.com/share/cdab86399e524632a1ba3e8ae6b3a12e)

**Comment by araposo-tistatech** [comment]
@geronimoramos can we add the designs for the form here limited to what is needed for adding a JMR & JMPR? Also, please add any necessary AC's that I may have missed.

**Comment by geronimoramos** [comment]
Added in the [UI designs/flow ](https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=891%3A0) with some items in review:
1. pre-populating CAVC judges' names (awaiting confirmation from lit support)
2. Potentially getting rid of the judgment date input field (awaiting confirmation from lit support)

**Comment by geronimoramos** [comment]
`box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.15);` for the Post Dispatch actions section

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||
5 | |||
8 | 
```

#### Why 3?
* New ui
* No tricky interactions between fields, simple data entry

#### Why 5?
* Rpecs for UI testing

**Comment by geronimoramos** [comment]
See here how to get to view a public docket case on the CAVC website https://www.loom.com/share/cdab86399e524632a1ba3e8ae6b3a12e
