### ISSUE TITLE
Bulk Assign | SSC reassign to Judge

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#14796]
## User or job story
As an SSC, I need to be able to select multiple cases and reassign them to a judge so that I can do it more quickly than assigning the cases one by one.

SSCs don't currently have access to the bulk assignment feature.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by hschallhorn** [comment]
This is done on the judge assign page through the AssignToAttorneyWidget https://github.com/department-of-veterans-affairs/caseflow/blob/613c9f7f6f9e1bf0699e01e1a482aca5cec0f014/client/app/queue/components/AssignToAttorneyWidget.jsx#L142-L146

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||
5 | ||||||||||
8 | 
```

History:
* They had this feature
* Removed this feature due to confusion over assigning to Acting judges

They cannot assign to judge in bulk assign.

Offer the dropdowns: Assign to attorney (selecting offers attorneys) and Reassign to [another?] Judge (selecting offers judges)

#### Why 3?
* Backend already exists?

#### Why 5?
* complete overhaul of the AssignToAttorneyWidget
* OR create a new ReassignToJudgeWidget to be reused in the reassign to judge modal?

**Comment by hschallhorn** [comment]
Detailed explanation. Previously, on the judge assign page, attorneys and judges were listed when selecting cases to assign. If the user the cases were being assigned to was a judge, we would reassign the case to the judge by creating a new JudgeAssignTask assigned to the user. If the user was an attorney, we would assign the case to them with an AttorneyTask.

This gets complicated as judges and SSCs were using this to BOTH reassign cases to an AVLJ (intending to reassign it to them as a judge) and assign cases to an AVLJ (intending assign it to them as an attorney)

As there was no way for the user to indicate their choice and we had a task action on the case details page for them to reassign a case to a judge, we disallowed assigning to judges from this page.

#### Current state of the page
The judge or ssc can select multiple cases they want to assign
They then select a user. The first dropdown is a list of all attorneys on their team. The second dropdown lists all attorneys (previously all attorneys and judges)
![Screen Shot 2020-07-30 at 1 53 49 PM](https://user-images.githubusercontent.com/45575454/88957123-6a4db580-d26c-11ea-8add-79a7abee635c.png)
![Screen Shot 2020-07-30 at 1 53 59 PM](https://user-images.githubusercontent.com/45575454/88957128-6c177900-d26c-11ea-98d5-cf9a780b1df2.png)

**Comment by hschallhorn** [comment]
@mbaenatan @RyanRoyUX @geronimoramos Going to move this into design backlog! Engineering is wondering what the best way to implement a way to distinguish "I am assigning this to an attorney" vs "I am reassigning this to a judge".
Another dropdown for all judges and a "reassign X cases" button? A toggle? A voice command?

**Comment by geronimoramos** [comment]
- Reassigning cases JudgeAssignTasks and reassigning to another Judge -> bulk reassign tasks to a judge to distribute to their attorneys
- We view SSCs as Judges in Caseflow
- SSCs much of the time manually assign cases to judges
- If SSC assigns DistrbutionTasks to a judge with over 15 cases in their assignment queue, there's no blocker to going above the 15 case limit. Only ACD gets a 15 limit.

**Comment by mbaenatan** [comment]
Included in design bonus set for sprint August 10-21. After investigating further decided to keep in backlog as low priority since work has not been prioritized by the Board yet
