### ISSUE TITLE
"Share" comment deep-link in Reader

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#14810]
## User or job story
As a user, I need the ability to "share" the deep-link to a comment in the Comments view in Reader so that I can send the comment to other users.

From DVC Osborne:
> "Rank 14 of 20
Add the “Share” link-copy feature to each comment in the “Comments” view in Caseflow."

See
- https://github.com/department-of-veterans-affairs/caseflow/pull/8429

## Acceptance criteria
- [ ] Add "Copy link" button next to "Jump to Section"

**Comment by hschallhorn** [comment]
Deep link for comments

![Screen Shot 2020-07-28 at 2 54 23 PM](https://user-images.githubusercontent.com/45575454/88951250-b9dbb380-d263-11ea-96c3-265b69e64821.png)
![Screen Shot 2020-07-28 at 2 55 16 PM](https://user-images.githubusercontent.com/45575454/88951248-b9dbb380-d263-11ea-9b26-b731d841b259.png)


Comments view in reader

![Screen Shot 2020-07-28 at 2 59 40 PM](https://user-images.githubusercontent.com/45575454/88951246-b9431d00-d263-11ea-9a66-3df809a73ae7.png)
![Screen Shot 2020-07-28 at 2 55 45 PM](https://user-images.githubusercontent.com/45575454/88951247-b9431d00-d263-11ea-87ca-4ce3715da4f8.png)

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||
2 | ||||||||
3 | |
5 | 
8 | 
```

## AC
- [ ] Add a copy icon (button?) next to "Jump to section"

#### Why 2?
* Already have a reusable component for this
* Could be one line of code

#### Why 3?
* Frontend & Reader are intimidating
