### ISSUE TITLE
Styleguide | Accordions

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1482]
As a developer and content writer, I want to see what the accordions section will look like in the living style guide

## Acceptance Criteria

- [ ] Verify that there is a title for Accordion and three subsections: Border, Borderless, Border with outline
- [ ] Verify that the border and borderless accordion looks like ones available on [USWDS accordion design](https://standards.usa.gov/components/accordions/).
- [ ] Verify that Border with outline has 1px stroke with `$color-gray-light`
- [ ] Verify that there is Accordion in the side nav of the style guide
- [ ] Verify that the copy below is under the title and above the UI component 

## Mockup
Border
![image](https://user-images.githubusercontent.com/13420618/27204642-3d6fff46-51fa-11e7-8e98-48e3a937a19c.png)

Borderless 
![image](https://cloud.githubusercontent.com/assets/13420618/24804370/38606d1a-1b7c-11e7-8214-80d3a460d5bc.png)

Border with outline 
![image](https://user-images.githubusercontent.com/13420618/27298512-f6ae35b4-54f6-11e7-99fe-7a03e608e412.png)

**Title**
Accordion

**Description**
Our accordion style was taken from the US Web Design Standards. Accordions are a list of headers that can be clicked to hide or reveal additional content.

**Copy for expanded accordion**

Millions of Americans interact with government services every day. Veterans apply for benefits. Students compare financial aid options. Small business owners seek loans. Too often, outdated tools and complex systems make these interactions cumbersome and frustrating. Enter the United States Digital Service. We partner leading technologists with dedicated public servants to improve the usability and reliability of our government's most important digital services. Visit [USDS.gov](https://www.usds.gov/) to learn more.

**Comment by NickHeiner** [comment]
Where are accordions used in the app currently?

**Comment by NickHeiner** [comment]
Ah, nm, I see in #2424 that it's planned for Reader.

**Comment by mmlumba** [comment]
@gnakm would it be possible to put the accordion text within the ticket also?

**Comment by mmlumba** [comment]
Potential third party React plugins:
*react-sanfona*: accessible React accordions https://github.com/daviferreira/react-sanfona

**Comment by gnakm** [comment]
@mmlumba I added the text to the Copy section under AC above. I'm advertising for USDS 😛

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in : Dev
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living style guide
2. Navigate to the accordions section via navbar or by manual scrolling. 
3. Verify the functionality of each accordion based on AC
4. Verify the copy based on mocks and AC

Screenshots:
![accordions](https://user-images.githubusercontent.com/23038505/27897030-ad8718c2-61eb-11e7-8730-cd9d7cc718f0.gif)
