### ISSUE TITLE
Fields should be validated on "Confirm Case Details", "Confirm Hearing", and "Sign and Certify" [5]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1484]
Add validation to the Confirm Case Details, Confirm Hearing, and Sign & Certify pages. See the Dispatch application for reference code and design.

# Acceptance Criteria

- On the Confirm Case Details page, if any field marked "Required" is on the page and is not filled out when the user clicks "Continue", the page should scroll to the required field, and there should be red text that spells out the error. The "Continue" button should remain enabled throughout. 

^ & ditto for the Confirm Hearing and Sign & Certify pages.

**Comment by astewarttistatech** [comment]
Hey @shellicious and @amprokop I need a little more context on what "visibly disabled" means. If you can provide a mock or a more in-depth description, that would be great.

**Comment by amprokop** [comment]
great! @shellicious do you have an example of this? i'm not 100% sure what you want from a design perspective

**Comment by shellicious** [comment]
Like this @amprokop and @astewarttistatech:

(From the UI Kit)

![screen shot 2017-04-12 at 12 56 08 pm](https://cloud.githubusercontent.com/assets/1178390/24969664/7f36465e-1f7f-11e7-942a-a5f8d3051fa2.png)

Hex color is D6D7D9 for the gray background. 

In context, it would look something like this (color is off due to this being an older wireframe): 

![screen shot 2017-04-12 at 12 54 02 pm](https://cloud.githubusercontent.com/assets/1178390/24969551/277a6e04-1f7f-11e7-8965-801268b02063.png)

**Comment by amprokop** [comment]
@shellicious — just thought of something. after the button is disabled, what should trigger re-validation? Should it happen on any change to any field?

**Comment by shellicious** [comment]
@amprokop it should be enabled when all of the required fields are filled out (and if they are text fields, they should be filled with text, not just blank spaces). If a user fills them out and them clears them again such that not all of them are filled out, ideally the "Continue" button would be disabled again.

**Comment by amprokop** [comment]
ok, that's a good common pattern for user-friendly validation. sounds good. @shellicious i updated the ticket to make this so, can you give it a once-over to make sure our expectations are aligned?

@sharonwarner, is this clear enough?

**Comment by shellicious** [comment]
sgtm!

**Comment by kierachell** [comment]
## Confirm Case Details

- Able to proceed with whitespace input
<img width="1033" alt="screen shot 2017-04-27 at 7 21 15 am" src="https://cloud.githubusercontent.com/assets/18075411/25481209/204c1622-2b1a-11e7-8f11-6582da6491e1.png">

## Sign and Certify

- Able to proceed with an invalid date (00/00/000)
- Able to proceed with whitespace input for text fields
<img width="1045" alt="screen shot 2017-04-27 at 7 23 23 am" src="https://cloud.githubusercontent.com/assets/18075411/25481288/7ae9d2e0-2b1a-11e7-9467-ce1930b6cad4.png">
<img width="1160" alt="screen shot 2017-04-27 at 7 25 35 am" src="https://cloud.githubusercontent.com/assets/18075411/25481352/b96c9ff2-2b1a-11e7-90d0-12a6e5548aa9.png">

**Comment by amprokop** [comment]
Yeah we should definitely do that @kierachell. We should be able to just add a class to each of them on rendering the React component that will do it.

**Comment by sharonwarner** [comment]
This card is on hold until we confirm what we want the validation to look like. Here's some code in the meantime: https://github.com/department-of-veterans-affairs/caseflow/tree/sharon-whitespace

**Comment by kierachell** [comment]
## It was all going great...
<img width="472" alt="screen shot 2017-05-17 at 11 09 56 am" src="https://cloud.githubusercontent.com/assets/18075411/26161301/8dedd6e8-3af1-11e7-8865-03047c9ac2e0.png">
<img width="605" alt="screen shot 2017-05-17 at 11 10 00 am" src="https://cloud.githubusercontent.com/assets/18075411/26161300/8debf832-3af1-11e7-9764-d88eb3d5b25b.png">
<img width="546" alt="screen shot 2017-05-17 at 11 10 13 am" src="https://cloud.githubusercontent.com/assets/18075411/26161302/8e3c46e8-3af1-11e7-8d39-1da6957a5a2a.png">

## Until this happened
![jumpfields](https://cloud.githubusercontent.com/assets/18075411/26161299/8dbe0f9e-3af1-11e7-8688-78cb9229f00d.gif)

**Comment by shellicious** [comment]
@kierachell @sharonwarner copy nit:

Instead of the error message "Please select a Form or statement", let's use the copy "Please select one of the options below." Sorry there wasn't guidance on this front before!

Should I open a new issue for the copy change?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome 

Steps to Validate:
1. Access Certification V2
2. Enter in out of the ordinary data into the required field forms to prompt error messages and then go back to correct them with data that fits the requirements but till isn't correct. 
3. Validate behavior against that for the AC

Screenshots: 
![fieldscertification](https://cloud.githubusercontent.com/assets/23038505/26251802/74d90664-3c7c-11e7-9315-40d5ea4223eb.gif)
