### ISSUE TITLE
Assigned by Field for JudgeDecisionReview Task on AMA Cases Displaying as Assigned VLJ

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14842]
## User or job story
User story: As a VLJ, I need to see the attorney name in the "Assigned By" field, so that I know who assigned me the task

## Acceptance criteria
- [ ] Attorney that completed the attorney task displays in the "Assigned By" field in the Currently Active Tasks area for JudgeDecisionReview Tasks 

## Image of current issue
<img width="1121" alt="Screen Shot 2020-07-20 at 2 22 44 PM" src="https://user-images.githubusercontent.com/59883609/89063656-8e75c900-d336-11ea-9441-e3d567617116.png">

### Background/context
[Slack Conversation
](https://dsva.slack.com/archives/CJL810329/p1595268710211300)

### Technical notes

[Here](https://github.com/department-of-veterans-affairs/caseflow/blob/fa38c46894a9ba9c1ec7b7488d884cb51e8a1f58/app/workflows/attorney_task_creator.rb#L17-L24) is where we create the judge decision review task when a judge completes their judge assign task to create an attorney task. Can update [this line](https://github.com/department-of-veterans-affairs/caseflow/blob/fa38c46894a9ba9c1ec7b7488d884cb51e8a1f58/app/workflows/attorney_task_creator.rb#L19) to 
```ruby
judge_assign_task.slice(:appeal, :assigned_to, :parent).merge(assigned_by: task_params[:assigned_to])
```

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | ||||||||||
3 | |
5 | 
8 | 
```

Could do this before the task comes off on hold when the attorney task is completed.



#### Why 1?
* ~~One line change to the assigner upon creating the judge review task~~

#### Why 2?
* ~~Updating the assigner if the attorney task is reassigned~~
* When an attorney task is completed, update 'assigned by' on the parent judge decision review
* tests?

**Comment by hschallhorn** [comment]
Possibly want to do both
1. Change the assigner at creation of the judge review task
AND
1. Update the assigner when attorney task is completed

**Comment by ajspotts** [comment]
After [conferring](https://dsva.slack.com/archives/CQCUMFA0H/p1601650797068800) it was determined that changing the assigner at the creation of the JDRT was not necessary at this time as 1. judges do not currently have an on hold tab and 2. it could be confusing to users that they would have a JDRT assigned by an attorney who has not yet completed the attorney task.  That said we'll only update the assigner when the attorney task is completed for now.
