### ISSUE TITLE
Add methods to retrieve BGS diagnostic code descriptions

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#14877]
Blocked by #14870 

We need to add a few methods to [`ExternalApi::BGSService`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/bgs_service.rb) in order to interact with the new diagnostic codes descriptions [endpoint](https://github.com/department-of-veterans-affairs/ruby-bgs/blob/5b7bedc99caaca3a79cff8b159eb48db0b2ec669/lib/bgs/services/share_standard_data.rb#L11).

The first method will be very similar to [this](https://github.com/department-of-veterans-affairs/caseflow/blob/26ca05d955a0763c3cdbfde0fbae8e51ed20f1a9/app/services/external_api/bgs_service.rb#L218) preexisting method with a name like `fetch_diagnostic_codes`.  The referenced method connects to its desired endpoint by identifying `client`, and then the `service_name` attribute of it's class (for this endpoint it will be `share_standard_data`) and finally the method for the particular data set it is attempting to retrieve (this will be `find_diagnostic_codes`).  The end result being `client.share_standard_data.find_diagnostic_codes`

The second method we should write will be similar to [this](https://github.com/department-of-veterans-affairs/caseflow/blob/26ca05d955a0763c3cdbfde0fbae8e51ed20f1a9/app/services/external_api/bgs_service.rb#L214) one and will memoize the result so that we are not making the external API call every time the diagnostic code descriptions are requested.

We should probably also add some fake descriptions to [`Fakes::BGSService`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/fakes/bgs_service.rb).  

## Acceptance criteria
- [ ] Write a method in `ExternalApi::BGSService` to connect to our new diagnostic codes descriptions endpoint
- [ ] Write a secondary method which will memoize the result of the call in the first method
- [ ] Add fake data to `Fakes::BGSService`

## Background/context/resources
[originating](https://github.com/department-of-veterans-affairs/caseflow/issues/10948) issue
[slack](https://dsva.slack.com/archives/C54QCEHAL/p1595355732017200) convo detailing issue discovery
[slack](https://dsva.slack.com/archives/CQCUMFA0H/p1595431749007500) convo detailing decision process

**Comment by ajspotts** [comment]
Because of unfamiliarity with this part of the code and it's interaction with BGS, a call is scheduled with Sally on 8/10 @ 3pm for 🦊 input

**Comment by hschallhorn** [comment]
Backend only changes. Frontend changes in a later ticket.
Should this split up? `ExternalAPI` changes in one, uses of it, another?
Booting to wait for fallout from call on the tenth.

**Comment by hschallhorn** [comment]
Manually pulling diagnostic codes from bgs

```ruby
forward_proxy_url = FeatureToggle.enabled?(:bgs_forward_proxy) ? ENV["RUBY_BGS_PROXY_BASE_URL"] : nil
current_user = User.system_user
client = BGS::Services.new(
  env: Rails.application.config.bgs_environment,
  application: "CASEFLOW",
  client_ip: ENV.fetch("USER_IP_ADDRESS", Rails.application.secrets.user_ip_address),
  client_station_id: current_user.station_id,
  client_username: current_user.css_id,
  ssl_cert_key_file: ENV["BGS_KEY_LOCATION"],
  ssl_cert_file: ENV["BGS_CERT_LOCATION"],
  ssl_ca_cert: ENV["BGS_CA_CERT_LOCATION"],
  forward_proxy_url: forward_proxy_url,
  jumpbox_url: ENV["RUBY_BGS_JUMPBOX_URL"],
  log: true
)

response = client.share_standard_data.find_diagnostic_codes
bgs_codes = response[:return][:types]
bgs_codes.count
=> 1067

new_codes = bgs_codes.reject { |bgs_code| Constants::DIAGNOSTIC_CODE_DESCRIPTIONS.keys.include? bgs_code[:code] }
new_codes.count
=> 260

hashed_new_codes = new_codes.map { |code| [code[:code], [["staff_description", code[:name]], ["status_description", code[:name]]].to_h] }.to_h
puts Constants::DIAGNOSTIC_CODE_DESCRIPTIONS.merge(hashed_new_codes).sort_by(&:first).to_h.to_json
## C/P into DIAGNOSTIC_CODE_DESCRIPTIONS.json
```

**Comment by GabbyTISTA** [comment]
Moved to: https://vajira.max.gov/browse/CASEFLOW-1620
