### ISSUE TITLE
Add ruby-bgs endpoint to receive diagnostic code descriptions

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#14870]
## Description
We need to add a new endpoint for our [ruby-bgs](https://github.com/department-of-veterans-affairs/ruby-bgs) gem to be able to receive the descriptions for diagnostic codes.  This involves creating a new BGS module in the ruby-bgs services [directory](https://github.com/department-of-veterans-affairs/ruby-bgs/tree/master/lib/bgs/services).  Within this new module, we will need to reference the [ShareStandardDataServiceInputOutput](https://github.com/department-of-veterans-affairs/appeals-team/tree/master/Project%20Folders/Caseflow%20Projects/Intake/BGS-VBMS/BGS-API-Docs) in order to utilize it's method for diagnostic code retrieval, which is `findDiagnosticCodes`.

## Acceptance criteria
- [ ] Add a new endpoint in ruby-bgs to receive diagnostic code descriptions

## Background/context/resources
[originating](https://github.com/department-of-veterans-affairs/caseflow/issues/10948) issue
[slack](https://dsva.slack.com/archives/C54QCEHAL/p1595355732017200) convo detailing issue discovery
[slack](https://dsva.slack.com/archives/CQCUMFA0H/p1595431749007500) convo detailing decision process

**Comment by hschallhorn** [comment]
Will be closed in #14900

**Comment by ajspotts** [comment]
Closed with completion of #14900

**Comment by ajspotts** [comment]
The [endpoint](https://github.com/department-of-veterans-affairs/ruby-bgs/pull/104/commits/5fc8e6d35dde0a8bba28c3aef5ecf0b46b334ad2) (and [gem](https://github.com/department-of-veterans-affairs/caseflow/pull/14949/)) were subsequently updated to remove the `file_number` argument so that it can be ran as a job
