### ISSUE TITLE
Create new diagnostic code table & model

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#14871]
Blocked by #14877

## Description
During the investigation of #10948 it was discovered that users are able to enter new diagnostic codes into VACOLS.  We currently store all of our diagnostic codes in this giant JSON [object](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json) which we do not dynamically update based on new codes we receive. We pull these codes from BGS [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/rating_decision.rb#L43) and [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/rating_issue.rb#L44) however we currently have no recourse in our code to deal with these new codes when we receive them.  It seems the best route to take is to move the location of these codes to the backend by creating a new table and model so that we can properly add new codes when we receive them. 

## Acceptance criteria
- [ ] Create new table for diagnostic codes
- [ ] Create new model ([here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/bgs_attorney.rb) is an example of a model similar to what we want to do along with the [test](https://github.com/department-of-veterans-affairs/caseflow/pull/14511/files) written for it)
- [ ] Migrate the codes to our new table from the FE 

## Background/context/resources
[originating](https://github.com/department-of-veterans-affairs/caseflow/issues/10948) issue
[slack](https://dsva.slack.com/archives/C54QCEHAL/p1595355732017200) convo detailing issue discovery
[slack](https://dsva.slack.com/archives/CQCUMFA0H/p1595431749007500) convo detailing decision process

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

There will be other code/ticket(s) to update the table with new and/or updated diagnostic codes and descriptions.
How to create seed data for dev and test envs?

#### Why 1?
* 

#### Why 2?
* Straightforward data table with no relations to others. 
* Model probably only has fewer than a handful of functions, easy to test
  - grabbing description from code
  - Hash to return to the front end with list of all

#### Why 3?
* How to deal with dev data and tests? Will we need to populate a diagnostic code entry for every issue we create in dev to have the description available?
* Update associated factories? `issue` - are those factories or generators?

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1622
