### ISSUE TITLE
VA.gov virtual hearing opt-in

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14881]
## Background
Coordinators at the board are currently calling and emailing Veterans to convert them to virtual. That has been manageable over the past few months for the ~1,500 already scheduled video and Central Office hearings from the end of FY20. Now the Board needs to scale up to contacting more than 70,000 Veterans in Q2 FY21 (Jan-Mar 2021). 

This method is not only inefficient, but it also requires a lot of handholding by coordinators to confirm that the Veteran has the technical requirements in place to participate in a virtual hearing.

## Goals
- Allow Veterans to opt-in to virtual hearings from VA.gov with a form that would convert their hearing to virtual in Caseflow
- Incorporate VA Video Connect testing into the flow to ensure that Veterans opting in to virtual hearings are prepared to participate in those hearings

## Success metrics
- 40%+ conversion rate to virtual hearings through VA.gov among Veterans contacted
- <20% of no shows, cancelations, and postponements for virtual hearings that opted in from VA.gov

## Open questions
- How would we model the request in Caseflow?
- Is there a team that has the capacity to do the front-end work on VA.gov?
- How do we address new appeals vs. existing appeals?
- When are Veterans allowed to opt in? What if their hearing has already been scheduled at an RO? What if it's the day before the hearing?
- How will Veterans be informed? Via letter? Email?

## Other resources
- Lighthouse product brief: https://community.max.gov/display/VAExternal/Virtual+Hearing+Opt-in+-+Initiative+Brief

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-51
