### ISSUE TITLE
"Continue" button should not appear on the initial page if the appeal is not ready for certification

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1488]
Currently, the user can continue through the certification flow even if the appeal cannot be certified. We should hide the continue button if the appeal is not ready to be certified.

# Acceptance criteria 

- The user should be able to continue to the Confirm Case Details page after navigating to a certification that is ready to start.

- The user should not be able to continue to the Confirm Case Details page if navigating to a certification that is not ready to start.

# References

See https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/TestCaseflowData.md for a list of links to certifications in various states for testing.

**Comment by amprokop** [comment]
@aroltsch — check with @nemodjuric before you start this.

**Comment by astewarttistatech** [comment]
@amprokop or @shellicious  if there are any mocks for this, it would be good to add them to the References sections. As a possible solution, after testing is complete, screenshots that are taken for validation can get looked over and placed in Acceptance Criteria in lieu of mocks.

**Comment by kierachell** [comment]
**PASSED**
it's gone!

<img width="1024" alt="screen shot 2017-04-18 at 4 48 13 pm" src="https://cloud.githubusercontent.com/assets/18075411/25153279/085fbcb0-245a-11e7-85fa-7547dc199d0a.png">
<img width="1074" alt="screen shot 2017-04-18 at 4 48 18 pm" src="https://cloud.githubusercontent.com/assets/18075411/25153278/085eed30-245a-11e7-9082-a9bc85fd7894.png">
