### ISSUE TITLE
[V2 polish] Center align single icon in document table

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1489]
## Current View
![screen shot 2017-04-07 at 1 54 51 pm](https://cloud.githubusercontent.com/assets/1178390/24812873/d3332fc2-1b99-11e7-8b2f-0072c3f45cac.png)

The red x or green check mark in the above table should be center aligned with the table heading above it.

## Expected
They should be aligned like this instead:
<img width="310" alt="screen shot 2017-04-19 at 9 29 46 am" src="https://cloud.githubusercontent.com/assets/18075411/25199186/f1eb0e1c-2517-11e7-85f9-9ebfd86ce814.png">
<img width="306" alt="screen shot 2017-04-19 at 9 30 23 am" src="https://cloud.githubusercontent.com/assets/18075411/25199187/f1eb11be-2517-11e7-9f27-108185f1847c.png">

# Acceptance Criteria
The red x or green check mark in the above table should be center aligned with the table heading above it.

**Comment by astewarttistatech** [comment]
Should there be a mock for the red X's?

**Comment by shellicious** [comment]
@astewarttistatech they should be displayed in the exact same way as the green checkmarks, so I don't believe it's necessary. There could also be combinations of red x's and green checkmarks, which I also don't think are necessary to mock up.

**Comment by kierachell** [comment]
@shellicious currently the column is so wide that the easiest solution is to center the whole thing
<img width="963" alt="screen shot 2017-04-17 at 9 43 07 pm" src="https://cloud.githubusercontent.com/assets/18075411/25111096/edf206b0-23b6-11e7-859b-3dac280f8dbb.png">
<img width="936" alt="screen shot 2017-04-17 at 9 43 12 pm" src="https://cloud.githubusercontent.com/assets/18075411/25111097/edf53682-23b6-11e7-936f-77127169fbe6.png">

Vs wonky solution via adding padding
<img width="916" alt="screen shot 2017-04-17 at 10 01 05 pm" src="https://cloud.githubusercontent.com/assets/18075411/25111517/655a8a22-23b9-11e7-912d-fde5a79864c4.png">

**Comment by kierachell** [comment]
<img width="880" alt="screen shot 2017-04-19 at 3 48 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/25199138/c39a5c16-2517-11e7-855d-030727604d61.png">
<img width="1027" alt="screen shot 2017-04-19 at 3 49 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/25199164/d98f73c6-2517-11e7-9408-2e68baf7b8c6.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod
Browser: Chrome and FF

Steps to Validate: 
1. In Certification V2, visit the check documents page for a veteran who has all required documents and visit the check documents page for a veteran who has none of the required documents to certify an appeal. 
2. Verify that the Found in VBMS column has centered X's or check marks. 

Screenshots: 
See above
