### ISSUE TITLE
Remove Schedule Hearing Task Modal

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14908]
## Description

Remove the schedule hearing task modal when the alternate non-modal view lands

## Acceptance criteria
- [ ] Confirm that the modal is no longer in use and hasn't already been removed
- [ ] Remove the schedule hearing task modal and related code

## Background/context/resources

After #14895 lands

**Comment by tomas-nava** [comment]
tagging @rubaiyat22 for connecting to a new feature toggle ticket
