### ISSUE TITLE
[V2 polish] Form 9 dates should be bold and in consistent format

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1490]
# Acceptance Criteria

The Form 9 upload dates in step 3 should be bolded and in the MM/DD/YYYY format.

## Current View

![screen shot 2017-04-07 at 2 17 28 pm](https://cloud.githubusercontent.com/assets/1178390/24813707/10d28032-1b9d-11e7-9dbe-02dfa873863a.png)

## Expected

The progress bar shown in the Current View above is correct (Confirm hearing step in the progress bar should have darkened text and a darkened section). 

![screen shot 2017-04-12 at 1 04 05 pm](https://cloud.githubusercontent.com/assets/1178390/24969949/93849b14-1f80-11e7-935c-46a14b338bae.png)

**Comment by astewarttistatech** [comment]
@shellicious Could you update the "expected" mock to not have the header bar if it is not completed/ or at its desired state. It is very confusing.

**Comment by shellicious** [comment]
@astewarttistatech updated

**Comment by nemodjuric** [comment]
@shellicious I noticed that text 'appellant's eFolder' has different coloring suggesting a link. If that is relevant to this issue, what exactly has to be done (i.e. link url)?

**Comment by shellicious** [comment]
@nemodjuric thanks for bringing that up! the link text should be a separate issue. It should link to the appellant's eFolder in VBMS< but I'm not sure it's possible.

@amprokop is it within scope of a future V2 milestone to link to the appellant's eFolder from Caseflow? Should I write a ticket and couple it with a future milestone?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: Preprod
Browser: FF and Chrome

Steps to Validate: 
1. In Certification V2, navigate to confirm hearing page
2. Verify the date is bolded, based on the AC. 

Screenshots: 
<img width="1344" alt="screen shot 2017-04-21 at 12 03 52 pm" src="https://cloud.githubusercontent.com/assets/23038505/25336866/6d79a7e8-28c7-11e7-8095-8fa3d1e649cb.png">
