### ISSUE TITLE
Reader | Expand all button

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1491]
**Story**
As a user, I want to be able to see all the details of each document (comments and issue tags) in a quick and easy way.

## Acceptance Criteria
- [x] Verify that the button is right-aligned with the table 
- [x] Verify that `Expand all` is sentence cased and in USWDS - primary
- [x] Verify that the document number is on the right of the search bar
- [x] Verify that when Expand all button is clicked, all details from each document, including issue tags and comments, are viewable
- [x] Verify that when all rows with details are expanded, the button changed to "Collapse all"
- [x] Verify that when Collapse all button is clicked, all details from each document, including issue tags and comments are collapsed and rows are back at fixed height.
- [x] Verify that the Expand all button is 45px from the column headers
- [x] Validate that all issue tags are visible under issue tag column
## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24813999/1badaada-1b9e-11e7-9b7e-30eb2c1840d0.png)

![image](https://cloud.githubusercontent.com/assets/13420618/24813922/deb6deee-1b9d-11e7-8b62-1c8edd6648d7.png)

**Comment by abbyraskin** [comment]
@gnakm how does "expand all" interact with filters? i would think ideally if a user has filtered by category or issue tag, it only expands what is showing in the filtered doc list view.

**Comment by gnakm** [comment]
@abbyraskin I agree that expand all should shows filtered view only. I think for the pilot, this will be okay but for v2 let's think about the placement and consider hierarchy.

**Comment by tejans24** [comment]
NOTE: See more button has been removed. Currently, all tags are shown in the table.

**Comment by astewarttistatech** [comment]
@tejans24 

Current Functionality: 
![readerflow](https://cloud.githubusercontent.com/assets/23038505/25619313/652f2c0a-2f18-11e7-8eb5-afbd5fce1848.gif)

**Comment by kierachell** [comment]
**PASSED**
![expandmeh](https://cloud.githubusercontent.com/assets/18075411/25643104/bc1fdda4-2f6b-11e7-894b-d9a73bbd9b7a.gif)
