### ISSUE TITLE
Account for out-of-order task assignments in ColocatedTaskDistributor

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14914]
## Description
As described in https://github.com/department-of-veterans-affairs/caseflow/issues/14629#issuecomment-670591117, 2 factors cause the ColocatedTaskDistributor to not evenly distribute tasks to the Colocated Team. The factors occur when assigning a new child user-task:
1. If there exists an open task on the same appeal assigned to a user in the assignee_pool, then the distributor assigns the new task to that user (this is desired "add-on" behavior)
2. End-user manually reassigned a (Colocated) task to user in the assignee_pool. Reassigning a task cancels the task and creates a new task assigned to the new user.

The assignment of the new task cause the `latest_task` to change, which causes `last_assignee` to jump/skip from the expected round-robin ordering. 

This ticket should resolve #14084.

## Acceptance criteria
- [ ] ColocatedTaskDistributor assigns tasks evenly across `assignee_pool`, despite other desired "add-on" behaviors and manual task reassignments
- [ ] Update documentation: 
  * https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Task-Distribution
  * https://github.com/department-of-veterans-affairs/caseflow/wiki/VLJ-Support#co-located-auto-case-distribution

## Background/context/resources
See the linked comment above.

## Technical notes
See [investigation notes](https://hackmd.io/0ekslnh7RAaoimlXVcDzGQ?both), esp. `closed_count`, `prior_task`, and `match`. 

Rough outline for a fix: 2 stages:  
1.  ignore the 2 root cause situations when calculating `latest_task` (the new method will be named something like `last_round_robin_assigned_task`)
2.  Using the latest 16 (or `Colocated.singleton.non_admins.count`) round-robin-assigned tasks, check that they are sequential -- they should be unless another root cause pops up. If not sequential, then extrapolate a trend line (that smooths out any outliers/jumps/skips) to determine the next appropriate assignee.

Another option is to consider the parent org-task in determining the `next_assignee`. This would address factor #2 (task reassignment).

See https://github.com/department-of-veterans-affairs/caseflow/pull/14897/files#r467182294 for hints to update tests.

**Comment by hschallhorn** [comment]
Closing in favor of #14952

**Comment by hschallhorn** [comment]
Great great finds though. Really good information here and will help diagnose any issues we have with other task distributors.
