### ISSUE TITLE
Write plan and setup data in UAT for 2nd dogfooding/end-to-end testing for Central-to-Virtual and Video-to-Virtual workflow

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14917]
## Description

Write a testing plan and setup data in UAT for the 2nd dogfooding/end-to-end testing session for the central-to-virtual and the new full-page video-to-virtual workflows.

## Acceptance criteria
- [ ] Data exists in UAT for dogfooding
- [ ] A testing plan document is prepared

## Background/context/resources

The session is currently scheduled for Friday, August 14th.

**Comment by rubaiyat22** [comment]
[Central to Virtual testing plan](https://hackmd.io/eU-DMyhYSmiZ4JG9vAPiow)
[Full page Video to Virtual](https://hackmd.io/5hNK2ib5Shiag66HQLCGCA)
