### ISSUE TITLE
Remove diagnostic code validation

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#14915]
## Description
The sentry error alert brought to light in #10948 was determined to be caused by the fact that we were receiving diagnostic codes that were not stored in our code.  The overall effort to correct this problem is being addressed in several different issues: #14870, #14871, #14872 & #14877.   However, since we have determined that this error will prevent judges/attorneys from completing reviews we have decided to remove the validation to remove the blockage.

## Acceptance criteria
- [ ] Remove [the validation](https://github.com/department-of-veterans-affairs/caseflow/blob/788ab1dd58a43cdd1055d86250e3892ffdbbb111/app/models/decision_issue.rb#L12-L13) that causes [the error](https://github.com/department-of-veterans-affairs/caseflow/blob/993fb3c00ab2ce06bfbdfef1cdb5a3ae4b4fe7b4/app/models/concerns/issue_updater.rb#L15)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||
2 | |||
3 | 
5 | 
8 | 
```

#### Why 1?
* Pull one line

#### Why 2?
* Any tests that need updating?
* pure distrust
