### ISSUE TITLE
OIT Metrics Request: # of Vets served in FY 2020

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#14916]
OIT is requesting metrics for the number of Veterans served through the following Caseflow products thus far in this fiscal year (10/1/19-now) by 8/12/20.

- Appeals Status (# of Veterans who checked their appeals status)
- Caseflow Hearings (# of Veterans scheduled through Caseflow Hearings)

**Comment by yoomlam** [comment]
1. How do Veterans check their appeals status? Is this within the scope of Caseflow since Veterans don't log into Caseflow?

2. How should "# of Veterans scheduled" be counted? 
   - Is it sufficient to sum the number of hearings on each `HearingDay`?
   - How should hearings that are scheduled and then postponed and rescheduled be counted? 
   - Should hearings that are scheduled but then cancelled count?

**Comment by alisan16** [comment]
1. Caseflow provides the Appeals Status API and tracks hits to the API in the api_views table (check out api_keys to find the VA.gov Appeals Status consumer api_key_id). Alternatively, we could try to ask VA.gov for this info directly, if they're tracking anything on their side. You can try #vfs-analytics as a first step.
2. OIT just needs rough estimates so you don't have to be so exact. I'm less familiar with the Hearings tables so you can try asking in #appeals-tango. Providing **the number of Veterans who were scheduled for a hearing through Caseflow** during that timeframe is sufficient, regardless of whether the hearing was actually held. Number of Veterans may be different from number of hearings scheduled, since multiple hearings may have been scheduled for Veterans in the case of cancellation/postponement.

**Comment by yoomlam** [comment]
For fiscal year to date, 2592 Veterans were scheduled for a hearing through Caseflow.
```ruby
span=(Date.new(2019,10,1)..Date.today)
hds=HearingDay.where(scheduled_for: span);
hds.count
=> 2445
hs=Hearing.where(hearing_day: hds);
hs.count
=> 3378
vs=hs.map{|h| h.appeal.veteran}.uniq
vs.count
=> 2592
```

#### Trial run (prior to getting actual stats)
```ruby
span=(Date.new(2020,7,1)..Date.new(2020,7,7))
hds=HearingDay.where(scheduled_for: span);
hds.count
# => 34
hs=Hearing.where(hearing_day: hds);
hs.count
# => 55
vs=hs.map{|h| h.appeal.veteran}.uniq
vs.count
=> 50

# Double-check: who has multiple hearings?
vss.group_by{|v| v.id}.map{|k,v| [k,v.size]}.select{|a| a.second>1}.to_h
=> {4267=>3, 240386=>3, 276014=>2}
vhs=hs.map{|h| [h.appeal.veteran.id, h]}.group_by{|a| a.first}

vhs[4267].map{|v,h| [h,h.hearing_day]}
# Hearings 4189 and 4251 look the same
h1=Hearing.find(4189);
h2=Hearing.find(4251);
h1.scheduled_time==h2.scheduled_time && h1.hearing_day==h2.hearing_day
=> true
# So there are duplicate hearings scheduled at the same time
```

**Comment by yoomlam** [comment]
Not obvious which [ApiKey](https://query.prod.appeals.va.gov/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjg5fX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) is relevant.
```ruby
ApiKey.pluck(:consumer_name)
=> ["Vets.gov", "Appeals Lambda", "QA", "Chris Given", "VETText", "peter karman test", "Premal Vettext"]
```
Well, the last 1M views are associated only with "Vets.gov", so that narrows it down:
```ruby
ApiView.last(1000000).pluck(:api_key_id).uniq
=> [1]
ApiView.last(1000000).first.created_at
=> Tue, 28 Jul 2020 12:46:34 UTC +00:00
# 1M "views" since Jul 28th

ApiView.first.created_at
=> Wed, 07 Feb 2018 15:44:03 UTC +00:00
ApiView.last.id
=> 45869309
# 45.8M views since Feb 2018
```

There is no index on any of the fields, so querying is not practical:
```ruby
ApiView.count
# times out
span=(Date.new(2020,7,1)..Date.new(2020,7,7))
ApiView.where(created_at:span).count
# times out
```

The `ApiViews` table shows Veteran identifiers, but it doesn't distinguish if a Veteran (as opposed to a tool) is querying or if the query is about an appeal's status, so this table may not be useful.

Sent [a message in #vfs-analytics](https://dsva.slack.com/archives/C1Q4294JJ/p1597070706317700).

**Comment by alisan16** [comment]
Vets.gov is the correct API key. The only Vets.gov (older name for VA.gov) API Caseflow provides currently is the appeals status API, which is only accessed when Veterans check their appeal status on VA.gov. I don't know how many times VA.gov hits the appeals status API when a single Veteran checks their status, though, there are probably duplicates in that 1M number since July 28. The lighthouse project is creating another API, but that's not live in production yet and they should be creating a separate API key.

**Comment by yoomlam** [comment]
Oct 1, 2019 records start at record id 23,089,325.
```ruby
ApiView.find(23089324).created_at
=> Mon, 30 Sep 2019 23:59:59 UTC +00:00
ApiView.find(23089325).created_at
=> Tue, 01 Oct 2019 00:00:00 UTC +00:00
```
Adjusting for Eastern time zone (-4 hrs), find the first record that was created at 01 Oct 2019 04:00:00 UTC, which is record id 23,104,903:
```ruby
ApiView.find(23104902).created_at
=> Tue, 01 Oct 2019 03:59:57 UTC +00:00
ApiView.find(23104903).created_at
=> Tue, 01 Oct 2019 04:00:01 UTC +00:00

ApiView.find(23114903).created_at
=> Tue, 01 Oct 2019 11:08:27 UTC +00:00
ApiView.where(id: [23104903..23114903]).select(:vbms_id).distinct.count
=> 4890
```
Curious that there were 15,578 records created (Veteran views) in 4 hours starting at Sep 30 8pm ET; and 10k records created in about 7hrs starting at Oct 1st midnight (for 4890 unique Veterans).

2442 distinct Veterans between midnight and 3am on Oct 1 ET.
```ruby
ApiView.find(23109903).created_at
=> Tue, 01 Oct 2019 07:04:36 UTC +00:00
ApiView.where(id: [23104903..23109903]).select(:vbms_id).distinct.count
=> 2442
```

**Comment by alisan16** [comment]
Thanks @tomas-nava for double checking the Hearings numbers, legacy hearings actually need to be queried for separately. I just ran the following this morning and will be reporting `38067 Veterans` served by Caseflow Hearings so far this year

```ruby
span=(Date.new(2019,10,1)..Date.today)
hds=HearingDay.where(scheduled_for: span);
hds.count
=> 2472

# AMA hearings
hs=Hearing.where(hearing_day: hds);
hs.count
=> 3426
vs=hs.map{|h| h.appeal.veteran}.uniq
vs.count
=> 2620

# legacy hearings
lhs=LegacyHearing.where(hearing_day_id: hds.map(&:id))
lhs.count
=> 42429
lvs=lhs.map{|lh| lh.appeal.veteran}.uniq
lvs.count
=> 35447

vs.count + lvs.count
=> 38067
```

**Comment by alisan16** [comment]
Also checking Caseflow Intake numbers for Veterans served thus far:
SQL query
```sql
SELECT count(distinct "public"."intakes"."veteran_file_number") AS "count"
FROM "public"."intakes"
WHERE ("public"."intakes"."created_at" >= timestamp with time zone '2019-10-01 00:00:00.000-04:00'
   AND "public"."intakes"."completion_status" = 'success')
```
=> 308,350

|Type                   |Distinct values of Veteran File Number|
|-----------------------|--------------------------------------|
|AppealIntake           |40641                                 |
|HigherLevelReviewIntake|72447                                 |
|RampElectionIntake     |269                                   |
|RampRefilingIntake     |14                                    |
|SupplementalClaimIntake|232028                                |

**Comment by alisan16** [comment]
Appeals Status views: https://dsva.slack.com/archives/C1Q4294JJ/p1597252808328400?thread_ts=1597070706.317700&cid=C1Q4294JJ

866,962 from 10/1/2019 - 8/11/2020

**Comment by alisan16** [comment]
OIT has requested these numbers again. For Appeals Status API, the previous number as of 8/11/2020 was 866,962. From 8/12/2020 - 9/30/2020, Google Analytics is saying 181,364 users accessed the track-claims/appeals. Adding the 2 reports below. This means that for FY20 (10/1/2019 - 9/30/2020) the total number of Veterans who checked their appeals status was 1,048,326

[data.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/5712927/data.pdf)
[data (1).pdf](https://github.com/department-of-veterans-affairs/caseflow/files/5712931/data.1.pdf)

**Comment by alisan16** [comment]
Using the Metabase dashboard for the other numbers. Thanks for setting that up @yoomlam, it was super easy to pull the numbers!

Vets served by Hearings in FY20: 40,310
Vets served by Intake in FY20: 388,296
