### ISSUE TITLE
Legacy appeals VACOLS locations may be changed incorrectly when user requests a hearing disposition change

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#14911]
## Description
As part of the actions we take when a user requests a hearing disposition change off of a ScheduleHearingTask, we [cancel the ScheduleHearingTask and its children](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L70-L71). If those tasks were the only children of the parent HearingTask, that HearingTask will close, [triggering a location change](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/hearing_task.rb#L43) on `when_child_task_completed`. Then the request hearing disposition change process continues, [creating additional hearing tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L79-L82).

There is [a guard clause](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/hearing_task.rb#L40) on the location change that checks for existing hearing tasks, but it is bypassed because, at that moment, we haven't created the new tasks yet.

This leaves the appeal in an incorrect state, in a non-`CASEFLOW` VACOLS location but with open tasks in Caseflow.

## Acceptance criteria

- [ ] Refactor this flow so that the appeal's VACOLS location isn't changed from `CASEFLOW` if we intend to add new open tasks.
- [ ] Find all appeals in Caseflow that are in this incorrect state and correct their locations in VACOLS.

## Technical notes

Notice that we cancel the ScheduleHearingTask's parent HearingTask three times: [once](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L70-L71) when we cancel all its children, [a second time](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L72-L75) directly, and [a third time](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L78) when we create the replacement HearingTask with `cancel_and_recreate`.

## Background/context/resources

There's a history of how this bug was found, and a link to a HackMD with a more detailed investigation of a single case in [this Slack message](https://dsva.slack.com/archives/C3EAF3Q15/p1596585686024700?thread_ts=1596572987.022700&cid=C3EAF3Q15).

**Comment by rubaiyat22** [comment]
- [ ] Find all appeals in Caseflow that are in this incorrect state and correct their locations in VACOLS.

https://hackmd.io/5GsoIc74RXekK07ISWW6LQ?both

**Comment by rubaiyat22** [comment]
closing per completion 
>[ ] Find all appeals in Caseflow that are in this incorrect state and correct their locations in VACOLS.
