### ISSUE TITLE
Add frontend code coverage for React

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1492]
Similar to how we use simple cov to verify code test coverage in ruby, we need to add a similar tool for our frontend infrastructure. 

Acceptance Criteria:
- Add Istanbul JS code coverage library
- Force some % of code coverage for all our Redux reducers & actions across all apps
- Consider adding code coverage to our /components directory too

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
