### ISSUE TITLE
Backfill data - missing dispositions with matching rating issue

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14936]
## Description
Prior to this ticket:
- A report has been created for request issues missing a disposition, but with a matching rating issue
- The desired disposition has been determined from data in the script, and edge cases have been flagged

This ticket is to write a script and to start processing these.

## Acceptance criteria
- [ ] Develop a script for processing these, include it in the [HackMD file](https://hackmd.io/Kl7jklf5T8io8lRCkVi-9g)
  - [x] The script should take the request issue ID and disposition as inputs
  - [x] The script should include safeguards to prevent processing if this is an edge case that was flagged
  - [ ] The script should also create remand supplemental claims on a review when appropriate
- [ ] Mark processed cases in the [spreadsheet]([Populate missing disposition when rating issue matches](https://docs.google.com/spreadsheets/d/1FKidiVEswz1nh9i9sjXKaEtBk60o4iSwriupW2ywZQg/edit#gid=0))

## Background/context/resources
Related: #14934, #14935

## Technical notes
For developing a script, see: `RequestIssue.sync_decision_issues!` to get a sense of what happens when syncing the decision issues, particularly the step where `create_decision_issues_from_rating` and `find_or_create_decision_issue_from_rating_issue` are happening.

**Comment by wdrougas-tista** [comment]
@leikkisa I think I need some clarification on providing the disposition as an input for this script. If we are pulling the disposition from the decision text of the `matching_rating_issue`, there will be some conditional logic to set the disposition and would we not be doing that within the script?

**Comment by wdrougas-tista** [comment]
Backfilled all decision issues that have been granted permission from OAR. Spreadsheet includes 5,324 request issues, have backfilled 4,049 of them. 1,231 are now showing no matching request issue, 34 need approval from VBMS, 10 have a matching rating issue that needs to be split.
