### ISSUE TITLE
Automatically Create & Send Child IHP Task to IHP writing POA

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14940]
## User or job story
Job story: When an attorney or VLJ user creates an admin action for an IHP task, the IhpColocated task should create child task for the POA on the case, so that the VLJ support task (parent task) is not worked until the POA task is completed. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: ihp_notification
- [ ] If there is exactly one POA on the case that should write an IHP for that appeal
  - [ ] An IHPColocated task is created for the VLJ Support team
  - [ ] A child IHP task is created for the IHP writing POA assigned to the case 
  - [ ] VLJ Support IHP task is placed on hold until the child POA IHP task is completed (should be done automatically by the creation of the child task)
- [ ] If there is more than one IHP writing POA on the case, do not automatically create child task
- [ ] If there no IHP writing POAs on the case, do not automatically create child task

## Release notes
IHP requests are now routed directly to the IHP writing VSO on the case. 

### Background/context

Currently, only one IHP task is created for the VLJ support team and a manual process outside of Caseflow has to occur to send the request to the IHP writing VSO. This process should eliminate the VLJ Support teams need for the manual process. 

### Technical notes

[Here is how we check reps on an appeal and if they should write IHPs](https://github.com/department-of-veterans-affairs/caseflow/blob/e82803c2cdb863b53ece9796ab1a2585739d1e5b/app/models/tasks/track_veteran_task.rb#L44-L56)

### Resources/other links
<img width="924" alt="Screen Shot 2020-08-18 at 9 14 46 AM" src="https://user-images.githubusercontent.com/65979678/90538389-55f62d80-e133-11ea-89a2-84074b1a8cc5.png">

**Comment by yoomlam** [comment]
When no POA, "Route IHP Requests w/no POA that writes IHPs to VLJ Support" #14976.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||||||||
3 | |||
5 | 
8 | 
```

See other colocated tasks for child tasks we create upon creation! (MissingHearingTranscriptsColocatedTask, FoiaColocatedTask, etc)

#### Why 1?
* Simple `after_create` callback with check for only one ihp writing rep

#### Why 2?
* Testing?

#### Why 3?
* Haven't done it before
* New tests
