### ISSUE TITLE
Attorney Fees | Make the relationship field drop-down active (not greyed-out)

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#14948]
## Description
This ticket is a result of dogfooding and comes from the [dogfooding bugs](https://docs.google.com/document/d/1InfCVKc2z46cXn_10FSceCIG87d13hUZZHk1CWb1REQ/edit) document.

For the "Claimant's relationship to the Veteran" field drop-down, do not make the drop-down disabled (grayed-out). Instead, a user should be able to click the drop-down if they'd like, but the only option they should see and be able to select is "Attorney (previously or currently)".

## Acceptance criteria
- [ ] "Claimant's relationship to the Veteran" field is not grayed-out
- [ ] The drop-down result defaults to "Attorney (previously or currently)"
- [ ] A user can open the drop-down, but the only option they see is ""Attorney (previously or currently)"

## Notes
This drop-down will change in the near future based on Non-Veteran Claimant functionality.

**Comment by nanotone** [comment]
@rutvigupta-design I opened PR #14962; cross-posting the screenshots here for visibility:

- Before this change:
<img width="462" src="https://user-images.githubusercontent.com/282869/90157161-5ff6e580-dd5b-11ea-955a-0ce0c19ef6cc.png">

- After this change:
<img width="459" src="https://user-images.githubusercontent.com/282869/90157192-6dac6b00-dd5b-11ea-964d-8e4a9460568d.png">

- Verifying that there is only one option (Claimant name menu is visible at bottom):
<img width="460" src="https://user-images.githubusercontent.com/282869/90157381-aa786200-dd5b-11ea-94f4-9f49bfa68108.png">
