### ISSUE TITLE
[V2] Pre-fill form fields that we have data for on Step 2

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1495]
On Step 2: Confirm Case Details, prefill the type and name of Representative if it's available from BGS

If it's not available and the radio buttons are unchecked, or the form field for Representative is blank, the "continue" button should be disabled.

![screen shot 2017-04-07 at 3 18 37 pm](https://cloud.githubusercontent.com/assets/1178390/24816108/915be4b6-1ba5-11e7-993a-be56153e1664.png)

Acceptance criteria: 
Type and name of the representative should be filled from data in UAT BGS.

**Comment by amprokop** [comment]
Duplicate
