### ISSUE TITLE
CAVC Remand: Update Auto-Distribution Criteria for Priority AMA Cases

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14958]
## User or job story
Job story: When a Litigation Support user completes the intake of a CAVC remand the CAVC Remanded case should be auto-distributed to VLJs via the Auto-Distribution Job, so that the VLJ can work these cases before legacy hearing & general population cases.

## Acceptance criteria
- [ ] This feature should be accessible to the following user groups: VLJs
- [ ] AMA CAVC Remands in-taken by the Litigation Support are included in the auto-distribution job for priority cases
- [ ] AMA CAVC Remands in-taken by the Litigation Support are included in the requested auto-distribution for priority cases
- [ ] Pare down code reuse with a refactor if possible

### Background/context

Legacy CAVC remanded cases are already incorporated into the algorithm, this ticket is to ensure AMA CAVC remands intaken by the Litigation Support team are incorporated as well. 

Appeal Priority Order: 
CAVC AOD
AOD
CAVC

### Technical notes

Where we determine what case is priority for ama appeals distributions
https://github.com/department-of-veterans-affairs/caseflow/blob/e6279de98591de6b6a5fa7657c0769c00715b963/app/models/docket.rb#L98-L105

**Comment by araposo-tistatech** [comment]
@hschallhorn should I create duplicate tickets for this one to incorporate MDR, Reversals, & Dismissals in the future or do you think this one ticket will capture even future work?

**Comment by hschallhorn** [comment]
Good question! I think it depends on what we decide on for appeal stream type naming. If we plan on calling all "Court Remand" (as we do with legacy appeals) or something similar, then they will all be captured in this work. If we decide MDR, Reversals, & Dismissals need to have their own stream type, then we will need tickets for each.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | ||||||||
5 | |||
8 | 
```

Should update requested ACD test, priority push job test, and distribution seeds.

#### Why 2?
* Sounds pretty clear...
* Simple update to the priority scope for acd

#### Why 3?
* ...but ACD
* ACD test updates
* Seconded ^^
