### ISSUE TITLE
ApiViews - What is it good for?

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#14950]
## Description
Stemming from https://github.com/department-of-veterans-affairs/caseflow/issues/14916#issuecomment-671412988, the `ApiView`s table has 45.8M records, the earliest created was on Feb 2018. It has no index on any of the fields (except `id`), so querying is not practical. 
Investigate the use of this table and the need to create `ApiView` records. 

## Acceptance criteria
- [ ] Document its use, i.e., add comments to `schema.rb` and maybe add a wiki page if needed.
- [ ] Create a ticket to: Deprecate the table, optimize its use, or replace with another tool, such as Google Analytics.

## Background/context/resources

Based on the frequency and cadence of the created records ([notes](https://github.com/department-of-veterans-affairs/caseflow/issues/14916#issuecomment-671538062)), it's likely that some automated tool is using this API endpoint.

**Comment by yoomlam** [comment]
Assigning to Team Echo for now so that some team has eyes on it.

**Comment by lomky** [comment]
Do as a documentation task - figure out what the table is for and file a followon ticket to take any actions based on the documentation. Estimating at a 2.

**Comment by yoomlam** [comment]
```ruby
ApiView.last
=> #<ApiView:0x0000000009046600
 id: 55 934 676,
...
```

Max value for `id` is 2,147,483,647.
