### ISSUE TITLE
on the Schedule Veterans page, remove null when no hearing room is associated with a date

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#14956]
## Description

As a hearing coordinator using the schedule veterans screen, if there's no hearing room associated with a date, I should not see irrelevant information under "Available Hearing Days" and above the Assign Hearing tabs.

Currently on the schedule veterans screen, the room displays as `null` when no hearing room is associated with a date.

<img width="400" alt="null-hearing-room" src="https://user-images.githubusercontent.com/45415133/90103566-926ef700-dcf7-11ea-9d3d-b8169a1ce992.png">

## Acceptance criteria
- [ ] Show nothing instead of `null` if no room is associated with the date is displayed (`Fri 7/13/2020 (11 slots remaining)` instead of `Fri 7/13/2020 null (11 slots remaining)`)

## Open questions

- [x] what text should we use? "No room available"? Consult with @nicholer (we will use no text)

## Technical Notes
- the null value appears in `http://localhost:3000/hearings/schedule/assign`
- React component where this is rendered is [here](https://github.com/department-of-veterans-affairs/caseflow/blob/b338cbc240680e53967ce3e176398b07b1521d6b/client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx#L48)

**Comment by nicholer** [comment]
@tomas-nava Can we show nothing? So it would display as `Fri 7/13/2020 (11 slots remaining)` I think that would follow what we're doing in the sidebar showing Available Hearing Days?
