### ISSUE TITLE
[V2] Pre-fill form fields we have data for on Step 4

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1496]
On Step 4: Sign & certify, these fields should be pre-filled:
- Name and location of certifying office
- Organizational elements...
- Decision Date 

![screen shot 2017-04-07 at 3 18 26 pm](https://cloud.githubusercontent.com/assets/1178390/24816383/8602048c-1ba6-11e7-8b0b-18b042fe1f5f.png)

# Acceptance Criteria
- Certifying username should be populated from `case_record.bfregoff`
- Name of certifying office should be the regional office in VACOLS
- Date should be pre-populated with current date
- Name of certifying official and title of certifying official should not be pre-populated

### Validation Notes
in form8.rb, this is where the info currently comes from:
```
      certifying_office: appeal.regional_office_name,
      certifying_username: appeal.regional_office_key,
      certification_date: Time.zone.now.to_date,
```

In VACOLS, `regional_office_key` is stored in `case_record.bfregoff`

**Comment by amprokop** [comment]
in form8.rb, this is where the info currently comes from:
```
      certifying_office: appeal.regional_office_name,
      certifying_username: appeal.regional_office_key,
      certification_date: Time.zone.now.to_date,
```

**Comment by amprokop** [comment]
In VACOLS, `regional_office_key` is stored in `case_record.bfregoff`

**Comment by astewarttistatech** [comment]
<img width="1202" alt="screen shot 2017-04-18 at 10 51 15 am" src="https://cloud.githubusercontent.com/assets/23038505/25138926/d1278ce4-2429-11e7-9318-d4bb03b2573b.png">

**Comment by kierachell** [comment]
Matching fields from VACOLS
<img width="976" alt="screen shot 2017-04-18 at 11 44 13 am" src="https://cloud.githubusercontent.com/assets/18075411/25140013/ea4e8364-242c-11e7-9a5a-32251cc54002.png">


Validated with 3 other cases.
