### ISSUE TITLE
Add link field to Send Back to Attorney modal

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14978]
## User or job story
User story: As a VLJ Support user, I need to be able to add a link to the IHP when completing an IHP task and returning the task to the Attorney.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: IHP_Notification
- [ ] This feature should be accessible to the following user groups: VLJ Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] The send back to attorney modal includes a required field where the IHP link can be added
- [ ] A link to the IHP is visible on the Case Details page
- [ ] A link to the IHP is visible in the Case Timeline of the completed VLJ Support IHP Task

## Release notes
The Send Back to Attorney modal now includes a link field where VLJ Support can add the IHP link when completing the task and routing the task back to the attorney. 

### Designs
[Link to designs](https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=0%3A1) in Figma

**Comment by araposo-tistatech** [comment]
@RyanRoyUX @mbaenatan this one needs thoughts around the design (specifically where the link should be displayed in the case details page as I believe only including it in the Case Timeline may not be very user friendly.

**Comment by hschallhorn** [comment]
Needs to be broken out into _maybe_ 3 engineering tickets.
1. Store reader link somewhere??? (is task instructions enough?)
1. Add spot for link in task completion modal
1. Show clickable reader ihp link in case details
