### ISSUE TITLE
Visiting a case with a stale POA triggers a refresh from VBMS

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14974]
## User or job story
Job story: When a POA is accessed in caseflow that has been updated in VBMS, Caseflow needs to be updated to maintain data integrity and proper task flow.

## Acceptance criteria
- [ ] POA changes in VBMS are updated in Caseflow in a timely manner

## Release notes
Outdated POA in Caseflow are updated within a day of accessing a Caseflow record with an updated POA in VBMS.

### Background/context
We are receiving reports that there seems to be a long delay in POA updates made in VBMS and seeing the changes in Caseflow. There are times when the updates never display in Caseflow and VLJ Support has to remove the POA in VBMS and re-add it for Caseflow to pickup the change. 

### Technical notes

*2020-12-03* Another Dive from @lomky - see #15647 & [research dive](https://dsva.slack.com/archives/C01FQCP17PF/p1606853581004000?thread_ts=1606853494.003700&cid=C01FQCP17PF)
 - we cannot dump stale records en masse due to the reporting use case cited by @yoomlam below.
 - there is nothing blocking moving forward with the other suggestion, which will help alleviate one of the user frustrations that is cropping up more often.
> - Upon reading a cache record with `last_synced_at` older than a day, enqueue a low-priority Shoryuken job to do a background sync for the latest POA data. POAs are likely to be requested multiple times while a user is in the vicinity, and in the off-chance they hit a wrong stale value, this makes it probable that they only see it once.
 - I'm grabbing this ticket to implement the above, with a more aggressive stale faactor (likely an hour)

*2020-09-10* Info dump from @nanotone:

- The `bgs_power_of_attorneys` table in Caseflow DB is what we use to cache POA data from BGS. When users talk about seeing POA data in VBMS, that originates from the same BGS source.
  - This cache is a Postgres table rather than Redis because the data is substantially relational than is supported by a key-value architecture. It needs to be queryable by several columns e.g. claimant PID, file number, POA PID.
  - Records never get deleted from this cache. See this [Slack thread](https://dsva.slack.com/archives/C2ZAMLK88/p1596147165058900) and #15043 for related work.
- The [WarmBgsCachesJob](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/warm_bgs_caches_job.rb#L43) class is responsible for updating Caseflow's cache of BGS POA records.
  - However, each run only touches the 1000 most stale records -- the more records overall, the longer it'll take for any one record to get synced with BGS.
  - Because the number of records is ever-increasing, staleness will get worse over time. At time of writing there are 210k records.

It is likely prohibitively expensive to refresh every cached record nightly. I recommend a two-pronged approach:
- Update or augment the nightly job to drop all BgsPowerOfAttorney records except the 10k records with most recent `last_synced_at`. This will ensure WarmBgsCachesJob stays useful.
  - The 10k number is just a guess based on this initial [observation](https://dsva.slack.com/archives/C2ZAMLK88/p1588001768384000?thread_ts=1588001664.383600&cid=C2ZAMLK88).
- Upon reading a cache record with `last_synced_at` older than a day, enqueue a low-priority Shoryuken job to do a background sync for the latest POA data. POAs are likely to be requested multiple times while a user is in the vicinity, and in the off-chance they hit a wrong stale value, this makes it probable that they only see it once.

**Comment by yoomlam** [comment]
Also to be considered: the Reporting Team currently relies on Caseflow's cache of POA records -- see https://github.com/department-of-veterans-affairs/dsva-vacols/issues/136 and https://github.com/department-of-veterans-affairs/dsva-vacols/issues/138.

If cached POA records are limited to a set number of records or if a POA record with a `participant_id` cannot be found in Caseflow's DB, then we'll need to have a discussion with the Reporting Team to update their expectations. Some expectations were described in [this response](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/136#issuecomment-668897334). There was some mention of the Reporting Team getting direct access to BGS but the current status and future plan are unknown.
