### ISSUE TITLE
[V2] Copy and tweaks to confirmation page [1]

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1497]
Make changes to this page to match changes to template for success confirmation page (https://github.com/department-of-veterans-affairs/caseflow/issues/1094):

- Change "Congratulations!" to "Success!"
- Descriptive paragraph under "Success!" reads: "_____'s case has been certified. You can now close this window and open another appeal in VACOLS."
- Remove "were" so that last bullet point reads: "Representative and hearing fields updated in VACOLS", so text is shortened to 1 line.
- Small text at the bottom of the page "Way to go! ..." removed.

<img width="961" alt="screen shot 2017-05-10 at 12 04 22 pm" src="https://cloud.githubusercontent.com/assets/18075411/25909223/7956e3fe-357a-11e7-9e9a-e8af9b7722e8.png">

**Comment by amprokop** [comment]
@shellicious — can you add the new Form 8 bullet copy to this ticket?

**Comment by kierachell** [comment]
<img width="1052" alt="screen shot 2017-05-10 at 12 16 34 pm" src="https://cloud.githubusercontent.com/assets/18075411/25909240/8826f57c-357a-11e7-9501-8995d14e5e66.png">

**Comment by astewarttistatech** [comment]
Based on updated AC changes, this ticket is now Obsolete.
