### ISSUE TITLE
Bulk Assignment Modal Filter for AOD & CAVC

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14985]
## User or job story
User story: As an organizational admin who has access to bulk assign tasks, I need the task type filter to include AOD & CAVC as options, so that I can bulk assign these to users separately. 

## Acceptance criteria
- [ ] Organizational Admins have the ability to filter out AOD & CAVC cases and bulk assign those to users on their team

**Comment by araposo-tistatech** [comment]
@hschallhorn not sure if this should be its own filterable field since we include this information in the "Task Type" column in queue.

**Comment by hschallhorn** [comment]
This would need to be a new dropdown as the bulk assign task type dropdown does not take AOD into account.

Where do you see this fitting in with Bulk Assign should prioritize AOD cases #14781
