### ISSUE TITLE
Add path field to POA Mark Task Complete Modal

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14980]
## User or job story
User story: As a POA, I need to be able to add a path to the IHP when completing an IHP task and returning the task to the VLJ support.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: ihp_notification
- [ ] This feature should be accessible to the following user groups: IHP writing POA
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] The Mark task complete modal includes a required field where the IHP path can be added
- [ ] Modal shows error if validation of path fails (see how we validate decision document ids)

## Release notes
The Mark Task Complete modal now includes a path field where POAs can add the IHP path when completing the task and routing the task back to VLJ Support.

**Comment by hschallhorn** [comment]
Needs to be broken out into 3 engineering tickets.
1. Store V drive IHP link somewhere???
1. Add spot for link in task completion modal
1. Show V drive IHP link in case details (restricted to vlj support)

We also need to grab information from VLJ support or VSO users on the formatting of this link. We could create a regex to validate the link

**Comment by ryanroyroy** [comment]
The VSO/POA will be able to select the action to 'Mark Task Complete' and then a modal will afford them the ability to insert a link to the file and instructions.

![image](https://user-images.githubusercontent.com/6116023/91996081-97c3ce00-ed06-11ea-925f-8231af65c588.png)

https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=62%3A0

**Comment by hschallhorn** [comment]
@ryanroyroy Is there any way we can reach out to VLJ support and get an example of a full v-drive path to an example ihp draft as uploaded by a VSO user? Basically, what do we expect the vso user to enter here? What format?

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||
5 | ||||||||
8 | 
```

Includes backend changes to set values in the model created in #15206.
If path already exists, update the path.

#### Why 1?
* 

#### Why 2?
*

#### Why 3?
*

#### Why 5?
* Moving away from the default "Mark task complete" action, may require a new action/component.
* Will need to update controller to allow completing a task to accept ihp path location, trigger creation/update of <insert ihp link model name here>
* Need to write feature tests
