### ISSUE TITLE
Capture Stats on AMA IHP Tasks 

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14997]
## Description
Capture stats on tasks created for IHP tasks to include: 

Task creation date
Task creation method (automated via Caseflow or an admin action created by VLJ/Attorney) 
Task instructions
Task placed on hold date
Number of days placed on hold
Task on hold end date
Task completion date

## Acceptance criteria
- [x] Report with above information added to Metabase
- [x] Can determine average number of days it takes to complete an IHP task for AMA Cases

## Background/context/resources
Looking for baseline information on the average time it currently takes to complete IHP tasks. We will want to distinguish if the task was created by Caseflow or if it was initiated via a VLJ/Attorney. My assumption is the automated tasks are completed faster then manual task creation, but would like evidence of that.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | |||||||
3 | 
5 | 
8 | 
```

automated via Caseflow - InformalHearingPresentationTask
admin action created by VLJ/Attorney - IhpColocatedTask

What do we mean by "instructions"? What would we like to see in metabase relating to instructions?
 - Just the instructions created with the task
Would like all information to be in a table with a column for each thing stipulated  
Can ask for graphs showing changes over time in later tickets

We think all the information we need to gather here is to be pulled from Caseflow

#### Why 1?
* Might get a boost from doing #15003

#### Why 2?
* SQL distinguishing between the two creation types

**Comment by hschallhorn** [comment]
Pair with @mkerns355 !

**Comment by lomky** [comment]
Dashboard created in #15003 [Metabase dashboard](http://query.prod.appeals.va.gov/dashboard/11)

[Assumptions made for Legacy Data collection:](https://github.com/department-of-veterans-affairs/caseflow/issues/15003#issuecomment-689802232)

 - Only `closed` IHP tasks will be considered
 - Old style holds are not accounted for in this data, as we have no way to reconstruct that information accurately
 - 'Task placed on hold date' is the earliest `created_at` date of a child TimedHoldTask
 - 'Task on hold end date' is the latest `closed_at` date of a child TimedHoldTask
 - 'Number of days placed on hold' is the difference between the above two, _not_ to sum of all TimedHoldTasks created->closed. In other words, time between 'on hold' is assumed to also be on hold _in this particular use case_

**Comment by mkerns355** [comment]
Hey @araposo-tistatech I believe this ticket is complete. Please verify that the results are sufficient. The query used for the AMA Appeals is a copy of the Legacy Appeals query Kat did except using `Appeal` versus `LegacyAppeal`. Query can be found here: https://query.prod.appeals.va.gov/question/92.

**Comment by araposo-tistatech** [comment]
@mkerns355 this looks great, thank you!

**Comment by hschallhorn** [comment]
@mkerns355 There are actually some additional IHP tasks that exist for AMA appeals. These have a task type of `InformalHearingPresentationTask` and are assigned directly to VSOs rather than the colocated team. We should include these in the dashboard as well

**Comment by mkerns355** [comment]
Hi @araposo-tistatech and @hschallhorn please see update Dashboard for additional IHP tasks that exist for AMA appeals with task type of `InformalHearingPresentationTask`. Let me know if this looks right?

IHP Tasks Dashboard: https://query.prod.appeals.va.gov/dashboard/11

**Comment by yoomlam** [comment]
@mkerns355 Take a look at the new query: https://github.com/department-of-veterans-affairs/caseflow/issues/15003#issuecomment-694961250
