### ISSUE TITLE
Attorney Fees | Add Clearable prop to searchable dropdown

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#14998]
## Description
This ticket is a result of dogfooding for Attorney fees:

The user cannot delete the name entered in the searchable dropdown (e.g. “Sarah Batz”) or backspace however they can type a character(s) to advance.

## Acceptance criteria
- [x] User can clear the text on the searchable dropdown on the Add Claimant modal
- [x] Update the Jest test for the add claimant modal to check that it's clearable

## Background
Reporting in the [Attorney Fees dogfooding](https://docs.google.com/document/d/1InfCVKc2z46cXn_10FSceCIG87d13hUZZHk1CWb1REQ/edit) journal.

## Technical notes
The SearchableDropdown is implemented in `caseflow/client/app/intake/components/AddClaimantModal.jsx` and has an optional prop to make it clearable.

**Comment by wdrougas-tista** [comment]
@leikkisa @jcq When trying to run the Jest test for the AddClaimant modal, I got the failure pasted below. Further down it is suggested to run `yarn run test:jest -u` to update code changes and when I ran that all of the clearable props across Caseflow were updated to `true`. I stashed those changes, made the necessary updates to the code again, and ran the AddClaimantModal test and got the same error. The test I added to confirm the dropdown can be cleared passes so what would you recommend here? 


![Screen Shot 2020-09-02 at 5.28.33 PM.png](https://images.zenhubusercontent.com/5e976ddfed689a8dc52aee6c/840ff776-5347-44ec-8e56-e3bbfd01c090)

**Comment by jcq** [comment]
@wdrougas-tista It looks like it's just a matter of something having changed in the snapshot, which may be entirely legit. Can you connect your PR with latest code to this (or just send me link) and I can take a look to confirm?

**Comment by wdrougas-tista** [comment]
@jcq Just created PR and tagged you on it

**Comment by wdrougas-tista** [comment]
So all of the jest tests are failing on the PR so it looks like I need to go ahead and run that command to update them
