### ISSUE TITLE
[Dogfooding Bug] Offset is displayed instead of Timezone for some cases

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14993]
## Description

![unnamed.png](https://images.zenhubusercontent.com/569954a5638e718c99601d36/59175bef-9670-4329-9099-ae9c00ebcef1)

An offset is displayed instead of a timezone for some timezones (e.g. "Vladivostok", which shows "+10").

## Acceptance criteria
- [ ] Ensure something friendlier than the timezone offset displays

## Technical notes

Possibly because there is no timezone abbreviation associated with "Vladivostok"; this is an issue in both the front end (moment.js) and back end (Rails timezones).

**Comment by ferristseng** [comment]
Relevant: https://stackoverflow.com/questions/51525777/strftimez-returns-wrong-result

**Comment by lund5000** [comment]
Closing as "won't fix" because it is unlikely to affect the vast majority of hearings and appellants
