### ISSUE TITLE
UI Improvement | Show legacy opt-in selection on add issues page table

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15006]
### UI improvement for Intake 

Show legacy opt-in selection on add issues page table
![Screen Shot 2020-08-18 at 2.46.36 PM.png](https://images.zenhubusercontent.com/5ee7e3b72a6c07806d69db7d/01025b91-80eb-4703-8108-e56521c44a6a)

**Comment by rutvigupta-design** [comment]
Closing because #14698 already addressed this.
