### ISSUE TITLE
Intake | Attorney Fees | Update claimant help text

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15001]
## Description
The current claimant-related help text will become outdated when the Attorney Fees feature is launched.

## Acceptance criteria
- [ ] Update claimant help text copy on the Intake Review page
  - [ ] If the attorney_fees feature toggle is enabled
  - [ ] And the intake is for an Appeal
- [ ] Add a screenshot to this GitHub issue

## Copy
**Label for form field**
Please select the claimant listed on the form.

**If it's easy to move this into help text below the label, separate it out. If not easy then keep it with the label:**
Please select the claimant listed on the form. If the claimant is a Veteran's dependent (spouse, child or parent) and they are not listed or their  information needs to be updated, please email for assistance. Note: Remember to encrypt any emails that contain PII (such as a veteran or claimant's name, file number or SSN).

If the claimant is an Attorney, please click "Add Claimant".

## Background/context/resources
Original discussion leading to this ticket [here](https://github.com/department-of-veterans-affairs/caseflow/issues/10586#issuecomment-674979780)

Current copy:
> Please select the claimant listed on the form. If you do not see the claimant in the options below or if the claimant's information needs to be updated, please email for assistance. Note: Remember to encrypt any emails that contain PII (such as a veteran or claimant's name, file number or SSN).

**Comment by rutvigupta-design** [comment]
Moving to eng. This will likely change in the future with upcoming Non-Veteran Claimant work, but for now it's worth making the edit so that users know they can still add attorneys.

**Comment by rutvigupta-design** [comment]
@leikkisa just flagging this so we ensure this copy reflects everywhere. The primary change is adding: 

`If the claimant is an Attorney, please click "Add Claimant".`

**Comment by leikkisa** [comment]
@rutvigupta-design Oh, thank you for the ping. I'm going to move this to Ready for Dev as a bonus ticket. It's a swiper.
