### ISSUE TITLE
[1] Add gray line between instructional text and questions/form elements

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1500]
We should use an existing styleguide component for this.

Like so on step 2:

![screen shot 2017-04-07 at 3 49 06 pm](https://cloud.githubusercontent.com/assets/1178390/24817331/1ee23e08-1baa-11e7-89c0-a950bac819c5.png)

And so on step 3:

![screen shot 2017-04-07 at 3 49 13 pm](https://cloud.githubusercontent.com/assets/1178390/24817330/1ecd42dc-1baa-11e7-8aae-51f5c1580701.png)

And on step 4:

![screen shot 2017-04-07 at 3 52 38 pm](https://cloud.githubusercontent.com/assets/1178390/24817380/4566d91c-1baa-11e7-9bcc-a7e5b9283932.png)

**Comment by astewarttistatech** [comment]
@shellicious Am I supposed to check the width of the grey line break as well as the color? If so, do I go by the hex code in the mocks, displayed. I do not know the spec of the line width.

**Comment by shellicious** [comment]
@astewarttistatech this ticket is still in feature definition, which means that I and other designers will finalize the spec (margins, width, color, etc.) in this Thursday's design meeting. After that meeting, I'll update the ticket with more detailed instructions.

**Comment by amprokop** [comment]
Look on the styleguide for the HTML and CSS to do this.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access certification v2
2. Go through the happy path flow
3. Validate that appropriate titles have grey line breaks under them (see the AC and mocks)

Screenshots: 
![cv2greyline](https://cloud.githubusercontent.com/assets/23038505/26000068/7670ab8a-36f5-11e7-9979-8c4340d7b83f.gif)
