### ISSUE TITLE
[Sentry] TypeError: Cannot read property 'map' of undefined config.tabs

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15014]
## Description
```
TypeError
Cannot read property 'map' of undefined
```
`config.tabs` is undefined

./app/queue/QueueTableBuilder.jsx in calculateActiveTabIndex at line 32:34
```ruby
class QueueTableBuilder extends React.PureComponent {
  paginationOptions = () => querystring.parse(window.location.search.slice(1));
  calculateActiveTabIndex = (config) => {
    const tabNames = config.tabs.map((tab) => {  # <===== Here
      return tab.name;
    });
    const activeTab = this.paginationOptions().tab || config.active_tab;
    const index = _.indexOf(tabNames, activeTab);

```

Hunter believes this happens when a judge goes from their assign page to their queue, specifically when clicking “queue” in the caseflow application title. [Slack msg](https://dsva.slack.com/archives/CLRTL92TW/p1597417374021100?thread_ts=1597343557.017300&cid=CLRTL92TW)

## Acceptance criteria
- [ ] This code does not raise an exception
- [ ] Corresponding pages load properly

## Background/context/resources
[Sentry alert](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10877)

**Comment by hschallhorn** [comment]
[Possibly related](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/10744/?referrer=webhooks_plugin)
[Slack Thread(s)](https://dsva.slack.com/archives/CLRTL92TW/p1592854788010200?thread_ts=1592830895.001600&cid=CLRTL92TW)

**Comment by hschallhorn** [comment]
Preference to fix the underlying issue which is believed to be "Navigating to queue from the judge assign page via the navigation bar (not "switch views") does not call the back end to get queue config"

Timebox to a 3, implement quick fix null check if root cause not found.

**Comment by hschallhorn** [comment]
LoadingDataDisplay->componentDidMount is not firing when switching between the two pages.
