### ISSUE TITLE
Design for unscheduled hearing notes

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#15032]
## User story
As a Hearing Coordinator, I want to see a hearing section on the Case Details page of appeals with no scheduled hearing, so that I can easily see the hearing request type, disposition, and view and add notes.

## Acceptance criteria

- [x] [ Add notes when converting hearing type or scheduling](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=7966%3A21)
- [x] [ Add notes directly from Case Details](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6271%3A9768)
- [x] View notes [when scheduling](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=7966%3A1386) and on [Case Details
](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=7952%3A289)
- [x] Edit notes anywhere they can be viewed 
- [x] **Consideration of notes functionality and behavior for all hearing request states. Specifically: [an unscheduled hearing that has been withdrawn ](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6271%3A8885)(disposition: cancelled)**

## Designs
[Figma link](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5791%3A20342)

### Design specs

- copy over from [JIRA ticket](https://vajira.max.gov/browse/CASEFLOW-234)

## Background / context
Unscheduled hearing notes were originally designed as part of completing work on converting an unscheduled hearing type to virtual (see #14857). In the course of breaking down the work into manageable engineering tasks with a focus on the highest-priority functionality, notes were broken out into their own epic (see #15061) for later implementation.

Designs were completed for adding, editing, and viewing notes. However, more consideration is needed to make sure we cover all possible hearing request states, and specifically, the case when an unscheduled hearing is withdrawn (disposition: cancelled). An initial design for this state was proposed in which the notes remain on Case Details in an uneditable state; 
(see design specs in engineering task #15063), but it needs another look.

For context, the range of possible hearing request states includes: unscheduled versus scheduled hearings. And dispositions of: `null`, cancelled, postponed, no show, and held. It may be beneficial for the team to include a _lightweight_ flow diagram (perhaps simply arrows connecting the Figma frames; or a separate boxes-and-arrows flow) to communicate how the notes display through the various states.

### Definitions
In this case, there are two "notes types" that will be discussed: 

- Withdraw notes: notes that are input as "instructions and context" into the Withdraw Hearing modal (just like as when you withdraw a scheduled hearing)

- Unscheduled Hearing notes: notes that are also context that the hearing coordinators add about the hearing before it is scheduled. 

### Business Value
Increasing the accuracy with which virtual hearings are scheduled 

### Checklist with milestones

Week 1
- [x] Review requirements and related tickets | RP + NR | 10/5
- [x] Pair with Tango engineer on proposed flow | RP+FT+RR+NR | 10/7
- [x] Draft participant recruitment emails | RP | 10/6
- [x] Review proposed flow and align on type of artifact needed to effectively collect user feedback | RP + NR | 10/8
- [x] Setup Hearing Coordinator feedback sessions for Week 3 | RP | 10/9

Week 2 & 3
- [x] Collect design team feedback | RP | 10/14
- [x] Finalize designs to show to users | RP | 10/16
- [x] Finalize moderator guide | RP | 10/19
- [x] Hold user feedback sessions | RP | 10/19-10/20
- [x] Collect engineering feedback | RP | 10/22

Week 4
- [x] Synthesize user feedback | RP | 10/21-10/28
- [ ] Present at Sprint Planning | RP | ~~10/29~~ TBD
- [ ] Finalize designs and ticket | RP | 11/4

### User Sessions
Three 30-minute sessions with hearing coordinators were held for feedback. 

- [Design Brief with Synthesis and Conclusion (Link)](https://docs.google.com/document/d/106KIiptCl1rZwczHgCrPc8WUBWqWErbdvx215vZghoA/edit#heading=h.735jltwz11z1)

- [Moderator Guide (Link)](https://docs.google.com/presentation/d/1QpWfyNALMiu_0FtZxUjIFD3nFbsTT2UgCzpBGR99_mM/edit#slide=id.g7290524a42_0_0)

#### Decision Summary
There were two different design options that unscheduled hearing notes could have taken. One was one notes field that combined withdraw notes and unscheduled hearing notes and output to the case timeline on the case details page, and the other was two separate notes fields that output to two different sections on the case details page. The designers chose the first option with one notes field in the interest of efficiency and minimizing confusion for both the team and hearing coordinators going forward.

**Comment by rishanava** [comment]
@nicholer can we fold into #12826?

**Comment by nicholer** [comment]
@rishanava I'm thinking there's enough here that it could be its own separate ticket. It applies to all unscheduled hearing types, not just specifically to Travel Board. And there are different states for when there's a single hearing, multiple previous hearings, etc. For now, I'm planning to write the ACs for this one. But there'll definitely be an ongoing conversation among product / eng / design, so stay tuned!

**Comment by nicholer** [comment]
Final design specs migrated to [CASEFLOW-234](https://vajira.max.gov/browse/CASEFLOW-234)
