### ISSUE TITLE
Remove cached POA when removed in BGS

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15043]
## Description
When a POA is removed in BGS, it is not removed from Caseflow's cache of BGS power of attorneys stored in Caseflow's database.  This is reflecting the data incorrectly in Caseflow.

## Acceptance criteria
- [ ] When a claimant's POA has been removed in BGS, it should also be removed from Caseflow's cache in the `bgs_power_of_attorneys` table.

## Out of scope
- Persons with invalid dates of birth
- Other current POA concerns

## Background/context/resources
[Original Slack thread (partially deleted due to PII)](https://dsva.slack.com/archives/CHX8FMP28/p1596116644087700)
[Re-post in Slack](https://dsva.slack.com/archives/CHX8FMP28/p1596123371096700)
[Discussion in appeals-engineering](https://dsva.slack.com/archives/C2ZAMLK88/p1596147165058900)

## Technical notes
BGSPowerOfAttorney, WarmBgsCachesJob, and Claimant are good places to start.

**Comment by nanotone** [comment]
Syncing BGS POA removals is a subset of a bigger BGS POA cache staleness issue. I did a technical info dump in the description of this sibling ticket: #14974 -- making sure removals are correctly handled would be closely related to that work.
