### ISSUE TITLE
Missing email alert when converting to virtual

### ISSUE THREAD

**Issue by lund5000** [department-of-veterans-affairs/caseflow#15056]
## User story
As a hearing coordinator, I need to know when the Veteran doesn't have an email in VBMS as I’m converting a hearing to virtual so I can fix that before scheduling.

## Acceptance criteria
- When a user is converting a hearing to virtual and the Veteran is missing an email in VBMS, then in the confirmation page
  - the Veteran Email is listed as "None"
  - an information alert appears under the Veteran Email

### Designs
[Figma link](https://www.figma.com/proto/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6333%3A2479&viewport=-839%2C837%2C0.08404029160737991&scaling=min-zoom)

<img width="500" alt="Screen Shot 2020-08-27 at 3 17 07 PM" src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/eca4ea59-7cf4-49a3-ac73-fa3fc9feddee">

### Technical notes
- Might not be able to serialize email address into this confirmation page because we're not caching it from VBMS
- Rubaiyat currently planning on loading the page and displaying email address from VBMS once it's retrieved

**Comment by nicholer** [comment]
@lund5000 If we split out Notes functionality from the convert flow, we'll need another ticket to update the warning copy later. Here's the relevant [design in Figma](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6333%3A2479).
