### ISSUE TITLE
Backfill Virtual Hearings Data in VACOLS

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#15052]
## Description

Backfill `BFHA` and the `HEARING_TYPE` fields in VACOLS.

`HEARING_TYPE` should be `R` for virtual hearings
`BFHA` should be `7` for held virtual hearings

We should hold off on backfilling data until we fully support legacy virtual hearings. Once that happens, we would only need to backfill data once.

## Open Questions

- [x] Can we write a 7 to BRIEFF.BFHA if the HEARSCHED.HEARING_TYPE isn’t ‘R’? Are there any constraints in VACOLS that requires them both to be set?
  _There are no database constraints, but ideally we would want them to be consistent, if BFHA = 7 then you would expect the HEARING_TYPE to = 'R'_
- [x] Is the HEARSCHED.HEARING_TYPE value important in the short term for accurate reporting?
  _Yes_
- [x] Are these changes currently in production? Could a coordinator choose a virtual request type now?
  _Yes, but they are not scheduling virtuals via VACOLS_
- [x] If we set either or both of these values, could that break some functionality for the user in VACOLS?
  _No_

## Acceptance criteria
- [ ] Update documentation: [link]

## Background/context/resources

Notes from discussion: https://hackmd.io/4SyBnZiYTJ2p9ZyFSwRW5w?both

**Comment by tomas-nava** [comment]
here's what I did to close this ticket on 2020-09-11:

## update Caseflow
For all the virtual legacy hearings in Caseflow, I saved the original request type to `original_vacols_request_type`

```ruby
lhs = LegacyHearing.all.select(&:virtual?)

lhs.count
=> 3280

lhs.each do |lh|
  begin
    rt = lh.request_type
  rescue Caseflow::Error::VacolsRecordNotFound
    next
  end

  # if the request type is not virtual, and we haven't already saved
  # an original request type, then save it
  rt_not_virtual = rt != VACOLS::CaseHearing::HEARING_TYPE_LOOKUP[:virtual]
  ovrt_blank = lh.original_vacols_request_type.blank?
  do_save = rt_not_virtual && ovrt_blank

  if do_save
    lh.update!(original_vacols_request_type: lh.request_type)
  end
end
```

## update VACOLS
The next step was to send Jed a list of ids for appeals and hearings to update. I used the script below to generate a CSV, which I then opened in Excel.

In the spreadsheet, I verified that the first script above had worked correctly. Then I identified a few edge cases where appeals had multiple held hearings, and looked at them more closely to make sure that I would send the correct information. Finally, I copied lists of 2,215 appeal and 3,153 hearing ids into their own CSVs and sent them to Jed.

```ruby
lhs = LegacyHearing.all.select(&:virtual?)

lhs.count
=> 3281

log = "hearing_vacols_id,request_type,original_request_type,disposition,appeal_vacols_id,bfha,appeal_hearings_count,held_hearings_count,most_recent_hearing_is_held_virtual\n"

lhs.each do |lh|
  lh.reload
  begin
    rt = lh.request_type
  rescue Caseflow::Error::VacolsRecordNotFound
    next
  end

  la = lh.appeal
  hearings_count = la&.hearings&.count
  bfha = la&.case_record&.bfha.presence || "none"
  disposition = lh.disposition.presence || "none"

  most_recent_hearing_is_held_virtual = false
  held_hearings_count = 0

  if disposition == Constants.HEARING_DISPOSITION_TYPES.held
    if hearings_count == 0
      most_recent_hearing_is_held_virtual = true
      held_hearings_count = 1
    else
      hhs = la.hearings.select { |ah| ah.disposition == Constants.HEARING_DISPOSITION_TYPES.held }
      held_hearings_count = hhs.length

      if hhs.exclude?(lh)
        held_hearings_count += 1

        if hhs.sort_by(&:scheduled_for)&.last&.scheduled_for &.< lh.scheduled_for
          most_recent_hearing_is_held_virtual = true
        end
      else
        most_recent_hearing_is_held_virtual = hhs.sort_by(&:scheduled_for)&.last == lh
      end
    end
  end

  log << "#{lh.vacols_id},#{rt},#{lh.original_request_type},#{disposition},#{la&.vacols_id},#{bfha},#{hearings_count},#{held_hearings_count},#{most_recent_hearing_is_held_virtual}\n"
end

puts log
```
