### ISSUE TITLE
Documents List | Search: highlight search results

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1507]
**Description** 
Make documents list search better! Right now, our search results do not give users enough feedback. We want to highlight results and make sure everything related to the search is visible. 

## AC

- [x] Verify that the comment section expands and highlights the word that's being searched
- [x] Verify that words that exactly match are in bold and highlighted in `$color-gold-lightest` [See style guide for color](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#colors)

- [x] Verify that the category tags have focus when the category name has been searched (procedural, other evidence, medical) (See Fig.2)
- [x] Highlight receipt Date text as well when a date matches the query
- [x] If the text in the comment doesn’t match the search query but it matches the doc type or tag text, do no expand comment; highlight doc type and issue tag
- [x] When search query is removed from the search box (reset search), hide all comments

## Note
We are aware of the 508 set backs of the yellow highlight on the gray background color on the issue tags. However, making the yellow and gray compliant will not make the text compliant with the background color. We decided that the next best thing was to bold the exact match search results so that there is still a visual distinction between the highlighted and not highlighted words. 

## Mock up
(Fig 1)
![image](https://cloud.githubusercontent.com/assets/13420618/26786861/f68128d4-49d5-11e7-9a22-5e0232b0f15f.png)

(Fig.2)
![image](https://cloud.githubusercontent.com/assets/13420618/26786905/174ae276-49d6-11e7-801a-e18f0345be18.png)

**Comment by tejans24** [comment]
The current Table component is not dynamic, i.e it doesn't re-render when a new valueFuncition is passed to the Table component.

There are two options:
* Update the current Table component to support new re-renders
* Create a new Table component that better matches the requirements of Reader

I am currently looking into how other parts of the Table work to see if the current table can suit the needs for this issue.

**Comment by tejans24** [comment]
@abbyraskin @gnakm 
* should we highlight Receipt Date text as well when a date matches the query?
* Also when a user is searching, if the text in the comment doesn’t match the search query but it matches the doc type or tag text, should we still expand the comment section of the result?

**Comment by gnakm** [comment]
Dropping our convo here and adding to AC above. 

- Yes highlight Receipt date
- Do no expand comment; highlight doc type and issue tag
- When search query is removed from the search box (reset search), hide all comments

**Comment by tejans24** [comment]
Removed the aria tag for search result. The highlighted text is wrapped in <mark> tag

**Comment by astewarttistatech** [comment]
@tejans24 Put that comment in the AC cause as of now it is failed.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Reader with multiple documents
2. Comment and add tags to multiple documents with a consistent theme
3. On the Documents List page, search for the term
4. Validate that the search results leave the term in a highlit state
5. Validate that the search results are expanded
6. Validate the search results based on the rest of the AC and mocks provided

Screenshots: 
<img width="1091" alt="screen shot 2017-07-13 at 7 44 35 am" src="https://user-images.githubusercontent.com/23038505/28165361-7f787a00-67a1-11e7-9312-5337fa517a9e.png">
<img width="1091" alt="screen shot 2017-07-13 at 7 46 30 am" src="https://user-images.githubusercontent.com/23038505/28165362-7f829daa-67a1-11e7-8d38-b45b27b91562.png">
