### ISSUE TITLE
Intake | Docket Change | Docket switch task automatic assignment 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15086]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board, when I add a docket switch task, it should automatically be assigned to myself so that I can take the appropriate actions on it

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by leikkisa** [comment]
Closing this as a story ticket, this work is already complete.
