### ISSUE TITLE
Intake | Docket Change | Creating docket switch mail task 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15084]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board, I want to be able to create a "docket switch" mail task so that I can initiate switching dockets

## Acceptance criteria

- [ ] Members of the Office of the Clerk of the Board team can see and select the "Add new mail task" button on the Case Details page
- [ ] When the "Add new mail task" button is selected, the "Add new mail task" modal appears
- [ ] The instructions in the "Add new mail task" modal are: "Add a new task based on a mail item from the Mail Portal.
Please add context for this action - this will be permanently visible as task instructions on the Case Details page." (please see design below)
- [ ] When a user selects the correspondence type, they can see all existing mail tasks and a new mail task: "Docket Switch" 
  - [ ] The options should be alphabetized 
- [ ] Only members of the OCB team should be able to view the Docket Switch mail task
- [ ] The context/instructions field is required, and the "Submit" button should be inactive until the user has entered a character in the field
- [ ] Upon submitting, the user should see: 
  - [ ] A success banner (please see design below) - covered by #15094
  - [ ] The Docket Switch task in their Active Tasks section
- [ ] The Docket Switch task should be automatically assigned to the user that crated the Docket Switch mail task

### Designs

[Figma prototype
](https://www.figma.com/proto/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=491%3A3109&viewport=981%2C607%2C0.06997568160295486&scaling=min-zoom)

**Designs:** 
![1. No Active Tasks.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/28c42669-de5b-43cd-8a21-4312b41bb4c7)
![5. Docket Switch selected.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/6e28d93e-cc03-4677-bec1-a1b51d620a10)
![7. Docket Switch task successfully added.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/8561adbc-5c61-47c9-9200-67fed45ce00f)

### Background/context

OCB team members need a way to create a mail task that will initiate the process of switching dockets. 

### Other notes
Remaining open questions that are being validated: 
- Should all members of the OCB team have the ability to create a Docket Switch mail task?
- What the next action should be - Send to Judge? This depends on the new added workflow steps that need to be designed and tested. 

### Resources/other links
- [Ticket for creation of `DocketSwitchMailTask` model](https://github.com/department-of-veterans-affairs/caseflow/issues/15136)

**Comment by rutvigupta-design** [comment]
@jcq I'm moving this to engineering define because it will largely be unaffected by the new steps we're working through in the workflow. Please let me know if anything else is needed from design for this story!

**Comment by leikkisa** [comment]
Closed as a story ticket
