### ISSUE TITLE
Intake | Docket Change | Docket switch task permissions

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15085]
## User or job story
As a user of the Office of the Clerk of the Board, the "docket switch" task should only be available to me and specified users within my organization

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by leikkisa** [comment]
Closing this story ticket as completed (handled in one of the early PRs).
