### ISSUE TITLE
Intake | Docket Switch | Ability to manually close tasks

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15099]
## User or job story
As a BVA Attorney at the Office of the Clerk of the Board, I need a way to manually close out any tasks that are no longer relevant to the newly selected docket type and shouldn't be switched over so that unnecessary tasks do not remain open

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_switch`
- [ ] This feature should be accessible to the following user groups: `clerk of the board`
- [ ] Once a user has added in information about the docket switch (date, type of grant, docket type), they should see the Add/Remove tasks screen
- [ ] The progress bar should be on the second step (please see the designs below)
- [ ] The user should see which docket they are switch from and to (For e.g: You are switching from Hearing to Direct Review.) at the top – this should be body text and bolded. 
- [ ] The user should see which docket they are switch from and to (For e.g: You are switching from Hearing to Direct Review.) at the top – this should be body text and bolded. 
- [ ] Below that, the user should see instructions – copy is in the designs below
- [ ] The user should see a list of all orphan tasks (i.e. tasks NOT associated with a docket like FOIA, Translation etc) that are currently open or assigned on the current docket
  - [ ] The orphan tasks should all be pre-selected
- [ ] Tasks that would be automatically generated for the new docket (e.g. Distribution task) show in the list
  - [ ] The automatically generated docket tasks that are applicable to the new docket should be inactive i.e. the user cannot remove it
- [ ] If a user re-selects the checkbox, that task should be transferred to the new docket
- [ ] Selecting back will take the user back to the Review Request page
- [ ] Taking action on this page is NOT required - the "continue" button should be active
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Out of scope

- [ ] If a user unselects a checkbox, they should get a modal asking them to confirm the removal (please see the design)

### Designs

**All tasks are preselected**
![Remove Tasks](https://user-images.githubusercontent.com/51714306/97454768-1dc65480-1905-11eb-829b-b6fbca614eb8.png)

**Confirmation modal if user removes a task**
![Remove Tasks - confirm removal](https://user-images.githubusercontent.com/51714306/97454793-23bc3580-1905-11eb-8b50-ef8b305ab2a4.png)

**Removed task**
![Remove Tasks - removed task](https://user-images.githubusercontent.com/51714306/97454810-261e8f80-1905-11eb-8690-b354026c3d99.png)

### Technical notes
Orphan tasks:
- Admin actions

Every appeal tasks or docket specific tasks (not orphan tasks):
- Draft decision, dispatch, hearing tasks

**Comment by Sjones352** [comment]
**All tasks are preselected**
<img width="1603" alt="Screen Shot 2021-01-21 at 12 14 51 PM" src="https://user-images.githubusercontent.com/23080951/105386365-5020de80-5be2-11eb-82e0-d787401b7f5a.png">

**Confirmation modal if user removes a task**
<img width="1599" alt="Screen Shot 2021-01-21 at 12 16 54 PM" src="https://user-images.githubusercontent.com/23080951/105386595-92e2b680-5be2-11eb-830e-ea17eb34678f.png">

**Removed task**
<img width="1585" alt="Screen Shot 2021-01-21 at 12 21 18 PM" src="https://user-images.githubusercontent.com/23080951/105387178-451a7e00-5be3-11eb-8fe1-9bd753e6c69f.png">
