### ISSUE TITLE
Intake | Docket Change | Add "Switch Docket" to action drop-down menu

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15095]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board to whom the task is assigned, when I add a docket switch task, I should have a "Switch Docket" action in my action drop-down menu so that I can initiate switching dockets

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `ClerkOfTheBoard` organization

### Resources/other links
This will get accomplished via #15136 due to inherent qualities of tasks

**Comment by leikkisa** [comment]
Being worked on as part of #15136
