### ISSUE TITLE
Intake | Docket Change | Task options 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15096]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board to whom a granted docket switch task is assigned, I should have "Put task on hold, Cancel Task, Assign to Person, Assign to Team" actions in my action drop-down menu so that I can take necessary actions on the task.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `ClerkOfTheBoard` organization
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Technical notes
This should come by default from inheriting from `AttorneyTask`

**Comment by jcq** [comment]
No design or engineering work should be necessary, since tasks get these due to their inheritance from `AttorneyTask`

**Comment by rutvigupta-design** [comment]
@jcq should we close this, or should we close it when the engineering work is complete for this?

**Comment by jcq** [comment]
Closing, as it was covered by #15424
