### ISSUE TITLE
Intake | Docket Change | Inputting docket switch information (Grant)

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15097]
## User or job story
As a BVA Attorney at the Office of the Clerk of the Board, I need a way to enter the necessary information from the Veteran's request to switch dockets, so that I best represent the veteran's request to switch dockets.

## Acceptance criteria
- [x] Please put this work behind the feature toggle: `docket_change`
- [x] This feature should be accessible to the following user groups: `ClerkOfTheBoard`
- [x] When a user selects "Switch docket" from their action drop-down menu, they should be taken to this screen
- [x] Please format the header and instructions as shown in the designs
- [x] The user should see a progress bar on the top as shown in the designs (this is the first step) 
- [x] The user should be able to select a date in the receipt date field (following the existing date selector component)
- [x] The user should be able to select "grant all issues" or "grant a partial switch"
- [x] "Grant a partial switch" should have the following help text: "e.g. if the Board is only granting a few issues"
- [x] There should be 3 docket options (Direct Review, Evidence Submission, Hearing) – please disable the current docket type (for e.g. if the current docket type is Hearing, the user should only be able to select Direct Review or Evidence Submission)
- [x] If a user selects "Grant a partial switch", they should be able to see a list of issues and select them (multi-select checkboxes) 
- [x] All fields are required and once the user has made all their selections, the continue button should become active
- [x] Selecting "cancel" will take the user back to the Case Details page
- [x] Implement form validation using `react-hook-form` (see prev docket change forms for ref)
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [x] Include Jest tests
- [x] Include Storybook story
- [ ] Update documentation: [link]

### Out of scope

Steps 2, 3, and submission

### Designs

**Empty state**
![19  Switch Dockets_ Review request](https://user-images.githubusercontent.com/51714306/97453012-55cc9800-1903-11eb-9f0e-c140c9a377e9.png)

**Full Switch**
![19 2 Switch Dockets_ Review request - Grant all issues - Docket Selected](https://user-images.githubusercontent.com/51714306/97453045-5c5b0f80-1903-11eb-9a22-affad7fc2a3d.png)

**Partial Switch**
![19 6 Switch Dockets_ Review request - Grant partial issues](https://user-images.githubusercontent.com/51714306/97453067-62e98700-1903-11eb-8be6-6fd888c97c59.png)

### Technical notes

Refer to MTV checkout for reference of the whole process.

### Other notes
- Verify w/ @rutvigupta-design that we don't need to display the previous docket on here
- Verify w/ @rutvigupta-design if we should disable entire form submission if they have selected the same docket or just disable the radio for that docket type so they can't select it

**Comment by jcq** [comment]
This is general story ticket, no engineering work required

**Comment by rutvigupta-design** [comment]
@jcq is there another ticket I should add design AC and designs to?

**Comment by jcq** [comment]
> @jcq is there another ticket I should add design AC and designs to?

Nope, this is good — I mistook this for a more general-purpose story ticket. This works for this chunk of the attorney checkout!

**Comment by leikkisa** [comment]
<img width="1072" alt="Screen Shot 2020-12-27 at 12 27 13 PM" src="https://user-images.githubusercontent.com/6589610/103180141-db0ef300-4847-11eb-894d-77c9880a9e2c.png">
<img width="1086" alt="Screen Shot 2020-12-27 at 12 27 07 PM" src="https://user-images.githubusercontent.com/6589610/103180144-e104d400-4847-11eb-92c3-a5876c542f91.png">
