### ISSUE TITLE
Intake | Docket Change | Routing tasks based on docket switch 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15105]
## User or job story
When a user confirms switching a docket, all tasks should get routed to the appropriate team/individual's queue based upon the selected docket type, so that the appeal can move forward accurately.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by leikkisa** [comment]
Closing as a story ticket
