### ISSUE TITLE
Edit EP Claim Labels | Show End Product Type on "Correct issues" page

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15109]
## User or job story
User story: As a VBA intake user, I need to see the current EP claim type for an issue, so that I can tell if it's correct in case I want to change it

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [edit_ep_claim_labels]
- [x] This feature should be accessible to the following user groups: Intake users (no additional permissions needed at this time)
- [ ] On the "Correct issues" page for decision reviews with end products, I can see the EP claim type that issues are on.
- [ ] The user can view and select the "Edit Claim Label" button that is in-line with the EP Claim Label row
- [ ] The width of the button is 140px and it is 20px from the edge of the row
- [ ] Include screenshot(s) in the Github issue

## Open questions
- Where should ineligible issues go? Should they go on the EP that they would normally go on or in a different section at the bottom? (default: different section at the bottom)

## Release notes
Users will be able to see End Product Claim Types on the "Correct issues" screen.

### Out of scope
- The ability to see claim type on the intake Add Issues page (although if shared code updates in both places, that's 👍)

### Designs
![1. Edit Issues.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/e2acec70-ad0a-4f20-bd3c-168d299feffb)

**If multiple EPs**
![1. Edit Issues - multiple EPs.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/702ee8a8-cd2a-4eb1-b49c-2fbc2fe279f4)

### Technical notes

- This wouldn't be happening on Appeals, or decision reviews processed in Caseflow.
- EP Code is currently included in the request issue data
- We can get the label from the EP code map

**Comment by rutvigupta-design** [comment]
@leikkisa added designs - ready for eng estimation!
