### ISSUE TITLE
Intake | Docket Change | Docket switch success banner

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15104]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board, when I confirm the docket switch, I want to be able to see a success banner so I know I have successfully switched dockets. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `ClerkOfTheBoard`
- [ ] Please format the copy for the banners according to the designs below (please note - these are different for a full switch vs a partial switch)
- [ ] Handles submission of the Docket Switch
- [ ] Format the header of the banner as: You have successfully switched [Claimant Name]'s docket to [New Docket Type]
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Designs

**Full Switch**
![23. (Full) Success banner on Case Details - Full Grant.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/2ffd8444-ec66-46b7-a532-06e31bbe2dff)

**Partial Switch** 
![24. (Partial) Success banner on Case Details - Partial Grant.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/7fe10674-876e-4335-9bc4-85d77a7be89f)

**Comment by jcq** [comment]
We should split this into separate tickets for completion of granted flow and for completion of denied checkout.
