### ISSUE TITLE
Intake | Docket Change | Ability to go back to make changes

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15103]
## User or job story
As a BVA Attorney at the Office of the Clerk of the Board, I need a way to go back and make any necessary changes so that I can ensure all the information is correct. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by rutvigupta-design** [comment]
Closing because this will be covered by an AC.
