### ISSUE TITLE
Intake | Docket Change | Review and confirm docket switch

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15102]
## User or job story
As a BVA Attorney at the Office of the Clerk of the Board, I need a way to review and confirm my selections so that I can ensure that the right information got entered.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `clerk of the board`
- [ ] After a user selects "continue" on the Add/Remove tasks page, they are taken to a confirmation page
- [ ] The progress bar should be on the last step (Review and Confirm)
- [ ] Please format the header and instructions based on the designs below
- [ ] The first part of the instructions includes "You are switching from [Existing docket] to [New docket]. Tasks specific to the [Existing docket] docket will be automatically removed, and tasks associated with the [New docket] docket will be automatically created."
- [ ] Please add in the fields that are displayed according to the design (please note - these slightly differ for a full grant vs a partial grant - partial has a "Issues on original docket" section
- [ ] Final action is "Confirm docket switch"
- [ ] Selecting "back" takes the user to the Add/Remove tasks page
- [ ] Redirect to the Case Details page (see Granted Docket switch banner ticket)
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Out of scope
Submission/continue

### Designs

**Full Grant**
![22. Confirmation - full switch.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/3b5071b2-5561-41c9-95c0-8427c0736955)

**Partial Grant**
![22. Confirmation - partial switch.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/97aa7ffc-0a8c-4bd2-8a8e-0bcd85264180)

**Comment by jcq** [comment]
@rutvigupta-design @mbaenatan Should this always be listing veteran and not claimant? What if claimant is different than veteran?

**Comment by rutvigupta-design** [comment]
@jcq I think this came up once with OCB (I vaguely remember them saying we may just want that to say claimant) but I can't remember why we didn't explore it further (or maybe I just missed it). **For now, let's add a `Claimant` row below the Veteran's row if the claimant is not the Veteran.** In the future, we can explore just having a single "Claimant" row that covers Veterans too but I think we'd want to check with OCB first before making that decision. @mbaenatan what do you think?

**Comment by mbaenatan** [comment]
@jcq @rutvigupta-design I think that's a good idea Rutvi. I also remember them saying that "claimant" is preferred since it is encompasses veteran + if the claimant is different from the veteran. Though not sure if everyone at the Board would agree with this

**Comment by jcq** [comment]
@leikkisa Stupid question... from where do I get the decision date for the various issues as shown in the designs? It looks like that's not something that is being included in the issues by the appeal serializer. 🤔

**Comment by leikkisa** [comment]
@jcq I think it would go into the work queue appeal serializer here.  The field is just called `decision_date`:

```ruby
  attribute :issues do |object|
    object.request_issues.active_or_decided_or_withdrawn.includes(:remand_reasons).map do |issue|
      {
        id: issue.id,
        program: issue.benefit_type,
        description: issue.description,
        notes: issue.notes,
        diagnostic_code: issue.contested_rating_issue_diagnostic_code,
        remand_reasons: issue.remand_reasons,
        closed_status: issue.closed_status,
        decision_date: issue.decision_date
      }
    end
  end
```

**Comment by jcq** [comment]
> @jcq I think it would go into the work queue appeal serializer here. The field is just called `decision_date`:
> 
Ah, k -- I can def just add it; I guess I was just surprised that we didn't already use it for something else and thought I might be missing something 😅

**Comment by leikkisa** [comment]
I was surprised it wasn't already there too (I guess because we use it more in Intake).
