### ISSUE TITLE
Refactor Task Model Spec

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1510]
There are tons of unnecessary db calls in `models/task_spec.rb` which slow down the tests. In addition, there are a lot of unfocused tests.

Lets clean those up.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
