### ISSUE TITLE
Story | Edit EP Claim Labels | User can initiate editing the claim label of an active end product

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15111]
## User or job story
User story: As a VBA intake user, I need to be able to initiate editing the claim label for an end product on a decision review.

## Acceptance criteria
- [ ] The user can click on the review type (Supplemental Claim/Higher Level Review) on the Search Cases page to view the "Edit Issues" screen
- [ ] The user can view and select the "Edit Claim Label" button that is in-line with the EP Claim Label row
  - [ ] The width of the button is 140px and it is 20px from the edge of the row
- [ ] Please put this work behind the feature toggle: [edit_ep_claim_labels]
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Designs

![1. Edit Issues.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/7650fdd5-c045-429f-9838-76ad07792a77)

**If multiple EPs**
![1. Edit Issues - multiple EPs.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/1adf1690-8d16-4f45-aec1-d85fc4f04aff)

**Comment by rutvigupta-design** [comment]
@leikkisa added designs - moving to eng define

**Comment by leikkisa** [comment]
We're going to combine this into the ticket where the user sees the modal and can select the new claim label in #15112

**Comment by leikkisa** [comment]
Combined AC into #15109, will consider this a "story" ticket and close it when that one is complete.

**Comment by leikkisa** [comment]
Closing this story ticket, the Eng ticket has been closed.
