### ISSUE TITLE
Edit EP Claim Labels | Ability to select new claim label

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15112]
## User or job story
User story: As a VBA Intake user, I need a way to select a new claim label from a defined list of allowed options so that I can select the correct label.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [edit_ep_claim_labels]
- [ ] The user can view and select the "Edit Claim Label" button that is in-line with the EP Claim Label row
  - [ ] The width of the button is 140px and it is 20px from the edge of the row
- [ ] After initiating a claim label edit by clicking the button, the user can select the new claim from a searchable dropdown list
- [ ] The drop-down defaults to the existing claim label and the "continue" button is inactive/disabled until a new claim label is selected
- [ ] The dropdown list is limited to the allowed new claim labels, based on the current claim label
- [ ] Clicking "cancel" or the "x" in the top right corner will close the modal and take the user back to their Edit Issues screen
- [ ] Once a new claim label is selected via the drop-down, the "continue" button will become active
- [ ] Make a storybook story for this component
- [ ] Include screenshot(s) in the Github issue

### Out of scope

- Handling submit

### Designs

![2. Edit claim label modal.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/cb24fd73-9bca-4ca0-b4b9-988a6587113a)
![4. Modal - selected claim label.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/0ef9a391-c5d9-4fc0-a887-c247815eab27)
![5. Modal - changed claim label.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/df36f64f-553a-4ad8-8225-faed9226f543)

### Resources/other links

[Figma prototype
](https://www.figma.com/proto/DsNMRSivTbsAOBlnIMcss6/Edit-EP-Claim-Labels?node-id=137%3A1673&viewport=249%2C808%2C0.14310863614082336&scaling=min-zoom)

**Comment by rutvigupta-design** [comment]
@leikkisa added designs and a few small interaction-related ACs. Moving to Eng define!
