### ISSUE TITLE
Edit EP Claim Labels | Show EP data on search page

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15110]
## User or job story
User story: As a VBA Intake user, I need see end product data on the search page results, so that I can quickly pick the claim that I want to view.

## Acceptance criteria
- [ ] On the veteran search results page, show additional the modifier and EP label
  - [ ] E.g: "030 HLR Non-Rating"
  - [ ] Base the column widths and space between columns based on the attached designs (please see attached design 1)
- [ ] If there are multiple EPs within a single decision review, display those as sub-rows (please see attached design 2)
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

## Release notes
Users will be able to see more information about end products on decision reviews on the veteran search page.

### Designs
**1. Annotated with spacing**
![0. Case Search - Annotated.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/fad0f62b-76b4-4d7b-b21e-26d0e308ed31)

**2. Multiple EPs in single decision review**
![0. Case Search - multiple EPs.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/d3dc6c53-3c80-4496-95bf-8b82303f32df)

**3. Design if claim label needs to overflow**
![0. Case Search - overflow.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/d91c43ed-caff-41d3-b283-4a71a5e57796)

### Technical notes
Currently these show up on separate lines within a row, and that pattern can continue

**Comment by rutvigupta-design** [comment]
@leikkisa added in designs – this is ready for eng

**Comment by leikkisa** [comment]
@Sjones352 This looks good to me, but when I tested a "longer" claim label, the styling gets a little messed up.
![Uploading Screen Shot 2020-10-14 at 10.53.22 AM.png…]()
