### ISSUE TITLE
Find a way to get better test coverage of AppealRepository

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1512]
AppealRepository logic is one of our biggest blind spots in test coverage and we have an ever-increasing amount of logic stored there.

My thought is that we may want to use the pattern of `ExternalAPI::BGSService` for VACOLS and VBMS. This way we could stub all of those in tests instead of Appeal repository.

We can use generators to extract the correct stubs :)

As part of this we should be testing `VALID_UPDATE_LOCATIONS` logic

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
