### ISSUE TITLE
Change Docket Type | Document Task Creation

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15124]
## Description
Document task(s) created when switching to new docket type. This should largely mimic what happens when a new intake of the given type is completed.

## Acceptance criteria
- [ ] Update documentation: [link]

## Background/context/resources
- [Data-Driven Documentation of Tasks](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/README.md#data-driven-documentation-of-task-trees)
  - Typical Task Creation Sequences (TCS)
    - [Direct Review](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-DR/freq-taskcreation.md)
    - [Evidence Submission](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-ES/freq-taskcreation.md)
    - [Hearing](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-H/freq-taskcreation.md)

## Technical notes
Most of the logic takes place in the `InitialTasksFactory` class. It will always create a `RootTask` if one doesn't already exist. Currently there is logic that will run `create_subtasks!` only if `appeal.original?` is `true`.

```ruby
  def create_subtasks!
    distribution_task = DistributionTask.create!(appeal: @appeal, parent: @root_task)

    if @appeal.evidence_submission_docket?
      EvidenceSubmissionWindowTask.create!(appeal: @appeal, parent: distribution_task)
    elsif @appeal.hearing_docket?
      ScheduleHearingTask.create!(appeal: @appeal, parent: distribution_task)
    else
      vso_tasks = IhpTasksFactory.new(distribution_task).create_ihp_tasks!
      # If the appeal is direct docket and there are no ihp tasks,
      # then it is initially ready for distribution.
      distribution_task.ready_for_distribution! if vso_tasks.empty?
    end
  end
```

**Comment by rutvigupta-design** [comment]
@jcq I'm curious here – do you think we should be displaying the Distribution task to users? Based on your notes here, I'm thinking: 

**Switch to Direct Docket**
- Show IHP (allow user to remove)
- Distribution task - maybe? (don't allow user to remove) 
 
**Switch to Evidence Submission**
- Show IHP (allow user to remove)
- Evidence submission window (don't allow user to remove)
- Distribution task - maybe? (don't allow user to remove) 

**Switch to Hearing**
- Schedule hearing task (don't allow user to remove)
- Distribution task - maybe? (don't allow user to remove) 


Anything else you think we should pre-populate outside of the individual/lone tasks?

**Comment by jcq** [comment]
Eep, somehow missed this until now!

Yeah, I think that makes sense; showing that it's being created but disabling the ability to remove for those seems logical.

I'll be honest, I'm not sure about IHP for Evidence Submission; the folks mentioned it in the meeting, but the logic as presented in `IntialTasksFactory` code seems to indicate it's only a thing for Direct Docket. Perhaps worth exploring a bit more with them...?

**Comment by jcq** [comment]
Some additional documentation of task-creation logic

`Appeal.create_tasks_on_intake_success!` is called by the `AppealIntake.complete!` method

```ruby
  def create_tasks_on_intake_success!
    InitialTasksFactory.new(self).create_root_and_sub_tasks!
    create_business_line_tasks!
    maybe_create_translation_task
  end
```

```ruby
  def create_business_line_tasks!
    business_lines_needing_assignment.each do |business_line|
      if business_line.nil? || business_line.name.blank?
        fail Caseflow::Error::MissingBusinessLine
      end

      next if tasks.any? { |task| task.is_a?(VeteranRecordRequest) && task.assigned_to == business_line }

      VeteranRecordRequest.create!(
        parent: root_task,
        appeal: self,
        assigned_at: Time.zone.now,
        assigned_to: business_line
      )
    end
  end
```

This logic decides whether or not to create a translation task:

```ruby
  def maybe_create_translation_task
    veteran_state_code = veteran&.state
    va_dot_gov_address = veteran.validate_address
    state_code = va_dot_gov_address&.dig(:state_code) || veteran_state_code
  rescue Caseflow::Error::VaDotGovAPIError
    state_code = veteran_state_code
  ensure
    distribution_task = tasks.open.find_by(type: DistributionTask.name)
    TranslationTask.create_from_parent(distribution_task) if STATE_CODES_REQUIRING_TRANSLATION_TASK.include?(state_code)
  end
```

And this defines the state codes that require translation task:
```ruby
STATE_CODES_REQUIRING_TRANSLATION_TASK = %w[VI VQ PR PH RP PI].freeze
```
