### ISSUE TITLE
Build internal metrics that feed into metrics that the Board's reports out

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15120]
## User story
User story: As a Caseflow team member, I need to know how Caseflow is being assessed (what metrics are being used by stakeholders), so that I know where to focus Caseflow improvement efforts (what work should be prioritized to ensure we meet stakeholder expectations).

Create dashboards to present metrics that are the same as or feed into metrics listed in [BVA's Annual Report](https://www.bva.va.gov/docs/Chairmans_Annual_Rpts/BVA2019AR.pdf).

1. Start with the first metrics reported in the PDF, presuming they are the most important.
2. Implement the easy metrics first to create a prototype and get early feedback.
3. Create separate tickets for harder-to-implement metrics.

## Acceptance criteria
- [ ] Dashboards presenting metrics that feed into metrics listed in BVA's Annual Report
- [ ] The metrics should be accessible to Caseflow team members

### Out of scope

Any metric that does not feed into metrics reported in [BVA's FY 2019 Annual Report](https://www.bva.va.gov/docs/Chairmans_Annual_Rpts/BVA2019AR.pdf).
For reference, [BVA FY2018 Annual Report](https://www.bva.va.gov/docs/Chairmans_Annual_Rpts/BVA2018AR.pdf).

### Background/context

To move toward more data-driven decision making and data democratization, we need to start measuring Caseflow and making these measurement accessible to Caseflow team members. The data will provide objective metrics to help focus our development efforts on specific features, as well monitor how feature releases affect the metrics.

BVA reports out the metrics annually. We should monitor the metrics more frequently to ensure Caseflow meets target numbers for the upcoming year.

### Other notes

Below are types of artifacts extracted from the annual report that can be counted and presented as metrics over time (at least monthly).

#### VBA
* HLR
* SC

#### CAVC
* remanded appeals that become SCs

#### BVA
* Appeal by dockets
   * ES
   * DR
   * Hearing
   * Legacy
      * Hearing

For many metrics, remember to distinguish Legacy and AMA appeals.
* decision per year and per FTE
   - FY 2019: 95k decisions; 88.3 decisions per FTE; 2% reduction in cost; 14.7% decrease in overtime cost due to significant output despite increase in overtime cases
* overtime decision per FY
* scheduled hearings per FY
   - by type: Central Office, Video, Virtual, Travel Board
   - FY 2019: 36k scheduled hearings; 22.7k held (38% increase); 68% video; 61.8k pending legacy appeals hearings (19% decrease); 11k AMA hearing requests pending at the end of FY
       - 68 virtual hearings with 97% satisfaction rate from Vets; VEText utilized
* quality review
   * accuracy (91.4% for legacy decision issues) - how was this calculated? maybe related to CAVC and US Court of Appeals remands
* IHP and VSO coordination
   * group by status: started, active/pending, completed
   - FY 2019: "reduction in Legacy Appeals Pending at Veterans Service Organizations (Original & Post Remand Appeals)"
   - FY 2019: "Significant progress was made in FY 2019 to track case inventory as it moves through both the legacy and 21 AMA processes and also with the tracking of case inventory currently residing for action with VSOs."

#### FY 2020 Goals
> The Board’s goals for FY 2020 are to adjudicate 91,500 appeals for Veterans and schedule a minimum of 36,000 hearings. FY 2020 will be a baseline year to focus on: (1) the reduction of legacy appeals; (2) holding a higher percentage of scheduled hearings; and (3) working all three dockets of AMA cases in a timely manner.

> Strengthening partnerships and accountability with VSOs: MOU will continue to support and conform activities for co-located VSOs and provide a mechanism for accountability. In addition to the MOU, the Board committed to providing regular notifications to VSOs that describe outstanding case inventory and timeliness goals.

* increase # Vets served
* increase efficiency of appeal system
* improve user experience
	* during appeal filing, hearings, decisions -- surveys sent to Vets
* better track and coordinate case movement regarding VSO and intake
	* cases pending (certified); awaiting hearing; docketed & pending
	* includes appeals, remands, non-VBA receipts, CAVC, AMA

> FY 2020 will be a baseline year to focus on: (1) the reduction of legacy appeals; (2) holding a higher percentage of scheduled hearings; and (3) working all three dockets of AMA cases in a timely manner.

* decrease legacy appeals
* increase scheduled hearings (via virtual hearings and VEText)
* work all 3 AMA dockets in timely manner

#### FY 2019 Statistics Data

See Annual Report pdf for details. Below are highlights.

> the Board receives legacy and AMA appeals simultaneously and manages four dockets: 1) legacy appeals; 2) AMA direct review; 3) AMA evidence submission; and 4) AMA appeal with a hearing request.

> -   38 U.S.C. § 7101(d)(2)(A)
>     -   Number of cases formally appealed to the Board (Substantive Appeal (VA Form 9) filed): 36,062
>     -   Number of AMA cases formally docketed by the Board (VA Form 10182): 23,849
>     -   Number of legacy appeals certified to the Board: 69,008
> -   38 U.S.C. § 7101(d)(2)(B)
>     -   Cases pending (certified) before the Board at the start of FY 2019: 137,383
>     -   Cases pending (certified) before the Board at the end of FY 2019: 120,638
>     -   (Includes certified appeals pending in the field awaiting hearings, as well as cases docketed and pending at the Board. Case receipts include original appeals, remands, non-VBA receipts, and cases returned by the CAVC. Beginning in FY 2019, this figure includes AMA cases received at the Board.)
> -   38 U.S.C. § 7101(d)(2)(D)
>     -   For legacy appeals decided in FY 2019, the average length of time between the filing of an appeal (i.e., Substantive Appeal (VA Form 9)) at the AOJ and the Board’s disposition of the appeal was 1,273 days. This total includes all decision types (original, supplemental, post remand, reconsideration, vacates, de novo, court remand, etc.).
> -   ...
> -   For AMA, the Board now maintains three separate dockets. The average days to complete those appeals from Notice of Disagreement and from Case Intake are included in the table below. ...
> -   38 U.S.C. § 7101(d)(3)(B) ...
> -   The Board set a record of 95,089 decisions dispatched in FY 2019, with 93,571 (approximately 98 percent) of those decisions occurring in the legacy system. This supported the reduction of the Board’s inventory of legacy appeals from 137,016 at the start of FY 2019, down to 98,549 appeals at the end of FY 2019 as detailed in the chart below.
> -   The Board will continue to receive new legacy appeals from VBA, VHA, and NCA as the administrations also work down legacy inventory. Estimates show the Board could receive as many as 100,000 legacy cases in FY 2020. With the exception of returned remands, initial projections indicate the Board plans to resolve its inventory of legacy appeals by the end of Calendar Year 2022.
> -   VA Operations Board Measures...
> -   Appeals Modernization Act Statistics...

**Comment by yoomlam** [comment]
- [ ] Check for relevant metrics reported by [Tableau](https://bva-tableau.va.gov).
- [ ] Replicate FY19 numbers to ensure we are counting in the same manner as BVA

**Comment by wdrougas-tista** [comment]
@yoomlam After reading annual report and comparing it to data that's been summarized here, it looks you already did a great job of pulling the useful data/metrics. I am going to ask the Foxtrot team at our next team sync if there are any metrics that they think would be useful to measure and show
