### ISSUE TITLE
Docket Change | Eng | Create DocketSwitchMailTask

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15136]
## Description
We need a new task type to designate a request to switch dockets.

## Acceptance criteria
- [ ] Add `DocketSwitchMailTask` class as subclass of MailTask
- [ ] Task actions should include "Switch Docket"
  - [ ] Add to task action constants
  - [ ] Add stub to TaskActionRepository
  - [ ] This should be available only to users in `ClerkOfTheBoard` org
- [ ] Put this behind `docket_change` feature toggle
- [ ] Update documentation: [link]

## Technical notes
Use VacateMotionMailTask as inspiration.

## Open questions
- Should this be a subclass of `MailTask`? If so, naming convention would likely lead to it being `DocketSwitchMailTask`
  - Yes

**Comment by jcq** [comment]
The default behavior of `MailTask` (and its inheritors) is to actually create two instances of the task: one for the organization (by default, `MailTeam`), and then a child task that is assigned to a user. When the user's task is completed, it would then complete the organization task.

Our desired behavior is to assign the new `DocketSwitchMailTask` to the user that is creating it, but do we want to bypass this default behavior of creating the on-hold organization task? I could certainly specify that the org task is assigned to the `ClerkOfTheBoard` organization, and it would only come into play if something happened to the child task (user goes inactive, for instance) before it is completed.

**Comment by rutvigupta-design** [comment]
@jcq follow-up question: Would the on-hold organization task appear in the `ClerkoftheBoard's` team queue/anywhere else on the "on hold" tab? Or would it be hanging out in the background – if so, how would someone "grab" it if a user were to go inactive?

**Comment by jcq** [comment]
@rutvigupta-design It looks like the default behavior is for it to show up in the "Assigned" tab for the org/team:
![Screen Shot 2020-09-11 at 12 21 28](https://user-images.githubusercontent.com/2581274/92964685-62fff700-f429-11ea-9f76-efba71148770.png)

**Comment by rutvigupta-design** [comment]
Hmmm...I think we should check with them, but _if_ I'm understanding it correctly, the value of this would be: there would be a way for someone else to grab this in case the assigned user is unavailable and also, it acts as a double-check to ensure it is completed (if my understanding is correct in that once the user completes the "Docket Switch" task, this would also get completed. 

The one trade-off I can see is it being potentially confusing to see, and users may think it's a duplicate but that may be able to be resolved via training/speaking with users.

**Comment by jcq** [comment]
Yeah — I think all of those things are true. I'd say the strongest reason to do it would be to simply have consistency with the functionality of all other tasks.

**Comment by rutvigupta-design** [comment]
I think we should check in with them and see who would see the Team View, but I also don't think (hope?) this should really bother them as long as we explain what the behavior is and why :) @mbaenatan any strong thoughts one way or another here?

**Comment by mbaenatan** [comment]
I like the default: one for ClerkOfTheBoard organization, and then a child task for the attorney processing the docket switch. On the OCB assigned tab (or Team View) it says who it is assigned to, which makes it easy to see who is working on it. I can see how this would benefit their team
