### ISSUE TITLE
Make PrepareEstablishClaimTasksJob dependency on CreateEstablishClaimTasksJob more explicit

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1513]
The daily run of `PrepareEstablishClaimTasksJob` is very dependent on `CreateEstablishClaimTasksJob` having completed first.

Right now we run `PrepareEstablishClaimTasksJob` 1 hour later than `CreateEstablishClaimTasksJob`, but I feel like this could cause issues if `CreateEstablishClaimTasksJob` takes longer than an hour, or if we change the times for some reason since the dependency isn't very explicit

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
