### ISSUE TITLE
Identify metrics for each Sprint Team

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15138]
Similar to #15120, except this story focuses on metrics originating from Caseflow members (rather than the BVA).

## User story
User story: As a Sprint Team member, I need understand which metrics are important to my Sprint Team, so that I can identify improvements (for Caseflow products my team is responsible).

Sprint Teams and associated [Ownership of Caseflow Products](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team#ownership-of-caseflow-products)

## Acceptance criteria
- [ ] List of metrics for each Sprint Team (preferably grouped by product)
- [ ] Team Delta (?)
- [x] Team Echo
   - [x] Queue
   - [x] Reader
- [ ] Team Foxtrot
   - [ ] Intake
   - [ ] Appeals Status API
- [ ] Team Tango
   - [ ] Hearings
- [ ] Team X-ray

### Out of scope

This ticket does not involve implementing the metric in a query or dashboard.

For now, focus on Caseflow products that are actively being developed.

### Background/context

For each sprint team, roadmap items should aim to improve metrics associated with the sprint team.

Sprint team metrics likely correspond or feed into metrics mentioned in #15120.

### Other notes
Design/research [discussion guide](https://docs.google.com/document/d/1Bnb6uCra0UXIPirUAaeCq0GF5iQxloFZkwe1-cK7dkw/edit#heading=h.2pg27g65dj8j) for teams to answer to come up with metrics

**Comment by yoomlam** [comment]
This may be helpful. I wrote up [Categorized Data and Metrics Needs](https://docs.google.com/document/d/12Zjmdi9Z6uMoe45VFLxvAGLCuGKmb4U3JZ98hq3iL38/edit#) as a result of investigation into [Internal Data and Metrics Needs](https://docs.google.com/document/d/1s-akZeibptmhb4HF0Z5B8GrYG4ukYI81gq0ms1d2BXQ/edit#heading=h.u47zrxgrbw1d).

**Comment by meckilabritt-navapbc** [comment]
> This may be helpful. I wrote up [Categorized Data and Metrics Needs](https://docs.google.com/document/d/12Zjmdi9Z6uMoe45VFLxvAGLCuGKmb4U3JZ98hq3iL38/edit#) as a result of investigation into [Internal Data and Metrics Needs](https://docs.google.com/document/d/1s-akZeibptmhb4HF0Z5B8GrYG4ukYI81gq0ms1d2BXQ/edit#heading=h.u47zrxgrbw1d).

The internal data and metrics needs document is insightful @yoomlam

**Comment by geronimoramos** [comment]
Hey @yoomlam,

Here are the key takeaways from the discussion with AM and HS

## **🐬 Echo metrics to track takeaways**

### Explicitly mentioned

- number of AMA and Legacy cases assigned to Inactive users
- number of colocated tasks that when completed, will be returned to an Inactive user
- number of active appeals at the Board with deceased veterans
- Support tickets from Reader bugs. This would be helpful so we could address or flag the situation before it's flagged by the Board. Put out the fire before it becomes one.
    - This might be difficult to retrieve.
    - Looking for spikes in support tickets based on category
- Capture data or be aware of case types that are not yet processed in Caseflow that are projected to arrive in large numbers or frequency based on AMA. A ranking would be helpful.
- How many attorneys and VLJs are using Caseflow out of all of them?
    - What pages are they interacting with? Most and least?
    - "If they're not interacting with a specific page, why don't we deprecate it?"
- How much time are attorneys spending in Reader? Is there adoption of the feature and who is using it? Any enhancement we can gather?
    - Which features of Reader are they using the most/least? Where might they be having issues with it?
- How much time are specific users spending in queue? For users who use queue a lot, what are their interactions? Less interested in users who don't use queue a lot.
- How many death dismissals are actually being received? (VACOLs has this at least for legacy cases)
- Where are error alerts happening frequently in team Echo features?
- Check to see if case ordering logic is still working as intended (awareness)

### Team echo leads learnings goals

- What case types are taking us the longest to complete?
- What are the trends in the number of cases dispatching, number of cases intaking, number of days it takes to complete?
- What's taking the longest to complete? IHP tasks? Decision drafting tasks?
    - Are there patterns in these cases? Such as do cases with 1,000+ documents or more issues take longer?
    - Vice versa, what are the attributes of the cases that are being done the fastest?
    - If we identify these we can flag to the Board that we should focus on the ones that move faster out the door.

### What reports do you want?

- AOD and CAVC data for ACD
- How many CAVC remands are there? How many are we holding? How many stuck in VACOLs that shouldn't be there? How long does it take them to process CAVC Remands?
- Data on granted substitutions. How many death dismissals are we closing that are getting granted substitutions currently?
