### ISSUE TITLE
Create a model for storing hearing notes on a legacy appeal

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#15155]
Connects #14857

## Description
If a hearing request type is being converted from travel board to virtual, a note may be submitted with the form. The note is intended to be viewed when a coordinator is scheduling a hearing, and it must persist until a hearing has been held, or the hearing request is withdrawn.

Create a new `HearingNote` model that will record the following details:

1. the contents of the note (`notes`)
2. the id of person who created/last updated the note (`updated_by_id`)
3. the date the note was created/updated (`created_at`, `updated_at`)
4. A polymorphic association with the appeal (`appeal_type`, `appeal_id`)

The table should have an index on the `appeal_type` and `appeal_id` columns together.

This approach will let us easily access a note and display it or make it editable in whatever context it needs to be seen.

## Out of scope
This ticket only creates the note object on the backend. Future tickets will handle displaying, editing, and saving the note on the frontend.

## Acceptance criteria
- [ ] Tests

**Comment by lund5000** [comment]
Completed in https://vajira.max.gov/browse/CASEFLOW-500
