### ISSUE TITLE
Document Viewer | Issue tags: Creating issue for the first time

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1515]
**Story**
When looking at a document, I want a quick and easy way to create a new issue tag for documents. 

## Acceptance Criteria

**Creating an issue tag for the first time**

- Validate that `Click in the box to select, or add issue(s)` is the text label above the search-in box
- Validate that when clicking in searchable dropdown, any issue tag that has not been saved primes a `Create an issue for "___"` option below it. 
- Validate that by clicking `Create an issue...` or enter/return on keyboard, that issue tag shows under Related Issues on the side menu
- The dropdown contains all of the tags in a given case
- Validate that there is a gray vertical line on the left of dropdown arrow
- Validate clicking on left side of vertical line will click into box to type in search

## Specs

- Specs for gray vertical line 24px, 13px from dropdown arrow
- Specs for tag issues should follow document list, font size 14px, 8px padding around text, grey tag is 32px height, 3px radius for corners 

## Mocks

**Creating an issue tag for the first time**

![image](https://cloud.githubusercontent.com/assets/13420618/24916930/96c560c4-1ea9-11e7-960f-c078ef6f1fdb.png)

**After an issue is added**

![image](https://cloud.githubusercontent.com/assets/13420618/24916934/9becf328-1ea9-11e7-88a8-d3af8dfc8c1a.png)

**_Note: This is an older version something the interaction of adding new issue. Ignore the tag an issue copy inside the search-in menu._** 

![no tags](https://cloud.githubusercontent.com/assets/13420618/24666192/9e4f0f7e-192d-11e7-9819-145e95acc4b9.gif)

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228309104)

## Related Story
#1437

**Comment by NickHeiner** [comment]
Is handling backend errors completely out of scope for this issue, and should be handled by #1573 instead?

**Comment by gnakm** [comment]
@NickHeiner I cannot give a 100% answer because I don't know what other backend errors could possibly happen. 

I think for this scope, it makes sense to handle all in document viewer errors as you mentioned, in issue #1573. For document list view, probably be handled with the default VMBS error in red as Artem once shared on slack.

**Comment by abbyraskin** [comment]
@NickHeiner curious if you'd recommend a different handling?

**Comment by NickHeiner** [comment]
No, that's fine, just wanted to make sure I understood the scope of each ticket properly.

**Comment by abbyraskin** [comment]
@kierachell 🙏 don't push this back for the bug noted here (basically, the search/dropdown suggests you create the tag you just created if you navigate to a new doc): https://github.com/department-of-veterans-affairs/caseflow/issues/1758

**Comment by astewarttistatech** [comment]
**FAILED**

Cannot add issue tag

Current view:
![readerissueindoc](https://cloud.githubusercontent.com/assets/23038505/25531159/cc5a20e4-2bf6-11e7-9c8c-39faba0e8fbc.gif)

**Comment by astewarttistatech** [comment]
Moving back since it was assigned to another developer

**Comment by kierachell** [comment]
The basic functionality is there, but does not fit the mocks:
- Grey line is not compliant with the specs
- Text above the dropdown/textfield is not the same as the mocks
<img width="371" alt="screen shot 2017-05-02 at 8 23 05 pm" src="https://cloud.githubusercontent.com/assets/18075411/25644593/6a4072e6-2f75-11e7-9d5e-dd2ec9f80291.png">

**Comment by tejans24** [comment]
the text is related to: #1753

**Comment by kierachell** [comment]
**PASSED**
just saw the change in 1753 :D
Nah, just saw it. np
