### ISSUE TITLE
Prevent ActiveRecord::RecordNotUnique error on appeals redistribution

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#15163]
## Description
[This](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10876/events/847792/) sentry alert uncovered an issue that in the event that a case is redistributed more than once, it will fail as as currently we are [hardcoding](https://github.com/department-of-veterans-affairs/caseflow/blob/01aae9619d26d77a3ba3b4c76c31a0260be6d6f6/app/models/tasks/schedule_hearing_colocated_task.rb#L50) the `case_id` in `ScheduleHearingColocatedTask`.  Instead, we need to update that line to dynamically assign case ids,  the most straightforward way being to inject a timestamp e.g. (case_id: "#{appeal.uuid}-attempt-#{Time.zone.now}")

## Acceptance criteria
- [ ] Update the `send_to_hearings_branch` function in `ScheduleHearingColocatedTask` to dynamically assign `case_id`

## Background/context/resources
[Sentry alert](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10876/events/847792/)
[Slack convo](https://dsva.slack.com/archives/CJL810329/p1598473658154800?thread_ts=1598027437.031200&cid=CJL810329)

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||||||
2 | |||||
3 | 
5 | 
8 | 
```

git grep -attempt-1
check in github for other things around `attempt-1`
update the bat team docs

#### Why 1?
* change something from `-1` to `-#{Time.zone.now}`

#### Why 2?
* Updating batteam wiki and githib tickets that reference attempt-1

**Comment by hschallhorn** [comment]
Updated batteam quick ref https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref/2cba4b2ee3416766776fb02baad67d2e4fa9f529
Also update https://github.com/department-of-veterans-affairs/caseflow/issues/14705#
Also updated https://github.com/department-of-veterans-affairs/caseflow/issues/14180
also pinged https://github.com/department-of-veterans-affairs/caseflow/issues/14597 to update processing script
