### ISSUE TITLE
When a hearing note is attached to a legacy appeal, it is displayed and editable in the schedule veteran form

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#15161]
Connects #14857

## Description
If a `HearingNote` object is attached to a legacy appeal, that note is displayed and editable in the schedule veteran form, as seen in [these designs](https://www.figma.com/proto/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6333%3A2104&viewport=-839%2C837%2C0.08404029160737991&scaling=min-zoom).

## Acceptance criteria
- [ ] The note is editable in the schedule veteran form
- [ ] A character count is displayed by the note text area
- [ ] The css ID of the person who last updated the note, along with the date it was edited, are displayed by the note text area
- [ ] Submitting the schedule veteran form with an edited note saves the update

**Comment by lund5000** [comment]
Completed in https://vajira.max.gov/browse/CASEFLOW-501
