### ISSUE TITLE
Reader documents list sort and search are cleared when hitting the back button

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#15173]
## Description

This issue is caused when the user sorts or filters the data in Reader, and opens a document, selects next/previous, then hits the back button. When they hit the back button, the sort parameters and search query are all reset. This only has been happening for specific users

## Acceptance criteria
- [ ] Fix the bug

## Background/context/resources

This has been reproducible on Angel's GFE and Shalanda's GFE, but *NOT* on Rubaiyat's GFE. This appears to be an environment specific bug.

One thing I noticed when shadowing Shalanda, was that going back would show the reader document list briefly, and then a full page reload would get triggered by something.

One suspicion we were investigating is whether or not it was an ordering issue with how Redux actions got processed by the reducer.

Support Ticket 1 - https://dsva.slack.com/archives/CHX8FMP28/p1597159358214900
Support Ticket 2 - https://dsva.slack.com/archives/CHX8FMP28/p1598979464112800

**Ferris has a video of this**

**Comment by ferristseng** [comment]
This could be relevant: https://stackoverflow.com/questions/46114989/link-onclick-is-causing-my-page-to-refresh

**Comment by hschallhorn** [comment]
Timeboxing to a 3

**Comment by ajspotts** [comment]
[HackMD Investigation notes](https://hackmd.io/BG87QrxfQJKpJjY4jo4WDw)

**Comment by NateMartinTista** [comment]
@ajspotts and @ferristseng I have heard that this work is no longer with Echo; do we know which team is picking up this work?

**Comment by NateMartinTista** [comment]
{caseflow-69] #comment Testing out tagging functionality

**Comment by alisan16** [comment]
🎉 Closing this ticket
https://dsva.slack.com/archives/C3AT1CRGC/p1612358371091700
