### ISSUE TITLE
Roles | Add a new Reader role

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1517]
Currently only System Admin users can access the Reader. We need to add a new 'Reader' role to give non System Admin's access.

**Acceptance Criteria**
1. Add a 'Reader' role
2. Add a link to switch to the 'Reader' role on the Test User page
3. Add a link to the Reader on the Test User page

**Comment by kierachell** [comment]
Well,
This blocks all Reader stories validation for the foreseeable future.

**Comment by kierachell** [comment]
**PASSED**
blocked us out! and then unblocked! :D
