### ISSUE TITLE
Intake | Something went wrong - intake not completing properly on submit

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15190]
## Description
This ticket is the result of a batteam support request.  There's a bug impacting a user when trying to perform an intake for a specific veteran. It's sometimes causing the Something Went Wrong error, and sometimes the Review not editable error which reflects that the claim establishment hasn't finished processing.  The intake gets cancelled or expires.

The cause of this bug is currently unknown but it may be related to zip_code related code on the veteran (according to Sentry alerts).  This ticket is for investigation and resolution.

## Acceptance criteria
- [ ] User can complete the intake

## Background/context/resources
[Slack thread](https://dsva.slack.com/archives/CHX8FMP28/p1598295178042100)

## Technical notes
The Sentry events have been aggressively grouped, but these individual events correspond to the user's intake attempts (all for the same veteran, Caseflow ID 118012):
- 2020-08-19 Intake 857849 - Events [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/24b5a178f1c0424ca366182a5bdc06a7/) & [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/b7c8b2c0bc6f490a88b838a739e74915/)
- 2020-08-21 Intake 861187 - Event [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/86ae3455107b4129a4f065e188f9ff6e/)
- 2020-08-24 Intake 863479 - Event [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/c3cd8506cc0644208fc1a4ce60359b5a/)
- 2020-08-25 Intake 865857 - Event [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/3c479fbc267c4f308c0d0d1d0a73063b/)
- 2020-08-25 Intake 865951 - Events [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/70e45ca51db247f89aabc7d9a6f08796/) & [10371](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10371/events/92eb2d47381845f3b353fe8efe19743b/)
- 2020-08-26 Intake 868254 - Event [10257](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/10257/events/2cdbe0a3655845f2bb4bf997969dcb55/)

**Comment by leikkisa** [comment]
Considering this an investigation ticket - timeboxing to a 3.

**Comment by leikkisa** [comment]
Note: this seems related to this GH issue, which is to prevent users from intaking remanded issues on regular intakes.
https://github.com/department-of-veterans-affairs/caseflow/issues/12967

**Comment by nanotone** [comment]
Here's the investigation [thread](https://dsva.slack.com/archives/C54QCEHAL/p1600705176022200) where we eventually unraveled this.

>found a stack trace from the logs:
```
NoMethodError (undefined method `[]' for nil:NilClass):
app/workflows/end_product_code_selector.rb:303:in `choose_code'
app/workflows/end_product_code_selector.rb:278:in `call'
app/models/request_issue.rb:227:in `end_product_code'
```
>this was for a request issue with contested_decision_issue_id = 111695, a rating decision issue with DTA disposition.
given these parameters to the code selector:
>- correction? no
>- remand? yes
>- remand_type: duty_to_assist
>- benefit_type: compensation
>- review_type (original): supplemental_claim
>- issue_type: rating (not relevant yet)
>i was able to reproduce that NoMethodError. it’s because the EP code selector doesn’t support SC as the original review type.

**Comment by nanotone** [comment]
Closing this ticket in favor of development on #12967, as the investigation phase is done.
