### ISSUE TITLE
More clearly indicate "virtual" docket days

### ISSUE THREAD

**Issue by lund5000** [department-of-veterans-affairs/caseflow#15196]
## User story
As a hearing coordinator, I want to see more clearly which docket days do not have a room assignment so I can be confident they're "virtual".

## Background
Currently a Hearing Coordinator would only be able to tell that a docket day is "virtual" and doesn't have a room assignment by the **_lack_** of the room label. 

_Screenshot of current state Caseflow scheduling queue UI (Tue 10/13/2020 has no hearing room assigned):_
![Screen Shot 2020-09-21 at 1.55.27 PM.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/52f194d7-0a88-4398-8295-cc57d702bfd2)

A more clear indicator would help a Coordinator know immediately how a hearing day with no room should be used (i.e. it should _not_ be used for in-person - Video or Central hearings - and instead _only be used for_ virtual hearings) and pick the right hearing day quickly.

### Business Value
Increasing the speed and accuracy with which virtual hearings are scheduled 

## Acceptance criteria
_These ACs were not initially prioritized when adding Virtual labels in #15440 and #15441 and are captured here as possible backlog items._
- If a given date has more than one "virtual" hearing day, its label should dynamically read "Virtual A", "Virtual B", etc. 
- The letter assigned to the hearing day should be consistent across all pages and components
- The options for Hearing Dates / Rooms should only show those with or without rooms based on the selected hearing type (Video/CO or Virtual)

### Design Specs
**Schedule Veteran Module:**
- When "Hearing Type" is selected as "Video":
- [ ] Under "Hearing Date" dropdown, only allow physical room options. 

**Schedule Veterans Queue Page**
On sidebar under "Available Hearing Days", if there is no hearing room next to the Hearing day (meaning the day is meant to be used for Virtual hearings), 
- [ ] add "(Virtual A)", "(Virtual B)", "(Virtual C)" etc if there are multiple Virtual hearing days with the same date

**"Postpone Hearing" Modal**
- [ ] Under "Hearing Date" dropdown, allow option to select Virtual Docket Day

**Comment by rishanava** [comment]
@nicholer 

1. I know you suggested that the "Daily Docket" page needs to be edited, but I'm not actually seeing any section where a hearing date needs to be changed (unless you go to edit the hearing day).
2. For the "Hearing Details Page" dropdown menu and the "Edit Hearing Day" module, do we want the same conditionality (_Virtual dates only for Virtual Hearings and Physical dates only for Physical (Video?) Hearings_) as for the "Schedule Hearings" module?

**Comment by nicholer** [comment]
1. If you look in the top right of the Daily Docket page, it displays the "Room number" - I wouldn't mock that up visually, but it'd be good to include in the specs so we know to confirm in QA. 
<img width="1027" alt="Screen Shot 2020-10-08 at 9 40 07 AM" src="https://user-images.githubusercontent.com/51681843/95466600-8051b380-094a-11eb-86be-53565f515d77.png">
2. I'm not seeing a way to change the Hearing Date on Hearing Details or the Edit Hearing Day modal reached from the Daily Docket. But I can see a slightly different problem, in which a Coordinator might try to change the room to Virtual after Video hearings are already scheduled to the day... I think this is pretty unlikely given the Ops Team is managing the manually created hearing days. So while we work toward longer-term changes, I'm inclined to proceed with the designs without trying to implement validation yet.
