### ISSUE TITLE
Show path to V-Drive draft IHP in case details

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15207]
## Description
As a VLJ Support user, I need the ability to view the file path for an IHP on the Case Details page, so that I can locate/navigate to the IHP quickly. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: ihp_notification
- [ ] Path is only shown vlj support team members
- [ ] Path is shown in POA section of case details if there is a path associated with the appeal and current POA on the case

## Technical notes
Now that we are storing the path to an IHP draft written by a POA, VLJ support should have access to this path on the front end.

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||||||||
5 | 
8 | 
```

display in POA details section of case details

#### Why 1?
* 

#### Why 2?
* Combination of minor front end changes, back end validations, adding to existing feature tests

**Comment by yoomlam** [comment]
POA section in case details:
![image](https://user-images.githubusercontent.com/55255674/93505479-8838ad80-f8e0-11ea-8bf7-2459cee7ec7e.png)

Add another row for the path.

**Comment by hschallhorn** [comment]
@RyanRoyUX , Any thoughts on how this link/path may look in the case details screen?

**Comment by ryanroyroy** [comment]
I was thinking that it could look like this in the POA area

![image](https://user-images.githubusercontent.com/6116023/93515428-9396d380-f8f6-11ea-8f5b-bb9e7114322b.png)
