### ISSUE TITLE
Create model to store IHP draft V-Drive path

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15206]
Associated with #14980. We need a way to store the location of a draft IHP written by a POA to be QA'd by VLJ support. This ticket is to create a new table to store this information

- [ ] Model is associated with an appeal
- [ ] Model is associated with an IHP writing VSO
- [ ] Model validates and stores properly formatted v-drive path
- [ ] TIMESTAMPS

### Open questions
- [ ] Should a IHP written by a VSO overwrite one they already wrote for an appeal?

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

Ryan will provide path string validation rules.

#### Why 1?
* 

#### Why 2?
* Add new model/table to schema

#### Why 3?
* Validation of path upon creation and update via regex (along with tests)

**Comment by hschallhorn** [comment]
Validations!

> Here is the link for Legacy Appeals:
> `V:\VBMS Paperless IHPs\AML\902`
> This link is specified by each VSO.  i.e., DAV\902, VFW\902, etc.
> Here is the link for AMA Appeals:
> `V:\VBMS Paperless IHPs\AML\AMA IHPs`
> This link is also specified by each VSO.  i.e., DAV\AMA IHPs, VFW\AMA IHPs
