### ISSUE TITLE
Spike: Investigate filtering by hearing type

### ISSUE THREAD

**Issue by lund5000** [department-of-veterans-affairs/caseflow#15203]
## Description
The new Hearing Type column will show a comma-separated list of values (e.g., "former Travel, Virtual") instead of a single value. Investigate the work needed to filter and sort this column while taking multiple values per row into account.

## Acceptance criteria
- [ ] Add notes in comments below to help the team more confidently estimate the work required to add filtering and sorting in #15058

## Background resources
The **Types** column on the Review Cases (`/queue/`) or Organization Queue (`/organizations/<org url>/`) pages can contain multiple comma-separated values (i.e. `"AOD, CAVC"`) and can be filtered by the individual values (i.e. `"AOD"` and/or `"CAVC"`). The column also has a sort control, but you only appear to be able to sort the column in descending order. This list is paginated.

The **Type** column on the Scheduled Hearings page (`/hearings/schedule/`) can contain multiple comma-separated values (i.e. `"Video, Virtual"`) and can be filtered by the individual values (i.e. `"Video"` and/or `"Virtual"`). The list cannot be sorted by the values in this column, and the list is not paginated.

This is an addition to the columns delivered in #15059

**Comment by ferristseng** [comment]
We found this is fairly easy to implement, so will follow this up with a PR for #15058
