### ISSUE TITLE
Confirmation page: Fix spacing of list items

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1522]
## **AC**
1. Verify that the second line of a list item indents to start under the first line.
1. Verify that the second line of a list item does not wrap under the check box.

## **Mocks**
_Current:_
<img width="426" alt="screen shot 2017-04-10 at 6 06 02 pm" src="https://cloud.githubusercontent.com/assets/4975959/24884652/68377382-1e18-11e7-913c-108c5be8d16b.png">

_Desired:_
<img width="503" alt="screen shot 2017-04-10 at 6 05 14 pm" src="https://cloud.githubusercontent.com/assets/4975959/24884621/4732cb5a-1e18-11e7-8550-4f0959ff48d0.png">

**Comment by kierachell** [comment]
Seems like this was already fixed
<img width="701" alt="screen shot 2017-05-11 at 9 20 38 am" src="https://cloud.githubusercontent.com/assets/18075411/25951278/2c4e892a-362b-11e7-83c1-a2d4b3dfda5e.png">

**Comment by kierachell** [comment]
<img width="384" alt="screen shot 2017-05-11 at 9 25 48 am" src="https://cloud.githubusercontent.com/assets/18075411/25951463/d41a6070-362b-11e7-9393-545b207376eb.png">
