### ISSUE TITLE
CAVC Remand: Add New CAVC Remand Section to Case Details

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15227]
## User or job story
User story: As a Caseflow user, I need specific CAVC data to be visible on the Caseflow UI, so that I have the information I need to complete my task. 

## Acceptance criteria
- [ ] Verify new section is created in Case Details called CAVC Remand that displays the following information stored via the court order entry form: 
  - Court docket: {Number}
  - Attorney representation: {Yes/No}
  - Name of Judge: 
  - Procedure: 
  - Type: {JMR or JMPR}
  - Court's decision date: {Date} 
  - Judgement date: {Date}
  - Mandate date: {Date} 
- [ ] Verify the stored information is displayed on the new appeal's case details page
- [ ] Verify CAVC Remand is displayed in side navigation
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

##### CAVC Remand section on case details page of new appeal stream
The data collected from intaking the Court order
![CAVC Remand sections](https://user-images.githubusercontent.com/49766982/93273952-f315a780-f76d-11ea-8454-7d7b88635d34.png)

"Tentative" indicates that field may be blank.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||||
5 | 
8 | 
```


#### Why 3?
* Basic work; nothing too new
* UI Testing (Jest? Storybook?)
* would be a two, but I'm rusty on FE work
