### ISSUE TITLE
Add notes field to form for converting a legacy appeal travel board hearing request to a virtual hearing request

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#15225]
Connects #14857

## Description
In #15157, we created a form for converting a legacy appeal travel board hearing request to a virtual hearing request, and in #15156, we added backend actions to handle submission of that form.

Add a textarea to this form for recording notes, as seen in the design and image below, and add the backend actions needed to save the note (to the model described in #15155).

## Out of scope
- displaying and making editable the submitted note is handled in #15161 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `notes-when-converting-hearing-request-type`
- [ ] display the textarea for writing notes
- [ ] save the contents of the note to a `HearingNote` when the form is submitted
- [ ] update Storybook and jest tests

## Design
[Figma link](https://www.figma.com/proto/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6333%3A2394&viewport=-839%2C837%2C0.08404029160737991&scaling=min-zoom)

![Screen Shot 2020-09-10 at 10.21.02 AM.png](https://images.zenhubusercontent.com/5f3586a328d3864508355291/c2b0800c-9de1-4140-ad8b-c48fb70942ef)

**Comment by lund5000** [comment]
Migrated to https://vajira.max.gov/browse/CASEFLOW-502
