### ISSUE TITLE
Investigate missing remand reason error when adding to MTV stream

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#15224]
## Description
When a user tries to add a remanded issue to a vacate stream, sometimes they get a `Remand reasons are missing for a remanded issue` error on the "Submit Draft Decision" page.

## Background/context/resources
This error message was seen twice in a Bat Team shift, although they may not necessarily originate from the same root cause.
[INC12451877](https://dsva.slack.com/archives/CHX8FMP28/p1599771108200600) - [Sentry event](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/11217/events/e7f0201f3cc94154a7abdbab8158a492/) (e7f0201f3cc94154a7abdbab8158a492)
[INC12629231](https://dsva.slack.com/archives/CHX8FMP28/p1599858232223300) - [Sentry event](https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/11217/events/1e07f961241747e4a5da51e8627822dd/) (1e07f961241747e4a5da51e8627822dd)

## Technical notes
The file that throws this error: `app/models/concerns/issue_updater.rb` (L98)
Where case review updates the record in Caseflow: `app/models/attorney_case_review.rb` (L38)

**Comment by leikkisa** [comment]
Just adding that during the regular judge checkout flow, remand reasons come up as the next page after the user adds decision issues and clicks continue (if an issue has a remanded disposition).

![Screen Shot 2020-09-22 at 3.22.32 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/cd60d1a2-0cd5-40de-b12b-8a1b95d9e84e)

**Comment by mikesanford** [comment]
Hi @leikkisa .  Is there any update on the status of this?  Unfortunately these cases are just sitting and can't be moved to dispatch because of this issue.  Thanks!

**Comment by leikkisa** [comment]
Moved to engineering ticket: #15425
