### ISSUE TITLE
Capture CAVC Document Types in Reader

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15238]
## User or job story
User story: As a Caseflow user who has access to view documents for a case, I need Reader to be able to determine what the CAVC document types are and display them labeled appropriately, so that I can easily distinguish CAVC documents in the appellants file

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: CAVC_Remand
- [ ] This feature should be accessible to the following user groups: Any user who has access to view an appellants documents (POA, VLJ, Attorney, VLJ Support, Litigation Support, etc.) 
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]
- [ ] CAVC documents are displayed in Reader with a label and not displayed as "other" 

### Background/context

There are three types of CAVC Documents that we appear to already be capturing in Reader based on the Master Document Type Categories [62328-.Master.Document.Type.Categories.06052018.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/5225136/62328-.Master.Document.Type.Categories.06052018.xlsx): 

CAVC Decision
Remand BVA or CAVC
CAVC Hold Sheet

**Comment by araposo-tistatech** [comment]
@geronimoramos @mbaenatan I've created this ticket, but based on having the "CAVC Decision" Type in the Master Document Type spreadsheet I believe we already capturing these documents. Any chance we can have this confirmed by Litigation Support? Do they have an example case they've uploaded these documents on? Even though the case will be completed in Caseflow my assumption would be we are still capturing uploads on the appellants file and can view them in Reader.

**Comment by mbaenatan** [comment]
@araposo-tistatech From the list support team:

We upload to VBMS any documents directly related to the argument and order the court made but none of the administrative documents. These include:

- The order itself (either Memorandum Decisions or Orders)
- Appellant’s (opening) Brief (if applicable)
- Appellee’s Brief (if applicable)
- Appellant’s Reply Brief (if applicable)
- Any joint motions for remand or termination (if applicable)
- Any documents pertaining to the Death of the appellant (e.g. Notification of death, Death Certificate, or Reply to Court order to show cause) (if applicable)

All documents are combined into one document that is uploaded with the Subject “CAVC-Litigation Materials“ and Document Type “Appeals: CAVC Decision” which shows up in VBMS as “CAVC Decision.”

Does this help?

**Comment by araposo-tistatech** [comment]
@mbaenatan that is where I pulled my thoughts from. Since it uploads into VBMS as "CAVC Decision" I believe we are already capturing this in Reader, but I was just looking for some confirmation by the Litigation Support team if it was possible.

**Comment by mbaenatan** [comment]
@araposo-tistatech we can ask on Thursday

**Comment by araposo-tistatech** [comment]
Confirmed by Board users CAVC Decision type is displaying in Reader, closing: 

![Reader_CAVC Decision](https://user-images.githubusercontent.com/59883609/93614410-1a53bb00-f9a0-11ea-897c-a12879dd2059.png)
