### ISSUE TITLE
Confirmation: Adjust spacing between cases assigned copy and button

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1523]
## **AC**
Verify that there are 30px between the 'x cases assigned, y completed' copy and the 'Establish next claim' button at the bottom of the Confirmation page.

## **Mocks**

_Current:_
<img width="513" alt="screen shot 2017-04-10 at 6 17 44 pm" src="https://cloud.githubusercontent.com/assets/4975959/24884967/077e1904-1e1a-11e7-9291-2bff0df939e8.png">

_Desired:_
<img width="569" alt="screen shot 2017-04-10 at 6 20 00 pm" src="https://cloud.githubusercontent.com/assets/4975959/24885043/59b16faa-1e1a-11e7-8e40-fa805a1d09b9.png">

**Comment by lakohl** [comment]
@gnakm flagging you bc this seem like a style guide issue?

**Comment by gnakm** [comment]
@lakohl Thanks! I'll add this spec into the existing issue. #1090

**Comment by astewarttistatech** [comment]
@mmlumba could you take a look at the spacing found in UAT currently?

Current View: 
<img width="1019" alt="screen shot 2017-05-08 at 11 25 43 pm" src="https://cloud.githubusercontent.com/assets/23038505/25834435/d5b2a7c2-3445-11e7-933b-328eb86ce7c4.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Go to Dispatch as a caseworker
2. Go through the happy path flow 
3. On the success page, validate the spacing in inspector (of the browser) between the button and cases assigned/completed against the specs in the AC. 

Screenshots: 
<img width="1398" alt="screen shot 2017-05-10 at 9 28 56 am" src="https://cloud.githubusercontent.com/assets/23038505/25901131/c35831e0-3563-11e7-9012-7ae6e48db29f.png">
