### ISSUE TITLE
New task type (Mail Team): 90 Day Letter Correspondence

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15239]
## User or job story
User story: As a Mail Team user, I need to be able to create a new task on a CAVC Remand case, so that when I receive correspondence from an appellant I can send the correspondence to the CAVC Litigation Support Team. 

## Acceptance criteria
- [x] Please put this work behind the feature toggle: cavc_remand
- [x] This feature should be accessible to the following user groups: Mail Team
- [x] Other conditions:
  - [x] `CavcTask` is open
  - [x] Appeal is a cavc remand
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: CAVC Remand
- [x] ~Task is child of CAVC task~
- [x] Verify "Add New Task" link is displayed on the appeal case details page
- [x] Verify Select Correspondence Type drop down includes CAVC Correspondence
- [x] Verify the new task 'CavcCorrespondenceTask' is routed to the CAVC Litigation Support team
- [x] Verify `CavcRemandProcessedLetterResponseWindowTask` status does not change. #15288

## Open questions
- [ ] With the assumption that the correspondence is NOT related to the response window and is just standard mail, what task actions should the `CavcCorrespondenceTask` have?

### Designs

![image.png](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/c41971c3-16be-457d-8350-2fdedde0557d)

### Technical notes

This could possibly be similar to the Evidence Submission Task as they are both timed responses.

**Comment by hschallhorn** [comment]
It sounds like the mail team is not going to to be reading any correspondence about cavc cases.
Instead, if they receive mail related to a cavc case, they want to just send the mail directly to the cavc lit support team by creating a new task. If this is a response to the 90 day letter, the cavc team can be in charge of deciphering that and completing the 90 response window task and moving the case forward.

So the mail team should not be able to manually complete this task, nor have any actions for this task, nor should it be assigned to them.

**Comment by geronimoramos** [comment]
@hschallhorn yes! no actions on the Mail team end except to add new mail item task to send it to lit support, and that's it for the mail team. They may not decipher the document(s) but they may look for identifiable information to look up in the system to see the status (CAVC Remand) which will let them know 'oh this needs to go to Lit Support for further processing'

Lit support will be responsible for closing the 90-day response window task

**Comment by araposo-tistatech** [comment]
@geronimoramos please verify I've captured the new requirements correctly.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

 Work:
       * create CavcCorrespondenceTask class (with MailTask parent) with default available actions
       * for the Mail Team, include task action that creates CavcCorrespondenceTask under CavcTask


#### Why 2?
* New mail task type that basically follows existing mail task subclasses

#### Why 3?
* New unit and feature tests
* First instance of logic determining if a mail task should be included in list of available tasks

**Comment by geronimoramos** [comment]
> With the assumption that the correspondence is NOT related to the response window and is just standard mail, what task actions should the CavcCorrespondenceTask have?

This one is tricky. I'm thinking CAVC lit support will want the 90-day timer to time out or wait for correct correspondence so they might want to continue to keep it on hold. Could they send the task back to the mail team and continue the hold? @mbaenatan thoughts?

**Comment by mbaenatan** [comment]
Based on discussion, we will move forward with default actions for mail tasks 
<img width="325" alt="Screen Shot 2020-11-12 at 4 06 38 PM" src="https://user-images.githubusercontent.com/65979678/99104470-e0fd8d00-2595-11eb-82e6-4466b8546b1b.png">
