### ISSUE TITLE
Confirmation: Remove vet ID from Success Message

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1524]
We show the veteran Name and ID at the top of the page, so it is redundant to restate it. 
The copy under the Success message was changed the last time we reorganized this page, however the copy update was not incorporated.

## **AC**
1. Verify that the Vet ID is removed from the Success message.
1. Verify that the copy under the word 'Success' reads as follows:
> [First Name MI Last Name's] claim has been processed. 
You can now establish the next claim or return to your Work History.

## **Mocks**
_Current:_
<img width="687" alt="screen shot 2017-04-10 at 6 26 27 pm" src="https://cloud.githubusercontent.com/assets/4975959/24885367/13901164-1e1c-11e7-842a-ee53c3408b46.png">

Desired:
<img width="887" alt="screen shot 2017-04-10 at 6 33 51 pm" src="https://cloud.githubusercontent.com/assets/4975959/24885416/488aef38-1e1c-11e7-96ae-6d3c74b859ba.png">

**Comment by lakohl** [comment]
In the event there are no more cases left in the queue, the message would show as follows:
> Joe Snuffy's claim has been processed.
You can now close Caseflow or return to your Work History.

<img width="581" alt="screen shot 2017-05-08 at 4 24 40 pm" src="https://cloud.githubusercontent.com/assets/4975959/25823721/ea76f4c8-340a-11e7-89b9-4ea0a8837360.png">

*you would also see the Way to Go! + emojis at the bottom

**Comment by mmlumba** [comment]
Original AC for 2:

> [First

 Name Last Name's] claim has been processed.

**Comment by lakohl** [comment]
@mmlumba At the top of the page (currently in the header) do we show the middle initial, or just the first and last name?

**Comment by mmlumba** [comment]
@lakohl we also show the middle initial in the header:
![screen shot 2017-05-09 at 1 37 38 pm](https://cloud.githubusercontent.com/assets/4773320/25864240/ba8cb150-34bc-11e7-8e8d-5e03813e47e5.png)

**Comment by lakohl** [comment]
Ok. Then you can show it in the Confirmation page copy as well. We should try to be consistent.

**Comment by astewarttistatech** [comment]
Based on the AC above,

**PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Access Dispatch as a caseworker
2. Go through the happy path of establishing an EP
3. Verify the Success page doesn't show the Veteran ID

Screenshots: 
<img width="1433" alt="screen shot 2017-05-10 at 8 09 01 am" src="https://cloud.githubusercontent.com/assets/23038505/25898461/3e99df70-355a-11e7-8c57-d795675c916c.png">
