### ISSUE TITLE
Intake | Docket Change | Eng | Set up Frontend Context/State Stubs

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15258]
## Description
In order to lay the groundwork for future frontend work for docket change, this will set up stubs/skeleton into which future tickets will plug for managing necessary state

## Acceptance criteria
- [ ] Update documentation: [link]

## Background/context/resources
- [MTV checkout context](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/mtv/checkout/MotionToVacateContext.js)
- [MTV checkout flow container](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/mtv/checkout/MotionToVacateFlowContainer.jsx)

## Technical notes
While the MTV checkout flow used [React Context API](https://reactjs.org/docs/context.html) for state, one could also choose to use Redux store if that makes more sense. (If using Redux, prefer hooks rather than the `connect` HoC.)

**Comment by leikkisa** [comment]
Closing this issue (this work will be handled in other tickets).
