### ISSUE TITLE
Help: header, URL

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1525]
Header should show the appropriate application name.
Determine URL pattern for Dispatch and Certification.

**Comment by slj** [comment]
We haven't gotten anywhere with this during the last 1.5 sprints, either it's been solved elsewhere or this simply isn't a priority.

**Comment by slj** [comment]
Confident that this will resurface in due time.

**Comment by lakohl** [comment]
@slj we should solve this, or the portions that were not addressed by: https://github.com/department-of-veterans-affairs/caseflow/pull/1656

**Comment by joofsh** [comment]
Spoke with @lakohl and it looks like this has been addressed. Closing
