### ISSUE TITLE
Format and style document list table for Reader

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1527]
- [x] Verified that the document list table styling is updated to look like the Mocks show below

**Comment by tejans24** [comment]
<img width="1003" alt="screen shot 2017-04-12 at 4 39 53 pm" src="https://cloud.githubusercontent.com/assets/1976755/24978596/38f16e06-1f9f-11e7-87dd-89a90e5ce00c.png">

**Comment by NickHeiner** [comment]
This work overlaps with #1274, because both are updating the Categories column. Now I'm having merge issues and it looks like @tejans24 and I duplicated effort.

**Comment by kierachell** [comment]
What am I validating here? There's no _Issue Tags_ to add here.
<img width="1035" alt="screen shot 2017-04-14 at 7 59 45 pm" src="https://cloud.githubusercontent.com/assets/18075411/25058918/f3fe64fc-214c-11e7-9705-3faeff8a1bc4.png">

**Comment by tejans24** [comment]
This needs to be validating that the table shows up with the correct styling and has the right columns.

**Comment by kierachell** [comment]
Which columns are right? Which columns are wrong? Should the **Issue Tags** column be so narrow?

What does "right" styling mean? Two lines for header is right or wrong (i.e. **Receipt Date**)? Is the arrow next to **Document Type** right or wrong? Should the **Document Type** links be bold until clicked?

**Comment by gnakm** [comment]
The spacing should follow this mockup from issue #1538
I adjusted the specs to accommodate for long Document Type Titles. 

![image](https://cloud.githubusercontent.com/assets/13420618/25135729/25019dea-2421-11e7-80b4-8aeddb360076.png)

- The header column should not be double lined. 
- The Icon next to Document Type is incorrect. It should be the same as the one used in Receipt Date
- The Document Type links being bold is correct assuming that they represent that they were not open by the user (regular = read/ bold = unread)

**Comment by tejans24** [comment]
There is a separate issue for formatting the table column widths: https://github.com/department-of-veterans-affairs/caseflow/issues/1538

**Comment by kierachell** [comment]
**PASSED**
<img width="1015" alt="screen shot 2017-04-19 at 2 34 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/25196041/61088bc2-250d-11e7-9875-c281c0abcf03.png">
