### ISSUE TITLE
New Organization: CAVC Litigation Support Team

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15278]
## User or job story
User story: As a Litigation Support team member who only works on CAVC cases, I need my own separate queue in Caseflow, so that I do not work or see any tasks that do not pertain to CAVC. 

## Acceptance criteria
- [ ] Include screenshot(s) in the Github issue if there are front-end changes, showing new org
- [ ] Update documentation: https://github.com/department-of-veterans-affairs/caseflow/wiki/Organizations
- [ ] New organization added to Caseflow for CAVC Litigation Support Team

### Background/context

Not all users in the Litigation Support team work all tasks. As the team that only works CAVC cases has never migrated to Caseflow we will want to include them as a new organization so they are not inadvertently assigned tasks they are not authorized to work or vice versa. 

### Other notes
![image](https://user-images.githubusercontent.com/49766982/94203025-9b64f380-fe73-11ea-9b1e-52efd7c23e5a.png)

**Comment by araposo-tistatech** [comment]
@geronimoramos created this ticket, feel free to update if the team name is incorrect.

**Comment by hschallhorn** [comment]
Be sure to call `CavcLitigationSupportTeam.singleton` in prod after deployed to create the team!

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||||||||
3 | 
5 | 
8 | 
```

#### Why 1?
* Create a new empty org with no tasks/actions? ok

#### Why 2?
* Verification in prod

**Comment by yoomlam** [comment]
Each org/team has an associated url. What should the url for this new team be? My initial guess is `cavc-lit-support`
```ruby
=> #<CavcLitigationSupport:0x00007fdc7803a9d8
 id: 30,
 accepts_priority_pushed_cases: nil,
 created_at: Mon, 19 Oct 2020 14:07:24 UTC +00:00,
 name: "CAVC Litigation Support",
 participant_id: nil,
 role: nil,
 status: "active",
 status_updated_at: nil,
 type: "CavcLitigationSupport",
 updated_at: Mon, 19 Oct 2020 14:07:24 UTC +00:00,
 url: "cavc-lit-support">
```

**Comment by yoomlam** [comment]
Added bullet to https://github.com/department-of-veterans-affairs/caseflow/wiki/Organizations#existing-organizations
