### ISSUE TITLE
New task type: Extension request task

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15287]
## User or job story
User story: As a Litigation Support user, when I Send to VLJ for Extension Request grant/denial via the CavcRemandProcessedLetterResponseWindowTask, I need a new task to be created for the VLJ so that they can take action on the request.  

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: cavc_remand
- [ ] This feature should be accessible to the following user groups: VLJs
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: CAVC 
- [ ] Verify extensionrequesttask is created when Litigation Support clicks submit on the modal for "send to VLJ for Extension Request grant/denial" via the 90 day letter response mail task
- [ ] Verify extensionrequesttask is child task of ExtensionRequestWindowTask
- [ ] Verify the extensionrequesttask is assigned to VLJ who originally decided on the case or DVC Scharnberger if the VLJ is no longer active.
- [ ] Available Actions: 
- Mark Task Complete - Completes extensionrequesttask

### Background/context

The first extension request can be granted or denied by the CAVC Litigation Support Team Organization for either approval or denial. The second request (and up) must be send to the VLJ who ruled on the original decision or DVC Scharnberger should the VLJ no longer be active.

**Comment by geronimoramos** [comment]
This is scoped down correct? No longer handling this process in Caseflow for now.

**Comment by araposo-tistatech** [comment]
@geronimoramos correct, this is being pulled out and reworked to its own epic.

**Comment by mbaenatan** [comment]
Ticket will be part of separate judge extension request epic work along with #15322 and #15323
