### ISSUE TITLE
Allow CAVC Litigation Support Users to Add Issues on newly created appeal

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15289]
## User or job story
User story: As a CAVC Litigation Support user, I need the ability to add issues on a CAVC case that the Board may not have captured in the original decision, so that the new issue can be decided on. 

## Acceptance criteria
- [ ] This feature should be accessible to the following user groups: CAVC Litigation Support
- [ ] Link should only appear if there is an active `CavcTask`
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: CAVC Remand
- [ ] User is routed to the Edit Issues page in Caseflow intake
- [ ] VBMS records are created as needed

**Comment by geronimoramos** [comment]
https://www.loom.com/share/06902bb5bd614f228fe32d6660fe6e34 @araposo-tistatech @hschallhorn

**Comment by araposo-tistatech** [comment]
> https://www.loom.com/share/06902bb5bd614f228fe32d6660fe6e34 @araposo-tistatech @hschallhorn

Totally agree with the easier path of just adding the modal to the button, but I feared it would not write back to VBMS and I know going through Intake does. Do you have any information around this @hschallhorn does it matter if the add issues goes through Intake or not?

**Comment by geronimoramos** [comment]
It's also probably worth noting -- in this instance, we may want to provide a `remove` link button in case they want to remove the issue they added at this point in time.

**Comment by lomky** [comment]
As it stands, in Queue the Decision Review (Appeal) needs to already exist to create a new Request Issue. To avoid re-implementing Caseflow Intake, we should instead of having the button here, we instead have helper text instructing the user to add any new issues on the next step (the Case Details page of the newly created appeal)

Work Becomes:
 - add helper text to CAVC Remand page
 - give CAVC Lit Support Org access to Issue Editing on the newly created appeal

Possible reasons we want to actually do this full lift: adding novel issues is actually common.

@geronimoramos do we have any insight into how often they need to add new issues?

**Comment by geronimoramos** [comment]
@lomky don't have a definitive metric for frequency but based on user interviews it was leaning more towards occasionally and not rarely. CAVC will at times tell the Board to add a new issue to the new appeal stream.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||||
3 | |||||
5 | 
8 | 
```

Concern around connection to VBMS? Reusing existing add/edit issue page _should_ cover everything we need here

Update only the Case Details page. The work is simply enabling the "Correct Issues" link for CAVC Litigation Support users, if there is an open CavcTask.

Where we determine if the link appears to users on the front end: https://github.com/department-of-veterans-affairs/caseflow/blob/16b2ece727da946de7d47449b630eaef353b7533/client/app/queue/CaseDetailsView.jsx#L128-L132

on the back end: https://github.com/department-of-veterans-affairs/caseflow/blob/16b2ece727da946de7d47449b630eaef353b7533/app/models/serializers/work_queue/appeal_serializer.rb#L40-L42

#### Why 2?
* Can most likely add a permission check to allow lit cavc member to see "Add issues" on case details.

#### Why 3?
* Room for any potential issues with CAVC being a new-ish addition
* (manual) testing unfamiliar intake flows
* Checking VBMS
