### ISSUE TITLE
Make CavcRemandProcessedLetterResponseWindowTask available when CavcCorrespondenceTask is created

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15288]
## User or job story
User story: As a Litigation Support user, I need the CavcRemandProcessedLetterResponseWindowTask to be available again when the mail team receives correspondence pertaining to a CAVC case, so that I can continue to process the case. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: cavc_remand
- [ ] This feature should be accessible to the following user groups: Litigation Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: Cavc Remand
- [ ] Verify the task is assigned to the CavcLitigationSupportTeam
- [ ] Verify when the Mail team creates a CavcCorrespondenceTask task the CavcRemandProcessedLetterResponseWindowTask status is updated from on-hold to active 
 

### Designs

![image.png](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/38db71ee-e7c4-4198-ba5a-5db620c26379)

**Comment by araposo-tistatech** [comment]
@geronimoramos since we are no longer creating a task for the mail team anymore (as they will be creating a task for themselves, what will prompt this one to be removed from on hold? Or will the CAVC Litigation Support team be responsible for moving this from on hold to active depending on what the correspondence is? I'm thinking this ticket may no longer be necessary depending on your response.

**Comment by hschallhorn** [comment]
CavcCorrespondenceTask created by the mail team may not be a response to the cavc letter and should not change the status of the CavcRemandProcessedLetterResponseWindowTask
