### ISSUE TITLE
Reformat the document list table header for Reader

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1528]
- [x]  Header is refactored to another react component
- [x]  Header looks similar to the mocks provided for Reader

**Comment by astewarttistatech** [comment]
@tejans24 is the header referenced in this ticket, the Caseflow Reader header from issue #1287 ?

**Comment by tejans24** [comment]
@astewarttistatech No, this is the header for Document List table

**Comment by astewarttistatech** [comment]
@tejans24 do you have any information on this header? Any mocks? Any description as to what it looks like? Any tickets that reference it elsewhere? This is too vague to test.
