### ISSUE TITLE
Add smart date population of judgement and mandate dates for CAVC remands

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15283]
## Description
Many CAVC remands will have the same date for decision, mandate, and judgement date. To speed up user input, we should assume these dates are the same most of the time by
1. Pre-populating mandate and judgement date when a decision date is entered
1. Providing a checkbox to hide/show the mandate and judgement date fields

S/O to whoever popularized the "billing address is the same as shipping address" UX

## Acceptance criteria
- [ ] Form autofills Mandate and Judgement date with Decision date when user enters a decision date (regardless of the state of the following check box)
- [ ] If Mandate or Judgement date have already been entered, do not change their values when decision date is changed, unless the following box is checked.
- [ ] Form defaults checkbox that hides/shows mandate and judgement date to checked

## Background/context/resources
- Designs -> https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=891%3A0

## Design
<img width="333" alt="Screen Shot 2020-11-12 at 1 40 07 PM" src="https://user-images.githubusercontent.com/45575454/98982035-c0c5c380-24ec-11eb-83c9-c0bc83a7f292.png">
<img width="438" alt="Screen Shot 2020-11-12 at 1 41 34 PM" src="https://user-images.githubusercontent.com/45575454/98982077-cc18ef00-24ec-11eb-8676-08ea437df4f3.png">

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | ||||
5 | 
8 | 
```

Front end only, no backend 
Right now: three separate date fields.
Wanted: Hide the two behind a checkbox 'same as decision date'; if box is checked and we have decision date, fill that date in as the other two fields values

Use existing Storybook item (courtesy of Alec).

#### Why 2?
* Only frontend changes
* Adding a few Checkbox components, fudging around with local state

#### Why 3?
* Testing various UI scenarios
* Updating storybook

**Comment by lomky** [comment]
Code to being implementing this!

```
diff --git a/client/app/queue/AddCavcRemandView.jsx b/client/app/queue/AddCavcRemandView.jsx
index cc2f8bc94..f18bc3c1e 100644
--- a/client/app/queue/AddCavcRemandView.jsx
+++ b/client/app/queue/AddCavcRemandView.jsx
@@ -79,6 +79,7 @@ const AddCavcRemandView = (props) => {
   const [type, setType] = useState(CAVC_DECISION_TYPES.remand);
   const [subType, setSubType] = useState(CAVC_REMAND_SUBTYPES.jmr);
   const [decisionDate, setDecisionDate] = useState(null);
+  const [judgementSelection, setJudgementSelection] = useState(true);
   const [judgementDate, setJudgementDate] = useState(null);
   const [mandateDate, setMandateDate] = useState(null);
   const [issues, setIssues] = useState({});
@@ -198,7 +199,13 @@ const AddCavcRemandView = (props) => {
           styling={alertStyling}
           lowerMargin />}
       <h3>{COPY.CAVC_JUDGEMENT_DATE_HEADER}</h3>
-      {subType === CAVC_REMAND_SUBTYPES.jmr &&
+      { <Checkbox
+        label={COPY.CAVC_JUDGEMENT_DATE_DESC}
+        name="judgement-decision-date"
+        vertical
+        value={judgementSelection}
+        onChange={(val) => setJudgementSelection(val)} /> }
+      {subType === CAVC_REMAND_SUBTYPES.jmr && judgementSelection
       <>
         <h4 {...labelStyling}>{COPY.CAVC_JUDGEMENT_DATE}</h4>
         <DateSelector

```

Add back with `git apply`, hit enter, paste in, hit ctrl-d
