### ISSUE TITLE
Create new CavcRemandProcessedLetterResponseWindowTask type

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15309]
## Description
As a Litigation Support user, when I complete a SendCavcRemandProcessedLetterTask, I want a new task to be created and placed on hold, so that I have something to indicate that I am awaiting a response from the appellant. 

## Acceptance criteria
- [ ] New task type CavcRemandProcessedLetterResponseWindowTask
- [ ]  When a SendCavcRemandProcessedLetterTask is completed, a CavcRemandProcessedLetterResponseWindowTask is created
   - [ ] As a child of the CavcTask
   - [ ] Assigned to the CavcLitigationSupportTeam
   - [ ] Is put on hold for 90 days by creating a child timed hold task
   - [ ] Give task action of "End hold early" while task is on hold
   - [ ] After 90 days, the task should come off hold and show up in the CAVC team's unassigned tab tab to be assigned/acted upon  

## ~Open~ Resolved questions
1. Should this automatically close? (If yes, put on hold ala [EvidenceSubmissionWindowTask by including TimeableTask and implementing when_timer_ends and timer_ends_at]( https://github.com/department-of-veterans-affairs/caseflow/blob/34b3fb4c0e676b05c8a824293e0666d5b2872735/app/models/tasks/evidence_submission_window_task.rb#L8-L18)) If so, what happens when the 90 day window expires (goes to distribution, new "no response" task, etc)? 
**NO**
1. Instead, should this pop back up as "assigned" and actionable after 90 days? (if yes, put on hold ala no show hearing tasks, where they are [automatically created with a timed hold task](https://github.com/department-of-veterans-affairs/caseflow/blob/7adbc4bdb0e06b0741e9576d0c682a4a40ae6b92/app/models/tasks/no_show_hearing_task.rb#L8-L18)
**YES**

## Background/context/resources
When a user completes a SendCavcRemandProcessedLetterTask to indicate that they have sent out the 90 day letter to the veteran notifying them that their remand has been processed, the veteran has 90 days to respond to the letter on how they would like to proceed. A CavcRemandProcessedLetterResponseWindowTask should be opened and put on hold for 90 days when a SendCavcRemandProcessedLetterTask is completed

Task actions will be added in #15324 

## Technical notes
![image.png](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/d3f4d5f0-2c66-442b-b129-f7d51d10abcf)

**Comment by hschallhorn** [comment]
@geronimoramos Mind 👀 ing the open questions here?
 

> ### Open questions
> 1. Should this automatically close? (If yes, put on hold ala EvidenceSubmissionWindowTask by including TimeableTask and implementing when_timer_ends and timer_ends_at) If so, what happens when the 90 day window expires (goes to distribution, new "no response" task, etc)?
> 1. Instead, should this pop back up as "assigned" and actionable after 90 days? (if yes, put on hold ala no show hearing tasks, where they are automatically created with a timed hold task

**Comment by geronimoramos** [comment]
@hschallhorn woops could have been more specific!

So when the 90-day window expires, the case can pop back into the team's unassigned queue for proper assignment and further processing from a CAVC lit support user. They will still want to review their options to either mark the task complete (and send to case distribution, most likely) or whatever other actions. Does this answer the question? 😬

**Comment by hschallhorn** [comment]
>Does this answer the question

Yes! Perfect! Thanks!

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | ||||
5 | 
8 | 
```

Once hold is completed/cancelled, user doesn't have any task actions (yet -- see other ticket).

#### Why 2?
* Well defined task on hold pattern from noshowhearingtask
