### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1531]
We should consider using yarn instead of npm. 

# Acceptance Criteria
* See the using `yarn` to install dependencies locally produces a working dev environment.
* See that deploys to AWS environments work.

# Benefits

*Note*: these benefits compare our current version of npm, `3.10.10`, to Yarn. The latest version of npm may have substantial improvements.

## Performance
Both of these tests were run while tethering on my EOP iPhone.

Test command: `[master] $ rm -rf node_modules && npm install`
(With populated cache)

| npm install time |
| --- |
| `1m5.530s` |
| `0m51.923s` |
| `0m52.691s` | 
| `1m20.948s` |

**[95% confidence interval:](https://www.wolframalpha.com/input/?i=65.5,+51.9,+52.6,+80.9)** `41s` to `84.4s`
(assuming Gaussian distribution)

Test command: `[master] $ rm -rf node_modules && yarn`
(After creating `yarn.lock` and with populated offline cache.)

| yarn install time |
| --- |
| `14.76s` |
| `13.85s` |
| `15.28s` | 
| `15.05s` |

**[95% confidence interval:](https://www.wolframalpha.com/input/?i=14.7,+13.9,+15.3,+15)** `14.135s` to `15.315s`
(assuming Gaussian distribution)

## Offline mode
Yarn can do offline installs. npm cannot.

## More deterministic locking
Yarn's `yarn.lock` contains more information than `npm-shrinkwrap.json`, and thus produces a more deterministic dep tree where all devs are guaranteed to get the same content.

## More mergeable lockfile
`yarn.lock` is not JSON, so diffs that modify it are smaller than diffs that modify `npm-shrinkwrap.json`. This makes merging easier.

## Vets.gov consistency
Vets.gov uses Yarn. It would be nice if we were all on the same stack.

## Stability
npm has a bunch of weird bugs. I've observed it hanging indefinitely while trying to do installs.

We've seen CI failures from intermittent npm checksum errors, like this:

```
npm ERR! shasum check failed for /tmp/npm-7028-d07481a1/registry.npmjs.org/sinon/-/sinon-2.4.1.tgz
npm ERR! Expected: 021fd64b54cb77d9d2fb0d43cdedfae7629c3a36
npm ERR! Actual:   ed5204c05d3b7b3fef737c7820276c325def2ae4
npm ERR! From:     https://registry.npmjs.org/sinon/-/sinon-2.4.1.tgz
```

### Other npm problems we've encountered
* https://github.com/npm/npm/issues/18770
* https://github.com/npm/npm/issues/18722

Yarn may not suffer from this bug.

# Other Considerations
Yarn is API-compatible with npm, so it should continue to work fine with our CI. We will need a bit more investigation to ensure that this is the case. We also will need to ensure that `yarn` is available on Travis and Jenkins.

~~We are not going to migrate `npm-shrinkwrap.json` to `yarn.lock`, so we'll need to fix #1530 before we do this.~~

**Comment by askldjd** [comment]
No problem with this. Just need to test it against our npm caching server (sinopia). If it works, great. If it doesn't, we can find a caching server that is compatible with Yarn.

**Comment by joofsh** [comment]
No problem from me either. As long as this works with our npm caching server, this should be feasible. I'd love to get rid of the npm shrinkwrap file 👍

**Comment by kierachell** [comment]
**PASSED**
lower env deploys have worked so far, let's ship it.
