### ISSUE TITLE
Create Modal for send to VLJ for Extension Request grant/denial

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15323]
## User or job story
User story: As a litigation support user, I need to send a hyperlink or path to the extension draft letter to the VLJ, so that they can locate the document quickly to grant or deny the request. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: cavc_remand
- [ ] This feature should be accessible to the following user groups: Litigation Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: cavc
- [ ] Verify modal appears with the following fields when "Send to VLJ for Extension Request grant/denial" is clicked
  - field for extension request document path or hyperlink
  - field for task instructions 
- [ ] Verify hyperlink or path is stored

### Designs

[Link to designs
](https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=1470%3A3474)

### Technical notes

We are creating a similar modal for IHP tasks [here](https://docs.google.com/spreadsheets/d/1xvGJkgfHvD1BgGgrTNQylr7uCCPdOOuN5qtd9fo-iJM/edit?ts=5f69173c#gid=683425496&range=A6)

**Comment by mbaenatan** [comment]
Ticket will be part of separate judge extension request epic work along with #15287 and #15322
