### ISSUE TITLE
Discuss pushing appeals status updates to Vets.gov with the Appeals Status API

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1532]
Vets.gov and the intake team agree that the single biggest improvement to the appeals status experience would be if we could push appeals status updates to Vets.gov, allowing Vets.gov to send an SMS or email to the Veteran when the status of their appeal changes. We'd love to collect some brainstorm-level thoughts from the team about that possibility. 

Note that this is not part of any currently planned workstream as it's likely to be a much bigger engineering lift than our current scope and it's not an MVP feature for the Appeals Status API.

- is this something we would want to take on only after we replicate VACOLS in AWS?
- are there common patterns we could follow for this? 
- what tools would we look into?
- what pitfalls/dangers should we be aware of?

Rough ideas: We'd need to 
- get appeals status changes out of VACOLS
  - a nightly job that queries to find a list of appeals in each status bucket? 
- figure out how to send that info to Vets.gov
   - some sort of pub/sub?
   - Vets.gov could poll daily for updates on an `/appeals-status-changes` endpoint?
   - would we send over the entire list of appeals or just the changes?
   - we could cache yesterday's results in Redis, diff them with today's results, and send only the 
    changes?

**Comment by NickHeiner** [comment]
I'm happy to be part of this discussion, but I think it would be most productive to do it as a synchronous session.

One pitfall off the top of my head: my last company, Opower, had a lot of outbound communications. There were several incidents in which code that was not properly tested resulted in elderly people in Massachusetts receiving IVR calls every 15 minutes from 11pm to 6am the next day.

**Comment by amprokop** [comment]
@NickHeiner — yep, sorry if I didn't make that clear. The pattern that I've seen work well is:

1. make a github discussion issue
2. ask people to read and think about it and add comments asynchronously to get juices flowing
3. if there's no clear group consensus from async input (for anything complicated there will likely not be), have a synchronous discussion at some point in the future to discuss everyone's input

what do you think of that approach?

**Comment by NickHeiner** [comment]
I think that works well in general. For me, I'm still missing a lot of context, and I think it would be tough to get it asynchronously. But we don't need to do a sync session just for me.

**Comment by askldjd** [comment]
My take on this:

 - Setup vets.gov and Appeals VPC peering so they can talk to us without having to open up public endpoints
 - Vets.gov polling Appeals with `GET /appeals-status-changes?time=123` once a day sounds fine to me.
 - I don't have much thought on caching strategy yet without knowing the traffic pattern. I pinged @J-Quag for daily/hourly traffic earlier, so hopefully the data can give us some guidance.

It is a bit difficult to determine the design without knowing VACOLS' performance on these queries. Do we know how long it takes to determine a single status? And is the runtime linear as number of statuses  in a single query goes up?

**Comment by shanear** [comment]
@amprokop in an ideal world, there should be an endpoint we could send a "veteran notification" to, and it would be responsible for determining how to send that notification to the veteran.

That endpoint/service needs to do many things we don't currently do (maybe vets.gov does?):
- send emails
- send SMS messages
- has veterans' contact info and prefered contact method

Once we have that endpoint build, deciding how we interact with it seems like the easy part.

**Comment by sharonwarner** [comment]
Do the appeal status changes come from VACOLS? What's writing the status changes? Do we have enough control over that process to send push notifications instead of polling for current statuses? 

I'm not sure what AWS services we're allowed to use, but I've done something similar to this in the past and used AWS's SQS. It was really easy to set up. 

https://aws.amazon.com/sqs/

**Comment by laurjpeterson** [comment]
I think this issue is very outdated, so I'm going to close it.
