### ISSUE TITLE
Create ExtensionRequestWindowTask upon creation of Extensionrequesttask

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15322]
## User or job story
User story: As a Litigation Support user, I need a new task to be created & placed on hold when I send an extensionrequesttask to a VLJ, so that I have something to indicate the VLJ has made their decision on granting or denying the extension request and prompt me to mail the letter to the appellant. 

## Acceptance criteria
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]
- [ ] Verify ExtensionRequestWindowTask (Child task) is created when Litigation Support clicks submit on the "send to VLJ for Extension Request grant/denial" modal via the 90 day letter response mail task
- [ ] Verify Assigned to the CavcLitigationSupportTeam
- [ ] Verify task is placed on hold
- [ ] Verify when the Extensionrequesttask is complete ExtensionRequestWindowTask status is updated from on-hold to active
- [ ] Verify the following actions are available on the task: 
  - Mark task complete - sends case to case distribution
  - Place task on hold - indicates letter was sent & extension request was granted

**Comment by mbaenatan** [comment]
Ticket will be part of separate judge extension request epic work along with #15287
