### ISSUE TITLE
Add Actions to CavcRemandProcessedLetterResponseWindowTask

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15324]
## User or job story
User story: As a Litigation Support user, I need actions to be available on the CavcRemandProcessedLetterResponseWindowTask, so that I can add actions if applicable or complete the task. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: cavc_remand
- [ ] This feature should be accessible to the following user groups: Litigation Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: Cavc Remand
- [ ] Verify the actions drop down has the following available: 
- Mark task complete
  - Closes self and parent to be ready for distribution
- Add admin action
  - FOIA - sent to privacy team
  - Translation - sent translation team 
  - Missing Hearing Transcripts - sent to hearing branch
  - AOD - sent to AOD team
~~- Put task on hold - opens current on hold modal~~ 
- Extension request ~~(visible if it is the first request)~~ 
~~- Send to VLJ for Extension Request grant/denial - (visible upon second request, would need to check for 1st extension request) workflow outside of this ticket~~
- Send to Hearings team 
  - Opens schedule hearing task (auto opens parent hearing task under distribution task) 
  - Closes self & parent
- Send to VSO
  - Creates IHP task under distribution task for VSO on file (existing task) 
  - Closes self & parent

### Designs

![image](https://user-images.githubusercontent.com/49766982/98177190-f5af9600-1eae-11eb-95b4-9cb735407f86.png)

**Comment by araposo-tistatech** [comment]
@geronimoramos @mbaenatan to confirm we no longer want the user to place this task on hold for any reason?

**Comment by mbaenatan** [comment]
@araposo-tistatech @geronimoramos Correct, MDRs get placed on hold. At this point for JMR/JMPR, the equivalent of a hold would be an extension request that they would want to track
