### ISSUE TITLE
Intake | Docket Change | VLJ action drop down 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15335]
## User or job story
As a VLJ, I should be able to see a "Rule on docket switch" action in the action dropdown menu so I can review and rule on the docket switch request

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] Any VLJ assigned a `Docket Switch Ruling` task should have access to this
- [ ] The assigned VLJ should see the following actions (listed alphabetically): Cancel task, Put task on hold, Re-assign to a judge, Rule on docket switch
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Out of scope

VLJ ruling screen

### Designs

![13  Switch Docket_ Judge Action Drop-down](https://user-images.githubusercontent.com/51714306/95501224-958c0980-096d-11eb-8a8d-32817d7a1fe1.png)

### Background/context

Judges need a way to initiate ruling on a docket switch task. 

### Resources/other links

[End-to-end Figma file](https://www.figma.com/file/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=770%3A7036)

**Comment by leikkisa** [comment]
Closing as a story ticket, engineering handled in another ticket.
