### ISSUE TITLE
Intake | Docket Change | VLJ queue

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15334]
## User or job story
As a VLJ, I should receive the assigned docket switch case (via a Docket Switch Ruling task) in my personal queue so that I can review and rule on a docket switch request.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `ClerkOfTheBoard` organization
- [ ] The assigned VLJ should receive a `Docket Switch Ruling` task once an attorney submits their recommendation.
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Out of scope

- Task instructions will be handled separately

### Designs

![12 0 VLJ receives task in queue](https://user-images.githubusercontent.com/51714306/95500519-85bff580-096c-11eb-865f-ce47b1a636c4.jpg)

### Resources/other links

[End-to-end Figma file](https://www.figma.com/file/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=770%3A0)

**Comment by leikkisa** [comment]
Story ticket, currently we don't think engineering is needed (baked into existing functionality).

**Comment by leikkisa** [comment]
Closing as a story ticket, engineering already handled.
