### ISSUE TITLE
Intake | Docket Switch | VLJ ruling view

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15336]
## User or job story
As a VLJ, I want to be able to see the docket switch recommendation from the Office of the Clerk of the Board so I can review and rule on the docket switch request

## Acceptance criteria
- [x] Please put this work behind the feature toggle: `docket_switch`
- [x] This feature should be accessible to the following user groups: `VLJ`
- [x] When a VLJ selects "Rule on Docket Switch", they are taken to this screen
- [x] At the top of the screen, they see instructions and information (summary, timeliness, recommendation, hyperlink) from the attorney - please format according to the design below
- [x] Please format the information from the attorney based on the design (bolded labels, line-break and 24px space after each section)
- [x] If the URL is a valid URL, please make it clickable
- [x] The user can select their ruling via the radio buttons (grant all issues, grant a partial switch, deny all issues) and this will trigger either a `Denied Docket Switch` or `Granted Docket Switch` task 
- [x] The user can enter in text in the hyperlink field - this is an optional field, and they don't need to enter in a valid hyperlink (e.g. they could write in: "sent via email") 
- [x] The user can enter in context or instructions via the notes field 
- [x] The user can assign this to a ClerkOfTheBoard attorney - it defaults to the user that assigned the task to them, and they should see all attorney members of the `ClerkOfTheBoard` organization as options (VLJ's excluded)
- [x] All fields except the hyperlink field are required
- [x] Include screenshot(s) in the Github issue if there are front-end changes
- [x] Add storybook story
- [x] Add jest test
- [x] Add to rspec feature test for happy path
- [ ] Update documentation: [link]

### Out of scope

Attorney task instructions - the ruling, hyperlink, and context fields from the VLJ ruling screen will be saved as task instructions for the attorney

### Designs

**VLJ Ruling Screen** 
![14. Switch Docket_ Rule on request.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/6a6582f5-e0c9-4bc8-8e89-25093ecf50eb)

### Technical notes
Use `RecommendDocketSwitchForm` and `RecommendDocketSwitchContainer` as inspiration. Like those, this should use `react-hook-form` and `yup` for form management & validation.

Adding email to copy can be done with Markdown + COPY.JSON

### Resources/other links

[End-to-end Figma file](https://www.figma.com/file/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=770%3A6081)

**Comment by leikkisa** [comment]
![Screen Shot 2020-11-09 at 6.18.52 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/1c84b95c-977c-4b81-9600-0517737b67a2)
