### ISSUE TITLE
Update PushPriorityAppealsToJudgesJob Alert

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15339]
## User or job story
User story: As a DVC, I need to see a breakdown of distributed & non-distributed cases after the PushPriorityAppealstoJudgesJob is run, so that I can see how the cases were distributed. 

## Acceptance criteria
- [ ] Update the PushPriorityAppealsToJudgesJob Alert in Slack to include:
  - Total number of appeals awaiting distribution
  - Total number of cases distributed
	- Number of cases tied to judges distributed
	- Number of general population cases distributed
	- Number of AOD cases
	- Number of CAVC cases
  - Total Number of appeals not distributed
	- Legacy cases tied to VLJs without judge teams
	- AMA cases tied to VLJs without judge teams
	- Number of AOD cases
	- Number of CAVC cases
- [ ] Add the above data to Datadog or any other reporting area the Board has access to

**Comment by yoomlam** [comment]
Preliminary [HackMD notes](https://hackmd.io/ZtC_VlmkSmmva7wP29fTtA) in preparation for meeting with the Board regarding the report.

**Comment by araposo-tistatech** [comment]
Per John, Tableau will be absorbing this report, closing.
