### ISSUE TITLE
Intake | Docket Switch | Receive VLJ ruling 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15338]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board, I should receive the VLJ ruled docket switch case in my personal queue so that I can take the appropriate action

## Acceptance criteria
- [x] Please put this work behind the feature toggle: `docket_switch`
- [x] This feature should be accessible to the following user groups: `ClerkOfTheBoard` organization
- [x] Assigned user should receive a `Denied Docket Switch` or `Granted Docket Switch` task based on the VLJ's ruling in their queue
- [x] Task instructions (from the VLJ) should be formatted as (nothing needs to be bolded, add line breaks after the ruling and signed ruling letter) - please see the design for more context: 
  - [x] I am proceeding with a [full switch/partial switch/denial].
  - [x] Signed ruling letter: [insert hyperlink/text here] - if this is a valid hyperlink, please make this clickable
  - [x] [Context/instructions]
- [x] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Out of scope

Steps after receiving the task (the flow is different for a grant vs a denial)

### Designs

**Example of task instructions**
![17  Granted Docket Switch task received](https://user-images.githubusercontent.com/51714306/95916126-cdc88900-0d6d-11eb-8739-ef4218192cf8.png)

### Resources/other links

[End-to-end Figma link](https://www.figma.com/file/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=770%3A0)

**Comment by leikkisa** [comment]
![Screen Shot 2020-11-13 at 7.55.12 AM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/d3d34426-407a-4728-a022-80e63c4685da)

**Comment by leikkisa** [comment]
To be combined with another issue, complete by PR #15594
