### ISSUE TITLE
Intake | Docket Change | Send recommendation to judge 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15332]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board, I should be able to see a "Send to judge" action in the action dropdown menu so I can send my recommendation with relevant information 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `ClerkOfTheBoard` organization
- [ ] Once a user has added a Docket Switch mail task, they should be able to see an action drop-down with the following actions (listed alphabetically): Assign to person, Assign to team, Cancel task, Put task on hold, Send to judge
- [ ] Selecting "Send to judge" should trigger the recommendation page
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Out of scope

The recommendation page that an attorney would use to send a docket switch recommendation to a judge.

### Designs

![9  Switch Docket action selected](https://user-images.githubusercontent.com/51714306/94729072-ca251300-0326-11eb-9971-831da52ba3b4.png)

### Background/context

After a OCB user has created a Docket Switch mail task, they need to be able to send this to a judge to review. This action will allow them to do so. 

### Resources/other links

[Figma file](https://www.figma.com/proto/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=560%3A1859&viewport=594%2C-438%2C0.32505378127098083&scaling=min-zoom)
[End-to-end Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1601042285247/0e921ee1c3286b3cc4ecaeb5298399b71d51bbe0)

**Comment by leikkisa** [comment]
This will be completed by PR #15341
