### ISSUE TITLE
Add parent task validation to task classes

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15349]
Motivated by [Kat's PR comment](https://github.com/department-of-veterans-affairs/caseflow/pull/15304/files#r496234858)

## Description
Add parent task validation to task classes (typically on task creation).

Currently we have code comments or wiki documentation that describes where a new task is expected to attached in a task tree. It would be great if we can enforce these expectations using validation code.

Example: For the `parent` field, call the built-in `PresenceValidator` then call the custom `ParentTaskValidator` with argument `DistributionTask` when the record is being created:
https://github.com/department-of-veterans-affairs/caseflow/blob/0cf9233c331314e5af61a0884b0a642110d7740a/app/models/tasks/cavc_task.rb#L9-L10

May have to add to `ParentTaskValidator` so that it:
* checks `appeal_type` to cause different validations for AMA vs. Legacy appeals;
* allows multiple task types for the parent task
* checks parent task's `status`
* checks parent task's `assigned_to_type`

## Acceptance criteria
- [ ] More use of `ParentTaskValidator` to enforce data integrity and task tree structure expectations

## Background/context/resources
Resources to determine parent-child task relationships
* [Task Overview](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md)
  - For example, to check `JudgeAssignTask`, navigate to [JudgeAssignTask_User](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/JudgeAssignTask_User.md), then click on the 3 links: "Task stats [for DR](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-DR/JudgeAssignTask_User.md), [for ES](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-ES/JudgeAssignTask_User.md), [for H](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-H/JudgeAssignTask_User.md) dockets." Note that all `JudgeAssignTask_User` have the `RootTask` has their parent task type for all 3 dockets. 
* Frequent Parent-Child Relationships for [DR](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-DR/freq-parentchild.md), [ES](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-ES/freq-parentchild.md), [H](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/docs-H/freq-parentchild.md) dockets for AMA appeals
* Use Rails query to create a table like this except with percentages:

|  | child_type | parent_type | count |
| --- | --- | --- | --- |
| 0 | AbstractMotionToVacateTask | VacateMotionMailTask | 1 |
| 1 | AddressChangeMailTask | AddressChangeMailTask | 27 |
| 2 | AddressChangeMailTask | RootTask | 16 |
| 3 | AddressVerificationColocatedTask | AddressVerificationColocatedTask | 813 |
| 4 | AddressVerificationColocatedTask | AttorneyRewriteTask | 1 |
| ... | ... | ... | ... |
| 288 | UnaccreditedRepColocatedTask | JudgeDispatchReturnTask | 1 |
| 289 | UnaccreditedRepColocatedTask | UnaccreditedRepColocatedTask | 46 |
| 290 | VacateMotionMailTask | RootTask | 26 |
| 291 | VacateMotionMailTask | VacateMotionMailTask | 50 |
| 292 | VeteranRecordRequest | RootTask | 552 |

(From [Jupyter Notebook](https://ip-10-247-40-83.us-gov-west-1.compute.internal:3000/view/on_host/_welcome/4-Network%20Graphs.html))

## Technical notes
Below are some initial finding.

These tasks have the listed parent task type 100% of the time:
- DistributionTask: RootTask
- JudgeAssignTask: RootTask
- JudgeDecisionReviewTask: RootTask
- AttorneyRewriteTask: JudgeDecisionReviewTask

These tasks can have one of the listed parent task types 100% of the time::
- InformalHearingPresentationTask: DistributionTask or RootTask

These tasks can have one of the listed parent task types _almost_ 100% of the time:
- HearingTask: DistributionTask except for 3 out of 14k cases
- ScheduleHearingTask: HearingTask except for 1 out of 14k cases
Perhaps fix the exceptional cases then apply validation, or simply apply the validation for future task creations.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||
3 | |||
5 | 
8 | 
```

This ticket covers all of the 'just add one line' tasks where this validation is a drop in. For more complicated ones where changes to the validation are required, file a new ticket.

Will need to add testing, however will be very similar to tests written in the referenced ticket from the description

#### Why 1?
* 

#### Why 2?
* Potentially just a one line addition for each task type
* Mimic testing used in PR #15304

#### Why 3?
* Quantity of changes
* Some further investigation and confirmation

**Comment by hschallhorn** [comment]
> These tasks can have one of the listed parent task types almost 100% of the time:
> - HearingTask: DistributionTask except for 3 out of 14k cases

`HearingTask`s also appear on legacy appeals and will not have a parent
