### ISSUE TITLE
Remove VLJ assignment requirement from AMA Hearing Cases

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15343]
## User or job story
Job story: When the priority case distribution job runs, AMA hearing cases do not need to be tied to the VLJ who held the case, but rather have an "affinity" for the attorney, so that the priority case distribution job distributes cases evenly. 

## Acceptance criteria
- [ ] Verify AMA hearing cases are not required to go back to the VLJ who held the hearing
- [ ] Verify even distribution of cases is higher priority then the affinity of assigning AMA hearing cases to the VLJ who held the hearing
- [ ] This feature should be accessible to the following user groups: VLJs

### Background/context

"Affinity" means that it is desired, but not legally necessary, for the appeal to go to a certain VLJ/AVLJ. For legacy and AMA, it is preferred that non-hearing post-remand appeals go to the A/VLJ that signed the last remand. For legacy and AMA, it is preferred that non-hearing CAVC appeals go to the VLJ that signed the decision that went to CAVC. For AMA, it is preferred that hearing cases go to the VLJ that presided over the hearing. The only requirement is that legacy hearing cases go to the VLJ that presided over the hearing, unless the VLJ is no longer with the Board and the appellant has waives her/his right to a new legacy hearing.

**Comment by hschallhorn** [comment]
How we currently determine "affinity": https://github.com/department-of-veterans-affairs/caseflow/blob/55b1e7c184adb9147195a5158f526964c5436c29/app/queries/hearing_request_distribution_query.rb#L76-L80

A case becomes "genpop" if the judge the case is "tied" to has not logged in for 60 days

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||
5 | |||
8 | 
```

Disregard prior constraint of the number of days (for judge-tied cases) must past before trying to distribute to another judge.

#### Why 1?
* 

#### Why 2?
* Job already exists, just adding additional logic

#### Why 3?
* Unfamiliarity with ACD job
* ACD is a tricky bit of code

#### Why 5?
* Simulate and verify desired results
* Bumped up due to ACD testing being hard

**Comment by yoomlam** [comment]
Caseflow is tying AMA cases with held hearing to VLJs: 
https://github.com/department-of-veterans-affairs/caseflow/blob/55b1e7c184adb9147195a5158f526964c5436c29/app/queries/hearing_request_distribution_query.rb#L32-L34

**Comment by araposo-tistatech** [comment]
Represented in Jira as [CASEFLOW-89](https://vajira.max.gov/browse/CASEFLOW-89)

**Comment by yoomlam** [comment]
Affinity is removed by PR #16326
