### ISSUE TITLE
How should we handle Appeal not found?

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1535]
Today we found a situation where the BFKEY in VACOLS for an appeal had changed underneath our feet. It was test veteran in prod, but it still blew up the missing decisions page.

We might want to handle that error more gracefully. Or invalidate tasks with no Appeal in VACOLS.

## Acceptance Criteria
- Validate that when you delete a case record in VACOLS for an unprepared task, the missing decisions page doesn't crash.

Related: https://github.com/department-of-veterans-affairs/caseflow/issues/1256

**Comment by kierachell** [comment]
Oooh, sounds fun. I can do that!

**Comment by kierachell** [comment]
**PASSED**
```
2017-04-18 15:13:59 -0400]   EstablishClaim Load (1.6ms)  SELECT "tasks".* FROM "tasks" WHERE "tasks"."type" IN ('EstablishClaim') AND "tasks"."id" = $1  [["id", 310]]
=> #<ActiveRecord::Relation [#<EstablishClaim id: 310, appeal_id: 217, type: "EstablishClaim", user_id: nil, assigned_at: nil, started_at: nil, completed_at: nil, completion_status: 8, created_at: "2017-04-18 16:07:36", updated_at: "2017-04-18 19:09:11", lock_version: 2, comment: nil, outgoing_reference_id: nil, aasm_state: "completed">]>
```
I changed the `BFKEY` for an unassigned task and it was skipped, yay.
