### ISSUE TITLE
Fix priority logic for appeals with aod motions for distributions

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15352]
## Description
Now that AOD motions should be associated with an actual appeal (#14085), we need to adjust the logic for what we consider priority for distributions. This is still looking for motions associated with the claimant that were created after the appeal was established. https://github.com/department-of-veterans-affairs/caseflow/blob/aec6a6a130402ca04a9330adbc60a70547af9005/app/models/docket.rb#L106-L113

## Acceptance criteria
- [ ] Priority ama appeals are pulled for distribution ONLY if one of the following are true
  - [ ] `aod_based_on_age` is true on the appeal
  - [ ] The claimant's dob is over 75 years ago
  - [ ] The claimant has a granted age base aod motion 
  - [ ] The appeal has a granted aod motion associated with the appeal
  - [ ] The appeal is a cavc remand (not yet implemented)
- [ ] Scope is created for appeal model that captures all this with no N+1 queries (should only produce one db call if possible)

## Notes
The first 3 AC have a lot of overlap. What should we consider as our source of truth as I assume we don't want to check all 3?

**Comment by yoomlam** [comment]
Blocked and deprioritized -- see https://github.com/department-of-veterans-affairs/caseflow/issues/13175#issuecomment-703618092
