### ISSUE TITLE
Intake | Check that user has access level to view veteran on Edit page

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15350]
## Description
Currently, if the user does not have the sensitivity level to view a veteran's information when they try to visit the "Edit" page for a veteran, they are getting "Something went wrong" instead of an Access error.

## Acceptance criteria
- [ ] Check if the user has access to view the veteran's record when navigating to Edit, send them to a separate page with a message that they don't have access to view the veteran's information.

## Background/context/resources
Sally to add screenshot with existing copy

## Technical notes
- This is checked during Intake during validation when starting an intake, but is not checked in the validation that happens prior to editing a claim.
- Here's the [related intake feature spec](https://github.com/department-of-veterans-affairs/caseflow/blob/a7322c51c6995eeab7e94df5bc1b07364513d8d2/spec/feature/intake/intake_spec.rb#L194)

**Comment by leikkisa** [comment]
@leikkisa & @rutvigupta-design to add more AC

**Comment by leikkisa** [comment]
@leikkisa Find example batteam thread.

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1684
