### ISSUE TITLE
Fix priority logic for appeals with aod motions for appeal attribute caching

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15353]
## Description
Now that AOD motions should be associated with an actual appeal (#14085), we need to adjust the logic for what we consider priority for cached appeal. This is still looking for motions associated with the claimant that were created after the appeal was established. https://github.com/department-of-veterans-affairs/caseflow/blob/00c4a75a58c07c9849517167a3ef102164ca70f8/app/jobs/update_cached_appeals_attributes_job.rb#L238-L247

## Acceptance criteria
- [ ] Cached appeals are marked as AOD ONLY if one of the following is true
  - [ ] `aod_based_on_age` is true on the appeal
  - [ ] The claimant's dob is over 75 years ago
  - [ ] The claimant has a granted age base aod motion 
  - [ ] The appeal has a granted aod motion associated with the appeal
  - [ ] The appeal is a cavc remand (not yet implemented)
- [ ] Query is written so no N+1 queries (should only produce one db call if possible for alllllllll appeals)
- [ ] Job is benchmarked before and after changes to ensure we have not blown up an already long job runtime

## Notes
The first 3 AC have a lot of overlap. What should we consider as our source of truth as I assume we don't want to check all 3?

## Background/context/resources
Related: #15352

**Comment by yoomlam** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||
5 | |||
8 | 
```

Performant caching involves writing efficient SQL.

#### Why 3?
* This job is known to fail (see #appeals-job-alerts) due to other problems.

#### Why 5?
* Non-trivial SQL queries
* Ensure we're not introducing unnecessary additional querying

**Comment by yoomlam** [comment]
Blocked and deprioritized -- see https://github.com/department-of-veterans-affairs/caseflow/issues/13175#issuecomment-703618092
