### ISSUE TITLE
Edit EP Claim Labels | Confirmation Modal

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#15369]
## User or job story
User story: As a VBA Intake user, I need a way to review the old and new claim label I just edited so that I can confirm my selection. 

## Acceptance criteria
- [x] Please put this work behind the feature toggle: [edit_ep_claim_labels]
- [x] The user sees the confirmation modal once they click "continue" after selecting a new claim label
- [x] Please add in copy based on the attached design
- [x] The user sees the original claim label in the field "Previous label: x"
- [x] The user sees the new claim label in the field "New label: y"
- [x] If the user cancels, close the modal and clear any data related to editing the claim label
- [x] Make a storybook story for this component
- [x] Add jest test
- [x] Include screenshot(s) in the Github issue

### Out of scope

- Steps before or the success banner after
- Handling submit

### Designs

![6. Confirmation modal.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/def77c6c-11d4-4b53-b9ec-8cd54dafb949)

**Comment by leikkisa** [comment]
![Screen Shot 2020-11-23 at 4.58.04 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/0b6f5c3f-f8b5-4399-9c20-eb9650988f0b)
