### ISSUE TITLE
Spike: Investigate Create New Appeal Stream

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15366]
## Description
For CAVC Remands we will be creating new appeal streams. Let's investigate and document the work needed to implement creating new appeal streams. 

## Acceptance criteria
- [ ] Create documentation on how to create new appeal streams
- [ ] Add documentation to #14792

**Comment by ajspotts** [comment]
Investigation findings [here](https://hackmd.io/mLXFsygJThW9Rd8i5T2a6w)

**Comment by ajspotts** [comment]
Implementation [ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/14792) has been estimated to closing this
