### ISSUE TITLE
Edit EP Claim Labels | Show error if editing the claim label was unsuccessful 

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#15378]
## User or job story
User story: As a VBA Intake user, I need to stay on the Edit Issues page if the claim label was not edited successfully, so I can be prompted to try again or submit a YourIT ticket. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [edit_ep_claim_labels]
- [ ] If the claim label is NOT edited successfully, the user remains on the Edit Issues page once they confirm editing the claim label
- [ ] The user sees an in-line red error banner below the claim label row
- [ ] Please add copy in the banner based on the attached design
- [ ] Include screenshot(s) in the Github issue

### Designs

![7. Save banner.jpg](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/05e951d3-24d9-4f4c-a4b5-713a21a32249)

**Comment by wdrougas-tista** [comment]
This is blocked currently, moving back
