### ISSUE TITLE
Add MDR to CAVC Entry Form

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15384]
## User or job story
User story: As a CAVC Litigation Support user I need the ability to identify an MDR was received on the CAVC Remand entry form so that I can initiate the MDR process. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: mdr_cavc_remand
- [ ] This feature should be accessible to the following user groups: CAVC Litigation Support Team
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: CAVC Remand
- [x] Verify Memorandum Decision on Remand (MDR) is a radio button on the CAVC entry form
- [x] Verify clicking the MDR radio button presents confirmation banner under the Court Decision Date picker with the following copy: "Choosing MDR will set a 90-day hold on this case starting from the Court’s decision date listed above. The hold is to wait for the Court’s judgement and mandate. This remand case will be accessible in the On Hold tab and will return to the team’s Unassigned tab when the 90-days are over."
- [x] Verify Confirmation modal is presented on users queue page upon clicking submit on the entry form with the following copy: 
"You have successfully created a CAVC Remand case 
This has generated an MDR task in your teams On Hold tab and will return to the unassigned tab after 90 days from the court decision date"

## Release notes

The CAVC Litigation Support team is now able to enter CAVC MDRs into Caseflow. 

### Designs
https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=882%3A302

**Comment by lomky** [comment]
**Info box on MDR selection**
![image](https://user-images.githubusercontent.com/6129479/103581015-2dd05680-4ea9-11eb-8c11-13b9c513737b.png)

**New Success detail**
![image](https://user-images.githubusercontent.com/6129479/103580950-1729ff80-4ea9-11eb-84b7-f73f44c1b0dc.png)
