### ISSUE TITLE
Document list | Specs for Column Spacing

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1538]
**Story**

As a developer, I want to know the spacing between each column so that the column headers do not create a double line. 

## Acceptance Criteria
- Validate that spacing matches the pixels shown in the mock below
  - Categories: 106 px
  - Receipt Date: 116px
  - Document Type: 226px
  - Issue tags: 225px
  - Comments: 85px
  - 16 px from far left and far right
  - Spacing between Categories and Receipt Date: 25px
  - Spacing between Receipt Date and Document Type: 25px
  - Spacing between Document Type and Issue Tags: 35px
  - Spacing between Issue Tags and Issue Comments: 25px
- Validate that table line length is 900px
- Validate that all everything on row is top aligned with first set of row of issue

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25135680/089116fe-2421-11e7-8d40-4886853accc6.png)

**Comment by NickHeiner** [comment]
@gnakm I didn't see this when I did #1800, and that kinda addressed this. Can you take a look at what the app currently looks like and tell me if you'd still like changes made?

The mockup is also currently inaccurate because it's missing the last read indicator column.

**Comment by gnakm** [comment]
@NickHeiner At this point, the mock we had above is totally outdated because we changed canvas size. I think what we currently have is better!
