### ISSUE TITLE
Fix display of hearing time and line height of helper text on schedule veteran

### ISSUE THREAD

**Issue by sahalliburton** [department-of-veterans-affairs/caseflow#15393]
## Description
UI bugs found during dogfooding for [schedule veteran workflow](https://hackmd.io/vxIlpnKgR9OSWdM3txDa2Q?view):

**Helper Text Line Height**
Steps to reproduce:
1. Follow [Scenario F](https://hackmd.io/vxIlpnKgR9OSWdM3txDa2Q?view#Scenario-F-Select-hearing-time-from-dropdown)
1. On the Case Details page, select the “Schedule Veteran” option from the Actions dropdown to open the Schedule page

Actual behavior: 
Help text line height on Veteran Email and POA Email fields is large

Desired behavior: 
Help text line height is same as on Hearing Details

**Hearing Time dropdown**
Steps to reproduce:
1. Complete steps 1-3 from Scenario A with https://appeals.cf.uat.ds.va.gov/queue/appeals/1055070 
1. When at "Schedule Hearings" page, scroll down to the Hearing Date Select a hearing date from the dropdown

Actual behavior: 
When hearing date is not selected, the dropdown menu covers the time zone options under "hearing time" and the time zone options are not contained inside the module box. When hearing date is selected, you can now see all the time zone options but they are still not contained inside the module box and partly cover the "cancel" button.

Desired behavior: 
The hearing time / time zone options are clearly visible and contained within the box and there are no buttons covered.

## Acceptance criteria
- [ ] Line height matches Figma diagrams
- [ ] Hearing time dropdown displays the same on smaller screens

## Technical notes

-Browser: Internet Explorer
-Computer used: 13 inch Macbook Air

**Comment by nicholer** [comment]
Just a note on IE - I believe Caseflow only officially supports Chrome as a browser.
