### ISSUE TITLE
Create new AOD Admin Task

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15409]
## Description

As a CAVC Litigation Support user I want to be able to send an AOD motion request to the AOD team, so that the team can either grant or deny the request for the appellant.

## Acceptance criteria
- [ ] Verify a new ColocatedTask is created that autoassigns to the AOD group
- [ ] Verify the task actions available on Org assigned task are: Assign, Cancel
- [ ] Verify the tasks actions available to AOD org members are: Complete, Cancel, Timed Hold
- [ ] Verify the tasks actions available to AOD org admins are: Reassign
- [ ] Verify the AOD org members are able to edit the Appeal Stream Type on the Case Details page

## Background/context/resources
Needed for the CAVC Remand admin actions #15286

**Comment by araposo-tistatech** [comment]
closing as these should  be routed to the AOD team via the Mail Team
