### ISSUE TITLE
Convert hearing request type from Video or Central to Virtual

### ISSUE THREAD

**Issue by lund5000** [department-of-veterans-affairs/caseflow#15402]
## User story
As a Veteran (or their representative), I want to request a virtual hearing so I can be placed in the virtual hearing queue.

## Background
Now that we can record a hearing request type in Caseflow, we should give other types of hearings the ability to have their hearing request type changed to virtual. This will help record Veteran preferences and build out a more accurate virtual hearing backlog.

## Acceptance criteria
- [ ] When a user with the "Admin Intake", "Build HearSched", or "Edit HearSched" roles ("authorized user") visits the Case Details page for a hearing with an open schedule hearing task and a hearing request type other than "Virtual", they are presented with an Action option to "Convert hearing to virtual"
- [ ] When an authorized user selects the "Convert hearing to virtual" option, they are taken to the "Convert Hearing to Virtual" page to confirm the conversion
  - [ ] Designs ([Figma link)](https://www.figma.com/proto/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=6333%3A2394&viewport=-3739%2C2019%2C0.2672133147716522&scaling=min-zoom) for "Convert Hearing to Virtual" page, success alert, and Case Timeline output are the same as completed #15053 work for Travel Board
- [ ] pre-select virtual type in schedule form? (yes, separate issue)

### Technical details
Unclear whether it would be the best choice to use the Travel Board to virtual approach for this, might need a new tech spec for an additional action on the coordinator's part.
Would not be same ChangeHearingRequestTypeTask as Travel Board to virtual.

**Comment by rubaiyat22** [comment]
Authorized User visits to case details page with a **open** `ScheduleHearingTask` and the appeal (`AMA` or `Legacy`) is not dispatched yet

- `Hearing Type` on Case Details should display `Central` or `Virtual`(the work is already there)

- If the FeatureToggle is on for the authorized user, create a `ChangeHearingRequestTypeTask` as a child of the open `ScheduleHearingTask` if it does not exist already([Example PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15213/files))
  - Unlike travel board flow, this `ChangeHearingRequestTypeTask` should **not** block scheduling. Hearing coordinator should still be able to Schedule a Veteran for Video or Central hearing.
  - FeatureToggle: something like `convert_appeal_hearing_request_type`
- As of now the only action the users can act upon is `Convert hearing to virtual`- when the user acts upon this action
  - Display ` Convert Hearing To Virtual` Form ([PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15314/files) for reference)
  - When user clicks `Convert Hearing To Virtual`
    - save `virtual` (`R`) in `changed_request_type` field on `Appeal` and `LegacyAppeal` (this will require a separate PR to add this field on `Appeal` - [Example PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15189/files)). 
    - The `changed_request_type` on `Appeal` should also be tracked by `PaperTrail` as it currently does for `LegacyAppeal` - [Example PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15231/files)
    - As of this [ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/15427), we should be writing updating location of Legacy Appeals to `CASEFLOW` when the user acts upon `ChangeHearingRequestTypeTask`, i.e when it's completed. 
    - As of this [ticket](https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/15426), we should geo-match(only applies to Legacy Appeals) and cache attributes to `CachedAppeals` table so the appeals can show up the apporpriate RO queue
  - Once converted,
    - Success alert displays indicating which RO queue the appeal will show up on (the work is already there)
    -  `Hearing Type` on Case Details should display `Virtual` ([PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15145/files) for reference) (the work is already there but double check)
    - Case Timeline should display the the relevant info about the completed `ChangeHearingRequestTypeTask` ([PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15395) for reference) (the work is already there)

The appeal should display on `Assign Hearings Table` for appropriate RO under `AMA Veterans Waiting` or `Legacy Veterans Waiting` tab when `Hearing Type` column is filtered by `Virtual`([Ticket](https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/15059) for reference) (the work is already there)

When hearing coordinator visits Case Details page to schedule the veteran for hearing, i.e to complete `ScheduleHearingTask`

- Display the `Schedule Veteran` form with `Virtual` pre-selected ([PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15348) for reference) (the work is partially there)
- Ensure the hearing can be directly scheduled to `Virtual` (the work is already there but will need to double checked)


Open questions?

- Can there be more than One **open** schedule hearing task at a time? If so, do we create the `ChangeHearingRequestTypeTask` for each open task?

**Comment by lund5000** [comment]
Completed in https://vajira.max.gov/browse/CASEFLOW-210
