### ISSUE TITLE
Add Hover Information to Attorney & Judge Queue Task Column 

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15404]
## Description

User Story: As a VLJ Support Staff member, I want to see added context or an identifier on the task column of my queue page, so that I can identify when an IHP task has been completed.

## Acceptance criteria
- [ ] Atty Assigned queue shows `- IHP Received` on the Tasks column for AttorneyTasks with a completed child IhpColocatedTask
- [ ] Judge Assign queue shows `- IHP Received` on the Tasks column for JudgeAssignTasks with a completed child IhpColocatedTask
- [ ] Atty Assigned queue shows the Received details on hover
- [ ] Judge Assign queue shows the Received details on hover
- [ ] Atty On Hold queue shows `IHP Requested` on the Tasks column for `AttorneyTasks` with an open child `IhpColocatedTask`, open `InformalHearingPresentationTask` assigned to a VSO, or an open `IhpColocatedTask` on a legacy appeal assigned by the user
- [ ] Atty On Hold queue shows the Request details on hover

## Background/context/resources
~~User Story: #13800~~ User story was split and closed
Sibling User Story: #15405

We want to show a bit more context for Attorneys and Judges who have requested an IHP when that task has completed, so they can understand this case has recently come back into their queues. See the User Story for more context #13800

This tickets focus is to tweak the Tasks column to give more context of an IHP task that has recently been finished (Atty&Judge) or is out for an IHP (Atty only)

### IHP Epic Designs
[Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1595518321333/a3929ce45595dca9177fe2adfd3cb3d6e3203fbd) of research and flows 
[Link to designs](https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=0%3A1) in Figma

Active Tab Display | On Hold Tab Display
-- | --
![image](https://user-images.githubusercontent.com/6129479/95504000-25d04b80-097a-11eb-840b-7f532706386e.png) | ![image](https://user-images.githubusercontent.com/6129479/95503367-46e46c80-0979-11eb-97dc-6c9f6e1e0ab7.png)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||
3 | |||||
5 | 
8 | 
```

[#15405](https://github.com/department-of-veterans-affairs/caseflow/issues/15405) should provide data on the front end to be able to hit the AC of this ticket.

https://github.com/department-of-veterans-affairs/caseflow/blob/74c5aee68ed707828415da142a9a620f792e476f/client/app/queue/components/TaskTableColumns.jsx#L118 
is where we can modify what is shown in the task column to add to the task type label.

#### Why 2?
* Can complete completely on the front end with data calculated and serialized in blocking ticket

#### Why 3?
* Unfamiliarity with TaskTableColumns
