### ISSUE TITLE
Docket Switch | Implement Text Formatting & API Post in RecommendDocketSwitchContainer

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15420]
## Description
In #15331 we created `RecommendDocketSwitchForm` as well as `RecommendDocketSwitchContainer` to wrap and supply it with props. We declared formatting the instructions and the API call to create the next task as out of scope for that ticket, and will instead implement here.

## Acceptance criteria
- [ ] Implement a function to format the submitted form data per the design
- [ ] Clicking submit makes an API POST call that creates a `DocketSwitchRulingTask` that is:
  - [ ] assigned to the specified VLJ
  - [ ] has instructions field populated with the properly formatted text
- [ ] Update documentation: [link]

## Background/context/resources
Design for the formatted instructions, plus add line breaks

![Screen Shot 2020-10-09 at 2.30.28 PM.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/060645c6-0784-4115-9a5c-4a74741b2c4a)

## Technical notes
The task creation step can be accomplished by using `ApiUtil.post()`

**Comment by jcq** [comment]
@rutvigupta-design Just to clarify, what are the three options for disposition copy? 

This is what I have as a placeholder:
- "Grant all issues"
- "Grant partial docket switch"
- "Deny docket switch"

**Comment by rutvigupta-design** [comment]
@jcq the dispositions are: 

- "Grant all issues"
- "Grant a partial switch" 
- "Deny all issues"
