### ISSUE TITLE
Automatically AOD CAVC Remand if Original appeal was AOD

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15428]
## User or job story
User story: As a CAVC Litigation Support user, I need any CAVC Remand whose previous decision was AOD'd to be automatically AOD'd as well, so that the case is processed as priority. 

## Acceptance criteria
- [ ] Verify the CAVC Remand is AOD if the original appeal was AOD

### Background/context

Right now, AOD labeling happens automatically if the previous appeal had AOD labeling. that is distinct from AOD colocated task action)

**Comment by yoomlam** [comment]
Resolved by #15717
