### ISSUE TITLE
Reader Bug| Files show unopened yet they have been viewed

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#15429]
## Description
User is reporting that Caseflow Reader files show unopened that should be showing as reviewed

## Acceptance criteria
- [ ] Update documentation: [link]

## Background/context/resources
We invested this bug in prod backend and see that user has indeed opened these files
`irb(main):020:0>` Document.where(id: 58963741).first.document_views.first.user
=> #<User id: 1222, station_id: "101", css_id: "BVAJJENKINS"`

We also reproduced it in the frontend by opening the file and then going back to the claim-folder. It showed that this file had been open.

## Technical notes
This is in connection with 2 bat-team issues 
https://dsva.slack.com/archives/CHX8FMP28/p1602785574271200
https://dsva.slack.com/archives/CHX8FMP28/p1602786076271600?thread_ts=1602785574.271200&cid=CHX8FMP28

**Comment by araposo-tistatech** [comment]
@Sjones352 is this still an issue? 

Note to future self: If still an issue, turn into an investigation ticket timeboxed to a 2.

**Comment by Sjones352** [comment]
@araposo-tistatech I have not tested this in a long while so I am not sure if it is an issue.

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1635
