### ISSUE TITLE
ARC Work Assignments | Cases Assigned vs Cases Completed vs Cases Remaining makes no sense

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1546]
# Description
When Manager assigns Dispatch tasks to workers - the numbers Assigned and Remaining are calculated in a very mysterious manner.

## Reproduction Steps

1. As a Manager, go to Dispatch

1. Start messing with # of workers for the day

1. See noting happen because no one did any tasks.

1. Let some workers complete some of their tasks

1. Mess with the numbers again

1. Observe wonky calculations:
  - Why do both workers get 3 cases out of 5?
  - Why both of them get 5 cases assigned?
  - Why workers don't show up on the page until AFTER they've completed a task?!?!?
  - Why does the whole table shift around like crazy?

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod
## Screenshots
**_Scenario 1 - ARC Work Assignments_**

<img width="1074" alt="screen shot 2017-04-12 at 12 58 23 pm" src="https://cloud.githubusercontent.com/assets/18075411/24971152/e5c272c6-1f84-11e7-8f27-a02826e4e400.png">
<img width="1158" alt="screen shot 2017-04-12 at 12 59 55 pm" src="https://cloud.githubusercontent.com/assets/18075411/24971151/e5c10b52-1f84-11e7-9c68-2e370390b20e.png">

**Comment by lakohl** [comment]
I'm re-designing the table on this page, so let's not fix this yet.

**Comment by lakohl** [comment]
This issue may be mute as we are re-designing this table now.

**Comment by lakohl** [comment]
@kierachell I think we can close this as the table has been reworked. Can you confirm that this is no longer a problem?
