### ISSUE TITLE
Docket Switch | Denial Screen

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#15470]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board to whom a denied docket switch task is assigned, I should be able to enter in the date and any context for the request so that Caseflow has a record of the denied docket switch.

## Acceptance criteria
- [x] Please put this work behind the feature toggle: `docket_switch`
- [x] This feature should be accessible to the following user groups: `Clerk of the Board`
- [x] When a user selects "deny docket switch" in their action drop-down, they are taken to the denial screen
- [x] The user should see the denial screen based on the designs below
- [x] Both the date and context fields are required
- [x] Include screenshot(s) in the Github issue if there are front-end changes
- [x] Add Jest test
- [x] Add Storybook story
- [ ] Update documentation: [link]

### Out of scope
- Submission to the backend and processing of `DocketChange` object

### Designs

**Denial Screen**
![16.4 Switch Dockets_ Deny request.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/8284f0e7-96f0-4089-8e78-54c66c12543d)

### Background/context

We decided to separate out the denial flow from the granted (full/partial) flow in order to streamline the process. 

### Technical notes
- This action is launched from existing task actions on `DocketSwitchDeniedTask`. 
- Route will need to be added to `docketSwitchRoutes.js`
  - route should be `/queue/appeals/:appealId/tasks/:taskId/docket_switch/checkout/denied`

### Other notes
- Verify with @rutvigupta-design that no need to display judge's task notes/instructions at the top

### Resources/other links

[End-to-end Figma file](https://www.figma.com/file/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=770%3A0)

**Comment by jcq** [comment]
### Screenshot
<img width="1043" alt="Screen Shot 2020-11-18 at 15 40 08" src="https://user-images.githubusercontent.com/2581274/99601516-688f3580-29b4-11eb-897d-e841bdbea6e2.png">

**Comment by rutvigupta-design** [comment]
Looks great @jcq – just one _tiny_ copy flag from my end: The copy at the top should say "Add the date and any context for the denial of this docket switch." 

Re: VLJ notes/instructions – correct, no need to show these at the top!
