### ISSUE TITLE
Docket Switch | Task Instructions Formatting on Case Details Page

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15531]
## Description
By default, task instructions are run through `StringUtil.nl2br` before being displayed on the Case Details page (either in "Currently active tasks" or the "Case Timeline" section). We want to be able to support more nuanced formatting, such as Markdown. Let's investigate using that, or if there is some reason not to do so (due to incompatibilities with other existing or commonly user-created task instructions), adjust the existing formatting in `RecommendDocketSwitchContainer` to remove Markdown.

## Acceptance criteria
- [ ] Either...
  - [ ] Add support for parsing Markdown to `TaskRows`
  - [ ] Remove Markdown formatting from `RecommendDocketSwitchContainer`

## Technical notes
- Parsing is done in `TaskRows` [ [link](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/TaskRows.jsx#L190) ]

**Comment by jcq** [comment]
@rutvigupta-design Is this OK for how to display the instructions on the Case Details page?
![Screen Shot 2020-10-30 at 11 31 52](https://user-images.githubusercontent.com/2581274/97743947-a3800680-1aa3-11eb-99e8-5b9ff619391b.png)

Your design didn't have line breaks here, but it did on the next (full-page) view; I can't customize this specifically to this type of task, so just trying to get a sense of if we're OK allowing full parsing of Markdown here, including line breaks.

**Comment by rutvigupta-design** [comment]
@jcq I'm good with line breaks, and the 100% width makes sense to me! 

Does the "Hide task instructions" have a pre-set margin to it? Would it be possible to move that up closer to the end of the instructions (12px)?

**Comment by jcq** [comment]
## Updated Screenshot
<img width="406" alt="Screen Shot 2020-11-02 at 14 18 25" src="https://user-images.githubusercontent.com/2581274/97925516-60799980-1d16-11eb-8781-60a0a81e88aa.png">

**Comment by rutvigupta-design** [comment]
Looks great @jcq!
