### ISSUE TITLE
Missing Decisions - shows decisions that have been uploaded

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1556]
Rolandus, the head of BVA Dispatch told us that our BVA Manager view for Missing Decisions is showing cases whose decisions were already uploaded to VBMS the day before (or further in the past). He says this is the case with several of the cases shown in our table. 

he and I pulled the Vet ID at the top of today's list (last name Young) and checked it in VBMS. Indeed it did have an uploaded 'BVA Decision'. (I can provide the vet ID over Lync)

- Are we checking VBMS for all the applicable Doc Types? 
- Apparently the Doc Types have a code - not sure if we use that or a label? 
- Are we truly refreshing the list daily?

**Comment by shanear** [comment]
- One of them has a file number that needs a 0 padded in the beginning
- The others seem to be legitimately missing a decision (@lakohl to confirm)

**Comment by lakohl** [comment]
I reached out to Rolandus to see if he is still experiencing this issue.

**Comment by shanear** [comment]
@lakohl should we pad all 8 digit file numbers with a 0 in the UI too?

**Comment by shanear** [comment]
Update. After a little more digging. I realized the vet in question has a C file number in vacols instead of an S type. Will be fixing that.

**Comment by shanear** [comment]
That vet is fixed and should be processed correctly. Assigning to @lakohl to get the low down on any others that should be going through.

**Comment by lakohl** [comment]
I asked Rolandus about this again (and explained about the one with the missing zero. He said 'looks like once we address the Veteran whose name persist on the report due to the leading “0” we’ll be on track.' 

It sound like if you implement the fixes above we'll be good (at least for now)!

**Comment by lakohl** [comment]
@shanear I think we can close this?

**Comment by shanear** [comment]
Ill keep it open until tomorrow if the missing zero one goes away we should be good

**Comment by shanear** [comment]
worked! closing this out.
