### ISSUE TITLE
Non-Veteran Claimants | Ability to add an unlisted claimant's POA

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15572]
## User or job story
As a BVA Caseflow Intake user, if an unlisted claimant indicates that they have a POA, I should be able to add that POA's information when intaking a board appeal.

This will behave similarly to adding an Attorney Claimant, it will start with the ability to search listed attorneys, and if not found, the ability to add them as a new Individual or Organization.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [non_veteran_claimants]
- [ ] On the "Add Claimant" page, if the user selects "Yes" for the claimant indicating a POA, allow the user to Continue to the next step after the required claimant information is entered.
- [ ] Continuing to the next step saves the claimant information, and stays on "3. Review" in the progress bar. The path is `/intake/add_power_of_attorney'
- [ ] The page has "Add Claimant's POA" as the title, and header copy (see copy below)
- [ ] There is a "Representative" section, which behaves similarly to adding an Attorney, handles listed and unlisted Org/Ind POAs.  It uses the same CorpDB data for listed representatives.
- [ ] If a representative is selected with the Searchable Dropdown, show their address below (see design)
- [ ] After adding required POA section, the ability to continue to the next step is enabled
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Out of scope
- Handling submit (Continue to next step)

### Designs
![Screen Shot 2020-11-04 at 3.44.49 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/a88337c1-6326-45e0-8036-212d1605106b)

![Screen Shot 2020-11-04 at 3.03.42 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/c3944239-2612-4e39-9194-1477abe7ff7d)

### Technical notes
The ability to handle listed attorney claimants is currently available through another workflow.

**Comment by Sjones352** [comment]
@rutvigupta-design 

Quick question on `There is a "Representative" section, which behaves similarly to adding an Attorney, handles listed and unlisted Org/Ind POAs. It uses the same CorpDB data for listed representatives.`. Should it have 2 searchable dropdowns where one  handles listed representatives like this?
![Screen Shot 2021-02-08 at 2.03.07 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/1628f09f-a17d-4a4c-9c33-e788e7e6bd68)
