### ISSUE TITLE
Fix copy in Case Timeline on the Case Details page

### ISSUE THREAD

**Issue by rutvigupta-design** [department-of-veterans-affairs/caseflow#15578]
## Description
The Case Timeline page currently says "Soon, you'll be able to see many more details" which may be confusing for users. This copy needs to be removed. 

## Acceptance criteria
- [ ] Remove ""Soon, you'll be able to see many more details" from the Case Timeline (globally)

## Existing Content
![Screen Shot 2020-10-29 at 2.45.04 PM.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/953f9c1b-0c5d-4cfb-b5c1-408b59d41a7e)

## Out of scope
- Adding in any other replacement copy

**Comment by Jeremy1026** [comment]
BEFORE|AFTER
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/2308626/110140713-5f2eab00-7da2-11eb-84f0-2e9c91696e27.png">
|<img width="1469" alt="image" src="https://user-images.githubusercontent.com/2308626/110140632-49b98100-7da2-11eb-996c-f7841820bfc5.png">

**Comment by rutvigupta-design** [comment]
I'm so happy this has been fixed! Looks great! 🎉
