### ISSUE TITLE
Upgrade Caseflow node/npm version

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1557]
Our version of node used by Caseflow is very old and outdated. We should upgrade to the newest LTS.

Ensure that the newest version can be installed/run on travis

**Comment by joofsh** [comment]
Deploys work, so this should be auto-QA'd

**Comment by kierachell** [comment]
**PASSED**
Deploys didn't work.
Then they worked.
Then everyone's `npm` broke
So it works
