### ISSUE TITLE
Non-Veteran Claimants | Ability to indicate a new claimant's POA

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15571]
## User or job story
As a BVA Caseflow Intake user, I should be allowed to add information for a POA representing a claimant if they have indicated that they have one.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [non_veteran_claimants]
- [ ] On the "Add Claimant" page, after the user selects a relationship and whether they're an Organization or individual, show a Radio option at the bottom of the page: "Has the claimant indicated a representative (POA)?", with the options "Yes" and "No"
- [ ] If the user selects "No" and has populated the required claimant information, enable the button to Continue to the next step
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

### Out of scope
- Handling if the user selects "Yes" to add a POA
- Handling submit (Continue to next step), which would open up the Confirmation modal

### Designs
![Screen Shot 2020-11-04 at 2.54.26 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/ddd7239f-95b9-41ca-ac0d-be8125cc82a6)

**Comment by rutvigupta-design** [comment]
@Sjones352 the copy for the question is: "Do you have a VA Form 21-22 for this claimant?"
