### ISSUE TITLE
Refactor CachedAppealService to separate AMA vs Legacy methods 

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15584]
## Description
Refactor `CachedAppealService` so that methods relating to AMA vs Legacy are in different classes. That would make the service class easier to follow (and reduce the number of lines).

## Acceptance criteria
- [ ] Update .reek.yml to remove unnecessary exclusions

## Background/context/resources
Motivated by review of Cache hearings related fields selectively #15577.

## Technical notes
Common methods used by both AMA and Legacy-related methods
* `regional_office_fields_to_cache`

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||
3 | ||||||
5 | 
8 | 
```

Tie goes to the larger estimate!

could keep `CachedAppealService` as a parent class with the few common methods

#### Why 2?
* Straightforward refactor :crossed_fingers: 

#### Why 3?
* Code is a bit hairy

**Comment by yoomlam** [comment]
May now be easier with PR #15668

**Comment by GabbyTISTA** [comment]
moved to https://vajira.max.gov/browse/CASEFLOW-1632
