### ISSUE TITLE
Work History | Stale Object Error

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1559]
# Description
When two Caseworkers click **Establish next claim** for the same task - only one of them wins. And the other causes a StaleObjectError

## Reproduction Steps

1. Login as Caseworker 1

1. Login as Manager

1. Login as Caseworker 2

1. Load up the queue with 1 task

1. As a Manager set number of workers to 2

1. Click **Establish next claim** as Caseworker1 and quickly as Caseworker2

1. Watch Sentry whine at you

1. Get weird error as one of the Caseworkers that only goes away on page refresh (because button gets greyed out)

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:

n/a

## Sentry:

https://10.236.66.247/sentry/caseflow-uat/issues/180/

## Screenshots
**_Scenario 1 - [Work History Error]_**

<img width="1119" alt="screen shot 2017-04-12 at 9 36 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/24986455/4c79c3a0-1fc8-11e7-8cb2-7a213bd80086.png">

# Related Issues
**_Engineering_**
#1416 
https://github.com/department-of-veterans-affairs/caseflow/issues/1466

**Comment by joofsh** [comment]
This has happened enough times in production that we should investigate further. Adding it to the upcoming sprint

**Comment by kierachell** [comment]
Sample error from another page:
<img width="1396" alt="screen shot 2017-04-24 at 11 05 57 am" src="https://cloud.githubusercontent.com/assets/18075411/25343795/141ef650-28de-11e7-8d7f-4599410d5db1.png">

**Comment by joofsh** [comment]
@kierachell 2 things are changed:
- The "success!" page will not properly show you an error (if one occurs)
- We've added  "retry" logic. So now it will try to assign you the _next_ task if there is a race condition. You'll still end up with a generic error if that was the last task in the queue

**Comment by kierachell** [comment]
**PASSED**
It worked!

```
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b46739f0123fefbc-172.30.67.250 [appeals.cf.uat.ds.va.gov] [5be5468c-3713-410b-8922-2ef10c018115] [172.30.67.250] [CASEFLOW_397   caseflow@va.gov] [2017-05-09 17:47:50 -0400] RetryHelper rescuing from StandardError. /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:102:in `_update_record'                   
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b46739f0123fefbc-172.30.67.250 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:129:in `_update_record'                                                                                                                                                                                                      
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b46739f0123fefbc-172.30.67.250 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:310:in `block in _update_record'
```


Did not see a Sentry error 👍
