### ISSUE TITLE
Docket Switch | Submit Denial

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15603]
## Description
When a user submits the information for denied docket switches (receipt date and context), this will handle 

## Acceptance criteria
- [x] Add Docket Switch controller
- [x] Add create endpoint that we submit the data and disposition to
- [x] Save a `docket_switch` object where the disposition is "denied"
- [x] Save the docket_switch receipt_date on the docket_switch object
- [x] Append the denial context to the existing docket switch denied task instructions
- [x] Close the docket switch denied task
- [x] Redirect to the Case Details page (see Denied Docket switch banner ticket)

**Comment by leikkisa** [comment]
Adding some example PRs to take a look at:
[Docket switch recommendation submission](https://github.com/department-of-veterans-affairs/caseflow/pull/15432)
[MTV Denial submission](https://github.com/department-of-veterans-affairs/caseflow/pull/12638/files)

**Comment by wdrougas-tista** [comment]
@jcq When submitting the docket switch denial, the `DocketSwitchDeniedTask` gets assigned a status of `completed` but its parent of `DocketSwitchRulingTask` has a status of `assigned` and the parent of the ruling task, `DocketSwitchMailTask`, has a status of `on_hold`. I imagine we want to assign both of these tasks a status of `completed` to move them out of the Currently Active Tasks and into the Case Timeline?

**Comment by jcq** [comment]
> @jcq When submitting the docket switch denial, the `DocketSwitchDeniedTask` gets assigned a status of `completed` but its parent of `DocketSwitchRulingTask` has a status of `assigned` and the parent of the ruling task, `DocketSwitchMailTask`, has a status of `on_hold`. Do we want to assign both of these tasks a status of `completed` to move them out of the Currently Active Tasks and into the Case Timeline?

When I run through the feature tests in `docket_switch_spec`, this is the resulting task tree that I see:
```
[2] pry(#<RSpec::ExampleGroups::DocketSwitch::COTBAttorneyCompletesDocketSwitchDenial>)> appeal.treee
                                       ┌────────────────────────────────────────────────────────────────────────┐
Appeal 1 (E 201217-1 Original) ─────── │ ID │ STATUS    │ ASGN_BY │ ASGN_TO         │ UPDATED_AT                │
└── RootTask                           │ 1  │ on_hold   │         │ Bva             │ 2020-12-22 19:29:03 -0500 │
    └── DocketSwitchMailTask           │ 2  │ completed │ CSS_ID5 │ ClerkOfTheBoard │ 2020-12-22 19:29:03 -0500 │
        └── DocketSwitchRulingTask     │ 3  │ completed │ CSS_ID3 │ CSS_ID4         │ 2020-12-22 19:29:03 -0500 │
            └── DocketSwitchDeniedTask │ 4  │ completed │ JUDGE_1 │ CSS_ID1         │ 2020-12-22 19:29:35 -0500 │
                                       └────────────────────────────────────────────────────────────────────────┘
```
In _theory_ that looks like it should be correct. Where are you seeing the others?

That said, the timeline needs work, as this is how they show up:
![Screen Shot 2020-12-22 at 16 39 37](https://user-images.githubusercontent.com/2581274/102946052-679a6980-4474-11eb-8b78-a6d90d3b84d2.png)

Clearly some more work needs to be done to properly show the ruling/denial task labels, etc
