### ISSUE TITLE
Give VLJs and Attorneys access changing to the MTV vacate type through a Task Action

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15618]
## Description
Right now if the Judge or Attorney determine that the created MTV stream type is incorrect, the Attorney must navigate to `Decision ready for review` from the Actions dropdown, and then on the page that appears click `please return to Judge` in the blue highlighted area. 
Step 1 | Step 2 | Step 3 | Step 4
--|--|--|--
![Attorney_Return_to_Judge_for_Vacate_type_change_1](https://user-images.githubusercontent.com/6129479/99552146-ab3c1800-298a-11eb-8a9b-16e60791c132.png) |![Attorney_Return_to_Judge_for_Vacate_type_change_2](https://user-images.githubusercontent.com/6129479/99552162-af683580-298a-11eb-969d-2324d5fdcc66.png) | ![Attorney_Return_to_Judge_for_Vacate_type_change_3](https://user-images.githubusercontent.com/6129479/99552175-b2632600-298a-11eb-8c34-18fd79007f13.png) | ![Attorney_Return_to_Judge_for_Vacate_type_change_4](https://user-images.githubusercontent.com/6129479/99552197-b727da00-298a-11eb-97e4-f53373cbb0c2.png)

[This has proven to be unintuitive to users](https://dsva.slack.com/archives/CHX8FMP28/p1605537407033500), who instead err to selecting `Return to Judge` in the actions drop down, but that just returns it to JudgeAssign, where the VLJ cannot kick off the process without assigning it back to the Attorney to select in their checkout. Let's instead add an action to the dropdown menu for both the Attorney and the Judge to `Change Vacate Type`.

Old Flow: Attorney initiates checkout on the Vacate stream, clicks the link in the box, hits submit - this kicks off the process.
New Flow: Attorney _or_ Judge selects `Change Vacate Type` on the Vacate stream, which kicks off the process.

This ticket is _only_ for changes to the front end flow. See TK for changes to how we process the request.

Open question: should we remove the text link during attorney checkout, or does it have other use cases so we should leave it? Ask Foxtrot Design.

## Acceptance criteria
- [ ] Vacate Stream type changes can be initiated via a Task Action process, in addition to (rather than?) than during Checkout
- [ ] This action is available to both the Attorney or the VLJ anytime before the Attorney has drafted a decision.

## Background/context/resources
[Bat Team convo](https://dsva.slack.com/archives/CHX8FMP28/p1605537407033500)
[Foxtrot convo](https://dsva.slack.com/archives/C54QCEHAL/p1605621794265200)

**Comment by lomky** [comment]
Possibly duplicates #15529 - need to figure out who owns MTV tickets!

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1699
