### ISSUE TITLE
Changing the Vacate Type of an appeal should be nondestructive

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15619]
## Description
Right now when the Attorney requests the VLJ change the vacate type of an appeal, the entire Vacate stream is deleted and a new AddressMotionToVacateTask is created for the VLJ on the original appeal. This was implemented this way as it was determined that the vacate appeal, at this point, contained no additional information. However, we do lose some information around where the appeal was and for how long with this process.

Path 1: Instead of deleting the vacate appeal, cancel it.
Path 2: Instead of deleting the vacate appeal, update it with the new values.

## Acceptance criteria
- [ ] Vacate appeals are retained through a type change

## Background/context/resources
#15618 
[Foxtrot convo](https://dsva.slack.com/archives/C54QCEHAL/p1605621794265200)

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1697
