### ISSUE TITLE
Intake | Bug | Decided non-comp issues are not getting closed as decided

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15613]
## Description
For SCs (supplemental claims) and HLRs (higher level reviews), if the business line is not compensation or pension, the decision reviews go to what we call the "non-comp queue", a lightweight version of queue that allows users to add decisions to request issues.

When users are adding decisions, the decision issues are getting added, but the request issues are not being closed as "decided".  This allows users to go back in and edit later, and do another action such as withdraw the issue.

## Acceptance criteria
- [ ] When a user submits a decision for a non-comp decision review (via the non-comp queue), it closes the decided request issues with the status of "decided"

## Background/context/resources
[Batteam Slack thread](https://dsva.slack.com/archives/CHX8FMP28/p1605555858039400)

## Technical notes
See `DecisionReviewTask.complete_with_payload!` where decision issues are getting created, the task is getting closed, but the request issues are not getting closed.  `RequestIssue.close_decided_issue!` should be called somewhere.

Note: creating decision issues does not immediately result in closing request issues on board appeals, just for non-comp/pen HLRs and SCs.

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1692
