### ISSUE TITLE
Caseworker Landing | No more assigned

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1562]
**Story**

As a caseworker, I want to know if I have completed all the claims assigned to me and if there aren't or aren't any more claims in the queue for me to work on. 

This happens in two scenarios:
1. No more assigned, still more claims in queue
1. No more assigned, no claims in queue

## Description
In these cases, x assigned, y completed numbers are the same. At this point, a caseworker cannot work on anything. 

## Acceptance Criteria

- Verify that the copy above the work history matches the copy in the bottom 
   - Your Work Assignments should be `h1` and in title case
   - Way to go! should be in `h2` and in sentence case
   - Work history should be in `h2` and in sentence case
   - See [style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography) for all heading sizes and spacing
- Verify that the assigned number matches the completed number.
- Verify that the `Establish next claim` button is disabled and follow our [disabled button pattern](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#buttons)
- Verify that there is a gray horizontal line dividing Congratulations messages and Work History section. See [horizontal line in style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#layout)
- Verify that all content is left aligned with Work history title

## Mockup
![image](https://user-images.githubusercontent.com/13420618/27560886-d8d7d124-5a93-11e7-90c8-a94886bcdeda.png)

## Copy
Way to go!
You have completed all the claims assigned to you. 

## Related
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/129
#1501
#1564

**Comment by gnakm** [comment]
@lakohl I split up the issues in this repo. Can you review these?

**Comment by lakohl** [comment]
@gnakm @avrildavid This looks good, but on the third line lets be consistent with how we message no more claims in the queue on #1564 e.e. if we say 'There are no more claims in the queue.' we should use that verbige on the third line here. Likewise if we say 'There are no more claims to pick up' on #1564 we should use that here.

**Comment by lakohl** [comment]
@gnakm the ARC team seemed to like the emojis as a way to indicate that they finished their daily assigned cases. I'm thinking that they might also be a good visual indicator here maybe next to Congratulations or to 'You have finished all the cases assigned to you'. 

@avrildavid Also to consider, using 'Way to go!' vs. 'Congratulations'

**Comment by gnakm** [comment]
@lakohl @avrildavid 
Mocks and copy are updated! 
Added Emojis
> the ARC team seemed to like the emojis as a way to indicate that they finished their daily assigned cases.

**Comment by avrildavid** [comment]
@gnakm - super small  update - this one should read "all the **claims**" instead of "all the cases" for consistency.

**Comment by gnakm** [comment]
@avrildavid Thanks! Will change the copy!

**Comment by gnakm** [comment]
@Sjones352 FYI I updated the mock above to match #1566

**Comment by lakohl** [comment]
@gnakm lets check in on this

**Comment by lakohl** [comment]
Ready to go

**Comment by kierachell** [comment]
### Completed all assigned works, but then:
<img width="1131" alt="screen shot 2017-07-25 at 4 12 22 pm" src="https://user-images.githubusercontent.com/18075411/28591526-0f3ec70a-7154-11e7-8100-ebd915930a41.png">


### What if...

- Worker started a claim
- Manager reduced the Quota for the worker
- Worker sees weird things and can still do more claims
<img width="1128" alt="screen shot 2017-07-25 at 4 11 43 pm" src="https://user-images.githubusercontent.com/18075411/28591556-2bb276c0-7154-11e7-9fc8-57a7e27235fb.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="1093" alt="screen shot 2017-07-25 at 4 16 37 pm" src="https://user-images.githubusercontent.com/18075411/28591717-ae33c176-7154-11e7-96c1-9bf7da91ecc8.png">
