### ISSUE TITLE
Upgrade to Storybook 6.1

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15628]
## Description
Storybook 6.1 has been released, bringing [a number of improvements](https://storybook.js.org/blog/storybook-6-1/). We should upgrade to take advantage of them!

## Acceptance criteria
- [ ] Update Storybook to 6.1.x

## Tech Notes
This can be accomplished simply by running `npx sb upgrade`

**Comment by meckila-navapbc** [comment]
Storybook version upgraded
