### ISSUE TITLE
`TaskSorter` Failure Due to Partial Match of Task Name

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15636]
## Description
The results of `TaskSorter` are subject to failure if there exists a class that inherits from `Task` that has a type that contains the type of another task as a substring. This results in incorrect sorting.

## Acceptance criteria
- [ ] `TaskSorter` will not fail if two tasks that share a type substring, regardless of output of their `label` method

## Background/context/resources
This can be replicated by changing the `label` method on `DocketSwitchAbstractAttorneyTask` to output a string (such as "AAA") that comes alphabetically before the `label` method of `AttorneyTask`.

## Technical notes
- The `TaskSorter` class defaults to sorting by the `label` method
  - This requires all classes that inherit to implement a `label` method, even if just being used as an abstract class
- `TaskSorter` considers _all_ descendants of `Task`, regardless of other context
- `task_type_order_clause` uses the `POSITION()` function, which searches for a substring in a string

**Comment by leikkisa** [comment]
Just a note that since this is substring matching, adding something to indicate the beginning and end of the name strings works! There might be a more elegant solution, but adding this here in the meantime. 

Located in: `TaskSorter.task_type_order_clause`

```ruby
task_types_sorted_by_label = Task.descendants.sort_by(&:label).map{|t| '$' + t.name + '^'}
    task_type_sort_position = "concat('$', tasks.type, '^') in '#{task_types_sorted_by_label.join(',')}'"
    "position(#{task_type_sort_position}) #{sort_order}"
```
