### ISSUE TITLE
Create IHP tasks when evidence submission window tasks are manually completed

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15639]
## Description
EvidenceSubmissionWindowTasks are created with a TaskTimer set to 90 days after an Appeal's Receipt date. When these tasks are completed via the job that processes the TaskTimer, IHP Tasks are properly created for any IHP writing VSO representative. However, members of the mail team also have the ability to manually complete an EvidenceSubmissionWindowTask early via the appeal's case details view. This method does not trigger IHP Task creation. 

## Acceptance criteria
- [ ] Completion of EvidenceSubmissionWindowTasks via the task action invokes the IHP Task creation process

## Background/context/resources
#14889 
Slack Research dive threads [1](https://dsva.slack.com/archives/CQCUMFA0H/p1606259912052000) [2](https://dsva.slack.com/archives/CQCUMFA0H/p1606317897004300)

## Technical notes
How the TaskTimer flow invokes the IHP Task creation process 
`create_ihp_tasks!` handles checking whether a given appeal with a given VSO gets to write an IHP

https://github.com/department-of-veterans-affairs/caseflow/blob/17a7507088c4b5c35192e545b312aa46d6f1d7fc/app/models/tasks/evidence_submission_window_task.rb#L14-L17

How to mock up an appeal at this state:
```ruby
FactoryBot.create(
  :appeal,
  :with_post_intake_tasks,
  claimants: [FactoryBot.create(:claimant, participant_id: "CLAIMANT_WITH_PVA_AS_VSO")],
  docket_type: Constants.AMA_DOCKETS.evidence_submission
)
```

To reproduce: navigate to appeal in UI as mail team member, select `Mark task complete`. 
```ruby
                                         ┌───────────────────────────────────────────────────────────────────┐
Appeal 1039 (evidence_submission) ────── │ ID   │ STATUS      │ ASGN_BY │ ASGN_TO  │ UPDATED_AT              │
└── RootTask                             │ 3530 │ on_hold     │         │ Bva      │ 2020-11-25 15:31:24 UTC │
    ├── TrackVeteranTask                 │ 3531 │ in_progress │         │ Vso      │ 2020-11-25 15:31:24 UTC │
    └── DistributionTask                 │ 3532 │ assigned    │         │ Bva      │ 2020-11-25 18:03:39 UTC │
        └── EvidenceSubmissionWindowTask │ 3533 │ completed   │         │ MailTeam │ 2020-11-25 18:03:39 UTC │
                                         └───────────────────────────────────────────────────────────────────┘
```

Invoking via the job gives us the expected, correct task tree
```ruby
timer = TaskTimer.where(task_id: 3537)
TaskTimerJob.new.send(:process, timer)
```
```ruby
                                            ┌───────────────────────────────────────────────────────────────────┐
Appeal 1041 (evidence_submission) ───────── │ ID   │ STATUS      │ ASGN_BY │ ASGN_TO  │ UPDATED_AT              │
└── RootTask                                │ 3534 │ on_hold     │         │ Bva      │ 2020-11-25 18:05:08 UTC │
    ├── TrackVeteranTask                    │ 3535 │ in_progress │         │ Vso      │ 2020-11-25 18:05:08 UTC │
    └── DistributionTask                    │ 3536 │ on_hold     │         │ Bva      │ 2020-11-25 18:05:08 UTC │
        ├── EvidenceSubmissionWindowTask    │ 3537 │ completed   │         │ MailTeam │ 2020-11-25 18:10:02 UTC │
        └── InformalHearingPresentationTask │ 3538 │ assigned    │         │ Vso      │ 2020-11-25 18:10:02 UTC │
                                            └───────────────────────────────────────────────────────────────────┘
```

**Comment by araposo-tistatech** [comment]
[what is this chart?|https://github.com/department-of-veterans-affairs/caseflow/issues/11533]
{code:bash}
1 | ||||||||
2 | |||||||
3 | 
5 | 
8 | 
{code}

 
h4. Why 1?
* Add call to `when_timer_ends` when an evidence submission window is manually closed.

h4. Why 2?
* IHP!!! *shakes fist*
* Testing
