### ISSUE TITLE
Caseworker Landing | Assigned claims, no claims in queue

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1564]
**Story**

As a caseworker, I want to know if I have claims assigned to me but there aren't any claims in the queue for me to work on. 

## Description
This is a case where x assigned > y completed and there are currently no more claims to be established in the queue. At this point, a caseworker cannot work on anything but will need to come back to check if there are any available at another time. 

## Acceptance Criteria
- Verify that the copy above the work history matches the copy in the bottom 
   - Your Work Assignments should be `h1` and in title case
   - All claims in queue completed should be in `h2` and in sentence case
   - Work history should be in `h2` and in sentence case
   - See [style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography) for all heading sizes and spacing
- Verify that the assigned number is greater than the completed number.
- Verify that the `Establish next claim` button is disabled and follow our [disabled button pattern](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#buttons)
- Verify that there is a gray horizontal line dividing Congratulations messages and Work History section. See [horizontal line in style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#layout)
- Verify that all content is left aligned with Work History title

## Mockup
![image](https://user-images.githubusercontent.com/13420618/27559367-4e380836-5a8e-11e7-9e08-10ea15e0b3c5.png)

## Copy

Your Work Assignments

All claims in queue completed

There are no more claims to pick up. 
Please come back later.

Work history

## Related
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/129
#1501
#1562

**Comment by gnakm** [comment]
@lakohl I split up the issues in this repo. Can you review these? For this one, I'm specifically concerned about the title.

**Comment by lakohl** [comment]
@gnakm this looks good to me. @avrildavid can you lend a second pair of eyes to the title. 
We are trying to describe a scenario where there are no more cases in the overall queue/ no more cases left for ARC to work that day

**Comment by gnakm** [comment]
@lakohl @avrildavid 
Mocks and copy are updated!

**Comment by kierachell** [comment]
**PASSED**
<img width="1125" alt="screen shot 2017-07-25 at 4 21 18 pm" src="https://user-images.githubusercontent.com/18075411/28591919-5577f60a-7155-11e7-8a3b-1f4468f3a7bd.png">
