### ISSUE TITLE
[IP Sprint] Research UpdatedCachedAppealsAttributes cache strategy improvements

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#15647]
## Description

Research Dive to figure out our best options for caching the data in UpdateCachedAppealAttributes

### AC
  - Which fields are prone to updating often, which arent. which external source do these pull from, how does hearings use the fields
  - Which fields should stay in the job & the Postgres DB cache, which should we move to redis
    - how does Caseflow currently use redis
  - For any that we move to the redis cache, should we write a tighter-scoped cache priming job to do the first heavy query? 
  - once common changed fields are out of the job, how often does it need to run?

**Comment by lomky** [comment]
Potentially connects with #15648 and #15651 !

**Comment by lomky** [comment]
Closing with two improvements queue'd up: #15648 will refactor the BGS call out of this job. #14974 will add an on-load refresh for stale POAs when individual cases are accessed.
