### ISSUE TITLE
Database Schema Introductory Documentation

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15644]
## Description
For each Caseflow product, identify the five most relevant tables and develop diagrams and documentation.

This work has already been started by Yoom, want to complete it across teams and products.
Follow-up on Slack threads where he asked the teams some initial questions to help fill out the documentation:
-   Tango: https://dsva.slack.com/archives/C3EAF3Q15/p1602020935106700
-   Foxtrot: https://dsva.slack.com/archives/C54QCEHAL/p1602020760230200
-   Echo: https://dsva.slack.com/archives/CJL810329/p1595003507182200

Instructions are provided at the top of [Caseflow-Data-Model-and-Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary).

## Acceptance criteria
- [ ] Updated [Caseflow-Data-Model-and-Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary) with diagrams for tables, intro/walkthrough documentation linking to related documentation for all Caseflow products

## Background/context/resources
[Checklist](https://hackmd.io/HOtlJFpbRnGgJppgLOHoCQ?view)

### How does this help achieve Caseflow's priorities?
* Helps new team members get familiar with product on an introductory level
* All team members get more familiar with Caseflow products where they may not spend much time

### How does this help us as a team be more effective?
Readily available data documentation for non-engineers (e.g., PMs and designers)

### Teams, Products, Models

**Echo**
- Dispatch: legacy_appeal, Dispatch::Task, user
- Queue: appeal, legacy_appeal, organization, organizations_user, task, user
- Reader: annotation, document, document_tag, document_view, tag

**Foxtrot**
- Certification: certification, certification_cancellation, form8, legacy_appeal
- Intake: appeal, end_product_establishment, higher_level_review, request_issue, supplemental_claim

**Tango**
- Hearings: hearing, hearing_day, hearing_task_association, legacy_hearing, task, virtual_hearing
- Efolder Express: files_downloads, manifest, manifest_sources, records

**Comment by wdrougas-tista** [comment]
Action Items for December 1

- Intake and Certification Diagrams - @wdrougas-tista 
- Intake writeup/description - @wdrougas-tista 
- Queue writeup/description - @ajspotts

**Comment by wdrougas-tista** [comment]
**Timeline**

First iteration for all documentation done by noon on Friday, December 2
Second iteration for all documentation done by EOD on Monday, December 5
Documentation finalized and formatting done by EOD on Thursday, December 8
Demo on Friday, December 9

**Delegation**
@ajspotts - Queue, Reader, Dispatch
@wdrougas-tista & @pbradin - Intake, Certification, Hearings, eFolder

**Comment by yoomlam** [comment]
@wdrougas-tista completed this.
