### ISSUE TITLE
Death Dismissal | Allow deceased veteran claimant on Appeals

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15681]
## Description
Currently, when a veteran is deceased, Intake blocks them from proceeding without selecting a claimant other than the veteran.  This currently happens on all decision review types (Appeals, HLRs, and SCs).  For this ticket, we would like to remove this blocker for Appeals, in order to allow intake to proceed where it will be processed as a death dismissal or a substitution claim.

## Acceptance criteria
- [x] If a veteran is deceased (has a date of death), a user may select "No" for a non-veteran claimant, and successfully continue to the next page
- [x] This only applies to Appeal intakes

## Background/context/resources
Historically, one reason these have been blocked is due to unresolved issues on how to handle these if they get routed to VBA.

Here's a screenshot of what this currently looks like for a deceased veteran.
![Screen Shot 2020-12-14 at 10.46.07 AM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/1fa4578d-2354-4191-b83a-330a9b5d026d)

## Technical notes
Steps to get here in the app:

1. Log in as an intake user
1. Start an **Appeal intake (Board NOD)** intake at `/intake` for a deceased veteran (file_number TBD)
1. This should bring you to the review page where the claimant is selected

On the frontend, see `caseflow/client/app/intake/pages/appeal/review.jsx` for the Appeal review page.
See `caseflow/client/app/intake/pages/review.jsx` for submit button validation
See `caseflow/client/app/intake/components/SelectClaimant.jsx` for the component for selecting a claimant

It does not look like there is currently backend validation on whether the veteran is deceased (but it doesn't hurt to look!)

**Comment by leikkisa** [comment]
![Screen Shot 2020-12-23 at 7 10 06 PM](https://user-images.githubusercontent.com/6589610/103057472-6f313f80-4554-11eb-9a68-adb9f404d030.png)
![Screen Shot 2020-12-23 at 7 08 57 PM](https://user-images.githubusercontent.com/6589610/103057474-70626c80-4554-11eb-8873-f179eab14758.png)

**Comment by ChatthaD** [comment]
I'm in need to identify Death Dismissal cases which are InTaken. Is Date_of_Death field in Veterans table in Caseflow.Public schema reliable? and how frequently its updated?  Thanks @HelimaBass @yoomlam @robert-vanallen

**Comment by leikkisa** [comment]
Hi @ChatthaD.  The veteran's cached data gets triggered from different user interactions, and I saw one job.  I'm not completely familiar with the code, but I did a quick review and will try to summarize here.

It's updated initially during intake. Then if it's a VBA claim, it gets checked when syncing the end product (daily), until the claim is no longer active.  Otherwise, it gets updated for some hearings activity.

Since you're trying to look for data on deceased veterans that have been intaken (and we knew it when they were intaken), all of those would have the date of death in our database, and it would be reliable for those.

If the veteran passes away after intake, it would become more spotty unless the veteran has an active end product.

I hope this helps!

-----
More details for when the cached attributes are updated:

- When a new intake is created for the veteran
- When an end product is created or synced (mostly for VBA claims)
- For certain hearing related activity
  - When sending a hearing email, the attributes are updated if the name fields are currently nil (indicating they hadn't been updated previously)
  - Through a job for hearings.  Given a specific day, veterans with hearings on that day will get updated (not sure the timing of when that happens relative to the hearing date)
- The update only happens if the user has access to the veteran's record (when triggered by a user instead of a job)

**Comment by ChatthaD** [comment]
Thank you @leikkisa for this detailed answer. Its very helpful.

**Comment by ChatthaD** [comment]
@leikkisa @yoomlam Veterans table in Caseflow does not show 'date of death' for some Veterans, even Caseflow Queue in eFolder FNOD is marked/shown red. Please advise the true source of updated 'Date of Death'. see if I could do a quick call or short meeting. Thanks @HelimaBass

**Comment by yoomlam** [comment]
@ChatthaD 
We identified a bug during the investigation, which prevents `date_of_death` from being updated. Here's the ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/15861
We'll follow-up with you when the bug is squashed!
