### ISSUE TITLE
BVA Cases index page does not filter correctly

### ISSUE THREAD

**Issue by wdrougas-tista** [department-of-veterans-affairs/caseflow#15716]
Users are presented with the option to sort BVA cases by "<<blank>>" Type in Queue. When selecting the filter, no cases are presented

![Screen Shot 2020-12-21 at 10.16.19 AM.png](https://images.zenhubusercontent.com/5e976ddfed689a8dc52aee6c/5ed28f42-b699-4290-869e-d20c0778ea87)

![Screen Shot 2020-12-21 at 10.16.27 AM.png](https://images.zenhubusercontent.com/5e976ddfed689a8dc52aee6c/9df25f5c-f59a-45c0-9cab-9e440521c490)

**Comment by hschallhorn** [comment]
Dupe of https://github.com/department-of-veterans-affairs/caseflow/issues/12129!

**Comment by wdrougas-tista** [comment]
Thanks @hschallhorn ! I'll close this out
