### ISSUE TITLE
Make h1 size consistent, introduce h2, define spacing around them

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1575]
Currently the size of the page headers is not consistent. As a case worker, I would like to be able to see what page I am on and understand what I am supposed to do there.  I would like the the hierarchy of the page to be easily discernible due to the use of consistent styling across the application.

## **AC**

Page headings:
1. Verify that all page titles follow the new* h1 style: Title Case, Source Sans Pro, Bold, 34 px.
1. Verify that subheadings follow the new* h2 style: Title case, Source Sans, Bold, 24 px
1. Verify that current page titles are broken into an h1 plus one or two h2s as indicated in the tables below:

| Current page title |new h1| new h2 |
|-------------------- | ------ | --- |
Work History | Work History | NA
| Review Decision | Review Decision | NA
Route Claim: Create End Product | Route Claim | Create End Product
| Route Claim: Existing End Product(s) | Route Claim | Existing End Product(s)
Route Claim: Confirm VACOLS Update | Route Claim | Confirm VACOLS Update
| Route Claim: Send Email Notification | Route Claim | Send Email notification

| Current page title |new h1| first h2 | second h2 |
|-------------------- | ------ | --- | --- |
| Route Claim: Confirm VACOLS Update, Add VBMS Note | Route Claim | Confirm VACOLS | Update Add VBMS Note

Header spacing:

4. Verify that the spacing between the h1 (page title) and the first h2 (subheading) is 30px.
5. Verify that the spacing between the h2 and the element below it is 30px

Gray line:

6. Verify that on the Route Claim: Confirm VACOLS Update, Add VBMS Note page there is a grey line dividing the Confirm VACOLS update section and the Add VBMS Note section.
7. Verify that there is 40px of margin above and below the gray line.

## **References**
See #1078 and #1677 for more info on Caseflow text and canvas styling

## **Mocks**

_Current:_
<img width="477" alt="screen shot 2017-04-22 at 12 50 43 pm" src="https://cloud.githubusercontent.com/assets/4975959/25306391/5990277a-275a-11e7-8970-fcdd20234f3b.png">
<img width="485" alt="screen shot 2017-04-22 at 12 50 54 pm" src="https://cloud.githubusercontent.com/assets/4975959/25306393/5ef3d14e-275a-11e7-9a27-d5b8b7cc4676.png">

_Desired:_
<img width="666" alt="screen shot 2017-04-22 at 12 48 07 pm" src="https://cloud.githubusercontent.com/assets/4975959/25306373/01644bf8-275a-11e7-9929-35b31d2b3ec6.png">
<img width="772" alt="screen shot 2017-05-08 at 11 25 46 am" src="https://cloud.githubusercontent.com/assets/4975959/25811404/3217c7fa-33e1-11e7-870c-4455015432af.png">

**Comment by lakohl** [comment]
Alternate option is to make the spacing above and below the dividing line 30px (see below)
<img width="741" alt="screen shot 2017-05-08 at 11 24 21 am" src="https://cloud.githubusercontent.com/assets/4975959/25811450/57a1b4ea-33e1-11e7-9f30-7c9e7edfcf00.png">
@shellicious do you remember what you were using in Certification?

**Comment by Sjones352** [comment]
@lakohl Should I change this too. <h1> Route Claim <h2> Send Email Notification

<img width="1071" alt="screen shot 2017-05-16 at 3 46 52 pm" src="https://cloud.githubusercontent.com/assets/23080951/26125147/1c4c5f2a-3a4f-11e7-8369-1d9b1cc17ed9.png">

**Comment by lakohl** [comment]
@Sjones352 Yes! Good catch. I updated the AC.

**Comment by mmlumba** [comment]
Original AC for 7 (changed to make clearer technical requirements):
> Verify that there is 40px of padding above and below the gray line.

**Comment by Sjones352** [comment]
Some screenshots

**Add VBMS Note**
<img width="1043" alt="screen shot 2017-05-16 at 4 30 17 pm" src="https://cloud.githubusercontent.com/assets/23080951/26207861/b016465e-3bb6-11e7-91a4-5606595712a5.png">

**Send Email Notification**
<img width="880" alt="screen shot 2017-05-17 at 10 18 45 pm" src="https://cloud.githubusercontent.com/assets/23080951/26207938/e66c0982-3bb6-11e7-854d-3d9532944e9d.png">

**Route Claim: Confirm VACOLS update and Add VBMS Note**
<img width="916" alt="screen shot 2017-05-17 at 10 13 52 pm" src="https://cloud.githubusercontent.com/assets/23080951/26208007/0f188f4a-3bb7-11e7-83e4-5e1b175305c8.png">

**Comment by astewarttistatech** [comment]
So far current view
![h1andh2tags](https://cloud.githubusercontent.com/assets/23038505/26211651/fe7c7d22-3bc0-11e7-957e-267715d272bf.gif)

**Comment by Sjones352** [comment]
@astewarttistatech your current view is wrong.

**Comment by astewarttistatech** [comment]
I am not seeing these changes in the current layout of UAT.
 
The licecap that shows all of this is too large.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT, Dev, and Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Navigate to the scenarios shown in the AC in Dispatch as a caseworker
2. Validate the header tags implemented. 

Screenshots: 
![h1andh2tags](https://cloud.githubusercontent.com/assets/23038505/26256324/943adf1a-3c8a-11e7-8260-d070c21cb20e.gif)
![h1andh2tags1](https://cloud.githubusercontent.com/assets/23038505/26256326/943ba59e-3c8a-11e7-8f66-db44bc583ebf.gif)
![h1andh2tags2](https://cloud.githubusercontent.com/assets/23038505/26256325/943ae8ac-3c8a-11e7-8a76-d88597919bea.gif)
