### ISSUE TITLE
Bug: Misleading error message displayed when user is trying to assign a case to an attorney

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#15756]
## Description

The user is seeing this error message:

```
One or more tasks couldn't be assigned. Reassign tasks to a judge on the case details screen
```

even though no error actually occurs on the server. This appears to be related to the request taking more than 5 minutes. The user should see an appropriate error message that has more accurate next steps.

## Impact

This error message seems to be instructing the user to fix something when no error actually occurred. Completing this ticket should resolve some confusion that users are having when they see this error message.

## Out of scope

Fixing the performance of the `/judge_assign_tasks` route

## Steps to reproduce
* Running locally, choose judge BVAAABSHIRE (VACO)
* Hit the "switch views" dropdown in the lower-upper right to get to the list of tasks
* Go to your running docker dashboard and click into Caseflow
* Hit the stop button on VACOLS
* Go back to the browser, select some tasks in the list, and reassign them to someone
* View desired uninformative error

## Acceptance criteria
- [ ] Ensure that a helpful error message displays if the request to assign an attorney a task times out

## Background/context/resources

- Slack Discussions:
  - https://dsva.slack.com/archives/CHX8FMP28/p1609447904331600
  - https://dsva.slack.com/archives/CHX8FMP28/p1609945241375500

## Technical notes

This appears to be a default catch-all error message:

https://github.com/department-of-veterans-affairs/caseflow/blob/e5964c41e1ab6492ab41274d17ecb28bc48ccd9c/client/app/queue/components/AssignToAttorneyWidget.jsx#L169-L173

**Comment by yoomlam** [comment]
It sounds like the current workaround is to refresh the page to confirm that the assignment action actually took.

**Comment by jjohni** [comment]
Checking on the status if this.

**Comment by lomky** [comment]
[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)
```bash
1 | 
2 | |||||||
3 | |||||
5 | 
8 | 
```

#### Why 2?
* Should be a fairly straight-forward error change

#### Why 3?
* May be a little code archeology, and dancing around the root cause of a page seemingly timing out

**Comment by jjohni** [comment]
Checking on the status of this?
