### ISSUE TITLE
[Flaky Test] ColocatedTaskListView jest failure

### ISSUE THREAD

**Issue by n1zyy** [department-of-veterans-affairs/caseflow#15764]
## Description

I see references to this happening in the past, but not a ticket for it, so here we are.

**ColocatedTaskListView Assigned tab shows only new tasks and tasks with a completed hold - ColocatedTaskListView**
```
AssertionError: expected '0 days' to equal '1 day'
    at Context.eval (webpack-internal:///./test/karma/queue/ColocatedTaskListView-test.js:380:83)
    at Test.Runnable.run (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
```

## Background/context/resources

 - Circle CI Error:  [ColocatedTaskListView Assigned tab shows only new tasks and tasks with a completed hold - ColocatedTaskListView](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/37836/workflows/21fb2375-cc3a-4574-a90b-683fa99333b1/jobs/142338)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

Previous failures:
- [August 2020](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/33709/workflows/f8d10367-4535-4b11-87b6-e5bece20525b/jobs/124076)
- [November 2020](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/36859/workflows/be11d98a-b538-4273-89e1-b220fb687ad3/jobs/137613)
- September 2018 (!) thread in #appeals-engineering maybe related: "ColocatedTaskListView New tab shows only new tasks - ColocatedTaskListView"

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by jcq** [comment]
Note that this is in an old Karma test; rather than fixing there, this should be an opportunity to rewrite as a Jest test

**Comment by n1zyy** [comment]
JC's IP sprint team has identified this as a priority, but to keep everything in this ticket -- this seems to be the test that is known to fail after 7pm, so getting this one ported over would be a win-win.
