### ISSUE TITLE
Investigate why the document_service is returning duplicate records

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15798]
## Description
The `document_service` used by DocumentFetcher seems to return duplicate documents. Investigate why -- could be a bug in how Efolder Express (one of the 2 `document_services`s) is retrieving documents or returning documents, or it may be reflect some oddity about the source of these documents (i.e., VBMS or VVA/LCM).

See Sentry alert mentioned in [this investigation](https://github.com/department-of-veterans-affairs/caseflow/pull/15787#issuecomment-761266148) following PR: Bulk upsert in DocumentFetcher with duplicate detection #15787.

## Impact

Determining the root cause of the duplicate documents, can result in cleaning up code in document_fetcher that does deduplication and fixing a bug upstream (in Efolder Express).

## Acceptance criteria
- [ ] Identify root cause of the duplicate documents
- [ ] Fix the problem or file a ticket to fix the problem

**Comment by araposo-tistatech** [comment]
Timeboxing to 3

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1623
