### ISSUE TITLE
Search | Empty state

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1581]
**Story**
When drafting a decision on a case, I want to know if my search words match 0 documents.

**Description**
- Show an empty state that explains 0 results have been found

## Acceptance Criteria
- Validate that the # of document next to search box is always 0
- Validate that `go back to the documents list` is a text link that clears filter
- Validate that expand all button is disabled
- Validate that there is a "remove" icon next at the far right of the search box that clears search result [Remove icon svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Remove%20Icon.svg) 
- Validate the [status message from style guide](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/StyleGuide/StyleGuideStatusMessages.jsx)

## Mockup 
![image](https://cloud.githubusercontent.com/assets/13420618/25045356/f08ce2c4-20f9-11e7-956e-6caf66212436.png)

## Copy

Search results not found

Sorry! We couldn’t find anything for “[what was inserted in searchbox].”
Please search again or go back to the documents list. 

## Related 

#1486

**Comment by abbyraskin** [comment]
Add link to styleguide

**Comment by NickHeiner** [comment]
The mock has a period at the end of the search query, but the AC in the ticket does not.

Mock:
> Sorry! We couldn’t find anything for “[what was inserted in searchbox].”

AC:
> Sorry! We couldn’t find anything for “[what was inserted in searchbox]”

Which should we do? 

I prefer

> Sorry! We couldn’t find anything for “[what was inserted in searchbox]”.

**Comment by gnakm** [comment]
Yes let's add the period.

**Comment by NickHeiner** [comment]
So, you want the "mock" option above?

**Comment by gnakm** [comment]
Yes.

**Comment by NickHeiner** [comment]
Why does the story say:

> When drafting a decision on a case, I want to search by category label, so I can filter my list of documents by category, and also know if documents cannot be filtered by my search words.

Shouldn't it just be:

> When drafting a decision on a case, I want to know if my search words match 0 documents.

**Comment by abbyraskin** [comment]
@NickHeiner the story used to be about search results, but was repurposed for empty state. I'll update it :)

**Comment by kierachell** [comment]
## Whitespace validation is kinda weird
## And so it numeric??
![searchspace](https://cloud.githubusercontent.com/assets/18075411/26504154/66d42a86-4211-11e7-89fe-5ca57523709e.gif)

**Comment by NickHeiner** [comment]
The reason adding a `9` produces additional results is that it matches `09` in the date of the SSOC doc.

**Comment by kierachell** [comment]
**PASSED**
