### ISSUE TITLE
Investigate bypass of permissions mechanism in eFolder search

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#15829]
## Description
Received a support [issue](https://dsva.slack.com/archives/CHX8FMP28/p1611321338059900) stating that users in eFolder are able to bypass the permissions on veteran's folders they don't have access to simply by clicking the Search button a second time. Issue was confirmed upon user impersonation with multiple veterans.

## Acceptance criteria
- [ ] Investigate what is occurring in the code that allows this behavior
- [ ] File ticket to fix if an immediate fix is too complicated

**Comment by ferristseng** [comment]
Description of the Issue:

![eFolder Digram-2](https://user-images.githubusercontent.com/1298274/106028014-71c60e00-6099-11eb-9eba-148e15635079.png)
