### ISSUE TITLE
Add certification v2 test cases with SSOCs [2]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1586]
We should have test cases that have SSOCs for certification V2.

Make sure
- unit tests cover the SSOC-related parts of the React component
- if necessary, feature tests cover a scenario with SSOCs.
- the fake appeals repository should contain an appeal with SSOCs

**Comment by nickheiner-usds** [comment]
@amprokop is this still relevant?

**Comment by laurjpeterson** [comment]
We haven't worked on this in a while. Closing.
