### ISSUE TITLE
Ensure that DocumentsCheckTable.jsx correctly handles the case with mismatched documents. [1]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1587]
It looks like we handle the scenario where documents match correctly, but it doesn't seem like the logic is correct for the documents check table in the scenario where VACOLS and VBMS dates don't match.

If the documents don't match, in the VBMS column we should display "Not found"

Certification v1 code:
```
<tr id="<%= name.downcase.parameterize %>-match">
  <td> <%= match ? svg_icon(:found) : svg_icon(:missing) %> </td>
  <td> <%= name %> </td>
  <td> <%= date.to_formatted_s(:short_date) %> </td>
  <td> <%= match ? date.to_formatted_s(:short_date) : "Not found" %> </td>
</tr>

```

Certification v2 code:
```        
<tr id="form9-match">
          <td>{props.form9Match ? <FoundIcon/> : <NotFoundIcon/>}</td>
          <td>Form 9</td>
          <td>{props.form9Date}</td>
          <td>{props.form9Date}</td>
        </tr>
        <tr id="nod-match">
          <td>{props.nodMatch ? <FoundIcon/> : <NotFoundIcon/>}</td>
          <td>NOD</td>
          <td>{props.nodDate}</td>
          <td>{props.nodDate}</td>
        </tr>
        <tr id="soc-match">
          <td>{props.socMatch ? <FoundIcon/> : <NotFoundIcon/>}</td>
          <td>SOC</td>
          <td>{props.socDate}</td>
          <td>{props.socDate}</td>
        </tr>
```

Also, let's add a unit test for the new `ssoc_dates_with_match` method in spec/models/certification_spec.rb.

**Comment by nemodjuric** [comment]
ssoc_dates_with_matches unit test seems to belong to appeal_spec.rb, no?

**Comment by kierachell** [comment]
The error shows that `documents were not found in VBMS`.
Is there a scenario where the document is present, but dates mismatch?
1. VACOLS date for NOD is `03/29/2001` but in VBMS it's uploaded at `04/01/2001`?
<img width="1049" alt="screen shot 2017-04-25 at 3 51 05 pm" src="https://cloud.githubusercontent.com/assets/18075411/25404823/4a8d43da-29cf-11e7-836f-3da4d83c2adf.png">
<img width="979" alt="screen shot 2017-04-25 at 3 51 10 pm" src="https://cloud.githubusercontent.com/assets/18075411/25404822/4a8cef8e-29cf-11e7-8666-ef33359ff54f.png">

**Comment by amprokop** [comment]
hmmm

@kierachell —

> If the document dates don't match, in the VBMS column we should display "Not found"

Basically, if there is no VBMS date that matches a VACOLS date, then we should display "Not found" in the VBMS column. Can you test this again? I think it should be right

**Comment by kierachell** [comment]
**PASSED**

<img width="969" alt="screen shot 2017-05-02 at 4 42 14 pm" src="https://cloud.githubusercontent.com/assets/18075411/25639044/7fba72ba-2f58-11e7-8f92-61f6881e7568.png">
<img width="1057" alt="screen shot 2017-05-02 at 4 43 45 pm" src="https://cloud.githubusercontent.com/assets/18075411/25639043/7fb431ca-2f58-11e7-8a19-6e9ad706f92f.png">
