### ISSUE TITLE
Remove the "Mark complete" action for SendCavcRemandProcessedLetterTask assigned to an org

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15898]
## Description
Remove the "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to an org.
This will enforce assignment to a user prior to marking the send task complete.

## Acceptance criteria
- [ ] No "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to an org
- [ ] "Mark complete" action for `SendCavcRemandProcessedLetterTask` that is assigned to a user

## Background/context/resources
[Slack](https://dsva.slack.com/archives/CJL810329/p1612825580210900)

**Comment by ajspotts** [comment]
[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)
```bash
1 | |
2 | ||||||||
3 | 
5 | 
8 | 
```


 
#### Why 1?
* Easy solution

#### Why 2?
* Fairly straightforward, just be wary of tricky task behaviors
* Update tests
