### ISSUE TITLE
Search Button has magnifying glass symbol underneath the Search text

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1606]
When the commons reference is updated we see a magnifying glass behind the Search button. This is because our button uses the USWDS search classes, but also writes search as the text. We should do one or the other.

<img width="980" alt="screen shot 2017-04-17 at 2 08 31 pm" src="https://cloud.githubusercontent.com/assets/3885236/25098695/84c247de-2377-11e7-80f3-cd9785b537b2.png">

**Comment by kierachell** [comment]
**PASSED**
seems to be fixed now
<img width="772" alt="screen shot 2017-05-13 at 3 57 22 pm" src="https://cloud.githubusercontent.com/assets/18075411/26028769/e13ad9d6-37f4-11e7-93c1-9bab77d88728.png">

**Comment by mdbenjam** [comment]
Has the commons gem reference been updated? This will only show up when that happens. I'm not sure when that will be, but eventually I think this will come back.
