### ISSUE TITLE
Certain job failures should be more loud

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1611]
This morning, the prepare establish claim task failed. Which was pretty bad and we didn't notice it. We need a better way to alert us if important jobs fail rather than.

Or maybe we just need a smarter retry mechanism.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/144/

**Comment by kierachell** [comment]
It shows up pretty much every night on `uat`
internal-dsva-appeals-sentry-uat-102776152.us-gov-west-1.elb.amazonaws.com/sentry/caseflow-uat/issues/185/

**Comment by shanear** [comment]
dup of https://github.com/department-of-veterans-affairs/appeals-deployment/issues/586, closing
