### ISSUE TITLE
Document Viewer | Going between document causes Category labels to act weird

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1613]
# Description
When switching between documents and adding category labels the documents get relabeled in a strange manner.

## Reproduction Steps

**Scenario 1 -**

1. Go view a document

1. Label it.

1. Go left or right to another document.

1. Label it too.

1. Go to another document (left or right) and find it already labeled???

1. Go to *View all documents* and find that documents are labeled in some other way!?

**Validated in the following Envrionment(s)**
- [X] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Switching documents]_**
![documentcheckboxess](https://cloud.githubusercontent.com/assets/18075411/25129486/4ebed446-240c-11e7-997a-b618cd33127e.gif)

# Related Issues
**_Engineering_**
#1274

**Comment by NickHeiner** [comment]
Yes, this is fixed by #1602.

**Comment by NickHeiner** [comment]
Addressed in  9476e44.

**Comment by kierachell** [comment]
**PASSED**
![categories](https://cloud.githubusercontent.com/assets/18075411/25193402/03523e04-2505-11e7-8942-ef3921f1d92f.gif)
