### ISSUE TITLE
[Flaky Test] SCM Team access to judge movement features

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#16163]
https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/41445/workflows/00b84552-0479-48fd-ab47-2399c05df22d/jobs/159840/tests#failed-test-0

## Description

spec/feature/queue/scm_judge_assignment_spec.rb

SCM Team access to judge movement features SCM user can view judge's queue can perform the same case movement actions as a judge on ama appeals

## Background/context/resources

 - Circle CI Error:  [  ]()
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by araposo-tistatech** [comment]
Timeboxing to a 3
