### ISSUE TITLE
Prevent creation of second JudgeCaseReview

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#16170]
## Description
Originating from https://github.com/department-of-veterans-affairs/dsva-vacols/issues/178#issuecomment-825702854

PR #16154 prevents dispatching an appeal before QR is complete, but still allows another `JudgeCaseReview` record to be created.

Time permitting, investigate what to do with the 2500+ appeals with multiple `JudgeCaseReview` records. https://github.com/department-of-veterans-affairs/dsva-vacols/issues/178#issuecomment-824073960
```ruby
res=JudgeCaseReview.group(:task_id).count.select{|k,count| count>1}
res.count
=> 2577
# TODO: investigate why so many
res.map{|tid,c| a=Task.find(tid.split('-').first)&.appeal rescue LegacyAppeal.find_by_vacols_id(tid.split('-').first); [a.uuid, a.stream_docket_number, a.created_at] rescue [a.vacols_id, a.created_at] }.compact
```
(copied from #13416)

## Impact
Prevents bad or misleading data, i.e., which `JudgeCaseReview` record should be used if there are multiple per appeal? Right now, we use the latest record.

## Out of scope
Deleting/Merging/Addressing extraneous `JudgeCaseReview` records.

## Acceptance criteria
- [ ] multiple `JudgeCaseReview` records per appeal cannot be created
- [ ] The user is presented with an error message when user attempts to create another `JudgeCaseReview` record per appeal

## Background/context/resources
https://dsva.slack.com/archives/CJL810329/p1619188815249800?thread_ts=1618846940.036200&cid=CJL810329

## Technical notes

Product and Designers may be needed to determine if we need to allow judges to modify an existing JudgeCaseReview since they won't be able to create a new one.

From @jcq 
> The actual engineering shouldn't be too difficult, but there's definitely involvement from design as to what would be the best UX. I'm not aware of any similar existing behaviors, but that doesn't necessarily mean that nothing exists. :sweat_smile:
> Various options that come to mind:
> 1. Put up an alert on the checkout form itself
> 2. Same as 1, but also disable all the fields and/or submit buttons
> 3. Redirect to Case Details with an error alert that states why they weren't able to navigate to the checkout
> Option 1 is easiest, but happy to discuss more if/when product/design desires!

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1634

**Comment by yoomlam** [comment]
Related to @eileen-nava's PR #16072.
