### ISSUE TITLE
Styleguide | Side Navigation version 2 with sub nav

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1618]
**Story**
As a developer and designer, I want to easily and quickly find various components through the side navigation menu. 

## AC
Dropdown behavior
- [ ] When clicking the title, the side nav should expand to show the list of level two and jump to level 1 section. 
- [ ] At any point, when clicking on the title, the page should jump to that section.

List of Improvements 
- [ ] Make the following edits:
- Branding
  - Move Branding to the top, under Introduction
  - Put Logos under Branding
- Typography 
  - Under Typography, delete of **Headings and Body** and **Styles**
- Button
  - For all the subsections under Button ( Primary, Secondary, Disabled, Link, Toggle), take out the word "button" at the end of each word on the side nav.
- Dropdown menus
  - Under Dropdown menus, change Single Select Searchable Dropdown to Search Single Selection and change Creatable Searchable Multi-select Dropdown to Search Multiple Selection
- Checkboxes
  - Delete ":" after Horizontal Checkboxes
  - Change "Single Checkbox with value set" to H4
  - "Forced Vertical Checkboxes" should be H4, under "Vertical"
- Radio Buttons, 
  - Take out "Radio Button" after each subsection on the side nav. 
  - Horizontal Radio Button Forced Into Vertical Layout should be H4 under Horizontal Radio Button
  - Take out "Errors" after "Required Radio Button"

## Copy

- Introduction
- Branding
  - Logos
- Typography
  - Text Styles
  - Font Family
  - Text Accessibility 
- Colors
  - Palette
  - Logos
- Buttons
  - Primary
  - Secondary
  - Disabled
  - Link
  - Toggle
- Search
- Dropdown menus
  - Search Single Selection
  - Create and Search Multiple Selection
- Checkboxes
  - Single
  - Vertical
  - Horizontal
  - Required
  - Acknowledgements
- Radio Buttons
  - Vertical
  - Horizontal
- Data input
- Tables
  - Queues
- Tab
  - Without Icons
  - With Icons
- Accordions
  - Border
  - Borderless
- Form fields
  - Text input
  - Text area
  - Character limit
  - Inline Form
- Loaders
  - Small loader
  - Loading buttons
- Alerts
  - Alerts lite
- Layout
  - Navigation bar
  - User dropdown menu
  - Main content area
  - App canvas
  - Actions
  - Horizontal line
  - Footer
- Messages
   - Success
   - Status
   -  Alert
- Dashboard
- Modals
- Progress bar

**Comment by gnakm** [comment]
This is currently happening 🙍 
![image](https://cloud.githubusercontent.com/assets/13420618/26222264/577dacf4-3be7-11e7-94c6-a4fe3b836df4.png)

**Comment by kierachell** [comment]
**PASSED**
![cool](https://user-images.githubusercontent.com/18075411/33180502-eddd9870-d03a-11e7-934b-2e6077e5d23f.gif)
