### ISSUE TITLE
Address Case Movement actions during Quality Review

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#16205]
Resulting from investigating a potential SCM (Case Movement) bug from Mike Sanford: [Cannot Assign Task to Any Attorney #187](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/187).

For an SCM user, Caseflow offers an "Assign to attorney" task action if the appeal is in Quality Review (QR) -- due to this code: https://github.com/department-of-veterans-affairs/caseflow/blob/fa497c36effddc750a20c9c5e4480247b6fbdb75/app/models/tasks/attorney_task.rb#L80

See [Cannot Assign Task to Any Attorney #187](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/187) for details.  Since `AttorneyQualityReviewTask` inherits from `AttorneyTask`, it (inadvertently) gave SCM users some task actions that we didn't intend.

## Description

Decide whether we want to either:
1. remove SCM task actions when the case is in QR (easy implementation)
2. or enable SCM during QR (a fairly big effort)
3. or do 1 with the intent to do 2 in the future.

## Impact

Either remove the non-functional task action or make it (and other SCM actions and scenarios) work properly.

## Acceptance criteria
- [ ] TBD

## Background/context/resources

[Investigation thread](https://dsva.slack.com/archives/CJL810329/p1620134661066600)

## Technical notes

See PR #16206 for replication instructions.

Currently for the "Assign to attorney" task action, the Submit button goes to `/judge/assign_tasks` with a payload like this:
![image](https://user-images.githubusercontent.com/55255674/117068823-5ea68800-acf1-11eb-9491-347777da7987.png)
(from running https://github.com/department-of-veterans-affairs/caseflow/blob/644ae484d8190d0a6c2714b4525d7e5140d34dc9/spec/feature/queue/scm_judge_assignment_spec.rb#L158)

This is trying to create a `JudgeAssignTask`, which is not what we want during QR since `JudgeAssignTask` only occurs during the [Decision Phase](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md#decision-phase). A different task needs to be created depending on the SCM task action being performed and the appeal's state.

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1633
