### ISSUE TITLE
Schedule Veteran Form - Always Show Time Selection When Hearing Day Selected

### ISSUE THREAD

**Issue by charleyf** [department-of-veterans-affairs/caseflow#16253]
## Description
It's possible to have a hearing day selected in the "Hearing Date" dropdown, but have no time selection UI appear on the screen. This makes it impossible to select a time for the hearing.

## Acceptance criteria
- [ ] Following the steps below will always show a time selection when there's a hearing day selected.

## Steps to Reproduce
1.  For this to work you need whatever current day it is (05/17 as I write this) to have both
    - A virtual hearing day
    - A hearing day in the St. Petersburg RO
    - Create those two hearing days if they don't exist.
2. Get a veteran to schedule by following these steps. If you take a shortcut reproducing probably won't work because choosing an RO here changes what happens on the schedule screen.
    - Go to the scheduled hearings page: http://localhost:3000/hearings/schedule
    - Click the "Schedule Veterans" button.
    - Select the "St. Petersburg, FL" RO from the dropdown.
    - Click the "AMA Veterans Waiting" tab
    - Click the name of the first veteran.
    - Choose "Schedule Veteran" from the dropdown
3. Look at the Schedule Veteran Form, which looks correct
    - You should be looking at the scheduling form for a veteran.
    - The "Hearing Type" should default to "Video"
    - The "Regional Office" should default to "St. Petersburg, FL"
    - The "Hearing Date" should default to todays date. <- If this doesn't happen, you need to create a hearing day.
    - You should see a "Hearing Time" selection dropdown.
4. Change the "Hearing Type" dropdown to "Virtual"
    - You should still see a "Hearing Time" selection dropdown.
    - The "Hearing Date" dropdown should still be filled in.
5. Change the "Regional Office" dropdown to "Virtual"
    - You should now see Timeslots and a "Choose a custom time" link.
    - The "Hearing Date" dropdown should still be filled in.
6. Change the "Regional Office" dropdown back to "St. Petersburg, FL".
    - The "Hearing Date" dropdown should still be filled in (though this behavior may be what we want to change).
    - **There is no way to select a time. No "Hearing Time" dropdown/radio or timeslots.**

**Comment by tomas-nava** [comment]
I moved this issue into Jira as [CASEFLOW-1752](https://vajira.max.gov/browse/CASEFLOW-1752)
