### ISSUE TITLE
Dispatch | Veteran and appellant appear switched - Spina Bifida legacy appeals

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#16302]
## User or job story
User story: The user is using Dispatch. When he clicks on establish the next claim, Caseflow take him to an all white screen. There is no error and the page never loads. The user is using Chrome.

## Background
This is a documentation ticket, intended for use to be transferred to Jira.

This is from batteam request [INC18113434](https://dsva.slack.com/archives/CHX8FMP28/p1621875486077500). The impacted legacy appeal had a nil veteran. This was causing an error trying to fetch end products on the undefined veteran, leading to the white page in Dispatch.

We were able to find the veteran's SSN in the appellant information, and the veteran information was actually for the veteran's child. We followed batteam instructions in this case to do some switching, but some of the data such as the appellant name was still out of date because that was not included.  When looking into that, Yoom checked in with Jed.

After checking with Jed, we learned that this was a spina bifida claim, and that the data structure was correct in this instance. Jed reverted the data, and a note has been added to the Batteam quickref instructions:
https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#legacy-appeal-missing-a-veteran-or-veteran-record-is-stale

## Proposals for investigation
1. If we can reliably detect Spina bifida claims (this involves looking at the issues), we can use the veteran's data stored in the appellant info to find the veteran
2. We could potentially use this as a fallback always, whether for spina bifida cases or not
3. We could check if Dispatch can continue to operate properly without a found veteran, if we do something like add safe operators

Oh interesting, so the swap was correct for Spina Bifida appeals. The sentry error was coming up due to an error with the list of end products, so there may be an engineering fix. I’m not sure though, it seems like not having a veteran on the appeal would cause other problems. If we can detect the Spina Bifida claims, we can fetch the veteran using the appellant’s info if they’re reliably switched.

## Acceptance criteria
- [ ] Investigate and determine proper solution

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1688

**Comment by yoomlam** [comment]
Legacy appeal `id: 1472110` appears to be stuck until a solution is found. The Bat Team Quick Ref instructs to "temporarily unblocks the user by unassigning this task from the user, and putting it back to the bottom of the queue of dispatch tasks to get assigned", which explains why it has been a recurring problem for Dispatch users -- see https://dsva.slack.com/archives/CHX8FMP28/p1624542860081900
