### ISSUE TITLE
Remove reviewForm from dispatch React state

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1630]
Migrate the existing reviewForm from react state to Redux

**Comment by joofsh** [comment]
To QA: No changes to functionality, just ensure things didn't break

**Comment by kierachell** [comment]
## Remand with Manlincon Compliance
<img width="564" alt="screen shot 2017-05-02 at 8 10 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/25644357/71322286-2f73-11e7-9859-9186b6fa99b8.png">

**Comment by joofsh** [comment]
Are there any other special issues checked? I can't repro this
![Uploading Screen Shot 2017-05-03 at 10.25.24 AM.png…]()
<img width="631" alt="screen shot 2017-05-03 at 10 25 30 am" src="https://cloud.githubusercontent.com/assets/2256237/25665206/e1e06430-2fea-11e7-88e9-62a2bc600f34.png">

**Comment by kierachell** [comment]
**PASSED**
Checked with existing RegOffs and Stations. is working now.

Will follow up on missing Station IDs with Chris.
