### ISSUE TITLE
Dispatch | Sensitivity Error

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1632]
Somehow a sensitivity issue made it through, need to check this out:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/153/

**Comment by shanear** [comment]
We are doing introduced a user bug again. Updating this to high priority and adding a PR for the fix ASAP.

**Comment by kierachell** [comment]
Requested varying sensitivity users from Raul...waiting on response...

**Comment by kierachell** [comment]
**PASSED**
Tried different sensitivity levels and it didn't seem to affect different user accounts we have.
