### ISSUE TITLE
Refactor StyleGuideLayout.jsx container in style guide

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#1634]
Currently we have several style guide issues that cover different parts of the main Caseflow application layout that are to be added to the style guide:
#1085 - Introduction to layouts
#1086 - Navigation bar and header
#1089 - Actions
#1090 - Footer

All parts of the main layout (as described above) live in `app/views/layouts/application.html.erb`.
Questions:
1. Should we break parts of their layout into individual components?
2. Is there a need to turn these into React components?

**Update 5/12**
It is decided that all layout components in `Caseflow Commons` be added in the following manner:
1. All descriptions for each component (as well as component titles) are added on the main `StyleGuideLayout.jsx` page
2. The code for each component (if applicable) lives in its own container (ie `StyleGuideAction`, `StyleGuideFooter`, `StyleGuideUserdropdown`, `StyleGuideNavigationBar`)

**Comment by Sjones352** [comment]
Closing this because it's related to #1085
