### ISSUE TITLE
Stats Page | Add Establish Claim Tasks Prepared for ARC

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1638]
As a manager or a Caseflow team member, I would like to know stats on how many tasks were prepared in a given day.

## AC
1. Verify that there is a section on the dispatch stats page for tasks ready for Claims Establishment called "Establish Claim Tasks with Decisions Uploaded to VBMS for {TIME_PERIOD}" that has the following stat boxes:
  - All
  - Full Grants
  - Partial Grants & Remands
2. Verify "Establish Claim Tasks Identified" to "Establish Claim Tasks Identified from VACOLS"

## Technical Notes
In order to do this we will have to begin recording the time each task was prepared in a `prepared_at` column.

**Comment by slj** [comment]
Revised stats:
![dispatch_stats](https://cloud.githubusercontent.com/assets/1053255/25724953/c9bd2698-30eb-11e7-8e2a-09a893421b2b.gif)

**Comment by kierachell** [comment]
**PASSED**

<img width="1122" alt="screen shot 2017-05-05 at 2 10 40 pm" src="https://cloud.githubusercontent.com/assets/18075411/25758460/a81b33d4-319c-11e7-9f98-1a3cb95ad06d.png">
