### ISSUE TITLE
npm run test:karma:watch is broken

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1639]
Running `test:karma:watch` does not properly run the test suite.

Steps to reproduce:
- Run `test:karma:watch` on mater, all tests pass
- Save a file, let the tests run again. Tests 54 will fail

Also: Is there a way to get better output from karma? Preferably both in the console and in the browser

**Comment by NickHeiner** [comment]
from https://github.com/department-of-veterans-affairs/caseflow/pull/1589:

![image](https://cloud.githubusercontent.com/assets/829827/25203017/970f9c52-2525-11e7-90bb-b3a8d4ac2e56.png)

Well, I guess that answers that question. :smile:

**Comment by NickHeiner** [comment]
To make the tests pass every time you run them, apply the following diff:

```diff
diff --git a/client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx b/client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
index 04e95765..2b939d3e 100644
--- a/client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
+++ b/client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
@@ -19,7 +19,7 @@ export class AssociatePage extends React.Component {
 
   componentWillMount() {
     if (!this.props.endProducts.length) {
-      this.props.history.goBack();
+      // this.props.history.goBack();
     }
   }
 
diff --git a/client/test/karma/containers/EstablishClaim-test.js b/client/test/karma/containers/EstablishClaim-test.js
index d5209836..50d188c4 100644
--- a/client/test/karma/containers/EstablishClaim-test.js
+++ b/client/test/karma/containers/EstablishClaim-test.js
@@ -57,7 +57,7 @@ describe('EstablishClaim', () => {
         expect(wrapper.state().page).to.equal('decision');
       });
 
-      it('redirects to decision if no existing EPs', (done) => {
+      xit('redirects to decision if no existing EPs', (done) => {
         // Add a listener to the history object and look for the "go back" POP event
         let unlisten = wrapper.state().history.listen((location, action) => {
           if (action === 'POP') {

```

This test is validating behavior of going to different browser pages. Karma wants us to stay on the same page, because that's the page that it sets up to run the unit tests. We have a few options here:

1. Declare that Karma tests will henceforth only test unit logic, and tests that involve modifying `window.location` are more feature/integration tests, and belong in capybara.
1. Modify the test to do a better job of mocking, so the page is not actually reloaded.
1. Move this test back to `client/test/node`, and worry about this later.

These options are roughly ranked in the order of my preference. What does everyone else think?

**Comment by NickHeiner** [comment]
I will look into getting more test output on the command line as well.

**Comment by NickHeiner** [comment]
@joofsh can I get your feedback on the above when you get a chance?

**Comment by joofsh** [comment]
I would probably prefer option 2. I imagine testing rich UIs (like Reader) would require navigating between pages (doesn't the URL change when you click into a document?). 

If we go with option 1, we should post it in #appeal-engineering to get feedback. I'm hesitant to go with this option because it makes us further depending on a monolith rails/react hybrid stack. It will make it more difficult to eventually split the frontend out to a separate repo (though maybe we never want to anyway). 

If we do go with option 2 long term, I'm fine moving it back to `test/node` until we fix the test (like we eventually should do for all the node tests)

**Comment by joofsh** [comment]
In this specific case though, these tests do feel more appropriate in capybara...

**Comment by NickHeiner** [comment]
This will enable browser console logging to show up in the terminal:

```diff
diff --git a/client/karma.conf.js b/client/karma.conf.js
index 5ee54033..11db6f89 100644
--- a/client/karma.conf.js
+++ b/client/karma.conf.js
@@ -1,7 +1,7 @@
 const _ = require('lodash');
 const webpackConfig = require('./webpack.config.js');
 
-const karmaTestPattern = 'test/karma/**/*-test.js';
+const karmaTestPattern = 'test/karma/constants/*-test.js';
 
 module.exports = function(config) {
   config.set({
@@ -9,6 +9,11 @@ module.exports = function(config) {
     frameworks: ['mocha'],
     singleRun: true,
 
+    browserConsoleLogOptions: {
+      terminal: true,
+      level: ''
+    },
+
     files: [
       { pattern: karmaTestPattern }
     ],
```
