### ISSUE TITLE
Confirm Hearing Save choices to DB

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1641]
- Create an actions/ConfirmHearing file and move the actions there. See `actions/ConfirmCaseDetails.js` and `ConfirmCaseDetails.jsx` for an example of this refactor
- Rename `hearingType` or `hearingTypes` to `hearingPreference` or `hearingPreference` everywhere in `ConfirmHearing` (and also in `reducer/index.js` and `constants/constants.js`
   - This is because we want the front-end name to match the name of the DB row

**Comment by laurjpeterson** [comment]
Old ticket, so closing.
