### ISSUE TITLE
[Flaky Test] case_details_spec.rb expects CASE_DETAILS_UNRECOGNIZED_POA

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#16431]
## Description

```
./spec/feature/queue/case_details_spec.rb:405:in `block (5 levels) in <top (required)>'
./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

```ruby
expect(page).to_not have_content(COPY::CASE_DETAILS_UNRECOGNIZED_POA)
```

## Background/context/resources

Case details attorney case details view when appellant is an attorney or unlisted claimant when an unrecognized appellant has a recognized POA details view contains POA information - spec.feature.queue.case_details_spec

 - Circle CI Error:  [Case details attorney case details view when appellant is an attorney or unlisted claimant when an unrecognized appellant has a recognized POA details view contains POA information - spec.feature.queue.case_details_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/43988/workflows/8e7ab7dc-7fa8-49d8-9438-ef0b5ba90e5d/jobs/172141)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by yoomlam** [comment]
Another one: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/44113/workflows/90097142-4711-49e2-9740-ac2111423fbc/jobs/172748

**Comment by barshirtcliff** [comment]
fixing this [here](https://github.com/department-of-veterans-affairs/caseflow/pull/16426)
