### ISSUE TITLE
New EngineeringTask Tech Spec

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#16445]
# Adding an `EngineeringTask` to indicate that a Caseflow engineer is working on an appeal
**Drafter**: @yoomlam
**Discussion Meeting**:   July 14th, 2021 (during Caseflow Engineering Huddle)

## Context
Why are you creating this tech spec? 

The `AppealsWithNoTasksOrAllTasksOnHoldQuery` of the `StuckAppealsChecker` alerted on an appeal with no active task. Upon [investigation](https://dsva.slack.com/archives/CN3FQR4A1/p1625058496039500?thread_ts=1625049333.039300&cid=CN3FQR4A1), it turns out this is expected behavior for unrecognized appellants until a further workflow is implemented in Caseflow.  If an `EngineeringTask` was active on this appeal, there would not be an alert for this appeal.

Also, a new `EngineeringTask` would indicate to Caseflow users that engineers are working on the appeal, which would be informative and prevent false alarms for the Board that may see such appeals as being "stuck" in Tableau reports or similar. Also for reporting purposes, the duration that the `EngineeringTask` took can be deducted from the total time spent by the Caseflow user.

What information helps readers understand the rest of this tech spec? 

* https://github.com/department-of-veterans-affairs/caseflow/wiki/Tasks
* For reference, example task trees can be found from https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md#hearing-phase

A child `EngineeringTask` would block the parent task. In the case of the `StuckAppealsChecker` alert, a `BvaDispatchTask` would be on hold with an active `EngineeringTask` child, which blocks any progress on the parent `BvaDispatchTask` until the `EngineeringTask` is closed. Alternatively, an active `EngineeringTask` child could be created under the `RootTask` -- this would not block any specific user-worked task but would at least indicate that this appeal is being worked and is not stuck.

## Overview

There is benefit to adding a new `EngineeringTask`. It would keep Caseflow users aware of engineering work (including long-term Bat Team work) on an appeal, reduce false positives when checking for stuck appeals, and enable more accurate time-keeping when reporting on Caseflow users' time spent on an appeal.

Task `instructions` can be populated to further explain why an appeal has an `EngineeringTask`.

### Requirements and/or Acceptance Criteria

* indicate to Caseflow users that engineers are working on the appeal
* prevent false positives when checking for stuck appeals
* the `EngineeringTask` is assigned to a specific engineer when possible, otherwise it is assigned to the Caseflow user `css_id: "CSFLOW"`
* to indicate that we are not actively working on the appeal, the `EngineeringTask` can be put on hold, probably via a [`TimedHoldTask`](https://github.com/department-of-veterans-affairs/caseflow/wiki/Timed-Tasks#timedholdtask)

## Open Questions

* Do we want to show the `EngineeringTask` on the Case Details page? In the case timeline?
 

## Research Notes

# Tech Spec Process

 - [x] Tech spec drafter: Schedule time to discuss the tech spec with scrum team or whole engineering team depending on the scope of the tech spec
 - [x] Tech spec drafter: Facilitate that discussion.
 - [x] Other developers: Read the tech spec before arriving at the discussion.
 - [x] Other developers: Remind the tech spec drafter if a tech spec has been produced and no meeting has been scheduled.
 - [x] One or more solutions determined as viable paths forward
 - [ ] Tech spec drafter: Turn tech spec into next-step actionable tickets.
    - [ ] Write tickets as is necessary
    - [ ] Other developers provide more formal feedback as is necessary.
- [ ] Once the tech spec is finalized, open a PR to add it to the docs/tech-specs directory following [these instructions](https://github.com/department-of-veterans-affairs/caseflow/tree/master/docs/tech-specs/README.md)

**Comment by lowellrex** [comment]
This looks great @yoomlam, thanks so much for writing this up. I especially love using the instructions to explain why the appeal is on hold and being able to assign the tasks to individual Caseflow team members in addition to the organization. I agree that we need to determine whether these tasks should appear on the case details page (my intuition as that they should be visible), but I think that is product and design's call to make.

**Comment by yoomlam** [comment]
Action items from Caseflow Engineering Huddle:
- guidelines on when an EngineeringTask is added to an appeal
- guidelines for what type of information should go into the `instructions` field
- consider using for other non-`Appeal` decision reviews (@leikkisa)
- have Designers research what users would want to see for `EngineeringTask` in Case Details, Queue page (in the on-hold tab), etc. (@jcq)
- This would enable tracking engineering time spent on fixing appeals -- from the Board's perspective, how would the Caseflow Team be held accountable?
