### ISSUE TITLE
Implement FeatureToggle UI

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#1645]
Implement UI to turn on the FeatureToggles for specific features. 

We need a way to tell that a specific feature exists in the list if it isn't enabled. We'll likely need to have a cross-team eng discussion to get buy in from everyone. One possibility is to implement a `FeatureToggle.register` and to make devs call the `register` method to register a feature.

Let's:
- rename the System Admin-only `/functions` page to `/admin`
- Change "User Functions" and also adding another section to it: "Toggle Features". See the current page:
![image](https://cloud.githubusercontent.com/assets/3781835/25816052/cf3cbaa4-33f0-11e7-8922-55ec6dc73308.png)

Lastly, we should remove any code that associates Certification V2 with a role being present (it should be just associated with a feature being toggled)

Acceptance criteria:
- System Admin users should see a Feature Toggle UI, and they should be able to toggle all features on and off. 
- This feature toggle UI should only affect the current (i.e. system admin) user. It should toggle the feature only for that user, not for an RO or globally.
- "Certification V2" should not appear in the "Change Functions" and should appear in the "Toggle Features" section.

**Comment by laurjpeterson** [comment]
@aroltsch do you think we still need this ticket?

**Comment by aroltsch** [comment]
I don't think we need it anymore because we have feature toggles in appeals-deployment.
