### ISSUE TITLE
Zooming | When zoomed out the pages don't provide an accurate size prediction

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1649]
When a document is zoomed out, the non-rendered pages are too large, making it difficult to know where in the document you've scrolled. As pages render the scroll bar moves. We should use different page sizes for different zoom levels.
AC
- When zoomed in or out, the non-renderd pages should be similar in size to the rendered pages.
- When zoomed out in a large document, the scroll bar should be accurate and shouldn't change drastically when a user scrolls to trigger a render of new pages.

**Comment by kierachell** [comment]
![zoomcrawl](https://cloud.githubusercontent.com/assets/18075411/25394521/395fcfb0-29ac-11e7-9ab6-6c1a42b5d389.gif)

bonus: with comments crawling around

**Comment by kierachell** [comment]
## Zooming out to multiple pages move the scrollbar

I guess that's not exactly what you want to happen?

![shiftingzoom](https://cloud.githubusercontent.com/assets/18075411/25864870/00e73b0a-34bf-11e7-90d7-67ca1a66ab3d.gif)

**Comment by NickHeiner** [comment]
@gnakm @abbyraskin can you take a look at this? I agree that the behavior @kierachell pointed out is not ideal, but I think we've made an improvement from what it was before. Should we keep working on it in this ticket, or open a new ticket?

**Comment by gnakm** [comment]
@NickHeiner Yowza. We should open a new ticket for it. Let's get the original pain passed!

**Comment by abbyraskin** [comment]
@kierachell I'm moving this back, per conversation and new ticket above.

**Comment by kierachell** [comment]
**PASSED**
