### ISSUE TITLE
Document View | Scrollbar hides behind header

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1650]
# Description
When viewing a document with many pages (15+) the scrollbar is not  visible because it's behind the header

## Reproduction Steps

**Scenario 1 -**

1. Go to view a document with a bunch of pages

1. Try to click on the side to scroll down

1. Not find the scrollbar

1. Scroll some other way

1. Find the scrollbar peek from under the header.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Scrolly scroll]_**

![scrollbarhides](https://cloud.githubusercontent.com/assets/18075411/25242107/7b776226-25c6-11e7-89ad-3713fa609deb.gif)

**Comment by nicholasholtz** [comment]
This bug was beaten by #1647.

**Comment by kierachell** [comment]
**PASSED**
NOICE
![scrollyayy](https://cloud.githubusercontent.com/assets/18075411/25505067/4d9b7e0c-2b6e-11e7-9345-3eb536bb65b6.gif)
