### ISSUE TITLE
Success page | Assigned EP confirmation has incorrect title

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1651]
**Scenario 1 -**

1. Go to Dispatch and start a new claim

1. Assign the claim to existing EP

1. See "Congratulations!" instead of "Success!"

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Current View]_**

<img width="555" alt="screen shot 2017-04-20 at 11 37 53 am" src="https://cloud.githubusercontent.com/assets/18075411/25242160/b0a8e1f4-25c6-11e7-8865-ccf4af506e31.png">

## Related Issue

#1144

**Comment by joofsh** [comment]
@mmlumba  I think you fixed this in a ticket this sprint? If so can you verify & move this ticket to in validation?

**Comment by mmlumba** [comment]
Fixed in https://github.com/department-of-veterans-affairs/caseflow/issues/1524

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Reproduce:
1. Access Dispatch as a caseworker
2. Go through the happy path flow 
3. Validate the Success page title is "Success" and not " Congratulations"

Screenshots: 
<img width="1433" alt="screen shot 2017-05-10 at 8 09 01 am" src="https://cloud.githubusercontent.com/assets/23038505/25999288/85c7758a-36f2-11e7-809d-069d7f5db671.png">
