### ISSUE TITLE
Convert String keys to symbols

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1652]
There are areas where we represent states via strings instead of symbols such as https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/vacols/case.rb#L13-L23
and 

We currently use these strings 1) for looking up the value (knowing if a case is of the type we expect) and 2) for rending in the UI. This tightly couples 2 very different responsibilities. 

We should move to all symbols for representing a data state. Different logic should be used for what is rendered in the UI

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
