### ISSUE TITLE
Better error message on SSOI failure

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow#166]
This page shouldn't really come up much (either user signs in successfully or is redirected back to SSOI login page) but it did come up in dev/UAT testing:

![image](https://cloud.githubusercontent.com/assets/16327036/13683730/4b091f88-e6d6-11e5-8465-cf6cb14a25ab.png)

Just need to render the error page with appropriate status code and better phrasing.

**Comment by KHarshawat** [comment]
@lakohl Wanna take a stab at this? If you can come up with better messaging, add it here along with the styles you'd like to use and a contractor can take it from there.

**Comment by lakohl** [comment]
@orischwartz what actions did the user perform to get this message?/ when would it show?

**Comment by orischwartz** [comment]
@lakohl I don't know of a way to recreate this message consistently -- it comes up if the SAML flow (our single-signon provider) is misconfigured.

I'd say it's safe to close this as `wontfix` for now and revisit if a user ever reports it.

**Comment by lakohl** [comment]
OK

**Comment by lakohl** [comment]
Closing. not fixing this right now.
