### ISSUE TITLE
Hook up Cancellation Modal to Redux in Certification V2 [2]

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#1660]
The link 'If you can’t find the document, cancel this certification', displayed when the user is trying to certify an appeal without matching documents, does not work since we don't have the certification modal hooked up to Redux. We should refactor the CancelCertificationModal to be triggered by Redux.

![cantfinddocs](https://cloud.githubusercontent.com/assets/4960030/25249795/35bcff78-25e1-11e7-9676-db9da4f883ff.png)

Acceptance Criteria:
- Make sure the Cancel Certification link "If you can’t find the document, cancel this certification" mentioned above works and triggers the modal display.
- Verify that a new CertificationCancellation record is created after the user saves it.

**Comment by amprokop** [comment]
`DISPLAY_CANCELLATION_MODAL`
`START_MODAL_SUBMIT`
`SUCCESS_MODAL_SUBMIT`
`FAILURE_MODAL_SUBMIT`

**Comment by kierachell** [comment]
**PASSED**

even if it looks a bit wonky:
<img width="465" alt="screen shot 2017-05-08 at 12 25 08 pm" src="https://cloud.githubusercontent.com/assets/18075411/25813921/6e4e39fe-33e9-11e7-942a-37571dc01f41.png">
