### ISSUE TITLE
Deep Linking | Add deep links to Reader

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1662]
Currently Reader does not have deep linking so the back and refresh keys do not work. We should add React Router to our stack to fix this.
AC:
- When a user clicks on a document, the document should have a specific deep linked URL
- When a user clicks on the back button from the documents page, it should return to the list view page

**Comment by kierachell** [comment]
**PASSED**
NICE 👍 

Although it kinda messes with issue tagging
