### ISSUE TITLE
Zooming | Improve rendering while zooming

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1664]
Currently we render pages when you scroll to within view. This doesn't work well with zoomed out PDFs since lots of pages get rendered all at once. Instead, we should render pages one at a time so it is more orderly.

AC
- When zoomed out, all pages visible have been rendered.
- When clicking fit-to-screen the page should be zoomed such that the height of the page is equal to the height of the PDF view window.
- When zooming in or out, the zoomed version should scroll so that the same part of the document is visible.

**Comment by kierachell** [comment]
Not sure what's going on?
![zoomingaround](https://cloud.githubusercontent.com/assets/18075411/25394674/b4e9da5e-29ac-11e7-9c49-d94346958ba3.gif)

**Comment by kierachell** [comment]
#### When clicking fit-to-screen the page should be zoomed such that the height of the page is equal to the height of the PDF view window.

That is not happening
![zoomabout](https://cloud.githubusercontent.com/assets/18075411/25864725/7ce19512-34be-11e7-990e-eeaf7da5e7f0.gif)

**Comment by abbyraskin** [comment]
@kierachell putting this back into validation, per our conversation. I will create a ticket to reexamine the fit to screen interaction, e.g., to only have a single page in view

**Comment by kierachell** [comment]
**PASSED**
