### ISSUE TITLE
Documents List | Cursor: sortorder for Receipt Date and Document Type

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1666]
#### Description
When you mouse over the Document List and Receipt Date headers, the mouse should look like a clickable link -- the words themselves should look clickable, not just the icons.

#### Current State
![clickableornot](https://cloud.githubusercontent.com/assets/18075411/26167256/5540e886-3b04-11e7-99cb-f9db8af015b9.gif)

## Related
#1847

**Comment by abbyraskin** [comment]
This appears to be fixed

**Comment by abbyraskin** [comment]
The headers themselves (for sortable columns) should look clickable, not just the icons

**Comment by kierachell** [comment]
![clickableornot](https://cloud.githubusercontent.com/assets/18075411/26167256/5540e886-3b04-11e7-99cb-f9db8af015b9.gif)

**Comment by mdbenjam** [comment]
This is really the same as #1847. I'm closing this.
