### ISSUE TITLE
Document Viewer | Focus page so users can navigate up/down

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1669]
**Current state**
When a user uses the keyboard right/left arrows to move between documents, the page is not focused on the document, so they can't use the up/down arrows unless they select the document to manually focus it.

**Expected**
Focus on the document so people can use the hotkeys

## AC
- When a user opens a document or navigates between documents, we should focus the page so the  up/down arrows work without having to select the document

**Comment by NickHeiner** [comment]
This should be done after #2121.

**Comment by kierachell** [comment]
**PASSED**

![arrowaround](https://user-images.githubusercontent.com/18075411/27181570-1df8fc0c-51a6-11e7-96f5-5b0c55a6b86b.gif)
