### ISSUE TITLE
Fit to Screen | Moves back to first page

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1672]
Currently, when a user clicks on the "fit to screen" icon from inside a document, they are jumped to the first page in the document.

This shouldn't happen.

Instead, they should remain on the page they're actively viewing.

## Acceptance Criteria
- If a user clicks the "fit to screen" icon, they remain on the page they're currently viewing, rather than jumping them back to the first page in the document.

**Comment by kierachell** [comment]
**PASSED**
Zooming does not reset position;...but...zooms weird?
![zoomabout](https://cloud.githubusercontent.com/assets/18075411/25863952/a4b1dcee-34bb-11e7-8279-2f0f3ac3303d.gif)
