### ISSUE TITLE
Route Claim: Create End Product - supress acknowledgement letter

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1674]
Bug. We should default to Suppressing the Acknowledgement Letter by checking the 'Suppress Acknowledgement Letter' box at the bottom of the EP Creation page.

## **AC**
1. Verify that the 'Suppress Acknowledgement Letter' box on the Route Claim: Create End Product page is checked by default.

## **Mock**
<img width="823" alt="screen shot 2017-04-21 at 9 27 16 am" src="https://cloud.githubusercontent.com/assets/4975959/25279544/c3f5ab4e-2674-11e7-99a9-ed810c9884ef.png">

**Comment by lakohl** [comment]
@abbyraskin can you verify that the above should indeed be our default?

**Comment by abbyraskin** [comment]
@lakohl yep, correct! and just double checked with George who says the same.

**Comment by shanear** [comment]
I can work on this now.

**Comment by kierachell** [comment]
When did this start happening?
<img width="1091" alt="screen shot 2017-04-21 at 1 44 59 pm" src="https://cloud.githubusercontent.com/assets/18075411/25289708/c8b6b802-2698-11e7-9a59-5a56d5af68aa.png">


still happening

**Comment by abbyraskin** [comment]
@shanear is a wizard
