### ISSUE TITLE
Reader | Fix non-deterministic test failure

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1675]
This issue should be used to document any non-deterministic test failures in Reader.

1) We think we understand why this test was failing, and it has been skipped until we can fix it. #2028

```
Reader Scrolling renders pages
     Failure/Error: expect(page).to have_content("Banana. Banana who")
       expected to find text "Banana. Banana who" in "Caseflow Reader | VanBuren, Thomas, A (078640614) DSUSER (DSUSER) View all documents BVA Decision Page 1 of 2 Hide Menu Document Type: BVA Decision Receipt Date: 04/12/2017 Procedural Medical Other Evidence COMMENTS Add a comment"
     # ./spec/feature/reader_spec.rb:138:in `block (2 levels) in <top (required)>'

Failure/Error: expect(page).to have_content(:all, "Important Decision Document!!!")
       expected to find text "Important Decision Document!!!" in "Caseflow Reader (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script', '','ga');........`
```

2) Shane has seen this:https://dsva.slack.com/files/shane-russell-va/F5H8XRR7A/screen_shot_2017-05-25_at_10.13.32_am.png
![image](https://cloud.githubusercontent.com/assets/3885236/26453933/7897c590-4133-11e7-91eb-2bd540856571.png)

3. 
  ```
1) Reader Short list of documents Zooming changes the size of pages
     Failure/Error: expect(page).to have_content("IN THE APPEAL")
       expected to find text "IN THE APPEAL" in "Caseflow Reader | Anthony, Susan, A (2311) DSUSER (DSUSER) Back to all documents NOD Page 1 of 10|Document 3 of 3 Hide menu Document Type: NOD Receipt Date: 05/24/2017 Procedural Medical Other Evidence RELATED ISSUES Select or tag issue(s) COMMENTS Add a comment". (However, . it was found 8 times including non-visible text.)
     # ./spec/feature/reader_spec.rb:416:in `block (3 levels) in <top (required)>'
Finished in 7 minutes 46 seconds (files took 27.71 seconds to load)
562 examples, 1 failure, 1 pending
Failed examples:
rspec ./spec/feature/reader_spec.rb:406 # Reader Short list of documents Zooming changes the size of pages
```

**Comment by shanear** [comment]
<img width="1070" alt="screen shot 2017-05-26 at 7 52 46 am" src="https://cloud.githubusercontent.com/assets/1596259/26493604/7ed6a1a0-41e8-11e7-997c-28c73c7a7358.png">

Another one today

**Comment by shanear** [comment]
<img width="1067" alt="screen shot 2017-05-26 at 10 05 02 am" src="https://cloud.githubusercontent.com/assets/1596259/26497834/e27b106c-41fa-11e7-97c1-c9403e9e3bab.png">

and another

**Comment by shanear** [comment]
<img width="1050" alt="screen shot 2017-05-26 at 11 01 27 am" src="https://cloud.githubusercontent.com/assets/1596259/26500093/bf6d20d0-4202-11e7-863d-7a327c0d52df.png">

**Comment by NickHeiner** [comment]
@shanear that most recent test should now be fixed.

**Comment by NickHeiner** [comment]
![image](https://cloud.githubusercontent.com/assets/829827/26509091/40c53c4a-4225-11e7-83ac-4d01e9e0ee96.png)

This issue is clearly aXe's fault. It complains that our element does not have an `aria-label` attribute, but it does.

We should see if we can repro this with a failing test case in [aXe](https://github.com/dequelabs/axe-core) and fix their bug. If not, maybe there is a way to ignore this error?

**Comment by joofsh** [comment]
Reader zoom test is often failing for me locally on master:
<img width="1655" alt="screen shot 2017-06-01 at 4 10 55 pm" src="https://cloud.githubusercontent.com/assets/2256237/26698688/ebbedb60-46e4-11e7-8917-5368aa8a7c77.png">

**Comment by NickHeiner** [comment]
See also: #2305.

**Comment by mdbenjam** [comment]
Closing this for now. Since we've made Reader tests significantly better!
