### ISSUE TITLE
Styleguide Component | Layout section - App Canvas

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1677]
As a developer, I want to know what the specs of an App Canvas should be. 

## Acceptance Criteria 

**_Note there isn't UI component to build out for this section._** 
- Verify that the canvas has 40px padding top, bottom, left and right in the code.  
- Verify the description copy below is under the title App Canvas
- Verify that App Canvas is under the Layout section

## App canvas

Almost all of the interaction in Caseflow takes place in an App Canvas. The content starts off with a page title and minimal instructions for what the user needs to do to complete their task on the page. It then contains any interaction that well help this to accomplish their task including forms, document previews, tables, error messages, and more.

**Comment by Sjones352** [comment]
### Screenshot
<img width="766" alt="screen shot 2017-05-04 at 10 54 59 am" src="https://cloud.githubusercontent.com/assets/23080951/25709751/299f950c-30b8-11e7-8505-73881e55cef9.png">


<img width="1275" alt="screen shot 2017-05-04 at 10 43 51 am" src="https://cloud.githubusercontent.com/assets/23080951/25709724/159c33d0-30b8-11e7-8705-2b23fa6e39bc.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Go to the living style guide and navigate to the Layout section
2. In inspector verify the sizing and padding of the section 
3. Verify the text under says "App Canvas".

Screenshots:
<img width="1206" alt="screen shot 2017-05-05 at 11 04 36 am" src="https://cloud.githubusercontent.com/assets/23038505/25751407/e3bc5946-3182-11e7-889f-990b2976313b.png">
