### ISSUE TITLE
Styleguide component | Typography - Font Family

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1684]
As a developer or designer, I want a guideline Caseflow typeface so that I know what to use for future applications.

## Acceptance Criteria
- Verify that this is under the Typography section in style guide
- Verify that the texts below are all in font size 24px
- Verify that each text resembles the Source Sans Pro weight it's supposed to be

**_Note: No description_**

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/25283860/318bd1e8-2683-11e7-90c3-67bf8f71d7a6.png)

Actual Text
Source Sans Pro Light (300)
Source Sans Pro Regular (400)
Source Sans Pro Italic (400)
Source Sans Pro Bold (400)

**Comment by slj** [comment]
Screenshot:

<img width="415" alt="screen shot 2017-05-08 at 11 38 25 pm" src="https://cloud.githubusercontent.com/assets/1053255/25834694/aafb8a06-3447-11e7-9769-ad5e244366d6.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT
Browser: FF and Chrome

Steps to Validate: 
1. Access the living style guide 
2. Validate the typography section against the AC

Screenshots: 
<img width="1372" alt="screen shot 2017-05-10 at 9 37 37 am" src="https://cloud.githubusercontent.com/assets/23038505/25901341/83e1c836-3564-11e7-96bd-a5b0ed184c6c.png">
