### ISSUE TITLE
Styleguide component | Typography - Text Styles

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1685]
As a developer or designer, I want a guideline for the typography styling so that I know what to use for future applications.

## Note Note Note! 
We are retiring the previous h1 (44px)!

## Mockup

- Verify that Text Styles is under the Typography section in style guide
- Verify that each text resembles the Source Sans Pro weight and size it's supposed to be
- Verify that font-family, font-weight, font-size, line-height are separated in two columns reflect each text style and is in font `Monaco` and in `gray`
- Verify that each row is 48px apart

## Mockup 

![image](https://cloud.githubusercontent.com/assets/13420618/25284996/bdeadd84-2686-11e7-9552-deaacdee670c.png)

Actual text:

Display 1
font-family: ‘Source Sans Pro’
font-weight: 700
font-size: 52px
line-height: 1.3em/68px

Display 2
font-family: ‘Source Sans Pro’
font-weight: 300
font-size: 44px
line-height: 1.3em/57px

Heading 1
font-family: ‘Source Sans Pro’
font-weight: 700
font-size: 34px
line-height: 1.3em/44px

Heading 2
font-family: ‘Source Sans Pro’
font-weight: 700
font-size: 24px
line-height: 1.3em/31px

Heading 3
font-family: ‘Source Sans Pro’
font-weight: 700
font-size: 19px
line-height: 1.3em/25px

Heading 4
font-family: ‘Source Sans Pro’
font-weight: 700
font-size: 15px
line-height: 1.3em/20px

Heading 5
font-family: ‘Source Sans Pro’
font-weight: 400
font-size: 13px
line-height: 1.3em/17px

Lead paragraph
font-family: ‘Source Sans Pro’
font-weight: 300
font-size: 22px
line-height: 1.5em/33px

Body copy. A series of 
sentences together which 
make a paragraph.
font-family: ‘Source Sans Pro’
font-weight: 400
font-size: 17px
line-height: 1.5em/26px

Italic body copy. A series of 
sentences together which 
make a paragraph.
font-family: ‘Source Sans Pro’
font-style: Italic
font-weight: 400
font-size: 17px
line-height: 1.5em/26px

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Dev
Browsers: FF and Chrome

Steps to Validate: 
1. Access style guide
2. Validate Typography section against mocks and AC

Screenshots:
![sgtypography](https://cloud.githubusercontent.com/assets/23038505/25834565/cfb3b07c-3446-11e7-8014-3ce62e2415e5.gif)
