### ISSUE TITLE
Special Characters/Numbers allowed in manipulative required fields

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1688]
**Description:**
Currently, a user can insert special characters into the text fields in Certification V2 and it works. 

**Environment:** Preprod
**Browsers:** FF and Chrome

**Steps to Replicate:**
1. Open Certification V2 for a veteran who has all of their required documents needed to certify an appeal. 
2. Go through the flow on the Confirm Case Details page. 
3. On the Confirm Hearing and Sign and Certify pages, type special characters or numbers (!@#$%^%#123456789) into any of the applicable required fields. 
4. Continue through the flow of Certification and notice, there are NO issues. 

**Screenshots**
![bug1](https://cloud.githubusercontent.com/assets/23038505/25286710/b0047cec-268c-11e7-92a4-6098a329a949.gif)

**Reported By:** Alexis Stewart

**Comment by amprokop** [comment]
@shellicious — should we prevent this?

**Comment by amprokop** [comment]
needs details from @shellicious re: invalid characters

**Comment by shellicious** [comment]
Discussed this with @cmgiven and other member of the design team. We think limiting special characters is over-optimizing, and we should not enforce a limit until it proves to be a problem.

**Comment by laurjpeterson** [comment]
Closing due to comment above.
