### ISSUE TITLE
Manager View | When more people complete a task than what was set in "Number of people working today", bump the number

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1691]
As a claims assistant I would like to see an accurate estimate of the number of cases I am assigned to work for the day. As a manager, I would like the queue to be distributed evenly across the claims assistants who log in - even if that number is larger than the number of employees I originally entered as working today.

## **AC**
When the number of claims assistants that have completed a task is larger than the number of employees the manager originally entered in the numeric text box as working today:

1. Verify that the number in the numeric text box is updated to reflect the number of employees who have completed at least one task that day.

1. Verify that each case workers' quota is updated accordingly.

## **Mocks**
_Manager view_
<img width="397" alt="screen shot 2017-04-23 at 3 24 35 pm" src="https://cloud.githubusercontent.com/assets/4975959/25316642/080597b6-2839-11e7-9550-719976f40a8e.png">

_Claims Assistant views_
<img width="750" alt="screen shot 2017-04-23 at 4 19 52 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317145/b6604a0c-2840-11e7-9db6-a0f0f447460c.png">
<img width="795" alt="screen shot 2017-04-23 at 4 19 14 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317146/b6611cf2-2840-11e7-84e6-2e37d345f27e.png">

**Comment by shanear** [comment]
## Originally AC
When the number of claims assistants logged in is larger than the number of employees the manager entered in the numeric text box as working today:

1. Verify that the number in the numeric text box is updated to reflect the number of employees who have logged in that day.

1. Verify the total number of claims in the queue is evenly distributed across the number of employees logged in that day.

1. Verify that the last line of the column 'Cases Assigned' reflects the cumulative number of cases assigned to claims assistants on that day.

1. Verify that the number of cases assigned to each employee is updated on the employee's Work History page.

1. Verify that the the number of cases assigned to each employee is updated on Confirmation page.

**Comment by kierachell** [comment]
- manager assigns
<img width="994" alt="screen shot 2017-04-26 at 10 08 41 am" src="https://cloud.githubusercontent.com/assets/18075411/25439564/c3bf6d32-2a6a-11e7-92a6-d38b6469771b.png">

- additional 3rd worker completes task.
<img width="996" alt="screen shot 2017-04-26 at 10 18 32 am" src="https://cloud.githubusercontent.com/assets/18075411/25439565/c3c1cbcc-2a6a-11e7-81bb-cb29e6dce45e.png">
