### ISSUE TITLE
Manager View | Account for remainders when automatically setting task assignments

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1692]
## AC
1. Verify that when the manager initially distributes cases for the day, if there is a remainder, it should be distributed one at a time from the top employee to the bottom.
2. Verify that when a user starts a task, they are added to the manger page and receive a quota
3. Verify that until a user starts a task in a day, they do not see a numeric quota, and instead see: "Get Started!" and "There are claims ready to get picked up for today."

## Examples
If there are 10 cases for the day and three employees (A, B, and C) the initial assignments should be
A: 4
B: 3
C: 3

**Comment by shanear** [comment]
## Original **AC**
1. Verify that when the manager edits and employee's Claims Assigned number the remaining cases in the queue (e.g. queue total - edited Claims Assigned = remaining cases) are re-distributed evenly amongst the unlocked rows in the Claims Assigned column.
1. Verify that if there is an odd number of cases to redistribute, the 'extra cases' will be distributed one at a time to the unlocked Claims Assigned rows starting with the row closest to the top of the table. (see mock)

**Comment by shanear** [comment]
Changing AC to reflect that this story should be done before https://github.com/department-of-veterans-affairs/caseflow/issues/1690.

**Comment by shanear** [comment]
@lakohl we should update the mock accordingly.

**Comment by shanear** [comment]
Added AC for technical reasons

**Comment by kierachell** [comment]
**PASSED**
<img width="985" alt="screen shot 2017-05-08 at 11 59 19 am" src="https://cloud.githubusercontent.com/assets/18075411/25813068/466d7830-33e6-11e7-9fe8-55d846216a07.png">
<img width="1191" alt="screen shot 2017-05-08 at 12 02 23 pm" src="https://cloud.githubusercontent.com/assets/18075411/25813066/462cb304-33e6-11e7-9651-546ac87512c8.png">
<img width="1034" alt="screen shot 2017-05-08 at 12 02 38 pm" src="https://cloud.githubusercontent.com/assets/18075411/25813065/45fae324-33e6-11e7-95ca-292d05fae649.png">
