### ISSUE TITLE
Manager View | Don't allow managers to assign fewer than total tasks

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1693]
As a manager, if I edit the Claims Assigned to each employee and as a result, I leave some claims in the queue unassigned, I would like to receive a warning.

## **AC**
1. Verify that if the total Claims Assigned are less than the total number of claims in the queue
the following warning is displayed:
> [x] Unassigned Cases
> You must assign [x] more cases in order to complete the cases in your queue.

**Comment by shanear** [comment]
@lakohl this situation would only occur if all the fields were "unlocked" not when they were "locked"

**Comment by shanear** [comment]
More discussion on actual solution here with @lakohl

**Comment by lakohl** [comment]
We do not want to allow the manager to leave any claims unassigned. When there are 5 employees working, the manager may edit the assignments of 4 of those employees. They will be blocked from editing the assignment of the fifth.

**Comment by lakohl** [comment]
Removed older mock from AC as it is no longer relevant

**Comment by kierachell** [comment]
**PASSED**
Can't even get that message to show, so that's pretty bullet-proof
![tasks](https://user-images.githubusercontent.com/18075411/27966901-f94024ce-630e-11e7-9081-1aadea48dba7.gif)

**Comment by lakohl** [comment]
Am I crazy, or are the table headers moving?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by kierachell** [comment]
Oh it's been doing that since the table was implemented. This is way less than it used to.
