### ISSUE TITLE
Not enough people start by a certain time in the day

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1694]
As a manager, I would like to ensure that all the cases available to ARC are completed on a given day.  At a set time each day, I would like Caseflow to check to see if the number of employees I set as working today matches the number of people who have logged in. If the number of people who have logged in is less than the number of employees entered as working today, I would like Caseflow to show me a warning.

## AC

1. Verify that at 10 a.m. EST each day, Caseflow checks to see if the number of employees who have logged in/completed a task that day matches the number of employees entered by the manager as working today. 1. If at 10 a.m. the number of employees who have logged in/have completed a task is less than the number of employees the manager entered as working today, display the following warning:

Header:
> [Number] employees have not logged in today

Body:
> To ensure that all of ARC's claims are worked you may need to redistribute the queue.
To adjust the number of people working today enter a new value and click Update.

1. When the number of people working today is updated, verify that:
a) if the number of people logged in/who have completed 1 claim is < the 'number of people working today', update the warning message to show the new number of employees that have not logged in.
b) if the number of people logged in/who have completed 1 claim = the 'number of people working  today', verify that the warning message no longer displays.

## **Mock**
<img width="791" alt="screen shot 2017-05-09 at 3 49 15 pm" src="https://cloud.githubusercontent.com/assets/4975959/25869673/2fe62de8-34cf-11e7-98f6-80a4f453a2b2.png">

**Comment by lakohl** [comment]
@shanear in the AC above I wrote that at 11 am Caseflow should redistribute the remaining cases amongst the employees who are logged in bc I worry that if they've already logged out they might think that they are finished for the day and have no way of knowing that they have been assigned more work.

I will check with George first thing Monday am to see if 11am is the right time to check for this.

**Comment by shanear** [comment]
## Original AC
As a manager, I would like to ensure that all the cases available to ARC are completed on a given day.  At a set time each day, I would like Caseflow to check to see if the number of employees I set as working today matches the number of people who have logged in. If the number of people who have logged in is less than the number of employees entered as working today, I would like Caseflow to automatically redistribute the remaining cases amongst the employees who are currently logged in.

1. Verify that at 11 a.m. (exact time tbd) each day, Caseflow checks to see if the number of employees who have logged in matches the number of employees entered by the manager as working today.

If at 11 a.m. the number of employees who have logged in is less than the number of employees the manager entered as working today:

1. Verify Caseflow redistributes the total number of cases remaining in the queue evenly (or as evenly as possible) across the employees who are currently logged in.
1. Verify that the numeric text box showing the number of people entered today is updated to the number of people who have logged in that day.
1. Verify that the number of cases assigned to each employee will be updated on the manager's ARC Work Assignments table.
1. Verify that the number of cases assigned to each employee is updated on the employee's Work History page.
1. Verify that the the number of cases assigned to each employee is updated on Confirmation page of the next claim worked.

If at 11 a.m. the number of employees who have logged in is more than the number of employees the manager entered as working today, see #1691

**Comment by lakohl** [comment]
@shanear I talked to Abby and am thinking that we should maybe hold off on implementing this ticket. Maybe start by showing a warning instead.

**Comment by shanear** [comment]
@lakohl k I will postpone working on it and you can take a crack at the new AC.

**Comment by lakohl** [comment]
@shanear I just spoke to George and he feels the manager should do the task of assigning these claims manually. I think we may want to handle this with a warning to the manager rather than auto-reassign

**Comment by lakohl** [comment]
Instead of automatically updating, I would like to try showing the manager a warning if there are employees that have not logged in by a certain time in the day (11am or 12pm). 

@avrildavid could you take a look at the warning copy?
<img width="659" alt="screen shot 2017-05-08 at 12 42 05 pm" src="https://cloud.githubusercontent.com/assets/4975959/25814510/c52fefcc-33eb-11e7-9b90-32b5e2efa6ab.png">

**Comment by avrildavid** [comment]
@lakohl – my only suggestion is to highlight that they haven't logged in to work claims - just in case there are employees who have logged in, but haven't finished a claim yet (they were interrupted or it's a tricky case that took longer to review, etc.) it could read:

“Two employees have not logged in today”. 

I think the rest of the instructional text looks good. Might also consider making “employees” and “people” consistent throughout (just choose one).

**Comment by lakohl** [comment]
I spoke to George, the ARC manager. He says that everyone working that day should have logged in by 9:30 a.m. Given that we show the employee's name once they have worked their first claim, it seems safe to show the warning at 10am.

**Comment by lakohl** [comment]
Old AC: 
As a manager, I would like to ensure that all the cases available to ARC are completed on a given day.  At a set time each day, I would like Caseflow to check to see if the number of employees I set as working today matches the number of people who have logged in. If the number of people who have logged in is less than the number of employees entered as working today, I would like Caseflow to automatically redistribute the remaining cases amongst the employees who are currently logged in.

## AC

Verify that at 11 a.m. each day, Caseflow checks to see if the number of employees who have completed a task that day matches the number of employees entered by the manager as working today. If at 11 a.m. the number of employees who have logged in is less than the number of employees the manager entered as working today:

1. Verify that the number in the numeric text box is updated to reflect the number of employees who have completed at least one task that day.

1. Verify that each case workers' quota is updated accordingly.

If at 11 a.m. the number of employees who have logged in is more than the number of employees the manager entered as working today, see #1691 

## Additional Notes
- Exact time subject to change by @lakohl & other designers & George

## **Mocks**
_Manager view_
<img width="397" alt="screen shot 2017-04-23 at 3 24 35 pm" src="https://cloud.githubusercontent.com/assets/4975959/25316642/080597b6-2839-11e7-9550-719976f40a8e.png">

_Claims Assistant views_
<img width="750" alt="screen shot 2017-04-23 at 4 19 52 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317145/b6604a0c-2840-11e7-9db6-a0f0f447460c.png">
<img width="795" alt="screen shot 2017-04-23 at 4 19 14 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317146/b6611cf2-2840-11e7-84e6-2e37d345f27e.png">

**Comment by lakohl** [comment]
@shanear can you verify - do the employee's names show in the ARC Work Assignments table when they log in? or once they have completed a claim?
