### ISSUE TITLE
ARC Work Assignments: Show people who have not yet logged in (with numbers)

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1695]
As a manager, I would like to see the total number of rows for employees working that day, even if Caseflow does not yet know who they are yet.

## **AC**

1. Verify that at the start of the day, the number of 'employee' rows in the ARC Work Assignments table matches to the number of employees the manager has set as working today. (e.g. if the manager has set the number of employees as working to 4, there should be 4 rows for employees and one for the totals).
1. Verify that the 'employee rows' are numbered chronologically by the first case they've completed that day from top to bottom.
1. Verify the when an employee has not yet logged in, they still are allotted a row that shows them as 'No cases completed" in the Employee Name column.
1. Verify that text and numbers in the row of an employee who is 'Not logged in' display in gray (from USWDS).

## **Mocks**
<img width="779" alt="screen shot 2017-04-23 at 4 39 43 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317270/7be3281a-2843-11e7-811c-86dccaa6cee9.png">

**Comment by shanear** [comment]
@lakohl 

#9b9b9b fails accessibility color contrast rules, and is also not a color in the USWDS.

Can we use #5b616b (gray) instead?

**Comment by shanear** [comment]
"Not logged in" is not a perfectly accurate way to describe it. Users won't appear there even if they are logged in, because they might not yet have completed a Claim Establishment today.

Something like "No completed cases", "None completed" would be more accurate.

@lakohl let me know if you'd like to change.

**Comment by shanear** [comment]
1. Verify that the 'employee rows' are numbered chronologically *by the first case completed that day* from top to bottom.

@lakohl is this correct?

**Comment by kierachell** [comment]
**PASSED**
<img width="1037" alt="screen shot 2017-05-08 at 12 39 06 pm" src="https://cloud.githubusercontent.com/assets/18075411/25814515/c6a6d76c-33eb-11e7-95c0-6f07c0dde3c6.png">
<img width="1094" alt="screen shot 2017-05-08 at 12 41 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/25814514/c6a43822-33eb-11e7-9679-96eefeef7c50.png">
