### ISSUE TITLE
Manager View: change column structure

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1696]
As a manager, I would like to see how many of each type of case (e.g. full grants, remands, partial grants) my employees work in a day. 

## AC

1. Verify that on the manager page, the ARC Work Assignments table now has six columns.
1. Verify that the column headers have the following new names:
  - Employee Name
  - Full Grant
  - Partial Grant
  - Remand
  - Completed
  - Claims Assigned
3. Verify the values in the table each employee are correct for the column header.
4. Verify the column headers display from left to right in the order indicated above.

## **Mock**
<img width="803" alt="screen shot 2017-04-23 at 4 51 30 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317342/20bfbe60-2845-11e7-9768-a31df3b6e7a9.png">

**Comment by slj** [comment]
Solution in action:
![arc_manager](https://user-images.githubusercontent.com/1053255/27365953-1945b5b4-5611-11e7-9db3-49023da31043.gif)

**Comment by slj** [comment]
Solution screenshot:
<img width="663" alt="screen shot 2017-06-22 at 1 58 30 pm" src="https://user-images.githubusercontent.com/1053255/27448497-fe6f88ee-5752-11e7-8fd0-59a199c5b87c.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Dispatch as a manager
2. Access the Manager Dashboard
3. Validate the table titles for the Manage Work Assignments

Screenshots: 
<img width="1080" alt="screen shot 2017-06-27 at 10 33 41 am" src="https://user-images.githubusercontent.com/23038505/27593066-330d9d3c-5b24-11e7-9a3f-e046a5fc47d8.png">
