### ISSUE TITLE
Collect in-app feedback

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#17]
We need a mechanism to collect in-app feedback during the pilot phase. Here are some options: 

- Provide a mailto link and set up an email list to collect feedback
- Create a feedback button that links to a survey (Google Sheets/ Survey Monkey)
- Use a service like UserVoice
- Others?

**Comment by MarinaMartin** [comment]
You could leverage UserVoice for vets.gov and we make you a category?

**Comment by plusjeff** [comment]
@gmorgana-va is working on this in https://github.com/department-of-veterans-affairs/appeals-pm/issues/16
