### ISSUE TITLE
Manger View | Reset queue

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1701]
As a manager, if I have manually adjusted the number of cases assigned to my employees, I would like the option to reset the queue and once again distribute today's cases evenly amongst my employees.

## **AC**
1. Verify that after editing the number of Claims Assigned to an employee, a manager can reset/redistribute the queue evenly again by undertaking the following steps:

- Clicking on the icons in the Claims Assigned column until they all display as 'unlocked' 
AND then
- Clicking the Update button next to 'Enter the number of people working...'.

## **Mock**
_Shows unlocked Claims Assigned rows_
<img width="664" alt="screen shot 2017-04-23 at 6 46 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/25318097/32cfd9d6-2855-11e7-9829-46e0b32ecc7f.png">

_Shows queue re-distributed after Update is clicked_
<img width="854" alt="screen shot 2017-04-23 at 6 53 14 pm" src="https://cloud.githubusercontent.com/assets/4975959/25318135/23543834-2856-11e7-8c96-e5ac650740d0.png">

**Comment by shanear** [comment]
No longer needed.
