### ISSUE TITLE
Create End Product | Make "Modifier" field read-only

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1704]
## Story
Currently, the **Modifier** field is an editable dropdown. Instead, it should be read-only, so users don't change it accidentally/unnecessarily. The styling should match other read-only fields on the page (such as **Station**)

## Acceptance Criteria
- **Modifier** field on the Create End Product page displays in read-only format, and cannot be changed by the user
- Update `duplicate_ep` error to be:

> Header: Unable to assign or create a new EP for this claim
Body: Please try to create this EP again. If you are still unable to proceed, select Cancel at the bottom of the page to release this claim, and process it outside of Caseflow.

- On `duplicate_ep` error, automatically increment the modifier value when appropriate (only possible for partial_grants and remands)

 Story**
https://github.com/department-of-veterans-affairs/caseflow/issues/622

**Comment by abbyraskin** [comment]
FYI, just snuck this one in to Triage @lakohl @shanear (should be a quick fix)

**Comment by joofsh** [comment]
todo: talk to abby and figure out what to do with edge cases

**Comment by abbyraskin** [comment]
@joofsh is the current error message the same regardless of whether it's a full grant or a remand? I have:

Header: At this time, we are unable to assign or create a new EP for this claim.
Body: An EP with that modifier was previously created for this claim. Try a different modifier or select Cancel at the bottom of the page to release this claim and proceed to process it outside of Caseflow.

We discussed incrementing the modifier if it's a 170 and encouraging the user to resubmit. If it's a 172, they will have to cancel and process the claim outside Caseflow. So, how about we tweak the wording a little while still covering both scenarios (given how rarely we think this will occur):

Header: Unable to assign or create a new EP for this claim
Body: Please try to create this EP again. If you are still unable to proceed, select Cancel at the bottom of the page to release this claim, and process it outside of Caseflow.

**Comment by joofsh** [comment]
@abbyraskin yes it's the same error text if it's a remand or full grant. It's not worth the complexity to change that (all errors go through the same generic code path). It sounds like the 2nd scenario would work well with a full grant or remand (with us auto-incrementing). 

Does that sound right to you?

**Comment by abbyraskin** [comment]
Yep, that was my thinking as well 👍

**Comment by slj** [comment]
Since the other error headers are sentences, I changed the one for this issue to:

`We were unable to assign or create a new EP for this claim.`

**Comment by slj** [comment]
Solution in action (RSpec test):

![imod 2](https://cloud.githubusercontent.com/assets/1053255/25961310/d76fbc40-3647-11e7-8536-cc8ef3e01d3c.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Dispatch as a caseworker
2. Go through the steps of establishing a claim with a remand
3. When the caseworker lands on the 'Route Claim' page, verify that the modifier is "read-only" by trying to manipulate it and then select "continue"

Screenshots:
<img width="1144" alt="screen shot 2017-05-15 at 7 55 39 am" src="https://cloud.githubusercontent.com/assets/23038505/26056720/87148a78-3944-11e7-8622-b5431061b67b.png">
