### ISSUE TITLE
Rethink the logic when a new tag is created in Reader

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1706]
Right now, when a tag is created, the POST returns a JSON with the newly created tags as response. Then the response is merged into to the redux state of documents.

Alternatively, we can make a get call /{document_id}/tags call after a successful POST, fetch all tags related to a document and update the redux state.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
