### ISSUE TITLE
Add "Refresh Page" button to Mismatched docs page for V2 [1]

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1711]
If documents for an appeal are mismatched or missing, the call to action button in the bottom right should be active (blue) and say "Refresh Page". Clicking on the button refreshes the page. 

If the documents are found, the user will then see a confirmation page stating that the documents have been found. If the documents are not found, on page refresh they will continue to see the mismatched docs page.

Disregard the styling of the table. This screenshot shows the "Refresh Page" button and how it should be implemented:

![screen shot 2017-04-24 at 11 56 33 am](https://cloud.githubusercontent.com/assets/1178390/25346341/5bcd47a2-28e5-11e7-8498-f88b2628a0a0.png)

Acceptance Criteria
- If the appeal has mismatched documents, the Documents Check page should have a button that says "Refresh Page" instead of "Continue"
- Clicking this button should trigger a page refresh
- If the user corrects the mismatched documents, after clicking "refresh page", the button should now say "Continue" and allow the user to continue through the certification.

**Comment by kierachell** [comment]
**PASSED**
EVEN SENTENCE CASE! YEAH!
<img width="803" alt="screen shot 2017-05-02 at 8 55 56 pm" src="https://cloud.githubusercontent.com/assets/18075411/25645188/c49c185e-2f79-11e7-8380-522f2fb167da.png">
