### ISSUE TITLE
Scroll | To last read document on `< Back to All Documents`

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1712]
Currently when you hit the `Back to all documents` button we don't scroll to the most recently read. It's annoying to scroll back down.

AC:
- When a user clicks on `< Back to all documents` the page should be scrolled so that the last read document is visible.

**Comment by kierachell** [comment]
**PASSED**
![lastread](https://cloud.githubusercontent.com/assets/18075411/25503210/7733c870-2b67-11e7-9aed-45224fb203e8.gif)
