### ISSUE TITLE
Document Viewer | Adding comment document highlight

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1713]
**Story**

As a user, I want to see a visual indicator that shows that I am at the active state for adding a comment on a document viewer. 

## Old AC

- Verify that there is a 10px border outline around the document viewer in `focus` or hex #3E94CF after a user clicks on add a comment button
- Verify that once the comment is saved, the border disappears

## ------------ Updated AC -----------

- Verify that there is a 10px border outline around the *pages* in color `focus` or hex #3E94CF after a user clicks on add a comment button
- Verify that once the comment is saved, the border disappears

![image](https://cloud.githubusercontent.com/assets/13420618/25350253/88c2414c-28f2-11e7-8ac5-62fc65336c7e.png)

Note: The border is wrong on the mockup. It should be around the document.

**Comment by kierachell** [comment]
**PASSED**
there's one hard to reproduce oddity, but otherwise it's good
![addcomment](https://cloud.githubusercontent.com/assets/18075411/25507548/aa975e08-2b7a-11e7-864f-ff4bef95edff.gif)

**Comment by mdbenjam** [comment]
I think this is a bug outside of the scope of this ticket. I made #1877 to track it. Moving it back to in validation.

**Comment by kierachell** [comment]
**PASSED**
<img width="938" alt="screen shot 2017-05-05 at 10 50 28 am" src="https://cloud.githubusercontent.com/assets/18075411/25750765/b7bf1cc2-3180-11e7-9197-6bdef42f84ea.png">
![Uploading Screen Shot 2017-05-05 at 10.50.49 AM.png…]()
