### ISSUE TITLE
New Tab | Ensure robustness

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1714]
When a user ctrl + clicks (PC) or command+click (Mac)  it should open a document in a new tab. When a new tab is opened, it should only contain that one file, and not load the entire case.

# AC
1. Verify that `ctrl/command/middle + click` on a document opens it in a new tab.
1. Verify there is no loading spinner in the new tab, that it loads just the one document.
1. Verify there is no back to all documents button in the tab.
1. Verify there are tests to check for regressions.

**Comment by kierachell** [comment]
### Verify there is no loading spinner in the new tab, that it loads just the one document.

Nope :(
![newtab](https://user-images.githubusercontent.com/18075411/27771481-27475ec8-5f1d-11e7-97c4-ac4f3c5446cb.gif)


### Verify there is no back to all documents button in the tab.

Nope :(


![tabnew](https://user-images.githubusercontent.com/18075411/27771482-2747668e-5f1d-11e7-89c1-94e0638bfaab.gif)

**Comment by mdbenjam** [comment]
Let's sync Wednesday about this. I'm not seeing the same behavior as you. It looks like both of these things work.

**Comment by kierachell** [comment]
**PASSED**
WOOOO
