### ISSUE TITLE
Use new version of the Form 8 [5]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1715]
We should put this issue behind a feature flag that's different from the `certification_v2` feature toggle, because we're not going to switch to the new form8 until after the pilot is finished.

[VA8_4.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/952802/VA8_4.pdf)

## Acceptance Criteria

1. You will need to `FeatureToggle.enable!(:form8_v2)` in UAT/preprod
1. Certify an appeal in Cert V2
1. Go to VBMS and find a new Form8 uploaded (sample above)

**Comment by nicholasholtz** [comment]
There is an updated version of this - same questions, but different layout. See slack. WIll upload here

**Comment by nicholasholtz** [comment]
[VA8 (3-21-17 Rev.).pdf](https://github.com/department-of-veterans-affairs/caseflow/files/952882/VA8.3-21-17.Rev.pdf)

**Comment by kierachell** [comment]
**PASSED**
new FORM8 was uploaded to VBMS
<img width="1384" alt="screen shot 2017-05-10 at 1 15 16 pm" src="https://cloud.githubusercontent.com/assets/18075411/25911686/ca263228-3582-11e7-9c56-87e6672afb0e.png">
