### ISSUE TITLE
Issue tags stutter a bit when you add them

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1717]
![tag stutter](https://cloud.githubusercontent.com/assets/829827/25358052/0c2cb2a4-290e-11e7-94db-b572d73e67a5.gif)

When you add a new tag, instead of the view updating immediately, the tag disappears and then is re-added. This is because we don't update the client, but instead send a request to the server and wait for it to tell us what the new tags are. We can make this a smoother experience at the cost of added clientside complexity.

## Acceptance Criteria
- [x] Verify that tags can be added and deleted as usual
- [x] Verify that tags can be added or removed instantaneously and there is no stutter 
- [x] Verify that if an error occurs on the server, the add or remove action is reverted and the error is shown

**Comment by kierachell** [comment]
**PASSED**
Checked on Chrome and FF
![stutter](https://cloud.githubusercontent.com/assets/18075411/25508058/ae04c956-2b7d-11e7-94d8-dc26c152c133.gif)
