### ISSUE TITLE
[1] Create a React component for Cancellation modal success page

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#1722]
Convert this view into a React component (jsx page):
![caseflow certification 11](https://cloud.githubusercontent.com/assets/4960030/25391006/267adfec-29a3-11e7-870e-91f48e7084b1.png)

Acceptance criteria:
After merge, check that the cancellation success page still renders properly.

**Comment by kierachell** [comment]
**PASSED**
<img width="780" alt="screen shot 2017-11-23 at 10 39 32 am" src="https://user-images.githubusercontent.com/18075411/33180482-da84b524-d03a-11e7-99e7-702d89df7247.png">
