### ISSUE TITLE
Document Viewer | Adjacent annotations featuring identical text show up as one in Menu

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1724]
# Description
When creating Annotations for a single document. If I add a comment in adjacent order to a comment with identical text, they will not show up as separate comments in the menu.

## Reproduction Steps

**Scenario 1 -**

1. Create "comment" in Document Viewer
1. Create "comment2"
1. Create "comment" again away from first "comment"
1. Create "comment" near one of the other "comment"-s

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [See for yourself]_**

![commenttext](https://cloud.githubusercontent.com/assets/18075411/25392609/160c3af8-29a7-11e7-9fd8-bf5c98b3d444.gif)

**Comment by kierachell** [comment]
Bonus:
**COMMENT SPAWN**

![spawncomment](https://cloud.githubusercontent.com/assets/18075411/25392984/3aad1674-29a8-11e7-82ae-4d9e7874bf00.gif)

**Comment by mdbenjam** [comment]
I think this was fixed a while ago. Moving to in validation to double check.

**Comment by kierachell** [comment]
**PASSED**
Seems fixed now :D

<img width="1057" alt="screen shot 2017-07-02 at 11 49 47 am" src="https://user-images.githubusercontent.com/18075411/27771457-ac58c1e8-5f1c-11e7-8482-973143337618.png">
