### ISSUE TITLE
Issues | Moving between documents, issue state is maintained

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1729]
Currently the dropdown stores the state of the issue box on the previous document.

![issues2](https://cloud.githubusercontent.com/assets/3885236/25400161/b26ab916-29bf-11e7-9ec9-e2489a470f5a.gif)

Acceptance Criteria
- [ ] When a user starts typing an issue and moves between documents, the issue should no longer appear.
- [ ] When a user unfocuses the dropdown any content they typed should remain in the box.

**Comment by abbyraskin** [comment]
@mdbenjam would it make sense to combine this with https://github.com/department-of-veterans-affairs/caseflow/issues/1758?

**Comment by kierachell** [comment]
**PASSED**
![tagstate](https://cloud.githubusercontent.com/assets/18075411/26126307/1cf35c54-3a53-11e7-8ea8-d487ceb94170.gif)
