### ISSUE TITLE
Refactor `certification.complete!`, `appeal.certify!`, and `Appeal.certify`

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1730]
We should take a look at these three methods and simplify them. These methods have been through a few iterations and we could probably refactor.

Consider getting rid of the class methods.

Context:
![image](https://cloud.githubusercontent.com/assets/3781835/25402348/6ac31782-29c6-11e7-8eb5-1a705362e9d0.png)

**Comment by laurjpeterson** [comment]
@amprokop - do you think we should keep this tech improvement ticket open? I'm doubtful we'll get to Caseflow Certification refactoring any time soon.

**Comment by jimruggiero** [comment]
Closing ticket - stale; could refactor if new certification issues around this code surface.
