### ISSUE TITLE
[2] Fix JS console warnings

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1731]
**Impact:** Minor annoyance for devs now; blocks us from upgrading our version of React in the future.

When we upgraded to `react@15.5.4`, we started seeing the following errors:

![image](https://cloud.githubusercontent.com/assets/829827/25402535/f9001fe0-29c6-11e7-8822-6a4c8cfb0793.png)

## To fix the `PropTypes` warning

1. Read [Don't Call PropTypes Warning](https://facebook.github.io/react/warnings/dont-call-proptypes.html)
1. Read the [Migration Instructions](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes)
1. Get someone ready to review your PR (you'll see why in a minute)
1. Ask everyone to hold off on merging to `master`
1. Run the `react-codemod` that [automatically does this migration](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types) across our entire codebase
1. Check in the results of the codemod
1. Open a PR
1. Get the PR approved
1. Wait for the PR to pass on Travis
1. Pray to the good lord Cthulu that no one merges to `master` in the meantime. If someone does, go back to step 5.
1. When everything is green, hit the merge button as hard as you can.

Obviously, the goal is to do steps 3-11 in as little time as possible. 

## To fix the `AutosizeInput` warning:

1. Ping on https://github.com/JedWatson/react-input-autosize/pull/79 and ask them to publish the changes from that PR to `npm`
1. Once that changes are published, `npm install react-select@latest --save`. That should pull in the latest `react-input-autosize`, because that's how we depend on it:
```
 λ npm ls react-input-autosize
caseflow-frontend@0.0.1 /Users/nth/dev/caseflow/client
└─┬ react-select@1.0.0-rc.3
  └── react-input-autosize@1.1.0 
```

**Comment by kierachell** [comment]
**PASSED**
Just seeing this now;
<img width="1006" alt="screen shot 2017-05-24 at 3 31 40 pm" src="https://cloud.githubusercontent.com/assets/18075411/26421995/1ff5a2ba-4096-11e7-880e-836d8e4f4dd0.png">
