### ISSUE TITLE
Document List | Opening a document using keyboard or in new Tab/Window leads to Not Found error

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1734]
# Description
When opening a document from Document List using keyboard...things...go awry

## Reproduction Steps

**Scenario 1 -**

1. Go to Document list
1. Tab around and select a document using your keyboard
1. Press Enter
1. Not see a document

![arrows](https://user-images.githubusercontent.com/18075411/27181462-ae7ab1d6-51a5-11e7-99f9-1e33a44aacc5.gif)

**Bonus: Going Back in History**
<img width="1375" alt="screen shot 2017-06-15 at 8 37 00 am" src="https://user-images.githubusercontent.com/18075411/27181511-dde732dc-51a5-11e7-9804-dbd905f010dc.png">

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Logs:
```
application-2ba082a….js:11 
Uncaught TypeError: ReactOnRails encountered an error while rendering component: BaseContainer.
Original message: Cannot read property 'id' of undefined
    at t.value (application-2ba082a….js:11)
    at d._renderValidatedComponentWithoutOwnerOrContext (application-2ba082a….js:38)
    at d._renderValidatedComponent (application-2ba082a….js:38)
    at d.performInitialMount (application-2ba082a….js:38)
    at d.mountComponent (application-2ba082a….js:38)
    at Object.mountComponent (application-2ba082a….js:6)
    at h.mountChildren (application-2ba082a….js:38)
    at h._createInitialChildren (application-2ba082a….js:38)
    at h.mountComponent (application-2ba082a….js:38)
    at Object.mountComponent (application-2ba082a….js:6)
```

## Screenshots
**_Scenario 1 - [Keyboard Only]_**

![keyboardonly](https://cloud.githubusercontent.com/assets/18075411/25407700/5407e190-29d9-11e7-8969-219cf1f02fa6.gif)

## Screenshots
**_Scenario 1 - [New tab]_**
![newdoc](https://cloud.githubusercontent.com/assets/18075411/25437750/6aeecbda-2a65-11e7-863b-5aaf4925e318.gif)

**Comment by kierachell** [comment]
Actually, now it always opens a single document from keyboard... so that's awkward cause I can't go back to Document List:
![whynewtab](https://user-images.githubusercontent.com/18075411/27865087-30277804-615f-11e7-94fe-904fa11d7352.gif)

**Comment by abbyraskin** [comment]
@kierachell that's tracked here in #2406 - can we close this ticket?

**Comment by kierachell** [comment]
Is there an issue to track that opening a document with keyboard opens it as a single document?

If yes, link it here and close.

**Comment by mdbenjam** [comment]
I'm using this one for the enter bug :). And I just finished it.

**Comment by kierachell** [comment]
**PASSED**
- IE11
![enterdocument](https://user-images.githubusercontent.com/18075411/28034081-264a0fae-657e-11e7-84aa-ccff5f9784e5.gif)
- Chrome
![onchrome](https://user-images.githubusercontent.com/18075411/28034194-869710f0-657e-11e7-9856-a2e9f2e8e8e6.gif)
