### ISSUE TITLE
Document list | Categories dropdown flicker

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1738]
**Story**

When selecting and deselecting categories in the dropdown, there is a flicker. 

## AC 
- [ ] Verify that when you click on each category, there isn't a flickering effect. 

![image](https://cloud.githubusercontent.com/assets/13420618/25442267/927668fe-2a72-11e7-92fa-ece520260877.png)

**Comment by abbyraskin** [comment]
Closing this out - won't fix.

**Comment by abbyraskinUSDS** [comment]
Closing this out - won't fix.
