### ISSUE TITLE
Document list | dropdown paddings

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1739]
**Story** 
As a user, I want to be able to use a clean and clear dropdown

**Description**

This is a cosmetic fix for the dropdown styling that wasn't added in the previous ACs

## AC
- [ ] Verify that both Categories and Issues dropdown have 14px padding for each option while Clear category filter and Clear tag filter have 14px margin (right, left and bottom).

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/25597274/d4f9fc36-2e9b-11e7-8b3a-51aa42a99c5a.png)

**Comment by Sjones352** [comment]
@gnakm after speaking to @mmlumba I would like to update the AC to the options being 14px padding and Clear category filiter plus clear filter to 14px margin.

Currently Looking like this
![reader-padding](https://user-images.githubusercontent.com/23080951/27875200-5f0b6dee-6180-11e7-9be1-6e51234a8ca5.gif)

**Comment by gnakm** [comment]
@Sjones352 sounds good to me!

**Comment by mdbenjam** [comment]
@gnakm is the bottom padding also supposed to be 14px?

**Comment by gnakm** [comment]
@mdbenjam  yes. 
@Sjones352 ^^ I changed AC for awareness.

**Comment by Sjones352** [comment]
@gnakm and @mdbenjam currently looks like this. A couple more adjustments then I will push the PR
![padding](https://user-images.githubusercontent.com/23080951/27964555-aea07c14-6306-11e7-90c1-6d043babbefd.gif)

**Comment by gnakm** [comment]
@Sjones352 I don't think there should be a scroll for the issue tags dropdown. It should be the same height as the categories dropdown.

**Comment by Sjones352** [comment]
@gnakm scroll was originally there but I can take it out if you like? Any suggestions @mdbenjam ?

**Comment by Sjones352** [comment]
@gnakm currently looks like this

![padding](https://user-images.githubusercontent.com/23080951/28027793-6d2b9728-6568-11e7-97a4-179a4a727d62.gif)

**Comment by kierachell** [comment]
**PASSED**
![screenshot_2017-07-12_13-17-43](https://user-images.githubusercontent.com/18075411/28130506-deacad9a-6704-11e7-8eaa-12ff6117b5ba.png)
![screenshot_2017-07-12_13-18-23](https://user-images.githubusercontent.com/18075411/28130505-dea49fec-6704-11e7-945c-ee4e5ba64945.png)

**Comment by kierachell** [comment]
**PASSED**

Go Sandra! Go Sandra! 
![screenshot_2017-07-12_19-54-37](https://user-images.githubusercontent.com/18075411/28144910-60d44148-673c-11e7-82aa-8930283744e3.png)
![screenshot_2017-07-12_19-57-14](https://user-images.githubusercontent.com/18075411/28144911-60d9ec24-673c-11e7-84ab-4429998257a2.png)
