### ISSUE TITLE
Document Viewer | Right/Left Arrows: shouldn't move between documents when focused on UI

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1740]
![leftright](https://cloud.githubusercontent.com/assets/3885236/25443749/c286c8e6-2a76-11e7-8f8c-ea4c9a288bab.gif)
^Example of hitting the right arrow.

## Description
Currently right/left are bound to the window, so you can move left and right between the documents. However, when you're focused on the issue tags or an open comment box, the left and right should move issue tags or comment text in the field, not between documents.

## AC
- Left and right in the tag box should not move between pages
- Left and right in an open comment box should move between characters in the comment 
- Left and right in an open comment box should not move between pages

**Comment by abbyraskin** [comment]
Moving this up in priority, as it applies both to issue tags and comments (a couple users have mentioned this as confusing)

**Comment by kierachell** [comment]
While I wholeheartedly approve of the commit messages...currently, only navigation within the comment works:
![keysonly](https://cloud.githubusercontent.com/assets/18075411/26028541/c2e5e2ae-37f0-11e7-829b-afce5982095e.gif)
## Does not work:
> Left and right in the tag box should move between tags.
> Left and right in the tag box should not move between pages

**Comment by NickHeiner** [comment]
> Left and right in the tag box should move between tags.

I am not convinced that this is even supported in `react-select`. If you go to the demo page, the arrow keys do not move between tags: http://jedwatson.github.io/react-select/. I think we should remove this AC and then the ticket will pass.

@mdbenjam @abbyraskin @gnakm thoughts?

**Comment by abbyraskin** [comment]
@NickHeiner I removed the AC. (This is not ideal from an accessibility standpoint, but it sounds like this would require a lot of effort, particularly for a feature that may change. So +1 to holding off on this right now.)

**Comment by kierachell** [comment]
**PASSED**
based on updated AC
