### ISSUE TITLE
Document viewer | Unsaved comment autosave

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1741]
**Description**
As a user, I may be going back and forth between pages and closing out tabs before saving all comments. Instead of showing an impersonal, hard to quickly read, default browser alerts, unsaved comments should be autosaved.

## AC
- [ ] Verify that an unsaved comment is autosaved when user 1. hits the back to documents list link or 2. escapes tab.

**Comment by gnakm** [comment]
@avrildavid Revisiting our little content situation. Could use your content help here.

Title: Leaving? vs. Unsaved Comments
Body: You have unsaved comments. Are you sure you want to leave this page without saving?
Cancel text: Oops! Go back
Confirm text: Ok, leave page

![image](https://cloud.githubusercontent.com/assets/13420618/25880371/ed43933c-3504-11e7-9c9d-2a1d982ac884.png)

![image](https://cloud.githubusercontent.com/assets/13420618/25880379/f844ab18-3504-11e7-8e4a-bec76b4ecbca.png)

/cc: @abbyraskin for awareness.

**Comment by avrildavid** [comment]
Hey @gnakm - even though I agreed earlier that "leaving?" sounds better, I'm concerned that someone might just see that title, not read the descriptive text below it and click the "ok, leave page", button just so they can move on. If "unsaved comments" is the first thing they see, they immediately know that there's still an action they should take before leaving (it's not just a confirmation pop-up because they tried to leave the page). I'd vote for "unsaved comments", even if it's not the coolest phrase.

**Comment by gnakm** [comment]
@avrildavid Yeah I agree that the title should give more context. 
@abbyraskin I'm going for option 1.

**Comment by abbyraskin** [comment]
The header in the mock and the AC are off (which is fine as long as we call it out), so just want to make sure -- should the title say unsaved changes or unsaved comments?

**Comment by gnakm** [comment]
@abbyraskin thanks. Didn't update the mock from bottom comment. It should be unsaved comments because changes can imply other things like categories, etc..

**Comment by gnakm** [comment]
Original AC just incase

**Story**
As a user, I want to know if I have any unsaved comments in a document viewer before I leave or exit the page.

Note: Sunil and I had a discussion that the browser will default to it's escape pop up and we should use that with the text provided below. 
## AC
- [] 
- [ ] Verify that a modal pops up when a user tries to leave the page (x-out, go back to doc list) when there are 1 or more comments open
- [ ] Verify that it matches the copy below

## Mock up
![image](https://cloud.githubusercontent.com/assets/13420618/25880371/ed43933c-3504-11e7-9c9d-2a1d982ac884.png)

## Copy
Title: Unsaved Comments
Body: You have unsaved comments. Are you sure you want to leave this page without saving?
Cancel text: Oops! Go back
Confirm text: OK, leave page
^ OK should be all caps (unlike mock)

**Comment by sunil-sadasivan** [comment]
@gnakm, after some more researching it looks as if chrome/firefox have removed support for changing the default messaging when closing the window. 

https://www.chromestatus.com/feature/5349061406228480
https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup

These are the states that look to be possible:

**Reloading the tab**
<img width="699" alt="screenshot 2017-09-19 10 03 30" src="https://user-images.githubusercontent.com/31223104/30596369-e7d3853a-9d21-11e7-9201-b844ecfb05ba.png">


**Exiting the tab**

<img width="755" alt="screenshot 2017-09-19 10 04 50" src="https://user-images.githubusercontent.com/31223104/30596415-0107bf94-9d22-11e7-9036-ae49943ee6bd.png">

**Changing (but not exiting the tab) to a new page within caseflow**
<img width="777" alt="screenshot 2017-09-19 10 09 01" src="https://user-images.githubusercontent.com/31223104/30596630-b2ebb9e0-9d22-11e7-9dd7-b590b2b2cfdf.png">

Not ideal, how does this feel for you @gnakm?

**Comment by gnakm** [comment]
Dropping last AC here. We decided to move on with autosave.
**Story**
As a user, I want to know if I have any unsaved comments in a document viewer before I leave or exit the page.

Note: Sunil and I had a discussion that the browser will default to it's escape pop up and we should use that with the text provided below. 

## AC
- [ ] Verify that the browser pop up has the following copy below when user 1. hits the back to documents list link or 2. escapes tab.

## Copy
Title: Unsaved Comments
Body: You have unsaved comments. Are you sure you want to leave this page without saving?

**Comment by kierachell** [comment]
**PASSED**

Nice! Vari nice!
<img width="538" alt="screen shot 2017-09-21 at 10 19 46 am" src="https://user-images.githubusercontent.com/18075411/30700737-74578606-9eb6-11e7-9a8a-6d52d78791c7.png">
![unsaved](https://user-images.githubusercontent.com/18075411/30700738-7458a766-9eb6-11e7-9abc-e1a8588bbce7.gif)
