### ISSUE TITLE
Document list | Sort/comment icons: missing svgs

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1750]
Noticed that some of the icons on the document list view are still in font awesome instead of svg. 

## AC
- Verify that the following mockups need to be replaced by appropriate svg files
- Get rid of the double ended arrow icon and replace it with double arrow icon

## Mockups
![image](https://user-images.githubusercontent.com/13420618/27437213-8b230cc6-572f-11e7-92c5-7a4a7135a69b.png)
^ this has got to go. 

![image](https://cloud.githubusercontent.com/assets/13420618/25454796/acc31fda-2a9b-11e7-9d81-f2c843f8fc89.png)
[Arrow-down.svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Arrow-down.svg)
[Arrow-up.svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Arrow-up.svg)

![image](https://cloud.githubusercontent.com/assets/13420618/25454839/c8bc59e0-2a9b-11e7-8b20-ba28abb0ba96.png)
[Chevron-down.svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Chevron-down.svg)
[Chevron-up.svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Chevron-up.svg)

![image](https://user-images.githubusercontent.com/13420618/27548665-9effead0-5a67-11e7-9b69-ce7bda912354.png)
[Double arrow](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Double%20arrow.svg)

**Comment by Sjones352** [comment]
@gnakm and @abbyraskin  I can't seem to find a corresponding arrow-up.svg in the design/icon repo.
<img width="132" alt="screen shot 2017-06-22 at 9 02 14 am" src="https://user-images.githubusercontent.com/23080951/27435270-9ff2ba80-5729-11e7-918e-7121b15a9007.png">
We only have the Arrow-down svg. I am currently blocked.
<img width="133" alt="screen shot 2017-06-22 at 9 05 15 am" src="https://user-images.githubusercontent.com/23080951/27435345-f3a4f080-5729-11e7-8445-7323af89324f.png">

**Comment by gnakm** [comment]
@Sjones352 updated above ^

**Comment by Sjones352** [comment]
@gnakm and @abbyraskin  Currently It looks like this
![reader](https://user-images.githubusercontent.com/23080951/27460269-c77f0ebc-5780-11e7-9fe1-5a6b982c9eaa.gif)

**Comment by Sjones352** [comment]
Currently looks like this. 
![reader](https://user-images.githubusercontent.com/23080951/27520949-e4c49cb6-59e3-11e7-8814-4b823d341d5e.gif)

**Comment by gnakm** [comment]
@Sjones352 Yes! That's exactly how we wanted it to look like :)

**Comment by gnakm** [comment]
@Sjones352 So the problem we discussed in person is that without an icon, it's hard to tell if one of the sortable headers is clickable. I added a new icon to replace the previous icon we had.

**Comment by Sjones352** [comment]
@gnakm Currently

![reader](https://user-images.githubusercontent.com/23080951/27557014-fc9f6a4e-5a85-11e7-9a34-61d9b7cb30f9.gif)

**Comment by gnakm** [comment]
@Sjones352 sorry i re-uploaded the double arrow svg file (it's updated in the AC) because the space between the two arrows looked too tight. https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Double%20arrow.svg

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate:
1. Access Reader
2. Navigate to the sorting columns in the Document List view. 
3. Validate that the headers indicated have been changed from font awesome to svg files. 

Screenshots:
<img width="1069" alt="screen shot 2017-06-28 at 10 50 15 am" src="https://user-images.githubusercontent.com/23038505/27643820-1add5a96-5bf0-11e7-9969-38588fb583cd.png">
<img width="1078" alt="screen shot 2017-06-28 at 10 51 01 am" src="https://user-images.githubusercontent.com/23038505/27643821-1ae02f00-5bf0-11e7-8cb3-3a87c0b5f1b4.png">
<img width="1051" alt="screen shot 2017-06-28 at 10 51 18 am" src="https://user-images.githubusercontent.com/23038505/27643819-1adcf4ac-5bf0-11e7-9b3e-506f14f08893.png">
