### ISSUE TITLE
Document viewer | Issue description

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1753]
As a user, I want to know that I have the apply to Select or tag issues to the document I have open, without any confusion. 

## AC

- [x] Change the issue tag description to the text below. 

## Mock
![image](https://cloud.githubusercontent.com/assets/13420618/25460855/ac699024-2ab3-11e7-8b05-8c9d335eec56.png)

## Copy 
Select or tag issues

**Comment by kierachell** [comment]
**PASSED**
