### ISSUE TITLE
Document Viewer | Bug: issues dropdown suggests you create the issue tag you just added

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1758]
**Description**
Currently, if you create a new issue tag, navigate to another document and click into the issues search box, it suggests you create the same tag you just added.

**Expected**
The issues search/dropdown should be blank until the user starts typing in a new issue; the suggested text should reflect the issue name you type into the box, rather than the one you just created (or should be blank if you have not typed in anything).

**Steps to reproduce**
1. Create a new issue tag on a document
1. Navigate to another document that does not yet contain the issue tag you just created
1. Click inside the issue tag search box and the selected text will show the tag you just created as a suggested tag to add

[screenshot]

**Comment by abbyraskin** [comment]
Duplicate of #1729, closing

**Comment by tejans24** [comment]
This is fixed in #1729

**Comment by kierachell** [comment]
**PASSED**
![createme](https://cloud.githubusercontent.com/assets/18075411/26180042/fb59f6a6-3b34-11e7-8b67-51dd2b33a871.gif)
