### ISSUE TITLE
Re-evaluate root request

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1762]
It has been suggested by some that, upon visiting `/`, the user is routed to a page within the application connected to his/her role.  @shanear suggested the following approach:

What we want to do is choose a "default application" for a user. We already have a `users` table in the DB, and we really want to avoid storing anything besides a user identifier and whatever we get back from SSO in the session unless we absolutely have to (for a variety of reasons, let me know if you want to chat about those). So if anything, we'd probably want to set it in the DB.

The next question is, how should we set a user's default application. My thought is that we should try and infer it from their roles instead of setting it and resetting it on each request (which is the part that is chaotic and error prone). For example, if the user has "Certify Appeal" and nothing else, their default application should be "Certification".

If they have multiple roles (which very few users do), then I think it's probably fine to just choose one to be their default application.

Because their default application can be derived from their roles (which we have in the user's session already) we don't need to store it in the session or the DB. We can just add a function to user `User.default_application` which performs the logic I described above.

That way it's unit tested and encapsulated.

**Comment by shanear** [comment]
Thanks @slj!

**Comment by NickHeiner** [comment]
@lakohl @laurjpeterson is this a thing that we want to implement from a product / design perspective? Or should we close this ticket?

**Comment by lakohl** [comment]
What we did in Dispatch is provide the Manager (who is the only user with two roles) with two different links. One gives them access to the Manager View, and the other gives them access to the Claims Assistant view in the event that they have to establish a claim themselves.

**Comment by NickHeiner** [comment]
Ok, so is there more work to do here for the other apps?

**Comment by NickHeiner** [comment]
Based on an in-person conversation with @laurjpeterson, I'm going to close this. We have already done the Dispatch-relevant work here, as @lakohl notes.
