### ISSUE TITLE
Document Viewer | Issue tags text length, whitespace validation, and textbox size

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1767]
# Description
When adding issues for a document, the UI breaks a bit when adding long issues.
When adding issues whitespace validation is a bit inconsistent?

## Reproduction Steps

**Scenario 1 -**

1. Go to view a document
1. Start typing like mad cause this dude's got a lot of issues
1. Note that whitespace is not trimmed
1. ~~Note that textbox size affects the whole UI~~ Moved to #1875
1. ~~Note that long issues are hard to delete~~ Moved to #1875

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Whitespace Disappearing? Or not?]_**
![whitepsace](https://cloud.githubusercontent.com/assets/18075411/25508199/71679b58-2b7e-11e7-9113-336c16316898.gif)

## Related issues
#1515

**Comment by gnakm** [comment]
@mdbenjam and I just talked about this in person. 
The issue tags should always be in one line. If it is too long to fit in the dropdown text box, it should be in the second line. 
Incorrect:
![image](https://cloud.githubusercontent.com/assets/13420618/25583234/fa823a3c-2e5e-11e7-849e-94048df4989f.png)

Correct:
![image](https://cloud.githubusercontent.com/assets/13420618/25583208/d117ecdc-2e5e-11e7-9ac9-bb6dbf009998.png)

@kierachell adding it to the AC above.

**Comment by gnakm** [comment]
@kierachell I'm writing out a separate issue for the text box part of this issue here #1875

**Comment by kierachell** [comment]
**PASSED**
whitespace issue fixed, there rest is captured
![whitespacetags](https://cloud.githubusercontent.com/assets/18075411/25748080/dc787c88-3177-11e7-9f12-1b33d1ff8da2.gif)
