### ISSUE TITLE
Unable to expand the view on documents after one has already been selected

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1773]
**Description:** 
In Reader, on the List Documents page, if a user expands the view for a document that has comments, they will not be able to toggle between other like documents. 

**Expected:** Users should be able to expand all documents on the List Document view. 

**Steps to Reproduce:** 
1. Go to Reader
2. Expand a document that has comments, in the List Documents view. 
3. Try to do the same manually for like-wise documents. 

**Screenshots:**
![readerexpandview](https://cloud.githubusercontent.com/assets/23038505/25530724/47667262-2bf5-11e7-8138-c81ce4e25e5b.gif)

*If the cursor hovers more than a second over a button that means that the feature has been disabled.

**Comment by abbyraskinUSDS** [comment]
This is outdated - closing.
