### ISSUE TITLE
Removal of babel-polyfill package crashed production

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1775]
Around **4/28/2017 at 6:45am** [this alert](https://dsva.slack.com/archives/C4JECDLSE/p1493376314907139) (followed by similar ones around **30 minutes** apart) citied this error:

`TypeError: Object doesn't support property or method 'assign'`

Around **8:30am** it was confirmed that **Dispatch** was reporting an alarming volume of errors.

As explained in [this pull request](https://github.com/department-of-veterans-affairs/caseflow/pull/1772), the root cause was a recent build missing the `babel-polyfill` package needed by older browsers that don't natively support `Object.assign`.

Once the package was re-added and ASG redeployed to production, the problem was solved.

At **10:01** another `Object.assign` error was reported by Sentry, likely caused by a user working with the previous build.  Once users refresh their application, the polyfill should take effect.

**Comment by slj** [comment]
@kierachell do you validate or close post-mortems?  Can I close this?  Please advise.

**Comment by kierachell** [comment]
Yeah, I have an action item to use IE for some tests; so this is fine to close now
