### ISSUE TITLE
Open in New Tab | Document should be marked as read

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1776]
## Description
Currently when you open a document in a new tab, it remains bolded as unread.

## Dev Notes
Update the Redux store when the document is selected.

## AC
- Validate that when I open an unread document in a new tab, the Document Type link is unbolded ("read" state)

**Comment by kierachell** [comment]
**PASSED**
But doesn't quite work with keyboard ?
![readmebabyonemoretime](https://user-images.githubusercontent.com/18075411/27520815-72b0d1a0-59e1-11e7-8471-4853d016a104.gif)

**Comment by mogrenAtWork** [comment]
@kierachell do we need a ticket for this to work with the keyboard?

**Comment by kierachell** [comment]
- It hasn't really worked for a while.... in many different forms: either just erroring, or 404ing, or not marking as read...or a lot of ways.
https://github.com/department-of-veterans-affairs/caseflow/issues/1734
