### ISSUE TITLE
Tag has to be deleted twice before being deleted after being added from the dropdown

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1781]
Steps to reproduce:
* Select a tag from the dropdown menu.
* Try to delete the tag.
* Delete has to be clicked twice before it goes away.

**Comment by abbyraskin** [comment]
@tejans24 does this happen every time?

**Comment by abbyraskin** [comment]
I haven't been able to reproduce this...

**Comment by tejans24** [comment]
@abbyraskin I can't reproduce it either right now. I'll close it until I see this happen again.
