### ISSUE TITLE
Filter Dropdown | Should update position

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1788]
![screen shot 2017-04-28 at 6 23 31 pm](https://cloud.githubusercontent.com/assets/3885236/25549460/cfadc69e-2c3f-11e7-81ee-9e514b7dfd2a.png)
Currently when the filter alert is shown, the page gets pushed down and the filter box is unaligned.

**Comment by kierachell** [comment]
**PASSED**
Noticed it working well today :D
