### ISSUE TITLE
Documents List | Search: receipt date shouldn't require formatting

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1789]
Currently, you have to enter the format YYYY-MM-DD to search by date.

Searching by receipt date should work with different date forms. For example. 4/17/2017, 04/17/2017, and 4-17-2017 should all work.

## AC
1. Verify searching by MM/DD/YYYY format returns documents with receipt dates on that day.
1. Verify searching by MM-DD-YYYY format returns documents with receipt dates on that day.
1. Verify leading zeros are not required in either the month or the day
1. Verify that searching for the day or year (with a / or none at the beginning) returns documents with those days/years in the receipt date 
   - Examples: 
      - searching for /2017 or 2017 should return documents with receipt dates in the year 2017
      - searching for /20 or 20 should return documents with a receipt dates on the 20th of the month

**Comment by kierachell** [comment]
### Technically this is passed, but I was wondering if users would like "by year" and or "by month" filtering.

There's a cool side-effect to current functionality by entering `/` or `//` is this ok @abbyraskin ?

![dates](https://user-images.githubusercontent.com/18075411/27254333-4e7d74e8-5354-11e7-94a7-c2b490ba4588.gif)

**Comment by abbyraskin** [comment]
@kierachell good catch. @tejans24 i think we should broaden the scope slightly to allow users to more intuitively search by day or year. right now, they have to enter // before a year, or / before a day for it to return the docs. 

Examples:
- searching for /2017 or 2017 should return documents with receipt dates in the year 2017
- searching for /20 or 20 should return documents with a receipt dates on the 20th of the month

**Comment by mdbenjam** [comment]
@abbyraskin you mention searching by date and year, but do we also want it for months?

**Comment by mdbenjam** [comment]
In hindsight, I don't think this matters. Since month is the first in the date we get that behavior for free.

**Comment by abbyraskin** [comment]
@mdbenjam yep, I left it out for that reason (I do think it's valuable to have that option as well) ☺️

**Comment by kierachell** [comment]
**PASSED**
<img width="929" alt="screen shot 2017-06-22 at 11 56 37 am" src="https://user-images.githubusercontent.com/18075411/27443707-f999bd5a-5741-11e7-9934-bf8a70fb770a.png">
<img width="729" alt="screen shot 2017-06-22 at 11 56 43 am" src="https://user-images.githubusercontent.com/18075411/27443706-f9962bb8-5741-11e7-809a-daac88b256c7.png">
<img width="1173" alt="screen shot 2017-06-22 at 11 57 09 am" src="https://user-images.githubusercontent.com/18075411/27443705-f995f01c-5741-11e7-8642-c6a8e07c1385.png">
