### ISSUE TITLE
Add "When VACOLS is down help content"

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#179]
We should provide instructions about what to do when VACOLS is down (AKA proceed to certify appeals by hand) 

https://github.com/department-of-veterans-affairs/appeals-pm/issues/117

**Comment by lakohl** [comment]
@RTOLSON @Sjones352 Do you want to take a stab at this when you finish the eX NSD requirements?

**Comment by Sjones352** [comment]
@lakohl I will definitely work on this issue

**Comment by RTOLSON** [comment]
I will help as well

**Comment by Sjones352** [comment]
@lakohl I talked to @KHarshawat and he says that we should close this issue because we don't control VACOLS.

**Comment by lakohl** [comment]
That's true! Closing
