### ISSUE TITLE
Redux | Add documents to store on creation

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1790]
We currently add documents to the store in the DecisionReviewer constructor. However, this is too late, since the first call to render will not have access to the documents. We then have to do a null check before rendering. Once the redux store is updated, we'll get triggered again with the documents and can render on that call. Instead we should add documents to the store on initialization, so that we can render properly on the first pass through.

**Comment by NickHeiner** [comment]
@mdbenjam I don't totally understand what the problem is here. Can we chat about this?

**Comment by mdbenjam** [comment]
Updated the above description, let me know if it still doesn't make sense.

**Comment by mdbenjam** [comment]
No longer relevant.
