### ISSUE TITLE
Tag filter div reloads and scrolls to the top after updating

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1792]
When a tag from the bottom is selected from the tag filter when scrolling is enabled, the dom refreshes and the view goes back to the top of the filter div. 

Instead, the view should stay where it is.

## AC
- When a user selects an issue tag below the scroll in the filter menu, the view stays put/does not scroll to top 

## Related 
 #1791

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
