### ISSUE TITLE
Add a close window link at the end of Caseflow

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#18]
> I'm not sure this is possible? AFAIK, the javascript stuff for closing a window only works for popups, you can't close a normal tab/window from JS.

--

> Gotcha -- you're probably right. I'll take a look a little later on. Super low priority task for now.

--

> `window.close()` hilariously works to close a non-popup on MSIE, but nothing else, ISTR

--

> All versions of IE? (IE is the vast majority of our users, sadly)

--

> Unknown - but it worked at some time in recent memory -- Easy enough to test next time I'm on a windows machine

**Comment by plusjeff** [comment]
Closing this, since letter generation will likely be the end step. Also, folks are pretty good at knowing how to close windows.
