### ISSUE TITLE
Unhandled/unexpected Nil UserQuota instance

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1803]
Sentry Trace [here](https://files.slack.com/files-pri/T03FECE8V-F57SPD2S2/image.png)

**Comment by ToddStumpf** [comment]
From:
  https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/171/

This looks like an application edge case of establish_claims_controller.rb#user_quota returning nil due to current_user lacking a quota for today (or perhaps current_user is invalid).

**Comment by slj** [comment]
Issue re-occurred on 5/2 at 8:10am:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/171/

**Comment by slj** [comment]
Issue re-occurred on 5/4 at 8:37am

**Comment by kierachell** [comment]
**PASSED**
Started a task one day, completed next...didn't explode
