### ISSUE TITLE
Document list | Remove icon in search box when field is empty

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1804]
**Story**
As a user, I want to know when my doc list is being filtered with the x indicator

**Description**
Currently x icon is in search box even when search is not being used.

## AC
- [ ] Verify that x icon is not in search box when search is not being used
- [ ] Verify that it is there when search is being used

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/25594621/5c9f6cd2-2e8f-11e7-99d9-8b17272de1d7.png)

![image](https://cloud.githubusercontent.com/assets/13420618/25594661/8a7acb2e-2e8f-11e7-9eb9-450fe5dc9f3b.png)

**Comment by kierachell** [comment]
**PASSED**
<img width="613" alt="screen shot 2017-05-22 at 11 24 57 am" src="https://cloud.githubusercontent.com/assets/18075411/26316157/537a60e6-3ee1-11e7-94ca-86c928bf4680.png">
<img width="728" alt="screen shot 2017-05-22 at 11 25 00 am" src="https://cloud.githubusercontent.com/assets/18075411/26316156/535071c8-3ee1-11e7-9faf-419bbf2cb434.png">
