### ISSUE TITLE
Styleguide component | Progress Bar edits

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1806]
**Story**
As a developer or designer, I want to know what the progress bar should look like across all caseflow apps. 

The progress bar in the living style guide needs edits that match new AC

## AC
- [ ] Bump up text size from 17px to 18px
- [ ] Make sure that the spacing between the text and progress bar is 11px

## Mockups
![image](https://cloud.githubusercontent.com/assets/13420618/25596107/82b03c84-2e95-11e7-892d-9de9ff446b7e.png)

**Comment by kierachell** [comment]
**PASSED**
font size 18px
<img width="720" alt="screen shot 2017-05-16 at 9 03 15 am" src="https://cloud.githubusercontent.com/assets/18075411/26107228/8e2fbcce-3a16-11e7-8681-b7fc7e7f4a4e.png">
space between the text and the bar is high enough (impossible to measure).
