### ISSUE TITLE
Styleguide component | Banner Alert Lite

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1807]
As a developer and designer, I want a consistent and easy way to implement Alert Banners so users can identify if important tasks were completed correctly.   

## Acceptance Criteria

1. Verify that in the living style guide that there is a title called Alerts lite
1. Verify that this is a subsection of Alerts
1. Verify that clicking on the side nave takes you to the appropriate section
1. Verify that each Alert has the appropriate icon adapted from the [USWDS Alerts](https://standards.usa.gov/components/alerts/)
1. Verify that the text is in 19 px and has 19px left and right padding
1. Verify that the order of the alerts displayed matches the mocks

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25596655/4ea77cb0-2e98-11e7-9f66-d1b80ca91c84.png)

![image](https://cloud.githubusercontent.com/assets/13420618/25596649/4512d320-2e98-11e7-97f4-880b3278435e.png)

## Copy

**Title:** 
Alerts lite

**Description:** 

Alert lite is a lighter version of our banner alerts designed for sections in our app with a different layout, specifically to call out features with smaller dimensions. Currently it is being used in the Caseflow Reader Menu.

**Comment by mmlumba** [comment]
Notes for Marian: 
320x62px for Banner Lite
Font size 22px
Space between icon and text is 19px

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Styleguide
2. Navigate to the Alerts section 
3. Validate that the Alerts-lite section roughly matches the AC and mocks posted 

Screenshots: 
<img width="1440" alt="screen shot 2017-08-16 at 11 50 19 am" src="https://user-images.githubusercontent.com/23038505/29373095-1ca3b940-827b-11e7-9a35-af389d507f31.png">
