### ISSUE TITLE
Document list | Issue tag dropdown hover

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1809]
Currently there is no hover for the issue tag drop down. 

![image](https://cloud.githubusercontent.com/assets/13420618/25597110/f154e068-2e9a-11e7-8f7c-80b218531270.png)

## Related issue
#1438

**Comment by abbyraskin** [comment]
@Sjones352 wanna take this one?

**Comment by Sjones352** [comment]
@gnakm yes since I am fixing it already lol.

**Comment by Sjones352** [comment]
Screenshot
<img width="248" alt="screen shot 2017-07-11 at 1 12 58 pm" src="https://user-images.githubusercontent.com/23080951/28080676-c30be404-663a-11e7-9d26-ed51fd5992a7.png">

**Comment by gnakm** [comment]
@Sjones352 Hover? 😃

**Comment by Sjones352** [comment]
@gnakm  Hover.

![hover](https://user-images.githubusercontent.com/23080951/28083761-790664ce-6644-11e7-9415-8a00ceffac25.gif)

**Comment by kierachell** [comment]
**PASSED**
![peek 2017-07-12 13-12](https://user-images.githubusercontent.com/18075411/28130141-efaae52c-6703-11e7-836b-8a121832f418.gif)
