### ISSUE TITLE
VBMS Appeals Service Request yielding 500 Error

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1811]
Sentry trace: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/154/

**Comment by shanear** [comment]
This is due to a vet lacking an SSN (which we handle correctly because of https://github.com/department-of-veterans-affairs/caseflow/pull/1571). Maybe we should suppress that error.

**Comment by askldjd** [comment]
@shanear Do you mean we should suppress the error in Sentry, or in the code?

**Comment by shanear** [comment]
@askldjd This is a known error that we handle in the best way we know. It's possible we should suppress those types of errors in the code. Thoughts?
