### ISSUE TITLE
Add Sidekiq UI

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1820]
Add sidekiq UI for better information on the stats related to our background jobs and when they last ran

connect https://github.com/department-of-veterans-affairs/caseflow/pull/1815

**Comment by kierachell** [comment]
So, uh... what are we validating? Is there a related PR just for context?

**Comment by joofsh** [comment]
Hey sorry, yes. my fault. This change is related to the bug here https://github.com/department-of-veterans-affairs/caseflow/issues/1814
It was resolved in a PR here: https://github.com/department-of-veterans-affairs/caseflow/pull/1815

**Comment by joofsh** [comment]
To QA:
- Go to `/sidekiq` in your environment
- You should get asked for basic authentication. The login info for uat, preprod, and prod are in 1Password
- Once authed, you should see the Sidekiq UI, with information all our jobs, crons, and when they were last run

**Comment by kierachell** [comment]
Whoa
Cool:
<img width="1320" alt="screen shot 2017-05-08 at 2 38 47 pm" src="https://cloud.githubusercontent.com/assets/18075411/25819485/1a2bcf18-33fc-11e7-929e-8d87af4ab4a2.png">

**Comment by kierachell** [comment]
<img width="1248" alt="screen shot 2017-05-08 at 2 41 38 pm" src="https://cloud.githubusercontent.com/assets/18075411/25819699/c8e3b6f6-33fc-11e7-8540-6bde9022661e.png">
SUPERCOOL

@astewarttistatech should still check it out, 'cause it's cool!

**Comment by kierachell** [comment]
**PASSED**

We should document this somewhere.

**Comment by kierachell** [comment]
Hangon, I didn't check prod. This is not set up in prod.
```
export SIDEKIQ_PASSWORD=""
export SIDEKIQ_USERNAME=""
```

**Comment by kierachell** [comment]
**PASSSED**
Prod works now too:
<img width="1154" alt="screen shot 2017-05-11 at 10 22 07 am" src="https://cloud.githubusercontent.com/assets/18075411/25954375/1a20aa18-3634-11e7-9ec1-5b8ec62f6947.png">
