### ISSUE TITLE
Tags | Index DB by text

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1824]
We currently do not index our tags table by text, yet we look up tags by the text within them. We should index tags by text.

## AC
1) Verify that there's an index on the `text` column of the `tags` table.

**Comment by mdbenjam** [comment]
How to deal with race conditions?

**Comment by NickHeiner** [comment]
As we discussed in person: no need to deal with race conditions if we're indexing by text.

**Comment by kierachell** [comment]
**PASSED**
Successfully made it fail with duplicate tag text :D
