### ISSUE TITLE
Fix a couple of CSS quirks in StyleGuide

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1827]
1. At a small enough width, the content and nav menu overlap:
<img width="571" alt="screen shot 2017-05-02 at 9 46 56 am" src="https://cloud.githubusercontent.com/assets/1053255/25644417/ca2cf532-2f73-11e7-9000-2c3b33c25b2d.png">

2. The container for the title and `View source code` button do not render consistently.  Most of the time the dividing line is not flush against the button, but sometimes it is:
![headers_inconsistent](https://cloud.githubusercontent.com/assets/1053255/25644443/034ece30-2f74-11e7-8d15-29a970e5b596.gif)

**Comment by slj** [comment]
Improvement in action:
![sg_less_quirky](https://cloud.githubusercontent.com/assets/1053255/25664923/1528a7d6-2fea-11e7-8b02-8c4da183d9e3.gif)

**Comment by astewarttistatech** [comment]
Failed. Still wonky, sorry @slj 

Validated in: Dev
Browsers: Chrome and FF

Steps to Validate: 
1. Access the Living Style Guide 
2. Manipulate the height and width of the style guide to see if anything overlaps or breaks. 

Screenshots: 
![sgmanipulation](https://cloud.githubusercontent.com/assets/23038505/25707176/b8b8411a-30b0-11e7-8719-05664e5d2a81.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Dev, UAT, and Preprod
Browsers: Chrome and FF

Steps to Validate:
1.Shrink browser to its smallest view
2.Validate navbar doesn't overlap content in style guide. 

Screenshots: 
Smallest width
<img width="399" alt="screen shot 2017-05-08 at 11 21 00 pm" src="https://cloud.githubusercontent.com/assets/23038505/25834330/36f10b4c-3445-11e7-9194-059bcf982928.png">
