### ISSUE TITLE
Fix `Uncaught TypeError: Cannot read property 'checked' of undefined` bug

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#183]
Appears on `certifications/janice-snuffy/start` and is breaking other JS on the page.

Likely caused by `$("input[name='13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER']")[0].checked`

Need to check whether `input[name='13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER']` exists on the page, or try:

    $("input[name='13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER']")[0].attr('checked')

**Comment by alex** [comment]
Probably we should only have that whole function run if you're actually on
the questions page?

On Tue, Nov 17, 2015 at 2:13 PM, Tiffany Brown <notifications@github.com>
wrote:

> Appears on certifications/janice-snuffy/start and is breaking other JS on
> the page.
>
> Likely caused by
> $("input[name='13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER']")[0].checked
>
> Need to check whether
> input[name='13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER']
> exists on the page, or try:
>
> $("input[name='13_RECORDS_TO_BE_FORWARDED_TO_BOARD_OF_VETERANS_APPEALS_OTHER']")[0].attr('checked')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/183>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by webinista** [comment]
Yeah. Right now, all of those form-related functions are running on page load without checking whether the objects they affect are available to the DOM.
