### ISSUE TITLE
Limit Reader access to pilot users

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1831]
Currently, there are a few users with access to Reader who should not have access. We should navigate users to the "unauthorized" view if they are not on the list of pilot users below.

## Pilot CSS IDs with "Reader" function
BVACBOYD
BVAEBRANDAU
BVAMBRUCE
BVAMHARRIGAN
BVAMLAVAN
BVAMLKANE
BVAMNYE
BVAMPETERS
BVANKROES
BVAPRUBIN
BVARCOSTELLO
VACOPARSOA
VACOSCARDR
VACOTIMBEM
BVADWIGHT
BVAKHUBERS
BVALKYLE
BVAMHYLAND
BVARVELDENZ
BVARWATKINS
BVASGORDON

## Pilot users with "Sys Admin" function
BVANHOLTZ 
BVAJNICHOLS

**Comment by abbyraskin** [comment]
@joofsh here are the IDs we have so far, will try to figure out the rest:

![image](https://cloud.githubusercontent.com/assets/4042181/25709474/7628bc4c-30b7-11e7-8d38-be4fa275417d.png)

**Comment by joofsh** [comment]
@abbyraskin awesome thanks abby! After today's prod deploy (~3pm) I will whitelist those 14 users. We'll have to whitelist the rest as they login to our system. It might be helpful to ask all pilot users to login now so that we can catch their css ids?

**Comment by abbyraskin** [comment]
OK! that's everyone with Reader access so far, so I don't think anyone else can log in.

**Comment by abbyraskin** [comment]
@joofsh the folks we are missing are actually supervisors who haven't actually been active participants in the pilot -- will remove their names from above list in description.

**Comment by kierachell** [comment]
I reckon this is to be properly validated in prod, assignign @abbyraskin

**Comment by abbyraskin** [comment]
Jane Nichols and Nicholas Holtz also need access as sys admin -- BVANHOLTZ and BVAJNICHOLS

**Comment by abbyraskin** [comment]
@kierachell I just added a section for users w/ sys admin access to the description above.

**Comment by kierachell** [comment]
**FAILED**

Unauthorized users should see an *Unauthorized* page, but currently there's a DoubleRender error:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/196/

<img width="1107" alt="screen shot 2017-05-08 at 2 36 38 pm" src="https://cloud.githubusercontent.com/assets/18075411/25819362/c61973b2-33fb-11e7-8123-f6181d676aeb.png">

**Comment by abbyraskin** [comment]
@joofsh Nicholas and Jane are no long able to log in to Reader. Are their User IDs on the whitelist as sys admin users (in the ticket description)?

**Comment by abbyraskin** [comment]
(I can create a new ticket if not)

**Comment by joofsh** [comment]
Unrelated to this ticket, was due to block all System Admins except CSFLOW

**Comment by kierachell** [comment]
**PASSED**

Well, no one is complaining so just gonna close this.
