### ISSUE TITLE
Document Viewer | Loader

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1837]
**Story**
As a user, I want to know when the document files are still loading in the viewer

## AC 
- [ ] Add loader (4 pt stars) with [reader green from style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#loaders)
- [ ] Copy underneath the loader is "Loading document in Reader…"

**_NOTE: 1. Mock has the word "now" but take that out 2. The toolbars in document viewer looks different today_**
 
## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25685672/2609f6e8-3037-11e7-9165-a76e83811895.png)

**Comment by abbyraskinUSDS** [comment]
Not building this, as documents load much more quickly now. Closing.
