### ISSUE TITLE
Duplicate key throwing warning for StyleGuideMessages

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1838]
<img width="1435" alt="screen shot 2017-05-03 at 3 53 08 pm" src="https://cloud.githubusercontent.com/assets/1053255/25678949/98c8a404-3019-11e7-882f-caa8f0f46745.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Go to the Style Guide
2. Open the browser's console
3. Validate that no errors are found. 

Screenshots: 
<img width="1400" alt="screen shot 2017-05-05 at 1 54 49 pm" src="https://cloud.githubusercontent.com/assets/23038505/25758118/3bc0141c-319b-11e7-9b05-e2208d03e726.png">
