### ISSUE TITLE
StyleGuideLayout component causes ValidDOMNesting warnings

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1839]
<img width="1435" alt="screen shot 2017-05-03 at 3 53 08 pm" src="https://cloud.githubusercontent.com/assets/1053255/25679008/d0e178c0-3019-11e7-9781-b3fcd4da6f69.png">

## Acceptance Criteria
Please visit `/styleguide` with the developer console open - you should **not** see these warnings.

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Go to the style guide
2. Open console
3. Validate that no errors are appearing.
<img width="1400" alt="screen shot 2017-05-05 at 1 54 49 pm" src="https://cloud.githubusercontent.com/assets/23038505/25757944/9cf62146-319a-11e7-9af2-f83d03b92b14.png">
