### ISSUE TITLE
TextField component causes Failed Prop Type Warning

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1840]
<img width="1435" alt="screen shot 2017-05-03 at 3 53 08 pm" src="https://cloud.githubusercontent.com/assets/1053255/25679097/1b9e6cce-301a-11e7-9cd8-1db2889d9114.png">

## Acceptance Criteria
Please visit `/styleguide` with the developer console open - you should **not** see this warning.

**Comment by kierachell** [comment]
**PASSED**
Didn't see that one either.
