### ISSUE TITLE
CheckboxGroup component causing Failed Prop Type warning

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1841]
<img width="549" alt="screen shot 2017-05-03 at 4 05 25 pm" src="https://cloud.githubusercontent.com/assets/1053255/25679185/6033320c-301a-11e7-88b5-cb5d26215c1d.png">

## Acceptance Criteria

Please visit `/styleguide` with the developer console open - you should **not** see this warning.

**Comment by kierachell** [comment]
**PASSED**
Went to Styleguide...didn't see errors
