### ISSUE TITLE
Style guide component | Loaders

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1843]
**Story**
As a user, I want to know when my application or page is loading so that I can wait for my information or task without getting confused.

## Note 
- For the style guide, let's use the one for dispatch as an example since it is currently the only app that is using it correctly and I like displaying something with two colors as an example, opposed to using the default
- We shouldn't fix the dimensions of these loaders because it will be case by case depending on the app. For now the default can be what's being used in dispatch

## AC
- [x] Verify that there is an animated 4 point starwave (not the 6 point) loader (taken from dispatch)
- [x] Verify that there is a message that says "Gathering information in VBMS now..."
- [x] Verify that the copy below is under Loaders

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/25679099/1bf8124c-301a-11e7-93e3-bfa75295850c.png)

## Copy
A large Caseflow loading indicator in the center of the page is used when some information has been retrieved but other information is still being pulled. Each loader should have a message underneath the logo in `gray-dark` that explains what is currently happening or where the information is being drawn from.

**Comment by Sjones352** [comment]
<img width="1180" alt="screen shot 2017-05-30 at 1 37 24 pm" src="https://cloud.githubusercontent.com/assets/23080951/26596817/01699700-453e-11e7-925c-491bedb972b3.png">

**Comment by gnakm** [comment]
@Sjones352 
Could you decrease the space between the loader and the copy by 40px?
Could you make sure Gathering information in VBMS now... is center-aligned with the loader?

**Comment by Sjones352** [comment]
<img width="1217" alt="screen shot 2017-05-31 at 7 08 18 pm" src="https://cloud.githubusercontent.com/assets/23080951/26657887/acdb51b8-4634-11e7-9ed9-6274118c8feb.png">

**Comment by gnakm** [comment]
lgtm! 👍

**Comment by astewarttistatech** [comment]
**PASSED**  @gnakm Should the message under the loader be centered?

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living style guide
2. Navigate to the Loaders section
3. Validate the UI against the AC displayed in the ticket

Screenshots: 
![loaders](https://cloud.githubusercontent.com/assets/23038505/26730036/ab015514-477d-11e7-8e15-4321fb0c59a2.gif)
