### ISSUE TITLE
Removing a tag before it's saved on the server throws an error in the browser

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1845]
* Create a tag
* remove it before it's saved on the server and has an Id assigned
* Notice a console error

<img width="827" alt="screen shot 2017-05-03 at 4 44 35 pm" src="https://cloud.githubusercontent.com/assets/1976755/25681204/7b8bd21e-3021-11e7-819a-118ca9113693.png">

<img width="596" alt="screen shot 2017-05-03 at 4 55 12 pm" src="https://cloud.githubusercontent.com/assets/1976755/25681211/7fc957de-3021-11e7-9fc7-d1ccadb791e3.png">

## AC
- Removing a tag before it's saved on serve doesn't create a browser error

**Comment by NickHeiner** [comment]
Ha, nice catch. Yes, hiding the `x` tag sounds like a good idea.

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
