### ISSUE TITLE
Documents List | Accessibility: remain focused

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1848]
**Story**
When tabbing through the documents list, I want to be able to select buttons on the page without the select order resetting to the top.

**Description**
Currently, everything that is a button resets to the top. Instead, it should remain focused on whatever I just selected. For example, if I tab to the filter icon and press enter, then press tab again, I should move to the next selectable element in the filter popup, not reset to the Caseflow Reader icon.

Look out for
- If you click and expand comment, skips "Jump to section" link and jumps to top
- If you click any filter icon, resets to the top

## AC
- [ ] Verify that everything that can be tabbed has a focus, and that the focus persists even if I select a button. 
- [ ] Verify that tabs go in this order:

**Navigation bar**
1. Caseflow reader link and icon
2. User dropdown

**Table header**
 3. search box
 4. search icon
 5. Expand all button
 6. Categories filter (and each selectable option in order)
 7. Receipt Date icon
 8. Document type icon
 9. Issue tag filter (and each selectable option in order)

**In the table** 
 10. Document type name
 11. Comment chevron (if applicable)
    - Jump to section if entered

## Dependent Story
#1847 -- Receipt Date and Doc Type should be buttons.

**Comment by mdbenjam** [comment]
This seems to work now. Moving to in validation

**Comment by kierachell** [comment]
**PASSED**

Seems to be working for all the cases listed above.
![keyboardallthethings](https://user-images.githubusercontent.com/18075411/27864969-beed18d8-615e-11e7-91e2-231414145348.gif)
