### ISSUE TITLE
Documents List | Accessibility: unread/read aria  label

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1849]
**Story**
When using a screen reader, I want to know which documents are read or unread.

## AC
- [ ] Add an aria label/description to opened or unopened documents
- [ ] Verify that with a screen reader, a document title that is bold is "unopened" and a document title that is regular (not bold) is "opened."

**Comment by mmlumba** [comment]
@abbyraskin shouldn't it be that a document title that is bold is unread and that a regular document title is read?

**Comment by abbyraskin** [comment]
Per our conversation, changed it to "unopened" and "opened" because the screen reader said "read" in the present tense, when the doc type ends in a number (in some ways opened/unopened is more accurate anyhow).

**Comment by kierachell** [comment]
### So the code is there
<img width="504" alt="screen shot 2017-06-25 at 8 56 13 pm" src="https://user-images.githubusercontent.com/18075411/27521269-dccc33a2-59e8-11e7-950a-a65b094bed67.png">

### But the screen reader is not recognizing it:

```
Document list 
row 1 column 1 column 2 Categories column 3 button Receipt Date column 4 button Document Type column 5 Issue Tags column 6 Comments 
row 2 column 1 Categories column 2 Receipt Date column 3 06/19/2017 Document Type column 4 link Form 8 Issue Tags column 5 Comments column 6 
row 3 column 1 Categories column 2 Receipt Date column 3 06/19/2017 Document Type column 4 link Form 8 Issue Tags column 5 Comments column 6 
row 4 column 1 Categories column 2 Receipt Date column 3 06/16/2017 Document Type column 4 link Form 8 Issue Tags column 5 Comments column 6 
row 5 column 1 Categories column 2 Receipt Date column 3 06/15/2017 Document Type column 4 link Form 8 Issue Tags column 5 Comments column 6
```

**Comment by mmlumba** [comment]
@kierachell which screen reader are you using for this?

**Comment by kierachell** [comment]
https://en.m.wikipedia.org/wiki/JAWS_(screen_reader) and I also have NVDA.

**Comment by abbyraskin** [comment]
@kierachell is this browser specific?

**Comment by NickHeiner** [comment]
Hmm. I wonder if those the screen readers are ignoring `aria-label` for `a` elements. If that's the case, I would not worry about this. I am curious what VoiceOver on macOS does.

**Comment by abbyraskin** [comment]
It works in VoiceOver.

**Comment by NickHeiner** [comment]
Ok, then I think we should close this issue and say we've satisfied it.

**Comment by NickHeiner** [comment]
I know that our users are not on Macs, but if we are creating accessible technology to the spec. If screen readers decide not to adhere to that spec, it gets into diminishing returns quickly for us to try to hack around it. Unless someone specifically complains that this is blocking them, I recommend closing this issue.

**Comment by abbyraskin** [comment]
@kierachell per conversation above + official decree from NTH2017, I'm closing this out (note that it works with Voiceover OSX and ChromeVox).
