### ISSUE TITLE
Document Viewer | Accessibility: add focus on toolbar buttons

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1851]
## Story
When tabbing through areas within a document, I want an indication that an element is in focus so I know where I am on the page.

## Description
Currently, the focus is set to 0 for buttons in the document toolbar, and the document 
itself lacks focus. We need a visual indicator for each button when tabbing through, and make sure the document itself, have focus.

- Document itself has focus (needs an attribute)
- All buttons need focus: back to documents, zoom, doc type, previous arrow, page number indicator, next arrow

## Acceptance Criteria
- When tabbing through the selectable areas on a document, the PDF toolbar buttons should change to a focused state
  - All buttons need focus: back to documents, zoom, doc type, download button, hide menu, left and right arrows
- Use the default focus from USWDS

## Mock up

Top
![image](https://cloud.githubusercontent.com/assets/13420618/26253757/6a70f140-3c82-11e7-9305-e719187f3b3c.png)
Bottom
![image](https://cloud.githubusercontent.com/assets/13420618/26259219/fcfe3ee2-3c95-11e7-91ea-6915e37394fc.png)

## Related
Top toolbar redesign #1996
Bottom toolbar redesign #2075

**Comment by abbyraskin** [comment]
@gnkm for the focus state, should we stick w/ the same blue as the hover state, or something else?

**Comment by gnakm** [comment]
I think the USWDS blue is good

![image](https://cloud.githubusercontent.com/assets/13420618/25752935/d115c214-3187-11e7-97ce-2c2de3db6bc1.png)

**Comment by gnakm** [comment]
@abbyraskin 
I just added in the AC. I think we should just stick with default focus from USWDS

**Comment by abbyraskin** [comment]
@gnakm is the focus for comment icons the same as the blue we use when selected? and what about for documents? the same highlight as "add comment" flow, or different?

**Comment by gnakm** [comment]
- The focus for comment icons were separately made, so those are SVGs. @NickHeiner Wondering if those SVGs still need a focus on top of the selected state? 
- The document has a different color. I didn't make it the USWDS color because it has a different opacity. 
- Add comment is USWDS

**Comment by NickHeiner** [comment]
> @NickHeiner Wondering if those SVGs still need a focus on top of the selected state?

I'm not sure what you're asking me.

**Comment by gnakm** [comment]
@NickHeiner I would like to take back the question that I asked because I answered it in my head.

**Comment by abbyraskin** [comment]
@gnakm i'm moving this back in to triage until we finalize headings/order

**Comment by abbyraskin** [comment]
Note: top toolbars are changing, see #1851

**Comment by kierachell** [comment]
**PASSED**
- Tabbed through all the bars in Chrome
- IE did not work for extraneous reasons.
![overlycompliant](https://user-images.githubusercontent.com/18075411/28327199-bf50cf2a-6bb0-11e7-9fdd-632bc77a48d4.gif)
<img width="1053" alt="screen shot 2017-07-18 at 12 01 49 pm" src="https://user-images.githubusercontent.com/18075411/28327266-e6ff3b2e-6bb0-11e7-89f7-9c892308b17e.png">
