### ISSUE TITLE
Document Viewer | Accessibility: adding comments from keyboard

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1852]
**Story**
As a user, I want to be able to add comments in the document viewer with a keyboard

## AC

The following AC are to be verified with Chrome, IE and Firefox on Macs and Windows machines:
- [x] Verify that Pressing Alt+C puts user in "add comment" state
- [x] Verify that when the user enters the "add comment" state, the comment icon appears in a page that is currently in view
- [x] Verify that if a user presses the arrow keys, they can move the comment before placing it.
- [x] Verify that comment is placed by entering alt+enter

**Comment by gnakm** [comment]
This was originally in the above comment but dropping here:
Adding a comment: alt+c to get into add comment state,  places it in center of doc, press space to enter it...alt+enter to save. Returns to focus on document.

**Comment by NickHeiner** [comment]
@abbyraskin @gnakm how about a hotkey for exiting annotation-leaving mode? `Esc` sounds good, but we should verify that that won't overlap with any existing browser functionality.

**Comment by NickHeiner** [comment]
This will be most easily done after #2121 is done.

**Comment by kierachell** [comment]
### Verify that comment is saved by entering alt+enter

On Mac, using Chrome:
I can start entering text after pressing `alt+enter` but I cannot Save comment

**Comment by abbyraskin** [comment]
@kierachell alt+enter is meant to place the comment. updated.

**Comment by kierachell** [comment]
**PASSED**

Verified in Chrome and Firefox.
IE - does not work
