### ISSUE TITLE
Document Viewer | Side Menu errors for comments

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1854]
As a user, I want to know when I cannot add a comment and still have the ability to save the text I typed in. 

Scenarios:
I tried saving a comment but there was a system error and I couldn't save
I tried editing a comment but there was a system error and I couldn't save
I tried deleting a comment but there was a system error and I couldn't save
I tried dragging and dropping a comment icon but there was a system error and I couldn't save

## AC 
- [ ] Verify that there is an error message above the comment box
- [ ] Verify that the comment box remains open with the text in the text box. User should be able to copy text from the box. 
- If a user clicks save, and the call fails, the text they entered remains in the box (essentially puts the user back in the open add comment state, rather than completely deleting their comment text)
- If the user successfully adds/edits/moves/deletes a comment, or navigates away from the page, the error message goes away

**Comments**
![image](https://cloud.githubusercontent.com/assets/13420618/25025753/6fd98aa2-2071-11e7-8693-64740eaee6c7.png)

**Comment by kierachell** [comment]
**PASSED**

checked adding/deleting/moving/editing/etc.
![failannotatte](https://cloud.githubusercontent.com/assets/18075411/26014085/30f33242-3729-11e7-8e2e-d1fa576d08bd.gif)

<img width="491" alt="screen shot 2017-05-12 at 3 40 00 pm" src="https://cloud.githubusercontent.com/assets/18075411/26014281/e0732b1e-3729-11e7-83f4-7789b9bd328e.png">

**Comment by NickHeiner** [comment]
lol I love that you have your certificate of completion as a test doc.
