### ISSUE TITLE
Add new CSS from Caseflow repo into commons

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#1863]
Since starting the style guide, it was agreed upon that new styles will be added to new/existing UI components first in the main Caseflow repo before being merged into commons. Many more components have been added in the Style Guide and the Caseflow apps since then, so now its time to go through all the style sheets and add all the reusable parts to commons.

**Comment by mmlumba** [comment]
Validation: compare screenshots of components from "before" state to what they currently look like in UAT

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated in: UAT
Browser: Chrome and FF

Validation: 
Before 
![styleguide5_9_17](https://cloud.githubusercontent.com/assets/23038505/25904578/a5d8cbf2-356d-11e7-8d4c-b56c50f4bf56.png)
<img width="785" alt="screen shot 2017-05-08 at 11 28 13 pm" src="https://cloud.githubusercontent.com/assets/23038505/25904600/b9aac2ca-356d-11e7-818f-36598ab4facb.png">



After
![sg_5_10_17](https://cloud.githubusercontent.com/assets/23038505/25904563/9d3b90e2-356d-11e7-8a37-3513a17fbc0e.png)
<img width="1433" alt="screen shot 2017-05-10 at 8 09 01 am" src="https://cloud.githubusercontent.com/assets/23038505/25904624/c4e2e834-356d-11e7-8b35-bf4379f4cb2e.png">
