### ISSUE TITLE
Certification: DB operation violates index_document_views_on_document_id_and_user_id constraint

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1865]
Sentry: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/180/

<img width="627" alt="screen shot 2017-05-04 at 1 03 32 pm" src="https://cloud.githubusercontent.com/assets/1053255/25715634/26fe6c62-30ca-11e7-9cee-dd602742649f.png">

**Comment by mdbenjam** [comment]
This is a Reader error. Putting the corresponding labels on it.

**Comment by mdbenjam** [comment]
We haven't seen this issue in 4 months. I'm closing as no longer relevant.
