### ISSUE TITLE
Dispatch: getting stale object error while establishing claim

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1866]
Sentry: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/162/

<img width="636" alt="screen shot 2017-05-04 at 1 07 45 pm" src="https://cloud.githubusercontent.com/assets/1053255/25715862/00c0794a-30cb-11e7-88bb-d99eee0f4792.png">

**Comment by joofsh** [comment]
I believe this has bene resolved. Closing
