### ISSUE TITLE
Redis | Isolate namespaces in test mode

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1867]
We currently don't isolate our namespaces which can result in tests affecting one another. For example in metric_service_spec we set a value in the request store that can be overwritten by another test when run in parallel.

When this is fixed reenable the skipped test and remove the :nocov: in metrics_service_spec.rb.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
