### ISSUE TITLE
Document Viewer | Issue tags textbox size 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1875]
When I type in super duper long issues, the text box expands

## AC
- [ ] Validate that the text box width is fixed to the default size
- [ ] Validate that when the issue text gets very long, the text falls on the next rows fits within the width of the text box width

## Mockups
_**Current**_
![stutter](https://cloud.githubusercontent.com/assets/18075411/25508170/3b9387d0-2b7e-11e7-84df-515a161b4564.gif)

_**Improved**_
![image](https://cloud.githubusercontent.com/assets/13420618/25725062/59fb442e-30ec-11e7-8525-8b12fa4deca6.png)

## Related Issue
#1767

**Comment by mogrenAtWork** [comment]
@gnakm as a user is typing a new tag, should the text they're typing break onto the next line as well (similar to your label example above) or continue on in a single line of text (example below)?
![](http://g.recordit.co/j23JPSQJdb.gif)

**Comment by kierachell** [comment]
**PASSED**
WOOHOO @mogrenAtWork from downtown with them bugfixes!
![taglongasf](https://user-images.githubusercontent.com/18075411/27254292-982965c6-5353-11e7-9b1e-20c0c84ca34b.gif)

**Comment by gnakm** [comment]
@mogrenAtWork I am so sorry that I missed this but what you did ^^ is beautiful. Thank you!

**Comment by mogrenAtWork** [comment]
No worries at all!
