### ISSUE TITLE
Comments | On the edge of a page can behave strangely

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1877]
Placing comments on the edge of a page can result on them hanging off the edge, and sometimes changing where the blue outline appears.

See Appeal: 1499662 on Preprod

![](https://cloud.githubusercontent.com/assets/18075411/25507548/aa975e08-2b7a-11e7-864f-ff4bef95edff.gif)

**Comment by abbyraskin** [comment]
Possible this was fixed -- need to investigate
