### ISSUE TITLE
Create integration with VACOLS for hearing data

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1881]
Create integration for retrieving hearings records from VACOLS.  Sync with Chris on translating the columns & values to human-friendly form

Technical Notes:
- `hearsched` table in VACOLS

**Comment by kierachell** [comment]
column names
```
 "HEARING_PKSEQ" "HEARING_TYPE"  "FOLDER_NR"     "HEARING_DATE"  "HEARING_DISP"  "BOARD_MEMBER"  "NOTES1"        "TEAM"          "ROOM"          "REP_STATE"     "MDUSER"   "MDTIME"        "REQDATE"       "CLSDATE"       "RECMED"        "CONSENT"       "CONRET"        "CONTAPES"      "TRANREQ"       "TRANSENT"      "WBTAPES"       "WBBACKUP"     
"WBSENT"        "RECPROB"       "TASKNO"        "ADDUSER"       "ADDTIME"       "AOD"           "HOLDDAYS"      "VDKEY"         "REPNAME"       "VDBVAPOC"      "VDROPOC"      
"CANCELDATE"    "ADDON"
```

**Comment by joofsh** [comment]
to QA:
- Check the `/app/models/vacols/case_hearing.rb` 
- Test using `VACOLS::CaseHearing.upcoming_for_judge()`, verify you get real results back. Note that because UAT has old data, you'll have to set the `date_diff` very high, I was testing with `7.years`

**Comment by kierachell** [comment]
@joofsh 
What date range to do you expect prod data to be? I will make a script to move it up in UAT to keep it proper
+ there's no PR for this :(

**Comment by joofsh** [comment]
@kierachell I think that's still in the air as a product requirement. My guess is we'll want to include hearings that were within the last  `7.days`, and then all future ones. 

What's the best way for me to document this? I just reverse engineered this from VACOLS documentation but I can definitely help you set up the right data for UAT testing

**Comment by kierachell** [comment]
@joofsh 
The best documentation is:
- What are the connecting keys? `STAFKEY` = `vacols_id` => `SATTYID` => `BOARD_MEMBER`
- What is the data that you are pulling and why (e.g. why does `HEARING_DISP` matter? )

**Comment by kierachell** [comment]
**PASSED**
```
irb(main):016:0> hears.first
=> #<HearingDocket:0x005603feb800a8 @date=Fri, 01 Jun 2018 00:00:00 EDT -04:00, @type=:video, @venue={:city=>"Hartford", :state=>"CT", :timezone=>"America/New_York"}, @hearings=[#<Hearing id: 1, user_id: 105, appeal_id: 2183, vacols_id: "367480">, #<Hearing id: 114, user_id: 105, appeal_id: 2296, vacols_id: "378595">], @user=#<User id: 95, station_id: "317", css_id: "CF_Q_317", full_name: "TEST ONE", email: "  caseflow@va.gov", roles: ["User", "System Admin", "Downl
oad eFolder"], vacols_id: "URPOWELL">>
```
