### ISSUE TITLE
Organize hearing records by Docket day

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1882]
On the backend, create a Docket model. Associate hearings with a Docket by their assigned date & judge.

Technical Notes:
- Dockets should be scoped to judge & date
- Should include a `to_hash` method for returning backend information to frontend

**Comment by joofsh** [comment]
To QA:
- On UAT, should be able to call `HearingDocket.upcoming_for_judge()` and get records back for a user with a properly set `vacols_id` (that of a real judge). On UAT I was using `RDPHILP`

**Comment by kierachell** [comment]
Can we have some documentation on the table joins so I can at least setup VACOLS data?
It seems like you look up STAFF by STAFKEY then join with HEARSCHED.BOARD_MEMBER on SATTYID? 

- How do our users get `vacols_id`? it's all `null` currently.
- Elsewhere `vacols_id` would refer to BFKEY?
- Why are hearing in their own repository folder away from AppealsRepository?

**Comment by kierachell** [comment]
**PASSED**
<img width="1252" alt="screen shot 2017-05-24 at 2 45 54 pm" src="https://cloud.githubusercontent.com/assets/18075411/26420178/db76c296-408f-11e7-973a-9873b0aa00a3.png">
