### ISSUE TITLE
Create Judge Schedule page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#1883]
- Create a new page at `/hearings/dockets` 

Technical Notes:
- Page should be created with React, follow example from Certification V2 for how to set up new page
- The route `/hearings/dockets` will already exist
- The ERB template in `/app/views/hearings/dockets` will already have the data populated
- `slot` and `start time` should be hardcoded for now. They will be updated in future tickets
- `VLJ: <name>` can be faked out for now

@astewarttistatech 
You can use CF_Q_317 user to access this page in UAT

Mock:
<img width="911" alt="screen shot 2017-05-10 at 4 30 47 pm" src="https://cloud.githubusercontent.com/assets/4975959/25919912/33884f92-359e-11e7-8506-bc26f2b3aac5.png">

**Comment by lakohl** [comment]
@slj I learned that Reader is using a stage that takes up 85% of the canvas. I would like to use that size for Hearing Prep as well. It's a bit wider than what we use in the rest of Caseflow, but the extra space will be very valuable for later pages of Hearing Prep which are crammed with info and need to be printable. Hearing Prep feeds into reader, so there we will also be preserving continuity in that transition.
@joofsh ^ for awareness

**Comment by kierachell** [comment]
@astewarttistatech 
You can use CF_Q_317 user to access this page in UAT

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access /hearings/dockets
2. Login with the indicated user

Screenshots: 
<img width="1033" alt="screen shot 2017-05-30 at 12 52 56 pm" src="https://cloud.githubusercontent.com/assets/23038505/26594859/5d13503e-4537-11e7-925f-1cf60ca8df0c.png">
