### ISSUE TITLE
Document Viewer | Ability to change page in document

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1884]
**Story**

As a user, I want the ability to skip to a specific page without having to scroll through the document. 

## AC
- Verify that there is box where a user can adjust the page number they want to be in 
- Verify that if a user enters a valid page number, then presses enter/return on keyboard, they are navigated to the page they specified
- Verify that if a user enters an invalid page number (one that does not exist in doc), when they press enter/return, they remain on the page they're currently viewing, and the # in the box reflects the page number they're currently viewing 

## Mock ups
![image](https://cloud.githubusercontent.com/assets/13420618/25753349/1f1b9bfe-3189-11e7-92d8-70979e664621.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26253953/0506e390-3c83-11e7-878b-1f5ffa1cd417.png)

**Comment by abbyraskin** [comment]
- We probably want to account for errors, e.g., if they enter a page that doesn't exist in the document

**Comment by abbyraskin** [comment]
This is changing based on toolbar redesign, new AC forthcoming

**Comment by abbyraskin** [comment]
@gnakm what happens if they enter an invalid #? e.g., it's a 10 page document and they enter 100.

I'm not sure how this is handled out of the box for the component we're using, but in Certification, if you are on page 10 (so you have a 10 in the box), if you change it to 100 (invalid) and press enter, it replaces the 100 with a 10. We could do something like this?

**Comment by NickHeiner** [comment]
This is blocked on #1984.

**Comment by gnakm** [comment]
@tejans24 We have a bug where the [bottom toolbar page and document numbers shift between documents](https://github.com/department-of-veterans-affairs/caseflow/issues/2230). Wonder if this issue will fix the problem.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access reader
2. Access a document with over 4 pages
3. View the pages of the document in a 2-page view. 
4. Enter in random unsequential numbers into the bottom toolbar for pages. 
5. Validate that the pages change based on the numbers entered and that they don't shift randomly. 

Screenshots: 
![readerpageview](https://user-images.githubusercontent.com/23038505/26933976-0fab4f26-4c36-11e7-81bd-b199ea77f3e6.gif)
