### ISSUE TITLE
Prepare Tasks Job | Checking for `nil` disposition or changes to issues before assigning task

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1886]
Currently we are not checking for `nil` disposition for prepared tasks after the job runs:
from prod:
```
Appeal.where(vacols_id: "3469911").first.decision_type => nil
```

So it causes errors in some cases and blocks users from progressing.

## Sentry:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/190/

## Reasons
It is also possible for issues to change between the time of task preparation and Dispatch workers getting to it:
```
   ISSKEY ISSSEQ ISSDC ISSDESC ISSPROG ISSCODE ISSLEV1 ISSLEV2 ISSLEV3 ISSPROG_LABEL      ISSCODE_LABEL    ISSLEV1_LABEL                                                    ISSLEV2_LABEL
1 3469911      1     4    <NA>      02      15      03    7319    <NA>  Compensation Service connection       All Others Irritable colon syndrome (spastic colitis, mucous colitis, etc.)
2 3469911      2     1    <NA>      02      15      04    7319    <NA>  Compensation Service connection New and material Irritable colon syndrome (spastic colitis, mucous colitis, etc.)
```
We do not handle that either. There's no way to check the date of the change of the issues, but maybe we should validate the cache before serving the data.

## Related Issues
https://github.com/department-of-veterans-affairs/appeals-support/issues/147

**Comment by joofsh** [comment]
It seems as though the issues related to this appeal were changed after being pulled into Dispatch. Based on the issues, it should never have reached Caseflow Dispatch (no non-N&M issues were granted).

We should check for this when invalidating tasks

**Comment by joofsh** [comment]
@kierachell so now when you go to assign a task without a decision_type, it will invalidate it and assign you the next one

**Comment by kierachell** [comment]
**PASSED**
Ran the job a few times, change the dispositions, didn't get errors
