### ISSUE TITLE
SOC and SSOC dates should use fuzzy date matching to check if documents match [5]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1889]
Interviews with the Honolulu ROs have uncovered a problem that results in low Caseflow usage there. Basically, due to circumstances out of their control, the VBMS date is very often 1-3 days before the VACOLS date.

Additionally, we should pass the VBMS date down to the client from the server. This will require saving those dates in the DB, so we'll need to run a data migration.

See https://github.com/department-of-veterans-affairs/caseflow/issues/1732 for more context.

## Acceptance criteria
- If the VACOLS date for the SOC or any of the SSOC's are up to 4 days after the VBMS date for a document with the matching type, it should allow the certification to continue.
- On the Check Documents page, when documents are matching, the proper VBMS and VACOLS date should be displayed. Even when they are different.
- The success message on the documents matching page should read:
    **Header**: Matching documents found in VBMS for all VACOLS documents.
    **Body**: A VBMS document date is considered matching if it's within 4 days before the VACOLS date.

## Mocks
![check docs - all docs found](https://cloud.githubusercontent.com/assets/1178390/25909388/04f3bd88-357b-11e7-9564-e57b464dcbc5.png)

## Testing Notes
Here's the code that sets the dates from VACOLS
```
      notification_date: normalize_vacols_date(case_record.bfdrodec),
      nod_date: normalize_vacols_date(case_record.bfdnod),
      soc_date: normalize_vacols_date(case_record.bfdsoc),
      form9_date: normalize_vacols_date(case_record.bfd19),
      ssoc_dates: ssoc_dates_from(case_record),

```

**Comment by shanear** [comment]
@laurjpeterson @shellicious lets talk about whether we should release this for just V2, or V1 and V2.

I'm leaning towards V1 and V2 because:
- This is an annoyance for a lot of RO's and it'd be nice to fix it ASAP
- It's more difficult to just change it for V2

**Comment by shellicious** [comment]
@shanear i'm also into releasing this for V1 before V2. We may need to get AMO to sign off on it, since I'm not sure what The Manual has to say about how closely dates need to match.

**Comment by shellicious** [comment]
Mocks of the new Check Documents page for a world with fuzzy date matching / an excuse to make the content on this page more clear:

**What's changed for a Check Documents page with errors:**
- Content in error message is more specific
- Table heading for the icons is more specific
- If no date is found, text says "Not found" under "VBMS date"
- Instructions for document date include an explanation of the fuzzy date match

**Open questions:**
- Should we point out that a VBMS date is too far from the VACOLS date, like in the second mock below?

![check docs - mismatched](https://cloud.githubusercontent.com/assets/1178390/25826716/d7cbeb52-3415-11e7-94ed-76b96a906ddf.png)

With some more text pointing out the date that is too far off to match:

![screen shot 2017-05-08 at 5 49 18 pm](https://cloud.githubusercontent.com/assets/1178390/25826901/b24d6e18-3416-11e7-90c5-71de1455a14b.png)

**What's changed for Check Documents sans errors:**
- Content in success message is more specific

![check docs - all docs found](https://cloud.githubusercontent.com/assets/1178390/25826936/d911a168-3416-11e7-82bc-61dc9463df20.png)

Would love your thoughts on content and the open question, @nicholasholtz @cmgiven @amprokop @laurjpeterson @shanear!

@shanear @laurjpeterson and I are meeting about this from 2:30-3PM EST tomorrow, Tuesday 5/9

**Comment by cmgiven** [comment]
Note that we need it to be up to four days, as it might be a three day weekend.

On the open question, I see where you're coming from in wanting to draw attention to the thing that needs correcting, but I'm not sure this does that. Maybe it even does the opposite, by surrounding it with additional text?

**Comment by nicholasholtz** [comment]
A thought - what if the "(Mismatch)" was to the right of the date? @cmgiven, would that change your opinion? 

Chris's point on 4 days makes sense.

**Comment by shellicious** [comment]
Thanks for feedback, working on another round of designs today

**Comment by shellicious** [comment]
Revisions!

What's changed:
- Changed text to 4 business days
- Less text in the error message so RO staff attention is focused on the specific document error
- Created a "status" column next to the "VBMS date" column that describes the exact problem. 
- Styled error text in "status" column to focus attention there.

Potential problem states to be aware  of:
- Document not found in VBMS
- Document is labeled correctly and found in VBMS, but VBMS date is more than 4 biz days from VACOLS date

![check docs - mismatched option 1](https://cloud.githubusercontent.com/assets/1178390/25865834/58951aea-34c2-11e7-8699-d4eaebf16670.png)

![check docs - all docs found option 1](https://cloud.githubusercontent.com/assets/1178390/25865836/59d888a6-34c2-11e7-886a-3d3a9498c004.png)

**Comment by cmgiven** [comment]
Ooh, that looks good! "Date out of range" feels a bit wonky. Would "Dates do not match" work?

**Comment by amprokop** [comment]
Looks great!

Re: `All documents found in VBMS with valid dates.`

Could this be more precise? 
Maybe—
header:`Matching documents found in VBMS for all VACOLS documents.`
more text:`A VBMS document date is considered matching if it's within 3 business days of the VACOLS date.`

**Comment by shellicious** [comment]
Updated mocks below, to reflect yesterday's conversation with @laurjpeterson and @shanear, where we concluded that we'll open another issue to discuss/define the content in the "Status" column. There are some edge cases we didn't realize existed to accommodate.

Once we decide on # of days, let's adhere to these mocks. I've made minor content changes to the heading of the first column in the table, the error message, and the instructions below. Feel free to modify the # of days depending on the outcome of the conversation in #1732.

Designers have access to my sketch files and can make the edits while I'm out.

![check docs - mismatched](https://cloud.githubusercontent.com/assets/1178390/25909389/04f6e850-357b-11e7-98bb-5dcb6a449023.png)

![check docs - all docs found](https://cloud.githubusercontent.com/assets/1178390/25909388/04f3bd88-357b-11e7-9564-e57b464dcbc5.png)

**Comment by laurjpeterson** [comment]
@amprokop based on conversations on the other fuzzy date issue ( #1732), we're moving forward with SOCs and SSOCs with VBMS dates 0-4 days before VACOLS dates. We could extend to NODs and Form 9s, but at a later time with more input and buy in.

Since the title of this issue includes Form 9s and NODs, confirming that the scope of this ticket and change you made is just for SOCs and SSOCs.

**Comment by shanear** [comment]
Changing AC to match the conversation.

## Old AC
    If the VACOLS date for NOD, SOC, any SSOCs, or the Form9 is 1-3 days after the VBMS date for NOD
        The success page should show up when visiting /certifications/new/ID
        The user should be able to certify the appeal
        The non-matching dates should both be displayed in the table.
        Some explanatory text should appear explaining (TBD by @shellicious)
    If the VACOLS date for SOC or SSOC is 4+ day after the VBMS date for SSOC, the user should see the "documents not matching" page and should not be able to certify the appeal.
    If the documents all match dates exactly, no explanatory text should appear

**Comment by astewarttistatech** [comment]
**FAILED**

Steps to Reproduce: 
1. Change dates of documents to 4 days earlier than the VACOLS date
![changingdates](https://cloud.githubusercontent.com/assets/23038505/26206653/6ba9656c-3bb3-11e7-8cf5-1232ff7769fe.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Certification V2 for a veteran who has all documents
2. Go into VBMS for that veteran in that environment
3. Locate the needed SOC and SSOCs and change the date to be 4 days before the VACOLS date for the document found on the certification check documents page. 
4. Reload the check documents page in Certification V2. 
5. Validate that all the SSOC and SOCs are still valid in order to continue certifying the appeal. 

Screenshot: 

**P.S. Please do not pay attention to the second SSOC, that one was uploaded in error. 
<img width="1260" alt="screen shot 2017-05-19 at 9 48 26 am" src="https://cloud.githubusercontent.com/assets/23038505/26250598/8d4d24ae-3c78-11e7-8558-9487f2d5e979.png">

**Comment by kierachell** [comment]
## If SSOC dates in VACOLS are within the fuzzy time and there's _one_ SSOC document in VBMS then it matches to both VACOLS dates?
<img width="951" alt="screen shot 2017-05-31 at 8 32 18 pm" src="https://cloud.githubusercontent.com/assets/18075411/26659668/552e69f8-4640-11e7-8ebc-9d4104800b1b.png">


<img width="809" alt="screen shot 2017-05-31 at 8 27 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/26659674/618c7fb4-4640-11e7-99a0-0027f62e1725.png">

**Comment by amprokop** [comment]
Great testing. In practice, I think this should be an edgy edge case, since it should only affect SSOCs where there are multiple released in a <4 day period.

**Comment by amprokop** [comment]
My impression is that which SSOC slot a document is in (SSOC1-5) doesn't have any significance really — they're just arbitrary buckets to put SSOCs in, it doesn't matter where an SSOC is. @cmgiven, can you confirm this?

**Comment by cmgiven** [comment]
That's correct. They are separate fields in the VACOLS interface, but for our purposes, there's no difference.

**Comment by amprokop** [comment]
I have opened https://github.com/department-of-veterans-affairs/caseflow/issues/2236 to track the edgy edge case, though it's low priority. @kierachell can you revalidate?

**Comment by kierachell** [comment]
**PASSED**
Edge case captured in #2236
