### ISSUE TITLE
[1] Ensure that static fields on Sign And Certify page are prefilled from server data, and are not user-modifiable.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1891]
The "Name and location of certifying office:", "Organizational elements certifying appeal", and "Date" fields should all be prepopulated from server data, should be visibly disabled, and should not be user-modifiable. They should not be included in the update request to the Rails server, and should not be whitelisted as params from the Rails server.

These fields should appear like the disabled Dispatch fields:
![image](https://cloud.githubusercontent.com/assets/3781835/25817083/3ea610f4-33f4-11e7-8b10-82cb2598e44b.png)

### Acceptance criteria ###
- The fields mentioned above are prepopulated from server data (look in certification.to_hash)
- The fields mentioned above are not modifiable from the Sign And Certify page

**Comment by amprokop** [comment]
Assigning to @shellicious to verify and add comments on what disabled fields should appear like.

**Comment by kierachell** [comment]
So this caused the `prod` issue with Date field and there has been no directive to change the formatting;

@amprokop how _exactly_ should the date be formatted?
- old
<img width="553" alt="screen shot 2017-06-01 at 3 45 27 pm" src="https://cloud.githubusercontent.com/assets/18075411/26707410/a8e26810-4712-11e7-9638-af5af83d3d9d.png">

<img width="1137" alt="screen shot 2017-06-01 at 3 45 56 pm" src="https://cloud.githubusercontent.com/assets/18075411/26707411/a8e2b98c-4712-11e7-8b8d-514056ce3735.png">

- new??
<img width="603" alt="screen shot 2017-06-01 at 9 37 16 pm" src="https://cloud.githubusercontent.com/assets/18075411/26707412/a8e33646-4712-11e7-9b17-c5a9c271ebff.png">

**Comment by amprokop** [comment]
@kierachell — plz revalidate? https://github.com/department-of-veterans-affairs/caseflow/pull/2205 should have fixed this

**Comment by kierachell** [comment]
## The date format is still "new":
<img width="562" alt="screen shot 2017-06-06 at 9 26 52 am" src="https://cloud.githubusercontent.com/assets/18075411/26831449/52f45284-4a9a-11e7-8dd0-6d08170a23fb.png">

**Comment by kierachell** [comment]
**PASSED**
We're back in business, baby!
<img width="616" alt="screen shot 2017-06-08 at 2 26 39 pm" src="https://user-images.githubusercontent.com/18075411/26944568-17d76f24-4c57-11e7-9635-e4fd6edcee74.png">
