### ISSUE TITLE
[1] Prevent the user from skipping past the documents check page by manually entering a URL

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1892]
Right now, it's possible to bypass the documents check page. For example, if you're on local dev and go to `certifications/new/456C`, you see the mismatched documents page, but you can still manually navigate to `certifications/456C/confirm_case_details` and continue to certification.

On every page load, we should check if the certification status is not `:started`, and redirect to documents check if not.

Acceptance criteria:
- For appeals that are not ready to certify, are already certified, or that have mismatched documents, if the user navigates to `/certifications/id/confirm_case_details` (or any URL later in the flow), the user should be redirected to the documents check page.

**Comment by kierachell** [comment]
**PASSED**
![skipme](https://cloud.githubusercontent.com/assets/18075411/26739363/82c4f3b8-479f-11e7-9ab2-00f968fa7b1a.gif)
![skiptest](https://cloud.githubusercontent.com/assets/18075411/26739364/82c709f0-479f-11e7-9a00-099e4ba71407.gif)
