### ISSUE TITLE
Add stats page stats for certification v2

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1897]
As stewards of Certification, we'd like to create a temporary  V2  stats page so we can easily track our new changes.

Initial stats for the stats page:
- V2 certifications started
- V2 certifications completed
- V2 certifications completed in the same period
- V2 time to certify (will most likely go up)
- V2 median time to certify

This will be a temporary page that we'll remove once V2 fully rolls out. Make a TODO issue to remove it as well.

**Comment by cmgiven** [comment]
I like the idea of separating V1 and V2 stats while in transition. I think that goes away once we've fully converted, though.

What do you hope to learn from the number with fuzzy date matches?

**Comment by amprokop** [comment]
Yep, definitely goes away once we're fully converted.

**Comment by amprokop** [comment]
With the fuzzy date match # — I'd like to get a general sense of how big of a problem it was for ROs.

**Comment by laurjpeterson** [comment]
I like seeing fuzzy date match # as well - can we separate these out by RO to see if it affects all time zones?

**Comment by cmgiven** [comment]
I think we're reaching the point where we should address this through a separate report, like the utilization report. There's value in keeping these dashboards simple.

**Comment by amprokop** [comment]
Hmm. Is the utilization report updated in real-time? How often are these things generated? And who are the most common users of the stats page? I've only looked at it 3 or 4 times in 6 or 7 months myself, so I don't really know.

**Comment by cmgiven** [comment]
Currently it's just internal to the team. Goal is to be able to quickly diagnose yes, the tool continues to be used, and there aren't any weird issues that have suddenly sprung up (i.e. we're suddenly missing a lot more documents). The reports are periodic, updated as needed, and intended to dive deeper in a specific area of inquiry. The utilization report is updated monthly (or as I get pinged to please refresh it).

**Comment by amprokop** [comment]
The Given comments above seem like an argument **for** adding these live stats. @shellicious and @laurjpeterson especially might want to be able to monitor certification v2 usage when we start rolling out to whole groups of users that we aren't personally talking to. It's not a large engineering task to do so — we basically just have to copy over the metrics that already exist in `certification_stats.rb` and add an additional condition to the queries there.

However, keeping the stats page simple is a good goal too — so let's just create a separate, temporary V2 stats page instead of grafting on to the old one.

**Comment by nemodjuric** [comment]
The difference between v1 and v2 fields once certification is loaded comes from fetch_power_of_attorney! method which includes bgs and vacols rep name, type and address fields

However,  there are cases when bgs record may be empty. This would bring v2 in the same position as v1 and no way to tell the difference. 
If we exclude certification started stat (including the very first step), there are some other fields (i.e. poaMatches that gets set at the second step) that v2 has but v1 does not.

So, it's either going without certifications started stat or introducing a new field that will distinction v1 and v2

@amprokop

**Comment by nemodjuric** [comment]
Wrote https://github.com/department-of-veterans-affairs/caseflow-commons/issues/101

**Comment by kierachell** [comment]
**PASSED**

<img width="712" alt="screen shot 2017-06-23 at 2 02 41 pm" src="https://user-images.githubusercontent.com/18075411/27494625-be47fe66-581c-11e7-84b3-114e8afebafb.png">
