### ISSUE TITLE
Filter Component | Set overflow-y and max-width

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1898]
The current filter dropdown component has a scrollbar when it's unnecessary. We should set the overflow-y and max-width to prevent this.

![image](https://cloud.githubusercontent.com/assets/3885236/25766352/173c4f5a-31c0-11e7-9b23-7b90afe53a08.png)

## AC
1. Filter dropdown component shouldn't have a horizontal scrollbar
1. Filter dropdown component should have a maximum width of 218px

## Related issue
#1438

**Comment by mdbenjam** [comment]
@gnakm Could you fill in the maximum width?

**Comment by gnakm** [comment]
@mdbenjam Added above!

**Comment by kierachell** [comment]
**PASSED**
<img width="569" alt="screen shot 2017-05-22 at 11 23 13 am" src="https://cloud.githubusercontent.com/assets/18075411/26316071/12f76b22-3ee1-11e7-847b-0bd7f01a80bf.png">
<img width="572" alt="screen shot 2017-05-22 at 11 23 50 am" src="https://cloud.githubusercontent.com/assets/18075411/26316102/2bd1476c-3ee1-11e7-85cb-99b723255123.png">
