### ISSUE TITLE
List View | Scroll to last read document on < Back to All Documents

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#1899]
A recent change made the < Back to all documents button no longer scroll to the most recently opened document. It is likely due to the change that made the table scrollable.

## AC
1. Verify when a user hits `< Back to all documents` they should return to the same scroll position they were in when they opened the document from the doc list, with the last read document indicator in view.
1. Verify that if a user opens a document, then navigates to a document before/beyond the last scroll position in the documents list view, then selects  `< Back to all documents`, the last read document (and indicator) is scrolled to the top of the list (see screenshot below)
1. Verify there is a robust feature test that avoids future regressions.
![image](https://cloud.githubusercontent.com/assets/4042181/26009508/24ce2cfe-3717-11e7-9bf3-8951758d8565.png)

**Comment by astewarttistatech** [comment]
Its wonky, because if you sit after the page scrolls to the last read (say it's at the bottom) it wil scroll to the top a few seconds after.  watch the last seconds. @NickHeiner 
![readerlastread](https://cloud.githubusercontent.com/assets/23038505/25954057/23ce1aec-3633-11e7-9120-f2bcda9cdee1.gif)

**Comment by NickHeiner** [comment]
@astewarttistatech I am not able to repro this. Are you at BVA on May 12th? Can you show me in person then?

**Comment by kierachell** [comment]
Seems like when switching documents around it will take you to last view, not last visited document.:

![lastreadswitch](https://cloud.githubusercontent.com/assets/18075411/26006561/e7e80316-370a-11e7-9d23-2dbf5d64ccc5.gif)

**Comment by abbyraskin** [comment]
@NickHeiner I added some clarifying AC for the scenario where a user navigates to a document beyond the last saved scroll position. in this case (and only this case), we'll scroll the last read doc to the top of the list.

**Comment by kierachell** [comment]
**PASSED**
AYYY!
![lastread](https://cloud.githubusercontent.com/assets/18075411/26086203/477b3ac4-39b7-11e7-949e-37a026fac466.gif)
