### ISSUE TITLE
collect screenshots of error pages

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#190]
I would like to take a look at the copy and style on each of the following pages and create mocks to port them over to the new design style.

- [x] 404.html
- [x] certify.html
- [x] error.html
- [x] not_found.html
- [x] not_ready.html
- [x] unauthorized.html
- [ ] vbms_failure.html

**Comment by alex** [comment]
`not_found.html`:
<img width="1472" alt="screen shot 2015-11-18 at 11 56 15 am" src="https://cloud.githubusercontent.com/assets/772/11247829/c8f2107e-8deb-11e5-9096-81d4e0dca471.png">

`not_ready.html`:
<img width="1472" alt="screen shot 2015-11-18 at 11 56 24 am" src="https://cloud.githubusercontent.com/assets/772/11247831/c8f4d3f4-8deb-11e5-9ed9-1f27cbea3b31.png">

`unauthorized.html`:
<img width="1472" alt="screen shot 2015-11-18 at 11 56 51 am" src="https://cloud.githubusercontent.com/assets/772/11247830/c8f24fa8-8deb-11e5-8000-399d583abc37.png">

**Comment by alex** [comment]
`certify.html`
![Uploading Screen Shot 2015-11-18 at 12.01.09 PM.png…]()

**Comment by alex** [comment]
`certify.html`
<img width="1472" alt="screen shot 2015-11-18 at 12 01 09 pm" src="https://cloud.githubusercontent.com/assets/772/11247908/25b21a16-8dec-11e5-80fb-c788696f4265.png">

**Comment by alex** [comment]
`404.html`:
<img width="1472" alt="screen shot 2015-11-18 at 12 15 58 pm" src="https://cloud.githubusercontent.com/assets/772/11248249/282693c4-8dee-11e5-80f7-17189812b52a.png">

**Comment by alex** [comment]
`error.html`:
<img width="1472" alt="screen shot 2015-11-18 at 12 17 09 pm" src="https://cloud.githubusercontent.com/assets/772/11248279/4e012596-8dee-11e5-9b00-082cedda3f2a.png">

**Comment by webinista** [comment]
Blocks #190, #192,  #251, #253, #254,

**Comment by KHarshawat** [comment]
@alex How would a user get to a 404 page? I'm trying to determine if we need to make the message more general than talking about appeals (`no appeal aselected` vs `The page you're looking for does not exist`)

**Comment by alex** [comment]
Manually futzing with the URL is the only way at present.

On Fri, Dec 18, 2015 at 10:39 AM, Kavi Harshawat <notifications@github.com>
wrote:

> @alex <https://github.com/alex> How would a user get to a 404 page? I'm
> trying to determine if we need to make the message more general than
> talking about appeals (no appeal aselected vs The page you're looking for
> does not exist)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/190#issuecomment-165809612>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by KHarshawat** [comment]
@maryannbrody can you do a copy edit for these various error messages and I'll throw them into mocks?

**Case not found**
*There is no case in VACOLS with the ID you provided.*
Try opening another appeal in VACOLS.

**Case not ready!**
*This case is not ready for certification yet.*
Try opening another appeal in VACOLS.

**Unauthorized**
*It looks like this appeal is not within your Regional Office’s jurisdiction.*
Double check the appeal’s jurisdiction or try opening another appeal in VACOLS.

**Page not found**
*Oops! It looks like the page you're looking for does not exist*
You might want to double check the URL for errors.

**Comment by maryannbrody** [comment]
Hi @KHarshawat, 

Just one change - added to "case not found"

**Case not found**
*There is no case in VACOLS with the ID you provided.*
Check the ID number again or try opening another appeal in VACOLS.

**Comment by KHarshawat** [comment]
@webinista here are updated mocks!

![404](https://cloud.githubusercontent.com/assets/6335546/11909988/10972404-a5a3-11e5-8987-f07a9b0a1241.png)
![case not found](https://cloud.githubusercontent.com/assets/6335546/11909990/109ba65a-a5a3-11e5-8696-bb0873e4ba5b.png)
![case not ready](https://cloud.githubusercontent.com/assets/6335546/11909991/109c5f78-a5a3-11e5-88b7-f3b83fd54346.png)
![unauthorized](https://cloud.githubusercontent.com/assets/6335546/11909989/1098e9e2-a5a3-11e5-8811-897d6b9e2c50.png)

**Comment by webinista** [comment]
Pretty sure we've captured all of these and redesigned them.
