### ISSUE TITLE
Error message | Wrong VACOLS ID

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1903]
As a user, I want to know if I entered the wrong VACOLS ID and be alerted a message that will give context to what I should do next. 

## AC
- [ ] Verify that this error comes up when the wrong VACOLS ID is entered
- [ ] Verify that it has the new copy (see below)
- [ ] Verify that it follows the [status message style guide component ](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/StyleGuide/StyleGuideStatusMessages.jsx)

Current
![image](https://cloud.githubusercontent.com/assets/13420618/25810661/c33baa06-33de-11e7-9ebf-1ea1a718313c.png)

New
![image](https://cloud.githubusercontent.com/assets/13420618/25812322/eb28e574-33e3-11e7-8fb3-e5bf14d8760a.png)

## Copy

Case not found

Oops! It looks like the VACOLS ID you have entered does not exist. 
Please check the URL was typed correctly or try again.

**Comment by abbyraskin** [comment]
closing this out because this will no longer be an issue when we have the welcome gate
