### ISSUE TITLE
Error Message | Document does not exist

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1905]
As a user, I want to be alerted when a document I am looking for does not exist.

## AC
- [ ] Verify that this error comes up when user clicks on a document that does not exist
- [ ] Verify that it has the new copy (see below)
- [ ] Verify that document list in the copy is a text link to the case document list page
- [ ] Verify that it follows the [status message style guide component ](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/StyleGuide/StyleGuideStatusMessages.jsx)

Current
![image](https://cloud.githubusercontent.com/assets/13420618/25811797/6687e79e-33e2-11e7-87a6-5ca848decc14.png)

New
![image](https://cloud.githubusercontent.com/assets/13420618/25812116/520239d6-33e3-11e7-9599-df9384158ea5.png)

## Copy

Document not found

Oops! It looks like the document you're looking for does not exist. 
Please check the URL was typed correctly or go back to the document list.

**Comment by abbyraskin** [comment]
I'm closing this out, as we're changing the way people access cases. May want to reevaluate a version of this messaging when we've implemented search in the "welcome gate."
