### ISSUE TITLE
Style guide component | Searchable dropdown double scroll bug

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1907]
Description
The searchable scroll bar in style guide has two scroll bars! It's buggin out!

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/25813898/51e7c154-33e9-11e7-9be3-8c71b7a8af49.png)

## AC
- [ ] Verify that there is only one scroll bar in the searchable dropdown

**Comment by gnakm** [comment]
/cc: @amprokop @tejans24 Not sure if I should assign this to whiskey or foxtrot.

**Comment by gnakm** [comment]
@tejans24 Sounds like this was already done? Can you confirm and close please 😁

**Comment by tejans24** [comment]
#1976 fixes this issue

**Comment by kierachell** [comment]
**PASSED**

<img width="594" alt="screen shot 2017-05-15 at 11 55 02 am" src="https://cloud.githubusercontent.com/assets/18075411/26066603/6bbccd96-3965-11e7-8ce5-d365877f2d56.png">

<img width="547" alt="screen shot 2017-05-15 at 11 55 15 am" src="https://cloud.githubusercontent.com/assets/18075411/26066590/63958e28-3965-11e7-8919-307be4009733.png">

<img width="727" alt="screen shot 2017-05-15 at 11 59 48 am" src="https://cloud.githubusercontent.com/assets/18075411/26066768/02f1e3b8-3966-11e7-86b3-b34fe6bc4653.png">

**Comment by amprokop** [comment]
Ay! Nice
