### ISSUE TITLE
Cancellation Modal | Cleanup: Remaining Character text, Button alignment

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1908]
# Description
1. Right now, the character limit appears when text in being typed in the box. This is causing a clutter in space with the text field immediately below it. For best practices, it is better to have the 2000 character limit text from the start. 

2. Placement of Cancel certification button is not aligned with cancel text link

## Reproduction Steps

**Scenario 1 -**

1. Go to Certification
1. Try to Cancel it
1. Select Other in the modal
1. Type some stuff
1. Look at ugly

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [NEED MOAR SPACE]_**

<img width="465" alt="screen shot 2017-05-08 at 12 25 08 pm" src="https://cloud.githubusercontent.com/assets/18075411/25814061/fefb1ca6-33e9-11e7-8e0a-83fba15716ac.png">

**_Improved_**

![image](https://cloud.githubusercontent.com/assets/13420618/25815254/fd39b20c-33ed-11e7-8d8e-1884d402dcc8.png)

## Related issue
Coming up in style guide #1411

**Comment by gnakm** [comment]
@shellicious for your awareness -- @kierachell originally made this issue and I edited it to fit style guide. Basically right now characters remaining come ups once a user starts typing. This causes weird spacing issues. I think it's better if we have the 2000 character limit text to begin with that way it's not as jarring for users and we won't have to worry about spacing. I also have a style guide issue for it.

**Comment by amprokop** [comment]
Hold on this until next sprint, when hopefully the style guide team will have fixed it.

**Comment by slj** [comment]
The button mis-alignment is problematic on other certification pages besides the modal.  For example, Form 8:

<img width="461" alt="screen shot 2017-05-08 at 5 11 23 pm" src="https://cloud.githubusercontent.com/assets/1053255/25830290/db13eecc-3429-11e7-8032-ef9019fd5798.png">
