### ISSUE TITLE
[2] Add Redux logger in Certification V2 for easy debugging

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1909]
Link up with JD or Mark or Teja about what Redux logger does (prints the state to the console) and enable it only for local development (demo and UAT too if that's easy, but not prod!)

**Comment by kierachell** [comment]
From Dispatch:
<img width="1420" alt="screen shot 2017-05-08 at 1 13 09 pm" src="https://cloud.githubusercontent.com/assets/18075411/25815848/2cbd383a-33f0-11e7-94b2-ffc3c722df0b.png">

**Comment by kierachell** [comment]
**PASSED**
Superfun!
<img width="862" alt="screen shot 2017-05-13 at 3 31 42 pm" src="https://cloud.githubusercontent.com/assets/18075411/26028577/9ec6d346-37f1-11e7-9c39-22ab75496bfa.png">
<img width="838" alt="screen shot 2017-05-13 at 3 33 01 pm" src="https://cloud.githubusercontent.com/assets/18075411/26028576/9ec65c4a-37f1-11e7-81e2-99752b254a6c.png">
<img width="266" alt="screen shot 2017-05-13 at 3 33 22 pm" src="https://cloud.githubusercontent.com/assets/18075411/26028578/9eca5bce-37f1-11e7-996f-92a4d1e2e15e.png">
