### ISSUE TITLE
Investigate CPU spikes on Caseflow

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1917]
Every 30min or so, we have a pretty significant spike on Caseflow load. This sometimes triggers some latency PagerDuty alarms, so it'd be nice to know why it's happening.

Screenshot of the spikes from Graphana
<img width="718" alt="screen shot 2017-02-16 at 9 11 00 am" src="https://cloud.githubusercontent.com/assets/1596259/23024374/ff6505aa-f427-11e6-969c-350114564241.png">

Note: this report is months old, let's start by validating that it's still happening.

**Comment by shanear** [comment]
Didn't find any immediate reason, and we amped up the horsepower to deal with this issue. Moving back to ready for dev

**Comment by laurjpeterson** [comment]
This is from very long ago! Closing.
