### ISSUE TITLE
Design "This case has not been certified!" error page 

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#192]
Get to that page by clicking _This case cannot be certified_ button from the start page.

**Comment by KHarshawat** [comment]
![not-certified](https://cloud.githubusercontent.com/assets/6335546/11580958/c359afde-9a0a-11e5-860a-cc800450f77f.png)

**Comment by KHarshawat** [comment]
@webinista I believe this is in already yes? If so, can you close the issue?
