### ISSUE TITLE
Style guide component | Radio button fieldset enhancement

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1924]
**Description**
For form fields, we want to make sure that all form fields have a 40px space between each component. This is not to be confused with spacing between each radio button -- those are great!

## AC
- Verify that the `fieldset` has `margin-bottom` of 40px below it

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the living style guide
2. Navigate to the Radio buttons section
3. Check the spacing between each EXAMPLE of radio buttons, not the individual buttons themselves. 

Screenshots: 
![fieldsetradio](https://user-images.githubusercontent.com/23038505/27341447-48da33a6-55ab-11e7-97ef-7420002cc0c6.gif)
