### ISSUE TITLE
Style guide component | Checkbox fieldset enhancement

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1925]
**Description**
For form fields, we want to make sure that all form fields have a 40px space between each component. This is not to be confused with spacing between each radio button -- those are great!

## AC
- Verify that the `fieldset` has `margin-bottom` of 40px below it

**Comment by astewarttistatech** [comment]
First 2 checkboxes couldn't be verified. @Sjones352 Any suggestions on how to verify this in UAT?

See below: 
![fieldsetcheckboxes](https://user-images.githubusercontent.com/23038505/27341597-bc7c4c7c-55ab-11e7-94b0-ee329a8762c1.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access style guide 
2. Navigate to checkbox section 
3. Verify that each example is 40 px apart according to AC

Screenshots: 
see above as well as 
<img width="1300" alt="screen shot 2017-06-21 at 9 11 23 am" src="https://user-images.githubusercontent.com/23038505/27385871-0024e36a-5662-11e7-9540-fb2e9b2a44a2.png">
<img width="1308" alt="screen shot 2017-06-21 at 9 12 33 am" src="https://user-images.githubusercontent.com/23038505/27385872-00262c2a-5662-11e7-870d-62668f9f6538.png">
