### ISSUE TITLE
StyleGuide: improve alignment of section header and source code button

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#1928]
The section header (H2/H3) and the source code button could be better horizontally aligned.  The current view:
<img width="381" alt="screen shot 2017-05-09 at 8 13 39 am" src="https://cloud.githubusercontent.com/assets/1053255/25850730/59562b30-3491-11e7-8c8b-87161aba2046.png">

can be improved by:
- Giving the parent container a `line-height` bigger than the children
- Making the section header an `inline-block`

Results:
![better_section_source_alignment](https://cloud.githubusercontent.com/assets/1053255/25850706/43c7fba4-3491-11e7-965b-806d37f7aada.gif)

**Comment by slj** [comment]
Fix in action:
![better_secsrc_align_action](https://cloud.githubusercontent.com/assets/1053255/25851744/f30bffa4-3494-11e7-92db-161a0fa11953.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the Style Guide
2. Validate Source Code button is aligned with its respective header.

Screenshots: 
![sg_5_10_17](https://cloud.githubusercontent.com/assets/23038505/25901743/b01a4562-3565-11e7-91b7-22e01cea73c0.png)
