### ISSUE TITLE
ARC Manager View - Add link to missing decisions page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1936]
Add a link to the Missing Decisions page so that the ARC manager can easily see what claims are missing decisions (and they don't have to call us).

## AC
- h2 'ARC Reports' is added to the manager view
- Link is added to manager view
- Link opens the missing decision page in another tab

## Mock

<img width="571" alt="screen shot 2017-05-22 at 2 11 06 pm" src="https://cloud.githubusercontent.com/assets/4975959/26322346/a44ba16c-3ef8-11e7-8be3-c57dc8c0cf7d.png">

**Comment by lakohl** [comment]
until we find a more elegant solution...

<img width="578" alt="screen shot 2017-05-22 at 9 58 14 am" src="https://cloud.githubusercontent.com/assets/4975959/26312389/63b45f22-3ed5-11e7-8db5-d023443fbee6.png">

**Comment by slj** [comment]
Solution in action:

![link_to_missing_docs](https://cloud.githubusercontent.com/assets/1053255/26552284/803375be-4454-11e7-9081-6b35542bf832.gif)

**Comment by kierachell** [comment]
**PASSED**
<img width="578" alt="screen shot 2017-05-30 at 5 37 13 pm" src="https://cloud.githubusercontent.com/assets/18075411/26606126/bb7904e4-455e-11e7-9253-61830866aaa6.png">
<img width="829" alt="screen shot 2017-05-30 at 5 37 26 pm" src="https://cloud.githubusercontent.com/assets/18075411/26606127/bb7bdd04-455e-11e7-8e2c-579bb73fae9c.png">

**Comment by lakohl** [comment]
I realize this was not in the AC, but can we make the page title for Claims Missing Decisions = 'Claims Missing Decisions'?

**Comment by slj** [comment]
@lakohl I'll create an issue to make the change once https://github.com/department-of-veterans-affairs/caseflow/pull/2184 is merged.
