### ISSUE TITLE
ARC Manager page: Add Work History

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1937]
Give the ARC manager more visibility into which claims his team is currently working. Show claims that have been cested in the last 1.25 months?

**AC**
On the ARC Manager page: 

1. Add link to Work History
2. Create a table showing which claims (by vet ID) have been worked and by whom (employee name/initials) and type of claim (full, partial, remand), date worked

**Mock:**
![screen shot 2017-12-29 at 2 07 21 pm](https://user-images.githubusercontent.com/4975959/34445439-ae0cfa8c-eca1-11e7-9d22-2ce59cb9cf33.png)

**Comment by lakohl** [comment]
@cmgiven is this history info covered in your monthly AMO report?

**Comment by cmgiven** [comment]
I send AMO a monthly report of cases in the frontend seam. I don't presently generate any other reports for AMO.

This would be fairly straightforward to make a script for, but it sounds like the kind of thing they want to check routinely?

**Comment by lakohl** [comment]
It seems like this table structure could also be used by BVA Dispatch
