### ISSUE TITLE
Zooming | Scroll and page jump

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1938]
**Description**
When zooming in and out of multiple pages, the scrollbar jumps and page number changes. 

Complementary gif by Artem
![shiftingzoom](https://cloud.githubusercontent.com/assets/18075411/25864870/00e73b0a-34bf-11e7-90d7-67ca1a66ab3d.gif)

## Related Issue

#1649

**Comment by mdbenjam** [comment]
I actually think this is going to be annoying to implement and is not that high of priority. Have people complained about this? @gnakm @abbyraskin

**Comment by gnakm** [comment]
@mdbenjam It isn't a high priority and it isn't a user feedback. Good call on pointing that out. However, in general it is pretty annoying. I definitely think we can relabel this as low-priority and also wonder if this problem will get fixed with the new jumping to different page issue #1884

**Comment by mdbenjam** [comment]
This no longer seems to happen. Closing.
