### ISSUE TITLE
Style guide component | Add gray-light to color palette

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1940]
**Description**
Add `gray-light` and `gray` to color palette

## AC
- Verify that `gray-light` (`#aeb0b5`) is added to the primary colors section of color palette
- Verify that `gray` (`#5b616b`) is added to the primary colors section of color palette
- Verify that it looks like the mock below

## Mockup 
![image](https://cloud.githubusercontent.com/assets/13420618/26058732/241755dc-394d-11e7-9ad4-582b2f3b8bee.png)

**Comment by lakohl** [comment]
Add gray #5b616b?
Also, when do we use the base #212121? I believe our default text color is #323a45

**Comment by gnakm** [comment]
@lakohl Adding `gray`I don't think #212121 is being used. I think that was added because of it was in the original caseflow style guide. I do wonder if we should use them for icons. Would love your thought on that.

**Comment by lakohl** [comment]
I think that we are currently using #000000 for icons (in the footer) it's pretty close to #212121 we should decide on one or the other

**Comment by mmlumba** [comment]
@gnakm @lakohl `grey-light` is actually #a3b0b5 in USWDS

**Comment by lakohl** [comment]
@mmlumba indeed you are correct about grey-light. Thanks for updating!

**Comment by lakohl** [comment]
Wait, @mmlumba grey-light is actually: #aeb0b5

**Comment by mmlumba** [comment]
@lakohl  you're right! changing that

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: Chrome and FF

Steps to Validate:
1. Access /styleguide
2. Verify the colors have been added per Mocks and AC

Screenshots:
<img width="1374" alt="screen shot 2017-05-16 at 10 04 02 am" src="https://cloud.githubusercontent.com/assets/23038505/26110051/27d8c5de-3a1f-11e7-9879-ec971b0d4a5e.png">
