### ISSUE TITLE
Required Checkboxes cause errors in console

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1947]
**Description:** When inspecting the section for Required Checkboxes in the style guide, errors appear in the console of the inspector. 

**Expected:** No errors should appear in the console. 

**Browser:** FF and Chrome
**Environment:** UAT

**Steps to Reproduce:** 
1. Access the Style Guide
2. Scroll to the Checkbox section 
3. Navigate to the Required Checkboxes
4. In your browser, open the inspector tool 
5. View the errors found in the Console. 

**Screenshots:**
<img width="1437" alt="screen shot 2017-05-10 at 10 15 46 am" src="https://cloud.githubusercontent.com/assets/23038505/25905318/b9c01a10-356f-11e7-934a-e8bdfba4ddc2.png">

**Reported by: Alexis Stewart**

**Comment by kierachell** [comment]
**PASSED**
![required](https://user-images.githubusercontent.com/18075411/29714459-53b8d4fe-8971-11e7-86f5-f23187352a7d.gif)
