### ISSUE TITLE
Remove VBMS ID from Success page message

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1949]
To make success pages consistent along all of the products of Caseflow, the VBMS-ID of the veteran in Certification should be removed on the Success page to reduce redundancy. 

**Acceptance Criteria:**
Success message should read, ' "_____'s case has been certified. You can now close this window and open another appeal in VACOLS.'

**Screenshots:**
<img width="961" alt="screen shot 2017-05-10 at 12 04 22 pm" src="https://cloud.githubusercontent.com/assets/18075411/25909223/7956e3fe-357a-11e7-9e9a-e8af9b7722e8.png">

**Steps to Validate:**
1. Go through the Certification happy path
2. Verify the message shown on the Success page against the AC.

**Comment by kierachell** [comment]
**PASSED**
BEcause I can
<img width="963" alt="screen shot 2017-05-13 at 4 12 39 pm" src="https://cloud.githubusercontent.com/assets/18075411/26028886/0a882fda-37f7-11e7-8b5f-4a8bd2935e7e.png">
