### ISSUE TITLE
Document Viewer | Display page count after document has rendered

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1954]
**Description**
Currently, when opening a large document, the page count increases as the page loads, causing confusion for users. Instead, we should show the total page count (after the document has rendered???) rather than adjusting the count as the page loads.

## Acceptance Criteria
- exact implementation TBD by engineers 
- The total page count on the bottom toolbar in the PDF viewer does not change mid-render

**Comment by kierachell** [comment]
Should there also be a loader for the first time render? Like Dispatch?

**Comment by abbyraskin** [comment]
yes, we have a ticket for this.

**Comment by abbyraskin** [comment]
> Should there also be a loader for the first time render?  

Yes, we have a ticket for this.

> Also, I thought you do not want to render all the pages at once; presumably you might want to save the page count as metadata to display right away and render as the person scrolls about?

I will leave the implementation details up to our devs :) I can make the AC less descriptive in meantime

**Comment by tejans24** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/2024 - fixes this issue. 

For some reason, the issue is not being connected to the PR.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access reader with large documents
2. Validate that the total page count appears at the bottom of the page
3. Validate the amount of pages in the document 

Screenshot: 
<img width="799" alt="screen shot 2017-05-30 at 1 20 19 pm" src="https://cloud.githubusercontent.com/assets/23038505/26595938/fce191fe-453a-11e7-92bc-722d6838a5a9.png">
