### ISSUE TITLE
Document Viewer | Find: hard to see highlighted results on document page

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#1957]
**Context**
Nick observed an attorney using Reader, and noticed that it was difficult to see the highlighted text when performing find (ctrl+f). 

**Description**
Customize the way text highlighting appears on the page so it's easier to see.

**Comment by kierachell** [comment]
Is this browser specific?

<img width="592" alt="screen shot 2017-05-10 at 8 28 37 pm" src="https://cloud.githubusercontent.com/assets/18075411/25926803/5081ce5e-35bf-11e7-96fc-bde581d9c67f.png">
<img width="619" alt="screen shot 2017-05-10 at 8 28 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/25926804/5088dd2a-35bf-11e7-9c47-d3b7b349c747.png">

**Comment by abbyraskin** [comment]
The person was using Firefox. I wonder if it could be monitor related -- needs more investigation.

**Comment by abbyraskinUSDS** [comment]
Haven't seen/heard this again. Closing.
