### ISSUE TITLE
Document Viewer | Artifacts when rendering large documents and causing `scrollWindow` errors

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1959]
Probably do not want the following to happen:
<img width="974" alt="screen shot 2017-05-10 at 7 11 10 pm" src="https://cloud.githubusercontent.com/assets/18075411/25925598/83e9c8b2-35b7-11e7-9905-5602723eede1.png">

Usually this happens when a document is loading and then you navigate away from it. Upon return, the document seems to be stuck in this "semi-loaded" state.

## Steps

1. Get a big PDF
1. Load it into VBMS.
1. Go to Reader
1. View that PDF and how it starts to load
1. Go to another PDF meanwhile
1. Go back to that PDF
1. Scratch head.

## AC
- Investigate why this is happening and explore/propose potential fixes

## Console Error:
![scrollwindow](https://cloud.githubusercontent.com/assets/18075411/26021434/f3d7ce86-375a-11e7-872f-505e01bef375.gif)

```
TypeError: n.scrollWindow is null[Learn More] application-14e4738177a2c00ef9515985497f643d5f7f2c34c9b4a496008fbcf8176e4941.js:24:27349
	t/n.renderInViewPages/< https://appeals.cf.uat.ds.va.gov/assets/application-14e4738177a2c00ef9515985497f643d5f7f2c34c9b4a496008fbcf8176e4941.js:24:27349
	forEach self-hosted:252:13
	t/n.renderInViewPages
```

## Sentry

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/207/

**Comment by nicholasholtz** [comment]
Happened on a 20 page doc today.

**Comment by kierachell** [comment]
This is also causing production errors like:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/207/

![scrollwindow](https://cloud.githubusercontent.com/assets/18075411/26021433/d34f48ba-375a-11e7-9c6f-d73e01a28efe.gif)

**Comment by abbyraskin** [comment]
Curious to see if #1984 fixes this.

**Comment by mdbenjam** [comment]
@kierachell I think this should be fixed with the scrolling changes. Would love your confirmation.

**Comment by kierachell** [comment]
Now it's not the same issue, but there's a LOT of lag with big documents
- I think you already know about the status bar loading
![lotsa pages](https://user-images.githubusercontent.com/18075411/27439239-7d1226f2-5735-11e7-8935-a45ba5506d2f.gif)


- There's also all these network calls, not sure if intended:
![loadingeverything](https://user-images.githubusercontent.com/18075411/27439702-8f15dd3e-5736-11e7-8834-310927bf4746.gif)

**Comment by mdbenjam** [comment]
Let's make a new ticket for this.

We are downloading future PDFs while displaying the first one. But this is good to see firsthand. These downloads are taking forever. There might be a way to reduce the impact on current viewing. This is a little hard to fake out, so it's hard to see while dev-ing. This is also something that eFolder Express integration might help. A change is in CR that will address the missing footer.

**Comment by kierachell** [comment]
**PASSED**
new issue captuer in #2412
