### ISSUE TITLE
Document Viewer | Switching between documents eats up memory

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1960]
So this is hard to fully debug and solution is not 100% obvious.

## Steps:

1. Go to Document Viewer
1. Open up developer console and start recording memory usage 
1. Switch around documents a bunch
1. Scroll for some documents
1. Go back and forth between documents
1. Watch memory usage climb like crazy

I ran some benchmarks via Firefox console to see how much memory Reader is eating up and here are some results:

### This doesn't look too bad at first:
<img width="623" alt="screen shot 2017-05-10 at 7 15 14 pm" src="https://cloud.githubusercontent.com/assets/18075411/25925496/ec1641d2-35b6-11e7-8846-7015af69ac93.png">

### You can see the memory usage grows continuously
<img width="952" alt="screen shot 2017-05-10 at 7 28 48 pm" src="https://cloud.githubusercontent.com/assets/18075411/25925498/eceffa8a-35b6-11e7-88c9-6a8b934d6162.png">

### It's impossible to tell where it's coming from because JS bundles everything weird.
<img width="994" alt="screen shot 2017-05-10 at 7 18 01 pm" src="https://cloud.githubusercontent.com/assets/18075411/25925497/ec17add8-35b6-11e7-91c5-b54a3f4c48d4.png">

I am not 100% sure of a good solution to this; but this is bound to cause memory problems for some users.

**Comment by kierachell** [comment]
Can confirm, just crashed my machine doing this... had a bit of a heart attack

**Comment by abbyraskin** [comment]
@mdbenjam curious how you think we should approach this one

**Comment by mdbenjam** [comment]
@abbyraskin I'm not sure yet, but it's probably fairly high priority. I'm wondering if we need to explicitly clean up stuff from pdfjs.

**Comment by kierachell** [comment]
### There seems to be a new issue when navigating between many documents quickly:

**Comment by mdbenjam** [comment]
I think this is unrelated to the bug I just fixed. I've heard about this before, but never seen it with my own eyes. Are you sure this didn't happen before this change? @kierachell

**Comment by kierachell** [comment]
**PASSED**
The other issue is captured in #2459 
<img width="274" alt="screen shot 2017-06-27 at 7 41 06 am" src="https://user-images.githubusercontent.com/18075411/27585985-5733dc70-5b0c-11e7-8acd-87e0c144f105.png">
