### ISSUE TITLE
Modal fix in style guide

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#1963]
**Description:** 

When in Caseflow Commons, as any user, and the user scrolls to "Modals", the Modal is does not pop up as the button is clicked. 
![modal-error](https://cloud.githubusercontent.com/assets/4773320/25956554/09dcee7c-363a-11e7-8987-88d663355570.gif)

**Steps to Recreate:**

1. Go to style guide in Demo
2. Click on "Modals" in the side nav
3. Click the "Launch modal" button and notice there is no modal popping up 

**Expected Results (If Any):**

Modal should pop up when "Launch modal" button is clicked

**Browser Found:** Chrome

**Environment Found:** Demo

- [ ]    5 - Data loss, data corruption or system unavailable

- [ ]    4 - Important functionality is unavailable with no workaround

- [ ]    3 - Important functionality is unavailable but has a
reasonable workaround

- [ ]    2 - Secondary functionality is unavailable but has a
reasonable workaround

- [x]    1 - Cosmetic issues or some functionality unavailable but has
a simple workaround

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate:
1. Access the style guide
2. Navigate to modals
3. Validate the modal behavior via AC

Screenshots:
![sgmodals](https://cloud.githubusercontent.com/assets/23038505/26000875/83070c4c-36f8-11e7-99fd-475b97bb514a.gif)
