### ISSUE TITLE
App Canvas | What is our landing page after user logs out?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1965]
# Description
When a user logs out or just goes to `https://appeals.cf.uat.ds.va.gov/` they land on a crappy-looking page. Should they be redirected to **What's New?**

<img width="936" alt="screen shot 2017-05-11 at 11 41 08 am" src="https://cloud.githubusercontent.com/assets/18075411/25958498/bed408d4-363e-11e7-91b0-a9240218660d.png">

## Reproduction Steps

**Scenario 1 -**

1. Go to `https://appeals.cf.uat.ds.va.gov`

1. See a boring page.

1. Wonder.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [X] Preprod
- [x] Prod

## Screenshots
**_Scenario 1 - [Lame]_**

<img width="1077" alt="screen shot 2017-05-11 at 11 38 36 am" src="https://cloud.githubusercontent.com/assets/18075411/25958359/6605166c-363e-11e7-8d1d-4da6917078d6.png">

**Comment by nikitarockz** [comment]
@lakohl @laurjpeterson @abbyraskinUSDS I realize this is a very low priority but it is a real thing.  I haven't checked to see what happens when you log out of production as to what happens.  I just wanted to make you aware of this.  I was going to close this issue as Obsolete but thought you might be interested in doing something about this.

**Comment by nikitarockz** [comment]
I just validate that when you log out from production you get the Caseflow Help page listing all help pages.  I am thinking we should have something that signifies that the user has actually logged out.

**Comment by nikitarockz** [comment]
I would also mention that once you have logged out (production), you are stuck in a state of being logged out and there is no way to get back logged in without closing all windows.  The stored cache keeps you logged out.  There's no option to to say login.
