### ISSUE TITLE
Document Viewer | Advanced comment error handling

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#1966]
**Description**

Right now if you add, edit, move, or delete a comment, users get the same generic message. We want issues to have errors tailored to each comment error situation (see #1854). 

When there is an error in the backend, we should just try again once or twice but then those fail, show the follow errors for each type of action.

## AC

- When a user tries to **save** or **edit a comment** (including new comments) but there is an error, 
  - [ ] Verify that it has message 
    - Title: **Unable to save your comment.** 
    - Body Copy: Please try saving again. 
    - Try saving again link should allow user to save again. 

![image](https://cloud.githubusercontent.com/assets/13420618/26805779/8fb7b6c2-4a1b-11e7-8451-7a73e1a6dd62.png)

- When a user tries to **delete a comment**  (including new comments)
  - [ ] Use [modal style guide component](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#modals)
   - [ ] Verify that it has message 
     - Title: **Unable to delete comment.** 
     - Body Copy: Please close this message and try again.
     - Red button should say "Close"

![image](https://cloud.githubusercontent.com/assets/13420618/26510730/b4957d18-422c-11e7-8001-12e86c8c2b28.png)

- When a user tries to **move comment icon** but there is an error, show no feedback

**Comment by abbyraskin** [comment]
This calls for a markdown box!

### Current state
Generic "unable to save" at top of comments section. This message disappears if a user performs another comment action successfully, or if they navigate away from the page.
![image](https://cloud.githubusercontent.com/assets/4042181/25961268/b3e9593e-3647-11e7-9d8c-1744865d18b5.png)


Action | Comment box behavior on fail | Message behavior on fail | 
---- | --- | ---- | 
Save new comment | Stays open, copy is saved | Generic error on top of comments |
Move comment icon | No action | Generic error on top of comments |
Save edit | Stays open, copy is saved | Generic error on top of comments |
Delete comment (confirm modal) | Copy is saved | Generic error on top of comments |

### Expected state
We probably want to consider more action-specific error message text and placement. We may want to persist these messages longer and/or add a 'try again' link for certain actions like saving an edit. The "move comment" fail scenario is probably the trickiest...

Action | Comment box behavior on fail | Message behavior on fail | 
---- | --- | ---- | 
Save new comment | Stays open, copy is saved | Generic error on top of comments |
Move comment icon | Box highlight?   | In line message? No change? |
Save edit | Stays open, highlight? | In line message? |
Delete comment (confirm modal) | Box highlight? | In line message? |

**Comment by gnakm** [comment]
#2079

**Comment by gnakm** [comment]
**_Save new comment_** and **_Save edit_**

I think **_save new comment_** and **_save edit_** can be the same message. For save edit, can we have it so that the behavior is the new copy is always saved? 
Version 1 allows users to save what they wrote in the comment box and save again by clicking link in the error copy. 
![image](https://cloud.githubusercontent.com/assets/13420618/26366422/0dc03f20-3fb9-11e7-947e-65dbaef3b0c9.png)

Version 2 allows users to save what they wrote in the comment box and close out the error message. We can have it so that the page refreshes. This means that the new comment will disappear but they know this is coming when they opted to close the error message. Pro for this is it will get the error message to go away. 
![image](https://cloud.githubusercontent.com/assets/13420618/26366427/15700af2-3fb9-11e7-9748-880f872965c7.png)

**Unable to move comment** 

Version 1 Show on top of comment that cannot be moved that the comment cannot move. The next step should be for users to refresh the page. 
![image](https://cloud.githubusercontent.com/assets/13420618/26367319/205353d6-3fbc-11e7-907f-7939c97f3fcb.png)

Version 2 - Have no error message. I think because the icons have some distance from the annotation menu, users may not see it as much. Also, comments not being able to move is sort of a feedback mechanism. 


**Delete comment (confirm modal)**

This error was the reason I thought it's best to stray away from modal as a error handing for this whole section because in this page, we already have a modal coming up and to have a modal back to back might be a weird, redundant experience. 

![image](https://cloud.githubusercontent.com/assets/13420618/26367407/78a6ae7a-3fbc-11e7-9f51-f78a07c59e7e.png)

**Comment by gnakm** [comment]
After our chat, this is where we landed:

**Save new comment** and **Save edit**
![image](https://cloud.githubusercontent.com/assets/13420618/26421219/33ed2b4c-4093-11e7-8ad3-ba54ea70c89f.png)
- [ ] Comment box should be focused
- [ ] Comment should be saved
- [ ] User can try again by clicking save button or the Try saving again link in copy. 
- [ ] Alert always above the individual comment box

**Delete comment**
![image](https://cloud.githubusercontent.com/assets/13420618/26421228/3e26fe26-4093-11e7-9910-b370f30f2c09.png)
- [ ] Comment box should be focused
- [ ] Comment should be saved
- [ ] User can try again by clicking save button or the Try saving again link in copy. 
- [ ] Alert always above the individual comment box

**Moving comment**
Don't need to show error feedback.
Ideas we explored:
- Modal - Too abrupt and big lift for something so small
- Error alert in annotation menu however if users are looking at the doc viewer, they will most likely miss it. 
- Icon not moving is already a feedback and usually users will try again and it will work

**Comment by gnakm** [comment]
^ @abbyraskin The above is what we discussed today between meetings. I want to make sure this is the final verdict so that I can write a detailed AC for the use cases.

**Comment by abbyraskin** [comment]
it looks good to me, i think we should run it past engineers first before you detail the AC.

**Comment by gnakm** [comment]
@NickHeiner @mdbenjam 

Could you guys check the previous comments on the mock and answer the following questions:
1. Do they make sense?
2. Are we missing something?
3. How should these issues be broken out? All in one issues? Granular issues?

**Comment by tejans24** [comment]
I think this makes sense. It's probably a typo for the Delete comment failure, but it should probably say 'Please try again' or 'Please try deleting again'?

Should it show up between the Page number and the text box or above the Page number column in the comment?

**Comment by mdbenjam** [comment]
In general this makes sense. It feels a little weird to give the user an option to immediately try again. It seems that we should just try again for them if we fail, and if we fail 2-3 times surface this error saying that we aren't able to save right now and that they should try again later. Similar idea around moving a comment. If it normally works the second time, we should just try twice before failing. But if it doesn't work then, some more feedback about what just happened might be useful.

I think one ticket would be fine.

**Comment by NickHeiner** [comment]
Makes sense to me. One ticket is fine.

**Comment by gnakm** [comment]
One thing Mark and I talked about is having feedback for when we try again on our end. 
Curious to know if the delete comment one is a bit excessive? 

|Actions|Processing|Error alerts|
|----|-----|----|
|Annotation handlings|When we try to save from our end|When we fail|
|Save new comment|![image](https://cloud.githubusercontent.com/assets/13420618/26508858/620824e0-4224-11e7-82ff-72ec3f825e5b.png)|![image](https://cloud.githubusercontent.com/assets/13420618/26510099/9c70d55a-4229-11e7-8de1-585405e40441.png)|
|Save edit comment|![image](https://cloud.githubusercontent.com/assets/13420618/26508858/620824e0-4224-11e7-82ff-72ec3f825e5b.png)|![image](https://cloud.githubusercontent.com/assets/13420618/26510099/9c70d55a-4229-11e7-8de1-585405e40441.png)|
|Move comment icon|No feedback needed|No feedback needed|--|
|Delete comment|![image](https://cloud.githubusercontent.com/assets/13420618/26509024/e97953d6-4224-11e7-99c7-596751a73705.png)| ![image](https://cloud.githubusercontent.com/assets/13420618/26510730/b4957d18-422c-11e7-8001-12e86c8c2b28.png)|

**Comment by NickHeiner** [comment]
Why do we have the spinners for the processing state? Our convention thus far has been to optimistically update the UI, and only show the error state if the action fails.

**Comment by gnakm** [comment]
@NickHeiner I had a chat with @mdbenjam about this and I may have totally misinterpret it when we talked about us taking time to update the UI. The process is for when it's taking a long time for us to retry some of these actions. My followup question is how long would that take and also, do we have to account for any latencies? The spinners may generally be excessive for these situations but a processing feedback may be helpful depending how long it takes.

**Comment by NickHeiner** [comment]
Let's chat synchronously about this.

**Comment by gnakm** [comment]
Original comment

**_Needs definition_**
We probably need better comment error handling overall. Right now, if you add, edit, move, or delete a comment and the call fails, the user receives a somewhat generic error message above the comment box (see #1854). 

This handling seems to make sense for the add comment flow, as it appears above the comment box itself. For other error scenarios, it's less contextual -- e.g., if a user moves the comment icon. 

The other confusing piece to our current implementation is that anytime a user takes a successful action on a comment, the error message goes away. So, if a user moves one comment and it fails, then quickly moves another comment and it succeeds, they could easily miss the error.

- How do we want to handle move errors? (for example, a red highlight/message near the comment box if a user unsuccessfully tries moving the comment icon)
- How long do errors persist? What actions do we want to allow the user to take when an error occurs? (e.g., "try again") 

### Scenarios to consider (currently all of these are handled by a message at the top of the comments section, which disappears automatically if the user successfully performs any of these actions or navigates away)
- User tries moving a comment and it fails
- User tries to delete a comment and the delete fails from confirmation modal
- User tries to edit a comment and save edit fails
- User tries adding a comment and it fails

**Comment by abbyraskinUSDS** [comment]
For the sake of prioritization, do we have a way of investigating how often these different error scenarios occur @mdbenjam? (save/edit comment failures, delete comment failures).

**Comment by abbyraskinUSDS** [comment]
We decided this isn't necessary.
