### ISSUE TITLE
Document Viewer | Progress indication

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1973]
## Story

As a user, I want to know which document I am from the total number of document as from the document viewer

## AC
- Verify that at the bottom of the document viewer toolbar, there is a progress indicator in the order of Document [number of current document] of [total number of documents]. 
- Verify that if a user has filtered the documents list and opens a document, the document count is based on the number in the filtered list, rather than the overall total
- Verify that if the user has filtered the list, a filter icon is shown right before the progress 

## Mock up 

What I should look like
![image](https://cloud.githubusercontent.com/assets/13420618/26607959/fc405538-4566-11e7-9a3b-709223e0b1a4.png)

Whole toolbar as reference
![image](https://cloud.githubusercontent.com/assets/13420618/26259610/c010fa2c-3c97-11e7-875f-39627b96c56b.png)

[Filter SVG](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Filter-white.svg)

Related: #1853

**Comment by abbyraskin** [comment]
I suppose this is more of a "where am i" indicator than progress, but may serve a dual purpose their first pass through a case.

**Comment by gnakm** [comment]
Original comment: 

> I'd like to think about how we might show progress in Reader -- there's a need for attorneys to know how many documents they've reviewed.
> 
> I'm thinking v1 could be something very light, which tells attorneys which document they're on in the list (reverse chronologically?) -- e.g. "document 50 of 100." We could also present this visually or as a percentage, but we won't be able to show very specific progress until we know how many pages are in an entire case file.
> 
> Open questions: where might we fit this on the page!? how should we show it?

**Comment by gnakm** [comment]
Things to consider:
- Arrows in side bar
- Doc # of total Docs when filtered.

**Comment by abbyraskin** [comment]
@gnakm added a note about total # of docs when filtered

**Comment by abbyraskin** [comment]
@gnakm note to update w/ new bottom toolbar

**Comment by astewarttistatech** [comment]
**Failed** There is no next and previous buttons and their corresponding arrows. @NickHeiner 

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate:
1. Access reader
2. Validate progress indicator against AC and mocks

Screenshots: 
<img width="799" alt="screen shot 2017-05-30 at 1 20 19 pm" src="https://cloud.githubusercontent.com/assets/23038505/26596012/4da89d58-453b-11e7-8823-5d372c3d3d2a.png">

**Comment by NickHeiner** [comment]
The "next" and "previous" buttons are not in the AC. They are in the mocks, because it's part of an overhaul of the toolbar, but for this ticket, they're not in scope.

@gnakm @abbyraskin we could have been clearer about the mock being a superset of the ACs. :smile:

**Comment by gnakm** [comment]
@astewarttistatech yes Nick is right about this being the subset of a bigger section. This is specifically for the Document # of total documents.

**Comment by abbyraskin** [comment]
Sorry for the confusion.
