### ISSUE TITLE
Document Viewer | Unable to move comments between pages

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1978]
# Description
When viewing multi-page documents, a created comment does not move between pages.

## Reproduction Steps

**Scenario 1 -**

1. Go to Document Viewer
1. Make a comment
1. Try to move it to another page within that document
1. See it move to the same coordinates but on the page it already was.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [X] Preprod
- [x] Prod

## Screenshots
**_Scenario 1 - [Moving about]_**
![movecomment](https://cloud.githubusercontent.com/assets/18075411/26008473/e8cd0300-3712-11e7-9a1a-98af65588dee.gif)

**Comment by abbyraskin** [comment]
thanks for documenting this one!

**Comment by kierachell** [comment]
**PASSED**

FINALLY

![movepage](https://user-images.githubusercontent.com/18075411/31950078-d526eac4-b8a8-11e7-9ca5-b1c01e44155c.gif)
