### ISSUE TITLE
Speed | Investigate: faster document list loading

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1982]
The first time you open a case, it's slow to load the documents list.

Investigate ways to improve the speed by which we display the document list.

**Comment by kierachell** [comment]
**PASSED**
I guess we're checking if network calls are being made on previously rendered documents? is that the AC here?
![network calls](https://cloud.githubusercontent.com/assets/18075411/26586494/4fa205e0-451d-11e7-8863-bc47404bab41.gif)
