### ISSUE TITLE
Document Viewer | Investigate: speed when navigating between docs

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1984]
Currently, documents are slow to load when navigating between documents in the viewer.

Investigate ways to smooth/speed up navigation between documents.

## Dependent Story
#1983 

## Related Story
#1959

**Comment by abbyraskin** [comment]
@NickHeiner can you add some engineering love to this 🙏

**Comment by NickHeiner** [comment]
@abbyraskin what specifically would you like? :smile:

We should do #1983 before we do this, since #1983 will affect all client-side interactions.

**Comment by abbyraskin** [comment]
I think I was concerned about the vagueness -- but understanding the order is helpful, thanks.

**Comment by NickHeiner** [comment]
I'm actually happy with the level of specificity – it's an open-ended ticket.

**Comment by abbyraskin** [comment]
👍 great - it didn't get the usual "story time" vetting so just wanted an engineer's eye on it. thank you!

**Comment by kierachell** [comment]
**PASSED**
Yeah, it's faster:
![fastprerender](https://cloud.githubusercontent.com/assets/18075411/26586282/be0c8d6c-451c-11e7-8e39-22d567c79a94.gif)
