### ISSUE TITLE
Process Private Attorney full grants in Dispatch

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1988]
As a Caseworker, I want to process Private Attorney full grants in Dispatch and properly route them to Regional Offices.

## Acceptance Criteria
- The Create Establish Claim should create tasks for Full grants with a private attorney marked in VACOLS.
- If a Private Attorney is marked in VACOLS (`BFSO` is `"T"`), the "Private Attorney or Agent" checkbox should be automatically checked on the Review Decision page. 
- Should be hidden behind a feature flag toggle

**Comment by cmgiven** [comment]
Note that we need to vet this change with AMO before moving forward.

**Comment by abbyraskin** [comment]
@lakohl did you bring this up with AMO? did they have any feedback?

**Comment by lakohl** [comment]
I did bring this up with AMO on 5/16 and they were not really aware that we were not already processing POA claims in Dispatch. They were on board with us going ahead and processing them, so I think we should build that functionality behind a feature flag and alert AMO once it's ready so they can warn the ROs.

**Comment by lakohl** [comment]
AMO was finding that there was a long delay between the decision date and when Private Attorney cases were cested.

Today, we exclude Full Grants with Private Attorney (they go to 99) from Caseflow.
- We could elect not to exclude them from Caseflow.

Today PA Partials and Remands (Return from  BVA) are sent directly to ->50
- We could ask Jed if VACOLS could send Remands or Partial to ->97 (Remand in transit to ARC) then Caseflow could Dispatch them to-> 50 and create an EP for the correct ROJ station. Theses claims wouldn't necessarily need to be surfaced in the ARC work queue (check with AMO on this). 
ARC might be able to identify other special issues related to the claim. Also does ARC want the PA claims for purposes of measuring the work?

I sent an email asking Rolandus and Denese which other types of cases are not Dispatched from BVA to ARC? (VHA/VAMC, CAVC, NCA?)  (VHA claims might be for medical devices?)
- Auto-responder indicated that both Rolandus and Denese are out until 6/12.

**Comment by lakohl** [comment]
Denese replied:

'Claims without attorney’s, having a service representative or no rep that are allowances and/or remands go to the Appeals Management Office/Center.
 
Claims involving education – go to the designated education center.
 
Claims for National Cemetery go back to that location. The insurance claims go back to the designated insurance centers.
 
The Education, National Cemetery, and Insurance Offices are the only facilities that process their own claims.'

**Comment by lakohl** [comment]
@sharonwarner when you get a chance, could you let me know when you think this ticket might be completed? Not wanting to pressure you. But, I'd like to let AMO know so they can alert the ROs this functionality is coming.

**Comment by kierachell** [comment]
**PASSED**

using:
```
   BFKEY DISPOSITION   BFCORLID BFCORKEY   SNAMEF  SNAMEL       SSN SNOTES BFDC BFMPRO TIVBMS BFSO BFREGOFF BFCURLOC                BFDDEC              TIOCTIME
1 892213   FULLGRANT 600701118S CK176485 JENNIFER JOHNSON 600701118    uat    1    HIS      Y    T     RO17       99 2017-06-18 00:00:00.0 2017-06-18 00:00:00.0
```

<img width="1017" alt="screen shot 2017-06-20 at 8 08 23 am" src="https://user-images.githubusercontent.com/18075411/27332387-b417f85e-558f-11e7-97e5-0910fac15dd9.png">
<img width="979" alt="screen shot 2017-06-20 at 8 09 12 am" src="https://user-images.githubusercontent.com/18075411/27332407-c2b24612-558f-11e7-8622-748fa28bc4a4.png">


## Where should PA Full Grants be routed? @lakohl  back to their RO?
<img width="589" alt="screen shot 2017-06-20 at 8 09 31 am" src="https://user-images.githubusercontent.com/18075411/27332474-03b0a9a6-5590-11e7-83ae-e0fea3063665.png">
