### ISSUE TITLE
Styleguide component enhancement | Label spacings

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1989]
## Description
Currently the form field component text labels are still too close to the. We need to do a scrub and add 8px spacing between text and fields

## AC
- [ ] Verify that the following have text and required labels have 8px `margin-bottom`
  - Dropdown Menus
  - Character limit
  - Text area
  - Text input
- [ ] Verify that the following have text and required labels have 20px `margin-bottom`
  - For the group of Checkboxes
  - For the group of Radio buttons

**Comment by lakohl** [comment]
Also - perhaps for another issue:

- Label styling: sentence or title case?
- Margin-bottom below text input boxes

**Comment by astewarttistatech** [comment]
@Sjones352 is this to be verified across Certification V2?

**Comment by Sjones352** [comment]
@astewarttistatech  please verify it in Styleguide.

**Comment by Sjones352** [comment]
@astewarttistatech  I have verified across Certification V2, V1, Dispatch and Reader so issue is ready for validation.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT and Dev
Browsers: FF and Chrome 

Steps to Validate: 
1. Go through the flow for every product in the Caseflow suite
2. Validate Checkboxes, Radio buttons, Dropdown Menus, character limit, text area, text input areas for their respective spacing of 8px or 20px

Screenshots: 
not necessary for this test sweep | smoke test
