### ISSUE TITLE
Document Viewer | Top Toolbar Redesign

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1996]
## Context
We revisited everything from a 508 POV and reordered the top toolbar accordingly. Document name is h1 and we wanted it to come before the zoom options. We also added the download option on the toolbar.

## Acceptance Criteria
-  Verify the new ordering of buttons: 
1. Back to document list 
2. Category tabs 
3. Document type
4. zoom + download icons  (_note_: _Note:_ the download icon should be added to the toolbar as part of this story if #2022 is not yet complete; however, the functionality is  implemented in #2022)
- Verify that there is 40px left margin of back to all documents link and 40px right margin after the download icon

## Mock up

![image](https://cloud.githubusercontent.com/assets/13420618/26124831/ec504508-3a4d-11e7-9bb6-95ca4715c25d.png)

[Download SVG can be found here](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Download.svg)

## Related issue 
Accessibility: #1853
Add download icon: #2022

**Comment by astewarttistatech** [comment]
**Failed**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Access a document in Reader
3. Validate the behavior and UI of the top toolbar redesign against mocks and AC

Screenshots: 
<img width="1002" alt="screen shot 2017-06-02 at 10 01 28 am" src="https://cloud.githubusercontent.com/assets/23038505/26729226/ea92c602-477a-11e7-810e-394764bf7556.png">

**Comment by gnakm** [comment]
I think the back arrow looks fine but @mmlumba could we move it 1px down so that it looks more center aligned with the back to all documents button link?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Compare the redesign of the top toolbar to what is stated in AC and Mocks
3. Make sure that the back arrow is centered aligned with text. 

Screenshots: 
<img width="1137" alt="screen shot 2017-06-07 at 10 18 44 am" src="https://user-images.githubusercontent.com/23038505/26883354-f7357df2-4b6a-11e7-8a2b-cc1242ff4b6b.png">
