### ISSUE TITLE
Document Viewer | Receipt date edit option

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1997]
## Description
We've heard from many users that receipt dates may be wrong and we want to allow users to edit and update the date in VBMS through reader.

## AC

- [ ] Verify that users can go into edit mode by clicking the "edit" link next to receipt type
- [ ] Verify that user can edit date using the date input component that will be added to [style guide](https://github.com/department-of-veterans-affairs/caseflow/issues/1082)
- [ ] Verify that users can opt out by clicking cancel or save any changes by clicking save
- [ ] Verify error state shown in [style guide issue](https://github.com/department-of-veterans-affairs/caseflow/issues/1082) is implemented 
- [ ] Please take out semicolon after Receipt Date now that edit is next to it :)

## Mock up 

![image](https://user-images.githubusercontent.com/13420618/28691276-5044544e-72ea-11e7-867f-4379b9f0c14d.png)

![image](https://user-images.githubusercontent.com/13420618/28691253-3a1f022c-72ea-11e7-9e59-2065d1276b4f.png)

![image](https://user-images.githubusercontent.com/13420618/28691258-4120531e-72ea-11e7-985c-29d7ca65fb7b.png)

Error state 
![image](https://user-images.githubusercontent.com/13420618/28796455-996afeec-760b-11e7-8cb9-50f21a49555a.png)

## Related
Style guide issue https://github.com/department-of-veterans-affairs/caseflow/issues/1082
#2745

**Comment by gnakm** [comment]
Things to investigate:

- Should the document type be a typeahead? What is it currently in VBMS? Dropdown?
- Will changing the date input field effect how data is changed in VBMS?

**Comment by abbyraskin** [comment]
Technical feasibility investigation here -- https://github.com/department-of-veterans-affairs/appeals-design-research/issues/211

**Comment by abbyraskin** [comment]
We also need to think about error handling, since it will require specific/constrained inputs.

**Comment by abbyraskin** [comment]
@gnakm we should prioritize nailing down some of these design/functionality details :D

**Comment by abbyraskin** [comment]
@aroltsch would love to sync with you on this soon

**Comment by gnakm** [comment]
Note for self:

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
