### ISSUE TITLE
Documents List | Claims folder details 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1998]
**Description**
It would be awesome if we can get information of a brief face at the top of the documents lists. 

## AC
- [ ] Verify that there is an accordion labeled `Case details` that is in the style of the USWDS accordion with border with all of claim detail information inside See [accordions in style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#accordions)

- [ ]  Verify that the following information is at the top of documents list
  - Veteran ID (Claim number)
  - If the case is AOD, show the word AOD in `$color-secondary` next to **Type** description.
  - If the case is CAVC, show the word CAVC in `$color-secondary` next to **Type** description.
  - If the case is both AOD or CAVC, show the words AOD, CAVC (note comma in between) in `$color-secondary` next to **Type** description.
    - See [colors for style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#colors) if needed here
  - Type (Court remand, Original, Remand...)
  - Docket number
  - Regional office number and city [same styling as Dispatch station field]
  - Issues 
    - Make sure they are numbered
    - `Issue code`:  `level 1-3`

## Mockup

![image](https://user-images.githubusercontent.com/13420618/28286550-84fa1f7a-6b06-11e7-880f-4b4892dab587.png)

![image](https://user-images.githubusercontent.com/13420618/28286553-8bb6a2d4-6b06-11e7-8b41-dab633d0046c.png)

## Related
#2161
https://github.com/department-of-veterans-affairs/caseflow/issues/2375

**Comment by gnakm** [comment]
Gina to check in with Lara so that top information is consistent with hearing prep worksheet.

**Comment by gnakm** [comment]
Reader and Hearing Prep team to chat about this 5/24 :)

**Comment by gnakm** [comment]
@abbyraskin According to Lara, we currently cannot pull the original claim date but Shane is planning to work on it when he get's back so we can punt that for later. I also took out documents number because it should be added below. 

Questions for you:
- I took out the diagnostic codes but this is a product decision on whether or not we want our users to use it. 
- Do you remember what an "office number" is? Representative code maybe?
- Is there anything missing?

__

## New AC
- [ ] Verify that there is an accordion labeled Claim detail that is in the style of the USWDS accordion with border with all of claim detail information inside (Related: #1482)

- [ ]  Verify that the following information is at the top of documents list
  - Claim number (Label Veteran ID)
  - Docket number
  - Original office number (office for rating decision is always accurate on brief face)
  - Issues 
    - Program 
    - Issues
    - Levels 1-3
    - Description - There is a section in VACOLS where judges go in to write usually judges go to re-write a better description of issues. Hearings prep will have this, where judges can write notes that will help guide review + decision building. 

## Mockup

Details closed
![image](https://user-images.githubusercontent.com/13420618/27203946-3f80bd60-51f6-11e7-8c59-e55d30e92fc3.png)

Details open
![image](https://user-images.githubusercontent.com/13420618/27203981-7b3e11f4-51f6-11e7-997b-6a226609d0cc.png)

## Related
#2161

**Comment by abbyraskin** [comment]
Notes / decisions from call with @gnakm :
(1) Claim detail --> Case details
(2) Change Description to Notes; description is generally 2 lines, but will scroll if longer.
(3) AOD/CAVC color coding from VACOLS (finding out what this is)
(4) Hold off on issue notes section until Hearings team has built on this field

**Comment by abbyraskin** [comment]
AOD = red
CAVC = blue

**Comment by gnakm** [comment]
Old mocks... just incase.

**Comment by abbyraskin** [comment]
@gnakm would you mind if we made this "details" (plural) instead of "detail"? singular sounds a little awkward to me.

**Comment by abbyraskin** [comment]
@gnakm do we have a ticket for adding the "Joe Snuffy's Claims Folder" to the top? Also, we might want to think about how long someone's name could be, and whether there will always be enough room between the name and the doc count.

**Comment by mogrenAtWork** [comment]
@tejans24 just a heads up, I've added a `levels` attribute to the `Issue` model that may help you: https://github.com/department-of-veterans-affairs/caseflow/pull/2530/files#diff-b4d2426dbdcb62ca15098fd8b5be9f0dR79

**Comment by kierachell** [comment]
### Ya done broke the Welcome Gate! :(

- Unable to see the welcome gate anymore :( sad...
- Seems like `appeal.to_hash` got new methods/fields and for some reason the Lazy Loading is turned off???
```
AssociatedVacolsModel::LazyLoadingTurnedOffError 
(AssociatedVacolsModel::LazyLoadingTurnedOffError):
  app/models/concerns/associated_vacols_model.rb:16:in `block (2 levels) in vacols_attr_accessor'                                                                                                             
app/models/appeal.rb:365:in `to_hash'
  app/models/user.rb:115:in `block in current_case_assignments_with_views'                                                                                                                                    
app/models/user.rb:114:in `map'
  app/models/user.rb:114:in `current_case_assignments_with_views'                                                                                                                                             
app/controllers/reader/appeal_controller.rb:8:in `block (3 levels) in index'
  app/services/metrics_service.rb:12:in `block in record'                                                                                                                                                     
app/services/metrics_service.rb:11:in `record'
  app/controllers/reader/appeal_controller.rb:6:in `block (2 levels) in index'                                                                                                                                
app/controllers/reader/appeal_controller.rb:3:in `index'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                            
app/middleware/metrics_auth.rb:10:in `call'
```
https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/340/


### What about no issues?
<img width="1216" alt="screen shot 2017-07-28 at 2 24 12 pm" src="https://user-images.githubusercontent.com/18075411/28741305-3fdae3c8-73e1-11e7-92b5-6199cc0ebcbe.png">


### Which secondary color? That looks blue not red
<img width="709" alt="screen shot 2017-07-28 at 2 21 22 pm" src="https://user-images.githubusercontent.com/18075411/28741307-4ad8a6ac-73e1-11e7-90d7-1991231e2e6e.png">

### No state? Why not?
<img width="285" alt="screen shot 2017-07-28 at 10 11 07 pm" src="https://user-images.githubusercontent.com/18075411/28741323-c252c3f2-73e1-11e7-94b5-3dd0fadba55d.png">

**Comment by tejans24** [comment]
@kierachell I addressed the color comments in a PR, it's merged into master now

**Comment by gnakm** [comment]
@kierachell the no issues issue can be found here: https://github.com/department-of-veterans-affairs/caseflow/issues/2787. As for not showing the state of the ROs, we've only heard ROs being called by the city and it's much more specific so I don't see the need for adding it.

**Comment by kierachell** [comment]
K, the reason I was asking is that Hearings Prep shows both

**Comment by kierachell** [comment]
**PASSED**
last little bit fixed by 
https://github.com/department-of-veterans-affairs/caseflow/pull/2803
