### ISSUE TITLE
Detect cases in which Caseflow was not completed

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#20]
For cases that VACOLS launched Caseflow, but the user did not complete the flow after a day, keep a log so that these cases can be marked as not certified and any generated PDF documents can be cleaned.

**Comment by alex** [comment]
Starting to think about these:

- [ ] How do we detect them? (What's the criteria for an uncompleted one)
- [ ] What do we do with the list?

**Comment by plusjeff** [comment]
Good question. The "What do we do with the list?" seems especially relevant. Will check in with BVA folks to see if this is needed.

**Comment by plusjeff** [comment]
Spoke with @labecker about this one.

It would be handy if we (the VA) have a way to see which cases were started in Caseflow, but not finished. Possible implementation: 

1. Log of every case started in Caseflow along with a timestamp
1. When the case is certified, remove from log (or mark as completed)
1. If something is on the list for more than a month, produce a report

This is a nice to have, but moving down on the priority list and placing in the backlog for later.

**Comment by labecker** [comment]
Agree - thank you! If we can also capture with the logging of every case (perhaps already the assumption) to include the specific RO data for analytics purposes.

**Comment by paultag** [comment]
I was able to scrape logs to do this before we move to a better solution

**Comment by KHarshawat** [comment]
Closing this issue because we have YuleLog to do this.
