### ISSUE TITLE
Fetch POA info from BGS and VACOLS and display it in the ConfirmCaseDetails UI.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2003]
Create the backend infrastructure for fetching, processing, and displaying POA information.

We’ll want to make a class named PowerOfAttorney. That class should handle the following operations:

- fetching POA from VACOLS and converting it into our format
- fetching POA from BGS and converting it into our format

## Acceptance Criteria ##
- The ConfirmCaseDetails page should display POA information from VACOLS and BGS in some format (it doesn't have to be styled in any particular way yet).
- This information must include representative name and representative type. We might have POA address wait until a later ticket.

For reference:
![image](https://cloud.githubusercontent.com/assets/3781835/26077797/57867612-398b-11e7-9bc7-d6d7c5dad7a9.png)

**Comment by kierachell** [comment]
**PASSED**
mocks are old af, but ok
<img width="1033" alt="screen shot 2017-06-02 at 11 43 50 am" src="https://cloud.githubusercontent.com/assets/18075411/26736590/c931ea64-4794-11e7-8f69-6ed254391a71.png">
<img width="1047" alt="screen shot 2017-06-02 at 12 46 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/26736591/c934cc52-4794-11e7-93ce-31cea7afd3cf.png">
