### ISSUE TITLE
Login page changes

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#201]
@KHarshawat There's no design for the login screen, but I also don't think it needs much work. I propose three changes:

- [ ] Move the error message to sit just above the form instead of above the _Welcome to Caseflow_ title
- [ ] Remove the left border from the login form
- [ ] Make the form fields line up with the introductory text.

![screen shot 2015-11-18 at 5 52 30 pm](https://cloud.githubusercontent.com/assets/354277/11257016/3567f1d4-8e1d-11e5-8e4e-c4bc3911113d.png)

**Comment by KHarshawat** [comment]
Everything sounds good... would just add padding b/t error message and Welcome to caseflow text.

**Comment by webinista** [comment]
Changes made.

![login](https://cloud.githubusercontent.com/assets/354277/11504526/ce4c80c2-9813-11e5-9e12-5a79f0364ec1.png)
