### ISSUE TITLE
Document list | The life and death of Categories

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2010]
We are testing the usability and effectiveness of the categories feature for the pilot. 

If we decide to go with them, here are the next steps:
- Users should be able to choose/edit categories and filter documents on list page
- Cannot use color to denote meaning so we're going to have to tag or use text somewhere that is not hidden

**Comment by abbyraskin** [comment]
This is not an engineering task. Also, I don't think we have any clear next steps at this point, so I'm closing this out.
