### ISSUE TITLE
Route Claim: Create EP, re-label EP codes

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2012]
ARC has implemented new EP codes without warning. They are now live. Therefore we need to re-label the EPs we create in Dispatch so that they are in sync with the new EP label structure and can be processed correctly. 

**When we have all the necessary info we should make this update behind a feature flag as AMO will need to be alerted before we implement the change.**

## AC
When we create an EP for a claim that gets worked on the ARC floor (Station 397) we use the label with ARC in the title e.g. 070 ARC BVA Grant. When we create an EP to be worked anywhere else we use the label without ARC in the title e.g. 070 BVA Grant. 

| Old Code | New ARC Code | New Field Code |
|-------------------- | ------ | --- |
170 Remand with BVA Grant | 070 ARC Remand with BVA Grant | 070 Remand with BVA Grant
|170 Remand | 070 ARC Remand | 070 Remand |
| 172 BVA Grant | 070 ARC BVA Grant |070 BVA Grant|

<img width="576" alt="screen shot 2017-05-30 at 1 58 39 pm" src="https://cloud.githubusercontent.com/assets/4975959/26597466/13de02de-4540-11e7-912e-fb4c7d496675.png">

[EP_CodesAndClaimLabels.docx](https://github.com/department-of-veterans-affairs/caseflow/files/1022885/EP_CodesAndClaimLabels.docx)

*Let's handle PMC separately as we don’t create EPs for them yet.

*We need more info from the VBMS team on which modifiers we should now use, and on whether we can have multiple concurrent full grant EPs.

**Comment by lakohl** [comment]
@kierachell is checking with the VBMS team on the appropriate claim label code for Remands and Partial Grants

**Comment by lakohl** [comment]
@kierachell once this issue gets implemented we should probably include a new EP labels in our next UAT test with Jennifer Powell

**Comment by kierachell** [comment]
Sent a question to VBMS team; they have not replied with any information yet.
Can you post the documented proposed changes here - @lakohl @nicholasholtz ?
Meanwhile I will explore VBMS

**Comment by lakohl** [comment]
Asked AMO on 5/16 about whether the label should say the RMD or RMND. They did not know, but said they would investigate. I'm sending a follow up email to AMO now. 
This issue is blocked until we get a response from AMO. They have a stop gap measure in place so that no claims get lost, but we should try to solve this soon as it means that ROs are having to look fro two types of EPs at the moment and that is less than ideal.

**Comment by nicholasholtz** [comment]
Spelling!!!!! The current blocker is SPELLING! Sigh….

**Comment by kierachell** [comment]
> What is showing in UAT now reflects the updated appeals EP model.  I’m pretty sure it has also been pushed to Production.  I have answered the below questions if this helps:
1. Can you confirm that the BVA Grants, and ARC Remands (with Grants) have changed from 170 to 070?  Confirmed.
2. Can you confirm that the new ARC Remand label is 070RMNDARC and not 070RMDARC? The  documentation is inconsistent.  Confirming that it is 070RMNDARC
3. Also, what are the possible values and modifier combinations for the new claim labels?  070, 071, 072?  They’re serial EPs.  If there is an 070 pending, the system will go to 071.  The claim labels that are showing in UAT are an accurate and complete list of the new CLs for 070s and 170s.
4. Do you know if these changes are already in production? As far as I am aware there is still further testing to do on May 24th and it seems like we were creating 170s and 172s as of a week ago.  These new EPs are presently in production.
 
![070 ep codes](https://cloud.githubusercontent.com/assets/18075411/26322877/cc2cfa4e-3efa-11e7-97c0-112fa9493cbd.png)

**Comment by lakohl** [comment]
Adding the email  Artem wrote this morning to VBMS UAT team (Michael Palmer, Maxim Pilipovskiy, Maria Jones, Jennifer Powell, Dawn Happel, and Jennifer Umberhind):

"...Based on the information, I just wanted to double check a couple of things to make sure our system handles the procedures correctly:

Code `BVAGR` seems to refer to a Full Grant. Based on what I checked in VBMS, it is possible to create multiple `BVAGR` End Products now, whereas previously that was not possible. Can you confirm that it is possible now to have multiple EPs for BVA Grants (full grant)? (070BVAGR, 071BVAGR, 072BVAGR, etc…)
The modifiers seem to be shared among all EPs: meaning if there is a 070BVAGR the next RMND will have to use 071 and so on. Do I understand that flow correctly?"

...We are awaiting response

**Comment by lakohl** [comment]
I updated the AC above with the most recent codes and EP labels. They can now be implemented behind a feature flag. We need to alert AMO before we release them. If whomever works this ticket can give me a day when they believe they will be ready to go I can prep AMO in advance.

**Comment by nicholasholtz** [comment]
@lark John Shriver called today and asked about this. He might be a good contact for AMO notice.

**Comment by lakohl** [comment]
@nicholasholtz I spoke to John about this last week and to Amy earlier this week. Did he have any new news?

**Comment by nicholasholtz** [comment]
He just wanted to know status of implementing the changes. Based on your comment above, https://github.com/department-of-veterans-affairs/caseflow/issues/2012#issuecomment-304034292, I assumed status had changed. Sorry my comment wasn't clear above!

**Comment by lakohl** [comment]
@nicholasholtz I'm writing him now:) will cc: you

**Comment by joofsh** [comment]
@kierachell can we validate this first thing in the morning please. Thank you!

**Comment by kierachell** [comment]
## Cannot release claim?
```
[appeals.cf.uat.ds.va.gov] [458078b6-0faa-44f1-989f-9a387dd5d181] [172.30.67.71] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 08:47:40 -0400] Started POST "/dispatch/establish-claim/2103/no-email-complete" for 127.0.0.1 at 2017-05-31 08:47:40 -0400                                                                                                dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0d8a8b647101d2d0b-172.30.67.71 [appeals.cf.uat.ds.va.gov] [458078b6-0faa-44f1-989f-9a387dd5d181] [172.30.67.71] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 08:47:40 -0400]                                                                                                                                                                                                           dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0d8a8b647101d2d0b-172.30.67.71 AbstractController::ActionNotFound (The action 'no_email_complete' could not be found for EstablishClaimsController):                                                                                                                                                                                                                                     app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```
<img width="988" alt="screen shot 2017-05-31 at 8 47 48 am" src="https://cloud.githubusercontent.com/assets/18075411/26632430/2a772ee6-45de-11e7-8d60-ecf380e2dc94.png">

**Comment by kierachell** [comment]
**PASSED**
Didn't kill anyone in prod;
made new issues from whatever is actually happening
