### ISSUE TITLE
Document Viewer | Can't add comments if the list of tags is big

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2016]
# Description
When there are a bunch of tags; the Add/Delete/Edit Comment functionality scrolls off screen

## Reproduction Steps

**Scenario 1 -**

1. Go to a document
1. Add a bunch of tags
1. Try to add comments
1. Try to edit comments
1. Be sad

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Comment scrolls]_**
![disappearcomments](https://cloud.githubusercontent.com/assets/18075411/26128663/32c02c58-3a5b-11e7-9d32-6b04b2d9e9f7.gif)

**Comment by kierachell** [comment]
![faceroflcoptertothekeyboard](https://cloud.githubusercontent.com/assets/18075411/26800452/5a02efec-4a07-11e7-9764-9ee4a1b7b36a.gif)
more fun

**Comment by mdbenjam** [comment]
This should no longer be a problem.

**Comment by kierachell** [comment]
**PASSED**
SCROLLBARS FOR THE WIN
<img width="405" alt="screen shot 2017-08-10 at 5 34 55 pm" src="https://user-images.githubusercontent.com/18075411/29193203-44aab1a6-7df2-11e7-9bbb-7efc6cae0361.png">
