### ISSUE TITLE
Document List | Receipt date sort

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2018]
## Description
Currently the receipt date sort is defaulted from oldest to newest but we heard from user research that they usually start from newest to oldest

## AC
- [ ] Verify that search is defaulted from newest to oldest

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome

Steps to Validate: 
1. Access a veteran's documents in Reader. (Must have more than 2)
2. Validate that the Receipt Date has a arrow facing up (UI indicator that the sort is on)
3. Manually validate that the order of the documents is by newest Receipt Date to oldest. 

Screenshots: 
<img width="1107" alt="screen shot 2017-06-01 at 10 07 11 am" src="https://cloud.githubusercontent.com/assets/23038505/26683859/40db9dc2-46b3-11e7-8929-4d2ea7e41c89.png">
