### ISSUE TITLE
Document List | Infinite recursion breaks Internet Explorer and causes BaseContainer errors

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2021]
# Description
When anyone uses IE to view Document List,
The browser or whatever runs out of stack space on render - probably due to infinite recursion

## Reproduction Steps

**Scenario 1 -**

1. Get IE
1. Go to Reader with 100+ documents
1. Watch sentry
1. Watch page barely load

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [X] Prod

## Logs:

```
ReactOnRails encountered an error while rendering component: BaseContainer.
Original message: Out of stack space
```

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/212/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/228/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/269/

## Screenshots
**_Scenario 1 - [Empty list]_**
<img width="1003" alt="screen shot 2017-05-17 at 8 59 53 am" src="https://cloud.githubusercontent.com/assets/18075411/26154874/4254adcc-3adf-11e7-82db-10826e5f41e8.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by NickHeiner** [comment]
@abbyraskin please let us know if this is worth fixing.

**Comment by abbyraskin** [comment]
@NickHeiner we aren't officially supporting IE, so I would say no. cc: @mdbenjam

**Comment by NickHeiner** [comment]
Cool. In that case I vote to close this for now.

**Comment by tejans24** [comment]
As discussed on Slack with @mdbenjam , we might need to looking catching this error and not letting it get to sentry as we are working on fixing this issue for IE.
