### ISSUE TITLE
Document Viewer | Add download functionality

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#2022]
**Story**
When reviewing documents, I want to download occasionally so I can print specific pages for my VLJ on request.

## Acceptance Criteria
- Verify that the download icon appears to the right of the zoom icons on the to toolbar
- Selecting download icon downloads the current document with default document type and ID 

## Design
[Download icon in white](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Download.svg)

![image](https://cloud.githubusercontent.com/assets/13420618/26124831/ec504508-3a4d-11e7-9bb6-95ca4715c25d.png)

## Related Story
#1996 - Top Toolbar Redesign

**Comment by mmlumba** [comment]
Original AC for 2: `Selecting download icon downloads the current document with default filename as given by browser`

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Access a document
3. Validate the download button in the top toolbar. 

Screenshots: 
<img width="1003" alt="screen shot 2017-06-01 at 3 28 36 pm" src="https://cloud.githubusercontent.com/assets/23038505/26697477/3278d65a-46e0-11e7-82a4-8989606ae7c7.png">
