### ISSUE TITLE
Add cancelled EP manager page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2030]
As a manger, I would like to see the recently cancelled EPs. This new page should use the same styling as the missing decision page.

AC:
- Shows all cancelled tasks in the last 5 weeks
- Cancelled tasks are ordered by most recent first
- Table columns include:  Vet name (Vet ID), decision type, 
decision date, cancel date, and cancel reason

**Comment by lakohl** [comment]
@JD is decision date from VBMS or VACOLS?

**Comment by joofsh** [comment]
@lakohl We use the VACOLS decision date throughout Dispatch, so for consistency I think we should continue to use that.

**Comment by kierachell** [comment]
**PASSED**
<img width="971" alt="screen shot 2017-05-30 at 6 59 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/26608573/4e471486-456a-11e7-8285-8261fae20b46.png">
