### ISSUE TITLE
ARC Manager View - Add link to cancelled tasks page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2031]
As a manager, I would like to be able to easily navigate from my main page to the cancelled tasks page

## AC 
1. Add the h2 'BVA Reporting'
1. Add a link to open the Cancelled task page in a new tab

## Mock
<img width="610" alt="screen shot 2017-05-22 at 2 01 43 pm" src="https://cloud.githubusercontent.com/assets/4975959/26322277/34bcd5a0-3ef8-11e7-8b1a-0af980d953c2.png">

**Comment by lakohl** [comment]
until we find a more elegant solution...

<img width="578" alt="screen shot 2017-05-22 at 9 58 14 am" src="https://cloud.githubusercontent.com/assets/4975959/26312389/63b45f22-3ed5-11e7-8db5-d023443fbee6.png">

**Comment by slj** [comment]
For consistency, going with link "View Canceled Tasks" instead of "...Cancelled..."

**Comment by slj** [comment]
Solution in action (Connects #2030 as well):

![link_to_canceled_eps](https://cloud.githubusercontent.com/assets/1053255/26601745/0bca8a7c-454f-11e7-9992-160e63879e24.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Dispatch as a manager after tasks have been completed. 
2. Validate the link for canceled EPs has been created

Screenshots: 
![caseflow dispatch](https://cloud.githubusercontent.com/assets/23038505/26646221/d4f53dca-4608-11e7-874a-449f9216f4b6.png)
