### ISSUE TITLE
Create Hearings Worksheet table & API

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2032]
Create hearings worksheet table with all fields savable in hearings worksheet (see designs)

Create read/save API endpoints to connect to frontend

AC:
- Hearing & Issue tables are created/updated
- persisting VACOLS fields like rep name & issues will be handled in **future tickets**

Raw Notes:
Fields:
- Rep Name: Pull from VACOLS hearing record, editable, persisted back to VACOLS
- Witness: new
- Issues:
  - Note: Pulled from VACOLS, editable, persisted back to VACOLS  **future ticket**
  - (Allow, Deny, Remand, Dismiss) checkboxes that are mutually exclusive, new
  - Reopen, VHA checkboxes, new
- Periods & circumstances of Service, text, new
-  contentions, text, new
- evidence, text,  new
- comments and special instructions to attorney , new

**Comment by joofsh** [comment]
@kierachell For now QA can just be: 
1) Did the new columns get added to hearings, did the new issue table get created?

**Comment by kierachell** [comment]
- can we have the PR for this...just for context?

## New columns in Hearings
```
 Hearing Load (1.4ms)  SELECT  "hearings".* FROM "hearings"  ORDER BY "hearings"."id" DESC LIMIT 1
[2017-06-02 19:21:09 -0400]   Hearing Load (1.4ms)  SELECT  "hearings".* FROM "hearings"  ORDER BY "hearings"."id" DESC LIMIT 1
=> #<Hearing id: 683, user_id: nil, appeal_id: nil, vacols_id: "306138", worksheet_witness: nil, worksheet_contentions: nil, worksheet_evidence: nil, worksheet_military_service: nil, worksheet_comments_for_attorney: nil>
```

## Issue table:
```
  Issue Load (1.1ms)  SELECT  "issues".* FROM "issues"  ORDER BY "issues"."id" DESC LIMIT 1
[2017-06-02 19:22:30 -0400]   Issue Load (1.1ms)  SELECT  "issues".* FROM "issues"  ORDER BY "issues"."id" DESC LIMIT 1
=> #<Issue id: 1, appeal_id: nil, vacols_sequence_id: nil, hearing_worksheet_status: nil, hearing_worksheet_reopen: false, hearing_worksheet_vha: false>
```

## Ticket says "pulled from VACOLS" but that's not actually happening yet...

**Comment by joofsh** [comment]
@kierachell Sorry about that, I've linked the relevant PR. A lot of what was originally in this ticket was more raw notes, I've moved them to a separate section and created real AC to validate against

**Comment by joofsh** [comment]
@kierachell hey moving this back to in validation finally (sorry about that!). I updated the original AC per your wise suggestion :)

**Comment by kierachell** [comment]
**PASSED**

<img width="1207" alt="screen shot 2017-06-16 at 12 57 33 pm" src="https://user-images.githubusercontent.com/18075411/27236538-61bc6b20-5293-11e7-8d1e-7cd233c36eb6.png">
