### ISSUE TITLE
Create page for judge to save their "VLJ ID"

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2033]
As a judge, I want to be able to save my "VLJ ID" to the Caseflow database

AC:
- Create new page a `/hearings/user`
- User is able to enter their "VLJ ID"
- Upon submit, if the input is empty they receive an error "Please enter a valid VLJ ID"
-  For now, on submit do nothing but redirect to the main `/hearings/docket` page

**Comment by lakohl** [comment]
@annienguyenUSDS This is a page for judges to sign in with their VLJ number, the first time they use Hearing Prep, so we can feed them the proper schedule.

**Comment by joofsh** [comment]
@annekainicUSDS @lakohl hey sorry to get to this so late, it looks like we don't actually need this page anymore. The 2FA update to VACOLS means we now have a way to directly link a user in our system to VACOLS. We no longer need to look up their VLJ ID one time (we can instead use their css_id). 

I'm going to close this ticket

**Comment by lakohl** [comment]
OK. Cool. I think you meant to flag @annienguyenUSDS !
