### ISSUE TITLE
Create "Daily Docket" page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2037]
As a judge, I would like to see a list of all my hearings for a given docket day. 

AC:
- Navigating to `/hearings/dockets/<YYYY-MM-DD>` will show a list of hearings for the current user on that given date
- Page is visually rendered properly with the correct information
- No click interaction is needed (no saving, etc), other than the link at the bottom back to hearing schedule

Technical Notes:
- This new page should exist within the Hearings React SPA
- For now, all inputs should be unconnected. (not hooked up to redux or react state)
- No need to implement the saving interface

## Mock
**NOTE:** This is outdated.  On the right, "Saved at..." is "Last saved..." and italicized, as specified [here](https://va-gov.invisionapp.com/d/main/#/console/11372263/240352627/preview)

![virtual docket web revised 1](https://cloud.githubusercontent.com/assets/4975959/26310235/1bbe3f14-3ece-11e7-8d47-0f8f9073dded.png)

**Comment by lakohl** [comment]
LK to add dropdown info and Save button

**Comment by lakohl** [comment]
I've been thinking about how to save updates to the docket - I wonder if we couldn't do something similar to gmail. e.g.  The system automatically saves 3 seconds after a user stops typing in a notes field or after they select from a dropdown and they are messaged accordingly in the top right of the page.
This would be my first choice.

<img width="776" alt="screen shot 2017-05-22 at 9 24 05 am" src="https://cloud.githubusercontent.com/assets/4975959/26310892/7020b7d8-3ed0-11e7-90ac-e570005549f4.png">

<img width="730" alt="screen shot 2017-05-22 at 9 20 29 am" src="https://cloud.githubusercontent.com/assets/4975959/26310919/7f0ba992-3ed0-11e7-9042-3b0b8a6a86e7.png">

**Comment by lakohl** [comment]
Saving option 2, requires the user to click an update button:

<img width="758" alt="screen shot 2017-05-22 at 9 28 37 am" src="https://cloud.githubusercontent.com/assets/4975959/26311110/19b32ae2-3ed1-11e7-821b-e188a7e4f519.png">

<img width="710" alt="screen shot 2017-05-22 at 9 30 56 am" src="https://cloud.githubusercontent.com/assets/4975959/26311191/65fc668e-3ed1-11e7-80ed-3aa35e177286.png">

**Comment by lakohl** [comment]
@joofsh see saving options above

**Comment by joofsh** [comment]
@lakohl I think option 1 is the better UX. It's more complex but I think worth it in this case given the page length. Working on a similar UI in the past, we implemented option 1 and people still wanted a hard save button (though it essentially did nothing). Just something to keep in mind if we go down this path

**Comment by lakohl** [comment]
@joofsh I agree, and understand your point. I like the first version too bc there is better feedback. Let's try without the fake button first, if need be we could have a button and feedback.

**Comment by slj** [comment]
@lakohl / @laurjpeterson  I'm concerned about the appearance of Saving.../Last saved at.

The original mock asks for a bold text like the table headers but a slightly lighter color.  I think it should stand out more, perhaps with both a different color and an italic font, like so:
![daily_italics](https://user-images.githubusercontent.com/1053255/27964864-b2906522-6307-11e7-8cbd-f9d26ae821e3.gif)


Thoughts?

**Comment by slj** [comment]
Here's a sample with a slightly smaller font using Arial as the face:
![daily_bold_italics_arial](https://user-images.githubusercontent.com/1053255/27967260-5c1fb432-6310-11e7-90bb-7aa6f6ae496b.gif)

**Comment by lakohl** [comment]
We actually have 'saving' in italic in later versions, so that is fine. But we should stick to colors and type faces from the style guide. I'm concerned that lighter grays may not be 508 compliant, but if you find one in the USWDS that is, I'm game to take a look.



Sent with Good (www.good.com)


-----Original Message-----

**Comment by slj** [comment]
@lakohl in the mock at the very top, the Representative column has two values, the first, based on my experience, is the name of the representative organization (VFW).  What value is "Patrick O'Sullivan"?

**Comment by lakohl** [comment]
Patrick O'Sullivan is the name of the Representative

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome

Steps to Recreate: 
1. Access a css login that doesn't have a "nil" vacols_id
2. Toggle on the "Hearings" feature
3. Enable the "Hearings" function
4. Access the daily docket page from one of the dates found on the Docket page for Hearings prep. Format: /hearings/dockets/YYYY-MM-DD

Screenshots: 
![dailydocket](https://user-images.githubusercontent.com/23038505/28276856-273a14b4-6ae6-11e7-9705-5a3a2e220d32.png)
