### ISSUE TITLE
ARC Work Assignments | Cases remaining can be negative?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2038]
# Description
When assigning tasks to a Caseworker who already completed their queue, it is possible to assign less than they've done which then displays negative values for **Cases Remaining**

## Reproduction Steps

**Scenario 1 -**

1. Go to Dispatch as a Caseworker
1. Do some work
1. Go to Dispatch as Manager
1. Assign 0 cases to that Caseworker
1. Scratch head.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Weirdness]_**
<img width="1019" alt="screen shot 2017-05-18 at 11 08 46 am" src="https://cloud.githubusercontent.com/assets/18075411/26209333/7eadf40a-3bba-11e7-8e2f-6851c154f4f0.png">

# Related Issues

**_Engineering_**
#1690

**Comment by lakohl** [comment]
Cases remaining should not be allowed to be negative. @kierachell is this still happening?

**Comment by kierachell** [comment]
Can probably close this, it's 2 months old so who knows...

Here's a more current issue:
https://github.com/department-of-veterans-affairs/caseflow/issues/2719

**Comment by lakohl** [comment]
closing
