### ISSUE TITLE
ARC Work Assignments | Assigning less than total amount of tasks changes the total in the header

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2039]
# Description
Assigning less than total amount of tasks changes the total in the header:

## Reproduction Steps

**Scenario 1 -**

1. Go to Dispatch
1. Have a queue of X cases
1. Assign a bunch of tasks to add up to less than X
1. See the total change to less than X

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod
## Screenshots
**_Scenario 1 - [Good Total]_**
<img width="577" alt="screen shot 2017-05-18 at 11 15 34 am" src="https://cloud.githubusercontent.com/assets/18075411/26209688/7f5ce568-3bbb-11e7-8236-2126e35d1b23.png">

**_Scenario 1 - [Bad Total]_**
<img width="541" alt="screen shot 2017-05-18 at 11 15 46 am" src="https://cloud.githubusercontent.com/assets/18075411/26210835/e4da63ea-3bbe-11e7-8a8b-b35402c0e608.png">

# Related Issues
**_Engineering_**
#1690 
#2038

**Comment by lakohl** [comment]
This is no longer happening as far as I can tell @kierachell can you verify?
