### ISSUE TITLE
ARC Work Assignments | Customizing multiple quotas only updates one

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2041]
# Description
When a Manager wants to customize multiple quotas at a time,
Only one of them will actually be saved

## Reproduction Steps

**Scenario 1 -**

1. Go to Manager page
1. Click to edit multiple quotas
1. Select all the pretty numbers
1. Click save and see only one saved

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Huh?]_**
![numbersaves](https://cloud.githubusercontent.com/assets/18075411/26211060/88662904-3bbf-11e7-8532-5e57aa06fcd8.gif)

# Related Issues
**_Support_**

**_Engineering_**
#1690

**Comment by lakohl** [comment]
@kierachell It's not a global 'Save' function. It only saves the changes in that line.

**Comment by lakohl** [comment]
verify when https://github.com/department-of-veterans-affairs/caseflow/issues/4245 is complete

**Comment by lakohl** [comment]
users can now only type numbers
