### ISSUE TITLE
Add current user as VLJ to Hearing Schedule page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2045]
On the dockets list view, I want to see that the current VLJ is myself.
@joofsh fails at AC

@astewarttistatech 
You can use CF_Q_317 user to access this page in UAT

Technical Notes:
- Create a User model `to_hash`
- Pass current user from backend to React

ACTUAL AC:
- Login as CF_Q_317
- Visit `/hearings/dockets`
- Currently logged in user's name shows up as VLJ in docket list view

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Login with indicated user
2. Access /hearings/dockets/

Screenshots: 
<img width="1033" alt="screen shot 2017-05-30 at 12 52 56 pm" src="https://cloud.githubusercontent.com/assets/23038505/26594782/0b87f878-4537-11e7-8589-f7c3c42660f1.png">
