### ISSUE TITLE
[5] Confirm Case Details Front-end Step 3: Add ability to enter new POA information.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2046]
After we display the POA information on the Confirm Case Details page from BGS and VACOLS, and after we've implemented the option to choose whether BGS or VACOLS is correct, then let's implement a feature that gives the user the ability to enter in new POA information.

### Acceptance Criteria ###
- If "None of the above" is selected on the question "Which information source shows the correct representative for this appeal?", a question appears with text "What type of representative did the appellant request for this appeal?" and corresponding radio options: "Attorney", "Agent", "Service Organization", "None", and "Other".

- If "Attorney" or "Agent" is selected, display this text: "Since you selected ____ [Attorney or Agent, depending on the selection], make sure you update the representative’s name and address information in VACOLS before continuing.  Caseflow will update the representative type in VACOLS."

- The following options should appear in the dropdown if "Service Organization" is selected:
```
    "The American Legion" 
    "AMVETS" 
    "American Red Cross" 
    "Disabled American Veterans" 
    "Jewish War Veterans" 
    "Military Order of the Purple Heart" 
    "Paralyzed Veterans of America" 
    "Veterans of Foreign Wars" 
    "State Service Organization(s)" 
    "Maryland Veterans Commission" 
    "Virginia Department of Veterans Affairs"  
    "Navy Mutual Aid Association" 
    "Non-Commissioned Officers Association" 
    "Other Service Organization" 
    "Army & Air Force Mutual Aid Assn." 
    "Catholic War Veterans" 
    "Fleet Reserve Association" 
    "Marine Corp League" 
    "Vietnam Veterans of America"
    "American Ex-Prisoners of War"
    "Blinded Veterans Association"
    "National Veterans Legal Services Program"
    "National Veterans Organization of America"
    "Wounded Warrior Project"
    "Unlisted service organization"
```

Once a service org is selected, this message appears: "Great! Caseflow will update the representative type, name, and address information for the selected service organization in VACOLS."

- If "Unlisted service organization" is selected, a free text field called "Service organization name" should be displayed. Text that says "Since you selected an Unlisted service organization, make sure you update the representative’s address information in VACOLS before continuing.  Caseflow will update the representative type and name in VACOLS." is also shown below the free text field.
- If "Service organization name" is filled out by the user, the user should be able to click continue and move to the next page. 
- If "None" is selected,  the user should be able to click continue and move to the next page.
- If "Other" is selected, a message appears: "Since you selected Other, make sure you update the representative’s name and address information in VACOLS before continuing.  Caseflow will update the representative type in VACOLS."
- "representative type" and "representative_name" should be updated based on user input
 
### Mocks ###

There's a typo in these mocks FYI: "contact informatin" should be "address information", as noted above.

If "Other" is selected:
![poa 3 step 4](https://cloud.githubusercontent.com/assets/1178390/26292987/80a616ea-3e88-11e7-97af-df72b8f96670.png)

If "Attorney" is selected: (Same text appears for "Agent", except "Agent" replaces "Attorney"):
![poa 3 step 5](https://cloud.githubusercontent.com/assets/1178390/26292994/85c264f8-3e88-11e7-8225-9c7f05b3c6bb.png)

If "Service organization" is selected:
![poa 3 step 6](https://cloud.githubusercontent.com/assets/1178390/26293000/8cde0580-3e88-11e7-89a2-7907ebbb2f6c.png)

If "Service organization" is selected and name of service org is in the dropdown:
![poa 3 step 9](https://cloud.githubusercontent.com/assets/1178390/26293352/08a9c220-3e8a-11e7-8f28-163386ace6c3.png)

If "Service organization" is selected and name of service org is **not** in the dropdown, user selects "Unlisted service organization" and manually enters the name of the service org:
![poa 3 step 8](https://cloud.githubusercontent.com/assets/1178390/26293014/a0c048a6-3e88-11e7-863c-f00a5afd6794.png)

**Comment by amprokop** [comment]
@shellicious — can you take a pass here and update any of the text if it's not what we want? I sorta did it from memory :)

**Comment by nemodjuric** [comment]
"One Time Representative" is missing from "Service Organization" list comparing what I found in case.rb for REPRESENTATIVES. Was this intentional? 
@amprokop @shellicious

**Comment by amprokop** [comment]
@nemodjuric — thanks for raising this. you're right, one time representative is missing. Yes, this was intentional — we expect users will select "Other" from the radio button group under "What type of representative did the appellant request" if the rep is a one time representative. However, it's probably a decision worth reconsidering at some point. @shellicious, this is still what we want right?

**Comment by kierachell** [comment]
## It was all going so well, until...

American Legion is the default value and it seems like *Contiunue* button expects value to be changed before proceeding
![defaultselect](https://user-images.githubusercontent.com/18075411/26957358-7608a7d0-4c92-11e7-969f-f6b2fc72ccc4.gif)

**Comment by nemodjuric** [comment]
There is an issue for default value that will be pushed out tomorrow (since Dropdown component did not support default Value at the time and it was broken into separate issue). #2259

**Comment by kierachell** [comment]
Feel free to change the AC and mention that in there

**Comment by amprokop** [comment]
@nemodjuric — can we set a character limit on the organization name here? Let's do 40 characters for now.

**Comment by shellicious** [comment]
@amprokop @nemodjuric: Yes, One Time Representative is not currently in the dropdown, since a one time rep is not the same as a service organization. We'll see how usability testing goes. We might have to change the radio button options, or change the way "Other" works if many people are confused.

**Comment by kierachell** [comment]
**PASSED**

<img width="1134" alt="screen shot 2017-06-13 at 8 29 28 am" src="https://user-images.githubusercontent.com/18075411/27106252-8f92ac42-5060-11e7-834d-55e879f2c939.png">
<img width="821" alt="screen shot 2017-06-13 at 8 29 53 am" src="https://user-images.githubusercontent.com/18075411/27106253-8f93296a-5060-11e7-8ff2-f412172f06ca.png">
