### ISSUE TITLE
Show a banner asking the user to do two Form 8s for two Appeals

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#205]
Perhaps with a link to the OFO guidance

**Comment by shanear** [comment]
assigning to @KHarshawat, for the deets on what this should say

**Comment by shellicious** [comment]
@KHarshawat, can you provide context on a. what user problem this is solving, b. about how often does this situation happen, and c. what are the negative consequences of not fixing this?

**Comment by nikitarockz** [comment]
@KHarshawat Under what circumstances would this occur? Why would the need to do 2 form 8s?

**Comment by laurjpeterson** [comment]
no longer relevant now that certification v2 has been launched
