### ISSUE TITLE
[1] Confirm Case Details front-end Step 1: Display mock POA information from BGS and VACOLS

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2052]
Let's display mock POA information from BGS in VACOLS to get the styling right.

Let’s put mock values in “mapDataToInitialState” so all we need to do is pass them from the server to the client when we hook it up. From the server, these values will be called`bgs_representative type` (let's hardcode to "Attorney"), `bgs_representative_name` (let's hardcode to "Anne Merica"), `vacols_representative_type` (let's hardcode to "Veterans Service Organization", and `vacols_representative_name` (let's hardcode to "Navy Mutual Aid Association").

### Acceptance Criteria ###
- VBMS and BGS POA data (name and type) should appear on the page with a layout matching the mock.
- Mock data will be used.

### Mock ups ###

![poa 3 step 1](https://cloud.githubusercontent.com/assets/1178390/26292780/bf3a3c94-3e86-11e7-8a71-154456c4f6dc.png)

**Comment by amprokop** [comment]
@shellicious — can you add a link to the appropriate wireframe?

**Comment by kierachell** [comment]
@amprokop 
`@poas[file_number] ||= get_poa_from_bgs_poa(bgs_poa)` seems to be causing errors:
```
NoMethodError (undefined method `[]' for nil:NilClass):
app/services/external_api/bgs_service.rb:44:in `fetch_poa_by_file_number'
app/models/power_of_attorney.rb:31:in `load_bgs_record!'
app/models/appeal.rb:93:in `power_of_attorney'
app/models/certification.rb:29:in `fetch_power_of_attorney!'
app/controllers/certifications_controller.rb:14:in `new'
app/middleware/metrics_collector.rb:14:in `call'
app/middleware/metrics_auth.rb:10:in `call'
```
## BGS response _does_ happen:
```
<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXdUAB13ZWJsb2dpYy5hcHAuQ29ycG9yYXRlRGF0YUVBUgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQABjEwLjIuMAAA</work:WorkContext></S:Header><S:Body><ns2:findPOAsByFileNumbersResponse xmlns:ns2="http://org.services.vetsnet.vba.va.gov/"><return><fileNumber>516517690</fileNumber><powerOfAttorney><legacyPoaCd>095</legacyPoaCd><nm>ITALIAN AMERICAN WAR VETERANS OF THE US, INC.</nm><orgTypeNm>POA National Organization</orgTypeNm><ptcpntId>45994</ptcpntId></powerOfAttorney><ptcpntId>600161064</ptcpntId></return></ns2:findPOAsByFileNumbersResponse></S:Body></S:Envelope>
```

**Comment by kierachell** [comment]
**PASSED**

using real data now:
<img width="1033" alt="screen shot 2017-06-02 at 11 43 50 am" src="https://cloud.githubusercontent.com/assets/18075411/26736554/a2830204-4794-11e7-8fcb-4c3207e9b5e6.png">
