### ISSUE TITLE
[3] Confirm Case Details Front-end Step 2: Indicate whether POA info matches or choose which one is correct

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2054]
We want to let the user choose which POA information is correct from BGS or VACOLS.

### Acceptance Criteria ###
- VBMS and BGS POA data (name and type) should appear on the page with a layout matching the mock.
- On pageload, a question appears with text: "Does the representative information from VBMS and VACOLS match? Answer yes if the only differences are due to typos or differences in punctuation." 
and corresponding radio options: "Yes", "No".
  - If Yes is selected, the user should be able to click "Continue" and navigate to the next page.
  - If No is selected, a question appears with text "Which information source shows the correct representative for this appeal?" and corresponding radio options: "VBMS", "VACOLS", "None of the above"
    - If "VACOLS" is selected, the user sees text that says, "Great! Caseflow will keep the representative information as it exists now in VACOLS." The user should be able to click "Continue" and navigate to the next page.
    - If "VBMS" is selected, the user sees text that says, "Great! Caseflow will update the representative name, type, and address in VACOLS with information from VBMS."  The user should be able to click "Continue" and navigate to the next page.
    - If “None of the above” is selected, the user sees the message “Please go to VACOLS and manually enter the correct representative information.”
- Upon clicking continue and continuing to the next pace, the values that the user chose are populated to the DB as `representative_type` and `representative_name`.
- New columns in the DB for `poa_matches?` and `poa_correct_in_vacols` should be added, and their values should be populated.

### Mocks ###
![poa 3 step 1](https://cloud.githubusercontent.com/assets/1178390/26292802/e729a5e6-3e86-11e7-9243-effb3b5e24f4.png)

![poa 3 step 2](https://cloud.githubusercontent.com/assets/1178390/26292807/eeff4eec-3e86-11e7-8f3d-b774ca9f692e.png)

**Comment by amprokop** [comment]
@shellicious — can you look over this text and update where necessary (I made up the question text so it's probably not exactly what we want)

**Comment by shellicious** [comment]
@amprokop updated! 

In the flow we've been discussing, when "None of the above" is selected, the user is prompted to enter the representative type (Attorney/Agent/Service org/etc.) via radio buttons. This ticket says that they'll be instructed to go to VACOLS instead. Is that because this ticket is for an MVP in which Caseflow doesn't ask users to input representative type, or is it because this ticket is out of date?

**Comment by shellicious** [comment]
oh nvm, I just saw https://github.com/department-of-veterans-affairs/caseflow/issues/2046 which answers my question

**Comment by kierachell** [comment]
## Are we handling going back and editing values?
![poaselect](https://cloud.githubusercontent.com/assets/18075411/26707495/49a473ba-4713-11e7-9426-6c0f87e8483c.gif)

1. Select "Matches"
1. Click *Continue*
1. Go back
1. Select "Not Matches"
1. Select "VBMS" <- sets value to `true`
1. Click *Continue*
1. Go back
1. Click "Matches"
1. Click *Continue*
1. Observe that `poa_correct_in_bgs?` is still true.

**Comment by kierachell** [comment]
**PASSED**
@nemodjuric is the man!
![clear values](https://user-images.githubusercontent.com/18075411/26948339-fc07ae6e-4c63-11e7-8b3f-8739e6ca3311.gif)
## Skipping still fails, which is good!
```
Caseflow::Error::CertificationMissingData (Caseflow::Error::CertificationMissingData):
  app/controllers/certifications_controller.rb:105:in `validate_data_presence_v2'
  app/controllers/certifications_controller.rb:50:in `certify_v2'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```
