### ISSUE TITLE
Change Judge Schedule column to reference regional_office

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2057]
Instead of showing the field office (where the hearing will be held), instead show the regional office

## AC
1. Verify that the column header is changed from 'Field Office' to 'Regional Office'.
1. Verify that the [city, state] (e.g. Newark, NJ) of the Regional Office holding the hearing is displayed in each date row.

## Mock
<img width="709" alt="screen shot 2017-05-26 at 4 29 36 pm" src="https://cloud.githubusercontent.com/assets/4975959/26511715/46fe144a-4231-11e7-8b15-99249f15844c.png">

**Comment by sharonwarner** [comment]
I'll add the constants for reference.

**Comment by slj** [comment]
I can just use `Appeal#regional_office`, no?

**Comment by sharonwarner** [comment]
@slj yeah, that sounds good!

**Comment by kierachell** [comment]
## Verify that the [city, state] (e.g. Newark, NJ) of the Regional Office holding the hearing is displayed in each date row.


Looks like that value has more than State in it. 
<img width="1278" alt="screen shot 2017-07-03 at 4 25 41 pm" src="https://user-images.githubusercontent.com/18075411/27807046-4ccdd15a-600c-11e7-8273-85ab433c4e97.png">


## Also the mock has title `Hearing Schedule` not `Hearings` - which one is right?

**Comment by kierachell** [comment]
**PASSED**
<img width="1204" alt="screen shot 2017-07-05 at 1 45 14 pm" src="https://user-images.githubusercontent.com/18075411/27877347-406102b6-6188-11e7-90e1-d50145cf5cdd.png">
