### ISSUE TITLE
Fix link on mismatched documents page

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2058]
I think `<a href="/help#mismatched-documents”>` -> `<a href=“/help/certification#mismatched-documents”>` should do it

### Acceptance Criteria ###
-The "labeled correctly" link on the mismatched documents Certification page leads the user to the section of the help page that deals with mismatched documents

**Comment by kierachell** [comment]
**PASSED**
<img width="918" alt="screen shot 2017-05-26 at 12 36 26 pm" src="https://cloud.githubusercontent.com/assets/18075411/26503765/f6162d68-420f-11e7-9a1f-d1631c7c8df5.png">
