### ISSUE TITLE
Ensure that V2 users cannot navigate to V1

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2059]
If the feature toggle is on for v2, the v1 routes should not work!

### Acceptance Criteria ###
- The user cannot navigate to v1 routes if v2 is enabled
  - Example: `/certifications/XXX` leads the user to the Form 8 PDF. it shouldn't work in V2.

**Comment by mmlumba** [comment]
@amprokop Typing in `/certifications/XXX` leads to a JSON object for that certification. Would that technically pass the AC?

**Comment by amprokop** [comment]
Yes.
