### ISSUE TITLE
[3] POA Backend Step 2: Save POA address from BGS and return `bgs_address_found?` to client

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2061]
For V2, we want to use the endpoint added in https://github.com/department-of-veterans-affairs/ruby-bgs/pull/34 to find the address of any representative with a participant id, and also handle the cases where we can't find an address.

For VSOs, we don't expect address information to be present in the BGS API—based on our conversations with BGS, there will likely be no participant id for the power of attorney if it's a VSO. Let's doublecheck this by finding some UAT data.

We also need to handle the possible case where address information for some attorneys/agents is not found.  Let's raise an exception to Sentry when we don't find an address where there is a participant id.

We should add fake data in our fake services or unit tests that handle all these cases.

### Acceptance Criteria ###
- Before certification starts, we should fetch address information from the BGS API for the current BGS POA and save it in our db
- A true/false `bgs_poa_address_found?` flag should be passed down to the client. If the rep address was successfully found, the flag should be true, else false.
- Cases where we can't find the address with the participant id or cases where there is no participant id should be handled gracefully and not cause errors.

**Comment by kierachell** [comment]
You might be getting 
```
Savon::SOAPFault: (S:Server) AddressWebService-->findPtcpntAddrs-->findPersonByPtcpntId-->No Person found for ptcpnt_id 12925992
from /Users/vhaisavovka/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
```
As they are not really handled at `ruby-bgs` level right now

**Comment by kierachell** [comment]
### Ruby-bgs is causing Sentry errors when `no person found for participant id`:
https://10.236.66.249/sentry/caseflow-uat/issues/245/
```
Savon::SOAPFault: (S:Server) AddressWebService-->findPtcpntAddrs-->findPersonByPtcpntId-->No Person found for ptcpnt_id 600156025
```
- from:
```
bgs_address = MetricsService.record("BGS: fetch address by participant_id: #{participant_id}",
                                          service: :bgs,
                                          name: "address.find_by_participant_id") do
        client.address.find_by_participant_id(participant_id)
      end
```
This is not "breaking" the process, but will explode sentry with 500s.

**Comment by amprokop** [comment]
@kierachell — this error is handled here. It should not block the user though it will be sent to Sentry (<- is this true in your experience?). I'd actually like to know how often this happens in production, so I'd prefer to keep it as a Sentry error at least at first so we have maximum visibility. What do you think?

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/power_of_attorney.rb#L46

**Comment by amprokop** [comment]
To reiterate, we want to make sure that this error will not block the user, but if it's sent to Sentry, that's fine for now (we actually don't know how often it will happen in production)

**Comment by aroltsch** [comment]
blocked by #1894

**Comment by amprokop** [comment]
@kierachell @aroltsch — this is complete, not blocked. As long as the error on `client.address.find_by_participant_id(participant_id)` does not block the user, we're fine with it showing up in Sentry for now.

**Comment by kierachell** [comment]
**PASSED**
The call happens at the start:
```
[2017-06-08T07:11:15.808081 #2956] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXdUAB13ZWJsb2dpYy5hcHAuQ29ycG9yYXRlRGF0YUVBUgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQABjEwLjIuM
AAA</work:WorkContext></S:Header><S:Body><ns2:findPOAsByFileNumbersResponse xmlns:ns2="http://org.services.vetsnet.vba.va.gov/"><return><fileNumber>141102021</fileNumber><message>No POA found for 600113621</message><ptcpntId>600113621</ptcpntId></return></ns2:findPOAsByFileNumbersResponse></S:Body></S:Envelope>
```

<img width="428" alt="screen shot 2017-06-08 at 7 13 40 am" src="https://user-images.githubusercontent.com/18075411/26926071-157408ba-4c1a-11e7-8bf1-e605780a0140.png">
<img width="641" alt="screen shot 2017-06-08 at 7 13 51 am" src="https://user-images.githubusercontent.com/18075411/26926072-15743362-4c1a-11e7-9812-9d2eeaf2a2c7.png">
