### ISSUE TITLE
If address should be updated in VACOLS but we can’t find it in BGS, show the user a message saying so

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2063]
@shellicious — we need this, right? Wanna mock it out? Low-pri compared to other bgs stuff

**Comment by shellicious** [comment]
Variations to be decided upon:

![poa 3 step 3c](https://cloud.githubusercontent.com/assets/1178390/26293382/47c24752-3e8a-11e7-89f2-9f1ad4f12b3d.png)

![poa 3 step 3](https://cloud.githubusercontent.com/assets/1178390/26293384/47cc1804-3e8a-11e7-9a0d-9b2443632163.png)

![poa 3 step 3b](https://cloud.githubusercontent.com/assets/1178390/26293383/47c638da-3e8a-11e7-8744-e31bd2d3ca7c.png)

**Comment by amprokop** [comment]
Ah we need a copy change here. 

If we can't find the address in BGS and we're updating the REP table in VACOLS, when we certify,  we wipe the address in the REP table. So if the user updates the POA address manually in VACOLS before continuing, we'll wipe it on certification.

@shellicious @laurjpeterson  — we need to change it to say something like "After you certify this appeal" instead of "Before continuing".

**Comment by laurjpeterson** [comment]
"After you certify this appeal" sounds right to me.

I know we're not tackling the POA address quite yet with V2. But in the spirit of certification paving the way for accurate data down the line, if we go with this solution I'm thinking we'll also need a reminder for the user on the success page that we couldn't find the address in VBMS and they have to update the address in VACOLS after certification. 

Cc: @shellicious

**Comment by amprokop** [comment]
Ok, since it's the weekend we'll go with this for now. I can change it to whatever y'all want later

            `Caseflow could not find an address for the repnresentative in VBMS. After
             this appeal is certified in Caseflow, the representative’s address
             will need to be updated in VACOLS.`

**Comment by amprokop** [comment]
Take a look at this PR when you get a chance. Had to update more of the copy on this page due to the fact that the user shouldn't update POA address until after they certify. Happy to push up any tweaks.

https://github.com/department-of-veterans-affairs/caseflow/pull/2302
