### ISSUE TITLE
Enable breadcrumbs on Sentry

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2064]
Breadcrumbs are a really neat Sentry feature that will hopefully help us a lot in debugging! 

https://blog.sentry.io/2016/05/04/breadcrumbs.html

Evaluate whether we need to install Raven.js (we have the ruby raven). We might need to install Raven from NPM as well to use this.

**Comment by laurjpeterson** [comment]
@pkarman do you think we still need this ticket?
