### ISSUE TITLE
Enable source maps on UAT

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2067]
Let's enable source maps on UAT for faster debugging.

For webpack, we only have test/development/production NODE_ENVs currently. We need to add a UAT NODE_ENV so source maps are only enabled there.

Read: https://stackoverflow.com/questions/30870830/how-do-i-generate-sourcemaps-when-using-babel-and-webpack

After the deployment of this ticket, the dev should take a pass through UAT and ensure that it's not unbearably slow. we could consider "eval-cheap-module-source-map" too if we find UAT too slow after source maps.

**Comment by askldjd** [comment]
Sound sourcemap be enabled for demo or UAT? 

UAT in theory is our only deployment gate. It is risky to have configuration custom for this env.

For sure, enabling sourcemap will slow down site loading significantly.

**Comment by amprokop** [comment]
@askldjd — @kierachell is the main user of UAT, and he is willing to trade off speed for functionality here. Do you have an objection if we go through with this, then revert if we find it's problematic?

**Comment by amprokop** [comment]
@askldjd — what if we just set it as an ENV var and passed it down to the client, instead of having a new node env?

**Comment by nemodjuric** [comment]
It seems that we don't have source maps enabled in demo, would that do instead of UAT? @amprokop

**Comment by amprokop** [comment]
This is up to @kierachell, I'm guessing no though.

**Comment by kierachell** [comment]
I guess the better solution would be to: create a new `NODE_ENV` that can be used in demo? Then the `dev` can use the source maps - I assume JS errors will be mostly frontend anyway so we don't need a full integration to see them?

**Comment by joofsh** [comment]
+1 creating a new `NODE_ENV` for demo, with source maps on. I would prefer to keep them off on UAT if at all possible. It's important that UAT perfectly mirrors the build steps of production, otherwise we are flying blind moving into production. We should be able to catch most if not all JS errors on demo.

**Comment by amprokop** [comment]
Sure, that solution sounds fine, if @kierachell is happy with it.

**Comment by amprokop** [comment]
@nemodjuric looks like we can go with demo ^

**Comment by kierachell** [comment]
@sharonwarner made a redux logger too which can be taken out of prod env the same way? Is that correct?

**Comment by nemodjuric** [comment]
After looking into this and talking to few of you, the obvious solution is to have RAILS_ENV: demo 
Then in rails_on_react.rb, have something like if Rails.env.demo? then config.npm_build_test_command = "npm run build:test"
(Will check if config.npm_build_demo_command = "npm run build:test" would work). 
What everyone else thinks about this solution? 
@askldjd @amprokop @joofsh @mdbenjam @tejans24 @kierachell (please tag if I missed anyone)

**Comment by kierachell** [comment]
That should work 
👍 from me

**Comment by amprokop** [comment]
sounds good to me too!

**Comment by kierachell** [comment]
**PASSED**

Thank you @nemodjuric !!!!!

<img width="1211" alt="screen shot 2017-06-30 at 7 27 39 pm" src="https://user-images.githubusercontent.com/18075411/27757027-d1c2a136-5dca-11e7-81a5-84c28f041316.png">
<img width="1121" alt="screen shot 2017-06-30 at 7 32 01 pm" src="https://user-images.githubusercontent.com/18075411/27757028-d1c61c12-5dca-11e7-8e20-6917089bdb2b.png">
