### ISSUE TITLE
Document Viewer | Bottom tool bar redesign

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2075]
## Description
This is an overview of what the bottom tool bar redesign will look like. The AC has an outline of all the issues of each component. 

## AC
- [ ] Previous and next arrows #2076
- [ ] Ability to change page in document #1884
- [ ] Progress indicator #1973

## Mock up

![image](https://cloud.githubusercontent.com/assets/13420618/26259610/c010fa2c-3c97-11e7-875f-39627b96c56b.png)

## Related issue 
Accessibility: #1853

**Comment by NickHeiner** [comment]
So does this ticket have any actual work in it? Or is it entirely split out into sub tickets?

**Comment by gnakm** [comment]
@NickHeiner Yeah it's split out into sub tickets. We thought this might provide a better overview.

**Comment by NickHeiner** [comment]
Ok – I think I'd recommend closing this ticket then. Having the overall mock is helpful, but it's confusing for a ticket to have no work associated with it.
