### ISSUE TITLE
Document Viewer | New previous and next arrows

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2076]
**Description**
Currently, the arrows for going between pages cover some of the context on the doc viewer, especially when document is zoomed in. Moving the arrows to the bottom would be better usability for moving between documents and skimming/ reading content. 

## AC
- [x] Verify that the spacing for the arrows and text follow the mock
- [x] Verify that the older arrows in doc viewer are gone
- [x] Verify that selecting the left arrow navigates the user to the previous document, and the right arrow navigates the user to the next document

## Icons
- [Icon for Previous (arrow-left)](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/arrow-left.svg)
- [Icon for Next (arrow-right)](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/arrow-right.svg)

## Mock up 
![image](https://cloud.githubusercontent.com/assets/13420618/26268668/5fb85f40-3cbe-11e7-900a-cbfc0b2573d1.png)

## Related
- Accessibility #1851
- Padding for next and previous buttons #2258

**Comment by NickHeiner** [comment]
@gina do you want the arrow to have the same hover fill as the text?

![image](https://cloud.githubusercontent.com/assets/829827/26468726/77b2dc46-4165-11e7-9dbd-0e2d8d041004.png)

**Comment by gnakm** [comment]
@NickHeiner Yes on the having both text and icon hover fill and thanks you fixing mis-alignment in advance 😬

**Comment by NickHeiner** [comment]
Ha, @gnakm this is getting an accessibility test failure because of insufficient color contrast. Can you recommend an alternate color?

```
  1) Reader Large number of documents Open a document, navigate using buttons to see a new doc, and return to list
     Failure/Error: (num_documents - 1).times { find("#button-next").click }
     
     Sniffybara::PageNotAccessibleError:
       Elements must have a contrast ratio of above 4.5:1
     
       Elements:
       <span class="right-button-label">Next</span>
       ["#button-next > .right-button-label"]
     
       Issue ID: color-contrast-critical
       Impact: serious
       More Info: https://dequeuniversity.com/rules/worldspace/2.0/color-contrast?application=fireeyesFirefox
     # ./spec/feature/reader_spec.rb:622:in `block (4 levels) in <top (required)>'
     # ./spec/feature/reader_spec.rb:622:in `times'
     # ./spec/feature/reader_spec.rb:622:in `block (3 levels) in <top (required)>'
```

**Comment by gnakm** [comment]
Lawl. Of course. 

Could we do: #02bfe7
[Secondary state color from USWDS](https://standards.usa.gov/components/colors/#palette)

Needs to be added to style guide because our blues ain't working for contrast.

**Comment by NickHeiner** [comment]
Curiously, the color that caused the accessibility fail was the same color that we'd been using for other PDF toolbar buttons all along, like the "Back to all documents" button. I don't know why it only just now started triggering a warning. Maybe because the markup is slightly different?

All the more reason that the accessibility checker is not to be fully trusted; it's a nice tool but not the be-all-end-all.

**Comment by gnakm** [comment]
Hmm interesting. 

![image](https://cloud.githubusercontent.com/assets/13420618/26500012/77cee0b0-4202-11e7-8522-a4ec89356bc4.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26500041/8f0b5394-4202-11e7-835d-066f29c3feb0.png)

**Comment by kierachell** [comment]
- The space from the left arrow to the edge of the window is not the same as right arrow to edge of viewer
<img width="1056" alt="screen shot 2017-06-06 at 8 47 28 am" src="https://cloud.githubusercontent.com/assets/18075411/26829869/01034c46-4a95-11e7-8724-61b5d75c140c.png">

- Not sure what you wanted on hover color: 02bfe7 is what it is now. LGMT but wanted to confirm.
<img width="151" alt="screen shot 2017-06-06 at 8 48 57 am" src="https://cloud.githubusercontent.com/assets/18075411/26829870/01483db0-4a95-11e7-887e-57bdf5cd3b73.png">

**Comment by NickHeiner** [comment]
I think that @gnakm does want `#02bfe7`, based on her comment above.

@gnakm @abbyraskin I don't have time to fix the spacing issue. Please make a new issue / re-assign this one if you think it's worth fixing.

**Comment by gnakm** [comment]
@kierachell color is correct
@NickHeiner I will make the issue

**Comment by NickHeiner** [comment]
Thanks. @kierachell in that case, let's close this issue as-is, and the spacing issue will be fixed in @gnakm's followup.

**Comment by gnakm** [comment]
New issue here: #2258

**Comment by kierachell** [comment]
**PASSED**

cause what they said
