### ISSUE TITLE
Styleguide sticky navigation bar extends past the app canvas

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2080]
As [noted](https://github.com/department-of-veterans-affairs/caseflow/issues/1618#issuecomment-302532530) in #1618, the Styleguide sticky navigation bar should not extend past the app canvas.

**Comment by slj** [comment]
Solution in action:

![clip-sticky-nav](https://cloud.githubusercontent.com/assets/1053255/26318926/e60f2e06-3eea-11e7-8aea-e667d49907b5.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the style guide
2. Manipulate the scrolling for the main content and navi-menu. 
3. Validate the behavior based on the AC

Screenshots: 
![scroll](https://cloud.githubusercontent.com/assets/23038505/26594433/985bd4d8-4535-11e7-9caf-2c2c7dbe3161.gif)
