### ISSUE TITLE
[V2] Update error message & instructions on Check Documents step for fuzzy date match

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2084]
### Acceptance Criteria
- Error message states: "Some documents could not be found in VBMS."
- Instructional text below table changed to:
"If the document status is marked with an X, try checking:"
- Document date instructional text changed to: "The document date in VBMS.  NOD and Form 9 dates must match their VACOLS dates. SOC and SSOC dates are considered matching if the VBMS date is the same as the VACOLS date, or if the VBMS date is 4 days or fewer before the VACOLS date. Learn more about document dates."
- "Learn more about document dates" links to an answer about document dates in the Caseflow Certification FAQ. (Issue tracking the FAQ answer here: https://github.com/department-of-veterans-affairs/caseflow/issues/2087)

### Mocks

![check docs - mismatched option 1](https://cloud.githubusercontent.com/assets/1178390/26293600/ca6ca6a6-3e8b-11e7-814c-64b592cd831f.png)

**Comment by nemodjuric** [comment]
It seems to me that this was fix with https://github.com/department-of-veterans-affairs/caseflow/pull/2170 @shellicious can you confirm that everything looks good? Changes are already in master (DEMO) or you can refer to screenshot in PR.
However, #2087 is still open. @amprokop would you like me to prioritize this one instead?

**Comment by nemodjuric** [comment]
@kierachell is working on #2087

**Comment by shellicious** [comment]
@nemodjuric, screenshot in PR looks good to me!

**Comment by astewarttistatech** [comment]
**PASSED**

Verified in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Certification V2, with a veteran who is missing 1 or more documents
2. On the Check Documents page, identify the error message at the bottom of the page
3. Validate the copy and UI from the AC and mocks posted in this ticket.

Screenshots:
<img width="1249" alt="screen shot 2017-06-12 at 8 11 22 am" src="https://user-images.githubusercontent.com/23038505/27033421-3a2bb29a-4f47-11e7-85eb-79f1dbd123e9.png">
