### ISSUE TITLE
[V2] Reshuffle table and add status column for Check Documents page

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2085]
### Acceptance Criteria
- First column in table is "Document"
- When a date cannot be found in VBMS, display a long dash: — 
- Last column in table is "Status"
- Display an X icon and "Not found in VBMS" if the document can't be found
- Display a check icon and "Found in VBMS" if the document is found with a matching date in VBMS
- Copy should match the mock
-  "Learn more about document dates" should link to a section on the help page that doesn't exist yet, /certification/help#document-dates (it's ok if the link goes nowhere for now)
https://github.com/department-of-veterans-affairs/caseflow/issues/2087

### Mocks

![check docs - mismatched option 1](https://cloud.githubusercontent.com/assets/1178390/26293629/fb9a788e-3e8b-11e7-99d4-425c0c55019c.png)

**Comment by nemodjuric** [comment]
@shellicious Just to confirm, 
1. Is the first column 'Document' or 'Documents'? 
2. Mock contains a text change as well - "Caseflow could not find the documents marked with an in the appellant's eFolder. This usually happens when something doesn't match up. Try checking:" - is what we have right now, vs "If the document status is marked with an X, try checking:" - is what's shown in mock here (but not in Acceptance  Criteria).

**Comment by amprokop** [comment]
1. `Document` is right

2. Let's follow the mock. Note that there's a new link there. "Learn more about document dates" should link to a section on the help page that doesn't exist yet, `/certification/help#document-dates`. @shellicious — can you provide copy for this section?

**Comment by shellicious** [comment]
Yup, copy for the answer on the FAQ will be posted on this issue: https://github.com/department-of-veterans-affairs/caseflow/issues/2087 I'll have a first draft by the start of next week!

**Comment by nemodjuric** [comment]
@amprokop @shellicious I will be changing usa-alert-heading message (with red background) to the one in the mock. Currently is "Cannot find documents in VBMS
Some of the files listed in VACOLS could not be found in VBMS."

**Comment by kierachell** [comment]
## Trying to learn about document dates doesn't scroll to the actual section in Help
<img width="849" alt="screen shot 2017-05-31 at 8 22 07 pm" src="https://cloud.githubusercontent.com/assets/18075411/26659486/f3a13748-463e-11e7-9b47-dd513b2d119e.png">

## Multiple SSOCs with the same date are validated against the same VBMS document
- If VACOLS has SSOC1 and SSOC2 dates that are the same-ish
- And there is _one_ SSOC document in VBMS
- Then which one is gonna match which?
<img width="809" alt="screen shot 2017-05-31 at 8 27 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/26659582/be2df44c-463f-11e7-8f40-ca7ce1aa0ce7.png">
<img width="851" alt="screen shot 2017-05-31 at 8 27 30 pm" src="https://cloud.githubusercontent.com/assets/18075411/26659583/be2e65b2-463f-11e7-8d54-a61491478fad.png">

**Comment by kierachell** [comment]
**PASSED**
based on updated AC
