### ISSUE TITLE
[V2] Update success message for Check Documents

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2086]
### Acceptance Criteria
- Table columns appear as in the mocks below
- Check marks and "Found in VBMS" appears in the status column for all documents
- If the SOC/SSOC have dates that are not an exact match between VACOLS and VBMS, the success message has an extra line of text: "SOC and SSOC dates in VBMS can be up to 4 days before the VACOLS date to be considered matching."

### Mocks

Success message if all documents are found, but the SOC or SSOC have dates that are not an exact match. 

![check docs - all docs found no soc window](https://cloud.githubusercontent.com/assets/1178390/26324360/7ba666a4-3f00-11e7-8fd1-9cb486662c0a.png)

Success message if all documents are found and have exactly matching dates:
![check docs - all docs found option 1](https://cloud.githubusercontent.com/assets/1178390/26293730/d6ba2b44-3e8c-11e7-953f-02aa96eb0238.png)

**Comment by amprokop** [comment]
@shellicious — still "Found with valid date"?  Not sure if the first mock is outdated here.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Certification V2
2. Upload documents needed, if needed
3. Validate the success message on the check documents page. 

Screenshots: 
<img width="1073" alt="screen shot 2017-06-02 at 11 57 54 am" src="https://cloud.githubusercontent.com/assets/23038505/26734104/e89dcbde-478a-11e7-9684-c562da36c175.png">
