### ISSUE TITLE
[V2] Add/update Caseflow Certification FAQ answer about document dates

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2087]
### Acceptance criteria

After they click on a link from the Check Documents page, Caseflow users are taken to the section of the Caseflow Certification Help page that explains document date matching rules. 

### Draft of Help page text:

Note: There is a new screenshot embedded below, reflecting the new design of the Check Documents table:

**5. Why does Caseflow say it cannot find documents in the appellant’s eFolder?**

Once you're logged in, Caseflow will check to see if documents in the VBMS eFolder (such as the NOD, SOC, and Form 9) match the dates entered in VACOLS. Caseflow will tell you if it cannot find these documents in VBMS.

<img width="924" alt="caseflow-mismatched_v2" src="https://user-images.githubusercontent.com/18075411/26989336-a93340a0-4d20-11e7-9283-9d431b079c57.png">

Document dates in VBMS and VACOLS for the NOD and Form 9 must match exactly. Document dates for the SOC and SSOC are considered matching if the VBMS date is no more than 4 days ahead of the VACOLS date. 

**6. What are the reasons Caseflow may not be able to find documents in VBMS?**

There are usually three reasons Caseflow wouldn't be able to find a document:

**1. The dates of the document in question are inconsistent between VACOLS and VBMS.**

If the dates are inconsistent, change the date in either VACOLS or VBMS to match the other, then click the "Refresh page" button in Caseflow. If the date cannot be changed in VBMS, change the date in VACOLS.

Document dates in VBMS and VACOLS for the NOD and Form 9 must match exactly. Document dates for the SOC and SSOC are considered matching if the VBMS date is no more than 4 days ahead of the VACOLS date. There is a wider range of acceptable dates for SOCs and SSOCs because SOCs and SSOCs may be uploaded to VBMS one or more days before they are mailed, causing VBMS dates to be earlier than VACOLS dates.

This text should be added to the section here: https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/certification/help#cannot-find-documents

**Current** help text shown below for context:

![screen shot 2017-05-26 at 1 01 09 pm](https://cloud.githubusercontent.com/assets/1178390/26504793/02f962ee-4214-11e7-8c36-35b0f882ac5e.png)

## Acceptance Criteria:

1. As a user with access to Certification v1 _only_ access `certification/help` page and make sure sections 5 and 6 match the old copy
1. As a user with access to Certification v2 (feature toggle `certification_v2` enabled) access `certification/help` page and make sure Sections 5 and 6 match the new copy

**Comment by shellicious** [comment]
@amprokop @avrildavid @wturne, what are your thoughts on the new Help page text above, explaining document date matching rules?

**Comment by avrildavid** [comment]
@shellicious - Looks great to me. I think this explanation is really clear.

**Comment by wturne** [comment]
@shellicious - Agreed, it looks good to me too.

**Comment by laurjpeterson** [comment]
@shellicious - Thanks for writing this up! Noticed one small thing:

For #5: should "Caseflow will tell you it cannot find documents in VBMS if it cannot detect these documents." be "Caseflow will tell you if it cannot find these documents in VBMS."

**Comment by shellicious** [comment]
Good work, Lauren "Eagle Eyes" Peterson! @laurjpeterson, I'll fix the typo!

**Comment by avrildavid** [comment]
https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Cert%20v1%20FAQs_for%20editing.docx - revised FAQs are living here at the moment.  Includes changes following our 5/31 review meeting.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Toggle on Certification V2
2. Access the help page
3. Verify the copy and UI against mocks and AC

Screenshots:
![caseflow_help](https://user-images.githubusercontent.com/23038505/27142405-ec886b88-50f8-11e7-8166-c9b76f6e3bf1.png)
