### ISSUE TITLE
Missing Decisions - change table header

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2093]
Change table header 'Days in Queue' to read 'Days Since Outcoding'
Might require adjusting the column spacing a bit

## Mocks
_Current_
<img width="966" alt="screen shot 2017-05-22 at 10 47 55 am" src="https://cloud.githubusercontent.com/assets/4975959/26314594/7cd18866-3edc-11e7-96d1-759b3834a5c6.png">

_Desired_
<img width="802" alt="screen shot 2017-05-22 at 10 53 41 am" src="https://cloud.githubusercontent.com/assets/4975959/26314778/0453f210-3edd-11e7-8702-c02c122435c5.png">

**Comment by slj** [comment]
Solution in action:

![new_missing_hdr](https://user-images.githubusercontent.com/1053255/27084513-2f13face-501a-11e7-94b7-4ff66d265e3b.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Log into Dispatch as a manager
2. Navigate to the ARC Dashboard
3. Under BVA Reports, select "Claims Missing Decisions" 
4. Validate the titles of the table against the AC and mocks. 

Screenshots: 
<img width="1241" alt="screen shot 2017-06-14 at 9 14 36 am" src="https://user-images.githubusercontent.com/23038505/27134098-7cf72540-50e2-11e7-9f7a-fb65bc4e5ca9.png">
