### ISSUE TITLE
Fill out mapping of BGS POA types to our POA types

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2094]
See  `BGS_REP_TYPE_TO_REP_TYPE` in `power_of_attorney_mapper.rb` — we need to map all BGS org type names to one of `Attorney, Agent, Service Organization, Other, and No Representative`.

Use the information obtained in https://github.com/department-of-veterans-affairs/ruby-bgs/issues/33 to complete this task.

**Comment by kierachell** [comment]
**PASSED**

<img width="901" alt="screen shot 2017-06-02 at 3 25 21 pm" src="https://cloud.githubusercontent.com/assets/18075411/26741533/b8587574-47a7-11e7-82e0-13e1a1e8a8df.png">


<img width="1047" alt="screen shot 2017-06-02 at 12 46 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/26741507/a26ac8f2-47a7-11e7-8cf5-3917b8429b9b.png">

<img width="1006" alt="screen shot 2017-06-02 at 8 43 38 am" src="https://cloud.githubusercontent.com/assets/18075411/26741516/a89f6f3e-47a7-11e7-9386-9fcd8c6ed4e1.png">
