### ISSUE TITLE
[2] POA Backend Step 1: Map BGS POA names to VACOLS POA dropdown names

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2097]
VACOLS lists some service organizations in a dropdown. We need to map the BGS names of these organizations to the VACOLS codes, and when we convert BGS POA to VACOLS POA, we should save the VACOLS-equivalent name in `representative_name`. This probably needs to be a manual hardcoded mapping, because there are likely to be small capitalization/spacing/punctuation differences between the two.

If the dev investigates and finds that all of the names actually match from BGS to VACOLS, bring that up for discussion and we'll find a different way.

Example:
```
BGS_REP_NAMES_TO_VACOLS_REP_CODES = {
"American Legion" : "A"
....
}
```

For reference, here are the vacols dropdown values and their corresponding orgs from `case.rb`:
```
  # corresponds to BRIEFF.bfso
  REPRESENTATIVES = {
    "A" => { full_name: "The American Legion", short: "American Legion" },
    "B" => { full_name: "AMVETS", short: "AmVets" },
    "C" => { full_name: "American Red Cross", short: "ARC" },
    "D" => { full_name: "Disabled American Veterans", short: "DAV" },
    "E" => { full_name: "Jewish War Veterans", short: "JWV" },
    "F" => { full_name: "Military Order of the Purple Heart", short: "MOPH" },
    "G" => { full_name: "Paralyzed Veterans of America", short: "PVA" },
    "H" => { full_name: "Veterans of Foreign Wars", short: "VFW" },
    "I" => { full_name: "State Service Organization(s)", short: "State Svc Org"},
    "J" => { full_name: "Maryland Veterans Commission", short: "Md Veterans Comm" },
    "K" => { full_name: "Virginia Department of Veterans Affairs", short: "Virginia Dept of Veteran" },
    "L" => { full_name: "No Representative", short: "None" },
    "M" => { full_name: "Navy Mutual Aid Association", short: "Navy Mut Aid" },
    "N" => { full_name: "Non-Commissioned Officers Association", short: "NCOA" },
    # TODO: double check that "Other Service Organization" is the correct full name.
    # Possibly this should just be "Other"
    "O" => { full_name: "Other Service Organization", short: "Other", rep_name_in_rep_table: true },
    "P" => { full_name: "Army & Air Force Mutual Aid Assn.", short: "Army Mut Aid" },
    "Q" => { full_name: "Catholic War Veterans", short: "Catholic War Vets" },
    "R" => { full_name: "Fleet Reserve Association", short: "Fleet Reserve" },
    "S" => { full_name: "Marine Corp League", short: "Marine Corps League" },
    "T" => { full_name: "Attorney", short: "Attorney", rep_name_in_rep_table: true },
    "U" => { full_name: "Agent", short: "Agent", rep_name_in_rep_table: true },
    "V" => { full_name: "Vietnam Veterans of America", short: "VVA" },
    "W" => { full_name: "One Time Representative", short: "One Time Rep", rep_name_in_rep_table: true },
    "X" => { full_name: "American Ex-Prisoners of War", short: "EXPOW" },
    "Y" => { full_name: "Blinded Veterans Association", short: "Blinded Vet Assoc" },
    "Z" => { full_name: "National Veterans Legal Services Program", short: "NVLSP" },
    "1" => { full_name: "National Veterans Organization of America", short: "NVOA" },
    "2" => { full_name: "Wounded Warrior Project", short: "WWP" },
    "3" => { full_name: nil, short: nil },
    "4" => { full_name: nil, short: nil },
    "9" => { full_name: nil, short: nil },
    ">" => { full_name: nil, short: nil },
    "?" => { full_name: nil, short: nil },
    nil => { full_name: nil, short: nil }
  }.freeze
```

### Acceptance Criteria ###
- If an appellant's POA in BGS is a service org that is found in the VACOLS dropdown (ex: National Veterans Organization of America) and the user indicates that the BGS POA information is correct:
  - upon certification, the correct VACOLS dropdown value should be selected.
  - the representative name should *not* appear in the REP table, it should only appear in the VACOLS dropdown

(this ticket should remain in validation until we successfully can update POA in VACOLS)

**Comment by kierachell** [comment]
blocked cause waiting for #2046

**Comment by kierachell** [comment]
Currently we are not fetching POA from `REPADDR1` if BFSO = `O`...
```
    BFKEY   BFCORLID BFCORKEY  SNAMEF SNAMEL       SSN SNOTES BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19
1 1733624 513451729C CK665294 Carolyn Helder 513451729    uat <NA>    ADV     <NA> 2017-02-22 12:17:18.0 2016-11-14 12:17:18.0 2016-08-06 12:17:18.0
                BFSSOC1               BFSSOC2               BFSSOC3               BFSSOC4               BFSSOC5 BFSO BFHR BFTBIND  REPKEY REPTYPE REPFIRST REPMI
1 2017-03-04 12:17:18.0 2017-01-03 12:17:18.0 2010-12-17 00:00:00.0 2012-01-13 00:00:00.0 2013-04-09 00:00:00.0    O    2    <NA> 1733624       G     <NA>  <NA>
  REPLAST                                       REPADDR1 REPST REPZIP
1    <NA> MASSACHUSETTS DEPARTMENT OF VETERANS' SERVICES  <NA>   <NA>
```

<img width="981" alt="screen shot 2017-06-11 at 12 30 55 pm" src="https://user-images.githubusercontent.com/18075411/27012652-d48c660a-4ea1-11e7-9dff-0da7f5316191.png">

**Comment by amprokop** [comment]
Yep! This is by design. We never decided that it was desirable to assume
that something in REPADDR1 was a rep org name, we only decided that writing
rep org names to REPADDR1 was safe since ROs do that sometimes. My sense is
maybe we should look at the data. In a sample of 1000 prod REP rows where
REPFIRST is null, REPLAST is null, and REPADDR1 is not null, how often is
REPADDR1 the org name?

If we

**Comment by kierachell** [comment]
But we are putting org name in REPADDR1... so the logic here is a bit confusing to me.

**Comment by aroltsch** [comment]
@amprokop can you please clarify what is needed to pass validation.

**Comment by amprokop** [comment]
@kierachell @aroltsch — Artem's comment above will be resolved by https://github.com/department-of-veterans-affairs/caseflow/issues/2312. It should not block validation of this ticket.

**Comment by kierachell** [comment]
**PASSED**
Issue will be addressed #2312 
Based on the comments.

**Comment by kierachell** [comment]
## So why is `BFSO=3` reading as `Service Organization`?
```
    BFKEY   BFCORLID BFCORKEY BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19 BFSSOC1 BFSSOC2 BFSSOC3 BFSSOC4
1 2599462 516517678S CK779938 <NA>    ADV     <NA> 2012-05-14 00:00:00.0 2011-06-10 00:00:00.0 2011-06-05 00:00:00.0    <NA>    <NA>    <NA>    <NA>
                BFSSOC5 BFSO BFHR BFTBIND REPKEY REPTYPE REPFIRST REPMI REPLAST REPADDR1 REPST REPZIP
1 2011-02-28 00:00:00.0    3    5    <NA>   <NA>    <NA>     <NA>  <NA>    <NA>     <NA>  <NA>   <NA>
```
<img width="755" alt="screen shot 2017-06-13 at 5 44 17 pm" src="https://user-images.githubusercontent.com/18075411/27106099-f1bdbbe2-505f-11e7-9549-6298892f0b34.png">

**Comment by kierachell** [comment]
**PASSED**
Remaining issue captured in: https://github.com/department-of-veterans-affairs/caseflow/issues/2354
