### ISSUE TITLE
Create mappers directory and move mapping logic inside of it, leaving only interface/border code in the repositories

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2100]
The appeal repository currently has a mix of integration code and conversion logic. We should isolate all conversion logic in dedicated `mapper` modules, so we can increase the testability of our code and only leave true border/interface code in the appeal repository.

Let's write some tests for our new appeal mapper as well.

See `power_of_attorney_mapper.rb` in https://github.com/department-of-veterans-affairs/caseflow/pull/2083 for an example of this for power of attorney.

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
