### ISSUE TITLE
[3] Update VACOLS address information from BGS POA information

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2101]
We want to be able to update POA address information using BGS information.

- If we don't have to put the representative name in REPADDR1 (see #2098):
  - `bgs_address_line_1` should be used to populate REP.REPADDR1
  -  BGS addresses can have up to three lines. Concatenate address line 2 and address line 3 and use them to populate REP.REPADDR2.
  - city, state, and zip as well  

- If we put the name in REPADDR1 (see #2098):
  - The entire street address should go in REPADDR2.
  - Note that REPADDR2 has a 50 character limit. We might have to cut off the address in some cases.

### Acceptance Criteria ###
- If the user opts to overwrite POA information using BGS information, REPADDR1 and REPADDR2 fields should be updated in VACOLS using the address from BGS (if we have it)
(QA validation for this ticket will need to wait until the frontend has been completed)

### STEPS TO VALIDATE:
Validation Steps:

For representative_type that is  Attorney, Agent, or Other, we need to update the REP table:

1. Representative is a person and address is available 
    1. Vacols rep name should be updated with the BGS rep name
    2. Vacols address_one should be updated with BGS address_line_1
    3. Vacols address_two should be updated with BGS address_line_1 and address_line_2
2. Representative is a person and address is not available
    1. rep name should be updated with the rep name
    2. address _one and address_two, zip, city, state should be all blank
3. Representative is not a person and address is available 
    1. rep name should be cleared in Vacols
    2. address_one should contain representative name
    3. address_two should contain BGS  address_line_1, address_line_2 and address_line_3
4. Representative is not a person and address is not available
    1. rep name should be cleared in Vacols
    2. address_one should contain representative name
    3. address_two should be blank

**Comment by aroltsch** [comment]
Blocked by https://github.com/department-of-veterans-affairs/caseflow/pull/2157

**Comment by aroltsch** [comment]
Validation Steps:

For representative_type that is  Attorney, Agent, or Other, we need to update the REP table:

1. Representative is a person and address is available 
    1. Vacols rep name should be updated with the BGS rep name
    2. Vacols address_one should be updated with BGS address_line_1
    3. Vacols address_two should be updated with BGS address_line_1 and address_line_2
2. Representative is a person and address is not available
    1. rep name should be updated with the rep name
    2. address _one and address_two, zip, city, state should be all blank
3. Representative is not a person and address is available 
    1. rep name should be cleared in Vacols
    2. address_one should contain representative name
    3. address_two should contain BGS  address_line_1, address_line_2 and address_line_3
4. Representative is not a person and address is not available
    1. rep name should be cleared in Vacols
    2. address_one should contain representative name
    3. address_two should be blank

**Comment by kierachell** [comment]
So...this is blocked because there is no address data for any `ptcpnt_id` in BGS

**Comment by kierachell** [comment]
```
#<Certification id: 10540, vacols_id: "2765716", already_certified: false, vacols_data_missing: false, nod_matching_at: "2017-06-13 21:18:21", soc_matching_at: "2017-06-13 21:18:21", form9_matching_at: "2017-06-13 21:18:21", ssocs_requ
ired: false, ssocs_matching_at: nil, form8_started_at: "2017-06-13 21:18:21", completed_at: nil, created_at: "2017-06-13 21:18:15", updated_at: "2017-06-13 21:18:26", user_id: nil, bgs_representative_type: "Service Organization", bgs_repr
esentative_name: "SHANA M DUNN", vacols_representative_type: nil, vacols_representative_name: nil, representative_type: nil, representative_name: nil, hearing_change_doc_found_in_vbms: nil, form9_type: nil, vacols_hearing_preference: "tra
vel_board", hearing_preference: nil, certifying_office: "Baltimore, MD", certifying_username: "RO13", certifying_official_name: nil, certifying_official_title: nil, certification_date: "2017-06-13", poa_matches: nil, poa_correct_in_vacols
: nil, poa_correct_in_bgs: nil, bgs_rep_address_line_1: nil, bgs_rep_address_line_2: nil, bgs_rep_address_line_3: nil, bgs_rep_city: nil, bgs_rep_country: nil, bgs_rep_state: nil, bgs_rep_zip: nil>
```
<img width="912" alt="screen shot 2017-06-13 at 5 19 28 pm" src="https://user-images.githubusercontent.com/18075411/27105160-96b11de6-505c-11e7-88dd-d7a05ff53f0f.png">

## After Certification
```
    BFKEY   BFCORLID  BFCORKEY BFDC BFMPRO              BF41STAT                BFDNOD                BFDSOC                 BFD19 BFSSOC1 BFSSOC2 BFSSOC3
1 2765716 516517690S CK1222204 <NA>    ADV 2017-06-13 00:00:00.0 2015-08-03 00:00:00.0 2015-09-03 00:00:00.0 2015-09-04 00:00:00.0    <NA>    <NA>    <NA>
  BFSSOC4 BFSSOC5 BFSO BFHR BFTBIND  REPKEY REPTYPE REPFIRST REPMI REPLAST REPADDR1 REPST REPZIP
1    <NA>    <NA>    O    1    <NA> 2765716    <NA>    SHANA     M    DUNN     <NA>  <NA>   <NA>```

**Comment by aroltsch** [comment]
@amprokop could you please respond to @kierachell's question.

**Comment by amprokop** [comment]
@kierachell @aroltsch — the conversion of POA data is sometimes lossy right now :( it's not 100% clear to me what we should do about this, so i've opened https://github.com/department-of-veterans-affairs/caseflow/issues/2354 and kicked it to design/product.

**Comment by kierachell** [comment]
**PASSED**

all 4 scenarios pass
