### ISSUE TITLE
Allow ARC Manager to cest cases as a Claims Assistant

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2104]
ARC Managers sometimes need to cest Dispatch claims themselves. We need a way for the ARC manager to access the Claim Assistant view.

### AC
* Create a separate URL for manager view

**Comment by lakohl** [comment]
Dependent on #1762

**Comment by astewarttistatech** [comment]
@lakohl The AC doesn't say what URL has been created or how to "cest" lol

**Comment by sharonwarner** [comment]
@astewarttistatech Information for how to validate is on the PR

**Comment by kierachell** [comment]
**PASSED**

This is old AF and has been out forever
