### ISSUE TITLE
Document Viewer | View keyboard shortcuts menu

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2107]
**Story**
As a user, I want to know all the keyboard shortcuts that will allow me to accomplish all of my tasks when reviewing cases. 

## AC

- [ ] Verify that icon and text are 12px apart and centered aligned with the annotation box
- [ ] Verify that selecting the "View keyboard shortcuts" link and icon open the keyboard shortcut modal. At hover, make sure to underline starting from the word "View."
- [ ] Verify that modal has Title, 3 tables, button (same placement as default red button from style guide) and x to exit (See copy below) [See Modal in style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#modals)
- [ ] Verify height of modal is 580px and that there is a scrollbar
- [ ] Shortcut text should be in `dark gray` _**Note: the mocks have red text but that is incorrect**_
- [ ] In the scroll section Page up and Page down should say `shift space` and `space` instead of `alt` plus arrows.
## Mock ups

**_Note: In the scroll section Page up and Page down should be `shift space` and `space`_**

What it should look like with 580px height
![image](https://user-images.githubusercontent.com/13420618/26906958-e6fa4b0e-4bbd-11e7-822d-cdc7cba2203d.png)

What it looks like with all content
![image](https://cloud.githubusercontent.com/assets/13420618/26640630/46943de0-45f6-11e7-8131-7e00debce85d.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26636241/191115d4-45ea-11e7-9845-d91c8f53e769.png)

## Copy

Title: Keyboard shortcuts 

| Scroll  | Shortcut |
|-------------------- | ------ |
Page up | `shift space`
Page down | `space`

| Add/ edit comment | Shortcut |
|-------------------- | ------ |
Add comment mode | `alt` + `c`
Move comment up | (up arrow icon)
Move comment down | (down arrow icon)
Move comment left | (left arrow icon)
Move comment right | (right arrow icon)
Place a comment | `alt` + `enter`

| View documents  | Shortcut |
|-------------------- | ------ |
Next document | (right arrow icon)
Previous document | (left arrow icon)

Button copy: Thanks, got it!

## Icons

[Up arrow](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/arrow-up-323A45.svg)
[Down arrow](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/arrow-down-323A45.svg)
[Left arrow](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/arrow-left-323A45.svg)
[Right arrow](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/arrow-right-323A45.svg)
[Keyboard](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/keyboard.svg)

**Comment by mmlumba** [comment]
@gnakm What is the color going to be for the keyboard keys (alt, enter, c)? Red on grey text or grey on black text?

**Comment by gnakm** [comment]
`gray-dark` please! Yes the red will cause 508 issues.

**Comment by mmlumba** [comment]
Per @NickHeiner and @mdbenjam:

If the PR is approved before all the keyboard shortcuts work (???), add a "mini" feature flag that keeps all the code but hides the UI components for the button and the modal.

**Comment by kierachell** [comment]
### centered aligned in the annotation menu aligned with features on toolbar

It's aligned with the whole Menu sidebar, but not against the scrollbar (for annotiations) line on the right - which do you want?
<img width="386" alt="screen shot 2017-07-03 at 9 59 24 am" src="https://user-images.githubusercontent.com/18075411/27796007-6270d8a8-5fd6-11e7-8546-e5e8634f2d75.png">

<img width="387" alt="screen shot 2017-07-03 at 10 10 34 am" src="https://user-images.githubusercontent.com/18075411/27796404-e0499c5a-5fd7-11e7-8c20-19fabbaa7177.png">

### Adding spaces is janky! There's now an eyesore of an underlined space to the left of `View`!
😄 
<img width="257" alt="screen shot 2017-07-03 at 10 01 30 am" src="https://user-images.githubusercontent.com/18075411/27796058-9d549004-5fd6-11e7-87a3-11f8b5e01972.png">


### Dat modal padding ain't 40!
<img width="261" alt="screen shot 2017-07-03 at 10 06 57 am" src="https://user-images.githubusercontent.com/18075411/27796306-937032ae-5fd7-11e7-94b4-7438bc31260a.png">

**Comment by gnakm** [comment]
@mmlumba 
1. Can we have the Icon and button link for View keyboard shortcut center aligned with the annotation box
1. There is an underline for a space before the View keyboard shortcut link. Could we take that out?
1. I'm going to take padding AC out since it should be whatever the modal is

Adjusting the AC with these comments. 

/cc: @artem

**Comment by kierachell** [comment]
**PASSED**

Lookin' spiffy!
<img width="227" alt="screen shot 2017-07-03 at 9 52 25 am" src="https://user-images.githubusercontent.com/18075411/27878165-56c2ea80-618b-11e7-8dc7-4ec2dcbabb5e.png">
<img width="386" alt="screen shot 2017-07-03 at 9 59 24 am" src="https://user-images.githubusercontent.com/18075411/27878166-56cdfe52-618b-11e7-8fce-28751b1938bd.png">
