### ISSUE TITLE
Sort Order | Make down default

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2111]
When switching between sorting by receipt date to sorting by type the sort order should be ascending and the icon should default to down. Currently, the sort order flips every time the user switches which column you sort by.

## AC
1. Verify when sorting by a new column the sort icon is down the sort order is newest to oldest for date and alphabetical for type.
1. Verify when clicking on the sorted column the sort order is reversed.

**Comment by gnakm** [comment]
I think what we have now is fine and we haven't heard from users that it's confusing.
