### ISSUE TITLE
Document List | Loader fail error message

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2115]
**Description**
There may be a time when a loading spinner fails and never goes away. We need to display an error message. 

- [ ] Verify that we use [Status Message Styling](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#messages) [Source code](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/containers/StyleGuide/StyleGuideStatusMessages.jsx)
- [ ] Use copy at the bottom
- [ ] Verify that refresh this page has a link that allows users to refresh page

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/26362817/2c03b036-3fad-11e7-8413-b8c82daaa527.png)

## Copy
Title: 
Unable to load documents

Body text: 
It looks like Caseflow was unable to load this case. Please refresh the page and try again.

**Comment by abbyraskin** [comment]
Could we say "Unable to load documents" just to add a tiny bit more context?
And maybe instead of list: "It looks like Caseflow was unable to load this case. Please refresh the page and try again."

**Comment by gnakm** [comment]
@abbyraskin Yar I like that better.

**Comment by gnakm** [comment]
@NickHeiner copy is good to go.

**Comment by NickHeiner** [comment]
As you can see in the screenshot on #2119, I messed up the message and inserted a linebreak where there should not have been one. Is it worth fixing?

**Comment by kierachell** [comment]
Yes

**Comment by gnakm** [comment]
@NickHeiner Could you add a line break after the 2nd sentence so it looks like this:

It looks like Caseflow was unable to load this case. 
Please refresh the page and try again.

**Comment by kierachell** [comment]
@gnakm Is the title supposed to be `title` case as it is in the Styleguide?

<img width="762" alt="screen shot 2017-05-25 at 4 52 35 pm" src="https://cloud.githubusercontent.com/assets/18075411/26470182/c445e620-416a-11e7-87c3-1e7ddcfccb89.png">

**Comment by gnakm** [comment]
We talked about this on slack but let's leave it sentence case the way it is in this mock. We're going to change style guide messages from title case > sentence case.

**Comment by kierachell** [comment]
**PASSED**
FINE


BE THAT WAY 👁
