### ISSUE TITLE
Style guide | Max Character Width

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2116]
**Story**
As a designer and developer, I want to know the max character width of text, which intentions are to provide good readability to users on all of Caseflow apps. 

## AC
- [ ] Verify that all of our headings and body text are set at a max character width of 70 rem for **left-aligned text**
- [ ] This doesn't need a subsection. Change source code in text styles
- [ ] Add new copy right under Typography header. It will be an overview of text styles and new character width.

**_Note: This does not apply to tables and Alerts. Those should go across the canvas._** 

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25583548/3f3cfa4e-2e60-11e7-8356-3d161070fbbd.png)

**_Note: This mock is for reference. No UI component needs to be build for this issue._** 

## Copy

The typography of Caseflow is very simple. We use Source Sans Pro as our only font. The text styles comes in different weights and sizes to provide visual hierarchy and clear context for users. 
Each text style has a set `margin-bottom` so that there is balance in a page and spacing between applications are consistent. The lead paragraph is encouraged to be used for instructions, descriptions and form copies. For clarity and readability, the text styles are set to a character width limit. On the contrary, the character width is not applicable for Tables and Alerts. 

Related issue 
https://github.com/department-of-veterans-affairs/caseflow/issues/1078

**Comment by Sjones352** [comment]
@gnakm 648px in rem is 44 rem not 70 rem. Correct me if I am wrong.
<img width="1245" alt="screen shot 2017-07-20 at 1 26 00 pm" src="https://user-images.githubusercontent.com/23080951/28430613-29243654-6d4f-11e7-97cf-3064789656dd.png">

**Comment by Sjones352** [comment]
@gnakm if I change the max-width of body-text. This is how it will look like. Compare the first paragraph that has been changed and the second one that has not been changed.

<img width="1280" alt="screen shot 2017-07-20 at 2 34 09 pm" src="https://user-images.githubusercontent.com/23080951/28433289-0f96e70e-6d59-11e7-878f-7171825f126f.png">

**Comment by kierachell** [comment]
### Sad :(
![screen shot 2017-07-21 at 11 47 22 am](https://user-images.githubusercontent.com/18075411/28479759-d8cf9026-6e2b-11e7-91ca-ecbbab455703.png)

![screen shot 2017-07-21 at 1 53 39 pm](https://user-images.githubusercontent.com/18075411/28479777-ebbfda42-6e2b-11e7-907a-a5302a26b0f5.png)

**Comment by Sjones352** [comment]
@gnakm and @kierachell so for this issue I have added the max-width style to the help page and Styleguide containers. I have to dig deep to find out how going to change it for all our app pages. 

<img width="1000" alt="screen shot 2017-07-21 at 8 05 12 pm" src="https://user-images.githubusercontent.com/23080951/28501221-553115fc-6fa5-11e7-916f-3b93d644396a.png">

**Comment by Sjones352** [comment]
@gnakm  when I changed  the width of heading and body-text to 70rem, the text only takes up 70rem within the parent element, and not from the whole page. This is why Reader was breaking because I added the style directly to to parent element.

### Suggestions
 Since the text in those screenshots(Reader) are centered whereas text in styleguide and help pages are not centered, can we  change the AC so that only left aligned text can have that max width. Right now I have this style applying to the Style guide and help pages. Please advice

**Comment by gnakm** [comment]
@Sjones352 I see what you mean. I'll change AC so that it only applies to left aligned text.

**Comment by kierachell** [comment]
**PASSED**


Checked Styleguide and Help pages lgtm
![screenshot_2017-07-24_18-41-25](https://user-images.githubusercontent.com/18075411/28548029-b949df06-709f-11e7-9588-4fea8a7f6a83.png)
