### ISSUE TITLE
Style guide | New lead paragraph font size

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2117]
Description
After testing different header sizes, we decided to change Lead Paragraph from 22px to 19px. 

# AC
- [x] Verify that in the style guide under typography > text style, the lead paragraph font-size is 19px in both source code and UI component. 
- [x] Change should be applied to all existing apps.

## Mock up
![image](https://cloud.githubusercontent.com/assets/13420618/26363206/5ddb7e1c-3fae-11e7-9ce1-f249e41fb560.png)

**Comment by NickHeiner** [comment]
@gnakm, is this ticket for updating only the styleguide, or for going through and making sure that all existing app content matches this as well?

**Comment by gnakm** [comment]
@NickHeiner This change should go across all existing apps. Updating AC now.

**Comment by kierachell** [comment]
### Seems to have some side effects

![screen shot 2017-07-21 at 1 53 39 pm](https://user-images.githubusercontent.com/18075411/28479802-09deaa8a-6e2c-11e7-8897-d3bb79819388.png)

![screen shot 2017-07-21 at 11 47 22 am](https://user-images.githubusercontent.com/18075411/28479813-1258702e-6e2c-11e7-8818-ad810e5b09c8.png)

**Comment by Sjones352** [comment]
@kierachell This is not in connection with ticket #2116. I am sure this one passes validation. #2116 has also been fixed.

**Comment by kierachell** [comment]
**PASSED**
Looks spiffy in the styleguide!
