### ISSUE TITLE
Style guide | Top navigation bar and footer and responsive to canvas

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2118]
**Description**
New apps Hearing Prep and Reader has new canvas width due to use cases of each project. 
We want to Navigation bar and footer so that they always align with the width of the app canvas. 
**_Note: This means that all the navigation bar and footer will not look the same across apps but that's okay (Artem)._**

## AC
- [ ] Set the top navigation bar so that the left of the caseflow logo and right of user dropdown is always aligned with the width of the app canvas
- [ ] Set the footer so that the left of Build by.. copy and right of feedback link are always aligned with the width of the app canvas. 
- [ ] Set the horizontal line in the footer as same width of the app canvas. 

## Note
This ticket can passed without Reader having the footer. There is a ticket for adding Reader Footer but this can be shipped first. https://github.com/department-of-veterans-affairs/caseflow/issues/2740

## Mock up
![image](https://cloud.githubusercontent.com/assets/13420618/26363688/c2612a0c-3faf-11e7-9f87-ec5faae655f2.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26363696/c8f09f92-3faf-11e7-9277-a8a428981e75.png)

## New Copy
Almost all of the interaction in Caseflow takes place in an App Canvas. The content starts off with a page title and minimal instructions for what the user needs to do to complete their task on the page. It then contains any interaction that well help this to accomplish their task including forms, document previews, tables, error messages, and more. The canvas has a default standard width but can be adjusted according to the needs of each application.

**Comment by mmlumba** [comment]
I believe @slj fixed this issue in the UI but I'm not sure which ticket this is referenced in. All I could recall is this ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/2606

I'm still creating a PR for the copy change in the style guide.

**Comment by astewarttistatech** [comment]
@mmlumba There is no footer on the Document List page and on the document viewer in Reader. 

Current View: 
![upcominghearings](https://user-images.githubusercontent.com/23038505/29714574-d580584a-8971-11e7-8d5f-1937d873018b.png)
![hearingworksheet](https://user-images.githubusercontent.com/23038505/29714583-db2e4de2-8971-11e7-8ae6-4bd5a9b21355.png)
![dailydocket](https://user-images.githubusercontent.com/23038505/29714586-deb213e0-8971-11e7-83a8-461ac29d3a18.png)
![documentlistpage](https://user-images.githubusercontent.com/23038505/29714594-e3ac697c-8971-11e7-8a76-8486823a2059.png)

**Comment by gnakm** [comment]
@astewarttistatech Updating ticket now. Ignore the footer in the mockups. That is a separate issue!

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Hearings 
2. Validate the pages (Daily Docket, Hearings Worksheet, and Upcoming Hearing Days) have canvases that are aligned with the header and footer present 

Screenshots: 

See above
