### ISSUE TITLE
Return 404 if user has no vacols_id

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2124]
For now, if a user does not have a vacols_id, show them the 404 page.

This prevents getting errors in production

**Comment by kierachell** [comment]
**PASSED**
<img width="1252" alt="screen shot 2017-05-24 at 2 45 54 pm" src="https://cloud.githubusercontent.com/assets/18075411/26420262/1103b018-4090-11e7-89a2-6575ce7dac0d.png">
## removed VACOLS_ID
<img width="1091" alt="screen shot 2017-05-24 at 2 48 07 pm" src="https://cloud.githubusercontent.com/assets/18075411/26420261/10fd6b18-4090-11e7-948b-cab32f960a9e.png">
