### ISSUE TITLE
Inline Form | Input validation lets random characters through...

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2134]
# Description
When typing random things as I always do into the inline form;
for some reason it lets me input non-numbers like:
`e`, `.`, `+`... but not any other non-numbers...weird.

## Reproduction Steps

**Scenario 1 -**

1. Go to any Inline Form
1. Type `e`
1. Type `a`
1. Type `+`
1. Type random shit and see only the above work

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Hah]_**
![randominput](https://cloud.githubusercontent.com/assets/18075411/26421540/66fb8c12-4094-11e7-8f8c-b803c88db634.gif)

# To Verify Fix

Visit an inline form an enter `+, . or e`.  The field should be cleared immediately.  If you enter a number followed by a dot and tab away, the field should be updated to just the number.  Basically anything other than integer N or N. should get cleared.

**Comment by slj** [comment]
# To Verify Fix

Visit an inline form an enter `+, . or e`.  The field should be cleared immediately.  If you enter a number followed by a dot and tab away, the field should be updated to just the number.  Basically anything other than integer N or N. should get cleared.

**Comment by amprokop** [comment]
who sez `e` isn't a number

**Comment by astewarttistatech** [comment]
**Failed** @slj field gets cleared entirely if a "+, . or e" is entered into the field anywhere (between numbers and after them)

Current view: 
![inlineform](https://cloud.githubusercontent.com/assets/23038505/26643484/79659198-45ff-11e7-847c-9338a4f5a480.gif)

**Comment by kierachell** [comment]
**PASSED**
![validation](https://cloud.githubusercontent.com/assets/18075411/26644906/5767f7ca-4604-11e7-9b1d-26c01f4247fd.gif)
