### ISSUE TITLE
Ensure that Form 9 PDF appears on demo and local

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2135]
Due to some code changes, the stub Form 9 stopped appearing on local demo. Ensure that we can fetch this document and display it on local and demo envs.

https://cloud.githubusercontent.com/assets/3781835/26214928/3f5e6868-3bcc-11e7-8314-eab2d23dae99.png

### Acceptance Criteria ###
- Ensure that for 123C, `lib/pdfs/Formal_Form9.pdf` is displayed on the Confirm Hearings page on both local and dev/demo
- Ensure that for 124C, the `lib/pdfs/Informal_Form9.pdf` is displayed on the Confirm Hearings page on both local and dev/demo

**Comment by astewarttistatech** [comment]
No form 9 shown in demo @aroltsch | Pushing this back into "In Progress" for you.

Current view of form 9 for 123C:
![certification demo](https://user-images.githubusercontent.com/23038505/26986592-24a66b32-4d16-11e7-8d56-027695b0c2c9.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validate: Demo/Dev and Local
Browsers: FF and Chrome
