### ISSUE TITLE
Fit to Page | Doesn't work until scrolled

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2136]
Currently the fit to page button doesn't make the documents the correct size, unless the user has scrolled the document first.

## AC
1. Verify fit to page zooms the pages such that the page height equals the scroll window height.
1. Verify fit to page zooms the pages such that the page height equals the scroll window height when it is clicked before a user has scrolled.

**Comment by abbyraskinUSDS** [comment]
This will be fixed by #2762
