### ISSUE TITLE
Create new category in Reader

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2137]
Create a 4th read-only category in Reader, called "Case Summary". Selecting this category will filter to show:
- original claim (if possible)
- NOD
- SOC
- Form 9
- VA 8 Certification of Appeal
- BVA Decision (all prior)
- SSOC (all SSOCS after the SOC date)
- DD214 (all)
- Rating Decision Codesheet (most recent)

#### Acceptance Criteria
- New category is listed for filtering documents 
- New category will *not*  editable by the user (you cannot add it to documents)
- When sending the documents to the frontend, the backend will  "preopulate" which documents have this category.

See #2752 for colors

**Comment by joofsh** [comment]
CC @lakohl can you update the list of desired documents?
@laurjpeterson Can you sync with the Reader team on the final name for this new category. Does "Case Summary" work for everyone?

**Comment by mdbenjam** [comment]
Case Summary is fine with me.

**Comment by lakohl** [comment]
Updated doc list above

**Comment by NickHeiner** [comment]
> should be preopulated on the frontend on reader page load

Do you mean that the frontend should determine which documents belong in this category? I think it would be cleaner if it was just presented by the backend as another category on the returned document JSON object.

**Comment by joofsh** [comment]
Good question. To clarify I mean the system (Caseflow) should artificially determine which documents are flagged as being in this new category. Whether it goes on the backend or frontend is an implementation detail (I wasn't trying to be too prescriptive yet). 

Pros of doing it on the backend:
- Simplifies reader frontend code

Downside:
- slightly slower? This will slow down every Reader pageload, though slightly

I don't have a strong preference. If you think this should go on the backend that's fine with me.

**Comment by NickHeiner** [comment]
I'm generally fine with not being prescriptive. But my intuition is that this won't make an appreciable perf difference, and should thus be done on the backend. But if we do measure a perf difference, that would be a good reason to do it on the frontend.

**Comment by joofsh** [comment]
Either way, updating the original description to clarify what I meant! Sorry about the confusion

**Comment by sharonwarner** [comment]
@lakohl do you know what the document type is in vbms for the original claim?

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Reader
2. In the Categories dropdown, verify that "Case Summary" is present
3. Verify that the document list is filtered when "Case Summary" is selected 

Screenshots: 
<img width="1202" alt="screen shot 2017-08-03 at 9 41 26 am" src="https://user-images.githubusercontent.com/23038505/28924532-1e3d4190-7830-11e7-83ce-4b917e9a2308.png">
