### ISSUE TITLE
Content fix for Style Guide

### ISSUE THREAD

**Issue by billhunt-usds** [department-of-veterans-affairs/caseflow#2144]
I really enjoyed seeing the Style Guide during the demo yesterday, this is a fantastic resource.  However, I see that we're using the term `spirit animal` under the `Tables` examples in a way that isn't appropriate.  Please replace this with a different term, perhaps `Favorite Animal` or `Patronus`.

More on the use of `spirit animal` as cultural appropriation:

* https://studybreaks.com/2016/06/17/everyones-spirit-animal-should-be-cultural-sensitivity/
* http://www.spiralnature.com/spirituality/spirit-animal-cultural-appropriation/

Please let me know if this is not the correct place to report this issue.

**Comment by gnakm** [comment]
@billhunt-usds Thanks Bill. We'll change it to Patronus. 

/cc: @mmlumba

**Comment by mmlumba** [comment]
@Sjones352 Since we are changing the `StyleGuideTables` component anyways could you also fix this console error?  (I'm fine with you selecting either prop option)
<img width="1276" alt="screen shot 2017-05-25 at 1 16 29 pm" src="https://cloud.githubusercontent.com/assets/4773320/26461845/80dc1eea-414c-11e7-98f9-f153580f10dc.png">

**Comment by mmlumba** [comment]
For validation:
1. Verify that the use of "Spirit Animal" is no longer used on Style Guide
2. Verify that the `<Table>` console error no longer appears

**Comment by mmlumba** [comment]
@gnakm we're gonna use "Favorite Animal instead"

**Comment by kierachell** [comment]
**PASSED**
<img width="746" alt="screen shot 2017-05-26 at 2 23 49 pm" src="https://cloud.githubusercontent.com/assets/18075411/26507588/0e941170-421f-11e7-99db-351023d48f19.png">
