### ISSUE TITLE
Status: Look up SSN in BGS

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#2146]
As the corporate database is more accurate than VACOLS, use BGS to retrieve the Veteran ID from the given social security number.

## Acceptance Criteria
- Verify that the file number used to look up appeals for the list appeals endpoint is retrieved from BGS and the SSN from VACOLS is not used.
- Verify that if the veteran with the SSN passed is not present in BGS, a 404 is returned.

**Comment by kierachell** [comment]
**PASSED**
Seeing BGS calls.
