### ISSUE TITLE
Improvements to Repository objects

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#2149]
Now that we have a bunch of repository objects floating around there are some refactoring tasks we could do to clean them all up:

- Move them all to one place. They are split between `app/services` and `app/repositories` right now.

- Move some of the common logic into a base class like `normalize_vacols_date`

**Comment by nickheiner-usds** [comment]
@shanear is this ticket still relevant?

**Comment by shanear** [comment]
yes it is. I was just thinking about this recently lol

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
