### ISSUE TITLE
Document Viewer | Back button too big

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2154]
**Description**
Back button at hover is huge!

## AC 
- Make the button hover stop right right after the 's.'

## Mock up

Ah! This is wrong!
![image](https://cloud.githubusercontent.com/assets/13420618/26469375/c2ffa2ea-4167-11e7-95c4-367e8cb8d9e7.png)

**Comment by kierachell** [comment]
Same for categories
<img width="430" alt="screen shot 2017-05-30 at 10 24 23 am" src="https://cloud.githubusercontent.com/assets/18075411/26588051/2c9b7dc4-4522-11e7-9561-350e66b959d2.png">

**Comment by astewarttistatech** [comment]
**Failed**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 

1. Access Reader
2. Open a document and verify the top toolbar's back button

Screenshot: 
<img width="1003" alt="screen shot 2017-06-01 at 3 28 36 pm" src="https://cloud.githubusercontent.com/assets/23038505/26697257/4cb1f9b2-46df-11e7-9b93-da32ee6bf0c1.png">

**Comment by mmlumba** [comment]
@astewarttistatech These are the size differences I made (viewable in dev tools). See below:
_Before_
![image](https://cloud.githubusercontent.com/assets/4773320/26739330/6938ad54-479f-11e7-9d81-bc24df629ffc.png)

_After_
<img width="261" alt="screen shot 2017-06-02 at 2 25 02 pm" src="https://cloud.githubusercontent.com/assets/4773320/26739349/79750c30-479f-11e7-996d-68a4acec5ee8.png">

**Comment by astewarttistatech** [comment]
Based on the above comment, **PASSED**

Validated: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access reader
2. Open a document
3. Inspect the back button
4. Validate the specs against the Mocks and AC. 

Screenshot: 
see above
