### ISSUE TITLE
Document Viewer | Placing annotation between different documents 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2156]
**Story**
Right now, a user can be in annotation mode when switching between documents. This is confusing because users may be adding comments to a document they weren't intending to. 

## AC
- [ ] When a user is in annotation mode and switches to another document, document should be automatically taken out of annotation mode. 

## Related Issue
#1768

**Comment by mmlumba** [comment]
@gnakm What are the buttons supposed to look like if disabled?

**Comment by gnakm** [comment]
Just take them out @mmlumba

**Comment by mdbenjam** [comment]
@gnakm I think that moving between pages should just take you out of annotation writing mode. That way it is consistent with our behavior for placing annotations. Also, we need to leave annotation placing mode if we hit the back to all documents button.

**Comment by gnakm** [comment]
@mdbenjam I see what you were saying. That makes more sense to me.

Changing the AC from
-  When you enter “placing annotation” mode, next and previous buttons should be disabled (not on the page) until annotation is either saved or cancelled. 

to 

- When a user is in annotation mode and switches to another document, document should be automatically taken out of annotation mode.

**Comment by kierachell** [comment]
**PASSED**

![annotaitons](https://user-images.githubusercontent.com/18075411/29188571-81bba0d4-7de1-11e7-8d20-0b19804c8828.gif)
