### ISSUE TITLE
Style guide | Add colors

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2159]
Description
As a developer or designer, I want to know about ALL the colors that are available to me including the new `primary-alt` and `gray-warm-alt` colors soon to be used in Reader.

## AC
- [x] Add `gray-warm-light` color in primary colors section
- [x] Add `primary-alt` color in secondary colors section 

[Colors can be found in USWDS](https://standards.usa.gov/components/colors/)

![image](https://cloud.githubusercontent.com/assets/13420618/26473211/3454b1be-4178-11e7-8af4-b5cad4c0c2f5.png)

**Comment by Sjones352** [comment]
![screen shot 2017-06-05 at 12 00 03 pm](https://cloud.githubusercontent.com/assets/23080951/26791889/8f69b858-49e6-11e7-9109-f99977801c0e.png)

**Comment by gnakm** [comment]
@Sjones352 lgtm!

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate:
1. Access the living style guide
2. Check the added colors match what is listed in the AC and mocks

Screenshots: 
![styleguide colors](https://user-images.githubusercontent.com/23038505/26883110-4049ba5e-4b6a-11e7-9eff-77c18cdd2c22.gif)
