### ISSUE TITLE
BVA Manager Missing Decisions page - UI updates

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2168]
As the BVA Manager, I would like to easily see how many cases are truly missing decisions.

## AC
1. Verify that the veterans/claims whose decisions have been missing (in queue/outcoded) for 0 days are no shown.
1. Verify that h1 text is updated to read: 'Claims Missing Decisions in VBMS'
1. Verify that 'Total missing: [number of claims]' is added to the upper right corner.
1. Verify that 'Total missing:' is 19px and the [number of claims] is 24px

## Mock
<img width="594" alt="screen shot 2017-05-26 at 5 14 32 pm" src="https://cloud.githubusercontent.com/assets/4975959/26513010/35cd203e-4237-11e7-9913-55e8c77b0d49.png">

**Comment by lakohl** [comment]
@shanear this is for your train ride...

**Comment by slj** [comment]
Solution screenshot:
<img width="656" alt="screen shot 2017-06-19 at 2 13 31 pm" src="https://user-images.githubusercontent.com/1053255/27299213-995eff1c-54f9-11e7-8eae-e2ec414410a8.png">

**Comment by astewarttistatech** [comment]
**FAILED**

The veterans/claims whose decisions have been missing (in queue/outcoded) for 0 days are being shown. @slj 
![missingdecisions](https://user-images.githubusercontent.com/23038505/27386963-623844c2-5665-11e7-8707-9bd1008c1037.gif)

**Comment by astewarttistatech** [comment]
Still validating James, Edward, B (879325488) in Dispatch.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Dispatch as a caseworker and produce claims that have no decisions
2. Access Dispatch as a Manager
3. Navigate to the BVA reports section and view the Missing Decisions page
4. Validate that the Missing Decisions page matches all the criteria mentioned in the AC and mocks. 

Screenshots: 
<img width="1076" alt="screen shot 2017-06-27 at 11 53 38 am" src="https://user-images.githubusercontent.com/23038505/27597208-b6295cfa-5b2f-11e7-8f80-33cf4af6cad2.png">
![missingdecisions](https://user-images.githubusercontent.com/23038505/27597229-c155639e-5b2f-11e7-91e3-0778d6ccfa42.gif)
