### ISSUE TITLE
Document List | Jump to section error

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2173]
Story
Currently when you jump to a section from the expanded comment section in the document list page, it always jumps to the first page of the document. 

## AC
- [ ] Verify that when you click jump to section, it lands on the appropriate page in the document viewer.

**Comment by astewarttistatech** [comment]
Theres a few errors in here i don't know what to make of. I can't decipher if they are related to the ticket or not. @gnakm @tejans24 

1. It goes to the first page first, then goes to the page the comment was on. 
2. If you push the the back button to switch to the previous document in that order and then press the next button (like i did by mistake (hehe), it doesn't take you to the first page of that document, it takes you to where you last left off. 

Current view: 
![readerjumptosection](https://user-images.githubusercontent.com/23038505/26935491-19ded338-4c3a-11e7-9ab6-5ee019a508c8.gif)

**Comment by gnakm** [comment]
@astewarttistatech @tejans24 Yes. these are all wrong. 

1. This is a bug. It is a concoction of what's incorrect + correct.  It should go straight to the correct page of the icon + comment. 
2. If you jump to a section and leave that document (whether going back to document list or different document), user should never land back at that section again unless s/he decides to jump to specific section.

**Comment by astewarttistatech** [comment]
I will make a new bug for the second issue and push this issue back.

**Comment by abbyraskin** [comment]
@astewarttistatech @tejans24 let's break out alexis' noted bugs into separate tickets (i will create one for the 1st issue) so we can have a slight fix for users in the meantime. 

@astewarttistatech can you link to any bug issue you've already created?

**Comment by abbyraskin** [comment]
I made a ticket for your first bullet point, here: https://github.com/department-of-veterans-affairs/caseflow/issues/2316

I think I need more info about the second issue.
