### ISSUE TITLE
Documents List | Search: empty search 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2174]
**Description**
It seems like overkill to show the "no results found" view if a user has only typed a space.

## AC
- If a user types a space (or multiple spaces with no other characters), we do not perform a search, as if the field is completely blank -- we do NOT show them the "no search results found" view, and the documents list is unchanged.

## Related Issue
#2171

**Comment by gnakm** [comment]
@abbyraskin RE our in person discussion, I'm going to change this issue so that when a user searches a blank or spacebar, it doesn't do anything. Technically we shouldn't filter anything and I don't think it will cause any confusions. Please 👍 if you concur.

**Comment by abbyraskin** [comment]
@gnakm yes! updated the AC, and moving it over

**Comment by kierachell** [comment]
**PASSED**
<img width="723" alt="screen shot 2017-06-27 at 7 28 18 am" src="https://user-images.githubusercontent.com/18075411/27585422-33c99c5e-5b0a-11e7-82d7-d44a34f928ef.png">
