### ISSUE TITLE
FeatureFlag | Update feature flag user check to be case insensitive

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2179]
Currently our feature flag for whitelisted users is doing a check for whether a user with a known css_id is logging into the system. After the recent CSS bug where people were not able to access Reader due to the change in CSS_ID capitalization, we should be case insensitive in our checks.

**Comment by aroltsch** [comment]
I think @amprokop fixed it.

**Comment by amprokop** [comment]
yasss
