### ISSUE TITLE
Document list | Filter alert enhancement

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2181]
**Story**
As a user, I want to have more clear and accurate information about filtered documents list. 

## AC
- [ ] Verify that new copy is in information alert when documents list is being filtered.
- [ ] Verify that copy lists, in italics, the categories and issue tags the documents are being filtered by.
- [ ] Verify that 'clear all filters' is a link that allows users to clear filters and see all documents list. 

## Mock ups
Current message:
![image](https://cloud.githubusercontent.com/assets/13420618/26599143/92cb916a-4545-11e7-9e7f-71c3272ecac8.png)

New message:
![image](https://cloud.githubusercontent.com/assets/13420618/26599101/6d469b06-4545-11e7-934e-8950e4465c90.png)

## Copy
Showing limited results
Documents are currently filtered by Procedural, Medical and Right Knee. Click here to

**Comment by abbyraskin** [comment]
Closing in favor of #2496
