### ISSUE TITLE
Design Meeting 6/1

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2185]
Add your issues here:

| Topic 💡 | Time 🕚  | Who 👯 |
|-------------------- | ------ | --- |
Design Issue Checklist | 5 mins | Gina
V2 pilot usability/discovery questions | 10 mins | Shelly
Style guide topics | 5 mins | Shelly/anyone
Appeals-design-research folder structure | 5 mins | Shelly/Phillip
Consistent Versioning | 3 mins | Phillip

**Comment by shellicious** [comment]
I'd also like to talk about the use of the "Required" tag on form field questions. In particular: if all of the questions on a page are required, do we need to show "Required" on every question? I'm adding a general "Style guide topics" agenda item to cover that and any other style guide things folks might want to talk about. cc @gnakm @lakohl

**Comment by gnakm** [comment]
@shellicious Great question -- let's talk about it manana~

**Comment by lakohl** [comment]
wrong repo, my bad moving this to: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/249
