### ISSUE TITLE
Establish Claim Full Grant Test | Travis Master Build Failing

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2187]
## So I looked at the commits to master lately
<img width="159" alt="screen shot 2017-05-30 at 4 29 29 pm" src="https://cloud.githubusercontent.com/assets/18075411/26607344/0a5ac908-4564-11e7-9e4b-720638f6869a.png">

## Most of the failing builds are in Dispatch:
```
Establish Claim - ARC Dispatch

  As a manager

    View quotas and update employee count

    Edit individual user quotas

    View unprepared tasks page

  As a caseworker

    Assign the correct new task to myself

    Visit an Establish Claim task that is assigned to another user

    Go back and forward in the browser

    Cannot re-complete a completed task

    Cancel a claims establishment

    Error establishing claim

    For an appeal with multiple possible decision documents in VBMS

      Review page lets users choose which document to use

      the EP creation page has a link back to decision review

    For a full grant

      Establish a new claim with special issue routed to national office

      Establish a new claim with special issue routed to ROJ

      Establish a new claim with special issues by routing via email

      When there is an existing 172 EP

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
- Travis is nice enough to provide potential solutions in the link above:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by kierachell** [comment]
Currently hanging locally with 10 attempts under my belt.:
<img width="1131" alt="screen shot 2017-06-11 at 11 23 30 am" src="https://user-images.githubusercontent.com/18075411/27012146-6fedd570-4e98-11e7-938a-b41f781ab844.png">

**Comment by joofsh** [comment]
@sharonwarner based on all the recent flakiness in the test builds, I've moved this up to the top of the sprint (still no pressure to work on tango stuff, do cert v2 tickets first!)

**Comment by kierachell** [comment]
**PASSED**

Based on running `rake` about 50 times: there are other tests that are failing now.
