### ISSUE TITLE
Change window title for Missing Decisions and Canceled EPs

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2191]
As requested [here](https://github.com/department-of-veterans-affairs/caseflow/issues/1936#issuecomment-305026962), when the ARC manager clicks "View Claims Missing Decisions", a new tab/window should open with the title "Claims Missing Decisions".  Likewise, when "View Canceled EPs" is clicked, the new tab/window should open with the title "Canceled EPs".

**Comment by slj** [comment]
Solution in action:

![tabs_are_titled](https://cloud.githubusercontent.com/assets/1053255/26617693/887e10a2-45a4-11e7-88ca-b40ffdd0aad1.gif)

**Comment by astewarttistatech** [comment]
This will be tested after UAT dispatch testing

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Dispatch as a manager with claims established
2. On the manager dashboard select the option for "View Claims Missing Decisions" under BVA Reports subheading
3. Validate that a whole new tab/window opened. 

Screenshots: 
![missingclaims](https://cloud.githubusercontent.com/assets/23038505/26646529/fdd1ba9c-4609-11e7-8cc2-1829c19d68e9.gif)
