### ISSUE TITLE
Existing EPs | How to handle recently cancelled EPs

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2198]
This is an investigation - so I consider it a bug because I have no clue if any of the things below are "features".

### VBMS throws an error message when we try to create an EP when one was cancelled that same day.

```
<faultstring>Claim not established. A duplicate claim for this EP code already exists in CorpDB. Please use a different EP code modifier. GUID: d584ee8d-35c9-4bc8-92c0-94dfa06ee974</faultstring>
```
- If you go into VBMS you won't find that EP/code
- There is a 24-ish hour cache in VBMS that won't allow you to create an EP with the same modifier if one was cancelled that same day.
- We can just retry with an increase modifier
```
<ns4:message>Claim not established. A duplicate claim for this EP code already exists in CorpDB. Please use a different EP code modifier.</ns4:message>
```

cause, you know, VBMS has been literally telling to do that for ages.

- BGS has a service that allows you to delete an EP if you want, that's usually instantaneous

## Related
#2012

**Comment by lakohl** [comment]
@abbyraskin digging into your memory on this. If I recall correctly, cleared EPs are ones where the work is completed - correct? As a result, we should not be able to assign them?

**Comment by lakohl** [comment]
@abbyraskin ignore the comment above. Apparently we do support this functionality currently.

**Comment by sharonwarner** [comment]
- The cleared EPs should not show up as existing EPs
- @lakohl will look into the pmc-routed EPs

**Comment by lakohl** [comment]
@sharonwarner let touch base on this briefly so we can close it out or create a new PMC issue

**Comment by kierachell** [comment]
Currently causing Prod alerts:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/262/

**Comment by lakohl** [comment]
It seems like we should up the modifier when VBMS required, for all 070 labels (including PMC ones) rather than throwing an error.

**Comment by kierachell** [comment]
![screen shot 2017-07-21 at 1 06 14 pm](https://user-images.githubusercontent.com/18075411/28474155-73901f02-6e15-11e7-81f7-8c23693d5387.png)

**Comment by kierachell** [comment]
## Detecting PMC-routed EPs:
Is happening now, so that's done:
<img width="923" alt="screen shot 2017-08-10 at 11 20 31 am" src="https://user-images.githubusercontent.com/18075411/29177907-fda05628-7dbd-11e7-92fa-6c2771736bba.png">
<img width="723" alt="screen shot 2017-08-10 at 11 21 30 am" src="https://user-images.githubusercontent.com/18075411/29177934-137feb52-7dbe-11e7-8172-f0066220c6e8.png">

**Comment by joofsh** [comment]
@kierachell  The second part of the issue **Detecting existing EPs is inconsistent?**. It looks like the "172 - BVA Grant" is the existing EP that we do not detect, correct? Do you know what the `claim_type_code` is for that EP?

**Comment by joofsh** [comment]
Spoke with Artem and both issues have been addressed. Closing this issue for now!

**Comment by joofsh** [comment]
**PASSED**

**Comment by joofsh** [comment]
This occurred again in production on 8/24 
```
@claim={:benefit_type_code=>"1", :payee_code=>"00", :predischarge=>false, :claim_type=>"Claim", :end_product_modifier=>"070", :end_product_code=>"070BVAGRARC", :end_product_label=>"ARC BVA Grant", :station_of_jurisdiction=>"397", :date=>Tue, 22 Aug 2017, :suppress_acknowledgement_letter=>true, :gulf_war_registry=>false}
```
Maybe that 1 specific end product code isn't being handled properly?

**Comment by kierachell** [comment]
- August 24th `070RMNDARC`
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/262/events/7229/

- August 22nd `070BVAGRARC`
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/262/events/7004/

**Comment by lakohl** [comment]
@sharonwarner @sunil-sadasivan is this still relevant?
