### ISSUE TITLE
have monitoring

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#22]
> Will be good to have some browser info and whatever else. Not sure if we can use GA for internal stuff or what the deal is?

--

> @alex spoke with Marina who said the following: "You could snag the code from the bottom of employment center, it's the OPIA one (not the EP one)"

> Do you need anything from me to set it up?

--

> @KHarshawat @MarinaMartin Do we have access to the Google Analytics dashboard that that code snippet is linked to?

--

> Yup! It's the same one attached to the central analytics dashboard showing current traffic across all US sites too

**Comment by ErieMeyer** [comment]
Our friend @tdlowden helps run the Digital Analytics Program at GSA (which is then published analytics.usa.gov). Looping him here to help confirm that we can use the normal DAP links for an internal VA tool.

**Comment by tdlowden** [comment]
Hi all, and thanks @ErieMeyer. I'm not familiar with this project, but since DAP is intended to measure public interaction with federal websites, if the tool is internal, it'd be out of the scope of DAP.

**Comment by tdlowden** [comment]
If there is a need for a dashboard, you could surely implement a separate GA account and then use 

https://github.com/18F/analytics-reporter & https://github.com/18F/analytics.usa.gov to replicate what we've done.
