### ISSUE TITLE
Cancel Certification link should not have white background on hover

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2202]
![image](https://cloud.githubusercontent.com/assets/3781835/26687143/0b9101c0-46bd-11e7-97ca-89777f488698.png)

**Comment by nemodjuric** [comment]
After talking to design team, we decided to apply this change globally.

**Comment by kierachell** [comment]
**PASSED**

<img width="461" alt="screen shot 2017-06-15 at 8 21 42 am" src="https://user-images.githubusercontent.com/18075411/27181132-3ae3d4ce-51a4-11e7-989d-96f215001e60.png">
<img width="1209" alt="screen shot 2017-06-15 at 8 25 27 am" src="https://user-images.githubusercontent.com/18075411/27181134-3ae72246-51a4-11e7-8cd8-37a279a3839a.png">
<img width="301" alt="screen shot 2017-06-15 at 8 25 29 am" src="https://user-images.githubusercontent.com/18075411/27181133-3ae696f0-51a4-11e7-8b90-16a6fe969243.png">
