### ISSUE TITLE
[V2] Scenarios in demo environment for V2 NYC pilot training

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2206]
We should prepare the following scenarios in the demo environment for the V2 training session in NYC on Monday, 6/12/17:

Situation 1 [This one is close to the current path in demo]
- Step 1: Documents match.
- Step 2: VBMS and VACOLS do not match (user can pick either to move forward, or select a representative manually and see the range of options (Attorney/Agent/Other/Service organization that is listed/Service organization that is unlisted/No Representative)
   - If the user chooses VBMS or VACOLS as the source of truth, they see a message stating that Caseflow will update or not update the representative information accordingly.
- Step 3: User can choose that hearing preference has changed, or that it's unchanged. If unchanged, user sees a Form 9 and reports hearing preference.
 - Step 4: Sign and certify and confirmation page

Situation 2: show Mismatched documents page.

Situation 3 [This one is also close to the current path in demo]
- Step 1: Documents match.
- Step 2: VBMS and VACOLS do not match. When user selects "VBMS", they see a message stating that the address could not be updated, and it needs to be manually changed in VACOLS.
- Step 3: User can choose that hearing preference has changed, or that it's unchanged. If unchanged, user sees a Form 9 and reports hearing preference.
 - Step 4: Sign and certify and confirmation page

**Comment by amprokop** [comment]
```
- Step 1: Documents are mismatched, refresh page to continue (User doesn't have to go to VBMS to edit documents)
```

@shellicious ^ do you mean that we want a scenario where the user goes to an ID, then sees a mismatch, then refreshes the page and the docs are then matching? that will be kinda difficult. we already have `456C`, an id where the documents are not matching—any chance we can just use that, and then have Step 1 of Situation 2 just show matching docs?

**Comment by shellicious** [comment]
@amprokop that sounds good to me for showing mismatched docs. The other thing situation 2 shows is the edge case in which "VBMS" is selected, but the user still has to manually add the address in VACOLS. 

We could leave Situation 1 unchanged, then ask users to view the mismatched docs page, then ask them to do Situation 2 with starting with matching docs. 

I'll update the situations accordingly

**Comment by shellicious** [comment]
Update: got rid of situation 3 (VBMS/VACOLS data matches) since it can be explained easily with words, added a stub of a situation (calling it Situation 2) for seeing the mismatched documents page.

**Comment by kierachell** [comment]
Add the numbers/test cases here! https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/docs/dev.md

**Comment by nemodjuric** [comment]
"Situation 3
...
Step 2: VBMS and VACOLS do not match. When user selects "VBMS", they see a message stating that the address could not be updated, and it needs to be manually changed in VACOLS."
@amprokop I am not familiar with this user case scenario. In which case when user picks VBMS we show a message that it needs to be manually changed in VACOLS?

**Comment by laurjpeterson** [comment]
@nemodjuric Here's a ticket that accounts for this message - when the address needs to be manually changed in VACOLS.

https://github.com/department-of-veterans-affairs/caseflow/issues/2063

**Comment by astewarttistatech** [comment]
Situation 1:
![path1cv2](https://user-images.githubusercontent.com/23038505/27033881-46fc00b8-4f49-11e7-8957-dbe5bc100561.gif)

Situation 2: 
![mismatchdemo](https://user-images.githubusercontent.com/23038505/27033893-50575518-4f49-11e7-9d2f-4516e1382d60.png)

Situation 3:
