### ISSUE TITLE
Style guide | Buttons

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2212]
**Story**
As a developer and designer, I want an easy way to see what the buttons should look like across Caseflow apps!

## AC
- [x] Verify that these components are in the Buttons section of style guide
- [x] Verify that there are two subsections, Primary and Secondary with the appropriate buttons (see mock below)
- [x] **_NOTE: Take out the grey button at the bottom. That may be used for future._** 

Styling can be found in [USWDS
](https://standards.usa.gov/components/buttons/) Colors can be found in [Caseflow Style Guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#colors)

**Primary**

| Default  | Hover | Active |
|---------- | ------ | --- |
`primary` | `primary-darker` | `primary-darkest`
| `secondary` | `secondary-darker` | `secondary-darkest` |

**Secondary**

| Default  | Hover | Active |
|---------- | ------ | --- |
`primary` | `primary-darkest` | `base`

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/26703833/9bc8a248-46f9-11e7-9777-8a1212e8dacf.png)

**Comment by Sjones352** [comment]
@gnakm  and @mmlumba we already have Link buttons that are exactly the same as the secondary buttons that I am adding.  Please let me know what I should do.
 <img width="697" alt="screen shot 2017-06-12 at 2 40 44 pm" src="https://user-images.githubusercontent.com/23080951/27049394-33088fe8-4f7d-11e7-8d51-658e32fac800.png">
I think we would move the first set of Link buttons and make them secondary buttons and then the Link button section would point to theses buttons. 
<img width="687" alt="screen shot 2017-06-12 at 2 45 26 pm" src="https://user-images.githubusercontent.com/23080951/27049621-e0815c40-4f7d-11e7-9fbb-f20f3329e9da.png">

**Comment by mmlumba** [comment]
That approach makes sense to me. What do you think @gnakm ?

**Comment by Sjones352** [comment]
@gnakm would you like to add a description at button section. Currently it looks like this.
<img width="692" alt="screen shot 2017-06-12 at 5 08 23 pm" src="https://user-images.githubusercontent.com/23080951/27055253-cd10ac6a-4f91-11e7-9093-ea09ee8ee8ec.png">

**Comment by gnakm** [comment]
I'm issue creepin a bit but can we do it like this:

Buttons

Primary buttons
Default | Hover | Active

Secondary buttons
Default | Hover | Active

Disabled buttons

Button color: $color-gray-lighter
Button text color: $color-gray-dark

Link buttons
Default | Hover | Active


![image](https://user-images.githubusercontent.com/13420618/27055186-a006d3e8-4f91-11e7-92e3-838932faf207.png)

**Comment by Sjones352** [comment]
@gnakm is  Disabled button a subsection?

**Comment by Sjones352** [comment]
@mmlumba Currently looks like this
<img width="690" alt="screen shot 2017-06-12 at 6 22 43 pm" src="https://user-images.githubusercontent.com/23080951/27057932-4805f178-4f9c-11e7-82f0-7686613b3f0e.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access the living style guide
2. Navigate to the Buttons section by navibar or by scrolling
3. Validate the UI and copy of the buttons section against mocks and AC

Screenshots: 
![sgbuttons](https://user-images.githubusercontent.com/23038505/27184263-b1657930-51af-11e7-8161-220bc47e3d62.gif)
