### ISSUE TITLE
Check Documents | We are not checking BFMPRO to be `ADV` to determine whether appeal is ready to certify

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2213]
After a `BRIEFF`ing from @cmgiven it has been determined that we're sorta "just trusting VACOLS" to give us Appeals ready to certify:

- The following appeal with `HIS` status:
```
 BFKEY   BFCORLID BFCORKEY   SNAMEF SNAMEL       SSN SNOTES BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19               BFSSOC1               BFSSOC2
1 888901 524259725C CK174723 Collette   Tran 524259725    uat    3    HIS     <NA> 2017-02-21 15:14:46.0 2016-11-13 15:14:46.0 2016-08-05 15:14:46.0 2017-03-03 15:14:46.0 2017-01-02 15:14:46.0
  BFSSOC3 BFSSOC4 BFSSOC5 BFSO REPTYPE REPFIRST REPLAST REPADDR1
1    <NA>    <NA>    <NA>    L    <NA>     <NA>    <NA>     <NA>
```
- Shows up just fine in Certification
<img width="1023" alt="screen shot 2017-06-01 at 7 58 01 pm" src="https://cloud.githubusercontent.com/assets/18075411/26705587/f8427fd4-4704-11e7-8880-87a906200434.png">

- Even though we _should_ expect only `BFMPRO=ADV` Appeals and _hopefully_ that's what VACOLS sends us.

## Questions
1. Does this happen ever?
1. Do we keep on trusting VACOLS?
1. How many more puns will @cmgiven tolerate?

**Comment by cmgiven** [comment]
I have a very low pun tolerance.

**Comment by kierachell** [comment]
too old to care for this
