### ISSUE TITLE
Implement new styling for Veteran Name and ID

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2216]
As a user, I would like to see consistent styling of the Veteran Name and ID across Caseflow apps.

## AC
1. Verify that the veteran name and ID number currently to the the right of the application name 'eFolder Express' are removed.
1. Verify that the user name displays in title case, 17px, color #5B616B
1. Verify that the Veteran Name is left aligned and displays in all caps, 22px, color #323A44
1. Verify that the label Appeal ID is changed to Veteran ID
1. Verify that the Veteran ID is displayed in color: #5B616A, style: bold, 17px, inside a button to the left of the 'copy' icon (also color: #5B616A). Button fill color: #FFFFFF, with a border: 2px, color: #5B616A.
1. Verify that there are 30px above the Vet ID button, and 30 px below the vet ID button
1. Verify that when there is not a box or border below the Vet Name and ID, a line is added between them and the progress bar:

## Mocks

<img width="680" alt="screen shot 2017-07-27 at 3 11 13 pm" src="https://user-images.githubusercontent.com/4975959/28687866-f1458bd6-72dd-11e7-9ee9-518ac94b6812.png">

<img width="815" alt="screen shot 2017-06-02 at 10 18 59 am" src="https://cloud.githubusercontent.com/assets/4975959/26730623/9050379c-477f-11e7-99b8-82a65093aba9.png">
<img width="821" alt="screen shot 2017-06-02 at 10 18 37 am" src="https://cloud.githubusercontent.com/assets/4975959/26730626/9321c1b6-477f-11e7-87d2-fb9bf17536f3.png">

**Comment by lakohl** [comment]
In cases where there already a box/border under the Vet Name and ID, we can elect to add a line with the it's pre-assigned padding of 40px.

<img width="714" alt="screen shot 2017-06-02 at 9 32 24 am" src="https://cloud.githubusercontent.com/assets/4975959/26728605/c6c5d84c-4778-11e7-9180-47340fbb5e28.png">

<img width="679" alt="screen shot 2017-06-02 at 9 33 14 am" src="https://cloud.githubusercontent.com/assets/4975959/26728608/cdbb96e6-4778-11e7-9543-3791902ce061.png">

**Comment by gnakm** [comment]
This is great and I like the use of the horizontal line. 40px makes the most sense because as you mentioned we have the margin-bottom padding for the horizontal line. I do get a little concerned that the canvas is pushed down a lot and content won't be visible.

**Comment by lakohl** [comment]
@gnakm I had/have the same concern, though I realize we use 40px padding on top in bottom in Certification today. Here are examples with 30px, let me know if you prefer them.

<img width="752" alt="screen shot 2017-06-02 at 10 14 14 am" src="https://cloud.githubusercontent.com/assets/4975959/26729664/4d03a044-477c-11e7-891c-2fac3b9145a7.png">
<img width="743" alt="screen shot 2017-06-02 at 10 13 56 am" src="https://cloud.githubusercontent.com/assets/4975959/26729670/51a876c4-477c-11e7-9cd0-48a4191ec81d.png">

<img width="815" alt="screen shot 2017-06-02 at 10 18 59 am" src="https://cloud.githubusercontent.com/assets/4975959/26729840/e9c68b1c-477c-11e7-9da8-d9ea68b720e9.png">

<img width="821" alt="screen shot 2017-06-02 at 10 18 37 am" src="https://cloud.githubusercontent.com/assets/4975959/26729843/eeb1f53a-477c-11e7-8684-934db2d2a000.png">

**Comment by gnakm** [comment]
I like it wayyyy better! Does that mean we should change horizontal margin-bottom to 30px? Cue: Angry devs 😬

**Comment by shellicious** [comment]
@lakohl @gnakm update: I discussed foxtrot building this out with @amprokop, who said that the team had bandwidth next sprint (beginning Monday 6/12). Let us know if you find engineers to implement this before then, otherwise we'll plan on foxtrot building the component next sprint. 

Are the designs in the most recent comment finalized?

**Comment by lakohl** [comment]
@shellicious It would be great if Foxtrot could take this on this sprint (we are down to 1 engineer on Tango and Whiskey also just lost Nick). I would suggest that they create it first as a Certification update and then as a Style Guide update. The AC above are correct and ready to go.

**Comment by shellicious** [comment]
We'd love to put it in this sprint, but the team has it's collective hands full getting V2 ready for the demo. If there is space next week / not too many bugs to fix during the pilot, we can add it in. Right now it's looking like the next sprint is best for this ticket.

**Comment by Sjones352** [comment]
@lakohl, @aroltsch  and @shellicious if this has not yet been done, I can do it this sprint.

**Comment by amprokop** [comment]
@Sjones352 — please do! Thanks!

**Comment by Sjones352** [comment]
Currently eFolder looks like this. 

<img width="1263" alt="screen shot 2017-07-26 at 9 14 00 pm" src="https://user-images.githubusercontent.com/23080951/28650151-b3fc977e-7247-11e7-9e6e-5e0f39827d79.png">

**Comment by Sjones352** [comment]
Since there are many mocks on this issue. @lakohl  can you please verify which one is correct and update the mock on the original ticket with the latest. Thanks

**Comment by Sjones352** [comment]
@Lara for this part in the AC, 'Verify that the veteran name and ID number currently to the the right of the application name 'eFolder Express' are removed' do you want them to be removed from all the other pages of eFolder too just like it is in certification?

**Comment by lakohl** [comment]
@shellicious @amprokop working on styling of the Veteran Name and ID across our apps. It seems that in Certification it currently appears Last Name, First Name, Middle Initial. Is this your desired order? Have you received any user feedback about how they prefer the name displayed e.g. FirstName Last Name or  LastName, First Name ?

**Comment by shellicious** [comment]
@lakohl woo, glad you are taking this on! I haven't received user feedback about Veteran Name (or the username in the upper right corner). I'm down with whatever helps us be consistent across apps.

**Comment by Sjones352** [comment]
@lakohl Currently Certification V2 is looking like this.

<img width="1232" alt="screen shot 2017-08-01 at 9 57 09 pm" src="https://user-images.githubusercontent.com/23080951/28854316-7009acc0-7704-11e7-90a6-bc5df4ad723f.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access eFolder
2. Search an appropriate file number
3. On the results page, verify the new Veteran name and ID implementation
4. Access Certification V2
3. Verify the new Veteran name and ID implementation

Screenshots:
<img width="1256" alt="screen shot 2017-08-02 at 12 21 26 pm" src="https://user-images.githubusercontent.com/23038505/28883760-88c02496-777d-11e7-8273-271894e394a0.png">
<img width="1256" alt="screen shot 2017-08-02 at 12 22 24 pm" src="https://user-images.githubusercontent.com/23038505/28883761-88c23470-777d-11e7-93ec-6e36c0e1f433.png">
