### ISSUE TITLE
Create "Hearing Worksheet" page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2218]
As a judge, I would like to see detailed information about a Veteran and their hearing, and be able to take notes on the hearing.

## AC:
- Page renders and is styled properly.
- Data is hardcoded for now

Technical Notes:
  - ignore rep name for now
  - No need to hook up the page to redux store yet
  - we don't need to save the values to the DB
  - For SSOC documents, show the newest date only

## Mock:
![hearing worksheet online mvp 8](https://user-images.githubusercontent.com/4975959/27534486-243a876a-5a35-11e7-91e0-7a517a0f7945.png)

Invision Link: https://va-gov.invisionapp.com/share/A7CBHYUUY

**Comment by joofsh** [comment]
CC @lakohl Can you add the latest designs & any AC you think are appropriate?

**Comment by lakohl** [comment]
New Invision link for the first three pages of Hearing Prep is here: https://va-gov.invisionapp.com/share/PGC0HUR64

Hearing Worksheet: 
![hearing worksheet online mvp 4](https://cloud.githubusercontent.com/assets/4975959/26789568/b39388ec-49de-11e7-82a0-ab3081a3bdfc.png)

**Comment by lakohl** [comment]
I took out the original claim. Uploaded mock at the top of the issues.

**Comment by lakohl** [comment]
@joofsh down the road, we will want to show all the SSOCs associated with the appeal stream being heard.

**Comment by lakohl** [comment]
@slj I updated the mock above per our conversation yesterday.

**Comment by lakohl** [comment]
Revised mock based on feedback form judges and Reader designs. For now we will only have the judge edit the Description but not the issue itself.
![hearing worksheet online mvp 7](https://user-images.githubusercontent.com/4975959/27290450-4e19ce06-54db-11e7-8964-a77f21cc3b9f.png)

**Comment by lakohl** [comment]
Updated Invision link under AC

**Comment by kierachell** [comment]
### Are these meant to be checkable?
- Checkboxes checkable?
- Textboxes expandable?
![click](https://user-images.githubusercontent.com/18075411/28441469-015daa4a-6d79-11e7-8064-2290cf5099dc.gif)

### Is this to be populated with real data now or is there backend ticket?
<img width="1233" alt="screen shot 2017-07-20 at 6 15 45 pm" src="https://user-images.githubusercontent.com/18075411/28441475-0af6bbc8-6d79-11e7-9d33-fd6c2736f787.png">

### One nit for the edge of the box:
<img width="211" alt="screen shot 2017-07-20 at 6 24 42 pm" src="https://user-images.githubusercontent.com/18075411/28441476-0af6cdca-6d79-11e7-98e8-d120eb5ad833.png">

**Comment by lakohl** [comment]
@kierachell yes, the preliminary impression boxes should be checkable

**Comment by kierachell** [comment]
@lakohl 
- Are the textfield values going to be saved eventually? Should there be limits?
- AC does not state if those text field should expand?

**Comment by kierachell** [comment]
@sharonwarner 
- Can we break up the backend AC/tickets into manageable chunks
  - e.g. pull VACOLS data properly
  - Pull Document data properly (VACOLS data vs VBMS date?)
  - Representative name?
  - Saving our own values to PG
  - Redux/responsiveness stuff?
  - Textfield limits?
  - Is this even writing to VACOLS?

**Comment by kierachell** [comment]
@slj 
### One more nit: that line under Relevant Docs and Issues
![screen shot 2017-07-21 at 1 11 16 pm](https://user-images.githubusercontent.com/18075411/28474983-a2c0acf8-6e18-11e7-9089-e9347ead62d9.png)

**Comment by sharonwarner** [comment]
Spoke with @kierachell , just one thing needs to be fixed still.

The box highlighting is inconsistent. Some boxes are highlighted on all 4 sides while others are just 1, 2, or 3 sides. We need to have all sides highlighted.

**Comment by kierachell** [comment]
Double checked the highlighting this morning:
<img width="1236" alt="screen shot 2017-08-03 at 10 54 57 am" src="https://user-images.githubusercontent.com/18075411/28928065-43d12336-783a-11e7-8926-7b4eb37de86f.png">
<img width="339" alt="screen shot 2017-08-03 at 10 55 03 am" src="https://user-images.githubusercontent.com/18075411/28928064-43cf3580-783a-11e7-9940-a6c638a02d07.png">

**Comment by joofsh** [comment]
@kierachell I've updated the AC to be more clear. The data being hardcoded is okay for the sake of this ticket

**Comment by astewarttistatech** [comment]
**PASSED**

Env:UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Select a docket
3. Select an Appellant
4. Verify that the next page that appears is the Hearings Worksheet page
5. Verify the UI against mocks and AC

Screenshots:
![hearingworksheet](https://user-images.githubusercontent.com/23038505/29027256-e756928c-7b4d-11e7-9497-1681ef431579.png)
