### ISSUE TITLE
[V2] Copy tweak: Change confirmation page heading from "Congratulations!" to "Success!"

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2220]
## Acceptance Criteria

- Heading on Confirmation page should say "Success!", not "Congratulations!"

## Mock ups

![confirmation](https://cloud.githubusercontent.com/assets/1178390/26734030/b1d7476a-478a-11e7-8c71-fbdeb7431d9a.png)

**Comment by kierachell** [comment]
**PASSED**
that was easy...
<img width="1043" alt="screen shot 2017-06-06 at 2 07 23 pm" src="https://user-images.githubusercontent.com/18075411/26844501-a5a95eda-4ac1-11e7-9eb9-726d0db9090d.png">
