### ISSUE TITLE
On pageload into Reader's pdf list view, category filter by query param

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2222]
As a reader user, I would like to enter reader and already see the documents filtered by my desired category.

Technical notes:
- Add a query param that gets used on react app boot to determine the initial category filters

Acceptance Criteria:
- Button on hearing worksheet page should go to the welcome page. (In a future PR, we'll link to the correct page)

**Comment by joofsh** [comment]
CC @laurjpeterson @mdbenjam for awareness

**Comment by kierachell** [comment]
## Hearing worksheet button leads to welcome gate:
<img width="1358" alt="screen shot 2017-09-05 at 9 17 31 am" src="https://user-images.githubusercontent.com/18075411/30063026-2d7951e4-921b-11e7-9d0d-6827f2ac102e.png">
<img width="801" alt="screen shot 2017-09-05 at 9 18 03 am" src="https://user-images.githubusercontent.com/18075411/30063027-2d7d84d0-921b-11e7-8133-ffbfa67278ea.png">

**Comment by kierachell** [comment]
### I am unable to `Clear all filters` if I use the `?category=` query
<img width="786" alt="screen shot 2017-09-05 at 9 15 19 pm" src="https://user-images.githubusercontent.com/18075411/30090181-9aa1cf30-927f-11e7-8a46-08af51213a6b.png">

if I click `Clear all filters` - nothing happens:
<img width="832" alt="screen shot 2017-09-05 at 9 16 44 pm" src="https://user-images.githubusercontent.com/18075411/30090194-a9398786-927f-11e7-8ab7-2bdc86e3e5e9.png">


- It only works if I open the dropdown and unselect the category

**Comment by kierachell** [comment]
**PASSED**

Well the nice side-effect is that they all work now:
![theyallwork](https://user-images.githubusercontent.com/18075411/30141345-f3798d54-9348-11e7-8a2c-47993a1fc3f9.gif)
