### ISSUE TITLE
BVA Dispatch Manager View- show all missing decisions

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2227]
**Show all Claims Missing Decisions**

Rolandus Branch, the BVA Dispatch Manager, asked if we could surface a comprehensive list of the claims that are missing decisions. Currently on the BVA Dispatch Manager view, we only surface claims that are missing decisions which are being routed to ARC - so we filter out Denials, claims with a Private Attorney, VHA claims etc...

It would be helpful if we could differentiate between where the claims missing decisions are routed. However, in order to have a better understanding of BVA Dispatch's performance, it would be good to include all types of claims on the Missing Decisions page.

**Comment by cmgiven** [comment]
So there are only two exclusions that we do not capture on the missing decisions page:

1. Private attorneys.
2. Non-VBMS cases (those that do not have the VBMS checkbox ticked in VACOLS).

1 will soon be incorporated.

Is there a need to check 2? Would a paper case still have a decision uploaded to VBMS?

**Comment by lakohl** [comment]
@cmgiven I I would like to know more about non-VBMS cases. 

This was Denese's description of claims not sent to/processed at ARC:

'Claims involving **education** – go to the designated education center.
Claims for **National Cemetery** go back to that location. 
The **insurance** claims go back to the designated insurance centers.
The Education, National Cemetery, and Insurance Offices are the only facilities that process their own claims.'

**Comment by cmgiven** [comment]
Can you say more about what you'd like to know? What are we trying to determine?

**Comment by lakohl** [comment]
I'd like to compile a list of the types of claims that aren't flowing through Caseflow Dispatch and therefore aren't showing on the missing decisions pg



Sent with Good (www.good.com)


-----Original Message-----

**Comment by lakohl** [comment]
Private Attorney claims should start showing here. Need to gather more info on what other types of claims could flow through Caseflow Dispatch and are not today

**Comment by lakohl** [comment]
@cmgiven Can we talk about this on monday?

**Comment by lakohl** [comment]
@cmgiven Can we close this?

**Comment by cmgiven** [comment]
Yes.
