### ISSUE TITLE
Document viewer | Top toolbar: Open link in new tab indicator

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2228]
**Description**
We've received a couple of comments on the top tool bar icons:
1. Document Type link on the top toolbar doesn't look like it will open in a new tab. Make link look like it will open in a new-tab! 
2. The zoom icons aren't that obvious. We are solving this by putting the zoom in and out ones together so that + and - have more context next to each other and swapping out old fit to screen icon for a new one. We also added label zoom and grouped all the zoom icons together. 

## AC
- [ ] Verify that when you hover over the document type, a hover message shows saying "Open in new tab."
- [ ] Add the word 'Zoom:' on the left of zoom icons
- [ ] Verify that the spacing between icons follow the specs mock below.
- [ ] Verify new icons are replacing old ones (see svgs below).

## Mock up 

![image](https://user-images.githubusercontent.com/13420618/27438110-389382a8-5732-11e7-8e14-caf8e31390cb.png)

Hover
![image](https://user-images.githubusercontent.com/13420618/27438099-2dea23de-5732-11e7-83eb-6a018ca012fd.png)

With specs
![image](https://user-images.githubusercontent.com/13420618/27438047-14b99c8c-5732-11e7-849e-b7fca8e0c8e5.png)

## SVGS

- [External link icon](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/external-link-white.svg)
- [New download icon](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/download-white.svg)
- [New fit to screen icon](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Fit-to-screen-white.svg)

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF, Chrome, IE

Steps to Validate: 
1. Access Reader
2. Select a document from the Document List view
3. Verify that the title of the document should be a link and there should be an icon to open the document in a new window

Screenshots: 
<img width="1135" alt="screen shot 2017-07-19 at 11 01 21 am" src="https://user-images.githubusercontent.com/23038505/28374295-53bc2b5c-6c72-11e7-9e1a-81fdc779f7af.png">
