### ISSUE TITLE
Add transition fade in/out for hidden/unhidden fields

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#223]
This will add more visual queueing for users to know when a field is appearing or disappearing.

Examples where there are no transitions:

![1448316061](https://cloud.githubusercontent.com/assets/950486/11351324/02a1c168-9204-11e5-95cf-befd2d07b80f.gif)

**Comment by webinista** [comment]
Notes for myself (subject to change):
- Use a `MutationObserver` callback to toggle a class on the `fieldset` parent
- In the `change` event handler, remove the `hidden` attribute and add a `transitionend` event handler that sets the `hidden`attribute when the transition ends.
- Progressively enhance just in case someone tries to use the app with IE < 11 (which lacks support for `MutationObserver`).
