### ISSUE TITLE
Document Viewer | Bottom toolbar shift bug

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2230]
**Description**
Currently, the page and document number at the bottom of the toolbar shifts when switching between documents. 

Wondering if this can be fixed when [page indicator](https://github.com/department-of-veterans-affairs/caseflow/issues/1884) is being implemented 🤔 

## AC
- [ ] Verify that Page [#] of [total] and document number is not moving when switching between documents. 

**_Note: Page indicator was added so this is the most accurate image of the toolbar. Gif below was shot previous to this new update so can't see page indicator._** 

![image](https://cloud.githubusercontent.com/assets/13420618/26791711/f06085d4-49e5-11e7-83e3-5eeb47ac5211.png)

![bottom-footer-shift](https://cloud.githubusercontent.com/assets/13420618/26683937/81e862e6-46b3-11e7-9aaa-46131eef4299.gif)

## Related issue
#1884

**Comment by astewarttistatech** [comment]
**FAILED**

Shifts when you go back to the first document. 

Current view: 
![readerbottomshift](https://user-images.githubusercontent.com/23038505/27135291-24ba13de-50e6-11e7-8c50-07b34ed3c4b7.gif)

**Comment by tejans24** [comment]
It seems like the changes for this were reverted by https://github.com/department-of-veterans-affairs/caseflow/pull/2291 by accident. I will commit these changes again.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT and Dev
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Select a multi-page document
3. Shift between all page and see if the footer toolbar shifts at all

Screenshots: 
![readerbottomshift](https://user-images.githubusercontent.com/23038505/27184139-2b1d4ede-51af-11e7-9e2c-6820336c2ab9.gif)
