### ISSUE TITLE
Document List | Search: "and" instead of "or" logic

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#2231]
**Context**
Currently, we search using "or" logic; users have reported some confusion, as they  expect to see a more refined (shorter) list of results as they enter more text into search.

## Acceptance Criteria
- When a user enters more than one word into search, the results are narrowed to  show only those results that match the entire phrase
  - e.g., entering "Form 9" would show documents matching the entire phrase "form 9", rather than all the documents with either "Form" or "9" attributes.

**Comment by tejans24** [comment]
I'm working on this

**Comment by kierachell** [comment]
**PASSED**
![aaaaaand_search](https://user-images.githubusercontent.com/18075411/27585946-3ed7c34e-5b0c-11e7-9e28-dacc1dfba5dd.gif)
