### ISSUE TITLE
Even with fuzzy date matching, SSOCs should only match 1:1

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2236]
If SSOC dates in VACOLS are within the fuzzy time and there's one SSOC document in VBMS, then it currently matches to both VACOLS dates. We should ensure that SSOCs in VBMS -> VACOLS have a 1:1 relationship.

![image](https://cloud.githubusercontent.com/assets/3781835/26796519/c8d02774-49f7-11e7-97ad-5e2feba98489.png)

### Acceptance Criteria ###
- If VACOLS SSOC dates are 06/01/2017, 06/02/2017, and 06/03/2017, and there is only one VBMS SSOC date of 06/02/2017, it should match only to the 06/02/2017 VACOLS SSOC and not others.

**Comment by aroltsch** [comment]
@amprokop I think this is done. See my PR: https://github.com/department-of-veterans-affairs/caseflow/pull/2225

**Comment by amprokop** [comment]
@aroltsch — i agree. We can close this. 👍 :clinking_glasses:
