### ISSUE TITLE
Document List | Expanding long comments is fun

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2239]
# Description
When a Comment has a really long word, then the UI breaks.

Spaces are handled... ok? still a bit ugly.

## Reproduction Steps

**Scenario 1 -**

1. Go to *Document View*
1. Write a really long no-space string
1. See UI break when you save it
1. Go to *Document List*
1. Expand the Comment
1. See the table explode

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Long String]_**
![longcommentexpand](https://cloud.githubusercontent.com/assets/18075411/26800201/668bd658-4a06-11e7-9fc8-4b252313d5b1.gif)

**_Scenario 1 - [Long String Doc]_**
<img width="402" alt="screen shot 2017-06-05 at 3 45 58 pm" src="https://cloud.githubusercontent.com/assets/18075411/26800206/71509d26-4a06-11e7-8986-b68d2b29ae7f.png">

**_Scenario 1 - [With Spaces]_**
<img width="1166" alt="screen shot 2017-06-05 at 3 46 30 pm" src="https://cloud.githubusercontent.com/assets/18075411/26800212/7b8b0cea-4a06-11e7-9be4-418c5799db7e.png">

**Comment by mdbenjam** [comment]
This seems to work now.

**Comment by mdbenjam** [comment]
<img width="1017" alt="screen shot 2017-09-19 at 5 00 34 pm" src="https://user-images.githubusercontent.com/3885236/30615192-15c214a4-9d5c-11e7-81ea-839a31ca85d0.png">

**Comment by kierachell** [comment]
**PASSED**

looks aight now


<img width="410" alt="screen shot 2017-09-20 at 8 20 30 am" src="https://user-images.githubusercontent.com/18075411/30643360-9feaeeb4-9ddc-11e7-9c75-9ed121708a42.png">
<img width="904" alt="screen shot 2017-09-20 at 8 20 39 am" src="https://user-images.githubusercontent.com/18075411/30643361-9feedb50-9ddc-11e7-9fc9-a1902a4a47b1.png">
