### ISSUE TITLE
Document Viewer | Open menu button relocation

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2242]
**Description**
The open menu button link on the top toolbar is placed at the wrong location. 

## AC
- [ ] Place Open Menu button link 40 px left of edge of toolbar and zoom options + download icons 40px to the right of it

Current view:
![image](https://cloud.githubusercontent.com/assets/13420618/26799970/8d402304-4a05-11e7-966b-ad3cccae8eef.png)

Expected view:
![image](https://cloud.githubusercontent.com/assets/13420618/26801499/151f6e10-4a0b-11e7-898f-dc709e2340ad.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26801192/10e18046-4a0a-11e7-831b-f32a153bdfeb.png)

**Comment by astewarttistatech** [comment]
@mmlumba its 41px on the right side of the Open Menu button. See below 
<img width="1302" alt="screen shot 2017-06-21 at 9 08 56 am" src="https://user-images.githubusercontent.com/23038505/27385668-6acacfa0-5661-11e7-8b60-d32a69a78e7e.png">
![Uploading Screen Shot 2017-06-21 at 9.09.17 AM.png…]()

**Comment by mmlumba** [comment]
@astewarttistatech Here's 40px on this screenshot:
<img width="1280" alt="screen shot 2017-06-21 at 9 23 40 am" src="https://user-images.githubusercontent.com/4773320/27386323-734f8aa6-5663-11e7-8965-892b0b1a26ae.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT/Dev
Browsers: FF and Chrome

Steps to Validate: 
1. Access reader
2. Close the open menu, to the right of the screen
3. Verify that the Open Menu button is there 
4. Verify the button's spacing from the right to the end of the page and from the left to the next web element. 

Screenshots: 
see above
