### ISSUE TITLE
Hearing Worksheet | [Backend] Load all appeal streams into hearing model

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2245]
For a given hearing and Veteran, load information about all active appeal streams. 

#### Acceptance Criteria
- create an `active_appeal_streams` method on the hearing model. This method returns all appeals associated to this hearing (through `folder_nr`), have a form 9 submitted, and have no decision yet

Technical Notes:
- A hearing is directly associated to 1 appeal (through FOLDER_NR). Through that direct association, we can look up the Veteran. From the Veteran's file_number, we can look up all other existing appeals in VACOLS that are active. 
- All appeals must be "ready for hearing". This means a form 9 has been submitted, but no decision has yet been made

**Comment by aroltsch** [comment]
@cmgiven and @joofsh do you know which field in `brieff` should I be using to determine that an appeal is ready for hearing (a form 9 has been submitted, but no decision has yet been made). Can I use `brieff.bfha`?

**Comment by joofsh** [comment]
we should be able to use `brieff.bfdec`. See us referencing it in [appeal repository](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/appeal_repository.rb#L109)

**Comment by cmgiven** [comment]
`BRIEFF.BFDDEC` is the decision date, yes. I believe we generally check for whether the stream has been finalized by looking for whether `BRIEFF.BFDC`, the appeal disposition, is null, but these should be set simultaneously. We know if a Form 9 has been submitted if `BRIEFF.BFD19 is not null`.

**Comment by kierachell** [comment]
- How does a hearing get associated with an appeal? Currently appeals are not loaded for any of the hearings:
```
Hearing.all.sample.appeal
  Hearing Load (1.7ms)  SELECT "hearings".* FROM "hearings"
[2017-08-23 12:49:15 -0400]   Hearing Load (1.7ms)  SELECT "hearings".* FROM "hearings"
=> nil
```

**Comment by aroltsch** [comment]
@kierachell a hearing should have an appeal_id in the `hearings` table

**Comment by aroltsch** [comment]
Please re-test.

**Comment by kierachell** [comment]
**PASSED**

Reloaded hearings in UAT:
- Ran the method: `active_appeal_streams`
- Extracted BFKEYS from loaded appeals
- None of the appeals BFDDEC
- All the appeals had BFD19
