### ISSUE TITLE
Document List | Filtered state preserves documents which no longer fit the criteria

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2247]
# Description
When viewing a _filtered_ Document List,
Then going to view a Document from that list and removing/editing the attribute/tag/comment that caused that Document to be in the filtered view,
if I return to the Document List, it will keep the "no longer applicable" Document in the list.

## Reproduction Steps

**Scenario 1 -**

1. Go to Document List
1. Filter by something and get `x` amount of documents
1. Go view one of those documents
1. Edit/Remove the item/tag/category/comment/whatever that was used to filter the Document
1. Go back to List view
1. Find the Document still in the list.
1. Sigh....
1. Be forced to reapply the filter...
1. Think to yourself: "VBMS is better than this crap."

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Labels]_**
![updatefilteredview](https://cloud.githubusercontent.com/assets/18075411/26830963/b8b29a1a-4a98-11e7-8b68-65ec32f33c6c.gif)

**_Scenario 1 - [Comments]_**
![removecomment](https://cloud.githubusercontent.com/assets/18075411/26830973/bfb12afc-4a98-11e7-8033-f3e8e5457028.gif)

**_Scenario 1 - [Edited Value]_**
<img width="1119" alt="screen shot 2017-06-06 at 9 14 06 am" src="https://cloud.githubusercontent.com/assets/18075411/26830982/c68f5e7a-4a98-11e7-91de-2dd4720a4639.png">

**_Scenario 1 - [Edited Value]_**
<img width="428" alt="screen shot 2017-06-06 at 9 17 22 am" src="https://cloud.githubusercontent.com/assets/18075411/26831040/fb0db8ea-4a98-11e7-98b1-105083367a32.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by gnakm** [comment]
Interesting situation. 

- When a user un-clicks a category and goes back to documents list, we should no longer show that document. 
- In this scenario, we should jump to last last document in the view

@mdbenjam Curious to hear your thoughts on this
/cc @abbyraskin

**Comment by gnakm** [comment]
I just tested this and it's been fixed. Closing.
