### ISSUE TITLE
Discussion: Commit Practice

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2249]
![image](https://cloud.githubusercontent.com/assets/829827/26832869/d3b84c0a-4a9e-11e7-9a6c-6ec925ee890a.png)

When you use the "Squash and Merge" button on GitHub, it defaults to creating a commit message that's just the concatenation of each squashed commit message. For example, see d5ab5a00:

![image](https://cloud.githubusercontent.com/assets/829827/26832923/f3826bd8-4a9e-11e7-91a4-266f139c0c79.png)

We have two options:

1. ❤️ Adopt a team norm of editing the squashed commit message to include something more meaningful.
1. 🎉 Continue with this practice, and don't care about commit messages.

Vote in the following way via a reaction on this issue:

❤️ – Have more meaningful commit messages
🎉 – Have less meaningful commit messages but an easier time committing

If you think this is worth discussing, please post your thoughts on this thread.

**Comment by askldjd** [comment]
This is a good guideline that I've always liked.
https://chris.beams.io/posts/git-commit/

Also, at one point, we were going to use git logs to generate changelogs. Is that still on the roadmap?

**Comment by NickHeiner** [comment]
> Also, at one point, we were going to use git logs to generate changelogs. Is that still on the roadmap?

I have no knowledge of this, but I'm happy to look into it if there's a strong need.

**Comment by slj** [comment]
As much I love to hit `Squash and merge` and keep it moving, we can definitely benefit from more concise commits.  If that means I have to get better at (gulp) `git rebase`, well...time to grow...

**Comment by NickHeiner** [comment]
Nothing we're discussing involves getting better at `git rebase`, although that is a good life goal. :smile:

We're just talking about editing this text field instead of accepting the default value, which is a concatenation of every commit message:

![image](https://user-images.githubusercontent.com/829827/26836367-aa7a9866-4aa8-11e7-8f13-b132cae625c0.png)

**Comment by slj** [comment]
I'll definitely be doing that from now on.

**Comment by NickHeiner** [comment]
There is consensus that we should have good commit messages. Closing this out.
