### ISSUE TITLE
Discussion: Appeals Team Norms (discussion after standup Wednesday, 6/21)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2250]
Last retro (6/2) surfaced some new ideas about meeting norms, which started a discussion around overall team norms. Many of these team norms already exist or came out of retro, and Nick, Abby, Sharon and I discussed others that we'd love the team's input on. Here's a ticket for us to discuss these norms. Comment away!

Once we have the discussion as a team, the outcome will be posting these on github as a reference.

### Meetings
- **Goal: Respect teammates' time during meetings**
  - Practice: Schedule meetings for 20 minutes or 50 minutes
  - Practice: Include those who could be interested/valuable in the meeting, but instill the norm that teammates don't feel obligated to attend meetings
   - Practice: Meeting leader establishes laptop policy at the start of each meeting
- **Goal: Continuous meeting improvement/audit**
  - Practice: Each teammate has the right to ask why there needs to be a meeting for a topic. That teammate should propose an alternative.
- **Goal: Make meetings productive**
  - Practice: Meetings should have an agenda. The agenda is primarily - **what are the decisions that need to be made during this meeting.** Communicate agenda in meeting invite and/or Slack in advance.
  - Practice: Every meeting has a facilitator.  A facilitator keeps the discussion on topic, tells people when to take things offline if they're getting side-tracked, prepares and keeps the agenda, drives decisions and action items.  
  - Practice: If there are to be meeting notes, the facilitator is not the notetaker
  - Practice: If there are next steps or to-do’s with deadlines at the end of a meeting, they should be reiterated at the end of the meeting
- **Goal: Cultivate creativity/flexibility within sprint teams**
  - Practice: Sprint teams are empowered to institute team meetings, as long as they are not at the expense of team wide meetings.

### Engineering
- **Goal: Have an effective Standup**
  - Practice: https://github.com/department-of-veterans-affairs/caseflow/issues/1703#issuecomment-297436941 
- **Goal: Effective engineering collaboration and code review**
  - Practice: Read through these miscellaneous engineering norms -
 https://github.com/department-of-veterans-affairs/caseflow/blob/master/docs/misc_eng_norms.md
  - Practice: Waffle column process - https://github.com/department-of-veterans-affairs/caseflow/blob/master/docs/process.md

### Productivity
- **Goal: Allow for periodic uninterrupted work time / Support project speed**
  - Practice: Build the habit for few to no meetings on the first Thursday of the sprint.
  - Practice: Team members can work from wherever they are most productive on the first Thursday of the sprint.
 
### General communication
- **Goal: Cultivate a culture of open communication**
  - Practice: Over-communication is welcome!
  - Practice: If you have side conversations, post results on Slack or github for team transparency.
- **Goal: Help teammates grow professionally** 
  - Practice: Sprint team leads will give engineers feedback regularly and vice versa.
  - Practice: VA Eng Lead has monthly 1:1s with each engineer.
 
### Work/Life Balance
- **Goal: Protect work/life balance when contacting others outside business hours**
  - Practice: Configure slack with "do not disturb" for non-work hours.
  - Practice: Individuals may ping any person at any time on slack, and the slack "do not disturb" setting will appropriately prevent notifications outside of working hours. If helpful, recipient can use the context menu (right-click on desktop, press and hold on mobile) “Remind me about this message…” option so that it doesn’t get lost.
  - Practice: Responses to emails and slack notifications are not expected outside of working hours.  For true emergency situations, call someone's phone, which can be found in their slack profile.
- **Goal: Allow teammates to enjoy vacation how they like when they are on vacation**
  - Practice: When you are going on vacation, establish a person for teammates to go to in your stead.
   - Practice: Make every effort not to contact teammates when they are on vacation.

**Comment by NickHeiner** [comment]
LGTM. Everything here matches what we already do, or what we've said we'd like to do.

**Comment by mdbenjam** [comment]
I agree that this looks good. I like the meeting stuff. Especially

> Each teammate has the right to ask why there needs to be a meeting for a topic. That teammate should propose an alternative.

**Comment by aroltsch** [comment]
I think it looks great! Thank you for putting it all together!

I can see you opened this issue under the Caseflow project. Is it a desired place for it?

**Comment by NickHeiner** [comment]
Yes, I think that's the desired place. It can go in a `.md` file in the `docs` directory.

**Comment by mmlumba** [comment]
Everything on this document is very helpful! This also seems like a good resource for onboarding new team members. I would also like to add one other thing regarding standup: 

> Post updates in the #appeals channel on Slack if you can't make team standup

I know we do that already, but it is a good thing to add should someone new come onboard and have no idea what to do when they miss standup.

**Comment by laurjpeterson** [comment]
Discussion will occur on Monday, 6/19

**Comment by joofsh** [comment]
> Goal: Make meetings productive

+1 all these points! I think this is an important positive direction for the team 


> Practice: If there are next steps or to-do’s with deadlines at the end of a meeting, they should be reiterated at the end of the meeting

I would maybe add that all to-dos or actionable items should be assigned to someone to take ownership of. 

Thanks @laurjpeterson for putting this together!
