### ISSUE TITLE
Add Veteran information validations

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2252]
When establishing a claim, we pull the veteran's information from BGS. Sometimes, we know the establish claim request will fail because the veteran's information is not valid. Add validations to the veteran object to determine if the veteran is "valid" for establishing claims.

Known ways a Veteran object would be invalid for establishing a claim:
- The veteran does not have a SSN
- The veteran has postal code, if their address is USA/Canada

## AC
- Veteran record is considered invalid if one of the above criteria exists
- establish claim request returns a 422 to the browser if the veteran record is invalid, and does *not* make the request to VBMS
- Verify that the following error message is displayed when the claim cannot be processed in Caseflow due to the reason above:
> **This claim cannot be processed in Caseflow**

> The veteran's profile in the corporate database is missing information required by Caseflow.
Select Cancel at the bottom of the page to release this claim and proceed to process it outside of Caseflow.

## Mock
<img width="569" alt="screen shot 2017-06-29 at 5 26 54 pm" src="https://user-images.githubusercontent.com/4975959/27711255-97e4bc36-5cf0-11e7-83ef-856247ef1b09.png">

**Comment by kierachell** [comment]
Is this kind of a duplicae of #2246?

**Comment by joofsh** [comment]
This is a subset of #2246. We'll treat that as an epic and split it off into smaller tickets

**Comment by sharonwarner** [comment]
Assigning @lakohl to determine the correct error message to display.

**Comment by lakohl** [comment]
Update error message to read:

> **This claim cannot be processed in Caseflow**

> The veteran's profile in the corporate database is missing information required by Caseflow.
Select Cancel at the bottom of the page to release this claim and proceed to process it outside of Caseflow.

@abbyraskin if you have a sec could you take a look at this copy ^

**Comment by lakohl** [comment]
@sharonwarner at what point is Dispatch aware that the claim cannot be processed in Caseflow? Once the user hits 'Route Claim' on the Decision page? or before that?

**Comment by sharonwarner** [comment]
@lakohl It's on the very last page. Right after they click 'Create End Product'.

**Comment by lakohl** [comment]
Ok. So in the event that we are not creating an EP, but are updating VACOLS loc + adding a diary note or sending an email would they see this message when they click 'Finish Routing Claim'? or does that not generate an error?

**Comment by lakohl** [comment]
@sharonwarner I updated the AC above

**Comment by kierachell** [comment]
## What about `city` and `state`?:
```
:address_line1=>nil, 
:address_line2=>nil, 
:address_line3=>nil, 
:city=>nil, 
:state=>nil, 
:country=>nil, 
:zip_code=>nil,
```

## Here's a sample:
```
fieldName>PersonalInfo Address AddressLine1</fieldName>
<errorType>MINIMUM_LENGTH_NOT_SATISFIED</errorType><message>The minimum data length for the PersonalInfo Address AddressLine1 within the veteran was not satisfied: The PersonalInfo Address AddressLine1 must not be empty.</message></formFieldErrors>
<formFieldErrors><fieldName>PersonalInfo Address City</fieldName>
<errorType>MINIMUM_LENGTH_NOT_SATISFIED</errorType><message>The minimum data length for the PersonalInfo Address City within the veteran was not satisfied: The PersonalInfo Address City must not be empty.</message></formFieldErrors>
<formFieldErrors><fieldName>PersonalInfo Address ForeignMailCode (PostalCode)</fieldName>
<errorType>MINIMUM_LENGTH_NOT_SATISFIED</errorType><message>The minimum data length for the PersonalInfo Address ForeignMailCode (PostalCode) within the veteran was not satisfied: The PersonalInfo Address ForeignMailCode (PostalCode) must not be empty.</message></formFieldErrors>
<formFieldErrors><fieldName>PersonalInfo Address CountryCode</fieldName>
<errorType>MINIMUM_LENGTH_NOT_SATISFIED</errorType><message>The minimum data length for the PersonalInfo Address CountryCode within the veteran was not satisfied: The PersonalInfo Address CountryCode must not be empty.</message></formFieldErrors>
```

**Comment by sharonwarner** [comment]
@kierachell We have another card for the rest of the validations.

**Comment by kierachell** [comment]
**PASSED**
<img width="1117" alt="screen shot 2017-07-10 at 1 25 11 pm" src="https://user-images.githubusercontent.com/18075411/28030834-5f6ec2b2-6573-11e7-973f-b6f13de2a50c.png">
