### ISSUE TITLE
Success Page | Message defaults to "updated VACOLS fields" even when they weren't

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2253]
# Description
When Certifying an Appeal,
If I verify that VACOLS POA info is correct,
Upon finishing certification I am still told that VACOLS POA was updated

@shellicious will provide proper wording for scenarios:
- When VACOLS POA was not updated
- Is there ever a case when hearing preference is not updated?

## Acceptance Criteria
- The Success Page shows the new hearings copy "Hearing fields updated in VACOLS" for all certified appeals. Hearing prefs are always updated.
- The Success Page shows the new POA copy "Representative fields updated in VACOLS" when VACOLS POA fields are updated. This is in the event that VBMS POA info is correct, and the user tells Caseflow that, the VACOLS fields will be updated with the VBMS info.
- The Success Page does not show any POA copy when VACOLS fields are not updated. The hearings copy still displays.

## Reproduction Steps

**Scenario 1 -**

1. Go to Certification
1. Select that VACOLS POA info is correct
1. Finish certifying
1. See that VACOLS POA info was "updated"
1. Question life

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots

Bullet points in the following screenshot should be updated as follows:

- [ ] Remove last bullet point
- [ ] Add bullet point stating, "Hearing fields updated in VACOLS."
- [ ] Only for appeals with POA updated in VACOLS, show: "Representative fields updated in VACOLS."

**_Scenario 1 - [Success Current View]_**
<img width="1043" alt="screen shot 2017-06-06 at 2 07 23 pm" src="https://user-images.githubusercontent.com/18075411/26844777-8ae4f25c-4ac2-11e7-89ac-177e93220b93.png">

**Comment by nemodjuric** [comment]
@shellicious @amprokop Can we get wording for these?

**Comment by shellicious** [comment]
@nemodjuric @amprokop 

Thanks for bringing this up. Here's copy for 2 bullet points.

This one will show up for all certified appeals, since hearing prefs are always updated.
- Hearing fields updated in VACOLS

This one will appear if the POA has been updated in VACOLS -- is the tech lift to determine this relatively low?
- Representative fields updated in VACOLS

**Comment by kierachell** [comment]
## VACOLS only hearing changed
![screenshot_2017-07-24_13-53-49](https://user-images.githubusercontent.com/18075411/28537136-e33c0320-7077-11e7-8863-4cb72b6cc604.png)

## POA updated
![screenshot_2017-07-24_13-55-24](https://user-images.githubusercontent.com/18075411/28537146-e9a9fb04-7077-11e7-8670-55571a98d253.png)
