### ISSUE TITLE
Form 9 | Loader color doesn't match Certification

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2254]
# Description
The color for Form 9 PDF loader does not match Certification's color!

The color for the loader should be #459fd7, Certification's logo color.

## Reproduction Steps

**Scenario 1 -**

1. Go to Certify an Appeal
1. Get to Form 9 to see it
1. Be disappoint with loader color.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Color mismatch]_**
<img width="1073" alt="screen shot 2017-06-06 at 2 18 51 pm" src="https://user-images.githubusercontent.com/18075411/26845057-5ef79252-4ac3-11e7-81c1-17a5eb263b74.png">
**_Scenario 1 - [Header Color]_**
<img width="77" alt="screen shot 2017-06-06 at 2 21 10 pm" src="https://user-images.githubusercontent.com/18075411/26845067-6899d810-4ac3-11e7-949b-5f34b2712fa3.png">

**Comment by shellicious** [comment]
Added certification color to the Description @kierachell

**Comment by kierachell** [comment]
**PASSED**
![laodeooda](https://user-images.githubusercontent.com/18075411/27980778-55771acc-6350-11e7-8ff5-529ffe65025d.gif)

**Comment by kierachell** [comment]
However, Dispatch was recolored as well :(
![nooo](https://user-images.githubusercontent.com/18075411/28025625-e9bc84ca-6561-11e7-836f-ef65532c3205.gif)

**Comment by kierachell** [comment]
**PASSED**
![peek 2017-07-12 20-03](https://user-images.githubusercontent.com/18075411/28145045-40917d3c-673d-11e7-997e-c841aae40d19.gif)

![peek 2017-07-12 20-00](https://user-images.githubusercontent.com/18075411/28145041-3c4ca8b4-673d-11e7-8df7-a9daa7956b5f.gif)
