### ISSUE TITLE
Document Viewer | Bottom toolbar spacing

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2258]
**Description**
Padding in both left and right of previous and next button links are inconsistent

## AC
- [ ] Verify that the padding left of previous button link is the same as right of next button link. Both should total to 40px. 

## Mock up

![image](https://user-images.githubusercontent.com/13420618/26847697-fcc3f6a8-4acb-11e7-8bdd-f7342e26923f.png)

Current situation
![image](https://user-images.githubusercontent.com/13420618/26847673-ebd8d980-4acb-11e7-8de3-a04f3f5ad212.png)

## Related
#2076

**Comment by kierachell** [comment]
It also moves when there is no left or right arrow:
![movingtoolbar](https://user-images.githubusercontent.com/18075411/26958718-28357fd0-4c9a-11e7-8037-ce320df86fd2.gif)

**Comment by mmlumba** [comment]
@kierachell https://github.com/department-of-veterans-affairs/caseflow/issues/2230 handles the shift when there's no left/right arrow

**Comment by astewarttistatech** [comment]
Is there any way to validate the space between the arrows and the edge of the page? @mmlumba 

Please view the video of validation below
![footerspacing](https://user-images.githubusercontent.com/23038505/27196788-dd90371e-51d9-11e7-8e5a-0f0c39a7019a.gif)

**Comment by mmlumba** [comment]
@astewarttistatech you could download the chrome extension Page Ruler and measure the space between the end of the arrow on "Next" and the end of the toolbar

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome

Steps to Validate:
1. Access Reader
2. Open a document and navigate to the bottom toolbar
3. While using various browser extensions, verify the elements in the bottom toolbar against mocks and AC

Screenshot:
see above
