### ISSUE TITLE
[v2] ConfirmCaseDetails dropdown should have different default value 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#2259]
On ConfirmCaseDetails page, the dropdown for 'Service organization name' should have "Select an organization" as the default selection.

**Comment by kierachell** [comment]
**PASSED**
![list](https://user-images.githubusercontent.com/18075411/26983219-0afc475e-4d09-11e7-947f-f62243a23e4c.gif)
