### ISSUE TITLE
App Canvas | Enable a "per application" out of service mode

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2265]
Sometimes only one part of *Caseflow* will have an issue. But others are just fine, so we need a way to disable one applications, while others function:

1. Break Dispatch
1. Certification is fine
1. Get scared because we need to take Dispatch out of service
1. Not want to stop Certifications from happening
1. Get sad.

- Tagged all the tech leads for visibility.
Discuss:

## Related Issue

https://github.com/department-of-veterans-affairs/caseflow/issues/248
https://github.com/department-of-veterans-affairs/caseflow/issues/2211

**Comment by amprokop** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/2702 will supersede this, closing. Add any thoughts about this there please.
