### ISSUE TITLE
Documents list | Clearing the filters navigates a user to the top of the page

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2270]
When a user clears any selected filter(s), either from the filter checkbox menu or the "click here to see all documents" link, they are navigated to the top of the document list.

**Comment by abbyraskin** [comment]
Do you remember why this was important? Will close this ticket and add to #2496 if we think it's necessary.

**Comment by abbyraskinUSDS** [comment]
Closing - won't fix this
