### ISSUE TITLE
[v2] ConfirmCaseDetails dropdown should be sorted in alphabetical order

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#2274]
On ConfirmCaseDetails page, the dropdown for 'Service organization name' should have its list in alphabetical order.

**Comment by kierachell** [comment]
**PASSED**
![list](https://user-images.githubusercontent.com/18075411/26983197-f5eb7e34-4d08-11e7-85f0-293625d04166.gif)
