### ISSUE TITLE
Reader tests failing: no session error for Selenium WebDriver

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#2275]
```
Selenium::WebDriver::Error::NoSuchDriverError:
            no such session
              (Driver info: chromedriver=2.22,platform=Linux 4.4.0-51-generic x86_64)
```

<img width="961" alt="screen shot 2017-06-07 at 2 05 07 pm" src="https://user-images.githubusercontent.com/1976755/26895645-2e602bc2-4b90-11e7-8949-e308dd86ab51.png">

**Comment by mdbenjam** [comment]
Seems like this has been resolved. I believe we were causing selenium to crash, but that has been fixed.
