### ISSUE TITLE
Styleguide | Nav menu scrolling is dependent on the main window scrolling

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2285]
# Description
When scrolling about in our GLORIOUS STYLEGUIDE OF DESTINY,
I am unable to scroll down the left side Nav Menu without scrolling down the main page

## Reproduction Steps

**Scenario 1 -**

1. Go to styleguide
1. See menu on the left side
1. Have an urgent desire to see what's down the menu
1. Start scrolling
1. Keep scrolling and see that the main window is scrolling, not the menu
1. Be weirded out.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Top]_**

![screenshot_2017-06-08_13-31-37](https://user-images.githubusercontent.com/18075411/26942124-e8d39110-4c4e-11e7-8a4b-3bdebc16e341.png)
**_Scenario 1 - [Post-scroll]_**
![screenshot_2017-06-08_13-31-59](https://user-images.githubusercontent.com/18075411/26942123-e8c96c3a-4c4e-11e7-9275-574b03e31bd6.png)

**Comment by astewarttistatech** [comment]
@mmlumba I don't know if when you are done scrolling in the nav bar if it should start scrolling the main page based on the AC of this ticket. 

**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate:
1. Navigate to styleguide
2. Scroll the main page and verify that the navbar doesn't scroll 

Screenshots: 

![scrolling](https://user-images.githubusercontent.com/23038505/31680319-f5c8eb72-b341-11e7-96b8-2715820a2625.gif)
