### ISSUE TITLE
Site degradation banner

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2294]
**Story**
As a user, I would like to be informed that Caseflow's dependencies may be experiencing an outage so I can decide whether to continue using Caseflow or come back later.

**Technical Details**

At first, we'll display the banner across all Caseflow apps if any of our dependencies (BGS, VACOLS, VBMS) shows evidence of being down. We can narrow this down in a future story if we think it's too broad.

This can be implemented as a React component for easy reuse across all of our applications.  We don't have to integrate it into Redux for now — it can manage its own state, since it's totally independent of application state. 

The component can poll a backend endpoint which hits Monitor at e.g. http://monitor.cf.uat.ds.va.gov/sample every 30 seconds and caches the result in Redis.

See https://github.com/department-of-veterans-affairs/caseflow-monitor/blob/master/app/views/monitor/index.html.erb for the code that the Monitor frontend uses to poll its backend. We should display the warning every time `up_rate_5` is less than 50%.

Sample response from `/sample`:
```
{
  "BGS": {
    "name": "BGS",
    "env": "beplinktest",
    "time": "2017-06-19T12:38:26.962-04:00",
    "latency": 0.97422855699551,
    "service": "Person",
    "api": "findPersonByFileNumber",
    "pass": true,
    "count": 7851,
    "up_rate_5": 100,
    "failed_rate_5": 9.8813129168249e-324,
    "latency10": 0.96277803080879,
    "latency60": 1.0175328978877
  },
  "VACOLS": {
    "name": "VACOLS",
    "env": "vacols.dev.vaco.va.gov",
    "time": "2017-06-19T12:38:19.753-04:00",
    "latency": 0.127516647015,
    "service": "VACOLS",
    "api": "VACOLS.BRIEFF",
    "pass": true,
    "count": 8063,
    "up_rate_5": 100,
    "failed_rate_5": 0,
    "latency10": 0.11212189598819,
    "latency60": 0.11250783646536
  },
  "VBMS": {
    "name": "VBMS",
    "env": "uat",
    "time": "2017-06-19T12:38:30.782-04:00",
    "latency": 1.1422687039885,
    "service": "VBMS",
    "api": "ListDocuments",
    "pass": true,
    "count": 7762,
    "up_rate_5": 100,
    "failed_rate_5": 0,
    "latency10": 1.2557626541836,
    "latency60": 1.3034552490905
  },
  "VBMS.FindDocumentSeriesReference": {
    "name": "VBMS.FindDocumentSeriesReference",
    "env": "uat",
    "time": "2017-06-19T12:38:33.926-04:00",
    "latency": 1.9285253830021,
    "service": "VBMS",
    "api": "FindDocumentSeriesReference",
    "pass": true,
    "count": 7512,
    "up_rate_5": 100,
    "failed_rate_5": 6.9255900327801e-100,
    "latency10": 2.182340673625,
    "latency60": 2.3166166827361
  }
}
```

## AC
- [ ] The custom banner comes up whenever dependent systems( BGS, VACOLS, VBMS) report an "up_rate_5" of less than 50% in Monitor.
- [ ] If Caseflow Monitor returns an error or is itself down, the custom banner does not display
- [ ] Requests to Caseflow Monitor are cached in Redis (i.e. each user does not result in more requests being made to Caseflow Monitor)
- [ ] The banner color is `$color-gold-lightest`[See color in Style Guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#colors)
- [ ] The banner has wrench icon and copy written below

## Mockup
Overview
![image](https://user-images.githubusercontent.com/13420618/26952167-3e01c706-4c72-11e7-8133-98913acece60.png)

_Note: Mock above is missing cf-nav bottom border._

Close up
![image](https://user-images.githubusercontent.com/13420618/26952925-92073d92-4c75-11e7-94ed-54b750b97b2f.png)

## SVG
[Wrench svg file](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/wrench.svg)

## Content
_Note: the copy below is more accurate than mock_  

We've detected technical issues in our system. You can continue working, though some users may experience delays.

## Related
Ses #2211 for past discussion

**Comment by abbyraskin** [comment]
Possible copy/preposition edit from convo (also added "technical" here as a suggestion but i do not have strong feelings about this, does it fit?)

We've detected technical issues in our system. You can continue working, though some users may experience errors or delays.

**Comment by gnakm** [comment]
@abbyraskin Lara and I went back and forth about adding the work technical in there as well. I'm pretty split half and half... maybe 51/49 on adding back technical because just issues might sound like it is something else. 

How about:
>We've detected technical issues in our system. You can continue working, though some users may experience delays.

![image](https://user-images.githubusercontent.com/13420618/26994369-64018b8a-4d35-11e7-8a2e-06d14432cc17.png)

I took out errors.

**Comment by kierachell** [comment]
See https://github.com/department-of-veterans-affairs/appeals-qa/issues/33 for maps of how systems are connected.

**Comment by nemodjuric** [comment]
@gnakm @abbyraskin Would you please update issue description to what is supposed to look like if necessary? (Not sure if we decided to go with word 'technical' or not)

**Comment by abbyraskin** [comment]
@nemodjuric i updated the content section -- it should read "We've detected technical issues in our system. You can continue working, though some users may experience delays."

**Comment by nemodjuric** [comment]
After talking to @gnakm, the mock is missing bottom border from cf-nav.

**Comment by nemodjuric** [comment]
@gnakm @abbyraskin Do you expect to see the banner on login and help page too, or only when a user is authenticated?

**Comment by gnakm** [comment]
@nemodjuric I think it makes sense to only show when user is logged in.

**Comment by kierachell** [comment]
### This isn't exactly "help page" but it does not require login to be shown. This is the basic `/` route.

- Also consider the `/whats-new` route. (you can even just check with `rake routes` for other possible pages)
![screenshot_2017-07-14_17-41-02](https://user-images.githubusercontent.com/18075411/28241387-860f7118-6961-11e7-8f52-24d5bef2a6ca.png)

**Comment by kierachell** [comment]
### You set the wrong monitor url - add `/sample`
```
http = HTTPI.get(request, :httpclient)
D, [2017-07-17T13:09:37.467507 #3777] DEBUG -- : HTTPI GET request to internal-dsva-appeals-monitor-uat-681055294.us-gov-west-1.elb.amazonaws.com (httpclient)
=> #<HTTPI::Response:0x00557b14df5b58 @code=200, @headers={"Cache-Control"=>"max-age=0, private, must-revalidate", "Content-Type"=>"text/html; charset=utf-8", "Date"=>"Mon, 17 Jul 2017 17:09:37 GMT", "ETag"=>"W/\"1fcc23efa8650836db050ce5abab785d\"", "Server"=>"nginx/1.10.3", "X-Content-Type-Options"=>"nosniff", "X-Frame-Options"=>"SAMEORIGIN", "X-Request-Id"=>"dcc3b423-07b5-43f4-9330-bc4f8f9e2095", "X-Runtime"=>"0.002904", "X-XSS-Protection"=>"1; mode=block", "Content-Length"=>"5866", "Connection"=>"keep-alive"}, @raw_body="<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>Caseflow Monitor</title>\n  <link rel=\"stylesheet\" media=\"all\" href=\"/assets/application-dc7bac88536c229b44ef78a570a247ab5891d946e5fc6e5231e578421c211113.css\" />\n  <script src=\"/assets/application-a755fbbf39954c977379d6f53c491d791e2556c2da22ca4118e15c92608dfd1f.js\"></script>\n\n  \n</head>\n\n<script>\n  $(document).ready(function() {\n    $(\"time.timeago\").timeago();\n  });\n</script>\n\n<body>\n  <header>\n
```

### Banner does show up for a not-logged in user

![screenshot_2017-07-17_13-13-27](https://user-images.githubusercontent.com/18075411/28280458-d0a04b9e-6af1-11e7-8783-5fa6c22327a2.png)

Otherwise it looks pretty good

**Comment by nemodjuric** [comment]
@kierachell Thanks for catching that, that should be fixed as part of appeals-deployment issue
When it comes to not-logged in user issue - our application controller checks for authentication. If the user is authenticated, then it will show the banner, if it's not then it will redirect to login page. Does it show when there is no user login?

**Comment by kierachell** [comment]
### There seems to be some kind application view error; this comes up on pages where I don't expect to see the banner but it is shown:
```
ActionView::MissingTemplate (Missing template sessions/new, application/new with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder]}. Searched in:
rails_1  | 22:40:01 rails.1  |   * "/caseflow/app/views"
rails_1  | 22:40:01 rails.1  |   * "/root/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/konacha-4.0.0/app/views"
rails_1  | 22:40:01 rails.1  |   * "/root/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/pdfjs_viewer-rails-a4249eacbf70/app/views"
rails_1  | 22:40:01 rails.1  | ):
rails_1  | 22:40:01 rails.1  |   app/middleware/metrics_collector.rb:14:in `call'
rails_1  | 22:40:01 rails.1  |   app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by kierachell** [comment]
**PASSED**

![vvadown](https://user-images.githubusercontent.com/18075411/28337910-184b9596-6bd5-11e7-8d90-5ccde4767a62.gif)


<img width="2" alt="screen shot 2017-07-18 at 3 51 30 pm" src="https://user-images.githubusercontent.com/18075411/28337251-0b255ec6-6bd3-11e7-8e00-152571a3fbed.png">
<img width="1090" alt="screen shot 2017-07-18 at 3 52 18 pm" src="https://user-images.githubusercontent.com/18075411/28337253-0b30f646-6bd3-11e7-82e2-ebdc8205ad4d.png">
<img width="1071" alt="screen shot 2017-07-18 at 3 56 42 pm" src="https://user-images.githubusercontent.com/18075411/28337252-0b294a68-6bd3-11e7-991e-d38e6adffd61.png">

Looking spiffy!
![comingback](https://user-images.githubusercontent.com/18075411/28337245-0191d8d0-6bd3-11e7-8e26-a9341390d79a.gif)
![vbmslslsosos](https://user-images.githubusercontent.com/18075411/28337244-018a6898-6bd3-11e7-81a4-1863315323b7.gif)
