### ISSUE TITLE
Update Routing Information for Philadelphia PMC

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#2300]
Got an email from Matthew Wright that they are closing the older Philadelphia PMC General Inbox:  PMCAPPEALS.VBAPHI@va.gov 

For appeals routed to PMC Philadelphia we should now be sending it to Matthew, Andrea, and the new inbox. Please see below.  

Matthew Wright: matthew.wright1@va.gov
Andrea Gaetano: andrea.gaetano@va.gov
New General Inbox: PensionCenter.vbaphi@va.gov

**Comment by kierachell** [comment]
**PASSED**
saw them emails
