### ISSUE TITLE
Document List | Loader stuck when there are no documents in VBMS

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow#2301]
# Description
When there are 0 documents in VBMS,
the initial loader for Document List gets stuck...

## Reproduction Steps

**Scenario 1 -**

1. Go to reader for an appeal that has no VBMS documents
1. Watch loader forever

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [VBMS]_**

<img width="972" alt="screen shot 2017-06-09 at 12 07 01 pm" src="https://user-images.githubusercontent.com/18075411/26984532-b3631ffe-4d0d-11e7-9bbf-515b47a5f53f.png">

**_Scenario 1 - [Reader]_**
<img width="883" alt="screen shot 2017-06-09 at 12 07 14 pm" src="https://user-images.githubusercontent.com/18075411/26984535-b87219dc-4d0d-11e7-82a9-af4a6ff0a610.png">

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
