### ISSUE TITLE
Help | Login system updated documentation

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2310]
# Description
When I go to the new Login page, I get confused,
so I go to Help page to figure out what I am supposed to do,
and I find that **Help** is not.. helpful

## Reproduction Steps

**Scenario 1 -**

1. Go to Help page section 4
1. Be even more confused

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Section 4]_**
<img width="898" alt="screen shot 2017-06-11 at 11 31 45 am" src="https://user-images.githubusercontent.com/18075411/27012215-c40a3f6c-4e99-11e7-8638-e1d8faea2a5c.png">

# Related Issues
**_Engineering_**
#2272

**Comment by gnakm** [comment]
@kierachell I kind of lost the context for this one. Could you explain more? If it is no longer relevant, close please.

**Comment by kierachell** [comment]
We have a `/login` page that @NickHeiner made for people logging in from Stations that map to multiple regional offices

The help page for Certification (the most relevant app for this use case) does not cover the new login page. (as shown in the screenshot above).

We need to update the relevant Help pages with description/explanation of what the Login page does and why.
