### ISSUE TITLE
How should we get POA addresses?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2311]
The POA address being not present or out of date in VACOLS is a persistent pain point. We wanted to address this with Certification v2— we were advised that BGS contained more up to date POA information. However, we recently determined that BGS production does not contain the addresses we expected it to. [See this issue in ruby-bgs](https://github.com/department-of-veterans-affairs/ruby-bgs/issues/32) for context on the failure of our previous efforts. 

Here are a few non-vetted ideas for how we could proceed.

- Follow up with the BGS team— they told us that these addresses should be there. 

- [This VA link](https://www.va.gov/ogc/apps/accreditation/index.asp) allows you to download markup files containing big buckets of POA information. We could write scripts to parse them into JSON and check them into the Caseflow repo as a short term solution.

- [The same link](https://www.va.gov/ogc/apps/accreditation/index.asp) has a form where you can submit a search. We could reverse engineer that request and parse the results ourselves.

- We could get access to the actual OGC database that contains this information. As far as I've heard, there is no API, but potentially we could read from the DB. According to @nicholasholtz this may be possible.

We should also consider a potential long-term POA solution. Do we want to be the system of record for any of this?

**Comment by amprokop** [comment]
I just did a run-through of the BGS API documents and I don't see any other service that looks like it would be a likely candidate for serving up POA addresses. @aroltsch, can you take a pass at the BGS documents and double-check?

**Comment by aroltsch** [comment]
I'll take a look @amprokop.

**Comment by aroltsch** [comment]
```findAllPtcpntAddrsByPtcpntId - finds all the PTCPNT_ADDRS rows that do not have an end_date, for the provided
ptcpnt_id```
I tested production data and there are addresses there.

**Comment by amprokop** [comment]
Well then! Let's try that approach and see if it works!

**Comment by nicholasholtz** [comment]
@amprokop 

>We should also consider a potential long-term POA solution. Do we want to be the system of record for any of this?

We are investigating this with OGC. Had a conversation with the folks who own the accreditation database last week, and have discussed the likelihood of a discovery sprint to investigate. Ultimately, they want/need a new database (plus some additional functionality), and our ultimate options are either to a) use this data now and then be ready to adjust to however they set up the database they build to replace this one, which will always mean balancing BGS records and the accreditation records, or b) figuring out a way to set this up ourselves. 

If it is doable, my strong preference would be to set it up ourselves, as this impacts many (all) of our products.

**Comment by laurjpeterson** [comment]
Closing in favor of more recent discussion about POA addresses - #7673
