### ISSUE TITLE
Jump to section: initially navigates to first page of document 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2316]
## Current State
When a user clicks the "Jump to section" link from the doc list view, the user is initially navigated to the first page of the document. 

## Expected
When a user clicks on the "jump to section" link, we should jump them to (load) the correct page without showing the first page of the document first.

![readerjumptosection](https://user-images.githubusercontent.com/23038505/26935491-19ded338-4c3a-11e7-9ab6-5ee019a508c8.gif)

**Comment by mdbenjam** [comment]
I don't think this happens any more. Moving to in-validation.

**Comment by kierachell** [comment]
**PASSED**

yup, working fine
