### ISSUE TITLE
Hearing Details Form 9 | Prefetch Form 9 cause it takes forever to load

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2318]
# Description
When I am validating hearing details on Form9, it would be nice to not have to wait forever for it to load

## Reproduction Steps

**Scenario 1 -**

1. Go to Cert v2
1. Get to Hearing Details page
1. Wait for form 9 to load
1. Fall asleep

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Screenshots
**_Scenario 1 - [LOAD SO SLOW]_**
![loadme](https://user-images.githubusercontent.com/18075411/27046010-eb9c022c-4f70-11e7-9a7b-659ab3242029.gif)

**Comment by amprokop** [comment]
@mdbenjam @aroltsch — is it possible for us to use the new eFolder Express API for this? We could potentially make a call to the API right when certification is started, thus stashing the Form 9 in S3, then grabbing it from S3 on page 3. Thoughts?
