### ISSUE TITLE
Linked form fields hide on change

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#232]
To duplicate:

1. Click _Located in another VA file_ for question 8B.
2. Enter text in the _8B EXPLANATION_ field.
3. Click somewhere else and be amazed as the  _8B EXPLANATION_ disappears. 

Applies to all linked fields.

**Comment by plusjeff** [comment]
11A and 11B have this problem too. If 11B is selected with No, it disappears.

**Comment by webinista** [comment]
Closing in light of #332
