### ISSUE TITLE
Sentry Error: nil for tasks_completed_count

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2328]
ActionView::Template::Error: undefined method `tasks_completed_count' for nil:NilClass
Culprit
----------------
app/views/establish_claims/complete.html.erb in _app_views_establish_claims_complete_html_erb___4092885392400982242_47271956138760 at line 9

**Comment by kierachell** [comment]
So uh... how does this happen again? What am I to validate?
