### ISSUE TITLE
eFolder Express Integration | Feature Toggle functionality

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2339]
Updating the Appeals model to pull from the eFolder endpoint `/api/v1/files/<vbms_id>` when `config.efolder_enabled` is set to `true` and the application is `Reader`. These will be displayed on the document list for an appeal in Reader. 

Read the full eFolder Express integration tech spec [here](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/prefetching_files_for_reader.md).

# AC
1. Set  the feature toggle for `efolder_docs_api` to `true` for the environment: `FeatureToggle.enable!(:efolder_docs_api)`
    - This integration will only work in the UAT environment since dev, test and demo environments use our Fakes library
1. Set the environment variable `EFOLDER_EXPRESS_URL` to the URL of eFolder
1. Set the environment variable `EFOLDER_API_KEY` to the correct token to use with the eFolder API (testing is using `token`)
1. Load an appeal that has files stored in eFolder
1. Verify that these files match with what's stored in eFolder
1. Verify the implementation of this function doesn't change when the FeatureToggle `efolder_docs_api` is set to false and Caseflow pulls from VBMS

**Comment by kierachell** [comment]
### You might need to set EFOLDER endpoint based on `deploy_env` vs `rails_env`

In UAT right now:
```
export EFOLDER_EXPRESS_URL="https://efolder.cf.ds.va.gov/"
```

**Comment by mogrenAtWork** [comment]
@mdbenjam can you help with this? I don't think I have access to the vault where these variables are stored so I don't know which to use

**Comment by mdbenjam** [comment]
Gah I have the wrong variable setup in the uat vars. Give me ten minutes.

**Comment by mogrenAtWork** [comment]
Blocked by https://github.com/department-of-veterans-affairs/appeals-deployment/issues/732

**Comment by kierachell** [comment]
This technically works and will be revalidated using https://github.com/department-of-veterans-affairs/caseflow/issues/2808

**Comment by kierachell** [comment]
**PASSED**
Will be revalidated using: https://github.com/department-of-veterans-affairs/caseflow/issues/2808
