### ISSUE TITLE
Add a Help page

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#234]
Need copy for page, and the URL. Blocks #236

**Comment by KHarshawat** [comment]
Should pull content from the FAQ and intro email sent to the NYRO. See the content here:

https://github.com/department-of-veterans-affairs/appeals-pm/issues/20

**Comment by webinista** [comment]
Screenshot below. This definitely needs some design work @KHarshawat 

![help-page](https://cloud.githubusercontent.com/assets/354277/11968999/666b4a68-a8e1-11e5-9ce0-61ad86d0a9f6.png)
