### ISSUE TITLE
eFolder Express Integration | Point Reader at `/documents/:document_id`

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2340]
Read the full eFolder Express integration tech spec [here](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/prefetching_files_for_reader.md).

Currently Reader hits the Caseflow backend which triggers file downloads from VBMS. Now we want to hit eFolder Express to stream our files.

# AC
1. Verify that files are retrieved from `/api/v1/documents/:document_id` endpoint from eFolder Express instead of the `document/:id/pdf` endpoint from Caseflow when the feature toggle is enabled `FeatureToggle.enable!(:efolder_docs_api)`

**Comment by kierachell** [comment]
I think you have this configured to point to prod in all envs
```
SocketError: getaddrinfo: No address associated with hostname (efolder.cf.ds.va.gov:443)

Exception(most recent call first)

```

**Comment by mogrenAtWork** [comment]
Relates to the issues in #2339

**Comment by mogrenAtWork** [comment]
This broke because a cert needed to be set in both environments to allow them to send requests/responses over HTTPS. This was completed with https://github.com/department-of-veterans-affairs/appeals-deployment/pull/730

Now I need to add the appropriate SSL settings to the HTTPI request in EfolderService

**Comment by kierachell** [comment]
**PASSED**

Remaining integration issues captured in https://github.com/department-of-veterans-affairs/caseflow/issues/2808
