### ISSUE TITLE
eFolder Express Integration | Modify S3 bucket cleanup policy

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2341]
Read the full eFolder Express integration tech spec [here](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/prefetching_files_for_reader.md).

Since attorneys may work a case over several days. Let's update the S3 bucket policy to keep files around for 2 weeks.

# AC
1. Verify this policy change does not violate our ATO
1. Verify that the S3 bucket is cleaned every two weeks instead of every 3 days.

**Comment by astewarttistatech** [comment]
So far files have stayed around pass 3 days (4) but will wait longer to validate that they stick around for 2 weeks.

**Comment by astewarttistatech** [comment]
**FAILED**

Documents have been cleared and the latest document is from August 9th. 

Sorry @tejans24

**Comment by tejans24** [comment]
Weird, I'll look into this issue.

**Comment by kierachell** [comment]
**PASSED**
it's been done for ages
