### ISSUE TITLE
Welcome Gate | Ability to search for a claims folder

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2342]
## Story
When chatting about a case with another attorney, I want to search for a claims folder not assigned to me, so I can quickly open the case for reference.

### Search
- [x] The [style guide search component](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#search) is currently being added to the style guide. Incase it's not ready on time, here is the [search issue](https://github.com/department-of-veterans-affairs/caseflow/issues/1423) for it. 
- [x] When a user enters the 9 digit Veteran ID, it should go straight to the Veteran's case, Documents List page.
- [x] If the Veteran has multiple appeals, then a modal pops up with choices to select from

### Modal 
- [x] When a Veteran ID number is entered in the search box, a modal should pop out with the claims folder information. [Style guide modal component](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#modals)
  - [x] Title: Select Claims folder
  - [x] [Radio button](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#radios) followed by appeals information
  - [x] Veteran (veteran first and last name), Veteran ID (Veteran ID number), Issues (note: this differs from mock)
  - [x] Above the horizontal line should be text `Not seeing what you expected? Please send us feedback.` Please send us feedback should be a text link to the feedback page. 
  - [x] Bottom right should have `primary` button with word Okay
  - [x] Bottom left should have Cancel button link to cancel out of the modal 
- [x] If there are multiple appeals from the same Veteran, should show multiple radio buttons with options. 

## Mockup
![image](https://user-images.githubusercontent.com/13420618/28894722-b01a28ae-77a3-11e7-981b-b97bd2374f2c.png)

![image](https://user-images.githubusercontent.com/13420618/27796312-9c779b8a-5fd7-11e7-9df8-5d8798ce833c.png)

## Related Story
https://github.com/department-of-veterans-affairs/caseflow/issues/1999
https://github.com/department-of-veterans-affairs/caseflow/issues/2521
Error alert: https://github.com/department-of-veterans-affairs/caseflow/issues/2920

**Comment by abbyraskin** [comment]
Note: add info about selecting VACOLS appeal

**Comment by abbyraskin** [comment]
@mdbenjam can you take a look at this and add any clarifying technical details if needed?

**Comment by mdbenjam** [comment]
The second AC in Search should probably be removed. As for technical details, I'll throw a question back to you. How do we know if we should show a case? Are we showing all cases associated with the veteran ever? If so, program alone is probably not enough to distinguish. If we're only showing cases that

**Comment by gnakm** [comment]
@mdbenjam I think @abbyraskin and I talked about even having a tab at one point that shows current ones vs. old ones but for the scope of this ticket, I think we need to lock down the ability to search for current claims folder. I believe VACOLs shows it that way today (current vs history).

But going back to original concern, are we feeling confident that programs provide enough distinction between appeals?

**Comment by gnakm** [comment]
@mdbenjam also, should 2nd AC in search be removed because it's unnecessary or because the flow is incorrect?

**Comment by mdbenjam** [comment]
The flow is incorrect right? It goes to the modal, not the documents page right?

If we're only saying current cases, then program should be enough to distinguish.

**Comment by gnakm** [comment]
@mdbenjam I just updated the AC -- the modal pops up only when there are more than 1 appeal for the Veteran ID, which in that case user has to choose.

**Comment by abbyraskin** [comment]
Needs updated mock to show issue code

**Comment by abbyraskin** [comment]
@mdbenjam assigning you, as you expressed interest in picking this up, but reassign accordingly as needed :D

**Comment by abbyraskinUSDS** [comment]
note: the "see more" expand shown in mock is out of scope for this ticket - see: https://github.com/department-of-veterans-affairs/caseflow/issues/2597

**Comment by tejans24** [comment]
We might need a few other UI changes to the mocks for the following cases: 
* What if we can't find the veteran with the ID?
* What if the API returns an error while searching for appeals for the veteran?
* Should we restrict the search input to max 9 characters? Does the input need any other validations?

**Comment by cmgiven** [comment]
It should not be restricted to 9 characters. It might contains spaces and/or a trailing 'S'.

**Comment by abbyraskinUSDS** [comment]
@gnakm we also need to capture the scenario where the ID is correct, but the person has no active appeals.

**Comment by kierachell** [comment]
@gnakm lemme know if these should be separate issues...


#### When opening a new document list through the search, the Veteran's name is left over from before for a second
![glitchyname](https://user-images.githubusercontent.com/18075411/29921939-9fbdf640-8e21-11e7-867e-ff02548f4f18.gif)

#### Responsive AF
![whatthehellisthisresponsiveness](https://user-images.githubusercontent.com/18075411/29921997-d6b5d8de-8e21-11e7-90ae-84e922f30a25.gif)

**Comment by gnakm** [comment]
@kierachell Yeah that's not a big deal but I'll make an issue for that and low-pri it. It does look strange. I'm confused by what is happening in the bottom gif.

**Comment by tejans24** [comment]
@gnakm The alert shows the search term  from the input in the search box + the message. @kierachell is searching for super long phrases in which the alert is getting over filled.

We can shorten the message in the alert once it reaches certain length.

**Comment by tejans24** [comment]
@kierachell For the 1st case I can't seem to be able to replicate it locally. Can you list out the steps to replicate?

Thanks

**Comment by gnakm** [comment]
@tejans24 
I made separate issues for the above if you want to add anything
https://github.com/department-of-veterans-affairs/caseflow/issues/3149
https://github.com/department-of-veterans-affairs/caseflow/issues/3148

**Comment by kierachell** [comment]
###  If the Veteran has multiple appeals, then a modal pops up with choices to select from
any appeals? active appeals? assigned appeals? what determines what appeals and what issues will the attorney see?

### Veteran ID in VACOLS can be what's known as `BFCORLID` and/or `SSN`... Can we search by `SSN` or only by `BFCORLID`?
- BFCORLID is stored in the BRIEFF table and can be 9-8 digits long (this is already handled properly)
- SSN is in the CORRES table. Do we care about it? Sometimes it's == to BFCORLID, sometimes not

### Can we search for Appeal ID?

**Comment by abbyraskinUSDS** [comment]
@kierachell: 

> If the Veteran has multiple appeals, then a modal pops up with choices to select from

- I talked to Mark and James about this, and right now it shows any appeals, which is fine, but we need to update the modal to say whether the appeal is active or in history status (cc: @gnakm)

> Veteran ID in VACOLS can be what's known as BFCORLID and/or SSN... Can we search by SSN or only by BFCORLID?
- How do we handle this in other applications, like eFolder Express? Can they search for either BFCORLID or SSN?

> Can we search for Appeal ID (not Veteran ID)?
- No

> Can we search for Docket number?
No

**Comment by cmgiven** [comment]
> How do we handle this in other applications, like eFolder Express? Can they search for either BFCORLID or SSN? We should include any ID that could be listed on the appeal as the vet ID.

eFolder Express just uses the file number (BFCORLID). This is also the only thing that would be listed on the appeal, and is consistent with how VACOLS retrieves cases. I would not suggest looking at the SSN field, as it has known quality issues.

**Comment by kierachell** [comment]
**PASSED**

I was mostly asking questions for the sake of documenting the intended use cases; thanks.
