### ISSUE TITLE
Switching between documents takes you where you last were inside of a doc

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#2343]
**Description:**
Currently, if you are in a multi-page document in Reader, if you switch to the previous document and then back to the original document, instead of taking you to the beginning of that multi-page document, you are back to the last page you were on within the document. 

**Found in:** UAT
**Browsers:** FF and Chrome 

**Steps to Reproduce: **
1. Access Reader for a veteran who has multiple documents and multi-page documents
2. Open a multi-page document and go past the first page
3. Select the previous button 
4. On the new document select the next button
5. Validate that the page that you arrived on is not the beginning of the document, but the last page you left when you originally were in the first document. 

**Expectation:** When navigating through documents, the user should be brought to the first page of the document, every time. 

**Screenshots: **
![readerjumptosection](https://user-images.githubusercontent.com/23038505/26935491-19ded338-4c3a-11e7-9ab6-5ee019a508c8.gif)

**Reported by:** Alexis Stewart

**Comment by abbyraskinUSDS** [comment]
This was fixed.
