### ISSUE TITLE
Make mock of what dropdown should look like, bring in line with web standards

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#235]
Make mock of what [dropdown should look like](https://playbook.cio.gov/designstandards/form-controls/#dropdown) related to web standards:

**Comment by KHarshawat** [comment]
@webinista lower priority but if you want to style the drop down here's a mock. 20px padding all around and b/t items.

![image](https://cloud.githubusercontent.com/assets/6335546/11907933/c440d75a-a58c-11e5-82d8-eaaf43735057.png)
