### ISSUE TITLE
[v2 - For St. Pete] | Sign & Certify and Success pages scroll down on load

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2352]
Potentially, we're scrolling to the first element with focus on page load. It's a little jarring to be scrolled halfway down.

### AC ###
- When loading Sign & Certify and Success pages, we should be at the top of the page

**Comment by kierachell** [comment]
**PASSED**
![success](https://user-images.githubusercontent.com/18075411/27981103-b534b376-6354-11e7-98dc-3772d274c1ef.gif)

**Comment by kierachell** [comment]
**PASSED**
![peek 2017-07-12 20-05](https://user-images.githubusercontent.com/18075411/28145392-f60ee2f6-673f-11e7-887e-3b5c181916e7.gif)
