### ISSUE TITLE
Style guide | Change button description

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2362]
**Description**
As a designer or developer, I want to know how to use the buttons in Caseflow so that they are consistent across all apps. 

## AC
- [ ] Verify that the description for buttons (see copy below) is added to the Buttons section above the UI components
**_Note: Nothing should change in the source code_** 😸 

## Copy
Primary actions are visually prioritized by being solid blue `usa-button` style.

Finally, there are actions that we generally want to discourage but should remain visible to users as an escape hatch. 

These actions can be `button-link` styles or use the `usa-button-secondary` style. For example, the “Cancel” button frequently found at the bottom of Caseflow workflow layouts is usually a button link because it launches a modal. The button to confirm that a user wants to cancel is red and serves as a warning to the user that the action is destructive. These styles should be used sparingly.

The width of the button will vary depending on the length of the content. In the source code, the buttons are set so that there is always 20px padding on the left and right of the text. While it is ideal not to change the default setting, in a case where buttons of various widths are stacked, we highly recommend adjusting the padding of the buttons so that they all match in width. 

## Related 
#1999

**Comment by Sjones352** [comment]
![screen shot 2017-06-28 at 1 40 25 pm](https://user-images.githubusercontent.com/23080951/27651768-6a25a218-5c07-11e7-8f62-8062ec18d67f.png)

**Comment by gnakm** [comment]
lgtm!

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the living style guide
2. Navigate to the buttons section
3. Validate the copy against the AC

Screenshots: 
<img width="1086" alt="screen shot 2017-06-29 at 9 05 20 am" src="https://user-images.githubusercontent.com/23038505/27688980-78167f5c-5caa-11e7-8e6c-37abb2c0c3b7.png">
