### ISSUE TITLE
Reader | Breadcrumb

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2364]
**Description**
As a user, I would like to quickly and easily navigate between different pages on Reader that is consistent to other Caseflow applications. 

## AC
- [ ] Verify that clicking the word "Reader" in Caseflow Reader will bring user to the [welcome gate page](https://github.com/department-of-veterans-affairs/caseflow/issues/1999)
- [ ] Verify that clicking Claims Folder will bring user to the documents list page
- [ ] Verify that clicking Document Viewer will bring user to document viewer page 
- [ ] Everything should be Title Case

## Mockup

![image](https://user-images.githubusercontent.com/13420618/27304825-5307ce18-550d-11e7-969f-bd100e320391.png)

## Dependencies
#2422

**Comment by abbyraskin** [comment]
^^ yes, i like that. claims folder sounds better.

**Comment by mdbenjam** [comment]
@gnakm I really like this! But--it will not be possible until we move rendering the header from Rails to React :/

**Comment by gnakm** [comment]
^^^ @lakohl @joofsh Curious to know how you guys are/were planning to build breadcrumbs for Hearings Prep

**Comment by abbyraskin** [comment]
@gnakm i added #2422 as a dependent story in your AC :-D

**Comment by kierachell** [comment]
**PASSED**
<img width="1039" alt="screen shot 2017-09-28 at 8 03 37 am" src="https://user-images.githubusercontent.com/18075411/30965523-af722c74-a423-11e7-83c7-e91321f0856e.png">

<img width="470" alt="screen shot 2017-09-28 at 8 04 16 am" src="https://user-images.githubusercontent.com/18075411/30965520-af708e8c-a423-11e7-9506-35ce0f5f740a.png">
<img width="560" alt="screen shot 2017-09-28 at 8 04 19 am" src="https://user-images.githubusercontent.com/18075411/30965522-af720762-a423-11e7-91f8-3abc43e42b0e.png">
