### ISSUE TITLE
Switching Between Documents | Footer doesn't load

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2367]
When switching quickly between documents, the footer doesn't load for a very long time, and document stays blank.

# AC
1. Verify the footer never disappears when switching between documents
1. Verify a message `Document Loading...` in italics is displayed where the page indicator will be when the document fully loads.

**Comment by mdbenjam** [comment]
@gnakm Does this look okay: 
![screen shot 2017-06-20 at 5 10 33 pm](https://user-images.githubusercontent.com/3885236/27356150-750ec34e-55db-11e7-8fe5-16c450ef21bb.png)

**Comment by kierachell** [comment]
**PASSED**
Technically passes the AC, but... something is off:
![loadmebabyonemoretime](https://user-images.githubusercontent.com/18075411/27520903-24d99ae6-59e3-11e7-9174-92d6d51b0aca.gif)
