### ISSUE TITLE
ArgumentError: comparison of Date with nil failed

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#2368]
Sentry link: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/252/events/

This error happens when vbms_document doesn't have a received date. 

Acceptance Criteria:
When a VBMS document does not have a received date, we should not match that VBMS document to any Vacols documents.

**Comment by kierachell** [comment]
**PASSED**
Would be fun to find a single document that has no receipt date :D - prod it shall be!
