### ISSUE TITLE
Document Viewer | DAS information in side menu

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2375]
**Story**
As a user, I would like to see VACOLS information at this interface so that I don't have to go back and forth comparing issues and information from another system. 

## AC
- [ ] Verify that the Document Information section has the following information
  - Veteran ID (Claim number)
  - Docket number
  - Type (Type action)

``` 
  TYPES = {
    "1" => "Original",
    "2" => "Supplemental",
    "3" => "Post Remand",
    "4" => "Reconsideration",
    "5" => "Vacate",
    "6" => "De Novo",
    "7" => "Court Remand",
    "8" => "Designation of Record",
    "9" => "Clear and Unmistakable Error"
  ```  

  - If the case is AOD, show the word AOD in `$color-secondary` next to **Type** description.
  - If the case is CAVC, show the word CAVC in `$color-secondary` next to **Type** description.
  - If the case is both AOD or CAVC, show the words AOD, CAVC (note comma in between) in `$color-secondary` next to **Type** description.
     - See [colors for style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#colors) if needed here
  - Regional office number
  - Issues (format: Program, Issues, Levels 1-3) 
- [ ] If there are no issues, A "No issues on appeal" message is shown.

_**Note: Editing Doc type and receipt dates are out of scope for this issue.**_

## Mock up 
![image](https://user-images.githubusercontent.com/13420618/28286704-0a823bd2-6b07-11e7-8b22-8519395ecfde.png)

## Related
#2161 
#1998
https://github.com/department-of-veterans-affairs/caseflow/issues/2593

**Comment by abbyraskin** [comment]
@gnakm I think the CAVC/AOD handling AC and mock is outdated now, to keep it consistent with changes in claims folder details accordion

**Comment by nicholasholtz** [comment]
Looking at mock vs. AC - under type, the mock indicates one option as "Remand". Is this part of the AC? If so, would "Post-Remand" be more appropriate language?

**Comment by abbyraskin** [comment]
@nicholasholtz correct, it's not a perfect real world example - just a mock (we aren't hard coding these, so the "Type" should always reflect the actual options available in VACOLS...will call out these options in AC, sorry for confusion)

**Comment by astewarttistatech** [comment]
**FAILED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Reader
2. In the side menu under Document Information, make sure the variables listed in the AC/Mocks are present. 

Current view: 
![readermenu1](https://user-images.githubusercontent.com/23038505/29173637-ebf31e08-7db1-11e7-962b-4e400d05840c.gif)

**Comment by tejans24** [comment]
* Editing fields is out of scope for this issue. AC should be updated accordingly.
* If there are no issues, A "No issues on appeal" message is shown. This needs to be added to the AC as well.

**Comment by astewarttistatech** [comment]
@tejans24  AC is still not updated.

**Comment by gnakm** [comment]
@astewarttistatech AC updated.

**Comment by kierachell** [comment]
## Not seeing AOD/CAVC show up in the Menu
<img width="412" alt="screen shot 2017-08-11 at 11 11 48 am" src="https://user-images.githubusercontent.com/18075411/29220339-be098608-7e88-11e7-86d4-36d00d09e5b8.png">
<img width="448" alt="screen shot 2017-08-11 at 11 15 15 am" src="https://user-images.githubusercontent.com/18075411/29220338-be08290c-7e88-11e7-97d7-ca1c70939d20.png">
<img width="567" alt="screen shot 2017-08-11 at 11 15 43 am" src="https://user-images.githubusercontent.com/18075411/29220342-be0dea36-7e88-11e7-9cca-cab7dbfe3e9c.png">
<img width="694" alt="screen shot 2017-08-11 at 11 29 23 am" src="https://user-images.githubusercontent.com/18075411/29220341-be0bde30-7e88-11e7-8615-f4fbddf351f0.png">
<img width="418" alt="screen shot 2017-08-11 at 11 31 11 am" src="https://user-images.githubusercontent.com/18075411/29220343-be0e3a2c-7e88-11e7-83e1-4ce2c2b6ef1b.png">
<img width="616" alt="screen shot 2017-08-11 at 11 31 48 am" src="https://user-images.githubusercontent.com/18075411/29220340-be0a3e18-7e88-11e7-8083-d5ae15837a4a.png">

**Comment by tejans24** [comment]
This should be good after https://github.com/department-of-veterans-affairs/caseflow/pull/2979 is merged into master.

**Comment by tejans24** [comment]
#2979 is merged

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Reader with different Remands, Full Grants, and Partial Grants
2. Navigate to the a document in the document list 
3. Verify in the menu that the DAS information is shown
4. Verify that CAVC/AOD's are mentioned in red text. 
5. Verify that the information appears in the summary found on the Document Lists page as well as inside of the document menu. 

Screenshots:
<img width="1397" alt="screen shot 2017-08-14 at 2 17 26 pm" src="https://user-images.githubusercontent.com/23038505/29285178-96d112fc-80fb-11e7-8196-80f7b8ceef83.png">
<img width="1233" alt="screen shot 2017-08-14 at 2 17 47 pm" src="https://user-images.githubusercontent.com/23038505/29285179-96d1d516-80fb-11e7-9b6c-921f955942d7.png">
<img width="1199" alt="screen shot 2017-08-14 at 2 19 57 pm" src="https://user-images.githubusercontent.com/23038505/29285218-c0f0d70c-80fb-11e7-8ca6-1d2a4f038c43.png">
<img width="1406" alt="screen shot 2017-08-14 at 2 20 09 pm" src="https://user-images.githubusercontent.com/23038505/29285217-c0ef8f1e-80fb-11e7-95bc-c0e0610d1d75.png">
