### ISSUE TITLE
Prioritize PA SI Correctly

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2376]
From @lakohl : I just chatted with Abby and it seems they will be rare, but on claims that have tier 2 or 3 special issues those special issues should take precedence. e.g. They should be routed to the tier 2/3 RO or Specialty Center rather than the ROJ

## AC:
- Go to Dispatch
- Start establishing next claim with Private Attorney preselected
- Choose a level 2 and/or 3 Special Isssue
- Make sure that Private Attorney routing behavior is overridden by the newly select Special Issue routing.

**Comment by astewarttistatech** [comment]
Currently blocked, due to VBMS error
![claimrouting](https://user-images.githubusercontent.com/23038505/27395851-36500e70-567f-11e7-8271-2fa41c943d45.gif)

**Comment by kierachell** [comment]
Still blocked:
```
<exception>An error occurred while establishing the claim: Unable to establish claim:  - The Tuxedo service is down</exception><message>Claim not established. System error with BGS.
</message>
</serviceException></detail>
</env:Fault></env:Body></env:Envelope>
```

**Comment by kierachell** [comment]
![pacase](https://user-images.githubusercontent.com/18075411/28026279-904d4756-6563-11e7-82ae-485fb9f12498.gif)
<img width="829" alt="screen shot 2017-07-10 at 11 32 34 am" src="https://user-images.githubusercontent.com/18075411/28026290-958dbc82-6563-11e7-961e-0df279d4597e.png">
<img width="705" alt="screen shot 2017-07-10 at 11 32 42 am" src="https://user-images.githubusercontent.com/18075411/28026291-958e369e-6563-11e7-9604-9f778b190399.png">
