### ISSUE TITLE
Investigate speeding up PDF page rendering when zooming out

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2380]
Investigate speeding up PDF page rendering when the user is zooming out of the canvas.

We may be able to use CSS transforms to scale the rendered images down quickly, without having to re-render them each zoom.

**Comment by abbyraskin** [comment]
Hold until Mark's mega-refactor is complete :-D

**Comment by mogrenAtWork** [comment]
Blocked by #2459

**Comment by abbyraskinUSDS** [comment]
Hold off until after the refactor to see if things have slowed down, then we'll reassess.

**Comment by mdbenjam** [comment]
I don't think we need to do this any more. Closing.
