### ISSUE TITLE
Document Viewer | Back button copy edit

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2381]
**Description**
We are now calling the documents list page the claims folder page, so we need to change that name everywhere. 

## AC
- [ ] Verify that the copy for the "Back to Documents" button link is now "Back to claims folder"

## Mock ups
![image](https://user-images.githubusercontent.com/13420618/27304947-cdd44f72-550d-11e7-995e-a718d2400e4d.png)

**Comment by mogrenAtWork** [comment]
Highlighting the link when using keyboard navigation to be addressed with #1851

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Reader
2. Open a document from the Document List view
3. Verify that the "Back to Documents" button has changed to "Back to Claims folder"

Screenshots: 
<img width="1076" alt="screen shot 2017-06-29 at 8 57 58 am" src="https://user-images.githubusercontent.com/23038505/27688783-dcebc744-5ca9-11e7-82de-4d28e6ac1c67.png">
