### ISSUE TITLE
Organize directory structure for external dependencies in Caseflow

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#2383]
I would like to propose the following directory structure:
1. Remove `app/repositories` directory as it is unclear what it means. 
2. Place external APIs under the following directories: `app/services/vacols/*`, `app/services/bgs/*`, `app/services/vbms/*`. We have an issue to re-factor `appeal_repository.rb` to separate Vacols and VBMS code. 
3. Place report code under `app/services/reports/*` directory
4. Leave local services in `app/services/*` directory

Please leave comments with your suggestions.

**Comment by mdbenjam** [comment]
I don't have strong feelings about this. But I think this approach makes sense.

**Comment by joofsh** [comment]
The goal with `app/repositories` was to be the location for all our external dependency code. I agree though that it's very similar to the `services` directory, and am totally fine nesting them back in there. 

LGTM 👍

**Comment by amprokop** [comment]
do we need the extra directories for `bgs` and vbms`? those files really aren't that big, as most of the logic lives in the gems

**Comment by amprokop** [comment]
also, what's report code?

**Comment by aroltsch** [comment]
There are a few files having `report` in their name in app/services. Ok, good point on `bgs` and `vbms`. Should we nest `bgs` and `vbms` under `app/services/external_api`? And we can place vacols repositories under `app/services/vacols`? 
@amprokop @joofsh @mdbenjam

**Comment by amprokop** [comment]
Sure, that sounds good.
