### ISSUE TITLE
Pdf.jsx | Refactor and add unit tests

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2385]
Pdf.jsx is getting super long. We've push a tremendous amount of logic into one file. The methods are long, tangled, and we're still using local state. To that end, we should consider a refactor to make it easier to read, easier to add code, and more testable.

**Comment by abbyraskinUSDS** [comment]
@mdbenjam can we close this?

**Comment by mdbenjam** [comment]
Yes we can!
