### ISSUE TITLE
Cleanup spec/support/form8-TEST.pdf after test executes

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2397]
# Description
Make sure the spec/support/form8-TEST.pdf file is deleted after the test that generates it is executed.

# AC
- [ ] `rake ci` is executed and the spec/support/form8-TEST.pdf file does not exist

**Comment by kierachell** [comment]
1. Clone repo
1. Bundle install
1. Npm install
1. Run `git status`
1. Run `ls -la spec/support`
1. Run `bundle exec rake`
1. Run `ls -la spec/support`
1. Find `form8-TEST.pdf` in there
1. Be sad!

**Comment by kierachell** [comment]
**PASSED**
the folder is empty and `tmp/pdfs` is not tracked anyway so should be ok :D
