### ISSUE TITLE
PDF file not found or upload failed

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#24]
![image](https://cloud.githubusercontent.com/assets/950486/10398314/64d14294-6e7a-11e5-9282-b34def0132e1.png)

Environment: UAT
Test ID: 633522287

Steps to Recreate:

1. Go to Caseflow
1. Fill out the form and continue
1. Attempt to certify it

Expected:

Uploaded to VBMS

Actual:

System error

**Comment by plusjeff** [comment]
Not able to recreate. Tried with multiple veterans and multiple logins. Likely a VBMS hiccup. Issue #21 might make this easier to spot if it occurs again.
