### ISSUE TITLE
PDF Viewer | Viewing a case with only one document hides "Back to all documents" link

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2406]
# Description
When viewing a Case where there is only 1 document,
if I go to the PDF Viewer  - the `back to all documents` button is not there :(

## Reproduction Steps

**Scenario 1 -**

1. Go to a case with 1 document
1. View that 1 document
1. Note the `back to all documents` link missing
1. Be sad

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [WHERE IS IT AT?!]_**
![backtowhat](https://user-images.githubusercontent.com/18075411/27436253-a60596ba-572c-11e7-9702-d93944fcaa5e.gif)

**Comment by mdbenjam** [comment]
This should be fixed now.

**Comment by kierachell** [comment]
**PASSED**
It's an edge case anyway
