### ISSUE TITLE
Cache Read messages are spamming Caseflow log files

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#2407]
When Prometheus queries the the application `/metrics` endpoint, there are a set of **Cache Read**  messages written to the log files. They are very verbose, and we should disable them to increase the signal-to-noise ratio.

![image](https://user-images.githubusercontent.com/3258724/27436235-981a383a-572c-11e7-88ea-a636c908dd35.png)

After some quick searches, the issue might be related to [our cache logging level](https://stackoverflow.com/questions/7254184/how-to-set-rails-cache-log-level-separately). I believe it is currently [set to `debug`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/config/environments/production.rb#L46).

## AC ##
- Cache read messages do not appear in logs
- Use AWS to access Cloudwatch -> and find Log Streams from `prod`, `preprod` and `uat` for currently running instances and validate that the logs do not include `Cache read` logs (shown above)
- Alternatively you can use https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/cheatsheet/logs.md to access logs from each environment and validate that the above shown spam does not show up.

**Comment by kierachell** [comment]
1h of logs is over 50 mb sometimes :(

**Comment by kierachell** [comment]
- Directly from the deploy! (using demo for PII and stuffs)
![screen shot 2017-07-12 at 7 05 13 am](https://user-images.githubusercontent.com/18075411/28114829-7f52b486-66d0-11e7-838d-68d3e01b065f.png)

**Comment by kierachell** [comment]
There was a rogue instance in production that resulted in the spam continuing beyond the fix.
Killed the instances.
Logs are clean.

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate: 
1. Access AWS Cloudwatch
2. Go into the logs for Preprod, Prod, and UAT for currently running instances 
3. Validate that the logs do not contain "Cache Read" logs

Screenshots: 
<img width="1168" alt="screen shot 2017-07-14 at 9 50 11 am" src="https://user-images.githubusercontent.com/23038505/28215112-d868b538-687a-11e7-82bf-fa1690aea35a.png">
<img width="1174" alt="screen shot 2017-07-14 at 9 52 23 am" src="https://user-images.githubusercontent.com/23038505/28215110-d866d380-687a-11e7-839b-ebbfb19c59f9.png">
<img width="1173" alt="screen shot 2017-07-14 at 9 52 50 am" src="https://user-images.githubusercontent.com/23038505/28215111-d86792a2-687a-11e7-971a-6df39bc83099.png">
<img width="1168" alt="screen shot 2017-07-14 at 9 53 19 am" src="https://user-images.githubusercontent.com/23038505/28215113-d868e1ca-687a-11e7-9a85-2bafa5f616fd.png">
<img width="1170" alt="screen shot 2017-07-14 at 9 53 47 am" src="https://user-images.githubusercontent.com/23038505/28215114-d869d9e0-687a-11e7-8a5e-75277e1a2b64.png">
<img width="1179" alt="screen shot 2017-07-14 at 9 55 31 am" src="https://user-images.githubusercontent.com/23038505/28215115-d86d3c84-687a-11e7-8533-f720c1c49d3b.png">
