### ISSUE TITLE
Can't process cases for veterans with no SSN

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2409]
https://github.com/department-of-veterans-affairs/appeals-support/issues/193

**Comment by laurjpeterson** [comment]
Note: per conversations already had with BGS, it cannot support appeals for Veterans without SSNs. there is no way for us to change this.

**Comment by laurjpeterson** [comment]
Adding an error message to address Veterans without SSNs in #2252
