### ISSUE TITLE
Document Viewer | Loading nearby PDFs hold up rendering of current view

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2412]
# Description
When loading a large document or a case with many documents,
sometimes it takes forever to render the current PDF into view because it seems like other PDFs are loading in the background

## Reproduction Steps

**Scenario 1 -**

1. Go to a case with many documents (1255968 in `uat`)
1. Go to view a document
1. Watch the network calls in the background
1. Move about to a document with 100+ pages
1. Watch slow network calls
1. See PDF not render for ever
1. See scrollbars and buttons lock up

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Loading about]_**
![loadingeverything](https://user-images.githubusercontent.com/18075411/27443395-e05a1c0a-5740-11e7-8140-2d7348bbda3d.gif)

**_Scenario 1 - [Cannot move!]_**
![lotsa pages](https://user-images.githubusercontent.com/18075411/27443407-eaae6116-5740-11e7-8fde-aefe6e035a7e.gif)

# Related Issues

**_Engineering_**
#1959

**Comment by mdbenjam** [comment]
This code has been completely overhauled. This issue is no longer relevant.
