### ISSUE TITLE
Analytics | Add timestamps to all Reader tables

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2418]
Currently we do not store `created_at` or `updated_at` timestamps for annotations. We're losing data that would be potentially useful for analytics in the future. 

#### Acceptance Criteria:
- the 2 timestamp columns (created_at, updated_at) have been added to all Reader tables
- The new timestamp columns are automatically set on create and update

**Comment by kierachell** [comment]
**PASSED**
```
Annotation Load (1.6ms)  SELECT  "annotations".* FROM "annotations"  ORDER BY "annotations"."id" DESC LIMIT 1
=> #<Annotation id: 256, document_id: 21115, comment: "created at\n", page: 1, x: 347, y: 92, user_id: 90, created_at: "2017-10-20 12:22:40", updated_at: "2017-10-20 12:22:40">
```
