### ISSUE TITLE
Bug: Ensure loading indicator appears when Form 9 is loading on UAT and prod

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2419]
The Form 9 is slow, so we should definitely have a loading indicator. It seems to appear on demo, but for some reason it didn't show up in prod. Let's check UAT and ensure that it shows up.

This seems to be exclusive to IE:
- The PDF is force downloading, instead of rendering the thing. Maybe PDFJS is broke?
<img width="1062" alt="screen shot 2017-07-07 at 11 27 43 am" src="https://user-images.githubusercontent.com/18075411/27964771-6a0fb9ba-6307-11e7-9104-001ca619290e.png">
- Download instead of render:
<img width="1025" alt="screen shot 2017-07-07 at 11 27 46 am" src="https://user-images.githubusercontent.com/18075411/27964772-6a13d298-6307-11e7-8de5-90fec61284e5.png">

## AC
- Using a Windows machine with Internet Explorer
- Visit Certification v2
- Proceed to Certify an Appeal
- On UAT , loading indicator is displayed before Form 9 is loaded

**Comment by kierachell** [comment]
### Currently in UAT

![form9](https://user-images.githubusercontent.com/18075411/28465199-e3b25a40-6df5-11e7-96cb-f49f67c44907.gif)
![form999](https://user-images.githubusercontent.com/18075411/28465200-e3d754bc-6df5-11e7-89f0-cf5a3b48938e.gif)

- JS Console log:
```
Error: Required "glyf" or "loca" tables are not found
```
Presumably it loads:
![screen shot 2017-07-21 at 9 22 52 am](https://user-images.githubusercontent.com/18075411/28465294-3942221a-6df6-11e7-8353-80230ac3085e.png)

**Comment by astewarttistatech** [comment]
Still not showing up in IE

**Comment by amprokop** [comment]
@nemodjuric — I remember that you spent a decent amount of time on this issue, but it was very tricky. When you're back in, can you post some details about what you found/tried?

**Comment by nemodjuric** [comment]
@amprokop We had PR for this (#2664) where we fixed pdf viewer showing in IE. However, spinner loading issue is still there.
