### ISSUE TITLE
[V2 - For St. Pete] Modify text of the hearing question

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2420]
### Acceptance Criteria

@astewarttistatech  This _can_ be validated in `demo` as it requires no integration whatsoever - just Certification v2 access

1. Instructions underneath the Confirm Hearing heading are: "Check the eFolder for the appellant’s most recent hearing preference."
2. The first question on the Confirm Hearing page is: "Has the appellant requested a change to their hearing preference since submitting the Form 9?"

### Screenshots

![confirm hearing wording change](https://user-images.githubusercontent.com/1178390/27704464-bb49c7ba-5cd8-11e7-87cf-be31a5a4e0a2.png)

**Comment by shellicious** [comment]
![confirm hearing wording change](https://user-images.githubusercontent.com/1178390/27699371-17fa885c-5cc8-11e7-9455-3ff17dd4a9eb.png)

Updated wording!

**Comment by kierachell** [comment]
**PASSED**
from `uat`
<img width="898" alt="screen shot 2017-07-07 at 8 39 14 pm" src="https://user-images.githubusercontent.com/18075411/27981093-65af47ee-6354-11e7-806a-06f735c19b10.png">
