### ISSUE TITLE
Prefill DRO's name and title on the Sign and Certify page

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2421]
As a Caseflow Certification user, I would like my name to auto-populate on the Sign & Certify page so that I don't have to type it in each time I certify a case.

It doesn't appear to be possible to prefill the user's title.

Acceptance Criteria:
- When the user gets to the Sign & Certify page, their name auto-populates into the Name field.
- Use the CSS user object to get the user's name. 
- Name field is still editable.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Reproduce: 
1. Log into the UAT environment of Caseflow with a css_id that has a name associated it with it (found in Rails or VACOLS)
2. Access Certification V2 with an appeal that is ready to certify 
3. Navigate to the Sign and Certify page
4. Validate upon page upload, the DRO's name is preloaded
5. Select that text field and edit the text. 

Screenshots: 
![droprefilled](https://user-images.githubusercontent.com/23038505/29269583-42dcccbc-80c0-11e7-869e-15bf8b47f129.gif)
