### ISSUE TITLE
React on Rails | Move header from Rails to React

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2422]
We currently render the page header in a Rails erb file. This leads to several problems:

1. We cannot make the homepage link a React-Router Link, so it forces us to make a network request when we could stay within the SPA.
1. We cannot modify the header within the SPA with things like the veteran's name, or breadcrumbs about which page you're on.

# AC
- [x] Verify there is a new React component that replaces our current header erb template.
- [x] Verify Reader uses this new template and header component.
- [x] Verify the header looks the same as it currently does, except for the removal of the what's new option.
- [x] Verify the new header sends analytics for:
  - When the dropdown menu is opened, closed, or blurred.
  - When any option in the dropdown menu is clicked.

**Comment by kierachell** [comment]
**PASSED**

wooo

<img width="590" alt="screen shot 2017-09-12 at 9 59 30 am" src="https://user-images.githubusercontent.com/18075411/30329834-75854494-97a1-11e7-9cd5-bcd5fa2cc0e3.png">
<img width="285" alt="screen shot 2017-09-12 at 9 59 47 am" src="https://user-images.githubusercontent.com/18075411/30329835-75869588-97a1-11e7-8903-cc51987b4ab8.png">
<img width="559" alt="screen shot 2017-09-12 at 10 00 29 am" src="https://user-images.githubusercontent.com/18075411/30329833-7581fa50-97a1-11e7-863e-9d45ae5c8409.png">
