### ISSUE TITLE
Accordion Component

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2424]
We need an Accordion Component for Reader.

**Comment by mdbenjam** [comment]
Duplicate of #1482

**Comment by mmlumba** [comment]
@mdbenjam @gnakm Is there a story for implementing accordions into Reader?

**Comment by gnakm** [comment]
@mmlumba  yes here: https://github.com/department-of-veterans-affairs/caseflow/issues/2161
