### ISSUE TITLE
[V2] Investigate: how many Form 9s in VBMS have the same date

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2427]
Multiple Form 9s with the same date came up twice during the NYRO pilot. Before investing design/dev resources into building a feature around this edge case, we wanted to assess how prevalent this problem is. 

It would be great to know:
- In VBMS, how many Form 9s have the same date?
- What percentage of Form 9s have the same date?

**Comment by cmgiven** [comment]
Are we looking for the prevalence of two appeals for the same Veteran that have the same Form 9 date? Or do we need to look to VBMS to understand whether they have multiple documents? (Querying VBMS is difficult, so hoping the former.)

**Comment by amprokop** [comment]
If you think the former is a reasonable proxy for the latter, then the former is probably fine IMO — thoughts @shellicious?

**Comment by cmgiven** [comment]
Yeah, I think it's the difference between how many Veterans _should_ have two Form 9 documents with the same date, versus how many _do_ have two Form 9 documents.

**Comment by shellicious** [comment]
We'd like to assess approximately how often the edge case of two Form 9s for the same veteran occurs (could be the same appeal, could be different appeals, there's no way to tell without reading the Form 9s and other docs). If it's really infrequent, we can deprioritize designing/building around this edge case. If it is frequent enough, then we should prioritize designing/building a future.

I'd prefer to know how many veterans _do_ have two Form 9 documents with the same date, @cmgiven. Is that the easier one to figure out?

**Comment by cmgiven** [comment]
To actually look at documents in VBMS will take some time, but I ran the easier numbers, and the results surprised me.

Of all Veterans who have appeals that have been perfected (have a Form 9) but have not been certified, *6%* have two or more appeals with the same Form 9 date. That's a pretty decent number. Perhaps that's sufficient to help with prioritization?

```r
cases <- query("select BFCORLID, BFD19 from BRIEFF where BFD19 is not null and BF41STAT is null and BFMPRO = 'ADV'")

n_vets <- length(unique(cases$BFCORLID))

n_multi9 <- cases %>%
  count(BFCORLID, BFD19) %>%
  filter(n > 1) %>%
  nrow()

n_multi9 / n_vets
```

**Comment by shellicious** [comment]
Wow, that seems higher than I expected. Thanks @cmgiven! @laurjpeterson @amprokop, what do you think about prioritizing this as a feature to design this or next sprint?

**Comment by laurjpeterson** [comment]
That is surprising! @shellicious yep, I think it makes sense to get a design out for this. cc: @cmgiven @amprokop
