### ISSUE TITLE
Error Page: give text that indicates that you can change the dates in VACOLS or VBMS

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#243]

**Comment by KHarshawat** [comment]
blocked by #328

**Comment by webinista** [comment]
#328 is now closed. Is this change now reflected in the [copy on that page?](https://github.com/department-of-veterans-affairs/caseflow/issues/328#issuecomment-167583985)

**Comment by KHarshawat** [comment]
Yup! Closing!
