### ISSUE TITLE
Form 8:  Question 5A, 6A, 7A:  Automatically expand text area fields as they fill up

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#243]
As a Caseworker, I would like to have the text boxes for question 5A, 6A, and 7A to automatically grow as I type so that I see everything I have typed without scrolling or manually stretching the box to fit all of the text.

### Acceptance Criteria
1. Verify that for question 5A when the text box fills up, it automatically expands allowing for viewing all text entered.
1. Verify that for question 6A when the text box fills up, it automatically expands allowing for viewing all  text entered.
1. Verify that for question 7A when the text box fills up, it automatically expands allowing for viewing all text entered.

### Tech Notes
Character limits for questions:  5A: 5500, 6A: 1000, 7A: 1000.

### Sub-tasks
Investigate jquery library to handle this.

### Initial Comments
Request from Virginia Grissom. She said they often have to enter a lot of info into 5A, 6A, and 7A. The current text boxes are far to small to see everything.

I'm cool with implementing this, just wanted to get the heads up from you @KHarshawat that it's the right way forward

**Comment by KHarshawat** [comment]
Expanding the text box as you type sounds great. Just don't want it to be huge by default.

**Comment by shanear** [comment]
:+1:

**Comment by nikitarockz** [comment]
@shanear What is the maximum character limit for questions 5a, 6a, and 7a?

**Comment by shanear** [comment]
@nikitarockz 5A: 5500, 6A: 1000, 7A: 1000.

**Comment by nikitarockz** [comment]
@shanear So, would you say that you would be able to increase the character limit for 6a & 7a to 5500 and 7000 for 5a?

**Comment by shanear** [comment]
This story isn't about the character limits. It's about having the text field "grow" as you enter enough text into them.

The comment box on github actually does this 😄 . Try entering 8 newlines and youll see the text area get bigger to accomidate for them

**Comment by nikitarockz** [comment]
Ok, got it.  It is just for viewing more text.

**Comment by astewarttistatech** [comment]
@amprokop only a scrollbar is added to the textbox, the box itself does not auto-expand.

**Comment by amprokop** [comment]
this is now merged @astewarttistatech

**Comment by kierachell** [comment]
This was held up because it was not merged; 

Correct behavior verified for all fields.
<img width="626" alt="screen shot 2016-12-21 at 21 29 10" src="https://cloud.githubusercontent.com/assets/18075411/21413353/92105282-c7c4-11e6-9e40-84ef28e7a06e.png">
<img width="603" alt="screen shot 2016-12-21 at 21 29 24" src="https://cloud.githubusercontent.com/assets/18075411/21413352/920f46ee-c7c4-11e6-88b5-c9d6b9bc0b52.png">
