### ISSUE TITLE
Make Google Analytics useful

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#2430]
We need a sensible way to record and understand Google Analytics stuff

## Acceptance criteria
- [x] Configure GA to work with `certification.cf.ds.va.gov` and `appeals.cf.ds.va.gov`
- [x] Make it easy to send page events to Google Analytics
- [x] Investigate whether we can send the page name (ie. `Document Page`) vs the page url (ie. `/document/1234`)
- [x] Get unique page views working (ideally by page name)

## Reader events to track
Click tracking
Documents list page
   - Search box
   - Expand all (note: this is changing to notes toggle)
   - Categories filter icon
   - Categories filters checkbox (x3)
   - Issue tag filter icon
   - Issue tag filters checkbox (varies per case)
   - Sort link: receipt date
   - Sort link: document type
   
PDF viewer    - “Back to claims folder” button
   - “Hide menu” button
   - Arrows within document
   - Jump to page
   - Zoom +/-
   - Download
   - Document type link
   - Add comment buttonGlobal    - Help link
   - Reader logo

**Comment by NickHeiner** [comment]
@shanear is going to take this on.

**Comment by shanear** [comment]
Current plan of attack:

- [ ] Make it easy to send page events to Google Analytics
- [ ] Get a sensible GA dashboard that gets rid of all the online marketing mumbo jumbo that's useless to us (bounce rate, funnel metrics, etc), and highlights events.
- [ ] Figure out how to share that dashboard with the rest of the team.
- [ ] Investigate whether we can send the page name (ie. `Document Page`) vs the page url (ie. `/document/1234`)
- [ ] Get unique page views working (ideally by page name)

**Comment by shanear** [comment]
Proposed google analytics event structure for the events:
(see https://support.google.com/analytics/answer/1033068#Anatomy)

"Controls"
"focus"
"Search"

"Controls"
"click"
"Search Box"

"Controls"
"click"
"Expand all"

"Controls"
"click"
"Category filter"

"Controls"
"click"
"Clear category filter"

"Documents"
"order"
"Receipt date", "Document type" 

"Documents"
"filter-by-category"
"Medical", "Procedural", "Other Evidence"

"Documents"
"filter-by-issue"
ISSUE_TAG

"Controls"
"click"
"Add Comment"

"Controls"
"click"
"Document Type"

"Controls"
"click"
"Download"

"Controls"
"click"
"Jump to Page"

"Controls"
"click"
"Zoom In"

"Controls"
"click"
"Zoom Out"

"Controls"
"click"
"Hide Menu"

"Controls"
"click"
"Next Document Arrow"

"Controls"
"click"
"Previous Document Arrow"

"Links"
"click"
"“Back to claims folder”

"Links"
"click"
"Reader Logo"

"Links"
"click"
"Reader Help"

**Comment by shanear** [comment]
@abbyraskin is it okay if we just track referrals (ie. users navigate to the help page from the document viewer page) instead of link clicks for the logo and the help click? They happen to be a little tricky and Google recommends to just use pageviews instead:

https://developers.google.com/analytics/devguides/collection/analyticsjs/events#outbound_link_and_form_tracking

**Comment by abbyraskin** [comment]
@shanear to make sure i'm understanding, we'll know what page they were on when they clicked the logo (for example), but will have no sense of frequency for the element itself?

**Comment by shanear** [comment]
Validated in prod. Moving documentation and dashboards to another ticket.
Also moving header GA events to another ticket
