### ISSUE TITLE
Create Dockerfile and new Jenkinsfile to mock Travis setup

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2436]
- [x] Create a Dockerfile to at least mock the test environment to be used with Jenkins/CircleCi/locally/or any other CI pipeline that accepts Docker.
- [x] Create a new Jenkinsfile (separate of the current Jenkinsfile) that sets up a Kubernetes cluster with Postgres, Redis and the Ruby containers to be used for the Jenkins instance Vets.gov has set up
- [x] Set up a Jenkins job (in the new instance) to execute all tests for the Caseflow project

# AC
- Running the docker-compose steps in your development environment build the docker container and start an environment
- The [DSVA Jenkins test environment](https://a54c945d65e0311e7843f0206c2f3847-1313167371.us-gov-west-1.elb.amazonaws.com) pulls the container successfully from the DSVA Docker repo and spawns an environment with k8s
- The Jenkins instance executes all tests with similar stages as the current Travis setup
    - Flakey tests will be addressed in separate tickets

**Comment by NickHeiner** [comment]
See also: #2293.

/cc @kierachell in case you have also done work with Docker for this.

**Comment by kierachell** [comment]
One fix was added at 12:30pm today

I am basically waiting for the Jenkins builder to stabilize:
![screenshot_2017-07-19_14-30-50](https://user-images.githubusercontent.com/18075411/28383270-e8788f30-6c8e-11e7-8844-52bbd8eb1228.png)

**Comment by kierachell** [comment]
- Waiting on a Kubernetes patch: https://github.com/jenkinsci/kubernetes-plugin/blob/master/CHANGELOG.md#012
- Waiting for production deployment of the whole builder

**Comment by kierachell** [comment]
sadface
