### ISSUE TITLE
Fix Hearings Schedule

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2437]
Related to #1883

When the user visits the hearings schedule page, the browser should show a loader then make an API request for dockets, which, when loaded, are displayed in a table where the first column (date) links to each docket.

**This will make the page match the screenshot in the AC of #1883.**

[ SCREEN SHOT ]

Currently, the API returns an array of dockets:
<img width="366" alt="screen shot 2017-06-23 at 11 22 25 am" src="https://user-images.githubusercontent.com/1053255/27489312-17e154f0-5808-11e7-8f56-7202d4d3426a.png">

Instead, return a hash of dockets indexed by date:
<img width="736" alt="screen shot 2017-06-23 at 11 50 54 am" src="https://user-images.githubusercontent.com/1053255/27489904-4394933a-580a-11e7-8f33-91a20774e14b.png">

Thus, when a judge clicks on a docket date, react-router can load the Docket component and quickly populate it by retrieving from the hash instead of traversing an array for an object with the right date.  Since there's no need for another API call to get a docket, the judge has a better UX.

**Comment by slj** [comment]
Solution in action:

![load_hearings](https://user-images.githubusercontent.com/1053255/27635145-ec1471e8-5bd3-11e7-8d5d-e53b39170609.gif)

**Comment by laurjpeterson** [comment]
Per most recent Invision mocks, the title of this page should be 'Upcoming Hearing Days'. We changed it because we will be building a separate Hearing Schedule solution. 

https://va-gov.invisionapp.com/d/main/#/console/11372263/240352625/preview

cc: @lakohl @slj @kierachell @sharonwarner

**Comment by kierachell** [comment]
@laurjpeterson I know it's a small change, but let's make that a separate issue for when that page actually comes out so that we can see the full flow together.

**Comment by laurjpeterson** [comment]
@kierachell good point. will create a ticket to make that update. thank you!

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: Chrome and FF

Steps to Validate: 
1. Log into the Caseflow app with an CSS login that works for Hearings (Caseflow_397)
2. Turn on Hearings function
3. Toggle on the Hearings function
4. Access /hearings/dockets
5. Check the network console for the json response for arrays

Screenshots: 
<img width="1430" alt="screen shot 2017-07-19 at 2 37 11 pm" src="https://user-images.githubusercontent.com/23038505/28384196-cb792a2c-6c91-11e7-876a-302d495c4180.png">
<img width="1440" alt="screen shot 2017-07-19 at 2 38 30 pm" src="https://user-images.githubusercontent.com/23038505/28384195-cb784e86-6c91-11e7-87a5-b26bfe600fdc.png">
