### ISSUE TITLE
Page up/down keyboard shortcuts do not work in FF

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#2439]
<h1>Template</h1>

**Description:** 

When in Caseflow Reader on the single document view, pressing `alt+up arrow` or `alt+down arrow` keys does not cause the page to move up or down in Firefox. 

**Expected Results (If Any):**

The page up and page down shortcuts should work

**Browser Found:** Firefox

**Environment Found:** Demo

**Associated Issues/Stories:**

#2107 

***

- [ ]    5 - Data loss, data corruption or system unavailable

- [ ]    4 - Important functionality is unavailable with no workaround

- [ ]    3 - Important functionality is unavailable but has a
reasonable workaround

- [ ]    2 - Secondary functionality is unavailable but has a
reasonable workaround

- [ ]    1 - Cosmetic issues or some functionality unavailable but has
a simple workaround

**Comment by mdbenjam** [comment]
We realized that alt + up/down only works on chrome. Changed the shortcuts to space, shift + space to work across browsers.
