### ISSUE TITLE
Viewport tests for Reader fail on 13 inch Mac

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#2441]
Description:
When running a test locally on a 13 inch Macbook, any tests with the `in_viewport` helper fail because Capybara cannot generate a large enough screen size. Also Capybara does not scroll to the element in the viewport.

Example:
```
Failures:

  1) Reader Large number of documents Open a document and return to list
     Failure/Error: expect(in_viewport("read-indicator")).to be true

       expected true
            got false
     # ./spec/feature/reader_spec.rb:802:in `block (3 levels) in <top (required)>'
```

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
