### ISSUE TITLE
Move fake vacols DB out of Rails auto-reload path

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2443]
Right now we save our in-memory fake "VACOLS DB" on `Fakes::AppealRepository.records` and `Fakes::HearingRepository.hearing_records`, etc. These classes get auto-reloaded by Rails in development mode on file save. This causes our in-memory DB to get wiped every save. 

#### Acceptance Critiera:
Move storing fakes from a class that is auto-reloaded by Rails to one that is explicitly outside the autoreload path. Consider making something like a  `VACOLS::DB` class in a different directory and push the current records and document_records there instead. That way it can survive between file saves and rails class reload

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
