### ISSUE TITLE
Remove all create() calls from Generators' build() methods

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2444]
Currently, we call `create` on other models [from within our generators](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/generators/establish_claim.rb#L6). This means, even if you call `build()` and create the model in memory, you are still persisting the associated model to the DB. If possible, we should not be calling `create` inside generator `build` methods.

#### Acceptance Criteria
- Remove all `create` calls from inside generator `build` methods. Instead consider alternatives such as `find` to use an existing model in the DB, or `new` and creating an associated model in memory

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
