### ISSUE TITLE
Appeal List | Add loading indicator

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2445]
# Description
When going to Reader for the first time
it can take a bit of time to load all the appeals/veteran info,
but there's no indication about how long...

## AC 
- [ ] Add loader similar to the loader for loading document list page 
   - [ ] [Style guide reference](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#loaders)
- [ ] Copy should say "Loading Reader..."

## Mockup
![image](https://user-images.githubusercontent.com/13420618/27543749-109d853a-5a59-11e7-95db-71ae5b3a98ea.png)

## Related issue 
#1999

**Comment by gnakm** [comment]
Thanks @kierachell. Moved original copy here and edited it for the AC above. 

# Description
When going to Reader for the first time
it can take a bit of time to load all the appeals/veteran info,
but there's no indication about how long...

## Reproduction Steps

**Scenario 1 -**

1. Go to Reader for the first time
1. See nothing
1. Wait
1. See something
1. Wonder if lag

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod


## Screenshots
**_Scenario 1 - [SLOW]_**

<img width="1272" alt="screen shot 2017-06-23 at 6 32 11 pm" src="https://user-images.githubusercontent.com/18075411/27502474-4e40b312-5842-11e7-8e04-42606014bb39.png">


# Related Issues

**_Engineering_**
#1999

**Comment by kierachell** [comment]
**PASSED**

I mean...it was done via another ticket so...
