### ISSUE TITLE
Organize directory structure for external dependencies in Caseflow

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#2447]
1. Remove app/repositories directory as it is unclear what it means.
2. Place BGS and VBMS code under app/services/external_api* and Vacols repositories under app/services/vacols/*
3. Place report code under app/services/reports/* directory
4. Leave local services in app/services/* directory

**Comment by laurjpeterson** [comment]
@aroltsch do you think we still need this ticket?

**Comment by aroltsch** [comment]
I think we can close it
