### ISSUE TITLE
Document list | change loader message

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2450]
**Description**
We are now calling Documents list --> Claims folder.

## AC
- New copy: Loading claims folder in Reader…

## Mock up:
![image](https://user-images.githubusercontent.com/13420618/27542083-282a1c2c-5a54-11e7-8c66-6a3039fb93e7.png)

**Comment by kierachell** [comment]
**PASSED**
![loader](https://user-images.githubusercontent.com/18075411/27880008-86d379d2-6191-11e7-9a1b-42a2aff18090.gif)
