### ISSUE TITLE
Dispatch Test Suite Updates

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2454]
Dispatch's feature tests are not in a good state. We currently skip several of them, and even the tests we do run are flaky and unreliable. We need to determine why the tests are flaky and update the test suite. 

# AC
1. Stop skipping tests
1. Run the entire test suite wrapped with [ensure_stable](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/reader_spec.rb#L5) and make sure it passes locally and on travis 10 times.

**Comment by sharonwarner** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/2647

**Comment by tejans24** [comment]
Blocked by Travis not being functional

**Comment by sharonwarner** [comment]
![Screen Shot 2018-01-30 at 2.29.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582a398e7d9c5f1300c030ee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f36b7191a37af110224f5a5c5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19141c95df74ce24955a2123360e7742431.png)

These tests have failed a few times today.

**Comment by tejans24** [comment]
@sharonwarner I think we should close this issue out, we haven't seen any dispatch test failures in a while.
