### ISSUE TITLE
Fix skipped tests | Reader Spec

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2455]
We currently skip the following test(s):

"Zooming changes the size of pages"

# AC
1. Stop skipping the test(s)
1. Run the test(s) wrapped with [ensure_stable](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/reader_spec.rb#L5) and make sure it passes locally and on travis 10 times.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
