### ISSUE TITLE
Fix skipped tests | Login Spec

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2456]
We currently skip the following test(s):

"With valid credentials"
"Logging out redirects to home page"
"Single Sign On is down"

# AC
1. Stop skipping the test(s)
1. Run the test(s) wrapped with [ensure_stable](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/reader_spec.rb#L5) and make sure it passes locally and on CI 10 times.

**Comment by laurjpeterson** [comment]
we don't use travis anymore, so closing.

**Comment by pkarman** [comment]
these tests are still skipped, putting this in backlog.
