### ISSUE TITLE
Fix skipped tests | Certification Specs

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2457]
We currently skip the following test(s):

"Trying to skip steps" - save_certification_spec
"When user tries to skip by manually entering URL"  - start_certification_spec

# AC
1. Stop skipping the test(s)
1. Run the test(s) wrapped with [ensure_stable](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/reader_spec.rb#L5) and make sure it passes locally and on travis 10 times.

**Comment by nemodjuric** [comment]
@mdbenjam @amprokop This issue does not seem to be current anymore. These tests are part of current build and they are passing.

**Comment by amprokop** [comment]
cool, closing
