### ISSUE TITLE
[v2 - For St. Pete] Refresh page error after NOD date discrepancy error 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#2466]
## Description  
When user click "Refresh this Page" after correcting the NOD date in VBMS, instead of getting a green success page, takes them to an erroed "Review Form 8 page." This error occurred three times. Once organically and once artificially as we re-created the issue. 

## Reproduction Steps 
1.) NOD not found after launching Caseflow Certification V2
<img width="378" alt="screen shot 2017-06-26 at 4 17 32 pm" src="https://user-images.githubusercontent.com/23316107/27558307-fee3d18c-5a8a-11e7-8b0b-7e8df7e704a8.png">
2.) User updates the date in VBMS 
3.) User clicks "Refresh this page" 
<img width="391" alt="screen shot 2017-06-26 at 4 11 56 pm" src="https://user-images.githubusercontent.com/23316107/27558135-375eb28a-5a8a-11e7-9d45-dda3adbc094f.png">

4.) Instead of refreshing the table it goes to a "Review Form 8" page with a blank document preview and the banner "unexpected server response" (see screen shot)
<img width="464" alt="screen shot 2017-06-26 at 4 08 31 pm" src="https://user-images.githubusercontent.com/23316107/27558044-d6116e82-5a89-11e7-9117-e40de803c9a9.png">
4.) User clicks the back button
<img width="33" alt="screen shot 2017-06-26 at 4 13 08 pm" src="https://user-images.githubusercontent.com/23316107/27558199-7b89244a-5a8a-11e7-84d4-a616f3a5380b.png">
5.) Table is updated correctly 
<img width="389" alt="screen shot 2017-06-26 at 4 13 43 pm" src="https://user-images.githubusercontent.com/23316107/27558202-7f5154f8-5a8a-11e7-851a-f9a1b1c9c0f0.png">

## Sentry:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/259/

**Comment by kierachell** [comment]
Can't exactly reproduce this...weird:
![fixdate](https://user-images.githubusercontent.com/18075411/27564346-f765aeca-5aa4-11e7-81ec-cae7f8d44e86.gif)

**Comment by kierachell** [comment]
JUST DID IT!

It is specific to IE!
![refresh](https://user-images.githubusercontent.com/18075411/27866040-e777bd22-6162-11e7-9f6d-d2c8d11cad0d.gif)
<img width="1048" alt="screen shot 2017-07-05 at 9 04 00 am" src="https://user-images.githubusercontent.com/18075411/27866039-e7766896-6162-11e7-99d3-f63b73eef233.png">
<img width="615" alt="screen shot 2017-07-05 at 9 04 04 am" src="https://user-images.githubusercontent.com/18075411/27866042-e77a161c-6162-11e7-94ba-498e75e4947f.png">

**Comment by kierachell** [comment]
**PASSED**

WOooo! Fixed it!
![refreshagain](https://user-images.githubusercontent.com/18075411/27878579-b51436ec-618c-11e7-920a-83263a1045cb.gif)
