### ISSUE TITLE
[Backend] Update upcoming_hearings_for_judge Query

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2468]
Currently the logic identifies master records incorrectly, doesn't pull in records with dispositions (during the day, judges would lose access to their hearings after they fill out the disposition) and doesn't pull in empty dockets.

Acceptance Criteria:
- Ensure we pull in hearings records from VACOLS such that we know about video empty dockets
- Ensure we are correctly identifying and handling master records
- Ensure we pull in future hearings and that have taken place for the past week

Note: travel board empty dockets will be handled in another ticket

**Comment by sharonwarner** [comment]
More details from Jed:

a) video
video master records are designated by hearing_type = "c" but folder_nr = "Video RO##" 
can't have multiple master records for same room/day/time 
same room/day is fine, but the restrictions on offices would need to change so we don't schedule 11 hearings for a 1 hour master record
b) central
central office hearings don't have the same concept of a master record. jed goes through and creates placeholder entries. if the hearing_type = "c", but folder_nr is blank, that's a placeholder entry. there are also dummmy numbers for folder_nr for holidays, training days, etc. 
we currently can't assign a judge without a veteran, but scott is trying to get them to change that. 
because there's no master record, in theory, we could assign a different judge for each hearing in a room in a day
c) travel board
travel board master records are in a different table, tb_sched. the children records are still in hear_sched

**Comment by sharonwarner** [comment]
While pulling data for Lauren, I discovered that the original query might be wrong. Going to look into that as well. 

Pull upcoming hearings for the pilot judges: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/295

**Comment by laurjpeterson** [comment]
@sharonwarner if it helps, see attached judges and their upcoming hearings for 8/22/2017 - 9/30/2017 Scott pulled earlier today 
[Judges current schedule 22 Aug 17.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1242915/Judges.current.schedule.22.Aug.17.pdf)

**Comment by kierachell** [comment]
@aroltsch 
https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries004.htm

select master records
union
select children records
```
with horrible_query_1 as (
  select .. .. ..
    from .. .. ..
) ,
ugly_query_2 as (
  select .. .. ..
     .. .. ..
)
(select * from horrible_query_1 minus select * from ugly_query_2    ) union all
(select * from ugly_query_2     minus select * from horrible_query_1)
```

**Comment by kierachell** [comment]
### This broke the frontend... not sure where to put the error, but you're trying to read master record's FOLDER_NR as BFKEY for whatever reason

```
STARTED VACOLS: load_vacols_data VIDEO RO17
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-08309bcff9db06fa9-172.30.70.64 [appeals.cf.preprod.ds.va.gov] [a9c2a45c-5d4c-4590-8e17-f74aa2e7deb5] [172.30.70.64] [CASEFLOW_317   caseflow@va.gov] [2017-09-13 20:27:09 -0400]   VACOLS::Case Load (105.9ms)  SELECT  "VACOLS"."BRIEFF".* FROM "VACOLS"."BRIEFF" WHERE "VACOLS"."BRIEFF"."BFKEY" = :a1 AND ROWNUM <
= 1   [["bfkey", "VIDEO RO17"]]                                                                                                                                                                             dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-08309bcff9db06fa9-172.30.70.64 [appeals.cf.preprod.ds.va.gov] [a9c2a45c-5d4c-4590-8e17-f74aa2e7deb5] [172
.30.70.64] [CASEFLOW_317   caseflow@va.gov] [2017-09-13 20:27:09 -0400]    (1.1ms)  BEGIN                                                                                                                   dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-08309bcff9db06fa9-172.30.70.64 [appeals.cf.preprod.ds.va.gov] [a9c2a45c-5d4c-4590-8e17-f74aa2e7deb5] [172
.30.70.64] [CASEFLOW_317   caseflow@va.gov] [2017-09-13 20:27:09 -0400]    (1.0ms)  COMMIT                                                                                                                  dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-08309bcff9db06fa9-172.30.70.64 [appeals.cf.preprod.ds.va.gov] [a9c2a45c-5d4c-4590-8e17-f74aa2e7deb5] [172
.30.70.64] [CASEFLOW_317   caseflow@va.gov] [2017-09-13 20:27:09 -0400] Completed 500 Internal Server Error in 5005ms (ActiveRecord: 4632.8ms)                                                              dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-08309bcff9db06fa9-172.30.70.64 [appeals.cf.preprod.ds.va.gov] [a9c2a45c-5d4c-4590-8e17-f74aa2e7deb5] [172
.30.70.64] [CASEFLOW_317   caseflow@va.gov] [2017-09-13 20:27:09 -0400]                                                                                                                                     dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-08309bcff9db06fa9-172.30.70.64 NoMethodError (undefined method `gsub' for nil:NilClass):
  app/models/appeal.rb:392:in `sanitized_vbms_id'                                                                                                                                                             app/services/external_api/vbms_service.rb:37:in `fetch_documents_for'
  app/models/appeal.rb:463:in `fetched_documents'                                                                                                                                                             app/models/appeal.rb:305:in `fetch_documents!'
  app/models/appeal.rb:89:in `documents'                                                                                                                                                                      app/models/appeal.rb:100:in `number_of_documents'
  app/models/hearing.rb:52:in `number_of_documents'                                                                                                                                                           app/models/hearing.rb:45:in `block in <class:Hearing>'
  app/models/concerns/cached_attributes.rb:37:in `instance_eval'                                                                                                                                              app/models/concerns/cached_attributes.rb:37:in `block in cache_attribute'
  app/models/hearing.rb:66:in `to_hash'                                                                                                                                                                       app/models/hearing_docket.rb:22:in `map'
  app/models/hearing_docket.rb:22:in `hearings_array'                                                                                                                                                         app/models/hearing_docket.rb:9:in `to_hash'
  app/controllers/hearings/dockets_controller.rb:7:in `block (2 levels) in index'                                                                                                                             app/controllers/hearings/dockets_controller.rb:5:in `index'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                            app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by aroltsch** [comment]
Yes, that's because video master records don't have an appeal associated with them. hearshed.folder_nr doesn't contain a brieff key

**Comment by kierachell** [comment]
So it shouldn't look it up that way then.

**Comment by aroltsch** [comment]
Yup, we need to figure out what to do with these master records.

**Comment by aroltsch** [comment]
Need to wait for FE to be fixed.

**Comment by kierachell** [comment]
@sharonwarner 

### Yup, Dockets page is broken:
<img width="364" alt="screen shot 2017-09-16 at 5 02 08 pm" src="https://user-images.githubusercontent.com/18075411/30515997-f5d419b0-9b00-11e7-937c-3420e632a007.png">
<img width="288" alt="screen shot 2017-09-16 at 5 02 31 pm" src="https://user-images.githubusercontent.com/18075411/30515998-f5d49944-9b00-11e7-9ea7-4c20600f468d.png">
<img width="442" alt="screen shot 2017-09-16 at 5 02 44 pm" src="https://user-images.githubusercontent.com/18075411/30515999-f5d5515e-9b00-11e7-9895-23b5181f1f69.png">

**Comment by kierachell** [comment]
**PASSED**

We're getting the records alright, it's the other shit that's broke
