### ISSUE TITLE
[Backend] [Spike] Investigate where we can pull periods of service from in BGS

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2469]
We would like to pre-fill the hearings worksheet with the Veteran's periods of service. We believe we can pull this from a BGS endpoint. For this ticket, investigate which BGS endpoint & data would fit these needs.

If we successfully find a way to prefill this,  we should create a new ticket implementing this

Note: We may want to reach out to the VBMS team in the `dsva-vbms` repo and creae an issue. They should be able to tell us where they pull the same information in the VBMS UI.

**Comment by joofsh** [comment]
Verified that we are able to pull a Veteran's periods of service from BGS 's `VetRecordWebService` which we already integrate with in production! 

The information exists within the `VetRecordService`'s `find_by_file_number` method. In order to retrieve this information, we will need to make updates to `ruby-bgs` which is done in this PR: https://github.com/department-of-veterans-affairs/ruby-bgs/pull/36#pullrequestreview-54476728. After that gets merged and updated, we can pull veteran's periods of service from the `service` key.  Within the `service` object, relevant attributes to period of service are:
- `branch_of_service`
- `entered_on_duty_date`
- `released_active_duty_date`

Further information about where we can pull this information can be found in the dsva-vbms issue here: https://github.com/department-of-veterans-affairs/dsva-vbms/issues/89

**Comment by kierachell** [comment]
Sample return
```
info[:service]
=> [{:short_service_number=>nil,
  :service_number_fill=>nil,
  :branch_of_service=>"ARMY",
  :entered_on_duty_date=>"01012005",
  :released_active_duty_date=>"01012011",
  :separation_reason_code=>"SAT",
  :nonpay_days=>nil,
  :pay_grade=>"E1 ",
  :char_of_svc_code=>"HON"},
 {:short_service_number=>nil,
  :service_number_fill=>nil,
  :branch_of_service=>nil,
  :entered_on_duty_date=>nil,
  :released_active_duty_date=>nil,
  :separation_reason_code=>nil,
  :nonpay_days=>nil,
  :pay_grade=>nil,
  :char_of_svc_code=>nil},
 {:short_service_number=>nil,
  :service_number_fill=>nil,
  :branch_of_service=>nil,
  :entered_on_duty_date=>nil,
  :released_active_duty_date=>nil,
  :separation_reason_code=>nil,
  :nonpay_days=>nil,
  :pay_grade=>nil,
  :char_of_svc_code=>nil}]```

**Comment by kierachell** [comment]
**PASSED**
Just make sure you know how to handle `no BIRLS record found` error
