### ISSUE TITLE
[Backend] Pull in issue "notes" from VACOLS

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2472]
Right now when we pull in issues from VACOLS, we don't include the issue's "note". Now we want to include those as well.

Technical Note:
- Determine which table/column the notes are stored in (ask Chris or Jed)
- Add that attribute to the Issue model `load_from_vacols`

**Comment by aroltsch** [comment]
@cmgiven Would you know know how to get `notes` for issues?

**Comment by cmgiven** [comment]
That's `ISSUES.ISSDESC`.

**Comment by kierachell** [comment]
**PASSED**
Just know that it gets a bunch of notes:
```
[nil, "Whether NME submitted to reopen SC for back disability"]
```
