### ISSUE TITLE
[Frontend] Persist daily docket changes to redux

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2473]
Hook up the daily docket page to the Redux store

Acceptance Criteria:
- Create a redux store for Hearing Prep
- Initially load the hearings into the redux store
- On user input change, update the redux store accordingly

Note:
- No backend integration needed in this ticket

**Comment by slj** [comment]
I've gotten this to a place where I need to discuss things with some engineers before doing any more.  I like the direction it's going if it's not acceptable I need to know now.

**Comment by astewarttistatech** [comment]
**FAILED** @sharonwarner 

Current view (UAT): 
<img width="1436" alt="screen shot 2017-08-14 at 7 02 55 am" src="https://user-images.githubusercontent.com/23038505/29269287-ab3df9fe-80be-11e7-9b3d-c9c9043da83d.png">

Console output:
<img width="1430" alt="screen shot 2017-08-14 at 7 04 04 am" src="https://user-images.githubusercontent.com/23038505/29269364-0de96732-80bf-11e7-8fa4-9b5c6eca7e2e.png">

**Comment by astewarttistatech** [comment]
@sharonwarner Any particular reason why this was moved back to in validation? It's still failing.

**Comment by astewarttistatech** [comment]
**FAILED** Sorry  @sharonwarner 

Current View: 

<img width="1437" alt="screen shot 2017-08-16 at 9 44 06 am" src="https://user-images.githubusercontent.com/23038505/29366280-9deb5594-8267-11e7-8cf4-011059f82682.png">

Resulting Sentry: https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/419/

**Comment by kierachell** [comment]
## Why is there two redux stores?
<img width="1242" alt="screen shot 2017-08-20 at 12 14 16 pm" src="https://user-images.githubusercontent.com/18075411/29496462-3f26bc00-85a1-11e7-88cc-1b5e20349957.png">

**Comment by sharonwarner** [comment]
That's a Reader issue. If you just click on the second instance you'll see hearings redux info.

**Comment by kierachell** [comment]
**PASSED**

Well, ok... is there a Reader-related ticket to fix this or... feature?
