### ISSUE TITLE
[Frontend] Hearing Worksheet : Persist Appellant/Veteran Information to redux

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2474]
Hook up the editable fields in the Appellant/Veteran Information section on the hearing worksheet page to the Redux store

Acceptance Criteria:
- Ensure rep name and witness/observer in the Appellant/Veteran information is initially saved to redux store on pageload
- On user input change, update the redux store accordingly

Notes:

Do not send the information to the backend. 
Do not hook up any additional fields.

**Comment by kierachell** [comment]
**PASSED**
![sameworksheet](https://user-images.githubusercontent.com/18075411/29876786-a9005b00-8d6b-11e7-89b5-fe0c0874a32e.gif)
