### ISSUE TITLE
Style guide component | Toggle buttons

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2478]
## Description
As a developer or designer, I want to know what a component that can helps users toggle between views looks like. 

## AC
- Under the button section add a subsection for Toggle
- The selected view should be in [primary button default](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#buttons) and have a drop shadow
- The unselected view should be in [secondary button default](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#buttons) and should not have its text bolded
- The length of each toggle button should be the same, following the longer word with the defaulted 20px margin left and right for the style guide button styling. 
- For the style guide, user View 1 and View 2 for the two view options
- User should be able to click between both options

## Mockup 
![image](https://user-images.githubusercontent.com/13420618/27561896-0006ecc2-5a98-11e7-84b7-a50e667feacf.png)

## Related product
#2229

**Comment by Sjones352** [comment]
@gnakm please let me know if the drop shadow is thick so I can reduce it. Still working on the margins.
![togglebutton](https://user-images.githubusercontent.com/23080951/28148617-ee550cfa-6755-11e7-9097-107afd690b4f.gif)

**Comment by Sjones352** [comment]
@gnakm and @mmlumba  this is the toggle button.
![togglebutton](https://user-images.githubusercontent.com/23080951/28318229-07512f7c-6b98-11e7-8665-055f457ffeed.gif)

**Comment by Sjones352** [comment]
![togglebutton](https://user-images.githubusercontent.com/23080951/28323441-da985e4c-6ba6-11e7-91fc-884aadd0fcd7.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF, IE, Chrome 

Steps to Validate: 
1. Access Styleguide
2. Navigate to Toggle Buttons
3. Verify criteria against Mocks and AC

Screenshots:
<img width="1136" alt="screen shot 2017-07-19 at 1 48 17 pm" src="https://user-images.githubusercontent.com/23038505/28381520-2d65a5d4-6c89-11e7-8483-bbd74a56340e.png">
<img width="1139" alt="screen shot 2017-07-19 at 1 48 54 pm" src="https://user-images.githubusercontent.com/23038505/28381519-2d34c34c-6c89-11e7-9d98-17930114b035.png">
