### ISSUE TITLE
Support "Out of Service" mode

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow#248]
As a developer, when external dependencies go down, we need to quickly declare the application to be out of service. Ideally, if `OUT_OF_SERVICE` is defined, it will prevent user from making changes to the site.

## Acceptance Criteria
- Verify that the AC in https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/312 are true for Caseflow

## Notes 
- The functionality should be in caseflow commons (see: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/312)
- We should remove the current VBMS releated error message mechanism in favor of this generic one.

## Earlier Notes
Caseflow is susceptible to the following outages:
- [x] **VBMS is down** -- we correctly detect and inform user of VBMS outages
- [ ] **Caseflow itself is down** -- nginx 502 and 503 pages should be customized to inform user of the outage, see department-of-veterans-affairs/deployment#222
- [ ] **SSOI/IAM service is down** -- There's no  way for us to detect this because the user would be redirected to the SSOI page. One solution is to have a manually toggled internal flag that disables logins and instead displays an error message. Ideally this would be done via distributed cache or a DB value so all instances can be updated at once without a deployment/restart.

**Comment by KHarshawat** [comment]
If we can figure out a way to show these messages we should still do this. Ideally these are messages we can re-use accross all of Caseflow and so can be a part of Caseflow Commons.

**Comment by askldjd** [comment]
@shanear 

> One solution is to have a manually toggled internal flag that disables logins and instead displays an error message. Ideally this would be done via distributed cache or a DB value so all instances can be updated at once without a deployment/restart.

Definitely a good idea. However, I don't think we have any pub/sub infrastructure (e.g. zookeeper) in our architecture today. Since all our apps have scaling group of 1, I would say just keep it simple for now and allow a ENV to be set. We can write a simple ansible role to restart all apps.

**Comment by shanear** [comment]
@askldjd I like that solution. Short and simple.

**Comment by kierachell** [comment]
@nemodjuric Would you be able to add a link to `test/users` or maybe `test/setup` where we can toggle this feature?

**Comment by kierachell** [comment]
![screenshot_2017-02-25_21-26-50](https://cloud.githubusercontent.com/assets/18075411/23336555/7c5e7430-fba1-11e6-8a73-c7153ba73b6f.png)
And with **APP BRANDING**
![screenshot_2017-02-25_21-27-55](https://cloud.githubusercontent.com/assets/18075411/23336557/80a86c6c-fba1-11e6-9aae-d0d37c45b184.png)

**Comment by kierachell** [comment]
However, it seems like I am unable to log out when the "site is down". Is that intended?
I will need confirmation from @orischwartz and @askldjd that Nemo's work satisfies the AC.
![peek 2017-02-25 21-31](https://cloud.githubusercontent.com/assets/18075411/23336582/f4c2447e-fba1-11e6-98c9-b252eaf28eea.gif)
