### ISSUE TITLE
Rethink how permissions work for prod

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2488]
Currently, we only have one permission level. If someone can access AWS and `ssh` into prod boxes, they can do quite a lot. It would be nice to have more granular permissions levels. Operating with a high permissions level is dangerous because you can easily break things. We would prefer to have a safer permissions level that can still be used to diagnose issues without as much risk of creating new issues.

**Comment by askldjd** [comment]
For reference, here are the available access that we give to everyone with access today. 

Vault password access, which allows you to decrypt all private keys and accounts in appeals-deployment.

Prod access to jumpbox, which leads to BGS/VACOLS/VBMS/VVA read/write access. It also allows ssh'ing to Prod EC2 instance, which allows you to read/write Redis/PG data.

AWS resource access (see image for access)
![image](https://user-images.githubusercontent.com/3258724/27651687-31d6d8a0-5c07-11e7-9e39-289e4939f99a.png)

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
