### ISSUE TITLE
Style Guide | Create Intro section

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2492]
**Description**
This was feedback from the style guide ticket

## AC
Create an intro section with the following

`h2` Purpose of style guide copy
`h3` Instructions
  - Link to creating a style guide ticket
  - Link to how to use style guide

`h3` Files for Designers 
- Link to Sketch UI kit master file
- Link to SVG files folder

## Related
#2353

**Comment by mmlumba** [comment]
@gnakm Do you have relevant copy for this section or are you working on that?

**Comment by gnakm** [comment]
@mmlumba Sorry. Pushing this back because it's not ready.

**Comment by gnakm** [comment]
Closing this and will have a WIP issue in design repo.
