### ISSUE TITLE
Documents List | Filtering by message

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2496]
## Description
Currently our filtered alert is too abrupt and confusing some users. We instead will use text that is less jarring yet still informative to our users. 

## AC
- Instead of the blue information alert box that shows limited results, show text underneath the search box that says what the documents are being filtered by and the number of filters per section. 
    - Example: Filtering by: Categories (1), Issue tags (4), Comments.
- Insert a Clear all filters - link appears after the "Filtering by" sentence.
- When documents list is being filtered by comments but there aren't any, still show it in the sentence.
- If the "Comments" toggle is selected, but the user clicks the "clear all filters" link, they should jump to the "Documents" view
- Should be selectable from a keyboard

## Mock up
![image](https://user-images.githubusercontent.com/13420618/27708208-21b06718-5ce6-11e7-8013-d8e9c07b31ad.png)

## Related
#2229

**Comment by tejans24** [comment]
I have a branch issue-1998 with most of the code done, it's a dependent on #2229 to be completed to show the comment filter message.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Toggle comments on
3. Filter by Issue tags and Categories
4. Verify that the sentence reflects what has been filtered. 

Screenshots: 
![newfilterf](https://user-images.githubusercontent.com/23038505/28923910-adbed34a-782d-11e7-80ec-5abbec694bb2.gif)
