### ISSUE TITLE
Documents list | Add heading with Veteran's name

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2497]
## Story
As an attorney or judge, I want to know whose claims folder I am reviewing. 

## AC
- Add h1 ([see style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography)) with the name of the Veteran
- Veteran's name should match the name showing in the welcome gate (First Last)
## Mock up 

![image](https://user-images.githubusercontent.com/13420618/27662245-05db19ae-5c2b-11e7-8c18-04f114af7526.png)

**Comment by mdbenjam** [comment]
Have most of the changes here. Waiting until Teja is done with #1998 before I proceed.

**Comment by mogrenAtWork** [comment]
Looks like this was taken care of with #1998 

<img width="1317" alt="screen shot 2017-08-01 at 7 02 17 am" src="https://user-images.githubusercontent.com/10132008/28822741-7492e29c-7688-11e7-8092-c136dfe487a3.png">

@gnakm was there anything else you had in mind for this ticket?

**Comment by gnakm** [comment]
lgtm!
