### ISSUE TITLE
Documents list | Show number of documents viewed

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2498]
**Story**
As an attorney or judge, I want to know how many documents I have already viewed. This helps the user set expectations on their workload. 

## AC
- At the right of the Veteran's name, show the message, "You've viewed x of y documents" in <p>
  - Ex. You’ve viewed 50 out of 100 documents
- Make sure it is right-aligned with the accordion

## Mock up

![image](https://user-images.githubusercontent.com/13420618/27662477-ef84c19a-5c2b-11e7-8d1b-84473b5ec504.png)

**Comment by mdbenjam** [comment]
I have most of the changes here. Waiting to do this with #2497

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Reader 
2. Validate the count viewed to the Document List view is right aligned to the accordion menu and is visible

Screenshots: 
<img width="1174" alt="screen shot 2017-08-02 at 10 09 36 am" src="https://user-images.githubusercontent.com/23038505/28877767-5e358430-776b-11e7-9e10-9c508a0f1923.png">
