### ISSUE TITLE
Style guide| Loader copy enhancement

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2503]
**Story**
As a user, I need to be informed that the loader color should match the color of the Caseflow app I am working on 

## AC
- [x] Replace current description with the copy below
- [x] Make sure that there is a text link that goes to the colors section below.

## Copy

A large Caseflow loading indicator in the center of the page is used when some information has been retrieved but other information is still being pulled. Each loader should have a message underneath the logo in `gray-dark` that explains what is currently happening or where the information is being drawn from. Loader should match the respective Caseflow app logo. Designers are responsible for letting developers know that defaulted color in the source code needs to be the color of the app logo. See [Caseflow Logos](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#colors) under the Colors section.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF, IE, Chrome

Steps to Validate: 
1. Access the living style guide
2. Navigate to the Loaders section
3. Verify the copy against what is listed in the AC

Screenshots:
<img width="1246" alt="screen shot 2017-07-21 at 10 25 08 am" src="https://user-images.githubusercontent.com/23038505/28467811-16dd3dbe-6dff-11e7-804c-6d927565f17b.png">
