### ISSUE TITLE
Drag and Drop | Text dropped onto a page

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2508]
We use drag and drop to move comments on pages. However, we don't validate the event.dataTransfer object in onCommentDrop in Pdf.jsx.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/267/activity/

# AC
1. Verify that dragging non-comments onto a pdf page does not cause an error, but that it does fire a Google Analytics event.

**Comment by astewarttistatech** [comment]
Currently Google Analytics are not turned on for UAT.

**Comment by kierachell** [comment]
<img width="442" alt="screen shot 2017-07-26 at 2 12 02 pm" src="https://user-images.githubusercontent.com/18075411/28636578-9471d40e-720c-11e7-8fc8-6c20632401e0.png">

**Comment by NickHeiner** [comment]
Ah, sorry, I could have been more clear about that. When GA is not enabled for an environment, you will see the following fake GA events in the console:

![image](https://user-images.githubusercontent.com/829827/28646264-d5428696-722e-11e7-9acc-075c6eded517.png)

If you see this, you can assume that GA is working.

**Comment by kierachell** [comment]
**PASSED**

- Text dragged
- No errors seen
- GA event attempted to fire
<img width="847" alt="screen shot 2017-07-26 at 7 00 56 pm" src="https://user-images.githubusercontent.com/18075411/28647379-d54940c0-7234-11e7-89d9-29f7461746a4.png">
