### ISSUE TITLE
Welcome Gate | populate table with VACOLS locations instead of DAS assignments

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#2511]
Currently, we're using assignment data from DECASS to build the list of work assignments; instead, we should pull in cases in the user's current location in VACOLS.

## AC
- Welcome Gate page is updated to reflect the mockup below
    - 'Work Assignments' `h2` title is now 'Cases Checked In'
    - Rename **View case file** to **View claims folder**
    - 'Learn more about Reader on our Help Page' is now 'Learn more about Reader on our FAQ page' and below the search box (search box completed with another ticket)
    - 'View Case File' column header is changed to 'View Claims Folder'
    - Add a new header column labeled `Issues` between Veteran ID and View claims folder and have appropriate Issues matching the appeal.
    - Format: 
        ```
      1. <Issue 1 code label>:
           <level 1 label>
           <level 2 label>
            <level 3 label>
      2. <Issue 2 code label>:
            <level 1 label>
           <level 2 label>
            <level 3 label>
        ```
    - Remove description under `h1` (Reader allows attorneys and judges review and annotate a Veteran’s case file. Reader allows attorneys and judges review and annotate a Veteran’s case file.)
- Welcome Gate displays all cases where the current location is the user. (i.e. where BRIEFF.BFCURLOC is equal to STAFF.SLOGID for the current user)
- If an appeal has multiple issues, have the issues stack on top of each other. 

## Mock up 
![image](https://user-images.githubusercontent.com/13420618/28182563-9f1dcea8-67da-11e7-806c-943ddb616d73.png)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/1998
https://github.com/department-of-veterans-affairs/caseflow/issues/2521

**Comment by kierachell** [comment]
1. Does this mean `CURLOC` value?
1. What is DAS? Do you mean DECASS?:
These are the column names from `DECASS` in VACOLS
```
[1] DEFOLDER    DEATTY      DETEAM      DEPDIFF     DEFDIFF     DEASSIGN    DERECEIVE   DEHOURS     DEPROD      DETREM      DEAREM      DEOQ        DEADUSR    
[14] DEADTIM     DEPROGREV   DEATCOM     DEBMCOM     DEMDUSR     DEMDTIM     DELOCK      DEMEMID     DECOMP      DEDEADLINE  DEICR       DEFCR       DEQR1      
[27] DEQR2       DEQR3       DEQR4       DEQR5       DEQR6       DEQR7       DEQR8       DEQR9       DEQR10      DEQR11      DEDOCID     DERECOMMEND
```

**Comment by abbyraskin** [comment]
Yeah, I think we're pulling in DEASSIGN from DAS now. @mdbenjam or @mogrenAtWork please add any technical AC here. @gnakm do you have an updated design for this page we should use?

**Comment by mogrenAtWork** [comment]
@kierachell to answer your questions:
1. I'll work with you and @cmgiven to determine the best query for this since I don't know the VACOLS schema
2. The welcome gate is currently querying DECASS, I corrected the description above to reflect this.

Do we have the schema anywhere I can access?

**Comment by abbyraskin** [comment]
@mogrenAtWork Chris certainly can answer this question better than I can, but this folder may be helpful as a starting point (it includes my personal favorite document, all the tables in VACOLS!): https://github.com/department-of-veterans-affairs/appeals-pm/tree/f56963df7cd26c10e671566981fe1163efd6b320/VA%20Tech%20System%20Documentation/VACOLS

**Comment by cmgiven** [comment]
The welcome gate is currently querying DECASS. After initial testing with users, we learned that this pulls in a number of cases that users do not expect to see, cases that were once assigned to them, and which they no longer own despite the assignment being incomplete.

Instead, we should pull those cases where the current location is the user. That would be where `BRIEFF.BFCURLOC` is equal to `STAFF.STAFKEY` for the user in question (the staff table contains all VACOLS users, in addition to generic locations; `STAFF.SDOMAINID` is the CSS ID of the user in question).

**Comment by abbyraskin** [comment]
(FYI the VACOLS report attorneys use for this purpose today is called "Cases checked in" -- Mark is reaching out to Jed to verify the data pulled here, but current location seems correct at first glance.)

**Comment by gnakm** [comment]
I added a mock up above. The `h2` is labeled Cases checked in and it should represent the cases checked into their location.

**Comment by mogrenAtWork** [comment]
Awesome, thanks all! I'll get cracking on this

**Comment by mdbenjam** [comment]
According to Jed:

The report uses the current location field in the BRIEFF table and their VACOLS logon id STAFF.SLOGID.
 
BRIEFF.BFCURLOC = STAFF.SLOGID

**Comment by mogrenAtWork** [comment]
@gnakm should there be any indentation for the `issue levels` below the issue description?

**Comment by gnakm** [comment]
@mogrenAtWork Yes! So it should always be that the texts are left aligned to each other and not the numbers.

**Comment by kierachell** [comment]
#### We discussed this and there were some redundant joins BRIEFF -> DECASS -> CASES_VACOLS_DECASS_JOIN:
```
SELECT defolder as vacols_id, deassign as date_assigned, dereceive as date_received, staff.slogid as vacols_user_id, brieff.bfddec as signed_date, brieff.bfcorlid as vbms_id, corres.snamef as veteran_first_name, corres.snamemi as veteran_middle_initial, corres.snamel as veteran_last_name FROM "VACOLS"."DECASS" INNER JOIN "VACOLS"."STAFF" ON "VACOLS"."STAFF"."SATTYID" = "VACOLS"."DECASS"."DEATTY" INNE
R JOIN "VACOLS"."BRIEFF" ON "VACOLS"."BRIEFF"."BFKEY" = "VACOLS"."DECASS"."DEFOLDER" INNER JOIN "VACOLS"."BRIEFF" "CASES_VACOLS_DECASS_JOIN" ON "CASES_VACOLS_DECASS_JOIN"."BFKEY" = "VACOLS"."DECASS"."DEFOLDER" INNER JOIN "VACOLS"."CORRES" ON "VACOLS"."CORRES"."STAFKEY" = "CASES_VACOLS_DECASS_JOIN"."BFCORKEY" WHERE (staff.sdomainid = 'CASEFLOW_317' and brieff.bfcurloc = staff.slogid)
```

**Comment by kierachell** [comment]
#### Not all issues per appeal are showing up:

 - I see 3
```
issues <- VACOLSfetch(DEVcon, getIssues, "isskey = '2142572'")
> str(issues)
'data.frame':	3 obs. of  14 variables:
 $ ISSKEY       : chr  "2142572" "2142572" "2142572"
 $ ISSSEQ       : num  1 2 3
 $ ISSDC        : chr  NA NA NA
 $ ISSDESC      : chr  NA NA NA
 $ ISSPROG      : chr  "02" "02" "02"
 $ ISSCODE      : chr  "15" "15" "15"
 $ ISSLEV1      : chr  "03" "03" "03"
 $ ISSLEV2      : chr  "7354" "8100" "9411"
 $ ISSLEV3      : chr  NA NA NA
 $ ISSPROG_LABEL: chr  "Compensation" "Compensation" "Compensation"
 $ ISSCODE_LABEL: chr  "Service connection" "Service connection" "Service connection"
 $ ISSLEV1_LABEL: chr  "All Others" "All Others" "All Others"
 $ ISSLEV2_LABEL: chr  "Hepatitis C (or non-A, non-B hepatitis)" "Migraine" "Post-traumatic stress disorder"
 $ ISSLEV3_LABEL: chr  NA NA NA
```

- But only 1 in reader:
![screenshot_2017-07-19_12-41-39](https://user-images.githubusercontent.com/18075411/28378838-a1380362-6c7f-11e7-86af-ce82d1fea910.png)

**Comment by mogrenAtWork** [comment]
@kierachell I've updated the AC to be a little cleared about the format to expect in the Issues column:
        ```
        1.  <Issue code label>:
             <level 1 label>
             <level 2 label>
             <level 3 label>
        ```

The number `1` corresponds to the issue for the case, if there are multiple issues for the case, you'll see numbers 1,2,3....

**Comment by kierachell** [comment]
### So what I am not seeing is:
from @cmgiven 
```
First off, the ISSUES table is uniqued on the combination of ISSKEY (which matches BFKEY from BRIEFF, etc) and ISSSEQ.
```

<img width="1053" alt="screen shot 2017-07-20 at 8 36 19 am" src="https://user-images.githubusercontent.com/18075411/28417653-ec73d458-6d26-11e7-88f2-7eea0392ed65.png">

 - expected:
```
$ ISSKEY       : chr  "1939416" "1939416" "1939416" "1939416" ...
 $ BFKEY        : chr  "1939416" "1939416" "1939416" "1939416" ...
 $ BFCORLID     : chr  "408157325S" "408157325S" "408157325S" "408157325S" ...
 $ ISSSEQ       : num  1 2 3 5 6 7 8 9
```
- 8 issues

**Comment by kierachell** [comment]
**PASSED**
Gonna make a separate issue to make this display better:
![andithoughtihaveissues](https://user-images.githubusercontent.com/18075411/28435398-b8706a56-6d60-11e7-8eb3-29067ca05925.gif)
