### ISSUE TITLE
Sidekiq | Prepare Tasks job silently doesn't happen

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2513]
## Description

On the night of June 29th to 30th the Sidekiq `PrepareEstablishClaimTasksJob` job just didn't happen;
<img width="914" alt="screen shot 2017-06-30 at 3 53 36 pm" src="https://user-images.githubusercontent.com/18075411/27756071-5cd02c16-5dc2-11e7-968c-805c664343be.png">

The logs do not show it happening
The UI shows that it did not run.
Reasons? Unknown. I wish I had more info.
Manually triggering it from console ran the job successfully and generated 300ish tasks

## Investigation options:

- Have some kind of report pushed to us in case a job failed or failed to run: `Task.where(aasm_state: "unassigned").count` - if it's 0 at 4am on a weekday, probably means something went wrong.
- Short term queue up the job twice. Run it again at 4am just in case
- Long term invest time into why sidekiq cron doesn’t work. As we start adding more background jobs we’re going to feel even more pain from this

**Comment by mperham** [comment]
1. You are using an old version of sidekiq-cron.  Upgrade, maybe the bug was fixed?
2. Have you considered Sidekiq Enterprise and its periodic job support?

**Comment by kierachell** [comment]
We will try that, @mperham 
Can't really validate it any other way that I can think of.

**Comment by kierachell** [comment]
**PASSED**
The issue has not come up in a week.
I made a separate ticket for capturing potential failures.
