### ISSUE TITLE
App Canvas | Re-enable "System Admin" functionality in Production

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2514]
# Description
A member of our Developer/Support/etc team attempts to smoke-test/access our application in Production - we do not have access to `/functions` page or any other `admin-access` page for that matter.

@nikitarockz tagged to confirm if/when/how "System Admin" will be disabled for our users
@amprokop tagges because he can remove `Cert v2` function and leave it as `FeatureToggle` only
@NickHeiner tagged because is this across the whole app and this is needed for Prod Squad functionality

**Possible Solution**: remove System Admin role completely and make it a FeatureToggle for specific CSS_IDs that we can control

Please edit this issue with proper implementation steps.

## Reproduction Steps

**Scenario 1 -**

1. Go to Prod
1. Try to access `/functions`
1. Fail

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

**Comment by NickHeiner** [comment]
@kierachell do you need help from me on this?

**Comment by amprokop** [comment]
Is the problem that we used to have a user with the System Admin role, but we don't have one anymore? So therefore we can't access stats or functions pages?

**Comment by kierachell** [comment]
Users with `System Admin` role (provided by CSUM and CSS login) are not able to access `functions` or any other admin pages.

**Comment by kierachell** [comment]
Obsoleting this since there will be a discussion about this stuff with appropriate action items
