### ISSUE TITLE
VACOLS | How to handle cases where BFCORLID != SSN

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2515]
# Description
When API call is made using a veteran's SSN, we assume that BFCORLID field in VACOLS will end with `S` and that it will match the SSN. However:
```
> VACOLSfetch(PRODcon, "select COUNT(*) from BRIEFF where ", "BFCORLID like '%C%'")
  COUNT(*)
1  1340476
> VACOLSfetch(PRODcon, "select COUNT(*) from BRIEFF where ", "BFCORLID like '%S%'")
  COUNT(*)
1  1709737
```
That's 1340476 appeals that veterans cannot access if BGS is out or something is off anyway.

@cmgiven tagged to provide guidance

## Reproduction Steps

**Scenario 1 -**

1. Go to `curl` the API with an SSN
1. See that VACOLS stores BFCORLID=`*******C` and not `*******S`
1. Get `{"data":[]}`
1. Go to VACOLS and see that there's plenty of appeals for that SSN there
1. Get mad.

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:

```
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Fri, 30 Jun 2017 23:04:27 GMT
ETag: W/"e0234245cb00aa260ccfa99a9a0b235e"
Server: nginx/1.10.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 77cb6c7d-ca1e-4113-abda-860b7428823b
X-Runtime: 1.577812
X-XSS-Protection: 1; mode=block
Content-Length: 11
Connection: keep-alive

{"data":[]}
```

meanwhile in VACOLS:
```
     BFKEY   BFCORLID       SSN BFAC                BFDNOD                BFDSOC                 BFD19               BFSSOC1              BF41STAT
1  1302932 124041722S 124041722    8 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0                  <NA> 2000-01-20 00:00:00.0
2   453462  22486941C 124041722    1 1991-03-15 00:00:00.0 1991-03-29 00:00:00.0 1991-09-13 00:00:00.0                  <NA>                  <NA>
3   921735  22486941C 124041722    1 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2003-01-09 00:00:00.0 2000-01-20 00:00:00.0
4  1213162  22486941C 124041722    3 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2003-01-09 00:00:00.0 2000-01-20 00:00:00.0
5  1213162  22486941C 124041722    3 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2003-01-09 00:00:00.0 2000-01-20 00:00:00.0
6  1213162  22486941C 124041722    3 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2003-01-09 00:00:00.0 2000-01-20 00:00:00.0
7  1213162  22486941C 124041722    3 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2003-01-09 00:00:00.0 2000-01-20 00:00:00.0
8  1316356  22486941C 124041722    7 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2003-01-09 00:00:00.0 2000-01-20 00:00:00.0
9  1790689  22486941C 124041722    7 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2008-03-25 00:00:00.0 2000-01-20 00:00:00.0
10 2073514  22486941C 124041722    7 1999-08-31 00:00:00.0 1999-11-22 00:00:00.0 1999-12-20 00:00:00.0 2010-06-08 00:00:00.0 2000-01-20 00:00:00.0
```

**Comment by cmgiven** [comment]
This contradicts my understanding of what the API is doing. I thought we were looking up the SSN using BGS to identify the file number? @shanear, can you clarify?

**Comment by kierachell** [comment]
None of the cases where I set the file number to have `C` at the end have ever worked.

**Comment by shanear** [comment]
> When API call is made using a veteran's SSN, we assume that BFCORLID field in VACOLS will end with S and that it will match the SSN. 

This is not the case. We look up the file number by SSN in BGS. We then convert the file number to a VACOLS BFCORLID according to the following logic.
```
def convert_file_number_to_vacols(file_number)
      return "#{file_number}S" if file_number.length == 9
      return "#{file_number.gsub(/^0*/, '')}C" if file_number.length < 9

      fail Caseflow::Error::InvalidFileNumber
end
```
We use the BFCORLID to look up appeals in VACOLS.

The problem here, is that it relies on BGS being up. If BGS is down. All non-cached appeals are down.

@kierachell

**Comment by amprokop** [comment]
@kierachell — does shane's response here satisfy you? can you take a look and modify this ticket or close it if there'sno action to take?

**Comment by kierachell** [comment]
closing in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/2639
