### ISSUE TITLE
Welcome Gate | Add issues column

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2521]
## Story
As an attorney, it is hard to distinguish the difference between different appeals of the same Veteran at a glance on the welcome gate page. 

We will be adding the Issues as a new column. 

## AC

- [ ] Add a new header column labeled Issues between Veteran ID and View claims folder and have appropriate Issues matching the appeal. This information is currently labeled "Levels.." in VACOLS
- [ ] Rename **View case file** to **View claims folder**
- [ ] Change `h2` **Work assignments** to **Cases checked in**
- [ ] Remove description under `h1` (Reader allows attorneys and judges review and annotate a Veteran’s case file. Reader allows attorneys and judges review and annotate a Veteran’s case file.)
- [ ] If an appeal has multiple issues, have the issues stack on top of each other. 

## Mock up

![image](https://user-images.githubusercontent.com/13420618/28032057-37bb11c2-6577-11e7-8fde-18d2f7cfb1a4.png)

## Related
#2342
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/288

**Comment by abbyraskin** [comment]
@cmgiven can you clarify which column in VACOLS we should look at here? Is it BFCASEV?

**Comment by cmgiven** [comment]
It's `ISSUES.ISSPROG`, which need to be joined on `ISSREF.PROG_CODE` in order to get the label (`ISSREF.PROG_DESC`). Alternatively, we could hardcode our preferred labels and skip the join, which may be preferable anyway, as some of the program names are quite long.

**Comment by cmgiven** [comment]
(Also note that we'll need to allow for the possibility of multiple program areas, probably comma separated? Two program areas is a reasonably common edge case. Three is possible but rare.)

**Comment by abbyraskin** [comment]
Thanks!

**Comment by gnakm** [comment]
@abbyraskin 

How about stacking instead of commas? The some of the programs are kind of long and stacking might look cleaner. 

![image](https://user-images.githubusercontent.com/13420618/27805504-1439b862-6003-11e7-8d0d-501860db58ac.png)

I don't think this really effects other views:
![image](https://user-images.githubusercontent.com/13420618/27805433-9b142404-6002-11e7-9e1c-40ea896d9391.png)

![image](https://user-images.githubusercontent.com/13420618/27805444-bc8b09cc-6002-11e7-8b0f-6d19edbd8b32.png)

**Comment by abbyraskin** [comment]
definitely agree @gnakm!

**Comment by abbyraskin** [comment]
note to figure out what our preferred hardcoded labels are for all of these - i think that's a better route

**Comment by abbyraskin** [comment]
@cmgiven how many program areas are there? could you paste them here when you have a chance? (or direct us to them? tried finding them myself and failed!)

**Comment by cmgiven** [comment]
```
   COUNT(*)                            PROG_DESC
1         9                        Loan Guaranty
2         3                            Insurance
3        28            BVA Original Jurisdiction
4       164                              Medical
5       437                              Pension
6         7 NCA Burial benefits (38 CFR Part 38)
7        37  VBA Burial benefits (38 CFR Part 3)
8        26                       Other programs
9     62876                         Compensation
10       19                                 VR&E
11      122                            Education
```

```sql
select count(*), PROG_DESC from ISSUES join (select distinct PROG_CODE, PROG_DESC from ISSREF) on ISSPROG = PROG_CODE where ISSDCLS > date '2017-01-01' and ISSDC in ('1', '3', '4') group by PROG_DESC
```

**Comment by gnakm** [comment]
@abbyraskin I wonder if we should make a separate issue for cleaning up program data and check-in with Lara since it effects hearings stuff as well.

**Comment by gnakm** [comment]
Closing because this has been combined with #2511
