### ISSUE TITLE
Document Viewer | Rotate page

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2522]
I want to rotate a document from the PDF viewer when a document was scanned upside down, so I can read it. 

## AC
- Selecting the rotate button turns the page 90 degrees clockwise
- Button is selectable from keyboard
- If I navigate away, the page remains rotated
- Button clicks are tracked as an event in Google Analytics
- Icon should be located right of fit to screen icon 
- Add a line divider between rotate and download icons
- [SVG icon here ](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Rotate.svg)

## Mockup 
![image](https://user-images.githubusercontent.com/13420618/27935661-70fb3ba6-627a-11e7-8928-24ff9365f0fa.png)

**Comment by abbyraskin** [comment]
Note: this may get moved into Milestone 2.

**Comment by astewarttistatech** [comment]
@abbyraskinUSDS While testing I opened up a new window for the doc while rotated and the new page opened up a doc that had been reset to its proper alignment. Didn't know if you guys wanted that or not. 

**PASSED**

Validated in Preprod
Browser: FF and Chrome 

Steps to Validate: 
1. Access Reader
2. Verify that the rotate button is on the appropriate tool bar. 
3. Verify that it can be clicked by mouse and has a resulting action (clockwise)
4. Verify that the button can be accessed via keyboard
5. Verify that each time the button is accessed a google analytics event occurs. 
6. Verify the line break between the rotate button and the download button is present 
7. Verify if something else on the page is accessed while the doc has been rotated, that the page is actually rotated. 

Screenshots:
