### ISSUE TITLE
Jump to comment | needs to scroll as pages are rendered

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2531]
Currently if you jump to a comment that is far down in the document, you lose your place as new pages above the comment are rendered. We need to keep your location as other pages are rendered.

# AC
1. Add a comment on a later page of a large document. Verify that when you jump to the comment from the list view, the scroll position doesn't shift while other pages are being loaded.
1. Scroll around in a large document. Verify that the scroll position doesn't shift while other pages are being loaded.

**Comment by kierachell** [comment]
## Not sure if this is intended....
- from Chrome
![weirdjump](https://user-images.githubusercontent.com/18075411/28180069-fa27ba1a-67d1-11e7-90dd-1229630da394.gif)

**Comment by astewarttistatech** [comment]
![jump_to_comments](https://user-images.githubusercontent.com/23038505/28180476-32c0a32c-67d3-11e7-8a46-f03ca2a894a3.gif)

**Comment by mdbenjam** [comment]
@kierachell what did you do to make that happen? Were you clicking any buttons offscreen?

**Comment by kierachell** [comment]
I did not touching anything extra.
- Add a comment to a 10+ page document on the last page
- Go to Document List
- Expand the comment section for that document
- Click jump to section
- Wait for the document to slowly load

NB:
- Maybe screen size affects the display - it seems like zoom level is not saved between views
- Rendering multiple pages on the screen (based on above) might still cause the view to scroll as one page loads and previous/next is not done.

**Comment by mdbenjam** [comment]
I was able to reproduce what you saw, and I think I fixed it.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF, Chrome, IE

Steps to Validate: 
1. Access a Reader session with multi-page documents
2. In the Document Lists section, locate a section that has comments
3. Use the "Jump to Section" button to verify that Reader will jump to the page where the comment is visible. 

Screenshots: 
![jumptosection](https://user-images.githubusercontent.com/23038505/28372191-03a8f096-6c6d-11e7-8c84-cd60678d7800.gif)
