### ISSUE TITLE
PDFJS Workers | Investigate why so many workers are created on each page switch

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2532]
PDFJS Worker threads seem to get cleaned up properly now, but you can create a lot of them by navigating between pages quickly. Investigate why we create so many.

**Comment by kierachell** [comment]
That was my bigger concern with the "memory leak" issue. It seemed like PDFjs was going nuts without getting cleaned up.

**Comment by kierachell** [comment]
FYI this is crashing my machine pretty regularly.
Chrome/IE
VM or not

**Comment by mdbenjam** [comment]
After our September refactor we properly clean up threads.
