### ISSUE TITLE
Document Viewer | Tabbing through Tag textbox creates last deleted tag

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow#2533]
# Description
When tabbing around the Viewer,
if I delete an Issue Tag,
then I tab around some more,
upon tabbing in and out of the Issue Tag textbox - it ends up creating last deleted Tag, instead of moving focus

## Reproduction Steps

**Scenario 1 -**

1. Go to Document Viewer
1. Create some Issue Tags
1. Delete them all
1. Focus elsewhere
1. Start tabbing into the Issue Tags textbox
1. Tab out of it
1. Can't - it makes an Issue Tag instead
1. Weird.

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Hard to tell because keyboard]_**
![weirdtag](https://user-images.githubusercontent.com/18075411/27807331-39690ac4-600e-11e7-97c2-3f80205abed2.gif)

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
