### ISSUE TITLE
Restyle 404 page

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#254]

**Comment by KHarshawat** [comment]
![404](https://cloud.githubusercontent.com/assets/6335546/11910021/743902e8-a5a3-11e5-8f52-6edcf644f046.png)

**Comment by webinista** [comment]
![screen shot 2015-12-23 at 11 24 25 am](https://cloud.githubusercontent.com/assets/354277/11980353/31a3eaf6-a968-11e5-94ea-8342e100a21c.png)
