### ISSUE TITLE
RecordNotUnique exception thrown for certification_cancellations

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#2542]
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_certification_...
```

Link to Sentry Logs:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/273/

**Comment by amprokop** [comment]
Searched Sentry. We haven't seen this since. It's possible that this is a bug where you can't cancel certifications twice, it would make perfect sense. Will look more into it if it ever happens again.
