### ISSUE TITLE
Analytics | Add document metadata to documents table

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2547]
We have the opportunity to learn a lot about what documents users find interesting. To that end Chris would like to do queries about document metadata. It'll be easiest if we store this information in our caseflow document database. We get all this information from eFolder express, now we just need to save it.

# AC
1. Verify we're storing doc type to documents table
1. Verify we're storing receipt date to documents table
1. Verify we're storing the case file number in the table

**Comment by kierachell** [comment]
**PASSED**

```
#<Document id: 21880, vbms_document_id: "{EC93DBA3-BF97-40A7-9BC9-D7D5333A70BD}", category_procedural: nil, category_medical: nil, category_other: nil, received_at: "2016-12-02", type: "other", file_number: "030103010">
```

**Comment by kierachell** [comment]
### Calling `appeal.documents` to trigger a VBMS request results in:
- This breaks Dispatch for me
```ActiveRecord::SubclassNotFound: Invalid single-table inheritance type: VA Memo is not a subclass of Document```
