### ISSUE TITLE
Analytics | Don't remove data

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2549]
We don't want to lose data. Currently if a user edits a comment, or deletes a tag, we don't have any record of that. We need to either make an audit log, or have some way of tracking changes.

**Comment by joofsh** [comment]
A couple thoughts:

If we are  interested in keeping deleted comments/tags, then we should consider implementing [soft deletes](https://github.com/rubysherpas/paranoia). This is a pretty commonly used pattern with several benefits (fixing human errors)

If we are interested in seeing edits (and tracking every change in a comment's text), then we'll need to setup a separate "audit table". This can be directly at the postgres DB level as a [trigger table](https://stackoverflow.com/questions/9547663/how-to-make-postgresql-insert-a-row-into-a-table-when-deleted-from-another-table), or could be manually accomplished from the application layer.

**Comment by abbyraskinUSDS** [comment]
Closing in favor of #2546
