### ISSUE TITLE
Make sure Form 8 Preview updates if you make edits

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#255]
We received the following feedback via Chris:

> Changes made to Form 8 do not show until the document has been uploaded

When asked when the feedback was collected:

> I got this feedback last Friday, April 22.  I think what the users were driving at was that after the Form 8 is generated, once they preview, if they make changes after that, they can’t see them until the upload it.

We should verify that the Form 8 Preview does in fact update if the user goes back and makes changes.

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached. 
![Uploading Screen Shot 2016-12-14 at 12.31.21 PM.png…]()
<img width="1147" alt="screen shot 2016-12-14 at 12 31 50 pm" src="https://cloud.githubusercontent.com/assets/23038505/21194007/5008d4b8-c1fc-11e6-9a2a-af4901bc6a48.png">

Moving this issue to closed.
