### ISSUE TITLE
Reader Help | FAQs | Update question/answer

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2552]
As a Product Owner, I would like the copy for all sections on the Help page to be updated which includes new content for FAQs and answers so that they reflect the most recent information.  

**_Note:  Several questions and answers have changed as well as order._**

## Acceptance Criteria
1. Verify that Header copy "Caseflow Reader Help" is changed to "Welcome to the Reader Help Page!".
1. Verify that in the "Welcome to the Reader Help Page!" section, the copy text wraps so that it is only on two lines (note:  "possible. " on 3rd line). (refer to Mock **_eFolder Express Help Page Example_**).
1. Verify that in the "Training Videos" section, the copy "Coming Soon" has been changed to "Coming Soon!".
1. Verify in the "Frequently Asked Questions" section, it contains the newly updated listing of all questions. (Refer to [Reader FAQs_Aug2017](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_FAQs_Aug2017.pdf))  
1. Verify that in the "FAQ Answers" section, it contains all newly updated questions and their answer.  (Refer to [Reader FAQs_Aug2017](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_FAQs_Aug2017.pdf)) 
1. Verify that each question in the FAQs section is a hyperlink to its answer. 

## Mocks
**_eFolder Express Help Page Example_**
![image](https://user-images.githubusercontent.com/23063044/28734924-1a5d52d2-73b1-11e7-8593-90c25ccb0301.png)

**_Current Reader Help Page - update FAQs section_**
![reader_faqs](https://user-images.githubusercontent.com/23361723/28689894-42e1c23c-72e5-11e7-8b5d-16f44f08a52d.png)

# Related Story
Reader | FAQs | Update Questions - Pilot Deliverable [#330](https://github.com/department-of-veterans-affairs/appeals-training/issues/33)

**Comment by nikitarockz** [comment]
Abbey's Original comments:
We're working on updating the content for the FAQs, ahead of the next release.  The format of the page should remain the same; only the copy is changing.

See updated content below (forthcoming):

**Comment by wturne** [comment]
@nikitarockz, FAQs have been updated and saved to PDF. They are stored in the Training Repo as Reader FAQs_Aug2017.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Reader Help page, and compare it to eFolder Help page

Screenshots: 
Efolder: 

![efolderhelp](https://user-images.githubusercontent.com/23038505/29078558-bae9d782-7c28-11e7-933c-f33b70de0650.png)

Reader:
![readerhelp](https://user-images.githubusercontent.com/23038505/29078573-c59a9716-7c28-11e7-83b1-b6e1579d50da.png)
