### ISSUE TITLE
Update Hearing Prep landing page copy to be 'Upcoming Hearing Days'

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2553]
As a Judge, I would like the hearing prep landing page to be called 'Upcoming Hearing Days' instead of 'Hearing Schedule', so that I do not confuse it with Caseflow Hearing Schedule (to be built).

Acceptance Criteria for `demo`:
- Visit `/test/users`
- Make yourself as `Hearings` user
- Visit `Hearings Prep`
- Title of page reads 'Upcoming Hearing Days'
- Breadcrumbs read ' Upcoming Hearing Days'

Mocks:
<img width="1015" alt="screen shot 2017-07-06 at 8 38 48 pm" src="https://user-images.githubusercontent.com/18075411/27938313-2d6c059e-628b-11e7-876b-81a193a95f8b.png">

**Comment by kierachell** [comment]
**PASSED**
works in UAT!
<img width="507" alt="screen shot 2017-07-07 at 8 35 19 pm" src="https://user-images.githubusercontent.com/18075411/27981064-26b91e98-6354-11e7-9ed5-32a402b3f68a.png">
<img width="207" alt="screen shot 2017-07-07 at 8 36 07 pm" src="https://user-images.githubusercontent.com/18075411/27981065-26bad3d2-6354-11e7-819a-b1be2d86e7e5.png">
