### ISSUE TITLE
On all screens, we should have some escape hatch / abort

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#256]
In the case we've done something wrong - including Form 8 preview, we need an escape hatch to back out the certification and reset the case.

This is pretty high urgency, it's happening a lot.

**Comment by paultag** [comment]
Does `WebController::error` DTRT here, or do we just reset `bf41stat` ?

**Comment by paultag** [comment]
e.g. do we need to reset `bfdmcon` and `bfms`, or just `bf41stat`?

**Comment by KHarshawat** [comment]
@webinista Here are mocks for the escape hatch (can't certify) on Questions page and Preview Form 8 page.

We will have to come up with a better followup page/modal when a user clicks on that button but that is a lower priority and in #192 

![preview form 8](https://cloud.githubusercontent.com/assets/6335546/11564624/36ec70f2-99a8-11e5-93a4-7351226dee9c.png)
![questions page](https://cloud.githubusercontent.com/assets/6335546/11564625/36f1da9c-99a8-11e5-9377-e1e615bf8a1b.png)

**Comment by KHarshawat** [comment]
Here's what should happen when you click that button:

- User see's a confirmation page that explains what happened
- We reset the Cert Date in VACOLS to none (un-certify the appeal)
- Append the appeal ID in a secure spreadsheet (eventually a DB) so we can see what happened.

@webinista you should work w/ @paultag or @plusjeff to make sure these things happen.

**Comment by paultag** [comment]
Punting on logging - I can grep server logs for the time being until we get graphite

**Comment by maryannbrody** [comment]
Hi, 

Here's content for the final cancel certification page:


**This case was not certified.**
Certification date was not set and any changes you made were not saved in Caseflow. 

You can go ahead and close this page and open another case in VACOLS.

**Comment by plusjeff** [comment]
@KHarshawat Confirming that go back color is `#494E58` (Generic RGB)

**Comment by paultag** [comment]
@plusjeff `usa-button-grey` for the button!

**Comment by plusjeff** [comment]
@maryannbrody Are you OK with this revision to the not certified text (just nitpick tweaks to remove redundancies)?

**This case was not certified**
Certification date was not set and any changes you made were not saved ~~in Caseflow~~.

You can ~~go ahead and~~ close this page and open another case in VACOLS.

**Comment by plusjeff** [comment]
@paultag @KHarshawat : Let me know what you think, but here are my thoughts on secure spreadsheet requirement...

When a user clicks "Can't certify", we set the following `brieff` fields:

- `bf41stat` to null
- `bfms` to null
- `bfmcon` to null

What if we also did this:

- `bfdcertool` to (datetime clicked)

This would indicate that Caseflow was used for a case, but not certified. We'd be able to detect cases that couldn't be certified via Caseflow with the following query:

`SELECT bfkey, bfcorlid FROM brieff WHERE bf41stat IS NULL and bfdcertool IS NOT NULL`

This seems to capture the spirit of the spreadsheet without having to have an actual spreadsheet generated, or any new database fields created.

Let me know your thoughts/concerns with this possible approach.

**Comment by paultag** [comment]
@plusjeff The only catch to that is that when they certify it by hand later (because of a caseflow error) it'll look like it worked fine -- I wonder if we can flag it as caseflow errored (I wish we had a db :\)

**Comment by plusjeff** [comment]
@paultag Good insight. I'm wondering: What is the underlying need? 

- Is it to have us notified when Caseflow seems to not be working?
- Is it to make sure veterans don't slip through the cracks?
- (Something else I'm not thinking of?)

**Comment by paultag** [comment]
Good questions; I'm not sure what the end goal is either -- @KHarshawat ?

**Comment by KHarshawat** [comment]
The goal of creating the secure spreadsheet was to be able to log and detect cases where Caseflow did not work. Eventually, we'll want to report these cases that could not be certified (along with more details about why the could not) to the appropriate party in VBA so they can handle it.

For next week, Paul has actually created a hacky way to look at the logs and see when a user hits this page and we can manually check in on these so I don't think the spreadsheet is needed.

We **should not** make it look like the case was certified when  they were not. This will be confusing to all parties involved.

**Comment by plusjeff** [comment]
Yay! Glad this is closed. This issued raised a question for me, so I created a question ticket #283 .
