### ISSUE TITLE
Analytics | Record search values

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#2561]
As a designer, I want to be able to see all of the things our attorneys are searching so I can make good design decisions :1st_place_medal:.

## Acceptance Criteria
- When I enter a value into the search bar on the Document list page, and either:
    - Wait 0.5 seconds
    - Unfocus the search element
- The value that I entered into the search bar should be saved to the Caseflow database.

## Notes
There is no way to see the searches on the front end (yet?). For now, we will only be able to read the values by querying the database.

**Comment by kierachell** [comment]
**PASSED**
<img width="531" alt="screen shot 2017-07-25 at 3 23 12 pm" src="https://user-images.githubusercontent.com/18075411/28589733-51619560-714d-11e7-9c98-695fdda9ecec.png">

```
ClaimsFolderSearch Load (1.8ms)  SELECT  "claims_folder_searches".* FROM "claims_folder_searches"  ORDER BY "claims_folder_searches"."id" DESC LIMIT 1
[2017-07-25 15:23:25 -0400]   ClaimsFolderSearch Load (1.8ms)  SELECT  "claims_folder_searches".* FROM "claims_folder_searches"  ORDER BY "claims_folder_searches"."id" DESC LIMIT 1
=> "sup"
```
