### ISSUE TITLE
Google Analytics for Certification

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2563]
Enable google analytics for events in Caseflow Certification so we can track user behavior. 

We want to be able to answer questions like:
- How long are RO staff spending one each page? 
- What % of appeals started in Certification aren't finished in the same session?
- Do all users make it through all of Certification? On what pages do they drop off?

## Acceptance Criteria
- Track event for the Check Documents page
- Track event for the Confirm Case Details page
- Track event for the Confirm Hearing page
- Track event for Sign & Certify page
- Track event for the Success page

**Comment by shellicious** [comment]
this looks good to me!

**Comment by kierachell** [comment]
- Where do I see this?
- Is there a GA account? Where do I find it?
- How do the metrics appear in GA?
- Is this actually connected to UAT?

**Comment by shanear** [comment]
<img width="691" alt="screen shot 2017-07-19 at 11 28 14 am" src="https://user-images.githubusercontent.com/1596259/28375497-a3cf9f0e-6c75-11e7-86ee-bfd7ef4aeccc.png">
@shellicious this look good to you? also we should be getting a flow chart soon. I had to make a small tweak

**Comment by shanear** [comment]
Validated in prod by @shellicious. Moving header analytics to a different story.
