### ISSUE TITLE
PropType violations are creating lots of log output from React unit tests

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2571]
As noted [here](https://github.com/department-of-veterans-affairs/caseflow/pull/2564#discussion_r126552575), we need to make sure the contracts in our React components are correct and engaged correctly.

The execution of `npm run test` yields lots of log output complaining about these violations.

**Comment by nolawi** [comment]
Could not reproduce and log outputs with `oneOfType`?

**Comment by kierachell** [comment]
**PASSED**

ran tests

didn't see it


maybe bad tests.
