### ISSUE TITLE
Reader feature test scenario "Open a document and return to list" failing in Jenkins env

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2576]
Fix the [Reader feature test](spec/feature/reader_spec.rb#809) for the scenario "Open a document and return to list". It is consistently failing in our new [Jenkins env](https://a54c945d65e0311e7843f0206c2f3847-1313167371.us-gov-west-1.elb.amazonaws.com) and randomly in the TravisCi environment:

```
Reader Large number of documents Open a document and return to list
     Failure/Error: expect(in_viewport("read-indicator")).to be true
       expected true
            got false
     # ./spec/feature/reader_spec.rb:819:in `block (3 levels) in <top (required)>'
```

This may be due Selenium moving too fast or our headless testing setup is missing additional configuration.

You can use the docker-compose environment committed with #2448 to debug.

**Comment by mogrenAtWork** [comment]
Running the tests again now to reproduce the error message and will add it to the ticket.

**Comment by mogrenAtWork** [comment]
@mmlumba had a good thought that this might be related to #2441 as our Xvfb server runs at 1024x768

**Comment by mdbenjam** [comment]
@mogrenAtWork Is this still an issue?

**Comment by mogrenAtWork** [comment]
Nope, looks like it's fixed, closing
