### ISSUE TITLE
Auto-focus on VACOLS login name

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#258]
When logging into VACOLS, we should auto-focus on the RO name field

**Comment by plusjeff** [comment]
This appears to already work in IE11 and Chrome via the autofocus attribute. Could someone add more detail?

**Comment by paultag** [comment]
Closing notabug; user must have not focused on the browser

**Comment by plusjeff** [comment]
Confirmed with team. Not an issue.
