### ISSUE TITLE
Remove 'Other' radio button from being selected by default on Sign & Certify page

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2583]
As a user, I do not want any title to be selected by default in the 'Title of certifying official' section of the Sign & Certify page, so that I can select my title myself.

Acceptance Criteria:
- No radio button is selected under 'Title of certifying official' when the user navigates to the Sign & Certify page.

**Comment by kierachell** [comment]
**PASSED**

Validated while checking other issue that was blocking Certification
