### ISSUE TITLE
ARC Work Assignments | Table columns shift when editing quotas

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2586]
# Description
When managing team/user quotas on the ARC Work Assignments page,
then table headers/columns/rows move around and it looks fugly.

## Reproduction Steps

**Scenario 1 -**

1. Go to Dispatch Manager page
1. Edit quotas
1. See table shift around
1. Be sad
1. Compare this to VBMS....

**Validated in the following Environment(s)**
- [ ] Dev
- [x] UAT
- [x] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Yeah]_**

![shiftinsands](https://user-images.githubusercontent.com/18075411/28114765-395b49fc-66d0-11e7-8a03-90d666e9779a.gif)

**Comment by nolawi** [comment]
@kierachell what is the route/url for `Dispatch Manager page` is it team/user ?

**Comment by kierachell** [comment]
I wish I knew anymore... Apparently it moved to
`/dispatch/work-assignments` based on:
https://github.com/department-of-veterans-affairs/caseflow/pull/2637

**Comment by kierachell** [comment]
### The columns still move about :(
![tableshit](https://user-images.githubusercontent.com/18075411/28589937-3efc56e8-714e-11e7-85f2-f71f9d4addf5.gif)

**Comment by nolawi** [comment]
oh ok will fix @kierachell

**Comment by kierachell** [comment]
**PASSED**

GLORIOUS!
![awdamnlookatdat](https://user-images.githubusercontent.com/18075411/28648053-072a49c8-7239-11e7-9031-3172204990c9.gif)
