### ISSUE TITLE
[Backend] Update `upcoming_for_judge` VACOLS query

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2590]
Currently we are looking up the judge's hearings by using the attyid (attorney id). Instead we should change this query to look the hearings up using the judge's `css_id` (instead of the current `staff.stafkey` matches the user's `vacols_id` in the caseflow DB). This also makes the User's `vacols_id` column unnecessary in the Caseflow DB, and it should be removed.

##Acceptance Criteria
- Update `VACOLS::CaseHearing.upcoming_for_judge` query to compare that `staff.sdomainid` is equal to their `css_id`. See a current example [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/vacols/case_assignment.rb#L10-L12)
- Remove the caseflow DB's user's `vacol_id` column & all references to it

### Steps

- SSH into a UAT instance of Caseflow
- Using the appeals-qa LOGINS.md, find a user with designation Judge and/or Attorney
- Using the Test User ID (aka CSS ID) call `VACOLS::CaseHearing.upcoming_for_judge(css_id: "<TEST USER ID HERE WITHOUT THE POINTY BRACKETS... JUST IN QUOTES; I PUT BRACKETS JUST TO INDICATE THAT THIS IS WHERE YOU WRITE DIFFERENT THINGS;>"
- Verify that for Test User IDs designated as Judge there is a non-nil result (with no errors). Preferably an array of `Hearings` should come back
- Verify that Test User IDs designated as Attorneys do not return hearings
- Verify that shit doesn't explode when `nil` is passed, and is case-insensitive
- Verify that Test User IDs that are not Attorneys or Judges return nil
- Verify that there is no `User`-s in the database that have `vacols_id` attribute.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT (console)

Steps to Validate: 
1. Open Rails console for the UAT environment 
2. Run the VACOLS::CaseHearing.upcoming_for_judge query with the css_ids we have for Hearing prep. 
3. Validate that hearings do return as a result of the query. 

Screenshots: 
CF_SCOTTY_398
<img width="1432" alt="screen shot 2017-08-17 at 9 05 51 am" src="https://user-images.githubusercontent.com/23038505/29413845-d282fc2a-832b-11e7-800e-cc5413100924.png">
