### ISSUE TITLE
Welcome Gate | Show AOD and CAVC

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2593]
## Description
Users have given us feedback that it would be helpful to see AOD and CAVC at a glance from the landing page. It will help users prioritize their reviews. 

## AC 
Reuses work from #1998
  - If the case is AOD, show the word AOD in `$color-secondary` in a second line under Veteran's name. 
  - If the case is CAVC, show the word CAVC in `$color-secondary` in a second line under Veteran's name. 
  - If the case is both AOD or CAVC, show the words AOD, CAVC (note comma in between) in `$color-secondary` in a second line under Veteran's name. 
  - See [colors for style guide](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#colors) if needed here

## Mock up

![image](https://user-images.githubusercontent.com/13420618/28286213-6f448630-6b05-11e7-8926-0d5f8bc4eb11.png)

**_NOTE -- The comma should be red between AOD and CAVC._**

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/1998

**Comment by abbyraskin** [comment]
- still needs notes about accessibility

**Comment by gnakm** [comment]
@tejans24 We made edits here. Both AOD and CAVC is in red. Could you add the data that Chris shared with us in the AC above?

**Comment by abbyraskin** [comment]
AOD is determined by "Type Action" field (if the value is 7).

AOD is a bit more complicated, pasting Chris' info here for now:

There are two ways that an appeal can be marked as AOD, either by the AOD office, or by a judge during a hearing. If the former, we'll look for a diary marking it as AOD in the `ASSIGN` table. If the latter, we'll look for a hearing where AOD was granted in the `HEARSCHED` table. We sum up the number of matching rows, and if there's more than one, we know it's an AOD appeal. Here's an example query.

```select
  BRIEFF.BFKEY,
  (case when (nvl(AOD_DIARIES.CNT, 0) + nvl(AOD_HEARINGS.CNT, 0)) > 0 then 1 else 0 end) AOD

from BRIEFF

left join (
    select TSKTKNM, count(*) CNT
    from ASSIGN
    where TSKACTCD in ('B', 'B1', 'B2')
    group by TSKTKNM
  ) AOD_DIARIES
  on AOD_DIARIES.TSKTKNM = BRIEFF.BFKEY

left join (
    select FOLDER_NR, count(*) CNT
    from HEARSCHED
    where HEARING_TYPE in ('C', 'T', 'V')
      and AOD in ('G', 'Y')
    group by FOLDER_NR
  ) AOD_HEARINGS
  on AOD_HEARINGS.FOLDER_NR = BRIEFF.BFKEY```

**Comment by NickHeiner** [comment]
![image](https://user-images.githubusercontent.com/829827/28722619-5d1ba346-7382-11e7-9011-716331bbcf0e.png)

Is it intentional that the comma is not red?

**Comment by gnakm** [comment]
Sorry that was a mockup typo -- Can we make it red?

**Comment by kierachell** [comment]
**PASSED**

I need a quick win today pls... :headhurts:
<img width="536" alt="screen shot 2017-08-01 at 4 22 30 pm" src="https://user-images.githubusercontent.com/18075411/28845337-acb0f3a6-76d5-11e7-85b7-87b758df2a19.png">
