### ISSUE TITLE
Unify application.html.erb templates

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2606]
Tango team diverged application templates between hearing prep and the previous apps. 
Keeping these two templates in parallel has created confusion & churn as changes are made to them.

Acceptance Criteria:
- Unify the templates such that only 1 is used across all products
- Ensure the template is still able to support narrow & wide viewpoints

**Comment by kierachell** [comment]
**PASSED**
![hearrrr](https://user-images.githubusercontent.com/18075411/28376460-29a23d4c-6c78-11e7-8f5b-3d03753f5f07.gif)
![readerddd](https://user-images.githubusercontent.com/18075411/28376458-298a35a8-6c78-11e7-8608-4388d2aaa49a.gif)
![screenshot_2017-07-19_11-47-03](https://user-images.githubusercontent.com/18075411/28376457-29895ca0-6c78-11e7-8757-238a069eabfd.png)
![screenshot_2017-07-19_11-48-02](https://user-images.githubusercontent.com/18075411/28376459-298c34f2-6c78-11e7-8ad1-ef720bcff073.png)
