### ISSUE TITLE
Welcome Gate | Add a "due date" column

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2607]
## Story
When opening Reader, I want to know case due dates at a glance, so I can prioritize my work assignments.

## Acceptance Criteria
- Gate includes a due date column, using due dates from DAS (DD/MM/YYYY)
- Cases appear in the order in which they are due - cases that are due soonest are at the top

## Mocks
![image](https://user-images.githubusercontent.com/13420618/28136085-78302508-6716-11e7-86a9-1057b3d011d3.png)

**Comment by abbyraskin** [comment]
@gnakm @mdbenjam hmmm - will judges see this column? will it always be blank for them?

**Comment by abbyraskin** [comment]
er, never mind. it would just show the date it's due for the assigned attorney.

**Comment by abbyraskin** [comment]
(I believe due dates are assigned at the time a judge checks a case in to their attorney, so I don't think they'd ever see one...)

**Comment by gnakm** [comment]
@abbyraskin Can we run this by a judge over lync? My guess was that they wouldn't see it.

**Comment by abbyraskin** [comment]
> Usually, no, HOWEVER cases that are advanced on the docket come to us with a “suggested” due date, if you will, and cases that come to us after CAVC action we are supposed to process (assign) within 30 days.  So while a due date column wouldn’t be helpful, a column showing the date was charged to us would be!!

I suggest we hold off on implementing this until we can make it meaningful for both VLJs and attorneys.

**Comment by abbyraskinUSDS** [comment]
@gnakm I think we should close this out in favor of future work queue. thoughts?

**Comment by abbyraskinUSDS** [comment]
This is a scenario the Queue team will address. Out of scope for Reader - closing.
