### ISSUE TITLE
Welcome Gate | Issues alignment

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2617]
## Description
Left-aligning the header "Issues" with the issues descriptions (not numbers) is clearer to read and balances unnecessary white space.

## AC
- [ ] Left-aligning the header "Issues" with the issues descriptions (not numbers) text.

## Mock ups

![image](https://user-images.githubusercontent.com/13420618/28226042-a91937a8-68a2-11e7-9c57-1dad168e14ed.png)

![image](https://user-images.githubusercontent.com/13420618/28226053-b5ac630a-68a2-11e7-9921-d169158bf287.png)

**_Note: See more link is out of scope for this issue_**

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2511

**Comment by kierachell** [comment]
**PASSED**
<img width="449" alt="screen shot 2017-07-18 at 10 42 47 am" src="https://user-images.githubusercontent.com/18075411/28323104-db8fe9d8-6ba5-11e7-81e6-c137c9613f1e.png">
