### ISSUE TITLE
Welcome Gate | Loading indicator

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#2618]
**Story**
As a user, I want to know when my checked in cases are still loading, so I don't think my list is blank.

## AC 
- Add loader (4 pt stars) to Welcome Gate page with [reader green from style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#loaders)
- Copy underneath the loader is "Loading cases in Reader..."
-  Loader should appear below the header, similar to this (but different copy):
 ![image](https://cloud.githubusercontent.com/assets/13420618/25966796/127a26ec-365a-11e7-892b-233833512e97.png)

**Comment by kierachell** [comment]
**PASSED**
HOLYSHIT FINALLY
![fuckyeah](https://user-images.githubusercontent.com/18075411/28718159-bc881bb2-7372-11e7-82c9-fd6d73086114.gif)
