### ISSUE TITLE
[V2] Feature Flag | Enable District ROs - Southeast (7/28/2017)

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#2620]
As Product Owner, I would like the following ROs to have the Certification v2 feature flag enabled on Friday, 7/28/2017 so that the users in the Southeast District can begin using Certification v2.

### ROs
District|BFREGOFF|Name
---|---|---
Southeast|RO17|St. Petersburg, FL
Southeast|RO16|Atlanta, GA
Southeast|RO22|Montgomery, AL
Southeast|RO55|San Juan, PR
Southeast|RO19|Columbia, SC
Southeast|RO20|Nashville, TN
Southeast|RO27|Louisville, KY

**_Total ROs:  7_**

# Acceptance Criteria
1.	Verify that the feature flag has been turned on for all ROs mentioned above.

# Related Stories
IP | Certification v2 | Request feature flag enabled [#1450](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1450)

**Comment by nikitarockz** [comment]
@nemodjuric Do you need Station number?

**Comment by nemodjuric** [comment]
No station number is necessary, @nikitarockz 
ROs have been added.
