### ISSUE TITLE
[Friday 7/21] Preventing bad writes to VACOLS

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2621]
We've had a couple of instances of writing bad data to VACOLS. We want to discuss team norms to minimize the chances of this happening. After our first incident we had originally updated our team norms to require two reviews on every write to an external system, but maybe this is not enough. What else should we do to prevent this from happening?

**Comment by kierachell** [comment]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/2580

**Comment by mdbenjam** [comment]
1. Create audit table for VACOLS writes (https://github.com/department-of-veterans-affairs/caseflow/issues/2681)
1. Use copy of VACOLS in RDS to dev (https://github.com/department-of-veterans-affairs/caseflow/issues/2680)
