### ISSUE TITLE
Hearings | How is a user getting a "vacols_id"?

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#2627]
**Description:**
Currently, when a user tries to access Hearings when the feature is toggled on and the function is enabled, if the css_id being used doesn't have a "vacols_id" (nil) then they will receive a 404 error and a "Page Not Found" page. This results in the hardcoding of a "vacols_id". 

**Expected:**
unknown

**Steps to Recreate:**
1. Log into the Caseflow app with "CASEFLOW1" css id. 
2. Enable "Hearings" as a function
3. Toggle on the "Hearings" feature
4. Go to /hearings/dockets
5. Verify that there is a 404 error and a "Page Not Found" page. 
6. Access the rails console for UAT
7. Find the details for "CASEFLOW1" css id. 
8. Verify that there is no value associated with the "vacols_id".

**Screenshots:**
<img width="560" alt="screen shot 2017-07-17 at 11 12 33 am" src="https://user-images.githubusercontent.com/23038505/28275625-737a561c-6ae2-11e7-81bd-ba5ee956792a.png">
<img width="1131" alt="screen shot 2017-07-17 at 11 13 01 am" src="https://user-images.githubusercontent.com/23038505/28275626-737be3f6-6ae2-11e7-974b-df07248ca12d.png">

After being hardcoded:
<img width="652" alt="screen shot 2017-07-17 at 11 33 43 am" src="https://user-images.githubusercontent.com/23038505/28276191-262510bc-6ae4-11e7-91d7-5d6910340fa5.png">
<img width="1110" alt="screen shot 2017-07-17 at 11 34 32 am" src="https://user-images.githubusercontent.com/23038505/28276192-26268eec-6ae4-11e7-8d35-faeb24f8a908.png">

**Comment by slj** [comment]
The completion of https://github.com/department-of-veterans-affairs/caseflow/issues/2590 may solve this issue.

**Comment by joofsh** [comment]
As @slj mentioned, this is being changed so that we no longer need to set a user's vacols_id. Will close
