### ISSUE TITLE
Welcome Gate | Update query to include cases assigned to judges

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2628]
Currently, the Welcome Gate only works for attorneys since we only use the DECASS table to query from in app/models/vacols/case_assignment.rb. We'd like to include all cases assigned to judges as well. None of the judges' cases have the sdomainid = css_id of the judge.

We'll need to figure out the correct query to pull the judges' cases in as well.

# AC
- Cases displayed on welcome gate include all cases assigned for all users (attorneys and judges)
    - Judges can be found be querying for users where `STAFF.SVLJ = 'J'`

**Comment by joofsh** [comment]
Hey, it look like this might relate to a hearing prep ticket https://github.com/department-of-veterans-affairs/caseflow/issues/2590 . We were going to change our setup to mimic Reader. Is this not valid for Judges? If so, can you update that ticket with what you've learned?

**Comment by mogrenAtWork** [comment]
@joofsh 
A case is usually not "assigned" to a judge, instead it remains assigned to an attorney and the `BRIEFF.BFCURLOC` column is updated with the judge's `css_id` when it is checked out to a judge.

Our original query included a join on the DECASS table where `STAFF.SATTYID = DECASS.DEATTY`, which limited the results to only attorneys since `DECASS.DEATTY` was going to remain the attorney's `css_id` of which it was assigned to:
```
SELECT defolder as vacols_id, 
    deassign as date_assigned, 
    dereceive as date_received, 
    staff.slogid as vacols_user_id, 
    brieff.bfddec as signed_date, 
    brieff.bfcorlid as vbms_id, 
    corres.snamef as veteran_first_name, 
    corres.snamemi as veteran_middle_initial,
    corres.snamel as veteran_last_name 
FROM "VACOLS"."DECASS" 
    INNER JOIN "VACOLS"."STAFF" ON "VACOLS"."STAFF"."SATTYID" = "VACOLS"."DECASS"."DEATTY" 
    INNER JOIN "VACOLS"."BRIEFF" ON "VACOLS"."BRIEFF"."BFKEY" = "VACOLS"."DECASS"."DEFOLDER" 
    INNER JOIN "VACOLS"."BRIEFF" "CASES_VACOLS_DECASS_JOIN" ON "CASES_VACOLS_DECASS_JOIN"."BFKEY" = "VACOLS"."DECASS"."DEFOLDER" 
    INNER JOIN "VACOLS"."CORRES" ON "VACOLS"."CORRES"."STAFKEY" = "CASES_VACOLS_DECASS_JOIN"."BFCORKEY" 
WHERE (staff.sdomainid = <css_id> and brieff.bfcurloc = staff.slogid)
```

To fix this, we replaced that join with the where clause criteria, `brieff.bfcurloc = staff.slogid`:
```
SELECT defolder as vacols_id, 
    deassign as date_assigned, 
    dereceive as date_received, 
    staff.slogid as vacols_user_id, 
    brieff.bfddec as signed_date, 
    brieff.bfcorlid as vbms_id, 
    corres.snamef as veteran_first_name, 
    corres.snamemi as veteran_middle_initial, 
    corres.snamel as veteran_last_name 
from BRIEFF
    inner join DECASS on BRIEFF.BFKEY=DECASS.DEFOLDER
    inner join STAFF on STAFF.SLOGID=BRIEFF.BFCURLOC
    inner join CORRES on BRIEFF.BFCORKEY=CORRES.STAFKEY
where staff.sdomainid = <css_id>
```

**Comment by kierachell** [comment]
It's  working!:

Attorney:
![screenshot_2017-07-19_11-21-04](https://user-images.githubusercontent.com/18075411/28375024-67011a90-6c74-11e7-9a53-da163d818c99.png)
Judge:
![screenshot_2017-07-19_11-27-48](https://user-images.githubusercontent.com/18075411/28375370-50a29188-6c75-11e7-9338-7eee67e37126.png)
