### ISSUE TITLE
Hearings | Selecting a date from the "Dockets" page re-routes, adding an extra "/dockets" to the URL

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#2629]
**Description:**
Currently, if on the /hearings/dockets page and a hyer-linked date is selected, when the page routes to the Daily Docket page the URL has an extra "/dockets" added, resulting in a blank page

**Expected:** 
URL should be /hearings/dockets/YYYY-MM-DD instead of /hearings/dockets/dockets/YYYY-MM-DD

**Steps to Recreate:**
1. Log into the Caseflow app with a user who has access to Hearings
2. Enable the "Hearings" function 
3. Toggle on the "Hearings" feature
4. Access the url /hearings/dockets
5. Select one of the hyper-linked dates for dockets
6. Verify that routing of the hyperlink takes you to a Caseflow Hearings page, but the content is blank.

**Screenshots:** 
![docket](https://user-images.githubusercontent.com/23038505/28278637-c21a95d0-6aeb-11e7-9ae0-72fc1cc2a7e3.gif)

**Comment by joofsh** [comment]
@astewarttistatech can you take a look at this again? It appears to be resolved

**Comment by kierachell** [comment]
**PASSED**
<img width="606" alt="screen shot 2017-08-04 at 9 25 20 am" src="https://user-images.githubusercontent.com/18075411/28970534-e4dae552-78f6-11e7-85af-85aa07c16eec.png">
<img width="921" alt="screen shot 2017-08-04 at 9 25 34 am" src="https://user-images.githubusercontent.com/18075411/28970535-e4de5e6c-78f6-11e7-89f5-364a7c622334.png">
