### ISSUE TITLE
Add in implicit form 8 fields as editable with the ones we show

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#263]
That are auto-populated with the information we grab, also allowing them to be editable

**Comment by paultag** [comment]
Full list of magic fields at this moment:

Seen at: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/case.rb#L20-L54

```
    fields = {
      '1A_NAME_OF_APPELLANT' => kase.correspondent.appellant_name,
      '1B_RELATIONSHIP_TO_VETERAN' => kase.correspondent.appellant_relationship,
      '2_FILE_NO' => kase.bfcorlid,
      '3_LAST_NAME_FIRST_NAME_MIDDLE_NAME_OF_VETERAN' => kase.correspondent.full_name,
      '4_INSURANCE_FILE_NO_OR_LOAN_NO' => kase.bfpdnum,
      '5A_SERVICE_CONNECTION_FOR' => Caseflow.format_issues(kase, 'service connection'),
      '6A_INCREASED_RATING_FOR' => Caseflow.format_issues(kase, 'increased rating'),
      '7A_OTHER' => Caseflow.format_issues(kase, 'other'),
      '8A_APPELLANT_REPRESENTED_IN_THIS_APPEAL_BY' => kase.vso_full,
      '8B_POWER_OF_ATTORNEY' => '',
      '9A_IF_REPRESENTATIVE_IS_SERVICE_ORGANIZATION_IS_VA_FORM_646_YES' => '',
      '9A_IF_REPRESENTATIVE_IS_SERVICE_ORGANIZATION_IS_VA_FORM_646_NO' => '',
      '10A_WAS_HEARING_REQUESTED_YES' => kase.hearing_requested?,
      '10A_WAS_HEARING_REQUESTED_NO' => !kase.hearing_requested?,
      '12A_DATE_STATEMENT_OF_THE_CASE_FURNISHED' => kase.bfdsoc_date,
      '12B_SUPPLEMENTAL_STATEMENT_OF_THE_CASE_REQUIRED_AND_FURNISHED' => kase.ssoc_required?,
      '12B_SUPPLEMENTAL_STATEMENT_OF_THE_CASE_NOT_REQUIRED' => !kase.ssoc_required?,
      '15_NAME_AND_LOCATION_OF_CERTIFYING_OFFICE' => kase.regional_office_full,
      '16_ORGANIZATIONAL_ELEMENT_CERTIFIYING_APPEAL' => kase.bfregoff
    }

    if fields['5A_SERVICE_CONNECTION_FOR'].present?
      fields['5B_DATE_OF_NOTIFICATION_OF_ACTION_APPEALED'] = kase.bfd19_date
    end
    if fields['6A_INCREASED_RATING_FOR'].present?
      fields['6B_DATE_OF_NOTIFICATION_OF_ACTION_APPEALED'] = kase.bfd19_date
    end
    if fields['7A_OTHER'].present?
      fields['7B_DATE_OF_NOTIFICATION_OF_ACTION_APPEALED'] = kase.bfd19_date
    end
```

**Comment by webinista** [comment]
:+1: thanks @paultag I was just about to ask you for those.

**Comment by paultag** [comment]
:us:

**Comment by KHarshawat** [comment]
@webinista we've created a mock including all the fields on the questions page. I've included some guidance for you in red text:

- Areas that need to be pre-filled and the data they should be pre-filled from
- Situations where questions are dependent on others (useful for future show/hide/disable logic)
- note there are N/A radio button options on some questions (those that are dependent on previous answers)
- Updated required question stars

LMK if you need anything else!

![questions_revised](https://cloud.githubusercontent.com/assets/6335546/11568514/8f19dd2a-99ba-11e5-9877-ea679ea32b2a.png)

**Comment by KHarshawat** [comment]
Corrections:

8B is *NOT* required
9A is *NOT* required
added a new question: 10C

**Comment by webinista** [comment]
I'm getting an error when I try to use `kase.bfdrodec`, should it be `kase.bfd19_date`?

**Comment by webinista** [comment]
@KHarshawat 10C is already part of the form. Should it remain a text field, or become a `textarea`?

**Comment by KHarshawat** [comment]
@webinista @paultag is looking into your kase.bfdrodec issue. 

We should use textarea for 10c. Thanks!

**Comment by paultag** [comment]
@webinista added bfdrodec in https://github.com/department-of-veterans-affairs/caseflow/pull/279

**Comment by webinista** [comment]
What happens when the user clicks the `Can't certify` button / link?

**Comment by paultag** [comment]
@webinista We should send them to the `#error` view, which will blank out the case and say that it went south -- #256 might be related

**Comment by webinista** [comment]
@paultag Not seeing data for the following:

`'5A_SERVICE_CONNECTION_FOR' => Caseflow.format_issues(kase, 'service connection'),`
`'6A_INCREASED_RATING_FOR' => Caseflow.format_issues(kase, 'increased rating'),`
`'7A_OTHER' => Caseflow.format_issues(kase, 'other'),`

Is there dummy data for those fields, or should I not worry about it?

**Comment by paultag** [comment]
@webinista good question; @plusjeff would know better than me - when do these get filled out?

**Comment by plusjeff** [comment]
@webinista @paultag Try this fake user (all of the possible fake users are in `fakes.rb`)

http://127.0.0.1:3000/caseflow/certifications/full-form8/questions

**Comment by KHarshawat** [comment]
Dude ... @plusjeff and @webinista killing. it.

**Comment by paultag** [comment]
:us:

**Comment by paultag** [comment]
Landed; y'all rock!
