### ISSUE TITLE
BGS | Return proper error when only one of the services is down.

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2639]
# Description
When BGS is down but VACOLS is up,
We're doing a filenumber lookup using the SSN in BGS.
But BGS is down - a lot - so we can't find the SSN/Filenumber...
and we return 404 when it's actually an outage/degradation

## Possible solution:
- can we cache more permanently all the SSNs and Filenumbers? Presumably those don't change
- Report **degradations* `(c) VBMS, 2017`  as 500 and not 404

## Reproduction Steps

**Scenario 1 -**

1. Go kill BGS
1. Lookup some SSN
1. Get 404
1. When it should be 500

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:

![image](https://user-images.githubusercontent.com/18075411/28314321-1893a2a2-6b88-11e7-8aa1-60251c453d96.png)

## Related issues:
https://github.com/department-of-veterans-affairs/caseflow/issues/2515

**Comment by laurjpeterson** [comment]
Closing due to sheer age of this issue
