### ISSUE TITLE
Health-Check | VACOLS connection potential issues

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2640]
# Description

## Concern 1
Current `health-check` reboots the server if a call to VACOLS fails 2+ times
However, if VACOLS is really down - there's no point in rebooting all the servers and causing Pager Duty alarms at 3AM on a Saturday night

Maybe have the HealthCheck read degradation cache if VACOLS is down:
https://github.com/department-of-veterans-affairs/caseflow/blob/4f737c5c714aff94c4bbc8ccdd6c2a6fc3a0ce60/app/services/dependencies_report_service.rb

## Concern 2
It is possible to propagate queries to `health-check` to VACOLS.
Meaning: For every `health-check` there's a query to VACOLS, that means I can DDOS VACOLS through our health-check.
Granted, we're not really exposed to the public net, but still - can be of concern.

## Reproduction Steps

**Scenario 1 -**

1. Kill VACOLS
1. Watch all of our servers reboot all the time
1. Get @askldjd super annoyed.

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Screenshots
**_Scenario 1 - [VACOLS is dead...nuttin we can do really]_**

![screenshot_2017-07-18_07-57-09](https://user-images.githubusercontent.com/18075411/28315983-cc03f2be-6b8e-11e7-8caa-c3b23399f85b.png)

**Comment by askldjd** [comment]
I have set PagerDuty to restrict the SRE hours from 6am - 12am. 

![image](https://user-images.githubusercontent.com/3258724/28376832-213254a2-6c79-11e7-85dd-096b76b7f5c3.png)

**Comment by kierachell** [comment]
The one last concern is that `health-check` exposes VACOLS to ddosing

**Comment by kierachell** [comment]
delegate this to someone

**Comment by dannysellers** [comment]
Related: [Minimum HealthyHostCount LessThanThreshold 1.0 for LoadBalancerName dsva-appeals-certification-prod](https://dsva-appeals.pagerduty.com/incidents/P3CUV1P)
