### ISSUE TITLE
establish_claim_spec failed on line 444 in Travis

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2647]
Line 444 on the establish_claim_spec.rb failed once on the master branch in https://travis-ci.org/department-of-veterans-affairs/caseflow/builds/254617816#L3305 for commit 2820e6b.

From NTH:
To test, wrap the test in the `ensure_stable` wrapper to execute 10 - 100 times both locally and on Travis to see if you can reproduce. The test failed with a `StaleElementReferenceError` meaning that we selected an element with Selenium, and then when we went to act upon it, it was no longer on the page.

This could be the result of a timing issue with how the DOM is re-rendered at various points during our interacting with the page. The solution is generally to always query for an element right before you use it, instead of grabbing one reference and using that many times. By always querying, you're protected against staleness.

**Comment by sharonwarner** [comment]
Combining with another similar issue.
