### ISSUE TITLE
Refactor Case class to include VACOLS::CaseAssignment

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2648]
Refactor `Case` to include a one-to-one relationship with `User` as an assignee and include the query performed in `VACOLS::CaseAssignment` to pull all relevant data.

The `User` model will also need to be refactored to reflect this relationship as one-to-many.

This can be lazy loaded to avoid the N+1 query problem.

**Comment by mdbenjam** [comment]
@mogrenAtWork do you think https://github.com/department-of-veterans-affairs/caseflow/issues/3213 captures this as well?

**Comment by mogrenAtWork** [comment]
Yeah, closing this out
