### ISSUE TITLE
Have a list of services needed for each application, and only display performance degradation banner if one of them is down.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2649]
VVA stability is not high, and although we don't use it for any Caseflow app, we'll currently display the performance degradation banner for it. We should manually list dependencies for each application, and only display the banner if one of those dependencies is reporting an outage.

Certification's dependencies:  
BGS, VBMS, VACOLS

Reader's dependencies:
VBMS, VACOLS

Hearing Prep's dependencies:
VACOLS

Dispatch's dependencies:
BGS,VBMS, VACOLS

See dependencies_report_service.rb and dependencies_check_job.rb for existing code to leverage.

**Comment by kierachell** [comment]
https://github.com/department-of-veterans-affairs/appeals-qa/tree/master/docs/DependencyMaps this?

**Comment by astewarttistatech** [comment]
@nemodjuric @amprokop Is there something to do here to shut off dependancies to produce a degradation banner or do I just wait for something to go down?

**Comment by astewarttistatech** [comment]
connects: #3917

**Comment by astewarttistatech** [comment]
Blocked due to inability to test.

**Comment by astewarttistatech** [comment]
So after all the work that @nemodjuric trying to get a service to go down, BGS AddressService went down on its own.

**PASSED**

Steps to Validate: 
1. Check monitor for a down service (in this case BGS AddressService)
2. Verify that the product that is dependent on that service (Certification) has a degradation banner
3. Verify that the common pages (help) also have a degradation banner
4. Verify that other products that don't use the service are up without a degradation banner (Dispatch, Reader). 

Screenshots: 
<img width="1409" alt="screen shot 2017-11-15 at 11 40 41 am" src="https://user-images.githubusercontent.com/23038505/32848819-713b6350-c9fb-11e7-92b0-b938fa5d36d8.png">
<img width="1400" alt="screen shot 2017-11-15 at 11 40 50 am" src="https://user-images.githubusercontent.com/23038505/32848820-7145dd3a-c9fb-11e7-9a2f-b2ca4c58a67e.png">
<img width="1399" alt="screen shot 2017-11-15 at 11 41 06 am" src="https://user-images.githubusercontent.com/23038505/32848821-71518d7e-c9fb-11e7-8b8c-a3c40ebb2fe6.png">
<img width="1401" alt="screen shot 2017-11-15 at 11 43 22 am" src="https://user-images.githubusercontent.com/23038505/32848822-715913be-c9fb-11e7-8bc7-89fbc74e67c2.png">
