### ISSUE TITLE
Explicitly include :html as a format for rendering templates in app/views/errors

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2652]
Both locally and on Travis builds, Rails complains about a missing template:

<img width="922" alt="screen shot 2017-07-18 at 6 52 26 pm" src="https://user-images.githubusercontent.com/1053255/28343312-b86a1e16-6bea-11e7-8ced-df5598f8145f.png">

But it doesn't look for HTML templates.  Until the root is truly known, it's perfectly fine to explicitly add :html as a format and quiet the noise.

**Comment by kierachell** [comment]
**PASSED**
Fixed Travis and Test spam (sorry don't have logs)
And fixed a `prod-alert`:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/304/
