### ISSUE TITLE
Unified layout not rendering properly for test/setup

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2655]
It looks like this:
![screenshot_2017-07-19_12-44-40](https://user-images.githubusercontent.com/1053255/28379453-ae4357bc-6c81-11e7-8c83-d34c5ca1e4c0.png)

and should look like this (notably, the header content should align with the main content:
![test_setup](https://user-images.githubusercontent.com/1053255/28379444-a2a9a6cc-6c81-11e7-850a-057caf0f29d0.gif)

**Comment by kierachell** [comment]
**PASSED**
![screenshot_2017-07-19_13-51-39](https://user-images.githubusercontent.com/18075411/28381591-6bcd9e12-6c89-11e7-932d-41082b846d07.png)
