### ISSUE TITLE
ArgumentError: comparison of NilClass with ActiveSupport::TimeWithZone failed

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#2658]
Sentry link: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/302/events/

There are appeals with no events. 

To verify:
Go to appeals status, pick appeal that has no document events and make sure the error does not show.

**Comment by joofsh** [comment]
This has been happening 3-5 times per week in production, causing 500 errors for real users on vets.gov

**Comment by amprokop** [comment]
This may have been fixed already. Connect with Teja and see.

**Comment by amprokop** [comment]
This happened again yesterday, so probably isn't fixed https://waffle.io/department-of-veterans-affairs/caseflow/cards/596fb91bdfbc0300245af3fd

**Comment by amprokop** [comment]
Updated Sentry link: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/302/events/

**Comment by kierachell** [comment]
**PASSED**

Tried the request...

<img width="833" alt="screen shot 2017-10-31 at 9 13 20 am" src="https://user-images.githubusercontent.com/18075411/32225483-c527a3a2-be1b-11e7-9bfe-f9636c0b88f2.png">


Saw no error

👏
