### ISSUE TITLE
Add a manual override to the document verification step

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#266]
DROs can short circuit Caseflow if they're clever anyway, let's at least capture why the thing was done. Not sure where to put it; in remarks?

**Comment by shanear** [comment]
This is a situation where she wanted a manual override:


    1) it was erroneously closed out in a different jurisdiction (without a form 8?)  -- The oldest  9 was incorrectly thought to be untimely, and the appeal was closed as untimely while the case was at another VARO; however, with the post-mark date, it was received on the last possible timely receipt date. 

    2) you found this case and added (how did you find the case, if it was outside your jurisdiction?)  The attorney pointed out that he still had an appeal pending on this issue.  I reviewed the 9, and recognized that, although it had been annotated as not received timely, it had in fact been received timely.  The VACOLS record, at another station, needed to be reopened by that other station, and then transferred to us.

    3) the appeal was transferred to your jurisdiction, (but when that happened it was un-certified?) and the 8 you uploaded was still there. You were required to use Caseflow to recertify it. Uploading a duplicate 8 to VBMS.    It was transferred to our station as an active appeal.  At that point, we certified it to BVA., using Caseflow and getting a duplicate 8.  Next time I would use the manual “paper file” process to make the case certified in VACOLS, without adding an 8 to VBMS, since a manual 8 was already in VBMS.

**Comment by paultag** [comment]
Another:

> Today I had an interesting case that involved your caseflow certification – it was a rebuilt folder with missing documents.  Your system would not let me bypass the part with the missing documents in order to  certify the appeal – like a manual override so to speak.
> 
> I had manually completed both the VAF8 and BVA Cert worksheet and uploaded them into VBMS because the it was a rebuilt folder and I knew documents were missing and a few were in Virtual VA. (which was all explained on the VAF8 I completed).  When I went to certify via VACOLS, Caseflow certification would not let me because of missing documents.
> 
> So, in order for me to get the appeal into Cert status , I said it was a hardcopy folder instead of a VBMS file, which allowed me to certify the appeal.  After it was in cert status I went into  VACOLS and updating the Dispatch tab stating it was a VBMS appeal.
> 
> So, is there or do you plan to have a way that we can bypass the automatic VAF8 completed by the system for cases that will not meet the required documents (lost folder/rebuilt folders) or is  the way I worked around it the best solution for now?

**Comment by shellicious** [comment]
Closing this because it is redundant with our research into why folks are working around Caseflow, and assessing if an override is necessary.  https://github.com/department-of-veterans-affairs/caseflow/issues/382

Taking note of reasons why cases with missing docs go forward in research findings: https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/certification/user-research/2016-11%20Findings%20from%20Workaround%20Research.md.
