### ISSUE TITLE
Fix Hearing Prep logo

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2660]
This:
<img width="240" alt="screen shot 2017-07-19 at 5 34 19 pm" src="https://user-images.githubusercontent.com/1053255/28390572-954c334c-6ca8-11e7-8c54-dbe633b1b1ef.png">

Should be this:
<img width="247" alt="screen shot 2017-07-19 at 5 34 35 pm" src="https://user-images.githubusercontent.com/1053255/28390574-9a5a0148-6ca8-11e7-8935-c2728cfe0d76.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access the /hearings/dockets url
2. Validate that the Hearings logo matches the one in the mocks and AC. 

Screenshots: 
<img width="676" alt="screen shot 2017-07-21 at 10 22 11 am" src="https://user-images.githubusercontent.com/23038505/28467687-a65fd772-6dfe-11e7-9d84-3b898aa9fe05.png">
