### ISSUE TITLE
Show spinner at Certification start

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2666]
**Story**
As a user, I want to understand that Caseflow Certification is loading while VBMS is slow. 
For more context, see this post-standup discussion: https://github.com/department-of-veterans-affairs/caseflow/issues/2510#issuecomment-312354083

## AC 
- Add loader at default size to the app canvas with certification blue from the style guide:
 (https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#loaders)
- Copy underneath the loader is "Loading and checking documents from the Veteran’s file…"
- If VBMS is taking longer than 30s to return a list of documents, display this message under the loader: "Documents are taking longer to load than usual. Thanks for your patience!"
- If the VBMS request fails, display an error message as shown in the mock below.

## Mocks

Loader: 

![loading page](https://user-images.githubusercontent.com/1178390/28381792-f9576574-6c89-11e7-86b8-3db5c58f366d.png)

Loader, when VBMS is taking longer than 30s: 

![loading page - slow](https://user-images.githubusercontent.com/1178390/28381814-0cd0a8c2-6c8a-11e7-8839-cc6853165f15.png)

Error message if VBMS is taking too long: 

![error](https://user-images.githubusercontent.com/1178390/28427496-635e8e9c-6d44-11e7-8bbb-af5df4007e47.png)

## Dependencies

- See LoadingScreen.jsx. We'll have to refactor that to be reusable first, so  https://github.com/department-of-veterans-affairs/caseflow/issues/2667 should be complete before starting this
- We'll have to refactor the Rails backend to accommodate this, so https://github.com/department-of-veterans-affairs/caseflow/issues/2668 should be complete before starting this

**Comment by nemodjuric** [comment]
@amprokop If app server returns that data is still loading, what do we do? Do we keep poking the server repeatedly (until one of the following happens: 1. we get data back, 2. request fails 3. time out)
Or do we treat that response as request failed?

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Certification V2 with a VBMS ID that is ready to certify
2. Verify that the spinner is present 
3. If VBMS is taking too long, verify that the Technical Difficulties page is displayed

Screenshots: 
![certification spinner](https://user-images.githubusercontent.com/23038505/28924139-aa01e0ca-782e-11e7-88c3-c944cb8c9952.gif)
