### ISSUE TITLE
Refactor LoadingScreen.jsx to be a reusable component.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2667]
LoadingScreen.jsx currently has a lot of Reader-specific logic in it. Let's refactor it to remove the reader-specific logic such that we can reuse it across all Caseflow apps. 

## AC
- LoadingScreen should be generic and should take in:
  - spinnerColor (for different apps)
  - message
  - anything else necessary

**Comment by kierachell** [comment]
**PASSED**
???? I guess ????
## Reader is still there...
![screenshot_2017-07-24_14-14-10](https://user-images.githubusercontent.com/18075411/28537918-72388f6a-707a-11e7-8dda-4bcbe6e7a30d.png)


## Hearings too


![screenshot_2017-07-24_14-15-31](https://user-images.githubusercontent.com/18075411/28537963-98b4faca-707a-11e7-869e-075a7a64ce0c.png)
