### ISSUE TITLE
Create Fakes::EfolderService to mock EfolderService calls to fetch documents

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2669]
Create a Fakes::EfolderService class to mock the /files endpoint that is being created to allow Reader to pull documents from eFolder rather than S3/VBMS.

The EfolderService will be implemented with calls to eFolder with #2339 

# AC
1. Set  the feature toggle for `efolder_docs_api` to `true` for the environment: `FeatureToggle.enable!(:efolder_docs_api)`
1. Go to http://localhost:3000/reader/appeal/reader_id1/documents
1. The document originally titled `This is a very long document type let's see what it does to the UI!` will now be titled `This is a very long document type that's loaded from eFOLDER!`
1. Disable the FeatureToggle and verify this document title has changed

**Comment by kierachell** [comment]
**PASSED**

Worked for me locally, did not check demo... not sure if needed.
