### ISSUE TITLE
Determine what's causing form fields to jump around. 

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#267]
#257 mentioned issues with IE, leading to removal of show / hide code. From Slack:

> We're also hitting a weird JS issue where the certification name goes missing. Any thoughts, @tiffany_b_brown ? It goes and shows when they click 'other'

Need to better understand what "certification name goes missing" means and figure out what could be causing it.

**Comment by webinista** [comment]
This is the behavior I see in IE 9, 10, or 11. @KHarshawat can you confirm whether this is what you / the user are seeing?

![2015-12-02_11-17-51](https://cloud.githubusercontent.com/assets/354277/11545307/b0af1578-9914-11e5-9bfc-4e2a5707d014.gif)

**Comment by KHarshawat** [comment]
@webinista nope, there was a bug where when the user checked / unchecked `other` 17a and 17b would actually completely disappear. Not sure how to reproduce but we should test thoroughly when we add the show/hide logic back in.

**Comment by webinista** [comment]
Closing for now, since the entire form has changed.
