### ISSUE TITLE
Document list | Error message when claims folder detail fails

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2675]
## Story 
There are 2 different types of error/ latency feedback we should show when there is a delay retrieving the claims folder detail. 

## AC
- [ ] Show the following errors for each situation

1.  **Scenario 1 -** Currently, it is faster to retrieve the API for documents list than the VACOLs claims detail information. When there we still cannot retrieve the claims folder details 0-30 seconds. 
![image](https://user-images.githubusercontent.com/13420618/28590537-752326aa-7150-11e7-80d4-5e25470b808f.png)

     - [ ] Show the word "**_Loading claims folder details..._**" in `h2` + bold + italicized followed by the button spinner when there is a few second glitch/ delay to retrieve claims folder information
     - [ ] [Loading Button spinner ](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#loading_buttons)

2. **Scenario 2** - When there we still cannot retrieve the claims folder details after 30 seconds. 
![image](https://user-images.githubusercontent.com/13420618/28587858-8a1f89b8-7146-11e7-95eb-56366861d261.png)
     - [ ] Title: Unable to retrieve claims folder details | Body copy: Caseflow is experiencing technical difficulties right now. Please refresh this page or try again later. | Hyperlink refresh this page to refresh page
     - [ ] [Alert Error status](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#alerts)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2792

**Comment by gnakm** [comment]
Consider what it would be like for document viewer side menu as well.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
