### ISSUE TITLE
VBMS::HTTPErrorapp/services/external_api/vbms_service.rb

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2679]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/300/

Seems related to VBMS::Requests::UploadDocumentWithAssociations

**Comment by mdbenjam** [comment]
Seems to be the same as this issue: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/347/
