### ISSUE TITLE
Form 8:  Browser Exit:  Add warning when leaving form 8 after changes were made

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#268]
As a RO Caseworker, I would like to see a warning message for when I accidentally close the window after having entered a lot of information so that I don't loose all of that data unknowingly.

# Acceptance Criteria
1. Verify that after adding information to Form 8 and click the browser close button, the following warning message is displayed in a browser alert box:   
**_Title:_** Leaving Certification?
**_Text:_** Your changes to this case have not been saved. Are you sure you want to leave this page?
1. Verify that the Alert box has the following buttons:  
**_Stay on this page_**
**_Leave this page_**
1. Verify that after clicking on the **_Stay on this page_** button, the Alert box is close and the Electronic Form 8 becomes the active window.
1. Verify that after clicking on the **_Leave this page_** button, the Electronic Form 8 window and Alert box are closed.

# Mockup
**_View - Browser Alert Box Sample_**
![browser alert box](https://cloud.githubusercontent.com/assets/23063044/22006643/d4f0dbd2-dc3a-11e6-97c5-08e43b36d8bc.png)

# Related Stories

**Comment by shanear** [comment]
@shellicious what do you think about this?

**Comment by shellicious** [comment]
@shanear this sounds like a good feature to pursue. Is there more context around this -- users requesting this, stakeholders bringing it up, progress made since May 6, etc.?

**Comment by shanear** [comment]
@shellicious I think we had some users in the beginning complain about loosing their form data after closing out. I thought this would be a good way to mitigate that. I could dig fro the exact feedbacks, but it'd be difficult since Sharepoint has become hard to access these days.

**Comment by shellicious** [comment]
@shanear @nikitarockz since this is a warning message that appears when a user tries to exit Certification (navigating to a new page, closing the window or tab), it will be an alert box, not a modal.

Proposed text: 

Title: Leaving Certification?

Text: Your changes to this case have not been saved. Are you sure you want to leave this page?

Buttons: Stay on this page, Leave this page

**Comment by shanear** [comment]
Postponing this one because the form8 may be going away soon.

**Comment by amprokop** [comment]
Closing, we launched v2 and have no Form 8 UI
