### ISSUE TITLE
IE 11: Hidden fields show all the time

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#268]
All the hidden fields show all the time.

Note: I'm in the three-up branch, which seems unrelated to this issue, but if that's helpful just wanted to note it here.

![image](https://cloud.githubusercontent.com/assets/950486/11563138/55a0e68e-99a0-11e5-8595-372985b91ff5.png)

**Comment by webinista** [comment]
That's by design in light of an issue the team found yesterday. See #257 and #262.
