### ISSUE TITLE
RDS Snapshot | Investigate creating a regular RDS snapshot of VACOLS to dev against

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2680]
Based on our conversation from https://github.com/department-of-veterans-affairs/caseflow/issues/2619 we would like to create a regular RDS snapshot of VACOLS that we can connect to and dev against.

**Comment by kierachell** [comment]
Working on TMS training to get access:
https://github.com/department-of-veterans-affairs/appeals-admin/blob/master/onboarding-contractors/Admin%20Privileges.md

**Comment by kierachell** [comment]
# Tech Spec (of sorts)
- Complete TMS training to have VACOLS system access
- Move smoke tests from UAT to Preprod
- Automate VACOLS DMS task
- Collect indicies/triggers/functions from VACOLS
- Automate VACOLS RDS replication (redeploy with every UAT deploy?)
- Adjust UAT env to point to new VACOLS
- Note that VBMS integration testing will still require UAT env
- Create VBMS/BGS scraping scripts for UAT env
- Create a de-personalization scripts that will seed VACOLS RDS with VBMS/BGS info

**Comment by kierachell** [comment]
- I need a list from @cmgiven of all tables+columns that would be considered PII.

Feel free to edit this comment to keep it as a single source:

- CORRES
  - SNAMEF
  - SNAMEL
  - SSN
  - SADDRST1
  - SADDRST2
  - SADDRCTY
  - SADDRSTT
  - SADDRCNTY
  - SADDRZIP
- BRIEFF
  - BFCORLID
- STAFF
  - SUSRPW
  - SNAMEF
  - SNAMEL
 
MAIL table? REP table? Some tables have SNOTES and other random fields that we might just need to dump to avoid random leaks?

**Comment by kierachell** [comment]
One side effect of a proper migration:
- https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/444/

- We will have to reference all tables as they should be: `VACOLS.<tablename` because our user `DSUSER` is not the owner of these tables. In VACOLS, this is hacked about, but it will not work in an AWS RDS as it does not allow such security hacks

**Comment by cmgiven** [comment]
Let's talk about why we want to differentiate PII/non-PII. By default, we should consider all VACOLS fields PII.

**Comment by kierachell** [comment]
- So I need to make a sanitizing script for the fields above.
- I will test it out when DMS task is a bit more automated.

**Comment by kierachell** [comment]
**PASSED**

Worked for me:
<img width="444" alt="screen shot 2017-10-26 at 9 44 11 am" src="https://user-images.githubusercontent.com/18075411/32056279-3f2b1f1e-ba32-11e7-8745-9b754c30d94d.png">
