### ISSUE TITLE
[V2] Feature Flag | Enable District ROs - North Atlantic (8/4/2017)

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#2688]
As Product Owner, I would like the following ROs to have the Certification v2 feature flag enabled on Friday, 8/4/2017 so that the users in the North Atlantic District can begin using Certification v2.

### ROs

District|BFREGOFF|Name
---|---|---
North Atlantic|RO13|Baltimore, MD
North Atlantic|RO01|Boston, MA
North Atlantic|RO07|Buffalo, NY
North Atlantic|RO08|Hartford, CT
North Atlantic|RO15|Huntington, WV
North Atlantic|RO73|Manchester, NH
North Atlantic|RO06|New York, NY
North Atlantic|RO09|Newark, NJ
North Atlantic|RO10|Philadelphia, PA
North Atlantic|RO11|Pittsburgh, PA
North Atlantic|RO04|Providence, RI
North Atlantic|RO14|Roanoke, VA
North Atlantic|RO02|Togus, ME
North Atlantic|RO05|White River Junction, VT
North Atlantic|RO18|Winston-Salem, NC

**_Total ROs:  15_**

# Acceptance Criteria
1.	Verify that the feature flag has been turned on for all ROs mentioned above.

# Related Stories
IP | Certification v2 | Request feature flag enabled [#1450](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1450)

**Comment by nemodjuric** [comment]
FeatureToggle.enable!(:certification_v2, regional_offices: ["RO13","RO01","RO07","RO08","RO15","RO73","RO06","RO09","RO10","RO11","RO04","RO14","RO02","RO05","RO18"])
=> true
