### ISSUE TITLE
[Backend] HEARSCHED changes update MDUSER and MDTIME

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#2690]
This issue is a child of #2221.

## Steps to Validate:

1. Start `rails c`` and ensure you are connected to Vacols dev env
2. Find a hearing in the hearings table (make sure it exists in Vacols)
`h = Hearing.find(id)`
3 Update any field on the hearing object which will trigger an update on the HEARSHED table. For example, 
```
h.update(disposition: :held)
h.update(hold_open: 30)
h.update(aod: :granted)
h.update(notes: "test")
h.update(transcript_requested: false)
```
4. Make sure Hearshed table's MDUSER and MDTIME are updated in accordance with the above AC.

## AC:

1. When the `HEARSCHED` table is updated (as by #2684), the following fields are updated:
    - `HEARSCHED.MDUSER` is set to the `STAFF.SLOGID` of the current user.
    - `HEARSCHED.MDTIME` is set to the current time.

**Comment by kierachell** [comment]
Is this a stored procedure? What method would cause this chain of updates?
- Looking in the PR
<img width="812" alt="screen shot 2017-08-03 at 10 28 16 am" src="https://user-images.githubusercontent.com/18075411/28926681-80b7e05e-7836-11e7-8404-badf1453c51d.png">
- Not seeing any testing directions or AC there either
- What do?

**Comment by aroltsch** [comment]
@kierachell 
Steps to Validate:

1. Start `rails c`` and ensure you are connected to Vacols dev env
2. Find a hearing in the hearings table (make sure it exists in Vacols)
`h = Hearing.find(id)`
3 Update any field on the hearing object which will trigger an update on the HEARSHED table. For example, 
h.update(disposition: :held)
h.update(hold_open: 30)
h.update(aod: :granted)
h.update(notes: "test")
h.update(transcript_requested: false)
4. Make sure Hearshed table's MDUSER and MDTIME are updated in accordance with the above AC.

**Comment by kierachell** [comment]
### Wrong disposition has beautiful error 👍 
```
h.update(disposition: :jesus_saved_me)
   (1.6ms)  BEGIN
[2017-08-04 10:22:50 -0400]    (1.6ms)  BEGIN
   (1.4ms)  ROLLBACK
[2017-08-04 10:22:50 -0400]    (1.4ms)  ROLLBACK
HearingMapper::InvalidDispositionError: HearingMapper::InvalidDispositionError
```

### Update to nil? is OK?
```
h.update(disposition: nil)
   (1.6ms)  BEGIN
[2017-08-04 10:23:32 -0400]    (1.6ms)  BEGIN
STARTED VACOLS: update_hearing! 370395
[2017-08-04 10:23:32 -0400] STARTED VACOLS: update_hearing! 370395
  SQL (107.7ms)  UPDATE "VACOLS"."HEARSCHED" SET "MDTIME" = :a1 WHERE "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a2  [["mdtime", 2017-08-04 10:23:32 UTC], ["hearing_pkseq", 370395]]
[2017-08-04 10:23:33 -0400]   SQL (107.7ms)  UPDATE "VACOLS"."HEARSCHED" SET "MDTIME" = :a1 WHERE "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a2  [["mdtime", 2017-08-04 10:23:32 UTC], ["hearing_pkseq", 370395]]
FINISHED VACOLS: update_hearing! 370395:   0.000000   0.000000   0.000000 (  0.215161)

[2017-08-04 10:23:33 -0400] FINISHED VACOLS: update_hearing! 370395:   0.000000   0.000000   0.000000 (  0.215161)

   (1.7ms)  COMMIT
[2017-08-04 10:23:33 -0400]    (1.7ms)  COMMIT
=> true
```

### Should MDUSER be updatable without `current_user`?

Right now MDUSER is updated _once_ and just set to SLOGID from STAFF (not from what is in Caseflow)

### Should MDTIME and MDUSER update on _every_ model update?

- Call `h.update` once: MDUSER is set to SLOGID from STAFF (not current user) and MDTIME is updated
- Call `h.update` again on the same hearing `MDTIME` is updated to most recent update time, but `MDUSER` not.

**Comment by aroltsch** [comment]
Question: Should MDUSER be updatable without current_user? 
Answer: mduser is set to SLOGID from STAFF - correct

Question: Should MDTIME and MDUSER update on every model update?
Answer: MDTIME and MDUSER should be updated on every update of disposition, hold_open, aod, notes, transcript_requested. MDUSER stays the same until SLOGID from STAFF is changed  (@cmgiven can confirm)


Question: What the hell am I updating here?????
Answer: you are right, we should only allow the update of disposition, hold_open, aod, notes, transcript_requested on HEARSHED

**Comment by cmgiven** [comment]
Yup, that's right.

**Comment by kierachell** [comment]
**PASSED**

Will be retested with full integration;
Listed validations are there:
```
h.update(notes: :held)
   (0.6ms)  BEGIN
[2017-08-08 08:43:02 -0400]    (0.6ms)  BEGIN
   (0.4ms)  ROLLBACK
[2017-08-08 08:43:02 -0400]    (0.4ms)  ROLLBACK
HearingMapper::InvalidNotesError: HearingMapper::InvalidNotesError
        from /opt/caseflow-certification/src/app/mappers/hearing_mapper.rb:42:in `notes_to_vacols_format'
        from /opt/caseflow-certification/src/app/mappers/hearing_mapper.rb:11:in `hearing_fields_to_vacols_codes'
        from /opt/caseflow-certification/src/app/repositories/hearing_repository.rb:13:in `update_vacols_hearing!'
        from /opt/caseflow-certification/src/app/models/hearing.rb:28:in `block in update'
```


```
<main>'irb(main):077:0> h.update(transcript_requested: :false)
   (0.4ms)  BEGIN
[2017-08-08 08:43:43 -0400]    (0.4ms)  BEGIN
   (0.4ms)  ROLLBACK
[2017-08-08 08:43:43 -0400]    (0.4ms)  ROLLBACK
HearingMapper::InvalidTranscriptRequestedError: HearingMapper::InvalidTranscriptRequestedError
```


Loving the error types :D
