### ISSUE TITLE
[Backend] Granting AOD on daily docket creates diary entry

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#2691]
This issue is a child of #2221.

AC:

1. When AOD is checked on the daily docket, a new diary entry is created in the `ASSIGN` table.
    - `ASSIGN.TASKNUM` should be set to `BRIEFF.BFKEY` + 'D' + the next available number 1 through 99. So the first diary for appeal '2222222' would be '2222222D1'. If that already exists, the next diary would be '2222222D2'.
    - `ASSIGN.TSKACTCD` should be set to 'B'.
    - The days to complete (`ASSIGN.TSKDTC` and the calculated `ASSIGN.TSKDDUE`) should be set to the value of `select ACTCDTC from ACTCODE where ACTCKEY = 'B'`
    - `ASSIGN.TSKSTFAS` should be set to the value of `select ACSPARE1 from ACTCODE where ACTCKEY = 'B'` (currently '59').
    - `ASSIGN.TSKRQACT` should be set to 'AOD granted on Record during hearing.'
    - `ASSIGN.TSKDASSN` should be set to the current time.
    - `ASSIGN.TSKADUSR` and `ASSIGN.TSKADTM` should be set to the current user and the current time, respectively. `ASSIGN.TSKSTOWN` should also be set to the current user.
    - `ASSIGN.TSKSTAT` should be set to 'P' (pending).
2. If the representative is the Paralyzed Veterans of America (`BRIEFF.BFSO = 'G'`), then a second diary entry should be created.
    - `ASSIGN.TSKACTCD` should be set to 'B1'.
    - The days to complete (`ASSIGN.TSKDTC` and the calculated `ASSIGN.TSKDDUE`) should be set to the value of `select ACTCDTC from ACTCODE where ACTCKEY = 'B1'`
    - `ASSIGN.TSKSTFAS` should be set to the value of `select ACSPARE1 from ACTCODE where ACTCKEY = 'B1'` (currently '59').
    - All other fields should be set as above.

**Comment by aroltsch** [comment]
@cmgiven could you please clarify, when you say "When AOD is checked on the daily docket", do you mean `granted`? We have 3 options for aod:
```
HEARING_AODS = {
    G: :granted,
    Y: :filed,
    N: :none
  }
```

Also, if aod is set to `nil` or `:none` do we want to delete a diary entry?

**Comment by cmgiven** [comment]
If AOD is either granted or filed, we should create the diary. Yes, I think it's appropriate to delete it, using the same logic as for the hold open.

**Comment by kierachell** [comment]
**PASSED**

- Checked setting to `nil`
- Checked with BFSO=G and without
- Checked changing Filed to Granted and back
- Checked deleting manually
