### ISSUE TITLE
[Backend] Holding a case open on daily docket creates diary entry

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#2692]
This issue is a child of #2221.

AC: 

1. If a number greater than 0 is selected in "Hold Open" dropdown menu, a new diary entry is created in the `ASSIGN` table.
    - `ASSIGN.TASKNUM` should be set to `BRIEFF.BFKEY` + 'D' + the next available number 1 through 99. So the first diary for appeal '2222222' would be '2222222D1'. If that already exists, the next diary would be '2222222D2'.
    - `ASSIGN.TSKACTCD` should be set to 'A'.
    - The days to complete (`ASSIGN.TSKDTC` and the calculated `ASSIGN.TSKDDUE`) should be set to the number of days entered by the user plus 5. So if the user selected 30 days, `TSKDTC` should be 35.
    - `ASSIGN.TSKSTFAS` should be set to the value of `select ACSPARE1 from ACTCODE where ACTCKEY = 'A'` (currently '25').
    - `ASSIGN.TSKRQACT` should be set to 'Record held open by VLJ at hearing for additonal evidence.'
    - `ASSIGN.TSKDASSN` should be set to the current time.
    - `ASSIGN.TSKADUSR` and `ASSIGN.TSKADTM` should be set to the current user and the current time, respectively. `ASSIGN.TSKSTOWN` should also be set to the current user.
    - `ASSIGN.TSKSTAT` should be set to 'P' (pending).

**Comment by kierachell** [comment]
### When `hold_open` set to 0 the Note should be deleted
<img width="470" alt="screen shot 2017-08-10 at 3 28 22 pm" src="https://user-images.githubusercontent.com/18075411/29188269-a0c8e6cc-7de0-11e7-9534-090f9b4c247d.png">

**Comment by kierachell** [comment]
**PASSED**

- Checked with no notes
- Overriding notes
- 0 holddays
- nil holddays
