### ISSUE TITLE
[Backend] Changes to daily docket disposition update BRIEFF.BFHA

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#2693]
This issue is a child of #2221.

## Steps to Validate:
1. Start `rails c` and ensure you are connected to Vacols dev env
2. Find a hearing in the hearings table (make sure it exists in Vacols)
`h = Hearing.find(id)`
3. Update the disposition on the hearing object:
```
h.update(disposition: :held)
h.update(disposition: :cancelled)
h.update(disposition: :postponed)
h.update(disposition: :no_show)
```
4. BRIEFF.BFHA associated with that hearing should be updated in accordance with the AC above

## AC: 

1. If the disposition is 'H' (held), `BRIEFF.BFHA` should be set to '1' (if central office hearing), '2' (if travel board hearing), or '6' (if video hearing).
2. If the disposition is 'P' (postponed), `BRIEFF.BFHA` should be set to null.
3. If the disposition is 'C' or 'N' (canceled or not held), `BRIEFF.BFHA` should be set to '5'.

Tech notes:

The mapping of BFHA values:

BFHA | Name
-- | --
1 | Central Office
2 | Travel Board
3 | Field (hearing officer)
4 | Informal Hearing (VSO brief, only)
5 | None
6 | Video Hearing

**Comment by aroltsch** [comment]
How to determine #1 in AC
If `bfhr == '1',` then `bfha = '1'` 2) If `bfhr == '2' && bfdocind != 'V'` , then `bfha = '2'` 3) If `bfhr == '2' && bfdocind == 'V'`, then `bfha = '6'`

**Comment by kierachell** [comment]
- When does this happen?
- Is there a method to call to cause this chain of events?
- Are the values read at any point?
- Looking in the PR for AC or Testing recommendations:
<img width="904" alt="screen shot 2017-08-03 at 10 30 11 am" src="https://user-images.githubusercontent.com/18075411/28926782-d561235e-7836-11e7-973e-550d968576e1.png">
- Nothing

**Comment by aroltsch** [comment]
@kierachell 
Steps to Validate:
1. Start `rails c` and ensure you are connected to Vacols dev env
2. Find a hearing in the hearings table (make sure it exists in Vacols)
`h = Hearing.find(id)`
3. Update the disposition on the hearing object:
```
h.update(disposition: :held)
h.update(disposition: :cancelled)
h.update(disposition: :postponed)
h.update(disposition: :no_show)
```
4. BRIEFF.BFHA associated with that hearing should be updated in accordance with the AC above

**Comment by kierachell** [comment]
### Can disposition be nullable?
```
h.update(disposition: nil)
   (0.7ms)  BEGIN
[2017-08-04 12:21:40 -0400]    (0.7ms)  BEGIN
```
returns TRUE,
sets DISP and BFHA to `NULL`


```
'data.frame':	1 obs. of  20 variables:
 $ STAFKEY      : chr "URPOWELL"
 $ SDOMAINID    : chr "CF_MCCOY_317"
 $ SATTYID      : chr "153"
 $ SNAMEF       : chr "Ursula"
 $ SNAMEL       : chr "Powell"
 $ BOARD_MEMBER : chr "153"
 $ HEARING_PKSEQ: num 367483
 $ HEARING_TYPE : chr "V"
 $ AOD          : chr NA
 $ HEARING_DATE : chr "2017-05-25 15:39:50.0"
 $ HEARING_DISP : chr NA
 $ BFHA         : chr NA
 $ VDKEY        : chr "355607"
 $ MDUSER       : chr "URPOWELL"
 $ MDTIME       : chr "2017-08-04 12:21:46.0"
 $ HEARING_VENUE: chr "RO08"
 $ HOLDDAYS     : num NA
 $ NOTES1       : chr "D.A.V.=Colleen Sullivan                                  Veteran"
 $ TRANREQ      : chr NA
 $ FOLDER_NR    : chr "2512379"
```

**Comment by aroltsch** [comment]
@kierachell you cannot update type through our Hearing model: `h.update(type: :travel)`- this will not work. You need to directly update HEARSHED `hearing_type` value. You can try this:
```VACOLS::CaseHearing.find_by(hearing_pkseq: 345501).update(hearing_type: "C")```

**Comment by aroltsch** [comment]
@cmgiven Can we clear disposition (set to `nil`). What happens to `BRIEFF.BFHA`  if we set disposition to `nil`?

**Comment by cmgiven** [comment]
Clearing the disposition would make it look as though the hearing is still pending. That probably should not happen. BFHA is one of the problems it would cause. An appeal can have multiple hearings, but there's only one BFHA. So if we were to overwrite BFHA with nil, we would potentially be overwriting not just the current hearing but also a previous one. We could reconcile that by looking for other hearings, but the simpler approach would be to prevent it altogether.

**Comment by aroltsch** [comment]
Ok, I will disallow clearing of disposition.

**Comment by kierachell** [comment]
- Woot
```
h.update(disposition: nil)
   (0.7ms)  BEGIN
[2017-08-08 07:46:50 -0400]    (0.7ms)  BEGIN
   (0.5ms)  ROLLBACK
[2017-08-08 07:46:50 -0400]    (0.5ms)  ROLLBACK
HearingMapper::InvalidDispositionError: HearingMapper::InvalidDispositionError
        from /opt/caseflow-certification/src/app/mappers/hearing_mapper.rb:49:in `disposition_to_vacols_format'
        from /opt/caseflow-certification/src/app/mappers/hearing_mapper.rb:12:in `hearing_fields_to_vacols_codes'
        from /opt/caseflow-certification/src/app/repositories/hearing_repository.rb:13:in `update_vacols_hearing!'
        from /opt/caseflow-certification/src/app/models/hearing.rb:28:in `block in update'
```

**Comment by kierachell** [comment]
### If bfhr == '1', then bfha = '1':
```
h.update(disposition: :held)
   (0.6ms)  BEGIN
[2017-08-08 07:53:02 -0400]    (0.6ms)  BEGIN
STARTED VACOLS: update_hearing! 347088
[2017-08-08 07:53:02 -0400] STARTED VACOLS: update_hearing! 347088
  SQL (102.9ms)  UPDATE "VACOLS"."HEARSCHED" SET "HEARING_DISP" = :a1, "MDTIME" = :a2 WHERE "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a3  [["hearing_disp", "H"], ["mdtime", 2017-08-08 07:53:02 UTC], ["hearing_pkseq", 347088]]
[2017-08-08 07:53:02 -0400]   SQL (102.9ms)  UPDATE "VACOLS"."HEARSCHED" SET "HEARING_DISP" = :a1, "MDTIME" = :a2 WHERE "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a3  [["hearing_disp", "H"], ["mdtime", 2017-08-08 07:53:02 UTC], ["hearing_pkseq", 347088]]
  SQL (103.1ms)  UPDATE "VACOLS"."BRIEFF" SET "BFHA" = :a1 WHERE "VACOLS"."BRIEFF"."BFKEY" = :a2  [["bfha", "6"], ["bfkey", "858673"]]
[2017-08-08 07:53:03 -0400]   SQL (103.1ms)  UPDATE "VACOLS"."BRIEFF" SET "BFHA" = :a1 WHERE "VACOLS"."BRIEFF"."BFKEY" = :a2  [["bfha", "6"], ["bfkey", "858673"]]
FINISHED VACOLS: update_hearing! 347088:   0.010000   0.000000   0.010000 (  0.313586)

[2017-08-08 07:53:03 -0400] FINISHED VACOLS: update_hearing! 347088:   0.010000   0.000000   0.010000 (  0.313586)

   (0.5ms)  COMMIT
[2017-08-08 07:53:03 -0400]    (0.5ms)  COMMIT
=> true
```

Checking vacols:
```
 $ HEARING_PKSEQ: num 347088
 $ HEARING_TYPE : chr "V"
 $ AOD          : chr NA
 $ HEARING_DATE : chr "2017-09-06 21:38:26.0"
 $ HEARING_DISP : chr "H"
 $ BFHA         : chr "6"
 $ BFHR         : chr "1"
 $ BFTBIND      : chr "X"
 $ BFDOCIND     : chr "V"
 $ VDKEY        : chr NA
 $ MDUSER       : chr "WMYATES"
 $ MDTIME       : chr "2017-08-08 07:53:02.0"
 $ HEARING_VENUE: chr NA
 $ HOLDDAYS     : num 7
 $ NOTES1       : chr NA
 $ TRANREQ      : chr NA
 $ FOLDER_NR    : chr "858673"
```

## If bfhr == '2' && bfdocind != 'V' , then bfha = '2':

```
$ HEARING_PKSEQ: num 347088
 $ HEARING_TYPE : chr "V"
 $ AOD          : chr NA
 $ HEARING_DATE : chr "2017-09-06 21:38:26.0"
 $ HEARING_DISP : chr "H"
 $ BFHA         : chr "6"
 $ BFHR         : chr "2"
 $ BFTBIND      : chr NA
 $ BFDOCIND     : chr NA
 $ VDKEY        : chr NA
 $ MDUSER       : chr "WMYATES"
 $ MDTIME       : chr "2017-08-08 07:56:31.0"
 $ HEARING_VENUE: chr NA
 $ HOLDDAYS     : num 7
 $ NOTES1       : chr NA
 $ TRANREQ      : chr NA
 $ FOLDER_NR    : chr "858673"
```
Nope...

What am I missing?

**Comment by aroltsch** [comment]
Artem, please re-test this. Ignore `bfhr` and `bfdocind`. Use HEARSHED.hearing_type to determine the hearing type.

**Comment by aroltsch** [comment]
@cmgiven we would like to clarify https://github.com/department-of-veterans-affairs/caseflow/issues/2693#issuecomment-320338875 you said that ```So if we were to overwrite BFHA with nil, we would potentially be overwriting not just the current hearing but also a previous one.```. However, in AC, you say ```If the disposition is 'P' (postponed), BRIEFF.BFHA should be set to null.``` Please clarify.

**Comment by kierachell** [comment]
## Before:
```
$ HEARING_PKSEQ: num 344506
 $ HEARING_TYPE : chr "V"
 $ AOD          : chr NA
 $ HEARING_DATE : chr "2017-06-08 00:31:04.0"
 $ HEARING_DISP : chr "P"
 $ BFHA         : chr "5"
 $ BFHR         : chr "2"
 $ BFTBIND      : chr NA
 $ BFDOCIND     : chr "V"
 $ VDKEY        : chr "319102"
 $ MDUSER       : chr "MWALLACE"
 $ MDTIME       : chr "2012-06-26 00:00:00.0"
 $ HEARING_VENUE: chr "RO49"
 $ HOLDDAYS     : num NA
 $ NOTES1       : chr "Vet is not dead this was a mistake at the RO they are going to correct it."
 $ TRANREQ      : chr NA
 $ FOLDER_NR    : chr "1687596"
```

- So it's already postponed?
- Let's...repostpone it

```
$ HEARING_PKSEQ: num 344506
 $ HEARING_TYPE : chr "V"
 $ AOD          : chr NA
 $ HEARING_DATE : chr "2017-06-08 00:31:04.0"
 $ HEARING_DISP : chr "P"
 $ BFHA         : chr NA
 $ BFHR         : chr "2"
 $ BFTBIND      : chr NA
 $ BFDOCIND     : chr "V"
 $ VDKEY        : chr "319102"
 $ MDUSER       : chr "HROBERT"
 $ MDTIME       : chr "2017-08-08 08:16:36.0"
 $ HEARING_VENUE: chr "RO49"
 $ HOLDDAYS     : num NA
 $ NOTES1       : chr "Vet is not dead this was a mistake at the RO they are going to correct it."
 $ TRANREQ      : chr NA
 $ FOLDER_NR    : chr "1687596"
```

**Comment by cmgiven** [comment]
If a hearing is marked as 'P', BFHA should be nulled. This is to mark that a hearing is still pending. 'P' indicates that the hearing will be rescheduled for another time, as opposed to canceled or no-show, which indicate that the case will proceed without a hearing.

You're right to note that this is contradictory with my previous comment. If we assume that the existence of a HEARSCHED row without a disposition demonstrates that a hearing is still pending, then we could null BFHA if HEARING_DISP is nulled. I guess the risk would be that a hearing is created in error, a disposition is set, and then removed. That seems pretty implausible.

The BFHA field should probably not exist.

**Comment by kierachell** [comment]
**PASSED**

Based on `HEARING_TYPE` I am seeing `BFHA` set correctly.
