### ISSUE TITLE
[V2] Feature Flag | Enable District ROs - Continental (8/11/2017)

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#2694]
As Product Owner, I would like the following ROs to have the Certification v2 feature flag enabled on Friday, 8/11/2017 at 4:10 pm so that the users in the **_Continental_** District can begin using Certification v2.

### Continental District ROs

District|BFREGOFF|Name
---|---|---
Continental|RO62|Houston, TX
Continental|RO21|New Orleans, LA
Continental|RO49|Waco, TX
Continental|RO39|Denver, CO
Continental|RO50|Little Rock, AR
Continental|RO23|Jackson, MS
Continental|RO36|Ft. Harrison, MT
Continental|RO42|Cheyenne, WY
Continental|RO41|Salt Lake City, UT
Continental|RO51|Muskogee, OK

**_Total ROs:  10_**

# Acceptance Criteria
1.	Verify that the feature flag has been turned on for all ROs mentioned above.

# Related Stories
IP | Certification v2 | Request feature flag enabled [#1450](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1450)

**Comment by nemodjuric** [comment]
FeatureToggle.enable!(:certification_v2, regional_offices: ["RO62", "RO21", "RO49", "RO39", "RO50", "RO23", "RO36", "RO42", "RO41", "RO51"])
=> true
