### ISSUE TITLE
Reader - ArgumentError: comparison of Fixnum with Hash failed

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2698]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/309/

ArgumentError
comparison of Fixnum with Hash failed

app/jobs/retrieve_appeals_documents_for_reader_job.rb in block in perform at line 24

**Comment by kierachell** [comment]
**PASSED**
```
{"limit"=>1500, "_aj_symbol_keys"=>[]}
```
Job does attempt to run, now just need to have it not explode on missing SSNs:
