### ISSUE TITLE
Pilot Header breaks 508 compliance

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#27]
This should be an easy fix, but should we get scanned, this would be a failure. Mostly filing an issue for awareness that we should check compliance when UI modifications are made (which hopefully will be easier once we're running this CI-style).

![image](https://cloud.githubusercontent.com/assets/950486/10514555/7736ccaa-731c-11e5-8eff-331bf5554062.png)

![image](https://cloud.githubusercontent.com/assets/950486/10514566/85f25a16-731c-11e5-9ed1-643f32e8a895.png)

**Comment by alex** [comment]
@plusjeff we can fix this by making that text really be an `<hsomething>` and using CSS to style it smaller, yeah? Or we could drop the bold?

**Comment by plusjeff** [comment]
Dropping the `strong`/bold is likely the easiest. To get it to still be bold, probably should just wrap it in a `span` or `hsomething` and style it.
