### ISSUE TITLE
Performance Degradation banner should be manually toggleable

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2703]
On the morning 07/24, we noticed that 13% of efolder requests that morning seemed to be failing, but that monitor didn't pick it up. We had no way to inform users of this partial outage. This convinced us that we should be able to manually toggle the performance degradation banner. We'll keep the manual toggle global for now (i.e. we don't need to break it out by application)

## AC
- We should be able to manually toggle the performance degradation banner 
- If we manually toggle the performance degradation banner, it should override the automated performance degradation banner. That is, if we manually turn it on, it should stay on regardless of Caseflow Monitor results.  If we manually turn it off, it should stay off regardless of Caseflow Monitor results. (This will be useful when we know there are false positives or if Monitor is misbehaving)

**Comment by evankroske** [comment]
@amprokop , what's AC? It's not in the glossary: http://www.navapbc.com/glossary/#ac

**Comment by evankroske** [comment]
It's "Acceptance Criteria"

**Comment by evankroske** [comment]
A similar change: https://github.com/department-of-veterans-affairs/caseflow/pull/2867

**Comment by evankroske** [comment]
I don't think that the benefits of posting reminders to appeals-devops while the banner is up outweigh the cost to implement and maintain the feature:
1. If we need to leave the banner up for more than three hours, the reminder would be noise.
1. If we forget to disable the banner, someone will probably tell us.
1. If we forget to disable the banner, people will still be able to do their work.

**Comment by amprokop** [comment]
Sounds good, we can forget the job then

**Comment by amprokop** [comment]
Feel free to edit the Acceptance Criteria to remove it
