### ISSUE TITLE
Certification | move logic associated with certification.start! to the StartCertificationJob

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2707]
Once we enable v2 everywhere, we should move logic that's just used to start certifications to the StartCertificationJob.

## AC
- All the same data should show up when starting a certification (no visible change)

**Comment by kierachell** [comment]
### So...uh... what am I doing here...

**Comment by amprokop** [comment]
@kierachell — if you could just run a quick check for a regression, that'd be great!

**Comment by kierachell** [comment]
### Why are document dates not detected from VBMS after I upload them?
![dates](https://user-images.githubusercontent.com/18075411/32077282-dd5bfb7a-ba70-11e7-98d0-9fb72fd6d444.gif)
