### ISSUE TITLE
Share perf analysis logic across all apps

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2708]
Reader supports showing wasted React renders, such as:

![image](https://user-images.githubusercontent.com/829827/28542979-45c9178a-708c-11e7-9111-39452d76fb36.png)

We would like to extend this functionality to be available across all apps. The other apps will probably not have nearly as much use for it, but we might as well make it available.

## AC
I can go to any React app in Caseflow and do the following:

1. Hit `alt+p`.
1. Observe the message "Started React perf measurements" in the console
1. Take some actions in the app
1. Hit `alt+p`.
1. Observe that render information is printed to the console.

**Comment by kierachell** [comment]
**PASSED**


<img width="1180" alt="screen shot 2017-07-25 at 2 58 02 pm" src="https://user-images.githubusercontent.com/18075411/28588809-c0575d00-7149-11e7-9334-09c0df5859bb.png">
