### ISSUE TITLE
Issue tags can't be created in Reader

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#2712]
Issue tags can't be created in Reader. It looks like the document controller is returning documents without a tags[] object. When the reducer is updating the tags object, it's pushing to an undefined object.

* Select a document without any tags
* Click on the document type link to get to the pdf view
* **added by @nickheiner** Refresh the page
* Add a new tag
* Notice the error

<img width="927" alt="screen shot 2017-07-24 at 7 58 48 pm" src="https://user-images.githubusercontent.com/1976755/28553255-b60a7a0a-70c0-11e7-9316-f76f20a852d6.png">

# AC
1. Verify the single page version of Reader is removed.
1. Verify opening a document in a new tab, opens another full instance of the SPA.
1. Verify you are able to add a tag using the above steps.

**Comment by NickHeiner** [comment]
[Relevant Slack conversation](https://dsva.slack.com/archives/C4N3QTLT1/p1501180016435529):

![image](https://user-images.githubusercontent.com/829827/28688182-05a03774-72df-11e7-80f7-60058a902c5d.png)

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Reader
2. Open a document that doesn't have any issue tags
3. Open Inspector for the browser  
4. Open the Console tab
5. Create an issue tag for the document
6. Verify that no errors are triggered 

Screenshots: 
![issuetags](https://user-images.githubusercontent.com/23038505/29223744-a96ee122-7e95-11e7-9954-ce6096b56e07.gif)

**Comment by NickHeiner** [comment]
@astewarttistatech those are not the right validation steps. I can follow the validation steps listed here and follow the gif, and even before the bugfix was merged (at `f8501b5e~1`), I do not reproduce the issue.

The key problem was opening the doc in "single document mode". That's the point of refreshing the page in the repro steps listed in the issue description: 

> * Select a document without any tags
> * Click on the document type link to get to the pdf view
> * **added by @nickheiner** Refresh the page
> * Add a new tag
> * Notice the error

We need to specifically see that "single document mode" has been removed to validate that this bug  is fixed. 

Please feel free to reach out to myself or @mdbenjam if you need additional help. :smile:

**Comment by astewarttistatech** [comment]
Revalidated on 8/14/17

**PASSED** 

Env: UAT
Browser: Chrome

Steps to Validate:

1. Access Reader
2. Open a document that doesn't have any issue tags
3. Open that document in a new tab, click the "open in new tab" icon next to the Document Type on the top of the PDF viewer.
4. In the new tab with the document open, open Inspector for the browser
5. Open the Console tab
6. Create an issue tag for the document
7. Verify that no errors are triggered

Screenshots: 
![readerdoctab](https://user-images.githubusercontent.com/23038505/29280538-9fc7fb26-80e9-11e7-977a-14270fcc2e53.gif)
