### ISSUE TITLE
Work Assignments | Changing worker numbers deletes tasks/claims

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2719]
# Description
When a Manager edits number of Workers,
sometimes Tasks and Claims can disappear/act weird in the UI

## Reproduction Steps

**Scenario 1 -**

1. Assign Tasks to workers and lock in the numbers
1. Reduce amount of people working today
1. Notice the amount of claims in queue decrease

**Scenario 1 -**

1. Have a worker start their tasks
1. As a Manager reduce a worker's quota below what they've done already
1. Note that they get a `-1` in tasks remaining

**Scenario 1 -**

1. Assign 0 claims to first few workers cause they're lazy/sick
1. Lock in quotas for other workers
1. Reduce amount of workers
1. Watch the number in queue disappear

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Quota below completed]_**
<img width="1128" alt="screen shot 2017-07-25 at 4 11 43 pm" src="https://user-images.githubusercontent.com/18075411/28592098-00bed4c0-7156-11e7-9b3a-a1863bf96d59.png">

**_Scenario 1 - [Goes to 0]_**
![goestozero](https://user-images.githubusercontent.com/18075411/28592129-0cacdd72-7156-11e7-9515-c7bb8202888a.gif)

# Related Issues

**_Engineering_**
#1564

**Comment by nolawi** [comment]
this should be closed @kierachell I think

**Comment by kierachell** [comment]
### Not quite:

- Have 1+ tasks and 2 users
- Lock user1 with 0 tasks
- Add user3
- Lock user2 with 0 tasks
- Observe user3 have the 2 tasks
- remove user 3
- observe tasks disappear

![fun_times](https://user-images.githubusercontent.com/18075411/32255147-53a7a96e-be7c-11e7-8e26-227b9dcdb200.gif)
