### ISSUE TITLE
Memory Leak? | Look into reports of a memory leak

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2722]
https://github.com/department-of-veterans-affairs/appeals-support/issues/211

**Comment by kierachell** [comment]
I suspect it's related to PDF workers going haywire with all the documents.
- crashes my VM (windows)
- crashes my real Mac

- Basically browsing between documents generates a weird thread snowball
<img width="628" alt="screen shot 2017-07-26 at 7 24 05 pm" src="https://user-images.githubusercontent.com/18075411/28647927-347a8772-7238-11e7-9234-1068c8f8fe07.png">

- Here's a snapshot of just a minute browsing between documents:
<img width="1438" alt="screen shot 2017-07-26 at 7 28 38 pm" src="https://user-images.githubusercontent.com/18075411/28648015-b701958c-7238-11e7-8315-662d6f2fd12e.png">

**Comment by mogrenAtWork** [comment]
Mark probably did the same work when he first started looking into this but here's what I did + found:
- I checked heap allocation on documents list for appeal with 400 docs
     - Even though we make requests to retrieve all of the documents  in the Documents List page, we're not storing these in the array. Instead, we're letting Chrome cache these on the disk.
- I recorded a performance profile of opening a document and clicking 'Next' to cycle documents for 65 seconds
     - There are peaks in memory + CPU usage if clicking through them quickly. The pdf-workers build up but eventually will dwindle down to 3 pdf-workers. It's an expensive operation to start + stop pdf-workers/threads and it takes a little time to close them, which causes the build-up. I'm wondering if we can re-use the same workers when loading documents
-  Through all of this, I watched the macOs activity monitor to make sure memory wasn’t spiking and it held steady ~300MB. I opened documents in 7 tabs concurrently as well and memory usage held steady.

Next steps:
- We should request the specs of the VA computers that are having issues as well as the Chrome version number

**Comment by kierachell** [comment]
### Reproducible steps:

- open a 1 page document
- wait for it to start rendering
- Try to navigate to another page
- see the page lock up for a second
- Open a 99 page document
- Try to navigate away when it start rendering
- Wait for a long time

**Comment by amprokop** [comment]
I just opened an appeal with 523 documents, then browsed around for 20 or so minutes. I would press the right arrow 100-200 times, then wait for it to catch up, then press the left arrow 100-200 times. After doing this a few times, my whole machine locked up and I needed to do a hard reset.

![image](https://user-images.githubusercontent.com/3781835/29676043-ef354a0a-88c4-11e7-99b1-842243def5c7.png)

**Comment by mdbenjam** [comment]
This may not be fixed. But we have made some improvements. I'd like to know if you can still easily cause it to crash.

**Comment by kierachell** [comment]
**PASSED**

Side effect logged in another issue

![noload](https://user-images.githubusercontent.com/18075411/29922944-ae8a3f22-8e25-11e7-8aa6-c138a3507478.gif)
<img width="958" alt="screen shot 2017-08-31 at 8 22 47 am" src="https://user-images.githubusercontent.com/18075411/29922942-ae858f36-8e25-11e7-8b28-6e9b13b3ebe6.png">
<img width="991" alt="screen shot 2017-08-31 at 8 22 54 am" src="https://user-images.githubusercontent.com/18075411/29922943-ae85e88c-8e25-11e7-9628-260d67d85e04.png">
