### ISSUE TITLE
[Dispatch Refactor] Refactor EstablishClaimEmail.jsx 

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2723]
This ticket is part in a series to refactor Dispatch with the broad goals of 1) reducing the number of lines in EstablishClaim.jsx, 2) Removing React state from Dispatch (moving it to redux), 3) Moving methods into utility functions where possible to be more easily unit tested

#### Acceptance Criteria
- Move EstablishClaimEmail submit down a level from EstablishClaim to EstablishClaimEmail
- Move all related utility functions to our /utils/index file
- Move toggle button state to Redux

- The code touched/moved should only be related to special issues where an email is sent. Though 1 non-email case should also be tested
- The email text is unrelated to the VACOLS note. We only do emailing when we can't route via VBMS or VACOLS. So you _either_ get the email page (special issue full grants) *or* you'd get the VACOLS diary note page. That said, submitting a vacols diary note should still be verified
- The logic related when the email page has not been touched. But it's the same in which it will show up for "unhandled special issues". 
- Sorry for lack of clarity, this means the loading spinner on the email page's submit button has been moved to Redux. So you'd just want to verify the button does spin while submit is occuring

**Comment by kierachell** [comment]
So in the spirit of not repeating the https://github.com/department-of-veterans-affairs/caseflow/issues/2292 snafu:
- Should I validate that _all_ SIC are routed properly based on their Tiers?
- Or does this only related to cases where there is an email to be sent?
- When should the Email page _not_ appear?
- Does "move toggle button to Redux" I will see its action in the Redux tools?

**Comment by joofsh** [comment]
- The code touched/moved should only be related to special issues where an email is sent. Though 1 non-email case should also be tested
- The email text is unrelated to the VACOLS note. We only do emailing when we can't route via VBMS or VACOLS. So you _either_ get the email page (special issue full grants) *or* you'd get the VACOLS diary note page. That said, submitting a vacols diary note should still be verified
- The logic related when the email page has not been touched. But it's the same in which it will show up for "unhandled special issues". 
- Sorry for lack of clarity, this means the loading spinner on the email page's submit button has been moved to Redux. So you'd just want to verify the button does spin while submit is occuring

**Comment by joofsh** [comment]
And more broadly, our test coverage for Dispatch is pretty decent. I would not expect a bug to surface from refactoring in general. #2292 occurred, in part, because it's related to the integration part of the code that we _can't_ test in our current setup. So with each refactor it's probably worth specifically verifying the VACOLS note looks right, and that a real EP can be created

**Comment by kierachell** [comment]
Blocked right now because we can't even make EPs in UAT or get veteran info in Preprod.

VBMS knows.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate:
Scenario #1:  
1. Access Dispatch as a caseworker
2. Using a full grant, select a third teir SIC 
3. Navigate to the Route Claim: Email page
4. Validate the page, appears where appropriate in the expected path

Screenshots:
![emaildispatch](https://user-images.githubusercontent.com/23038505/28923297-866e795a-782b-11e7-8ede-f2750f6f00c2.png)
