### ISSUE TITLE
Analytics | Add expand comments button

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2724]
We currently don't have an analytics event for the expand individual document's comments button.

![](https://user-images.githubusercontent.com/829827/28596355-17c05300-7166-11e7-90c9-e55a7f978eaf.png)

# AC
1. Verify when clicking on toggle button for a single document's comment that we fire an analytics event.

**Comment by kierachell** [comment]
**PASSED**

<img width="679" alt="screen shot 2017-08-10 at 3 41 17 pm" src="https://user-images.githubusercontent.com/18075411/29188815-67bcc252-7de2-11e7-904e-d5e3048f41b8.png">
