### ISSUE TITLE
Hearing model: implement vacols_attr_accessor for attributes stored in memory

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#2725]
AC:

Hearing model: in-memory attributes should be loaded from Vacols

**Comment by kierachell** [comment]
- When are they in memory?
- What attributes?
- When are they loaded from VACOLS?
- Are they lazy loaded or together?
- Does Status API load them?
- Does loading an Appeal load them?
- Is there a curl/http call to make to trigger that with certain parameters?

**Comment by aroltsch** [comment]
I am going to close this as this ticket will be validated with other tickets.
