### ISSUE TITLE
Demo | eFolder | All Demo users have no documents in their eFolders

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#2727]
**Description:** 
Currently, if you access eFolder in the Demo environment and use any of the "Demo" users they all return no documents in the eFolder. 

**Expected:** Demo users, "DEMO1, DEMO2, DEMO3, and DEMO4" should all have documents unless otherwise indicated. 

Found in: Demo
Browser: IE, FF, and Chrome

Steps to Recreate: 
1. Access eFolder in Demo
2. Enter "DEMO1" as a efolder to search
3. Verify that the search returns "no documents" for that efolder. 

**Screenshots:**
![efolderdemo](https://user-images.githubusercontent.com/23038505/28632820-c37d2404-71ff-11e7-9314-4b6c0c4c8096.gif)

**Comment by kierachell** [comment]
wrong repo
