### ISSUE TITLE
Replace sidekiq-cron

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2728]
Sidekiq-cron has been too unreliable. We need to find a replacement.

**Comment by evankroske** [comment]
How about `cron`? We would need to extract our jobs into their own programs, but that seems like a benefit to me. Separating our jobs would make them more readable and thus more maintainable

**Comment by askldjd** [comment]
I have a few questions cron's availability and reliability.

 - Where do you run it? If you run it in the app instance, it must be done in one of the machine. Do you need leader election?
 - What happens if the cron instance goes down? Who provision this?

**Comment by askldjd** [comment]
So there are two issues I see:
 1. How to make sure the job actually starts?
 1. How to make sure the job retries on failure?

For the first issue, we could use AWS Cloudwatch to trigger an AWS Lambda task. The lambda task just runs the sidekiq job. This combo is essentially same as Jenkins, except it is highly available and reliable. 

For the second issue, I think we need to fix our Sidekiq job to retry properly. Sidekiq is supposed to be able to handle this. Our job might be misconfigured.
