### ISSUE TITLE
Update Certification to use updated layout CSS

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2730]
This came up during a code search:
<img width="530" alt="screen shot 2017-07-26 at 1 24 03 pm" src="https://user-images.githubusercontent.com/1053255/28634828-78ee17f2-7206-11e7-8e44-fa548ae2a891.png">
The classes should be `cf-actions` and `cf-app-width`

**For Context**

"cf--alt" was for the alternate template which has now been out-phased. "cf-app-width" replaces the functionality. Overall updating of css classes.

**Comment by slj** [comment]
Solution in action:
![fix-cert-class-use](https://user-images.githubusercontent.com/1053255/28637726-8c6b56dc-7210-11e7-8776-f8e6fe70e6a9.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Env: Local
Browsers: FF, Chrome, IE

Steps for Validation: 
1. Access Certification
2. Go through the happy path and sad path
3. Notice any CSS issues with the UI (none)
4. Go into the source code for the certifications folder to see if there are any "cf--alt" remaining within the code of that folder. 
5. Check the merge file to see if all "cf--alt" has been changed to "cf" to indicate the change in the css classes. 

Screenshots: 
<img width="1122" alt="screen shot 2017-07-31 at 11 30 43 am" src="https://user-images.githubusercontent.com/23038505/28785392-43e7b414-75e4-11e7-86d1-cd7af5de293c.png">
<img width="1177" alt="screen shot 2017-07-31 at 11 30 58 am" src="https://user-images.githubusercontent.com/23038505/28785391-43e3601c-75e4-11e7-9186-922a42d7bfae.png">
