### ISSUE TITLE
Dispatch Stale Element Test Failure

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2734]
![image](https://user-images.githubusercontent.com/4306128/28674135-82965452-72b2-11e7-9942-e46cd5db4a7a.png)

**Comment by kierachell** [comment]
**PASSED**

master build passed, I'm sure we will know within minutes if it's actually fixed.
![Uploading Screen Shot 2017-08-01 at 1.49.35 PM.png…]()
