### ISSUE TITLE
Create End Product | Missing RO70 Station

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2736]
# Description
When we get an appeal from RO70.
creating an EP for it that will go to its station of jurisdiction.

## Reproduction Steps

**Scenario 1 -**

1. Get a claim from RO70
1. Try to create an EP that goes to RO
1. Get error because Station is `nil`

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/323/

**Comment by nolawi** [comment]
@kierachell how does one get a claim from an RO70. ?

**Comment by nolawi** [comment]
[bfregoff: "DSUSER",](https://github.com/department-of-veterans-affairs/caseflow/blob/edc20c71b877a95739efe28d6df8b8ad4c86c1c4/spec/services/appeals_repository_spec.rb#L44)

 [station-codes](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Station%20Codes.csv)

**Comment by kierachell** [comment]
**PASSED**

Made one yesterday with VBMS team! :D

**Comment by nolawi** [comment]
cool it works.. wasn't able to test
