### ISSUE TITLE
Create admin page for viewing FeatureToggles & out of service status

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2737]
Create a simple admin page so non-engineers can know the status of certain features and out of service apps

#### Acceptance Criteria
- Page should only be accessible by `System Admin`
- Page should be viewable even if app is "out of service"
- Page should show a read-only view of all feature toggles and their details
  -  Show if the feature toggle is enabled/disabled
  - Show if it is specifically enabled for any specific users or ROs
- Page should show a read-only view of our "out of service" flag. Is the application up right now?
- Page should use simple caseflow-common styling

**Comment by laurjpeterson** [comment]
Old, and I don't think relevant enough for us to keep open. Also, the out of service section of this ticket has been solved by Statuspage
