### ISSUE TITLE
[V2] Remove copy about updating POA address

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#2739]
### Story

As a Caseflow Certification V2 user on the Confirm Case Details page, I want to be confident that V2 has updated the POA type in VACOLS. I do not want to be given instructions about updating POA address in VACOLS if it is optional.

### AC
On the Confirm Case Details page:
- When the user selects "None of the above" in response to the 2nd question on the page, and selects "Attorney", "Agent", or "Other", remove this sentence: "Since you selected [Attorney/Agent/Other], make sure you update the representative’s name and address information in VACOLS before continuing." The sentence "Caseflow will update the representative type in VACOLS." should remain.
- When the user selects "None of the above" in response to the 2nd question on the page, and selects "Service organization" and then "Unlisted Service Organization", and enters in the name of the unlisted service org, remove the sentence  "Since you selected [Unlisted Service Organization], make sure you update the representative’s name and address information in VACOLS before continuing." and replace it with "Caseflow will update the representative type and name in VACOLS."
- When the user selects "None of the above" in response to the 2nd question, selects "Service organization", but no address is found, display the sentence: ""Great! Caseflow will update the representative type and name information for the selected service organization in VACOLS." and remove the sentence "After this appeal is certified in Caseflow, the representative’s address
will need to be updated in VACOLS."
- Keep this sentence everywhere it appears: "Caseflow will update the representative type in VACOLS."
- When Caseflow cannot detect the POA's address, remove this sentence: "Caseflow could not find an address for the representative in VBMS. Update the representative’s address in VACOLS before continuing." and replace it with "Caseflow will update the representative type in VACOLS with information from VBMS."
    - This occurs when VBMS is selected as the correct source of POA but the address cannot be found, or when a Service Organization is selected but an address cannot be found.  

### Mocks

The below mocks show examples of what the Confirm Case Details page looks like with the copy changes noted above. Ignore the purple boxes; they are for the Invision prototype.
 
If Attorney is selected (same sentence should appear if Agent or Other is selected):
![poa 3 attorney](https://user-images.githubusercontent.com/1178390/28687992-55d9a776-72de-11e7-8b65-3bab43d7bdb5.png)

If address cannot be found in VBMS: 
![poa 3 step 3](https://user-images.githubusercontent.com/1178390/28687999-5c36fd44-72de-11e7-8add-341a11e47986.png)

If address cannot be found for a Service organization.
![poa 3 unlisted](https://user-images.githubusercontent.com/1178390/28688002-603b6a2e-72de-11e7-8454-9a59429e9e32.png)

**Comment by nemodjuric** [comment]
@shellicious There's nothing about this, but wanted to double check - do you still want to keep:
"Great! Caseflow will update the representative type and name
             information for the selected service organization in VACOLS. After
             this appeal is certified in Caseflow, the representative’s address
             will need to be updated in VACOLS."

**Comment by shellicious** [comment]
Good catch @nemodjuric! That sentence should be: "Great! Caseflow will update the representative type and name information for the selective service organization in VACOLS." Adding this copy change to the AC.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Recreate: 
1. Access Certification V2 with an appeal that is ready to be certified
2. Go through the scenarios in the AC 
3. Validate the copy on the pages, matches what is in the AC and mocks. 

Screenshots: 
![confirmdeets1](https://user-images.githubusercontent.com/23038505/28882666-eb967632-7779-11e7-9b03-a473ef132f5c.png)
![confirmdeets2](https://user-images.githubusercontent.com/23038505/28882665-eb94bad6-7779-11e7-9c26-53fb2d32fd3a.png)
![confirmdeets3](https://user-images.githubusercontent.com/23038505/28882667-eb976ee8-7779-11e7-8caa-447b90bfa202.png)
