### ISSUE TITLE
Reader | Add footer

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2740]
## Description
Reader needs a footer so that we have a place for a link where users can send us feedback.

## AC 
- [ ] Verify that there is a footer that follows the [style guide footer](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#layout).
- [ ] Verify that the Send feedback link opens to feedback form.

## Mock up 

![image](https://user-images.githubusercontent.com/13420618/28687874-f719538a-72dd-11e7-9c9d-78d6d01c2839.png)

**Comment by kierachell** [comment]
### Awkward:

![iamokwiththis](https://user-images.githubusercontent.com/18075411/30835512-7b745234-a226-11e7-9876-6e9fdf52a966.gif)


but i am sure support team is ok with it

**Comment by mmlumba** [comment]
@kierachell which environment/browser was this in?

**Comment by kierachell** [comment]
I guess we don't have one in preprod.... awkward...
