### ISSUE TITLE
Add employee name/initials to each claim on the missing Decisions page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2741]
Rolandus would like to see which employee outcoded each claim on the Missing Decisions page. 

Add a column for the employee name/initials to each claim on the missing Decisions page. This pulls directly from a VACOLS field which indicates who outcoded the case at Dispatch.

**Comment by nolawi** [comment]
<img width="1257" alt="screen shot 2017-07-27 at 3 28 36 pm" src="https://user-images.githubusercontent.com/1745984/28688582-589eb80a-72e0-11e7-95bd-3958bcb1120e.png">

**Comment by nolawi** [comment]
@lakohl Can we the exact text for the fifth column. I am not sure if we have just the initial.? Will check.

**Comment by lakohl** [comment]
Sadly, I don't have access to VACOLS. Pehaps @sharonwarner or @cmgiven can provide an example from VACOLS

**Comment by nolawi** [comment]
right, what did you want the column header to say. 'Employee'?

**Comment by lakohl** [comment]
How about 'Outcoded By'?

**Comment by cmgiven** [comment]
`FOLDER.TIOCUSER` is the field from VACOLS that we want to show. If we join on `STAFF.STAFKEY` we can get the first and last name (`STAFF.SNAMEF` and `STAFF.SNAMEL`), instead of the VACOLS user name.

**Comment by astewarttistatech** [comment]
@aroltsch In the process of uploading missing decisions

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Create a task in Dispatch
2. Change the attributes of that task in rails console (UAT) making the date created over the amount of days needed to be a "Missing Decision". 
3. Access the Missing Decisions page as a manager in Dispatch
4. Validate that the Missing Decision has a name and initials associated with it. 

Screenshots: 
<img width="1286" alt="screen shot 2017-08-14 at 1 58 21 pm" src="https://user-images.githubusercontent.com/23038505/29284422-aff2ac6c-80f8-11e7-845f-fcd9d004cce7.png">
