### ISSUE TITLE
Style guide | Fix Footer bug

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2743]
## Description
The footer in style guide under the layout section is sad :(

![image](https://user-images.githubusercontent.com/13420618/28688392-c1fb2834-72df-11e7-8184-df5375618046.png)

## AC
- [ ] Fix the footer in the layout section so that the digital service and send feedback links are in one line
 
![image](https://user-images.githubusercontent.com/13420618/28688701-bd975884-72e0-11e7-8a4f-5e7a8cc09243.png)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Style Guide
2. Navigate to Layouts section
3. Validate the footer section against the mocks and AC. 

Screenshots: 
<img width="1246" alt="screen shot 2017-07-31 at 8 07 55 am" src="https://user-images.githubusercontent.com/23038505/28777305-94c5cb6c-75c8-11e7-9262-6448bd532147.png">
