### ISSUE TITLE
Scroll to top of Hearing Worksheet

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2744]
Currently, when the user navigates to the Daily Docket and Hearing Worksheet, they land where they were  located on the previous page.  

The user should be at the top of the page when landing on the Daily Docket and Hearing Worksheet pages

AC
- When loading Daily Docket page, the user should be at the top of the page.
- When loading Hearing Worksheet pages, the user should be at the top of the page.

**Comment by laurjpeterson** [comment]
FYI @lakohl @annienguyenUSDS

**Comment by joofsh** [comment]
Handling scroll with react router:

https://reacttraining.com/react-router/web/guides/scroll-restoration

**Comment by nolawi** [comment]
![giphy](https://user-images.githubusercontent.com/1745984/28787581-bd4d7dd8-75ea-11e7-8654-d3c8b92d9697.gif)
@joofsh

**Comment by nolawi** [comment]
might have to take this out of the react-router 
https://github.com/ReactTraining/react-router/issues/3956 location.key is not preserved as of v4 react router

 working on another solution.

**Comment by nolawi** [comment]
@joofsh fyi https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md 

I don't know how we would attach it to `history` if we needed to with react router.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Select a docket and verify that you land at the top of the page
3. Select an appellant
4. Verify that the page loads you at the top of it. 

Screenshots: 
![hearingpages](https://user-images.githubusercontent.com/23038505/29028442-58979b18-7b52-11e7-9822-0c1514d170df.gif)
