### ISSUE TITLE
Document Viewer | Doc type edit option

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2745]
## Description
We've heard from many users that Document types may be wrong and we want to allow users to edit and update document type in VBMS through reader.

## AC
- [ ] Verify that users can go into edit mode by clicking the "edit" link next to document type
- [ ] Verify that we are pulling documents list from VBMS api and populating it in our dropdown
- [ ] Verify that users can click the arrow and see document types in dropdown 
- [ ] Verify the dropdown works as a type ahead so that users can search for document types and select their option
- [ ] Verify that users can opt out by clicking cancel or save any changes by clicking save
- [ ] Please take out semicolon after Document type now that edit is next to it :)

## Mockup 

![image](https://user-images.githubusercontent.com/13420618/28690561-9e3bf4b6-72e7-11e7-9575-d09de766d9ef.png)

![image](https://user-images.githubusercontent.com/13420618/28690571-a73c6438-72e7-11e7-9028-5779242e38b3.png)

![image](https://user-images.githubusercontent.com/13420618/28690646-f0695e22-72e7-11e7-937d-93d4d65fcdd0.png)

## Related

https://github.com/department-of-veterans-affairs/caseflow/issues/1997

**Comment by abbyraskinUSDS** [comment]
Moving this note over from  1997:

Some of these document types are getting long so consider the following:

- [ ] Character limit 
- [ ] Edit link
- [ ] Typeahead

![image](https://user-images.githubusercontent.com/13420618/28480361-453fc3aa-6e2e-11e7-8bc1-772815a39956.png)

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
