### ISSUE TITLE
Update User Permissions for Hearing Prep

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2747]
As a Hearing Prep user, I need access to nagvigate to Reader, so that I can review a Veteran's eFolder while I prep a hearing

AC
- Verify that a user whose CSS_ID has the Role (Function) of  "Hearing prep", they can launch Reader.

**Comment by astewarttistatech** [comment]
AC is written incorrectly, please indicate if this is css_id with the hearings role only or a system admin.

**Comment by nikitarockz** [comment]
I updated the AC to reflect @astewarttistatech request.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Log into Hearings in a enabled role css_id 
2. Access hearings/dockets
3. Navigate to Reader
4. Verify that Reader appears and not an error page for access. 

Screenshots: 
![hearingreaderstuff](https://user-images.githubusercontent.com/23038505/29042987-430e7ea8-7b87-11e7-8ab3-84038de67e07.gif)
