### ISSUE TITLE
Add button to access Reader

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2748]
Add button to bottom of Hearing Worksheet page to allow users to navigate to Reader

Mock:
- https://va-gov.invisionapp.com/d/main/#/console/11372263/240352628/preview

AC
- 'Review eFolder' button at bottom of Hearing Worksheet

**Comment by sharonwarner** [comment]
For now, the link doesn't need to go anywhere. I'll update that in another issue.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Select a docket
3. Navigate to the hearing worksheet
4. Verify at the bottom of the page there is a button, right-aligned that says 'Review eFolder'

Screenshots: 
<img width="1255" alt="screen shot 2017-08-03 at 9 58 26 am" src="https://user-images.githubusercontent.com/23038505/28925334-976c98de-7832-11e7-8caa-96b5dc485d73.png">
