### ISSUE TITLE
[Frontend] Update Saving styling

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2749]
Hearing Worksheet saving functionality on this page should be styled in the same as appears on the Daily Docket page

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Hearings 
2. From the Dockets page view the saving functionality 
3. Navigate to the Hearings Worksheet page and verify that the saving functionality mimics what is present on the Dockets page. 

Screenshots: 
![savinghearings](https://user-images.githubusercontent.com/23038505/29129240-251ce164-7cf4-11e7-9fad-66638373d662.gif)
