### ISSUE TITLE
Move Docs in eFolder

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2750]
Move the copy 'Docs in eFolder' and the [number of docs] to the space under 'Docs since Certification'.

**Mock**
<img width="882" alt="screen shot 2017-07-27 at 5 46 43 pm" src="https://user-images.githubusercontent.com/4975959/28693614-a206d49c-72f3-11e7-8fcb-984b482853e4.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="1247" alt="screen shot 2017-07-28 at 1 58 01 pm" src="https://user-images.githubusercontent.com/18075411/28730123-d65eda10-739c-11e7-93ed-dc7e86261017.png">
<img width="1232" alt="screen shot 2017-07-28 at 1 58 10 pm" src="https://user-images.githubusercontent.com/18075411/28730124-d65f8bc2-739c-11e7-9f05-731aa06d5e6d.png">
