### ISSUE TITLE
Reader | implement doc type and receipt backend changes 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2751]
## Description
We need to implement new API to connect to VBMS to update [document type](https://github.com/department-of-veterans-affairs/caseflow/issues/2745) and [receipt date](https://github.com/department-of-veterans-affairs/caseflow/issues/1997). According to the VBMS team this is possible. 

- [ ] Investigate and see if we need to be using - VBMS old or new version of APIs.
- [ ] Implement API in connect VBMS (~ 2-3 days).
- [ ] Once we have API ready in Connect VBMS, we need to integrate reader with it. 

## Technical notes
- vaReceiveDate == Receipt Date. VBMS service v1 (new service) UpdateDocument allows to update vaReceiveDate. Still investigating Doc Type.
- Regarding Doc Type, according to the VBMS team, there is metadata tag called documentTypeId that you can use during the initializeUpdate to change the documentType
```
<versionMetadata key="documentTypeId"><v5:value xmlns:v5="http://vbms.vba.va.gov/cdm/document/v5">130</v5:value></versionMetadata>
```

**Comment by abbyraskin** [comment]
Added some technical notes above.

**Comment by abbyraskinUSDS** [comment]
Closing in favor of #3490
