### ISSUE TITLE
Adobe EPM popup on user Win IE

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#276]

**Comment by paultag** [comment]
https://helpx.adobe.com/acrobat/kb/epm-support-acrobat-products.html

**Comment by paultag** [comment]
OK, we need to fail gracefully on this one

**Comment by plusjeff** [comment]
@paultag Is there a video of this happening that could be shared?

**Comment by paultag** [comment]
@plusjeff NACK; was just down with the DROs and one of them showed me this -- It's just a simple popup model from IE and the PDF is greyed out.

I'm tempted to see if going to the IE Dev tools, and changing the IE compat to the highest one it has could work. We saw someone do that with VBMS on an unrelated video call.

**Comment by paultag** [comment]
As for how to detect that; I'm not sure. I want to sit with that user tomorrow

**Comment by plusjeff** [comment]
@paultag Good to know. FWIW, we have a meta tag already that forces IE out of compatibility mode so that it renders in the newest version it can:

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/views/layouts/basic.html.erb#L4

**Comment by paultag** [comment]
Hunh. Interesting.

**Comment by paultag** [comment]
Re-assigned this to Limited Rollout

**Comment by alex** [comment]
Was this something that occured on a per-user basis, or a per-pdf basis?

**Comment by webinista** [comment]
Can we close this issue since we've switched to PDF.js?

**Comment by alex** [comment]
Yup
