### ISSUE TITLE
Add more analytics to Reader

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2761]
Some Reader events are not being captured in GA. In particular, we'd like to know how often people open docs in new tabs. 

## AC
1. Validate that GA events are fired when viewing Reader in "single document mode"
    1. Go to the claims folder
    1. Right click on a document type and choose "open in new tab"
    1. See that one (and only one) GA event is fired that looks like:
    ```
    JS Google Analytics Event
    category: Document Viewer
    action: single-document-mode
    label: undefined
    ```

1. Validate that when you are not in "single document mode", you do not see the aforementioned GA event.
1. Validate that events are fired around the keyboard shortcuts modal:
![image](https://user-images.githubusercontent.com/829827/28728541-08df9fde-7397-11e7-8aec-da5e66f9d14c.png)
    1. Opening from "View keyboard shortcuts" button:
    ```
    JS Google Analytics Event
    category: Document Viewer
    action: open-keyboard-shortcuts-modal
    label: view-shortcuts-button
    ```
    1. Closing with "esc" key or "x" button:
    ```
    JS Google Analytics Event
    category: Document Viewer
    action: close-keyboard-shortcuts-modal
    label: modal-close-handler
    ```
    1. Closing with "Thanks, got it!" button:
    ```
    JS Google Analytics Event
    category: Document Viewer
    action: close-keyboard-shortcuts-modal
    label: modal-got-it-button
    ```

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Reader
2. Go through the scenarios listed in the AC
3. In console, verify that these events are indeed firing. 

Screenshots: 
<img width="1254" alt="screen shot 2017-08-02 at 12 13 26 pm" src="https://user-images.githubusercontent.com/23038505/28883528-cd5c05c6-777c-11e7-950d-b1dbd523fe35.png">
<img width="1254" alt="screen shot 2017-08-02 at 12 16 32 pm" src="https://user-images.githubusercontent.com/23038505/28883526-cd557b5c-777c-11e7-8671-758f8ed20acd.png">
<img width="1252" alt="screen shot 2017-08-02 at 12 17 28 pm" src="https://user-images.githubusercontent.com/23038505/28883525-cd54d314-777c-11e7-95d1-3aa706414cf0.png">
<img width="1253" alt="screen shot 2017-08-02 at 12 17 49 pm" src="https://user-images.githubusercontent.com/23038505/28883527-cd5a6a2c-777c-11e7-9ff4-1dda7733a1d2.png">
