### ISSUE TITLE
Navigation | Help | Add Introduction and Training Video sections

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#2764]
As a Product Owner, I would like to have the Welcome and Training Video sections added to the page so that it is consistent with the other products' help page.

# Acceptance Criteria
1. Verify that the following two sections and their sub-copy have been created at the top of the page as the first 2 sections. (refer to mockup View 2 - **_eFolder Express Help Page sample_**):

     Section |Header|Sub-copy
     ---|---|---
     Introduction|Welcome to the Certification Help Page!|Here you will find Training Videos and FAQs for Caseflow Certification.If you need help with a topic not covered on this page, please contact the Caseflow Product Support Team by calling 1-844-876-5548. We will assist you as quickly as possible.
     Training Videos|Training Videos|Coming Soon!

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "FAQs" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the section Header "Caseflow Certification Help" has been changed to "Frequently Asked Questions".

### **_View 1:  Current Certification Help page_**
![image](https://user-images.githubusercontent.com/23063044/28724516-416434b4-7388-11e7-9445-890e5ae0f983.png)

### **_View 2:  Sample Help Page with Introduction and Video Sections added_** 
_Note:  Using eFolder Express page as an example_

![image](https://user-images.githubusercontent.com/23063044/28724350-ae74c484-7387-11e7-9067-bbd7edb525fa.png)

# Related Stories
EPIC: IP | Certification v2 | Execute Plan [#1272](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1272)

**Comment by Sjones352** [comment]
![screen shot 2017-08-28 at 1 43 53 pm](https://user-images.githubusercontent.com/23080951/29820936-2913e06a-8c94-11e7-87fb-e1ea71f8e46d.png)

**Comment by kierachell** [comment]
**PASSED**
<img width="840" alt="screen shot 2017-08-29 at 9 16 52 am" src="https://user-images.githubusercontent.com/18075411/29822823-d700802e-8c9a-11e7-8ed8-9eb804522646.png">
