### ISSUE TITLE
Style guide | Add new colors 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2767]
## Story
As a designer or developer, I want an easy way to find ALL the colors being used in our applications. 

## AC
- [ ] Add subsection `Reader Categories` under the [Colors section](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#colors) of style guide after Logos with the following four colors
  - #fdc231 Hearing
  - #5a94ec Procedural
  - #ff6868 Medical
  - #3ad2cf Certification

## Mockup

![image](https://user-images.githubusercontent.com/13420618/28729348-2a866f8e-739a-11e7-834e-3a521e535baa.png)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2752

**Comment by Sjones352** [comment]
<img width="669" alt="screen shot 2017-08-14 at 12 39 14 pm" src="https://user-images.githubusercontent.com/23080951/29281616-c18171e4-80ed-11e7-8519-50a38951e393.png">

**Comment by gnakm** [comment]
lgtm! @Sjones352

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT 
Browser: FF and Chrome 

Steps to Validate: 
1. Access Styleguide
2. Navigate to the colors section
3. Validate the new colors based on their HEX codes as well as AC and Mocks. 

Screenshots: 
<img width="1337" alt="screen shot 2017-08-16 at 8 16 37 am" src="https://user-images.githubusercontent.com/23038505/29362834-807cac1c-825b-11e7-8b06-6b6f36dc1b34.png">
