### ISSUE TITLE
Move Docs in eFolder Again

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2768]
Move Docs in eFolder. Again. We realized that the existing 'new' placement won't work well when we have to add multiple appeal streams. So we are moving it once again. Apologies.

**AC**
1. Add a single instance of Docs in eFolder left-aligned under Relevant Documents and before Appeal Stream 1.
1. Move Docs Since Certification back up to the top row of the 5th column for each Appeal Stream.
1. Ensure that the heading ' Appellant/ Veteran Information' spells 'Appellant' correctly (with 2 l's).

**Mock**
<img width="721" alt="screen shot 2017-07-28 at 2 07 31 pm" src="https://user-images.githubusercontent.com/4975959/28730520-84b3f388-739e-11e7-9936-7f2a608475fd.png">

**Comment by nolawi** [comment]
@lakohl basically u want to revert this ticket https://github.com/department-of-veterans-affairs/caseflow/issues/2750 right ?

**Comment by lakohl** [comment]
Not exactly. 'Docs in efolder' is now going to be the first item under Relevant Documents not the last item under Appellant/Veteran Information. Also, I just realized we may have spelled Appellant wrong so adding that to the AC.

**Comment by nolawi** [comment]
got it

**Comment by nolawi** [comment]
<img width="1404" alt="screen shot 2017-07-29 at 6 46 53 pm" src="https://user-images.githubusercontent.com/1745984/28749225-56b989ac-748e-11e7-8b1a-686fe5b315a9.png"> 
like this ?

**Comment by lakohl** [comment]
That is the right spot, but can you make sure that there is the same amount of padding between the line below 'Relevant Documents' and 'Docs in eFolder' as there is between the line below 'Appellant/Veteran Information' and 'Appellant Name:'? It looks too tight right now.
Also, 'Docs in eFolder' should be Regular (not bold) type. Thanks!

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Select a Docket
3. Select an appeallant
4. Navigate to the Related Documents section in the Hearing Worksheet page
5. Verify the "Docs in eFolder" section

Screenshots: 
<img width="1242" alt="screen shot 2017-08-07 at 10 06 26 am" src="https://user-images.githubusercontent.com/23038505/29030212-5047a4e8-7b58-11e7-8200-65e0e98f09c6.png">
