### ISSUE TITLE
AppealRepository | VBMS_ID not being set for certain appeals - breaks `next_assignable` Task call

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2769]
# Description
We have 433 appeals that for some reason do not have VBMS ID set for them:
```
Appeal.where(vbms_id: nil).count
   (6.3ms)  SELECT COUNT(*) FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
[2017-07-29 12:05:06 -0400]    (6.3ms)  SELECT COUNT(*) FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
=> 433
```
When EstablishClaim parses for `assignable` tasks, it finds some of them and tries to retireve the `sanitized_vbms_id`...but...there isn't one.

The Appeals above _do_ in fact have VBMS IDs of some sort in VACOLS (doesn't matter `C` or `S` or what), because it is possible to get `case_record` and `build_appeal` for each one of their respective BFKEYs with a VBMS_ID... so... for some reason VBMS_ID is not being saved in our database.

- I confirmed that `Appeal.find_or_initialize_by(vacols_id: "*****")` generates an Appeal without a `vbms_id`. This method is used for Status API via `build_appeal` method. Whereas `find_or_create` does create an Appeal object with VBMS ID and saves it to database.

## Resolution
The issue was resolved by running `Appeal.find_or_create_by_vacols_id` for each of the 433 Appeals mentioned above. I do have the original BFKEYs saved for posterity

`Appeal.for_api` serve as a cache for VACOLS/BGS, but what if it's being actively worked on? We are messing up the most relevant appeals with this error

## Questions

- what is the value of `Appeal.find_or_initialize_by(vacols_id:` vs `find_or_create_by_vacols_id`? The former does not load the VBMS ID...
- build/load methods are not saving/updating the database, why not?
- Additionally, why is VBMS ID allowed to be nil?
- `find_or_create_by_vacols_id` does seem to update the database with accurate VBMS_IDs - why is this method not used for the 433 appeals mentioned above?

## Reproduction Steps

**Scenario 1 -**

1. Look up a new Appeal that's gonna be Dispatched soon using the API
1. Go Dispatch
1. Complete a task
1. Try to move on
1. Get a template error.

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:

`ActionView::Template::Error: undefined method `gsub' for nil:NilClass`

when

```
  def sanitized_vbms_id
    numeric = vbms_id.gsub(/[^0-9]/, "")
```
 is called from

```
def any_assignable_to?(user)
      !(user.current_task(self).nil? && next_assignable.nil?)
    end
```

```
Appeal.where(vbms_id: nil).count
   (8.6ms)  SELECT COUNT(*) FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
[2017-07-29 12:09:33 -0400]    (8.6ms)  SELECT COUNT(*) FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
=> 433
```

but

```
Appeal.where(vbms_id: nil).last.case_record.bfcorlid
```
returns a proper value

```
AppealRepository.load_vacols_data
```
returns true...but that appeal still has no VBMS_ID

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/330/events/5900/

# Related Issues
**_Support_**
https://github.com/department-of-veterans-affairs/appeals-support/issues/216

**Comment by kierachell** [comment]
Triple confirmed that Status API is generating VBMS_ID-less Appeals.
There was one created around 19:16 UTC today via a Status API call.

**Comment by kierachell** [comment]
This is fucking up reader too :( ? https://github.com/department-of-veterans-affairs/caseflow/issues/2804

**Comment by joofsh** [comment]
To validate:
- Create new appeal without a vbms_id
- Call `appeal.vbms_id`
- Verify it returns a vbms_id & saves it to the database

**Comment by kierachell** [comment]
**PASSED**


## Start with
```
Appeal.where(vbms_id: nil).map(&:vacols_id)
  Appeal Load (1.3ms)  SELECT "appeals".* FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
[2017-08-02 13:17:47 -0400]   Appeal Load (1.3ms)  SELECT "appeals".* FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
=> ["2520864", "2477475", "2064592", "2606704", "1874934", "2460002", "2474762", "2515126", "2454445", "2536136", "2453517", "2510254", "2347030", "2011303", "1758232", "1966959", "1982631", "2334160", "2634139", "2346158", "2301250", "2076104", "2307020", "2112737", "2372015", "9999"]
```

## Attempt:
```
Appeal.where(vbms_id: nil).map(&:vbms_id)
```

## Saw VACOLS selects


## End with:
```
Appeal.where(vbms_id: nil).map(&:vacols_id)
  Appeal Load (0.9ms)  SELECT "appeals".* FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
[2017-08-02 13:19:01 -0400]   Appeal Load (0.9ms)  SELECT "appeals".* FROM "appeals" WHERE "appeals"."vbms_id" IS NULL
=> ["9999"]
```
