### ISSUE TITLE
Form 8 5B, 6B, 7B filled out with Form 9 date, rather than data from VACOLS

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#277]
Under Docket tab; dates box, Notification value

Not sure where in the schema that is (yet)

**Comment by paultag** [comment]
100% of test users mentioned it was wrong :(

**Comment by plusjeff** [comment]
@paultag @KHarshawat @maryannbrody @gmorgana-va : Can you ask the users where it should come from?

**Comment by paultag** [comment]
@plusjeff They mentioned the data that's under the Docket tab in VACOLS, in the Dates box, value is `Notification`

**Comment by paultag** [comment]
From Slack:

Jeff:
> Are all of the xB fields that same notification date?

Paul:
> Yep!

**Comment by paultag** [comment]
Added to our model in https://github.com/department-of-veterans-affairs/caseflow/pull/279
