### ISSUE TITLE
Reader's back button loads JSON

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#2773]
**Description:** 

If you are in Reader and use the browser's back button, the whole page starts to resemble what happens when you do the same thing in VBMS

**Expected:** Not that (see screenshot)

**Env:** UAT
**Browsers:** FF and Chrome 

**Steps to Recreate:**
1. Access Reader
2. On any page within the document viewer, use the browser's back button

**Screenshots:**
![claims folder caseflow reader](https://user-images.githubusercontent.com/23038505/28780342-5ca3ea96-75d4-11e7-822f-1e88132975ec.png)

**Notes:**
This is believed to cause exceptions in prod.
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/338/
<img width="980" alt="screen shot 2017-08-01 at 2 42 06 pm" src="https://user-images.githubusercontent.com/1596259/28841377-08556cae-76c8-11e7-8ea5-1adbabb15a1a.png">

**Comment by Sjones352** [comment]
**PASSED**

Validate Uat/ Chrome
1.  Access Reader
2. On any page within the document viewer, use the browser's back button

![reader](https://user-images.githubusercontent.com/23080951/35712891-81252362-0792-11e8-999d-58ed4d7c00d8.gif)
