### ISSUE TITLE
Fix initialize_appeal_without_lazy_load and data being passed from fakes/AppealRepository for Welcome Gate

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#2774]
```
    def initialize_appeal_without_lazy_load(hash)
      appeal = find_or_initialize_by(vacols_id: hash[:vacols_id])

     # this line has been removed as a fix for Welcome Gate
      appeal.turn_off_lazy_loading(initial_values: hash)
      appeal
    end
```

**Comment by kierachell** [comment]
related? https://github.com/department-of-veterans-affairs/caseflow/issues/2804

**Comment by mogrenAtWork** [comment]
@kierachell this has the same acceptance criteria as #2804

**Comment by kierachell** [comment]
you now why :D

**Comment by kierachell** [comment]
**PASSED**

Got to Welcome Gate...no errors at last!
<img width="1124" alt="screen shot 2017-08-09 at 12 57 26 pm" src="https://user-images.githubusercontent.com/18075411/29133695-4f003cd4-7d02-11e7-813a-0d96e9a6159c.png">
