### ISSUE TITLE
Style Guide | Moving from displaying "required" to "optional"

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2776]
## Description
As a designer and engineer, I want to know what the best practices for what required fields should look like. What we've discovered is that most of the fields are required and the "required" red text is jarring when it's being repeated multiple times on a page. 

## AC

- [ ] Change subsection title **Text Input Error** to **Text Input Requirement and Error**
- [ ] Change the Text Input copy to the one below: 

In most cases, Caseflow form fields are required on a page. The form instructions should say "Please fill out all fields" and non-required fields should have (optional) after the field label. 

When a required label is necessary, the text label should have a required text in `secondary` right-aligned with the text input box. 

## Related
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/252

**Comment by jimruggiero** [comment]
@carodew - moving to your design backlog

**Comment by alisan16** [comment]
Closing as this is now obsolete.
