### ISSUE TITLE
Welcome Gate | Consistent button widths 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2779]
## Description
The button widths look very different on the welcome page. We want things to look more consistent without having to change our style guide button styling. 

## AC
- Change `New` button label to `Start case`

## Mockup

![image](https://user-images.githubusercontent.com/13420618/30662610-a64fdb78-9e15-11e7-9073-321b492503ec.png)

**Comment by abbyraskin** [comment]
@gnakm does this look right to you?

**Comment by gnakm** [comment]
lgtm! After this, we should brainstorm style guide buttons.

**Comment by abbyraskinUSDS** [comment]
@gnakm could you weigh in on priority/relevance here? i know Mark had some concerns about inconsistency with styleguide, but I don't think we made a concrete decision.

**Comment by abbyraskinUSDS** [comment]
Not fixing - closing.
