### ISSUE TITLE
Add missing ROs to caseflow popdown menu

### ISSUE THREAD

**Issue by joduinn** [department-of-veterans-affairs/caseflow#278]
While debugging with @shanear earlier this week, we found the list of ROs used in caseflow are different to the list provided by Jed in a report to John. As users are not able to manually type in ROs into the popdown field, possible this may cause some users to back out of using caseflow if their location is not there?

Two step process to fix: 
1) rework the list in regional_office.rb to be sorted by RO##.  This will make it easier to later tell what has actually changed.
2) compare both lists and insert new/missing ROs.

**Comment by joduinn** [comment]
[snip]
1) rework the list in regional_office.rb to be sorted by RO##. This will make it easier to later tell what has actually changed.
[snip]
This step1 was done last week as part of PR #279 and has been landed.

**Comment by joduinn** [comment]
[snip]
 2) compare both lists and insert new/missing ROs.
[snip]
This step2 was done as part of PR #284 last night and landed by @paultag just now.

**Comment by joduinn** [comment]
@shanear when you get a gap-in-time, can you/we look at the popdown menu to see if it shows the new/full list of ROs?

**Comment by joduinn** [comment]
Also, just emailed Jed to see if there is anything else that needs to be done on his side to enable those new ROs to see/use caseflow.

**Comment by joduinn** [comment]
1) Jed confirmed that all ROs are enabled for caseflow. This was true on 21apr, and he's been doing this for each new RO created since then.

2) @shanear will deploy the updated code to production AnyDayNow (tm) - in between other work - and update this bug with timestamp, so we can compare with caseflow usage patterns.

**Comment by KHarshawat** [comment]
@cmgiven this is an example of why we'd want to know which ROs are actively using CF Certification.

**Comment by shanear** [comment]
The RO list is current and up to date. Closing
