### ISSUE TITLE
Refactor Reader Analytics

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2782]
[From Slack](https://dsva.slack.com/archives/C4N3QTLT1/p1501265112448431):

![image](https://user-images.githubusercontent.com/829827/28795400-b95118e4-7607-11e7-8c8b-fbeff589f207.png)

## Acceptance Criteria
Validate that nothing that could be PII is logged. For instance, we should not be logging the text of issues, comments, or searches.

Validate that events follow this pattern:
* Category = the page the user is on, like "Document Viewer" or "Claims Folder"
* Action = the thing the user did, like "open-accordion". 
* Label = Optionally, additional information about the event. This could be "visible-ui" or "keyboard-shortcut", to identify how the event occurred. Or it could be "procedural" or "medical", for instance, indicating which category was clicked.

Validate that all actions are styled with `dash-case`.
 
### Events
The following events should trigger a GA event to fire, with sensible "Category", "Action", and "Label" fields. For instance, validate that the "Category" field always matches the page the user is on.

- [x] Typing in the search bar
- [x] Clearing the search contents
- [x] Opening and closing the dropdown filter on the document list (filtering by categories or issue tags)
- [x] Filtering the document list by category
- [x] Filtering the document list by issue tag
- [x] Clearing all filters for the document list
- [x] Clearing all tag filters for the document list
- [x] Clearing all category filters for the document list
- [x] Switching between "documents" and "comments" mode in the document list
- [x] Changing the sort direction on the document list
- [x] Starting to edit a comment
- [x] Opening the modal to delete a comment
- [x] Closing the modal to delete a comment
- [x] Clicking a comment to select it
- [x] Deleting a comment
- [x] Dragging and dropping a comment to move it
- [x] Starting to edit a comment
- [x] Hitting "cancel" while editing a comment
- [x] Typing in the edit field for a comment
- [x] Removing all content in the edit field for a comment, thereby triggering the delete modal
- [x] Hitting "save" to save edited comment content
- [x] Jumping to a page in the doc
- [x] Starting to place a comment
- [x] Stopping placing a comment, either by:
    * Hitting `esc`
    * Going to a different document
    * Clicking on the page outside of the document
- [x] On the document viewer, hiding or showing the side menu

**Comment by NickHeiner** [comment]
I just merged a change so that analytics will be sent for real, instead of the fake console logging. To verify that events are being sent, look at the network traffic:


![image](https://user-images.githubusercontent.com/829827/28940121-9e21d944-7861-11e7-84d7-5ab33a6ef425.png)

**Comment by astewarttistatech** [comment]
**FAILED**

@NickHeiner Events are not firing anywhere in the network console for any of the actions in the Events list. Please see below.

![analyticsrefactor](https://user-images.githubusercontent.com/23038505/29027583-4a1b99fc-7b4f-11e7-89fe-6514ef0a7e44.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome

Steps to Validate: 
1. Access Reader
2. Go through each Event scenario with the network tab open
3. Verify the events are firing

Screenshots:
![reader analytics](https://user-images.githubusercontent.com/23038505/29076980-09679fa6-7c25-11e7-81a3-9e2bd0c25284.gif)
![reader analytics2](https://user-images.githubusercontent.com/23038505/29076988-09965904-7c25-11e7-8aec-a80a8d8fcace.gif)
![reader analytics3](https://user-images.githubusercontent.com/23038505/29076983-096ebe26-7c25-11e7-8ce9-6933020dce59.gif)
![reader analytics4](https://user-images.githubusercontent.com/23038505/29076981-09691a3e-7c25-11e7-925a-9c8f7d1ac870.gif)
