### ISSUE TITLE
Reader | Make New Tabs Great Again

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2789]
When opening a document in a new tab we've done some hack-y work to avoid having to make a request to VACOLS and VBMS to load all the necessary data. Instead we've been passing the required metadata in the URL. Then on the backend we check to see if that metadata is passed, if it is, we just use that, otherwise we trigger a reload. In this view we also disable the main document list page since it we don't have the data to display it.

There are some problems with this approach.
1) If you click on a link to a document the metadata appears in the URL, which means on a refresh you'll get the single document view.
1) As we add more metadata, we don't want to keep putting metadata into the URL.

Once we integrate with the eFolder endpoint we should be able to make these queries faster, and be able to open new full fledged tabs quickly.

**Comment by mdbenjam** [comment]
@abbyraskinUSDS Are there any concerns with how we deal with opening docs in new tabs? If not we can close this.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
