### ISSUE TITLE
Document Viewer | Error message when claims folder detail fails

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2792]
## Story 
There are 2 different types of error/ latency feedback we should show when there is a delay retrieving the claims folder detail. 

## AC

- [ ] Add a horizontal like between receipt date and VACOLS information.
- [ ] Show the following errors for each situation:

1.  **Scenario 1 -** Currently, it is faster to retrieve the API for documents list than the VACOLs claims detail information. When there we still cannot retrieve the claims folder details 0-30 seconds. 
![image](https://user-images.githubusercontent.com/13420618/28833359-1a1385ae-76ad-11e7-9825-2883e879085d.png)

     - [ ] Show the word "**_Loading claims folder details..._**" ibold + italicized followed by the button spinner when there is a few second glitch/ delay to retrieve claims folder information
     - [ ] [Loading Button spinner ](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#loading_buttons)

2. **Scenario 2** - When there we still cannot retrieve the claims folder details after 30 seconds. 
![image](https://user-images.githubusercontent.com/13420618/28833501-84dc9ac4-76ad-11e7-9970-839c4b7d042a.png)

     - [ ] Title: Unable to retrieve claims folder details | Body copy: Caseflow is experiencing technical difficulties right now. Please refresh this page or try again later. | Hyperlink refresh this page to refresh page
     - [ ] [Alert Error status](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#alerts)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2675
https://github.com/department-of-veterans-affairs/caseflow/issues/2795

**Comment by astewarttistatech** [comment]
Current View: 

![readermenu1](https://user-images.githubusercontent.com/23038505/29171050-1dbea2bc-7da9-11e7-82e9-6bddeedd9677.gif)

**Comment by kierachell** [comment]
# The `!` is missing
<img width="428" alt="screen shot 2017-08-10 at 3 42 19 pm" src="https://user-images.githubusercontent.com/18075411/29188878-97ab862e-7de2-11e7-8bd3-ec2aef9721ab.png">

**Comment by gnakm** [comment]
@kierachell I made an exception for no spinner in this one because the grey in the spinner is the same color as menu background color and don't want to change what's been standardized. 

@tejans24 You are missing the ! icon.

**Comment by tejans24** [comment]
I am reusing the alert component. That should show up automatically. This is working locally for me. Are there any errors in the network tab?

**Comment by kierachell** [comment]
**PASSED**

<img width="412" alt="screen shot 2017-08-11 at 11 11 48 am" src="https://user-images.githubusercontent.com/18075411/29219423-fa2b2c48-7e85-11e7-8d14-e8ca87dae7d6.png">
