### ISSUE TITLE
Style guide | Small loader

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2795]
## Description
As a designers and developer, I want to know what a small loading indicator ought to look and function across Caseflow applications.

## AC
- [ ] Add a section titled "Small Loader" between Loader and Loader buttons 
- [ ] Loading default message on style guide should say **_Loading..._** in font-weight 700, italicized and in 1.9 rem. 
- [ ] Use spinner from Loader button and change size to be 19 x 19px

## Mockup 
![image](https://user-images.githubusercontent.com/13420618/28837551-2d2061ae-76bb-11e7-8e78-bbf8e3cc590f.png)

## Copy

The small loading indicator can be used when information is still being pulled for a specific section on a page. Designers are responsible to indicate what the message should say and which application logo to use in the acceptance criteria.

**Comment by Sjones352** [comment]
<img width="740" alt="screen shot 2017-08-16 at 3 54 47 pm" src="https://user-images.githubusercontent.com/23080951/29382653-44b1f5e4-829b-11e7-9fcf-49c2770a6a1e.png">

**Comment by gnakm** [comment]
@Sjones352 👍

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome and FF

Steps to Validate: 
1. Access Style Guide
2. Navigate to the Small Loader section
3. Validate the behavior and text against mocks and AC

Screenshots: 
<img width="1306" alt="screen shot 2017-08-23 at 9 57 07 am" src="https://user-images.githubusercontent.com/23038505/29619645-96210bf6-87e9-11e7-850a-142b57f391bc.png">
