### ISSUE TITLE
Document List | Fixed spacing for filtered message

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2799]
## Description
Currently, the filtered and search message is not fixed and is pushing down the document list, which looks weird and feels jarring.

https://files.slack.com/files-pri/T03FECE8V-F6GN8PN4C/bouncy_house.gif

## AC
- [ ] Make sure that the documents list is fixed and stays in the same place whether there is or isn't a filtered message. 
- [ ] Make sure that there are 20px space between search and filter message and filter message and document list header (measure from top of filter icon).

## Mockup
![image](https://user-images.githubusercontent.com/13420618/28843452-39abcf30-76cf-11e7-8528-6468668e9ed4.png)

![image](https://user-images.githubusercontent.com/13420618/28843593-bec6d8d6-76cf-11e7-939d-617b10b72a6f.png)

## Note for developer
Please assign ticket back to me  to check just in case I don't give the go 👌

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate: 
1. Access Reader's Document List
2. Create a filter message by filtering categories
3. Check the spacing
4. Clear filters, verify no spacing changed. 

Screenshots: 
<img width="1255" alt="screen shot 2017-10-18 at 11 50 07 am" src="https://user-images.githubusercontent.com/23038505/31728711-05f3a384-b3fb-11e7-94bf-70f448a0a155.png">
![Uploading Screen Shot 2017-10-18 at 11.51.49 AM.png…]()
