### ISSUE TITLE
Document List | Text selection in the table rolls over to another comment

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2801]
# Description
When selecting text in the Issues column,
for some reason the selection spills over into the header of the other columns...
kinda weird.

## Reproduction Steps

**Scenario 1 -**

1. Go to Document List
1. Double click Docket Number or some other field
1. See selection spill over to another column
1. Be forced to reselect the text.
1. Be sad.

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [fur the lulz]_**
![selecttext](https://user-images.githubusercontent.com/18075411/28846740-8c2e2bc6-76da-11e7-8d62-6d35e51189fc.gif)

**Comment by mdbenjam** [comment]
I think this is pretty standard browser functionality.
