### ISSUE TITLE
Document View | PDF Header looks a bit weird in IE

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2807]
# Description
When, someday, we support IE, might wanna fix that:
- Zoom `+` and `-` don't show up
- Back to documents button has a weird box next to it
- Document is truncated on the whole page so there's never a chance to see the whole string

## Reproduction Steps

**Scenario 1 -**

1. Go to Reader using IE
1. If it doesn't crash, open a document view
1. Try to zoom
1. Be sad.
1. Try to find Document type if it's long
1. Be sad.

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod
## Screenshots
**_Scenario 1 - [IE buttons]_**
![reader_ie](https://user-images.githubusercontent.com/18075411/28876047-d2426952-7765-11e7-8dd8-ab59613a9d4d.PNG)

**_Scenario 1 - [Document type truncated everywhere]_**
<img width="1071" alt="screen shot 2017-08-02 at 9 16 30 am" src="https://user-images.githubusercontent.com/18075411/28876095-f2e05854-7765-11e7-8078-e534a431d007.png">

**Comment by mdbenjam** [comment]
We've decided not to try and support IE. Closing in favor of #4133
