### ISSUE TITLE
eFolder Integration | HTTPI not communicating between Caseflow <-> eFolder

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2808]
# Description
This is to enable the last bit of Caseflow <-> eFolder connection

- Currently Caseflow is required to use revproxy to talk to eFolder: https://github.com/department-of-veterans-affairs/appeals-deployment/issues/732 so it would be nice to fix that in addition to the following
- HTTPI is not using the right SSL format: 
![image 1](https://user-images.githubusercontent.com/18075411/28876536-88089bf2-7767-11e7-8a53-4ccf9d32e789.png)

```
HTTPI GET request to efolder.cf.uat.ds.va.gov (httpclient)
HTTPI::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

## Reproduction Steps

**Scenario 1 -**

1. Go to rails console on a server and `FeatureToggle.enable!(:efolder_docs_api)`
1. Validate that https://github.com/department-of-veterans-affairs/caseflow/issues/2338#issuecomment-319533313 works
1. Validate that accessing DocumentList in Reader shows a list of newly loaded documents
1. Validate that Document Viewer in Reader shows PDFs
1. Validate that eFolder responds to api calls from Caseflow for following features:
  - https://github.com/department-of-veterans-affairs/caseflow/issues/2339
  - https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/505
  - https://github.com/department-of-veterans-affairs/caseflow/issues/2340
1. Perform exploratory testing to see if empty strings, empty tokens, invalid numbers might be passed at any point

# Related Issues

**_Engineering_**

**Comment by kierachell** [comment]
### Working so far!
```
EFolderService.fetch_documents_for(a, u)                                                                                                                                                   STARTED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files                                                                                                                                [2017-08-02 19:24:38 -0400] STARTED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files                                                                                                    D, [2017-08-02T19:24:38.023278 #31607] DEBUG -- : HTTPI GET request to efolder.cf.uat.ds.va.gov (httpclient)                                                                                                FINISHED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files:   0.020000   0.000000   0.020000 ( 43.034305)                                                                                                                                                                                                                                                                                            [2017-08-02 19:25:21 -0400] FINISHED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files:   0.020000   0.000000   0.020000 ( 43.034305)                                                                                                                                                                                                                                                                # of Documents retrieved from efolder: 343                                                                                                                                                                  [2017-08-02 19:25:21 -0400] # of Documents retrieved from efolder: 343
```

**Comment by kierachell** [comment]
### 60+ second timeouts: related to https://github.com/department-of-veterans-affairs/caseflow/pull/2834
- If I go more than 500 documents: the time out is 60s:
```
EFolderService.fetch_documents_for(a, u)
STARTED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files
[2017-08-02 19:35:50 -0400] STARTED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files
D, [2017-08-02T19:35:50.744121 #31607] DEBUG -- : HTTPI GET request to efolder.cf.uat.ds.va.gov (httpclient)
FINISHED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files:   0.010000   0.010000   0.020000 ( 59.269636)

[2017-08-02 19:36:50 -0400] FINISHED eFolder GET request to https://efolder.cf.uat.ds.va.gov/api/v1/files:   0.010000   0.010000   0.020000 ( 59.269636)

eFolder HTTP status code: 504 for appeal: #<Appeal:0x0055e5cc1887a8>.
[2017-08-02 19:36:50 -0400] eFolder HTTP status code: 504 for appeal: #<Appeal:0x0055e5cc1887a8>.
Caseflow::Error::DocumentRetrievalError: Caseflow::Error::DocumentRetrievalError
```
VMBS_ID: 500501028
Document count: 525

- Note that if new API ever comes along (DocumentSeriesBlah) then the requests will become EVEN LONGER... so.... yeah...
- However, Retrieve job might mitigate that
- Still... 60s is not gonna be enough


### Document ID comes back as nil?
```
#<Document id: nil, vbms_document_id: "{E39E9C3B-0ECD-4AAC-BF6C-A4F3594CD9BB}", category_procedural: nil, category_medical: nil, category_other: nil>, #<Document id: nil, vbms_document_id: "{1734B160-11AF-4C9A-9EE3-C87D2AC50A47}", category_procedural: nil, category_medical: nil, category_other: nil>
```

### The FeatureToggle for API is enabled globally for Caseflow, but in eFolder it is limited by user

```
Processing by Api::V1::FilesController#index as */*                                                                                                                                                dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-04561b79bd7613ec8-172.30.70.7 [efolder.cf.uat.ds.va.gov] [2f57710a-a368-4e4d-b32f-2763784e9353] [172.30.70.7] [2017-08-02 19:55:57 -0400]   User Load (1.6ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CF_SCOTTY_317"], ["station_id", "317"]]                        dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-04561b79bd7613ec8-172.30.70.7 [efolder.cf.uat.ds.va.gov] [2f57710a-a368-4e4d-b32f-2763784e9353] [172.30.70.7] [2017-08-02 19:55:57 -0400]   Download Load (1.5ms)  SELECT  "downloads".* FROM "downloads" WHERE "downloads"."file_number" = $1 AND "downloads"."user_id" = 14  ORDER BY "downloads"."id" DESC LIMIT 1  [["file_number", "9239
09440"]]                                                                                                                                                                                                    dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-04561b79bd7613ec8-172.30.70.7 [efolder.cf.uat.ds.va.gov] [2f57710a-a368-4e4d-b32f-2763784e9353] [172.30.70.7] [2017-08-02 19:55:57 -0400]    (1.4ms)  BEGIN
dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-04561b79bd7613ec8-172.30.70.7 [efolder.cf.uat.ds.va.gov] [2f57710a-a368-4e4d-b32f-2763784e9353] [172.30.70.7] [2017-08-02 19:55:57 -0400]   SQL (1.5ms)  INSERT INTO "downloads" ("file_number", "created_at", "updated_at", "lock_version") VALUES ($1, $2, $3, $4) RETURNING "id"  [["file_number", "923909440"], ["created_at", "2017-08-02 23:55:57.041785"], ["updated_at", "2017-08-02 23:55:57.041785"], ["lock_version", 0]]                                                                                                                     dsva-appeals-efolder-uat/opt/efolder-express/src/log/efolder-express.out i-04561b79bd7613ec8-172.30.70.7 [efolder.cf.uat.ds.va.gov] [2f57710a-a368-4e4d-b32f-2763784e9353] [172.30.70.7] [2017-08-02 19:55:57 -0400]    (3.6ms)  COMMIT
```
The user above does not have the API `reader_api` FeatureToggled but Caseflow can still get documents for him/her?

**Comment by mdbenjam** [comment]
# 60 second timeout
I'll look into it more. Maybe there is something that's taking too long on the eFolder side. Since I don't think the API takes that long. Even VBMS hasn't been THAT slow for Reader.

# Document ID comes back as nil?
This document id is the id of the local record. It doesn't have one yet because when you call it through `fetch_documents_for` it's calling `new` without a `save`. There will be an id when it's saved.

# Feature toggle
Shouldn't be a problem. I don't think we need to gate this by user.

# Wrong VBMS ID
This should be fixed. I don't think eFolder should freak out. Maybe it should return an error. I'll think about it.

# Document endpoint
It looks like you didn't pass a document id. Was that a call made from the frontend?

# Caching documents
Document lists are cached per user because of some restrictions with eFolder's architecture. I want to change this in the future. But the documents themselves should only be stored once in S3.

**Comment by mogrenAtWork** [comment]
Re: Document ID comes back as nil?
I don't think any changes here are necessary. Document IDs are returned by the reader/documents endpoint.

Re: Document endpoint
This is because the [`content_url`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/document.rb#L180) of the document isn't loading the [`efolder_id`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/document.rb#L79)k

I'd be curious if this is because the back button was hit or we're loading the documents again from somewhere and this `efolder_id` isn't stored in redux?

**Comment by kierachell** [comment]
## Retrieve Job not passing User.css_id whe eFolder service is enabled?
```
request.auth.ssl.ca_cert_file = ENV["SSL_CERT_FILE"]

    headers["AUTHORIZATION"] = "Token token=#{efolder_key}"
    headers["CSS-ID"] = user.css_id.to_s
    headers["STATION-ID"] = user.station_id.to_s
    request.headers = headers
```

causes:
```
NoMethodError

undefined method `css_id' for nil:NilClass
```

**Comment by mogrenAtWork** [comment]
Fixing the batch job issue with #2338

**Comment by mdbenjam** [comment]
So we've addressed the timeout (we were using the wrong eFolder API in UAT). The document id being nil is not a bug. The feature toggle has been turned on for all reader users now. I created #2872 to address sending bad VBMS ids. We've fixed calling the wrong documents endpoint. The problem with caching in S3 is a more long term problem that I'll be writing a tech spec about.

**Comment by kierachell** [comment]
**PASSED**
- Document list endpoint is working
- Fetch document endpoint is working
- Documents are saved to S3
- Redundant calls are being addressed
- FeatureToggle addressed
