### ISSUE TITLE
Add "None" as an option for 8A?

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#281]
Caseflow does not have an option in the representative field to choose none.  So I picked other, and put none as the name of organization, and N/A as the name of the representative.  It would work better if an option to choose was none for representative

**Comment by shanear** [comment]
@KHarshawat what do you think?

**Comment by KHarshawat** [comment]
Assigning to @lakohl for her thoughts and design.

**Comment by shellicious** [comment]
Closing this as it covers the same problem as #295
