### ISSUE TITLE
Daily Docket | Integrate Daily Docket frontend hearing save with backend

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2813]
Using the new saving component, connect the save triggers to an API request to the backend. This ticket ties together the frontend & backend for the Daily Docket page

#### Acceptance Criteria
- The relevant saving mechanism described [here](https://github.com/department-of-veterans-affairs/caseflow/issues/2475) triggers an API request to `PUT /hearings/:hearing_id`
- All hearing fields displayed on this page should be included & received by the backend
- These fields should correctly be saved to VACOLS as described [here](https://github.com/department-of-veterans-affairs/caseflow/issues/2221)
- Only trigger saves for records that have the `editing` flag set to true. E.g. we don't want to trigger API calls for hearing records we know did not update

**Comment by kierachell** [comment]
#### Updating notes:
<img width="977" alt="screen shot 2017-09-27 at 9 23 07 am" src="https://user-images.githubusercontent.com/18075411/30915747-b51a16d2-a365-11e7-85ad-755c77cce8ef.png">

```
Started PATCH "/hearings/369" for 127.0.0.1 at 2017-09-27 09:23:21 -0400                                                         dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0ba64ac0778f9e22c-172.30.66.162 [appeals.cf.preprod.ds.va.gov] [687aea69-fa80-4a4e-987c-296f110d4863] [17
2.30.66.162] [CF_SCOTTY_397   caseflow@va.gov] [2017-09-27 09:23:21 -0400] Processing by HearingsController#update as JSON                                                                                  dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0ba64ac0778f9e22c-172.30.66.162 [appeals.cf.preprod.ds.va.gov] [687aea69-fa80-4a4e-987c-296f110d4863] [172.30.66.162] [CF_SCOTTY_397   caseflow@va.gov] [2017-09-27 09:23:21 -0400]   Parameters: {"hearing"=>{"id"=>369, "user_id"=>20, "appeal_id"=>3103, "vacols_id"=>"67939", "witness"=>nil, "contentions"=>nil,
 "evidence"=>nil, "comments_for_attorney"=>nil, "date"=>"2017-10-02T00:00:00.000-04:00", "request_type"=>"CO", "disposition"=>nil, "aod"=>nil, "transcript_requested"=>nil, "hold_open"=>nil, "notes"=>"COPY OF TRANSCRIPT REQUESTED. NOW and NOW", "add_on"=>nil, "master_record"=>false, "appellant_last_first_mi"=>nil, "appellant_city"=>"APO", "appellant_state"=>"AE", "representative_name"=>nil, "veteran_age"=>61, "veteran_name"=>"LEAVITT, SAMUEL, P", "regional_office_name"=>"Pittsburgh Foreign Cases, PA", "venue"=>nil, "vbms_id"=>"552045042S", "edited"=>true}, "id"=>"369"}
```

- But not in VACOLS :(

<img width="292" alt="screen shot 2017-09-27 at 9 34 04 am" src="https://user-images.githubusercontent.com/18075411/30916294-0c9bc3be-a367-11e7-805e-be739d017cff.png">

**Comment by aroltsch** [comment]
@kierachell please re-test.

**Comment by kierachell** [comment]
AOD is sent as `grant` and expected as `granted`

**Comment by kierachell** [comment]
**PASSED**
<img width="108" alt="screen shot 2017-09-28 at 4 50 27 pm" src="https://user-images.githubusercontent.com/18075411/30990081-f5e595e8-a46d-11e7-84b1-452b95b1ed14.png">
<img width="212" alt="screen shot 2017-09-28 at 4 50 43 pm" src="https://user-images.githubusercontent.com/18075411/30990084-f5e707f2-a46d-11e7-86ca-15322d0f8aa4.png">
<img width="55" alt="screen shot 2017-09-28 at 4 51 12 pm" src="https://user-images.githubusercontent.com/18075411/30990085-f5e86e30-a46d-11e7-8b32-e611af8477b0.png">
<img width="764" alt="screen shot 2017-09-28 at 4 51 52 pm" src="https://user-images.githubusercontent.com/18075411/30990086-f5e8c790-a46d-11e7-9d88-0c4edc7f3b0d.png">
<img width="143" alt="screen shot 2017-09-28 at 4 52 46 pm" src="https://user-images.githubusercontent.com/18075411/30990082-f5e61324-a46d-11e7-9a98-ac565ee3a55c.png">
<img width="297" alt="screen shot 2017-09-28 at 4 54 01 pm" src="https://user-images.githubusercontent.com/18075411/30990083-f5e62a44-a46d-11e7-9761-3a527e87da64.png">
<img width="741" alt="screen shot 2017-09-28 at 4 55 34 pm" src="https://user-images.githubusercontent.com/18075411/30990087-f5ee4eb8-a46d-11e7-8043-2d54d0e50006.png">
