### ISSUE TITLE
Dispatch | Caseworker | Missing "Required" text in Email Route Claim

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#2814]
**Description**

Currently, when in Dispatch as a caseworker and have a special issue category selected, routing the claim is missing the "Required" red text that accompanies the checkbox at the bottom of the modal. 

**Expected:** There is a "Required" text there in red.  

**Reference Mocks:**
**_Scenario 1 - Route Claim - Send Email - Correct size/position - Added Requirement text_**

![image](https://cloud.githubusercontent.com/assets/13420618/23915047/48839260-08be-11e7-9b48-2a385c617c25.png)

View when checkbox is selected
![image](https://cloud.githubusercontent.com/assets/13420618/23915260/f1ab4a9a-08be-11e7-80f9-0a1b9857c15f.png)

**Env:** UAT
**Browsers:** FF and Chrome 

**Steps to Reproduce:**
1. Access Dispatch as a caseworker
2. With a full grant, select a tier 3 SIC
3. Navigate to the route claim: email page
4. Verify that there is no "Required" text in red next to the checkbox. 

**Current View:**

![emaildispatch](https://user-images.githubusercontent.com/23038505/28881617-b1b318ec-7776-11e7-8288-d0376862b0d5.png)
![routeclaim checked](https://user-images.githubusercontent.com/23038505/28881615-b13a5fc4-7776-11e7-802f-37166135f517.png)

**Comment by Sjones352** [comment]
@lakohl Currently 

<img width="1043" alt="screen shot 2017-09-14 at 2 48 39 pm" src="https://user-images.githubusercontent.com/23080951/30448219-29b41c22-995c-11e7-944e-49723cf8290a.png">

**Comment by lakohl** [comment]
Yay! Good to go.

**Comment by kierachell** [comment]
**PASSED**
<img width="1113" alt="screen shot 2017-09-16 at 4 49 19 pm" src="https://user-images.githubusercontent.com/18075411/30515919-146ab0d4-9aff-11e7-914b-cfbca9db306f.png">
