### ISSUE TITLE
[Backend/Frontend] Hearing Worksheet | Save rep name, witness, contentions, periods, evidence, comments

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2815]
#### Acceptance Criteria
- Witness, contentions, periods, evidence, comments should save to our database every 30 seconds or when the user exits the page
- Rep name should save to vacols every 30 seconds or when the user exits the page

**Comment by kierachell** [comment]
**PASSED**
![Screen Shot 2017-10-10 at 2.12.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5857efb248fc0213005d7c10/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f36b7191a37af113294f5b575ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df64ce7485ca6103064e57e2431.png)
![Screen Shot 2017-10-10 at 2.13.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5857efb248fc0213005d7c10/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f36b7191a37af113284f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df64ce7485ca6103064e1712431.png)
![Screen Shot 2017-10-10 at 2.13.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5857efb248fc0213005d7c10/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f36b7191a37af113284f5c5c5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df64ce7485ca6103064e27e2431.png)
