### ISSUE TITLE
Document list | Jump to section page numbers are not in order

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2817]
## Description
When looking at the expanded comment view you should see jump to comment links in page order. Currently the order seems random. See how the comment on page 20 comes before the comment on page 1.

![screen shot 2017-08-23 at 6 20 08 pm](https://user-images.githubusercontent.com/3885236/29641109-04bd97f0-8830-11e7-9979-48904289b102.png)

## AC
- [ ] Verify that the pages in jump to section are all in numerical order.
- [ ] Verify that the comments on the same page are in order based on their location on the page. (i.e. comments with a smaller y value should come first).

**Comment by kierachell** [comment]
**PASSED**

Woulda tried page -1, but couldn't find one

<img width="925" alt="screen shot 2017-09-12 at 2 24 15 pm" src="https://user-images.githubusercontent.com/18075411/30341988-24c2ce44-97c6-11e7-9fba-d5da145f5f3c.png">
<img width="1002" alt="screen shot 2017-09-12 at 2 24 19 pm" src="https://user-images.githubusercontent.com/18075411/30341989-24c8d55a-97c6-11e7-957e-dbc9d3401be9.png">
