### ISSUE TITLE
Document list | Text alignment adjustment 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2819]
## Description
Right now the Jump to section link and page are top-aligned with the comment box. This cosmetic change to make the texts align will make our application look less buggy :)

## AC
- [ ] Verify that Page number and jump to document link are aligned with the first line of text in the comment section (see mockup). 

## Mockups
![image](https://user-images.githubusercontent.com/13420618/28885607-7f822558-7784-11e7-8ee4-75a2f7231e58.png)

**Comment by kierachell** [comment]
**PASSED**
LGTM
<img width="641" alt="screen shot 2017-08-10 at 3 31 45 pm" src="https://user-images.githubusercontent.com/18075411/29188437-0e836250-7de1-11e7-8119-b52874b17d05.png">
