### ISSUE TITLE
[Wednesday 8/9 ~10:40am] Should we manage our own permissions?

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2821]
@kierachell @nikitarockz and I had a conversation today about the future of Caseflow permissions.

## Background 

Currently, users of Caseflow have to go through CSEM to gain "functions". 

## Current CSEM Process
1.  We need to request that the new "Function" and/or "Role" be added to CSEM.  This allows for the CSEM user to select the options from a drop down.  

2.  Supervisors at each RO with users that need access have to submit a request to their station's CSEM Initiator or ISO. This person goes into CSEM and initiates this request which then has to go through 3 levels of approval. These approvals are all done through automatic notifications from the CSEM application. Once that is done it is then implemented in CSS.

Here's a copy of the Training which was presented to PM team.  [CSEM Training Materials for BVA.pptx](https://github.com/department-of-veterans-affairs/caseflow/files/1200456/CSEM.Training.Materials.for.BVA.pptx)

## PM Team's Goal for Changing the Process
1.  Provide guidance ([Caseflow User Access Guidance](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/How%20Tos/Caseflow%20Access%20Guidance%20-%2020170711.docx)) to all CSEM users which includes CSEM Initiators, ISO Approvers, and National ISOs.

2. Provide specific Caseflow produce guidance, such as [Caseflow Reader User Access Guidance](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/How%20Tos/Caseflow%20Access%20Guidance%20-%20Reader%20-%2020170726.docx), to RO supervisors who need to request their staff to get access to a particular Caseflow product. 

3.  A CSEM user who needs to grant people access has to log into a specific station in CSEM.  Our goal is to obtain access to all Stations within CSEM using the Initiator and Approving Official CSEM roles.  This will allow us to control the entering of requests and starting the approval process.  It will still need to go through a couple more approvers but at least we will have seen it and know the permissions have been set up correctly.  We currently have been granted access to 101 which is our station.  We are waiting on approval for other stations now.  We even have the resources to carry this out.

## Potential Solutions
- Continue using CSEM.
   - Pros:
      1) we don't have to code new admin pages & manage permission rules
   - Cons:
      1)  A 3rd party (people with access to CSEM) is currently capable of giving any VA employee the "System Admin" function. This compromises the safety & security of our system, and resulted in us [disabling the System Admin function](https://github.com/department-of-veterans-affairs/caseflow/issues/2514)
      2) Gaining new CSEM functions can be slow. This has delayed product pilots & rollouts

- Take over control of granting/removing permissions for Caseflow. This would mean completely circumventing CSEM permissions. Instead we would have an admin page where we can grant users permissions as necessary. 
  - Pros:
      1) we can grant permissions as quickly as we want 
      2) we ensure that no one unintentionally gains System Admin access.
      3) This has been suggested by our COR Angela, as another IT team has chosen to go in this direction

     **_Clinician User Interface (CUI)_**
     > For internal users (within VA), CUI will use PIV/2-FA mechanism where user can sign in and request access to particular sites/roles thereafter. This is to align with VA’s initiative to make all applications 2FA compliant.
     >
     >For external users, we are planning to use another mechanism such as ID.me, details are still evolving.
    >
    >In the meantime, we are using a stop gap - user id/email and password mechanism - until both implementation (stated above) are fully functional. 
    >
    >Our stop gap solution requires that we manually stage users i.e. create user accounts based on approvals and notify users. Unfortunately, we don’t have an alternative mechanism and process such as CSEM/CSUM to control access for CUI.
  - Cons:
     1) We would need to code admin pages and permission rules. How do we give a user permissions before they've ever logged in? How can a user request new permissions from us?
     2) Start tracking user's last login (which we should be doing anyway). On login, if it's been over 90 days, strip their System Admin permission

**Comment by evankroske** [comment]
@joofsh , we might be able to avoid creating the background job by stripping the "System Admin" role when someone tries to use it after 90 days of inactivity

**Comment by joofsh** [comment]
Good catch @evankroske ! That sounds like a better way to do it. Will update the description

**Comment by kierachell** [comment]
I am 1000% for this
Caseflow:
 - deprecates old VA systems
 - runs on Sidekiq

**Comment by NickHeiner** [comment]
> Caseflow:
>  - deprecates old VA systems

Well, we're not talking about a viable way to deprecate a VA system now. We're talking about adding yet another permissions management system at the VA. Caseflow is not going to expand to replace all of CSEM. 

I am interested in hearing from people who have had to deal with CSEM, to get a sense of how much of a pain this is. Managing permissions on our own certainly seems like it could be a good idea, if the current situation is painful enough.

**Comment by kierachell** [comment]
### Current Pains:
- All of our users got `System Admin` in role for no reason whatsoever
- Many times "relevant" ISO do not know what Caseflow is or what the form means or what functions/roles/permissions are
- A simple signature takes weeks because ISO needs to feel important
- Nobody on this team can see our application in Production

### Solution:
- ISO still get to grant user-app access and feel "relevant"
- But we get to control which parts they get to access and any functionality (FeatureToggle basically does this right now anyway and no one complained)

**Comment by askldjd** [comment]
I see both side of the argument. The current ISO process is ridiculous, but at the same time, we can not replace CSEM. If we do, we are yet another lonewolf VA system in 10 years. For security purposes, I think authority of grant/revoke Caseflow should reside in VA AD.

However, I think @kierachell's hybrid solution is a good compromise for both world.

- CSEM controls who gets "Caseflow" access. It is a one-time exercise.
- Caseflow controls the feature that the user gets. Sort of what we do now, except we expand it to include Efolder, and decide who would get admin access.

This way, VA OIT retains the revoke power for any security threat. And Caseflow controls the feature level to control fine-grain rollout. If we treat Caseflow as a whole, and Reader/Dispatch/Certification/Hearing/Efolder to be an implementation detail, I don't see how we would violate the ATO.

**Comment by nikitarockz** [comment]
I have just update the description above and added what the PM team is currently doing.  

> Cons:
>       2) Gaining new CSEM functions can be slow. This has delayed product pilots & rollouts
I don't necessarily agree with the second Con. Now that I have established a relationship with the team that implements this, it really doesn't take that long.  We give them a date when to have it done, and it gets done.  They actually can do it within minutes; however, lets just say about 2 days.  The only hold up is the form 8824 which they are trying to deprecate.  They have to have everyone in CSEM.  Currently, there is only 1 station (101) that doesn't have all users in it.  Almost there.  The form really isn't a problem for us because our users don't need to use the form.
