### ISSUE TITLE
Break out certification into separate readme and add summary of Caseflow overall

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2825]
## AC
- description of the problem/product
- ways to test/enter certification
- link to it from the main readme

**Comment by astewarttistatech** [comment]
I see the PR @Sjones352  but could you put a link to the actual readme?

**Comment by Sjones352** [comment]
@astewarttistatech  Sorry screenshots
<img width="884" alt="screen shot 2017-09-26 at 10 11 02 am" src="https://user-images.githubusercontent.com/23080951/30864929-1eb76fb8-a2a3-11e7-818a-f363236febc3.png">

<img width="978" alt="screen shot 2017-09-26 at 10 11 16 am" src="https://user-images.githubusercontent.com/23080951/30864930-1ebb65be-a2a3-11e7-9d81-f041dce1832d.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate: 
1. Access Caseflow repo
2. Go to docs folder
3. Select certification.md 
4. Verify that it matches what is posted in the PR listed. 

Screenshots: 
![certificationmd](https://user-images.githubusercontent.com/23038505/30865222-00dce008-a2a4-11e7-99a2-0ed50133952a.png)
