### ISSUE TITLE
Refactor | Pdf.jsx

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2826]
The monstrosity that is PDF.jsx is due for a good ole fashion refactor. I don't want to be too prescriptive, but some thoughts:

# AC
- [ ] Verify there is a new CommentLayer component that is in charge of drawing comments and receiving clicks for placing new annotations.
- [ ] Verify there is a new PdfPage component that is in charge drawing the div/canvas that are used by PDFJS to place the images/text of the PDF. This component should also be in charge of calculating dimensions.
- [ ] Verify all normal PDF functionality still works.

**Comment by mdbenjam** [comment]
I've been using this as an omnibus ticket. That's not transparent or a good record of what is actually happening here. I'm updating the AC based on what has actually been done, moving it to in-validation, and creating new tickets here on out. @NickHeiner thanks for holding me accountable.

**Comment by kierachell** [comment]
### Is the edge of the page for placing annotation supposed to be different for mouse vs keyboard?

1. Start making annotation
1. Move the marker to the edge of the page using keyboard
1. Move it to the edge using mouse
1. Weird.

![edgelimit](https://user-images.githubusercontent.com/18075411/30406600-d9195f84-98c0-11e7-9530-5773e152531f.gif)


### Dat error message looks janky, yo
<img width="442" alt="screen shot 2017-09-13 at 8 16 18 pm" src="https://user-images.githubusercontent.com/18075411/30406622-fdb3007a-98c0-11e7-8f0f-3fa2240543b8.png">


### Editing an annotation to be blankspace... does it need to have this error?

<img width="1397" alt="screen shot 2017-09-13 at 8 16 02 pm" src="https://user-images.githubusercontent.com/18075411/30406626-05a64dc8-98c1-11e7-8277-233cee0b84f0.png">


### I don't know how I did this: why are they disappearing?

![lolwut](https://user-images.githubusercontent.com/18075411/30406723-984e60b6-98c1-11e7-9d4a-a392d0d204d9.gif)

**Comment by mdbenjam** [comment]
@kierachell I think we should make new tickets for these. None of them seem too severe.

**Comment by kierachell** [comment]
@mdbenjam I made new issues; push this into validation if you want me to re-test everything for more.

**Comment by kierachell** [comment]
**PASSED**

Extraneous issues have been captured in other tickets
