### ISSUE TITLE
Refactor | PdfSidebar.jsx

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2828]
PdfSidebar.jsx isn't too big, but it would still be nice to make it more succinct.

Move each accordion into its own component in its own file.

# AC
- [ ] Verify each accordion is defined as its own component in its own file.

**Comment by astewarttistatech** [comment]
Finding some JS errors while accessing accordions in Reader, trying to see if there is a way around them in order to validate this ticket

**Comment by astewarttistatech** [comment]
After talking to @mmlumba this ticket regards the accordions on the PDF viewer and therefore has


**PASSED**

Validated in: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Reader
2. Navigate to PDF Viewer
3. Open Elements and view each section of the accordion to see if it has its on part
4. View this in Console as well

Screenshots: 
![readeraccordions](https://user-images.githubusercontent.com/23038505/31125740-69ba803a-a817-11e7-9608-9cd20b9adb0f.gif)
