### ISSUE TITLE
Refactor | Reducer

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2829]
We have one giant global reducer. We should split this up into several smaller reducers.

# AC
- [ ] Verify the reducers is split into many logical sub-reducers.

# QA AC
- [x] Verify Reader works as expected.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated : Preprod | Chrome 

Validated via smoke test to ensure existing features were not broken by this change.
