### ISSUE TITLE
What does the BFDCERTOOL field mean?

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#283]
There was some discussion in #256 that made me wonder if we're all on the same page about what the `BRIEFF.BFDCERTOOL` field means.

In my mind, it means that Caseflow was used for a case, not that it was certified (that's the `BRIEFF.BF41STAT` field). I could be wrong here (maybe it means it was certified *with Caseflow*).

We should clarify this so that we can log, report, and use this field consistently. (i.e. maybe we should be setting it when a user tags something as not certifiable)

**Comment by alex** [comment]
Right _now_ we are using it to indicate that something was successfully certified with Caseflow. I don't know if we meant to extend it to "anything that Caseflow touches". I don't think anyone actually consumes this, so we can do what we like with it.

**Comment by KHarshawat** [comment]
We no log when something is not certified correctly using Yule Log.
