### ISSUE TITLE
Refactor | Actions

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2830]
We have one giant actions file. We should split these up into separate action files that correspond to the reducer files. See https://github.com/department-of-veterans-affairs/caseflow/issues/2829

# AC
- [x] Verify actions are split into multiple logical files.
- [x] Verify these action files correspond to the reducer files in #2829

# AC for QA
- [x] Verify everything in Reader works the way it's supposed to work

**Comment by astewarttistatech** [comment]
@mdbenjam @tejans24 Based on the AC, this seems like whoever approved the PR would have essentially validated this. Is there something you needed validated?

**Comment by astewarttistatech** [comment]
A smoke test was ran through Reader in Chrome. Everything is working as to be expected.
