### ISSUE TITLE
[Frontend] Hearing Worksheet : Persist Issues Information to redux  re-open, vha

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2838]
Hook up part of the editable fields in the Issues section on the hearing worksheet page to the Redux store

Acceptance Criteria:

- Ensure  `re-open`, and `vha` in the Issues section are initially saved to redux store on pageload.
- On user input change, update the redux store accordingly
- The fields should be saved within an appeal in the 'streams' object. The appeal number can be hardcoded.

Notes:
- You can hard code the appeal number and the issue number for now
- Do not add the other preliminary impression checkboxes to redux
- Do not send the information to the backend.
- Do not hook up any additional fields.

**Comment by nolawi** [comment]
<img width="441" alt="screen shot 2017-08-14 at 3 05 30 pm" src="https://user-images.githubusercontent.com/1745984/29287055-2f44cad2-8102-11e7-9b5e-a886d0f2494a.png">
is each box seperately true or false

**Comment by kierachell** [comment]
### I am not seeing anything loaded or changed in the Redux (actions are sent tho...so...what?)
