### ISSUE TITLE
[Frontend] Hearing Worksheet : Persist textbox input to redux

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2839]
Hook up the editable fields in the Issues section on the hearing worksheet page to the Redux store

Acceptance Criteria:
- On page load, copy initial worksheet object to the `worksheet` key in Redux
- Ensure the input in the textboxes at the bottom of the page (Contentions, Periods and circumstances of service, Evidence, Comments and special instructions to attorneys) are initially saved to redux store on pageload
- On user input change for those fields, update the redux store accordingly

Notes:

- Do not send the information to the backend.
- Do not hook up any additional fields.

**Comment by astewarttistatech** [comment]
**FAILED**

Env: UAT
Browser: Chrome 

1. Open Hearing Prep 
2. Navigate to a Hearing Worksheet
3. Check the page for the worksheet object on load for Redux
4. Check to see when text is entered into text fields that the actions get saved into the Redux store accordingly (**DOES NOT**)
5. Check to see if the Contentions, Periods and circumstances of service, Evidence, Comments and special instructions to attorneys are initially saved on page load (**DOES NOT**)

**Comment by astewarttistatech** [comment]
Due to updated AC, this ticket has **PASSED**

Additional Screenshot: 
<img width="1397" alt="screen shot 2017-08-23 at 1 47 40 pm" src="https://user-images.githubusercontent.com/23038505/29630291-b264d214-8809-11e7-8d2a-6148d4b02de1.png">
