### ISSUE TITLE
Analytics: Add user id

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2847]
If we provide GA with a user id, then it can provide [more accurate results](https://support.google.com/analytics/answer/3123663). It will also allow us to combine data we see in GA with data in our own database to get deeper insights into user behavior.

## Acceptance Criteria
See that the `uid` field of the Google Analytics request is set to the current user's ID:

![image](https://user-images.githubusercontent.com/829827/29139215-1dfb53e6-7d14-11e7-9d8b-b57e2082aeb8.png)

In the database, the value we want is the `id` column of the `users` table for the currently logged in user.

**Comment by astewarttistatech** [comment]
@NickHeiner Could you walk me through how to test this when we get back to the office?

**Comment by NickHeiner** [comment]
I've updated the ticket with AC. Sorry about omitting it originally! :smile:

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Reader with a unique css_id
2. In the Network tab of the browser's Inspector tool, look for the UID value. 
3. Perform a few tasks in the flow of reader to validate that the UID value is constant. 
4. Log out of that css_id and log back in as another css_id
5. Check the UID value in the Network tab to make sure it is a different value from the css_id that was previously logged into Reader. 

Screenshots: 
![analyticsuser](https://user-images.githubusercontent.com/23038505/29173536-9a01d90e-7db1-11e7-929b-6d222b7d10eb.gif)
