### ISSUE TITLE
Competing buttons / links on Generate screen

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#285]
Just checking which buttons should be here? Latest design I have only includes the _Can't certify_ link and _Upload and Certify_ buttons. (Ignore the error screen).
 
![screen shot 2015-12-03 at 2 57 38 pm](https://cloud.githubusercontent.com/assets/354277/11572298/77e3407e-99ce-11e5-9325-899b2344f39e.png)

**Comment by KHarshawat** [comment]
This `go back and make edits` button should only be on the preview Form 8 Screen (which I believe this is)

If it is, then it's correct, pending the feedback in #307 that "Can't certify" is a confusing label. We included this button b/c users didn't notice a clear way to revise the Form 8.

**Comment by webinista** [comment]
So

**Comment by KHarshawat** [comment]
@webinista Sorry! Should be exactly as the mock looks

`<< Go back and make edits` [Can't certify]() ------------- `Upload and Certify`
