### ISSUE TITLE
Hearing Worksheet | [Frontend] Implement appeal streams

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2851]
Update currently hardcoded appeals stream info to reference the `appeals` array returned within each hearing object.

#### Acceptance Criteria
- On the hearing worksheet, all "active appeals" (returned within the hearing object) have their document information rendered
- On the hearing worksheet, all "active appeals" (returned within the hearing object) have their issues information rendered

Note:
- The issue checkboxes should not be changed. They should continue to be stubbed out

**Comment by laurjpeterson** [comment]
Closing because captured in #3070 and #2967
