### ISSUE TITLE
What tech improvements should we prioritize?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2856]
The Foxtrot team has some bandwidth in the coming sprints and we'll be tackling some tech improvement issues overall. We need input from all the teams. Please add ideas for tech improvements to this issue. If your idea is already in the Tech Improvements column, you don't have to add it here, we'll be taking a pass through that column (but if you think it's really important, feel free to mention here anyway to make sure it doesn't get lost). We'll then prioritize them and put them in the coming sprints!

Examples:
- Refactor AppealRepository to be more testable
- Refactor the Monitor REST API to be explicit about uptime/downtime 
- Refactor Redux / React to come up with a form-building pattern that handles validation/errors/etc while minimizing boilerplate
- Audit all routes to for RESTfulness and establish patterns for app interaction
- Add Dead Man's Snitch to alert us when our jobs/backups don't run

**Comment by nolawi** [comment]
- move static assets to the react app

**Comment by joofsh** [comment]
- Add tests to `ruby-bgs` gem. Right now the gem is completely untested. It's a core dependency of all our applications, and making changes to it is risky!

**Comment by shanear** [comment]
#devops

https://github.com/department-of-veterans-affairs/appeals-deployment/issues/738

**Comment by NickHeiner** [comment]
* https://github.com/department-of-veterans-affairs/caseflow/issues/1531 or upgrade to the latest `node` / `npm`
* Consider re-architecting repo to have a cleaner separation between different apps or a better-defined contract with a core platform.
* Fix outstanding `prod-alert` errors
* Upgrade to Rails 5 (are there things that will be useful for us?)

**Comment by kierachell** [comment]
- remove old FeatureToggles that we don't need (dispatch, etc)
- remove functions for Cert v2 and v2 (they are FeatureToggles now?)

**Comment by mogrenAtWork** [comment]
I'll second some things I've seen earlier on this list and some obvious/generic improvements that may have already been checked:
- Upgrade node and rails
- Fixing outstanding prod-alerts
- Fixing skipped tests
- Adding tests to ruby-bgs
- Analyzing our worst queries and seeing if we can improve them

Some new things to investigate:
- Refactor AppealsRepository to include CaseAssignmentRepository functionality
    - CaseAssignmentRepository only pulls in assignees to appeals. We could make this cleaner by creating a relationship between User -> Appeal and updating AppealsRepository to pull in the relevant information when needed.
    - Caveat: The CaseAssignment query is a doozie and may bloat an already bloated AppealsRepository, so I can be convinced this doesn't need to be done.
- Consider improving fakes setup: 
    - We have fake repositories that are supposed to contain in-memory objects. Sometimes these objects get saved in intermediate steps in a request, so it then becomes unclear what object we're _actually_ working with when testing functionality
     -  Consider creating seeds.rb per environments with fake data that is inserted into our database and using rake to load/destroy it appropriately

**Comment by mdbenjam** [comment]
- I support refactoring the repositories to make the code testable. We should keep as little as possible  in the actual interaction with dependencies.
- An audit of all our React components. I have a lot of thoughts here and am not sure it's appropriate for this 'summer' refactor.
- I like looking at making our APIs restful
- Adding audit tables
