### ISSUE TITLE
Reader Redux is showing up everywhere

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2858]
If you open the Redux Dev Tools on any Caseflow React page, you'll see Reader's redux state:

![image](https://user-images.githubusercontent.com/829827/28980268-328b8e04-791b-11e7-84aa-13176220cdd9.png)

This is annoying to every team that is not Reader.

The problem is this line in `BaseContainer`, that gets called on every page load:

```js
import Reader from '../reader/index.jsx';
```

In `reader/index.jsx`, at the top level, we create the store:

```js
const store = createStore(
  readerReducer,
  composeEnhancers(applyMiddleware(thunk, perfLogger, reduxAnalyticsMiddleware))
);
```

So we are creating the store for every page. We should not do this.

Instead, we should have `reader/index.jsx` do what Hearings does: pass a `configureStore` method to `Provider`:

```jsx
<Provider store={configureStore(hearings)}>
```

By only creating the store within that method, we will avoid creating a store on every single page.

**Comment by amprokop** [comment]
Unfortunately, there is a strange bug in our test setup here.

```
19 09 2017 21:11:16.245:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
19 09 2017 21:11:16.253:INFO [launcher]: Launching browser Chrome with unlimited concurrency
19 09 2017 21:11:16.292:INFO [launcher]: Starting browser Chrome
19 09 2017 21:11:18.477:INFO [Chrome 55.0.2883 (Linux 0.0.0)]: Connected on socket kpxw1cfh9zIYY52TAAAA with id 80972870
19 09 2017 21:11:28.479:WARN [Chrome 55.0.2883 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 55.0.2883 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
```

The karma tests fail without any error message when we move the store creation out of the global level of the file. After a lot of trial and error, I discovered that if `DocumentsTable-test.js` is commented out fully, the tests pass. Testing this was pretty timeconsuming, since I wasn't able to replicate the failure using the karma watch task, so I had to wait ~30s for the app to recompile every time.

**Comment by amprokop** [comment]
It appears that some global behavior is happening in `DocumentsTable.jsx` that somehow interacts with the Reader store and causes silent failures.

I'm going to try two items:
- Extracting `getRowObject` into its own file 
- Commenting out the tests

**Comment by amprokop** [comment]
🤞
