### ISSUE TITLE
vbms_id is saving unsaved appeals

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#2859]
Not sure how to recreate this. Might want to skip validation and see if the Sentry alerts stop rolling in.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/340/

**Comment by shanear** [comment]
Not sure how to recreate this. Might want to skip validation and see if the Sentry alerts stop rolling in.

**Comment by kierachell** [comment]
- Just open Reader's Welcome Gate page after using Status API to generate a bunch of Appeals (some of which might be assigned to that attorney/judge).
- Do the same for Dispatch - look up a ready-to-dispatch Appeal in Status. Then try to work/assign/prepare it in Dispatch.

**Comment by kierachell** [comment]
They did not:

Starts happening now, breaks Dispatch:
https://github.com/department-of-veterans-affairs/caseflow/issues/2870

**Comment by shanear** [comment]
The linked issue is unrelated. Can you send the UAT sentry log for the breakage?

This issue hasn't recurred in prod since this code has been deployed
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/340/events/
<img width="1174" alt="screen shot 2017-08-08 at 10 27 59 am" src="https://user-images.githubusercontent.com/1596259/29076766-75489ffa-7c24-11e7-9a0e-68ca8f4a4d9f.png">

**Comment by kierachell** [comment]
Cause I haven't deployed :D
