### ISSUE TITLE
Post to appeals-devops if apps are out of service 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#2861]
Related to #2702 (its prerequisite)

Every three hours, a job should run checking the out of service status of various applications and posting to the #appeals-devops channel in Slack if apps are out of service, so we can't forget. To avoid spamming the cannel, only post if some applications are out of service.

### AC:

<img width="427" alt="screen shot 2017-08-15 at 6 28 12 am" src="https://user-images.githubusercontent.com/18075411/29312365-f0b87c2e-8182-11e7-9560-b61d92d96056.png">

### Steps:

- SSH into a UAT instance
- From the Rails console write:
`Rails.cache.write("reader_out_of_service", true)`
- Attempt to visit `/reader/appeal` and other Reader-related pages
- See `Technical Difficulties` page
- Verify in Slack that: a job should ran checking the out of service status of various applications and posting to the #appeals-devops (or #dev_null for lower environments) channel in Slack if apps are out of service,
- Repeat above steps for other applications

- To undo the `out_of_service` setting, use `Rails.cache.write("dispatch_out_of_service", false)`
- Verify that you left all the applications "in service" after testing this shit

**Comment by astewarttistatech** [comment]
Changed AC for clarity.

**Comment by astewarttistatech** [comment]
@nemodjuric  I had certification set to out of service all yesterday and monitored the #appeals-devops channel and slack and did not see any reminders. 

**FAILED**

**Comment by nemodjuric** [comment]
@astewarttistatech Validation for this issue should wait for https://github.com/department-of-veterans-affairs/caseflow/issues/2918 to be fixed.

**Comment by nemodjuric** [comment]
@astewarttistatech https://github.com/department-of-veterans-affairs/caseflow/pull/3007 unblocked this issue. It's ready for verification.

**Comment by kierachell** [comment]
**PASSED**

<img width="501" alt="screen shot 2017-08-23 at 9 02 04 am" src="https://user-images.githubusercontent.com/18075411/29617140-c9508d42-87e1-11e7-9366-0b4e7c900497.png">
