### ISSUE TITLE
StaleObjectError when hitting document endpoint

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2864]
https://sentry.uat.ds.va.gov/sentry/efolder-uat-u4/issues/361/

# AC
1. Verify when going to the single document view (opening a new tab of a document) that tags can be left.
1. Verify when going to the single document view there exists a back to all documents button, that the view is a full Reader instance and not just a single page.

**Comment by kierachell** [comment]
I need to setup a test where I hit the API and download in eFolder at the same time

**Comment by kierachell** [comment]
**PASSED**

Will recreate the issue when I can truly reproduce it.
