### ISSUE TITLE
Google Analytics: Add Page Speed Timings

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#2865]
We would like to instrument our page speed timings so we can get a sense of what our browser performance is. In the past, we've had reports of Reader being unusably slow, so we'd like to stay ahead of that going forward.

Things to instrument include:
1. How long the page takes to become initially usable
1. How long the reducer takes to process actions
1. How long React takes to update the page after a user action
1. How long API calls take
1. How long Reader takes to render a PDF, switch between pages, etc.

## AC
1. Wait until the code for this ticket is deployed to prod.
1. Go to Google Analytics
1. Limit your view to only prod traffic using the [Appeals Prod](https://analytics.google.com/analytics/web/template?uid=l16lnNdgSueJVdYZXckXTw) GA filter.
1. View the "User Timings"
1. See that HTTP request times are being tracked:

![image](https://user-images.githubusercontent.com/829827/30830763-20b31618-a213-11e7-9de9-f55825495c36.png)

**Comment by astewarttistatech** [comment]
Locked out of prod and have been trying to get my account unlocked by NSD.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in Google Analytics

Steps to Validate: 
1. Access Google Analytics (Caseflow > Appeals > All Website Data)
2. From the Nav Bar navigate Behavior > Site Speed > User Timings
3. From that view, validate that HTTP requests are included

Screenshots:
<img width="1392" alt="screen shot 2017-09-29 at 11 38 26 am" src="https://user-images.githubusercontent.com/23038505/31024080-f2303860-a50b-11e7-9589-c6473f11bacb.png">
<img width="1370" alt="screen shot 2017-09-29 at 11 45 39 am" src="https://user-images.githubusercontent.com/23038505/31024081-f23e6142-a50b-11e7-92d3-ae673eece4bd.png">
