### ISSUE TITLE
VBMSService | `fetch_documents_for` doesn't expect `current_user`

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2870]
# Description
When fetching documents for an appeal,
current user is not an expected parameter.
This causes errors.

- Can't fetch documents no more :(
- Can't create Tasks no more :(
- Can't really do much no more :(
- Smoke tests are broke

## Reproduction Steps

**Scenario 1 -**

1. Go to `admin/establish-claim`
1. Try to make a new task for an appeal
1. Fail
1. See sentry
1. Get sad

**Scenario 1 -**

1. Go to Reader
1. Have everything work
1. Scratch head...

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:

```
ArgumentError: wrong number of arguments (2 for 1)
```

Coming from:

```
def self.fetch_documents_for(appeal)
    @vbms_client ||= init_vbms_client
```

called by

```
def fetched_documents
    @fetched_documents ||= document_service.fetch_documents_for(self, RequestStore.store[:current_user])
  end
```

## Sentry:

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/363/

## Screenshots
**_Scenario 1 - [500]_**
<img width="721" alt="screen shot 2017-08-06 at 4 34 08 pm" src="https://user-images.githubusercontent.com/18075411/29006841-ad796a90-7ac5-11e7-8480-42cd6266267f.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Dispatch /test/setup (reset time and location)
2. Navigate to /admin/establish-claim
3. Create a task
4. Verify creating that task was successful

Screenshots: 
![admin establish-claim](https://user-images.githubusercontent.com/23038505/29030675-ebe59076-7b59-11e7-9031-0eebd9ab9cd7.gif)
