### ISSUE TITLE
Files Endpoint | Invalid File Number

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2872]
Currently if a bad File Number is passed to the files endpoint then a sentry error is thrown. We need to catch this error and return a bad request to the user. See: https://github.com/department-of-veterans-affairs/caseflow/issues/2808

# AC
1. When passing an invalid file number (i.e. 999) the endpoint doesn't throw an error.
1. When passing an invalid file number (i.e. 999) the endpoint returns error code 400 to indicate a bad request.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
