### ISSUE TITLE
Files Endpoint | List of files not cached within 3 hours

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2873]
Currently on UAT (not locally) the files endpoint is not properly cached. The API is supposed to look at the most recent manifest fetch time and only go to VBMS if it has been 3 hours since the last manifest was fetched. Currently it always fetches the manifest again.

# AC
1. Verify when the API is called twice within 3 hours, the second call returns immediately and does not call VBMS.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access eFolder Express
2. Search a valid eFolder
3. Go back to search and delete cache on the recently searched eFolder. 
4. Re-search that eFolder. 
5. Verify it doesn't take more than 2 seconds to download
