### ISSUE TITLE
Claims folder | Add more information to claims folder details 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2876]
## Description
Attorneys have expressed the importance of seeing the representative on their claims folder. This will be one less reason to open up VACOLS. 

## AC
- [ ] Add a section after Regional Office with title Representative and the representative below it. 

## Mockup
![image](https://user-images.githubusercontent.com/13420618/29080104-ed329c16-7c2c-11e7-937b-d8ea3d92080e.png)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2901

**Comment by abbyraskinUSDS** [comment]
I think we should verify that we want to show the VACOLS representative vs. the POA (in VBMS, from BGS)

**Comment by gnakm** [comment]
@abbyraskinUSDS let's go kindly bug a VLJ either today or Wednesday.

**Comment by abbyraskinUSDS** [comment]
Other data we might want to add to claims folder (note: some of these are stored in the corporate database, rather than VACOLS):
- Birthdate
- Dates of service
- Rep/POA
- Hearing date + judge
