### ISSUE TITLE
Reader making extra calls to document endpoint

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2881]
Because of a race condition we currently can call the documents endpoint several times in a row. Now we add a set of promises and setTimeouts to wait for the first request to finish and then use the result.

We also add a config flag to add to make local development against an efolder instance easier.

Reproduction Steps:
- Run latest master of eFolder express on localhost:4000
- Change use_efolder_locally to true in development.rb
- Go into Rails console and run FeatureToggle.enable!(:efolder_docs_api)
- Restart the server
- Look at the network tab as you navigate between documents. Ensure that each document is requested once (there will be two requests an OPTIONS one for CORS, and a GET request)
- Look at the network tab as you navigate between documents. See that each document is requested more than once

# AC
1. Verify that when navigating to a page, the document is loaded no more than once.

**Comment by kierachell** [comment]
### When switching to a new document that was not rendered before:

- If it's more than 10 documents away from current view, the new document is loaded a bunch of times still
![fastswitch](https://user-images.githubusercontent.com/18075411/29072042-1f03e768-7c14-11e7-9e13-fd58f3116dea.gif)


- There seems to be some kind of locking/delay when rendering a PDF, which bugs out the whole document loading process @tejans24 was looking into it:

- Have a large document start loading
- Note the browser lock up
- Try to navigate away
- Note the browser not respond
- After 5-10 seconds, browser moves to a new document
- Loads it up 5+ times, though
![renderlock](https://user-images.githubusercontent.com/18075411/29072168-a2fd6f8a-7c14-11e7-89d0-d9d90fdf8c53.gif)




### Single-Document view

- can't even load the document
<img width="949" alt="screen shot 2017-08-08 at 8 32 11 am" src="https://user-images.githubusercontent.com/18075411/29072039-1ae033d0-7c14-11e7-874b-a6aad0826fb7.png">

**Comment by mdbenjam** [comment]
This was fixed a while back when we removed the code on the frontend to eager load all the documents.
