### ISSUE TITLE
Add documents to the Case Summary Reader filter

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2883]
We need to add the following documents to the case_summary filter:
- "VA 21-526EZ, Fully Developed Claim (Compensation)"
- "VA 21-527EZ, Fully Developed Claim (Pension)"

## Acceptance Criteria

In the Reader Document List view, if the document is one of the types above, a case summary flag (currently yellow/gold) will appear to its left

**Comment by lakohl** [comment]
Show most recent rating decision code sheet per @abbyraskinUSDS's attorney, but all rating decision narratives?

**Comment by kierachell** [comment]
**PASSED**
<img width="1060" alt="screen shot 2017-08-31 at 8 21 04 am" src="https://user-images.githubusercontent.com/18075411/29923364-4717fee0-8e27-11e7-9418-553dda069f75.png">
