### ISSUE TITLE
[Frontend] Daily Docket: Add "Add on" checkbox

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#2884]
Daily Docket: Add "Add on" checkbox.

Description: As a judge, would need to know if case was an "add on" to the daily docket. 
AC: Show a checkbox with copy "Add on" to the right for every claim aligned below "Disposition" drop down. Be able to add check to the box similar to "Transcript Requested." See mock.

In the mock, also moved "Transcript Requested" to align below "Hold Open" drop down".
<img width="585" alt="screen shot 2017-08-07 at 5 09 59 pm" src="https://user-images.githubusercontent.com/22620270/29045937-5731ca50-7b93-11e7-849b-385f690243c0.png">

**Comment by astewarttistatech** [comment]
Because of hearing prep being down with #2473. This ticket is blocked.

**Comment by kierachell** [comment]
**PASSED**

see the ending
![changes](https://user-images.githubusercontent.com/18075411/29496486-b3dee144-85a1-11e7-841e-604f0d23ff5a.gif)
