### ISSUE TITLE
[Frontend] Hearing Worksheet: Make witness box expandable and scrollable

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2890]
As a user I would like to be able to add the name of more than one Witness in the witness box.

Use the same flexible styling (expandable vertically and scrollable) on the witness box as is used on the Notes section of the Daily Docket.

**Comment by nolawi** [comment]
<img width="1533" alt="screen shot 2017-09-05 at 9 04 45 am" src="https://user-images.githubusercontent.com/1745984/30062481-5116081a-9219-11e7-8ffa-fafb1e7d631b.png">

this looks a little weird me.

**Comment by kierachell** [comment]
@lakohl 
### Should it expand as I enter more text?
### Is there input limit validation?

![expandmepls](https://user-images.githubusercontent.com/18075411/30090416-5772aff2-9281-11e7-8f60-d24ee3c8fb6b.gif)

**Comment by lakohl** [comment]
@kierachell yes, it should automatically expand as you enter more text. Let's limit it to 5 lines of text for now.

**Comment by nolawi** [comment]
We are not doing any front end Validation, if there needs to be - there should be new ticket with details

**Comment by lakohl** [comment]
@nolawi I see the difficulty here. This ticket was created before we updated the behavior of the Notes field on the Daily Docket, and my expectation was that they would behave in the same manner - expanding as the contents of the box grows to display it at all time (not scroll). apologies, thsi id totally my fault.

How would you like to proceed? I can update the AC above, or create a new ticket.

**Comment by nolawi** [comment]
@lakohl no big deal, we can update AC - I prefer new ticket for validation stuff. But eitherway we will get it to where it needs to be

**Comment by kierachell** [comment]
**PASSED**
