### ISSUE TITLE
[Frontend] Back to Docket  on Daily docket - should say back to Upcoming Hearing Days

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2892]
AC
Link in the lower left of the Daily Docket page that allows the user to move backwards should read: 
Back to Upcoming Hearing Days (not Back to Docket).

**Comment by astewarttistatech** [comment]
Because of hearing prep being down with https://github.com/department-of-veterans-affairs/caseflow/issues/2473. This ticket is blocked.

**Comment by kierachell** [comment]
**PASSED**
<img width="469" alt="screen shot 2017-08-20 at 12 14 39 pm" src="https://user-images.githubusercontent.com/18075411/29496458-2da27ed8-85a1-11e7-9f82-08ce924eccb4.png">
