### ISSUE TITLE
Daily Docket Notes UI clean up

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2893]
1. Left align the word 'Notes' so it starts directly under the vet ID number.
1. Remove colon after 'Notes'
1. Adjust the Notes box accordingly.

Note: color going in/out is side-effect of animated GIF):
![fix-notes-ac](https://user-images.githubusercontent.com/1053255/29781004-bc1405d4-8be5-11e7-9b96-4e9333c40cdc.gif)

**Comment by slj** [comment]
@lakohl or @annienguyenUSDS is this what you're expecting?

![fix-dd-notes](https://user-images.githubusercontent.com/1053255/29370930-db7dc1a0-8274-11e7-8579-d9442254a9a2.gif)

**Comment by annienguyenUSDS** [comment]
@slj 1 & 2 looks good. I don't know what "3. Adjust Note box accordingly" since it's the UI is not responsive, it all looks a little wonky. Can you clarify a bit more if possible?

**Comment by lakohl** [comment]
Grey background seems to come and go?

**Comment by slj** [comment]
Ideally, the UI would be super responsive, but that's not the goal of this ticket.  The only thing that matters is the position of the Notes field and its associated label.  If you're happy with that I think we should get the change into the code and validated by QA.  @lakohl the actual background doesn't change - it's just a bug in the animated GIF.

**Comment by lakohl** [comment]
Sounds good! This ticket is ready for validation.

Upon further exploration, we thought the notes field should behave a bit more like the comments box in Reader, so we made new ticket for that: https://github.com/department-of-veterans-affairs/caseflow/issues/3058

**Comment by astewarttistatech** [comment]
**PASSED**

Env: Preprod
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings with a user who is an Attorney or a Judge
2. Navigate from the Upcoming Hearings page to the Hearings Worksheet page for an appellant
3. Verify that the Notes column is aligned with the Appellant column on the worksheet. 

Screenshots: 
<img width="1339" alt="screen shot 2017-08-28 at 12 18 03 pm" src="https://user-images.githubusercontent.com/23038505/29782543-fe564a88-8bea-11e7-9cd6-c6051b4a3726.png">
