### ISSUE TITLE
Open Hearing Worksheet in a different tab

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2894]
As a judge I would like to be able to view the Daily Docket and the Hearing Worksheet at the same time.

AC
1. When a Veteran ID is clicked on the Daily Docket page, open the Hearing Worksheet for that Veteran ID in a different browser tab.

**Comment by slj** [comment]
Is this a definite requirement?  If we train judges to use the browser's built-in capability to open in new tabs, then we satisfy those who prefer the two-tab workflow w/o aggravating those users who may not care for it.  Thoughts?

**Comment by mmlumba** [comment]
@joofsh Do you expect the state to persist across the two windows?

**Comment by kierachell** [comment]
**PASSED**
![tabs](https://user-images.githubusercontent.com/18075411/30483651-a0f30ffc-99f5-11e7-8a6f-8108b94cd52b.gif)
