### ISSUE TITLE
[Backend] Hearing Worksheet | Character of Service

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#2895]
We currently only pull in the veteran's branch and service dates. We'd like to also pull in character of service. 

AC:
In the rails console, when we load a veteran's military_service, it pulls in character of service.

**Comment by joofsh** [comment]
For implementation details, see the spike ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/2469

**Comment by lakohl** [comment]
This ticket looks good. I want to confirm exactly which of these fields are most valuable with a judge early next week.
```{:short_service_number=>nil,
  :service_number_fill=>nil,
  :branch_of_service=>"ARMY",
  :entered_on_duty_date=>"01012005",
  :released_active_duty_date=>"01012011",
  :separation_reason_code=>"SAT",
  :nonpay_days=>nil,
  :pay_grade=>"E1 ",
  :char_of_svc_code=>"HON"}```

**Comment by lakohl** [comment]
@joofsh @sharonwarner @kierachell 
Judges would ideally like to see the following info under Circumstances and Periods of Service.
See: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/402 for details and screenshots

- Dates of Service
- Branch
- MOS (Military Occupational Specialty - what I’ve been calling Role)
- Active Duty? vs. National Guard or Reserve
- Awards/Decorations/Honors (for combat service?)
- Location of Service (Sometimes indicated as Foreign/sea svc)
- Character of Service = Nature of Discharge (Honorable or not)

I am not certain, but don't believe that all of this exists in the VBMS sidebar. If not, is there anywhere else we can pull this info in from?

**Comment by lakohl** [comment]
Also, can you confirm which of the above are easily pulled form the VBMS sidebar?

**Comment by lakohl** [comment]
@cmgiven ^^

**Comment by sharonwarner** [comment]
![Screen Shot 2017-09-22 at 10.55.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582a398e7d9c5f1300c030ee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6456f16b7191a379ef0c2e54415f4fbc30254d58eeb9cb74fce36f34985619e8d96f0e76903818aeb18249bb01eb278b4fd7b4b98a4f92fa2137a5dad11b61435c52dcbd4f3fb29842c259f34be74d5ca6123463e570316e0a.png)

**Comment by kierachell** [comment]
Oy, this will be a pain to scrape BGS for proper data with this... 🤕

**Comment by aroltsch** [comment]
@lakohl @sharonwarner How do we want to display a character of service in the military_service? Currently we do this, for example: `ARMY 05/06/2013 - 05/07/2014, NAVY 03/04/2015 - 03/04/2017`

**Comment by aroltsch** [comment]
```ARMY 05/06/2013 - 05/07/2014, Honorable Discharge; NAVY 03/04/2015 - 03/04/2017, Honorable Discharge```

**Comment by aroltsch** [comment]
Codes we know about: ["HON", "UHC", "12D", "HVA", "DVA"]

 “HON” = Honorable, “UHC” = Under Honorable Conditions,” HVA = “Honorable for VA Purposes,” and DVA = “Dishonorable for VA Purposes.”

12D TBD

**Comment by cmgiven** [comment]
Army Regulation 135-178, Chapter 12, paragraph 12-1d, provides for separation from service for abuse of illegal drugs. That would be my guess. Perhaps there are special rules around such discharges.

**Comment by cmgiven** [comment]
(Nicholas, please forgive me for no doubt messing up the Bluebook style on that one.)

**Comment by aroltsch** [comment]
@cmgiven do you happen to know what the exact text for 12D displayed in VBMS ;) ?

**Comment by cmgiven** [comment]
¯\_(ツ)_/¯ Can't help you there.

**Comment by astewarttistatech** [comment]
Preprod is down currently:  
<img width="1405" alt="screen shot 2017-09-29 at 11 20 27 am" src="https://user-images.githubusercontent.com/23038505/31024160-2d2563b4-a50c-11e7-9982-0c138c96f608.png">

Will review once back up.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate: 
1. Access Hearings 
2. Navigate Upcoming Hearing Days > Daily Docket > Hearing Worksheet
3. Use Inspect to see the network tab while the Hearing Worksheet loads (reload the page if necessary)
4. Look for the worksheet.json
5. Verify that the military_service value has a branch of service in it along with service dates. 

Screenshots: 
<img width="1404" alt="screen shot 2017-09-29 at 1 44 58 pm" src="https://user-images.githubusercontent.com/23038505/31028697-ef121ab6-a51c-11e7-8b4e-48e8cc01e77f.png">

**Comment by kierachell** [comment]
@lakohl @aroltsch 
https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/docs/BGS_Linktest.md


Using that you can see what is available in BGS:
<img width="267" alt="screen shot 2017-09-29 at 8 24 03 pm" src="https://user-images.githubusercontent.com/18075411/31040339-47cb26a2-a554-11e7-8b1d-aac9506b8def.png">

See further discovery here:
https://dsva.slack.com/archives/C36HGTT62/p1506731272000021

**Comment by aroltsch** [comment]
```
CHARACTER_OF_SERVICE_CODES = {
    "HON" => "Honorable",
    "UHC" => "Under Honorable Conditions",
    "HVA" => "Honorable for VA Purposes",
    "DVA" => "Dishonorable for VA Purposes"
  }
```
This is what we got so far. @lakohl, who do you think can help us with the rest of the values?

**Comment by kierachell** [comment]
@aroltsch I posted all the possible values in #appeals-discovery as linked in my comment above

**Comment by sharonwarner** [comment]
12D => Dishonorable - Ch 17 Eligible
12C => Dishonorable - Not Ch 17 Eligible
OTH => Other Than Honorable
DIS => Discharge

**Comment by aroltsch** [comment]
Since `Discharge` is one of the options, we will not append `Discharge` at the end of each  military service description.

**Comment by kierachell** [comment]
**PASSED**
<img width="626" alt="screen shot 2017-10-05 at 3 17 02 pm" src="https://user-images.githubusercontent.com/18075411/31248178-f7c3e842-a9e0-11e7-8496-57d36caa60a9.png">
<img width="585" alt="screen shot 2017-10-05 at 3 20 31 pm" src="https://user-images.githubusercontent.com/18075411/31248176-f7820d50-a9e0-11e7-879b-99e254c64a6f.png">
<img width="547" alt="screen shot 2017-10-05 at 3 21 55 pm" src="https://user-images.githubusercontent.com/18075411/31248177-f7919d4c-a9e0-11e7-9133-0af359031bb2.png">
