### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2898]
There is very little information here:
<img width="836" alt="screen shot 2017-08-08 at 10 18 33 am" src="https://user-images.githubusercontent.com/3885236/29076247-f3582b74-7c22-11e7-8a43-5b9e33de384b.png">

Only two events in the last 24 hours.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/345/

**Comment by shanear** [comment]
<img width="845" alt="screen shot 2017-08-08 at 10 53 49 am" src="https://user-images.githubusercontent.com/1596259/29078284-e3fc9728-7c27-11e7-8d65-90d629226550.png">

these breadcrumbs seem legit

**Comment by amprokop** [comment]
Removing this from Foxtrot and putting it in the Whiskey queue, since the Sentry breadcrumbs seem to show that this is a Reader error
