### ISSUE TITLE
Document Viewer | Add representative field to annotation menu

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2901]
## Description
Attorneys have expressed the importance of seeing the representative on their claims folder. This will be one less reason to open up VACOLS. 

## AC
- [ ] Add a section after Regional Office with title Representative and the representative below it. 

## Mockup
![image](https://user-images.githubusercontent.com/13420618/29080278-611680fc-7c2d-11e7-91ee-180aa9b99e42.png)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2876

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
