### ISSUE TITLE
Is a directory @ rb_sysopen - /opt/caseflow-certification/src/tmp/pdfs/

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2908]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/344/

Don't know this code path, but it looks like it might be due to something that is missing a filename, so we try to write to the directory instead:

![screen shot 2017-08-08 at 2 59 21 pm](https://user-images.githubusercontent.com/3885236/29089431-321e0d16-7c4a-11e7-9412-23e1d2c071f0.png)

**Comment by amprokop** [comment]
Let's investigate this, but timebox it to ~2 hours. If we don't have an idea of what's going on here after ~2 hours, let's skip it.

**Comment by amprokop** [comment]
Actually, this has only 2 events. We haven't seen it in awhile. Let's close it.
