### ISSUE TITLE
Task::UserAlreadyHasTaskError

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2909]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/343/
Only one instance of this.

![screen shot 2017-08-08 at 3 03 12 pm](https://user-images.githubusercontent.com/3885236/29089605-c50f1570-7c4a-11e7-9333-b4a4950b6a9e.png)

**Comment by shanear** [comment]
This is an unavoidable race condition due to a click happy user I believe 😄

best we could do is rescue the error?

**Comment by sharonwarner** [comment]
Sentry link is too old :(

**Comment by mdbenjam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/343/
