### ISSUE TITLE
Unicode Data in Form 8 isn't always rendered

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#291]
Not all UTF-8 is rendered - although  the most critical ones (I tried a few diacritical marks, common ones worked), but a Chinese name in UTF-8 doesn't.

Might be worth fixing this

**Comment by webinista** [comment]
Could this be a font-related issue? Is it making it to the database as UTF-8 and just not being rendered when retrieved?

**Comment by paultag** [comment]
Yeah, sounds very likely - something is doing the ignore missing codepoints and render them as a `?` thing. Likely pdftk

**Comment by orischwartz** [comment]
![pdf char encoding](https://cloud.githubusercontent.com/assets/16327036/13649006/88e4febc-e609-11e5-87b7-fc1e016318c9.png)

**Comment by paultag** [comment]
Windows-1252 strikes again. Latin-1 is also perhaps a concern.

I have no idea how to handle that gracefully except running it through chardet
