### ISSUE TITLE
How should we handle our jobs interacting with their dependencies?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2916]
The BGS API needs `current_user` information. We're currently temporarily using `RequestStore[:current_user]` to pass it through. We had to put in a pretty messy hotfix (https://github.com/department-of-veterans-affairs/caseflow/pull/2915/files) to make cert work again, but it's probably not the cleanest way to handle passing user info to the job.

How should we best handle that?
Also, what information does the eFolder API need?

**Comment by mogrenAtWork** [comment]
Just for reference, the eFolder API needs the user's [CSS-ID and STATION-ID](https://github.com/department-of-veterans-affairs/caseflow/blob/609790f0a42ff3551b6d77a8ad84522b6133a21e/app/services/external_api/efolder_service.rb#L42) for requests to the eFolder API.

The eFolder API uses this to (there might be more to this list that I don't know about):
- [Authenticate](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/b702d08321a63c982dc0d14f4377353351ffb811/app/controllers/api/v1/application_controller.rb#L37)
    - This is used to limit the API to only Reader users, but might be overkill. We have a shared secret between Caseflow and eFolder on top of this
- [Checks to see if download manifest from VVA is enabled for user](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/jobs/download_manifest_job.rb#L7)
    - I don't have any context on why we only enable this for certain users
- [Records audit statistics to show what docs were accessed by whom](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/b702d08321a63c982dc0d14f4377353351ffb811/app/controllers/api/v1/files_controller.rb#L30)
    - This approach should be changed for the API since our audits might contain false information now that we're requesting the docs in a batch job

We use the RequestStore[:current_user] for Reader to [keep our VBMS functionality](https://github.com/department-of-veterans-affairs/caseflow/blob/609790f0a42ff3551b6d77a8ad84522b6133a21e/app/models/appeal.rb#L419) and prevent refactoring several layers of function calls.
