### ISSUE TITLE
Remove Document.fetch_content once eFolder is enabled

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2917]
Remove Document.fetch_content() once the eFolder API is being used 100% of the time.

Blocked until the eFolder API for Reader is deemed stable.

**Comment by abbyraskinUSDS** [comment]
@mdbenjam is this still relevant?

**Comment by mdbenjam** [comment]
Unfortunately other apps are still using this, but I'm not sure if this is a priority. I'm indifferent on what we do with this ticket.

**Comment by pkarman** [comment]
Efolder API is fully live. The `Document.fetch_content` method still talks directly to VBMS. Not clear to me whether it is still being used anywhere. Logging added to trace if deprecated method is still used.

**Comment by jimruggiero** [comment]
@pkarman Can you check the logs added last May and let me know if Document.fetch_content is still being used?

**Comment by pkarman** [comment]
It is being actively used. Kibana shows log calls as recently as this week.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
