### ISSUE TITLE
Sidekiq/Slack | Change the name of SLACK_DISPATCH_ALERT_URL environment variable

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#2918]
Change the name of the `SLACK_DISPATCH_ALERT_URL` environment variable since it's now being used in Dispatch and Reader,
and it's used by Certification.

**Comment by kierachell** [comment]
Retrieve job is posting under Dispatch's name
<img width="366" alt="screen shot 2017-08-15 at 8 44 47 am" src="https://user-images.githubusercontent.com/18075411/29316481-38052376-8196-11e7-97d7-92fd7e3f19c5.png">

**Comment by nemodjuric** [comment]
That is correct. Please include this one as well - ENV["SLACK_OUT_OF_SERVICE_REMINDER_URL"]
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/out_of_service_reminder_job.rb#L26

**Comment by kierachell** [comment]
Yeah, you can modify message to anything necessary: so let's stick with one ENV var:

### Actions
- Get all the Slack VARs from Caseflow and Appeals-deployment
- Rename them all to one generic SALCK_ALERT_URL or whatever
- Make sure all webhooks use just that one var

**Comment by pkarman** [comment]
not worth the effort
