### ISSUE TITLE
Hearings Worksheet: reference to classNames causing error

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#2919]
The page should not generate this error:
<img width="554" alt="screen shot 2017-08-09 at 8 54 18 am" src="https://user-images.githubusercontent.com/1053255/29122492-86ba1356-7ce0-11e7-996d-ac1dbf2b83d0.png">

**Comment by slj** [comment]
This problem is solved by using `className` instead of `classNames` - `classNames` is not needed here b/c the class is static.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Navigate to a Hearings Worksheet
3. On the Hearings Worksheet page, using the browser's "Inspect" tool, view the console and see if any errors appear on the page. 
4. Refresh the Hearings Worksheet while having the console open to double-check. 

Screenshots: 
<img width="1440" alt="screen shot 2017-08-09 at 11 21 43 am" src="https://user-images.githubusercontent.com/23038505/29129825-1392d8d4-7cf6-11e7-8a11-dbc586a8f6c4.png">
