### ISSUE TITLE
Welcome Gate | Search error: invalid veteran ID entered

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2920]
## Story
As a attorney or judge, I want to know if I entered a wrong Veteran ID in the welcome search bar. 

## AC
- [ ] When an incorrect Veteran ID is entered (one that does not actually exist), show the error message below using [style guide error alert](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#alerts)

## Mockup
![image](https://user-images.githubusercontent.com/13420618/29138381-829d9d52-7d11-11e7-8eba-8c13ec8cac25.png)
**_Notes: Use the copy below and not the one in the mock because it's low-key aggressive._** 

## Copy
Title: Veteran ID not found
Body copy: Please enter a valid Veteran ID and try again.

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2342

**Comment by abbyraskinUSDS** [comment]
@gnakm 👍 👍 👍

**Comment by mdbenjam** [comment]
@gnakm This message sounds super aggressive to me. What do you think about "Please enter a valid Veteran ID and try again."

**Comment by gnakm** [comment]
@mdbenjam Yeah that sounds less aggressive. Works for me.

**Comment by abbyraskinUSDS** [comment]
Passive aggression FTW.

**Comment by tejans24** [comment]
I'll make this change! Thanks ya'll!

**Comment by kierachell** [comment]
**PASSED**
<img width="772" alt="screen shot 2017-08-31 at 7 41 08 am" src="https://user-images.githubusercontent.com/18075411/29921906-7b1caf7a-8e21-11e7-8ac1-63e4025e5aa2.png">
<img width="790" alt="screen shot 2017-08-31 at 7 41 21 am" src="https://user-images.githubusercontent.com/18075411/29921905-7b1b284e-8e21-11e7-8d17-14a48c121bdf.png">
