### ISSUE TITLE
Welcome Gate | Search error: veteran ID has no active appeals

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2924]
## Story
As a attorney or judge, I want to know whether the veteran ID I searched for on the Welcome Gate isn't associated with any active appeals.

## AC
- [ ] Show the following alert when Veteran ID exists but doesn’t have any associated appeals
- [ ] Use [Style guide informative status alert](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#alerts) pattern 

## Mock up
![image](https://user-images.githubusercontent.com/13420618/29177403-9f7e9fd8-7dbc-11e7-93b9-8119a0342f97.png)

## Copy
Title: No appeals found
Body copy: Veteran ID [ID number] does not have any appeals.

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/2920

**Comment by gnakm** [comment]
@tejans24 Clarification needed! What exactly are the parameters of the search right now? Are we able to see only active appeals vs. appeals that have decisions.

**Comment by abbyraskinUSDS** [comment]
Deprioritized in favor of future Queue
