### ISSUE TITLE
Refactor eFolder API feature toggle code

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2926]
See Post-Mortem: https://github.com/department-of-veterans-affairs/caseflow/issues/2925

We should refactor how we look at the :efolder_docs_api Feature Toggle to prevent future errors. Each fork of the toggle should be very clear and should avoid other conditions. Specifically examine this code: https://github.com/department-of-veterans-affairs/caseflow/pull/2922/files#diff-da766db961b1ebe7e7e8de051dac4096R182

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
