### ISSUE TITLE
Document viewer | Keyboard shortcut for saving a comment

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2928]
**Story**
When writing a comment, I want a keyboard shortcut that saves my comment so I can move quickly to the next task. 

**Acceptance Criteria**
- Entering `alt+enter` on keyboard when a comment is active saves the active comment

## Related
#3083 | Add new shortcuts to modal

**Comment by abbyraskinUSDS** [comment]
Note we'll also need a story to update keyboard shortcuts menu.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: FF and Chrome 

Steps to Validate: 
1. Access a document in Reader
2. Start creating a comment
3. Before saving, select the 'alt+enter' command
4. Verify that the command used saved the comment rather then clicking the button on the right menu. 

Screenshots: 
![savereader](https://user-images.githubusercontent.com/23038505/31622731-39f45e76-b26b-11e7-8f77-ec49bf0ae53d.gif)
