### ISSUE TITLE
Some dates are getting being filled in on the Form 8 PDF with the wrong format

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#293]
From Slack:

> Paul Tagliamonte [10:24 AM]  Had another in that date format
> ​[10:25] YYYY-MM-DD HH:MM:SS UTC
> [10:25] All 3 filled out when it was empty - I wonder if it had all whitespace
> Paul Tagliamonte [10:27 AM] 
> Got the POST - `"6A_INCREASED_RATING_FOR"=>""`

**Comment by paultag** [comment]
This isn't every one - some came out blank, others came out with a weird formatting, others were as expected.
