### ISSUE TITLE
Track last login timestamp for users

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2930]
Prerequisite eFolder ticket: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/589

As an internal Caseflow admin, I'd like to track the time that each user last logged in.

#### Acceptance Criteria
- Add a last login timestamp column to the User table
- When looking up the `current_user` from the session cookie, check the last login timestamp attribute. If it does not match the current value in the database, update the value in the database to match that in the cookie.

**Comment by amprokop** [comment]
Closing, we decided not to do this
