### ISSUE TITLE
Re-enable System Admin role

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2931]
Prerequisite tickets:
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/589
https://github.com/department-of-veterans-affairs/caseflow/issues/2930

Currently the System Admin role is essentially [disabled](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/user.rb#L66). We'd like to re-enable System Admin role and only grant it to internal Caseflow team members.

### Acceptable Criteria
- Remove the restriction in the User's `admin?` method that checks specifically for the `CSFLOW` user
- Update the User's `from_session` method [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/user.rb#L159). Instead of automatically saving the session's roles, we'll need to check if the `System Admin` role already exists in the database user's roles. If it does not exist, **remove it** from the session (and therefore not saving it to the user record)
- Provide a report to @nikitarockz with the `css_id`s of all current users in the database that have the "System Admin" role. Verify with her that these are the correct users (it should be exclusively Caseflow team members)

**Comment by amprokop** [comment]
We pursued an alternate approach for this
