### ISSUE TITLE
Document Viewer | Refresh page resets Document Viewer to single document view and clears Document List

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2935]
# Description
When viewing a Document,
if I refresh the page...
the document is no longer fetched.

## Reproduction Steps

**Scenario 1 -**

1. Go to view a document
1. Refresh page
1. Not see the PDF
1. Go to Document List
1. See only one document????

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:

```
Request URL:https://efolder.cf.uat.ds.va.gov/api/v1/documents/
Request Method:GET
Status Code:404 Not Found
Remote Address:10.236.66.225:443
Referrer Policy:no-referrer-when-downgrade
```

## Screenshots
**_Scenario 1 - [Refresh]_**
![pagerefresh](https://user-images.githubusercontent.com/18075411/29149068-a2681698-7d3f-11e7-9dfc-8207f2e6a7c9.gif)

**_Scenario 1 - [List gone!]_**
There were 300 before!
<img width="1221" alt="screen shot 2017-08-09 at 8 20 12 pm" src="https://user-images.githubusercontent.com/18075411/29149168-4bd5c004-7d40-11e7-9316-866f27a204c5.png">

# Related Issues

**_Engineering_**
https://github.com/department-of-veterans-affairs/caseflow/issues/2633

**Comment by mdbenjam** [comment]
This is fixed. Single document view no longer exists.
