### ISSUE TITLE
Document Viewer | Blank comments cause sentry/DB errors that look ugly

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2936]
# Description
When leaving empty Comments (blank, or just line breaks),
there's no need to invalidate it at DB level and cause Sentry alerts

## Reproduction Steps

**Scenario 1 -**

1. Go to Document view
1. Start leaving a comment
1. Enter only whitespace or only linebreaks
1. Try to save
1. Get error that looks ugly
1. See Sentry alerts

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:

```
ActiveRecord::RecordInvalid: Validation failed: Comment can't be blank
```

## Sentry:

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/290/

## Screenshots
**_Scenario 1 - [Ugly error]_**

<img width="427" alt="screen shot 2017-08-09 at 8 22 55 pm" src="https://user-images.githubusercontent.com/18075411/29149252-ef75887a-7d40-11e7-9dd5-12954bc2fc5e.png">

**Comment by lowellnava** [comment]
@kierachell, @mdbenjam, @gnakm, Am I correct in assuming that the correct behaviour should be to allow whitespace-only comments to be saved (which may be useful as placeholders)? Or should we not allow whitespace-only comments at all?

**Comment by lowellnava** [comment]
After standup we decided that the proper behaviour is to disable the save button when there are no non-whitespace characters in the comment text (in other words, the save button will be disabled when the comment text is empty or contains only whitespace). We will also return a better error message from the back end to the front end that the front end can display in a more reasonable manner.

**Comment by kierachell** [comment]
**PASSED**
![blank](https://user-images.githubusercontent.com/18075411/32638377-ff1c0d96-c58c-11e7-9c8a-ad5cd1e20044.gif)
