### ISSUE TITLE
Remove respond to code from Reader::AppealController#show

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2940]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/338/

We currently check for what format the request comes in, but then ignore html requests. Instead we should redirect the user to a useful URL.

# AC
1) Verify when a user goes the URL: reader/appeal/:id we forward them to reader/appeal/:id/documents

**Comment by nickheiner-usds** [comment]
That sentry link does not work for me.

![image](https://user-images.githubusercontent.com/25331532/32614755-f327f6c2-c53b-11e7-9a3c-61b606f4d6ba.png)

**Comment by mdbenjam** [comment]
That's weird. Here's a newer error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/593/

**Comment by kierachell** [comment]
### If I navigate to the Document List by entering the URL then navigate back (keyboard, or swipe) to the other appeal I get a json:

![other](https://user-images.githubusercontent.com/18075411/33530709-006325f4-d852-11e7-9d6d-ceb8a689ebd1.gif)

**Comment by mdbenjam** [comment]
Closing in favor of: https://github.com/department-of-veterans-affairs/caseflow/issues/2773
