### ISSUE TITLE
Welcome page | Change search ui component 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2947]
## Description
Right now the search in the welcome page works the way the search in document list works (type ahead...). This is the wrong feature for this task because a user can type in (the wrong) valid ID for a shorter number without completely typing in an ID. 

## AC
- [x] Switch the search so that it is using the [Style guide big search](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#search) component
- [x] Make sure the search box width (not including button) is 250px
- [x] Verify that user can enter search by pressing the search button or pressing enter on keyboard
- [x] Verify that when there is latency that the search turns into the [loading button](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#loading_buttons) and make sure the logo inside is in [reader brand color](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#colors)

## Mockup

![image](https://user-images.githubusercontent.com/13420618/29191946-7ef22cc2-7ded-11e7-9492-cb3cde18c6c8.png)

**Comment by tejans24** [comment]
@gnakm So, should we not search if user presses the 'enter' key in the search bar?

**Comment by tejans24** [comment]
#2952 might also be a dependency of this issue.

**Comment by gnakm** [comment]
@tejans24 Users should be able to search by hitting enter and the search button.

**Comment by gnakm** [comment]
@tejans24 I changed AC - Verify that user can enter search by pressing the search button or pressing enter on keyboard

**Comment by kierachell** [comment]
**PASSED**
![veteranid](https://user-images.githubusercontent.com/18075411/29922075-1efcf64a-8e22-11e7-84b2-9212772c06a3.gif)
