### ISSUE TITLE
Claims Folder | Investigate alternatives to double-scroll interaction on list view

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2948]
We currently have 2 scroll bars on the documents list view, which is not great from a usability standpoint. Users sometimes tried scrolling on the outer scrollbar and were initially confused about how to scroll through their entire document list.

![doublescrollbar](https://user-images.githubusercontent.com/3885236/29641581-3bc334f6-8832-11e7-997a-c4cb35498bda.gif)

Note: When we encountered this in the past we found keeping the outer scrollbar and trying to make the header sticky was very difficult, hence the inner scrollbar. My hunch is that we'll need to keep the inner scrollbar and get rid of the outer one.

# AC
- Verify the header (everything above the list) is always visible at the top of the screen.
- Verify there is only one scrollbar (either the outer or inner).
- Verify that when returning to the list view from the document view the app still scrolls to last-read document.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
