### ISSUE TITLE
Form 8: Question 8A: No option for No POA

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#295]
As a user filling out a form 8 on Caseflow Certification, I want an option to record that the veteran has no representative, and I would like irrelevant fields to hide.

### Acceptance Criteria
1. Verify that on the Form 8, question 8A has  a "None" option.
1. Verify that when the "None" option is selected on question 8A, questions 8B, 8C, 9A, and 9B are hidden.
1. Verify that when "None" is selected for 8A, and the form 8 is submitted, verify that on the Form 8 PDF, that 8A reads "None", and 8B, 8C, 9A, and 9B are all empty.

### Additional notes
This issue was based on the below feedback when a Veteran has no POA –

> Caseflow requires you to select if there is a 646 or equivalent of record (Question 9A) – which is only required when the veteran has a POA – this question should be blank because the veteran has NO POA …. Meaning you should not have to complete this question at all
> 
> So I selected NO because the system would not allow me to move forward and another question comes up (Question 9B) and asks Why is the Form 646 not of record – well it would be because the veteran has NO POA and that form is not needed.
> 
> I think it all stems from Question 8A – Representative Type: (Required) …. There should be an option that states NO POA and then the system would skip these additional questions – 9A & 9B …
> 
> If you select Attorney or Other under question 8A  - the 646 questions do not appear as a required question to answer.  However you have to specify other or Attorney’s name.  If you select Agent – No representative appears in 8A and then you have to answer 8B What is the authority for recognizing such representative in this appeal and 8C Is Agent on accredited list (Required)
> 
> You may want to add the option of NO POA for Veteran’s that do not have one.

**Comment by lakohl** [comment]
@shanear could you fill @shellicious in on this?

**Comment by shanear** [comment]
@shellicious what do you want to know? would it be better if we chatted about this in person?

**Comment by shellicious** [comment]
@shanear let's slack about it. I got tagged on a bunch of certification related issues, and it would be great to understand them all together.

**Comment by shellicious** [comment]
This issues covers two problems:

- Form 8, question 8A needs to have a "no representative" or "none" option,  in the event that the veteran/claimant does not have a representative.
- questions 8B, 9A, and 9B should be skipped if the answer to 8A is "no rep" or "none"
