### ISSUE TITLE
Document list | Remove search button from search box

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2951]
## Description
Right now, the search button is not functional for the search feature in documents list. It is confusing and according to our google analytics, it is hardly clicked on. 

## AC
- [ ] Remove the search button in the search box
- [ ] Add in search box "Type to search..." (italicized) 

## Mockup
![image](https://user-images.githubusercontent.com/13420618/29192359-2aa50476-7def-11e7-802a-6c90727b826f.png)

**Comment by gnakm** [comment]
@mmlumba Looks like this issue can be closed? I defer to you!

**Comment by mmlumba** [comment]
@gnakm I'll move this to "In Validation" for review since its related ticket (#2952) is still "In Validation".

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Reader 
2. On the Document Lists page, verify that then search bar is without a search button and that the text inside of the box is italicized based on the AC and mocks. 

Screenshots: 
<img width="1358" alt="screen shot 2017-08-23 at 9 59 13 am" src="https://user-images.githubusercontent.com/23038505/29619775-ef646dc0-87e9-11e7-9a13-455b8a1cd4f9.png">
