### ISSUE TITLE
Style guide component | Add type ahead search

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2952]
## Description
As a designer and developer, I want to know every kind of search feature available on caseflow style guide. 

## AC
- [ ] Add a search type ahead from reader under small search in the [search section](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#search)
- [ ] Add in search box "Type to search..." (italicized) 

## Mockup
![image](https://user-images.githubusercontent.com/13420618/29192359-2aa50476-7def-11e7-802a-6c90727b826f.png)

**_Note: The toggle buttons on the side does not need to go on style guide. It is reference to layout in Reader._**

**Comment by mmlumba** [comment]
_For searches in general_
1. Are _all_ searches supposed to have [x] to the left of the search button when a user types in text?

_For Search Ahead_
1. Is there supposed to be no search button to the right of the search bar?
2. Do I need to add the toggle buttons for the search ahead component also?

**Comment by gnakm** [comment]
For searches in general
- yes

For Search Ahead
- no search bar
- > Do I need to add the toggle buttons for the search ahead component also? 
    - confused by this @mmlumba

**Comment by mmlumba** [comment]
@gnakm Am I adding these to the style guide too:
![29192359-2aa50476-7def-11e7-802a-6c90727b826f](https://user-images.githubusercontent.com/4773320/29288651-86c2d57e-8107-11e7-94b0-c5344eaf8901.png)

**Comment by gnakm** [comment]
@mmlumba I am still confused. The search ahead component doesn't need a button. Do you mean adding the toggle button to style guide?

**Comment by mmlumba** [comment]
@gnakm Yes adding the toggle buttons to the search bar like in the mock

**Comment by gnakm** [comment]
Oh. No. That's just a mockup specifically for reader.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Chrome and FF 

Steps To Validate: 
1. Access the Styleguide
2. Navigate to the Search section
3. Validate the Search Ahead search feature based on UI and mocks. 

Screenshots: 
<img width="1287" alt="screen shot 2017-08-23 at 12 31 39 pm" src="https://user-images.githubusercontent.com/23038505/29627487-3f169710-8800-11e7-945b-927a7fd9babb.png">
