### ISSUE TITLE
[Frontend] Save Add On to Redux

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2956]
Requires #2884 

Acceptance Criteria:
- Ensure addOn is initially saved to redux store on pageload
- On user input change, update the redux store accordingly

Technical Notes:
- Do not update any of the backend code
- Do not update any backend calls

**Comment by slj** [comment]
This is handled in https://github.com/department-of-veterans-affairs/caseflow/pull/2968

**Comment by slj** [comment]
@kierachell / @astewarttistatech this is essentially the same as #2884

**Comment by kierachell** [comment]
**PASSED**
see the ending
![changes](https://user-images.githubusercontent.com/18075411/29496497-cd9f7562-85a1-11e7-82fd-2cfbfc6190a3.gif)
