### ISSUE TITLE
[Frontend] Daily Docket | Pre-save 'edited' field on hearings redux state

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2957]
When we need to update Redux, we need to mark what's been updated so we can know whether or not to send a request to the backend. 

Example:

![Screen Shot 2017-08-14 at 10.02.17 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582a398e7d9c5f1300c030ee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f76b7191a379ef0c2b53415e49bc30254d58eeb9cb74fce36f34985619e8d96f0e76903818aeb18249bb01eb278b4fd7b4b98a4f92fa2137a5dad11b61435c52dcbd4f3fb29c4cce50fc4ae44d57a3123f60e3733e79478653.png)

Add 'edited' at same level as id, user_id, appeal_id, etc

Acceptance Criteria:
- After editing a hearing's field, add a redux field 'edited' on the hearing and set it to true

**Comment by kierachell** [comment]
**PASSED**
![changes](https://user-images.githubusercontent.com/18075411/29496481-a4549de0-85a1-11e7-9d79-bb5b394e2009.gif)
