### ISSUE TITLE
[Frontend] | Daily Docket post-save redux updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#2959]
Requires #2475

When we trigger a save, we need to update the Redux state to reflect the save.

Acceptance Criteria:
- After a successful call to the backend, the 'edited' field on the hearing's state should be reset to `false`

Tech notes:
- The backend call should be stubbed out for now

**Comment by slj** [comment]
Actually being covered in the work on #2475

**Comment by slj** [comment]
This was accomplished in https://github.com/department-of-veterans-affairs/caseflow/pull/3114

**Comment by kierachell** [comment]
**PASSED**
![itsasaving](https://user-images.githubusercontent.com/18075411/30213524-4526176a-9477-11e7-92a4-4a9915388cac.gif)
