### ISSUE TITLE
hearing request data dind't get pulled from VACOLS

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#296]
10A isn't being populated with the right data from VACOLS

**Comment by plusjeff** [comment]
@paultag @KHarshawat Is this for the PDF or the Questions page? (or both?)

**Comment by paultag** [comment]
@plusjeff I think this is the questions page too, I'll have to check notes

**Comment by paultag** [comment]
Yeah, questions page

**Comment by paultag** [comment]
Done!
