### ISSUE TITLE
UI lockup when using eFolder endpoint

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2960]
Currently when we turn on the eFolder integration, EVERYTHING HANGS when switching PDFs.

# AC
1. Verify when moving between PDFs, the UI doesn't hang.
1. Verify that the PDFs are still being cleaned up (i.e. there is no JS memory leak).

**Comment by kierachell** [comment]
related? https://github.com/department-of-veterans-affairs/caseflow/issues/2937

**Comment by joofsh** [comment]
Mark and Alex spent the evening and afternoon debugging.'

In Pdf.jsx, the line `_.omit(this.predrawnPdfs, pdfsToKeep);` was found to be very slow (on the order of 1500 ms). This line runs several times.


If we roll our own implementation, it seems to fix the problem:
```
var keepPdfs = [];
_.each(this.predrawnPdfs, function(pdf, url, object){
	if (_.findIndex(pdfsToKeep, url)) {
		keepPdfs.push(object);
	}
});
```

**Comment by kierachell** [comment]
**PASSED**
at last!
![working](https://user-images.githubusercontent.com/18075411/29620697-a452aff6-87ec-11e7-8e9f-0a44c7479426.gif)
