### ISSUE TITLE
[Backend] Hearing Worksheet | Update database columns

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2961]
Add new columns to store information about judge's impressions regarding an appeals issues

#### Acceptance Criteria
- Delete current `hearing_worksheet_status` and related code from the Issue model/table
- Add 4 new boolean columns to the `Issue` table: `allow`, `deny`, `remand`, and `dismiss`

**Comment by kierachell** [comment]
**PASSED**

Crappy AC leads to crappy validation:
```
#<ActiveRecord::Relation [#<Issue id: 1, appeal_id: nil, vacols_sequence_id: nil, hearing_worksheet_reopen: false, hearing_worksheet_vha: false, allow: nil, deny: nil, remand: nil, dismiss: nil>]>
```
