### ISSUE TITLE
Reader making unneccessary calls to get documents

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2962]
If you move between documents somewhat quickly you can start loading a document then switch to the next document before the first request finishes. We should stop trying to load the first document since it uses up one of our network requests.

Look at calling `.destory` here:
https://mozilla.github.io/pdf.js/api/draft/PDFDocumentLoadingTask.html

**Comment by kierachell** [comment]
That or the browser cache is not working?

**Comment by mdbenjam** [comment]
This was completed in a previous PR.
