### ISSUE TITLE
Document Viewer | Moving annotations in Firefox redirects to empty page

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#2969]
# Description
Using Firefox
When moving a created Annotation across a PDF page
I am redirected to an invalid URL; probably coordinates are not parsed correctly

## Reproduction Steps

**Scenario 1 -**

1. Go to Document Viewer
1. Use Firefox
1. Make a comment
1. Save it.
1. Drag it.
1. Crash

**Validated in the following Environment(s)**
- [x] Dev
- [x] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Crash!]_**

![moving-annotation-bug](https://user-images.githubusercontent.com/4773320/29222967-c4a47df6-7e92-11e7-9534-840ecd7ded0d.gif)

**Comment by mmlumba** [comment]
@Sjones352 originally found the bug and I and @kierachell can confirm

**Comment by kierachell** [comment]
## I wouldn't worry too much
<img width="1092" alt="screen shot 2017-09-10 at 8 02 20 pm" src="https://user-images.githubusercontent.com/18075411/30254212-063ee8d6-9663-11e7-9b5c-abacb5f81595.png">

**Comment by oscarAtNava** [comment]
Fixed by adding an event.preventDefault() call in the drop event handler.
