### ISSUE TITLE
Remove Excessive Details from Confirmation Page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#297]
on the Congratulations page in Caseflow Certification we should ...
- [ ] Remove to header section that lists the appeal type, file type,  rep, and vet name.
- [ ] Center align the check list items
- [ ] Include the veteran name in the congratulations message instead...e.g. `Davy Crocket's appeal has been certified`

**Comment by KHarshawat** [comment]
![image](https://cloud.githubusercontent.com/assets/6335546/16694418/18ff222c-4508-11e6-8fef-5e2c6d4e0247.png)

vs 

![image](https://cloud.githubusercontent.com/assets/6335546/16694423/1fd58d02-4508-11e6-88b2-9aece7a296a1.png)

**Comment by shanear** [comment]
closing, combining with #450
