### ISSUE TITLE
SPIKE: Verify Hearing Schedule Pilot Plan on VACOLS dev

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2974]
Before conducting the hearing schedule AM/PM shift pilot, we want to verify creating 2 master hearing records for the same room will not break VACOLS GUI.  On VACOLS dev:

- [x] manually insert 2 master records assigned to the same room/day but different ROs, verify it does not break the VACOLS GUI for either RO
- [x] manually insert 2 master records assigned to the same room/day and to the same RO, verify it does not break the VACOLS GUI for either RO
- [x] manually insert 2 master records assigned to the same room/day and to the same Judge, verify it does not break the VACOLS GUI for either the RO or the judge

**Comment by joofsh** [comment]
Verified all permutations. We can in fact create 2 "dockets" assigned to the same judge, same room, and RO. 
 
<img width="453" alt="screen shot 2017-08-23 at 11 42 20 am" src="https://user-images.githubusercontent.com/2256237/29629232-1811bb30-8806-11e7-94a7-f73b5122327d.png">
<img width="814" alt="screen shot 2017-08-23 at 11 47 49 am" src="https://user-images.githubusercontent.com/2256237/29629234-18142bae-8806-11e7-8721-84f7e347cdce.png">
<img width="836" alt="screen shot 2017-08-23 at 11 48 57 am" src="https://user-images.githubusercontent.com/2256237/29629233-1811ca12-8806-11e7-93cc-2671685bdef0.png">
<img width="372" alt="screen shot 2017-08-23 at 11 52 58 am" src="https://user-images.githubusercontent.com/2256237/29629235-18142db6-8806-11e7-94fb-b664536ebdc4.png">
<img width="474" alt="screen shot 2017-08-23 at 11 56 41 am" src="https://user-images.githubusercontent.com/2256237/29629236-18160064-8806-11e7-8fd6-e65502c09dca.png">

**Comment by joofsh** [comment]
CC @lakohl @laurjpeterson @sharonwarner @annienguyenUSDS  for awareness. We should be good to go for the hearing schedule pilot

**Comment by lakohl** [comment]
Awesome! Thanks @joofsh

**Comment by joofsh** [comment]
Don't think this needs QA, but moving it to in-validation for consistency

**Comment by kierachell** [comment]
I can actually try this out with @sharonwarner to add some more relevant data

**Comment by kierachell** [comment]
**PASSED**

![thisishowyoudoit](https://user-images.githubusercontent.com/18075411/29847077-da0ac8ea-8ce7-11e7-8a5a-d605c5001122.gif)
