### ISSUE TITLE
Welcome Gate | VLJ case assignments list is incomplete

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2975]
**Context**
A couple VLJs have mentioned they aren't seeing all their checked in cases in Reader. We met with a user, and it looks like cases that haven't been assigned in the DCASS table (no assigned date) aren't showing up on the Welcome Gate. 

**Story**
When opening Reader, I want to see a full list of cases in my station, so I can use Reader to prepare for hearings and to pre-screen cases before assigning work to attorneys without going into another application.

## Acceptance Criteria 
- Welcome Gate includes ALL cases current checked in to a user's location (including cases that haven't yet been assigned). Before the behavior was to only show cases that also had a record in DECASS. Now we should any appeal that is checked in to the attorney's or judge's location.

**Comment by mdbenjam** [comment]
The issue here is we're doing an inner join between DECASS and BRIEFF but should do a left join. We probably need to write some raw SQL. I think I know the change, but would prefer to wait until I'm back online next Wednesday to implement it. Don't want this to break something else while Artem and I are out.

**Comment by kierachell** [comment]
**PASSED** 


Uh...I don't quite know...what the AC means...
Here's a sample:
```
   VACOLS_ID         DATE_ASSIGNED         DATE_RECEIVED VACOLS_USER_ID       CSS_ID USER_TYPE           SIGNED_DATE    VBMS_ID       SSN
1     983574 2006-01-30 00:00:00.0 2006-02-02 00:00:00.0       JBKRAMER CF_MCCOY_283         J 2006-02-07 00:00:00.0 584902240S 584902240
2    1393985 2007-02-21 00:00:00.0 2007-04-03 00:00:00.0       JBKRAMER CF_MCCOY_283         J 2007-04-12 00:00:00.0 412883087S 412883087
3    1433930 2004-10-14 00:00:00.0 2004-10-20 00:00:00.0       JBKRAMER CF_MCCOY_283         J 2004-11-29 00:00:00.0  18134689C 424384490
4    1705870 2013-06-05 00:00:00.0 2013-06-13 00:00:00.0       JBKRAMER CF_MCCOY_283         J                  <NA>  24887782C 146361723
5    1720467                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 212508253S 212508253
6    1803065                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 437840057S 437840057
7    1874071                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA>  17537267C 242426084
8    1997431 2013-02-14 00:00:00.0 2013-02-12 00:00:00.0       JBKRAMER CF_MCCOY_283         J                  <NA> 149092159S 149092159
9    2015440                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 426296843S 426296843
10   2127606 2012-10-23 00:00:00.0 2012-11-06 00:00:00.0       JBKRAMER CF_MCCOY_283         J                  <NA> 251667204S 251667204
11   2127606 2013-01-10 00:00:00.0 2013-01-11 00:00:00.0       JBKRAMER CF_MCCOY_283         J                  <NA> 251667204S 251667204
12   2185046                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 435067247S 435067247
13   2231792                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA>  28937943C 437749291
14   2305006                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 420888212S 420888212
15   2389439                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA>  25795810C 436661281
16   2400693                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 433685183S 433685183
17   2445506                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA> 436961183S 436961183
18   2430046                  <NA>                  <NA>       JBKRAMER CF_MCCOY_283         J                  <NA>  28773358C 434742098
```

Looks like some `DECASS` fields come back as `null` so...right?


Should the date received/assigned be visible on the frontend? do users care?

**Comment by mdbenjam** [comment]
We don't expose those in the frontend as of now. Probably will in the future. And yeah some decass fields will come back as null.

**Comment by mdbenjam** [comment]
So we undid this change last month. After making the change we made too many calls to VACOLS which cause the page to time out. @tejans24 has done a lot of work to remove those extra calls, so we should now be able to reinstate this change.

**Comment by kierachell** [comment]
**PASSED**
<img width="139" alt="screen shot 2017-10-18 at 2 33 17 pm" src="https://user-images.githubusercontent.com/18075411/31735943-584ece4a-b411-11e7-946d-663bf8f7bf6a.png">
<img width="552" alt="screen shot 2017-10-18 at 2 33 27 pm" src="https://user-images.githubusercontent.com/18075411/31735944-587079c8-b411-11e7-89be-69b4e74eef2f.png">
