### ISSUE TITLE
Remove remaining single document page code

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2976]
Connects: https://github.com/department-of-veterans-affairs/caseflow/pull/2871#issuecomment-322216604

In the above ticket, Nick pointed out dead code we forgot to remove.
<img width="786" alt="screen shot 2017-08-14 at 11 21 29 am" src="https://user-images.githubusercontent.com/3885236/29278482-da250036-80e2-11e7-9e08-3b0406be4f57.png">

# AC
1. Verify the above dead code is removed.
1. Verify there is no more dead code associated with the single document page.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
