### ISSUE TITLE
Document List | Read/unread doc state reset

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2977]
### Description
A couple users mentioned that documents they had previously opened in Reader appeared as unread when they opened Reader today (Monday 8/14).

## Expected behavior
- If a document was previously opened by a user, it should not reset to bold (unread).

**Comment by mdbenjam** [comment]
This really makes no sense to me. I guess this could happen if we fail to make the API call to the server to mark them as read. Seems unlikely though. @abbyraskinUSDS can we ask users to send us the URL of the case they're working on and the names of any specific documents this happens to?

**Comment by abbyraskinUSDS** [comment]
Yeah, it's pretty weird. Seemed to happen on the same day to at least two users. I asked for it last week but they hadn't kept track. I told them to let us know if it happens again, and to keep track of the specific documents. I'm going to move this to Inbox for now until we hear about it again.

**Comment by abbyraskinUSDS** [comment]
Seems like this was a fluke, I haven't heard of this happening again. Closing.
