### ISSUE TITLE
Comments | Add optional date field to comments

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2983]
When adding comments to documents in Reader, I sometimes want to add a date to a comment, so I can note the date a fact in a case took place, and so I can later sort my comments chronologically.

## Acceptance Criteria
- After clicking + Add a comment, there should be an optional field for adding date (Style guide : [Date input](https://github.com/department-of-veterans-affairs/caseflow/issues/1082))
- After saved, the comment format should look like the following: receipt date should be in bold followed by a hyphen and then comment (ex. **05/07/2010** - Text... )
- If there is no relevant date saved, keep comment as is today. 
- Page number should continue to be above the comment box
- Comments should be sorted by page number 

#### State of editing/ adding comment
![image](https://user-images.githubusercontent.com/13420618/30010401-7453d504-90fd-11e7-87a8-76a06c22ded8.png)

![image](https://user-images.githubusercontent.com/13420618/30165602-9c2e68e2-93ae-11e7-943b-522df8320d8a.png)

[Invision link for interaction](https://va-gov.invisionapp.com/share/AUDE0ZWWR#/254419660_1_-_Document_List)

## Note for developer: 
- Ignore the user name and icon for this issue. That is for issue [insert #]

**Comment by gnakm** [comment]
@abbyraskinUSDS Would there ever be a use case for needing to sort by page number? 

![image](https://user-images.githubusercontent.com/13420618/30010871-12ceb6b0-9101-11e7-9e74-83502d986865.png)

![image](https://user-images.githubusercontent.com/13420618/30010914-7ce99916-9101-11e7-8cde-24e801ce3fcc.png)

**Comment by abbyraskinUSDS** [comment]
Hmmmmm - I was thinking these would still sort by page number from the side menu. I feel like I need to talk out loud with you about this one to think it through. It feels like visually, at this particular step (while within a document, actively adding comments) it makes sense to still order them by page, but I don't know if that creates a weird inconsistency w/ the comments view. :thinking:

**Comment by astewarttistatech** [comment]
**FAILED**

Current View:
![readersmoke](https://user-images.githubusercontent.com/23038505/34275412-33bfe9ba-e66b-11e7-8151-5d22b4ba2ad9.gif)

**Comment by astewarttistatech** [comment]
Obsolete, already in prod, cannot test in preprod or UAT.
