### ISSUE TITLE
Document list | Comments toggle: ability to sort by comment date

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2984]
When I've finished reviewing a file in Reader, I want to organize my comments chronologically so I can figure out the correct timeline of events in a veteran's appeal.

## Acceptance Criteria
- [ ] Verify that clicking on the comments toggle sorts the comments chronologically by relevant date (oldest to newest)
- [ ] All comments without relevant date goes to bottom and sorts by receipt date
- [ ] Add document type above page number and jump to section link
- [ ] Add `Sorted by relevant date` above comments on top left
- [ ] Users can search by comment text and document type from this view

![image](https://user-images.githubusercontent.com/13420618/34114167-058bbbc4-e3e0-11e7-87bb-a97c3fcd5993.png)

## Dependent story
https://github.com/department-of-veterans-affairs/caseflow/issues/2983

**Comment by abbyraskinUSDS** [comment]
OLD:
![image](https://user-images.githubusercontent.com/13420618/30010482-0054ed04-90fe-11e7-821d-ec0a55d3e083.png)

[Invision link for interaction](https://va-gov.invisionapp.com/share/AUDE0ZWWR#/254419660_1_-_Document_List)

**Acceptance Criteria**
- Ability to sort by date from Comments tab: clicking on the sort icon next to "Comments" header launches checkbox popout menu with sort options ?? [interaction needs definition]
- Comments without a date are listed at the end of the list

**Dependent story**
https://github.com/department-of-veterans-affairs/caseflow/issues/3167

**Comment by mdbenjam** [comment]
What is the search bar supposed to do on this page? I'm thinking we should maybe remove it.

**Comment by abbyraskinUSDS** [comment]
Added a bullet re: search -- we decided to allow users to search by comment text and document type from this view

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod / Chrome 

Steps to Validate: 
1. Access Reader
2. Create comments with dates associated in the PDF view of several documents if not already done so
3. Navigate to the Document List page
4. Toggle the comment feature on
5. Verify that the comments listed are sorted by relevant date according to the AC. 

Screenshots: 
<img width="1313" alt="screen shot 2018-01-17 at 2 00 03 pm" src="https://user-images.githubusercontent.com/23038505/35061405-1f65845a-fb8f-11e7-83c4-9fbb3f4bbea3.png">
