### ISSUE TITLE
Make page down great again

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#2985]
https://github.com/department-of-veterans-affairs/caseflow/issues/3824 should be worked first.

**Current behavior**
A handful of users have reported frustrations with page down in Reader. They're frustrated by (a) the speed of scrolling within a document and (b) the apparent inability to view only 1 complete pdf page at at a time and scroll page by page.

> "Page by page scrolling within a document is slow or delayed and doesn't necessarily go page by page."  

**Expected behavior**
Users can navigate a complete page at a time using page down. This is an investigation ticket to identify option(s) for improving page down so that it works as expected.

We need to override the Page Up/Page Down keys to scroll the length of an entire page, not just the height of the window.

# AC
1) Verify when a user presses page down, the viewer should scroll to the top of the next page.
1) Verify when a user presses page up, the viewer should scroll to the top of the previous page.

## Dependent story
https://github.com/department-of-veterans-affairs/caseflow/issues/3762

**Comment by abbyraskinUSDS** [comment]
@mdbenjam can you weigh in on this?

**Comment by mdbenjam** [comment]
@abbyraskinUSDS I'd like some clarification here. When you say page, do you mean a page in the PDF or the visible portion of the screen. Page up/down uses the second definition. I think this is expected, so that each time you hit it, you scroll to the next viewable section.

**Comment by abbyraskinUSDS** [comment]
@mdbenjam They're used to being able to scroll one complete page (PDF page) at a time, which a handful of folks have mentioned they aren't able to do in Reader, even when they adjust the zoom level.

**Comment by abbyraskinUSDS** [comment]
(e.g.: "page by page scrolling within a document is slow or delayed and doesn't necessarily go page by page.")

**Comment by mdbenjam** [comment]
Hmm okay, I'm open to changing the behavior, it seems like if you make the view fit to page this should be close to what it does. I have noticed the slowness. I'm not exactly sure what is causing it. We can make a ticket to look into it.

**Comment by abbyraskinUSDS** [comment]
Yeah, even with fit to page it isn't quite right. I'll make this an investigation ticket. 💃

**Comment by abbyraskinUSDS** [comment]
Note: wait until windowing is complete before starting development on this ticket.

**Comment by Sjones352** [comment]
**PASSED**

Validate Uat/ Chrome

1.Access Reader and on Document Viewer.
2.Verify that when you press page down, the viewer should scroll to the top of the next page.
3.Verify that when you press page up, the viewer should scroll to the top of the previous page.

![reader](https://user-images.githubusercontent.com/23080951/35712715-7c3aa364-0791-11e8-8758-83d05bb1c4ac.gif)
