### ISSUE TITLE
Spike: Investigate running VACOLS locally

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#2987]
Related to running VACOLS on RDS: https://github.com/department-of-veterans-affairs/caseflow/issues/2680

Investigate how we could run VACOLS locally in development mode:

- How can we easily install & run oracle DB on mac? Dockerized?
- How can we load the VACOLS schema locally? How can we keep this schema up-to-date
- How can we easily pre-populate our local VACOLS DB with relevant data (from UAT?)

**Comment by kierachell** [comment]
See https://github.com/department-of-veterans-affairs/appeals-deployment/pull/828

**Comment by kierachell** [comment]
This is done...

**Comment by kierachell** [comment]
closed by https://github.com/department-of-veterans-affairs/appeals-deployment/pull/950

you don't want the pain of running the thing localy

**Comment by aroltsch** [comment]
Ok, this is not closed. This issue is for running Oracle in the test environment so we can write better unit tests.
