### ISSUE TITLE
[Frontend] Hearing Worksheet : Persist Issues Information to redux descriptions

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#2990]
connects #2838
Hook up part of the editable fields in the Issues section on the hearing worksheet page to the Redux store

Acceptance Criteria:

- Ensure `description` in the Issues section are initially saved to redux store on pageload.
- On user input change, update the redux store accordingly

Notes:
- Do not add the other preliminary impression checkboxes to redux
- Do not send the information to the backend.
- Do not hook up any additional fields.

**Comment by nolawi** [comment]
holing of submitting PR till we solve issues

**Comment by kierachell** [comment]
### Any input limit here?
<img width="586" alt="screen shot 2017-09-05 at 10 09 33 pm" src="https://user-images.githubusercontent.com/18075411/30091301-f2c30cb8-9286-11e7-8e4d-70348836300f.png">

**Comment by sharonwarner** [comment]
The limit in VACOLS is 50 characters.

**Comment by nolawi** [comment]
Updated this with counter- 120 and display of character counter

**Comment by kierachell** [comment]
**PASSED**
<img width="1257" alt="screen shot 2017-09-16 at 5 04 26 pm" src="https://user-images.githubusercontent.com/18075411/30516023-739805d2-9b01-11e7-9f14-c8ef7d8e4fb6.png">
<img width="1228" alt="screen shot 2017-09-16 at 5 04 57 pm" src="https://user-images.githubusercontent.com/18075411/30516024-73984196-9b01-11e7-83ec-888248061cfc.png">
<img width="1003" alt="screen shot 2017-09-16 at 5 05 19 pm" src="https://user-images.githubusercontent.com/18075411/30516025-739c8a30-9b01-11e7-882e-a9a9fb379508.png">
<img width="766" alt="screen shot 2017-09-16 at 5 06 36 pm" src="https://user-images.githubusercontent.com/18075411/30516026-739e7962-9b01-11e7-84e7-ef427ce76a08.png">
