### ISSUE TITLE
Accordions | Accordions without kids causing JS errors... empty nest syndrome?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2991]
# Description
Accordions are causing JS errors on all the pages where they are present.

## Reproduction Steps

**Scenario 1 -**

1. Go to Styleguide
1. Open JS console
1. See error
1. Go to Reader
1. Open page with Accordions
1. See errors

**Validated in the following Environment(s)**
- [X] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:

```
Warning: Failed prop type: 'Accordion' children should be of type 'AccordionSection', but was 'undefined'.
    in Accordion (created by StyleGuideAccordions)
    in StyleGuideAccordions (created by StyleGuideIndex)
    in div (created by StyleGuideIndex)
    in div (created by StyleGuideIndex)
    in StyleGuideIndex (created by BaseContainer)
    in div (created by BaseContainer)
    in BaseContainer
    in AppContainer
```

## Screenshots
**_Scenario 1 - [Lame]_**
<img width="1102" alt="screen shot 2017-08-15 at 10 16 50 am" src="https://user-images.githubusercontent.com/18075411/29319710-dfaf9d7a-81a2-11e7-97e6-77fdb02cee07.png">

**Comment by astewarttistatech** [comment]
**PASSED** 

Env: UAT
Browser: Chrome 

Steps to Validate: 
1. Locate an accordion in Caseflow (I used styleguide)
2. Open the console in the browser
3. Click through the children in the accordion and see if any JS errors appears. 

Screenshots: 
![accordianjs](https://user-images.githubusercontent.com/23038505/29674750-10d49bb0-88c1-11e7-922c-5639f81ce046.gif)
