### ISSUE TITLE
Hearing Prep Redux Dev Tools seeing multiple instance

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#2999]
<img width="1039" alt="screen shot 2017-08-15 at 8 02 34 pm" src="https://user-images.githubusercontent.com/1745984/29341813-d5124ec4-81f4-11e7-8a02-14dcc75a777a.png">

**Comment by sharonwarner** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/2858

This is a Reader issue that they're handling.
