### ISSUE TITLE
Users have to log into Caseflow every time VACOLS opens it

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#300]
Seems like the session isn't getting saved, and they continue to have to enter their VACOLS login

**Comment by alex** [comment]
Does anyone have notes on what their usage patterns were? Entirely closing IE, just closing the tab, etc.?

**Comment by paultag** [comment]
Entirely closing IE, and every time VACOLS popped up Caseflow, it'd forget the session

**Comment by alex** [comment]
So, the `_caseflow_session` cookie does not have `expires` or `max-age` set, so it's cleared when the user quits their browser. I guess we should just set one. 2 weeks seem reasonable?
