### ISSUE TITLE
IE | Efolder | Coachmarks don't automatically start on start of session

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3000]
**Description:**

Currently, if logged into a eFolder with a css id that has coachmarks enabled and they do not start at the beginning of the session. 

**Expected:**
Coachmarks start at the beginning of the session. 

**Env:** UAT
**Browser:** IE

**Notes:** Conflicts with: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/517

**Steps to Reproduce:
1. Access an eFolder with a css id that has coachmarks enabled 
2. When you arrive on the eFolder homepage verify that the coachmarks do not start with the beginning of the session. 

**Screenshots:**

![coachmarksie](https://user-images.githubusercontent.com/23038505/29368495-da229274-826d-11e7-9f71-3554cafa734f.gif)

**Comment by aroltsch** [comment]
@astewarttistatech I don't think this is still happening?

**Comment by astewarttistatech** [comment]
Closed due to this issue being obsolete.
