### ISSUE TITLE
Remove vacols_id references from Users

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3001]
In the hearings repository, we reference a removed column from the Users table. 

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/hearing_repository.rb#L49

This is causing Sentry errors: 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/362/

**Comment by kierachell** [comment]
**PASSED**

![jdpls](https://user-images.githubusercontent.com/18075411/29496405-05c1007a-85a0-11e7-92ab-631ae2759d93.png)

So we good 👍

**Comment by joofsh** [comment]
@kierachell That slack conversation was referring to an entirely different PR. In the context of this production error, I _did_ test the code on UAT, but I did not test it comprehensively or correctly. I tested the `VACOLS::CaseHearing` model in isolation from the UAT console. I did not correctly test it in conjunction with the `HearingRepository` which led to this production error
