### ISSUE TITLE
Document viewer | Bug: copy/paste removes spaces between words

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3004]
**Current behavior**
When a user copies text from a document in Reader, then pastes it into Word (e.g., if they want to quote part of a document in their final decision), all formatting is removed from the text (so it's all one big word). Some users have also reported this happening when pasting from the document to a comment in Reader.

**Expected behavior**
- We should keep all formatting to the extent possible. We shouldn't remove spaces/characters from document text when pasting outside Reader.

**Comment by mdbenjam** [comment]
I don't think there is anything we can do about this. Tempted to close.

**Comment by abbyraskinUSDS** [comment]
Hmm, okay. If there's nothing we can do, we should close it. Is it worth investigating further? It seems rather annoying.

**Comment by mdbenjam** [comment]
It's kind of up to the browser how it lets you select text. I don't think it's worth investigating further. Going to close it.

**Comment by abbyraskinUSDS** [comment]
reopening this - sounds like we might be able to address it after all. we're continuing to receive feedback about this issue.

**Comment by mdbenjam** [comment]
Discussion about this issue: https://github.com/mozilla/pdf.js/issues/6657

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
