### ISSUE TITLE
Post Mortem: [08/17/2017] - Appeal status API partial outage

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3008]
Date: 08/17/2017
Authors: JD Pagano
Status: Resolved

## Summary
Caseflow was deployed to production on 08/17/2017 including a DB migration removing a column. Code still existed that referenced this column,  causing requests to the appeals status API to result in 500 status codes. This occurred **only** for appeals with an associated hearing. The code in question was linked to a ticket that had not yet been validated on UAT. Integration tests were run prior to the deploy and all passed. 

## Impact
The production issue started at the conclusion of the deploy at ~12:00 pm ET and was resolved at 5:26 pm ET. In total 49 requests were affected. 

## Root Causes
A [DB migration](https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/migrate/20170810193012_remove_vacols_id_from_users.rb) ([ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/2590)) was deployed removing the `vacols_id` column from the User table. [Code still existed](https://github.com/department-of-veterans-affairs/caseflow/blob/769f1c6b1a807d5abbcc1cf5d8f2c198b55ace14/app/repositories/hearing_repository.rb#L49) that referenced this column, resulting in [PG::UndefinedColumn](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/362/) errors. 

## Trigger
Any request to the appeals status API that included an appeal with an associated hearing would execute the error-causing code, resulting in a 500 status code response.

## Resolution
A timeline for the resolution of the issue is as follows:
- 1:20pm: The Sentry error was noticed by Prod Squad and a ticket was created. This ticket was incorrectly evaluated by the assigned developer as affecting UAT-only and was thus _deprioritized_ & considered non-urgent.
-  3:02pm: A [new PR](https://github.com/department-of-veterans-affairs/caseflow/pull/3002) was put out that resolved the bad line of code. 
- 3:08pm:  The assigned developer realized the issue was affecting production and asked for immediate code review
- 3:12pm: The PR was reviewed and merged to master. A hotfix production deploy was then requested. QA stated they would be able to do a production deploy at 7pm. The assigned developer deemed this acceptable and did not escalate the urgency of deploying. 
- 5:36pm: Integration tests were run and passed, and master was deployed to production by the devOps team.

## Detection
The issue was first detected due to a [Sentry error](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/362/) in production.

## Lessons Learned / Discussion Topics
Several small things went wrong for this to reach production. Breaking them into categories:

#### Unit Tests
Because the code in question was in the HearingRepository, we do not have unit tests for this. Generally our accepted practice is to not test these classes, and to rely on integration tests. In this case though, the code _could_ have been unit tested. We should move from a model of never testing repository code, to testing as much of the hearing repository code as possible. Adding `#nocov` to the code should be heavily scrutinized in code review. Similarly, 

#### Integration Tests
The Appeals status API integration tests do not include an appeal that has an associated hearing (an appeal with a scheduled hearing). This is challenging to solve when there is a disconnect between the who writes the application code (developers) and who writes the integration tests (QA). Do we need to change our process for how integration tests are maintained/extended? Should developers be more involved? This should not fall solely on the shoulders of QA

#### Coding Integrations & Code Review
The [PR](https://github.com/department-of-veterans-affairs/caseflow/pull/2946) that caused the bug included an **insufficient** testing plan. The developer tested simply that the newly added migration ran up/down. When removing a column, the test plan should include verifying that all references to the column are also removed from the code. 

#### Prod Squad Communication
The [ticket that was created](https://github.com/department-of-veterans-affairs/caseflow/issues/3001) correctly assigned the `prod-alert` label. However, we have many `prod-alert` tickets, and it is not always clear the urgency in fixing them. Does the error affect one user one-time? some users as an edgecase? all users? Currently our process is to create a ticket and to then silence the Sentry error. So the Prod Squad developer will only see 1 error ever occur. The problem with this approach is that it does not give the Prod Squad team enough information to know how to properly escalate the issue. 

#### Process for fixing production
After the bugfix had been coded, there were two options for getting the code to production: deploy a hotfix or merge to master and deploy master. Both of these approaches currently have process problems. There is currently no documentation for deploying a hotfix to production, which made this option challenging mid-production incident. For deploying master to production, several other commits had been merged into master that were not yet verified on UAT.  Do we feel comfortable deploying non-validated code changes to production as long as the integration tests pass?

## Action Items
- Add unit tests to methods in our hearing repository where possible https://github.com/department-of-veterans-affairs/caseflow/issues/3011
- Add integration tests for the appeal status API for an appeal with a hearing https://github.com/department-of-veterans-affairs/appeals-qa/issues/104
- Write steps for deploying a hotfix to production https://github.com/department-of-veterans-affairs/appeals-qa/issues/105

**Comment by kierachell** [comment]
> Do we need to change our communication style, or just be more mindful of being explicit in the future?

Yeah, how about clarifying what `associated hearing` means before expecting that to be part of a smoke test.

Between...
- Never creating a sensible AC for whatever `associated hearing` is (I asked multiple times what constitutes a hearing event that would show up in the API response)
- Dismissing any errors as `bad test data` (note, I reported this bug before deployment)
- Having only 49 out of ~4k requests fail (again, dismissed as edge case/bad test data when I asked)

...the priority of this part of API functionality was communicated to be low.

**Comment by NickHeiner** [comment]
>  For deploying master to production, several other commits had been merged into master that were not yet verified on UAT. Do we feel comfortable deploying non-validated code changes to production as long as the integration tests pass?

We do deploy non-validated code to prod all the time. The process is that the QAs look at the in-validation column and see if anything looks particularly problematic, and if not, they deploy.

**Comment by NickHeiner** [comment]
@kierachell The points you're bringing up sound valid. I haven't had a chance to dig in fully, but if you have specific Slack conversations / GH comments you'd like to share about our communication breakdown here, that could be useful to figure out where things went wrong.

However, despite the validity of your points, I find your tone to be slightly aggressive. A post-mortem is a sensitive time, because people may have made mistakes. We'd like to safely analyze those mistakes and avoid them in the future, rather than point fingers. Please make an effort to state your valid points in a dispassionate way that could not reasonably be construed as being irritated with our teammates.

**Comment by NickHeiner** [comment]
@joofsh can you link the original ticket for the work that caused the problem?

**Comment by joofsh** [comment]
It is already linked in the description

**Comment by kierachell** [comment]
We got action items; we got unit tests on the way; integration tests include hearings now; closing.
