### ISSUE TITLE
Instruct users calling help desk to specify the Caseflow team in routing the ticket

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow#301]
**AC**

On the following pages:
- [500 Error page](https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/app/views/errors/500.html.erb)
- [404 Not found page](https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/app/views/errors/404.html.erb)
- [Help page](https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/app/views/help/show.html.erb)

_Replace the (last) line of copy:_ 
>'If you continue to see this page, please contact the help desk.' 

with the following...

_Replacement copy:_ 
>"If you continue to see this error, please contact the help desk and ask the representative to assign the ticket to the _Caseflow team._"

**Comment by shanear** [comment]
@lakohl could you look into this one?

**Comment by Chingujo** [comment]
So this just needs new copy? 

This is what exists? "If you continue to see this page, please contact the help desk" 

Here's my stab it. Thoughts @lakohl ?

## 500 error page:

"If you continue to see this error, please contact the help desk and ask the representative to assign the ticket to the _Caseflow team_" We will resolve this issue as quickly as possible. 

## 404 page:

"If you continue to see this error, please contact the help desk and ask the representative to assign the ticket to the _Caseflow team_" We will resolve this issue as quickly as possible. 

## Help page:

If you still need help, please contact the help desk and ask the representative to assign the ticket to the _Caseflow team"_ We will assist you as quickly as possible.

**Comment by lakohl** [comment]
@Chingujo I updated the above. Just took out the last sentence to keep things brief, because there is usually another sentence before this one.
