### ISSUE TITLE
Add unit tests for real hearing_repository

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3011]
A couple of the methods in hearing_repository are unit testable, so we should test them. Lack of unit tests around these methods caused a [production outage](https://github.com/department-of-veterans-affairs/caseflow/issues/3008)

### Acceptance Criteria
- For the methods that we can unit test, add them! This includes `set_vacols_values` and `hearings_for`. See [appeal repository spec](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/services/appeals_repository_spec.rb) for inspiration

**Comment by joofsh** [comment]
The tests already existed (thanks anya). No need to validate really

https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/repositories/hearing_repository_spec.rb

**Comment by kierachell** [comment]
**PASSED**
