### ISSUE TITLE
Disable nightly Reader job

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#3016]
Disable the 9pm retrieve_docs_for_reader_job until we have a discussion with the VBMS team about how we can handle the load on VBMS

# AC
- The job is disabled
    - Open the rails console
    - Execute `Sidekiq::Cron::Job.all.select { |j| j if j.name == "retrieve_documents_for_reader_job" }` to ensure that the job is no longer active
         - This will return an empty array (i.e. `[]`) if the job is no longer active
- The job is not executed at 9pm
    - Check that the job did not post a message to the `appeals-devops-alerts` channel
        - The messsage will say `RetrieveDocumentsForReaderJob successfully retrieved X documents and X document(s) failed. X appeal(s) failed.` if the job is successful, `Job stopped after X failures` if the job fails.

**Comment by kierachell** [comment]
**PASSED**
```
irb(main):003:0> Sidekiq::Cron::Job.all.map(&:name)
=> ["out_of_service_reminder_job", "dependencies_report_service_log_job", "prepare_establish_claim_tasks_job", "dependencies_check_job", "create_establish_claim_tasks_job", "heartbeat_tasks_job", "reassign_old_tasks"]
```

Check for name in prod as well..
