### ISSUE TITLE
Spike: Investigate longterm scheduled jobs solutions

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3025]
Currently, our background jobs are run via [sidekiq](http://sidekiq.org/) scheduled via [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron). 

### Problem 1:
There have been several issues with this approach with jobs failing to start. We have lost faith in sidekiq-cron to do a reliable job queue'ing our jobs at the time we request. 

Related issues:
https://github.com/department-of-veterans-affairs/caseflow/issues/2868
https://github.com/department-of-veterans-affairs/caseflow/issues/2728
https://github.com/department-of-veterans-affairs/caseflow/issues/2513
https://github.com/department-of-veterans-affairs/caseflow/issues/1814
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/768
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/586
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/744

### Problem 2:
Currently with the free version of sidekiq, jobs do not recover from system ungraceful shutdown. I.e. if the instance is terminated during a deploy the job dies and is never re-run. 

#### Acceptance Criteria:
- Research alternatives to Sidekiq-cron. Some options we've considered so far are
  - [sidekiq-enterprise](http://sidekiq.org/products/enterprise)
  - [AWS lambda](https://aws.amazon.com/lambda/)
  - [EC2 System Managers](https://aws.amazon.com/ec2/systems-manager/)
- Write tech spec that includes:
  - evaluating the pros/cons of various options for running our jobs & scheduling them

  - making a recommendation on the best approach
  - Any considerations for migration strategy from existing solution to new one

**Comment by sunil-sadasivan** [comment]
Started a tech spec around re-architecture exploration here:

https://docs.google.com/document/d/1qut1f5steDTtQF92RYyP9mvpDImS7jxvw6S_SMtDaNE/edit#
