### ISSUE TITLE
Change RetrieveDocsForReader job to limit requests made by eFolder to VBMS

### ISSUE THREAD

**Issue by mogrenAtWork** [department-of-veterans-affairs/caseflow#3027]
Before eFolder is enabled for Reader, the RetrieveDocumentsForReader batch job needs to be adjusted to limit the number of requests made by eFolder to VBMS.

The batch job should run nightly to:
1. Retrieve all active appeals assigned to Reader users (this will need to be limited in the future as well when opened to 700 users)
1. Loop through the appeals
1. For each appeal, retrieve the list of documents for the case from eFolder. 
    - This request triggers eFolder to cache these documents from VBMS into S3

Currently, the job has no way to tell if eFolder has to make requests to VBMS for the documents. It will not stop until [all documents for all appeals have been retrieved](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/retrieve_documents_for_reader_job.rb#L46).

This ticket may need a tech spec for how to implement the required changes to the eFolder API to return a field that shows if an appeal has to be fetched from VBMS or not

**Comment by mdbenjam** [comment]
We long ago updated the job and have it working in prod.
