### ISSUE TITLE
Support IE8

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3032]
In order to complete the e-Reader rollout to the rest of the board, we need all of Caseflow to support IE8. (It's not just Reader because AOD cases require VLJs to go into Dispatch / Certification to finish reviewing the case.)

Our general rollout will happen on 10/1, but we need to have IE8 support in place early so the 508 testers can begin their audit. (Without this, we can't proceed with the rollout.) They test with IE8 / JAWS 11. We promised that they would be able to start testing with IE8 in UAT by 9/1. I forgot to make this ticket until recently, but hopefully this isn't too big of a lift. Thanks!

**Comment by abbyraskinUSDS** [comment]
thanks for the troll, @NickHeiner

**Comment by NickHeiner** [comment]
Why did you delete the text? :smile:

**Comment by abbyraskinUSDS** [comment]
Because this is a public repo and it's shameful! But I saved it to my desktop for eternity.

**Comment by amprokop** [comment]
hmm i missed something here. unassigning myself because i want no part of ie8 support
