### ISSUE TITLE
Analytics | Fix category of expand comments button

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3038]
Currently the category from the action `TOGGLE_LIST_COMMENT` action is `INTERACTION_TYPES.VISIBLE_UI`; it should be `CATEGORIES.CLAIMS_FOLDER_PAGE`.

From @NickHeiner 
 If we look for other usages of the `meta.analytics.category` field, we'll see that it's always set to a value from the `CATEGORIES` constant:

```
λ _grep 'category:' client/app/reader/actions.js 
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:          category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:        category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:        category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.CLAIMS_FOLDER_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
client/app/reader/actions.js:      category: CATEGORIES.VIEW_DOCUMENT_PAGE,
```

This shows up incorrectly in the Analytics:

![image](https://user-images.githubusercontent.com/829827/29528415-f73093d4-8669-11e7-9a2c-df2920d8c858.png)

Because this happens on the "Claims Folder" page, the correct value here is `CATEGORIES.CLAIMS_FOLDER_PAGE`.

PR for context: https://github.com/department-of-veterans-affairs/caseflow/pull/2902/files#r134274260

Related to #2724 

## AC
* Open the Document list page in Reader
* Use the toggle comment button for any document with comment(s)
* Notice the browser console to have a redux action `Constants.TOGGLE_COMMENT_LIST`
* Also notice that `meta.analytics.category` field is "Claims Folder"

**Comment by astewarttistatech** [comment]
@mmlumba The AC is a tad bit confusing, should I be looking for "CATEGORIES.CLAIMS_FOLDER_PAGE" or is that incorrect based on @NickHeiner comment?

**Comment by mmlumba** [comment]
@astewarttistatech The action should be "CATEGORIES.CLAIMS_FOLDER_PAGE"

**Comment by astewarttistatech** [comment]
I updated the AC for clarity

**Comment by kierachell** [comment]
**PASSED**
Looks like the event category and action align now:
<img width="626" alt="screen shot 2017-10-23 at 8 53 36 pm" src="https://user-images.githubusercontent.com/18075411/31920052-781817d2-b834-11e7-8e1a-323edfe6bdf6.png">
<img width="852" alt="screen shot 2017-10-23 at 8 53 52 pm" src="https://user-images.githubusercontent.com/18075411/31920053-7829bab4-b834-11e7-898d-e6d104a40736.png">
