### ISSUE TITLE
Ensure that Sidekiq saves jobs in Redis and restarts them after the deploy

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3039]
During a deploy, autoscaling groups will terminate "old" instances and replace them with new ones. If an old instance is in the middle of running a job, that job will die in the middle and never be re-run.

We should follow the [recommended deployment practices for sidekiq](https://github.com/mperham/sidekiq/wiki/Deployment) to ensure that no jobs are ever lost. This will involve changes to our deployment scripts.

**Comment by evankroske** [comment]
The fact that the correct operation of Sidekiq requires that EC2 instances never fail tells me that we should switch to a better tool. When an EC2 instance fails, there's no opportunity to safely shut down anything

**Comment by evankroske** [comment]
> Sidekiq uses BRPOP to fetch a job from the queue in Redis. This is very efficient and simple but it has one drawback: the job is now removed from Redis. If Sidekiq crashes while processing that job, it is lost forever.
—https://github.com/mperham/sidekiq/wiki/Reliability#using-super_fetch

**Comment by pkarman** [comment]
we use shoryuken now
