### ISSUE TITLE
[Backend] Implement Vacols attribute accessors for Issue model

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3044]
AC:
1. Implement `vacols_attr_accessor` for the `Issue` model 
2. Set up fake values for Vacols `issues` values 

Steps to Validate
Please test in Demo and UAT:
1. In UAT, login as a judge or in Demo, login as hearing prep user
2. Go to `<url>/hearings/dockets.json`
3. Ensure `issues` key have vacols attributes set: levels, program, type, category, description, disposition, program_description, note
4. Change values for these in Vacols, retry and ensure they are updated
5. Try very hard to break it

**Comment by astewarttistatech** [comment]
@aroltsch The AC in your PR and this ticket are two different things. Which one should I go by? This ticket's AC caused an error (see below)
<img width="1440" alt="screen shot 2017-08-28 at 1 27 01 pm" src="https://user-images.githubusercontent.com/23038505/29785301-0afb0666-8bf5-11e7-9697-96da90c2c3b1.png">

...versus the PR AC wanted me to look at the JSON response to show that the Issues had that new attribute.

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: Terminal

Steps to Validate: 
1. Open up Rails console in UAT for Certification
2. Run the Hearings.to_hash["issues"] query
3. Validate that fake (or real) data comes back with information about the issues. 

Screenshots: 
<img width="1436" alt="screen shot 2017-08-28 at 1 39 18 pm" src="https://user-images.githubusercontent.com/23038505/29785708-92fe6d54-8bf6-11e7-82ff-60b58c05aad6.png">
