### ISSUE TITLE
Comments | Adding comment via alt+c should open sidebar

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3053]
Currently when adding a comment using the keyboard (alt + c) we will not show the sidebar if it's hidden. We should automatically show the sidebar when you place a comment.
![annotation from keyboard with closed menu](https://user-images.githubusercontent.com/3885236/29629266-3e80fbe6-8806-11e7-90fa-b2f7f90af2b7.gif)

**Comment by kierachell** [comment]
**PASSED**
![sidebar](https://user-images.githubusercontent.com/18075411/31950821-793fa7da-b8aa-11e7-95dc-af2d97e59cd3.gif)
