### ISSUE TITLE
Daily Docket: Notes Field criteria

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3058]
As a judge, I would like to see all the notes in the notes field all the time.

1) Display the notes field like the comments box in Reader. It should automatically expand to show the entire note instead of scrolling.

1) Remove character limit on the notes field? (ideal scenario would be not to have one, unless VACOLS RO view does)

**Comment by lakohl** [comment]
@joofsh or @sharonwarner does the notes field in the VACOLS RO view have a character limit?

**Comment by sharonwarner** [comment]
@lakohl the limit in vacols is 100 characters

**Comment by lakohl** [comment]
@sharonwarner good to know. Eventually, I would like to change this limit. But for now, the hearing coordinators need to be able to see what the judge writes in their view of VACOLS - and I'm assuming they won't be able to see anything over 100 characters. So it sounds like we have to stick to 100 characters for now.  + @annienguyenUSDS for awareness
