### ISSUE TITLE
[Frontend/Backend] Hearing Worksheet | Connect page to real data from backend Part 5

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3062]
Prerequisite backend tickets:

#2953
#2954
#2955

Prerequisite frontend ticket:
#2857

Populate the hearing worksheet page header with read-only values from the backend

Acceptance Criteria

On initial pageload, populate the date and the hearing type with the correct information from the backend.

**Comment by kierachell** [comment]
**PASSED**
<img width="334" alt="screen shot 2017-09-19 at 4 39 36 pm" src="https://user-images.githubusercontent.com/18075411/30614445-70c95770-9d59-11e7-9374-51367b7b6848.png">
<img width="541" alt="screen shot 2017-09-19 at 4 40 11 pm" src="https://user-images.githubusercontent.com/18075411/30614444-709d8c62-9d59-11e7-9a33-1acabd785e1c.png">
