### ISSUE TITLE
Update hearings tests to avoid setTimeout

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3064]
We use setTimeout in three unit tests: DailyDocketContainer-test.js, DocketsContainer-test.js, and HearingWorksheetContainer-test.js. 

We need to update them to use the setTimeout helper methods found in AsyncTests.js instead.

Acceptance Criteria:

- No hearings karma unit tests have any setTimeouts

**Comment by slj** [comment]
The unit tests mentioned above are karma-, Chrome-based tests. The AsyncTest helpers are for node-based tests.

The `sinon/spy` approach may work...
