### ISSUE TITLE
Hearing Prep Worksheet | PDF/Print Version

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3067]
As a judge, I would like to be able to have information on the veteran and the issues on appeal at my fingertips during a hearing, along with notes I took when preparing for the hearing. I would like these to be easy to read, and to take up as little space/number of pages as possible while still affording me room on the page to take notes during a hearing. There are moments when I need to print and/or download the Hearing Worksheet. 

A condensed PDF/print version of the hearing worksheet is important me as a judge because:
- It takes some time to prepare for a hearing, and I do not trust the VA systems to always work when I need to access this info. This is frustrating and awkward, especially on Travel Board.

- If I write in one color pen while I prepare for a hearing and another color pen when I take notes during the hearing, I can distinguish when I made the annotation.

- I prefer to make eye contact with the veteran during the hearing. I do not want to be typing and looking at a screen while s/he is talking as that may seem disrespectful.

- I'm use to writing quick notes by hand. I use them to review the later when entering them and/or handing them over to lawyer.

- Typing on keyboard in the hearing room can be distracting and loud.

A/C: 
- When I click the 'Save as PDF' on the worksheet button (https://github.com/department-of-veterans-affairs/caseflow/issues/3068) on the bottom of the page, I will see the browser pop-up dialog for to print or save PDF version of the hearing prep worksheet. 
- Font size is 11pt
- Spacing is tightened to fit more on the page, 6pt between line break
- Remove "trash" icon
- Remove "Add Issue" button
- Preliminary impressions boxes and text should fit on the page
- If Multiple Appeal Streams, separate with line
- If Multiple Issues separate with line
- Remove box outlines for text fields, except for "Preliminary Impressions"
- If Judge has made notes in text boxes, it should print and fit all notes on PDF
- If Judge has marked any Preliminary Issues, they should be marked on the PDF
- If Judges add issue row, show text. Do not show box borders.

- Keeping Veteran/Appellant info on Page 1 and 2 (front and back) on top of the pages will help the judge with who veteran/appellant/rep info when taking notes. 
-  Keep all Appeal Streams and Appeal Issues on page one as much as possible, and notes section (Periods and circumstance, Contentions, Evidence, and Comments to attorneys) on page 2 (back), and allow more room to write.
- If issues move to page 2, carry over titles ( Program, Issue, Levels 1-3, Notes, Preliminary Impressions). Titles only need to exist once per page. 
- Spacing for "Periods and circumstances" can be made smaller and up to the text that is filled out.
Condense the notes section (Periods and circumstance, Contentions, Evidence, and Comments to attorneys) on Page 2, and can continue to page 3.
- Want to make the PDF version of the hearing worksheet to fit on the two pages (as much as possible).
- Add page number on bottom right of the page in footer for print.

mock that match current UI below: 

Front page:
![hearing worksheet print front](https://user-images.githubusercontent.com/22620270/33283116-d877291a-d378-11e7-9b2f-a9f359710bf4.jpg)

If issues do not fit on page 1, continue on page 2:
![hearing worksheet print back2](https://user-images.githubusercontent.com/22620270/33283256-3c6e97e6-d379-11e7-9a5e-fa8bb7b4d77c.png)

Page 2: 
![hearing worksheet print back](https://user-images.githubusercontent.com/22620270/33283101-caa22e70-d378-11e7-9099-dd883659f2e5.png)

**Comment by lakohl** [comment]
might consider adding a 'download .pdf' link or the like instead of a button that says 'print'

**Comment by annienguyenUSDS** [comment]
@lakohl would do you think of "Save as PDF" or Download PDF"? How do other products title this? (cc @MikeLewisUSDS-VA to keep tabs on language across products)

**Comment by laurjpeterson** [comment]
#3068 is button ticket

**Comment by nickheiner-usds** [comment]
![image](https://user-images.githubusercontent.com/25331532/33086941-356d17b8-ceb7-11e7-8b57-81d0d727c37a.png)

@annienguyenUSDS, in your mock, the fourth column says "Description". In the UI, it currently says "Notes". Is that discrepancy intentional? Did you want the column name to change from "Notes" to "Description" for print mode?

**Comment by nickheiner-usds** [comment]
@annienguyenUSDS in the current app, "Periods and circumstances of service" comes first, and "Contentions" comes second. 

![image](https://user-images.githubusercontent.com/25331532/33087588-0566f1b8-ceb9-11e7-8a01-3573afc786f5.png)

In your mockup, it's reversed:

![image](https://user-images.githubusercontent.com/25331532/33087608-1425064a-ceb9-11e7-89b7-682286dbcbf3.png)

Is this intentional?

**Comment by lakohl** [comment]
@NickHeiner Good catch! We just pushed the change from 'Description' to 'Notes' in the online version to be more consistent with the VACOLS labeling. These mocks were made before that. But, yes indeed we should use 'Notes' in the print version too.

**Comment by nickheiner-usds** [comment]
![image](https://user-images.githubusercontent.com/25331532/33088590-04a365a6-cebc-11e7-8f3d-9def3849393b.png)

@annienguyenUSDS or @lakohl the "Issues" is variable-length, so I can't ensure that it'll fit on the first page. Is it ok if the full printout is 3 or more pages when there are many issues?

**Comment by nickheiner-usds** [comment]
In the mockup, the header font size looks smaller relative to the normal content.

Mockup:
![image](https://user-images.githubusercontent.com/25331532/33088668-445a19ce-cebc-11e7-9c0f-09563cb2c845.png)

Live app:
![image](https://user-images.githubusercontent.com/25331532/33088657-3eaa2a32-cebc-11e7-9500-2cd5b4cc43e9.png)

Is this intentional? Do you want me to be changing this just for the print view?

**Comment by nickheiner-usds** [comment]
@annienguyenUSDS the "Preliminary Impressions" section does not match between the code and the mockup. Is this intentional?

Code:

![image](https://user-images.githubusercontent.com/25331532/33091054-07855290-cec4-11e7-8af1-fd27894fe516.png)

Mockup:

![image](https://user-images.githubusercontent.com/25331532/33091071-0ee4bc56-cec4-11e7-89fd-a2a7b51322d0.png)

**Comment by annienguyenUSDS** [comment]
@NickHeiner, we had made changes to UI since the ticket for PDF so thanks for all the catches. Want to follow the update UI order of information, and for "Preliminary impressions."
Want to condense the font of the header to fit better for print version so yes, smaller than the current.
For printing, yes if there's multiple issues we will want Judges to be able to print them all.

**Comment by nickheiner-usds** [comment]
> For printing, yes if there's multiple issues we will want Judges to be able to print them all.

Ok, and we'll just accept that this means that the worksheet won't always fit neatly on two pages?

**Comment by nickheiner-usds** [comment]
> Want to follow the update UI order of information, and for "Preliminary impressions."

I'm not sure if you're telling me to make the changes here or not. In either case, if the changes are for the whole UI and not just print mode, then those can be done in a follow-up ticket since this PR is already over-sized.

**Comment by nickheiner-usds** [comment]
> Want to condense the font of the header to fit better for print version so yes, smaller than the current.

I'm just going to eyeball what font size we want since there is none mentioned in the spec 😄. If you'd like specific font sizes, I can do that too.

**Comment by kierachell** [comment]
# AC is outdated; I have no clue what this ticket is for anymore.

- there is no differentiation between page 1 and 2 as far as I can tell:
<img width="715" alt="screen shot 2017-11-23 at 9 47 52 am" src="https://user-images.githubusercontent.com/18075411/33178282-ac7d7a00-d033-11e7-964e-0c7c8d7485c5.png">

- Check boxes are squished:
<img width="555" alt="screen shot 2017-11-23 at 9 48 59 am" src="https://user-images.githubusercontent.com/18075411/33178289-b41ea3b0-d033-11e7-8ef3-1ee548bb5718.png">

- Why is there two headers? The *Hearing Worksheet* info is repeated inconsistently
<img width="1415" alt="screen shot 2017-11-23 at 9 44 43 am" src="https://user-images.githubusercontent.com/18075411/33178321-d2511c0a-d033-11e7-9cd9-d988419eb8d3.png">

- Appeal Stream subsections have weird background color:
<img width="98" alt="screen shot 2017-11-23 at 9 51 26 am" src="https://user-images.githubusercontent.com/18075411/33178365-f2b0eac0-d033-11e7-9a3e-5c038f5307ea.png">

- Rep name is offset lower than other fields:
<img width="589" alt="screen shot 2017-11-23 at 9 52 00 am" src="https://user-images.githubusercontent.com/18075411/33178401-0e88481a-d034-11e7-8c00-7ac69c1d4ab2.png">

- Are the checkboxes/textboxes to be editable? How does this differ from the previous page?
<img width="524" alt="screen shot 2017-11-23 at 9 52 44 am" src="https://user-images.githubusercontent.com/18075411/33178432-242b8632-d034-11e7-9a99-8dc60c0467b3.png">
<img width="550" alt="screen shot 2017-11-23 at 9 53 20 am" src="https://user-images.githubusercontent.com/18075411/33178439-29537458-d034-11e7-9a66-a300e805e0df.png">

**Comment by annienguyenUSDS** [comment]
Working on updating the A/C & mocks to match latest UI

**Comment by annienguyenUSDS** [comment]
@kierachell updated A/C and mocks
