### ISSUE TITLE
Hearing Worksheet | Add button to Save as PDF

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3068]
As a judge, I want to be able to see a condensed Hearing Worksheet PDF version. When I click on "Save as PDF" and I can download the worksheet to print if I need to or save for my attorney on their drive. 

A/C: display secondary button below worksheet to the left of "Review eFolder" : "Save as PDF"

When they click the button, the PDF will download. They can decide to move or print it, but will not open up.

Mock below:
<img width="593" alt="screen shot 2017-10-19 at 8 34 13 pm" src="https://user-images.githubusercontent.com/22620270/31800160-e80f7556-b50c-11e7-969b-441962da8e98.png">

**Comment by nickheiner-usds** [comment]
This will be done as part of #3067.
