### ISSUE TITLE
Hearing Prep Worksheet | Adding Issue

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3069]
***WIP ticket***

As a Judge, I want to be able to add one or multiple issues my Hearing Prep Worksheet online as notes to myself for prep and/or during the hearing with the Veteran. This is helpful so I can hear
additional issue from another appeals stream during a hearing and/or so that I can make a correction to existing issues on the worksheet. This worksheet is used to write down notes, thoughts and initial impressions during the hearing, but is not the final outcome. I give these to their attorneys when they are writing the decision (could be years) later to help give context, but I want them to use the notes as a reference point.  

A/C:
-  "+ Add Issue" secondary button is below all issues in each Appeals Stream Section
- Clicking on "+ Add Issue" secondary button that will add another numbered row and show blank fields, preliminary checkboxes & remove icon in a row below all issues and above the button in the issues section. 
- Filling it out any of the new fields in a row is not required
- Ability to add additional rows by clicking on button
- Not required to have text in field box to add another issue
- For new issue added, field boxes will remain on the page that are editable 
- Issues listed (not added) cannot be editable, expect for field box for description
- If text in description field is long, box will resize to show all text

Mock below:
<img width="576" alt="screen shot 2017-08-24 at 2 36 28 pm" src="https://user-images.githubusercontent.com/22620270/29682946-c03134d8-88da-11e7-9bd1-d1be20c00bbf.png">

Clicking on button will add a row:
<img width="574" alt="screen shot 2017-08-24 at 2 36 42 pm" src="https://user-images.githubusercontent.com/22620270/29682958-c641d4ae-88da-11e7-83c3-acba0c5105a2.png">

Adding multiple issues:
<img width="576" alt="screen shot 2017-08-24 at 2 36 53 pm" src="https://user-images.githubusercontent.com/22620270/29682959-c94e78d2-88da-11e7-973c-d5cf236b7120.png">

**Comment by annienguyenUSDS** [comment]
On hold until we conduct these interviews with judges:
https://github.com/department-of-veterans-affairs/caseflow/issues/2632

**Comment by annienguyenUSDS** [comment]
Discussed with @lakohl @sharonwarner, updated the info above, and ready to be broken down into smaller tickets.

**Comment by kierachell** [comment]
### Why does everything shift?
![moves](https://user-images.githubusercontent.com/18075411/31413548-c43feea2-ade7-11e7-8dce-bcbe8e141d78.gif)

### CHARACTER LIMITS... PLS...
<img width="989" alt="screen shot 2017-10-10 at 6 20 31 pm" src="https://user-images.githubusercontent.com/18075411/31413554-c8a32478-ade7-11e7-9b00-3ecc15a57847.png">

### Textboxes gone wild: why can I expand them so much?
<img width="1092" alt="screen shot 2017-10-10 at 6 21 23 pm" src="https://user-images.githubusercontent.com/18075411/31413565-de3b5972-ade7-11e7-8839-af072aeed29a.png">

**Comment by sharonwarner** [comment]
We have another card for everything shifting: #3478, and we have another card for character limits: #3186. 

The textboxes and the delete modal should already be fixed.

**Comment by astewarttistatech** [comment]
Can't access Hearings Worksheet because the Veteran ID/Appellant is missing (There is an issue for this, just forgot the number). Current View: 
<img width="1325" alt="screen shot 2017-10-17 at 1 52 10 pm" src="https://user-images.githubusercontent.com/23038505/31680613-d453ef72-b342-11e7-9ed8-f4d317d5175b.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in : Preprod
Browser: Chrome 

Steps to Validate: 
1. Access Hearing Prep
2. Navigate to the Hearing Worksheet
3. Navigate to the Issues section
4. Add issues with and without text 

Screenshots: 
![addingremoveissue](https://user-images.githubusercontent.com/23038505/31682941-7c3ec972-b349-11e7-9552-c3397d762957.gif)
![addingremoveissue2](https://user-images.githubusercontent.com/23038505/31682942-7c58c430-b349-11e7-8341-6a4203ee3073.gif)
<img width="1363" alt="screen shot 2017-10-17 at 2 42 44 pm" src="https://user-images.githubusercontent.com/23038505/31683057-ce0fb0cc-b349-11e7-82d7-ad33bd859d72.png">
