### ISSUE TITLE
Flesh out "cancel certification" flow

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#307]
We received feedback that the word "Can't certify" was confusing b/c the user thought it was an error that Caseflow itself couldn't certify the case. We should change this to "Cancel certification"

Also we need to add a confirmation to let the user know what will happen if they cancel and we should capture optional feedback to understand why they are cancelling it. Here are mocks:

![cannotcertify_01_modal](https://cloud.githubusercontent.com/assets/6335546/11602172/413fa3a4-9aa6-11e5-9c91-ce0c58e2c6b6.png)
![cannotcertify_02_feedback](https://cloud.githubusercontent.com/assets/6335546/11602173/41422dcc-9aa6-11e5-9f82-3249d538374b.png)
![cannotcertify_03_confirmation](https://cloud.githubusercontent.com/assets/6335546/11602174/41452c70-9aa6-11e5-80cc-0a5be46df1f0.png)

**Comment by webinista** [comment]
Closing this issue because the flow is fleshed out. One of the tasks that originated from this is done. The other needs a database, and is on hold until we get one.

**Comment by mebates** [comment]
We need "Are you sure?" modals as well for certify.SBA.gov. Right now we're using the default javascript alert box.
