### ISSUE TITLE
[Frontend] Hearing Worksheet | Update Redux to allow for multiple appeal streams

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3070]
We currently are hardcoding redux to always update the first appeal in the appeal stream. We need to determine which appeal is being edited, and update the issues for that appeal.

Prerequisite: 
#2967, #3198 

AC:
- For a hearing with multiple appeal streams, Redux is correctly configured to load and update information for each appeal.

**Comment by astewarttistatech** [comment]
@sharonwarner If I am reading into this AC correctly, I am to check to see if a hearing with multiple appeals doesn't create any Redux errors when going through the happy path?

**Comment by sharonwarner** [comment]
Correct, thanks!

**Comment by astewarttistatech** [comment]
**FAILED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate: 
1. Access a css_id that has access to Hearing Prep
2. Navigate to the Upcoming Hearing Days page
3. Open Inspector and use the Redux plugin
4. From that page, select a date of the hearing
5. No Daily Docket page shows up (show error in console) 

Screenshots: 
![reduxhearings2](https://user-images.githubusercontent.com/23038505/30550098-71c9f6d4-9c64-11e7-9a54-34b810d0342a.gif)

**Comment by nolawi** [comment]
Ok thanks..

**Comment by kierachell** [comment]
**PASSED**
<img width="452" alt="screen shot 2017-09-18 at 3 18 13 pm" src="https://user-images.githubusercontent.com/18075411/30560053-b2ad11de-9c84-11e7-8387-e8b0f88f276b.png">
<img width="531" alt="screen shot 2017-09-18 at 3 18 31 pm" src="https://user-images.githubusercontent.com/18075411/30560054-b2afe94a-9c84-11e7-806e-09ff62e48679.png">
<img width="538" alt="screen shot 2017-09-18 at 3 18 39 pm" src="https://user-images.githubusercontent.com/18075411/30560055-b2bcffcc-9c84-11e7-9990-78e76f7fcf0d.png">
