### ISSUE TITLE
[Frontend] Hearing Worksheet | Edited field on issue inputs

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3073]
We need to designate when the Redux state has been edited to know if we should send a request for the backend.

Prerequisite:
#3070 

AC:
When a user updates Preliminary Impressions or description in the issues section, a field, 'edited', is added to the Redux state at the appeal's **issue level that's equal to true.**

Notes:
Do not do update anything for fields not in the issues section.

**Comment by kierachell** [comment]
**PASSED**
<img width="631" alt="screen shot 2017-09-28 at 8 11 32 am" src="https://user-images.githubusercontent.com/18075411/30965826-c4fe7920-a424-11e7-8f9d-3bf46ed95f73.png">
<img width="1140" alt="screen shot 2017-09-28 at 8 12 06 am" src="https://user-images.githubusercontent.com/18075411/30965827-c502df38-a424-11e7-898e-b1a6629b6d85.png">
