### ISSUE TITLE
Hearing Prep Worksheet | Removing Issue

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3075]
WIP ticket

As a Judge, I want to be able to remove one or multiple issues from my Hearing Prep Worksheet online as notes to myself for prep and/or during the hearing with the Veteran. This is helpful so I can make corrections to existing issues on the worksheet and have a more accurate list of the issues on appeal.

A/C:
1. Display a remove ([trash icon](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Trash_Can_Blue.svg)) on the far right of each issue in the row under the Appeals Stream. 
1. Confirm that clicking on the trash can icon will highlight the row and prompt a pop-up modal asking the judge to confirm that they want to remove the issue and entire row. 
1. Confirm that clicking Yes, will remove the row. 
1. Confirm that emoving the row will not remove it from VACOLS (as noted in pop-up) but will only remove it from the Hearing Worksheet.
1. Confirm that if the row desired to be removed is not the last one and that affects ordering, issues order number will be updated.
1. Confirm that all issues can be removed, but removed one row at a time right now. 
1. Confirm that when all issues are removed, the add issue button will remain. 

Mock below: 

Remove icon on the far right of each issue row:
<img width="576" alt="screen shot 2017-08-24 at 2 36 28 pm" src="https://user-images.githubusercontent.com/22620270/29698949-2bc9cda8-8927-11e7-91dc-d6cbddbbb83d.png">

Clicking on remove icon will highlight the row and prompt to confirm will pop up:
<img width="575" alt="screen shot 2017-08-24 at 11 46 36 pm" src="https://user-images.githubusercontent.com/22620270/29698973-475681ce-8927-11e7-8026-a41ed4d84970.png">

Clicking on "Yes" will remove the highlighted row, and adjust number order to issue if last issue is not removed:
<img width="577" alt="screen shot 2017-08-24 at 11 46 58 pm" src="https://user-images.githubusercontent.com/22620270/29698989-69ffffb6-8927-11e7-8f00-23de864bf948.png">

When all issues are removed, add issue button will remain:
<img width="577" alt="screen shot 2017-08-24 at 11 59 29 pm" src="https://user-images.githubusercontent.com/22620270/29699152-7b6f0dea-8928-11e7-8d71-acb733759c69.png">

**Comment by annienguyenUSDS** [comment]
On hold until we conduct these interviews with judges during pilot:
#2632

**Comment by kierachell** [comment]
### Delete: I am not deleting a VACOLS issue
<img width="1152" alt="screen shot 2017-10-10 at 4 34 16 pm" src="https://user-images.githubusercontent.com/18075411/31409158-f1519b98-add8-11e7-8d2e-70ceff489346.png">

**Comment by annienguyenUSDS** [comment]
When a Judge has added an issue on the worksheet, and then wants to delete it, we will show the Judge a modal to confirm the removal: 

<img width="376" alt="screen shot 2017-10-11 at 2 04 43 pm" src="https://user-images.githubusercontent.com/22620270/31458660-c04dac4c-ae8e-11e7-8eb3-dca256248557.png">

**Comment by astewarttistatech** [comment]
Can't access Hearing Worksheet, missing Appellant/Veteran ID on Daily Docket (There is an issue out for it, just forgot the number). Current view: 
<img width="1325" alt="screen shot 2017-10-17 at 1 52 10 pm" src="https://user-images.githubusercontent.com/23038505/31680685-07872882-b343-11e7-861a-a58855786fff.png">

**Comment by astewarttistatech** [comment]
Don't know if when an issue is removed the numbering fixes itself to go back in chronological order, instead of just missing one @annienguyenUSDS  but otherwise this is 

**PASSED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate:
1. Access Hearing Prep
2. Navigate to Hearing Worksheet
3. Remove an issue, verify it against the AC
4. Remove all issues, verify that the 'Add Issue' button will remain.

**Comment by annienguyenUSDS** [comment]
@astewarttistatech yes, if Issue Row is deleted out of number, it should reorder with new number so the example above when 9 is deleted, the issues after should make the issues follow 9, 10, 11, 12 instead of 9, 11, 12.

**Comment by astewarttistatech** [comment]
Pushing this back @sharonwarner with the changed req. from @annienguyenUSDS

**Comment by annienguyenUSDS** [comment]
@astewarttistatech would be good to test multiple streams to see renumbering of issues. If an issue is deleted or added to appeal stream 1, issues should also reorder in consecutive order in appeal stream 2 like above.

**Comment by astewarttistatech** [comment]
Just another note, when you refresh the page, it brings back the deleted comments. 

![welpitsbroken](https://user-images.githubusercontent.com/23038505/31683362-cce81846-b34a-11e7-9ea5-ca2e9fbd8b6e.png)

**Comment by annienguyenUSDS** [comment]
Deleting and adding issues keeps the issues in order, however, it doesn't delete the count. See mock below. Also weird spacing between added issues and first issue:
<img width="914" alt="screen shot 2017-10-19 at 9 44 55 pm" src="https://user-images.githubusercontent.com/22620270/31801534-ddaffe0a-b516-11e7-9f30-3bbf1fcc0115.png">

**Comment by sharonwarner** [comment]
The spacing and the numbering will both be fixed in #3390.

**Comment by kierachell** [comment]
**PASSED**
![issues](https://user-images.githubusercontent.com/18075411/32078356-b0e87bfa-ba74-11e7-8d37-f867ad9d2fa5.gif)
