### ISSUE TITLE
To determine System Admin access, refer to Redis instead of to properties on the user model whenever we want to determine system admin access.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3076]
Redis should be the source of truth for System Admin users, instead of CSS. We should provide a Functions class that allows us to add role data to Redis. Use FeatureToggle in caseflow-commons as a reference (we should namespace similarly). 

## Acceptance Criteria
- CSUM/CSEM users with “System Admin” function should not be able to access Caseflow system admin pages
- After running `Functions.grant("System Admin", users: ["CSS_ID"])` on a Caseflow instance, user `CSS_ID` and only user `CSS_ID` should: 
    - be able to access all Caseflow apps (see `User.can?`)
    - and also the stats pages (see `User.admin?`) 
    - be able to see the "Change Functions" tab on UAT
- Subsequently running `Functions.grant("System Admin", users: ["CSS_ID2"])` should ensure that only user CSS_ID2 is a system admin (i.e. it overrwrites the previous array)
- Running `Functions.grant("Reader", users: ["CSS_ID"])` should store data for that function in Redis, but not do anything else for now (we'll handle that in a future ticket)

**Comment by kierachell** [comment]
**PASSED**

```
User.where(css_id: "CASEFLOW_283")
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."css_id" = $1  [["css_id", "CASEFLOW_283"]]
[2017-09-06 19:50:34 -0400]   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."css_id" = $1  [["css_id", "CASEFLOW_283"]]
=> #<ActiveRecord::Relation [#<User id: 12, station_id: "283", css_id: "CASEFLOW_283", full_name: "TEST THIRTEEN", email: "  caseflow@va.gov", roles: ["User", "System Admin", "Download eFolder"]>]>
```

<img width="923" alt="screen shot 2017-09-06 at 7 52 52 pm" src="https://user-images.githubusercontent.com/18075411/30139632-fe01a60a-933c-11e7-8c14-9fe10551c797.png">

### Trying Reader:
```
Functions.details_for("Reader")
=> {:users=>["CASEFLOW_283"]}
```

<img width="923" alt="screen shot 2017-09-06 at 7 52 52 pm" src="https://user-images.githubusercontent.com/18075411/30139640-0bfbd280-933d-11e7-9e9d-022a475c8127.png">


### Sysadmin:

```
Functions.grant!("System Admin", users: ["CASEFLOW_283"])
=> true
```

<img width="537" alt="screen shot 2017-09-06 at 7 54 37 pm" src="https://user-images.githubusercontent.com/18075411/30139703-805c7d50-933d-11e7-976a-85bb881c014b.png">


### The only problem is that when you `flushall` that... wipes the whole Redis

**Comment by amprokop** [comment]
wait isn't that a big problem lol

**Comment by amprokop** [comment]
oh i see it's just the test suite. still, that's probably a bug, we should just flush the namespace

**Comment by kierachell** [comment]
Yeah, I passed because you have https://github.com/department-of-veterans-affairs/caseflow/issues/3116

But it would be nice to limit it to namespace, yes
