### ISSUE TITLE
Document viewer | Add new shortcuts to modal

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3083]
# Story
Users need to see how Saving a comment can be entered on the keyboard shortcut link. 

# AC
- [ ] Add "Save a comment" under "Place a comment" in the keyboard shortcut modal. 
- [ ] Create new table section "Navigate Reader" with "View next document", "View previous document" followed by new features, "Open/Hide Menu" and "Back to document list." 

# Mockup
![image](https://user-images.githubusercontent.com/13420618/30009169-2107fe7e-90f4-11e7-9542-43cb30ff5f72.png)

Dependent story
Back to document list | https://github.com/department-of-veterans-affairs/caseflow/issues/3165
Saving a comment | https://github.com/department-of-veterans-affairs/caseflow/issues/2928
Open/Hide menu | https://github.com/department-of-veterans-affairs/caseflow/issues/3164

**Comment by gnakm** [comment]
![image](https://user-images.githubusercontent.com/13420618/30008100-7e582050-90e9-11e7-9268-662f84aecb91.png)

@abbyraskinUSDS Which of the two do you prefer? The table headers for the new shortcuts aren't active. Halp!

**Comment by abbyraskinUSDS** [comment]
How about second grouping, but "navigate Reader" as last header?

**Comment by gnakm** [comment]
I like! ty!

**Comment by kierachell** [comment]
**PASSED**
![cuts](https://user-images.githubusercontent.com/18075411/31791242-fcf2510e-b4e5-11e7-8c5f-3e3cc6bc1b40.gif)
