### ISSUE TITLE
Document List | Issue tags filter is missing a scrollbar

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3084]
**Current behavior**
The issue tag filter only shows 6 items max; if you have more than 6 issue tags, you can't scroll to see/filter them.

![image](https://user-images.githubusercontent.com/4042181/29719141-01139650-8983-11e7-8859-a85f9b97802e.png)

**Expected**
- Users should be able to see/scroll through all issue tags from the issue tag filter menu
- Validate that we show half of an issue (at default length) before scroll, to help indicate that there is more.

**Comment by mdbenjam** [comment]
Known issue that you see the scroll bar even when there aren't enough elements to need to scroll.

**Comment by gnakm** [comment]
@mdbenjam and I just chatted about this. We are going to show half of the last issue so that that dropdown indicates that there is more. Adding the AC now.

**Comment by kierachell** [comment]
Ahaha , that works 👍

**Comment by kierachell** [comment]
**PASSED**
<img width="523" alt="screen shot 2017-09-25 at 9 31 45 pm" src="https://user-images.githubusercontent.com/18075411/30838342-f72f7e6e-a238-11e7-8853-16946dced21d.png">
