### ISSUE TITLE
Document Viewer | Zoom level consistency

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3086]
## Story
As a user, if I hit the zoom out button twice and then zoom in again twice, it won't show the same amount of documents from the previous views. 
## Description
Per our story time discussion, seems like the end points are different from where it's being zoomed in and out from. 

## AC
- [ ] Make sure that document viewer shows the same amount of documents at the same zoom level.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
