### ISSUE TITLE
Refactor | Remove other components from DocumentsTable.jsx

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3093]
The DocumentsTable file is very large, we should remove the definition of other components from its file.

# AC
- [ ] Verify all non-table components defined in DocumentsTable.jsx are moved to their own files.

**Comment by kierachell** [comment]
**PASSED**

Don't really care what files you put all this crap, as long as the table looks usable:
<img width="1138" alt="screen shot 2017-10-23 at 9 34 02 pm" src="https://user-images.githubusercontent.com/18075411/31920910-f54a1318-b839-11e7-87d7-55700b668515.png">
