### ISSUE TITLE
Refactor | Unify location of files

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3094]
Our Reader files are in three places. `client/app/components`, `client/app/components/reader`, and `client/app/reader/`. We should move everything to `client/app/reader/`. 

In the future we might move a reusable PDF component back into components. But until then everything is Reader specific.

Make sure to coordinate this move with others on team to avoid massive merge conflicts.

# AC
- [ ] Verify every file from components/reader is moved to reader/
- [ ] Verify the following files are moved from components/ to reader/
  - `Comment.jsx`
  - `CommentIcon.jsx`
  - `DocumentCategoryIcons.jsx`
  - `EditComment.jsx`
  - `Pdf.jsx`
  - `PdfKeyboard.jsx`
  - `PdfSidebar.jsx`
  - `PdfUI.jsx`

**Comment by kierachell** [comment]
**PASSED**
shit got moved...cool

**Comment by nickheiner-usds** [comment]
Thank you for doing this! It was driving me crazy. :smile:
