### ISSUE TITLE
Remove horizontal scroll bar that shows up on error page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#310]
A horizontal scroll bar or a weird shadow div occasionally shows up on the error page in IE. See screenshot below:

![mismatch](https://cloud.githubusercontent.com/assets/6335546/11602371/c76a6a12-9aa7-11e5-86a9-ee9761359f3c.png)

**Comment by alex** [comment]
Does this occur on all cases, if not can you post a specific fake-case that this occurs on?

**Comment by webinista** [comment]
It's caused by an `overflow-x: scroll` declaration that should be `overflow-x: auto`. It's already fixed in master.
