### ISSUE TITLE
[Backend] Hearing Worksheet | Periods of Service

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3101]
We need to pull the veteran's periods of service from BGS. 

AC: 
- On the initial load of a hearing, we need to pull periods of service from BGS and set it in `military_service` column on the hearing record

Notes:
See #2469 for more info.

**Comment by astewarttistatech** [comment]
@sharonwarner @aroltsch The PR attached to this says nothing about validation and neither does the AC listed. 🙃

**Comment by aroltsch** [comment]
Updated steps to validate in the PR.

**Comment by kierachell** [comment]
@aroltsch 
So you're calling BGS for every Veteran.
Say we get a week worth of hearings, with maybe 5 ish per day. That's 25 BGS calls on page load...

- big VACOLS query
- big VBMS query to check for Documents
- and now a BGS query (does it have a `can?` component?)...

I am getting 504 gateway timeout pretty regularly now

**Comment by aroltsch** [comment]
Don't worry about performance. We will be moving these calls (VBMS query to check for Documents and a BGS query) out of the dockets page to the hearing worksheet page). We have an issue: https://github.com/department-of-veterans-affairs/caseflow/issues/3293. Currently, is it slowing you down when testing?

**Comment by kierachell** [comment]
Takes 3-4 reloads before I can see the page; are we gonna have `StartHearingsDocketsJob`? 😄

**Comment by aroltsch** [comment]
@sharonwarner I can work on the #3293 once I'm done with the issues ticket if that's okay with you.

**Comment by sharonwarner** [comment]
Sounds good, thanks @aroltsch!

**Comment by astewarttistatech** [comment]
Tried Caseflow_283 and there is no value set for "military_service" the rest of the applicable css_ids cannot be toggled to work with Hearing Prep at this time. Will investigate.

**Comment by aroltsch** [comment]
@astewarttistatech an appeal with vbms_id `516517678S` has BGS military service. What you could try to do is modify a hearing's appeal record in UAT directly and set vbms_id to `516517678S`. Then go to  `/hearings/dockets.json` in the browser and check the military service for that hearing.

**Comment by aroltsch** [comment]
@astewarttistatech let me know if you need help with this

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT (rails console) 

Steps to Validate: 
1. Access Rails Console for the UAT environment 
2. Query the database for a user who has military_service value

Screenshots:
<img width="1341" alt="screen shot 2017-09-22 at 9 51 54 am" src="https://user-images.githubusercontent.com/23038505/30748626-e04bc084-9f7e-11e7-909a-92044813bdbe.png">
