### ISSUE TITLE
[Spec ticket] Manage System Admin & other roles in source control

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3103]
We want to be able to manage System Admin roles ourselves. We also want to be able to override other CSUM/CSEM roles to both enable and disable them where necessary. 

Managing roles in source-controlled code has the following benefits:
- It allows us to have easy visibility into roles we have added and removed at any given time
- It lets us manage roles without having to ssh and run code against production boxes
- It lets us check each others' work
- It lets anyone with access to the appeals-deployment repo add/remove roles (support/designers/PMs could do so fairly easily!)
- It enables easy offboarding for System Admin users in a manner that's consistent with our current offboarding (i.e., we remove a departed colleague's CSS ID from the admin list when we remove the SSH key)

The workflow to add roles would be:
 1. Add/remove the user's CSS ID from a source-controller
 2. Submit a PR, get it reviewed, merge it
 3. If we want to enable/disable roles immediately, there's a jenkins job we can use to do so
 4. If it's not urgent, we update all roles on deployment regardless

We could store the list of System Admin users and other role overrides in either Redis or Postgres. We currently store all roles in Postgres and get them straight from the CSS session. Here, we propose to sore only System Admin & our other role overrides in Redis (keeping the CSS roles in Postgres) for the following reasons:
 - Having a separate source of truth for roles we've managed and roles CSS manages is natural. We don't want to usurp CSEM/CSUM, we only want to be able to temporarily override roles where we need to, and System Admin is a "special" role that we will only give to Caseflow team members.
 - Building this in Redis will allow us to pretty much directly mimic it so we can manage FeatureToggles in code as well (which we should do!)
 - It will require less code and be more flexible if we manage our role overrides in Redis, and thus less risky

## Acceptance Criteria

There will be a number of smaller issues with their own AC here. When all the tasks are complete, we should validate with the following:

Given the following config in appeals-deployment repo (exact location and key names TBD, update this to match what we eventually decide on) 
```
application_role_overrides:
  System Admin:
    enable:
      - VACOLTID1
      - VACOLTID2
  Certify Appeal:
    enable: 
      - VACOLTID4
      - VHAISAMASTERID0
    disable:
     - VACOLTID6
  Reader:
    disable:
      - VACOLTID5
```
  - A Jenkins job exists in both UAT and prod to cause changes to propagate across all Caseflow apps (i.e. both caseflow and efolder)
  - Changes propagate on every deploy anyway
  - VACOLTID1 and VACOLTID2 have System Admin access
  - No other user has System Admin admin access, we make an exception and ignore CSUM/CSEM System Admin roles
 - VACOLTID4 and VHAISAMASTERID0 have access to features that require the Certify Appeal role, regardless of CSUM/CSEM role
 - VACOLTID6 does not have access to Certify Appeal, regardless of CSUM/CSEM role
 - VACOLTID5 does not have access to Reader, regardless of CSUM/CSEM role

## Issues

1. https://github.com/department-of-veterans-affairs/caseflow/issues/3076
2. https://github.com/department-of-veterans-affairs/caseflow/issues/3112
3. https://github.com/department-of-veterans-affairs/caseflow/issues/3113
4. https://github.com/department-of-veterans-affairs/caseflow/issues/3116
5. https://github.com/department-of-veterans-affairs/caseflow-commons/issues/115
6. https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/603
https://github.com/department-of-veterans-affairs/caseflow-feedback/issues/141
7. https://github.com/department-of-veterans-affairs/appeals-deployment/issues/790
8. https://github.com/department-of-veterans-affairs/appeals-deployment/issues/791
9. https://github.com/department-of-veterans-affairs/appeals-deployment/issues/804

**Comment by kierachell** [comment]
@amprokop 

I am wondering, considering the problem with Feedback not having Redis (https://github.com/department-of-veterans-affairs/caseflow-feedback/issues/141)  and some issues I see with the way we login from eFolder -> Caseflow

### Would it make sense to make a unified Redis cache for... well... our whole cache?

- This way there is a single source of truth for all `Functions` and `User` access control
- And we need to also consider this: https://github.com/mperham/sidekiq/wiki/Using-Redis#memory
  - at least until we completely get rid of Sidekiq.

Just an idea

**Comment by amprokop** [comment]
Hmm. Good to raise this, @kierachell.  

A few questions for you and others:
- What are the issues you see with logging in from eFolder -> Caseflow?
- Do we want to migrate the eX frontend to React and put it in Caseflow?
- Are there other uses for a shared cache?

The Feedback workaround is ultimately **fairly** trivial. We could always just run Redis then drop Functions in there, it'd be not too much work.

**Comment by nemodjuric** [comment]
We decided not to go with Redis for feedback, being an overhead
We will just have a simple Admin table
As for single Redis for all apps - there are some performance concerns as Redis being lightweight.
https://redislabs.com/blog/benchmark-shared-vs-dedicated-redis-instances/
Redis Labs
Benchmark: Shared vs. Dedicated Redis Instances
Benchmark analysis of shared vs. dedicated Redis instances.

**Comment by kierachell** [comment]
One of the reasons is to:
- not have to run 3 separate caches/tables
- eFolder is sorta the source of truth for roles/authentication (from CSEM, at least) right now
- If the Caseflow <-> eFolder integration goes on, you can pass a simpler request to eFolder via the cache:
  - store document list in the cache
  - store User ID in the cache for access/sensitivity checks

### Not related but why not:
- eFolder React sounds dandy as it could possible be added to commons after that? Can we migrate Styleguide to commons and then load it "as needed" during eFolder's migration?

**Comment by evankroske** [comment]
We should preserve the boundaries between eFolder, Caseflow, and Feedback and not share Redis. The coupling introduced by sharing Redis isn't worth the cost savings. These systems should communicate using APIs, not shared databases

**Comment by kierachell** [comment]
Good point... make a CSEM login microservice!

**Comment by amprokop** [comment]
This is complete!
