### ISSUE TITLE
Caseflow Feedback Admin | Really long words break the UI

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3105]
**Description**
If there's a really long word submitted in Caseflow Feedback, the UI breaks, and there's no way to read the feedback as a result. We should probably wrap the text in a smarter way.

**Screenshot**
![image](https://user-images.githubusercontent.com/4042181/29780667-9692a898-8be4-11e7-8712-297c072f385e.png)

**Comment by Sjones352** [comment]
@mmlumba and @kierachell currently page looks like this.
<img width="1084" alt="screen shot 2017-08-30 at 5 52 37 pm" src="https://user-images.githubusercontent.com/23080951/29896944-e3e578b8-8dac-11e7-9aec-fec1f384811f.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="1010" alt="screen shot 2017-08-31 at 5 53 38 pm" src="https://user-images.githubusercontent.com/18075411/29946955-60f567a0-8e75-11e7-848a-04fc4c06b7bc.png">
