### ISSUE TITLE
TextareaField component should not look up `length` if not using character counter

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3108]
### AC

- Use of component doesn't give and error if value is null

_The component requires value, it should be able to handle `null,`  and the length should not be looked up, unnecessary calculation_

**Comment by kierachell** [comment]
#### I don't know what you expect... should there be a visible character limit indicator anywhere?
<img width="572" alt="screen shot 2017-10-20 at 8 38 37 am" src="https://user-images.githubusercontent.com/18075411/31821164-2bd2af3c-b572-11e7-9e4f-a9c14cd46394.png">
<img width="458" alt="screen shot 2017-10-20 at 8 38 41 am" src="https://user-images.githubusercontent.com/18075411/31821165-2bef6992-b572-11e7-8e5a-69515292451d.png">
<img width="466" alt="screen shot 2017-10-20 at 8 38 47 am" src="https://user-images.githubusercontent.com/18075411/31821166-2c0c12fe-b572-11e7-9124-a756c9686423.png">

**Comment by kierachell** [comment]
**PASSED**
