### ISSUE TITLE
POA not pulled correctly 

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#311]
Caseflow often shows Attorneys and Agents as `Attorney - Attorney` and `Agent - Agent`. I believe these should look something like `Attorney - John Smith` and `Agent - John Smith` and we should drop the `Attorney -` or `Agent -` when filling out the Form 8.

**Comment by alex** [comment]
@plusjeff, @KHarshawat: Do either of you know where I would find this data in the VACOLS database offhand?

**Comment by alex** [comment]
I have a guess as to where it is in the DB, but I could use a record to test against. Can someone send me a BFKEY and what the expected attorney name is?

**Comment by KHarshawat** [comment]
@alex were you able to open some of the test cases that were sent to us in VACOLS? As discussed, this would probably be the best way to find out quickly what the data should look like.

**Comment by alex** [comment]
Nope!

On Mon, Dec 7, 2015 at 6:56 PM, Kavi Harshawat <notifications@github.com>
wrote:

> @alex <https://github.com/alex> were you able to open some of the test
> cases that were sent to us in VACOLS? As discussed, this would probably be
> the best way to find out quickly what the data should look like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/311#issuecomment-162709132>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
After discussing with Jed, and reviewing the database, it looks like it's fairly inconsistent whether the attorney's name is recorded in the database or not. How do you want to proceed? Do you want me to find the name when available, or something else?
