### ISSUE TITLE
Tests | Pdf component

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3115]
We have very good feature tests, but are lacking unit tests for our components. We recently deleted the remaining minimal tests we had for the Pdf component. The problem we had was with the change we made we had a new child component that connected to the redux store. Ideally we could test just the Pdf component and just use enzyme's shallow method. Unfortunately, because of how integrated this component is with actual DOM elements (look at the refs), we need to mount the component. But if we mount it, then we need to connect it to the store. If we wrap it in a provider, then it's harder to call methods directly on the Pdf instance. We need to figure out the right approach here.

Ideally we would test all the pure functions we can with unit tests, and then mount the component at a high level to do some feature tests with Enzyme.

Consider the removed test here: https://github.com/department-of-veterans-affairs/caseflow/pull/3091/files#diff-b1119a24bdf42c0e58ee25fca86bfdafL1

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
