### ISSUE TITLE
Case select change the get call to not use Veteran ID in the url

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#3117]
Brought up in the PR: https://github.com/department-of-veterans-affairs/caseflow/pull/3089

Comment from @mdbenjam 

<img width="807" alt="screen shot 2017-08-28 at 8 48 51 pm" src="https://user-images.githubusercontent.com/1976755/29799552-575bcd32-8c32-11e7-8ed5-f548f96956b5.png">

**Comment by mdbenjam** [comment]
This was moved to a header.
