### ISSUE TITLE
 Help | Create Hearing Prep Help page

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3120]
As a Case Supporter, I would like to be able to go to a Help page when I don’t understand something or need more information so that I can quickly find answers to my questions.  
 
## Acceptance Criteria
1. Verify that when the Help link is clicked from the Username Menu in the Navigation bar, the ‘Hearing Prep Help’ page is displayed.
1. Verify that the new Help page has been created with the following sections and their sub-copy (refer to mockup):

Section | Header | Sub-copy
-- | -- | --
Introduction | Welcome to the Hearing Prep Help Page! | Here you will find Training Videos and answers to the   Frequently Asked Questions (FAQs) for Hearing Prep, as well as links to the Training Guide and the Quick Reference Guide. These items are provided to   assist you as you access and use Hearing Prep. If you require further   assistance after reviewing these items, please contact the Caseflow Product   Support Team by phone (1-844-876-5548) or email (caseflow@va.gov). We look   forward to assisting you.    _(this text should be a lead-paragraph)_
Training Videos | Training Videos | Coming Soon! _(this text should be a lead-paragraph)_
FAQs | Frequently Asked Questions |  
FAQ Answers | (No header) |  

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "FAQs" is a hyperlink to the Frequently Asked Questions section.
1. Verify in the Frequently Asked Questions section, it contains listing of all questions. (Refer to [Hearing Prep FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep_FAQs_Oct2017.pdf))
1. Verify that in the FAQ Answers section, it contains all questions and their answer. (Refer to [Hearing Prep FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep_FAQs_Oct2017.pdf))
1. Verify that each question in the FAQ section is a hyperlink to its answer.
1. Verify that clicking on 'back to top' takes you to the top of the page.

## Mocks
Same as Dispatch mocks, but replace "Dispatch" with "Hearing Prep".

![dispatch help page](https://cloud.githubusercontent.com/assets/23316107/24629755/2d27b224-1888-11e7-9029-d0a7096c3860.png)

# Related Stories
**_PM/Training Issues_**
IP | Hearing Prep | Create Engineer Story for Training Material Additions [#1557](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1557)
Hearing Prep | FAQs | Develop/update questions - Prototype deliverable [#35](https://github.com/department-of-veterans-affairs/appeals-training/issues/35)

**Comment by wturne** [comment]
Updated links for Hearing Prep Frequently Asked Questions (FAQs). 

[HearingPrep_FAQs_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1356385/HearingPrep_FAQs_Oct2017.pdf)

**Comment by wturne** [comment]
Updated links for Hearing Prep QRG and Training Guide.  

[HearingPrep Training Guide_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1376975/HearingPrep.Training.Guide_Oct2017.pdf) 

[HearingPrep_QRG_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1376977/HearingPrep_QRG_Oct2017.pdf)

**Comment by Sjones352** [comment]
Currently Page looks like this 
**-Screenshot1_**
<img width="1031" alt="screen shot 2017-10-12 at 1 37 55 pm" src="https://user-images.githubusercontent.com/23080951/31510484-b4f8ce20-af52-11e7-8220-5948b5258c2a.png">

**-Screenshot2_**
<img width="770" alt="screen shot 2017-10-12 at 1 38 20 pm" src="https://user-images.githubusercontent.com/23080951/31510524-d147808a-af52-11e7-8f76-6f419ddfc1a3.png">

**Comment by Sjones352** [comment]
@wturne and @nikitarockz 
Currently all help pages look like this with a Back to top button
**_Screenshot1_**
<img width="771" alt="screen shot 2017-10-12 at 1 41 09 pm" src="https://user-images.githubusercontent.com/23080951/31510663-23877b7a-af53-11e7-8f1e-09ebad440514.png">

**_Screenshot2_**
Making it look like this will make it too repetitive. I think you should run it by design team.
<img width="866" alt="screen shot 2017-10-12 at 1 42 35 pm" src="https://user-images.githubusercontent.com/23080951/31510729-55944aee-af53-11e7-8041-09166585dd8e.png">

**Comment by nikitarockz** [comment]
@Sjones352 @wturne I thought the back to button was only on the bottom.

**Comment by Sjones352** [comment]
Yes it is but if you look at the FAQs, it has Back to Top on every question

**Comment by wturne** [comment]
It should be at the end of the response for each question. Since the user is clicking the hyperlinked question to get to the response. There should be a link to take him or her back to where they started. If you would like, I can take the "Back to top" out. However, I believe it makes it easier for the user to navigate the FAQs.

**Comment by Sjones352** [comment]
@wturne 
Yes I do understand that but all our help pages don't have this. I think you should create a new ticket to update all help pages with the "Back to top" link.

**Comment by kierachell** [comment]
**PASSED**
- Header accessible
- Looks noice
<img width="1209" alt="screen shot 2017-10-15 at 8 24 24 pm" src="https://user-images.githubusercontent.com/18075411/31590930-4a4c071c-b1e7-11e7-8284-3653f67b3b4a.png">
