### ISSUE TITLE
Minimize requests to Vacols and BGS requests when not needed

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3121]
In the `Hearing.rb` model there are methods:
1. to_hash
2. to_hash_with_all_information 
which will include `to_hash` data plus:
* Request to BGS to look up periods of service
* Request to VACOLS for all appeals streams
* Request to VACOLS to pull in the issues for each appeal stream

Whenever we are asking for a collection of hearings, we can use `to_hash` method to minimize Vacols and BGS calls. When we are on the hearing worksheet page, we call `to_hash_with_all_information`

AC:
1. `hearings/dockets.json?all_information=true` returns appeal streams and issues for each appeal stream
2. `hearings/dockets.json` returns minimal information
        :date,
        :request_type,
        :disposition,
        :aod,
        :transcript_requested,
        :hold_open,
        :notes,
        :add_on,
        :appellant_last_first_mi,
        :appellant_city,
        :appellant_state,
        :representative_name,
        :veteran_age,
        :veteran_full_name,
        :venue, 
       :vbms_id

**Comment by sharonwarner** [comment]
Duplicate ticket
