### ISSUE TITLE
Document Viewer |  Issue tags are not in the suggestion dropdown no more!

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3125]
# Description
When creating new issue tags and moving between documents,
they do not appear in the suggestions on other documents...

## Reproduction Steps

**Scenario 1 -**

1. Go to Document Viewer
1. Make an issue tag
1. Move to another document
1. Not see the created issue tag in the suggestion dropdown

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [TAGS?!?!?!]_**
![issue](https://user-images.githubusercontent.com/18075411/29877345-57fc78d6-8d6d-11e7-9927-ecc7bd5994a8.gif)

**Comment by abbyraskinUSDS** [comment]
FYI a user reported that it's better, but there are still bugs. She can see the tags she created in the issue tags filter, but:
> When I went to place issue tags on a document, I was initially provided the list in the dropdown and I was able to select one. After that, the other options disappeared and now I do not see my created tags in the drop down.

**Comment by kierachell** [comment]
**PASSED**
![tagsareback](https://user-images.githubusercontent.com/18075411/29971906-1207df46-8ef8-11e7-847f-9ae3861f1c7a.gif)
