### ISSUE TITLE
When navigating to an appeal id that doesn't exist, we should show a 404 error

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3126]
Low priority, since users enter Certification through a link provided to them by VACOLS which ostensibly always contains an appeal id that exists in VACOLS.

![image](https://user-images.githubusercontent.com/3781835/29878371-5f3afe4e-8d70-11e7-8e95-81b92b1a27af.png)

## Acceptance Criteria
- If the user tries to navigate to an appeal that doesn't exist in VACOLS we should show a 404 page, not the Technical difficulties page

**Comment by kierachell** [comment]
Does this actually happen? I asked about this a while back but was told that VACOLS wouldn't send us to a non-existent appeal :man_shrugging:
