### ISSUE TITLE
[Frontend] Hearing Prep | Trigger save when user navigates away from current page

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3129]
When a user navigates away from the current page, we want the `AutoSave` component to trigger one final save.

Related to previous ticket https://github.com/department-of-veterans-affairs/caseflow/issues/2475

#### Acceptance Criteria
- When a user navigates away from the current page, trigger a save call

Technical Note:
- This can be accomplished using the `componentWillUnmount` React lifecycle function

**Comment by kierachell** [comment]
**PASSED**
- Checked with clicking links
- Checked with going back and forward
- Checked with not editing
- Checked that still saves every 30s
![saving30seconds](https://user-images.githubusercontent.com/18075411/30278588-c6e7d17c-96d8-11e7-84c0-cf3cd0aae131.gif)
