### ISSUE TITLE
Connect certification to Redis

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#313]
- [ ] Deploy and configure a redis instance for certification https://github.com/department-of-veterans-affairs/appeals-deployment/issues/136
- [ ] Add redis URL to deployment role (e.g., `REDIS_URL: "{{ redis_url }}"`)
- [ ] Add a redis library to Gemfile
- [ ] Modify [application.rb](https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/config/application.rb#L30) to use a redis-backed `cache_store`

_Ori edit 9/21 to put checklist in root comment_

**Comment by orischwartz** [comment]
Currently [cache is backed by in-memory](https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/config/application.rb#L30) storage. Need to use Redis so that data survives deploys across instance.

**Comment by orischwartz** [comment]
Could use https://github.com/redis-store/redis-rails:

#### Gemfile
```ruby
gem 'redis-rails'
```

#### secrets.yml
```yml
production: 
  redis_url: <%= ENV["REDIS_URL"] %>
```

#### application.rb
```ruby
config.cache_store = :redis_store, Rails.application.secrets.redis_url, { expires_in: 24.hours }
```

**Comment by shanear** [comment]
@orischwartz sounds great. I just realized efolder express also doesn't use redis for it's cache, so we need to do that there as well.

**Comment by orischwartz** [comment]
@shanear This is a pretty easy ticket that touches both deployment and application code. Any objection to adding a `contractor-ready` label to it and holding off? Or we can bang it out quickly but in my opinion it's not an urgent fix and could be valuable as educational tool.

**Comment by shanear** [comment]
@orischwartz 👍

**Comment by orischwartz** [comment]
Related to #426
