### ISSUE TITLE
Hearing Prep Help | Add link to display Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#3136]
As a Product Owner, I would like to have clearly visible and accessible links to both the Training Guide and Quick Reference Guides displayed on the Help Page, so that the users can obtain additional detailed information on how to use Hearing Prep.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. [HearingPrep Training Guide_Oct2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep%20Training%20Guide_Oct2017.pdf)
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab. [HearingPrep_QRG_Oct2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep_QRG_Oct2017.pdf)

**_FAQ Answer Section_** 

_"What is Caseflow Reader?"_
1. Verify that in the answer, the text "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [HearingPrep Training Guide_Oct2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep%20Training%20Guide_Oct2017.pdf)

_"What if I still need help?"_
1. Verify that in the answer the text "FAQs" is a hyperlink to the “Frequently Asked Questions” section.
1. Verify that in the answer the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" in the answer is clicked, the following pdf is displayed in a new tab. [HearingPrep_QRG_Oct2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep_QRG_Oct2017.pdf)
1. Verify that in the answer, the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [HearingPrep Training Guide_Oct2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep%20Training%20Guide_Oct2017.pdf)

## Mocks
**_Help Page - Introduction section requiring change_**

**_Help Page - FAQ Answers section:  First Question requiring change_**

**_Help Page - FAQ Answer section:  Last Question requiring change_**

# Related Stories
**_Engineering Pre-requisite_**
Help | Create Hearing Prep Help page #3120 

**_PM/Training Issues_**
IP | Hearing Prep | Create Engineer Story for Training Material Additions [#1557](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1557)
Hearing Prep | Quick Reference Guide | Develop/Update guide - Prototype deliverable [#36](https://github.com/department-of-veterans-affairs/appeals-training/issues/36)
Hearing Prep | Training Guide | Develop guide - Prototype deliverable [#37](https://github.com/department-of-veterans-affairs/appeals-training/issues/37)

**Comment by wturne** [comment]
Updated links for the Hearing Prep Quick Reference Guide.  

[HearingPrep_QRG_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1356283/HearingPrep_QRG_Oct2017.pdf)

**Comment by wturne** [comment]
Updated link for the Hearing Prep Frequently Asked Questions. 

[HearingPrep_FAQs_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1356308/HearingPrep_FAQs_Oct2017.pdf)

**Comment by wturne** [comment]
Updated links for the Hearing Prep Training Guide. 

[HearingPrep Training Guide_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1356362/HearingPrep.Training.Guide_Oct2017.pdf)

**Comment by kierachell** [comment]
**PASSED**
![guide](https://user-images.githubusercontent.com/18075411/31590935-739e42f6-b1e7-11e7-9e98-9ca6f1a4d361.gif)

**Comment by nikitarockz** [comment]
# Reopening
The last question doesn't have the expected links for FAQs, Training Guide, and Quick Reference Guide.

![image](https://user-images.githubusercontent.com/23063044/33565099-30dcc0d0-d8ea-11e7-8568-3ca4ab46d618.png)

**Comment by kierachell** [comment]
<img width="507" alt="screen shot 2017-12-04 at 11 54 24 am" src="https://user-images.githubusercontent.com/18075411/33565117-3e24aab4-d8ea-11e7-8ed2-8753ab7b99ab.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome

![caseflowhearings](https://user-images.githubusercontent.com/23038505/33617833-d4f4e336-d9ae-11e7-98cc-87aa5a1afed8.png)
