### ISSUE TITLE
Hearings Issues data structure 

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3137]
It looks that there is going to be multiple streams and multiple issues in our current structure for the worksheet. 
```js
  {
      veteran: {},
      appeal: {},
      streams: [{
              appeal_id: 502,
              veteran_name: "Vasiliy Pupkin",
              issues: [{
                      issue_id: 101
                  },
                  {
                      issue_id: 103
                  }
              ]
          },
          {
              appeal_id: 503,
              veteran_name: "Egor Popov",
              issues: [{
                      issue_id: 109
                  },
                  {
                      issue_id: 109
                  }
              ]
          }
      ]
  }
```
Hence if i need to update `issue_xx` - we have to loop through `streams` array and find `appeal id` then loop through `issues.` I am assuming in most case scenario there will be 1-3 streams. But the number of issues on multiple streams could be a lot. Regardless I was hoping we can flatten the issues array in a `key value pair` using the `issue id`

```js {
      veteran: {},
      appeal: {},
      streams: [{
              appeal_id: 502,
              veteran_name: "Vasiliy Pupkin",
              issues: [
                   issue_01:  {appeal_id: 79, etc },
                   issue_02:  {appeal_id: 79, etc },
              ]
          }
      ]
  }
```

**Comment by sharonwarner** [comment]
[worksheet.txt](https://github.com/department-of-veterans-affairs/caseflow/files/1265098/worksheet.txt)

I'm totally open to edits/suggestions, but that is what I thought would work well for the Redux state on the worksheet page.

**Comment by joofsh** [comment]
I agree @nolawi,  storing the issues in key/value pairs will make it easier for the frontend code. For consistency though, I would vote we do the same for the appeals stream array (what sharon does in her linked doc)

**Comment by nolawi** [comment]
Oh cool, what @sharonwarner has is even better.. completely normalized!

**Comment by aroltsch** [comment]
Are we talking about `/hearings/dockets.json` response or some other response?

**Comment by nolawi** [comment]
Yes @aroltsch 
one last suggestion.. since we will also add issues.  `streams > appeal_0 > issues > issue_0 > issue` might be confusing thus  issues > issue_0 > issue_name` or `name`

**Comment by aroltsch** [comment]
Ok, `/hearings/dockets.json` looks completely different now. We will need a BE ticket to change the response structure based on what we all agree.

**Comment by nolawi** [comment]
Resolved
