### ISSUE TITLE
Document viewer | Default zoom level

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3140]
Currently, when you zoom with a document, then navigate to the documents list page, then open another document, the zoom level resets to the default size. We should save the user's preference per session so they don't need to keep resetting the zoom level when using Reader.

## Acceptance Criteria
- If a user zooms, their preference is saved per session (within the SPA)

**Comment by oscarAtNava** [comment]
Clarification question: you want the zoom value to remain while user is in that specific list of documents in a particular claim folder? Or do you want the zoom level to remain for all cases? I suspect it is the former. Please confirm.

The zoom value is kept as local state in the PdfUI component. I just need to know how high up I need to store the zoom value.

**Comment by abbyraskinUSDS** [comment]
@oscarAtNava my original thought was the zoom level a user sets would persist across cases (per session at least?).

**Comment by oscarAtNava** [comment]
Ok, I will store their zoom preference at the session level.
