### ISSUE TITLE
Daily Docket: Notes Textarea height issue

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3142]
![2017-08-31 08 22 38](https://user-images.githubusercontent.com/1745984/29923037-0b89c7e2-8e26-11e7-8595-8d33efc328d8.gif)
AC
Make sure the text height doesn't size down too much

**Comment by kierachell** [comment]
**PASSED**

- Should the worksheet textbox expand with more text? https://github.com/department-of-veterans-affairs/caseflow/pull/3169
![expandable](https://user-images.githubusercontent.com/18075411/30279557-8f657c60-96db-11e7-91b1-2dc622de55e5.gif)
