### ISSUE TITLE
Document Viewer | Loading/Rendering get stuck when navigating too fast between documents

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3143]
# Description
When navigating between documents with more than 20 pages,
if I navigate away from a document before it full renders,
sometimes the viewer gets stuck in a loading/rendering state;
which requires going back to Document List to force the reload/render of the PDF

## Reproduction Steps

**Scenario 1 -**

1. Enable eFolder API (although can happen without it if you get large enough PDFs)
1. Go to Document Viewer
1. Find a document list with 10+ documents
1. Find a few PDF with more than 20 pages
1. Start using keyboard to move about quickly between PDFs
1. Notice that at some point the PDFs stop rendering
1. Pause and see `loading document` state get stuck

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Logs:

- JS Console
`Failed to create temp file 11 : An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.`

and 

```
Uncaught (in promise) undefined

Promise rejected (async) |   |  
-- | -- | --
  | n.drawInViewPages | @ | application-6253f26….js:27
  | value | @ | application-6253f26….js:28
  | e.notifyAll | @ | application-6253f26….js:23
  | close | @ | application-6253f26….js:52
  | closeAll | @ | application-6253f26….js:10
  | perform | @ | application-6253f26….js:10
  | perform | @ | application-6253f26….js:10
  | perform | @ | application-6253f26….js:8
  | T | @ | application-6253f26….js:8
```

## Screenshots
**_Scenario 1 - [Loadddd]_**
![noload](https://user-images.githubusercontent.com/18075411/29923272-ef442bb2-8e26-11e7-855b-36959aade06c.gif)

# Related Issues
**_Engineering_**
#2722 
#2459

**Comment by mdbenjam** [comment]
I do not believe this still happens. I think this was fixed in our large refactor.
