### ISSUE TITLE
[Discussion] Issue fields on the Hearing Worksheet

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#3144]
Discussion ticket around where issue fields from the Hearing Worksheet should come from upon refreshes.

### Background
After interviewing more judges earlier this week we more clearly understand their perspective about their hearing worksheet notes from before and during hearing - they are preliminary impressions and not from a full review of the Veteran's situation, so they should not be reflected in VACOLS. Though judges might buy into saving the issue description field and added issues at a future date, we don't want to start a pilot with this. 

Instead, we'd like for edited issue descriptions and added issues (this ticket is still in feature definition) to just save to Caseflow. We know the case where an issue will change from the time a judge preps to when they view the hearing worksheet on the hearing day is very rare, so are making the assumption this won't happen.

### Fields to discuss
- For editing issues:
  - Issue Description
- For adding issues (in feature definition):
  - Program
  - Issue
  - Levels 1-3
- Preliminary Impressions (?)

### Suggested AC
- Upon a users first load of Hearing Worksheet, all issue fields should load from VACOLS.
- Upon every subsequent load/refresh of the Hearing Worksheet, all issue fields should load from Caseflow

What is the feasibility of this suggested AC?

**Comment by lakohl** [comment]
Discussed this more with @annienguyenUSDS yesterday. We feel that we should allow judges to add, remove, and edit issues freehand during the pilot (as they have this ability today) but that these actions should not at present write back to VACOLS. 

We also discussed the fact that if down the road we do want changes to issues to write back to VACOLS, we will need to use the VACOLS convention/dropdowns for adding and editing issues. @annienguyenUSDS and I will explore a design solution for this and may decide to A/B test this approach for adding and editing issues with a subset of judges during the pilot.

However, we first want to better understand how comfortable judges currently are with adding and editing issues in VACOLS - whether they know how to do this, or currently have the occasion to.  (If they are less familiar with this process it could add time to hearing prep, not subtract from it). Our plan is to interview judges specifically on how they work with issues next week.

We would like to better understand the added value of judges correcting issues in VACOLS at the Hearing Prep stage as we know that attorneys will eventually correct the issues when they write the final decision. To learn more we are planning to interview attorneys next week to learn more about whether the judge's editing of issues in VACOLS would benefit them.
