### ISSUE TITLE
[Backend] - Replace sidekiq cron jobs with lambda+cloudwatch

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#3145]
This task ensures we can replace sidekiq-cron with Lambda Scheduled Expressions.  

In order to test effectively.  This PR will need to be merged:
https://github.com/department-of-veterans-affairs/caseflow/pull/3277

And we'll need to run the ansible-playbook specified in this [PR: #851](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/851)

**AC**
- All cronjobs are triggered reliably on time and as expected.  

This might be a challenging one to validate.  Please message Sunil to schedule a time to validate this in UAT. 

Before deploying to prod ensure the following steps are taken:

- [ ] Production CW events are generated by [ansible-playbook in this pr](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/851)
- [ ] Turn off sidekiq jobs by merging and deploying #3277

**Comment by kierachell** [comment]
I am setting up a lambda config in our TF files for low-env alerts:
https://github.com/department-of-veterans-affairs/appeals-deployment/tree/master/terraform

(very much WIP atm)
The function will use an SNS subscription to CloudWatch for trigger. Let me know if you wanna add the code to the  deployment repo so we can have a shared Lambda TF module or something like that

**Comment by sunil-sadasivan** [comment]
@kierachell amazing, thanks for that!  Yup, right now I'm just manually testing through the AWS console... I'll def need to set up the lambda config in TF.  

Very cool to hear you're using lambda with SNS.  My function at the moment uses Cloudwatch Scheduled events as a trigger.  I'll TF it probably once I get the end-to-end trigger working (mid this week).

**Comment by kierachell** [comment]
```
resource "aws_lambda_function" "caseflow_job_trigger" {
    filename = "job_trigger.zip"
    function_name = "caseflow_job_trigger"
# This setup is the most problematic:
# This role will need:
# KMS access
# DynamoDB access (for credstash)
# Assume role access given via non_MFA session
    role = "lambda_role"
    handler = "index.handler"
}

resource "aws_cloudwatch_event_rule" "daily" {
    name = "daily"
    description = "Runs a job daily"
    schedule_expression = "cron(0 * 20 * ? *)"
}

resource "aws_cloudwatch_event_target" "target_caseflow_job_trigger" {
    rule = "${aws_cloudwatch_event_rule.daily.name}"
    target_id = "caseflow_job_trigger"
    arn = "${aws_lambda_function.caseflow_job_trigger.arn}"
}

resource "aws_lambda_permission" "permission_clusterfuck" {
    statement_id = "AllowExecutionFromCloudWatch"
    action = "lambda:InvokeFunction"
    function_name = "${aws_lambda_function.caseflow_job_trigger.function_name}"
    principal = "events.amazonaws.com"
    source_arn = "${aws_cloudwatch_event_rule.daily.arn}"
}
```

**Comment by sunil-sadasivan** [comment]
Just an update, deployed the secret endpoint to UAT last night.  

Will be working with Artem to set up cloudwatch events to trigger events in production.

**Comment by sunil-sadasivan** [comment]
Deployed to production yesterday.  Dispatch jobs ran successfully with CW+Lambda.  Now I'll be moving to migrate existing sidekiq-cron jobs to the same framework so we can deprecate sidekiq-cron fully.

**Comment by kierachell** [comment]
**PASSED**

Seeing them in prod now, wooo!
