### ISSUE TITLE
Reader Help | Add link to display Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#3147]
As a Product Owner, I would like to have clearly visible and accessible links to both the Training Guide and Quick Reference Guides displayed on the Help Page, so that the users can obtain additional detailed information on how to use Reader.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. 
     [Reader Training Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader%20Training%20Guide_May2018.pdf)
1. Verify that then name of the pdf is displayed as "Reader Training Guide_May2018.pdf"
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab. 
     [Reader_Quick_Reference_Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_Quick_Reference_Guide_May2018.pdf)
1. Verify that then name of the pdf is displayed as "Reader_Quick_Reference_Guide_May2018.pdf"

**_FAQ Answer Section_** 
_"What is Caseflow Reader?"_
1. Verify that in the answer, the text "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. 

     [Reader Training Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader%20Training%20Guide_May2018.pdf)
1. Verify that then name of the pdf is displayed as "Reader Training Guide_May2018.pdf"

_"What if I still need help?"_
1. Verify that the answer copy has been changed to the following:

     > If you require further assistance after reviewing the [FAQs](), [Quick Reference Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_Quick_Reference_Guide_May2018.pdf), or [Training
Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader%20Training%20Guide_May2018.pdf), please contact the Caseflow Product Support Team by phone (1-844-876-5548) or email
(caseflow@va.gov). We look forward to assisting you.

1. Verify that in the answer, the text "FAQs" is a hyperlink to the “Frequently Asked Questions” section.
1. Verify that in the answer, the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" in the answer is clicked, the following pdf is displayed in a new tab.  

     [Reader_Quick_Reference_Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_Quick_Reference_Guide_May2018.pdf)
1. Verify that then name of the pdf is displayed as "Reader_Quick_Reference_Guide_May2018.pdf"
1. Verify that in the answer, the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. 

     [Reader Training Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader%20Training%20Guide_May2018.pdf)
1. Verify that then name of the pdf is displayed as "Reader Training Guide_May2018.pdf"

## Mocks
**_Help Page - Introduction section requiring change_**
![reader help page](https://user-images.githubusercontent.com/23038386/29930080-6059d978-8e3b-11e7-85ce-52b320d28844.PNG)

**_Help Page - FAQ Answers section:  First Question requiring change_**
![reader help page 2](https://user-images.githubusercontent.com/23038386/29930119-805f7bb0-8e3b-11e7-9c03-c15920433db5.PNG)

**_Help Page - FAQ Answer section:  Last Question requiring change_**
![reader help page 3](https://user-images.githubusercontent.com/23038386/29930158-a22dd57a-8e3b-11e7-8c7c-a84caad499a9.PNG)

# Related Stories
Reader | Quick Reference Guide | Develop/Update guide - Prototype Deliverable [#42](https://github.com/department-of-veterans-affairs/appeals-training/issues/42)
Reader | Training Guide | Update guide - Pilot Deliverable [#43](https://github.com/department-of-veterans-affairs/appeals-training/issues/43)
IP | Reader | Create Engineer Story for Training Material Additions [#1560](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1560)

**Comment by wturne** [comment]
Links for updated Reader Quick Reference Guide have been added to the Acceptance Criteria.  

[Reader_Quick_Reference_Guide_Oct2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1383615/Reader_Quick_Reference_Guide_Oct2017.pdf)

**Comment by wturne** [comment]
Added the links for the latest and greatest Reader Quick Reference Guide to the Acceptance Criteria.  

[Reader_Quick_Reference_Guide_Nov2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1583284/Reader_Quick_Reference_Guide_Nov2017.pdf)

**Comment by wturne** [comment]
Added the links for the latest and greatest Reader Training Guide, dated 29 December 2017, to the Acceptance Criteria.  

[Reader Training Guide_Dec2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1593789/Reader.Training.Guide_Dec2017.pdf)

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
