### ISSUE TITLE
Document List | Veteran name cached/displayed from previous Document List query

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3148]
## Story
When opening a new document list through the search, the Veteran's name is left over from before for a second. This is very minor but would be nice to fix for a fluid and seamless experience. 

## Steps
1. Search for one Veteran ID and open her document list
1. Search for another Veteran ID and open its document list
1. While VACOLS data loads note that 1 Veteran's name is displayed for a _brieff_ moment :drum: 

## AC
- [ ] Make sure that if there is a delay in loading Veteran name that the _"Loading..."_ message shows. 

## Gif/Mockup
![glitchyname](https://user-images.githubusercontent.com/18075411/29921939-9fbdf640-8e21-11e7-867e-ff02548f4f18.gif)

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
