### ISSUE TITLE
Add loading indicator to buttons

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#315]
Given responses from VBMS can be very slow, we need to provide some visual feedback that Caseflow is making progress. This will help ease frustration but also help drive users away from re-clicking on action buttons.

cc/ @emilyville @maryannbrody and @mollieru for design feedback

We have a few options: 
- Gif Overlay on top of the page, while lightboxing the background 
- Change the button to a loading icon 
     - like this: http://tympanus.net/Tutorials/CircularProgressButton/ 
     - or these: http://tympanus.net/Development/ProgressButtonStyles/
- Or another indicator: http://tympanus.net/Development/CreativeLoadingEffects/

I'm a fan of changing the button to a loading icon inline because the user's attention is already directed in place at the icon. Downside is this kind of breaks the Web Design Standards.

![image](https://cloud.githubusercontent.com/assets/6335546/11607731/403f8bb0-9b21-11e5-9647-0e85d3c3cae9.png)
![image](https://cloud.githubusercontent.com/assets/6335546/11607723/29eedbea-9b21-11e5-8724-b6e378a853ea.png)
![image](https://cloud.githubusercontent.com/assets/6335546/11607729/3860b892-9b21-11e5-9afa-192cdca72a92.png)

Otherwise using a full page loading indicator like these would be good:

Flat Bar at top (might have browser issues) ![image](https://cloud.githubusercontent.com/assets/6335546/11607740/9b738b9e-9b21-11e5-81af-87562081b2a5.png)
Surrounding borders  ![image](https://cloud.githubusercontent.com/assets/6335546/11607760/b532d148-9b21-11e5-8f4b-b9d2ed1ec76a.png)
Pie Timer ![image](https://cloud.githubusercontent.com/assets/6335546/11607761/c91941c4-9b21-11e5-91b3-48454d6d1fdf.png)

**Comment by maryannbrody** [comment]
Hi @KHarshawat -

I'm partial to flat bar at top -- mainly because of the reason you mentioned. It breaks web design standards.. it's really cute, though -- but I think it's weird for a button to change states. 

If the browser issues can be avoided, I vote for something like this:
![image](https://cloud.githubusercontent.com/assets/12674895/11630525/139a7d8e-9ccc-11e5-8321-f3d664755d1c.png)

**Comment by webinista** [comment]
Are we actually showing load progress, or just asking the user to wait while VBMS does something? It sounds like the latter. In which case, I think an infinitely spinning circle is the best option. It's an established convention in software and operating systems.

**Comment by alex** [comment]
Confirmed that it's the latter.

On Fri, Jan 8, 2016 at 9:13 AM, Tiffany Brown <notifications@github.com>
wrote:

> Are we actually showing load progress, or just asking the user to wait
> while VBMS does something? It sounds like the latter. In which case, I
> think an infinitely spinning circle is the best option. It's an established
> convention in software and operating systems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/315#issuecomment-170014117>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
