### ISSUE TITLE
[Frontend] Hearing Worksheet : Move issue in single container

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3153]
<HearingWorksheet.jsx>
               <HearingWorksheetStream.jsx>
                         <HearingWorksheetIssues.jsx>`
 
 perquisite tech-improvement ticket for #2950 #2838 & #3141

This way single `issue` doesn't care `issues` in which stream its on.

**Comment by kierachell** [comment]
So what do you want me to do about this? Look in the reducer? It's all mocked out?
Look in the dockets.hearings_array?
If nothing, then just close it.

**Comment by nolawi** [comment]
No, I think you should not validate this- because there was no new features or functionality. tech improvement.

**Comment by kierachell** [comment]
then close it
