### ISSUE TITLE
Document List | File count differs from VBMS

### ISSUE THREAD

**Issue by RTOLSON** [department-of-veterans-affairs/caseflow#3158]
# Description
User just opened the file now and haven't started opening any documents. There is a small discrepancy between the number of VBMS documents (79 documents without hiding duplicates) and Reader documents (82 documents).

## Reproduction Steps

**Scenario 1 -**

1. User goes to the **_Welcome Gate page_**

2. Click **_New button_**

3. On **_Document List page,_**  user sees a discrepancy in the total number of documents displayed as it compares to VBMS.

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [x] Prod

## Logs:

n/a

## Sentry:

n/a

## Screenshots
**_Scenario 1 - 

![reader document list](https://user-images.githubusercontent.com/23316043/29983814-8db81ae8-8f25-11e7-86df-47bd7a7f10a3.PNG)

# Related Issues
**_Support_**
Reader file count differs from VBMS(https://github.com/department-of-veterans-affairs/appeals-support/issues/270)

**_Engineering_**

**Comment by abbyraskinUSDS** [comment]
We haven't heard this again recently, closing for now.
