### ISSUE TITLE
Test form changes with test data

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#316]
We received around 7 sample cases from Cat at the NYRO. We should use this to make sure the Form 8 is working as intended.

**Comment by plusjeff** [comment]
Will send @paultag the encrypted list after I get to a working PIV card reader.

**Comment by plusjeff** [comment]
Test data sent to @paultag. Handing over.

**Comment by plusjeff** [comment]
@paultag Does #350 close this, or is just a step towards completing?

**Comment by paultag** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/350 closes this for sure
