### ISSUE TITLE
eFolder Integration | Timeout errors are not fake news

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3163]
# Description
Sometimes requests to eFolder will time out and cause Sentry alerts... what do we do about them?

## Reproduction Steps

**Scenario 1 -**

1. Go to Reader
1. Turn on eFolder integration
1. Start downloading PDFs (500+)
1. Get a timeout
1. See Sentry

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:
```
HTTPClient::ConnectTimeoutError

execution expired
```

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/451/

# Related Issues
**_Engineering_**
#2808 
#2834

**Comment by mdbenjam** [comment]
@kierachell is this the problem we fixed? Or are you seeing this for large cases independently of the issue we addressed last week?

**Comment by kierachell** [comment]
@mdbenjam haven't seen much more now. Keep it in backlog as y'all roll out

**Comment by kierachell** [comment]
Well, you can check the alerts channel from last week. It was nothing but timeout errors.

**Comment by lowellrex** [comment]
Pretty sure today's sentry alert is the same issue: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/540/

**Comment by mdbenjam** [comment]
We should fix this when we move the eFolder API to polling.

**Comment by aroltsch** [comment]
Closing it as Reader will be using eX v2 polling.
