### ISSUE TITLE
Document viewer | Keyboard shortcut for opening and hiding menu

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3164]
**Story**
As a user, I want a keyboard shortcut that opens and hides the side menu quickly and easily.

**Acceptance Criteria**
- Entering `alt+m` on keyboard opens and hides the side menu.

## Related
#3083 | Add new shortcuts to modal

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate: 
1. Access Reader
2. Open a document and use the `alt+m` command to open and close the side menu

Screenshots: 
![shortcut](https://user-images.githubusercontent.com/23038505/31729025-dfa43152-b3fb-11e7-9f95-ab199447bf8c.gif)
