### ISSUE TITLE
Document viewer | Keyboard shortcut for back to document list

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3165]
**Story**
As a user, I want a keyboard shortcut that can easily get me back to the document list page.

**Acceptance Criteria**
- Entering `alt+backspace` on keyboard should go back to the document list

## Related
#3083 | Add new shortcuts to modal

**Comment by kierachell** [comment]
**PASSED**
![back](https://user-images.githubusercontent.com/18075411/31820523-a7bf5daa-b56f-11e7-8009-c8266646dfc6.gif)
