### ISSUE TITLE
Welcome Gate | Modal shows active or in history status

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3166]
[WIP]
update the modal to say whether the appeal is active or in history status

**Comment by gnakm** [comment]
Brain dumping options

![image](https://user-images.githubusercontent.com/13420618/30599920-fc2ea294-9d2b-11e7-922f-602bb32f74f2.png)

**Comment by abbyraskinUSDS** [comment]
yeah, though i'd like to investigate the various VACOLS statuses again, as they're slightly more complicated. "history" status essentially means closed for the Board's purposes.

**Comment by abbyraskinUSDS** [comment]
@mdbenjam @gnakm is there any reason we shouldn't just take you to the active appeal? i.e., skip this modal if there's only 1 active appeal?

**Comment by mdbenjam** [comment]
Couple of questions here. Do we need to show cases in history status? Do people actually want to view them? If they don't we should just filter based on active cases. If they do, I don't think we should skip if there's 1 active appeal. That's extra behavior to build into the app that provides unnecessary complexity.

**Comment by nicholasholtz** [comment]
I am not sure why we need to give options to "open" the closed appeal. That is confusing, I'd argue. I am all for displaying the closed appeals, in some way, but giving the oportunity to "open" them in this way will probably lead to a lot of attorneys not understanding that all of them are going to the same place. 

Is the reasoning that the appeal the open will provide the banner information? Not sure how often that would be valuable for HIS appeals.

**Comment by mattwilcut** [comment]
As attorney, I absolutely view historical cases all the time.  For example, if the most recent decision is one that includes a failure to provide new and material evidence (NME), the "new and material" comparison is being made against a cited historical decision, which usually is not attached or quoted substantively.

It would be impossible for the ratings author to enumerate what all would qualify as NME.

It would be great to have any "active" NME decision in Caseflow have a pointer to the cited historical case to immediately reference, otherwise you have to sort by date.

**Comment by gnakm** [comment]
Alrighty -- we had a mini huddle and need to rearrange/ reprioritize how we are going to tackle this. Key things

- Change text to say appeal
- Show - Issues the way it's shown on case assigned table

Others:
- Add a message for folders without any appeals that says something like "Currently no appeals."
- Get more feedback and use cases for when judges and attorneys need to revisit history cases

We talked about adding NOD dates but right now, I don't think we need it as a unique identifier if we are showing issues and we don't have it on the table.

![image](https://user-images.githubusercontent.com/13420618/31555198-20ef0d90-b00e-11e7-9fd2-1b2df00da8d2.png)

@abbyraskinUSDS @mdbenjam Can you guys confirm this? I'll put together AC above once I get 2 thumbs up.

**Comment by abbyraskinUSDS** [comment]
Deprioritized in favor of future Queue...
