### ISSUE TITLE
Document List | New expanded comments styling

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3167]
# Story
1. New style including relevant date
2. We've gotten feedback about white space issues in the past. 

# AC
- [ ] Verify that comment box has the following in this order
    - Relevant date
    - Page number/ Jump to section link below
    - Comment text
- [ ] Verify that comment box length is now the same width as table row line
- [ ] Comment box should now be padded 25px
- [ ] There should be 45px spacing between relevant date, page number and comment

# Mock up
![image](https://user-images.githubusercontent.com/13420618/30165191-347595b4-93ad-11e7-9d38-c93b20772cd8.png)

For reference:
![image](https://user-images.githubusercontent.com/13420618/30165348-b4f5030a-93ad-11e7-858c-1cc9fadde4d6.png)

# Related
[Invision link for interaction](https://va-gov.invisionapp.com/share/AUDE0ZWWR#/254419660_1_-_Document_List)
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/391https://github.com/department-of-veterans-affairs/caseflow/issues/2983#event-1230347857
https://github.com/department-of-veterans-affairs/caseflow/issues/1082

# Note
- Ignore user name and icon for this issue

**Comment by astewarttistatech** [comment]
**FAILED**

Current View (preprod): 
<img width="1347" alt="screen shot 2018-01-04 at 10 03 27 am" src="https://user-images.githubusercontent.com/23038505/34569612-4f1004e4-f137-11e7-9557-ac2243b80922.png">

**Comment by dannysellers** [comment]
For reference, users/names who create comments are out of the scope of this ticket (see #3340). Looking into the broken border issue 👍

**Comment by mdbenjam** [comment]
@astewarttistatech what exactly was failing here?

**Comment by mdbenjam** [comment]
Just tested in UAT, and no longer see the broken comment border. Closing.
