### ISSUE TITLE
[Frontend] Hearing Worksheet | Update Reader Link

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3171]
The reader link on the hearing worksheet page should point to the appeal's eFolder with the correct category filter.

AC:
- Link goes to /reader/appeal/*vacols_id*/documents?category=case_summary

**Comment by kierachell** [comment]
**PASSED**
<img width="1305" alt="screen shot 2017-09-19 at 4 19 38 pm" src="https://user-images.githubusercontent.com/18075411/30613510-5e45d7d4-9d56-11e7-9279-ad50500e1a0e.png">
