### ISSUE TITLE
Welcome Gate modal | "Send feedback" link doesn't route from Reader

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3180]
If a user clicks on the "Send feedback" link on the multiple appeals modal, Caseflow Feedback does not know that it came from Reader (it shows as blank)

**QA NOTES:** Can only be validated in UAT.

**Comment by mdbenjam** [comment]
I have a feeling this works now. Not sure though :)

**Comment by abbyraskinUSDS** [comment]
It doesn't :-/

**Comment by abbyraskinUSDS** [comment]
It doesn't :-/ It no longer says Certification, but it shows as blank.

**Comment by astewarttistatech** [comment]
@mmlumba not sure if this is right or not. 
![readerhelp](https://user-images.githubusercontent.com/23038505/33779112-988b8540-dc19-11e7-9f6a-09bb10d42718.gif)

**Comment by mmlumba** [comment]
@astewarttistatech Can you click the feedback link from the footer to validate?

**Comment by mdbenjam** [comment]
In UAT it goes to a different app than in prod. Might be hard to test in UAT.

**Comment by kierachell** [comment]
There's no Feedback in preprod, that's why

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT | Chrome 

Steps to Validate: 
1. Access Reader
2. Access upper right user drop-down information
3.Select "Send Feedback"
4. Verify that the feedback page has text for Reader. 

Screenshots: 
![readerhelp](https://user-images.githubusercontent.com/23038505/33890597-ba938650-df21-11e7-9364-a1eb85250152.gif)
