### ISSUE TITLE
Document Viewer | Unable to highlight document text

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3183]
Users aren't able to copy document text - it looks like the focus is broken in some way. You can only highlight document text if you've started dragging/focusing areas outside the document (e.g., the toolbar).

# AC
1. Verify a user can highlight/copy text.
1. Verify placing annotations and moving annotations still works.

**Comment by kierachell** [comment]
**PASSED**
- Annotations are movable in Chrome (not Firefox)
![selectable](https://user-images.githubusercontent.com/18075411/30277627-67ce4ace-96d6-11e7-856a-a327bf80c151.gif)
