### ISSUE TITLE
[Frontend] Hearing worksheet Witness Input validation 

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3185]
connects #2890 
requires decision #3186 

AC

1. Verify that each line of the witness box can accommodate 21 characters.
1. Verify that as the user types additional lines of text in the witness box, the box scrolls to display the additional copy.
1. Verify that a user can add up to 5 lines of copy in the witness box.
1. Verify that once the user clicks out of the witness box after typing in it, the box expands to display any additional lines of copy.
1. Verify that the box remains expanded as long as more than one line of copy is present.
1. Verify that if the user deletes a line of copy from the witness box, and then clicks outside the box, the box will shrink to a height that that corresponds to the lines of copy in the box. (e.g. if there are 2 lines of copy, the box should be tall enough to show 2 lines of copy, not more.)

**Comment by lakohl** [comment]
@nolawi let me know if that makes sense to you. Trying to mimick the way the comments work in Reader.

**Comment by nolawi** [comment]
Got it! thanks @lakohl
