### ISSUE TITLE
[Frontend] Hearings Worksheet | Character limits

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3186]
Hearing Worksheet inputs should have a max character limits (recommended)

1. Rep. Name: (30)
2. Witness: (120)
3. Program: 30
4. Issue: (100)
5. Levels: (100) vacols has 156 for 3 levels
6. Description: 100 vacols (same as notes in dockets)
7. Contentions (5000)
8. Periods and circumstances of service (5000)
9. Evidence (5000)
10. Comments and special instructions to attorneys (5000)

**Comment by kierachell** [comment]
**PASSED**
<img width="576" alt="screen shot 2017-11-02 at 8 09 56 pm" src="https://user-images.githubusercontent.com/18075411/32356223-072ebfca-c00a-11e7-9724-94f5589b4dfa.png">
<img width="896" alt="screen shot 2017-11-02 at 8 10 35 pm" src="https://user-images.githubusercontent.com/18075411/32356224-073de1f8-c00a-11e7-83dc-ce1b9fb9c930.png">
<img width="1241" alt="screen shot 2017-11-02 at 8 10 55 pm" src="https://user-images.githubusercontent.com/18075411/32356225-074ef024-c00a-11e7-8290-b24c196ff1f0.png">
<img width="1320" alt="screen shot 2017-11-02 at 8 11 06 pm" src="https://user-images.githubusercontent.com/18075411/32356226-075d2360-c00a-11e7-8426-3c8c1218e920.png">
<img width="403" alt="screen shot 2017-11-02 at 8 11 21 pm" src="https://user-images.githubusercontent.com/18075411/32356227-0771c7e8-c00a-11e7-9eee-8d3f5b236e1e.png">
<img width="429" alt="screen shot 2017-11-02 at 8 11 23 pm" src="https://user-images.githubusercontent.com/18075411/32356228-078db23c-c00a-11e7-93b5-d13105641458.png">
