### ISSUE TITLE
[Backend] Rename DB columns and other things

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3189]
1. Rename DB columns: 
 `issues` table: hearing_worksheet_reopen => reopen, hearing_worksheet_vha => vha
`hearings` table: remove worksheet prefix from all columns
2. Rename `appeals` => `appeals_ready_for_hearing` in `to_hash_with_all_information` method
3. Rename `to_hash_with_all_information` to `to_hash_with_streams_and_issues`
4. dockets.json should call `to_hash` instead of `to_hash_with_appeals_and_issues`

**Comment by kierachell** [comment]
#### Issues table:
```
Issue id: 446, appeal_id: 1962, vacols_sequence_id: "1", reopen: false, vha: false, allow: false, deny: false, remand: false, dismiss: false
``

### Appeals and hashes:
```
"2017-07-24": {
    "date": "2017-07-24T00:00:00.000-04:00",
    "type": "central_office",
    "regional_office_name": "Roanoke, VA",
    "hearings_array": [
      {
        "id": 80,
        "user_id": 12,
        "appeal_id": 1945,
        "vacols_id": "184186",
        "witness": null,
        "contentions": null,
        "evidence": null,
        "military_service": null,
        "comments_for_attorney": null,
        "date": "2017-07-24T00:00:00.000-04:00",
        "request_type": "CO",
        "disposition": null,
        "aod": null,
        "transcript_requested": null,
        "hold_open": null,
        "notes": null,
        "add_on": null,
        "appellant_last_first_mi": null,
        "appellant_city": "Lewisville",
        "appellant_state": "TX",
        "representative_name": null,
        "veteran_age": 57,
        "veteran_full_name": "Otha F Evans",
        "venue": {
          "city": "Milwaukee",
          "state": "WI",
          "timezone": "America/Chicago"
        },
        "cached_number_of_documents": 11,
        "cached_number_of_documents_after_certification": 3,
        "vbms_id": "156292244S"
```
