### ISSUE TITLE
VBMS::SOAPError: Unable to parse SOAP message

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#3192]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/365/

app/services/external_api/vbms_service.rb in block in send_and_log_request at line 127
app/services/metrics_service.rb in block in record at line 12
Called from: benchmark.rb in measure
app/services/metrics_service.rb in record at line 11
app/services/external_api/vbms_service.rb in send_and_log_request at line 124
app/services/external_api/vbms_service.rb in fetch_document_file at line 30
app/models/document.rb in fetch_and_cache_document_from_vbms at line 106
app/models/document.rb in fetch_content at line 115
app/models/document.rb in content at line 119
app/models/document.rb in serve at line 123
app/controllers/document_controller.rb in pdf at line 29
Called from: action_controller/metal/implicit_render.rb in send_action
app/middleware/metrics_collector.rb in call at line 14
Called from: rack/deflater.rb in call
app/middleware/metrics_auth.rb in call at line 10
Called from: puma/configuration.rb in call

Nokogiri::XML::SyntaxError
Premature end of data in tag Envelope line 1
app/services/external_api/vbms_service.rb in block in send_and_log_request at line 127

    MetricsService.record("sent VBMS request #{request.class} for #{vbms_id}",
                          service: :vbms,
                          name: name) do
        @vbms_client.send_request(request)
    end

  rescue VBMS::ClientError => e

**Comment by mdbenjam** [comment]
We no longer use this API in reader. Everything comes through eFolder. And we haven't seen the error in 2 months. Closing for now.

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8613

**Comment by alisan16** [comment]
Closing this issue since it's so low priority, if the errors occur more frequently we can re-open and actually work on it in the future.
