### ISSUE TITLE
Refactoring Broke Prerendering and Cleanup

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3203]
The latest change to #2826 broke pre-rendering and cleanup. Since we were looking for the pdfDocument in the state to draw documents, when we didn't clean it up properly, we would leave old documents in the DOM. We also didn't always fill pdfDocument correctly in the state, which broke prerendering.

# AC
1. Only the current, previous, and next docs should be in the DOM.
1. The previous and next document should be pre-rendered, and moving to the next or previous document should be quick.

**Comment by kierachell** [comment]
***PASSED**
Whatever you did there... it's totally fast now holy shit:
![onlysee3](https://user-images.githubusercontent.com/18075411/30211359-b57b2b80-946e-11e7-9bf2-cd27e555af62.gif)
