### ISSUE TITLE
WHERE IS THE MEMORY LEAK

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3205]
We still have a memory leak that users report. Investigate where it is.

# How do I reproduce this (without connecting to efolder)?
1. Add 50 more PDFs to the static list of data in Fakes:AppealRepository::static_reader_documents: https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/fakes/appeal_repository.rb#L320
1. Update the switch statement in Fakes:VBMSService::fetch_document_file to return megadoc for several IDs: https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/fakes/vbms_service.rb#L28
1. Go to http://localhost:3000/reader/appeal/reader_id1/documents
     - If you're not authorized, click on the username in the upper right corner and switch to a `Reader User`
1. Open a document a start scrolling down and clicking through 'Next documents'

**Comment by kierachell** [comment]
### I am still getting Loading locks in UAT
- I spent 10 minutes just exploring the profiler while that document was loading...
<img width="553" alt="screen shot 2017-09-10 at 8 05 46 pm" src="https://user-images.githubusercontent.com/18075411/30254300-453fca4a-9664-11e7-8800-c7837a0f18a8.png">

### I am still getting high CPU usage, which can totally bring down slower machines
- getDocument function takes a long time...
```
n.getDocument = function(e) {
                return [].concat(a(n.props.prefetchFiles), [n.props.file]).includes(e) ? E["default"].get(n.predrawnPdfs, [e, "pdfDocument"]) ? Promise.resolve(n.predrawnPdfs[e].pdfDocument) : n.isGettingPdf[e] ? new Promise(function(t) {
                    return setTimeout(function() {
                        n.getDocument(e).then(function(e) {
                            t(e)
                        })
                    }, k)
                }
                ) : (n.isGettingPdf[e] = !0,
                n.loadingTasks[e] = m.PDFJS.getDocument({
```

**Comment by mdbenjam** [comment]
Closing this as our refactor seemed to fix most of it.
