### ISSUE TITLE
Revert change #3193

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3209]
Change https://github.com/department-of-veterans-affairs/caseflow/pull/3193 pulled in more cases. This revealed that we're making four queries to VACOLS for every appeal pulled in. This could be dozens of appeals. We're reverting this change until we can address the underlying issue.

**Comment by kierachell** [comment]
**PASSED**

Used to be 35... now it's 13 :(
<img width="586" alt="screen shot 2017-09-08 at 8 23 17 am" src="https://user-images.githubusercontent.com/18075411/30211438-07548384-946f-11e7-9980-c5833ff01662.png">
