### ISSUE TITLE
Record edits made to defaults on Form 8

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#321]
Start recording changes made to a Form 8 from the defaults. This will be helpful in determining how useful our defaults are.

It's possible the best way to do this is a JSON blob. Might be helpful to know exactly how we'll query the data.

**Comment by shanear** [comment]
@cmgiven @KHarshawat what's the prioritization on this one? can we leave this out of the current sprint?

**Comment by cmgiven** [comment]
Figuring out how to use this data is on my plate for this sprint, but I was already assuming it would be next week at the earliest. In my view, this is far less important than starting to track certifications in postgres. Don't know what else this is competing with.

**Comment by KHarshawat** [comment]
@shanear @cmgiven also seems like it'd be an easy one for a contractor to start out with. Adding the "contractor-ready" label. Doesn't need to be done this sprint from my perspective though.

**Comment by shanear** [comment]
@amprokop this is donsies right?

**Comment by amprokop** [comment]
yep.
