### ISSUE TITLE
Move CaseAssignmentRepository to AppealRepository

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3213]
After writing CaseAssignmentRepository we determined that it should really be a part of AppealRepository since it already does most of what we want it to do. Furthermore, we've added fields to Appeal's `to_hash` that we're not querying for in CaseAssignmentRepository and have to get those fields by calling `set_vacols_values` in AppealRepository. We should move the functionality from CaseAssignmentRepository into AppealsRepository.

# AC for developer to confirm:
1. Create a new function in AppealsRepository that takes a css_id and queries VACOLS for all appeals that are checked into that location.
1. Call this new function wherever CaseAssignmentRepository was being used.

# AC for QA:
1. Verify the welcome gate still shows the cases assigned to a given user.
   - Verify the issues are still displayed in the table.
   - Verify whether the case is AOD is still displayed in the table.
1. Verify the welcome gate still allows users to search for veteran IDs.

**Comment by astewarttistatech** [comment]
Sorry @mdbenjam these requirements are a little too vague.

**Comment by mdbenjam** [comment]
@astewarttistatech I've updated the AC to have some criteria confirmed by me, and some AC confirmed by you. I've confirmed my end.

Also linking to this ticket which is part 2: https://github.com/department-of-veterans-affairs/caseflow/issues/3498

**Comment by tejans24** [comment]
Sorry, I should have updated the AC on this issue.

**Comment by kierachell** [comment]
### Why does this attorney have all AOD cases? Is it because one of them comes back AOD from a bulk query?
![all_aod](https://user-images.githubusercontent.com/18075411/31591005-8c1a559e-b1e8-11e7-9fcd-0951a9ed57d9.gif)

**Comment by tejans24** [comment]
@kierachell there is an issue for this: https://github.com/department-of-veterans-affairs/caseflow/issues/3565 

Which I am currently working on.

**Comment by mdbenjam** [comment]
Moving this back to in-validation since there is already an issue for that.

**Comment by mdbenjam** [comment]
Also @kierachell what attorney is that in UAT? Last time I checked @tejans24 was looking for a good test user for this.

**Comment by kierachell** [comment]
**PASSED**
@tejans24 found the fix, I think
