### ISSUE TITLE
Refactor DailyDocketContainer

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#3219]
Per [these comments](https://github.com/department-of-veterans-affairs/caseflow/pull/3114/commits/cf44e365db3ecf25d43af28378db39bd9cf5fa8e#r137584217)

- Remove `dockets` as a property into the component. We should replace this with `docket`. The DailyDocketComponent only cares about its one specific docket, not the collection of all dockets

- Always call `getDockets` when the component mounts. We should move the conditional check to `mapDispatchToProps`. When the function is called (on component mount) we can check if the dockets array already exists in the redux store. If it does, the function call can no-op.

**Comment by slj** [comment]
I don't think we need to do the first change, because:

- `DailyDocketsContainer` passes a single docket to the `DailyDocket` container
- Dockets need to be retrieved when the user refreshes the screen

I've submitted a [WIP PR](https://github.com/department-of-veterans-affairs/caseflow/pull/3220) for the second change.  I'd like to discuss the first change with @joofsh .

**Comment by joofsh** [comment]
Good point @slj . Okay let's leave the `dockets` parameter for now

**Comment by kierachell** [comment]
**PASSED**

Refreshing page reloads the data? right?
![reload](https://user-images.githubusercontent.com/18075411/30279118-4be8b3d6-96da-11e7-9ada-17f914e846f8.gif)
