### ISSUE TITLE
Form 8:  Record users involved in certification.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#322]
Record the user that completed each certification.

Add the unique id from the Users table as a foreign key to the certifications table.

Acceptance criteria:
QA by manually taking a screen shot.

**Comment by shanear** [comment]
This is blocked until we start using CSS.

**Comment by astewarttistatech** [comment]
Can someone add the QA'd screenshot to this?

**Comment by amprokop** [comment]
it's in PR #486
