### ISSUE TITLE
Document Viewer | Find doesn't always find everything.

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3229]
**Current**
When you ctrl+f search for a word in a document, it doesn't always find all the matching terms. I observed this bug with a user, and noticed that when she searched for a word, it would say there were only, for example, 19 results found. Once she had navigated to the 19th term, the number would increase, to say more results were found.

**Expected**
- When a user searches using ctrl+f, the browser displays the total number of matching terms

**Comment by mdbenjam** [comment]
Covered in #3658
