### ISSUE TITLE
FeatureToggle | Remove :reader feature toggle check.

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3230]
In development the :reader feature keeps getting turned off. We have to re-run seeds.rb to turn it back on. This is annoying especially since we've turned on the :reader feature toggle in production.

# AC
1. Verify there is no :reader feature toggle checking code.
1. Verify access to the app still works if a user has the correct role.

**Comment by kierachell** [comment]
**PASSED**
```
FeatureToggle.disable!(:reader)
=> true
irb(main):004:0> FeatureToggle.details_for(:reader)
=> nil
irb(main):005:0> FeatureToggle.features
=> [:dispatch_partial_grants_remands, :dispatch_full_grants, :certification_v2, :appeals_status, :efolder_docs_api]
```
<img width="1295" alt="screen shot 2017-09-12 at 8 06 38 am" src="https://user-images.githubusercontent.com/18075411/30325096-6d6dc552-9791-11e7-97a2-54697cc73c33.png">


Next step would be to migrate it to @nemodjuric 's Functions for pilot users
