### ISSUE TITLE
dispatch/establish-claim route does not check for Establish Claim role

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#3236]
Currently, this route is accessible even if user has no Establish Claim role set. 

Step to reproduce / Acceptance Criteria:
- Log in with a user that does not have the Establish Claim role
- Try to access the main dispatch route `/dispatch/establish-claim`
- Verify you get the drat! page

**Comment by kierachell** [comment]
**PASSED**

-- Functions disabled
<img width="1211" alt="screen shot 2017-09-16 at 4 14 36 pm" src="https://user-images.githubusercontent.com/18075411/30515658-56886a74-9afa-11e7-9abf-b0af6ae65718.png">
<img width="1120" alt="screen shot 2017-09-16 at 4 14 42 pm" src="https://user-images.githubusercontent.com/18075411/30515656-56878618-9afa-11e7-9c9a-c4b63f91b5c4.png">

- Checking Work History
<img width="1253" alt="screen shot 2017-09-16 at 4 14 51 pm" src="https://user-images.githubusercontent.com/18075411/30515659-56899804-9afa-11e7-9456-28b60747c07c.png">

- And as Manager for both?
<img width="1277" alt="screen shot 2017-09-16 at 4 15 22 pm" src="https://user-images.githubusercontent.com/18075411/30515657-56883e0a-9afa-11e7-9a2d-f4b219898868.png">
