### ISSUE TITLE
[Certification] Remove admin_roles feature for System Admins

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#3238]
Currently having System Admin role only is not sufficient to access Caseflow app pages. One would still need admin roles added on /functions page.
Ideally, we would like to get rid of admin_roles and power up System Admin role to be self sufficient.

**Comment by kierachell** [comment]
**PASSED**
Functions be gone now!
<img width="774" alt="screen shot 2017-09-19 at 2 44 38 pm" src="https://user-images.githubusercontent.com/18075411/30609431-634f0f0a-9d49-11e7-8262-fa75c66576ab.png">

other pages are all accessible:
<img width="844" alt="screen shot 2017-09-18 at 9 44 30 pm" src="https://user-images.githubusercontent.com/18075411/30609446-6d37d6a0-9d49-11e7-8ade-cc045cd6751d.png">
<img width="869" alt="screen shot 2017-09-19 at 2 44 33 pm" src="https://user-images.githubusercontent.com/18075411/30609445-6d37997e-9d49-11e7-86ed-54f6c39408cc.png">
