### ISSUE TITLE
Document Viewer |  Cliking on Annotation textbox to jump to it makes them disappear from the PDF

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3253]
# Description
Sometimes, in a large pdf, when I click on an annotation to move to it,
the yellow icon disappears for all annotations so i dunno where they is...

## Reproduction Steps

**Scenario 1 -**

1. Go to Document with annotations
1. Click on the Annotation textboxes in the menu
1. Jump about the document
1. See the yellow icons disappear
1. Be forced to reload the document.

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Logs:

NONE! I CAN'T FIND ANY!

## Screenshots
**_Scenario 1 - [Jump to disappear]_**
![disappearingcomments](https://user-images.githubusercontent.com/18075411/30347164-2af698be-97d9-11e7-8067-aa095a52c3c2.gif)

**Comment by mdbenjam** [comment]
I'm pretty sure this was related to a bug where we used the same ids for multiple comments. I haven't seen it in a long time, so I'm closing it.
