### ISSUE TITLE
Stuck appeals unable to be processed in Dispatch

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3254]
We have 4 appeals that have been outcoded, have a decision uploaded, but are stuck and are unable to be processed in Caseflow. We need to manually resolve these 4 appeals so that they can continue to be processed. 

#### Task ids for the 4 stucks appeals:
[511, 13147, 13246, 13560]

#### All 4 are unable to be accessed/updated in BGS for the following 2 reasons:
- No Person record found
- This is a Sensitive Record and you do not have high enough access to update it

### Recommended steps to take:
- Manually invalidate these 4 task
- Reach out to a coach at AMO. Send them the VACOLS id or (veterans id?) for the 4 appeals
- Ask them to manually process them outside of Dispatch
- Create follow up actions (updates to the admin page?) to ensure coaches are aware of stuck appeals and know how to process them

**Comment by joofsh** [comment]
These 4 tasks have been invalidated:
![screen shot 2017-09-14 at 3 36 15 pm](https://user-images.githubusercontent.com/2256237/30452067-7620b34e-9962-11e7-8a4f-b79446c91360.png)

**Comment by joofsh** [comment]
Note: No QA is required

**Comment by lakohl** [comment]
I reached out to Edwin Massiah the ARC Coach and confirmed that of the 4 cases, 1 case was missing the 'zero' at the front of the Vet ID, 2 cases were VA employees, and 1 case was Level 8 Sensitivity.
Edwin established and EP for the claim missing the zero, and I reached out to Mike Edsall and John Shriver about the remaining 3 case. Mike is looking into how to handle them, and said he would get back to me.

**Comment by kierachell** [comment]
@lakohl please close this when everything is fully resolved

**Comment by kierachell** [comment]
@joofsh We have a `created_at` field for each task. I know we "recreate" some tasks, but maybe we can have a counter in `recreated` and/or `reprepared` columns that will let us know if a task has been "bouncing about" for too long (a week+?)

**Comment by lakohl** [comment]
Mike E. said AMO would handle these particular cases, but I never heard back from AMO about how to handle similar ones in the future.  Have reached out again to see if I can get a clear answer.

**Comment by lakohl** [comment]
I messaged Dayna and Edwin about a new instance of this issue on 4/6. She said she would check with their ISSO to figure out who should work it as nobody at ARC can.

**Comment by lakohl** [comment]
We are handling these on a case by case basis at the moment.
