### ISSUE TITLE
Convert Hearing Prep top nav to React

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3260]
The top navbar for Heaing Prep is currently rendered on the rails side. Recently a new [NavigationBar](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/NavigationBar.jsx) component was added and used in Reader. We should convert to using the same component in React so that we can update it in the SPA

#### AC
- Top Nav is rendered via React

**Comment by nolawi** [comment]
No @lakohl
