### ISSUE TITLE
Convert Hearing Prep top nav header to React

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3261]
The top navbar for Heaing Prep is currently rendered on the rails side. Recently a new [NavigationBar](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/NavigationBar.jsx) component was added and used in Reader. We should convert to using the same component in React so that we can update it in the SPA

#### AC
- For all pages in hearing prep, the header is rendered in React
- Ensure breadcrumbs update correctly as you navigate between pages

**Comment by mmlumba** [comment]
Waiting for breadcrumb implementation from https://github.com/department-of-veterans-affairs/caseflow/issues/2364

**Comment by kierachell** [comment]
**PASSED**
<img width="717" alt="screen shot 2017-09-28 at 8 15 15 am" src="https://user-images.githubusercontent.com/18075411/30965977-36c7f9c8-a425-11e7-9916-b4216bad3476.png">
<img width="710" alt="screen shot 2017-09-28 at 8 15 19 am" src="https://user-images.githubusercontent.com/18075411/30965978-36cda51c-a425-11e7-9e3f-6b0d9cbc7704.png">
<img width="905" alt="screen shot 2017-09-28 at 8 15 23 am" src="https://user-images.githubusercontent.com/18075411/30965979-36cdedf6-a425-11e7-87a5-baacd29e685e.png">
