### ISSUE TITLE
Certification V2 Help | Add link to display Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#3262]
As a Product Owner, I would like to have clearly visible and accessible links to both the Training Guide and Quick Reference Guides displayed on the Help Page, so that the users can obtain additional detailed information on how to use Certification.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that in the "Welcome to the Certification Help Page!" section, the copy has been updated to the following:
     >  Here you will find [Training Videos]() and answers to the [Frequently Asked Questions (FAQs)](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Certification.v2.FAQs_Jun2017.pdf) for Certification, as well as links to the [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/CertificationV2_Training.Guide_Jun2017.pdf) and the [Quick Reference Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Certification.V2.QRC_Final_Jun2017.pdf). These items are provided to assist you as you access and use Certification. If you require further assistance after reviewing these items, please contact the Caseflow Product Support Team by phone (1-844-876-5548) or email (caseflow@va.gov). We look forward to assisting you. 

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab.
[CertificationV2_Training.Guide_Jun2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/CertificationV2_Training.Guide_Jun2017.pdf)
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab.
[Certification.V2.QRC_Final_Jun2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Certification.V2.QRC_Final_Jun2017.pdf)

**_FAQ Answer Section_** 
1. Verify that answer to the question "What is Caseflow Certification?" has been updated to the following copy:
     > Caseflow Certification is a web-based tool that streamlines the certification process by checking case documents for readiness and ensuring accuracy of the Veteran’s representative and hearing preferences. The tool was built by the United States Digital Service at the Department of Veterans Affairs, in close collaboration with Decision Review Officers and other employees in VA regional offices all over the country. Learn more: [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/CertificationV2_Training.Guide_Jun2017.pdf).
1. Verify that answer to the question "What if I still need help?" has been updated to the following copy:
     >  If you require further assistance after reviewing the [FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Certification.v2.FAQs_Jun2017.pdf), [Quick Reference Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Certification.V2.QRC_Final_Jun2017.pdf), or [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/CertificationV2_Training.Guide_Jun2017.pdf), please contact the Caseflow Product Support Team by phone (1-844-876-5548) or email (caseflow@va.gov). We look forward to assisting you. 
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. [CertificationV2_Training.Guide_Jun2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/CertificationV2_Training.Guide_Jun2017.pdf)
1. Verify that the text "FAQs" is a hyperlink to the “Frequently Asked Questions” section.
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab. [Certification.V2.QRC_Final_Jun2017.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Certification%20V2/Certification.V2.QRC_Final_Jun2017.pdf)

## Mocks
**_Help Page - Introduction section requiring change_**
![certv2](https://user-images.githubusercontent.com/23038386/30395222-72c52010-9893-11e7-8b1b-52642f037d79.PNG)

**_Help Page - FAQ Answers section:  First Question requiring change_**
![capture](https://user-images.githubusercontent.com/23038386/30396852-0082fb48-9899-11e7-8986-acd0a1942f40.PNG)

**_Help Page - FAQ Answer section:  Last Question requiring change_**
![capture](https://user-images.githubusercontent.com/23038386/30396888-1a99a48c-9899-11e7-90e8-13cbe04505c3.PNG)

# Related Stories
EPIC: Certification v2 | Create/Update Training Materials [#17](https://github.com/department-of-veterans-affairs/appeals-training/issues/17)

**Comment by wturne** [comment]
Updated engineering story with links to the training materials. 

[Certification.v2.FAQs_Jun2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1318499/Certification.v2.FAQs_Jun2017.pdf) 

[Certification.V2.QRC_Final_Jun2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1318500/Certification.V2.QRC_Final_Jun2017.pdf) 

[CertificationV2_Training.Guide_Jun2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1318501/CertificationV2_Training.Guide_Jun2017.pdf)

**Comment by kierachell** [comment]
**PASSED**

<img width="1116" alt="screen shot 2017-10-19 at 8 13 24 pm" src="https://user-images.githubusercontent.com/18075411/31799768-27010188-b50a-11e7-901d-8e11cef60437.png">
<img width="1098" alt="screen shot 2017-10-19 at 8 13 49 pm" src="https://user-images.githubusercontent.com/18075411/31799769-270aea36-b50a-11e7-8fab-c1db44126c08.png">
<img width="987" alt="screen shot 2017-10-19 at 8 14 01 pm" src="https://user-images.githubusercontent.com/18075411/31799770-271438fc-b50a-11e7-96c6-5115cd252e48.png">
<img width="840" alt="screen shot 2017-10-19 at 8 14 28 pm" src="https://user-images.githubusercontent.com/18075411/31799771-271ecf9c-b50a-11e7-8510-45674a152472.png">
