### ISSUE TITLE
[Frontend] Hearing Worksheet | Design Update For Field Names

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3264]
<img width="821" alt="screen shot 2017-09-13 at 5 10 58 pm" src="https://user-images.githubusercontent.com/4306128/30400998-b7275076-98a6-11e7-91ef-e14c7aeb0846.png">

Acceptance Criteria:
- 'Rep. Name' and 'Witness (W)/Observer (O)' should not be bold. They should be styled the same way as the other field names in this section.

**Comment by kierachell** [comment]
**PASSED**

The `field name` vs `field value` is kinda bland right now... need better styling, pls.
<img width="1273" alt="screen shot 2017-09-16 at 4 13 14 pm" src="https://user-images.githubusercontent.com/18075411/30515636-fac1dc52-9af9-11e7-8318-80e096fc7dbb.png">
