### ISSUE TITLE
[Backend] Pull in travel board master records

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3266]
On the judge's homepage, we need to pull in empty travel board master records so that judges can see their upcoming schedule. 

Acceptance Criteria: 
- [ ] The judge's upcoming hearings query pulls in empty travel board master records. 

Notes from @aroltsch:

I assume css_id is their Common Security Sign-on which is also their AD domain account alias.  If that's what you're looking for, the domain alias is stored in the STAFF.SDOMAINID column. You could look-up the css_id that corresponds to TBSCHED.tbmem1, tbmem2, tbmem3, tbmem4 by doing a:
 
Select STAFF.SDOMAINID from STAFF into :vlj1 where  STAFF.SATTYID =  TBSCHED.tbmem1
Select STAFF.SDOMAINID from STAFF into :vlj2 where  STAFF.SATTYID =  TBSCHED.tbmem2
Select STAFF.SDOMAINID from STAFF into :vlj3 where  STAFF.SATTYID =  TBSCHED.tbmem3
Select STAFF.SDOMAINID from STAFF into :vlj4 where  STAFF.SATTYID =  TBSCHED.tbmem4

**Comment by kierachell** [comment]
**PASSED**
<img width="699" alt="screen shot 2017-10-15 at 8 22 17 pm" src="https://user-images.githubusercontent.com/18075411/31590900-b4fa3dbe-b1e6-11e7-92d8-635f22d4f5b8.png">
<img width="1116" alt="screen shot 2017-10-15 at 8 22 23 pm" src="https://user-images.githubusercontent.com/18075411/31590901-b505456a-b1e6-11e7-85f9-2d94cb7fd24f.png">
<img width="1216" alt="screen shot 2017-10-15 at 8 23 13 pm" src="https://user-images.githubusercontent.com/18075411/31590902-b50f51a4-b1e6-11e7-94f6-f18a31415a66.png">
