### ISSUE TITLE
[Frontend] Homepage | Remove 'Print' link

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3267]
AC: The print link should not be there

<img width="925" alt="screen shot 2017-09-13 at 5 28 06 pm" src="https://user-images.githubusercontent.com/4306128/30401639-fe65342e-98a8-11e7-8495-4513971235c5.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="1249" alt="screen shot 2017-09-16 at 4 12 15 pm" src="https://user-images.githubusercontent.com/18075411/30515626-d541fe44-9af9-11e7-9fb9-de967a522d4e.png">
