### ISSUE TITLE
[Backend] Homepage | Pull in correct number of slots and start time for each docket day

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3275]
AC: 
The hearing docket object has two methods that
- Pull in the correct number of slots for the day
- Pull in the correct start time for the day (probably have to loop through each of the hearings and get the earliest east coast time)

Notes: 
The values are in the STAFF table:
STC2 is the Travel Board limit for Mon  and Fri.
STC3 is the Travel Board limit for Tue, Wed, Thur.
STC4 is the Video limit.
 
SELECT STAFF.STAFKEY,  
         STAFF.SNAMEL,  
         STAFF.STC2,  
         STAFF.STC3,  
         STAFF.STC4,  
         STAFF.SORC1,  
         STAFF.SSPARE1,  
         STAFF.SSPARE2,  
         STAFF.SSYS 
    FROM STAFF 
   WHERE ( substr(stafkey,1,2) = 'RO' ) AND 
         ( length(stafkey) = 4 )

**Comment by aroltsch** [comment]
```The values are in the STAFF table:
STC2 is the Travel Board limit for Mon  and Fri.
STC3 is the Travel Board limit for Tue, Wed, Thur.
STC4 is the Video limit.```

**Comment by aroltsch** [comment]
Waiting on @lakohl to confirm the CO values

**Comment by aroltsch** [comment]
CO hearing days in VACOLS:  11 spots per day

**Comment by kierachell** [comment]
**PASSED**
Will have to iron the rest out later.
<img width="1126" alt="screen shot 2017-10-11 at 9 06 36 am" src="https://user-images.githubusercontent.com/18075411/31442198-98306432-ae63-11e7-957a-22987c0329bc.png">
