### ISSUE TITLE
[Frontend] Homepage | Display correct number of slots, hearings, and start time for each docket day

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3276]
AC:
- The upcoming dockets page displays the correct number of slots for each RO
- The upcoming dockets page displays the correct start time (must find the earliest hearing and display that time)

Prereq: #3275

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Chrome 
Env: UAT

Steps to Validate: 
1. Access Hearings > Upcoming Hearings Days page
2. Open Network tab and reload page
3. Verify that the slots and times are correct. 

Screenshots: 
<img width="1406" alt="screen shot 2017-10-10 at 7 52 52 am" src="https://user-images.githubusercontent.com/23038505/31385210-599f858c-ad90-11e7-83a4-7a4b90687c86.png">
