### ISSUE TITLE
[Backend] Hearing Worksheet | Store appeal issues in our database

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3278]
Prereqs:
#3285

Because we are giving our users the capability to add and delete issues, and edit their added issues, we need to store VACOLS issues in our database. We also need to differentiate between VACOLS issues and user-generated issues so that the user can edit their own issues but not VACOLS issues.

AC: 
- [ ] When we run appeal.issues from the console, and the appeal has no issues saved in our database, we hit VACOLS, save the returned issues in our database, and return the issues
- [ ] When we run appeal.issues from the console, and the appeal has issues saved in our database, we return the issues from our database
- [ ] When we save an issue from VACOLS in our database, we save a flag on the object (from_vacols?) that's set to true

**Comment by kierachell** [comment]
**PASSED**
```
WorksheetIssue.find(1087)
  WorksheetIssue Load (0.6ms)  SELECT  "worksheet_issues".* FROM "worksheet_issues" WHERE "worksheet_issues"."id" = $1 LIMIT 1  [["id", 1087]]
[2017-09-21 09:58:40 -0400]   WorksheetIssue Load (0.6ms)  SELECT  "worksheet_issues".* FROM "worksheet_issues" WHERE "worksheet_issues"."id" = $1 LIMIT 1  [["id", 1087]]
=> #<WorksheetIssue id: 1087, appeal_id: 2874, vacols_sequence_id: "1", reopen: false, vha: false, allow: false, deny: false, remand: false, dismiss: false, program: "compensation", name: "service_connection", levels: ["All Others", "Degenerative arthritis of the spine (see also diagnostic code 5003)"], description: ["15 - Service connection", "03 - All Others", "5242 - Degenerative arthritis of the spine (see also diagnostic code 5003)"], from_vacols: true>
```


<img width="649" alt="screen shot 2017-09-21 at 9 58 55 am" src="https://user-images.githubusercontent.com/18075411/30699750-92366f14-9eb3-11e7-9528-71548412126b.png">
