### ISSUE TITLE
[Frontend] Hearing Worksheet | Buttons for adding and deleting

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3279]
We need to add the buttons to allow users to add and delete hearings

AC:
- The UI should include the add button for each appeal
- The UI should include the trash button for each issue

<img width="576" alt="mock_for_ui_update" src="https://user-images.githubusercontent.com/4306128/30437912-d4f014ca-993d-11e7-9388-ed810556c4db.png">

Notes:
- The buttons should not do anything when somebody clicks on them yet

**Comment by kierachell** [comment]
**PASSED**

They're there...
<img width="1175" alt="screen shot 2017-09-16 at 5 13 53 pm" src="https://user-images.githubusercontent.com/18075411/30516071-6fd8ff86-9b02-11e7-8187-882612f3bf2c.png">
