### ISSUE TITLE
[Frontend] Hearing Worksheet | Deleting issue warning confirmation

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3280]
Prereq:
#3279 

Acceptance Criteria:
- When a user clicks on the trashcan to delete an issue, we display a warning as shown in the mock below and highlight the row
- When a user clicks either 'Cancel' or 'Yes', the warning should disappear

<img width="575" alt="remove_issue_popup" src="https://user-images.githubusercontent.com/4306128/30438886-5f0e9986-9940-11e7-952c-f380a67f1620.png">

Notes:
- Do not add the 'yes' functionality yet. That will be handled in a separate card.

**Comment by nolawi** [comment]
<img width="1074" alt="screen shot 2017-09-18 at 4 42 45 pm" src="https://user-images.githubusercontent.com/1745984/30563629-75c99470-9c90-11e7-8e5a-d0f611fb166f.png"> 
@annienguyenUSDS  this is what i am proposing take a look and let me know.. but i can modify structure to fit us

**Comment by annienguyenUSDS** [comment]
@nolawi 

- [ ] Remove the line under title
- [ ] Update title: "Remove Issue Row"
- [ ] Update text: "Are you sure you want to remove this issue from Appeal Stream 1 on the worksheet? This issue will be removed from the worksheet, but will remain in VACOLS

**Comment by nolawi** [comment]
updated new layout for QA
<img width="1245" alt="screen shot 2017-09-21 at 12 13 15 pm" src="https://user-images.githubusercontent.com/1745984/30706446-54c8362c-9ec6-11e7-9487-423c51635a5d.png">

**Comment by kierachell** [comment]
### It works but...
<img width="1282" alt="screen shot 2017-10-01 at 2 23 28 pm" src="https://user-images.githubusercontent.com/18075411/31057697-308da93a-a6b5-11e7-84ff-dc573aaafb4b.png">

- @annekainicUSDS Our Cancellation and delete modals in other apps usually have red buttons, not blue. Do you mean for the following buttons to be blue?
<img width="837" alt="screen shot 2017-10-01 at 2 23 32 pm" src="https://user-images.githubusercontent.com/18075411/31057699-3091a940-a6b5-11e7-9058-89abb721269e.png">
<img width="1314" alt="screen shot 2017-10-01 at 2 23 38 pm" src="https://user-images.githubusercontent.com/18075411/31057698-308f89f8-a6b5-11e7-9b8b-a024b1d5de12.png">

**Comment by annienguyenUSDS** [comment]
Thanks @kierachell, looking at[style guide]( http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#modals), and yes, it should be red button with "Confirm delete" and "Cancel" as a link.

The content in the modal should be the same.

**Comment by sharonwarner** [comment]
Created a new issue for the design updates: https://github.com/department-of-veterans-affairs/caseflow/issues/3483

**Comment by kierachell** [comment]
**PASSED**
easy
