### ISSUE TITLE
[Frontend] Hearing Worksheet | Deleting an issue

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3286]
Prereq: 
#3280 
#3278 

AC:
- When a user selects 'yes', we remove the issue from the redux state and the UI (the numbers should update accordingly)

**Comment by kierachell** [comment]
**PASSED**
<img width="1282" alt="screen shot 2017-10-01 at 2 23 28 pm" src="https://user-images.githubusercontent.com/18075411/31057767-f47dfd18-a6b5-11e7-9603-2ed5fe715b4f.png">
<img width="837" alt="screen shot 2017-10-01 at 2 23 32 pm" src="https://user-images.githubusercontent.com/18075411/31057768-f483c158-a6b5-11e7-9776-d7a5825ff990.png">
<img width="1314" alt="screen shot 2017-10-01 at 2 23 38 pm" src="https://user-images.githubusercontent.com/18075411/31057769-f4844f6a-a6b5-11e7-91c9-315879fc3ce9.png">
