### ISSUE TITLE
[Frontend] Hearing Worksheet | Differentiate between user and vacols created records

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3287]
The backend is adding a flag on the issues table that will be true for vacols-created records and false for user-created records. We need to display the issues differently based on that flag.

Prereq
#3285 

AC:
For program, issue, and level, 
- User-created issues are displayed as editable fields
- VACOLS-created issues are displayed as read-only

<img width="576" alt="editable_and_not" src="https://user-images.githubusercontent.com/4306128/30445235-5fc828de-9953-11e7-8756-5552c0ce04a2.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod
Browsers: FF and Chrome 

Steps to Validate:
1. Access Hearings Prep
2. Navigate to a Hearing Worksheet that has issues VACOLS and issues that are typed in
3. Verify that the issues from VACOLS cannot be edited. 
4. Verify the opposite for the other types of issues. 

Screenshots: 
![hearingworksheet](https://user-images.githubusercontent.com/23038505/30987514-459cd46a-a465-11e7-91b0-cd5243b93618.png)
