### ISSUE TITLE
[Frontend] Hearing Worksheet | Adding new issues

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3288]
Prereq:
#3287 
#3279 

AC:
- When the user clicks the 'Add Issue' button, we
    - Add a new user-created issue row
    - Add the issue to Redux
    - Set an 'edited' field on the issue to true

**Comment by kierachell** [comment]
**PASSED**
<img width="1314" alt="screen shot 2017-10-01 at 2 23 38 pm" src="https://user-images.githubusercontent.com/18075411/31057650-5297be22-a6b4-11e7-8616-ce0e047bec4c.png">
<img width="1263" alt="screen shot 2017-10-01 at 2 24 02 pm" src="https://user-images.githubusercontent.com/18075411/31057649-5297357e-a6b4-11e7-8dde-33b0d1eca7db.png">
<img width="412" alt="screen shot 2017-10-01 at 2 24 28 pm" src="https://user-images.githubusercontent.com/18075411/31057651-529dd58c-a6b4-11e7-99ba-93a754f5b3bd.png">
