### ISSUE TITLE
VBMS::HTTPError A PIF for this EP code already exists. 

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3289]
```
<ns4:exception>A PIF for this EP code already exists.  Please delete the PIF file, or select a different EP code modifier.</ns4:exception><ns4:message>Claim not established. BGS code; PIF is already in use.</ns4:message>
```

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/262/

**Comment by amprokop** [comment]
@mmlumba — is this certification-related? this looks like it would be dispatch

**Comment by mmlumba** [comment]
I don't have the original log anymore since the link above is erroring out with the message: `https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/262/`.

I'll close this ticket and re-open it if the same error reappears.
