### ISSUE TITLE
[Frontend] Daily Docket | Update hearing time

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3291]
AC:
- The start times for the hearings are correctly listed in east coast time. 

Notes: 
- The start times on the hearing object are in the RO's time zone. We need to convert the time to east coast time.

**Comment by kierachell** [comment]
### The times are not read properly. I think you're reading the Date object and not DateTime or Time object;
- in VACOLS:
<img width="219" alt="screen shot 2017-10-01 at 4 26 26 pm" src="https://user-images.githubusercontent.com/18075411/31058674-694179fe-a6c5-11e7-8bda-f8f9b87c4c91.png">

- in Caseflow:
<img width="285" alt="screen shot 2017-10-01 at 4 26 36 pm" src="https://user-images.githubusercontent.com/18075411/31058676-6d184e72-a6c5-11e7-880b-330a3868f390.png">

**Comment by kierachell** [comment]
### Pretty sure that's not what you want:

- This is from Prod. So... yeah
<img width="200" alt="screen shot 2017-10-07 at 4 52 17 pm" src="https://user-images.githubusercontent.com/18075411/31311708-f7acf7ae-ab7f-11e7-8407-3630eabd0103.png">
<img width="225" alt="screen shot 2017-10-07 at 4 52 26 pm" src="https://user-images.githubusercontent.com/18075411/31311709-f7ae0fc2-ab7f-11e7-9c0b-ac4508c5b8ed.png">

**Comment by nolawi** [comment]
Resolved in #3276 will get revalidated in that ticket.

**Comment by kierachell** [comment]
Daily docket shows incorrect times still

**Comment by aroltsch** [comment]
I can investigate this issue.

**Comment by kierachell** [comment]
**PASSED**
Since we sorta figured it out together anyway
<img width="530" alt="screen shot 2017-10-18 at 3 59 57 pm" src="https://user-images.githubusercontent.com/18075411/31739896-75475718-b41d-11e7-907a-b7d7a1744da0.png">
