### ISSUE TITLE
[Backend] Fix seed data

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3292]
After the pilot, we're going to give judges access to the demo environment so that they can learn how to use the application effectively. We need to have seed data that makes sense and is interesting. 

AC:
- Appeals should have documents that show up in Reader
- Request Type and Date should show up correctly on the worksheet page
- Mocked master records should mimic prod more closely
  - One per day
  - Making sure that master records don't have any children records

**Comment by kierachell** [comment]
**PASSED**
something is there...
<img width="1262" alt="screen shot 2017-09-26 at 5 06 14 pm" src="https://user-images.githubusercontent.com/18075411/30884302-110a99d2-a2dd-11e7-960b-1e710e8b9f20.png">
<img width="1271" alt="screen shot 2017-09-26 at 5 06 18 pm" src="https://user-images.githubusercontent.com/18075411/30884301-11076b36-a2dd-11e7-9212-a9f41ae09889.png">
