### ISSUE TITLE
Functions | Removing deny/granting to empty hashes has different behavior

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3297]
## Steps:

1. Grant functions to users
1. Deny functions to users
1. Attempt to clear the list of CSS_IDs for a function using `{}`
1. See different behaviors...
1. Be mildly annoyed.

### Logs:

```
Functions.deny!("Certify Appeal", {})
=> true
irb(main):010:0> Functions.grant!("Certify Appeal", {})
ArgumentError: missing keyword: users
```

**Comment by nemodjuric** [comment]
Array [] instead of {} should be used as per README in caseflow-commons
