### ISSUE TITLE
Dispatch Stats | Slow....and make all these VACOLS calls... and slow...

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3304]
Stats pages are slow AF on initial load

### Steps:

1. Go to Dispatch Stats
1. Get 504
1. Watchlogs and see like 1000+ queries
1. Get 504 5-6 more times
1. Finally see stats.
1 Switch to another tab of stats
1 Get 504

<img width="952" alt="screen shot 2017-09-16 at 9 46 24 pm" src="https://user-images.githubusercontent.com/18075411/30517294-7fbdf336-9b28-11e7-844c-bbc52bb5fe4c.png">

nuff said

Finally see stats after 1/2 hour

**Comment by lakohl** [comment]
@sharonwarner how long do you estimate it would take to fix this?
