### ISSUE TITLE
Document Viewer | Annotation creation error is janky

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3305]
# LOOK AT THIS THING

<img width="442" alt="30406622-fdb3007a-98c0-11e7-8f0f-3fa2240543b8" src="https://user-images.githubusercontent.com/18075411/30517307-143a44d8-9b29-11e7-9a58-5f230e505e66.png">

# UGH

related: https://github.com/department-of-veterans-affairs/caseflow/issues/2826

**Comment by mdbenjam** [comment]
It's pretty now! 

![screen shot 2018-01-10 at 5 58 01 pm](https://user-images.githubusercontent.com/3885236/34799954-db868586-f62f-11e7-8d8c-55996ef560ea.png)
