### ISSUE TITLE
Document Viewer | Moving annotation marker w/ mouse and w/ keyboard is weird

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3306]
### Is the edge of the page for placing annotation supposed to be different for mouse vs keyboard?

1. Start making annotation
1. Move the marker to the edge of the page using keyboard
1. Move it to the edge using mouse
1. Weird.

![edgelimit](https://user-images.githubusercontent.com/18075411/30406600-d9195f84-98c0-11e7-9530-5773e152531f.gif)

related #2826

**Comment by mdbenjam** [comment]
This is fixed.
