### ISSUE TITLE
Document Viewer | Annotation markers disappear!

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3307]
### Desc:

When jumping to the page with annotations sometimes all of the yellow markers for annotations diappear

### Steps

1. Click `Jump to section` in the document list
1. Or just click on the textbox of an already-created annotation (in the menu)
1. See window move to the location of the yellow markers
1. Click on another annotation (either marker or its textbox)
1. See the first one disappear
1. See inconsistent behavior (sometimes they _don't_ disappear!)
1. See them toggle disappearing
1. Go to other annotations on the document and see the marker not be present.

### Screenshots:

kinda captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/3253
![lolwut](https://user-images.githubusercontent.com/18075411/30406723-984e60b6-98c1-11e7-9d4a-a392d0d204d9.gif)

related: #2826

**Comment by mdbenjam** [comment]
This is fixed.
