### ISSUE TITLE
[Frontend] Hearing Worksheet | Blank Appellant Name

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3311]
When there is no value entered in the appellant name field, default to displaying the Veteran name in the format: [LastName, FirstName]

**Comment by kierachell** [comment]
**PASSED**
YAAAY
<img width="518" alt="screen shot 2017-10-10 at 6 16 35 pm" src="https://user-images.githubusercontent.com/18075411/31413436-343eb860-ade7-11e7-8303-3202a73ff2b5.png">
