### ISSUE TITLE
Feature tests for hearings_controller

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3315]
Our hearings_controller is currently entirely :nocov:. We need to get rid of that and add feature tests.

**Comment by kierachell** [comment]
**PASSED**
If Travis is passing, everyone is happy.
<img width="257" alt="screen shot 2017-10-20 at 8 36 34 am" src="https://user-images.githubusercontent.com/18075411/31821069-cc51467c-b571-11e7-8392-23d799cfa0c5.png">


Also ran tests locally and they passed without a hitch. and coverage was happy..
