### ISSUE TITLE
Jobs | Heartbeat job is no longer necessary

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3316]
https://github.com/department-of-veterans-affairs/caseflow/commit/d043871df55b5a35a61f53a45322605588ddf927

Was added to keep track of sidekiq cron; but we're getting sidekiq cron so:

- Disable?
- Delete? It's nice for testing, but that's about it.

🔥

**Comment by sunil-sadasivan** [comment]
This is nice as a debugging job and testing the critical path for our async jobs/queuing infra.  I think it might be good to keep this job around however I may adjust the purpose of the heartbeat job to output say more useful debugging info. How's that sound?
