### ISSUE TITLE
Improve establish claim code coverage

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3326]
Had a failed build on master due to low code coverage on establish claim spec:

https://travis-ci.org/department-of-veterans-affairs/caseflow/jobs/276020736

Will investigate what the cause was and if there are any possible solutions

**Comment by joofsh** [comment]
#### Research

I pulled down the code coverage results for this build from S3. Analyzing the results I see:

Code coverage results, very low for many files:
<img width="813" alt="screen shot 2017-09-25 at 4 26 10 pm" src="https://user-images.githubusercontent.com/2256237/30829565-22604ba6-a20f-11e7-8ca9-04c7744fdc53.png">

Looking inside `establish_claim_spec.rb`, the test scenarios were never executed, or at least weren't counted towards code coverage:
<img width="937" alt="screen shot 2017-09-25 at 4 26 20 pm" src="https://user-images.githubusercontent.com/2256237/30829564-2256a286-a20f-11e7-8a2b-6bc8e5e11cd2.png">

Looking at the dispatch tests, I confirmed that the tests did run (though one test did fail). So code coverage results should be normal.

I then looked at other builds of master. None of the most recent 20 builds see the same issue.

#### Conclusion
It's unclear to me how the code coverage result file got into this state. Maybe someone cancelled the build mid-run? Somehow the code coverage file does not match up with the tests that were run on this build. Chalking this up to a weird exception for now. Will look into it further if more tests fail

**Comment by sharonwarner** [comment]
It's a little scary that 'View quotas and update employee count' passed, but code coverage said that most of the test never ran. It's good code coverage causes it to fail.
