### ISSUE TITLE
Hearing Worksheet Date showing up as invalid

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#3331]
<img width="1402" alt="screen shot 2017-09-20 at 10 58 38 am" src="https://user-images.githubusercontent.com/1745984/30651165-ee3e97c6-9df2-11e7-8d28-2ea6f12cb7ee.png">

       <div>{moment(worksheet.date).format('ddd l')}</div> on hearing worksheet
the date is coming out as `null` worksheet json

**Comment by sharonwarner** [comment]
@aroltsch is working on this as part of #3292
