### ISSUE TITLE
Styleguide | Replace Navigation bar example with NavigationBar.jsx

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3337]
We now have a React component that creates a navigation bar in React pages: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/NavigationBar.jsx

This should be used in the Style guide instead of the navigation bar rendered in plain HTML.

AC:
* Use the [Navigation Bar](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/NavigationBar.jsx) React component in `StyleGuideNavigationBar.jsx`
* Ensure dropdown functionality still works as expected

**Comment by Sjones352** [comment]
Currently 

Default logo
![screen shot 2017-09-29 at 11 19 09 am](https://user-images.githubusercontent.com/23080951/31050967-ea85a4f0-a629-11e7-8e89-88c478a22b70.png)


Caseflow App
![screen shot 2017-09-29 at 11 18 31 am](https://user-images.githubusercontent.com/23080951/31050971-fad19076-a629-11e7-99a3-1ef59c0ac715.png)

**Comment by astewarttistatech** [comment]
@Sjones352 This is validated via Style Guide?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Styleguide
2. Navigate to the section for the navigation bar
3. Verify that the mocks and what is currently in UAT match. 

Screenshots: 
<img width="1362" alt="screen shot 2017-10-02 at 8 23 56 am" src="https://user-images.githubusercontent.com/23038505/31078806-80ff34fa-a751-11e7-9e89-ca5c5e58ab6f.png">
