### ISSUE TITLE
Document List | Account toggle dropdown

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3339]
## Story
As a user, I want to have the option to filter document list view by my annotations or annotations of all users who have reviewed the folder. 

## AC
-  [ ] Add [style guide dropdown](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#dropdowns) between number of documents and documents and comments toggle. 
-  [ ] Dropdown should have the following
   - [ ] A profile icon
   - [ ] View as: All users or Me in bold (All users should be default)
- [ ] When dropdown is clicked, user should have option to choose from All users or Me 
   - [ ] [Use styleguide radio button](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#radios)

## Mock up 

![image](https://user-images.githubusercontent.com/13420618/30670082-f0efdfc0-9e2e-11e7-8a08-f63947e0e362.png)

![image](https://user-images.githubusercontent.com/13420618/30670079-e9afb802-9e2e-11e7-8b68-a19766de92eb.png)

![image](https://user-images.githubusercontent.com/13420618/30670069-e13b2d28-9e2e-11e7-9666-fdfc4c1ed30c.png)

[Invision link for interaction](https://va-gov.invisionapp.com/share/AUDE0ZWWR#/254419660_1_-_Document_List)

## Dependent Issue
https://github.com/department-of-veterans-affairs/caseflow/issues/3340

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
