### ISSUE TITLE
Document List | Comments with account names

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3340]
## Description
As a user, I want to have the option to filter document list view by my annotations or annotations of all users who have reviewed the folder.

## AC
- [ ] Show profile icon and account user's first and last name (sentence case) above comment
    - Note: Icon and name should be horizontally center-aligned
- [ ] Verify that there is 10px space between bottom of icon and comment box (see mockup)
- [ ] Verify that comment numbers next to caret, in far right column matches the number comments according to account

## Mockup

![image](https://user-images.githubusercontent.com/13420618/30670271-b4eb2ee8-9e2f-11e7-819d-de6ea25f61b0.png)
[Invision link for interaction](https://va-gov.invisionapp.com/share/AUDE0ZWWR#/254419660_1_-_Document_List)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/3339

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
