### ISSUE TITLE
Document Viewer | Account view

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3341]
## Story
As a user, I want to be able to see who wrote each comment in each document of a veteran's claim folder.

## AC
- [ ] Show profile icon and account user's first and last name (sentence case) above comment and after page number
    - Note: Icon and name should be horizontally center-aligned
- [ ] Verify that there is 10px space between bottom of icon and comment box

## Mock up
![image](https://user-images.githubusercontent.com/13420618/30670450-5cdc5640-9e30-11e7-98cf-4dfdca62636c.png)

[Invision link for interaction](https://va-gov.invisionapp.com/share/AUDE0ZWWR#/254419660_1_-_Document_List)

## Related issues
#3339
#3340

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
