### ISSUE TITLE
We should only check if dependencies are down when the tab is active.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3348]
Right now, at a configured interval, we fire off server requests to check if dependencies are down in every tab. With `document.hidden` we can detect if the tab is currently displayed, and only fire requests for that tab. See PerformanceDegradationBanner.jsx.

## AC
Requests to the dependency check route should only fire for the visible tab.

## Test Plan

1. open up 2 tabs for any app (I used certification as an app, but you could use any)
2. Check for the current tab you have open, `dependencies-check` appears in the network tab
3. Check for the other tab, `dependencies-check` does NOT appear on the network tab

QA Notes: Dependencies check is ran every 2 hours so these tabs would have to remain open for 2 hours

**Comment by astewarttistatech** [comment]
Where would `document.hidden` be because currently I do not see it in the network tab @amprokop  @mmlumba 

Current View:

**Comment by astewarttistatech** [comment]
Still cannot find `document.hidden` anywhere in console or network tabs. Dependancies check occurred on both open pages. Not sure if this is a pass or a fail @mmlumba

**Comment by mmlumba** [comment]
@astewarttistatech `document.hidden` is in the code; its not supposed to be in the console. When you open the two tabs, the active tab of the application is the one that is supposed to show dependency check like so:
<img width="1432" alt="screen shot 2017-12-21 at 12 25 30 pm" src="https://user-images.githubusercontent.com/4773320/34273645-173181a8-e64a-11e7-8406-3e2f36174ebe.png">

**Comment by astewarttistatech** [comment]
**FAILED**

`Dependecies-check` occurs on both tabs in Preprod 
@mmlumba

**Comment by mmlumba** [comment]
@astewarttistatech Here's an example of dependency check working as expected:
(all dated for 12/28)
tab 1 at 2:03pm:
<img width="1280" alt="screen shot 2017-12-28 at 2 03 00 pm" src="https://user-images.githubusercontent.com/4773320/34529908-4e07811a-f062-11e7-93ff-7b4fb11658e8.png">

tab 2 at 2:03pm:
<img width="1280" alt="screen shot 2017-12-28 at 2 03 05 pm" src="https://user-images.githubusercontent.com/4773320/34530000-9d424800-f062-11e7-8c01-b71b8c7d5ac2.png">

tab 1 at 2:10pm:
<img width="1280" alt="screen shot 2017-12-28 at 2 10 40 pm" src="https://user-images.githubusercontent.com/4773320/34530018-aa6f35a6-f062-11e7-9d4c-59a9c1ea1a70.png">

tab 2 at 2:10pm:
<img width="1280" alt="screen shot 2017-12-28 at 2 10 48 pm" src="https://user-images.githubusercontent.com/4773320/34530038-bb17fa0a-f062-11e7-94f8-740f7796cf55.png">

**Comment by astewarttistatech** [comment]
**PASSED**
