### ISSUE TITLE
Hearing Prep: better solution at handling master records

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3351]
Problem: 
Currently, master records are created from the Hearing model which has a lot of fields that master record does not have.

Currently, we assume the first hearing's RO is the RO for the entire day on the Upcoming Hearing Days page. To mitigate risk of the wrong RO being listed in the first hearing of the day on the Daily Docket page, let's we assume the RO for the entire day is the RO that has the majority of hearings associated with it.

**Comment by sharonwarner** [comment]
Fixed through other tickets
