### ISSUE TITLE
Ensure all document dates are correctly filled out on form8 v2

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3352]
It looks like we're missing NOD, form 9, and ssoc dates on the new form 8.

![image](https://user-images.githubusercontent.com/3781835/30710848-d71aaeb2-9ed4-11e7-91a1-652bf0e79822.png)

![image](https://user-images.githubusercontent.com/3781835/30710876-ea2b2f0e-9ed4-11e7-9a71-16d3db729ecf.png)

## AC 
- NOD, SOC, Form9, and up to 3 SSOC  dates should be filled out on the Form 8 v2

**Comment by kierachell** [comment]
**PASSED**
as seen in VBMS
<img width="770" alt="screen shot 2017-09-28 at 3 58 27 pm" src="https://user-images.githubusercontent.com/18075411/30987698-eeddad56-a465-11e7-822e-b806c091cfcf.png">
