### ISSUE TITLE
Hearing Prep: Daily Docket Left Align Hearing time and location

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3369]
**AC**
Hearing Prep: On the Daily Docket  the Hearing time and location should be left aligned to the right of the hearing slot number. Currently this happens in some cases but not in others... (See mock: third hearing slot displays the desired outcome.)

**Current state:**
<img width="527" alt="screen shot 2017-09-22 at 10 42 34 am" src="https://user-images.githubusercontent.com/4975959/30750469-a4616bb8-9f84-11e7-8d23-2bc3befddcca.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod
Browsers: FF, Chrome, and IE

Steps to Validate:
1. Access Hearings via appropriate css_id
2. From the Upcoming Hearing Days page, select a date
3. On the Daily Docket page, verify that the time and region is left aligned to their according number lists. 

Screenshots: 
![readerleftalignedtimeandregion](https://user-images.githubusercontent.com/23038505/30864432-9169096a-a2a1-11e7-9677-863f64c73bfb.png)
