### ISSUE TITLE
Feature Flag | Enable for Group 1 - Pilot Users on 10/9/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3380]
As Product Owner, I would like the following feature flag enabled on Monday, 10/9/2017 at 8 am (as early as possible) for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  Hearing Prep Phase 1

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following users only.

User Name | Email | User ID
-- | -- | --
Vincent Chiappetta | Vincent.Chiappetta@va.gov | bvavchiapp
Sonnet Bush | sonnet.bush@va.gov | bvasbush
Marjorie "Margie" Auer | marjorie.auer@va.gov | bvamauer
Susan Kennedy | susan.kennedy@va.gov | bvaskennedy
Brad Hennings | Bradley.Hennings@va.gov | bvabhennings
Paul Sorisio | Paul.Sorisio@va.gov | bvapsorisio
Dorilyn Ames | Dorilyn.Ames@va.gov | bvadames
Leli Simpson | alexandra.simpson@va.gov | bvaapsimpson
Simone Mays | Simone.Mays@va.gov | bvaSbelcher
Stacey Heneks | Stacey.Heneks@va.gov | bvasheneks
Jonathan Hager | Jonathan.Hager@va.gov | bvajhager
Simone Krembs | simone.krembs@va.gov | bvaskrembs

## Related Stories
IP | VVA | Execute Plan [#1537](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1537)
IP | Hearing Prep | Request feature flag enabled - Pilot Group [#1573](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1573)

**Comment by sharonwarner** [comment]
We're just going to send an email with the link when it's ready.

**Comment by nikitarockz** [comment]
@sharonwarner I understand you point; however playing devils advocate, suppose a user shares the link with a colleague who is not supposed to be in the this pilot.  You might think at first no problem because they don't have the right CSS permissions.  To that I say, suppose they do have the right permissions because this person who had requested access to another one of our tools was fortunate enough to have the person submitting the request to decide this user should have access to these other functions because it sounded right.  Point being, these people make mistakes.  I am just trying to ensure it doesn't happen.  Just a thought.  😄
