### ISSUE TITLE
Remove more v1 certification code

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3381]
AC 
- All v1 tests, or tests that test code that was only used in v1, are removed
- All Form 8 v1 code is removed
- Do an audit of all certification code and identify any other pieces that need to be removed (make new issues for these)

**Comment by amprokop** [comment]
Now that we turned on the form 8 v2 everywhere, we can remove all the form8 v1 code paths @nemodjuric

**Comment by astewarttistatech** [comment]
@nemodjuric @amprokop So this didn't need to be tested? Is this why Demo's certification is completely gone (V1 and V2)?

**Comment by amprokop** [comment]
@astewarttistatech — no to both

**Comment by kierachell** [comment]
K
