### ISSUE TITLE
Document Viewer | Wassup with this scrollbar?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3389]
# Description
When looking at a PDF there's a weird new scrollbar that's always there, not sure if intended

## Reproduction Steps

**Scenario 1 -**

1. Go to view a PDF
1. See a scrollbar box
1. Scroll and see the bar show up
1. Weird, huh?

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [PDF]_**
<img width="400" alt="screen shot 2017-09-26 at 7 35 07 am" src="https://user-images.githubusercontent.com/18075411/30858330-43e10d0a-a28d-11e7-8c2a-5b0ab54e1741.png">
<img width="405" alt="screen shot 2017-09-26 at 7 35 17 am" src="https://user-images.githubusercontent.com/18075411/30858329-43e00694-a28d-11e7-9c7d-cf60a29288f9.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by mdbenjam** [comment]
Don't think this is still relevant.
