### ISSUE TITLE
Hearing Prep Worksheet | Update Issues Numbering for multiple Appeal Streams

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3390]
Users need a way see the total number of issues consecutively across multiple Appeals Streams. Users want to see the number of each issue to add up together on the Hearing Worksheet.

**AC**
- If there are multiple Appeals Streams, continue the numbering from Appeal Stream 1 to first issue under Appeals Streams 2. (Appeals Streams 2 should never have an issue numbered 1)

<img width="577" alt="screen shot 2017-09-26 at 10 22 02 am" src="https://user-images.githubusercontent.com/22620270/30865857-b9d1fe08-a2a5-11e7-95ec-834c818a5912.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="1264" alt="screen shot 2017-10-31 at 9 02 50 am" src="https://user-images.githubusercontent.com/18075411/32225102-6107ec16-be1a-11e7-858c-4e1a97060474.png">
<img width="858" alt="screen shot 2017-10-31 at 9 03 27 am" src="https://user-images.githubusercontent.com/18075411/32225103-61196e00-be1a-11e7-8324-8ea39d60f77e.png">

**Comment by sharonwarner** [comment]
Reopening and clarifying the AC

**Comment by kierachell** [comment]
shit, sorry.. did not expect that

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearings Prepd > Hearings Worksheet
2. Add Issues
3. Delete issues out of order
4. Verify that numbering updates
5. Add Issues 
6. Verify that those new issues follow the same numbering logic
7. Refresh the page to see if all the issues you just messed around with show up again, if they don't then you are golden (and they didn't). 

Screenshots: 
![numberinghearings](https://user-images.githubusercontent.com/23038505/32453619-b548507a-c2ea-11e7-8897-54cf1eb52ad6.gif)
