### ISSUE TITLE
Styleguide | Replace Footer example with Footer.jsx

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3394]
We now have a React component that creates a footer in React pages: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/Footer.jsx

This should be used in the Style guide instead of the footer rendered in plain HTML.

AC:
* Use the [Footer](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/Footer.jsx) React component in `StyleGuideFooter.jsx`for the footer portion
* Use the [Navigation Bar](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/NavigationBar.jsx) React component for the Navigation bar portion

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Styleguide
2. Navigate down to the footer 
3. Open inspector and check the elements of the footer for React components
4. Do the same for the navigation bar

Screenshots: 
<img width="1355" alt="screen shot 2017-10-04 at 10 00 02 am" src="https://user-images.githubusercontent.com/23038505/31179892-2e9c2178-a8eb-11e7-99d0-e5d2bcab26d8.png">
<img width="1397" alt="screen shot 2017-10-04 at 10 01 06 am" src="https://user-images.githubusercontent.com/23038505/31179893-2e9ca562-a8eb-11e7-93b0-66d8df1942b5.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Styleguide
2. Navigate down to the footer 
3. Open inspector and check the elements of the footer for React components
4. Do the same for the navigation bar

Screenshots: 
<img width="1355" alt="screen shot 2017-10-04 at 10 00 02 am" src="https://user-images.githubusercontent.com/23038505/31179892-2e9c2178-a8eb-11e7-99d0-e5d2bcab26d8.png">
<img width="1397" alt="screen shot 2017-10-04 at 10 01 06 am" src="https://user-images.githubusercontent.com/23038505/31179893-2e9ca562-a8eb-11e7-93b0-66d8df1942b5.png">
