### ISSUE TITLE
Daily Docket | Save feature test should include dropdowns

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3399]
The feature test for saving the daily docket doesn't include the dropdowns. We should follow the pattern established in Reader for adding them. 

https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/reader/reader_spec.rb#L1004

AC:
- Dropdowns are covered in feature test

**Comment by astewarttistatech** [comment]
@sharonwarner What is needed for validating this ticket?

**Comment by sharonwarner** [comment]
@astewarttistatech yeah, you can look through the code if you want, but no functionality was updated.

**Comment by astewarttistatech** [comment]
**PASSED** (No functionality changed)

Validated: Master

Steps to Validate: 
1. Navigate to the test spec file for Hearing Prep and see if it includes lines about the dropdowns on the Daily Docket page. 

Screenshots: 
<img width="975" alt="screen shot 2017-10-16 at 11 58 34 am" src="https://user-images.githubusercontent.com/23038505/31622168-a5025aa8-b269-11e7-9ae5-ae8d02f6d122.png">
