### ISSUE TITLE
Create certification feedback view

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#340]
Build on modal pattern created in #321. Make sure that  _Skip_ button links to the error page.

Blocks #307.

![cannotcertify_02_feedback](https://cloud.githubusercontent.com/assets/6335546/11602173/41422dcc-9aa6-11e5-9f82-3249d538374b.png)

**Comment by webinista** [comment]
Blocked by #341. Can't merge unless that's resolved.

**Comment by webinista** [comment]
Clearing this from the Limited Rollout milestone since it needs a database.

**Comment by KHarshawat** [comment]
From the NYRO Requirements Gathering, people aborted for the following reasons:

- 646 still needed
- DRO established a 930 (this means that some issue is unaddressed – in this case, the issue of unemployability still needed a decision)
- Appeal was very complicated
- NOD was of record but was labeled as correspondence 

We should explore adding these as checkboxes in this modal + and "other" option before implementing.
