### ISSUE TITLE
Standup Report | BVA Technology | Show only "In Progress" type issues

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3400]
As BVA PMO, I would like to have the BVA Technology Standup Report updated to show only "In Progress" type issues so that our team can focus on the current issues that are being worked.

## Acceptance Criteria
1. Verify that when the "BVA Technology" Standup Report option is selected, only issues with the following labels are displayed by Assignee:

     > In Progress PMO
     > In Progress VACOLS

1. Verify that the sub-copy for the "Daily Standup Report" section has been updated to the following:

     > Only issues that are marked as **in progress** are shown.

1. Verify that the column "Business Time in Current State" has been added to display the total number of days an issue has been in a state of "In Progress".  (**_Note:_** _Use the same formula that is used on the Caseflow and Appeals PM reports._)

### Developer Notes
This should done in developer repo.

## Related Stories
Standup Report | Create engineering story to update for BVA Technology [#1578](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1578)

**Comment by kierachell** [comment]
**PASSED**
![bva](https://user-images.githubusercontent.com/18075411/31502767-fc1138b8-af3b-11e7-89bd-14b4336f0c77.gif)
