### ISSUE TITLE
Standup Report | Appeals PM | Show issues with label "Peer Review"

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3401]
As Caseflow PM, I would like to have the Appeals PM Standup Report updated to also show issues with "Peer Review" label so that our team can see when things have a request for another person to review the issue product.

## Acceptance Criteria
1. Verify that when the "Appeals PM" Standup Report option is selected, issues with the following labels are displayed by Assignee:

     > In Progress
     > Peer Review

1. Verify that the sub-copy for the "Daily Standup Report" section has been updated to the following:

     > Only issues that are marked as **in progress** are shown, this also includes items that currently undergoing "peer review".

### Developer Notes
This should done in developer repo.

## Related Stories

**Comment by kierachell** [comment]
**PASSED**
<img width="634" alt="screen shot 2017-10-27 at 1 31 34 pm" src="https://user-images.githubusercontent.com/18075411/32117116-2d35f95c-bb1b-11e7-899a-a44361de4ac5.png">
