### ISSUE TITLE
Fix text alignment and font for ctrl + f

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3402]
When searching a document using ctrl + f, the font and alignment are off. This is because we are showing the invisible text on the PDF. We should investigate if we can go back to how PDFJS does it normally (using transparency), while maintaining the high contrast when using ctrl + f. Also firefox ctrl + f is opaque, that must also be fixed.

![image](https://user-images.githubusercontent.com/3885236/30891942-e048a0ba-a303-11e7-9dd5-88f76f907a46.png)

**Comment by laurjpeterson** [comment]
I think Mark fixed this on a more recent ticket before he left. Closing.
