### ISSUE TITLE
SPIKE: Investigate JS testing setup

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3403]
Our JS testing setup is not working well.

1) Karma tests are slow to execute, give no feedback about what went wrong, and the watch command regularly disconnects from Chrome.
1) Source maps are not good. It's hard to tell where errors are coming from.
1) Writing more complex tests using our frameworks requires a lot of practice, and we lack utility functions to easily wait, or click on buttons etc in Enzyme.

Explore how to either improve our Karma setup, or how to move to a different testing stack.

**Comment by alisan16** [comment]
Closing as this is now obsolete.
