### ISSUE TITLE
Document Viewe  r | Current page indicator freezes

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3409]
# Description
When browsing between Documents, sometimes current page indicator gets stuck on a random page number

## Reproduction Steps

**Scenario 1 -**

1. Go to Document Viewer
1. Note current page number
1. Browse to other PDFs
1. Browse to different pages
1. Note that if a document is slow to load, next document you navigate to will have page number stuck

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

### Page number indicator freezes after switching between large documents:

<img width="1031" alt="screen shot 2017-09-26 at 3 45 05 pm" src="https://user-images.githubusercontent.com/18075411/30880798-bfb78186-a2d1-11e7-8ae1-8389c16cbffb.png">

![lags0z](https://user-images.githubusercontent.com/18075411/30880643-43427548-a2d1-11e7-942c-d9718ea00723.gif)

# Related Issues
**_Support_**

**_Engineering_**

**Comment by mdbenjam** [comment]
I don't think this still happens.
