### ISSUE TITLE
Document Viewer | Footer shows up in the rendering PDF

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3410]
# Description
When a PDF is slow to load, sometimes the footer shows up as a placeholder

## Reproduction Steps

**Scenario 1 -**

1. Go to a sizeable PDF
1. Wait for it to render
1. See footer!??!
1. Be confused

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

### Footer shows up in rendering pages? 😃 

<img width="965" alt="screen shot 2017-09-26 at 3 49 40 pm" src="https://user-images.githubusercontent.com/18075411/30881026-63e4bfee-a2d2-11e7-86b5-5da2cc310560.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by mdbenjam** [comment]
I no longer see this. I just see a blank pdf view now. Closing.
