### ISSUE TITLE
Document Viewer | PDFs are fetched twice?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3412]
# Description
When viewing PDFs in Reader, I noticed in the network tabs that many PDFs are fetched twice?
Am I missing something?

## Reproduction Steps

**Scenario 1 -**

1. Open Network tab
1. Go to Document List
1. Open a Document
1. Watch network tab
1. Note that some are refetched from disk cache, but some are not

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [network]_**

<img width="1430" alt="screen shot 2017-09-27 at 12 42 54 pm" src="https://user-images.githubusercontent.com/18075411/30926010-bfb6f01c-a381-11e7-8155-8d2413009f5e.png">
<img width="1019" alt="screen shot 2017-09-27 at 12 43 29 pm" src="https://user-images.githubusercontent.com/18075411/30926008-bfb2354a-a381-11e7-9108-67b1a45d3aad.png">
<img width="913" alt="screen shot 2017-09-27 at 12 43 35 pm" src="https://user-images.githubusercontent.com/18075411/30926009-bfb6adc8-a381-11e7-8f87-062b2a994771.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by mdbenjam** [comment]
This should be fixed now. I think the refactor of Pdf.jsx and https://github.com/department-of-veterans-affairs/caseflow/pull/3951 fixed it.
