### ISSUE TITLE
[Frontend] Upcoming Dockets | Scheduled Hearings Count

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3415]
AC:
- The upcoming dockets page displays the correct number of scheduled hearings (must differentiate between master and child records)

**Comment by astewarttistatech** [comment]
@sharonwarner How am I to determine that the number is correct? Please add this to the AC.

**Comment by aroltsch** [comment]
@astewarttistatech 
1. If it is a master record, it should always show 0 scheduled hearings
2. If it is a non-master record, check dockets.json response and check the size of the hearings_array

**Comment by astewarttistatech** [comment]
Thanks @aroltsch 

**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Recreate: 
1. Access Hearings and navigate to the Upcoming Hearing Days page
2. Check the dockets.json response and check the size of the hearings_array for non-master. 
3. Verify that the master record should always show 0 for scheduled hearings

Screenshots: 
<img width="1268" alt="screen shot 2017-09-29 at 2 05 41 pm" src="https://user-images.githubusercontent.com/23038505/31030908-f79a5ede-a524-11e7-8f3a-ff22930655ca.png">
