### ISSUE TITLE
[Intake] Create initial app skeleton

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#3416]
## AC
1. A new app exists at `/intake`
1. You can click through a 4-step process.

**Comment by abbyraskinUSDS** [comment]
Mocks:

![image](https://user-images.githubusercontent.com/4042181/30937636-63879e30-a3a5-11e7-9c68-55a03fe3514d.png)

![image](https://user-images.githubusercontent.com/4042181/30937687-882294e8-a3a5-11e7-8288-ddf962d8b8d1.png)

![image](https://user-images.githubusercontent.com/4042181/30937705-950e7c80-a3a5-11e7-865e-8907ee941782.png)

![image](https://user-images.githubusercontent.com/4042181/30937746-b427e1a6-a3a5-11e7-9c2f-51468ded2ea3.png)


Error state: if Veteran doesn't match with a Veteran in Caseflow's [TBD] "veterans notified" column 
![image](https://user-images.githubusercontent.com/4042181/30937839-06ebda82-a3a6-11e7-87e0-838a0aeeedbf.png)

**Comment by NickHeiner** [comment]
![intake clickthrough](https://user-images.githubusercontent.com/829827/30979589-137e0d46-a44c-11e7-978f-f48d894236b3.gif)

@abbyraskinUSDS, for the progress bar: your mockups have only the current section in an "active" state. However, the way the component currently works, all sections up to the current one are marked as "active". Is it ok if we keep that behavior?

**Comment by abbyraskinUSDS** [comment]
@NickHeiner (a) you rock, this is great* (b) yes, absolutely, apologies for the inconsistency.

*I may have some copy tweaks forthcoming (though no major changes so far), pending more info from AMO.

**Comment by kierachell** [comment]
**PASSED**
<img width="1137" alt="screen shot 2017-09-28 at 9 38 19 pm" src="https://user-images.githubusercontent.com/18075411/30997379-8308e03e-a495-11e7-849b-a10092eb2646.png">
<img width="1106" alt="screen shot 2017-09-28 at 9 38 34 pm" src="https://user-images.githubusercontent.com/18075411/30997378-83045cd0-a495-11e7-9045-76794ec888cc.png">
<img width="698" alt="screen shot 2017-09-28 at 9 39 09 pm" src="https://user-images.githubusercontent.com/18075411/30997377-83037298-a495-11e7-960d-2c4e19e8df5f.png">
<img width="607" alt="screen shot 2017-09-28 at 9 39 11 pm" src="https://user-images.githubusercontent.com/18075411/30997376-8302e936-a495-11e7-9d95-702e895fb7ad.png">
