### ISSUE TITLE
Document Viewer | Search does not handle multiple words or line breaks

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow#3418]
# Description
When searching a PDF... I can only search one word at a time

## Reproduction Steps

**Scenario 1 -**

1. Go to view a PDF
1. Search for `word`
1. Get a match
1. Search for `word `
1. Get a match
1. Search for `two words`
1. Be forever alone

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [No match]_**
<img width="1032" alt="screen shot 2017-09-27 at 7 09 58 pm" src="https://user-images.githubusercontent.com/18075411/30942325-43a6c4ac-a3b8-11e7-93bf-489e4cee4171.png">

<img width="795" alt="screen shot 2017-09-27 at 7 16 06 pm" src="https://user-images.githubusercontent.com/18075411/30942332-58813696-a3b8-11e7-9d6c-d2a1cc3e6b45.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
