### ISSUE TITLE
Fix missing doc stats

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#342]
The stats for how often a certification was missing documents isn't calculating correctly:

<img width="964" alt="screen shot 2016-10-19 at 8 47 24 am" src="https://cloud.githubusercontent.com/assets/1596259/19519205/eb606908-95d8-11e6-9e04-41c574c99d3e.png">

We should also add light unit tests for all the `Certification.was_missing_X` methods

**Comment by cmgiven** [comment]
Central issue is that the stats logic assumes that `:form8_started_at` corresponds to the date the appeal was first opened in Caseflow. This attribute is not set, however, until all documents match, so as a result, there is never a missing document as far as the stats are concerned. Two options:

1. We could use the minimum date that any document matched.
2. We could begin to log the first date a given appeal was opened in Caseflow.

I prefer option 2, as it's more consistent with the intent of the metric. Option 1, for example, would not register an appeal that was opened with no matching documents.

**Comment by amprokop** [comment]
Option 2 sounds right to me. Should we modify the description body to add that?

**Comment by shanear** [comment]
We'll go with that, update the description if it's helpful to you, but no need from my perspective.

**Comment by aroltsch** [comment]
PR: https://github.com/department-of-veterans-affairs/caseflow/pull/557

**Comment by astewarttistatech** [comment]
@aroltsch @cmgiven  said that the stats are showing every document is a missing doc. Moving this back

**Comment by shanear** [comment]
<img width="973" alt="screen shot 2016-12-20 at 8 27 25 pm" src="https://cloud.githubusercontent.com/assets/1596259/21374309/d1ff9424-c6f3-11e6-841a-eaa9896e3fe9.png">

This is looking real-ish in prod. @cmgiven can you confirm?

**Comment by cmgiven** [comment]
I can fully confirm once I have access to the prod DB. Beyond that, yes, looks "real-ish". Let's close this one out. Great work, @aroltsch.

**Comment by aroltsch** [comment]
"Real-ish" lol. Love it!
