### ISSUE TITLE
Move footer to React

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3429]
Hearings Prep lost its footer when we moved to the React header. We need to move the footer to React as well.

**Comment by kierachell** [comment]
**PASSED**

no idea what the change really is , but looks nice:
<img width="1425" alt="screen shot 2017-09-28 at 4 39 12 pm" src="https://user-images.githubusercontent.com/18075411/30989421-a5880376-a46b-11e7-9c68-3a63fda69e20.png">
<img width="1375" alt="screen shot 2017-09-28 at 4 39 40 pm" src="https://user-images.githubusercontent.com/18075411/30989420-a582abec-a46b-11e7-9dd3-59871a37d66b.png">
