### ISSUE TITLE
If 13 "Other" has text, check "Other" on the question 13 checkboxen

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#343]
Seems unintuitive to strip the contents if other isn't set, rather, other being full of text should set other

**Comment by alex** [comment]
The original UI here was that the text field didn't show up until you checked "Other" correct?

**Comment by webinista** [comment]
Yes. That was the original UI.

**Comment by alex** [comment]
Ok. Assuming we don't want to add the hiding logic back, I think this makes
sense.

On Tue, Dec 8, 2015 at 1:27 PM, Tiffany Brown <notifications@github.com>
wrote:

> Yes. That was the original UI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/343#issuecomment-162969908>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by webinista** [comment]
So for clarity: We're now going to check the _Other_ box if text is entered in the _Specify Other_ field?

**Comment by alex** [comment]
I think that would be reasonable. It's Kavi's call though.

On Tue, Dec 8, 2015 at 1:31 PM, Tiffany Brown <notifications@github.com>
wrote:

> So for clarity: We're now going to check the *Other* box if text is
> entered in the *Specify Other* field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/343#issuecomment-162972075>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by webinista** [comment]
@KHarshawat Please weigh in when you have a moment. I think this is a good approach.

**Comment by webinista** [comment]
Changes are in the issue#343 branch, just in case. Will create a PR if Kavi OKs the change.

**Comment by KHarshawat** [comment]
@webinsta yep! That sounds great!!

**Comment by paultag** [comment]
Re-targeting for limited rollout
