### ISSUE TITLE
Integrate hearing prep with feedback

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3430]
AC:
- [x] Feedback gets categorized as 'Caseflow Hearing Prep'
- [x] 'Send Feedback' link takes you back to 'Caseflow Hearing Prep'

**Comment by astewarttistatech** [comment]
Couple of things. 

1. Cancel and Send Feedback buttons aren't aligned (making a new ticket for it)
2. There is no link to Hearings Prep in the footer. 

Screenshot: 
![hearingfeedback](https://user-images.githubusercontent.com/23038505/31176679-b018b22a-a8e1-11e7-965d-e59bb009887d.gif)

**Comment by astewarttistatech** [comment]
Based on the change in AC, this ticket is now 

**PASSED**

Validated in: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings Prep
2. From the Username dropdown select "Send Feedback" 
3. Verify that the link takes you to a feedback page for Hearings Prep
4. Fill in the required slots of information 
5. Select the "Send Feedback" button 
6. Verify that the button click will take you back to Hearings Prep, **after navigating through the Thank You page** <-- not mentioned in AC but is part of the flow of Feedback.

Screenshots:
