### ISSUE TITLE
Intake Search | Search for Veteran to process RAMP opt-in election

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3431]
As a Claims Assistant, I want to be able to search for a veteran to begin processing their RAMP opt in election letter.

## Acceptance Criteria
When the user types a file number and submits the search (via the button, or by pressing enter), Caseflow should search for a veteran that has been recorded as having received an opt in letter.

- If a veteran for that file number is found, but did not receive an opt in letter, navigate to instructions on what letter to send (see: #3441).
- If a veteran for that file number is not found, show user an error message saying that a veteran for that file number was not found in the corporate DB 
![image](https://user-images.githubusercontent.com/4042181/30989258-0df92da0-a46b-11e7-8188-9991d3c6d508.png)

- If the veteran for that file number was found and did receive an opt in letter, record the time the intake began and proceed to the next step in processing the opt in election also process (see: #3436)

## Additional Notes
- We need to track the time that the opt-in election process was started because it is important for time processing purposes.
- There will be some additional checks added at this step to make sure the veteran's appeal is still eligible added in #3433.

## Mocks
![image](https://user-images.githubusercontent.com/4042181/31250353-8d6b589c-a9e8-11e7-8619-4e1cbf440277.png)

**Comment by kierachell** [comment]
### When SSN exists in VACOLS but not BGS, why am I getting this error?
<img width="860" alt="screen shot 2017-10-16 at 9 04 22 am" src="https://user-images.githubusercontent.com/18075411/31613412-0f9f803e-b251-11e7-9172-e017b69f5ad0.png">

**Comment by shanear** [comment]
The veteran should exist in BGS for that error message to pop up. Can we walk through this issue tomorrow?

**Comment by shanear** [comment]
Looks like these vets don't have a BIRLS record, and thus are not found. Checking to see if all vets have BIRLS records.

This hasn't been a major issue with Dispatch, so I'm thinking it just might be a test data issue.

**Comment by kierachell** [comment]
Sure, it's not found. Why am I getting `permission` error a not a `not found` error?

**Comment by shanear** [comment]
I'll fix the permission error. As for what to do about the overarching issue, I created a ticket:

https://github.com/department-of-veterans-affairs/caseflow/issues/3660

**Comment by kierachell** [comment]
**PASSED**
<img width="768" alt="screen shot 2017-10-19 at 7 44 59 am" src="https://user-images.githubusercontent.com/18075411/31770118-6dc42aac-b4a4-11e7-8c3c-dd413fed2a65.png">

@abbyraskinUSDS should the text still reference `valid` or should it say `another`?
<img width="837" alt="screen shot 2017-10-19 at 8 06 05 am" src="https://user-images.githubusercontent.com/18075411/31770119-6dfae088-b4a4-11e7-8923-ba042d992d3d.png">

**Comment by kierachell** [comment]
### If I input a number with S or C, I get error:
```
BGS::ShareError: findVeteranByFileNumber: FileNumber is invalid, must be 8 or 9 digits
```

and the search hangs
<img width="827" alt="screen shot 2017-10-19 at 8 53 13 am" src="https://user-images.githubusercontent.com/18075411/31771660-f5762e36-b4aa-11e7-86fd-f8ddfd74b307.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Gather veteran IDs that match the criteria set in the AC.
2. Access Intake
3. Verify that each of the "If, Then" statements in the AC. 

Screenshots

Veteran ID not found: 
<img width="1404" alt="screen shot 2017-10-20 at 2 30 23 pm" src="https://user-images.githubusercontent.com/23038505/31836460-6d0f1fb8-b5a3-11e7-9f86-e8424d4553b7.png">

RAMP opt-in notice not sent: 
<img width="1387" alt="screen shot 2017-10-20 at 2 32 53 pm" src="https://user-images.githubusercontent.com/23038505/31836563-c8934bb6-b5a3-11e7-9903-5e1fc8dd440f.png">

Veteran with RAMP opt in notice sent: 
![intakestuff3](https://user-images.githubusercontent.com/23038505/31836585-d9cfc7e2-b5a3-11e7-860d-8f91406ed8bb.gif)

**Comment by kierachell** [comment]
### Do we need a Sentry error every time someone searches for a not-found ID?

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/475/

**Comment by shanear** [comment]
> Do we need a Sentry error every time someone searches for a not-found ID?

This will only happen when the file number is not 8 or 9 digits, I've created a separate issue to track that.
https://github.com/department-of-veterans-affairs/caseflow/issues/3702
