### ISSUE TITLE
Intake Search | Validate that an appeal is still eligible for RAMP Opt-in

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3433]
As a claims assistant, I want to validate that the appeal I am processing an Opt-in election for is still eligible for RAMP opt-in.

## Acceptance Criteria
- When a veteran that received an opt-in letter was successfully found on the search page, before proceeding to the next step, the system should validate that the appeal(s) being elected are still eligible to be converted to HLR or SC.
- An appeal is *ineligible* if:
  - it has been activated to the Board
  - it has been decided (either at VBA or the Board)
- If the appeal is ineligible, navigate to instructions on how to process an invalid election (see: #3442)
- If the appeal is eligible, continue to the next step as usual.

## Technical notes
1. The status (`BFMPRO`) should be `'ADV'`. This will exclude cases that are at the Board (`'ACT'`), remands (`'REM'`), pending motions (`'MOT'`), and closed cases (`'HIS'`).

2. The appeal must have at least one undecided issue (`ISSUES.ISSDC is null`)

**Comment by cmgiven** [comment]
To translate this to VACOLS, there two checks I think should be performed.

1. The status (`BFMPRO`) should be `'ADV'`. This will exclude cases that are at the Board (`'ACT'`), remands (`'REM'`), pending motions (`'MOT'`), and closed cases (`'HIS'`).

2. The appeal must have at least one undecided issue (`ISSUES.ISSDC is null`). This is probably redundant with the first check, but just a sanity check.

**Comment by abbyraskinUSDS** [comment]
Reevaluate after we know the eligibility for the first 500 participants.

**Comment by abbyraskinUSDS** [comment]
@shanear remands ARE, in fact, eligible for RAMP. so we should update the technical notes accordingly.

**Comment by abbyraskinUSDS** [comment]
Note: remands returned to the Board are NOT eligible, however.

***
Participation in RAMP is only open to Veterans who receive a RAMP Notice letter and have a compensation benefit appeal pending in the current (legacy) appeals process.  

To be eligible the appeal must be:
•	an active appeal pending for a compensation claim and
•	in one of the following appeals stages:
−	NOD 
−	Form 9
−	Certified to BVA (not activated) 
−	Remand

VA will not accept an election to participate in RAMP if the above noted conditions are not met.

Note: Other issues on appeal, such as pension claims, survivors claims, insurance claims, or loan guaranty claims are excluded from processing under RAMP in addition to compensation appeals in the following stages: 
•	Certified to BVA (Activated: formally placed on the Board’s docket)
•	Remand Returned

**Comment by kierachell** [comment]
**PASSED**
- first one didn't work
<img width="1120" alt="screen shot 2017-10-24 at 8 43 14 am" src="https://user-images.githubusercontent.com/18075411/31943679-6ee5b0da-b897-11e7-8311-867de9beeb22.png">
- 2nd one did: ADV and ISSDC null
<img width="818" alt="screen shot 2017-10-24 at 8 43 45 am" src="https://user-images.githubusercontent.com/18075411/31943684-758408c4-b897-11e7-882b-f05846acf6d1.png">
