### ISSUE TITLE
Review Election | Process request submission

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3436]
As a claims assistant, I want to be able to select the type of review requested on a veteran's opt-in election and it's receipt date, and I want my selections to be saved and to be routed to the correct next steps.

## Acceptance Criteria
- When I click "Continue to next step" button on the Review Request Page,
  - If I did not select a election option, then no actions should be taken and there should be an error telling me to select a election option.
  - If I did not enter a receipt date, then no actions should be taken and there should be an error telling me to enter a receipt date.
  - If all fields were entered, save those selections, and proceed to the next step ~which should have slightly different copy depending on the election option. (see: #3437)~ (Nick's note: removing this last sentence part so it's clear what's in scope for this ticket, and what's in scope for #3437.)

## Additional Notes
- Follow styleguide for error handling and field validations.

**Comment by shanear** [comment]
@nickheiner-usds if you want to take the front-end error checking and submission, i can take the api after that. thoughts?

**Comment by kierachell** [comment]
**PASSED**
<img width="1118" alt="screen shot 2017-10-16 at 9 02 52 am" src="https://user-images.githubusercontent.com/18075411/31613486-46c45a94-b251-11e7-82cb-9e8c95d80296.png">
<img width="907" alt="screen shot 2017-10-16 at 9 03 02 am" src="https://user-images.githubusercontent.com/18075411/31613487-46e29266-b251-11e7-93c3-c017bab913a9.png">
<img width="877" alt="screen shot 2017-10-16 at 9 03 18 am" src="https://user-images.githubusercontent.com/18075411/31613488-46ff9a82-b251-11e7-84db-fed5652b8613.png">
<img width="1110" alt="screen shot 2017-10-16 at 9 05 47 am" src="https://user-images.githubusercontent.com/18075411/31613491-47a06eb2-b251-11e7-9036-1cc3f5cf91fd.png">
