### ISSUE TITLE
Finish Processing | Complete intake and close VACOLS appeal(s) and Success

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3439]
As a claims assistant, once I have completed all the manual steps on the "Finish Processing" page I want to close the VACOLS record automatically, record the time the intake was completed, and show the congrats page.

## Acceptance Criteria
- When the user clicks the "I've completed all steps" button on the Finish Processing page, then:
   - Any active appeals at VBA should be marked as closed with the opt-in disposition
   - The intake completion time is saved in Caseflow
   - The user is navigated to a success page (follow styleguide  #rules)

![image](https://user-images.githubusercontent.com/4042181/31022636-5f164ff0-a507-11e7-8480-1e9bd3028351.png)

**Header:** Intake completed
**Body:** [Veteran_First_Name] [Veteran_Last_Name]'s (ID#[VetID]) opt-in request has been processed. You can now begin intake for the next opt-in letter.
**Checkmark:** Caseflow closed the VACOLS record
  
## Additional Notes
- There will be additional validations of the steps completed here when the button is clicked that will be added later, but not slated for the V1 release.

## Technical Notes
- The new disposition should be added here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/vacols/case.rb#L26
- How do we get all active appeals at VBA? @cmgiven 
- @cmgiven will extra validate the PR for this.
- The SQL required to close an Appeal in VACOLS :hurtrealbad: 
```
UPDATE FOLDER SET TICUKEY = 'HISTORY', TIKEYWRD = 'HISTORY',
   TIDCLS = :sentdttm, TIMDTIME = :gd_sysdate,
   TIMDUSER = upper(:sqlca.logid)
   WHERE TICKNUM = :gs_folder USING SQLCA;
if sqlca.sqlcode <> 0 then goto error_rtn

ls_casev = f_get_program_area(gs_folder)
UPDATE BRIEFF SET BFMPRO = 'HIS', BFDDEC = :sentdttm, BFDC = :disp,
   BFCURLOC= '99', BFDLOOUT = :gd_sysdate, BFDLOCIN = :gd_sysdate,
   BFBOARD = '00', BFMEMID = '000', BFATTID = '000',
    BFCASEV = :ls_casev, BFDCFLD3 = :ls_dro, BFDCFLD1 = :ls_infconf, 
    BFDCFLD2 = :ls_formal WHERE BFKEY = :gs_folder USING SQLCA;
if sqlca.sqlcode <> 0 then goto error_rtn

UPDATE ISSUES SET ISSDC = :disp, ISSDCLS = :gd_sysdate, ISSGR = :ls_gr
  where ISSKEY = :gs_folder and ISSDC is null;
if sqlca.sqlcode <> 0 then goto error_rtn

UPDATE ASSIGN set TSKDCLS = :gd_sysdate, TSKMDTM = :gd_sysdate,
                  TSKMDUSR = upper(:sqlca.logid), TSKSTAT = 'C'
   WHERE TSKTKNM = :gs_folder and TSKDCLS is null USING SQLCA;
if sqlca.sqlcode <> 0 then goto error_rtn

UPDATE HEARSCHED set CLSDATE = :gd_sysdate, HEARING_DISP = 'C'
  WHERE FOLDER_NR = :gs_folder and HEARING_DISP is null and CLSDATE is null;
if sqlca.sqlcode <> 0 then goto error_rtn

UPDATE PRIORLOC set LOCDIN = SYSDATE, LOCSTRCV = upper(:sqlca.logid),
   LOCEXCEP = 'Y' where LOCKEY = :gs_folder and LOCDIN is null
   USING SQLCA;
if sqlca.sqlcode <> 0 then goto error_rtn

INSERT into PRIORLOC (LOCDOUT, LOCDTO, LOCSTTO, LOCSTOUT, LOCKEY)
   values (SYSDATE, SYSDATE, '99', upper(:sqlca.logid), :gs_folder)
   USING SQLCA;
```
* We set FOLDER.TICUKEY to 'HISTORY'
* We set FOLDER.TIKEYWORD to 'HISTORY'
* We set FOLDER.TIDCLS to the date the waiver was received
* We mark that we modified the FOLDER table by updating TIMDTIME and TIMDUSER

* We set BRIEFF.BFMPRO to 'HIS'
* We set BRIEFF.BFDDEC to the receipt date of the opt in election letter
* We set BRIEFF.BFDC to a 'P' (the special RAMP disposition)
* We set BRIEFF.BFBOARD to '00'
* We set BRIEFF.BFMEMID to '000'
* We set BRIEFF.BFATTID to '000'

For each issue that has not already been resolved (`ISSDC is null`):
* We set ISSUES.ISSDC to a disposition code to be determined
* We set ISSUES.ISSDCLS to the date the waiver was received

* We change the location of the appeal to '99'.
* We close out any pending diaries and cancel all pending hearings.

**Comment by cmgiven** [comment]
I don't understand the context, but all advance VBA appeals would:

`select * from BRIEFF inner join (select ISSKEY, count(*) VBA_N from ISSUES where ISSDC is null and ISSPROG in ('01', '02', '03', '04', '05', '07', '08')) on BFKEY = ISSKEY where BFMPRO = 'ADV' and VBA_N > 0`

Unless you also want remands, which I don't think you do. Comp is easier:

`select * from BRIEFF inner join (select ISSKEY, count(*) COMP_N from ISSUES where ISSDC is null and ISSPROG = '02') on BFKEY = ISSKEY where BFMPRO = 'ADV' and COMP_N > 0`

**Comment by abbyraskinUSDS** [comment]
Abby to figure out messaging.

**Comment by cmgiven** [comment]
One additional thing here: we need to ensure that non-comp issues do not get moved over. Again, a thing that probably should be weeded out before the letters go out, but we definitely should ensure we don't close out anything that is not eligible.

**Comment by abbyraskinUSDS** [comment]
@shanear this is ready on the design side - it's not clear to me whether you've incorporated Chris' lastest comment, so i'll let you decide if this is ready to be moved over.

**Comment by astewarttistatech** [comment]
Blocked 

Current View: 

<img width="1353" alt="screen shot 2017-10-18 at 7 55 04 am" src="https://user-images.githubusercontent.com/23038505/31717455-effd55aa-b3d9-11e7-9654-a0264c3943e6.png">

^ Hangs up here for like 10+ minutes.

**Comment by kierachell** [comment]
### It works, but:
<img width="701" alt="screen shot 2017-10-19 at 8 46 35 am" src="https://user-images.githubusercontent.com/18075411/31771591-aefaed8e-b4aa-11e7-9e84-eee3697e1ba4.png">
<img width="392" alt="screen shot 2017-10-19 at 8 50 40 am" src="https://user-images.githubusercontent.com/18075411/31771593-af18bc1a-b4aa-11e7-9afb-3ea6ba24a2e3.png">
<img width="321" alt="screen shot 2017-10-19 at 8 51 06 am" src="https://user-images.githubusercontent.com/18075411/31771594-af413186-b4aa-11e7-94c6-41f1f33edc6a.png">


### Why does it work again? Is the API call erroring?
<img width="967" alt="screen shot 2017-10-19 at 8 54 03 am" src="https://user-images.githubusercontent.com/18075411/31771865-a6a91768-b4ab-11e7-910a-4b7bb2e59bb2.png">
- I complete intake once
- Then I go back for that same vet and redo the intake:
```
STARTED VACOLS: appeals_by_vbms_id
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 [appeals.cf.uat.ds.va.gov] [8c0e0f33-d444-4ebd-8b55-49a0419a17f0] [172.30.67.123] [CF_KIRK_317   caseflow@va.gov] [2017-10-19 08:58:02 -0400] FINISHED VACOLS: appeals_by_vbms_id:   0.000000   0.000000   0.000000 (  0.001140)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 [appeals.cf.uat.ds.va.gov] [8c0e0f33-d444-4ebd-8b55-49a0419a17f0] [172.30.67.123] [CF_KIRK_317   caseflow@va.gov] [2017-10-19 08:58:02 -0400]   VACOLS::Case Load (0.8ms)  SELECT "VACOLS"."BRIEFF".* FROM "VACOLS"."BRIEFF" WHERE "VACOLS"."BRIEFF"."BFCORLID" = :a1  [["bfcorlid", "010
511003S"]]                                                                                                                                                                                                  dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 [appeals.cf.uat.ds.va.gov] [8c0e0f33-d444-4ebd-8b55-49a0419a17f0] [172.30.67.
123] [CF_KIRK_317   caseflow@va.gov] [2017-10-19 08:58:02 -0400]    (1.4ms)  COMMIT
```
- Presumably this should fail, right?
<img width="1042" alt="screen shot 2017-10-19 at 8 58 06 am" src="https://user-images.githubusercontent.com/18075411/31771866-a6c3f678-b4ab-11e7-9fc3-77f851ecfb07.png">

**Comment by shanear** [comment]
> Presumably this should fail, right?
No, you can re-close the same appeal. It will just do nothing.

> Then I go back for that same vet and redo the intake.
this will be dealt with by https://github.com/department-of-veterans-affairs/caseflow/issues/3443

**Comment by kierachell** [comment]
### You are not pulling _only_ active appeals:
```
Completed 500 Internal Server Error in 127ms (ActiveRecord: 78.5ms)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0567e121bd4bf0854-172.30.67.93 [appeals.cf.uat.ds.va.gov] [8a3b6dbf-b519-41bc-9f36-440c56a1bc4b] [172.30.67.93] [CF_LAFORGE_317   caseflow@va.gov] [2017-10-20 09:35:59 -0400]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0567e121bd4bf0854-172.30.67.93 RuntimeError (Only active appeals can be closed):                               app/models/appeal.rb:536:in `close'
  app/models/appeal.rb:307:in `close!'                                                                                                                                                                        app/models/ramp_intake.rb:13:in `block (2 levels) in complete!'
  app/models/ramp_intake.rb:12:in `each'                                                                                                                                                                      app/models/ramp_intake.rb:12:in `block in complete!'
  app/models/ramp_intake.rb:9:in `complete!'                                                                                                                                                                  app/controllers/intake/ramp_intakes_controller.rb:32:in `complete'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                            app/middleware/metrics_auth.rb:10:in `call'
```

<img width="361" alt="screen shot 2017-10-20 at 9 34 21 am" src="https://user-images.githubusercontent.com/18075411/31823497-5756f78c-b57a-11e7-8f54-0cb53521cca8.png">
<img width="809" alt="screen shot 2017-10-20 at 9 34 30 am" src="https://user-images.githubusercontent.com/18075411/31823498-5773eba8-b57a-11e7-8db8-82fea7795c37.png">

**Comment by shanear** [comment]
> You are not pulling only active appeals:

This will be fixed by https://github.com/department-of-veterans-affairs/caseflow/pull/3693

**Comment by kierachell** [comment]
**PASSED**
- Closed some other appeals

- BRIEFF:
```
BFKEY       |BFCORLID        |BFM|BFCURLOC        |B|TO_CHAR(BFDLOOUT,'Y|BFDLOOUT |BFDLOCIN |BFBOARD   |BFCA|BFMEMID         |BFATTID         |BFDDEC
------------|----------------|---|----------------|-|-------------------|---------|---------|----------|----|----------------|----------------|---------
2840456     |785431637S      |HIS|99              |P|2017-10-24 12:54:16|24-OCT-17|24-OCT-17|00        |    |000             |000             |24-OCT-17
```
- FOLDER:
```
TICKNUM     |TINUM               |TICUKEY   |TIKEYWRD                                                                                                                                                             |TIDCLS
------------|--------------------|----------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------
2840456     |1501166             |HISTORY   |HISTORY                                                                                                                                                              |24-OCT-17
```
- ISSUES:
```
select ISSDC,ISSDCLS from ISSUES where ISSKEY='2840456';
I|ISSDCLS
-|---------
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
P|24-OCT-17
```

![back](https://user-images.githubusercontent.com/18075411/31944263-73f3da00-b899-11e7-909d-9968be5b2e2e.gif)
