### ISSUE TITLE
Intake | Display veteran's name in the UI

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3440]
As a claims assistant, I want to see the name of the veteran I am processing in various parts of the UI.

## Acceptance Criteria
- When on the Review Request page. The title copy should contain the veteran's name.
- When on any page after the search page where a veteran has been found, the veteran's name and file number should show up in the header.

## Screenshots
<img width="806" alt="screen shot 2017-09-28 at 3 31 36 pm" src="https://user-images.githubusercontent.com/1596259/30986699-5656b940-a462-11e7-81ab-bc7d3b80541e.png">

Use the Dispatch styling:
![pasted image at 2017_09_28 04_39 pm](https://user-images.githubusercontent.com/4042181/30990560-c38e0cf4-a46f-11e7-9079-c19dc1d0673a.png)

## Technical Notes
- This will require a query to BGS (a la Appeals status)

**Comment by kierachell** [comment]
**PASSED**
<img width="800" alt="screen shot 2017-10-16 at 9 06 57 am" src="https://user-images.githubusercontent.com/18075411/31613538-686c8374-b251-11e7-9fce-e47f5cb42b6f.png">
