### ISSUE TITLE
Intake Search | Error: Veteran has not received opt in notice

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3441]
As a claims assistant, I want to be able to perform the correct actions when a veteran who has not received an opt in notice sends in a opt in election letter.

## Acceptance Criteria
- Verify that if a user enters a Veteran ID that does not match a notification mailed ID, an alert is displayed on the search page (using the Caseflow styleguide and copy below).

## _Copy_
**Header:** A RAMP Opt-in Notice Letter was not sent to this Veteran.  
**Body:**
Please check the Veteran ID entered, and if the Veteran ID is correct, take the following actions outside Caseflow:  

- Upload the RAMP Election to the VBMS eFolder with Document Type <b>Correspondence</b> and Subject Line “RAMP Election.”
- Notify the Veteran by mail of his/her ineligibility to participate in RAMP using the <b>RAMP Ineligible Letter</b> in <i>Letter Creator.</i>
- Document your actions as a permanent note in VBMS.   

## _Mocks_
![image](https://user-images.githubusercontent.com/4042181/31636249-abfc315c-b297-11e7-8d2a-1e49077296a7.png)

**Comment by abbyraskinUSDS** [comment]
- Ineligible letter

**Comment by kierachell** [comment]
**PASSED**
<img width="1108" alt="screen shot 2017-10-20 at 9 38 39 am" src="https://user-images.githubusercontent.com/18075411/31823588-88ee0786-b57a-11e7-88c7-5c62cabe6858.png">
