### ISSUE TITLE
Intake Search | Error: Veteran's appeal is no longer eligible for RAMP

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3442]
As a claims assistant, I want to be able to perform the correct actions when a veteran who's appeal is no longer eligible for RAMP sends in an election letter.

## Acceptance Criteria
- Verify that if a user enters a Veteran ID for an appeal that is not eligible for RAMP (see #3433), an alert is displayed on the search page (using the Caseflow styleguide and copy below).

## _Copy_
**Header:** This Veteran is not eligible to participate in RAMP.
**Body:**
Please check the Veteran ID entered, and if the Veteran ID is correct, take the following actions outside Caseflow:  

- Upload the RAMP Election to the VBMS eFolder with Document Type <b>Correspondence</b> and Subject Line “RAMP Election.”
- Notify the Veteran by mail of his/her ineligibility to participate in RAMP using the <b>RAMP Ineligible Letter</b> in <i>Letter Creator.</i>
- Document your actions as a permanent note in VBMS.   

## _Mocks_
![image](https://user-images.githubusercontent.com/4042181/31636222-983ef2bc-b297-11e7-8320-b8352f2a2318.png)

**Comment by abbyraskinUSDS** [comment]
- Ineligible letter

**Comment by shanear** [comment]
this is blocked by https://github.com/department-of-veterans-affairs/caseflow/issues/3433

**Comment by kierachell** [comment]
**PASSED**

With some errors:
![why so much error](https://user-images.githubusercontent.com/18075411/31943100-997410be-b895-11e7-9b7b-84c637984d8f.gif)

**Comment by shanear** [comment]
> With some errors presumably captured in #3702
Yeah this is cause we aren't catching the error in the Promise. Is this something we should be doing? @NickHeiner
