### ISSUE TITLE
Intake Search | Error: Veteran already has a RAMP supplemental claim or higher level review

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3443]
As a claims assistant, I want to be able to perform the correct actions when a veteran who already has a HLR or a SC.

## Acceptance Criteria
- If a Veteran's appeal has already been processed in Caseflow, display a standard styleguide alert with the copy below, including the date the Veteran was mailed a letter inviting them to participate in RAMP.

## Copy
Title: Opt-in already processed in Caseflow
Body: A RAMP opt-in for the notice mail date MM/DD/YYYY was already processed in Caseflow. Please ensure this is a duplicate election form, and proceed to the next intake.  

## Mock
![image](https://user-images.githubusercontent.com/4042181/31945926-8fdf445c-b89e-11e7-9a8b-821b3eab4c64.png)

**Comment by abbyraskinUSDS** [comment]
In progress (pending AMO input):

![image](https://user-images.githubusercontent.com/4042181/31247692-64bf26c0-a9df-11e7-9c66-2ac3edd572f8.png)

**Comment by abbyraskinUSDS** [comment]
Asked Jennifer for input on this scenario and waiting for a response.

**Comment by shanear** [comment]
The CA would be required to check the system to ensure it’s not a duplicate as the Veteran may have had a previously excluded appeal, now be eligible or may have submitted a new NOD and so the letter may be valid.  If not, and it’s truly just a duplicate, then no action is necessary if an EP is Pending.  If we already decided the claim under RAMP, they would need to send an ineligible letter as they have no valid appeals pending that meet the requirement.  It would be the no active appeals (withdrawn) letter.

**Comment by kierachell** [comment]
**PASSED**
good enough:
<img width="1148" alt="screen shot 2017-10-25 at 9 17 03 pm" src="https://user-images.githubusercontent.com/18075411/32030586-eaba2bea-b9c9-11e7-8c71-17f65dba2024.png">
