### ISSUE TITLE
Intake | Cancel intake

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3445]
As a claims assistant, there may reasons I want to stop the processing of an intake.

## Acceptance Criteria
- There should be a "Cancel intake" button on the Review Request and Finish Processing pages.
- When the button is pressed, show a warning modal that says bad things will happen if they've already uploaded the document or created the EP 😨
- If they confirm the cancellation, cancel the intake and wipe out any data saved about the form (receipt date and option). 

## Mocks
The modal should follow [styleguide](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#modals).

### Copy

title="Cancel Intake?"
```
<p> 
     If you click the <b>Cancel intake</b> button below your work will not be saved in Caseflow.
</p>
<p>
     If you have taken any action on this intake outside Caseflow, such as establishing an EP in VBMS, 
     Caseflow will have no record of this work.
</p>
```
![image](https://user-images.githubusercontent.com/4042181/31245682-1fe74c68-a9d9-11e7-9347-e871b4bfa51d.png)

**Comment by nickheiner-usds** [comment]
> If they confirm the cancellation, close out any intake data such as start time

For analytics, it would probably be better to record that the cancellation occurred, rather than removing the start time entirely.

**Comment by abbyraskinUSDS** [comment]
@shanear this is done on the design side, assigning back to you.

**Comment by shanear** [comment]
@nickheiner-usds if you want to take on the modal part of this I can get an endpoint online and take it from there. Thoughts?

**Comment by NickHeiner** [comment]
@abbyraskinUSDS For the "close" button on the modal, you have a link. Every other Caseflow usage currently uses a button for that purpose. I'm going to use a button as well unless you tell me otherwise.

![image](https://user-images.githubusercontent.com/829827/31516005-2739842c-af65-11e7-933b-8bb702cceec5.png)

**Comment by NickHeiner** [comment]
Actually, I was wrong. I'll do it the way you had it originally.

**Comment by NickHeiner** [comment]
I assume that clicking the "cancel intake" button on the modal should redirect the user to the start page?

**Comment by NickHeiner** [comment]
@abbyraskinUSDS what do we if the Caseflow API we hit to cancell the intake fails?

**Comment by abbyraskinUSDS** [comment]
> I assume that clicking the "cancel intake" button on the modal should redirect the user to the start page?
Hmm...I would prefer that flow, though we often go to a cancellation confirmation page. Let's go back to the home page for now, as it doesn't require a new page, and I'll sync with a designer.

> What do we if the Caseflow API we hit to cancell the intake fails?
First of all, I admire your dedication to two Ls in the word cancell[ed]. Can we reuse handling from another app? Do we call the Caseflow API when you cancel EP establishment in Dispatch (maybe a @shanear question)?

**Comment by nickheiner-usds** [comment]
> > I assume that clicking the "cancel intake" button on the modal should redirect the user to the start page?
>
> Hmm...I would prefer that flow, though we often go to a cancellation confirmation page. Let's go back to the home page for now, as it doesn't require a new page, and I'll sync with a designer.

:+1:

**Comment by nickheiner-usds** [comment]
> > What do we if the Caseflow API we hit to cancell the intake fails?
>
> First of all, I admire your dedication to two Ls in the word cancell[ed]. Can we reuse handling from another app? Do we call the Caseflow API when you cancel EP establishment in Dispatch (maybe a @shanear question)?

Let's all three of us chat in person about this.

**Comment by abbyraskinUSDS** [comment]
per standup, @shanear to investigate how this scenario is currently handled in Dispatch.

**Comment by nickheiner-usds** [comment]
Unassigning myself since the next steps are on @shanear. I'll re-assign myself when I am working on this ticket again.

**Comment by shanear** [comment]
Dispatch just shows an error message with

Error
There was an error while cancelling the current claim. Please try again later.

I will just copy this functionality for now. (updating "claim" to "intake") and we can polish later.

**Comment by NickHeiner** [comment]
> If you have taken any action on this intake outside Caseflow, such as establishing an EP in VBMS, Caseflow will have no record of this work.

@abbyraskinUSDS, do you think the implications of this will be obvious to a user?

**Comment by NickHeiner** [comment]
@shanear can you update the AC to match our current understanding before handing this off to validation?

**Comment by abbyraskinUSDS** [comment]
@NickHeiner I'm not sure how else to emphasize the implications in words, but I am open to suggestions (I do think we need to make this as explicit as possible in training, and it's an unfortunate, inherent risk of an MVP that requires them to complete the bulk of the work outside our system).

**Comment by NickHeiner** [comment]
@abbyraskinUSDS how about:

> If you have taken any action on this intake outside Caseflow, such as establishing an EP in VBMS, Caseflow will have no record of this work. This could put the veteran's appeal in a broken state, and result in them receiving an inaccurate or delayed decision.

**Comment by kierachell** [comment]
**PASSED**
<img width="717" alt="screen shot 2017-10-19 at 7 50 54 am" src="https://user-images.githubusercontent.com/18075411/31769623-632fdd9a-b4a2-11e7-99f6-744177106082.png">
<img width="1041" alt="screen shot 2017-10-19 at 7 51 48 am" src="https://user-images.githubusercontent.com/18075411/31769624-634c3080-b4a2-11e7-9c00-a6fa48c0ade0.png">

**Comment by abbyraskinUSDS** [comment]
@nth let's go for what you wrote - I'm not sure how AMO will react, but it's much more direct. Do you want me to make a new ticket for it?
