### ISSUE TITLE
Intake | Redirects to correct location

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3446]
As a claims worker, I should be redirected to the correct location if I accidentally visit a url that doesn't make sense.

## Acceptance Criteria
- If the user has already started an intake and not finished it and they visit the search page in the intake app, they should be redirected to the last step they were on on the intake that they started.
- If the user has not started an intake via the search page and they visit any page in the intake app other than the search page, they should be redirected back to the search page.

**Comment by astewarttistatech** [comment]
Blocked 

Current View: 

<img width="1353" alt="screen shot 2017-10-18 at 7 55 04 am" src="https://user-images.githubusercontent.com/23038505/31717455-effd55aa-b3d9-11e7-9654-a0264c3943e6.png">

^ Hangs up here for like 10+ minutes.

**Comment by kierachell** [comment]
**PASSED**

Got stuck yesterday.

Got too stuck tho.
![movingabut](https://user-images.githubusercontent.com/18075411/31769525-1114c3ae-b4a2-11e7-91ac-c41ea84047df.gif)

**Comment by kierachell** [comment]
### I can "reprocess" the same intake, why?
![redo](https://user-images.githubusercontent.com/18075411/31770279-143e44d0-b4a5-11e7-8d8d-ea4c7e060ea0.gif)

**Comment by shanear** [comment]
> I can "reprocess" the same intake, why? Should there be "already processed" screen?

#3443 will prevent you from reprocessing the same intake

**Comment by kierachell** [comment]
**PASSED**

IT BETTER WORK
