### ISSUE TITLE
Intake | Hitting the back button

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3448]
As a claims assistant, hitting the back button at any stage in the intake process should not put me in a bad state.

## Acceptance Criteria
- If I hit the back button,
  - and I'm on the Review Request page, i should be redirected back to the Review Request page
  - and I'm on the Finish Processing page, i should be taken back to the the Review Request page.
  - and I'm on the Success page, i should not be redirected to either the Review or Finish pages.

## Notes
There was some discussion on whether we should have URLs and back button functionality at all. I've created a ticket to capture those design concerns, https://github.com/department-of-veterans-affairs/caseflow/issues/3695.

For now, we'll just make sure the user can't accidentally put themselves into a bad state.

**Comment by shanear** [comment]
@nickheiner-usds this should be all front end. Requires #3445 though.

**Comment by kierachell** [comment]
**PASSED** then

**Comment by kierachell** [comment]
closed the wrong one 🙄 (for real this time)

**Comment by kierachell** [comment]
**PASSED**
![back](https://user-images.githubusercontent.com/18075411/31944110-fbf46c54-b898-11e7-819d-e7eba3bd2690.gif)
