### ISSUE TITLE
Document List | Search state persists across different cases

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3451]
# Description
When applying filters/search to one Document List,
it seems like the state of the filtering/search persists across all document lists.

## Reproduction Steps

**Scenario 1 -**

1. Go to one case and enter a search string
1. Or filter by category
1. Go to another case
1. See that you're still in the searching/fitlering state

**Validated in the following Environment(s)**
- [x] Dev
- [ ] UAT
- [X] Preprod
- [X] Prod

## Screenshots
**_Scenario 1 - [Not the docs you're looking for]_**
![still_looking](https://user-images.githubusercontent.com/18075411/30994252-11b2af1e-a481-11e7-9d8e-9ccc56c9cb36.gif)

**Comment by kierachell** [comment]
#### Filtered state persists:
![filterstate](https://user-images.githubusercontent.com/18075411/31959250-30f190ca-b8c2-11e7-8570-2b8fe5f60e62.gif)

**Comment by kierachell** [comment]
### Filtered state persists across Cases:
![filtered](https://user-images.githubusercontent.com/18075411/32078679-c9831dea-ba75-11e7-9bb0-3a905b4a628d.gif)


### Searched state gets cleared after viewing a document within a case. Intended?
![samecasesearch](https://user-images.githubusercontent.com/18075411/32078686-d083b1c2-ba75-11e7-8ecd-186dc07a6985.gif)

### YA DIDN'T MERGE THE PR BRUH WHY IS IT HERE?!?! 😄

**Comment by kierachell** [comment]
<img width="689" alt="screen shot 2017-10-26 at 5 49 00 pm" src="https://user-images.githubusercontent.com/18075411/32081006-d5e77af8-ba80-11e7-8c15-9a20bc12333d.png">

- I think you didn't merge your PR yet.
- Once it's merged to master it gets deployed to UAT/Preprod and that's when I can test it
- In UAT/Preprod the app is deployed in production mode as is hooked up to all the VA backends.
- That's when the Github issue can go into `In-Validation`
- I don't test anything locally or with fakes. That's for whoever reviews your PR (not me)

**Comment by dannysellers** [comment]
Ugh, I definitely knew that, at least implicitly... Thanks for spelling it out—I'll let you know when this has been reviewed/merged

**Comment by kierachell** [comment]
All good :D

**Comment by kierachell** [comment]
### Now it's back to persisting :( on all cases

- Open Document List
- Enter a search token
- Observe filtering take effect
- Go back to Welcome Gate
- Go to another Document List
- observe that results are still filtered

![isaidhey_whatsgoingon](https://user-images.githubusercontent.com/18075411/32171268-f1c7c5fa-bd4d-11e7-886d-0837e5f474ee.gif)

**Comment by dannysellers** [comment]
It looks like the `clearSearch` and `clearAllFilters` actions were relocated after this was merged, so it doesn't work any more. PR [#3789](https://github.com/department-of-veterans-affairs/caseflow/pull/3789) addresses this
