### ISSUE TITLE
Hearings | Loading message has been pushed into the page break due to degradation banner

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3455]
**Currently:**

When a user is accessing Hearings Prep with a Degredation Banner the loading message that resides under the Loading Spinner is pushed through the line break 

**Expected:** 
The loading message should still remain above the line break. 

**Browser:** Chrome 
**Environment:** Preprod

**Steps to Reproduce:**
1. Access Hearings with a Degradation Banner 
2. You might want to throttle the page while loading 
3. Verify that the Loading message has been pushed down into the line break of the page. 

**Screenshots:**

<img width="1408" alt="screen shot 2017-09-29 at 11 18 03 am" src="https://user-images.githubusercontent.com/23038505/31024494-3ea71f96-a50d-11e7-8fef-23e2699a451a.png">

**Comment by astewarttistatech** [comment]
@kierachell this is currently happening just as a heads up: 
![loaderhearings](https://user-images.githubusercontent.com/23038505/31384679-f04e2ec8-ad8d-11e7-8e1d-1d5fe3c726e8.gif)

**Comment by kierachell** [comment]
### Doesn't even need a banner now to be janky.

<img width="776" alt="screen shot 2017-10-10 at 10 27 40 am" src="https://user-images.githubusercontent.com/18075411/31391885-c8f48b52-ada5-11e7-970b-2fa5092b1b13.png">
<img width="680" alt="screen shot 2017-10-10 at 10 28 20 am" src="https://user-images.githubusercontent.com/18075411/31391886-c904ca4e-ada5-11e7-86c1-924d1793fca3.png">

**Comment by astewarttistatech** [comment]
#3577

**Comment by nolawi** [comment]
ok can we close that this one since u created a new ticket for it? @astewarttistatech
