### ISSUE TITLE
Mocked data updates for demo

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3464]
AC: 
- Mocked data should always be false for Add on and Transcript Requested
- Witness shouldn't be pre-populated
- All checkboxes on worksheet page should start out false
- Mocked issues should all be from_vacols
- Contentions, evidence, and comments should start blank

**Comment by kierachell** [comment]
**PASSED**
<img width="776" alt="screen shot 2017-10-01 at 2 40 57 pm" src="https://user-images.githubusercontent.com/18075411/31057822-e71a7308-a6b6-11e7-87df-869d7253db6f.png">
<img width="558" alt="screen shot 2017-10-01 at 2 41 48 pm" src="https://user-images.githubusercontent.com/18075411/31057823-e71b8572-a6b6-11e7-9a21-17f3810d64d5.png">
<img width="355" alt="screen shot 2017-10-01 at 2 42 31 pm" src="https://user-images.githubusercontent.com/18075411/31057824-e71c326a-a6b6-11e7-8dcd-36cb0d732315.png">
<img width="384" alt="screen shot 2017-10-01 at 2 42 56 pm" src="https://user-images.githubusercontent.com/18075411/31057825-e71c53e4-a6b6-11e7-90e7-f3072e55b930.png">
