### ISSUE TITLE
[Frontend] Daily Docket | Disposition, Hold Open, AOD null on page load

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3466]
AC:
- [ ] When page loads in demo, disposition, hold open, and aod should all display 'Select...'

**Comment by kierachell** [comment]
**PASSED**
<img width="776" alt="screen shot 2017-10-01 at 2 40 57 pm" src="https://user-images.githubusercontent.com/18075411/31057808-91c2619a-a6b6-11e7-8e90-32ab352941f7.png">
