### ISSUE TITLE
[Frontend] Hearing Worksheet | Reader link opens in new tab

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3472]
AC:
- [x] Reader link should open in new tab

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome 

Steps to Validate:
1. Access Hearings
2. Upcoming Hearing Days > Daily Docket > Hearing Worksheet
3. Scroll to the bottom of the Hearing Worksheet and select "Review eFolder" 
4. Verify that the button click will take you to Reader for that Appellant. 

Screenshots: 
![hearingreader](https://user-images.githubusercontent.com/23038505/31179323-af961ca4-a8e9-11e7-9823-ca9842234641.gif)
