### ISSUE TITLE
[Backend/Frontend] Daily Docket | Appellant/Veteran Information Updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3473]
AC:
- [ ] 2nd column's header reads: 'Appellant/Veteran ID'
- [ ] Representative on daily docket matches representative org on worksheet

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Hearings 
2. Select a date from the Upcoming Hearing Days page
3. From the Daily Docket page, verify that the second column is titled Appellant/Veteran ID
4. Take note of the service organization that is associated with an appellant
5. Click on the Veteran ID of that appellant. 
6. On the Hearing Worksheet page verify that the organization that was listed is the same of what was seen in the Daily Docket page. 

Screenshots: 
<img width="1398" alt="screen shot 2017-10-02 at 8 33 22 am" src="https://user-images.githubusercontent.com/23038505/31077655-4a8594fe-a74d-11e7-9dac-2fcd22d72cd7.png">
<img width="1392" alt="screen shot 2017-10-02 at 8 35 41 am" src="https://user-images.githubusercontent.com/23038505/31077654-4a833b78-a74d-11e7-81e4-264955480857.png">
