### ISSUE TITLE
[Frontend] Hearing Worksheet | Checkbox bug

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3476]
AC: 
- When adding multiple issues, the correct checkboxes should update when checked

![onemoretime](https://user-images.githubusercontent.com/4306128/31057916-bc572cae-a6b8-11e7-8355-6fa109e261f9.gif)

**Comment by kierachell** [comment]
**PASSED**
<img width="430" alt="screen shot 2017-10-01 at 3 25 37 pm" src="https://user-images.githubusercontent.com/18075411/31058143-d53e05f4-a6bc-11e7-9abd-a0b299bdfea2.png">
