### ISSUE TITLE
[Frontend] Textboxes should auto expand

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3477]
AC:
- All textboxes should auto-expand if the user types more than the box displays 
    - Notes on Daily Docket page
    -  Witness in appellant/veteran info section on worksheet page
    - Program / Issue / Level / Description in issues section on worksheet page
    - Contentions / Periods / Evidence / Comments in bottom section on worksheet page

**Comment by kierachell** [comment]
#### Repname doesn't expand
![nope](https://user-images.githubusercontent.com/18075411/31311877-94d9fb46-ab83-11e7-9752-c11259fbb230.gif)

**Comment by nolawi** [comment]
I have updated the requirement here. rep name is only one person so we are not using textarea there. Referring #3264

**Comment by astewarttistatech** [comment]
**FAILED**

Notes on Daily Docket page does not auto-expand, but it will not let you type anymore if you fill the text area. 

Current view:
![dailydocketnotes](https://user-images.githubusercontent.com/23038505/31385349-f66d1398-ad90-11e7-99e0-429be8527142.gif)

**Comment by nolawi** [comment]
we have a max number of characters for notes @astewarttistatech

**Comment by sharonwarner** [comment]
@astewarttistatech that's correct. it auto-expands if you just press enter a bunch of times.

**Comment by kierachell** [comment]
**PASSED**
Yes it expands... 🙄
