### ISSUE TITLE
Hearing Worksheet | Adding issue shifts columns

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3478]
### Descritpion
When adding Issues on the worksheet, 
pre-loaded issue spacing is affected:

### Screenshots:

- note Issue and Level columns are moving
![moves over](https://user-images.githubusercontent.com/18075411/31058087-a2bec7fe-a6bb-11e7-8277-3b935cea2689.gif)

**Comment by mmlumba** [comment]
@annienguyenUSDS @sharonwarner Is this a concern for users? The text boxes will always be slightly bigger than the program name (unless there is a long program name that we're not using yet), so this is always going to happen.

**Comment by kierachell** [comment]
**PASSED**

![shiftmebabyonemoretime](https://user-images.githubusercontent.com/18075411/31998154-c830332a-b95c-11e7-81f2-679300a4b2f7.gif)
