### ISSUE TITLE
[Frontend] Daily Docket | Hold open options

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3479]
AC: 
- Hold open should have '0 days' as an option

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Navigate to Daily Docket page
3. In the Actions section, verify that Hold Open has 0 days as an option in the drop down. 

Screenshots: 
<img width="1298" alt="screen shot 2017-10-04 at 10 50 23 am" src="https://user-images.githubusercontent.com/23038505/31182492-ff7ab218-a8f1-11e7-8b94-bb39ec7aef01.png">
