### ISSUE TITLE
[Frontend] Hearing Worksheet | Delete modal design updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3483]
AC: 
- [ ] Text on 'Yes' button should read 'Confirm delete'
- [ ] 'Cancel' should be styled as a link
- [ ] 'Confirm Delete' button should be red

**Comment by annienguyenUSDS** [comment]
<img width="363" alt="screen shot 2017-10-02 at 10 25 11 am" src="https://user-images.githubusercontent.com/22620270/31082201-427e3c02-a75c-11e7-915b-3011dcbc8938.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Verified in: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Hearings
2. Navigate to Hearings Worksheet
3. Select the trashcan icon to the left of the Issues row
4. Verify the UI of the buttons in the modal. 

Screenshots: 
![deleterowhearings](https://user-images.githubusercontent.com/23038505/31124771-de82807e-a813-11e7-8171-6933e95d05a1.gif)
