### ISSUE TITLE
Demo | Windows | Hearings | JS Errors gone wild

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3484]
**Currently:** Accessing Hearings in Demo is creating a ton of JS errors when navigating backwards in the flow.

**Expected:** Not this

**Found in:** Chrome, Demo

**Steps to Recreate:**
1. Access Demo 
2. Switch user to Hearings
3. Select the Hearings tab
4. Select the link to Hearings
5. Select a date from the Upcoming Hearing Days page
6. Select an appellant from the Daily Docket page
7. Open Inspector (console)
8. Navigate back (back button or selecting Hearings Prep in the nav bar)
9. Look at all the errors

**Screenshots:**
![pasted image at 2017_10_02 08_50 am](https://user-images.githubusercontent.com/23038505/31083452-b34647ba-a75f-11e7-93a1-0f6c3b4c2d52.png)

**Comment by nolawi** [comment]
can we re-test, this should be resolved now

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Chrome/Windows/Demo

Steps to Validate: 
1. Access Demo
2. Switch user to Hearings
3. Select the Hearings tab
4. Select the link to Hearings
5. Select a date from the Upcoming Hearing Days page
6. Select an appellant from the Daily Docket page
7. Open Inspector (console)
8. Navigate back (back button or selecting Hearings Prep in the nav bar)
9. Verify the errors are indeed not going wild

Screenshots:

<img width="1416" alt="screen shot 2017-10-10 at 7 47 42 am" src="https://user-images.githubusercontent.com/23038505/31385009-7240eec4-ad8f-11e7-9dc1-0913c0fdc3e2.png">
