### ISSUE TITLE
Hearings | Daily Docket Missing Veteran ID/Appellant

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3485]
**Currently**: When on the Daily Docket page the second column of the table (Appellant/Veteran ID), the values are missing for each Docket. 

**Expected:** They should be there and be clickable

**Found:** In Chrome on UAT

**Steps to Recreate:**

1. Access Hearings Prep with the appropriate css_id
2. Select a date from the Upcoming Hearing Days page
3. Verify that on the Daily Docket page that the Appellant/Veteran ID values are missing. 

**Screenshots:**
<img width="1246" alt="screen shot 2017-10-02 at 11 23 16 am" src="https://user-images.githubusercontent.com/23038505/31086172-20b90c22-a767-11e7-88a9-5252977d9d49.png">

**Comment by kierachell** [comment]
**PASSED**

<img width="184" alt="screen shot 2017-10-10 at 4 25 38 pm" src="https://user-images.githubusercontent.com/18075411/31408780-ad039d2a-add7-11e7-96a7-afc1fc5aba9c.png">
