### ISSUE TITLE
Reader | Last retrieval dates for VBMS and VVA

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3488]
## Story
As a user, I want to know a claims folders was retrieved from VVA and VBMS. 

## AC
- [ ] Add two lines with VMBS and VVA retrieval time and date under the canvas, as shown below
- [ ] Expect to see these timestamps on the reader document list page only
- [ ] If manifest_vva_fetched_at is null, then the "Last VVA retrieval..." line should not appear
- [ ] The "Last VBMS retrieval..." line will always appears (since its should never be null)
- [ ] Font size: 15px

## Mockup
![image](https://user-images.githubusercontent.com/13420618/31085651-c72da448-a765-11e7-85a5-f153521304ba.png)

**Format**
Last VBMS retrieval: mm/dd/yyyy  EST 
Last VVA retrieval: 10/02/2017 00:00 am/pm timezone 

example
Last VVA retrieval: 10/02/2017 11:20pm EST

**Comment by mdbenjam** [comment]
This is blocked on https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/630. But that should be merged soon.

**Comment by lowellnava** [comment]
In addition to Gina's AC above:
* Expect to see these timestamps on the reader document list page only
* If manifest_vva_fetched_at is null, then the "Last VVA retrieval..." line should not appear
* The "Last VBMS retrieval..." line will always appears (since its should never be null)

**Comment by kierachell** [comment]
@lowellnava please just overwrite the original issue with new AC. this will keep the ticket as the single source of truth about the feature/implementation (sometimes an issue can have way too many comments to find the one that has "real AC")

### You might've missed some `doc_struct` being an array:
Error:
`TypeError: no implicit conversion of Symbol into Integer`



```
@manifest_vbms_fetched_at = doc_struct[:manifest_vbms_fetched_at]
    @manifest_vva_fetched_at  = doc_struct[:manifest_vva_fetched_at]
    @fetched_documents = doc_struct[:documents]
```

**Comment by kierachell** [comment]
### Sorry, the timezone is not formatted correctly :(

<img width="636" alt="screen shot 2017-10-26 at 3 25 18 pm" src="https://user-images.githubusercontent.com/18075411/32072815-feea0b9c-ba61-11e7-8ed5-5520e4ace1d6.png">

**Comment by kierachell** [comment]
**PASSED**

no VVA for now.
<img width="480" alt="screen shot 2017-10-31 at 8 35 05 pm" src="https://user-images.githubusercontent.com/18075411/32254991-0a424c62-be7b-11e7-8cf0-0c38d9dc35e1.png">
