### ISSUE TITLE
Investigate changing receipt date and document type in VBMS

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3490]
Preliminary investigation into changing document type and receipt date in VBMS.

Findings:
1) The new API has an update function. Similar to uploading, updating requires two steps. First, you must call `initializeUpdate` with the `contentHash`, `documentVersionReferenceId`, `vaReceiveDate`, and `versionMetadata`. Out of that we get an `uploadToken`. We then use the `uploadToken` as an input to `updateDocument` along with the `content`.
1) Someone from the VBMS team mentioned that they had trouble updating the doc type via the API, and filed a bug for us. Therefore, we may not be able to do this right away.
1) The API returns a `newDocumentVersionRefId`. We'll need to deal with versioning of documents to make this work properly. This is something we already need to consider as we switch to the new API. @nicholasholtz is compiling some information on what exactly the document versioning change requires.
1) The API requires us to re-upload the entire document, which is more than we'd like to have to do to change metadata.

Recommendation:
I believe it is worthwhile to focus on other things until we understand versioning better.

For more on the conversation with VBMS see: https://github.com/department-of-veterans-affairs/dsva-vbms/issues/92.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
