### ISSUE TITLE
Replacement CaseAssignment functionality in Case

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#3498]
comment from @mdbenjam in #3414 : "We should also delete the case_assignment.rb file. It is just connecting to the brieff table which is exactly what case.rb does. We should use that instead and delete case_assignment.rb. However, we can do that in a separate PR since this one is getting large." 

# AC for developer to confirm:
1. Remove case_assignment.rb.
1. Verify only three calls are made to VACOLS.
   - First, to get AOD
   - Second, to get issues
   - Third, to get everything else.

# AC for QA:
1. Verify the welcome gate still shows the cases assigned to a given user.
   - Verify the issues are still displayed in the table.
   - Verify whether the case is AOD is still displayed in the table.
1. Verify the welcome gate still allows users to search for veteran IDs.

**Comment by mdbenjam** [comment]
I don't think this is still a priority.
