### ISSUE TITLE
[Backend] Hearing Worksheet | Blank appeals_ready_for_hearing object

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3500]
In UAT, we're getting blank appeals_ready_for_hearing objects for some hearings (1145 is one). At the very least, that should always return the appeal associated with the hearing. This is either a bug with the method itself or UAT data.

**Comment by aroltsch** [comment]
Out of 66 appeals in UAT associated with the hearing, only 18 are actually “ready for hearing”. An appeal is ready for hearing if form 9 has been submitted, but no decision has yet been made. A lot of hearings in UAT are associated with the appeals that already have a decision date. Do we need to correct the data in UAT?

**Comment by kierachell** [comment]
**PASSED**
Checked by flipping BFDDEC
