### ISSUE TITLE
Welcome Gate | Mapping appeals that don't have issues causes Sentry errors

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3502]
# Description
When we map all issues on appeals, what if some appeals that were found for a veteran did not have issues (moved to another appeal?)

according to @cmgiven : don't even show appeals that have no issues. Seems to have been part of some old cleanup.

## Reproduction Steps

**Scenario 1 -**

1. Go to Welcome Gate
1. Search for veteran with an appeal that had no issues
1. See error

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Logs:
```
NoMethodError: undefined method `map' for nil:NilClass
  def self.issues(vacols_id)
    VACOLS::CaseIssue.descriptions([vacols_id])[vacols_id].map do |issue_hash|
      Issue.load_from_vacols(issue_hash)
    end
  end
```
## Sentry:

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/455/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/485/

**Comment by mmlumba** [comment]
Possibly related sentry error (coming from a different endpoint though): https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/486/

**Comment by kierachell** [comment]
**PASSED**

Couldn't get it to error, so should be good:
<img width="365" alt="screen shot 2017-10-13 at 8 46 31 am" src="https://user-images.githubusercontent.com/18075411/31546848-19638ca6-aff3-11e7-964e-4b91b994f8fe.png">

**Comment by kierachell** [comment]
### What about Case:IssueDescriptions?

**Comment by tejans24** [comment]
This is a duplicate issue

**Comment by mdbenjam** [comment]
Closing.
