### ISSUE TITLE
Replace Form8 v2 that says "March 2017" on the bottom left corner with version that says "Sept 2017"

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3506]
## AC
-Form 8 attached here (that says "Sept 2017" on the bottom left corner of each page) should be used in production
-Check in UAT, preprod, and prod that `FeatureToggle.enable!(:form8_v2)` has been run

[VA8 (2017) (1).pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1353036/VA8.2017.1.pdf)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Prod, UAT, Preprod

Steps for Validation: 
1. SSH into environmental jumpboxes
2. For each environment run the command FeatureToggle.features 
3. All responses should have form8_v2. 

Screenshots: 
Preprod:
<img width="580" alt="screen shot 2017-10-06 at 9 15 05 am" src="https://user-images.githubusercontent.com/23038505/31279452-1f11e6b0-aa77-11e7-8170-daee65222da7.png">
Prod:
<img width="1071" alt="screen shot 2017-10-06 at 9 17 20 am" src="https://user-images.githubusercontent.com/23038505/31279515-506e88bc-aa77-11e7-8bc9-bb3b422b8792.png">
UAT:
<img width="580" alt="screen shot 2017-10-06 at 9 15 05 am" src="https://user-images.githubusercontent.com/23038505/31279452-1f11e6b0-aa77-11e7-8170-daee65222da7.png">
