### ISSUE TITLE
Hearing Worksheet | Them texboxes are janky

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3510]
- I can make it too small
<img width="469" alt="screen shot 2017-10-03 at 7 46 27 pm" src="https://user-images.githubusercontent.com/18075411/31154229-a77da9ea-a873-11e7-9924-68a4e7389c0a.png">

- they do not auto-expand
<img width="313" alt="screen shot 2017-10-03 at 7 46 29 pm" src="https://user-images.githubusercontent.com/18075411/31154231-aaaf2576-a873-11e7-86ac-4659ec74a97a.png">

**Comment by nolawi** [comment]
@kierachell will be resolved by #3477
