### ISSUE TITLE
Loading indicator | How small can we get?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3511]
- sometimes degradation banner pushes the loading indicator into the footer territory
- or if your screen is too small
- or just open the console
<img width="975" alt="screen shot 2017-10-03 at 7 49 43 pm" src="https://user-images.githubusercontent.com/18075411/31154294-1b01add0-a874-11e7-8f1d-a4aefa9e3510.png">

**Comment by nolawi** [comment]
#3455

**Comment by kierachell** [comment]
FINE


...




AM SLOW
