### ISSUE TITLE
Remove more certification v1 code

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#3517]
Related to #3381 
Remove stats code for v2. 
QA:

- /stats page has no CertificationV2 Stats link

- Certification Stats page include both certification v1 and v2

**Comment by kierachell** [comment]
**PASSED**

Looks GONE


hard to uh... screenshot what is gone

<img width="1184" alt="screen shot 2017-10-24 at 7 11 07 pm" src="https://user-images.githubusercontent.com/18075411/31972523-24751be6-b8ef-11e7-97d2-e81587b9f93a.png">
<img width="1026" alt="screen shot 2017-10-24 at 7 11 12 pm" src="https://user-images.githubusercontent.com/18075411/31972524-248ac392-b8ef-11e7-873e-923be55a3fcd.png">
