### ISSUE TITLE
Hearing Prep / Document List | Hearing Prep role does not give access to view PDFs

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3519]
Currently users with `Hearing Prep` role are able to access Reader but not able to download any PDFs. They receive `unauthorized` message from the backend and on the frontend the PDF is eternally loading

**Comment by kierachell** [comment]
**PASSED**
<img width="675" alt="screen shot 2017-10-05 at 1 10 17 pm" src="https://user-images.githubusercontent.com/18075411/31240418-a22e812e-a9ce-11e7-9454-75a18786ba04.png">

- in eFolder
```
User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CASEFLOW_397"], ["station_id
", "397"]]
```

**Comment by mattwilcut** [comment]
Could be mocked but that record looks like PII
