### ISSUE TITLE
Document List | No scrollbar visible within the document list table

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow#3522]
# Description
When a user wants to scroll down the Document List Table without using the mouse wheel,
they can't really...

## Reproduction Steps

**Scenario 1 -**

1. Go to Document List
1. Hover over the Table
1. Try to move down without scrolling
1. Fail
1. Scroll and see scroll bar
1. Use scroll bar to see more documents

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Screenshots
**_Scenario 1 - [Haha]_**
![noscrollbar](https://user-images.githubusercontent.com/18075411/31189465-51ecf254-a906-11e7-8560-a36b3340d078.gif)

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
