### ISSUE TITLE
App Canvas | React on Rails is done broke

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3528]
# Description
Accessing Caseflow...

you can't...

## Reproduction Steps

**Scenario 1 -**

1. Go to Caseflow anything
1. Fail.
1. Open JS console
1. See error

**Validated in the following Environment(s)**
- [X] Dev
- [X] UAT
- [X] Preprod
- [ ] Prod

## Logs:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseRailsContext (webpack-internal:///1141:162)
    at reactOnRailsPageLoaded (webpack-internal:///1141:171)
    at HTMLDocument.eval (webpack-internal:///1141:225)
```

- from 
```
var el = document.getElementById('js-react-on-rails-context');
  if (el) {
    return JSON.parse(el.textContent);
  }
```

## Screenshots
**_Scenario 1 - [Is dead... so dead]_**
<img width="573" alt="screen shot 2017-10-04 at 8 07 25 pm" src="https://user-images.githubusercontent.com/18075411/31206811-2c4209ee-a948-11e7-81d1-ba759c638595.png">

I get to submit a `high-priority` bug for once... so fun.

**Comment by nickheiner-usds** [comment]
I will look at this first thing after standup.

**Comment by kierachell** [comment]
Will deploy to prod tonight and validate... just...to...be...safe

**Comment by kierachell** [comment]
**PASSED**

```
[root@ip-172-30-70-90 client]# npm -v
5.4.2
[root@ip-172-30-70-90 client]# node -v
v6.11.3
```

```
root@ip-172-30-70-90 client]# npm ls react-on-rails
caseflow-frontend@0.0.1 /opt/caseflow-certification/src/client
└── react-on-rails@8.0.6
```


application still alive
woot

**Comment by NickHeiner** [comment]
> application still alive

Excellent success criteria. :smile:
