### ISSUE TITLE
[Backend] When hearing slots cannot be found in Vacols, use defaults based on the timezone

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3530]
Tech details:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/vacols/regional_office.rb#L70

AC: 
When Vacols doesn't have slots information for a regional office, it should use the default values based on the regional office timezone
```
SLOTS_BY_TIMEZONE = {
    "America/New_York" => 11,
    "America/Chicago" => 9,
    "America/Indiana/Indianapolis" => 11,
    "America/Kentucky/Louisville" => 11,
    "America/Denver" => 9,
    "America/Los_Angeles" => 7,
    "America/Boise" => 9, 
    "America/Puerto_Rico" => 11,
    "Asia/Manila" => 7,
    "Pacific/Honolulu" => 7,
    "America/Anchorage" => 7 
  }
```

**Comment by kierachell** [comment]
**PASSED**
Will have to iron the rest out later.
<img width="1126" alt="screen shot 2017-10-11 at 9 06 36 am" src="https://user-images.githubusercontent.com/18075411/31442198-98306432-ae63-11e7-957a-22987c0329bc.png">
