### ISSUE TITLE
[Backend] Set timezone for the hearing date

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3532]
Notes:
The hearing datetime reflect the time zone of the local RO, so we append the timezone based on the regional office location
and then convert the date to Eastern Time

AC:
Datetime should be displayed in regional office's timezone.

**Comment by kierachell** [comment]
**PASSED**
- In vacols:
```
TO_CHAR(HEARING_DATE,
---------------------
2017/11/17:01:00:00pm
```
- in Caseflow:
```
Fri, 17 Nov 2017 13:00:00 EST -05:00
```
