### ISSUE TITLE
Reader sidebar document information issue keys are not unique

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#3533]
![image](https://user-images.githubusercontent.com/1976755/31239841-847c752a-a9cc-11e7-9b4b-c557566dd2c2.png)

* This also happens in ClaimsFolderDetails

**Comment by mdbenjam** [comment]
@tejans24 Can you define this a little more. Add some AC? Hard to know what I'm looking for.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate: 
1. Access Reader
2. Open a document with inspector open and verify that the warning listed above not showing when Document Information child (accordion) is opened. 


Screenshots: 
<img width="1370" alt="screen shot 2017-10-17 at 2 00 36 pm" src="https://user-images.githubusercontent.com/23038505/31681086-342e46a8-b344-11e7-8f08-7d7435ea6d4f.png">
<img width="1362" alt="screen shot 2017-10-17 at 2 02 55 pm" src="https://user-images.githubusercontent.com/23038505/31681087-34955546-b344-11e7-8694-d4dd0667c3bf.png">
