### ISSUE TITLE
[Backend/Frontend] Hearing Worksheet | Issues add/delete/edit save to backend

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3546]
AC: 
- Added issues get saved to the backend, and the id gets saved to Redux
- Deleted issues are deleted from the backend, and _destroy is set to true in Redux
- Edited issues are saved to the backend

**Comment by kierachell** [comment]
**PASSED**
### Add
```
#<WorksheetIssue id: 848, appeal_id: 11582, vacols_sequence_id: "41", reopen: false, vha: false, allow: false, deny: false, remand: false, dismiss: false, program: "NEW", name: "ISSUE", levels: "HERE", description: "PSLSPLDSPLASD", from_vacols: false, deleted_at: nil>
```
<img width="808" alt="screen shot 2017-10-10 at 4 31 24 pm" src="https://user-images.githubusercontent.com/18075411/31409027-7bb9d1a2-add8-11e7-8155-4e7ac5f33876.png">
### Edit
```
#<WorksheetIssue id: 848, appeal_id: 11582, vacols_sequence_id: "41", reopen: false, vha: false, allow: false, deny: false, remand: false, dismiss: false, program: "NEW", name: "ISSUE", levels: "HERE", description: "EDITED", from_vacols: false, deleted_at: nil>
```
<img width="568" alt="screen shot 2017-10-10 at 4 32 40 pm" src="https://user-images.githubusercontent.com/18075411/31409089-a754503a-add8-11e7-9d50-afb8299a3bf0.png">
```
#<WorksheetIssue id: 848, appeal_id: 11582, vacols_sequence_id: "41", reopen: false, vha: true, allow: true, deny: true, remand: true, dismiss: false, program: "NEW", name: "ISSUE", levels: "HERE", description: "EDITED", from_vacols: false, deleted_at: nil>
```

### Delete: I am not deleting a VACOLS issue
<img width="1152" alt="screen shot 2017-10-10 at 4 34 16 pm" src="https://user-images.githubusercontent.com/18075411/31409158-f1519b98-add8-11e7-8d2e-70ceff489346.png">
