### ISSUE TITLE
Status API | Move endpoint from Prod VACOLS to DMS-provisioned VACOLS copy

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3549]
related:
https://github.com/department-of-veterans-affairs/caseflow/issues/2680

**Comment by cmgiven** [comment]
Heads up that the next iteration of Appeals Status is expected to roll out at the end of January. I also know that Vets.gov is working on a "hardening" for the month of December in anticipation of increased traffic next year. If we were able to make this cutover by the end of January, that'd be amazing, but I don't know what is required.

**Comment by askldjd** [comment]
Things that we need to do:
1. Add indices back into VACOLS DMS now that we have stabilized DMS.
1. Add a second VACOLS pool to Caseflow and reroute Appeals status to use the second pool.
