### ISSUE TITLE
Daily Docket | Worksheet | UI not totally responsive on smaller monitors

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3561]
### Remember that Macs have higher resolution so things appear smaller on their monitors:

- Textboxes overflow
- Dropdown text overflows
- 
<img width="808" alt="screen shot 2017-10-10 at 6 35 37 pm" src="https://user-images.githubusercontent.com/18075411/31413990-dd8e01ee-ade9-11e7-804d-adec044d3f28.png">

- Checbox text overflow
<img width="536" alt="screen shot 2017-10-10 at 6 39 18 pm" src="https://user-images.githubusercontent.com/18075411/31414116-66a0bef4-adea-11e7-87e8-f9909a529e58.png">

<img width="1092" alt="screen shot 2017-10-10 at 6 21 23 pm" src="https://user-images.githubusercontent.com/18075411/31414121-6e49411c-adea-11e7-8258-5112f9d0e6aa.png">

**Comment by astewarttistatech** [comment]
Currently: 
<img width="798" alt="screen shot 2017-10-12 at 8 44 47 am" src="https://user-images.githubusercontent.com/23038505/31496683-62d5e4fc-af2a-11e7-83e9-49f6b6671477.png">

**Comment by nolawi** [comment]
test at 1024min. although it looks good at 1000ish

**Comment by astewarttistatech** [comment]
Blocked because the Veteran ID/ Appellant is missing again (yes there is a ticket out for it, just forgot the number). 

Current view: 
<img width="1232" alt="screen shot 2017-10-18 at 7 50 50 am" src="https://user-images.githubusercontent.com/23038505/31717283-43e2f752-b3d9-11e7-9f9e-610673982dee.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: Chrome 

Steps to Validate: 
1. Access Hearing Prep pages at 1000px width 

Screenshots: 
@1000px width 

<img width="1376" alt="screen shot 2017-10-18 at 11 51 49 am" src="https://user-images.githubusercontent.com/23038505/31732908-0bbecd0e-b408-11e7-9841-cd673011c0b3.png">
![1000px width](https://user-images.githubusercontent.com/23038505/31732921-177a10b8-b408-11e7-9832-af77200e1b44.png)
