### ISSUE TITLE
Hearing Worksheet | Multiple Appeal Stream certification and SSOC dates merged?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3563]
### Where there are multiple appeal streams, it seems like they share Certification and SSOC dates. Is that expected?

- Should the dates be different for different appeals?
<img width="600" alt="screen shot 2017-10-10 at 8 02 55 pm" src="https://user-images.githubusercontent.com/18075411/31416308-3465eade-adf6-11e7-84b8-e1b97f8c66a1.png">

**Comment by lakohl** [comment]
If the appeal streams are still separate, it's unlikely.  (though it's possible the Vet could have filed the paperwork on the same dates.) @cmgiven can you confirm?

**Comment by cmgiven** [comment]
It would actually be pretty common for them to share certification date. Remember that they're generally being worked by the same person at the RO. I can't speak to SSOC, but I wouldn't say that sharing the same date is wrong.

**Comment by lakohl** [comment]
Good point @cmgiven that makes sense!

**Comment by astewarttistatech** [comment]
Can't get to hearing worksheet because Veteran ID/Appellant is missing again (There is an issue out there for this, just can't remember the number). 

Current View: 
<img width="1325" alt="screen shot 2017-10-17 at 1 52 10 pm" src="https://user-images.githubusercontent.com/23038505/31680517-86610caa-b342-11e7-992c-a9662756a6f3.png">

**Comment by astewarttistatech** [comment]
Now blocked because all of the css_id's are running either no Hearings or only one Appeal Stream

**Comment by astewarttistatech** [comment]
Now missing the Veteran ID/Appellant again.

**Comment by astewarttistatech** [comment]
Back to reason 2 🙃

**Comment by kierachell** [comment]
**PASSED**
<img width="569" alt="screen shot 2017-10-18 at 2 39 25 pm" src="https://user-images.githubusercontent.com/18075411/31736229-32310b64-b412-11e7-951d-5fa8b9f505b2.png">
<img width="612" alt="screen shot 2017-10-18 at 2 39 29 pm" src="https://user-images.githubusercontent.com/18075411/31736230-324ef886-b412-11e7-8a3c-83515ccdd230.png">
