### ISSUE TITLE
Daily Docket / Hearing Worksheet | Appellant name weirdly formatted

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3564]
### Why is there a comma at the start?
<img width="344" alt="screen shot 2017-10-11 at 9 31 09 am" src="https://user-images.githubusercontent.com/18075411/31443354-34410edc-ae67-11e7-82df-c9b7a225b699.png">
<img width="292" alt="screen shot 2017-10-11 at 9 31 12 am" src="https://user-images.githubusercontent.com/18075411/31443355-34628030-ae67-11e7-8cae-e69bf0b556c5.png">

**Comment by astewarttistatech** [comment]
So what is the naming convention of the Veteran? This is not mentioned in the AC. Pushing this back. @annienguyenUSDS
