### ISSUE TITLE
Welcome Gate | All cases are marked as AOD

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3565]
## Description
- Users reported that all of their cases are (or were) showing as AOD in the Welcome Gate, even though they are not all AOD cases. We should fix this.

## Acceptance Criteria
- Verify that only those cases marked as AOD in VACOLS are displaying the red "AOD" label in the Welcome Gate

**Comment by kierachell** [comment]
**PASSED**

- Logged in as bugged user
- AOD is ok
<img width="229" alt="screen shot 2017-10-19 at 3 30 53 pm" src="https://user-images.githubusercontent.com/18075411/31790166-8b38d360-b4e2-11e7-9872-b1307a06566e.png">
