### ISSUE TITLE
NoMethodError undefined method `capitalize' for nil:NilClass

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3569]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/503/
app/models/worksheet_issue.rb in block in create_from_issue at line 14
```
  class << self
    def create_from_issue(appeal, issue)
      WorksheetIssue.find_or_create_by(appeal: appeal, vacols_sequence_id: issue.vacols_sequence_id).tap do |record|
        record.update(program: issue.program.capitalize,
                      name: issue.type[:label],
                      levels: issue.levels.join("; "),
                      description: issue.description.join("\n"),
```

**Comment by kierachell** [comment]
**PASSED**

Didn't see error when no issues happened, so I reckon it's alright:
<img width="828" alt="screen shot 2017-10-15 at 8 19 27 pm" src="https://user-images.githubusercontent.com/18075411/31590872-32ee4162-b1e6-11e7-8eb7-042a056731ae.png">
