### ISSUE TITLE
Postmortem 10/18/2017 - VVA documents not included in manifest

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3570]
Description of the incident:
On Thursday 10/05/2017, eX could not connect to VVA due to the OpenSSL incompatibility. In order to allow users to continue using eX, VVA feature was disabled for all eX users for a few hours. As a result, users downloaded manifests without VVA documents in them. Users were not notified that VVA feature was out of service. We received a few support issues that VVA documents were not downloading. Even after the VVA feature was enabled for users, users still could not re-download the manifest for another 3 days because eX caches the manifest for 3 days. 

As a solution we deleted cached manifests for users so they can re-download the manifest.

Solutions:
1. Allow users to delete the cache from the UI
2. Invalidate the cache (how can we know when the cache is not valid?)

**Comment by sunil-sadasivan** [comment]
Interesting... is there a reason why it's set for 3 days?  
I believe the File API only caches manifests for 3 hours (if I'm not mistaken?)

**Comment by evankroske** [comment]
Is there a way to know whether the manifests we're writing will be invalid? It would be better to not write a bad manifest than to make users manage their manifests

**Comment by nickheiner-usds** [comment]
I tried unassigning Anya so this would show up in the standup app as a discussion, but it didn't. 😦 Anya can just remember to announce this herself at standup.

**Comment by aroltsch** [comment]
1. We can have two timestamps: `vva_manifest_fetched_at` and `vbms_manifest_fetched_at`. If the user  clicks on history or tries to search for a file number, we check the above timestamps and if either one of them is nil or old, we re-download the manifest for user.
2. If VVA feature flag is off, we need to display a message to users that manifests won't contain VVA documents
