### ISSUE TITLE
Hearings | Spinner | Smaller size than normal

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3577]
**Currently:** I don't know why the spinner in Hearings is always changing, but its small now. 

**Expected:** The spinner should be the actual size (refer to styleguide)

**Found:** Chrome/Preprod

**Steps to Recreate:** 
1. Log into Hearings in Preprod
2. Verify the spinner is small. 

**Screenshots:**
![hearingsloaderbroke](https://user-images.githubusercontent.com/23038505/31496159-406ea446-af28-11e7-8d43-f8f9d92cc0bc.gif)

**Comment by kierachell** [comment]
**PASSED**

@mmlumba 

WITH

DEM

FIXES

<img width="923" alt="screen shot 2017-10-23 at 9 34 56 pm" src="https://user-images.githubusercontent.com/18075411/31920921-12652e74-b83a-11e7-9ef0-bbf8182e42b9.png">


💪
