### ISSUE TITLE
Field 5A on the Form 8 V2 should pull from BRIEFF.BFDRODEC

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3579]
See https://github.com/department-of-veterans-affairs/appeals-support/issues/679.

## AC
- Field 5A on the Form 8 V2 should pull from BRIEFF.BFDRODEC and not be the NOD date

**Comment by kierachell** [comment]
**PASSED**
<img width="167" alt="screen shot 2017-10-15 at 8 14 49 pm" src="https://user-images.githubusercontent.com/18075411/31590844-8860dfac-b1e5-11e7-8f03-931943d871af.png">
<img width="251" alt="screen shot 2017-10-15 at 8 14 52 pm" src="https://user-images.githubusercontent.com/18075411/31590845-886a6108-b1e5-11e7-9609-870a252f8fbc.png">
