### ISSUE TITLE
Finish Processing | Show VACOLS issues for eligible elections

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3583]
When processing the election outside Caseflow, I want to see all the issues on appeal alongside the steps I need to complete, so I can finish processing the RAMP election letter without having to open VACOLS in a separate window.

## Acceptance Criteria
- Verify that on the Finish Processing page, every pending issue is listed below the steps, in the blue alert from styleguide. 
- Verify that the number of pending appeals is displayed above the issues

## Mocks
<img width="1041" alt="screen shot 2017-10-19 at 11 17 10 am" src="https://user-images.githubusercontent.com/1596259/31778646-2e91c900-b4bf-11e7-87b1-7099d8ebe02a.png">

**Comment by abbyraskinUSDS** [comment]
Working on adding issues to this step.

**Comment by NickHeiner** [comment]
@abbyraskinUSDS it would be nice if the AC mentioned what screen this was supposed to appear on.

**Comment by abbyraskinUSDS** [comment]
Sure, it's in the story title, but added to first AC.

**Comment by NickHeiner** [comment]
Ah, sure, that makes sense. I missed that.

**Comment by kierachell** [comment]
### No issues:
<img width="927" alt="screen shot 2017-10-20 at 9 29 36 am" src="https://user-images.githubusercontent.com/18075411/31823344-ef144d14-b579-11e7-80af-e670763b5421.png">

### This veteran does _not_ have 7 active appeals, only a couple:
<img width="361" alt="screen shot 2017-10-20 at 9 34 21 am" src="https://user-images.githubusercontent.com/18075411/31823379-fed67ef2-b579-11e7-8874-c791b1721678.png">
<img width="809" alt="screen shot 2017-10-20 at 9 34 30 am" src="https://user-images.githubusercontent.com/18075411/31823380-fef38222-b579-11e7-89be-7371805d720d.png">

**Comment by shanear** [comment]
> You are not pulling only active appeals:

This will be fixed by https://github.com/department-of-veterans-affairs/caseflow/pull/3693

**Comment by kierachell** [comment]
@abbyraskinUSDS 

- Should the issues be numbered?
<img width="1094" alt="screen shot 2017-10-24 at 8 45 58 am" src="https://user-images.githubusercontent.com/18075411/31943831-fc37ef20-b897-11e7-98f2-30f6d44ada8b.png">
![whao](https://user-images.githubusercontent.com/18075411/31943832-fc4a9008-b897-11e7-9ade-8de5d82ec34d.gif)

**Comment by abbyraskinUSDS** [comment]
I had numbered them originally, but this is fine for now. Thanks.
