### ISSUE TITLE
Welcome Gate | Previously opened cases are showing as "new"

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3585]
A couple users have reported that cases they had previously opened have started showing as "new" on the welcome gate. 

## AC
- Verify that cases that have been previously opened show a "continue" button next to them on the welcome gate, and that their "new" status does not reset.

**Comment by kierachell** [comment]
**PASSED**
Stays `continue` after a few hours
<img width="1129" alt="screen shot 2017-10-19 at 3 30 02 pm" src="https://user-images.githubusercontent.com/18075411/31790130-7057ae9a-b4e2-11e7-86ac-f2b67d0b0c39.png">
