### ISSUE TITLE
Show veteran name after page reload

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3588]
If you hit refresh at step 2, then you won't see the vet's name:

![image](https://user-images.githubusercontent.com/829827/31511427-b3d2e7d0-af55-11e7-8b0b-f77a7deae4ee.png)

This is because when you're resuming an intake, we pass `intakeId`, but we don't pass the vet name and file number. And the frontend doesn't make another request to `/intake` to get that data. We should pass this data along with `intakeId`.

**Comment by kierachell** [comment]
### Works after refresh
<img width="863" alt="screen shot 2017-10-16 at 9 01 02 am" src="https://user-images.githubusercontent.com/18075411/31613274-9acaa1b2-b250-11e7-88c6-a76767c6c6f2.png">


### But now you have a side-effect of persisting it back on the search page.

**Comment by shanear** [comment]
>But now you have a side-effect of persisting it back on the search page.

This issue will be fixed with #3448.

**Comment by kierachell** [comment]
**PASSED** then
