### ISSUE TITLE
Performance Degradation Banner's styling suffered undesirable changes

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#3590]
According to @amprokop this might have be related to react rendering of top banner in Reader. 
Caseflow seems to be unaffected. 

![assignments caseflow reader](https://user-images.githubusercontent.com/4960030/31512623-a0c2f3d4-af59-11e7-9be9-c361ff958a9b.png)

## AC
- Performance degradation banner should match mockup in https://github.com/department-of-veterans-affairs/caseflow/issues/2294

**Comment by kierachell** [comment]
**PASSED**
<img width="1268" alt="screen shot 2017-10-13 at 9 19 07 am" src="https://user-images.githubusercontent.com/18075411/31548093-bed26b04-aff7-11e7-9103-c8c95c707204.png">
