### ISSUE TITLE
Welcome gate | Add link to hearing working sheet for cases

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3601]
## Story
As an attorney, I want to see view my judge's hearing notes specifically so that I get a quick and easy summary of the case. 

## AC
- [ ] Add a downloadable link to hearing worksheet for those cases that have hearing worksheets in the Caseflow database
  ~~- [ ] Format of the link should be View Hearing Worksheet [mm/dd/yyyy of hearing]~~ Per conversation with @sharonwarner this is obsolete. There will also be no download icon. 

## Mockup 
![image](https://user-images.githubusercontent.com/13420618/31898821-117c74ec-b7e8-11e7-941d-5e68a66c58b7.png)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/3602

**Comment by cmgiven** [comment]
Confirmed with @gnakm that this is not intended to be limited to AOD cases.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome | RConsole

Steps to Validate: 
1. Pull up an EC2 instance in the chosen environment
2. Pull up Reader 
3. Select an Appeal ID from current welcome gate
4. Add Hearing to an Appeal via `Generators::Hearing.create(appeal: Appeal.find("..."))` in terminal 
5. Access Reader Welcome Gate 
6. Verify that download link is now present under the Appeal id originally used. 

Screenshot: 
<img width="642" alt="screen shot 2017-12-22 at 4 35 37 pm" src="https://user-images.githubusercontent.com/23038505/34313118-0593799a-e737-11e7-9852-268d41d7a3a0.png">
