### ISSUE TITLE
Document list | Add pdf link to hearing working sheet in claim folder detail

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3602]
## Story
As an attorney, I want to see view my judge's hearing notes specifically for AOD cases so that I get a quick and easy summary of cases that need to be expedited. 

## AC
- [ ] Add a section with label Notes (left aligned with Docket number label) 
- [ ] Add downloadable hearing worksheet link under the section.
  - [ ] Format of the link should be View Hearing Worksheet [mm/dd/yyyy of hearing]

## Mockup 
![image](https://user-images.githubusercontent.com/13420618/31557418-9fdcd21a-b016-11e7-9a21-ff3a3a154657.png)

Alignment
![image](https://user-images.githubusercontent.com/13420618/31557428-a7eaf8c4-b016-11e7-8849-bb696fbaa927.png)

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/3601

**Comment by gnakm** [comment]
@lakohl @annienguyenUSDS from our last chat, we decided to go with just having a link on the welcome gate page, correct?

**Comment by lakohl** [comment]
Yes, I believe so

**Comment by gnakm** [comment]
I'm going to drop the label `won't fix` though this isn't a bug but to track it incase we need to open it again. Closing!
