### ISSUE TITLE
Intake Logo color 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3615]
## Story
Per discussion (or my decree), we will be moving forward with yellow for the Caseflow Intake logo

## AC
- [ ] Add a logo to Caseflow Intake header (color #FFCC4E)

## Mockup
![image](https://user-images.githubusercontent.com/13420618/31565451-dca08822-b034-11e7-9de5-af0fcaba1799.png)

## Files
[Logo can be found here](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Logo/Caseflow%20Logo%20-%20Intake.svg)

## Related issue
https://github.com/department-of-veterans-affairs/caseflow/issues/3616

**Comment by NickHeiner** [comment]
> Per discussion (or my decree),

:smile:

**Comment by kierachell** [comment]
**PASSED**

GOLDEN
<img width="401" alt="screen shot 2017-10-24 at 8 17 58 am" src="https://user-images.githubusercontent.com/18075411/31942603-e0bcfb2c-b893-11e7-9a1d-59d933f94efb.png">
