### ISSUE TITLE
Style guide | Color clean up 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3616]
## Story

As a designer and developer, I need to know the latest updates on Caseflow colors and how they are being used. We need to update a couple of things.

## AC

- Under logo section, add Caseflow Intake color and copy as shown in mock
- Change Caseflow Reader Case Summary category so that it matches the new intake color
- Make sure all case summary categories in reader are now in the new color
- Change Reader category "Certification" to "Other Evidence"

## Mockup

What it should look like 
![image](https://user-images.githubusercontent.com/13420618/31566279-e3246620-b037-11e7-81e6-55e4b8f27d1c.png)

What it currently looks like 
![image](https://user-images.githubusercontent.com/13420618/31566309-043999ca-b038-11e7-8b0f-a36d0db99959.png)

## Related issue
https://github.com/department-of-veterans-affairs/caseflow/issues/3615

**Comment by Sjones352** [comment]
Currently 

<img width="735" alt="screen shot 2017-10-31 at 10 37 55 am" src="https://user-images.githubusercontent.com/23080951/32229651-b9130168-be27-11e7-88ba-808aed2ff8bf.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod

Steps to Validate: 
1. Access Style Guide
2. Navigate to the Logo section for colors. 
3. Validate that the Reader Categories are labeled correctly as well as that for Logos. 

Screenshot:
<img width="1390" alt="screen shot 2017-11-03 at 1 24 11 pm" src="https://user-images.githubusercontent.com/23038505/32387441-d8d0fda0-c09a-11e7-8bd0-7fb58fd5df86.png">
