### ISSUE TITLE
Mail Intake | Press Enter to search

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3617]
### When I search for a file number, I want the search to trigger when I press Enter (like in Reader)

![click_to_search](https://user-images.githubusercontent.com/18075411/31610636-c3313ad0-b246-11e7-9d2f-cf458d8a1c38.gif)

**Comment by NickHeiner** [comment]
Thanks for noticing this, @kierachell. I had this on my mental to-do list of things to fix.

**Comment by kierachell** [comment]
**PASSED**
![clear](https://user-images.githubusercontent.com/18075411/31920841-71a0174c-b839-11e7-9922-3d610179d0e0.gif)
