### ISSUE TITLE
Welcome Gate | Viewed state not persisted

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3618]
### Why is it reseting back to new?

![new](https://user-images.githubusercontent.com/18075411/31614595-e66211d8-b254-11e7-8cc8-b42f0ade6ebd.gif)

**Comment by dannysellers** [comment]
@kierachell I'm not able to reproduce this behavior. Did you do anything beyond navigating between pages (within a single session) when you encountered this?

**Comment by kierachell** [comment]
**PASSED**

I think https://github.com/department-of-veterans-affairs/caseflow/issues/3585 covered this (I was slow making the issue)
