### ISSUE TITLE
Hearing Prep - cache `slots` information in Redis and expire it after a week (debatable) 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3622]
We can cache `slots` information in Redis and expire it after a week. The key will be based on the RO and a week day. This information rarely changes so no need to query Vacols each time. 

AC:
Ensure slots are pulled from cache for RO based on the week day.

**Comment by sharonwarner** [comment]
We're moving the slots information to Caseflow. This ticket is no longer needed.
