### ISSUE TITLE
[Backend] Hearing Worksheet | Pull in notes field from issues 

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3623]
AC:
The description column in the issues section of the hearing worksheet page should display what's in the notes section of the issues table in VACOLS.

**Comment by kierachell** [comment]
**PASSED**
<img width="580" alt="screen shot 2017-10-18 at 2 48 33 pm" src="https://user-images.githubusercontent.com/18075411/31736856-e09d5328-b413-11e7-9c18-68696bd9b2da.png">
<img width="713" alt="screen shot 2017-10-18 at 2 48 44 pm" src="https://user-images.githubusercontent.com/18075411/31736857-e0bdcd74-b413-11e7-9575-57e3beb79a02.png">
<img width="564" alt="screen shot 2017-10-18 at 2 49 02 pm" src="https://user-images.githubusercontent.com/18075411/31736858-e0d9cfec-b413-11e7-82e7-ea2b602962ac.png">
