### ISSUE TITLE
Blacklist | Remove Group 1 - BVA users on 10/30/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3627]
As Product Owner, I would like the following users removed from the Reader blacklist on Monday, 10/30/2017 at 8 am (as early as possible) so that all users can enjoy this product.

## Acceptance Criteria
1. Verify that the only following users have been removed from the blacklist.

     **_Group 1 - Reader Users (114)_**
“BVATADAMS”, “vacoans”, “bvasflot”, “vacoboydm1”, “bvadbrook”, “bvajrbryant”, “bvajcheng”, “bvabchatterjee”, “bvaamclark”, “vacoalexaj10”, “vacoKatzD3”, “bvabbcopeld”, “bvaacryan”, “vacoDavidC”, “vacoDonohP”, “bvajdworkin”, “bvacfleming”, “bvajflynn”, “bvajpgervas”, “bvasginski”, “vacogrzect”, “vacohouled”, “vacojigget”, “bvagjmcrae”, “vacokalols”, “bvankamal”, “bvackammel”, “bvajkim”, “bvaKKordich”, “bvaclkras”, “vacokunjue”, “bvaclamb”, “bvakmillikan”, “bvakmitchell”, “vaconealm”, “bvadsnelson”, “vaconguyep”, “vaconohp”, “bvatoshay”, “vacopedenn”, “vacosetteJ”, “bvacsmith”, “BVATHSMITH”, “bvamsopko”, “vacoThompM6”, “vacowainas”, “bvaffuller”, “vacoYehN”, “bvahyoo”, “vacoabarrs”, “bvajabrams”, “vacopoindp”, “vacoArnolA2”, “vacobanksc4”, “bvaabarone”, “bvalbarstow”, “vacobaylesjj”, “bvacbiggins”, “vacoBreitn”, “bvadbreitbeil”, “bvarburriesci”, “bvaccollins”, “vacoDaillM”, “bvajrdavit”, “vacoDeanR2”, “bvabdonnelly”, “bvajdupont”, “vacoedelsm”, “bvarpatner”, “bvaalevans”, “vacofergus1”, “vacoFosteK5”, “bvamcgraham”, “bvatgriffin”, “vacoHarriR3”, “bvamhawley”, “bvakhughes”, “bvajkomperda”, “bvaskreitlow”, “bvamelarkin”, “bvaclawson”, “bvaamacken”, “bvakwalters”, “vacomcleop”, “bvajmeawad”, “vacomorrisj”, “bvatcasey”, “vacomukhec”, “vaconealm”, “vaconorwoa”, “vacopatels”, “vacoPerkim5”, “vacoquarlb”, “bvamriley”, “bvawripp”, “bvabchech”, “bvagrsenyk”, “bvajrsiegel”, “vacoskowrw”, “bvagslovick”, “bvamsorisio”, “vacostalll”, “vacostaskn”, “bvaevpollack”, “bvaKWallin”, “bvalwgreen”, “bvajwhite”, “bvabwilliams”, “bvatwishard”, “bvabyoon”, “bvaMYoung”, “BVAKALLEN”, “vacoakinto”, “vacofalest”, "BVARVELDENZ", "vacoscardr", "bvaaweis", "BVACBOYD", "bvadhavelka", "vacogonzam6", "BVAMBRUCE", "bvaebrandau"

## Related Stories
**_PM Issue(s)_**
IP | Reader | Request Blacklisted users removed - Throttle Release [#1597](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1597)

**_Engineering Stories_**
Create blacklist for phased rollout [#3395](https://github.com/department-of-veterans-affairs/caseflow/issues/3395)

**Comment by nikitarockz** [comment]
@abbyraskinUSDS  This story is ready to go.

**Comment by mdbenjam** [comment]
I've added a feature toggle and removed these folks from the blacklist.
