### ISSUE TITLE
Deny List | Remove Group 3 - BVA users on 11/13/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3629]
As Project Manager, I would like the following users removed from the Reader Deny List on Monday, 11/13/2017 at as early as possible so that all users can enjoy this product.

## Acceptance Criteria
1. Verify that the only following users have been removed from the Deny List.

**_Reader Users - Group 3 (Total 328)_** 
_Note:  All users including those who might have been granted access previously_

“vacoAbdelD”, “bvajadavis”, “bvaaadamson”, “bvaaahlberg”, “bvaalderman”, “bvakalibran”, “bvadsames”, “bvadames”, “bvaledwards”, “bvajjenkins”, “bvatanthony”, “bvamauer”, “vacobakerjh”, “vacoljbakke”, “bvakbanfield”, “bvacbanister”, “bvalbarnard”, “bvaabarner”, “bvaJBarone”, “vacobaskel”, “bvacbates”, “vacobaxtes”, “vacoBernaT”, “vacobieret”, “bvatblake”, “vacoBlaker”, “vacobodib”, “bvaebrandau”, “vacobrandk1”, “bvajtaylor”, “bvadbrenn”, “bvaHBrokowsky”, “vacobrownn6”, “vacobrowns”, “vacoBrozyK”, “BVAMBRUCE”, “vacobrunor”, “bvabwilson”, “bvaabudd”, “vacoBulgeF”, “bvaIcannaday”, “vacocaraca”, “vacocarroe”, “bvamcaylor”, “bvadtcherry”, “bvadchiapp”, “bvavchiapp”, “vacochilcd1”, “vacoChoC”, “bvamcolicelli”, “vacocooklc”, “vacocrawfl”, “vacoCreegA”, “bvaLCrohe”, “bvajcrowley”, “bvalbcryan”, “bvasdale”, “vacoDausH”, “vacodavist1”, “bvajdeane”, “vacoDeChiA”, “bvajdefrank”, “bvaedeichert”, “bvasdelhauer”, “vacofergua”, “bvardodd”, “bvamdoran”, “vacoduffym”, “bvadebaugh”, “bvaledmonson”, “vacoellior”, “ bvajembscad”, “bvamespinoza”, “vacoEvansB”, “bvaRFeinberg”, “bvacsfields”, “vacoFisheH”, “vacoFitzgT”, “bvaaflamini”, “vacoFowleJ”, “bvajfrancis”, “bvarfrank”, “vacofrankp”, “bvagfraser”, “vacofreems”, “bvajfussell”, “vacogandhr”, “bvabbgarcia”, “vacogastok”, “vacoGentiJ”, “bvakgeorgiev”, “vacoGiaqum”, “bvakgielow”, “bvaygomez”, “vacogonzam6”, “vacoGrossC”, “bvakgunn”, “bvaahaddock”, “bvakhaddock”, “bvaahampton”, “bvamhannan”, “vacohansot”, “vacoharnec1”, “vacoHarrim30”, “bvadhavelka”, “vacohawkit”, “BVASHENEKS”, “bvaJHenriquez”, “vacohenryt”, “vacoHiggiJ”, “bvamhindin”, “vacoHitchi”, “bvahhoeft”, “bvashoopen”, “vacoHooveL”, “bvachoubeck”, “bvachowell”, “vacohunns”, “bvamjin”, “vacoinnetl”, “BVACBOYD”, “bvaejalley”, “vacojamise”, “bvaljeng”, “vacoJenser”, “vacojobek”, “vacojohnsp2”, “bvarepjones”, “vacojosept”, “bvajschroader”, “bvakkardian”, “bvampkatz”, “vacoKeeleb”, “bvaKKennerly“, “vacoKeoghN”, “bvajkeselyak”, “bvamkilcoyn”, “bvaskim”, “vacoKingT10”, “bvarkipper”, “vacoKominB”, “bvakkovarovic”, “bvaskravitz”, “BVANKROES”, “bvaskrunic”, “vacoKuczyR”, “vacokutroa”, “vacolaffik”, “bvaMLane”, “bvaalech”, “bvadlee”, “vacoleej5”, “vacoleey1”, “vacolemoib”, “vacoLewisB”, “vacolillyg”, “bvaalindio”, “bvamluboch”, “bvamlunger”, “vacoLynchK4”, “bvamdlyon”, “bvajlyons”, “bvaamacdonald”, “bvaamacdonald”, “bvaamaddox”, “bvaamainelli”, “vacomamisr”, “vacomarsha”, “bvammartin”, “vacomartic9”, “vacomaysp”, “vacomcdon4”, “vacomcdufk”, “bvacmcentee”, “bvammcphaull”, “vacomedins”, “bvaamichel”, “vacomillee”, “bvammiller”, “bvammills”, “vacominee”, “bvaSMisha”, “bvajmoats”, “vacomonrot”, “bvammoore”, “vacomorras”, “vacomorras1”, “vacomounts”, “bvabmuetzel”, “bvabmullins”, “bvacmurray”, “bvajmurray”, “bvasnajarian”, “vaconarduv”, “vaconelsoj”, “vaconelsol3”, “bvaanolley”, “BVAMNYE”, “bvajoconnell”, “vacoODonnC”, “vacooconnm”, “bvaaweis”, “bvajolsen”, “bvajolsen”, “bvapolson”, “vacoOngG”, “bvacorie”, “VACOOsborM”, “bvakosegueda”, “vacopalaca”, “bvamapappas”, “bvalpelican”, “bvaspflugner”, “bvajporter”, “bvampostek”, “bvarpoulson”, “bvaurpowell”, “bvawpreston”, “vacoPriceA”, “vacoprinss”, “bvaapurcell”, “vacorafteg”, “vacoRasoon”, “bvaeredman”, “bvasreed”, “vacoReidJ”, “bvadremcar”, “VACOReynoT”, “bvabrideout”, “vacoriordb”, “bvaNRippel”, “bvaarock”, “BVAPRUBIN”, “vacosahraz”, “bvajsaikh”, “vacosalazm”, “bvatsamad”, “vacosamia”, “vacoscardr”, “bvakschaefer”, “bvaRScharnb”, “bvadschecht”, “vacoschics”, “bvaschinnerer”, “bvamschlick”, “bvahschartz”, “bvaascire”, “bvajseay”, “vacosetteJ”, “vacoShannG”, “vacoShannT”, “bvaashawkey”, “bvassiesser”, “vacosilverl”, “vacoSimm”, “bvadwsingle”, “bvaeskiouris”, “bvacaskow”, “vacosmitha5”, “bvatasmith”, “bvanmcelwain”, “bvaasolomon”, “bvaaspector”, “vacoSpigeA”, “bvakspragins”, “bvajspringer”, “vacostephp”, “vacosteven”, “VacoStromG”, “bvamsuffole”, “vacosuhg”, “bvaasyed”, “vacotalamT”, “bvaphogan”, “bvaetamlyn”, “bvajtang”, “vacoTayloC”, “vacoTayloY”, “vacotimbem”, “vacotissej”, “vacotrickj”, “vacotrottr”, “bvactsessing”, “bvajtunis”, “bvaaturnip”, “vacoUmoi”, “bvajunger”, “bvaavanvalk”, “bvadcamilleri”, “vacovangs”, “BVARVELDENZ”, “bvapveresink”, “ bvagwadding”, “vacoWadeJ”, “bvahwalker”, “vacowalkek3”, “bvamwalker”, “vacowalkew ”, “vacowared”, “vacowarrei”, “bvagwasik  ”, “BVARWATKINS”, “bvasboehm”, “bvacwendell”, “bvacwendell”, “vacowetmow”, “vacowhitan”, “VACOWhiteY”, “bvadwhitehd”, “vacowhitlj”, “BVADWIGHT”, “bvagfenice”, “bvajwilliams”, “vacoWilliL12”, “VACOWilliS4”, “bvatwillie”, “vacowillia”, “vacoWinbub”, “bvamwulff”, “vacoYacouM”, “bvawmyates”, “vacoyoffep”, “BVADWIGHT”, “BVALYANTZ”, “BVAMYUAN”, “vacowatsom3”, “bvatminot”, “Bvarstephens”

## Related Stories
**_PM Issue(s)_**
IP | Reader | Request Denied users removed - Throttle Release [#1597](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1597)

**_Engineering Stories_**
Create blacklist for phased rollout [#3395](https://github.com/department-of-veterans-affairs/caseflow/issues/3395)

**Comment by mdbenjam** [comment]
Deny list has been disabled for everyone.
