### ISSUE TITLE
Document View | Shows "page 2 of 1" for one page documents

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3634]
## Description of bug
When opening single-page documents, the bottom toolbar says "page 2 of 1." I was not able to find a test case with documents to test it on my own computer, it a user has reported it happens frequently with one page documents.

![image](https://user-images.githubusercontent.com/4042181/31676324-4032ac3c-b335-11e7-90bb-fee1b46bbfc5.png)

## Acceptance Criteria
- Verify that one-page documents display the page count as "Page 1 of 1" instead of "2 of 1" for all one-page documents.

**Comment by abbyraskinUSDS** [comment]
I can't reproduce it either. I'm not sure what could be causing this. I will reach out to some other users to see if they've noticed the same bug. I think we can deprioritize this over other fixes in the meantime.

**Comment by tejans24** [comment]
It could be their screen resolution or screen size? 

Sounds good! Thanks @abbyraskinUSDS

**Comment by mdbenjam** [comment]
Yeah I wonder if it happens when they have their monitor plugged in.

**Comment by abbyraskinUSDS** [comment]
I don't think this is worth fixing. Closing.

**Comment by mdbenjam** [comment]
We've also changed how we display this, so it's likely fixed.
