### ISSUE TITLE
Handle error cases on completion

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3636]
Handle generic 500's or VACOLS errors on Intake completion, from the "Finish processing" page. Add a generic error message.

**Comment by kierachell** [comment]
**PASSED**

lame AC gets lame validation:
<img width="1188" alt="screen shot 2017-10-24 at 9 19 28 am" src="https://user-images.githubusercontent.com/18075411/31945227-81915c20-b89c-11e7-8c21-b0191ef3afd5.png">
