### ISSUE TITLE
Upcoming Hearing Days | TB Master records don't have ROs and start at midnight

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3642]
# Description
We are not handling master TB records consistently. The ones with children are OK-ish, but without are missing ROs and start dates are set to midnight (+/- timezone)

## Reproduction Steps

**Scenario 1 -**

1. Go to Upcoming Hearing Days
1. Look at TB Master records without children
1. Look at TB master records with children
1. Be confused

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [X] Prod

## Screenshots
**_Scenario 1 - [Weird]_**
<img width="547" alt="screen shot 2017-10-17 at 3 01 07 pm" src="https://user-images.githubusercontent.com/18075411/31684055-a5b1600a-b34c-11e7-84bf-5b6a62dfe703.png">
<img width="880" alt="screen shot 2017-10-17 at 3 02 51 pm" src="https://user-images.githubusercontent.com/18075411/31684056-a5df3b74-b34c-11e7-9f94-956279d46e04.png">

# Related Issues
**_Support_**

**_Engineering_**

**Comment by laurjpeterson** [comment]
Questions:
- Do we want to show start time for travel board at all? 
- Do we want travel board to be in a the time zone that the RO is in? (this is different than the current default 
- What do we want to show when it is just a master record, meaning there are no hearings scheduled yet for that day (currently, this would show midnight)?

**Comment by lakohl** [comment]
@sharonwarner is this ticket still relevant?

**Comment by sharonwarner** [comment]
@lakohl Yes, any master record with no children will show up with a midnight EST start time and won't have an RO.

**Comment by lakohl** [comment]
@sharonwarner so... Travel Board hearing days would not show the RO when no Veterans have been scheduled but Video Hearings days with no Veterans scheduled would? Is there a way around this? 
-I'd like to show the RO for both scenarios, as we should know that info in advance. 
As for the start  time, I believe Travel Board start times for each day are predictable, but that seems less important to get exactly right without the Veterans scheduled than the RO.

**Comment by lakohl** [comment]
@sharonwarner we should check back in on this. I wonder if it make sense to have default start times for TB? I need to confirm the exact times, but it would be something like this:

| ---| ----|
|**Day** | **Time**|
|Monday| 12:30pm|
|Tuesday| 8:30am|
|Wednesday| 8:30am|
|Thursday| 8:30am|
Friday| 8:30am|

**Comment by lakohl** [comment]
Justin confirmed the start times are 8:30am and 12:30pm
