### ISSUE TITLE
Status API | VBMS is being nice and telling us when they're down

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3643]
### Sometimes VBMS goes down and causes code 418 errors
http://prometheus.ds.va.gov/grafana/dashboard/db/va-systems-error-rates?fullscreen&edit&tab=alert&panelId=2&orgId=1

### And then vets.gov get those errors:
https://dsva.slack.com/archives/C4LPZ4YG1/p1508255553000235

### But VBMS is nice enough to tell us that it's down:
https://dsva.slack.com/archives/C4LPZ4YG1/p1508255553000235

```
 <h1>VBMS is currently unavailable due to maintenance.<br/>We apologize for the inconvenience.<br /> <span>Please check back soon.</span> </h1> 
```

Prolly cause they're making tea

## So let's handle it gracefully

**Comment by marvokdolor-gov** [comment]
Overtaken by events. Closing.
