### ISSUE TITLE
Reader | NoMethodError

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3652]
MethodError: undefined method `map` for nil:NilClass

Line 331: `appeal.issues = assignment_issues_hash_array.map { |issue_hash| Issue.load_from_vacols(issue_hash) }`

Environment: Prod
Found: Windows 7 | Chrome 61.0

Sentry Error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/516/

**Comment by dannysellers** [comment]
I think this is addressed by #3670

**Comment by mdbenjam** [comment]
I think this is fixed by #3670. Closing.
