### ISSUE TITLE
Search | Count number search terms on each page

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3653]
See the tech spec here: https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/reader/searching.md

Blocked on: https://github.com/department-of-veterans-affairs/caseflow/issues/3644

After using redux-search to get a list of pages with the search term, we can easily count the number of hits on each page with the term. We need this value to give an accurate count of search results. We can also compute what number hit the first search term on a given page is. This will be an important value to use when navigating between search terms.

# AC validated by Dev
1) There should be a selector that given the document text, search term, and page numbers with hits returns an array with the index of the first hit on each page.

**Comment by kierachell** [comment]
**PASSED**

<img width="572" alt="screen shot 2017-10-26 at 5 42 19 pm" src="https://user-images.githubusercontent.com/18075411/32078746-1569526a-ba76-11e7-8362-53853a3ba4c4.png">
<img width="434" alt="screen shot 2017-10-26 at 5 41 18 pm" src="https://user-images.githubusercontent.com/18075411/32078745-155a94a0-ba76-11e7-9e46-17747cc803a0.png">
