### ISSUE TITLE
Intake | Clearing search bar doesn't work

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#3654]
On the [Begin Intake](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intake/pages/begin.jsx) page, there's no `onClearSearch` callback passed to the `<SearchBar/>`, so clicking the X button doesn't do anything.

**Comment by NickHeiner** [comment]
Thanks for noticing this!

**Comment by kierachell** [comment]
**PASSED**
![clear](https://user-images.githubusercontent.com/18075411/31920833-66672636-b839-11e7-9266-4ae47b684374.gif)
