### ISSUE TITLE
Hearing Prep | Daily Docket | Appellant/Veteran ID goes missing

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3656]
Heads up there might be a duplicate ticket out there for this issue, but I cannot seem to find it. 

**Currently:** When at the Daily Docket page, the Appellant/Veteran ID clickable text will not be visible for a random amount of time. 

**Expected:** The Appellant/Veteran ID should always be visible when applicable on the Daily Docket page. 

Found: Preprod/UAT
Browser: FF and Chrome 

**Steps to Reproduce:**
1. Access the Daily Docket page
2. Verify that there isn't a value under Appellant/Veteran ID (this happens randomly and no errors show up in console so I can't give anything more)

**Screenshots:**
<img width="1349" alt="screen shot 2017-10-18 at 10 47 02 am" src="https://user-images.githubusercontent.com/23038505/31725776-2f52a8ae-b3f3-11e7-8c99-f95f4a92222d.png">

**Comment by kierachell** [comment]
**PASSED**

It's back
