### ISSUE TITLE
Search | Highlight Results

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3658]
See the tech spec here: https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/reader/searching.md

Blocked on: https://github.com/department-of-veterans-affairs/caseflow/issues/3644

We want to add mark.js to highlight the search results on each page.

# AC
1) Ensure that search results are highlighted on every page.

**Comment by kierachell** [comment]
**PASSED**


<img width="432" alt="screen shot 2017-10-31 at 8 46 11 pm" src="https://user-images.githubusercontent.com/18075411/32255201-a6e64a2c-be7c-11e7-8e48-a613d7170d64.png">
<img width="436" alt="screen shot 2017-10-31 at 8 46 23 pm" src="https://user-images.githubusercontent.com/18075411/32255202-a6f194f4-be7c-11e7-874d-3d1aba0b9acc.png">
<img width="310" alt="screen shot 2017-10-31 at 8 46 25 pm" src="https://user-images.githubusercontent.com/18075411/32255203-a6ff158e-be7c-11e7-9f79-f414253d2140.png">
<img width="574" alt="screen shot 2017-10-31 at 8 46 40 pm" src="https://user-images.githubusercontent.com/18075411/32255204-a72d14fc-be7c-11e7-9925-6805b7f4091c.png">
<img width="553" alt="screen shot 2017-10-31 at 8 46 43 pm" src="https://user-images.githubusercontent.com/18075411/32255205-a73939b2-be7c-11e7-9948-3609c0111874.png">



<img width="520" alt="screen shot 2017-10-31 at 8 45 56 pm" src="https://user-images.githubusercontent.com/18075411/32255200-a6d94c78-be7c-11e7-8088-e0802be3b27e.png">
