### ISSUE TITLE
Search | Navigate Results

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3659]
See the tech spec here: https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/reader/searching.md

Blocked on: #3644 & https://github.com/department-of-veterans-affairs/caseflow/issues/3658

We want to allow users to navigate between search results. As they hit enter or shift + enter they should move forward and backward through the results. The in focus result should be highlighted in a different color, and should be scrolled to.

# AC
1) Verify when a user searches for a term the first result is highlighted in the "current highlight" color.
1) Verify when a user hits enter in the search box, the next result is highlighted.
1) Verify when a user hits shift + enter in the search box, the previous result is highlighted.

**Comment by astewarttistatech** [comment]
blocked by #4036

**Comment by mdbenjam** [comment]
I don't think #4036 blocks this ticket. The file numbers in VACOLS are not correlating to actual veteran eFolders. I updated one of them to work. You should be able to go to /reader/appeal/2765748/documents to see it.

**Comment by kierachell** [comment]
**PASSED**

<img width="482" alt="screen shot 2017-12-03 at 5 49 54 pm" src="https://user-images.githubusercontent.com/18075411/33530759-7f0745fc-d852-11e7-9587-13a38c2e87a1.png">
<img width="739" alt="screen shot 2017-12-03 at 5 50 00 pm" src="https://user-images.githubusercontent.com/18075411/33530760-7f1b57f4-d852-11e7-9fc5-c1b46eb6a02e.png">
<img width="686" alt="screen shot 2017-12-03 at 5 50 05 pm" src="https://user-images.githubusercontent.com/18075411/33530761-7f72403c-d852-11e7-894e-e63137a4b417.png">
![searcb](https://user-images.githubusercontent.com/18075411/33530762-80107950-d852-11e7-92b1-556fa7d5a58f.gif)
