### ISSUE TITLE
What to do about vets with no BIRLS record?

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3660]
All veterans should have a BIRLS record, which is returned from BGS. But some don't :sad:

What should we do in this case? Efolder express uses the person endpoint which seems more reliable especially for basic data.

Needs some investigation

**Comment by laurjpeterson** [comment]
@leikkisa do you think we should keep this ticket open?

**Comment by pkarman** [comment]
In the case of #11175 we found it was inconsistent data in VACOLS, not a problem with BIRLS.

I think we should close barring specific cases to investigate.
