### ISSUE TITLE
Document view | Search UI and interaction 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3665]
## Story
As an attorney or judge, I want to be able to easy find and use a search interface that will help me easily find words within a document. 

## AC
- [x] Add a search icon on the far right of the toolbar, next to the download button
- [x] When a user either clicks the icon or enters Ctrl+F, a search bar should drop down
- [x] Verify that both ctrl + g and enter goes through highlights of the search results
- [x] Search bar should be 440 px width and 60 px in height in color `$color-gray-dark`and have 6 px radius rounded corners at the bottom
   - [x] The search bar inside should be in the [styleguide search ahead](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#search) style, 332px in width
   - [x]  There should be 2 new buttons next to the type ahead 
      - [x] `$color-primary` 
      - [x] 30px width 
      - [x] 6 px radius rounded corners 
      - [x] white carets (left and right). 
- [x] When text is entered, there should be a number x of y in `$color-gray` on the right

## Mockups
![image](https://user-images.githubusercontent.com/13420618/31924208-a485f1f4-b84d-11e7-801c-0c80d3c43bb5.png)
![image](https://user-images.githubusercontent.com/13420618/31924212-ac0af7da-b84d-11e7-9717-805378be66bd.png)
![image](https://user-images.githubusercontent.com/13420618/31924220-b467f19e-b84d-11e7-8ce7-23313dd87e2f.png)

**QA Notes:** Search is a FeatureToggle

**Comment by mdbenjam** [comment]
@gnakm - @dannysellers brought up a point about whether we should make cmd+(shift)g a hotkey and maybe not make enter a hotkey. See his question in this PR: https://github.com/department-of-veterans-affairs/caseflow/pull/3735.

**Comment by gnakm** [comment]
@mdbenjam I think that make sense. Let's go with that! I'll make a ticket to add it to the hotkey modal. @dannysellers thanks for the suggestion!

**Comment by gnakm** [comment]
@mdbenjam ^ Before I totally two thumbs up the suggestion above, both enter and ctrl + g will do the same job in most common browsers. The distinction is that ctrl/cmd + g works for both when browser AND search bar has focus. I don't know if it's worth the technical implementation but since those two hotkeys are pretty standard across all browsers, will creating out own search override those hotkeys or will they still work the same?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Reader
2. Open a Document with `search` FeatureToggle enabled
3. Click the magnifying glass
4. Enter a term 
5. Use ctrl + g and Enter key to move through the results. (actually moving through the page is a different ticket)

Screenshots: 
![readersearch](https://user-images.githubusercontent.com/23038505/32575028-e3120b10-c4a0-11e7-9f32-ed755b70909d.gif)
