### ISSUE TITLE
Finish processing | Checkbox state persists across pages

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3671]
# Description
When I check `Finish processing Supplemental Claim election` checkbox that I did all the steps and go back or forward; the checked state persists and doesn't force me to recheck that I did the steps according to my new selection

## Reproduction Steps

**Scenario 1 -**

1. Go to Intake
1. Find a Vet
1. Start processing RAMP
1. Check something on Review Request and enter date
1. Go to next page and check the completed steps box
1. Go back
1. Select something else
1. Go forward

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Check]_**
<img width="674" alt="screen shot 2017-10-19 at 8 13 39 am" src="https://user-images.githubusercontent.com/18075411/31770486-21f1a63e-b4a6-11e7-8dab-98f43dd1b706.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT

Steps to Validate: 
1. Access Intake
2. Find a Vet that has opt'd in for RAMP (can be queried in Rails console)
3. From the Review Request page select an election
4. Continue to Finish Processing page
5. Select the required checkbox
6. Select the back button 
7. Select the next button where you are taken back to the Finish Processing page
8. Verify that the checkbox is no longer checked. 

Screenshots: 
![intakestuff1](https://user-images.githubusercontent.com/23038505/31835174-91f65fe4-b59e-11e7-9b56-83e0d602254a.gif)
