### ISSUE TITLE
Review Request | Errors don't go away

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3674]
1. Submit the review request screen with errors
2. Submit it successfully.
3. Go back the Review Request screen, the errors from step 1 are still there, even though they shouldn't be

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Intake
2. Start Intake with a vet that has opt'd in for RAMP
3. On the Review Request page, create an error (wrong date)
4. Correct the error
5. Verify that the error message is gone upon navigating to the next page. 

Screenshots: 
![intakestuff2](https://user-images.githubusercontent.com/23038505/31835680-916170ee-b5a0-11e7-9253-740948a3acf5.gif)
