### ISSUE TITLE
Reader | Moving new annotation by keyboard always moves right

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#3679]
After creating a new annotation, the user can use the arrow keys to move the annotation around the document. Pressing any arrow key moves the annotation to the right

![out](https://user-images.githubusercontent.com/8533004/31786128-63472c9c-b4d5-11e7-9bf8-0d961d4353ce.gif)

**Comment by kierachell** [comment]
#### Well, apparently I can't move them using keyboard at all!

- create a new comment
- alt+enter to save it
- use arrows to try to move it
- see that you end up moving around documents/pages and not moving the comment
![arrows](https://user-images.githubusercontent.com/18075411/31948735-a7d33a62-b8a5-11e7-826c-6fa690d8163c.gif)

**Comment by dannysellers** [comment]
These keyboard shortcuts are only usable when initially positioning the annotation (before any text is actually added / before they're saved) ([ref](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/reader/PdfViewer.jsx#L80)). Afterwards, they can only be moved by mouse. The keyboard shortcut modal does seem to indicate otherwise, though...

We certainly could enable moving annotations by keyboard after creating them, though things might get confusing given that left and right arrows are already used to navigate between documents.

@mmlumba @gnakm @mdbenjam thoughts?

**Comment by kierachell** [comment]
- What would I be moving then?
![itshardtomovewhatyoucantsee](https://user-images.githubusercontent.com/18075411/31949880-581a62a4-b8a8-11e7-8a02-fbed00e88653.gif)

**Comment by dannysellers** [comment]
If you create an annotation (whether by clicking or by pressing `Alt+C`) and move the mouse over the document such that the annotation icon appears, you can then move it around using the arrow keys

**Comment by kierachell** [comment]
**PASSED**

Able to move when created via keyboard. Invisble icon issue captured here:https://github.com/department-of-veterans-affairs/caseflow/issues/3738
