### ISSUE TITLE
Switch to use PDF.js

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#368]
It's pretty great. Did some work throwing large PDFs at it (to put my machine under load) and it was fine. I'll test out a Windows machine next.

This would help us get rid of the #276 bug, and let us avoid moving parts as to which document reader is handling things (until that's done too)

Thoughts? I can send in a PR for this

**Comment by alex** [comment]
Please confirm it works on IE11.

On Thu, Dec 10, 2015 at 4:08 PM, <notifications@github.com> wrote:

> It's pretty great. Did some work throwing large PDFs at it (to put my
> machine under load) and it was fine. I'll test out a Windows machine next.
>
> This would help us get rid of the #276
> <https://github.com/department-of-veterans-affairs/caseflow/issues/276>
> bug, and let us avoid moving parts as to which document reader is handling
> things (until that's done too)
>
> Thoughts? I can send in a PR for this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/368>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by paultag** [comment]
@alex confirmed, stressed it, it worked, at least with the VA8 and the default PDF

**Comment by webinista** [comment]
[pdfjs Ruby gem](https://rubygems.org/gems/pdfjs)
