### ISSUE TITLE
Document list | Document description

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3686]
## Story 
As an attorney or judge, I want an "at-a-glance" description that will help me understand what a document in a folder is about. 

## AC
- [ ] Validate that the document description that gets saved from [document viewer side menu](https://github.com/department-of-veterans-affairs/caseflow/issues/3687) gets saved in document list page, under the appropriate document type link. 
- [ ] Validate that the text is 1.5 rem and in $color-gray

## Mockup 
![image](https://user-images.githubusercontent.com/13420618/31828170-8ac2e826-b587-11e7-8990-df8f1998a90e.png)

## Dependent Issue
https://github.com/department-of-veterans-affairs/caseflow/issues/3687

## Related
[Invision link](https://va-gov.invisionapp.com/share/ASD9BV6BE#/screens/254419666)

**Comment by dannysellers** [comment]
@gnakm At the moment, the row fields are centered vertically, not top-aligned. Should they be pegged to the top of the row?

![screen shot 2017-12-28 at 2 18 43 pm](https://user-images.githubusercontent.com/8533004/34420892-0cd5ef24-ebda-11e7-8f8d-ad724a373e7c.png)

**Comment by gnakm** [comment]
@dannysellers Top aligned please! It helps users read across the page more easily. 
![image](https://user-images.githubusercontent.com/13420618/34439876-2e67381e-ec7f-11e7-93f6-948918fb9039.png)

**Comment by dannysellers** [comment]
👍

**Comment by Sjones352** [comment]
**FAILED**
@dannysellers  and @gnakm 
Validate UAT/Chrome

 Text is not 1.5 rem but 1.7rem and  It is not in $color-gray but $color-gray-lighter

<img width="1133" alt="screen shot 2018-02-01 at 9 36 04 pm" src="https://user-images.githubusercontent.com/23080951/35714024-8c9597bc-0798-11e8-9e3f-b697c6d2dfeb.png">

<img width="1150" alt="screen shot 2018-02-01 at 9 35 16 pm" src="https://user-images.githubusercontent.com/23080951/35714036-9c218844-0798-11e8-95a0-88aa15e4c9bd.png">

This is $color-gray in style guide
<img width="151" alt="screen shot 2018-02-01 at 9 36 38 pm" src="https://user-images.githubusercontent.com/23080951/35714118-f7732f68-0798-11e8-95c9-338153dfcbb4.png">

**Comment by dannysellers** [comment]
@Sjones352 I think you're looking at the wrong field here. By default, documents don't have a description (not sure where the fake data lives for Documents, though it might be a good idea to update that), so to add one, open a document, expand the Document Information panel in the sidebar, and click Edit next to the field. After saving a description, you should see something like this in the claims folder view:

![screen shot 2018-02-05 at 8 39 32 am](https://user-images.githubusercontent.com/8533004/35807271-42810a98-0a50-11e8-9e7c-06c5d0c18c0f.png)

**Comment by gnakm** [comment]
It's been :shipit: ed
