### ISSUE TITLE
Post-Mortem | Minimum HealthyHostCount LessThanThreshold 1.0 for LoadBalancerName dsva-appeals-certification-prod

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3694]
Caseflow went down at 7:01 PM yesterday and I was alerted at 3:00 PM today. Here is a screenshot of the PD Alert. 

Slack wasn't notified in any of the channels. I only received a text alert. 

![147 minimum healthyhostcount lessthanthreshold 1 0 for loadbalancername dsva appeals certification prod pagerduty](https://user-images.githubusercontent.com/23038505/31841488-b2853672-b5b7-11e7-972b-25c6ab7f6b80.png)

@kierachell @lisac-usds @evankroske

**Comment by kierachell** [comment]
### Actions

- PD integration fixed
- Alert chalked up to ELB bug (occasionally loses connection)
