### ISSUE TITLE
Alert if a user navigates to a previous step mid-intake

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3695]
As a Claims Assistant, I want to know if I've navigated to a previous/irrelevant step in the middle of an intake; as a VSR, I want to check the status of previously completed intakes.

Scenario | Possible pages  where alert appears | Alert options |
--- | ----- | -----
I'm in the middle of an intake and I navigate to a previously canceled intake | review, finish, and confirm?| This intake was canceled; continue with current |
I'm in the middle of an intake and I navigate to the wrong page for the appeal i'm currently processing | search (disabled), review (disabled), finish (disabled) - depends on what you've completed, you can only go backwards? | Continue or cancel |
I'm in the middle of an intake and I navigate to a previously completed intake page |  review (disabled), finish (disabled), confirm | Continue or cancel |
I'm NOT in the middle of an intake, and I navigate to a previously completed intake page | review, finish, confirm | This is complete?
I'm NOT in the middle of an intake, and I navigate to a previously canceled intake page | review, finish, confirm | This was canceled
I'm NOT in the middle of an intake, and I navigate to an in-progress intake someone else is processing | 

## Acceptance Criteria
- Verify that if a user navigates to a different URL in the app while processing an intake that is not yet finished, they receive the alert shown below (design should follow styleguide).
- Selecting the "continue where you left off in Caseflow" link navigates the user to the page where they last left off on the current intake
- Selecting the "cancel processing" link triggers the cancel warning modal

## Copy
Title: Incomplete intake in progress
Body: You have already started processing [Vet Name] [(ID)]’s intake. Click here to continue where you left off in Caseflow. If necessary, you can also cancel processing this opt-in.

## Mocks
![image](https://user-images.githubusercontent.com/4042181/32023801-64525576-b9a8-11e7-9ca2-62930409a72a.png)

**Comment by abbyraskinUSDS** [comment]
Pasting your description here for posterity:

> Right now we use URLs for each of the states in Intake.
However, in most cases, you shouldn't actually be allowed go back to a previous state. So we have to add a lot of logic to make sure you are redirected to a safe place.
This brings up the question of whether we want URLs at all? Maybe steps should be combined?
Let's explore.

And repurposing this issue to create the warning alert that displays when users try to navigate to a page they shouldn't be on.

**Comment by laurjpeterson** [comment]
@leikkisa @pkarman do you think this ticket is still relevant?

**Comment by pkarman** [comment]
I haven't seen any errors related to navigation so far, so let's close. If we do in future, we can open new tickets.
