### ISSUE TITLE
load_user_case_assignments_from_vacols raises ActiveRecord::RecordNotUnique

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3699]
Sentry Error: https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/479/activity/

I think this line should just look up by vacols id since that's the unique constraint: https://github.com/department-of-veterans-affairs/caseflow/blob/issue3679/app/services/appeal_repository.rb#L323

# AC
1) The welcome gate should load even when one of the appeals listed already has an appeal record in the caseflow DB.

**Comment by kierachell** [comment]
**PASSED**

Didn't see it other than in Dispatch... but who cares about dispatch.
