### ISSUE TITLE
Welcome Gate | Documents still fetching after I am done viewing case

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3704]
# Description
When I am done viewing PDFs for a case and I go back to Welcome Gate,
some PDFs are still fetching. Granted I might want to go back to that case, but... do I need to keep downloading documents in the meantime?

## Reproduction Steps

**Scenario 1 -**

1. Go a document list
1. Click on some PDFs
1. Watch network tab load PDFs
1. Go back to Welcome Gate
1. Watch PDFs still downloading
1. for a while....

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Loading]_**
![stillfetching](https://user-images.githubusercontent.com/18075411/31889867-41daa938-b7cf-11e7-8588-22c6fb71b1b8.gif)

**Comment by mdbenjam** [comment]
Addressed in https://github.com/department-of-veterans-affairs/caseflow/pull/3951
