### ISSUE TITLE
Create v2 appeals API endpoint

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3708]
## AC

* I should be able to query `/api/v2/appeals`; the response should initially be identical to v1, except for the following attributes, which have been cut: `prior_decision_date`, `requested_hearing_type`, and `relationships` (hearings).
* Changes made to the v2 api should not affect v1, and vice versa.

**Comment by kierachell** [comment]
**PASSED**
-V1
<img width="608" alt="screen shot 2017-10-25 at 8 45 13 am" src="https://user-images.githubusercontent.com/18075411/31999335-e5b9d6fe-b960-11e7-8a04-e3c5235b2697.png">

-V2
<img width="526" alt="screen shot 2017-10-25 at 8 45 18 am" src="https://user-images.githubusercontent.com/18075411/31999337-e88485a0-b960-11e7-8ebb-3f0bc5bfb890.png">
