### ISSUE TITLE
Combined Appeal Streams

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3713]
## Story

As a user of Caseflow or as a Veteran using the Appeals Status API, I want to be able to see the full story of my appeal back to the original claim, including remands, motions for reconsideration, etc.

## AC
* A Veteran should have one or more combined appeal streams.
* Each combined appeal stream should have one or more child appeals. Every appeal should be included in one combined appeal stream, no appeal should be included more than once.
* Some combined appeal streams are incomplete, meaning they are known to be missing data (it could predate VACOLS, e.g.) or that it includes appeals that are not root, but for which the parent could not be found.
* The logic for combining appeal streams is as follows:

1. If `BRIEFF.BFAC` is `'1'`, this is a root. Other appeals may be descended from it, but it has no parent.
2. If `BRIEFF.BFKEY` ends in `'B'` or `'W'`, the parent can be found as the appeal that has the same `BFKEY`, without the trailing letter. If this appeal could not be found, we mark the appeal stream as incomplete.
3. If the `BFKEY` does not end with `'B'` or `'W'`, we will look to the prior decision date (`BRIEFF.BFDPDCN`).
4. If `BRIEFF.BFDPDCN` is null, we mark the appeal stream as incomplete.
5. If `BRIEFF.BFDDEC` <= `BRIEFF.BFDPDCN`, we mark the appeal stream as incomplete (in order to prevent loops).
6. We identify parent candidates where `BRIEFF.BFDDEC` equals the `BRIEFF.BFDPDCN` of the current appeal. If there is only one parent candidate, we select it. If there is no parent candidate, we mark the appeal stream as incomplete. If there are multiple parent candidates, we look to issues.
7. We create sets of issue categories present on each appeal (the combined values of `ISSUES.ISSPROG` and `ISSUES.ISSCODE`).
8. We create the set of categories present in more than one parent candidate set. If the current appeal's set intersects with this set, we mark the appeal stream as incomplete.
9. We match if current appeal's set intersects with exactly one parent candidate set.
10. Otherwise, we mark the appeal stream as incomplete.

* Once we've created these initial combined streams, we further combine those streams if they contain merged (`BRIEFF.BFDC = 'M'`) appeal streams, using the following logic. From the issues, select issues where `ISSUES.ISSDESC` includes the following text: `From appeal merged on [mm/dd/yy] ([bfkey])` where `[mm/dd/yy]` is the formatted `BRIEFF.BFDDEC`, and `[bfkey]` is the `BRIEFF.BFKEY`. If this joins to just one appeal stream (note it could appear in that stream multiple times), merge it in. If more than one, mark this appeal and all potential children as incomplete and do not join. If none, just mark this appeal stream as incomplete.
* _Doesn't appeal merging mean that what you're labeling a "root" is actually a "leaf"?_ Yes, yes, it probably does. Or you could just imagine some weird, intertwined trees. 

## Boy, Chris, that's a lot of logic, care to give me some test cases so I don't have to read through that all?
* For a given Veteran, every appeal should be included in exactly one combined appeal stream.
* All appeals in the combined appeal stream should belong to the same Veteran (`BRIEFF.BFCORLID` is the same for all appeals).
* If a combined appeal stream does not include an appeal where `BRIEFF.BFAC` is `'1'`, it should be marked as incomplete.
* If the `BRIEFF.BFKEY` of an appeal in the combined appeal stream ends in `'B'` or `'W'`, but there is no appeal with a `BFKEY` where that trailing character is dropped, the appeal stream should be marked as incomplete.
* If a Veteran has an appeal that 1) is a post-remand, 2) has a prior decision date, and 3) there are no other appeals owned by that Veteran with a decision date that is the matches this appeal's prior decision date, the appeal should belong to an incomplete appeal stream.
* If there are two appeals with the same decision date that contain the same issues (at least with the same `ISSPROG` and `ISSCODE`), a post-remand appeal that has that decision date as its prior decision date should belong to an incomplete appeal stream.

**Comment by cmgiven** [comment]
Some quick stats on this one, from the testing in R:

98% of all appeals known to have a parent will successfully match that parent.
<4% of all Veterans _with a post-remand appeal_ will have an incomplete combined appeal stream across their appeals. This is <0.6% of all Veterans with an appeal.

**Comment by kierachell** [comment]
@cmgiven 
- 💯 Amazing AC 🙏 
- This is a big one tho, so...
   - I will spin up a server that will be connected to a prod copy of VACOLS and prod copy of Caseflow DB and test this.
   - We can run through v2 API using Postman or something
   - I will probably have 3 million questions

**Comment by cmgiven** [comment]
There is a fairly significant bug here if the appeal is doesn't have a decision date (all of our fakes have decision dates by default). Fix coming soon.

**Comment by cmgiven** [comment]
Fix merged.

**Comment by kierachell** [comment]
Ok; I was going to ask about it after some monkeying around...

Retesting

**Comment by kierachell** [comment]
## Input validation - wrong error code:
<img width="499" alt="screen shot 2017-12-03 at 2 51 40 pm" src="https://user-images.githubusercontent.com/18075411/33529086-84f86716-d839-11e7-9ec3-7862337d6213.png">

**Comment by cmgiven** [comment]
The SSN issue affects both v1 and v2 APIs. Opened a separate issue as #4046.

On first glance, it doesn't look like there's anything wrong with that appeal, it's just an extreme edge case. It combines a total of thirteen individual appeals, and received its first Board decision way back in 2001.

Will want to dig into performance, though. The reason to write in Rails was to try to avoid creating another thing that's some gnarly SQL that only I understand and everyone else on the team views as radioactive waste (I think my issue descriptions query is part of the reason that the Issue model is in such dire need of refactoring). I thought it was workable in ActiveRecord, but if we're timing out, there's clearly something going on there.

**Comment by kierachell** [comment]
@cmgiven I have a pretty good flow set up now in UAT if you want to run through some of these (with a prod VACOLS copy) together this week.
