### ISSUE TITLE
v2 appeals API should use combined appeal stream

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3714]
Dependent on #3713.

## AC
* The "appeals" returned by the v2 appeals API correspond to combined appeal streams, not individual appeals.
* They should include all events from the child appeals, uniqued by type and date.
* If any appeal is active, the combined appeal stream should be marked as active.
* The type of the appeal should be the type of the active appeal. If there are more than one active appeal in the appeal stream (unlikely), the type should be the from the appeal most recently moved (`BRIEFF.BFDLOOUT`)
* If the combined appeal stream is marked as incomplete, the response should include an `incompleteHistory` attribute set to `true`.

**Comment by kierachell** [comment]
**PASSED**

Yeah it does, individual bugs will be captured in other issues:
<img width="400" alt="screen shot 2017-12-03 at 4 19 45 pm" src="https://user-images.githubusercontent.com/18075411/33529964-257b18c6-d846-11e7-8e59-6385e2e76be4.png">
<img width="333" alt="screen shot 2017-12-03 at 4 21 46 pm" src="https://user-images.githubusercontent.com/18075411/33529965-258b199c-d846-11e7-89e0-48f1a9473bee.png">
