### ISSUE TITLE
Record docket snapshots

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3715]
## AC

* There should be a new job to record a DocketSnapshot of the docket. Snapshots should be taken daily.
* A DocketSnapshot should have the date it was recorded, the number of non-AOD, non-post-CAVC appeals on the docket at that time, and the latest docket month being decided (docket month should only update on Fridays, however).
* In addition, a DocketSnapshot should have many DocketTracers, each of which records for a given docket month how many appeals were ahead on the docket at the time the snapshot was recorded and how many of those appeals were ready for a decision.

**Comment by amprokop** [comment]
A few questions for my learning.

> A DocketSnapshot should have the date it was recorded, the number of non-AOD, non-post-CAVC appeals on the docket at that time, and the latest docket month being decided (docket month should only update on Fridays, however).

Why should we include only non-AOD, non-post-CAVC appeals?

What do we mean by "ahead on the docket"?

> how many of those appeals were ready for a decision.

What does this mean, "ready for a decision"?

**Comment by amprokop** [comment]
Judging by
```
select extract(year from BFD19) YEAR, extract(month from BFD19) MONTH, count(*) 
count(case when BFMPRO = 'ACT' and (BFCURLOC = '81' or SATTYID is not null) then 1 end) READY_N
```
Does "ahead on the docket" refer to any appeal with a Form 9 date before or equal to the current docket month/year?

"Ahead on the docket and ready for a decision" appears to signify that the appeal is activated and either at location 81 (case storage?) or assigned to an attorney.

**Comment by cmgiven** [comment]
Because AOD and CAVC cases jump the line, we set them aside so that we have a line that just includes the non-prioritized cases. This allows us to show a consistent number that always decreases over time.

Yup, ahead on docket can also be read as "the number of appeals that are ahead of you."

And yes, ready for a decision means the appeal either has already been picked up by a judge or attorney or is sitting in central case storage, presumably ready to be picked up once it is in docket range.

**Comment by amprokop** [comment]
👍

**Comment by astewarttistatech** [comment]
@cmgiven Where would these DocketSnapshots be located?

**Comment by cmgiven** [comment]
The `docket_snapshots` and `docket_tracers` tables.
