### ISSUE TITLE
v2 appeals API should include a docket object

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3716]
Dependent on #3715.

## AC
* An appeal should have a docket object with the following attributes: `front` (boolean, whether the appeal is at the front of the docket), `total` (int, the total number of appeals on the docket), `ahead` (int, the number of appeals ahead of you on the docket), `ready` (int, the number of appeals ahead of you that are ready for a decision), and `eta` (date, a prediction of what month your appeal will reach the front of the docket).
* `eta` is stubbed and will always be null.

**Comment by Sjones352** [comment]
**PASSED**
<img width="988" alt="screen shot 2018-01-30 at 11 00 00 am" src="https://user-images.githubusercontent.com/23080951/35576963-643892e2-05ae-11e8-8e35-6ac3fe3272cf.png">
