### ISSUE TITLE
v2 api uses issue dispositions for field grants

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3717]
## AC

* In addition to using appeal-level disposition (`BRIEF.BFDC` and `BRIEF.BFDDEC`) for the `field_grant` event, we should also use the issue dispositions (`ISSUES.ISSDC` and `ISSUES.ISSDCLS`). The disposition codes for field grants are `'A'` and `'B'`. These events should be uniqued by type and date (there shouldn't ever be multiple events of the same type on the same day).
* This event should not be returned by the v1 API.

**Comment by kierachell** [comment]
<img width="385" alt="screen shot 2017-12-03 at 3 48 25 pm" src="https://user-images.githubusercontent.com/18075411/33529693-776df27e-d842-11e7-8691-2e1316717257.png">
<img width="326" alt="screen shot 2017-12-03 at 3 50 46 pm" src="https://user-images.githubusercontent.com/18075411/33529694-777f7aee-d842-11e7-90fe-54ec40b84b92.png">
<img width="410" alt="screen shot 2017-12-03 at 3 50 55 pm" src="https://user-images.githubusercontent.com/18075411/33529695-778ffd06-d842-11e7-8b0f-32b93b550bb5.png">


- So what status is this?: `713653`
<img width="307" alt="screen shot 2017-12-03 at 4 03 02 pm" src="https://user-images.githubusercontent.com/18075411/33529799-927b5a6a-d843-11e7-92af-0699b3075de2.png">

**Comment by cmgiven** [comment]
So this is not related to the status. There's also a `field_grant` status, which is set if a field grant resolves an appeal, but this is for the `field_grant` event. If I have a field grant for a single issue, so the rest of the appeal will carry on, I should have a `field_grant` event with the date that issue was field granted.

Does that clarify?

**Comment by kierachell** [comment]
** PASSED**


I think so

<img width="337" alt="screen shot 2017-12-03 at 4 55 53 pm" src="https://user-images.githubusercontent.com/18075411/33530245-f4704dbe-d84a-11e7-99e9-a73bde5b8d87.png">
<img width="309" alt="screen shot 2017-12-03 at 4 56 26 pm" src="https://user-images.githubusercontent.com/18075411/33530246-f484c028-d84a-11e7-83a7-31cb74b4d5c3.png">
