### ISSUE TITLE
Add claim decision event to v2 api

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3719]
## AC
* `BRIEFF.BFDRODEC` should be returned as a new event of type `claim_decision`. This event should be uniqued by date and type.
* This event should not be returned by the v1 API.

**Comment by kierachell** [comment]
**PASSED**
<img width="376" alt="screen shot 2017-12-03 at 3 18 27 pm" src="https://user-images.githubusercontent.com/18075411/33529307-52d29578-d83d-11e7-8f62-d83925339b94.png">
<img width="366" alt="screen shot 2017-12-03 at 3 18 55 pm" src="https://user-images.githubusercontent.com/18075411/33529308-53040a90-d83d-11e7-891d-902123f4a8dd.png">
<img width="335" alt="screen shot 2017-12-03 at 3 18 58 pm" src="https://user-images.githubusercontent.com/18075411/33529309-5314353c-d83d-11e7-8bd4-ed93023ac0d1.png">
