### ISSUE TITLE
v2 API returns ssoc event regardless of type action

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3720]
## AC
* The v1 API returns an `ssoc` or `remand_ssoc` depending on whether the SSOC's date is before or after the certification date. All v2 SSOCs should be typed `ssoc`.
* The v1 API should be unaffected

**Comment by kierachell** [comment]
**PASSED**
<img width="305" alt="screen shot 2017-12-03 at 3 20 50 pm" src="https://user-images.githubusercontent.com/18075411/33529336-a3279eb0-d83d-11e7-8fc8-273788e8a8b4.png">


- Should SSOCs be numbered?
<img width="351" alt="screen shot 2017-12-03 at 3 20 57 pm" src="https://user-images.githubusercontent.com/18075411/33529333-9d63f046-d83d-11e7-90b6-17670d7dabdf.png">


<img width="439" alt="screen shot 2017-12-03 at 3 06 37 pm" src="https://user-images.githubusercontent.com/18075411/33529217-a6e59662-d83b-11e7-8e7d-e88d0115b2c5.png">
