### ISSUE TITLE
v2 API updates disposition events

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3721]
## AC
* The v1 API disambiguates Board decisions into final and remands. All v2 decisions events (including dispositions such as `'1'`, `'3'`, and `'4'`) should be returned as `bva_decision`.
* The v1 API returns `other` events for the dispositions `'D'` and `'R'`. These should instead return `'record_designation'` and `'reconsideration'`, respectively.
* `'G'` and `'X'` should return `ftr`.
* `'P'` should return `ramp`.
* `'8'` and `'E'` should return `death`.
* `'5'` should return `vacated`.
* `'6'` should return `other_close`.
* The v1 API should be unaffected.

**Comment by kierachell** [comment]
**PASSED**
<img width="289" alt="screen shot 2017-12-03 at 5 14 17 pm" src="https://user-images.githubusercontent.com/18075411/33530458-adb93c70-d84d-11e7-8c22-abe5a313616c.png">
<img width="420" alt="screen shot 2017-12-03 at 5 14 31 pm" src="https://user-images.githubusercontent.com/18075411/33530459-adcd602e-d84d-11e7-9813-2f9138a7ca36.png">
<img width="381" alt="screen shot 2017-12-03 at 5 14 41 pm" src="https://user-images.githubusercontent.com/18075411/33530460-adf0c01e-d84d-11e7-8d46-87c8ffe8d6eb.png">
<img width="364" alt="screen shot 2017-12-03 at 5 15 56 pm" src="https://user-images.githubusercontent.com/18075411/33530461-ae23c662-d84d-11e7-94cd-97790e848d56.png">
<img width="314" alt="screen shot 2017-12-03 at 5 16 00 pm" src="https://user-images.githubusercontent.com/18075411/33530462-ae37f2cc-d84d-11e7-98d3-c60763ef9fa9.png">
