### ISSUE TITLE
[Frontend] Hearing Worksheet | Normalize redux state

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3728]
Dev AC:

- [ ] worksheetIssues is set at the first Redux level
- [ ] worksheetAppeals is set at the first Redux level
- [ ] appeals_ready_for_hearing is removed from worksheet
- [ ] Old functionality works as expected (adding, deleting, editing issues, multiple appeals stream display)

For QAs:
- [ ] Confirm adding, deleting, and editing issues works as expected
- [ ] Confirm multiple appeals streams are still displayed as expected

**Comment by kierachell** [comment]
**PASSED**
![issues](https://user-images.githubusercontent.com/18075411/32073228-57e80f18-ba63-11e7-9c88-ee2d416e589b.gif)
<img width="501" alt="screen shot 2017-10-26 at 3 35 08 pm" src="https://user-images.githubusercontent.com/18075411/32073229-57f61d10-ba63-11e7-8f46-01abc0ffd1ab.png">
<img width="659" alt="screen shot 2017-10-26 at 3 35 23 pm" src="https://user-images.githubusercontent.com/18075411/32073230-5809c446-ba63-11e7-8a7e-b41126d6da7b.png">
