### ISSUE TITLE
Add aod attribute to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3730]
## AC
* If the appeal is AOD, set the `aod` attribute to `true`, otherwise `false`.
* This should not affect the v1 API.

**Comment by kierachell** [comment]
**PASSED**
- checked with null/Y/N/G:

<img width="403" alt="screen shot 2017-12-03 at 3 21 54 pm" src="https://user-images.githubusercontent.com/18075411/33529395-70f3393a-d83e-11e7-9608-b6780fad7149.png">
<img width="282" alt="screen shot 2017-12-03 at 3 25 41 pm" src="https://user-images.githubusercontent.com/18075411/33529396-71081b8e-d83e-11e7-9545-1cadd081d8df.png">
<img width="325" alt="screen shot 2017-12-03 at 3 26 17 pm" src="https://user-images.githubusercontent.com/18075411/33529397-711aedcc-d83e-11e7-86d3-024db560ab44.png">
<img width="394" alt="screen shot 2017-12-03 at 3 26 20 pm" src="https://user-images.githubusercontent.com/18075411/33529398-712db2fe-d83e-11e7-8155-3af3d13ec5b0.png">
<img width="340" alt="screen shot 2017-12-03 at 3 26 47 pm" src="https://user-images.githubusercontent.com/18075411/33529399-713dba46-d83e-11e7-81ef-536cf520bf79.png">
