### ISSUE TITLE
Add location attribute to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3731]
## AC
* If `BRIEFF.BFMPRO` is `'ADV'` or `'REM'`, the `location` attribute should be `'aoj'`. If anything else, the `location` should be `'bva'`.
* This should not affect the v1 API.

**Comment by kierachell** [comment]
<img width="418" alt="screen shot 2017-12-03 at 3 36 34 pm" src="https://user-images.githubusercontent.com/18075411/33529511-dfcf9c94-d83f-11e7-897a-894932a3b3eb.png">
<img width="338" alt="screen shot 2017-12-03 at 3 36 39 pm" src="https://user-images.githubusercontent.com/18075411/33529512-e00b1c24-d83f-11e7-8b5d-3a53e032bcd1.png">
<img width="315" alt="screen shot 2017-12-03 at 3 36 42 pm" src="https://user-images.githubusercontent.com/18075411/33529513-e01ce5f8-d83f-11e7-8188-9cb7ce2f3600.png">


- What about `ADV` ?
<img width="379" alt="screen shot 2017-12-03 at 3 36 49 pm" src="https://user-images.githubusercontent.com/18075411/33529514-e02d3ec6-d83f-11e7-8942-18ed49c51b47.png">
<img width="375" alt="screen shot 2017-12-03 at 3 37 16 pm" src="https://user-images.githubusercontent.com/18075411/33529515-e0489874-d83f-11e7-8951-94eecb0e65f2.png">

- Should it be `aoj`?
<img width="298" alt="screen shot 2017-12-03 at 3 43 07 pm" src="https://user-images.githubusercontent.com/18075411/33529576-b50cd304-d840-11e7-9bd0-d8edd225d384.png">

**Comment by cmgiven** [comment]
Shoot. There was a typo in the AC. It should be `ADV` or `REM`. Edited, back to you.

**Comment by cmgiven** [comment]
@kierachell: Is there a reason you moved this one back? The AC has been updated.

**Comment by kierachell** [comment]
Possibly because Github hates me and deleted my comment. now I need to re-discover it.

**Comment by kierachell** [comment]
**PASSED**
