### ISSUE TITLE
Document Viewer | Make toolbars responsive

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3736]
## Story
As a user, I want Reader to be usable in different screen sizes (desktop) so that all features are clear and easy to find and use. 

Several times, I have seen a lot of the buttons on the top tool bar getting pushed to a second line because many attorneys uses different size desktops and minimize their browser in different widths so that they can use it side by side with a word doc (decision/ note taking purposes). FWIW, nobody has ever complained about it. 

## AC
- [ ] Top toolbar should be responsive so that buttons on top tool bar do not get pushed to a second line. 
- [ ] Width less than 800px, the words Zoom (top toolbar) and Previous and Next (bottom tool bar) should disappear. Document type should stay as is.
- [ ] Change the back link text to just back (for all screen sizes)

## Mockup

![image](https://user-images.githubusercontent.com/13420618/31923408-4fc8a440-b848-11e7-87ba-e17c05e28dd1.png)

![image](https://user-images.githubusercontent.com/13420618/37720659-20fe00ee-2cfe-11e8-8b7c-36bb8ab0ab33.png)

**Comment by nolawi** [comment]
@gnakm if sidebar is hidden the width of the toolbar will always be above 800px hence, the 'words' should be visible. right? We are basing this on the width of the document viewer and not the browser. LMK

**Comment by gnakm** [comment]
@nolawi yeah that makes sense
