### ISSUE TITLE
Double Sentry alerts fire when Reader can't fetch documents from the eFolder API 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3747]
In efolder_service.rb, we throw `Caseflow::Error::DocumentRetrievalError` when the eFolder API returns an error. This results in double Sentry alerts. For example:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/482/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/520/

To confirm, correlate the appeal id in the reader URL with the eFolder file number found in the body of the request using `Appeal.find_or_create_by_vacols_id`.

These double alerts create extra noise in the alerts channel. Potentially, we should log these errors but not trigger a Sentry alert from Reader, only from eFolder. The easiest way to do this would be to remove this line: `fail Caseflow::Error::DocumentRetrievalError if response.error?`, but Whiskey should determine what to do.

## AC
- StaleObjectErrors and other eFolder errors do not result in Sentry alerts from both Reader and eFolder

**Comment by nickheiner-usds** [comment]
Thanks for the detailed and clear writeup!

**Comment by kierachell** [comment]
Will be validated by not happening today

**Comment by kierachell** [comment]
**PASSED**

Noting today! SILENCE AT LAST! THANK YOU SO MUCH!

🎆
