### ISSUE TITLE
Log all ineligible RAMP opt-ins 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3750]
AMO would like to track the outcome of all claims that have been mailed opt-in notices. Specifically, they want to know whether any Veterans who were mailed opt-in letters were no longer eligible for RAMP at the time of intake.

Currently, while we handle this scenario on the front-end, we aren't capturing this metric in our database.

## Acceptance Criteria
- Verify that any time an Intake user searches for an appeal that is ineligible for RAMP (not C&P, activated at Board, or remand returned to Board), we store this event in Caseflow.

**Comment by astewarttistatech** [comment]
@abbyraskinUSDS So is this in ActiveRecord? If so, which table? Can you add it to the AC for reference?

**Comment by shanear** [comment]
sorry about that, it's an implementation detail. It will be in the `intakes` table under `error_code`

**Comment by kierachell** [comment]
- What type of errors? what are all expected values? what are not expected values?
```
#<Intake id: 17, detail_id: nil, detail_type: nil, user_id: 107, veteran_file_number: "889343355", started_at: "2017-11-02 12:03:16", completed_at: "2017-11-02 12:03:16", completion_status: "error", error_code: "no_active_appeals">
```

**Comment by shanear** [comment]
The values are sensible keys representing the type of error.

"did_not_receive_ramp_election"
"ramp_election_already_complete"
"no_eligible_appeals"
"no_active_appeals"

**Comment by kierachell** [comment]
**PASSED**
- you forgot to mention vet not found 😄 

```
[nil, nil, "no_active_appeals", "no_eligible_appeals", "ramp_election_already_complete", "no_eligible_appeals", nil, "invalid_file_number", "no_active_appeals", "no_eligible_appeals", "veteran_not_found", "veteran_not_found", "veteran_not_found", "veteran_not_found", "did_not_receive_ramp_election", nil, nil, "veteran_not_found", "ramp_election_already_complete", "did_not_receive_ramp_election", "invalid_file_number", "did_not_receive_ramp_election", "no_eligible_appeals", nil, "no_active_appeals", nil]
```
