### ISSUE TITLE
Add Google Analytics for Intake

### ISSUE THREAD

**Issue by nickheiner-usds** [department-of-veterans-affairs/caseflow#3759]
We would like to have app-specific Google Analytics for Intake:

## AC
1. View the "Appeals Not Prod" property in Google Analytics
    * This [segment](https://analytics.google.com/analytics/web/template?uid=Gfpy2lL0Snah1znXuyPqgQ) should isolate Intake traffic.
    * You may wish to wait a few days for events to show up.
1. See that event data is showing up
    1. In particular, see we log when a user triggers this validation error:
![image](https://user-images.githubusercontent.com/25331532/32065885-04c4685c-ba4c-11e7-9add-cd02e3b263f2.png)
1. See that HTTP request timing is showing up under "User Timings"
1. See that page navigation is showing up (eg views per page, user flow between pages, etc)
1. Validate that Reader event analytics are not broken.
    * Because Reader is already sending data to GA, I recommend validating this by ensuring that the XHR traffic looks the same from Reader before and after this PR.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT/GA

Browser: Chrome 

Steps to Validate: 
1. Access Intake in UAT and go through the regular flow
2. Navigate to Finish Processing page
3. Do not click the required checkbox
4. Open GA for Appeals not Prod and check the User Timings for API request and to see if the Event for Validation error appears. 

Screenshots: 
<img width="1351" alt="screen shot 2017-10-30 at 11 44 05 am" src="https://user-images.githubusercontent.com/23038505/32182527-4c9298ce-bd6d-11e7-804c-f52093568873.png">
<img width="1327" alt="screen shot 2017-10-30 at 11 46 35 am" src="https://user-images.githubusercontent.com/23038505/32182528-4c9dc3ca-bd6d-11e7-9630-337f491dc714.png">
<img width="1332" alt="screen shot 2017-10-30 at 11 46 47 am" src="https://user-images.githubusercontent.com/23038505/32182529-4ca84a02-bd6d-11e7-8c7f-377fff9777b7.png">
![pasted image at 2017_10_30 12_00 pm](https://user-images.githubusercontent.com/23038505/32182551-5fa7d3d4-bd6d-11e7-85c4-aa74ff04b1eb.png)
![pasted image at 2017_10_30 12_02 pm](https://user-images.githubusercontent.com/23038505/32182552-5fb56468-bd6d-11e7-96aa-158d03e6b8cf.png)
