### ISSUE TITLE
Reporting | Build an Intake stats page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3765]
We need to figure out what AMO and PA&I need in terms of reporting and dashboards.

### First-time election
- Number of opt-in notices mailed by month and to date
- Number of opt-in elections received by month and FYTD
- Percent opt-in elections received from mailings
- Number of elections into Supplemental Claim lane
- Number of elections into Higher-Level Review lane
- Number and percentage of eligible elections
- Number and percentage of ineligible elections disaggregated by reason for ineligibility
- Average days to respond to RAMP election notice

### Re-filing 
- Number and rate of re-file into RAMP lanes
- Number of SC re-filings
- Number of HLR re-filings
- Number of appeals
- Breakdown of appeal lanes 
- Average days to respond to a RAMP decision

## Other
- Number of notices returned undeliverable to ARC (may have to self-report to Caseflow and probably not dashboard worthy, but want to make sure we capture and maintain somewhere)

**Comment by abbyraskinUSDS** [comment]
@shanear is this still relevant?

**Comment by shanear** [comment]
It's deprioritized. We are supplying PGE with a database image. We will see how that plays out.

**Comment by abbyraskinUSDS** [comment]
Made some edits. Realistically, we'll probably want to break some of these out into separate tasks.

**Comment by abbyraskinUSDS** [comment]
Discussing requirements with AMO today.

**Comment by abbyraskinUSDS** [comment]
AMO has interest in our stats dashboard, but is discussing options internally and will let us know what they decide.

**Comment by shanear** [comment]
So I'm estimating 1-2 weeks for the reporting dashboard with potentially another 2-3 weeks for the CSV export functionality (which will run on top of the reporting dashboard and thus require it as a prerequisite).

>  Number of opt-in elections received by month and FYTD
How important is FYTD vs YTD in the real time dashboard? We aren't well positioned to do FYTD and since we'll only be operating RAMP for 1 full fiscal year and 2 partial fiscal years, it seems like it may not be worth the time investment.

**Comment by abbyraskinUSDS** [comment]
I believe they have to report on FYTD outcomes at the end of the fiscal year, but I think as long as there's a way for them to manually figure that out (by adding the months), it might be okay. Let's ask today.

**Comment by shanear** [comment]
Demo'ed today. Closing in favor of multiple follow up issues
