### ISSUE TITLE
Document viewer | Keyboard shortcut with search

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3774]
## Story
As a user, I want to know what the keyboard shortcut for searching within documents

## AC
- [ ] Change the ordering of keyboard shortcut subsections so that it is in this order:
  - Navigate Reader
  - Search within document
  - Add/edit comment 
- [ ] Add Scroll page up and Scroll page down as first two items under Navigate Reader
- [ ] Add the following under new section Search within documents
  - Open search box `ctrl` + `f`
  - Navigate search results `ctrl` + `g`

## Mockup
![image](https://user-images.githubusercontent.com/13420618/32121215-adf769dc-bb29-11e7-95cc-7c0f95eff8b8.png)

**Comment by gnakm** [comment]
@abbyraskinUSDS I changed the sequencing of the keyboard shortcut and added the new search stuff. Could you take a look to confirm?

**Comment by abbyraskinUSDS** [comment]
what does navigate search results do? that's how you move between results? I don't think PCs have command keys, it's a windows symbol.

**Comment by gnakm** [comment]
@abbyraskinUSDS yes, navigate search results means going through the highlighted results. @dannysellers said we should be able to program it so that the cmd in `ctrl` + `cmd` + `g` only shows for mac users, instead of just `ctrl` + `g` for PC users.

**Comment by abbyraskinUSDS** [comment]
okay, but i think all our users are on PCs.

**Comment by gnakm** [comment]
Yeah that was a bad call. Let's scratch cmd and go with showing `ctrl` + `g`. It's standard across most browsers anyway.

**Comment by abbyraskinUSDS** [comment]
Okay, it seems like enter should still work if there's focus, so I wonder if that's confusing.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome

Steps to Validate: 
1. Navigate to Reader
2. Select a document
3. In the right side menu, select shortcut keys modal at the bottom. 
4. Verify that all the shortcut keys are in proper order. 

Screenshots: 
<img width="1392" alt="screen shot 2017-11-13 at 10 19 40 am" src="https://user-images.githubusercontent.com/23038505/32733154-8bb9690c-c85c-11e7-99dc-7f9b6f5f3046.png">
<img width="1374" alt="screen shot 2017-11-13 at 10 19 53 am" src="https://user-images.githubusercontent.com/23038505/32733156-8bc35b60-c85c-11e7-86c9-c7476fe742fb.png">
<img width="1384" alt="screen shot 2017-11-13 at 10 20 06 am" src="https://user-images.githubusercontent.com/23038505/32733157-8bcd5160-c85c-11e7-8215-bb6d197e96d1.png">
