### ISSUE TITLE
Review Request | Split ineligible alerts, depending on reason

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3775]
AMO would like us to separate out the 2 main reasons a veteran's appeal may have become ineligible at the time of intake:
- Veteran's appeal was withdrawn or closed between time RAMP notice letter was mailed, and opt-in was received
- Veteran's appeals aren't in an eligible stage anymore (they're at the Board rather than VBA)

## Acceptance Criteria
- If the Veteran's appeal has been transferred to the Board between the notification date and date of receipt, the alert title should say "Ineligible to participate in RAMP: appeal is at the Board"
- If the Veteran's appeal is at the Board, the alert title should say: "Ineligible to participate in RAMP: no active appeal"
- The body copy is identical, and hasn't changed (see below)

#### No active appeals
![image](https://user-images.githubusercontent.com/4042181/32195550-f266ebc6-bd93-11e7-8242-0cdbef852784.png)

Title copy: Ineligible to participate in RAMP: no active appeals
Body copy: Please check the Veteran ID entered, and if the Veteran ID is correct, take the following actions outside Caseflow:  	
•  Upload the RAMP Election to the VBMS eFolder with Document Type Correspondence                    	    and Subject Line “RAMP Election.”
•  Notify the Veteran by mail of his/her ineligibility to participate in RAMP using the RAMP 	    Ineligible Letter in Letter Creator. 
•  Document your actions as a permanent note in VBMS.   

#### Appeal is activated/returned to Board
![image](https://user-images.githubusercontent.com/4042181/32195635-39a03ec0-bd94-11e7-8732-7f94841da243.png)

Title copy: Ineligible to participate in RAMP: appeal is at the Board
	•  Upload the RAMP Election to the VBMS eFolder with Document Type Correspondence                    	    and Subject Line “RAMP Election.”
	•  Notify the Veteran by mail of his/her ineligibility to participate in RAMP using the RAMP 	    Ineligible Letter in Letter Creator. 
	•  Document your actions as a permanent note in VBMS.

**Comment by kierachell** [comment]
**PASSED**
<img width="852" alt="screen shot 2017-11-02 at 8 48 02 pm" src="https://user-images.githubusercontent.com/18075411/32357033-80553a1e-c00f-11e7-8250-517b7227f537.png">
<img width="850" alt="screen shot 2017-11-02 at 8 48 52 pm" src="https://user-images.githubusercontent.com/18075411/32357034-8066aa2e-c00f-11e7-8275-e131afe5a9b7.png">
