### ISSUE TITLE
Override visited link color

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#378]
<img width="1088" alt="screen shot 2015-12-14 at 10 15 12 am" src="https://cloud.githubusercontent.com/assets/772/11784661/949d4b08-a24b-11e5-92ad-1ac707a707cf.png">

**Comment by webinista** [comment]
The current link colors inherit from the [U.S. Web Design Standards](https://playbook.cio.gov/designstandards/visual-style/#links) initial styles.

**Comment by KHarshawat** [comment]
@webinista since these are not content links but action links, I suggest we override and make them stay the same color (blue) even after they've been clicked.

**Comment by webinista** [comment]
Pushing back slightly here. I agree that _Cancel certification_ is an action link. But _Digital Service at the VA_ is IMO a content link. Do we want to make an exception here for the links in the footer? Or make them all blue all the time?

**Comment by KHarshawat** [comment]
Ah, great call. Sorry I didn't catch that @webinista 

- Action links such as `Cancel certification` should always be blue
- Sometimes these action links exist in the body of content (for example we used to have a link that said `refresh` on the mismatched page
- Any other link links (e.g. those in the footer) should continue to have the purple visited color
