### ISSUE TITLE
VVA | Investigate converting .tiffs to .pdfs

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3782]
There are a lot of .tiff files in VVA, which our users can't open in Reader without downloading them. We should convert TIFFs to PDFs in eFolder so that Reader can display them.

# AC
1) Verify when downloading a TIFF file from VVA that it is converted to a PDF first.

**Comment by kierachell** [comment]
### Some conversion and file saving errors:

- Download any of the VVA-testable IDs in UAT (like `999999999`)
https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/artem_junk_drawer/connect_vva_tests.rb#L33
- Why is `pdftk` complaining about these files
```
cannot write pdf of size 473761 via pdftk - update_info '/tmp/pdf-attributes20171114-2964-63gt7x' output '/opt/efolder-express/src/tmp/files/2206/00250-Appellate Brief (VSO IHP; Post remand
Brief; Attor-20140613-8C844EC1-7601-4A09-AF28-885A20B6CB25.pdf': Error: Unable to find file.
dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-076455877d100fccc-172.30.70.89 Error: Failed to open PDF file:
   -
dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-076455877d100fccc-172.30.70.89 Errors encountered.  No output created.
dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-076455877d100fccc-172.30.70.89 Done.  Input errors, so no output created.
```

- Should theyse end up in the `Errored` tab?
<img width="586" alt="screen shot 2017-11-14 at 3 23 58 pm" src="https://user-images.githubusercontent.com/18075411/32802943-e8798b24-c94f-11e7-9504-11149f6f9b4d.png">


- they end up all corrupted; even regular ones:
<img width="792" alt="screen shot 2017-11-14 at 3 24 52 pm" src="https://user-images.githubusercontent.com/18075411/32803116-8331f94e-c950-11e7-87d5-8377509ff6c2.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="430" alt="screen shot 2017-11-17 at 8 41 12 am" src="https://user-images.githubusercontent.com/18075411/32950384-202372f8-cb74-11e7-92d3-ddca56647fb0.png">
<img width="621" alt="screen shot 2017-11-17 at 8 48 09 am" src="https://user-images.githubusercontent.com/18075411/32950385-203d1a6e-cb74-11e7-85aa-df8a87ad8996.png">
<img width="486" alt="screen shot 2017-11-17 at 8 48 34 am" src="https://user-images.githubusercontent.com/18075411/32950386-204e412c-cb74-11e7-949d-51b375b8547d.png">

```
STARTED VVA: fetch document content for: {E172FBF4-5509-455D-B20E-A022A664DE2F}                                                                                                           dsva-appeals-efolder_worker-preprod/opt/efolder-express/src/log/efolder-express-worker.out i-0a09c9a566f000444-172.30.70.29 [ActiveJob] [DownloadFilesJob] [2b1dbfbe-74df-4302-8f5a-fa01ab8e1149] [2017-11-1
7 08:46:29 -0500] FINISHED VVA: fetch document content for: {E172FBF4-5509-455D-B20E-A022A664DE2F}:   0.030000   0.000000   0.030000 (  1.756360)                                                           dsva-appeals-efolder_worker-preprod/opt/efolder-express/src/log/efolder-express-worker.out i-0a09c9a566f000444-172.30.70.29 [ActiveJob] [DownloadFilesJob] [2b1dbfbe-74df-4302-8f5a-fa01ab8e1149] [2017-11-1
7 08:46:29 -0500] STARTED Image Magick: Convert tiff to pdf                                                                                                                                                 dsva-appeals-efolder_worker-preprod/opt/efolder-express/src/log/efolder-express-worker.out i-0a09c9a566f000444-172.30.70.29 convert: Unknown field with tag 33000 (0x80e8) encountered. `TIFFReadDirectory'
@ warning/tiff.c/TIFFWarnings/820.                                                                                                                                                                          dsva-appeals-efolder_worker-preprod/opt/efolder-express/src/log/efolder-express-worker.out i-0a09c9a566f000444-172.30.70.29 [ActiveJob] [DownloadFilesJob] [2b1dbfbe-74df-4302-8f5a-fa01ab8e1149] [2017-11-17 08:46:29 -0500] FINISHED Image Magick: Convert tiff to pdf:   0.000000   0.000000   0.690000 (  0.799778)
```
