### ISSUE TITLE
Hearing Worksheet: Veteran age does not show

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3783]
AC:
- Pull DOB from BGS
- Confirm age shows up on hearing worksheet for all veterans with DOB in BGS

**Comment by sharonwarner** [comment]
The veteran @annienguyenUSDS sent me had a blank DOB in VACOLS, so we can't calculate the age.

**Comment by annienguyenUSDS** [comment]
@aroltsch also had another Veteran during our interview yesterday to check.

**Comment by aroltsch** [comment]
I have a Hearing ID from prod DB => 2236 @sharonwarner

**Comment by annienguyenUSDS** [comment]
Following up on this: Is BGS more consistent with having birthdates? Worth looking into BGS as main data source or pulling info from BGS only when VACOLS cannot.

**Comment by kierachell** [comment]
### Confirm age shows up on hearing worksheet for all veterans

This will not happen. BGS doesn't always have full veteran's info.

**Comment by astewarttistatech** [comment]
Hey @annienguyenUSDS and @sharonwarner  I am not seeing any fields for a DOB in the DB that could possibly be filled 'nil' if a veteran doesn't have a DOB stored or any correlating UI on the Hearing Worksheet page that would show a DOB. Am I missing something?

**Comment by sharonwarner** [comment]
@astewarttistatech We pull the DOB and then use it to calculate the age on the hearing worksheet. We don't store it in the database. You can just confirm that the age shows up on the hearing worksheet.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: Chrome 

Steps to Validate: 
1. Access Hearings 
2. Navigate to the Hearing Worksheet of a Veteran who has a recorded DOB (can validate in VBMS)
3. Verify that on the Hearing Worksheet, that there is an age for the Veteran. 

Screenshot:
