### ISSUE TITLE
Hearing Worksheet: Change Issue 'Description to 'Notes'

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3784]
Under Issues, change the copy on the column header from 'Description' to 'Notes'.

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Hearings
2. Navigate to Hearings Worksheets
3. Validate that there are no more "Notes" but only "Description" 

Screenshots: 
![hearing worksheet](https://user-images.githubusercontent.com/23038505/32566920-9691d87e-c487-11e7-9706-02232392db23.png)
