### ISSUE TITLE
Hearing Prep - ways to improve performance 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#3787]
1. Upcoming dockets page - split `hearings/dockets.json` into two calls - `hearings/dockets.json` and `hearings/daily_docket.json`
2. Query issues using an array of appeal stream ids in one big query
3. Use efolder API to query document list. Include hearing prep users in a reader_user list so documents will be prefetched in a nightly job
4. Profile to figure out what's causing the slowness

**Comment by aroltsch** [comment]
1. Upcoming dockets page - split `hearings/dockets.json` into two calls - `hearings/dockets.json` and `hearings/daily_docket.sjon`
2. Worksheet page - when a call is made to the upcoming dockets page, start a background job to pre-fetch the worksheets for a judge.

**Comment by sharonwarner** [comment]
Duplicate ticket
