### ISSUE TITLE
Conduct Override feature interviews

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#379]
Interview 6-8 DROs and VSRs from Regional Offices to understand why they are using workarounds for Certification.

**Comment by shellicious** [comment]
Draft of interview questions:

Introduction (5 min)
- Talk through goals of the interview
- Warm-up question: how are you doing? What are you working on today? Walk me through your day.

Types of cases (15 min)
- Tell me about the last case you worked on
- What other types of cases are there?
- What types of cases are difficult to certify with Caseflow?
 - What do you do if documents are missing?
 - What do you do with remanded cases?
 - What do you do if documents are mislabeled?

Use of Certification: (15 min)
If video call:
- Show me how you certified the last case, or a current case
- Show me how you certify the most common type of case 
- Show me what you do if you don’t think Certification is suited for the case

If not video call:
- Talk me through how you certified a recent case in the tool
- Talk me through your workflow for the most common type of case
- Talk me through what you do when a case isn’t suitable for Certification

Follow-up (5 min)
- How satisfied are you with Caseflow?
- What changes would you like to see in Caseflow?

**Comment by abbyraskin** [comment]
It sounds like a few specific questions came out of the Oakland RO visit. Let's probe on these if they don't come up naturally as they walk us through today's certification process:
- After certifying an appeal, do you dispatch the case? (if so, walk us through what you're doing in VACOLS or elsewhere.)
- Why do you dispatch certified appeals? What happens after you dispatch an appeal? (is it to notify the veteran/vet's rep? who physically notifies the vet/rep?)

**Comment by shellicious** [comment]
Sounds good!

**Comment by shellicious** [comment]
Completed! Thanks @abbyraskin @Chingujo @nikitarockz for being part of this!
