### ISSUE TITLE
Change "review request" to "review election"

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3791]
We should change the "Review request" section in the progress bar to say "Review election" to better align with the name of the form and step in the process. We should also update the copy on the Review request/election page title.

## Acceptance Criteria
- Change the progress bar step "Review Request" to "Review Election"
- Change all instances of opt-in request to opt-in election.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browser: Chrome

Steps to Validate: 
1. Access Intake 
2. Verify that the "opt-in request" has been changed to "opt-in election"
3. Navigate to the Review Election page, verify that the heading is that. 

Screenshots: 
<img width="1344" alt="screen shot 2017-11-15 at 1 26 08 pm" src="https://user-images.githubusercontent.com/23038505/32855252-257ae03a-ca0f-11e7-99f9-ab1d50920719.png">
<img width="1194" alt="screen shot 2017-11-15 at 2 14 02 pm" src="https://user-images.githubusercontent.com/23038505/32855284-41da8db6-ca0f-11e7-92e2-2fba1015c8ed.png">
