### ISSUE TITLE
Feature Flag | Enable Group 1 – ARC users on 11/2/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3811]
As Project Manager, I would like the following feature flag enabled on Thurs., 11/2/2017 at 8 am (as early as possible) for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  Mail Intake (initial release)

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

“AMCJVIDR”, “AMCBFOX”, “AMCMMASO”, “AMCBBURN”, “AMCDCROS”, “AMCDMASO”, “AMCKFARN”, “AMCCROSS”, “AMCKMILL”

## Related Stories
**_PM Issues_**
IP | Intake | Request Feature Flag enabled [#1587]( https://github.com/department-of-veterans-affairs/appeals-pm/issues/1587)

**Comment by nikitarockz** [comment]
@abbyraskinUSDS This story is ready for the engineering team to implement.

**Comment by abbyraskinUSDS** [comment]
@shanear we don't need a whitelist - let's just open it up to everyone who has the correct CSS role/function.

**Comment by nikitarockz** [comment]
@abbyraskinUSDS @shanear I would caution you against that allowing anyone with "Mail Intake" as their to have access.  I don't trust these people.  We don't control the person who is actually entering the information in CSEM, only for station 101-BVA.  We are currently doing a lot of clean up for eFolder.  I can promise you that we also need to clean up for Certification too.  If I remember correctly, Reader has some unknown users as well.  Until we can have a tighter reign on who has access, you can't assume that because their profile has "Mail Intake" they should be using it.  Remember we have a large number of people requesting access to  our other systems.  These people can make a mistake and select the function for "Mail Intake" just because.  There's 50 CSEM station users who are setting theses functions.  I am very concerned about security ramifications if we do this.

**Comment by shanear** [comment]
Feature toggle is enabled for all of ARC, `RO97`.
