### ISSUE TITLE
Catch JS errors associated with error responses

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3813]
Lots of the REST requests in intake let the error propagate out of the promise into JS errors. We should catch those

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Intake with Inspector in-browser. 
2. Go through the Intake (End-to-End)
3. Verify that there are no JS errors occurring in the console tab of Inspector

Screenshots: 
Licecap was too long.
<img width="1422" alt="screen shot 2018-01-05 at 11 11 26 am" src="https://user-images.githubusercontent.com/23038505/34617566-e1523af2-f209-11e7-8fca-4ecce771f5ac.png">
