### ISSUE TITLE
Reader: Open efolder in a new window instead of a new tab

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3814]
Judges need to go back and forth between the Hearing Worksheet and the Reader docs when they prep for  a hearing.
Open efolder in a new window instead of in a new tab.

**Comment by Sjones352** [comment]
Currently
![hearing](https://user-images.githubusercontent.com/23080951/33862515-22221eba-deb1-11e7-941b-e7367546c351.gif)

**Comment by lakohl** [comment]
@Sjones352 I might be hard to see in the .gif, but it looks like Reader/efolder is opening in a new tab, and then the Reader document is opening in another tab. 

What we are looking for is to have Reader/the efolder open in a separate window from the Hearign Worksheet.

**Comment by Sjones352** [comment]
@lakohl thanks for the explanation. let me fix that now.

**Comment by Sjones352** [comment]
@sharonwarner and @lakohl after further investigation  I suspect websites can't force a user to open a new window (most browsers include an option to open new links in a tab vs a window), cause that's how popups work so this might be a little tricky. We might have to train our users on how to open the links in a different from their computers. Please read https://stackoverflow.com/questions/4964130/target-blank-vs-target-new/4964223#4964223

**Comment by Sjones352** [comment]
@lakohl check this out
![hearingsworksheet](https://user-images.githubusercontent.com/4773320/33950241-ed44e872-dff9-11e7-9ed5-0b29ed530d55.gif)
