### ISSUE TITLE
Claims Search | Missing file message state updates as you type

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3815]
If you search for a case file that has no matches as you change the number in the search box without pressing enter, the message stays and updates the value.
![searchingclaimsfolder](https://user-images.githubusercontent.com/3885236/32290256-dc788022-bf0f-11e7-8c9e-9e2633669e1c.gif)

Steps to reproduce:
1) Go to the welcome page.
1) Type in an invalid claims file number into the search bar.
1) Search for the invalid number.
1) When the error appears, try to search for a different number.
1) Notice how the error also changes.

**AC**
- [ ] The error should not change even as you type in the search bar.

**Comment by oscarAtNava** [comment]
Fixed with PR [4583](https://github.com/department-of-veterans-affairs/caseflow/pull/4583)
