### ISSUE TITLE
Daily Docket: Bold Veteran ID

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3816]
Reader currently uses a DocumentViews object to track which users have viewed which documents. That information is then used in the UI - documents that have not been viewed are bold, documents that have been viewed are normal text. We need to create a similar process in hearings prep to mark which judges have viewed which hearing worksheets. 

**AC**
- Create an object (HearingsViews) that is foreign keyed to hearings and users
- When a judge clicks on a veteran's hearing worksheet from the daily docket, we create an entry in the HearingsViews table to designate that the judge has viewed that worksheet
- When displaying the daily docket, the links (the veteran's vbms id) to hearings that have entries in HearingsViews are displayed with regular text and the others are displayed with bold text.

**Comment by astewarttistatech** [comment]
Blocked until new Hearings are loaded.
