### ISSUE TITLE
Hearing Prep | Update Loading Error Message

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3819]
Update current Alert for when there's an error loading the page on Daily Docket and Hearing Worksheet from: 

<img width="1125" alt="screen shot 2017-11-01 at 1 40 09 pm" src="https://user-images.githubusercontent.com/22620270/32293429-7d333a6c-bf19-11e7-92be-c892ee7d08cb.png">

to be consistent with Reader and showing the "refresh the page" link for Judge to click on:
<img width="1001" alt="screen shot 2017-11-01 at 2 27 45 pm" src="https://user-images.githubusercontent.com/22620270/32293422-784f3ec4-bf19-11e7-906d-1ac158742202.png">

**Comment by astewarttistatech** [comment]
Looks good. 

**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearings 
2. Toggle network off while loading documents 
3. Verify that the error message given is a page alert and not the former banner. 

Screenshots: 
<img width="1399" alt="screen shot 2017-11-03 at 2 00 56 pm" src="https://user-images.githubusercontent.com/23038505/32389482-2010a840-c0a1-11e7-9842-4db7564e612d.png">
