### ISSUE TITLE
Up & Down Arrows: Add key listeners so we don't need focus

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3824]
Currently you need focus on the scroll window to navigate through the pdf. We should add key listeners for up, down, pageUp, and pageDown so that users don't have to be focused.

## AC
- Verify that pressing up or down, pageUp, and pageDown scroll the document as expected without needing focus on the page

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
