### ISSUE TITLE
Post Mortem | Remanded appeals weren't returned in appeals_ready_for_hearing

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3825]
# Summary

When pulling appeals for the hearing worksheet, we take the veteran's VBMS id and return all appeals ready for a hearing associated with that VBMS id. We defined ready for a hearing as having a form 9 and no decision date. 

Our pilot users started notifying support that for some hearings, no appeals were showing up on the hearing worksheet. This meant that they couldn't see any of the associated dates or issues and they couldn't add issues.

Anya and Sharon looked into one of the users hearings with no appeals and found the associated appeal had a decision date. They realized that remanded appeals have a decision date. Appeals ready for hearings can correctly be identified only by the decision date and the disposition code. Appeals with a remanded disposition code and a decision date are still ready for a hearing. 

Anya submitted a PR to correct the logic, and it was deployed the following business day.

# Root Causes

We incorrectly identified the logic for selecting appeals ready for hearings.

# Solutions

Pilot users preparing for hearings with remanded appeals used VBMS and VACOLS instead of Hearing Prep temporarily. A fix was deployed 2 business days after the bug was found.

# Open Questions

1. Could we have found this bug before launching?
1. Should we have deployed a temporary bug fix to allow pilot users to continue using Hearing Prep?

# Associated Tickets

#3664

**Comment by laurjpeterson** [comment]
- engineering, product, and design could sync about ticket AC before working on them. we can use story time for this.

**Comment by sharonwarner** [comment]
Action Items:

1. I will spend a few minutes going through each bug report that @kierachell files to determine how urgent it is.
