### ISSUE TITLE
Post Mortem | Start times were calculated based on appeal's RO

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3826]
# Summary

While observing hearings, Annie found that a pilot user was missing one hearing on her daily docket, so she didn't prepare for it. Sharon and Anya looked into it and found the missing hearing's date was incorrectly returning the day before. That particular hearing was scheduled by the RO in the Philippines, but took place in San Diego. The hearing was scheduled for 8:30 AM. In Philippines time, that would be 8:30 PM the day before in DC time, but in San Diego time, that would be 11:30 the correct day in DC time. Because we used the RO to calculate the time, we listed this hearing at 8:30 PM the day before.

Anya deployed a fix to use the hearing venue to calculate the start time if the hearing venue is not null. If the hearing venue is null, we still use the RO's time zone. 

# Root Causes

We incorrectly calculated hearing's start times based on the appeal's RO's time zone rather than the hearing venue. 

# Solution

We deployed a fix the day after the bug was discovered.

# Open Questions

1. Was the time zone feature rushed too much before the pilot launch?
1. Should we communicate with judges that they should check hearing prep's information with VACOLS and VBMS?
1. Is it safe to use the RO's time zone when hearing venue is null?

# Associated Tickets

#3796

**Comment by laurjpeterson** [comment]
- engineering, product, and design could sync about ticket AC before working on them. we might have caught the use case of different hearing venues, though it is a tricky use case. story time could be a good time for this.
