### ISSUE TITLE
Post Mortem | Hearings Prep users were blacklisted from Reader

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3827]
# Summary 

Anya, Gina, Lara, and Annie were interviewing a judge, and when the judge tried to access Reader, they were denied. Anya looked through recent deploys, and found a new feature that reduced reader access to users who were not blacklisted. After alerting Mark, he found that all hearing prep users were blacklisted. He immediately took all hearing prep users off the blacklist, and they were able to access Reader again.

# Open Questions

1. How can we improve communication between hearing prep and reader?

**Comment by laurjpeterson** [comment]
A few thoughts:
- access/blacklist changes and features could be announced at team-wide standup announcements
- when Hearing Prep adds more users, we can proactively communicate with Reader team (though by this time, Reader will likely have been rolled out to all attorneys and judges)

**Comment by sharonwarner** [comment]
Action Items:

1. Since @aroltsch is moving to Whiskey, she'll communicate any Reader changes that may affect Hearing Prep to Tango.
