### ISSUE TITLE
Documents List | VVA timestamp alert when VVA docs are unavailable

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3831]
If we haven't retrieved VVA documents for a given claims folder, and VVA is down or the feature flag is disabled, replace the timestamp with an alert message so users are aware that VVA documents are not included in the manifest.

## Acceptance Criteria
- If Virtual VA is down, or we've disabled the VVA feature flag, AND we've never retrieved the VVA docs for this file, we should replace the VVA timestamp copy with: "Unable to display VVA documents at this time" in red $color-secondary (see mock below)
- If VVA is down but we have previously retrieved VVA files, display the timestamp of last retrieval as usual

![image](https://user-images.githubusercontent.com/13420618/32452830-a1ea59a8-c2e8-11e7-847a-88d2eade16ab.png)

**Comment by abbyraskinUSDS** [comment]
@gnakm can you take a look at this copy and see if this works on the design side?

**Comment by gnakm** [comment]
@abbyraskinUSDS The copy looks good. What if we say VVA documents instead of Virtual VA because that's how we write our timestamp. 
![image](https://user-images.githubusercontent.com/13420618/32452830-a1ea59a8-c2e8-11e7-847a-88d2eade16ab.png)

**Comment by mmlumba** [comment]
@abbyraskinUSDS @gnakm Which red is supposed to be used for the text?

**Comment by gnakm** [comment]
@mmlumba `$color-secondary`

**Comment by astewarttistatech** [comment]
@mmlumba @abbyraskinUSDS is there any information on taking down VVA in order to see the timestamp in action?

**Comment by mmlumba** [comment]
@astewarttistatech Not sure if this exists currently, but is there a claims folder with missing/corrupted VVA documents you can access? That would be the only way I can think of on how to test this
