### ISSUE TITLE
Document Viewer | Add document type to header when new tab is opened

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3833]
When opening documents in separate Chrome tabs, I want to see the Document Type as a title on the tab so it's easier to distinguish between documents at a glance.

## Acceptance Criteria
- Verify that upon opening a document in a new tab, the tab's title matches the Document Type for the open document (follow browser's default truncation behavior for long titles)

**Comment by astewarttistatech** [comment]
Blocked because of 5XX errors in Reader. Current view:

**Comment by kierachell** [comment]
**PASSED**
<img width="542" alt="screen shot 2017-11-23 at 10 35 23 am" src="https://user-images.githubusercontent.com/18075411/33180248-11066274-d03a-11e7-8f13-cae3b746f578.png">
