### ISSUE TITLE
Hearing Worksheet: Display continuous numbering of issues

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3835]
Even if Issues come from multiple appeals streams the numbering of the issues should be continuous. e.g.:

Appeal Stream 1:

1. First issue
2. Second issue

Appeal Stream 2

3. Third Issue
4. Fourth Issue

Appeal Stream Three

5. Fifth Issue.

**Comment by nolawi** [comment]
duplicate #3390
