### ISSUE TITLE
RAMP ineligibility | Veteran's appeal has been moved to location 96

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3837]
If a Veteran's appeal has been moved to location 96 ("remand returned to BVA"), they are not eligible for RAMP. We should show them the "appeal is at the Board" message, and track this reason in our database separately.

AMO is attempting to filter these out on the front end, but it's possible cases will move to this stage between the sending and receiving of mail.

## Acceptance Criteria
- Verify that searching for an appeal that is in location 96 in VACOLS displays the "Ineligible to participate in RAMP: appeal is at the Board" alert (see: https://github.com/department-of-veterans-affairs/caseflow/issues/3775)
- Verify that we're capturing this ineligibility in our database as an error

**Comment by abbyraskinUSDS** [comment]
@shanear @cmgiven can you take a look?

**Comment by kierachell** [comment]
**PASSED**

```
OpenStruct BFKEY="3423515", BFCORLID="015449774S", BFCORKEY="CK1077839", BFATTID="1634", BFSO="D", BFAC="3", BFREGOFF="RO20", BFDC="3", BFMPRO="REM", BFCURLOC="96", BFHR="2", BFTBIND="X",
```
<img width="889" alt="screen shot 2017-11-24 at 9 37 09 am" src="https://user-images.githubusercontent.com/18075411/33215231-0bda2150-d0fd-11e7-8832-9136168b33c0.png">
