### ISSUE TITLE
Hearing Worksheet: Change the order of names listed on the Hearing Worksheet to be first name last name

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3839]
Hearing Worksheet: Change the order of names listed on the Hearing Worksheet to be first name last name

AC
Display the Veteran name and the Appellant name as: [firstname lastname] rather than the inverse.
If there's a middle initial: display both as [firstname mi. lastname]

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Navigate to Hearings 
2. Navigate to the Hearings Worksheet
3. Validate that the name of Appellant is in F,M,L order. 

Screenshot: 
![hearing worksheet](https://user-images.githubusercontent.com/23038505/32562450-bec2106c-c47c-11e7-8685-b1b7f19d3023.png)
