### ISSUE TITLE
Change name of repo back to Caseflow

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#384]
Rename this repo to caseflow.
- [x] Rename this repo to `caseflow` from `caseflow-certification`
- [x] make sure any dependent integrations still works
- [ ] Make sure waffle still works

**Comment by shanear** [comment]
@orischwartz this is going to involve a lot of changes to the appeals-deployment repo. Mind if i take that on?

**Comment by orischwartz** [comment]
@shanear Sure go for it.

**Comment by orischwartz** [comment]
Closing, tracking outstanding deployment changes in https://github.com/department-of-veterans-affairs/appeals-deployment/issues/199
