### ISSUE TITLE
Opened docs are sometimes not unbolding

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3841]
We've gotten several user reports that sometimes docs that were opened are not unbolded.

https://github.com/department-of-veterans-affairs/appeals-support/issues/731

**Comment by abbyraskinUSDS** [comment]
Also department-of-veterans-affairs/appeals-support#1793

**Comment by D-L-Ware** [comment]
Closed as part of clean up of Reader tickets.
