### ISSUE TITLE
What are the necessary steps to enable us to explore a service-oriented long-term architecture?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3846]
What are the necessary steps we have to take if we want to explore more of a service-oriented architecture?

Let's enumerate them in this issue with some initial, then start specing individual pieces out.

### VACOLS adapter code is complex and would likely need to be shared by multiple services. How would we do that?

Similar to ruby-bgs and connect-vbms, we'd want to abstract all VACOLS interaction code into a shared connect-VACOLS gem. Work Queue, Intake, and the Caseflow monolith would then all use this gem.

In a connect-VACOLS spec, we'd seek to answer the following questions and more:

- How mature is the shared VACOLS code?
- Which directories/models would we want to move over?
  - move the whole /vacols directory into this gem?
  - Refactor some VACOLS-specific repository code into the gem? So maybe we'd want our respositories to call out to gem methods for any VACOLS-specific logic. `AppealRepository` should then look more like `VBMSService`
- Can we enable read-only services like appeals status to use the DMS replica instead of the live VACOLS instance?
- Can we set up an environment where it is trivial to connect to one's own AWS VACOLS replica and run commands to interact with the DB?
  - This would improve development efficiency significantly.

### How would we share UI components between apps?

In /client/app/components, we currently have a healthy list of components that we share between our apps. Development on Work Queue, Intake, and the Caseflow monolith would be greatly speeded up if we share those components. We already share a lot of css from caseflow-commons.

In a spec directed towards modularizing UI components, we would answer the following questions:

- How mature are our shared components? If they're fairly mature (changed <= ~1x a week?), this will work better. If they're changed constantly, it'll be tough :(
- How much shared/sharable React code exists *outside* of the /components folder?
- Should we move the styleguide to caseflow-commons and set up a simple webpack/Rails config, so we can easily dev in caseflow commons?
- We do have a lot of CSS in the caseflow monolith. Do our components in /components depend heavily on that CSS, and can we abstract it? 
  - Do any teams need to devote a sprint to making their own stuff sharable?

### What is the source of truth for post-VAIMA appeals, and what would that look like in more of a service oriented architecture?

Right now, the source of truth for appeals is VACOLS. One key question to answer is—what is the source of truth for appeals created after February 14th, 2019? Where do we get and set appeals data?

**Comment by kierachell** [comment]
- Can Caseflow Commons bundle the UI code? Isn't that its purpose?
- Caseflow might remain the VACOLS adapter and the source of truth for the appeals model
- Other services we already kind of have via `connect_<VA system>` repos. In a way -  eFolder is a connect VBMS/VVA abstraction/service for Reader.

**Comment by amprokop** [comment]
lol @kierachell,  finding the unfinished issues and commenting on them

**Comment by kierachell** [comment]
sorry for showing interest and trying to be helpful? 🤷‍♂️
