### ISSUE TITLE
Daily Docket: Change the way time is displayed for Travel Boards in the UI

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3849]
As a judge I want to know what time (local time of RO) of day my hearings start...

**AC**
Daily Docket: Change the way time is displayed for Travel Boards to show both EDT and the local time at the RO:

**Mock**

<img width="881" alt="screen shot 2017-11-03 at 1 40 33 pm" src="https://user-images.githubusercontent.com/4975959/32388078-e19a1ec4-c09c-11e7-831f-5b445eb9f67f.png">

**Comment by astewarttistatech** [comment]
**Failed** @nolawi 

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing Prep > Daily Docket page
2. Verify that EST and the time of the RO are displayed

Current View: 
<img width="1398" alt="screen shot 2017-12-01 at 9 33 27 am" src="https://user-images.githubusercontent.com/23038505/33487390-0b597824-d67b-11e7-8d47-8f20d689a76a.png">

**Comment by lakohl** [comment]
@astewarttistatech I updated the AC to say EDT instead of EST - as this is where we landed in the end.

**Comment by astewarttistatech** [comment]
**PASSED** due to changed AC
