### ISSUE TITLE
Loading spinner is very large and does not show immediately

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3851]
Loading spinner is very large and does not show immediately

When the Hearing Schedule page is loading a very large spinner shows. 
When the Hearing Worksheet is loading no spinner shows fro several seconds, then when one does appear for a second it is very large.

**Comment by annienguyenUSDS** [comment]
@lakohl can you add a screenshot of large spinner, and what it should be.

**Comment by lakohl** [comment]
Sadly I'm locked out of demo right now, so can't take a screenshot. It should be the size of the spinner in Caseflow Commons.

**Comment by lakohl** [comment]
Caught it! 
![screen shot 2017-11-07 at 11 09 33 am 2](https://user-images.githubusercontent.com/4975959/32503940-92edf8e6-c3ac-11e7-913b-0bf15a71ea03.png)

**Comment by annienguyenUSDS** [comment]
Alexis also found another larger spinner: [3925](https://github.com/department-of-veterans-affairs/caseflow/issues/3925)

**Comment by mmlumba** [comment]
@lakohl @annienguyenUSDS I only see this in FF and not Chrome

**Comment by lakohl** [comment]
@mmlumba I think you are right. It looks ok in Chrome now, just janky in FF. I think we can close this.
