### ISSUE TITLE
Hearing Worksheet: Adjust Periods and circumstances of service box

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3852]
Hearing Worksheet: Adjust Periods and circumstances of service box:

1. Move this box up to display under Issues and above Contentions.
2. This box only needs to be as tall/large as the pre-populated data.

AC
Check if Adjust Periods and circumstances of service box is first.
Check if it auto resizes, and defaults to single line if its empty

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearings 
2. From Hearings, navigate to Hearings Worksheet
3. Validate that the Periods and Circumstances of Service box is moved under Issues but before Contentions

Screenshots: 
![hearing worksheet](https://user-images.githubusercontent.com/23038505/32573162-0bc074a8-c49b-11e7-959c-82ad73bb37df.png)
