### ISSUE TITLE
Hearing Worksheet: Display level diagnostic code under Levels 1-3

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3853]
As a judge I would like to see both the label and the diagnostic code (e.g. 5010 in mock below) listed in VACOLS under Levels 1-3

AC:
Display level diagnostic code under Levels 1-3

Mock:
<img width="850" alt="screen shot 2017-11-03 at 2 52 08 pm" src="https://user-images.githubusercontent.com/4975959/32390922-9ad1edfa-c0a6-11e7-9c6d-2e2ec55df221.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome, FF

Steps to Validate: 
1. Access Hearing Prep
2. Navigate to Hearing Worksheet
3. In the Issues section, validate that one of the columns has Levels 1-3 Diagnostic codes. 

Screenshots:
