### ISSUE TITLE
Hearing Worksheet: Remove the letter displayed after the Vet ID so judges can easily copy/paste it from the Hearing Worksheet

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3861]
**AC**
Remove the letter displayed after the Vet ID so judges can easily copy/paste it from the Hearing Worksheet into DAS. (like in Dispatch)

**Comment by nolawi** [comment]
<img width="511" alt="screen shot 2017-12-12 at 9 07 39 am" src="https://user-images.githubusercontent.com/1745984/33889315-b4973fca-df1d-11e7-9b82-fb360e02f1db.png"> we should consider one of these- its faster for the user.

**Comment by mmlumba** [comment]
@nolawi We do have a "copy to clipboard" feature for the VBMS note in Dispatch.

**Comment by nolawi** [comment]
ok

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearings 
2. Select a Veteran ID to a Hearings Worksheet
3. Verify that the letter at the end of the Veteran ID is gone, making it easier to copy. 

Screenshots:
<img width="1172" alt="screen shot 2017-12-15 at 10 29 11 am" src="https://user-images.githubusercontent.com/23038505/34049322-fa58f670-e184-11e7-8d2f-ea8808817b6e.png">
