### ISSUE TITLE
Hearing Worksheet: Add ability to format the notes on the HW

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3862]
AC:

1. Combine 'Contentions', 'Evidence', and 'Comments' into one box labeled 'Hearing Summary'.
1. Insert two lines of vertical after 'Contentions', after 'Evidence', and after 'Comments'.
1. Allow users to edit the labels 'Contentions', 'Evidence', and 'Comments' and the spaces between them.
1. Add the wysiwyg editor toolbar to allow judges to bold, italicize, Underline, adjust font size,
add bullets, create a numbered list, and adjust font color to blue, black and red.

![toobar](https://user-images.githubusercontent.com/4306128/39766214-bfccc31c-52b1-11e8-9ded-00a7c55e60fe.png)

**Comment by nolawi** [comment]
Not feasible inside the textboxes

**Comment by annienguyenUSDS** [comment]
@nolawi are there other ways to edit inside the text boxes?

**Comment by nolawi** [comment]
Essentially if its a textbox you can not style it. You can however display it with styles but not inside the text box

**Comment by annienguyenUSDS** [comment]
@nolawi, we're looking into other options to possible distinguish before and during hearing. 
Are there  shortcuts to change text?
Another option, if we have judge check a box, could we switch to different font or color for day of hearing?

**Comment by lakohl** [comment]
@NickHeiner wondering if you have any clever ideas for this... our aim is to distinguish notes made before a hearing from notes made during a hearing that are typed in the same box. (In the past judges have used different colored pens to differentiate these actions.)

**Comment by annienguyenUSDS** [comment]
@tejans24, if you have more updates on this to add. thanks!

**Comment by annienguyenUSDS** [comment]
@lakohl, Teja sent this link to look at in what formatting tools we want: https://jpuri.github.io/react-draft-wysiwyg/#/

**Comment by lakohl** [comment]
**Wish list (may need editing)**
Bold
Italic
undeline
font
font size
bullets
numbered list
font color
link? (Could we link to a reader doc? - would it work on the attorney view?)

**Comment by lakohl** [comment]
**Wish list (may need editing):**
Bold
Italic
undeline
font
font size
bullets
numbered list
font color
link? (Could we link to a reader doc? - would it work on the attorney view?)

**Comment by annienguyenUSDS** [comment]
@lakohl, from your list, took off font:
Bold
Italic
Underline
font size
bullets
numbered list
font color: we could limit this to 3 - blue, black and red
link - asking @tejans24 if that is possible, otherwise I would leave this off

**Comment by tejans24** [comment]
Yes, that is possible. The link would be something like this: [http://localhost:3000/reader/appeal/5db35c989/documents/4](http://localhost:3000/reader/appeal/5db35c989/documents/4) - 4 represents the document id

**Comment by lakohl** [comment]
@sharonwarner here's a mock to help describe a single note box solution:
![hearing worksheet one note](https://user-images.githubusercontent.com/4975959/39332128-872ea598-4974-11e8-8f35-671862af8640.png)

**Comment by lakohl** [comment]
I checked with Justin and he surveyed some additional folks for me. They thought 'Hearing Summary' could work as could 'Judge Comments'.

**Comment by lakohl** [comment]
@tejans24 I just saw this in demo - a couple little nits:
- Hearing Summary text should be the same size as Veteran/Appellant Information.
- No need to leave so much room above the Hearing Summary header, the space above it could be reduced by half.
- Can you make the top of the rectangle enclosing the formatting tools the same color as the side and bottom of the box?
- Would you be able to darken the border around each of the editing tool boxes? I don't think they will pass a 508 check.

**Comment by nolawi** [comment]
@tejans24 Can you rename [file](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/assets/stylesheets/react-draft-wysiwyg.css), and make it a symline like `PDF viewer css`.

**Comment by sharonwarner** [comment]
@lakohl I'm going to create another ticket with those design updates.

**Comment by lakohl** [comment]
I'm happy to be a reviewer or answer question on this ticket if it's helpful.
