### ISSUE TITLE
Hearing Worksheet: Re-order Document Dates

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3863]
**AC**
1. Re-order Document Dates section to display (left to right): Docket number, Prior BVA Decision, Rating Decision, NOD, SOC, Form 9, SSOC, Certification, Docs Since Certification (see mock)

1. Add in Rating Decision (RO notify date).

**Mock**
<img width="725" alt="screen shot 2017-11-16 at 12 56 47 pm" src="https://user-images.githubusercontent.com/4975959/32907353-bc815f22-cacd-11e7-9997-75c1a2349ae8.png">

Pre-req #3785 for rating decision

**Comment by nolawi** [comment]
|   |   |   |   |   |
|---|---|---|---|---|
| Docket Number  | NOD  |Form 9   |Prior BVA Decision   |  Docs since Certification |
| SOC  | Certification   | SSOC  |   |   |

this is ^ current order 

Can we reorder this so we know how exactly...

**Comment by lakohl** [comment]
@nolawi yes! confirming order now.

**Comment by lakohl** [comment]
@nolawi See top of the issue - now correct

**Comment by nolawi** [comment]
👍

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome, FF

Steps to Validate: 
1. Access Hearing Prep
2. Navigate to a Hearing Worksheet
3. In the Related Document section, verify that the sections are listed as such: (left to right): Docket number, Prior BVA Decision, Rating Decision, NOD, SOC, Form 9, SSOC, Certification, Docs Since Certification. 

Screenshots:

**Comment by lakohl** [comment]
The order here is still not quite right. Docs since Certification should come last _**after**_ the Certification date. See mock at the top.

Current:
![screen shot 2017-12-15 at 11 43 18 am](https://user-images.githubusercontent.com/4975959/34054624-ca7c91f4-e199-11e7-9707-929a53ce5214.png)
