### ISSUE TITLE
Manager View: History: Ability to "Show More" information

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#387]
As a Manager, I would like the ability to see more task items in the History section so that I can see the activity on more than just the last 10 tasks in the history.

### Acceptance Criteria
- Verify that when a user clicks on "Show More" under the the "Work History" list, the next 10 completed tasks are added on to the bottom of the list. The whole list should be in reverse chronological order by task completion date (timestamped).
- Verify that if there are fewer than ten remaining tasks to show, it shows all remaining tasks.
- Verify that if all tasks completed are shown, the "Show More" button is hidden.

### Technical Notes
- This may require an API call, so we should probably show "Loading More" in place of the "Show More" button while the request is in flight.

### Sub-task

- [ ] QA manually testing

**Comment by lakohl** [comment]
What are the items a manger would want to search on their Current/History page?

**Comment by abbyraskin** [comment]
Matt mentioned he may want to search for a specific case number (veteran ID) to check status.

**Comment by joofsh** [comment]
@nikitarockz The title says "Show More/Search", but the acceptance criteria seem focused on Show More.  If we don't have any current plans for search, can we split that out to a separate ticket in the backlog?

**Comment by nikitarockz** [comment]
@joofsh I just updated the title.  Sorry for the delay in responding to your request.  :smile:
