### ISSUE TITLE
Hearing Prep | Repetitive Issue under Multiple Appeals

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3870]
We met with Paul today, and he had an hearing with 4 Appeal Streams that showed the same issue under each to look into further why that happened.

**Comment by lakohl** [comment]
@sharonwarner maybe check if this bug still persists after you deploy #3797

**Comment by nolawi** [comment]
closing @annienguyenUSDS no longer an issue
