### ISSUE TITLE
Daily Docket | Past hearings were not all there

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3871]
Met with Paul today to look at most recent video hearing 10/30 with San Juan. He had 12 hearings, but only 3 showed up on the Hearing Prep Daily Docket. VACOLS shows all 12 hearings for that day.

AC:
1. Display the entire day/date of hearings or do not display that date/day at all on the Hearing Schedule page.
1. Display hearing days/dates up to 30 days in the past on the Hearing Schedule page.

**Comment by kierachell** [comment]
**PASSED**

<img width="633" alt="screen shot 2017-11-23 at 9 56 55 am" src="https://user-images.githubusercontent.com/18075411/33178580-a9a88b16-d034-11e7-8b1f-ddfc64f066cc.png">
