### ISSUE TITLE
Hearing Worksheet: Don't display comma when there is no city, state

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3877]
Hearing Worksheet: Don't display comma when there is no city, state

Current state:
![screen shot 2017-11-07 at 1 04 19 pm](https://user-images.githubusercontent.com/4975959/32509817-79d53ee0-c3bc-11e7-9ecb-749d17c81d76.png)

**Comment by astewarttistatech** [comment]
@lakohl @mmlumba do you know which css id was used to the original issue?

**Comment by lakohl** [comment]
@astewarttistatech I think the mock is in demo. But we've observed it in prod as well.

**Comment by astewarttistatech** [comment]
Unfortunately Mr. Washington is no longer in the same state in DEMO. I cannot find any data that has a Appellant without a City/State. How would you like to proceed in validation? @lakohl @mmlumba

**Comment by astewarttistatech** [comment]
Blocked until data needed for this ticket to be validated can be found.

**Comment by astewarttistatech** [comment]
@lakohl Is there anyway you can tell me about the data that matches this scenario in prod?

**Comment by lakohl** [comment]
unfortunately, I don't believe I have a case number for this.
