### ISSUE TITLE
Case Summary: Display any doc added in the past 30 days

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3878]
When a hearing prep user clicks over to Reader, they automatically have the case_summary document category filter on. We want to add more documents to that category filter. 

**AC**
- Include any doc added in the past 30 days in the case_summary category filter in reader.

**Comment by nickheiner-usds** [comment]
> any doc added in the past 30 days

Is that defined by the `received_at` column in the `documents` table?

**Comment by astewarttistatech** [comment]
@NickHeiner Currently it looks like the some of the veterans we have in Preprod do not have documents even though their hearing worksheet says other wise. Also, when in VBMS to upload documents, these "veteran(s) cannot be found". I do not know how you would like to proceed, but until then this ticket is blocked. 

Screenshots: 
<img width="1341" alt="screen shot 2017-12-19 at 7 57 49 pm" src="https://user-images.githubusercontent.com/23038505/34186012-0d4158de-e4f7-11e7-84ef-057e5d3ca43c.png">
<img width="1374" alt="screen shot 2017-12-19 at 7 58 00 pm" src="https://user-images.githubusercontent.com/23038505/34186013-0d4d2768-e4f7-11e7-8b50-8ad90957cbce.png">

**Comment by nickheiner-usds** [comment]
> Currently it looks like the some of the veterans we have in Preprod do not have documents even though their hearing worksheet says other wise.

In the screenshot you posted, the hearings worksheet says "Docs in eFolder: 0". Is there a different screenshot for the case you described of a vet having no docs when the worksheet says they do?

> Currently it looks like the *some* of the veterans

Is there any veteran for which you can test this ticket? Or does every single sample data case have this same problem?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Reader from Hearing Prep
2. Verify that documents that have been added within the last 30 days and haven't been viewed, are bolded in their name from the Document List page. 

Screenshots: 
<img width="1354" alt="screen shot 2018-01-05 at 11 22 55 am" src="https://user-images.githubusercontent.com/23038505/34618385-9b3f3eea-f20c-11e7-95c1-e01a3272af34.png">
