### ISSUE TITLE
Clear browser cache between feature subtests

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#3883]
Currently, feature subtests within the same test file share an instance of Capybara::Session and the browser associated with that session retains its cached assets across supposedly independent subtests. This could cause a subtest to fail when run in isolation, however pass when run after other subtests due to the assets the browser caches (or the opposite, as was the case in [reader_spec](https://github.com/department-of-veterans-affairs/caseflow/pull/3880/commits/c4b59a31003decea5389f26c969ca409b0972d41)). We should be able to clear the browser's cache during tests (and maybe default to this behaviour, even though this is not the current default behaviour).

Capybara has a [reset! method](http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara%2FSession:reset!) that sounds like it should solve this problem, yet it does not. I looked into a [few different ideas](https://makandracards.com/makandra/16117-how-to-clear-cookies-in-capybara-tests-both-selenium-and-rack-test) about how to implement this, but could not get any to work (this appears to be a [known issue](https://github.com/teamcapybara/capybara/issues/1001) in the Capybara community as well).

AC:
* Browser cache can be cleared between feature subtests

**Comment by lowellnava** [comment]
Possible solution to this issue, courtesy @kierachell: https://gist.github.com/nruth/864dc9875b4feb183b7b10ddbd25c7f4#file-selenium-rb-L66

**Comment by alisan16** [comment]
Closing as this is now obsolete.
