### ISSUE TITLE
SPIKE: Can we relay when a veteran is deceased?

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3888]
SPIKE: Can we relay when a veteran is deceased?
Can we pull this info from BGS/VBMS? and display it on the Hearing Worksheet?

**Comment by kierachell** [comment]
- From BGS:
Yes:
```
{:brthdy_dt=>#<DateTime: 1945-01-01T00:00:00-05:00 ((2431457j,18000s,0n),-18000s,2299161j)>,
 :death_dt=>#<DateTime: 2017-07-25T00:00:00-05:00 ((2457960j,18000s,0n),-18000s,2299161j)>,
 :email_addr=>nil,
 :ethnic_type_cd=>"L",
 :file_nbr=>"123123123",
 :first_nm=>"JIM",
 :first_nm_key=>"-2",
 :gender_cd=>"M",
 :jrn_dt=>#<DateTime: 2017-11-01T10:40:18-05:00 ((2458059j,56418s,0n),-18000s,2299161j)>,
 :jrn_lctn_id=>"328",
 :jrn_obj_id=>"CRMUD  - FNOD",
 :jrn_status_type_cd=>"U",
 :jrn_user_id=>"281TUSER06",
 :last_nm=>"SHEWZ",
 :last_nm_key=>"-2",
 :lgy_entlmt_type_cd=>"04",
 :mlty_person_ind=>"Y",
 :person_death_cause_type_nm=>"Unknown",
 :ptcpnt_id=>"12989707",
 :race_type_nm=>"Unknown",
 :ssn_nbr=>"123123123",
 :ssn_vrfctn_status_type_cd=>"0",
 :station_of_jurisdiction=>"328",
 :termnl_digit_nbr=>"23",
 :vet_ind=>"Y"}
```
- `:gender_cd` but it is not _always_ present

**Comment by lakohl** [comment]
@cmgiven Which of these sources (VACOLS or VBMS) of info do yo think would be more reliable? VACOLS is probably where the most recent changes would have occurred, but not sure if that field is always used/updated.

**Comment by cmgiven** [comment]
I don't have a good sense for accuracy, although I had done some work on a different DSVA project that leads me to be skeptical. But do we need whether the Veteran is deceased, or is it sufficient to know whether it's a non-Veteran appellant? Because we know the latter with some accuracy.

**Comment by lakohl** [comment]
Both of those its of info are helpful for different reasons.
