### ISSUE TITLE
SPIKE: Can we display the Veteran's sex/gender?

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3889]
SPIKE: Can we display the Veteran's sex/gender on the Hearing Worksheet?

Where do we pull this info from? What are the options for sex/gender?

**Comment by kierachell** [comment]
- From BGS:
Yes:
```
:brthdy_dt=>#<DateTime: 1969-12-12T00:00:00-06:00 ((2440568j,21600s,0n),-21600s,2299161j)>,
  :email_addr=>nil,
  :file_nbr=>"906051540",
  :first_nm=>"PARRY",
  :first_nm_key=>"-2",
  :gender_cd=>"F",
  :jrn_dt=>#<DateTime: 2015-03-10T11:39:19-05:00 ((2457092j,59959s,0n),-18000s,2299161j)>,
  :jrn_lctn_id=>"452",
  :jrn_obj_id=>"VBMS  - CEST",
  :jrn_status_type_cd=>"U",
  :jrn_user_id=>"TT317_DVSR",
  :last_nm=>"NERMAL",
  :last_nm_key=>"-2",
  :mlty_person_ind=>"Y",
  :ptcpnt_id=>"600068327",
  :ssn_nbr=>"906051540",
  :ssn_vrfctn_status_type_cd=>"0",
  :station_of_jurisdiction=>"452",
  :termnl_digit_nbr=>"40",
  :vet_ind=>"Y"}
```

- `:gender_cd` but it is not _always_ present

**Comment by lakohl** [comment]
Thanks @kierachell !

**Comment by lakohl** [comment]
What are the options in the gender field? are there any other than m and f?

**Comment by lakohl** [comment]
Implementation: https://github.com/department-of-veterans-affairs/caseflow/issues/3930

**Comment by kierachell** [comment]
Sorry, didn't see the mention:
Afaik the values are 'M', 'F' or nil.

VBMS does show `nil` as `Undifferentiated`. But we can't exactly set that via the backend API
