### ISSUE TITLE
Daily Docket | Remove "Add on"

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3890]
As a Judge I don't need to use "Add on" on the Daily Docket if a Veteran is on the Docket. The RO or coordinator will note this elsewhere in their workflow.

A/C
- Move "Transcript Requested" to where "Add on" is and align under Deposition dropdown.

Mock

previous:
<img width="447" alt="screen shot 2017-11-09 at 12 59 19 pm" src="https://user-images.githubusercontent.com/22620270/32621466-dd2cdbe6-c54d-11e7-9ab2-3938c23883f3.png">

proposed:
<img width="451" alt="screen shot 2017-11-09 at 12 50 42 pm" src="https://user-images.githubusercontent.com/22620270/32621425-c0297298-c54d-11e7-894a-c6ad31601d97.png">

**Comment by kierachell** [comment]
**PASSED**
<img width="606" alt="screen shot 2017-11-23 at 9 39 21 am" src="https://user-images.githubusercontent.com/18075411/33177949-5eade23e-d032-11e7-979a-0f06c5fb455f.png">
