### ISSUE TITLE
When category is selected via URL param cannot toggle comments

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3892]
When the hearing prep category is selected via URL param the toggle comments button on the document list page turns the filter back on if it was turned off, and does not toggle the comments.

![canttogglecomments](https://user-images.githubusercontent.com/3885236/32623868-891b5bec-c555-11e7-92c1-e6ec1f8bfb2f.gif)

# AC
1) Verify comments can be toggled even when a category is selected.

**Comment by kierachell** [comment]
**PASSED**

![cool](https://user-images.githubusercontent.com/18075411/32638333-d246ed54-c58c-11e7-83e8-eb4b8e1c6b81.gif)
