### ISSUE TITLE
Hearing Prep | Distinct Titles in Browser Tabs

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3894]
related #4157
As a Judge, I have multiple tabs and windows open during hearing prep and hearings. This includes multiple tabs for hearing prep worksheets, which are difficult to distinguish what hearing I'm working on because the labels have the same titles. As a Judge, I sometimes go back and forth between tabs and often it takes time to figure out to which Veteran's worksheet I am so I click on all the tabs until I find the one I'm looking for.

A/C: Clearer titles in tabs across Hearing Prep Product that match the page that the Judge is viewing.

Current Naming in Caseflow:
1. For all pages: "Caseflow Hearing Prep"

Current mock - Hearing Prep pages are not distinguished from one another:
<img width="707" alt="screen shot 2017-11-06 at 10 52 09 pm" src="https://user-images.githubusercontent.com/22620270/32476787-b7bd7cf6-c347-11e7-8506-9f7c57f1254b.png">

Proposed Tab Naming Change:
1. Your Hearing Days 
2. Daily Docket 11/30/2017 (date of the docket)
3. J. Snuffy's Worksheet (First initial, Last Name's Hearing Worksheet)
~~4. J. Snuffy's Claims Folder (First initial, Last Name's Claims Folder)~~ (to be tested in another ticket)

Proposed Mock: 
Update "Upcoming Hearing Days" below to "Your Hearing Days" 
<img width="1123" alt="screen shot 2017-11-09 at 4 37 19 pm" src="https://user-images.githubusercontent.com/22620270/32630950-8b200368-c56c-11e7-8d76-cd7583dd8fa5.png">

**Comment by annienguyenUSDS** [comment]
@sharonwarner checked with Reader, and they are good with the title change for claims folder page.

**Comment by astewarttistatech** [comment]
**FAILED**

Current View in Preprod: 

<img width="206" alt="screen shot 2018-01-05 at 10 39 46 am" src="https://user-images.githubusercontent.com/23038505/34616323-ed920558-f205-11e7-9938-c2b4c780bef9.png">
<img width="218" alt="screen shot 2018-01-05 at 10 40 01 am" src="https://user-images.githubusercontent.com/23038505/34616324-ed9f5730-f205-11e7-9c1c-d41c9dfcd2e3.png">
<img width="186" alt="screen shot 2018-01-05 at 10 46 32 am" src="https://user-images.githubusercontent.com/23038505/34616325-edadfe66-f205-11e7-9723-005e05edfda3.png">
<img width="152" alt="screen shot 2018-01-05 at 10 47 14 am" src="https://user-images.githubusercontent.com/23038505/34616326-edb8dcfa-f205-11e7-923b-14965c87f9d0.png">

**Comment by astewarttistatech** [comment]
Current view | Preprod & UAT 

@nolawi still no names on the tabs.

Screenshot: 
<img width="587" alt="screen shot 2018-01-08 at 11 49 39 am" src="https://user-images.githubusercontent.com/23038505/34681515-1ce5efe8-f46a-11e7-9194-cf5d3cf45178.png">

**Comment by nolawi** [comment]
Looks like this works, some Appeals in UAT do not have an appellant thus the worksheet might not show a name..

**Comment by astewarttistatech** [comment]
<img width="863" alt="screen shot 2018-01-11 at 11 27 07 am" src="https://user-images.githubusercontent.com/23038505/34835483-f312c3ac-f6c2-11e7-84e4-bf6d1792bf48.png">

Still not showing up. 

Current View: Preprod

**Comment by annienguyenUSDS** [comment]
I'm seeing First Name and Last Name in Demo. 
It should be First Initial and Last Name.

**Comment by annienguyenUSDS** [comment]
Current in Demo: "Daily Docket 2018-01-07" 
Should be "Daily Docket 1/7/2018", and "Daily Docket 11/30/2018"

**Comment by Sjones352** [comment]
**PASSED**


Validated in:  Chrome 

Steps to Validate: 
1. Access Hearing-Prep
2. Click Date 
3. Validate the Distinct Titles in Browser Tabs


<img width="1012" alt="screen shot 2018-01-22 at 2 54 03 pm" src="https://user-images.githubusercontent.com/23080951/35241550-ce7640d0-ff84-11e7-887f-a9d3b008ba44.png">
