### ISSUE TITLE
Use flexbox to center StatusMessage in PdfFile

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#3897]
When we added the status message to indicate that a document failed to load, we implemented the centering style in a less-than-ideal fashion (see https://github.com/department-of-veterans-affairs/caseflow/pull/3880/files#r149727695). We should use flexbox instead.

AC:
* Use flexbox to center StatusMessage in PdfFile

**Comment by D-L-Ware** [comment]
Closed as part of clean up of Reader tickets.
