### ISSUE TITLE
Store appeal document list category filter state in URL

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#3898]
Currently, we can apply a filter to an appeal's document list when we initially navigate to the document list page by including a parameter in the URL's query string (/reader/appeal/{{APPEAL_ID}}/documents?category={{CATEGORY}}). However, as we change the filters on the document list page (and navigate away from/ and back to the document list) the parameter remains what it was when we initially navigated to that page. For instance, if we navigate to /reader/appeal/123456789/documents?category=case_summary and remove the initial filter, the URL in the location bar will not update to reflect this change.

The behaviour to set the document list's initial filter starts in DecisionReviewer.determineInitialCategoryFilter().

AC:
* Update URL in browser location bar to reflect current document list category filters

**Comment by D-L-Ware** [comment]
Closed as part of clean up of Reader tickets.
