### ISSUE TITLE
Finish Processing | First-time RAMP: update copy

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3902]
As a Claims Assistant, I want clear copy when using Intake so I know what is happening in the app.

## Acceptance Criteria
- Verify that issues box header, checkbox instructions, and button copy were all updated (see below)

## Copy
- Change from "active appeal" to "eligible appeal": 
> This Veteran has [#] eligible appeal, with the following issue(s):

- Change checkbox copy to note what happens in the next step more clearly
>  I've completed the above steps outside Caseflow. 

- Change the submit button copy 
> Finish intake

- Make the cancel intake button sentence case
> Cancel intake

## Design
![image](https://user-images.githubusercontent.com/4042181/32743678-14e4f282-c87b-11e7-9d6e-d0e4e2d338b4.png)

**Comment by mmlumba** [comment]
@abbyraskinUSDS The description below "Finish processing[...]" is currently the following:
> Please complete the following steps outside Caseflow.
But the mock has a different description. Do you want me to update that also?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome

Steps to Validate: 
1. Access Intake
2. Use a first time Veteran eligible for RAMP
3. Navigate to the Finish Processing page. 
4. Verify that the copy on the page matches what is requested in mocks/AC. 

Screenshots: 
<img width="1418" alt="screen shot 2017-12-18 at 11 33 38 am" src="https://user-images.githubusercontent.com/23038505/34116777-91652b74-e3e7-11e7-9f24-ab7a17ffe0f6.png">
