### ISSUE TITLE
InvalidEndProduct

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3903]
Each time an end product fails our validation, we get a Sentry alert. We should instead rescue that exception. 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/594/

**Comment by sunil-sadasivan** [comment]
**AC**


Ensure that this error message is returned when an invalid end product exception is thrown in the manage claim step of dispatch.  (http://localhost:3000/dispatch/establish-claim/)

<img width="1307" alt="screenshot 2017-11-14 10 07 13" src="https://user-images.githubusercontent.com/31223104/32787127-cbc575d2-c923-11e7-83b6-89bb5a575093.png">

For testing... I manually threw an exception here:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/establish_claim.rb#L72

**Comment by sunil-sadasivan** [comment]
This is now fixed... however we should still have better logging to understand why exactly this will fail validation. 

I've created that task here: https://github.com/department-of-veterans-affairs/caseflow/issues/3915

**Comment by kierachell** [comment]
**PASSED**

- Found a vet with no gender
- Tried to make an EP
<img width="1179" alt="screen shot 2017-11-14 at 5 24 53 pm" src="https://user-images.githubusercontent.com/18075411/32808448-0ce7eb16-c961-11e7-8431-d02cd627009b.png">
<img width="715" alt="screen shot 2017-11-14 at 5 25 00 pm" src="https://user-images.githubusercontent.com/18075411/32808450-0d02f352-c961-11e7-9c2b-ba2133783dd0.png">
<img width="1122" alt="screen shot 2017-11-14 at 5 25 06 pm" src="https://user-images.githubusercontent.com/18075411/32808451-0d1a4322-c961-11e7-95a1-60095e85a611.png">


- No Sentry error = YAY
