### ISSUE TITLE
Set timeout for network requests through ApiUtil

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#3906]
Currently, when we make network requests with SuperAgent by way of ApiUtil we return a promise. If that request never responds for whatever reason (server hangs, crashes but doesn't send a signal, user disconnects from wifi and network disconnection signal is not sent, etc.) then that promise will stay in the pending state forever. SuperAgent allows us to set a timeout on requests (https://visionmedia.github.io/superagent/#timeouts). I think it might be a good idea to set some default value for all our requests for the worst case scenarios.

AC:
* Network requests made through ApiUtil trigger rejected state callback after some length of time

**Comment by nickheiner-usds** [comment]
This sounds good to me. I'd just do a quick check of existing code that uses `ApiUtil` to ensure that we don't ever expect requests to take a very long time (e.g. downloading a large document).

**Comment by alisan16** [comment]
Closing as this is now obsolete.
