### ISSUE TITLE
Feature Flag | Enable Group 2 – ARC users on 11/13/2017

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#3909]
As Project Manager, I would like the following feature flag enabled on Thurs., 11/13/2017 as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  Mail Intake (initial release)

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

“AMCJWILL”, “AMCCKARR”, “AMCNTANN”, “AMCRBANK”, “AMCAMILL”, “AMCRCOAT”

## Related Stories
**_PM Issues_**
IP | Intake | Request Feature Flag enabled [#1587]( https://github.com/department-of-veterans-affairs/appeals-pm/issues/1587)

**Comment by shanear** [comment]
Feature toggle is enabled for all of ARC, `RO97`.
