### ISSUE TITLE
Better error message when duplicate 683 or 682

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3912]
Right now, if there is already a 682 or 683 EP. We have a generic error message. We should give them something more specific. Or maybe it doesn't matter.

There are also other reasons why they may have a conflicting 682 or 683:
<img width="546" alt="screen shot 2017-11-13 at 5 44 54 pm" src="https://user-images.githubusercontent.com/1596259/32754101-71056dfe-c89d-11e7-9cdc-b84af733fcc9.png">

<img width="598" alt="screen shot 2017-11-13 at 5 44 27 pm" src="https://user-images.githubusercontent.com/1596259/32754103-72e94da2-c89d-11e7-9024-9d21cb56c01c.png">

**Comment by abbyraskinUSDS** [comment]
Closing in favor of #4773
