### ISSUE TITLE
`AppealRepository.certify` should have more thorough unit tests

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3919]
We got a report of 200 certified cases where a hearing was not found in VACOLS even though the Form 9 showed that a hearing was needed. In the end, we don't think there was a bug, and this report was misfiled. But it was a bit scary because our `certify` method is not well-tested. 

The live method is:

```
  def self.certify(appeal:, certification:)
    certification_date = AppealRepository.dateshift_to_utc Time.zone.now

    appeal.case_record.bfdcertool = certification_date
    appeal.case_record.bf41stat = certification_date

    preference_attrs = VACOLS::Case::HEARING_PREFERENCE_TYPES_V2[certification.hearing_preference.to_sym]
    appeal.case_record.bfhr = preference_attrs[:vacols_value]
    # "Ready for hearing" checkbox
    appeal.case_record.bftbind = preference_attrs[:ready_for_hearing] ? "X" : nil
    # "Video hearing" checkbox
    appeal.case_record.bfdocind = preference_attrs[:video_hearing] ? "V" : nil

    MetricsService.record("VACOLS: certify #{appeal.vacols_id}",
                          service: :vacols,
                          name: "certify") do
      appeal.case_record.save!
    end
  end
```

while the fake method is just a stub.

```
  def self.certify(appeal:, certification:)
    @certification = certification
    @certified_appeal = appeal
  end
```

We should unit test all the `case_record` lines of code. It's up to the developer how to do this. One way would be to copy them over to the fake version, so they almost completely match.

## AC for Dev
- The `certify` method should be unit tested with a stub `case_record` object.

**Comment by alisan16** [comment]
Closing as this is now obsolete.
