### ISSUE TITLE
Caseflow Dispatch Logo:  Add Caseflow Dispatch logo

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#392]
As a user, when I open up any page in Caseflow Dispatch I should see Caseflow Dispatch and not Caseflow Certification at the top of the page.

### Acceptance Criteria 
Verify that the logo and title of the page has changed to Caseflow Dispatch.

### Sub-tasks

- [ ] QA discovery and scripting

**Comment by joofsh** [comment]
@nikitarockz @shanear Do we have the logo asset for this ticket?

**Comment by nikitarockz** [comment]
I am going to let Shane answer that one.  That is before my time.  :-)

On Nov 16, 2016 7:15 PM, JD Pagano <notifications@github.com> wrote:

@nikitarockz<https://github.com/nikitarockz> @shanear<https://github.com/shanear> Do we have the logo asset for this ticket?

-

**Comment by shanear** [comment]
@KHarshawat can you add the dispatch versions of the certification logo? If there is one?

![caseflow-logo_2x](https://cloud.githubusercontent.com/assets/1596259/20391623/3af427ea-aca2-11e6-93a8-23174a53cca9.png)
![caseflow-logo](https://cloud.githubusercontent.com/assets/1596259/20391622/3af41110-aca2-11e6-8ac1-3965c1cf7dad.png)

@joofsh the dispatch logo will match the dimensions of the existing certification logo in `/app/assests`. The title is in plain text. The logic on what logo/title to display should be the tricky part of this story.

So y'all can just copy the current logo assets and then we can fill them in with the new logo asset if we get one. Sound good?

**Comment by KHarshawat** [comment]
Logo attached here!

[Caseflow Dispatch Logo.svg.zip](https://github.com/department-of-veterans-affairs/caseflow/files/598615/Caseflow.Dispatch.Logo.svg.zip)

**Comment by shanear** [comment]
<img width="340" alt="screen shot 2016-12-01 at 2 29 45 pm" src="https://cloud.githubusercontent.com/assets/1596259/20808998/aca625ba-b7d2-11e6-81a0-6f50455ebcfe.png">

@mdbenjam it doesn't say "Dispatch"

**Comment by astewarttistatech** [comment]
**PASSED**

Looks good. See attached. 
<img width="1117" alt="screen shot 2016-12-05 at 9 48 52 am" src="https://cloud.githubusercontent.com/assets/23038505/20889214/1f9d8c20-bad0-11e6-82c6-9d51aab7d91e.png">
