### ISSUE TITLE
Analytics | Fix bugs from actions refactor

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3923]
Looks like 2 actions' analytics were broken in the action refactor.

https://github.com/department-of-veterans-affairs/caseflow/commit/b4d33ebcffdd708fb2278f47e9ff436980fd2b9e#commitcomment-25633362
https://github.com/department-of-veterans-affairs/caseflow/commit/6fb336dd72ca874033ca17c064b7182f1ae77b7e#commitcomment-25633450

# AC
1) Verify the placing annotation analytics is filed under: 'start-placing-annotation',
1) Verify the handleAltBackspace analytics is marked as 'from-back-to-documents'.

**Comment by astewarttistatech** [comment]
@mmlumba this did not pass. 

Verify the placing annotation analytics is filed under: 'start-placing-annotation', ✅ 
<img width="1430" alt="screen shot 2017-12-07 at 11 30 41 am" src="https://user-images.githubusercontent.com/23038505/33726345-c048f9d2-db42-11e7-9564-7167035c5ec6.png">


Verify the handleAltBackspace analytics is marked as 'from-back-to-documents'. ❌ 
<img width="1404" alt="screen shot 2017-12-07 at 11 33 12 am" src="https://user-images.githubusercontent.com/23038505/33726350-c4b6fce4-db42-11e7-9395-42710dbf5c35.png">
