### ISSUE TITLE
Intake | Prevent two people from working on the same veteran form

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3924]
I noticed that there are two intakes for the same veteran by two different users today.

We should automatically prevent this from happening.

## Acceptance Criteria
- When a user searches for a veteran to begin an intake, if there is another intake in progress for that same form & veteran, show the following error

Title: NAME already started processing this form
Body: We noticed that NAME may be in the middle of processing the same form for this Veteran in Caseflow. Please confirm they will complete this intake, then move on to the next mail item.

**Comment by shanear** [comment]
@abbyraskinUSDS to touch up the copy here.

**Comment by abbyraskinUSDS** [comment]
Title: NAME already started processing this form
Body: We noticed that NAME may be in the middle of processing the same form for this Veteran in Caseflow. Please confirm they will complete this intake, then move on to the next mail item.

**Comment by suzchap** [comment]
LGTM
