### ISSUE TITLE
Hearing Prep | Spinner is HUGE in FF

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3925]
**Currently:** If you access Hearing Prep in the FF browser, the spinner comes up about as big as your screen. **this is only in FF and not chrome**

**Expected:** Not that. The spinner should be the size of the rest of the spinners in the rest of the products. 

**Found in:** Preprod and Local
**Browser:** FF

**Steps to Recreate:**
1. Open your FF browser
2. Go to appeals.cf.preprod.ds.va.gov/hearings/dockets/
3. Verify that the spinner is gigantic. 

**Screenshots:**
<img width="1440" alt="screen shot 2017-11-15 at 1 08 21 pm" src="https://user-images.githubusercontent.com/23038505/32852762-f2c2347a-ca06-11e7-9f6a-cd75fa716614.png">

**Comment by nolawi** [comment]
we do not support FF but #3851 should fix it
