### ISSUE TITLE
SPIKE: Can we surface and distinguish btwn VACOLS flashes

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3926]
SPIKE: Can we surface and distinguish btwn VACOLS flashes?

Flashes in VACOLS indicate: homelessness, financial hardship, incarcerated vet etc. 
Can we distinguish between flashes that might extend the Veteran AOD status and other types of flashes? Can we surface these on the Hearing Worksheet?

**Comment by annienguyenUSDS** [comment]
@laurjpeterson

**Comment by annienguyenUSDS** [comment]
@sharonwarner wondering if you can look into?
