### ISSUE TITLE
Confirmation | Reminder to close pending EP

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3928]
Context: When we close the VACOLS record for an eligible RAMP appeal, there may be a pending EP in VBMS that the CA needs to also close. We should add some language reminding CAs to do this, as we won't do this in Caseflow for now.

## Acceptance Criteria
- On the confirmation page for a first-time RAMP Election Form, descriptive copy after the header should be updated to say: "[Veteran's Name]'s (ID #35555555) opt-in election has been processed. Remember to close any pending EPs associated with this appeal." 

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34852548-41090c30-f6fd-11e7-849f-d56bb0164584.png)

**Comment by shanear** [comment]
@abbyraskinUSDS is this a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/4664?

**Comment by abbyraskinUSDS** [comment]
They're actually opposite (4664 undos this ticket). I think you already completed this ticket though, so I'll close it.
