### ISSUE TITLE
Hearing Worksheet: Display the Veteran's gender from BGS

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#3930]
As a judge, I would like to know the gender of the veteran whose case I am hearing. 

**AC**
Display the Veteran's gender (e.g. male, female...) on the Hearing Worksheet. This info should be pulled from the BGS 'gender' field and translated into a word, eg. 'female' when BGS indicates 'f'.

**Mock**
<img width="910" alt="screen shot 2017-11-15 at 2 59 27 pm" src="https://user-images.githubusercontent.com/4975959/32857572-37df5c54-ca16-11e7-9e50-a65e0eacba03.png">

**Comment by lakohl** [comment]
more info in: https://github.com/department-of-veterans-affairs/caseflow/issues/3889

**Comment by tejans24** [comment]
@lakohl @annienguyenUSDS What should the Gender be if the value is nil from BGS?

@kierachell mentioned the possible values from BGS to be 'M', 'F' or nil in #3889 or should we even show the field if it's nil?

**Comment by lakohl** [comment]
@tejans24 I think if there is no value for gender we can leave the field blank but display the label

**Comment by tejans24** [comment]
@lakohl sounds good
