### ISSUE TITLE
Style guide | Change accordion text color

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#3933]
## Story
We are trying to use less variations of gray in our applications. Since our default text color is `$color-gray-dark`, we want to make the accordion text and svg icons the same. 

## AC
- Verify that the text and icon colors of [style guide accordions](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#accordions) are `$color-gray-dark`

**Comment by astewarttistatech** [comment]
**PASSED**

Preprod | Chrome

Screenshot:
![navbarv2](https://user-images.githubusercontent.com/23038505/33618330-40791e50-d9b0-11e7-9335-ca3ccedb7827.gif)
