### ISSUE TITLE
SPIKE: How often do Judges fill out boxes in "+Add issue" row in Hearing Worksheet?

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3937]
SPIKE: How often do Judges fill out boxes when they "+Add issue" row in Hearing Prep Worksheet? 

Want to know when Judges add an new Issue row, if they fill in the first box with text or fill out all the boxes in that row.

**Comment by sharonwarner** [comment]
total number of user_created issues: 37
with edited program: 32
with edited name: 32
with edited levels: 27
with edited description: 27

**Comment by annienguyenUSDS** [comment]
thanks @sharonwarner! do you know the number of judges have done this?

**Comment by sharonwarner** [comment]
{824=>1, 819=>5, 749=>2, 851=>14, 755=>5, 825=>1, 827=>1, 740=>1, 817=>1}

Those are judge ids along with the number of issues they've created. So, judge 824 has created 1 issue.
