### ISSUE TITLE
Select Form | New first step: CA selects form to process

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3956]
As a CA, I want to tell Caseflow which type of form I'm processing from the Mail Portal, so the app can help me complete the right steps.

## Acceptance Criteria
- Verify that this page is the first step in Caseflow Intake
- Verify that the copy matches the copy below, following styleguide for design specifics 

Copy:
**Welcome to Caseflow Intake!**
Please select the form you are processing from the Centralized Mail Portal.

Which form are you processing?
RAMP Opt-In Election Form
21-4138 RAMP Selection Form

Invision prototype:
https://va-gov.invisionapp.com/share/MVESO6KPG

**Comment by astewarttistatech** [comment]
**FAILED**

Current view:
