### ISSUE TITLE
Search | Re-filing: search validations

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3957]
When processing a RAMP re-entry form, I want to know that I'm searching for a valid Veteran ID, so I can continue processing the form.

## Acceptance Criteria
- If a Veteran ID does not match a Veteran ID already processed in Intake, display an alert (see below)
- If the Veteran ID has a pending RAMP EP, display an alert (see below)
- (The rest of the alerts are the same as Intake v1: exists in corporate db, ID is valid, user has sensitivity to access file)

Copy:
**Search for Veteran by ID**
To continue processing this form, enter the Veteran’s 8 or 9 digit ID number into the search bar below.

![image](https://user-images.githubusercontent.com/4042181/33625305-2375d20c-d9c5-11e7-9183-2155fc2d1a9f.png)

## Veteran did not participate in RAMP
![image](https://user-images.githubusercontent.com/4042181/34118652-6eb21e7e-e3ed-11e7-9fca-2c2062b638e1.png)

No RAMP Opt-In Election
A RAMP Opt-In Election Form was not yet processed in Caseflow, so this Veteran is not eligible to request a RAMP re-filing. Notify the Veteran using the “RAMP Ineligible Letter”.

## Pending EP alert
![image](https://user-images.githubusercontent.com/4042181/34118605-4d026bbc-e3ed-11e7-822c-26e2879f351c.png)

This Veteran has a pending RAMP EP in VBMS
If this Veteran has not yet received a RAMP decision on their RAMP Opt-In Election Form, notify them using the “RAMP Ineligible Letter” (premature election).

**Comment by abbyraskinUSDS** [comment]
@shanear can you take a look at this, and if necessary, make it more engineery and/or break it out in a way that makes sense to you?

**Comment by abbyraskinUSDS** [comment]
Add copy  just for re-filings

**Comment by abbyraskinUSDS** [comment]
@shanear to clean up.

**Comment by abbyraskinUSDS** [comment]
Abby to add alert copy for two messages mentioned above

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

1. Access Intake 
2. Search a veteran ID that has already been filed
3. Verify the error message displayed is correct
4. Search a veteran who
