### ISSUE TITLE
Review Request | Enter receipt date and selection

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3958]
When processing an intake form, I want to select the form I need to process, so Caseflow will guide me through the right steps to complete.

## Acceptance Criteria
- Receipt Date field with validations using our date picker
  - Can't be in future
  - Must be earlier than previous Receipt Date
- All fields are required; show in-line error from styleguide if a user selects the "Create End Product" button with empty field(s) on page
- If the Veteran's last review was a HLR (with or without conference), display an alert (see below)
- See #4139 for behavior if user selects Appeal to Board (for this ticket, radio button does not need to do anything)
- Button says "Continue to next step" -- selecting it navigates user to confirmation page

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34116539-efa909e0-e3e6-11e7-853e-31a75939f123.png)

### Copy
- Review [Veteran's Name]'s [name of form]
- What is the Receipt Date of this form?
- Which review lane did the Veteran select?
  - Supplemental Claim
  - Higher-Level Review
  - Higher-Level Review with Informal Conference
  - Appeal to Board

### Alert if HLR --> HLR
![image](https://user-images.githubusercontent.com/4042181/34114538-0fa9f354-e3e1-11e7-85a0-b93eb725ee4d.png)

### Copy
Ineligible for Higher-Level Review
Contact the Veteran to verify their lane selection. If you are unable to reach the Veteran, send a letter indicating that their selected lane is not available, and that they may clarify their lane selection within 30 days.

**Comment by abbyraskinUSDS** [comment]
Note: need to add receipt date here

**Comment by abbyraskinUSDS** [comment]
Review request instead of review form

**Comment by abbyraskinUSDS** [comment]
Need language if Veteran requests HLR -> HLR

**Comment by astewarttistatech** [comment]
**Blocked** until access granted for Share (sp?)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT | Chrome | Console

1. Access Intake
2. Start an Opt-In RAMP Intake with a veteran file number found in bgs and VACOLS with appeals
3. Complete the happy path for that veteran in Intake
4. Access VBMS in the same environment
5.Access the same veteran's EP and add a contention
6. In Terminal, clear the same EP for that veteran
7. Access Intake again
8. Pick the wrong date (future and past)
9. Pick the wrong review lane
10. Verify the error message
11. Continue through happy path. 

Sceenshots:
<img width="1427" alt="screen shot 2018-01-12 at 2 18 44 pm" src="https://user-images.githubusercontent.com/23038505/34891794-e86deb92-f7a4-11e7-9506-7d483b7a5a59.png">
<img width="1423" alt="screen shot 2018-01-12 at 2 19 00 pm" src="https://user-images.githubusercontent.com/23038505/34891795-e87dcd28-f7a4-11e7-8544-3700e990e547.png">
<img width="1430" alt="screen shot 2018-01-12 at 2 19 29 pm" src="https://user-images.githubusercontent.com/23038505/34891796-e897690e-f7a4-11e7-86a5-7e2529933f2e.png">
