### ISSUE TITLE
Failing unique key constraint for in document.vbms_document_id in Appeal.find_or_create_documents!

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#3959]
We expect that the list of existing_documents we create in `Appeal.find_or_create_documents!()` will contain all of the documents that already exist in the database with any vbms_document_id from the list of fetched_documents. This error appears to have been triggered because that assumption was false. `if existing_documents.key?(document.vbms_document_id)` evaluated to false so we attempt `document.save!` however that fails to pass the table's unique key constraint on vbms_document_id.

As far as I can tell this could have happened for one of two reasons:
1. The list of existing_documents is incomplete (is the `includes()` call not actually doing the outer join we expect it to be doing?)
2. Additional documents have been added to the database between when we created the existing_documents variable and when we attempt to save the document in question.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/597/

> ActiveRecord::RecordNotUniqueapp/models/appeal.rb in block in find_or_create_documents!
> PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_documents_on_vbms_document_id"

# AC
1) Verify that when a user opens a never before opened case file for the first time in two tabs at once. Neither request should throw this error. Both should load without errors. (Note this will be easiest to reproduce on cases with a decent number of documents. At least 100. You can use a case you've already viewed if the entries in the Document table are cleared.)

**Comment by evankroske** [comment]
## Test Plan
- [ ] Find an appeal that hasn't been opened in Reader UAT
- [ ] Open it in two tabs at the same time
- [ ] Confirm that both appeals load successfully

**Comment by astewarttistatech** [comment]
@evankroske I am updating your test plan in addition to that this ticket is blocked due to #4036

**Comment by evankroske** [comment]
Verified that the Reader request succeeds. However, the request to Efolder fails, so the page displays an error. 🤷‍♂️
