### ISSUE TITLE
Update progress bar steps

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3964]
When processing any RAMP mail, I want to know all the pages I'll encounter, so I understand where I am in the overall flow.

## Acceptance Criteria
- Verify that there are 5 progress bar steps in the same order, no matter whether I'm processing a re-entry for a first-time opt-in: Select Form, Search, Review Request, Finish Processing, Confirmation
- Follow styleguide for design - past and current steps are darker gray

example
![image](https://user-images.githubusercontent.com/4042181/33624651-0f16de5c-d9c3-11e7-9cab-041b908ee7ff.png)

**Comment by abbyraskinUSDS** [comment]
If these titles are too long, use these:
- Select
- Search
- Review
- Finish
- Confirmation

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Intake 
2. Very that the progress bar's copy matches what is indicated in the AC and mocks. 

Screenshots: 
<img width="1430" alt="screen shot 2017-12-18 at 11 38 43 am" src="https://user-images.githubusercontent.com/23038505/34117126-b8ec0dec-e3e8-11e7-8e0a-fbeeb661eb98.png">
