### ISSUE TITLE
Search | Search copy update

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3965]
When processing any RAMP mail, I want to see the same search message, so the language is consistent regardless of which form I'm inputting. 

## Acceptance criteria
- The search copy is the same for either RAMP form (see copy below)
- Search is the second step

Copy:
**Search for Veteran by ID**
To continue processing this form, enter the Veteran’s 8 or 9 digit ID number into the search bar below.

![image](https://user-images.githubusercontent.com/4042181/33101632-fb33c706-cee6-11e7-8281-81f90bf46470.png)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Intake
2. Navigate to the Search page
3. Verify that the copy matches what is requested by mocks/AC. 

Screenshots: 
<img width="1430" alt="screen shot 2017-12-18 at 11 38 43 am" src="https://user-images.githubusercontent.com/23038505/34116973-291469ee-e3e8-11e7-92cd-0b1f29d1f0bf.png">
