### ISSUE TITLE
Finish Processing | Re-filing: select contentions

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#3966]
When processing a re-entry selection form, I want to  select the contentions the Veteran wants to review under RAMP, so their claim is reviewed accurately.

## Acceptance Criteria
- Verify that the list of contentions matches all contentions previously associated with that Veteran's RAMP EP (682 or 683).
- All selection requests (SC, HLR, appeal) from previous step navigate to this page.
- The user is required to select at least one checkbox - if they select the "finish intake" button without any checkboxes selected, display an in-line error 
- If the selection includes _at least one_ eligible contention, navigates to success confirmation page (#4064)
- If the user only selects the ineligible checkbox, navigate to the ineligible confirmation page (#4206)
- If this is an appeal request, navigate user to "appeal created" confirmation page (#4181)
- The selection should be saved in the database. There is some engineering discretion about how the schema should look.

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34265626-6fd943f0-e644-11e7-8310-a45cc0a8153f.png)

## Copy
- Finish processing RAMP Selection Form
- 1. Complete the following tasks outside Caseflow and mark when complete
- 1a. Upload the RAMP Selection Form to the VBMS eFolder and ensure the Document Type is Correspondence.
- 1b. Update the Subject Line with “RAMP Lane Selection”. 

- I’ve completed the above tasks outside Caseflow.

- 2. Review and select contentions 
- 2a. From the list of eligible contentions below, select the contentions requested for review on the Veteran’s form
- 2b. If the form contains any ineligible contentions, note via the checkbox at the bottom of the table.

**Comment by abbyraskinUSDS** [comment]
Need language from AMO for scenario where the form contains a new contention

**Comment by abbyraskinUSDS** [comment]
Add any addition language from SOP

**Comment by abbyraskinUSDS** [comment]
@shanear there's still an open question around how to message "unhappy paths" (e.g., they submit an issue that is not under RAMP) - I'm finalizing the handling/language for these with Jennifer today

**Comment by abbyraskinUSDS** [comment]
Split out alert into another ticket

**Comment by abbyraskinUSDS** [comment]
Note: if there are no contentions, display error earlier in the process (at search)

**Comment by abbyraskinUSDS** [comment]
- Select if applicable
- Select eligible RAMP contentions

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT/Chrome 

Steps to Validating: 
1. Access Ramp
2. Start a refile
3. Navigate to the Finish Processing page
4. Verify that the UI matches what is in the mocks. 

Screenshots:
![finish processing caseflow intake](https://user-images.githubusercontent.com/23038505/35054832-a1fc2856-fb7b-11e7-8a3a-8d5097a2a570.png)
