### ISSUE TITLE
[Frontend] Hearing Worksheet | Save before generating PDF

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3968]
If a user has unsaved edits on the hearing worksheet, they won't be displayed on the PDF. When a user clicks 'Save to PDF', it should call the save function, then generate the PDF. 

AC:
- All edits are displayed on the PDF.

**Comment by nolawi** [comment]
`https://github.com/department-of-veterans-affairs/caseflow/compare/issue3968?expand=1`
