### ISSUE TITLE
Styleguide | Refactor it all

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3971]
Relates to #1618 and this PR: https://github.com/department-of-veterans-affairs/caseflow/pull/3882

Other suggestions: https://github.com/department-of-veterans-affairs/caseflow/pull/3882#pullrequestreview-78297375

AC
* Ensure that the anchors for links and ID's for all headers use `kebab-case` in `StyleGuideContainers`: https://github.com/department-of-veterans-affairs/caseflow/pull/3882#pullrequestreview-78271293
* Ensure that all containers use `React.PureComponent` if they are classes and not functions: https://github.com/department-of-veterans-affairs/caseflow/pull/3882#discussion_r152435166

**Comment by astewarttistatech** [comment]
@Sjones352 where is this to be validated? Console or just going through PRs to see if stuff is merged?

**Comment by astewarttistatech** [comment]
Validated via PR Review and smoke test of Style Guide
