### ISSUE TITLE
Evaluate other caught exceptions for Rails/Sentry logging

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#3974]
In relation to department-of-veterans-affairs/appeals-deployment#1038

## Background

We found some AWS logs with 500 logs with no verbose information being logged or sent to Sentry related to Annotations in Reader.
```
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0255d3e9d34d6c7c7-172.30.86.71 [appeals.cf.ds.va.gov] [702aeb07-5748-484b-8b0e-620940c17767] [172.30.86.71] [BVAJRUTKIN ] [2017-11-21 11:02:09 -0500] Completed 500 Internal Server Error in 12ms (Views: 0.5ms | ActiveRecord: 4.7ms)
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-084c1163fa55135ad-172.30.86.14 [appeals.cf.ds.va.gov] [f5356a32-1250-4648-9925-f2f84755610b] [172.30.86.14] [BVAJRUTKIN ] [2017-11-21 11:02:15 -0500] Completed 500 Internal Server Error in 12ms (Views: 0.4ms | ActiveRecord: 4.9ms)
dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-02f0aec1dc14c2384-172.30.83.111 [appeals.cf.ds.va.gov] [b254152e-1d7e-49d4-8f1e-3bcdda14cf13] [172.30.83.111] [BVAJRUTKIN ] [2017-11-21 11:02:25 -0500] Completed 500 Internal Server Error in 16ms (Views: 0.4ms | ActiveRecord: 2.0ms)
```
We had to add some logging to the exception for the errors to properly show up in Sentry and rails logs:
```
  rescue_from ActiveRecord::RecordInvalid do |e|
    Rails.logger.error "#{e.message}\n#{e.backtrace.join("\n")}"
    Raven.capture_exception(e)
  end
```

## Next Steps

We need to evaluate to see if there are other 500 errors in the code base that are being caught and not properly being logged and sent to Sentry.

**Comment by nickheiner-usds** [comment]
Related discussion: https://github.com/department-of-veterans-affairs/caseflow/pull/3972/files#r152640694.

**Comment by nickheiner-usds** [comment]
Catching errors that we care about also hides them from New Relic.

We should either:

1. Allow errors to be caught by the global catcher.
2. Create a single utility function that logs to New Relic, Sentry, Prometheus, and whatever else we want to log to.

**Comment by mdbenjam** [comment]
I think the answer here is to never throw 500's ourselves. 500's should only be thrown by Rails. If we catch an error then we should not turn around and throw a 500.

To me the action items here are:
1. Ensure we're not explicitly throwing any 500's.
1. Removing the logging we just added, we don't want those events to go to sentry, we want them to not throw 500's.

**Comment by mdbenjam** [comment]
Removed all instances of throwing 500's. Closing this issue.
