### ISSUE TITLE
Styleguide | Side Navigation version 2.2 with sub nav

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3975]
**Story**
As a developer and designer, I want to easily and quickly find various components through the side navigation menu. 

For this ticket, add the specific styles for the side navigation. See AC below for details.

## AC
- [ ] When clicking the title, the side nav should expand to show the list of level two and jump to level 1 section. 
- [ ] Verify that all the side nav text links are in `$color-gray-dark` and when selected the text become bold and `$color-primary`

## Related tickets
#1618

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome

Steps to Validate: 
1. Access StyleGuide 
2. Navigate to the navbar
3. Click links in the navbar that will create other sublinks under them 
4. Check against AC. 

![navbarv2](https://user-images.githubusercontent.com/23038505/33489601-5edc8d22-d682-11e7-8261-3ff317413e96.gif)
