### ISSUE TITLE
v2 API does not return activation event

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3981]
## AC

* An appeal with a `case_review_date` should not return an `activation` event.
* The V1 API should be unaffected.

**Comment by kierachell** [comment]
-  appeal `3565120` (and/or appeals for that veteran) have TIDKTIME but I don't see the date show up. Is it scoped?

- where is the date?
<img width="400" alt="screen shot 2017-12-03 at 3 34 40 pm" src="https://user-images.githubusercontent.com/18075411/33529489-80b531a6-d83f-11e7-8c9f-e947fe591c41.png">

**Comment by cmgiven** [comment]
I think that's what we want to have happen. For the v2 API, we do _not_ want an activation event to be present. The key test is that it still should appear in the v1 API.

**Comment by kierachell** [comment]
- so there is not `case_review_date` event/status/whatever?

**Comment by cmgiven** [comment]
Not in the v2 API, no. It's been cut as an unnecessary and confusing intermediate step.

**Comment by kierachell** [comment]
**PASSED**

Then we good...as far as I can tell
