### ISSUE TITLE
Add transcript event to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3982]
## AC

* An appeal with a Board hearing (`HEARING_TYPE in ('C', 'T', 'V')`) that has been held (`HEARING_DISP = 'H'`) where a transcript was sent to the Veteran (`TRANSENT is not null`) should return a `transcript` event with the `TRANSENT` date.
* If any of the above conditions are not true, there should not be a `transcript` event.
* The V1 API should be unaffected.

**Comment by kierachell** [comment]
**PASSED**

<img width="314" alt="screen shot 2017-12-03 at 4 08 24 pm" src="https://user-images.githubusercontent.com/18075411/33529861-70e66790-d844-11e7-8d06-6850aeebee0d.png">
<img width="271" alt="screen shot 2017-12-03 at 4 09 52 pm" src="https://user-images.githubusercontent.com/18075411/33529862-70f5b40c-d844-11e7-9bc5-257d3601cc2a.png">
