### ISSUE TITLE
Add status object to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3984]
## AC
* It should have the attribute `type`, to be determined by logic specified below.
* It should have a `details` object, populated with different attributes determined by the `type` (unknown at this point, will be determined by content).
* The logic for `type` is as follows:

* If `BFMPRO = 'ADV'`:
  * If `BF41STAT is not null`:
    * If there is a scheduled, pending hearing: `scheduled_hearing`
    * If there is a pending hearing request (`BFHR in ('1', '2') and (BFHA = '3' or BFHA is null)`): `pending_hearing_scheduling`
    * Else: `on_docket`
  * If `BFD19 is not null`: `pending_certification`
  * If `BFDSOC is not null`: `pending_form9`
  * Else: `pending_soc`
* If `BFMPRO = 'ACT'`:
  * If there is a scheduled, pending hearing: `scheduled_hearing`
  * If `BFCURLOC = '49'`: `stayed`
  * If `BFCURLOC = '55'`: `at_vso`
  * If `BFCURLOC in ('19', '20')`: `opinion_request`
  * If `BFCURLOC in ('14', '16', '18', '24')`:
    * If there is a row in `DECASS` where `DEFOLDER` is equal to the `BFKEY`: `abeyance`
    * Else: `on_docket`
  * Else:
    * If there is a row in `DECASS` where `DEFOLDER` is equal to the `BFKEY`: `decision_in_progress`
    * Else: `on_docket`
* If `BFMPRO = 'HIS'`:
  * If `BFDC in ('1', '4')`: `bva_decision`
  * If `BFDC in ('A', 'B')`: `field_grant`
  * If `BFDC in ('9', 'F', 'Q', 'W')`: `withdrawn`
  * If `BFDC in ('G', 'X')`: `ftr`
  * If `BFDC = 'P'`: `ramp`
  * If `BFDC in ('8', 'E')`: `death`
  * If `BFDC = 'R'`: `reconsideration`
  * Else: `other_close`
* If `BFMPRO = 'REM'`: `remand`
* If `BFMPRO = 'MOT'`: `motion`
* If `BFMPRO = 'CAV'`: `cavc`

**Comment by kierachell** [comment]
```
If BFD19 is not null: pending_certification
If BFDSOC is not null: pending_form9
```

- I think you mean that this should be pending form9?
<img width="422" alt="screen shot 2017-12-03 at 5 00 31 pm" src="https://user-images.githubusercontent.com/18075411/33530298-93cde5f6-d84b-11e7-8674-ed682c175a9e.png">

- A bit confused:
<img width="333" alt="screen shot 2017-12-03 at 5 01 44 pm" src="https://user-images.githubusercontent.com/18075411/33530310-b1e39b12-d84b-11e7-81b4-c2e3bb34f8e7.png">

- Doesn't `withdrawn` also map to BFKEY having `W` in it?

- Spot checks:
<img width="364" alt="screen shot 2017-12-03 at 5 07 07 pm" src="https://user-images.githubusercontent.com/18075411/33530392-d2bd8f5e-d84c-11e7-83e5-ae03e95fb9a7.png">
<img width="364" alt="screen shot 2017-12-03 at 5 09 48 pm" src="https://user-images.githubusercontent.com/18075411/33530393-d2d3b4f0-d84c-11e7-8c48-ea148606b0a5.png">
<img width="379" alt="screen shot 2017-12-03 at 5 11 06 pm" src="https://user-images.githubusercontent.com/18075411/33530405-fbee834c-d84c-11e7-8b39-e1e7bc0e9094.png">

**Comment by cmgiven** [comment]
@kierachell: Anything preclude moving this back to validation?

**Comment by cmgiven** [comment]
Note that some of this logic has been superseded by #4080 and #4102. Let me know if I should update the AC.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Postman 
<img width="902" alt="screen shot 2017-12-18 at 10 59 04 am" src="https://user-images.githubusercontent.com/23038505/34117655-52afb9dc-e3ea-11e7-87e3-275d09188067.png">
<img width="1202" alt="screen shot 2017-12-18 at 11 00 34 am" src="https://user-images.githubusercontent.com/23038505/34117656-52bd714e-e3ea-11e7-92b3-57f1bee1cdeb.png">
<img width="910" alt="screen shot 2017-12-18 at 11 14 29 am" src="https://user-images.githubusercontent.com/23038505/34117657-52cbc898-e3ea-11e7-8b3d-fe504079b694.png">
