### ISSUE TITLE
Stub out all other attributes for the v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3985]
In order to get ready for v2 integration, we need to have stubbed out everything in the Swagger spec.

## AC
* The appeals object in the v2 api should include the following attributes:

```json
"aoj": "vba",
"programArea": "compensation",
"description": "",
"docket": null,
"issues": [],
"evidence": []
```

**Comment by kierachell** [comment]
**PASSED**

<img width="263" alt="screen shot 2017-12-03 at 4 10 56 pm" src="https://user-images.githubusercontent.com/18075411/33529876-95e11338-d844-11e7-8ac5-a996ac416a62.png">
<img width="386" alt="screen shot 2017-12-03 at 4 10 58 pm" src="https://user-images.githubusercontent.com/18075411/33529877-95f18060-d844-11e7-87ec-751db95432f0.png">
