### ISSUE TITLE
Add alerts to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#3987]
## AC
* When the api status (see #3984) is `pending_form9`, the `alerts` array in the API should contain an object with a `type` attribute of `form9_needed` and a `details` object with an attribute `due_date`, which should be equal to the notification date plus one year or the SOC date plus 60 days, whichever is greater. This alert should not appear if the due_date has already expired.
* When the appeal is active and there is a pending, scheduled hearing, it should have a `scheduled_hearing` alert, including as its `details` the `date` (the calendar date of the hearing) and `type` (video, central_office, travel_board).
  * If there are multiple such hearings, this should use the date of the earliest one.
* When the appeal is active and there is a hearing with the disposition "no show" (`'N'`) in the last 15 days, it should have a `hearing_no_show` alert with a `due_date` equal to the scheduled date of the hearing plus 15 days.
  * If there are multiple such hearings, this should use the max due date.
* When the api status is `on_docket` and there is a held hearing with a hold_open number of days greater than zero, it should have a `held_for_evidence` alert with a `due_date` equal to the date of the hearing plus hold_open days. This alert should not appear if the due_date has already expired.
  * If there are multiple such hearings, this should use the max due date.
* If an appeal has been issued a Board decision within the last 120 days (`BFDC in ('1', '3', '4')`), it should have a `cavc_option` alert with a `due_date` of the decision date plus 120 days.

**Comment by kierachell** [comment]
### Where is Form9 alert? for appeals of vet with appeal `965960`
<img width="275" alt="screen shot 2017-12-03 at 4 14 08 pm" src="https://user-images.githubusercontent.com/18075411/33529913-0a2957aa-d845-11e7-8cd0-591728ae54df.png">

### I think you put these things in `events` not `alerts`:
<img width="297" alt="screen shot 2017-12-03 at 4 16 39 pm" src="https://user-images.githubusercontent.com/18075411/33529935-7c0f94ba-d845-11e7-9311-5b59643d0b32.png">

**Comment by cmgiven** [comment]
Both of those are closed. We don't show the alert when the appeal is closed. I'll update the AC.

**Comment by cmgiven** [comment]
Actually, I'm gonna switch this to requirements-incorrect and take a look at it tomorrow.

**Comment by kierachell** [comment]
### I found one:

- Some kind of date scope?
<img width="402" alt="screen shot 2017-12-03 at 4 25 35 pm" src="https://user-images.githubusercontent.com/18075411/33530152-1f458092-d849-11e7-8b00-ec16bef3dd74.png">

**Comment by cmgiven** [comment]
Basically. The logic as written requires it to be in a particular status to show the alert. In some cases, like the ones you initially flagged, that makes sense, as they are closed and so don't require the alert. But I'm going to review and ensure that the logic is documented in the AC.

**Comment by cmgiven** [comment]
AC updated. New PR soon.

**Comment by cmgiven** [comment]
PR: #4061.

**Comment by astewarttistatech** [comment]
Current view:

Pending form 9: 
Scheduled Hearing: 
<img width="902" alt="screen shot 2017-12-18 at 10 59 04 am" src="https://user-images.githubusercontent.com/23038505/34115562-036d4ac0-e3e4-11e7-81a7-f82c41c78136.png">

The response just says "travel" instead of "travel_board" is that a problem?

Hearing No Show: 

On Docket:
<img width="1202" alt="screen shot 2017-12-18 at 11 00 34 am" src="https://user-images.githubusercontent.com/23038505/34115639-39b1d006-e3e4-11e7-9726-09bea43897de.png">

I don't see a due date, does that mean that it has passed?

Cavc_Option: 
<img width="1202" alt="screen shot 2017-12-18 at 10 24 58 am" src="https://user-images.githubusercontent.com/23038505/34115714-6677ada4-e3e4-11e7-891f-e5f4ffc01267.png">

**Comment by cmgiven** [comment]
on_docket is a status. You're looking for a held_for_evidence alert.
