### ISSUE TITLE
Admin | Header logo is wrong color

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3995]
### Problem:

Header logo is not purple like other dispatch logos:
<img width="501" alt="screen shot 2017-11-26 at 6 41 42 pm" src="https://user-images.githubusercontent.com/18075411/33245756-eb920ba4-d2d9-11e7-9056-d04bdeb03f8a.png">

### AC:

make it purple

**Comment by nolawi** [comment]
<img width="435" alt="screen shot 2018-07-06 at 11 03 00 am" src="https://user-images.githubusercontent.com/1745984/42385973-41592e7e-810c-11e8-8430-308e4fa03d87.png">
looks like this is resolved
