### ISSUE TITLE
Caseworker:  EC Task:  Release all tasks at Midnight

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#400]
As a Caseworker, I want to have all assigned tasks that have not been completed by midnight to be automatically released and made available for processing so that no one task item is held hostage by a given caseworker.

### Acceptance Criteria

1. Verify that for any assigned tasks that are in a state of "In Progress", it's assignment is released at midnight.

**Comment by shanear** [comment]
@astewarttistatech @sharonwarner since dev gets reseeded on every deploy, this one might be a bit tricky to test. I'll test it tonight.

**Comment by shanear** [comment]
I missed the window on this two nights in a row. Gonna be really trick to test in Dev. Going to test in UAT.

**Comment by shanear** [comment]
tested this over the weekend. Worked!
