### ISSUE TITLE
Add additional information to degradation banner

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#4002]
If I were a caseflow user, I think I would like to know more information about why the degradation banner is being displayed. This would allow users to do some amount of investigation before contacting support and enable them to have more information when they do eventually contact support.

Imagine the scenario where we send an email to reader users that VVA is inaccessible so only VBMS documents will be available in reader. However, VBMS then goes down and triggers the service degradation banner. The users may assume that the reason the banner is being shown is because of the VVA outage, and continue to attempt to user reader and become frustrated when VBMS documents are inaccessible as well.

I figure there are many ways to address this issue (include additional text in the banner with why the banner was triggered), but maybe the quickest solution would be to just add a link in the banner to caseflow-monitor.

AC:
* Provide caseflow users with information about why we are displaying the service degradation banner

**Comment by laurjpeterson** [comment]
Closing because we now have Caseflow StatusPage
