### ISSUE TITLE
Blurry Images in Reader

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4005]
We got a support ticket that a user looked a document that was blurry, but was not blurry in VBMS. Originally thought it might be a document we converted from TIFF -> PDF, but this user did not have VVA docs on. Only one report so far.

## Support tickets
department-of-veterans-affairs/appeals-support#922

**Comment by abbyraskinUSDS** [comment]
Closing this out - we haven't heard of this happening again.
