### ISSUE TITLE
Caseworker Landing:  Establish Next Claim:  Retrieve incomplete task

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#401]
As a Caseworker, if I have an incomplete Establishment Claim (EC) Task assigned to me, when I click "Establish Next Claim" button it should be send me to that task instead of assigning a new task so that I can cheat the system.

### **Acceptance Criteria**

1. Verify that when the "Establish Next Claim" button on the Caseworker Landing page is clicked and there is an incomplete task assigned to me, the incomplete task is retrieved for working on instead of a new task.

### Sub-Tasks

- [ ] QA discovery and scripting

**Comment by nikitarockz** [comment]
**Duplicate Issue:**  It refers to the frame that is already captured for Certification.

**Comment by shanear** [comment]
@astewarttistatech you got this one :smile: let @sharonwarner know if you have any questions about how to test it in dev.

**Comment by astewarttistatech** [comment]
Failed. Link to establish new claim takes me to a page not found page. See attached 
<img width="1092" alt="screen shot 2016-11-30 at 1 47 57 pm" src="https://cloud.githubusercontent.com/assets/23038505/20766271/be55cff6-b703-11e6-8230-40a19a58a2da.png">

**Comment by astewarttistatech** [comment]
This has failed due to it has the same response with both a "canceled" and "no work history" status on cases.

**Comment by astewarttistatech** [comment]
Blocked until further data is created.
