### ISSUE TITLE
[Backend] Daily Docket | Separate backend call 

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#4016]
AC:
- Old functionality should work as expected (loading upcoming hearings, loading daily docket, editing daily docket)
- Daily docket page sends request to backend which populates dailyDocket in the redux state
- Upcoming hearings page sends request to backend which populates upcomingHearings in the redux state

**Comment by kierachell** [comment]
**PASSED**
- hearingworksheet log:
```
**PASSED**
```
STARTED VACOLS: load_vacols_data 3000045
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500]   VACOLS::Case Load (6.1ms)  SELECT  "VACOLS"."BRIEFF".* FROM "VACOLS"."BRIEFF" WHERE "VACOLS"."BRIEFF"."BFKEY" = :a1 AND ROWNUM <= 1   [["b
fkey", "3000045"]]                                                                                                                                                                                          dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.
245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500]   VACOLS::Folder Load (20.3ms)  SELECT "VACOLS"."FOLDER".* FROM "VACOLS"."FOLDER" WHERE "VACOLS"."FOLDER"."TICKNUM" IN ('3000045')          dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.
245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500]   VACOLS::Correspondent Load (8.2ms)  SELECT "VACOLS"."CORRES".* FROM "VACOLS"."CORRES" WHERE "VACOLS"."CORRES"."STAFKEY" IN ('CK1223229')  dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.
245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500] FINISHED VACOLS: load_vacols_data 3000045:   0.010000   0.000000   0.010000 (  0.037844)                                                    dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.
245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500]   VACOLS::Staff Load (2.4ms)  SELECT  "VACOLS"."STAFF".* FROM "VACOLS"."STAFF" WHERE "VACOLS"."STAFF"."SLOGID" = :a1 AND ROWNUM <= 1   [["slogid", nil]]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500] STARTED VACOLS: HearingRepository.load_vacols_data: 568135
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500]   VACOLS::CaseHearing Load (29.0ms)  SELECT  VACOLS.HEARING_VENUE(vdkey) as hearing_venue, staff.sdomainid as css_id, "VACOLS"."HEARSCHED"."
HEARING_DISP", "VACOLS"."HEARSCHED"."HEARING_PKSEQ", "VACOLS"."HEARSCHED"."HEARING_DATE", "VACOLS"."HEARSCHED"."HEARING_TYPE", "VACOLS"."HEARSCHED"."NOTES1", "VACOLS"."HEARSCHED"."FOLDER_NR", "VACOLS"."HEARSCHED"."VDKEY", "VACOLS"."HEARSCHED"."AOD", "VACOLS"."HEARSCHED"."HOLDDAYS", "VACOLS"."HEARSCHED"."TRANREQ", "VACOLS"."HEARSCHED"."TRANSENT", "VACOLS"."HEARSCHED"."REPNAME", "VACOLS"."HEARSCHED"."ADDON"
, "VACOLS"."HEARSCHED"."BOARD_MEMBER", "VACOLS"."HEARSCHED"."MDUSER", "VACOLS"."HEARSCHED"."MDTIME", "SATTYID", "BFREGOFF", "BFSO", "BFCORKEY", "BFDDEC", "BFDC", staff.slogid, corres.snamef, corres.snamemi, corres.snamel, corres.sspare1, corres.sspare2, corres.sspare3 FROM "VACOLS"."HEARSCHED" left outer join vacols.staff on staff.sattyid = board_member left outer join vacols.brieff on brieff.bfkey = fold
er_nr left outer join vacols.corres on corres.stafkey = bfcorkey WHERE "VACOLS"."HEARSCHED"."HEARING_TYPE" IN ('V', 'T', 'C') AND "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a1 AND ROWNUM <= 1   [["hearing_pkseq", 568135]]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.245] [CASEFLOW_317 caseflow@va.gov] [2017-12-13 07:59:07 -0500] FINISHED VACOLS: HearingRepository.load_vacols_data: 568135:   0.000000   0.000000   0.000000 (  0.038560)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70.245] [CASEFLOW_317 caseflow@va.gov] [active_model_serializers] [2017-12-13 07:59:07 -0500]   WorksheetIssue Load (1.6ms)  SELECT "worksheet_issues".* FROM "worksheet_issues" WHERE "worksheet_issues"."del$
ted_at" IS NULL AND "worksheet_issues"."appeal_id" = $1  [["appeal_id", 54692]]                                                                                                                             dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0b6fe8ac65044e75b-172.30.70.245 [appeals.cf.uat.ds.va.gov] [83a84df6-990a-444a-b801-4cc210a95170] [172.30.70$
245] [CASEFLOW_317 caseflow@va.gov] [active_model_serializers] [2017-12-13 07:59:07 -0500]   WorksheetIssue Load (1.6ms)  SELECT "worksheet_issues".* FROM "worksheet_issues" WHERE "worksheet_issues"."dele
ted_at" IS NULL AND "worksheet_issues"."appeal_id" = $1  [["appeal_id", 54713]]
```

<img width="843" alt="screen shot 2017-12-13 at 7 59 11 am" src="https://user-images.githubusercontent.com/18075411/33940092-b5fd0ac0-dfdb-11e7-827a-9fc10379c1b9.png">
<img width="1241" alt="screen shot 2017-12-13 at 7 59 22 am" src="https://user-images.githubusercontent.com/18075411/33940093-b628f072-dfdb-11e7-8a2f-4a6dec41aeb6.png">

- but I honestly have no idea what I am looking for
