### ISSUE TITLE
Nil document ~receipt date causing Casefolder not to load

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#4019]
A support issue has been submitted that a user cannot view a CaseFolder and they just see a loading screen and nothing happens. 

https://github.com/department-of-veterans-affairs/appeals-support/issues/915

After some minimal investigation in the console log: 
<img width="1280" alt="screen shot 2017-11-22 at 2 36 00 pm" src="https://user-images.githubusercontent.com/1976755/33399919-43c17040-d522-11e7-99ca-a8b4b4e8d222.png">

This console log led to finding out that this error is coming from the Highlighter component from `react-highlight-words`. After looking into the Highlight component in reader, it looks like there are not default props for children or searchQuery. 

Also, further looking into the documents fetched from eFolder, `receivedAt` is a nill value. This is one of the strings being passed into the Highlight component.

## AC: 
* Add documents with nil receipt dates
* Open Reader case folder with these documents with nil values
* Expect the Folder to properly load without any errors

**Comment by mdbenjam** [comment]
This was fixed on 11/29.
