### ISSUE TITLE
De-italicize "Specify file if applicable" box title

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#402]

**Comment by webinista** [comment]
@KHarshawat Is this issue still applicable given the latest mock-up? If not, can you close this issue?
![](https://cloud.githubusercontent.com/assets/6335546/11909721/a399f8fc-a59f-11e5-9790-a61fd624e362.png)

**Comment by KHarshawat** [comment]
Hey @webinista did you already make the change? If so would you mind sending me before and after screenshots with and without italicized text?

**Comment by KHarshawat** [comment]
Or you could just let me know what you think looks better :) and we'll go with that :)

**Comment by webinista** [comment]
I made the change, but I don't think I ever created a pull request for the branch. Here are the before and after screen shots.

**Before:**

![screen shot 2015-12-22 at 12 50 02 pm](https://cloud.githubusercontent.com/assets/354277/11962024/9f4a4686-a8aa-11e5-961c-fc192d440fc2.png)

**After:**

![screen shot 2015-12-22 at 12 50 21 pm](https://cloud.githubusercontent.com/assets/354277/11962033/ab6a4966-a8aa-11e5-9e32-d96e5dc71105.png)

I like the italics, to be honest. But the last decision we made -- before receiving the new mockups -- was to remove them.

**Comment by KHarshawat** [comment]
Ok, let's keep 'em! Closing the issue :)
