### ISSUE TITLE
Hearing Worksheet: Update Issue Label

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4021]
Change how issues are displayed, so that each Appeal Stream has it's own section, instead of a single Issue section.

## AC
1. Remove 'Issues' label and replace it with 'Appeal Stream [#] above the single line
1. Style 'Appeal Stream [#]' in bold
1. Remove 'APPEAL STREAM [#] from below the single line
2. Repeat 'Appeal Stream [#]' styling for subsequent appeal streams

## Mocks
_**Current:**_
<img width="569" alt="screen shot 2017-11-29 at 5 57 43 pm" src="https://user-images.githubusercontent.com/4975959/33403555-d1f90222-d52e-11e7-94fa-2a5b355ba261.png">

**_Desired_**
<img width="514" alt="screen shot 2017-11-29 at 5 42 36 pm" src="https://user-images.githubusercontent.com/4975959/33403564-debc1198-d52e-11e7-842d-b2b90958a7f4.png">

**Comment by nolawi** [comment]
@lakohl should appeal level be the same h2 as relevant docs

<img width="1017" alt="screen shot 2017-12-08 at 12 59 54 pm" src="https://user-images.githubusercontent.com/1745984/33781560-1a964260-dc23-11e7-8234-1ce029b7f97c.png">

**Comment by lakohl** [comment]
@nolawi thanks for asking! We are moving towards the design below (incrementally). So Having Appeal Stream 1 show as an h2 for now is fine.

<img width="516" alt="screen shot 2017-12-08 at 2 36 33 pm" src="https://user-images.githubusercontent.com/4975959/33782089-44c85fb2-dc25-11e7-9d31-c1d2b0e2779a.png">

**Comment by astewarttistatech** [comment]
**Failed** @nolawi 

Current View: 
<img width="1308" alt="screen shot 2017-12-12 at 9 41 08 am" src="https://user-images.githubusercontent.com/23038505/33890260-b6956eca-df20-11e7-9fa7-d2f841918162.png">

**Comment by nolawi** [comment]
can we retest now.. it seems like a it was tested before it was deployed

**Comment by astewarttistatech** [comment]
**FAILED** 

Current State: 
<img width="1308" alt="screen shot 2017-12-12 at 9 41 08 am" src="https://user-images.githubusercontent.com/23038505/33890260-b6956eca-df20-11e7-9fa7-d2f841918162.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Hearings 
2. Open a Hearing Worksheet
3. Navigate to the Appeal Stream (Issues)
4. Verify that the labels have been changed.

Screenshots:

<img width="1266" alt="screen shot 2017-12-19 at 11 14 22 am" src="https://user-images.githubusercontent.com/23038505/34166910-35088368-e4ae-11e7-996d-9f99c45e66eb.png">
