### ISSUE TITLE
Navigation | Help | Create Intake Help page

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4027]
As a Case Supporter, I would like to be able to go to a Help page when I don’t understand something or need more information so that I can quickly find answers to my questions.  
 
## Acceptance Criteria
1. Verify that when the Help link is clicked from the Username Menu in the Navigation bar, the ‘Intake Help’ page is displayed.
1. Verify that the new Help page has been created with the following sections and their sub-copy:

Section | Header | Sub-copy
-- | -- | --
Introduction | Welcome to the Intake Help Page! | Here you will find Training Videos and answers to the   Frequently Asked Questions (FAQs) for Intake, as well as links to the Training Guide and the Quick Reference Guide. These items are provided to assist you as you access and use Intake. If you require further assistance after reviewing these items, please contact the Caseflow Product   Support Team by phone (1-844-876-5548) or email (caseflow@va.gov). We look forward to assisting you.    
Training Videos | Training Videos | Coming Soon! 
FAQs | Frequently Asked Questions |  (No Copy)
FAQ Answers | (No header) |  

1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "FAQs" is a hyperlink to the Frequently Asked Questions section.
1. Verify in the Frequently Asked Questions section, it contains listing of all questions. (Refer to [Intake FAQs_Dec2017](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake%20_FAQs_Dec2017.pdf))
1. Verify that in the FAQ Answers section, it contains all questions and their answer. (Refer to [Intake FAQs_Dec2017](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake%20_FAQs_Dec2017.pdf))
1. Verify that each question in the FAQ section is a hyperlink to its answer.
1. Verify that clicking on 'Back to top' takes you to the top of the page.

## Mocks
Same as Dispatch mocks, but replace "Dispatch" with "Intake".

![dispatch help page](https://cloud.githubusercontent.com/assets/23316107/24629755/2d27b224-1888-11e7-9029-d0a7096c3860.png)

# Related Stories
Intake | FAQs | Develop/update questions - Prototype deliverable [#103](https://github.com/department-of-veterans-affairs/appeals-training/issues/103)

**Comment by wturne** [comment]
@nikitarockz Updated engineering story with title and link to Caseflow Intake FAQs.  

[Intake _FAQs_Dec2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1553539/Intake._FAQs_Dec2017.pdf)

**Comment by abbyraskinUSDS** [comment]
@Sjones352 it's all you!

**Comment by astewarttistatech** [comment]
**PASSED**


Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access /help
2. Select "Intake Help"
3. Validate the Intake Help page
![intakehelp](https://user-images.githubusercontent.com/23038505/34780162-6146e5c0-f5f0-11e7-8668-f7407163a673.png)
