### ISSUE TITLE
Navigation | Help | Update links to Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4028]
As a Project Manager, I would like to have clearly visible and accessible links to both the Training Guide and Quick Reference Guides displayed on the Help Page, so that the users can obtain additional detailed information on how to use Intake.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. 
[Intake_Training.Guide_April2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_April2018.pdf)
1. Verify that when the pdf "Training Guide" is displayed in the new tab, the pdf name displayed is "Caseflow Intake Training Guide". (Refer to **_Displayed PDF Name_** mock)
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following .pdf is displayed in a new tab. [Intake_Quick_Reference_Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Quick_Reference_Guide_Apr2018.pdf)
1. Verify that when the pdf "Quick Reference Guide" is displayed in the new tab, the pdf name displayed is "Caseflow Intake Quick Reference Guide". (Refer to **_Displayed PDF Name_** mock)

**_FAQ Answer Section_** 

_"What is Caseflow Intake?"_
1. Verify that in the answer, the text "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. 
[Intake_Training.Guide_April2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_April2018.pdf)

_"What if I still need help?"_
1. Verify that in the answer the text "FAQs" is a hyperlink to the “Frequently Asked Questions” section.
1. Verify that in the answer the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" in the answer is clicked, the following pdf is displayed in a new tab. 
[Intake_Quick_Reference_Guide_](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Quick_Reference_Guide_Apr2018.pdf)

1. Verify that in the answer, the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. 
[Intake_Training.Guide_April2018.pdf](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_April2018.pdf)

## Mocks
These mocks represent a simulation as to what each should look like.

**_Help Page - Introduction section requiring change_**
![image](https://user-images.githubusercontent.com/23038386/39582046-005ca14a-4ebb-11e8-9b23-9f84080acc2d.png)

**_Help Page - FAQ Answers section:  First Question requiring change_**
![image](https://user-images.githubusercontent.com/23038386/39582081-193561f2-4ebb-11e8-842c-288b5d923f81.png)

**_Help Page - FAQ Answer section:  Last Question requiring change_**
If you require further assistance after reviewing the [FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake%20_FAQs_Jan2018.pdf), [Quick Reference Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Quick_Reference_Guide_Apr2018.pdf), or [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_Mar2018.pdf), please contact the Caseflow Product Support team by phone (1-844-876-5548) or email (caseflow@va.gov).  We look forward to assisting you.  (See screenshot)
![image](https://user-images.githubusercontent.com/23038386/39582148-50d01198-4ebb-11e8-88b8-9d62611f8696.png)

**_Displayed PDF Name_**
![image](https://user-images.githubusercontent.com/23063044/39588943-dab2371a-4eca-11e8-849d-0bc257f643ac.png)

# Related Stories
**_Engineering Pre-requisite_**
Help | Create Intake Help page #4027 

**_PM/Training Issues_**
IP | Intake | Create Engineer Story for Training Material Additions [#1685](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1685)
Intake | Quick Reference Guide | Develop/Update guide - Prototype deliverable [#81](https://github.com/department-of-veterans-affairs/appeals-training/issues/81) 
Intake | Training Guide | Develop guide - Prototype deliverable [#98](https://github.com/department-of-veterans-affairs/appeals-training/issues/98)

**Comment by wturne** [comment]
Reviewed issue and verified that the proper documents are referenced and identified.

**Comment by wturne** [comment]
Updated links for Training Guide and Quick Reference Guide.  

[Intake_Training.Guide_Mar2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1971599/Intake_Training.Guide_Mar2018.pdf)

[Intake_Quick_Reference_Guide_Apr2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1971600/Intake_Quick_Reference_Guide_Apr2018.pdf)

**Comment by nikitarockz** [comment]
@leikkisa I put Feature Definition on this because @wturne is making a couple more changes to the Training Guide.  He should have it completed shortly.

**Comment by leahbannon** [comment]
looks good - I also added a missing space with #5462
