### ISSUE TITLE
Caseworker:  Adding Cases with no decisions to Managers report

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#403]
As a Caseworker, I only want an Establishment Claim (EC) task created when an appeal has an available decision document. Otherwise continue checking for the document each day.

# Acceptance Criteria
1. Verify that an Establishment Claim Task is created only when an appeal has a decision document in VBMS.
2. Verify that when an appeal can not be associated with a decision document, the appeal is included in the next run of the task creation process.

# Related Stories

**Comment by nikitarockz** [comment]
Duplicate:  Already captured in as a part of the certification frame.

**Comment by lakohl** [comment]
Hold on this. Abby reports that AMC is supposed to create an EP even if there is no signed decision in VBMS.

**Comment by KHarshawat** [comment]
@abbyraskin assigning to you ... would you mind commenting when you find out if we should only show appeals with decisions that have been uploaded to VBMS?

Also related to https://github.com/department-of-veterans-affairs/caseflow/issues/405#issuecomment-263734810

**Comment by abbyraskin** [comment]
Yep. Will let you know when I have clarity.

**Comment by joofsh** [comment]
@nikitarockz The latest comments say this is on hold. Is this truly "ready for dev"? Are we continuing in this direction?

CC @abbyraskin @KHarshawat @lakohl

**Comment by nikitarockz** [comment]
Agreed.  I am going to move this one back.

**Comment by shanear** [comment]
@lakohl blocked until we answer whether VACOLS decisions can be used for the Claims Establishment process. My understanding was that this was not acceptable.

**Comment by lakohl** [comment]
Need to confirm with Nicholas re: pulling decisions from VACOLS vs. VBMS.

**Comment by lakohl** [comment]
@nikitarockz We are going to look for the doc in VBMS. This issue is for Milestone 2. For Milestone 1 - if there is no decision doc in VBMS for that claim we will surface a message where the decision would be saying 'there is currently no decision document in VBMS in the date range x-y.' 
@abbyraskin Do you you agree we should look for a decision withing a date range (how many days?) or should we just look for a specific date?  As soon as we make a call I can mock it.
We will also need to make an issue for a scenario when 2 decisions have the same date.

**Comment by abbyraskin** [comment]
@lakohl we spoke about this briefly in person but wanted to follow up and see if any of the requirements changed? it sounded like we're going to truly handpick cases for milestone 1 so the "no signed decision" view might not be necessary after all.

for milestone 2...on the backend, we may want to use a date range of +/-3 days in case the VBMS scan/upload date doesn't exactly match the decision date in VACOLS (so our Denise list is accurate). 3 days seems to be the typical lag between decision and scan, so we can start there and adjust as needed.

**Comment by lakohl** [comment]
See rule in above comment. For milestone 1 we will handpick cases with VBMS decisions. We will never assign a claim Establishment task to a case that does not have a VBMS decision.

**Comment by nikitarockz** [comment]
Duplicate Item:  
Refer to #637
