### ISSUE TITLE
Reader Help | FAQs | Add new question/answers 

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4030]
As a Project Manager, I would like to add new questions and answers for those questions raised during the various training sessions so that all the users will have the latest answers.

## Acceptance Criteria
**_Frequently Asked Questions section_**
1. Verify in the following 6 new questions have been added.   (Refer to [Reader FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_FAQs_Dec2017.pdf))
     -	Can the Comments in Reader be sorted by date?
     -	What does the Case Summary category in Reader represent?
     -	Why do I get the, “Drat. You are not authorized to use this Caseflow application.” message when I try to log into Reader?
     -	Why do I get the, “Drat. You are not authorized to use this PART of Caseflow yet.” message when I try to log into Reader?
     -	Why do I get the, “Drat. You are not authorized to use eFolder Express.” message when I try to log into Reader?
     -	How do I bookmark Reader?
1. Verify that each new question is a hyperlink to its answer in the FAQ Answer section.
1. Verify the listing of questions is represented in the following order.  (Refer to [Reader FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_FAQs_Dec2017.pdf))

>    1.	What is Caseflow Reader?
>     2.	How was Reader developed?
>     3.	How do I access Reader?
>     4.	Why do I get the, “Drat. You are not authorized to use this Caseflow application.” message when I try to log into Reader? 
>     5.	Why do I get the, “Drat. You are not authorized to use this part of Caseflow yet.” message when I try to log into Reader?  
>     6.	Why do I get the, “Drat. You are not authorized to use eFolder Express.” message when I try to log into Reader?  
>     7.	How do I bookmark Reader?  
>     8.	How do I start a case in Reader?
>     9.	Where do the documents in Reader come from?
>     10. Can I view Virtual VA documents in Reader?
>     11. How do I search for a document in Reader? 
>     12. How do I know which documents I have read on the Claims Folder page? 
>     13. How do I open a document in a separate tab?
>     14. How do I add a comment to a document in Reader?
>     15. How do I delete comments in Reader?
>     16. How do Issues Tag(s) work?
>     17. Can I sort documents by Issues Tag(s)?
>     18. How do I complete a case in Reader?
>     19. What happens if I cannot complete a review in one sitting? 
>     20. Can the Comments in Reader be sorted by date?  
>     21. What does the Case Summary category in Reader represent?
>     22. What should I do if I encounter problems?
>     23. How can I share my suggestions for improving Reader? 
>     24. What if I still need help? 

**_FAQ Answer section_**
1. Verify that all newly added questions and their answer are displayed.  (Refer to [Reader FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Reader/Reader_FAQs_Dec2017.pdf)) 
1. Verify that any answer with an image is of jpg format.
1. Verify that the answer copy to the question **_"Where do the documents in Reader come from?"_** has been updated to the following:

     > Reader retrieves documents from the VBMS eFolder. Documents in the Claims Folder are refreshed
from VBMS every three hours. If VBMS is down, Reader still retrieves documents to ensure that
documents are always readily available.

## Mocks
**_Current Help Page - update FAQs section_**
![image](https://user-images.githubusercontent.com/23063044/34418000-9bd96d88-ebc9-11e7-945d-fc6ea5e95dca.png)

**_Answer Section Sample - Update with new questions and changed answers_**
![image](https://user-images.githubusercontent.com/23063044/34418073-f9d2dff0-ebc9-11e7-8cf9-8af6e826a9eb.png)

# Related Story
**_PM/Training Issues_**
Reader | FAQs | Update questions based on rollouts – Production Deliverable #89

**_Engineering Prerequisite_**
Reader Help | Add link to display Training Guide and Quick Reference Guide #3147

**Comment by wturne** [comment]
Updated issue with current Reader FAQs reference.  

[Reader_FAQs_Dec2017.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1587749/Reader_FAQs_Dec2017.pdf)
