### ISSUE TITLE
Category error state looks weird

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4034]
When there is a server error with updating a category, the error state messes up the UI:
 ![screen shot 2017-11-30 at 11 12 55 pm](https://user-images.githubusercontent.com/3885236/33467658-15a4f36e-d624-11e7-9065-c484fea7ee7d.png)

**Comment by hschallhorn** [comment]
@mdbenjam Any guidance on reproducing this error message?

**Comment by hschallhorn** [comment]
<img width="382" alt="screen shot 2018-12-17 at 11 22 52 am" src="https://user-images.githubusercontent.com/45575454/50100736-26b94b80-01ef-11e9-9488-a6607aa69579.png">
Still tracking down where to test how it looks with a comments error, but this is what I've got with the tags and category errors.

**Comment by hschallhorn** [comment]
<img width="258" alt="screen shot 2018-12-17 at 11 54 28 am" src="https://user-images.githubusercontent.com/45575454/50102633-8f0a2c00-01f3-11e9-98d0-984d6f8ee177.png">
Annnnnnd comments! Pushing changes and submitting a PR to close this.
