### ISSUE TITLE
Reader Search | Navigating to mark breaks if user scrolls away from page

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4039]
When navigating between marks on a page, if a user scrolls away so the page is no longer rendered, navigating to the next mark does not work.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod  | Chrome 

Steps to Validate: 
1. Access Reader > Document
2. Start a search
3. Navigate til the page the search started on is no longer rendered
4. Select "->" to see the next result in the search. 
5. Verify that this brings you to the next result in the document. 

Screenshots: 
![readersearch](https://user-images.githubusercontent.com/23038505/33725688-e279a846-db40-11e7-9616-03e9b27264ea.gif)
