### ISSUE TITLE
Ensure value for REPADDRESS2 is <=50 characters

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4040]
A user couldn't complete certification because the value we were trying to update a vacols field to was too long. See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/668/

We should be able to use http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-truncate to keep all strings to 50 chars or less for this field. (we have never seen this error before for any other field, so I'm comfortable just changing this for now) `PowerOfAttorney.repository.get_address_one_and_two` might be a good place for the modification.

## AC
- The value we attempt to update VACOLS' REP.REPADDRESS2 with should be no more than 50 chars in length, regardless of the length of the values we get from BGS

**Comment by askldjd** [comment]
I don't have a good feel for it. Truncating is a bit risky. We lose data.

Here's a crazy thought. Why not relax the VACOLS contraint to line it up with BGS? We have root access and we can talk to Jed about it as well.

**Comment by amprokop** [comment]
Hmm. If that's an option, that'd certainly be better. As far as I know, we have only seen this error for one appeal, and it happened yesterday when we tried to put 51 characters in a 50 max field. How difficult would it be to deploy this change to VACOLS? My only concern is spending a ton of time on a really rare error if there's a "good enough" fix.

**Comment by askldjd** [comment]
Added @kierachell since he also has VACOLS admin permission.

**Comment by amprokop** [comment]
Some context: 

As of today, roughly 22,000 v2 certifications have been started. If we trust sentry to report errors, this error has happened in only one of them. Certification has a bounded lifespan at this point. Once VAIMA hits, only legacy appeals will be certified using certification. Since there are about 500k open appeals, and many of them will probably opt into the new system, it's super unlikely that certification will process more than 500k appeals in the future, and probably much fewer given what we know about VA wanting to have folks opt in. 500k/22k = 22, so perhaps we expect this error to happen between 5 and 100 times in the future.

Next, the way that addresses are stored in VACOLS is already lossy and requires human interpretation/intervention to understand. We stuff names in address field, concatenate lines, etc. Staff are used to looking outside of VACOLS to find addresses (for non-Attorney/Agent POAs, they need to do so all the time)

With these considerations in mind, I think it's best to find a low-effort solution and move on. If relaxing the VACOLS constraint will take more than an hour or two total, I'm not convinced it's the best investment. Lmk your thoughts. @askldjd @kierachell

**Comment by kierachell** [comment]
It's just an `alter table` command (I'll double the size). I would have to do it during off-hours (it waits for table lock) but it won't take more than 10 minutes.

Leave a 👍 and I'll do it tonight.

**Comment by amprokop** [comment]
👍  cool, didn't know we had this kind of autonomy. thanks!

**Comment by kierachell** [comment]
```
alter table VACOLS.REP modify REPADDR2 varchar2(100);

Table altered.

SQL> commit;

Commit complete
```

### TEsted:
```
update REP set REPADDR2 = '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'
where REPKEY = '*******';
update REP set REPADDR2 = '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' where REPKEY = '******'
                          *
ERROR at line 1:
ORA-12899: value too large for column "VACOLS"."REP"."REPADDR2" (actual: 170,
maximum: 100)
```

**Comment by askldjd** [comment]
I would ping Jed about this to keep him in sync. But in general, since Caseflow will deprecate VACOLS app, I think it is a good idea to assume that we have full ownership over VACOLS DB (at least the Appeals table). We should feel comfortable modifying its schema when it makes sense.

**Comment by kierachell** [comment]
yeah, I messaged him last night.

**Comment by amprokop** [comment]
Awesome. Thanks for the clarity.

**Comment by askldjd** [comment]
@kierachell Does this have any impact on DMS or scripts around DMS like VACOLS UAT?

**Comment by kierachell** [comment]
As far as I've checked
- VACOLS Prod
- VACOLS Prod DMS replica
- VACOLS Dev
- VACOLS Dev DMS replica
- VACOLS UAT copy
- VACOLS bake snapshots

all have the new schema propagated already

**Comment by amprokop** [comment]
Cool, sounds good!
