### ISSUE TITLE
Reader | Fix scrolling to correct page on iterate search results

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4041]
Connects #4038

`PdfPFile.getPageIndexofMatch` was updated to return the index of the matched page within `matchesPerPage`, which only contains pages with matches. It should return the index of the page within the array of all pages.

## AC
* Load document, run search for term not present on every page.
* Go to the last result in a page before a page that doesn't have the search term (i.e., searching for "veteran", get matches returned on pages 1 and 3, go to last result on page 1).
* Tick up to next search result. Document should jump to next page containing a match, not the next page in the document.

**Comment by astewarttistatech** [comment]
Blocked due to #4036 
Current View:
<img width="1319" alt="screen shot 2017-12-04 at 9 51 38 am" src="https://user-images.githubusercontent.com/23038505/33558851-f5deb5c6-d8d8-11e7-882d-942fb3ea215d.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Reader
2. Open a document
3. Search for a term not found on every page
4. When navigating through search results, verify that you are skipping pages to where the next result is, not just going to the next page in the document. 

Screenshots: 
![readersearch](https://user-images.githubusercontent.com/23038505/33725886-8521d7a8-db41-11e7-96fe-20be449fb7e1.gif)
