### ISSUE TITLE
Review Decision: Special Issues checking

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4044]
Review Decision: Special Issues are checked and unchecked when the user clicks near the special issue label, but outside the box.

**AC**
Check/Uncheck a Special Issue only when the user clicks on the checkbox or the text

**Current**
Today the user can click far to the right of and outside the checkbox to check/uncheck an issue. This means that they could accidentally make an unintended selection.

**Comment by lakohl** [comment]
@sharonwarner I can provide more context on this.

**Comment by lakohl** [comment]
@sharonwarner do you think we could look into this during this sprint?

**Comment by nolawi** [comment]
PR added to[ caseflow commons](https://github.com/department-of-veterans-affairs/caseflow-commons/pull/127)

**Comment by nolawi** [comment]
can be tested in style guide

**Comment by astewarttistatech** [comment]
**FAILED**

Current view in Preprod:
![checkboxes](https://user-images.githubusercontent.com/23038505/34618601-40b821a2-f20d-11e7-9a4d-fa8799c898a8.gif)

**Comment by sharonwarner** [comment]
This can now be tested in caseflow.

**Comment by astewarttistatech** [comment]
Current Caseflow Dispatch view: 

<img width="1426" alt="screen shot 2018-01-10 at 10 11 04 am" src="https://user-images.githubusercontent.com/23038505/34781331-8fb931ee-f5f3-11e7-99a9-61c29fdaa61d.png">
<img width="608" alt="screen shot 2018-01-10 at 10 45 36 am" src="https://user-images.githubusercontent.com/23038505/34781332-8fd2d4be-f5f3-11e7-93a7-c5cd1f95f300.png">

**Comment by nolawi** [comment]
Lets test is now.. its merged. Can be tested in the styleguide if dispatch UAT is down @astewarttistatech

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Dispatch
2. Navigate to the Review Decision page
3. In the SIC section click around selections (outside of text, slightly below and above) and verify that those clicks do not select any of the checkboxes
4. Verify that clicking the text(box) does check/uncheck boxes. 

Screenshots: 
![sicselect](https://user-images.githubusercontent.com/23038505/34834912-523b7fce-f6c1-11e7-86ed-46014165334b.gif)


ISSUE FOUND: #4341
