### ISSUE TITLE
API requests with non-numeric SSNs should be rejected as invalid

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4046]
## AC

* Both v1 and v2 API requests with an SSN like "12345abcd" should return 422 errors, not 404 errors.
* Numeric SSNs should continue to work as expected.

**Comment by kierachell** [comment]
**PASSED**

<img width="748" alt="screen shot 2017-12-13 at 7 54 49 am" src="https://user-images.githubusercontent.com/18075411/33939908-f417a33e-dfda-11e7-8690-4de3a135efec.png">
