### ISSUE TITLE
Reader Search | Search from point where user clicks

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4051]
When searching, if a user clicks on a page, iterate through search results starting from that page.

## AC
* Run search
* Click on page after first page
* Click to go to next search result. The next result should be the first one on that page

**Comment by astewarttistatech** [comment]
**FAILED**

Search doesn't resume at the next indicated page just the next result in a sequence. 

Current View: 
![readersearch](https://user-images.githubusercontent.com/23038505/33725454-2bf8e0aa-db40-11e7-8074-fd262bd08eff.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Reader
2. Access a multipage doc
3. Search a term
4. Scroll away from original page with results.
5. Resume search and verify that the next results are on the page scrolled to. 

Screenshots:
