### ISSUE TITLE
Reader Search | After running one search, loading spinner doesn't appear after changing documents

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4058]
The first time a search is run during a Reader session, the search bar will have a spinner appear while the text is being extracted/searched. If the user switches documents and runs a second search, the spinner will never appear, and the search bar will just say `0 of 0` until the text is extracted/searched.

## AC
* Navigate to a document, run a search
* Navigate to a second document, run a search. A spinner should appear inside the Search Bar

**Comment by astewarttistatech** [comment]
Blocked by #4036

**Comment by astewarttistatech** [comment]
**PASSED** 

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Reader
2. Open a document
3. Use search, verify spinner appeas
4.Navigate to another document and repeat 3.

Screenshots:
![readersearch](https://user-images.githubusercontent.com/23038505/33724689-1d918aaa-db3e-11e7-82a0-044b1bc61a75.gif)
