### ISSUE TITLE
Content audit

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#406]
Creating a content audit task, mostly to serve as a vehicle for sharing our Caseflow screenshots.

![questions](https://cloud.githubusercontent.com/assets/354277/11854691/990f8d94-a413-11e5-976e-8fbfd89359bb.png)
![cancel-certification 2](https://cloud.githubusercontent.com/assets/354277/11854693/9915a076-a413-11e5-8bfc-17af96c742f6.png)
![start](https://cloud.githubusercontent.com/assets/354277/11854692/9915701a-a413-11e5-8e26-3ba745680c97.png)
![login](https://cloud.githubusercontent.com/assets/354277/11854694/9929729a-a413-11e5-9134-a6246901de9a.png)

**Comment by webinista** [comment]
Generate screen

![generatepage](https://cloud.githubusercontent.com/assets/354277/11906188/c7623134-a598-11e5-94c6-8563432814a9.png)

**Comment by webinista** [comment]
Login error message / page

![login-error](https://cloud.githubusercontent.com/assets/354277/11944194/4ac390ba-a812-11e5-8479-24408c67f7ae.png)

**Comment by maryannbrody** [comment]
Hi @webinista -- here are some small content changes based on my audit. Let me know if you have any questions (cc @KHarshawat )

**Banner Throughout tool**
- Change from, “Caseflow is a pilot stage project. Have a question, feature improvement, or problem? Send feedback.”  
- Change to: "Caseflow is a new project and we are still working on making it helpful and useful. Have a question, feature improvement, or problem? Send feedback.” 

**Form 8 Page**
- Change instructional sentence to: “Caseflow pre-fills a Form 8 for each case using data from VACOLS and VBMS. To finish the form, answer the remaining questions. When you are done, click **continue**."
- Change 8C to “If an agent is designated, is he/she on accredited list?"
- 17A and 17B - **Certifying Official** should be lowercase, (changed to **certifying official**)


**Cancel Certification**
- Looks good.

**Cannot find documents in VBMS**
-Change last sentence to, “If you can’t find the document, click the **cancel certification** link below.

**Welcome to Caseflow/Login**
-Change opening sentence to, “Caseflow helps you certify an appeal by making sure all documents necessary for certification are in the eFolder. If all documents are accounted for, Caseflow will assist with filling out an electronic Form 8." 
- Add a line break before the next sentence “Please log in…. "

**Generate Screen**
- Change title to “Review Form 8” (Delete “before upload”)
- Change instructions to, “Review the completed Form 8. If the form looks correct, click **Upload and certify** and the form will automatically be uploaded into VBMS."
- Change button to “Upload and certify” (lowercase “c”)


**Login/error message page**
-Change to “Login ID and password did not work. Please try again."

**Comment by webinista** [comment]
Split these into separate tickets so that it's easier to track tasks, make changes, and review pull requests.
