### ISSUE TITLE
Add ramp_letter event to v2 api

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4062]
## AC
* An appeal should have a `ramp_letter` event if the Veteran has received such a letter, as indicated by the presence of a RampElection with the Veteran's file number.
* The event date should be notice date of the RampElection; we use the earliest date in the case where there are multiple RampElections for the Veteran.

**Comment by astewarttistatech** [comment]
@cmgiven Am I correct to assume that `ramp_letter` is the same as `ramp_notice`?

**PASSED**

Validated: UAT | Postman
<img width="1010" alt="screen shot 2017-12-22 at 3 41 05 pm" src="https://user-images.githubusercontent.com/23038505/34311941-a50b4312-e72e-11e7-82c3-388f6a5cc0aa.png">

**Comment by cmgiven** [comment]
That's right. Will just make sure that Vets.gov has the right one.
