### ISSUE TITLE
Add RAMP alerts to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4063]
## AC
* If the Veteran received a RAMP letter in the last 60 days (as determined by the notice date of RampElection), an alert should be added to the appeal in the v2 API.
* If the appeal is eligible to participate in RAMP, the `type` of this alert should be `ramp_eligible`. If not, the type should be `ramp_ineligible`.
* The `details` of this alert should have a `due_date` of the notice date plus 60 days.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Postman

<img width="897" alt="screen shot 2017-12-18 at 12 39 23 pm" src="https://user-images.githubusercontent.com/23038505/34119648-f0a8c57e-e3f0-11e7-910c-16217690ebfb.png">
