### ISSUE TITLE
Confirmation | Re-filing confirmation page

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4064]
When processing a re-entry form, I want to know that I've completed all necessary tasks, so I understand what Caseflow has done behind the scenes and I can feel confident moving on to the next form.

## Acceptance Criteria
- Verify that if an EP was successfully created for a ramp re-filing (VA Form 21-4138), the success confirmation page is displayed as the final step (see mock below and styleguide for specs)
- The confirmation page should list two steps: the EP created and should state that contentions were created in VBMS (copy below)
- Selecting the "Begin next intake" button navigates user to first page (select form)

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34178329-ce05dad6-e4d4-11e7-9abb-4d32ae085f3d.png)

## Copy
- [Veteran's name]'s (ID # [Vet ID]) VA Form 21-4138 has been processed. Send the “RAMP Acknowledgement Letter”, listing all eligible contentions, and ineligible contentions if applicable. 
- Established [EP: 682HLRRRAMP - Higher Level Review Rating] for Station 397 - ARC
- Added contentions to EP
- Way to go! You can now begin intake for the next RAMP form.

**Comment by suzchap** [comment]
Waiting for Sally to set a test ID to have the right criteria.

**Comment by leikkisa** [comment]
@leahbannon 
Test ID: 561349911

Choose supplemental claim

**Comment by suzchap** [comment]
@leikkisa I selected `RAMP Selection (VA Form 21-4138)` and then entered the test id `561349911` and the search box showed the loading icon and then just stopped without producing anything. I tried another ID and it worked as expected. Thoughts?

**Comment by suzchap** [comment]
LGTM (last line had been omitted but deemed preferable by me)

<img width="1095" alt="screen shot 2018-09-12 at 2 29 57 pm" src="https://user-images.githubusercontent.com/11219417/45445553-8a842380-b698-11e8-8b76-9d30146b7702.png">
