### ISSUE TITLE
Daily Docket | Update Hightlight Dropdown Menu

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4066]
## Story
As a Judge, when I select a dropdown under Actions on Daily Docket, it should highlight the dropdown box and be consistent in look and interaction with other parts of Caseflow. This allows me to see more clearly of the field I'm selecting.

## AC
1. When selecting from drop down, show blue highlight around the first cell.
2. Should be the same as Reader's comments dropdown (shown under desired).

**_Current:_**
<img width="402" alt="screen shot 2017-12-05 at 3 29 35 pm" src="https://user-images.githubusercontent.com/22620270/33663119-a727053e-da5c-11e7-9687-1b5b254454aa.png">

**_Desired:_**
<img width="351" alt="screen shot 2017-12-05 at 3 49 05 pm" src="https://user-images.githubusercontent.com/22620270/33663092-8b41fba8-da5c-11e7-84a9-38ce585b15aa.png">

**Comment by Sjones352** [comment]
Currently
<img width="145" alt="screen shot 2017-12-11 at 2 03 34 pm" src="https://user-images.githubusercontent.com/23080951/33848571-2b2ba2ea-de7c-11e7-98e4-25267c0df081.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Current View: 
<img width="1279" alt="screen shot 2017-12-12 at 9 58 15 am" src="https://user-images.githubusercontent.com/23038505/33891141-1a202ba4-df23-11e7-8d86-8799b50ab35b.png">
