### ISSUE TITLE
Hearing Worksheet | Update Line Break colors

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4068]
One of the line breaks before text boxes is different on the Hearing Worksheet. 

Line breaks should be consistent with all line breaks in style guide. The color should be `#d6d7d9`	`$color-gray-lighter`.

Current: 
The line break after "Add Issue", and before "Periods and circumstances of service" is a different color. 

<img width="947" alt="screen shot 2017-12-06 at 12 00 30 pm" src="https://user-images.githubusercontent.com/22620270/33674390-572abf14-da7d-11e7-927d-0c8af64fa0d2.png">

http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/hearings/32/worksheet

**Comment by kierachell** [comment]
**PASSED**
<img width="929" alt="screen shot 2017-12-13 at 8 03 26 am" src="https://user-images.githubusercontent.com/18075411/33940230-3734e716-dfdc-11e7-9ebe-4a9cdfbfdbcf.png">
<img width="956" alt="screen shot 2017-12-13 at 8 03 59 am" src="https://user-images.githubusercontent.com/18075411/33940231-376647d4-dfdc-11e7-8c5c-8623321b59a8.png">
<img width="507" alt="screen shot 2017-12-13 at 8 04 04 am" src="https://user-images.githubusercontent.com/18075411/33940232-378c6fb8-dfdc-11e7-8b40-f911459359c1.png">
