### ISSUE TITLE
AMC Dispatch: "Managers who also are workers" flow

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#407]
Managers might need to work cases, but would they be flipping back and forth between manager view and worker view? Should there be a link to do this?

It's possible that they should just be able to pick their own cases?

Need more guidance on the actual flow & experience.

**Comment by lakohl** [comment]
@abbyraskin we should discuss this on monday

**Comment by abbyraskin** [comment]
@shanear @lakohl yes, let's discuss. Managers aren't processing cases day to day (ever, at least in one manager's case - scheduling follow up with second manager), but are technically trained and are expected to be capable of doing so.

**Comment by lakohl** [comment]
@shanear we still need to allow managers to cest claims. Right now it doesn't seem possible for them to switch roles. Would a solution be to make the Manager view a different URL - or perhaps you can think of a better way?

**Comment by shanear** [comment]
@lakohl I think that is fine. In hindsight, we should have probably always done that (you were right @joofsh 😬)

**Comment by lakohl** [comment]
Ok. Cool. We should figure out a new URL for the manager and let @nikitarockz know. She is helping get the desktop shortcut links for Dispatch set up.

**Comment by nikitarockz** [comment]
@shanear I have already submitted a request for adding links.  Would you like me to hold off until you can get a Manager link?  Right now I gave the same link for both.

**Comment by lakohl** [comment]
url was created. Closing
