### ISSUE TITLE
comparison of Date::Infinity with ActiveSupport::TimeWithZone failed

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4070]
app/models/appeal_history.rb in sort_by at line 196

**Comment by astewarttistatech** [comment]
@cmgiven How is this to be validated? I did a smoke test of the API and there doesn't seem to be anything broken (coming back nil or empty or unrecognizable fields).

**Comment by cmgiven** [comment]
This bug affected appeals without an NOD. If an appeal without an NOD can be shown without error, we're good.

Sorry for the lack of an AC. This was in response to a bug Artem identified in an earlier QA.
