### ISSUE TITLE
Coalesce aod and issue lookups to improve v2 API performance

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4073]
## AC
* A query to the v2 API should trigger a max of two VACOLS queries: one to retrieve the appeals and one to retrieve the issues of those appeals. The current behavior triggers 2n+4 VACOLS queries, where _n_ is the number of appeals the Veteran has.
* I also stopped calling the ugly issue descriptions SQL. No need to add a bunch of costly joins that we're not going to use anyway.

**Comment by kierachell** [comment]
### I am getting this error now:

- It seems like you're missing something:
```
undefined method `key?' for #<VACOLS::CaseIssue:0x00560aff6b5228>
```

- In the `load_from_vacols` method:
```
      if hash.key? "issprog_label"
        attributes[:type] = { name: TYPES[hash["isscode"]], label: hash["isscode_label"] }
        attributes[:description] = description(hash)
```

**Comment by cmgiven** [comment]
Bleargh.

**Comment by kierachell** [comment]
Completely agree

**Comment by cmgiven** [comment]
@kierachell: Fix merged in. Sorry about that.

Also, Alex is looking at the date comparison bug fix now. That'll be merged in as soon as Alex and Travis permit.

**Comment by kierachell** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: UAT | Postman


![postmanuat](https://user-images.githubusercontent.com/23038505/34311841-09222e2a-e72e-11e7-8adc-32f4a26d3c9a.gif)
