### ISSUE TITLE
Reader | Remove search FeatureToggle

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4074]
Document search is still hidden behind a FeatureToggle

## AC
* Search button should be visible to all users

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome | Preprod Jumpbox

1. Access Preprod Jumpbox and disable search FeatureToggle
2. Access Reader for Preprod
3. Open a document and validate that not only the search button is visible but also functional. 

Screenshots: 
<img width="1421" alt="screen shot 2017-12-06 at 12 17 11 pm" src="https://user-images.githubusercontent.com/23038505/33675876-11bd24b2-da82-11e7-86bf-8016866e319f.png">
<img width="1431" alt="screen shot 2017-12-06 at 12 17 35 pm" src="https://user-images.githubusercontent.com/23038505/33675880-12a7e100-da82-11e7-8488-4e280a5337af.png">
