### ISSUE TITLE
Manager Dashboard:  Reports:  Ability to view appeals without a decision document

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#408]
As a BVA Dispatch Manager, I would like to view a listing of all appeals the have not been able to be associated with a decision document so that I can manage and escalate the issue to a resolution as necessary.

## Acceptance Criteria
1. Verify that when navigated to the Missing Decision report page, a list of appeals missing a decision is displayed.
1. Verify that only users with "System Admin" and "Manage Claim Establishment" are authorized to access this page. 
1. Verify that all appeals that are ready for Claims Establishment but missing a decision document are displayed in this list.
1. Verify that for each appeal in the list, the following columns of information is displayed:
   - **Veteran** column is filled in with the VBMS ID of the appeal
   - **Decision Type** - the VACOLS Decision Type value for the claim
   - **Decision Date** - is filled in with the decision date retrieved from VACOLS. _Format:_  mm/dd/yyyy
   - **Days in Queue** - is filled in with the # of days the system tried to obtain the decision document VBMS
1. Verify that the list is ordered by _"Days in Queue"_ with the most days being at the top.
1. Verify that the Header contains the current date in the following format:  

     > Claims Missing Decision - [Today's Date - mm/dd/yyyy]
1. Verify that the standard application header is displayed with the following elements (Refer to mockup): 
    - **Application Name** - "Caseflow Dispatach" 
    - **Application Logo** - [logo file]
    - User Name menu 
1. Verify that the standard application Footer is displayed with **_Digital Service_** and **_Send Feedback_** links. 
## Mockup
<img width="549" alt="screen shot 2017-01-12 at 4 26 37 pm" src="https://cloud.githubusercontent.com/assets/4975959/21908957/f4d3d1a2-d8e3-11e6-9648-4096c69cb072.png">

# Technical Notes
- Use a US Web Design Standards table and the Caseflow Dispatch layout.
- URL is /dispatch/missing-decision

# Related Stories
Decision Review: Show Decision PDF and information #405
Manager Dashboard: Reports: Ability to limit and show more Missing Document Claims #632
Manager Dashboard: Header: User Menu: Ability to logout #633

**Comment by KHarshawat** [comment]
Related to discussion in https://github.com/department-of-veterans-affairs/caseflow/issues/405

**Comment by lakohl** [comment]
Design is here: https://marvelapp.com/1j37g4b

**Comment by KHarshawat** [comment]
@lakohl which manager would see this page? The AMC manager or the one working at BVA (Denise)? 
 
If it's the latter, how would we provide them access to this page?

**Comment by lakohl** [comment]
@KHarshawat I designed this with Denise (BVA Dispatch Manager) in mind, so she can act on cases missing decisions. I'm presuming she would have access to this Caseflow Dispatch page based on her login credentials.
We are planning not to serve up cases that do not have a VBMS decision to AMC caseworkers, thus I don't see a need this table to AMC managers.

**Comment by lakohl** [comment]
<img width="879" alt="screen shot 2017-01-03 at 6 20 38 pm" src="https://cloud.githubusercontent.com/assets/4975959/21626798/5b2d01bc-d1e1-11e6-970a-145e9af04e99.png">

**Comment by shanear** [comment]
@lakohl What the "Decision Uploaded" checkboxes are supposed to do? If the decision was uploaded, shouldn't it be taken off the report?

**Comment by lakohl** [comment]
<img width="549" alt="screen shot 2017-01-12 at 4 26 37 pm" src="https://cloud.githubusercontent.com/assets/4975959/21908957/f4d3d1a2-d8e3-11e6-9648-4096c69cb072.png">

**Comment by astewarttistatech** [comment]
Current View:

<img width="1293" alt="screen shot 2017-02-07 at 9 01 31 am" src="https://cloud.githubusercontent.com/assets/23038505/22694211/4951a04e-ed14-11e6-81d1-7af071864356.png">

There is no "View Dashboard" button, as pictured, as that part of this issue's scope? @lakohl

**Comment by kierachell** [comment]
criteria has been updated to remove the "View Dashboard" thingy.
