### ISSUE TITLE
Remove :ip_addres accessor from user model 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#4092]
The idea is to have it hardcoded for each env. 
See https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/staging-NAT-mappings-NSOC.md
and
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/production-NAT-mappings-NSOC.md

**Comment by astewarttistatech** [comment]
@nemodjuric How is this to be validated if it needs to be?

**Comment by nemodjuric** [comment]
Make sure that Caseflow communicates with BGS successfully. 
```bgs = BGS::Services.new(
  env: Rails.application.config.bgs_environment,
  application: "CASEFLOW",
  client_ip: Rails.application.secrets.user_ip_address,
  client_station_id: "317",
  client_username: "CF_LAFORGE_317",
  ssl_cert_key_file: ENV["BGS_KEY_LOCATION"],
  ssl_cert_file: ENV["BGS_CERT_LOCATION"],
  ssl_ca_cert: ENV["BGS_CA_CERT_LOCATION"],
  log: true
)

ssn = "SOME_SSN"
bgs.people.find_by_ssn(ssn)

**Comment by astewarttistatech** [comment]
@nemodjuric AC needs to be better defined. If this is a ticket for Certification then the validation should be in Certification and the anywhere where services are shared/affected. "Make sure that Caseflow communicates with BGS successfully" in what way? What is the code for and where does it go? BGS is just used to match the SSN to a file number.

**Comment by astewarttistatech** [comment]
No Validation needed other than smoke test
