### ISSUE TITLE
Daily Docket: Daily Docket displays veterans in a different order than VACOLS Virtual Docket

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4094]
Daily Docket displays veterans in a different order than VACOLS Virtual Docket. 

It can make it hard to see when a veteran is added if they are not added to the bottom of the list.

What order is Caseflow using?

**Comment by sharonwarner** [comment]
From Jed on the Virtual Docket order: They are sorted by VLJ, Date/time, Veteran Name.

**Comment by lakohl** [comment]
So alphabetical by Veteran (after time)?

**Comment by sharonwarner** [comment]
We currently order them by ID, so hearings they will be ordered by the time they are saved in VACOLS.

**Comment by sharonwarner** [comment]
Replaced by #4691
