### ISSUE TITLE
Cancel:  Ability to stop processing current case

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#410]
As a Caseworker, I want to be able to Cancel out of the current case that I am working on so that it can be available to another caseworker because I am unable to complete the review for various reasons (needing to take a bio break, speak to supervisor, need more information, etc.).

**Acceptance Criteria**
1. Verify that on the Decision Review page, there is a link to with the following label:  Cancel.  
1. Verify that on the Decision Review page when the “Cancel” link is clicked, a new Established Claim task is created for that case.
1. Verify that on the Decision Review page when the “Cancel” link is clicked, the Caseworker Landing page is displayed.
1. Verify that on the Decision Review page when the “Cancel” link is clicked, the "Action" value on the Caseworker Landing page in the Work History section is set to "Cancelled” for the current task.  
1. Verify that on the End Product page, there is a link to with the following label:  Cancel.  
1. Verify that on the End Product page when the “Cancel” link is clicked, the Caseworker Landing page is displayed.
1. Verify that on the End Product page when the “Cancel” link is clicked, the "Action" value on the Caseworker Landing page in the Work History section is set to "Cancelled” for the current task
1. Verify that on the End Product page when the “Cancel” link is clicked, a new Established Claim task is created for that case.

# Mockups
### **End Product Page**
![image](https://cloud.githubusercontent.com/assets/23063044/20400508/ee508b2e-acc2-11e6-9548-93439ada5c0d.png)

### **Decision Review Page**
![image](https://cloud.githubusercontent.com/assets/23063044/20400523/0ae39538-acc3-11e6-8b5b-884b5e779d78.png)

**Comment by joofsh** [comment]
@nikitarockz @shanear Should we be saving their reason for cancelling out of the appeal?

**Comment by nikitarockz** [comment]
That is on the agenda but it hasn't been designed out. we figured this would be a first step.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by joofsh** [comment]
@astewarttistatech let me know if you have any questions on how to QA this
I would try to validate:
  - From landing page can click to open new Establish Claim task
  - At bottom of that page, can click cancel to return to landing page

**Comment by astewarttistatech** [comment]
Sounds good. This has been validated.
