### ISSUE TITLE
Add post-SSOC statuses to v2 API

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4102]
## AC
* When an appeal is in `pending_certification` status (see #3984), and it has at least one SSOC, the status should instead be `pending_certification_ssoc`.
* When an appeal is in `remand` status, and it has at least one SSOC created after the decision date, the status should instead be `remand_ssoc`.

**Comment by Sjones352** [comment]
@cmgiven this passes for an appeal is in remand. 
<img width="955" alt="screen shot 2018-01-30 at 1 38 18 pm" src="https://user-images.githubusercontent.com/23080951/35585383-c4cc11ee-05c5-11e8-82bd-a7975302e1f7.png">
