### ISSUE TITLE
Address user requests around React-Virtualized

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4108]
After adding the windowing changes last month, there are three issues we're hearing from users.

1) Lack of horizontal scroll bar. When a user zooms in, there is no horizontal scroll bar.
1) No side-by-side viewing. When a user zooms out, they can only see one page at a time.
1) Vertical scroll bar changes in size. The vertical scroll bar jumps around as a user scrolls.

# AC
1) Verify there is a horizontal scroll bar when a user zooms in to the point of needing one.
1) Verify that when zoomed out, a user can see multiple pages side by side.
1) Verify that the vertical scroll bar stays relatively stable as a user scrolls vertically.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Reader
2. Select a document from a veteran's document list
3. Zoom in, inorder to to enact a horizontal scroll bar to appear at the bottom of the PDF viewer
4. Scroll down to enact a vertical scroll bar to appear on the right-hand side of the page. 
5. Zoom out to see that the pages in the multipage doc end up side to side. 

Screenshots: 
![readerscroll](https://user-images.githubusercontent.com/23038505/34675268-0d06141c-f457-11e7-8f5e-75ab5cacb7a4.gif)
