### ISSUE TITLE
RO Routing:  Full Grant:  Ability to manage information (location, explanation) for routing case

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#411]
As a caseworker, I want to be able manage routing information (location, explanation) for a case so that I can identify the Regional Office location and provide additional information to help continue the processing. 

### Acceptance Criteria
1. Verify that there is a Destination dropdown.  (Refer to the Mockup for details.)
2. Verify that the Destination dropdown contains the following options:  TBA what can they designate now? Can we have the Vets RO show here? Or is the location a more general designation?
3. Verify that an Explanation can be provided for re-routing the case.

**Comment by shanear** [comment]
We aren't routing to ROs. Closing
