### ISSUE TITLE
Daily Docket | Show when a case is prepped

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4112]
Daily Docket: Show when a case is prepped
As a judge I would like to be able to keep track of which cases I have prepped and which cases I still need to work.

## AC

1. Add a column with the column header 'Prep' in between case number and the hearing time on the Daily Docket.
1. Add a checkbox to the right of each case number.
1. Allow a judge to check and uncheck the Prep checkbox.

## Mock
<img width="535" alt="screen shot 2018-01-02 at 10 34 40 am" src="https://user-images.githubusercontent.com/4975959/34488986-99354fba-efa8-11e7-8ee2-e758296c8130.png">

**Comment by nolawi** [comment]
is there label called 'Prepped' how will should we handle the label
![screen shot 2017-12-20 at 3 05 32 pm](https://user-images.githubusercontent.com/1745984/34226314-4bba9594-e597-11e7-9051-c252e44c34ee.png)

How will the user know to do this? maybe it should be right

**Comment by lakohl** [comment]
Header looks like this: 
<img width="510" alt="screen shot 2017-12-20 at 8 05 40 am" src="https://user-images.githubusercontent.com/4975959/34229967-40a6cfda-e5a4-11e7-80fb-ce02d6869ebe.png">

**Comment by Sjones352** [comment]
**PASSED*
Validate/Chrome
1. Access Hearing Prep
2. View Daily Docket and see if Prep Column has been added.
3. Click on checkbox and uncheck Prep checkbox

![hearing](https://user-images.githubusercontent.com/23080951/35652827-54f56a20-06b3-11e8-8392-89e7f74c519d.gif)
