### ISSUE TITLE
Daily Docket Dropdown: BUG text displays is accidentally bolded, add ellipses

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4117]
Daily Docket Dropdown: is accidentally and randomly bolded
![2017-12-08 17 04 09](https://user-images.githubusercontent.com/4975959/33787233-5bcf334c-dc3a-11e7-81fb-c2059ac123e2.gif)

## AC
1. Dropdown should display 'Select' as [Select...] with ellipses
1. Dropdown should not randomly bold dropdown values.

**Comment by lakohl** [comment]
@Sjones352 I see what you mean, ok.

**Comment by kierachell** [comment]
![after-hover-leave](https://user-images.githubusercontent.com/18075411/33915153-ce147b6e-df6f-11e7-9db4-904521823318.gif)

So the real issue is that the `hovered` state is preserved when you click away from the dropdown:
- hover over a value
- move away from dropdown and click to close the dropdown
- reopen dropdown to see the that the "last hovered" value still has dark background

**Comment by Sjones352** [comment]
it's no longer bolded. Sorry for the poor gif

![hearing](https://user-images.githubusercontent.com/23080951/33940342-96f6160c-dfdc-11e7-9d61-d72997b304fc.gif)

**Comment by kierachell** [comment]
- I don't know if the desired behavior is to have the `current selection` bolded?
- should the dark background stay on the `current selection or follow the mouse pointer hover?
- should the dark background reset to `current selection` when dropdown is closed?

**Comment by lakohl** [comment]
Desired behavior is the styleguide behavior. The dark background should start on the selection and then follow the mouse. When the mouse moves off the current selection that selection should show as bolded until another selection is made.

**Comment by kierachell** [comment]
So then there is no bug:
![peek 2017-12-13 10-57](https://user-images.githubusercontent.com/18075411/33948303-89053006-dff4-11e7-8220-782c5948fd68.gif)

**Comment by lakohl** [comment]
In the .gif above, when Germany is selected, the dropdown menu should open with the  grey bar on Russia, not on United States. Germany would then display in bold in the dropdown until another selection has been made. This is how Caseflow Commons should work.It's unclear to me if that is how it is working, I can't reproduce @kierachell's results.

**Comment by nolawi** [comment]
@lakohl you can reproduce it here 
http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#dropdown-menu  that is how it works right now.. I don't think we need this change at all

**Comment by nolawi** [comment]
Tix- will be closed for now.. we can't replicate the issue consistently.
