### ISSUE TITLE
Caseflow apps all have different stage sizes?

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4118]
Dispatch, Reader and Hearing Prep Display with different stage sizes. What is the best way to fix this?
<img width="1439" alt="screen shot 2017-12-08 at 5 17 15 pm" src="https://user-images.githubusercontent.com/4975959/33787619-141186de-dc3c-11e7-8252-463700289980.png">

**Comment by nolawi** [comment]
This has been resolved `<NavigationBar wideApp>` makes stage wide
