### ISSUE TITLE
Hearing Prep stage should match the width of the Reader stage

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4119]
See: #4118

**Current:**
In desending order: Dispatch, Reader, hearing Prep...
<img width="1439" alt="screen shot 2017-12-08 at 5 17 15 pm" src="https://user-images.githubusercontent.com/4975959/33787758-c7c73da4-dc3c-11e7-82bb-1906b7218002.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing Prep
2. Access Reader
3. Verify that their spacing from top bar to body page content is the same. 

Screenshots: 
<img width="1418" alt="screen shot 2017-12-21 at 11 08 18 am" src="https://user-images.githubusercontent.com/23038505/34264296-714d1a30-e640-11e7-9bb1-b171dbf1de89.png">
<img width="1432" alt="screen shot 2017-12-21 at 11 08 34 am" src="https://user-images.githubusercontent.com/23038505/34264297-7154f624-e640-11e7-8c92-6dbdf68d7d0a.png">

**Comment by astewarttistatech** [comment]
So I validated what the title of the ticket told me to do, but since this was reopened and there is no AC on what needs to be validated, pushing this back for better requirements. @lakohl @sharonwarner

**Comment by lakohl** [comment]
@nolawi @sharonwarner would you be able to add details to help Alexis validate this? thx
