### ISSUE TITLE
RO Routing:  Ability to route case

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#412]
As a Caseworker, I want to be able Route the Appeal to the RO that has a Special Issue so that they can continue to process the case. 

**Acceptance Criteria**

1. Verify that there is a ‘Re-route Appeal to RO’ button.  (Refer to the Mockup for details)
2. Verify that when the ‘Re-route Appeal to RO’ button is clicked; the Decision Results value is set to “Re-route Appeal to RO”.
3. Verify that when the ‘Re-route Appeal to RO’ button is clicked; the case is moved to ???????.  (Not sure where it goes from here, another system?)

**Comment by KHarshawat** [comment]
Assigning to @lakohl since she's working on this one.

**Comment by lakohl** [comment]
@nikitarockz RO Routing is not happening anymore in the manner of the original mocks. For Milestone 2 we are going to have AMC create all Full Grant EPs. The EPs that they create for ROs will possibly be assigned to a specific Station. @abbyraskin Need to investigate exactly how this will work.

**Comment by shanear** [comment]
We aren't routing to ROs. Closing
