### ISSUE TITLE
Daily Docket | Update Appellant Name Order

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4120]
_**Story:**_
To help the Judge read Appellant names on the Daily Docket more easily, we want to change the name order and do not capitalize the entire name.

_**A/C:**_
This is below Appellant/Veteran ID title.
First Name Middle Last Name order.
Keep bold.
Do not use all caps. 

**_Current:_** 
**ANTHONY, MARTIN A.**

_**Current mock:**_ 
<img width="180" alt="screen shot 2017-12-08 at 5 27 44 pm" src="https://user-images.githubusercontent.com/22620270/33788102-5c1c2d06-dc3e-11e7-875f-8cd3e42c4155.png">

_**Desired:**_
**Martin A. Anthony**

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing Prep
2. Navigate to the Daily Docket page
3. Verify that the "Appellant/Veteran ID" matches the criteria in the AC

Screenshots: 
<img width="1282" alt="screen shot 2018-01-04 at 10 05 39 am" src="https://user-images.githubusercontent.com/23038505/34569740-af42d7b0-f137-11e7-8262-b9f7ef171b36.png">
