### ISSUE TITLE
Hearing Worksheet | Print/Save PDF UI Clean-up

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4121]
Story: When a Judge clicks on Save as PDF on the hearing worksheet, he/she wants to see most information on one page and improve formatting. 

AC:
We want to maximum page with hearing worksheet information:

- [x] If there is second or multiple pages, remove Veteran/Appellant Info on top part of the page.
- [x] If there is a second or multiple pages, do not repeat Header info (Hearing Worksheet, VLJ, Type)
- [x] Font size for copy should be 11pt for all content.
- [x] Under Preliminary Issues so text is not getting squished and covered by checkboxes.
- [x] Remove the button outline/box around Veteran ID.
- [x] Keep original text and spacing in text boxes for "Contentions", "Periods of circumstance", "Evidence", and "Comments and special instructions."
- [ ] Show veteran name and page number in the bottom right corner of every page. First Initial Last Name, Page #. (A. Washington, page 2).
- [ ] If Appeal Streams continue to page 2, continue with header on page 2 "Appeal Stream X", line break and Issue, Notes, Preliminary Issues, but do not repeat the headers twice by making sure these heads and issue show together ([4769](https://github.com/department-of-veterans-affairs/caseflow/issues/4769))
- [x] Reduce extra spacing between rows. 
- [x] Remove box outlines on issues that were added (using the +Add issue button).
- [x] Show all typed notes in boxes even if box is not expanded, and do not cut off
- [x] Make sure if preliminary checkboxes are marked that is it shows on print view ([4768](https://github.com/department-of-veterans-affairs/caseflow/issues/4786))
- [x] Make sure line break does not cross through any content/words on the page 
- [x] Keep all the formatting of text in all boxes as the Judge has typed and print the same formatting in all Note boxes (ex. periods and circumstances, contentions, evidence, special instructions to attorneys).

- [ ] Goal is to fit everything in one page. Have note boxes "Contentions", "Periods of circumstance", "Evidence", and "Comments and special instructions" follow after Issues.

_**Current mock:**_
Page 1:
![hearing worksheet for jackson james a_](https://user-images.githubusercontent.com/22620270/33798362-eb0bfffe-dce4-11e7-9ded-53755a51f8aa.jpg)
Page 2:
![hearing worksheet for jackson james a_back](https://user-images.githubusercontent.com/22620270/33798365-ffec004a-dce4-11e7-8116-c71517368b07.jpg)

[Hearing Worksheet for Jackson, James A_.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1544964/Hearing.Worksheet.for.Jackson.James.A_.pdf)

---
**Desired mock:**
Page 1:
![hearing worksheet print front](https://user-images.githubusercontent.com/22620270/35491820-fb04e542-0476-11e8-858c-ab4e27af9884.jpg)

Page 2:
![hearing worksheet print 3](https://user-images.githubusercontent.com/22620270/35491824-0290d3c0-0477-11e8-91a6-adcc55a6dbae.png)

**Comment by Sjones352** [comment]
@annienguyenUSDS 

<img width="894" alt="screen shot 2018-03-14 at 10 24 09 am" src="https://user-images.githubusercontent.com/23080951/37408158-e5697f7c-2771-11e8-9047-835b8cae3564.png">

**Comment by annienguyenUSDS** [comment]
@Sjones352, can you give more context on the screenshot above?
