### ISSUE TITLE
Reader | Streamline navigating between search results

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4125]
At the moment, both `PdfFile` and `PdfPage` calculate the page a match belongs to, using the same logic. We should run this calculation just from `PdfFile` and delegate to its pages using props.

## AC
- [ ] Navigating through search results works as expected / as before. These changes are totally behind-the-scenes

**Comment by astewarttistatech** [comment]
**PASSED**


Validated: Preprod | Chrome 

Steps to Validate: Smoke test of Reader Search to see if it is working as to be expected.
