### ISSUE TITLE
Styleguide | Fix links on style guide

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#4132]
For certain sections of the navigation, the anchor links do not jump to the appropriate header when clicked on.

AC:
Verify that the following links in in the navigation jump to their respective sections
* (under "Tabs")
  * Without icons
  * With icons
* (under "Radio Buttons")
  * Vertical
  * Horizontal

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Styleguide
2. Select a few of the links in the navibar and then select their child links and verify that the sections are adjusted to the top of the screen. 

Screenshots:
