### ISSUE TITLE
Look into rate limiting Reader users

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4134]
We don't want a rogue browser to DoS our servers. One way we can prevent this is by adding some type of rate limiting.

**Comment by evankroske** [comment]
AWS WAF looks promising:

https://aws.amazon.com/about-aws/whats-new/2017/06/aws-announces-rate-based-rules-for-aws-waf/

I think that Envoy also might support rate limiting.

**Comment by D-L-Ware** [comment]
Closed as part of clean up of Reader tickets.
