### ISSUE TITLE
Review Request | Display appeal selection options

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4139]
When processing a Veteran's request for an appeal, I want to see all the options available within that review lane, so I can accurately document their selection and move on to the confirmation page

## Acceptance Criteria
- Verify that if a user selects "Appeal to the Board" radio button, the second question + options (shown in the mock below) displays.
- Verify that if a user selects the appeal option and selects "Continue to the next step", they are navigated to the (TBD) Finish Processing page (handled in #4182)

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34178154-334c845e-e4d4-11e7-99d9-bf468b60ea57.png)

**Comment by abbyraskinUSDS** [comment]
@shanear do we need to include any additional technical notes about what/where info is stored (the output in general), given that we aren't creating EPs?

**Comment by shanear** [comment]
I'm planning on storing them in the Caseflow DB.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT | Chrome 

Steps to Validate: 
1. With a veteran who has contentions in VBMS and a cleared EP, start the Selection RAMP Intake flow
2. Select "Appeal to Board" as the review lane
3. Verify that the additional options appear beneath, upon selection. 

Screenshots: 
<img width="1427" alt="screen shot 2018-01-12 at 2 18 44 pm" src="https://user-images.githubusercontent.com/23038505/34892008-a3dbf5cc-f7a5-11e7-8a5a-5360c348d2a7.png">
