### ISSUE TITLE
RO Routing:  Ability to return to Decision Preview page

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#414]
As a Caseworker, I want to be able to go back to the Decision Preview page so that I can review again the decision information committing to routing the case to the Regional Office.  (???Not sure if this is the real reason why.)

**Acceptance Criteria**

1. Verify that there is a “Back to preview” link.
2. Verify that when the “Back to preview” link is clicked; the Review Decision page is displayed for the current case.
3. Verify that when the “Back to preview” link is clicked; any information entered for Destination and/or Explanation isn’t saved.  (? Not sure if this is what is wanted? If it should be saved, then update Route story to include a statement reflecting existing data.)

**Comment by shanear** [comment]
We aren't routing to ROs. Closing
