### ISSUE TITLE
Determine how long it takes to acquire a new VACOLS connection

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#4145]
One assumption we make in the [post-mortem for the health-check outage](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1071) on 30 November is that ActiveRecord is very slow to acquire new connections to VACOLS (on the order of seconds instead of milliseconds as we would hope). We should turn this assumption into a fact and figure out why it takes so long and what we can do to reduce that duration.

## Acceptance criteria
* Determine how long it takes ActiveRecord to acquire a connection to VACOLS
* Determine why (ActiveRecord-Oracle DB issue? VACOLS-specific issue?)
* Determine if there is anything we can do to mitigate it on our end

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
