### ISSUE TITLE
RO Routing:  Cancel:  Ability to stop processing the current case

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#415]
As a Caseworker, I want to be able to Cancel out of the current case that I am working on so that it can be available to another caseworker because I am unable to complete the RO Routing for various reasons (needing to take a bio break, speak to supervisor, need more information, etc.).

**Acceptance Criteria**

1. Verify that there is a link to with the following label:  Cancel Processing.   (??? Not sure this is the name you want. The mockup has Back to Queue. This term may be a little clearer what is occurring.)
2. Verify that when the “Cancel Processing” link is clicked, the current case is released back to the queue available for processing. (???Represents an item status change. Not sure what the status should be.)
3. Verify that when the “Cancel Processing” link is clicked, the Casework Landing page is displayed.
4. Verify that when the “Cancel Processing” link is clicked, the Result value of the current case is set to “Canceled”.  (??? If this item’s Result value is set to Cancel, the value will have to change when another person picks it up.  Now that can potential bring to light another issue.  On the current user’s history log, will the value of that remain as Canceled after the other user picks it up or will it change to the new values of “In Progress”?)

### Related Issues
EPIC: Decision Review: Ability to review and discern a result for an appeal case https://github.com/department-of-veterans-affairs/appeals-pm/issues/1031

**Comment by KHarshawat** [comment]
The actions vary by page. I'll try to document for clarity here.

On the Decision Review page the cancel action should be a link and by itself

![image](https://cloud.githubusercontent.com/assets/6335546/20769546/6848a7d4-b710-11e6-9543-1f78cacb8d70.png)


On subsequent pages, the cancel action should still be a link but accompanied by actions to navigate to the previous step:

![image](https://cloud.githubusercontent.com/assets/6335546/20769508/2deda684-b710-11e6-8ffc-8315a6561db8.png)

**Comment by shanear** [comment]
We aren't routing to ROs. Closing
