### ISSUE TITLE
Hearing Prep | Distinct Titles in Browser Tabs Part 2

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#4157]
Related # #3894

As a Judge, I have multiple tabs and windows open during hearing prep and hearings. This includes multiple tabs for hearing prep worksheets, which are difficult to distinguish what hearing I'm working on because the labels have the same titles. As a Judge, I sometimes go back and forth between tabs and often it takes time to figure out to which Veteran's worksheet I am so I click on all the tabs until I find the one I'm looking for.

A/C: Clearer titles in tabs across Hearing Prep Product that match the page that the Judge is viewing.

Current Naming in Caseflow:
3. Reader document: "Document Viewer |  Caseflow Reader"
4. Welcome gate: "Assignments | Caseflow Reader"

Current mock - Hearing Prep pages are not distinguished from one another:
<img width="707" alt="screen shot 2017-11-06 at 10 52 09 pm" src="https://user-images.githubusercontent.com/22620270/32476787-b7bd7cf6-c347-11e7-8506-9f7c57f1254b.png">

Proposed Tab Naming Change:
3. J. Snuffy's Worksheet (First initial, Last Name's Hearing Worksheet)
4. J. Snuffy's Claims Folder (First initial, Last Name's Claims Folder)

Proposed Mock: 
<img width="1123" alt="screen shot 2017-11-09 at 4 37 19 pm" src="https://user-images.githubusercontent.com/22620270/32630950-8b200368-c56c-11e7-8d76-cd7583dd8fa5.png">

**Comment by Sjones352** [comment]
**PASSED**


Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing-Prep
2. Click Date 
3. Validate the Distinct Titles in Browser Tabs

![Screen Shot 2018-01-22 at 1.43.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58209eeb97c65e0e00e4cfa6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f16b7191a379f116284f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df74de7495da7153e66e1752431.png)
