### ISSUE TITLE
Hearing Worksheet | Close window after print/save modal action/close out

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4159]
Story: A Judge has clicked on "Save as PDF", and a new window that opens will shows the print/save modal. After Judge has taken action in the modal, the new print view new window should close automatically. This helps the Judge go back to their hearing worksheet and do not have to close the Save as PDF window.  

AC:
Close new window after Judge has taken action (cancel, save, or print) from the modal.
Ensure that the print dialogue displays the page after everything renders.

**Comment by nolawi** [comment]
tested this and adding `window.close();` right after `window.print();` seems to do the trick!

**Comment by lakohl** [comment]
@tejans24 would you mind posting a gif of how this would look for the user?

**Comment by tejans24** [comment]
Sure

**Comment by annienguyenUSDS** [comment]
@tejans24 looks good!

**Comment by tejans24** [comment]
![print-video](https://user-images.githubusercontent.com/1976755/37363826-4f4e7850-26cf-11e8-9043-310832c356bc.gif)

**Comment by lakohl** [comment]
@tejans24 the window closes as desired. But when I select 'Save as PDF' I get print options not Save options. Is this a browser thing?
[Screen Shot 2018-03-16 at 7.56.46 PM.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1821055/Screen.Shot.2018-03-16.at.7.56.46.PM.pdf)
