### ISSUE TITLE
End Product:  Collect information for creating an End Product

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#416]
As a Caseworker, I want the ability to collect information relevant to an End Product so that I will be able  to generate an End Product.

**Acceptance Criteria** 
1. Verify that on the Decision Review page, when the Create End Product button is clicked, the End Product page is displayed.
1. Verify that the following fields are available (refer to mockup for layout details):  Benefit Type; Payee; EP & Claim Label; Modifier; Decision Date; Segmented Lane; Station; POA; POA Code; Allow POA Access to Documents; Gulf War Registry Permit; Suppress Acknowledgement Letter
1. Verify that the field "Benefit Type" is set to the value of"C&P Live" value.
1. Verify that the field "Benefit Type" cannot be edited.
1. Verify that the field "Payee" is set to the value of "00 - Veteran".
1. Verify that the field "Payee" cannot be edited.
1. Verify that the field "EP & Claim Label" drop down contains the following values: " "; "172BVAG - BVA Grant";  "170PGAMC - AMC-Partial Grant"; "170RMDAMC - AMC-Remand"
1. Verify that if the decision of the appeal is a Full Grant, set the the field "EP & Claim Label" to "172BVAG - BVA Grant".
1. Verify that the field "Modifier" drop down contains the following values:  "170"; "172"
1. Verify that the “Modifier” value equals to the matching 1st 3 digits of the value in the “EP & Claim Label”.  
1. Verify that the field “Claim Type” is set to the value “Claim”.
1. Verify that the field “Claim Type” is not visible.
1. Verify that the field “Decision Date” defaults to the VACOLS decision date.
1. Verify that the field “Decision Date” cannot be edited.
1. Verify that the field "Segmented Lane" drop down contains the following values:  "Core (National)", "Spec Ops (National)".
1. Verify that the field "Segmented Lane" drop down defaults to the following option value:  "Core (National)".
1. Verify that the field "Station" set to the value "499 - National Work Queue".
1. Verify that the field "Station" cannot be edited.
1. Verify that the field "POA" only accepts one of the following valid options:   "None", "VSO", and "Private".
1. Verify that the field "POA" defaults to the following value:   "None".
1. Verify that the field "POA Code" field is only displayed when the "POA" field has a value of "VSO" or "Private".
 1. Verify that the field "Allow POA Access to Documents" field is only displayed when the "POA" field has a value of "VSO" or "Private".
 1. Verify that the field "Allow POA Access to Documents" defaults to being checked when the "POA" field has a value of "VSO" or "Private".
1. Verify that there is a "Submit End Product" button.
1. Verify that there is a "Back to Preview" link.
1. Verify that there is a "Cancel" link.  

## Mockup
![416 - end product page](https://cloud.githubusercontent.com/assets/23063044/20353701/b767faf4-abe9-11e6-94f6-d38084d93a56.PNG)

### Developer Notes

- Required fields will be address in another user story.
- Button Actions will be addressed in another user story.
- Veteran name in the header will be addressed in another user story.

Sub-tasks
Develop UI
QA discovery and scripting

**Comment by shanear** [comment]
All of the info required for this should be available in VACOLS. @cmgiven can help with any VACOLS related questions for this.

**Comment by mdbenjam** [comment]
@nikitarockz the ticket describes an attached mapping document. However, I don't see one attached.

**Comment by mdbenjam** [comment]
Waiting for some other stories to get more feature tests before moving to validation.

**Comment by astewarttistatech** [comment]
Looks good. 

Verified on Chrome/Firefox browsers.
