### ISSUE TITLE
Some log lines are duplicated

### ISSUE THREAD

**Issue by nickheiner-usds** [department-of-veterans-affairs/caseflow#4171]
Some lines show up twice, with an additional timestamp:

```
13:46:34 rails.1  | [localhost] [2ff1d5d6-4292-4cc1-9c67-fe3cf1c10939] [localhost] [Reader ] STARTED load appeal reader_id1
13:46:34 rails.1  | [localhost] [2ff1d5d6-4292-4cc1-9c67-fe3cf1c10939] [localhost] [Reader ] [2017-12-14 13:46:34 -0500] STARTED load appeal reader_id1
```

Best case scenario, this is an annoyance locally. Worst case scenario, it's also happening in prod, and making our logs harder to sort through in a prod debugging situation.

[Related Slack](https://dsva.slack.com/archives/C2ZAMLK88/p1513277237000150).

# AC
- Logs aren't duplicated in local or on AWS

**Comment by astewarttistatech** [comment]
**No QA necessary**

**Comment by nickheiner-usds** [comment]
I am still seeing duplicate log lines.

```
14:22:26 rails.1  | [localhost] [d4c67330-ce7d-4ed0-b163-bb78c01703bf] [localhost] [Mail Intake ]    (0.3ms)  COMMIT
14:22:26 rails.1  | [localhost] [d4c67330-ce7d-4ed0-b163-bb78c01703bf] [localhost] [Mail Intake ] [2018-01-08 14:22:26 -0500]    (0.3ms)  COMMIT
```

**Comment by nemodjuric** [comment]
Caseflow gem ref has to be updated to include necessary caseflow-common changes in order this to work.  See:
https://github.com/department-of-veterans-affairs/caseflow/pull/4305
I'll test this once it's ready, and notify everyone

**Comment by nemodjuric** [comment]
@NickHeiner Try it now, it should work.

**Comment by nickheiner-usds** [comment]
Yep, I see that it's working. Nice!
