### ISSUE TITLE
Daily Docket: update how we display Appellant/Veteran ID

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4173]
As a judge, I'd like to see the Veteran name and the Appellant name indicated on the Daily Docket when they are not the same person.

## AC
1. All names should be styled in title case, and ordered [Firstname Lastname].
1. Display Veteran name in bold, followed by the Veteran ID, when the veteran and appellant are the same person.
1. When the Appellant is not the Veteran, display the Appellant's name in bold on the top line. Below that, display the Veteran name in regular type, followed by the text: '(Veteran)'. Display the Veteran ID on the third line.

## Mocks

_Veteran and Appellant are the same:_
![screen shot 2017-12-15 at 10 03 08 am](https://user-images.githubusercontent.com/4975959/34048061-4636bbae-e180-11e7-9310-43ffd423a719.png)

_Appellant is not the Veteran:_
<img width="730" alt="screen shot 2018-01-12 at 12 43 52 pm" src="https://user-images.githubusercontent.com/4975959/34888867-e3ee1c96-f799-11e7-8175-5ff1fbf828e9.png">

**Comment by nolawi** [comment]
@lakohl `Appellant` is long, some of the names are going to have like 20+ characters

![screen shot 2017-12-22 at 9 13 04 am](https://user-images.githubusercontent.com/1745984/34300934-6adb42c2-e6f8-11e7-93e2-409cb1313581.png)

At the widest browser width, this is how its going to look.

**Comment by Sjones352** [comment]
**FAILED**


Validated in:  Preprod/Chrome 

**This fails in the Preprod** 
Please note there only 2 hearings in Preprod
 
<img width="1141" alt="screen shot 2018-01-23 at 12 00 34 pm" src="https://user-images.githubusercontent.com/23080951/35289906-a8b14e3c-0036-11e8-83fd-bc78243b1d92.png">

**This passes in Demo**

<img width="1187" alt="screen shot 2018-01-23 at 12 04 26 pm" src="https://user-images.githubusercontent.com/23080951/35290153-57cdecb8-0037-11e8-8840-3eae0354818a.png">

**Comment by annienguyenUSDS** [comment]
Header is incorrect in Demo: "Veteran/Veteran ID"
Should be "Appellant/Veteran ID"
<img width="913" alt="screen shot 2018-01-28 at 9 30 59 pm" src="https://user-images.githubusercontent.com/22620270/35491163-bca4b826-0472-11e8-9e51-d90f44aab6a1.png">
