### ISSUE TITLE
Daily Docket: Dropdown should not be Searchable

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4174]
Daily Docket dropdowns should not be searchable. Don't allow judges to type in the dropdown.

_Current:_
![2017-12-15 13 34 28](https://user-images.githubusercontent.com/4975959/34055360-d31c6f66-e19c-11e7-8364-ef554ba11da3.gif)

AC
Use [Regular Dropdown](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#dropdown-menu)

**Comment by Sjones352** [comment]
### PASSED
1. Open dropdown menu
2. Type in something
3. Nothing shows up 

![hearing](https://user-images.githubusercontent.com/23080951/34970430-56948410-fa42-11e7-9fe9-ef6787271532.gif)

**Comment by nolawi** [comment]
passed - closing
