### ISSUE TITLE
Certification | VBMS isn't instantly relaying docs to Certification V2

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#4176]
Currently: When an appeal is missing documents in VBMS, when the user uploads documents in VBMS and goes back to Certification V2 and refresh the page the documents aren't loaded. 

Expected: VBMS talks to Certification immediately. 

Steps to Reproduce: 
1. Find an appeal missing documents in Certification
2. Open VBMS for that environment
3. Add the missing documents to the Veteran's eFolder
4. Refresh the certify appeal page
5. Verify that missing doc page isn't refreshing with uploaded data from VBMS

**Comment by nicholasholtz** [comment]
@amprokop Should this still be an open issue?

**Comment by amprokop** [comment]
Nope.
