### ISSUE TITLE
End Product:  Return to Decision Preview page

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#418]
As a Caseworker, I want to be able to go back to the Decision Preview page so that I can review again the decision information before committing to creating the End Product.  

**Acceptance Criteria**

1. Verify that there is a “Back to preview” link.
2. Verify that when the “Back to preview” link is clicked; the Review Decision page is displayed for the current case.

### Sub-tasks
- [ ] QA Discovery and scripting

**Comment by astewarttistatech** [comment]
Looks good. See attached. 
<img width="1254" alt="screen shot 2016-12-01 at 2 34 37 pm" src="https://cloud.githubusercontent.com/assets/23038505/20809248/895be2f6-b7d3-11e6-888c-dd29199bde1f.png">
