### ISSUE TITLE
Intake | Display a more useful error message if veteran is missing sex identifier

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4184]
If a veteran is missing a sex identifier in the corporate database, the EP creation will fail. We should show users and error messaging telling them to update the Veteran's profile and retry - we can use the same message as Dispatch.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/688/

Dispatch already handles this via: https://github.com/department-of-veterans-affairs/caseflow/pull/2507/files

## Alert copy
Header: 'The Veteran's profile is missing information required to create an EP.'
Body: 'Please update the following field(s) in the Veteran's profile in VBMS or the corporate database, then retry establishing the EP in Caseflow: [name of empty field]'
- If there are multiple required empty fields, separate with semicolon

**Comment by shanear** [comment]
This popped up again today, and it's really annoying to deal with manually. I think we should prioritize it.

**Comment by abbyraskinUSDS** [comment]
@sansb i just updated the copy above

**Comment by shanear** [comment]
setting up the test data is too difficult for this one, and we've validated that this is happening in prod
