### ISSUE TITLE
Dockerize Image Magick Conver

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4186]
Tiff files are the bane of our existence. Since rolling out VVA integration with Reader we first discovered that some of the files were Tiffs, then after converting them with Image Magick found that some of the files were not convertible by the version of linux/version of image magick we were using, then we found that some TIFFs would cause our servers to crash.

Currently conversion is turned off. To provide a more robust fix we will move to dockerize the image-magick conversion. Dockerizing our conversion is useful for several reasons.
1) While not the only way, it enables us to easily control how many CPU and memory resources our process takes.
1) It helps shield us against the ImageTragick vulnerability.
1) It is a nice exemplar of a using docker containers for app code, and gives us a possible route to moving it to kubernetes.
1) A container version of image magick can use older versions of image magick or tiff2pdf to convert some of the older tiff documents.

Design decisions:
1) What should we write this tiny service in?
   - A small Ruby Sinatra app.
1) How should we communicate between our rails app and this converter?
   - POST to localhost:\<port\>/convert-tiff
   - Takes the tiff as a parameter
   - Returns a pdf

Other considerations:
1) We need some way of stoping a convert process if it hangs.

# AC
1) A docker container that responds on localhost:<port>/convert-tiff

**Comment by sunil-sadasivan** [comment]
@mdbenjam if it's helpful for dev... I pushed my docker-compose.yml to a branch I use for my postgres and redis deps within docker containers. 

https://github.com/department-of-veterans-affairs/caseflow/pull/4187/files

**Comment by sunil-sadasivan** [comment]
@mdbenjam this seems good to me, and it'll be a good test.  

Some other open questions:
- Do you plan to separate this to it's own repo, or setup a new dir structure in caseflow.  I can see pros/cons for either approach.  Perhaps for now it'll be good to keep it within caseflow.
- Should we build the docker container on each deploy like we do for envoy and now every local env or start thinking about a registry?  Seems like for now it's ok to build locally/with each deploy.  We can discuss this with @askldjd 

 `POST to localhost:<port>/convert-tiff` seems like a good route to me, especially to keep with a rest interface.  Another route is simply having `convert` in a docker container and passing parameters to the container directly.  I think a simple rest endpoint is cleaner though.

**Comment by nickheiner-usds** [comment]
@mdbenjam did you consider using AWS Lambda as an alternative? It seems like it could provide the isolation you're looking for but could be even simpler.

**Comment by mdbenjam** [comment]
We did talk about that. However, we decided this might be a good exemplar for how to use containers in production. In terms of simplicity, they seem fairly similar to me.

**Comment by nickheiner-usds** [comment]
What are the benefits we're hoping to get from containers in production? (Not trying to push back; just interested in understanding.)

**Comment by askldjd** [comment]
> We need some way of stoping a convert process if it hangs.
You can use [`timeout`](https://linux.die.net/man/1/timeout).

> POST to localhost:<port>/convert-tiff
Many ways to do this. Totally subjective and they all work. 
 - One way is to run your tiff converter with a shared volume mount. This way, you only post the file path name instead of passing binaries back and forth. This translates well in the k8s world where your Pod will have the eX app and the tiff converter as containers in the Pod. Shared volume among containers in a Pod is common practice.
 - Another way is to have your tiff converter upload to S3 and have eX download from S3. This way, you only need to pass object names around.
