### ISSUE TITLE
DateSelector | Use type="date"

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4188]
Currently in the [`DateSelector`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/DateSelector.jsx) component, we have [logic](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/DateSelector.jsx#L12) to parse user-input strings as dates. By setting the input `type` to ["date"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date), we can get a lot for free, including: Calendar dropdown, basic number validation (i.e. day between 1 and 31), and `min` and `max` dates.

Browsers that [don't support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility) this input type (IE and Safari) will fall back to a "text" input. We're already working on blocking IE from reader (#4133), and tell users to use Chrome.

Additionally, `DateSelector` currently returns dates in `mm/dd/yyyy` format, which can be parsed into Dates differently in different environments (moment [#1407](https://github.com/moment/moment/issues/1407#issuecomment-41619352)). Using a date input returns values in ISO8601 format (`yyyy-mm-dd`).

Currently, the only writeable instance of `DateSelector` is within `intake/pages/rampElection/review.jsx`. This dispatches a `SET_RECEIPT_DATE` action, which prepares data for `intake/actions/rampElection.js -> submitReview`, which runs `formatDateStringForApi` on the slash-separated date, transforming it into ISO8601 format using moment.

**Comment by dannysellers** [comment]
Addressed by #1082

**Comment by nolawi** [comment]
There is a new date input[ component in USWDS 2 ](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/date-input.html)

**Comment by dannysellers** [comment]
It looks good, though the validation isn't working quite right for me, and it could use some UX improvements (for example, after typing 2 numbers in the first field I have to manually switch to the next field). That said, it's still in beta, so 👍

<details><summary>gif</summary>
<img src="https://user-images.githubusercontent.com/8533004/46744469-12415b80-cc60-11e8-9f40-ceabfb3cb105.gif">
</details>

**Comment by alisan16** [comment]
Closing as this is now obsolete.
