### ISSUE TITLE
End Product:  Required Fields:  Add required field validation

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#419]
As a Caseworker, I want to have certain fields mandatory for completing so that the minimum required fields for creating the end product has been captured.

# Acceptance Criteria
1. Verify that the following fields has the text "(Required)" next to their labels:  
     - EP & Claim Label
     - Decision Date
1. Verify that after clicking on the **_Create End Product_** button and no value has been selected for the field _"EP & Claim Label"_, the following message is displayed:   Please enter the EP & Claim Label.
1. Verify that after clicking on the **_Create End Product_** button and when no value has enter for the field _"Decision Date"_, the following message is displayed:     Please enter the Decision Date.
1. Verify that after clicking on the **_Create End Product_** button and when an invalid date format has been entered for the field _"Decision Date_", the following message is displayed:     The date must be in mm/dd/yyyy format.
1. Verify that after clicking on the **_Create End Product_** button, all fields not meeting required field validation is displayed with its validation error message.
1. Verify that after clicking on the **_Create End Product_** button, the cursor is taken to the first field with a validation issue.

### Mockup
**_View - Example of Validation Display_**
![image](https://cloud.githubusercontent.com/assets/23063044/20804966/f3239834-b7c2-11e6-892b-869a8caf59b8.png)

### Notes
This feature should perform like Certification.

# Related Issues
EPIC: Decision Review: Ability to review and discern a result for an appeal case https://github.com/department-of-veterans-affairs/appeals-pm/issues/1031
End Product:  Collect information for creating an End Product #416

**Comment by nikitarockz** [comment]
@abbyraskin  Can you help me out with what error messages and validation should for these required fields?

**Comment by abbyraskin** [comment]
I'd assume we'd use a similar error treatment as used in Certification, for example:

<img width="499" alt="screen shot 2016-12-01 at 10 18 47 am" src="https://cloud.githubusercontent.com/assets/4042181/20799247/9b05e05c-b7af-11e6-8ca8-d15a5d2f0292.png">

**Comment by shanear** [comment]
@nikitarockz this should work the same as the form8 form?

**Comment by mdbenjam** [comment]
@nikitarockz  Based on conversation I'm not making modifier or segmented lane required since they have defaults selected. I can change that if desired.

**Comment by kierachell** [comment]
1. Verified that the following fields has the text "(Required)" next to their labels:
        EP & Claim Label
        Decision Date 
        Segmented Lane **need clarification on the latest specs**
        Modifier **need clarification on the latest specs**
<img width="588" alt="screen shot 2016-12-21 at 22 39 31" src="https://cloud.githubusercontent.com/assets/18075411/21414544/64985778-c7ce-11e6-87cc-bc75eb53d87f.png">
__Decision date is pre-populated AND required?__

2. Verified that after clicking on the Create End Product button and no value has been selected for the field "EP & Claim Label", the following message is displayed: Please enter the EP & Claim Label.


<img width="597" alt="screen shot 2016-12-21 at 22 41 17" src="https://cloud.githubusercontent.com/assets/18075411/21414587/ace9757a-c7ce-11e6-920a-4d22a445344f.png">


3. Verify that after clicking on the Create End Product button and when no value has enter for the field "Decision Date", the following message is displayed: Please enter the Decision Date.


**Decision date is pre-populated AND required?**

4. Verify that after clicking on the Create End Product button and when an invalid date format has been entered for the field "Decision Date", the following message is displayed: The date must be in mm/dd/yyyy format.


<img width="580" alt="screen shot 2016-12-21 at 22 43 49" src="https://cloud.githubusercontent.com/assets/18075411/21414608/f80dfbd4-c7ce-11e6-94de-ba052d34742c.png">
Maybe change the wording to 'Invalid Date Entered'? 

5. Verify that after clicking on the Create End Product button and when no value has been enter for the field "Segmented Lane", the following message is displayed: Please select a Segmented Lane.

Similar to *3.* the field is prepopulated.

6. Verify that after clicking on the Create End Product button and when no value has been enter for the field "Modifier", the following message is displayed: Please select a Modifier.

Same as *.3* - the field is prepopulated

7. Verify that after clicking on the Create End Product button, all fields not meeting required field validation is displayed with its validation error message.
<img width="594" alt="screen shot 2016-12-21 at 22 47 55" src="https://cloud.githubusercontent.com/assets/18075411/21414682/8ef12bde-c7cf-11e6-8b7d-418ed7080e5f.png">
Selection *VSO* or *Private* auto-expands new fields - not clear if these fields are required based on selection of POA.

8. Verified that after clicking on the Create End Product button, the cursor is taken to the first field with a validation issue.
<img width="592" alt="screen shot 2016-12-21 at 22 49 51" src="https://cloud.githubusercontent.com/assets/18075411/21414708/d80e1e76-c7cf-11e6-956a-b094b0518361.png">
It works!

**Comment by kierachell** [comment]
Specifications have been verified and adjusted.

Validated on my end.

**Comment by nikitarockz** [comment]
Update Acceptance Criteria.  _"Removed Modifier"_ and _"Segmented lane"_ as being required fields because the dropdown doesn't allow for a blank option value.
