### ISSUE TITLE
Reader Welcome Gate: show link to Hearing Worksheet on all appeals streams heard

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4195]
As a judge/attorney, I would like to be able to access the Hearing Worksheet from the Reader Welcome Gate underneath any of the appeal streams that were included in the hearing. (e.g. not only from the case that triggered the hearing)

## AC 
On the Welcome Gate, show the hearing worksheet link under all appeal streams (docket numbers) included on the hearing worksheet for which all issues therein were not deleted by a judge.

_**example:**_
If there are 2 appeal streams each with 1 issue and the judge does not delete any issues from either appeal stream on the Hearing Worksheet, show the Hearing Worksheet link under both those cases/docket numbers on the Welcome Gate.

If a judge deletes the first and only issue under the first appeal stream, only show the link to the hearing worksheet under the second case/docket number on the Reader Welcome Gate.

**Comment by annienguyenUSDS** [comment]
We should show all Hearing worksheet with appeal stream even if there are no issues for now. 

To follow up, we ask judges how they indicate an appeal stream with no issues was not heard/heard, and how they convey this to their attorneys. If judges do need a way to indicate this, we'll explore where/how they can do this on Hearing Prep (ex. Daily Docket checkbox or Pop-up, and how does colocated get flagged, this such as report that we run?)

**Comment by lakohl** [comment]
We should show the Hearing worksheet on all appeal streams (even if there are no issues) for now.


To follow up, we ask judges how they indicate an appeal stream with no issues was not heard/heard, and how they convey this to their attorneys. If judges do need a way to indicate this, we'll explore where/how they can do this on Hearing Prep (ex. Daily Docket checkbox or Pop-up, and how does colocated get flagged, this such as report that we run?)

**Comment by sharonwarner** [comment]
Dup of #4557
