### ISSUE TITLE
Review Request | First-time election: update Review Request page

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4197]
When processing RAMP forms, I want consistent language across the application, so I can complete my work quickly/accurately.

## Acceptance Criteria
- On the Review Request page, for a first-time RAMP Opt-In Election form, make the following changes to v1:
  - Remove the prompt under the title
  - Switch the order of the two questions
  - Change the wording of first question to match v2: "What is the Receipt Date of this form?"
  - Change the wording of second question to match v2: "Which review lane did the Veteran select?"
  - Change the order of the selection options to match v2: Supplemental Claim, Higher-Level Review, Higher-Level Review with Informal Conference 
 - Title should include the name of the form they selected in first step

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34177898-4469ecbe-e4d3-11e7-9f66-41a8391e10e2.png)

***
## Old version for reference
![image](https://user-images.githubusercontent.com/4042181/34174132-f040b350-e4c5-11e7-9dcf-b6db47cd5be4.png)

**Comment by suzchap** [comment]
1/ In the review lane question, the word Veteran should be capitalized.

<img width="586" alt="screen shot 2018-07-17 at 2 05 56 pm" src="https://user-images.githubusercontent.com/11219417/42836986-a6ddb7c6-89ca-11e8-8e28-b6fb5e1d5c5d.png">

2/ both HLR options should be "Higher-Level Review" (hyphen and all words cap)

**Comment by leikkisa** [comment]
@suzchap 
Validate with Veteran: 561349912

**Comment by suzchap** [comment]
LGTM.
