### ISSUE TITLE
Confirmation:  Successful:  End Product:  Ability to provide a completion notification

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#420]
As a Caseworker, I want to know that my work on this case has been completed successfully so that I can move on to the next case or end my work.

**Acceptance Criteria**

1. Verify that after successfully creating an End Product for an appeal (see: https://github.com/department-of-veterans-affairs/caseflow/issues/417), a Confirmation Congratulations page is displayed.
1. Verify that on the Confirmation Congratulations page, there is a View History link.
1. Verify that on the Confirmation Congratulations page, there is a Establish Next Claim button.
1. Verify that on the Confirmation Congratulations page, the Veteran’s name is displayed in the following text (refer to mockup for details):  “[Veteran First Name] [Veteran Last Name]’s End Product has been created.” 

Mockup
![420 - confirmation - congratulations](https://cloud.githubusercontent.com/assets/23063044/20439059/f2102fba-ad87-11e6-862f-96898bdf09ab.PNG)

**Developer Notes**
- The error scenario will be handled in a future story. For now, just throw an exception.

### Sub-Tasks

- [ ] QA discovery and scripting

**Comment by astewarttistatech** [comment]
**PASSED**

It meets the requirements but the spacing is off from the mock. Please see attached.
<img width="617" alt="screen shot 2016-12-02 at 2 27 11 pm" src="https://cloud.githubusercontent.com/assets/23038505/20847402/e4962bc2-b89b-11e6-96e7-5047294a864f.png">
