### ISSUE TITLE
Loading appeal data lacks error state

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4203]
Loading appeal data on the document list page lacks an error state. It just gets stuck on the loading screen. We need to utilize the `didLoadAppealFail` variable from the state.

![screen shot 2017-12-19 at 5 43 56 pm](https://user-images.githubusercontent.com/3885236/34182460-5a11c71a-e4e4-11e7-87e7-7af0da2ecd1f.png)

**Comment by D-L-Ware** [comment]
Closed as part of clean up of Reader tickets.
