### ISSUE TITLE
Daily Docket: Show Rep Name

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4205]
## AC
Display Rep Name under Rep Org on Daily Docket. Pre-populate Rep Name from the Rep Name field on the Hearing Coordinator view of the VACOLS Virtual Docket.

## Mock
<img width="656" alt="screen shot 2018-01-29 at 10 35 57 am" src="https://user-images.githubusercontent.com/4975959/35518724-54cefac2-04e0-11e8-89c1-41d36afe80ec.png">

**Comment by lakohl** [comment]
update mock to show number of issues. put Rep name on the same line

**Comment by annienguyenUSDS** [comment]
@Sjones352, when it's ready to look at in demo, let us know to check. thanks!

**Comment by Sjones352** [comment]
@lakohl currently it looks like this.
<img width="1109" alt="screen shot 2018-03-20 at 9 00 45 pm" src="https://user-images.githubusercontent.com/23080951/37690714-415113fc-2c83-11e8-98d8-1fe378f36388.png">

**Comment by lakohl** [comment]
@Sjones352 the print version of the Hearing Worksheet looks good! For the Daily Docket, let's try to get the Rep Name on the same line as the City and # of issues (when the Veteran is the appelant).
I'm imagining something like this: 
![dd rep name](https://user-images.githubusercontent.com/4975959/37726092-e6170d9c-2d0a-11e8-854c-35f10c870116.png)

**Comment by Sjones352** [comment]
@lakohl I can create a short PR updating this.

**Comment by Sjones352** [comment]
@lakohl I checked in Demo and this is what it looks like so I may not have to change it.

<img width="1156" alt="screen shot 2018-03-21 at 3 30 00 pm" src="https://user-images.githubusercontent.com/23080951/37774405-7a91e28e-2db6-11e8-89ba-6597dca17e56.png">

**Comment by lakohl** [comment]
The 3 words line up, which is great. So I'll pass this ticket. Next week I'd love to try to find a way to drop them down a few pixels so they line up with the bottom of the dropdown box.

**Comment by annienguyenUSDS** [comment]
Closing this ticket. To address alignment on Daily Docket, ticket here: https://github.com/department-of-veterans-affairs/caseflow/issues/4928
