### ISSUE TITLE
Confirmation | No EP created (ineligible)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4206]
If the Veteran only requests ineligible RAMP issues, the user will see a specific confirmation page that completes intake for that form.  

## Acceptance Criteria
- Verify that if a user selects **only** the ineligible issue(s) checkbox in the previous step, they are navigated to this confirmation page (see mocks/copy below - use styleguide for design)

## Mocks
![image](https://user-images.githubusercontent.com/4042181/34623852-e4a8d23a-f220-11e7-8249-c54f107989a2.png)

## Copy
- Ineligible RAMP request
- The Veteran’s RAMP Selection Form did not include any issues that are eligible for review under RAMP. Notify the Veteran using the “RAMP Ineligible Letter”.
- You can now begin intake for the next RAMP form.

**Comment by leahbannon** [comment]
(to test: RAMP refiling)

**Comment by suzchap** [comment]
Waiting for Sally to set a test ID to have the right criteria.

**Comment by leahbannon** [comment]
this looks good!
