### ISSUE TITLE
Confirmation:  Successful:  Ability to retrieve the next case or not

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#421]
As a Caseworker, I want to be able to quickly move to the next case or stop working after successfully submitting an End Product so that I can continue working case or move onto other tasks.

**Acceptance Criteria**

1. Verify that after clicking on the Establish Next Claim button on the Confirmation Congratulations page, the next Establish Claim task in the queue is assigned to the current user. (use same logic as #438) 
1. Verify that after clicking on the Establish Next Claim button on the Confirmation Congratulations page, the Decision Review page is displayed.
1. Verify that after clicking on the View History link on the Confirmation Congratulations page, the Caseworker Landing page is displayed.

Mockup
![image](https://cloud.githubusercontent.com/assets/23063044/20440480/4b86cfe4-ad8e-11e6-9f6a-6665dbbaceda.png)

### Sub-Tasks

- [ ] QA discovery and scripting

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached.

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached. 

<img width="617" alt="screen shot 2016-12-02 at 2 27 11 pm" src="https://cloud.githubusercontent.com/assets/23038505/20847892/e8e8384e-b89d-11e6-881f-9d56d5a5fde1.png">
