### ISSUE TITLE
Your Hearing Days | Show past hearings in new tab

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4212]
**Story:** 
As a judge, I want to see and access my past hearings a year back from today's date when I view my [upcoming hearings days page](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/hearings/dockets). This helps me be able to consistently find my upcoming and past hearings in one place. As a judge, seeing past hearings may also help jog my memory of hearings held in assigning cases to attorneys, and if I had any updates to the Hearing Worksheet I could do so if I need to.
Many of the support tickets that come in are Judges wanting access to their past hearing days, which this would solve this.

**A/C:**
- [x] Show past hearings in new tab. Show active and inactive tabs according to [styleguide](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#tabs) when clicking on either tab
- [x] "Upcoming" and "Past" title names for the two tabs 
- [x] Titles should be center in the tab
- [x] The table of hearings listed should have a bordered outline with a scroll bar (similar to eFolder express)
- [x] Change showing number of past hearings for the last 60 days to a year/365 days 
- [x] If no past or upcoming hearings, show message in the table: 
Past tab: "You have not held any hearings in the past 365 days." 
For upcoming hearings tab that are not scheduled yet: "You currently have no hearings scheduled."

**Current Mock:**
<img width="1058" alt="screen shot 2017-12-20 at 4 21 14 pm" src="https://user-images.githubusercontent.com/22620270/34229326-d8ef4126-e5a1-11e7-8d9c-6e55352cb14b.png">

**Desired Mock:**
"Upcoming" Tab: 
<img width="648" alt="screen shot 2017-12-20 at 5 02 47 pm" src="https://user-images.githubusercontent.com/22620270/34230906-e913ff32-e5a7-11e7-8daa-7763addec539.png">

"Past" Tab:
<img width="658" alt="screen shot 2017-12-20 at 5 02 58 pm" src="https://user-images.githubusercontent.com/22620270/34230908-ebc2ee82-e5a7-11e7-9d09-26ee1d69ba34.png">

**Comment by annienguyenUSDS** [comment]
@tejans24 let me know when this is ready to check in demo to validate. thanks!

**Comment by lakohl** [comment]
@tejans24 this is looking good, but can we get rid of the line that shows directly under each tab and above the table headers?

**_Current:_** 
![fireshot capture 16 - your hearing days_ - http___dsva-appeals-certification-](https://user-images.githubusercontent.com/4975959/37548169-7ad62480-294c-11e8-956c-c9fdc689efea.png)

![fireshot capture 15 - your hearing days_ - http___dsva-appeals-certification-](https://user-images.githubusercontent.com/4975959/37548150-5079e7ee-294c-11e8-86b3-b06e9d357c95.png)

**_Desired_**

<img width="648" alt="screen shot 2017-12-20 at 5 02 47 pm" src="https://user-images.githubusercontent.com/22620270/34230906-e913ff32-e5a7-11e7-8daa-7763addec539.png">

<img width="658" alt="screen shot 2017-12-20 at 5 02 58 pm" src="https://user-images.githubusercontent.com/22620270/34230908-ebc2ee82-e5a7-11e7-9d09-26ee1d69ba34.png">

**Comment by lakohl** [comment]
@tejans24 We just need to get rid of the extra line under the tabs

**Comment by annienguyenUSDS** [comment]
@tejans24, still see the line on "Your Hearing Days" table, if you can check this.
