### ISSUE TITLE
Hearing Worksheet: Allow the judges to copy/paste the Vet ID

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4218]
## AC
Hearing Worksheet: Allow the judges to copy/paste the Vet ID - use caseflow commons styling.
Ask judges where they might paste the vet ID and when it requires modification.

## Mock:
<img width="816" alt="screen shot 2017-12-05 at 5 01 59 pm" src="https://user-images.githubusercontent.com/4975959/34488416-7583c36e-efa6-11e7-9908-2d7cfb012b2f.png">

**Comment by Sjones352** [comment]
This passes in Demo so maybe we should consider it until documents are loaded for hearing-prep.

![hearing2](https://user-images.githubusercontent.com/23080951/34970762-3885f92a-fa44-11e7-82ae-6cac9aab5d4b.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome

Steps to Validate:

1. Access Hearings
2. Open a docket for an Appellant 
3. Navigate to Hearing Worksheet for Appellant. 
4. Verify that veteran ID is copied to clipboard upon initial click
5. Verify that upon pasting, that what was copied is the veteran ID. 

Screenshots: 
<img width="1380" alt="screen shot 2018-01-16 at 11 50 09 am" src="https://user-images.githubusercontent.com/23038505/35001115-17673afe-fab4-11e7-9e23-c15c60c4f3fc.png">
