### ISSUE TITLE
Confirmation:  Successful:  RO Routing:  Ability to provide a completion notification

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#422]
As a Caseworker, I want to know that I have successfully routed my current case, so that I can move on to the next case or end my work.

### Acceptance Criteria

1. Verify that when a RO Routing has been submitted successfully, a Confirmation “Congratulations” page is displayed.
2. Verify that when a RO Routing has been submitted successfully, the Veteran’s name, Case #, and Routing Destination is displayed in the following (refer to mockup for details):   “You have routed [Case #] for [Veteran First Name] [Veteran Last Name] to [Routing Destination].”   (??? This probably will need to be changed.)
4. Verify that when a RO Routing has been submitted successfully, the following listing of completed tasks are displayed:  (???? Need to get list for Routed case.)

### Related Issues
EPIC: Decision Review: Ability to review and discern a result for an appeal case https://github.com/department-of-veterans-affairs/appeals-pm/issues/1031

**Comment by KHarshawat** [comment]
There are several different states this message can be in depending on the circumstances of the claim. 

If the claim is re-routed and is a full grant we should show something like this, where the Station ID (or RO) the appeal is re-routed to is displayed in the second line.

![congrats rerouted - full grant](https://cloud.githubusercontent.com/assets/6335546/20768194/fc95696e-b70a-11e6-9f1d-65ac19e10ee8.png)

If the claim is re-routed and is a partial grant or remand we should show something like this, where the Station ID (or RO) the appeal is re-routed to is displayed in the second line and the location number could be `50`, `51`, `54` or `70`
![congrats rerouted - partial grant or remand](https://cloud.githubusercontent.com/assets/6335546/20768195/fd7d5c92-b70a-11e6-9d78-3355e1965baf.png)

**Comment by KHarshawat** [comment]
If we're logging the different actions that occur on the appeal we could simply tie the messages we display in the confirmation to the those actions.

**Comment by KHarshawat** [comment]
@nikitarockz back to you to figure out what you want to do with this.

**Comment by shanear** [comment]
We aren't routing to ROs. Closing
