### ISSUE TITLE
SPIKE | 3-way conference hearing

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4221]
We've heard from Judges it's useful to know if there's a 3-way conference call with satellite RO or medical centers, because it will add time to deal with tech issues to set-up before hand. Judges and coordinators might hear this case last or first based on this type of call. Sometimes ROs note that in Notes on DD. 
Wondering how we can surface this info or pull that in or put that somewhere for hearing prep.

Does VACOLS provide the location(s) for a 3-way or satellite office video conference hearing?

**Comment by lakohl** [comment]
@sharonwarner 
1. where if anywhere is it indicated in VACOLS that a hearing is a multi-point hearing (3-way)?
1. is it indicated in VACOLS if the hearing takes place at a satellite location?
1. or are the above only indicated in the Daily Docket notes?
