### ISSUE TITLE
Daily Docket: Show Hold Open 0 Days when selected from the dropdown

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4223]
Under Hold Open, when a user selects 30, 60, or 90 days from the dropdown and then switches their selection to '0 Days' in order to null their previous selection, the selection field should display '0 days' (not Select...).  In the .gif below the AOD dropdown behaves as expected.

![2017-12-21 14 20 39](https://user-images.githubusercontent.com/4975959/34271574-d049aafc-e65a-11e7-94e5-0c9aa077172d.gif)

**Comment by Sjones352** [comment]
**PASSED**


Validated in:  Preprod/Chrome 

Steps to Validate: 
1. Access Hearing-Prep
2. On Hold Open 30, 60, or 90 days from the dropdown menu
3. Validate that when 0 days is selected, Select is not displayed.


![hearing](https://user-images.githubusercontent.com/23080951/35287935-80d5f99e-0031-11e8-8313-3c8b8e8b86f2.gif)
