### ISSUE TITLE
Daily Docket: Adjust spacing above 'Issues'

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4226]
Daily Docket: Adjust spacing between dropdown label and dropdown.

Issues should be plural if its more than one. 

_**Current**_
<img width="1172" alt="screen shot 2018-01-10 at 3 32 19 pm" src="https://user-images.githubusercontent.com/4975959/34834499-1b1849b0-f6c0-11e7-81e9-747c76c82584.png">

_**Desired**_
<img width="827" alt="screen shot 2018-01-11 at 12 50 27 pm" src="https://user-images.githubusercontent.com/4975959/34838978-0a27445e-f6ce-11e7-9c11-ea348a971c50.png">

**Comment by lakohl** [comment]
Add to Style Guide

**Comment by lakohl** [comment]
@Sjones352 can you post a screenshot of this when you think you are done?

**Comment by Sjones352** [comment]
This has already been done by @nolawi but here is a screenshot adjusting it to `margin-bottom: 5px ` from 8px.
<img width="1187" alt="screen shot 2018-03-09 at 8 41 53 am" src="https://user-images.githubusercontent.com/23080951/37210182-caf57222-2375-11e8-9716-c13cb5826547.png">

**Comment by lakohl** [comment]
@Sjones352 the space between issues and notes is looking much better. When you expand the window a bit more to the right 'Notes' and 'Transcript Requested' Should show on the same line.

**Comment by Sjones352** [comment]
@lakohl something like this.
<img width="1087" alt="screen shot 2018-03-09 at 1 44 08 pm" src="https://user-images.githubusercontent.com/23080951/37223930-08034e1c-23a0-11e8-82ec-9d2cdeb31bf5.png">

**Comment by lakohl** [comment]
Yes.

**Comment by lakohl** [comment]
Looks good. Will make another ticket for the Transcript portion.
