### ISSUE TITLE
start_certification_job.rb - ArgumentError: wrong number of arguments

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#4227]
Link to: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/770/

This error lines up with with [deploy](https://appealsjenkins.ds.va.gov/job/deploys/job/prod/job/certification/17/console). I think we broke hot-compatibility by removing arguments to a Sidekiq job.

It is a one-time error, but we may consider reaching out to the affected user.

**Comment by amprokop** [comment]
Closing, this should have been cleared up when the user refreshed. 👍
