### ISSUE TITLE
Hearing Worksheet: Move Autosave above the canvas

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4230]
## AC
1. Move the 'Last Saved' copy to display outside the canvas in the top right. (DailyDocket & Worksheet)

## Mock
<img width="532" alt="screen shot 2018-01-02 at 4 05 32 pm" src="https://user-images.githubusercontent.com/4975959/34500220-cd4c4d7e-efd7-11e7-8f57-8f4702cec7e6.png">

**Comment by lakohl** [comment]
@annienguyenUSDS  Here are two options:

**option 1**
![screen shot 2018-01-05 at 2 07 54 pm](https://user-images.githubusercontent.com/4975959/34624142-2d378c3e-f222-11e7-825b-fe112bc90791.png)

**option 2**
![screen shot 2018-01-05 at 2 07 25 pm](https://user-images.githubusercontent.com/4975959/34624152-3adfc66c-f222-11e7-9c59-1007127f3683.png)

**Comment by annienguyenUSDS** [comment]
@lakohl leaning towards option 1

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing Prep
2. Navigate to an Appellant's worksheet
3. Verify the placement of Autosave message. 

Screenshot: 
<img width="1384" alt="screen shot 2018-01-08 at 9 17 35 am" src="https://user-images.githubusercontent.com/23038505/34674713-f3c0d98a-f454-11e7-90cf-fff3c0170ae8.png">
