### ISSUE TITLE
Hearing Prep - Update "Autosave" text color and adjust position

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4231]
## AC
1. Update "Last saved at 3:21 pm" text color from #323a45 (doesn't exist in style guide) to #d6d7d9 that exists in Caseflow Common's [style guide](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#typography).

2. Last Save text should be ten pixels above white box.

Related [#559](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/559)

## Current mock:

<img width="970" alt="screen shot 2017-12-21 at 4 03 50 pm" src="https://user-images.githubusercontent.com/22620270/34275016-6bb9020e-e669-11e7-8310-9f32947a6e39.png">

## Desired
![screen shot 2018-01-15 at 11 41 27 am](https://user-images.githubusercontent.com/4975959/34952819-038d1308-f9e9-11e7-980c-451015ced865.png)

**Comment by nolawi** [comment]
is this global, including the worksheet header?

**Comment by annienguyenUSDS** [comment]
Yes, that current text color isn't in style guide and want to make it consistent.

**Comment by lakohl** [comment]
@annienguyenUSDS I edited the AC to make it a darker styleguide color, bc moving the Saving message means putting it on a grey background and the original choice was too light for 508 compliance.

**Comment by Sjones352** [comment]
@annienguyenUSDS and @lakohl which text color should it be updated to.
 Currently this is the text-color #5b616b in pre-prod

<img width="1257" alt="screen shot 2018-01-23 at 5 45 40 pm" src="https://user-images.githubusercontent.com/23080951/35306130-4d1d330e-006a-11e8-9d2f-96096dad64c4.png">

**Comment by lakohl** [comment]
@Sjones352 the StyleGuide color for Gray is 5B616B

**Comment by Sjones352** [comment]
**PreProd**
<img width="1220" alt="screen shot 2018-01-29 at 9 29 37 pm" src="https://user-images.githubusercontent.com/23080951/35546502-6b54f14a-0542-11e8-977c-b482c15af0af.png">




**UAT**
<img width="1098" alt="screen shot 2018-01-29 at 10 38 14 pm" src="https://user-images.githubusercontent.com/23080951/35547110-350ff1a4-0545-11e8-9fac-d52b38ccd89f.png">

**stage/canvas**
<img width="1201" alt="screen shot 2018-01-29 at 8 56 59 pm" src="https://user-images.githubusercontent.com/23080951/35547171-768497ca-0545-11e8-8748-46aaecca940d.png">

**Comment by lakohl** [comment]
yes. the margin brtwn the top bar and the canvas should be 40px on both pages. 'Last Saved...' should be anchored to the canvas on both pages, so it's right above it, not floating closer to the to bar w/logo as it is now.

**Comment by Sjones352** [comment]
**PASSED**
Validate/chrome


**PreProd**
<img width="1220" alt="screen shot 2018-01-29 at 9 29 37 pm" src="https://user-images.githubusercontent.com/23080951/35546502-6b54f14a-0542-11e8-977c-b482c15af0af.png">


**UAT**
<img width="1098" alt="screen shot 2018-01-29 at 10 38 14 pm" src="https://user-images.githubusercontent.com/23080951/35547110-350ff1a4-0545-11e8-9fac-d52b38ccd89f.png">

**stage/canvas**
<img width="1201" alt="screen shot 2018-01-29 at 8 56 59 pm" src="https://user-images.githubusercontent.com/23080951/35547171-768497ca-0545-11e8-8748-46aaecca940d.png">
