### ISSUE TITLE
Hearing Worksheet | Clean up Header and Veteran Info

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4233]
Hearing Worksheet: Clean up Header and Veteran Info to sync with the way that judges read this information for the transcript during the hearing

## AC
1. Update the h1 to align with Reader by displaying the Veteran's name. It should read '[FirstName LastName's] Hearing Worksheet'.
1. Update styling of the labels for hearing and Veteran information to: all caps, 13px, color:5B616B
1. Display the hearing and Veteran info in 5 columns
1. Re-order the hearing and Veteran info as shown in the 'desired' mock
1. Put pre-populated Representative Org info in a text box.
1. Add a box for Additional Notes.
1. Add non-editable Representative Org. label and info to the right of the City/State.
1. Group the data-entry boxes Representative Name (shorter - to accommodate 30 characters) and Witness (W)/Observer (O), Additional Details (vertically expandable to accommodate up to 130 characters) below the Veteran Info.
1. Move Periods and Circumstances of Service up the page to display below the Representative and Witness. 

## NEW Mocks
![hearing worksheet top 2](https://user-images.githubusercontent.com/4975959/39606660-8877ff90-4f04-11e8-9675-cc9ab97df3ee.png)

Current:
![vet top](https://user-images.githubusercontent.com/4975959/36034003-8fb6c040-0d80-11e8-8c61-650357b705c0.png)

Measurements: https://github.com/department-of-veterans-affairs/caseflow/issues/5101

Design ticket: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/585

**Comment by lakohl** [comment]
<img width="703" alt="screen shot 2018-01-11 at 1 02 19 pm" src="https://user-images.githubusercontent.com/4975959/34839592-1cc7bcfe-f6d0-11e7-9815-3c689cb594ad.png">

**Comment by annienguyenUSDS** [comment]
I like this! The bold titles help with scanning. 
The 233 Documents is called out in the title as well as Docket number.  It's hard to find currently.
Looks like we are listing dates as 01/01/1990, should we do this on Daily Docket? 
Also, are people familiar with term "Case Summary" or is it something we want them to use "Key Documents"?
We a support ticket that an attorney couldn't distinguish between Veteran's City/State and RO location, so this would help separate the two.

**Comment by lakohl** [comment]
Agree that we should be consistent about how we display the date. I think that 01/01/1990 is the safest bet, but am open to other arguments.
Right now Key Documents and Case Summary are not the same, but it might be helpful to ask about the usefulness of Key Documents again, now that Case Summary Exists. Case Summary is our made-up term.
Re: location we should verify where this is pulled from. It seems that it should relate to the appellant (not the veteran).

**Comment by lakohl** [comment]
add extra notes box mock

**Comment by lakohl** [comment]
Make 5 columns and Overall Rating

**Comment by annienguyenUSDS** [comment]
Reference measurements layout listed in this ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/5101

**Comment by tejans24** [comment]
@annienguyenUSDS @lakohl We don’t have a form inline textboxes in the Styleguide (http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide) or in uswds standards (https://designsystem.digital.gov/components/form-controls/#text-input) . Do we for sure want to introduce to introduce it here?

**Comment by lakohl** [comment]
@tejans24 We don't know how to pull the Veteran Disability rating yet, so I'm going to take that line out of the AC.

**Comment by annienguyenUSDS** [comment]
@sharonwarner is there a character limit only for rep name, correct? 
Rest of them don't have character limits since we don't write back?

**Comment by sharonwarner** [comment]
They all will have character limits. Witness is currently 120, and rep name is 30. I'll have to look up what the limit for rep org is, and we can decide together for additional notes.

**Comment by annienguyenUSDS** [comment]
@sharonwarner , if you can make some adjustments, and show the mock: 
- Make "Representative Name" and "Representative Org" the length of the max characters.
- Make the boxes closer to the "Representative Name". 
- Reference measurements here to tighten: https://github.com/department-of-veterans-affairs/caseflow/issues/5101
- Include "Periods and circumstances of service" and the box.

**Comment by lakohl** [comment]
@annienguyenUSDS here are the two solutions drawn out:
![hearing worksheet top shrunk](https://user-images.githubusercontent.com/4975959/39582139-49e69faa-4ebb-11e8-9364-2c1ef8036fcf.png)

![hearing worksheet expanded](https://user-images.githubusercontent.com/4975959/39582147-5045533c-4ebb-11e8-80de-5356c2e66652.png)

![labels on top](https://user-images.githubusercontent.com/4975959/39582174-605e37c0-4ebb-11e8-8b87-edf834aabfba.png)

**Comment by lakohl** [comment]
Actual character counts could look like this
![hearing worksheet field capacity](https://user-images.githubusercontent.com/4975959/39583010-24e29f5e-4ebd-11e8-9434-72214cd68c28.png)

**Comment by lakohl** [comment]
@sharonwarner would you mind checking the Rep Org character count?
