### ISSUE TITLE
Confirmation:  Unsuccessful:  RO Routing:  Ability to provide an incompletion notification

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#424]
As a Caseworker, I want to know that I have unsuccessfully routed my current case, so that I can correct the issues and resubmit the routing.

**Acceptance Criteria**

1. Verify that when a RO Routing has been submitted unsuccessfully, a Confirmation “Unsuccessful Submission” page/modal is displayed. (??? Confirm title of page/modal.)
2. Verify that when a RO Routing has been submitted successfully, the Veteran’s name, Case #, and Routing Destination is displayed in the following (refer to mockup for details):  “The [Case #] for [Veteran First Name] [Veteran Last Name] was not successfully to [Routing Destination] due to the following issues.”   (??? This probably will need to be changed.)
4. Verify that when a RO Routing has been submitted unsuccessfully, the following listing of completed tasks are displayed indicating whether successful or not:  (???? Need to get list for Routed case.)

**Comment by KHarshawat** [comment]
What are the reasons that something could be unsuccessfully routed? If this is because of an integration issue we should show the integration error message. https://github.com/department-of-veterans-affairs/caseflow/issues/471

There are multiple success states for RO routing described in https://github.com/department-of-veterans-affairs/caseflow/issues/422

**Comment by nikitarockz** [comment]
@abbyraskin  Are you able to answer some of these questions?

**Comment by abbyraskin** [comment]
Right, i think it would be an integration/backend issue.

**Comment by KHarshawat** [comment]
Got it. Then this is redundant with https://github.com/department-of-veterans-affairs/caseflow/issues/471 and we should close this issue.

**Comment by shanear** [comment]
We aren't routing to ROs. Closing
