### ISSUE TITLE
Demo: Add users to the Dispatch Manager Dashboard

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4245]
It's not possible to test/view this functionality in Demo with no users logged in.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Demo | Chrome 

Steps to Validate: 
1. Access the Demo env. 
2. Switch User to be a Dispatch manager
3. Navigate to the Work Assignments page
4. Make sure seed data is there 

Screenshots:
<img width="1430" alt="screen shot 2018-01-12 at 10 45 31 am" src="https://user-images.githubusercontent.com/23038505/34883025-54c9212c-f786-11e7-9036-9f029d8ba9f2.png">
