### ISSUE TITLE
v2 API includes date the data was updated

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4251]
## AC
* The appeal should return an `updated` attribute, which should be the ISO8601-formatted time the data was last updated (use Eastern time).
* If the response has been cached, `updated` should be the time the response was generated, not the time it was retrieved from cache.
* The cache time should be lowered from 24 hours to 20 hours, so that a user who checks their status at the same time every day is refreshed every day.

**Comment by Sjones352** [comment]
**PASSED**
<img width="887" alt="screen shot 2018-01-28 at 11 03 01 am" src="https://user-images.githubusercontent.com/23080951/35527732-b331d076-04f9-11e8-9651-4f1a7ca97f72.png">
