### ISSUE TITLE
Create Queue app skeleton

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4254]
## Acceptance Criteria
- Create Queue app which should be available to System Admins at appeals.cf.ds.va.gov/queue.
- The title of the page is "Your queue".
- A table should be present.

### Queue table
![mvp_table-not-measured](https://user-images.githubusercontent.com/31224257/35051452-3f54314c-fb73-11e7-9236-9428c33e7763.png)

### Queue table (with measurements)
![mvp_table-measured](https://user-images.githubusercontent.com/31224257/35051482-4d0e7504-fb73-11e7-9030-b37a9435de35.png)

### Components utilized:
Caseflow Navigation Bar
Search Bar
Table Component - Customized for Queue
Footer

### Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white
$color-secondary

**Comment by dannysellers** [comment]
## AC
- [ ] Navigate to `/queue`
- [ ] See task/appeal data for user dumped to screen as block of JSON

**Comment by Sjones352** [comment]
**PASSED**

Validate/Chrome
1. Navigate to `/queue` as System Admin
2.  Verify table matches mockup (besides Reader document count)

<img width="1239" alt="screen shot 2018-02-01 at 6 37 06 pm" src="https://user-images.githubusercontent.com/23080951/35709533-f6f871d2-0780-11e8-9a9e-1e3b8c944e80.png">
