### ISSUE TITLE
Queue table | Sort attorney tasks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4256]
When an attorney looks at their queue of appeals, they want to see highest priority Veterans at the top, so they can work on highest priority decisions first.

Sorting hierarchy as follows:
- Group AOD veterans and CAVC remands - they are highest priority
  - Sort oldest to newest docket date (form 9 date) within this group
- Group all other appeals (originals, remands, etc.)
  - Sort oldest to newest docket date (form 9 date) within this group

## Acceptance Criteria
- Verify that attorney appeals are sorted according to the hierarchy above.

### "Your Queue" Table
![mvp_table](https://user-images.githubusercontent.com/31224257/35004592-aa091396-fabe-11e7-9849-2005b14f9d5a.png)

### "Your Queue" Table - With measurements
![mvp_table-measured](https://user-images.githubusercontent.com/31224257/35014096-7ddfdf4c-fadd-11e7-98de-29c871721881.png)

## Components utilized:
Caseflow Navigation Bar
Search Bar
Table Component - Customized for Queue
Footer

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white
$color-secondary

**Comment by Sjones352** [comment]
@dannysellers and @laurjpeterson has this changed because currently this is what I see.

<img width="1239" alt="screen shot 2018-02-01 at 6 37 06 pm" src="https://user-images.githubusercontent.com/23080951/35709766-0a8421b4-0782-11e8-9c69-5b1ce0dd5fa7.png">

**Comment by Sjones352** [comment]
**PASSED**
Validate/ Chrome
1. Access Queue
2. Validate Group AOD veterans and CAVC remands - they are highest priority
```Sort oldest to newest docket date (form 9 date) within this group```
3. Validate Group all other appeals (originals, remands, etc.)
```Sort oldest to newest docket date (form 9 date) within this group```

<img width="1279" alt="screen shot 2018-02-04 at 5 02 15 pm" src="https://user-images.githubusercontent.com/23080951/35782884-3e537e98-09cd-11e8-85d1-2d05a1459a83.png">
