### ISSUE TITLE
Queue table | Link to Reader

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4257]
When an attorney is looking at their queue and is getting ready to start a draft decision task, they want to quickly access Reader to review documents, so they can write the decision draft. 

## Acceptance Criteria
- A link to 'X' docs in Reader exists for each appeal in the table
- Reader opens in the same tab
- Verify that Reader opens to the correct Veteran's claims folder
- If error with call to eFolder to get the number of documents, change copy in Reader per mocks below. The user should still open to the correct Veteran's claims folder in Reader.

### "Your Queue" Table
![mvp_table](https://user-images.githubusercontent.com/31224257/35004592-aa091396-fabe-11e7-9849-2005b14f9d5a.png)

### "Your Queue" Table - With measurements
![mvp_table-measured](https://user-images.githubusercontent.com/31224257/35014096-7ddfdf4c-fadd-11e7-98de-29c871721881.png)

### "Your Queue" Table, when call to VBMS fails
![mvp_table_vbms-load-fail](https://user-images.githubusercontent.com/31224257/35014104-831feb3c-fadd-11e7-93df-c70804449336.png)

## Components utilized:
Caseflow Navigation Bar
Search Bar
Table Component - Customized for Queue
Footer

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white
$color-secondary

## Technical Notes
- Make call to eFolder

**Comment by amprokop** [comment]
@sneha-pai @laurjpeterson — so if the eFolder call fails we should display "View in Reader"  instead of #. Should we display "View in Reader" before the eFolder call finishes as well?

**Comment by laurjpeterson** [comment]
@amprokop - would the user be able to navigate to Reader before the eFolder call finishes?

**Comment by dannysellers** [comment]
@laurjpeterson We can create a link to Reader regardless of whether the document count loads, yeah. What should link text be if there's an error? I've just set it to "View in Reader" for now.

**Comment by laurjpeterson** [comment]
@dannysellers - if there is an error, yes, 'View in Reader'. And to @amprokop's question - yes, we should display "View in Reader" before the eFolder call finishes as well. Thank you!

**Comment by Sjones352** [comment]
**PASSED**

Validate Uat/Chrome
1. Access Queue
2. Verify line View 'x' in Reader
3. Verify that Reader opens to the correct Veteran's claims folder

![queue](https://user-images.githubusercontent.com/23080951/35711105-2d61c798-0789-11e8-94b9-9382d463bc5a.gif)
