### ISSUE TITLE
Queue table | Ready for judge review

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4263]
When an attorney finishes drafting a work product, they want to give it to a judge for review right from their Queue, so they have a quick way to move the appeal to the next step in the appeals process.

We've learned that work products are draft decisions - which could have a variety of dispositions (grant, deny, remand) - and draft requests for outside medical opinions (OMO). We can auto-calculate the work product from issue dispositions, so want to simplify the flow for attorneys to choose decision or OMO, then progress through the check out flow.

### Acceptance Criteria
- [ ] Verify that there is a column labeled "Action"
- [ ] Verify that clicking the drop down expands and shows two options: 
        -"Ready for Decision Review" 
        - "Ready for OMO Review"
- [ ] Verify that when "Ready for Decision Review" is selected the user is taken to "Select Dispositions" in the same window #4471 
- [ ] Verify that when user select "Ready for OMO Review" it takes them to the "Submit OMO Page" in #4465  

### React Components Used
- Everything from Queue Table
- Dropdown

#### Table View with Dropdown
![dropdown - mvp queue table](https://user-images.githubusercontent.com/23316107/35997496-a9f79022-0ce7-11e8-82b2-25449de10117.png)

![dropdown selection - queue mvp table](https://user-images.githubusercontent.com/23316107/35997527-bf137ad4-0ce7-11e8-9a2d-6dcaa826c6a8.png)

## Related Issues
#4471 - Enter Issue Dispositions 
#4465 - Submit OMO and Draft Decision Review

**Comment by Chingujo** [comment]
@laurjpeterson @sneha-pai 

In the mocks we have a dropdown but we only have one action: Ready for Judge Review. I mocked a button and a dropdown view of this. We can do one of the following:
-  go with the button/link (makes sense UX wise) 
-  have a dropdown with one action anticipating the addition of more 
- change the button to a dropdown when we actually have more than one action later

**Comment by laurjpeterson** [comment]
@Chingujo I updated the story and AC to reflect our new check out flow - feel free to update the mocks when they're ready!
