### ISSUE TITLE
Demo | Can't open Hearing Worksheet Link in Welcome Gate (Reader)

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4267]
To access past hearing worksheets in Reader/Welcome Gate demo, I click on the worksheet link and it opens a new tab with an error. 

http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/hearings/84/worksheet/print

QA AC:
* Go to Demo Reader Case Select page
* Click on the Hearing prep worksheet links
* They should take users to a worksheet print page and doesn't error out

**Comment by Sjones352** [comment]
### PASSED
In chrome/Safari
1.Go to Demo Reader Case Select page
2.Click on the Hearing prep worksheet links
3. Takes you to a worksheet print page and doesn't error out.


![reader](https://user-images.githubusercontent.com/23080951/34997535-b9aee320-faaa-11e7-9805-b575dc8adfa6.gif)
