### ISSUE TITLE
When denied permission user should be informed.

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4280]
Before showing a user a case file we need to ensure that they have access to the veteran's file. eFolder does this check and returns a 403 if the user does not have permissions. We catch the error in Caseflow and then throw `Caseflow::Error::EfolderAccessForbidden` https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/efolder_service.rb#L19 

This error is caught here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/reader/documents_controller.rb#L25.

Instead of a generic error message, we should inform the user that they do not have access to view this case file.  Currently our error looks like this:

<img width="1016" alt="screen shot 2018-01-31 at 4 25 43 pm" src="https://user-images.githubusercontent.com/3885236/35648335-6ce9c2b2-06a3-11e8-87f0-58e28ef59344.png">

We should have a separate error message that says:
Heading: Access Denied
Body: It looks like you do not have the necessary level of access to view this claims folder.

**AC**
1) Verify when `Caseflow::Error::EfolderAccessForbidden` is thrown, we see the above error message with the provided text.

**Comment by evankroske** [comment]
The error was a 500:

```
I, [2018-01-04T14:51:23.664240 #3155] INFO -- : SOAP response (status 500)
D, [2018-01-04T14:51:23.664318 #3155] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>No Person record found</faultstring><detail><ns2:ShareException xmlns:ns2="http://services.share.benefits.vba.va.gov/"><message>No Person record found</message></ns2:ShareException></detail></S:Fault></S:Body></S:Envelope>
```

From the Efolder CloudWatch logs

**Comment by mdbenjam** [comment]
Hmmm that's interesting, looks like when our connect_bgs gem receives a 500 from BGS when it tries to determine permissions then it assumes it's access denied. If this keeps coming up I'll file a bug.

**Comment by oscarAtNava** [comment]
To fix this properly we will need to remediate more than just one React component. The error message is displayed using a common component called LoadingDataDisplay. This component is used by several screens, such as: QueueLoadingScreen.jsx, CaseSelectLoadingScreen.jsx and ReaderLoadingScreen.jsx. In all cases the detail screens format the error message which the common component, LoadingDataDisplay.jsx, displays. All is fine and dandy except...

The detail screens define a promise that is only executed within the common component. The promise definition includes a service call specific to the detailed screen. The detailed screen formats a generic error message today. If we want to make the message reflect the status code returned by the service executed in the promise, the errors need to be formatted where the promise is executed, that is in the common component: LoadingDataDisplay.jsx.

I plan to move the error message formatting to the common component, defining some specific error messages that align with the error codes. I will have to change not only the original component identified in this ticket but the other components I mentioned above.

Please shout if you have any comments or other suggestions.
