### ISSUE TITLE
Dispatch is throwing: Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8 

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#4290]
Properly handle: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/822/
  
This is causing dispatch to error. 

In further digging I noticed caseflow commons was recently updated in the last deploy, and logic to the S3 service `store_file` method was adjusted.

https://github.com/department-of-veterans-affairs/caseflow-commons/pull/124

**Comment by lowellrex** [comment]
I'm fairly certain [caseflow commons 131](https://github.com/department-of-veterans-affairs/caseflow-commons/pull/131) resolved this issue, so we can close this out.
