### ISSUE TITLE
Reader | Scroll to X position for comments / search results

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4292]
When a document's zoomed in until it's wider than the viewport (reenabled by #4235), jumping to an annotation / between search results only scrolls the document vertically. [`PdfFile.jumpToComment`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/reader/PdfFile.jsx#L157) and the `setDocScrollPosition` flow ([`PdfPage.highlightMarkAtIndex`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/reader/PdfPage.jsx#L56), [`PdfFile.scrollToSearchTerm`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/reader/PdfFile.jsx#L204), [`PdfViewerActions.setDocScrollPosition`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/reader/PdfViewer/PdfViewerActions.js#L49)) should be updated to scroll along the x-axis.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
