### ISSUE TITLE
Finish Refiling | Show error message on unknown error

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4293]
## Acceptance Criteria
- When submitting a ramp refiling, there should be an error message if the server has an unknown error. This message should look like the one on the Ramp Election finish page:

![screen shot 2018-01-08 at 1 55 44 pm](https://user-images.githubusercontent.com/1596259/34687067-a37adfe4-f47b-11e7-982a-cb0633a6c06f.png)

see: https://github.com/department-of-veterans-affairs/caseflow/pull/4272#discussion_r159923315

**Comment by suzchap** [comment]
Waiting for Sally to set a test ID to have the right criteria.

**Comment by leikkisa** [comment]
We will need to validate this locally since we need to create an unknown error.  However, to validate this locally I need to figure out how to make a decision on a RampElection locally (since that happens outside of Caseflow).

**Comment by leikkisa** [comment]
@leahbannon 
I think this is ready to validate this on my local environment with test file number 239120550. We'll want to pair on this.

**Comment by shanear** [comment]
This has been deployed for months. We can assume it's working correctly
