### ISSUE TITLE
Styleguide | Adding color

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4296]
Adding Gray color #f1f1f1 to primary color section of caseflow styleguide (http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#colors). 
This color is used as the background in Hearing Prep Daily Docket to distinguish between actions on the page.

**Comment by nolawi** [comment]
Looks like $color-gray-lightest:   #f1f1f1 !default; is in USWDS now. we can close this.
