### ISSUE TITLE
Feature Flag | Enable Group 8 – RMC users on 1/8/2018

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4297]
I would like the following feature flag enabled on 1/8/2018 as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  eFolder Express - VVA  

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following users only.

"DIRAGEIS", "DIRAJOHN", "VBARMCLASLES", "VBARMCBARNEA", "VBARMCMIKEM", "VBARMCDAVISL", "VBARMCRAUHUL", "VBARMCMALOND", "VBARMCSETTLE", "VBARMCSTEVEW",  "VBARMCHIBBLS", "CSDLBECK"

## Related Stories
**_PM Issues_**
IP | eFolder Express - VVA | Request Feature Flag enabled (RMC Group 8) [#1738](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1738)

**Comment by aroltsch** [comment]
Done.
