### ISSUE TITLE
Post-mortem: RAMP intake overwriting previous dispositions; January 4, 2018

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4307]
## Events

10/5/2017: PR [#3527](https://github.com/department-of-veterans-affairs/caseflow/pull/3527) is merged. This PR includes logic for closing an undecided appeal, but unknowingly [overwrites previously decided issues](https://github.com/department-of-veterans-affairs/caseflow/pull/3527/files#diff-e306b931976c85042b0d0e75acc300acR267). It does not anticipate closing post-remand appeals.

Prior to 11/1/2017: The team learns that AMO will include post-remand appeals in RAMP.

Between 11/1/2017 and 1/4/2018: 213 appeals are withdrawn in order to participate in RAMP.

1/4/2018 12:41PM: @cmgiven realizes that the close logic was never updated to account for post-remands, and while confirming this issue, identifies that previously decided issues are being overwritten.

1/4/2018 2:30PM: @shanear merges [#4277](https://github.com/department-of-veterans-affairs/caseflow/pull/4277), preventing overwriting of previously decided issues.

1/4/2018 6:35PM: @shanear merges [#4282](https://github.com/department-of-veterans-affairs/caseflow/pull/4282), closing post-remands by moving the remand to HIS status and creating a new appeal to hold the RAMP disposition.

1/5/2018 10:07AM: Fixes deployed to production.

1/5/2018 11:35AM: @cmgiven corrects 13 cases of advance appeals with previous issue-level dispositions that were overwritten.

1/6/2018 8:39AM: @cmgiven corrects 19 cases of post-remand appeals that were incorrectly closed.

## Affected parties

32 appeals were closed incorrectly, 13 due to the overwriting of all issue dispositions, and 19 due to closing post-remands using logic for undecided appeals. Before it was repaired, VACOLS would have had no record of the affected field grants, withdrawals, and decisions, and this would have affected any reports that were run during this time. There would not have been any Veteran-facing effects.

## Solutions

* Deployed patches to address the issue.
* Wrote script to restore appeal data, using a 12/1/2017 VACOLS snapshot. For the two post-remands that were RAMPed prior to 12/1/2017 (and to confirm that an additional case did not have any issue dispositions overwritten), a data report from 7/12/2017 was used, and manual review of the eFolder confirmed that there had not been other changes prior to 12/1/2017.

## Key issues

* When we learned that the RAMP rules had changed to include post-remands, we did not revisit application logic that had been designed with a different set of assumptions.

* The various `close` methods gave the impression of being more generic than they in fact were. Code that touches VACOLS could more clearly indicate which cases it accounts for, and which it does not.

* The earliest VACOLS snapshot available was 11/24/2017 (the 12/1/2017 snapshot was used instead, as the affected cases had been RAMPed prior to either snapshot). A prior snapshot had been mistakenly deleted after DMS was up and running.

## Action items

* Set up long term backup for VACOLS RDS [appeals-deployment#1145](https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1145)

**Comment by askldjd** [comment]
As discussed in Slack, the post-mortem will be moved to the [new style](https://github.com/department-of-veterans-affairs/appeals-pm/blob/1c52406858bf2a5a6633bda0b6e52088430aee7a/how-we-work/prod-squad.md#post-mortems). @cmgiven If you want me to review this as is, let me know. Otherwise, I will wait for new PR.
