### ISSUE TITLE
Styleguide | Add `Save long text` section

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4308]
## Story
As a designer or developer, I want to know the options for how to save a text input for Caseflow applications. 

## AC
- [ ] Add section `Save long text` on the side navigation, under form field section
- [ ] Add an text box with cancel and save buttons underneath it (see Reader comment section)
    - [ ] When there aren't any characters in box, save button should be disabled. 
    - [ ] When characters are entered in text box, save button should be active. 

## Mockup
![image](https://user-images.githubusercontent.com/13420618/34689395-64a9311e-f483-11e7-8252-3f5f778e4dd2.png)
![image](https://user-images.githubusercontent.com/13420618/34689466-a35582f0-f483-11e7-9145-79886f25e45f.png)

**Comment by Sjones352** [comment]
**PASSED**

Validate Chrome
1. Access Styleguide
2. Click on side nav to access form fields.
3. When no characters save button should be disabled.
4. Enter Characters and click save. Save button is enabled.

![save](https://user-images.githubusercontent.com/23080951/35643111-4584dfc8-0693-11e8-8ed0-e8674b649330.gif)
