### ISSUE TITLE
Styleguide | Add `Save short text` section

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4309]
## Story
As a designer or developer, I want to know the options for how to save a text input for Caseflow applications. 

## AC
- [ ] Add section `Save short text` on the side navigation, under form field section
- [ ] Add edit link next to title text
- [ ] When user clicks edit, a text input should appear with Cancel | Save links replacing edit link

## Mockup
![image](https://user-images.githubusercontent.com/13420618/34689650-48ad36b2-f484-11e7-9d4e-0f19179d4b63.png)
![image](https://user-images.githubusercontent.com/13420618/34689887-1048a8d2-f485-11e7-98b7-73ffd8b61666.png)

 ## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/4308

**Comment by Sjones352** [comment]
**PASSED**
Validate in Chrome/Uat
1.Access Styleguide
2. Navigate to Form Section
3. Verify `Save short text`
4 Verify edit link next to title text exists
5. Verify when you click edit, a text input should appear with Cancel | Save links replacing edit link

![forms](https://user-images.githubusercontent.com/23080951/36069398-bf62c636-0eb6-11e8-8b8a-ee1a94222a51.gif)
