### ISSUE TITLE
Refactoring— use DB id instead of VACOLS id for all routes

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#431]
We previously used the VACOLS id for routing, where to save the PDF file, etc. Now that we persist everything, use the certification id and form8 id

see certifications_controller.rb,   ` redirect_to certification_path(id: certification.form8.vacols_id)`

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
