### ISSUE TITLE
Reader | Color audit

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4313]
## Description
Design team was pinged and notified that there are many colors in our code base that is not being used. We discovered other colors on Reader that was inconsistent with the styleguide. 

## AC

- Make the adjustments for the following: 
  - [ ] Make sure Document number and receipt date are `$color-gray-dark`
  - [ ] depreciate the color #6b7079 from code base

**Comment by nolawi** [comment]
resolved in https://github.com/department-of-veterans-affairs/caseflow/issues/4958
