### ISSUE TITLE
Style guide | Change breadcrumb color

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4315]
## Story
For some reason, we had a default breadcrumb color that is not being used anywhere else and it's close to an existing color. Let's stick to the existing color so we don't have all 50 shades of grey. 

## AC
- [ ] Change #757575 to #5b616b or &color-gray - this can be found in Dispatch, Reader, eX coachmarks
- [ ] Identify any other places where #757575 is being used, change it to #5b616b so that #757575 is depricated

**Comment by nolawi** [comment]
this was resolved in colors PR
