### ISSUE TITLE
Feature Flag | Enable DSVA users on 1/9/2018

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4326]
I would like the following feature flag enabled on 1/9/2018 as early as possible for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  eFolder Express - VVA  

## Acceptance Criteria
1.	Verify that the feature flag has been enabled for the following users only.
"VHAISAJOPHIL", "VHAISAJONESS", "VHAISATOLSOR", "BVATATURNER", "VACOKOHLL"

## Related Stories
**_PM Issues_**
IP | eFolder Express - VVA | Request Feature Flag enabled (DSVA/101) [#1744](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1744)

**Comment by aroltsch** [comment]
Done.
