### ISSUE TITLE
722 Establish Claims stuck in dispatch with 'missing_decision' result

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#4328]
Filing this ticket to dig in to for tomorrow.  It appears we have 722 dispatch ECs that are stuck in the unprepared state.  When I manually run dispatch, I see 'missing_decision' gets returned as the result. 

This seems abnormally high and our current runs of dispatch have processed less than normal amounts of ECs. 

I'll be digging in to this tomorrow. 

cc @shanear @lakohl 

Please refer to this slack thread of my initial investigation.
https://dsva.slack.com/archives/C4JECDLSE/p1515546082000014

**Comment by lakohl** [comment]
@cmgiven adding you for awareness

**Comment by sunil-sadasivan** [comment]
It appears this is being done at the instruction of Rolandus (Head of BVA Dispatch) in order to take control of pending backlog.  

From @lakohl 

First email from Rolandus
> There is no issue with the system.  I instructed my staff to dispatch for a few days without uploading.  Our pending number grew so I had to make a decision on how best to get it under control.

Second email from Rolandus

> To be honest, we are doing an dispatch blitz this week.  We had a backlog of over 1,400 decisions about 2 weeks ago.  We got that down around 1,000 last week so this week we are going to just get it all done (or at least under our Over Time threshold of 350).  So, to answer your question, at least until we are under the threshold.   The upload process, while it may not take as long, I figured that by the time they upload 3 decisions into VBMS, they could have dispatched one more.  By the way, I just had a few of my employees upload a few of their decisions from Monday.

I'll maintain a close watch on the Dispatch backlog.  For now we can close this.  

I've created a business metrics monitoring dashboard for me to keep a close eye on this and how it affects dispatch runs. 

https://app.datadoghq.com/dash/454201/caseflow---dispatch-business-metrics?live=true&page=0&is_auto=false&from_ts=1515159065650&to_ts=1515763865650&tile_size=m
