### ISSUE TITLE
Daily Docket | Why so much space above issues?

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4333]
Why so much space above the number of issues?

**Current:**
<img width="1172" alt="screen shot 2018-01-10 at 3 32 19 pm" src="https://user-images.githubusercontent.com/4975959/34794250-1434797e-f61c-11e7-9306-1e1bc9edf492.png">

**Comment by nolawi** [comment]
possible duplicate #4226
