### ISSUE TITLE
Update copy/paste the Vet ID button style

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4334]
Update the copy/paste interaction of the Vet ID button.

## AC
Let the user know what the Vet ID button does.

1. On hover, display the following tool tip message: [Copy Veteran ID] in 19px type.
1. Show the Vet ID button in its gray-dark hover state.
1. On click, display the following snackbar message: [Veteran ID copied to clipboard.] in 19px type, for 1600ms.

**Mock**
![2018-02-12 14 03 31](https://user-images.githubusercontent.com/4975959/36114294-a22e0d26-0ffd-11e8-9bf7-306164b2516c.gif)

**Comment by annienguyenUSDS** [comment]
Checking if this was already updated?

**Comment by lakohl** [comment]
The old (styleguide) version of this button is currently live in HP. This Design Issue exists to update the styling: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/632

**Comment by lakohl** [comment]
**Possible approach**
![2018-01-05 12 52 04](https://user-images.githubusercontent.com/4975959/35168364-aca94f34-fd26-11e7-975c-abe8955030be.gif)
The InVision Public Share link first provides a tooltip on hover 'Copy to clipboard', then displays a toast with the  feedback 'Copied to Clipboard'.

**Comment by lakohl** [comment]
Dark version of snackbar message.
![alert dark](https://user-images.githubusercontent.com/4975959/36100864-aa8411f0-0fd5-11e8-8f88-f6fea22c7f4b.png)

**Comment by lakohl** [comment]
Invision interaction:
https://va-gov.invisionapp.com/share/JWFT6H8R7HC

**Comment by lakohl** [comment]
![2018-02-12 14 03 31](https://user-images.githubusercontent.com/4975959/36114294-a22e0d26-0ffd-11e8-9bf7-306164b2516c.gif)

**Comment by Sjones352** [comment]
@lakohl  dropping  [Copy Veteran ID] in 19px type to 13px is like screenshot below. I think we should drop it further down to may 10px.
<img width="229" alt="screen shot 2018-05-22 at 8 39 05 pm" src="https://user-images.githubusercontent.com/23080951/40397347-415dfcee-5e00-11e8-8f7a-a678df8cf0e7.png">

**Comment by lakohl** [comment]
@Sjones352 seeing as we can only have one string of copy for both hover and click, please use this text: 'Click to copy to Clipboard'

**Comment by Sjones352** [comment]
@lakohl  that's at 19px
<img width="409" alt="screen shot 2018-05-30 at 7 27 32 pm" src="https://user-images.githubusercontent.com/23080951/40753123-970f19c0-6440-11e8-9a09-75f478217e1f.png">

And this is at 13px
<img width="330" alt="screen shot 2018-05-30 at 7 29 54 pm" src="https://user-images.githubusercontent.com/23080951/40753141-a9aafc48-6440-11e8-85d1-dca81988712e.png">

**Comment by lakohl** [comment]
@Sjones352 Let's go with 14px Source Sans bold. My apologies for causing confusion, 'clipboard' should start with a lowercase c.
