### ISSUE TITLE
Hearing Worksheet: Add CC and DIC

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4337]
As a judge I would like to know when a  claim is classified as DIC or as contested.

## AC
1. Add CC in red: E21C3D to the right of the Docket Number if the hearing includes a contested claim.
1. Add DIC to the right of theDocket Number if the hearing includes a death and indemnity compensation.

## Mock
![cc and dic](https://user-images.githubusercontent.com/4975959/38469008-14db4f8e-3b1c-11e8-99f1-1c7abf693669.png)

**Comment by lakohl** [comment]
@annienguyenUSDS can you confirm that you want CC and DIC next to the Veteran name?

**Comment by annienguyenUSDS** [comment]
Yes, that works with design

**Comment by cmgiven** [comment]
Note that deceased does not equal DIC. For example, in the case of an accrued or substitution appeal.

If you do mean DIC, we could find that by looking for a DIC issue.

**Comment by lakohl** [comment]
@cmgiven could you elaborate about the difference between deceased and DIC? and what you think the best source of truth for each?

**Comment by cmgiven** [comment]
Deceased is whether the Veteran is alive or dead. BGS is the best source.

DIC is a type of claim that a survivor might pursue. VACOLS is the only source.

**Comment by lakohl** [comment]
Me: **When looking to see if an appeal is a CC or if the Veteran is deceased do you usually look in VACOLS? VBMS? or elsewhere?**

Dustin:
I would look at the documentation in VBMS then if something in it suggested the claim was either CC or the Veteran is deceases I would go to VACOLS to see if it was put in correctly.  I might look in VACOLS first but CC is almost never coded in VACOLS correctly prior to the case making it to an attorney's desk. (edited)
Death on the other hand is much more reliably coded in VBMS or VACOLS as VBA does a bi weekly match with SSA's death master file (DMF) and I think Jed also does some sort of reconciliation with a death file every so often as well.  That being said, I would still usually just go straight into the file instead of looking in either of these places. (edited)
DIC is "death and indemnity compensation."  It is an umbrella term for multiple different claims a beneficiary (veteran's spouse, child, or parent) can make in order to receive compensation following the death of the veteran.  So DIC will never be at issue until the veteran is dead.

**Comment by lakohl** [comment]
@annienguyenUSDS I wonder if our logic should be as follows:

1. When CC is indicated in VACOLS, display CC next the the Veteran name on the HW
1. When DIC is indicated in VACOLS, display DIC next to the Veteran name on the HW
1. When a Veteran is marked as deceased in BGS, display the word 'deceased' in red font under Veteran Age on the HW

**Comment by lakohl** [comment]
We are going to handle deceased Veterans in another ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/4984

**Comment by lakohl** [comment]
will update mock

**Comment by lakohl** [comment]
Mock and AC updated
