### ISSUE TITLE
Break up the Finish Processing steps

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4340]
Context: On the Finish Processing page when processing a ramp re-filing (RAMP Selection Form), we should break up the way we display the questions in the UI so it's easier for users to read. We'll only display the second question after the first question is complete.

## Acceptance Criteria
- On the Finish Processing page when processing a RAMP re-filing, the second question only appears after a user has selected the "I've completed the above steps outside Caseflow" checkbox in the first question
- If a user tries to move to the next page without selecting the checkbox, they'll see an in-line error next to the first question

**Comment by suzchap** [comment]
Waiting for Sally to set a test ID to have the right criteria.

**Comment by leahbannon** [comment]
This looks good.
