### ISSUE TITLE
Queue | Google Analytics

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4343]
Set up Google Analytics before first release.

### Goals:
- We want to see how a user navigates through Queue to Reader:
   - Queue table > queue task details > Reader
   - Queue table > Reader

### Events to track:

Queue table / home page:
- If a user clicks into an appeal's task details
- If a user clicks the reader documents link from Queue table
- If a user right clicks the reader documents link from Queue table to open in a new tab

Queue task details:
- If a user clicks 'Open in Reader' from the task details view
- If a user right clicks 'Open in Reader' from the task details view to open in a new tab
- If a user clicks Appellant tab
- If a user clicks Appeal tab
- If a user clicks into the Hearing Worksheet

Reader claims folder and document view:
- If a user clicks the Queue breadcrumb to navigate back to Queue
- If a user clicks the Queue link to navigate back to Queue

**Comment by amprokop** [comment]
Re: right clicks —it looks a bit more involved to track and you kind of have to infer that a user is right clicking so that they can open in a new tab. We'll probably have to write some custom code (vs regular analytics) to do this. The dev who picks this up should look at LOE, we may want to prioritize differently if LOE for that is way higher than other analytics.

https://stackoverflow.com/questions/14253951/how-to-track-open-new-tab-traffic-in-google-analytics

**Comment by nickheiner-usds** [comment]
@laurjpeterson, there are two types of tracking we can do:

1. Track when a user clicks on a link to visit a page, like "task details".
2. Track when a user visits the "task details" page.

We get (2) for free. (1) requires custom tracking. Can we get by with just (2)?

**Comment by laurjpeterson** [comment]
We'd like to be able to distinguish how a user navigates to Reader for an appeal - whether they go there from the main table vs. from task details. Assuming we can do that with (2), yes we can get by with just (2). 

For some more context - We'd like to better understand how users navigate between Reader and Queue. This will help us understand how our apps converge. 

We'd like to be able to answer if our users see them as separate, and have Queue open at the same time as Reader (opening in a new tab)? Or do they more often than not stay within the same window to go back and forth between the apps? Based on Alex's comment above, I understand the LOE here may be high so we may need to get this info elsewhere.

**Comment by mmlumba** [comment]
@laurjpeterson In GA you can track what the previous page is for a specific page, so yes we can do that with just (2).

**Comment by nickheiner-usds** [comment]
@laurjpeterson is this the type of information you want in terms of how people are navigating between pages?

![image](https://user-images.githubusercontent.com/25331532/36043183-6ebd0ae0-0d9c-11e8-9a31-2cd544d1880d.png)

**Comment by laurjpeterson** [comment]
@nickheiner-usds Yep, we can use the behavior flow for this.

**Comment by mmlumba** [comment]
@laurjpeterson Would the above behavior flow be ok in place of determining if Queue/Reader is opened in a new window?

**Comment by laurjpeterson** [comment]
@mmlumba Yes, let's just move forward with the behavior flow. We can ask and observe users to learn if they open in a new tab or not. Thank you!

**Comment by laurjpeterson** [comment]
closing because GA was implemented for release 1. will open a new ticket for subsequent GA work.
