### ISSUE TITLE
Form 8:  Question 10B:  Pre-populate Hearing Held value

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#435]
As a Certification Caseworker, I would like to have question 10B - Hearing Held value to be pre-populated from the appeal so that it reduces errors and speeds up my ability to complete the form faster.

# Acceptance Criteria
1. Verify that when a new form is being filled out, question 10B - Hearing held has been pre-populated with the value from the appeal.

### Mockups
**_View - Question 10B_**
![image](https://cloud.githubusercontent.com/assets/23063044/21319295/aa51ab66-c5da-11e6-81f1-e971eb92f990.png)

# Realated Stories

**Comment by amprokop** [comment]
from @shanear 


Shane Russell	[5:57 PM]  
@alex its entirely possible that were just not setting the defaults correctly here

[5:57]  
seems like a product of logic weve had there for over a year, when we knew the mysteries of VACOLS even more poorly than we do today

[5:58]  
you're added initial vs actual will help us know for sure

[5:58]  
good catch btw

**Comment by kierachell** [comment]
Verified that field __10B__ is pre-populated based on field __10A__ selection.
<img width="690" alt="screen shot 2016-12-21 at 21 25 51" src="https://cloud.githubusercontent.com/assets/18075411/21413295/2c34851e-c7c4-11e6-8a3b-16e9c133b603.png">

Subsequent fields also auto-expand.
