### ISSUE TITLE
Queue task details | Link to Reader

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4353]
When an attorney reviews appeal data and gets ready to start a draft decision task, they want to quickly access Reader to review documents, so they can write the decision draft.

## Acceptance Criteria
- A link to 'Open in Reader' exists in the task details view
- Verify that Reader opens to the correct Veteran's claims folder
- If error with call to eFolder to show the number of documents was unsuccessful, show error states

### Appeal Details Tab (Appeal tab is active on page load)
![mvp_appeal_details](https://user-images.githubusercontent.com/31224257/35049452-11181226-fb6e-11e7-83b6-92f8db2de229.png)

**Comment by dannysellers** [comment]
@laurjpeterson Currently, the link reads "Open documents in Caseflow Reader" regardless of whether we successfully fetch the document count from eFolder. Should it display something different if that call fails?

**Comment by sneha-pai** [comment]
@dannysellers if you're able to fetch the document count, you can have that link read like this:
"Open #NUM documents in Caseflow Reader"
(@laurjpeterson)
