### ISSUE TITLE
[Backend] | Hearing database updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#4358]
- Add a column to hearing.rb: 'prepped'
- Add 'prepped' as an allowed field for the API request in hearings_controller's update_params
- Confirm the API request updates the database correctly (I usually use Postman)

**Comment by tejans24** [comment]
After briefly chatting with @sharonwarner, we decided to keep the prepped field as null value as default.

**Comment by astewarttistatech** [comment]
Any changes to AC should be inside of the original AC
