### ISSUE TITLE
Intake | Searches and Errors don't clear after selecting different RAMP

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#4359]
**Currently:** When in Intake and you search a veteran via one route of RAMP (initial filing or refiling) and get an error, if you click the Intake logo to take you back to `/intake` to select a new route, the page loads with the same error you got from the other route. 

Ex. Intake > Selection > Search 'xxxxxxxxx' > get error > Intake > Opt-in > get same error 

**Expected:** When returning back to Intake the data and all associated errors should be cleared in order for the user to move into the next Intake.

**Found:**Preprod/UAT/Chrome 

**Steps to Reproduce:**

1. Access Intake 
2. Select to Refile or Initial File 
3. Search a non-allocated veteran ID
4. Get an error
5. Select the Intake spinner in the page header (or just go to /intake in the address bar)
6. Select the other option (if you selected refile, now select initial file vice versa)
7. Verify that the error and the veteran ID show up from the first attempt at a RAMP. 

**Screenshots:**
![intakebug1](https://user-images.githubusercontent.com/23038505/35002021-4395c36e-fab6-11e7-9986-32a13dbe178d.gif)

**Comment by leahbannon** [comment]
After running through the steps to replicate, the vet number is still pre-filled when I get to the Search page a second time. But the error is cleared and I can just type a new vet number, so I think this is fine.
