### ISSUE TITLE
Queue task details | Create task details skeleton

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4361]
When an attorney has selected a task to work on, they want a place to go for more information specific to the appeal and appellant, so they can get required context to write a decision. 

## Acceptance Criteria
- When navigating to `appeals.cf.ds.va.gov/queue/tasks/:vacols_id`, an attorney should see the draft decision task for that vacols_id.
- Title of page is "Draft decision - [Veteran name - VBMS ID]"
- Create two-tab skeleton

### Task and Appeal Details
![mvp_appeal_details](https://user-images.githubusercontent.com/31224257/35052647-19768eae-fb76-11e7-9f77-dd42f5d21644.png)

## Components utilized
Caseflow Navigation Bar
Tab Component (No Icons)

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white

**Comment by amprokop** [comment]
@sneha-pai @laurjpeterson — can we add the "Notes" field issues into these mocks?

Here's some sample text from VACOLS w notes

```
 {:issues=>
       [{:close_date=>nil,
         :codes=>["02", "15", "03", "7101"],
         :disposition=>:remanded,
         :id=>"111117",
         :labels=>
          ["Compensation",
           "Service connection",
           "All Others",
           "Hypertensive vascular disease (hypertension and isolated systolic hypertension)"],
         :note=>"hypertension secondary to DMII.",
         :vacols_sequence_id=>1},
        {:close_date=>nil,
         :codes=>["02", "12", "04", "8599"],
         :disposition=>:remanded,
         :id=>"111117",
         :labels=>
          ["Compensation",
           "Increased rating",
           "Schedular",
           "Other peripheral nerve paralysis"],
         :note=>"PERIPHERAL NEUROPATHY RIGHT UPPER EXTREMITY 8599-8515",
         :vacols_sequence_id=>2},
        {:close_date=>nil,
         :codes=>["02", "12", "04", "8599"],
         :disposition=>:remanded,
         :id=>"111117",
         :labels=>
          ["Compensation",
           "Increased rating",
           "Schedular",
           "Other peripheral nerve paralysis"],
         :note=>"PERIPHERAL NEUROPATHY LEFT UPPER EXTREMITY 8599-8515",
         :vacols_sequence_id=>3},
        {:close_date=>nil,
         :codes=>["02", "15", "04", "7101"],
         :disposition=>:allowed,
         :id=>"111117",
         :labels=>
          ["Compensation",
           "Service connection",
           "New and material",
           "Hypertensive vascular disease (hypertension and isolated systolic hypertension)"],
         :note=>nil,
         :vacols_sequence_id=>4}],
```

**Comment by amprokop** [comment]
@dannysellers — we can start on this task whenever, but keep in mind that we'll need to add the note field too (a trivial task)

**Comment by Sjones352** [comment]
**PASSED**

Validate Uat Chrome
1. Navigate to Tasks
2. Verify Title of page is "Draft decision - [Veteran name - VBMS ID]"
3. Verify Two Tabs Appeals and Appellant[Veteran name]

![queue](https://user-images.githubusercontent.com/23080951/35711621-db984f4c-078b-11e8-90c1-68e4a652a40c.gif)
