### ISSUE TITLE
Queue task details | Appeal tab

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4362]
When an attorney has selected a task to work on, they want to see data about the appeal, so they can get required context to write a decision. 

## Acceptance Criteria
- Appeal tab contains two sections: Appeal Summary and Issues
- Appeal Summary section in Appeal tab contains the following data (see mocks for more detail)
  - Appeal type (same options as Queue table)
  - Power of Attorney
  - Hearing preference
  - Hearing held date (only if hearing held)
  - Judge at hearing (only if hearing held)
  - Regional office
- Issues section contains issue details as outlined below. Include Program, Issue Levels 1-3, and Notes

### Appeal Details Tab (Default tab on page load)
![mvp_appeal_details](https://user-images.githubusercontent.com/31224257/35052285-34ec6aec-fb75-11e7-8eb8-3db475d1181d.png)

## Components utilized
Caseflow Navigation Bar
Tab Component (No Icons)

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white

**Comment by dannysellers** [comment]
@laurjpeterson What should the Notes field look like / where should it go? Should it just be a third column next to Issue?

**Comment by sneha-pai** [comment]
@dannysellers, for now it can appear like this (only if a note is present). If a note is not present, please do not display a label.

5327 - Lumbosacral or cervical strain
**Note:** #STRING

@laurjpeterson

**Comment by dannysellers** [comment]
@laurjpeterson @sneha-pai updated screenshot

![screen shot 2018-02-05 at 1 31 27 pm](https://user-images.githubusercontent.com/8533004/35822030-e50b2a6e-0a78-11e8-9c5a-30312ccb1126.png)

**Comment by laurjpeterson** [comment]
@dannysellers looks good!
