### ISSUE TITLE
Queue task details | Link to Hearing Worksheet

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4363]
When an attorney reviews appeal details for a an appeal where a hearing was held, they want a quick way to access the judge's Hearing Worksheet notes, so they can get context on the case and potential disposition.

## Acceptance Criteria
- If the appeal's hearing was held and it has a Hearing Worksheet established by Hearing Prep, a link to Hearing Worksheet exists in the Appeal Summary section (see mocks below for placement)
- Hearing Worksheet opens in a new tab (this is the same convention for Reader Welcome Gate and Claims folder details today)

## Mocks

Appeal Details Tab (Hearing worksheet present)
![mvp_appeal_details_hearing-worksheet-present](https://user-images.githubusercontent.com/31224257/35051792-08a05ada-fb74-11e7-89d4-b47c8a0967b2.png)

## Components utilized:
Caseflow Navigation Bar
Tab Component (No Icons)

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white

**Comment by dannysellers** [comment]
Blocked by #4362
