### ISSUE TITLE
Queue task details | Appellant tab

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4365]
When an attorney has selected a task to work on, they want to see data about the appellant, so they can get required context to write a decision.

## Acceptance Criteria
- Appellant tab contains Appellant name in parentheses

**If the Veteran is the appellant:**
- Appellant tab contains 'Veteran details' section that contains:
  - Copy to explain whether the Veteran is the appellant
  - Veteran name
  - Veteran preferred pronoun
  - Veteran date of birth
  - Veteran mailing address

**If the Veteran is not the appellant, contains an 'Appellant details' section, then a 'Veteran details' section, that contains:**
  - Appellant details:
    - Copy to explain whether the Veteran is the appellant
    - Appellant name
    - Appellant preferred pronoun
    - Appellant date of birth (?)
    - Appellant mailing address
  - Veteran details:
    - Veteran name
    - Veteran preferred pronoun
    - Veteran date of birth (?)

### Appellant Details Tab (Where veteran is the appellant)
![mvp_appellant_details](https://user-images.githubusercontent.com/31224257/35049495-345f0f64-fb6e-11e7-9d08-4d3156c70a9f.png)

### Appellant Details Tab (Where veteran is NOT the appellant)
![mvp_appellant_details_veteran-not-appellant](https://user-images.githubusercontent.com/31224257/35049506-3c73a8ae-fb6e-11e7-9db8-1237251bd356.png)

## Components utilized
Caseflow Navigation Bar
Tab Component (No Icons)

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white

**Comment by dannysellers** [comment]
It looks like there're a couple fields missing when the veteran is not the appellant:
- Gender (preferred pronoun)
- DOB

@amprokop @laurjpeterson

**Comment by laurjpeterson** [comment]
@dannysellers appellant relationship seems useful. what are the options listed there?

cc: @shellicious @sneha-pai

**Comment by dannysellers** [comment]
@laurjpeterson I'm not sure all the possible options (data comes from VACOLS), but fake data includes values like 'Parent', 'Child', 'Daughter', 'Brother', or ['Fancy Man'](https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/models/form8_spec.rb#L18) 😄

**Comment by sneha-pai** [comment]
@laurjpeterson @dannysellers 
Let's display appellant relationship (when available) after Appellant name
