### ISSUE TITLE
Queue task details | Navigate back to Your queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4366]
When an attorney is viewing a decision task's appeal and appellant details, they want a way to go back to their queue (list of assigned tasks), so that they can work on a different decision task if they want to.

## Acceptance Criteria
- Link to go 'Back to Your Queue' exists
- User is taken back to their Queue page

### Task and Appeal Details View
![mvp_appeal_details](https://user-images.githubusercontent.com/31224257/35052285-34ec6aec-fb75-11e7-8eb8-3db475d1181d.png)

## Components utilized
Caseflow Navigation Bar
Tab Component (No Icons)

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white

**Comment by Sjones352** [comment]
**PASSED**
Validate Uat/ Chrome 

1. Access Queue
2. Click on Appeal
3. Link to go 'Back to Your Queue' exists
5. User is taken back to their Queue page

![queue](https://user-images.githubusercontent.com/23080951/35711337-6ccbaa10-078a-11e8-90db-a3ab58bf96af.gif)
