### ISSUE TITLE
Queue task details | Assignment and deadline

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4367]
When an attorney decides to work on a task and navigates into it to see more details, they want to know who assigned it to them and when it is due, so they can plan their work accordingly.

## Acceptance Criteria
- Below the title of the page, there is copy to explain who assigned the task and the task's deadline

### Task and Appeal Details
![mvp_appeal_details](https://user-images.githubusercontent.com/31224257/35052535-d079ed54-fb75-11e7-982a-35673ff06ad9.png)

## Components utilized
Caseflow Navigation Bar
Tab Component (No Icons)

## Colors utilized:
$color-base
$color-gray-lighter
$color-primary
$color-white

**Comment by dannysellers** [comment]
Deadline implemented in #4510; assigned pending #4503

**Comment by dannysellers** [comment]
@laurjpeterson What should be displayed in cases where there is no assigner? Will that ever happen (like the first time a case/task is reviewed)?

**Comment by laurjpeterson** [comment]
I don’t think that should ever happen, bc cases come from judges or senior counsel. In the rare case that it happens though, I think leave it blank. @sneha-pai
