### ISSUE TITLE
Queue/Reader breadcrumbs | Navigate Back to Your Queue from Reader

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4368]
For the first release of Queue for attorneys, when an attorney opens an appeal in Reader from their Queue (or from task details), we are experimenting with it opening in the same window.  

When an attorney opens a claims folder in Reader from Queue, they want a way to navigate back to their Queue, so they can review other assigned cases. 

## Acceptance Criteria
- When a user navigates from their Queue table to Reader, breadcrumbs in Reader contain a "back to Your Queue" link
- When a user navigates from Queue task details to Reader, breadcrumbs in Reader contain a "back to Decision draft for [Veteran Name(Appeal ID)]"
- "Caseflow Reader" in the Navigation would still be a link, but instead of a link to `/reader/appeal` (currently the Welcome Gate), it would be a link to `/reader/appeal/:vacols_id/documents` (the Claims Folder)

#### Reader Linking back to "Your Queue"
![reader-linking-1 copy 2](https://user-images.githubusercontent.com/31224257/36054545-1c2ec010-0dc5-11e8-8a11-40b66ad0a167.png)

#### Reader Linking back to "Draft Decision for [name of veteran(appeal ID)]" for respective veteran.
![reader-linking-1 copy 4](https://user-images.githubusercontent.com/31224257/36054552-278ffc4e-0dc5-11e8-9de0-eee3fc52148b.png)

**Comment by nickheiner-usds** [comment]
What should the URL be for each of these screens?

(I ask because I'm talking with Alex about the best way to implement this.)

**Comment by nickheiner-usds** [comment]
The top breadcrumb is "Caseflow Queue > Your Queue > Claims Folder". Which page does "Caseflow Queue" and "Your Queue" go to?

**Comment by sneha-pai** [comment]
Revision mock for discussion with @amprokop 

## Acceptance Criteria
When a user navigates from their Queue table to Reader, breadcrumbs in Reader contain Queue and Reader Claims Folder

When a user navigates from Queue task details to Reader, breadcrumbs in Reader contain Queue, Task details, and Reader Claims Folder

When a user clicks on the Caseflow Reader logo in the Navigation Bar, the current page will reload, preserving "back to queue" linkage.


### Mock
#### "Back to Your Queue" link
![reader-linking-queue-v2](https://user-images.githubusercontent.com/31224257/36035036-cb542bf8-0d83-11e8-80ed-0cad2541dbbc.png)

#### "Back to Draft Decision - Vera Marshall(000000000)" link
![reader-linking-queuetaskdetail-v2](https://user-images.githubusercontent.com/31224257/36035154-18f5b214-0d84-11e8-9d58-20cd4f1e4e57.png)

**Comment by nickheiner-usds** [comment]
@sneha-pai would you mind updating the original post with the updated AC? (Feel free to paste the original AC in a message below for posterity if you'd like.) It's much easier for everyone to be on the same page when the current state is always in the original post of the issue.

**Comment by amprokop** [comment]
👍, @sneha-pai and i talked and there are some changes we can make here.

**Comment by laurjpeterson** [comment]
this is done!
