### ISSUE TITLE
Intake | Header not aligned

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#4374]
**Current:** 
When logged into UAT and on the Intake homepage, the header is unaligned for the veteran name/file id. 

**Expected:** Header should be aligned 

**Found:** UAT / Chrome 

**Steps to Reproduce:**
1. Access Intake
2. Search a veteran file number based on initial RAMP or re-file. 
3. Verify that the header is unaligned. 

**Screenshots:**
<img width="814" alt="screen shot 2018-01-17 at 11 31 47 am" src="https://user-images.githubusercontent.com/23038505/35054916-cb03175a-fb7b-11e7-8698-7c99f46f8112.png">

**Comment by shanear** [comment]
This was fixed by updating styleguide
