### ISSUE TITLE
Hearing Prep: Update demo pre-Pilot Training

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4376]
## Story
We want to update the dummy data info in demo to reflect more accurately in the correct fields when we show judges for the kickoff. These include:

## AC
1. Update info in Notes in Notes field on DD. (Should not include veteran's service info, should include: '#2 or Veteran Cancelled, or Delayed by traffic..)
1. Update Case Summary Documents in Reader to show the Case Summary Doc Types and no other types of docs or category flags.
1. Show more than 1 issue for some cases on Daily Docket as well as Hearing Worksheet
1. Show more than 1 appeal stream for some Hearing Worksheets
1. Times on Daily Docket should be on the hour or half-an-hour.

**Comment by annienguyenUSDS** [comment]
4. Lower on the list, but times on Daily Docket should be on the hour or half-an-hour.
