### ISSUE TITLE
Create tabbed pattern

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#438]
![](https://cloud.githubusercontent.com/assets/6335546/11908728/ab5cd1a6-a593-11e5-9767-e2e8da77a55f.png)

**Comment by ErieMeyer** [comment]
From @maya:

Accessible tabs: 
http://heydonworks.com/practical_aria_examples/#tab-interface
http://getbootstrap.com/javascript/#tabs
http://foundation.zurb.com/sites/docs/v/5.5.3/components/tabs.html#tabs-deeplink-3

**Comment by webinista** [comment]
I'm leaning towards the one from [Refills](http://refills.bourbon.io/), but adding the aria labels from the [HeyDonWorks](http://heydonworks.com/practical_aria_examples/#tab-interface) example is probably a good idea.

**Comment by maya** [comment]
@webinista :100: That's a great idea! Keep us posted with how it goes and maybe we can feed it back into the main USWDS library.

**Comment by ErieMeyer** [comment]
🇺🇸🇺🇸🇺🇸

**Comment by webinista** [comment]
[Work in progress](http://codepen.io/webinista/pen/WrjMNo)

Need to add ARIA attributes and toggle `hidden` attribute.

**Comment by webinista** [comment]
Not sure about how best to make this available for testing within Caseflow since we're not yet using this pattern. 

@maya If you'd like to review the [WIP](http://codepen.io/webinista/pen/WrjMNo) and offer feedback (in this thread is fine), I'm happy to try integrating it into the USWDS.

**Comment by maya** [comment]
@webinista we have our roadmapping next week, so that will be a better time to see what new components we'd like to take on for this phase. Stay tuned!

**Comment by paultag** [comment]
(Opening over in Road Runner)
