### ISSUE TITLE
Caseworker Landing:  Establish Claim:  Rename button to Establish Next Claim

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#439]
As a Caseworker, I would like to have the button "Establish Claim" on the Caseworker Landing page renamed to "Establish Next Claim" so that the label more accurately reflects its purpose.

Acceptance Criteria

1. Verify that the button "Establish Next Claim" button has been renamed to "Establish Next Claim".

### Mockup
![439 - rename establish claim button](https://cloud.githubusercontent.com/assets/23063044/20351040/3d5a351a-abdf-11e6-8f2d-d9a688654780.PNG)

**Comment by mdbenjam** [comment]
@nikitarockz  This is currently Establish Claim not Create End Product. Do we still want it to say Establish Next Claim?

**Comment by nikitarockz** [comment]
Yes, this should be Establish Next Claim.  I will update the story to correctly reflect the current labeling.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
