### ISSUE TITLE
Refactor color constants

### ISSUE THREAD

**Issue by nickheiner-usds** [department-of-veterans-affairs/caseflow#4402]
We have color constants that are duplicated throughout our codebase. For instance:

```
λ grep '#417505' -r app/
app//constants/AppConstants.js:export const LOADING_INDICATOR_COLOR_READER = '#417505';
app//containers/StyleGuide/StyleGuideColors.jsx:    Reader: '#417505',
app//containers/StyleGuide/StyleGuideLogos.jsx:        accentColor: '#417505',
app//reader/constants.js:export const READER_COLOR = '#417505';
```

We should centralize these constants, defining them in one place and referencing them elsewhere.

Some of these values already exist in `import { LOGO_COLORS } from '@department-of-veterans-affairs/appeals-frontend-toolkit/util/StyleConstants'`. Those should be used where possible.

## Dev AC
Each color is only defined in a single place in the JS.

**Comment by mmlumba** [comment]
@nickheiner-usds I'm assuming that this is for all colors and not just Reader colors?

**Comment by nickheiner-usds** [comment]
No need for QA on this one.
