### ISSUE TITLE
Case details | Appeal Details Tab | Multiple Hearings

### ISSUE THREAD

**Issue by sneha-pai** [department-of-veterans-affairs/caseflow#4403]
When a veteran has had more than one hearing, the Hearings section of the Appeal Detail Tab should reflect relevant information per hearing. 

## Acceptance Criteria
- Verify that each hearing for an appeal has corresponding data for date held and name of judge at hearing.
- Verify that the treatment for hearing details is scaleable and can handle a maximum of 3 hearings and their details.

### 1 hearing
![mvp_appeal_details_hearing-singular](https://user-images.githubusercontent.com/31224257/37621442-59ae1a24-2b95-11e8-966e-00d29b4025c6.png)

### 2-3 hearings
![mvp_appeal_details_hearing-multiple](https://user-images.githubusercontent.com/31224257/37621447-5ba6ad0a-2b95-11e8-9d87-3e5bfa00b05d.png)

**Comment by dannysellers** [comment]
@sneha-pai It looks like Regional Office is missing from the mocks. Should it go below the hearing(s) info, as it is now, or above?

<img width="726" alt="screen shot 2018-05-14 at 11 25 43 am" src="https://user-images.githubusercontent.com/8533004/40006943-98602910-5769-11e8-89f8-7f8114e935d8.png">

**Comment by dannysellers** [comment]
Also, should this have the same logic as before? Currently, we'll always display at least the hearing preference / type. If there is no disposition, that's all we'll display, else we'll also show disposition. If the disposition is `cancelled`, that's all we'll display, else we'll show the date and judge name.

**Comment by dannysellers** [comment]
> ...can handle a maximum of 3 hearings and their details.

Does this mean that we should display at most 3 hearings? i.e. should we limit it? I imagine appeals with ≥ 3 hearings are uncommon
