### ISSUE TITLE
Remove dead views

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4411]
Let's remove unused layouts. Remove `/whats_new` folder, remove `/layouts/ceritfications`, and audit other files in `/views` to see if they're removable.

# AC for dev
- All unused views in `/views` are removed

**Comment by Sjones352** [comment]
**PASSED**


Validated in:  Reader App

Steps to Validate: 
1. Click User dropdown menu
2.Check if what's new page still exits


![new](https://user-images.githubusercontent.com/23080951/35348050-e2275480-0104-11e8-88f7-e2f17b316b1a.gif)
