### ISSUE TITLE
Style guide | Add missing logos 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4415]
## Description

We are missing some of our logos in the branding section!

## AC

- [ ] Add the following logos under the Branding section 
  - [ ] eFolder
  - [ ] Certification

**Comment by Sjones352** [comment]
**PASSED**
Validate Chrome/Uat
1.Access Styleguide
2.Nagivate to Branding
3. Verify that eFolder and Certification logo exist

<img width="1052" alt="screen shot 2018-02-10 at 10 52 02 pm" src="https://user-images.githubusercontent.com/23080951/36069325-53efebb4-0eb5-11e8-9ccb-7d78c5f8a191.png">
