### ISSUE TITLE
Fix ReactOnRails warning

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4419]
When the local env is set up, we see this warning:

```[DEPRECATION] ReactOnRails: remove skip_display_none from configuration.```

Determine what this error means and if it's safe, remove `skip_display_none` from our react on rails config.

**Comment by Sjones352** [comment]
**PASSED**
Vadlidate
1. Pull from master
2. Check  react_on_rails.rb file if `config.skip_display_none = false` still exists. 
3. It has been removed so PR passes.
