### ISSUE TITLE
Set up Queue fake data for the default local dev case

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4421]
So local dev reflects real world scenarios, the fake data we use for Queue should include the following scenarios:

- [x] an AOD case
- [x] an AOD and CAVC case
- [x] a case with no POA
- [x] a case with VSO poa
- [x] a case with a one time rep
- [x] a case with an attorney
- [x] a case with one issue
- [x] a case with 5 issues
- [x] a case with 12 issues
- [x] a case with no hearing
- [x] a case with multiple hearings
- [x] a case with one hearing
- [x] a case where the veteran is not the appellant
- [x] a case where the veteran is the appellant

**Comment by shellicious** [comment]
More scenarios:
- 2 cases in the same Queue with the same appellant (2 different appeals for the same person, which cannot be merged)
- a case which is a remand
- a case with a hearing scheduled, that the veteran did not attend, and then cancelled 
- a case where the appellant has passed away (this data may not be available in VACOLS, an attorney I spoke with says she gets it from an employee named Jewell, who gets it from a Social Security database, will ask Chris)

**Comment by sneha-pai** [comment]
- a case with a hearing scheduled that hasn't occurred yet.

**Comment by amprokop** [comment]
```
a case where the appellant has passed away (this data may not be available in VACOLS, an attorney I spoke with says she gets it from an employee named Jewell, who gets it from a Social Security database, will ask Chris)
```

interesting @shellicious — would this be reflected in the Queue UI at all? If it's not in VACOLS, how would you envision us getting this data?

**Comment by amprokop** [comment]
```
a case with a hearing scheduled, that the veteran did not attend, and then cancelled
```

how would this be reflected in the UI also?

**Comment by laurjpeterson** [comment]
> - a case with one hearing
> - a case with a hearing scheduled that hasn't occurred yet.

For one hearing related cases, perhaps we can split it out as:
- a case with one hearing that has not been scheduled
- a case with one hearing that has been scheduled, but hasn't occurred yet (above)
- a case with on hearing that has occurred

> - 2 cases in the same Queue with the same appellant (2 different appeals for the same person, which cannot be merged)

Related: 
- 2 cases for the same appellant, one in an attorney's queue, the other at the SOC stage. ADV status, pre-certification

**Comment by amprokop** [comment]
```
2 cases for the same appellant, one in an attorney's queue, the other at the SOC stage. ADV status, pre-certification
```
interesting @laurjpeterson — why would this sort of case appear in an attorney's queue? or do i misunderstand?

**Comment by laurjpeterson** [comment]
```
2 cases for the same appellant, one in an attorney's queue, the other at the SOC stage. ACT status, pre-certification
```

The attorney is writing a decision for the case in their queue, but they want to see if that appellant has another open appeals stream. I revise my scenario - let's have the second appeal be in ACT status, so the attorney is checking if the appeals should be merged.

**Comment by shellicious** [comment]
Update re: death data from @cmgiven (thanks, Chris!)

> BGS has it, I believe. Having worked briefly on a sprint related to VA’s death data, though, I don’t have a lot of confidence in that data, particularly if we’re trying to use it as an authoritative record for an attorney.

**Comment by amprokop** [comment]
Cool. This seems like a separate initiative to me @shellicious — unless there is some reason we would want to include this information only in fake development data when we don't have it otherwise? Probably warrants its own discovery and tech spec if not.

**Comment by amprokop** [comment]
```
The attorney is writing a decision for the case in their queue, but they want to see if that appellant has another open appeals stream. I revise my scenario - let's have the second appeal be in ACT status, so the attorney is checking if the appeals should be merged.
```

Ah, I see what you mean — it wouldn't appear in the attorney's queue, but it would appear if they searched using the search bar. 👍  that sounds like something that will require a larger rethink of fake appeals data, probably won't get to it today but on a second pass will keep that in mind.
