### ISSUE TITLE
Queue table | Display CAVC instead of "Court Remand"

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4439]
I didn't realize that CAVC == Court Remand for purposes of appeals status. `QueueTable` currently displays `CAVC` if the task `type` is 'Court Remand', and also displays the `type`.

## AC:
- [ ] Navigate to `/queue`
- [ ] For tasks of type 'Court Remand', 'CAVC' should be rendered in red under the Type column

**Comment by Sjones352** [comment]
**PASSED**
Validate Uat Chrome
1. Access https://appeals.cf.uat.ds.va.gov/queue
2. Verify for tasks of type 'Court Remand', 'CAVC' should be rendered in red under the Type column

<img width="1279" alt="screen shot 2018-02-04 at 5 02 15 pm" src="https://user-images.githubusercontent.com/23080951/35782929-d16af9a4-09cd-11e8-93d0-db21c7f49a74.png">
