### ISSUE TITLE
Intake feedback tickets should specify the name of the app

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4441]
Currently, if a user sends in feedback through Intake, the feedback shows up as a generic "Caseflow" feedback, rather than saying it's from Intake. It's helpful to know the source of the feedback upfront.

## Acceptance Criteria
- If a user submits feedback from Caseflow Intake, the feedback app labels it as such

**Comment by leahbannon** [comment]
this works
