### ISSUE TITLE
Already Certified: Page inappropriately shows "Mismatched Documents" in Header

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#446]
On the "Already Certified" page, the header says "Mismatched Documents" in the header.

It should say "Certification"

<img width="1554" alt="screen shot 2016-11-15 at 2 19 33 pm" src="https://cloud.githubusercontent.com/assets/1596259/20320154/dddcc6e8-ab3e-11e6-8f07-97c00892dc6a.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached. 
<img width="1043" alt="screen shot 2016-12-07 at 3 54 30 pm" src="https://cloud.githubusercontent.com/assets/23038505/20986171/7da6d8b4-bc95-11e6-9a66-ccaaf7b322ad.png">
