### ISSUE TITLE
Intake Stats | Add average response time by notice date

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4462]
AMO needs the ability to look up the response time of RAMP invites were returned based on their sent date.

## Acceptance Criteria
- On the intake stats page, there should be a metric box reporting the average time between notice date and receipt date of ramp elections by their sent date
- Change "Median response time" to "average response time by receipt date", and update the calculation accordingly

## Notes

order of stats should be:

**Ramp Elections Sent for <TIME>**
Total
Total Returned
Percentage Returned
Average Response Time

**Ramp Elections Received for <TIME>**
Total
Average Response Time

**Comment by suzchap** [comment]
Labels don't match exactly but Abby said it's fine as-is.
