### ISSUE TITLE
Intake Stats | Add number and % of received elections ineligible stat

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4463]
AMO needs the ability to look up how many and what % of elections were ineligible processed during a time period

## Acceptance Criteria
- On the intake stats page, there should be a section for ramp elections processed. In that section we should report how many and what percentage of ramp elections were eligible/ineligible.

## Notes
The section should be below the "Ramp Elections Received" section and have the following stats/copy:

**Ramp Elections Processed for {TIME}**
Eligible
Total Ineligible
Ineligible - Appeal Ineligible
Ineligible - No Active Appeals
Ineligible - Duplicate
% Eligible

**Comment by leahbannon** [comment]
(note to leah: validate this in prod)

**Comment by suzchap** [comment]
Labels don't match exactly but Abby said it's fine as-is.
