### ISSUE TITLE
Attorney check out | Submit draft decision

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4465]
As an attorney, I want the work product automatically filled out based on my dispositions for Decision related work products. When an attorney assigns a case to a judge for review, they need to enter in the document ID, mark the case overtime, and input any notes, so the judge can easily find the work product and get context on the case they are signing.

#### User selected "Decision Ready for Review" as the action in the table or appeals detail viewand was directed to dispositions
- [ ] Verify that after the Issues Disposition Screen (#4471), the work product auto fills based on the type of issue disposition in the backend and there is no Work Product screen in the front end - logic here: https://github.com/department-of-veterans-affairs/caseflow/issues/4525
- [ ]  Verify that there is a checkbox underneath the Work Product with the following copy "This work product is overtime" 
     - The overtime designation is updated in VACOLS per work product logic above
- [ ]  Verify that there is a section called "Check out to" with the name of the Judge who assigned the task
- [ ] Verify that there is a link that shows "Select another judge" next to the Judge name in "Check out to" 
- [ ] Verify that there is a section called 'Document ID" and attorney can type in the document ID number with a required label in secondary color and italicized. 
- [ ] Verify that there is a text field called "Notes" 
- Notes save back to VACOLS field - 'factors affecting timeliness'
- [ ] Verify that there is a link at the bottom left of the app canvas with the following copy "Go back to draft decision (Appeal ID)" 
- [ ] Verify that there is a continue button on the bottom right of the app canvas labeled 'Check out decision" and leads to the decision confirmation page (#4479)

### Style Guide Components Used (top to bottom)

- Header
- App canvas
- Dropdown 
- Text field 
- Text input label
- Link
- Primary button
- Text area
- Footer

### Mocks and specs
Page title: Heading 1 (34)
All body text: Body (17)
Row labels should be bold 
Spacing should follow existing dimensions from the Queue MVP and Ticket views 

#### Submit draft decision (after disposition selection)
![draft decision review](https://user-images.githubusercontent.com/23316107/36043793-812d697a-0d9e-11e8-8217-061ba18c3776.png)

#### Submit draft decision (after Remand Reasons)
_Bread crumbs and back link text changes at the bottom of the canvas_
![draft decision review -- back to remand reasons](https://user-images.githubusercontent.com/23316107/36045617-46b0c94e-0da4-11e8-9d98-c2fe3edb8998.png)

### Related Issues
#4471 Add Dispositions
#4479 Confirmation Screens

**Comment by Chingujo** [comment]
@laurjpeterson 

Added A.C. and mocks - feel free to delete this comment after notification received/reviewed.

**Comment by laurjpeterson** [comment]
@Chingujo I added Vacate back into our list.

**Comment by amprokop** [comment]
Open technical questions, some for Jed, others to track down on our own:

1.  What VACOLS field corresponds to work product— is it `DECASS.DEPROD`?

1. What are the VACOLS values that correspond with `Decision, Remand, Vacate, OMO - VHA, OMO - IME, OMO - VHA, and IME`?

1. Which VACOLS field marks a work product as overtime, and what is the value used (boolean maybe?)

1. Confirm that `DEDOCID` corresponds to document ID?

1. Does `DEATCOM` or `DEBMCOM` correspond to the "Notes affecting timeliness" field?

**Comment by Chingujo** [comment]
Seems most of these are Jed questions. Will track down 6

**Comment by laurjpeterson** [comment]
I'll shoot an email to Jed with these questions! I asked him about Vacates today.

**Comment by laurjpeterson** [comment]
>1. What VACOLS field corresponds to work product— is it DECASS.DEPROD?  

Correct

>2.       Which VACOLS field marks a work product as overtime, and what is the value used (boolean maybe?)  

Same field DEPROD, just different values ‘DEC’ = regular decision, ‘OTD’ = Overtime decision, there’s more than those 2 values.

>3.       Confirm that DEDOCID corresponds to document ID? 

Correct.

>4.       Does DEATCOM or DEBMCOM correspond to the "Notes affecting timeliness" field?  

Correct, there are two comments fields one for the attorney and one for the Board Member (VLJ).

>5.       How can we best get a list of all current BVA judges?  

You can query the staff table for SVLJ = ‘J’ and SACTIVE = ‘A’;

@amprokop `Decision, Remand, Vacate, OMO - VHA, OMO - IME, OMO - VHA, and IME` are work products. Do you still need the VACOLS values for these? I forgot that one question.

**Comment by laurjpeterson** [comment]
Jed's also going to look into the logic for what happens in VACOLS when an issue (or issues) on appeal is Vacated and another record created.

**Comment by amprokop** [comment]
> @amprokop Decision, Remand, Vacate, OMO - VHA, OMO - IME, OMO - VHA, and IME are work products. Do you still need the VACOLS values for these? I forgot that one question.


@laurjpeterson yep if you get a chance

**Comment by laurjpeterson** [comment]
@amprokop - work product values attached. I need to make a crosswalk of which ones we are using and which ones to update VACOLS with and update the AC above.

For example, if the decision contains a grant and a remand, it may previously have been a 'Decision & Remand' work product. Since we're removing that work product, it would just map to Remand. 

[deprod.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/1686868/deprod.xlsx)

**Comment by Chingujo** [comment]
Updated AC and mocks based on the new flow. Also included the logic for auto filling the Work product for the "Ready for Judge review (DEC)" flow. 

Qq- since we are including Vacate as a work product now  @laurjpeterson does that mean we have to include all Vacates options: 

Vacate
Vacate and decision
Vacate and remand
Vacate and dismissal

**Comment by laurjpeterson** [comment]
@Chingujo I'm emailing David Ames about this crosswalk right now

**Comment by Chingujo** [comment]
@amprokop 
@amprokop 
> 1. How can we best get a list of all current BVA judges? Should we display their full names and CSS IDs in the list? 

The tables in VACOLS that holds all the employee information are updated by Jed every week. Other VACOLS application such as the HR app is also reliant on the same tables. So, we can pull from VACOLS. 

Displaying their first and last name world. Don't need CSS ID displayed on the front end.

**Comment by laurjpeterson** [comment]
@Chingujo take a look

**Comment by Chingujo** [comment]
@laurjpeterson 

Uploading and updating all the AC's and was wondering if we should split the OMO and Review Decision pages out to avoid confusion when this gets built or at least rename the issue since it's no longer work products. Thoughts?

**Comment by Chingujo** [comment]
final mocks uploaded, AC changed to reflect

**Comment by laurjpeterson** [comment]
good idea - making those changes now!
