### ISSUE TITLE
Attorney check out | Add an issue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4477]
When an attorney is checking out a draft decision to a judge where they've addressed an issue that wasn't yet tracked for the appeal, they need to add that issue, so that the Veteran's record is up to date for judge review.

### Acceptance Criteria
- [ ] Verify that when a user clicks the "Add issue" of the disposition screen they are taken to a page called "Add issue"
- [ ]  Verify that under "Add issue" there are the following dropdown labeled "Select Program" and "Select Issue'
-  [ ] Verify that there is a sub section called "Subsidiary Questions or Other Tracking Identifier(s)"
    **Note: These dropdown are conditional. For example, some issues only let you select two levels others three. This logic can be found here:
[Appendix F - VACOLS Issue Logic](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/BVA%20Work%20Queue/Research/Documents/Appendix%20F%20-%20VACOLS%20Issue%20Coding.pdf)
  - Verify that there are conditional dropdown for Levels 1 to 3 
- [ ]  Verify that after Level 3 there is a notes Input field
- [ ] Verify that there is a link to the bottom left of the canvas with the following copy "Go back to Select Disposition" and takes them to the Select Dispositions screen 
- [ ] Verify that there is a button on the bottom right called "Add issue" 
- [ ] Verify that it adds the new issue below the last issue in the Select Dispositions screen #4471 
- [ ] Verify that new issues are added to VACOLS

### Style guide components (top to bottom)
- Header
- Dropdown
- Text input field
- Link
 - Primary button
- Footer 

### Mocks and specs
![add issue screen](https://user-images.githubusercontent.com/23316107/35529726-f385bc5e-04ff-11e8-83ef-77041b059165.png)

### Related issues
#4471 - Enter Issue Dispositions

**Comment by Chingujo** [comment]
AC details added and uploaded mock

**Comment by amprokop** [comment]
@Chingujo — will these dropdowns have thousands of choices?

**Comment by Chingujo** [comment]
@amprokop 

Not thousands but quite a few. however, these should be able to pulled using existing issues logic. See [Appendix F - VACOLS Issue Logic](https://github.com/department-of-veterans-affairs/appeals-designresearch/blob/master/Projects/BVA%20Work%20Queue/Research/Documents/Appendix%20F%20-%20VACOLS%20Issue%20Coding.pdf)

I would assume that we would initially have to pull in most (almost all) of the programs and issues listed here barring some changes due to updates or removal of outdated issues. Levels are conditional based upon what issue is chosen per the above Appendix. 

 Hoping that it's easy to pull because the data exists already - finding out what is essential.

**Comment by amprokop** [comment]
@Chingujo — in that spreadsheet you linked, every time it says "Diagnostic code" there are a lot of potential options. 

See https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/constants/issue.rb, I'm not sure that list is complete either.

I think Intake should be doing some similar issue creation work, have you connected with them? We should attempt to share a component/some logic here if we can.

**Comment by laurjpeterson** [comment]
@amprokop the link you list is one that @cmgiven put together over the holidays as an attempt to make issues actually human readable. the hope is that they are used for appeals status, but they'd have to be approved. 

@sharonwarner and the Hearing Prep team currently add and edit issues. can we reuse logic there?

**Comment by Chingujo** [comment]
Is the concept of adding an issue the same across Caseflow? Hearing prep adds issue using a free text field I believe (according to Demo). If it's the same logic, are we just hiding some in the UI or are we using different logic based on app needs? +1 to using a similar issue logic and reaching out to Intake. 

<img width="1027" alt="screen shot 2018-02-01 at 1 51 14 pm" src="https://user-images.githubusercontent.com/23316107/35697021-044bf59a-0757-11e8-8ab9-8779663b4cf8.png">

**Comment by laurjpeterson** [comment]
ah yes - thanks for catching that @Chingujo I don't think we can re-use that.

**Comment by dannysellers** [comment]
@aroltsch No rush, but Phillip mentioned you might have a text dump of the descriptions/etc found in [Appendix F - VACOLS Issue Logic](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/BVA%20Work%20Queue/Research/Documents/Appendix%20F%20-%20VACOLS%20Issue%20Coding.pdf) that we could use on the front-end

**Comment by aroltsch** [comment]
@dannysellers I don't have it. We need to somehow get that list.
