### ISSUE TITLE
Attorney check out | Delete an issue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4478]
When an attorney checks out a draft decision to a judge, they want to be able to delete any irrelevant issues, but be prevented from deleting any by accident, so that the record reflects the most up to date data about a Veteran's appeal. 

### Acceptance Criteria
- Verify that when a user clicks delete issue from the "Edit Issue" page a modal with the title 'Delete Issue" appears
- Verify that the modal has the following copy: "You are about to permanently delete this issue. To delete please click the "Delete issue" button or click the "Go back link"  to return the previous screen. "
- Verify that the modal has a link text on the left with the following copy "Close" 
- Verify that there is a red secondary button labeled "Delete issue" 
- Verify that the Deleted issues no longer exist in VACOLS when the user confirms the delete within the modal

### Style guide components used:
- Modal

### Mocks and specs
![delete issue](https://user-images.githubusercontent.com/23316107/35883092-2623e8ca-0b54-11e8-9801-1142d930c1f6.png)

**Comment by Chingujo** [comment]
A.C. details added mock uploaded

**Comment by laurjpeterson** [comment]
@Chingujo the copy in the modal says "go back link" but the link in the modal is "close"

**Comment by dannysellers** [comment]
What should we do in cases where an appeal only has 1 issue? @amprokop @laurjpeterson

**Comment by Chingujo** [comment]
Great point @dannysellers 

If you are deleting a single issue appeal, you are basically closing that appeal out. Have not heard or can think of a use case in which this would exist. You are much more likely to edit the issue if it is wrong or change the disposition. 

If an appeal needs to be closed out that would be marked with a withdrawal, dismissal, or something along those lines seem more likely. 

What are your thoughts on only rendering the delete issue when 2 or more are apparent @laurjpeterson and @amprokop

**Comment by amprokop** [comment]
Oooh. @Chingujo, what if a user wants to delete and re-add an issue on an appeal with 1 issue? Do we just want them to edit?

**Comment by Chingujo** [comment]
Imo, think editing makes more sense because they basically achieve the same thing. 

Deleting + adding = two steps to change desired issue

Editing = one step to change to desired issue

**Comment by laurjpeterson** [comment]
+1 to editing. Today, I know some judges choose to delete then add an issue (Nate Kroes, for instance). But this could be behavior that we could change.

**Comment by Chingujo** [comment]
Woot! Will check with Nate (easy due diligence for a potential gotcha) but pretty sure that was for multi issue appeals.
