### ISSUE TITLE
Attorney check out | Confirmation screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4479]
When an attorney checks out a case to the judge, they want to see confirmation that it's been checked out, so they can move on to their next case.

#### Ready for judge review confirmation
- [ ] Verify that when the user clicks the "Check out decision" from the "Select Dispositions" screen that they are directed to the queue table with the following success message:
- Title: Thank you for drafting [Veteran Name]'s decision. It's been sent it to [Judge Name] for review."
- Body: If you need to make any changes, please email your judge.

#### OMO confirmation
- [ ] Verify that when the user selects OMO from the "Select Work Product" screen and submits that they are directed to the queue table with the following success message:
- Title: Thank you for drafting [Veteran Name]'s outside medical opinion (OMO) request. It's been sent it to [Judge Name] for review."
- Body: If you need to make any changes, please email your judge.

### React components used (top to bottom)
- Success confirmation banner

#### Check out decision
![decision confirmatin message](https://user-images.githubusercontent.com/23316107/36036445-e28660c6-0d87-11e8-960f-b1685f71f448.png)

#### Check out OMO 
![omo confirmatin message](https://user-images.githubusercontent.com/23316107/36036504-08699b82-0d88-11e8-84ac-dd58c0c1395f.png)

### Related issues
#4471 - Check out dispositions
#4465 - Work Product selection for OMO flow

**Comment by Chingujo** [comment]
Ac details added and mock uploaded

**Comment by laurjpeterson** [comment]
@Chingujo - @sneha-pai mentioned something a while back - how might we incorporate a personal touch when an attorney assigns a case/completes a draft decision or OMO? to connect purpose back to what attorneys are doing on a day to day basis.

what if we added a sentence to this confirmation banner - like "Thank you for your service to our Veterans. [Veteran Name's] decision has been successfully submitted to [First Name][Last name] for review."

**Comment by Chingujo** [comment]
@laurjpeterson 

I prefer it to be robotic. 

Jk...sounds good and I think it adds a good humanistic touch. I'll play with a few messaging types and post some examples including the ones you have.

**Comment by dannysellers** [comment]
I got a little tied up in playing the merge race game and forgot to update the confirmation messages... They're updated in #5051, which should be merged soon
