### ISSUE TITLE
Certification Confirmation:  Correct alignment and wording

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#450]
The congratulations page contains extra information that is not needed.  Additionally, the list text is not  aligned properly.  

1. Remove the Header section that contains the Appeal Type, File Type, and Representative.
1. The text below the words "Congratulations" should read as follows:  [veteran_firstname] [veteran_lastname] ([vbms_id]) case has been certified.
1. The check marked statements should be centered on the page in a list format.  (Refer to mockup and Kavi's last comments below)

## Mockup
**_View - Certification Confirmation - Before_**
![image](https://cloud.githubusercontent.com/assets/6335546/20332811/85e349c4-ab7c-11e6-9e33-58b23f8dcb84.png)
**_View - Certification Confirmation - After_**
![image](https://cloud.githubusercontent.com/assets/23063044/22007245/44e4ba54-dc3f-11e6-9d81-26e0eeddb296.png)

**Comment by shanear** [comment]
@KHarshawat This diverges from the designs for the claims establishment success page. Do we want to be shooting for them being consistent?

**Comment by KHarshawat** [comment]
Yes, I'd like us to make these changes in Caseflow Commons if possible but it's most relevant here.  @lakohl and I actually have a task to re-design this success message a bit so it's less awkard. Perhaps we should wait until that's completed?

**Comment by shanear** [comment]
ok, backlogging this guy

**Comment by nikitarockz** [comment]
@lakohl We were looking at this congratulations page and noticed that it isn't consistent with what we currently have in Dispatch.  Can we talk about this one and make a decision which way to go?

**Comment by shanear** [comment]
@KHarshawat this is also related to https://github.com/department-of-veterans-affairs/caseflow/issues/297

Can we figure out what we want here?

**Comment by lakohl** [comment]
@nikitarockz let's look at this tomorrow am

**Comment by KHarshawat** [comment]
@shanear @lakohl at the very least we should remove the excessive details from this page as mentioned in #297

**Comment by lakohl** [comment]
Agreed. Here is the design from #297 
![image](https://cloud.githubusercontent.com/assets/6335546/16694447/539d947c-4508-11e6-8c37-e8637d752ad6.png)

**Comment by KHarshawat** [comment]
Hi, after looking at the above and re-creating this bug I have a much better understanding for why the text is not aligned properly and what needs to be fixed. I'd like to pair with an engineer to fix this in Caseflow Commons but the gist is as follows:

- Right now the checkmarks are listed as `span` items, not `list-style-image`. This screws up indention
- We can get the desired result when the `ul` style has `margin: 0 auto;` and `max-width: 50%;`. This automatically centers the content in the page the the list items left aligned and works for variable content lengths in the `li`.
- I'd like to make sure we can make this consistent across Caseflow apps and that this results in minimal customization.

```
<ul style="
    margin: 0 auto;
    max-width: 50%;
">
  <li>Verified documents were in eFolderVerified documents were in eFolderVerified documents were in eFolderVerified documents were in eFolder</li>
  <li>Verified documents were in eFo</li>
</ul>
```

**Comment by lakohl** [comment]
@KHarshawat  based on the comments above, it's my understanding that the second line (below congratulations) should read:
> Davy Crockett's case (`VBMS ID`) has been certified. 

I'll try to re-mock this to show that, the check marks, and copy for different versions.

**Comment by KHarshawat** [comment]
@lakohl Correct!

**Comment by KHarshawat** [comment]
@lakohl no need .. re-mocked and attached here:

![congrats certification](https://cloud.githubusercontent.com/assets/6335546/20727605/21e2cbbc-b648-11e6-980c-4dc9b088cba6.png)

**Comment by nikitarockz** [comment]
@lakohl @KHarshawat Do we have a final mockup for this page?  This story will stay in Feature Definition until the mockup has been added and the Acceptance Criteria updated.  Just let me know when you are ready, I can make the changes and move this one forward.

**Comment by lakohl** [comment]
@nikitarockz the final design is above.

**Comment by kierachell** [comment]
Certification completion:
<img width="1223" alt="screen shot 2017-01-30 at 09 12 20" src="https://cloud.githubusercontent.com/assets/18075411/22426198/76cd1c22-e6cc-11e6-8831-ca8d17b34d17.png">
👍 


For reference current UI in Dispatch:
Dispatch Establishment and Assignment:
<img width="1229" alt="screen shot 2017-01-30 at 09 12 52" src="https://cloud.githubusercontent.com/assets/18075411/22426197/76cc97a2-e6cc-11e6-8551-5b3607f139a1.png">
<img width="1231" alt="screen shot 2017-01-30 at 09 13 23" src="https://cloud.githubusercontent.com/assets/18075411/22426199/76d0438e-e6cc-11e6-97a8-48f9037a96dc.png">
