### ISSUE TITLE
Intake | Remove notice date filter

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4501]
The RAMP business rules have been updated to allow all Veterans with eligible appeals to opt in to the program. This means a Veteran's opt-in is valid even if they did not receive an invitation to the program. We should remove the filter/alert that currently blocks users from processing a claim if they were not mailed a notice.

## Acceptance Criteria
- Caseflow no longer validates that a Veteran was sent a notice letter (did_not_receive_ramp_election alert)
- We'll still store notice dates for those that have them (not a mandatory field)

**Comment by shanear** [comment]
We no longer check this.
