### ISSUE TITLE
Expose month and docketMonth attributes in docket object

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4502]
## AC

* The `docket` object should have `month` and `docketMonth` attributes. These should be ISO-formatted dates, always rounded to the beginning of the month, equal to the month of the Form 9 and the latest month the Board is deciding, respectively.

**Comment by Sjones352** [comment]
**PASSED**
Validate with postman
1. Docket has `month` and `docketMonth`



<img width="961" alt="screen shot 2018-02-10 at 8 02 18 pm" src="https://user-images.githubusercontent.com/23080951/36068191-6902fb4e-0e9d-11e8-9cd6-0e8f187c6685.png">
