### ISSUE TITLE
Fetch the name of the judge who assigned a case to an attorney

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4503]
We believe the judge who assigned a case to an attorney can be found at `DECASS.DEADUSR`. We need to confirm this (check UAT data), and ensure the client receives the full name of the judge (not just CSS ID) so it can be rendered in the task details view. (This may require a join on the STAFF table) We'll need to update the Queue query in `case_assignment.rb`, send these attributes to `DraftDecision`, and ensure they're serialized with `task_serializer.rb` 

# AC
- The full name and CSS ID of the judge who assigned each case to an attorney are both sent as attributes on each task to the Queue front-end

**Comment by aroltsch** [comment]
I emailed Jed to confirm. He said:

```
In most case the VLJ will be the one adding the DAS so decass.deadusr would be accurate.
```
