### ISSUE TITLE
404 page should render in React

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4514]
# AC
- When users receive a 404, the 404 page should render as a React component (no React-Router necessary, we can just render the base component).

**Comment by amprokop** [comment]
@sneha-pai will be suggesting a change to the error text. She may make a new ticket or add to the AC here.

**Comment by sneha-pai** [comment]
When users receive a 404 error in Queue, the 404 page should display with standard copy (see mock below) and a link that takes them back to the My Queue page. 

Similarly, 404s for all Caseflow products should contain links that route back to the main page of the product.

### Mocks
![404-error-queue](https://user-images.githubusercontent.com/31224257/36010634-789e4122-0d20-11e8-9d2a-a5ffe549ede4.png)

@shellicious @laurjpeterson please advise for copy accuracy and clarity

**Comment by amprokop** [comment]
@sneha-pai — yep, @nolawi is right. This should probably be generic, as we'll serve a 404 page for every route that we don't have defined.

**Comment by sneha-pai** [comment]
@amprokop @nolawi - In that case, what's the best place this person can go to re-enter caseflow? Is there such a thing as a caseflow generic homepage?

**Comment by sneha-pai** [comment]
@amprokop @nolawi 
Revised Mocks to reflect your feedback above and in slack:
## Acceptance Criteria
When users arrives at a 404 error in any Caseflow product, the 404 page should display with standard copy (see mock below) with a link that takes them to Caseflow Help Page and an link that takes them to Feedback form.

### Mocks
![404-error-v2](https://user-images.githubusercontent.com/31224257/36041398-62ed80f6-0d96-11e8-8ae0-12987652dee5.png)
