### ISSUE TITLE
500 page should be rendered in React

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4515]
```
<% if @error_retry_external_service %>Please give <%= @error_retry_external_service %> a few moments to come back online, then <button type="button" class="cf-action-refresh cf-btn-link cf-btn-link--inline">refresh this page</button>. <% end %>
```
We don't need to port this bit over to React, as we don't use it anymore.

## AC
- The 500 page should be rendered as a React component (no router necessary, we can just render an Error500 component directly). 
- Unused code around the `error_retry_external_service` in the controller should be removed

## 
To test visit/500 and see error view

**Comment by Sjones352** [comment]
**PASSED**
Validate in Chrome
1. Access /500 page
2. Inspect page to see if it renders in react 

<img width="1274" alt="screen shot 2018-02-10 at 10 39 34 pm" src="https://user-images.githubusercontent.com/23080951/36069245-df31cde8-0eb3-11e8-85df-5c9b004ac8b3.png">
