### ISSUE TITLE
Hearing Worksheet | Remove extra line break btwn Appeal Streams

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4519]
Story: Extra link break shows between multiple appeal streams. 

AC: Remove extra line break when there are multiple appeal streams (line after +Add Issue and before Appeal Stream 2)

current mock: 
<img width="1085" alt="screen shot 2018-02-01 at 6 03 51 pm" src="https://user-images.githubusercontent.com/22620270/35708090-70dcc2ca-077a-11e8-9fe9-ea15a711300a.png">

**Comment by sharonwarner** [comment]
Will be fixed in #4383
