### ISSUE TITLE
[epic] Queue Phase 2 Backend: Outside Medical Opinion requests

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4523]
When reviewing cases, attorneys need to be able to send cases back to judges for two reasons:
- so the judge can review the draft decision
- to seek outside medical opinion where no draft decision can be completed yet 

We'll need to build both abilities for Phase 2 of Queue, but we'll build the second one first since it's simpler.

- Rename `DraftDecision` to `VacolsAssignment` https://github.com/department-of-veterans-affairs/caseflow/issues/4524
- Create the AttorneyCaseReview table https://github.com/department-of-veterans-affairs/caseflow/issues/4525
- Create shell VACOLS function for an OMO request and validations for that function https://github.com/department-of-veterans-affairs/caseflow/issues/4527
- Create VACOLS logic that marks a case as needing an OMO and reassigns it to a judge https://github.com/department-of-veterans-affairs/caseflow/issues/4533
- Create endpoint that returns a list of all current judges in VACOLS https://github.com/department-of-veterans-affairs/caseflow/issues/4534
- Create endpoint for an attorney to complete a case review task by creating an OMO request https://github.com/department-of-veterans-affairs/caseflow/issues/4636

**Comment by aroltsch** [comment]
All of the issues are complete in this epic.

**Comment by amprokop** [comment]
Validated that the case is successfully assigned to the judge, and that work product and document id are updated.

Here's the code I wrote to validate using a local vacols copy:

```
# find users with tasks assigned to them
sdomainids = VACOLS::Staff.all.map { |staff| staff.sdomainid }.compact
users_with_tasks = sdomainids.map { |sdomainid| [sdomainid, QueueRepository.tasks_for_user(sdomainid)] if QueueRepository.tasks_for_user(sdomainid).length > 0 }.compact


attorney = "READER"
judge = "CF_PICARD_397"
RequestStore[:current_user] = User.find_by(css_id: attorney)

tasks_and_appeals = AttorneyQueue.tasks_with_appeals(User.find_by(css_id: attorney))
num_tasks = tasks_and_appeals[0].length

judge_tasks_and_appeals = AttorneyQueue.tasks_with_appeals(User.find_by(css_id: judge))
num_judge_tasks = judge_tasks_and_appeals[0].length

# optional: ensure that the date has no hh:mm:ss if we're working with improperly sanitized data
task_id = tasks_and_appeals[0][0].task_id
task_date = task_id.split("-", 2)[1]
defolder = task_id.split("-", 2)[0]

decass = VACOLS::Decass.find_by(defolder: defolder)
decass.deassign = task_date
decass.save

complete_params = { type: "OMORequest", reviewing_judge: User.find_by(css_id: judge), attorney: User.find_by(css_id: attorney), task_id: tasks_and_appeals[0][0].task_id, overtime: true, work_product: "OMO - IME", document_id: "23432.432432"}

AttorneyCaseReview.complete!(complete_params)

new_tasks = AttorneyQueue.tasks_with_appeals(User.find_by(css_id: attorney))
new_num_tasks = new_tasks[0].length

new_judge_tasks_and_appeals = AttorneyQueue.tasks_with_appeals(User.find_by(css_id: judge))
new_num_judge_tasks = new_judge_tasks_and_appeals[0].length

puts "Attorney no longer assigned case: #{new_num_tasks == (num_tasks -1)}"
puts "Judge assigned new case: #{new_num_judge_tasks == (num_judge_tasks + 1)}"
```
