### ISSUE TITLE
Distribute EPs to additional stations of jurisdiction

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4526]
Additional offices will start working RAMP claims soon, so we need to distribute the work across multiple offices. To make this simpler, Caseflow can automatically assign EPs to specific VBMS work stations.

## Acceptance Criteria
- [Placeholder - pending AMO's business rules]

**Comment by laurjpeterson** [comment]
Closing because we've taken care of this in subsequent tickets.
