### ISSUE TITLE
Queue Feature Flag | Enable Pilot Group 1 – BVA users on 2/15/2018

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4529]
As Project Manager, I would like the following feature flag enabled on **_Thursday, 2/15/2018_** at **_11:00 am_** for the following users so that all users can enjoy this new feature.

**_Feature Flag_**:  Queue

## Acceptance Criteria
1.	Verify that the feature flag has been enabled been enabled for the following users only.

**_Pilot Group 1 - BVA:_**  16 users
"VACOFOSTEK5", "BVASKIM", "BVAKMITCHELL", "VACOWYSOKK", "VACOTANGM", "VACOKENINA", "BVAPJOHNS", "BVASPATEL", "VACOHURLES", "VACOBEHLER", "BVAABAKER", "BVASMISHA", "VACOMINEE", "BVAASOLOMON", "BVAKSCHAEFER", "BVAJJENKINS"

## Related Stories
IP | Queue | Add users to rollout (Pilot) – BVA Group 1 [#1792](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1785)

**Comment by nikitarockz** [comment]
2/15/2018 @ 1:15 pm Users Enabled
