### ISSUE TITLE
Hearing Worksheet | update efolder to claims folder

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4532]
**Story:** to be more consistent with content and Reader, we are moving from eFolder to Claims Folder.

**AC:** 
- On the Hearing Worksheet, update "Docs in eFolder: 400" to "Docs in Claims Folder: 400"
- On the Hearing Worksheet, update "Review eFolder" button to "Review claims folder" button. (lower case)

**Comment by sharonwarner** [comment]
Duplicate of #4228
