### ISSUE TITLE
Create VACOLS logic that marks a case as needing an OMO and reassigns it to a judge

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4533]
Part of https://github.com/department-of-veterans-affairs/caseflow/issues/4523
We need to update VACOLS with OMO request information.

## total WIP, not trustworthy AC
- find the DECASS row reflecting the current assignment (there should only be one) 
  - where `decass.defolder` is the vacols id, `decass.decomp` is null, and `staff.sdomainid` is the css id of the current user
  - join `brieff` on `brieff.bfkey = decass.defolder` and joining `staff` on `brieff.bfcurloc = staff.slogid`
  - update `deprod` to the correct value for Work Product from VACOLS (determined in another ticket)
  - set `decomp` to the current date 
  - set `detcom` to the note that the attorney entered
  - set `dedocid` to the document id that the attorney entered of the OMO document in SharePoint
- on the `staff` table, update `sdomainid` to the CSS ID of the judge (?)
- Do all of the following in a transaction

# Open Questions
- Confirm all of the above with Jed
- There appears to be a lock column at `DECASS.DELOCK`. Should we use it in our update? If so, does that require waiting until DELOCK is a certain value, then setting it to a certain value?
- We don't need to create a new DECASS row, correct?

**Comment by aroltsch** [comment]
Jed's response:

![image](https://user-images.githubusercontent.com/3811786/35935437-800316da-0c0e-11e8-86cf-4e0843b27fd8.png)

**Comment by aroltsch** [comment]
To update BRIEFF.BFCURLOC and create a new row in PRIORLOC, we can use the method: ```appeal.case_record.update_vacols_location!(location)```
