### ISSUE TITLE
Add details to status objects

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4543]
## AC

* The `details` object for the `scheduled_hearing` status should include `type` (the type of hearing, central_office, travel_board, or video), `date` (the date the hearing is scheduled for), and `location` (a text description of where the hearing will occur, typically the regional office, i.e. "Oakland regional office").
* The `details` object for the `pending_hearing_scheduling` status should include `type` (the type of hearing requested, central_office, travel_board, or video).
* The `details` object for the `pending_form9`, `pending_certification`, and `pending_certification_ssoc` statuses should include `lastSocDate` (the date of the last SOC or SSOC), `certificationTimeliness` (the range of months it typically takes to certify an appeal), `ssocTimeliness` (the range of months it typically takes to create an SSOC).
* The `details` object for the `pending_soc` status should include `socTimeliness` (the range of months it typically takes to create an SOC or field grant).
* The `details` object for the `at_vso` status should include `vsoName` (the name of the VSO on the appeal).
* The `details` object for the `decision_in_progress` should include `decisionTimeliness` (the range of months it typically takes to mail a decision after the appeal has been first assigned to an attorney).
* The `details` object for the `bva_decision` and `remand` statuses should include an array of `issues`, each of which should have a `description` and a `disposition`.
* The `details` object for the `remand` status should include `remandTimeliness` (the range of months it typically takes to either create an SSOC, field grant, or return to the Board a remand).
* The `details` object for the `remand_ssoc` status should include `lastSocDate` (the date of the last SSOC), `returnTimeliness` (the range of months it typically takes to return a remand to the Board after creating an SSOC), and `remandSsocTimeliness` (the range of months it typically takes to create a second SSOC on a remand).

**Comment by Sjones352** [comment]
* The `details` object for the `pending_soc` status should include `socTimeliness` (the range of months it typically takes to create an SOC or field grant).

<img width="536" alt="screen shot 2018-02-23 at 8 14 17 pm" src="https://user-images.githubusercontent.com/23080951/36623810-303f76e6-18d6-11e8-8c93-9db2e2376a39.png">
