### ISSUE TITLE
Hearing Worksheet | Update Issue headers spacing

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4545]
Update the Issue section header and the spacing between issue row and add issue button to 28px, and following appeal stream header. In addition, update spacing when after an issue row is deleted to be consistent. 

**AC:**
1. Update the spacing between the Add Issue button and issue above it to be 28px
1. Update the spacing between the issue table headers (Issue, Notes, Disposition...) and the Add Issue button to be 28px when no issues are displayed.
1. Update space above and below the line that divides appeal steam and the next element to be 28px.

**Curent Mock:** 
With issues: 
<img width="1088" alt="screen shot 2018-02-05 at 12 04 10 pm" src="https://user-images.githubusercontent.com/22620270/35821002-8d738a4c-0a75-11e8-91de-61cedc7a58dc.png">

without issues:
<img width="1087" alt="screen shot 2018-02-05 at 12 03 52 pm" src="https://user-images.githubusercontent.com/22620270/35821024-9a492e52-0a75-11e8-9c7d-0229f8828aa6.png">

**Desired Mock:**
With Issues:
![with issues](https://user-images.githubusercontent.com/4975959/36003746-51744e84-0cfd-11e8-9c01-31ccc65a714c.png)

Without Issues:
![no issues](https://user-images.githubusercontent.com/4975959/36003569-a917de5e-0cfc-11e8-8bf0-5961899bae2d.png)

**Comment by lakohl** [comment]
@annienguyenUSDS I think I accidentally deleted your AC  😁
