### ISSUE TITLE
Update call to efolder manifest fetch progress API endpoint

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#4551]
A [recent change](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/856) to the efolder v2 api requires the manifest ID when requesting the progress of the manifest fetch. The endpoint that was previously `GET http://efolder.cf.ds.va.gov/api/v2/manifests` with the veteran ID coming across in the HTTP_FILE_NUMBER header element now becomes `GET http://efolder.cf.ds.va.gov/api/v2/manifests/:manifest_id` with no veteran ID in the HTTP headers.

**Comment by mdbenjam** [comment]
Completed in an earlier PR (https://github.com/department-of-veterans-affairs/caseflow/pull/4737/files)
