### ISSUE TITLE
Route private attorney cases to ARC

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4556]
The ARC recently decided to work private attorney cases at the ARC, rather than sending them to the field. This means we need to update our routing logic in Dispatch so that private attorney cases are routed to ARC's station, rather than the originating regional office.

## Acceptance Criteria
- If a user selects the Private Attorney or Agent special issue, Caseflow routes the case to the ARC (station 397, RO97)

**Comment by abbyraskinUSDS** [comment]
@sharonwarner we got some feedback from the ARC that private attorney cases are still getting routed to location "50" in VACOLS. any thoughts on whether we might have a bug?

**Comment by nicholasholtz** [comment]
@abbyraskinUSDS are cases actually being dropped here or is this in the realm of an inconvenience?
