### ISSUE TITLE
Navigation | Help | FAQs | Replace existing questions and answers with updated version

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4562]
As a Project Manager, I would like to replace the existing questions and answers with an updated version of questions and answers so that all users will have the latest answers.

## Acceptance Criteria
**_Frequently Asked Questions section_**
1. Verify that the questions have been updated to the new set of questions in the correct order presented.   (Refer to Hearing Prep FAQs - [HearingPrep_FAQs_????](???))
1. Verify that each new question is a hyperlink to its answer in the FAQ Answer section.

**_FAQ Answer section_**
1. Verify that all newly added questions and their answer are displayed.  (Refer to Hearing Prep FAQs - [HearingPrep_FAQs_???](???))
1. Verify that all images are displayed correctly.

## Mocks
**_Current Help Page - update FAQs section_**
![hearing prep help page 1](https://user-images.githubusercontent.com/23038386/35885713-ac742336-0b86-11e8-97b5-6ceceb6bf547.JPG)
![hearing prep help page 2](https://user-images.githubusercontent.com/23038386/35885749-ca78a9ba-0b86-11e8-9d5b-7910d13a7b64.JPG)

# Related Story
**_PM/Training Issues_**
IP | Hearing Prep | Create Engineer Story for Training Material Updates [#1788](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1788)
Hearing Prep | FAQs | Update questions – Pilot Deliverable [#115](https://github.com/department-of-veterans-affairs/appeals-training/issues/115)
Hearing Prep | FAQs | Update questions - Pilot Deliverable [#72](https://github.com/department-of-veterans-affairs/appeals-training/issues/72)

**Comment by wturne** [comment]
Engineering story updated with latest version of the Hearing Prep FAQs dated Feb 2018. 

[HearingPrep_FAQs_Feb2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1708741/HearingPrep_FAQs_Feb2018.pdf)

**Comment by wturne** [comment]
Engineering story updated with latest version of the Hearing Prep FAQs dated April 2018.  This FAQs version replaces FAQs dated February 2018. 

[HearingPrep_FAQs_April2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1928307/HearingPrep_FAQs_April2018.pdf)

**Comment by wturne** [comment]
Engineering story updated with latest version of the Hearing Prep FAQs dated May 2018.  This FAQ version replaces FAQ dated April 2018.  

[HearingPrep_FAQs_May2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1984133/HearingPrep_FAQs_May2018.pdf)
