### ISSUE TITLE
Navigation | Help | Update link to display current Training Guide and removal of Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4563]
As a Project Manager, I would like to have the link to the Training Guide updated and the link to the Quick Reference Guide removed on the Help Page, so that the users can obtain the most current help information on how to use Hearing Prep.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that the copy has been updated to the following.
     > Here you will find [Training Videos]() and [Frequently Asked Questions (FAQs)](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep_FAQs_Jun2018.pdf) for Hearing Prep, as well as link~s~ to the [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep.Training.Guide_Jun2018.pdf). These items are provided to assist you as you access and use Hearing Prep. If you require further assistance after reviewing these items, please contact the Caseflow Product Support Team by phone (1-844-876-5548) or email (caseflow@va.gov). We look forward to assisting you.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. [Hearing Prep Training Guide_Jun2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep.Training.Guide_Jun2018.pdf)
1. Verify the when the "Training Guide" pdf is displayed in the new tab, the name is displayed as "Hearing Prep User Training Guide".

**_FAQ Answer Section_** 

_"What is Caseflow Hearing Prep?"_
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Hearing Prep Training Guide_Jun2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep.Training.Guide_Jun2018.pdf)

_"What should I do if I encounter problems?"_
1. Verify that copy has been updated to the following:
     > Reviewing the [FAQs](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep_FAQs_Jun2018.pdf) or [Training Guide](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep.Training.Guide_Jun2018.pdf) may help you with most questions or issues.  They may be accessed by clicking Help, located in the dropdown menu next to your username. However, if you encounter any problems while using Hearing Prep, feel free to send feedback using the “Send Feedback” in the Help menu or the link at the bottom of the page. Additionally, you may contact the Caseflow Product Support Team by calling 1-844-876-5548 or sending an email to caseflow@va.gov. They can be reached from 8:00AM to 8:00PM ET, Monday through Friday.

1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Hearing Prep Training Guide_Jun2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Hearing%20Prep/HearingPrep.Training.Guide_Jun2018.pdf)
1. Verify the when the "Training Guide" pdf is displayed in the new tab, the name is displayed as "Hearing Prep User Training Guide".

## Mocks
**_Help Page - Introduction section requiring change_**
![hearing prep help page 1](https://user-images.githubusercontent.com/23038386/35886875-6de86452-0b8a-11e8-91c0-58e418decebb.JPG)

**_Help Page - FAQ Answers section:  First Question requiring change_**
![hearing prep help page first faq](https://user-images.githubusercontent.com/23038386/35886925-9f519e8c-0b8a-11e8-9057-670cb7c8c524.JPG)

**_Help Page - FAQ Answer section:  Last Question requiring change_**
![hearing prep help page last faq](https://user-images.githubusercontent.com/23038386/35886984-c5d1a5ca-0b8a-11e8-91ae-2fc3dcb4bd72.JPG)

# Related Stories
Navigation | Help | FAQs | Replace existing questions and answers with updated version #4562

**_PM/Training Issues_**
Hearing Prep | FAQs | Update questions - Pilot Deliverable [#72](https://github.com/department-of-veterans-affairs/appeals-training/issues/72) 
Hearing Prep | Quick Reference Guide | Update guide - Pilot Deliverable [#117](https://github.com/department-of-veterans-affairs/appeals-training/issues/117)
Hearing Prep | Training Guide | Update guide - Pilot deliverable [#116](https://github.com/department-of-veterans-affairs/appeals-training/issues/116)

**Comment by wturne** [comment]
Updated links for FAQs with latest version of Hearing Prep FAQs dated April 2018. 

[HearingPrep_FAQs_April2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1928388/HearingPrep_FAQs_April2018.pdf)

**Comment by wturne** [comment]
Updated links for Training Guide with latest version of Hearing Prep Training Guide dated May 2018. 

[HearingPrep.Training.Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1979919/HearingPrep.Training.Guide_May2018.pdf)

**Comment by wturne** [comment]
Updated links for FAQs with latest version of Hearing Prep FAQs dated May 2018. 

[HearingPrep_FAQs_May2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1979951/HearingPrep_FAQs_May2018.pdf)

**Comment by wturne** [comment]
Updated the links and the narrative for the Hearing Prep Training Guide and the Hearing Prep FAQs.  



[HearingPrep_FAQs_Jun2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/2255085/HearingPrep_FAQs_Jun2018.pdf)
