### ISSUE TITLE
Navigation | Help | Update link to display current Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#4564]
As a Project Manager, I would like to have clearly visible and accessible links to both the Training Guide and Quick Reference Guides displayed on the Help Page, so that the users can obtain additional detailed information on how to use Intake.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. [Intake Training Guide_April2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_April2018.pdf)
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab. [Intake_QRG_Apr2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Quick_Reference_Guide_Apr2018.pdf)

**_FAQ Answer Section_** 

_"What is Caseflow Intake?"_
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Intake Training Guide_April2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_April2018.pdf)

_"What if I still need help?"_
1. Verify that when the link "Quick Reference Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Intake_QRG_Apr2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Quick_Reference_Guide_Apr2018.pdf)
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Intake Training Guide_April2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/Intake_Training.Guide_April2018.pdf)

## Mocks
**_Help Page - Introduction section requiring change_**
![intake welcome faq](https://user-images.githubusercontent.com/23038386/35887997-19ecf116-0b8e-11e8-8410-a51f384e386e.JPG)

**_Help Page - FAQ Answers section:  First Question requiring change_**
![intake faq 1](https://user-images.githubusercontent.com/23038386/35888027-359bdb5c-0b8e-11e8-89e9-dadf5e7c8d83.JPG)

**_Help Page - FAQ Answer section:  Last Question requiring change_**
![intake faq last](https://user-images.githubusercontent.com/23038386/35888051-4c5b6ef2-0b8e-11e8-92b5-90beb08b05c4.JPG)

# Related Stories
**_PM/Training Issues_**
IP | Intake | Create Engineer Story for Training Material Additions [#1780](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1780)
Intake | Quick Reference Guide | Update guide (Selection) – Prototype Deliverable [#125](https://github.com/department-of-veterans-affairs/appeals-training/issues/125)
Intake | Training Guide | Update guide (Selection) – Prototype Deliverable [#61](https://github.com/department-of-veterans-affairs/appeals-training/issues/61)
Intake | Quick Reference Guide | Update guide (BVA Appeals) - Pilot Deliverable [#141](https://github.com/department-of-veterans-affairs/appeals-training/issues/141)

**Comment by wturne** [comment]
Updated engineering story with the link to the latest version of the Caseflow Intake QRG dated Feb 2018. 

[Intake_Quick_Reference_Guide_Feb2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1708808/Intake_Quick_Reference_Guide_Feb2018.pdf)

**Comment by wturne** [comment]
Updated engineering story with the link to the latest version of the Caseflow Intake Training Guide dated Feb 2018. 

[Intake_Training.Guide_Feb2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1708868/Intake_Training.Guide_Feb2018.pdf)

**Comment by wturne** [comment]
Updated engineering story with the link to the latest version of the Caseflow Intake QRG dated April 2018.  

[Intake_Quick_Reference_Guide_Apr2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1875991/Intake_Quick_Reference_Guide_Apr2018.pdf)

**Comment by wturne** [comment]
Updated engineering story with the link to the latest version of the Caseflow Intake Training Guide dated April 2018.  This replaces the version dated March 2018.  

[Intake_Training.Guide_April2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1984370/Intake_Training.Guide_April2018.pdf)

**Comment by msj0nes** [comment]
# Ticket Obsolete
