### ISSUE TITLE
Dispatch: VACOLS and VBMS using different IDs to track cases?

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4567]
BVA Dispatch has observed that when the ID that is used in VACOLS (SS?) is entered into VBMS the system recognizes it, but switches it to a different set of 8 numbers. They are concerned that as a result decisions uploaded by BVA Dispatch are not recognized by Caseflow and remain on the Missing Decisions page even when a decision is uploaded.

**Comment by sharonwarner** [comment]
I confirmed that VACOLS and VBMS are using different IDs to track these cases. 

For the two examples that Lara sent me, each has two IDs: a claims file number and an SSN. VBMS only returns documents for the claims file number, but VACOLS only returns appeals for the SSN. We're making the request to VBMS with the SSN and getting no documents, so we're inaccurately marking these tasks as missing decision documents. 

Solutions we can try:
1) Generally, when VBMS is using the claims file id, VACOLS stores it in the BFCORLID field in the BRIEFF table, however, for these cases, VACOLS is still storing the SSN in BFCORLID. We could figure out why VACOLS is storing the wrong number for these cases (approximately 30), and see if it's fixable.
2) We could update our appeal_repository such that, if VBMS doesn't return any documents for a veteran's SSN, we could try to get the claims file id from either BGS or VBMS and then make another request with the correct claims file id. 
3) We could ask VBMS to update their API to return the eFolder for a veteran's SSN or claims file id. Their UI currently does this.

**Comment by cmgiven** [comment]
On 1, just a small note that the BFCORLID is manually entered. However, it does match the file number that will be printed on decisions. We need more information about why some Veterans have two file numbers. I'm not sure that we can just "fix" VACOLS, as there might be a reason why we need to continue to use the file numbers that are currently there, even as the eFolder is stored under a different ID.

**Comment by sunil-sadasivan** [comment]
Chatted with Sharon, IRL.  Sharon will ask VBMS if there is a VBMS endpoint to look up claims file id given a veteran's SSN (just as it is possible to do in the VBMS UI).  

If not, we'll need to explore if this option is available via BGS.  In general my intuition would be to go with #2 as that may handle other cases gracefully we're unaware of. .

**Comment by cmgiven** [comment]
Is it only ever S numbers being converted to C numbers?

**Comment by sharonwarner** [comment]
I have the numbers available if you want to look at them. They look completely different to me. The two cases I looked into are both old, I'm assuming they're from before VBMS started using SSNs.

**Comment by cmgiven** [comment]
Yeah, so the question is do the VACOLS numbers all end in "S" (indicating that they are newer, SSN-based numbers) and the VBMS ones all end in "C" (indicating older file numbers).

**Comment by sharonwarner** [comment]
Ah, I see. The number in BFCORLID ends in 'S', at least in the two examples I looked into.

**Comment by cmgiven** [comment]
If that's true of all of them, then we can probably just use the existing BGS endpoint for looking up people by SSN just by removing the 'S'. That's assuming that BGS is probably the source of truth for what VBMS is using.
