### ISSUE TITLE
Reader | Text box is now typing the error message

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#4570]
**Currently:** When accessing Reader and searching for a veteran, if the veteran has no appeals, then the user is prompted an error. After accessing the error, the user goes back to the text box to change the veteran ID and notices the error changes with the keystrokes. 

**Expected:** Not this. A static message based on the initial search. 

**Found:** UAT | Chrome 

**Steps to Reproduce:**
1. Access Reader
2. Search a veteran Id without appeals
3. Verify error message
4. Start changing the info in the search box
5. Verify that the info changing is affecting the error message displayed. 

**Screenshots:**
![readerbug1](https://user-images.githubusercontent.com/23038505/35926777-09ef9192-0bf7-11e8-9543-949f57d4866e.gif)

**Comment by mdbenjam** [comment]
This has been fixed in a previous PR.
