### ISSUE TITLE
Intake | Typo in Error message

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#4571]
**Currently:** There is a typo found in the error message given to a user trying to use a RAMP eligible veteran for Selection, instead of opt in. "tf"

**Expected:** No Typos, "tf" could possible be "the"

**Steps to Recreate:**
1. Access Intake 
2. Select "Selection"
3. Search a veteran Id that is RAMP eligible
4. Verify that there is a typo in the resulting error message. 

**Screenshots:**
<img width="1189" alt="screen shot 2018-02-07 at 11 10 30 am" src="https://user-images.githubusercontent.com/23038505/35927083-c961b5e6-0bf7-11e8-97aa-e2a40fcc0565.png">

**Comment by abbyraskinUSDS** [comment]
Closing this in favor of #4589 where I changed the copy slightly (in addition to fixing the typo).
