### ISSUE TITLE
Intake Stats | Disaggregate some stats up by review type

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4574]
AMO needs the ability to look up some stats disaggregated by the review type.

## Acceptance Criteria

In the " Ramp Elections Sent" section:
  - Change "Number Returned" to "Total Returned"
  - Add stats for "Higher Level Reviews Returned", "Higher Level Reviews with Informal Conference Returned", "Supplemental Claims Returned"

In the " Ramp Elections Received" section:
  - Add stats for "Higher Level Reviews", "Higher Level Reviews with Informal Conference", "Supplemental Claims"

## Notes

order of stats should be:

**Ramp Elections Sent for <TIME>**
Total
Higher Level Reviews Returned
Higher Level Reviews with Informal Conference Returned 
Supplemental Claims Returned
Total Returned
Percentage Returned
Average Response Time

**Ramp Elections Received for <TIME>**
Total
Higher Level Reviews
Higher Level Reviews with Informal Conference
Supplemental Claims
Average Response Time

**Comment by shanear** [comment]
@leahbannon validate this in prod on the stats page

**Comment by leahbannon** [comment]
In the "Ramp Elections Sent" section, missing: "Higher Level Reviews with Informal Conference Returned"

In the " Ramp Elections Received" section, missing: "Higher Level Reviews with Informal Conference"

**Comment by leahbannon** [comment]
looks good
