### ISSUE TITLE
Intake Stats | Ramp Refiling Stats

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4578]
AMO needs the ability to look up the response time of RAMP invites were returned based on their sent date.

## Acceptance Criteria
- On the intake stats page, there should be a section for Ramp Refilings received. Which should have the total number of ramp refilings received, and also number received disaggregated by review type.

## Notes
The section should be at the bottom of the intake stats page and have the following stats/copy:

**Ramp Refilings Received for <TIME>**
Total
Higher Level Reviews
Higher Level Reviews with Informal Conference
Supplemental Claims
Appeals

**Comment by shanear** [comment]
People from AMO are asking about this. So setting it as the highest priority.

**Comment by shanear** [comment]
@leahbannon validate this in prod on the stats page

**Comment by leahbannon** [comment]
missing "Higher Level Reviews with Informal Conference"

**Comment by leahbannon** [comment]
looks good!
