### ISSUE TITLE
Intake Stats | Add "Total without Opt In" to Received Ramp Elections stats

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4579]
AMO needs the ability to look up how many Ramp Elections were received without an opt in notice. 

## Acceptance Criteria
- On the intake stats page, under the "Ramp Elections Received" section, there should be a stat for the total received without an opt in. This would show the total RAMP Elections received where a notice was not sent.

## Notes
The order for the section should be:

**Ramp Elections Received for <TIME>**
Total
Higher Level Reviews
Higher Level Reviews with Informal Conference
Supplemental Claims
Total without Opt In
Average Response Time
Average Time since NOD
Average Control Time

**Comment by abbyraskinUSDS** [comment]
Deprioritizing this for the time being - closing.
