### ISSUE TITLE
Only expose `AppealRepository.uncertify` in non-prod environments

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#458]
`AppealRepository.uncertify` is potentially dangerous and it'd be best to only expose it in non production environments.

See discussion here: https://github.com/department-of-veterans-affairs/caseflow/pull/453#pullrequestreview-8897850

**Comment by kierachell** [comment]
I guess I should've seen this... Oh well. I'll address it tomorrow along with the other testing stuff.

**Comment by kierachell** [comment]
Well, there are checks on it and it might be needed later on; 
Closing this after an approval from @joofsh
