### ISSUE TITLE
Intake Stats | Add Average Control Time

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4585]
## Acceptance Criteria
- On the intake stats page, under the "Ramp Elections Received" section, there should be a stat for the "Average Control Time". This would show the average time between the receipt date and the control date (the date it was processed) of the RAMP election.
- If the date it was processed can not be found. Don't include it in the average.

## Notes
The order for the section should be:

**Ramp Elections Received for <TIME>**
Total
Higher Level Reviews
Higher Level Reviews with Informal Conference
Supplemental Claims
Total without Opt In
Average Response Time
Average Time since NOD
Average Control Time

**Comment by shanear** [comment]
I'm thinking we will want to add `established_at` to RampElections just like we did with RampRefilings so we don't have to do any weird joins on intakes that may or may not be there.

**Comment by shanear** [comment]
@leahbannon validate this in prod on the stats page

**Comment by leahbannon** [comment]
validated the section exists on the stats page
