### ISSUE TITLE
Intake Stats | Average Time since NOD

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4587]
## Acceptance Criteria
- On the intake stats page, under the "Ramp Elections Received" section, there should be a stat for the "Average Time since NOD". This would show the average time between the date the NOD was filed and the control date of the RAMP election (the date it was processed)

## Technical Notes
This will require us to query VACOLS for the closed appeals. We currently don't keep a handle on the appeals closed by any one RAMP election. We could calculate that based on close date and close disposition. Just wouldn't be easy 😄 

Additionally, to avoid excessive VACOLS calls, we can begin recording some data in the Caseflow DB about the appeals that were closed for RAMP. We don't do this currently.

## Notes
The order for the section should be:

**Ramp Elections Received for < TIME >**
Total
Higher Level Reviews
Higher Level Reviews with Informal Conference
Supplemental Claims
Total without Opt In
Average Response Time
Average Time since NOD
Average Control Time

**Comment by leahbannon** [comment]
@shanear I validated on staging that the section was added. It's lovely. But I can't validate that the data going into the bars is correct -- can you validate that?
