### ISSUE TITLE
Fix EP error typo 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4589]
If a Veteran attempts to search for a Veteran in the Selection flow, they will receive an alert if the EP is still pending - there's currently a typo in our alert message. See suggested copy below, which fixes the typo and cleans up the messaging.

Current:
![image](https://user-images.githubusercontent.com/4042181/35977213-6f823834-0cb0-11e8-9d31-828c6db670da.png)

Expected:
- The body copy should read: If this Veteran has not yet received a decision for their RAMP Opt-In Election, notify them using the "RAMP Ineligible Letter" (premature election).

**Comment by leahbannon** [comment]
(not to leah for testing: 1. create ramp election 2. create ramp refiling)

**Comment by leikkisa** [comment]
@suzchap the numbers above are still good.  The page is supposed to show an error, the error copy is what is getting validated.

**Comment by suzchap** [comment]
These might be questions for @abbyraskinUSDS....

Neither message matches the AC Copy exactly. Is the election copy newer than this issue maybe? The selection copy is only off by a word or two... fine as-is or should it match the AC copy exactly? 

RAMP election, I get this message:
<img width="777" alt="screen shot 2018-08-08 at 1 29 30 pm" src="https://user-images.githubusercontent.com/11219417/43853841-4530c44a-9b0f-11e8-9607-f086293b8ad3.png">

RAMP selection, I get this message:
<img width="1102" alt="screen shot 2018-08-08 at 1 36 47 pm" src="https://user-images.githubusercontent.com/11219417/43854194-257d617a-9b10-11e8-9170-09f73794ce73.png">

**Comment by abbyraskinUSDS** [comment]
I believe this ticket only relates to the refiling/selection error. The only difference I see is the word "Form" was added, which I _do_ think we should correct before approving - they don't get a decision on the form, they get a decision on the type of review.

**Comment by abbyraskinUSDS** [comment]
good catch - also RAMP decision is less redundant in copy provided in ticket

**Comment by suzchap** [comment]
Ok, moving it back to "current sprint" to match RAMP Selection error message to:

"If this Veteran has not yet received a decision for their RAMP Opt-In Election, notify them using the "RAMP Ineligible Letter" (premature election)."

**Comment by leikkisa** [comment]
@leahbannon You should be able to validate this with test file number 561349913

**Comment by suzchap** [comment]
LGTM
