### ISSUE TITLE
Add array of BFKEYs to API results

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4592]
## AC

* The Appeals API should return an attribute called `appealIds`, an array of strings.
* These should match all of the Appeals present on the AppealSeries.
* Vets.gov will use these to match URLs referring to previous appeal ids.

**Comment by Sjones352** [comment]
**PASSED**
Validate Postman
Returns attribute`appealIds` an array of strings
<img width="966" alt="screen shot 2018-02-10 at 9 34 39 pm" src="https://user-images.githubusercontent.com/23080951/36068747-7f60454c-0eaa-11e8-830d-31f065ad0942.png">



<img width="971" alt="screen shot 2018-02-10 at 9 35 13 pm" src="https://user-images.githubusercontent.com/23080951/36068745-78634e88-0eaa-11e8-892b-4178896432f0.png">
