### ISSUE TITLE
Hearing Worksheet | Update issue header styles

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4597]
Update the Issue headers as follows

## AC
1. Instead of each Appeal Stream having it's own h2, create a single header for the Issues section. The copy for this single h2 for the Issues section should be 'Issues on Appeal'
1. Label each Appeal Stream under 'Issues on Appeal' as follows: 'Appeal Stream [#] Issues' using 17px, bold

## Mock
**_Desired_**
![appeal streams](https://user-images.githubusercontent.com/4975959/36053723-d130399e-0dc0-11e8-83b1-24e7302c6b72.png)

**_Current_**
![fireshot capture 6 - g merica s hearing worksheet_ - http___dsva-appeals-certification-d](https://user-images.githubusercontent.com/4975959/36053817-55a2e226-0dc1-11e8-8b39-7b61e78d9d71.png)

**Comment by Sjones352** [comment]
@lakohl Question
So currently we have Current Issues as a tab header, Isn't it over kill if we have `Issues on Appeal` too as a header yet we also have `Prior Issues` ?
<img width="485" alt="screen shot 2018-04-02 at 6 15 17 pm" src="https://user-images.githubusercontent.com/23080951/38220472-56b2f240-36a8-11e8-8a2e-214d8e9aa98f.png">


Currently the PR looks like this https://github.com/department-of-veterans-affairs/caseflow/pull/5041
<img width="692" alt="screen shot 2018-04-02 at 6 40 26 pm" src="https://user-images.githubusercontent.com/23080951/38220456-480b61d2-36a8-11e8-9e03-828f9e9d717a.png">
