### ISSUE TITLE
Hearing Worksheet | Update how document dates are displayed

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4599]
AC:
1. Change section header from 'Relevant Documents' to 'Procedural History'
1. Create an Accordion (Similar to the Reader Claims folder details) to contain the key documents and their dates. Accordion should be open when page loads.)
1. Include '[#] Documents in the claims folder' after the label 'Key Documents'.
1. Align '[#] Documents in the claims folder' with the first column of document dates.
1. Above each set of document dates indicate 'Appeal Stream [#] - Docket #[#]'
1. Bold and left align document labels.
1. Display the document date to the right of the document label.
1. Right align document dates.
1. Separate documents with a short thin grey line.
1. Separate appeal streams with a longer thin grey line.

Current:
![fireshot capture 3 - g anthony s hearing worksheet_ - http___dsva-appeals-certification-d](https://user-images.githubusercontent.com/4975959/36032146-10cead10-0d7b-11e8-8e4f-6cccdd67ac97.png)

Desired:
![docs regular](https://user-images.githubusercontent.com/4975959/39273163-11c135be-48ac-11e8-862d-3a642421fbf6.png)

![docs](https://user-images.githubusercontent.com/4975959/38470630-af584faa-3b33-11e8-8c5b-2037deb06014.png)

**Comment by annienguyenUSDS** [comment]
To update with total percentage.

**Comment by lakohl** [comment]
to add mock

**Comment by lakohl** [comment]
squish no rating percentage

**Comment by lakohl** [comment]
@annienguyenUSDS wanted to check with you on the Rating Decision date (this would be an added date). Can we correlate the rating decision to the appeal stream at all? or will we always be showing the latest one? Also, what are your thoughts on 'Procedural History' vs. 'Relevant Documents' as a heading?

**Comment by lakohl** [comment]
@annienguyenUSDS wanted to check with you on the Rating Decision date (this would be an added date). Can we correlate the rating decision to the appeal stream at all? or will we always be showing the latest one? Also, what are your thoughts on 'Procedural History' vs. 'Relevant Documents' as a heading?

**Comment by lakohl** [comment]
@sharonwarner Could you put up a screenshot with 2 appeal streams so I can better see what you mean?
Also thinking the spacing between the lines could be a bit tighter.

**Comment by sharonwarner** [comment]
Also, we don't currently pull rating decision into our system. I'm going to make that into a separate ticket.

**Comment by sharonwarner** [comment]
<img width="998" alt="screen shot 2018-04-25 at 11 14 36 am" src="https://user-images.githubusercontent.com/4306128/39255166-e152a2a0-4879-11e8-94b3-a4746512e9f2.png">

Here's a screenshot with multiple appeal streams.

**Comment by lakohl** [comment]
Thanks @sharonwarner! I think this will work. 
I thought I'd updated the screenshot. My fault. Let's leave the rating decision out for now.

**Comment by sharonwarner** [comment]
No worries! Sure, I can do that.

**Comment by lakohl** [comment]
@annienguyenUSDS Here's one possible solution:
![docs in claims folder](https://user-images.githubusercontent.com/4975959/39270832-3287346c-48a5-11e8-9ad1-888dc9bdb76a.png)

**Comment by annienguyenUSDS** [comment]
To add border to accordion for "Procedural History"
http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#accordions
