### ISSUE TITLE
Hearing Prep | Update "Autosave" text size and spacing on the Daily Docket and Hearing Worksheet

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4606]
## AC 
**Make the following adjustments across Hearing Prep:**
1. Ensure that there is always 40px of space between the top bar with the Caseflow logo and the canvas box.

**Make the following adjustments on the Daily Docket and Hearing Worksheet:**
1. Display the autosave text in the space between the header bar and the canvas, and position it os that it sits 10px above the canvas.
1. Use the following styling to display the autosave text: 15px, bold, color: 5B616A

## Mock
![autosave](https://user-images.githubusercontent.com/4975959/36079051-e386b36a-0f4c-11e8-967b-b09da6549ad1.png)

**Comment by Sjones352** [comment]
@lakohl currently it looks like this 
<img width="1155" alt="screen shot 2018-03-21 at 12 14 01 pm" src="https://user-images.githubusercontent.com/23080951/37722327-21a2befa-2d02-11e8-831e-9e9d0dc3786f.png">

**Comment by Sjones352** [comment]
@lakohl is it `#5b616b` or `#5b616a`?

**Comment by Sjones352** [comment]
@lakohl also see the difference in this gif
![autosave](https://user-images.githubusercontent.com/23080951/37723659-48f52f4e-2d05-11e8-9dd2-0be218f5f791.gif)
