### ISSUE TITLE
Dispatch Header:  View veteran Name and ID

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#461]
As a Caseworker, I would like to see the Veteran's name and ID on all pages for the current Establish Claim task so that I am certain as to who I am working on.

### Acceptance Criteria
1. Verify that on all Dispatch pages, the veteran's name and id is displayed in the header.

### Mockup
![461 - dispatch page header](https://cloud.githubusercontent.com/assets/23063044/20495091/b297fd96-afed-11e6-8dd3-76c5790614b0.PNG)

**Comment by astewarttistatech** [comment]
Looks good. Please see attached. Moving to Done column. 

Tested in Chrome and Firefox. 
<img width="1092" alt="screen shot 2016-11-30 at 4 21 35 pm" src="https://cloud.githubusercontent.com/assets/23038505/20812803/fda5e424-b7e0-11e6-9472-0a68bad47def.png">
