### ISSUE TITLE
Caseflow incorrectly updating post-remand appeals in VACOLS

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4615]
From Chris Watts:

> Here’s the problem I’m seeing with the RAMP opt-in of remanded appeals in VACOLS:
> 
> Prior to Jan.1, if a remand was closed with a ‘P’ disposition code, the remanded record was duplicated (so that if you go into VACOLS, you see the first record with a ‘3’ remand disposition code, along with a duplicate record with a ‘P’ disposition code, and all other relevant information). This is ideal for tracking purposes, because you can see the record in VACOLS, and can obtain all the metrics that we track.
Example: XXX (the top two records are the RAMP record, and the Remand record that is put into HIS status)
> 
> After Jan.1, this changed. A skeleton record is created in the database with only an appeal ID (‘BFKEY’, in case you’re asked), decision date, and a ‘P’ disposition code. While we can query this record in the EDW to get a count of RAMP cases, it does not contain any other relevant information (like station, or NOD date) which makes meeting reporting requirements more difficult. You also can’t see the record in VACOLS, because it’s missing the file number (‘BFCORLID’ field).
Example: XXX Remand record was marked complete on 2/1, and there is a skeleton record with a ‘P’ code, but you can’t see it through the VACOLS interface)
> 
> I’m working on a solution to the reporting issue by pulling in the station/file number/NOD date from the closed remand record, but this is not ideal.

**Comment by cmgiven** [comment]
@abbyraskinUSDS has the file numbers if needed.

**Comment by shanear** [comment]
It looks like this might be causing the problem:
https://github.com/department-of-veterans-affairs/caseflow/pull/4282/files

**Comment by cmgiven** [comment]
Right. It's just for some reason the `clone_attributes` setup is not working:

https://github.com/department-of-veterans-affairs/caseflow/pull/4282/files#diff-e306b931976c85042b0d0e75acc300acR344
