### ISSUE TITLE
Create endpoint for an attorney to complete a case review task by creating an OMO request 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#4636]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4523

On POST to /queue/tasks/:vacols_id/complete with the following format, an OMO request should be created and the appeal should be reassigned to the reviewing judge.

```
{
  type: "OMORequest",
  document_id: "399329032.3290" (check the format)
  reviewing_judge_id: 12,
  overtime: true,
  note: "This is some freetext",
  work_product: "VHA", "IME", or "VHA and IME"
}
```

# AC
1. If reviewing_judge_id, document id, work_product, overtime, or type are missing, return a bad request error (400?)
2. If the appeal is not assigned to the user using `BFCURLOC`, return an error to the client if the appeal is not currently assigned to the user. We may want to display this in the UI.
    - **tentative: the appeal must also have a DECASS row associated with it assigned to the attorney where dereceive is null
4. Create a new OMORequest record 
5. Update the DECASS record to be reassigned to the judge
6. Update the location to the judge's location

4-6 should possibly happen with a transaction (Caseflow DB update) inside a transaction (VACOLS update), so there is no chance we wind up having one of the VACOLS update and Caseflow DB update fail, but not the other. (See http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)

**Comment by amprokop** [comment]
`3. A new user record should be created if a judge is not in Caseflow DB`

@aroltsch, what is this for again? sorry i don't remember
