### ISSUE TITLE
Issues API for attorneys

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4645]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4644

During the [checkout process](https://app.mural.ly/t/workqueue2001/m/workqueue2001/1516395984233/be6d5588c4d60f1e66d2daafaf74c02dd5202ee6), attorneys need to be able to add, edit, and delete issues on an appeal. Later on, we'll likely need to allow others to do the same. Let's build API routes to enable this.

### Add issue
`POST /appeals/:appeal_id/issues`
```
{
  program: required, any of the values in PROGRAMS in issues.rb
  issue: correponds to ISSREF.ISSCODE
  level_1: corresponds to ISSREF.LEV1_CODE
  level_2: corresponds to ISSREF.LEV2_CODE
  level_3: corresponds to ISSREF.LEV3_CODE
  note: optional
}
```
- Creates a row in the `ISSUES` table, and sets:
  - `ISSKEY` to `BRIEFF.BFKEY`
  - `ISSEQ` to the previous max `ISSEQ` plus 1
  - `ISSPROG` to the value for program (e.g. compensation) 
  - `ISSCODE`, `ISSLEV1`, `ISSLEV2`, `ISSLEV3` to the codes that correspond to values in `ISSREF`
  - `ISSADTIME` to the current datetime
  - `ISSADUSER` to the current user

### Edit issue
`PUT /appeals/:appeal_id/issues/:vacols_sequence_id`
- Only updates the params passed by the client
- Sets `ISSMDTIME` to the current time and `ISSMDUSER` to the current user

### Delete issue
`DELETE /appeals/:appeal_id/issues/:vacols_sequence_id`
- Removes the issue with the specified vacols_sequence_id

## AC
- The routes specified above should be created
- For now, the only users who can add, edit, or delete issues should be users with DECASS rows currently assigning appeals to them

## Open Questions
- When deleting an issue, do we have to update `vacols_sequence_id`s/`ISSEQ` of other issues?
- Do we have to update `ISSMDTIME` and `ISSMDUSER` when creating a new issue?
- When issues are deleted, should we save a record of the previous set of issues — just in case?
- Should our API use the Caseflow Appeal ID as path params, or the VACOLS ID?
- What's the best way to make this forwards compatible with AMA appeals?
- Currently, I don't see any reason we would have to read/edit `ISSEL`(Issue selected), `ISSGR`(Reason for RO Grant(CUE, De Novo, New Evidence)), `ISSDEV` (Issue Development Flag). Can we confirm this?
- Can we confirm with Jed that the VACOLS updates we specify above are correct?

**Comment by cmgiven** [comment]
I don't know the answer to question one; we should ask Jed.

On question three, I don't think it's worth spending too much time on this one. Since VACOLS issues can be updated willy-nilly, there's really not a lot to be gained if we start capturing that at this late stage of legacy appeals, and our snapshots would save us if we were to have some sort of bug.

**Comment by aroltsch** [comment]
Jed's response:
![image](https://user-images.githubusercontent.com/3811786/36558133-107e4250-17d8-11e8-95f4-171e1ec72316.png)
