### ISSUE TITLE
Attorneys can create draft decisions using /queue/tasks/:task_id/complete

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4646]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4644

On POST to /queue/tasks/:task_id/complete with the following format, a draft decision should be created and the appeal should be reassigned to the reviewing judge.

```
{
  type: "DraftDecision",
  document_id: "399329032.3290"
  reviewing_judge_id: 12,
  overtime: true,
  work_product: "Decision",
  note: "This is some freetext",
  issues: {
     vacols_sequence_id: 1,
     disposition: "Allowed",
  },{
   vacols_sequence_id: 2,
    disposition: "Remanded",
    remand_reasons: {
       ...
    } 
  }
}
```

### AC
- If reviewing_judge_id, document id, overtime, or type are missing, return a bad request error
- If the appeal is not assigned to the user using BFCURLOC, return an error to the client if the appeal is not currently assigned to the user. We may want to display this in the UI.
- If the dispositions passed don't match the issues on the appeal, return a bad request error
- Create a new DraftDecision record
- Update the DECASS record to be reassigned to the judge
- Update the location to the judge's location
- Update the work product — `DEC` if it's a decision, `OTD` if it's an overtime decision
- Update the issues on the appeal to have the indicated dispositions
  - `ISSUES.ISSDC` should be updated to the disposition code
  - `ISSUES.ISSDCLS` should be updated to the current date
  - `ISSUES.ISSMDTIME` should be updated to the current datetime (confirm with Jed in case this field isn't typically updated when only issue disposition changes)
  - `ISSUES.ISSMDUSER` should be updated to the current user (confirm with Jed in case this field isn't typically updated when only issue disposition changes, and check in the prod DB whether this is a CSS ID or a key to the STAFF table)
- We'll need to update remand reasons on the appeal as well, but since we don't deal with remand reasons much in Caseflow yet, that will be handled in a different ticket and possibly separate PR/s
   - This uses the RMDREA table. Will be speced out in https://github.com/department-of-veterans-affairs/caseflow/issues/4690
- The VACOLS DB update/Caseflow DB update should possibly happen with a transaction (Caseflow DB update) inside a transaction (VACOLS update), so there is no chance we wind up having one of the VACOLS update and Caseflow DB update fail, but not the other. (See http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)

## Open Questions
- Given the fact that we have a separate add/edit issues API, how do we ensure that nothing totally bizarre and terrible happens if the user has two browser windows open and adds an issue in one and completes the draft decision in another?

### dispositions to include - only the below:
    "1" => "Allowed",
    "3" => "Remanded",
    "4" => "Denied",
    "5" => "Vacated",
    "6" => "Dismissed, Other",
    "8" => "Dismissed, Death",
    "9" => "Withdrawn",

---
### disposition values from case.rb
```
  DISPOSITIONS = {
    "1" => "Allowed",
    "3" => "Remanded",
    "4" => "Denied",
    "5" => "Vacated",
    "6" => "Dismissed, Other",
    "8" => "Dismissed, Death",
    "9" => "Withdrawn",
    "A" => "Advance Allowed in Field",
    "B" => "Benefits Granted by AOJ",
    "D" => "Designation of Record",
    "E" => "Advance Withdrawn Death of Veteran",
    "F" => "Advance Withdrawn by Appellant/Rep",
    "G" => "Advance Failure to Respond",
    "L" => "Manlincon Remand",
    "M" => "Merged Appeal",
    "P" => "RAMP Opt-in",
    "Q" => "Recon Motion Withdrawn",
    "R" => "Reconsideration by Letter",
    "V" => "Motion to Vacate Withdrawn",
    "W" => "Withdrawn from Remand",
    "X" => "Remand Failure to Respond"
  }.freeze
```

**Comment by aroltsch** [comment]
From Jed,

```
Yes you should update ISSUES.ISSMDTIME and ISSUES.ISSMDUSER we also currently update ISSGR (grant reason) if ISSDC = ‘1’, there’s a pick list of grant reasons.  If ISSDC = ‘3’ then in VACOLS they are required to enter the remand reasons, that whole process is rather complicated, not sure if you plan to continue tracking remand reasons in CaseFlow.```
