### ISSUE TITLE
RAMP intake does not ensure appeal has only compensation issues

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#4659]
AMO is sending RAMP letters to Veterans with multiple appeals, some of which may have non-compensation issues and thus are ineligible for RAMP.

## Acceptance Criteria
- When intaking a RAMP election. For each appeal check if it has at least 1 non-compensation issue. if it does, it should be ineligible and not included in the list of closed appeals.
- If all appeals are ineligible, we should show the ineligible appeals error

## Technical Notes
[Appeal.eligible_for_ramp?](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/appeal.rb#L259) does not validate that the appeal does not contain non-compensation issues.

To do this, we should check to ensure that the `program` for all issues on appeal is `:compensation`.

**Comment by shanear** [comment]
I think the proper resolution to this issue is that we update the appeal closure script to only close compensation issues.

If the appeals only have non-comp issues they should be ineligible.

*sigh*

**Comment by shanear** [comment]
We've seen this happen in prod and were about to update the logic here. So closing
