### ISSUE TITLE
Unauthorized view shouldn't be certification specific

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#466]
Right now, if you go to a page you're unauthorized for in dispatch, you get a certification related message. Probably not high priority, but we should probably make the message more generic.

<img width="1554" alt="screen shot 2016-11-18 at 4 49 51 pm" src="https://cloud.githubusercontent.com/assets/1596259/20447881/302425a0-adaf-11e6-9514-c57e3c4a409b.png">

Error Message should match eFolder unauthorized notice.  Do not add FAQ links.  This will to be solidified at a later date.  

### Sub-Tasks
QA manual test

**Comment by shanear** [comment]
this is a duplicate @lakohl, do with it what you wish :robot:

**Comment by joofsh** [comment]
From Lara:

Make it similar to eFolder unauthorized. Except we can't have the 'Click Here' to find out how to get access (not yet). Instead we could say ... 'Speak to your manager or ISO about getting to permission to use Caseflow Dispatch.'

**Comment by astewarttistatech** [comment]
Current view. Please see attached. @mdbenjam Could you please revise?

<img width="824" alt="screen shot 2016-12-20 at 1 22 11 pm" src="https://cloud.githubusercontent.com/assets/23038505/21362691/83d39174-c6b7-11e6-85e3-c0d27b198901.png">

**Comment by lakohl** [comment]
From the Style Guide... Links are only underlined in their hover state.
<img width="250" alt="screen shot 2016-12-20 at 2 10 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/21364266/1d5cef56-c6be-11e6-9449-2ac728746253.png">

**Comment by mdbenjam** [comment]
@astewarttistatech The link at the bottom is only on visible in development environments, it won't be there in prod environments. What else is wrong with the page?

**Comment by shanear** [comment]
The link seems to be the only bad part of the page and is a development only link, so I'm ok with it not being perfect. The bigger issue here is that the title still says "Caseflow Certification" (see the tab in the screen shot).

<img width="1554" alt="screen shot 2017-01-04 at 4 37 12 pm" src="https://cloud.githubusercontent.com/assets/1596259/21660142/32538cdc-d29c-11e6-88c9-e7bbfaaadbac.png">

I don't think we had this as part of the AC, but do you mind fixing that @mdbenjam ?

**Comment by mdbenjam** [comment]
Yeah I can take care of that.

**Comment by mdbenjam** [comment]
Actually, this is a broader problem that we should address in a separate ticket. #651

**Comment by shanear** [comment]
Cool, let's close this one out then
