### ISSUE TITLE
Hearing Prep | Last saved not updating

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4660]
User is unable to see when the document saved last - Last Saved time is not auto updating.

## AC
1. Ensure that the Daily Docket and the Hearing Worksheet save continuously (every min?)
1. Update the time displayed in 'Last Saved at [hr:min]' in the top left current corner of the DD and the HW when the page is automatically saved.

![last saved](https://user-images.githubusercontent.com/4975959/36309543-11ed1614-12f3-11e8-9233-1271335630ae.png)

**Comment by sharonwarner** [comment]
Dup of #4663
