### ISSUE TITLE
Remove reminder to close pending EP (copy change)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4664]
Context: This step has been moved to further in the process, so it isn't something CAs should be doing.

## Acceptance Criteria
- On the confirmation page for a first-time RAMP Election Form, descriptive copy after the header should be updated to remove the second sentence. It should say, for a Veteran named Joe Snuffy with Vet ID 999999999: "Joe Snuffy's (ID #999999999) opt-in election has been processed."

**Comment by shanear** [comment]
![screen shot 2018-04-16 at 7 04 48 pm](https://user-images.githubusercontent.com/1596259/38839532-0c2d1794-41a9-11e8-8036-1b7fff38c633.png)
confirmed this is gone
