### ISSUE TITLE
Run more comprehensive 508 compliance tests

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#469]
Right now the only URL we check is `/caseflow/login`, this is because all other pages require a user to be logged in, which we don't have good support for in the testing environment. We should figure out how to do that well and then add more pages to the tests. This may require moving from running the `pa11y` CLI to the JS integration to properly instrument cookies or similar.

**Comment by ErieMeyer** [comment]
Hi all! I know folks at 18F and CFPB who are great at this and may be willing to take a quick look. LMK if I can be of assistance!

**Comment by alex** [comment]
We've already got basic tests running, there's a pure-engineering task now
to just expand this out.

On Wed, Jan 6, 2016 at 10:29 AM, Erie Meyer <notifications@github.com>
wrote:

> Hi all! I know folks at 18F and CFPB who are great at this and may be
> willing to take a quick look. LMK if I can be of assistance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/469#issuecomment-169357450>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
