### ISSUE TITLE
Update remand reasons on issues if an appeal is remanded

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4690]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4644, mocks found in https://github.com/department-of-veterans-affairs/caseflow/issues/4484

# AC

- When setting an issue's disposition to "Remand", we need to create a new row in RMDREA with the following attributes:
  - RMDKEY as vacols id / BRIEFF.BFKEY
  - RMDISSSEQ as VACOLS issue sequence ID
  - RMDVAL as the value of the remand reason
  - RMDMDUSR as the user creating the draft decision
  - RMDMDTIM to the current date and time
  - Set RMDDEV to `R1` if the issue is being remanded due to something that happened before certification (at the RO), and `R2` if the issue is being remanded due to something that happened at BVA (post-certification)
- Validate that values for RMDDEV and RMDVAL are present for each remanded issue

## Open Questions
- Confirm requirements with Jed
- Ask Jed if he has a mapping of RMDVAL codes to English
- Confirm that we should set RMDMDUSR and RMDMDTIM (this might just be on modifying remand reasons, not when creating them)
- Do we need to set RMDPRIORITY?

**Comment by aroltsch** [comment]
Response from Jed:

![image](https://user-images.githubusercontent.com/3811786/37525465-4f53acf4-2903-11e8-9125-9812580e4d23.png)

**Comment by aroltsch** [comment]
[rr.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/1819487/rr.xlsx)
