### ISSUE TITLE
SPIKE: Investigate way for caseflow to send email to employees

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#470]
Caseflow needs to send email to RO. The result is either a gem or a micro-service that sends email with a simple interface. This issue tracks the design and implementation details on how we solve the problem.

Below is the technical info copied from https://github.com/department-of-veterans-affairs/appeals-pm/issues/905. It will provide a good starting point.

### Setup: msmtp 1.6.5

```
# .msmtprc at home directory
account        va
host           smtp.va.gov
port           25
from           caseflow@va.gov
```

### Sample test-mail.txt
```
From: caseflow@va.gov
To: chun.ning@va.gov, Kavi.Harshawat@va.gov
Subject: Caseflow Email Test

Hi, you just got spammed.

This is a test email sent from smtp.va.gov. Please ignore it.
```

### Command to send mail
```
cat test-mail.txt | msmtp -a va chun.ning@va.gov, Kavi.Harshawat@va.gov
```

@shanear

**Comment by shanear** [comment]
@askldjd in the interest of keeping things simple, lets make this a service in caseflow commons? That way we don't need another repo to keep track of.

**Comment by askldjd** [comment]
Closing since we no longer have a need for this. If we need it, smtp.va.gov will be there for us. This is pretty much a solved problem.
