### ISSUE TITLE
Point users to the DSVA Caseflow Statuspage

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#4700]
We now have https://dsva.statuspage.io/ that we should be updating whenever there is an issue or outage.  

Our users should now know about this. 

We should:

- [ ]  Add a link to our status page on our out-of-service pages. 
- [ ] Add a link to our status page on our support views
- [ ] Add a link to the Caseflow footer

**Comment by Sjones352** [comment]
@lakohl @sharonwarner @annienguyenUSDS and @gnakm 

This is what the out-of-services page looks like eFolder that I worked on.  Check out eFolder ticket
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/426

<img width="825" alt="screen shot 2018-01-02 at 7 33 49 pm" src="https://user-images.githubusercontent.com/23080951/34505596-e90264ec-eff3-11e7-8328-53ab300afbbf.png">

So if I add the the Status page to our Caseflow app. This is how it would look like. Please advise 
<img width="1054" alt="screen shot 2018-03-02 at 12 18 48 pm" src="https://user-images.githubusercontent.com/23080951/36912473-c67882b8-1e14-11e8-8f40-2d8d445cbe17.png">

**Comment by gnakm** [comment]
Technical Difficulties 

Caseflow is experiencing technical difficulties right now. You can track updates on our [Caseflow Status Page](https://dsva.statuspage.io/).

**Comment by Sjones352** [comment]
@gnakm do we need to this link to our footer and if so where

**Comment by gnakm** [comment]
![image](https://user-images.githubusercontent.com/13420618/36916459-f4cbae6c-1e21-11e8-8503-78bcb2659273.png)

**Comment by Sjones352** [comment]
<img width="1217" alt="screen shot 2018-03-02 at 4 05 01 pm" src="https://user-images.githubusercontent.com/23080951/36921844-d83221c0-1e33-11e8-9c09-5d0734c40191.png">

**Comment by lakohl** [comment]
@Sjones352 can 'You can track updates...' start on the third line?

**Comment by Sjones352** [comment]
<img width="1269" alt="screen shot 2018-03-02 at 4 43 18 pm" src="https://user-images.githubusercontent.com/23080951/36924382-5cc207cc-1e3c-11e8-9dc9-d22d29a5e2e2.png">

**Comment by lakohl** [comment]
So much better @Sjones352 ! @gnakm wondering if per our styleguide conventions 'page' should be lower case?

**Comment by gnakm** [comment]
@Sjones352 could we make p in page lowercase?

**Comment by sunil-sadasivan** [comment]
@gnakm @lakohl would love your intuition on the copy for the status page as well!

<img width="921" alt="screenshot 2018-03-05 10 12 31" src="https://user-images.githubusercontent.com/31223104/36982380-c424cfee-205d-11e8-853b-36c1221c0faa.png">

https://dsva.statuspage.io/

**Comment by gnakm** [comment]
@sunil-sadasivan 

- [ ] P in page should be lower case
- [ ] Could we change the `About This Site` to `Welcome to Caseflow Status page` (and delete the one below it). 
- [ ] The light gray on this page is so faint that it's conflicting with the acidic green. Could we make all the light grays #5b616b / $color-gray

**Comment by sunil-sadasivan** [comment]
@gnakm, I was able to tackle 1 and 3.  Hmm... It looks like `About This Site` isn't configurable from what I can tell 😞

**Comment by gnakm** [comment]
@sunil-sadasivan That's fine. None of these are really non-negotiables :)

**Comment by Sjones352** [comment]
<img width="1080" alt="screen shot 2018-03-07 at 12 19 18 pm" src="https://user-images.githubusercontent.com/23080951/37107232-cf9be650-2201-11e8-9b4d-8a1005d3befa.png">
