### ISSUE TITLE
EP Creation | Create End Product | Update Integration Error Message

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#471]
As a Product Owner, I would like to have an updated error message displayed when there is an integration error while trying to create an End Product on the `EP Creation` page so that it is more meaningful and complies with consistent styling.

## Acceptance Criteria
1. Verify that after clicking on the **_Create End Product_** button and there is any integration error, the following error message is displayed: 
    **_Title:_**  
    > System Error

    **_Message:_**  
    > Something went wrong with on our end. We were not able to create an End Product. Please try again later.

## Mockup
**_View - EP Creation page - with Current error message_**
<img width="1554" alt="screen shot 2017-02-06 at 2 55 33 pm" src="https://cloud.githubusercontent.com/assets/1596259/22710366/06091b82-ed4b-11e6-97de-2c802af592a0.png">

# Related Stories
n/a

**Comment by KHarshawat** [comment]
@nikitarockz The design of this page largely depends on whether we know the cause of the error. For example, if we know that the issue is integration with VBMS we can show a message saying as much.

**Comment by KHarshawat** [comment]
As a rough first pass here is a mock

![vbms integration error](https://cloud.githubusercontent.com/assets/6335546/20767748/7f4ef8c2-b709-11e6-945c-ce0a70f752de.png)

**Comment by nikitarockz** [comment]
That is a good mock.  This story was a result of our last Story Time.  It was decided this needed to be separate from the main story.  We need to discuss ideas of where this is going to go.  

@shanear I know you have some ideas on this.  What do you think about the direction of where this is going?

**Comment by shanear** [comment]
@KHarshawat @nikitarockz This error makes more sense on the form page, so they can resubmit the form. 

However the general error page will also be useful because when we load the end product creation form, we will be querying BGS for claims. If that call fails, we should have some way of dealing with that error.

It might be helpful to have a discussion about error handling.

**Comment by lakohl** [comment]
@shanear Is this the same as #635?

**Comment by shanear** [comment]
@lakohl nope. 404 is "Not Found", which basically means the URL you tried doesn't work and was never intended to work.

This story is basically for the 500 page, which is "System Error", which means that the URL you entered should have worked and something went wrong on our end.

**Comment by lakohl** [comment]
@shanear thanks for the clarification!

**Comment by shanear** [comment]
<img width="1554" alt="screen shot 2017-01-19 at 5 07 33 pm" src="https://cloud.githubusercontent.com/assets/1596259/22129196/82b81c2e-de72-11e6-8c55-bd27cf0210ad.png">

The way it currently looks is fine right now

**Comment by shanear** [comment]
@lakohl to update copy

**Comment by mmlumba** [comment]
@nikitarockz @lakohl @KHarshawat The current message at the top of the issue reads:

> Something went wrong **with on** our end.

Is it supposed to be "Something went wrong **on** our end." ?

**Comment by lakohl** [comment]
@mmlumba yes! please make the adjustment. thanks.

**Comment by kierachell** [comment]
**PASSED**
validated on `uat`
<img width="1041" alt="screen shot 2017-03-06 at 2 48 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/23626951/bc4c92f2-027c-11e7-901f-8c18dd287502.png">
