### ISSUE TITLE
Judges queue | Review X cases (cases to sign)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4713]
As a Judge, I want a simple table where I can clearly see all the important information needed to review and sign a case so that I do not have to switch between multiple tables in DAS. 

### Acceptance Criteria
- [ ] Verify the title of the page is 'Review X cases'
  - X = the number of appeals assigned to the judge for signing (see notes below for logic)
- [ ] Verify we have populated all appeals assigned to judges by attorneys, chief judges, and/or senior counsel for signing correctly into the their table
-  [ ] Verify the table includes the following data points:
    - [ ] Case details = Veteran name (Veteran ID/VBMS ID/SSN) (note: this is the same as attorney queue)
    - [ ] Document ID = Document ID from [user who assigned]
    - [ ] Type = Vacols action list and AOD diary (if applicable) (note: this is the same as attorney queue)
    - [ ] Docket = docket number (note: this is the same as attorney queue)
    - [ ] Issues = number of issues (note: this is the same as attorney queue)
    - [ ] Days Waiting = number of days the case has been with the judge

Note: We will not have the 'Actions' dropdown with this ticket.

### Mocks
![queue - review cases](https://user-images.githubusercontent.com/23316107/37779682-5a09d8b6-2dc3-11e8-86d8-a32553a0dd3a.png)

### Notes
Judges complete a two distinct decision-related tasks: signing decisions/work products drafted by their attorneys and assigning cases to attorneys to draft decisions.

When judges prepare to **sign decisions**, they want to access all appeals assigned to them in one place, distinct from where they access appeals to assign to their attorneys, so they can focus on one type of task at a time. They need to see this alongside information that helps them get context on the case (e.g. number of issues and docket number), so they can prioritize what to work on.

Attorneys assign finished draft decisions back to their judges. Chief judges and senior counsel sometimes "case manage" judges workloads, so these finished draft decisions could also be assigned to judges by those users.
- The VLJ Master List in DAS separates out cases for judges to sign and cases to assign to attorneys. Reader's welcome gate doesn't currently separate this out. We can likely mimic DAS for this.
- From Jed:
     > How do you distinguish 'Unassigned' and 'Assigned' today? Is it based on prior locations, or some other logic?

     >It looks at the DECASS.DEASSIGN date, if it’s null then the case is unassigned otherwise if it’s not null it’s been assigned.
     > DECASS.DEASSIGN gets updated when the VLJ initially assigns the case to the attorney.

**Comment by evankroske** [comment]
I still need to add the name of the assigner to the document ID column
