### ISSUE TITLE
Judges | Assign cases | Select and assign multiple cases to an attorney

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4716]
Judges will have ~20-30 cases in their 'Unassigned' queue, and can assign any number of them to attorneys on their team. Judges can select different attorneys per case, and those cases will be assigned when the judge clicks the 'Assign' button.

When judges are assigning cases to their attorneys, they need to choose which attorney on their team they should assign the case to, so that attorney can draft an appeals decision.

### Acceptance Criteria
- Verify that a column 'Assign to' exists in the 'Assign Y Cases' table
- Verify that a dropdown exists for each unassigned case in the 'Assign to' column
- Verify that the dropdown only contains attorneys that are on their team, plus an 'Other' option
-  Verify that an 'Assign' button exists on the top and bottom of the judges Assign tables, per mocks
- Verify these buttons are present no matter what table the judge is looking at (i.e. Unassigned cases or one of their attorney's queues)

### Mocks

https://app.mural.co/t/workqueue2001/m/workqueue2001/1524171664613/04929efd3dea35587ae9168016d56fa5e5870613

https://va-gov.invisionapp.com/d/main/#/console/13735727/286320006/preview

**Comment by evankroske** [comment]
## Estimates
- [ ] Add button to judge assign view to assign to attorneys on the judge's team: 6 hours.
- [ ] Extend assignment widget to support assigning to anybody: 8 hours.

**Comment by evankroske** [comment]
I think that this issue was resolved by https://github.com/department-of-veterans-affairs/caseflow/pull/6017 , but I could be wrong. Feel free to reopen this issue if you don't think it's done.
