### ISSUE TITLE
End Product:  Back Preview:  Save any entered information

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#472]
As a Caseworker, I would any information I entered on the End Product page to be saved when I go back to review the Decision Preview page so that I do not have to re-type the information upon return to the End Product page.

### Acceptance Criteria
1. Verify that when the “Back to preview” link is clicked; any information entered for End Product page is saved.  

### Mockup
*End Product page*
![image](https://cloud.githubusercontent.com/assets/23063044/20778209/3c4efc44-b73a-11e6-95f9-db5c128a7ac3.png)

### Sub-Tasks
Change page to be in React and unify them.
QA Manual test

**Comment by KHarshawat** [comment]
@nikitarockz I don't believe this needs to be defined any further. Should we remove this label and move to triage?

**Comment by joofsh** [comment]
@shanear Did you have a preference on how this ticket is accomplished?

Do we care if the data is lost on page reload? If not, we can accomplish this by saving the form information in browser memory (via React). Otherwise we'll have to start persisting the EP form to the database. 

CC @KHarshawat @nikitarockz

**Comment by shanear** [comment]
@joofsh we're on the same page here. I was thinking the same thing.

**Comment by KHarshawat** [comment]
@joofsh We also have a "Hold" functionality that's in another issue. We were thinking that "Holding" a claim would also save the data in the form so when the user goes back they woudln't have to re-enter it. I understand this could actually be a much bigger lift b/c it'd require storing EP form in the DB. If this is too much work then I'm happy to just indicate to the user that when they Hold a claim any information they've entered will be lost.

**Comment by joofsh** [comment]
@KHarshawat It's definitely a bigger lift to persist the EP form to the DB. Given how short the form is & the unknown future of EPs, I don't believe it's worth the level of effort. I would recommend we have them refill the form if they return to an appeal on Hold.

**Comment by KHarshawat** [comment]
Sounds good! I'll update the #518 to reflect we won't be saving the form.

**Comment by astewarttistatech** [comment]
**PASSED**

When changing the information on the Create End Product form, hitting the Back to Preview button, and returning back to the Create End Product form, nothing on the page changes. 

![Uploading Screen Shot 2016-12-14 at 1.18.42 PM.png…]()
