### ISSUE TITLE
End Product:  Increment Modifier value by 1 for multiple EP codes

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#475]
As a Caseworker, I would like the Modifier value to automatically be incremented by 1 whenever there is more than one EP code associated to the appeal so that it is clear that there is more than one of the EP code..

### Acceptance Criteria
1. Verify that the “Modifier” value increments by one (1) if there is more than one matching “EP & Claim Label” value.

### Notes
Retrieve previous end products that exist.

**Comment by nikitarockz** [comment]
@abbyraskin  I know where trying to find out how this would work.  I was wondering if you got any additional information I can use to clarify this story.

**Comment by abbyraskin** [comment]
see notes here: https://github.com/department-of-veterans-affairs/appeals-pm/issues/1004#issuecomment-262067007

in general, i would recommend showing the modifier (as an editable dropdown) only if there are actually multiples of the same EP code. for instance, if there's already a 170, the modifier will increment to 1. if there is not a second EP, hide this field. today, VBMS automatically detects if there's an EP and increments accordingly, so we should treat it the same way on the backend, but hide the field if it isn't relevant to the user.

**Comment by KHarshawat** [comment]
@abbyraskin Looking at this screens specifically while trying to figure out the UI: https://marvelapp.com/1fbbefd/screen/16597631

![image](https://cloud.githubusercontent.com/assets/6335546/20764818/e34b7c44-b6fd-11e6-8752-659798031441.png)

Some questions:
- If I'm understanding you correctly, we should only show this when we've detected a previous EP on the backend... is that correct?
- Should the modifier field be required if it's shown?
- What values should be shown in the modifier field?

**Comment by nikitarockz** [comment]
1.  So, are you saying that if the case already has a modifier of 170, then the page will display 171 as the default modifier value and because this is a list the the drop down will show (170,171)?

2. When you say the drop down should be editable, do you mean that the user has the ability to to pick existing options of 170 and 171.  Or, are you saying the user can add a totally different value, in essence adding a new value to the list of value (170, 171, 354)?

On Nov 30, 2016 10:54 AM, abbyraskin <notifications@github.com> wrote:

see notes here: department-of-veterans-affairs/appeals-pm#1004 (comment)<https://github.com/department-of-veterans-affairs/appeals-pm/issues/1004#issuecomment-262067007>

in general, i would recommend showing the modifier (as an editable dropdown) only if there are actually multiples of the same EP code. for instance, if there's already a 170, the modifier will increment to 1. if there is not a second EP, hide this field. today, VBMS automatically detects if there's an EP and increments accordingly, so we should treat it the same way on the backend, but hide the field if it isn't relevant to the user.

-

**Comment by abbyraskin** [comment]
> If I'm understanding you correctly, we should only show this when we've detected a previous EP on the backend... is that correct? 

- Correct. If there's an identical EP code (just the code needs to be the same, not necessarily the label after the code) we should display this dropdown. Today, VBMS knows if there's already an EP and increments accordingly, but it also shows what is essentially duplicate info if there isn't a previous EP.
- Note: I'm not seeing any available modifiers for 172 in VBMS in UAT. Might want @shanear to confirm what is provided by API. I think this suggests you can only have one pending 172, so the modifier field would never show for full grants.

> Should the modifier field be required if it's shown?
Yes. Sometimes there are multiple EPs of the same type pending and this helps with tracking.

> What values should be shown in the modifier field?
For 170s:
171
175
176
178
179

**Comment by abbyraskin** [comment]
> 1.  So, are you saying that if the case already has a modifier of 170, then the page will display 171 as the default modifier value and because this is a list the the drop down will show (170,171)?

Sorry for the lack of clarity. If the veteran's VBMS profile already has a 170 EP associated with it, the page will display the modifier 171. 

@KHarshawat as I think through this more, I'm not sure if it makes sense to let them change the modifier. I'd still display it when relevant (and hide when not) but make it display text (incrementing last EP by one), rather than a dropdown.

> 2. When you say the drop down should be editable, do you mean that the user has the ability to to pick existing options of 170 and 171.  Or, are you saying the user can add a totally different value, in essence adding a new value to the list of value (170, 171, 354)?

See above. I would choose the modifier for them and would not make it a dropdown (nor editable in any way).

**Comment by shanear** [comment]
Covered with existing issues. closing
