### ISSUE TITLE
Judges queue | Assign x cases | Attorney side bar

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4763]
When a judge is assigning cases to their attorneys, they want to see a list of their attorneys they can assign to at the same time as they look at their cases to assign, so they can assign cases as easily and quickly as possible.

### Acceptance Criteria
- [ ] Verify there is a sidebar on the left that contains entries for the judges unassigned cases, plus the list of attorneys associated with the judge below

**Out of scope for this ticket:**
- Populating each attorney table with cases assigned to those attorneys - https://github.com/department-of-veterans-affairs/caseflow/issues/4890

### Mocks
![queue - assign cases](https://user-images.githubusercontent.com/23316107/37781950-2438f5f0-2dc8-11e8-8196-f841e2dc5e48.png)

### Related
- Assign x cases - https://github.com/department-of-veterans-affairs/caseflow/issues/4714
- Count of cases per attorney - https://github.com/department-of-veterans-affairs/caseflow/issues/4715
- Populate attorney queue data - https://github.com/department-of-veterans-affairs/caseflow/issues/4890

### Notes
- There is a table that associates each attorney with their VLJ in VACOLS

**Comment by evankroske** [comment]
@sneha-pai, could you point me to a precedent in the USWDS for this sidebar design? USWDS sidebars look really different from the mock: https://designsystem.digital.gov/components/sidenav/

**Comment by evankroske** [comment]
Estimated time to complete: 4 days total

**Comment by evankroske** [comment]
Moved a few acceptance criteria to https://github.com/department-of-veterans-affairs/caseflow/issues/4890
