### ISSUE TITLE
Hearing Worksheet | Printing title repeats in format

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4769]
**A/C:** 
When user is on a Hearing Worksheet, and clicks on "Save as PDF", the issue titles (issue, notes, disposition, preliminary impressions) repeat at the bottom of the page and the next page, which should not repeat and where the page breaks.

<img width="448" alt="screen shot 2018-03-05 at 12 42 26 pm" src="https://user-images.githubusercontent.com/22620270/36996486-f83753f2-2084-11e8-907b-055584f4a022.png">

**Desired:** 
Should always show the issue titles with an issue row. If cannot because of page break, move the issue and titles to second page, and do not repeat titles (issue, notes, disposition, preliminary impressions) on first page.

**Comment by lakohl** [comment]
@Sjones352 I'm currently getting inconsistent results when I download the .pdf. On my first try there were no labels: 
[J. King's Hearing Worksheet.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842032/J.King.s.Hearing.Worksheet.pdf)

on the second attempt the appeal stream titles behaved as expected, but there is a lot of white space underneath some of the issues:
[T. Washington's Hearing Worksheet.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842026/T.Washington.s.Hearing.Worksheet.pdf)

**Comment by Sjones352** [comment]
my local 
[B. Washington's Hearing Worksheet.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842204/B.Washington.s.Hearing.Worksheet.pdf)

**Comment by Sjones352** [comment]
@lakohl this is what I see in demo 
[J. Jefferson's Hearing Worksheet.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842165/J.Jefferson.s.Hearing.Worksheet.pdf)

**Comment by Sjones352** [comment]
@lakohl made a gif and this is what looks like in demo on VA laptop
![print](https://user-images.githubusercontent.com/23080951/37840272-fe18c65e-2e92-11e8-9dd7-142e9e9c5de4.gif)


[T.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842445/T.pdf)

**Comment by lakohl** [comment]
@Sjones352 from what I can tell, once the Veteran has a 3rd issues the issue row shows with extra space. 
See: 
[T. Washington's Hearing Worksheet.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842540/T.Washington.s.Hearing.Worksheet.pdf)
[J. King's Hearing Worksheet2.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1842542/J.King.s.Hearing.Worksheet2.pdf)

In your example (with 2 issues) 
1. There appears to be a lot of room below the label 'Periods and Circumstances of Service' 
1. There doesn't seem to be enough space allotted under 'Contentions' or under 'Evidence'
1. It seems as though Periods and Contentions of Service and everything below it could fit on the first page. In that case, I wonder why are we running it onto the second page?

**Comment by Sjones352** [comment]
![Screen Shot 2018-03-26 at 11.39.25 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58209eeb97c65e0e00e4cfa6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f56b7191a379ee0c2858415d4bbc30254d58eeb9cb74fce36f34985619e8d96f0e76903818aeb18249bb01eb278b4fd7b4b98a4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e34d52ac143f67e273366e0a.png)

**Comment by lakohl** [comment]
Issue spacing looks much more consistent! @Sjones352

**Comment by Sjones352** [comment]
@lakohl and @annienguyenUSDS this is what it looks likes. (issue, notes, disposition, preliminary impressions) doesn't repeat at the bottom the next page.

<img width="1007" alt="screen shot 2018-03-30 at 9 59 55 am" src="https://user-images.githubusercontent.com/23080951/38140381-775a7f94-3401-11e8-8802-4c4cfa99259c.png">
