### ISSUE TITLE
Cancel link does not appear for a DRO

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#477]
DRO from Waco informed us that he sees a message for cancelling out of Caseflow, but does not see the link to do so. We need to investigate the cause of this, and the issue.

Screenshot attached:

![screen shot 2016-11-21 at 12 48 24 pm](https://cloud.githubusercontent.com/assets/1178390/20493977/e85d6218-afe8-11e6-8abe-e012954ecc02.png)

**Comment by aroltsch** [comment]
Cancel link should be at the left bottom, same as other pages

**Comment by kierachell** [comment]
The only endpoint I see this implemented on is the appeals with mismatched documents.
<img width="984" alt="screen shot 2017-01-05 at 14 57 18" src="https://cloud.githubusercontent.com/assets/18075411/21695375/89c02a32-d357-11e6-9451-7746f9862ed7.png">
So this works according to specifications.

Are there other pages that need the cancellation link? @shellicious 

<img width="942" alt="screen shot 2017-01-05 at 14 59 58" src="https://cloud.githubusercontent.com/assets/18075411/21695399/a730e926-d357-11e6-8e99-326a38922cb8.png">

**Comment by kierachell** [comment]
Works per original specifications;
