### ISSUE TITLE
[Backend] Upcoming Hearings | RO sharing dockets

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4772]
If ROs are sharing dockets, how do they current indicate this in VACOLS? 
We saw from interview, that RO noted "SHARED DOCKET" in DD Notes to let the VLJ know.

In VACOLS, VLJ listed twice for same day, but different location 4 out of 4 scheduled.

Anne Jaeger - 4/4, Philly

**Comment by annienguyenUSDS** [comment]
@sharonwarner, to check how VACOLS shows shared dockets and slots are added/filled.
Options: 1) to show two RO locations on DD or 2) create separate dockets for each location.

**Comment by sharonwarner** [comment]
Answer from Jed:
There are two master records, one for each RO.  Right now there is no logic in VACOLS to restrict the slots for shared dockets, they can still schedule up to 9 or 11 depending on the RO's timezone.  It’s up to the hearing coordinators to realize it’s a shared room and only schedule 4 or 5 for each half of the day.

**Comment by lakohl** [comment]
@sharonwarner can we detect and therefore message to the judge if there are 2 master record for the same day.
