### ISSUE TITLE
Hearing Worksheet | Preliminary Issues checkmarks don't save in Save as PDF view

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4786]
Talked to a Judge and when they see a preview or print as "Save as pdf", preliminary impressions do not save.

**Comment by lakohl** [comment]
Checkboxes are saving. Yay! But can we ps show unchecked boxes as white instead of grey?

**Comment by sharonwarner** [comment]
That's the default color for a disabled checkbox. If we re-enabled them, they would be white.
