### ISSUE TITLE
Moving between documents is slow

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4791]
We want to make switching between documents as smooth as possible. In order to do this we pre-load the documents before and after the current one. This way, when a user switches between documents the previous and next one should already be ready to show.

However, I've noticed that when we switch between documents, they don't seem to be pre-loaded. The render time feels like it lags. I believe it's because of the last condition in the `if` statement on this line: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/reader/PdfFile.jsx#L436. We check to see if the PDF is visible. Why do we do this? I think this condition is no longer needed and should be removed. However, we need to make sure that there are no adverse consequences of it. Does removing this condition actually render these other PDFs on screen? Does it interfere with comments at all?

This is a good ticket to get more familiar with how we're doing our windowing using react-virtualized, and how the PDF rendering actually works.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
