### ISSUE TITLE
Intake | Allow partial closure of Appeals when there is a mix of rating and non-rating issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4793]
RAMP only applies to rating issues. Currently we aren't allowing any appeals that have just one non-rating issue to be eligible for RAMP. We should instead just close the rating issues for appeals that have a mix of rating and non-rating issues.

## Acceptance Criteria
- If an appeal has a mix of rating and non-rating issues, it should be considered eligible for RAMP.
- For these appeals, instead of closing them, only close the rating issues on the appeal and keep the appeal and the non-rating issues open.
- Appeals with 100% rating issues should close as they always have.
- Appeals with 100% non-rating issues should still be considered ineligible.
- On the confirmation page, only display the rating issues that will be closed out.

## Notes
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4659

**Comment by abbyraskinUSDS** [comment]
@shanear can you investigate whether this has happened?

**Comment by shanear** [comment]
There are 71 instances of this occurring in prod to date:

```
irb(main):021:0> RampElectionIntake.where(error_code: "no_active_fully_compensation_appeals").count
[2018-06-19 10:57:50 -0400]    (27.1ms)  SELECT COUNT(*) FROM "intakes" WHERE "intakes"."type" IN ('RampElectionIntake') AND "intakes"."error_code" = $1  [["error_code", "no_active_fully_compensation_appeals"]]
=> 71
```

I'm thinking we may need to handle this 🤔

**Comment by cmgiven** [comment]
I take this to mean that we want to close out compensation issues, but not others. In this case, we leave the appeal alone, and only create a closed disposition on compensation issues (those `where ISSPROG = '02'`).

I'd suggest creating a 'close' method on 'Issue', and then calling it for each of the `LegacyAppeal.compensation_issues`.

As we do in `AppealRepository.close_undecided_appeal!`, we then need to update the ISSDC and the ISSDCLS.

```
        issdc: disposition_code,
        issdcls: VacolsHelper.local_time_with_utc_timezone
```

**Comment by shanear** [comment]
I've validated that this is happening in prod.
