### ISSUE TITLE
Hearing Worksheet | After Hearing is Held, do not make changes to issues

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4797]
As a Judge, I expect the hearing worksheet information and my notes to look the way they did on the hearing day when I revisit them to assign my cases to attorneys. 

@sharonwarner to look into VACOLS/talk to Jed. Possible solution is to figure out convert HW to PDF view?  before we work on it in the following sprint.

**Comment by lakohl** [comment]
I believe this is being covered by: https://github.com/department-of-veterans-affairs/caseflow/issues/4902
