### ISSUE TITLE
Limit options available to different user groups (VBA vs. Board review lanes)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4798]
Currently, VBA and Board users see the same options in the app, which is misleading because VBA users can process HLRs and SCs, and Board employees can only process appeals. To prevent errors and streamline this process, we should hide any options that aren't actually relevant to the particular group.

## AC
- Board users (station 101): Always a RAMP Selection - taken directly to search after logging in
- Board users (station 101): Hide the "Which review lane did the Veteran select?" question and always select "Appeal" automatically
- Board users (station 101): Users start at Search (there is only one form available); 
- VBA users: Hide appeal option for RAMP Selections

**Comment by abbyraskinUSDS** [comment]
@shanear can you take a look at this^

**Comment by shanear** [comment]
I have some concerns. (ie. what happens if a RAMP selection marked as appeal lands in VBA's plate?)

**Comment by abbyraskinUSDS** [comment]
I'm not sure what you mean - that could be true no matter what, how would they know if it's suppose to be something that it isn't?

**Comment by abbyraskinUSDS** [comment]
And I don't think VBA or the Board has any flexibility as far as who processes which type

**Comment by abbyraskinUSDS** [comment]
I'm concerned the bigger risk is opening the door for users to select the wrong form, and adding unnecessary friction.
