### ISSUE TITLE
Hearing Worksheet | Maintain Format Changes

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4800]
When a judge preps or takes notes in Hearing Worksheet, I want to make sure my formatting in all notes field stay the same when I come back as well as print view. 

Currently, on the Hearing Worksheet to the Browser View changes the format. The format changes to run-on sentences.
<img width="970" alt="screen shot 2018-03-09 at 12 17 25 pm" src="https://user-images.githubusercontent.com/22620270/37220260-14485b42-2394-11e8-9696-1b6942a466cf.png">

<img width="1141" alt="screen shot 2018-03-09 at 12 12 45 pm" src="https://user-images.githubusercontent.com/22620270/37220275-2381a866-2394-11e8-9a2d-e05502b0bd2a.png">

**Comment by lakohl** [comment]
This is now working in the application and in the .pdf, but in the .pdf preview window it still shows the text as one big run-on sentences
