### ISSUE TITLE
Your Hearing Day | should be lowercase "am" "pm"

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4807]
Currently show "Am" and "Pm" on Your Hearing Day: 
<img width="1016" alt="screen shot 2018-03-09 at 10 33 25 am" src="https://user-images.githubusercontent.com/22620270/37215262-72e5603c-2385-11e8-80ba-cea1191a8d2c.png">

**Comment by lakohl** [comment]
Looks good!
