### ISSUE TITLE
Your Hearing Day | Fix hearings in past tab should be in order

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4808]
As a judge, I want to see my past hearings starting with most recent on top and in order by date. 

AC:
- See most recent past hearing on top
- Order by date 

Right now see the hearings not by date:
![Screen Shot 2018-03-09 at 10.37.00 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59763931322ccf001a1cd54f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a379ef0c2856415f4ebc30254d58eeb9cb74fce36f34985619e8d96f0e76903818aeb18249bb01eb278b4fd7b4b98a4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e14b55ad1a3161e67f306e0a.png)

**Comment by lakohl** [comment]
Looks good!
