### ISSUE TITLE
[Frontend] Hearing Worksheet | Checkboxes should be disabled in PDF

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#4815]
The checkboxes in the PDF view of the Hearing Worksheet should be read-only.

**Comment by lakohl** [comment]
@sharonwarner now that the .pdf view page closes as soon as the Print window is closed, there doesn't actually seem to be a way to get to a .pdf view where the user could check any boxes. Given that this is the case, I'm wondering if unchecked boxes need to display as greyed out, that seems a bit confusing to me.
