### ISSUE TITLE
All users with manager role can process Intake forms

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4817]
Some ARC managers need the ability to create EPs in Caseflow too - we should make the manager role inclusive of the mail intake role, so all managers have this ability moving forward.

## Acceptance Criteria
- Managers can access all Intake functionality, not just the stats page. Users with the "Admin Intake" role (stats page) enabled also have access to "Mail Intake" functionality (main Intake workflow)
- Add "Admin Intake" to the demo roles

**Comment by shanear** [comment]
@abbyraskinUSDS can we validate this in prod?
