### ISSUE TITLE
Bug: Certification Date not being updated correctly

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#482]
Certification date, which fills in 17C on the Form 8, is only being updated when the form 8 is first started. If a day passes, it won't update to that day, because `update_from_appeal` is never triggered.

Also we are experiencing an issue in prod where the certification date is just missing. This should never happen.

**Comment by orischwartz** [comment]
Missing certification date may be caused by #464

**Comment by amprokop** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/499 fixed this

**Comment by shanear** [comment]
agreed. Also, this one is going to be hard to reproduce, so well call it fixed and keep an eye out for tickets
