### ISSUE TITLE
Include the Veteran's suffix in the Claims Folder title

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4821]
If the Veteran's name includes a suffix, we should show that in the title, where we currently list the veteran's name. 

For example, if Joe Snuffy's full name is Joe Snuffy Jr., we should say "Joe Snuffy Jr.'s Claims Folder" at the top of the document list.

## AC
- On the document list page where the Veteran's name is listed, Reader includes the Veteran's suffix when applicable

## Related
Support ticket [1573](https://github.com/department-of-veterans-affairs/appeals-support/issues/1573)

**Comment by abbyraskinUSDS** [comment]
@mdbenjam what do you think about tackling this one?

**Comment by mdbenjam** [comment]
Hmmm seems like a pretty quick fix. I can see if we can get to it.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
