### ISSUE TITLE
Hearing Prep | Pulling in issues closer to hearing day

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4823]
As a judge, I want the most current version of the issues on appeal. In order for this to be the case we need pull in the number of issues closer to the hearing day. Pull in number of issues on the Daily Docket a month out (?)

AC
1. Only allow judges to click on hearings that are <30 days out, so as to pull in appeals stream issues closer to the hearing.
1. Move the issues pull to the daily docket.

**Comment by lakohl** [comment]
@sharonwarner Assuming we decided to pull in and display the number of issues on the DD 30 days before a hearing, would it be possible to allow the judge to click on a Your Hearing Days date 31+ days out and see a docket without issues?

**Comment by sharonwarner** [comment]
@tejans24 We still need to disable the link on the upcoming hearing days page if the hearing day is more than 30 days away.
