### ISSUE TITLE
Automatically check the VBMS Checkbox when certifying an appeal

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#483]
As a user, when I certify an appeal I would like it to automatically check the VBMS checkbox so I don't have to.

See #476 for additional information.

### Acceptance Criteria
1. Verify that when an appeal is certified, verify that the VBMS checkbox is checked in VACOLS, if it wasn't already checked.

### Tech Notes
- This is an integration story and will be validated via the VA network
- This is done in VACOLS by setting `FOLDER.TIVBMS` to 'Y'.

**Comment by shanear** [comment]
@shellicious can you confirm that we want to do this? I'm not 100% sure and I can't remember.

**Comment by shanear** [comment]
Per @KHarshawat, This is already happening in a VACOLS dialog before Caseflow is launched. Going to chat with Jed to confirm.

**Comment by shanear** [comment]
Sent an email to Jed about it.

**Comment by kierachell** [comment]
So I reckon this is still In Progress?

**Comment by shanear** [comment]
From Jed:

> The FOLDER.TIVBMS field should already be set to ‘Y’ long before the case is certified but if it’s not and they select the VBMS paperless e-folder option at certification then the field is set to ‘Y’.

<img width="433" alt="screen shot 2017-01-11 at 10 25 52 am" src="https://cloud.githubusercontent.com/assets/1596259/21854335/579b7bde-d7e8-11e6-825c-79e7273527b3.png">

Looks like we are good here.
