### ISSUE TITLE
Document Viewer | Add more increments of zoom

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4859]
## Story 
As an attorney, I want more varieties of zoom levels so that 1. the document doesn't get hidden under the side menu at various screen sizes and 2. makes my workflow easier when scrolling or keyboarding through pages and documents. 

## AC
- [ ] Add a half sizes in between the current zoom levels

## Related
 #4802

**Comment by gnakm** [comment]
@mdbenjam I don't know what the current levels of zoom are so if you think this horribly vague AC needs love, could you help me make it more specific?

**Comment by mdbenjam** [comment]
I think that's descriptive enough.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
