### ISSUE TITLE
Demo DD | Add cases where the Veteran = the Appellant to Demo

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4883]
On the Daily Docket in Demo, need to be able to see both cases where the Veteran is the appellant and cases where a second person is the appellant.

**_Current:_**
![fireshot capture 19 - daily docket 3_16_2018_ - http___dsva-appeals-certification-](https://user-images.githubusercontent.com/4975959/37548629-a734b48a-294f-11e8-895a-fb208083aa45.png)

**_Desired_**
![claim row 10](https://user-images.githubusercontent.com/4975959/37548664-d3e1ad12-294f-11e8-872b-84e88c3eec46.png)

**Comment by annienguyenUSDS** [comment]
Moving forward with UAT for training/testing instead of demo.
