### ISSUE TITLE
Intake | Users are cancelling intakes when APIs are slow

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4889]
After a little digging on why Postgres deadlock errors are occurring (see: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1049/events/41717/). It looks like when the calls to BGS and VBMS associated with establishing a claim take a long time (20-30sec), some users are cancelling the intake. This causes a deadlock error, which is problematic because the claim might have been created, but the cancellation also goes through.

Short term solution, take the establish claim API calls out of the transaction boundaries.

As a long term solution, we could move the claim establishment to an asynchronous job, taking an eventual consistency pattern. I'll follow up with this ticket.

## Acceptance Criteria
- On the finish intake page, the "Cancel Intake" button should hide as long as the Submit button has been clicked and is loading.

**Comment by shanear** [comment]
Try using 561349913 in UAT to test this

**Comment by leahbannon** [comment]
Reviewed, looks good. Cancel intake button is disabled after I click on Submit, then I get a "something went wrong" error and the button is enabled.
