### ISSUE TITLE
Assign x cases | Attorney side bar | Attorney queues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4890]
As a judge, I want to see the cases in my attorney queues to help triage and assign appropriate cases across my attorneys. 

### Acceptance criteria
- [ ] Verify that when an Judge clicks on an attorney name on the side bar, they are taken to that queue
- [ ] Verify that there is a table titled Attorney Queues
- [ ] Verify that the Attorney side bar of the selected attorney is highlighted
- [ ] Verify that there is a table with the following: 
    - [ ] Case details - list of cases with Veteran Name and Veteran ID
    - [ ] Docket = docket number (note: this is the same as attorney queue)
    - [ ] Issues = number of issues (note: this is the same as attorney queue)
    - [ ] Docs in claims folder = number of documents in claims folder (note: same as attorney queue but without link to Reader)
    - [ ] Days Waiting = number of days the case has been with the judge
- [ ] Verify the list of cases assigned to  the user clicks on an attorney's name, the user sees a table populated with their cases
- [ ] Verify that the sidebar includes the number of cases assigned to each attorney

### Mocks
![harry muggle queue](https://user-images.githubusercontent.com/23316107/37787323-0f9f2760-2dd5-11e8-92f1-4c61dae3b1f0.png)

### Related
- Assign x cases - https://github.com/department-of-veterans-affairs/caseflow/issues/4714
- Attorney side bar - https://github.com/department-of-veterans-affairs/caseflow/issues/4763
- Count of cases per attorney - https://github.com/department-of-veterans-affairs/caseflow/issues/4715

### Notes
When a judge is assigning cases to attorneys, they want to see the other cases on their attorneys' plates. They attempt to assign cases of varying complexity to their attorneys so they are not overwhelmed with difficult decisions to write, so seeing what other cases are currently on their attorneys' plate helps them decide if they case they are assigning is too complex or not.

**Comment by evankroske** [comment]
Estimate: 10 hours

**Comment by evankroske** [comment]
Actual time taken: 15 hours
