### ISSUE TITLE
Vacated issues should be able to be marked for duplication

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4891]
![image](https://user-images.githubusercontent.com/3781835/37615733-5aa1dcf6-2b84-11e8-8b2f-11e2caa551ca.png)

Attorneys should be able to mark vacated issues for readjudication.

## AC
- If the user marks an issue with the `5 - Vacated` disposition and checks "Automatically create vacated issue for readjudication", when the user submits the draft decision, that issue should be duplicated on the appeal

**Comment by aroltsch** [comment]
```
The following columns should be duplicated onto a new issue: issprog, isscode, isslev1, isslev2, isslev3, issdesc
Then issseq should be set to the previous max issseq plus 
ISSADTIME to the current datetime
ISSADUSER to the current user 
issdc should be set to nil ```

**Comment by amprokop** [comment]
Reopening so @dannysellers can confirm when frontend/backend are hooked up.

**Comment by dannysellers** [comment]
Confirmed, closing
![issue_duplication](https://user-images.githubusercontent.com/8533004/38336691-ac9389d4-3830-11e8-90d2-861c26263656.gif)
