### ISSUE TITLE
All users | Navigate to Queue from Reader

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4894]
When any Caseflow user has navigated to Reader to start reviewing any case (assigned to them or not), they want a way to navigate back to their own queue (homepage) to choose another case to work on, switch tasks, etc. 

This is relevant timing for judges, because they currently cannot navigate to Reader from their queue, just from Case Details. But, it will be relevant for all users.

The design team is thinking through navigation on a larger scale and removing breadcrumbs entirely, so this is an interim solution. 'Caseflow' in the navigation should link to the user's default queue view, or if the user does not have cases assigned to them, back to the queue empty route/search page. 

### Acceptance Criteria
- Insert a '>' between "Caseflow" and "Reader" in the header. Reader does not link anywhere.
- "Caseflow" in the Caseflow Reader header navigation links to the user's default Queue 
- If the user does not have cases assigned to them in a Queue, Caseflow links to the Queue empty route / search page

**Comment by amprokop** [comment]
@laurjpeterson @Chingujo, can you take another pass on this and slap the ready for development label on after?

**Comment by laurjpeterson** [comment]
@amprokop interim solution is ready!

**Comment by amprokop** [comment]
hmmm. i'm actually wondering — do we need Reader in the title bar anymore at all? what difference would it make to our users if we actually removed it? is this branding that they rely on? should future attorneys who weren't here for the Reader rollout even think of Reader as its own product?

**Comment by amprokop** [comment]
@laurjpeterson — i was worried for a moment that it might be a surprising amount of work to implement this. But after looking at the code, i don't think so anymore. Fine with this interim solution.
