### ISSUE TITLE
Allow judges to distinguish between assignments that need to be assigned to attorneys and assignments to review

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4895]
Part of https://github.com/department-of-veterans-affairs/caseflow/issues/4853

![image](https://user-images.githubusercontent.com/3781835/37618867-eb485c86-2b8d-11e8-8064-642350d4ac33.png)

For the judge view, we need some new pieces of information. We need to distinguish between cases to assign and cases to review, and for each of them, we need to be able to calculate a "Days waiting" value.

For cases to review, this column means “Days since the attorney has assigned the case back to the judge”, and for cases to assign, this column means “Days since the DAS assignment to this judge was created”.

# AC
-  For judges, `GET /queue/:user_id` should return a list of tasks that tell the client whether they're cases to review or cases to assign
  - If `DERECEIVE` is nil, it's a case to assign, otherwise it's a case to review
- For judges, `vacols_assignment.assigned_on` should reflect the date on which the case entered the judge's queue, so the frontend can use that to calculate "Days waiting"
  - This probably means that we're not pulling from `DEASSIGN` for `assigned_on` anymore, as we would for attorneys
  - For cases that the judge has to assign to an attorney, `assigned_on` should come from `DECASS.DEADTIM`
   - For cases that the judge has to review, `assigned_on` should come from `DECASS.DERECEIVE`

**Comment by amprokop** [comment]
As always.. let's confirm this with Jed. Just my best guess.

**Comment by aroltsch** [comment]
How to determine if a user is an attorney or judge:

STAFF.SVLJ = ‘J’ indicates a user is a Judge, the field may also have an ‘A’ which indicates an Acting judge. If the STAFF.SVLJ is nil and STAFF.SATTYID is not nil then it is an attorney.
