### ISSUE TITLE
Allow judges to fetch a list of attorneys in their group 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4896]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4853

![image](https://user-images.githubusercontent.com/3781835/37621385-26045828-2b95-11e8-86ea-fa2c8c011462.png)

For the Judge queue, judges have to be able to see a list of attorneys that work under them and fetch their queues.

We'll need to ask Jed how to associate attorneys with their judge, it's not entirely obvious from the data. My best guess from the data is that `stitle`contains the team name, so we'd first query VACOLS for `VACOLS::Staff.find_by(sdomainid: JUDGE_ID).stitle` and use that to find all staff members with `sdept` = `BDCOUNSEL` and `stitle` equal to the value we fetched

Anonymized `STAFF` record:

```
 #<VACOLS::Staff stafkey: "POLD", susrpw: nil, susrsec: "1", susrtyp: nil, ssalut: nil, snamef: "Don", snamemi: nil, snamel: "Pol", slogid: "POLD", stitle: "D1", sorg: nil, sdept: "BDCOUNSEL", saddrnum: nil, saddrst1: nil, saddrst2: nil, saddrcty: nil, saddrstt: nil, saddrcnty: nil, saddrzip: nil, stelw: nil, stelwex: nil, stelfax: nil, stelh: nil, staduser: nil, stadtime: nil, stmduser: nil, stmdtime: nil, stc1: nil, stc2: nil, stc3: nil, stc4: nil, snotes: nil, sorc1: 0, sorc2: 0, sorc3: 0, sorc4: 0, sactive: "A", ssys: "Y", sspare1: nil, sspare2: nil, sspare3: nil, smemgrp: "511", sfoiasec: false, srptsec: false, sattyid: "1952", svlj: nil, sinvsec: nil, sdomainid: "VACOPOLD">
```

# AC
- `GET /users?judge_team=JUDGENAME` will return the Caseflow user id, full name, and css id of all the attorneys that work with the judge
- Limit to judges and attorneys in the chief groups: Scire, Scharnberger, Crawford, Bruce, Jones, Allen, and Catino
- TODO: Trueba, Buck, March

**Comment by aroltsch** [comment]
From jed, 
```
There is currently no data in VACOLS that ties the attorney back to their Judge.  STAFF.SMEMGRP ties the attorney back to the Chief Member.
```

**Comment by laurjpeterson** [comment]
[BVA Org Chart](https://github.com/department-of-veterans-affairs/caseflow/files/1857286/2018.01.08.Reconciled.Org.Chart.-.Intranet.with.names.pdf)

See slides numbered 6 through 10 for judge teams and their attorneys.

**Comment by laurjpeterson** [comment]
@aroltsch here's the 6 chief groups I have in one excel. still waiting on the 4 more chief groups.
[attorneys_judges_chiefs_april 2018.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/1892391/attorneys_judges_chiefs_april.2018.xlsx)

**Comment by laurjpeterson** [comment]
updated!

[attorneys_judges_chiefs_april 10 2018.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/1896436/attorneys_judges_chiefs_april.10.2018.xlsx)
