### ISSUE TITLE
Allow a judge to assign an appeal to an attorney with POST /tasks

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4897]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/4853

Judges need to be able to assign appeals to attorneys.

POST /tasks

```
{
  appeal_id: 48323209C
  appeal_type: "Legacy"
  attorney_id: 4
}
```

## AC
- Only judges can assign appeals to attorneys, if the user who POSTs to `/tasks` is not a judge, error (we'll have to change this later)
- Create a row in DECASS:
  - `defolder` should be the appeal id
  - `deatty` should be the attorney id
  - `deteam` should be the attorney/judge team id
  - `depdiff`—?
  - `deadusr` should be the judge’s slogid
  - `deadtim` should be the date (not hour/m/second) that the assignment is created
  - We can likely skip `dedeadline`
  - `deicr`—?
- Update the appeal's location to the attorney's location

**Comment by aroltsch** [comment]
From Jed

![image](https://user-images.githubusercontent.com/3811786/38148947-8e5bd060-3426-11e8-9ea6-a1da2ac415a1.png)

**Comment by aroltsch** [comment]
From Jed

![image](https://user-images.githubusercontent.com/3811786/38198568-5febab38-365b-11e8-9342-a8966562ba4b.png)
