### ISSUE TITLE
Document Viewer, Make PDF toolbar Flexbox

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#4913]
Related #4802

<img width="747" alt="screen shot 2018-03-21 at 11 00 49 am" src="https://user-images.githubusercontent.com/1745984/37717549-254c3eba-2cf7-11e8-8630-d935cc1d2fbc.png">

##AC
Make Toolbar responsively fit views.

_Potential Solution at smallest width_
At around 800px, if the sidebar is open the PDF container is only 525px or so. 
I am wondering if we should hide middle category section(covers ranges between 800-920px.
<img width="541" alt="screen shot 2018-03-21 at 11 04 39 am" src="https://user-images.githubusercontent.com/1745984/37717976-0fa59132-2cf8-11e8-809a-8126ae730f13.png">

**Comment by mdbenjam** [comment]
I think Gina had some thoughts around this on this ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/3736

**Comment by nolawi** [comment]
Awesome, I will close this ticekt and continue to #3736
