### ISSUE TITLE
Daily Docket | Align text with the bottom of the dropdown

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4928]
Drop the City, # of issues and Rep Name a few pixels, so the bottom of the  text lines up with the bottom of the Actions dropdowns.

**Comment by lakohl** [comment]
Related to: https://github.com/department-of-veterans-affairs/caseflow/issues/4205

**Comment by MeredithStewart** [comment]
Fixed with new hearing schedule daily docket.
