### ISSUE TITLE
Search | Remember location of last search or click

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4930]
Currently when a user searches we always bring them back to the first result. The only way to skip to a later result is to click on a page with a result on it, and hit the next or previous arrow and it will highlight a result from that page. Clicking on pages without results does not do anything.

In standard browser search if you search for one term, click anywhere on the page, the next highlighted term will be the one after the location of your click. Furthermore, if you change your search term, you start search from the location of the most recently highlighted term.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
