### ISSUE TITLE
Caseworker Home:  Establish Next Claim:  Disable button when no more claims

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#494]
As a Caseworker, I would like to have the Establish Next Claim button disabled when there are no more claims available for processing so that I don't attempt to click on the button.

### Acceptance Criteria
1. Verify that on the Caseworker Landing page, the _Establish Next Claim_ button is disabled when there are no more claims to process.
1. Verify that on the Caseworker Landing page when the _Establish Next Claim_ button is disabled, the queue count text is replaced with the following text: "No claims to establish right now".

### Mockup
*View 1 - Disabled "Establish Next Claim" button*
![494 - establish next claim button](https://cloud.githubusercontent.com/assets/23063044/20765247/831ab69e-b6ff-11e6-9516-757fdc6a0c91.PNG)

*View 2 - Enabled "Establish Next Claim" button*
![494 - establish next claim button-enabled](https://cloud.githubusercontent.com/assets/23063044/20765287/b6a2114c-b6ff-11e6-8859-79157e2174e6.PNG)

### Sub-Tasks
QA Manual testing

**Comment by KHarshawat** [comment]
@nikitarockz Here is the mock of what the button looks like when it is disabled. Please note that this results in a change to what the text next to the button should look like in both the active and inactive states. See the second mock below.


![establish claim disabled](https://cloud.githubusercontent.com/assets/6335546/20764592/d8528c48-b6fc-11e6-81e2-e2047867b529.png)

![establish claim enabled](https://cloud.githubusercontent.com/assets/6335546/20764591/d83024f0-b6fc-11e6-9f42-8b9595debfb6.png)

**Comment by lakohl** [comment]
@KHarshawat this solution looks great, thanks for doing it.

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached.
<img width="1155" alt="screen shot 2016-12-15 at 4 35 42 pm" src="https://cloud.githubusercontent.com/assets/23038505/21242963/cd9c77fc-c2e4-11e6-949e-abbc3d6a7ad8.png">
<img width="1073" alt="screen shot 2016-12-15 at 4 35 53 pm" src="https://cloud.githubusercontent.com/assets/23038505/21242964/cd9d6504-c2e4-11e6-9771-63f2652044b0.png">
