### ISSUE TITLE
Service Treatment Record documents do not convert/load properly

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4946]
Some important STR documents are not loading - it seems like these are (always? sometimes?) .tiffs that aren't converting. 

## Example documents
https://appeals.cf.ds.va.gov/reader/appeal/3702684/documents/10186176
https://appeals.cf.ds.va.gov/reader/appeal/3702684/documents/10186157
https://appeals.cf.ds.va.gov/reader/appeal/3702684/documents/10186158
https://appeals.cf.ds.va.gov/reader/appeal/3702684/documents/10186159
https://appeals.cf.ds.va.gov/reader/appeal/3702684/documents/10186160

# Related Tickets
**_Support_**
`Parent`:  Document Viewer| STR documents are not loading [#1706](https://github.com/department-of-veterans-affairs/appeals-support/issues/1706)

**Comment by abbyraskinUSDS** [comment]
Another support ticket came in about this today: https://github.com/department-of-veterans-affairs/appeals-support/issues/1809

**Comment by mdbenjam** [comment]
I spent a couple more hours looking into this earlier this week. It seems like the conversions that fail take a long time and can cause our boxes to crash (even when the docker container is supposedly resource limited), figuring out what's going on here seems complicated :/

**Comment by mdbenjam** [comment]
I also tried upgrading libtiff and it did not fix the problem.

**Comment by abbyraskinUSDS** [comment]
Thanks for looking into this! Given the complexity here, I'm closing this out.

**Comment by abbyraskinUSDS** [comment]
Two more recent support tickets:
- https://github.com/department-of-veterans-affairs/appeals-support/issues/2000
- https://github.com/department-of-veterans-affairs/appeals-support/issues/1977

**Comment by abbyraskinUSDS** [comment]
Another support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/2087

**Comment by abbyraskinUSDS** [comment]
Some of these are .tiffs, and some are just very large medical pdfs.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
