### ISSUE TITLE
AMA intake | Select form: replace radio buttons with searchable dropdown when there are more than 3 form options available

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4947]
Context: In the future, there will be more than 2 form options available to users. We're updating the UI with a different styleguide component that is more user-friendly for this scenario.

## Acceptance Criteria
- If there are more than 3 form options available to a user, the radio buttons on the Select Form page are replaced by a searchable dropdown (see styleguide) with the following options:
  - RAMP Opt-In Election 
  - RAMP Selection (VA Form 21-4138 Statement in Support of Claim)
  - Request for Higher-Level Review (VA Form 20-0988) 
  - Supplemental Claim (VA Form 21-526b)
  - Notice of Disagreement (VA Form 10182)
- Selecting "Continue to search" button navigates user to the Search page once it is developed  
- Hidden behind a feature flag 

## Mocks
![image](https://user-images.githubusercontent.com/4042181/37919386-b33dd4b0-30f1-11e8-9109-42f768b1127f.png)

## Copy
Title: Welcome to Caseflow Intake:
Body: To get started, choose the form you are processing for intake.
Dropdown label: Which form are you processing?
Dropdown placeholder: Enter or select form
Dropdown options:
  - RAMP Opt-In Election 
  - RAMP Selection (VA Form 21-4138 Statement in Support of Claim)
  - Request for Higher-Level Review (VA Form 20-0988) 
  - Supplemental Claim (VA Form 21-526b)
  - Notice of Disagreement (VA Form 10182)

**Comment by shanear** [comment]
Do we want to add the caveat that if there are more than 3 options it should turn into a searchable dropdown? This way we can more easily support: https://github.com/department-of-veterans-affairs/caseflow/issues/4798 when the time comes.

**Comment by leahbannon** [comment]
looks good - reviewed with Sally on local because it's behind a feature tag
