### ISSUE TITLE
AMA intake | Search: SC, HLR, NOD

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4948]
(Search functionality isn't changing much, but this is to make sure we have a search page for each review option)

## Acceptance Criteria
- Users arrive on this page after selecting a form on the Select Form page 
- Body copy includes name of form selected in previous step
- Validations are the same as existing RAMP functionality: Vet exists in corporate db, user has sensitivity, profile valid in corporate 
- Submitting search navigates user to "Review" step once this page is developed (can navigate to blank screen for now)

## Mocks
![image](https://user-images.githubusercontent.com/4042181/37919590-553dd332-30f2-11e8-821b-f5a2964ca8f1.png)

## Copy
Title: Search for Veteran by ID
Body: Enter the Veteran's ID below to process this [form name].
  - Example: Enter the Veteran's ID below to process this Request for Higher-Level Review (VA Form 20-0988).

**Comment by leahbannon** [comment]
reviewed - this looks good
