### ISSUE TITLE
AMA intake | Review: Supplemental Claim

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4949]
This is the page where users can enter the Receipt Date for an AMA Supplemental Claim form.

## Acceptance Criteria
- User navigates to this page by selecting a SC on the first step, and submitting a valid search on the previous page
- Receipt date is not in the future
- Receipt Date is required
- "Cancel intake" button launches same modal as RAMP (for now)
- Selecting "Continue" button navigates user to the Finish processing page once it is developed 
- Note: will need to figure out the data structure

## Mocks
![image](https://user-images.githubusercontent.com/4042181/38044253-36e98160-3287-11e8-81dc-cde18bcf0bb3.png)

**Comment by shanear** [comment]
Clarified the receipt date validations

**Comment by shanear** [comment]
you can use any of these file numbers to test this

https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/TestEfolderData.csv

**Comment by leahbannon** [comment]
looks great! reviewed on local with Sally because it's behind a feature flag
