### ISSUE TITLE
File being retrieved does not show in History

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#495]
File being retrieved does not show in History. I found the following bug while conducting eX UAT tests.

**Comment by lakohl** [comment]
Normally a file in the process of being retrieved should still show in the History.

I searched for Vera Marshall, then went back to home to search for a new Vet ID. The History section was still not visible on the eX homepage.
<img width="887" alt="screen shot 2016-11-28 at 12 05 44 pm" src="https://cloud.githubusercontent.com/assets/4975959/20678155/b65566aa-b563-11e6-8eda-36d1b3d36f9a.png">
<img width="872" alt="screen shot 2016-11-28 at 12 05 51 pm" src="https://cloud.githubusercontent.com/assets/4975959/20678160/b9abb6f6-b563-11e6-98b0-e563eb9c2c6b.png">

**Comment by shanear** [comment]
@lakohl this should be `caseflow-efolder`

**Comment by lakohl** [comment]
@shanear Argh. Sorry!

**Comment by lakohl** [comment]
Closing
