### ISSUE TITLE
AMA Intake | Review: Higher-Level Review

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#4950]
The HLR form captures a couple extra data points (conference, office preference), so the "review" step should include a place for users to note these requests.

## Acceptance Criteria
- User navigates to this page by selecting the Higher-Level Review form on the first step, and submitting a valid search on the previous page
- The title includes the form name in the title - Request for Higher-Level Review (VA Form 20-0988)
- Receipt date validations from standard date picker (that the date was entered, and it's not in the future or an invalid date)
- All questions on this page are required 
- "Cancel intake" button launches same modal as RAMP (for now)
- Selecting "Continue" button navigates user to the Finish processing page once it is developed

## Mocks
![image](https://user-images.githubusercontent.com/4042181/38823286-fbe17158-4173-11e8-8293-f7bbcbe11e38.png)

**Comment by shanear** [comment]
> - Receipt date validations from standard date picker (same as RAMP)

the only validation here that makes sense is validating that the date is not in the future. The other validation is that it's after the RAMP notice date which doesn't make sense. I'll just explicitly call that out.

**Comment by abbyraskinUSDS** [comment]
And that the date exists :) E.g., there's no month 13.

**Comment by leahbannon** [comment]
Header copy currently reads, "Review [vet]'s Higher-Level Review (VA Form 20-0988)" -- it needs to read, "Review [vet]'s *Request for* Higher-Level Review (VA Form 20-0988)"

**Comment by leikkisa** [comment]
I'm going to make this change in the Appeal confirmation PR

**Comment by leahbannon** [comment]
looks great!
