### ISSUE TITLE
[spec] Automating Case Storage assignment to judges: 2nd draft

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4954]
# Context

See https://github.com/department-of-veterans-affairs/appeals-design-research/issues/645

# Overview

We'll develop a Case Storage auto-assignment model that:
 - removes any need for a Case Storage staff member to push cases to judges and eliminates lag time
 - allows the Board to monitor and adjust the throughput of different types of cases so it can remain compliant & prevent logjams
 - will leave room to add three types of AMA appeals
 - will allow us to add specialty case teams

# Implementation

## Assigning a case from case storage to a judge

- Get the current docket date using `VACOLS::CaseDocket.docket_date_of_nth_appeal_in_case_storage` 
- To be eligible for case storage assignment, an appeal must have the following attributes:
   - location 81 
   - BFD19 <= current docket date
   - activated
   - no pending mail or open diaries
- To assign an appeals to a judge, we:
  - set the appeal to the judge's location (BRIEFF.BFCURLOC = STAFF.SLOGID)
  - create a DECASS rows for that appeal where DEFOLDER is equal to BRIEFF.BFKEY 

## Assignment parameters

By law, we need to prioritize AODs, and the board has slated hearing cases as a priority. Currently, AOD decision output is somewhere around 20%, which we see as a  healthy figure. However, it appears that judges and case storage staff manually keep case category throughput in balance. If we develop a relatively simple auto-assignment model, but keep certain parameters configurable, we can control the throughput of various case categories centrally and monitor throughput to ensure it meets compliance and production goals.

Proposed configurable parameters:
- Assignment batch size
  - Likely 20 or 30 to start
- Max % of AOD cases   
  - Around 20%, if that's our target
- Max % of hearing cases
  - TBD — 50%?

## Provisional auto-assignment logic

Auto-assignment will happen for one judge at a time.

Find and assign (batch size * (Max % AOD)) AOD cases to a judge.
Find and assign the minimum of (batch size - already assigned cases) and (batch size * (Max % hearing)) hearing cases to a judge.
Find and assign (batch size - already assigned cases) gen pop cases to the judge.

### Example

Batch size is 30, AOD % is 20, Hearing % is 50.

A judge requests a batch of 30 cases.

The judge has 25 hearing cases awaiting decision, there are 500 AOD cases currently on docket, and 7000 genpop cases. The judge requests a batch of cases from case storage.

30 * .2 = 6, so 6 AOD cases are assigned to the judge.
30 * .5 = 15 is the max # of hearing cases the judge can receive in a batch. The judge has 30 - 6 = 24 cases that can still be assigned, so 15 hearing cases are assigned to the judge.
30 - 6 - 15 = 9, so 9 genpop cases are assigned to the judge.

## Monitoring

To validate our model is behaving as we intend and so we can watch for any needed adjustments, we'll need to track the flow of all types of cases to judges separately. However, in the end, the top-line metric we care about is decision output, not case assignment. We'll want to also ensure descision output by case type is surfaced and easily available. We might opt to do this in Datadog at first, but ideally we'd make this easy to view for BVA employees as well, and ensure Tableau or a business metric tool can surface necessary data.

## AMA appeal preparation

The business requirements for AMA case storage auto-assignment are not yet clear. It may be the case that separate judge/attorney teams exclusively work AMA appeals.

In this case, we could just create a separate case storage auto-assignment code path with its own configuration variables.

Additionally, we want to make it easy to track case storage assignments. We'll defer a final decision until later, but we'll consider creating a CaseStorageAssignment record for all appeals, so we ensure we're tracking assignments in Caseflow.

## Specialty case teams

Business requirements for specialty case teams are not clear yet, but adding specialty case teams *may* significantly increase the complexity of this effort.

A few options:

- We could never assign appeals with specialty case team issues in the general auto-assignment process, reserving them exclusively for the specialty teams
- We could assign appeals with specialty case team issues in the general auto-assignment process only if they have been in the docket range for some amount of time

These questions probably deserve their own separate spec.

## Manual assignment

It's likely that there will be assignment hiccups. When we initially roll out case storage auto-assignment, we should ensure we can manually tweak case assignments as needed. At first, this can just be through a method exposed to the Rails console that a system admin engineer can run. This manual method must be able to support switching cases from judge to judge.

## User interface

We'll weigh two different approaches for triggering the assignment of cases from case storage to judges.

### Option 1: Self-service button

When a judge loads Caseflow Queue and views the appeals assigned to them, we could present the judge a "Fetch more from Case Storage" button. Upon clicking a button, we'd assign a batch of case storage cases to the judge, and they'd appear in the Queue list view immediately after assignment is complete.

#### Goal: Judges should understand the methodology behind automatic case allocation
  - The button would require minimal training and explanation
#### Goal: Cases should not be allocated to attorneys and judges on PTO/leave
  - Judges are likely in the best position to know who is on PTO/leave, and they won't request cases for themselves while they're on leave
#### Goal: Cases are only allocated to active staff 
  - Cases will not be assigned to judges unless they click a button, and judges will know not to assign cases to inactive attorneys
#### Goal: Cases should not sit on judges plates to assign or to sign for long times
  - A "Fetch more from Case Storage" button could be disabled until after a judge has assigned all existing cases 

### Option 2: Auto-assign cases to judges from case storage

We wouldn't need any UI for this option. We could approach a full automation option in several ways. Two that come to mind:

1. A recurring job could run on some interval and ensure each judge has at least N cases on their plate to assign to attorneys. 

2. Each time a judge assigns an appeal to an attorney, if the judge has less than N cases on their plate, we add a batch of new cases from case storage

However, a fully automated option will create some challenges and risks.

#### Goal: Judges should understand the methodology behind automatic case allocation
  - We would need to think about how to ensure that it doesn't feel like cases are assigned at random times
#### Goal: Cases should not be allocated to attorneys and judges on PTO/leave
 - Accounting for PTO/leave may prove to be difficult and error-prone— delays may result
#### Goal: Cases are only allocated to active staff 
  - We would need to ensure that we don’t accidentally assign cases to judges who have retired, and if cases do get assigned to those judges, we should audit it.
#### Goal: Cases should not sit on judges plates to assign or to sign for long times
  - If their plates are automatically refilled, judges might hold on to difficult cases longer than they would otherwise

# Test Plan

Using FACOLS, we'll be able to thoroughly test the Case Storage assignment to judge logic locally. 

# Rollout Plan

We can develop this in parallel with the judge queue, but we shouldn't roll it out until we roll out the judge queue. We could test this process change with one judge at first by putting it behind a feature toggle.

**Comment by aroltsch** [comment]
Great document @amprokop! From the implementation standpoint, everything looks pretty straight forward. We should definitely invest some time to ensure we have good logging and monitoring in place so we can track auto assignments. 

I like `Option 1: Self-service button` more than `Option 2: Auto-assign cases to judges from case storage` because it would allow a judge to control the assignment. I doubt there is a way for us to determine programmatically if a judge is on PTO. I also think we should provide a judge with an option to select a batch size.
