### ISSUE TITLE
Styleguide | Delete unused colors!

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#4958]
## Story
As a developer, I want to be able to see only the colors we are using in our code so that I don't get confused and potentially add more colors than needed. Really, we should follow style guide.

## AC
- [ ] Take out any color that is not in the list below: 

`#212121` - `$color-base`
`#323a45` - `$color-gray-dark`
`#5b616b` - `$color-gray`
`#aeb0b5` - `$color-gray-light`
`#d6d7d9` - `$color-gray-lighter`
`#e4e2e0` - `$color-gray-warm-light`
`#0071bc` - `$color-primary`
`#fff` - `$color-white`
`#e31c3d` - `$color-secondary`
`#2e8540` - `$color-green`
`#02bfe7` - `$color-primary-alt`
`#f9dede` - `$color-secondary-lightest`
`#e7f4e4` - `$color-green-lightest`
`#e1f3f8` - `$color-primary-alt-lightest`
`#fff1d2` - `$color-gold-lightest`
`#4c2c92` - visited link - overwrite USWDS

**Logos:**
`#844e9f`
`#F0835e`
`#73e5d4`
`#459FD7`
`#417505`
`#FFCC4E`
[insert hearing prep]

**Reader categories**
`#FFCC4E`
`#5a94ec`
`#ff6868`
`#3ad2cf`

Others:
`#f9f9f9` (canvas color)

### Special instructions
- Anything that is `#757575` should be changed to `#5b616b`-`&color-gray`

### Note
- There may be some colors currently being used for coach
marks. Those we can keep. 
- If there is anything else, please ping appropriate designers for each application, or Gina/ @sneha-pai for overall style guide questions 

## Dependent issues
https://github.com/department-of-veterans-affairs/caseflow/issues/4315

## Original Issue
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/559

**Comment by nolawi** [comment]
`#0872b9` - `#0071bc` - `$color-primary` 
editing...

**Comment by nolawi** [comment]
Looks like the visited link color is `#4c2c92` - am wondering if it should be `#844e9f`

**Comment by nolawi** [comment]
@lakohl ^
