### ISSUE TITLE
Case Summary | Show Case Summary Doc types in demo

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4960]
The Case Summary should show the doc types included in the Case Summary and not others. So this is the case, we should avoid using the same date for all docs in the efolder and not have more than one doc with a date in the last 30 days.

## AC
1. In demo, avoid showing more than 1 doc added to the claim folder in the last 30 days.
1. Display the following Case Summary doc types: 
 "NOD",
    "Notice of Disagreement",
    "SOC",
    "Statement of Case (SOC)",
    "Form 9",
    "VA 9 Appeal to Board of Appeals",
    "Form 8",
    "VA 8 Certification of Appeal",
    "BVA Decision",
    "SSOC",
    "Supplemental Statement of Case (SSOC)",
    "DD 214 Certified Original - Certificate of Release or Discharge From Active Duty",
    "Rating Decision - Codesheet",
    "Rating Decision - Narrative",
    "VA 21-526EZ, Fully Developed Claim (Compensation)",
    "VA 21-527EZ, Fully Developed Claim (Pension)",
    "VA 21-22 Appointment of Veterans Serv. Org. as Claimant Rep",
    "Power of Attorney (incl. VA 21-22, VA 22a)",
    "Hearing Transcript"

## Currently in demo:
![fireshot capture 24 - v marshall s claims folder_ - http___dsva-appeals-certification-](https://user-images.githubusercontent.com/4975959/37928935-7fec9d06-310c-11e8-8423-1a1afb0569b2.png)

**Comment by annienguyenUSDS** [comment]
Moving forward with UAT for training/testing instead of demo.
