### ISSUE TITLE
AMA Pilot 1 - Issues exploration — How might we retain the mapping of issues to disability rating?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4961]
## Context

One of Caseflow Intake’s goals is to connect issues to specific parts of the disability rating, so VA can know which parts of the disability rating are currently being appealed/higher level reviewed/supplemental claimed. As such, Caseflow has to be able to map issues on a decision to issues on the disability rating.

Caseflow Intake includes a manual step where Intake users will map issues on an NOD to specific parts of the disability rating before creating an appeal. Current VACOLS-era workflows would often break this mapping. 

During case review, attorneys often make judgement calls regarding what issues should be on an appeal. For example, perhaps an RO staffer read the NOD and created an issue with code A. During case review, an attorney might decide that a veteran's medical record more closely resembles issues with codes B and C. Right now, an attorney would then delete issue A and add issues B and C. 

The flexibility that attorneys have likely works in Veterans' favor. Attorneys can obtain higher disability ratings for Veterans by changing issues. But we need a way to retain the mapping of appeal issues to the original issues which staffers have associated with the disability record.

## Proposal

During attorney case review for AMA appeals, attorneys can still change issues. But they have to map their changes back to the original issues, which have previously been mapped to the disability rating.

We could solve this problem by storing two sets of issues for an appeal—NOD issues and decision issues. NOD issues cannot be changed outside of Caseflow Intake. However, attorneys can modify decision issues, with two requirements:

- each decision issue must be associated with an NOD issue
- each NOD issue must have at least one decision issue associated with it

## Example 

A claims assistant entered issues A and B on an appeal.
When the attorney starts case review, NOD issues and decision issues would both equal [A, B].
The attorney decides that the veteran's condition most closely matches [A, C, D].
So the attorney deletes decision issue B and adds C and D to the decision issues.
Before finishing the case review, Caseflow requires the attorney to map C and D back to either A or B.

**Comment by cmgiven** [comment]
I think this captures it, yes. Thumbs up.

One lingering question in my mind is what happens if the NOD was entered incorrectly. In that case, we might need to revise the NOD issues based on the appeal-able issues that were available at the time. This would basically be to re-Intake it, though, and is possibly a separate flow from what is described here. Shane, thoughts how you’d like that to go? Can we have a “NOD was done wrong” button that triggers Intake?

**Comment by shanear** [comment]
> This would basically be to re-Intake it, though, and is possibly a separate flow from what is described here. Shane, thoughts how you’d like that to go? Can we have a “NOD was done wrong” button that triggers Intake?

Yes, we are working this flow out with HLRs and SCs too. We will support this use case.

**Comment by laurjpeterson** [comment]
Closing this, because Caseflow Intake does this mapping now.
