### ISSUE TITLE
Rails 5 Test plan

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#4962]
Tests should include users with permission and no permissions. Also, positive tests (when user has permission) should be using at least two different sessions. 
All apps should try to submit feedback. 
This is a draft, team leads are encouraged to modify/make additions to the existing plan. 

Certification:

- New

- Missing docs

- Already certified

- VBMS Error

- Unable to certify

Reader:

- Communication with eX works 

- Welcome Gate

- Document List

Dispatch:

- Work History

- Work Assignments

- Missing Decisions

- Oldest Unassigned Tasks

Hearing Prep:

- Upcoming Days

Intake: 

- Start

Stats:

**Comment by mdbenjam** [comment]
Tested Reader:
1) Ensured cases showed up on the welcome gate & search.
1) Viewing document lists works
   1) Claims folder details load
   1) Searching and filtering work
   1) Comment view works
1) Document view works
   1) Documents show up
   1) Adding/removing categories, tags, and comments works
   1) Moving to next/previous documents works
1) Leaving feedback says it's from Reader
1) Users unauthorized to use Reader are sent to unauthorized page.
