### ISSUE TITLE
Make `RampElectionIntake.complete!` partially idempotent and remove transactions

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#4966]
## Acceptance Criteria
- There are no nested transactions within `RampElectionIntake.complete!`
- If an EP with the matching claim date and ep code exists in BGS, attach that to the RampElection and allow it to complete successfully.
- If an EP with a matching ep code but different claim date exists, still throw the same duplicate ep error message.
- If no EP with the matching claim date and ep code is found, and a duplicate EP error is still sent, show a message asking the user to try again.

## Original Thoughts
In intake, we have a couple atomic write operations that require us to write to VBMS, VACOLS, and our database, sometimes multiple times. We perform these operations synchronously, which causes some problems:

1) They're slow, sometimes taking over 20 seconds to complete.

2) In the scenario where one of these writes fail, it sometimes leaves the transaction in a half completed state.

We should explore making these operations asynchronous, and able to be retried when certain parts of them fail.

**Comment by sansb** [comment]
Sounds good. Disabling the cancel button while request is in-flight was a good first step and could be sufficient for quite a while- we should keep an eye on Sentry for any failures around this and prioritize appropriately.

**Comment by shanear** [comment]
Validated in prod by having ARC process some of the cases we knew to have duplicate EPs:

```
irb(main):008:0> Intake.where(error_code: "connected_preexisting_ep").count
[2018-04-11 12:25:22 -0400]    (2.9ms)  SELECT COUNT(*) FROM "intakes" WHERE "intakes"."error_code" = $1  [["error_code", "connected_preexisting_ep"]]
=> 4
```

We already have 4 connected EPs
