### ISSUE TITLE
Your Hearing Days | Indicate that HP should be used with Chrome

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4968]
Indicate that HP should be used with Chrome - feedback form the 508 team
## AC
1. When Hearing Prep is opened in a browser other than Chrome display the following message:

**[Browser Name] is not supported**
To access Hearing Prep, you must use Chrome as your browser.
If you need to install Chrome on your computer, please call the
VA Enterprise Service Desk at 855-673-4357.

## Mock 
**(substitute Hearing Prep for Reader)**
![image](https://user-images.githubusercontent.com/13420618/33967270-c16260ea-e030-11e7-91fb-6307297d43e1.png)

**Comment by annienguyenUSDS** [comment]
@lakohl, I think we can use similar messaging for reader if they use IE at the top of Your Hearing Days page

**Comment by Sjones352** [comment]
@lakohl currently page looks like this. 
<img width="1152" alt="screen shot 2018-04-16 at 11 32 17 pm" src="https://user-images.githubusercontent.com/23080951/38847211-7a3854c2-41ce-11e8-88e6-351b6d8a0134.png">
