### ISSUE TITLE
Fire an alert if we detect an appeal with a stay on any issue

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4969]
There are no stays currently on appeal issues, but we need to prevent attorneys from working on cases with stays.

# AC 
- If a user is loading their queue and an appeal has an issue that is a stay (The ISSUES.ISSDC will = ‘S’ if the issue is stayed), throw an error in Slack that says: “We detected a stay on an issue in a user’s queue. The appeal will not be shown to the user. We should contact the attorney and inform them. VACOLS db id: xxx, issue_sequence_id: xxx. We do not handle stays currently in Caseflow. If this error begins to appear regularly for different appeals, we should consider building UI supporting stays.”
- Don't display the appeal with the stay in the user's queue.

**Comment by laurjpeterson** [comment]
[Thread](https://dsva.slack.com/archives/C54QCEHAL/p1526418077000653?thread_ts=1526050045.000353&cid=C54QCEHAL) from slack about stays.

**Comment by laurjpeterson** [comment]
Closing because we're going to create a task for stayed appeals #11278
