### ISSUE TITLE
Consolidate the Caseflow Grays

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#4971]
Related #4958 
## Our Grays
`#323a45` - $color-gray-dark
`#5b616b` - $color-gray
`#aeb0b5` - $color-gray-light
`#d6d7d9` - $color-gray-lighter
`#e4e2e0` - $color-gray-warm-light

## Convert below to ..
$color-gray-medium `#757575` -> 
$gray-font-color  `#6b7079` ->
### random grays either in commons or in our styles
color: `#5b616b`
color: `#666666`
color: `#6b7079`
color: `#737373`
color: `#757575`
color: `#aeb0b5`
color: `#cccccc` also as `ccc`
color: `#d6d7d9`
color: `#b3b3b3`  
color: `#d9d9d9`
color: `#999999`;

**Comment by gnakm** [comment]
Reference: https://github.com/department-of-veterans-affairs/caseflow/issues/4958

**Comment by lakohl** [comment]
USWDS Grays:
`#212121` -$color-base
`#323a45` - $color-gray-dark
`#aeb0b5` - $color-gray-light

`#5b616b` - $color-gray
`#d6d7d9` - $color-gray-lighter
`#f1f1f1` - $color-gray-lightest

`#494440` - $color-gray-warm-dark
`#e4e2e0` - $color-gray-warm-light
`#757575` - $color-gray-brown

**Comment by lakohl** [comment]
@nolawi I think before you replace one of the USWDS colors in a Caseflow app it would be best to check with the designer/product owner.

**Comment by gnakm** [comment]
**Convert**:
color: `#666666`
color: `#6b7079`
color: `#737373`
color: `#757575`
->
color: `#5b616b`- $color-gray

**Convert**:

color: `#cccccc` also as `ccc`
color: `#d9d9d9`
->
`#d6d7d9` - $color-gray-lighter

**Convert**:
color: `#999999`; 
color: `#b3b3b3`
-> 
color: `#aeb0b5`- $color-gray-light
