### ISSUE TITLE
Crank up the CircleCI containers

### ISSUE THREAD

**Issue by sansb** [department-of-veterans-affairs/caseflow#4979]
Kate Brown said she was going to get us a 4 container CircleCI plan. I think we're at the point where we could really benefit from 8 or even 12 containers (4-6x parallelization with 2 concurrent builds).

I understand that we recently purchased a fairly beefy annual Travis plan. That plan would not go to waste since we still have other projects running on Travis.

This sorta blocks making CircleCI the authoritative CI since until then Circle throughput will be limited.

Assigning to @shanear to work this out.

**Comment by shanear** [comment]
@sansb We are up to 8 containers now. We can pop that up to 12 should we need it. I figured we could start at 8 and see how much wait time we are experiencing.

**Comment by sansb** [comment]
@shanear attempted

**Comment by shanear** [comment]
We made a mistake on this and now have to call Circle CI to sort it out.

**Comment by shanear** [comment]
Fixed!
