### ISSUE TITLE
Hearing Prep | Check with Justin on RO Tech Set-Up

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4989]
Check with Justin on RO Tech Set-Up   - who owns it, can we influence it? 
1. Some ROs only have one monitor
1. Quiet keyboards?

**Comment by lakohl** [comment]
According to Justin this is still the purview of the Board

**Comment by annienguyenUSDS** [comment]
Closing since we have https://github.com/department-of-veterans-affairs/appeals-design-research/issues/760 & confirmed keyboards in hearing rooms.
