### ISSUE TITLE
Marked as read | Documents that don't load should not be marked as read

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#4991]
Currently if a user opens a document (that's bolded) but the document fails to load, it's marked as read. https://github.com/department-of-veterans-affairs/appeals-support/issues/1722

We should not mark documents as read unless they actually load.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.

**Comment by pkarman** [comment]
This affects our data integrity so I'm going to re-open this one.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||
2 | |||||
3 | |||||
5 | 
8 | 
```
### Why 1?
- Existing code mostly there; maybe there's a loaded_at field we can use to check if doc loaded.

### Why 2?
- Unsure of how to tell if a document actually loaded

### Why 3?
- No familiarity with code
