### ISSUE TITLE
Cancel intake modal | Update modal to include cancellation explanation options

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5006]
This is a ticket to update the cancel modal to allow users to select a cancelation reason, which managers will be able to view in their manager queue (see https://github.com/department-of-veterans-affairs/caseflow/issues/5003).

## AC
- The "Cancel intake" modal link is available on every page after a successful search (same as today)
- Selecting "Cancel intake" navigates the user to the home page (/intake); selecting "close" closes the modal on the user's current page (same as today)
- The selected reason populates the "explanation" column on the manager page (#5003), in the format "Canceled: [selected reason]
  - An "other" option includes a freeform text input (do we want a character limit?)
- Radio button options:
  - Duplicate EP created outside Caseflow
  - System error
  - Missing signature
  - Need clarification from Veteran
  - Other (explain):
- Selecting a cancelation reason is required -- if a user tries to cancel the intake without selecting an option, display "this field is required" error

## Mocks
[See styleguide modal for design](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#modals)
![image](https://user-images.githubusercontent.com/4042181/38199911-6c343630-3660-11e8-911c-90af6c8979fd.png)

**Comment by leahbannon** [comment]
looks great!
