### ISSUE TITLE
Hearing Prep | Implement 508 guidance

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5010]
1) On the Daily Docket page the Notes form field visually appears before and to the left of Transcript Requested. With assistive technology the Notes field is read after Transcript Requested.
1) Tabs on pages such as the hearing Worksheet page with Current and Prior Issues are read as buttons for assistive technology users. Visually these elements are selectable tabs and should read the label, identify it as a tab, and indicate to a user which of the tabs is selected.
1) On the hearing Worksheet page the Save as PDF button cannot be accessed using a keyboard or with assistive technology programs. This button should be included in the tabbing order.
1) On the hearing Worksheet page, the Delete button found on the Current Issues tab cannot be accessed with a keyboard or using assistive technology programs.
1) On the Daily Docket page there are check boxes for Prep and Transcript Requested. Both of these check boxes are read as: label. This defect can also be found with all the check box selections on the hearing Worksheet page. 
1) The field label for Notes is read as: Time/RO(s) Notes. This label should read as Notes as it appears visually for the field.

# Reference
Section 508 Audit | Remediate non-conformant issues (25633) #5110

**Comment by annienguyenUSDS** [comment]
Walked through 4/13.  @sharonwarner to break down tickets with team.

**Comment by sharonwarner** [comment]
Closed because we're merging hearing prep into hearing schedule.
