### ISSUE TITLE
Search bar on the Queue list view should lead the user to the Search MVP screen

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5011]
Related to https://github.com/department-of-veterans-affairs/appeals-design-research/issues/707

Currently, the Queue list view search bar copies over Reader search functionality, and links to Reader.  We should modify the Queue search bar so that when the user searches, our new search results page is displayed.

Let's hide these changes behind a feature flag called something like `queue_appeal_search`.

# AC
- When a Queue user searches for a veteran id, the page displayed should match the mocks in the epic if the necessary feature is enabled

**Comment by lowellrex** [comment]
Completed by the work in #5108.
