### ISSUE TITLE
Queue Search List View should link to Appeal Details Screen

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5013]
Related to https://github.com/department-of-veterans-affairs/appeals-design-research/issues/707

# AC

- When a user clicks an appeal on the search results screen
  - the user should be redirected to `/appeals/:vacols_id` 
  - an appeal details screen should pop up that matches the mocks in the issue above

**Comment by lowellrex** [comment]
Completed by the work in #5108.
