### ISSUE TITLE
Screenshots on the help page are slightly out of date

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#502]
They show the `Built with <3 by the Digital Service at the VA. Send feedback` footer as centered, instead of the left/right aligned verison we have now.

**Comment by webinista** [comment]
PDFTK hangs on my machine, so I can't take an adequate screen shot of the _Review Form 8_ page. Can someone capture that for me?

**Comment by paultag** [comment]
![image](https://cloud.githubusercontent.com/assets/132447/12236588/b7b655e0-b848-11e5-8eb1-daad3dc4d495.png)

**Comment by paultag** [comment]
![image](https://cloud.githubusercontent.com/assets/132447/12237825/ade38050-b84e-11e5-9e63-a765b0e500d5.png)
