### ISSUE TITLE
Attorney Check out | When editing issues,  "Level" codes should be erased

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5033]
![issue levels not erased](https://user-images.githubusercontent.com/3781835/38213148-318af1da-368e-11e8-9e67-16de5d7794e2.gif)

# AC
- If an issue is edited & an attribute is changed, all attributes lower than that in the issue hierachy should be removed, even 
  - Ex: If "Program" is changed, then "Issue", "Level 1", "Level 2", etc should all be erased
  - Ex: If "Issue" is changed to an value that does not have diagnostic codes, all diagnostic codes should be erased

**Comment by dannysellers** [comment]
Closing. This was created before #5202, but that one gets at the issue better
