### ISSUE TITLE
Unify certification and eFolder's VBMS integration

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#504]
Currently some functionality is duplicated in Certification and eFolder. Move this logic to Caseflow-Commons.

**Comment by mogrenAtWork** [comment]
Some of this was completed in `efolder_service.rb` for #2685 

I removed unused code at the time that may be useful here in 0e24e72bfd7f52c3d9d5020eafaa82babf253d0a

**Comment by aroltsch** [comment]
All Caseflow should be using eFolder Service.

**Comment by mdbenjam** [comment]
There is still code that's running through our VBMS service on the caseflow side to get docs. We should update this to use efolder service. That way we can move everyone to the new API.

**Comment by mdbenjam** [comment]
JK Anya says there are other tickets for these.
