### ISSUE TITLE
[Backend] | Remove 'assigned' state for dispatch tasks

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5052]
On the same page load, we currently update tasks from 'unassigned' => 'assigned' => 'started'. Occasionally tasks get lost in 'assigned' status, and we get errors that they're trying to transition from 'assigned' => 'completed'. 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1099/

We should remove the 'assigned' state since we're not really getting any value out of it (tasks should never be in that state for more than a split second. 

AC:
- AASM state 'assigned' is removed from the tasks state machine

**Comment by tejans24** [comment]
@sharonwarner is the state supposed to go from :unassigned -> :started ? Do we need unassigned state if we don't have an assigned state?
