### ISSUE TITLE
Allow judges to change an appeal assignment from one attorney to another

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5053]
We need to allow judges to change an appeal assignment from one attorney to another. 

## Open Questions
- Should we use `PATCH /tasks/:task_id`? 
  - `deassign` is currently a component of the task id. And that will change when a case is reassigned. So effectively once we `PATCH`, the task id will change
- Should we do a combination of `DELETE /tasks/:task_id` and `POST /tasks`? 
  - How do we make it into a transaction? It's not acceptable for one to fail and the other to succeed.
- Should we delete a DECASS row, or just change the attributes of the existing DECASS row?

**Comment by aroltsch** [comment]
@amprokop we no longer use `deassign` to generate a task_id, we use `deadtim`. I talked to Jed, he confirmed the following steps:

```
Set deassign to a new date
Set deatty to a new attorney ID
Set deteam to the attorney's judge/attorney group name
Update the appeal's location to the attorney's location by updating the BRIEFF and PRIORLOC table
Set bfattid to a new attorney ID
```

**Comment by amprokop** [comment]
Wow! Finally, some good news 😺. Hmmm, this looks like PATCH might be the best option then. What do you think?
