### ISSUE TITLE
Dispatch | Cases with decisions uploaded to VBMS still show on the Missing Decisions page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5061]
BVA Dispatch claims that some cases with decision uploaded to VBMS, are still showing on the Missing Decisions report.

## AC
1. Check that the Decision is really uploaded to VBMS.
2. Check the the case still shows on the Missing Decisions page.
3. If both 1 & 2 are true, troubleshoot.

**Comment by sharonwarner** [comment]
Replaced by #4567
