### ISSUE TITLE
Build our own Docker images for our Circle builds

### ISSUE THREAD

**Issue by sansb** [department-of-veterans-affairs/caseflow#5062]
We should bake a Docker image with all of our dependencies pre-built. This will decrease build times.

A good solution will include a clear way to update and push new images; automation preferred. 

We'll need our images to include the browser stack Circle includes in their `ruby-browsers` line.

Circle docs on using custom Docker images- https://circleci.com/docs/2.0/custom-images/

**Comment by mdbenjam** [comment]
Plan of attack:

1) Setup a new docker registry in ECR for use with CircleCI.
1) Create credentials for CircleCI to access our ECR.
1) Create a dockerfile to build a new image for testing.
   1) The image will be based on` circleci/ruby:2.2-browsers` and will have everything in `setup-cricleci-prereqs`
   1) The image will also have Oracle Instaclient installed: http://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html. To enable us to connect to FACOLS
1) Use our Dockerfile to build and push an image to our ECR manually. In the future we can automate this if we determine that it's a common operation.
