### ISSUE TITLE
Dispatch | Oldest case in the Queue not being served up first?

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5063]
The Dispatch Coach at ARC said that to spite working over a thousand cases in the last week, the 'Oldest case in the Queue' remains the same. If Caseflow serves up the Dispatch cases to be worked in order from oldest (in Dispatch) to youngest, why is this? (I have a claim number for the oldest listed case)

**Comment by sharonwarner** [comment]
Nobody at ARC had the correct permissions to work this case. Closing in favor of #3254 which has some more information.
