### ISSUE TITLE
Make Circle builds use the same version of Ruby as dev and prod

### ISSUE THREAD

**Issue by sansb** [department-of-veterans-affairs/caseflow#5064]
Our Ruby version for dev is specified in //caseflow/.ruby-version
Our Ruby version for prod is specified in //appeals-deployment/ansible/bake-base-ami.yml

Currently dev and prod use 2.2.4 while CI uses 2.2.10 (latest in 2.2 line via Circle pre-built Docker image).

Ideally we do not create a third source of Ruby versions but not a hard constraint.

**Comment by kahlouie** [comment]
Considering the pending ruby version upgrade and the fact that @ferlatte is helping on that, I'm going to close this. :)
