### ISSUE TITLE
React Loading Button

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#507]
Add a new react component that ensures double click submitting of forms is not allowed. While submit is occuring, show fancy spinner.

Can be modeled off current jQuery version

**Comment by astewarttistatech** [comment]
**PASSED**

No double-click enabled, loading image added. Please see attached. 
![screen shot 2016-12-14 at 1 09 20 pm](https://cloud.githubusercontent.com/assets/23038505/21194788/39f20a5c-c1ff-11e6-9f51-031e9d60131e.png)

Moving this to closed.
