### ISSUE TITLE
Stylesheet Font Sizes set too many times

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#5080]
It looks like we have a lot of one-offs as far as font sizes in out styles. Here is a Iist compiled which includes USWDS/Commons and Caseflow. The number next to the size is the number of times its **set** in our css (not how many times its used)

I think we should stick format `em` and remove sizes that only have one-offs. 

font-size: .85em; 1
font-size: 0.9em; 2
font-size: 0; 1
font-size: 1.05em; 1
font-size: 1.15em; 1
font-size: 1.1em; 1
font-size: 1.1rem; 1
font-size: 1.26em; 1
font-size: 1.2rem; 1
font-size: 1.3333333333em; 1
font-size: 1.3rem; 4
font-size: 1.4rem; 1
font-size: 1.5em; 1
font-size: 1.5rem; 11
font-size: 1.6rem; 1
font-size: 1.7rem; 13
font-size: 1.9rem; 2
font-size: 10px; 1
font-size: 11px; 8
font-size: 12px; 1
font-size: 13px; 2
font-size: 15px; 4
font-size: 17px; 2
font-size: 18px; 2
font-size: 19px; 3
font-size: 1em; 3
font-size: 1rem; 1
font-size: 2.4rem; 1
font-size: 2.5rem; 2
font-size: 20px; 1
font-size: 22px; 1
font-size: 24px; 3
font-size: 2em; 3
font-size: 2rem; 6
font-size: 3.2rem; 1
font-size: 3.5rem; 1
font-size: 34px; 1
font-size: 3em;1
font-size: 3rem; 3
font-size: 44px; 1
font-size: 4em; 1
font-size: 4rem; 2
font-size: 5.2rem;2
font-size: 52px; 1
font-size: 55%; 1
font-size: 5em;1
font-size: 6rem; 1
font-size: 75%; 2
font-size: 80%; 1
font-size: 90%; 1
font-size: 9px; 2
font-size: inherit; 7
font-size: medium; 1
font-size: small; 1

**Comment by alisan16** [comment]
Closing as this is now obsolete.
