### ISSUE TITLE
Refactor cancellation modals to use Redux for state

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#5086]
Certification and Intake cancellation modals components currently use local state. Refactor them to use Redux.

Intake PR: https://github.com/department-of-veterans-affairs/caseflow/pull/5070
Certification PR: https://github.com/department-of-veterans-affairs/caseflow/pull/1506

**Comment by leikkisa** [comment]
Intake PR: https://github.com/department-of-veterans-affairs/caseflow/pull/5070
Certification PR: https://github.com/department-of-veterans-affairs/caseflow/pull/1506

**Comment by jiahuang** [comment]
I think we want to move in the opposite direction where we put more redux state into local state.

**Comment by leikkisa** [comment]
Shane wanted this at some point but I would be cool with closing it.
