### ISSUE TITLE
Create a cleaner favicon for Caseflow

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#509]
As a Product Owner, I would like the current favicon replaced and displayed on all pages in the app so that it is consistent and shows the same favicon seen within the application.

# Acceptance Criteria
1. Verify that all pages have the new [Caseflow Favicon.ico.zip](https://github.com/department-of-veterans-affairs/caseflow/files/625532/Caseflow.Favicon.ico.zip) favicon.  (refer to mockup)

### Mockup
![image](https://cloud.githubusercontent.com/assets/23063044/21317926/2a739eb8-c5d5-11e6-976b-3f835c9642bd.png)

# Related Stories

**Comment by shanear** [comment]
@KHarshawat it's gonna be difficult to change the favicon from feature to feature. Can we have one universal caseflow favicon for now?

**Comment by KHarshawat** [comment]
Yeah, I can create one.

**Comment by KHarshawat** [comment]
@shanear Please use this favicon for all Caseflow apps. I'll close the other issues.


[Caseflow Favicon.ico.zip](https://github.com/department-of-veterans-affairs/caseflow/files/625532/Caseflow.Favicon.ico.zip)

**Comment by mmlumba** [comment]
@astewarttistatech @kierachell Instructions for testing listed in above PR

**Comment by kierachell** [comment]
See [this comment](https://github.com/department-of-veterans-affairs/caseflow-commons/pull/27#issuecomment-270662683) for screenshots from `dev`

Will it work upstream?

**Comment by mmlumba** [comment]
@KHarshawat Here are the following PR's to add this favicon to the apps
Certification: https://github.com/department-of-veterans-affairs/caseflow/pull/640
efolder: https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/349
feedback: https://github.com/department-of-veterans-affairs/caseflow-feedback/pull/92

**Comment by kierachell** [comment]
I am seeing different favicons between the apps:
**Feedback** 👍 
<img width="150" alt="screen shot 2017-01-05 at 15 04 58" src="https://cloud.githubusercontent.com/assets/18075411/21695570/69d3a464-d358-11e6-8c7b-3f8933e0f4f8.png">

**eFolder** 👍 
<img width="129" alt="screen shot 2017-01-05 at 15 06 04" src="https://cloud.githubusercontent.com/assets/18075411/21695613/9c329a6e-d358-11e6-962b-bf607ccaf765.png">

**Certification** ❓ 
<img width="152" alt="screen shot 2017-01-05 at 15 06 16" src="https://cloud.githubusercontent.com/assets/18075411/21695614/9c60649e-d358-11e6-9e40-0c75276a50e2.png">

**Dispatch** ❓  (I know they're the same but just for completeness)
<img width="148" alt="screen shot 2017-01-05 at 15 06 45" src="https://cloud.githubusercontent.com/assets/18075411/21695615/9c6175f0-d358-11e6-8f5b-402f250a93d9.png">
