### ISSUE TITLE
Deleted hearings in VACOLS

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#5090]
Through the Sentry error listed below, we discovered that hearings are being deleted from VACOLS. We need to determine why, and how we should display hearing worksheets for hearings that no longer exist.

--------------------

Sentry: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/908/

NoMethodError
undefined method `hearing_venue' for nil:NilClass

def vacols_attributes(vacols_record)
      # use venue location on the hearing if it exists
      ro = vacols_record.hearing_venue || vacols_record.bfregoff
      type = VACOLS::CaseHearing::HEARING_TYPES[vacols_record.hearing_type.to_sym]...

## AC
1. Show the following error message when the judge or attorney clicks on the the link to the hearing worksheet form the Reader Cases Checked In page. 

Line 1: **No hearing held**
Line 2: **The Veteran was scheduled for a hearing, however, their case was removed from the Daily Docket before the hearing date.**

## Mock
![no hearing held](https://user-images.githubusercontent.com/4975959/39544580-85385d2c-4e1c-11e8-8de8-8602c4058025.png)

**Comment by sharonwarner** [comment]
I don't think this is related to the Rails 5 upgrade. The Sentry page says it's been happening for a few months.

When looking into the most recent error, it looks like a hearing that we're trying to access was deleted from VACOLS. I believe ROs sometimes delete hearings that were cancelled. Either way, I'll submit a PR to account for this.

**Comment by lakohl** [comment]
Have 5 cases from @sharonwarner and I'm looking into this. this week I learned about a practice of some ROs that Justin is trying to curb, but which may account for these 'orphan' worksheets. 

It sounds like the Veteran may have postponed their hearing. But, the RO, instead of marking the Veteran as postponed, deleted the Veteran from the Daily Docket.

**Comment by lakohl** [comment]
@sharonwarner 
Checking my assumption... when we pull a Veteran/case onto the Daily Docket we are making the assumption that hearing will be held. So any case deleted from the Daily Docket would produce an 'orphan' hearing worksheet. Is that correct?  (If so, this might explain why some ROs use spreadsheets to schedule Veterans before they input them in VACOLS.)

**Comment by lakohl** [comment]
Left a message for the Hearing Coordinator at the RO in Winston Salem, Jason Britt and for two hearing coordinators at the Muskogee, RO: Thomas Youell and James Grady.

**Comment by lakohl** [comment]
I was able to get Dustin to look up some cases where the hearing disappeared. 

1. TB hearing  scheduled for March 2018 - No Show. BVA Decision April 2018: All issues were withdrawn.
2. Video hearing held in Dec 2017. Case is in remand status.
3. Two active AOD appeals. Video hearing held in Dec 2017 
4. Video hearing scheduled for Feb 2018 - No Show
5. No hearing info. BVA Decision April 2018: All issues withdrawn.

**Comment by lakohl** [comment]
For now, let's show this error message when the judge or attorney clicks on the the link to the hearing worksheet form the Reader Cases Checked In page. @annienguyenUSDS could you take a  👀to see if you think this error message works?

Line 1: **No hearing held**
Line 2: **The Veteran was scheduled for a hearing, however their case was removed from the Daily Docket before the hearing date.**

![no hearing held](https://user-images.githubusercontent.com/4975959/39473931-682236ca-4d1f-11e8-8e88-16bb853c8f3b.png)

**Comment by annienguyenUSDS** [comment]
Update Line 2: **The Veteran was scheduled for a hearing, however, their case was removed from the Daily Docket before the hearing date.**

**Comment by lakohl** [comment]
@tejans24 You may need to do this ticket first: https://github.com/department-of-veterans-affairs/caseflow/issues/5379
