### ISSUE TITLE
Fix NameError in app/models/judge.rb

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#5091]
Sentry: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1115/

NameError: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer

def list_all
      Rails.cache.fetch("#{Rails.env}_list_of_judges_from_vacols") do
        repository.find_all_judges ...

**Comment by aroltsch** [comment]
I was able to reproduce locally:

start rails console pointing to Facols
```
rails c -e local
```

Run:

```
[1] pry(main)> Judge.list_all
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer
```
