### ISSUE TITLE
Run a VACOLS UI integration test

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5097]
## Context

We should run a VACOLS integration test with the UI before launching the Attorney checkout flow to ensure backwards compatibility.

This test does not have to test every detail and edge case, it should just act as a smoke test for the following parts of attorney checkout:
- OMO request creation
- remand reason editing
- issue add/edit/delete
- draft decision creation
- assignment from attorney to judge

We need an environment where Caseflow connects to VACOLS DB and the VACOLS UI is running connected to the VACOLS DB. This is probably UAT.

## Testing Steps
1. Log in with Caseflow in UAT and find an attorney with current case assignments
1. Log into the VACOLS UI as the same attorney
1. Go through the VACOLS DAS attorney checkout flow for a case and create an OMO request
1. Go through the Caseflow attorney checkout flow for a case and create an OMO request
1. Log into the VACOLS UI as the judge those cases were assigned to
1. Examine the two assignments to the judge — are both cases visible? does everything look the same?  
1. Log into VACOLS UI and Caseflow as an attorney again
1. Start a draft decision flow in Caseflow and add an issue.
1. Reload the VACOLS UI — do we see the issue with all expected params? Are the added at/modified by fields correct?
1. Start a draft decision flow in Caseflow and edit an issue
1. Reload the VACOLS UI — do we see the issue with all expected params? Are the added at/modified by fields correct?
1. Start a draft decision flow in Caseflow and delete an issue
1. Reload the VACOLS UI — is the issue now missing? Are the added at/modified by fields correct?
1. Start a draft decision flow in Caseflow and add an issue, mark an issue as vacated & for duplication, add remand reasons, and check out the issue to a judge
1. Do the same in the VACOLS UI as an attorney
1. Log into the VACOLS UI as a judge — are all expected parameters present?

**Comment by amprokop** [comment]
## Outcomes

Ran through the scenarios mentioned above, minus the ones where we create OMO requests in VACOLS, which didn't seem worth it once we were testing.

A few notes:

1. The vacols UI (not DB) requires grant reasons — so if an issue is granted, previously the attorney would have had to specify a grant reason before pushing the case to the judge. Now, if an issue is granted, everything works fine except that the judge will have to select a grant reason in the VACOLS UI before moving the case to dispatch. Thinking of asking Jed to remove the validation.

2. Discovered a remand reasons bug: https://github.com/department-of-veterans-affairs/caseflow/issues/5290

3. Found that when navigating to some appeal details screens on preprod, it crashes prod: https://github.com/department-of-veterans-affairs/caseflow/issues/5285

**Comment by amprokop** [comment]
Those were the only problems we found!

**Comment by laurjpeterson** [comment]
Closing! 
- Alex completed this integration test and we released attorney check out to 3 attorneys on 5/3. 
- Jed removed the validation for grant reasons. 
- Remand reasons bug: #5290 has been resolved
- Found that when navigating to some appeal details screens on preprod, it crashes prod: #5285 - ticket still open
