### ISSUE TITLE
Hearing Worksheet | Fix formatting on the Print/Save as PDF version

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#5098]
As a judge, I would like to be able to see as much as possible of the Hearing Worksheet on one page. 
When printing/save as PDF view, the note boxes are printing on the page 2 and a lot of white space is on Page 1. This happens in both demo and UAT. We heard this feedback from users as well.

Recent updates to Caseflow Commons have wreaked a bit of havoc on the Print view so this ticket will also address those.

## AC
1. Remove any automatic page breaks... e.g. The Hearing Summary section should be right below the Issues section, not pushed to Page 2.
<img width="625" alt="screen shot 2018-04-06 at 3 34 40 pm" src="https://user-images.githubusercontent.com/22620270/38440705-448da3d4-39b0-11e8-8e36-392c4b50aef7.png">
<img width="505" alt="screen shot 2018-04-06 at 3 34 16 pm" src="https://user-images.githubusercontent.com/22620270/38440716-4cc3ca9c-39b0-11e8-9c37-b279454bed0f.png">

**Update/fix the .pdf formatting to reflect the following:**
2. [Veteran FirstName LastName’s] Hearing Worksheet = h1
<img width="621" alt="screen shot 2018-06-07 at 4 49 25 pm" src="https://user-images.githubusercontent.com/4975959/41125545-c51e3d90-6a72-11e8-8536-46073c9e3212.png">
3. Labels in all caps should be ~ 1/3 smaller than the item it is labeling
<img width="167" alt="screen shot 2018-06-07 at 4 48 08 pm" src="https://user-images.githubusercontent.com/4975959/41125495-a22d2544-6a72-11e8-90c4-0e719ad826ac.png">
4. Veteran/Appellant Information and Hearing Summary = h2 (see previous screenshot)
5. Veteran/Appellant Information and Hearing Summary = h2 (see previous screenshot).
<img width="100" alt="screen shot 2018-06-07 at 5 23 49 pm" src="https://user-images.githubusercontent.com/4975959/41127045-9060b8f8-6a77-11e8-8bf2-7b13159ddfbe.png">
6. Shrink the type on 'Representative Name', 'Witness...', and 'Periods and...' to be the same size as 'Procedural History' and 'BVA Decision'.
<img width="502" alt="screen shot 2018-06-07 at 5 24 13 pm" src="https://user-images.githubusercontent.com/4975959/41127060-9e64a4c8-6a77-11e8-9b58-bb3ff344ce2d.png">
7. More space is required between some rows above Procedural History in order to ensure a clear relationships. e.g in the screenshot below more space is needed between the 'Ewald D. Buckridge' (appellant name) and the label 'Representative Name' because they are not related.
<img width="304" alt="screen shot 2018-06-07 at 4 56 40 pm" src="https://user-images.githubusercontent.com/4975959/41125959-fbde21e6-6a73-11e8-86da-df0c0cac8635.png">
<img width="576" alt="screen shot 2018-06-07 at 5 01 21 pm" src="https://user-images.githubusercontent.com/4975959/41126102-6e927cfa-6a74-11e8-81c8-0380b232cea4.png">
8. Remove the box around and icon next to the Veteran ID.
<img width="435" alt="screen shot 2018-06-07 at 5 19 19 pm" src="https://user-images.githubusercontent.com/4975959/41126853-f19895e2-6a76-11e8-8a77-7ca7d5b8ef19.png">
9. Remove empty space between elements.
<img width="657" alt="screen shot 2018-06-07 at 4 59 19 pm" src="https://user-images.githubusercontent.com/4975959/41126052-42cde726-6a74-11e8-96f8-84464f912170.png">
10. In the Procedural History section, tighten the spacing between Appeal Stream 1 and the first BVA decision date so that it is the same as that between 'BVA Decision' and NOD.  
<img width="526" alt="screen shot 2018-06-07 at 5 09 03 pm" src="https://user-images.githubusercontent.com/4975959/41126461-93cd6ce0-6a75-11e8-9860-feaa5f1ff597.png">
11. Hide the Procedural History 'box' and expand/collapse icon.
<img width="526" alt="screen shot 2018-06-07 at 5 09 03 pm" src="https://user-images.githubusercontent.com/4975959/41126461-93cd6ce0-6a75-11e8-9860-feaa5f1ff597.png">

_**Current**_
<img width="1032" alt="screen shot 2018-06-06 at 10 40 12 pm" src="https://user-images.githubusercontent.com/4975959/41127100-c5e15d34-6a77-11e8-854e-07797a42e2fc.png">

_**Desired**_
<img width="663" alt="screen shot 2018-06-07 at 5 25 54 pm" src="https://user-images.githubusercontent.com/4975959/41127128-dd189fee-6a77-11e8-80b4-5e3eafa7b94f.png">

**Comment by lakohl** [comment]
@Sjones352 @sharonwarner because our priority is to make the .pdf as compact as possible, we should remove any page breaks.
