### ISSUE TITLE
What should we do with patterns that we're building, but not yet using?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#510]
In #438, for example, I'm building a tabbed pattern that will eventually be used for the [Form 8 Questions page](https://github.com/department-of-veterans-affairs/caseflow/issues/332#issuecomment-165923202), but isn't being used yet. Similarly, the `help_text` partial (#470) is there but not being used.

What's the best place for these patterns so that they're available for testing, review, and demonstration?

**Comment by paultag** [comment]
Hurm, good question. I'm not quite sure what's idiomatic here. I'd say some example HTML somewhere that shows the basics of usage? What are your thoughts?

**Comment by webinista** [comment]
I think a separate repo would be good, because these patterns separate from the app. But creating our own Caseflow pattern library feels a little like overkill.

**Comment by shanear** [comment]
what do you mean by pattern here? the css & raw html?

**Comment by webinista** [comment]
Yes, so that it can be tested without actually adding it to Caseflow.

**Comment by shanear** [comment]
I say just add a controller route and a view and use a `Rails.env.development?` flag to block it off in prod.

**Comment by webinista** [comment]
Closing. Will add these patterns to Roadrunner.
