### ISSUE TITLE
Hearing Worksheets | Reference Measurements for new layout

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5101]
For reference, this mock includes measurements for the new Hearing Worksheet Layout.

**Mock**
![hearing worksheet new top5 measurements](https://user-images.githubusercontent.com/4975959/38472336-830050a6-3b4c-11e8-8126-066f95524a17.jpg)

**Comment by lakohl** [comment]
@Sjones352 I'd like to use this ticket to work with you on tightening up the spacing on the Hearing Worksheet next week.

**Comment by Sjones352** [comment]
@lakohl that's fine. Let's do that.
