### ISSUE TITLE
Intake Bug | Prevent double intake create race condition on the back end

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5104]
Like with https://github.com/department-of-veterans-affairs/caseflow/issues/5105, we mitigate against the risk of double clicking the search button by disabling it, but we found that it's not preventing all double requests.

<img width="981" alt="screen shot 2018-04-16 at 9 48 05 pm" src="https://user-images.githubusercontent.com/1596259/38844203-6982ef92-41c0-11e8-869c-898fcb9d6fe1.png">

We should be preventing these on the back end.

**Comment by leahbannon** [comment]
works for me!
