### ISSUE TITLE
Intake Bug | Prevent cancellation on the back end if the ramp election is established

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5105]
Even though we mitigate the problem by disabling the cancel button on the front-end, there's still a race condition where users can cancel a intake while it's being completed. We should make this impossible on the back end.

**Comment by leikkisa** [comment]
Double check

**Comment by leikkisa** [comment]
For the cancellations, if the user refreshes the page while the intake is being completed, then they can cancel it.
