### ISSUE TITLE
RAMP opt-in | Only close appeals with NOD date before opt-in receipt date

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5115]
Currently if a Veteran opts in to RAMP, we're closing all eligible VACOLS appeals at the time of intake. This is a problem because a Veteran can start a new (legacy) NOD in the time between when VA receives the opt-in and when VA actually processes the form. So, we should close the Veteran's valid VACOLS appeal(s) with an NOD date before the election receipt date.

## Acceptance Criteria
- Validate that the NOD date is earlier than the opt-in election receipt date before closing the VACOLS record - only close appeal(s) with NOD dates prior to receipt date

**Comment by leahbannon** [comment]
This was reversed by #5681 so I'm closing it
