### ISSUE TITLE
EndProduct.claim_date should be a Date and not a DateTime

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5121]
Claim date should be represented as a date and not a DateTime.

**Comment by kahlouie** [comment]
Is this already true? I think we're storing it in the db as a Date, not a DateTime. Can we close this?

**Comment by shanear** [comment]
If it is true, then we shouldn't have to convert it to a date everywhere we use it and need it to be a date:

Here's an example:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/end_product.rb#L81

But my guess is that it isn't always true since we are converting it to a date whenever it's used.
