### ISSUE TITLE
RAMP election | Allow some ACT appeals to opt into RAMP

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5130]
Currently, we prevent all activated cases from opting into RAMP. However, the Board and VBA would like to allow certain activated appeals to opt into RAMP - specifically those that meet all of the following criteria:
- have a docket date 2016 or later
- have not had a hearing
- are not in AOD (advance on docket) status
- are not CAVC cases

## Logic
> have a docket date 2016 or later

`BFD19 >= date '2016-01-01'`

> have not had a hearing

If we assume VACOLS is always correct, this should be:

`BFHA is null or BFHA not in ('1', '2', '6')`

But I will check with Jed whether we should implement a more rigorous check.

> are not in AOD (advance on docket) status

We have already built logic for this at `Appeal#aod`.

> are not CAVC cases

`BFAC <> '7'`

**Comment by abbyraskinUSDS** [comment]
@cmgiven could you weigh in on the logic/complexity here? We don't need this urgently, but sometime in the next couple weeks would be great, if feasible.

**Comment by cmgiven** [comment]
> have a docket date 2016 or later

`BFD19 >= date '2016-01-01'`

> have not had a hearing

If we assume VACOLS is always correct, this should be:

`BFHA is null or BFHA not in ('1', '2', '6')`

But I will check with Jed whether we should implement a more rigorous check.

> are not in AOD (advance on docket) status

We have already built logic for this at `Appeal#aod`.

> are not CAVC cases

`BFAC <> '7'`

**Comment by leikkisa** [comment]
@cmgiven 
Hi Chris! We are wanting to set up some test data in UAT for validating this issue for one of our 10 RAMP veterans. Would you be able to help me figure out what I need to do to get that set up?

**Comment by cmgiven** [comment]
Sure thing. You have an hour to pair sometime tomorrow?

**Comment by leikkisa** [comment]
@cmgiven Yes, that would be great! I'm pretty free all day (West coast time)

**Comment by shanear** [comment]
This has been deployed for months. We can assume it's working correctly
