### ISSUE TITLE
Judge check out | Send to next team from their queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5149]
After a judge finishes reviewing a decision and signs it electronically (outside of Caseflow), they want to send it to be dispatched from the Board, so the Veteran can receive their decision.

After the judge reviews an attorney's drafted OMO request, they want to send it to the Outside Medical Opinion team for processing.

## AC
- Verify that judges have an 'Actions' column in their Review Cases table with a drop down.
- Verify that there the judge can select `Ready for dispatch` and `Assign to OMO` from that drop down.
- Verify that when the judge selects `Ready for dispatch`, they navigate to the Review Dispositions screen. 
- Verify when the user selects 'Assign to OMO':
   - the case is moved to VACOLS location 20
   - the case is removed from their queue
   - the OMO confirmation message appears at the top (#5152). 

## Mocks
![queue base table dropdown](https://user-images.githubusercontent.com/23316107/39930267-41af9e88-5508-11e8-904e-d29c0360c977.jpg)

**Comment by Chingujo** [comment]
@laurjpeterson 

Screen updated
