### ISSUE TITLE
Improve the date widget experience

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#515]
Default closed and open states for the date input type in Chrome.

<img width="478" alt="screen shot 2016-01-12 at 2 07 02 pm" src="https://cloud.githubusercontent.com/assets/354277/12273788/c71ad892-b935-11e5-98a5-41ebffa22e24.png">

<img width="522" alt="screen shot 2016-01-12 at 2 06 33 pm" src="https://cloud.githubusercontent.com/assets/354277/12273778/b6833cf4-b935-11e5-8121-864e4c0c3a22.png">

What it looks like when jQuery UI is enabled (this is in Firefox, but it works the same in IE 11).

<img width="576" alt="screen shot 2016-01-12 at 2 07 36 pm" src="https://cloud.githubusercontent.com/assets/354277/12273805/d8f9fc1e-b935-11e5-9aa7-fb0804b60400.png">

What it looks like in Microsoft Edge (latest browser version). Closed:
<img width="478" alt="screen shot 2016-01-12 at 2 09 40 pm" src="https://cloud.githubusercontent.com/assets/354277/12273873/31fbe73c-b936-11e5-9276-834226ca7971.png">

Open:

<img width="478" alt="screen shot 2016-01-12 at 2 11 09 pm" src="https://cloud.githubusercontent.com/assets/354277/12273925/67df4f74-b936-11e5-9d1b-ab5a44c1cfcb.png">

**Comment by orischwartz** [comment]
Superseded by #574, #588
