### ISSUE TITLE
FACOLS should use the real PowerOfAttorneyRepository

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5150]
See `Fakes::Initializer.load`. In that file, we'll probably have to move  `PowerOfAttorney.repository = Fakes::PowerOfAttorneyRepository` into the conditional, then ensure we use the fake version of BGS.

# AC
- In the `local` env running FACOLS, BGS should be faked out, but we should use the local FACOLS copy.

**Comment by laurjpeterson** [comment]
@lowellrex - i see a PR of yours has been merged here. can this ticket be closed?
