### ISSUE TITLE
Judge check out | Evaluate decision

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5151]
After a judge reviews a decision and confirms issue dispositions, judges are required to evaluate the quality of the attorney's decision for their performance evaluation. 

Judges will get to this screen in a few ways:
- If there are no remanded issues, directly after the 'Review dispositions' screen
- If there are remanded issues, directly after the 'Select remand reason(s)' for the last remanded issue.

### Header area 
- Verify that the title of the Page follows the following convention: Evaluate Decision - Veteran Name
 - Underneath the title in body text verify the following: 
    -  Counsel: Counsel Name
    - Document ID: Document ID associated with the decision 
- Verify that they are three horizontal sections (see mock)
  - Case details:
    - Docket number: 
    - Number of issues: 
    - Number of documents
   - Timeliness: 
     - Date assigned: 
     - Decision submitted: 
     - Calendar days worked: 
   - Attorney Notes: This is pulled from the notes field in the attorney check out flow submit page 
- Verify that there is a horizontal line separating the header and the body area 
### Body area
- Verify that the following question is displayed: "How would you rate the overall complexity of the case?" Underneath this question should be the following three circles (these options are blank by default): 
  - Easy
  - Medium
  - Hard
- When the judge makes a selection, the final complexity rating in VACOLS should be updated. The initial complexity rating can remain untouched.
- Verify that the next question is How would you rate the overall quality of this case? With the following options (these options are blank by default): 
  - 5 - Outstanding
  - 4 - Exceeds Expectations
  - 3 - Meets expectations
  - 2 - Needs improvement 
  - 1 - Does not meet expectations 
  - If a user chooses quality rating 1 or 2, the following note displays: 
     - Please provide more details about the quality of work below. If none of the below apply, please add your thoughts in the comments box below. 
     - There is no error state
- Verify that they are two horizontal sections after the quality question with the following titles: 
   - Where there any factors not considered?
   - Where there any areas of improvement? 
   - Please see mock for the options
- Verify that there is a comments section titled Additional factors affecting complexity and quality

### General notes
- Calendar days worked = Decision submitted - Date assigned
- The default state of the complexity and quality states is that no buttons are selected
- There is no error state if the user does not select a box after a 1 or 2 is selected
- Please follow the navigation patterns in the attorney check out flow

## Mocks
_See most recent comment_

**Comment by Chingujo** [comment]
@laurjpeterson 

Completed/revised AC and added general notes and mocks. Lmk if you see any concerns

**Comment by mkhandekar** [comment]
I will wrap this up, provide designs and drop screenshots [here](https://docs.google.com/presentation/d/1jOmWsMjYlmc83PkJ-mVGFU1lcilXgMP8mD1uaBGv42k/edit?usp=sharing) for @laurjpeterson

**Comment by mkhandekar** [comment]
These screens contain adjustments to match the design team's conversation in [murally](https://app.mural.co/invitation/mural/workqueue2001/1525197080534?sender=phillipjo4517&key=83519e8e-200e-4b1b-bce7-0acc8bea0ef8).

### The changes are:
- I recommend changing the drop down option that says either "Assign to Dispatch" or "Sign Decision" to "**Review and finish decision**" to make it more clear that it's not an immediate assignment, and they are not electronically _signing_ anything. _Review and finish decision_ more clearly communicates that they need to go through a few evaluation / review steps to eventually finish the decision that the attorney started.
- Incorporation of the new design of case snapshot (header area) @lowellrex has already implemented a majority of this. Would it be possible to bring his work over on this screen?
  - One **open question** for us to learn about is whether both **date assigned** and **decision submitted** data points are both needed. We will leave these in for now, but may want to remove these based on future usability testing. If we do remove these, we will need to make sure that this data is written back to VACOLS for attorney performance evaluation reporting (per @laurjpeterson)
- Evaluation questions live under 3 sections, separated by a horizontal line: **complexity of case**, **quality of work** and **additional comments**, for more easeful scanning and entering of information, and to make it easier for us to call out specific sections in the case that the judge enters a 1 or 2 under quality of work.
- Incorporation of the new USWDS alert style, that appears when the judge enters a 1 or 2 under quality of work. I believe @nolawi has already implemented these, but please update us if not!

---
### A note on page / step titles
We need to do more work re: where to place page / step titles if we are going to incorporate the case snapshot on this screen (and potentially other screens). As a first pass, **Evaluate decision** is below case snapshot. But @dannysellers if you want to continue with having the page / step title at the very top, for now, please do, and we can revisit soon.

---

## Evaluate decision - choose 3-5 under quality of work
![image](https://user-images.githubusercontent.com/1598889/41051167-55a29258-6983-11e8-8337-d33ffa09a957.png)

---

## Evaluate decision - choose 1-2 under quality of work

![image](https://user-images.githubusercontent.com/1598889/41051303-b87fa0fa-6983-11e8-9ad0-73361f255d6e.png)

---

## Evaluate decision - choose 1-2 under quality of work, then, attempt to **finish case** without providing details about their evaluation

![image](https://user-images.githubusercontent.com/1598889/41051342-d844ec60-6983-11e8-95e0-737e26511787.png)

**Comment by sneha-pai** [comment]
**Question**: What's the relationship between the case snapshot's action dropdown and the evaluate decision area?

**Comment by nolawi** [comment]
@mkhandekar the updated USWDS styles are not in prod yet. They will be in about 2 sprints.

**Comment by laurjpeterson** [comment]
@mkhandekar - I confirmed requirements with Chief Cherry Crawford.

1) She would like to keep date assigned to attorney, date submitted to judge, and total days worked on this screen for the judge to see.
    - These fields are on the VACOLS 'Cases currently charged to [x user]' report.
    - These fields are *not* on the reports they use to evaluate attorneys. (Timeliness is measured by beating, meeting, or missing the deadline that the judge assigned to the attorney - the deadline field is not affected by this screen)

2) The two questions - factors not considered and areas for improvement - should be combined into one question. She thinks just the question "Were there any areas for improvement?" suffices. 
   - If the judge rates the case a 1 or 2 in overall quality, they are required to select at least one of the 11 checkboxes. 
   - The single question will add clarity to the Required completion error. We can just have "Required" after the one question, so it is clear the user only has to select one of the eleven, not one from each column.

**Comment by mkhandekar** [comment]
@laurjpeterson _thank you_ for tracking down those answers and feedback _so_ fast!

**Comment by mkhandekar** [comment]
How's this for consolidation of those two sections? 

![image](https://user-images.githubusercontent.com/1598889/41117267-89c39942-6a5a-11e8-8b55-9c43c85ee478.png)

**Comment by mkhandekar** [comment]
Based on the changes from LP and discussions with the team, here are the updated screens:

## Evaluate decision - choose 3-5 under quality of work

* Cleaner / more standard case snapshot (cc: @lowellrex)
* Case timeliness as part of page content instead of within case snapshot. I still believe this is case data that would be better housed under case snapshot, but I'd love to explore case details and check out flows more thoroughly first.

![image](https://user-images.githubusercontent.com/1598889/41166727-050a19e6-6b0f-11e8-9bdf-5efcafa1c708.png)

## Evaluate decision - choose 1-2 under quality of work

* Informational alert shows up right above **areas for improvement** 

![image](https://user-images.githubusercontent.com/1598889/41166759-19b03948-6b0f-11e8-8120-e75378452798.png)

## Evaluate decision - choose 1-2 under quality of work, then, attempt to finish case without providing details about their evaluation

* Informational alert stays above **areas for improvement** 
* Additional form error shows up if a user clicks finish decision before choosing an area for improvement

![image](https://user-images.githubusercontent.com/1598889/41166762-1ced861a-6b0f-11e8-8a65-0d16f65725e2.png)
