### ISSUE TITLE
Judge check out | OMO confirmation screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5152]
After a judge has assigned a case to OMO, they need to see a confirmation screen that the case has been sent to then next team. 

## AC
- After a judge selects 'Assign to OMO' from the dropdown, the confirmation banner appears at the top of their table.
- Copy: 
  - Title: You have successfully submitted an OMO for [Veteran First Name] [Last name]
  - Body: If you need to make any changes, please manage this case in DAS.

## Mocks
![queue confirmation omo](https://user-images.githubusercontent.com/23316107/39930156-ee312d08-5507-11e8-9f9d-09097ebc7223.png)

**Comment by Chingujo** [comment]
@laurjpeterson Mock with copy. We can make it more humanistic if necessary.
