### ISSUE TITLE
Judge check out | Decision confirmation screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5153]
After a judge has finished the 'Evaluate Decision' screen and submitted the case, they need to see a confirmation screen that the case has been sent to then next team. 

## AC
- After a judge selects 'Submit' on the Evaluate Decision screen, they are taken back to their table:
   - the case is assigned to team 31 or 32 TODO - goal: all cases are sent to location 30
   - the case is no longer listed in the table
   - the confirmation banner appears at the top of the table.
- Copy: 
- Title: Thanks for reviewing Vera Marshall's decision
- Body: If you need to make any changes, please manage this case in DAS.

## Mocks
![queue confirmation banner dispatch](https://user-images.githubusercontent.com/23316107/39928778-41bf305e-5504-11e8-966f-819fac3e5c0f.png)

**Comment by Chingujo** [comment]
@laurjpeterson mock added with updated copy
