### ISSUE TITLE
Manager Dashboard: Only show in progress appeals under "Current"

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#516]
As a manager, I want to see what the caseworkers I am managing are working on. This list shouldn't be long, so there is no need for a search bar.

### Acceptance criteria
- Verify that all appeals that are currently in progress are displayed in the list under "Current"
- Verify that the name of the caseworker assigned to each task is displayed in the "Worked By" column
- Verify that there is no search bar associated with that list.

### Current state
<img width="1034" alt="screen shot 2016-12-02 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/1596259/20930787/c276e7e4-bb9c-11e6-8f5e-1c0a227285c4.png">

### Sub-tasks

- [ ] Start saving first and last names of users logging in. (database structure change)
- [ ] QA Manual testing

**Comment by joofsh** [comment]
@shanear Acceptance criteria says we should be displaying username (but we probably mean name?). Does CSS have an API for retrieving that information? Otherwise we'd have to start saving user names in our DB, duplicating sources of truth

**Comment by astewarttistatech** [comment]
"Worked by" column is still not populated with any user data. 

Please see attached. Moving this back to current sprint. 
<img width="634" alt="screen shot 2016-12-14 at 11 42 34 am" src="https://cloud.githubusercontent.com/assets/23038505/21191271/9ad7ad8e-c1f2-11e6-95cc-fa4f7d7e39f9.png">
