### ISSUE TITLE
AMA intake | Cancel intake modal: update cancellation reasons

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5166]
When a user selects "cancel intake" they see a cancellation modal with some pre-defined reasons, and the ability to write in a reason. 

The cancellation reasons were created for RAMP, and prior to an early applicability pilot, they should be revisited to make sure they apply to AMA.

In addition, these reasons populate a manager page. Does anyone look at this page? Is there any way to make it better?

**Comment by alisan16** [comment]
Closing as this is now obsolete.
