### ISSUE TITLE
AMA intake | Establish SC End Product

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5168]
This story covers the technical step of creating a Supplemental Claim End Product for rated issues in the National Work Queue.

## Acceptance Criteria
- When a user selects the **Establish claim** button on the "Finish" page, we create the End Product associated with that type of review. 
  - EP code 040 for Supplemental Claims (rated)
- Establish the EP in the National Work Queue (station 499)
- For now, we're only establishing rated EPs (non-rated will be covered in a later story)
- Create a record of it in the database

**Comment by abbyraskinUSDS** [comment]
@shanear i don't know the exactly claim codes/labels - is that something you can find out in prod, or need me to ask?

**Comment by shanear** [comment]
@abbyraskinUSDS I could probably find them in prod, but I think we should ask to confirm.

**Comment by shanear** [comment]
turns out the reason Leah can't do this in UAT is because the ep code is wrong. Need to fix that

**Comment by shanear** [comment]
040SCNR    Supplemental Claim Non-Rating
040SCNRPMC    PMC Supplemental Claim Non-Rating
040SCR    Supplemental Claim Rating
040SCRPMC    PMC Supplemental Claim Rating
040SCRRAMP    RAMP - Supplemental Claim View

**Comment by shanear** [comment]
<img width="577" alt="screen shot 2018-05-24 at 2 59 40 pm" src="https://user-images.githubusercontent.com/1596259/40505726-2664f0d2-5f63-11e8-8322-b8f437635ea0.png">

**Comment by leahbannon** [comment]
This looks good, but for now we're still establishing EPs in ARC since NWQ isn't ready yet. I created issue #5928 to track this.
