### ISSUE TITLE
Manager's Home:  Work History:  No "Worked By" values being displayed

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#517]
"Worked By" column should be filled in with the User ID of the user who the task was assigned to when it was completed.

<img width="979" alt="screen shot 2016-12-02 at 7 35 36 pm" src="https://cloud.githubusercontent.com/assets/1596259/20854997/8e46ee20-b8c6-11e6-9f0d-8c5c02d1db0e.png">

### Sub-Task

- [ ] Has to occur after #516 
- [ ] QA Manuel

**Comment by joofsh** [comment]
@shanear I assume you mean the css_id (not our internal user id)? Does that have any meaning to a manager?

**Comment by sharonwarner** [comment]
This was fixed in a previous PR.

**Comment by astewarttistatech** [comment]
**PASSED** 

Please see attached. 
<img width="652" alt="screen shot 2016-12-15 at 2 59 48 pm" src="https://cloud.githubusercontent.com/assets/23038505/21240006/660384b2-c2d7-11e6-8b0f-4817fa38dc78.png">
