### ISSUE TITLE
AMA intake | Finish: select from previously rated AMA issues (NOD)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5172]
As a Board Claims Assistant, I want to see a list of previously rated issues so I can accurately establish an AMA appeal.

## Acceptance Criteria
If a user has selected one of the 3 board lanes in the previous step:
- The list of rated issues includes issues from each decision made within 370 days (1 year + 5 day buffer) of the form's Receipt Date, entered in the previous step
- Each decision includes an "Award date" (promulgation date) and any rated issue(s) from that decision
- Issues list is sorted newest to oldest award date
- Users can select any combination of issues on this page, but must select at least one issue - the "Establish appeal" button is disabled until at least one issue is selected
- Title includes the Veteran's name
- The title includes the type of review - Notice of Disagreement (VA Form 10182)
- The button says "Establish appeal" 

Out of scope:
- We are developing the non-rated tab in another story; for now, the tab is present but selecting it doesn't do anything (developed in #5167) 
- "Establish appeal" button doesn't do anything yet 
- "Cancel intake" button is the same as RAMP for now (changes developed in #5166 )

## Mocks
![image](https://user-images.githubusercontent.com/4042181/39487723-26223c00-4d4e-11e8-92c7-4d13f7840448.png)

## Copy
Body: Select or enter all the issues that best match the Veteran's request.

**Comment by leahbannon** [comment]
Does "or enter" in the copy indicate there's a free text field where they can create new ones?

**Comment by abbyraskinUSDS** [comment]
Yeah, for the non-rated tab (which hasn't been developed)

**Comment by leahbannon** [comment]
This looks good except for 2 things:
1. There's a date issue we need to fix - #5927
2. Once that bug is fixed, we'll want to test the year+5 timeliness

**Comment by shanear** [comment]
@leahbannon this was merged: #5927

so this one should be ready to validate.

**Comment by leikkisa** [comment]
This can be validated with: 888451290

**Comment by suzchap** [comment]
LGTM (date criteria tested as part of #5927)
