### ISSUE TITLE
Judges | Assign cases | Assign to 'Other'

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5174]
Allow the judge to search for Other users, when they are not assigning a case to someone on their team.

## AC

- Verify that when the user chooses 'Other' from the drop down, they have a text box to enter the name of an attorney or judge.
- Copy:
- Error state: When the user types in an attorney or judge that is not at the Board, they should receive an error.

## Mocks

**Comment by evankroske** [comment]
@sneha-pai, in the design of the assign widget, how important is it to put the attorneys on the judge's team in a separate dropdown from the other attorneys? It would be much easier for me to implement and maintain this feature if I could use just one dropdown. The attorneys on the judge's team would appear above other attorneys, so judges wouldn't have to search. What do you think about this change to the design?

**Comment by sneha-pai** [comment]
@evankroske This is an excellent and efficient idea. Would it be possible to show any kind of visual cue in the dropdown, to differentiate the judge's attorneys from other attorneys? (Bolding, different colors, etc)

**Comment by evankroske** [comment]
@sneha-pai , sure! I could put a blank between attorneys on the judge's team, or I could simulate a horizontal rule with a bunch of em dashes: `—————`. Would that work from a design perspective?

**Comment by mkhandekar** [comment]
Nice! Wondering if we could also **title** the two sections, kinda like this? 

<img width="132" alt="screenshot 2018-07-09 15 16 20" src="https://user-images.githubusercontent.com/1598889/42478839-0fa8ad9c-838b-11e8-8f83-34855992979c.png">

**Comment by evankroske** [comment]
@mkhandekar, sorry, but [the select widget we're using](http://jedwatson.github.io/react-select/) doesn't support sections, and I don't think that adding support would be feasible.

**Comment by evankroske** [comment]
@mkhandekar, I was wrong; react-select does support sections. I'm going to label each section with the judge's name, OK?

**Comment by mkhandekar** [comment]
@evankroske sounds good! can you drop in a screenshot of what that looks like (here or the eventual PR)?
