### ISSUE TITLE
Judges | Assign cases | Reassign cases from one attorney to another

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5177]
Judges may have to reassign a case from one attorney to another attorney. This should largely follow the same pattern as assigning cases to attorneys for the first time. 

## AC
- Verify that when a judge is viewing an attorney's queues, the 'Assign to' column's dropdowns are all populated with that attorney's name
- Verify that the judge can click the dropdown, and the list of attorneys on their team displays
- Verify that the judge can select another attorney from the list

## Mocks

**Comment by evankroske** [comment]
Fixed by https://github.com/department-of-veterans-affairs/caseflow/pull/6017
