### ISSUE TITLE
EP Cancellation:  Stop processing EP claim establishment task

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#518]
As a Casework, I would like the ability to stop processing the current task of EP establishment so that I can put it on hold to retrieve additional information, escalate it to my coach, or release it back to the queue to be processed by another Caseworker.

### Acceptance Criteria
1. Verify that after clicking on the Cancel button on the Decision Review page, the EP Cancellation page is presented in a modal form.
1. Verify that after clicking on the Cancel button on the EP Creation page, the EP Cancellation page is presented in a modal form.
1. Verify that on the EP Cancellation page, the Heading title and subtext matches the mockup.
1. Verify that on the EP Cancellation page, the following action buttons are available:  **_Cancel EP Establishment_**.  (Refer to Mockup for details)
1. Verify that on the EP Cancellation page, the following action link is available:  Go Back.  (Refer to Mockup for details)
1. Verify that on the EP Cancellation page, the following fields are available:  Explanation  (Refer to Mockup for details)
1. Verify that on the EP Cancellation page, the field Explanation has the "(Required)" label.
1. Verify that on the EP Cancellation page when the **_Cancel EP Establishment_** button is click and the Explanation field has no text value, the following validation message is displayed:  Please enter an Explanation.

### Mockup
_EP Cancellation Page_
![image](https://cloud.githubusercontent.com/assets/23063044/21022164/95e9add4-bd49-11e6-92d6-bf44abd7f688.png)

_Modal View from Decision Review Page_
![image](https://cloud.githubusercontent.com/assets/23063044/21025183/7f732fba-bd55-11e6-9db8-156e827de3c9.png)

_Error Styling_
<img width="628" alt="screen shot 2016-12-05 at 11 01 06 am" src="https://cloud.githubusercontent.com/assets/1596259/20892142/e98735c2-bada-11e6-96f8-948a554db635.png">

### Sub-Task
QA manual testing

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
I'd also add that

**Comment by KHarshawat** [comment]
Update: We decided we will not save work if you place the appeal on hold since this will require quite a bit of engineering lift. We should make sure the text is updated to what's shown in the previous comment.
