### ISSUE TITLE
Case details | Display power of attorney information from both the brieff and representative tables

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5185]
Right now, we don't display all POA information in the appeal details page. That information is distributed across the BRIEFF and REP tables. We're not using the PowerOfAttorney model and repository that were built for that purpose. 

We should make sure we're showing Caseflow users all the information they need to identify power of attorney for an appeal. We may need to change the PowerOfAttorney model/repository somewhat — right now, `appeal.power_of_attorney` will get us the information we want, but it will also make an extra call to both VACOLS and BGS, which would result in a large number of new queries/API calls for e.g. the queue homepage. We'll likely want to be able to feed the data from our bulk appeal query into the POA model.

# AC
- We should display POA information from both BRIEFF and REP tables in the existing Appeal Details screen (sync with @laurjpeterson and @sneha-pai about how we should concatenate `vacols_representative_type` and `vacols_representative_name` e.g. "State Organization — Virginia Vets Assn" or "Attorney — Lowell Q Wood Esq")
- We shouldn't trigger an extra roundtrip to VACOLS *just* for that information
- We shouldn't currently make a call to BGS for POA information, but we should easily be able to trigger the call when we want to, since we're anticipating wanting to surface BGS POA info in Caseflow (see `appeal.power_of_attorney`)
- Verify that if VBMS or BGS is down, we display the error message

## Mocks
see designs in this [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1524163475348/3f583e97fd628f81eb05d516c829d3aced02fd5)

**Comment by lowellrex** [comment]
I think this was completed by the work in PR #5208. @amprokop can you confirm that?
