### ISSUE TITLE
What model name/ DB table name should we use for AMA appeals?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5195]
We're getting close to the point where we'll need to create appeals in the Caseflow DB. However, we already have an Appeal model and an Appeals Postgres DB table. This model/table has lots of logic and attributes that are specific to VACOLS and legacy appeals, and we want to change many aspects of appeal data (see https://github.com/department-of-veterans-affairs/caseflow/issues/3404), so we'll need to store AMA appeals and legacy appeals and legacy appeals in separate models/db tables.

## Option 1: Create a new AmaAppeals table

With this approach, we'd leave `appeal.rb` and the `Appeal` model as is and create `AmaAppeal` 

### Pros
- Minimal work

### Cons
- Naming debt. This name will be around after there are no more legacy appeals.

## Option 2: Rename the existing Appeals table to Legacy_appeals and create a new Appeals table

We'd need to run a db migration and find-and-replace all instances of `Appeal` and replace them with `LegacyAppeal`

### Pros
- More future-thinking.

### Cons
- Will require a PR and some coordination, although it shouldn't be more than a day or two of work total.

**Comment by shanear** [comment]
I like option 2. We will need it eventually, and it will be nice to have the `Appeal` model be the one we can use for the future. If not, we will likely be stuck with `AmaAppeal` forever.

**Comment by evankroske** [comment]
If we call the new table "AmaAppeal", rename the class Appeal to "LegacyAppeal", and call the new appeal class "Appeal", we could have pretty code without having to work late to rename a table

**Comment by shanear** [comment]
> work late to rename a table

If we break the migration into 3 parts, then we wouldn't need to do this.

**Comment by mdbenjam** [comment]
That sounds like a lot of work to rename the table, and I don't really think it's worth it. I'd rather either just have some name debt or have a short off-hours downtime migration. Don't have a major preference between the two.

We could also change `Appeal.rb` to `LegacyAppeal.rb` and update the `table_name` variable to have it point to the `appeal` table. Though I think that's just more confusing, it would enable us to sort of abstract away the details of renaming the table.

One other thought, do we want an `AppealBase` model that these inherit from? There are likely going to be several common methods we'll need for both even though their implementations will be very different. Not sure this is the right place to discuss this?

**Comment by sansb** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/5295#issuecomment-386094811 addresses this

**Comment by leikkisa** [comment]
Will special issues on the AMA appeals will still be needed in the same way as they are being used for RAMP? Are the special issues related to issues, or appeals?

**Comment by amprokop** [comment]
Great questions @leikkisa. Can you make a discussion ticket for this specifically? Would be good to talk with some product folks on this too.
