### ISSUE TITLE
EP Cancellation:  Hold:  Ability temporarily stop processing current task

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#520]
As a Caseworker, I would like the ability to temporarily stop processing the current EP Establishment task so that I can obtain additional information for this task and continue processing later.

###  Acceptance Criteria
1. Verify that on the EP Cancellation page after clicking the **_Hold_** button, the "Status" value is set to "On Hold" for the current case. (Seen on Manager's Home page - Current Claims section)
1. Verify that the held task is displayed in the Held Claims section on the Caseworker's Home page.

### Mockup
**_View - Manager's Home Page_**
![image](https://cloud.githubusercontent.com/assets/23063044/20856314/e8031d7c-b8d9-11e6-8807-131bef8332c1.png)
![managers home - current](https://cloud.githubusercontent.com/assets/23063044/20982191/7a441516-bc85-11e6-8e43-35d94bcb07aa.PNG)

**_View - Caseworker's Home Page- Held Claims_**
![image](https://cloud.githubusercontent.com/assets/23063044/20981902/58c1aa76-bc84-11e6-8fbf-54f14b21d9b6.png)

## Related Issues
EP Cancellation:  Stop processing EP claim establishment task #518 

## Sub-tasks

- [ ] QA Manual testing

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
I wold change the wording displayed form "In Hold" or "Placed on Hold" to just "On Hold" for consistency.

The status in the "Work history" section should update once the claim EP has been created, after being On Hold.

**Comment by mdbenjam** [comment]
@nikitarockz Update mock to remove value in the Work history section.

**Comment by nikitarockz** [comment]
Mockups have been updated.

**Comment by nikitarockz** [comment]
Based on the direction we are going now (no holding of issues), this issue is being placed in the ice box.
