### ISSUE TITLE
Checkbox should appear when an issue is marked "Vacated"

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5203]
Tested on Safari.

![image](https://user-images.githubusercontent.com/3781835/38895646-943a1e9c-425e-11e8-8090-b37cff19d817.png)

# AC
- When "Vacate" is selected, a checkbox should appear

**Comment by dannysellers** [comment]
I don't see this issue :\

![screen shot 2018-05-07 at 6 40 20 pm](https://user-images.githubusercontent.com/8533004/39728658-1e02e9d4-5226-11e8-95b9-51655a3aee11.png)

I'm running Safari 11.1 on my personal laptop—I'm not sure what version my VA laptop is using, but I'll check there tomorrow

**Comment by laurjpeterson** [comment]
no issues in demo, closing
