### ISSUE TITLE
Issue is marked "5." on "Edit dispositions" screen but called "Issue 1" on remand reasons screen

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5205]
![image](https://user-images.githubusercontent.com/3781835/38896249-2c28c216-4260-11e8-9827-788958ca7e18.png)

![image](https://user-images.githubusercontent.com/3781835/38896313-54246cf2-4260-11e8-89cf-7ea2412f8c0f.png)

This may need conferring with design, feel free to bump this to design.

# AC
- Issues should be named consistently across the screens

**Comment by dannysellers** [comment]
Resolved by #5298
