### ISSUE TITLE
AMA intake | Confirmation: HLR success

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5206]
When a Claims Assistant has successfully created a higher-level review or supplemental claim EP, we show them a confirmation page so they know the intake is complete.

## Acceptance Criteria
- If a user successfully establishes an EP by selecting the "Establish claim" button in the previous step, we should show them a success page 
- The page includes the name of the EP that was established (030 Higher Level Review)
- For now, we are only establishing the rated EP codes (rated issues)

## Mocks
![image](https://user-images.githubusercontent.com/4042181/38823950-c446d966-4175-11e8-9923-0e78bba592fe.png)

**Comment by leahbannon** [comment]
looks good!
