### ISSUE TITLE
EP Cancel Confirmed-Hold:  Display acknowledgement of EP case being held

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#521]
As a Caseworker, I would like receive a confirmation that my current EP Establishment task has been held so that I am confident that the case will be available for me to process later.

###  Acceptance Criteria
1. Verify that on the EP Cancellation page after clicking the **_Hold_** button, the EP Cancel Confirmed- Hold page is displayed.
1. Verify that on EP Cancel Confirmed Held page, the Header title matches the mockup.
1. Verify that on EP Cancel Confirmed Held page, the subtext matches the mockup.
1. Verify that on EP Cancel Confirmed Held page, the following action button is available:  **_Establish Next Claim_**.
1. Verify that on EP Cancel Confirmed Held page, the following action link is available:  **_View Work History_**.

### Mockup
_View 1 - EP Cancel Confirmed-Hold Page_
![image](https://cloud.githubusercontent.com/assets/23063044/20854023/50615472-b8be-11e6-982f-0fd2609dc090.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518 
EP Cancellation:  Hold:  Ability temporarily stop processing current task #520

### Sub-task
QA manual testing

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
lgtm

**Comment by nikitarockz** [comment]
Based on the direction we are going now (no holding of issues), this issue is being placed in the ice box.
