### ISSUE TITLE
[Discussion] Can we do better when it comes to VACOLS? 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#5217]
1. From the requirements perspective, how do we know which VACOLS fields require an action? Example: when creating a `DECASS` record, we should also update `BRIEFF`. 
2. From the requirements perspective, how do we know which columns to update on VACOLS tables? 
3. When setting time/date it is important to differentiate between timestamp vs date stamp. 
4. Do we always set `added_by` and `added_at` (e.g, `decass.deadusr` and `decass.deadtim`) when creating a record?
5. Do we always set `updated_by` and `updated_at` (e.g, `decass.demdusr` and `decass.demdtim`) when updating a record?
6. Should we keep track of deleted items?
7. Some primary keys in VACOLS are not uniq. For example, `decass.defolder` is not uniq so if you run `VACOLS:Decass.find(123456).update(…)`, it will update all DECASS records that have `defolder` value of 123456

**Comment by aroltsch** [comment]
### Open Questions ###
1. Should we reference VACOLS source code? 
2. Can we have two PR reviewers: one is a team tech lead and another is VACOLS QA (can randomly assign developers)?
3. Should we create a WIKI page? 
4. Should we have an audit table for items that we delete in VACOLS?

**Comment by aroltsch** [comment]
### Decisions ###
1. We will ask Jed if we can create a repo similar to dsva-vbms to ask him questions instead of using email so we maintain history.
2. We will always set added_by and added_at
3. We will always set updated_by and updated_at
4. For models without uniq primary keys, we will implement methods similar to this: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/vacols/case_issue.rb#L128

**Comment by evankroske** [comment]
Audit logs are good for more than just fixing mistakes: https://www.confluent.io/blog/turning-the-database-inside-out-with-apache-samza/
