### ISSUE TITLE
EP Cancel Confirmed-Held:  Ability to retrieve the next case or not

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#522]
As a Caseworker, I want the ability to quickly move to the next case or stop working after placing the my previous case on hold so that I can continue working other cases or move onto other tasks.

## Acceptance Criteria
1. Verify that on the EP Cancel Confirmed-Held page after clicking on the **_Establish Next Claim_** button, the next Establish Claim task in the queue is assigned to the current user. (use same logic as #438) 
1. Verify that on the EP Cancel Confirmed-Held page after clicking on the Establish Next Claim button, the Decision Review page is displayed.
1. Verify that on EP Cancel Confirmed Held page after clicking on the **_View Work History_** link, the Caseworker Home page is displayed.
1. Verify that on the EP Cancel Confirmed Held page when there are no more items available in the Establish Claim queue, the **_Establish Next Claim_** button is disabled.

### Mockup
![image](https://cloud.githubusercontent.com/assets/23063044/20854115/200cf0a0-b8bf-11e6-83e6-b48f719a7472.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518 
EP Cancellation:  Hold:  Ability temporarily stop processing current task #520
EP Cancel Confirmed-Hold:  Display acknowledgement of EP case being held #521

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
@nikitarockz for this and other issues related to the "Establish Next Claim" button we should verify that when there are no more claims left in the queue to work on, the button should be disabled. I'm just going to write this comment here but it applies to all stories like this.

**Comment by nikitarockz** [comment]
@KHarshawat Good catch.  I will update this and the other stories.

**Comment by mdbenjam** [comment]
@lakohl Will double check to make sure this is the flow we want to go with, in terms of having this page at all.

**Comment by nikitarockz** [comment]
Based on the direction we are going now (no holding of issues), this issue is being placed in the ice box.
