### ISSUE TITLE
EP Cancellation:  Establish Claim Task:  Permanently stop processing current task

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#523]
As a Caseworker, I would like the ability to permanently stop processing the current EP Establishment task so that it can be worked manually and no longer available in the work queue.

#  Acceptance Criteria
1. Verify that on the EP Cancellation page after clicking the **_Cancel EP Establishment_** button, the "_Action_" value is set to "Cancelled" for the current task. (Seen on Caseworker's Home page - Work History section)
1. Verify that on the EP Cancellation page after clicking the **_Cancel EP Establishment_** button, no new Established Claim task is created.
1. Verify that on the EP Cancellation page after clicking the **_Cancel EP Establishment_** button, the _"Status"_ value is set to "Cancelled" for the current case. (Seen on Manager's Home page - Work History section)

## Mockup
**_View - Caseworker's Home Page_** - Action updated
![image](https://cloud.githubusercontent.com/assets/23063044/20856118/93d57f5a-b8d5-11e6-89f1-6f3e745e495f.png)

**_View - Manager's Home Page_** - Status updated
![image](https://cloud.githubusercontent.com/assets/23063044/21061768/bd2f1a46-be1b-11e6-973f-efdf89528157.png)

# Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
lgtm

**Comment by nikitarockz** [comment]
@lakohl @joofsh I updated this story and mockups to match what is needed for Milestone 1.  Refer to AC2 & 3.

**Comment by kierachell** [comment]
Verified that Action is set to "Cancelled" on worker's Work History page.
Verified that the claims left count does not go down.
Verified that Manager's Work History displays the claim as Status: "Cancelled"

To note: when cancelling a claim; if "Case Explanation" field is filled with just spaces the user is redirected back to 'establish-claim/:id' route with a flash alert: "Error There was an error while cancelling the current claim. Please try again later". Not sure if that is desired behavior.

**Comment by lakohl** [comment]
Top portion of your comment sounds good.

For bottom portion 'when cancelling a claim' and the field is left blank we should follow this convention for messaging: https://github.com/department-of-veterans-affairs/caseflow-feedback/issues/60#issuecomment-268260102
