### ISSUE TITLE
EP Cancel Confirmed:  Display acknowledgement of EP case being cancelled

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#524]
As a Caseworker, I would like receive a confirmation that my current EP Establishment task was cancelled so that I am confident that the case has returned to the queue to be processed by another Caseworker.

###  Acceptance Criteria
1. Verify that on the EP Cancellation page after clicking the **_Cancel EP Establishment_** button, the EP Cancel Confirmed page is displayed.
1. Verify that on EP Cancel Confirmed page, the Header title matches the mockup.
1. Verify that on EP Cancel Confirmed page, the following subtext displayed (refer to mockup):

**_We’ve recorded your explanation for canceling the creation of this EP._** 
**_This claim has been removed from your queue and must now be processed outside of Caseflow Dispatch._**

**_You may establish another claim or view your Work History._**

1. Verify that on EP Cancel Confirmed page, the following action button is available:  **_Establish Next Claim_**.
1. Verify that on EP Cancel Confirmed page, the following action link is available:  **_View Work History_**.

### Mockup
**_View - EP Cancel Confirmed page_**
![image](https://cloud.githubusercontent.com/assets/23063044/21279762/f2b74460-c3af-11e6-8a3c-9dfb8e5a908d.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518 
EP Cancellation:  Establish Claim Task:  Permanently stop processing current task  #523

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
lgtm!

**Comment by kierachell** [comment]
Verified the page title and subtext upon successful cancellation. 
Options available are "View History" (should it be explicitly "View Work History" ?) and "Establish Next Claim" (as button).
