### ISSUE TITLE
AMA intake | Finish: select review lane per issue (NOD)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5240]
A user could theoretically request different Board docket lanes for each issue.
- If a user selects that option during the "review" step, they see a slightly modified version of the issue selection page.

**Comment by abbyraskinUSDS** [comment]
Since this is a bit of an edge case, I'd propose we hold off on developing it until we're closer to AMA (i.e., not for pilot).

**Comment by leikkisa** [comment]
Can we get a mock up for this?
