### ISSUE TITLE
Bug | Checkmarks disappear next day

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#5241]
https://github.com/department-of-veterans-affairs/appeals-support/issues/1881

**Comment by annienguyenUSDS** [comment]
Having Tami to follow-up for screenshot, but will plan to follow-up in person next week.

**Comment by lakohl** [comment]
I believe he was on travel board in Little Rock yesterday, and that the last time it happened he was on a travel board in Baltimore.
