### ISSUE TITLE
AMA intake | Validate there are no HLR->HLR issues

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5244]
Per the law, a Veteran cannot request a higher level review or board appeal for the same issue, twice in a row.
- If a Veteran attempts to create a HLR issue, when a HLR was just previously decided for that issue, we should display an alert message.
- Same for Board --> Board. Same for Board --> HLR 

## Mocks
![image](https://user-images.githubusercontent.com/4042181/40007676-722d4f50-576b-11e8-9565-8e081673aba2.png)

**Comment by abbyraskinUSDS** [comment]
We should revisit how we want to handle this check.

**Comment by shanear** [comment]
dup of https://github.com/department-of-veterans-affairs/caseflow/issues/7293, closing
