### ISSUE TITLE
EP Cancel Confirmed:  Ability to retrieve the next case or not

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#525]
As a Caseworker, I want the ability to quickly move to the next case or stop working after cancelling my previous case so that I can continue working other cases or move onto other tasks.

## Acceptance Criteria
1. Verify that on the EP Cancel Confirmed page after clicking on the **_Establish Next Claim_** button, the next Establish Claim task in the queue is assigned to the current user. (use same logic as #438) 
1. Verify that on the EP Cancel Confirmed page after clicking on the Establish Next Claim button, the Decision Review page is displayed.
1. Verify that on EP Cancel Confirmed page after clicking on the **_View Work History_** link, the Caseworker Home page is displayed.
1. Verify that on the EP Cancel Confirmed page when there are no more items available in the Establish Claim queue, the **_Establish Next Claim_** button is disabled.

### Mockup
![image](https://cloud.githubusercontent.com/assets/23063044/20854388/6caa9c94-b8c1-11e6-8e9a-ee8f21860f85.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518 
EP Cancel Confirmed:  Display acknowledgement of EP case being cancelled #524

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
LGTM!

**Comment by kierachell** [comment]
1. Verified that clicking on _Establish Next Claim_ redirects to the next claim in the queue
2. Verified that _Decision Review_ page is displayed for the appropriate claim
3. Verified that _View History_ redirects to work history for the appropriate user. (should it be _View Work History_?)
**4.** The _Establish Next Claim_ button is not disabled. Clicking it redirects _Decision Review_ page for the yet another claim; upon cancelling it as well, user is redirected to _Decision Review_ page with flash alert: 

> "Error; There was an error while submitting the current claim. Please try again later"
From there I am able to continue to "Generate End Product" (the flash alert persists/gets passed on the next page). 
Might be related to 523 note I left about leaving _Case Explanation_ field blank - which also generates the same behaviour.

**Comment by kierachell** [comment]
4. Is working correctly now.
