### ISSUE TITLE
EP Cancellation:  Escalate:  Ability stop processing and send to Coach current task

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#526]
As a Caseworker, I would like the ability to stop processing the current EP Establishment task and sent it to my coach so that the coach can reconcile the challenge and complete the establishment process.

###  Acceptance Criteria
1. Verify that on the EP Cancellation modal after clicking the  "Send claim and explanation ...." field checkbox and the **_Cancel EP Establishment_** button, the "Action" value is set to "Escalated" for the current task. (Seen on Caseworker's Home page - Work History section)
1. Verify that on the EP Cancellation modal after clicking the "Send claim and explanation ...." field checkbox and the **_Cancel EP Establishment_** button, the "Status" value is set to "Escalated” for the current case. (Seen on Manager's Home page - Current Claims section)
1. Verify that on the EP Cancellation modal after clicking the "Send claim and explanation ...." field checkbox and the **_Cancel EP Establishment_** button, a new Established Claim task is created for the current case and available in the queue.

### Mockup
**_View - Caseworker's Home Page - Action Updated_**
![image](https://cloud.githubusercontent.com/assets/23063044/20856774/f627763a-b8e5-11e6-9cf3-98122b17acb2.png)

**_View - Manager's Home Page_**
![image](https://cloud.githubusercontent.com/assets/23063044/20856148/1b5d3efe-b8d6-11e6-9459-a527e44e77ff.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
@nikitarockz A couple changes...
- For clarity I would change "EP Cancellation page" to "EP Cancellation modal"
- The word "escalated" should be in red (USWDS `secondary`) on the user's page

**Comment by nikitarockz** [comment]
@KHarshawat Updated.

**Comment by mdbenjam** [comment]
@nikitarockz --- Pushing back because this is closely related to Hold.
