### ISSUE TITLE
Remove "Built with <3 by Digital Service at VA" from the Caseflow footer

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5268]
@nicholasholtz expressed the thought that we should get away from DS branding on Caseflow in preparation for the eventual DS rolloff of the project. 

Kicking this to design/product for async discussion whenever convenient.

**Comment by lakohl** [comment]
My feeling is that we should keep it for now.
@suzchap can provide some context on how they handled this on Vets.gov

**Comment by carodew** [comment]
@jimruggiero this seems appropriate to me to remove this line from the footer, if for nothing else than the VA.gov style guide does not contain this in the footer and it could be potentially confuse users (small risk of that to be fair, but not none). If nothing else there's a missing space in that line that if we left it, we should fix. 

I don't think it needs design attention at this point, moving it to Backlog.

**Comment by alisan16** [comment]
The missing space is fixed. @jimruggiero @carodew should we go ahead and remove this footer altogether?

**Comment by carodew** [comment]
That would be my preference although unsure of the politics of that.

**Comment by nicholasholtz** [comment]
I'd say go for it :)  Consider this the approval from the USDS side of things.

Hope y'all are doing well.

**Comment by alisan16** [comment]
To actually remove this we need to update the hash caseflow uses for caseflow-frontend-toolkit: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/package.json#L60
