### ISSUE TITLE
EP Cancel Confirmed-Escalated:  Display acknowledgement of EP case being sent to coach

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#527]
As a Caseworker, I would like to receive a confirmation that my current EP Establishment task was escalated and sent it to my coach so that I am confident that the case has been sent to be processed by my coach.

###  Acceptance Criteria
1. Verify that on the EP Cancellation page after clicking the "Send claim and explanation ...." field checkbox and the **_Cancel EP Establishment_** button, the EP Cancel Confirmed-Escalated page is displayed.
1. Verify that on EP Cancel Confirmed-Escalated page, the Header title matches the mockup.
1. Verify that on EP Cancel Confirmed-Escalated page, the subtext matches the mockup.
1. Verify that on EP Cancel Confirmed-Escalated page, the following action button is available:  **_Establish Next Claim_**.
1. Verify that on EP Cancel Confirmed-Escalated page, the following action link is available:  **_View Work History_**.

### Mockup
_View 1 - EP Cancel Confirmed-Escalated Page_
![image](https://cloud.githubusercontent.com/assets/23063044/20855760/8f8fddce-b8cf-11e6-9c60-c1c79624c974.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518 
EP Cancellation:  Escalate:  Ability stop processing and send to Coach current task #526

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
LGTM!
