### ISSUE TITLE
EP Cancel Confirmed-Escalated:  Ability to retrieve the next case or not

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#528]
As a Caseworker, I want the ability to quickly move to the next case or stop working after escalating my previous case so that I can continue working other cases or move onto other tasks.

### Acceptance Criteria
1. Verify that on the EP Cancel Confirmed-Escalated page after clicking on the **_Establish Next Claim_** button, the next Establish Claim task in the queue is assigned to the current user. (use same logic as #438) 
1. Verify that on the EP Cancel Confirmed-Escalated page after clicking on the Establish Next Claim button, the Decision Review page is displayed.
1. Verify that on EP Cancel Confirmed-Escalated page after clicking on the **_View Work History_** link, the Caseworker Home page is displayed.
1. Verify that on the EP Cancel Confirmed Escalated page when there are no more items available in the Establish Claim queue, the **_Establish Next Claim_** button is disabled.

### Mockup
**_View - EP Cancel Confirmed-Escalated page_**
![image](https://cloud.githubusercontent.com/assets/23063044/20855839/ea46d87a-b8d0-11e6-816f-817b85f226a3.png)

### Related Stories
EP Cancellation:  Stop processing EP claim establishment task #518 
EP Cancellation:  Escalate:  Ability stop processing and send to Coach current task #526
EP Cancel Confirmed-Escalated:  Display acknowledgement of EP case being sent to coach #527

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
LGTM!
