### ISSUE TITLE
AMA intake | Designate "same office" as special issue on claim for HLRs

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5281]
In VBMS Claims Service V5 we will have the ability to pass a special issue designating if the Higher Level Review or Supplemental Claim was requested to be processed at the same station. We should pass this value properly.

## Acceptance Criteria
- When a user intakes a HLR and selects same station, we should designate that the HLR EP should be routed to the same station as where one of the original issues was processed.
- When a user does not select same station, we should not designate that it should be routed to the same station.

## Technical Notes
- We need a way to determine if VBMS correctly received the request.
- This is dependent on #5428 

This can be done via the existing CreateContentions endpoint:

```
<contentionsToCreate ...>
  ...
  <ns2:issue typeCd="SSR" narrative="Same Station Review" inferred="false"/>
</contentionsToCreate>
```

## Validation instructions
Test file numbers: 888451290
Choose Higher Level Review
Select "yes" for same office
Finish establishing an end product

After an EP is created we'll need to figure out how to look at it in VBMS. If we can't validate in the VBMS UI, then I can look at what gets returned by ListContentions and see if it's in there.

**Comment by abbyraskinUSDS** [comment]
@shanear to add details and investigate

**Comment by shanear** [comment]
This is blocked because the create contentions service is down in UAT right now.

**Comment by leahbannon** [comment]
(for testing, look for special issue on contentions created in VBMS)

**Comment by leikkisa** [comment]
888451290 should be a good number for this.  So choose Higher Level Review, select "yes" for same office.  After an EP is created we'll need to figure out how to look at it in VBMS.   If we can't validate in the VBMS UI, then I can look at what gets returned by ListContentions and see if it's in there.

**Comment by leikkisa** [comment]
ListContentions does not show data on this. I feel like we need to ask VBMS how to validate this .

Here are a couple of UAT HLRs that we can use to validate what happened after we passed it over to VBMS:
<HigherLevelReview id: 59, veteran_file_number: "123458308", receipt_date: "2018-07-15", informal_conference: false, same_office: true, established_at: "2018-07-25 20:30:51", end_product_reference_id: "600134040", end_product_status: nil, end_product_status_last_synced_at: nil>

 <HigherLevelReview id: 60, veteran_file_number: "123458309", receipt_date: "2018-07-18", informal_conference: false, same_office: true, established_at: "2018-07-25 20:35:08", end_product_reference_id: "600134041", end_product_status: nil, end_product_status_last_synced_at: nil>

**Comment by leikkisa** [comment]
I just tried to take an intake with this selected, and create_contentions failed. It succeeded without the same office selected. 

To do: 
Figure out if this is a problem with VBMS or with Caseflow.
Fix it, test it
Create an intake with Same Office selected,
Send the test file number and claim id to Joe for validation on VBMS's side.

**Comment by kahlouie** [comment]
We need to get more data on the soap request for what it should be

**Comment by leikkisa** [comment]
Here's the schema, and we think we need to move the issues before the origSrc.

```<xs:complexType name=“Contention”>
       <xs:sequence>
           <xs:element name=“completionDate” type=“xs:date” minOccurs=“0"/>
           <xs:element name=“source” type=“common:Source” minOccurs=“0”/>
           <xs:element name=“submitDate” type=“xs:date” minOccurs=“0"/>
           <xs:element name=“issue” minOccurs=“0" type=“Issue” maxOccurs=“5000">
               <xs:annotation>
                   <xs:documentation>Associations between Contentions and Issue are maintained by the
                       ISSUE_CONTENTION_ASSOC table in the PDM.
                   </xs:documentation>
               </xs:annotation>
           </xs:element>
           <xs:element name=“startDate” type=“xs:date” minOccurs=“0”/>
           <xs:element name=“origSrc” type=“xs:string” minOccurs=“0" maxOccurs=“1” />
       </xs:sequence>```

**Comment by suzchap** [comment]
Getting an error. Tried to validate with Sally so she saw error code.
<img width="1101" alt="screen shot 2018-09-12 at 2 53 57 pm" src="https://user-images.githubusercontent.com/11219417/45446774-bf45aa00-b69b-11e8-865d-8a17200cb7a1.png">

**Comment by shanear** [comment]
validation is blocked due to https://github.com/department-of-veterans-affairs/caseflow/issues/7108

**Comment by shanear** [comment]
<img width="616" alt="screen shot 2018-09-24 at 7 09 35 pm" src="https://user-images.githubusercontent.com/1596259/45984076-6841bc80-c02d-11e8-9a10-ae70556aec35.png">

Validatarific!
