### ISSUE TITLE
AMA intake | Create contentions on EP (HLR)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5282]
This story covers the technical step of creating the issues and contentions associated with a Higher Level Review request.

## Acceptance Criteria
- When a user selects the **Establish claim** button on the "Finish" page, in addition to creating the End Product associated with that type of review, we should also create associated contentions on that supplemental claim for each selected rating issue.
- There should additionally be a record of each issue in the Caseflow database containing: the id of the associated rating issue, the id of the contention created, the text of the contention, and the polymorphic association to it's parent AMA review.

## Technical Notes
- Because there are multiple different kinds of Issues in Caseflow, it's suggested we call the issue model `RequestIssue`. See https://github.com/department-of-veterans-affairs/appeals-design-research/issues/770 for more details.
- We will eventually need to figure out a way to make the operation of creating the EP, contentions and DB objects idempotent. This will require more VBMS contentions endpoints than we have currently built, so we'll pass on that for now.

**Comment by shanear** [comment]
@leahbannon what's blocking this one?

**Comment by suzchap** [comment]
We submitted tests but waiting for Sally to be able to connect to UAT to see if it worked then she'll share screenshots for confirmation.
