### ISSUE TITLE
AMA intake | Increment EPs when simultaneous review requests are pending

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5289]
There can only be one EP per "modifier" in BGS. We will have 10 available EP modifiers for both Higher Level Reviews (030-039) and Supplemental claims (040-049). We should use an unused modifier in order to prevent EP code collisions.

e.g., if there's an 030 in the system for issue A, and a Veteran submits a claim for issue B, we should increment the EP to 031.

## Acceptance Criteria
- When creating the EP for a higher level review, if there are already existing higher level review EPs, we should use the lowest unused modifier when creating that EP. (same for supplemental claims)

**Comment by leahbannon** [comment]
works! huzzah

**Comment by programmersun** [comment]
hello
