### ISSUE TITLE
Caseworker Home:  View held claims

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#529]
As a Caseworker, I want the ability to view all claims that I placed on hold so the I can process them at a later time.

### Acceptance Criteria
1. Verify that on the Caseworker Home page, there is a new section labeled "Held Claims".
1. Verify that in the Held Claims section, there is a table with the following columns:
   - "Veteran Name"
   - "Decision Date"
   - "Decision Type"
   - "Explanation"
1. Verify that the Held Claims table contains all tasks assigned to the current user and Action value of "On Hold". 
1. Verify that for each task in the list,
   - the "Veteran ID" column contains the value for the VBMS ID of the appeal
   - the "Decision Date" column contains the value for the decision date retrieved from VACOLS
   - the "Decision Type" column contains the value for the decision type retrieved from VACOLS
   - the "Explanation" column contains the value for the hold Explanation of the task.
1. Verify that for each Held Claims task in the the list there is a link "Establish Claim".
1. Verify that if there are no held claims, hide the Held Claims section.

### Mockup
**_View - Caseworker Home page - Held Claims Section_**
![image](https://cloud.githubusercontent.com/assets/23063044/20856579/10cf0a62-b8e0-11e6-90cb-93b8ea2aa597.png)

### Sub-task
QA manual

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
LGTM!

**Comment by mdbenjam** [comment]
@nikitarockz Update mockup to have the value "On Hold".

**Comment by mdbenjam** [comment]
@lakohl @nikitarockz There needs to a new mockup/story for allowing the user to continuously go in to a task that is on hold.

**Comment by nikitarockz** [comment]
Based on the direction we are going now (no holding of issues), this issue is being placed in the ice box.
