### ISSUE TITLE
Casework Home: Held Claims:  Establish Claim:  Ability to continue working on task

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#530]
As a Caseworker, I want the ability to continue working on a claim that I have previously place on hold so that I can complete the process to Establish an EP.

### Acceptance Criteria
1. Verify that on the Caseworker Home page after clicking the "Establish Claim" link, the Decision Review page is displayed. with the selected task.
1. Verify that on the Decision Review page, the claim information for the selected held task is rendered.
1. Verify that after completing the process of establishing the EP for the previously held task, it is no longer displayed in the Held Claims section on the Caseworker Home page.
1. Verify that after completing the process of establishing the EP for the previously held task, the Action value on the Caseworker Home page has been updated to the selected EP code.

### Mockup
**_View - Caseworker Home page - Held Claims Section_**
![image](https://cloud.githubusercontent.com/assets/23063044/20856579/10cf0a62-b8e0-11e6-90cb-93b8ea2aa597.png)

### Related Stories
Caseworker Home:  View held claims #529

**Comment by nikitarockz** [comment]
@KHarshawat Please look at these and make sure I captured your plan.
@shanear check it out.

**Comment by KHarshawat** [comment]
@nikitarockz LGTM!

**Comment by nikitarockz** [comment]
What does LGTM! stand for?

**Comment by KHarshawat** [comment]
Looks Good To Me :)

**Comment by nikitarockz** [comment]
Based on the direction we are going now (no holding of issues), this issue is being placed in the ice box.
