### ISSUE TITLE
Move case search bar to navigation bar

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5306]
Move case search bar to the navigation bar to make more room in the container for subsequent Caseflow functionality. 

## Mocks
![image](https://user-images.githubusercontent.com/1598889/42038845-eded0358-7ab9-11e8-8665-08cfa57a1d39.png)

## Resources
- [Case details Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1525112874684/5765d285f568b5f631990e2c8e514a39d9b6b570)
![img_24377f8750d8-1](https://user-images.githubusercontent.com/27704093/39275451-51f9d6ac-48b3-11e8-924d-f269742de7d0.jpeg)

**Comment by amprokop** [comment]
Could be sweet. Questions — 

1. Will this be consistent across apps? Seems like it should at least appear across Reader and everything Queue-related. What about Hearing Prep? Certification?
1. How does this rank among alternatives — potentially we could have a "Search" link or a search icon link at the top which takes the user to a search page. Tradeoff— it's one extra click, but potentially a lot less clutter. Not sure if the search bar in the header adds some level of distraction
1. With the search bar embedded in the header, how do we think about navigation back to what the user was previously doing before searching? If we want to have some sort of breadcrumb/back link, it probably needs to be programmatically named

**Comment by mkhandekar** [comment]
Just a quick add that the design of the search functionality could vary, based on what works best for each caseflow feature/product:
- full search bar
- only search icon that is expandable on click
- only search link that takes user to search page on click

**Comment by laurjpeterson** [comment]
1. I think it could be consistent across apps, though probably not Certification or Dispatch just yet. I recommend we keep it to Board users for now. Do you see any drawbacks of it being across all apps? If we moved the search bar like in this ticket, will it inherently affect all apps or can we keep it to queue?

2. Would defer to @sneha-pai and @mkhandekar on the other design suggestions. I haven't done user research on the alternatives. The main goal for moving the search bar right now is to make more space for the Judge functionality we're working on, and pave the way for future users. 

3. How does moving the search bar change the navigation from how it is done today, when the search bar is just below the header?

**Comment by laurjpeterson** [comment]
With this particular ticket, I’m not proposing it be changed from what we have today.

**Comment by laurjpeterson** [comment]
from how we have it today*

**Comment by amprokop** [comment]
Hmm can we get a sense of what the medium term view is re: where this bar should appear, @laurjpeterson? 

If we definitely want it to appear eventually in other React apps other than Queue (Reader, Certification, for instance), than that may affect the implementation of this ticket. I'm thinking the eng who picks this up might want to design the solution in a way that allows us to easily enable this search bar across different Caseflow apps/pages, not just for this page.

**Comment by mkhandekar** [comment]
Our (Queue team) current thinking is to have the search component in the nav bar everywhere on Caseflow:

![image](https://user-images.githubusercontent.com/1598889/42038845-eded0358-7ab9-11e8-8665-08cfa57a1d39.png)

... and when a user clicks on that, they are taken to Caseflow Search landing page.

But we need to talk through this with other teams as it will affect:
- what do I see when I search for something from Queue?
- what do I see when I search for something from Reader? 
- and I'm sure other questions I am not thinking of right now!

We have it in our design team priorities to work through navigation & search throughout Caseflow (to and from other products) in the next couple weeks and would definitely want to make sure the engineer who would be working on this is part of those conversations @amprokop. 

cc: @sneha-pai @allyceh

**Comment by amprokop** [comment]
Thanks for everyone's thoughts! Was thinking about the subtleties here and I didn't find it easy to disentangle how we would roll this nav bar out from a wider Case Search rollout, so  I captured an idea for how that might happen to try to move this task forward. Caveat that I don't know if folks have made alternative plans yet, so apologies in advance if there's already a fleshed out path there, and let's chat!


@lowellrex @mkhandekar @sneha-pai @laurjpeterson, feel free to take a look at https://github.com/department-of-veterans-affairs/caseflow/issues/6111

**Comment by mkhandekar** [comment]
The idea described in @amprokop's new issue works for me / @lowellrex. 
@laurjpeterson did you get a chance to take a look?

Adding that when we implement this, let's also deal with the empty/white space that was caused by removing breadcrumbs (https://github.com/department-of-veterans-affairs/caseflow/pull/6201).

**Comment by laurjpeterson** [comment]
yes! apologies for my delay. i am good with alex's plan.

**Comment by mkhandekar** [comment]
hi @amprokop + @laurjpeterson! y'all met a couple weeks ago about this right? can one of you post a super quick update about the feasibility of this change?

**Comment by laurjpeterson** [comment]
@mkhandekar we're all aligned on this change and @amprokop's proposed implementation! however, since search functionality is working (though not the most up to date design), and with @mdbenjam heading out for a few weeks, we're going to postpone implementing it. @lowellrex will focus on organizational queues and vso work for this sprint.

**Comment by laurjpeterson** [comment]
closing this issue in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/6111, where implementation details are captured.
