### ISSUE TITLE
VACOLS:  "Dispatch Appeals" link launches Caseflow

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#531]
A DRO we interviewed on 12/1/16 told us that sometimes when he clicks on "Dispatch Appeal" in VACOLS, it launches Caseflow. According to @shanear this should not happen. The DRO couldn't say exactly when it occurred. He said he recalled it happening with cases that were not certified in Caseflow.

## Related Issues
_Product Support Issue:_  https://github.com/department-of-veterans-affairs/appeals-pm/issues/1036

**Comment by shanear** [comment]
This will require us to follow up with Jed.

**Comment by nikitarockz** [comment]
### Closing:  Based on final Investigation

**_Shelly's comments:_**
Daravann responded, and it appears that he misunderstood what was happening. He wanted to tell us that Caseflow does NOT launch when he is certifying a remand, which is a known problem that we are working to resolve.
