### ISSUE TITLE
[Spec] How we might make task.rb generic and usable for all Caseflow tasks

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#5310]
Reference: https://github.com/department-of-veterans-affairs/appeals-design-research/wiki/Co-located-end-to-end and 
Reference: https://github.com/department-of-veterans-affairs/appeals-design-research/wiki/Attorneys-to-Co-located
- LP edited this link to the attorneys to co-located epic in github wiki instead of a github issue on 5/1. they have the exact same content, but the epic on wiki will be updated and be the source of truth moving forward

The existing Task model was created for Dispatch staff. This spec will examine the existing Task model, and how it can be refactored to be reusable across different teams. 

### Current `tasks` Table: ###

```
create_table "tasks", id: :serial, force: :cascade do |t|
    t.integer "appeal_id", null: false
    t.string "type", null: false
    t.integer "user_id"
    t.datetime "assigned_at"
    t.datetime "started_at"
    t.datetime "completed_at"
    t.integer "completion_status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "lock_version"
    t.string "comment"
    t.string "outgoing_reference_id"
    t.string "aasm_state"
    t.datetime "prepared_at"
```

### Analysis of Each Column ###

1. `appeal_id` - which appeal it is associated with
2. `type` - we can specify what type of a task it is. Currently there is only one type: `EstablishClaim`. In Queue, type will mean something different: AOD, Reman, CAVC, Original, etc
3. `user_id` - a user who is assigned a task
4. `assigned_at`, `started_at`, `completed_at`, `created_at`, `updated_at` - timestamps
5. `completion_status` is very Dispatch specific:

```
enum completion_status: {
    routed_to_arc: 0,
    canceled: 1,
    expired: 2,
    routed_to_ro: 3,
    assigned_existing_ep: 4,
    special_issue_emailed: 5,
    special_issue_vacols_routed: 7,
    invalidated: 8,
    # These statuses are not in use anymore
    special_issue_not_emailed: 6
  }
```

6. `comment` - a comment associated with a task
7. `outgoing_reference_id` - currently it is an End Product ID (Dispatch specific)
8. `aasm_state` - a state machine that determines which state the task is currently at. 

Current states:

```
Task.aasm.states.map(&:name)
=> [:unprepared, :unassigned, :assigned, :started, :reviewed, :completed]
```

For Queue tasks, we might not need unprepared, unassigned, reviewed. For Queue, we need on-hold state. Also, some of the transitions are Dispatch related, for example, on `start`, there is a method call to create quota:  

```
def create_quota!
   self.class.todays_quota.assigned_quotas.find_or_create_by!(user: user)
end
```

9. `prepared_at` - datetime needed for Dispatch tasks.

### Analysis of the `Task` Model ###

1. A `Task` model contains a lot of methods that will only be used by Dispatch and will never be used by Queue.
2. A `Task` model has a completion status that is Dispatch specific
3. A `Task` model has a state machine that has states that are not be needed for Queue. Queue might not even need a state machine.
4. Current model is missing a few fields that we will need for Queue: `assigned_by`, `instructions`, `on_hold_reason`, `on_hold_due_date`, `team_id`, etc.
5. For queue, we will have 4 statuses: assigned, in-progress, on-hold, completed
6. Dispatch tasks are not distributed evenly amongst users. A Dispatch user selects that they are ready for a new task and a first available task gets assigned to them. For co-located, we will probably have different logic to assign work to users (similar to Jed's allocation program in VACOLS). 

### Analysis of the Queue Task ###

This is a simple example of what a queue task will look like: 

```
create_table "tasks", id: :serial, force: :cascade do |t|
    t.integer "appeal_id", null: false 
    t.integer " status" # assigned (?), in-progress, on-hold, completed
    t.text "name"
    t.text "instructions"
    t.text "on_hold_reason"
    t.datetime "on_hold_due_date"
    t.integer "assignee_id"
    t.integer "assignor_id"
    t.integer "team_id"
    t.datetime "assigned_at"
    t.datetime "started_at"
    t.datetime "completed_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
   
```

##### 1. Re-factor `Task.rb`. Make `Task.rb` more generic. Move Dispatch specific code to EstablishClaim class. #####

Pros: 
* We can reuse tasks table
* We can reuse some of the methods

Cons:
* We might introduce new bugs in Dispatch
* Some `tasks` columns are not needed for Queue 
* It is unclear at first glance which methods can be made generic
* EstablishClaim.rb is already complicated. Moving more code there will make it even more complex. 
* Requires a lot of effort on our side. 

#### 2. Rename Task.rb to DispatchTask.rb. Create Task.rb that will be used by Queue. Move TasksController.rb under Dispatch directory. These two classes will be completely separated from each other. #####

Pros:
* We will not introduce new bugs in Dispatch
* We don't have to worry about Dispatch code
* We can create a simpler model for Queue
* We have freedom of designing Queue Model any way we prefer 

Cons:
* Some of the code will be duplicated
* We will have to start from scratch

**Comment by amprokop** [comment]
> type - we can specify what type of a task it is. Currently there is only one type: EstablishClaim. In Queue, type will mean something different: AOD, Reman, CAVC, Original, etc

hmm i think the `type` in Queue you reference here would be on the appeal, not the task

**Comment by amprokop** [comment]
`2. Rename Task.rb to DispatchTask.rb. Create QueueTask.rb. These two classes will be completely separated from each other.`

Slight preference to just call the new task model `Task.rb`, since we're getting away from `Queue` as app branding.

**Comment by amprokop** [comment]
Another question — have you looked at AASM for use in tasks for other teams other than Dispatch? I'd be interested in the advice of some engineers that have used AASM. Potentally @sharonwarner and @mdbenjam would have some good thoughts here:

- What problem AASM brought into the project to solve? (I have a fuzzy idea but would love details, including whether we brought it in once we were experiencing a problem)
- Did it solve that problem well?
- Would we use it again?

**Comment by mdbenjam** [comment]
My top question is, what does dispatch look like in AMA world? Is our app still relevant? If not, then I'd go hard on option 2. We can create a cleaner task model that isn't so tied to dispatch, and we can avoid modifying dispatch code. We can update cases in VACOLS such that Dispatch will still pick them up. Queue and Dispatch will be integrated via VACOLS. If Dispatch as an app is still relevant in its current form in AMA world, then maybe option 1 has some more merit. Then we can actually integrate the applications. Even in that scenario I think option 2 is valid, we just need to think about what the future complexity of integrating it with dispatch is.

AASM was probably not necessary. I don't think we added it because of a specific problem, just felt like the best way to manage state. Previously we transformed states through a row in our table, AASM enforces only valid state transitions. I know there were a lot of bugs we had to fix around that, curious of Sharon's thoughts if those bugs were real business logic bugs. Or were they "fake bugs" where we weren't allowing valid state transitions and AASM just created extra work for us?

**Comment by aroltsch** [comment]
I think AASM is needed to enforce only valid state transitions. For example, the task can go from unassigned to assigned and not backwards. For queue, I don't see that we need these strict rules.

**Comment by evankroske** [comment]
I vote for option 2. I think that we should try leave Dispatch code alone. Personally, I don't think we should even rename Task. Instead, I think that we should call the new task model Queue::Task or AmaTask.

**Comment by amprokop** [comment]
> I think AASM is needed to enforce only valid state transitions. For example, the task can go from unassigned to assigned and not backwards. For queue, I don't see that we need these strict rules.

Devil's advocate — is there something specific about dispatch's task state that makes this useful? Are we sure that wider Caseflow tasks don't share that property?

**Comment by amprokop** [comment]
I have an idea in my head that this was to solve a race condition problem where workers are all pulling from the same pool of tasks. Is there a chance we want to handle co-located in that fashion as well?

**Comment by sharonwarner** [comment]
I agree with option 2. It's sad because we attempted to design the task and establish claim models such that the task model was reusable, but it didn't really turn out that way. 

I think AASM was pretty useful for dispatch. It was helpful to differentiate between the unprepared and unassigned states: unprepared tasks are tasks that don't have decision documents, and unassigned tasks are tasks that are available to be picked up. It was also helpful to have the built in before/after hooks, for example, our assign event confirms that the assign function finishes successfully before transitioning to assigned. All of this functionality is obviously possible without AASM, but having all the transitions along with their before/after hooks explicitly defined in 40ish lines of code helped keep everything very clear/concise.

**Comment by tejans24** [comment]
I vote for option 2 as well. I think it's worth keeping the business logic separate and keeping dispatch on it's own. It's going to be hard to debug issues if we have a consolidated task model and try to integrate business logic from multiple applications together. As Mark mentioned, if we design the new code in a way with consideration of possibly using this logic for dispatch in post AMA, that might make future integration of this code simpler.

**Comment by sharonwarner** [comment]
For more context, here's the original issue for dispatch states: https://github.com/department-of-veterans-affairs/caseflow/issues/551
