### ISSUE TITLE
Change Veteran class into ActiveRecord from ActiveModel and create associated db table

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#5311]
In order to enable us to have unique URLs for each veteran (for example, on a [search results page](https://github.com/department-of-veterans-affairs/caseflow/issues/5181)), and to reduce the number of calls we make to BGS when retrieving the `participant_id` BGS uses as their Veteran identifier, we will be creating a new table to store the following information about a Veteran: id (autoincrementing table index), social_security_number, participant_id (from BGS). All three values will be required.

If we need to be able to create new records when we only know the C number and not the SSN, then we should add that as a separate field (c_number) from social_security_number instead of combining them into a single file_number field if possible. We could require that at least one of these two values (SSN, C number) be present when inserting into the `veterans` table.

The recent work in #5286 to refactor the `Veteran` class to lazily load data from BGS reduces the effort to accomplish this task.

## Acceptance criteria
* `veterans` table created with the aforementioned fields
* `Veteran` changed into a subclass of `ActiveRecord` in order to be associated with the table

**Comment by shanear** [comment]
> If we need to be able to create new records when we only know the C number and not the SSN, then we should add that as a separate field (c_number) from social_security_number instead of combining them into a single file_number field if possible. We could require that at least one of these two values (SSN, C number) be present when inserting into the veterans table.

I wholeheartedly disagree. No other system in the VBA ecosystem makes the distinction between whether the file number is a "C number" or an SSN. It would be used in the exact same way.

Additionally, we [already have a method that can determine whether a file number should be prepended with a "S" or "C"](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/appeal.rb#L519) in case we need to use it with VACOLS.
