### ISSUE TITLE
Update README to include setup details for shoryuken

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#5313]
In order to have shoryuken running localy, we need to run:
RAILS_ENV=<ENV> shoryuken start -q caseflow_local_high_priority caseflow_local_low_priority -R

Also, we should make this option for development env, look: 
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/certification.rb#L21

**Comment by laurjpeterson** [comment]
@nemodjuric - is this ticket still relevant?
