### ISSUE TITLE
Queue doesn't de-dupe trailing slashes correctly

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5317]
If I navigate straight to `http://localhost:3000/queue/appeals/2556987/` (rather than http://localhost:3000/queue/appeals/2556987), and click "Create Draft Decision", i wind up at an invalid route:

![image](https://user-images.githubusercontent.com/3781835/39320021-dd49080c-4950-11e8-98d2-8989f352bbf2.png)

## AC
- Queue should somehow dedupe slashes such that links won't send us to paths with doubleslashes in them

**Comment by evankroske** [comment]
Estimate: 1 hour

**Comment by evankroske** [comment]
Steps to reproduce the issue: https://dsva.slack.com/archives/C54QCEHAL/p1525901489000140

**Comment by evankroske** [comment]
Steps to reproduce the issue:

Alex Prokop [6 days ago]
Hey! Try http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/queue/appeals/333334/

Alex Prokop [6 days ago]
First go to the switch users page

Alex Prokop [6 days ago]
And switch to Reader at station 283

Alex Prokop [6 days ago]
Then go to http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/queue/appeals/333334 and select Submit Draft Decision from the dropdown

Alex Prokop [6 days ago]
Then try http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/queue/appeals/333334/ and do the same

Alex Prokop [6 days ago]
Let me know if that doesn’t work!

**Comment by evankroske** [comment]
This issue seems to be fixed. Here's how I tried to reproduce it:

1. caseflowdemo.com
1. Become Bvascasper.
1. http://www.caseflowdemo.com/queue/appeals/3626186/
1. Select action "Decision Ready for Review".
