### ISSUE TITLE
Hearing Worksheet | Primary Impressions and added issues are not saving

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5322]
Sonnet reported that her Primary Impressions and 2 added issues are not showing on the Hearing Worksheet.

**Comment by lakohl** [comment]
Sonnet's encryption is not working. I forwarded Sonnet's email to Tami and asked her to try to get the Vet ID for this case.

**Comment by annienguyenUSDS** [comment]
Sharon checked this veteran's info in our database. they currently have 3 open appeals. we have user-created issues saved for 1 of the appeals, and we have preliminary impressions saved for 6 out of 10 of the issues. nothing seems off to me, but if we could ask the judge for a specific box or issue that didn't save correctly, that would be helpful

Asked for Raven to follow back up on the support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/1956
