### ISSUE TITLE
RAMP intake | Update RAMP ineligible copy to mention EP 400s instead of letters

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5328]
Update the RAMP ineligible alert (rampIneligibleInstructions) as follows:

## New language
<p>
    Please check the Veteran ID entered, and if the Veteran ID
    is correct, take the following actions outside Caseflow:
  </p>
  <ul>
    <li>
      Establish an EP 400 in VBMS.
    </li>
    <li>
        Add a note in VBMS stating the reason for creating the EP 400 (Veteran is not eligible for RAMP).
    </li>
    <li>
      Route the EP to the RAMP Team for letter generation.
    </li>
  </ul>
</div>

***

## Existing language (for reference)
<p>
    Please check the Veteran ID entered, and if the Veteran ID
    is correct, take the following actions outside Caseflow:
  </p>
  <ul>
    <li>
      Upload the RAMP Election to the VBMS eFolder with
      Document Type <b>Correspondence</b> and Subject Line "RAMP Election".
    </li>
    <li>
      Notify the Veteran by mail of his/her ineligibility to participate
      in RAMP using the <b>RAMP Ineligible Letter</b> in <em>Letter Creator</em>.
    </li>
    <li>
      Document your actions as a permanent note in VBMS.
    </li>
  </ul>
</div>

**Comment by abbyraskinUSDS** [comment]
From Claire: 
b.      Add: Establish EP 400 in VBMS
c.       Add: Put note in VBMS stating reason for creation of EP400 (due to current upload lag between CMP and VBMS)
d.      Add: Route EP to RAMP Team for letter generation

**Comment by leahbannon** [comment]
closing - this was reverted with #5395
