### ISSUE TITLE
Add support to mismatched script for recognizing potential alternates (1/22)

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#533]

**Comment by alex** [comment]
Two cases we are about:

- For NOD or Form9, if not found report if specific other labels (TBD) present on the same date
- For NOD or Form9, if not found report if NOD or Form9 found within N (TBD) days.

**Comment by KHarshawat** [comment]
From @alex 

> Locate alternate documents is basically done, just need to update the script with the constants Chris confirmed yesterday.

**Comment by alex** [comment]
We're just waiting on the final list of relevant document types, then this PR will be r4r.
