### ISSUE TITLE
EXPECTED JULY 15: Approve and open BGS Rating endpoints in prod

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5332]
Work with John Dell on opening up the rating endpoints we use for Caseflow Intake in prod.

These are the two services:
RatingInformationService
RatingComparisonEJBService

**Comment by shanear** [comment]
@abbyraskinUSDS what's the date we need to go live with this?

**Comment by abbyraskinUSDS** [comment]
I would like to test these by mid June if possible - the week of June 18th. (Definitely no later than end of June.)

**Comment by shanear** [comment]
This is for retrieving rating information

**Comment by abbyraskinUSDS** [comment]
Note: This is basically a bureaucracy hacking ticket. Requires filling out a form and proving we've tested in UAT - can take a month. Shane will send the initial email.

**Comment by shanear** [comment]
holding on this for a little bit until we have more clarity on what's going on with passing the user information to VBMS. The fact that we have not done this is likely to piss off BGS.

**Comment by shanear** [comment]
Sent an email to John today. Waiting on a response.

**Comment by shanear** [comment]
The process has been kicked off

**Comment by shanear** [comment]
John says these might be available right now. Tested them and they are not. Sending him a follow up to kick off the process of opening them up

**Comment by nikitarockz** [comment]
@shanear I agree with John. The last time we asked for end points it turned out we already had them in Prod.

**Comment by shanear** [comment]
Alright, after much back and forth, It looks like they'll be opening up these services this weekend. I'll check up and make sure everything looks good for them after that.

An important note, is that the version in prod is behind the version in linktest for the "domain" (or installation) of services we are using. I don't think it should matter too much, but we should be careful about this.

**Comment by shanear** [comment]
These were tested yesterday and work.

**Comment by shanear** [comment]
BGS blew up today and was rolled back. @kahlouie will be taking over the testing of the service as it gets deployed to preprod and prod this week.

**Comment by kahlouie** [comment]
Tested on 7/21 and looks fine. Found a vet without a participant id
