### ISSUE TITLE
Queue Navigation | Help | Add link to display Training Guide and Quick Reference Guide

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/caseflow#5336]
As a Project Manager, I would like to have clearly visible and accessible links to both the Training Guide and Quick Reference Guides displayed on the Help Page, so that the users can obtain additional detailed information on how to use Queue.

## Acceptance Criteria
**_Introduction Section_**
1. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
1. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
1. Verify that the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" is clicked, the following pdf is displayed in a new tab. [Queue Training Guide_??????](https://github.com/department-of-veterans-affairs/appeals-training/blob/master)
1. Verify that the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" is clicked, the following pdf is displayed in a new tab. [Queue_QRG_May2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Queue/Queue_Quick_Reference_Guide_May2018.pdf)

**_FAQ Answer Section_** 

_"What is Caseflow Queue?"_
1. Verify that in the answer, the text "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Queue Training Guide_??????](https://github.com/department-of-veterans-affairs/appeals-training/blob/master)

_"What if I still need help?"_
1. Verify that in the answer the text "FAQs" is a hyperlink to the “Frequently Asked Questions” section.
1. Verify that in the answer the words "Quick Reference Guide" is a link.
1. Verify that when the link "Quick Reference Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Queue_QRG_May2018](https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Queue/Queue_Quick_Reference_Guide_May2018.pdf)
1. Verify that in the answer, the words "Training Guide" is a link.
1. Verify that when the link "Training Guide" in the answer is clicked, the following pdf is displayed in a new tab. [Queue Training Guide_??????](https://github.com/department-of-veterans-affairs/appeals-training/blob/master))

## Mocks
**_Help Page - Introduction section requiring change_**

**_Help Page - FAQ Answers section:  First Question requiring change_**

**_Help Page - FAQ Answer section:  Last Question requiring change_**

# Related Stories
**_Engineering Pre-requisite_**
Navigation | Help | Create Queue Help page #5335  

**_PM/Training Issues_**
IP | Queue | Create Engineer Story for Training Material Additions [#1800](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1800)
Queue | Training Guide | Develop guide – Throttle Deliverable [#162](https://github.com/department-of-veterans-affairs/appeals-training/issues/162)
Queue | FAQs | Develop questions – THROTTLE Deliverable [#160](https://github.com/department-of-veterans-affairs/appeals-training/issues/160)
Queue | Quick Reference Guide | Develop guide – Throttle Deliverable [#164](https://github.com/department-of-veterans-affairs/appeals-training/issues/164)

**Comment by wturne** [comment]
Added link for Queue Quick Reference Guide (QRG) dated May 2018.  

[Queue_Quick_Reference_Guide_May2018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/2063595/Queue_Quick_Reference_Guide_May2018.pdf)
