### ISSUE TITLE
Investigate BGS endpoint to create tracked item

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5337]
We will need this endpoint in order to complete:

https://github.com/department-of-veterans-affairs/caseflow/issues/5280

We need to figure out where it is and how to call it/connect to it.

Web Service: DocumentService
Web Method: generateTrackedItems

WSDL: https://bepdev.vba.va.gov/DocumentService/DocumentService?WSDL
Schema: https://bepdev.vba.va.gov/DocumentService/DocumentService?xsd=1

**Comment by shanear** [comment]
Talked to Nate and he said that this would be best to do via a BGS endpoint. Sent an email today to John requesting more information there.

**Comment by shanear** [comment]
Talked to John Dell and it looks like we need to submit another service request for this. Sent an email to Tina Edwards to kick that off.

**Comment by shanear** [comment]
We're scheduling a meeting with Nate and John to discuss moving forward on this.

**Comment by shanear** [comment]
Confirmed in a meeting today that Tina and John from BGS will be sending us documentation for this.

**Comment by abbyraskinUSDS** [comment]
They sent us a Sharepoint link last week.

**Comment by shanear** [comment]
<img width="661" alt="screen shot 2018-07-03 at 2 35 22 pm" src="https://user-images.githubusercontent.com/1596259/42238700-c1aa0830-7ecf-11e8-870a-20d336287aae.png">
😢

**Comment by shanear** [comment]
The BGS service does not seem to be implemented. I emailed John to see what to do...

**Comment by shanear** [comment]
got a response from Jinmay 👍
It was in fact, a different service.

**Comment by shanear** [comment]
Looks like the service is not documented in the BGS reference guide. Following up about where the documentation might be.

**Comment by shanear** [comment]
We got the information on the service back, but now it looks like we'll need a tracked item type created in the corporate database before we can begin using the endpoint. I sent a follow up email requesting how to do this.

**Comment by shanear** [comment]
So it looks like we are going to need a submit a Service Request for to create the "Informal Hearing" tracked item. No idea how long that will take but I'm going to forward the email regarding that process.

**Comment by kahlouie** [comment]
Sounds like we already have the HLR Informal Hearing tracked item available to us in dev. We do need to make a call to `manageClaimantLetter_V2` prior to generating the tracked item. Not sure if there's any cases we'll have in caseflow that'll have us `manageThirdPartyLetter_V2` instead of the claimant letter.
