### ISSUE TITLE
Investigate how to send data to VBMS required to route HLRs and SCs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5338]
VBMS is currently working on the ability to attach rating issue ids to contentions we create.

Additionally we should be able to add the "Same Station" special issue to the EP we create.

Need to sync with Nate on the best way to do this.

This is a prerequisite to:
https://github.com/department-of-veterans-affairs/caseflow/issues/5281

**Comment by shanear** [comment]
Nate said he would send the documentation for Claim Service V5, which would allow for this within the week

**Comment by abbyraskinUSDS** [comment]
Nate sent the docs last week, closing.
