### ISSUE TITLE
Google Analytics |  Certification |  Add user cancellation and completion tracking

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#535]
As Product Owner, I would like to track when users are cancelling out of certifying based on the following scenarios so that I obtain metrics, monitor activity and/or make additional improvements.

This will include:
- How many users have started a case in Caseflow and have not finished certifying it in Caseflow
- How many users have started a case in Caseflow and have finished certifying it in Caseflow
- How many users clicked on the “cancel” link to leave Caseflow

# Acceptance Criteria 
1. Verify that after clicking on the **_Cancel_** link on the Electronic Form 8 page, this action is counted as [StartedCancellation] value.
1. Verify that after clicking on the **_Cancel Certification_** button on the Electronic Form 8 page, this action is counted as [CancellationCommitted] value.
1. Verify that after clicking on the **_Upload and Certify_** button on the Form 8 Preview page and the Confirmation page is displayed, this action is counted as [CertificationCompleted] value.
 
## Mockup
View - Electronic Form 8 Page - Starting Cancellation Process
View - Certification Cancellation Page - Backed out of cancellation
View - Certification Cancellation Page - Committed to Cancellation

# Related Stories

**Comment by shanear** [comment]
@shellicious can you confirm what we need to track here?

**Comment by nemodjuric** [comment]
I created this per slack conversation, but it was confirmed by @shellicious that is no longer needed.

**Comment by shellicious** [comment]
I believe we have answers to the first two questions, but we don't have metrics on the cancellation link. So we still need to know the answer to the 3rd question. 

I also don't recall confirming this issue isn't needed, can you refresh my memory @nemodjuric about the conversation?

**Comment by nemodjuric** [comment]
This was from engineering chat room on Dec 6:

Shane Russell [5:34 PM]  
it means, it wasn't completed

Shelly Ni [5:34 PM]  
ohh

[5:34]  
got it

Shane Russell [5:34 PM]  
could mean the cancel button

[5:34]  
could mean they closed the browser

Shelly Ni [5:34 PM]  
3% is low, that’s good

Nemo Djuric [5:35 PM]  
I can add tracking for cancel button them, if Shelly needs it then

Shane Russell [5:36 PM]  
uploaded an image: Screen Shot 2016-12-06 at 5.36.11 PM.png 
Add Comment

Shane Russell [5:36 PM]  
it hovers around 99-97

Shelly Ni [5:37 PM]  
cool

[5:37]  
is this dashboard accessible by people like me who are not on the VA network?

Shane Russell [5:42 PM]  
Nope :pensive:

Shelly Ni [5:43 PM]  
that’s ok! i see the numbers i wanted for now"

My understanding was that this is no longer needed since stats page gave what Shelly was asking. However, we can add tracking for Cancel button clicks, if needed.

**Comment by shellicious** [comment]
Thanks for digging that up, @nemodjuric. I thought the metrics for cancellation issue had already been created earlier that day, given a conversation in #appeals-discovery, and was reassuring Shane that it was OK that the dashboard was not accessible to people outside the VA network. I see how the slack conversation was ambiguous. 

I (and probably other folks!) would like to see metrics on how often the "Cancel" button is clicked, and how often users complete the cancellation process by clicking on a confirmation in the modal that appears. Can we keep this issue open until we have metrics added for those two things?

if the current cancel flow works differently from my assumption above, my suggestion is to track however is possible the number of people initiating the cancellation flow, and the number of people who complete it.

**Comment by shanear** [comment]
@shellicious Do we want to track both clicks to the cancel button, and actual manual cancellations of certifications?

**Comment by shellicious** [comment]
What are manual cancellations of certifications @shanear?

**Comment by shanear** [comment]
@shellicious 

The first is clicking the button here,
<img width="1554" alt="screen shot 2016-12-09 at 5 44 07 pm" src="https://cloud.githubusercontent.com/assets/1596259/21067075/1bd13730-be37-11e6-919e-65984e768287.png">

And the second is clicking "Yes, I'm sure" here. Which would manually cancel the appeal
<img width="1554" alt="screen shot 2016-12-09 at 5 43 45 pm" src="https://cloud.githubusercontent.com/assets/1596259/21067064/1056264a-be37-11e6-8638-ed8d48b8b6a7.png">

**Comment by shellicious** [comment]
@shanear @nemodjuric Yes, it would be great to track both clicks.

**Comment by laurjpeterson** [comment]
@nemodjuric - Can you confirm that we are tracking cancellations? Since #1173 was created after this one, it seems like we might be.

https://github.com/department-of-veterans-affairs/caseflow/issues/1173

**Comment by laurjpeterson** [comment]
I don't think this is relevant anymore, closing.
