### ISSUE TITLE
AMA intake | Confirmation: NOD success

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5359]
When a Claims Assistant has successfully created an appeal, we show them a confirmation page so they know the intake is complete.

## Acceptance Criteria
- After selecting "Establish appeal" button in previous step, create appeal in database 
- If a user successfully creates an appeal by selecting the "Establish appeal" button in the previous step, show them a success page (see mock below)
- The page includes the name of the Veteran and the name of the form
- Dependent on #5240 

## Mocks
![image](https://user-images.githubusercontent.com/4042181/39601705-df06042e-4ef0-11e8-91cd-c5b66ed3e268.png)

**Comment by leahbannon** [comment]
looks good
