### ISSUE TITLE
Investigate non-deterministically failing tests.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#536]
There is a strong suspicion among our lovely team that some certification-related tests fail non-deteministically. This is a difficult problem to reproduce, but it definitely causes a lot of development friction. Ten or twenty minutes spent fruitlessly debugging a PR here and there adds up! We should investigate this and see if there's a fix. Even if you take this task on and **don't** fix anything, please add notes detailing what you tried and where you looked, so the next person to try can have more context!

## List of non-deterministic travis failures
- <https://travis-ci.org/department-of-veterans-affairs/caseflow/builds/202739706>  (Confirm Certification -> Successful certification)

**Comment by kierachell** [comment]
This one fails about every 20 runs - Travis and Locally

<img width="732" alt="screen shot 2017-01-24 at 15 31 55" src="https://cloud.githubusercontent.com/assets/18075411/22298431/82ce92a8-e2ee-11e6-997c-5f968d6f97a0.png">
<img width="677" alt="screen shot 2017-01-25 at 10 26 07" src="https://cloud.githubusercontent.com/assets/18075411/22298433/83c93d8e-e2ee-11e6-9c58-ff134f7f20ed.png">

**Comment by amprokop** [comment]
interesting, @kierachell! great find.

**Comment by amprokop** [comment]
```
  scenario "Screen reader user visits pdf link" do
    visit "certifications/5555C"
    # We want this content to only appear for screen reader users, so
    # it will not be visible, but it **should** be in the DOM.

    expect(page).to have_content("The PDF viewer in your browser may not be accessible.")
    expect(page).to have_css(".usa-sr-only", visible: false)

    # Sending click or keypress events to elements that are not in the DOM doesn't seem to work,
    # so let's find the hidden link's href and visit it manually to check that the pdf can be
    # found there.
    pdf_href = page.find("#sr-download-link")["href"]
    visit(pdf_href)
    content_header = page.response_headers["Content-Disposition"]

    expect(content_header.include?("form8-TEST.pdf")).to be true
  end
```

The test in question. The only thing I can think of offhand is that the resource might not be loaded when we're checking the headers? Capybara is usually so good with waiting tho.

**Comment by kierachell** [comment]
Another random failure after 40 more builds on Travis.
<img width="945" alt="screen shot 2017-01-25 at 12 59 28" src="https://cloud.githubusercontent.com/assets/18075411/22303402/24d333b2-e301-11e6-9eb1-71d587ef2d64.png">

**Comment by mdbenjam** [comment]
Yeah, I had a test last week that checked database values before checking screen content after submitting a post request. The database values were not changed before I arrived on the page. I'd be curious what would happen if we:

1) put a sleep after the visit
2) change our expect to be something like 

```
expect(page.response_headers).include?("form8-TEST.pdf")).to be true
```

Not sure if that syntax is right, but I wonder if putting page inside expect forces capybara to wait for a while.

**Comment by amprokop** [comment]
good call. @kierachell, since you seem to have a rig set up to run the specs continuously, can you try @mdbenjam's suggestion?

**Comment by amprokop** [comment]
it would be 
```
expect(page.response_headers.include?("form8-TEST.pdf")).to be true`
```

i think

**Comment by kierachell** [comment]
So here's an updated error: I suspected that `pdf_href` was not generated:
<img width="703" alt="screen shot 2017-01-25 at 14 47 21" src="https://cloud.githubusercontent.com/assets/18075411/22306443/4c86f9dc-e30d-11e6-8a92-601da25dadf9.png">

**Comment by kierachell** [comment]
It seems like `content_header = page.response_headers["Content-Disposition"]` gets lost sometimes and no matter how long you wait it won't load.

**Comment by kierachell** [comment]
Got a new one popping up now:
<img width="815" alt="screen shot 2017-01-30 at 09 31 18" src="https://cloud.githubusercontent.com/assets/18075411/22426840/e1f8fc6c-e6ce-11e6-8267-463341531273.png">

**Comment by amprokop** [comment]
@kierachell — yeah I agree that revisiting is hacky. if there are other PDF tests failing like the above ^, perhaps this is a PDF.js bug.

**Comment by mmlumba** [comment]
I've started to have this test fail on me from time to time:
<img width="764" alt="screen shot 2017-01-31 at 9 40 19 am" src="https://cloud.githubusercontent.com/assets/4773320/22469238/4f832eea-e799-11e6-8d34-11d22ccab0d3.png">

**Comment by mdbenjam** [comment]
Darn, yeah I was afraid of that when I added the test. I think I know what's going on. I made a ticket to fix it. #793

**Comment by kierachell** [comment]
added a small PR:
Adjusted the reader test;
Apparently `google-analytics` was not disabled fully, so sometimes the tests would fail because they couldn't reach Google...yeah
Removed a couple of random warnings that are obnoxious

There is a pending test and no one is owning up to it. Want me to delete it or what's up?

**Comment by joofsh** [comment]
@kierachell You can look through git history to see who added (or in this case skipped) a test. I commented out because it did not make sense with the existing codebase, but will be a feature we reintroduce in the near future

**Comment by mdbenjam** [comment]
Just saw a new one: 

![screen shot 2017-02-07 at 11 51 31 am](https://cloud.githubusercontent.com/assets/3885236/22701507/ce48b744-ed2b-11e6-9f9c-986e06d528a6.png)

**Comment by mmlumba** [comment]
Another one:
<img width="1280" alt="screen shot 2017-02-13 at 7 11 56 pm" src="https://cloud.githubusercontent.com/assets/4773320/22909161/8064818a-f220-11e6-83d2-43b6379b0877.png">
