### ISSUE TITLE
[Spec] What is the best way to separate Dispatch Task from Queue Task.

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#5360]
In the previous [tech spec](https://github.com/department-of-veterans-affairs/caseflow/issues/5310) we made a decision to not re-use an existing Dispatch `task.rb` and create a new Task model for Queue. This tech spec will examine a few options on how to proceed.

#### Option 1: Rename `Task` to `DispatchTask`
* Rename `task.rb` to `dispatch_task.rb`
* Rename `tasks_controller.rb` to `dispatch_tasks_controller.rb`
* Move `tasks/establish_claim.rb` to `dispatch_tasks/establish_claim.rb`

#### Option 2: Move Dispatch classes under `dispatch` directory
* Move `task.rb` to `dispatch/task.rb`
* Move `tasks_controller.rb` to `dispatch/tasks_controller.rb`
* Move `tasks/establish_claim.rb` to `tasks/dispatch/establish_claim.rb`

#### Option 3: Leave Dispatch classes the way they are
* That's assuming we will go with option 1 for Queue Code Organization

#### Option 1: Put Queue classes under `queue` directory
* `queue/task.rb`
* `queue/tasks_controller.rb`
* Put all queue tasks under `tasks/queue`

#### Option 2: Queue Task will become a primary Task
* `task.rb` will become a Queue task
* `tasks_controller.rb` will become a Queue task controller

**Comment by evankroske** [comment]
I don't think that the readability benefits of renaming Task are worth the effort and risk involved. I vote for Dispatch option 3 and Queue option 1. However, I don't feel very strongly that we shouldn't rename Task. If Anya really wants to clean up the code, I'm OK with that.

**Comment by tejans24** [comment]
+1 for option 2 for Dispatch and option 1 for Queue.

**Comment by mdbenjam** [comment]
I think I agree with Evan, but think Anya's approach is best if we decide refactoring names is worth it. Don't have strong feelings.
