### ISSUE TITLE
Record the user's email address and DB id when reporting Sentry frontend errors

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5361]
https://docs.sentry.io/clients/javascript/#adding-context

# AC
- User email and id should be reported to Sentry when frontend errors are sent.

**Comment by evankroske** [comment]
We should probably use Sentry's built-in user metadata system: https://docs.sentry.io/learn/context/#capturing-the-user

**Comment by amprokop** [comment]
@evankroske that's what the open PR does afaik

**Comment by laurjpeterson** [comment]
@pkarman [non-urgent] do you know if we already do this?

**Comment by pkarman** [comment]
yes! e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4114/
