### ISSUE TITLE
Cases Checked In | Don't show worksheets for hearings that were not held

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5371]
Cases Checked In - Don't show worksheets for hearings that were Canceled or No Show

## AC
1. On the judge and attorney Cases Checked in page (Queue or Reader) don't show worksheets for hearings where that hearing's disposition is marked as No Show, or Canceled

**Comment by MeredithStewart** [comment]
This will be easier to do post February in Caseflow.
