### ISSUE TITLE
Store CircleCI's full output logging as a file artifact

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#5372]
For our ATO we need to provide the CI output of random builds during a sprint.  

This was easier to obtain with Travis.  We'll need to adjust our CircleCI builds so that we can store and obtain these artifacts as well. 

Details of how to do this:

https://discuss.circleci.com/t/view-or-download-full-output-logs/247/7
https://discuss.circleci.com/t/uncapped-logging-output/3367

**Comment by sansb** [comment]
Do we need to supply this as a single file? Do we need to include all generated artifacts? Or just the straight log output we see on the build page?

**Comment by sunil-sadasivan** [comment]
Update, yeah we need this as a log/output file that can be converted to a PDF rather than a CircleCI link

**Comment by sansb** [comment]
OK. When do we need this by?

**Comment by sunil-sadasivan** [comment]
Think we're good for now, but Kate needs to pull up these reports every month I _think_.  So ideally sometime in the next few weeks would be great!

**Comment by sansb** [comment]
https://circleci.com/docs/api/v1-reference/#build

**Comment by KCollinsBrown** [comment]
cc @nikitarockz Thanks @sansb for your help with this and @sunil-sadasivan - I basically just upload the code reports (not sure of how to describe them exactly) into Rational, as a way to show that we test our code, etc.

**Comment by sansb** [comment]
@KCollinsBrown here's a working example. To get the full output, you'd go to a build (use this one for now: https://circleci.com/gh/department-of-veterans-affairs/caseflow/3340), click "Artifacts", click "Container 0 > home > circleci", then click all_logs.log. Then you can save as PDF. Will this work for you?
