### ISSUE TITLE
Create issues in the order they are selected

### ISSUE THREAD

**Issue by sansb** [department-of-veterans-affairs/caseflow#5375]
We should create them in the order in which they were selected if possible, as this will make it easier for the next person to review them in order. (presumably the user will select them in the order they appear on the form - something to user test)

See https://github.com/department-of-veterans-affairs/caseflow/issues/5283#issuecomment-386072571

**Comment by abbyraskinUSDS** [comment]
This is not a priority, and will be accounted for in other improvements to the issues selection flow. Closing.
