### ISSUE TITLE
Hearing Worksheet | Adjust layout of hearing info

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5379]
Hearing Worksheet: Clean up Header and Veteran Info to sync with the way that judges read this information for the transcript during the hearing

Partner to issue: https://github.com/department-of-veterans-affairs/caseflow/issues/4233

## AC 
1. Display the VLJ name, Hearing type, RO, and hearing date horizontally across the page.

## Mock
![hearing info](https://user-images.githubusercontent.com/4975959/39547715-625a1a34-4e26-11e8-85d8-aeb0b1601c8d.png)

**Comment by sharonwarner** [comment]
Duplicate of #4233
