### ISSUE TITLE
Intakes does not gracefully handle an appeal without an nod_date

### ISSUE THREAD

**Issue by sansb** [department-of-veterans-affairs/caseflow#5384]
Unclear to us whether this is actually an issue- would an appeal in the wild ever not have an nod_date?

**Comment by nicholasholtz** [comment]
In my thinking, in the world of RAMP, if there is no NOD, then probably Intake shouldn't handle it gracefully - someone probably should have to stop what they are doing and find out why there is a RAMP form but no record of an appeal that could be opted-in.

**Comment by sansb** [comment]
This is what happens currently:
<img width="1344" alt="screen shot 2018-05-03 at 10 40 04 am" src="https://user-images.githubusercontent.com/299486/39593381-6c1d3612-4ebe-11e8-874e-c3ab73f6e4e5.png">

**Comment by shanear** [comment]
Thanks for asking @sansb 

Agree with nicholas. NODs are required to start an appeal so I think we can assume that they will all have nod_dates. Gonna close this.
