### ISSUE TITLE
Judge queue | Handle Acting Judge case

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5385]
Some attorneys were previously acting judges. An acting judge is an attorney who had applied for the privileges to hear Veteran cases at a hearing and therefore decide/sign those decisions. They do not write the decisions for these cases. Instead, another attorney writes them. The frequency of acting judges has decreased over time.

These attorneys need a way to toggle between the Judge view of queue and Attorney view.

- There are 373 appeals pending where a hearing was held by an active attorney in an acting VLJ capacity. 
- There are 57 different attorneys who held hearings for those appeals. 
- There are roughly ~400,000 active appeals.
- So, this would affect 57 out of ~700 attorneys (soon to be ~1000). 

## AC
- Attorneys who also have the judge role in VACOLS should see a role toggle in their queue page
- Attorneys who also have the judge role in VACOLS should default to the attorney role
- When the attorney toggles to the judge view, they should see the judge Review cases (x) | Assign cases (y) view

## Mocks
To be reviewed by team before development can begin

#### Attorney View
![queue_actingjudge_attorney_inactive](https://user-images.githubusercontent.com/31224257/41553051-a0148c9a-72fe-11e8-9a63-36670f9fe1ec.png)

#### Switching to Acting Judge via toggle
![queue_actingjudge_attorney-toggle](https://user-images.githubusercontent.com/31224257/41553052-a027d930-72fe-11e8-8895-1ca84a59394a.png)

#### Judge View
![queue_actingjudge_inactive](https://user-images.githubusercontent.com/31224257/41553053-a03da4a4-72fe-11e8-9f01-2a994686087a.png)

#### Switching to Attorney via toggle
![queue_actingjudge_judge-toggle](https://user-images.githubusercontent.com/31224257/41553054-a0962ea8-72fe-11e8-9d8f-84bc53802add.png)

### Discusion  5/2
- aiming for the simplest option --> toggling between roles will be the easiest from the back end
- @aroltsch will pull the number of users in VACOLS that are both acting judges and attorneys
- @sneha-pai will explore a role toggle pattern
- goal: solve for acting judges by the time we roll out to judges (aiming for week of 5/14/2018)

**Comment by evankroske** [comment]
Personally, I think that a regular dropdown would be the most clear:
```
Role: | Acting Judge |
      | Attorney     |
```

**Comment by laurjpeterson** [comment]
I agree with the dropdown!

**Comment by amprokop** [comment]
👍this could work, @dannysellers or @evankroske could probably make an evaluation of engineering lift here if we needed

**Comment by amprokop** [comment]
![image](https://user-images.githubusercontent.com/3781835/40941441-b592e15c-67ff-11e8-976d-db010143c334.png)

**Comment by dannysellers** [comment]
I'm sure there are prefab toggle switch React components we could find that would make the overall engineering lift pretty minimal, but I don't know that a dropdown is any less clear, and would take slightly less time.

I'm not sure how complicated it would be to switch roles without reloading the page—we'd basically have to restart the site—but with reloading the page I don't think it'd be too difficult

**Comment by laurjpeterson** [comment]
@amprokop - re: not stitching them into the existing "Your Queue" view. I believe we all had this conversation about a role toggle together at the whiteboard in Hoth and that surfaced the toggle as the simplest option. 

Shall we move forward with the dropdown option? @sneha-pai @dannysellers @evankroske

**Comment by sneha-pai** [comment]
@laurjpeterson @amprokop @mkhandekar Regarding Alex's comment above re: stitching this toggle to the Queue components more closely: what if we added this role toggle to the top left or right area, floating above the queue container (especially if we're moving search to navigation)?

Thoughts?

**Comment by mkhandekar** [comment]
I just want to make sure I'm understanding the different approaches clearly. 

### 1. User sees all cases for both roles in one table 

My read of Alex's comment:
> i guess we've decided not to stitch these tasks into the existing "Your Queue" view? 

... is to not show a universal toggle, rather, show all tasks in the table normally, and 
-  add a column that indicates whether X case is assigned to them as an judge vs attorney
- have a different set of "actions" (drop down) based on the role
- **scope:** this seems to me a more streamlined user experience, but has implications for crowding table rows more than they are now. we could move towards this approach later on, when our tables include more mature functionality and UX for filtering and sorting cases. part of maturing the tables includes an option to stop showing an actions dropdown per row, and make it a more universal action somewhere in the table header (similar to gmail), which leaves us more room to include a role column.

### 2. User has to choose an option from the role dropdown to see cases for that role

@sneha-pai Yes! Moving the dropdown closer to the table so that it is more clear what that action will affect, might look like this:

![image uploaded from ios](https://user-images.githubusercontent.com/1598889/40990169-ed081c60-68bd-11e8-9f8d-fd54f3519c9a.jpg)

- we still need to chat about whether and how _your work, in progress, on hold_ live on the page together. even if we don't have _your work_ as a page title, let's put the role drop down to the right.
- **scope:** this seems to be the lightest weight option to implement now.

**Comment by laurjpeterson** [comment]
during 10/31 BVA leadership/DS meeting, BVA leadership decided we should not focus on building functionality for acting judges because she will be reassessing whether AVLJs will still be in use come January

**Comment by sneha-pai** [comment]
Anya's notes: 

A few things to think about: 1. When a user with both roles loads a queue page, do we display a role toggle? 2. When a judge assigns a case to a user with both roles, should we give a judge an option to choose which role (attorney or judge) to use or do we want to default to a role on the BE?

**Comment by sneha-pai** [comment]
### Discussion Questions: 

Do we need to rely on roles at all (technical part)?

### Activities we need:

**Review cases:**
- Attorney drafting decisions (assigned by Judges) and assigning administrative actions (to VLJ support)
- Attorneys (as Acting Judges) signing cases (assigned by their attorneys), signing motions.

**Assigning cases:**
- Attorneys (as Acting Judges) assigning cases to attorneys

**Comment by laurjpeterson** [comment]
LP's raw notes:

* Reason for acting judges 
	* VACOLS staff record, indicator that they’re an acting judge
* Can we disassociate role type from acting judges entirely?
	* Assigning tasks = team view
		* Ask users to choose what task to assign
	* Queue view = individual 
		* All tasks become the individual queue
		* JudgeAssign - org/team view
			* pick a single role?
* Can we delay acting judges after DAS deprecation?
	* Build role-agnostic acting judge flow for AMA appeals first
	* Create an acting judge organization?
		* check if a user has a judge team
* Attorney/judge configurations are different, they have different columns
* Attorneys are already showing QR tasks in their queue, Judges have QR tasks
* Attorney, new acting judge - how do they get to their team queue
	* Caseflow team management page to add the judge. Can call it an acting judge
* Acting judges need to be able to request cases (?) automatic case distribution
	* Requesting only hearing cases
	* Can they receive tasks without auto-case distribution? Suggest that this would need to happen
* How do acting judges decide which attorneys to assign cases to? 
	* Allow users to select Other
* Acting judges after deprecating DAS
	* If we need to do it first, Consolidate LegacyTasks into one thing to have better actions if we wanted to enable Acting Judges before DAS deprecation
		* create one LegacyTask with different actions?
* Caseflow determination for judge attorney roles before fully deprecating DAS too
* Exclude acting judge from attorney/judge pilot

**Comment by laurjpeterson** [comment]
LP's todos:
- external/stakeholder facing overview of DAS deprecation

**Comment by laurjpeterson** [comment]
The Board has appointed more acting judges. We haven't deprecated DAS yet (and aren't likely to do so in the next few months). Posting those acting judges here so we have them.
 
[01-19-03 AVLJ June.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/3245328/01-19-03.AVLJ.June.pdf)

**Comment by laurjpeterson** [comment]
Note: another idea about acting judges - creating an organization, here https://github.com/department-of-veterans-affairs/caseflow/issues/10029. We may end up wanting to close this issue in favor of a more up to date one.

**Comment by laurjpeterson** [comment]
Closing this ticket because it's over a year old. 

Acting judges _can_ complete all their work for AMA cases. They're still working on legacy cases in VACOLS.
