### ISSUE TITLE
Spike: investigate VBMS eFolder API to see if it's impossible to fetch 21-22

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5386]
Forms [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf) and [21-22A](https://www.vba.va.gov/pubs/forms/VBA-21-22A-ARE.pdf) are the way Veterans express their wishes for legal representation (21-22 assigns power of attorney to a service organization, 21-22a  individual

We can currently fetch documents like Form 9, NOD, etc using a "type" attribute provided by VBMS. Last year, we were told that 21-22 and 21-22a weren't typically identifiable using that type attribute. Let's double-check to verify.

- Find a few Veterans' eFolders with 21-22 and/or 21-22a
- Make manual eFolder API calls to VBMS for those efolders
- Determine whether or not document types are present for those forms like they typically are for Form 9, NOD, etc

**Comment by amprokop** [comment]
@laurjpeterson — is it easy for you to ask some BVA employee for a few file numbers for Veterans with 21-22 and 21-22as?

**Comment by alisan16** [comment]
Closing as this is now obsolete.
