### ISSUE TITLE
[Spec] How we can track co-located admin actions in Caseflow

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#5389]
## Attorney Queue

Attorney's queue will contain in-progress and on-hold columns. In-progress column will contain attorney's tasks they are working on and on-hold column will contain admin actions they've assigned to a co-located staff member. Attorney's in-progress tasks will be pulled from VACOLS while attorney's on-hold tasks will be pulled from Caseflow. 

When an attorney creates an admin action, they can select a co-located team (A or B), enter action type and instructions. On the backend, we will automatically determine which user has the least amount of assigned/in progress tasks for the selected team and assign the task to that user. This will create a Task record in Caseflow database that will contain the following information:

* appeal ID 
* assigned by user
* assigned to user
* action type (e.g, Waiver of AOJ letter)
* status (will be `assigned` on the initial creation)
* instructions 
* assigned on date

##### In Progress Tasks
A co-located staff member can view assigned/in-progress tasks that will be pulled from Caseflow `tasks` table using their Caseflow user ID number. Caseflow Task will have an appeal_id so we can get any appeal's information from VACOLS (e.g, type: AOD, Remand, etc). 

##### On Hold Tasks
When a co-located staff member places a task on hold, on the backend we will update a status column to `on-hold`. If they need to add a reason and duration for putting a task on-hold, we can add additional columns to the Task table:
* on hold reason
* on hold due date

##### Complete Task
When a co-located staff member completes a task, on the Caseflow side we will update task status to `completed` and update a datetime `completed_at` to the current time. We will also make a request to VACOLS to update appeal location to attorney's location.

**Comment by amprokop** [comment]
Nice! I like the A few thoughts—

In this approach, when an attorney creates a co-located task, what is updated in VACOLS, if anything?

> On the backend, we will automatically determine which user has the least amount of assigned/in progress tasks for the selected team and assign the task to that user.

Not sure it's yet clear how we would determine who receives a task. Maybe we should leave this as an explicit open question for now, there may be a lot of process concerns.

**Comment by mkhandekar** [comment]
👀

**Comment by laurjpeterson** [comment]
@amprokop yep, will schedule more time with co-located. In general, reports are for co-located to prove their productivity. I do not know how tied to performance evaluations they are, but will find out.

Here's what we have from last year so it's on this thread. 

From Eugene Scott, co-located supervisor:
> At the end of the day, he updates a master spread sheet that keeps track of all the types of work done. This is compiled into a weekly report for his Chief, Ty Walls. He keeps track of:
> - Cases charged to location 30 (LP note: this is a location that appeals go to after a judge has signed the decision and it's ready for dispatch)
> - Cases charged to location 4E, 4W, 3W (LP note: these locations are deprecated. Co-located locations are 11 and 12. 4E was reopened for the interactive decision template (IDT) pilot)
> - Correspondence to OVLJ Support pending due in the next 7 days	
> - Mail closed in a particular day
> - How much Mail is pending
> - Merging pending (from email)
> - He also responds to requests for reports from Lit, Team lead, and the admin section chief (Ty)
> - He also runs a mail report to see if anything is assigned back to Eugene

https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/BVA%20Work%20Queue/Research/Notes/Eugene%20Scott%20Co-located%20Support.MD

From Tim Owens, co-located team member:
> Lots of different reports to identify what needs to actually be worked.
> - Mail reports
> - Location reports
> - Shared inbox emails
> - Past due daries
> - Individual charges

https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/BVA%20Work%20Queue/Research/Notes/Timothy%20Owens%20Co-located%20Support%203W.MD

**Comment by laurjpeterson** [comment]
Option 1: update the below fields in VACOLS = backwards compatibility
- Current VACOLS location + user (e.g. Location 11 - ESCOTT, Location 12 - TOWENS)
- Assigned on date 
- Assigned by (e.g. attorney) - could require updating Prior Locations table

cons:
- if we are backwards compatible and another VACOLS user assigns the case out of co-located user to another team, our caseflow table fields won't make sense (e.g. our status column of in-progress)
   - if this is an edge case, we could show an error state to the user

Option 2: no backwards compatibility

- no Board users will be able to see cases at co-located
- Co-located won't be able to run their Daily Reports for DVC

Auto-assignment options:
1. assign from attorney straight to co-located user (e.g. with the least amount of tasks)
    - pros: 
        - no middleman queue (location 11 or 12) - prevents delays 
        - might get through tasks more quickly
        - a user has ownership of a case at all time. if mail comes in, for instance, co-located user is responsible for it
    - cons: 
        - all users might have too many tasks
        - what happens when users are out of the office? (might not be a big change from today)
2. ask users to click to retrieve a task (like Caseflow Dispatch)
      - pros:
      - cons:

**Comment by laurjpeterson** [comment]
[copy of VLJ Admin Spt Daily Report.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/1984635/copy.of.VLJ.Admin.Spt.Daily.Report.xlsx)

**Comment by aroltsch** [comment]
@laurjpeterson we can have more than one action type if we go with option 2 or 3.

**Comment by laurjpeterson** [comment]
@amprokop @aroltsch - i just discovered that the report above, correspondence rows, contains just cases in location 24, abeyance. not 11 and 12 like originally thought.

I will keep you posted after my convos with Kim Osborne. I still think option 4 is viable! Will find time to chat with @nicholasholtz about it too.

---
From co-located:

The Correspondence received, processed and coming due are for cases in loc. 24 after they are moved from loc. 11/12. When they are in loc. 11/12, they are just pending assignment to co-located admin staff.

There is another report that is used to get those numbers which I did not go over with you. The report is accessed by going to Custom Reports ( VACOLS Reports) / Admin. Productivity/ Diary Action Summary.

This report will give a list of various actions listed in the diary drop down. Too columns are provided. They are diaries closed which is correspondence processed and diaries added which is correspondence received.

The only actions we use to get our teams numbers are Ext, HCL, IHP, OTH, POA, PRIV and TRAN. We add the total for each admin action and that is how we receive our Correspondence received and Correspondence added numbers.

To find the correspondence coming due (7 days) is found by going to Diary Reports (VACOLS 3) / Coming Due / Branch office / Law Judge Support.

- **Correspondence Received** (VACOLS Reports>Custom Reports>Admin Productivity>Diary Action Summary (Added/Closed)>Enter Date>Run) – Column 1
   - Contains all correspondence (Diaries Added) for location 24 after they are moved from loc. 11/12. (Focusing on actions that we take…i.e. EXT – Extension Request / HCL – Hearing Clarification Letter / IHP – Drafting of IHP / OTH – Other Admin Action Needed / POA – POA Clarification Letter / PRIV – Privacy Act Fulfillment).

- **Correspondence Processed** (VACOLS Reports>Custom Reports>Admin Productivity>Diary Action Summary (Added/Closed)>Enter Date>Run) – Column 2
    - I asked: Are they all cases that were assigned back to attorneys only? 
    - Response: Ideally yes, once the diaries are updated and closed, the admin action has been completed and charged back to the attorneys for further review.  However, keep in mind, some diaries are created for tracking purposes and for follow-up., i.e. I may create an diary for the hearing branch and charge to location 57, my diary is primarily for a paper trail that contains the admin action taken….so, I may close that diary if the case will remain with the hearing branch pending scheduling of a hearing.  In this instance, the diary was closed, and case not charged back to the attorney staff.  Once hearing branch completes their actions, they will either charge back to the attorney or the admin staff.
 
- **Correspondence Coming Due (7 Days)**? (VACOLS>Diary Reports>Coming Due>VLJ Branch>7 days>(click assignee)>Run)
     - To find the correspondence coming due (7 days) is found by going to Diary Reports (VACOLS 3) / Coming Due / Branch office / Law Judge Support.

**Comment by nicholasholtz** [comment]
From speaking with some folks at the Board, I think we can get rid of the  co-located team (A or B) designations. Not final decision on that yet, but just wanted to post that for awareness.

**Comment by laurjpeterson** [comment]
@aroltsch @amprokop @nicholasholtz - Met with DVC Osborne and Cherry Crawford today. Some actions:
- They are bought in to a Caseflow location, knowing that they can have oversight into what co-located is doing.
- When reviewing the reports, they didn't really know what the data in those reports meant, so we talked about what she'd like to know.
- In weekly, rather than daily reports, she wants to know:
  - how many actions attorney assigns to co-located
  - how many actions co-located puts on hold (or moves to another team)
      - co-located should not be held accountable for cases that have to move off their plate (e.g. move to FOIA) 
  - actions should be focused around: Extension Request / HCL – Hearing Clarification Letter / IHP – Drafting of IHP / OTH – Other Admin Action Needed / POA – POA Clarification Letter / PRIV – Privacy Act Fulfillment
- She understands that mail won't be part of Caseflow with these initial releases

## Next steps
- I will meet with co-located admin chiefs to let them know about the Caseflow location and ideas for reporting
- She was amenable to naming a date for when co-located will no longer be completing dispatch related tasks (location 31 and 32) and pushing forward the IDT rollout. This is helpful for us, because it reduces the types of tasks co-located has to do overall. They can just work admin actions in Caseflow and mail in VACOLS, rather than both mail and dispatch tasks in VACOLS.
- We will need to map out options for co-located when the admin action requires moving the case to another team. I think the simplest is asking them to search for these cases in VACOLS and move them using VACOLS, but open to other ideas.
