### ISSUE TITLE
Move EFolder to use S3Service from Caseflow-Commons

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#539]
We recently migrated the S3Service code to Caseflow-Commons. In order to not duplicate, let's use this version instead.

**Comment by aroltsch** [comment]
Testing Notes:
Test Caseflow and eFolder on UAT and demo to ensure nothing breaks.

**Comment by kierachell** [comment]
Having a hard time checking if this is an issue with this particular change or VBMS in general:
<img width="1129" alt="screen shot 2017-02-14 at 10 17 48" src="https://cloud.githubusercontent.com/assets/18075411/22934956/e39f62d2-f29e-11e6-97dd-bd880303bc97.png">
<img width="1075" alt="screen shot 2017-02-14 at 10 18 00" src="https://cloud.githubusercontent.com/assets/18075411/22934955/e399af5e-f29e-11e6-9f83-1cb8d3af9aa6.png">


Out of 5 eFolders tested, all failed on `FetchDocument` for some documents.

**Comment by kierachell** [comment]
**PASSED**
Seems like VBMS is back up to speed;
outside of regular eFolder errors functionality seems to be intact
