### ISSUE TITLE
Only show link to Hearing Worksheet if a judge used it for a hearing

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5391]
Today, attorneys can open a Hearing Worksheet from the link in Case Details regardless of if their judge used that Hearing Worksheet for their hearing. Suggest to remove the link if the judge did not have access to Hearing Prep for that hearing, or if the judge did not use Hearing Prep for that hearing. Perhaps the "mark case as prepped" check box would be a useful way to determine that Hearing Prep was used, but trust tango with the solution here!

## AC
- Attorneys only have access to Hearing Worksheets from Hearing Prep that judges have used/taken notes in.

**Comment by sharonwarner** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/5345

This is how we did it in Reader, though there's a bug because hearing.user is sometimes nil. We'll have an updated PR later today.
