### ISSUE TITLE
Deactivate Case Details link for paper cases

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5394]
When an attorney tried to open a paper case (BVA decision date of 1999) from the Case List, the page did not load. I checked in VACOLS and the case was indeed a paperless case. I suggest we put together an error state, or deactivate the link for paper cases. 

## AC
- When the case is paperless, deactivate the Case Details link.
- Underneath the Veteran's name, like where we have "The Veteran is not the appellant", include the copy:
   - This is a paper case.

**Comment by amprokop** [comment]
`FOLDER.TIVBMS` is the field that denotes paper cases. Need to check the values.

**Comment by amprokop** [comment]
@laurjpeterson should this be kicked to design, or would you prefer to add some guidance here e.g. paper cases should have their links greyed out with a message below
