### ISSUE TITLE
Persist issue dispositions in the attorney check out flow

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5396]
An attorney received a case that his judge asked him to make revisions on. So, he had already entered issue dispositions in his initial check out to the judge. Upon starting the check out flow again after he got the case back, all of those dispositions were cleared. These issue dispositions should persist so the attorney does not have to do double work. This is like how we persist the attorney's issue dispositions for judge check out.

## AC
- If a case already has issue dispositions selected and the attorney initiates check out flow, those issue dispositions should be pre-populated.

**Comment by laurjpeterson** [comment]
@amprokop - no, the judge didn't clear the dispositions. I saw them set in Case Details before the attorney checked out.

**Comment by dannysellers** [comment]
That's correct, when the user [goes to Select Dispositions](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueDetailView.jsx#L67), we non-destructively wipe issue dispositions to force the user to choose one per issue. We can stop doing that, but my understanding was that we wanted to force the user to set dispositions

**Comment by amprokop** [comment]
👍 yeah i think we should stop doing that. wanna open a PR when you have time?
