### ISSUE TITLE
Create Release Notes Page

### ISSUE THREAD

**Issue by gmorgana-va** [department-of-veterans-affairs/caseflow#540]
Create a page to capture release notes + add link to page in user drop-down menu

**Comment by KHarshawat** [comment]
![image](https://cloud.githubusercontent.com/assets/6335546/12460841/d15088ee-bf83-11e5-81d9-bd2cba0c2ab5.png)

**Comment by KHarshawat** [comment]
@webinista we need this b/c unions would like to see what's changed. I was thinking we could include something similar to slack's feature.

![image](https://cloud.githubusercontent.com/assets/6335546/12460940/4e6df280-bf84-11e5-83dc-7434ba285b75.png)


Let me know if you have questions!

**Comment by webinista** [comment]
@KHarshawat Can you talk me through this? Is the intention here to indicate that something is, in fact, new using an icon? I'm thinking about how best to track when the what's new page has changed.

**Comment by KHarshawat** [comment]
Heya Tiffany, I think for now we'd just like a log of major feature changes or improvements. It'd be a standalone page that we could update whenever we have some big new change to announce (such as adding letter generation). We could also include smaller updates such as bug fixes but given that we'll be deploying almost daily for a while, not sure what the inherent and visible value is besides "We're making it better."

**Comment by webinista** [comment]
**Status**:

I decided to make this a bit more robust, and turn it into a more Slack-like feature with an indicator. That will take a little more work. Need to store the last time a user visited the _What's New?_ page, in addition to checking whether there are updates. Outlines of that JS are done, just need to adjust my approach. 

In the meantime, the routes and templates are in place. Do we have content for this page?
