### ISSUE TITLE
Establish AMA EPs in the NWQ

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#5400]
Establish AMA EPs in National Work Queue
National Work Queue (station 499)

Right now we're using the same station as RAMP, which seems to be using a Regional Offices file. In order to add National Work Queue, we should get the data to add it there. Abby says it's not really a Regional Office so not sure if we're adding it there.

**Comment by shanear** [comment]
This is a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/5928.

Closing
