### ISSUE TITLE
Keep order of issues when any changes are made

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5401]
After an attorney edited issues, the list of issues changed order. We should attempt to keep issues in the same order they were inputted so attorneys can find them easily.

## AC
- When an attorney edits an issue, issues remain in the same order.
- If an attorney deletes an issue, the issues below/after it in order moves up. 
- If an attorney adds an issue, it is added to the end of the list.

**Comment by dannysellers** [comment]
I'm not able to reproduce this—issues stay in order as expected 😕. Was there any specific operation done that caused the order to change?

**Comment by laurjpeterson** [comment]
Hmm. I saw it happen when the user edited an issue, and then came back to the select dispositions screen. If you can't reproduce it no worries. It may be one that we wait and see if it happens again.
