### ISSUE TITLE
Prevent clearing all issue dispositions when editing an issue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5402]
When an attorney edited an issue today, all other issues' dispositions were cleared. We should persist issue dispositions for all issues despite the user taking an action, like editing an issue, during check out.

## AC
- When a user edits one issue and then navigates back to the Select Dispositions screen, all previously set issue dispositions remain.

**Comment by dannysellers** [comment]
@laurjpeterson Is this different than #5396?

**Comment by laurjpeterson** [comment]
@dannysellers I think so. In this issue, when the user edited an issue and was taken back to the Select Dispositions page, all of the dispositions cleared out. In the other issue, the problem was dispositions being set once before, and were cleared when the user started the check out flow after the judge had assigned the case back to them.
