### ISSUE TITLE
Write tech spec for AMA Schema

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5406]
We need to begin designing the schema for AMA appeals and their associated tables. We've been having a discussion around how to separate the appeal table into AMA and legacy appeal tables: https://github.com/department-of-veterans-affairs/caseflow/issues/5295#issuecomment-386330977.

Now we need to define what this table will look like, and what other tables it is linked to.

**Comment by laurjpeterson** [comment]
A spec was written for AMA schema, so closing.
