### ISSUE TITLE
SPIKE: What is the level of effort to show users when there are new documents in the eFolder?

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5410]
Could we investigate the feasibility of surfacing new documents in the eFolder, say, upon each load of a user's queue?
- How much load does this put on VBMS?
- Does this affect Queue loading performance?
- What might be the optimal technical design of this feature?

This type of feature can help us solve for mail and for reducing on hold time.

### User stories
- As any Board employee, I want to see if there are any new documents in a Veteran's eFolder so I can assess if I still can work on the case.
   - e.g. As an attorney, if a FOIA request comes in the mail I want to be notified, so I can know that I cannot finish the decision, I need to transfer the case to FOIA.
   - e.g. As a co-located team member, after I've sent correspondence to a Veteran for a hearing clarification and placed the case on hold, I want to see if there are new documents added to the eFolder so I can check if that new document is the Veteran's answer, and I can complete the hold.

### Questions to be aware of
- Who is alerted by new documents in eFolder when a case is in "case storage" or not assigned to anyone?
- If we are showing any user when there are new documents in the eFolder, what happens to the mail team? Do all users know how to handle all mail?

**Comment by mkhandekar** [comment]
👀

**Comment by laurjpeterson** [comment]
@mdbenjam - I'd like to pressure test this in some way. 

1) Could we look at the cases that are in location 24 abeyance right now, and see how many of them have new documents in the eFolder day over day? This would test "on hold" cases and how often they might get mail or other documents that a co-located user might want to look at.

2) Could we look at cases that are in location 11 or 12 and assigned to a co-located team member day over day and see how many documents are added to their folders day over day?

**Comment by mdbenjam** [comment]
So would these cases be visible on these user's queue? It's easy if we do this when a user takes an action, like loading their queue, rather than doing it in the background.

**Comment by laurjpeterson** [comment]
Yes, in a future state, these cases would be in a users' queue - either in progress (reflected in option 2 above) or on hold (reflected in option 1/abeyance). I'm just wondering if we could look at these cases as they are in VACOLS today, see if and how many documents are added each day. To check if this feature is worthwhile before implementing it. 

Could we run this query once a day for a subset of users or cases just to check?

**Comment by mdbenjam** [comment]
Hmmm, I think the feature is easier to build than this job to check if the feature should be built. So I'm hesitant.

**Comment by laurjpeterson** [comment]
Ok, good to know. If most claims folders have many new documents a given time, our idea to notify users about them to potentially serve as mail notifications might be unwieldy to users. So the risk is we build something we may not end up using, but I agree that if the level of effort of building is much less than data profiling we should just go with that. @mkhandekar @sneha-pai and @Chingujo are including this in usability testing next week, so we'll know more then when we should move forward with building this.

**Comment by mdbenjam** [comment]
We could build it behind a feature flag and test it with one or two users.

**Comment by laurjpeterson** [comment]
sounds good, thanks! closing. will create another issue when we want to implement.
