### ISSUE TITLE
Discussion: Product focused slack channels

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5412]
resurfacing slack discussions from retro last week! will bring up during standup to define the right path forward for coming to a decision, but notes here:

i have a suggestion to split up and/or rename some of our channels into product-specific channels, while keeping some norms that seem to be working. (like for queue, the team has benefited from a design/feature definition channel (appeals-queue) and an engineering focused channel (appeals-foxtrot))

examples of this would be:
- appeals-whiskey --> appeals-efolder, appeals-reader
- appeals-foxtrot --> appeals-queue-eng, appeals-certification
- appeals-tango --> appeals-dispatch, appeals-hearing-prep

*some reasoning*:
- prevent product-specific alerts crowd each other out and risk less than timely responses (e.g. dispatch alerts crowding hearing prep alerts in the tango channel)
- consistency. appeals-intake and appeals-hearings are already AMA-focused products and product-focused channels
- aligns with our team's focus on prep for AMA. for example, we could move certification discussion out of foxtrot/queue into it's own channel (recognizing that cert slack posts are likely less than 1%)
- we have appeals-touchpoints for cross-product discussion
- we can always reverse this decision later!

*risks - and my suggested mitigation*:
- there is a risk that these channels could make us more siloed, and result in some members of the team not having as much context about products in maintenance mode (certification, dispatch, efolder).    i think that product owners and tech leads can bring in other team members as needed to fix bugs/solve issues regardless of where alerts and conversation is about each product. 
- more channels for certain people to pay attention to. however, i think that tech leads and product owners will be paying attention to these alerts regardless of what channel they are in. this move could reduce crowding for other team members, and help tech leads and product owners distinguish which alerts to attend to

initial slack thread: https://dsva.slack.com/archives/CA217E1FA/p1525268649000341

**Comment by laurjpeterson** [comment]
Initial slack comments:

Leah Bannon [2 days ago]
so would the team channels be reserved for team and stand up related content and then all product-related discussions would go in their specific channels? I think as long as we have clear lists of what goes in each channel, more slack channels is ultimately less work once you get used to it, because it's easier to fine tune the level of attention you pay to each channel


Lauren Peterson [1 day ago]
i was thinking that we wouldn't have a whiskey or foxtrot channel anymore. does sierra have a sierra channel and an intake channel?


Leah Bannon [1 day ago]
We have just intake, but that's also our only product. I was considering a similar change, but after poking around the rooms, it seemed like yall still need a space for everyone on a team like foxtrot to do stand up or warn you when they'll be out. Also, I wasn't sure where notifications would go for something that multiple products are using, since we're sharing a lot. If we can sort those out, I think the change will make slack more intuitive.


Lauren Peterson [1 day ago]
i was thinking we'd rename appeals-foxtrot to appeals-queue-eng and use it the same way. that is where we host standup today


Lauren Peterson [1 day ago]
what's an example for something that multiple products are using? @holtz created appeals-touchpoints a few weeks ago


Lara Kohl [18 minutes ago]
I think this would help follow the thread of conversations, and would also be better for product owners and designers who are part of a different team. The downside is that it would create more slack channels.

**Comment by leahbannon** [comment]
I love this idea. I think the only thing you're overlooking in your proposal are some of the non-product-team-related discussions, like:
- asynchronous stand up and other team-wide sprint ceremony content (ex: /reminders and waffle board screenshots)
- starting a slack call with the team
- people's status being out or other heads up you want to give to your broader team
- memes (team-wide lulz)

My hunch is that you might want to keep the #appeals-foxtrot channel, but only use it for that ^ stuff, and then all other product-related discussions go in those channels.

I also propose getting rid of #appeals-touchpoints in favor of greater visibility (cause that's the point) in the main #appeals channel.

**Comment by laurjpeterson** [comment]
@leahbannon so i understand correctly, are you thinking 3 channels per team?
1. appeals-foxtrot (or sierra, tango, etc.) = async standup, slack calls, status, memes, heads up
2. appeals-queue-eng = queue focused engineering discussions 
3. appeals-queue-design = queue focused design and feature definition discussions

or were you thinking:
1. appeals-foxtrot = team focused convos
2. appeals-queue = both engineering and design conversations
  - risk here is that queue channel will have all the action, and foxtrot won't have much

the third option is to just do everything in appeals-queue!

**Comment by mkhandekar** [comment]
Yes, 👍to both this:

> 1. appeals-foxtrot = team focused convos (standups, slack calls, team whereabouts)
> 2. appeals-queue = all product, engineering and design conversations

and this:

> I also propose getting rid of #appeals-touchpoints in favor of greater visibility (cause that's the point) in the main #appeals channel.

**Comment by sharonwarner** [comment]
Agreed. We use appeals-tango for our standup call in the morning. If we only had appeals-hearing-scheduling and appeals-hearing-prep, I'm not sure which one we would use for standup.

**Comment by laurjpeterson** [comment]
Discussion 5/11.

Actions:
- @laurjpeterson to create appeals-reader, appeals-certification, appeals-efolder channels, etc.
- whiskey, tango, foxtrot channels remain untouched. each team can decide how they want to use them, e.g. for standup calls, engineering conversations that the sprint team picked up that are not explicitly product focused, retro action items, process conversations, etc. but are not required to use them
- @leahbannon to review slack channel descriptions
- will follow-up with tech leads to change the alerts to be routed to the correct channels
