### ISSUE TITLE
Hearing Worksheet | Appellant DOB

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#5414]
If Appellant is a widow/spouse/dependent on Hearing Prep, and qualifies for AOD, seeing the DOB of appellant if different from Veteran is useful. If AOD, should be red.

**Comment by annienguyenUSDS** [comment]
@lakohl is this something we want to keep open/hold or close?

**Comment by lakohl** [comment]
@annienguyenUSDS Let's write this up for future investigation/milestones. Then we can close it.
