### ISSUE TITLE
"APPELLANT REPRESENTED IN THIS APPEAL BY" is completed incorrectly

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#543]
<img width="603" alt="screen shot 2016-01-21 at 11 01 34 am" src="https://cloud.githubusercontent.com/assets/772/12485910/5ccaf97c-c02e-11e5-9ea7-db6b2275de48.png">

**Comment by webinista** [comment]
What's the expected result here? Is it `NO REPRESENTATIVE` rather than `8A_NO_REPRESENTATIVE` or is there some phrasing that we need to work on?

**Comment by alex** [comment]
I think either blank or `NO REPRESENATATIVE`? /cc @gmorgana-va @KHarshawat

**Comment by webinista** [comment]
Ok, that question has a few options. Currently, the `value` attribute for each are as follows:

- `8A_POWER_OF_ATTORNEY`
- `8A_NO_REPRESENTATIVE`
- `8A_SERVICE_ORGANIZATION`
- `8A_AGENT`

I can replace with versions that don't have the `8A_` prefix and separated by spaces.

**Comment by alex** [comment]
That sounds like a good fix.

On Thu, Jan 21, 2016 at 3:11 PM, Tiffany Brown <notifications@github.com>
wrote:

> Ok, that question has a few options. Currently, the value attribute for
> each are as follows:
>
>    - 8A_POWER_OF_ATTORNEY
>    - 8A_NO_REPRESENTATIVE
>    - 8A_SERVICE_ORGANIZATION
>    - 8A_AGENT
>
> I can replace with versions that don't have the 8A_ prefix and separated
> by spaces.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/543#issuecomment-173694352>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
It looks like it's supposed to have more details though, e.g. for a VSO the full name of the VSO.

**Comment by webinista** [comment]
VSO = "Veteran's Service Organization"?

**Comment by alex** [comment]
Yeah.

On Thu, Jan 21, 2016 at 3:19 PM, Tiffany Brown <notifications@github.com>
wrote:

> VSO = "Veteran's Service Organization"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/543#issuecomment-173696419>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by webinista** [comment]
@KHarshawat @gmorgana-va Did I miss an associated input field for the `8A_SERVICE_ORGANIZATION` option?

**Comment by orischwartz** [comment]
I suspect other form fields have this same problem. 

The ideal way is to reuse the options data defined here:

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/views/web/questions.html.erb

And map it back to its label after the form is submitted.

**Comment by orischwartz** [comment]
@webinista I can take a stab at it if it's ok with you...eta soon

**Comment by webinista** [comment]
@orischwartz Go for it.

**Comment by orischwartz** [comment]
fixed by #545
