### ISSUE TITLE
Send associated rating issue with each contention created for Higher Level Reviews and Supplemental Claims

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5430]
In order for the VBMS NWQ to be able to route same station Higher Level Reviews correctly, they need to know the rating issue being reviewed for each contention. These will be passed

## Acceptance criteria
- Pass the correct rating issue id (`rba_issue_id`) along with each contention being created as part of a higher level review or supplemental claim. 

## Technical notes
- We need some way of verifying that VBMS received the data correctly.
- This issue is dependent on https://github.com/department-of-veterans-affairs/caseflow/issues/5428

**Comment by shanear** [comment]
We discovered a bug with this service where the wrong id is being used. VBMS is fixing the bug, but said it might take a while.

**Comment by shanear** [comment]
This should be fixed tomorrow. Going to retest.

**Comment by shanear** [comment]
Retested this today and there is now another bug. Should be retestable in 1-2 weeks 😢

**Comment by leikkisa** [comment]
The order of the process should be:
establishClaim
createContentions (against the returned claimId)
associateRatedIssues (with the contentionId and claimId's returned previously)

**Comment by leikkisa** [comment]
We cannot validate this ourselves, because success doesn't mean it shows up on the associated rated issues in VBMS (according to Joe).  It sounds like he would need to manually validate this somehow.

**Comment by leikkisa** [comment]
Have asked Joe to help validate this on test file number: 984562385

**Comment by leikkisa** [comment]
Joe says it worked!  He checked rated issue ID 113584 (test data)
