### ISSUE TITLE
Attorneys | Add admin action screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5439]
When an attorney is assigning an admin action to co-located support, they want to specify the admin action(s), provide instructions, and assign the case to the right co-located team, so the admin action can be completed.

## Acceptance criteria
- Verify that there is a page called "Assign an Administrative Action" when an attorney selected create admin action from the Queue or Case Details page
- User can select from a list of admin action types (default to no type)
   - List of admin action types from VACOLS list
~There is a dropdown where the attorney can select the appropriate team.~

 ~- Although the attorney can change the assign to via dropdown it should auto fill on the following:~ 

~Admin action | Default display on dropdown | 
-- | -- |~
~FOIA | FOIA
Hearing schedule | Hearings
Translation | Translation 
Transcription | Transcription
All other | Select - attorney will select if co-located 1 or 2~

- Verify that there is a free text comment box called Instructions
   - We can follow the same text character limit
- Ensure that all copy is in the COPY.json file
- Verify when the user submits this assignment, the case is auto-assigned to a co-located user per https://github.com/department-of-veterans-affairs/caseflow/issues/5982
   - Note: for the first release of this functionality, cases will only be assigned to two co-located users - Randy Seay and Eugene Scott

## User Stories
- When an attorney is assigning an admin action, they need to choose the type of admin action they are assigning, so co-located knows what their task is.

- When an attorney is assigning an admin action, they need to explain instructions for the task, so co-located knows how to execute on that task.

### "Admin Actions Details" flow
![attorneys_assign-one-admin-action](https://user-images.githubusercontent.com/31224257/43268725-5ad4a49c-90bf-11e8-85fc-7dc3c4a4250d.png)

### List of admin actions in VACOLS case distribution program
- IHP
- Waiver of AOJ letter
- Arneson letter
- Hearing clarification letter
- POA clarification letter
- Unaccredited representative letter
- Retired VLJ letter
- New rep arguments (PT_VSO) letter
- Extension request ruling
- Missing hearing transcript
- Schedule hearing
- FOIA/Privacy Act request
- Pending scanning banner VBMS
- Missing records in file
- ~Substitution determination needed~
- Address verification
- Other

**Comment by sneha-pai** [comment]
@laurjpeterson can you please review the A/C here that I've x-ed out to ensure that it is accurate till date.

**Comment by laurjpeterson** [comment]
Looks good!

**Comment by dannysellers** [comment]
@sneha-pai With such a long label for the admin action type dropdown, it butts up against the Required label, creating a line break:
![screen shot 2018-07-30 at 11 39 04 am](https://user-images.githubusercontent.com/8533004/43407641-4a9319d4-93ed-11e8-942b-2afdf7b5b3a3.png)

How about "Select an administrative action type"?
![screen shot 2018-07-30 at 11 40 34 am](https://user-images.githubusercontent.com/8533004/43407678-62454336-93ed-11e8-93b0-f6f47dce97ee.png)

Open to other suggestions of course. This text will be in `COPY.json`, so it can easily be changed later

**Comment by laurjpeterson** [comment]
@dannysellers - the Required text should no longer be there, for all drop downs. We removed it for the submit draft decision page (see: https://github.com/department-of-veterans-affairs/caseflow/issues/5423) but this should hold true for all. Instead, the error would show up if the user tried to advance without filling required text in. 

cc: @sneha-pai
