### ISSUE TITLE
Attorneys | Add admin action confirmation

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5440]
When an attorney adds an admin action, they want to see a confirmation screen and navigate back to their queue, so they can start working on the next task.

## Acceptance criteria
- When the user finishes adding an admin action, they navigate back to their default queue
- Confirmation message copy:
   - Title: Your IHP has been successfully submitted to [Name of team]
      Body: If you need to make any changes, please manage this case in DAS.
- Verify the case for which the attorney added the admin action is no longer in their queue

## Mocks
![confirmation page](https://user-images.githubusercontent.com/23316107/39942487-9f9347aa-552d-11e8-8e15-1ef534fa00f4.png)

**Comment by dannysellers** [comment]
Should this always say "Your IHP has been...", or should "IHP" be replaced by the specific action type? (i.e. the (right-side) values from [`CO_LOCATED_ADMIN_ACTIONS.json`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/CO_LOCATED_ADMIN_ACTIONS.json))

**Comment by dannysellers** [comment]
Where does the team name come from? / How is the team name correlated with the action type/value?
