### ISSUE TITLE
Non-rated issues | Finish: Incorporate non-rated issues into count

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5443]
Adds some lightweight visual feedback near the "Establish claim" button to tell users how many issues have been selected on the page. 

## Acceptance Criteria
On the "review" page for SCs and HLRs:
- Add any non-rated or uncategorized issues to the total issues count
- Remove the word "rated"

## Mock
![image](https://user-images.githubusercontent.com/4042181/41855266-2f9da340-7860-11e8-9711-0b9d11651e87.png)

**Comment by abbyraskinUSDS** [comment]
Don't break it out by rated/non-rated - just one total count of issues - scope this to issues count, not the button label

**Comment by suzchap** [comment]
LGTM
