### ISSUE TITLE
Mark a case as overtime at the point of assigning

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5445]
Chiefs and senior counsel request the ability to mark a case overtime at the point of assigning to an attorney, rather than having the attorney mark a case overtime. 

Only chiefs and senior counsel can approve overtime, not judges. So this functionality/design is required when we are able to provide Caseflow to senior counsel and chiefs. 

How might we incorporate the overtime checkbox at the point of assignment?

### AC
- When judges or SSCs assign cases to attorneys, they can mark the case as overtime **for both AMA and legacy cases**

### Notes
- For legacy cases, since we're updating VACOLS, we have the backend fields
- For AMA cases, we need to build them

### Early design provocations (2018):
For a lean/simple solution for marking cases overtime, Senior Counsel(permission-driven) would be the only users who are able to see a blue link in the Case Title area of Case Details
@allyceh @laurjpeterson please provide your comments/reactions on the proposed designs below.

##### _Senior counsel would click on a blue link in Case Title area of Case Details, reading "Mark this case as overtime":_
![overtime-marking-add](https://user-images.githubusercontent.com/31224257/55699452-f3b2e780-5998-11e9-817b-b04ff631208a.png)

##### _Senior counsel can see a confirmation that this case is now marked overtime. They can also see a new badge appear at the top right of case title.:_
![overtime-marking-confirmation](https://user-images.githubusercontent.com/31224257/55699625-9e2b0a80-5999-11e9-91b7-c5d4ed2129e3.png)
(The senior counsel will now see another link in Case Title - this time to remove overtime status (in case they made a mistake or have to change the status for other reasons)

##### _Senior counsel can remove overtime status by clicking on "Remove overtime status for this case"
![overtime-marking-remove](https://user-images.githubusercontent.com/31224257/55699859-c2d3b200-599a-11e9-89b6-a7a4cfb8430f.png)
- they'll be prompted with a pop-up modal message asking them "Are you sure you want to remove overtime status?" ----> if they click "yes" they will see a confirmation reading "Vera Marshall's case is no longer marked as overtime. The "OT" status badge has been removed.
-they will also see that the overtime badge has disappeared, and the blue link now reads "Mark this case as overtime"

**Comment by laurjpeterson** [comment]
Note: there are no longer chief judges. Will need to determine who assigns overtime cases with the new BVA organization structure - it might continue to be senior counsel.

**Comment by allyceh** [comment]
Thoughts about "Mark case as overtime" and "Remove overtime status" as the link text? I am going for the same meaning but a little more concise since we're putting these in the case header area and want to conserve space. 

Looks good!

**Comment by laurjpeterson** [comment]
Can you share why you chose this case title link approach vs. marking the case overtime at the point of assigning - i.e. as part of the the flow where judges/senior counsel actually assign cases to attorneys through the actions dropdown on Case Details?

Note: judges/senior counsel can also assign cases to attorneys in the Assign cases view, in bulk. I understand why we aren't tackling bulk OT assignment at the moment, though, because it likely adds complexity.

**Comment by allyceh** [comment]
Note: Sneha and I discussed putting a checkbox next to the "Assign to" button in the judge assign view.

**Comment by carodew** [comment]
@jimruggiero this is from 2018. I don't have context on this to know it's relative priority or if it's outdated. Suggest we move this to Icebox or New Issues until we have more clarification? 

It doesn't, on it's face, appear too difficult from the design perspective but I'm not sure what designer or team we'd ask to do it.

**Comment by carodew** [comment]
Noting that these designs use the update case details header, which does not match what is in production. We'll either need to complete the work in #8211 (https://github.com/department-of-veterans-affairs/caseflow/issues/8211) OR back-design the designs here to match the old header.

**Comment by araposo-tistatech** [comment]
Closing, updated requirements on #13418
