### ISSUE TITLE
Already decided issues should not be in the check out flow

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5466]
Issues that have already been decided are not required to be included in an attorney's decision. So, we should prevent already decided issues from requiring the attorney check out flow. For instance, if an issue was already granted at the RO, the attorney should still see that issue in case details, but not need to mark an issue disposition. 

We learned about this through Shamil Patel's feedback from attorney check out:
> I noticed difference between the Caseflow and DAS checkout options.  I just did a case in which one of the issues is listed in VACOLS as being “Adv-Allowed in field.” It was essentially granted before coming to the Board and so I don’t need to worry about it.  When checking the case out in DAS, that issue does not appear and I don’t need to assign a disposition.  However, it did appear during the Caseflow checkout process.  Caseflow did give me the option to delete the issue, but I didn’t know if that meant deleting it just from the Caseflow process or from VACOLS as well.

## AC
- Exclude issues with the following dispositions from appearing in the check out flow. Issues with these dispositions should remain unchanged.
    "A" => "Advance Allowed in Field",
    "B" => "Benefits Granted by AOJ",
    "D" => "Designation of Record",
    "E" => "Advance Withdrawn Death of Veteran",
    "F" => "Advance Withdrawn by Appellant/Rep",
    "G" => "Advance Failure to Respond",
    "L" => "Manlincon Remand",
    "M" => "Merged Appeal",
    "P" => "RAMP Opt-in",
    "Q" => "Recon Motion Withdrawn",
    "R" => "Reconsideration by Letter",
    "V" => "Motion to Vacate Withdrawn",
    "W" => "Withdrawn from Remand",
    "X" => "Remand Failure to Respond"

**Comment by dannysellers** [comment]
Also, should attorneys be prohibited from changing the disposition? Or should the dropdown be enabled and have a pre-set value?
