### ISSUE TITLE
Change specifically task-related routes back to /tasks... from /appeals...

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#5471]
In #5326 I got a little punchy and changed too many routes from `/tasks...` to `/appeals...`. The `POST` and `PATCH` [routes](https://github.com/department-of-veterans-affairs/caseflow/blob/c9ec40973bb745a93a933ff45e7f4d8dacd91253/config/routes.rb#L132) should be changed back to `/tasks...` since they deal explicitly with task resources and not appeals resources.

## Acceptance Criteria
* Front-end code references the `/tasks...` endpoints instead of the `/appeals...` aliases where appropriate (as described above)

**Comment by alisan16** [comment]
Closing as this is now obsolete.
