### ISSUE TITLE
Discussion: Should we store person information in Caseflow?

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5484]
# Problem statement
VACOLS currently stores a lot of information about people. Specifically contact info. This is done for the veteran's power of attorney (representative table) and for the appellant (correspondent table). We likely need access to the same information in our system. The board currently sends decisions to both POA and appellants, and the board needs to communicate with POAs throughout the decision process.

Do we want to store this information? Or can we leverage BGS to store it?

# We store the information
Advantages:

- Reduces our reliance on an external dependency BGS
- Allows us to develop more quickly
- Makes handling non-VBA business lines easier

Disadvantages:

- Two sources of truth. What happens when they're out of sync?
- How will we keep our information up to date?

Implementation:

- Could create a contact table which appellants and veterans would have a foreign key into.

# We let BGS store the information
Advantages:

- One source of truth
- Often information will already exist for the person

Disadvantages:

- The process to be allowed to write to BGS might be long
- Is BGS okay with us writing contact information for people who come up through non-VBA business lines (i.e. NCA)
- We are beholden to BGS. What if they go down? What if they decide to remove some of our data?

Implementation:

- Use BGS's person service which has both read and write endpoints to get and add people.

# We use BGS when the information exists, but never write to BGS
Advantages:

- Don't have to go through the process of writing to BGS
- Might make dealing with non-VBA business lines easier

Disadvantages:

- If someone we store is eventually added to BGS then there are two sources of truth. What happens when they're out of sync?
- How will we keep our information up to date?
- Super complicated model (sometimes go to BGS, sometimes go to our DB)

Implementation:

- Could create a contact table which appellants and veterans would have a foreign key into. But only store it when BGS doesn't return anything.

**Comment by aroltsch** [comment]
I am curious to hear how complicated the process to be allowed to write to BGS would be? Do they already have API endpoints that would allow us to do that or do they have to implement them?

**Comment by MeredithStewart** [comment]
I would advocate for whatever path gets us the most up-to-date information. 

In AMA, the Board will take over all correspondence (letters) to Veterans and POAs for scheduling hearings (right now ROs do it). It's essential that they have the most up-to-date contact info so they can receive the letter telling them when to show up for a hearing. Today, 30% of Veterans don't show up for the hearing and we don't want this getting worse.

**Comment by amprokop** [comment]
> VACOLS currently stores a lot of information about people. Specifically contact info. 

A few questions:
-Is it correct to say that contact info for POAs and appellants is the only duplicated info across VACOLS and BGS? 
-Can we clarify what information exactly we mean when we say "contact info"— names? addresses? phone numbers? emails? all of the above?
-Also, POAs aren't necessarily people, they can be firms or organizations right?

**Comment by amprokop** [comment]
> The process to be allowed to write to BGS might be long

**Comment by amprokop** [comment]
> We use BGS when the information exists, but never write to BGS

**Comment by MeredithStewart** [comment]
Does anyone know about the Vets 360 initiative and how that might related to this? My info is limited: This is something Vets.gov will be interfacing with in the near future. Vets 360 was supposed to launch soon. It's not one centralized database, but the goal of change a Veteran's address in one place and it changes it in all places.

**Comment by shanear** [comment]
So I've been chatting with AMO about what to do here for higher level reviews and supplemental claims:

- Most cases, the appellant/claimant will already exist as a related dependent to the veteran in the VBA corporate DB.
- There is a BGS endpoint for pulling relationships for the veteran. There is a chance that this endpoint is already available in prod since we use other end points on the `PersonWebService`.
- In the case where the appellant/claimant isn't in Corp DB. The CA will be asked to add it (in SHARE I  think). For BVA, we should consider if this is possible in VBMS, because they don't have access to SHARE.

So I am very in favor of this option, since it's what we'll be doing for HLR and SC.
## We use BGS when the information exists, but never write to BGS

**Comment by mdbenjam** [comment]
@amprokop 

> Is it correct to say that contact info for POAs and appellants is the only duplicated info across VACOLS and BGS? What about POA itself, are we leaving this to a separate discussion? Not sure if we want to frame this as just a discussion on appellant / veteran name & contact info

I think POA is a separate discussion, I think this should just be about contact information.

> Can we clarify what information exactly we mean when we say "contact info"— names? addresses? phone numbers? emails? all of the above?

VACOLS currently stores addresses and phone numbers. I don't think they have email addresses. I think we need addresses, unsure about phone numbers.

> Also, POAs aren't necessarily people, they can be firms or organizations right?

Regarding POA I feel very strongly that we shouldn't store their full contact information, instead we should just store POA codes and get the contact information from BGS. I believe this is possible.

> Hm, have we articulated the complexity here? What writes would we potentially make to BGS? Are there policy questions here — does VA ideally maintain only one address/etc for a Veteran? Are there legitimate use cases where BVA might want different data than other VA branches?

We could write new person records using the `insertPersonWithRelationship` endpoint in the person service. This would allow us to add a person record, and define the relationship with the veteran.

I think the VA should only have one address for a veteran, I think having multiple addresses adds a lot of unneeded complexity.

I do not think there is a use case where BVA wants something different. But I see many cases where they want the same address. If a veteran moves, and they notify VBA then the address could get updated in BGS but not our system (if we maintain a different address). Now we can no longer communicate the veteran.

> Are appellants who are not Veterans possible to add to BGS? There may be strict rules around what sort of data should be stored in BGS.

Yes BGS has a person endpoint for specifically this purpose.

> Should we add a discussion of options to cache certain pieces of information here? If so, what would we cache and how long?

We should certainly cache results from BGS. We likely want to cache everything, for a medium-length amount of time. i.e. 1 week. But I feel this is an implementation detail we don't have to decide right now.

> Does this mean we would store Veteran info but not non-Veteran appellant info?

Appellants should already usually be in the system, since BGS tracks claimants and in most cases they are the same.

> Can we articulate different example scenarios with specific pieces of information, from a BVA user/employee point of view?

The scenario that comes to my mind is BVA dispatch. The board has to mail decisions to appellants, therefore we need to have an address.

> Do we have a good idea of how and when contact information is updated in VACOLS today? How about when contact information is updated in BGS?

I do not have a good understanding of this.

--------

After Shane and I talked yesterday, I'm also in favor of `We use BGS when the information exists, but never write to BGS`. We can have our users write contact information in Share when it doesn't exist. In the future if we decide we have time to implement it, we could integrate with the insert/update person endpoints to allow users to change and insert appellants right in caseflow.

**Comment by nicholasholtz** [comment]
My initial thinking is also strongly in favor of option 3, `We use BGS when the information exists, but never write to BGS`. There never will be a single source of truth for all Veterans, no matter how much that would be an idealized state; BGS may have most (or even all) VBA appellants but we know there are situations where they will not have some VHA and NCA appellants. Even though the numbers for VHA and NCA are relatively small, they are not small enough to be considered edge cases.

At the same time, consistency with BGS is a huge win. Relying on a BGS-first model would allow this. 

I am not sure I agree with this statement:
> Super complicated model (sometimes go to BGS, sometimes go to our DB)

It seems like it would be more consistent than that, and likely look like:
1. Call BGS
2. If there is a BGS record, check if we have stored a separate Caseflow record for a prior instance when there was no BGS record, and if so, update Caseflow to reflect BGS data and archive the Caseflow record.
3. If there is no BGS record, use Caseflow data.

**Comment by laurjpeterson** [comment]
Actions:
	- try pulling Veteran name from BGS (with VACOLS as backup) for some users to test it out adn implement datadog monitor @mdbenjam 
	- async think about cacheing strategy @mdbenjam to start an issues about this
	- investigate if Board employees can update in SHARE (short term) @nicholasholtz 
	- investigate if Board employees can update in VBMS (short term) @nicholasholtz 
		- from Jebby: Board does not update addresses in BGS or VBMS - think they don't have the ability to. Might be able to get permissions to do so in VBMS. Only update POA in both systems.
	- investigate writes to BGS (long term) - @nicholasholtz to determine who we can talk to about this
		- John dell?
		- can we write to BGS with person info
