### ISSUE TITLE
AMA intake - non-rated | Finish: include previous non-rated issues in list

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5498]
Show non-rated issues that have previously entered the system, along with their decision date.

## Acceptance Criteria
- For non-rated decisions that have passed through the system, the list of previous decisions issues should include non-rated issues with their associated decision date

**Comment by leikkisa** [comment]
Should include non-rated issues from any AMA intake in progress, so that people can see if they are a duplicate and are able to remove ones that are
Include screenshots

**Comment by suzchap** [comment]
Now redundant per convo with Abby so closing.
