### ISSUE TITLE
AMA intake - non-rated | Finish: Validate timeliness

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5499]
Validate timeliness from manual date entry

## Notes
The timeliness rules are as follows:

__A)__ If the rating issue is part of a RAMP decision,
then it is untimely if it's more than 1 year ago.
(also do not show the VACOLS matching step)

__B)__ If a VACOLS issue is matched to the issue,
then it can not be untimely,
however, it is invalid for opt-in if the soc date is more than 60 days ago and the nod date is more than 1 year ago.

__C)__ If it is neither A or B,
then it is untimely if it's more than 1 year ago,
it is also invalid if the decision was made prior to Feb 13, 2019 (the AMA start date)

**Comment by shanear** [comment]
dup of https://github.com/department-of-veterans-affairs/caseflow/issues/7300
