### ISSUE TITLE
Fix mobile header

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#55]
#52 adds a header, but it's not super mobile friendly. We should resolve that.

**Comment by alex** [comment]
<img width="1538" alt="screen shot 2015-10-26 at 10 55 25 am" src="https://cloud.githubusercontent.com/assets/772/10732360/12b250e4-7bd0-11e5-9db3-1c4ef8f9aff8.png">

**Comment by plusjeff** [comment]
Let's fix this when we do #106

**Comment by KHarshawat** [comment]
Closing the issue because as Jeff mentioned it'll be fixed w/ #106
