### ISSUE TITLE
Test caseflow in IE9 / Enable Saucelabs

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#550]
Need to ensure baseline functionality for outliers.

**Comment by webinista** [comment]
@KHarshawat @maryannbrody A few users opened IE9 during the last batch of testing. What was the resolution for that? Should I bother test in IE9 and 10 or are those users going to get upgrades?

**Comment by maryannbrody** [comment]
All users accessed caseflow via IE9 (6 total across 4 ROs). I think we need to test in IE9 for sure.
