### ISSUE TITLE
Judges | Review Remand Reasons

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5506]
When a judge is sending a case to dispatch, they want to review the Remand Reasons that their attorney selected, so the Veteran's data is accurate.

## AC
- Verify that if the case has a remanded issue, the user navigates to remand reasons for that issue. 
- Verify that the remand reasons the attorney had selected are pre-filled for the judge.

_Note: this page should be have the same as attorney check out - viewing one issue at a time, and clicking the button to scroll and advance._

## Mocks
![select remands reasons checkbox](https://user-images.githubusercontent.com/23316107/40014816-8bd6b478-577f-11e8-958c-05ff39a2e05f.png)

**Comment by dannysellers** [comment]
This was handled by #5707. Closing
![remand_reasons_persist](https://user-images.githubusercontent.com/8533004/40995561-58679666-68cd-11e8-9fbb-c8db12be0300.gif)
