### ISSUE TITLE
Add state-machine to Tasks

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#551]
Currently the Tasks model handles its transitions manually, checking via the date columns that the task is in the appropriate state to accept the transition from Unassigned => Assigned => Started => Completed

This will become unwieldy if we add more states, and before then we should consider implementing a state machine. So we'd newly add a `state` column, and that column would dictate it's current state and manage transition rules between states

**Comment by kierachell** [comment]
Confirmed that column exists.
