### ISSUE TITLE
Update Sentry Error Filtering

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5521]
Now that we have new Slack rooms for each product, let's split up the slack sentry error reporting on a per product basis.

# AC
1. Each product should only receive relevant sentry alerts.

**Comment by nemodjuric** [comment]
Here's the previous mapping:
  reader: whiskey,
  efolder: whiskey,
  document: whiskey,
  dispatch: tango,
  hearings: tango,
  appeals: foxtrot,
  certifications: foxtrot,
  intake: intake
Thanks to @laurjpeterson I got all rooms for each product, except document and appeals. @mdbenjam is document going to appeals-efolder and appeals to appeals-certification?

**Comment by mdbenjam** [comment]
Hmmm if it's document within the caseflow monolith then probably... Reader honestly. Since it's most reliant on the document class. Curious what the document mapping actually looks like. Happy to sync in person to verify this.

**Comment by alisan16** [comment]
Closing as this is now obsolete.
