### ISSUE TITLE
Understand how NWQ routes EPs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#553]
There's kind of a complex set of rules around how the NWQ is routing an EP after we create it. We should make sure that:

1) All EPs created by AMC should be assigned a stationOfJurisdiction of "499" for NWQ.
2) When an EP should be created on behalf of an RO, is it correct to assign a stationOfJurisdiction of the value corresponding with that RO, even though NWQ may reassign it due to business rules.

We should get in touch with contacts at VBA on answering these questions. Also feel free to update/add to this list.

**Comment by shanear** [comment]
@lakohl @abbyraskin @KHarshawat @ariperez any idea on the right people to ask here?

**Comment by abbyraskin** [comment]
happy to help tackle this with you @joofsh. i don't have any NWQ contacts. @ariperez do you have any ideas? I think @shanear mentioned Laura Finley and Brad Houston at VBA...

**Comment by joofsh** [comment]
@abbyraskin Yes it would be great to have help with this. If we don't know anyone directly, then based on our call with the VBMS tech team, they recommended reaching out to Laura Finley or Brad Houston initially, as they would be able to connect us with the right people internally at VBMS.

Do we have either of their email addresses?

**Comment by ariperez** [comment]
@joofsh @abbyraskin , I"m actively working on getting the best contact. Give me till early afternoon.

**Comment by abbyraskin** [comment]
thanks @ariperez! @joofsh let's work together to organize/nail down all our NWQ related questions. i can take an initial stab later this afternoon.

**Comment by abbyraskin** [comment]
- After a claim has been established at AMC, how does NWQ pick it up? What are they looking for/filtering by to identify it (EP code?)
- If we set the jurisdiction to a specific RO station during claim establishment, will NWQ still pick it up/reassign? Possible to bypass/ignore Caseflow?
- How do ROs know if a claim has been assigned to them?
- How does NWQ know how to route a claim, what are their rules for routing

**Comment by lakohl** [comment]
adding to your questions...
What about special issues that are not handled by ROs? (pensions?) Who handles these? How are they routed to them?

**Comment by abbyraskin** [comment]
Call has been scheduled for 3pm today with the NWQ Deputy Director, Astrid Perez.

Agenda is to understand a) the current state and how NWQ routes EPs today and b) implications for future state - would they prefer we send all previously-rerouted EPs to NWQ or assign to specific RO location at point of CEST?

**Comment by joofsh** [comment]
@shanear Based on our conversation with Astrid the recent responses from the VBMS tech team, I believe we have all the information we need towards understanding the NWQ and creating EPs. 

Going to close this ticket.

**Comment by shanear** [comment]
@joofsh I want to do a little more testing with this in UAT. I can pick this one up from here.
