### ISSUE TITLE
Docket Number

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5533]
# How to store docket number
We discussed how to store docket number on the AMA tech spec. It seems from a UI perspective we want to have a datestamp and an incrementing counter. i.e. 20180402-12345. Here we lay out two options for storing docket number.

## Calculate at runtime
Instead of storing this string in our database, we propose calculating this string each time it's needed by using the established_at timestamp and the row id.

- Since we use the row id, it's guaranteed that each docket number is unique.
   - The numbers within a docket or even on a given day may not be sequential. This will definitely be the case if there is ever a need to move an appeal within a queue by changing the established_at timestamp. 
   - If the established_at timestamp is being changed to move the appeal, it seems as long as the date is right, the subsequent id does not need to be sequential.
- Moving between dockets is easy, as the dates + row id are naturally ordered correctly.
- The docket numbers will get somewhat large, as we expect there to be millions of appeals which means docket numbers will have ids of 7 digits.
- Don't need to store it in the DB.

## Store in DB
We could calculate the docket number (date stamp + sequential id representing the number of appeals on this day) and store it in the DB.

- The ids stay small.
- The ids will usually be sequential.
- Storing the docket number duplicates the source of truth. How do we keep established_at and the docket number in sync?
- If someone needs to change the docket_number do keeping the ids sequential might be complicated.

**Comment by aroltsch** [comment]
I have a few questions to get a little more context:
1. Where does `established_at` come from?        
2. Why does storing the docket number in our DB duplicates the source of truth?
3. Could you describe how docket numbers are used and why they might change?

**Comment by amprokop** [comment]
> We discussed how to store docket number on the AMA tech spec. It seems from a UI perspective we want to have a datestamp and an incrementing counter. i.e. 20180402-12345. Here we lay out two options for storing docket number.

Partially checking my own understanding here — are we completely settled on how the incrementing counter is calculated? Should we be explicit about what the two options mean? This difference might have some significance for BVA users. 

### Option 1: Date + unique id across the entire appeals table

Two appeals total, one is established on 2000-01-01 and another on 2000-01-02.
Their docket numbers are 20000101-1 and 20000102-2.

In ten years, if there are 999,999 appeals, a docket number might be 20280101-999999.

### Option 2: Date + id that is unique for that particular date

Two appeals total, one is established on 2000-01-01 and another on 2000-01-02.
Their docket numbers are 20000101-1 and 20000102-1.

In ten years, if there are 999,999 appeals, a docket number would be 20280101-1.

Option 2 seems to have a readability advantage, but I'm not sure what needs our users really have here. Maybe @sneha-pai @laurjpeterson can chime in.

**Comment by amprokop** [comment]
It might help to lay out some requirements at the beginning, so we can debate those first and clearly compare across dimensions. Here's a stab at a few:

### Requirements
- BVA users should be able to use docket number as a unique identifier
- Docket number format must be able to support appeals changing dockets
- Docket number format must be able to support backfilling appeal established_at date (if, say, some appeals are processed/created after a delay)

**Comment by mdbenjam** [comment]
@amprokop thanks for clarifying. Yes I'm suggesting option 1. Though we can ask designers if they think option 2 is better.

I like those requirements, don't think I have anything to add there.

@aroltsch

1. established_at is set when the record is created, but I've been told that it might need to be manually changed if there was a clerical error and it is determined that the established_at date should be moved.
2. If we store docket_number, and that number is calculable from other fields, then if any of those fields change, we also need to change docket_number.
3. Docket numbers are used to determine in which order cases move through the system. I'm not clear on why it might change, I think it's if there is some error in processing a case and it's determined the veteran should have been entered sooner than they were. Their docket number might move up.

**Comment by laurjpeterson** [comment]
Notes from discussion 05/21/2018:

Exploring Option 1: date + unique id across the entire appeals table
- in the Queue table, we show the date that the appeal was established. e.g. column name = `Date established` and we show 180203
- in Case details, we show the entire docket number 180203-12345

Other notes:

- docket number needs to be editable
- docket number today assigned at Activation - if adjusted, Jed will append with an A. Docket number should reflect Form 9 date
- does not matter within a day
- in the new system, do we really need to expose docket number? yes
	- the docket number is listed on the decision
	- shared as a non-PII unique identifier
- docket number needs to be stable
- we record the timestamp for when the appeal was established - if we need to make a change, we'd need to change established_at
