### ISSUE TITLE
Splitting appeals or one appeal with many, many to many relationships

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5536]
# Overview
In VACOLS appeals can currently be merged and split for various reasons, many of which will still be true in AMA land. We want to build our model to elegantly handle these situations. Specifically:

1) Contested claims - One appeal can have multiple appellants. (Today handled by splitting appeals)
1) Multiple POA - One appeal can have multiple POA for different issues (Today handled by splitting appeals)
1) One docket, multiple appeals - A veteran can have multiple appeals in a docket at once. (Today handled by merging appeals)

There are certainly more scenarios, that are not listed here. We propose two solutions for these problems.

## Splitting appeals
We could continue to split appeals, but provide an appeal_group table that would have a one to many relationship with appeals. In this way we could have a simple schema for an appeal (an appeal have one POA, one appellant, etc.) while still having a way to group all relevant appeals and surface them at once. The appeal_group can have the docket number instead of the appeal table.

Consider how this would work for our three scenarios:

1) Contested claims - When there are two appellants for an appeal, we could duplicate the appeal, and set one appellant for each appeal. The appeals could be grouped together so that users can see all the related appeals, and where possible do work for multiple appeals at once (i.e. reviewing the eFolder).
1) Multiple POA - When there are two POA for different issues in an appeal, we could split the appeal based on which issues belong with each POA. Each appeal could have only one POA.
1) Multiple appeals in a single docket - Just need to add an appeal group that contains these appeals. The grouped appeal could get the docket number of the lowest docket numbered appeal.

An upside to this approach is it allows us to create a much simpler model between appeal and other tables. Fewer many to many tables.

Some downsides are that every appeal needs to have an appeal group even if there is only appeal. This approach might move complexity to the frontend.

## Many, many-to-many relationships
In this approach an appeal can have a lot of many to many relationships. An appeal can have multiple decisions, multiple appellants, and each issue on appeal can have many POA.

Consider how this would work for our three scenarios:

1) Contested claims - When there are two appellants for an appeal, then we can have a join table that allows a many to many relationship between those two appellants and their appeals.
1) Multiple POA - When there are two POA for different issues in an appeal, we could associated POA directly with the issues.
1) Multiple appeals in a single docket - The issues from the second appeal can be added to the first appeal and the second appeal can be closed.

An upside to this approach is that it makes appeals first class citizens.

Some downsides are it makes our data model very complex as appeals can have multiple decisions, multiple appellants, and multiple POA (through issues).

**Comment by aroltsch** [comment]
Would it be possible to digram both approaches? I think it will make it easier to make a discussion.

**Comment by mdbenjam** [comment]
Here are some scenarios: https://docs.google.com/presentation/d/1Uyt3ipuHNPkJON5ST2RInMsZCioyTZumo3i9O3SjeAY/edit?usp=sharing

**Comment by mdbenjam** [comment]
![appeal schema diagram](https://user-images.githubusercontent.com/3885236/40188887-f56d0ffe-59c8-11e8-895f-da4bad4606d0.png)
![appeal schema diagram 1](https://user-images.githubusercontent.com/3885236/40188882-f37d2580-59c8-11e8-84fe-2dc852194b0b.png)
![appeal schema diagram 2](https://user-images.githubusercontent.com/3885236/40188881-f36cee7c-59c8-11e8-8683-4e08f9d3e06d.png)
![appeal schema diagram 3](https://user-images.githubusercontent.com/3885236/40188880-f35ecd74-59c8-11e8-9925-ff1fb198eba5.png)
![appeal schema diagram 4](https://user-images.githubusercontent.com/3885236/40188879-f351d0f6-59c8-11e8-8588-20af4f1a0a6e.png)

**Comment by mdbenjam** [comment]
From our discussion we came up with the following approach:

- Each appeal can have multiple decisions, appellants, and issues. Each appellant can have multiple POA.
- Contested claims are handled by having multiple appellants on a single appeal.
- Multiple POA is handled by displaying all POA info for a given appellant and letting the user decide what the proper procedure is.
