### ISSUE TITLE
RAMP opt-in election | Copy change: update document type and order actions in ineligible alert

### ISSUE THREAD

**Issue by leahbannon** [department-of-veterans-affairs/caseflow#5538]
Since the user must perform all of these actions, I think we should switch lists like this to ordered lists from bullets

<img width="1006" alt="screen shot 2018-05-14 at 4 05 12 pm" src="https://user-images.githubusercontent.com/4323988/40020700-bf20105c-5790-11e8-8136-f44802d16f49.png">

## Acceptance Criteria
- Use **RAMP Opt-In Election** instead of **Correspondence** in ineligible RAMP instructions
- Order these instead of using bullets (Step 1, Step 2, Step 3), as we do elsewhere in the app

**Comment by abbyraskinUSDS** [comment]
We need to change the document type - we could do both in this story. I will update.

**Comment by abbyraskinUSDS** [comment]
@leikkisa both are in the AC...i can add a mock if it's helpful though

**Comment by leikkisa** [comment]
<img width="982" alt="screen shot 2018-05-29 at 2 47 50 pm" src="https://user-images.githubusercontent.com/6589610/40687797-a8a21d0e-6350-11e8-931c-4a618629c120.png">

**Comment by leikkisa** [comment]
@leahbannon @abbyraskinUSDS I am having trouble going through the Ramp Refiling flow on FACOLS, but I found this section of the code and am wondering if we also need to change the document type or formatting here.
<img width="821" alt="screen shot 2018-05-29 at 2 57 20 pm" src="https://user-images.githubusercontent.com/6589610/40687836-c84a82a4-6350-11e8-9622-b3f1858a684e.png">

**Comment by abbyraskinUSDS** [comment]
@leikkisa good catch, yes!

**Comment by leahbannon** [comment]
looks great!
