### ISSUE TITLE
Fix error message typo

### ISSUE THREAD

**Issue by leahbannon** [department-of-veterans-affairs/caseflow#5539]
I'm noticing a lot of content where we have punctuation outside of the quotation marks. Our style is to include punctuation inside, for example:
* RIGHT: Do a thing in "RAMP Election."
* WRONG: Do a thing in "RAMP Election".

![screen shot 2018-06-21 at 3 53 19 pm](https://user-images.githubusercontent.com/1596259/41742196-550d3b06-756b-11e8-87b3-fd7cdc6775c1.png)

## Validation instructions
Try to do a RAMP Refiling (RAMP Selection) for a Veteran that does not yet have a RAMP Election.  Confirm that the period is inside of the quotation marks.

Test file number: 123458310

**Comment by abbyraskinUSDS** [comment]
We put the period inside the quotation marks when a CA had to write something word for word (e.g., in the subject line in VBMS). I prefer it in the quotation marks, too, but we decided to make an exception for cases where we're telling users to write a specific phrase in VBMS so the CAs don't include a period.

**Comment by abbyraskinUSDS** [comment]
"RAMP Ineligible Letter".

**Comment by leahbannon** [comment]
also "RAMP Selection Letter".

**Comment by leahbannon** [comment]
I think this was fixed by using bold instead of quotation marks - can someone verify and close?

**Comment by abbyraskinUSDS** [comment]
It wasn't fixed everywhere - it's still here:

![image](https://user-images.githubusercontent.com/4042181/42459936-c0c537e2-836a-11e8-9fca-e4897d172ab3.png)

**Comment by suzchap** [comment]
LGTM
