### ISSUE TITLE
Remove userCanAccessQueue condition in QueueLoadingScreen

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#5551]
#5470 adds a check in `QueueLoadingScreen`'s `render()` function that returns early if the user does not have queue access so we do not make a request to the API. This is somewhat of a hack and we should probably be handling this in a different way.

There are undoubtedly others but two ways this could be accomplished are:
1. Determine if the user has queue access on the backend and return empty arrays in that case
1. Unwrap `QueueLoadingScreen` from `QueueDetailView`

## Acceptance Criteria
* `QueueLoadingScreen`'s `render()` function no longer contains the `userCanAccessQueue` condition
* The behaviour of the application (from a user's point of view) is unchanged

**Comment by hschallhorn** [comment]
No longer exists in the codebase!
