### ISSUE TITLE
Vacols Integration | Pull hearings in by date range

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5560]
We currently pull hearings in by judge and by appeal. We need to be able to pull hearings in by date range so we can display the schedule in the UI.

AC:
- From the Rails console, we can run Hearing.repository.hearings_by_date_range(date, date) and it returns all VACOLS hearings in that date range.

**Comment by oscarAtNava** [comment]
We should close this issue in favor of 5451

**Comment by oscarAtNava** [comment]
Closing in favor of issue 5451.
