### ISSUE TITLE
Identify and mark cases as specialty case teams

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5565]
When judges are reviewing their cases to assign, they need to see if any of their cases have specialty case team issues, so they know the case must be assigned to a particular attorney.

What are specialty case teams?
- Attorneys are members of specialty case teams, which were established to increase efficiency in decision-writing for appeals with rare issues. 
- Cases with rare issues are organized into specialty case team groups, and only attorneys in that specialty case team will draft the decision for the cases. 
- These attorneys applied to be part of a specialty case team. They must hit the same production quota as other attorneys.  

## AC
- For legacy appeals only
- If an appeal has a SCT issue, display SCT label in the queue table and search results per @sneha-pai's designs 
    - The SCT group designation is stored in the `BRIEFF.BFBOX`
- Display hover over with SCT group number from VACOLS - use copy "Specialty Case Team [insert number]" (I'm open to suggestions for this copy)

### Displaying specialty case label in Individual Queue table (always to the left of case details column)
Note: When browser width is narrow, we can stack labels vertically to save horizontal space. If browser width permits, place multiple labels side by side (limit 2 horizontally before wrapping)
![judge-table-your-cases](https://user-images.githubusercontent.com/31224257/49960999-85c14c80-fedf-11e8-8fcd-6d4295b4868b.png)

### Displaying specialty case label in Search results (always to the left of Docket column)
Note: When browser width is narrow, we can stack labels vertically to save horizontal space. If browser width permits, place multiple labels side by side (limit 2 horizontally before wrapping)
![search-results-sc-hlr-1 copy](https://user-images.githubusercontent.com/31224257/49961793-822ec500-fee1-11e8-89e0-a68c19076271.png)

## Technical notes
- This PR excludes SCTs from automatic case distribution - https://github.com/department-of-veterans-affairs/caseflow/pull/8167

## VACOLS logic 
From https://github.com/department-of-veterans-affairs/dsva-vacols/issues/8#issuecomment-413600936

![image](https://user-images.githubusercontent.com/27704093/49115420-c1fe7700-f268-11e8-8a59-566795c98fff.png)

## Additional Resources/Context
- About Specialty Case Teams - https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Post-Discovery/Case%20Assignment%20Ideas/David%20Ames_SCT.md
- Original request to Jed to implement specialty case teams - https://github.com/department-of-veterans-affairs/bva-technology/issues/389
- From Jed, about current state - https://github.com/department-of-veterans-affairs/dsva-vacols/issues/8
- Proposed SCTs - [pdf](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Post-Discovery/Case%20Assignment%20Ideas/Proposed%20SCTs.pdf)
- From Judge Nate Kroes, about assigning Specialty Case Team cases to attorneys:
> Regarding SCT, let me start by saying a lot of judges don’t have any attorneys on the team.  One Judge (Steve Reiss) has five; I happen to have two.  As far as process, once a week Senior Counsel Kristy Zadora sends cases for assignment (usually 3 per attorney) to judges who have attorneys on the SCT.  The idea is that the judge works as the central point of case assignment, but in reality the cases sent from Kristy are meant for certain attorneys.  The judges know the cases are SCT cases as there is a pink indicator in DAS.  The indicator has a number which corresponds to the SCT specialty.  I have one attorney who specializes in Dental issues and one who specializes in Reductions.  By looking at the SCT number I know who to assign the case to.  I suppose if a judge had two attorneys with the same SCT specialty the judge would decide which of the SCT cases in that specialty went to which attorney.

**Comment by mkhandekar** [comment]
👀

**Comment by mkhandekar** [comment]
@laurjpeterson sorry to ask you to do this but could we find out what this looks like in DAS? I see that the indicator is pink, but also am reading that there are numbers attached to different types of SCT cases. I'd like to know what that number in conjunction with the color looks like. Also, what is the range of numbers?

If there is a person I can reach out to myself for this info, let me know!

**Comment by laurjpeterson** [comment]
@mkhandekar here you go!

![image](https://user-images.githubusercontent.com/27704093/41356437-e9b2d4ee-6ef1-11e8-9dbf-598bb167d67f.png)

Additional resources:
- [SCTs as defined by David Ames](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Post-Discovery/Case%20Assignment%20Ideas/SCT_Summary.csv)
- [Original SCT request to define SCT issues](https://github.com/department-of-veterans-affairs/bva-technology/issues/336)
- [SCT request for the flag in VACOLS](https://github.com/department-of-veterans-affairs/bva-technology/issues/389)
- [Folder with notes from David Ames about SCTs](https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/Caseflow%20Queue/Post-Discovery/Case%20Assignment%20Ideas)

If we have any more questions about SCTs, we can continue this thread with Jed - https://github.com/department-of-veterans-affairs/dsva-vacols/issues/8

**Comment by mkhandekar** [comment]
**Do we care if its a SC case after it's been assigned to a SCT attorney?**

1. Senior counsel (10 ppl) are responsible for assigning to SCT attorneys
2. Judges care to see if cases are SCT because they have SCT attorneys on their teams
3. Judges who have to signs decisions care
4. Board employees want to track for productivity

**Comment by mkhandekar** [comment]
For legacy cases:
- we can point to Jed's designation and design our own indicator for table/case details

For AMA cases:
- no mapping exists

**Comment by laurjpeterson** [comment]
Asked Jed a few more questions today in the [dsva-vacols github issue](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/8), also linked in the Resources section of the main comment above. 

![image](https://user-images.githubusercontent.com/27704093/44221902-f3878280-a150-11e8-824b-64fbbcce1350.png)

**Comment by sneha-pai** [comment]
#### Caseflow needs to Identify the unique attributes for the respective cases, for legacy and AMA cases.

Attributes such as:
- Specialty Cases (determine workload, and who should do it)
- Overtime cases
- Hearings cases
- One-time hearing(?) not in scope right now

Specialty cases: How does this work?
    - Senior counsel are responsible for assigning specialty cases to certain attorneys (preselected)
    - Judges care to see that they are specialty cases (to understand workload)
    - Judges who have to sign specialty cases care when signing that they are specialty cases.
    - Attorneys work a mix of specialty cases AND non-specialty cases.
    - Board employees want to track 
    - Allyce: Would colocated want to know if specialty?
    - Often cases with these specialty issues have paper documents. 

**Specialty cases back-end approach:**
For legacy cases, point to Jed’s tagging work
For AMA issues, a mapping doesn’t exist yet. 

#### Caseflow also needs to display attributes for the case (in case details AND table-level)

Mixed docket = display of which lane this case is in 
	4 lanes: 
H - hearing
E - evidence
DR - direct review
L - legacy

H = If a hearing has been done for this case, if I HAVE done this case
	Impact: bigger reach (all judges)	     
SCT = one or more specialty issues
	Impact: small group of attorneys would be affected by this.
	we don’t yet know how we’re displaying issues yet
	engage with CHRISTI and the folks who’ve designed SCT

OT = overtime cases 
OtH = One-touch hearings: Hearing prep feature
	- One-touch hearing box (out of docket order)
	- this program may not last that long

**Comment by sneha-pai** [comment]
Additional notes from our post-standup discussion (08/16/18):

**Caseflow needs to _identify_ the unique attributes for the respective cases, for legacy and AMA cases.**

Attributes such as:
- Specialty Cases (determine workload, and who should do it)
- Overtime cases
- Hearings cases

**Specialty cases: At a table level:**
- Specialty case-team issues (Jed has programmed what cases count as specialty cases)
- Put into a bucket, in VACOLS, there’s a pink designation if the case is part of a specialty case team.


**Specialty cases: How does this work?**
    - Senior counsel are responsible for assigning specialty cases to certain attorneys (preselected)
    - Judges care to see that they are specialty cases (to understand workload)
    - Judges who have to sign specialty cases care when signing that they are specialty cases.
    - Attorneys work a mix of specialty cases AND non-specialty cases.
    - Board employees want to track 
    - Allyce: Would colocated want to know if specialty?
    - Often cases with these specialty issues have paper documents. 

**Specialty cases back-end approach:**
For legacy cases, point to Jed’s tagging work
For AMA issues, a mapping doesn’t exist yet. 

**Caseflow ALSO needs to _display_ attributes for the case (in case details AND table-level)**
Mixed docket = display of which lane this case is in 

4 lanes: 
H - hearing
E - evidence
DR - direct review
L - legacy

H = If a hearing has been done for this case, if I HAVE done this case
	Impact: bigger reach (all judges)	     
SCT = one or more specialty issues
	Impact: small group of attorneys would be affected by this.
	we don’t yet know how we’re displaying issues yet
	engage with CHRISTI and the folks who’ve designed SCT

OT = overtime cases 
OtH = One-touch hearings: Hearing prep feature
	- One-touch hearing box (out of docket order)
	- this program may not last that long

**Comment by laurjpeterson** [comment]
Good morning,

 

I am the coordinator for the Specialty Case Teams, a pilot the Board is running in which attorneys predominately draft decisions in one or two assigned topic areas.  I have met a few weeks ago with Lauren Peterson about the pilot and the needs we will have under AMA.

 

There have been some changes to the SCT program that you will need to be aware of.

 

Cases involving 1151 and SC/IR dental are no longer in the SCT pilot program.  This removal was thought to be a temporary pause but likely will be permanent, pending a decision by senior leadership.  Jed Wagner has updated the VACOLS programming for legacy cases.
There is a pending proposal with the Chairman to include SC PTSD due to MST as an specialty within SCT.  These cases are designated as sexual assault/harassment in VACOLS and can be coded as SCT by using this designation.  If this proposal is approved by the Chairman, attorneys will start drafting SCT cases in the SC PTSD due to MST area beginning in approximately mid-November.
 

Here is a list of the items needed to ensure that SCT pilot continues to be functional within AMA.

 

Report showing SCT attorney production (for both SCT designated cases and non-SCT designated cases) for AMA cases.  It is my understanding that the creation of reports are under development.  I will require a specific report showing the number of signed AMA cases drafted by SCT attorneys, including SCT and non-SCT cases.  This production information is critical to determine the success of SCT and production information is reported to external stakeholders.  For instance, I have answered congressional inquiries about the SCT pilot and the associated production just two weeks ago.
A way to continue to designate and charge SCT cases to SCT VLJs/attorneys.  For legacy appeals, this is currently completed through the case distribution program.  Something similar is necessary for AMA appeals.
Ideally there will be a SCT indicator somewhere in Caseflow queue to allow VLJs/attorneys to know that they have SCT appeal.  I understand from Lauren that this may be a challenge due to space limitations in the columns.
 

Please let me know if you require any additional information.

 

Kristy L. Zadora

Senior Counsel

Board of Veterans’ Appeals

**Comment by laurjpeterson** [comment]
@sneha-pai - can you paste in your queue table designs with SCT label to the original issue?

**Comment by sneha-pai** [comment]
### Mocks 

##### Displaying specialty case label in table (always to the left of case details column)
Note: When browser width is narrow, we can stack labels vertically to save horizontal space. If browser width permits, place multiple labels side by side (limit 2 horizontally before wrapping)
![judge-table-your-cases](https://user-images.githubusercontent.com/31224257/49960999-85c14c80-fedf-11e8-8fcd-6d4295b4868b.png)

**Comment by lowellrex** [comment]
LARGE
