### ISSUE TITLE
Design Queue page when no cases are currently assigned to a user

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5566]
What should we display to users when they currently have no cases assigned to them in their queue? How might we adjust the table view?

## Mocks
TBD

## Resources

This is what Dustin Ware currently sees in Reader when no cases are assigned to him:

![My Reader.PNG](https://images.zenhubusercontent.com/5a81eda04b5806bc2bc6a201/bdb8f30b-4280-4e21-8211-a37f3e959fba)

**Comment by amprokop** [comment]
<StatusMessage title="Tasks not found">
        Sorry! We couldn't find any tasks for you.
      </StatusMessage>;

**Comment by laurjpeterson** [comment]
Taken care of in another ticket. We display copy to explain there are no cases assigned but users can search for cases.
