### ISSUE TITLE
AMA Intake | Review: Handle scenario where claimant is different from Veteran

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5569]
The Form includes the option to list a claimant other than the Veteran. We need a way for users to view associated relationships from the corporate database, so they can select the relevant claimant/appellant when establishing the appeal. At the VBA level, the claimant may need to be added to corporate database (via Share), so we should provide CAs instructions to do so if the Veteran doesn't have any associated relationships yet.

## AC
- Add a required question to the "Enter details" step for all AMA review types
  - "Is the Claimant someone other than the Veteran?"

If yes:
- Show the next question asking to select relationship from BGS (see mock)
- Show radio button list of Veteran relationships from BGS _(_more discovery/definition needed here @shanear_) _
- User can select a name from the list (only one for now) - required field

## Mocks
![image](https://user-images.githubusercontent.com/4042181/40666947-ec99c9a2-632e-11e8-909f-2a3eaba01d09.png)

## Related
#5695 (empty state)

**Comment by abbyraskinUSDS** [comment]
@shanear passing this over to you for review/to add any technical details about the bgs fields.

**Comment by shanear** [comment]
Looks good to me, a couple considerations:

1. Is "Share" capitalized like that? I always thought it was all caps. Like "SHARE".

2. Also we may have access to their relationship to the veteran, if you want to put that on the radio buttons too.

3. Another case we may have to account for is where a user has no relationships in BGS. Might be for another story though.

**Comment by abbyraskinUSDS** [comment]
- I think it actually is "Share" but I'll confirm.
- Yes, that'd be great! I wasn't sure what info we have
- Yeah, i'll make an empty state story.

**Comment by leikkisa** [comment]
@mdbenjam @shanear 

Hey Mark! We are wondering the proposed data structure for storing claimants. We are thinking of making a claimant table with a one to many relationship to reviews (appeals?), so if a claimant was partaking in multiple appeals, they would appear multiple times in the table.  We are thinking of storing the review_id, the participant_id, and perhaps the relationship, and calling on BGS for any other data needed.  Thoughts?

**Comment by leikkisa** [comment]
I'm also wondering if we should hide this feature if there are zero relationships.

**Comment by leikkisa** [comment]
@abbyraskinUSDS When you're back we want to ask you how you want to present the front-end when a veteran has no relationships.

**Comment by leikkisa** [comment]
We are wondering if we should store the veteran in Claimants table if the Veteran is the claimant. Moving forward assuming "yes".

**Comment by leahbannon** [comment]
Confirmed with AMO: we should instruct them to add the claimant in SHARE if they're not in the pre-loaded list or there are none to load. (Creating the claimant in SHARE doesn't create a relationship to the Veteran.)

**Comment by mdbenjam** [comment]
This was the ticket I had made for this: https://github.com/department-of-veterans-affairs/caseflow/issues/5632. I think your approach sounds basically the same so I'm mostly 👍 . Four thoughts:
1) We will probably need a many-to-many relationship between appeal and claimant (https://github.com/department-of-veterans-affairs/caseflow/issues/5536#issuecomment-390758466)
1) Should we call it claimant or appellant. I see advantage with standardizing with VBA terminology. But will that confuse the board. Can the appellant be someone other than the claimant?
1) What is the `review_id`?
1) I'd advocate just caching relationship, because in theory that could be corrected and we add a second source of truth. We could just aggressively cache it.

**Comment by leahbannon** [comment]
Sally to work on test data for Leah to validate

**Comment by leikkisa** [comment]
@leahbannon 564930680 has a relationship on it, so you should be able to use that file number to validate

**Comment by mdbenjam** [comment]
^ This is in UAT right not prod? Just get scared when I see a file number in github :)

**Comment by leikkisa** [comment]
@mdbenjam Yeah it's in UAT

**Comment by suzchap** [comment]
Waiting for Sally to set up a test ID to have the right criteria (relationships)

**Comment by leikkisa** [comment]
@suzchap If you can add address data for 564930680 in VBMS, that file number should be good.  Sandra knows how to do this and said that everyone has VBMS, so preferably have her show you how to do it (even though she's already working on setting addresses for a bunch of other file numbers).

**Comment by suzchap** [comment]
LGTM.
