### ISSUE TITLE
AMA Intake | VBA: Handle scenario where claimant is different from Veteran 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5570]
The Form includes the option to list a claimant other than the Veteran. We need a way for users to view associated relationships from the corporate database, so they can select the relevant claimant/appellant when establishing the appeal. At the VBA level, the claimant may need to be added to corporate database (via Share), so we should provide CAs instructions to do so if the Veteran doesn't have any associated relationships yet.

- Add a required question to the "Enter details" 
  - "Is the Claimant different from the Veteran?"

If yes:
- Show list of Veteran relationships from BGS _(_more discovery/definition needed here @shanear_) _
- User can select a name from the list (only one for now)
- Instructions to add claimant via Share if they don't appear in list

## Related issues
https://github.com/department-of-veterans-affairs/caseflow/issues/5569

**Comment by abbyraskinUSDS** [comment]
How will this work for non-comp business lines? The same as VBA?

**Comment by shanear** [comment]
We don't know yet. We still have to figure that scenario out.

**Comment by abbyraskinUSDS** [comment]
Closing this in favor of #5569 - we can have the same handling for all types of reviews.
