### ISSUE TITLE
Case details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5571]
## Recent activity
- [#710 Case details - initial explorations](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/710)
- [#694 MVP appeals timeline - explorations for showing form dates on case details](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/694)
- [VACOLS content audit (and what to depreciate when)](https://app.mural.ly/t/workqueue2001/m/workqueue2001/1507744211843/c9bc053003b3581e4dd469dc67e208fb113f1e1f) - murally 
- [Exploration of appeal data elements](https://app.mural.ly/t/workqueue2001/m/workqueue2001/1520461927098/e07d6ac4686d64c7c16fa8462daa21778007a450) - murally 
- [#681 Nailing the coffin on Queue patterns](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/681)

---

## Goals
- Provide clarity and context for an appeal
   - Surface the most important and accurate appeal data to the user so they can get context on a case
   - Track how, when, and who updates appeal data
- Ensure accuracy of appeal data, allow for updates
- Deprecate parts of VACOLS UI: docket tab, prior locations tab
- Reuse case details components, prevent custom views for each type of user

## Elements
Here is a list of all the elements for case details to help guide a scoping activity and defining discrete projects for each. 

### User-specific appeal info
- Date assigned
- Assigned by
- Information relevant to Board user assigned to the case. Some examples:
   - Judge: document ID
   - Judge: notes from the attorney from check out
   - Co-located: Admin action type and instructions

### Permissioned actions
- Navigate to Reader
- Ability to update appeal data
- Ability to assign cases to another team

### Veteran details
- RO
- Periods and circumstances of service - branch, dates, etc.
- Special issues? (a la Caseflow Dispatch)
- Addresses
- Appellant if not the Veteran
- Other open appeals

### Case details 
- Docket date
- POA data: who, type, address
- Open mail
- Hearing data: type, judge, disposition ([caseflow/#5083](https://github.com/department-of-veterans-affairs/caseflow/issues/5083))
- Issues + issue dispositions
- Dispatch data: date outcoded
- Appeal timeline/history
   - Surface important document dates
   - Surface important process dates - remand return, original decision
   - Surface important Board processes, teams, and dates - e.g. "prior locations" 
- Data change history - date, time, and which users update appeal data (e.g. POA, hearing preference)

### Edit/Update appeal data
- Clarity on who updated appeal data recently
- Clarity on when that appeal data was updated

### Navigation to Case List
- Navigate back to case list to view additional appeals streams

## Phases + priority
- We will align expansion of case details with deprecation of VACOLS tabs.
- Users will need to edit data on the tabs before we can deprecate them.

1. Docket tab + Issues tab - attorneys need this information in order to complete their decision tasks. 
   - Docket tab includes key dates
2. Address tab

**Comment by allyceh** [comment]
Closing this. We finished this case details work.
