### ISSUE TITLE
Automatic case distribution

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5575]
# Automatic case distribution

## Background
- We are rolling out Queue to judges after attorneys. A key task judges complete is assigning cases to attorneys. 
- Case assignment to attorney process today:
  1. Judges request cases from case storage by entering a spreadsheet on the P: drive for their chief group. It varies how often judges do this.
  2. Case storage assigns them to judges in VACOLS (using Jed's automated program to identify oldest cases, hearing cases, etc.). Case storage assigns AOD cases to senior counsel, who assign cases to judges.
  3. Judges assign cases to attorneys based on a number of parameters:
      - Case complexity: Number of issues, Type of issues, Number of documents, Predicted disposition from a prior hearing
      - Attorney workload
      - Attorney vacation/leave
      - Attorney experience/habits: Some attorneys can handle 10 draft decisions on their plate vs. others finding that overwhelming
      - Some judges also pre-review appeals to help them get context on the case before assigning to attorneys

## Goals
- Speed up the appeals process from case storage to attorneys drafting a decision, by reducing time judges need to spend assigning appeals
- Support case assignment among legacy and AMA dockets

## Hypotheses / Potential Impact
- Reducing judges' manual tasks increases time they can spend completing other tasks, like writing decisions, which streamlines the appeals process at this step
- Attorneys and judges can maintain productivity with automatic case assignment in this way (e.g. random case assignment, or another method outlined below)  
- Attorneys can maintain job satisfaction with automatic case assignment in this way - they don't get burnt out
- Automatic case assignment prevents cases from sitting with a judge for too long before assignment to an attorney (we've heard too long is 60 days)

## Approach
We explored suggesting attorney case assignments to judges in our first round of [usability testing](https://app.mural.ly/t/workqueue2001/m/workqueue2001/1517943430953/5ef685d149db8079f267b34956a4e77b746524e8) with 5 judges. All expressed skepticism about automating assignment to attorneys - they weren't sure an algorithm could take into account all of the subjective pieces of the puzzle. All responded positively to viewing their attorneys' queues. We heard that it takes a lot of time to see what's cases are currently on their attorneys' plates. So, we want to explore breaking up automatic case assignment into smaller chunks - automating case assignment from case storage to judges, not directly to attorneys:

1. Define auto assignment from case storage to judges: Automatically assign case to judges from case storage. Allow Judges to view attorney queues and manually assign cases to attorneys.
2. Depending on how (1) affects speed of case assignment, reintroduce explorations of direct assignment to attorneys with judge approval (original exploration above).
3. Iterate on (1) to incorporate multiple dockets as required by AMA.

## Assumptions
- Working appeals in "docket order" is achieved by assigning cases to attorneys in docket order.

Additional assumptions, if we moved forward with suggesting attorney case assignments:
- Subjective decisions judges make about case assignment can be automated. 
- Automatically assigning cases to attorneys will reduce Judge time spent on case assignment/attorney management.
- Automatically assigning a variety of cases to attorneys will also give judges enough variety in case complexity.

### 1. Automatic case assignment from case storage to judges

Option 1: Cases assigned to Judges when they request in Queue.
Option 2: Queue continuously assigns cases to Judges so they always have cases on their plate.

- **Judges need to be involved in case assignment. They should approve and have the option to adjust their attorney's workload.** They need to have insight into attorney work for their performance evaluations.
  - VACOLS currently has a column for which VLJ the attorney is assigned to. 

- **Judges must sign their own legacy hearing cases to deplete their individual hearing backlogs.** In Cheri's view, legacy hearing cases are higher priority than general population cases because other judges can work gen pops. 
- **The allocation facilitates a steady stream of work for attorneys and judges - cases to write and work products to sign.** 
   - We learned that attorneys tend to request more cases from their judges when they have 1-2 left on their plate and Judges should have ~15-20 work products on their plate at a time.
   - What are the benefits of batch assignment to groups of attorneys a la how judges do it today vs. recognizing when an attorney is low and assigning directly to them?
   - Could we prompt judges to assign to attorneys when attorneys have 1-2 cases on their plate
- **Cases should not sit on judges plates to assign or to sign for long times** (We've heard that 60 days is too long - could we find a different target)
   - What if we required judges to assign all cases to attorneys before getting new cases so they don't sit on cases?
- **Cases should not be allocated to attorneys and judges on PTO/leave**
- **Cases are only allocated to active staff**
- **Judges should be able to swap cases to other attorneys within their group, but not outside of their group**
  - How are attorneys notified about this? Desktop notifications
  - Are there any limitations - e.g. 5 days on plate, attorney opened it in queue
  - Warning message to the user
- **Judges should understand the methodology behind automatic case allocation**

### 2. If we suggested case assignments for attorneys
Requirements as listed above, plus:
- **Attorneys and judges should understand the methodology behind allocation**
- **Attorneys should get a mix of case complexity**
  - What's the lightest weight complexity rating that makes sense for judges and attorneys? Could we prioritize issues over documents? Should we use the existing complexity methodology in VACOLS today?
  - Prioritize issues over documents, and surface AOD (oldest to newest), then CAVC remands (oldest to newest), then the rest oldest to newest
  - Examples:
      - Low complexity: 1-2 issues
      - Medium complexity: 3-4 issues or 3-6 issues (Jebby's rating)
      - Large complexity: 4-8 issues or 7+ issues (Jebby's rating)
      - X-Large complexity: 8+ issues
- **If a case was previously worked on by an attorney (e.g. before OMO or admin action), it should be assigned back to them**
   - Open question if the case is assigned to a different judge than that attorney is aligned with
- **Lower complexity cases are concentrated to lower tenure attorneys** - could potentially be achieved by judges switching cases among their attorneys.

### 3. Incorporate multiple dockets for AMA
- **Attorneys and judges, in the aggregate, get a proportional allocation of both legacy and AMA docket based on the number of appeals in each lane.** Appeals are worked "first in, first out" in each lane.
   - How often should we capture the proportion of appeals across legacy and AMA? 
       - If Veterans can switch between lanes at the Board, should this be daily?
   - Legacy appeals will be stored in VACOLS DB and AMA appeals will be stored in Caseflow DB.
   - Is there an optimal # of cases to assign?
- **We need to take into account 90 day waiting periods for evidence before allocating to judges.**
   - For AMA evidence submission - 90 days after NOD
   - For AMA hearing cases - 90 days after hearing
- **Appeals should be allocated from each docket in such a way that Direct Review appeals (no evidence, no hearing) can hit their target timeline to be worked within a year.** 
  - Caseflow might need to assign more Direct Review appeals than the proportion of appeals at the Board might indicate so they hit the target timeline. 
      - E.g. Let's say the proportion of legacy and AMA appeals is as follows: 10% Direct Review, 10% Evidence Submission, 30% AMA Hearing, 50% Legacy. Fewer Direct Review appeals would be allocated to judges for decisions and therefore those appeals could sit in the Direct Review backlog for longer. If those appeals in the backlog are approaching, say, 200 days at the Board, Caseflow might allocate more than 10% so those appeals can hit the timeline.

## Future Scope
- Out of scope for now, but we could iterate on automatic case assignment to support a pilot of specialty case teams at the Board. More information [here](https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/BVA%20Work%20Queue/Post-Discovery/Case%20Assignment%20Ideas).

## Resources
- Initial conversations about this epic in this now closed [appeals-design-research issue](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/645)

## Additional notes
- Cheri expressed desire to sign decisions for legacy hearing cases close to hearing date - route to attorney right after the hearing - can an attorney start drafting the decision while it's out for a transcript?
- Note: decision template somehow populates an attorney's productivity document - connect with Paul
- Have to know how long it's taking for cases to be worked - Direct Review appeals should be under a year

From Jed about current complexity rating in VACOLS:
>Q: We're interested in the calculation behind the complexity rating in VACOLS. How does it take into account # of issues and # of documents? Where do you get the # of documents number from?

>I created a database function VACOLS.DECASS_COMPLEX the code is below.  Basically it's 1 point for each service connected issue, 2 points for IR issues, 3 points for all other issues, plus 1 point for each 100 documents in the efolder, or 1 point for each volume of a paper case.  The number of efolder documents is entered by the Intake team during case review.

[Jed's Case Distribution program logic](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Post-Discovery/Case%20Distribution%20Program%20-%20no%20PII.pdf)

**Comment by laurjpeterson** [comment]
# Specialty Case Teams - convo with Kristy Zadora - 20180308
Approved by Cheri 20180308
1 year pilot

- Specialty cases will be broken into 29 different categories
  - Examples: IR Eye, Dental, 1151, Spina bifida

Staffing:
- 60 attorneys in the group - each will all be assigned to one or two specialties
- SCT is for 13s and above


VACOLS: Jed has done some programming in VACOLS -
-  topics will be batched out of regular stream
- attorneys will write all the cases in that specialty area, whether hearing or not, no matter who the judge is
- those cases will not be available for normal docket assignment
- under specialty number - (e.g., Eye is 29)
  - you can select a specific number of cases, in docket order, to assign to specific attorneys
   - ie., 3 to bill (will go in docket order)
   - does not allow skipping cases out of docket order
- In DAS:
 - category numbers show in DAS as well - far right column in DAS Print Preview

**Comment by laurjpeterson** [comment]
## Auto-case distribution section of 90 day report

The Board remains committed to an average processing time goal of 365 days for direct docket appeals – appeals received under the new framework that do not include a request for a hearing or an opportunity to submit additional evidence. To accomplish this goal, Digital Service is using a technique called Discrete Event Simulation (DES) to model the Board's dockets and to test and optimize the automatic case distribution algorithm prior to implementation. The outputs of this simulation measure its performance according to identified business objectives. The Board's 365-day average processing time goal for cases on the direct docket is a "constraint" on the algorithm, meaning that direct docket cases must be distributed at a rate that allows the Board to meet its goal. Each case on the direct docket will have a "target distribution date," which will take into account both the date on which the case must be decided in order to meet the timeliness goal (365 days from the date of the NOD), and the average amount of time it takes to issue a decision from the date that the case is assigned to a Veterans Law Judge. The distribution rate of cases on the direct docket will be determined in part by the total number of direct docket cases with a target distribution date close to the current date.
Cases on the legacy, evidence, and hearing dockets are distributed at a rate proportionate to the number of cases on each docket. A natural bias for legacy cases will be created, which ensures that the legacy cases in the Board’s working docket range will be worked prior to those in the hearing or evidence lanes of the new system. The case distribution algorithm will take into account pending remands and historical receipt rates of substantive appeals in calculating the legacy inventory to ensure those appeals are not undercounted. Initially, the Board's inventory of legacy appeals will be larger than its inventory of new system appeals. Therefore, the Board will work a higher percentage of legacy appeals in the first year following the effective date.

The case distribution algorithm must also take into account certain statutory requirements that affect the order in which the Board may decide appeals. Legacy appeals must be decided in order according to docket date, which is based on the date of receipt of a substantive appeal. Legacy appeals retain their original docket date upon return from the agency of original jurisdiction after a remand by the Board. In contrast, appeals under the new framework must be decided in the order they are received on each docket. Under both the legacy and new framework, cases may be advanced on their docket due to the Veteran's age, illness, financial hardship, or other reasons. Cases that have been remanded to the Board by the Court of Appeals for Veterans' Claims must be expedited. Moreover, legacy appeals in which the Veteran testified before a Veterans Law Judge must be decided by the same Veterans Law Judge who presided over the hearing, while no such requirement exists for appeals in the new system.

As a policy matter, the Board may apply additional constraints to the case distribution algorithm. For example, distribution of direct docket cases may be accelerated during the first few months following the effective date. Otherwise, these cases would not be distributed until their target distribution date, which would be nearly a year after the effective date. Placing timeliness contraints on the evidence and hearing dockets would restrict the algorithm's ability to distribute cases proportionate to inventory, prioritize cases based on statutory requirements, and ensure that the direct docket goal is met. If the Board imposed timeliness constraints on all three dockets, there is significant risk that it would be unable to satisfy all of those constraints simultaneously. Initially, the Board anticipates that cases in the evidence and hearing dockets will take longer than those in the direct docket, as a result of the prioritization of legacy and direct docket appeals.

Rather than setting goals for the evidence and hearing docket timeliness prior to implementation, the Board will publish projected wait times for each docket after implementation, based on early results, with regular updates. By providing transparent, realistic timeliness estimates for the other two Board dockets, VA empowers Veterans to make informed choices as to which Board option best suits their individual needs. User research conducted during BEAAM, discussed in more detail in section 4, supports this approach. In particular, Veterans who were interviewed reported that they have limited confidence in timeliness estimates that do not reflect their experiences. Veterans expressed a preference for dynamic time estimates for each option which show a range of durations, rather than an average. Moreover, Veteran representatives expressed that they would cease to recommend an option if it proved unreliable, for example, if a stated timeliness goal was not realistic. Transparency not only assists Veterans in making informed choices, it also allows Veteran representatives to more effectively inform and advocate for their clients, for example, by providing a Veteran facing homelessness with an accurate comparison between wait times on the Board’s hearing and direct dockets.

**Comment by cmgiven** [comment]
Guidance from Cheri, week of July 23: A minimum of 10% of Board capacity should be assigned to Direct Review, scaling up toward the one year timeliness goal.

**Comment by laurjpeterson** [comment]
Done!
