### ISSUE TITLE
Investigate and fix date bug.

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#558]
Spotted for question 7b, 12a.

![pasted image at 2016_01_28 09_49 am](https://cloud.githubusercontent.com/assets/354277/12647929/9f201e84-c5a5-11e5-8f27-2d594aaa3a65.png)

**Comment by webinista** [comment]
This may be a problem with the way the date is formatted and being returned. cc: @paultag @shanear @orischwartz

**Comment by shanear** [comment]
This bug is also an issue on IE 11.

**Comment by paultag** [comment]
So, I believe it's due to formatting. Trying something out

**Comment by paultag** [comment]
OK, so it chokes on the VA formatted `12/12/2012`, but not `2012-12-12`. We need to ensure all the dates on the way out are formatted `YYYY-mm-dd`.

**Comment by paultag** [comment]
I'm going to open a PR tomorrow to remove HTML5 datepicker for the jQuery one everywhere (after some testing and thinking hard)

**Comment by webinista** [comment]
More background and context in case it helps: 

- HTML5 date picker needs to have date values of `YYYY-MM-DD`.
- VA dates are usually `MM/DD/YYYY` ... Are they also MM/DD/YY sometimes?
- The date methods in the code now are used to convert dates to and from `MM/DD/YYYY` and `YYYY-MM-DD` formats to support browsers that support `type=date` and not. 
- The method that converts dates from `YYYY-MM-DD` to `MM/DD/YYYY` format is probably where the bug lies if the date format from the controller isn't being printed in the template as `YYYY-MM-DD` first.

**Comment by orischwartz** [comment]
Superseded by #574, #588
