### ISSUE TITLE
VSOs

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5581]
## Background

Veterans Service Organizations have the following overall goals:
- Assist Veterans in moving through the appeals process
- Helping the veteran by giving reminders and advice about forms, hearings
- Writing and submitting Informal Hearing Presentations (IHPs) for Veterans who have not elected a hearing
- Representing Veterans who have elected a hearing at their hearing.

Veteran Service Organizations (VSOs) currently access their appeals work in VACOLS. They also have access to the Veteran's claims folder in VBMS. (Note: they want access to Reader.)

Under AMA, they will still be writing IHPs. The Board does not need to wait for an IHP to be submitted, though it currently tends to wait. 

If a Veteran has chosen the Direct Review lane under AMA, meaning they are not submitting any new evidence, the Board has a goal timeframe of deciding the case within 365 days from the NOD date. This timeframe will take precedence over waiting for the IHP to be submitted.

## Goals
- Facilitate VSOs knowledge of actions they could take for their Veterans' cases
   - e.g. submit IHP (VSOs are assigned appeals in VACOLS for this today) 
   - e.g. prepare for hearing (VSOs are not assigned appeals in VACOLS for this today)
- Provide VSOs with as lightweight of functionality as required before AMA effective date

## Assumptions
- We could use a lightweight MVP for VSOs
  - Build queue for VSO users - see a list of appeals assigned to that VSO
  - Search for appeals, only see appeals at that VSO

### At any point
- As a VSO representative, I need to be able to see all Veterans' appeals that have chosen me as their representative. (Case search?)
- When a VSO searches for an appeal, the results can only show Veterans' appeals that have chosen them as their VSO.
- As a VSO representative, I need to be able to access Veterans' claims folders in VBMS that have chosen me as their representative. 

### Hearings
- As a VSO representative, I want to be notified of my Veterans' upcoming hearings, so I can contact them, prepare for the hearing, and help the Veteran through the process. (connect with hearing schedule? a view of hearing prep?)

### Informal Hearing Presentations (IHP)
This is likely where the bulk of the functionality lives.
- As a VSO representative, I need to see which appeals have been routed to me (specifically) for an IHP, so I can quickly write it and don't hold it up in the appeals process.
- As a VSO representative, I need to see which AMA or legacy docket the appeal is in, so I know how quickly I need to complete my work (Direct Reviews have a 365 day goal).
- When a VSO representative has finished writing the IHP, they need transfer the case back to the Board, so that the attorney and judge can consider it for the BVA decision.

## Open Questions
- What data can/can't VSOs see that Board employees can?
- What access hurdles do we need to get over first? (none; requisite users have CSS access)
- How does Jed currently know which employees are with which VSOs?
- Can we scope out case assignment to employees within VSO organizations to complete specific tasks? (Jed's case assignment program does this for one VSO)
- Does VSO access equate to access for other representatives that use single sign-on? (https://github.com/department-of-veterans-affairs/caseflow/issues/5581#issuecomment-394783431)
- What is our strategy for answering VSO questions about getting access to Reader?
- What can we do / how does the Board want to manage timeliness by VSOs? The Board has mentioned not requiring or waiting for IHPs, especially for Direct Docket cases and the 365 day goal.
- What is our stance on providing VSOs access to the hearing schedule and how might it fit into the Hearing Schedule roadmap

## Resources
- Jed's answers to a few questions - https://github.com/department-of-veterans-affairs/dsva-vacols/issues/9
- [VSO Mural from Queue discovery](https://app.mural.co/t/workqueue2001/m/workqueue2001/1505353215232/e9fee82ce547bd3fc9f1d6cea01947f5b2527920)
- [VSO Research 2018](https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/Caseflow%20Queue/Research/VSO%20research)

**Comment by laurjpeterson** [comment]
Notes 6/4:

### Scope
- likely need a new function in Caseflow for VSOs 
   - VSOs and Queue
      - what is our scope? searching, viewing Veterans with that particular VSO, viewing cases assigned to that particular VSO user
      - restrict Hearing Worksheet
      - restrict editing functionality
   - VSOs and Reader
      - we need to restrict attorney and judge comments
      - do we allow VSOs to make comments?
- How many non-VSO attorneys have access to VBMS? 
  - 1500 VSOs have access to VACOLS

### Questions
- what about other attorneys who have access to VBMS (they don't have access to VACOLS today)?

### Rollout questions
- What does a pilot look like with VSOs? Which would we partner with? Should we choose a co-located VSO to partner with?

### Project schedule
1. Board quarterly meeting with VSOs on Thursday. Dustin could ask if some VSOs are interested in user research. Multiple co-located VSOs - American Legion, PVA, DAV.
2. Brief VSO research plan, proposed scope - next week's leadership meeting
3. Create VSO interview guide

**Comment by nicholasholtz** [comment]
Changed "VSO attorney/employee" references to "VSO representative" throughout; VSO reps are generally not attorneys, and because there is also the other question of access for non-VSO representatives that may be attorneys (which I also added), did not want to have confusion there.

**Comment by nicholasholtz** [comment]
Re: scope - Reader:
- adding Reader at this stage raises serious questions as far as bandwidth of the team in light of AMA implementation. 

Re: scope - Private attorneys:
- For Queue, the use case is different, as attorneys do not create IHPs; if this is focused on the flow of cases through BVA a la Queue, then this is likely out of scope.

**Comment by mkhandekar** [comment]
👀

**Comment by laurjpeterson** [comment]
LRP presentation to Chairman 3/29/2018: [Informal Hearing Presentations for Chair_March29_2018.pptx](https://github.com/department-of-veterans-affairs/caseflow/files/2263543/Informal.Hearing.Presentations.for.Chair_March29_2018.pptx)

**Comment by laurjpeterson** [comment]
8/16 - @lowellrex, @nicholasholtz, and @laurjpeterson met to discuss rollout plans

### RAMP appeals pilot scope - October 2018
- VSOs can search for any **AMA appeal (BEAAM appeal and/or RAMP appeal)** where they are listed as the VSO in VACOLS
- VSOs can view a list of all cases where they are listed as the VSO in VACOLS (regardless of user)
- VSOs can view case details for those cases

### Rollout plans
- Test with PVA user Jamie Rudert. As of 8/16, the only AMA appeals we have readily available in our Caseflow DB are BEAAM appeals. Pending deploy on 8/17, we can test PVA view of BEAAM appeals in prod with Jamie as early as next week.
- Once RAMP appeals have been "re-intaked", we can test with additional VSO users
- Test with a few users from American Legion and DAV, because we've conducted research with them July - August
- Identify VSOs with RAMP appeals, and rollout to select users from those VSOs

### Comms
- When testing with VSO users, we should explain that this functionality is just to support the RAMP appeals pilot, and more functionality will come down the line. We anticipate VSOs will not think this Caseflow scope meets their needs.

Queue overall launch and rollout plans live [here](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Launch/Queue%20Rollout%20Plans.md)

**Comment by laurjpeterson** [comment]
@lowellrex @mdbenjam - these are the VSOs that write IHPs, and therefore will be the organizations where the Board assigns tasks to, and where they complete the IHP task:

1. **Armed Forces Services Corporation, Room 2W.240J
1. **American Legion (AL), Room 2E.102B
1. **American Red Cross (ARC), Room 2W.240K
1. **American Veterans (AMVETS), Room 2W.240G
1. **Blinded Veterans Association (BVA), Room 2W.240M
1. **Catholic War Veterans (CWV), Room 2W.240D
1. **Disabled American Veterans (DAV), Room 2E.250J
1. **Fleet Reserve Association (FRA), Room 2W.240C
1. **Marine Corps League (MCL), Room 2W.240I
1. **Maryland Department of Veterans Affairs (MDVA)
1. **Military Order of the Purple Heart (MOPH), Room 2W.240P
1. **National Veterans Legal Services Program, Inc. (NVLSP), Room 2W.240H
1. **Navy Mutual Aid Association (NMAA), Room 2W.240J
1. **Paralyzed Veterans of America (PVA), Room 2W.210C
1. **Veterans of Foreign Wars (VFW), Room 2E.450K **Vietnam Veterans of America (VVA), Room 2W.220F
1. **Wounded Warrior Project (WWP), Room 2W.240S – VSO-Flexi Desk

Reference: https://github.com/department-of-veterans-affairs/dsva-vacols/issues/33
- This is where you can find Jed's comments on VSO 3-letter codes, too

**Comment by laurjpeterson** [comment]
some updates from this morning's BVA leadership meeting re: VSOs
1. cheri has decided to wait until the start of the RAMP appeals pilot, october 2, to experiment with co-located VSO IHP turnaround times. this means:
   - we don't need to rush to get VSO users access to caseflow (outside of testing in prod with a few of them)
   - we'll have fewer cases that are ready to work right on oct 2 because we will have to wait for VSOs to submit IHPs for some evidence submission and direct review cases

2. she wants to give access only to VSOs that have RAMP appeals. @cmgiven is getting us the updated list of VSOs with RAMP appeals so we can identify users from only those VSOs
  - this means fewer VSOs needing access than previously thought (1 from each org)

**Comment by laurjpeterson** [comment]
RAMP appeal VSOs as of 9/5/2018. **Bolded = co-located VSO that writes IHPs**


  | direct_review | evidence_submission | hearing | total
-- | -- | -- | -- | --
**AMERICAN LEGION | 5 | 1 | 21 | 27**
**AMVETS | 1 |   | 1 | 2**
ARIZONA DEPARTMENT OF VETERANS' SERVICES |   |   | 1 | 1
CALIFORNIA DEPARTMENT OF VETERANS AFFAIRS |   |   | 3 | 3
**DISABLED AMERICAN VETERANS | 8 | 5 | 10 | 23**
FLORIDA DEPARTMENT OF VETERANS AFFAIRS | 1 | 1 | 3 | 5
GEORGIA DEPARTMENT OF VETERAN SERVICE | 1 |   |   | 1
ILLINOIS DEPARTMENT OF VETERANS AFFAIRS |   |   | 1 | 1
MISSOURI VETERANS COMMISSION | 1 |   |   | 1
NATIONAL ASSOCIATION FOR BLACK VETERANS,   INC |   |   | 1 | 1
NATIONAL VETERANS ORGANIZATION OF   AMERICA, INC |   |   | 1 | 1
NEW YORK DIVISION OF VETERANS AFFAIRS | 1 |   |   | 1
OKLAHOMA DEPARTMENT OF VETERANS AFFAIRS |   |   | 1 | 1
SOUTH CAROLINA DIVISION OF VETERANS   AFFAIRS | 1 | 1 | 1 | 3
TENNESSEE DEPARTMENT OF VETERANS SERVICES |   |   | 1 | 1
TEXAS VETERANS COMMISSION | 3 | 1 | 6 | 10
**VETERANS OF FOREIGN WARS OF THE US | 3 | 1 | 4 | 8**
**VIETNAM VETERANS OF AMERICA |   |   | 3 | 3**
WISCONSIN DEPARTMENT OF VETERANS AFFAIRS |   |   | 1 | 1
Grand Total | 25 | 10 | 59 | 94

@nicholasholtz do you know if National Association for Black Veterans, Inc is a VSO that writes IHPs?

### VSOs with Evidence and Direct Review RAMP appeals needing access for October
- American Legion
- AMVETS
- DAV
- VFW
- VVA (note: requested to help testing Caseflow, but only has Hearing docket cases)

**Comment by mdbenjam** [comment]
I don't see NCOA in BGS. But besides that here are the organizations I'm going to add:

```
Vso.create(name: "Armed Forces Services Corporation", role: "VSO", feature: "vso_queue", url: "armed-forces-services-corporation", participant_id: "2452332")

Vso.create(name: "American Legion", role: "VSO", feature: "vso_queue", url: "american-legion", participant_id: "2452327")

Vso.create(name: "American Red Cross", role: "VSO", feature: "vso_queue", url: "american-red-cross", participant_id: "2452407")

Vso.create(name: "American Veterans", role: "VSO", feature: "vso_queue", url: "american-veterans", participant_id: "2452322")

Vso.create(name: "Blinded Veterans Association", role: "VSO", feature: "vso_queue", url: "blinded-veterans-association", participant_id: "2452334")

Vso.create(name: "Disabled American Veterans", role: "VSO", feature: "vso_queue", url: "disabled-american-veterans", participant_id: "2452340")

Vso.create(name: "Fleet Reserve Association", role: "VSO", feature: "vso_queue", url: "fleet-reserve-association", participant_id: "2452343")

Vso.create(name: "Marine Corps League", role: "VSO", feature: "vso_queue", url: "marine-corps-league", participant_id: "2452359")

Vso.create(name: "Maryland Department of Veterans Affairs", role: "VSO", feature: "vso_queue", url: "maryland-department-of-veterans-affairs", participant_id: "2452360")

Vso.create(name: "Military Order of the Purple Heart", role: "VSO", feature: "vso_queue", url: "military-order-of-the-purple-heart", participant_id: "2452362")

Vso.create(name: "National Veterans Legal Services Program", role: "VSO", feature: "vso_queue", url: "national-veterans-legal-services-program", participant_id: "2452368")

Vso.create(name: "Veterans of Foreign Wars", role: "VSO", feature: "vso_queue", url: "veterans-of-foreign-wars", participant_id: "2452411")

Vso.create(name: "Vietnam Veterans of America", role: "VSO", feature: "vso_queue", url: "vietnam-veterans-of-america", participant_id: "2452415")

Vso.create(name: "Wounded Warrior Project", role: "VSO", feature: "vso_queue", url: "wounded-warrior-project", participant_id: "20388167")
```

**Comment by cmgiven** [comment]
Counts as of 9/20/18.

VSO Name                                          | Count
--------------------------------------------------|------
DISABLED AMERICAN VETERANS                        | 48
AMERICAN LEGION                                   | 47
TEXAS VETERANS COMMISSION                         | 19
VETERANS OF FOREIGN WARS OF THE US                | 15
INDIVIDUAL                                        | 13
CALIFORNIA DEPARTMENT OF VETERANS AFFAIRS         | 11
INDIVIDUAL                                        | 8
FLORIDA DEPARTMENT OF VETERANS AFFAIRS            | 7
VIETNAM VETERANS OF AMERICA                       | 6
INDIVIDUAL                                        | 5
INDIVIDUAL                                        | 4
SOUTH CAROLINA DIVISION OF VETERANS AFFAIRS       | 3
INDIVIDUAL                                        | 3
NORTH CAROLINA DIVISION OF VETERANS AFFAIRS       | 2
AMVETS                                            | 2
INDIVIDUAL                                        | 2
INDIVIDUAL                                        | 2
NEW YORK DIVISION OF VETERANS AFFAIRS             | 2
ILLINOIS DEPARTMENT OF VETERANS AFFAIRS           | 2
OKLAHOMA DEPARTMENT OF VETERANS AFFAIRS           | 2
INDIVIDUAL                                        | 2
INDIVIDUAL                                        | 2
INDIVIDUAL                                        | 1
GEORGIA DEPARTMENT OF VETERAN SERVICE             | 1
NATIONAL VETERANS ORGANIZATION OF AMERICA, INC    | 1
WISCONSIN DEPARTMENT OF VETERANS AFFAIRS          | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
NATIONAL ASSOCIATION FOR BLACK VETERANS, INC      | 1
ARIZONA DEPARTMENT OF VETERANS' SERVICES          | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
AGENT OR PVT ATTY-EXCLUSIVE CONTACT NOT REQUESTED | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
MISSOURI VETERANS COMMISSION                      | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
TENNESSEE DEPARTMENT OF VETERANS SERVICES         | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1
INDIVIDUAL                                        | 1

**Comment by cmgiven** [comment]
Disaggregated by docket.

VSO Name | Direct Review | Evidence Submission | Hearing | Total
--|--|--|--|--
DISABLED AMERICAN VETERANS | 13 | 10 | 25 | 48
AMERICAN LEGION | 10 | 2 | 35 | 47
TEXAS VETERANS COMMISSION | 5 | 2 | 12 | 19
VETERANS OF FOREIGN WARS OF THE US | 4 | 2 | 9 | 15
INDIVIDUAL | 11 | 2 |  | 13
CALIFORNIA DEPARTMENT OF VETERANS AFFAIRS | 4 |  | 7 | 11
INDIVIDUAL |  | 4 | 4 | 8
FLORIDA DEPARTMENT OF VETERANS AFFAIRS | 2 | 1 | 4 | 7
VIETNAM VETERANS OF AMERICA |  |  | 6 | 6
INDIVIDUAL | 4 | 1 |  | 5
INDIVIDUAL | 2 | 2 |  | 4
SOUTH CAROLINA DIVISION OF VETERANS AFFAIRS | 1 | 1 | 1 | 3
INDIVIDUAL | 2 | 1 |  | 3
NORTH CAROLINA DIVISION OF VETERANS AFFAIRS | 1 |  | 1 | 2
AMVETS | 1 |  | 1 | 2
INDIVIDUAL |  |  | 2 | 2
INDIVIDUAL | 1 | 1 |  | 2
NEW YORK DIVISION OF VETERANS AFFAIRS | 2 |  |  | 2
ILLINOIS DEPARTMENT OF VETERANS AFFAIRS | 1 |  | 1 | 2
OKLAHOMA DEPARTMENT OF VETERANS AFFAIRS |  |  | 2 | 2
INDIVIDUAL |  | 2 |  | 2
INDIVIDUAL | 1 |  | 1 | 2
INDIVIDUAL |  |  | 1 | 1
GEORGIA DEPARTMENT OF VETERAN SERVICE | 1 |  |  | 1
NATIONAL VETERANS ORGANIZATION OF AMERICA, INC |  |  | 1 | 1
WISCONSIN DEPARTMENT OF VETERANS AFFAIRS |  |  | 1 | 1
INDIVIDUAL | 1 |  |  | 1
INDIVIDUAL | 1 |  |  | 1
NATIONAL ASSOCIATION FOR BLACK VETERANS, INC |  |  | 1 | 1
ARIZONA DEPARTMENT OF VETERANS' SERVICES |  |  | 1 | 1
INDIVIDUAL | 1 |  |  | 1
INDIVIDUAL |  |  | 1 | 1
AGENT OR PVT ATTY-EXCLUSIVE CONTACT NOT REQUESTED |  |  | 1 | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL | 1 |  |  | 1
INDIVIDUAL |  |  | 1 | 1
MISSOURI VETERANS COMMISSION | 1 |  |  | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL |  |  | 1 | 1
TENNESSEE DEPARTMENT OF VETERANS SERVICES |  |  | 1 | 1
INDIVIDUAL | 1 |  |  | 1
INDIVIDUAL |  | 1 |  | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL |  |  | 1 | 1
INDIVIDUAL |  | 1 |  | 1

**Comment by laurjpeterson** [comment]
@lowellrex @mdbenjam @amprokop - FYI, the chairman does not want to adhere to VSO turnaround times for October pilot anymore. 

From Andrea MacDonald's email: 
> She indicated RAMP is too soon to hold VSOs to IHP limitations. She suggested we could encourage VSOs participating in RAMP to test the limitations which will be enforced later on a phased in basis. She confirmed 30 days for AODs and 45 for all other cases.

My response: 

It sounds like she does *not* want to hold VSOs accountable for the 30 or 45 day time frame starting October 1. This means that Caseflow should *prevent* distributing cases needing IHPs to judges even if it goes beyond 30 or 45 days.

Re: Caseflow - we don't yet have functionality for VSOs to send cases back to the Board through Caseflow. What I'd recommend to track VSO turnaround times until we have that is:
1. Appeal establishment date / date assigned to VSO - from Caseflow
   - October 1 for all appeals established in Caseflow Intake prior to October 1
   - Intake date for appeals established after Oct 1 
      - (Caseflow automatically adds a "Submit IHP" task for cases with IHP-writing VSOs at the time of establishment)
2. Date returned to BVA - manual
   - Option 1: VBMS upload date
       - Note: this might not be the exact date when the VSO put the IHP in the shared drive, but it is the date when the appeal can move. 
   - Option 2: Date on the IHP pdf/word doc itself
   - Another option?

**Comment by lowellrex** [comment]
> Re: Caseflow - we don't yet have functionality for VSOs to send cases back to the Board through Caseflow.

I think we're most of the way there. VSO employees can mark tasks complete in their queues now, so I think the only thing left to do is modify the query we use to determine which cases are ready for distribution to judges. It's possible @mdbenjam or @amprokop has already modified the assignment code to properly handle this case (I'm not familiar with where in the code that happens), but if not then I can take that on.

**Comment by laurjpeterson** [comment]
@lowellrex @mdbenjam @cmgiven @nicholasholtz

@nikitarockz is tracking which specific VSO users are in the process of getting VSO access to Caseflow in issues in the appeals-pm repo

For now, we have a few users in flight for the following VSOs
- PVA - Jamie Rudert
- DAV - Tom Wendel (is out until Oct 9 so I emailed other DAV contacts to see if anyone else needs access. @nicholasholtz will take follow-ups here)
- American Legion - Bill Wertman
- VVA - Alec Ghezzi 
- VFW - Sylvester and Chance
- AMVETS - Duayne Driscoll, Christopher Johnson, Mike

**Comment by laurjpeterson** [comment]
URLs:
- PVA: `appeals.cf.ds.va.gov/organizations/pva`
- American Legion: `appeals.cf.ds.va.gov/organizations/american-legion`
- DAV: `appeals.cf.ds.va.gov/organizations/disabled-american-veterans`
- VVA: `appeals.cf.ds.va.gov/organizations/vietnam-veterans-of-america`

**Comment by laurjpeterson** [comment]
Sat with DAV user 10/16. 
Confirmed that all users from PVA, DAV, American Legion, and VVA have been able to log into Caseflow. 
VFW users at a conference this week.
AMVETS users have yet to get CSEM access.

**Comment by laurjpeterson** [comment]
Chatted with @lowellrex about VSO queues 10/30:
- Not all cases with VSOs require IHPs. All co-located VSOs write IHPs only for Evidence Submission, Direct Review, and Legacy cases without hearing requests EXCEPT for PVA, who write IHPs for all appeals. 
- Because of this, it likely makes sense to populate the list of cases that each VSO has in a different way, other than them having VSO tasks associated with them. We won't make any changes to what we are doing now, just add improvements late.
- We can potentially put the onus on the VSO to tell us when they create Submit IHP tasks. In the Case details view, we can add an Action to `Add Submit IHP task` so VSOs can assign only cases needing IHPs to individuals.

**Comment by laurjpeterson** [comment]
RAMP appeal VSOs as of 11/06/2018

<img width="926" alt="screen shot 2018-11-06 at 1 31 08 pm" src="https://user-images.githubusercontent.com/27704093/48092768-99401000-e1db-11e8-9471-e3731b15d86e.png">

**Comment by laurjpeterson** [comment]
# Draft Plan for rolling out Caseflow to more VSOs 

## Background
There are two types of VSOs - VSOs that write IHPs (often referred to as co-located) and VSOs in the field that do not write IHPs. Some examples:
-  IHP writing VSOs - American Legion, Veterans of Foreign Wars
- Field VSOs - CalVet, Texas Veterans Commission

All types of VSOs currently have access to VACOLS, and will need access to Caseflow. They have VBMS, so do not need Reader at this time.

Co-located/IHP-writing VSOs have more access in VACOLS than Field/non-IHP writing VSOs, who have read-only VACOLS access.

## VSO functionality

### Both IHP-writing and non-IHP writing VSOs
- Search and view only cases for which they are the VSO
- View a list of cases for which they are the VSO
- View Case details for those cases 

### Only IHP-writing VSOs
- Assign IHP tasks to users (not in production yet)
- Users' individual queues (not in production yet)
- Complete IHP tasks (in production)

## Goals:
1. All IHP-writing VSOs have access to Caseflow to view RAMP/AMA appeals by February 14th
2. All other VSOs have access to Caseflow  to view RAMP/AMA appeals by February 14th - field offices currently have read-only VACOLS capabilities)

**Out of scope before February:**
- All VSOs viewing Legacy appeals in Caseflow

## Suggested phases:
1. Small number of users from IHP-writing VSOs with evidence submission and direct review RAMP appeals - _in progress_
    - American Legion 
    - DAV
    - AMVETS
    - VFW
    - MOPH (first user in progress)
    - PVA
    - VVA (also has access, but no evidence submission or direct review RAMP appeals)

2. All IHP writing users from IHP-writing VSOs with evidence submission and direct review RAMP appeals - _in progress_ 
    - Initiating access for 10+ DAV and 10+ American Legion users
    - Questions:
	    - Should we ask BVA to initiate getting all of the IHP-writing VSOs access to Caseflow now, proactively? (LP thinks yes)
	    - Is there any reason to restrict access now? For example, Legion asked for their Indianapolis located VSOs to have Caseflow access because they write IHPs. I don't see any reasons.

3. Create CSEM function for non-IHP writing VSOs for their "read only" access. This can probably be used by the Private Bar as well. 
     - Questions: 
             - Is a separate CSEM function needed? 

4. Implement whatever is needed for that read-only VSO view.

5. Initiate access for all other VSOs (could be ~1500 field VSO reps)
    - Questions:
	    - Should we ask BVA to initiate getting all of the non IHP-writing VSOs access to Caseflow, proactively? (LP thinks yes)
            - When should this happen? (LP thinks starting in January)
	    - How should we phase out this access? Regionally?

### Questions and Unknowns
- I don't know if Field VSOs would benefit from having individual queues - assuming they won't for now
- I don't know the exact number of field + IHP-writing VSO users. Jed estimates 80 co-located/IHP-writing VSOs + 1500 field VSOs here - https://github.com/department-of-veterans-affairs/dsva-vacols/issues/9

---
@nicholasholtz @lowellrex @sneha-pai @marvokdolor-gov @nikitarockz-  i'd love your feedback on the above plan for more VSO users to get access to Caseflow.

My main questions for you:
- When should each of these phases take place, knowing that now that we have given access to some (1-3 users) from IHP-writing VSOs, requests to expand that access have been coming in.
- Are the goals and time frames I've listed above correct?
- Do you agree that BVA should be involved in initiating access for VSOs as I've listed?

**Comment by lowellrex** [comment]
I see no harm in an aggressive rollout schedule for VSOs, both in increasing number of users that belong to a given VSO and the number of total VSOs that have queues in Caseflow (with the caveat that non-IHP writing VSOs will only be able to view their cases through search until #7905 is merged).

**Comment by nikitarockz** [comment]
My thoughts and beliefs.  😄 

1. When should each of these phases take place, knowing that now that we have given access to some (1-3 users) from IHP-writing VSOs, requests to expand that access have been coming in.
     - How should we phase out this access? Regionally?
     **_Definitely regionally, just like we did Certification._**
     - Is there any reason to restrict access now? For example, Legion asked for their Indianapolis located VSOs to have Caseflow access because they write IHPs. I don't see any reasons.
     **_I think it is ok.  I think this first group serves as a great pilot.  I was preparing to get that started.  What kind of feedback have you been getting from these current users?  Is the feedback causing the need for changes or positive comments with no changes suggested?_**

2. Are the goals and time frames I've listed above correct?     
     - All IHP-writing VSOs have access to Caseflow to view RAMP/AMA appeals by February 14th 
     **_Yes, I feel like this makes sense and is do able._**

     - All other VSOs have access to Caseflow to view RAMP/AMA appeals by February 14th - field offices currently have read-only VACOLS capabilities) 
     **_With this being about 1,500 users, this may be a stretch since everyone will have to submit paper work.  SInce these users will be read only, I feel like we have time to push it out a bit.  I am thinking the focus should be on the IHP writing ISO users to meet the 2/14 goal._** 

3. Do you agree that BVA should be involved in initiating access for VSOs as I've listed?  
**_BVA CSEM Initiator can only submit requests for those considered a part of BVA.  For all other VSOs (field) not at station 101, their specific station CSEM Initiator will have to provide them access.  I have been working with OBPI.  They have agree to help with any user access that is required at other stations since we can't directly submit those requests in CSEM.   This will be same process we used when we rolled out access to Certification users who are across all stations._**
     - Is a separate CSEM function needed?
     **_It will be easy to add a new "function" such as VSO-ReadOnly.  Will it be important to track who has Read-only access?  Will having this function make it easier to render to correct read only pages?_**
     - Should we ask BVA to initiate getting all of the non IHP-writing VSOs access to Caseflow, proactively? 
     **_Yes, beginning in January will be a good time since it will be after the holidays and it might take a while for all users to submit their forms._**

**Comment by nicholasholtz** [comment]
@laurjpeterson I think this looks good, and I think your assumptions are on the mark. 

@nikitarockz re:
> All other VSOs have access to Caseflow to view RAMP/AMA appeals by February 14th - field offices currently have read-only VACOLS capabilities)
With this being about 1,500 users, this may be a stretch since everyone will have to submit paper work. SInce these users will be read only, I feel like we have time to push it out a bit. I am thinking the focus should be on the IHP writing ISO users to meet the 2/14 goal.

- I do not think that date is something that can be pushed. 

> Should we ask BVA to initiate getting all of the non IHP-writing VSOs access to Caseflow, proactively?
> **_Yes, beginning in January will be a good time since it will be after the holidays and it might take a while for all users to submit their forms._**

I think this might have been a typo - the non-IHP-writing VSOs will be out in the field, and would not be initiated by BVA, correct?

**Comment by laurjpeterson** [comment]
@nicholasholtz @nikitarockz - thank you!

> I think this might have been a typo - the non-IHP-writing VSOs will be out in the field, and would not be initiated by BVA, correct?

I meant that we would reach out to field VSOs and initiate the process of getting them CSEM access. Someone from BVA or the Caseflow team would get updated VSO contacts from Nick U and reach out to each VSO contact asking for the list of people that need access, their CSS IDs, and all CSEM required forms. 

I think this is something that we could initiate, right @nicholasholtz?

**Comment by marvokdolor-gov** [comment]
I don't know enough to provide any substantive feedback here, but happy to help with the emails out to VSOs.

**Comment by laurjpeterson** [comment]
closing, knowledge docs/base will be stored in the wiki, here: https://github.com/department-of-veterans-affairs/caseflow/wiki/VSOs
