### ISSUE TITLE
Intake stats | padding issue

### ISSUE THREAD

**Issue by leahbannon** [department-of-veterans-affairs/caseflow#5584]
The spacing between the bar charts got a little wonky, especially for the new RAMP refilings section.

I'm on Chrome 65.0.3325.181

<img width="1135" alt="screen shot 2018-05-16 at 5 56 52 pm" src="https://user-images.githubusercontent.com/4323988/40146253-d40348ba-5932-11e8-9f0d-0b902cb76d6a.png">

**Comment by abbyraskinUSDS** [comment]
We aren't going to continue developing the stats page, closing this out.
