### ISSUE TITLE
Outcoding, upload, and EP creation for AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5591]
# Background
After a case is outcoded from VACOLS, employees at the Appeals Resource Center use Caseflow Dispatch to create EPs in VBMS that can be routed to, picked up in VBMS, and worked by the correct Agency of Jurisdiction (AOJ) for claim adjudication. 

There are many appeals with special issues that require special routing and adjudication. Attorneys and judges are the subject matter experts for issues, so an idea was floated: what if attorneys marked special issues when they assigned draft decisions to judges, judges confirmed them, and EPs were automatically created when the case is "outcoded" from BVA?

# Goals
- Speed up time from outcoding to claims adjustment (same metric as Caseflow Dispatch today)
- Batch outcoding, upload to VBMS, and EP creation at the time BVA dispatch outcodes an appeal, so we can deprecate Caseflow Dispatch

# Assumptions
- Attorneys and judges will understand special issues as outlined in Caseflow Dispatch
- All compensation appeals will be adjusted in VBMS
- Caseflow will build queues for non-compensation business lines to adjust their claims

# Phases & Stories

### Attorney & judge check out
- As an attorney or judge, I want to mark special issues when I am assigning a draft decision to my judge. These special issues directly align with special issues requiring special adjudication.
   - *Update: included for AMA appeals for October 1 RAMP appeals pilot*
   - TODO: update routing and include for legacy

### BVA dispatcher - IDT flow
- BVA dispatchers need to verify an errorless BVA decision before finalizing the decision and uploading to VBMS. 

### Automatic upload to VBMS
- As a BVA dispatch user [or as a judge], I need to upload the final, errorless BVA decision to VBMS, so that BVA has the correct system of record.
- Caseflow saves the decision document from the IDT to s3.
- Decision document is uploaded from s3 to VBMS. We think there should be a lag between finishing the IDT and uploading to VBMS just in case there are any errors.

### EP Creation
- For compensation and other entities that use VBMS:
    - EPs are created as a background job.
    - EPs are only created if a decision exists in VBMS.
    - At the time of outcoding, EPs are created and routed to the correct location based on special issues marked by attorneys and judges and/or by automatically identifying those special issues based on VBMS data (like flashes)
         - in progress - https://github.com/department-of-veterans-affairs/caseflow/issues/6903
- For non-compensation business lines that do not use VBMS:
    - A task is created in the correct non-compensation Caseflow queue
    - At the time of outcoding, a work item is created in Caseflow and put into the appropriate organization's queue.

#### TODO:
- Define requirements for automatically identifying special issues

#### Resource:
- Routing logic (in progress): https://github.com/department-of-veterans-affairs/caseflow/issues/6903#issuecomment-420317509

### Supplemental Claim Creation
Note: Collaboration with Caseflow Intake cc: @shanear 

# Resources
[Caseflow Dispatch Project Description](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Dispatch%20Project%20Description.md)
- [BVA dispatch epic](https://github.com/department-of-veterans-affairs/caseflow/issues/5590)

# Future opportunities
- Generate special issues based on issues on appeal, rather than asking attorneys/judges to enter them.

**Comment by laurjpeterson** [comment]
Note: we're pulling in Special issues to the attorney checkout flow for October 1 RAMP appeals pilot because it is easier than connecting to Caseflow Dispatch.

**Comment by laurjpeterson** [comment]
Intake: dispatch related issues:
- https://github.com/department-of-veterans-affairs/appeals-design-research/issues/998
- https://github.com/department-of-veterans-affairs/caseflow/issues/6167

**Comment by allyceh** [comment]
Potential update to user stories: Last time around, we discovered that it's not required by law that the decision date on the letter match the upload date in VBMS. This is an internal policy to encourage VBMS uploads. Noting this so that we know that it's amendable.

**Comment by laurjpeterson** [comment]
Hypothesis: if we own batching uploading to VBMS and creating EPs automatically, it will reduce time from dispatch to claim adjustment.

Strategy:

- Phase 1: Upload decisions to VBMS but do not create EPs
- Should we do AMA and legacy cases concurrently? Yes, for uploading.

To do's:

**Phase 1: Get legacy appeals ready**
1. Finish POA address from BGS for legacy appeals
1. Veteran name and address from BGS for legacy appeals
1. Return legacy cases through Caseflow API for BVA Dispatch IDT (currently, Caseflow is only sending AMA cases)
1. Implement attorneys/judges marking special issues for legacy appeals (https://github.com/department-of-veterans-affairs/caseflow/issues/7216)
    - Compare with ARC marking special issues - LP

**Phase 2: Upload to VBMS**
1. Spec out how we would upload decisions from IDT to VBMS during dispatch using s3 - Anya
   - Consider error states

**Phase 3: Automatically create EPs**
1. Finish requirements gathering/updating EP creation and routing logic - LP
   - Confirm what we're doing for non-comp business lines


Future (post-February)
- Consider saving BVA decision to s3 after attorney drafts it
   - benefits: 
      - eliminates issues with document IDs
      - issues with users modifying the shared drive
      - if we are migrating away from IDT, s3 is the first step
- Deprecate Caseflow Dispatch for legacy appeals
- Investigate and decide whether we should give BVA dispatchers a Caseflow queue instead of IDT queue. This allows us to have a dispatch to judge/attorney flow. - Allyce
   - We'd need to make changes to judge/attorney queues so they know this is a task coming from BVA dispatch. We don't have a task column for them yet.

**Comment by shanear** [comment]
> Phase 3: Automatically create EPs

Sierra can assist with the development of this part

**Comment by laurjpeterson** [comment]
Discussion 11/15
- EP creation can only occur when decision has been uploaded to VBMS because the VBA user needs to view the decision document in order to process the EP
- Save the decision document in our own s3
- We need a background job to upload the decision from s3 to VBMS
   - Perhaps we have a long lag between outcoding and VBMS upload so BVA dispatchers can undo?
- EP creation background job starts
- (Routing happens with the National Work Queue)
- Create task in non-comp queues

To do's:
1. Decision issues backend and front end (11/19 - 11/30 sprint)
1. @aroltsch to present outcoding to intake team
1. Background job for document upload 
1. Background job for EP creation - @shanear  
1. Meet with Josh for special issues routing - @shanear and @laurjpeterson 
1. Define requirements for automatically identifying special issues - @shanear and @laurjpeterson 
1. Redesign special issues page - @allyceh 
1. Designing how to show special issues in Case details - @allyceh

**Comment by laurjpeterson** [comment]
We're automatically creating EPs!
