### ISSUE TITLE
Show when a Veteran's claims folder has new documents

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5593]
As any Board employee, I want to see if there are any new documents in a Veteran's claims folder so I can assess if I still can / continue to work on the case.
   - e.g. As an attorney, if a FOIA request comes in the mail I want to be notified, so I can know that I cannot finish the decision, I need to transfer the case to FOIA.
   - e.g. As a co-located team member, after I've sent correspondence to a Veteran for a hearing clarification and placed the case on hold, I want to see if there are new documents added to the eFolder so I can check if that new document is the Veteran's answer, and I can complete the hold.

### Questions to be aware of
- Who is alerted by new documents in eFolder when a case is in "case storage" or not assigned to anyone?
- If we are showing any user when there are new documents in the eFolder, what happens to the mail team? Do all users know how to handle all mail?

### Where do users get notified of new documents?
- [x] within table row
- [x] case details
- [x] In Progress & On Hold tabs (gmail style) - ❌out of scope for now

### Resources
- SPIKE ticket- https://github.com/department-of-veterans-affairs/caseflow/issues/5410

**Comment by mkhandekar** [comment]
I updated the original issue with **where users get notified of new documents**, and will be working on this this sprint.

**Comment by mkhandekar** [comment]
Work in progress that was shared with the team yesterday:

### Visual indicator within tabs when there are new documents associated with the cases within that tab

<img width="1080" alt="screenshot 2018-06-14 15 27 49" src="https://user-images.githubusercontent.com/1598889/41433658-9734e06c-6fe7-11e8-91f5-3d3ddfe05edb.png">

### Visual indicator in the table when there are new documents associated with that case

<img width="1086" alt="screenshot 2018-06-14 15 27 58" src="https://user-images.githubusercontent.com/1598889/41433699-b4a6d9e8-6fe7-11e8-8de9-365d8b842137.png">

---

The team talked about taking out the document count within the table view, so next I'll work on an iteration showing:
- [ ] A link to all Veteran documents (without document number)
- [ ] That the case has a new documented

**Comment by mdbenjam** [comment]
@mkhandekar  I was talking with @laurjpeterson about doing this one in the next sprint. Is this design finalized? Also was telling LP that if we are interested, it should also be easy to show the number of new documents.

**Comment by mkhandekar** [comment]
I love that showing the number in the tabs is do-able, but for now, let's keep it simple and just have a new icon. @mdbenjam would it also be possible to know what kind of document has been uploaded? 

## Display new document icon in the table

<img width="388" alt="screenshot 2018-07-09 16 37 37" src="https://user-images.githubusercontent.com/1598889/42481477-7216a3a6-8397-11e8-97fb-4e3e5dcc7a4e.png">

## Display new document icon in case details title area

<img width="767" alt="screenshot 2018-07-09 16 38 27" src="https://user-images.githubusercontent.com/1598889/42481478-7230572e-8397-11e8-9792-04b4f691fde8.png">

--- 

**Alt text:** "View docs. New icon" (I want to treat the icon and "new" text as one component, so screenreaders can simply say "New icon" so attaching an SVG shortly).

**SVG:** to be added

**Comment by mdbenjam** [comment]
We know what kind of document is uploaded. The icon will go away once someone visits Reader regardless of how they get there.

**Comment by mdbenjam** [comment]
So the co-located flows aren't built yet, so I'll hold off on implementing the icon in the tabs. But I'll add it to the main table, and the case detail screen.

**Comment by mkhandekar** [comment]
@mdbenjam hey Mark, as per my previous comment's **out of scope** section, yes, hold off on the icon in the tab until we decide it's worth it.

**Comment by mdbenjam** [comment]
@mkhandekar I'm thinking about implementation and I see two main options, which would you prefer
1) When a user gets to the page, the new icons are there immediately, we put them in place based on a check of our local Caseflow documents DB. However, this might be up to 24 hours out of date.
2) When a user gets to the page, the new icons act like the current document counts where it appears after we've had an opportunity to make a web request (might take a few seconds).

Do you have any preference between the two?

**Comment by mkhandekar** [comment]
@mdbenjam I'd go with the more accurate and up to date option - # 2!  Thank you for thinking through this <3
