### ISSUE TITLE
All users | Change title of # documents column

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5599]
Rename the attorney column from 'Reader documents' to 'Veteran documents' for consistency.

## AC
- Attorney queue and judge queue columns are titled 'Veteran documents'

**Comment by mkhandekar** [comment]
- documents
- documents in Reader

we use _documents_ in Case details too.

**Comment by mkhandekar** [comment]
We changed it to **Veteran Documents** for now.
