### ISSUE TITLE
Add days waiting to Attorney queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5600]
We are moving away from due dates for attorneys. Their performance standard is based on number of duty days until submitting the draft decision. To ease the switch from due dates to days waiting, I propose we include a calendar days waiting counter in the attorney queue before removing the due date field.

**Priority:** I think we should deploy this before all judges are assigning cases to attorneys, so attorneys have time to adjust to the days waiting concept.

## AC
- Rename 'Due date' column to 'Total days waiting'
- Add tool tip or another interaction to define 'Total days waiting' as 'Calendar days this case has been assigned to you'
- Show total days waiting, and due date per mocks

## Out of Scope
- Sorting by days waiting - this will be covered here: https://github.com/department-of-veterans-affairs/caseflow/issues/5781

## Mock
![attorney_table_in-progress](https://user-images.githubusercontent.com/31224257/41562160-cd52f10e-7319-11e8-95d7-94645a682040.png)

## Questions
- What do we think about our definition mentioning information about no longer setting due dates to help with this change? We could brainstorm the right copy.

**Comment by sneha-pai** [comment]
This counter should be live when judges begin assigning to attorneys

**Comment by sneha-pai** [comment]
how do you want to show the count of days (next to due date)?
