### ISSUE TITLE
Refactor queue_spec to use FACOLS and break it up up into separate specs 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5603]
`queue_spec` is almost at 1000 lines. We should refactor it to use FACOLS. We should also break it up into different spec files for a few reasons:

- attorney checkout / case search aren't really parts of queue functionality
- prevent test setup from colliding
- we'll be adding lots more users / specs and don't want to keep piling on this file

We should consider breaking it out into potentially five specs:
- case_search_spec
- attorney_queue_spec
- attorney_checkout_spec
- judge_queue_spec
- judge_checkout_spec

**Comment by lomky** [comment]
Timebox to 2.
We're assuming this should be largely copy and paste, with some setup clean up.
