### ISSUE TITLE
Allow multiple RAMP opt-ins

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5607]
We need to allow multiple RAMP opt ins for a single veteran.

## Acceptance Criteria
- Users should now be allowed to start a RAMP Election intake for a veteran that already has a RAMP Election.
- When completing a RAMP Election where the veteran already has a RAMP Election:
  - If all prior RAMP Elections are cleared or canceled, create the EP as it would normally be created.
  - If the RAMP election EP is active and has a different EP code, create the EP as it would normally be created.
  - If the RAMP election EP is active and has same EP code, then we THINK the answer is to connect the new EP with the old EP, but are not yet sure. Waiting to hear back from AMO. For now, throw an error?
  
## Technical notes
This requires us to rethink what it means to be a duplicate. Since the way we were checking for a duplicate RAMP involved looking for an existing RAMP election.

It also forces us to rethink how refilings will work, since they can now pull in issues from many different Elections.

It also may force us to rethink some of our stats stuff since they may assume that veterans have a single RAMP election.

**Comment by abbyraskinUSDS** [comment]
Note: we told AMO we'd finish this by 06/01

**Comment by shanear** [comment]
@abbyraskinUSDS do we remember what we said we would do if there was already a RAMP election EP? meaning we can't create a new one.

**Comment by shanear** [comment]
@abbyraskinUSDS we've had a bunch of RAMP issues that have taken precedence over this. I think we're going to have to push this back a week

**Comment by kahlouie** [comment]
@shanear doc containing design consequences: https://github.com/department-of-veterans-affairs/caseflow/issues/5776
