### ISSUE TITLE
No way to return to the start / certification or a "home page" from Help, What's New pages.

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#561]
Noticed today that there's no real way for users to leave the Help or What's New pages other than by click the _Back_ button. Should we link to a start page here? Should the Help and What's New? pages actually be modals or new windows instead? This seems like an issue that will pop up at some point.

cc @maryannbrody

**Comment by KHarshawat** [comment]
@webinista I accidentally created a dupe but we should open the help page and the what's new page in a new window when the user clicks on it:

https://github.com/department-of-veterans-affairs/caseflow/issues/595
