### ISSUE TITLE
Judge check out to dispatch backend

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5611]
After judges sign appeals decisions or OMO requests, they send the case to other teams at the Board - BVA dispatch and OMO office respectively. 

- Allow judges to assign the case to BVA dispatch - VACOLS location 30
   - Validate by there being issue dispositions
- Allow judges to assign the case to OMO office - VACOLS location 20
   - Validate by checking that the work product is OMO (overtime or not)?
- Allow judges to evaluate the attorney's decision
   - Update VACOLS final complexity field (easy, medium, hard) - `DEFDIFF `
   - Enter attorney quality of case and update VACOLS overall quality - `DEOQ`
   - Enter factors not considered and update VACOLS - `DEQR1-DEQR6`
   - Enter areas for improvement and update VACOLS - `DEQR7-DEQR11`

```
These values have "Y" when set, otherwise it contains NULL -  Correct (null or ‘N’ when not checked)

Theory Contention – DEQR2
Caselaw – DEQR3
Statue regulation – DEQR4
Administrative procedure – DEQR5
Relevant records – DEQR6
Lay evidence – DEQR7
Did not properly identify .. – DEQR1
Findings are not supported .. - DEQR8
Did not adequately address .. - DEQR9
Remands not complete .. - DEQR10
Major or frequent spelling .. - DEQR11

```
   - Enter notes and update VACOLS field `Factors Affecting Complexity / Quality`- `DEBMCOM`
   - Update `demdusr` and `demdtim`

## Resources
- Front end designs: https://github.com/department-of-veterans-affairs/caseflow/issues/5151

**VACOLS**
<img width="469" alt="screen shot 2018-05-18 at 2 07 06 pm" src="https://user-images.githubusercontent.com/27704093/40250617-ccceaeb8-5aa4-11e8-803e-b73ca02f4558.png">

**Comment by amprokop** [comment]
> Allow judges to assign the case to BVA dispatch - VACOLS location 30
Validate by there being issue dispositions
Allow judges to assign the case to OMO office - VACOLS location 20
Validate by checking that the work product is OMO (overtime or not)?

**Comment by amprokop** [comment]
Some more questions:

- Should judges be able to edit the document id in Caseflow? 

> Enter notes and update VACOLS
- What VACOLS freetext field should this map to?

**Comment by laurjpeterson** [comment]
> Can judges choose where a case goes next? If an attorney creates an OMO request wouldn't we know that the case should go to location ~30~ **20**, for example? Are there other scenarios here that we don't know about?
- Yes. Today, judges do choose where the case goes to next. 
- I'm not sure I know what your second sentence is referring to. Yes, we'd know that the judge would be assigning the case to location 20 after reviewing the attorney's OMO request. But the judge is required to sign the OMO request before it goes to OMO, so it cannot go straight from attorney to OMO.
- Judges assign OMO requests to OMO, and signed decisions to BVA dispatch.
- Other scenario could be assigning the case back to the attorney for a rewrite. We will have this functionality with the judge release 2, assigning to attorneys.

> Should judges be able to edit the document id in Caseflow?
- We don't currently allow judges to do this in our flow and I think that is ok because the document ID should not change from attorney to judge. Are you asking if we should add it in or do you see it in the mocks somewhere?

> What VACOLS freetext field should this map to?
- `Factors affecting complexity / quality`

**Comment by amprokop** [comment]
> Should judges be able to edit the document id in Caseflow?

`We don't currently allow judges to do this in our flow and I think that is ok because the document ID should not change from attorney to judge. Are you asking if we should add it in or do you see it in the mocks somewhere?

`

Nah, I was just wondering — when a judge finalizes a decision, that judge then edits the existing document rather than creating a new one?
