### ISSUE TITLE
Mini Tech-Spec for RO and Judge Assignments

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5618]
Fill in RO and Judge Assignment sections of this doc: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Hearings/Hearing%20Schedule/Tech%20Specs/HearingSchedule.md

**Comment by MeredithStewart** [comment]
Teja and Meredith talked through aspects of RO and Judge assignments. Points that were made: 1) Don't build anything that Scott and Justin are doing manually 2) We want to purposively make the assignment as simple as possible, not building for the edge cases. 3) Further refinement to the assignment would be managed either through adding availability days or through more manual editing by Scott and Justin after the schedule was created.  

5/24 - Teja and Meredith met with Justin and talked through several pieces of Judge assignments. 

5/31/18 - Teja and Meredith met with Scott and got some more info on assignments.

**Comment by MeredithStewart** [comment]
Followup -  @tejans24 will send Scott the outline of the assignment algorithms on 5/31 for him to provide feedback by 6/1.

**Comment by MeredithStewart** [comment]
@tejans24 sent Scott email 5/31. Meredith will followup 6/1 to see if Scott had any feedback to that specifically.
