### ISSUE TITLE
Hearing Prep | Add instructions for accessing Hearing Prep in demo

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#5621]
We have a number of new folks coming on to the team soon, and it would be helpful to have instructions for accessing Hearing Prep in Demo on the Environments page.

**Comment by annienguyenUSDS** [comment]
@lakohl if you need help with this, let me know.

**Comment by lakohl** [comment]
thanks @annienguyenUSDS. We are now using the new demo environments, so I pinged @sharonwarner and @Sjones352 on 7/13 with the following:
cc: @tejans24 

HEARING PREP demo issues
- Ironically, the VA demo environment only works on Safari. When I try to access HP I get a message that Safari is not supported. :upside_down_face: ( This should not be fixed but it’s a limitation of that demo env.)

- On the Caseflowdemo.com environment  it’s possible to access the Upcoming Hearing Days page, but no Upcoming Hearing dates are clickable. Could we add some clickable docket dates to the upcoming tab?
- The Reader view shows a case with only Case Summary documents, so ‘Clearing all filters’ does not result in a longer list of documents. Could we add more docs to the case file that do not have the Case Summary tag?

**Comment by lakohl** [comment]
@sharonwarner 
I just checked Hearing Prep UAT and there no upcoming hearing days listed. We should probably add some when you have a chance.

**Comment by lakohl** [comment]
This is covered by this ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/6441
