### ISSUE TITLE
RAMP opt-in election | Copy change: update document upload instructions with new document type

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5622]
There's now a VBMS document label for opt-in elections. CAs no longer need to use the "correspondence" document type. We should update body copy on the "Finish" page for opt-in elections to read:

**Step 1.** Upload the RAMP Election form to the VBMS eFolder and ensure the Document Type is **RAMP Opt-In Election.**  
**Step 2.** Update the Subject Line with **RAMP Election.**

## Mocks
![image](https://user-images.githubusercontent.com/4042181/40310665-88e5bd5c-5cdb-11e8-83d5-5e28e3eb11ff.png)

## Related story
https://github.com/department-of-veterans-affairs/caseflow/issues/5624

**Comment by kahlouie** [comment]
Decided to standardize on non-bolded periods. :)

**Comment by leahbannon** [comment]
looks good -- also +100 to non-bolded periods unless the entire sentence is in bold :)
