### ISSUE TITLE
AMA intake | Copy/component changes on "finish" page (NODs)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5623]
This is a ticket to make copy and UI changes to the "finish" step for appeals.

## Acceptance Criteria
- Remove the rated/non-rated tab
- Add page header:
  - Identify issues on Joe Snuffy's Notice of Disagreement (VA Form 10182)
- Add page body:
  - Please select all the issues that best match the Veteran's request on the form. The list below includes issues claimed by the Veteran in the last year. If you are unable to find one or more issues, enter these in the "other issues" section.
- Add table header:
  - Select from previous decision issues

![image](https://user-images.githubusercontent.com/4042181/40313766-827cd65e-5ce4-11e8-8919-d68d63c766ec.png)

## Related
#5501

**Comment by abbyraskinUSDS** [comment]
Would it make sense to do this for the VBA lanes now too?

**Comment by leikkisa** [comment]
@abbyraskinUSDS Is this only for appeals, or also for HLR and SC?

**Comment by abbyraskinUSDS** [comment]
@leikkisa that's right, thank you!

**Comment by leikkisa** [comment]
@abbyraskinUSDS Can I get a larger version of the mock up please? Thanks!

**Comment by leahbannon** [comment]
looks good!
