### ISSUE TITLE
RAMP re-filing | Copy change: update document upload instructions with new document type

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5624]
There's now a VBMS document label for opt-in elections. CAs no longer need to use the "correspondence" document type. We should update body copy on the "Finish" page for re-filings to read:

**1a.** Upload the RAMP Selection Form to the VBMS eFolder and ensure the Document Type is **RAMP Opt-In Election.**
**1b.** Update the Subject Line with **RAMP Selection.** 

## Mocks
![image](https://user-images.githubusercontent.com/4042181/40310917-4b9f994e-5cdc-11e8-9542-f787319afbdc.png)

## Related story
https://github.com/department-of-veterans-affairs/caseflow/issues/5622

**Comment by leahbannon** [comment]
This is currently showing up with quotation marks instead of bold, but it looks fine to me.
