### ISSUE TITLE
Create method to load Appeal or LegacyAppeal based on id

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5626]
There are a lot of code paths where we our frontend passes us an appeal_id or a vacols_id and we need to retrieve the appeal record. For example, Reader has a URL that references vacols_ids and Queue has at least one URL that references the old appeal_id. To make these products work transparently with both types of appeals we'll need a way to determine which type of appeal to instantiate when we see a URL.

- `Appeal.find_appeal_or_legacy_appeal_by_id`

The first method will determine if the appeal id is for a new or legacy appeal and will return the corresponding appeal. The second method will determine if the id is for a new appeal or is a vacols id used to reference an old appeal.

# Acceptance Criteria
- Each AMA appeal should be created with a 20 char UUID.
- The above two methods return either an appeal or legacy appeal based on which id is passed.

**Comment by kahlouie** [comment]
@mdbenjam I've updated the issue with @shanear due to the fact that appeal doesn't have a uuid yet and legacy appeal ids are the same thing as vacols ids. Feel free to send anymore questions here of via slack.

**Comment by shanear** [comment]
Im gonna go ahead and validate this
