### ISSUE TITLE
Get Reader and Queue working with AMA appeals

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5627]
For July 1 we want basic Reader and Queue functionality to work for AMA appeals as defined in this [tech spec](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/queue/AMA_Appeals.md).

Basic Reader functionality is defined as:
1) Users are able to use Queue navigational links to open cases in Reader.
1) Users are able to use an appeal id to open a case directly in Reader via the URL: `/reader/appeal/appeal_id`.
1) Case details within Reader does not need to have all of an appeals information.

Basic Queue functionality is defined as:
1) Users in the pilot are able to go to `/queue/amapilot` and see all of the appeals in the pilot.
1) Users should be able to click on any of those appeals and go to the Case details page. 
1) This page does not need to have all of the appeal's information, but should have as much as we can show:
    - whether the Veteran is AOD or not
    - Power of Attorney
    - Regional Office
    - Issues (no dispositions)
    - Docket type
        - Hearing, Evidence Submission, Direct Docket
    - Docket number
    - Veteran name, address, pronoun
    - Appellant name, address, pronoun (if applicable

**At this time, RAMP appeals are excluded from this view**

**Comment by shanear** [comment]
Yeah we need to figure out how we will get a users regional office. I think its in BGS?

**Comment by mdbenjam** [comment]
Yeah I'm pretty sure it's in your rating response. Check out: `jrnLctnId` I think that's it. (3 digit number that starts with 3 :))
