### ISSUE TITLE
URL for editing Higher Level Review and Supplemental Claim issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5628]
We need a URL pattern for allowing any downstream case workers to edit issues. This pattern should either take the claim id of the Higer

## Acceptance criteria
- When the URL pattern for a review is visited, show a mostly blank page with the name of the veteran.

## Technical notes
- Don't worry if the review is cleared, we will handle that in a future story
- Don't worry about the link for appeals, we will handle that in a future story

**Comment by leikkisa** [comment]
@shanear 
I'm guessing the description above is meant to say "This pattern should either take the claim id of the Higher Level Review or Supplemental Claim", and not "either the claim_id or [another non-claim_id option].  Also, figuring the claim_id is the same as the end_product_reference_id.

**Comment by leahbannon** [comment]
Plan is for Sally  to figure out where it will be placed and how much we can influence the visual design (and interaction related to new tab, etc.) and keep Abby in the loop.

**Comment by abbyraskinUSDS** [comment]
@leikkisa @suzchap we're thinking the label should read "Edit in Caseflow", and the placement would be next to the "Add Contentions" button. It would be reeeally cool if we could add a Caseflow logo to the button, but let us know how much influence we have there.

**Comment by leikkisa** [comment]
@abbyraskinUSDS It's looking like we'll get all of the above! We'll get a screenshot for you when it's ready

**Comment by suzchap** [comment]
@leikkisa Is this done yet and will I be able to validate this based on the screenshot or do I need to see it live?

**Comment by leikkisa** [comment]
@suzchap 
I think for the VBMS side of things, since I can't get that, the screenshot that we sent should be good. For our side of things, you should be able to go to the URL:
/higher_level_reviews/600133239
Now that you made an end_product_reference_id for that (the same as claim_id)

**Comment by suzchap** [comment]
@leikkisa hmmm, that URL didn't work for me so we might have to look at this one together.

**Comment by leikkisa** [comment]
@suzchap I think I forgot to indicate "edit" on the URL.  Assuming this is the correct UAT URL, the link should be this:
https://appeals.cf.uat.ds.va.gov/higher_level_reviews/600133239/edit

**Comment by suzchap** [comment]
This is what I see... It does show Veteran name and ID so is this correct?

![Screen Shot 2018-07-26 at 1.04.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57758753a582050e0017b00d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f56b7191a379f1122f4f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e74f51a3123762e1772431.png)

**Comment by leikkisa** [comment]
Yes, this is it! It's just a placeholder for now.
