### ISSUE TITLE
Create appellant model & table

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#5632]
After [this discussion](https://github.com/department-of-veterans-affairs/caseflow/issues/5536) we decided that we want a many to many relationship between appeals and appellants. We need to create an appellant table with the following fields.

```
1) id
2) participant_id
```

The participant_id comes from BGS and allows us to make queries to determine appellant information.

The model should implement the following methods:

```
appellant_name,
appellant_address_line_1,
appellant_address_line_2,
appellant_city,
appellant_state,
appellant_zip,
appellant_country,
appellant_relationship
```

This information should all be available in BGS.

Finally, once we have this model we can update the newly created `WorkQueue::AppealSerializer` to use these appellant methods.

# AC
- [ ] There should be a new appellant table.
- [ ] There should be a new appellant model with the methods described above.
- [ ] The `WorkQueue::AppealSerializer` should call the new appellant model methods.

**Comment by lowellrex** [comment]
Future me: don't forget about this puppy: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/associated_bgs_record.rb
