### ISSUE TITLE
Design patterns: explore navigation patterns within & between Caseflow features

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#5634]
Sneha and I are meeting this week to work through...

- [ ] Getting to a Veteran's other cases from case details (based on conversation about removing breadcrumbs - [see mural](https://app.mural.co/invitation/mural/workqueue2001/1525184340185?sender=meghana7585&key=e60c0b98-8f4b-4e00-bbe9-528a92465dd2))
- [ ] Getting to Reader (and scheduling?)
- [ ] Getting to other caseflow products (as defined by who you are and what you can access)
- [ ] What is the nesting schema? What stays on the same hierarchy?

**Comment by mkhandekar** [comment]
A couple of starting points in navigation:

![1525794142620](https://user-images.githubusercontent.com/1598889/40328738-6c32fdca-5d15-11e8-90c7-1fb404399406.jpg)

more in this [mural](https://app.mural.co/invitation/mural/workqueue2001/1525184340185?sender=meghana7585&key=e60c0b98-8f4b-4e00-bbe9-528a92465dd2).

**Comment by mkhandekar** [comment]
Part of this is: **Judges | Navigation to Hearing Prep from Queue #5582**

**Comment by laurjpeterson** [comment]
Closing this issue because the work on navigation is being tracked here: https://github.com/department-of-veterans-affairs/caseflow/issues/7503
