### ISSUE TITLE
Users can't access Case Search

### ISSUE THREAD

**Issue by evankroske** [department-of-veterans-affairs/caseflow#5636]
Caseflow should redirect only attorneys and judges from / to /queue, but due to the following code, Caseflow considers everyone to be either an attorney or a judge:

```ruby
    def vacols_role(css_id)
      staff_record = staff_record_by_css_id(css_id)
      case staff_record.svlj
      when "J"
        "Judge"
      when "A"
        staff_record.sattyid ? "Attorney" : "Judge"
      when nil
        "Attorney" if staff_record.sattyid
      end
    end
```

https://github.com/department-of-veterans-affairs/caseflow/blob/b41135366a80b2d84dc474d5eb133e4af5a512b4/app/repositories/user_repository.rb#L13

This keeps anybody from accessing Case Search.

**Comment by lowellrex** [comment]
@evankroske is this a different issue than [folks without VACOLS records](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1449/) attempt to access caseflow triggering `Caseflow::Error::IssueRepositoryError`s? If that is the same issue as this, does adding the following rescue block to the end of the function look like a good quick fix to your eyes?

```ruby
def can_access_queue?
  role = current_user.vacols_role
  return true if role == "Attorney"
  return true if role == "Judge" && feature_enabled?(:judge_queue)
  false
rescue Caseflow::Error::UserRepositoryError
  false
end
```

**Comment by amprokop** [comment]
> but due to the following code, Caseflow considers everyone to be either an attorney or a judge:

@evankroske —I'm curious about this. From my reading it looks like the `vacols_role` method will return `nil` if `staff.svlj` is nil and `staff.sattyid` is nil — so we should be able to distinguish attorney/judge users from non-attorney/judge users. What do you think?

**Comment by evankroske** [comment]
@lowellrex , no, I don't think this is the same issue as the UserRepositoryError.

@amprokop , you're right, I forgot to read the last half of the last line of the last case to see the trailing "if" statement. This method is correct.

**Comment by amprokop** [comment]
See https://github.com/department-of-veterans-affairs/caseflow/issues/5670 for related thoughts
