### ISSUE TITLE
Investigate flurry of "File Number does not exist within the system" errors

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5638]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1359/

It looks like 8-10 appeals currently result in this error. These errors may be beyond our control (if e.g. bfcorlid doesn't contain the VBMS-searchable file number). Consider handling this error so it's not reported to Sentry if so.

**Comment by aroltsch** [comment]
This has been done.
