### ISSUE TITLE
Dropdown menu opening broken

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#564]
To reproduce:

1. Open a page
2. Click on your name to open dropdown
3. Click _away_ on the page (not on your name)
4. Try to open dropdown again
5. It doesn't work

**Comment by webinista** [comment]
Eventually it closes. Off to diagnose.

**Comment by alex** [comment]
This seems like maybe it got fixed? Or have I gone crazy.

**Comment by webinista** [comment]
No. It's fixed-ish. I think the earlier bug was actually a really long delay. Now the delay is shorter, so it works. Still way too slow IMO.
