### ISSUE TITLE
[Frontend] Hearing Worksheet | Summary Design Updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5643]
Design updates from #3862 

1) Hearing Summary text should be the same size as Veteran/Appellant Information.
1) No need to leave so much room above the Hearing Summary header, the space above it could be reduced by half.
1) Can you make the top of the rectangle enclosing the formatting tools the same color as the side and bottom of the box?
1) Would you be able to darken the border around each of the editing tool boxes? I don't think they will pass a 508 check.

**Comment by MeredithStewart** [comment]
Closing. Pending another 508 review post updates to Hearing Prep in November 2018, new 508 recommendations will come in to be worked.
