### ISSUE TITLE
Stats page in Caseflow should only be available to users with role "System Admin"

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#565]
Currently, anyone can access it. No bueno!

Acceptance criteria:
-User without "System Admin" role should see the unauthorized page when attempting to access Caseflow stats (the `/stats` route)
-User with "System Admin" role should be able to see Caseflow statistics on the `/stats` route

**Comment by kierachell** [comment]
Is there a User with the admin role available for validating Stats page?

**Comment by astewarttistatech** [comment]
@nemodjuric Can the System Admin role be accessed on the Dev side?

**Comment by kierachell** [comment]
As per #608:
new "System Admin" user is the only one able to access the ```/stats``` route; So, working as intended.
Not sure if requires UAT testing.
<img width="1212" alt="screen shot 2016-12-28 at 17 40 19" src="https://cloud.githubusercontent.com/assets/18075411/21533187/0597a096-cd26-11e6-8b29-5fd404d6a2cb.png">

**Comment by kierachell** [comment]
@shanear said he will be able to look into this.

**Comment by kierachell** [comment]
`demo` uses sqlite, which does not support `INTERVAL` - so it's breaking the page.
Related issue [#313 from at deployment](https://github.com/department-of-veterans-affairs/appeals-deployment/issues/313)

**Comment by shanear** [comment]
<img width="1512" alt="screen shot 2016-12-30 at 5 53 57 pm" src="https://cloud.githubusercontent.com/assets/1596259/21573962/f4cda744-ceb8-11e6-8a42-014f16de4134.png">

Validated on UAT
