### ISSUE TITLE
FACOLS Integrations | Hearing prep tests should run on FACOLS

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5676]
We want to avoid having any hearing scheduling code run off of the fake repositories. Because the hearing scheduling code relies on already-existing models, we need to update those models' unit tests to run off of FACOLS. 

AC:
The following tests run off of FACOLS:
- spec/controllers/hearings/worksheets_controller_spec.rb,
- spec/controllers/hearings_controller_spec.rb,
- spec/feature/hearings_spec.rb,
- spec/models/hearing_spec.rb,
- spec/repositories/hearing_repository_spec.rb,
- spec/models/judge_spec.rb

**Comment by mdbenjam** [comment]
Suggestion, can we update this ticket to fix the tests in all these hearing related files?

```
spec/controllers/hearings/worksheets_controller_spec.rb,
spec/controllers/hearings_controller_spec.rb,
spec/feature/hearings_spec.rb,
spec/models/hearing_spec.rb,
spec/repositories/hearing_repository_spec.rb,
```

**Comment by sharonwarner** [comment]
@mdbenjam yeah, absolutely! i just updated the ticket.
