### ISSUE TITLE
Explore certification checklists across different ROs

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#569]
Not for immediate action, but -- 

We've heard from user research that most DROs use a checklist before certifying a case. We've seen some of them and they are not all the same. It would be good to do some research and take a look across all of the different checklists to explore similarities and differences, and also to see what can be re-created using software. 

Assigning to myself, but tagging @KHarshawat and @gmorgana-va as FYI.

**Comment by gmorgana-va** [comment]
Thanks, @maryannbrody.  Discussed with @KHarshawat.  Tracking with new information here: https://github.com/department-of-veterans-affairs/appeals-pm/issues/135
