### ISSUE TITLE
AMA intake | Claimant is not veteran and veteran has no relationships

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5695]
Right now, if the veteran has no relationships, and the claimant is not the veteran, we show this:

<img width="1139" alt="screen shot 2018-10-03 at 1 12 10 pm" src="https://user-images.githubusercontent.com/1596259/46427053-48d22000-c70e-11e8-9d06-8ed31348b350.png">

We prompt the user for a payee code, but don't allow them to select the claimant. We need to update this to properly handle the situation.

## Acceptance Criteria:
- When intaking any decision review, and "Is the claimant someone other than the Veteran?" is set, and the veteran has no dependents (`veteran.relationships`) in CorpDB/BGS:
  - Don't show the payee code prompt
  - Disable the "Next" button
  - Show the error message below the radio button according to the comps, "There are no Claimants in our records. You can add the claimant in VBMS and refresh this page."

## Copy
There are no Claimants in our records. You can add the claimant in VBMS and refresh this page.

## Mocks
![REVIEW: no relationship alert.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b91284c50ee5a0014e9de9d/125516c66e82c728ace21e0d46dab1ac0aa7b4f3cfe7b003b658fc953d4f287d3a0caa3b3084ef2dad56394d4d1f0cf31b0d0c00eef39b2eaeb46d72dc5902efd86d0970c66c16acb8d01dba01b972995397f4edd4189fb5646fb2c99d452c1f0d1288fa5934a89848c95ff64ae84f47e9.png)

## Related
#5569 (Adds "other claimant" question)

**Comment by abbyraskinUSDS** [comment]
- Sally is holding off on developing any validations for now
- Assigning to Leah to figure out how AMO wants CAs to handle this scenario

**Comment by leikkisa** [comment]
Potential plan:
If there are no relationships, keep the "yes/no" radio button, and if they select "yes", show a message that no relationships have been found and that they need to add them and refresh (very similar to current message).
If they select "yes", the "continue" button is greyed out until a relationship is selected

**Comment by shanear** [comment]
@carolaponce need thoughts or designs on what alert should happen on this screen when the veteran has no relationships recorded

**Comment by carolaponce** [comment]
Introducing a style from style-guide I don't think we are using, but I see applicable in this case.
I don't want to use red text because it is not an error - It is an alert.

Proposed text: 
There are no Claimants in our records. 
You can add the claimant in VBMS and refresh this page.

**Comment by carolaponce** [comment]
![review no relationship alert](https://user-images.githubusercontent.com/11700545/48172400-982ee180-e2b4-11e8-9884-6ea3825ddedf.png)

**Comment by leikkisa** [comment]
@carolaponce I'd like to propose the copy say something more like "The Veteran has no relationships in our records." etc., since they are not yet claimants and they won't all be claimants.

**Comment by steve-gov** [comment]
Validated:

<img width="962" alt="screen shot 2019-01-07 at 3 45 14 pm" src="https://user-images.githubusercontent.com/25468689/50792526-46461000-1293-11e9-8c2a-71e391653335.png">
