### ISSUE TITLE
New wording and logic for form 8 -- question 8.

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#570]
Hey, @webinista, 

We have a small change on question 8 on Form 8 in Caseflow. Can we please change the whole question to the following logic.... 

Let @KHarshawat know if you'd prefer to see a quick mockup of this. Thanks!!

8A* Representative Name: 
_Text Field_
	
* Represetnative Type:
- Attorney
- Organization
- Agent
- Other

Specify Other
*_Text field_

8B.  
What is the authority for recognizing such representative in this appeal?* *_Radio Buttons_
- POA
- Certification that valid POA is in another VA file [SPECIFY FILE] 

If 8A = "Agent"; Show 8C
Is Agent on accredited list?*
<Radio Buttons>
- Yes
- No 

If 8A = "Organization"; Show 9a
Is VA Form 646, or equivalent, of record?*
<Radio Buttons>
- Yes 
- No

If 9a = "No"; Show 9b
Why is the Form 646 not of record?*
<Text Field>

**Comment by shanear** [comment]
@maryannbrody do we still want to hide 8B if Agent is selected?

**Comment by KHarshawat** [comment]
@shanear I believe 8B (POA) is relevant to all types in 8A so we should always show 8B.
