### ISSUE TITLE
Discussion | Determine the URLs for each page

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5706]
We need to decide what URLs to use for the following pages:

1) Homepage for hearing coordinators' scheduling functionality
1) Homepage for hearing prep (currently using /hearings/dockets)

**Comment by sharonwarner** [comment]
I think it makes sense to keep hearing prep as '/hearings/dockets' and use '/hearings/scheduling' for hearings scheduling.

**Comment by MeredithStewart** [comment]
hearings/scheduling and hearings/schedule -- might look too close if we end up need another user view URL path.  Ok, maybe that's all I had to say on the subject!

**Comment by MeredithStewart** [comment]
Other people that may need views with different roles for the schedule information:
- Board hearing coordinators (are they going to slot Veterans and make changes? Still TBD) 
- RO hearing coordinators to manage day-of hearing logistics (view only)

**Comment by sharonwarner** [comment]
After thinking about this more in the context of user permissions, maybe it would make sense for the url to be /hearings/scheduling/admin
