### ISSUE TITLE
Figure out why cases are missing

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5708]
The Boise RO says they're missing 4 appeals.

**Comment by sharonwarner** [comment]
I looked into 4 appeals. Two of the appeals didn't have any allowed issues, so we correctly didn't create tasks. For the other two appeals, we created tasks, they were processed through dispatch, and marked as 'assigned existing ep'.

**Comment by lakohl** [comment]
Thanks for taking the time to look in to these @sharonwarner
