### ISSUE TITLE
Should the "ready" box under "hearings" be automatically checked upon certification??

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#571]
@gmorgana-va and @KHarshawat  -- can you guys double check this with the board???

Finding -- 

Participants said they do not select the box “ready” under “hearings” until
they are absolutely sure the case is ready to be certified (since the hearing
board may pull a list of cases for hearings at any time). If the hearing
board pulls a case that is not actually certified, they would not be able to
hold the hearing. 

Possible Solution

-- Double check this use case with the Board. Should the “ready” box
automatically populate if a hearing was requested once the case is
certified?

**Comment by labecker** [comment]
Would recommend to loop in Jed on this. I question whether there is really a need to have this ready box. Once a hearing is requested - from Board perspective the RO can schedule right away if in docket order.

**Comment by gmorgana-va** [comment]
Requested feedback from Jed.  (https://github.com/department-of-veterans-affairs/appeals-pm/issues/112)
