### ISSUE TITLE
Case details | Issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5735]
Viewing issues on an appeal is the highest priority for many Board users, including attorneys and judges. When attorneys and judges click to view details about a case, they want to see issues front and center, so they can get immediate context on the case. 

## AC
- Incorporate new issues designs
- If issues have a disposition already in VACOLS, show that disposition under the Note field, following the design styling
- If issues do not have a disposition, do not show the disposition row

## Mocks
![image](https://user-images.githubusercontent.com/1598889/41435760-d7dd9d92-6fed-11e8-8ca7-4e4e287291b7.png)

## Resource:
- [Case details Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1525112874684/5765d285f568b5f631990e2c8e514a39d9b6b570)

**Comment by laurjpeterson** [comment]
@lowellrex @mkhandekar looks like issues redesign is deployed, so closing. Will cover editing in future issues.

**Comment by lowellrex** [comment]
@laurjpeterson I'm pretty sure this work has been completed. Can you confirm so I can go ahead and close this ticket out?
