### ISSUE TITLE
Case details | Add periods and circumstances of service

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5740]
When Board users view information about a Veteran, they want to see the Veteran's periods and circumstances of service from VBMS (because it is more accurate than VACOLS), so they can get context about the Veteran. 

This issue also contains some UI enhancements that are accounted for in the mocks.

## AC
- Add medal icon to Veteran details, next to the existing Veteran name, address, etc. info covered in this issue (https://github.com/department-of-veterans-affairs/caseflow/issues/5738)
- Verify that we are displaying periods and circumstances of service from VBMS

## Mocks
Note: this mock contains VACOLS data. We should create another mock with VBMS data @sneha-pai 

![image](https://user-images.githubusercontent.com/1598889/41832262-44eda3b8-7819-11e8-86ea-a7ab3eeb1697.png)

The mocks do not currently include detailed _periods and circumstances of service_ data.

## Resources
- [Case details Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1525112874684/5765d285f568b5f631990e2c8e514a39d9b6b570)
- Hearing Prep periods and circumstances of service
![screen shot 2018-05-31 at 12 36 55 pm](https://user-images.githubusercontent.com/27704093/40795240-697d028a-64cf-11e8-9471-1905735802d9.png)
- #### VBMS screenshots depicting periods of service and circumstances:

![military service vbms 1](https://user-images.githubusercontent.com/31224257/51134497-c3c6ce80-1805-11e9-9777-624d16ad97fe.PNG)

![military service vbms 2 1](https://user-images.githubusercontent.com/31224257/51134638-26b86580-1806-11e9-940e-04a0405da6bc.PNG)

![military service vbms 3 1](https://user-images.githubusercontent.com/31224257/51134639-26b86580-1806-11e9-9214-202c1c8f0960.PNG)

- Issues related to pulling this info from VBMS for hearing prep - connect with @sharonwarner with any questions
   - https://github.com/department-of-veterans-affairs/caseflow/issues/2469
   - https://github.com/department-of-veterans-affairs/caseflow/issues/2895
   - https://github.com/department-of-veterans-affairs/caseflow/issues/2857

**Comment by mkhandekar** [comment]
@laurjpeterson Maybe I missed this... but, I did not see "periods and circumstances of service" in the VACOLS UI. I'm happy to incorporate this in, but want to make sure it is required.

@lowellrex Does the Hearing Prep data structure require us to display service history in any particular way in case details? For example, can we adjust how we display: 
  - branch of service
  - dates served
  - discharge notes?

**Comment by laurjpeterson** [comment]
@mkhandekar - correct! periods and circumstances comes from VBMS. what VACOLS does have is Periods of Service on the Vet Info Tab. Instead of relying on VACOLS for this information, we'd like to rely on VBMS because it is more accurate and because Hearing Prep already accesses it. It will increase accuracy and consistency among our Caseflow apps. 

<img width="218" alt="screen shot 2018-06-25 at 9 17 32 am" src="https://user-images.githubusercontent.com/27704093/41852277-a3c962de-7858-11e8-8675-596b6dad7223.png">

**Comment by mkhandekar** [comment]
@laurjpeterson Do we have a screenshot of the VBMS periods and circumstances data?

**Comment by eric-nava** [comment]
Hey, @shanear @mdbenjam - we're looking for some real vet data that contains "flashes." Do you know where we might find some?

**Comment by sneha-pai** [comment]
- [VBMS Flashes Categories](https://www.notion.so/VBMS-Flashes-Categories-1d357e9e76f249da8964f805e407580f 
) from [this va resource/guide](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000036570/Appendix-C.-Index-of-Claim-Attributes#2)

- [VBMS Flashes screenshot from a real claim case](https://www.notion.so/VBMS-Flashes-screenshot-of-a-real-claim-case-1b91c7f921d74d2cb39bc5451b186d24) from [this blog](https://asknod.org/2018/11/07/vbms-returning-computers-to-the-dial-up-era/)

**Comment by sneha-pai** [comment]
![image](https://user-images.githubusercontent.com/31224257/57725447-26689380-765b-11e9-89c4-bbc2c333fcd5.png)

**Comment by laurjpeterson** [comment]
Users haven't really asked for this. If we get this feedback in the future, we can create another ticket for it.
