### ISSUE TITLE
Case details | Header | View all cases associated with a Veteran ID

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5743]
With the new Case details design, we've consolidated some information in the header. When users navigate to see information about the Veteran's appeal, they want to easily view other appeals/cases associated with the Veteran, so they can quickly access tools and info needed to gain context on the case. 

## AC
- Verify that a link to 'View all cases' is on the same line as Veteran name.
- When the user clicks 'View all cases', a dropdown window appears per the mocks, titled '[Veteran name]'s cases'.
- Verify that the dropdown window contains the same information and view as case search results.
- Verify that if a user clicks on docket number (?), they are taken to that appeal's case details page. @mkhandekar to verify.

## Mocks
@mkhandekar to add

## Resources
- [Case details Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1525112874684/5765d285f568b5f631990e2c8e514a39d9b6b570)

**Comment by lowellrex** [comment]
@mkhandekar @laurjpeterson What do we want to do when the Veteran only has one case associated with them (and thus, if somebody is viewing a case details page for the Veteran it will be the only case that Veteran has)? Do we still want to display the "View all cases" link and list the one case that is already open, or do we want to do something different?

**Comment by laurjpeterson** [comment]
Good q. I defer to Meghana here. We wouldn't need to show a link, but we might want to include some copy in its place to explain that this is the Veteran's only case. 

Side note - if a Veteran has 1 active appeal and 1 appeal in history status, I'd still want to show the view all cases link so the user can see the active and history status appeal.

More q's!
- @mkhandekar - would the case that the user is viewing also be in the case list? if so, should we signal that it is the current appeal?
- @lowellrex - for AMA appeals, it would be awesome to also show if a Veteran has open supplemental claims or higher level reviews. this is just a nice to have, but it could be a good question to ask shane about how we might do this in the future.

**Comment by mkhandekar** [comment]
Agreed to not show "view all cases" link when there is only 1 case, and thinking on how we can indicate that this is their only case. 

@laurjpeterson can you say more about the difference between "active appeal" and "appeal in history status"?

**Comment by mkhandekar** [comment]
I'm going to put together a couple views for us to look at that include: 

- normal state 
  - Veteran has 1 case open
  - Veteran has more than 1 case to their name
- view all cases clicked > view list
  - Veteran has 1 case open
  - Veteran has more than 1 case to their name
- view all cases clicked > view list > indicate that one of the cases in the list is being viewed currently

**Comment by laurjpeterson** [comment]
@mkhandekar 
- active appeal - any appeal that has not been decided yet; it's "active" at the Board
- history appeal - an appeal that has been decided. a decision has been sent to the Veteran, and no further action needs to be done (i.e. there are no remanded issues). 

For some more context of where I got the terms from, "active" (ACT) and "history" (HIS) status are fields in VACOLS. You can see how this looks on the first screenshot on the VACOLS Mural - https://app.mural.co/t/workqueue2001/m/workqueue2001/1507744211843/c9bc053003b3581e4dd469dc67e208fb113f1e1f

**Comment by mkhandekar** [comment]
@laurjpeterson all makes sense - thank you for taking the time to break it down!

**Comment by lowellrex** [comment]
About to merge the first step for this issue but wanted to attach a screenshot of what the current state looks like for reference as we figure out the remaining items.
![image](https://user-images.githubusercontent.com/32683958/43803581-3e16eb1a-9a67-11e8-93b0-b9ea2b3625ca.png)

**Comment by laurjpeterson** [comment]
@mkhandekar @lowellrex - since we've implemented this first iteration of view all cases and it meets the current acceptance criteria, shall we close this issue? we can open another when we prioritize enhancements to this feature.

**Comment by mkhandekar** [comment]
Sounds good! Opened a new issue ^
