### ISSUE TITLE
Remind users to fill out form 8 if they select hardcopy claims folder

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#575]
@KHarshawat -- not sure who I should assign this too... 

We noticed confusing during usability testing that there is some confusion about paperless claims and paper-based claims in the pop-up following a user clicking "certify". We need to make sure users understand that if they have a virtual VA case or a hardcopy case that they will still need to fill out form 8.  

![image](https://cloud.githubusercontent.com/assets/12674895/12723748/bae2125e-c8d8-11e5-9fe9-5cdcb0d560c3.png)

Similarly to the popup for Caseflow when a user selects "VBMS paperless e-folder," (Caseflow will now launch in your web browswer..) can we add a popup when users select "Hardcopy.." to say:

"You will need to fill out a form 8 manually to complete certification."

**Comment by KHarshawat** [comment]
Jed has added this.
