### ISSUE TITLE
Case details breadcrumbs do not update

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#5757]
![breadcrumb-persistence](https://user-images.githubusercontent.com/32683958/40853392-e94ba166-659b-11e8-84e0-a1c7fcb916f7.gif)

## Reproduction steps
* Start at a personalized task queue
* Enter the case details view for some case
* Observe the link in breadcrumbs reflect the name of the Veteran to which the case belongs
* Click the "Your Queue" breadcrumb to return to the queue
* Enter the case details view for a different case
* Observe the link in the breadcrumbs has not been updated to reflect the current case's Veteran information

## Acceptance criteria
* Navigating to case details pages cause the breadcrumbs to update

**Comment by laurjpeterson** [comment]
closing this because we've removed breadcrumbs from Caseflow! cc: @mdbenjam @lowellrex @mkhandekar @sneha-pai
