### ISSUE TITLE
Add test for modal focus capture

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#576]
It is difficult to test the modal focus capture in a unit test since it involves capturing tab events on the document. See if there is a way to do this, or if a feature test is necessary.

**Comment by kierachell** [comment]
@mdbenjam 
Since we're adding a few modals; are you talking about the current Cancellation modal or?

I can put something together as a feature test probably.

**Comment by mdbenjam** [comment]
I'm talking about the Cancel EP modal. That's written in React and will be what we use going forward. I think a feature test would be good. I would love to write it as a react test using the Enzyme testing framework (see EstablishClaim-test.js) but was having a lot of trouble controlling focus in that. So it'll probably have to be a feature test.

**Comment by kierachell** [comment]
I'll see what we can do

**Comment by kierachell** [comment]
Well, right now it doesn't capture focus at first (it does after tabbing through all the background elements and landing within the modal); so the tests will break the deploys;

Make sure it captures right away and then we can add the tests.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
