### ISSUE TITLE
Fetch task information when navigating directly to case details page

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#5764]
Currently we use the tasks from a user's personalized task queue to populate the "active task". If a user clicks into a case details page from their queue, we use the element of the assigned tasks queue to set the task associated with the case they clicked on as the "active task". However, if we navigate directly to the case details page via URL we will never set the "active task" (and will not display the associated task information if there is any) because we have not yet loaded the user's personalized task queue.

When navigating directly to a case details page, we should fetch the task information for the associated case, and set the "active task" if the current user has a task associated with that case. I can think of three ways off the top of my head, but I am sure there are others:
* Load the user's queue when navigating to a case detail page
* Load the case information and fetch the associated task if the case's `location_code` matches the current user
* Return the task associated with the case when returning the case information in the initial call and conditionally set it as "active task"

## Acceptance criteria
* Display the task information (if applicable) when navigating directly to a case details page directly

**Comment by lowellrex** [comment]
When navigating back to the case details page from Reader, task information also fails to load.

**Comment by laurjpeterson** [comment]
@lowellrex - it looks like you already knew about the support issue I tagged you on today! https://github.com/department-of-veterans-affairs/appeals-support/issues/2773
