### ISSUE TITLE
End Product:  Decision Date:  Change to be editable value

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#577]
As a Caseworker, I would like to be able to change the defaulted _"Decision Date"_ so that it contains the correct value since sometimes the VACOLS Decision Date is not accurate.

# Acceptance Criteria
1. Verify that the field _“Decision Date”_ defaults to the VACOLS decision date.
1. Verify that field _"Decision Date"_ can be edited.

### Mockups
![image](https://cloud.githubusercontent.com/assets/23063044/21272672/51cf502c-c38e-11e6-8803-abac75f2d3cb.png)

# Related Stories
End Product: Collect information for creating an End Product  https://github.com/department-of-veterans-affairs/caseflow/issues/416

**Comment by kierachell** [comment]
Done. 

Checked to be editable; (can be edited to an invalid date e.g. 14/33/0109)
