### ISSUE TITLE
Work needed to support multiple ramp elections

### ISSUE THREAD

**Issue by kahlouie** [department-of-veterans-affairs/caseflow#5776]
# Supporting multiple ramp elections

## What is the problem?
Some users may still have claims being settled after their opt-in to RAMP. This leaves some of their appeals as legacy appeals, and some as converted appeals. We're aiming to support all of their appeals through RAMP.

## What we learned:
In our discovery, we determined that it is possible to support multiple ramp elections. There will need to be some modifications to the code base to support this. Please note that while we are supporting multiple ramp elections. We are NOT supporting multiple ramp refilings. Each veteran will only be entitled to one ramp refiling at the moment, regardless of how many ramp elections they have. The reason we don't intend to support multiple ramp refilings yet is that this will add undue complications at this moment.

### app/models/ramp_election_intake.rb
   In `#find_or_build_initial_detail`, if we find existing ramp election and it has an active EP, add this intake to existing ramp election. We might even want to move the `#matching_ramp_election` up into this method as it's the only place it'll be used.
 
 
   In `#validate_detail_on_start`, remove the if clause `matching_ramp_election.established?` as we should now support extending existing ramp elections and supporting multiple ramp elections if the EP on the existing ramp elections are no longer active.
 
   `#veteran_ramp_elections` may need to be deleted or moved up into `#find_or_build_initial_detail`.
   
### app/models/ramp_refiling.rb

  Take out the assumption that a ramp refiling belongs to a single ramp election. This will involve data model changes as well, though. We will either need to support storing multiple ramp elections in ramp refiling or remove altogether and base it on the veteran_file_number.
 
  In `#election_receipt_date`, we should choose the earliest receipt date of the ramp_elections.
 
  We'll need to modify `#validate_receipt_date` and `#validate_option_selected` to handle multiple ramp elections.

### app/models/ramp_refiling_intake.rb

  We'll need to modify `#preload_intake_data` and `#validate_detail_on_start` to handle multiple ramp elections.

  In `#validate_detail_on_start`, the first if clause should check if ramp_elections is empty. The second should check that there aren't any active ramp elections. The third one needs to make sure cleared ramp elections have no issues. We should continue ensuring there's only a single ramp_refiling per veteran ever (at the moment).

  In `#ramp_refiling_already_processed?`, we'll need to check for the ramp refilings by veteran file numbers instead of by ramp election id.
 
  In `#initial_ramp_refiling`, don't set the ramp election on the ramp refiling.
 
   We'll have to get multiple ramp_elections instead of using the existing `#ramp_election`. We'll need to fetch them by veteran file number. 
 
   Same with `#fetch_ramp_election`.
 
### db/schema.rb

  We'll need to disconnect the ramp_election_id from ramp refilings table.

## Plan of attack
1. Support multiple elections (we can fake do this by just adding the single one to an array). You'll need to account for this when making date calculations and in validations.
2. Fetch elections based on veteran file number instead of ramp election id. It should then only be an array of one item, but it should be doing the "right thing". Remove any code connections between ramp election id and ramp refilings.
3. Remove ramp election from the ramp refiling table. At this point, we can now safely remove it from the db since we're no longer using it in code. This last one should be it's own pr and deployed separately.

**Comment by shanear** [comment]
Hard to grok fully, but looks good to me. I'd love to get a plan on how we can make this change in chunks. Do you have thoughts on that?

**Comment by kahlouie** [comment]
@shanear I will brainstorm this afternoon.

**Comment by kahlouie** [comment]
@shanear Added the Plan of attack section. I think it's relatively safe and chunked small enough, but please share any feedback! 😄

**Comment by shanear** [comment]
We tried one in prod and it worked! calling this one done

**Comment by kahlouie** [comment]
All cleaned up now 🎉
