### ISSUE TITLE
End Product: Claim Label:  Should be labeled as "EP & Claim Label"

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#578]
The _"Claim Label"_ field is labeled incorrectly.  It should be labeled as "EP & Claim Label".

# Reproductive Steps
1. Click on the **_Establish Next Claim_** button.
1. Click on the _**Create End Product**_ button.
1. The label for "Claim Label" is wrong.  (Refer to mockups and related stories)
### Mockups 
![image](https://cloud.githubusercontent.com/assets/23063044/21273041/bcc3fbca-c38f-11e6-91f3-21a496f62746.png)

# Related Stories
End Product: Collect information for creating an End Product https://github.com/department-of-veterans-affairs/caseflow/issues/416

**Comment by kierachell** [comment]
Label looks fixed: "EP & Claim Label"
