### ISSUE TITLE
All Sentry errors for `/api` should go to #appeals-status

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5785]
They currently go to #appeals-queue.

![image](https://user-images.githubusercontent.com/3781835/40942617-a2660d62-6803-11e8-95e8-39df7fc65cad.png)

# AC
- All Sentry errors for `/api` should go to #appeals-status

**Comment by alisan16** [comment]
Closing as this is now obsolete.
