### ISSUE TITLE
User dropdown broken on React pages

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#579]
User dropdowns (controlled by jQuery) are broken on react pages. 

Steps to reproduce:
1) Login as Dispatch Manager
2) Go to Dispatch Landing Page
3) Click user dropdown in top right corner
4) Result = no affect. Dropdown does not open

**Comment by shanear** [comment]
also have a feature test

**Comment by kierachell** [comment]
Verified to work on all pages that are available to this role

<img width="593" alt="screen shot 2016-12-21 at 22 34 44" src="https://cloud.githubusercontent.com/assets/18075411/21414479/c1c8b5a6-c7cd-11e6-9b13-2a0058502110.png">
