### ISSUE TITLE
Add real end product codes

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#5790]
We now have the real end product codes, so we should update the placeholders with the real thing.

040SCNR Supplemental Claim Non-Rating
040SCNRPMC PMC Supplemental Claim Non-Rating
040SCR Supplemental Claim Rating
040SCRPMC PMC Supplemental Claim Rating
040SCRRAMP RAMP - Supplemental Claim View

030HLRNR - Higher-Level Review Non-Rating
030HLRNRPMC - PMC Higher-Level Review Rating
030HLRR - Higher-Level Review Rating
030HLRRAMP - RAMP - Higher Level Review
030HLRRPMC - PMC Higher-Level Review Rating

**Comment by shanear** [comment]
This was fixed by https://github.com/department-of-veterans-affairs/caseflow/pull/5680
