### ISSUE TITLE
Remove Actions column from attorney queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5798]
In order to make more space for columns in our queue table and to encourage users to complete actions from Case details, we'd like to remove the Actions column from our table design.

## AC - 
- Actions column has been removed from attorney queue

## Notes
- Actions column will be removed from judge queue when it's added to judge case details - https://github.com/department-of-veterans-affairs/caseflow/issues/5504

**Comment by laurjpeterson** [comment]
Prioritizing this before we rollout attorney checkout to more attorneys

**Comment by laurjpeterson** [comment]
@lowellrex this is live! can i close this issue?

**Comment by lowellrex** [comment]
Closed!
