### ISSUE TITLE
Ensure form8 exists locally before serving it

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#580]
We encountered a bug in production during a deploy where a form8 file did not exist locally

This will occur on a deploy when the app servers are being rotated in/out of the LB

<img width="1092" alt="screen shot 2016-12-16 at 6 01 55 pm" src="https://cloud.githubusercontent.com/assets/2256237/21281377/1be81832-c3ba-11e6-8638-35442924c4bb.png">

For more information can check in Sentry
https://localhost:8080/department-of-veterans-affairs/caseflow-certification/issues/36/

# Related Stories
**_Product Support Issue:_**  
Preview Form 8: Upload and Certify: User unable to upload Form 8 and receives error message [#11](https://github.com/department-of-veterans-affairs/appeals-support/issues/11)
**_Engineering Stories_**
Send user ID and email address to sentry - https://github.com/department-of-veterans-affairs/caseflow/issues/581
Record User email addresses - https://github.com/department-of-veterans-affairs/caseflow/issues/583

**Comment by shanear** [comment]
This requires S3 to be configured and set up in production to complete this issue.

**Comment by joofsh** [comment]
@shanear can you clarify what you mean? This bug is already occurring in production.

**Comment by shanear** [comment]
This issue was blocked because the solution required s3. Which wasn't yet deployed, this is ready to be developed

**Comment by aroltsch** [comment]
I think @shanear will be testing this.

**Comment by shanear** [comment]
<img width="953" alt="screen shot 2017-01-31 at 11 22 51 am" src="https://cloud.githubusercontent.com/assets/1596259/22473744/d0d1d092-e7a7-11e6-8ee5-8848ce59a792.png">

So it does reload the PDF from s3. But PDF.js thinks the pdf is corrupted. Need to look into this.

**Comment by nikitarockz** [comment]
@shanear Is this issue going to be worked?  It is a fix for a support ticket.

**Comment by aroltsch** [comment]
@shanear to troubleshoot, I can try setting up S3 access on my local machine and use the actual s3_service instead of the fake one.

**Comment by shanear** [comment]
Yeah, I'm going to try and have it figured out by the end of the week

**Comment by shanear** [comment]
confirmed the storage in S3 is busted

```
=> "/opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf"
irb(main):004:0> `cat /opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf | openssl sha1`
=> "(stdin)= 7b48ca575970331944f2d20e74d138dfb6daa066\n"
irb(main):005:0> FileUtils.rm("/opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf")
=> ["/opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf"]
irb(main):006:0> `cat /opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf | openssl sha1`
=> "(stdin)= 26060aff26c2b6ea8a5c64e2f91404f48aeacff9\n"
```

**Comment by shanear** [comment]
Validated on the terminal and in the browser.
```
irb(main):005:0> `cat #{filepath} | openssl sha1`
=> "(stdin)= 6dca78ece0b735f20e0580a8880577aa279bbaea\n"
irb(main):006:0> FileUtils.rm(filepath)
=> ["/opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf"]
irb(main):007:0> Form8.last.pdf_location
  Form8 Load (1.3ms)  SELECT  "form8s".* FROM "form8s"  ORDER BY "form8s"."id" DESC LIMIT 1
=> "/opt/caseflow-certification/src/tmp/pdfs/form8-123C.pdf"
irb(main):008:0> `cat #{filepath} | openssl sha1`
=> "(stdin)= 6dca78ece0b735f20e0580a8880577aa279bbaea\n"
```
