### ISSUE TITLE
Show when a case is newly assigned to a user

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#5800]
We have introduced two ways to view work: In Progress and On Hold tabs. In Progress contains cases that have just been assigned to the user. On Hold contains cases that the user has passed on to someone else, and is waiting for their response.

We need a way to differentiate ongoing in progress cases from _newly assigned cases_ that the user hasn't opened the Case Details for. 

### Explore treatment for new cases in tables for:
- [x] judges
- [x] attorneys
- [x] co-located staff

**Comment by laurjpeterson** [comment]
Related, bolding ticket from a while ago- https://github.com/department-of-veterans-affairs/caseflow/issues/4573. @dannysellers should these be two separate tickets?

**Comment by mkhandekar** [comment]
@dannysellers @evankroske do you both think this (brand new cases in New tab show up as **bold**, anything that the user has clicked on returns to normal weight) is addressed in y'alls co-located work? if yes, we can close this.

**Comment by dannysellers** [comment]
Oops, sorry I missed your question Lauren, but no, I don't think these need to be separate tickets. We currently use a `CaseDetailsLink` component in all tables to link to the case details view, so we should automatically get this behavior everywhere once it's implemented 👍

I have not done any work on this

**Comment by laurjpeterson** [comment]
@evankroske - since you're working on co-located users viewing their work in the queue table, do you think you could add this change into one of your upcoming PRs?

**Comment by dannysellers** [comment]
Current implementation (leaving for future reference):
- For all AMA/RAMP/BEAAM (non-legacy) tasks and all users / user roles, we will set their status to `in_progress` when the user clicks into the case details view (#6788)
- For colocated users, we will bold the case detail link for `assigned` tasks

#### Eventually
Once DAS is deprecated, we'll be able to store Task information for LegacyAppeals in the Caseflow database, and will be able to track when a user first views a task.

**Comment by mkhandekar** [comment]
Can we close this?

**Comment by hschallhorn** [comment]
Where we determine bolding (remove role check!) https://github.com/department-of-veterans-affairs/caseflow/blob/0ec98c06bdf3d76d2059f4e94c858b90d3c12eb9/client/app/queue/CaseDetailsLink.jsx#L46
Where we pull all tasks for an appeal for case details (add update status for any tasks with "assigned" status and assigned to the current user) https://github.com/department-of-veterans-affairs/caseflow/blob/befe386da2803738292594f844a7f9fb87317f9e/app/controllers/tasks_controller.rb#L102-L108
