### ISSUE TITLE
Explore ways to show definitions and help text in Caseflow

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#5802]
As we build Caseflow, we are changing terminology and patterns that our users may not easily grasp. A recent example: we've changed "placed in abeyance" (feelings of: off my plate, another team's responsibility) to "on hold" (grounding in plain language that hopefully expresses that the case is still on my plate but I'm waiting for something).

If content is important and key, we'll need to say that on the page. If content is supplementary and could be helpful _in case_ a user is confused or turned around, help text or definitions of new terms may be helpful.

We want to explore what it might look like to introduce this idea within Caseflow, with a clear focus on accessibility and usability. It could be:
- a hoverable / clickable tooltip
- a link to FAQ / Help section of Caseflow
- something else entirely

**Comment by mkhandekar** [comment]
![image](https://user-images.githubusercontent.com/1598889/41377299-a6589ca0-6f29-11e8-826f-cde654a20442.png)

The above screenshot is a little overboard with little tooltips, but just wanted to share a start to the type of items that might benefit from a little explanation.

The first thing we will implement is the little (i) icon to describe "on hold" as a new term for a familiar concept "in abeyance".

**Comment by laurjpeterson** [comment]
@mkhandekar - since we've implemented a few of these tooltips so far, can we close this issue?

**Comment by mkhandekar** [comment]
Yes! 🎉
