### ISSUE TITLE
Discuss architectual issues with the current caseflow

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#581]
- Most of the logic is in controllers or views, not very testable or idiomatic.
- routes.rb doesn't use resources, not very idiomatic
- all the routes are in one big WebController. Possibly separate out?
- there are almost no tests. The tests that exist aren't in rSpec.
- no way to write tests involving models (because VACOLS oracle database is required)
- column names are obscure, and not translated in the app
- javascript isn't very modular, and untested
- lots of unused models (presumably just to document VACOLS: attachment, appallant type,  etc)
- global variables ($vbms)
- non-idiomatic handling of error routes

**Comment by shanear** [comment]
@paultag @orischwartz

**Comment by shanear** [comment]
Additionally, clicking the back button breaks all the show/hide things on Form 8. It's not pretty.

**Comment by orischwartz** [comment]
Submitted form fields should be parsed from strings to native types and then formatted back to strings as needed for the PDF form.

e.g., Dates are currently taken as strings from the submitted form and printed directly to the PDF, which assumes both PDF and HTML form use the same date format. They're two distinct uses of the same date and should be treated as such.
