### ISSUE TITLE
Send user ID and email address to sentry

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#581]
Currently, Caseflow is only sending user IP address to Sentry, and not email address and/or CSS ID.  Without these identifiers, product support team can not reach out to the users when they experience failures.

Efolder is doing this correctly.

# Related Stories
**_Product Support Issue:_**  https://github.com/department-of-veterans-affairs/appeals-pm/issues/1092
Ensure form8 exists locally before serving it - https://github.com/department-of-veterans-affairs/caseflow/issues/580
Record User email addresses - https://github.com/department-of-veterans-affairs/caseflow/issues/583

**Comment by aroltsch** [comment]
This can only be tested in production because production environment is the only one that has a Sentry server.

**Comment by astewarttistatech** [comment]
@shanear This can only be tested in Prod, see Anya's comment, so how would you like to proceed?

**Comment by aroltsch** [comment]
Alan set up Sentry server in UAT so can be tested in UAT now
