### ISSUE TITLE
Record User email addresses

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#583]
As a Product Owner, I would like to have the email addresses for the users that log into Caseflow captured, so that we can contact them in case of an error.

# Acceptance Criteria
1. Verify that when the user logs into Caseflow, their email address is captured. (Does this mean the login screen is changed?)
1. Verify that the captured user's email can be retrieved.

# Related Stories
**_Product Support Issue:_**  https://github.com/department-of-veterans-affairs/appeals-pm/issues/1092
Send user ID and email address to sentry - https://github.com/department-of-veterans-affairs/caseflow/issues/581
Ensure form8 exists locally before serving it - https://github.com/department-of-veterans-affairs/caseflow/issues/580

**Comment by aroltsch** [comment]
This can be validated on demo. However, should be validated on UAT as well.

**Comment by astewarttistatech** [comment]
@kierachell this has been validated in Demo but we need someone to validate in UAT. @shanear any suggestions?

**Comment by shanear** [comment]
None of our users have emails in UAT, I will validate this in prod after the deploy this afternoon

**Comment by shanear** [comment]
validated in prod DB. New users are getting emails!
