### ISSUE TITLE
Install Rails Prometheus client and have custom counters report to Prometheus

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#585]
UAT/Prod Caseflow, Feedback, and eFolder should report some simple custom counters to the Prometheus servers in UAT and Prod. 

Metrics we want:
current thread count
DB connection count
????

Let’s install the Prometheus client in each of the Rails apps and report to the Prometheus servers. This issue covers eFolder, Feedback, and Caseflow.

https://github.com/prometheus/client_ruby

**Comment by askldjd** [comment]
As of yesterday, Prometheus ruby client is now part of Caseflow.

![image](https://cloud.githubusercontent.com/assets/3258724/22253431/981f7a20-e21f-11e6-8d83-5a0658bcfc99.png)
