### ISSUE TITLE
Question 9B should only be shown if 9A == 'no'

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#585]
1) go to form 8 page.
2) Select "Service Organization" for question 8A
3) Select "Yes" for question 9A
4) Write something in 9B
5) submit the form.

Whatever you wrote down in 9B does not appear on the form. I assume that's because it's irrelevant (with an answer of yes on 9A).

Should we just hide 9B when 9A is yes, instead of blowing out the user's input?

**Comment by KHarshawat** [comment]
@shanear yep, you got it. 9B should be hidden if 9A = `yes`

**Comment by orischwartz** [comment]
If nobody objects, assigning myself, was just looking at this for #583

**Comment by shanear** [comment]
@orischwartz :+1:
