### ISSUE TITLE
Non-rating issue validation

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#5858]
For non-rating issues, determine if category and description are required. If category is not required, do we want to default it to "Unknown". If data is not filled in, do we want to grey out the "add issue" button.  Find out if someone can finish an intake with only non-rating issues?

**Comment by abbyraskinUSDS** [comment]
Blocked on connecting w/ AMO on preferred handling

**Comment by leikkisa** [comment]
I'm going to combine this information into the existing ticket, and close this.
