### ISSUE TITLE
Fix ratings call when there are zero ratings within 1 year timeframe and display a message 

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5868]
Currently, if a Vet has no ratings in BGS, users see a normal error, but then their account is stuck in limbo (they can't do anything else until it's cleared out in BGS).

If the Veteran does not have any rating issues from the past year, we should show a message to users, so they can notify the Veteran or take any necessary actions.

## Acceptance Criteria
- Fix the backend issue to allow AMA intakes to happen even if there are no timely ratings in BGS 

```
NoMethodError: undefined method `[]' for nil:NilClass
	from app/models/rating.rb:65:in `ratings_from_bgs_response'
	from app/models/rating.rb:46:in `fetch_timely'
	from app/models/veteran.rb:104:in `timely_ratings'
	from (irb):27
```
- Display a message on this page (copy below) under the decision issues header

### Copy
> This Veteran has no rated, disability issues within the one-year timeframe for requesting a review. If the Veteran listed non-rated issues, add them below. Otherwise, cancel the intake and follow your standard operating procedures for notifying the Veteran.

**Comment by abbyraskinUSDS** [comment]
Asking Rachel for suggestions.

**Comment by abbyraskinUSDS** [comment]
Mock to follow

**Comment by abbyraskinUSDS** [comment]
I think we should rethink this interaction altogether.

**Comment by abbyraskinUSDS** [comment]
Since they can now add non-rated issues, i think this approach makes sense (I was thinking we'd want to detect this earlier in the process)

**Comment by abbyraskinUSDS** [comment]
@leikkisa here's the no ratings ticket

**Comment by leikkisa** [comment]
Should I keep the "Select from previously rated issues" heading?
<img width="866" alt="screen shot 2018-07-30 at 3 45 50 pm" src="https://user-images.githubusercontent.com/6589610/43427745-d37f1e6a-940f-11e8-9226-6faa3c6f6841.png">

**Comment by suzchap** [comment]
Abby and I discussed... agree the language here is awkward in this scenario but I plan to do a full design/content audit in the next few weeks so I added this to my [Audit & Style Guide ticket](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/938) so we're fine leaving it as-is for now. Thanks for noticing it!

**Comment by leikkisa** [comment]
Can validate this using Veteran 933732230
