### ISSUE TITLE
Caseflow Certification Nav Bar is shorter than other Caseflow apps

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#588]
This is very small but I can't figure out what's causing it and it's driving me nuts. The nav bar height on Caseflow Certification is shorter than on other Caseflow apps. See the gif below (look at the curser) for a demonstration. I've dug through the CSS in the DOM but can't tell what the difference is. 

![navbar height](https://cloud.githubusercontent.com/assets/6335546/21324243/e9f33d20-c5ee-11e6-9251-95142122d98d.gif)

**Comment by slj** [comment]
@KHarshawat I cannot reproduce this locally.  @kierachell can you?

**Comment by kierachell** [comment]
![headersize](https://cloud.githubusercontent.com/assets/18075411/23231915/7c6d8452-f917-11e6-8c15-3a05af41ae13.gif)

**Comment by slj** [comment]
Height is consistent (cannot reproduce locally and QA verified consistency)

Logo position is a different issue.
