### ISSUE TITLE
Intake | Show appropriate issue categories in Add Issues modal for HLRs and SCs

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5882]
We should only show issue categories appropriate to the selected business line.

## Acceptance Criteria
- When intaking or editing issues on an HLR or SC, the "Issue Category" field on the second modal in the Add Issue flow should have only the options for the business line selected in the "Benefit Type" question on the previous page. See the category lists in https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1043.

## Notes
requires https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1043

**Comment by leikkisa** [comment]
Are the current issue categories all of the "Compensation" issue categories?

**Comment by steve-gov** [comment]
Validated. There will likely be some revisions before launch but no bigs.
