### ISSUE TITLE
Hearing Worksheet | Checkbox undefined error

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5883]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1562/

**Comment by tejans24** [comment]
![Screen Shot 2018-06-14 at 4.41.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5675faf1c69a181300e98240/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f76b7191a37cf1162a4f5e585ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df442e14c57a1123564e07f2431.png)
