### ISSUE TITLE
Have Caseflow verify POA

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#59]
https://github.com/department-of-veterans-affairs/caseflow/issues/88

**Comment by shellicious** [comment]
@shanear @KHarshawat, do you have more context about this issue?

**Comment by KHarshawat** [comment]
@shellicious Sometimes we may have  Power of Attorney on record (through VACOLS). Today Caseflow Certification shows the Representative at the top of the screen but does not allow the user to edit/change this information. We should actually add a pre-filled field with this information and allow the user to edit as necessary.

The Veteran can be represented by themselves, a private lawyer, an agent, or a Veteran Service Organization. Most common representatives have re-used representative codes stored in the system for reference.

**Comment by laurjpeterson** [comment]
Closing. Caseflow Certification v2 surfaces the VACOLS and VBMS POA to the user, asking them to verify and edit if needed.
