### ISSUE TITLE
Queue | Fix access for role-less users

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#5905]
With the [rollout of the `:case_search_home_page`](https://github.com/department-of-veterans-affairs/caseflow/blob/9479f7d98142d719398e104215316a68499b224b/app/controllers/home_controller.rb#L7) FeatureToggle, we allow users to access Queue who have no `vacols_role`. However, the site wouldn't work for these users, because within `QueueApp`, we [use the user role to set the page title](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueApp.jsx#L166).

Possible solutions include:
- Give `QueueApp` a default prop of `""` for `userRole`
- Modifying the arguments in [`queue/index.html.erb`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/views/queue/index.html.erb#L5)
- Within `QueueApp`, set page titles in a way that fails (more) gracefully

**Comment by laurjpeterson** [comment]
@dannysellers is this one ready to close?
