### ISSUE TITLE
Expose application version and deployment time

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow#592]
We need an easy way to determine which version we're running in production to eliminate confusion over which fixes are included. 

There are many ways to do this but at a minimum we should expose:

* Deploy time
* Git revision
* *Optional*: [Application version](http://semver.org/)

Ideally this would be auto-generated at deployment and exposed

* In small print on every page footer
* With more diagnostic information hidden in the `title` attribute or an HTML comment.

For example, here's stackoverflow's footer:
![untitled](https://cloud.githubusercontent.com/assets/16327036/12930707/e21b2c00-cf47-11e5-9659-ab11971fe7d6.png)

**Comment by paultag** [comment]
Issue being addressed in another repo, porting issue.
