### ISSUE TITLE
Add end_product_status to Ramp Refiling

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#5926]
Add end_product_status, and end_product_status_last_synced_at to Ramp Refiling

**Comment by kahlouie** [comment]
@leikkisa I think this is outdated now that we don't keep that on the various appeals and store this in end product establishments table. Mind if we close it?

**Comment by leikkisa** [comment]
@kahlouie Makes sense! Yay for EndProductEstablishment DRY'ing up some work.
