### ISSUE TITLE
 AMA intake | Establish EPs in station 499 (NWQ) not 397 when NWQ is ready

### ISSUE THREAD

**Issue by leahbannon** [department-of-veterans-affairs/caseflow#5928]
AMA EPs will be distributed by NWQ and not assigned directly to AMO. This means they should be created in station 499 (NWQ)

## Acceptance Criteria
- All EPs created for AMA claim reviews should be created in station 499

**Comment by shanear** [comment]
<img width="742" alt="screen shot 2018-10-26 at 2 30 41 pm" src="https://user-images.githubusercontent.com/1596259/47585599-bd723600-d92b-11e8-901a-a037bf400786.png">

The EP was correctly routed via the NWQ
