### ISSUE TITLE
Smoke test judge checkout to dispatch in  the VACOLS UI 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5933]
## Context

We should do a manual test with Caseflow and the VACOLS UI before launching the judge checkout to dispatch flow to ensure basic correctness and backwards compatibility.

This test does not have to test every detail and edge case, it should just act as a smoke test.

We should use Caseflow preprod, since Caseflow preprod connects to VACOLS dev and the VACOLS UI is running connected to the VACOLS DB. 

## Testing Steps (tentative, should be fleshed out)
1. Log into Caseflow in preprod as a judge with cases to review
1. Log into the VACOLS UI as the same judge
1. Go through the Caseflow flow to check out a case to dispatch, edit dispositions, and edit remand reasons 
1. Go through the VACOLS flow to check out a case to dispatch, edit dispositions, and edit remand reasons
1. In the VACOLS UI, verify that both cases are in the BVA dispatch location, and that the edited info appears as expected - issues, remand reasons, etc

**Comment by dannysellers** [comment]
Notes from 7/2/2018 test:
- Overall quality attr (Evaluate Decision) was not set—no option selected in VACOLS
- Look into "one-touch initiative", an option in VACOLS screen with case review options (Decision tab?)
- Cases should be set to active status
- We currently allow assigning cases to inactive judges

**Comment by aroltsch** [comment]
@laurjpeterson @dannysellers a fix for the overall quality attribute not being set has been merged.
