### ISSUE TITLE
What time should foxtrot standup be?

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5934]
## Goals
- provide daily updates and promote alignment as a team
- promote productive time / reduce interruptions in the morning
- maintain time for team discussions as they come up

## Options (add more!)
1. Move standup earlier, to 10:00am
   - pros: uninterrupted time from ~10:30-11:45am
   - cons:  earlier mornings?
2. Move standup to 11:20ish
   - pros: 9-11ish could be uninterrupted time; forces us to be timely for standup before caseflow-wide standup, if we did pre-standup discussions at 11am would also force some timeliness standards. 
   - cons:
      - not at the beginning of the day would have to adapt to a different discussion time
      - discussion times, if before 11:20ish could bleed into standup time and interrupt our ability to hold standups
3. Keep standup at 10:15am
4. Other options?

**Comment by aroltsch** [comment]
I like option 3

**Comment by mdbenjam** [comment]
I think we should check with @shanear and the rest of Caseflow West to see if they'd be interested in our standup. Otherwise I say stick with what we have (option 3)

**Comment by mkhandekar** [comment]
Option 1 or 3 for me :)

**Comment by evankroske** [comment]
I vote for option 2. I'd like to squish all my meetings into a block

**Comment by laurjpeterson** [comment]
@mdbenjam and i connected with @shanear earlier this week. it sounds like mark will attend intake standups, and not vice versa, for now.

**Comment by laurjpeterson** [comment]
Since we're experimenting with teamwide standup being before wisdom wednesday, I think the pain point of interrupted mornings is reduced. Let's keep standup at 10:15am.
