### ISSUE TITLE
Add S3 Bucket ENV to Prod and UAT

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#595]
Add the environment variables to enable S3

**Comment by kierachell** [comment]
I'm sure it's there and works perfectly!
Tagging @askldjd @shanear to the rescue

**Comment by shanear** [comment]
This will be validated vicariously through https://github.com/department-of-veterans-affairs/caseflow/issues/580.

Will go ahead and close this issue out to remove the clutter
