### ISSUE TITLE
Flow 2 | View Schedule | Download the current schedule

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#5953]
### User story
As a hearing branch manager, I want to be able to export the current schedule with a date range to quickly filter data for reports and QA. 

### Acceptance criteria
- [ ] Verify that there is a "Download schedule" dropdown in the upper right of the view schedule page
- [ ] Verify that when a user clicks the dropdown, it expands to show two date ranges following our date input component
- [ ] Verify that there is a download button, which downloads the current schedule based on that range

### Mocks
Default view
![list view judge filled download not expanded](https://user-images.githubusercontent.com/23316107/43909251-de4cf4c4-9bc7-11e8-98e8-b511026f5a31.png)

Expanded view
![list view judge filled](https://user-images.githubusercontent.com/23316107/43909223-cc55834e-9bc7-11e8-845d-0005193c1662.png)

**Comment by MeredithStewart** [comment]
Looks great, @Chingujo!

**Comment by oscarAtNava** [comment]
Quick question. It may be a simpler implementation to have user download the dates already in the View Schedule view. I question why we need to go back to the db for a new date range. Just my two cents.

**Comment by Chingujo** [comment]
@sharonwarner 

I updated the mocks to reflect the new home page

@oscarAtNava 
That's a great point. When we designed this we weren't sure how far we are going back. So, if the user enters the hearing schedule page and just wanted to download, they can enter a date range. It's something that was requested as useful. This should be reflected in the user story. 

If we aren't storing that far back we could do something like this
![minimal download schedule](https://user-images.githubusercontent.com/23316107/43908839-f7ebd608-9bc6-11e8-96ca-83753b804ed9.png)

**Comment by MeredithStewart** [comment]
Will the download schedule output also reflect the filtering that has also been done in the UI? If it's not going to, then I think using one data range would be confusing, I would advocate for having the drop down date range specific to the download.

**Comment by MeredithStewart** [comment]
@Chingujo -- Change mock to reflect "Download current view" and we've made the decision to go with 1 date filter for view/download, giving users extra filter features with downloads.
