### ISSUE TITLE
Re-intake RAMP appeals so they are AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5958]
## Goals
- Allow users to search and find all AMA appeals (including RAMP appeals)

## AC
- Move RAMP appeals into the AMA appeal table, re-intake them so they can go through the intake flow for AMA appeals
- Add RAMP to the Type (e.g. AOD, CAVC)

## Notes 6/19
- RAMP data issues:
   - RAMP appeals are not mapped to the Veteran's disability profile.
   - Don't track any issue dispositions for RAMP EPs in Caseflow.
      - No way to know if an issue on an HLR EP has been granted or denied. VBA just closes the EP.
   - Caseflow creates contentions + EP --> VBA user goes to a rating portion --> creating a new rating issue
      - Caseflow is suggesting that for these contentions, they need to add a disposition
- Shane's idea: Translate RAMP appeal data to AMA data. If a RAMP election was completed, this will result in a rating. That rating will turn into AMA (so no RAMP appeals would go straight to AMA appeals)
- Shane's idea: Intake RAMP appeals

### Definitions
- Contention - Veteran thinks this is what they deserve
- Rating issue - What the Veteran ends up getting

**Comment by lowellrex** [comment]
When we re-intake these RAMP appeals we will need to create the root task of the task tree (how we will track work that needs to be done on an appeal post-VACOLS). We added a method to create the root task in PR #6689, so all that needs to be done is one call with an `Appeal` object that looks like `Task.create_root_task(appeal)`.

Let me know if there are any questions!

**Comment by laurjpeterson** [comment]
Re-intaking is in process! going to close this ticket.
