### ISSUE TITLE
Populate BEAAM direct reviews into appeal table

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5960]
BGS won't have the endpoint required in time for the BEAAM pilot to begin on 7/2, but the Board will need to begin working BEAAM direct reviews immediately. 

Attorneys and judges working BEAAM direct reviews need to search for and view BEAAM direct review appeals in Reader so the Board can begin working BEAAM appeals at the start of the pilot.

## AC
- Verify that BEAAM direct reviews exist in the appeal table
- Verify that users can search for BEAAM direct reviews in queue and reader (per: @mdbenjam this is already done)

## Notes 
- @abbyraskinUSDS will collect the BEAAM direct review Veteran IDs
- Will need to intake these post July 15th

**Comment by leahbannon** [comment]
Shane to do this with Sally or Kara for teaching

**Comment by abbyraskinUSDS** [comment]
Sent the 11 IDs to Shane on Lync.

**Comment by shanear** [comment]
running this script to populate them:

```
  fns = ['FILENUMBER1', 'FILENUMBER2']

  fns.each do |fn|
    Appeal.create!(
      veteran_file_number: fn,
      established_at: Time.zone.now,
      docket_type: "direct_review"
    )
  end
```

**Comment by shanear** [comment]
We'll run something like this to clean them up:
```
Appeal.where(receipt_date: nil).each { |a|
  a.appeal_views.delete_all
  a.delete
}
```
