### ISSUE TITLE
Editing AMA appeal issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5961]
Caseflow users across Intake and Queue will need to edit appeal data, especially issues.

We are talking about two separate things here:
1. Correcting mistakes - when the intake user made a mistake inputting data from the AMA NOD
2. Modifying/adding issues ("attorney magic") - when attorneys change issues regardless of what was on the AMA NOD to better reflect what the Veteran is appealing
    - Today, attorneys can even add brand new issues in this way

View definitions, user flows, and four scenarios on this [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1530197104426/ad25f0911c9e16551dbef41615fbd70c96c91f27)

View the progression of research and design in this [Mural room](https://app.mural.co/t/workqueue2001/r/1538145329940).

## Goals
- Require all Caseflow users to link issues, even modified issues, to prior VA decisions to ensure there is a connection all the way through
- To adhere to section 5 reporting requirements
- Allow attorneys to represent the issues Veterans are appealing, regardless of what the Veteran puts on the NOD

## Scenarios
1. Correct issues on appeals - "Checkbox":  Post-intake, users (likely VBA and BVA) need to add/remove which request issues to reflect which issues were on the Veteran's NOD.
2. Edit unknowns - "Unknown": Post-intake, users (likely VBA and BVA) can correct/add detail to a non-rated request issue that was categorized as "unknown".
3. Attorney magic - "Add": Post-intake, an attorney can add a decision issue to better reflect what the Veteran is appealing (while maintaining a link to a request issue).

## Design + development ownership
- Intake team is designing and developing scenarios about correcting request issues
- Queue team is designing and developing attorney magic

## User Stories

*Viewing Issues in Case Details: Attorneys (and all other BVA users)* 
- https://github.com/department-of-veterans-affairs/caseflow/issues/7957 - As an attorney, I want to see a veteran's request issues in Case Details as they are displayed in Caseflow intake so that I can understand what the veteran is appealing. - 
Two formats:
    - One field, a narrative description, like:
       - Service connection for Emphysema is granted with an evaluation of 100 percent effective June 1, 2013
       - Basic eligibility to Dependents' Educational Assistance is established from October 1, 2017
       - The claimant is not competent to handle disbursement of funds
       - Evaluation of right hip condition, which is currently 30 percent disabling, is increased to 40 percent effective February 15, 2018.
   - Two fields, for non-rated issues, `Issue category` and `Issue description`, like:
       - Dependency, Spouse seeking benefits
- As an attorney, I need to see the latest issues on appeal (including decision issues I've added) so that I can understand what's on appeal, how the issues have evolved (if applicable), and connections between request issues and new decision issues. 

*Adding Decision Issues*
- https://github.com/department-of-veterans-affairs/caseflow/issues/7958, https://github.com/department-of-veterans-affairs/caseflow/issues/7965 - **When attorneys are checking cases out to their judges**, they want to decide issues on appeal by adding decision issues. (This is where attorneys currently add decisions/dispositions for legacy cases, so we're repeating the pattern here.)
- https://github.com/department-of-veterans-affairs/caseflow/issues/7963 - As an attorney, I need to **add one or more decisions to each request issue** that the Veteran listed on their NOD, so that the decision I am drafting best reflects what the Veteran is appealing. We are defining a decision in this case to be an issue + disposition connected back to a request issue.
   - This includes staged ratings - As an attorney, I need the ability to indicate a staged rating in decision issues so that I can grant the veteran a particular rating for one time period and a different rating for another time period. Ex: 10% from Jan 2001-2005. 20% from 2005-2018. 
- As an attorney, I need the ability to select the Benefit Type when I am adding a decision issue. 
    - Acceptance criteria: 
       - When a user adds a decision, Caseflow pre-populates the same benefit type as the request issue. 

*"Merging" request issues one decision issue*
- As an attorney, I need the ability to add the same decision to another request issue to better reflect what the veteran is appealing. This is the scenario where two request issues align with one decision issue. 
    - Real life scenario from Rachel: I think the most common example would be psych. We get a two issue appeal - depression and PTSD, and we determine that the diagnosis is depression so we merge them.
  - Acceptance criteria: 
       - When a user adds a decision, they are only able to add the decision to request issues that don't already have a decision attached.
       - When a user adds a decision and all request issues already have decisions attached, we don't display the "issues" dropdown in the modal. 
- As an attorney, I need the ability to add more than one decision to two or more request issues. 
    - Example: The attorney adds the same decision (depression) to two request issues (depression and PTSD). They also need to add an additional decision to those issues (TDIU). 
    - Note: After the same decision has been added to multiple request issues, the attorney is unable to add decisions to individual request issues. They must add them to the group of request issues they've "merged". 

*Editing decision issues*
- https://github.com/department-of-veterans-affairs/caseflow/issues/7966 - As an attorney, I need the ability to **delete/remove a new decision issue** that I've added by mistake so that I can fix any accidental errors. 
  - Acceptance criteria: 
    - Removing the last decision from a group of two or more request issues "un-merges" the request issues. Issues are displayed as two separate issues on the attorney checkout page. 
- https://github.com/department-of-veterans-affairs/caseflow/issues/7966 - As an attorney, I need the ability to **edit a new decision issue** that I've created so that I can fix any accidental errors. 
- As an attorney, I need the ability to remove a decision from 2 or more contested issues after I've already added a decision (in case I make an error). 
- As an attorney, I need the ability to add the decision to additional contested issues after I've already added the decision (in case I make an error). 
    - Acceptance criteria: 
       - Display request "issues" in the drop down that don't have a decision added to them. 

*Connecting Decision Issues to Request Issues*
Note: Depending on how the designs evolve, attorneys may not need to manually connect issues, and we can do it for them. TBD. 
- As an attorney, I need to connect new decision issues to request issues so that I can ensure that the Board meet their AMA reporting requirements. 
  - Acceptance criteria: 
    - Users are only able to connect new issues to request issues. New decision issues are not presented in the list. 
- As an attorney, I need the ability to edit the connection between request issues and new decision issues I've added so that I can fix any human error or connections I made by mistake.

*Correcting Clerical Errors* 
- https://github.com/department-of-veterans-affairs/caseflow/issues/7920 - When attorneys are viewing issues in Case details and they recognize that issues listed are not what the Veteran listed on the NOD, they need to fix those mistakes from the Case details page. They need the ability to fix clerical mistakes made by Intake so that I can accurately reflect what the veteran is appealing. (uses the flow already developed by the Intake team)
- As an attorney, I need the ability to select the correct request issues if Intake could not determine which issues to select. 

### Open Questions
~- How should VBA users edit issues? How is it different than how attorneys can edit issues?~
~- How do attorneys edit issues today? Will they understand the concept of request and decision issues?~
- Technical questions to be tracked in this issue - https://github.com/department-of-veterans-affairs/caseflow/issues/6246
    - Are we using the same fields as VACOLS (e.g. program, issue, levels 1-3) in the future?

**Comment by mkhandekar** [comment]
👀

**Comment by amprokop** [comment]
> How do we differentiate correcting mistakes versus "legal magic"?

One thought is that the difference is process. It's possible that we'd want to "re-intake" appeals if there are truly mistakes/errors on the NOD. I believe @shanear @abbyraskinUSDS are already thinking about this flow, so it might be part of Intake. In this case, the request issues might change. In the "legal magic" case, however, attorneys would create review issues in Queue that need to be linked to request issues.

On the other hand, I don't have full understanding of why we'd truly *need* to differentiate the two. Would like to see a strong case for that before we embark on making two flows.

**Comment by laurjpeterson** [comment]
@sneha-pai @mkhandekar @abbyraskinUSDS @leahbannon @suzchap @shanear @mdbenjam @amprokop @allyceh - check out the updates to the Mural. 
1. I tried to make the Mural easier to follow by labeling sections
2. I incorporated Abby's high level user flow and clearly delineated intake and post-intake actions
3. I devoted a section to all four scenarios

I hope this is more clear, so we can begin to sketch out flows for both intake and queue, and answer open questions this sprint. 

The graveyard section below contains notes and former diagrams, if they were useful to you.

**Comment by mdbenjam** [comment]
I see three main approaches to storing issues:

1) Maintain VACOLS levels - In this approach we keep things exactly how VACOLS does them. The downside is that a user needs to translate what a Veteran is appealing into VACOLS data.
2) Have some basic structure - In this approach we have basic levels probably business line, maybe an issue (increased rating), and diagnostic code. We can either present this in the same tiered approach VACOLS does right now, or we could through them all into a giant searchable dropdown. Attorneys will still need to create the leveled data from what the Veteran is appealing. However, we might be able to automate some of this by looking at key phrases from what VBA adjudicated.
3) Provide a free text field - In this approach we just copy the request issue into the decision issue. There is no structure here besides the diagnostic code which we will still maintain.

**Comment by shanear** [comment]
I think we will almost certainly want to do 2 or 3, unless the Board is realllllllly attached to the VACOLS levels system.
 
I have some comments on some of the assertions you made in those:

> Attorneys will still need to create the leveled data from what the Veteran is appealing.

Maybe not, we can dig a good amount of the info about the issue from BGS, such as the diagnostic code from BGS if its a disability issue.

> In this approach we just copy the request issue into the decision issue. 

I don't think we'd want to copy anything, since it doesn't make since in a lot of cases. Just have the attorneys write the decision issues in connected to the appropriate request issue.

**Comment by laurjpeterson** [comment]
Another reference - Intake team started the discussion around what structured data we coul duse for rated issues. https://github.com/department-of-veterans-affairs/appeals-design-research/issues/835

**Comment by mkhandekar** [comment]
This is a cross-post of my [slack message](https://dsva.slack.com/archives/C754H751T/p1533910673000050), with some additional context, so that we are also tracking on github:

I / Queue team are trying to understand what data Intake team has so that we might surface separate fields for each piece of data in Case Details, and make it possible for users to edit it.

- I met with @suzchap re: how adding/editing issues works in intake-land (thank you!)
- There were a few threads with Q & A & discussion re: the types of data y'all have about issues. 
  - [July 25th, asking how Intake gathers what the Veteran wrote on the NOD](https://dsva.slack.com/archives/C754H751T/p1532549578000049)
  - [Aug 7, asking about issue description](https://dsva.slack.com/archives/C754H751T/p1533648928000220)
  - [Aug 7, code snippet for rating issues](https://dsva.slack.com/archives/C754H751T/p1533675824000122)
  - [Aug 7, code snippet for disability issues](https://dsva.slack.com/archives/C754H751T/p1533676304000293)

Using that info, LP and I put together our understanding (so far): [**Edit AMA issues mural**](https://app.mural.co/invitation/mural/workqueue2001/1533216145387?sender=meghana7585&key=f4a85826-521b-4176-a52f-6a56e01110c9)

@shanear, @mdbenjam and any other intake teammates who would have additional insight -- can y'all hop in there, poke holes, answer some of our questions and help round out our understanding of the breadth of data you have?

You'll help us move forward with a couple of ideas we have about how editing can work in case details!

**Comment by laurjpeterson** [comment]
Progress update:
- Scenarios 1 and 2: Intake designs in this [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537795938997/f5834747503f5a248340b9f3426fbac652812400)
- Scenarios 3 and 4: Queue prototypes in this [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537369023440/f8fafbe08dd07a43d270af0d9b26851fd175eab5)

**Comment by laurjpeterson** [comment]
@allyceh is taking over this work! this week, we discussed:
- Phase 1: allowing attorneys (or other users) to correct issues by re-using as much of the Caseflow Intake edit/correct issues designs as possible
- Phase 2: allowing attorney magic editing

**Comment by shanear** [comment]
>As an attorney, I need to add a decision issue to the veteran's appeal so that the decision I am drafting reflects what's in Caseflow.
> As an attorney, I need to add a decision issue to the veteran's appeal when I am checking the case out to my judge so that the decision best reflects what they're appealing.

Not sure what is different about these two

**Comment by shanear** [comment]
It looks like you have adding and connecting as two separate stories. I was thinking it might be easiest to add a decision already connected to a request issue? This way you don't have to worry about the complexity of connecting after the fact.

**Comment by allyceh** [comment]
Note: we've been updating user stories/requirements in the original ticket above on an ongoing basis. Refer to the User Stories section for all of the latest.

**Comment by laurjpeterson** [comment]
DONE!
