### ISSUE TITLE
Define what "release notes" look like

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#597]
We have the "What's new" page. We should decide

- What do the notes on this page contain?
- How often/when do we add new release notes?

**Comment by KHarshawat** [comment]
Related: #553 and #561

**Comment by orischwartz** [comment]
These should follow conventions you see in most mobile app updates:

* Phrased in the user's language, no technical jargon beyond "bug fixes to improve stability".
* Briefly describe new features and why they're beneficial

Simplest approach is to have a markup file that we update manually, then incorporate into dropdown menu as prototyped by @webinista in #556.

I'll take a stab at porting into caseflow-certifications project.

**Comment by orischwartz** [comment]
Closed by https://github.com/department-of-veterans-affairs/caseflow-certification/pull/25
