### ISSUE TITLE
Dropdown button

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#5983]
AC:
- Update DropdownMenu.jsx in the frontend-toolkit to allow button styling (primary and secondary)
- Update the node-module in Caseflow
- Add the dropdown button to the styleguide

![dropdownbutton](https://user-images.githubusercontent.com/4306128/41726241-b724899c-753f-11e8-9f2d-f473ed35d222.png)

**Comment by nolawi** [comment]
So looking at this ticket what is proposed is that we make the dropdown menu look like a button as a secondary option.
<img width="483" alt="screen shot 2018-06-21 at 2 04 49 pm" src="https://user-images.githubusercontent.com/1745984/41737058-2e5e040e-755c-11e8-81f2-4b6ee1b2ad51.png">
 
But most of the styles will be inherited a button. The dropdown menu is already very complex with `searchable ` option as well. 

I think it might be better to create a new dropdown button component that inherits the button but has an arrow and options as the current dropdown menu is very complex already. LMK

**Comment by sharonwarner** [comment]
I'm fine with either approach, but I meant the DropdownMenu component. It's the one we use in the navigation bar to login/logout. It's not nearly as complicated as the SearchableDropdown you're describing.
