### ISSUE TITLE
Add decision date for non-rated issues

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5991]
CAs will need to enter the last decision date for each non-rated issue, so these issues can be tracked for timeliness. This story covers the component for adding the date, but does not handle the timeliness validation.

## Acceptance Criteria
- Issue category and issue description are mandatory fields
- A date picker field with the label "Decision date" is present when adding a new non-rated issue
- This field is mandatory, unless it's an uncategorized issue
- Uncategorized issues do not require a decision date 

## Design
![image](https://user-images.githubusercontent.com/4042181/42457669-0a9bfb3a-8366-11e8-9d1e-b38f30fb6990.png)

**Comment by leahbannon** [comment]
note - we need to also write a story for checking timeliness

**Comment by leahbannon** [comment]
pair with Sally on this! :)

**Comment by suzchap** [comment]
I've needed to make some adjustments on this to accommodate issues around editing issues... so hold off on this until I can update this ticket. Please and thank you :)

**Comment by kahlouie** [comment]
@suzchap noted.

**Comment by suzchap** [comment]
Ok, sounds like y'all should just move forward with this issue as-is... just keep in mind we'll be rearranging the fields and adding the remove issue in a later issue. Thanks!

**Comment by kahlouie** [comment]
The current work as is in prod behind the intakeAma toggle allows users to submit a decision date that's not complete, like `03/` as the date. We'll need to fix that before continuing forward.

**Comment by kahlouie** [comment]
@suzchap Looks like if decision date is required, there's a weird formatting issue that occurs. Would you like us to add space to decisionDate so that it has room for the `Required` or would you like to move Required label on all sections to a different place?
![Screen Shot 2018-07-31 at 2.02.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0329701e56750012d0676e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246457f26b7191a37af112294f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19041c95df548e14a56a4113162e57e2431.png)

**Comment by suzchap** [comment]
We're actually going to remove the required label moving forward. We may introduce an "optional" label at some point but not yet. Does that fully fix your problem?

**Comment by kahlouie** [comment]
Yes. Thanks @suzchap I'll leave it as is until we get to that story.

**Comment by suzchap** [comment]
I tried to submit with only Issue Category selected and didn't get the in-line... I got this:
![Screen Shot 2018-08-08 at 1.16.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57758753a582050e0017b00d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454fb6b7191a379f1132d4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19041c95df548e6495da21b3263e5742431.png)

**Comment by kahlouie** [comment]
Hmmm, I wonder if you get the same if only issue description is filled out.

**Comment by leikkisa** [comment]
@kara I think she's talking about the CSS placement, how they're on top of each other instead of side-by-side

**Comment by suzchap** [comment]
No, I just missed a few words in my previous comment... I don't get an "in-line error" that explains that the missing field is required... and instead I only get the "something went wrong" alert message.

I'm not worried about the fields lining up horizontally for this ticket (tho we should fix that at some point)

**Comment by kahlouie** [comment]
@suzchap to update the acceptance criteria (although she's already validated it prior).

**Comment by suzchap** [comment]
Removed from AC because it's technically complex and may be moot since we're redesigning this page. New ticket #6714 to remind us to revisit.

> - If a user does not enter a date, an in-line error is displayed that says the field is required (follow pattern of issue category and description)

**Comment by suzchap** [comment]
Validated.
