### ISSUE TITLE
Limit how long a user can hold onto a RAMP intake

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5994]
Currently you can hold onto a case forever, so if you go on vacation (or quit) no one else can process the form in intake, which is not ideal.

## Acceptance Criteria
- If a user has not completed an intake within a day, the intake is "released " so other users can process it
- This rule should apply to RAMP elections and refilings, as well as AMA reviews

## To Validate
- Start an intake (any type) with one user for a veteran
- Attempt to start an intake of the same type for the same veteran that day (it should say it is currently being worked on)
- Wait one day, and attempt to start an intake of the same type for the same veteran again. It should work this time

**Comment by kahlouie** [comment]
One day, "release" intake when a user is searching for the veteran to start a new intake for that same veteran.

**Comment by leikkisa** [comment]
@leahbannon 
Note: Validate this before this 4064, because then you'll be able to use the same file number

Test ID: 561349911
Choose supplemental claim

**Comment by suzchap** [comment]
Validation part 1:
I started a SC for the test id ^.... 

I started the claim with caseflow test user CF_Q_283 and then using caseflow test user CF_KIRK_283, I tried to start a SC for the same test veteran ID and successfully got the message "TEST ONE already started processing this form We noticed that TEST ONE may be in the middle of processing the same form for this Veteran in Caseflow. Please confirm they will complete this intake, then move on to the next mail item."

Will do validation part 2 tomorrow (and then #4064 )

**Comment by suzchap** [comment]
Validation part 2: I returned 25 hrs later, again as CF_KIRK_283 and tried to start intake for this test user --- and was able to just fine. Validation complete.
