### ISSUE TITLE
RAMP elections | Add a placeholder contention if an additional opt-in is received

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6003]
If an opt-in is pending, add a contention to the EP to alert VSRs to the new RAMP review if a RAMP review (EP) is already pending.

## Acceptance Criteria
- If an additional RAMP opt-in is processed while one is already pending in the system, add a contention with the text "Secondary election" to the pending EP

**Comment by shanear** [comment]
Deprioritizing this since AMO doesn't seem to care about it

**Comment by abbyraskinUSDS** [comment]
Closing this - deprioritized indefinitely (can reopen if AMO deems necessary)
