### ISSUE TITLE
Case details | make Veteran ID copy-able

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6004]
Case details includes the Veteran ID prominently next to the Veteran name. We've learned that users often copy and paste it to do their work. Let's use / upgrade if needed the copy-able functionality already available elsewhere in Caseflow, and translate that for case details. 

## Case details (current)
![image](https://user-images.githubusercontent.com/1598889/40918784-5ad1fb6a-67d5-11e8-8bd7-68332104bdc0.png)

## Copy-able Veteran ID (for reference)
<img width="143" alt="screen shot 2018-05-22 at 2 57 03 pm" src="https://user-images.githubusercontent.com/27704093/40798717-b524341a-64d9-11e8-827e-5219842e91c2.png">

## To do:

- [ ] design a slimmer, more appropriate copy-able text / button for the Veteran ID

**Comment by mkhandekar** [comment]
@amprokop do you know who worked on the copy-able Veteran ID component?  I'd love to see if we can update it with something like this. Or if it would be ok to develop a slightly alternative version for Queue. The changes include a hover state with a tooltip telling users of what to expect and Veteran ID label to the left instead of above (like the reference image in the original comment ^).

## Copy-able Veteran ID [normal]
<img width="752" alt="screenshot 2018-07-09 20 32 05" src="https://user-images.githubusercontent.com/1598889/42487786-73557b46-83b7-11e8-93da-7dbe18a3086f.png">

## Copy-able Veteran ID [hover]
<img width="751" alt="screenshot 2018-07-09 20 32 20" src="https://user-images.githubusercontent.com/1598889/42487787-736e379e-83b7-11e8-8118-d06ea73e92f3.png">

cc: @laurjpeterson

**Comment by laurjpeterson** [comment]
@lowellrex implemented this last week, closing
