### ISSUE TITLE
Case details | define what "case status" means and how it's displayed

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6005]
We'll need to define what case status means for cases for each user, and then experiment with how we display that status to users within case details:

1. if the case has not arrived at a disposition, what phase is it in?
    - not assigned / new
    - in progress / pending action
    - on hold
2. if the case has a disposition:
    - what is it? (show in place of 1 ^ )
3. if the case has had a hearing
    - don't think this is important for case snapshot area. check with users. can we include this within the hearings section? 

---

4. another detail to add is the date when a case was assigned to the person it is currently with
    - within _about the case_ section, add a line — "date assigned to [first name] - [date]"
    - or, somehow attached to, on hover / click, or in line with 1. the phase
    - or, within _case information_ section, add a line below _assigned to_ — "date assigned to [first name] - [date]"

**Comment by laurjpeterson** [comment]
We can also consider what language to use here. We have Appeals Status, which shows the status of the appeal in the appeals process.

We also have a `Status` column in Search results, which tells us if the appeal has been certified (Advance / ADV (Cert)), activated (Active / ACT), in history status (History / HIS), has been remanded (Remand / REM), and if there is a motion (Motion / MOT).

Original designs for Search Results [here](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/707).
