### ISSUE TITLE
Allow attorneys to view multiple admin actions in their table

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6014]
When an attorney assigned multiple admin actions for the same case, VLJ support users need to see both of those admin actions in my table so I have context before I start working on them.

**Comment by mkhandekar** [comment]
Handing off to @sneha-pai + @allyceh who will talk with @mdbenjam to get an update on any new multiple admin work, then prioritize with guidance from @laurjpeterson ❤️(per conversation on Oct 10)

**Comment by lowellrex** [comment]
@laurjpeterson @sneha-pai I'm combing through some old issues and am a little confused about what the problem here is. Is it that an attorney might have two different tasks related to the same appeal at once, and we would like to display those as distinct rows in their queue table?

**Comment by laurjpeterson** [comment]
This is related just to the `On hold` tab, when we have it. If an attorney assigns co-located two admin actions, then the attorneys should see both of those admin actions listed on the `On hold` tab.

**Comment by laurjpeterson** [comment]
We can already do this, so closing.
