### ISSUE TITLE
Display all tasks in case details/queue table if multiple tasks are assigned to you for a single case

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6015]
As a co-located staff member — when an attorney assigns multiple admin actions for the same case, I need to see both of those admin actions in Case details/Case snapshot so I have context before I start working on them.

## Acceptance criteria
When multiple tasks are assigned to you for the same case:
* [ ] Display multiple tasks in queue table
* [ ] Display multiple tasks in the case details view

**Comment by mkhandekar** [comment]
### Multiple admin actions in a colocated admin's "new" tab

![image](https://user-images.githubusercontent.com/1598889/42888486-6027fbaa-8a76-11e8-9046-453d158a621c.png)
 
### Multiple admin actions in a colocated admin's case snapshot
to add

**Comment by laurjpeterson** [comment]
@mkhandekar - i moved this back to backlog - unprioritized issues because it is out of scope for our first release/pilot with co-located

**Comment by mdbenjam** [comment]
Do we need the `assigned to` field? If we're showing them a task, it must be assigned to them right? (Or maybe the organization they belong to)

**Comment by mkhandekar** [comment]
Yes! You are totally right @mdbenjam! No need for `assigned to` field for co-located staff.

Tagging @sneha-pai who actually did this work <3 (I just posted 'em!)

Sneha, I remember talking about showing the `assigned to` to all other users as a way to increase transparency around whose court the case is in at any given time. Do you remember this as well?

**Comment by mkhandekar** [comment]
Handing off to @sneha-pai + @allyceh who will talk with @mdbenjam to get an update on any new multiple admin work, then prioritize with guidance from @laurjpeterson ❤️(per conversation on Oct 10)

**Comment by laurjpeterson** [comment]
We do this! We could enhance this by grouping tasks together in a more obvious way, but closing because we've hit the min. AC
