### ISSUE TITLE
Translate existing designs to new grids

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6022]
- we have new grids! (to add link to it and give context)
- we'll want to test out the grids by translating our all our existing designs to this grid. but to start with, we'll be designing:  
  - [x] table @sneha-pai 
  - [x] a couple check out screens @sneha-pai 
  - [ ] case details @mkhandekar
  - [ ] judge evaluation (this is slightly more complex than other check out screens, so we want to establish breakpoints / responsiveness behavior on this one) @mkhandekar

**Comment by mkhandekar** [comment]
## 768 px
To add info about widths and gutters

![screenshot 2018-07-16 12 52 01](https://user-images.githubusercontent.com/1598889/42772034-2228f014-88f7-11e8-898c-b95904d14e17.png)

## 1200 px
To add info about widths and gutters

![screenshot 2018-07-16 12 52 12](https://user-images.githubusercontent.com/1598889/42772042-23fbf9fe-88f7-11e8-8c2e-7beb5763ba0e.png)

**Comment by mkhandekar** [comment]
## Table - 768 px

![image](https://user-images.githubusercontent.com/1598889/42772139-7a7f620c-88f7-11e8-8ff4-cac2ae81fd7c.png)

## Table - 1200 px

![image](https://user-images.githubusercontent.com/1598889/42772161-8dbe04a4-88f7-11e8-8839-99d15c5396f0.png)

**Comment by mkhandekar** [comment]
## Checkout - attorney assigning to colocated - 768 px

![image](https://user-images.githubusercontent.com/1598889/42772192-b8c4cd86-88f7-11e8-9647-46e12d3f2ca1.png)

**Comment by mkhandekar** [comment]
## Case details - 768 px

![image](https://user-images.githubusercontent.com/1598889/42772397-4c5eb7b4-88f8-11e8-8c17-d5014316502c.png)

## Case details - 1200 px
to add

**Comment by mkhandekar** [comment]
Handing off to @sneha-pai + @allyceh who will prioritize with guidance from @laurjpeterson ❤️(per conversation on Oct 10)

**Comment by allyceh** [comment]
Closing this out. We use the grid template now :)
