### ISSUE TITLE
Spreadsheet Validation | Allow ROs to have no non-availability dates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6027]
When filling out the RO non-availability spreadsheet, the hearing coordinators will put "N/A" under each RO that has no non-availability dates.

AC:
- When validating the RO non-availability dates, allow the date field to either be a date or "N/A"
- When importing the RO non-availability dates, skip the entries that have "N/A" as the date

**Comment by MeredithStewart** [comment]
@sharonwarner - Can we also add this validation for Board non-availability dates? There would always likely be some (for fed holidays), but it is possible that there wouldn't be any if the timeframe was shorter.  

Do we need to update the spreadsheets to indicate the n/a options?

**Comment by sharonwarner** [comment]
I'll add a second ticket for the board non-availability dates. I don't know Excel very well, but I think we could add 'N/A' as an option for the row right below the ROs.
