### ISSUE TITLE
Add more tests for Form8PdfService

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#603]
The spec is pretty barren. We should unit test more of this. In general, if it's possible to unit test services, we should do that.

**Comment by kierachell** [comment]
There are additional pdf_service tests in `models` for some reason;
will move/refactor those to services

**Comment by kierachell** [comment]
So uh, to validated this.
@amprokop is to blame 'cause he wanted this. :D

**Comment by amprokop** [comment]
Looked at the PR. Rad. Thanks. Validated.
