### ISSUE TITLE
Document EFolder Labels used

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#603]
We need to document and put information into the help page on what the exact lables we're using are.

We currently have the integers, we should make sure the human text on the eFolder matches our docs.

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/e_folder/case.rb#L5-L15

**Comment by gmorgana-va** [comment]
Key Labels: 

- SOC_DOC_TYPE_ID = 95; Label: Statement of Case (SOC)
- NOD_DOC_TYPE_ID = 73; Label: Notice of Disagreement
- SSOC_DOC_TYPE_ID = 97; Label: Supplemental Statement of Case (SSOC)
- FORM_9_DOC_TYPE_ID = 179; Label: VA 9 Appeal to Board of Appeals

**Comment by KHarshawat** [comment]
@gmorgana-va can this be closed?

**Comment by gmorgana-va** [comment]
:+1:  Tracking inclusion of this information in help content via https://github.com/department-of-veterans-affairs/caseflow/issues/547#issuecomment-186368399
