### ISSUE TITLE
Case details | Attorney assignment to co-located admin support

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6031]
When an attorney is reviewing a Veteran's claims folder and identifies that an admin action needs to be done, they need a way to assign it to co-located support, so the admin action can be completed while the attorney works on another case. 

## AC
- Verify that the attorney has another option in their case details dropdown to`Add admin action`
- Verify this is behind another feature flag

### Case Details (snapshot area)
_mock to be placed_

**Comment by sneha-pai** [comment]
closing as this is redundant with #5438
