### ISSUE TITLE
Assign | Attorney assign admin action screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6032]
- When an attorney is assigning an admin action, they need to choose the type of admin action they are assigning, so co-located knows what their task is.
- If a case requires more than one admin action, the attorney needs to be able to choose more than one. 
- When an attorney is assigning an admin action, they need to explain instructions for the task, so co-located knows how to execute on that task.

## AC
- Verify that a new screen is created titled `Assign admin action` (to verify page title per designs)
- Verify the user can select one or more admin actions from the list:
   - IHP
   - Waiver of AOJ letter
   - Arneson letter
   - Hearing clarification letter
   - POA clarification letter
   - Unaccredited representative letter
   - Retired VLJ letter
   - New rep arguments (PT_VSO) letter
   - Extension request ruling
   - Missing hearing transcript
   - Schedule hearing
   - FOIA/Privacy Act request
   - Pending scanning banner VBMS
   - Missing records in file
   - Address verification
   - Other
- Verify the user can see the case is being assigned to co-located (but they cannot see the individual user being assigned)
- Verify the user can type in instructions for the admin action task
- Ensure that all copy is in the COPY.json file
- Verify when the user submits this assignment, the case is auto-assigned to a co-located user per https://github.com/department-of-veterans-affairs/caseflow/issues/5982
   - Note: for the first release of this functionality, cases will only be assigned to two co-located users - Randy Seay and Eugene Scott

## Mocks
@sneha-pai to add

**Comment by sneha-pai** [comment]
closing issue as this is redundant with #5439
