### ISSUE TITLE
Attorney assigned admin action confirmation screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6033]
When an attorney has assigned an admin action, they want confirmation the case has been moved off their plate to the co-located admin support team and to return to their queue to continue working on other cases.

## AC
- Verify that the user is taken back to their queue table after assigning an admin action
- Verify the Confirmation banner and message appears per designs

## Mocks
@sneha-pai to add

**Comment by dannysellers** [comment]
Closing, dupe of #5440
