### ISSUE TITLE
Mark BEAAM appeals in case search results

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6041]
Users should be able to see that an appeal is BEEAM in the case search results page.

![image](https://user-images.githubusercontent.com/3781835/42034937-96f98242-7aaf-11e8-8e27-ad20d394b548.png)

# AC
- For BEAAM appeals, add `BEAAM` in the type field with AOD and CAVC

**Comment by laurjpeterson** [comment]
@mdbenjam has already implemented this! closing.
