### ISSUE TITLE
Turn on BEAAM appeals feature toggle for special counsel

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6050]
The following special counsel have been assigned to work BEAAM appeals. They need access to `queue_beaam_appeals`.

Name | CSS ID | Email |
---|---|---
Anderson, Kalisse | bvakanderson | Kalisse.Anderson@va.gov
MacDonald, Andrea | bvaamacdonald | Andrea.MacDonald2@va.gov
Armstrong, Anna | bvaaarmstrong | Anna.Armstrong@va.gov
Casey, Theo | bvatcasey | Theophilus.Casey@va.gov
Caylor, Marissa | bvamcaylor | Marissa.Caylor@va.gov
Costello, Rachel | bvarcostello | Rachel.Costello@va.gov
Coyne, Marcella | bvamcoyne | Marcella.Coyne@va.gov
Grace Smart, Devon | bvadremcar | Devon.Rembert-Carroll@va.gov
Haddock, Amanda | bvaahaddock | Amanda.Haddock@va.gov
McCabe, Luke | bvalmccabe | Luke.McCabe@va.gov
Mills, Martina | bvammills | Martina.Mills@va.gov
Nichols, Jane | bvajnichols| Jane.Nichols5@va.gov
Sauter, Rachel | bvarsauter | Rachel.Sauter@va.gov
Skowronski, William | vacoskowrw | William.Skowronski@va.gov
Sorathia, Sadia | bvassorathia | Sadia.Sorathia@va.gov
Tamlyn, Emily | bvaetamlyn | Emily.Tamlyn@va.gov
Walker, M. Scott | bvamwalker | M.Scott.Walker@va.gov
Ware, Dustin | bvadware | Dustin.Ware@va.gov
Wendell, Christopher | bvacwendell | Christopher.Wendell@va.gov
Wheatley, Christa | bvacsfields | Christa.Fields@va.gov
Yasui, Lynne | bvalyasui | Lynne.Yasui@va.gov
Spector, Amanda | bvaaspector | Amanda.Spector@va.gov
Stepanick, Laura | bvalstepanick | Laura.Stepanick@va.gov

## AC
- Feature toggle `queue_beaam_appeals` has been turned on for the above CSS ids

**Comment by mdbenjam** [comment]
I added these users as well as Chris, Me, Alex, and Lauren.
