### ISSUE TITLE
Ruby upgrade sanity check

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#6067]
Tests should include users with permission and no permissions. Also, positive tests (when user has permission) should be using at least two different sessions.
All apps should try to submit feedback.

**Team leads are encouraged to modify/make additions to the existing plan.**

- Certification:

New

Missing docs

Already certified

VBMS Error

Unable to certify

- Reader:

Communication with eX works

Welcome Gate

Document List

- Dispatch:

Work History

Work Assignments

Missing Decisions

Oldest Unassigned Tasks

- Hearing Prep:

Upcoming Days

- Intake:

Start

- Queue:

< Foxtrot team members should provide input here >

**Comment by shanear** [comment]
This was completed
