### ISSUE TITLE
Upgrade Ruby 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#6068]
Caseflow team will upgrade Ruby from current 2.2.4 version to the latest stable version 2.5.1
Release notes for Ruby 2.5 can be found here: https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/
Ruby upgrade should include security fixes and upgrades, it should bring some performance gains and overall reliability. 
Also, it will keep our ruby ecosystem up to date and easier to maintain. Beside that, all support of the Ruby 2.2 series has ended. 

Once everything installed, with a passing test suite and no deprecation warnings, 
Ruby upgrade should be deployed and tested in UAT as separate branch
After successful sanity check in UAT, it should be deployed to Production during after-business hours. 

Guideline for sanity checks:
https://github.com/department-of-veterans-affairs/caseflow/issues/6067

**Comment by ferlatte** [comment]
I admit, I don't know much about the production environment setup. Does it honor .ruby-version automatically? I don't believe that CircleCI does; we'll need to make a new base container with the appropriate version and deploy it when we want to commit to 2.5.1.

Does it make sense to get CircleCI running our tests using both Ruby versions during the transition period? It looks like that's possible with rbenv and may be worth doing so that we can keep future Ruby upgrades easy.

**Comment by nemodjuric** [comment]
Yes, our production environment does ruby-version-lookup where it looks into .ruby_version, then ruby-existence-check to see if that version is installed, and then if it's not it runs ansible role called ruby which includes installation of set default ruby version. 
Running both versions of Ruby makes sense, I'm eager to see how will it work in practice. Would there be two separate builds using different containers? Just curious - what about approach to have CircleCI read .ruby-version file similar to what we do in production environment setup?

**Comment by ferlatte** [comment]
I think we can make the CircleCI environment honor .ruby-version without it being too painful; that seems like a good thing to do regardless.

I'd need to see what CircleCI 2.0 provides now for multiple versions; I know they have support for parallel builds using different base containers when they added workflow support, which might do the trick.

**Comment by ferlatte** [comment]
Nemo and I chatted this morning and have a plan for getting CircleCI to honor .ruby-version. I'm going to do some exploratory work on the Caseflow CircleCI container tomorrow morning and see if I can get something working. We aren't going to setup parallel test runs with multiple Rubies for the time being.

**Comment by shanear** [comment]
closing this since its upgraded in prod. @enriquemanuel will be handling fixing CI
