### ISSUE TITLE
Demo Environment User Seeds

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#607]
As a Developer, I want to make sure our development/testing environment seeds resemble production as close as possible:

For that we need to change some of the seeded users and tasks:
<img width="907" alt="screen shot 2016-12-28 at 11 05 12" src="https://cloud.githubusercontent.com/assets/18075411/21525794/89e93528-cced-11e6-8696-90df72a9a293.png">

1. Rename the users based on their role the way _Establish Claim_ and _Ceritfy Appeal_ are named (e.g. _Anne Merica_ -> _Guest User_ ?); to clarify: sometimes specifications about features or bugs come in the form "As a Caseworker..." or "As a System Admin..." - it would be beneficial to have seeded users follow the same naming convention.
Ask @nikitarockz if you need clarification about how specifications come in.

<img width="555" alt="screen shot 2016-12-28 at 11 19 01" src="https://cloud.githubusercontent.com/assets/18075411/21526138/f6197800-ccef-11e6-88be-5b18cc5af51e.png">

2. Set 2+ users for each role; with different parameters; this will help with checking for edge cases (collisions, etc).

3. Change the FakeDecisionDocument to resemble actual real-life data.
[SampleIRDecisionGrant.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/678968/SampleIRDecisionGrant.pdf)

**Comment by kierachell** [comment]
Here's an mockup with a few changes to the seeds and view for dev_users (on my local setup)

<img width="907" alt="screen shot 2016-12-28 at 22 14 29" src="https://cloud.githubusercontent.com/assets/18075411/21536019/1fe2756e-cd4b-11e6-8c23-1fa7d647189e.png">


This way it's easy to confirm which Caseworker worked on which task.

<img width="1011" alt="screen shot 2016-12-28 at 22 16 32" src="https://cloud.githubusercontent.com/assets/18075411/21536047/5fc4c916-cd4b-11e6-873b-aa415a96f6cc.png">

**Comment by kierachell** [comment]
Relevant check found:
- ```verify_authentication``` does not happen for dispatch/establish_claim; so users with multiple ROs still have acess

**Comment by kierachell** [comment]
Here's the changes I made so far to make tests easier:
Station ID 316 maps to multiple ROs
<img width="954" alt="screen shot 2016-12-29 at 10 13 06" src="https://cloud.githubusercontent.com/assets/18075411/21567173/f6fbf0e8-ce77-11e6-8ba1-b471e7b3f70a.png">
added certification routes for quick manual checks

**Comment by kierachell** [comment]
I am not seeing the updated PDF (actual sanitized version) in **Review Decision** on `demo`  - are there separate ones being served/cached somewhere else?

next up - add different PDFs to serve;
refactor tasks/appeals to utilize new `type` property

**Comment by astewarttistatech** [comment]
@shanear You would probably be the best person to answer @kierachell 's question. 

Other than that this ticket looks great in dev, has additional roles and Anne Merica will never go away it seems.   @kierachell  can you confirm these were intended since they go against the mock? 


<img width="853" alt="screen shot 2017-01-09 at 9 59 00 am" src="https://cloud.githubusercontent.com/assets/23038505/21770681/4acf1eca-d652-11e6-9a0a-54313163937c.png">

**Comment by astewarttistatech** [comment]
Based on my conversation with @kierachell the changes made are indeed correct. Moving this ticket to closed. 

**PASSED**
