### ISSUE TITLE
Attorney and Judge Assignment for AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6070]
Currently, we rely on DAS assignments for attorney and judge case assignment. Since AMA appeals will not live in VACOLS, only Caseflow, we need to change attorney and judge assignment to our Task model for AMA appeals. 

## Out of scope
- Task model for legacy appeals
- Auto-case distribution

## Stories
- Judges can complete the assignment flow with an AMA appeal.
https://github.com/department-of-veterans-affairs/caseflow/issues/6311 **Done**
https://github.com/department-of-veterans-affairs/caseflow/issues/6340 **Done**
https://github.com/department-of-veterans-affairs/caseflow/issues/6309  **Done**
https://github.com/department-of-veterans-affairs/caseflow/issues/6312 **Done**
- Attorneys can complete the check out flow for AMA appeals
   - Attorneys can enter issue dispositions for AMA appeals #6493 **Done**
   - This requires an update to the attorney check out flow - remand reasons page - https://github.com/department-of-veterans-affairs/caseflow/issues/5760
- Judges can complete the check out flow with an AMA appeal #6581 **Done**
   - Judges can review issue dispositions for AMA appeals **Done**
   - This also requires an update to the remand reasons page **Done**
   - Judges can evaluate attorneys for AMA appeals **Done**
- Judges and attorneys can view both AMA and legacy appeals in their queues. **Done**

**Comment by amprokop** [comment]
We should potentially add to the seed functions first — we should create AMA appeals locally and assign them to judges.
