### ISSUE TITLE
Co-located table | New tab

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6078]
As a co-located user, I want to distinguish which cases and tasks are newly assigned to me, from those on hold or those that are pending action to come off of hold. 

## AC
- Establish the 'New' tab
- Verify newly assigned case and tasks exist in the co-located table in the new tab

### User Stories
- When a co-located team member is planning what to work on, they need to see all tasks assigned to them (mail, VACOLS, 3230s, etc.) in one place, so they can prioritize what to work on.
  - These tasks include appeals assigned to them to work AND appeals that they placed on hold.

- When a co-located team member is planning what to work on, I need to see what type of tasks are assigned to me, so I can prioritize what to work on.
  - e.g. task type column
  - this task type would initially come from the VACOLS field, and in the future come from when attorneys assign the tasks in queue

##### New Tab
![colocated-table-new-tab-single-actions-768](https://user-images.githubusercontent.com/31224257/43283661-80eb7dae-90e7-11e8-9f71-01abb998f958.png)

##### New Tab with Tooltips
![colocated-table-new-tab-single-actions-wtooltips-768](https://user-images.githubusercontent.com/31224257/43283662-81092944-90e7-11e8-95ca-4bbfcc7a9cd1.png)

**Comment by mkhandekar** [comment]
I've updated the link to the design under "mocks" in the original issue.
