### ISSUE TITLE
Co-located table | On hold tab

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6080]
As a co-located user, I want to move cases that I put on hold off my plate, so I can focus on newly assigned cases and tasks or cases pending action. 

## AC
- Establish the 'On hold' tab
- Verify that cases in the On hold tab are those where the user has set a hold
- Verify that this table has `Days on hold` instead of `Days waiting`

### User Stories
- When an administrative action requires further actions before assigning back to an attorney (e.g. extension request, wait for IHP or POA clarification), co-located team members need to put the case on hold.
  - This does not remove the case from the co-located team member's list of work, but recognizes that further work cannot be done on it at this time. It should not count against the user's productivity standards by still being on the team member's plate.

#### "On hold" Tab
![colocated-table-on-hold-tab](https://user-images.githubusercontent.com/31224257/43293713-b6e88222-9109-11e8-8831-fed1c32a6230.png)

**Comment by mkhandekar** [comment]
I've updated the link to the design under "mocks" in the original issue.
