### ISSUE TITLE
Co-located | On hold confirmation banner

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6084]
After a co-located user places a case on hold, they want confirmation that it's been placed on hold and to view it in their On hold queue, before moving on to the next task.

## AC
- Verify that after a user places the case on hold, they view the banner above their queue tables with a confirmation message per the mocks

## Mocks
https://va-gov.invisionapp.com/share/SMIN736NGAE#/297025987_MVP_Table-Colocated_Hold-Success

**Comment by evankroske** [comment]
## Implementation Plan
- [ ] Display a message when a task is placed on-hold successfully. Estimate: 2 hours.
- [ ] Get PR approved. Estimate: 4 hours.

- Total estimate: 1 day.
