### ISSUE TITLE
Send back to attorney (back end completed), send to other teams (front end only)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6086]
When co-located admin support users finish a task, they need to send it back to the attorney.

Note: co-located will also send tasks to other teams in the future, but that is out of scope for this ticket.

### Send back to attorney
- On case details, the Actions dropdown contains `Send back to attorney`
- When they select that option, the modal per designs pops up so the user can confirm sending 

### Send to another team
- Establish a page dedicated to sending the case to another team
- Provide a dropdown that includes `Hearing Branch` and `Translation` - verified
- Backend ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/6632

All tasks should have the option to send back to the assigning attorney. Tasks that are not on hold should also have an option to place a hold, and tasks of `:translation` or `:schedule_hearing` types should have an option to send to the corresponding team.

### Send back to attorney
![co-located_modal_sending-case_attorney](https://user-images.githubusercontent.com/31224257/43865169-c6aa700a-9b2f-11e8-9d53-f622241cc5f9.png)

### Send action to another team
<img alt="screen_shot_2018-08-24_at_2 36 39_pm_720" src="https://user-images.githubusercontent.com/8533004/44662564-2eed4100-a9dc-11e8-8f03-c02700daa93b.png">
<details><summary>old mock</summary>
<img src="https://user-images.githubusercontent.com/31224257/43915960-3cd6e952-9bda-11e8-9d7a-f8f92ca015ad.png">
</details>

## Reference - sending to other teams
- We will support co-located assigning `Schedule hearing` tasks to co-located right now re: https://github.com/department-of-veterans-affairs/caseflow/issues/5931
- Might expand to Translation - need to confirm that attorneys don't assign directly to Translation, what VACOLS location to assign to, etc.

**Comment by evankroske** [comment]
## Implementation Plan for Assigning Back to Attorney
- [ ] Finish PR. Estimate: 2 more days.
- [ ] Get PR approved. Estimate: 1 day.

- Total estimate: 3 days.

## Implementation Plan for Assigning to Other Teams
[insert plan here]
