### ISSUE TITLE
Form 8 Preview: Questions 5b, 6b, 7b:  Automatically populating when no value in counterpart question A.

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#609]
On the Form 8 Preview page, the date is automatically being pre-populated for questions 5b, 6b, & 7b when there is no comment/value in its counter part question 5a, 6a, 7a.  There should not be a date when there is no value in 5a, 6a, and/or 7a.  This has been confirmed for working like this in the demo and production environments.

# Reproductive Steps
Scenario 1
1. Enter only values for required fields on the Form 8 page.
1. Click on the **_Preview Completed Form 8_** button.
1. There are date values in blocks 5b, 6b, & 7b. (Refer to Screen Shots)

Scenario 2
1. Enter a value for question 5a on the Form 8 page.
1. Click on the **_Preview Completed Form 8_** button.
1. There are date values in blocks 6b, & 7b. (Refer to Screen Shots)

# Screen Shots
**_Scenario 1 - Form 8 page - no values in 5, 6, or 7a_**
![image](https://cloud.githubusercontent.com/assets/23063044/21568088/7462573c-ce7f-11e6-862c-fdc243d4b92a.png)

**_Scenario 1 - Form 8 Preview page -  values showing in 5,6, & 7b_**
![image](https://cloud.githubusercontent.com/assets/23063044/21568144/184ec65a-ce80-11e6-8f13-e9936128d19d.png)

**_Scenario 2 - Form 8 page - no values in 6 or 7a_**
![image](https://cloud.githubusercontent.com/assets/23063044/21568326/a2cd01b0-ce81-11e6-89bc-95b967647c98.png)

**_Scenario 2 - Form 8 Preview page - values showing 6 & 7b_**
![image](https://cloud.githubusercontent.com/assets/23063044/21568351/d0a1b950-ce81-11e6-83ad-3bf490dd4d6f.png)

# Relate Stories/Issues
**_Support Issues_**
Form 8 Preview: Questions: 5b, 6b, 7b automatically populated when no value in #a & 13 Other Specified value not displaying - [#5](https://github.com/department-of-veterans-affairs/appeals-support/issues/5)
Form 8 Preview: Questions: 5b, 6b, 7b automatically populated when no value in #a counter-part - [#4](https://github.com/department-of-veterans-affairs/appeals-support/issues/4)

**_Engineering Stories_**
Form 8: Fields 5b/6b/7b date validation - #643 
Form 8: Fields 5B/6B/7B date caching irregularities - #656

**Comment by nikitarockz** [comment]
@shellicious @shanear Check this issue out.  It is ready to be moved forward (Ready for Dev) unless you have any additional questions.

**Comment by kierachell** [comment]
See [comment with additional info](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1125#issuecomment-269806167)

**Comment by kierachell** [comment]
Without any entry, the dates do no show up in PDF.
<img width="573" alt="screen shot 2017-01-13 at 13 29 22" src="https://cloud.githubusercontent.com/assets/18075411/21940956/9249a7f8-d994-11e6-9c82-07e6503605a0.png">
<img width="897" alt="screen shot 2017-01-13 at 13 29 32" src="https://cloud.githubusercontent.com/assets/18075411/21940958/925ac5b0-d994-11e6-92c3-7931de48083a.png">

Going back to make edits and varied entries for **5A**, **6A**, and **7A** preserves and clears the corresponding **B** fields as reflected below.
<img width="897" alt="screen shot 2017-01-13 at 13 30 27" src="https://cloud.githubusercontent.com/assets/18075411/21940957/9259f266-d994-11e6-96c6-b8822e18b35d.png">
