### ISSUE TITLE
AMA Intake | Configure AMA contentions with the correct defaults

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6094]
All contentions require a _classification code_ in order for the claim (EP) to move forward in the process. These classification codes are used primarily for determining which types of exams are required to verify the veteran's disability.

Because supplemental claims will involve exams, we will create the contentions with no classification and require the VSR processing the claim to add the classification for each.

Higher level reviews however, do not require exams or any additional evidence. For this reason classification codes are not useful, but still required systematically by VBMS. The solution is to use a "default" contention classification

Ask Joe Tyson in Slack about the endpoint

## Acceptance Criteria
- If the createContentions endpoint allows it, default `typeCode` to `null` or `""` (empty string). If not, default it to `REP`.
- Default `medical` to `true`

## Technical Notes
Make these values configurable in connect VBMS

**Comment by abbyraskinUSDS** [comment]
Info from Kaitlin:

When establishing a contention, VBMS requires a classification for each contention associated with VA examinations. As Caseflow is working to automate contentions, and we won’t be ordering examinations under HLR 030, is there a generic “other” classification that can be auto populated for all contentions or can we create one if it is not already available?

> After speaking with folks who understand the implications of contention classifications, there doesn’t appear to be any great opposition to not creating a contention classification for 030s.  The real need for them at this point is for examinations.  Since examinations are not permissible for HLRs, it will make no difference that HLRs have no CCs assigned to them.  PA&I indicates they do not use them for metrics purposes.

**Comment by abbyraskinUSDS** [comment]
From AMO call:
- Jennifer: Create HLR with no classification code if possible.

**Comment by shanear** [comment]
No change required due to this. Closing

**Comment by nicholasholtz** [comment]
Reopening this issue based on discussions with Mary Kate. We are sending a classification for certain elements, and the contentions are locked by VBMS. There is a change in the works to make those contentions editable, but it is apparent that the classification we are sending is creating additional work of having to change the classifications.

We need AMO clarification on what the preferred classifications to send are.
@shanear

**Comment by leikkisa** [comment]
I asked VBMS, and they said we are setting this to null, and believe this is correct and that users will set it if need be.  Waiting to hear confirmation from AMO that this is correct.

**Comment by leikkisa** [comment]
Some information from Joe:
```
Expectations via the Claim Service V5:
Medical: true or false

Type: 
BGS StandardDataService.getContentionTypeList() - the ‘cd’ value should be sent to ClaimServiceV5

<return>
            <cd>INC</cd>
            <groupTn>CNTNTN_TYPE</groupTn>
            <nm>Increase</nm>
         </return>
         <return>
            <cd>NEW</cd>
            <groupTn>CNTNTN_TYPE</groupTn>
            <nm>New</nm>
         </return>
         <return>
            <cd>REP</cd>
            <groupTn>CNTNTN_TYPE</groupTn>
            <nm>Reopen</nm>
         </return>
         <return>
            <cd>RFE</cd>
            <groupTn>CNTNTN_TYPE</groupTn>
            <nm>RFE</nm>
         </return>
         <return>
            <cd>SEC</cd>
            <groupTn>CNTNTN_TYPE</groupTn>
            <nm>Secondary</nm>
         </return>

Contention Classification:
BGS StandardDataService.getContentionClassificationTypeCodeList()
clsfcnId would be the value sent into the ClaimServiceV5

<ns2:getContentionClassificationTypeCodeListResponse xmlns:ns2="http://services.mapd.benefits.vba.va.gov/">

         <return>
            <clsfcnId>10</clsfcnId>
            <clsfcnTxt>abnormal heart</clsfcnTxt>
            <endDt>2016-02-04T11:51:56-06:00</endDt>
         </return>
         <return>
            <clsfcnId>20</clsfcnId>
            <clsfcnTxt>abnormal mitral valve</clsfcnTxt>
            <endDt>2016-02-04T11:51:56-06:00</endDt>
         </return>…..

Example ClaimServiceV5.createContention call

<createContentions>
      <contentionsToCreate
          actionableItem="true"
          awaitingResponse="foo"
          claimId="600143815"
          classificationCd="20"
          id="0"
          medical="true"
          partcipantContention="foo"
          secondaryToContentionID="10"
          title="Digestive"
          typeCode=“SEC"
          workingContention="YES">
        <ns2:submitDate>2018-11-27-05:00</ns2:submitDate>
        <ns2:issue typeCd="SSR" narrative="Same Station Review" inferred="false"/>
        <ns2:origSrc>APP</ns2:origSrc>
      </contentionsToCreate>
     </createContentions>
```

**Comment by shanear** [comment]
had a call today about this.

they'd prefer typeCode to not be set, but if the service does not allow that we can set it to "Reopen"
medical is always defaulted to "true"

**Comment by leikkisa** [comment]
There is another field called classification_cd that is still nil.  Seems worth pointing out since we've been calling the type_cd the contention's classification code, but they might not be interchangeable terms.

Tested nil and empty string for typeCode and it's not allowed, so updated the default to "REP", and also updated the medical default to "true".

**Comment by steve-gov** [comment]
Validated:

## HLR Created
<img width="570" alt="screen shot 2019-01-30 at 3 43 01 pm" src="https://user-images.githubusercontent.com/25468689/52020473-3c848680-24a6-11e9-9ded-295c840853e5.png">

## Results in EP with Type: Reopen and Medical: Yes
<img width="592" alt="screen shot 2019-01-30 at 3 46 27 pm" src="https://user-images.githubusercontent.com/25468689/52020502-53c37400-24a6-11e9-847d-4f603afbb6f3.png">

**Comment by shanear** [comment]
![image 5](https://user-images.githubusercontent.com/1596259/52090373-09093100-2566-11e9-877d-bb05e2305f9e.png)
mary kate reported this not working. I'm looking into why

**Comment by shanear** [comment]
ahhh i see cool. I'll reclose

**Comment by leikkisa** [comment]
When I fetch the contentions for that I get this:
```#<VBMS::Responses::Contention id="315596", text="Service connection for Neck is granted with an evaluation of 30 percent effective January 1, 2015.", start_date=Thu, 31 Jan 2019, submit_date=Thu, 31 Jan 2019, actionable_item="false", awaiting_response="unknown", claim_id="600149037", classification_cd=nil, contention_category=nil, file_number="612341447", level_status_code=nil, medical="true", participant_contention="unknown", secondary_to_contention_id="869365", type_code="REP", working_contention="unknown">]```
