### ISSUE TITLE
Automatically rollback AMA reviews where the EP was canceled

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6097]
The long term solution to canceled EPs is to have Caseflow properly respond to them. The current plan is if an EP is canceled in the field, the associated higher level review/supplemental claim should also be "canceled" and rolled back (along with any closed VACOLS records).

This would happen as part of our synchronization job.

## Technical notes 
[Shane's fancy script]

**Comment by abbyraskinUSDS** [comment]
We brought this up again during the weekly meeting. They have not made a final decision, but have suggested they will today or tomorrow - we should check in again on Friday.

**Comment by abbyraskinUSDS** [comment]
Still waiting on an answer from AMO.

**Comment by abbyraskinUSDS** [comment]
AMO approved...but they are somewhat nervous about it. They would like us to turn it on for 1 day to validate.

**Comment by shanear** [comment]
dup of https://github.com/department-of-veterans-affairs/caseflow/issues/6615

closing
