### ISSUE TITLE
Intake | Set the claimant when establishing the end product

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6098]
We need to be able to set the claimaint on the EP we create in VBMS via the EstablishClaim service.

There is no officially supported way to do this right now. However, there is a unofficially supported way of passing the claimant's participant id where the veteran participant id would go. VBMS said they could add official support for this before the December release and potentially before the August release.

## Acceptance criteria
- Set the claimant on the EP we create for AMA HLRs and SCs using the unofficial method.
- Comment clearly in the code that this is a workaround

**Comment by leahbannon** [comment]
If the claimant is different from the vet, we send the claimant in participant ID not the vet.

**Comment by kahlouie** [comment]
From Sally: Can't set non-veteran claimant without a payee code.

**Comment by abbyraskinUSDS** [comment]
@leikkisa would working on #6234 unblock this?

**Comment by shanear** [comment]
<img width="878" alt="screen shot 2018-09-25 at 5 43 10 pm" src="https://user-images.githubusercontent.com/1596259/46045084-96d19d00-c0ea-11e8-9397-35b27cb47596.png">
Works!
