### ISSUE TITLE
AMA Intake | Sync Higher Level Review and Supplemental Claim data with BGS

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6099]
After creating the HLR or SC end product in VBMS, there is some information about it that can change. We need to either, not store this data or sync it from BGS/VBMS.

- Claimant information
- Payee code
- Claim date (receipt date)

Some technical design/thought needs to be put into the strategy here.

**Comment by leahbannon** [comment]
We should follow up with Queue team w/ an answer

**Comment by shanear** [comment]
This was brought up as an issue by the business. We may have to prioritize it.
