### ISSUE TITLE
Form 8 |  Pre-populated Fields | Missing data (completely blank) and unable to manually enter 

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#610]
# Description
User is having any issues with form 8. The pre-populated slots are not being populated, nor can she enter some fields manually. User can not enter the file number, question#2, nor can she enter into questions 15 and 16. However, she can enter information into question #3. See the screenshot below
User URL is: https://certification.cf.ds.va.gov/certifications/new/3030564

_We've gotten a couple of reports of certifications being completely blank, not pulling any information from VACOLS._

[Here is an example of a certification that experienced this issue](https://certification.cf.ds.va.gov/certifications/new/2935004). The user ended up manually certifying the appeal, so the blank certification record should continue to exist in the DB.

Our current workaround to this issue is to delete the offending certification row in production so the data can reload.

**Environment:**
- [x] Production
- [ ] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [x] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [x]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
# Reproductive Steps
**_Scenario 1 - Missing pre-populated data_**
1. In VACOLS, enter Vet ID #.
1. Click on the **_Certify_** button in VACOLS to launch Caseflow Certification.  
1. `Electronic Form 8 ` page will be displayed with pre-populated values.
**Results**:  Values missing for question 2.   

**_Scenario 2 - Unable to enter values in questions 2, 15, 16_**
1. Continuing from Scenario 1.
1. Enter required values for questions 2 - 16.  
**Results**:  User is unable to enter values in question 2, 15, & 16..

# Screen Shots
**_Scenario 1 - Missing pre-populated data_**
![form 8](https://cloud.githubusercontent.com/assets/23316043/22790510/6dca907e-eeb4-11e6-839a-40a9ab30db1c.PNG)

# Relate Stories/Issues
**_Support Ticket_**
Form 8: Not pulling any pre-populated data from Vacols - [#6](https://github.com/department-of-veterans-affairs/appeals-support/issues/6)
Form 8: Pre-populated fields: no data: unable to manually enter [#52](https://github.com/department-of-veterans-affairs/appeals-support/issues/52)

**Comment by kierachell** [comment]
Edge case; will reopen if shows up again.

**Comment by shanear** [comment]
It popped up again: https://github.com/department-of-veterans-affairs/appeals-support/issues/52

**Comment by nikitarockz** [comment]
@shanear , diagnostic information below:
```
irb(main):015:0* Certification.find_by_vacols_id(3030564)
  Certification Load (4.4ms)  SELECT  "certifications".* FROM "certifications" WHERE "certifications"."vacols_id" = $1 LIMIT 1  [["vacols_id", "3030564"]]
=> #<Certification id: 1994, vacols_id: "3030564", already_certified: false, vacols_data_missing: false, nod_matching_at: "2016-10-01 16:33:56", soc_matching_at: "2016-10-01 16:33:56", form9_matching_at: "2016-10-01 16:33:56", ssocs_required: false, ssocs_matching_at: nil, form8_started_at: "2017-02-09 14:43:45", completed_at: nil, created_at: "2016-10-01 16:33:51", updated_at: "2017-02-09 14:43:45", user_id: nil>
irb(main):018:0> Appeal.find_by_vacols_id(3030564)
  Appeal Load (1.2ms)  SELECT  "appeals".* FROM "appeals" WHERE "appeals"."vacols_id" = $1 LIMIT 1  [["vacols_id", "3030564"]]
=> #<Appeal id: 12165, vacols_id: "3030564", vbms_id: "492624783S", rice_compliance: false, private_attorney: false, waiver_of_overpayment: false, pensions: false, vamc: false, incarcerated_veterans: false, dic_death_or_accrued_benefits: false, education_or_vocational_rehab: false, foreign_claims: false, manlincon_compliance: false, hearings_travel_board_video_conference: false, home_loan_guaranty: false, insurance: false, national_cemetery_administration: false, spina_bifida: false, radiation: false, nonrating_issues: false, proposed_incompetency: false, manila_remand: false, contaminated_water_at_camp_lejeune: false, mustard_gas: false, dependencies: false>
irb(main):021:0> Form8.find_by_vacols_id(3030564)
  Form8 Load (8.5ms)  SELECT  "form8s".* FROM "form8s" WHERE "form8s"."vacols_id" = $1 LIMIT 1  [["vacols_id", "3030564"]]
=> nil
```

@orischwartz ; I put this technical information here in the engineering story and removed it from the support ticket.

**Comment by aroltsch** [comment]
Should we add validation at the DB level so it would throw an error when form8 is  saved with empty values?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT

Steps to validate:
1. Go to Caseflow and enable the certify appeal role from the functions page
2. Access a new form 8 page, https://certification.cf.uat.ds.va.gov/certifications/new/2765723
3. Scroll down and validate that information is being pre-populated from VACOLS. 

Screenshots: 
<img width="1085" alt="screen shot 2017-03-01 at 1 51 11 pm" src="https://cloud.githubusercontent.com/assets/23038505/23475858/dc30867c-fe86-11e6-8967-7bb4a7c803fc.png">
