### ISSUE TITLE
Form 8 Preview: Question 13 Other Specified:  Isn't displaying value entered

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#611]
When a value is entered for 13 Other Specified on the Electronic Form 8 page, that value isn't displayed on the Form 8 Preview page.  This issue seems to be only occurring in the Production environment.  It is working properly in the Demo environment.

# Reproductive Steps
Scenario 1
1. Launch Certification.  Electronic Form 8 page will be displayed.
1. Enter required values for questions 1 - 12.
1. Select the option "Other" for question 13.
1. Enter a value for question 13 Other Specified.
1. Click on the **_Preview Completed Form 8_** button.
1. The value for 13 Other Specified is not displayed.  (Refer to Screen Shots)

# Screen Shots
**_Scenario 1 - (Production) Electronic Form 8 Page - Question 13 Other Specified value_**
![image](https://cloud.githubusercontent.com/assets/23063044/21569108/ff0f8a82-ce87-11e6-8574-c82d798e952c.png)

**_Scenario 1 - (Production) Form 8 Preview Page - No value for Question 13 Other Specified_**
![image](https://cloud.githubusercontent.com/assets/23063044/21569141/3739b7a2-ce88-11e6-94f7-760ebda17bf4.png)

**_Scenario 1 - (Demo) Electronic Form 8 Page - Question 13 Other Specified value_**
![image](https://cloud.githubusercontent.com/assets/23063044/21569184/9374d45c-ce88-11e6-833a-1d857b88ca27.png)

**_Scenario 1 - (Demo) Form 8 Preview Page - No value for Question 13 Other Specified_**
![image](https://cloud.githubusercontent.com/assets/23063044/21569218/e8e3ddd4-ce88-11e6-8244-dc699155a58e.png)

# Relate Stories/Issues
**_Support_**
Form 8 Preview: Questions: 5b, 6b, 7b automatically populated when no value in #a & 13 Other Specified value not displaying - [#5](https://github.com/department-of-veterans-affairs/appeals-support/issues/5)

**Comment by nikitarockz** [comment]
@shellicious @shanear Check this issue out. It is ready to be moved forward (Ready for Dev) unless you have any additional questions.

**Comment by kierachell** [comment]
It appears now...
<img width="1018" alt="screen shot 2017-01-27 at 09 17 24" src="https://cloud.githubusercontent.com/assets/18075411/22373906/da416da6-e471-11e6-8060-c344b28f897c.png">
<img width="952" alt="screen shot 2017-01-27 at 09 17 39" src="https://cloud.githubusercontent.com/assets/18075411/22373907/da4dc8f8-e471-11e6-996e-4c272582edcf.png">

but doesn't disappear (see #739 )
