### ISSUE TITLE
Idea: Steps for Case Search rollout 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6111]
1. Modify the nav bar to have a search link 
    - Modify the nav bar such that we can put a case search link in the nav bar for a particular React application, if we choose. (Our React applications are currently Queue, Reader, Dispatch, Hearings Prep, Certification, Hearings Schedule, and the Help pages)
   - This link should lead the user to the empty route, `/`, which should load the Caseflow Search landing page
     - Bonus points for dev: If the user is coming from inside the Queue app, we should be able to use a React Router link and not a regular `a` tag to avoid a full pageload

2. Roll the nav search link out for Queue
    - Currently, when Queue users go to the empty route, `/`, we load the Queue page and *not* the Caseflow Search page. So when clicking the `Search` link, all Queue users would wind up back at `/queue`. 
      - Q: do we want to unwind this decision? If not, as we roll out users to Queue, they will no longer be able to see the Caseflow Search page, and we'd have to ensure in the future that everything we put on that page is redundant.

3. Enable access to Case Search for all BVA employees (station: 101 I think?)
    - This will reduce rollout complexity we have to manage, as we won't have to worry about the search link not working for some folks who have access to e.g. Reader or Hearings Schedule or Hearings Prep but not Queue or Case Search

4. Roll the nav search link out for all BVA-only apps: Reader, Hearings Schedule, and Hearings Prep

5. Enable access to Case Search for all users with at least one Caseflow function (e.g. Dispatch, Certify Appeal, Intake)
    - At this point, all BVA employees and all non-BVA employee Caseflow users should be able to search for appeals, but not necessarily everyone on the VA network. 
6. Roll the nav search link out for all remaining Caseflow apps: Intake, Certification, Dispatch
7. At some point, create a Caseflow Search CSS function and tell VA it can be given to any employee who needs to see appeals

**Comment by mkhandekar** [comment]
Yes, love it! What you've described matches the direction I was imagining: 
- changing the search bar to a search link
- search link opens the Search landing page
- Search landing page looks/works consistently and similarly for all Caseflow users

I agree with # 2 about modifying the behavior for Queue users to:
- If a user has access to Queue, clicking on the Caseflow logo takes them to their queue
- If a user does not have access to Queue, clicking on the Caseflow logo takes them to the Search landing page
- Any user reaches the Search landing page by clicking the search link in the header.

---

My open question is still: how do search results differ (if at all) when a user searches from different apps (Reader, Hearings Schedule, and Hearings Prep, etc, etc)? (We can talk about this synchronously sometime soon).

**Comment by lowellrex** [comment]
Plan makes sense to me, and I agree with @mkhandekar's thoughts on where to send folks when they click on the search link and the caseflow heading.

**Comment by mkhandekar** [comment]
@amprokop 💯 i agree that we should expect the search link to behave the same!

**Comment by laurjpeterson** [comment]
Case search link is now in the nav bar! Closing.
