### ISSUE TITLE
Copy change: add new claimants in VBMS not SHARE

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6116]
Currently, our instructions when adding a new claimant tell  the user to add the relationship in SHARE. Instead, they should do this in VBMS, so we should update our copy.

## Acceptance Criteria
- Our instructions should prompt users to add claimants in VBMS:
  - Please select the claimant listed on the form. If you do not see the claimant in the options below, add them in VBMS, then refresh this page.

**Comment by suzchap** [comment]
LGTM
