### ISSUE TITLE
Form 8:  Rename "Cancel Certification" link to "Cancel"

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#612]
As a Product Owner, I would like to have the link "Cancel Certification" renamed to "Cancel" on the Electronic Form 8 page so that it is consistent with the application standards and doesn't conflict with the button on the Cancellation page.

# Acceptance Criteria 
1. Verify that on the Electronic Form 8 page the link **_"Cancel Certification"_** has been rename to **_"Cancel"_**.

## Mockup
**_View - Electronic Form 8 Page - Before_**
![image](https://cloud.githubusercontent.com/assets/23063044/21570707/aad798c4-ce96-11e6-9b5b-d5551cca8414.png)

**_View - Electronic Form 8 Page - After_**
![image](https://cloud.githubusercontent.com/assets/23063044/21570730/de41e048-ce96-11e6-866b-0092b9d713ec.png)

# Related Stories

**Comment by kierachell** [comment]
Looks correct on my end:
<img width="956" alt="screen shot 2017-01-05 at 14 52 20" src="https://cloud.githubusercontent.com/assets/18075411/21695186/b56ee232-d356-11e6-84f9-bc596b72e064.png">
