### ISSUE TITLE
RampElection Sync Job causing excessive BGS errors

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#6145]
It appears that the background job to sync Ramp Elections causes us to see higher error rates than normal.  @shanear, we need to find a better way to handle errors so that these are not re-tried.  

![](https://www.dropbox.com/s/fxac7yf7ylt0owp/Screenshot%202018-07-09%2011.11.27.png?dl=1)

**Comment by shanear** [comment]
so after some looking into this. We aren't doing an exponential roll off on retries or anything. This is just causing a consistent 30 errors per hour per broken file number. 

There are currently 4 broken file numbers, so we're seeing ~120 errors per hour. We are working on fixing the underlying causes of these problems, and unless ~120 errors an hour is a huge problem then I'm gonna hold on working on this

**Comment by shanear** [comment]
All the consistently failing syncs have been fixed. The only ones we are still seeing are timeouts which happen sporadically. Closing.
