### ISSUE TITLE
Decision Review:  Create EP:  Show potential EP duplicates

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#615]
As a Caseworker, I would like to view a list of existing EPs that could be a potential duplicates before I create the new EP so that I am confident I am not recreating an existing EP.

## Acceptance Criteria 
1. Verify that after clicking on the **_Create End Product_** button on the Decision Review page, search for potential duplicates based on EPs - pending/open that could be associated with post decision. Following are potential duplicate EP codes:

     - 170APPACT
     - 170APPACTPMC
     - 170PGAMC
     - 170RMD
    - 170RMDAMC
    - 170RMDPMC
    - 172GRANT
    - 172BVAG
    - 172BVAGPMC
    - 400CORRC
    - 400CORRCPMC
    - 930RC
    - 930RCPMC

1. Verify that if there is one or more exiting EPs, the Existing EPs page is displayed.
1. Verify that that the following warning message is displayed containing the Decision Date range of +/- 30 days (refer to mockup).
 
1. Verify that on the Existing EPs page, there is a table listing all existing EPs with the following columns:
     - **_Decision Date_** - Shows the date of the claim found in VBMS.  _**Format:**_  mm/dd/yyyy
     - **_EP Code_** -  Shows the EP code found in VBMS.
     - **_Status_** - Shows the status of the listed EP.  **_Valid Values:_**  Pending, Cleared
     - **_Select this EP_** -  Action column with a **_Assign to Claim_** button
1. Verify that the Existing EPs are listing in chronological order by Decision Date, with the most recent at the top.
1. Verify that after clicking on the **_Create new EP_** button for a selected existing EP, the End Product page is displayed.

## Mockup
**_View - Exisitng EPs Page_**
<img width="436" alt="screen shot 2017-01-04 at 10 54 28 am" src="https://cloud.githubusercontent.com/assets/4975959/21648494/355f175a-d26c-11e6-8998-6ca1a86f0963.png">

**_View - End Product Page_**
![image](https://cloud.githubusercontent.com/assets/23063044/21652190/bc850872-d279-11e6-8f30-6697f472017b.png)

## Technical Notes
Checking for existing EPs are in BGS.

# Related Stories

**Comment by lakohl** [comment]
https://marvelapp.com/1j3336d

**Comment by lakohl** [comment]
Updating design based on conversation with @shanear and @cmgiven

**Comment by lakohl** [comment]
<img width="724" alt="screen shot 2017-01-03 at 5 18 13 pm" src="https://cloud.githubusercontent.com/assets/4975959/21625228/a6db3a2e-d1d8-11e6-8085-4def8fe9a444.png">

**Comment by lakohl** [comment]
<img width="563" alt="screen shot 2017-01-03 at 5 48 17 pm" src="https://cloud.githubusercontent.com/assets/4975959/21626055/f169423a-d1dc-11e6-9d51-4c748bd3e24e.png">

**Comment by nikitarockz** [comment]
@lakohl I have finished updating this story, please read through the ACs carefully to make sure I capture information correctly.    
Is this page being launched from the Decision Review page when the user clicks on the Create End Product button?

**Comment by shanear** [comment]
AC 1. (all EPs in the last 30 days) seems to conflict with AC 3. (all EP's in +/- 3 days)

@lakohl can you specify?

**Comment by lakohl** [comment]
I made a couple adjustments above. We should display all Pending or Cleared EPs within 30 days +/- of the decision date.

**Comment by lakohl** [comment]
I updated the mocks above.

**Comment by mdbenjam** [comment]
@lakohl what text should we show under EP Code for each of these:

170APPACT
170APPACTPMC
170PGAMC
170RMD
170RMDAMC
170RMDPMC
172GRANT
172BVAG
172BVAGPMC
400CORRC
400CORRCPMC
930RC
930RCPMC

Can we just use these codes directly?

**Comment by mdbenjam** [comment]
Also, I was looking at EP codes and it appears there is a code CAN. Presumably this means canceled. Should we allow association with canceled EPs?

**Comment by shanear** [comment]
@mdbenjam 

170APPACT - Appeal Action170APPACTPMC
170APPACTPMC - PMC-Appeal Action
170PGAMC - AMC-Partial Grant 
170RMD - Remand 170RMDAMC - AMC-Remand
 170RMDPMC - PMC - Remand
 172GRANT - Grant of Benefits
 172BVAG - BVA Grant
 172BVAGPMC - PMC - BVA Grant 
400CORRC - Correspondence
 400CORRCPMC - PMC-Correspondence
 930RC - Rating Control
 930RCPMC - PMC - Rating Control

**Comment by mdbenjam** [comment]
Thanks Chris. @lakohl Another question is what should the back to review button look like if there were associated EP's? Should it be a back to EP select page?

**Comment by astewarttistatech** [comment]
@shanear @mdbenjam should I be able to test all of the EP codes? 

Currently this is what displays

<img width="1033" alt="screen shot 2017-01-11 at 4 25 47 pm" src="https://cloud.githubusercontent.com/assets/23038505/21867134/d6d277ea-d81a-11e6-801c-900365496095.png">

**Comment by mdbenjam** [comment]
I could add more fake data to show all of them, if that would be helpful.

**Comment by astewarttistatech** [comment]
Yes please! @mdbenjam

**Comment by kierachell** [comment]
I messed around some and @mdbenjam added proper seeds (and then I refactored them ;) )
<img width="751" alt="screen shot 2017-01-17 at 08 22 05" src="https://cloud.githubusercontent.com/assets/18075411/22023343/cf6b3514-dc93-11e6-8301-2597e2b1769b.png">
