### ISSUE TITLE
FOLLOW UP  JULY 13 | Fix wild RAMPS July 9

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6158]
Erik sent a batch of new wild RAMPs to fix.

**Comment by shanear** [comment]
There are a couple that don't make sense, I'm gonna get back to him tomorrow

**Comment by shanear** [comment]
Erik is still looking into these :/

**Comment by abbyraskinUSDS** [comment]
I'm moving this back, since Shane is out and we aren't actively doing anything with these right now.

**Comment by abbyraskinUSDS** [comment]
This was done a while ago - closing.
