### ISSUE TITLE
Decision Review | Ability to view multiple Decision Documents

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#616]
As a Caseworker, I would like to be able to view multiple decision documents from VBMS within a given date range so that I can select and create an EP for the correct decision document.

# Acceptance Criteria

1. Verify that all the decisions documents within the assigned date range are displayed one per tab.
1. Verify that each decision is displayed with a label title in the following format:
     **_Format:_**  Decision # ([DecisionDate])
     **_Date Format:_** mm/dd/yy
     **_Example:_**  Decision 1 (01/02/17)
1. Verify that the Decision Tabs are displayed in reverse chronological order (most recent to oldest).
1. Verify that after clicking on the Decision Tab, that decision document becomes the actively selected document.
1. Verify that the text: ' Select a Decision Document' appear above the .pdf document.
1. Verify that the text: 'Use the tabs to review the decision documents below and select the decision that best fits the VACOLS Decision Criteria.  ' Appears below the title 'Select a Decsion above the decision tabs.
1. Verify that the button CTA copy reflects the decision selected.  **_Example:_** Create End Product for Decision 1.
1. Verify that after clicking on the Create End Product for Decision x button, that the Decision document, as well as any updates to the Decision Type value and/or selected Special Issues are associated with the Claim Establishment task.

# Mockup
**_View - Decision Review Page - Multiple Decisions Tab displayed_**

<img width="327" alt="screen shot 2017-01-31 at 8 30 45 am" src="https://cloud.githubusercontent.com/assets/4975959/22467133/6a53b0c6-e791-11e6-8225-1e52b21e8278.png">

# Related Stories
EPIC: Decision Review: Ability to review a veteran's VBMS decision [#3](https://github.com/department-of-veterans-affairs/appeals-design/issues/3)
Decision Review | Display an alert when there multiple decisions available #735
Decision Review | Ability to view Decision Criteria information #736

**Comment by lakohl** [comment]
https://marvelapp.com/project/1112802/

**Comment by lakohl** [comment]
Updating design based on conversation with @shanear, @joofsh and @cmgiven

**Comment by lakohl** [comment]
@cmgiven @shanear Does this look like what we discussed for multiple VBMS Decisions?
![fg two decisions criteria](https://cloud.githubusercontent.com/assets/4975959/21627683/786da5be-d1e7-11e6-9167-0e3c2b61071b.png)

**Comment by cmgiven** [comment]
Yes. Two notes:

1. A decision can have multiple issues, so we probably shouldn't list the decision type as a column.
2. I feel like it might be worth noting the provenance of this info (VACOLS), as we're asking someone to make a judgment based on info that may be wrong or incomplete. Maybe the header could be "VACOLS Issues"?

**Comment by cmgiven** [comment]
Also remember to delete that "Level 1" and "Level" text.

**Comment by lakohl** [comment]
@cmgiven I'm not sure I'm following you exactly - understand about the many issues, but less about the decision type, and nthe levels, but I made some quick fixes:
<img width="692" alt="screen shot 2017-01-03 at 7 24 33 pm" src="https://cloud.githubusercontent.com/assets/4975959/21628054/79bd8d28-d1ea-11e6-9874-f1f5e58e03cd.png">

**Comment by cmgiven** [comment]
I mean that it doesn't make sense for there to be a decision type column, as it would be repeated for each issue in the decision. Better separate from the table?

**Comment by lakohl** [comment]
@cmgiven I see. Got it!

**Comment by lakohl** [comment]
<img width="665" alt="screen shot 2017-01-12 at 2 56 54 pm" src="https://cloud.githubusercontent.com/assets/4975959/21905966/6612873a-d8d7-11e6-8c46-fa3481cc2942.png">

**Comment by nikitarockz** [comment]
# Sprint Planning 
Update ACs to match mockup.

**Comment by lakohl** [comment]
@nikitarockz I updated the mock and acceptance criteria above. Could you review? thanks

**Comment by lakohl** [comment]
@mdbenjam  I took out the radio buttons. Let me know if you have questions!

**Comment by lakohl** [comment]
also, sorry to move things around on you! Hadn't refreshed my browser since last night and didn't see that it was in the In Progress column.

**Comment by mdbenjam** [comment]
Not a problem, haven't gotten to that part yet. Still working on the tabs.

**Comment by astewarttistatech** [comment]
Current view in UAT:

<img width="1374" alt="screen shot 2017-02-07 at 8 21 47 am" src="https://cloud.githubusercontent.com/assets/23038505/22692859/d88242c4-ed0e-11e6-8a67-ac1773cf9346.png">

@mdbenjam please revisit this issue

**Comment by kierachell** [comment]
**PASSED**
Works with 4+ documents in `preprod`
<img width="1278" alt="screen shot 2017-02-09 at 20 27 53" src="https://cloud.githubusercontent.com/assets/18075411/22810360/4011b516-ef06-11e6-8517-b090cb52dd84.png">
Might have to check for 20+
