### ISSUE TITLE
Appeal Outcoding | Create a supplemental claim on a DTA error or remand for a decided Appeal

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6167]
When an appeal is outcoded, if the disposition of that issue is in the list below, we should create a follow up supplemental claim with those issues.

requires #8262

## Acceptance Criteria
When a board appeal is outcoded, after the decision document has been uploaded in the outcoding job referenced in #8262:
- if any decision issues have dispositions of "Remanded", there should be a DTA supplemental claim created with request issues contesting each remanded decision issue.
- The `040BDE` should be used as the EP code for the follow up EPs unless:
  - The benefit type is pension, then use the `PMC` version of the EP code.
  - If the remand reason category is `medical exams and opinions` and the remand reason is `advisory medical opinion`. Then use the `IMO` version of the EP code.

## Notes
EP codes:

 EP | Claim Label 
-- | --
040BDE | Board DTA Error
040BDEIMO | Board DTA Error with IMO
040BDEPMC | PMC Board DTA Error 
040BDEIMOPMC | PMC Board DTA Error - w/IMO

## Technical Notes
- The "Remanded" disposition has a constant here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/ISSUE_DISPOSITIONS_BY_ID.json#L3
- The creation of the SupplementalClaim should happen asynchronously, just like it does for HLRs
- All request issues should have dispositions at that point. I think we can probably raise an exception if that is not the case.

**Comment by abbyraskinUSDS** [comment]
I'm not sure about the dispositions text. But here is the list of AMA end products. It looks like there are two EP options for a supplemental claim stemming from an HLR decision (to track non-rating and rating):
- 040HDENR
- 040HDR

![eps for ama](https://user-images.githubusercontent.com/4042181/45230581-e3b21880-b28e-11e8-8ab9-4c680de023fd.png)

**Comment by laurjpeterson** [comment]
[Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1534279378866/d4531cbe67b6690068a6bd052d4deed55f6ab131) with mapping of issue dispositions, remand reasons, EPs, and whether or not to make a supplemental claim.

**Comment by shanear** [comment]
First outcome, figure out how decision issues are going to be modeled and how they are going map to DTA error supplemental claims.

**Comment by leikkisa** [comment]
I got started on this, but it seems like it would make sense to wait for 8263 so I am pausing for now.

**Comment by leikkisa** [comment]
Shane says to wait until after some related bug fixes he is currently working on before starting this

**Comment by steve-gov** [comment]
Blocked due to #8803 .

**Comment by steve-gov** [comment]
EPs show as Caseflow search results on `123458316` (last 4 in image):

<img width="948" alt="screen shot 2019-01-30 at 12 35 35 pm" src="https://user-images.githubusercontent.com/25468689/52010989-b5c2b000-248b-11e9-99b5-b4b4924620ac.png">

**Comment by steve-gov** [comment]
Clicking `Edit in Caseflow` in VBMS on the resulting SC results in the appropriate "issues not editable" page:

<img width="839" alt="screen shot 2019-01-30 at 12 37 29 pm" src="https://user-images.githubusercontent.com/25468689/52011080-e3a7f480-248b-11e9-9b43-8f863bf7dd93.png">
