### ISSUE TITLE
AMA Decisions | Create a supplemental claim on a DTA error for a decided higher level review

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6168]
When a higher level review is decided, if the disposition of that issue is in the list below, we should create a follow up supplemental claim with those issues.

DTA Error – PMRs
DTA Error – Fed Recs
DTA Error – Other Recs
DTA Error – Exam/MO

## Acceptance Criteria
- When syncing the dispositions of request issues of a higher level review, if any of the request issues have dispositions of DTA Error (see the list above), Caseflow should automatically create a follow on supplemental claim with request issues linked to those issues.
- If the supplemental claim is the result of DTA error the EP created should have a special code (040HDENR for non rating EPs, 040 HDER  for rating EPs)

## Technical notes
- We will have to determine how to link request issues in the database. It would be good to agree on this structure before we begin coding this task.

blocks #6169

**Comment by abbyraskinUSDS** [comment]
Here is the list of AMA end products. It looks like the options for a supplemental claim stemming from a Board remand decision are:
- 040BDE
- 040BDEIMO

![eps for ama](https://user-images.githubusercontent.com/4042181/45230581-e3b21880-b28e-11e8-8ab9-4c680de023fd.png)

**Comment by shanear** [comment]
This didn't work 😢 

PR incoming.

**Comment by shanear** [comment]
<img width="1176" alt="screen shot 2018-10-10 at 12 56 41 pm" src="https://user-images.githubusercontent.com/1596259/46752732-f81d7280-cc8b-11e8-82d8-f955fafb769c.png">
woohoo!

Checked everything linked up correctly in the DB as well
