### ISSUE TITLE
App Canvas | Header | Add Progress Indicator

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#617]
As a Caseworker, I would like to have a Progress Indicator at the top of each Dispatch page indicating the three major steps:  1) Review Decision, 2) Route Claim 3) Confirmation so that I know where I am at all times and understand how much more work I still need to do.

# Acceptance Criteria
1. Verify that the Progress Indicator has the following 3 steps (refer to Mockup):

     > Review Decision
     > Route Claim
     > Confirmation
1. Verify that the Progress Indicator is at the current step in the dispatch process indicated with dark grey color bar and bold type.
1. Verify that past steps are indicated on the Progress Indicator with dark grey color and bold type.
1. Verify that future steps are indicated on the Progress Indicator in light grey color and regular type.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Decision Review` page.
1. Verify that when on the `Decision Review` page, the Progress Indicator is set to "Review Decision" as the current step.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Route Claim: Create End Product` page.
1. Verify that when on the `Route Claim: Create End Product` page, the Progress Indicator is set to "Route Claim" as the current step.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Route Claim: Update VACOLS` page.
1. Verify that when on the `Route Claim: Update VACOLS` page, the Progress Indicator is set to "Route Claim" as the current step.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Route Claim: Existing EP` page.
1. Verify that when on the `Route Claim: Existing EP` page, the Progress Indicator is set to "Route Claim" as the current step.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Route Claim: Add VBMS Note` page.
1. Verify that when on the `Route Claim: Add VBMS Note` page, the Progress Indicator is set to "Route Claim" as the current step.
1. Verify that when on the `Route Claim: Update VACOLS and VBMS` page, the Progress Indicator is set to "Route Claim" as the current step.
1. Verify that when on the `Confirmation` page, the Progress Indicator is set to "Confirmation" as the current step.
# Mockups
**_View -  Decision Review page - Current Step Progress Indicator_**
<img width="702" alt="screen shot 2017-02-09 at 6 28 47 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807569/af647e00-eef5-11e6-9263-80cd4e612fe1.png">
**_View -  EP Creation page - Current Step Progress Indicator_**
<img width="682" alt="screen shot 2017-02-09 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807571/b26acdd4-eef5-11e6-9df2-4b9aa2b66869.png">
**_View -  Route Claim page - Current Step Progress Indicator_**
<img width="682" alt="screen shot 2017-02-09 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807571/b26acdd4-eef5-11e6-9df2-4b9aa2b66869.png">
**_View -  Existing EP page - Current Step Progress Indicator_**
<img width="682" alt="screen shot 2017-02-09 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807571/b26acdd4-eef5-11e6-9df2-4b9aa2b66869.png">
**_View -  EP Confirmation page - Current Step Progress Indicator_**
<img width="685" alt="screen shot 2017-02-09 at 6 29 10 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807572/b5334cd0-eef5-11e6-9416-df34adabcc38.png">

# Related Stories
n/a

**Comment by lakohl** [comment]
working on refining this design

**Comment by lakohl** [comment]
<img width="412" alt="screen shot 2017-01-12 at 4 57 21 pm" src="https://cloud.githubusercontent.com/assets/4975959/21909988/39cbb17c-d8e8-11e6-8c09-0c120d2fc708.png">

**Comment by lakohl** [comment]
Resolve moving back and forth between all pages

**Comment by lakohl** [comment]
Newest version of the progress indicator is at the top.

**Comment by lakohl** [comment]
@shanear why can't people use the progress indicator to move forward to pages where they've already been?

**Comment by shanear** [comment]
@lakohl it's possible, it will just be complicated. Can we add it as a seperate story?

**Comment by lakohl** [comment]
After discussing with @shanear leaving this as is.

**Comment by lakohl** [comment]
@nikitarockz 'Verify that when on the EP Creation page, the Progress Indicator is set to "Route Claim" as the current step.' This should be also be the case on the 'Route Claim' page which substitutes the EP Creation page for Special Issues when an EP is not created. e.g. https://github.com/department-of-veterans-affairs/caseflow/issues/884

**Comment by sharonwarner** [comment]
@lakohl When running unit tests, I'm getting an accessibility error: 'Elements must have a contrast ratio of above 4.5:1'. It's complaining that the unactivated parts of the progress bar aren't contrasting enough with the background. Is there another color we could use for the unactivated parts?

**Comment by lakohl** [comment]
Gotcha. We suspected this might be the case. Can you use what exists for now and we will update the colors by the end of the week. @gnakm do you want to take a stab at this?

**Comment by Chingujo** [comment]
Some mock variants based on the contrast test results @gnakm @lakohl @KHarshawat 

<img width="590" alt="screen shot 2017-03-08 at 11 30 28 am" src="https://cloud.githubusercontent.com/assets/23316107/23713084/c5f60726-03f2-11e7-8f35-2b55ce4427bb.png">

**Comment by gnakm** [comment]
I vote the 3rd, the one in canvas with blue and grey. I think the progress bar pops more and there is more contrast between blue, grey and white. 

What color will `3. Confirmation` be? I think as long as the color of that text passes the color contrast checker, we're good.

**Comment by Chingujo** [comment]
Good call. If we darken the color to "gray" instead of "light-gray" which  passes the test (the next color up) it passes the contrast. Here is what it would like it. 

For reference here is the link: http://webaim.org/resources/contrastchecker/. Thanks @gnakm for this =D

<img width="766" alt="screen shot 2017-03-08 at 12 04 13 pm" src="https://cloud.githubusercontent.com/assets/23316107/23717023/356a2b02-0400-11e7-8e87-c346a2dd68ea.png">

**Comment by Chingujo** [comment]
@gnakm @lakohl 

# Progress Bar:

- [ ] All text color is 5B616B
  - Bold for completed steps and regular weight for future steps 
- [ ] Completed Bar Color is 5B616B and to be completed is AEB0B5


<img width="586" alt="screen shot 2017-03-09 at 2 03 34 pm" src="https://cloud.githubusercontent.com/assets/23316107/23766017/400a709a-04d1-11e7-8dfb-e0a2a91419a5.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT

Steps to Validate: 
1. Go to Dispatch as a caseworker and go through the steps of creating an EP
2. Validate that Review Decision, Create End Product and Confirmation pages reflect the corresponding progress bar changes. 

Screenshots: 
![caseflow dispatch 1](https://cloud.githubusercontent.com/assets/23038505/23813386/a6b82bbc-05ac-11e7-956e-fc9b8ffea753.png)
<img width="1355" alt="screen shot 2017-03-10 at 4 11 50 pm" src="https://cloud.githubusercontent.com/assets/23038505/23813407/bbe18858-05ac-11e7-98bd-d5a88ed3518a.png">
<img width="1339" alt="screen shot 2017-03-10 at 4 12 12 pm" src="https://cloud.githubusercontent.com/assets/23038505/23813408/bbe31ec0-05ac-11e7-88b6-aaa800714b0a.png">
