### ISSUE TITLE
Should Caseflow Logo be linked 

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#6170]
This is what we have 
<img width="264" alt="screen shot 2018-07-10 at 2 38 15 pm" src="https://user-images.githubusercontent.com/1745984/42530326-ea79f5b6-844e-11e8-8e10-feec2224a049.png">
the icon is not part of the caseflow link

Question is if we should make the link like the below
![screen shot 2018-07-11 at 10 12 53 am](https://user-images.githubusercontent.com/1745984/42577796-2b26f6b4-84f3-11e8-955e-4bdbf0c05777.png)

**Comment by lakohl** [comment]
@nolawi I think the answer is yes, but can you give a bit more context?

**Comment by nolawi** [comment]
@lakohl updated

**Comment by lakohl** [comment]
appreciate it. I think the logo should be included in the link
