### ISSUE TITLE
Judges queue | update attorney sidebar design

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6195]
Update judge queue attorney sidebar to reflect current designs.

## AC
- The attorney caseload sidebar is updated per designs, reusing the Case details sidebar already implemented - https://github.com/department-of-veterans-affairs/caseflow/issues/5736

## Currently on demo
<img width="448" alt="screenshot 2018-10-10 10 14 07" src="https://user-images.githubusercontent.com/1598889/46753703-6a368d00-cc75-11e8-91e9-7ea5df9845de.png">

## Desired: match the sidebar that is already live in case details (with the active state being the dark gray)
<img width="578" alt="screenshot 2018-10-10 10 03 18" src="https://user-images.githubusercontent.com/1598889/46753702-699df680-cc75-11e8-9d46-297df8354157.png">

**Comment by mkhandekar** [comment]
If I were to prioritize one of the bullets, I would do the sidebar first!  🎉

**Comment by laurjpeterson** [comment]
Edited this issue to only be about updating the attorney sidebar.

**Comment by mkhandekar** [comment]
I think this is live. Right @evankroske?

**Comment by mkhandekar** [comment]
I've updated the original post with designs.
