### ISSUE TITLE
AMA Intake | Set the EP benefit type correctly

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6205]
Right now, we always set `benefitTypeCd` to `1` which represents a "C&P Live" claim. However, if the veteran is deceased we need to create a "C&P Death" claim represented by a `benefitTypeCd` of `2`.

## Acceptance criteria
- Check if the Veteran is deceased (somewhere in BGS)
- When processing an AMA HLR or SC, and the veteran is deceased (BGS), the `benefitTypeCd` for the EP should be set to `2` for all EPs created

## Technical notes
- Here is the value that should be passed to connect_vbms to change the benefitTypeCd: https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/lib/vbms/requests/establish_claim.rb#L74

**Comment by shanear** [comment]
Nate said this is set in the UI by users. Would AMO want us to set this too manually?

**Comment by abbyraskinUSDS** [comment]
Erik understood the question, but did not want to make a unilateral decision without programs folk on the line. So, I'll send a follow-up email.

**Comment by kahlouie** [comment]
Still waiting on AMO. Big HVAC hearing is helping to cause delays.

**Comment by abbyraskinUSDS** [comment]
VBMS sets it as death if the veteran is not alive. VBMS defaults payee code to spouse instead of Veteran in this case. Date of death. If deceased death, the benefit type defaults to death. no reason to change default. So we should probably check if Veteran is deceased and default to 2 if so - and remove Veteran from payee code options?

**Comment by jiahuang** [comment]
@pkarman `date_of_death` was just added to the veteran model: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/veteran.rb#L12

According to the commit, looks like its nil for alive and has a value for deceased.

**Comment by pkarman** [comment]
Answered via slack: yes, regardless of form, set `benefitTypeCd`

**Comment by shanear** [comment]
I need to get some test data from Colin for a deceased vet before i can validate this

**Comment by shanear** [comment]
Sent an email to Colin. Waiting on that

**Comment by shanear** [comment]
Looks like this failed:

```
status_code=500, body=<env:Envelope xmlns:env=\"http://schemas.xmlsoap.org/soap/envelope/\"><env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Claim not established. Unable to successfully validate Veteran. GUID: 6eac4373-cefb-4178-9256-c73967aaeedb</faultstring><detail><ns2:dataValidationFaultDetailBean xmlns:part=\"http://vbms.vba.va.gov/cdm/participant/v5\" xmlns:ns2=\"http://vbms.vba.va.gov/external/ClaimService/v5\" xmlns:doc=\"http://vbms.vba.va.gov/cdm/document/v5\" xmlns:com=\"http://vbms.vba.va.gov/cdm/common/v5\" xmlns:claim=\"http://vbms.vba.va.gov/cdm/claim/v5\" xmlns:aw=\"http://vbms.vba.va.gov/cdm/award/v4\"><ns2:formFieldErrors><ns2:fieldName>claim.payeeCd</ns2:fieldName><ns2:errorType>INVALID_DATA_VALUE</ns2:errorType><ns2:message>Verify payee code 02 is correct for benefit type CPD.</ns2:message></ns2:formFieldErrors></ns2:dataValidationFaultDetailBean></detail></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::EstablishClaim:0x0000555dc072cfb8 @veteran_record={:sex=>\"M\", :ssn=>\"564930680\", :address_line1=>\"11737 SUNNINGDALE PL\", :address_line2=>nil, :address_line3=>nil, :city=>\"WALDORF\", :state=>\"MD\", :country=>\"USA\", :zip_code=>\"20602\", :service=>[{:short_service_number=>nil, :service_number_fill=>nil, :branch_of_service=>\"CG  \", :entered_on_duty_date=>\"01011990\", :released_active_duty_date=>\"01011995\", :separation_reason_code=>\"SAT\", :nonpay_days=>nil, :pay_grade=>nil, :char_of_svc_code=>\"HON\"}, {:short_service_number=>nil, :service_number_fill=>nil, :branch_of_service=>nil, :entered_on_duty_date=>nil, :released_active_duty_date=>nil, :separation_reason_code=>nil, :nonpay_days=>nil, :pay_grade=>nil, :char_of_svc_code=>nil}, {:short_service_number=>nil, :service_number_fill=>nil, :branch_of_service=>nil, :entered_on_duty_date=>nil, :released_active_duty_date=>nil, :separation_reason_code=>nil, :nonpay_days=>nil, :pay_grade=>nil, :char_of_svc_code=>nil}], :date_of_birth=>\"01/01/1970\", :date_of_death=>\"12/01/2016\", :file_number=>\"564930680\", :address_type=>\"\", :first_name=>\"Zero\", :last_name=>\"Brad\", :name_suffix=>nil}, @claim={:benefit_type_code=>\"2\", :payee_code=>\"02\", :predischarge=>false, :claim_type=>\"Claim\", :end_product_modifier=>\"035\", :end_product_code=>\"030HLRNR\", :end_product_label=>\"Higher-Level Review Nonrating\", :station_of_jurisdiction=>\"397\", :date=>Fri, 10 Aug 2018, :suppress_acknowledgement_letter=>false, :gulf_war_registry=>false, :claimant_participant_id=>\"600215162\"}, @v5=true>
```

**Comment by pkarman** [comment]
interesting. The error message says:
> Verify payee code 02 is correct for benefit type CPD.
which is the correct payee code if the veteran is deceased, which according to the record:
> :date_of_death=>"12/01/2016"
they are.

**Comment by leikkisa** [comment]
I'm thinking the payee code for this intake should be "10" which is for Spouse the participant ID's claimant is that of the spouse).  The 02 payee code stands for: Second Payee Recipient | 2, no idea what that means.

At one point we had planned on filtering out the payee code list to just the relevant ones, so this seems like fixing this would be related to that ticket.  
https://github.com/department-of-veterans-affairs/caseflow/issues/6842

We need to do some research on which payee codes are available in which circumstances.  Shane had said we might be able to get some info on this based on the dropdowns in VBMS.  There's also this, just have to figure out how to use StandardDataWebService :-P.

This is where we can find out which payee codes are valid for which end product type:
StandardDataWebService.findPayeeCdsByBnftClaimTypeCd

shareComndTypeCd = CEST
pgmTypeCd = CPL or CPD (CPL is live veteran, CPD is a death claim)
svcTypeCd = CP
bnftClaimTypeCd = your EP label, eg 030HLRR

**Comment by pkarman** [comment]
ah you're right @leikkisa -- I was conflating payee code and benefit type code (the latter is the topic of this ticket).

So the benefit type code is being set correctly, but the payee code is now not correct.

**Comment by shanear** [comment]
<img width="887" alt="screen shot 2018-10-09 at 5 16 20 pm" src="https://user-images.githubusercontent.com/1596259/46699207-12514500-cbe7-11e8-909d-7d1cf532dd00.png">

Nice this works
