### ISSUE TITLE
End Product: Existing EP:  Assign existing EP to complete Establish Claim task

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#621]
As a Caseworker, I would like to have the selected existing EP assigned to the current Establish Claim task so that it is marked as completed.

## Acceptance Criteria
1. Verify that after clicking on the **_Assign to Claim_** button for the selected claim, that claim ID is associated with the current Establishment Claim task.
1. Verify that after clicking on the **_Assign to Claim_** button, the current Establish Claim task "Status" is set to "Completed" as seen on the Manager Home page.
1. Verify that after clicking on the **_Assign to Claim_** button, the current Establish Claim task "Action" is set to "Assigned Existing EP" as seen on the Caseworker Home page.
1. Verify that after clicking on the **_Assign to Claim_** button for a selected existing EP, the End Product Confirmation page is displayed. (can be minimal for now, design captured in https://github.com/department-of-veterans-affairs/caseflow/issues/627)

## Mockup 
**_View - Existing EP page_**
![image](https://cloud.githubusercontent.com/assets/23063044/21634049/3cccea2a-d222-11e6-97d0-fdb6e2f29d0f.png)

# Related Stories
Decision Review: Create EP: Show potential EP duplicates on a page before EP Creation form #615

**Comment by lakohl** [comment]
<img width="563" alt="screen shot 2017-01-03 at 5 48 17 pm" src="https://cloud.githubusercontent.com/assets/4975959/21626040/de8c1a2a-d1dc-11e6-9281-e5c830d7694f.png">

**Comment by nikitarockz** [comment]
@lakohl updated.

**Comment by shanear** [comment]
For AC 3. shouldn't action be "Preexisting EP" or something like that to distinguish tasks where an EP was created with caseflow, and ones where a preexisting EP was assigned to the task?

@lakohl @nikitarockz

**Comment by lakohl** [comment]
@shanear I updated the description above to record the action as 'Assigned Existing EP' and I deleted AC 4.

**Comment by astewarttistatech** [comment]
**PASSED IN DEMO, BUT STILL NEEDS TO BE VALIDATED IN UAT**

@shanear 

Caseworker is prompted to duplicate EP page, after "Assign to Claim" button is selected the Caseflow loading animation appears and takes caseworker to success page. Please see below. 


<img width="1033" alt="screen shot 2017-01-11 at 4 25 47 pm" src="https://cloud.githubusercontent.com/assets/23038505/21902926/cf714e66-d8cb-11e6-9d0c-8faeea882250.png">
<img width="721" alt="screen shot 2017-01-12 at 1 31 08 pm" src="https://cloud.githubusercontent.com/assets/23038505/21902928/cf73b5c0-d8cb-11e6-9b89-799e2c72eae9.png">
<img width="736" alt="screen shot 2017-01-12 at 1 31 33 pm" src="https://cloud.githubusercontent.com/assets/23038505/21902927/cf721094-d8cb-11e6-861f-a3a8ce31bc4b.png">
