### ISSUE TITLE
Editing VBA Issues | Edit rating issues selection page

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6210]
When a VBMS user needs to modify claim issues under review after an intake is completed for a Higher Level Review or Supplemental Claim, they can navigate to a "Edit Claim Issues" page and then an issue selection screen in Caseflow, so they can accurately represent the requested issues while maintaining the connection to the original rated issue.

## Acceptance Criteria
- Within the editing flow, selecting the "Edit issues" link navigates the user to the list of issues page. 
- The page shows all available issues within the 372 day timeframe. Any issues previously saved will be selected by default.
- Note: the progress bar is not displayed on this screen
- Note: variation showing what previously selected "other" issues looks like during edit flow is covered in #6368 
- Note: mockup doesn't reflect the new "add issue" button style changed via #6384.

## Mocks
<img width="778" alt="edit issues" src="https://user-images.githubusercontent.com/11219417/42759265-63a6c50c-88d4-11e8-8bae-5c6ae1411b9f.png">

## Related stories
department-of-veterans-affairs/appeals-design-research#862

## Validation instructions
Test this at the same time as 6181. 
- From the landing page (in 6181), click the edit issues link to navigate here and/or go directly to https://appeals.cf.uat.ds.va.gov/intake/higher_level_reviews/600136115/edit/select_issues.
- It should bring you to the Select Issues page. Check that it matches the design. Note that the save and cancel will be added in a later story.

**Comment by kahlouie** [comment]
should follow #6181

**Comment by kahlouie** [comment]
Suzanne will create a non-rating issue issue

**Comment by kahlouie** [comment]
@suzchap I'm gonna get started on this, but try to ignore all the nonratings issues as previously discussed

**Comment by kahlouie** [comment]
@suzchap I'm removing `If you are unable to find one or more issues, enter these in the "other issues" section.` since we're not including unratings issues on this story.

**Comment by kahlouie** [comment]
@suzchap What should the cancel button do? When should it be used?

**Comment by kahlouie** [comment]
Test this at the same time as 6181. Click the edit issues link on the landing page to navigate here and/or go directly to `https://appeals.cf.uat.ds.va.gov/intake/higher_level_reviews/600132141/edit/select_issues`.

**Comment by suzchap** [comment]
@kahlouie The Cancel button should just close the window.

**Comment by kahlouie** [comment]
@suzchap I think this is ready for validation. We had decided after I asked that we'd save that for a later story as it's unnecessary for getting the rest of it validated. That said, this'll all change soon, so not sure it's worth validating.

**Comment by shanear** [comment]
validation is blocked on https://github.com/department-of-veterans-affairs/caseflow/issues/7138

**Comment by shanear** [comment]
![screen shot 2018-09-28 at 12 26 10 pm](https://user-images.githubusercontent.com/1596259/46220996-d29e7980-c319-11e8-86ff-147bd65e7715.png)
looking good.
