### ISSUE TITLE
Editing VBA issues | Saving edited issues as contentions on existing EP

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6212]
This is the simplest outcome of successfully editing EP issues - issues are added or removed under the existing EP and reflected as contentions in VBMS. (rating -> rating or non-rating -> non-rating)

## Acceptance Criteria
- The "Save" button is grayed out until a change is made, then it's the default blue button color.
- Clicking the "Save" button should trigger changing the issues.
- When the issues are saved, if issues of the same type (rated or non-rated) are added or removed to/from an existing EP, the new contentions are saved in VBMS under the same EP code and label

## Technical Notes
- To do this, we will have to remove any contentions for issues that were removed. This could be done via the `removeContention` endpoint in the VBMS claims service.

requires https://github.com/department-of-veterans-affairs/connect_vbms/issues/190

## Mocks
<img width="778" alt="edit issues" src="https://user-images.githubusercontent.com/11219417/42765672-8dd06fc4-88e6-11e8-9d44-ed7d0ef30b06.png">

## Related stories
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/862

## Validation

1. Visit https://appeals.cf.uat.ds.va.gov/higher_level_reviews/600134030/edit/select_issues
1. Select/deselect issues to test the following cases
   1. No change -> button is disabled gray
   1. Deselect all issues -> hitting save displays a 'no issues selected' error message
   1. Select some issues (a different selection than original) -> hitting save redirects back to /edit when the request completes
   1. Note that while saving, the button should be disabled, though this might be very brief
1. Go to VBMS, look up test file number 123458304
1. look up claim id 600134030, the higher level review we just updated
1. Verify that contentions match the issues selected above in 2.3
1. An engineer could check for:
   1. the removed_at timestamp being set for any request_issues that were deselected
   1. review_request_id is set to nil for any request_issues that were deselected
   1. the rating_issue_associated_at is set for any newly created request_issues

**Comment by leikkisa** [comment]
Wait until edit framework is done to get started on this

**Comment by shanear** [comment]
@suzchap what happens if a user doesn't change anything and clicks save?

**Comment by shanear** [comment]
Asked this in person, the decision is that the Save button should be disabled until a change is made.

**Comment by kencheeto** [comment]
@suzchap I've got this working and failure modes show an alert (you can see in https://github.com/department-of-veterans-affairs/caseflow/pull/7017). However, I'm not sure what to show when the update succeeds - right now the button becomes disabled again (because there are 'no changes') but there is nothing else to indicate that the save worked.

Completing an intake takes you to a 'Complete' page - is there something like that we could add in a followup issue?

**Comment by leikkisa** [comment]
We have green "success" messages that look kind of like the error messages. We could do that. Or we could send them back to the landing page.

**Comment by suzchap** [comment]
We have plans for a v.2 of the editing flow so if sending back to landing page is easy, go with that and we'll have a fuller solution in the next round. Thanks!

**Comment by shanear** [comment]
This appears to be broken 😢 

Looking into why.

**Comment by shanear** [comment]
![screen shot 2018-09-28 at 12 59 53 pm](https://user-images.githubusercontent.com/1596259/46222469-6eca7f80-c31e-11e8-92a1-c38b2ecbbff4.png)

`VBMSService.removeContention` has a syntax error 🙃

**Comment by shanear** [comment]
Works for adding issues! But removing issues is still bugging out
https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1006/
![screen shot 2018-10-01 at 2 36 19 pm](https://user-images.githubusercontent.com/1596259/46308359-6a54cf80-c587-11e8-8f6d-81665af9988e.png)

looking into it

**Comment by shanear** [comment]
This is caused by https://github.com/department-of-veterans-affairs/caseflow/issues/7201

Adding that bug to track it.

**Comment by shanear** [comment]
<img width="1434" alt="screen shot 2018-10-01 at 6 41 38 pm" src="https://user-images.githubusercontent.com/1596259/46319863-b6b10700-c5a9-11e8-901d-dc726b252af1.png">
works!
