### ISSUE TITLE
Editing VBA issue | Saving edited issues triggers new EP establishment

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6213]
While fixing the issues originally created during intake for the claim, if the issues change from all rated to a mixture of non-rated and rated (or vice-versa), there needs to be a new EP to track both types of claim issues. This story captures the "Save" scenario where we need to create a new EP. (i.e. rating -> rating + non-rating)

## Acceptance Criteria
- If the edited EP issues are edited to include a category of issue (Rating or Non-rating) that did not previously have any issues on the EP, then Caseflow should create the appropriate new EP and attach the new issues to that EP.
- If the EP created above was part of a Higher Level Review where an informal conference was requested, Caseflow should also generate an Informal Conference tracked item (see: https://github.com/department-of-veterans-affairs/caseflow/issues/7118 for more information)

## Example
If an HLR with 1 non-rating issue, X, is edited to have both non-rating issue, X, and a new rating issue, Y, then we would create an additional rating EP and attach issue Y to it.

requires #6148 
requires #7269

**Comment by jiahuang** [comment]
Looked through some code and I believe that this is already being done.

Upon a higher level review or supplemental claim update, we call `request_issues_update.perform!` which in turn calls `review.create_issues!(new_issues)` which creates new eps if needed for each issue.

Will add tests to confirm functionality.

**Comment by leikkisa** [comment]
Yeah, during sprint planning we suspected that but thought it'd be good for someone to confirm!  Thanks for looking at it and adding tests!

**Comment by shanear** [comment]
<img width="811" alt="screen shot 2018-11-01 at 6 56 15 pm" src="https://user-images.githubusercontent.com/1596259/47884724-472c7280-de08-11e8-937d-1d8feaea4fc8.png">

<img width="797" alt="screen shot 2018-11-01 at 6 59 58 pm" src="https://user-images.githubusercontent.com/1596259/47884754-6aefb880-de08-11e8-8949-dea26576d744.png">

Nice! This is working 👍
