### ISSUE TITLE
Editing VBA issues | Save edits scenario where we need to cancel irrelevant EPs

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6214]
While fixing the issues originally created during intake for the claim, if the issues change from rated to non-rated or vice-versa, the EP label would need to change too. This story captures the "Save" scenario where we need to cancel the existing EP and create a new one with the accurate claim label. (i.e., rating -> non-rating)

## Acceptance Criteria
- If the edited EP issues remove an entire category (rating or non-rating) of issues from the review, then Caseflow should cancel that EP

## Example
A user edits a Supplemental claim with rating issue, X, and non-rating issue, Y. They change issue Y to a rating issue, leaving no more non-rating issues as part of the supplemental claim. Caseflow should cancel the non-rating supplemental claim EP associated with that supplemental claim.

## Technical notes
You can cancel an EP by using the `claims.cancel_end_product` method in Ruby BGS (see: https://github.com/department-of-veterans-affairs/ruby-bgs/blob/master/lib/bgs/services/benefit.rb#L37)

requires #6213 
requires #7269

**Comment by shanear** [comment]
This is failing. I think due to this error: https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1061/

**Comment by shanear** [comment]
new error 🙁 

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1087/

**Comment by shanear** [comment]
woohoo, it worked 🔥 🔥 
<img width="772" alt="screen shot 2018-11-06 at 4 51 37 pm" src="https://user-images.githubusercontent.com/1596259/48096074-49197b80-e1e4-11e8-88eb-70eccb32de57.png">
