### ISSUE TITLE
Editing VBA issues | Editing issues confirmation page (no EP changes)

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6216]
When a VBMS user modifies claim issues after an intake is completed for a Higher Level Review or Supplemental Claim in Caseflow, they will receive a confirmation page so they know the edit was successful.

## Acceptance Criteria
- Selecting the "save" button on the "Edit issue selection page" navigates user to a confirmation page.
- For the associated Higher Level Review or Supplemental Claim EP, the page shows:
   - Name of the form, Veteran name and ID, instructions to go to VBMS to edit other details, and confirmation that contentions were updated and that the EP was updated with EP code and label. (see mock)

## Mocks
<img width="731" alt="edit confirmation screen" src="https://user-images.githubusercontent.com/11219417/42760221-c13a1e96-88d7-11e8-9a74-322e95561672.png">

## Copy Example
Claim Issues Saved!
Issues for Seven Wright’s (984562357) Request for Supplemental Claim have been saved. 
Go to VBMS to view claim details for EP 030 - Supplemental Claim.
Contentions updated
Updated EP: 040SCR - Supplemental Claim Rating for Station 397 - ARC

## Related stories
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/862

**Comment by shanear** [comment]
dup of #7313
