### ISSUE TITLE
End Product: Don't display already used modifiers

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#622]
As a Caseworker, I would like to limit the the Modifers eligible for selection based on the selected EP Code so that I can reduce the possibility of human error.

# Acceptance Criteria
1. Verify that if the EP Code (concatenated value **_"EP & Claim Label"_**) is 170 and no other EPs exist, the following Modifier options are available: 170, 171, 175, 176, 177, 178, 179
1. Verify that if the EP Code is 170 and there are existing EPs, the list of available Modifier options excludes the ones that already exist.
1. Verify that if the EP Code is 172, the Modifier is set to 172 and uneditable.
1. Verify that after changing the _"Decision Type"_ for the EP Code on the Decision Review page, the correct Modifiers are available for selection based on the change. (Note: Change can produce error.  Refer to related stories.) 

# Mockup
**_View - End Product Page - Modifier_**
![image](https://cloud.githubusercontent.com/assets/23063044/22002258/7e4e17da-dc18-11e6-91f2-fb5883ab7bba.png)

**_View - Decision Review Page - Changing the Decision Type for EP Code_**
![image](https://cloud.githubusercontent.com/assets/23063044/22002332/2d5f61a2-dc19-11e6-8bf7-1779c9a05400.png)

# Related Stories
Existing EP: Error if there are no valid modifiers #636

**Comment by lakohl** [comment]
Assigning it to myself for error message

**Comment by lakohl** [comment]
This seems related to: https://github.com/department-of-veterans-affairs/caseflow/issues/475

**Comment by lakohl** [comment]
@abbyraskin could you confirm that what is listed at the top is correct?

**Comment by abbyraskin** [comment]
@lakohl looks good to me!

**Comment by abbyraskin** [comment]
@lakohl I added 177 as a modifier option.

**Comment by lakohl** [comment]
@abbyraskin are you sure 177 is an option? I have a feeling that @cmgiven thought it might not apply?

**Comment by cmgiven** [comment]
I don't recall that, but my mind these days...

**Comment by abbyraskin** [comment]
The manual says...

<img width="514" alt="screen shot 2017-01-12 at 3 52 13 pm" src="https://cloud.githubusercontent.com/assets/4042181/21907812/2755c75c-d8df-11e6-929c-c106807112b3.png">

**Comment by cmgiven** [comment]
Praise be to the manual, source of all truth and goodness in the land!

**Comment by lakohl** [comment]
Thank you both! Sorry for the confusion.

**Comment by kierachell** [comment]
Able to test Partial/Remand modifiers.
<img width="422" alt="screen shot 2017-01-18 at 10 02 26" src="https://cloud.githubusercontent.com/assets/18075411/22069123/568c3814-dd65-11e6-8955-0b92e151a451.png">

Can't test 172 because there are no test data for that (blocked by duplicate EP)

**Comment by shanear** [comment]
Two issues with this:
1) Cleared EPs should not block the usage of a modifier.
2) This is only taking into account EPs made in the last 30 days, which is not correct. Any open EP (regardless of claim date) should block the modifier.

**Comment by kierachell** [comment]
Trying a Full Grant:
<img width="613" alt="screen shot 2017-01-26 at 11 26 23" src="https://cloud.githubusercontent.com/assets/18075411/22341082/8cc8ed24-e3bd-11e6-94b0-1ff071864552.png">

Partial/Remand with no other EPs:
<img width="644" alt="screen shot 2017-01-26 at 11 23 50" src="https://cloud.githubusercontent.com/assets/18075411/22341103/9b1532fc-e3bd-11e6-99ba-076ae4d70c20.png">
<img width="603" alt="screen shot 2017-01-26 at 11 34 32" src="https://cloud.githubusercontent.com/assets/18075411/22341108/9dc7bb3c-e3bd-11e6-9a3e-1c091c196687.png">

With Existing EPs:
<img width="1214" alt="screen shot 2017-01-26 at 11 24 37" src="https://cloud.githubusercontent.com/assets/18075411/22341124/a8c0ec48-e3bd-11e6-9a79-57c0b6d0aada.png">
<img width="604" alt="screen shot 2017-01-26 at 11 24 42" src="https://cloud.githubusercontent.com/assets/18075411/22341125/a8c0f300-e3bd-11e6-8d91-b2ebe785c37d.png">
and
<img width="532" alt="screen shot 2017-01-26 at 11 25 08" src="https://cloud.githubusercontent.com/assets/18075411/22341137/b19f4d78-e3bd-11e6-9341-389d9644d10b.png">
<img width="305" alt="screen shot 2017-01-26 at 11 25 13" src="https://cloud.githubusercontent.com/assets/18075411/22341136/b19e8ae6-e3bd-11e6-9f92-0efac1b025f5.png">
