### ISSUE TITLE
Locked ratings will block AMA intake

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6221]
Among the craziness of deploying the ratings services, we discovered an unfortunate bug.

The ratings endpoint we are using seems to fail if there is a rating currently in progress. It says that the rating is "Locked". This will cause the entire flow to fail.

We asked AMO how common it might be to have a rating locked at the same time an AMA review would be received, and they seemed to think that it could be significant. This is because it's locked when it's in a raters queue, which could be multiple days.

The solution here is to request that BGS allow the update the rating services to be allow reads even when the rating is locked.

**Comment by abbyraskinUSDS** [comment]
> The ratings endpoint we are using seems to fail if there is a rating currently in progress.

Does this mean if the rating for that specific issue is in progress, or any rating for that Veteran?

**Comment by abbyraskinUSDS** [comment]
From AMO call:
Basically, it sounds like we should explore getting BGS to change their service
- Mike Palmer: What constitutes it being locked? You can have several claims pulled in, but only actively working on one. Big difference -- "locked" vs. actively working on it. 
- Joshua Will thinks it's locked if it's pulled into the VBMS-R queue...

**Comment by mc-usds** [comment]
Will work with Nikita to submit the SR. 

Also as a side note, it seems like this bug would be affecting the Claim for Increase work being done on the Veteran Facing Tools side. I'm going to reach out to the EVSS guys to see if they have encountered it and if they've brought it to up with BGS or how they've worked around it, if at all.

**Comment by mc-usds** [comment]
service request id: SR-001373

**Comment by shanear** [comment]
Looks like we'll be waiting on an estimate of when this will be released to UAT. Earliest it could be released to prod would be with the December coordinated install.

**Comment by mc-usds** [comment]
Tested in UAT with (700017078 700017075) and the fix appears to working.
