### ISSUE TITLE
Case Details | Actions dropdown disappears on refresh

### ISSUE THREAD

**Issue by evankroske** [department-of-veterans-affairs/caseflow#6222]
## Steps to Reproduce the Issue
- Become BVAAABSHIRE.
- Go to /queue.
- Click on a case.
- Refresh the page.

## Example
![untitled](https://user-images.githubusercontent.com/357369/42710776-765cb008-86b3-11e8-80b5-589d527efa0a.gif)

**Comment by mdbenjam** [comment]
https://media.giphy.com/media/qyuxJs79G0PVC/giphy.gif
