### ISSUE TITLE
VACOLS Upload Success Page | Link to uploads

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6229]
- Update the message in the success alert (in BuildSchedule.jsx) to read 'You can view your uploaded schedule by clicking the link below'
- Add a link titled 'View schedule' that goes to 'hearings/schedule'

![successpage](https://user-images.githubusercontent.com/4306128/42728073-28a41a90-8780-11e8-86bf-9e864aafdea3.png)

**Comment by Chingujo** [comment]
Sounds good @sharonwarner 

How about just:

"View schedule" 

Keeps the copy short and removes the filtered view aspect of it
