### ISSUE TITLE
End Product:  Decision Type determines EP & Claim Label

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#623]
As a Caseworker, I would like to have the "EP & Claim Label" value determined by the "Decision Type" selected on the Decision Review page and cannot be edited so that it reduces the chance of user error.

## Acceptance Criteria
1. Verify that the when the value of _"Decision Type"_ is "Full Grant" on the Decision Review page, the _"EP & Claim Label"_ value is to "172BVAG - BVA Grant" on the End Product page (refer to mockup).
1. Verify that the when the value of _"Decision Type"_ is "Partial Grant" on the Decision Review page, the _"EP & Claim Label"_ value is to "170PGAMC - AMC-Partial Grant" on the End Product page.
1. Verify that the when the value of _"Decision Type"_ is "Remand"on the Decision Review page, the _"EP & Claim Label"_ value is to "170RMDAMC - AMC-Remand" on the End Product page.
1. Verify that the _"EP & Claim Label"_ field cannot be edited and grayed out.
1. Verify that the _"EP & Claim Label"_ field no longer has a "Required" label.

# Mockup
**_View - Decision Review Page - Decision Type Selected_**
![image](https://cloud.githubusercontent.com/assets/23063044/21644530/d8fdadb0-d25b-11e6-9b35-21f8da8f7b0b.png)

**_View - End Product Page - EP & Claim Label_**
![image](https://cloud.githubusercontent.com/assets/23063044/21633029/ac7b0ffe-d219-11e6-91dc-5667597f41f5.png)

# Related Stories

**Comment by nikitarockz** [comment]
@lakohl This is done.

**Comment by shanear** [comment]
@lakohl Should this field also be grey like "Benefit Type" and "Payee"?

**Comment by lakohl** [comment]
@shanear yes, let's try to having the EP & Claim label appear pre-selected and uneditable. In this case it does not have to be a dropdown.

**Comment by kierachell** [comment]
The dropdown appears correctly:
<img width="1098" alt="screen shot 2017-01-09 at 11 44 40" src="https://cloud.githubusercontent.com/assets/18075411/21776059/a30781b8-d666-11e6-8577-8d084eda6f86.png">



And has 3 selectable values:
<img width="1156" alt="screen shot 2017-01-09 at 11 45 44" src="https://cloud.githubusercontent.com/assets/18075411/21776066/a877d0c6-d666-11e6-9514-1a5262164ed4.png">


That are reflected in __EP & Claim Label__ field appropriately:
<img width="496" alt="screen shot 2017-01-09 at 11 45 51" src="https://cloud.githubusercontent.com/assets/18075411/21776070/adf4d67a-d666-11e6-800b-3a9248577f62.png">
👍 


<img width="475" alt="screen shot 2017-01-09 at 11 46 07" src="https://cloud.githubusercontent.com/assets/18075411/21776071/ae1c202c-d666-11e6-9922-f2eef2d11287.png">
👍 
The value is uneditable and is greyed out


<img width="471" alt="screen shot 2017-01-09 at 11 46 33" src="https://cloud.githubusercontent.com/assets/18075411/21776072/ae2f75f0-d666-11e6-852b-421d8b2e87f1.png">
👍
