### ISSUE TITLE
Audit feature toggles and see which ones can be removed

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6231]
We should go through the Queue feature toggles and see if any feature toggle code can be removed. Let's also make a note here of feature toggle code we can remove in the near future.

**Comment by dannysellers** [comment]
Phase two:
```
$ grep -R phase_two app/queue/
app/queue//AttorneyTaskTable.jsx:        width: this.props.featureToggles.phase_two ? '25%' : ''
app/queue//CaseSnapshot.jsx:      { this.props.featureToggles.phase_two &&
```

The first one should already be removed—is vestigial from when the start checkout flow dropdown was in AttorneyTaskTable
