### ISSUE TITLE
Allow users to set payee code during intake

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#6234]
## Story
For 3 AMA lanes, when entering a claimant other than the Veteran, I want to select the payee code so the VSR can process the claim.

If the claimant is other than Veteran, once the claimant is selected from presented options, it will show a list of relationships and the type of relationship. The user will then need to select the payee code. For now, we will show the entire list of possible payee codes, and optimize in the future.

## Technical notes
Payee code should be stored in the database, and sent to VBMS when establishing a claim
Depending on VBMS validation, it's possible that this will have to happen concurrently with setting the claimant participant ID when establishing the claim in VBMS

## Acceptance criteria
- Once the Claimant is selected, a searchable drop-down menu appears that contains the entire payee code list.

## Copy
- Field label: "What is the payee code for this claimant?"
- Drop down contents: [listed here](https://github.com/department-of-veterans-affairs/caseflow/issues/5878#issuecomment-409051820)

## Mocks
<img width="618" alt="screen shot 2018-07-31 at 9 14 47 am" src="https://user-images.githubusercontent.com/11219417/43461747-3a5b5be8-94a2-11e8-8cbb-1e4fecd3c132.png">

## Related issues
- #5878 

## How to Validate
- Test user criteria: AMA with dependents
- Steps to get there: Original intake flow, 3 AMA lanes (SC, HLR, Board) > Choose claimant isn't Veteran > select name > see payee codes
- Choose a payee code that matches the claimant relationship, e.g. choose "Spouse" and "Spouse"
- Dev team to check that the payee is stored in the database
- Check if the payee code is set on the claim (VBMS to help)

Validation for #5281 can happen at the same time

**Comment by abbyraskinUSDS** [comment]
@suzchap this would be a good one to get ready for dev soon if possible

**Comment by kahlouie** [comment]
Should be sent at the same time as the other claimant and we should store payee code in our db.

**Comment by kahlouie** [comment]
Only adding the payee code selection

**Comment by suzchap** [comment]
I began validation with test user 564930680 and chose payee code 99. When I went to create the EP on the "finish" page, I got the "something went wrong" error so I canceled the intake.

Once that's resolved, I guess I'll need to submit again? Or will we be able to check the last two bullets in the "how to validate" section without actually creating an ep?

@kahlouie or @shanear can one of you help with this or should we wait for Sally to be back?

**Comment by shanear** [comment]
Let's wait for sally to get back

**Comment by leikkisa** [comment]
@suzchap Can we try again by selecting Spouse, and payee code 10?  Not all of the payee codes are valid, but it's still a "to do" item to figure out which payee codes are valid per claim type using StandardDataWebService.findPayeeCdsByBnftClaimTypeCd.

I can't remember if I manually validated this in VBMS or not, but it would make sense to do that too so that we can get the error code.

We might also need to add the benefit claim type before we can use this.

**Comment by suzchap** [comment]
@leikkisa Hmmm, now I can't even get past the ID lookup and keep getting "You don't have permission to view this Veteran's information​".... I tried it with these test caseflow users: CASEFLOW_283, CF_SCOTTY_283, CF_LAFORGE_283, CF_Q_283

**Comment by shanear** [comment]
<img width="878" alt="screen shot 2018-09-25 at 5 43 10 pm" src="https://user-images.githubusercontent.com/1596259/46045067-891c1780-c0ea-11e8-9753-eb94e05eaba2.png">
works!
