### ISSUE TITLE
Decision Review: Add "Decision Type" dropdown and prepopulated from VACOLS

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#624]
As a Casework, I would like to have the field "Decision Type" added as a dropdown and pre-populated by the claim's Decision Type value from VACOLS on the Decision Review page so that I am aware of the current value.
 
## Acceptance Criteria
1. Verify that there is a new field "Decision Type" displayed as an editable dropdown.
1. Verify that the "Decision Type" dropdown contains the following values (refer to mockup):
     - Full Grant
     - Partial Grant
     - Remand
1. Verify that the field "Decision Type" pre-populates/defaults to the VACOLS Decision Type value for the current claim.
1. Verify that after clicking on the **_Create End Product_** button, the "Decision Type' value is saved in the database.

## Mockup
**_View - Decision Review - New Field "Decision Type"_**
<img width="444" alt="screen shot 2017-01-04 at 11 21 16 am" src="https://cloud.githubusercontent.com/assets/4975959/21649510/f46f73d0-d26f-11e6-91b8-3d368b534ceb.png">

**_View - Decision Review - "Decision Type" values_**
<img width="458" alt="screen shot 2017-01-04 at 11 17 50 am" src="https://cloud.githubusercontent.com/assets/4975959/21649378/85b04d7a-d26f-11e6-9d67-45f8407c6e5f.png">

# Related Stories
Decision Review: Special Issue Categories #625

**Comment by lakohl** [comment]
@cmgiven can you provide the logic rules?

**Comment by cmgiven** [comment]
We're looking at the dispositions of the individual issues (ISSDC from the ISSUES table).

If it has at least one '1' and no '3's it is a full grant.
If it has at least one '3' and no '1's it is a remand.
If it has at least one '1' and at least one '3' it is a partial grant.

**Comment by cmgiven** [comment]
<img width="640" alt="screen_shot_2016-10-26_at_11 50 49_am" src="https://cloud.githubusercontent.com/assets/5375557/21621923/3687dbec-d1c9-11e6-8b4f-3c319a55825f.png">

**Comment by nikitarockz** [comment]
Sprint planning Notes:  @lakohl update mockup showing Decision Type dropdown values.

**Comment by lakohl** [comment]
@nikitarockz did it in real time!

**Comment by nikitarockz** [comment]
Cool Beans!!!

**Comment by mdbenjam** [comment]
@nikitarockz What does this mean:

"Verify that after clicking on the Create End Product button, the "Decision Type' value is saved in the database."

I don't think we have a database for dispatch. We're just creating an end product right?

**Comment by kierachell** [comment]
Ay, I didn't see this change happen!

**Comment by astewarttistatech** [comment]
@mdbenjam no one on our end tested this. 👎  I'm disappointed in you lol

**Comment by mdbenjam** [comment]
Ahh oh no! Good catch. I must have put fixed in the PR. I'll make sure to just use connect in the future.

**Comment by kierachell** [comment]
<img width="457" alt="screen shot 2017-01-09 at 13 01 43" src="https://cloud.githubusercontent.com/assets/18075411/21777234/03b7b3e8-d66c-11e6-8128-ca575831762c.png">
one thing to add: make the __"Full Grant"__ be the first item in the dropdown

**Comment by kierachell** [comment]
<img width="592" alt="screen shot 2017-01-10 at 18 44 29" src="https://cloud.githubusercontent.com/assets/18075411/21829573/dd1e9e96-d764-11e6-94b4-d92cbbbcd7c0.png">
looks good in `demo` 👍

**Comment by kierachell** [comment]
To Validate that the values are collected from VACOLS we need @shanear or someone else to check.

**Comment by shanear** [comment]
@kierachell Validated this with VACOLS
