### ISSUE TITLE
Decision Review | Add Special Issue Categories

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#625]
As a Caseworker, I would like the ability to select any special issues categories associated with the selected Decision Type so that I can provide additional classification to the end product.

 ## Acceptance Criteria
1. Verify that there is a Special Issue Category section (refer to mockup).
1. Verify that when the Decision Type is "Full Grant", the following list of Special Categories are displayed: 

- Rice Compliance
- Private Attorney 
- Waiver of Overpayment
- Pensions
- VAMC
- Incarcerated Veterans
- DIC - death, or accrued benefits 
- Education or Vocational Rehab 
- Foreign Claims
- DIC - death, or accrued benefits

1. Verify that when the Decision Type is "Partial Grant" or "Remands", the following list of Special Categories are displayed: 

- Manlincon Compliance 
- Rice Compliance 
- Private Attorney 
- Hearings - travel board & videoconference
- Home Loan Guaranty 
- Waiver of Overpayment 
- Education or Vocational Rehab 
- VAMC 
- Insurance 
- National Cemetery Administration
- Spina Bifida
- Radiation
- Non-rating Issues 
- Foreign Claims
- Incarcerated Veterans 
- Proposed Incompetency
- Manila Remand 
- Contaminated Water at Camp LeJeune 
- Mustard Gas 
- Dependencies 
- DIC - death, or accrued benefits
1. Verify that one or more Special Issue Category items can be selected.
1. Verify that after clicking on the **_Create End Product_** button, the _"Decision Type"_ and all selected Special Categories have been saved in the database.

## Mockup
**_View - Decision Review page - Special Categories_**
<img width="497" alt="screen shot 2017-01-03 at 3 28 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/21622147/1852db44-d1ca-11e6-9cf7-55d7dade41f0.png">

# Related Stories 
EPIC: End Product: Ability to create and submit an end product - [#1120](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1120)
Decision Review: Add "Decision Type" dropdown and prepopulated from VACOLS #624
Decision Review: Create End Product: Dispay Special Issue Cancellation Warning modal #634

**Comment by lakohl** [comment]
<img width="497" alt="screen shot 2017-01-03 at 3 28 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/21622147/1852db44-d1ca-11e6-9cf7-55d7dade41f0.png">

**Comment by lakohl** [comment]
I'm looking for the two different lists of Special Issue categories and will post them asap

**Comment by lakohl** [comment]
*Special Issue categories:*

**Full Grants**
Rice Compliance (routed to ROJ)
Private Attorney (routed to ROJ)
Waiver of Overpayment (routed to ROJ)
Pensions (routed to regional PMC)
VAMC (routed to 51 or 54)
Incarcerated Veterans(routed to ROJ)
DIC - death, or accrued benefits (routed to PMC)
Education or Vocational Rehab (if it's an education debt issue, gets routed to 307, 316, 331, 351, otherwise ROJ)
Foreign Claims (routed to Pittsburgh RO)
DIC - death, or accrued benefits (routed to PMC)

**Remand/Partial-specific**
Manlincon Compliance (routed to ROJ)
Rice Compliance (routed to ROJ)
Private Attorney (routed to ROJ)
Hearings - travel board & videoconference (routed to ROJ)
Home Loan Guaranty (routed to ROJ)
Waiver of Overpayment (routed to PMC)
Education or Vocational Rehab (if it's an education debt issue, gets routed to 307, 316, 331, 351, otherwise ROJ)
VAMC  (Routed to 51 or 54)
Insurance (ROJ)
National Cemetery Administration (?)
Spina Bifida (routed to ROJ)
Radiation (routed to ROJ)
Non-rating Issues (routed to ROJ)
Foreign Claims(routed to Pittsburgh RO))
Incarcerated Veterans (routed to ROJ)
Proposed Incompetency(routed to ROJ)
Manila Remand (routed to ROJ)
Contaminated Water at Camp LeJeune (routed to ROJ)
Mustard Gas (return to Muskogee 351) 
Dependencies (routed to ROJ)
DIC - death, or accrued benefits (routed to PMC)

*For Milestone 1 we will create EPs only for Special Issue categories that are routed to the ROJ.

**Comment by lakohl** [comment]
*For Milestone 1 we will create EPs only for Special Issue categories that are routed to the ROJ.

**Comment by nikitarockz** [comment]
Sprint Planning Notes;  @nikitarockz Remove values within ( ) from category list.

**Comment by mmlumba** [comment]
@lakohl @nikitarockz Does the order matter for the special issue checkboxes?

**Comment by lakohl** [comment]
@mmlumba are you still working on this? @abbyraskin I can provide some more info on how to display Special Issues

**Comment by mmlumba** [comment]
@lakohl yes

**Comment by lakohl** [comment]
@mmlumba we are thinking of having one longer list of special issue categories (the one you are using for Remands/Partial Grants) for all types of grants. You can implement that change. I have another issue open for Special Issue ordering and styling.

**Comment by abbyraskin** [comment]
@lakohl @mmlumba I'm editing the list slightly to reflect feedback from AMO.

**Comment by lakohl** [comment]
@abbyraskin which list did you edit? very top? User suggestion was for these three issues to appear at the top of the list: 
Rice
Manlicon
Pension
DIC
Education
Attorney Rep/Agent

**Comment by abbyraskin** [comment]
Yep, the very top. I didn't reorder but will do that now. Pension has a few different permutations now, so I will put that one after the other popular issues.

**Comment by astewarttistatech** [comment]
Tested in UAT but format is off @mmlumba 

There are no two columns for the Special Issue Categories. Please see attached image. 
<img width="927" alt="screen shot 2017-01-30 at 1 15 01 pm" src="https://cloud.githubusercontent.com/assets/23038505/22440396/4bb62346-e701-11e6-86bd-7f0afae94dcc.png">

**Comment by astewarttistatech** [comment]
Apparently this is undergoing a redesign. @lakohl Can you confirm? If so, I will put this as blocked until this is done.

**Comment by lakohl** [comment]
@astewarttistatech there we always supposed to be two columns for the special issue categories. (The latest design is below.) If it's possible to make two evenly spaced columns now that would be grand.  I also created another issue: #715 to clean up styling and to put the issues in alphabetical order, so we can also incorporate the 2 column task into that issue.

<img width="443" alt="screen shot 2017-01-28 at 10 56 38 pm" src="https://cloud.githubusercontent.com/assets/4975959/22469212/3ad6e9a0-e799-11e6-87f0-e0a154ab3600.png">

**Comment by nikitarockz** [comment]
# Updating Acceptance Criteria 
Following has been AC **_removed_**
1. Verify that the following list of Special Category check boxes are displayed.
     - _Manlincon_ Compliance 
     - _Rice_ Compliance
     - Education - GI Bill, dependents educational assistance, scholarship, transfer of entitlement
     - Vocational Rehab 
     - Private Attorney or Agent
     - DIC - death, or accrued benefits - United States
     - Pension - United States
     - Foreign pension, DIC - Mexico, Central and South American, Caribbean 
     - Foreign pension, DIC - all other foreign countries
     - Hearing - including travel board & videoconference 
     - Waiver of Overpayment
     - VAMC 
     - Incarcerated Veterans
     - Home Loan Guaranty
     - Insurance
     - National Cemetery Administration
     - Spina Bifida 
     - Radiation 
     - Non-rating issue
     - Incarcerated Veterans 
     - Mustard Gas  
     - Foreign claim - compensation claims, dual claims, appeals
     - U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian)
     - U.S. Territory claim - Philippines
     - U.S. Territory claim - Puerto Rico and Virgin Islands

**Comment by lakohl** [comment]
@nikitarockz I'm not sure what you mean in the comment above

**Comment by astewarttistatech** [comment]
Tested in UAT | Still broken :eyes: 

Screenshot: 
<img width="1229" alt="screen shot 2017-02-01 at 10 11 37 am" src="https://cloud.githubusercontent.com/assets/23038505/22512413/ed908c36-e866-11e6-8e5b-6db9c2671a92.png">

**Comment by mmlumba** [comment]
@astewarttistatech The latest PR has been merged to make the special issues into two columns...please take a look.

**Comment by astewarttistatech** [comment]
**PASSED** 

Environment Tested in: UAT

Steps to Validate: 
1. Log on to Caseflow Dispatch as a caseworker
2. Establish a new claim
3. Scroll down from the Review Decision page and verify that Special Issue Categories are divided into columns

Screenshots: 
<img width="1289" alt="screen shot 2017-02-01 at 11 45 47 am" src="https://cloud.githubusercontent.com/assets/23038505/22517771/43e3e0b8-e878-11e6-87b0-5e1e600d62e6.png">

**Comment by abbyraskin** [comment]
@mmlumba i noticed in the demo environment that "Guaranty" for "Home Loan Guarantee" is misspelled. Reopening this issue for the fix.

**Comment by abbyraskin** [comment]
@mmlumba on second thought, i'm going to open a new issue to keep it clean/easier to prioritize.
