### ISSUE TITLE
AMA Intake | Set origin source as Caseflow when calling CreateContentions 

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6251]
Right now, VBMS knows that contentions are AMA contentions (which cannot be deleted/edited and require a disposition) based on the fact that they are being created from a request with our SAML token.

This isn't ideal for several reasons. First and most importantly, there is a chance that our SAML token/id will change in the upcoming years. This will unknowingly break a lot of AMA functionality. Secondly, it adds friction to any other potential app in the future that would like to add AMA contentions via the ClaimService.

Instead, we should be explicitly stating the originSource, or some other way to designate that a contention is an AMA contention. This would mitigate the issues stated above.

1) Follow up with Nate and the VBMS team to add the `originSource` argument to `createContentions` which is used in determining whether a contention is an AMA contention or not instead of the SAML token.

2) Modify Caseflow/Connect VBMS to pass the `originSource` argument properly.

## How to Validate
- In Caseflow, create an AMA HLR or SC, 984562385 should work
- In VBMS, look up the Veteran and claim you just created
- Look at one of the contentions, it should not be editable in VBMS

**Comment by leikkisa** [comment]
This is available in VBMS now, reaching out to get documentation or information about what we should be passing and where

**Comment by leikkisa** [comment]
The request succeeded, but we checked VBMS and the contentions are still editable in VBMS, so am asking VBMS if this is working alright.

**Comment by leikkisa** [comment]
Just validated this with Joe. No changes were made, but it is working now.

**Comment by leikkisa** [comment]
Validated with test file number: 984562385, test claim 600135831
