### ISSUE TITLE
Certification: Cancellation Modal: Ability to view instructions and report issues

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#626]
As a Regional Office Caseworker, I want to understand how to cancel a certification and report problems that led to the cancellation in a modal view, so that I can quickly cancel and report problems to the Caseflow team.

## Acceptance Criteria
1. Verify that after clicking the **_"Cancel"_** link on the Electronic Form 8 page, the Certification Cancellation Modal is displayed.
1. Verify that the Certification Cancellation modal contains the content in the mockup
     - A header
     - Brief instructions explaining the purpose of the modal.
     - “**Cancel certification**” is bolded within the instructions.
1. Verify that the modal contains the following fields:
     - _**Why can't this case be certified in Caseflow?**_ -  Reasons why user is unable to certify case.  _Radio Button Options:_ 
          - VBMS and VACOLS dates didn't match and couldn't be changed
          - Missing document could not be found
          - Pending FOIA request
          - Other
     - **_What's your VA email address?_** - RO Caesworker's email who is canceling certification.  
    - **_Tell us more about your situation_** - Additional reason and information about why canceling.    
1. Verify that the after clicking on the “Other” radio button option for the field "Non-certifiable Reason", the "Other Comment" field is displayed.   
1. Verify that the following link is displayed: **_Go Back_**.
1. Verify that the following button is displayed:  **_Cancel Certification_**. (Refer to mockup)
1. Verify that after clicking the **_“Go back”_**, the modal closes and the Electronic Form 8 becomes the active window displaying the current case being certified.

## Mockup
**_View - Certification Cancellation Modal - Upon Initial display_**
![radio button](https://cloud.githubusercontent.com/assets/1178390/21618452/f7f8757c-d1b8-11e6-8643-81beada00211.png)

**_View - Certification Cancellation Modal - Other Option Selected_**
![radio button other](https://cloud.githubusercontent.com/assets/1178390/21618463/04498a50-d1b9-11e6-99aa-86c833b49bc4.png)

# Technical Notes
- There is an existing modal created in project - javascript and CSS

# Related Stories
EPIC: Certification Cancellation - [#1138](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1138)
Certification: Cancellation Modal: Cancel Certification:  Ability to submit cancellation - #631
Certification Cancellation: Ability to view confirmation #630 
Certification: Cancellation Modal: Add required field validation - #629

**Comment by nikitarockz** [comment]
**_Sprint Planning Notes_**
@KHarshawat We would like to make sure of the placement of the "Required" text.  Can you verify that in the mockup it is correct.

**Comment by KHarshawat** [comment]
@nikitarockz @lakohl and I made a design decision yesterday that all required fields appear in parenthesis after the input label

**Comment by KHarshawat** [comment]
![image](https://cloud.githubusercontent.com/assets/6335546/21657966/9facfeee-d292-11e6-8052-cfe2fdaa1fbf.png)

**Comment by kierachell** [comment]
Required on Feedback: 

<img width="503" alt="screen shot 2017-01-04 at 15 32 01" src="https://cloud.githubusercontent.com/assets/18075411/21658090/24888e8a-d293-11e6-8485-1ccc0aaef137.png">


Required in dispatch?
<img width="455" alt="screen shot 2017-01-04 at 15 32 08" src="https://cloud.githubusercontent.com/assets/18075411/21658091/2494676e-d293-11e6-9912-660127daff37.png">


just put this in commons?

**Comment by kierachell** [comment]
@KHarshawat @nemodjuric @nikitarockz  I was told that the design for the modal is not finalized? 
<img width="1141" alt="screen shot 2017-01-17 at 08 42 17" src="https://cloud.githubusercontent.com/assets/18075411/22023272/80543142-dc93-11e6-8318-0168b2899c2d.png">

Probably should not look like this.

**Comment by lakohl** [comment]
@shellicious could you make a design for this more in line with our other modals?

**Comment by shellicious** [comment]
@kierachell is there something I can help clear up with the mockups posted under "Mockup" at the start of this issue? Those are the most recent/final designs, and are in line with USWDS. 

@lakohl is there something that needs to be changed about the mockups posted under "Mockup" at the top of this issue to be in line with other modals? I used the most recent sketch file of the modal style guide -- if that has been updated or decisions made elsewhere, let me know.

**Comment by lakohl** [comment]
I'm posting the image of the design from @shellicious's Sketch  file - it looks right to me there!
@kierachell @nemodjuric note the h1 font weight, width of the modal, button color, and 'Required' styling
@KHarshawat could you give guidance on modal width - this appears to be 534px? and confirm that t

<img width="537" alt="screen shot 2017-01-17 at 1 57 27 pm" src="https://cloud.githubusercontent.com/assets/4975959/22035167/ef58fe50-dcbc-11e6-85d0-c002dc44a28e.png">

**Comment by nemodjuric** [comment]
As per conversation I had with @shanear we will postpone changes to modal looks for later. We had css interfering with modal for dispatch, so we decided to leave it as is and refactor code for all modals as a separate issue. There is issue created for that: #641

**Comment by kierachell** [comment]
Ok; letting this pass... for now
