### ISSUE TITLE
Confirmation: Existing EP:  Display acknowledgement of Assigned to Claim

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#627]
As a Caseworker, I would like to receive a confirmation that my current EP Establishment task was assigned to the selected Existing EP so that I am confident that the case has been processed.

##  Acceptance Criteria
1. Verify that on the Existing EP page after clicking the **_Assign to claim_** button, the Existing EP Confirmation page is displayed.
1. Verify that on EExisting EP Confirmation page, the Header title matches the mockup.
1. Verify that on Existing EP Confirmation page, the subtext matches the mockup.
1. Verify that on Existing EP Confirmation page, the following action button is available:  **_Establish Next Claim_**.
1. Verify that on Existing EP Confirmation page, the following action link is available:  **_View Work History_**.
1. Verify that after clicking on either the **_View Work History_** link or **_Establish Next Claim_**, the Continue EP Process is started (refer to Related Stories).
## Mockup
**_View 1 - Existing EP Confirmation Page_**
<img width="771" alt="screen shot 2017-01-03 at 5 57 37 pm" src="https://cloud.githubusercontent.com/assets/4975959/21626271/275f0054-d1de-11e6-95a0-b2eda170491a.png">

# Related Stories
**_Continue EP_** 
Confirmation: Successful: Ability to retrieve the next case or not #421

**Comment by lakohl** [comment]
<img width="738" alt="screen shot 2017-01-03 at 5 55 10 pm" src="https://cloud.githubusercontent.com/assets/4975959/21626200/cac4a4ac-d1dd-11e6-9c14-a662ce7ae372.png">

**Comment by astewarttistatech** [comment]
@sharonwarner no one tested this

**Comment by kierachell** [comment]
Can't validate this; we need Preexisting EP seeds to properly validate this.

**Comment by astewarttistatech** [comment]
Related issue: 704

**Comment by astewarttistatech** [comment]
Other than the related issues, it looks good on chrome. Please see success screen below 
<img width="973" alt="screen shot 2017-01-18 at 1 11 58 pm" src="https://cloud.githubusercontent.com/assets/23038505/22076832/c8a4c4ce-dd7f-11e6-911d-3e4f88fa96cf.png">

**Comment by shanear** [comment]
confirmed in UAT testing
