### ISSUE TITLE
End Product: Default Station Code value to ROJ based on Special Issue Category

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#628]
As a Caseworker, I would like to have the "Station Code" value on the End Product page to default to the claim's Regional Office Jurisdiction (ROJ) when a "Special Issue Category" has been selected on the Decision Review page so that it reduces the chance of user error.

## Acceptance Criteria
1. Verify that the when one of the following Special Issue Category has been selected on the Decision Review page, the _"Station"_ value is set to the claim's ROJ on the End Product page.

- Rice Compliance 
- Private Attorney 
- Waiver of Overpayment 
- Incarcerated Veterans
- Manlincon Compliance 
- Hearings - travel board & videoconference 
- Home Loan Guaranty 
- Insurance 
- Spina Bifida 
- Radiation 
- Non-rating Issues 
- Proposed Incompetency
- Manila Remand 
- Contaminated Water at Camp LeJeune 
- Dependencies 

# Mockup
**_View - Decision Review Page - Special Issue Category selected_**
![image](https://cloud.githubusercontent.com/assets/23063044/21644320/eef619c8-d25a-11e6-9a24-ebc2cf6c9c6a.png)

**_View - End Product Page - Station Code_**
![image](https://cloud.githubusercontent.com/assets/23063044/21644621/54977bb8-d25c-11e6-966a-968a2a2916b2.png)

# Related Stories

**Comment by lakohl** [comment]
See below for list of Special Issues for whom EPs will be routed to the ROJ (assigned to the ROJ Station).

Full Grants
Rice Compliance (routed to ROJ)
Private Attorney (routed to ROJ)
Waiver of Overpayment (routed to ROJ)
Pensions (routed to regional PMC)
VAMC (routed to 51 or 54)
Incarcerated Veterans(routed to ROJ)
DIC - death, or accrued benefits (routed to PMC)
Education or Vocational Rehab (if it's an education debt issue, gets routed to 307, 316, 331, 351, otherwise ROJ)
Foreign Claims (routed to Pittsburgh RO)
DIC - death, or accrued benefits (routed to PMC)

Remand/Partial-specific
Manlincon Compliance (routed to ROJ)
Rice Compliance (routed to ROJ)
Private Attorney (routed to ROJ)
Hearings - travel board & videoconference (routed to ROJ)
Home Loan Guaranty (routed to ROJ)
Waiver of Overpayment (routed to PMC)
Education or Vocational Rehab (if it's an education debt issue, gets routed to 307, 316, 331, 351, otherwise ROJ)
VAMC (Routed to 51 or 54)
Insurance (ROJ)
National Cemetery Administration (?)
Spina Bifida (routed to ROJ)
Radiation (routed to ROJ)
Non-rating Issues (routed to ROJ)
Foreign Claims(routed to Pittsburgh RO))
Incarcerated Veterans (routed to ROJ)
Proposed Incompetency(routed to ROJ)
Manila Remand (routed to ROJ)
Contaminated Water at Camp LeJeune (routed to ROJ)
Mustard Gas (return to Muskogee 351)
Dependencies (routed to ROJ)
DIC - death, or accrued benefits (routed to PMC)

**Comment by lakohl** [comment]
@nikitarockz Do we need to clarify the list above - e.g. which ones go to ROJ and which ones cancel?

**Comment by abbyraskin** [comment]
@sharonwarner for UAT testing this week, we're hoping to test the scenario where an EP is assigned to an RO that is not the ROJ -- not for specialty centers with shared stations, but for scenarios where a specific RO always handles a specific type of claim. 

when a remand (or partial grant) is selected, if the Mustard Gas box is checked, the EP goes to Muskogee (Station 351) - is it possible to have this ready in time for testing?

**Comment by sharonwarner** [comment]
make sure the location gets saved

**Comment by abbyraskin** [comment]
@sharonwarner if the EP is not getting routed to an RO, it goes to station 397, not 499. This is AMC's station in VBMS.

**Comment by kierachell** [comment]
When checking the following special issues, I am able to proceed through the create EP process:
<img width="533" alt="dispatch_rojrouting_partial531" src="https://cloud.githubusercontent.com/assets/18075411/22068668/c05636fc-dd63-11e6-8579-93f624f07efb.png">

Mustard Gas gives the following result:
<img width="1285" alt="dispatch_mustardgas_partial351" src="https://cloud.githubusercontent.com/assets/18075411/22068787/2794b956-dd64-11e6-832a-c38ee10b35ce.png">

Other issues, presumably routed somewhere else, just throw an error:
<img width="808" alt="screen shot 2017-01-18 at 09 55 08" src="https://cloud.githubusercontent.com/assets/18075411/22068896/7aea3978-dd64-11e6-8fd2-471c4cca8258.png">
<img width="767" alt="screen shot 2017-01-18 at 09 55 19" src="https://cloud.githubusercontent.com/assets/18075411/22068895/7ae84334-dd64-11e6-8eb1-bc7bdf772fdc.png">
<img width="745" alt="screen shot 2017-01-18 at 09 55 35" src="https://cloud.githubusercontent.com/assets/18075411/22068897/7af1affa-dd64-11e6-9a1e-9bb2091ea0bc.png">
<img width="790" alt="screen shot 2017-01-18 at 09 56 36" src="https://cloud.githubusercontent.com/assets/18075411/22068894/7ae6ae8e-dd64-11e6-8398-ea3a516360e5.png">
I assume National Cemetery case throws an appropriate `?`

Can't test if it actually reaches VBMS or whatever it's supposed to reach.

**Comment by lakohl** [comment]
@kierachell for NCA (National Cemetaries) the user can't create an EP
