### ISSUE TITLE
CHECK ON AUGUST 18: VBMS requires postal codes for Germany and Caseflow does not

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6285]
Discovered this bug with this Sentry error:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1917/

The Veteran model only requires USA and Canada to have zip codes in validation.

**Comment by leikkisa** [comment]
@abbyraskinUSDS  @suzchap Can one of you check this out and see what is required, and if we are missing any other countries?  If we don't know, let me know and I can ask VBMS knows.

**Comment by abbyraskinUSDS** [comment]
Hm yeah, this seems like a VBMS question.

**Comment by abbyraskinUSDS** [comment]
phoning a friend named @aroltsch who dealt with something similar for Dispatch a long time ago...

**Comment by aroltsch** [comment]
It appears to me other countries require postal code. This error is for Germany and zip code we are sending is nil.

```
:country=>"Germany", :zip_code=>nil
```

However, I don't remember dealing with it personally. I found a few tickets Shane files with VBMS team:
https://github.com/department-of-veterans-affairs/dsva-vbms/issues/77
https://github.com/department-of-veterans-affairs/dsva-vbms/issues/80

**Comment by leikkisa** [comment]
I am double checking with VBMS if we just need to add Germany (and potentially other countries) to the list of countries requiring postal code in the Veteran model.  

I looked at the other tickets and I think this is unrelated to the OVR address type issue because it's an INT address type and I don't think it's a military address (the Veteran is not in the military anymore and I didn't see any of those other codes).

**Comment by leikkisa** [comment]
VBMS checked and it appears that Germany is allowed to come through without a zip code in V5, but for some reason we were still using v4. Some things to check:
- Are we setting it to use V5 when we make the request?
- Is there a V5 feature flag that needs to be turned on in prod?

**Comment by leikkisa** [comment]
Happening for Australia too.

**Comment by kahlouie** [comment]
Sally has emailed VBMS to see if the bug fix on their side got deployed this weekend. Will get a pr up for the revert with the blocked label until we get confirmation.
