### ISSUE TITLE
Certification: Cancellation Modal: Add required field validation

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#629]
As a Regional Office Caseworker, I want to have certain fields mandatory for completing the cancellation of a certification so that I will be guaranteed that certain information is captured when canceling a certification.

## Acceptance Criteria
1. Verify that the following fields has the text "(Required)" next to their labels:  
     - _**Why can't this case be certified in Caseflow?**_
     - **_What's your VA email address?_**
    - **_Tell us more about your situation_**
1. Verify that after clicking on the **_Cancel Certification_** button and there's no value in the _"Why can't this case be certified in Caseflow?"_ field, the following error Message is displayed: (Refer to mockup) 

     > Make sure you’ve selected an option below.

1. Verify that after clicking on the **_Cancel Certification_** button and there's no value in the "_What's your VA email address?_" field, the following error Message is displayed:

     > Make sure you’ve entered a valid email address below.

1. Verify that after clicking on the **_Cancel Certification_** button and the value in the "_What's your VA email address?_" field is not in an email format, the following error Message is displayed:

     > Make sure you’ve entered a valid email address below.
1. Verify that after clicking on the **_Cancel Certification_** button and there's no value in the "_Tell us more about your situation_" field, the following error Message is displayed:

     > Make sure you’ve filled out the comment box below.

1. Verify that after clicking on the **_Cancel Certification_** button, all fields not meeting required field validation are highlighted/outlined in Red and displayed with its validation error message.  (Refer to mock)
1. Verify that after clicking on the **_Cancel Certification_** button, the cursor is taken to the first field with a validation issue.

## Mockups
**_View - Certification Cancellation Page - Missing Not able to certify reason_**
![image](https://cloud.githubusercontent.com/assets/23063044/21629316/2cafc540-d1f5-11e6-9ee2-8ff503297266.png)

**_View - Certification Cancellation Page - Missing Other explanation comment_**
![image](https://cloud.githubusercontent.com/assets/23063044/21629102/1b50d4c6-d1f3-11e6-89eb-cfd81611421b.png)_

**_View - Certification Cancellation Page - Invalid Email_**
![image](https://cloud.githubusercontent.com/assets/23063044/21629185/f5165c26-d1f3-11e6-8d03-cddf16d1ed4e.png)

**_View - Certification Cancellation Page - Missing all required fields_**
![image](https://cloud.githubusercontent.com/assets/23063044/21629367/90b597e0-d1f5-11e6-9726-d60bc8797705.png)

# Related Stories
EPIC: Certification Cancellation - [#1138](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1138)
Certification: Cancellation Modal: Ability to view instructions and report issues - #626
Certification: Cancellation Modal: Cancel Certification:  Ability to submit cancellation - #631
Certification: Cancellation Modal: Ability to view confirmation - #630

**Comment by nemodjuric** [comment]
@KHarshawat @nikitarockz @lakohl @shanear @shellicious 
Just to confirm - we want no default radio button selected?

**Comment by lakohl** [comment]
Good question @nemodjuric . @shellicious is there any case where more than one of these reasons might be valid?

**Comment by shellicious** [comment]
@nemodjuric Yes, we want no default radio button selected.

I can't think of existing cases where more than one reason may be valid. I'm OK with launching this as-is and changing it to multiple-choice boxes if RO staff would like to submit more than 1 reason. What do you think, @lakohl?

**Comment by lakohl** [comment]
@shellicious that sounds fine. I prefer experiences that pre-select a radio button for the user rather than leaving them all blank. We may not have enough info to make that call right now, but once we have some data on why most people cancel we could consider that modification.

**Comment by nemodjuric** [comment]
![caseflow certification 6](https://cloud.githubusercontent.com/assets/4960030/21824943/96b8d5e4-d74f-11e6-802c-b154d245151f.png)

@lakohl @shellicious @KHarshawat @nikitarockz 
Note: When there is no default radio option selected, USWDS usa-input-error class produces screen shot above.

**Comment by shellicious** [comment]
@nemodjuric that shows up when the user tries to submit without selecting an option, right?

**Comment by nemodjuric** [comment]
@shellicious Correct.

**Comment by shellicious** [comment]
@nemodjuric works for me!

@lakohl think it best to leave a survey-like interaction unbiased by leaving the radio buttons blank. Google Forms, for instance, defaults to inputs that are blank by default. I'm concerned it would be too easy to leave the selected radio button and click through the modal, and we'd get bad data as a result.

**Comment by kierachell** [comment]
@nemodjuric mentioned that the design for the modal is not finalized.
Here's what I am seeing:

<img width="1141" alt="screen shot 2017-01-17 at 08 42 17" src="https://cloud.githubusercontent.com/assets/18075411/22023093/c51beb7c-dc92-11e6-9526-fc8ef49770cc.png">

Then I tried to mess with it:

<img width="949" alt="screen shot 2017-01-17 at 08 56 48" src="https://cloud.githubusercontent.com/assets/18075411/22023174/1e1f3efe-dc93-11e6-8e8b-886e6c0970ae.png">
<img width="974" alt="screen shot 2017-01-17 at 08 57 01" src="https://cloud.githubusercontent.com/assets/18075411/22023175/1e1f903e-dc93-11e6-8bd7-182b1179bdee.png">
<img width="947" alt="screen shot 2017-01-17 at 08 57 21" src="https://cloud.githubusercontent.com/assets/18075411/22023176/1e20729c-dc93-11e6-9dc2-3be526f0ae37.png">
<img width="994" alt="screen shot 2017-01-17 at 08 57 36" src="https://cloud.githubusercontent.com/assets/18075411/22023177/1e28fef8-dc93-11e6-8cfc-79b32385fbb2.png">
