### ISSUE TITLE
Add hover tooltip to Days waiting in judge queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6294]
Let's give judges a definition of Days waiting, so they are confident in knowing how long a case has been assigned to them. 

## AC
- Add tooltip pattern to Days waiting column in judge queue
- Tooltip reads "Calendar days this case has been assigned to you"

## Reference - attorney queue
<img width="257" alt="screen shot 2018-07-20 at 10 05 02 am" src="https://user-images.githubusercontent.com/27704093/43006718-6a4730d0-8c04-11e8-8555-71ead07f7c80.png">

**Comment by mkhandekar** [comment]
I'd recommend having a little info icon wherever there are tooltips for accessibility. I'm not recommending developing this right away, but want to drop this here to further the conversation (and, it needs eyes on it by @sneha-pai and @dannysellers who developed the first tooltip). How tough would it be to include an icon in the table header?

![image](https://user-images.githubusercontent.com/1598889/43149406-533c3370-8f35-11e8-9fa1-36a329d95165.png)

@mdbenjam also in the screenshot above, we have all columns sortable.

**Comment by laurjpeterson** [comment]
the above looks good to me. i think the info icon makes sense to add for both attorney and judge queues, and wherever we include a tooltip!

**Comment by dannysellers** [comment]
Does this info icon already exist? It wouldn't be difficult to add next to the text in a column header.

**Comment by mkhandekar** [comment]
It does not, to my knowledge. 

here it is: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/images/icon-info.svg

**Comment by dannysellers** [comment]
This is not complete, thanks for noticing.

This should be a quick ticket. As far as I can tell, there's just one complication / point to resolve: the Days Waiting column is used in multiple contexts, including both when reviewing a judge's own cases and when looking at cases assigned to attorneys. In the former, it'll say `Calendar days this case has been assigned to you`, but in the case of looking at attorneys' cases, should the text read `...assigned to ${attorneyName}`?

**Comment by laurjpeterson** [comment]
@dannysellers - is this another case where we want uniformity? if so, we could make the tooltip read `Calendar days since this case was assigned` or `Calendar days since this case was assigned to user`. I don't personally like the "to user" part of it. 

If we don't need it to be universal, then I agree with `assigned to ${attorneyName`

I changed the copy a bit here, because we have it so the Days waiting counter restarts when the case has been assigned back to the attorney from co-located, not just when the judge assigns it to the attorney. @mkhandekar what do you think about this tweak?

**Comment by mkhandekar** [comment]
Thanks for bringing up the complication Danny!

Yes, I like your tweak here Lauren 👍 

- if uniformity is needed: `Calendar days since this case was assigned`
- if not: `Calendar days since this case was assigned to ${attorneyName}`

**Comment by dannysellers** [comment]
I'll have to think more about if/how we could have a dynamic tooltip there. But, there're two interrelated issues I see: first, the table component has no idea of the context it's used in, so we'd have to check task assignment info from the row values we pass in (to get whether we're looking at tasks assigned to the current user or not). However, because this tooltip is on a header row cell, it doesn't have access to the data that's passed in to the table body (nor should it, really).

So, I guess that separation means we should just stick with a uniform tooltip
