### ISSUE TITLE
Certification Cancellation: Ability to view confirmation

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#630]
As a Regional Office Caseworker, I would like to permanent cancel the certification of the current case and receive a confirmation message that case I was certifying has been successfully cancelled so that I am confident that the case now needs to be certified outside of Caseflow.

###  Acceptance Criteria
1. Verify that after clicking the **_Cancel Certification_** button on the Certification Cancellation modal, the Certification Cancellation Confirmed page is displayed.
1. Verify that the Header title matches the mockup.
1. Verify that the subtext matches the mockup.

### Mockup
**_View - Certification Canceled Confirmation page_**
![image](https://cloud.githubusercontent.com/assets/23063044/22079402/b4a12684-dd89-11e6-95b9-bb26305d3275.png)

# Related Stories
EPIC: Certification Cancellation - [#1138](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1138)
Certification: Cancellation Modal: Cancel Certification:  Ability to submit cancellation - #631 
Certification: Cancellation Modal: Ability to view instructions and report issues #626 
Certification: Cancellation Modal: Add required field validation - #629

**Comment by nikitarockz** [comment]
@shellicious Sorry, I changed this mockup for this story as we had briefly talked about it being consistent with Dispatch. We can keep this one or if you can whip up a new mockup soon similar. I would like to push this forward. Planning is at 3 pm.   Thanks.

**Comment by shellicious** [comment]
@nikitarockz mock updated with header color changes!

**Comment by kierachell** [comment]
As a _Caseworker_ I am seeing the following messages during the cancellation process:
<img width="1174" alt="screen shot 2017-01-17 at 08 45 25" src="https://cloud.githubusercontent.com/assets/18075411/22022841/9a147490-dc91-11e6-8470-dd0a479f3e39.png">

<img width="1082" alt="screen shot 2017-01-17 at 08 45 32" src="https://cloud.githubusercontent.com/assets/18075411/22022764/58e38baa-dc91-11e6-9059-4a1b77fe0b36.png">

As a _System Administrator_ I receive the following:
<img width="1141" alt="screen shot 2017-01-17 at 08 42 17" src="https://cloud.githubusercontent.com/assets/18075411/22022873/bf0fc33a-dc91-11e6-9bda-62e9b0e95f84.png">
<img width="1190" alt="screen shot 2017-01-17 at 08 42 33" src="https://cloud.githubusercontent.com/assets/18075411/22022872/bf0eb9d6-dc91-11e6-9612-ba7cb37a515b.png">

@nikitarockz please confirm that the functionality is intended and if the following errors require adjustment:
I am unable to verify:
4. - no link displayed
5. - closing window functionality probably required integration with VACOLS which I am unable to test.

**Comment by kierachell** [comment]
@nemodjuric 
1. "Close window" Link not necessary.
2. The new `Cancel Certification` modal should be used for all _Caseworkers_, not just for _System Admins_
3. Header needs to display **Caseflow Certification**, and _Not Certified_

currently that is missing:
<img width="589" alt="screen shot 2017-01-18 at 13 58 26" src="https://cloud.githubusercontent.com/assets/18075411/22078531/4ab9c580-dd86-11e6-8219-b48d94c07ddc.png">

**Comment by nikitarockz** [comment]
## Acceptance Criteria and Mockup Update
Removed the following 2 ACs as they are no longer needed.
     1. Verify that the following link is displayed: **_close this window_**.
     1. Verify that after clicking the **_close this window_**, the Certification Cancellation Confirmed page is closed and the Certification Home page is displayed for the Caseworker to start certifying a new case.

**Comment by nikitarockz** [comment]
@kierachell @nemodjuric The path of this story should follow that of a Caseworker; however, based on what I am seeing it is following the System Administrator.  The Certification modal and Cancellation page currently displayed for the System Administrator should be displayed as the Caseworker.

**Comment by kierachell** [comment]
Here are the latest results:
<img width="926" alt="screen shot 2017-01-24 at 11 01 18" src="https://cloud.githubusercontent.com/assets/18075411/22255348/1fd17c8e-e225-11e6-8b8d-a6616427583b.png">
Looks good on my end 👍
