### ISSUE TITLE
Refactor TextField Component

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#6301]
TextField component has too many props. Refactor component to remove rarely used logic/ app specific logic in a container.

1, make label a require property
2, separate out readOnly 
3, remove fixedInput used only in hearing prep PDF
4, consider using ` defaultValue` instead of `value = (value === null || typeof value === 'undefined') ? '' : value;`

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
