### ISSUE TITLE
Certification: Cancellation Modal: Cancel Certification:  Ability to submit cancellation

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#631]
As a Regional Office Caseworker, I would like to permanently cancel the processing of a case certification and save cancellation reason information so that I can certify the case outside of Caseflow.

## Acceptance Criteria
1. Verify that the current certification case task has been updated to a cancellation state. 
1. Verify that after clicking the **_Cancel Certification_** button on the Certification Cancellation modal, all values (_**Why can't this case be certified in Caseflow?**_, **_What's your VA email address?_**, and **_Tell us more about your situation_**) have been saved.
1. Verify that after clicking the **_Cancel Certification_** button on the Certification Cancellation modal, the Certification Cancellation modal and Electronic Form 8 page is closed.
1. Verify that after clicking the **_Cancel Certification_** button, the Certification Cancellation Confirmed page is displayed.

# Related Stories
EPIC: Certification Cancellation - [#1138](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1138)
Certification: Cancellation Modal: Ability to view confirmation #630
Certification: Cancellation Modal: Ability to view instructions and report issues - #626
Certification: Cancellation Modal: Add required field validation - #629

**Comment by kierachell** [comment]
The modal appears correctly as per updated specifications.
<img width="573" alt="screen shot 2017-01-24 at 11 39 20" src="https://cloud.githubusercontent.com/assets/18075411/22257119/0d37a70a-e22b-11e6-915c-560180f441a5.png">
Table is generated for the appropriate certification.

However, a few bugs have come up:
- No whitespace trimming or error:
<img width="954" alt="screen shot 2017-01-24 at 11 08 36" src="https://cloud.githubusercontent.com/assets/18075411/22257145/270a4a7a-e22b-11e6-9c7c-fc4340157079.png">
- No character limit:
<img width="935" alt="screen shot 2017-01-24 at 11 49 54" src="https://cloud.githubusercontent.com/assets/18075411/22257176/3ef9b81e-e22b-11e6-9d7b-473c21eb23a3.png">
- Pressing back button will return one to the Certification and it is possible to finish the certification
- Pressing back button will return one to the Certification Cancellation modal and pressing Cancel again will result in explosions:
<img width="1389" alt="screen shot 2017-01-24 at 12 01 50" src="https://cloud.githubusercontent.com/assets/18075411/22257732/ee70a7d4-e22c-11e6-8596-62d187203c34.png">

**Comment by nemodjuric** [comment]
- Pressing back button... We should find a way to handle the error message, however, it's expected behavior when it comes to db table - there shouldn't be more than one cancellation per certification.  @shanear What is the official stance on character limit and white space?

**Comment by shanear** [comment]
Good catches @kierachell!

1) We should trim the input before validating. Shouldn't be too difficult to do.

2) The back button issue can be solved via the following update:
```
  def create
    begin
      @certification_cancellation = CertificationCancellation.create(certification_cancellation_params)
    rescue PG::UniqueViolation
      # Do nothing if already cancelled.
    end

    redirect_to @certification_cancellation
  end
```
    
```
