### ISSUE TITLE
Revisit attorney/co-located loop scope

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6324]
# Goals
- revisit our definition of minimal viable product for the attorney/co-located loop. 

# Scope
- attorneys can assign admin actions to co-located
- co-located admin users can view admin actions in their queue
- co-located admin users can place admin action tasks on hold
- co-located admin users can send cases with admin actions to another team, if need be (the only example we have right now is Schedule hearing tasks)
- co-located admin users can assign cases back to attorneys

**Comment by laurjpeterson** [comment]
# Results of discussion
- Limit scope to attorneys only being able to assign one admin action to an attorney at a time. Co-located users only view one task at a time in their table and in case details
- Remove notes field when co-located sends cases back to attorney - @sneha-pai to provide some options for a reduced flow here
- Implement attorneys assigning tasks to co-located, co-located placing on hold, co-located new table before implementing the 3 tabs. @dannysellers and @evankroske to collaborate on the order of implementation. Resources to help do this:
      - [Epic](https://github.com/department-of-veterans-affairs/caseflow/issues/5434
      - [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1524169387338/8917c31aab5f57444eaa6aacf5b93bc310395e29)

# Future decisions
- If we are in a time crunch, we may consolidate the Pending Action and On Hold tabs

# Future explorations
- @sneha-pai and @mkhandekar to think about judge assignment to attorney flow alongside these co-located assignment flows. where are the similarities?

**Comment by dannysellers** [comment]
@evankroske and I discussed a high-level strategy for approaching development: end-to-end. 

First phase, Attorneys adding admin actions (me):
#5438, #5439, #5430 

Other phases (order TBD):
- Attorney assigning admin actions (#6031, #6032, #6033)
- Colocated table views (#6077, #6078, #6079, #6080)
- Place hold (#6081, #6082, #6083, #6084)
- Send to another team (#6085, #6086)
