### ISSUE TITLE
Manager Dashboard:  Header: User Menu: Ability to logout

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#633]
As a Manager, I would like to have a "Sign Out" option under the Username Menu in the Header of all so that I may logout when I am finished with my tasks.

# Acceptance Criteria 
1. Verify that after clicking on the Username Menu, the only option available is "Sign Out".
1. Verify that after clicking on the "Sign Out" menu option, the user is logged out of the system.

### Mockups
![image](https://cloud.githubusercontent.com/assets/3781835/20507119/c40c0dea-b026-11e6-864f-6bd1707917ff.png)

![image](https://cloud.githubusercontent.com/assets/23063044/20774118/e73f3442-b722-11e6-9b6a-31b717d301e4.png)

# Related Stories 
Manager Dashboard: Reports: Ability to view appeals without a decision document #408

**Comment by nikitarockz** [comment]
@lakohl This is a new one added. New page needs to be able to sign out.

**Comment by shanear** [comment]
This already exists. Closing
