### ISSUE TITLE
Decision Review:  Create End Product:  Display Special Issue Cancellation Warning modal

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#634]
As a Caseworker, I would like to have a warning message displayed when I attempt to create an End Product and have selected a Special Issue Category that can not be handled within Caseflow Dispatch so that I have an option to cancel the claim establishment process or correct my selection.

## Acceptance Criteria
1. Verify that after clicking on the **_Create End Product_** button on the Decision Review page, the Special Issue Warning modal is displayed when one of the following Special Issue Categories have been selected:  
     - Pensions
     - VAMC
     - DIC - death, or accrued benefits
     - Foreign Claims
     - Education or Vocational Rehab 
     - Waiver of Overpayment 
     - National Cemetery Administration 
     - Foreign Claims
1. Verify that on the Special Issue Warning Modal, the Header matches the mockup.
1. Verify that on the Special Issue Warning Modal, the Subtext matches the mockup.
1. Verify that on Special Issue Warning Modal, the following action button is available:  **_Cancel Claim Establishment_**.
1. Verify that on Special Issue Warning Modal, the following action link is available:  **_Close_**.
1. Verify that when the **_Close_** link is clicked, the Special Issue Warning Modal is closed and the Decision Review page is active with the current Establish Claim task.
1. Verify that when the **_Cancel Claim Establishment_** button is clicked, the Special Issue Warning Modal is closed and the EP Cancellation process commences (refer to Related Stories).

## Mockup
**_View - Special Issue Warning Modal_**
![image](https://cloud.githubusercontent.com/assets/23063044/21650914/9275ce18-d274-11e6-8b78-0673588f213b.png)

**_View - Decision Review - Special Issue Warning Modal active window_**
![image](https://cloud.githubusercontent.com/assets/23063044/21647356/f2aabc4c-d267-11e6-8cbb-84bd098b1bdb.png)

# Related Stories
**_Cancellation Process_**
EP Cancellation:  Ability to provide instructions and obtain cancellation information  #518
EP Cancellation: Establish Claim Task: Permanently stop processing current task #523
EP Cancel Confirmed: Display acknowledgement of EP case being cancelled #524
EP Cancel Confirmed: Ability to retrieve the next case or not #525

**Comment by kierachell** [comment]
Checked that the modal shows up for the cases listed above.
<img width="1076" alt="screen shot 2017-01-13 at 09 04 26" src="https://cloud.githubusercontent.com/assets/18075411/21932743/157e3d2a-d970-11e6-8a3b-eccc233bd65f.png">
<img width="1023" alt="screen shot 2017-01-13 at 09 07 06" src="https://cloud.githubusercontent.com/assets/18075411/21932745/1596defc-d970-11e6-9c1a-7c4a35a2112f.png">
<img width="1030" alt="screen shot 2017-01-13 at 09 07 14" src="https://cloud.githubusercontent.com/assets/18075411/21932744/15943e72-d970-11e6-9ab8-9eefc55cc7e7.png">
<img width="1027" alt="screen shot 2017-01-13 at 09 07 23" src="https://cloud.githubusercontent.com/assets/18075411/21932747/1598a246-d970-11e6-9712-28b8f6a5757f.png">
<img width="841" alt="screen shot 2017-01-13 at 09 07 32" src="https://cloud.githubusercontent.com/assets/18075411/21932746/1597f058-d970-11e6-88e8-768e67659dad.png">
<img width="884" alt="screen shot 2017-01-13 at 09 08 08" src="https://cloud.githubusercontent.com/assets/18075411/21932748/1598a444-d970-11e6-8328-df03ed043f30.png">
<img width="952" alt="screen shot 2017-01-13 at 09 08 22" src="https://cloud.githubusercontent.com/assets/18075411/21932749/15a2c532-d970-11e6-8ffc-4009b38950e5.png">
<img width="1012" alt="screen shot 2017-01-13 at 09 08 52" src="https://cloud.githubusercontent.com/assets/18075411/21932750/15ab3e74-d970-11e6-8149-dfac6b286af4.png">

@nikitarockz @KHarshawat @lakohl Need to know if the modal's corners have to be rounded.


There is an issue with modal focus capturing as shown below:
**Steps**
- Select one of the special issues that will cause the modal to show up when clicking _Create End Product_
- Once the modal shows up press `TAB` on the keyboard and watch the focused element switch to an element in the background
- Press `TAB` on the keyboard until _Cancel_ link is selected from the background
- Press `ENTER` to have another modal show up.
<img width="1012" alt="screen shot 2017-01-13 at 09 12 28" src="https://cloud.githubusercontent.com/assets/18075411/21932811/7567a65e-d970-11e6-9d13-10deeb79a675.png">

**Comment by kierachell** [comment]
I can open a separate issue to fix all the modals - if necessary;
