### ISSUE TITLE
Review Assignments | Redirect when finalized == true

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6345]
If a user navigates to /hearings/schedule/build/${schedule_period_id} after the schedule period has already been uploaded to VACOLS, we currently redirect to the /hearings/schedule/build since that page doesn't really hold any useful information and expires after 4 days. That redirect is causing problems because /hearings/schedule/build is where we hold the logic for uploading the algorithm results to VACOLS. I think instead of redirecting to that page, we should display an alert saying something like 'Page Expired'.

**Comment by Chingujo** [comment]
@sharonwarner 

Here is the mock for the page expired when the user tries to go back after the schedule has been uploaded to VACOLS. I believe we have a message styling using the dark gray component in the style guide. 

This mock redirect them to the home page here so the user can go to where she or he needs to go and to prevent a sense that the process has been reset if we just sent them to the more recent active page. Lmk if this isn't ideal. Thanks! 

![page expired](https://user-images.githubusercontent.com/23316107/43273707-21f2fafa-90cb-11e8-86e5-d90ba068b0a0.png)
