### ISSUE TITLE
Better designed 404 page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#635]
Our 404 (not found) page looks very janky. Might want to make it more informative:

Current state:
<img width="1505" alt="screen shot 2017-01-04 at 10 44 00 am" src="https://cloud.githubusercontent.com/assets/1596259/21648644/ad93dc7e-d26c-11e6-93fb-2ca61e72a4e9.png">

**Comment by shanear** [comment]
@lakohl thoughts?

**Comment by lakohl** [comment]
<img width="665" alt="screen shot 2017-01-27 at 7 05 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/22392096/d57d8b54-e4c3-11e6-831b-134a0e2f4fb5.png">

Above is the Design for eX. For other Caseflow products the name of that product would appear instead.

**Comment by lakohl** [comment]
@nikitarockz this one is ready to go

**Comment by KHarshawat-gov** [comment]
@lakohl, @shanear asked me to take a pass at this too. WDYT?

![generic 404](https://cloud.githubusercontent.com/assets/25437276/22708579/ded98fac-ed44-11e6-898d-819f60d8abf6.png)
