### ISSUE TITLE
Save Veteran first, middle, last, and suffix in the Caseflow DB when an appeal goes through intake

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6351]
When an appeal goes through Caseflow Intake, we should save the most current veteran first name, middle name, last name, and suffix from BGS in a new veteran record or in one that already exists. 

For veteran rows already in our DB, the next time we fetch BGS information, we should save the Veteran name to backfill data.

# AC
- `first_name`, `middle_name` `last_name`, and `name_suffix` are added to the Veterans table
- Middle name and suffix are fetched from BGS (currently we only fetch first name and last name)
- When Caseflow Intake is used to intake an appeal, we fetch the Veteran name from BGS and either save it to  a new Veterans row or update the existing row
- For Veteran rows already in the DB, if the name is blank, the next time we fetch data from BGS, save the Veteran name in the DB

**Comment by kahlouie** [comment]
@mdbenjam Heard you might be interested in this?

**Comment by mdbenjam** [comment]
This is needed for Queue by October. So I was thinking of picking it up. If you or anyone else has bandwidth you should go for it! I'm pretty slammed with Queue work this week and then am on vacation the next two weeks. I'll get to it after that if no one else has done it.

**Comment by kahlouie** [comment]
Good to know. Thanks.

**Comment by shanear** [comment]
This seems fairly complex. Why does caching the name not work?

**Comment by amprokop** [comment]
@shanear — I prefer this solution for its predictability. Reasons:

1. Request latency

There are users who are going to need to see 100+ Veteran names every time they interact with Caseflow. It's likely those users will see sporadic timeouts and sporadically very long load times.

2. Downtime

If we cache, BGS downtime is going to bring down Queue, the IDT, and other parts of Caseflow for some users sometimes. Potentially it's better to save the name up front then have to worry about the case where BGS is down in all of those situations. 

3. This is fairly static data

Veteran names change rarely enough that no one I've talked to seems to perceive that out of date Veteran names are a problem with VACOLS data (vs out of date addresses and POAs which are a big problem).

Lmk if you want to connect synchronously on this, @shanear. Otherwise, is there a timeline we could hope this could be done by? Potentially @mdbenjam or myself could pick this task up if y'all are short on bandwifth

**Comment by shanear** [comment]
> It's likely those users will see sporadic timeouts and very long load times when the cache expires for Veteran names.

We can cache the veteran names indefinitely, this seems like it would solve the issues you're talking about. I'm open to chatting about this.

**Comment by mdbenjam** [comment]
I'm generally against storing duplicate data in Caseflow that we can get from BGS. But I think for these kinds of *almost* never changing fields it makes sense. Another example where we'll need this is for birthdates. We need that in PG rather than Redis since we'll have to run queries on which Veterans are older than 75 to determine who is eligible to be advanced on the docket.

**Comment by shanear** [comment]
> I'm generally against storing duplicate data in Caseflow that we can get from BGS. But I think for these kinds of almost never changing fields it makes sense. Another example where we'll need this is for birthdates. We need that in PG rather than Redis since we'll have to run queries on which Veterans are older than 75 to determine who is eligible to be advanced on the docket.

I'm cool with this, especially if we need to query on it, but I think we don't want to get involved in any background jobs or anything. We set it the same time we set participant id on the veteran table, once when it's created and never again, and we assume it never changes.

**Comment by amprokop** [comment]
👍

**Comment by kahlouie** [comment]
@amprokop @mdbenjam Can you help validate this is what you wanted? It will deploy to prod on monday morning.

**Comment by shanear** [comment]
There is a bug happening with this in prod:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2465/

**Comment by amprokop** [comment]
Ooh, nice catch.

**Comment by shanear** [comment]
Here's another bug happening with this in prod:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2464/

**Comment by kahlouie** [comment]
I think we need someone from Queue team to validate that it's good enough :)
@amprokop @mdbenjam?

**Comment by amprokop** [comment]
Steps to validate:
- Find a recently intaked AMA appeal, confirm veteran name fields for the veteran on that appeal were in DB
- Find a veteran row without name fields saved to the DB, confirm that `Veteran.find_or_create_by_file_number` backfills and successfully saves name to DB

@kahlouie @mdbenjam are these the steps you expect?

**Comment by mdbenjam** [comment]
That sounds good to me! Also reminder that Kara's last day on Caseflow was Friday 😢

**Comment by amprokop** [comment]
Ah sorry. We miss you, Kara!

**Comment by shanear** [comment]
> Find AMA appeal, confirm veteran name fields for the veteran on that appeal were in DB
> Find a veteran row without name fields saved to the DB, confirm that > Veteran.find_or_create_by_file_number backfills and successfully saves name to DB

I validated both of these in prod. Closing.

**Comment by amprokop** [comment]
Ah thanks for the note — was just looking for this ticket so I could
validate it. Appreciate you beating me to it!
