### ISSUE TITLE
Cancel EPs that were created but one of the contentions requests failed or subsequent end product establishments failed

### ISSUE THREAD

**Issue by ferlatte** [department-of-veterans-affairs/caseflow#6356]
In our clean up job, we should be looking for `EndProductEstablishment`s where the EP was created but all the operations didn't successfully complete (i.e. `established_at` isn't set), and cancel the EP.

## Acceptance Criteria
- Periodically in a script, Caseflow should look for rows in `end_product_establishment` where `reference_id` is set but `established_at` or `confirmed_at` is nil and cancel the EP with the associated `reference_id`

## Technical Notes
- Because of timing issues, to be safe we probably want to wait around 30 minutes after the end product establishment was created to make sure it truly has failed and isn't still processing. 
- We will need to write a `rollback!`/`revert!`/`cancel!` method on `EndProductEstablishment` that cancels the EP.
- In order to rollback successfully established EPs where one of the other EPs associated with a claim review failed, we may need another timestamp to mark that the entire claim review establishment was successful. This could be called `finalized_at` or `confirmed_at` or something like that.

## Validation
- This story should be validated by engineers

Requires #6357

**Comment by leikkisa** [comment]
Requires #6357

**Comment by shanear** [comment]
After a discussion with Sally we don't think this is the best way forward.

**Comment by shanear** [comment]
Yeah confirmed we are not doing this
