### ISSUE TITLE
Existing EP:  Error if there are no valid modifiers

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#636]
As a Caseworker, I would like to be prevented and receive an error message that there are no valid modifiers available when attempting to create a new End Product on the Existing EP page so that I inadvertently create an invalid EP Code.

# Acceptance Criteria
1. Verify that if there's no more valid/available modifiers for the EP Code corresponding to the select _"Decision Type"_, the following alert message is displayed on the Existing EP page:   
**_Title:_**  

     > Existing EP, all EP & Claim Label Modifiers in use

     **_Message:_**  
     > We found one or more existing EP(s) created within 30 days of this decision date.  You may assign an existing EP from the table below to this claim. 

     > A new [_EP & Claim Label_] cannot be created for this Veteran ID as all EP modifiers are currently in use.

1. Verify that if there's no more valid/available modifiers for the EP Code corresponding to the select  _"Decision Type"_, the **_Create New EP_** button is disabled.

# Mockup
**_View - Existing EP Page with alert message and disabled button_**
<img width="543" alt="screen shot 2017-01-18 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/4975959/22072555/bc1a949a-dd70-11e6-8959-ff62ebdcba71.png">

# Related Stories
End Product: Don't allow duplicate modifiers on EP form #622

**Comment by nikitarockz** [comment]
**_Shane's Original Comments_**
We should check to see if there are any available modifiers for the EP Code corresponding to the select Decision Type, when they are on the Existing EPs page. If there aren't any available modifiers:

- Disable the "Create New EP" page.
- Change the text inside of the "Existing EP" alert box at the top. Exact copy to be provided by @lakohl

**Comment by lakohl** [comment]
Existing EP, all EP & Claim Label Modifiers in use
We found one or more existing EP(s) created within 30 days of this decision date.  You may assign an existing EP from the table below to this claim. 

A new [_display EP & Claim label_] EP cannot be created for this Veteran ID as all EP modifiers are currently in use.

See design below.
<img width="812" alt="screen shot 2017-01-17 at 10 39 54 am" src="https://cloud.githubusercontent.com/assets/4975959/22027279/588ad806-dca1-11e6-9bc9-bdf43a721569.png">

**Comment by kierachell** [comment]
Don't have a Mockup, don't know what to validate.

**Comment by lakohl** [comment]
<img width="543" alt="screen shot 2017-01-18 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/4975959/22072555/bc1a949a-dd70-11e6-8959-ff62ebdcba71.png">

**Comment by nikitarockz** [comment]
## Acceptance Criteria and Mockup Updated

1. Updated AC 1 with alert text.
2. Updated Mockup with new image.

**Comment by kierachell** [comment]
When creating a new 172 grant EP; I am not seeing 2nd part of the message:
<img width="910" alt="screen shot 2017-01-18 at 14 44 18" src="https://cloud.githubusercontent.com/assets/18075411/22080223/c2f7ca46-dd8c-11e6-9def-949b269b622d.png">

The following message is not showing up:
```
A new [EP & Claim Label] cannot be created for this Veteran ID as all EP modifiers are currently in use.
```

**Comment by kierachell** [comment]
<img width="1083" alt="screen shot 2017-01-27 at 15 22 40" src="https://cloud.githubusercontent.com/assets/18075411/22386483/54518292-e4a5-11e6-982a-106e8d200b3b.png">
👍
