### ISSUE TITLE
IDT API should return a list of VACOLS appeals by assigned attorney or by file number

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6360]
Create routes to return simple appeal info for the IDT

`GET /idt/api/v1/appeals --header "TOKEN: 254tretrewrew"` 
`GET /idt/api/v1/appeals --header "FILE: 22222222" --header "TOKEN: 254tretrewrew"`

# Sample output

```
{
  "data": [
    {
      "id": "2556987",
      "type": "legacy_appeals",
      "attributes": {
        "veteran_first_name": "Jay",
        "veteran_middle_name": "Q",
        "veteran_last_name": "Lemke",
        "file_number": "750998600",
        "docket_number": "2053383",
        "number_of_issues": 1
      }
    },
    {
      "id": "3019694",
      "type": "legacy_appeals",
      "attributes": {
        "veteran_first_name": "Tatum",
        "veteran_middle_name": "C",
        "veteran_last_name": "Schumm",
        "file_number": "849386058",
        "docket_number": "7592395",
        "number_of_issues": 1
      }
    }
  ]
}
```

# AC
- IDT endpoint returns appeals with veteran name, claim number, # of issues, docket_number, id.
- The user must be an attorney or a judge.
- A valid token is required.
- If no file number is passed in the headers, it will return appeals assigned to the user.
- If a file number is passed in the headers, it will return appeals with that file number.
- Only return appeals in ACT status.

**Comment by laurjpeterson** [comment]
This is done.
