### ISSUE TITLE
Editing VBA issues | edit non-rating issues

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6368]
## Story
When a VBMS user needs to modify claim issues under review after an intake is completed for a Higher Level Review, Supplemental Claim, or NOD from the "Edit Claim Issues" page in Caseflow, they can remove previously entered non-rated issues.

This issue overlaps greatly with #6385 

## Acceptance Criteria
- remove button uses font awesome icon [trash-alt ](https://fontawesome.com/icons/trash-alt?style=regular&from=io) and is clickable along with the "remove" text.
- The order of fields should be "Issue category" "Decision date" "Issue Description" and then the Remove link. When viewing a full screen width, all these should be inline. When viewing on small screen, "Issue Description" should drop to a second row (see mockup)
- note: "add issue" button style changed to the "secondary" button pattern per #6384
- note: clicking "remove" will trigger a modal asking "are you sure..." with a call to action button to actually remove it. This is covered in #6402.

### Full width
<img width="605" alt="screen shot 2018-07-25 at 6 41 56 pm" src="https://user-images.githubusercontent.com/11219417/43231444-6f416a58-903a-11e8-89c8-eea5e52c4950.png">

### Shorter width
<img width="356" alt="screen shot 2018-07-25 at 6 42 18 pm" src="https://user-images.githubusercontent.com/11219417/43231459-7e1e8b64-903a-11e8-9783-9754c2cf9a98.png">

## Related issues
- Design issue: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/941

**Comment by abbyraskinUSDS** [comment]
My hunch is that this will be difficult to test until #6148 is complete

**Comment by shanear** [comment]
this is outdated now
