### ISSUE TITLE
Improve appearance of case table headers

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6369]
We have been adding sorting ability to our tables in a piecemeal way (based on highest priority). Now that we have added sorting for [days waiting](https://github.com/department-of-veterans-affairs/caseflow/issues/6299), let's move forward and make all columns sortable.

@mdbenjam has been working on the dev [[see slack message](https://dsva.slack.com/archives/C6E41RE92/p1532378719000241)]

And here's what I propose it looks like:

<img width="767" alt="screenshot 2018-07-26 08 40 16" src="https://user-images.githubusercontent.com/1598889/43265968-2a9edb96-90b8-11e8-8ad7-d1c989d14c9e.png">

## AC

- [ ] normally, make all text left aligned. however, whenever column header might span two lines, make it center aligned.
- [ ] the carats are 10 px to the right of the column header, horizontally centered to it
- [x] carats gray until clicked on. whenever ascending/descending, the appropriate carat is blue to indicate active state
- [x] include spacing and text sizing constraints to the column header text such that carets never wrap down to a different line

The grid behind this shows us that each table column is two grids wide (Mark if this looks unfamiliar to you, don't worry, we'll walk through the new grid for smaller screens next week):

<img width="766" alt="screenshot 2018-07-26 09 41 54" src="https://user-images.githubusercontent.com/1598889/43266059-5ffbefae-90b8-11e8-8c83-422e7c07a403.png">

@sneha-pai can I get your 👀on this?

**Comment by lowellrex** [comment]
PR #6616 includes some--but not all--of the desired changes here. As far as I can tell, the remaining changes are:
* Decrease space between text and sorting indicator carets when column header spans two lines
* Center align text when column header spans two lines
* Constrain column headers to grid

**Comment by mkhandekar** [comment]
@lowellrex should we make a new issue for the 3 bullets you identified?

**Comment by lowellrex** [comment]
As far as I can tell, all three of those items still need to be addressed. I think the below screenshot demonstrates all three:
![image](https://user-images.githubusercontent.com/32683958/45513018-8ecf4000-b76f-11e8-88c6-174fbd1f2b7d.png)

As for whether we want to create a new issue or keep that work attached to this ticket, I have no preference either way.

**Comment by mkhandekar** [comment]
Cool, I'm good with keeping this open!

**Comment by allyceh** [comment]
@sneha-pai @mkhandekar and I had a conversation about removing "due date" and just having "days waiting" as a stand alone, sortable column. This is based on user feedback.

**Comment by jimruggiero** [comment]
@carodew For awareness, moving this to the design backlog.

**Comment by hschallhorn** [comment]
![Screen Shot 2020-07-10 at 12.22.42 PM.png](https://images.zenhubusercontent.com/5cf5629d96db72707b4b2717/9b6bd8f0-1951-472e-a375-609d57780577)

Select header seems like it should be center justified. Veteran documents should be center justified per the AC.
