### ISSUE TITLE
Caseworker:  EC Task:  Prefetch decision documents when creating Claims Establishment jobs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#637]
As a Caseworker, I only want an Establishment Claim (EC) task created when an appeal has an available decision document. Otherwise continue checking for the document each day.  So that no EC task is queued up without a decision document.

# Acceptance Criteria
1. Verify that an Establishment Claim Task is created only when an appeal has a decision document in VBMS.
2. Verify that when an appeal can not be associated with a decision document, the appeal is included in the next run of the task creation process.

# Technical Notes
When creating claims establishment jobs, we should prefetch the decision document from VBMS and store it in S3. 

Additionally, we should deal with three edge cases:
1) No decision document exists - in this case we should somehow mark this appeal as needing a decision so it can appear on the report described in #408
2) Two or more decision documents exist (in the time range) - A task should still be created, but these should marked as having too many decisions in the time range, and when that task is assigned to a user, they should be notified that they need to cancel the task and create the EP outside of caseflow.
3) Two or more appeals exist for the same veteran on the same decision date - do the same as edge case 2. Except mark each appeal as having a conflicting date with another appeal for that veteran. Inform the user that they must cancel the task and complete the EP Establishment outside of caseflow.

The extended solution for edge cases 2/3 will be fleshed out in future issues.

# Related Stories

**Comment by lakohl** [comment]
@shanear we have issues that go beyond this milestone - e.g. multiple EPs and multiple decisions. Do you want to include them in UAT or not?

**Comment by kierachell** [comment]
Need to see if we have appropriate test data to validate this in `uat`

**Comment by kierachell** [comment]
**PASSED**
Checked in `preprod` via the `missing-decision` page.
