### ISSUE TITLE
Veteran Documents column iteration: include link, doc count and "new" icon

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6370]
We removed the document count because in colocated research, we found that folks did not mention using document count to help them prioritize cases, and because `View documents` is a much clearer & actionable link than `1234 documents`. 

But that might have been because we didn't actively inquire about it - and that's a small research failure on our part, because we started getting support tickets asking for this feature back. [See slack thread](https://dsva.slack.com/archives/C6E41RE92/p1532379929000041).

Here's a middle-of-the-road approach that meets these needs:

## AC
- actionable link `View Docs`
- leaving space for "new" icon when needed, to the right of the link. [Download SVG here](https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/Caseflow%20Queue/images). 
  - on hover, tooltip informs user that "this case has new documents" 
- In table: document count (2 pts smaller than link, in color `$color-gray`)
- In case details: document count (same size as link, in color `$color-gray`)

### In table 
<img width="318" alt="screenshot 2018-07-31 11 13 07" src="https://user-images.githubusercontent.com/1598889/43468747-be3035e6-94b2-11e8-8859-937474d5bfaf.png">

### In case details
<img width="1468" alt="screenshot 2018-07-31 11 17 51" src="https://user-images.githubusercontent.com/1598889/43469072-641cca32-94b3-11e8-87bf-8f020a483081.png">

cc: @sneha-pai @laurjpeterson

**Comment by laurjpeterson** [comment]
This looks good to me! I added the Acceptance Criteria heading to your three bullet points - I think it's ready to be picked up by an engineer!

**Comment by mkhandekar** [comment]
Thank you, LP!

**Comment by mdbenjam** [comment]
What should the loading state for the number of documents be? Is the text `Loading number of docs...` okay?

**Comment by mkhandekar** [comment]
We decided to have the loading text on the table, but not in case details.

**Comment by lowellrex** [comment]
Completed by #6571.
