### ISSUE TITLE
Intake Sync Job fails on reopen_undecided_appeal!

### ISSUE THREAD

**Issue by kahlouie** [department-of-veterans-affairs/caseflow#6377]
Seen starting July 11, 2018 2:30:29 AM UTC.

Sentry errors found here: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1942/events/latest/

**Comment by shanear** [comment]
This is a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/6810

closing
