### ISSUE TITLE
Error Handling | Messages and Design

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6381]
We need to confirm the messages and design of error handling. I think it makes the most sense to have a generic error message ('We have found the following errors: <errors>. Please check the uploaded spreadsheet and dates and try again'), and then specify the errors in a list.

Current error messages and design:

```
ERROR_MAPPINGS = {
  'ValidationError::MissingStartDateEndDateFile': 'Please upload a file and enter a start date and an end date.',
  'ValidationError::EndDateTooEarly': 'Please enter an end date that is after the start date.',
  'SchedulePeriod::OverlappingSchedulePeriods': 'You have already uploaded a file for these dates. Please check your file to make sure you have entered the correct dates.',
  'HearingSchedule::ValidateRoSpreadsheet::RoDatesNotUnique': 'You have listed duplicate non-availability dates for an RO. Please update spreadsheet and try again.',
  'HearingSchedule::ValidateRoSpreadsheet::RoDatesNotInRange': 'The ro non-availability spreadsheet contains dates outside the range you selected. Please update these dates and try again.',
  'HearingSchedule::ValidateRoSpreadsheet::RoDatesNotCorrectFormat': 'All dates must be in the following format : mm/dd/yyyy. Please check the RO non-availability sheet to make sure all dates match this format.',
  'HearingSchedule::ValidateRoSpreadsheet::RoTemplateNotFollowed': 'We have found column names that vary from the template. Please check the RO non-availability sheet for any additional or different columns and upload the corrected file again.',
  'HearingSchedule::ValidateRoSpreadsheet::RoListedIncorrectly': 'The ro non-availability spreadsheet lists different ROs than we have in our system. Please ensure every Regional Office has a row and upload the corrected file.',
  'HearingSchedule::ValidateRoSpreadsheet::CoDatesNotUnique': 'The central office non-availability spreadsheet contains dates outside the range you selected. Please update these dates and try again.',
  'HearingSchedule::ValidateRoSpreadsheet::CoDatesNotInRange': 'The central office non-availability spreadsheet contains dates outside the range you selected. Please update these dates and try again.',
  'HearingSchedule::ValidateRoSpreadsheet::CoDatesNotCorrectFormat': 'All dates must be in the following format : mm/dd/yyyy. Please check the CO non-availability sheet to make sure all dates match this format.',
  'HearingSchedule::ValidateRoSpreadsheet::CoTemplateNotFollowed': 'We have found column names that vary from the template. Please check the CO non-availability sheet for any additional or different columns and upload the corrected file again.',
  'HearingSchedule::ValidateRoSpreadsheet::AllocationNotCorrectFormat': 'The central office non-availability spreadsheet contains dates outside the range you selected. Please update these dates and try again.',
  'HearingSchedule::ValidateRoSpreadsheet::AllocationRoListedIncorrectly': 'The allocation spreadsheet lists different ROs than we have in our system. Please ensure every Regional Office has a row and upload the corrected file.',
  'HearingSchedule::ValidateRoSpreadsheet::AllocationDuplicateRo': 'The allocation spreadsheet lists the same RO twice. Please update the spreadsheet and try again.',
  'HearingSchedule::ValidateRoSpreadsheet::AllocationTemplateNotFollowed': 'We have found column names that vary from the template. Please check the allocation sheet for any additional or different columns and upload the corrected file again.',
  'HearingSchedule::ValidateJudgeSpreadsheet::JudgeDatesNotCorrectFormat': 'All dates must be in the following format: mm/dd/yyyy. Please check the judge non-availability sheet to make sure all dates match this format.',
  'HearingSchedule::ValidateJudgeSpreadsheet::JudgeTemplateNotFollowed': 'We have found column names that vary from the template. Please check the spreadsheet for any additional or different columns and upload the corrected file again.',
  'HearingSchedule::ValidateJudgeSpreadsheet::JudgeDatesNotUnique': 'You have listed duplicate non-availability dates for a judge. Please update the spreadsheet and try again.',
  'HearingSchedule::ValidateJudgeSpreadsheet::JudgeDatesNotInRange': 'The judge non-availability spreadsheet contains dates outside the range you selected. Please update these dates and try again.',
  'HearingSchedule::ValidateJudgeSpreadsheet::JudgeNotInDatabase': 'A judge listed in the spreadsheet is not in our database. Please check the CSS IDs and try again.',
  'ValidationError::UnspecifiedError': 'Something went wrong while uploading the spreadsheet. Please check the data and try again.'
};
```

<img width="1036" alt="screen shot 2018-07-26 at 10 49 34 am" src="https://user-images.githubusercontent.com/4306128/43283089-f06407ac-90e5-11e8-95e7-c21fa6b8d1f9.png">

**Comment by Chingujo** [comment]
@sharonwarner  The parsing T-T.

Here are the error messages in order of above to help with copy and pasting. I separated between sections. 
### General
- Please select one of the options below to upload your file. 

- Please enter an end date that is after the start date 

- We have found a previously uploaded file for these dates. Please check your file to make sure you have entered the correct date range.

### RO

- We have found duplicate non-availability dates for an RO. Please check your file and remove any duplicates before uploading. 

- The RO non-availability spreadsheet contains dates outside the range you selected. Please enter a date range that includes all the dates in your file. 

- All dates must be in the mm/dd/yyyy format. Please check your RO non-availability spreadsheet and make sure all your dates are entered correctly. 

- We have found column names that vary from the template. Please check your RO non – availability spreadsheet and sure that the column names have not been changed from the template.

- We found Regional Offices that do not match our system. Please check your file and ensure every Regional Offices has a row and there are no duplicate or additional RO’s. 

#### Central Office

- The CO non -availability spreadsheet contains dates outside the range you selected. Please enter the date range that encompasses all the dates in your file. 

- The CO non-availability spreadsheet contains dates outside the range you selected. Please enter a date range that includes all the dates in your file. 

- All dates must be in the mm/dd/yyyy format. Please check your CO non -availability spreadsheet and make sure all your dates are entered correctly.

- We found column names that vary from the template. Please check your CO non–availability spreadsheet and sure that the column names have not been changed from the template.

- The CO non-availability spreadsheet contains dates outside the range you selected. Please enter the date range that encompasses all the dates in your file. 

#### Allocation? 
- The allocation spreadsheet has Regional Offices that do not match our system. Please check your file and ensure every Regional Offices has a row and there are no duplicate or additional RO’s. 

- The allocation spreadsheet lists the same RO twice. Please check your file and remove any duplicate RO’s. 

- We have found column names that vary from the template. Please check the allocation sheet for any additional or different columns and upload the corrected file again.

- All dates must be in the mm/dd/yyyy format. Please check your judge non -availability spreadsheet and make sure all your dates are entered correctly.  

#### Judges

- We found column names that vary from the template. Please check your judge non-availability spreadsheet and sure that the column names have not been changed from the template.

- We have found duplicate non-availability dates for an judge. Please check your file and remove any duplicates before uploading. 

- The judge non-availability spreadsheet contains dates outside the range you selected. Please enter a date range that includes all the dates in your file. 

- We found a judge that is not in our system. Please make sure all your CSS ID’s are correct before trying again.

**Comment by Chingujo** [comment]
### Mocks for multiple errors
![upload page multiple errors](https://user-images.githubusercontent.com/23316107/43409039-cbb1664e-93f0-11e8-9b4c-ce16bc311adf.png)

**Comment by Chingujo** [comment]
@amiklik 
Hi rock star Amanda! Caseflow Hearing schedule is currently trying to nail down error messaging for our allocation algorithms. These are mostly upload errors that deal with the data entry in the file they are uploading. 

For more context, the users are HMB branch managers who have a pretty good understanding of the terms such as Regional Office and Central Office. We are also trying to figure out in the rare instance when they are more than one errors with an upload. 

Tagging you since you mentioned consistent error messaging in last design meeting and don't want caseflow to be on the bad list =D. No worries if you are busy though!
