### ISSUE TITLE
Intake | Finish: "add issue" button style change

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6384]
Button style for "add issue" should change from the primary button design pattern (blue with white text) to the secondary button design pattern (blue outline, white background, blue text) and the corresponding active and visited states as shown in the style guide. This button appears on the Finish page of the original intake flow and on the corresponding page in the edit flow for HLR, Supplemental, and NOD. This change is being made so this button doesn't distract from the primary call to action button that advances you to the next screen.

## Acceptance Criteria
- "+ Add issue" button style uses secondary button design pattern
  - This button appears on the Finish page of the original intake flow and on the corresponding page in the edit flow for HLR, Supplemental, and NOD.

## Mocks
<img width="135" alt="screen shot 2018-07-26 at 3 53 20 pm" src="https://user-images.githubusercontent.com/11219417/43285157-143b7380-90ec-11e8-94d8-9dfd2e1a82c5.png">

**Comment by leikkisa** [comment]
Validation test file number: 586864247

**Comment by suzchap** [comment]
I still see the primary button -- at least in the HLR flow ---

![Screen Shot 2018-08-24 at 2.30.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57758753a582050e0017b00d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f76b7191a37af1112b4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19041c95df54ee04953a1123566e3702431.png)

**Comment by suzchap** [comment]
LGTM
