### ISSUE TITLE
Intake | Finish: add link to remove "other" issues

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6385]
## Story
During the original intake flow for Supplemental Claims, HLR, and NOD, users need to be able to remove non-rated "other" issues that they've just added so they can make final decisions before submitting the EP. 

## Acceptance Criteria

- The "Remove" button uses font awesome icon [trash-alt](https://fontawesome.com/icons/trash-alt?style=regular&from=io) and is clickable along with the "remove" text.
- The order of fields should be "Issue category" "Decision date" "Issue Description" and then the Remove link. When viewing a full screen width, all these should be inline. When viewing on small screen, "Issue Description" should drop to a second row (see mockup).
- "Issue category" and "Issue description" field labels no longer have a red "required" labels.
- note: "add issue" button style changed to the "secondary" button pattern per #6384
- note: clicking "remove" will trigger a modal asking "are you sure..." with a call to action button to actually remove it, but this functionality is not required for this story. This is covered in #6402.

## Mocks
<img width="600" alt="screen shot 2018-07-27 at 2 20 22 pm" src="https://user-images.githubusercontent.com/11219417/43339760-3ab9dc4c-91a8-11e8-9e5c-14316e027033.png">

<img width="217" alt="screen shot 2018-07-27 at 2 38 13 pm" src="https://user-images.githubusercontent.com/11219417/43340548-bfbc3140-91aa-11e8-90f4-77d533adf96f.png">

## Related issues
- Design issue: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/941
- Edit flow version of this ticket #6368

**Comment by kahlouie** [comment]
on hold - we're waiting until we can focus on non-rating together -LB

**Comment by shanear** [comment]
This is outdated and no longer relevant. Closing
