### ISSUE TITLE
Colocated - Table: "On hold" Tab

### ISSUE THREAD

**Issue by sneha-pai** [department-of-veterans-affairs/caseflow#6388]
### User Stories
- When an administrative action requires further actions before assigning back to an attorney (e.g. extension request, wait for IHP or POA clarification), co-located team members need to put the case on hold.
  - This does not remove the case from the co-located team member's list of work, but recognizes that further work cannot be done on it at this time. It should not count against the user's productivity standards by still being on the team member's plate.

#### "On hold" Tab
![colocated-table-on-hold-tab](https://user-images.githubusercontent.com/31224257/43293713-b6e88222-9109-11e8-8831-fed1c32a6230.png)

**Comment by laurjpeterson** [comment]
This is live. Closing!
