### ISSUE TITLE
Co-located Table: "Pending action" Tab

### ISSUE THREAD

**Issue by sneha-pai** [department-of-veterans-affairs/caseflow#6389]
### User Stories
- When an admin action's hold is up, co-located team members want to be alerted, so they can continue working on the case ASAP and move the appeal along in the process.

##### Pending Action Tab
![colocated-table-pending-action-tab-768](https://user-images.githubusercontent.com/31224257/43294059-7e8bf330-910b-11e8-8e19-8c384e0f231e.png)

**Comment by laurjpeterson** [comment]
This is live. Closing!
