### ISSUE TITLE
Queue improved access control

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#6391]
We need to make a few improvements to our access control checks.

1) Before searching for a Veteran file number or showing a details page we need to
   - Make a call to BGS to see if the user has access to the veteran file
   - If the user is a VSO check to see if the user is part of the VSO/is the rep for the veteran
1) We need to split up the appeal/task endpoints.
   - One for getting tasks that go on the queue page (i.e. just basic info like name of veteran docket number etc.)
   - One for getting detailed information on the case details screen.

This way the most information we return if a user doesn't have access to the veteran is a name and SSN.

**Comment by lowellrex** [comment]
This is complete! The second improvement was completed in #6786.
