### ISSUE TITLE
Return judge information from and user information from IDT API endpoints

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6395]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/6358

# AC
- `/idt/api/v1/judges` should return a list of all judges, with first name, middle name, last name, and attorney id for each judge
- `/idt/api/v1/user` should return user info for the user associated with a token, with first name, middle name, last name, attorney id, vlj status, and css id
- both routes should only be accessible if a valid token is passed in the headers

**Comment by laurjpeterson** [comment]
PR was merged, closing.
