### ISSUE TITLE
Refactor Queue to enable pulling only basic appeal information from tasks endpoint and task info from the appeals endpoint

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#6396]
In thinking through access control, we've decided the need to separate basic appeal info (name, docket number etc) from more sensitive information (appellant, rep, issues, etc.) In order to get to this point we need to separate endpoints. The first endpoint is the tasks endpoint which will return basic information on each appeal. This will not do a sensitivity access check before returning. The second endpoint is the appeals endpoint which will start returning any tasks of the appeal assigned to the current user, and will return the full appeal information. This will do a sensitivity access check before returning.

The redux store will store denormalized state in three places.
1) `queue.basic_appeal_info`
1) `queue.full_appeal_info`
1) `queue.tasks`

We'll make requests to the tasks controller on `queue` pages and requests to the appeal controller on the `details` page.

**Comment by evankroske** [comment]
Will full_appeal_info store a superset of the information in basic_appeal_info?

**Comment by mdbenjam** [comment]
I'm thinking yes. Normally against duplicating state... But I think this might be a reasonable use case. We could also have them store a disjoint set of data.
