### ISSUE TITLE
Support Quality Review

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6407]
The Quality Review department reviews the quality of a subset of BVA decisions before they are sent to Veterans. The current rule is:
- every 10th CAVC appeal is reviewed
- every 20th appeal of any other type is reviewed
- a max of 136 cases are sent to QR in a month

There is functionality in DAS and VACOLS that recognizes which cases are sent to QR at the time the judge sends a case to BVA dispatch and keeps track of a counter so it stops when it hits 136 cases. 
- Jed said he sends every 40th case to QR (which is different than the methodology Josh laid out above)
- BVA usually hits 136 cases the 3rd week of the month
- We could have a goal of rolling out Caseflow judge check out by the 3rd week of August, so we can have QR selection in one place instead of two asap

We have already built Caseflow functionality for judges to send cases to BVA dispatch and plan to pilot it with 24 judges. We will need to send some cases checked out in Caseflow to QR, because 24 of 96 judges at the Board is a significant enough portion.

### Idea
- Divide the 136 cases sent to QR between Caseflow and DAS/VACOLS cases proportionally - 24 judges piloting Caseflow is 1/4th of the total number of judges :
  - DAS/VACOLS collects 102 cases
  - Caselfow collects 34 cases
- When a judge finishes the check out flow, Caseflow selects cases for QR. Caseflow changes their VACOLS location to 48 instead of the dispatch location of 4E
  - Every Xth CAVC case 
  - Every Yth other cases
  - Assumption: this can't be the same as for the total judge population, because of the smaller size of judges 
- Caseflow updates the VACOLS counter to keep track of progress toward the 136 total goal

### Open Questions
- How does Jed's case selection need to change in the short term, with fewer judges using DAS?
- How does knowing we will have to do this in the long run affect how we build this now?
- What are the merits of updating the VACOLS counter or not?

### Resources
- Convo with Jed about QR program logic - https://github.com/department-of-veterans-affairs/dsva-vacols/issues/23
- Notes from conversation with Josh Freeman, QR, July 27, 2018 - https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Post-Discovery/Quality%20Review.md

**Comment by cmgiven** [comment]
This approach makes sense to me.

Small future note: AMA may justify an increase to the number of cases that go to QR. The Board will want to make assertions that its quality is unchanged from legacy to AMA, which the current sample size is not designed to support. We should particularly ask whether they want to oversample post-RAMP appeals in the October period so as to be able to make such claims prior to February.

**Comment by aroltsch** [comment]
In Caseflow, there is a table `judge_case_reviews`. We can utilize this table to implement a database trigger to count how many case reviews already happened in the month. We will only be counting cases that are sent to BVA Dispatch location. 

1. Is the case a CAVC case? If yes, count how many CAVC cases were created within a month. If it is Xth CAVC case, send it for review. 
2. Is the case a CAVC case? If no, count how many non-CAVC cases were created within a month in Caseflow. If it is Yth non-CAVC case, send it for review.
3. How do we determine what `X`th and `Y`th case in caseflow? Jed will probably need to adjust his X and Y?
3. If we are checking against the VACOLS counter (137) do we even need to set our max number of cases we collect?

**Comment by laurjpeterson** [comment]
@aroltsch - agree that we will only count cases sent to BVA dispatch location. re: number 4. I was thinking we would update Jed's VACOLS counter when we sent a case to QR so VACOLS knew to stop sending cases to QR. do you think this is feasible or too much effort?

@cmgiven  re: 20-sided die - do you think there are any issues if we do 20-sided die but jed's methodology is different? separately, do you think this is the preferred way to do QR in the long run?

**Comment by aroltsch** [comment]
I think it would make sense to introduce our own counter assuming we will be deprecating DAS and we will need to introduce our counter anyways at some point. As we roll out to more users, we can ask Jed to adjust his numbers accordingly?

**Comment by cmgiven** [comment]
@laurjpeterson Provided we are both looking at different sets of cases (there isn't ever a case that could get grabbed by both Caseflow and VACOLS), the method doesn't matter. I think the random number generator is probably the better way to go for the long term, but there are tradeoffs.

Advantages: 

* Doesn't require a counter, easier to implement.
* Independence of draws, so its more difficult to game. If I've just finished a case that got sent to QR, that doesn't affect the likelihood that the next case I finish will also get sent to QR (unless we've crossed the monthly limit).

Downsides:

* The monthly limit remains an issue that affects the randomness of the sample. Submitting later in the month make you less likely to get selected for QR.
* The number of cases drawn is now subject to random variation. There's a (quantifiable) risk that you might not select enough cases in a given month to meet or exceed the limit, thus filling the quota.

**Comment by laurjpeterson** [comment]
Thanks @cmgiven - can you explain more about the 2nd downside bullet? I spoke with Josh Freeman about QR on Friday, and he explained that over selection of cases for QR is much better than underselection of cases. I'm hesitant to explore an option that leaves QR at risk of underselection.

**Comment by cmgiven** [comment]
That might be sufficient to rule it out. Here's an example:

Let's say the Board does 10,000 decisions a month. QR wants 200 cases. If we were to use a naive probability of 200/10,000 (2%), 50% of the time (actually 49% of the time, because [binomial probability](https://www.khanacademy.org/math/ap-statistics/random-variables-ap/binomial-random-variable/v/binomial-variables)), we'd grab too few cases.

So instead, we adjust the number. Let's say that instead of sending a case to QR 2% of the time, we instead send it to QR 2.25% of the time. Now we have a sufficient number of cases 96% of the time, but still, we'd expect that once every two years or so, we'd not have enough.

So we adjust it further. We grab 2.5% of cases. We'll generally hit our quota earlier in the month, but as a result, we have too few cases only 0.04% of the time, or once every 200 years or so.

If we go up to 3% of cases, it basically becomes a statistical impossibility that we have too few cases (although statistically impossibility does not preclude reenacting the first scene to _Rosencrantz and Guildenstern are Dead_ at some point in the next few millennia). The downside being that in a typical month, we'd expect to hit our limit about 2/3rds of the way into the month.

**Comment by laurjpeterson** [comment]
I see, thanks for the explanation. (Though I'll need to watch Rosencrantz and Guildenstern are Dead in follow-up...) I think we should go to 2.5% of the cases. Josh explained that they hit the limit around the 3rd week of the month currently, so I think hitting the limit earlier in the month is ok. 

How would we implement this? I'd like to send an explanation to Josh, and give @aroltsch some guidance on what to do next.

**Comment by cmgiven** [comment]
Using the numbers from Lauren's email to Josh, we should take 4% of cases (0.04). Here's the explanation, as could be left in a comment next to that constant (and note that when Caseflow handles everything, this number will need to be revised down).

```ruby
QR_SELECTION_PROBABILITY = 0.04
# Probability that a given case should be selected for Quality Review (p)
# We want the number of cases selected in a given month (X) to equal or exceed the target (x), as any excess selected cases will be ignored. The target during the pilot is 34 cases.
# We want the probability that X is less than x (P(X<x)) to be less than 0.000833, an event that would happen once per century.
# In December 2017, the Board wrote 5,549 decisions. Taking 1/4 of that figure, reflecting that Caseflow is piloted with 1/4 of the Board's judges, we have a number of trials (n) equal to 1,387.
# When n = 1,387, x = 34, and p = 0.04, we find that P(X<x) = 0.000464, which is less than our maximum probability 0.000833.
# This probability should be 0.032 when Caseflow expands to include all judges.
# When n = 5,549, x = 136, and p = 0.032, we find that P(X<x) = 0.00043, which is less than our maximum probability 0.000833.
# An easy way to avoid doing the math is to use this calculator: https://stattrek.com/online-calculator/binomial.aspx
```

**Comment by laurjpeterson** [comment]
For context, my email to Josh:

Hi Josh,

Thanks again for connecting last Friday. Here's what we're thinking to support Quality Review while piloting Caseflow judge check out to BVA dispatch functionality as soon as this week. 

What do you think about this methodology?:
- Divide the 136 cases sent to QR between Caseflow and DAS/VACOLS cases proportionally - 24 judges piloting Caseflow is 1/4th of the total number of judges:
   - DAS/VACOLS collects 102 cases for QR
   - Caselfow collects 34 cases for QR
- For VACOLS:
   - Jed updates the VACOLS counter to be 102 cases instead of 136 cases, and keep your selection methodology the same
   - Note: Jed explained that CAVC decisions and regular decisions are now combined and selected as one pool of cases. There is no longer separate selection intervals for CAVC cases and regular cases. A few years ago there was separate intervals but now all decisions fall into one pool.
- For Caseflow:
   - When a judge finishes the check out flow, Caseflow randomly selects cases for QR.
   - We will either select cases randomly by implementing a methodology of rolling a 20-sided die, or repeat Jed's current methodology of selecting every 40th case
   - Caseflow changes selected cases' VACOLS locations to 48 instead of the dispatch location of 4E.
   - Caseflow keeps a counter for how many cases sent to QR. Caseflow stops sending cases to QR when we hit 34 cases.
- If Jed updates the VACOLS counter to 102 instead of 136, we think that Caseflow doesn't need to update the VACOLS counter itself.

Let us know what you think!

**Comment by laurjpeterson** [comment]
@aroltsch has implemented support for QR, so closing this issue.
