### ISSUE TITLE
Modals: Polish modals throughout Caseflow

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#641]
As an engineer, I want to build modals in any Caseflow app consistently, so that designs can be implemented quickly and to USWDS/VA Appeals standards.

## Acceptance Criteria
1. Modals should follow spacing, type treatment, button placement, and styling as shown in the mocks below. 
2. UI that isn't shown in the mocks below should follow USWDS / VA style guide standards.

## Mocks

Example of modal with disabled button:
![screen shot 2017-01-04 at 6 07 46 pm](https://cloud.githubusercontent.com/assets/1178390/21692650/d31d4c5c-d34b-11e6-9d1e-1cb4c2c70d78.png)

Example of modal with enabled button:
![screen shot 2017-01-04 at 6 07 40 pm](https://cloud.githubusercontent.com/assets/1178390/21692657/d6e4fb6e-d34b-11e6-8418-44a714d3d92f.png)

**Comment by shellicious** [comment]
@KHarshawat, perhaps you can provide more guidance on exact spacing? These mocks came from a style guide Sketch file you posted pre-holiday break.

Context is, as engineers are building modals for Dispatch and Certification cancellation flows, they are in need of guidance to make sure modals are consistent.

**Comment by shanear** [comment]
Work with @KHarshawat on this.

**Comment by mmlumba** [comment]
@lakohl @abbyraskin The current text for Dispatch is the following:
![screen shot 2017-01-30 at 11 42 22 am](https://cloud.githubusercontent.com/assets/4773320/22431920/39847940-e6e1-11e6-8c6b-5fd5711807f9.png)

For this specific Dispatch modal would you like me to update the text as well?

**Comment by lakohl** [comment]
@mmlumba the most recent copy and for the required field styling are shown in the mock below:
<img width="591" alt="screen shot 2017-01-30 at 12 21 29 pm" src="https://cloud.githubusercontent.com/assets/4975959/22433594/e8754e20-e6e6-11e6-9035-8a74cdf497b9.png">

**Comment by KHarshawat-gov** [comment]
@mmlumba 

![image](https://cloud.githubusercontent.com/assets/25437276/22514016/f4956614-e86b-11e6-9029-9f830319c29a.png)

**Comment by mmlumba** [comment]
@KHarshawat What are the border radius/drop shadow specs?

**Comment by KHarshawat-gov** [comment]
I would make `border-radius: 3px`
I would use the exact same `box-shadow` we used for the dropdown the other day.
