### ISSUE TITLE
Clean up failed Ramp Refiling EP data

### ISSUE THREAD

**Issue by kahlouie** [department-of-veterans-affairs/caseflow#6416]
There have been 13 cases where the completion of a Ramp Refiling failed mid way through. We can see all 13 currently affected file numbers via the following console query:

```
EndProductEstablishment.where(source_type: "RampRefiling").select { |e| e.source.nil? }
```

We need to determine a way to clean up this data and then do it.

## Technical notes
This can cause an error when the Refiling is re-processed. Example:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2144/

This problem could recur, until we handle the below issues:
requires #6354
requires #6356
requires #6357

**Comment by kahlouie** [comment]
These appear to happen directly after the VBMS v5 errors. They may only be nil when VBMS fails OR it could be the other way around where when valid modifiers is nil, it causes VBMS errors. I'm unsure how we get the sentry errors published into slack. We should still continue looking at this one in case that is not true.

**Comment by kahlouie** [comment]
We have not seen this and RAMP intakes have been taken since. Our original theory that these were related to the VBMS errors might be true.

**Comment by kahlouie** [comment]
Still an issue. Moved it back to current sprint.

**Comment by kahlouie** [comment]
I figured this out. this was only true for ramp end products because  https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/ramp_review.rb#L58 the #valid_modifiers method is no longer there. I'll need some help figuring out what a valid modifier for ramp appeal end products are. @shanear do you know?

**Comment by leikkisa** [comment]
Going through the validation tickets. Not sure if you already talked since I don't see a response or another PR.

@kara
They're in the ramp_review file, in the END_PRODUCT_DATA_BY_OPTION, it's using the end_product_modifier method.  So either 683 or 682.

**Comment by kahlouie** [comment]
Yep, I had seen what they are. Somehow this issue came back up though :(

**Comment by kahlouie** [comment]
reopening since we got another error where valid_modifiers is null. I think I'd like someone else's eyes on this problem since I've been the only one to work on it and my fix didn't solve it all. @shanear @leikkisa

**Comment by shanear** [comment]
This one is a little beasty, and is the result of half-completed RampRefilings due to errors mid way through the completion process.

We can see all 13 currently affected file numbers here:
```
EndProductEstablishment.where(source_type: "RampRefiling").select { |e| e.source.nil? }
```

We need to clean up the data with that and possibly start prioritizing the development issues @ferlatte created to solve this problem:

https://github.com/department-of-veterans-affairs/caseflow/issues/6354
https://github.com/department-of-veterans-affairs/caseflow/issues/6356
https://github.com/department-of-veterans-affairs/caseflow/issues/6357

**Comment by kahlouie** [comment]
* issues should get deleted (create a new ticket for this)
* EP establishments shouldn't get deleted
* check whether refiling has been redone -- if it has, cancel the incomplete EP -- if it hasn't, cancel the EP and re-intake it

**Comment by shanear** [comment]
Reran the query. There are now 16 of these 😢 

I think we'll probably want to work on the solution before cleaning up the data.

**Comment by shanear** [comment]
I think the plan here will be to record the file numbers, cancel the EPs and have AMO reprocess them.

**Comment by shanear** [comment]
Cancelled the EPs via the following script

```
bgs = BGSService.new
client = bgs.send(:init_client)

EndProductEstablishment.where(source_type: "RampRefiling").select { |e| e.source.nil? }.each do |epe|
  if epe.status_active?(sync: true)
    client.claims.cancel_end_product(
      file_number: epe.veteran_file_number,
      end_product_code: epe.result.claim_type_code,
      modifier: epe.result.modifier
    )  
  end
end
```

**Comment by shanear** [comment]
All i need to do is send the file numbers to AMO for reprocessing. Will do that tomorrow.

**Comment by shanear** [comment]
the numbers and a description of the issue have been sent to AMO. This ones all done from our perspective 👐
