### ISSUE TITLE
Judge Algorithm | Fix the disabled and non-deterministic tests

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6426]
It always passes locally but only fails on CircleCI

```
 it "all hearing days should be assigned to judges" do
        day_count = hearing_days.reduce(0) do |acc, (_id, hearing_day)|
          acc += 1 unless hearing_day.folder_nr.nil? && !hearing_day.hearing_date.to_date.wednesday?
          acc
        end
      
        # disabled line
        expect(subject.count).to eq(day_count)
end
```
![Screen Shot 2018-08-16 at 12.01.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582a398e7d9c5f1300c030ee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f56b7191a379ed0c2b50415b49bc21254d58eeb9cb74fce36f34985619e8d96f0e76903818aeb18249bb01eb278b4fd7b4b98a4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e54956a110336be3733e6e0a.png)

**Comment by sharonwarner** [comment]
![image (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582a398e7d9c5f1300c030ee/125516c66e82c728ace21e0d46e1999b2487c3e1dea0fd0fe64de29b234324676b5ee17e28d7e27ab9172253565f18a841095844fcab8b2ea6b56e62964e49bc8f3900299f7744eeaa880dbe06b0218e4c83b0b48c44c9ea3b24ef99c2.png)
