### ISSUE TITLE
Backfill and End product modifier not getting saved to End Product Establishments

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6427]
Noticed when poking through UAT that End Products are getting created correctly with the correct modifier, but that the end product modifier in EndProductEstablishments is nil.

**Comment by kahlouie** [comment]
Maybe the right thing is to drop the end product modifier column as we don't use it, even for getting the end product or for showing end product contentions on the page.

**Comment by kahlouie** [comment]
Fixed this in https://github.com/department-of-veterans-affairs/caseflow/pull/6619

**Comment by leikkisa** [comment]
Validated that this is working, still need to backfill data

**Comment by shanear** [comment]
Backfilled the data via the following commands:
```
EndProductEstablishment.where(modifier: nil, code: "682HLRRRAMP").update_all(modifier: "682")
EndProductEstablishment.where(modifier: nil, code: "683SCRRRAMP").update_all(modifier: "683")
```

This fixed all the data:
```
irb(main):022:0> EndProductEstablishment.where(modifier: nil).count
[2018-08-22 12:59:42 -0400]    (6.3ms)  SELECT COUNT(*) FROM "end_product_establishments" WHERE "end_product_establishments"."modifier" IS NULL
=> 0
```
