### ISSUE TITLE
Design Audit for Hearing Schedule 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6433]
## Home page - View the Schedule 
_Note that this will most likely change in the future as we develop other aspects of hearing schedule and we tighten up design for future iterations_ 
Title: Welcome to hearing schedule
Body: The below table shows the hearings scheduled for the dates listed in the below date fields. To change the view, please select a new date range using the From and To fields. To add slots or assign judges, please use the “Build Schedule” button below. 

![list view judge filled](https://user-images.githubusercontent.com/23316107/43471506-29459ad2-94b9-11e8-8fc5-c3b8d6a73eda.png)

## Build Schedule
- The app canvas looks a little wide is this the default width? 
  - Ignore this if the above is true: The copy stretches out can we truncate it so the user doesn't have to read across a large screen?
- Align the Date table header and the date in the table to the title of that page
- If we are removing CO from the spreedsheet we should change the template name from RO/CO hearings to just RO hearings
- Download icon is misaligned

## Upload page
- Same thing change RO/CO to RO hearings
- Can we remove some white space between the date inputs and the instruction. 
- In the date input field you can add more numbers than allowed in a date see screen shot. Can we make it so the user can't do that? Right now it lets me progress without errors despite the wrong year
<img width="374" alt="screen shot 2018-07-23 at 1 39 30 pm" src="https://user-images.githubusercontent.com/23316107/43093426-fdf4b1ec-8e7d-11e8-81d6-3f90d81e405b.png">

## Video Assignment page
- Can we reduce the white space between the top and the banner?

## Video Assignment Modal
- Can we change the styling of the X and remove the blue highlight? 
<img width="41" alt="screen shot 2018-07-23 at 1 41 44 pm" src="https://user-images.githubusercontent.com/23316107/43093491-31001a7c-8e7e-11e8-843d-cd041b7742eb.png">
- Need to change the name from RO/CO

## Confirmation
- When we display confirmation can we include the mm/dd/yyyy format to keep it consitenet with inputs and displays
- Also can we include the link to view schedule in the banner as a link underneath the body copy 

## View Current Schedule
- Can we remove the white space from the date inputs to the From and To and incease the space between the two date inputs
- The date input here also allows the user to put in more numbers than allowed with errors 
- Can't test the apply and clear in demo what does this look like?

**Comment by Chingujo** [comment]
@sharonwarner 

Moved this over from appeals design and added a mock. Didn't put any other labels as none of the above are super high priority.

**Comment by MeredithStewart** [comment]
If this work was prioritized, this ticket would need to be revisited based on new updates.
