### ISSUE TITLE
Testing | RO Algorithm

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6444]
1. #### Test that the hearing days are spread evenly throughout the entire schedule period
- [x] Create a schedule period that is 1 year long
- [x] Allocate 2 hearings to each RO
- [x] Confirm the hearing days are spread evenly throughout the year

2. #### Test that RO non-availability days are filtered out
- [x] Create a schedule period that is 1 week long
- [x] Assign 4 non-availability days to 10 ROs
- [x] Allocate 1 hearing to the same 10 ROs
- [x] Confirm that the 10 ROs are assigned their only available days
- [x] Assign all 5 non-availability days to the same 10 ROs
- [x] Confirm that an error is thrown

3. #### Test that CO non-availability days are filtered out
- [x] Create a schedule period that is 1 week long
- [x] Assign 4 co non-availability days
- [x] Allocate 1 hearing to 10 ROs
- [x] Confirm all 10 ROs are assigned to the available day
- [x] Assign all 5 co non-availability days
- [x] Confirm that an error is thrown

4. #### Test that travel board days are filtered out
- [ ] Create a schedule period that is 1 week long
- [ ] Create travel board hearings for 10 ROs for 4 days
- [ ] Allocate 1 hearing to the same 10 ROs
- [ ] Confirm all 10 ROs are assigned to the available day
- [ ] Create one more travel board hearing for the remaining available day
- [ ] Confirm an error is thrown

5. #### Test that ROs with multiple hearing rooms are assigned multiple rooms on the same day
- [x] Create a schedule period that is 1 week long
- [x] Allocate 10 hearings to St Petersburg
- [x] Confirm that St Petersburg is assigned 2 hearing days on all 5 days
- [x] Create a schedule period that is 1 year long
- [ ] Allocate 2 hearings to St Petersburg
- [ ] Confirm that St Petersburg is assigned both their hearing days on the same day

6. #### Test that no more than 10 hearings days are assigned to the same date
- [x] Create a schedule period that is 1 week long
- [x] Allocate 5 hearings to 10 ROs
- [x] Confirm that all 10 ROs are assigned hearings for each available day
- [ ] Allocate 5 hearings to 11 ROs
- [ ] Confirm that an error is thrown

**Comment by Sjones352** [comment]
@MeredithStewart 
1. #### Test that the hearing days are spread evenly throughout the entire schedule period
This test passes validation. I used this spreadsheet 
[validRoAlgorithm.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2390290/validRoAlgorithm.xlsx) and  after filtering it to 1 year period, I downloaded 
[HearingSchedule1yearPeriod.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2390317/HearingSchedule1yearPeriod.xlsx)

2. #### Test that RO non-availability days are filtered out
I used this spreadsheet
[validRoOneWeek.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2390330/validRoOneWeek.xlsx) and I am getting this error 
<img width="1417" alt="screen shot 2018-09-17 at 5 11 28 pm" src="https://user-images.githubusercontent.com/23080951/45651256-e981d800-ba9e-11e8-906c-d1e578ac82ab.png">

**Comment by MeredithStewart** [comment]
@Sjones352 -- 
1. I can't open the second file (the output) on the first test above. Can you see if it works for you or reattach? My computer is saying it's corrupted or not the right file type. 
2, 3, and 4 -- You shouldn't get that error for those tests. @sharonwarner spreadsheet or system might need updating.

**Comment by MeredithStewart** [comment]
For the first part of the test, "2. Test that RO non-availability days are filtered out," the algorithm is applying a CO Hearing day for a FRIDAY (should be a Wed.) and it has a judge in the output. It would be good for @sharonwarner to take a look.

**Comment by MeredithStewart** [comment]
For the first part of test, "3. Test that CO non-availability days are filtered out," update the input spreadsheet to remove the RO non-avail days (putting in N/A along top rows) and then add the 4 non-avail days to the tab, "Board Non-Avail Dates." Then re-run and see if output puts all hearing dates for the ROs on the same day.

**Comment by MeredithStewart** [comment]
For test #4 - to make sure travel board dates are filtered out -- will need help from @sharonwarner.

**Comment by MeredithStewart** [comment]
@sharonwarner -- @Sjones352 and I have attempted to complete testing outputs, but we keep having issues having the algorithm run. Maybe you and I can knock this out next week?
