### ISSUE TITLE
eFolder Express | remove VVA copy

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#6451]
Update eFolder Express homepage copy

### Home page
- Remove copy indicating that eFolder Express now contains VVA documents

<img width="511" alt="screen shot 2018-07-31 at 11 06 11 pm" src="https://user-images.githubusercontent.com/4975959/43498767-635c6914-9516-11e8-8a74-80b270bffbff.png">

**Comment by pkarman** [comment]
won't fix
