### ISSUE TITLE
 Manager View Queue link font bolded

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#646]
While on Caseflow Dispatch in a **Manager View**, the user sees the link to the queue of cases as a bolded link currently. Please see attached for reference.

<img width="833" alt="screen shot 2017-01-06 at 11 03 35 am" src="https://cloud.githubusercontent.com/assets/23038505/21723840/f09f036a-d3ff-11e6-9909-3b6f676f738e.png">

**Comment by kierachell** [comment]
It's not a link at the moment, right?

**Comment by astewarttistatech** [comment]
@kierachell Not to my knowledge but @KHarshawat referred to it as one.

**Comment by kierachell** [comment]
Need to know if this is actually supposed to be a link or just plain text or header text; then we'll pass it on to reimplement

**Comment by lakohl** [comment]
@kierachell it's not a link.
Here is a later design (prob, soon to change also).  I would prefer it be dark grey so that people don't mistake it as a link.
<img width="663" alt="screen shot 2017-01-12 at 1 34 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/21903871/720ba68c-d8cf-11e6-94e0-e3f66173096e.png">

**Comment by lakohl** [comment]
This design is changing. Will remove current cases in favor of assigning to employees.

**Comment by lakohl** [comment]
New design for the top of this page is as follows.  'X cases in queue, total of y cases completed today' is in dark grey and not a link.

<img width="800" alt="screen shot 2017-01-29 at 8 57 10 am" src="https://cloud.githubusercontent.com/assets/4975959/22424451/9fb15b7e-e6c4-11e6-8307-7ffda36bdecb.png">

**Comment by KHarshawat** [comment]
@lakohl questions/feedback about the design: 

- What do the checkboxes do? Are they interactive?
- How does the manager actually assign cases?
- I think the "ARC Dispatch WorkFlow" heading is redundant with the "Work Assignments for..." title. I would stick with the latter.
- We haven't really used cammel case for WorkFlow ever ... is this something we're looking at doing? Not sure how I feel about it but we should discuss in the next design sesh.

**Comment by lakohl** [comment]
@KHarshawat I appreciate the feedback.

During our last usability session we learned that the coaches would like to divide the work equally between their employees each day. At the start of the day employees need to be notified how many cases they are expected to complete on that day. After they are done with their individual queue of cases, employees go on to do other kinds of work. 

The boxes allow the coach/manager to select who is working today and assign work to that employee. The total work queue is then automatically divided between all the employees who are checked/working that day. 

Good points about the page and the table titles being similar/redundant. These could be re-thought. There is a second table lower on the page (see full page below). Thus, it seems like the page itself needs a title and that each table also needs a title. 

<img width="739" alt="screen shot 2017-01-30 at 12 09 30 pm" src="https://cloud.githubusercontent.com/assets/4975959/22433092/30b9c29e-e6e5-11e6-9aa9-ad23f048ea5a.png">


I'll switch WorkFlow to Workflow. that makes sense to me.

**Comment by shanear** [comment]
This is obsoleted by https://github.com/department-of-veterans-affairs/caseflow/issues/869

closing.
