### ISSUE TITLE
VACOLS Integrations | Schedule Period Inclusive Date Range

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6472]
When we hit VACOLS for hearings from 1/1 to 3/31, we only get the hearings from 1/1 to 3/30. We need to update the selector to pull all hearings.

**Comment by oscarAtNava** [comment]
This issue is not in the query. It turns out we have to store the hearing_date in UTC using the VacolsHelper utility class. I also had to fix the JSON Serializer to make sure the date was preserved when the date is converted to a string.
