### ISSUE TITLE
Build Schedule Homepage | Refresh Schedule Periods

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6479]
We don't refresh schedule periods when schedulePeriods is already set in props. We need to update the logic to refresh so that new schedule periods show up.

**Comment by MeredithStewart** [comment]
Noted in demo with Scott today 8/2/18. We even navigated away from the Build Schedule page and went back a few times and the file he had just uploaded (and associated data) didn't appear.
