### ISSUE TITLE
Design questions brought up by refactoring

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#6480]
1) Is the task list page a list of tasks or list of appeals.
   - i.e. are we grouping multiple tasks for a given appeal in one row, or do we show it in multiple rows.
1) Case details can have multiple tasks, we need a way to take action on all of them.

**Comment by mkhandekar** [comment]
Handing off to @sneha-pai + @allyceh who will talk with @mdbenjam to get an update on any new multiple admin work, then prioritize with guidance from @laurjpeterson ❤️(per conversation on Oct 10)

**Comment by carodew** [comment]
Does anyone remember what this is about, and if so, is it still current? 

If no one remembers I'm inclined to close this issue.

**Comment by laurjpeterson** [comment]
I think we can close it!
