### ISSUE TITLE
RO Algorithm output | CO hearing rooms assigned bug

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#6481]
In testing the RO algorithm with Scott in Demo today (8/2), the output showed two ROs were assigned video hearing days and assigned to hearing rooms 1 & 2, which should be reserved for the Central Office hearing rooms. 

![cohearingroomsassigned](https://user-images.githubusercontent.com/36775274/43607314-dfd050d6-966b-11e8-959e-9dc63c1572ff.png)

**Comment by tejans24** [comment]
I cannot replicate this. This might be a one off thing with some inconsistent data. Video hearing days WILL definitely start at 4.

**Comment by MeredithStewart** [comment]
So weird!

**Comment by MeredithStewart** [comment]
We can't replicate this. We've tested extensively and we don't think it's doing this.
