### ISSUE TITLE
Success Page | VACOLS failure message

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6485]
If the VACOLS upload fails, we should display a message asking the user to try again.

**Comment by Chingujo** [comment]
@sharonwarner 

The only question is where we send the user. The logical flow is that we send them one stop back. However, what are the risks that what they are trying to upload needs to be re-sorted if the VACOLS upload fails. If that's the case, we should send them back to the upload file page?  

For easy copying =D:

Title: 
- We could not complete your VACOLS upload

Body: 
- We encountered an error uploading to VACOLS. Please use the "Go back" link to try again. If the problem persists, you can check the status of our applications or submit a help request using the inks in the footer. 

Link: 
- < Go back

### Mock
![page expirednormal](https://user-images.githubusercontent.com/23316107/43726073-274b260e-996c-11e8-97e7-25cae6430c59.png)
