### ISSUE TITLE
Review Assignments | Specify algorithm error

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6486]
Right now, we only show a generic message when the algorithm fails (listed below). We just added some error handling to the backend to specify which RO has been either allocated too many days or has too many non-availability dates, so we could display more specific error messages on the frontend.

- Add message for which date doesn't have enough judges

Current error message: 
Title: 'The assignments algorithm was unable to run successfully.'
Message: 'Please confirm the information in the spreadsheet is valid and try again. If the issue persists, please contact the Help Desk.'

**Comment by tejans24** [comment]
**RO assignment errors:** 

1). When RO doesn't have enough available days to assign
``` 
fail NotEnoughAvailableDays, "#{ro_key} can only hold #{max_hearing_day_assignments} hearing days."
```
We can provide them the RO that didn't have enough available days for Hearing day assignments

**Judge assignment errors:**

1). When hearing days cannot be assigned judges
```
fail CannotAssignJudges
```
We can provide them the Hearing days and the dates that couldn't be assigned to.

**Comment by tejans24** [comment]
This needs @Chingujo 's input into what the UI error messages need to be.

**Comment by Chingujo** [comment]
@tejans24 

Please also make sure there is a < Go back link in the bottom left of the error message. I believe we have this pattern already in the app. 

## Allocated too many hearing days
- Title: The assignments algorithm was unable to run successfully

- Body: You have allocated too many hearing days to the [Regional office name]. Please check your spreed sheet and upload the file again using the "Go back" link below. 

## Too many non availability days 

- Title: The assignments algorithm was unable to run successfully

- Body: The [Regional office name] has too many non - availability days.  Please check your spreed sheet and upload the file again using the "Go back" link below.

**Comment by tejans24** [comment]
for: 
```
Body: You have allocated too many hearing days to the [Regional office name]. Please check your spreed sheet and upload the file again using the "Go back" link below.
```
@Chingujo do we want to let them know the max capacity of hearing days as well?

**Comment by tejans24** [comment]
updated the issue with @Chingujo 's in person input
