### ISSUE TITLE
Parse and return contesting claimant info and addresses, and return multiple REP rows if they exist

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6492]
- Parse appellant and contesting claimant information from the Rep table
 - Our code assumes a 1:1 relationship between BRIEFF and REP, whereas it's actually 1:many — fix that
- Make REP.REPNOTES available so we can use it if we decide to

See https://github.com/department-of-veterans-affairs/dsva-vacols/issues/26

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
