### ISSUE TITLE
Review Assignments | Sort algorithm output

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6499]
How should we sort the algorithm output? Currently we just display it in the order the algorithm sends it to us which, for the RO algorithm, groups by RO and then sorts by date, and for the judge algorithm, seems to be kind of random.

**Comment by Chingujo** [comment]
@sharonwarner  Thanks for catching this

The non - RO availability ordering sounds ace. 

For judges, if it is urgent we can sort by last name. If it isn't, we can ask tomorrow during our user interview to get the preference =D

**Comment by sharonwarner** [comment]
Not urgent! Just let us know when you decide!

**Comment by MeredithStewart** [comment]
@Chingujo and @sharonwarner I think this ticket can be closed.

**Comment by MeredithStewart** [comment]
In chronological order by date for both algorithm outputs would be great.
