### ISSUE TITLE
Convert certification & form 8 to use React

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#650]
Right now we are straddling two different javascript styles in Caseflow. We have committed to React, and should convert the Form 8 form.

**Comment by kierachell** [comment]
@nemodjuric and @mdbenjam and @sharonwarner !
There are some modals being developed right now and I don't want us to redo them when it can be done right from the start and not add to the backlog.
What's the plan for current sprint's modals?

**Comment by shanear** [comment]
@kierachell we have a modal in jQuery (non-react) too. We will use that for now. It won't require any waisted work.

**Comment by amprokop** [comment]
@shanear — can we hold on this task? we're talking to leadership about removing the form8 tomorrow and on tuesday, so we might never need to convert it

**Comment by shanear** [comment]
For sure. Lets wait on this until the Form 8 settles down.

**Comment by kierachell** [comment]
@amprokop  You know what to do
![shaqcat](https://user-images.githubusercontent.com/18075411/30251358-1f57709a-962c-11e7-818c-e99941fb3566.gif)

**Comment by amprokop** [comment]
This is complete, @kierachell!
