### ISSUE TITLE
View Hearings | Loading spinner

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6501]
<img width="1191" alt="screen shot 2018-11-02 at 11 51 19 am" src="https://user-images.githubusercontent.com/4306128/47925923-aa181b00-de95-11e8-95f7-afa34e2cc831.png">

The ui elements above should render in the ListScheduleContainer. A loading spinner should be displayed when sending the API request to the backend for hearing days. 

We can do this the same way we updated the AssignHearings page, but there is one difference. On this page, we want the initial page load to load hearings one month in the past to one year in the future.

**Comment by Chingujo** [comment]
Moving the in progress label as we are thinking on the loading spinner

**Comment by MeredithStewart** [comment]
Let's put this on hold, until we determine other UI aspects of this page. We think we will prefer "apply" becomes a button with a spinner.
