### ISSUE TITLE
Editing VBA issues | confirm issue remove modal

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6508]
## Story
For users coming from VBMS to edit an issue, when they click the "remove" link, they should be asked to confirm they definitely want to remove it with a description of what will happen to the EP.

## Acceptance criteria
- Within the editing flow, selecting the "Remove" link will produce a modal overlay.
- Within the modal, clicking "Cancel" will close the modal / reveal the list of issues page without doing anything else.
- Within the modal, clicking "Yes, remove issue" will close the modal / reveal the list of issues page and the issue they wanted to remove is gone.
- When the user has removed an issue and then clicked the "Save" button on the issues page, [@abbyraskinUSDS: what happens on the backend?]. 
 

## Copy
Modal title: Remove issue
Line 1: The contention you selected will be removed from the EP in VBMS. 
Line 2: Are you sure you want to remove this issue?
bottom: "Cancel" link and "Yes, remove issue" as button. 

## Mocks
<img width="517" alt="screen shot 2018-08-06 at 10 31 57 am" src="https://user-images.githubusercontent.com/11219417/43722740-fbea79d6-9963-11e8-8811-1dc5e692ff03.png">

## Related issue
Design issue: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/953

## How to Validate
Not sure how validation will be done since path to the edit flow starts at VBMS so we'll need to figure this out.

**Comment by shanear** [comment]
dup, closing
