### ISSUE TITLE
Review Assignments | Cancel Schedule Period 

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6522]
A user could, theoretically, create a schedule period, cancel out on the Review Assignments page, upload a different schedule period to VACOLS, then return to the cancelled schedule period's page, and accidentally upload more hearings. We need to prevent that from happening.

**Comment by MeredithStewart** [comment]
@sharonwarner I need some help understanding this one. Does finalized == true mean that we've read that the schedule period is already set in VACOLS so we prevent Caseflow from assigning again?

**Comment by oscarAtNava** [comment]
I also need more context on this one. Were the items reviewed confirmed? Only when clicking confirm should we set the finalized field to true. Otherwise we will never be able to load hearing days for the period represented by that SchedulePeriod. 

Perhaps I misunderstand the issue.

**Comment by sharonwarner** [comment]
Sorry, it's kind of hard to describe: 

Let's say a user creates a schedule period for 1/1/18-5/31/18, they see the algorithm output on the Review Assignments page (/build/upload/1), and they decide something is wrong. 

They click 'Go back', and create a new schedule period for 1/1/18-5/31/18, and on the Review Assignments page (/build/upload/2), they confirm the upload to VACOLS.

There's nothing preventing the user from manually navigating to `/build/upload/1` because that schedule period was never finalized. They could click confirm, and upload all of those hearings to VACOLS as well.

I don't think this situation is particularly likely, and I think it's fine if we decide not to fix this, but I think it's worth thinking about. 

To fix it, I think we'd have to make these updates:
- add a new column 'cancelled' that we set to true when users cancel schedule periods
- on the home page, we filter out cancelled schedule periods
- on the review assignments page, if the schedule period is cancelled, we should display the 'expired' message
- in the `can_be_finalized` method, we should confirm the schedule period wasn't canceled

**Comment by MeredithStewart** [comment]
I understand more now. I think if they click "go back" than that should cancel that upload and we shouldn't allow them to navigate back and upload that one.  I think it's worth fixing, but it's not high priority.

**Comment by oscarAtNava** [comment]
'There's nothing preventing the user from manually navigating to /build/upload/1'
How would they reach this url? Non-finalized schedule periods are not displayed in the UI. Would they type it in?

**Comment by sharonwarner** [comment]
Yes, they would have to type the url (I'm mostly picturing a scenario where they're trying to type a different url, but it auto-completes incorrectly.)
