### ISSUE TITLE
Change display date for rated_issues to profile_date

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6543]
## Story
The decision date that users see should match the forms, which should be the profile_date, it is currently the promulgation_date

## Technical notes
- In the client intake component for rated issues, change the display date from promulgation_date to profile_date.
- We should also double check that timeliness should be calculated based on promulgation_date (current calculation), and not profile_date

## Acceptance criteria
Date above rated issue groups should show profile_date

## Related issues
https://github.com/department-of-veterans-affairs/caseflow/issues/5172

## How to Validate
- Use any AMA flow, only one needs to be checked (they share the rated_issues code)
- veteran_file_number: 984562385
- Check that the dates ratings are grouped by match the profile_date.

Note
- Only ratings with a promulgation of a receipt date within a year + 1 week of the receipt date should show up. You do not need to validate this, but am putting it here so that you know all of these might not show up on the page.

Data:
Ratings 1:
@profile_date=Thu, 12 Jul 2018
@promulgation_date=Fri, 01 Dec 2017

Ratings 2:
@profile_date=Wed, 04 Apr 2018
@promulgation_date=Tue, 04 Apr 2017

Ratings 3:
@profile_date=Tue, 10 Oct 2017
@promulgation_date=Mon, 24 Oct 2016

**Comment by leikkisa** [comment]
After looking at the forms, I'm pretty sure we should also be using the profile_date to look up the timely ratings.

**Comment by leahbannon** [comment]
hey I think some of the ratings have been closed out - I need a few more to really validate this, right?

<img width="981" alt="screen shot 2018-08-29 at 12 49 50 pm" src="https://user-images.githubusercontent.com/4323988/44802573-1753bb00-ab8a-11e8-99b8-b4fe5a5c8f95.png">

**Comment by kahlouie** [comment]
@leahbannon I don't think you need more ratings, just need to know that it's using the profile date instead of the promulgation date. Do you have that in VBMS UAT?

**Comment by leikkisa** [comment]
I'm moving this to done because the Decision Date appearing matches a profile_date, and not any of the promulgation dates.
