### ISSUE TITLE
Using back and forward in browser while uploading to VACOLS

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6546]
Steps:
1). Upload a validated RO schedule
2). Confirm uploading to VACOLS
3). Click the back button before it finishes
4). Proceed forward again (browser control)

It will keep uploading many many records to VACOLS as long as that process is repeated.

**Comment by MeredithStewart** [comment]
Seems like something that should be stopped. Justin and Scott wouldn't purposely try to mess up the system, but seems like we shouldn't let possibly do either.

**Comment by oscarAtNava** [comment]
@sharonwarner Unless you already started working on this one, it seems related to the 6485 as it is all in the same components. You want me to take a look at this as well?
