### ISSUE TITLE
Form 8: Fields 5B/6B/7B date caching irregularities

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#656]
# Description:
As a User filling out an empty Form 8 the date in fields 5B/6B/7B exhibits irregular caching behavior when switching between Form 8 Preview (PDF rendering) and Editing (actual editable form).  This irregular behavior changes based on browser.

@aroltsch reports that `dev` environment does not save the date at all; so when she clicks _Go back to make edits_ the value resets to previous.

**Type of Bug:**
- [x] Functional
- [ ] Design
- [ ] Security
- [ ] Tech Improvement

**Environment:**
- [ ] Production
- [ ] UAT
- [x] Demo
- [x] Development

**Severity Level:**
- [ ]    5 - Data loss, data corruption or system unavailable
- [ ]    4 - Important functionality is unavailable with no workaround
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround
- [x]    2 - Secondary functionality is unavailable but has a reasonable workaround
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround

# Reproductive Steps
_Scenario 1:_**`demo`** and **`dev`** **_
1. Enter text for field 5A and a date with 01/01 for `month` and `day`.
1. Enter any value for `year` for 5B.
<img width="456" alt="screen shot 2017-01-10 at 09 04 21" src="https://cloud.githubusercontent.com/assets/18075411/21809006/cecea350-d713-11e6-9e4d-637da95d5198.png">
3. Then click *Preview Completed Form 8*, I see:
<img width="800" alt="screen shot 2017-01-10 at 09 05 08" src="https://cloud.githubusercontent.com/assets/18075411/21809021/e86027b2-d713-11e6-8739-4c7af37069c2.png">
4. Click  on the *Go back link.  

5. Make edits to the form.  The following behaviors happen:

**__Firefox_ in `demo` environment_**
<img width="456" alt="screen shot 2017-01-10 at 09 05 51" src="https://cloud.githubusercontent.com/assets/18075411/21809043/00f376da-d714-11e6-8a91-beb5391fbca0.png">

**_Chrome in 'demo' environment_**
<img width="497" alt="screen shot 2017-01-10 at 09 07 34" src="https://cloud.githubusercontent.com/assets/18075411/21809097/3cab1bc4-d714-11e6-8a2f-dbfce1ad9889.png">
6. The `year` value has gone down by 1.  This only happens when `month` and `day` are set to 01/01; and only on Chrome. 

# Relate Stories/Issues
**_Support Tickets/Features/Issues_**
Form 8: Fields 5b/6b/7b date validation - #643 
Form 8 Preview: Questions 5b, 6b, 7b: Automatically populating when no value in counterpart question A. - #609

**Comment by shanear** [comment]
postponing this because the form8 may be going away soon.

**Comment by amprokop** [comment]
Form 8 v1 is gone gone
