### ISSUE TITLE
Displaying Holidays in the Hearings Calendar

### ISSUE THREAD

**Issue by oscarAtNava** [department-of-veterans-affairs/caseflow#6561]
Today the VACOLS UI displays holidays in its Hearing Schedule list with the text 'HOLIDAY Do Not Sched' displayed across the name and folder_nr columns in their UI. Our Caseflow View Schedule list does not display holidays. Should we?

In the VACOLS DB holidays are identified by a special value in the folder_nr column: 1779233.

**Comment by MeredithStewart** [comment]
@oscarAtNava and @Chingujo I checked with Justin on this one last week and they would like to show if it's a holiday.   

@Chingujo - Do we want to create mocks for this now? 

An additional user stories: They'd like the ability to manually add to a specific date for not scheduling hearings.  They'd also like the ability to manually override and put in a hearing on a holiday (if it's an AOD and Veteran is dying situation).

**Comment by sharonwarner** [comment]
Closed because we aren't pulling days from VACOLS anymore.
