### ISSUE TITLE
Caseflow Hearing Schedule Home Page

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6562]
As a user, I want to be directed to the hearing schedule as a home page as the build schedule page is more of an admin function. 

### Acceptance Criteria
- [ ] Verify that there is a title called "Welcome to Hearing Schedule" 
- [ ] Verify that there is a "Build schedule" button on the right of the title that is only avaliable to Scott and Justin
- [ ] Verify that there is the following body copy: 
- The below table shows the hearings scheduled for the dates listed in the below date fields. To change the view, please  select a new date range using the From and To fields. To add slots or assign judges, please use the “Build Schedule”. 
- [ ] Verify that there is a hz line under the body
- [ ] Verify that there is a download schedule dropdown with a date range feature as in #5953 

### Mocks
![list view judge filled download not expanded](https://user-images.githubusercontent.com/23316107/43909149-a780bafc-9bc7-11e8-95e9-f35936b63732.png)

**Comment by Chingujo** [comment]
@MeredithStewart @sharonwarner 

I did not see a ticket for the home page, so making one as this changes due to the download ticket on #5953

**Comment by MeredithStewart** [comment]
@Chingujo -- Update to remove copy under header.
