### ISSUE TITLE
Build out generic queues for admin teams

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#6573]
# Overview
In discussions over the past few weeks we've determined that at our current rate of progress we're not going to be able to rollout Queue to all admin teams in the timeframe required. However, by thinking of queues in the most generic form, we think we can get an MVP into the hands of users, giving us more time to come back and make Queue work for users' specific needs.

**What is a generic queue?**
Generic functionality that is made possible by our task tree data model that tracks responsibility for tasks, so that we can roll queues out to multiple teams at the board quickly and simultaneously

Resource: [presentation](https://docs.google.com/presentation/d/1__UukJy9ts2qbvHVhbLd3lnInaiZ3UqAqAYdLmC7vDM/edit#slide=id.g3fe0b62e2f_0_222) to BVA leadership about Caseflow tasks 10/17/2018

**What functionality is needed to have a generic queue?**
- Task tree data model
- Viewing tasks in an organization's queue (e.g. quality review)
   - Includes tabs available: New, On Hold, Completed
- Viewing tasks in a user's queue (e.g. quality review user)
   - Includes tabs available: New, On Hold, Completed
- Creating a task on the root task
- Creating child tasks
- Task actions
   - Assign to person
   - Assign to team
   - Mark complete
   - (Place on hold?)
   - (Cancel?)
- Adding notes/instructions to tasks
- Mapping people to organizations

**What functionality is made possible by a generic queue + task tree model?**
- Case timeline - https://github.com/department-of-veterans-affairs/caseflow/issues/5592

# Initiatives
Generic queues is a big project with quite a few initiatives tracked in separate epics/issues. We've assigned point people for each:
- VSOs - https://github.com/department-of-veterans-affairs/caseflow/issues/5581 - @mdbenjam 
- Creating generic task on root (for mail, lit support) - https://github.com/department-of-veterans-affairs/caseflow/issues/7404 - @lowellrex 
- Case timeline - https://github.com/department-of-veterans-affairs/caseflow/issues/5592 - @lowellrex 
- Organization management - https://github.com/department-of-veterans-affairs/caseflow/issues/7427, https://github.com/department-of-veterans-affairs/caseflow/issues/7455 - @mdbenjam 
- Refactoring co-located queue (eventually) to generic queue - TBD

# Rollout plan
1. VSOs
2. Quality review, AOD, FOIA - #7355 begins this work
3. Mail, Lit support (requires creating task on root task), Translation
4. Hearing branch, Transcription (in collab with Hearing Schedule team)

# Resources
- Tech spec (below)
- Planning [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1539709516244/6f439b9eb42f9b962443641a96ecde413e4c1ff9) for generic queue work

---
# Tech Spec

# Organization
We propose adding a new model called an `organization` into Queue. Organizations, like users, can have tasks assigned to them. Like users, they will have an organization queue which displays all the tasks assigned to the organization. By building out this structure we hope that adding a new admin team to Queue will be as simple as adding a few rows in our database.

# Users in an organization
The first question we will answer is how do we determine which users are within an organization. In the future when Caseflow maintains an org structure we can have a foreign key in the user table that maintains which organization the user belongs to. However, until that time we can continue to rely on VACOLS. It looks like admin teams are specified through the `stitle` and `sdept` columns on the Staff table. We can include in the organization table these two columns as foreign keys. To determine the users within the organization we can run a query on the Staff table, specify the `stitle` and `sdept` and return the user's corresponding css_ids. Note that currently the Staff table doesn't seem to have css_ids for these users. We can either ask Jed to add them, since other members of the staff table do have their css_ids in the table, or we can append "BVA" to the stafkey which usually gives us the correct css_id. The first option is obviously preferable.

# Organization view
We have already built the organization table and setup tasks with a polymorphic association to users and organizations. This means we organizations can have assigned tasks. We now need a view that can show members of the organization which tasks are assigned to it.

The organization table has a `url` column which specifies where the organization view lives. i.e. `organization/mail` or `organization/american-legion` or in general `organization/:url`. When a user access that page they will need to be authenticated as a member of the organization. We can get the list of users in the organization as described in the previous section and ensure their css_id is in the list. If so then we can show them a standard queue page, where the tasks in the queue are not assigned to them, but to the organization.

# Case details page for organization member
When a member of an organization views the case details page of an appeal with a task assigned to the organization, they will see a dropdown with two options: `Complete` and `Assign to team member`. Clicking `complete` will complete the task, and if this was the last child task of the parent, move the parent task from on-hold to in-progress. Clicking `assign to team member` will take the user to a checkout flow with a dropdown populated with all the organization users css_ids. When a user is chosen, a new child task is created and assigned to that member of the organization.

# Team as task barrier
In addition to the `Mark task complete` and `Assign to team member` actions, there will be  an `Assign to team` action. The `Assign to team` action is how tasks are moved from team to team. Tasks assigned to an individual only ever have parent and child tasks that are assigned to teams. Teams *may* have parent/child tasks that are assigned to other teams in addition to the more common case of parent/child tasks being assigned to individual people. For example, when an attorney discovers a document that requires translation it might go through the following flow:
```
            +---------------------------+
            |                           |
Person      | Case assigned to attorney |
            |                           |
            +---------------------------+
                        |
                        | Attorney requests
                        | admin action
                        v
                +---------------------------------+
                |                                 |
Team            | Task assigned to colocated team |
                |                                 |
                +---------------------------------+
                                |
                                | Automatic round robin
                                | assignment to team member
                                v
                        +----------------------------------------+
                        |                                        |
Person                  | Task assigned to colocated team member |
                        |                                        |
                        +----------------------------------------+
                                        |
                                        | Documents need to be
                                        | translated
                                        v
                                +-----------------------------------+
                                |                                   |
Team                            | Task assigned to translation team |
                                |                                   |
                                +-----------------------------------+
                                                |
                                                | Assignment through organization's
                                                | admin queue view
                                                v
                                        +------------------------------------------+
                                        |                                          |
Person                                  | Task assigned to translation team member |
                                        |                                          |
                                        +------------------------------------------+
```

This "barrier" between individuals allows teams autonomy over how they allocate work, and provides insurance for when an individual person is not able to complete a task (on leave, retirement, etc.). In that case, the original individual's task can be closed after opening another subtask to the team-level task. Using the same example as above we can visualize this scenario in terms of individual and team tasks:
```
        +-----------------------------------------------------------------------+
        |                                                                       |
Team    |                   Task assigned to translation Team                   |
        |                                                                       |
        +-----------------------------------------------------------------------+
                            |   ^                           |
Original assignment through |   | Team member               | Task re-assigned to different
org's admin queue view      |   | retires                   | team member
                            v   |                           v
                    +---------------+               +---------------+
                    |               |               |               |
Person              | Team member 1 |               | Team member 2 |
                    |               |               |               |
                    +---------------+               +---------------+
```

# Task states
Implicit in this abstract heirarchy of tasks is a sense of a task being in some sort of state. The primary state bieng whether a task requires further action from the person to whom it is assigned or whether it does not. If a task requires no further action from the current assignee, then the task is `complete`. If a task requires further action from current assignee and the assignee can take that action now, then the task is `in-progress`. If the assignee has additional work to do on the task but cannot complete that until some other task is complete, then that task is `on-hold`. The `on-hold` status can be a status on the task itself or it could be determined programatically by checking to see if any of a given task's immediate subtasks are not `complete`.

# Future task types
During the initial implementation of generic organizational queues we will only have three actions that can be taken on any task--`Mark task complete`, `Assign to team member`, and `Assign to team`--but by examining how these three actions operate we can create a general framework for task actions.

### Mark task complete
* Who can do this (actor): Anyone. Any team or individual can mark a task assigned to them as complete.
* What state is the task in after this action (state after): `complete`
* Who is assigned child tasks that are created (child actor): No child tasks are created when this action is taken.
* What action-specific application logic happens when this action occurs (application logic/type): None (Though there will have to be some general application logic that marks team tasks complete when the last incomplete subtask assigned to an individual is marked complete)

### Assign to team member
* Actor: Anyone (team or individual)
* State after: `on-hold` if creating a subtask of a team task, `complete` if reassigning already assigned task to another member of the same team.
* Child actor: Individual
* Application logic/type: None

### Assign to team
* Actor: Anyone (team or individual, though the more common case will be an individual taking this action)
* State after: `on-hold`
* Child actor: Team
* Application logic/type: None

I am not advocating that we change the way existing task actions behave, however considering existing tasks within the framework established above allows us to envision how future task actions might be implemented more quickly using this framework.

### Decision ready for review
* Actor: Attorney (individual)
* State after: `complete`
* Child actor: No subtask created.
* Application logic/type: Disposition selection, add document ID, and notes. (Completing this task triggers the parent task assigned to the judge to move from `on-hold` to `in-progress`)

We can describe action from the translation example above in this manner as well.

### Request document translation
* Actor: Colocated admin (individual or team)
* State after: `on-hold`
* Child actor: Translation (team)
* Application logic: None. This simply reassigns responsibility.

Conceptualizing task actions like this allows us to quickly add new actions by adding a row to a database table (without even having to wait for a deployment cycle!). Additionally, we can use this table to populate the "Actions" dropdown by selecting all of the rows where the current user's role matches the actor allowed to take that action.

# Examples
Here are two examples to illustrate how we can use this model to generalize assigning tasks to the colocated and mail teams.

## Colocated team
An attorney assigns a new task, POA Clarification, to the colocated organization. The users of the organization are queried from the VACOLS::Staff table for where the `stitle` is either `A1` or `A2`, because the colocated row in the organization table has an array of `[A1, A2]` in the `stitle` column and a `*` wildcard in the sdept column. Because the task is of type round-robin, we automatically create a child task and assign it to the next co-located user.

The colocated user determines that they are not suitable for this task, and decides to assign it to another user on the team. They go to the case details screen, select "Assign to a different user" from the drop down. On the next screen they see a list of colocated users populated from the query to the VACOLS::Staff table. The select which user to assign the task to. Their task gets completed and a new task is created assigned to this new user. The task's parent is the same parent as the task that was just completed.

This new colocated user completes the task, and goes into the case details page and selects "Complete task" from the dropdown. This completes both the task assigned to the user, as well as the task assigned to the organization. Since the task assigned to the attorney no longer has any child tasks, it is moved from on-hold to in-progress.

**Comment by laurjpeterson** [comment]
## re: Organization view
- we discussed the possibility of this view being the judge assignment view, *if it makes sense*
- this leaves the opportunity open to bulk assign cases to members within the organization
- members within the organization would comprise the current attorney caseload list

## re: Case details page for organization member
- Questions regarding showing Assign to team member and Assign to team. I anticipate that some users will not be allowed to assign to particular team members. i.e. if we go this route, only supervisors could assign tasks to other team members. Will we be able to restrict assignment to team member?

## Other notes
- We'll want to keep track of the timestamps where tasks were assigned to teams, team members, and marked complete. This will help us populate a Case timeline view with tasks, and tell the story of the appeal as it goes from task to task.

**Comment by lowellrex** [comment]
We've decided to delay work on a generic task action framework indefinitely. The following assumptions lead us to believe that a generic task action framework (where we store the definitions for those task actions and permissions for those actions in the database) is less favorable than simply defining all of the task actions we will ever need in code without a database component:
* The limited set of default task actions (`Mark as complete`, `Assign to team`, `Assign to individual`) that will be available for all tasks in the organizational task queues will be sufficient for most of the organizations we will roll queue out to
* Adding/hiding/modifying task actions in code will not be substantially slower than adding rows with the appropriate configuration in the database
* We will not be able to extract enough meaningful abstractions common to multiple different task actions to make the value of those abstractions worth the cost of the abstraction inherent in the task action framework itself
* We do not currently store any configuration data in the database, so this would be a departure from how we have currently arranged Caseflow which may cause confusion when trying to reason about the application in the future

**Comment by laurjpeterson** [comment]
@mdbenjam @lowellrex @sneha-pai and @laurjpeterson met on 10/16 to discuss path forward with generic queues. 

Notes from the discussion captured in this [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1539709516244/6f439b9eb42f9b962443641a96ecde413e4c1ff9). 

To do's discussed, that span generic queue initiatives discussed in the top comment:
1. Create task on root tasks (first use case = mail, second use case = lit support post-decisional motions) 
    - eng: backend work to create a task on a root task
    - design: clean up mail sketches, confirm mechanism to do this (from actions dropdown in case details)

2. Clean up organizational membership - Mark
    - eng: move to github individual/team mapping (interim)
    - proposal to build a UI, CSEM role
    - product: figure out who is in which organization

3. Tabs for generic queues
    - eng: rollout completed tabs for VSOs
    - product: communicate complete tasks

4. Link structure for users with multiple organizations
   - view org queue, view individual queue
   - get back to organizational queue

5. Task types
    - eng: change code to reflect the task type vs. task actions
    - product: list task types

6. Case timeline - tracked elsewhere: https://github.com/department-of-veterans-affairs/caseflow/issues/5592
   - design: finish the design based on minimum data
   - eng: TBD
