### ISSUE TITLE
Hearing data not showing in Case details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6580]
Judge Kroes identified that hearing cases are not showing up in Case details.

![image](https://user-images.githubusercontent.com/27704093/43927355-406157ee-9bfb-11e8-8488-92798db9de3d.png)

![image](https://user-images.githubusercontent.com/27704093/43927348-3a7758d8-9bfb-11e8-9af4-826ae9f6dedb.png)

**Comment by dannysellers** [comment]
Well, the short answer is that `appeal.hearings` returns no hearings for this appeal. Investigating further

**Comment by laurjpeterson** [comment]
Closing, because the hearing was actually associated with the Original appeal, when Nate was assigned the Post Remand.
