### ISSUE TITLE
Research: How accurate is the veteran address in different VA systems?

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6584]
**Question**: In related to fetching the closest hearing location(including alternate hearing places) to the veteran, how accurate are the addresses of the veteran in **BGS**(focus), VBMS and VACOLS?

**Goal** is to find the best source of information about the veteran to accurately fetch the closest location (driving distance or by zip code) to the veteran.

**Comment by MeredithStewart** [comment]
Related Mural Here, reflecting information about Vets360. https://app.mural.co/t/workqueue2001/m/workqueue2001/1528997950795/b75955a5390352019a9bc0e35a154024b24c558d

**Comment by MeredithStewart** [comment]
From our RO Research (July 2018): 
* Prior to scheduling a Veteran for a hearing, RO hearing coordinators are checking VBMS to see if there is a discrepancy between the VACOLS address and if there are documents indicating a change of address in VBMS. Houston called this step "Research." 
* If a Veteran can't be reached - returned mail - then the RO Hearing Coordinator would try calling the Veteran or checking a medical VA system to see if they could find a more recent address.

**Comment by MeredithStewart** [comment]
From LP: Queue team is pulling in Veteran addresses from BGS. Because of the Vet360 work, Veteran address updates in other systems will flow through to BGS. 

Meredith: 
This means that BGS would likely be more up-to-date than VACOLS, because a Veteran would have updated their address more recently in another location than through the Board in VACOLS. 

Question: Will the Board have a way to update Veteran address, should it receive it, so that they can update BGS?

**Comment by MeredithStewart** [comment]
**Meredith's current thinking**
* BGS is better than VACOLS, but Queue is only doing AMA appellants before February. 
* Checking VBMS is a manual process that is currently done with RO hearing coordinators.  
* If necessary, the matching of Veteran home address to hearing location could continue to have a manual VBMS check to see if there was an update. Not ideal.

**Comment by MeredithStewart** [comment]
Update based on team convo 8/13: 
* Perhaps Tango should consider doing the work to get BGS addresses for legacy appellants before AMA implementation.
