### ISSUE TITLE
Research: What's the best tool that can be used to fetch the closest hearing location to a veteran?

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6586]
**Question**
What's the best tool for fetching the closest hearing location to the Veteran?

What do we have?
* List of all hearing locations (including alternate hearing locations)
* Veteran address

Possible criteria:
* Driving distance
* Zip code search
* How easy is it to integration into our stack/application?
* Usage limit constraints
* Cost

Options:
* Google maps api
* open street maps api?
* Mapbox
...etc

We want to find the best and most integratabtle tool for finding this information.

**Comment by tejans24** [comment]
Mapbox examples: https://www.mapbox.com/help/building-a-store-locator/#make-the-map-interactive
Google maps store locator: https://developers.google.com/maps/solutions/store-locator/clothing-store-locator

**Comment by MeredithStewart** [comment]
Explore VA's ERRA tool - can we leverage this internal VA tool that matches a Veteran's address to RO, and VHA locations?

**Comment by MeredithStewart** [comment]
The Vets.gov Facility locator has just released an API that we should take a look at: https://www.vets.gov/facilities/. The UI is available here: https://www.vets.gov/facilities/
