### ISSUE TITLE
Research: Would the Veteran addresses we send be considered PII?

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6587]
**Questions**
* Is veteran address alone considered PII?
* Can we send this information to 3rd party services to get driving distance or distance by miles/km? (Example: Google maps API, Mapbox etc)

**Comment by marvokdolor-gov** [comment]
**Answers**
- Yes a Veteran's address alone is considered PII.
- It would be advisable to use a Ruby Gem that performs this function i.e. calculating driving distance or distance by miles/km. This is preferred to sending this information to 3rd party services like Google or Mapbox.

**Comment by MeredithStewart** [comment]
@marvokdolor-gov -- Is the source of "Veteran's address alone" for PII, was that a determination that was made by a Privacy Lawyer for Vets.gov purposes? Or is the source somewhere else?

**Comment by marvokdolor-gov** [comment]
Sorry about not providing a source: https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf
Executive Summary includes "Examples of PII include, but are not limited to:...Address information, such as street address or email address"
