### ISSUE TITLE
Research: Is it ok to make API calls to 3rd party services from prod or VA network?

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6588]
**Question**
Can we make API calls to 3rd party services such as Google maps, Mapbox etc from our production servers? If not, what does it take to make it happen?

**Comment by oscarAtNava** [comment]
We would have to submit a formal request to the VA network admin folks. We should plan on the request taking about a month to complete. The request to interact with GitHub took a couple of months to get approved and implemented, as an example.
