### ISSUE TITLE
"System Admin" should be able to change roles

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#660]
We need a way for people with "System Admin" see what it's like to have different sets of roles.

- If the user has "System Admin" they should see a "Change Functions" link in the menu bar.
- If that link is clicked it should show a screen with a list all possible functions that caseflow looks for (we will have to create this list).
- Each function will say whether the User currently has that function enabled or not, and a button to toggle that function on or off.
- Store the set of functions currently set for the user in the session.
- Default admin_roles to enable all available roles.

This will make UAT testing far easier.

**Comment by kierachell** [comment]
It works!
<img width="888" alt="screen shot 2017-01-13 at 10 51 24" src="https://cloud.githubusercontent.com/assets/18075411/21936189/47a47036-d97e-11e6-93a8-09fe44b2b6f5.png">
<img width="962" alt="screen shot 2017-01-13 at 10 51 53" src="https://cloud.githubusercontent.com/assets/18075411/21936202/51a884fa-d97e-11e6-911d-c3328ea57655.png">
