### ISSUE TITLE
Handle when country is not set for veteran

### ISSUE THREAD

**Issue by kahlouie** [department-of-veterans-affairs/caseflow#6600]
Apparently sometimes BGS doesn't have enough information about the veteran, including country. We should handle that error earlier than where it's doing country validation for state and or postal code.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2243/events/112633/

**Comment by kahlouie** [comment]
There should be an existing error message for missing veteran information. Use that.

**Comment by leikkisa** [comment]
@leahbannon 
For validation, I believe this test file number should work: 564930680
Expected result - an error message saying that the user needs to fill in stuff (one of the fields it should say we need to fill in is country)

**Comment by shanear** [comment]
![screen shot 2018-09-24 at 2 03 47 pm](https://user-images.githubusercontent.com/1596259/45969765-afff1e80-c002-11e8-9920-bd50b8a9e3f7.png)

lookin' good.
