### ISSUE TITLE
RAMP Intake | Automatically rollback RAMP election when EP is canceled

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6615]
In order to make an entire class of wild RAMPs be a little easier to deal with, and test a feature that will be used in the end state, we will be rolling back RAMP elections whenever the corresponding EP is canceled.

## Acceptance Criteria
- When the EP status of a RAMP election is being synced, and the status is updated to canceled from any other status, then the corresponding election should be rolled back.
- The description for the rollback should be "Automatic roll back due to EP [682/683] cancelation"

## Technical notes
There is a class we've been using for manual rollbacks of RAMP elections, `RampElectionRollback` that should be used for rolling back the RAMP election.

## Notes
- For now, this will only occur for RAMP elections. We will assess whether we need to do it for RAMP refillings too soon.
- The end state story for this same functionality is https://github.com/department-of-veterans-affairs/caseflow/issues/6097

**Comment by kahlouie** [comment]
Add a feature toggle to turn it on and/or off for testing.

**Comment by kahlouie** [comment]
Shane can help pair on this.

**Comment by kahlouie** [comment]
To test this, you'll need to run `FeatureToggle.enable!(:automatic_ramp_rollback)` in the environment's rails console. or you'll need to make a pr to add it into the environment in appeal-deployment repo.

**Comment by kahlouie** [comment]
Jennifer Williams from AMO wants to see it herself.

**Comment by shanear** [comment]
This was validated by Erik Tonne and me in prod. Turning the feature on in prod today
