### ISSUE TITLE
Limit case search results for VSO users

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#6621]
Currently, all caseflow users who have access to case search can see every case that matches the results of their search. With the introduction of VSO users we will want to prevent those users from viewing cases for Veterans the user's VSO does not represent.

**Comment by mdbenjam** [comment]
I think we should expand the scope of this ticket a little. It should be that before running a search we need to check if the user, board of VSO has access to the case. If the board user doesn't have high enough sensitivity, we shouldn't show it to them either. And the check here is the same. Just need to call `can_access?` for the file number.

**Comment by laurjpeterson** [comment]
@lowellrex it looks like mark wrote his ideas up in this ticket - should they be consolidated? https://github.com/department-of-veterans-affairs/caseflow/issues/6391

**Comment by lowellrex** [comment]
@laurjpeterson I think it makes sense to consolidate them. This ticket is just part one of that other two part ticket.

**Comment by laurjpeterson** [comment]
closing in favor of #6391
