### ISSUE TITLE
Assign task to VSO during intake of RAMP appeals when Veteran is represented by VSO

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#6623]
In order for VSOs to see RAMP appeals for Veterans they represent in caseflow, we need to create tasks associated with the appeal and assigned to the VSO that represents the Veteran. We should do this during the intake step for all new appeals (RAMP and later AMA), as well as backfilling tasks for BEAAM cases.

These tasks are only placeholders and do not imply that the VSOs are required to take any action on the appeal. This is simply a way to provide VSOs with a view of the RAMP appeals they represent that leverages existing frameworks for convenience's sake. A later ticket will be written to create an IHP task assigned to a VSO when we intake a direct appeal case which will represent a real task with some required action to be taken by the VSO.

## Acceptance criteria
* Create tasks assigned to VSOs during intake for all appeals where Veteran is represented by VSO
* Create tasks for appeals already in caseflow where VSO represents Veteran

**Comment by laurjpeterson** [comment]
We've completed this! Closing.
