### ISSUE TITLE
Collect queue user feedback

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6666]
# Goals
- Understand how our users [attorneys and judges] use Caseflow among their other tools (VBMS and VACOLS) to:
   - track against adoption goals
   - uncover additional user needs
- Seek user feedback more frequently than we do now, and enable fast follows after releases

# Lightweight user research sessions

- Every week, the team observes at least 1 attorney and at least 1 judge using Caseflow for 15-30 minutes.
   - We could include attorneys who have worked BEAAM cases as well.
- After each session, block off 15-30 minutes to add insights to one single place - either mural or github issue - to document feedback in the moment. 
- We schedule these sessions for the same time, same day each week. (We could ask Kate to help us with scheduling these)
- We rotate which two team members should attend these sessions. One team member takes notes. (We could potentially also ask Kate to help us with this rotating schedule). 
- Our main activity should be to observe them using Caseflow to complete tasks, so we can see how they use their various tools.
- We ask everyone 3-5 standard questions we want to ask to spark conversation and gather insights around our product goals. For example:
   1. Tell us about the last time you had to view an appeal in VACOLS. Why was that?
   2. Have you experienced a time where you were looking for information in Caseflow but could not find it? If so, what were you looking for? Where did you expect it to be?
   3. How is Caseflow currently fitting into your workflow?
   4. When you think about processing appeals under AMA, is there anything you think you need to feel more prepared?

### Pros
- All team members (if they would like to) can get exposure to our users.
- Standard schedule, easy to remember, and easy to block off time.

### Risks
- We do have BVA Dispatch usability testing and Co-located/admin action pilot coming up that will compete for time. 

# Success Metrics

**Phase 1: Attorney/Judge loop**

Goal | Metric
---|---
Attorneys have the information they need to prioritize tasks in their queue table; feature parity with Reader Welcome Gate| 100% pilot users who report not needing additional information
Attorneys use Queue, not VACOLS, for appeals data| Judge reported use of VACOLS/ VBMS
Attorneys can transfer tasks to Judges in Queue| 100% of queue pilot attorneys use queue for check out
Attorneys are satisfied with Queue for check out | 100% queue pilot users report they prefer Queue to DAS/Attorney check out
Assigning cases to judges in Queue is simple| reduction in clicks for attorney checkout flow <br> 100% of attorneys report assigning cases to judges in Queue is simpler than DAS/Attorney check out
Reduced time to check out |	time elapsed during check out flow in clicks (baseline [here](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/640))

---

# Previously considered

## Survey

- Use same questions as above, plus some more statement type questions. For example:
   - I am able to find the information I need about a Veteran in Caseflow, and I do not have to use VACOLS. 
      - Strongly disagree, disagree, neutral, agree, strongly agree, don't know
   - Assigning cases to judges/attorneys in Caseflow is harder than it is in VACOLS/DAS. 
      - Strongly disagree, disagree, neutral, agree, strongly agree, don't know

## Assumptions
- Our users are more likely to respond to a shorter survey with fewer long answer questions, because of their busy schedules
- The best way to gather user feedback is through conversations, and we will not get 100% participation in this survey. However, we think that sending a survey will surface actionable feedback and spark additional research questions.

### Pros
- Lightweight, especially with our schedules and deadlines
- Reader set this precedent, we know that some attorneys and judges will respond
- Helps when presenting to stakeholders

### Risks
- Surveys aren't the best way to gather user feedback. They can feel good, by quantifying data quickly, but unless the survey is extremely carefully created, that data is often biased.
- Response rate, especially with long answer questions.

**Comment by mkhandekar** [comment]
I love and support option 1!

**Comment by mkhandekar** [comment]
Additional options for questions:

- Was there a time this week where you thought “ugh, this is more trouble than it’s worth” or were just not able to complete your task in Caseflow? 
  - _looking for recent examples where Caseflow is lacking and can improve_
- Was there a time this week where you thought “wow, that was a lot faster/more efficient than before” or something that worked really well? 
  - _looking for recent examples where Caseflow is excelling_

**Comment by laurjpeterson** [comment]
discussion notes 8/20:
- Pull previously submitted feedback by users prior to sessions
- Perhaps ask users to figure out which have feedback for us, rather than "cold-calling"
- What about emailing users these questions?

**Comment by mkhandekar** [comment]
Snowball recruitment method: Ask each interviewee, if there's someone they recommend someone we should talk to:
- someone they know for whom Caseflow is really not working, and are unhappy with it
- someone they know who has a lot of opinions / thoughts / ideas about what Caseflow could be

**Comment by laurjpeterson** [comment]
Discussion with @KCollinsBrown - 

- schedule sessions on Wednesdays at 1:30pm for 30 minutes
- schedule sessions for Wednesday 8/22, 8/29, 9/5, 9/12
- one judge, and one attorney per

- attorneys and judges (as of may 16, 2018) are listed in this excel file. 
[attorneys_judges_chiefs_may.16.2018.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2307575/attorneys_judges_chiefs_may.16.2018.xlsx)

**Comment by KCollinsBrown** [comment]
@laurjpeterson just emailed the above users.  Will track here who is attending and dates:

Name | Date Attending
---| ---

**Comment by laurjpeterson** [comment]
## Proposal for these user feedback sessions

- **Begin** with introductions, and by thanking the user for sitting down with us, and explain that we're hoping to observe them use Caseflow and ask a few questions about how they use it to do their work.
- **Observe:** Ask the user to show how they've been using queue that day
- **Ask:** The below questions

Suggested priority order for questions:

1. Tell us about the last time you had to view an appeal in VACOLS. Why was that?
2. Was there a time this week where you thought “ugh, this is more trouble than it’s worth” or were just not able to complete your task in Caseflow?
  - _looking for recent examples where Caseflow is lacking and can improve_
3. Have you experienced a time where you were looking for information in Caseflow but could not find it? If so, what were you looking for? Where did you expect it to be?
   - _skip if above question answers this_
4. Was there a time this week where you thought “wow, that was a lot faster/more efficient than before” or something that worked really well?
   - looking for recent examples where Caseflow is excelling
5. (only ask if time) When you think about processing appeals under AMA, is there anything you think you need to feel more prepared?

**Comment by sneha-pai** [comment]
_--- Proposed edits by Sneha below-------_
## Proposal for these user feedback sessions

- **Begin** with introductions, and by thanking the user for sitting down with us, and explain that we're hoping to observe them use Caseflow and ask a few questions.

- **Mention** that nothing they say will offend us. We want them to be as open as possible with their feedback, and that their feedback is essential in helping improve the product.
- **Request** that as we continue to ask questions, that they talk out loud, and tell us what they're seeing or not seeing, throughout the interview.
- **Ask** them the questions below

Suggested priority order for questions:

1. When was the last time you had to view an appeal in VACOLS. What was the reason? What did you do with that appeal?

2. Was there a time this past week where you thought “ugh, this is more trouble than it’s worth” or were just not able to do what you needed? Can you show us an example of that with a current appeal (only if possible)?

3. Have you experienced a time in the past week when you were looking for certain information in Caseflow but could not find it? Can you show us an example of that with a current appeal (only if possible)?
               - What were you looking for? 
               - Where did you expect it to be?

4. Was there a time this past week where you thought “wow, that was a lot faster/more efficient than before” or something that worked really well?
   _(Notes to moderator: you're looking for recent examples where Caseflow is working as the user intended to perform their tasks)_

5. _(only ask if time permits)_ When you think about processing appeals under AMA, is there anything you think you need to feel more prepared?

@allyceh @mkhandekar please also add your notes/comment to this.

**Comment by mkhandekar** [comment]
I like these questions and would appreciate seeing an example of what they are talking about, but let's be conscious of how much time each example / show&tell is taking, and prevent going down rabbit holes. If a workflow seems to be a particularly hairy one, let's pause and ask to set up a follow up conversation for them to take us through it, so that we can get through all the questions.

**Comment by mkhandekar** [comment]
We did 2 sessions yesterday. 
- [Raw notes in workflowy](https://workflowy.com/s/WsC.BxBGVcpPY0) (ask one of the designers to send you a link!)
- [Light analysis (so far) of observations in mural ](https://app.mural.co/t/workqueue2001/m/workqueue2001/1534886274809/89a0709cd78e64cd2b3b005e4afc858e26c1996b)

**Comment by laurjpeterson** [comment]
Interviewed Judge Jonathan Kramer - notes in workflowy and light analysis in Mural (see links above)

**Comment by laurjpeterson** [comment]
Updated attorney Allen Kerpan's notes in [workflowy](https://workflowy.com/s/WsC.BxBGVcpPY0)
