### ISSUE TITLE
Caseworker Success Page Button/Link Placement/Alignment

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#667]
**Description:**
Currently, if you go through the flow to establish a claim as a caseworker, the success page's "View History" and "Establish a Claim" button/links are misaligned to each other. Also the "Establish Next Claim" button also looks a bit too far to the left of the page. 

**Steps to Recreate**

1. Log into Dispatch under the function of a Caseworker
2. Select the option to "Establish New Claim"
3. Go through the flow to establish a new claim
4. On the success page verify the image, below matches.

**Expected Results:** Please see Lara's attached image below this post
**Environment Found:** Demo
**Browser Found:** Chrome

**Screenshots:**

<img width="483" alt="screen shot 2017-01-11 at 10 15 46" src="https://cloud.githubusercontent.com/assets/23038505/21857363/27e3bb62-d7f3-11e6-8da6-c727c0fcc508.png">
<img width="1129" alt="screen shot 2017-01-11 at 11 34 45 am" src="https://cloud.githubusercontent.com/assets/23038505/21857395/4a5be70a-d7f3-11e6-98c1-e8f1c3379ba6.png">

**Related Issues/Stories:**

**Reported By:** Alexis Stewart

**Comment by lakohl** [comment]
@astewarttistatech see screenshot:
<img width="494" alt="screen shot 2017-01-11 at 2 35 04 pm" src="https://cloud.githubusercontent.com/assets/4975959/21863375/368b6832-d80b-11e6-9282-644606a62f7c.png">

**Comment by kierachell** [comment]
<img width="1270" alt="screen shot 2017-02-08 at 20 57 56" src="https://cloud.githubusercontent.com/assets/18075411/22766066/754e545c-ee41-11e6-8194-385018dc59ae.png">
<img width="1141" alt="screen shot 2017-02-08 at 21 00 26" src="https://cloud.githubusercontent.com/assets/18075411/22766114/a8050d14-ee41-11e6-82ef-5cd34cf63a45.png">

:( **View History** != **View Work History**
