### ISSUE TITLE
Copy tweaks: Change "Caseflow Status" to "Caseflow status" and add punctuation

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6673]
"status page" and "status" are perhaps best considered common nouns (vs proper nouns) and should be lowercased.

![image](https://user-images.githubusercontent.com/3781835/44283396-4bdf8280-a22c-11e8-9673-4fe3c971792e.png)
![image](https://user-images.githubusercontent.com/3781835/44283409-5437bd80-a22c-11e8-8845-4551edb255cc.png)

# AC
- Change references from Status Page to `status page`
- Change Status Page to `status`
- Add punctuation on the technical difficulties page

**Comment by nicholasholtz** [comment]
I am guessing the Status page derived from the fact that it is statuspage.io.

**Comment by laurjpeterson** [comment]
Looking in production today and this doesn't look like it was fixed. Moving back to backlog.

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
