### ISSUE TITLE
Adopt single format for passing dates (and times) from back-end to front-end

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#6674]
Currently, we serialize dates and times in many different string formats on the back-end and have to appropriately handle each of those format when they are read on the front-end. This leads to errors caused by us expecting a certain date format and receiving a different format (for example, issue #6550). It would be much more convenient to settle on a single that dates (and times) will be in when they cross the back-end/front-end boundary.

## Acceptance criteria
* All date and time objects are serialized in the same format when leaving the back-end

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years
