### ISSUE TITLE
Fix message when file number does not exist 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#6680]
Currently, when we search for file number that does not exist in VBMS, we display Technical difficulties page with 'try again later' message. This is misleading. We should show either 'Information cannot be found' or something more specific like 'File Number does not exist within VBMS system.'

See Sentry errors for `VBMS::FilenumberDoesNotExist`

**Comment by pkarman** [comment]
This is still a generally valid problem, though more broadly in the app. We still log frequent `VBMS::FilenumberDoesNotExist` errors for reader, e.g.

I'll change the description.
