### ISSUE TITLE
Prod DB dump script & accompanying jenkins job

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#669]
Have a way to dump and sanitize prod DB PII.
   - The script would have a hash of the current migration to keep it from getting out of date.
   - Incorporate it into a jenkins job which uploads the dump to s3, so any developer can download locally.

See the full conversation here: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/345

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
