### ISSUE TITLE
Canceling RampRefilings or AMA Reviews should delete issues too

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6709]
When we cancel a RampRefilingIntake it deletes the associated RampRefiling, but not the RampIssues associated to that refiling. Those RampIssues should be deleted as well.

As another item on this ticket, we should also clean up any orphaned RampIssues in prod.

**Comment by leikkisa** [comment]
These should be deleted in our database.

**Comment by shanear** [comment]
This has been deployed for months. We can assume it's working correctly
