### ISSUE TITLE
Case search / Case list | Add Higher Level Reviews and Supplemental Claims

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6710]
As a VBA employee I want to be able to see all the higher level reviews, supplemental claims and appeals for a veteran, and the details about those reviews.

### AC
- Users can view a list of SCs and HLRs in search results
- Users can view a list of SCs and HLRS in case list within Case details

#### Option 1 (All data revealed in table form)
![search-results-sc-hlr-1](https://user-images.githubusercontent.com/31224257/49529520-31392400-f884-11e8-9f4e-30395a699038.png)

#### Option 2a (Claim high level information on display (and accordion behavior reveals EP code-level information)
![search-results-sc-hlr-2a](https://user-images.githubusercontent.com/31224257/49529685-9260f780-f884-11e8-936f-13257e037893.png)

#### Option 2b ( (Claim high level information on display (and accordion behavior reveals EP code-level information) Opened accordions
![search-results-sc-hlr-2b](https://user-images.githubusercontent.com/31224257/49529694-9856d880-f884-11e8-8f5b-fbb20bd12972.png)

**Comment by mkhandekar** [comment]
adding myself to this one so we can circle back in a few weeks

**Comment by laurjpeterson** [comment]
@shanear - circling back here. @sneha-pai put together some designs for this on Friday and is going to post them to this issue for your and @carolaponce's review.

After her exploration of combining all of the requirements listed in this [comment](https://github.com/department-of-veterans-affairs/caseflow/issues/7016#issuecomment-428678275), she came to the conclusion that we could not fit all SC, HLR and appeal results in one table. Instead, SCs and HLRs would be in one table, while appeals live in another.

**Comment by sneha-pai** [comment]
@shanear here's a proposal for how higher level reviews and supplemental claims might appear when a veteran ID is searched for in Caseflow Search. [ @laurjpeterson ]

### Questions for your consideration: 
- what would you call that list? Right now it's tentatively **VBA Reviews**. 
- Is it important to see **Appellant Name** for HR reviews and Supplemental Claims?
- Are any table columns missing?

### Proposed design:
![search results-proposed](https://user-images.githubusercontent.com/31224257/48099914-3ce6eb80-e1ef-11e8-85ae-7ce175841579.png)

**Comment by shanear** [comment]
> what would you call that list? Right now it's tentatively VBA Reviews.

Not all HLRs and SCs are owned by VBA, so I'd just call it "Other Decision Reviews" or maybe "Other Reviews"

> Is it important to see Appellant Name for HR reviews and Supplemental Claims?

I think so, but not sure.

> Are any table columns missing?

- EP Code should probably change to "EP Code(s)" since there can sometimes be more than 1 EP associated with a HLR or SC.
- Unfortunately, there is no ability to deep link into VBMS 😢 so we can't make those links.
- "Benefit type" might be helpful to know what business line it's with.

**Comment by sneha-pai** [comment]
> * "Benefit type" might be helpful to know what business line it's with.

@shanear What are the different benefit types?

**Comment by shanear** [comment]
>@shanear What are the different benefit types?

@sneha-pai 

you can find them here:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/BENEFIT_TYPES.json

**Comment by joeyyang** [comment]
hey @sneha-pai! Pinging here to get an updated design. Thanks!

**Comment by joeyyang** [comment]
just discussed with @sneha-pai — we agreed to these changes per @shanear's suggestions and I'll summarize them here to save her from having to make another design:
- change “VBA Reviews” -> “Other Reviews”
- “EP Code” -> “EP Code(s)”
- add column “Benefit type”

**Comment by joeyyang** [comment]
discussed a few details with @shanear 
- EP Code
    - for HLRs and SCs that are not `BENEFIT_TYPES.compensation` or `BENEFIT_TYPES.pension`, there will be no EP code & it should say "Tracked in Caseflow" or similar (there will be a link, to be added later — see https://github.com/department-of-veterans-affairs/caseflow/issues/8031)
    - one HLR may have many EPs, so if this is the case each EP should get its own row

**Comment by joeyyang** [comment]
@shanear and I created this wireframe:
![](https://files.slack.com/files-pri/T03FECE8V-FEF70J49X/image_from_ios.jpg)

**Comment by sneha-pai** [comment]
Post conversation with @joeyyang and @shanear and @sneha-pai:

- change title of results to Supplemental Claims and Higher-Level Reviews
- A table might be enough to show

#### What's the most amount of info on this page:
VBMS has a 10 active EP limit per veteran. (10 active supplemental claim EPs and 10 active higher-level review EPs)
Shane guesses: no more than 20

#### Typical:
1-2 active reviews (with 1-2 EPs) + a history of completed reviews

**Comment by sneha-pai** [comment]
Hi @joeyyang and @shanear, please review main issue comment's mocks to review and provide feedback on the two variants displayed.

I'm open to taking a call for feedback as well.

**Comment by joeyyang** [comment]
thank you @sneha-pai! My initial thought is: I like option 1 better and think we can manage the additional engineering complexity in making the custom table. 

My one concern with option 1 is, which maybe @shanear can answer: will this view ever have to display any more information than what's currently available? (Will this view get too dense / break down horizontally if more info comes in?)

**Comment by steve-gov** [comment]
Validated, at least for purposes of this issue:

![screencapture](https://user-images.githubusercontent.com/25468689/51202569-df88ae00-18b3-11e9-9542-6da013b43fca.gif)

**Comment by shanear** [comment]
Some tweaks:
<img width="1029" alt="screen shot 2019-01-15 at 2 01 57 pm 1" src="https://user-images.githubusercontent.com/1596259/51217307-62bdfa00-18dc-11e9-8ce7-1005c29e448b.png">

1. if there is no EP, we should not say "null" in EP Code
1. if the EP is not yet established the status should read "Establishing..."
1. if the EP is not yet established and there is any value in `establishment_error`, then it should stay "Establishment Failed. Support notified." Bonus points if this is a red color
1. remove "Decision Date" column

**Comment by shanear** [comment]
Found some more issues with this page:

<img width="1299" alt="screenshot 2019-01-18 07 30 06" src="https://user-images.githubusercontent.com/1596259/51396051-1dbfe080-1af3-11e9-91c1-f22262498ed0.png">

**Comment by steve-gov** [comment]
Reviewed a number of cases and seems good, but Shane should probably review and close.

<img width="957" alt="screen shot 2019-01-31 at 1 22 09 pm" src="https://user-images.githubusercontent.com/25468689/52086253-42886f00-255b-11e9-8af2-5edbfda84f65.png">

**Comment by shanear** [comment]
yep this is nice :)
