### ISSUE TITLE
Non-rated issues in-line error for required fields

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6714]
CAs will need to enter the last decision date for each non-rated issue, so these issues can be tracked for timeliness. This story covers what happens when a required field isn't filled out AND if one of the rated issues is selected (if a rated issue isn't selected it doesn't matter because the Create EP button is grayed). 

This was originally part of #5991 but was pulled to be done separately because of technical complications and because this page will likely change and we may need to worry about it.

## Acceptance Criteria
  - If a user does not enter a date, an in-line error is displayed that says the field is required (follow pattern of issue category and description)
- Uncategorized issues do not require a decision date

**Comment by shanear** [comment]
This issue is out of date, closing.
