### ISSUE TITLE
Investigate how VACOLS BVA Dispatch outcoding works, and how we might outcode AMA appeals after BVA Dispatch

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6715]
### Raw notes — what happens when BVA Dispatch outcodes in VACOLS?

Walked through [this logic](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/25)

- error if decision is not a valid date 
- error if not all issues have dispositions 
- check if there are any remanded, granted, in-development, and stayed issues
- error if there are any issues marked "in-development"

- if there are any remanded issues
    - ensure that gs_remdest <> 'R' and gs_remdest <> 'D' and gs_remdest <> 'V'and gs_remdest <> 'G' and gs_remdest <> 'N'
    - Q: what do these destinations mean?
    - error of any remanded issue doesn't have a destination

- a bunch of other error checks
 - date to board member has to be before the current date
 - date to board member has to be after the received date

- error if any are missing:
 - regional office
 - type action
 - hearing request
 - hearing action
 - service org
 - opinion code
 - decision team
 - attorney code
 - signing member
 - docket number
 - prior decision date if type action is 3 or 7
 - special contentions not filled in
 - other contentions not filled in

- assign the appeal disposition to the highest-level issue disposition
    - Q: what are the rules for this? that code seems like it's not in the snippet
    - i'm guessing - grant if any issues granted, remand if no issues granted and some remanded, denied if all issues denied

- if there are remanded issues
    - if there are also granted issues, mark the appeal status as a remand and a partial grant
    - else mark it as a remand
    - Q: what is gs remarks for?
    - if the POA is a private attorney, change the remand destination to "D" - AMC (now AMO?) (as of 2017)
- if no remanded issues
 - put the appeal in history status
 - mark it as a final decision

- if the appeal is marked as a remand
 - use the remand destination to determine where to send the appeal - which location number and and ro 
 - if remand dest is V send it to the Veterans Health Administration Central Office
 - if remand dest is N send it to the Remand General Counsel
 - if remand dest is R 
     - and the action is "Court Remand", send it to CAVC Remand FIle
     - else send it to the "Remand to the regional office" location
     - mark the specific RO
 - if it's a remand with any other remand dest value
   - send it to location 97 which i believe is ARC
 - otherwise..
   - put it in the completed file location
   - if the RO is Veterans Health Administration Central Office, send it to VAMC 
   - if the RO is *not* VHA CO
     - if there are granted issues and a private attorney is the rep, put it in the ARC location
     - otherwise, put it in the RO location
 - in all of these conditions, note if the appeal is going to an RO or to VAMC

 - get program area 
  - Q: what is this?

- update the appeal table with all the information we calculated above:
 - decision date
 - HIS or REM status
 - location information signifying whent the appeal moved to its next location
 - appeal's next location
 - top level disposition
 
 - update folder table with other info
 
 - do something in the ASSIGN table
  - if the appeal is being closed, maybe close assignments?
  - if the appeal is being remanded, something else

 - open the form letter
 - check if there's another active appeal for the appellant which might possibly also need to be outcoded
 - check if there's a pending court remand for the appellant, user is instructed to forward case to Lit Suppport if so
 - check if there's a pending motion for the appeallant, user is instructed to forward the case to the decision team support chief if so
 - Please complete a Notice of Appeal (NOA) if there are specific action codes 
   - From my research this looks like a form that confirms that the appellant is appealing to CAVC

- if there's an AOD diary, "'AOD diary exists.  After reestablishing cover jacket on pending issues, please walk case to Development Team.'"

### Open Questions
 - Caseflow Dispatch does not handle all cases. How can we ensure that all AMA cases can be dispatched?
   - It only handles paperless remands sent to ARC (Location 97), and paperless full grants.
  - It doesn't handle remands that are sent to the Veterans Health Administration Central Office or the Remand General Counsel. 
  - It doesn't handle paper cases.
- How can we transition away from legacy appeal outcoding in VACOLS to outcoding in Caseflow?
- Schedule meeting with Jed to discuss if any pieces are redundant

**Comment by laurjpeterson** [comment]
Closing. We're "outcoding" from the IDT for RAMP appeals, and working through #5591 for future state outcoding work.
