### ISSUE TITLE
Determine which organizations a Caseflow user belong to

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#6724]
In order to allow folks to visit [generic organizational task queues](https://github.com/department-of-veterans-affairs/caseflow/issues/6573) for various organizations within the Board, we need to know if they are a part of those organizations. The ways by which we determine if somebody can access a queue differs for each queue that currently exists. For VSOs, we check that the user has the [VSO CSEM function](https://github.com/department-of-veterans-affairs/caseflow/blob/9042b27f3284cddd7bae38ab2fc0d469843dc3a2/app/models/user.rb#L128) and that the user is [associated with the VSO in BGS](https://github.com/department-of-veterans-affairs/caseflow/blob/9042b27f3284cddd7bae38ab2fc0d469843dc3a2/app/models/organizations/vso.rb#L2). For attorneys, judges, and co-located admin, we rely on different fields in VACOLS `staff` table to [determine the board employee's role](https://github.com/department-of-veterans-affairs/caseflow/blob/9042b27f3284cddd7bae38ab2fc0d469843dc3a2/app/repositories/user_repository.rb#L70). We will probably do something similar to the latter approach as we enable access to organizational task queues for other Board teams.

In addition to determining if a single user is a member of an organization, we need to determine which users belong to an organization so we can build the list of folks to populate the "Assign to team member" dropdown.

## Acceptance criteria
* Determine if a user belongs to an organization
* Retrieve list of users who belong to an organization

**Comment by laurjpeterson** [comment]
Closing. Mark has built a way for our users to map individuals to teams and we acquired the October 2018 BVA org chart.
