### ISSUE TITLE
Resolve test failures with phantomJS crash

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#673]
On master, one specific test seems to fail non-deterministically. When it fails, phantomJS has crash.

Will fail on the test `Cancel an Establish Claim task returns me to landing page` with output:

PhantomJS client died while processing {"id":"42f919e5-a25e-4f94-b675-a097ec110bef","name":"click","args":[1,5]}
If you run poltergeist with debug mode on (verbose), you will see output "phantomjs has crashed".  

I looked into this for ~3 hours without luck. Within the test, it crashes on the line executing `click_on "\u00AB Go Back`. Some ideas I tried:
  - thought it might be related to the unicode character. Removed it but didn't help
  - This click is happening inside a modal. Thought it might be related to that but not sure how that would matter or how to fix that.

**Comment by kierachell** [comment]
Is this still failing? I am unable to reproduce the failure to check.
It's been passing with all kinds of weird selectors.

**Comment by joofsh** [comment]
looks like it's stopped failing on master. Closing this issue
