### ISSUE TITLE
Test attorney-co-located loop with Jed (admin action pilot)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6734]
We've finished developing both the back and front end for the attorney to co-located loop so we'd like to test the whole flow and ensure it updates VACOLS as intended.

- Testing changing VACOLS locations
   - When attorneys assign admin actions to co-located, VACOLS location changes to CASEFLOW
   - When co-located assign translation task to translation, VACOLS location changes to 14 
   - When co-located assigns schedule hearing task to hearings team, VACOLS location changes to 57
   - When co-located places a task on hold, VACOLS location remains CASEFLOW
   - When co-located assigns case back to attorney, VACOLS location changes back to attorney's location
 
- Testing assignment back to attorney
   - When co-located assigns case back to attorney, attorney's Days waiting counter restarts at zero

- Testing VACOLS reports for any empty fields
   - Let's look at what Cases charged to - CASEFLOW location - looks like
   - When co-located places task on hold, Cases charged to CASEFLOW
   - Cases charged to 14
   - Cases charged to 57

- AMA attorney/co-located loop
   - Attorneys cannot select Translation or Schedule hearing tasks for AMA appeals

### Test users
- CF_KHAN_397 station ID 397: Attorney
- CF_KIRK_317 station ID 317: Co-located

**Comment by evankroske** [comment]
## Test Plan
- [ ] Become CASEFLOW_283.
- [ ] Open the case of LAA.
- [ ] Select "add colocated task".

**Comment by laurjpeterson** [comment]
@dannysellers - can we run through this test locally?
- When the case was assigned back to the attorney, the days waiting counter restarted at 0 in the attorney's queue?

**Comment by dannysellers** [comment]
@laurjpeterson Confirmed!

<details><summary>gif</summary>
<img src="https://user-images.githubusercontent.com/8533004/45172846-848fcd80-b1d4-11e8-9f14-3335332f485f.gif">
</details>

**Comment by aroltsch** [comment]
- [ ] Attorney’s on-hold tasks don’t show up in the queue
- [ ] When attorney assigns an AMA colocated admin task to a user, attorney’s task becomes on hold. A new colocated task is created with a parent ID of the attorney task. 
- [ ] When attorney assigns a legacy colocated admin task to a user, attorney’s task becomes on hold. A new colocated task is created without a parent ID of the attorney task. 
- [ ] A colocated user should see all non-completed tasks in their queue with statuses (assigned, in_progress, on_hold)
- [ ] If it is a hearing schedule or translation for an AMA task, a colocated user can only do two things: assign back to attorney and place on hold.
- [ ] If it is a hearing schedule or translation for a legacy task, a colocated user can only do two things: send to the team and place on hold.
- [ ] When a colocated sends back an AMA task to attorney, colocated task should become completed and attorney’s task must become assigned and assigned at should reset.
- [ ] When a colocated sends back a legacy task to attorney, colocated task should become completed and attorney’s task must be assigned to attorney’s location and must show up in attorney’s queue. Didn’t pass. Result: task shows up under attorney queue but it is missing a task_id.
