### ISSUE TITLE
Add issue dispositions for AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6736]
When attorneys are assigning AMA cases to judges, they need to add issue dispositions for each issue, so the judge can review the draft decision.

**Out of scope:** 
- Attorneys editing issues
- Attorneys adding dispositions to edited issues

**Comment by laurjpeterson** [comment]
I reviewed the demo site and this issue looks done and works for AMA appeals! @dannysellers can it be closed?

**Comment by dannysellers** [comment]
In progress, closing https://github.com/department-of-veterans-affairs/caseflow/pull/7007
