### ISSUE TITLE
Existing EP: Remove "Send to RO" link and reposition "Cancel" link

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#674]
As Product Owner, I would like to have the link "Send to RO" removed and the "Cancel" link reposition so that the Existing EP page more accurately reflects current available tasks.

# Acceptance Criteria
1. Verify that the link "Send to RO" has been removed from the Existing EP page.
1. Verify that the link "Cancel" has been moved.  (refer to mockup)

# Mockups
View - Existing EP Page - Before
![image](https://cloud.githubusercontent.com/assets/23063044/21906149/16b5ad74-d8d8-11e6-9490-1fdc95bbf278.png)

View - Existing EP Page - After
<img width="929" alt="screen shot 2017-01-12 at 2 15 21 pm" src="https://cloud.githubusercontent.com/assets/4975959/21904428/959d4d74-d8d1-11e6-98cc-96138632e83b.png">

# Related Stories
Decision Review: Remove "Send to RO" link and reposition "Cancel" link #690

**Comment by lakohl** [comment]
Old link and button copy and placement:
<img width="791" alt="screen shot 2017-01-12 at 2 13 25 pm" src="https://cloud.githubusercontent.com/assets/4975959/21904359/515e3b28-d8d1-11e6-8910-f72338df4b68.png">
New link and button placement: 
<img width="929" alt="screen shot 2017-01-12 at 2 15 21 pm" src="https://cloud.githubusercontent.com/assets/4975959/21904428/959d4d74-d8d1-11e6-98cc-96138632e83b.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Steps for Validation:
1. Go into dispatch as a caseworker, establishing a claim 
2. On the Review Decision doc page, take the first step to establish a full grant w/o any Special Issues
3. Assign EP page pops up showing that the "Send to RO" link has been removed and the "Cancel" link has been re positioned. 

Screenshots: 
<img width="1277" alt="screen shot 2017-01-23 at 2 12 04 pm" src="https://cloud.githubusercontent.com/assets/23038505/22218776/542c4bbc-e176-11e6-8fb7-c520e97e2fad.png">
