### ISSUE TITLE
Open up new BGS endpoints in Production

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#677]
Contacting Michael Taylor about what is needed for this waiting on a reply

**Comment by shanear** [comment]
Had a call with BGS on this today.

We will have to fill out a prod change request, and do some preprod testing. Next step is to fill out the prod change request and get preprod testing scheduled

**Comment by shanear** [comment]
Sent emails to both the SIO team notifying them of our release, as well as a Tina Edwards with the WSCR document. Now just playing the waiting game until preprod.

**Comment by nikitarockz** [comment]
Please provide the following:

-	Implementation plan
-	Test Plans
-	Test Results
-	Back-out plan

Note:  The attached document is a page from the SIPT slides that has information. 
[CO Requests.pptx](https://github.com/department-of-veterans-affairs/caseflow/files/751409/CO.Requests.pptx)

**Comment by nikitarockz** [comment]
We are no longer blocked, and progressing on as expected.

**Comment by nikitarockz** [comment]
**_Success._**
