### ISSUE TITLE
Success Page | Timeout issues

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6775]
Requires #6771 

Currently, the VACOLS upload takes ~3 minutes. If it cannot be reliably sped up to under 1 minute, we need to make the following changes:

1) Move the VACOLS upload to a job
1) Update the frontend confirmation logic to start the job and then poll the backend to see when the job is completed
1) While the job is running, we should prevent the user from making other edits (possibly show a banner on other pages?)
1) Add a blocker on the backend to prevent two jobs from running at the same time

**Comment by MeredithStewart** [comment]
Moving to backlog, need to test what kind of optimizations we'll need when we are just in Caseflow (not VACOLS).
