### ISSUE TITLE
Spreadsheet Validations | Specific errors

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6777]
Currently when a hearing scheduling user gets a spreadsheet error, the errors aren't descriptive enough to be useful to the user. We need to make the errors more specific:

1) When a judge is missing from VACOLS, we should show the judge name
1) When a date is out of the date range, we should show the date
1) When there are duplicate dates, we should show the duplicate dates
1) When a date is not in the right format, we should show the date
1) When an RO doesn't match our data, we should show the RO

**Comment by MeredithStewart** [comment]
Refer to this ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/7492

**Comment by laurjpeterson** [comment]
When will the hearing schedule be built for FY 2020? Usually June/July summer before. @pshahVA to ask Lori (Hearing Branch Deputy Chief)
