### ISSUE TITLE
Adapt AMA attorney checkout flow for RAMP appeals

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6778]
- Get basic AMA attorney flow working for appeals where all issues are granted or denied
- Verify requirements for `on_hold` tasks and ensure they're correctly filtered out for an attorney if necessary
- Allow remand reasons to be chosen for AMA appeals during attorney checkout (https://github.com/department-of-veterans-affairs/caseflow/issues/5760)
- Investigate and address errors in the console that appear when navigating to `/queue` if necessary )("Same key" warning, "Invalid prop type passed to AttorneyTaskListView")
- Ensure that the Notes field filled out by attorneys is saved somewhere and displayed to judges for AMA appeals
- Disable "Edit Issue", "Delete Issue", and "Add Issue" for AMA attorney checkout
- If disposition is "Vacated", remove the "duplicate issue" checkbox

**Comment by dannysellers** [comment]
- [ ] Get basic AMA attorney flow working for appeals where all issues are granted or denied
- [x] Verify requirements for `on_hold` tasks and ensure they're correctly filtered out for an attorney if necessary (#6750)
- [ ] Allow remand reasons to be chosen for AMA appeals during attorney checkout (https://github.com/department-of-veterans-affairs/caseflow/issues/5760)
- [ ] Investigate and address errors in the console that appear when navigating to `/queue` if necessary )("Same key" warning, "Invalid prop type passed to AttorneyTaskListView")
- [ ] Ensure that the Notes field filled out by attorneys is saved somewhere and displayed to judges for AMA appeals
- [ ] Disable "Edit Issue", "Delete Issue", and "Add Issue" for AMA attorney checkout
- [ ] If disposition is "Vacated", remove the "duplicate issue" checkbox
