### ISSUE TITLE
Add new Fiduciary issues

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6796]
![image](https://user-images.githubusercontent.com/3781835/44861151-f51f7300-ac45-11e8-8b8a-0aeb19986e39.png)

**Comment by amprokop** [comment]
02 Hub Manager removal of a fiduciary under 13.500
03 Hub Manager misuse determination under 13.400
04 RO Director decision upon recon of a misuse determ
05 Dir of PFS negligence determination for reissuance

**Comment by dannysellers** [comment]
| Program        | Issue           | Level 1  | Level 2 |
|:------------ |:------------ |:------- |:------- |
| 12 | 02 | Hub Manager | removal of a fiduciary under 13.500 |
| 12 | 03 | Hub Manager | misuse determination under 13.400 |
| 12 | 04 |  RO Director | decision upon recon of a misuse determ |
| 12 | 05 | Dir of PFS | negligence determination for reissuance |
