### ISSUE TITLE
All Modals | Not proprely capturing focus

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#680]
# Description
This issue happens across all applications.  Any time a modal is triggered to open, it is possible to use `TAB` and `SPACE` to interact with the elements in the background.

**Confirmed Environment(s)**
- [x] Dev
- [x] Demo
- [ ] UAT
- [ ] Prod

**Type of Bug**
- [x] Functional
- [ ] Design
- [ ] Security
- [ ] Tech Improvement

**Severity Level**
- [ ]    5 - Data loss, data corruption or system unavailable
- [ ]    4 - Important functionality is unavailable with no workaround
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround
- [X]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround

# Reproductive Steps
1. Select one of the special issues that will cause the modal to show up when clicking _Create End Product_
1. Once the modal shows up press `TAB` on the keyboard and watch the focused element switch to an element in the background
1. Press `TAB` on the keyboard until _Cancel_ link is selected from the background
1. Press `ENTER` or `SPACE` to have another modal show up or interact with a background elements.

# Screen Shots
<img width="1012" alt="screen shot 2017-01-13 at 09 12 28" src="https://cloud.githubusercontent.com/assets/18075411/21932811/7567a65e-d970-11e6-9d13-10deeb79a675.png">

<img width="854" alt="screen shot 2017-01-13 at 10 12 53" src="https://cloud.githubusercontent.com/assets/18075411/21934984/9dae1af4-d979-11e6-9208-dfe2abd5d4ab.png">

**Comment by astewarttistatech** [comment]
Hitting tab doesn't go through all of the possible options listed in modals. 

Current View: Certification V2 | Cancel Certification | Demo 
![modal navigation](https://user-images.githubusercontent.com/23038505/32283438-af2351d4-befa-11e7-862e-a5e92fcb0c9b.gif)
