### ISSUE TITLE
Caseflow Dispatch when hovered over creates odd link

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#681]
**Description:** 
When in Caseflow Dispatch, as any user, and the header logo is hovered over with a cursor, the logo becomes a link with a small underscore to the left of it. 

**Steps to Recreate:**
1. Go to Dispatch in Demo, any page will work as long as it has the header
2. Hover over Dispatch logo on header with cursor 
3. Validate link has a small underscore to the left of it. 

**Browser Found:** Chrome
**Environment Found:** Demo

**Screenshots:**
![Uploading Screen Shot 2017-01-12 at 12.24.18 PM.png…]()

**Associated Issues/Stories:**

**Reported by:** Alexis Stewart

**Comment by astewarttistatech** [comment]
@mdbenjam Hey did you fix this already?

**Comment by mdbenjam** [comment]
I think this was fixed a while ago, and isn't even relevant anymore. Moving it to done.

**Comment by mdbenjam** [comment]
@nikitarockz Just for awareness. I'm cleaning up things with my name on them :)

**Comment by nikitarockz** [comment]
@mdbenjam LOLOL, Ok,
