### ISSUE TITLE
Support quality review

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6814]
AMA appeals will need to be routed to quality review before dispatching appeals in order to monitor decision-writing quality and consistency.

- Learn logic for sending an AMA appeal for quality review from Josh Freeman
- When case is selected for quality review, add `Quality review` task
   - Q: Should this be created as a child task for dispatch decision?
- Create quality review organizational queue
   - Determine who is part of the quality review team
   - Q: Note, this team changes more frequently because attorneys at the Board go "on detail" to this org
- Determine how to distribute cases to quality review attorneys - e.g. round robin automatically or using the assign cases view
- When quality review attorney has completed their quality review, they can send the case to BVA dispatch for dispatching - `Ready for dispatch`. 
    - Propose to reuse modal view from co-located assigning cases back to attorneys

---
- Quality review needs the ability to send a case:
   - Back to their judge (if there are required corrections to the decision) 
   - Straight to BVA dispatch (if there are no issues with the decision and it can go straight out)

**Comment by laurjpeterson** [comment]
From Josh Freeman, 9/5/2018, when asked about logic for AMA quality review. 

At this point, there is no logic.  The volume of Post RAMP NODs is simply too low to do an accurate estimation.  Since we calculate the accuracy rate on a monthly basis, if we clear 100 in October, we’ll need to QR 59 of them.  That’s less QR’ing than checking up on people.  I’m trying to put together a pitch to management regarding the hows of implementation so maybe I’ll have something better by next week. 

cc: @amprokop

**Comment by amprokop** [comment]
Thanks! Also tagging @aroltsch who will likely be leading this effort.

**Comment by amprokop** [comment]
Not sure I follow the seeming statement that they need to do QR on 59 out of 100 appeals — but all in time, I suppose!

**Comment by laurjpeterson** [comment]
Email sent to Josh 9/24:

Connected with Chris and we have some ideas for QR. Here's the spark notes. Are you available to connect sometime Tuesday or Wednesday to dig a little deeper into them?

*Overall idea:* You could suggest that instead of selecting the # of cases to QR based on a monthly sample, sample from the entirety of the RAMP appeals period - October 1st to February 14th. (Or, since the Secretary has to certify that VA is ready on January 14th, that period could be October 1st to January 14th.) Let's say there will be 250 case over that entire time period, then QR would only have to do 40-50 cases. 

*Some relevant Caseflow and pilot details:*
= We won't have a QR queue ready on October 1, so in these options we have spelled out how to handle that period. But, I anticipate that we could have one at least early November. 
- Also note that as of Friday, September 21, only 55 cases are ready to be distributed day 1 (54 Direct Reviews that don't have IHP writing VSOs, 1 Evidence Submission that is within the evidence window and doesn't have an IHP writing VSO).

Option 1:
- sample the entirety of the RAMP period
- In October, randomly pick two judges and QR all of their cases. QR partners with the Judge to review the decisions. Ask the judge to not check out their cases to dispatch (OR, QR 1 from each judge)
- prototype QR in november
- Pros: deliberate approach - QR can partner with judges to really learn about AMA decision writing

Option 2:
- sample the entirety of the RAMP period
- do not QR any cases October. just select cases from a few judges later, starting in November
- prototype QR in november

Option 3: (least favorite)
- Selection per month like we do for legacy - QR almost all cases
- Start late in October, giving as much time as possible to build a QR queue
- Cons: would put QR under a lot of strain

**Comment by laurjpeterson** [comment]
Completed this work! And documentation captured in the wiki, here - https://github.com/department-of-veterans-affairs/caseflow/wiki/Quality-Review
