### ISSUE TITLE
Caseworker | Spacing for "Special Issue Category" header and above dropdown is close

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#683]
**Description:**
Currently, if you go through the flow to establish a claim as a caseworker, on the Review Decision page, the Special Issue Category header is very close to the above drop down menu. 

**Steps to Recreate**

1. Log into Dispatch under the function of a Caseworker (Establish Claim at Station 318)
2. Select the option to "Establish New Claim"
3. Scroll down the Review Decision page to verify the "Special Issue Category" header is close to the above drop down menu. 

**Expected Results:** 
Spacing should be [ add specs here ]

**Environment Found:** Demo
**Browser Found:** Chrome

**Screenshots:**
![caseflow dispatch - review decision doc](https://cloud.githubusercontent.com/assets/23038505/21938035/98c928ea-d987-11e6-9148-0acdcbdf13b9.png)

**Associated Issues/Stories**

**Reported by:** Alexis Stewart

**Comment by kierachell** [comment]
<img width="874" alt="screen shot 2017-02-07 at 15 12 57" src="https://cloud.githubusercontent.com/assets/18075411/22709490/eee17b46-ed47-11e6-84da-ac1b9d663145.png">
BOOM!
quickest validation yet?
