### ISSUE TITLE
End Product:  Hide "POA" and "Segmented Lane" fields and labels

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#684]
As a Product Owner, I would like to have the "Segmented Lane" and "POA" fields/radio options hidden so that they are temporarily disabled until the integration rules have been defined.

# Acceptance Criteria
1. Verify that the label "Segmented Lane" is no longer visible.
1. Verify that the label "POA" is no longer visible.
1. Verify that the "POA" radio options are no longer visible.
1. Verify that the "Allow POA Access Documents" is not visible.

# Mockup
**_View - End Product Page - No POA and Segmented Lane_**
![image](https://cloud.githubusercontent.com/assets/23063044/21938832/01feba7a-d98b-11e6-9e86-f942bc5daf47.png)

# Related Issues

**Comment by kierachell** [comment]
On the back end: what are the default values (if any) will be passed for now?

**Comment by kierachell** [comment]
And... it's gone!

<img width="1101" alt="screen shot 2017-01-24 at 09 36 14" src="https://cloud.githubusercontent.com/assets/18075411/22251384/91ee5ea2-e218-11e6-9996-ed7477e0a73b.png">
<img width="1138" alt="screen shot 2017-01-24 at 09 36 40" src="https://cloud.githubusercontent.com/assets/18075411/22251407/a26e7654-e218-11e6-82d7-a2df8310889e.png">
