### ISSUE TITLE
Caseworker | Establish Claim | Special Issue Categories Transfer over different Decision Types

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#685]
**Description:**

When in Caseflow Dispatch, as a Caseworker trying to establish a claim, on the Review Decision page, the caseworker can change decision types and if they have any Special Issue Categories selected they will transend the different decision type.

**Steps to Recreate:**

1.Go to Dispatch as a Caseworker (Establish Claim at station 318).
2. From the Work History page, select to "Establish Next Claim".
3. On the Review Decision page, scroll down to the Special Issue Category checklist and select a few of the options available. 
4. In the Decision Type drop down menu, change from what was currently selected (Full grant) to another decision type. 
5. Verify that the Special Issue Categories selected did not change.
 
**Expected Results (If Any):**

When a decision type is changed, the selected Special Issue Categories should automatically be cleared for selection. 

**Browser Found:** Chrome

**Environment Found:** Demo

**Screenshots:**
<img width="340" alt="screen shot 2017-01-13 at 11 52 33" src="https://cloud.githubusercontent.com/assets/23038505/21938502/a8375b4c-d989-11e6-80f2-2b556331da73.png">
<img width="293" alt="screen shot 2017-01-13 at 11 53 15" src="https://cloud.githubusercontent.com/assets/23038505/21938503/a83ecff8-d989-11e6-93db-2e47245efe3e.png">

**Associated Issues/Stories:**

[# Issue number] Title of Issue/Story

**Reported by:** Alexis Stewart

**Comment by kierachell** [comment]
**PASSED**
Changing Decision Type functionality will be deprecated!
