### ISSUE TITLE
Co-located tweaks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6855]
Tracking some tweaks before launch.

Co-located user
- Add title in header font to co-located queue = "Your Cases"
- Add notes box when co-located user places hold
- Change Pending tab to read Pending action
- Co-located user can add another hold when a case is in the Pending Action tab

Attorney user
- Change copy from "Add Colocated task" to "Add admin action" 
@laurjpeterson, shouldn't it say Add administrative action? [asks Sneha]

**Comment by sneha-pai** [comment]
### Note 1: 
![screencapture-caseflowdemo-queue-2018-09-06-16_42_35](https://user-images.githubusercontent.com/31224257/45228713-ed894b00-b291-11e8-953c-c83a5dcd6e64.png)
"When the hold has been completed, the case will automatically move to the Pending Action tab


### Note 2
"Pending" tab should be renamed to "Pending action"

**Comment by laurjpeterson** [comment]
@sneha-pai re: Note 2, I think being able to type is how the dropdown as designed. For example, when an attorney is selecting a different judge to check the case back out to, they can begin searching for a judges name instead of having to scroll through.

@sneha-pai @mkhandekar - are we aligned on co-located queue table being titled "Your cases" and changing attorney queue to read "Your cases" as well?

**Comment by dannysellers** [comment]
@laurjpeterson we can prevent searching/typing in the dropdown. I agree that doing so here would probably make this page easier to figure out—otherwise, we wouldn't (by default) validate the input until the user clicks Continue, etc

**Comment by mkhandekar** [comment]
Yes, I'm aligned with co-located and attorney tables being titled "Your cases"
