### ISSUE TITLE
Lightweight Case timeline for RAMP appeals pilot

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6856]
Let's try to design and implement a lightweight Case timeline for RAMP appeals pilot (does not need to be ready exactly on Oct 1).

For AMA appeals only.

### AC
- Create another "tab" in Case details for Case timeline
- Case timeline elements:
   - NOD date
   - Decision date

**Comment by mkhandekar** [comment]
I've added a few questions (yellow with black border - @laurjpeterson can you take a peek?) and sketches to the mural started by LP!

https://app.mural.co/t/workqueue2001/m/workqueue2001/1531849576358/38b753bff1e25963a76d8ebecf9679d6445c39b3

### NOD recieved, decision pending
Since the timeline is pretty sparse, added a line about what to expect in this area soon.
![screenshot 2018-09-12 11 49 11](https://user-images.githubusercontent.com/1598889/45436952-f0b17c00-b681-11e8-8644-1e49eeba86fc.png)

### NOD recieved, decision made (dates at the end of sentence)
![screenshot 2018-09-12 11 49 20](https://user-images.githubusercontent.com/1598889/45436994-06bf3c80-b682-11e8-8e52-47a552ae46e8.png)

### NOD received, decision made (dates before checkbox - I prefer this at this point, but could change my mind / approach when we design the entire timeline), deep links to specific forms/documents in Reader

![screenshot 2018-09-12 11 49 29](https://user-images.githubusercontent.com/1598889/45437142-4ede5f00-b682-11e8-8dc5-9c6f2f3043dc.png)

**Comment by laurjpeterson** [comment]
Oh one more thing! For this initial timeline, I think we should just include the `NOD date` and `BVA decision date`. `Extension request ruling` is an administrative action that co-located would be working on and I agree would eventually be in the Case timeline, but not for this first pass.

I'd suggest the copy is just "BVA decision date".

I prefer the version with the dates before checkbox!

**Comment by mkhandekar** [comment]
Brought this into sketch:

### NOD received:
![image](https://user-images.githubusercontent.com/1598889/45499044-83691e00-b749-11e8-81a3-65d6a8ca82d9.png)

### BVA decision made:
![image](https://user-images.githubusercontent.com/1598889/45499048-85cb7800-b749-11e8-9f6e-20dbfd6b9e87.png)

**Comment by laurjpeterson** [comment]
Related support ticket about viewing prior locations so co-located knows what judge to email questions to - https://github.com/department-of-veterans-affairs/appeals-support/issues/3040

**Comment by laurjpeterson** [comment]
Related support ticket about task information from the attorney disappearing when the case is put on hold. Co-located user would like to see the attorney's instructions, not only the fact that they moved the case from new to on hold, in the Task information section of case snapshot - https://github.com/department-of-veterans-affairs/appeals-support/issues/3041

Both of these support tickets may not be resolved with Case timeline, but posting here for visibility.

**Comment by mdbenjam** [comment]
FYI the case status UI resides in vets.gov, which means it's unlikely we'll get much reusability here. 

Something I'd love to chat about is displaying tasks in case timeline or maybe their own section. Like a task hierarchy, where we can show all the tasks in the tree. Who completed each of them and when. I think this would solve a number of the issues that co-located users brought up. But maybe is a separate discussion from case timeline.

**Comment by mdbenjam** [comment]
Are we building case timeline for both legacy and AMA?

**Comment by mdbenjam** [comment]
Also we currently do not capture which NOD form and decision document correspond to this appeal, so we can't really do the linking thing at the moment.

**Comment by laurjpeterson** [comment]
> Something I'd love to chat about is displaying tasks in case timeline or maybe their own section. Like a task hierarchy, where we can show all the tasks in the tree. Who completed each of them and when. I think this would solve a number of the issues that co-located users brought up. But maybe is a separate discussion from case timeline.
- Agree on this! Showing tasks should be part of case timeline, but because of the design lift involved, not this initial lightweight version that I'd like to get out during the pilot. 

> Are we building case timeline for both legacy and AMA?
- Eventually, yes. For this ticket, I was thinking just AMA because it would be easier. If you think it's just as easy to do this same thing for legacy, go for it! We'd want to add in Form 9 date (in addition to NOD and decision date) for legacy, though.

> Also we currently do not capture which NOD form and decision document correspond to this appeal, so we can't really do the linking thing at the moment.
- Sounds good, we can leave the links out.

**Comment by mdbenjam** [comment]
I'll also need some images for this.

**Comment by mkhandekar** [comment]
images live here (for the green check mark and gray dot): https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/Caseflow%20Queue/images

**Comment by mdbenjam** [comment]
Is the BVA Decision made when the judge sends it to BVA dispatch or when BVA dispatch sends it out?

**Comment by mdbenjam** [comment]
For legacy should we show the same thing that exists in appeals status?

**Comment by laurjpeterson** [comment]
It should be the date on the decision doc which should be the same date the decision is mailed. Can you remind me - we get that date from the IDT right? 

If not, we can show the date the decision was outcoded - when the BVA dispatcher finished what’s in the IDT. In that case, we can change the copy to say something like “Date dispatched from BVA”

In the future, we may need to ask a user to input the decision date if we don’t have a way to get it programmatically.

If we’re doing legacy, yes, the same as appeals status.

**Comment by mdbenjam** [comment]
It looks like we currently only have the date we outcode. So I'm going to change the copy for now to Date dispatched from BVA.
