### ISSUE TITLE
EP Cancellation | Cancel EP Establishment | Loading favicon moves across page

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#686]
# Description
When a Caseworker is in Dispatch, establishing a claim and decides to cancel, the loading favicon shifts from the bottom right of the page to the left. 

**Environment:**
- [ ] Production
- [ ] UAT
- [X] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [x] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
1. Go into Dispatch as a Caseworker. 
2. On the `Caseworker Home` page, click the **_Establish Next Claim_** button.
3. On the `Review Decision` page, click the **_Cancel_** button. (Note;  This can be done on any of the pages in Dispatch that you can cancel on.)
4. When the `EP Cancellation` modal appears, the loading favicon appears and shifts to the left on the bottom of the modal. 

## Screenshots
**Browser Found:** Firefox/Chrome
**_Scenario 1 - Favion on the wrong side_**
![dispatch_review_decision_cancelmodal](https://cloud.githubusercontent.com/assets/18075411/21955966/ab319d7a-da43-11e6-8ee2-94ec7315d60c.png)

**Expected Results**: 
Loading favicon should be on the right of a page/modal. 
![dispatch_review_decision_cancelmodal2](https://cloud.githubusercontent.com/assets/18075411/21955982/03c30514-da44-11e6-9a9a-0ff441551453.png)

# Related Stories
n/a

**Reported by:** Artem Vovk

**Comment by kierachell** [comment]
<img width="944" alt="screen shot 2017-02-01 at 09 09 30" src="https://cloud.githubusercontent.com/assets/18075411/22510132/c38bfd4c-e85e-11e6-9099-d080b4295817.png">
Look real bad - is css messed up or what?

**Comment by kierachell** [comment]
UAT right now:
<img width="447" alt="screen shot 2017-02-01 at 10 05 19 am" src="https://cloud.githubusercontent.com/assets/18075411/22512173/17801288-e866-11e6-8b7d-e9605b480f87.png">

**Comment by kierachell** [comment]
<img width="795" alt="screen shot 2017-02-07 at 13 43 23" src="https://cloud.githubusercontent.com/assets/18075411/22706059/dd15467e-ed3b-11e6-8293-8420b6706431.png">

AMAZING STYLING
5 OUT OF 7
WOULD RECOMMEND
