### ISSUE TITLE
SPIKE:  Routing EPs: investigate adding EP labels and/or stations in VBMS

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#689]
Talk to VBMS about:
- Adding labels to EPs 
- Adding stations for special issue centers
- VBMS notes integration

We currently have unique EP labels for AMC and for PMC - can we add unique labels in 170s series for other specialty centers? e.g., BVA Grant Education.

If not, can we create additional VBMS stations so every location (unique in VACOLS) has a unique VBMS station?

**Comment by shanear** [comment]
Asked VBMS about these:

New EP Codes/Labels:
https://github.com/department-of-veterans-affairs/dsva-vbms/issues/67

Notes:
https://github.com/department-of-veterans-affairs/dsva-vbms/issues/66

**Comment by shanear** [comment]
Got answers here! Pursuing each of these options separately.
