### ISSUE TITLE
Capitalize Veteran name before using as an argument to Establish Claim

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6897]
## Story
When a Veteran's name is not capitalized when sending the Veteran's information in the establish_claim VBMS call, it can cause an incident flash error, causing establish_claim to fail

## Acceptance criteria
A Veteran's name is capitalized before sending it to VBMS in establish_claim

## Validation
Monitor incident flash errors to see if any of them being caused have non-capitalized names.  Potentially ask to specifically have one of the past failures to be re-intaken to see if it causes an incident flash.

**Comment by leikkisa** [comment]
Might not need these, we suspect it's not the actual problem.

**Comment by shanear** [comment]
Starting to look like this isn't the problem. I'm gonna close this issue and reopen if we end up needing it.

**Comment by nicholasholtz** [comment]
Provided vet IDs to Jared Mrozinski this morning for VBMS to look into this. @shanear

**Comment by leikkisa** [comment]
Another thing I want to ask about is if the middle initial is missing, if that could potentially be a cause for the Incident Flash.
