### ISSUE TITLE
Decision Review:  Remove "Send to RO" link and reposition "Cancel" link

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#690]
As Product Owner, I would like to have the link "Send to RO" removed and the "Cancel" link reposition so that the Decision Review page more accurately reflects current available tasks.

# Acceptance Criteria
1. Verify that the link "Send to RO" has been removed from the Decision Review page.
1. Verify that the link "Cancel" has been moved.  (refer to mockup)

# Mockup
**_View - Decision Review - Before - Both Cancel and Send to RO_**
![image](https://cloud.githubusercontent.com/assets/23063044/22006266/a2cf6dd8-dc37-11e6-9ab6-984c60fd3c73.png)
**_View - Decision Review - After_**
![image](https://cloud.githubusercontent.com/assets/23063044/22006309/0b3c8450-dc38-11e6-931a-46bae9185b2c.png)

# Related Stories
Existing EP: Remove "Send to RO" link and reposition "Cancel" link #674

**Comment by astewarttistatech** [comment]
**PASSED** 

Steps to Validate: 

1. Go into dispatch as a casworker establishing a claim. 
2. On the review decision page, the bottom of the page revealed the "Send to RO" link had been removed and the "Cancel" link re-positioned. 

Screenshots: 
<img width="1204" alt="screen shot 2017-01-23 at 2 16 27 pm" src="https://cloud.githubusercontent.com/assets/23038505/22218912/c2cb2cd2-e176-11e6-955d-6a5d7171c79d.png">
