### ISSUE TITLE
EP routing for legacy and AMA

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6903]
Caseflow Dispatch currently creates EPs (when they can) and routes them to particular ROs for Board grants and partial grants depending on if there are special issues or not. There are quite a few special issues that require emails to be sent, because the AOJs adjusting the claim do not use VBMS - these are most commonly other business lines like VHA, NCA, Fiduciary, etc.

We want to know if this routing should be updated for AMA appeals, and correct it for legacy appeals as well.

# AMA
**Open questions:**
- Dayna said just SeaTac and St. Pete, Josh says all three DROCs SeaTac, St. Pete, and DC. Which is correct?
- [x] What else do we need to add to the EP in order for NWQ to apply it's routing rules?
   - Is what we're doing in Caseflow Dispatch enough?
   - Are Corp DB flashes enough?
- Will all flashes already be there for the Veteran? Can we assume that? (We have an endpoint to read out the flashes on a Veteran)
- What business line does Waiver of Overpayment correspond to?
- Where do `Foreign pension, DIC - Mexico, Central and South America, Caribbean` and `Foreign pension, DIC - all other foreign countries` go through NWQ Station 499 or to the PMC ROs depending on region - PMC: RO81 - Philadelphia PMC, RO82 - Milwaukee PMC, or RO83 - St. Paul PMC depending on region 

### Appeals without Special Issues
- All Board Grants (compensation and pension management center (PMC)) are routed to DROCs - SeaTac (Station 346) or St. Pete (Station 317) via the NWQ (Station 499)
    - Note: We would like to create new station numbers for DROCs SeaTac and St. Petersburg but for now we are using the codes of the existing RO.
     - **Note: Josh said all 3 DROCs, including DC, while Dayna just said SeaTac and St. Pete**
- NWQ can distinguish Pension EPs because of their claim label
- NWQ can distinguish DTA errors because of their claim label
- We have to add a contention to each EP to chain issues

#### Comp & Pen --> Creating VBMS EPs
Special Issue Name |Routing logic for Board Grants
--- |---
Incarcerated Veterans | Caseflow relies on there being an `Incarcerated` Flash on the Veteran. NWQ sees this flash and routes accordingly. 
Non-rating issue | Use Board Grant Non-Rating EP codes for comp and pen
Private Attorney or Agent | Caseflow relies on there being `Private Attorney - Fee PayablePrivate Attorney - No Fee Payable` Flash
Radiation | 323-Jackson Radiation<br> - Contention Special Issue: Radiation Radiogenic Disability Confirmed
Rice Compliance | Routed the same as normal Board Grant EPs (via NWQ to DROCs)
Spina Bifida | Routed the same as normal Board Grant EPs (via NWQ to DROCs)
Vocational Rehab | Separate Benefit Type, task created for Voc Rehab business line in Caseflow
Restricted Access | Caseflow relies on there being a `Restricted Access` flash for routing
Contaminated Water at Camp LeJeune | 327-Louisville CLCW<br>- Contention Special Issue: Environmental Hazard - Camp Lejeune – Louisville
Foreign claim - compensation claims, dual claims, appeals | 311-Pittsburgh Foreign<br>- Flash: Foreign Claim (this should already be there for the Veteran)
Mustard Gas| Caseflow relies on the `Mustard Gas` flash
U.S. Territory claim - American Samoa, Guam, Northern| Caseflow relies on NWQ looking at the Veteran's zip code
Mariana Islands (Rota, Saipan & Tinian) |Caseflow relies on NWQ looking at the Veteran's zip code
U.S. Territory   claim - Philippines| Caseflow relies on NWQ looking at the Veteran's zip code
U.S. Territory   claim - Puerto Rico and Virgin Islands| Caseflow relies on NWQ looking at the Veteran's zip code
Foreign pension, DIC - Mexico, Central and South America, Caribbean | using PMC EPs + labels, Caseflow relies on NWQ looking at the Veteran's zip code
Foreign pension, DIC - all other foreign countries | using PMC EPs + labels, Caseflow relies on NWQ looking at the Veteran's zip code
Pension - United States | using PMC EPs + labels, going through NWQ Station 499
DIC - death, or accrued benefits - United States |using PMC EPs, going through NWQ Station 499

**Note:**
- Any EP with a Contention Special Issue, we need to know the Special Issue at the issue level not at the appeal level (like we have it today)
- We should automatically discover/determine/reveal special issues for some of these - can be at outcoding (or earlier if we think users want to see it)

#### Non-Comp & Pen --> Creating Caseflow tasks
- Current strategy is for non-comp business lines to have Caseflow and queues
- Caseflow will create tasks in non-comp business lines 
- Can identify non-comp business lines by `Benefit type` field currently inputted in Caseflow Intake

Special Issue Name | Routing |
--- |---
Education - GI Bill, dependents educational assistance | Create Caseflow task in Education
Home Loan Guaranty | Create Caseflow task 
Insurance | Create Caseflow task 
National Cemetery Administration | Create Caseflow task 
VAMC | Create Caseflow task 
Waiver of Overpayment | ???
Scholarship, transfer of entitlement | Create Caseflow task for education

---
# Legacy 

## Appeals without special issues
- EPs routed to AMO

## Appeals with special issues
- Caseflow Dispatch currently defines 3 tiers - ROJ, specialized RO, non-VBMS

### Legacy
Special Issue Name | Create EP? | Specific RO or   Original RO - station of jurisdiction | VBMS RO key | RO location
-- | -- | -- | -- | --
Hearing - including travel board & video conference | Yes | Original RO - station   of jurisdiction | varies | varies
Incarcerated Veterans | Yes | Original RO - station   of jurisdiction | varies | varies
Manlincon Compliance | Yes | Original RO - station   of jurisdiction | varies | varies
Non-rating issue | Yes | Original RO - station   of jurisdiction | varies | varies
Private Attorney or Agent | Yes | Original RO - station of jurisdiction | varies | varies
Radiation | Yes | Original RO - station   of jurisdiction | varies | varies
Rice Compliance | Yes | Original RO - station   of jurisdiction | varies | varies
Spina Bifida | Yes | Original RO - station   of jurisdiction | varies | varies
Vocational   Rehab | Yes | Original RO - station   of jurisdiction | varies | varies

#### Tier 2: Create EP at specialized RO

Special Issue Name | Create EP? | Specific RO or   Original RO - station of jurisdiction | VBMS RO key | RO location
-- | -- | -- | -- | --
Contaminated Water at Camp LeJeune | Yes | Specific RO | 327 | Louisville,   KY
Foreign claim - compensation claims, dual claims, appeals | Yes | Specific RO | 311 | Pittsburgh,   PA
Mustard Gas | Yes | Specific RO | 351 | Muskogee,   OK
U.S. Territory claim - American Samoa, Guam, Northern | Yes | Specific RO | 459 | Honolulu,   HI
Mariana Islands (Rota, Saipan & Tinian) | Yes | Specific RO | 459 | Honolulu,   HI
U.S. Territory   claim - Philippines | Yes | Specific RO | 358 | Manila,   Philippines
U.S. Territory   claim - Puerto Rico and Virgin Islands | Yes | Specific RO | 355 | San   Juan, Puerto Rico

#### Tier 3: No EP in VBMS
- Send emails until Caseflow for non-comp business lines 

Special   Issue Name | Create EP? | Who/RO (VACOLS   RO code) | Email address
-- | -- | -- | -- 
DIC - death, or accrued benefits - United States | No | PMC: RO81 -   Philadelphia PMC, RO82 - Milwaukee PMC, or RO83 - St. Paul PMC depending on   region | See PMC jurisdiction list
Education - GI Bill, dependents educational assistance | No | RO91   - Buffalo Education Center, RO93 - Muskogee Education Center, or RO94 - St.   Louis Education Center, depending on region, see education jurisdiction | See   Education jurisdiction list
Foreign pension, DIC - Mexico, Central and South America, Caribbean | No | RO83   - St. Paul PMC | AppealsPMC.VAVBASPL@va.gov, Hillary.Hernandez@va.gov
Foreign pension, DIC - all other foreign countries | No | PMC:   RO81 - Philadelphia PMC, RO82 - Milwaukee PMC, or RO83 - St. Paul PMC   depending on region | See   PMC jurisdiction list
Home Loan Guaranty | No | RO88   - Atlanta HLG Center | jennifer.Tillery@va.gov
Insurance | No | RO80   - Philadelphia Insurance Center | nancy.encarnado@va.gov
National Cemetery Administration | No | RO98   - NCA | richard.byersII@va.gov
Pension - United States | No | PMC:   RO81 - Philadelphia PMC, RO82 - Milwaukee PMC, or RO83 - St. Paul PMC   depending on region | See   PMC jurisdiction list
VAMC | No | RO99   - VHA CO | Travis.Richardson@va.gov'
Waiver of   Overpayment | No | RO84   - Philadlephia COWC, RO85 - Milwaukee COWC, or RO86 - St. Paul COWC | See   COWC jurisdiction list
Scholarship, transfer of entitlement | No | RO91   - Buffalo Education Center, RO93 - Muskogee Education Center, or RO94 - St.   Louis Education Center, depending on region, see education jurisdiction | See   Education jurisdiction list

---
# EPs

### AMA
 EP | Claim Label
-- | -- 
030BGR | Board Grant Rating 
030BGNR | Board Grant Non-Rating 
040BDE | Board DTA Error
040BDEIMO | Board DTA Error with IMO
030BGRPMC | PMC Board Grant Rating 
030BGNRPMC | PMC Board Grant Non-Rating 
040BDEIMOPMC | PMC Board DTA Error - w/IMO
040BDEPMC | PMC Board DTA Error 

### Legacy
 EP | Claim Label 
-- | -- | -- | --
070BVAGR | BVA Grant (070) 
070BVAGRARC | ARC BVA Grant 
070BVAGRPMC | PMC BVA Grant (070) 
070RMND | 070RMND
070RMNDARC | ARC Remand (070) 
070RMNDPMC | PMC Remand (070) 
070RMNDBVAG | Remand with BVA Grant (070)
070RMBVAGARC | ARC Remand with BVA Grant
070RMBVAGPMC | PMC Remand with BVA Grant

---
### Notes/tracking from update process
This is the original spreadsheet sent to AMO:
[EP routing and claim adjustment questions_09052018.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2371629/EP.routing.and.claim.adjustment.questions_09052018.xlsx)

### Questions asked to AMO
- [x] Do all end products for AMA appeal grants without special issues continue to be routed to AMO? Legacy appeals?
    - Legacy - yes, ARC
    - AMA Grants go to DROCs - DC, Seattle, St. Petersburg, FL
    - [ ] what are the station numbers? ask Dayna
    - [ ] How are grants distributed among DROCs? Equally?
            - has to be talked out by the Ops team - need to talk with Dayna, John Shriver, Mike Edsall** action
- [ ] Is our special issues VBMS EP or non-VBMS routing methodology still correct for legacy appeals? 
    - Mirror routing rules for legacy appeals for routing for AMA. Anything that would go for priority routing remains with the station. NWQ does Routing rules- Josh Will- NWQ routes once they are picked?
- [ ] How should AMA appeal   grants with special issues be routed?
    - NWQ routing?
- [x] Are any more special issues   no longer relevant under AMA?
    - no
- [x] What special issues are not relevant to Compensation appeals (and are therefore not eligible for RAMP appeals pilot)?
    - Vocational Rehab
    - DIC - death, or accrued benefits - United States
    - Education - GI Bill, dependents educational assistance
    - Foreign pension, DIC - Mexico, Central and South America, Caribbean
    - Foreign pension, DIC - all other foreign countries
    - Home Loan Guaranty
    - Insurance
    - National Cemetery Administration
    - Pension - United States
    - VAMC
    - Waiver of Overpayment
    - Scholarship, transfer of entitlement
- [ ] Are these email addresses correct for AMA and legacy appeals?
- [ ] What ROs should adjust Pension Management Center claims, since AMA appeals don't originate at ROs? Are these emails still correct for legacy appeals?
- [x] What ROs should adjust Education claims, since AMA appeals don't originate at ROs? Are these emails still correct for legacy and AMA appeals?
    - RO91 - Buffalo Education Center - 307
        - Sharon.Judson@va.gov
        - edu.vbamus@va.gov
    - RO93 - Muskogee Education Center - 351
        - dawn.arnold@va.gov
        - edu.vbamus@va.gov
    - RO94 - St. Louis Education Center - 331
        - Kristy.Scott@va.gov
        - edu.vbamus@va.gov
- [x] What ROs should adjust COWC claims, since AMA appeals don't originate at ROs? Are these emails still correct for AMA and legacy appeals?
    - 330 COWC Chairperson John Guion john.guion@va.gov
    - 331 COWC Chairperson Elmer Linzie elmer.linzie@va.gov

**Comment by laurjpeterson** [comment]
Response from AMO:

[EP routing and claim adjustment questions_09072018 (002) AMO Edits.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2371635/EP.routing.and.claim.adjustment.questions_09072018.002.AMO.Edits.xlsx)

**Comment by laurjpeterson** [comment]
EDU RO POCs

See below.  Please note that the POCs have changed.


RO91

Buffalo Education Center

307

RO91

Sharon.Judson@va.gov<mailto:Sharon.Judson@va.gov>

edu.vbamus@va.gov<mailto:edu.vbamus@va.gov>

RO93

Muskogee Education Center

351

RO93

dawn.arnold@va.gov<mailto:dawn.arnold@va.gov>

edu.vbamus@va.gov<mailto:edu.vbamus@va.gov>

RO94

St. Louis Education Center

331

RO94

Kristy.Scott@va.gov<mailto:Kristy.Scott@va.gov>

edu.vbamus@va.gov<mailto:edu.vbamus@va.gov>

**Comment by laurjpeterson** [comment]
Follow-up Questions to ask Caitlin:
1. **Original question** -  Do all end products for AMA   appeal grants without special issues continue to be routed to AMO? Legacy   appeals?
   - **Original answer** - AMA Grants go to DROCs. Legacy grants continue to go to ARC.
   - **Follow-ups:**
       - What are the DROCs and their associated VBMS station numbers? (DC, Seattle, and?)
       - How are grants distributed among DROCs? Equally?
2. **Original question** - Is our special issues VBMS   EP or non-VBMS routing methodology still correct for legacy appeals?
   - **Original answer** - Mirror routing rules for legacy appeals for routing for AMA. Anything that would go for priority routing remains with the station.  NWQ does Routing rules- Josh Will- NWQ routes once they are picked
   - **Follow-ups:** 
      - Can you clarify how we can mirror legacy routing rules for AMA while also satisfying NWQ routing?
3. **Original question** - How should AMA appeal grants with special issues be routed?
   - **Original answer** - according to NWQ routing

---
4. **Original question** - Are any more special issues no longer relevant under AMA?
   - **Original answer** - No
5. **Original question** - What special issues are not relevant to Compensation appeals (and are therefore not eligible for RAMP appeals pilot)?
   - **Original answer** - see: https://github.com/department-of-veterans-affairs/caseflow/issues/6854#issuecomment-420416824

**Comment by laurjpeterson** [comment]
You can find finance POCs here<https://vbaw.vba.va.gov/orm/fin/field_poc.asp>.

330 COWC Chairperson John Guion john.guion@va.gov

331 COWC Chairperson Elmer Linzie elmer.linzie@va.gov

**Comment by laurjpeterson** [comment]
Below is the list of attributes applied to a special mission claim to properly identify and route.   

 

311-Pittsburgh Foreign

Flash: Foreign Claim
 

323-Jackson Radiation

Special Issue: Radiation Radiogenic Disability Confirmed
 

327-Louisville CLCW

Special Issue: Environmental Hazard - Camp Lejeune – Louisville
 

335-St. Paul RACC (Restricted Access Claim Center)

Flash: Restricted Access
 

 

Further discussion will be needed with the AMO on how to identify Appeals for IDES claims as currently IDES claims for the VSC are identified using the below claim labels. 

304-Providence IDES

Claim Label:
Rating claims: DES Initial Comp 8 +/ Pension Dual Claim, DES Initial Compensation 8 + Issues, DES Initial Live Comp < 8 Issues, DES Initial Live Comp/Pension, DES Supplemental 8+ Issues, DES Supplemental < 8 Issues, IDES Rating - Proposed, IDES Reconsideration Request - Active Duty, IDES Reconsideration Request - Not on AD
Non-Rating claims: DRAS Dependency, DRAS Automobile Allowance, DRAS Clothing Allowance, DRAS CRSC/CRDP Processing, DRAS Character of Discharge, DRAS Eligibility Determination, DRAS Military Pay in Lieu of Comp, DRAS Return to Active Duty, DRAS Retired Pay Waiver/Election, DRAS Special Home Adaptation, DRAS Specially Adapted Housing, DRAS Vehicular Adaptive Equipment, DRAS Predetermination Notice, IDES Proposed Rating, DRAS Incompetency Determination and
Most Recent Branch of Service: Air Force, Air Force Reserves, Marine Corps, Marine Corps Reserves, Navy, Navy Reserves, Air National Guard
346-Seattle IDES

Claim Label:
Rating claims: DES Initial Comp 8 +/ Pension Dual Claim, DES Initial Compensation 8 + Issues, DES Initial Live Comp < 8 Issues, DES Initial Live Comp/Pension, DES Supplemental 8+ Issues, DES Supplemental < 8 Issues, IDES Rating - Proposed, IDES Reconsideration Request - Active Duty, IDES Reconsideration Request - Not on AD
Non-Rating claims: DRAS Dependency, DRAS Automobile Allowance, DRAS Clothing Allowance, DRAS CRSC/CRDP Processing, DRAS Character of Discharge, DRAS Eligibility Determination, DRAS Military Pay in Lieu of Comp, DRAS Return to Active Duty, DRAS Retired Pay Waiver/Election, DRAS Special Home Adaptation, DRAS Specially Adapted Housing, DRAS Vehicular Adaptive Equipment, DRAS Predetermination Notice, IDES Proposed Rating, DRAS Incompetency Determination and
Most Recent Branch of Service: Army, Army National Guard, Army Reserves
 

 

Respectfully

 

Joshua Will

Supervisory Lead Management Analyst

National Work Queue, Department of Veterans Affairs

**Comment by laurjpeterson** [comment]
From Dayna Ribnikar, AMO Ops, 11/6:

AMA Board Grant EPs will be routed to DROCs SeaTac and St. Petersburg – DC will not receive these cases. Distribution of such cases will occur via NWQ and will be based on capacity at St. Pete and SeaTac.

Station Numbers are:
SeaTac – 346
St. Petersburg – 317

We would like to create new station numbers for DROCs SeaTac and St. Petersburg but for now we are using the codes of the existing RO.

---

Essentially, yes – EPs will be created via Caseflow Intake and each night NWQ will recall all newly created EPs into 499. From there, based on the rules we set up and the priorities dictated, NWQ will distribute cases daily to SeaTac and St. Pete.

**Comment by laurjpeterson** [comment]
@aroltsch - next step is for @shanear and I to meet with Josh Will from NWQ to hammer out the details we don't know above for AMA appeal EP routing.

**Comment by shanear** [comment]
We got a response from Josh!




Type of claim | Flash | Board Grants will Route to | Comments |  
Incarcerated Veterans | Incarceration | None | Please let us know which station(s) you would like the claims routed to. We currently route these claims to specific stations for non-rating claims and can mirror those stations for appeals. |  
Private Attorney/Agent | Private Attorney - Fee PayablePrivate Attorney - No Fee Payable | Local RO | We currently route these claims to specific stations for rating and non-rating claims, which route to the local RO, and can mirror those stations for appeals. |  
 
Mustard Gas | Mustard Gas | Muskogee RO | Please let us know if you want to change current routing |  
U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian) | None required | Honolulu RO | We use country/zip codes from the Veteran’s address.  Please let us know if you want to mirror rating and non-rating and route to RO459- Honolulu |  
U.S. Territory claim – Philippines | None required | Manilla RO | We use country/zip codes from the Veteran’s address.  Please let us know if you want to change current routing |  
U.S. Territory claim - Puerto Rico and Virgin Islands | None required | San Juan (RAMP claims are currently going to St Petersburg as requested by OPS until San Juan gets training) | We use state codes from the Veteran’s address.  Please let us know if you want to change current routing |  
Foreign pension, DIC - Mexico, Central and South America, Caribbean | None required | PMCs | We use country codes from the Veteran’s address.  Existing claim labels:EP682 PMC-Reviews – Rating Involved 2EP683 PMC-Reviews – Rating Involved 3Would route to PMC unless you want them routed differently.Additionally, if you will be creating new claim labels please let us know* |  
Foreign pension, DIC - all other foreign countries | None required | PMCs |  
  |   |

**Comment by shanear** [comment]
> Are VBMS flashes on Veterans or on EPs?

Veteran. Confirmed with nate.
