### ISSUE TITLE
Receipt date allows invalid dates

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6931]
## Story
When a user is selecting a receipt date, they can enter a date of 17/33/2018 and it passes the date validation

![Screen Shot 2018-09-12 at 2.17.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9b7c9e7d70200133c2088/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f16b7191a37af1132c4f5b5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a29941c95df54de64a5dac12306be6712431.png)

## Acceptance criteria
If a user tries to enter a receipt_date that is not valid, they should get an error telling them to enter a valid date.

Related:
https://github.com/department-of-veterans-affairs/caseflow/issues/10714

**Comment by Sjones352** [comment]
I validated this issue and the decision_date for non-rated issues with an invalid date still lets you create an Ep.
![Screen Shot 2019-05-14 at 4.08.55 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/9440e889-2129-4507-8691-f9b9a9252587)
![Screen Shot 2019-05-14 at 4.10.33 PM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/e4b96675-9fa3-4acc-b53a-ae9d18d01a09)

**Comment by leikkisa** [comment]
@Sjones352 We have another ticket now for the non-rating issue decision date:
https://github.com/department-of-veterans-affairs/caseflow/issues/10714

So I'll remove that from this ticket's description, and this one can be just for the receipt date.  It is possible the receipt date has been fixed since this ticket was open since it's pretty old and I think this issue was causing some Sentry errors.
