### ISSUE TITLE
RELEASE DEC 9: Add user ID to establish_claim and create_contentions

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6938]
## Story
There's an issue where a VBMS claim gets rolled back, but the BGS claim is still being created.  Right now when we create a claim, the user is listed as efolder_express.  We would like to send the actual user ID of the person logged into Caseflow, for both establish_claim and create_contentions, because these two calls use external domains.

VBMS needs to develop the functionality for this, and then provide documentation on how to send the data in the calls.

## Acceptance criteria
- establish_claim call to VBMS includes the user_id of the person logged into Caseflow
- create_contentions call to VBMS also includes the user id
- remove_contention call to VBMS should use the user id of the system user

## Technical Notes
- This should  be toggleable by a feature flag.

This can be done by adding the following user information to the VBMS security header:

```
  <soapenv:Header>
  	<ext:Security xmlns:ext="http://vbms.vba.va.gov/external">
		<ext:cssUserName>nherro_ssuper</ext:cssUserName>
		<ext:cssStationId>317</ext:cssStationId>
		<ext:SecurityLevel>9</ext:SecurityLevel>
	</ext:Security>
  </soapenv:Header>
```

We will likely need to modify `VBMS::Requests::EstablishClaim`, `VBMS::Requests::CreateContentions`, and `VBMS::Requests::RemoveContention` to take in a user object so the information can be injected into the header.

**Comment by shanear** [comment]
Nathan says this should be ready to go

**Comment by shanear** [comment]
Next steps are to reach out to Nate/Joe about how to pass the information, and how we can test that on UAT.

**Comment by leikkisa** [comment]
I sent them a message to ask about this

**Comment by leikkisa** [comment]
From Joe today:
This work isn’t complete, the plan is to make available, during establishClaim and createContentions, and user and station number field that we can then pass through to BGS. Once this work is complete we will include some documentation/examples regarding how it will work from the CASEFLOW side

**Comment by shanear** [comment]
This should be released to UAT by 10/8, instructions should have been sent from Joe on how to use that service.

**Comment by leikkisa** [comment]
Here's how the headers should look:
```
<ext:Security xmlns:ext="http://vbms.vba.va.gov/external">
                <ext:cssUserName>nherro_ssuper</ext:cssUserName>
                <ext:cssStationId>317</ext:cssStationId>
                <ext:SecurityLevel>9</ext:SecurityLevel>
</ext:Security>
```
After it's been tested, we should let VBMS know so that they can switch it on.

**Comment by leikkisa** [comment]
Adding this comment from Joe: 

I'm wondering if it would be possible to add these headers to all calls to the VBMS Claim Service? That may give a better perspective of the user is that is affecting the claim - since the point for BGS is to log which USER_XXXX created/updated a claim, contention, etc. Unless of course those are system-actions rather than user-actions then maybe that'd be a different scenario.

**Comment by jiahuang** [comment]
I have a branch https://github.com/department-of-veterans-affairs/connect_vbms/pull/206 that adds the correct header however there is a blocking issue in that the logged in user on caseflow needs to already have a vbms account for this header to work.

**Comment by shanear** [comment]
A couple things:

1) Any removal of contentions should happen via the [system user](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/user.rb#L276), because we don't want to rely on the user having the ability to remove contentions.

2) EPs created as part of HLR or SC intake should use the user that intook them.

3) EPs created by Caseflow Dispatch should use the user that performed the dispatch `EstablishClaim` task. (if that's a heavy lift we can use the system user for now)

**Comment by shanear** [comment]
Another thing, need to make sure our prod system user has the appropriate permissions

**Comment by shanear** [comment]
<img width="769" alt="screen shot 2018-10-26 at 5 39 14 pm" src="https://user-images.githubusercontent.com/1596259/47593708-46966680-d946-11e8-84dc-bf8672577ec5.png">

It looks like it's establishing the EP in the station of the user, which I don't think is correct 🦍... Will need to ask VBMS about this.

**Comment by shanear** [comment]
Works for intake 👍 

Need to test for dispatch. Getting in touch with @Sjones352 to help.

**Comment by shanear** [comment]
Validated with dispatch 👍 

I think we're ready to move forward with a plan to go to prod

**Comment by kencheeto** [comment]
Test by flipping feature flag by hand, then open a pr to appeals-deployment if successful

**Comment by shanear** [comment]
this is failing in prod 😢

```
An error occurred while establishing the claim: Client received SOAP Fault from server: ID: FB5E2F7E-2716-4BC8-94CE-937315A6C515: The required external domain headers ExternalUID or ExternalKey were missing or empty
```

**Comment by shanear** [comment]
```
irb(main):002:0> FeatureToggle.enabled?(:claims_service_v5)
=> false
```

This is probably why...

**Comment by leikkisa** [comment]
That makes sense. Is V5 ready to be enabled?

**Comment by shanear** [comment]
Turning `:claims_service_v5` on today

**Comment by shanear** [comment]
Turned both feature flags on today, and we are still getting an error 😢 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3035/

**Comment by shanear** [comment]
Alright, looks like it might be an issue with VBMS/BGS. Reached out to Joe from VBMS and he's looking into it.

**Comment by shanear** [comment]
Confirmed with Joe, that there is a missing property on the VBMS side. They are turning it on but need approvals, they'll let me know when it's turned on.

**Comment by leikkisa** [comment]
I turned this off in UAT too, because it was giving Sandra issues (and she's confirmed that turning it off fixed things). So there might be something more we need to look at if we thought it was working in UAT before.

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1056/

**Comment by leikkisa** [comment]
Shane turned this on for both Prod and UAT, now we are waiting for the week to see if there are any failures as a way of validating.

**Comment by shanear** [comment]
turned this on and it appears to be working. We'll check back in in a week.

**Comment by shanear** [comment]
This has been working for a week in prod
