### ISSUE TITLE
Editing VBA Issues | Re-associate rated issues on edit issues

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#6939]
## Story
When a claim review is edited, and issues are added or removed, the entire map for associate_rated_issues needs to be re-sent.  It will replace the previous map.

## Acceptance Criteria
- When a claim review is edited successfully (meaning issues were either added or removed), and contentions were added or removed to any EPs connected to that claim review, Caseflow should call the VBMS request to associate all contentions to rated issues for each EP on the claim review.

## Technical Notes
- There is no logical problem with sending the same data to AssociateRatingIssues twice (it will just affect performance).

## Validation
- Edit a claim_review issues
- Check with VBMS that the new rated issue map matches the new issues selected

**Comment by shanear** [comment]
RemoveContentions is not working with the permissions VBMS gave our system user. This is blocked until we fix that 😞

**Comment by shanear** [comment]
Confirmed this is working with Joe 👍
