### ISSUE TITLE
Retry failed VBMS requests for HLR and SC establishments

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6942]
Once we begin processing VBMS requests for HLR and SC establishments asynchronously, we will need a way to retry them when they fail.

## Acceptance Criteria
- When any part of the VBMS establishment for an HLR or SC fails, a job should periodically attempt to retry processing them.
- An HLR or SC should be retried every 3 hours for 4 consecutive days. After that, it should no longer be retried.

requires #6941

**Comment by pkarman** [comment]
Moving the tasks to ActiveJob in #7111 will get us some automatic retries per https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/setting-up-a-caseflow-cron-job.md#step-1-implement-your-active-job

That only goes to a max of 5 hours though, so #7111 makes it possible to go for days instead.

However, for #6944 we need to capture the last error for any job so this ticket should be scoped to:

* rescue from any exceptions
* capture and save the error message
* re-throw the exception to trigger retry

**Comment by pkarman** [comment]
looks like it re-ran with no error:
```
> puts hlr.pretty_inspect
#<HigherLevelReview:0x0000558b2e78aca8
 id: 214,
 veteran_file_number: "123458312",
 receipt_date: Sun, 09 Sep 2018,
 informal_conference: false,
 same_office: false,
 establishment_submitted_at: Wed, 03 Oct 2018 22:21:21 UTC +00:00,
 establishment_processed_at: Thu, 04 Oct 2018 01:22:29 UTC +00:00,
 benefit_type: "compensation",
 establishment_attempted_at: Thu, 04 Oct 2018 01:22:01 UTC +00:00,
 establishment_error: nil>
=> nil
```

**Comment by shanear** [comment]
`pretty_inspect`! I'm totally gonna use that in the future lol


![screen shot 2018-10-05 at 5 35 31 pm](https://user-images.githubusercontent.com/1596259/46561313-13bbfe00-c8c5-11e8-8a3f-1a9701149155.png)
