### ISSUE TITLE
Update copy on HLR and SC success page to designate that the EP might not be created immediately

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6943]
Because we will be establishing EPs in VBMS in a separate job that may fail, or may take close to a minute to process, we should probably tell users that the EP "will be established shortly". 

We could also allude to the fact that if the EP does not show up they can attempt to reprocess it and add a button to allow them to do that?

**Comment by suzchap** [comment]
@shanear can you say more about the second part? How much is this needed? Would the button only be there if the EP failed/is delayed or would it always be there? If it's always there, I can imagine people might just automatically click it every time.

**Comment by shanear** [comment]
subsumed by https://github.com/department-of-veterans-affairs/caseflow/issues/7303 and https://github.com/department-of-veterans-affairs/caseflow/issues/7313
