### ISSUE TITLE
Check for long addresses as part of validating veterans

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6947]
BGS does not allow veterans to have addresses with `address_line_1` greater than 20 characters. We should be validating that before the intake begins and adding an appropriate error message.

## Acceptance Criteria
- When searching for a veteran in any intake flow, check to see if the veteran's `address_line_1` is greater than 20 characters. If it is, show the following error message (in the same style as other error messages on this page):
 
> This Veteran's address is too long. Please edit it in VBMS or SHARE so each address field is no longer than 20 characters (including spaces) then try again.

> Tips:
> 
> Do: move end of address to additional address fields (address 2 & 3)
> Do: abbreviate to St. Ave. Rd. Blvd. Dr. Ter. Pl. Ct.
> Don't: edit street names or numbers

## Technical notes
- We can also remove the check and handling of `Caseflow::Error::LongAddress` from the complete page.

## Validation
1. Find a veteran with an address_line1 (or address_line2/3) that is longer than 20 characters
1. Attempt an intake with this veteran - there should be an error displayed with instructions to update their address in VBMS or SHARE.

**Comment by shanear** [comment]
Suzanne: talk to ARC or AMO about techniques to do this, and then write those in the message.

**Comment by shanear** [comment]
Also explore potentially automatic ways to fix this.

**Comment by abbyraskinUSDS** [comment]
AMO gave the OK to break these into multiple lines

**Comment by suzchap** [comment]
This Veteran's address is too long. Please edit it in VBMS or SHARE so each address field is no longer than 20 characters (including spaces) then try again. 
Tips:
- Do: use multiple address fields
- Do: abbreviate to St. Ave. Rd. Blvd. Dr. Ter. Pl. Ct.
- Don't: edit street names or numbers

Alt -- Do: abbreviate type of street (ex. Street -> St.)

**Comment by kencheeto** [comment]
I think I need some help again finding a veteran with a long address, but otherwise this will be merged in a bit and ready for validation.

**Comment by shanear** [comment]
I think we can just validate this one by making sure we don't see any `Caseflow::Error::LongAddress` errors. If we do we can always reopen this. That plus automated tests are good enough for me.

**Comment by nicholasholtz** [comment]
VA is beginning an effort to change VBA systems from 6x20 to 6x35. I do not have a projected date here.

> To enable Vet360 to be the authoritative source of Veteran contact information, VBA must work to remove all dependencies on the 6 line by 20 character address format and align with standard postal and Department of Treasury requirements used by VHA.  We are addressing most VBA dependencies by updating web services currently utilizing this format and updating the format to the validated 6 line by 35 character address format which is known as PAM.  

Per OBPI, BGS will implement this for the February CI.

**Comment by nicholasholtz** [comment]
@amprokop FYI

**Comment by kencheeto** [comment]
thanks, this will be easy and safe to change after BGS implements 6x35 support.
