### ISSUE TITLE
Select form page: copy and style changes

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6955]
## Story
Fine-tuning of content and styles.

## Acceptance criteria
- "Which form are you processing?" is coded as a form label
- "To get started, choose the form you are processing for intake." has been removed

## Copy
No new copy.

## Mocks
<img width="611" alt="screen shot 2018-09-13 at 12 36 46 pm" src="https://user-images.githubusercontent.com/11219417/45502686-9cc29800-b752-11e8-820b-0f146aee150e.png">

## How to Validate
- It's the first screen of intake so no test user needed.

**Comment by pkarman** [comment]
@suzchap it looks like from the mock image that you want the form label to be bold, which seems to be different than the styleguide shows form labels (with no extra font weight). Can you confirm?

**Comment by carolaponce** [comment]
@shanear what is the URL to review these? I figure there might be a prod URL or would it be Demo?

**Comment by suzchap** [comment]
LGTM

<img width="1105" alt="screen shot 2018-09-27 at 11 45 44 am" src="https://user-images.githubusercontent.com/11219417/46157966-e6c77580-c24a-11e8-96fa-bc226ea3bfc3.png">
