### ISSUE TITLE
Search page: copy and style changes

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6960]
## Story
Fine-tuning of content and styles.

## Acceptance criteria
- Label for search box is "Enter the Veteran’s ID"
- "Enter the Veteran’s ID" is coded as a form label

## Copy
- Enter the Veteran’s ID

## Mocks
<img width="610" alt="screen shot 2018-09-13 at 12 59 08 pm" src="https://user-images.githubusercontent.com/11219417/45503444-d72d3480-b754-11e8-9080-21731e3dfa36.png">

## How to Validate
- Select any AMA form to land on the Search page.

**Comment by suzchap** [comment]
<img width="1100" alt="screen shot 2018-09-27 at 12 07 07 pm" src="https://user-images.githubusercontent.com/11219417/46159277-e7154000-c24d-11e8-8ce7-7e35a77eb64a.png">

**Comment by carolaponce** [comment]
LGTM

**Comment by carolaponce** [comment]
Thank you @suzchap for walking me through these!
