### ISSUE TITLE
Design universal case title

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6963]
Quoting @laurjpeterson from from https://github.com/department-of-veterans-affairs/caseflow/issues/6650:

> We continue to see in our user research sessions that attorneys and judges spend the bulk of their time in Reader. How does this design translate, if at all, to Reader? I'm wondering if users could benefit from docket type being in the heading somehow for Reader, since the Claims folder details accordion isn't expanded when a user navigates to Reader. cc: @abbyraskinUSDS 

### Current case title and snanshot area in case details
<img width="1094" alt="screenshot 2018-09-13 14 11 36" src="https://user-images.githubusercontent.com/1598889/45507087-1ceefa80-b75f-11e8-98d2-64e20d8b4c00.png">

### Current Reader

<img width="1130" alt="screen shot 2018-08-29 at 7 52 48 pm" src="https://user-images.githubusercontent.com/27704093/44821742-358adc80-abc5-11e8-9de5-455be5f70c3c.png">

<img width="1119" alt="screen shot 2018-08-29 at 7 52 36 pm" src="https://user-images.githubusercontent.com/27704093/44821743-358adc80-abc5-11e8-8d5f-f9cb82def07f.png">

---

# [Draft] AC:
Case title should contain:
- Veteran name
- Veteran ID
- Docket number
- Link to Veteran's documents
- Link to view all cases
- TBD: any labels that are associated to the case

---

# Drafts for universal case title

These drafts come from collaboration / conversation between @sneha-pai @allyceh @laurjpeterson @mkhandekar in this mural: [Edit AOD: Sketches](https://app.mural.co/t/workqueue2001/m/workqueue2001/1536605643302/759a692551fff392640860e504d25842db09dec7)

![image](https://user-images.githubusercontent.com/1598889/45507253-8969f980-b75f-11e8-84c5-1068cb1f493e.png)

![image](https://user-images.githubusercontent.com/1598889/45507289-a6063180-b75f-11e8-951c-5f5b73afe2ba.png)

---

[See sketch file here](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/11a3978b1d6f318ccdbfc0d548a39c5c2e4cd90d/Design/Design%20Files/Example%20sketch%20files%20across%20our%20products/Case%20Details/Case%20Timeline%20v1.sketch).

@sneha-pai to continue on this work!

**Comment by mkhandekar** [comment]
Related: https://github.com/department-of-veterans-affairs/caseflow/issues/6005

**Comment by sneha-pai** [comment]
####
####
## Designs ready for your review
@laurjpeterson @allyce (for AOD view/edit implications) @joeyyang please view:
https://app.mural.co/t/workqueue2001/m/workqueue2001/1542168117930/97105573bccce4a9b87cff7579d08465efb1c9d7 

### Next steps
- please review the proposed designs in the mural.co link above, and add comments/questions as needed.
- Sneha to schedule a quick meeting to walk through designs and discuss any edits.

**Comment by sneha-pai** [comment]
@laurjpeterson @lowellrex @joeyyang 

Here are some questions to mull over in preparation for our chat later today. I'd prefer discussing these during our call as having a pre-discussion in slack will not work with my schedule. 

#### Questions:
- what technical concerns do you have, if any, with the proposed designs and their variations?
- Would we want to build this component all at once, or progressively? Do we need a leaner version to begin with?
- **[execution-related]** Case title component is isolated in this design ( and has it's own bounding box. Do we want to approach the Case Title component as a stand-alone container, or incorporate other case details into one larger container (like it is today)
-  **[product and effort-related]** More effort and big proposal to move AOD from being a "Type" to a Label. How do we feel about this?

**Comment by laurjpeterson** [comment]
2. I don't have a preference here. I will defer to engineers on order of implementation from a technical perspective. 
3. What are the pros/cons of each one? I could potentially defer this question too.
4. From a product/user perspective, I feel good about it. I think AOD will be just as visible in the design proposed as it is now, so I think it's good to move forward with.

**Comment by lowellrex** [comment]
1. Curious how we might handle some editing AOD situations (more in point 4).
2. It depends. If we can move faster by releasing segments of progress here then I think we should do that. If it is easy enough to do it all at once then I'm in favor of that
3. I'm not sure I understand what the distinction between stand-alone container vs part of a larger container is.
4. Two thoughts here.
    * First, what do folks at the Board (specifically the AOD team) think of the AOD indication as? Do they think of it as "type" of case? Or is it a label applied to a case? Can we get some sense of this from how VACOLS currently represents AOD cases?
    * Second, we need to make it clear to AOD users what the "edit" link allows them to do (change whether a case is AOD or not), so no matter how we change the design that relationship (clicking the "edit" link allows changing AOD status of a case) needs to be clear.

**Comment by allyceh** [comment]
@sneha-pai I added some design comment in black boxes on the Mural. 

@lowellrex : Per your question, "First, what do folks at the Board (specifically the AOD team) think of the AOD indication as? Do they think of it as "type" of case? Or is it a label applied to a case? Can we get some sense of this from how VACOLS currently represents AOD cases?", I think we could ask what attorneys, judges, and co-located (?) expect since they are the primary consumers of this information and AOD helps them understand whether a case is high priority or not.

**Comment by laurjpeterson** [comment]
continuing work here - https://github.com/department-of-veterans-affairs/caseflow/issues/7903 - so closing this issue.
