### ISSUE TITLE
Intake | Style change to make form labels bold

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6965]
## Story
CSS for all intake form labels should be bold (`<strong>`).

## Technical notes
This will require adding the `strongLabel` configuration to `SearchableDropdown`

## Acceptance criteria
- form labels display as bold (style is currently set to just regular, not bold). Note, not all text that's above a form field has been coded as a form label so these won't be affected but we will change those to form labels in other tickets.

## Notes
- Since we are short on design time, the engineer working on this issue should check what labels in intake are not bold.

## How to Validate
- We have labels on almost every page so I'm content if we validate that some that were not bold before, now are. One form that does have a proper form label but isn't bold, is the "Issue category" field that you can find by going to Higher-level Review form > search any ID > answer questions any way you want > on the Finish page, click "add issue". If "Issue category" is bold, consider this validated.

**Comment by suzchap** [comment]
This is waiting on me to add a list of all the places where a label needs to be bold.

**Comment by shanear** [comment]
Everywhere I've checked looks good!
