### ISSUE TITLE
AMA Intake | Create an "Add issues" landing page

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6966]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. This landing page will be their starting point. This will address a number of usability issues and set the stage for future additions to accommodate edge cases.  

## Technical notes
Even though we are no longer showing the old Add Issues UI, we will still be using parts of it in follow along stories (see https://github.com/department-of-veterans-affairs/caseflow/issues/6981 and https://github.com/department-of-veterans-affairs/caseflow/issues/6988) so it's probably good to keep a lot of the state structure and components around. The old feature tests can go though.

## Acceptance criteria
- After a user submits a review page, they are shown this "Add Issues" landing page. 
- "Complete intake" button is disabled
- "Cancel intake" link opens the cancel model (same as it works right now),
- "Add issues" button doesn't need to do anything yet (that will be in another ticket)
- The contents of the page show a summary of every field that was completed earlier in the process. Fields are displayed in the order that they appear in the intake flow and will vary for each form type as shown below.

## Copy
**NoD**
- Form ––––– `Form name (Form #)`
- Veteran –––– `Veteran Name (ID # XXXXXXXX)`
- Form receipt date –––– `MM/DD/YYYY`
- Review option –––– `Hearing`, `Direct Review`, or `Evidence Submission`
- Claimant –––– `if Claimant = veteran, display Veteran name; if Claimant = not Veteran, display Claimant name (payee code = XXXX)`
- Requested issues –––– `("+ Add issue" button only / no content for this ticket)`

**SC / Non-Comp**
- Form ––––– `Form name (Form #)`
- Veteran –––– `Veteran Name (ID # XXXXXXXX)`
- Form receipt date –––– `MM/DD/YYYY`
- Benefit type ––– `LoB selected`
- Requested issues –––– `("+ Add issue" button only / no content for this ticket)`

**HLR / Non-Comp**
- Form ––––– `Form name (Form #)`
- Veteran –––– `Veteran Name (ID # XXXXXXXX)`
- Form receipt date –––– `MM/DD/YYYY`
- Benefit type ––– `LoB selected`
- Informal conference –––– `Yes | No`
- Review by same office –––– `Yes | No`
- Requested issues –––– `("+ Add issue" button only / no content for this ticket)`

**SC / Comp**
- Form ––––– `Form name (Form #)`
- Veteran –––– `Veteran Name (ID # XXXXXXXX)`
- Form receipt date –––– `MM/DD/YYYY`
- Benefit type ––– `LoB selected`
- Claimant –––– `if Claimant = veteran, display Veteran name; if Claimant = not Veteran, display Claimant name (payee code = XXXX)`
- Requested issues –––– `("+ Add issue" button only / no content for this ticket)`

**HLR / Comp**
- Form ––––– `Form name (Form #)`
- Veteran –––– `Veteran Name (ID # XXXXXXXX)`
- Form receipt date –––– `MM/DD/YYYY`
- Benefit type ––– `LoB selected`
- Informal conference –––– `Yes | No`
- Review by same office –––– `Yes | No`
- Claimant –––– `if Claimant = veteran, display Veteran name; if Claimant = not Veteran, display Claimant name (payee code = XXXX)`
- Requested issues –––– `("+ Add issue" button only / no content for this ticket)`

## Mocks
Note: mock shows _all_ bits of content that may show but these would never all show at once so see Copy section for which show each. 
<img width="804" alt="screen shot 2018-09-14 at 9 23 56 am" src="https://user-images.githubusercontent.com/11219417/45552754-f2a14980-b7ff-11e8-9348-c800764bcba4.png">

## How to Validate
- Probably best to test with each AMA form and with variations on question selections.

**Comment by shanear** [comment]
This looks good.
![screen shot 2018-09-28 at 12 30 27 pm](https://user-images.githubusercontent.com/1596259/46221265-9d465b80-c31a-11e8-93c1-aa45a3412c6a.png)

When the claimant isn't the veteran, it's not showing up right:
![screen shot 2018-09-28 at 12 32 27 pm](https://user-images.githubusercontent.com/1596259/46221260-9a4b6b00-c31a-11e8-86f6-ff5965ba64cd.png)

**Comment by shanear** [comment]
![screen shot 2018-10-01 at 6 34 21 pm](https://user-images.githubusercontent.com/1596259/46319608-a6e4f300-c5a8-11e8-8f1f-35cf9764a2dd.png)
very nice very nice
