### ISSUE TITLE
Enable active state on sidebar

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#6977]
Currently, there is no indication within the side nav that the user has scrolled up/down case details. It would be helpful to create a visual indication and anchor for users to place where they are within case details, as they browse and are looking for items.

<img width="338" alt="screenshot 2018-10-10 10 10 12" src="https://user-images.githubusercontent.com/1598889/46754014-36a83280-cc76-11e8-9b55-1241eb3f2d79.png">

# AC

The hover state (dark gray) should turn into the the active state (the exact same dark gray) depending on what the user clicks or is currently viewing. 

- The active state should default to being active on "Issues" the top level nav item
- As a user is scrolling up/down case details, the active state should switch to different nav items, depending on what section the user is closest to.
- When a user clicks on different nav items, the active state should remain active until the user has scrolled up/down to a different section within case details.

<img width="578" alt="screenshot 2018-10-10 10 03 18" src="https://user-images.githubusercontent.com/1598889/46753092-bb458180-cc73-11e8-8cab-f36a9f98f951.png">

**Comment by jimruggiero** [comment]
@carodew For awareness, moving this to the design backlog.
