### ISSUE TITLE
AMA Intake | Clicking "Add this issue", and displaying added issues

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6982]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option. 

This ticket is for activating the "Add this issue" button that's on the rated issues modal (created in #6981) and how the issue displays on the "Add issue" page (created in #6966).

requires #6981

## Acceptance criteria
- clicking the "Add this issue" button on the rated issue modal closes the modal
- on the "Add issues" page, the previously selected rated issue and it's decision date are added to the "Requested issues" section.
- The issues listed are sequentially numbered and shown in the order they were created

## Notes
- Out of scope / in another ticket
   - Remove trash icon and link
   - Cancel link
   - "None of these..." button
   - Notes field

## Copy
- no new static copy

## Mocks
**With just one issue added**
<img width="599" alt="screen shot 2018-09-14 at 11 39 58 am" src="https://user-images.githubusercontent.com/11219417/45560382-eecaf280-b812-11e8-95ad-c2e30669055d.png">

**With two issues added**

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review, any answers > on "Add issue page, click "+Add issue" > on modal, select a rated issue > click "Add this issue" button > add another issue (so you can check numbering on Add issue page)
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by shanear** [comment]
![screen shot 2018-10-03 at 1 10 33 pm](https://user-images.githubusercontent.com/1596259/46426879-d3664f80-c70d-11e8-84f1-442a8f5e21ba.png)
looking good
