### ISSUE TITLE
AMA Intake | Modal specifications

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6984]
The modal should scroll to fit large lists of ratings/rating issues. The modal should be completely viewable on different screen sizes and the appropriate width.

## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

This ticket is to provide additional specifications for how the modal operate for all modal variations.

requires #6990 

## Technical notes
- Add a scenario where a veteran has a lot of ratings and rating issues to demo

## Acceptance criteria
- The entire modal should be viewable on different screen sizes. 
- All modals within the "Add issues" section should be the same size.
- When the modal has more content than can be seen, a scroll bar is added within the modal window.
- When the user scrolls within the modal, the page behind it does not scroll too.

## Copy
N/A

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review, any answers > on "Add issue page, click "+Add issue" to display modal to be tested, then also... > advance through the "None of these match" path to view the non-rated modal and Unknown issue modal.
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by suzchap** [comment]
This should be done after all modals have been created so they can all be validated as being a consistent size.

**Comment by leikkisa** [comment]
Sometimes Caseflow users open it on half of the screen

**Comment by leikkisa** [comment]
For reference, my Windows GFE has a screen resolution of 1366x768

**Comment by shanear** [comment]
Nice!
![screen shot 2018-10-26 at 1 03 58 pm](https://user-images.githubusercontent.com/1596259/47581560-afb6b380-d91f-11e8-829f-42b5e3fd9821.png)

**Comment by shanear** [comment]
responsive AF
