### ISSUE TITLE
AMA Intake | Add a notes field to the Rated Issues page

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6986]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

This ticket is for adding an optional notes field to the first modal for selecting rated issues (created in #6981).

requires #6981
requires #7000

## Technical notes
- Notes are stored in the database for the request issue

## Acceptance criteria
- User can add notes as optional.

## Notes
- There may be a character limit on contention text. We'll have to figure that out and put it in a follow up story

## Copy
- Notes
- Optional

## Mocks
<img width="760" alt="screen shot 2018-09-14 at 12 05 45 pm" src="https://user-images.githubusercontent.com/11219417/45561903-d65cd700-b816-11e8-8c7f-849ba9733d66.png">

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" to display modal > enter text in Notes field > click "Add this issue" (notes don't currently display anywhere so Dev will need to check that they were logged.
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by leikkisa** [comment]
I believe this requires #7000, since it requires saving to the database, so I am going to wait to continue working on it

**Comment by leikkisa** [comment]
@suzchap @carolaponce Should I be displaying the notes on the list of added issues?

**Comment by shanear** [comment]
```
[#<RequestIssue id: 301, review_request_type: "HigherLevelReview", review_request_id: 241, rating_issue_reference_id: "114209", rating_issue_profile_date: "2018-07-30 11:28:31", contention_reference_id: "307727", description: "Service connection for ptsd is granted with an eva...", issue_category: nil, decision_date: nil, disposition: nil, end_product_establishment_id: 159, removed_at: nil, rating_issue_associated_at: "2018-10-05 18:35:39", parent_request_issue_id: nil, notes: "Shane's notes">, #<RequestIssue id: 300, review_request_type: "HigherLevelReview", review_request_id: 241, rating_issue_reference_id: "114210", rating_issue_profile_date: "2018-07-30 11:28:31", contention_reference_id: "307728", description: "Service connection for Back is denied.", issue_category: nil, decision_date: nil, disposition: nil, end_product_establishment_id: 159, removed_at: nil, rating_issue_associated_at: "2018-10-05 18:35:39", parent_request_issue_id: nil, notes: "these are notes">]>
```

There they are 😄
