### ISSUE TITLE
AMA Intake | Cancel out of modal

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6987]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

When a user initiates adding an issue and opens a modal, they can cancel out of this action by clicking an X in the upper right of the modal or by clicking the "Cancel adding this issue" link.

requires #6981 

## Acceptance criteria
- On the Add issue modal, clicking the X in the upper right corner closes the modal to reveal the Add Issues Summary page with nothing changed.
- On the Add issue modal, clicking the "Cancel adding this issue" link closes the modal to reveal the Add Issues Summary page with nothing changed.

## Copy
N/A

## Mocks
<img width="526" alt="screen shot 2018-09-14 at 12 33 36 pm" src="https://user-images.githubusercontent.com/11219417/45563133-71a37b80-b81a-11e8-9c2e-ed0588547736.png">

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" to display modal to be tested > click X in corner to close modal. Repeat +Add issue to test closing using the link.
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by shanear** [comment]
<img width="569" alt="screen shot 2018-10-01 at 6 28 46 pm" src="https://user-images.githubusercontent.com/1596259/46319395-e7903c80-c5a7-11e8-95b7-81d792c6843b.png">
There's a link there.
It works. 
It just says the wrong thing 😮
Should say "Cancel adding this issue". Easy fix.

**Comment by shanear** [comment]
![screen shot 2018-10-03 at 1 09 23 pm](https://user-images.githubusercontent.com/1596259/46426792-913d0e00-c70d-11e8-926c-b39c65634099.png)
copy checks out
