### ISSUE TITLE
AMA Intake | Create "Unidentified Issue" modal and add entry to Add Issues Summary page

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#6990]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

When a user doesn't find a match for an issue written on the form with a non rated issue displayed on #6981 OR on the non-rated (#6988), they can click the "None of these match, see more options" button to advance to a new modal that displays "Unknown issue" options where they can transcribe the issue from the form and add optional notes. This content then shows on the Add Issue Summary page. 

requires #6988 

## Technical notes
- we will need to figure out the DB structure for this

## Acceptance criteria
- From the Add issue modal for non-rated issues, clicking the "None of these match, see more options" button moves to show another modal with a field to transcribe the issue as it's written on the form and an optional Notes field.
- "Add this issue" button is disabled until all the required fields are filled out.
- "Add this issue" button, when clicked, will close the modal, and the Add Issues summary page will now display the transcription and note (if there is one) in the "Requested issues" section.'' (it will be in harsh red)

## Notes
- don't worry about the contention text if you don't want to (it will be handled https://github.com/department-of-veterans-affairs/caseflow/issues/7010)
- Out of scope:
   - Dynamic issue ("Add issue 3") and numbering doesn't need to work yet, it'll be done in another issue.
- this will also be for edit.

## Copy
- Add issue modal
   - Describe the issue to mark it as needing further review.
   - Transcribe the issue as it's written on the form
   - Notes
   - Optional
- Add issue summary page
   - Unidentified issue: no issue matched for "[TRANSCRIPTION FIELD]"

## Mocks
**Add issue modal for unknown issues**
<img width="628" alt="screen shot 2018-09-14 at 1 06 05 pm" src="https://user-images.githubusercontent.com/11219417/45564651-1cb63400-b81f-11e8-821e-ec3b2a2b62f0.png">

**Add issues summary page**
<img width="716" alt="screen shot 2018-10-05 at 9 25 49 am" src="https://user-images.githubusercontent.com/11219417/46537981-b3a36880-c880-11e8-8ac4-a5bc51431230.png">

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" to display modal > click "None of these match" on the rated issues page > click "None of these match" on the non-rated issues page > view the unknown issues modal > fill in both fields > Click "Add this issue" > view Add issue summary page
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by steve-gov** [comment]
<img width="921" alt="screen shot 2018-10-15 at 2 41 15 pm" src="https://user-images.githubusercontent.com/25468689/46980158-92185d00-d088-11e8-9810-34bbf11dab03.png">

Validation curiosities:
1. Empty "decision date" field renders any time a new issue is added; see all three added lines of the screenshot.
2. Field should have basic validation to ensure data integrity; in the third line of the screenshot, a single whitespace was accepted as a valid issue.

**Comment by shanear** [comment]
<img width="599" alt="screen shot 2018-10-16 at 7 30 59 pm" src="https://user-images.githubusercontent.com/1596259/47053236-07178f80-d17a-11e8-9b40-80b00f0cf44b.png">
yay! both of these issues were fixed
