### ISSUE TITLE
Search & AMA Flow Questions for Queue Team

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#6991]
Use this issue for tracking all questions for Queue team related to Search for 1 pm Monday 9/17 sync.

Agenda
- Questions related to Caseflow Search 
- Questions related to AMA flow 

Caseflow Search
- Related ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/6878 

AMA Flow
- For AMA appeals, what flow patterns are replacing VACOLS locations? 
- How much is queue doing to streamlining for AMA flows? Does it look much different (less steps, locations, etc) than what happens in VACOLS today? 
- Based on your knowledge of the Hearings flow, what would you recommend we do for an AMA flow through the Hearings Management Branch? 
- How does the hearings AMA flow fit within the overall Queue AMA flow?

**Comment by MeredithStewart** [comment]
Related old thread for AMA flow for hearings: https://dsva.slack.com/archives/C42P25D6H/p1522765065000820

**Comment by oscarAtNava** [comment]
1. What attributes does search cover? ssn?, name? case id? vacols id? Others?
2. Is the result set that search returns designed in a way where we can add to it without affecting others? That is inheritance, overriding, overloading?
3. What authorizations are required to search?

**Comment by MeredithStewart** [comment]
**Notes from 9/17**  

- Search is on queue table/homepage, but not 
- Attributes on current search -- ONLY Veteran ID - 1 ID, 4 names for it
- Future state: Could allow other IDs, other attributes, but not currently planned  
- Have not implemented Name search (current users are copying and pasting Veteran ID from other sources) 
- If they don't have a Veteran ID (would still be able to search for legacy in VACOLS and for all in VBMS) 
- Global Search, regardless of the user. It's one search for everyone, just changes to who can see it or not 
- Queue isn't planning to put search in the header
- Search bar is its own component 
- Search results page sends you to a task page that sends you cases + some number, list of results send you queue app 
- Default for search results page? 
- It should be doable -- to add hearings details in results
- Put global search in the header? Should be doable, just have it been putting off 
- Authorizations required to search: Right now, any of the roles we have can search. Except VSOs who have a CSEM function (1 bucket of access permissions).  

**Options for Path Forward:** 
- If we can add the two columns to search, then we can move it to the the header (Foxtrot does work)  
- Or we customize search results for hearings and keep it off the header. (After April, we could move to Header)  
- @Chingujo -- Discuss with Sneha to see if we can add the two columns we need to the case search results.  
- Open Questions: For VSO & RO Views, should we customize the results of Veterans to only show their Veterans. We wouldn't customize the results. Should we include case details? 
- VSOs will need an initial list of their Veterans -- Queue is already getting this to VSOs.

**Comment by MeredithStewart** [comment]
Related Tickets: 

- https://github.com/department-of-veterans-affairs/caseflow/issues/6650
- https://github.com/department-of-veterans-affairs/caseflow/issues/6111
- https://github.com/department-of-veterans-affairs/caseflow/issues/5436

**Comment by MeredithStewart** [comment]
Closing this ticket, since search will be captured on another ticket. Creating new ticket for AMA flow research.
