### ISSUE TITLE
AMA Intake | Contentions for Unidentified issue

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7010]
As a claims worker, I need to be alerted if there are unidentified issues on a claim review that I need to fix in Caseflow.

requires #6990 

## Acceptance criteria
- When a contention is created for unknown issue, it should have the text "UNIDENTIFIED ISSUE - please click "Edit in Caseflow" button to fix"
- These should also always go on the Rating EP, even if there are no other rating issues.

## Copy
UNIDENTIFIED ISSUE - Please click "Edit in Caseflow" button to fix

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" > Add an unknown issue.
- Complete the intake
- Go to VBMS and validate the contention text

**Comment by suzchap** [comment]
@shanear this was on our list but I don't think it's a UI ticket so I'll pass back to you to fill out.

**Comment by shanear** [comment]
![screen shot 2018-10-26 at 2 24 39 pm](https://user-images.githubusercontent.com/1596259/47585621-cd8a1580-d92b-11e8-9cef-46ac545a5136.png)
Looking good 👍

**Comment by shanear** [comment]
oh no, it looks like when you add an unidentified contention in the Edit page, it does not use this text:

```
<env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Contention creation failed. System error. GUID: 16f73f0d-c3be-4c30-afa8-a371e8ebcf36</faultstring><detail><ns2:serviceException xmlns:part="http://vbms.vba.va.gov/cdm/participant/v5" xmlns:ns2="http://vbms.vba.va.gov/external/ClaimService/v5" xmlns:doc="http://vbms.vba.va.gov/cdm/document/v5" xmlns:com="http://vbms.vba.va.gov/cdm/common/v5" xmlns:claim="http://vbms.vba.va.gov/cdm/claim/v5" xmlns:aw="http://vbms.vba.va.gov/cdm/award/v4"><ns2:exception>Could not create contentions for ClaimID: 600142241</ns2:exception><ns2:message>Contention creation failed. System error.</ns2:message></ns2:serviceException></detail></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::CreateContentions:0x00007f1b0c722e40 @veteran_file_number="123458311", @claim_id="600142241", @contentions=["hi", "Service connection for Back is denied."], @special_issues=[], @v5=true>
```

**Comment by pkarman** [comment]
@shanear it seems like doing things from the Edit page were not in the original scope of this ticket. Am I misreading it?

**Comment by shanear** [comment]
It's certainly not clear from the ticket that it's part of the scope, this was more of a problem with the ticket that the dev work on it.

Either way we still need contentions to work like this even when created from the edit page. Would you mind doing that as part of this ticket?

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/7626 may address some of this.

**Comment by shanear** [comment]
This works now 👍 
![screen shot 2018-10-31 at 1 49 22 pm](https://user-images.githubusercontent.com/1596259/47821552-6effd580-dd37-11e8-815f-5fe8e1c896fa.png)
