### ISSUE TITLE
AMA intake | dynamic issue numbering

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7014]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

This ticket is focused on some dynamic issue numbering that appears on the Add rated issues page (#6981) and the Add issues landing page (#6966). 

requires #6988
requires #6966

## Acceptance criteria
- When a user has multiple issues, they are all listed on the Add Issues landing page, ordered and numbered in the order they were added.
- When a user add issues via the Add Issues modals, the text provides a reminder of which issue they are on. 

## Copy
(where X = the sequence of issue)
- Add issue X
- Does issue X match any of these issues from past decisions?
- (already selected for issue X)

## Mocks
<img width="561" alt="screen shot 2018-09-17 at 6 58 06 pm" src="https://user-images.githubusercontent.com/11219417/45654955-e04b3800-baab-11e8-9201-973f23d3d6e8.png">
<img width="554" alt="screen shot 2018-09-17 at 6 57 54 pm" src="https://user-images.githubusercontent.com/11219417/45654956-e04b3800-baab-11e8-96bb-06e150fb0e38.png">
<img width="554" alt="screen shot 2018-09-17 at 6 57 46 pm" src="https://user-images.githubusercontent.com/11219417/45654957-e04b3800-baab-11e8-9d58-aa384862c0df.png">
<img width="776" alt="screen shot 2018-09-17 at 6 57 34 pm" src="https://user-images.githubusercontent.com/11219417/45654958-e04b3800-baab-11e8-98c8-9829b1be37b9.png">

## How to Validate
- Doesn't require a specific test user
- Step one, add one rated issue: Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" > select a rated issue (check that modal title = "Add issue 1" and "Does issue 1 match...")  > click "Add this issue" button
- Step two: On Add issue landing page, check that your issue one is listed and displayed with a "1)" in front of it.
- Step three, add another issue: on "Add issue page, click "+Add issue" > on first "Add issue modal check that modal title = "Add issue 2" and "Does issue 2 match..." and the grayed out issue ends with "(already selected for issue 1)" then select "None of these match"  > on second "non-rated" modal, check that it says "Add issue 2" and "Does issue 2 match..." then select "None of these match" > on final Unknown issue page, check that it says "Add issue 3" then fill in any answer and click "Add this issue"
- Step four: on Add issue landing page, check that the 2nd issue has been added as "2)"
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by suzchap** [comment]
@shanear Should I split this into multiple tickets? One for each page? Or 1 for all modals and one for landing page?

**Comment by shanear** [comment]
<img width="508" alt="screen shot 2018-10-09 at 5 19 45 pm" src="https://user-images.githubusercontent.com/1596259/46699379-9e636c80-cbe7-11e8-846d-3b4eab31ba92.png">

got there
