### ISSUE TITLE
Existing XP | Assign to Claim | Caseworker cannot assign existing EPs in Firefox/IE browsers

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#702]
## Description
If user, using Firefox, tries to Assign an EP as a caseworker in Dispatch, the Assign to EP button doesn't work when clicked. 

**Steps to Recreate:**
1. Open Dispatch in Firefox
2. Establish a full grant claim, w/o Special Issues as a caseworker
3. Try clicking "Assign to EP" button, notice it is unresponsive.

**Expected Results:** 
User should be able to assign the existing EPs.

**Browser Found:** Firefox
**Environment Found:** Demo

**Screenshots:**
**_In Internet Explorer__ the button does nothing:_**
<img width="1027" alt="screen shot 2017-01-18 at 11 27 51" src="https://cloud.githubusercontent.com/assets/18075411/22072829/8d1dd93a-dd71-11e6-802c-dc735510ed4f.png">

**__In Chrome__ it works:**_
<img width="914" alt="screen shot 2017-01-18 at 11 31 12" src="https://cloud.githubusercontent.com/assets/18075411/22072864/ae377f90-dd71-11e6-89e4-92cf804461cd.png">
<img width="685" alt="screen shot 2017-01-18 at 11 32 16" src="https://cloud.githubusercontent.com/assets/18075411/22072901/d2618078-dd71-11e6-951f-aa7ed344e48d.png">

**Associated Issues/Stories:**
#627
#636
#621

**Reported by:** Alexis Stewart

**Comment by shanear** [comment]
Confirmed to work
