### ISSUE TITLE
AMA Intake | Add Issue Landing page "remove" button

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7028]
## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

When a user adds an issue and it displays on the Add Issue Landing page, they are able to remove that issue if needed.

requires #6982 

## Technical notes
- trash icon: https://fontawesome.com/icons/trash-alt?style=regular&from=io

## Acceptance criteria
- When a user adds an issue and it appears on the Add Issue Landing page, they can then remove that issue by clicking "Remove" next to it. 
- Clicking the Remove link will make that issue go away (we aren't doing a warning modal here)

## Copy
- Remove

## Mocks
<img width="686" alt="screen shot 2018-09-18 at 11 40 46 am" src="https://user-images.githubusercontent.com/11219417/45699340-c2c3b000-bb37-11e8-87f9-31001efd213b.png">

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" > Add a rated issue > back on the Add Issue Landing page click "remove" link & that issue should disappear.
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by shanear** [comment]
works like a charm 🍀
