### ISSUE TITLE
Citation numbers

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7031]
VACOLS stores citation numbers for each decision. This number is the public identifier for each case. Now that Caseflow handles the checkout flow for AMA we'll need to generate these numbers. Their current form is: 2 digit year + 7 digit sequence. For AMA we'll use the same approach and append the docket type initial to the front. i.e. H180000001. For the sequence I suggest we use the database id %10^7. This seems very unlikely to have a collision.

**Comment by laurjpeterson** [comment]
@aroltsch - no rush - do we support citation numbers in the IDT API?

**Comment by aroltsch** [comment]
Yup! We can close it
