### ISSUE TITLE
AMA Intake | "Complete Intake" button

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7035]
"Complete Intake" should save the issues

## Story
For any AMA forms, when a user needs to add issues, they will be walked through a multi-screen selection process to help them make the best choice. The landing page created in #6966 will be their starting point and a modal on top of it will walk the user through rated, non-rated, and an "unknown" option.

When a user is done adding issues and is ready to submit the claim/review, from the Add Issue Landing page, they can click the "Complete intake" button to save the issues and then display the "Confirmation" page.

## Acceptance criteria
- When a user clicks the "Complete intake" button, the issues are saved, and the "Confirmation" page is displayed.

## Copy
n/a

## Mocks
<img width="686" alt="screen shot 2018-09-18 at 11 40 46 am" src="https://user-images.githubusercontent.com/11219417/45700725-4763fd80-bb3b-11e8-961b-a5afd972bf95.png">

## How to Validate
- Doesn't require a specific test user
- Form select > search id > review page: any answers > on "Add issue page, click "+Add issue" > Add a rated issue  & click "Add this issue" > on Add Issue landing page, click "Complete intake" > You should land on the confirmation page and the review/claim should appear in VBMS. 
- TBD: does this need to be tested with all 3 AMA forms or will one suffice?

**Comment by shanear** [comment]
Duplicate closing
