### ISSUE TITLE
Existing EP | "Assign to Claim" button changing other claim's EP Code

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#704]
# Description:
When a Caseworker is on the `Existing EP` page and clicks on the **_Assign to Claim_** button for a specific claim, some of other Claim's EP Code value changes while waiting for the next page to render.  Not sure if this a UI bug or actual functionality is affected. 

**Environment:**
- [ ] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [x] Functional

**Severity Level:** 
- [x]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
**Scenario 1:**
1. Login as Caseworker.
2. Click on the **_Establish Next Claim_** button.
3. On the `Decision Review` page, click on the **_Create End Product_** button. 
4. On the `Existing EPs` page, click any of the **_Assign to Claim_** buttons.  While viewing the Loading Favicon, some of the other claim's EP Code value has changed.

# Screen Shots
**_Scenario 1 - Existing EP page_**
<img width="1799" alt="dispatch_assignep_randomclicks" src="https://cloud.githubusercontent.com/assets/18075411/22074193/86add9ca-dd75-11e6-8ac4-7821832d50b1.png">

**Results**
_Expected_: None of the EP codes change when **_Assign to Claim_** button is clicked
_Actual_: Random EP codes on the page change after clicking **_Assign to Claim_** button

# Related Stories
#702 
#621 
#636

**Comment by nikitarockz** [comment]
# Sprint Planning
Since this issue is based on results of using FireFox, this will not be addressed at this time. Returning back to Triage.

**Comment by kierachell** [comment]
**PASSED**
Works on Chrome/Firefox/IE now
![dispatchassignshift](https://cloud.githubusercontent.com/assets/18075411/22892560/0d717eb0-f1e1-11e6-8ec7-f3749dd8c725.gif)
