### ISSUE TITLE
Judge assignment bug: not able to see attorney dropdown + "assign cases" button

### ISSUE THREAD

**Issue by mkhandekar** [department-of-veterans-affairs/caseflow#7052]
@allyceh and I interviewed a judge as part of our regular usability sessions, and noticed a bug.

She showed us the case assignment screens. She's able to see the cases to be assigned and checkboxes on the assign table view, but *does not* see the attorney dropdown + "assign case" functionality, once one or more cases are selected.

This led her to use VACOLS to do all assignment related tasks instead. 

[related slack conversation](https://dsva.slack.com/archives/C6E41RE92/p1537381267000100)

**Comment by amprokop** [comment]
Thanks! Do you have the name or css id of the judge?

**Comment by mkhandekar** [comment]
Judge Kalpana Parakkal

**Comment by mkhandekar** [comment]
My understanding is that the toggle for judge assignment did not include the checkboxes, and Judge Parakkal was not one of the judges for whom the feature toggle was turned on. 

[We chatted in Slack](https://dsva.slack.com/archives/C6E41RE92/p1537381267000100), and have decided to leave this alone until next week (ish) when we rollout this feature to all judges. 

cc: @dannysellers since you _might_ be the one making this change? :)

**Comment by mkhandekar** [comment]
this should be resolved both by https://github.com/department-of-veterans-affairs/appeals-support/issues/3067 and the fact that the assignment toggle is going to be turned on for all judges.
