### ISSUE TITLE
Queue | Judges | Cases with dereceive not null and deprod = 'REA' should appear in the assign queue

### ISSUE THREAD

**Issue by evankroske** [department-of-veterans-affairs/caseflow#7057]
Today, these cases incorrectly appear in a judge's review queue. [Details](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/39). You can find cases like this with the following query:

```ruby
output = []
Constants::AttorneyJudgeTeams::JUDGES[:prod].keys.each do |css_id|
  user = User.find_by(css_id: css_id)
  tasks, = LegacyWorkQueue.tasks_with_appeals(user, "judge")
  tasks.each do |task|
    if (task.action == "assign") != (!task.document_id || task.document_id.empty?) then
      output << "#{task.id} #{task.appeal.vacols_id} #{task.action} #{task.document_id}"
    end
  end
end
puts output
```

**Comment by amprokop** [comment]
Nice job tracking this down. Let's fix it!

**Comment by evankroske** [comment]
After talking to Jed about this issue, it turns out that REA records are created by judges when the want to recall a case from an attorney in order to assign it to another attorney. In other words, Caseflow makes REA records obsolete because it supports reassignment of cases without them. 

For that reason, I think that Caseflow should ignore Decass records with deprod = 'REA'. This would cause cases with REA records to show up in judges' assign queues.

Jed also said that REA records are very uncommon, so this issue wouldn't be very important if there wasn't an outstanding REA record at this moment.
