### ISSUE TITLE
BVA Dispatch IDT appeal details returns error

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7064]
Steps to reproduce:
- Review a case as a judge
- Find that case's appeal id
- Create a token associated with a BVA dispatch user 
- Curl localhost:3000/idt/api/v1/appeals/:appeal_id 
- See that an error is returned

When creating BVA Dispatch tasks assigned to the user, it looks like we do not set assigned_by_id, since the task is assigned round robin.

Looks to me like the test seed data we have sets that field, but it might be the case that it would never be set in a real life situation, so localhost:3000/idt/api/v1/appeals/:appeal_id for a dispatch user might always fail.

Not sure what will happen for legacy appeals, but we aren't handling them quite yet.

# AC
- localhost:3000/idt/api/v1/appeals/:appeal_id should succeed when passing a token associated with a BVA dispatch user

**Comment by laurjpeterson** [comment]
@aroltsch is this ticket still relevant?
