### ISSUE TITLE
Display VLJ and senior counsel on case details page

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7069]
Many co-located administrative tasks require knowing who the VLJ and senior counsel are for a given case (to send them emails, for instance). This information is not visible on the case details page so co-located staff have to use VACOLS to determine who those folks are. That is an acceptable workaround for legacy appeals, but since AMA appeals will never enter VACOLS we need to add some way to determine who the judge and attorney working the case are.

Slack thread: https://dsva.slack.com/archives/C6E41RE92/p1537386021000100

## Acceptance criteria
* Display VLJ and senior counsel for an appeal on the case details page

**Comment by mkhandekar** [comment]
[Additional slack thread](https://dsva.slack.com/archives/C6E41RE92/p1537473497000100) with @lowellrex's first pass.
