### ISSUE TITLE
Intake | Don't require city and state for military addresses

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7081]
We've been getting reports that users can't process veterans with military addresses because we are requiring that they have city and state set. We should get rid of this requirement for military addresses.

## Validation
1. Find a veteran with a military address and no city/state (for example, a non-US military address)
2. Confirm that we can process an intake for this veteran

Or

1. Ask Katlin to reattempt intake with one of these veterans

**Comment by kencheeto** [comment]
@shanear you mentioned that there are examples of this, should I look for those in Sentry once I confirm access?

**Comment by shanear** [comment]
Yeah, I think the best thing to do would be to inform Katlin that they can try intaking forms for those vets again and see if it's working for them, (since it doesn't actually throw an exception, it was just incorrectly requiring them to enter a city and state)

**Comment by kencheeto** [comment]
@shanear okay! I'm looking for "Katlin" but I don't see them in Slack. How do I find them?

**Comment by shanear** [comment]
She’s at AMO and not in Slack. I notified her via email. I'll CC you if/when she responds.

**Comment by kencheeto** [comment]
okay, thanks!

**Comment by shanear** [comment]
validated in Prod this is working! Katlin didn't get the email but told us in the AMO meething.

**Comment by kencheeto** [comment]
🎉 thanks!
