### ISSUE TITLE
A man, a plan, a canal: Manual! | Manual RAMP processing~ a manual

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7088]
RAMP appeals have to be intaken as RAMPs and as NODs.
We should ideally query if any RAMP rows are older than three days without an appeal row associated with them, these are likely candidates to be lost.
```
RootTask.count == Appeal.count - 24
RootTask.count == WhateverRAMPClass.count
```

Set the current user object if you're making BGS calls!
```
RequestStore[:current_user] = User.find_by(css_id: "VHAISAPROKOA")
```

Assign all non-VSO tasks to judge users.
```
# Find all root tasks with no children, that means they are not assigned.
root_tasks_needing_assignment = RootTask.left_outer_joins(:children).all.select { |t| t.children.empty? }

list_of_assigneer

root_tasks_needing_assignment.each do |root_task|
	# paranoid check just so we don't assign any BEEAM appeals
	fail "this is BEAAM appeal" if root_task.appeal.established_at < Date.new(2018,9,1)

     JudgeTask.create!(appeal: task.appeal, parent: root_task
end
```

Find VSO tasks that need assignment to judge users.

1. Find VSO tasks that are more than 30 days old without completed dates. Set them as complete. Create judge tasks for those tasks. (Starting October 31st)
```
 GenericTask.
  .where(assigned_to_type: "Vso")
  .where("completed_at IS NULL")
  .where("parent_id IS NOT NULL")
  .where("assigned at < ?", 30.days.ago)

```

2. Find VSO tasks that have a completed at date but do not have any judge task associated with the same appeal   
Untested code example: 
```
GenericTask
  .where(assigned_to_type: "Vso")
  .where("completed_at IS NOT NULL ")
  .where("parent_id IS NOT NULL")
  .select do |vso_task|
  # Find VSO tasks with root tasks that aren't already associated with judge tasks
  vso_task.parent.children.none? { |t| t.type == "JudgeTask" }
end

# Or we could do it with joins :)
```

**Comment by laurjpeterson** [comment]
### Distribution criteria

On October 1, we should only distribute cases to judges that meet the following criteria:
- Only Direct Review or Evidence Submission appeals
- Appeals without IHP-writing VSOs
- If Evidence Submission, confirm their evidence window of 90 days has concluded

Throughout the pilot, we must wait until VSOs have completed their IHP before distributing. The Chairman changed her requirements to hold VSOs accountable to a 30 or 45 day turnaround time. See details [here](https://github.com/department-of-veterans-affairs/caseflow/issues/5581#issuecomment-424318754) in the VSO epic.

On October 1 and throughout the pilot, we should NOT distribute cases to the following judges (in progress):
- Judges with large legacy hearing backlogs (@cmgiven to get the list)
- Chief judges
     - Theresa Catino
     - Claudia Trueba
     - Bethany Buck
     - Cherry Crawford
     - Anthony Scire
     - Keith Allen
     - Cynthia Bruce
     - James March
     - Bob Scharnberger
     - John Jones

**Comment by cmgiven** [comment]
Post-hearing appeals by judge. ACT are those cases that have yet to receive a decision. REM are those cases that have received a decision, but may return and will require the same judge.

Note there are several inactive judges that remain in the list.

|id   |name                    | ACT| REM| total|
|:----|:-----------------------|---:|---:|-----:|
|467  |Steven Reiss            | 199| 433|   632|
|731  |Eric Leboff             | 188| 414|   602|
|611  |Anthony Mainelli        | 145| 298|   443|
|536  |Harvey Roberts          | 135| 444|   579|
|776  |Jessica Zissimos        | 128| 437|   565|
|872  |Ryan Kessel             | 125| 369|   494|
|458  |Kalpana Parakkal        | 118| 370|   488|
|894  |James Reinhart          | 115| 137|   252|
|418  |Jacqueline Monroe       | 110| 424|   534|
|571  |Vito Clementi           | 108| 290|   398|
|153  |Ursula Powell           | 106| 346|   452|
|657  |David Wight             | 106| 415|   521|
|048  |Derek Brown             | 104| 381|   485|
|365  |John Crowley            | 104| 172|   276|
|809  |Sonnet Bush             | 104| 252|   356|
|875  |Mary Sorisio            | 103| 137|   240|
|627  |Jonathan Kramer         | 102| 133|   235|
|738  |Tanya Smith             | 100| 395|   495|
|784  |Anne Jaeger             |  98| 429|   527|
|945  |Stacey Heneks           |  98| 235|   333|
|1024 |Bobby Mullins           |  95| 120|   215|
|533  |Michael Herman          |  94| 326|   420|
|904  |Holly Seesel            |  94| 268|   362|
|876  |Kerri Millikan          |  92| 499|   591|
|008  |Marjorie Auer           |  90| 392|   482|
|750  |Marti Hyland            |  90| 403|   493|
|595  |Thomas O Shay           |  88| 299|   387|
|550  |Michael Skaltsounis     |  87| 244|   331|
|947  |Jennifer Hwa            |  87| 148|   235|
|308  |Susan Kennedy           |  86| 364|   450|
|847  |Matthew Blackwelder     |  86| 235|   321|
|653  |Simone Belcher-Mays     |  85| 141|   226|
|036  |Barbara Copeland        |  82| 454|   536|
|561  |Glenn Wasik             |  81| 196|   277|
|981  |Helena Walker           |  81| 194|   275|
|955  |Nathan Kroes            |  80| 253|   333|
|346  |Michael Pappas          |  79| 492|   571|
|556  |Linda Howell            |  78|  68|   146|
|728  |Matthew Tenner          |  78| 219|   297|
|541  |Kelly Conner            |  77| 112|   189|
|598  |Michelle Kane           |  77| 330|   407|
|450  |Deborah Singleton       |  76| 290|   366|
|654  |Michael Lane            |  76| 299|   375|
|840  |Simone Krembs           |  76| 196|   272|
|323  |Lisa Barnard            |  73| 301|   374|
|457  |Yvette White            |  73| 134|   207|
|586  |Gayle Strommen          |  72| 207|   279|
|845  |Lana Jeng               |  72| 148|   220|
|846  |Lesley Rein             |  72| 163|   235|
|332  |Michael Martin          |  71| 445|   516|
|1118 |Kristin Haddock         |  69| 143|   212|
|178  |Howard Schwartz         |  69| 259|   328|
|319  |Michael Kilcoyne        |  68| 311|   379|
|398  |Karen Alibrando         |  68| 312|   380|
|471  |Caryn Graham            |  68| 244|   312|
|647  |Kelli Kordich           |  68| 201|   269|
|895  |Dana Johnson            |  67| 121|   188|
|909  |Paul Sorisio            |  67| 214|   281|
|438  |Paula Dilorenzo         |  66| 418|   484|
|1010 |Amy Ishizawar           |  65| 168|   233|
|778  |Jonathan Hager          |  65| 166|   231|
|460  |Jeffrey Parker          |  64| 175|   239|
|797  |Kathy Banfield          |  64| 374|   438|
|1093 |Vincent Chiappetta      |  62| 121|   183|
|115  |Michael Lyon            |  62| 369|   431|
|842  |Estela Velez            |  62| 252|   314|
|559  |Andrew Mackenzie        |  61| 418|   479|
|881  |John Francis            |  61| 138|   199|
|1591 |Victoria Moshiashwili   |  60| 193|   253|
|790  |Rebecca Feinberg        |  59| 220|   279|
|1070 |Bradley Knope           |  58| 129|   187|
|915  |Kristi Gunn             |  58| 111|   169|
|256  |Milo Hawley             |  57| 439|   496|
|748  |Tara Reynolds           |  55| 258|   313|
|607  |Alexandra Simpson       |  51| 109|   160|
|1590 |Anthony Scire           |  50| 154|   204|
|225  |George Senyk            |  48| 474|   522|
|1006 |Caroline Fleming        |  47| 143|   190|
|1062 |Cynthia Bruce           |  47|  95|   142|
|386  |Keith Allen             |  47| 167|   214|
|464  |Mary Larkin             |  47| 419|   466|
|918  |Nathaniel Doan          |  46| 350|   396|
|824  |Donnie Hachey           |  45|  72|   117|
|1939 |Angel Caracciolo        |  44| 135|   179|
|679  |Robert Scharnberger     |  44| 267|   311|
|871  |Dorilyn Ames            |  44| 101|   145|
|511  |Cherry Crawford         |  43|  78|   121|
|805  |Bethany Buck            |  41| 155|   196|
|374  |James March             |  34| 111|   145|
|616  |Claudia Trueba          |  27| 136|   163|
|448  |John Jones              |  18|  84|   102|
|442  |Kimberly Osborne        |  17|  53|    70|
|370  |Theresa Catino          |   8|  49|    57|
|1092 |DelYvonne Whitehead     |   7|   0|     7|
|725  |William Donnelly        |   7|  10|    17|
|337  |Cheryl Mason            |   4|  22|    26|
|588  |Thomas Jones            |   4|  11|    15|
|1060 |Kristy Zadora           |   3|   1|     4|
|592  |Demetrious Orfanoudis   |   3|  14|    17|
|504  |Carolyn Krasinski       |   2|   5|     7|
|1064 |Brianne Ogilvie         |   1|   4|     5|
|1081 |Corey Bosely            |   1|   1|     2|
|183  |David Spickler          |   1|  18|    19|
|290  |John Prichard           |   1|  10|    11|
|570  |Cynthia Wasser          |   1|   1|     2|
|575  |Stephen Eckerman        |   1|   1|     2|
|581  |Neil Werner             |   1|  12|    13|
|587  |Thomas Douglas          |   1|   8|     9|
|743  |Jennifer Deane          |   1|   2|     3|
|801  |Karen Kennerly          |   1|  15|    16|
|815  |April Maddox            |   1|   5|     6|
|831  |Saramae Kreitlow        |   1|   0|     1|
|965  |Laura Yantz             |   1|   1|     2|
|995  |Christopher Murray      |   1|   4|     5|
|9992 |TBD2 *To be Determined2 |   1|   0|     1|
|1026 |Ann-Monique Clark       |   0|   2|     2|
|1034 |Kristine Gielow         |   0|   5|     5|
|1171 |Kristin Neilson         |   0|   1|     1|
|295  |Anne Shawkey            |   0|   1|     1|
|335  |John Hutcheson          |   0|   3|     3|
|362  |Robert Jones            |   0|   1|     1|
|382  |Nancy Rippel            |   0|   3|     3|
|390  |Jacqueline Connolly     |   0|   1|     1|
|401  |Heather Harter          |   0|   1|     1|
|407  |Michael Mazzucchelli    |   0|   1|     1|
|474  |Debbie Breitbeil        |   0|   3|     3|
|483  |Carole Kammel           |   0|   4|     4|
|524  |Deborah Drucker         |   0|   1|     1|
|569  |William Yates           |   0|   2|     2|
|599  |Lila Bakke              |   0|   2|     2|
|658  |Lauren Cryan            |   0|   1|     1|
|683  |Debra Bredehorst        |   0|   1|     1|
|695  |Jacqueline Barone       |   0|   6|     6|
|751  |Michael Osborne         |   0|   4|     4|
|755  |Motrya Mac              |   0|   8|     8|
|769  |Marcy Kreindler         |   0|   2|     2|
|802  |Sonja Mishalanie        |   0|   6|     6|
|818  |Meaghan Zawadzki        |   0|   1|     1|
|821  |Sarah Richmond          |   0|   6|     6|
|861  |Adriane Turnipseed      |   0|   3|     3|
|865  |Paul Rubin              |   0|   1|     1|
|867  |Jennifer Moats          |   0|   5|     5|
|869  |Nancy Snyder            |   0|   1|     1|
|899  |Josh Freeman            |   0|   2|     2|
|957  |Michael Donohue         |   0|   1|     1|
|986  |Rebecca Poulson         |   0|  11|    11|

```r
cases <- query("
  select BFMEMID, BOARD_MEMBER, SNAMEF, SNAMEL, SACTIVE, BFMPRO
  from BRIEFF
  join FOLDER on BFKEY = TICKNUM
  left join (
    select distinct TINUM, BOARD_MEMBER
    from HEARSCHED
    join FOLDER on FOLDER_NR = TICKNUM
    where HEARING_DISP = 'H' and HEARING_TYPE in ('C', 'T', 'V')
  ) HEARSCHED on FOLDER.TINUM = HEARSCHED.TINUM
  join STAFF on SATTYID = BOARD_MEMBER
  where BFMPRO in ('ACT', 'REM')
    and BFHA in ('1', '2', '6')
")

counts <- cases %>%
  filter(BFMPRO == 'ACT' | BFMEMID == BOARD_MEMBER) %>%
  count(BOARD_MEMBER, SNAMEF, SNAMEL, SACTIVE, BFMPRO) %>%
  subset(!is.na(BOARD_MEMBER) & SACTIVE == 'A') %>%
  spread(BFMPRO, n) %>%
  replace_na(list(ACT = 0, REM = 0)) %>%
  transmute(id = BOARD_MEMBER, name = paste(SNAMEF, SNAMEL), ACT, REM, total = ACT + REM) %>%
  arrange(desc(ACT))

counts %>% kable()
```

**Comment by laurjpeterson** [comment]
@nicholasholtz - could you go through what Chris posted and mark who is a judge vs. senior counsel vs. attorney? You could cross off the rows in his table to signify appeals shouldn't be distributed to those people. I think there are quite a few acting judges that have low legacy hearing backlogs that we should exclude.

**Comment by nicholasholtz** [comment]
Initial update provided. Most of the ?s are probably Actings. Will need to get confirmation

**Comment by laurjpeterson** [comment]
Thanks! @amprokop take a look at what Chris put above. I think we would select judges from Dorilyn Ames' name and above to distribute cases to. How does the affect the queries you've written?
