### ISSUE TITLE
End-to-end test plan

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7090]
### 1. Intake RAMP appeal with Caseflow Intake

Ensure the `:ama_intake` feature flag is enabled.
Navigate to Caseflow Intake,
Choose the Notice of Disagreement option.
Go through the flow 3-4 times, so you have enough appeals.
963360019 works as a file number, not sure what else 🤔 

### 2. See it show up in the VSO queue - In progress
Setting up this for local testing is not quite finished.

### 3. Complete task as VSO user (not in scope) 
Setting up this for local testing is not quite finished.

### 4. Run a manual query to find that the appeal is eligible for assignment to judge & run a manual query to assign the appeal to a judge

The code snippet here doesn't quite work yet, it's a work in progress.

We can accomplish this with changes to the JudgeTask class. See here for latest.

https://github.com/department-of-veterans-affairs/caseflow/pull/7091/files

### 5. Assign the appeal to an attorney

![image](https://user-images.githubusercontent.com/3781835/45885146-82984380-bd6a-11e8-81b2-1043d5acbeb7.png)

Log in as either BVAAABSHIRE or BVAOFRANECKI. Assign a mix of legacy and AMA appeals, and test out assigning them back and forth between different attorneys.

### 6. See it show up in the attorney's queue

Log in as the attorney you chose.

### 7. As attorney, assign the appeal to colocated

Colocated tasks are round-robin assigned. 

### 9. As colocated, complete the task

Add a note.

### 10. See it show up in the attorney's queue again

Verify that the note is still present.

### 11. Make curl requests to test attorney IDT API — case is visible by the IDT as assigned to the attorney 

From the terminal:
```
curl localhost:3000/idt/api/v1/token
```
You'll see a response with a token and a one time key. Hang on to both.
Then, in a browser, when you're logged in as an attorney user.
```
localhost:3000/idt/auth?one_time_key=ONE_TIME_KEY
```
You should see a success message. The token is now associated with the user you're logged in as. Now you can make test requests as that user.

View the list of appeals and verify it contains everything you expect.
```
curl localhost:3000/idt/api/v1/appeals --header "TOKEN: #{token}"
```
Also, view details for an appeal:
```
curl localhost:3000/idt/api/v1/appeals/#{appeal_id} --header "TOKEN: #{token}"
```
### 12. Review the appeal as an attorney, adding special issues, dispositions  and remand reasons and a note

Make sure to test that remand reasons are saved.
 
### 13. See the appeal show up for a judge, and view/edit the dispositions, remand reasons, and the note 

Verify that all the data, including remand reasons and the note, is present.

### 14. Make curl requests to test judge IDT API — case is visible by the IDT as assigned to the judge

Log in as a judge and follow the same instructions for IDT attorney testing.

### 15. Review the appeal as a judge, and finalize the review

Make sure you make a note of the appeal id.

### 16. Test the BVA Dispatch IDT API — addresses and tasks are viewable by the dispatch team

Log in as a BVA Dispatch user, and follow the IDT API attorney testing instructions.

### 17. Complete the task

POST to `/idt/api/v1/appeals/:appeal_id/outcode`. Verify with a manual query that the task is complete.

**Comment by dannysellers** [comment]
Testing results / action items:
- Attorney instructions were missing after placing a task on hold
- For AMA cases: colocated users shouldn't have the option to send a task to the Schedule Hearing team
- for AMA cases: colocated users should only be able to place holds on Translation tasks
- AMA remand reasons aren't populating correctly on load (i.e. after setting reasons, completing attorney checkout, viewing reasons as judge)
- After reviewing the case as an attorney, `task.assigned_by_id` was `nil` on the `JudgeTask`

**Comment by amprokop** [comment]
```
Yeah, I wasn't 100% sure whether a nil assigned_by_id was expected or not, though it does make sense. But, we saw an error when trying to evaluate the case as a judge—we got an error saying "Attorney can't be blank", because attorney_id was null.
```

Interesting. Can you fix that?

**Comment by laurjpeterson** [comment]
@dannysellers - 

| action type | docket | actions |
|--------|-----------|--------|
| schedule hearing | | |
| | legacy | send to team, send to attorney, place hold | |
| | ama | ~send to team~, send to attorney, place hold |
| translation | | |
| | legacy | send to team, send to attorney, place hold | |
| | ama | ~send to team~, send to attorney, place hold |
| all other types | | |
| | legacy | send to attorney, place hold |
| | ama | send to attorney, place hold |

**Comment by laurjpeterson** [comment]
October pilot completed! Closing
