### ISSUE TITLE
Describe Caseflow on login screen

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#71]
The large text at the VACOLS login prompt went relatively unnoticed by most participants. This text could include vital informaiton such as context about Caseflow and what it does.    

Suggestion: Consider making the text smaller and providing more explanation or context for what the application does here. Consider moving it to the left or right of the VACOLS username and password boxes.

**Comment by KHarshawat** [comment]
Rough mock!

![image](https://cloud.githubusercontent.com/assets/6335546/10798490/48ccfa58-7d7e-11e5-8fe7-71ccdb42e354.png)

**Comment by alex** [comment]
If someone can give me some sample HTML for this userface, I can work on it.

**Comment by paultag** [comment]
If you want, I can pick this issue up

On Thu, Oct 29, 2015 at 11:07 AM, Alex Gaynor <notifications@github.com>
wrote:

> If someone can give me some sample HTML for this userface, I can work on
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/71#issuecomment-152208470>
> .
>



-- 
:wq

**Comment by plusjeff** [comment]
@KHarshawat Mockup doesn't have the dual logins (SSOi + VACOLS).

**Comment by paultag** [comment]
@plusjeff the SSOi page kicks someone over to the SSOi site, then they get this page (when we have SSOi disabled locally, we only just see this) -- but it's a redirect, so we shouldn't have to deal with it in the view :+1:
