### ISSUE TITLE
Refactor task action dropdowns

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7102]
Currently our task action dropdowns are very specific to role. Each dropdown operates differently. We propose the following pattern:

The initial request to the backend will get a list of actions that user can perform and the URLs those actions take the user to. This helps us solve a couple of problems: 1) If a user has multiple roles, we can give them tasks from all of those roles. 2) We can add tasks that should be accessible to everyone. 3) It scales better than making a new component for every role.

See the following slack conversation for more context: https://dsva.slack.com/archives/C6E41RE92/p1537542173000100

**Comment by laurjpeterson** [comment]
@lowellrex i moved this to backlog, but, should it actually be closed?

**Comment by lowellrex** [comment]
I think we can close this puppy out!
