### ISSUE TITLE
App Actions | Show Loading Indicator during button click

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#711]
As a Product Owner, I would like to have the Loading indicator is displayed while the system is performing actions after clicking on any action button within the Dispatch product so that there is an indication that something is happening. 

# Acceptance Criteria
1. Verify that after clicking **_Establish next claim_** button on the `Caseworker Home` page, a loading indicator is displayed while the system loads the `Decision Review` page.
1. Verify that after clicking  **_Route claim_** button on the `Decision Review` page, a loading indicator is displayed while the system loads the `Route Claim` page.
1. Verify that after clicking  **_Route claim for Decision 1_** button on the `Decision Review: Multiple Decisions` page, a loading indicator is displayed while the system loads the `Route Claim` page.
1. Verify that after clicking  **_Route claim for Decision 2_** button on the `Decision Review: Multiple Decisions` page, a loading indicator is displayed while the system loads the `Route Claim` page.
1. Verify that after clicking  **_Create End Product_** button on the `Route Claim` page, a loading indicator is displayed while the system loads the `Confirmation` page.
1. Verify that after clicking  **_Create new EP_** button on the `Existing EP` page, a loading indicator is displayed while the system loads the `Confirmation` page.
1. Verify that after clicking  **_Assign claim_** button on the `Existing EP` page, a loading indicator is displayed while the system loads the `Confirmation` page.
1. Verify that after clicking  **_Finish routing claim_** button on the `Route Claim: Add VBMS Note` page, a loading indicator is displayed while the system loads the `Confirmation` page.
1. Verify that after clicking  **_Finish routing claim_** button on the `Route Claim: Send Email` page, a loading indicator is displayed while the system loads the `Confirmation` page.
1. Verify that after clicking  **_Finish routing claim_** button on the `Route Claim in VACOLS` page, a loading indicator is displayed while the system loads the `Confirmation` page.
1. Verify that after clicking  **_Establish next claim_** button on the `Confirmation` page, a loading indicator is displayed while the system loads the `Confirmation` page.

# Mockup
<img width="255" alt="screen shot 2017-02-24 at 2 54 52 pm" src="https://cloud.githubusercontent.com/assets/4975959/23318657/4da03b20-faa1-11e6-91d7-6218959c24f3.png">

# Related Stories
#1001

**Comment by nikitarockz** [comment]
1. Verify that after clicking **_Create End Product_** button on the `Decision Review` page, a loading Favicon is displayed while the system loads the `End Product` page.
1. Verify that after clicking **_Cancel_** button on the `Decision Review` page, a loading Favicon is displayed while the system loads the `EP Cancellation` page.
1. Verify that after clicking **_Cancel_** button on the `End Product` page, a loading Favicon is displayed while the system loads the `EP Cancellation` page.
1. Verify that after clicking **_Create End Product_** button on the `End Product` page, a loading Favicon is displayed while the system loads the `EP Cancellation` page.

**Comment by lakohl** [comment]
add mock

**Comment by slj** [comment]
1. Verify that after clicking Establish next claim button on the Caseworker Home page, a loading indicator is displayed while the system loads the Decision Review page.  **NEW Component needed**

2. Verify that after clicking Route claim button on the Decision Review page, a loading indicator is displayed while the system loads the Route Claim page. **Clicking the button changes the client state so fast that the "Loading..." view may not be necessary**

3. Verify that after clicking Route claim for Decision 1 button on the Decision Review: Multiple Decisions page, a loading indicator is displayed while the system loads the Route Claim page.  **Client state change - see no. 2**

4. Verify that after clicking Route claim for Decision 2 button on the Decision Review: Multiple Decisions page, a loading indicator is displayed while the system loads the Route Claim page.  **Client state change - see no. 2**

5. Verify that after clicking Create End Product button on the Route Claim page, a loading indicator is displayed while the system loads the Confirmation page.  **Loading works, needs restyling**

6. Verify that after clicking Create new EP button on the Existing EP page, a loading indicator is displayed while the system loads the Confirmation page.  **Client state change - see no. 2**

7. Verify that after clicking Assign claim button on the Existing EP page, a loading indicator is displayed while the system loads the Confirmation page.  **Loading works, needs restyling**

8. Verify that after clicking Finish routing claim button on the Route Claim: Add VBMS Note page, a loading indicator is displayed while the system loads the Confirmation page.  **Loading works, needs restyling**

9. Verify that after clicking Finish routing claim button on the Route Claim: Send Email page, a loading indicator is displayed while the system loads the Confirmation page.  **Loading works, needs restyling**

10. Verify that after clicking Finish routing claim button on the Route Claim in VACOLS page, a loading indicator is displayed while the system loads the Confirmation page.  **WHERE IS THIS????**

11. Verify that after clicking Establish next claim button on the Confirmation page, a loading indicator is displayed while the system loads the Confirmation page.  **NEW Component needed**

**Comment by lakohl** [comment]
@slj I'll take a look at this shortly.

**Comment by slj** [comment]
1. Verify that after clicking Create End Product button on the Decision Review page, a loading Favicon is displayed while the system loads the End Product page. **WORKING NOW**
2. Verify that after clicking Cancel button on the Decision Review page, a loading Favicon is displayed while the system loads the EP Cancellation page. **Do we really need this one? This looks like another client-side transition that's fast enough to make a loader negligible**
3. Verify that after clicking Cancel button on the End Product page, a loading Favicon is displayed while the system loads the EP Cancellation page. **See pt. 2**
4. Verify that after clicking Create End Product button on the End Product page, a loading Favicon is displayed while the system loads the EP Cancellation page. **See pt. 4**

**Comment by lakohl** [comment]
@slj You are correct re: Cancel. It is not be a button, but rather a link, and should not require the loading favicon.
Are you testing in prod? I'm asking cause we've observed that it can be significantly slower. I would set a rule that the loading favicon appears after 2? secs. If the next page displays before that we don't have to show the loading favicon, but it should exist for slow days.

**Comment by slj** [comment]
@lakohl I have not personally tested in prod, but as soon as https://github.com/department-of-veterans-affairs/caseflow/pull/1131 gets merged into master we can find out.  The only button on which I did not implement the loading flag is item 6:
```
Verify that after clicking Create new EP button on the Existing EP page, a loading indicator is displayed while the system loads the Confirmation page.
```
If a loading button proves necessary it's a quick change.

**Comment by slj** [comment]
@lakohl FYI all the buttons mentioned in the original spec render the Loading status, even if the change is too quick to notice.

**Comment by lakohl** [comment]
Super. thanks @slj !!

**Comment by astewarttistatech** [comment]
No spinner on the loader button currently. 

Current view: 
<img width="563" alt="screen shot 2017-03-29 at 9 21 38 am" src="https://cloud.githubusercontent.com/assets/23038505/24456645/ae48c832-1461-11e7-95fd-f12d94e25025.png">

Pushing back to in progress.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Validated on: FF and Chrome 

Steps to Validated: 
1. Go to Dispatch as a caseworker and go through the flow of creating an EP
2. Check all of the loading buttons for their new look 

Screenshots: 
<img width="320" alt="screen shot 2017-03-29 at 12 07 25 pm" src="https://cloud.githubusercontent.com/assets/23038505/24467279/e78c6d5e-1481-11e7-94c0-bd7945ab7ba0.png">
