### ISSUE TITLE
Create Informal Conference tracked item when establishing a claim

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#7118]
## Story
In order to be able to create an informal conferenced tracked item for Higher-Level Review claims, we need to make a couple of calls to BGS

Add call to manageClaimantLetter_V2 and generateTrackedItems to BGSService
Update the ruby_bgs version in the Gemfile

If a user selects the "Informal Conference" option for a Higher Level Review, then the tracked item should be created as part of establishing the claim (after the claim is established).

Necessary steps should be taken to include it in the idempotency for establishing a claim (tracking success of each of these calls, re-trying if necessary).

requires department-of-veterans-affairs/ruby-bgs#65

**Comment by shanear** [comment]
![screen shot 2018-10-03 at 1 04 43 pm](https://user-images.githubusercontent.com/1596259/46426651-30153a80-c70d-11e8-9cdc-c4c994b5d825.png)
i never thought i would see this day. so happy. 🙂
