### ISSUE TITLE
Change task type (front end only)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7126]
Related support ticket - https://github.com/department-of-veterans-affairs/appeals-support/issues/3066#issuecomment-423973823

Stories:
* When a co-located user is assigned a task incorrectly identified by the attorney, they need to be able to change the task type, so they have the right actions available to them for the next step.
* When Litigation Support users are assigned a post-decisional motion (like a Motion for Reconsideration) and after reviewing the file they realize that the Veteran actually requested a Motion to Vacate, they need to change the task type to track what the Veteran actually requested about the case.
* When any user is assigned a mail task and notices that the mail team incorrectly categorized the mail task, they want to change the task type so it accurately reflects what the Veteran/mail says.

#### User, in this case a VLJ Support staff member, sees that the task that's been assigned to them by the attorney is inaccurate. They select the actions dropdown for that respective task, to change task type.
![changing-task-1](https://user-images.githubusercontent.com/31224257/55447041-1eafcc80-5590-11e9-8acd-664d6b74484e.png)

#### They have the opportunity to select from an available list of replacement tasks (in this case, other admin actions). They can also provide a task note.
![changing-task-2](https://user-images.githubusercontent.com/31224257/55446890-916c7800-558f-11e9-86f0-21a5148feaa5.png)

#### They select a different admin action from the list
![changing-task-3](https://user-images.githubusercontent.com/31224257/55446891-916c7800-558f-11e9-900d-e42c15a00934.png)

#### They fill out a note
![changing-task-4](https://user-images.githubusercontent.com/31224257/55446892-916c7800-558f-11e9-9a6e-3215a1eef871.png)

#### They see a confirmation message as well as the reflected task changes in Currently active tasks
![changing-task-5](https://user-images.githubusercontent.com/31224257/55446893-916c7800-558f-11e9-84b8-54d4e3cfe529.png)

## AC
- Front end work for change task type

## Out of scope (and needs discussion)
- Back end work for changing task type according to the above scenarios. We currently have automatic routing of mail tasks, so we need to think through how to handle a change in task type. Also, we need to think through how to trace task changes up the tree given different changes.

**Comment by laurjpeterson** [comment]
Note: I realized that implementing this change would only add it for co-located users, but we would likely want it for future org queue users. Therefore, we can design this, but hold off on implementing until we decide it's absolutely necessary for co-located. 

cc: @aroltsch @mdbenjam @lowellrex

**Comment by laurjpeterson** [comment]
@sneha-pai - reminder to please drop in designs

**Comment by tomas-nava** [comment]
too early to point...
- need design
- need to confirm that sending a PATCH to the task endpoint is able to update task type (if not, we should do that as part of this task)

**Comment by allyceh** [comment]
@tomas-nava Designs are added (above!)
