### ISSUE TITLE
App Canvas | Error message should not persist on following page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#713]
# Description
General error message needs to clear when users moves (forward or backward) to the next page. If error is triggered again, a new error message will appear.

**Environment:**
- [x] Production
- [x] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [x] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [x]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1 - Integration Error
1. Click on the Establish Next Claim button.
1. Select "Mustard Gas" from the Special Issue Categories
1. Click on the Route Claim button.
1. Click on the Create End Product button.
1. The integration error is displayed on the EP Creation page.
1. Click on the browser's back button.  
**_Results:_** The error message is now displayed on the `Decision Review` page.

## Screenshots
 **_Scenario 1 - Receive error message on EP Creation page_**
<img width="1554" alt="screen shot 2017-01-19 at 5 07 33 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128020/a67a4034-de6c-11e6-8b25-5303b1458b40.png">

 **_Scenario 1 - Receive error message on EP Creation page_**
<img width="1554" alt="screen shot 2017-01-19 at 5 09 56 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128023/a778f192-de6c-11e6-903d-488969ae4843.png">

# Related Issues
n/a

**Comment by lakohl** [comment]
@shanear  to provide screenshots

**Comment by shanear** [comment]
Original error
<img width="1554" alt="screen shot 2017-01-19 at 5 09 56 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128023/a778f192-de6c-11e6-903d-488969ae4843.png">

After clicking "Back to Review"
<img width="1554" alt="screen shot 2017-01-19 at 5 07 33 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128020/a67a4034-de6c-11e6-8b25-5303b1458b40.png">

**Comment by lakohl** [comment]
It's true, the error should not persist when the user goes back to the previous screen.
@kierachell Do you know if this still happening?

**Comment by kierachell** [comment]
Yes it is

**Comment by kierachell** [comment]
**PASSED**

no longer happens and no one cares anyway
