### ISSUE TITLE
Decision Review | Special Issues |  Show all issues regardless Decision Type

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#715]
As a Caseworker, I want to be able to see the complete and correct list of Special Issues for all Decision Types so that I am certain I am selecting all that apply regardless of the Decision Type.

# Acceptance Criteria
1. Verify that the following list of all of the Special Issue categories are always displayed regardless of the Decision Type (Full Grants, Partial Grants, and Remands) (Refer to mockup):
> • Contaminated Water at Camp LeJeune
> • DIC - death, or accrued benefits - United States
> • Education - GI Bill, dependents educational assistance, scholarship, transfer of entitlement
> • Foreign claim - compensation claims, dual claims, appeals
> • Foreign pension, DIC - Mexico, Central and South American, Caribbean
> • Foreign pension, DIC - all other foreign countries
> • Hearing - including travel board & video conference
> • Home Loan Guarantee
> • Incarcerated Veterans
> • Insurance
> • _Manlincon_ Compliance
> • Mustard Gas
> • National Cemetery Administration
> • Non-rating issue
> • Pension - United States
> • Private Attorney or Agent
> • Radiation
> • _Rice_ Compliance
> • Spina Bifida
> • U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian)
> • U.S. Territory claim - Philippines
> • U.S. Territory claim - Puerto Rico and Virgin Islands
> • VAMC
> • Vocational Rehab
> • Waiver of Overpayment
2. Verify that the Special Issue Categories are in alphabetical order according to the list above.
1. Verify that the label for the section title is 'Select Special Issue(s)', and it matches the style of the mock below. (@lakohl can help verify)
1. Verify that the following words are italicized:
_Manlicon_ and _Rice_ (the word "Compliance" should not be italicized)

## Mockups
**_View - Decision Review page with new Special Issues_**
<img width="621" alt="screen shot 2017-02-10 at 1 15 15 pm" src="https://cloud.githubusercontent.com/assets/4975959/22838413/08c56674-ef93-11e6-885e-4b8f5526682a.png">

# Related Stories
**_Pre-requisites_**
Decision Review | Don't allow changing Decision Type #803
Decision Review | Create End Product.. | Save selected Special Issues for an unsupported Special Issue Cancellation #811

**Comment by lakohl** [comment]
@abbyraskin could you take a look at this list of special issues and make any adjustments to the naming or add any issues I may have missed? thnx!

•	Contaminated Water at Camp LeJeune
•	DIC - death, or accrued benefits - United States
•	Education - GI Bill, dependents educational assistance, scholarship, transfer of entitlement
•	Foreign claim - compensation claims, dual claims, appeals
•	Foreign pension, DIC - Mexico, Central and South American, Caribbean
•	Foreign pension, DIC - all other foreign countries
•	Hearing - including travel board & videoconference
•	Home Loan Guarantee
•	Incarcerated Veterans
•	Incarcerated Veterans
•	Insurance
•	Manlincon Compliance
•	Mustard Gas
•	National Cemetery Administration
•	Non-rating issue
•	Pension - United States
•	Private Attorney or Agent
•	Radiation
•	Rice Compliance
•	Spina Bifida
•	U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian)
•	U.S. Territory claim - Philippines
•	U.S. Territory claim - Puerto Rico and Virgin Islands
•	VAMC
•	Vocational Rehab
•	Waiver of Overpayment

**Comment by abbyraskin** [comment]
@lakohl I added in Manila (these are all handled by Manila RO) and a little styling - as I'm comparing to the worksheets they use today, they have a decent amount more keywords provided to them. I think we can start light with this list and see if we need to add more context for any of the issues.

**Comment by lakohl** [comment]
@abbyraskin Do you think we should say 'Select a Special Issue Category' or 'Select Special Issue Categories'?

**Comment by abbyraskin** [comment]
How about **Select any special issue(s) contained in this appeal:** otherwise i'd just say **Select Special Issue(s):**

Also, should we add Other as an explicit option? I was thinking it might be useful in figuring out anything we're explicitly missing (and in case their "why are you canceling" reason isn't clear enough).

**Comment by shanear** [comment]
@lakohl Can you add a mock for where the 'Describe the Special Issue' field should go and what it should look like?

**Comment by lakohl** [comment]
@shanear see above. Sorry I thought I'd already done that. Must have forgotten to hit the Comment button.

**Comment by shanear** [comment]
@lakohl also, what does this mean? 
> to describe their reason for cancelling out.

I assume if they click other, then we should automatically force it to be cancelled.

**Comment by lakohl** [comment]
@shanear Sorry for the back and forth. Abby and I just spoke and we decided to take out Other for now.

**Comment by lakohl** [comment]
@shanear it's ready to go now!

**Comment by lakohl** [comment]
@abbyraskin did you say we were missing one issue here?

**Comment by abbyraskin** [comment]
yes, not sure where it disappeared to :) Committee on Waivers

**Comment by lakohl** [comment]
Thanks @abbyraskin !

**Comment by abbyraskin** [comment]
@lakohl arg so sorry for the confusion - we had it listed as "Waiver of Overpayment." I'm erasing Committee on Waivers now.

**Comment by abbyraskin** [comment]
@lakohl @nikitarockz i edited AC for italicized words

**Comment by lakohl** [comment]
Thanks @abbyraskin !

**Comment by kierachell** [comment]
AC does not reflect a new issue:
https://github.com/department-of-veterans-affairs/caseflow/issues/946
![aasmerror](https://cloud.githubusercontent.com/assets/18075411/23051003/bb767b1e-f493-11e6-9ffc-348c5135284d.png)

Update to address both. Easy enough.
