### ISSUE TITLE
Add "End hold early" to actions for "on hold" tasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7152]
Sometimes tasks are put on hold while a Board employee waits for a response from a third-party. Currently, there is no way for a Board employee to end a hold early (say the third-party responded on day 18 of 30).

## Acceptance criteria
* Board employees have some way to end holds early for tasks that are on hold.

**Comment by sneha-pai** [comment]
@lowellrex when a colocated person clicks on "end hold early", what would you imagine happening to that case? Would it move the case to "pending actions"? 

Today, any colocated user can "end" the hold by actioning on it at any time.

**Comment by lowellrex** [comment]
Correct, ending a hold early would change the status in the database to `in_progress` and move the task in the UI to the "Pending" tab. Currently the only way co-located folks can end a hold early is by assigning it back to the attorney who assigned it to them (since that is the only action available to on hold co-located tasks).

**Comment by laurjpeterson** [comment]
@lowellrex is this ticket still relevant, given the work you've done on timed tasks / allowing all individual queue folks to place tasks on hold?

**Comment by lowellrex** [comment]
Great find! You're totally right, this is completed by [the work we did](https://github.com/department-of-veterans-affairs/caseflow/blob/6edbd5334a4c6f1284b158d1058dc549042ccd72/app/models/task.rb#L77) for the timed hold tasks.
