### ISSUE TITLE
Existing EP | Assign to Claim | Loading Indicator incorrect position and styling

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#716]
# Description
The Loading Indicator icon displayed after clicking on the **_Assign to Claim_** button on the `Existing EP` page is messed up.  It is not in the correct position and the favicon icon is not overlapping properly.  The Loading Favicon should be centered within the dimensions of the **_Assign to Claim_** button and the favicon icon should be overlapped properly (refer to Expected Results).

**Environment:**
- [ ] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproductive Steps
**Scenario 1:**
1. Login as Caseworker.
2. Click on the **_Establish Next Claim_** button.
3. On the `Decision Review` page, click on the **_Create End Product_** button.  (Note: The current case must already have some existing EPs in order for the `Existing EP` page to render.)
4. On the `Existing EPs` page, click any of the **_Assign to Claim_** buttons.

# Screen Shots
**_Scenario 1 - Existing EP Page - Wonky and incorrect positioned Loading Favicon_**
![existing ep - loading indicator - incorrect](https://cloud.githubusercontent.com/assets/23063044/22432474/0058eb54-e6e3-11e6-9339-9598b961de92.PNG)

### Expected Results
**_Correct Favicon Overlapping_**
![loading favicon - certification](https://cloud.githubusercontent.com/assets/23063044/22431599/198a20dc-e6e0-11e6-9b99-99f7cd09fca6.PNG)

**_Correct Loading Favicon positioning_**
![existing ep - loading indicator - correct](https://cloud.githubusercontent.com/assets/23063044/22432458/f3b2fe08-e6e2-11e6-8203-38ec0e55039e.png)

**Comment by lakohl** [comment]
@shanear to provide screenshot

**Comment by shanear** [comment]
<img width="434" alt="screen shot 2017-01-19 at 5 27 50 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128063/d5b971d0-de6c-11e6-9636-a6e8a8c3e01d.png">

**Comment by kierachell** [comment]
<img width="981" alt="screen shot 2017-02-07 at 13 49 00" src="https://cloud.githubusercontent.com/assets/18075411/22708372/05eb35e2-ed44-11e6-9cbf-394a52b91595.png">
<img width="1273" alt="screen shot 2017-02-07 at 13 50 13" src="https://cloud.githubusercontent.com/assets/18075411/22708371/05e89c56-ed44-11e6-9dfe-15f221136226.png">
👎

**Comment by shanear** [comment]
Yep, I noticed this too. A pretty high priority to fix since we can't really deploy until we do. @mdbenjam

**Comment by kierachell** [comment]
**PASSED**
<img width="1256" alt="screen shot 2017-02-09 at 13 34 34" src="https://cloud.githubusercontent.com/assets/18075411/22797527/9565c686-eecc-11e6-9406-34a2710698d6.png">
<img width="687" alt="screen shot 2017-02-09 at 13 35 45" src="https://cloud.githubusercontent.com/assets/18075411/22797555/af7f0262-eecc-11e6-9724-f2797a0d8458.png">

**Comment by kierachell** [comment]
Note, merging a PR for this issue created a `bug`
