### ISSUE TITLE
RAMP appeals | Interim solution for attorney editing/adding issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7167]
## Background
For October 1, Caseflow Queue de-scoped attorney ability to add/edit AMA issues. This is for a few reasons (list not exhaustive):
- complexity of connecting decision issues to request issues
- decisions in flight around surfacing other VBMS issue data (e.g. issue type `Service connection`, `Increased rating`; diagnostic code, etc.)
- incomplete user research to validate MVP prototypes and designs
- running out of time

For the RAMP appeals pilot, October 1, we decided that 
- Attorneys would not add/edit issues in Caseflow. They would write them into the decision Word document through the IDT. They would email Del Yvonne Whitehead (Board contact person for RAMP appeals pilot) when they needed to edit an issue. 
- We would create a spreadsheet with the decided issues and their dispositions so that AMO could manually create EPs. This would have to include the added/edited issues.
- Caseflow would create supplemental claims 
- Caseflow would backfill these issues when we have editing functionality available

Nicholas provided some more context this morning as to how this will not suffice:
> Late yesterday I was talking with Sadia Sorathia about ways to lessen Del's workload (Del is the Senior Counsel that is helping manage the manual processes required for RAMP), and I realized that it is highly likely that many appeals will need to add issues - specifically TDIU.

> Even under AMA, it will be very common for there to be a finding of DTA error related to an IR claim, which results in a TDIU remand - the TDIU claim is present before the claim is decided in many IRs, even if never addressed by the RO, and that will mean that the case will be sent back for an SC for exams/records in support of TDIU.

> This is perhaps even more likely than it is today, because of the new attorney standards that the Board told us last week that they are putting out (we do not have details, but the attorneys can get credit based on # of issues, rather than just number of cases). In other words, attorneys will be incentivized to add this issue to help them with their production, especially since the Board is going to try and pummp out over 90K cases in FY2019, a probably unreachable total (notably, this new standard will probably make that total even less likely to be attained).

> The other significant problem this raises is related. Because attorneys can now get credit based on issues, if those issues are not able to be added to Caseflow now (and will have to be back-filled in a month or two), a) there could be a _lot_ of them, and b)  we can expect attorneys and judges and chiefs and DVC, etc. to be up in arms about the fact that the correct credit is not clear.

**Comment by nicholasholtz** [comment]
Right now the plan is for attorneys to email to Del when they have issues that need to be added. That email is just going to be a free-text email that will need to be integrated with the disposition data so EPs can be created, and ultimately will need to be backfilled into Caseflow in ~ a month. 

Proposal: since emailing issues is problematic, what if we either:
  1. Provided a free-text field for adding issues that attorneys can have, so that we will knwo at least numerically that there is an additional issue, and will actually store it in caseflow, even if it isn't in the format we will ultimately need it in (we will still need to backfill this into the ultimate issue format)
  2. Provide the same VACOLS-type drop down that is available for legacy issues, with the same need to backfill issues after the issue format for RAMP/AMA is finalized.

**Comment by laurjpeterson** [comment]
Mark, Nicholas, and Alex had a conversation on this topic 9/27:

Their takeaways were:
- We expect that on the high end, the number of RAMP cases we'll process in October where an attorney would want to add an issue would be in the low hundreds
- We should obtain the updated attorney performance formula
- Given those bits of information, we should make a guess re: when we can realistically expect to deploy an add/edit issue flow (say, November) and get a better sense of the potential impact on each individual attorney if we do not allow them to add issues until then
- Given our current knowledge, it doesn't seem clear that there will be a materially negative impact on attorney performance ratings if we don't build and release a quick fix, and instead wait until we have a better sense of our desired final state and build toward that (very open to changing gears here as the information changes)

Slack thread: https://dsva.slack.com/archives/C7P7M26QM/p1538083512000100?thread_ts=1538051483.000100&cid=C7P7M26QM

Closing.
