### ISSUE TITLE
End Product | Missing RO location name in the Station field

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#717]
# Description
The "Station of Jurisdiction" field isn't always showing the Station code concatenated with RO Location Name.  This appears to occur when certain Special Issue selected on the `Decision Review` page.   on the "Special Issue" selected on the Decision Review page, it doesn't show the RO Location Name (City and state for some).

**Environment:**
- [ ] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [x] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [x]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
**Scenario 1**
1. Click on the Establish Next Claim button.  The `Decision Review` page will be rendered.
1. Select "Private Attorney" as a _"Special Issue Category"_.
1. Click **_Create End Product_** button. The "Station of Jurisdiction" contains the value "313" should read "313 - Baltimore, MD"on the `End Product` page.

**Scenario 2**
1. Go to Decision Review page.
1. Select "Mustard Gas" as a _"Special Issue Category"_.
1. Click **_Create End Product_** button. The "Station of Jurisdiction" contains the value "351 - Muskogee",  should be "351 - Muskogee, OK" on the `End Product` page.  

## Screenshots
**_Scenario 1 - End Product Page - "Private Attorney"_**
<img width="910" alt="screen shot 2017-01-19 at 5 35 36 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128399/5b8d1cf2-de6e-11e6-937d-82e72ef06e67.png">

**_Scenario 2 - End Product Page - "Mustard Gas"_**
<img width="939" alt="screen shot 2017-01-19 at 5 35 00 pm" src="https://cloud.githubusercontent.com/assets/1596259/22128398/595e649a-de6e-11e6-9574-7bf6cf34033a.png">

# Related Issues
n/a

**Comment by abbyraskin** [comment]
@lakohl do we want to include the words Regional Office (or RO) at the end? e.g., Muskogee, OK Regional Office (to prepare for potential future routing to shared stations and for general clarity)?

**Comment by lakohl** [comment]
@abbyraskin I def think we should include the name of the city and state on the Station of Jurisdiction. e.g. '351 - Muskogee, OK' I'm assuming all VBMS stations are ROs (is that correct?) f you think in the future we might have station codes for Centers or other non-RO locations then we could expand the label to say '351 - Muskogee, OK RO'

**Comment by abbyraskin** [comment]
also note: if the claim is not getting routed to an RO it goes to AMC. So it would read: "397 - Appeals Management Center" (or whatever their name is by then...).

**Comment by lakohl** [comment]
Good point. In that case I would say we should say '351 - Muskogee, OK RO' and '397 - Appeals Management Center'. 
*We should check on whether the AMC labels are going to incorporate AMC's new name?!

**Comment by kierachell** [comment]
So this works mostly, but...
<img width="1004" alt="screen shot 2017-02-08 at 20 44 28" src="https://cloud.githubusercontent.com/assets/18075411/22765794/27ec0c82-ee40-11e6-984e-6b54bcdff0b2.png">
<img width="1185" alt="screen shot 2017-02-08 at 20 45 27" src="https://cloud.githubusercontent.com/assets/18075411/22765791/27e53010-ee40-11e6-8340-7857b30d6d70.png">
<img width="1218" alt="screen shot 2017-02-08 at 20 46 02" src="https://cloud.githubusercontent.com/assets/18075411/22765792/27e5cbec-ee40-11e6-9efa-0f2209719852.png">
<img width="1315" alt="screen shot 2017-02-08 at 20 48 33" src="https://cloud.githubusercontent.com/assets/18075411/22765793/27e760f6-ee40-11e6-9a81-5470b3a9f305.png">
========
There might be a bit of a bug when going back in the browser:
![dispatchroutingbug](https://cloud.githubusercontent.com/assets/18075411/22765889/9c0e56a6-ee40-11e6-874d-051f6a1d7926.gif)

**Comment by astewarttistatech** [comment]
**PASSED**

Validated on: Preprod
Steps to Validate:
1.Go to dispatch as a caseworker
2.Establish a full grant claim with a working SIC on the Review Decision page
3.Validate on the next page that the SOJ has a code with it's corresponding location. 

Screenshots: 
<img width="1044" alt="screen shot 2017-02-09 at 10 06 38 am" src="https://cloud.githubusercontent.com/assets/23038505/22795953/8fa3163c-eec6-11e6-880b-411a6edc9f2e.png">
