### ISSUE TITLE
DISCUSS 10/3: Tech spec discussion

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#7173]
In a retro we discussed some options around tech specs without google docs. This is a ticket to formalize what we want to do around:  

1. Where should tech specs be located? Should they be in this repo under /docs/tech_specs or in a private repo like appeals-design-research? Or maybe in a private repo by themselves? 

    Pros of being in this repo would be that they're easier to find & read, cons would be that specs with lots of images or screenshots could lead to this repo becoming bloated. Leaning towards this repo for now for ease of use & adoption. Can always migrate content + do a git prune if this section becomes too big.

2. What should the process for tech specs be? Peter had a good idea of doing it in github PRs, however there are other tools like Review board. I've been looking for something like collabedit + inline comments but can't really find one. Leaning towards github PRs for now due to ease of workflow.

3. What should the tech spec template look like? The one I like to use is a variation of Nava's default:  

```
#Tech Spec Title

Tech specs are a lightweight format for documenting technical research and decision making. 
The headings below are guidelines, not rules, so modify your copy as you see fit.
Especially large tech specs may require more headings and subheadings for example. 
Be rigorous in your research and planning, but balance that with forward progress - 
if something is uncertain, document that appropriately and move on if you can. 
Getting feedback early from team mates during tech spec writing can be helpful too.

## Context
What are the related github tickets & issues?
Why are you creating this tech spec? 
What information helps readers understand the rest of this tech spec? 
Who are the stakeholders?

## Overview
Exec summary of the entire spec. 
Usually written at the end after comments have been addressed. 
Team leads should be able to glance at context + this paragraph and approve/disapprove.

## Open Questions
Sometimes we're missing information needed to fully spec work. What is missing? 
Who can answer these questions, and how might it affect the recommendation? 
Each question should be flagged to a person who can potentially answer it.

## Implementation
Add notes about recommended action items. This will change as you get feedback. 
Is the work sufficiently defined such that someone else could pick it up? Is the work parallelizable?

### Option A
If there are multiple implementation paths, note the options and the pros and cons of each.

#### Pros
#### Cons

## Rollout plan
Is there a phased rollout? Are there any rollout risks? What needs to be done to mitigate risks?

## Follow up issues
Add any notes about follow up tickets or tasks that might need to be created or changed here.

```

## ACTION ITEMS
- create a tech-specs folder here (https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/Intake/Product%20Documents)
- put the template in that folder

**Comment by shanear** [comment]
Here's a place where tech specs are. We could add a folder there?

https://github.com/department-of-veterans-affairs/appeals-pm/tree/1c52406858bf2a5a6633bda0b6e52088430aee7a/caseflow/tech_specs

**Comment by kencheeto** [comment]
1. I vote separate repo, one of the existing docs repos we have
2. I vote google doc that gets copied into github when more stable, we can leave a link to the gdoc in the markdown file. in general i still think markdown is very limited in density compared to a gdoc, looking at other tech specs we've written, but happy to give it a shot
3. lgtm! would be helpful to have an example tech spec and walk people through briefly after standup (or pair with someone that is writing a tech spec for the first time

**Comment by pkarman** [comment]
1. +1 to appeals-pm repo
2. +0 on google doc. If the repo is the document-of-record, I don't care what happens before it gets there. I would personally do .md PR and skip the google doc part, since it seems like extra work, but I'm fine if others want to work it out that way. In that sense, the gdoc is like whiteboarding in a async/distributed-team-friendly way.
3. lgtm

**Comment by leikkisa** [comment]
1. 1 to appeals-pm repo, plus making our own "intake" folder
2. +0 on Google doc. Would rather have fewer places to look than more features.
3. Yay, love that there's a template.  Would love a section for connected Github tickets (like the design-research ones) and PRs.  Sometimes I'll find out later that there were a bunch of design tickets related to the thing I'm working on that had useful info.
