### ISSUE TITLE
Intake | Create contentions fails if two contentions have identical text

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7176]
A bug popped up in prod today where a RampRefiling was created with two contentions with identical texts (see: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/ramp_refiling.rb#L72). Since we match the issue by text, both created contentions are mapped to the first ramp issue.

This causes us to continually retry creating the contentions. Which is not good.

**Comment by pkarman** [comment]
does this address it?

```diff
diff --git a/app/models/end_product_establishment.rb b/app/models/end_product_establishment.rb
index 74d8ca342..c499d4c7d 100644
--- a/app/models/end_product_establishment.rb
+++ b/app/models/end_product_establishment.rb
@@ -81,7 +81,7 @@ class EndProductEstablishment < ApplicationRecord
     # Currently not making any assumptions about the order in which VBMS returns
     # the created contentions. Instead find the issue by matching text.
     create_contentions_in_vbms(issues_without_contentions.pluck(:description)).each do |contention|
-      issue = issues_without_contentions.find { |i| i.description == contention.text }
+      issue = issues_without_contentions.find { |i| i.description == contention.text && i.contention_reference_id.nil? }
       issue && issue.update!(contention_reference_id: contention.id)
     end
```

**Comment by shanear** [comment]
Validation is blocked on https://github.com/department-of-veterans-affairs/caseflow/issues/7177 so we can clean up the data and try again

**Comment by shanear** [comment]
![screen shot 2018-10-05 at 2 42 09 pm](https://user-images.githubusercontent.com/1596259/46553974-e19ea200-c8ac-11e8-9b35-759e046f7cbd.png)
VBMS is looking okay, need to check Caseflow DB

**Comment by shanear** [comment]
confirmed this is connecting correctly in the DB as well :+1:

**Comment by shanear** [comment]
Because our code isn't DRY, this is breaking for RampRefilings (works for AMA claim reviews)

**Comment by shanear** [comment]
👍
