### ISSUE TITLE
AMA Decisions | Save request issue to resulting rating issue mapping

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7178]
When a rating is made (i.e. the decision is made) on a HLR or SC in VBMS-R, users will be forced to map each rating issue to a contention (which would be represented by a request issue generated at intake). We can query and use this mapping to store which rating issues were the result of which request issues (via #6545).

This will allow us to perform certain eligibility checks such as preventing previously appealed issues from being re-appealed, and preventing previously higher level reviewed issues from being higher level reviewed again (#5244).

requires #6545

## Acceptance Criteria
- When the EP for a HLR or SC is cleared, Caseflow should query which rating issues resulted from which contentions, and thus which request issues. That relationship of rating issues to contentions should be saved in the database.

## Notes
- There can be multiple rating issues mapped to a single request issue

## Technical Notes
This should happen in the exact same place where we are generating a follow up Supplemental Claim.

**Comment by pkarman** [comment]
@shanear by

> This should happen in the exact same place where we are generating a follow up Supplemental Claim.

did you mean? https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/higher_level_review.rb#L72

Or some where else?

**Comment by shanear** [comment]
> did you mean? https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/higher_level_review.rb#L72

> Or some where else?

Since it needs to happen for SC and HLR, probably a little further up the call stack. Like here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/claim_review.rb#L71

**Comment by shanear** [comment]
working! 

```
irb(main):018:0> sc.request_issues.map { |i| RatingIssue.find_by(request_issue: i) }
[2018-10-12 17:26:57 -0400]   RatingIssue Load (0.8ms)  SELECT  "rating_issues".* FROM "rating_issues" WHERE "rating_issues"."request_issue_id" = 317 LIMIT $1  [["LIMIT", 1]]
[2018-10-12 17:26:57 -0400]   RatingIssue Load (0.5ms)  SELECT  "rating_issues".* FROM "rating_issues" WHERE "rating_issues"."request_issue_id" = 316 LIMIT $1  [["LIMIT", 1]]
=> [#<RatingIssue id: 1, request_issue_id: 317, reference_id: "118688", profile_date: "2018-10-10 18:05:31", decision_text: "Service connection for Back is granted with an eva...">, #<RatingIssue id: 2, request_issue_id: 316, reference_id: "118689", profile_date: "2018-10-10 18:05:31", decision_text: "Evaluation of PTSD, which is currently 30 percent ...">]
```

I think we'll probably need to work out some edge cases for this for when the data is funky or not like we expected, but I'm cool with closing this for now
