### ISSUE TITLE
CSS Login | Navigate user to Dispatch Caseworker Home page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#719]
As a Caseworker, when I attempt to access the Dispatch homepage when not logged in, I would like to be navigated to the CSS login page. Upon successful login, I would like to be returned to the Dispatch homepage

# Acceptance Criteria
1. Verify that when a user tries to load the dispatch homepage, they are navigated to the CSS login page first. After logging in, they are redirected back to dispatch

# Mockup
**_View - Casework Home page_**
![image](https://cloud.githubusercontent.com/assets/23063044/22427804/88001ade-e6d2-11e6-9050-0764fedb3dc2.png)

# Related Stories
n/a

**Comment by astewarttistatech** [comment]
@joofsh Can you take a look at this again?

When signed-out of caseflow and cookies cleared, I tried to access Dispatch (https://certification.cf.uat.ds.va.gov/dispatch/), logged in and was taken to the unauthorized page. 

Screenshots: 
<img width="1372" alt="screen shot 2017-02-06 at 2 13 26 pm" src="https://cloud.githubusercontent.com/assets/23038505/22662341/9ed98c96-ec76-11e6-81b3-65b12908f88c.png">

**Comment by joofsh** [comment]
@astewarttistatech This happens because we do special magic with System Admins (where you can switch your "functions"). When you initially login, you start with zero functions and have to add them through the functions page first.

Unfortunately I don't think there's an easy way to test this w/o a user that specifically has the "Establish Claim" role. 

@shanear Probably a dumb question, but is there an easy way to create new users/roles on UAT?

**Comment by shanear** [comment]
@joofsh Yeah, I usually email Raul (Saldivar, Raul E., OEDAUSTIN <Raul.Saldivar@va.gov>)

**Comment by joofsh** [comment]
@astewarttistatech to validate this:
- Hit the dispatch url not logged in
- Verify it redirects you to CSS login

That's sufficient to verify the code changes here

**Comment by astewarttistatech** [comment]
Discovery! Since I cannot set a function, it might be the reason i keep getting the "Drat!" page. @joofsh Does that makes sense?

**Comment by astewarttistatech** [comment]
@nikitarockz see the above comment. This is to be expected behavior based on the current functionality, this ticket, in order to work, would require a general user scenario aside from the different functions that can be toggled on and off.
