### ISSUE TITLE
Decision Review: Diary Note and UI for Partial/Remand with Special Issues in VACOLS

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#720]
When user attempts to create an EP for Remands and Partial grants with x Special Issues do not allow them to create the EP, but do change the location in VACOLS and attach a diary note noting the special issue.

NOTE: we only route special issues in VACOLS this way

1. We should also add a diary note for Partial Grants and Remands to the case.
1. If we can create an EP for the special issue, we should update the Congrats page (provide copy @lakohl)
1. If we can't create the the EP, skip the EP creation screen and go to the congrats screen. (confirm @lakohl)

**Comment by lakohl** [comment]
Assigning to @abbyraskin for a list of special issues to which this rule applies,  routing instructions, and Diary note copy

**Comment by lakohl** [comment]
I will provide a design for the modal

**Comment by abbyraskin** [comment]
Below is my current understanding of special issues not yet supported for EP creation in Caseflow (subject to change pending feedback from AMC stakeholders), their corresponding location change in VACOLS:

Education Debt - Location 50
Waiver of Overpayment - Location 50
Insurance - Location 50
Foreign Claim - Location 50 
Pension - Location 50
DIC, death, accrued benefits - Location 50
VAMC - Location 54
National Cemetery Administration 

@cmgiven do you know NCA's location in VACOLS? Also, do you know if VAMC is both 51 and 54?
also also, is there a compelling "good data" reason to check these in from location 97 to location 98 (behind the scenes) prior to sending them to a non-AMC location?

**Comment by abbyraskin** [comment]
oops, one more question for you @cmgiven: do you know the character limit on diary notes?

**Comment by lakohl** [comment]
Super helpful. Thanks!

**Comment by cmgiven** [comment]
I see two potential fields in the ASSIGN table:

1. "Requested Activity," TSKRQACT, 280 characters
2. "Response Notes," TSKRSPN, 200 characters

**Comment by cmgiven** [comment]
"Remand NCA" is 53.

"Remand VAMC" is 51. 54 is "Remand VHA CO."

As far as I know, no reason to checkout to 98. Staying in 97 until routing to 50 or 98 as appropriate is more consistent with historical data, although 97 -> 98 -> 50 does happen.

**Comment by abbyraskin** [comment]
thanks @cmgiven!

**Comment by abbyraskin** [comment]
@lakohl maybe something like this for diary copy?

The AMC* is transferring this claim to [VACOLS RO code] for further development as it contains a [special issue] issue. EP 170 [label] has been established in VBMS station [station #] for this claim.

*ARC?

**Comment by shanear** [comment]
Blocked until we confirm we can add notes in BGS

**Comment by shanear** [comment]
@lakohl provide UI for what happens

**Comment by lakohl** [comment]
When EP cannot be created, one approach would be to message the user on separate page:

![screen shot 2017-02-07 at 11 52 40 pm](https://cloud.githubusercontent.com/assets/4975959/22724029/767816ac-ed91-11e6-980b-f2a6187e5398.png)

Followed by:
![screen shot 2017-02-08 at 12 01 37 am](https://cloud.githubusercontent.com/assets/4975959/22724079/d024b41c-ed91-11e6-8853-911d5b3fa98e.png)

@abbyraskin would like to know your thoughts on page vs. modal and on copy.

**Comment by lakohl** [comment]
When an EP is established, the user would travel from the EP creation form page to this Congratulations page:

![screen shot 2017-02-08 at 12 05 59 am](https://cloud.githubusercontent.com/assets/4975959/22724155/6aad3d74-ed92-11e6-85c0-9e5bd31875e1.png)

**Comment by lakohl** [comment]
this seems like a duplicate and we have already built this.

**Comment by shanear** [comment]
I believe so too. Closing.
