### ISSUE TITLE
Edit VBA Issues | Too many updates too fast can cause bugs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7201]
When validating #6212, I noticed that submitting 2 or more edits in rapid succession can cause the processing of `RequestIssuesUpdate` to bug out (not being able to find contentions because they were already removed).

I think (?) the solution here might be to prevent going to the edit issues screen if there is a `RequestIssuesUpdate` that is pending processing. There may be other solutions too

**Comment by jiahuang** [comment]
We discussed this and came to the conclusion that on submit we should:

1. Check the submitted_at & processed_at fields for a RequestIssuesUpdate
2. If the submitted_at field is filled but processed_at is not, make the submit action a no-op and flash an error message telling the user to wait a few min.

**Comment by pkarman** [comment]
Tech implementation note: could probably add an `submitted?` method to the `app/models/concerns/asyncable.rb` concern so you end up with:

```ruby
if submitted? && !processed?
```

**Comment by shanear** [comment]
![screen shot 2018-10-10 at 3 35 32 pm](https://user-images.githubusercontent.com/1596259/46761369-48073400-cca2-11e8-913f-c10d3c955bbb.png)
nice!
