### ISSUE TITLE
AssociateRatingIssues is not working for non-disability issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7206]
Whenever I try and intake an HLR or SC with an issue that is not a disability issue, the ClaimService associateRatingIssue request throws an error, preventing the intake from processing.

Here is an example of an error
```
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Unable to create contention, rated issue does not exist</faultstring></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::AssociateRatedIssues:0x00007f585c756398 @claim_id="600138280", @rated_issue_contention_map={"110377"=>"306282"}>
```

**Comment by shanear** [comment]
getting in touch with Nate about this

**Comment by shanear** [comment]
Nate got back to me and thinks it's a bug between VBMS and BGS. Well probably talk about it in our weekly sync.

**Comment by leikkisa** [comment]
SR 837173 (for using in meetings with BGS)

**Comment by mc-usds** [comment]
Per 10/18 meeting update, the fix should be in UAT.
Is this something that is tested through connect_vbms?

**Comment by shanear** [comment]
Woohoo this works in UAT! @mc-usds
