### ISSUE TITLE
End Product | Set Station Code to "Louisville RO" based on Special Issue Category

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#721]
As a Caseworker, I would like to always have the "Station" value on the `End Product` page set to the Louisville RO when the _Special Issue Category_ "Contaminated Water at Camp LeJeune" has been selected on the `Decision Review` page so that it reduces the human error and the EP is routed to the correct Regional Office for handling of all decision type appeals -- full grants, remands, and partials.

# Acceptance Criteria
1. Verify that the when only the following _"Special Issue Category"_ has been selected and clicks the **_Create End Product_** button on the `Decision Review` page, the _"Station"_ value is set to the "327" on the `End Product` page.
     -  Contaminated Water at Camp LeJeune 

# Mockup
**_View - Decision Review Page - Special Issue Category "Contaminated Water at Camp LeJeune" selected_**
![image](https://cloud.githubusercontent.com/assets/23063044/22401552/32ea5d02-e5a6-11e6-9666-cb5639a28357.png)

**_View - End Product Page - Station Code_**
![image](https://cloud.githubusercontent.com/assets/23063044/21644621/54977bb8-d25c-11e6-966a-968a2a2916b2.png)

# Related Stories
Decision Review | Special Issue Category | Add new category "Contaminated Water at Camp LeJeune" #757

**Comment by shanear** [comment]
@abbyraskin can you follow up with more detail here?

**Comment by abbyraskin** [comment]
@shanear I edited the description above.
