### ISSUE TITLE
Add "Recall task" option to recently completed tasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7213]
Co-located staff have no way to "recall" a task after it has been assigned back to an attorney. Currently, one common occurrence is that a co-located staffer charges a case back to an attorney in VACOLS after completing whatever needed to be done, but remembers one task that they forgot so they charge it back to themselves effectively reclaiming the task as their own. Our current implementation of tasks do not allow for this behaviour.

If/when we [add a tab to display recently completed tasks](https://github.com/department-of-veterans-affairs/caseflow/issues/7211), we could display an action to recall a task for some period of time as an available option in the actions dropdown there. We will need to determine how long to display that option but that seems like one solution (2 hours? Until the parent task is modified?).

Additionally, while implementing this it may be worthwhile to consider other actions we may want to "undo" and determine if we want to think about broader undo functionality (perhaps a task could sit in a queue of things that can be undone for some period of time so we don't update the parent task and no changes can be made to it).

## Acceptance criteria
* Allow folks to recall a task if they have hastily marked it as complete

**Comment by araposo-tistatech** [comment]
Will need Board buy in & prioritization as this will be a significant implementation.
