### ISSUE TITLE
Make copy changes for special issues page for legacy appeals

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7216]
Allow attorneys to select special issues during the checkout flow for legacy appeals like we do for AMA appeals. This sets us up to deprecate Caseflow dispatch.

## AC
- Create a screen titled `Select special issues`
- `Select special issues` screen comes after selecting 'Decision Ready for Review' in the attorney checkout flow
- Special issues include all in the below mock EXCEPT `Hearing - including travel board and videoconference`

## Background
See [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1536261263374/a50fb8424a7bff4e04c49d0b4023a6a63e519f09) for flow.

This is how special issues are currently displayed in Caseflow Dispatch. 
<img width="670" alt="screen shot 2018-09-06 at 7 12 30 pm" src="https://user-images.githubusercontent.com/27704093/45189842-e833ee00-b208-11e8-85f9-5d7b36a437c3.png">

## Mocks

![image](https://user-images.githubusercontent.com/40216950/50693029-ca826400-1003-11e9-8320-4f1d853bd691.png)

## Reference - AMA issue
https://github.com/department-of-veterans-affairs/caseflow/issues/6854

**Comment by allyceh** [comment]
@laurjpeterson @aroltsch Latest mock is above for copy review. Updated based on @nicholasholtz feedback.

**Comment by allyceh** [comment]
@laurjpeterson @nicholasholtz @aroltsch I posted another mock above with updates based on feedback from Josh Freeman. Unless there is additional feedback, this mock is ready for dev.

Consensus: Attorneys aren't going to know what a non-rating issue is. If anyone has a better way to describe it, let me know your thoughts. Hopefully we can automatically check "non-rating issue" in the future if those issues are on the cases.
