### ISSUE TITLE
Separate reassign and assign logic

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7229]
We currently do a lot of work to ensure Judges can both assign and reassign tasks to attorneys. However both assign and reassign goes through the same UI flow. It seems likely that separating these flows, or moving the logic to the backend could make our code simpler. We should hold off on this until we have generic queues working, since I think there may be an opportunity to share code between the two.

**Comment by laurjpeterson** [comment]
[non-urgent] is this still relevant, considering refactoring work since this ticket was created? @lowellrex

**Comment by lowellrex** [comment]
I think this is already handled! Closing it out!
