### ISSUE TITLE
End Product | Create End Product | Set Location code in VACOLS for Partial and Remand grants

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#723]
As a Caseworker, I would like to set the _"Location Code"_ in VACOLS based on specific _"Station"_ code for all remands and partial grants so that when the Regional Office receives the EP it can be picked up by a specific team.

# Acceptance Criteria
1. Verify that when the _"Station"_ code value is 397 (AMC), no Special Issues have been selected and the **_Create End Product_** button has been clicked, set the _"Location Code"_ in VACOLS to "98".
1. Verify that when the _"Station"_ code value is not 397 (AMC), has Special Issues selected except for VAMC and "National Cemetery Administration" and the **_Create End Product_** button has been clicked, set the _"Location Code"_ in VACOLS to "50".
1. Verify that when "VAMC" has been selected as the Special Issue and the **_Create End Product_** button has been clicked, set the _"Location Code"_ in VACOLS to "54".
1. Verify that when "National Cemetery Administration" has been selected as the Special Issue and the **_Create End Product_** button has been clicked, set the _"Location Code"_ in VACOLS to "53".

# Mockups
**_View - Decision Review Page Allows for selecting Special Issues_**
![image](https://cloud.githubusercontent.com/assets/23063044/22401552/32ea5d02-e5a6-11e6-9666-cb5639a28357.png)

**_View - End Product Page shows station code_**
<img width="560" alt="screen shot 2017-01-30 at 12 15 53 pm" src="https://cloud.githubusercontent.com/assets/4975959/22433292/e42cfde6-e6e5-11e6-918a-92841958c8ef.png">

# Related Stories
n/a

**Comment by lakohl** [comment]
@abbyraskin can you confirm or adjust the instructions above?

**Comment by nikitarockz** [comment]
Sprint Planning
@nikitarockz Add End Product page to mockup.

**Comment by lakohl** [comment]
second mock added above

**Comment by joofsh** [comment]
@lakohl @abbyraskin 

From Chris:

> That looks right, although maybe with one addition, unless I've missed a thread: VHA claims need to get routed to 54.

Do we need to be updating the location for VHA too? We don't currently offer that as a special issue in the dispatch UI

**Comment by lakohl** [comment]
@joofsh It's somewhat confusing bc VACOLS has two locations one for VAMC (VA Medical Care) and one for VHA so we are trying to figure out which one we should send medical claims to. @abbyraskin and I have this on our list to answer in our mtg with AMC tomorrow.

**Comment by joofsh** [comment]
@kierachell This PR made some changes to the establish claim integration code. It would be good if your integration scripts could verify everything still works. thank you!

**Comment by kierachell** [comment]
Can't validate no `UAT` test data to work with in Dispatch

**Comment by astewarttistatech** [comment]
Can't validate in VACOLS as of yet, passing this off to @shanear

**Comment by kierachell** [comment]
Also, any attempt to create an EP with SIC set to _VAMC_ or _National Cemetery Association_ creates a _Cancellation_ modal, no location will be set anyway.
<img width="969" alt="screen shot 2017-02-07 at 10 18 02" src="https://cloud.githubusercontent.com/assets/18075411/22697240/e4a9c9ea-ed1e-11e6-9a5a-00c532a831e6.png">
<img width="947" alt="screen shot 2017-02-07 at 10 18 08" src="https://cloud.githubusercontent.com/assets/18075411/22697239/e4a61674-ed1e-11e6-8dbc-f728b224c619.png">

**Comment by shanear** [comment]
Lets do this as part of preprod testing tomorrow.

**Comment by lakohl** [comment]
I think the trouble you are having here is that we are tackling Special Issues in two Phases.
1) For Phase 1, we will only be handling Special Issues grants for whom we create an EP and which have a single station code on the EP Creation Page. **We should be changing the VACOLS location for those special issues only.** All other Special Issues will trigger a modal that asks the user to process tha claim outside of Caseflow.
1) For Phase 2, we will include VAMC and NCA as well as additional Special Issues in Caseflow. We will then change the VACOLS location automatically for grants with those issues.

**As long as we are in Phase 1 and asking users to process VAMC and NCA cases outside of Caseflow, we should not route those claims in VACOLS.

**Comment by kierachell** [comment]
1. Has been validated to function correctly; the rest of the cases are not implemented and require further revision; pushing this back until we are ready to implement this.

**Comment by shanear** [comment]
@kierachell They are implemented, just unable to be tested because it's dependent on future issues. This is blocked until then.

**Comment by kierachell** [comment]
I suggest updating original acceptance criteria for the passing case;
splitting off the rest of the cases (with appropriate criteria) into separate tickets referencing the blocking future issues

**Comment by lakohl** [comment]
I would suggest taking out AC:
3) Verify that when "VAMC" has been selected as the Special Issue and the Create End Product button has been clicked, set the "Location Code" in VACOLS to "51".
4) Verify that when "National Cemetery Administration" has been selected as the Special Issue and the Create End Product button has been clicked, set the "Location Code" in VACOLS to "53".

Instead, I would suggest adding the following as the last AC:
- Verify that for Partial Grant Special Issue cases where we are creating an EP, a VACOLS Diary note is added : 'The AMC-Partial Grant decision dated [decision date] for John Doe, ID# [123456789], was sent to the ARC but cannot be processed here, as it contains [special issue category] in your jurisdiction. Please proceed with control and implementation of this grant.

- Verify that for Remand Special Issue cases where we are creating an EP, a VACOLS Diary note is added : 'The AMC-Remand decision dated [decision date] for John Doe, ID# [123456789], was sent to the ARC but cannot be processed here, as it contains [special issue category] in your jurisdiction. Please proceed with control and implementation of this grant.

**Comment by shanear** [comment]
Lets just have this story blocked for validation until https://github.com/department-of-veterans-affairs/caseflow/issues/884 is complete.

**Comment by kierachell** [comment]
@lakohl This is still not fully implemented, but I am checking if the AC have changed since 16 days ago.
Can you update the original issue with the latest iteration of expected results - for clarity.

**Comment by lakohl** [comment]
@kierachell you are too awesome! I updated the AC above for VAMC. This is good to go.

**Comment by kierachell** [comment]
Currently not working on `uat`:

Not seeing location change in VACOLS for _VAMC_ or _National Cemetery_

```
certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ] Started POST "/dispatch/establish-claim/1005/review-complete?1489062754821" for 127.0.0.1 at 2017-03-09 07:32:34 -0500
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ] Processing by EstablishClaimsController#review_complete as JSON
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   Parameters: {"vacols_note"=>"The BVA Full Grant decision dated 02/27/2017 is being transfered from ARC as it contains: VAMC in your jurisdiction.", "1489062754821"=>nil, "task_type"=>:EstablishClaim, "id"=>"1005", "establish_claim"=>{}}
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[35mUser Load (0.7ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CASEFLOW1"], ["station_id", "283"]]
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[36m (0.6ms)[0m  [1mBEGIN[0m
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[35m (0.6ms)[0m  COMMIT
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[36m (0.6ms)[0m  [1mBEGIN[0m
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[35mTask Load (0.7ms)[0m  SELECT  "tasks".* FROM "tasks" WHERE "tasks"."id" = $1 LIMIT 1  [["id", 1005]]
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[36mAppeal Load (0.8ms)[0m  [1mSELECT  "appeals".* FROM "appeals" WHERE "appeals"."id" = $1 LIMIT 1[0m  [["id", 140]]
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ]   [1m[35m (0.9ms)[0m  ROLLBACK
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ] Completed 500 Internal Server Error in 212ms (ActiveRecord: 4.6ms)
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ] ** [Raven] Sending event 77688a2924410828f0ec8e9fc8763f9b to Sentry
[certification.cf.uat.ds.va.gov] [172.30.67.69] [2017-03-09 07:32:34 -0500] [CASEFLOW1 ] 
ArgumentError (unknown keyword: station):
  app/services/appeal_repository.rb:201:in `location_after_dispatch'
  app/services/appeal_repository.rb:194:in `update_location_after_dispatch!'
  app/services/appeal_repository.rb:183:in `block in update_vacols_after_dispatch!'
  app/services/appeal_repository.rb:182:in `update_vacols_after_dispatch!'
  app/services/dispatch.rb:73:in `update_vacols!'
  app/controllers/establish_claims_controller.rb:20:in `block in review_complete'
  app/controllers/establish_claims_controller.rb:19:in `review_complete'
  app/middleware/metrics_auth.rb:10:in `call'
```

<img width="1037" alt="screen shot 2017-03-09 at 8 58 46 am" src="https://cloud.githubusercontent.com/assets/18075411/23753366/352979fc-04a7-11e7-96c0-9fbbf14a164a.png">

**Comment by kierachell** [comment]
**PASSED**
works on `uat`;

there's a couple of UI issues that will be generated from this
