### ISSUE TITLE
Confirmation | Add message text when Establish Next Claim disabled

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#724]
As a Caseworker, I would like to have a message next to the disabled Establish Next Claim button on the End Product Confirmation page so that I understand why I am unable to get the next claim in the queue.

# Acceptance Criteria
on both the "EP Cancellation Page" and the "EP Created Page" and "Claim Assigned to EP Page"
1. Verify the styling and position for the "View Work History" button and the "Establish Next Claim" button matches the style guide.
1. Verify that when the Establish Next Claim button is disabled because there are no more claims, the following text is displayed (refer to mockup):
     > There are no more claims in your queue.

<img width="485" alt="screen shot 2017-01-27 at 7 14 27 pm" src="https://cloud.githubusercontent.com/assets/4975959/22392204/dca0b1f8-e4c4-11e6-94c5-9f8cb10811d6.png">

**Comment by lakohl** [comment]
Adding mock and message: There are no more claims to be worked.

**Comment by lakohl** [comment]
<img width="485" alt="screen shot 2017-01-27 at 7 14 27 pm" src="https://cloud.githubusercontent.com/assets/4975959/22392204/dca0b1f8-e4c4-11e6-94c5-9f8cb10811d6.png">

**Comment by shanear** [comment]
This is obsoleted by https://github.com/department-of-veterans-affairs/caseflow/issues/868, closing
