### ISSUE TITLE
Silence karma/legacy test warnings 

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#7241]
fix proptype warnings 

1. Cancel Dispatch modal 
2, HearingScheduling 

<img width="1555" alt="screen shot 2018-10-03 at 11 48 40 am" src="https://user-images.githubusercontent.com/1745984/46422465-70bb8680-c702-11e8-9c28-7f109b626101.png">

**Comment by sharonwarner** [comment]
Fixed in a different ticket.
