### ISSUE TITLE
VACOLS Integrations | Hearings for ROs/dates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7243]
- Create VACOLS method that, given an array of master record ids, will pull the master records' associated children records with the following fields:
    -  id
    - veteran_name
    - appellant_name
    - appeal_type
    - docket_number
    - hearing_location
    - hearing_time
    - appeal_issue_count
    - veteran_street
    - veteran_city
    - veteran_state
    - veteran_zipcode
    - vbms_id
    - hearing_disposition
    - hearing_notes

For context, this method will be used the same way as HearingDayRepository.fetch_hearing_days_slots in HearingDayController.index_with_hearings

**Comment by oscarAtNava** [comment]
I want to confirm the source of some of these fields

 
    -  id (child hearing)
    - veteran_name (appeal)
    - appellant_name (appeal)
    - appeal_type (appeal)
    - docket_number (appeal)
    - hearing_location (parent hearing
    - hearing_time (parent hearing)
    - appeal_issue_count (appeal)
    - veteran_street (appeal)
    - veteran_city (appeal)
    - veteran_state (appeal
    - veteran_zipcode (appeal) 
    - vbms_id (appeal)
    - hearing_disposition (child hearing)

These are the only attributes you need returned to the controller?
