### ISSUE TITLE
Case details - Assign hearing search 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7245]
As a user, I need to be able to select the RO and Hearing date if I get to the case details via search to assign the hearing. 

### Acceptance Criteria
- [ ] Verify that when a user gets to the Veteran Case Details via the search, they launch the assign modal with dropdowns for the Regional Office and Hearing Date
- [ ] Verify the RO date dropdown is Select Regional Office
- [ ] Verify that the hearing date is Select Hearing Date 
- [ ] Verify that the date is disabled dropdown is disabled until the RO is selected

### Mocks
**Default**
![assign hearing search disabled](https://user-images.githubusercontent.com/23316107/46737633-02c71000-cc6a-11e8-9595-638136bf6380.png)

**RO selected**
![assign hearing modal](https://user-images.githubusercontent.com/23316107/46737639-078bc400-cc6a-11e8-81df-e5f07db37f92.png)

**Comment by sharonwarner** [comment]
Already completed through another ticket.
