### ISSUE TITLE
Integration testing frequency and notifications (Discussion on 01/27)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#725]
Now that we have some amazing integration tests (thanks Artem and Alan!), we need to make some decisions surrounding their purpose and how they should be set up:

1) How frequently should integration tests be run? Should they be triggered by an event like a deploy to UAT, or as a gate before a prod deploy?
1) Should we run integration tests against the demo environment as well as UAT?
1) Where should we display the results of the integration tests? Currently we're showing it in the `#appeals-devops` slack channel, but @askldjd has noted that it's creating a lot of noise and we may want to make an `#appeals-qa` channel for it?

See https://github.com/department-of-veterans-affairs/caseflow/blob/master/docs/pipeline.md#integration-testing-and-deployment for our current approach to integration testing. We will update this doc as a result of the outcome of this discussion

## Outcomes

1. Integration tests have to pass before a prod deploy. We will be connecting these jobs in Jenkins. There is a race condition here, which can be solved by passing the commit hash of the current AMI, however slack will have to do until that is implemented.
1. Save all prod AMIs, don't worry about UAT AMIs since they are not all validated
1. Integration test failures should be "louder" than successes so they are immediately handled. 👍 
1. We won't run them against demo, and all demo output goes nowhere 👍 
1. Integration tests run 4 times daily (this already happens) 👍 
1. Explore performance testing options, but better monitoring and scalability are higher priority

**Comment by askldjd** [comment]
Item 3 is addressed. @kierachell is testing #dev_null, and shouldn't spam the channels anymore.

**Comment by amprokop** [comment]
> 1. How frequently should integration tests be run? Should they be triggered by an event like a deploy to UAT, or as a gate before a prod deploy?

Why not both? One thing to keep in mind if we shunt UAT integration tests off to a separate channel is that devs might not see it. Maybe we can post to `appeals-engineering` only if tests fail?

**Comment by kierachell** [comment]
1. What @amprokop said

2. I basically run those like 20 times per hour manually; Depends on how different you want to keep `demo` from `UAT`. On `demo` my tests go through a lot more endpoints/scenartios at this time;

3. What @askldjd said. Can confirm, do not subscribe to `#dev_null` if you want to stay sane.

**Comment by amprokop** [comment]
Re: 2, ideally we would always run them against UAT, since it's much more similar to prod, right? I can see the maintenance time being high if we want to maintain integration tests against both demo and UAT in perpetuity. Not sure what other folks think tho

**Comment by shanear** [comment]
1. Love the idea to make UAT integration test failures loud and in #appeals-engineering or #appeals-development. Any time there is an integration test failure, it's important and someone should be working towards fixing it. Also, so we don't get a bunch of noise, we should make sure the only loud errors are on integration tests that should pass, not experimental tests.

2. I agree with you @amprokop. If there is a gap in our isolation testing (ie: demo) we should address that in our feature tests. Our tests should be thorough, but also readable, maintainable, and not duplicative. @kierachell What do you think? 

3. ❤️ that solution. Thanks @askldjd & @kierachell!

**Comment by shanear** [comment]
Also, we're going to have the live discussion about this after standup on Friday 11/27

**Comment by kierachell** [comment]
1. I'm experimenting with different Slack message formats - I can throw just a generic "something is wrong!" or a backtrace like: 
<img width="443" alt="screen shot 2017-01-24 at 10 19 55" src="https://cloud.githubusercontent.com/assets/18075411/22254614/1f302df4-e223-11e6-9cbe-bf4b8f0b6605.png">
Which, I reckon, is more informative; and louder.

**Comment by shanear** [comment]
1. Integration tests have to pass before a prod deploy. We will be connecting these jobs in Jenkins. There is a race condition here, which can be solved by passing the commit hash of the current AMI, however slack will have to do until that is implemented.
1. Save all prod AMIs, don't worry about UAT AMIs since they are not all validated
1. Integration test failures should be "louder" than successes so they are immediately handled.
1. We won't run them against demo, and all demo output goes to #dev-null
1. Integration tests run 4 times daily
1. Explore performance testing options, but better monitoring and scalability are higher priority

**Comment by shanear** [comment]
Just a "@here" should be loud enough. Besides that, do what you think is most helpful. Also can you make another issue for this? I'm going to close this out.
