### ISSUE TITLE
Intake | Investigate how we can know if a rating came from a RAMP EP

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7256]
For a future issue eligibility story, we will need to be able to know whether a rating was created from a RAMP EP. I think it is possible to do this, we just need to find out how.

**Comment by leikkisa** [comment]
Here's the section in a rating profile which contains this information (note, this has been simplified a little).  I think the best way to go is to use the endPrdctTypeCd is equal to 682 or 683.
```
<rbaProfile>
  <associatedClaims>
    <bnftClmTc>683SCRRRAMP</bnftClmTc>
    <bnftClmTn>RAMP - Supplemental Claim Review Rating</bnftClmTn>
    <claimRcvdDt>2017-11-27T00:00:00-06:00</claimRcvdDt>
    <clmId>63510043</clmId>
    <endPrdctTypeCd>683</endPrdctTypeCd>
    <lockedInd>N</lockedInd>
    <prflDt>2018-01-22T08:53:33-06:00</prflDt>
    <ratingDt>2018-01-23T07:11:41-06:00</ratingDt>
    <statusTc>CLR</statusTc>
  </associatedClaims>
</rbaProfile>
```

**Comment by shanear** [comment]
sweet, sounds good. I'll link this to the relevant issue.
