### ISSUE TITLE
Add new documents prompt to the on_hold tab, but stop moving tasks between tabs as new mail comes in

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7261]
For the colocated queue we move things from on hold to in progress based on whether or not they have new documents. However this seems problematic since new documents are determined based on the last time the user has clicked into Reader. Here are two potential cases.
1) The user completes their task without clicking into Reader. They will always have *new documents*. So their task will never go to on hold, it will always be pending action.
2) New documents come in, the task goes to pending action. The user looks at the task, and clicks on Reader. There are no longer new documents and the case goes back on hold.

I think that’s a more transparent behavior. We could also put a *new documents* icon in the tab to alert them when there is something in the hold tab that has changed.

Relevant conversation: https://dsva.slack.com/archives/C6E41RE92/p1538592320000100

**Comment by laurjpeterson** [comment]
Closing because this is captured in #9361
