### ISSUE TITLE
AMA Edit | Add Issue Landing

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7268]
## Story
For any AMA forms, when a user needs to edit issues, they will click the "Edit in Caseflow" button in VBMS to return to the "Add issues landing page" where they will be able to add new issues and/or remove issues added previously. There are a few "are you sure?" type modals to help reduce errors. [Entire flow via Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537795938997/f5834747503f5a248340b9f3426fbac652812400)

This ticket is focused on the content of the landing page and functionality of the "Add issue" button.

## Technical notes

- We should consider that the intake (/add_issues) and intake edit (:id/edit) flows are similar; it may make sense to share some code.
- Unlike with intake screen (a la #6966), the edit page is not currently being used in prod. We don't have to support the old flow in prod.

## Acceptance criteria
- When you click "Edit in Caseflow" in VBMS, you go to the Add Issues Landing page (URL path should remain /{claim type}/{claim id}/edit where claim type is `higher_level_reviews` and `supplemental_claims`)
- The Add Issues Landing page should display the same fields as what displays on the Add Issues Landing page that's used in the original intake flow (as described in #6966) but should not have the progress bar at the top, the primary button is "save", and the cancel link is "cancel edit"  (see mock).
- The "+Add issue" button should behave the same as how it works in the original intake flow.
- The 'save' and 'cancel' buttons do not do anything (that comes in #7269)

## Notes
- Out of scope:
-- Page title is being changed from "Add Issues" to "Add/Remove Issues" for original and edit flows via #7266 

## Copy
n/a

## Mocks
<img width="625" alt="screen shot 2018-10-04 at 3 33 13 pm" src="https://user-images.githubusercontent.com/11219417/46498227-d4b97a00-c7ea-11e8-83c1-957ae71a3d5d.png">

## How to Validate
 
(no need, Shane's got this :muscle:)

**Comment by kencheeto** [comment]
> For any AMA forms,

@shanear this means HLR and SC but not appeal, right? Since AMA appeals don't have end products?

**Comment by shanear** [comment]
> @shanear this means HLR and SC but not appeal, right? Since AMA appeals don't have end products?

yes, appeals will come in a later story

**Comment by steve-gov** [comment]
<img width="953" alt="screen shot 2018-10-15 at 4 35 46 pm" src="https://user-images.githubusercontent.com/25468689/46984103-7321c700-d098-11e8-8603-930ba16e1c15.png">

Accepted!
