### ISSUE TITLE
AMA Edit | Add Issue Landing | save functionality

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7269]
## Story
For any AMA forms, when a user needs to edit issues, they will click the "Edit in Caseflow" button in VBMS to return to the "Add issues landing page" where they will be able to add new issues and/or remove issues added previously. There are a few "are you sure" type modals to help reduce errors.

This ticket is focused on the landing page's save button and it's destination page.

requires #7268 

## Technical notes
There shouldn't need to be much additional back end logic to support this. We should continue to use `RequestIssuesUpdate`

## Acceptance criteria
- On the Add Issues Landing page, the "Save" button is disabled until an issue is either added or removed.
- When you click the "Save" button, the intake is completed and you go to an Edit Confirmation page.
- When you click "Cancel edit", the intake is canceled and you go to an Edit Canceled page.

## Notes
- The Edit confirmation page can be a very simple dummy page until we work on #7273 

- Out of scope:
-- Design/content for Edit Canceled page will be handled by #7276
-- Design/content for Edit Confirmation page will be handled by #7273 

## Copy
n/a

## Mocks
Same as #7268 

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by shanear** [comment]
So it looks like create contentions fails when you save an edit. This is editing an EP created with the new internal domain code :/

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1013/

**Comment by shanear** [comment]
works!
