### ISSUE TITLE
Caseflow returns 500 when it loses connection to VACOLS

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#727]
This incident was observed during integration testing. It is unclear if Caseflow recovers.

Here's the call stack
```
ActiveRecord::StatementInvalid (OCIException: OCI8 was already closed.: SELECT  "VACOLS"."BRIEFF".* FROM "VACOLS"."BRIEFF" WHERE "VACOLS"."BRIEFF"."BFKEY" = :a1 AND ROWNUM <= 1 ):
  app/services/appeal_repository.rb:29:in `block in load_vacols_data'
  app/services/metrics_service.rb:8:in `block in timer'
  app/services/metrics_service.rb:7:in `timer'
  app/services/appeal_repository.rb:28:in `load_vacols_data'
  app/models/appeal.rb:161:in `find_or_create_by_vacols_id'
  app/models/certification.rb:40:in `appeal'
  app/models/certification.rb:104:in `calculate_already_certified'
  app/models/certification.rb:19:in `start!'
  app/controllers/certifications_controller.rb:10:in `new'
  app/middleware/metrics_auth.rb:10:in `call'
```

At a glance, it doesn't seem like ActiveRecord automatically reconnects.
http://stackoverflow.com/questions/26165681/activerecord-how-to-reconnect-to-postgresql-automatically-when-connection-drops

**Comment by joofsh** [comment]
After talking with Alan, we've decided to solve this by updating the `/health-check` endpoint to return a 400 if the connection to VACOLS becomes dead. To QA this we can:

- Verify regular healthcheck requests still return 200
- Run [tcpkill](https://gist.github.com/vdw/09efee4f264bb2630345) on the UAT instance. I did this by running `sudo tcpkill -i eth0 -9 port 1526` (blocking all traffic to VACOLS port), then run a healthcheck query and verify we get a 400 back

**Comment by kierachell** [comment]
**PASSED**

- Killed the connection to VACOLS with iptables
- Got ELB to rotate the instance
![screenshot_2017-07-14_11-53-21](https://user-images.githubusercontent.com/18075411/28220371-2dff7506-688d-11e7-820f-e38e675de63f.png)
