### ISSUE TITLE
AMA Edit | Add Issue Landing | Unidentified issue alert modal

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7271]
## Story
For any AMA forms, when a user needs to edit issues, they will click the "Edit in Caseflow" button in VBMS to return to the "Add issues landing page" where they will be able to add new issues and/or remove issues added previously. There are a few "are you sure?" type modals to help reduce errors. [Entire flow via Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537795938997/f5834747503f5a248340b9f3426fbac652812400)

This ticket is focused on the "Are you sure?" modal that shows when a user tries to save but hasn't removed an unidentified issue (formerly known as an unknown issue).

requires #7268 

## Acceptance criteria
- From the Add Issues Landing page, when there is an Unidentified issue listed but you click "Save" (you must first add or remove another issue to activate the Save button), a modal appears asking the user to confirm that they really want to save without having removed the unidentified issue.
- When you click "Cancel" the modal closes to reveal the Add Issues Landing page with no changes.
- When you click "Yes, save" save the update and you go to the Edit confirmation page.

## Notes
If https://github.com/department-of-veterans-affairs/caseflow/issues/7271 is complete, and the confirmation modal from that issue also triggers, then both modals should show sequentially in any order.

Out of scope:
- Design/content of the Edit confirmation page are covered in #7273 

## Copy
Unidentified issue
You still have an "Unidentified" issue that needs to be removed and replaced with a rated or non-rated issue.

Are you sure you want to save this issue without fixing the unidentified issue?
Yes, save
Cancel

## Mocks
<img width="676" alt="screen shot 2018-10-09 at 9 41 22 am" src="https://user-images.githubusercontent.com/11219417/46673350-8ec43380-cba7-11e8-84af-c98eb763164b.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by suzchap** [comment]
Ooops! Thanks for catching this. I went ahead and updated the mock to be the right one.

**Comment by shanear** [comment]
![screen shot 2018-10-26 at 2 47 26 pm](https://user-images.githubusercontent.com/1596259/47586829-30c97700-d92f-11e8-8c1e-3665563e019e.png)
Working great 👍
