### ISSUE TITLE
AMA Edit | Add Issue Landing | Issue # change alert modal

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7272]
## Story
For any AMA forms, when a user needs to edit issues, they will click the "Edit in Caseflow" button in VBMS to return to the "Add issues landing page" where they will be able to add new issues and/or remove issues added previously. There are a few "are you sure?" type modals to help reduce errors. [Entire flow via Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537795938997/f5834747503f5a248340b9f3426fbac652812400)

This ticket is focused on the "Are you sure?" modal that shows when a user tries to save but there are a different number of issues listed than when they started. The premise is that during original intake, there would be _something_ logged for each issue written on the list so if the numbers don't match, it's likely something got messed up during editing.

requires #7268 

## Acceptance criteria
- From the Add Issues Landing page, if you edit issues (either add or remove) and the number of issues at the end is different than when you started and you try to click "Save", a modal appears asking the user to confirm that they really want to save give the difference in number of issues.
- When you click "Cancel" the modal closes to reveal the Add Issues Landing page with no changes.
- When you click "Yes, save", execute the update and you go to the Edit Confirmation page.

## Notes
If https://github.com/department-of-veterans-affairs/caseflow/issues/7271 is complete, and the confirmation modal from that issue also triggers, then both modals should show sequentially in any order.

Out of scope:
- Design/content of the Edit Confirmation page are covered in #7273 

## Copy
Number of issues has changed
This review originally had [X] issues but now it has [Y]. 
Please check that it has the correct number.
Cancel
Yes, remove issue

## Mocks
<img width="696" alt="screen shot 2018-10-05 at 9 53 15 am" src="https://user-images.githubusercontent.com/11219417/46539475-91abe500-c884-11e8-93cb-f7fd4ac6804c.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by shanear** [comment]
Works great (forgot to capture a screen shot 😬)
