### ISSUE TITLE
AMA Edit | Update edit canceled confirmation page copy

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7276]
## Story
For any AMA forms, when a user needs to edit issues, they will click the "Edit in Caseflow" button in VBMS to return to the "Add issues landing page" where they will be able to add new issues and/or remove issues added previously. There are a few "are you sure?" type modals to help reduce errors. [Entire flow via Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537795938997/f5834747503f5a248340b9f3426fbac652812400)

This ticket is focused on the Edit Cancelation page that you click "Cancel edit" from the Add Issue Landing page in the edit flow. 

## Technical notes
- The 2 sentences under the page title should be styled as "Lead Paragraph"

## Acceptance criteria
- The Edit Canceled page should be updated to explain that nothing was saved and give directions for returning to VBMS again to make edits (see copy/mocks)

## Notes
- This page already exists but was made adhoc during last round of edit flow work.

## Copy
Edit Canceled
No changes were made to [Veteran's Name] (ID #XXXXXXXXX) Request for [FORM NAME] (VA Form [FORM NUMBER]).
Go to VBMS claim details and click the “Edit in Caseflow” button to return to edit.

## Mocks
<img width="671" alt="screen shot 2018-10-05 at 10 20 47 am" src="https://user-images.githubusercontent.com/11219417/46540799-5c08fb00-c888-11e8-962e-3837280b9d1e.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by shanear** [comment]
![screen shot 2018-10-26 at 4 43 52 pm](https://user-images.githubusercontent.com/1596259/47591645-5f9b1980-d93e-11e8-8ad9-15397bad8f5d.png)
The new form names make the wording fairly awkward now 🤔

**Comment by shanear** [comment]
@kencheeto think we could take "Request for" out of the copy?

i.e. change

> No changes were made to Audrie Croker's (ID #123458311) ~Request for~ Decision Review Request: Supplemental Claim — VA Form 20-0995

**Comment by shanear** [comment]
Looks great 💯 👍
