### ISSUE TITLE
AMA Intake | Add Issue Landing | Include any issue "notes" 

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7289]
## Story
For any AMA forms, either during original intake or during the edit flow, when a user has included optional issue notes when adding rated, non-rated, or unidentified issues, those notes should be display on the Add Issues Landing page. 

## Acceptance criteria

- Rated, non-rated, and unidentified issues should appear consistently on intake and edit flows
- Notes, if present, should appear italicized (as in #7246)
- The notes field and label should not display at all if empty
- Text for unidentified issues, including notes, should be red

## Notes
It looks like this has already been done for [rated and non-rated](https://github.com/department-of-veterans-affairs/caseflow/pull/7246#issuecomment-427113500
) but not the unidentified issues and may or may not have been changed for the edit flow version of the Add Issues Landing page. 

## Copy
n/a

### What it looks like for Unidentified Issues in original intake. 
<img width="698" alt="screen shot 2018-10-05 at 11 22 35 am" src="https://user-images.githubusercontent.com/11219417/46544280-2d435280-c891-11e8-86d8-7cf58d6ac719.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by kencheeto** [comment]
@suzchap @shanear the red here and in https://github.com/department-of-veterans-affairs/caseflow/issues/7293#event-1888622639 is a bit different - do you have a hex code to use or can we find the color in a style guide somewhere?

**Comment by suzchap** [comment]
Good 👀 --- it's the red that's in the [caseflow style guide](http://www.caseflowdemo.com/styleguide) which looks to be #e31c3d

**Comment by shanear** [comment]
this is done. and the red & notes for unidentified issues is captured in https://github.com/department-of-veterans-affairs/caseflow/issues/6990
