### ISSUE TITLE
Complete QR access to Queue

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7290]
[We recently added](https://github.com/department-of-veterans-affairs/caseflow/pull/7281) an organization and task type for Quality Review, changed the judge checkout step to create an instance of the Quality Review task (instead of the BVA Dispatch task), and made it so completing a Quality Review task creates a BVA Dispatch task. As a result we are almost ready to roll Queue access our to the QR team. The list of tasks that still remain is below:

- [x] Add row to map between the Quality Review organization in the Caseflow database and the VACOLS staff table once we know [how QR folks will be identified in VACOLS](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/42#issuecomment-427170744).
- [x] Ensure those folks can access Caseflow.

(☝️ These are the only two tasks that we absolutely must do before we can begin piloting QR queues)
- [x] Determine if there are any specific actions in addition to the generic "assign to team", "assign to person", and "mark as complete" task actions we will need to add for Quality Review.

**Comment by amprokop** [comment]
@lowellrex — do those users have to navigate to ```caseflow.cf.ds.va.gov/queue/quality-review```

**Comment by lowellrex** [comment]
QR folks will have to go to `/organizations/quality-review` to view the team's queue.

As for seed data, I haven't added any yet since we don't know which field in the `vacols.staff` table we will be using to identify these folks. I was planning on adding seed data when I add the migration to create the row in the `staff_field_for_organizations` table. We could add that locally and create fake staff records to test this manually though.

**Comment by amprokop** [comment]
Sounds good! As long as we have some seeds for testing beforehand, that would be good.


```
As for seed data, I haven't added any yet since we don't know which field in the vacols.staff table we will be using to identify these folks.
```

Is this something we should ask Jed?

**Comment by lowellrex** [comment]
Yup! https://github.com/department-of-veterans-affairs/dsva-vacols/issues/42#issuecomment-427170744

**Comment by lowellrex** [comment]
Added the row to the production database to associate QR employees' VACOLS staff records with the caseflow QR organization (`StaffFieldForOrganization.create!(organization: QualityReview.singleton, name: "sdept", values: %w[QR])`) so they should be able to go to `/organizations/quality-review` tomorrow to see the QR tasks when they are created after outcoding (there are currently none). cc @laurjpeterson

**Comment by laurjpeterson** [comment]
Scheduled time for @lowellrex and I to meet with Josh, QR chief tomorrow 10/18.
