### ISSUE TITLE
Add issue edge cases | Add Issue Landing | if duplicate lane

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7291]
## Story
When a user adds issues, they may encounter edge cases where the issue is ineligible. We will not indicate that an issue isn't eligible on any of the add issue selection pages but will indicate it on the Add issue landing page and Confirmation Page so they have the information they need to inform the applicant in the letter they send following intake data entry. If an issue is ineligible in will get logged in Caseflow but not VBMS. [Mural showing edge cases](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430).

This ticket is focused on the scenario where the issue being requested is already in another AMA lane and how we display it's ineligibility on the Add Issues Landing page. This scenario can occur in HLR, SC, or Board Appeal lanes.

## Technical notes

- we will need to query for request issues with the same rating_issue_reference_id is on an active decision review (Appeal, SC, HLR), and include this information so the client can render them as ineligible
- we may need to store additional metadata about the issue's ineligibility (like reference ids, etc)

## Acceptance criteria
- when rendering the list of issues on the add issue landing page, if an issue is already active in an AMA lane, we should use red text and add the 'ineligible' copy below
- when the intake is completed and the issue is being saved, save it in the caseflow db with the ineligibility reason but do not create a contention

## Notes
- Identical wording will be used on the confirmation page #7308 
- this only applies to rating issues for now because we don't have a way to know if nonrating issues are duplicates from another AMA lane

## Copy
[Issue selected] is ineligible because it's already under review as a [SC/HLR/Appeal].

## Mocks
<img width="759" alt="screen shot 2018-10-06 at 10 59 08 am" src="https://user-images.githubusercontent.com/11219417/46572620-24b54f80-c957-11e8-8921-671248963682.png">

## Background issues
- #5228 

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by kencheeto** [comment]
@shanear how do we tell if an issue is already being requested in another AMA lane?

**Comment by shanear** [comment]
> @shanear how do we tell if an issue is already being requested in another AMA lane?

There is a request issue with the same rating_issue_reference_id is on an active decision review (Appeal, SC, HLR).

For non rating issues, we'll probably need to show open issues as options. @suzchap have you worked on this at all?

**Comment by kencheeto** [comment]
okay - I left a technical note about that because i don't think the client currently knows which issues are ineligible or not. let me know if that's off base

**Comment by shanear** [comment]
Sorry the AC was not clearly worded here. It said "another AMA lane", but we really want the issues to be ineligible if they are active in "any AMA lane".

For example: 
If issue B is being appealed, a request issue for issue B on a future appeal should be ineligible

**Comment by pkarman** [comment]
The "active claim review" is the part I'm missing, then. How is that indicated or implemented? I see `EndProductEstablishment` `status_active?` but all the other "active" mentions seem to be in RAMP related models.

**Comment by shanear** [comment]
We only need to account for it for AMA decision reviews. And yeah you are right, it is if the end product establishment attached to it is active

**Comment by pkarman** [comment]
Should there be a unique index on `RequestIssue` `[:rating_issue_reference_id, :removed_at]`?

**Comment by shanear** [comment]
![screen shot 2018-10-26 at 2 35 52 pm](https://user-images.githubusercontent.com/1596259/47585837-7d5f8300-d92c-11e8-8ed5-2e079a5f20ac.png)
![screen shot 2018-10-26 at 2 35 45 pm](https://user-images.githubusercontent.com/1596259/47585839-7e90b000-d92c-11e8-9469-abb12f7b06d6.png)

This is still not marking duplicates appeal/appeal as invalid.

**Comment by shanear** [comment]
I found another problem. It seems like issues that were removed via edit are still tripping this constraint:

![screen shot 2018-10-31 at 1 41 28 pm](https://user-images.githubusercontent.com/1596259/47807622-f129d300-dd12-11e8-957d-1093d05a935f.png)

So in this screenshot, "Service connection for Back is denied." was on this supplemental claim but removed via the edit screen. It's still showing up as active.

**Comment by leikkisa** [comment]
Ah, so when we remove an issue, we should recalculate the eligibility for other issues that have been created afterwards. Which one should get a contention created for it... the one that was intaken first?

**Comment by pkarman** [comment]
#7576 should fix this issue too

**Comment by leikkisa** [comment]
One conversation that Peter and I had, which I think is a separate issue, is if an issue is removed in a way that affects the eligibility of issues that come after it, there should maybe be a way to communicate this to the user.

**Comment by pkarman** [comment]
> This works on old decision reviews, but if i just created them, then it's not working. I think there's still a problem with caching?

yes. The rating issues are cached for 24 hours per https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/ama_review.rb#L17

I suspect that to test this adequately, you'd need to manually clear the cache via rails console after creating the rating issue.

**Comment by pkarman** [comment]
Alternately, we could set a different cache TTL depending on the `RAILS_ENV`.

**Comment by shanear** [comment]
I think we would want to cache whatever comes from BGS, and not whatever is being changed in Caseflow

**Comment by pkarman** [comment]
@shanear I believe that is what we are doing. We should discuss.

**Comment by shanear** [comment]
So in trying to debug this, I retested it in UAT. Now it works lol.

I think there may have been some interaction between the old and the new cached values the first time I tested it.
