### ISSUE TITLE
Add issue edge cases | if duplicate lane | only save in Caseflow

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7292]
## Story
For ALL AMA LANES: When a user adds issues, they may encounter edge cases where the issue is ineligible. We will not indicate that an issue isn't eligible on any of the add issue selection pages but will indicate it on the Add issue landing page and Confirmation Page so they have the information they need to inform the applicant in the letter they send following intake data entry. If an issue is ineligible in will get logged in Caseflow but not VBMS. [Mural showing edge cases](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430).

This ticket is focused on the scenario where the issue being requested is already in another AMA lane and that we save the requested issue and reason for ineligibility to Caseflow but don't save to VBMS.

requires #7291 

## Acceptance criteria

- we save the requested issue and reason for ineligibility
- when 'Complete Intake' is clicked, we do not create a contention in vbms for any ineligible issues due to already being requested in another lane

## Notes
- Out of scope:

## Copy
n/a

## Mocks
n/a

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by kencheeto** [comment]
subsumed by #7291
