### ISSUE TITLE
AMA Intake Confirmation | Happy path updated design

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7303]
(Not technically about the edge cases but needed to complete them.)

## Story
When a user adds issues, they may encounter edge cases where the issue is ineligible. We will not indicate that an issue isn't eligible on any of the add issue selection pages but will indicate it on the Add issue landing page and Confirmation Page so they have the information they need to inform the applicant in the letter they send following intake data entry. If an issue is ineligible in will get logged in Caseflow but not VBMS. [Mural showing edge cases](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430).

This ticket is focused on introducing a revised design for the confirmation page that will be expanded on in following tickets.  The goal of the redesign is to better summarize what's been done to help the intaker populate the letter that will be sent to the applicant. This applies to all AMA lanes. 

## Technical notes
- the paragraph below the page title should be styled as "Lead Paragraph"
- "Edit this notice letter..." sentence should be the appropriate heading (h2?)

## Acceptance criteria
- The confirmation page should look like the mocks below. Follow the "Copy" section for exact copy.
- When one or more contentions are created, the confirmation page should show them, grouped by the EP that they're connected to. If more than 1 EP is created, there would be 2 EP's listed (each with a green checkmark).

### IF SC/HLR
[Veteran name]’s (ID #XXXXXXXXX) Request for [FORM NAME] (VA Form XX-XXXX) has been processed. If you need to edit this, go to VBMS claim details and click the “Edit in Caseflow” button.
Edit the notice letter to reflect the status of requested issues.
[for each EP established]
A [ep type] EP is being established:
[for each contention]
Contention: [contention text]
[if informal conference tracked item was added]
Informal Conference Tracked Item

possible EP types:
Higher-Level Review Rating
Higher-Level Review Nonrating
Supplemental Claim Rating
Supplemental Claim Nonrating

### IF BOARD APPEAL
[Veteran name]’s (ID #XXXXXXXXX) Request for [FORM NAME] (VA Form XX-XXXX) has been processed. If you need to edit this, go to VBMS claim details and click the “Edit in Caseflow” button.
Edit the notice letter to reflect the status of requested issues.
Appeal created: 
[for each issue]
  Issue: [issue selected]

### For SC/HLR
<img width="616" alt="screen shot 2018-10-10 at 5 23 15 pm" src="https://user-images.githubusercontent.com/11219417/46766846-3e38fd00-ccb1-11e8-813f-5faa7319bc26.png">

### For Board Appeals
<img width="615" alt="screen shot 2018-10-10 at 5 24 02 pm" src="https://user-images.githubusercontent.com/11219417/46766881-4e50dc80-ccb1-11e8-9c94-0f416ccf52a5.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by suzchap** [comment]
Copy and mocks have been updated to remove mention of the EP code. If more than one EP is created, there would just be a green check mark section for each.

**Comment by shanear** [comment]
If I make a HLR with 1 unidentified issue, we don't say that we are establishing an EP. We are establishing an EP:

 ![screen shot 2018-10-26 at 1 15 52 pm](https://user-images.githubusercontent.com/1596259/47582071-50f23980-d921-11e8-9b16-e8b4502682e4.png)

**Comment by kencheeto** [comment]
Ah, I will add handling of unidentified issues, good catch

**Comment by shanear** [comment]
![screen shot 2018-10-26 at 1 47 49 pm](https://user-images.githubusercontent.com/1596259/47583532-c95af980-d925-11e8-9ac8-7a9b3983cb58.png)
Also the checkbox section appears to be a little squished

**Comment by shanear** [comment]
<img width="676" alt="screen shot 2018-11-01 at 6 41 38 pm" src="https://user-images.githubusercontent.com/1596259/47884793-8a86e100-de08-11e8-9d47-f510ac98ae1d.png">

This is not the actual text of the contention we make, and I'm wondering if that matters. I'm thinking it should say "UNIDENTIFIED ISSUE - Please click "Edit in Caseflow" button to fix", what do you think @kencheeto?

**Comment by kencheeto** [comment]
@shanear to come to a decision here - wdyt of showing the contention text only (esp since it's prefixed with "Contention" already), and only showing the unidentified description as a part of the warning alert at the top when we add it in #7304 ?

**Comment by shanear** [comment]
>showing the contention text only (esp since it's prefixed with "Contention" already), and only showing the unidentified description as a part of the warning alert at the top when we add it in #7304 ?

I like that plan

**Comment by shanear** [comment]
So for this issue the fix is to say "UNIDENTIFIED ISSUE - Please click "Edit in Caseflow"

**Comment by carolaponce** [comment]
Left align looks great. Black sub-header per our conversation.  Thanks!

**Comment by shanear** [comment]
![screen shot 2018-11-06 at 5 36 29 pm](https://user-images.githubusercontent.com/1596259/48098372-85e87100-e1ea-11e8-9c91-8fadf28dec94.png)
solid 💯
