### ISSUE TITLE
Add issue edge cases | Confirmation | if Unidentified issue

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7304]
(Not technically about the edge cases but needed to complete them.)

## Story
When a user adds issues, they may encounter edge cases where the issue is ineligible. We will not indicate that an issue isn't eligible on any of the add issue selection pages but will indicate it on the Add issue landing page and Confirmation Page so they have the information they need to inform the applicant in the letter they send following intake data entry. If an issue is ineligible in will get logged in Caseflow but not VBMS. [Mural showing edge cases](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430).

This ticket is focused on adding an alert to the new confirmation page (#7303) when an "Unidentified issue" (via this screen #6990 ) has been added. This applies to all AMA lanes. 

requires #7303 
requires #6990
requires #7313 

## Technical notes
- see details for how we store whether or not an issue is unidentified in https://github.com/department-of-veterans-affairs/caseflow/pull/7349

## Acceptance criteria
- After an intake has been completed for any AMA lane, if the review contains any unidentified issues, the confirmation screen will show it as an alert box with instructions on how to come back and edit. 
- After an intake has been edited for any AMA lane, if the review contains any unidentified issues, the confirmation screen will show it as an alert box with instructions on how to come back and edit. 
- If there are multiple unidentified issues, show them on separate lines in the same alert box

## Copy
Unidentified issue
There is still an unidentified issue that needs to be resolved before sending the notice letter.  To edit, go to VBMS claim details and click the “Edit in Caseflow” button.  
Unidentified issue: no issue matched for requested “service connection left shoulder condition.”

## Mocks
<img width="744" alt="screen shot 2018-10-06 at 9 57 15 am" src="https://user-images.githubusercontent.com/11219417/46572094-3ba37400-c94e-11e8-8c00-c2c35ea92256.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by shanear** [comment]
Looks good!

![screen shot 2018-11-26 at 12 32 31 pm](https://user-images.githubusercontent.com/1596259/49031238-6b654000-f177-11e8-844d-805db84c1dc7.png)
