### ISSUE TITLE
Add issue edge cases | Confirmation | all ineligible issues

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7308]
## Story
When a user adds issues, they may encounter edge cases where the issue is ineligible. We will not indicate that an issue isn't eligible on any of the add issue selection pages but will indicate it on the Add issue landing page and Confirmation Page so they have the information they need to inform the applicant in the letter they send following intake data entry. If an issue is ineligible in will get logged in Caseflow but not VBMS. [Mural showing edge cases](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430).

This ticket is focused on adding adding a section for ineligible issues to the new confirmation page (#7303). There are currently 5 scenarios where an issue would be displayed in this section (detailed in copy section). These will be saved in caseflow but not VBMS. This applies to all AMA lanes. 

requires #7303 
requires #7313

## Technical notes
- font-awesome [fa-asterisk](https://fontawesome.com/icons/asterisk?style=solid&from=io)

## Acceptance criteria
- When an issue is added that's ineligible, on either the intake or the edit page, it displays on the confirmation page in it's own section, in red, with the reason it's ineligible.

## Notes
- The copy for the ineligible issues should be the same as on the add_issues page
- Out of scope: displaying issues ineligible due to Appeal -> HLR and Appeal -> Appeal, which will happen in #7344 
- Out of scope: displaying issues ineligible due to opt-ins that haven't been approved by the veteran (#7336 )

## Copy
(note: this copy is also used on the Add Issues landing page as specified in issues #7291 , #7293 , #7300 )

Scenario | Display copy 
--- | --- 
(ineligible) If the request is an HLR and same issue was last processed as an HLR | [Issue selected] is ineligible because it was last processed as a Higher-Level Review and this can't be done twice in a row.
(ineligible) If the request is a Board Appeal and the same issue was last processed as a Board Appeal | [Issue selected] is ineligible because it was last processed as a Board Appeal and this can't be done twice in a row.
(Ineligible) If the request is a HLR and same issue was last processed as a Board Appeal | [Issue selected] is ineligible because it was last processed as a Board Appeal which can't be followed by a Higher-Level Review.
(duplicate) If the request is a SC/HLR/Board and same issue is already being processed in another lane | [Issue selected] is ineligible because it's already under review as a [SC/HLR/Appeal].
(timeliness not overridden) If the requested issue has a decision date older than 1 year and applicant didn't include a request to override | [Issue selected] is ineligible because it has a prior decision date that's older than 1 year.

## Mocks
(Mock shows all ineligible language variations represented in this ticket -- which would never happen in real life)
![v 2 copy 3](https://user-images.githubusercontent.com/11219417/46572566-43671680-c956-11e8-86da-55863d198246.png)

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by carolaponce** [comment]
@allyceh - the copy we discussed

**Comment by shanear** [comment]
![screen shot 2018-11-20 at 12 51 10 pm](https://user-images.githubusercontent.com/1596259/48792718-fb604100-ecc2-11e8-819e-12eb83a004bf.png)
looks 👍
