### ISSUE TITLE
Add test endpoint to reset data for dispatch integration test

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#732]

**Comment by kierachell** [comment]
Will be validated by [UAT Dispatch scripts](https://github.com/department-of-veterans-affairs/appeals-qa/issues/14)

**Comment by astewarttistatech** [comment]
Currently, the issue persists. 

When testing in UAT, Caseflow Dispatch, the scenario where a caseworker is trying to establish a partial grant on the review decision page is greeted by an error (see attached). This is after the cache has been reset. Modifier was 170, just for reference. 
<img width="1130" alt="screen shot 2017-01-31 at 12 02 40 pm" src="https://cloud.githubusercontent.com/assets/23038505/22483930/4903960c-e7cd-11e6-8514-9feca994ddb1.png">

**Comment by kierachell** [comment]
[UAT_logs.gz](https://github.com/department-of-veterans-affairs/caseflow/files/743439/out.gz)

**Comment by kierachell** [comment]
Need to update `test_data_service` to change the date for partial EP to show up 2nd in queue

**Comment by kierachell** [comment]
Works manually 👍 
now time to setup tests!
