### ISSUE TITLE
Fix undefined method bug in Rating model

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#7323]
BGS may return a nil value instead of an empty list, in https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/rating.rb#L72 so we need a little defensive check there. Not sure whether it means we should raise an exception or return an empty array.

ref https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2531/

**Comment by leikkisa** [comment]
We should raise an exception, returning an empty array would erroneously make it seem like there are no timely ratings for the Veteran.

**Comment by shanear** [comment]
I think this was due to BGS returning the locked rating error. (it's still a 200 though)

**Comment by shanear** [comment]
![screen shot 2018-10-12 at 4 32 33 pm](https://user-images.githubusercontent.com/1596259/46892707-728cf480-ce3c-11e8-9d04-7f357747ed76.png)
This looks like it's still happening in UAT. 

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/984/

**Comment by shanear** [comment]
Aaaaand, this is because the code hasn't deployed to UAT, because jenkins is broken. hanging on to this one to re-test.

**Comment by shanear** [comment]
![screen shot 2018-10-12 at 5 12 45 pm](https://user-images.githubusercontent.com/1596259/46894316-11681f80-ce42-11e8-9fe8-c43166aa6ab1.png)
super
