### ISSUE TITLE
Refactor EstablishClaim code

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#733]
Rushing to reach UAT integration deadlines, we incurred some technical debt within our EstablishClaim react page.

Potential refactors:
- [x] Clean up buttons. Make buttons unique to each page
- [x] Split `handlePageChange` routing method into unique methods for each page (i.e. navigateToReview)
- [x] Make each page its own true component. Shift code from parent EstablishClaim into child pages as appropriate
- [x] rename `form` to `establishClaim` in state object for clarity
- [ ] Get `EstablishClaim.jsx` under the 400 lines so that it's within the eslint rule (removing the lint ignore)
- [ ] Possibly move the string to date conversion here (https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/appeal.rb#L213) to BGSService.

**Comment by shanear** [comment]
Added the other refactor we talked about yesterday

**Comment by joofsh** [comment]
@shanear I looked at the code, but this seems like a fine place for that code for now. Moving it anywhere else would cause another loop through the array. I think there's also value in maintaining the "original" response from BGS.  But feel free to split this out to another ticket if you disagree.

I looked at getting `EstablishClaim.jsx` under 400 lines but it did not seem feasible. Will consider the refactoring done for now

**Comment by joofsh** [comment]
To QA:

This was just refactoring, w/o any real changes to functionality. Just a quick smoke test of dispatch should be sufficient

**Comment by kierachell** [comment]
Are these failures related to the refactored code:
<img width="706" alt="screen shot 2017-01-31 at 10 07 23" src="https://cloud.githubusercontent.com/assets/18075411/22471048/3763294a-e79f-11e6-90a9-5f3265fad04f.png">
<img width="713" alt="screen shot 2017-01-31 at 10 07 38" src="https://cloud.githubusercontent.com/assets/18075411/22471047/37612ad2-e79f-11e6-8860-f0ebf985dbac.png">
?
