### ISSUE TITLE
Make webpack bundle improvements

### ISSUE THREAD

**Issue by nolawi** [department-of-veterans-affairs/caseflow#7331]
Related #6864

1. Upgrade to webpack 4
2. Split bundle into two files (vendor files) [separately](https://webpack.js.org/guides/code-splitting/#entry-points). 

Additional wants

1. Lazy loading
2. webpack-bundle-analyzer

**Comment by mdbenjam** [comment]
Great I'll dig into all of this.

**Comment by alisan16** [comment]
Related to #12708. Closing this in favor of the newer issue
