### ISSUE TITLE
Legacy Opt-in | Review page | add opt-in question

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7333]
## Story
[Mural showing all opt-in screens](https://app.mural.co/t/workqueue2001/m/workqueue2001/1538676663322/098da798af658862105ea8d4d5aeb03fa7aaf99a)

When a user has a legacy appeal, they will be allowed to "opt-in" to move one or more of those issues into an AMA lane. The AMA paper forms will have a question on them for the applicant to acknowledge that by checking that box, they understand that any legacy issues listed on that form will be moved out of the legacy lane and into the new AMA lane.

This ticket is focused on adding the opt-in question to the review page. 

## Technical notes
- This should be behind a feature flag

## Acceptance criteria
- When creating an intake for any AMA review, add question in the mock below to the bottom of the review page
- When completing an intake for any AMA review, save the answer to the new question to the database

## Notes
- Out of scope: doing anything with the answer to this question. We'll use the answer in the add issues flow in the future

## Copy
Did they agree to withdraw their issues from the legacy system? 

## Mocks
<img width="545" alt="screen shot 2018-10-10 at 2 08 54 pm" src="https://user-images.githubusercontent.com/11219417/46756711-17b99880-cc96-11e8-9963-46ed4d683c6f.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by nicholasholtz** [comment]
Does this question show up for all AMA review intakes, or does this show up specifically because of something the user has done to indicate that this will be an opt-in?

**Comment by shanear** [comment]
need the feature flag set in UAT to test this

**Comment by shanear** [comment]
![screen shot 2018-10-31 at 1 27 21 pm](https://user-images.githubusercontent.com/1596259/47806717-c8a0d980-dd10-11e8-85c2-967e0a30b5e2.png)

need to validate in the db on the supplemental claim on 123458319 in UAT

**Comment by shanear** [comment]
```
#<SupplementalClaim id: 99, veteran_file_number: "123458319", receipt_date: "2018-10-22", establishment_submitted_at: "2018-10-31 17:51:34", establishment_processed_at: "2018-10-31 20:52:20", benefit_type: "compensation", is_dta_error: nil, establishment_attempted_at: "2018-10-31 20:52:08", establishment_error: nil, legacy_opt_in_approved: true>
```

nailed it 💯
