### ISSUE TITLE
Legacy Opt-in | Add issue | VACOLS modal

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7335]
## Story
[Mural showing all opt-in screens](https://app.mural.co/t/workqueue2001/m/workqueue2001/1538676663322/098da798af658862105ea8d4d5aeb03fa7aaf99a)

When a user has a legacy appeal, they will be allowed to "opt-in" to move one or more of those issues into an AMA lane. The AMA paper forms will have a question on them for the applicant to acknowledge that by checking that box, they understand that any legacy issues listed on that form will be moved out of the legacy lane and into the new AMA lane.

This ticket is focused on the modal that displays VACOLS issues that need to be matched.

requires #7334 

## Acceptance criteria
- The modal reached by the flow in #7334 should show the modal in the mock below.
- A notice of disagreement header should show for each active and eligible legacy appeal (see #7334 for definitions of active and eligible) for the veteran, ordered from most recent to least recent. Any issues on those appeals should be shown below the appropriate header as a radio button.
- The last radio button in the list should be "None of these match"
- Only one item should be selectable from the radio button lists, even if there are multiple appeals.
- If "None of these match" is selected, the "Add this issue" button is enabled, and if clicked, it should be treated as a normal, eligible issue.
- "Add this issue" button is disabled until any item is selected 

## Notes
- Out of scope: if a VACOLS issue is selected from the list, what happens next will be handled by follow up stories (#7336 and #7337)

## Copy
Does issue 1 match any of these VACOLS issues?
None of these match

## Mocks
<img width="549" alt="screen shot 2018-10-10 at 2 53 48 pm" src="https://user-images.githubusercontent.com/11219417/46759044-581c1500-cc9c-11e8-9187-9c54063d213a.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by shanear** [comment]
this and
https://github.com/department-of-veterans-affairs/caseflow/issues/7335

aren't working with prod

**Comment by shanear** [comment]
![screen shot 2018-11-19 at 7 05 47 pm](https://user-images.githubusercontent.com/1596259/48742757-3cf2dc80-ec2e-11e8-856b-52d142952192.png)
There is something off with the radio buttons.

**Comment by steve-gov** [comment]
Radio buttons validated working, can be selected independently. (Mac/ Chrome)

![issues-screencast](https://user-images.githubusercontent.com/25468689/49765092-3cc28b80-fc86-11e8-82f7-47da2c823e21.gif)

**Comment by steve-gov** [comment]
All acceptance criterial are met.
