### ISSUE TITLE
Legacy Opt-in | Add Issue landing and conf | if ineligible

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7336]
## Story
[Mural showing all opt-in screens](https://app.mural.co/t/workqueue2001/m/workqueue2001/1538676663322/098da798af658862105ea8d4d5aeb03fa7aaf99a)

When a user has a legacy appeal, they will be allowed to "opt-in" to move one or more of those issues into an AMA lane. The AMA paper forms will have a question on them for the applicant to acknowledge that by checking that box, they understand that any legacy issues listed on that form will be moved out of the legacy lane and into the new AMA lane.

This ticket is focused on what happens if the answer to the "Did they agree to withdraw their issues from the legacy system?" question on the Review page = NO (because this means they didn't agree to opt-in their legacy issues so we're considering them ineligible). 

requires #7308 
requires #7335 
requires #7333 

## Technical Notes

- we will need to style ineligible issues consistently with different kinds of ineligibility reasons

## Acceptance criteria
- When we intake any AMA lane, when adding an issue, if a legacy issue is selected (#7335):
    - if the opt-in checkbox on #7333 is "no", display the issue as ineligible on the add issues page (see copy below)
    - if the opt-in checkbox is "yes" but the legacy issue selected is ineligible (see #7334 for definitions of eligible), display the issue as ineligible on the add issues page (see copy below)
- When an intake is completed for any AMA lane, ineligible issues should be stored in the database with the reason along with the matched legacy issue id
- Ineligible issues should be shown on the confirmation page using the same design introduced in #7308 (there's a section for ineligible issues)

## Copy
[issue selected] is ineligible because the same issue is under review as a Legacy Appeal but the claimant didn’t choose to withdraw their issue from the legacy system. 

[issue selected] is ineligible because the same issue is under review as a Legacy Appeal and that appeal is outside the window of eligibility.

## Mocks
<img width="799" alt="screen shot 2018-10-11 at 12 27 02 pm" src="https://user-images.githubusercontent.com/11219417/46819163-01bcde00-cd51-11e8-92ac-9f7a39e94fbb.png">

<img width="819" alt="screen shot 2018-10-11 at 12 24 39 pm" src="https://user-images.githubusercontent.com/11219417/46819111-e3ef7900-cd50-11e8-86aa-b83508947b57.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by leikkisa** [comment]
A note from a conversation with Chris Given and Rachel Sauter:
we should show all issues that either do not have a disposition, or where the disposition is one of "Remanded" or "Manlincon Remand". An issue with any other disposition can be safely not shown.

**Comment by leikkisa** [comment]
Nevermind the above, according to Shane all issues can be opted into AMA no matter what the disposition or if they're already closed, based on conversations with AMO.

**Comment by leikkisa** [comment]
If the Veteran does not agree to withdraw, we should only show active issues, not eligible issues.

**Comment by leikkisa** [comment]
https://app.mural.co/t/workqueue2001/m/workqueue2001/1542753396822/853e22ef759a38adf841287c61e75a4a3118c447

**Comment by shanear** [comment]
For active but ineligible:

data setup
```
fn = "700032765S"
inactive = VACOLS::Case.where(bfmpro: "HIS")
active = VACOLS::Case.where.not(bfmpro: "HIS")

ineligible_active = active.where("bfdnod < ? AND bfdsoc < ?", Time.zone.today - 373.days, Time.zone.today - 61.days).first
ineligible_active.update!(bfcorlid:  "700032765S")
```

<img width="1552" alt="screenshot 2019-01-16 09 30 01" src="https://user-images.githubusercontent.com/1596259/51266978-7ebfab00-1971-11e9-98b3-ae112bda49f2.png">

<img width="1552" alt="screenshot 2019-01-16 09 30 07" src="https://user-images.githubusercontent.com/1596259/51266988-82ebc880-1971-11e9-9940-6fd0b0d43a27.png">

DB looks good too
```
irb(main):016:0> HigherLevelReview.last.request_issues.first.ineligible_reason
[2019-01-16 12:30:55 -0500]   HigherLevelReview Load (0.7ms)  SELECT  "higher_level_reviews".* FROM "higher_level_reviews" ORDER BY "higher_level_reviews"."id" DESC LIMIT $1  [["LIMIT", 1]]
[2019-01-16 12:30:55 -0500]   RequestIssue Load (0.7ms)  SELECT  "request_issues".* FROM "request_issues" WHERE "request_issues"."review_request_id" = $1 AND "request_issues"."review_request_type" = $2 ORDER BY "request_issues"."id" ASC LIMIT $3  [["review_request_id", 893], ["review_request_type", "HigherLevelReview"], ["LIMIT", 1]]
=> "legacy_appeal_not_eligible"
```

**Comment by shanear** [comment]
For veteran didn't agree to opt in:
<img width="1552" alt="screenshot 2019-01-16 09 33 24" src="https://user-images.githubusercontent.com/1596259/51267148-f42b7b80-1971-11e9-9d62-840ebc101c36.png">

<img width="1552" alt="screenshot 2019-01-16 09 33 40" src="https://user-images.githubusercontent.com/1596259/51267158-f8f02f80-1971-11e9-8e05-7f5faf581bf9.png">

DB looks good:
```
irb(main):017:0> HigherLevelReview.last.request_issues.first.ineligible_reason
[2019-01-16 12:33:54 -0500]   HigherLevelReview Load (0.8ms)  SELECT  "higher_level_reviews".* FROM "higher_level_reviews" ORDER BY "higher_level_reviews"."id" DESC LIMIT $1  [["LIMIT", 1]]
[2019-01-16 12:33:54 -0500]   RequestIssue Load (0.7ms)  SELECT  "request_issues".* FROM "request_issues" WHERE "request_issues"."review_request_id" = $1 AND "request_issues"."review_request_type" = $2 ORDER BY "request_issues"."id" ASC LIMIT $3  [["review_request_id", 894], ["review_request_type", "HigherLevelReview"], ["LIMIT", 1]]
=> "legacy_issue_not_withdrawn"
```

**Comment by shanear** [comment]
Awesome work! this is 🍏
