### ISSUE TITLE
Legacy Opt-in | Add Issue landing and conf | if eligible

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7337]
## Story
[Mural showing all opt-in screens](https://app.mural.co/t/workqueue2001/m/workqueue2001/1538676663322/098da798af658862105ea8d4d5aeb03fa7aaf99a)

When a user has a legacy appeal, they will be allowed to "opt-in" to move one or more of those issues into an AMA lane. The AMA paper forms will have a question on them for the applicant to acknowledge that by checking that box, they understand that any legacy issues listed on that form will be moved out of the legacy lane and into the new AMA lane.

This ticket is focused on what happens if the answer to the "Did they agree to withdraw their issues from the legacy system?" question on the Review page = YES (which means we're considering this issue eligible). 

requires #7335 
requires #7300
requires #7309
requires https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1712

## Technical notes
- We already have a lot of logic to close VACOLS issues (look at `RampClosedAppeal#close!`)
- The legacy opt-in flow is already behind a feature flag

## Acceptance criteria
- When we intake any AMA lane, when adding an issue, if a legacy issue is selected (#7335):
    - if the opt-in checkbox is "yes" and the legacy issue selected is eligible (see #7334 for definition of eligible), display the issue as eligible on the add issues page, noting that the VACOLS issue will be closed (see copy below)
    - eligible issues with a legacy issue selected ignore timeliness eligibility checks as described in #7300 and #7309 
- When we complete an intake in any AMA lane, if there are eligible issues with a legacy issue selected, the legacy issue id (bfkey) should be stored in the DB.
    - during asynchronous processing of this intake completion, close the legacy issue in VACOLS with a disposition code of "O"
    - if that issue was the last issue on the VACOLS appeal, also close the VACOLS appeal with a disposition code of "O"
    - The contention created should have a "VACOLS Opt-in" special issue issue on it. This will use the same mechanism as the same station special issue (see: https://github.com/department-of-veterans-affairs/caseflow/issues/5281). A service request to create the special issue is being tracked in https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1712. 
- Any closed VACOLS issues should be shown on the confirmation page using the design below

## Notes
- The VACOLS disposition "O" should be added which stands for "AMA Opt-in"
- Now that there are multiple sections that show up on the confirmation page that can occur in different combinations, the order should be: unidentified issue alert (#7304 ) > EP established  > VACOLS > Ineligible.

## Copy
Add issue landing page: Adding this issue will automatically close VACOLS issue: [selected VACOLS issue]
Confirmation page: VACOLS issue has been closed:

## Mocks
<img width="711" alt="screen shot 2018-10-10 at 3 19 28 pm" src="https://user-images.githubusercontent.com/11219417/46760375-ec3bab80-cc9f-11e8-85a9-56f8c54b4cf1.png">
<img width="607" alt="screen shot 2018-10-10 at 5 21 39 pm" src="https://user-images.githubusercontent.com/11219417/46766769-ffa34280-ccb0-11e8-975a-29885af2ff00.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by kencheeto** [comment]
We should pair up on this issue and see if we can break it down / make a plan

**Comment by pkarman** [comment]
> if that issue was the last issue on the VACOLS appeal, also close the VACOLS appeal 

How is the "last issue" determined? @shanear @kencheeto would appreciate any insights.

**Comment by leikkisa** [comment]
Some notes from talking to Chris:
For status (BFMPRO) of ADV or REM, for the most part, having a disposition means the issue is closed. The one exception is if the disposition is ‘3’, which indicates a remanded issue. On appeal where the status is REM (remanded) the issues with disposition ‘3’ are still active.

An appeal in ACT status can have “draft dispositions,” dispositions that an attorney has made, but which the judge has not signed and dispatch branch hasn’t sent out the door.  That could be any disposition between ‘1’ and ‘9’.

**Comment by pkarman** [comment]
more logic notes:
```
ACTIVE:
  - has no disposition
  - OR has a disposition of 3 AND parent appeal is REM

  ELIGIBLE:
  - ACTIVE OR disposition on current white list: [G, X]
  - AND meets date requirements
```

and per @cmgiven:
> in order for a disposition on the white list to be eligible, we need to ensure that its ISSDCLS is _after_ the SOC/SSOC date. Otherwise, we might be showing things that were closed years ago and were thus not addressed on the SOC/SSOC.

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-01-16 10 16 29" src="https://user-images.githubusercontent.com/1596259/51269645-d3662480-1977-11e9-9971-d2dfe6f7d89c.png">

VACOLS issues should also ignore the AMA timeliness reqs too

**Comment by shanear** [comment]
![test](https://user-images.githubusercontent.com/1596259/51288534-7be4aa80-19b1-11e9-886e-71ea68ceaf04.gif)

**Comment by shanear** [comment]
Validated that VACOLS issue/appeal closed properly as well

**Comment by shanear** [comment]
UAT 700032765 033
Works - Edit and add the remaining 4 VACOLS issues, test that the VACOLS appeal was closed
Works - Edit and remove one of the issues, test that the issue and the VACOLS appeal was reopened
Works - Edit and remove the remaining issues, test that they are reopened

**Comment by shanear** [comment]
Woot works with Remands too. 👍

**Comment by shanear** [comment]
So the timeliness checks are properly skipped in intake, but they are not skipped on add/remove issues (edit).

I know this wasn't specifically called out in the ticket 😢but we should fix it.

**Comment by shanear** [comment]
I see the issue. The problem is that we are showing the untimely explanation modal even though it doesn't matter.

<img width="1552" alt="screenshot 2019-01-23 11 09 36" src="https://user-images.githubusercontent.com/1596259/51630598-6a465a00-1eff-11e9-84fa-7e7b1263b829.png">

I selected "No" and added it

<img width="1552" alt="screenshot 2019-01-23 11 10 41" src="https://user-images.githubusercontent.com/1596259/51630648-8cd87300-1eff-11e9-8f60-d0309eb7a148.png">

and it was valid

**Comment by shanear** [comment]
test url: https://appeals.cf.uat.ds.va.gov/higher_level_reviews/600147535/edit

**Comment by shanear** [comment]
woohoo. works!
