### ISSUE TITLE
How do we validate and verify released issues? (Discussion on 2/1)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#734]
There are a couple problems we're having right now.

1) We are deploying twice a week, sometimes without validating that PRs correctly complete the issues they are completing.
1) The support team and other stakeholders cannot easily tell when an issue has been deployed or released.

I believe these two issues are interlaced and there is a way we can help resolve both of them.

## Outcomes
- Each deploy should have release notes. (These can be retroactive)
- We should record any bug released because of unvalidated issue

**Comment by kierachell** [comment]
Does this relate to the current practice of validating only after merges into master?

As in, can we have a separate `prod` or `dev` branch that is merged only after validation? that will provide a history of "worked on" features and "implemented and validated" issues.

**Comment by KHarshawat** [comment]
Regarding 2: Is there some way we can be more formal around release notes to make the communication of what is launched and what is visible to the user easier to track? We don't really take advantage of our "What's new" indicator in our apps either but it would be nifty to use it too.

**Comment by joofsh** [comment]
1. Can you provide more info on this? We have an "In Validation" column and a QA team. Are you saying it needs to be vetted by someone from product/design as well?

2. The lowest level of effort to solve this is to extend our Jenkins slack integration. Right now we post that we are doing a deploy to prod, but it doesn't say _what_ we are deploying. We could have it do a git log diff between the current code on prod and what we're deploying, to at least show a clean list of what changes are going in. We could also have this posted to the general #appeals channel for everyone to see.

**Comment by aroltsch** [comment]
Regarding 1: One solution to this problem is to have two main branches: master and develop. Master is to be the branch where the source code always reflects a production-ready state. Develop is to be the branch where the source code always reflects the latest delivered development changes. When the source code in the develop branch reaches a stable point and is ready to be released, all of the changes should be merged back into master somehow and then tagged with a release number.
Here is a good article describing the workflow: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by shanear** [comment]
@joofsh 1. is regarding a problem where we have stories that are still in "In Validation" that are being deployed to production with out being vetted by anyone. That's because the code was merged to master and not QA'ed

**Comment by shanear** [comment]
@aroltsch what you are describing is typically called "git flow", and it adds a lot of complexity with branching and merging which can be very cumbersome. Vets.gov tried this in the beginning and found that to be true. I'd prefer to stick with "Trunk Based Development" if we can help it.

@KHarshawat I think you are on to something. I think @kierachell or @astewarttistatech could check all the issues merged since last release and verify that the release is ready to go and then add "deployed" tag to them or something, and post those issues to slack on a deploy.

**Comment by shanear** [comment]
Also we will be dicussing this Wed, Feb 1 after standup

**Comment by kierachell** [comment]
[generated issues for QA](https://github.com/department-of-veterans-affairs/appeals-qa/issues/32)
