### ISSUE TITLE
Add issue edge cases | Add Issue Landing | if ineligible lane (just Appeal -> HLR and Appeal -> Appeal)

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#7344]
## Story
When a user adds issues, they may encounter edge cases where the issue is ineligible. We will not indicate that an issue isn't eligible on any of the add issue selection pages but will indicate it on the Add issue landing page and Confirmation Page so they have the information they need to inform the applicant in the letter they send following intake data entry. If an issue is ineligible in will get logged in Caseflow but not VBMS. [Mural showing edge cases](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430).

This ticket is focused on the scenario where the issue being requested isn't eligible for that lane and how we display it's ineligibility on the Add Issues Landing page. There are 3 scenarios where this might occur that are detailed in the copy section -- note that they will only occur for HLR and Board Appeal lanes and only for rated issues.

requires https://github.com/department-of-veterans-affairs/appeals-design-research/issues/998

## Acceptance criteria
- If a decision issue that was decided as part of an appeal is contested as part of a higher level review, it should be considered ineligible. This means it should show as ineligible with the copy below, and show up as ineligible on the confirmation page described in #7308  
- If a decision issue that was decided as part of an appeal is contested as part of an appeal, it should be considered ineligible. This means it should show as ineligible with the copy below, and show up as ineligible on the confirmation page

## Notes
- Identical wording will be used on the confirmation page #7308

## Technical note
- Could write these as independent testcases (not mixed with other ineligibility test coverage)

## Copy
Scenario | Display copy 
--- | ---
If the request is a Board Appeal and the same issue was last processed as a Board Appeal | [Issue selected] is ineligible because it was last processed as a Board Appeal and this can't be done twice in a row.
If the request is a HLR and same issue was last processed as a Board Appeal | [Issue selected] is ineligible because it was last processed as a Board Appeal which can't be followed by a Higher-Level Review.

## Mocks
(Sample show what the first scenario would look like)
<img width="759" alt="screen shot 2018-10-06 at 10 43 34 am" src="https://user-images.githubusercontent.com/11219417/46572492-ba031480-c954-11e8-98aa-90cd5e927c86.png">

## Background issues
- #5244 

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by steve-gov** [comment]
Validated on outcoded appeals from #8263:

<img width="820" alt="screen shot 2019-01-30 at 5 29 19 pm" src="https://user-images.githubusercontent.com/25468689/52024195-bd4a7f00-24b4-11e9-99c1-994252009ea4.png">

<img width="812" alt="screen shot 2019-01-30 at 5 28 17 pm" src="https://user-images.githubusercontent.com/25468689/52024196-bd4a7f00-24b4-11e9-810a-bcba7f561718.png">

**Comment by steve-gov** [comment]
Note that issues earlier in the chain can still be added, but that is covered in a separate issue.
