### ISSUE TITLE
Create database rows for Mail, FOIA, and AOD organizations

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7355]
Now that we know [how VACOLS identifies members of these teams](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/42), all that is left to do in order to give these teams access to the full power of Caseflow is to add the database rows for the Mail, FOIA, and AOD organizations by running the following commands in a production Rails console:
```
mail_org = Organization.create!(name: "Mail", url: "mail")
StaffFieldForOrganization.create!(organization: mail_org, name: "sdept", values: %w[MPS])

foia_org = Organization.create!(name: "FOIA", url: "foia")
StaffFieldForOrganization.create!(organization: foia_org, name: "sdept", values: %w[AIRS])

aod_org = Organization.create!(name: "AOD", url: "aod")
StaffFieldForOrganization.create!(organization: aod_org, name: "sdept", values: %w[AOD])
```

We should hold off on doing that until we are ready to pilot because adding those rows will allow anyone who is identified in VACOLS as being a member of any of those teams will have access those organizations' queues.

**Comment by amprokop** [comment]
Nice! Is it better to add those organizations in a PR so it's more traceable and auditable? Seems like that's the path we were going for before, correct me if I'm wrong or if it seems like a lot of work!

**Comment by amprokop** [comment]
Yeah. Not concerned with this particular instance, just concerned with treating this sort of thing as a normal long-term path.

- How many times do you anticipate having to do this?
- What would happen if we made a mistake? How would we know, and how would we fix it?
- Do we also have to manually run these commands in lower environments?

**Comment by lowellrex** [comment]
Closing this issue since we have settled on a new strategy for associating users and organizations: #7506.
