### ISSUE TITLE
Insight to implementation discussion (10/11/2018)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7359]
## Problem to solve
What is a _lean_ process we can all align on as we go from our user needs/feedback to product decisions and modifications?

## Discussion
- We have a solid process of research --> design exploration --> usability testing --> scope definition --> implementation --> launch for those topics we know little about
	- A lot of our recent research and design has been focused on these large, thorny issues, and has gone through this cycle
- Due to our team size, need for speed, multiple concurrent projects, many team members are working with our users, not only designers, and are hearing user needs/insights from one or more people. We don't yet have a process to turn those insights into action.
- A light, cylical model to describe this:
	1. user feedback
	2. problem identification
	3. solution implementation
	4. production release
	1. user feedback
	2. ...
- Can also be described as:
	1. what is the problem
	2. how do we know?
	3. what do we do
	4. do it
	1. what is the problem
	2. ...
- Our discussion focused around the "what do we do" element of this model.
- Two concerns about our current state were raised:
	- A lot of our research and design is focused on large, thorny issues
	- Mark and Lowell are going blind in their work on generic queues

## Proposal for a lean process
Please provide feedback for this proposal in the comments of this github issue, and provide insights into the open questions we still have around it.

After a team member has identified a problem to solve for our users, whether through support tickets, user feedback, or anything else, please follow these steps:

1. Describe the problem (in a github issue)
2. Suggest solution/response options (in the github issue)
3. Share the github issue and provide a deadline for feedback to those involved
	- Note: though you may tag a subset of the team, you can share this publically so the team is aware of it and can chime in if they see fit
4. Make a decision with those key team members (sync or async, whatever the group decides)
5. Document the decision (in the github issue, and elsewhere if need be)

#### Open questions about this process - seeking feedback
- Who is part of each project? Who should be tagged in this decision?
- What is an appropriate deadline?
- What if someone is on PTO? Can we delegate decision-making so there is no bottleneck?
- What happens if team members disagree? How do we move forward?

## Next Steps
- @laurjpeterson @sneha-pai @allyceh meeting 10/11 to define which designer is working on which queue project
- **All foxtrot team members comment on this ticket by standup (11:45am) Monday, October 15th**
   **1. feedback on the proposed process - if there are any additions/deletions/yays or nays
   2. feedback/ideas for the questions posed**

**Comment by mdbenjam** [comment]
I think the time boxing has to depend on the substantiveness of the task. I think for small things it's reasonable to expect an answer within 24 hour. For more complex initiatives, 2-3 days. Obviously this is all subjective, but I'm not sure how to make it less so.

If someone is on PTO then the other designer, or engineer involved gives the definitive answer unless they think the person on PTO has required information to make a decision.

If we disagree, I think we need to figure out at what point do we disagree. Do we disagree about the problem or the solution. If it's the former, what idk what to do. If it's the latter, then it's up to the disagreeing party to come up with an alternative solution. I think LP is the ultimate decision maker, and breaks ties.

**Comment by lowellrex** [comment]
Agree with all of @mdbenjam's points above.

A default timebox of 24 hours is reasonable and the person who has been asked to provide input can work with the requestor if they think it will take longer than 24 hours. All disagreements should be resolved by the product owner (LP) at any stage of this process.
