### ISSUE TITLE
Decision Review | Ability to view Decision Criteria information when Multiple Decisions available

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#736]
As a Caseworker, I would like ability to view Decision Criteria information (Decision Type and VACOLS Issues) about the current case when there are multiple decisions available so that I have a clearer picture of the current case and am better prepared to select the correct decision.

#  Acceptance Criteria
1. Verify that there is a VACOLS Decision Criteria section only when there are multiple decisions within the Decision Date range.
1. Verify that in the VACOLS Decision Criteria section, there is a field _"Decision Type"_ that displays as read only the VACOLS Decision Type value for the current case.
1. Verify that in VACOLS Decision Criteria Section, there is a table containing all of the VACOLS' issues related to the current case.
1. Verify that in VACOLS Decision Criteria Section, the table contains the following columns:

     -  **_Program_** - contains the VACOLS Program value for the current case.
     -  **_VACOLS Issue(s)_** - contains the VACOLS Issue value for the current case.
     -  **_Disposition_** - contains the VACOLS Disposition value for the current case.

# Mockup
**_View - Decision Review page with Decision Criteria Section_**
<img width="818" alt="screen shot 2017-01-30 at 12 49 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/22434571/9a1cf134-e6ea-11e6-8897-e12a56820b0b.png">

# Related Stories
EPIC: Decision Review: Ability to review a veteran's VBMS decision [#3](https://github.com/department-of-veterans-affairs/appeals-design/issues/3)
Decision Review | Display an alert when there multiple decisions available #735
Decision Review | Ability to display multiple Decision Documents #616

**Comment by mdbenjam** [comment]
@lakohl Should this really be a table view? I'm trying to implement it now, but am running into a problem where we only have the VACOLS record associated with the Create EP Task. We don't necessarily have the records corresponding to the other decision documents. Don't we just want to present the information from the VACOLS record we have, and then let the caseworker look through the decisions to decide which one is right? If we just show all the information from all of the VACOLS records, then what information do they pick to selection the correct decision document?

**Comment by lakohl** [comment]
@mdbenjam as you said, the problem that we are trying to solve is:  we are asking the caseworker to pick the correct .pdf decision from VBMS, but in order to do that we need to surface enough information in VACOLS for them to make that call.  A table seemed the best route because there may be several issues associated with a single claim/decision, some granted some not. We are only showing information from one VACLS record but are listing the issues out separately. I think we are on the same page!

**Comment by kierachell** [comment]
Need claims with multiple documents to test this in `uat`

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate: 
1. Go into Dispatch and try to establish a claim that has multiple docs
2. Validate the message shown

Screenshots:
<img width="1355" alt="screen shot 2017-02-08 at 4 24 40 pm" src="https://cloud.githubusercontent.com/assets/23038505/22758173/8e13f0f8-ee1b-11e6-92ba-f956064464fb.png">
