### ISSUE TITLE
Add Assigned to for AMA/RAMP appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7360]
When Lit Support is trying to understand the story of an appeal so they can answer status/congressional inquiries, they want to see who at the Board currently has responsibility for the appeal, so they can complete their investigation.

## AC
- Populate the CSS ID of the user who currently has the appeal in the `Assigned to` column of the Case list for AMA appeals.

<img width="1072" alt="screen shot 2018-10-11 at 1 40 47 pm" src="https://user-images.githubusercontent.com/27704093/46823235-9e847900-cd5b-11e8-86bc-6729462306e8.png">

**Comment by lowellrex** [comment]
If there is no attorney assigned to an appeal (or if the attorney has already drafted a decision or requested OMO), then display the CSS ID or organization name of the entity with most immediate responsibility for the appeal (most-nested child task, tie-breaking on most recently created if need be).

**Comment by lowellrex** [comment]
After chatting with @laurjpeterson the final criteria should actually just be whoever has the most recent open task for an appeal.

@laurjpeterson if there are no open tasks for an appeal (case hasn't been distributed or the decision has been dispatched) what should this "assigned to" field read?

**Comment by lowellrex** [comment]
I like `Case storage` for cases that haven't been distributed yet because it is language folks already know, and I think `Post decision` is slightly preferable to `N/A` since the former is a little more precise about what state the case is in.

**Comment by laurjpeterson** [comment]
Sounds good - let’s go with that! @sneha-pai, @cmgiven, or Amanda might have opinions to change it down the line, but I think we can go with these terms for now to get this out there
