### ISSUE TITLE
Queue | Judges | Cases returning from OMO should appear in Judges' Assign Tab

### ISSUE THREAD

**Issue by evankroske** [department-of-veterans-affairs/caseflow#7362]
When cases return from OMO (an OMO individual charges the case back to the judge's location), Judges need to be able to assign them to an attorney, so a decision can be drafted.

Caseflow can't distinguish cases that have returned from the OMO team from cases that need to be dispatched to the OMO team because both have Decass records with an OMO deprod value (VHA, IME, etc.) This causes cases from the OMO team to be shown on the review queue, where they can't be assigned to an attorney.

## AC
- Cases that have returned from OMO appear in the Assign Cases queue for judges

## See Also
- [The support request when this issue was discovered.](https://github.com/department-of-veterans-affairs/appeals-support/issues/3237)

**Comment by evankroske** [comment]
I asked a VLJ, BVARKESSEL, how he knows whether an OMO case needs to be assigned. He said that he receives an email from the attorney or OMO team member that he uses to decide what to do with the case. He also said that he can look at a case's assign date (deassign) to determine what to do with it: if the assign date is really long ago, then the case has returned from the OMO team.

**Comment by evankroske** [comment]
Jed says that preliminary creates a new Decass record if the existing record is an OMO case, and he explained the code that implements it. When [this code](https://github.com/department-of-veterans-affairs/VACOLS/blob/1d31c01e5410d9b1c5a52fd5d454914ab6f56da4/src/decass.pbl-dump/w_update_prelim_2017.srw#L160) checks for an existing Decass record, it uses [this query](https://github.com/department-of-veterans-affairs/VACOLS/blob/1d31c01e5410d9b1c5a52fd5d454914ab6f56da4/src/issues.pbl-dump/d_das_update_prelim_2017.srd#L23) to search for it, which excludes OMO Decass records. We need to update our assignment code to match.

**Comment by evankroske** [comment]
Now I'm trying to figure out how DAS and VACOLS handle the two Decass records. Does the VLJ Master list show both of the records? If not, how does it decide which Decass record to use?

**Comment by evankroske** [comment]
VLJ Master list code:

- [Data window](https://github.com/department-of-veterans-affairs/VACOLS/blob/1d31c01e5410d9b1c5a52fd5d454914ab6f56da4/src/decass.pbl-dump/d_cases_charged_to_vlj.srd)
- [Print preview screen](https://github.com/department-of-veterans-affairs/VACOLS/blob/1d31c01e5410d9b1c5a52fd5d454914ab6f56da4/src/decass.pbl-dump/w_print_preview_vlj_master.srw)

**Comment by evankroske** [comment]
## Hypothesis
The VLJ master list only uses the most recent Decass record of each case.

**Comment by evankroske** [comment]
After reading the code, it seems like the table will show two rows for cases with two Decass records.

**Comment by evankroske** [comment]
I'm convinced that the table shows both Decass records, but I don't think that matters. When a judge assigns a case, both rows would disappear because the case would no longer be assigned to the judge according to Brieff.bfcurloc. Caseflow can probably just use the latest Decass record.

**Comment by aroltsch** [comment]
https://github.com/department-of-veterans-affairs/dsva-vacols/issues/48#issuecomment-460709180

**Comment by laurjpeterson** [comment]
Discussed this, and decided that the workaround of judges using DAS to assign OMO tasks works for now. OMOs are decreasing, and we should spend time on deprecating DAS/legacy tasks over making this work. Closing.
