### ISSUE TITLE
Private Attorney Special Issue

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7366]
I need to do some more research on this, but when we pull appeals from VACOLS, we set private_attorney_or_agent equal to true if case_record.bfso == "T" and false otherwise. I believe that introduced a bug such that if a user selects private attorney to true on the special issues page, but case_record.bfso != "T", the special issue gets reset back to false the next time we try to pull the appeal from VACOLS.

Relevant PR: https://github.com/department-of-veterans-affairs/caseflow/pull/2365

**Comment by laurjpeterson** [comment]
Emailed AMO today with language that they can send to Caseflow Dispatch users about the change. I'll post here again when we can merge.
