### ISSUE TITLE
Legacy Opt-in | Reopen VACOLS issues if AMA issue is removed

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#7369]
in #7337 we are going to start closing VACOLS issues and/or appeals when legacy issues are linked - if those AMA issues are removed, we will need to reopen the VACOLS issues / appeals.

requires https://github.com/department-of-veterans-affairs/caseflow/issues/7337

## Acceptance Criteria
- If an issue associated with an "opted-in" VACOLS issue (via #7337) is removed from any decision review via the Edit issues flow, then the "opted-in" VACOLS issue should be reopened with the previous disposition code

## Notes
We should confirm with Chris which code we should reopen with

## Technical Notes
- This also means that if the parent appeal was closed, because the opted-in issue was the last issue on that appeal, it must be reopened as well.
- There are methods that do this already (look at Ramp election code RampClosedAppeal, RampRollback)
- (An edge case that we don't need to address in this issue: the parent appeal was closed for some other reason (not "O"))

**Comment by shanear** [comment]
This is working like a champ :100:

tested partial/full on remands and originals.

Everything works 👍
