### ISSUE TITLE
AMA Intake | Skip first "rating issue" modal if there are no promulgated ratings

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7375]
If the veteran has no ratings, Caseflow currently shows a system error when submitting the review page. We confirmed with AMO that even if the user has no ratings, we should still allow decision reviews for potential non-rating issues, so allow them to go through the flow.

Additionally, no business lines except compensation and pension even use ratings.

requires #7383

## Acceptance Criteria
When intaking a HLR or SC and the veteran has no ratings or prior nonrating decisions (see: #7383) of the selected business line:
When the 'Add Issues' button is clicked, do not show the "Does issue 1 match any of these issues from past descriptions?" modal. Instead, skip to the modal titled "Does issue 1 match any of these issue categories?".

**Comment by kencheeto** [comment]
@mdbenjam this could be a fairly straightforward issue to pick up that is still meaningful.

**Comment by mdbenjam** [comment]
@kencheeto just want to make sure I understand y'alls terminology. Since this requires #7383, that means I should wait until that ticket is done before starting this one?

**Comment by shanear** [comment]
Looks like it's working!
![screen shot 2018-11-26 at 12 29 51 pm](https://user-images.githubusercontent.com/1596259/49031086-04e02200-f177-11e8-8526-65a3e97f2549.png)
