### ISSUE TITLE
Certification Cancellation Modal: Whitespace validation and character limit

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#738]
# Description:
As a Regional Office Caseworker, when filling out the Cancel Certification form using _Other_ as the reason;
I fill out the _Tell us more about your situation_ field with whitespaces `  ` and/or unlimited amount of text.
**I expect** an error message to be displayed in both cases; character limit to be 2000.
**Actual result:** the cancellation is generated normally.

**Environment:**
- [ ] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproductive Steps
**Scenario 1:**
1. Login as "Certify Appeal" user

2. Proceed to a new Certification

3. Press "Cancel" button at the bottom of the page

4. Select "Other" as the reason why the case cannot be certified

5. Fill the _Tell us more about your situation_ text field with whitespaces

6. Fill in a valid email address in the next text field

7. Click "Cancel Certification" button

**Scenario 2:**
1. Login as "Certify Appeal" user

2. Proceed to a new Certification

3. Press "Cancel" button at the bottom of the page

4. Select "Other" as the reason why the case cannot be certified

5. Fill the _Tell us more about your situation_ text field with an enormous amount of text

6. Fill in a valid email address in the next text field

7. Click "Cancel Certification" button
# Screen Shots
**_Scenario 1 - Cancel Certification Modal with whitespace_**
<img width="954" alt="screen shot 2017-01-24 at 11 08 36" src="https://cloud.githubusercontent.com/assets/18075411/22265401/ed1775e4-e249-11e6-9b3f-53c18fad588a.png">

**_Scenario 2 - Cancel Certification Modal with text_**
<img width="936" alt="screen shot 2017-01-24 at 15 30 22" src="https://cloud.githubusercontent.com/assets/18075411/22265448/14a32ee6-e24a-11e6-848e-a032e2eb23e1.png">

# Relate Stories/Issues
**_Support_**

**_Engineering_**
Certification Cancellation: Ability to submit a Cancellation - #631

**Comment by nikitarockz** [comment]
prioritize - under 268

**Comment by nemodjuric** [comment]
@kierachell @nikitarockz  I assume this includes character counter message and the limit is 2000 as in https://github.com/department-of-veterans-affairs/caseflow-feedback/issues/103

**Comment by kierachell** [comment]
**PASSED**
spacing between the fields could be better, but will wait for directions from designers.
![cancelcert](https://cloud.githubusercontent.com/assets/18075411/23717301/4733344a-0401-11e7-806c-f43e850ac3bd.gif)
