### ISSUE TITLE
AMA Intake/Edit | Show prior decided non-rating issues in Add Issue flow

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7383]
In order to properly distinguish duplicates and issue chains for non-rating issues, we need CA's to be able to match incoming non-rating issues to prior decided non-rating issues. In order to do this we need to show them in the Add issues flow.

## Technical Notes
This is the mural for the nonrating issue data structure:
https://app.mural.co/t/workqueue2001/m/workqueue2001/1540421981879/ba39075927b4039387697e094436e6a236fe7fa4

## Acceptance Criteria
- When issues are being added to an intake, all past decided nonrating issues should show up on the first modal of the Add Issues page.
- When an intake is completed with one of these prior issues selected, the new request issue should be linked in the database to the past decided non-rating request issue. The description for the new request issue should be "{disposition}: {prior issue category} - {prior issue description}"
- The following existing validation patterns should apply to prior non-rating issues:
  - Multiple active issues reviewing the same non-rating decision should be ineligible (https://github.com/department-of-veterans-affairs/caseflow/issues/7291)
  - If HLR, then issues reviewing prior non-rating HLR decisions should be ineligible (https://github.com/department-of-veterans-affairs/caseflow/issues/7293)

## Copy
Past decisions from {decision_date}
- {disposition}: {category} - {description}

## Mocks
The issues should show up in another section like the "Past decisions from X" sections on this page
![screen shot 2018-10-23 at 7 19 42 pm](https://user-images.githubusercontent.com/1596259/47396463-e494f180-d6f8-11e8-97ce-fbc9b2554db2.png)

**Comment by shanear** [comment]
@carolaponce this was created based on our conversation yesterday. Me and ken think it's ready for dev, but would be good for you to take another look and get your thoughts

**Comment by carolaponce** [comment]
WIP - This interface can be used for Comp & non-comp.  The wording and type of issues would change accordingly.  Using the existing UI patter to identify active decision issues.

**Comment by carolaponce** [comment]
![issues - active decisions copy](https://user-images.githubusercontent.com/11700545/47466178-2045bf00-d7be-11e8-95cf-837e9de37801.png)

**Comment by carolaponce** [comment]
![3 issues](https://user-images.githubusercontent.com/11700545/47466194-2fc50800-d7be-11e8-9a6c-8bfe99f11eab.png)

**Comment by carolaponce** [comment]
![issues - active decisions](https://user-images.githubusercontent.com/11700545/47466400-09ec3300-d7bf-11e8-9775-3614685fb026.png)

**Comment by carolaponce** [comment]
![issues - active decisions copy](https://user-images.githubusercontent.com/11700545/47466402-0e185080-d7bf-11e8-94ef-8506b677936b.png)

**Comment by carolaponce** [comment]
![3 issues](https://user-images.githubusercontent.com/11700545/47466409-13759b00-d7bf-11e8-974c-f369943a4644.png)

**Comment by carolaponce** [comment]
So the rule is that if they identify the issue as an "Active decision" we don't allow them to add it, if they think it is not a duplicate then they have the ability to add it again and not select one of the active decisions.  I am not sure if the terminology is correct - any feedback @shanear?

**Comment by shanear** [comment]
This issue is referring specifically to nonrating issues that have a decision recorded already. Active nonrating issues are captured in this issue: https://github.com/department-of-veterans-affairs/caseflow/issues/7515

**Comment by carolaponce** [comment]
![3 issues](https://user-images.githubusercontent.com/11700545/47506569-5a56a580-d83e-11e8-8e50-2bfff08187ff.png)

**Comment by shanear** [comment]
closing as a dup of #7978 🙃
