### ISSUE TITLE
AMA Intake | Add better error message on intake when a user has a locked rating

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7385]
It might be a little while before https://github.com/department-of-veterans-affairs/caseflow/issues/6221 gets fixed. In the mean time we may want to show a user friendly message on what to do.

**Comment by kencheeto** [comment]
an example error in sentry: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2918/events/

**Comment by leikkisa** [comment]
Closing this, because the user will no longer see an error when they have a locked rating.

**Comment by leikkisa** [comment]
I am re-opening this, because we may want to let the user know that there was a locked rating (even if there were regular promulgated ratings), because maybe those do have issues that can be intaken.

related https://github.com/department-of-veterans-affairs/caseflow/issues/9817

**Comment by pkarman** [comment]
e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3976/events/270463/

**Comment by pkarman** [comment]
@leikkisa This may be moot now but I am too far removed to know anymore.

**Comment by leikkisa** [comment]
@pkarman I'd be down for closing this (I see that I re-opened it at some point lol).  I don't think we have a good way to know if there are locked ratings now, unless the only rating is locked, so that would make this hard.
