### ISSUE TITLE
Form 8 | Question 13 Other Specified | Isn't clearing values selected after edit

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#739]
# Description:
Edits made to the "Other Specified" fields
When the user puts a check in the "Other" checkbox and supplies an "Other Specified" value for Question 13 on the Electronic Form 8 page, then goes to the Form 8 PDF Preview page, the 
they are rendered on the Form 8 PDF.  However, if a Caseworker clicks "Go back and make edits" button on the  *Review Form 8* page, unchecks any of the boxes for Question 13, and goes to back to the Review Form 8 page. 

**Expected result:** Question 13 checked boxes should match the new edit
**Actual result:** Question 13 checked boxes are not unchecked based on the edits; they remain checked from the original submission.
@aroltsch mentions that the database does not update for these edits as well.

**Environment:**
- [ ] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Security
- [x] Functional
  
**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [x]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproduction Steps
**Scenario 1:**
1. Proceed to Form 8 for a new Certification
2. Fill out the Required fields for Form 8 with any values
3. For Question 13 check any number of boxes
4. Proceed to _Review Form 8_
5. Observe the appropriate boxes checked for Question 13
6. Click "Go back and make edits" button
7. For Question 13: uncheck any number of boxes that were previously checked
8. Proceed to _Review Form 8_ again
9. Observe that the PDF does not reflect the new state for checkboxes for Question 13.

**note that the textfield for Checkbox `Other` is handled by another issue**

# Screen Shots
**_Complete Form 8 at Question 13 first time_**
<img width="1001" alt="screen shot 2017-01-24 at 15 48 39" src="https://cloud.githubusercontent.com/assets/18075411/22266556/70736796-e24e-11e6-95b4-795d00f690eb.png">

**_Review Form 8 at Question 13 first time_**
<img width="1004" alt="screen shot 2017-01-24 at 15 48 55" src="https://cloud.githubusercontent.com/assets/18075411/22266578/83866ff4-e24e-11e6-8f7d-cb2afe3a099e.png">

**_Database Entry_**
<img width="833" alt="screen shot 2017-01-24 at 16 20 25" src="https://cloud.githubusercontent.com/assets/18075411/22267276/3a068ea6-e251-11e6-9de9-4e41ac5bc25f.png">

**_Complete Form 8 at Question 13 editing_**
<img width="964" alt="screen shot 2017-01-24 at 15 49 09" src="https://cloud.githubusercontent.com/assets/18075411/22266592/8fbbb3a6-e24e-11e6-8ca7-45265c116943.png">

**_Review Form 8 at Question 13 after edits_**
<img width="994" alt="screen shot 2017-01-24 at 15 49 20" src="https://cloud.githubusercontent.com/assets/18075411/22266600/9c14beae-e24e-11e6-997f-fcb43fba17f7.png">

**_Database Entry unchanged after edits_**
<img width="837" alt="screen shot 2017-01-24 at 16 20 46" src="https://cloud.githubusercontent.com/assets/18075411/22267297/4676de66-e251-11e6-8d1e-412524a3c3ef.png">

# Relate Stories
Form 8 Preview: Question 13 Other Specified: Isn't displaying value entered - #611

**Comment by nikitarockz** [comment]
prioritized - low

**Comment by kierachell** [comment]
Now that the text appears, it decides to stay after edits:
<img width="1018" alt="screen shot 2017-01-27 at 09 17 24" src="https://cloud.githubusercontent.com/assets/18075411/22373872/b6c2550c-e471-11e6-9bb7-747d03154c29.png">
<img width="952" alt="screen shot 2017-01-27 at 09 17 39" src="https://cloud.githubusercontent.com/assets/18075411/22373875/b6cbe93c-e471-11e6-9a0c-4408d16419df.png">
<img width="994" alt="screen shot 2017-01-27 at 09 17 49" src="https://cloud.githubusercontent.com/assets/18075411/22373874/b6c67394-e471-11e6-99a9-bcf4ea1ac4ca.png">
<img width="977" alt="screen shot 2017-01-27 at 09 18 00" src="https://cloud.githubusercontent.com/assets/18075411/22373873/b6c5fc98-e471-11e6-8461-f113e6b65bdc.png">

**Comment by kierachell** [comment]
**PASSED**
Checkboxes clear and show up appropriately.
![form8q13checks](https://cloud.githubusercontent.com/assets/18075411/22886376/8b392da4-f1cb-11e6-9c2b-698917b704ad.gif)
