### ISSUE TITLE
Move tabs logic inside TaskTable component

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7391]
Currently when we draw tabs, we create separate `TaskTable` components for each tab. This ticket exists to move the tabs logic inside of the `TaskTable` (first discussed as [a comment on a PR](https://github.com/department-of-veterans-affairs/caseflow/pull/7389#discussion_r225183195)).

Two ideas for how this could work are:
1. Calling code passes `TaskTable` an array of objects that have titles, optional descriptions, and functions that filter which tasks to display in the table (and maybe eventually columns as well if we want to display different columns in each view?).
2. Display a pre-defined set of tabs if a `showTabs` flag is set on the component by the calling code.

## Acceptance criteria
* `TaskTable` handles the rendering of tabs within the component itself.
* `TaskTable` continues to work and appear as it does now for use cases where it does not handle tab logic internally.

**Comment by laurjpeterson** [comment]
@lowellrex - i see you merged a PR here. can this be closed?

**Comment by lowellrex** [comment]
Closing this out since this work will be completed as part of #10049.
