### ISSUE TITLE
Release 2 | On hold functionality

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7396]
As a hearing coordinator, I want to be able to place a scheduling task on hold to track and account for scheduling tasks that can not immediately be scheduled. This prevents the from "losing them" and looking up redundant tasks.

**Comment by laurjpeterson** [comment]
@Chingujo I think this functionality exists, right? If so, let's close!

**Comment by alisan16** [comment]
Closing this out as there hasn't been any movement in 1.5 years
