### ISSUE TITLE
AMA Intake/Edit | Error handling for save

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#7397]
When saving changes on the Add/Remove Issues screen of the edit flow, there are a couple reasons why the changes may be invalid.

## Acceptance criteria
- When a user saves an AMA review edit or intake, if there is an error with that submission, caseflow should display an error message in an alert.

## Technical notes
- The backend for these validations already exists here: (https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issues_update.rb#L94)
- The component to show the correct error message also exists(https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intakeEdit/components/RequestIssuesUpdateErrorAlert.jsx#L4)

## Copy
Use the same copy we were using before:
found here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intakeEdit/components/RequestIssuesUpdateErrorAlert.jsx#L4

## Mocks
We should show an error alert like this at the top of the page, below the "Add/Remove Issues" title.
<img width="823" alt="screen shot 2018-10-16 at 2 43 11 pm" src="https://user-images.githubusercontent.com/1596259/47040224-bf7e0d00-d153-11e8-9741-51fa7b444188.png">

**Comment by shanear** [comment]
![screen shot 2018-10-26 at 2 50 20 pm](https://user-images.githubusercontent.com/1596259/47586773-1394a880-d92f-11e8-8ef9-5e9882de25c4.png)
![screen shot 2018-10-26 at 2 54 36 pm](https://user-images.githubusercontent.com/1596259/47586775-142d3f00-d92f-11e8-8d0e-7f9188993d91.png)
Got there 👍👍
