### ISSUE TITLE
Start/Doc Comparison Page: Highlight the ability to refresh the page

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#74]
Many participants hard a hard time finding the "refresh" link after they had corrected missing file dates in VBMS. 

Suggestion: Consider adding a "Refresh" button down next to the "This case cannot be certified" button and/or auto-refreshing the page.

**Comment by KHarshawat** [comment]
![image](https://cloud.githubusercontent.com/assets/6335546/10799033/17201866-7d81-11e5-8960-638bae7cccba.png)
