### ISSUE TITLE
Create generic tasks / mail rollout

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7404]
# Background
Veterans and appellants send in all different types of mail at any point in the appeals process. Mail is typically sent to the central mail processing center in Janesville, Wisconsin. Mail comes into the VBA or BVA P.O. Box. Employees in Janesville upload the mail in the Mail Portal. If the mail is for BVA, BVA employees process it in the following way:
- Mail supervisor assigns mail to individual mail staff in the Mail Portal
- Mail employee opens the mail in the mail portal 
- Mail employee searches for the Veteran to confirm there is an appeal record. 
- Mail employee adds a "mail tab" in VACOLS and assigns it based on routing rules. This is a mail task for someone at the Board to do
- Mail employee uploads the mail to VBMS utilizing centralized mail portal

We need to build a way to create these tasks in Caseflow so (1) the mail team can create and assign tasks and (2) so other Board teams can create and assign tasks from these mail tasks.

# Strategy
- Build a manual mail task creation piece up front first before diving into VBMS document types
  - As Alex pointed out, it helps us de-risk the business end by checking the correctness of an automated mail task creation system later on. For example, if users were checking the mail portal and creating MailTasks, theoretically we could build this automated piece which would create FakeMailTasks, then check to see how the results are different. Potentially if we had time we could also use VACOLS mail to accomplish the same end.

# Suggested flow
- Mail supervisor assigns mail to individual mail staff in the Mail Portal
- Mail employee opens the mail in the mail portal 
- Mail employee searches the appellant's ID in Caseflow 
- Mail employee clicks into the appellant's correct `Case details` page.
- Mail employee creates a mail task from the Actions dropdown
- Mail employee fills in a variety of data about the mail task and assigns it to an organization

**Open Questions:**
- Can we auto-fill task assignees like VACOLS does today? Is it worth it?
   - Note: we are planning to do this, yes.

# Rollout ideas
- Start with initial list of mail tasks that can be worked by VLJ Support Staff
       - Implementing active tasks is required before this can begin
       - Note: we think that we can allow mail team to create tasks for AOD + Privacy teams right off the bat, too
- Progressively add additional teams mail tasks can be assigned to
- Progressively add additional mail task types to the list that can be chosen

### 1. AMA first
See routing logic, here https://github.com/department-of-veterans-affairs/caseflow/issues/7906

1. Allow mail team to create mail tasks and assign to VLJ Support Staff
    - [x] Mail team can view the active task is with attorney or judge in Case details
    - [x] Mail team can create mail tasks for cases that are located at an attorney or judge. These mail tasks will be round robin distributed among the team members and show up in the team and individual queue.
         - `Change of Address` (low frequency)
                  - Should mail management handle these?
                  - Note: Veteran addresses will need to be changed in SHARE for AMA cases (instead of VACOLS like Legacy cases)
         - `Evidence or Argument`(high frequency)
                  - This is the most common type of BVA mail
         - `Power of Attorney Related`
         - `Extension Request`
                  - Note: judge needs to sign off on these
         - `Withdrawal of appeal`
     - Mail can assign tasks the following teams: `VLJ Support team`
1. Allow mail team to create AOD mail tasks and assign to AOD office
    - [x] Ensure AOD users access to their team and individual queues
    - [x] Mail team can create `Motion to Advance on Docket` task and route to the `AOD team`
         - if AOD mail task is selected, can we auto-populate the assigned team list to AOD?
    - Mail can now assign tasks the following teams: `VLJ Support team` + `AOD team`
1. Allow mail team to create mail tasks for Privacy/FOIA and assign to Privacy office
    - [x] Create Privacy team queue
    - [x] Mail team can create tasks to route to Privacy team
          - `FOIA Request`
          - `Privacy Act Request`
          - `Privacy complaints`
          - if Privacy/FOIA mail tasks are chosen, can we auto-populate the assigned team list to Privacyt?
    - Mail can now assign tasks the following teams: `VLJ Support team` + `AOD team` + `Privacy team`
1. Allow mail team to create mail tasks for "easy" Lit Support use cases and assign to Lit Support
    - [x] Create a Lit Support team queue
    - [x] Build Congressional Inquiry data capture flow (tracking progress of this flow in this [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1541515515637/acd1e6f66aa5535c25b71b0ac7c72b5e7ddee793).
     - [x] Mail team can create `Congressional Interest` mail task
     - Mail can now assign tasks the following teams: `VLJ Support team` + `AOD team` + `Privacy team` + `Lit Support`
     - `Attorney Inquiry`
                  - Note: need to confirm what this means
1. Allow mail tam to create mail tasks for AMA appeals that have had decisions, and assign to Lit Support
    - [x] Lit Support can create tasks on the root after completing a mail task
    - Mail team can create lit support tasks
          - `CUE related`
          - `Motion for Reconsideration`
          - `Motion to Vacate`
          - `Other Motion` 
     - Mail can now assign tasks the following teams: `VLJ Support team` + `AOD team` + `Privacy team` + `Lit Support`

### 2. Then Legacy cases
**Assumption:** We do not need to update any VACOLS locations with this mail task creation. Mail team simply creates mail tabs in VACOLS. We are replacing that task creation with a Caseflow task creation.
- **Note:** excluding AMA because of backwards compatibility of setting AOD diary (we already know how to do this through hearing prep, but I'm ok leaving it out for now if it makes sense for us)
- Note: excluding Lit Support - can continue with auto-assignment and tracking them in VACOLS

1. Allow IDT to flag whether there are any open Caseflow tasks (instead of the pop-up that shows open VACOLS mail tasks). 
1. Allow mail team to create mail tasks and assign to VLJ support management branch
    - Mail team can create any mail task for cases that are located at an attorney or judge, and route them to the `VLJ Support team` (Co-located). 
    - The only team mail can select as the assignee is `VLJ Support team`. 
    - These mail tasks will be round robin distributed among the team members.
    - We update the VACOLS location to be CASEFLOW upon task assignment
    - We update the VACOLS location to be the attorney's upon task completion (like we do for admin actions today)
1. Allow mail team to create mail tasks for Privacy Act/FOIA and assign to Privacy office
    - [ ] Create Privacy team queue
    - [ ] Mail team can create `Privacy Act/FOIA` or `Privacy complaints` mail for AMA cases and route to the `Privacy team`
    - Mail can assign tasks the following teams: `VLJ Support team` + `Privacy team`
1. Allow mail team to create mail tasks for Hearing Related mail and assign to Hearing team (**only when Hearing Schedule has built this**)

### Open Questions
- Is there a chance we could support AMA AND legacy mail tasks for co-located to start? It would make their lives easier.
- Can we auto-populate assigned to teams for some mail task types - AOD motion, Privacy Act/FOIA.
- Do we want to change the names of any mail types?
- Which organization should process `Withdrawal of appeal` mail? Assuming co-located.
- Does VLJ support work mail for cases that have not yet been distributed to judges now that Case management branch does not exist?
- `Death Certificate` - assign to Wendy Bray, mail team. Can we have assign to person instead of assign to team for this one? Should we just create a mail team queue?

### Mail related stories
- When a mail employee is processing mail from the mail portal, they can create a mail task from the Actions dropdown in Case details, so that task can be assigned to the appropriate user.
- If there is an open mail task on the appeal, the appeal cannot be dispatched from the Board.

### Generic task related stories
- When a user is assigned a mail task, they can perform the generic queue task actions for it - complete, place hold, assign to other user, assign to other team, and cancel (maybe).
- When a user is assigned a mail task and they realize it is incorrect, they need to change/edit the task to reflect what should be done, and assign it to the correct user (if applicable).

## Resources
- Mail sketches - https://app.mural.co/t/workqueue2001/m/workqueue2001/1535659570198/59f25daa137f4d7ee24eb7884119f90dce565097
- Mail mural - https://app.mural.co/t/workqueue2001/m/workqueue2001/1531760214520/f444215272b533dc9981f0bea710158fce9c7ddd
- Q for Jed - https://github.com/department-of-veterans-affairs/dsva-vacols/issues/31

### Mail Types
Field Name:	MLTYPE
01	Change of Address
02	Congressional Interest
03	Controlled Correspondence
04	CUE Related
05	Evidence or Argument
06	FOIA Request
07	Hearing Related
08	Motion to Advance on Docket
09	Motion for Reconsideration
10	Power of Attorney Related
11	Professional Service Mail
12	Returned or Undeliverable Mail
13	Status Inquiry
14	Death Certificate
15	Appellate Group Mail
16	Extension Request
17	Privacy Act Request
18	Other Motion
19	Privacy Complaints
20	Intra/Inter Agency Request
21	Ebert Temporary Transfer
22	How Do I Appeal Pamphlet
23	ECA Revocation
24	FOIA Request & Other Actions
25	Motion to Vacate
26	Attorney Inquiry
27	Withdrawal of Appeal

**Comment by laurjpeterson** [comment]
Reviewing [October 2018 Mail SOP](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Documents/PrinciplesOfMailManagementOct2016.pdf)

- **Some mail types have auto-assignment. Requiring mail users to add in the destination of the task for AMA mail tasks could be a risk, since they haven't had to do this before.**
<img width="676" alt="screen shot 2018-07-19 at 1 11 53 pm" src="https://user-images.githubusercontent.com/27704093/42959026-5ea4d39a-8b55-11e8-8903-5bc69a29a5a4.png">

- Some mail types are processed by specific people.
<img width="698" alt="screen shot 2018-11-05 at 10 26 07 pm" src="https://user-images.githubusercontent.com/27704093/48041254-6437ad00-e14a-11e8-9e2f-99890897d7c7.png">

**Comment by laurjpeterson** [comment]
Discussion with Ivy and Jennifer Jessup 11/20:

- Change of address mail - should be handled by mail management team in the future, but not now. Can still be handled by VLJ support
	- current: add mail task in VACOLS, close it out, update address in VACOLS and VBMS (but not sure if they do)
	- it's a lot to have mail portal + Caseflow + VACOLS + VBMS open
	- mail team is unfamiliar with VBMS
- Pilot users: Tajuana Donaldson, Crystal Williams, Ivy Wilson

Routing rules - AMA:
- Attorney Inquiry - usually sent to Lit Support
- do we still send Death Certificates to Wendy Bray?
- Confirm with Maria Braswell that mail should go to VLJ support if at VSO
- Where should mail be assigned if it is a Hearing docket case?
	- e.g. if there is mail to reschedule a hearing
- QR - confirm with josh that they should get mail if the case is with them
- returned or undeliverable mail - should this go to BVA dispatch?  
- at the time the mail comes in, we don't know that there is a RAMP appeal form in the mail portal. Is it ok that that mail is still added and assigned in VACOLS?
- ? LRP - do Ebert Temporary Transfer or ECA, appeal pamphlet still exist?
- withdrawal - VLJ support. Confirm with LRP

RAMP appeal forms process:
- in Mail Portal - identify RAMP Selection Form (RAMP appeal)
- assign case to Ivy within Mail Portal
- Ivy distributes to 4 employees within her branch that are processing these
- employee gets it in their Mail Portal queue. Opens VACOLS, Caseflow, Mail Portal
- Search in. Caseflow to check if it has uploaded and processed already
	- Check issues to make sure they are the same, if they are, mark it as a duplicate (VBMS subject line field that also exists in Mail Portal)
- If it isn't a duplicate, start Caseflow Intake RAMP refiling flow
- Then, Caseflow Intake RAMP NOD flow
- Go to mail portal and click upload to VBMS
- Create letter for Veteran (MS word, Veteran address, claim number, docket, save as PDF)
- Upload letter to VBMS
- Add to Package feature in VBMS to mail to Veteran (some people do this in MS Word to create a label, if they don't want to use the Add to Package feature)

Questions
- do not create a mail task for multiple appeals. They associate mail with the active appeal. 

Legacy
- intake abeyance 25 - missing NOD, SOC, waiting for medical, waiting for SSOC

**Comment by laurjpeterson** [comment]
From Corey Benjamin:

1. Ebert Temporary Transfer – There is no longer a request for these as these were request for physical files to be transferred back to AOJ.  This will not be useful going forward.

2. ECA – This pertain to the Expedited Claim Adjudication cases that became appeals at BVA.  As this process no longer exist, it may not be useful going forward. 

3. Appeal pamphlet – Veterans continue to mail the Board pertaining to understand the appeal process.  Although receipt of these are limited we can consider keeping these.  We just have to figure out 1) who will be the responsible party issuing these pamphlets 2) consideration on changing the current pamphlet as we are going under AMA.

**Comment by laurjpeterson** [comment]
Emailed Heather to ask if we need to do a demo with union. This is the only process blocker before providing training and rolling out.

**Comment by laurjpeterson** [comment]
Update: best case scenario, we release to the 2 mail pilot users the week of monday, december 17. that week, we will shadow each user and observe their workflow creating mail tasks. tbd on who from our team will be sitting with them, but we want to do this to mitigate risk of missing any issues.

@lowellrex @sneha-pai @marvokdolor-gov 

i'd like to monitor in a Looker report:
- mail tasks created by type and user
- who mail tasks are assigned to, and marry them up with mail routing rules

**Comment by laurjpeterson** [comment]
Based on this [slack thread](https://dsva.slack.com/archives/CA1QBDLEL/p1545148239053500), we know that Veterans will send in correspondence to waive their 90-day evidence window. 

Some approaches:
- If the mail team recognizes that the mail item is a waiver of the evidence window
    - Mail team closes the `90 day evidence window` task
- If the mail team does not recognize that the mail item was a waiver of the evidence window
    - Mail team creates a general `Correspondence` task
- Open questions:
    - How should this task be routed? assuming it could automatically go to the person who "has" the case at the time. 
    - Whoever recognizes the waiver will close the 90-day evidence window task
    - How might we explain to users that they can close the 90-day evidence window task and that equals the Veteran waiving that window?

cc: @lowellrex - fyi, another mail scenario coming soon.

**Comment by marvokdolor-gov** [comment]
@laurjpeterson I have a little [Mail and Privacy Dashboard](https://caseflow-looker.va.gov/dashboards/19) going as a starting point for the [thought above](https://github.com/department-of-veterans-affairs/caseflow/issues/7404#issuecomment-443785053).
