### ISSUE TITLE
Handle PG::UniqueViolation error when canceling certification

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#741]
Right now if you click back button after Canceling certification and trying to resubmit, it will show:
<img width="1389" alt="pg--uniqueviolation" src="https://cloud.githubusercontent.com/assets/4960030/22269309/db55d0d0-e258-11e6-9b87-556e95191bf8.png">
  
Refer to #631

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
