### ISSUE TITLE
End Product | Change the "Required" label styling

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#742]
As the Product Owner, I would like the "Required" label repositioned and without parenthesis so that it is consistent with the application stylization.

# Acceptance Criteria
1. Verify that the "Required" label next to the field "Decision Date" has been updated to match application stylization as follows (refer to mockup):
- Italicized
- Red text
- Aligned to the right of field box

# Mockup
**_View - End Product Page - Before_**

**_View - End Product Page - After_**

**_Style Guide_**

# Related Stories
n/a

**Comment by shanear** [comment]
![Uploading Screen Shot 2017-02-07 at 2.14.39 PM.png…]()

This was done as a part of another issue. Closing.
