### ISSUE TITLE
Search | Link to case details page

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7431]
The search link on `/hearings/schedule` currently uses the same functionality as queue's search bar. That is, the results are displayed on `/cases/${id}` and when a user clicks on a result link, they're taken to queue's Case Details page `/queue/appeals/2096907/${id}`. 

In hearing scheduling, when a user is searching for a veteran, it's because they want to schedule the veteran for a hearing. The link on the search results page should go to `/hearings/queue/appeals/${appeal.id}`. 

Requires #6874

**Comment by mdbenjam** [comment]
I'm closing this, since we are now using the same URL as queue.
