### ISSUE TITLE
Intake | Add case search link to the navbar

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7437]
Claims Assistants sometimes want to be able to search for Appeals and other claims they just created to double check that everything looks right. In order to do this, we'll provide a search link in the header of intake.

## Acceptance Criteria
- On every page in the intake flow, there should be a link to the Case Search page. When clicked, t should open the search page in another window, not the same window.

## Notes
This link should not appear in the edit issues flow

## Technical Notes
Queue already includes this in the Navbar so we can look at their code to see how to do this.

## Mocks
It should look like the "Search Cases" link in the queue header

<img width="1282" alt="screen shot 2018-10-17 at 7 02 29 pm" src="https://user-images.githubusercontent.com/1596259/47121248-f893ab80-d23f-11e8-9e9d-d3f71a965e36.png">

**Comment by lowellrex** [comment]
PR where I finally put the link to case search in the correct place: https://github.com/department-of-veterans-affairs/caseflow/pull/7347

**Comment by shanear** [comment]
> open the search page in another window, not the same window.

It appears to be opening the search page in the same window

**Comment by leikkisa** [comment]
Oops, I missed that spec. Thanks Shane!

**Comment by shanear** [comment]
works! thanks sally 🙌
