### ISSUE TITLE
Release 2 | On hold | On hold table view

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7440]
As a hearing coordinator, I want to be able to place "admin" type actions on hearings that can't be scheduled to make sure they do not get lost. I also want to be tied to a Regional Office, because I am assigned entire RO's that change frequently. 

### Acceptance Criteria
- [ ] Verify that there is a toggle above the date selector 
- [ ] Verify that the toggle is called "on hold vetearns"
- [ ] Verify that when this toggle is selected, the date selector is removed
- [ ] Verify that a table appears with the following table names:
  - Case details
  - Task 
  - Type
 - Docket
- [ ] Verify that when the days waiting exceeds selected the days waiting turns red
- [ ] Verify that when the user clicks the case details it takes them to the case details 
- [ ] Verify that the RO filter is still there so the User can cycle through RO on holds without having to go back to the assignment page

### Related issues

**Comment by MeredithStewart** [comment]
new epic replaces: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
