### ISSUE TITLE
Release 2 | On hold | Case details place on hold

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7441]
As a hearing coordinator, I want to be able to place an appeal on hold in the case details view, so I can make a decision while reviewing the case. 

### Acceptance criteria
- [ ] Verify that there is an option called "on hold"
- [ ] Verify this takes them to a page that allows them to the place on hold page

**Comment by MeredithStewart** [comment]
new epic replaces: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
