### ISSUE TITLE
Release 2 | On hold | On hold checkout page

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7442]
As a hearing coordinator, I want a simple way to place something on hold where I can select the reason, the duration, and task instruction.

### Acceptance criteria 
- [ ] Verify that this page is called Place [Veteran's name] case on hold
- [ ] Verify that the veteran ID appears underneath the title in the following format
     **Veteran ID:** #
- [ ] Verify that there is a HZ line separating the title with the rest of the page
- [ ] Verify that there is a drop down called "Reason for on hold" with the following options
   - POA Clarification
    - Incarcerated Veterans
    - Contested claim
    - Address verification
- [ ] Verify that there is a dropdown called "Select the total number of days to place on hold"
- [ ] Verify that there is a notes area called "Task Interaction"
- [ ] Verify that there is a button called "Place on hold" that sends them to the confirmation page
- [ ] Verify that there is a button called "cancel" that sends the user back to case details

**Comment by MeredithStewart** [comment]
new epic replaces: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
