### ISSUE TITLE
Release 2 | On hold | Confirmation of on hold

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7443]
As a hearing coordinator, I need to know when a case has been succcesssfully placed on hold.

### Acceptance Criteria
- [ ] Verify that when a user clicks the place on hold button in the create on hold page, that they are sent to the table with the following confirmation
- [ ] Title [Veteran Name] has been placed on hold for [#] days
- [ ] Body: When this hold is completed, it will be automatically sent back to the the assignment queue

**Comment by MeredithStewart** [comment]
new epic replaces: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
