### ISSUE TITLE
Release 2 | On hold | Mark as complete

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7444]
As a hearing coordinator, I want to be able to mark an admin action as complete and move it back to the assignment queue

### Acceptance Critiera
- [ ] Verify that when a user clicks on the case details in the on hold tab, there is an action called
"send back to hearing assignment" 
- [ ] Verify that when the user clicks this a modal pops up with the title "Mark as complete"
- [ ] Verify this modal has the following body copy: Mark this task as "complete" and send the case back to the scheduling pool.
- [ ] Verify an hz line below the copy
- [ ] Verify that there is a button in the bottom right called "Mark as complete"
- [ ] Verify that there is a link in the bottom left called "Cancel" 
- [ ] Verify that when the mark as complete button is clicked it sends the user back to the assignment table with the confirmation
- [ ] Verify it is no longer in the on hold toggle

### Mocks

**Comment by MeredithStewart** [comment]
new epic replaces: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
