### ISSUE TITLE
Release 2 | On hold | Confirmation of completed on hold

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7445]
As a hearing coordinator, I want to be able to confirm that I completed an on hold task and that it has been removed form the on hold queue of the RO.

### Acceptance Criteria
- [ ] Verify that when a user completes a task in the on hold toggle of the RO, the user gets the following confirmation message
- [ ] Title: [Veteran's name] has been marked as complete
- [ ] Body: If you made a mistake, please email your supervisor to make any changes

### Mocks

**Comment by MeredithStewart** [comment]
new epic replaces: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
