### ISSUE TITLE
Release 2 | Hearings search | Search on all pages

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7447]
As a hearing coordinator, I need to search for individual veterans based on AOD's, congressional requests, to respond to VSO status requests, and fix errors. 

### Acceptance criteria 
- [ ] Verify that search is implemented across the following pages 
  - Assign table
  - Schedule 
  - Case details
  - Daily docket
- [ ] Verify we are implementing the most up to date search where there is al ink in the nav bar

**Comment by MeredithStewart** [comment]
On hold until requested for by users.
