### ISSUE TITLE
Release 2| Hearing search | Assign via case details 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7448]
As a hearing coordinator, I need to be able to assign a hearing relevant case from the search page. Otherwise, I would have to go back to the assign table and reach a dead end in the flow making it cubersome. 

### Acceptance criteira
- [ ] Verify that when a user clicks on the case details from the search page that has a schedulable hearing it has the following actions: 

- Assign hearing
- Place on hold

- [ ] Verify that clicking on these actions takes them to the correct pages

**Comment by MeredithStewart** [comment]
@MeredithStewart -- To test with Justin to confirm this is working from the Search implementation on View Schedule home page.

**Comment by MeredithStewart** [comment]
@sharonwarner -- Tested with Justin Madigan 11/5/18 -- "Schedule Veteran does not appear."
