### ISSUE TITLE
Hearing Prep/Schedule | Hearing types

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7451]
We're currently using different display values for hearing types. We need to pick our default display values and use them consistently across both (all) applications. 

"C" => "Central" or "CO"
"V" => "Video"
"T" => "Travel"

**Comment by MeredithStewart** [comment]
Justin decided on Central (to avoid confusion with Colorado). He'd prefer "Central Office" where there's more room.
