### ISSUE TITLE
Queue | Caseflow is creating duplicate Decass (DAS) records

### ISSUE THREAD

**Issue by evankroske** [department-of-veterans-affairs/caseflow#7461]
For example, the case 3289614 has two Decass records that were created 10/16 and 10/17. This isn't supposed to be possible.

**Comment by evankroske** [comment]
## Problem
When a judge assigns a case to another judge, Caseflow creates a Decass record for the case. When the second judge assigns the case to an attorney, Caseflow creates another Decass record. The duplicate Decass records may be skewing productivity reports for judges.

## Implemented Short-Term Fix
I modified the code that Caseflow uses to assign cases from judges to attorneys to throw an exception if the case already has a Decass record. This prevents the creation of any duplicate Decass records. However, some cases, including OMO cases, should have more than one Decass record, so this code will have to be changed once we add support for OMO cases. In addition, this fix allows Caseflow to create Decass records when cases are assigned by chief judges to judges. These Decass records shouldn't be created because DAS doesn't create them in this case.
https://github.com/department-of-veterans-affairs/caseflow/issues/7461

## Research Notes
I used the following query to confirm my hypothesis that the duplicate Decass records were created when judges assigned cases to other judges:

```sql
select dups.defolder, locdout, LOCSTOUT, s1.svlj, LOCSTTO, s2.svlj
from (select defolder
from decass
where deadtim >= to_date('2018-10-10', 'YYYY-MM-DD') 
group by defolder
having count(*) > 1) dups join
	priorloc on dups.defolder = lockey join
	staff s1 on locstout = s1.stafkey join
	staff s2 on locstto = s2.stafkey
where rownum <= 1000
order by dups.defolder, locdout;
```

**Comment by evankroske** [comment]
## Proposed Fix: Allow Assignee to Specify Assignment Type
As I understand it, DAS requires the user to choose which type of assignment to use. I think that Caseflow should adopt the same approach. Judges would be able to choose whether to create a Decass record for an assignment. We should use the same language as DAS to make the distinction between the two types of assignment clear.

**Comment by hschallhorn** [comment]
Reopening as this was reverted in #11994 7547

**Comment by tomas-nava** [comment]
### query to find duplicate DAS records:

_SQL_
```sql
SELECT
  defolder,
  COUNT(defolder)
FROM decass
WHERE deassign >= '2018-07-01'
AND (deprod IS NULL OR deprod NOT IN ('REA', 'REU', 'VHA', 'IME', 'AFI', 'OTV', 'OTI'))
GROUP BY defolder
HAVING COUNT(defolder) > 1;
```

_ActiveRecord_
```ruby
VACOLS::Decass.select("defolder").where("deassign >= ?", Date.new(2018, 7, 1)).where("deprod IS NULL OR deprod NOT IN ('REA', 'REU', 'VHA', 'IME', 'AFI', 'OTV', 'OTI')").group("defolder").having("count(*) > 1")
```

### Work product abbreviations

Decass records with the `deprod` (work product) abbreviations below are excluded in the query because when any of those work products are used, we expect a second work product to follow.

| abbreviation | meaning |
| --- | --- |
| AFI | Another type of opinion |
| IME | Independent Medical Exam |
| OTI | Overtime IME |
| OTV | Overtime VHA opinion |
| REA | Reassigned |
| REU | Reassigned unsat |
| VHA | VHA opinion |
