### ISSUE TITLE
Allow VSO users to assign cases to VSO users

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7480]
When a VSO user is viewing AMA appeals needing an IHP, they want to assign the case to a member of their organization, so the IHP can be written.

## AC
- In the Actions dropdown of Case details, a VSO user has the option to assign the task to a user within their organization

## Related
https://github.com/department-of-veterans-affairs/caseflow/issues/9693

**Comment by laurjpeterson** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/5581#issuecomment-434355384

**Comment by laurjpeterson** [comment]
Re-opening because this engineering work still has to be done

**Comment by hschallhorn** [comment]
done in #7767
