### ISSUE TITLE
CO Release | Daily docket | Default date selection

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7486]
As a hearing coordinator, I need a way to pick the original date of the daily docket in case I change it on accident. 

### Acceptance Criteria 
- [ ] Verify that the dropdown shows the default date with a line underneath 
- [ ] Verify that it freezes as the user scrolls
OR
- [ ] Verify that the top date is always the default date 

**The first would be very useful. Included second option incase loe is very high so the user does not get lost in the dropdown. If the first is too much work....the second is fine. idc**

### Mocks
![screen shot 2018-10-22 at 8 12 06 am](https://user-images.githubusercontent.com/23316107/47291569-32630a00-d5d2-11e8-8e3a-61c77a9321e7.png)

_We do something similar in Readeer_
![screen shot 2018-10-22 at 8 11 26 am](https://user-images.githubusercontent.com/23316107/47291573-368f2780-d5d2-11e8-9aff-9f389f2dd3c0.png)

**Comment by MeredithStewart** [comment]
Resolved with cancel introduced.
