### ISSUE TITLE
Build schedule | Validation copy clean up

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7492]
#### Video

- [ ] The start date, end date, or file are missing --> 
The start date, end date, or file is missing. Please verify you have uploaded a file and inputed a date range.

- [ ] The end date is before the start date --> Please verify that the end date is before the start date 

- [ ] You have already uploaded a file for these dates --> You have already uploaded a file for these dates. Please verify that your spreadsheet contains dates that were not previously uploaded.

- [ ] The RO non-availability spreadsheet contains duplicate dates for an RO. ---> The RO non-availability spreadsheet contains duplicate dates for an RO. Please verify that every RO has a unique set of dates. 

- [ ] The RO non-availability spreadsheet contains the same RO twice. --> The RO non-availability spreadsheet contains the same RO twice. Please verify that the following RO only appear once in this spreadsheet:

- [ ] The RO non - availability spreadsheet contains dates outside the selected range --> 
The RO non - availability spreadsheet contains dates outside the selected range. Please verify that all dates in the this spreadsheet are within the date range you selected.  

- [ ] The RO non-availability spreadsheet contains dates that are not in this format: mm/dd/yyyy. --> The RO non - availability contains dates that are not in the correct format. Please verify that all dates in this spreadsheet are in the mm/dd/yyyy format. 

- [ ]  The RO non-availability spreadsheet does not follow the template  -->
The RO non-availability spreadsheet does not follow the given template.  Please verify that this spreadsheet follows the format in the template including the format and title of headers, rows, and dates.

- [ ] The RO non-availability spreadsheet contains different ROs than we have in our system. --> The RO non-availability spreadsheet contains RO's that are not recognized in Caseflow.  Please verify that that all RO's in this spreadsheet are correct.

#### Central Office
- [ ] The central office non-availability spreadsheet  contains duplicate dates --> The central office non-availability spreadsheet contains duplicate dates. Please verify that every date in the CO spreadsheet is unique. 

- [ ] The central office non-availability spreadsheet contains dates that are not in this format: mm/dd/yyyy. --> The central office non - availability contains dates that are not in the correct format. Please verify that all dates in this spreadsheet are in the mm/dd/yyyy format. 

- [ ] The central office non-availability spreadsheet does not follow the template. ---> 
The central office non-availability spreadsheet does not follow the template.  Please verify that this spreadsheet follows the format in the template including the format and title of headers, rows, and dates. 

### Allocation errors
- [ ] The allocation spreadsheet has the incorrect data type for an allocation. --> **What does this mean?**  

- [ ] The allocation spreadsheet contains different ROs than we have in our system. --> The RO non-availability spreadsheet contains RO's that are not recognized in Caseflow. Please verify that that all RO's in this spreadsheet are correct. 

- [ ] The allocation spreadsheet contains the same RO twice. --> The allocation spreadsheet contains the same RO twice. Please verify that the following RO only appear once in this spreadsheet:

- [ ] The allocation spreadsheet does not follow the template. --> The RO non-availability spreadsheet does not follow the template. Please verify that this spreadsheet follows the format in the template including the format and title of headers, rows, and dates. 

### Judge allocation

- [ ] The judge non-availability spreadsheet contains dates that are not in this format: mm/dd/yyyy. --> The judge non - availability spreadsheet contains dates that are not in the correct format. Please verify that all dates in this spreadsheet are in the mm/dd/yyyy format. 

- [ ]  The judge non-availability spreadsheet does not follow the template. ---> The RO non-availability spreadsheet does not follow the template. Please verify that this spreadsheet follows the format in the template including the format and title of headers, rows, and dates. 

- [ ] The judge non-availability spreadsheet contains duplicate dates for a judge ---> The judge non-availability spreadsheet contains duplicate dates for a judge. Please verify that the following judge is assigned different dates: 

- [ ] The judge non-availability spreadsheet contains dates outside the range you selected ---> The judge non - availability spreadsheet contains dates outside the selected range. Please verify that all dates in the this spreadsheet are within the date range you selected.  

- [ ] The judge non-availability spreadsheet contains a judge not in our database. ---> The judge non-availability spreadsheet contains a judge not recognized in Caseflow. Please verify that that all judges in this spreadsheet are correct.

**Comment by sharonwarner** [comment]
Closing - can  use #6777 to track progress.
