### ISSUE TITLE
New co-located pilot user

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7496]
Tim Owens is out on military leave, so we will bring Marvin Koroma into the list.

## AC
- Transfer all of Tim Owens' assigned tasks to Marvin Koroma in the same way they are in Tim's queue (e.g. on hold tasks go to the on hold column (unless hold times have finished)
- Change round robin work to go to Marvin Koroma instead of Tim Owens

**Comment by lowellrex** [comment]
All 10 of Tim Owens's incomplete tasks (7 of which were on hold) were reassigned to Marvin Koroma.
