### ISSUE TITLE
Start/Doc Comparison Page: Reduce emphasis of "This case cannot be certified button"

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#75]
One participant mistakenly clicked the "This case cannot be certified" button immediately as soon as they saw the error page. As a result they had to re-open the case using VACOLS causing a lot of extra work.

Suggestion: Significantly reduce the emphasis of this option by making it a link-style button. Consider hiding the option behind a link. Consider adding a confirmation dialogue before allowing the user to use the option.

**Comment by alex** [comment]
This was finished.

<img width="609" alt="screen shot 2015-10-30 at 3 58 43 pm" src="https://cloud.githubusercontent.com/assets/772/10856607/1c308706-7f1f-11e5-85b0-fd188a921244.png">
