### ISSUE TITLE
Form 8 | Whitespace text field trimming

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#750]
# Description:
As a Regional Office Caseworker, when filling out Form 8;
If I input white space into any of the text fields (even required);

**Expected:** that the whitespace will be trimmed and an error will show up and PDF not be generated
**Actual Result:** PDF is generated with empty fields; for questions 5A/6A/7A the corresponding dates are not generated (implying that the whitespace does get trimmed)
_Addtionally:_ Validate that databases are updated correctly.

**Type of Bug:**
- [X] Functional

- [X] UI

- [ ] Security

- [ ] Tech Improvement

# Reproductive Steps
**Scenario 1:**
**`demo`**

1. Proceed to Complete Form 8

2. Fill all/any of the text fields with whitespace `   `; you can even replace preloaded text with whitespace.

3. Click Preview Completed Form 8

4. Observe that no errors are generated

5. Observe that PDF is generated with blank entries (overflow remarks are still generated, but show blank)

# Screen Shots
**_Scenario 1 - `demo` Complete Electronic Form 8_**
<img width="614" alt="screen shot 2017-01-25 at 09 36 55" src="https://cloud.githubusercontent.com/assets/18075411/22295163/ee70f77c-e2e3-11e6-9cd3-818f94e37bd8.png">

**_Scenario 2 - `demo` Generated PDF_**
<img width="986" alt="screen shot 2017-01-25 at 09 52 59" src="https://cloud.githubusercontent.com/assets/18075411/22295199/15796520-e2e4-11e6-9e53-32ae1509f4af.png">
<img width="978" alt="screen shot 2017-01-25 at 09 53 03" src="https://cloud.githubusercontent.com/assets/18075411/22295200/157a4b20-e2e4-11e6-88ec-fdc711f1eed7.png">

# Relate Stories/Issues
**_Support Tickets/Features/Issues_**
Certification Cancellation Modal: Whitespace validation and character limit - #738

**Comment by nikitarockz** [comment]
prioritized - bottom

**Comment by astewarttistatech** [comment]
**PASSED** 

Environment Validated In: UAT

Steps to Validate:
1. Go to https://certification.cf.uat.ds.va.gov/certifications/new/2765748
2. Fill in all the required fields w/ white space.
3. Try to submit Form 8
4. Validate that Form 8 reloads with error messages prompting the user to fill in the fields with actual text. 

Screenshots: 
<img width="1311" alt="screen shot 2017-02-03 at 11 18 55 am" src="https://cloud.githubusercontent.com/assets/23038505/22598847/d022385a-ea02-11e6-9c02-d17dee1175ff.png">
