### ISSUE TITLE
Manually create BVA dispatch tasks for QR'ed RAMP appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7504]
Josh Freeman confirmed that his team has finished QRing 5 RAMP appeals. The five appeals are in this report - https://caseflow-looker.va.gov/looks/61. We need to create BVA dispatch tasks for them so they can be dispatched from the Board

## AC
- BVA dispatch tasks have been manually created for the 5 appeals in this report - https://caseflow-looker.va.gov/looks/61

**Comment by lowellrex** [comment]
Done! The looker still has the cached statuses of those tasks, but they have been marked complete and `BvaDispatchTask`s have been created for those 5 appeals.
