### ISSUE TITLE
Update tasks in Case Timeline with new user-facing task names

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7508]
Scope: Focusing on AMA and AMA + legacy tasks right now, excluding legacy only tasks.

# Goals

- Any BVA user (regardless of their role) should be able to pop in to Caseflow and understand the status of an open task with little context
- Make task names consistent, understandable, and plain language

# Writing Rules

Proposed rules for writing Caseflow tasks: 
- Always start with an action verb so that tasks sound "actionable". Tasks should read like a list of "to-do's" for a case. 
- Use task names to clearly indicate to the user what needs to happen, but keep them general enough so that they aren't too narrow or specific.
- Avoid BVA jargon or department-specific jargon, like the word "dispatch". (Example: Can say "send" rather than "dispatch") so all users can understand.

When naming a new task, aim to start the task with a verb that's already used in other task names. Avoid starting a task name with a different verb that means the same thing as other verbs we use. (Ex: We shouldn't have two tasks called "Find IHP" and "Locate hearing request". Find and locate mean the same thing, and we can standardize the language to make it easier on our users.)
Examples of verbs we use:
- Review _____
- Draft _____
- Send _____
- Find _____
- Sign _____
- Complete _____

# Interactions that create tasks
- When creating a task on the Root, use the `Create a new task` link in Task Snapshot. 
- When creating a child task, use the Actions dropdown in Task Snapshot
---

# Tasks

## When an appeal is established

Scenario | Task created on the `RootTask`| User facing task name
---|--- |---
Hearing Request docket appeal | `ScheduleHearingTask`| Confirm hearing request
Evidence Submission docket appeal | `90DayEvidenceWindowTask` | Start 90-day window for new evidence
All dockets | `DistributionTask` | N/A - not shown on front end 
Appeals from San Juan or Manila RO | `TranslationTask` | Translate document(s)

## VSOs
Scenario | Task created on the `RootTask`| User facing task name
---|---|---
If Veteran has an IHP-writing VSO | `InformalHearingPresentationTask`| Draft Informal Hearing Presentation (IHP)
If Veteran has a VSO (any VSO) | `TrackVeteranTask` | N/A - not shown in queue tables or case timeline, just here for tracking purposes

In the future, VSO users will be able to assign IHP tasks to individuals.

## Hearings
This section is a work in progress. @allyceh synced with @ShellySmithDSVA and has an inventory of all of the tasks and actions available to people using Hearing Schedule. Phase 2 of this effort will include syncing with Shelly on proposed task names that fit the schema of the names we've identified here, but that also meet the Hearings users' unique needs. 

Scenario | Task created on the `RootTask`| User facing task type
---|---|---
Hearing Request docket appeal | `ScheduleHearingTask`| TBD
A hearing docket AMA appeal has been scheduled, next step is to hold the hearing | `HoldHearing`| TBD
A hearing has been held, next step is to transcribe hearing | `TranscribeHearing` | TBD
A Veteran requests their transcript | `TranscriptRequest` | TBD

## Mail
Scenario | Task created on the `RootTask`
---|---
Mail comes to BVA in the Mail Portal, Mail team creates task in Caseflow | `MailTask`, with a child correspondence type task (e.g. Change of Address, Evidence or argument, Privacy)

Original naming of correspondence types here: https://github.com/department-of-veterans-affairs/caseflow/issues/7906#issuecomment-440442213
- Review address change
- Review evidence or argument
- Review hearing documents 
- Review power of attorney documents 
- Review returned or undeliverable mail 
- Review extension request
- Review AOD motion
- Review FOIA request
- Review privacy act request
- Review privacy complaints 
- Review congressional inquiry
- Review controlled correspondence 
- Review CUE-related
- Review motion for reconsideration
- Review case status inquiry 
- Review other motion
- Review motion to vacate
- Review appeal withdrawal 
- Review death certificate 

## Privacy 
- if coming from VLJ support, Privacy tasks are child tasks of that VLJ support task
- If coming from mail, Privacy tasks are child tasks of the `MailTask`

## Admin actions assigned by attorneys to VLJ Support
- All are `ColocatedTasks` with distinct labels (?)
  - Find Informal Hearing Presentation (IHP)
  - Send waiver of AOJ letter
  - Send Arneson letter
  - Send hearing clarification letter
  - Send POA clarification letter
  - Send unaccredited representative letter
  - Send retired VLJ letter
  - Send new rep arguments (PT_VSO) letter
  - Put on hold (extension request)
  - Find missing hearing transcript
  - Confirm hearing request (note: legacy only)
  - Put on hold (pending scanning banner in VBMS)
  - Find missing records 
  - Verify address
  - Other
  - Translate documents

## Judges

Scenario | Task | Root or Child| User facing task type
---|---|---|---
When an appeal is distributed to the judge | `JudgeAssignTask` | Root | N/A - task type not shown in Assign Cases view or Case Timeline 
When an attorney finishes drafting a decision | `JudgeDecisionReviewTask`| Root | Sign decision
When QR asks judges to revise a decision | `JudgeQRTask` | ? | Revise decision (quality review)
When BVA employees need judges to sign motions (there are probably quite a few of these) | `JudgeMotionTask`| Child | Sign motion
**When judges are assigned tasks from BVA dispatch, and BVA dispatch is blocked from dispatching the case** | `JudgeDispatchTask`| Child | Correct decision

## Attorneys
Scenario | Task | Root or Child| User facing task type
---|---|---|---
Judge assigns case to attorney | `AttorneyTask` | Child to `JudgeDecisionReviewTask` | Draft decision
Judge asks attorneys to rewrite decision | TBD ? | Child to  `JudgeDecisionReviewTask` | Revise decision (judge review)

## QR
Scenario | Task on the `RootTask`| User facing task type
---|---|---
Case is selected for Quality Review | `QualityReviewTask`| Conduct quality review

## Dispatch
Scenario | Task on the `RootTask`| User facing task type
---|---|---
Judge checks out the case to BVA dispatch |`BvaDispatchTask` | Send decision letter

Need to define Caseflow tasks created in non-comp business line queues for benefit adjustment in collab with @shanear and Intake team

## Lit Support: Congressional Inquiries (WIP)

WIP: @sneha-pai and @allyceh to propose tasks and names. 

Scenario | Task | User facing task type
---|---|---
Lit Support receives a congressional inquiry by phone or email, assign to Lit Support team lead | `CongressionalInterestTask`| TBD
Lit Support receives controlled correspondence from White House or secretary's office | `ControlledCorrespondenceTask` | TBD
Lit Support needs to respond to a Veteran question in a survey response | ?
Lit Support staff creates a draft of congressional correspondence, assign to Lit Support team lead (or other?) for review | `?` | TBD
Team Lead approves draft and submits letter for Chairman signature, date stamping, uploading to VBMS | `?` | TBD

## Lit Support: CAVC (WIP)

WIP: @sneha-pai and @allyceh to propose tasks and names. 

Scenario | Task | User facing task type
---|---|---
Lit support places a case on hold because of CAVC appeal. Required action in Notes section | `?` | TBD
Case returns to the board from CAVC and now the board needs to notify veteran, route to VLJ office of appellate operations (OAO) | `?` | TBD

- Post decisional motions may lead to more task types

**Comment by lowellrex** [comment]
This mapping will be significantly cleaner once we remove the action column from the task table (#7686) and rely entirely on a task type's label method.

**Comment by laurjpeterson** [comment]
@MeredithStewart - here's the gh issue where we've been brainstorming names of tasks for users. Please weigh in on Hearing Schedule tasks, and add Hearing Admin Action tasks. I think it'd be nice for this to contain all task types, but feel free to link to other documentation for Hearing Admin Actions if you already have it somewhere else.

**Comment by laurjpeterson** [comment]
@allyceh @eric-nava - here's where I think we can work together on user facing task types - what users see in case timeline and currently active tasks. Still WIP, as you can see by the ? marks. Any and all suggestions for naming task types is welcome!

**Comment by eric-nava** [comment]
`JudgeDispatchTask` seems to be a potential bottleneck for the Veteran experience. Once there is a decision ready for dispatch, the priority should be getting it out the door. Potential solutions for this: create completion time window on this task. Then, either:

-  Close at expiration and send back to BVA Dispatch queue and prompt BVA Dispatch to reassign Judge, in the event time window expires. 

or

- Re-sort this task to the top of Judge Queue with an overdue time notice (borrow "overdue" design pattern from #8277)

**Comment by nicholasholtz** [comment]
Hey @allyceh - on this, a question or two: 
![image](https://user-images.githubusercontent.com/16781398/54030936-35265c00-417b-11e9-8df7-9864aefce159.png)

- Is this suggesting that the Board is sending notices to Veterans upon receipt of a non-remand CAVC decision? If we are talking remands, why is an NOD being sent to the Veteran? If it is a remand, I understand holding it 90 days (though, from my understanding, Veterans are not permitted to add new evidence in that window, only argument), but not sending an NOD.
- Does a new appeal task need to be created to intake the CAVC remand? (see https://github.com/department-of-veterans-affairs/caseflow/issues/8547, section on CAVC remands, noting the need to intake these).

**Comment by allyceh** [comment]
Hi @nicholasholtz -- I didn't add that one. This issue is a place to rename tasks/inventory tasks we have/propose new ones, so I am going to remove this. I don't know that we need that task at this point.

And yes, I think we should create a new appeal task for CAVC remands!

**Comment by allyceh** [comment]
Added @sneha-pai as an assignee for this ticket so that this stays on the radar with all of the case timeline design work.

**Comment by mbaenatan** [comment]
Per prioritization discussion with engineering and product, we should consolidate all case timeline tickets and create an Epic for case timeline improvements.
