### ISSUE TITLE
AMA Intake | Fix question spacing

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7517]
The spacing on the rating issues Add Issues modal is off, we should fix that.

## Technical Notes
- We should look for an opportunity to improve the shared modal component - if this looks reasonable, create a followup issue for that and tag @kencheeto , but keep the scope of this issue limited to the mentioned modal.

## Acceptance Criteria
- The spacing between ratings on the first Add Issues modal should be corrected to match the mock.

## Mocks
Top is what it should be. Bottom is current state.
<img width="635" alt="screen shot 2018-10-23 at 8 44 31 pm" src="https://user-images.githubusercontent.com/1596259/47399014-c0d7a880-d704-11e8-96cf-21328ea665d4.png">

## Notes
No need to be pixel perfect, just need it to satisfy the following request
> the distance from each section title to the content should be the same, and the distance from the end of the content to the next section of data should be the same and slightly higher than the distance from the tile.

The spacing between radio questions on the review page of both Appeals and HLRs also looks a little off. This might be related and something we want to look into:
![screen shot 2018-10-26 at 1 00 04 pm](https://user-images.githubusercontent.com/1596259/47581398-459e0e80-d91f-11e8-8861-ee940d54b86e.png)

**Comment by shanear** [comment]
I think this fix may have made things very squishy on the review page:
![screen shot 2018-11-01 at 7 07 09 pm](https://user-images.githubusercontent.com/1596259/47884999-5829b380-de09-11e8-85bb-6969f15e0def.png)

**Comment by pkarman** [comment]
fix in #7690

**Comment by shanear** [comment]
![screen shot 2018-11-05 at 5 07 36 pm](https://user-images.githubusercontent.com/1596259/48029920-7a7b4400-e11d-11e8-8246-9673684dacd4.png)
![screen shot 2018-11-05 at 5 08 49 pm](https://user-images.githubusercontent.com/1596259/48029921-7bac7100-e11d-11e8-98c2-72ad8b4965a2.png)

Looks awesome 💃
