### ISSUE TITLE
[Discussion] Not all legacy appeals have Veteran info in BGS

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7523]
How do we handle legacy appeals that don't have veteran info in BGS

#### 1. Default to Vacols. 

Pros: 
* A Caseflow user can see VACOLS info

Cons:
* Addresss (Veteran, Appellant, and POA) are difficult to parse from VACOLS
* Code base will need to handle two different paths
* No single source of truth

#### 2. Ask a user to update this info in SHARE

Pros:
* One source of truth
* Code is cleaner
* Move forward VACOLS deprecation 

Cons:
* Who is responsible for updating this information in Share

**Comment by laurjpeterson** [comment]
Is it possible to get a count of how many legacy appeals don't have Veteran information in BGS? (maybe we just look at active appeals?)

I think option 2 is possible, but depends on how many there are and therefore how big the task is.

**Comment by laurjpeterson** [comment]
@shanear @cmgiven @mdbenjam - if you have any thoughts here

**Comment by aroltsch** [comment]
@laurjpeterson I ran a sample in production and out of 400 appeals, 358 had veteran information.

**Comment by aroltsch** [comment]
Well, surprisingly I am seeing better results now. I ran 3 samples randomly selecting 400 legacy appeals. All of them had veteran info.

```
res = LegacyAppeal.all.sample(400)
result = res.reject { |r| r.veteran.present? }
result.size => 0
```

**Comment by cmgiven** [comment]
Head scratcher.

**Comment by cyber-gov-shane** [comment]
Just a note, this is going to be an even bigger problem with AMA and non-comp business lines, so VACOLS is not the answer. I think we need to work out a method for anyone in the VA to get a veteran added to the VBA corp database. Not sure how that would work, but that should be the first course of action.

**Comment by shanear** [comment]
Gave the AMA scenario some more thoughts. Tracking options here:

https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1050

**Comment by aroltsch** [comment]
Closing in favor: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1050#issuecomment-437460219
