### ISSUE TITLE
Show "send to team" options for all colocated legacy tasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7533]
Currently if an attorney creates an administrative task with a type (in the action field) of either "Schedule hearing" or "Translation" (for a legacy appeal) then the colocated staffer can send the case to that team in (charge the case to the correct location in VACOLS). However, if the task type is not either of those two actions (say it is other because the attorney didn't take the time to read the list of options and just picked "other") then neither of those options show up in the dropdown actions menu.

Alternatively, we could allow the colocated staffer to change the task type (action) to the type that would allow the action (assigning to the correct team) that they would like. My only fear with this approach is that it requires some knowledge about which actions are available to the different task types. For example, if Billie Colokes receive an ColocatedTask with action "other" but wants to charge the task to hearings scheduling team, would Billie know that they need to first change the task type to "Schedule hearing" (and not "Hearing clarification" or any other task type) before seeing that option available to them?

## Acceptance criteria
* "send to schedule hearing team" and "send to translation" task actions appear in the dropdown for all colocated tasks for legacy appeals.

**Comment by laurjpeterson** [comment]
@lowellrex - I think we should ask the VLJ Support user to change the task type where possible, first. The story is captured in this ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/7126 - but the design has yet to be posted (because focus has been on Lit Support mapping this week). cc: @sneha-pai

**Comment by hschallhorn** [comment]
These are now automatically routed to the correct team in #11113
