### ISSUE TITLE
AHL | All alternate hearing locations for an RO

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7546]
We need a json object that contains all alternate hearing locations for an RO. We should create a new file called `alternate_hearing_locations.rb` that contains a json object in the following format: 

```
{
  RO01: [
    {
      addres_line1: "",
      address_line2: "",
      address_line3: "",
      city: "",
      state: "",
      zipcode: ""
    }
  ]
}
```

We should add a method in `regional_office.rb` that will retrieve the alternate hearing locations for any RO.

[Consolidated Alt Locations & Facility Locator.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2515814/Consolidated.Alt.Locations.Facility.Locator.xlsx)

**Comment by MeredithStewart** [comment]
@sharonwarner @lomaxap attached spreadsheet here -- we should pull the addresses from the facility locator: 
[Consolidated Alt Locations & Facility Locator.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2515826/Consolidated.Alt.Locations.Facility.Locator.xlsx)

We won't include those locations I've identified as back up locations. Keep in mind that we will drop one of the Maui locations (I need them to confirm if the CBOC or the Vet Center is the backup hearing location). 

Two of the alt locations addresses need to be updated in the facility locator - I've put in the request to get those done.
