### ISSUE TITLE
Simplify task access/assign controls

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7551]
Currently we have three different functions that control access to tasks:
* [ApplicationController.can_assign_task?](https://github.com/department-of-veterans-affairs/caseflow/blob/70ab6077583e03e108e7b776e2934bf517e429f8/app/controllers/application_controller.rb#L133)
* [Task.verify_user_access!](https://github.com/department-of-veterans-affairs/caseflow/blob/70ab6077583e03e108e7b776e2934bf517e429f8/app/models/task.rb#L113)
* [Task.verify_user_can_assign!](https://github.com/department-of-veterans-affairs/caseflow/blob/70ab6077583e03e108e7b776e2934bf517e429f8/app/models/task.rb#L119)

I suspect these functions aspire to solve similar problems. If so, then we should consolidate them into a single function. If these are truly satisfying different objectives (assign vs. view perhaps?) then we should make that distinct clearer.

**Comment by mdbenjam** [comment]
I think this has changed a decent bit: @lowellrex are there still changes you wanted to make here?

**Comment by lowellrex** [comment]
Nope! I think this is mostly solved for now. Closing it out.
