### ISSUE TITLE
Determine which tasks for an appeal are actionable for a given user

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7557]
Currently we have a handful of places on the frontend where we decide which task to show for a given appeal and user combination (tasksForAppealAssignedToUserSelector, tasksForAppealAssignedToAttorneySelector, organizationTasksByAssigneeIdSelector, incompleteOrganizationTasksByAssigneeIdSelector). A [recent PR added a way](https://github.com/department-of-veterans-affairs/caseflow/pull/7423/files#diff-2a3f4e296b35f6015a2d1d3ef72e5506R138) to select only the tasks that are actionable by the current user. We should use that selector in place of the various selectors that serve the same purpose where possible. Additionally, we need to figure out which task is most salient (and probably make the other task not actionable) in the case where a single user can see two actionable tasks for the same appeal (say an organization's task as well as a task assigned to a person).

**Comment by mdbenjam** [comment]
Fixed here: https://github.com/department-of-veterans-affairs/caseflow/pull/7646
