### ISSUE TITLE
Assign Hearings | Gray box should end further to the left

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7564]
Reduce the gray space after the date selector and make sure that there is enough space between the date selector and the table.

**Comment by Chingujo** [comment]
I can upload a mock if needed

**Comment by MeredithStewart** [comment]
@Chingujo -- Add a mock for this to be worked.

**Comment by lomaxap** [comment]
@Chingujo is this still an issue?
