### ISSUE TITLE
Add link to daily docket in hearings section

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7567]
As a user, I want to be able to go the daily docket of a hearing that I already scheduled for that day. Especially, if I am searching an individual veteran who was already scheduled. 

### Acceptance criteria
- [ ] Verify that when there is no task and the veteran has already been scheduled, the task information and action section is blank
- [ ] Verify that in the hearing section in case detail for a hearing that is scheduled, there is a link called: View hearing date
- [ ] Verify that clicking this link takes you to the specific day in the daily docket

### Mocks
![screen shot 2018-10-26 at 1 35 58 pm](https://user-images.githubusercontent.com/23316107/47583152-8cdace00-d924-11e8-8918-08a7cd2a3219.png)

**Comment by MeredithStewart** [comment]
We want to re-visit.

**Comment by sharonwarner** [comment]
Dup of #9110
