### ISSUE TITLE
Change Assign Hearings to Schedule Veterans

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7568]
We want to use the schedule copy to better reflect how users communicate the need to schedule veterans task. This was also identified in usability. Below are all areas in which this needs to be changed. 

**Veteran should always be capitalized**

### Schedule Page
_Button title_
(we removed the instructional text for now so ignore it)
<img width="595" alt="screen shot 2018-10-26 at 1 03 16 pm" src="https://user-images.githubusercontent.com/23316107/47581529-9f9ed400-d91f-11e8-8b07-05e3e1140831.png">

### Schedule Veteran Table
_Title_
<img width="169" alt="title of page" src="https://user-images.githubusercontent.com/23316107/47582596-c7436b80-d922-11e8-9e69-0a54cf3c241d.png">

_Version 1_
<img width="166" alt="screen shot 2018-10-26 at 1 05 01 pm" src="https://user-images.githubusercontent.com/23316107/47582557-aaa73380-d922-11e8-8e25-2ef0214871f8.png">

_Version 2_
![screen shot 2018-10-26 at 1 29 03 pm](https://user-images.githubusercontent.com/23316107/47582697-20130400-d923-11e8-95b5-0178a004d873.png)

### Case Details
_Actions_
![screen shot 2018-10-26 at 1 30 05 pm](https://user-images.githubusercontent.com/23316107/47582759-4fc20c00-d923-11e8-8c14-474f62c0b032.png)

_Modal_
<img width="127" alt="screen shot 2018-10-26 at 1 07 13 pm" src="https://user-images.githubusercontent.com/23316107/47582784-5ea8be80-d923-11e8-8c18-a80e06d6dbf8.png">

**Comment by Chingujo** [comment]
@MeredithStewart 

If you find any other instances where this needs to be changed, please add it here

**Comment by MeredithStewart** [comment]
All instance of "veteran," needs to be capitalized, "Veteran." 

@Chingujo -- I like either options for "Schedule a Veteran" and "Veterans to schedule" -- I think I prefer "Veterans to schedule" since that title evokes that it's the list of Veterans (the common list for all hearing days).

**Comment by MeredithStewart** [comment]
@Chingujo -- I've gone through the flow and I think you've got them all. Except that the modal and the confirmation banner that pop up don't seem to be correct in Demo -- there might be more "schedule Veteran" language in those two items.
