### ISSUE TITLE
Decision Review | Special Issue | Add new category "Contaminated Water at Camp Lejeune"

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#757]
As a Caseworker, I would like to add a new _"Special Issue Category"_ checkbox "Contaminated Water at Camp Lejeune" on the `Decision Review` page so that it contains a category for Louisville.

# Acceptance Criteria
1. Verify that the following _"Special Issue Category"_ has been added a checkbox (Refer to Mock).
     - Contaminated Water at Camp LeJeune
1. Verify the "Contaminated Water at Camp Lejeune" _"Special Issue Category"_ has been added after "Hearing - including travel board & videoconference" checkbox.

# Mockup
**_View - Decision Review page with new category_**
![image](https://cloud.githubusercontent.com/assets/23063044/22401552/32ea5d02-e5a6-11e6-9666-cb5639a28357.png)

# Related Stories
End Product | Set Station Code to "Louisville RO" based on Special Issue Category #721

**Comment by nikitarockz** [comment]
prioritize - top

**Comment by astewarttistatech** [comment]
Dispatch was up and down today, was unable to verify.

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate:
1. Go to Dispatch as a caseworker and try to establish a claim
2. Verify on the Decision document page that "Contaminated Water at Camp Lejeune" is one of the Special Issue Categories

Screenshot:
<img width="1347" alt="screen shot 2017-02-07 at 8 36 32 am" src="https://cloud.githubusercontent.com/assets/23038505/22693570/ca31db32-ed11-11e6-8895-5139c5c9d700.png">
