### ISSUE TITLE
Investigate case list

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7579]
Jebby reported a case where there are only 3 cases associated with the Veteran ID in Caseflow ( showing in the Case list/search results) but may more in VACOLS. Can we investigate why Caseflow isn't showing all of the results?
![unnamed](https://user-images.githubusercontent.com/27704093/47594759-c6becb00-d94a-11e8-9080-3d5693809054.png)

**Comment by amprokop** [comment]
@laurjpeterson — i confirmed that the fix works in prod. previously Caseflow Case Search only returned 4 cases for the user, now we return 28.
