### ISSUE TITLE
App Canvas | Cancel | Change "Cancel" link label to "Cancel Certification"

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#758]
As Product Owner, I would like to change the "Cancel" link label to 'Cancel Certification" on the _Missing Documents_ and _Electronic Form 8_ pages so that it more accurately matches the action and eliminates confusion.

# Acceptance Criteria
1. Verify that on the _Missing Documents_ page, the "Cancel" link has be changed to "Cancel Certification" (Refer to Mock).
1. Verify that on the _Electronic Form 8_  page, the "Cancel" link has be changed to "Cancel Certification" (Refer to Mock).

# Mockup
**_View - Missing Documents - Before_**
![certification - missing documents - cancel](https://cloud.githubusercontent.com/assets/23063044/22375985/46af9d16-e47a-11e6-9ff4-753f003f2d48.PNG)

**_View - Missing Documents - After_**
![certification - missing documents - cancel certification](https://cloud.githubusercontent.com/assets/23063044/22375796/84a8b1f8-e479-11e6-9bd7-1beda6db6b7d.png)
**_View - Electronic Form 8 - Before_**
![form 8 - cancel](https://cloud.githubusercontent.com/assets/23063044/22378475/b638eef4-e483-11e6-9718-44487da25847.PNG)

**_View - Electronic Form 8 - After_**
![form 8 - cancel certification](https://cloud.githubusercontent.com/assets/23063044/22378482/bb801ed2-e483-11e6-9162-6289cc213c5b.PNG)

# Related Stories
n/a

**Comment by kierachell** [comment]
<img width="1251" alt="screen shot 2017-02-07 at 08 44 32" src="https://cloud.githubusercontent.com/assets/18075411/22693568/c96a6908-ed11-11e6-812a-887997961713.png">
<img width="1298" alt="screen shot 2017-02-07 at 08 44 57" src="https://cloud.githubusercontent.com/assets/18075411/22693569/c96f7dee-ed11-11e6-9c7b-afd02d82d80c.png">
👍
