### ISSUE TITLE
AMA Intake | Payee code is required when claimant not veteran

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7595]
When the Payee code is needed, it should also be required, because we'll need it to create the EP properly.

## Acceptance Criteria
- When intaking a compensation or pension claim review, if the claimant is not the veteran, the payee code should be required.

## Notes
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/7524

**Comment by leikkisa** [comment]
Adding inline validation for this field.

**Comment by leikkisa** [comment]
@shanear is the payee_code still technically required when the claimant is the Veteran (and defaulted to "00")?

**Comment by shanear** [comment]
![screen shot 2018-11-19 at 7 50 24 pm](https://user-images.githubusercontent.com/1596259/48744233-63b41180-ec34-11e8-8a97-afeeab9d52e8.png)

It seems to not throw an error when no claimant was selected. I'm thinking we should probably require both the claimant and the payee code in this case.

**Comment by leikkisa** [comment]
Ah, on the veteran part it looks like it's halfway, doesn't require it for the payee_code error, but will add one in the benefit_type (sorry we restructured and I missed that).

Claimant part makes sense!

**Comment by steve-gov** [comment]
Validated in all three AMA forms by selecting one or the other fields, or neither:

<img width="927" alt="screen shot 2018-12-05 at 4 39 18 pm" src="https://user-images.githubusercontent.com/25468689/49553528-f13a6700-f8ac-11e8-8d08-5ec6c2cc318e.png">

<img width="933" alt="screen shot 2018-12-05 at 4 40 32 pm" src="https://user-images.githubusercontent.com/25468689/49553529-f13a6700-f8ac-11e8-8cb2-a269d7593724.png">

<img width="892" alt="screen shot 2018-12-05 at 4 42 20 pm" src="https://user-images.githubusercontent.com/25468689/49553530-f13a6700-f8ac-11e8-828a-a46283356434.png">
