### ISSUE TITLE
Release 2 | Editing the schedule | Add hearing day

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7602]
As a hearing admin, I want to be able to add a hearing date to the schedule to accommodate for varying availability at Regional Offices, and add dates as needed to accommodate AOD Veterans.  

### Mocks 
* https://va-gov.invisionapp.com/share/G6P70ASQTR3

### Acceptance Criteria 
- [ ] Verify that there can select date for new hearing day  
- [ ] Verify that the user can select hearing type (Video or Central) 
- [ ] Verify that the user can select RO from a list of ROs that hold hearings 
- [ ] Verify that an VLJ can be added from of all VLJs 
- [ ] Verify that a hearing day can be created without selecting a VLJ
- [ ] Verify that a room number is automatically assigned based on available room numbers 
- [ ] Verify that a coordinator can select if they do not want a Board hearing room assigned 
- [ ] Verify that an error is shown if there are no hearing rooms available (and no hearing room hasn't been selected) 
- [ ] Verify that a coordinator can be added (free text)
- [ ] Verify that the hearing day can be created without selecting a coordinator 
- [ ] Verify that User can save text in the hearing day's notes field. 
- [ ] Verify that there is a confirmation when the hearing day is added 
- [ ] Verify that errors are shown when user does not select a required fields (date, type, RO if type is video). 
- [ ] Verify that error is shown when hearing day cannot be saved  
- [ ] Verify that only hearing admin can add hearing day to schedule (not hearing coordinators)

Users should only be able to add hearing days through Caseflow past January 1st for CO hearings and past April 1st for video hearings.

**Comment by Chingujo** [comment]
@MeredithStewart 

Thinking through do we ever need to add a range of dates? I put that in the AC from some UX but that was 2 months ago. Might be good to double check?

**Comment by MeredithStewart** [comment]
@Chingujo -- @laurenrussell and I will check with Justin and report back. If needed, I would think this would be post MVP functionality.

**Comment by MeredithStewart** [comment]
@laurenrussell -- Add more here around room numbers (save state should default to null if none available), and hearing coordinator data element that needs to be added.

**Comment by laurenrussell** [comment]
@MeredithStewart I thought we were putting this in the Change edit (7602), where users specify the room within the empty docket state? Is the assumption that they should be able to edit that new line after adding a date?

**Comment by laurenrussell** [comment]
https://va-gov.invisionapp.com/share/EPP1JSLWN48
