### ISSUE TITLE
Release 2 | Editing Schedule - Remove hearing days 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7604]
### User Story - Remove hearing day 
* As a Hearing Branch administrator, I want to be able to remove hearing days from the schedule when an error has been made in adding a new hearing day. 

Note: If Veterans have already been scheduled for that hearing day, Veterans will be postponed and a note will be made on the hearing day indicating the change in date, but the hearing day will not be removed.

### Mocks
* https://va-gov.invisionapp.com/share/QAP70DI563C

### Acceptance Criteria
 - [x] Verify that the user can select remove hearing day, only if no Veterans have been scheduled, canceled, or postponed in that hearing day.
- [x] Verify that that the user can see, "No Veterans are scheduled for this hearing day." 
- [x] Verify that there is a warning that pops up that warns the user for CO hearings, "Once the hearing day is removed, users will no longer be able to schedule Veterans for this **Central Office** hearing day on [**date**]." 
- [x] Verify that there is a warning that pops up that warns the user for video hearings, ""Once the hearing day is removed, users will no longer be able to schedule Veterans for this **Video** hearing day on [**date**] for [**RO**]   
- [x] Verify that there is confirmation when the day is removed
- [x] Verify that only hearing admin can add hearing day to schedule (not hearing coordinators)

This logic should only be available for Caseflow parent records.

**Comment by Chingujo** [comment]
@MeredithStewart 

I know we talked about this for removing a day from the schedule that we would want to prevent the deletion if there are already veterans scheduled for that day. In this case I propose the following solution: 

- We render an error say that all veterans must be moved to a different day before deleting. In this case they would have to postpone and move the veteran, or in the case of a removing, they would pick the cancel disposition. 

Are there any concerns to this?

**Comment by MeredithStewart** [comment]
@Chingujo -- Let me confirm with Justin this is desired behavior. I will also check on date ranges, but I think that's a most MVP thing if needed.

**Comment by MeredithStewart** [comment]
@laurenrussell and I think we may be able to roll out functionality that does not include editing the hearing day. A day on the schedule would remain (with postponed Veterans), and a new hearing day created. 

However -- the user story that we may want to design for: A Hearing Admin creates a hearing day on the wrong day and prior to scheduling any Veterans wants to change the hearing date, removing the incorrect day from the schedule.  We need to do more research with the Hearings Management Branch on this.

**Comment by MeredithStewart** [comment]
Updated user stories and acceptance criteria 11/15/18.

**Comment by MeredithStewart** [comment]
We are merging this ticket with the Edit hearing day ticket, since that functionality will exist in the Edit modal.
