### ISSUE TITLE
Release 2 | Epic 2 - Editing the schedule (All tickets in Current Sprint)

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7607]
As a Hearing Management Branch Admin, I need to be able to able to add a hearing day and edit a hearing day, and remove a hearing day that was created in error. 

As a Hearing Management Coordinator, I need to be able to edit attributes of the hearing day. 

### Issues
#7602 Add hearing day
https://va-gov.invisionapp.com/share/G6P70ASQTR3

#7605 Edit hearing day 
https://va-gov.invisionapp.com/share/HQP70E6DWPY

#7604 Remove hearing day 
https://va-gov.invisionapp.com/share/QAP70DI563C

#7946 Lock hearing day
https://va-gov.invisionapp.com/share/2PP8PZ4MBGV

**Comment by MeredithStewart** [comment]
Lock hearing day ticket was created and designed 11-21-18, based on stakeholders identifying during final stakeholder sign off.

**Comment by MeredithStewart** [comment]
All four tickets moved to current sprint 11-21-18.

**Comment by MeredithStewart** [comment]
All tickets done, tested with users, fixes recorded.
