### ISSUE TITLE
When docket number is missing from VACOLS, case details should still be clickable

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7610]
Don't know why appeals would be missing docket numbers! Here's what it looks like in prod: 

![image](https://user-images.githubusercontent.com/3781835/47739349-91b4c000-dc4b-11e8-9752-ca47df58cf45.png)

Go to https://appeals.cf.ds.va.gov/cases/122055

# AC
- if an appeal has no docket number, a link should say "No docket number"

**Comment by laurjpeterson** [comment]
I investigated the appeals listed https://appeals.cf.ds.va.gov/cases/122055 in VACOLS. 

Two of them validly don't have docket numbers, but I think we should still have a Case details link for them so users can see the issues associated with the appeal record. 

@lowellrex - does your change allow the user to navigate to Case details, still?

**Comment by lowellrex** [comment]
Yup! Instead of there being no link for cases that do not have docket numbers we will show a link with text that reads "Missing docket number".

**Comment by laurjpeterson** [comment]
Excellent thank you
