### ISSUE TITLE
Tweak copy when no representative is found

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7611]
<img width="658" alt="screen shot 2018-10-30 at 1 01 47 pm" src="https://user-images.githubusercontent.com/3781835/47739508-e6f0d180-dc4b-11e8-9ec8-45d084f60255.png">

**Comment by allyceh** [comment]
This is being handled here: https://github.com/department-of-veterans-affairs/caseflow/issues/7530#issuecomment-433496695

**Comment by laurjpeterson** [comment]
Closing, because this is a duplicate ticket to what Allyce commented above.
