### ISSUE TITLE
Judge to Judge assignment of RAMP tasks fails

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7612]
![image](https://user-images.githubusercontent.com/3781835/47740016-1d7b1c00-dc4d-11e8-86c3-7d570632b06e.png)

Since RAMP task assignment was built to create an AttorneyTask, it is a POST to `/tasks`. This correctly fails validation if the assigned to user is a judge. Right now, judges cannot push RAMP tasks to other judges. Unclear if anyone has tried this in production.

Possibilities for remediation:

# Quick fix
- on POST to `/tasks`, if a judge is the assigning user and the user being assigned, instead modify the existing JudgeTask (easy fix, adds tech debt)

# Thorough fix
- `AttorneyRepository.find_all_attorneys` currently (and perhaps unexpectedly) returns judges, acting judges, and attorneys. It queries for staff records where `sattyid` is not null, but judges and attorneys both have attorney ids. Return the type of user to the client. If the user is an attorney, POST to `/tasks` to create an AttorneyTask. If the user is a judge, PATCH `/tasks/:id` to change the assigned to user on the existing JudgeTask. If the user is an acting judge, POST to `/tasks` to create an AttorneyTask (later, we'll likely have to disambiguate assignment to acting judge acting as a judge vs acting judge acting as attorney)

**Comment by lowellrex** [comment]
I am a little confused about what the problem here is. As I understand the scenario above, a judge is trying to assign a case to an attorney for them to draft a decision but we are wrongly identifying that attorney as a judge. So is the problem that attorneys are being misidentified as judges?

**Comment by amprokop** [comment]
Nope.

The class and method names in the codebase implies that we’re only
returning attorneys, so that’s misleading.

But if you look at the Assign Tasks view, it says something like “select an
attorney or a judge” when you select “Other” in the dropdown- we intended
to support judge to judge assignment but it does not work.

**Comment by lowellrex** [comment]
So would judge X be asking judge Z to draft a decision in this example? Or is judge X just trying to change the ownership of this case to judge Z so judge Z can ask one of their attorneys to draft a decision?

**Comment by lowellrex** [comment]
Gotcha gotcha. I didn't know that we supported this behaviour.

I think the simplest thing to do is just to [change the copy](https://github.com/department-of-veterans-affairs/caseflow/blob/e2dfaa4735e2cfcc8ec9c380aec8e45a29a9b602/client/COPY.json#L166) for now and manually reassign judge tasks for now if a judge requests that. We should definitely eventually add the ability for judges to reassign cases to other judges (for them to assign later), but I'd love to know how frequently this is happening before we prioritize it very highly.

**Comment by amprokop** [comment]
We launched this view to a group of chief judges, who I believe mostly use
it to assign legacy cases to other judges. Last week, when I fixed a
duplicate DAS bug, the duplicates created were all judge -> judge
assignments. If we want to roll that back, you probably need to take it up
with Lauren, would probably require telling chief judges not to use
Caseflow.

But if you want to not fix RAMP judge -> judge assignment for now, thats
probably fine. as mentioned, I’m not sure if anyone has tried this in
production.

**Comment by lowellrex** [comment]
So, the work to do on this ticket is:
* [ ] Make judge to judge assignment work for AMA cases

**Comment by hschallhorn** [comment]
> Return the type of user to the client

We don't store the type of a user (attorney, judge, acting judge) in our User repository. The current way we fetch the type of a user is by making [a call to vacols](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/user.rb#L252). This seems like a pretty redundant call to make after just retrieving all the attorney users from vacols. 

SO. Do we want to
1. Add a vacols_role column in our user table.
2. Eat the performance hit
3. Go with the **Quick Fix**
4. Others??

**Comment by lowellrex** [comment]
We have a ticket to [use `JudgeTeam` membership to determine](https://github.com/department-of-veterans-affairs/caseflow/issues/8436) whether somebody is a judge or an attorney instead of VACOLS roles. Could we use a similar approach here?

**Comment by hschallh** [comment]
It looks like we're down to 22 VACOLS judges that do not have a judge team. Would there be any downside to automatically creating a team for each of these judges?

**Comment by hschallhorn** [comment]
It looks like we're down to 22 VACOLS judges that do not have a judge team. Would there be any downside to automatically creating a team for each of these judges?

**Comment by lowellrex** [comment]
> It looks like we're down to 22 VACOLS judges that do not have a judge team. Would there be any downside to automatically creating a team for each of these judges?

It's likely that not all of them are judges. See [this recent investigation](https://github.com/department-of-veterans-affairs/caseflow/issues/8436#issuecomment-466144809) into why there is a mismatch between the number of judges we identify with `JudgeTeam`s and judges as determined by the [`User.judge_in_vacols?` method](https://github.com/department-of-veterans-affairs/caseflow/blob/9887a895f97d976a8107bdc5d0fdb593b27b9693/app/models/user.rb#L50). Long story short: some folks we think are VACOLS judges are DVCs, senior counsel, or acting judges. We will likely create [judge team-like organizations](https://github.com/department-of-veterans-affairs/caseflow/issues/10029) for some of them but we need to be careful about creating judge teams for all of them because doing so may have impacts on other parts of the application (like [auto-case distribution](https://github.com/department-of-veterans-affairs/caseflow/blob/9887a895f97d976a8107bdc5d0fdb593b27b9693/app/models/distribution.rb#L127) for example).
