### ISSUE TITLE
AMA Edit | Edit appeal copy changes

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7623]
There should be some copy differences when editing the issues on an appeal. These will help the edit flow cater better to attorneys who will be using it.

## Acceptance Criteria
When editing any decision review:
- The call to action buttons on the bottom should read "Save" and "Cancel"

When editing the issues on a Board Appeal:
- The "Form being processed" row should be hidden
- "Receipt date on this form" should instead say "NOD receipt date"
- The copy on the "Remove Issue" modal should be updated to reflect copy below (see mocks below)

## Notes
this was created because of requests by @allyceh on this issue https://github.com/department-of-veterans-affairs/caseflow/issues/7594

## Copy
The issue you selected will be removed from the list of issues on appeal.

Are you sure that this issue is not listed on the veteran's NOD and that you want to remove it?

## Mocks
![image](https://user-images.githubusercontent.com/40216950/47751418-14e40f00-dc68-11e8-880b-55c8f7fd6625.png)
![image](https://user-images.githubusercontent.com/40216950/47751646-c1be8c00-dc68-11e8-8f88-d4b380a00921.png)

**Comment by allyceh** [comment]
A second set of eyes would be great before we're ready for dev. @laurjpeterson or @sneha-pai , can you take a look? Sneha, if you need more context, happy to walk you through things, too.

**Comment by laurjpeterson** [comment]
looks good to me!

**Comment by allyceh** [comment]
Great. I’d say we’re good to start dev.

**Comment by carolaponce** [comment]
@allyceh  and I reviewed her UI/copy changes today and the needs of her users. There are a few things we want to clarify:

1. Based on the user (clerk, attorney, etc) a different version of this edit issues screens would appear.  We will have variations of copy based on the user. Correct? @shanear 

2. Issues that are not valid or duplicates will not show up in the case details page of Queue, correct?

3. Whenever there is an invalid issue, or any issue error, the Intake team (Ivy's team) is responsible for notifying the Veteran.  Does anybody know this part of the process? If not I can check with Ivy.

**Next steps:**

- Clarify questions above.
- I will review our error messages and send @allyceh  feedback.

**Comment by carolaponce** [comment]
My comments in #7594

**Comment by carolaponce** [comment]
@allyceh for our review today:
![issues-sumary-exploration error copy 2](https://user-images.githubusercontent.com/11700545/48430620-b88bef80-e73d-11e8-9e94-5e50a88ffcf0.png)
![issues-sumary-exploration error](https://user-images.githubusercontent.com/11700545/48430621-b88bef80-e73d-11e8-8cb2-b0eef2717073.png)

**Comment by leikkisa** [comment]
@carolaponce From the ticket description, it doesn't look like I'm supposed to work on the ineligibility message, but just wanted to check since there are mocks for it.

**Comment by steve-gov** [comment]
Bullet 1 validated: 

<img width="938" alt="screen shot 2019-01-03 at 3 46 39 pm" src="https://user-images.githubusercontent.com/25468689/50667893-75e1d900-0f70-11e9-8f31-76915d517687.png">

**Comment by steve-gov** [comment]
Bullets 2-4 validated:

<img width="980" alt="screen shot 2019-01-03 at 4 09 24 pm" src="https://user-images.githubusercontent.com/25468689/50668119-fbb25400-0f71-11e9-84f7-2641a6802330.png">

**Comment by carolaponce** [comment]
@leikkisa  sorry for the late response _ my settings were off and I was not getting the messages.  These are not new designs - we were using this ticket to review styling modifications to the alerts but have not changed that style in development.  I will review with @allyceh and write a new ticket if necessary.
