### ISSUE TITLE
Prevent creating duplicate Tasks on backend

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7631]
Some tasks have a uniqueness constraint that is not represented in the database and, as a result, we can create multiple tasks when really we should only create a single task. This ticket exists to prevent the creation of duplicate tasks on the backend (either in controllers or models, whichever makes most sense).

An example of a "somewhat unique" task is the BvaDispatchTask (part of a solution introduced in #7603) where only one BvaDispatchTask should be created for each appeal (maybe this isn't true for remanded appeals if they share the same appeal ID).

Part of the work on this ticket includes collecting the list of tasks that are "somewhat unique" and describing in what ways they are unique. 
* BvaDispatchTask (only one org task per appeal)
* QualityReviewTask (only one org task per appeal)
* JudgeTask (only one active task per appeal)
* AttorneyTask (only one active task per appeal)

**Comment by mdbenjam** [comment]
I very much agree with this. In fact some of this can be built into a validate method of GenericTask. In general we can have a validation that says we cannot create a new child task if this current task is on hold or complete. There would still be a narrow window for a race condition but it feels pretty small. Then in some cases we can override this i.e. when we want multiple admin actions.
