### ISSUE TITLE
[BUG] Able to complete/reassign a QR task that is already completed

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7632]
Steps to Repro:
1. Dispatch an AMA case using any judge 
2. Go to http://localhost:3000/organizations/quality-review
3. Go to actions, assign to a QR user 
4. Go to actions, mark task as complete 
5. Go back to actions, you can assign a completed task to a QR user again
6. Go back to actions, you can complete a completed task again
7. Result is a bunch of bad data

![image](https://user-images.githubusercontent.com/3811786/47793647-28898700-dcf5-11e8-9c14-b946c71704e0.png)

**Comment by laurjpeterson** [comment]
@aroltsch to check if this is still happening

**Comment by hschallhorn** [comment]
Tested. No longer happens. Closing.
