### ISSUE TITLE
Rollout admin action functionality to more co-located folks + attorneys

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7640]
Current status:
- 2 co-located folks can view attorney admin actions in their queue
- 9 attorneys can assign legacy admin actions
- Any attorney can assign AMA admin actions

Next step for rollout:
- Any attorney can assign legacy admin actions to co-located

Dependencies:
- [x] Meet with Kim Osborne. _Scheduled for 9am 11/7_ - LP
- [x] Notify the union - ask if there are any issues - LP
- [x] Refresher training for all admin folks next week (of 11/5). _Scheduled for 11/8 1pm_ - LP
- [x] Verify round robin assignment - change how we do it on our end in Caseflow? - LP
       - Changing co-located to a team makes this easier, so we should probably do it
- [x] Rollout Caseflow to all co-located admin folks
- [ ] Rollout Caseflow admin action functionality to all attorneys

Not a dependency, but might need to do it anyway:
- [x] Create co-located team/org queue - https://github.com/department-of-veterans-affairs/caseflow/issues/7535

Decisions we need to make:
- NO - Prioritize multiple admin action functionality in co-located queue (not generic)?
        - Note: backend code already supports this for generic queues
- DELAY - Prioritize changing co-located for generic queue because of all the questions and feature requests we could get (e.g. multiple admin actions)?
- YES - Prioritize co-located to write notes when sending back to the attorney (instead of just the modal)?
        - Note: this would be a generic thing
- NO - use Case timeline - Prioritize attorneys being able to see most recent task in Case details/Case snapshot?
- DELAY - Decide whether to roll admin action functionality out to judges as well?

**Comment by marvokdolor-gov** [comment]
A couple of questions/ideas @laurjpeterson :
- We have our monthly touch base with Osborne on 11/14 at 3pm as a back-up opportunity to talk to her if we're not able to get on the calendar before that.
- On that note, should we talk to Jennifer Jessup and Rolandus, ahead of Osborne, or is that just over-complicating things?
- Either way happy to help get whatever we decide scheduled, so assigning myself here.

**Comment by laurjpeterson** [comment]
Met with Kim, Rolandus, Jennifer Jessup, Jack Kenner, Martina Mills on  11/7:
- We will rollout Caseflow to all VLJ support staff no earlier than Tuesday, November 13th. Their training will occur tomorrow.
- We'd like to rollout to 100 attorneys, then all attorneys two weeks later. This allows the new VLJ support folks to ease into using Caseflow for admin actions.

**Comment by marvokdolor-gov** [comment]
@laurjpeterson how will we decide which 100 attorneys? Will we need Osborne (or Jebby or JJessup) to tell us which VLJ's attorneys should get the functionality?

**Comment by laurjpeterson** [comment]
Good q. I figure we should suggest 2 chief groups, and then ask Kim to respond. Might be easy to choose the 2 chiefs in charge, Claudia Trueba and Cynthia Bruce. Or just one. Each chief has 8 judges, ~9 attorneys per judge. ~72 attorneys total.

@lowellrex - would you be open to 2 chief groups, bringing us to ~150 attorneys, instead of 100 attorneys?

**Comment by lowellrex** [comment]
I think either one or two chief groups would work. I'm fine with either.
