### ISSUE TITLE
Unbold "no cases" text in queue view

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7643]
When looking at an empty queue view (like the one below), we should keep the body copy unbolded, and only bold the hyperlink so it looks something like "You have no cases assigned to you. You can **search for cases**".

![image](https://user-images.githubusercontent.com/32683958/47796665-2f1afd00-dcfb-11e8-9f3f-913440f80cbe.png)

**Comment by joeyyang** [comment]
Closed in https://github.com/department-of-veterans-affairs/caseflow/pull/7651.
