### ISSUE TITLE
Intake Refactor | Create a snake_case to camelCase converter for data sent to the front end

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#7648]
Outcome of the naming discussion on 10/31. We're going to create a client side way to convert snake_case data from the back end into camelCase data on the client app.

## Acceptance Criteria
- Fix all instances of `.ui_hash` on the back end so that we consistently use snake_case.
- Create a function to convert snake_case data from the back-end to camelCase on the front end, to be used in the view or with props. Most likely with props so that it can live on the client-side.
- Convert the intake and intakeEdit client apps to use this function to convert rendered data to snake case.

**Comment by jimruggiero** [comment]
Closing because this issue will be addressed when alternate serializer tickets are completed in current or near-term sprint.
