### ISSUE TITLE
Intake Refactor | Store decision issues instead of rating issues in the DB

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7652]
Right now, in order to connect the rating issues that resulted from a request issue on a HLR or SC, we store that connection issue in the `rating_issues` table. After many fruitful discussions about the data model, we decided we should be storing this relationship in the same table that will eventually be used by appeals, which is `decision_issues`.

## Acceptance criteria
- When an EP for a supplemental claim or higher level review is cleared, decision issues are created for each rating issue made on the resulting rating. They should be connected in the DB to the request issues matching their associated contentions.
- If a rating issue is added and not connected to one of the request issue contentions, then it should still be created as a decision issue and connected directly to the decision review. (this shouldn't happen, but is technically possible in VBMS)
- The `rating_issues` table in DB should be deleted, and `RatingIssue` should return to an ephemeral class. 

## Technical Notes
This is a mural describing the relationships between the objects and models: https://app.mural.co/t/workqueue2001/m/workqueue2001/1540421981879/ba39075927b4039387697e094436e6a236fe7fa4

There is unknown time delay on when the rating is retrievable from when the EP status is changed to clear. We need to factor this time delay in when retrieving the rating and the decision issues.

There should not be any records in the `rating_issues` table in prod, as this functionality is not yet live, so no need to worry about migrating data.

**Comment by leikkisa** [comment]
Need to have a conversation with Queue team since they use the Decision Issues model and now we want to do it. Mark is going to kick off a conversation.

Suggestions for collaboration:
- Start reviewing each others' PRs (Queue <> Intake).
- Have an ambassador on each team to attend each others' meetings (sprint planning)?

**Comment by shanear** [comment]
```
=> #<RequestIssue id: 453, review_request_type: "HigherLevelReview", review_request_id: 310, rating_issue_reference_id: "114217", rating_issue_profile_date: "2018-07-30 11:56:05", contention_reference_id: 310595, description: "Service connection for Ptsd is granted with an eva...", issue_category: nil, decision_date: nil, disposition: "Denied", end_product_establishment_id: 233, removed_at: nil, rating_issue_associated_at: "2018-11-15 18:42:48", parent_request_issue_id: nil, notes: "requesting 50%", is_unidentified: nil, ineligible_due_to_id: nil, untimely_exemption: nil, untimely_exemption_notes: nil, ineligible_reason: nil, ramp_claim_id: nil, decision_sync_submitted_at: "2018-11-19 22:52:11", decision_sync_attempted_at: "2018-11-20 01:54:08", decision_sync_processed_at: "2018-11-20 01:54:15", decision_sync_error: nil>
irb(main):023:0> HigherLevelReview.where(veteran_file_number: "123458318").first.request_issues[3].decision_issues
[2018-11-20 12:53:05 -0500]   HigherLevelReview Load (1.0ms)  SELECT  "higher_level_reviews".* FROM "higher_level_reviews" WHERE "higher_level_reviews"."veteran_file_number" = $1 ORDER BY "higher_level_reviews"."id" ASC LIMIT $2  [["veteran_file_number", "123458318"], ["LIMIT", 1]]
[2018-11-20 12:53:05 -0500]   RequestIssue Load (0.7ms)  SELECT "request_issues".* FROM "request_issues" WHERE "request_issues"."review_request_id" = $1 AND "request_issues"."review_request_type" = $2  [["review_request_id", 310], ["review_request_type", "HigherLevelReview"]]
[2018-11-20 12:53:05 -0500]   DecisionIssue Load (0.7ms)  SELECT  "decision_issues".* FROM "decision_issues" WHERE "decision_issues"."source_request_issue_id" = $1 LIMIT $2  [["source_request_issue_id", 453], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy [#<DecisionIssue id: 1, disposition: nil, disposition_date: nil, description: nil, source_request_issue_id: 453, promulgation_date: "2018-11-19 16:46:04", profile_date: "2018-11-16 16:40:19", participant_id: 600233673, rating_issue_reference_id: "120164", decision_text: "Evaluation of Ptsd, which is currently 30 percent ...">]>
```

beautiful 💯
