### ISSUE TITLE
Make queue table view description more generic

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7665]
Currently the descriptions for the different tabs in the queue table view are very specific to the co-located admin team. Since this view will be the basis of all generic queues that we roll out to all of the different teams (and individuals on those teams) going forward we need to make these more generic. If it is possible to retain the current text for the colocated queue table view then we should do that. However, since they already have some experience using this view I don't think it would be a terrible outcome if we had to change the text for them as well.

| Tab | Co-located text | Generic text |
| --- | --- | --- |
| New | These are new administrative actions that have been assigned to you | These are cases that require some action from you |
| Pending action | When a hold is complete, the case will appear here. Cases with new documents will also appear here | These are cases that have been assigned to some other team (or placed on hold) require some action from you again |
| On hold | When a hold is complete, the case will automatically return to the Pending action tab | These are cases that do not require immediate action from you |
| Completed | Cases with tasks that were marked complete in the last two weeks will appeal here | _No change_ |

@sneha-pai @allyceh @laurjpeterson @joeyyang What do y'all think of this approach?

## Acceptance criteria
* [ ] More generic descriptions are displayed for all generic queues

**Comment by joeyyang** [comment]
Hi everyone! Not 100% sure I'm getting the meaning correct, but I took a stab at reducing the UI copy down for scannability and comprehension:

| Tab | Co-located text | Generic text |
| --- | --- | --- |
| New | These are new administrative actions that have been assigned to you | New cases assigned to you |
| Pending action | When a hold is complete, the case will appear here. Cases with new documents will also appear here | Cases assigned back to you *or* Cases requiring action |
| On hold | When a hold is complete, the case will automatically return to the Pending action tab | Cases on hold (will return to Pending when hold is released) |
| Completed | Cases with tasks that were marked complete in the last two weeks will appear here | Cases completed (last two weeks) |

**Comment by laurjpeterson** [comment]
> These are cases that have been assigned to some other team (or placed on hold) require some action from you again
- Can you explain this a bit further? Why would something assigned to some other team require some action from the individual again and be in the pending action tab, instead of the New tab?

**Comment by joeyyang** [comment]
Hi everyone — threw together a PR here: https://github.com/department-of-veterans-affairs/caseflow/pull/7697. Let me know your thoughts on copy and I can change. Thanks!
