### ISSUE TITLE
Public version: Finding Source of Truth for VSO Addresses

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#7673]
## Update 02/20/2019
Our original hypothesis was that the address that OGC associates with VSOs would be the best source of truth. This is because OGC accredits VSOs. Exploration of the validity of this hypothesis is on hold until OGC updates their database to Salesforce ~ May 2019.

## Background
The Corporate Database/BGS currently only stores addresses for Power of Attorney holders who are Private Attorneys or Agents but **not** VSOs.
There is no system, that we know of, where VA stores VSO addresses.
The Board's work around for this is VACOLS and (_I think_) an Excel file the Interactive Decision Template (IDT) pulls from.
[Slack Thread](https://dsva.slack.com/archives/C6E41RE92/p1540301374000100)

## Hypotheses
**Initial Hypothesis**: Storing these address in CorpDB/BGS is the best path forward.
- Learnings documented below helped us understand that while CorpDB is capable of storing these many to many addresses, BGS is not capable of serving them up at this time.

**Next Hypothesis**: The Office of General Counsel (OGC) would be a good place to store these addresses since they are responsible for accrediting VSOs ~~Representatives~~. **Update 1/29/2019: learned that OGC accredits organizations not individuals.**
- OGC has a database called GCLAWS that initially appeared promising, however (as is common with most OGCs) they are reluctant to be the source of truth for any data the business will use day-to-day, in this case VSO ~~Representative~~ Addresses.

**Latest Hypothesis for comments/ discussion
- VSO address information is stored in VACOLS today and updated by BVA staff. 
    - This allows BVA to control access to this information as well as its accuracy.
- This may have to become Caseflow functionality in the future:
    - it involves being able to print out properly-formatted labels
    - [Allyce's comment below](https://github.com/department-of-veterans-affairs/caseflow/issues/7673#issuecomment-439977601) is a guide to understanding which users need this functionality and what the functionality is. (This exploration will be captured in a MURAL linked in the [private version](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1059#issuecomment-439951405) of this issue).

**Comment by mc-usds** [comment]
Notes from BGS meeting:
There is a business rule for no address being stored in corpDB for National/Regional/State POAs. They can have multiple locations and it was agreed that instead the address of the Regional Office in the Veteran's jurisdiction would be used for mailing correspondence. VSOs have an office or mailbox at the Regional Office accessible to the VSO representative.

**Comment by marvokdolor-gov** [comment]
### Notes from Melissa's conversation with BGS/VBMS (Troy and Geoffrey were also there)

- There's a hand-shake agreement between BGS and the business (we're not sure who exactly the "the business" is) that BGS that National, State, and Regional VSO addresses would not be stored in CorpDB because there are multiple addresses.
- CorpDB has indicated that they could store them. The database does **not** have any constraints on storing multiple addresses for one entity. (Melissa to share email details in private version of this issue.)
- The constraint (via the handshake agreement above) is at the service level i.e. BGS/VBMS, as far as we understand.
- Consensus is that the Regional Office address would be used.

- It would be a little more complicated than just a list of addresses.
- JoshQ was also a resource.

#### What folks are using now:
- Excel spreadsheet is used by the Board.
- Access database is used by OGC. They're planning to move to Salesforce. They have a UI currently and there *might* be an API. There are 2 consumers of OGC information: eBenefits and OGC website.
- Next step, talk to OGC about this after touching base with Holtz:
- [ ] Touch base with Holtz on this.
- [ ] Touch base with Allyce.
- [ ] Reach out to Lara.Eilhardt@va.gov

### Takeaways
- Melissa thinks the source of truth should **not** be Caseflow
- Both ChrisG and Melissa think that: OGC is the business source of truth so should be the data source of truth as well

**Comment by allyceh** [comment]
An exercise that could be helpful to make sure we're storing the right address data could be: 

1. Who uses VSO addresses in Caseflow? What do they use them for?
Example: 
_BVA dispatch team: mails copy of decision letter_
_Privacy/FOIA team: mails correspondence to the veteran's rep when a privacy or FOIA request comes to the Board_
_AOD team: mails copy of AOD grant/denial to the rep (??)_

2. What type of VSO address do they need? At which address do VSOs like to receive correspondence?
Example: 
_BVA dispatch team: the VSO location/person who reviews copies of the decision letter_
_Privacy/FOIA team: HQ?_
_AOD team: HQ?_

As you can see, there are a lot of ? marks. Doing this exercise could show us that VSOs like to receive mail at the same address. Or, it would show us if there are any variations.

**Comment by marvokdolor-gov** [comment]
This is very helpful framing Allyce. Thank you!

Sounds like I should schedule some time with each of these teams (or simply stop by their desks) to get answers to these questions, at least as a starting point. I'm guessing I should also ask them if they know who else might need VSO information, beyond the teams already on this list.

### Teams to talk to about VSO Addresses:

- [ ] BVA Dispatch
- [ ] Privacy
- [ ] AOD
- [ ] ?Hearings

**Comment by MeredithStewart** [comment]
Hearings Management Branch will take over scheduling all Veterans (legacy and AMA) beginning February 14, 2019. This includes sending the hearing notification letter to the Veteran/appellant and their representation. The creation of and sending these letter has currently been done by Regional Office staff. The Hearings Management Branch needs as much accuracy as possible in the addresses of the rep, so that the rep receives timely notification of the hearing. Otherwise, the likelihood of requests for reschedules is going to rise. Already this has been a trend where Veterans request to reschedule because their representative is unavailable. 

@marvokdolor-gov -- When you are ready to sit down with Justin Madigan in hearings, I can arrange and be there to talk through this issue.  Let me know if this week works.

**Comment by marvokdolor-gov** [comment]
### Notes from meeting with Justing Madigan and Meredith 11/28/2018
[WIP]

**Comment by marvokdolor-gov** [comment]
### Notes from call with Lara Eilhardt and Jonathan Taylor 11/29/2018

Goal: learn the status of Salesforce as the source of truth for VSO Addresses.

**Comment by MeredithStewart** [comment]
Notes from conversation with Justin Madigan: 
* VSO addresses in VACOLS, from the VACOLS 3 main menu. See VACOLS screen shot.  It’s called “VSO Reference File Update” 
* Today for CO HearingsFor co-located in the Building — They send them an email to say the schedule has been updated.  
* Different people have different sheets and different labels pre-populated in the R drive - VSO Labels at the Board.  He’d pull a label template and confirm the address is the same. The few times he uses it, it’s been the same. 
* Jed updates the VSO Reference File Update (VACOLS address); Option for State Service or Other. Note: When a user selects, “print label,” it changes who updated it, even though it has not been updated. 
* VMBS Letter Creator - just pulls in the Service Org, not the address. He would go back in. 
* IN VACOLS they can print the label for the private attorney — if he double clicks on the attorney, you  select “Print label” and it prints it out in the format the envelope.

**Comment by laurjpeterson** [comment]
@marvokdolor-gov - i'm curious about the first two comments on this thread, that the "Consensus is that the Regional Office address would be used."

do we know of any BVA branches (dispatch, hearings, etc.) using the RO offices as a way to contact National/Regional/State VSOs?

**Comment by marvokdolor-gov** [comment]
Going to have to punt on these:
@mc-usds any clarification on John Dell's cryptic communication here?
@MeredithStewart do I have it right that Hearings Branch sends information to "colocated" VSOs or is that he Mail Team sending information on behalf of the Hearings Branch?

**Comment by marvokdolor-gov** [comment]
### Quick pull-up meeting with Melissa C. Chris G. and Meredith
12/6/2018

**Plan**
BVA Staff will continue to use VACOLS for VSO Addresses in the near-term. 
In the medium-term a read-only replica of the VSO Address table could be created in Caseflow. This would include a name and email address for someone to touch base with for any needed updates.
- [ ] Marvo: Explore who this person will be. We think it should be one person responsible for updating VSO Addresses.
- [ ] Marvo: Continue to explore OGC's possible role here. Try to get a meeting scheduled between a technical person working on GCLAWS and Chris G.

**Rough summary of discussion**
I asked them both what their thoughts were on Caseflow creating a VSO Address data source, with an interface for Board staff to update these addresses. This would duplicate the current functionality they have in VACOLS.

**Comment by mc-usds** [comment]
Regarding John's explanation, the example he gave was the St. Petersburg RO where a VSO (don't remember which one) has an office there and their correspondence gets sent there. Also, he said in some cases a VSO will have a mailbox at the RO and a representative will go to pick up mail. I'm not sure if this setup is the exception or the rule.

**Comment by marvokdolor-gov** [comment]
### Update 12/17/2018

Reached out to Joseph Shelley mentioned [above](https://github.com/department-of-veterans-affairs/caseflow/issues/7673#issuecomment-442951922). I'll be chatting with him and his team 12/20 at 11:30am.

He shared the following documents about the work to connect GCLAWS to Salesforce:
- [CLIN2015AA AIM Business Requirements Document (Accredited Representative V1-2 11012018)w comments.docx](https://github.com/department-of-veterans-affairs/caseflow/files/2687827/CLIN2015AA.AIM.Business.Requirements.Document.Accredited.Representative.V1-2.11012018.w.comments.docx)
- [VA OSP ICAM Onboarding Accredited Representative Overview V1-1 08272018.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/2687828/VA.OSP.ICAM.Onboarding.Accredited.Representative.Overview.V1-1.08272018.pdf)

**Comment by marvokdolor-gov** [comment]
### Update 12/20/2018
Call with Joseph Shelley and team mentioned above, Jonathan Taylor (OGC), ChrisG, MelissaC, Marvo
Goal: Explore the possibility of Caseflow having access to accredited representative address information being stored in Salesforce.

**Comment by marvokdolor-gov** [comment]
## Update 01/117/2019

Call with GCMatters Team: Ken (kbeecher@acumensolutions.com); dsheehan@acumensolutions.com; (Melissa) mwaid@acumensolutions.com; hkalla@acumensolutions.com

**Goal**: Explore the possibility of Caseflow having access to accredited representative address information being stored in Salesforce.

**Key Takeaway:** This team has been working with OGC over the past 6-7 months. They won't get to the accreditation portion of this work until Aug/Sep 2019. So they won't be able to answer our question about getting access to Accredited Representative Addresses for a while. They did suggest reaching out to Alex re: APIs though. If I'm able to do that, will drop notes here.

**Next Steps:**

- [ ] Touch base with Alex Loehr (Deputy CTO) about his API team's work with Salesforce.
- [ ] Reach out to these folks in May to see where they are in the process of migrating from GCLAWS to GCMATTERS.

**Comment by laurjpeterson** [comment]
Older, related ticket about POA addresses: #2311
