### ISSUE TITLE
Case details corrections for VSO views

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7678]
I screenshared with American Legion and identified these issues with Case details:

1. **Power of Attorney**
   - VSO view: POA section of Case details says "We're unable to load this information. If the problem persists, please submit feedback through Caseflow."
   - My view: I searched in Caseflow prod and the correct VSO, American Legion, was showing.

2. **About the Veteran, About the Appellant**
   - VSO view: Blank information for `About the Veteran`, info filled for `About the Appellant`. 
   - My view: I had data for both `About the Veteran` as `About the Appellant`. Since the Veteran and the appellant were the same, the data was repeated.

3. **Case Snapshot** 
    - VSO view: Task information is blank
    - My view: Task information is blank 

4. **Edit AOD**
    - VSO view: Edit AOD link visible (unclear if clickable - I did not ask)
    - My view: Edit AOD link visible, clickable, likely submit-able

---

## To do now
- [x] Show POA information for VSOs
- [x] Show About the Veteran information for VSOs
- [ ] If Veteran is the same as the appellant, do not show appellant information
- [x] Remove Edit AOD link, especially if it is active

## To do later
- Show that there is an outstanding IHP task in Task information

**Comment by lowellrex** [comment]
Ticketed item 3 as #7681.

**Comment by laurjpeterson** [comment]
Creating another issue for: If Veteran is the same as the appellant, do not show appellant information
