### ISSUE TITLE
Hide link to edit AOD from people who cannot edit AOD

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7681]
Currently everybody can see the link to edit a case's type and set AOD status. We should limit who can see this link to only members of the AOD team because they are the only ones who should be able to change AOD status.

![image](https://user-images.githubusercontent.com/32683958/47875159-366e0380-ddec-11e8-8e20-0fa271482b15.png)

## Acceptance Criteria
* Limit the set of people who can see the edit AOD link to only AOD team

**Comment by mdbenjam** [comment]
I think we should move this edit button into the task dropdown for the AOD team and maybe judges. Until we get mail working for AOD, we might need to make it an action on the root task.

**Comment by lowellrex** [comment]
I prefer leaving the ability to edit AOD as a link for now (though I am absolutely up for moving it into the task actions dropdown at some point) for two reasons:
1. Keeping the "Edit" link proximate to the area of the thing we want to change seems most natural to me. That is, if I want to change whether a case is AOD or not, I expect to look at where I can see if a case is AOD or not and make the change there. Additionally, we expect to support inline editing of some attributes of a case at some point down the line so I think it is appropriate for us to start doing that with editing AOD.
2. Conceptually editing AOD is an action and not a task. Editing AOD is an action that could complete a "Edit AOD status" task that mail assigns to an AOD team member. Currently, the only things that we display in the task actions dropdown menu are actions that manipulate (create, close, place on hold) tasks.

**Comment by mdbenjam** [comment]
That's fair. In fact I agree with number in that it is an action. But since we're going to need to make a task type for the AOD team, it seems like a good action on that task is "update aod". This could also be an option for judges who are hearing a case. The advantage of this over an edit button is it limits who can edit it within the permission structure we already have. But fine to leave it as an edit button for now.

**Comment by lowellrex** [comment]
The existing permission structure is a huge advantage for sure. One upside keeping this edit functionality separate has is that we can start to see how this class of activity (editing attributes of a case) tends to be designed so we can start to see what the natural framework for this class of activity is in the near term.
