### ISSUE TITLE
Move active tasks from case snapshot into a lockup below universal case title

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7682]
_Lowell: The final version of case timeline (mocks in [this mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1531849576358/38b753bff1e25963a76d8ebecf9679d6445c39b3)), we will include the incomplete tasks above the completed tasks in a continuous linear view. In order to get there we need to be able to view multiple tasks at once. I think the mocks provide a good example of how this could look. I propose we move the task information and actions dropdown out of the case snapshot area with this ticket and move it into this lockup._

_An open question is what case snapshot looks like without the task information. Perhaps docket type and AOD/CAVC (and VLJ and attorney information) get moved into [the proposed universal case title](https://github.com/department-of-veterans-affairs/caseflow/issues/6963)? @sneha-pai what do you think of this approach?_ [Resolved by Universal Case title]

## Acceptance criteria
* [ ] Primary task is displayed in new lockup on case details page.

![image](https://user-images.githubusercontent.com/32683958/49831142-2806f600-fd61-11e8-9f3a-e710e4274de4.png)

## Non-goal
* Showing/hiding the task instructions when clicking the "View task instructions" link. This version will always display task instructions.
* "+ Add a new task" button will not be implemented as part of this ticket.

![image](https://user-images.githubusercontent.com/32683958/49831293-8502ac00-fd61-11e8-8d6e-bddd87fb6760.png)

Please see https://app.mural.co/t/workqueue2001/m/workqueue2001/1543851111020/bbd6df5b95ca9a9ad179cd991d40c9314f35c929 for more details about the active-task logic.

**Comment by sneha-pai** [comment]
@lowellrex I walked Joey through these lightly yesterday. What are your thoughts on this "bridging" of Current tasks + actions component?

### Single task assigned to this user ( with respective action)
![current tasks-single-task](https://user-images.githubusercontent.com/31224257/48568655-db4d0e00-e8cd-11e8-974f-ba7a7cbb2900.png)

### Two tasks assigned to this user ( with respective actions)
![current-task-multiple-tasks](https://user-images.githubusercontent.com/31224257/48568656-db4d0e00-e8cd-11e8-88b5-c16507cffbda.png)

### No task assigned to this user ( with no available task actions)- But a way to create a new root-task below.
![current-tasks-actions-stacked](https://user-images.githubusercontent.com/31224257/48568657-db4d0e00-e8cd-11e8-87cd-c8b76935aae5.png)

**Comment by lowellrex** [comment]
@sneha-pai I love it! That all looks great! I especially like the consideration for actions unrelated to existing tasks (add mail task), I was totally overlooking that scenario. Great catch!
