### ISSUE TITLE
SPIKE: Investigate VVA integration

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#769]
We need to connect to VVA and they've given us documentation on their API and the proper endpoints.

The outcome of this spike should be to have made a successful read request to a VVA document. We can do this either through a SOAP client, or by creating a `connect_vva` library.

**Comment by nikitarockz** [comment]
# Sprint Planning
Add link to the VVA issue which has the links.

**Comment by aroltsch** [comment]
I cannot establish TCP connection with the VVA Dev environment:
```Errno::ECONNREFUSED: Failed to open TCP connection to vbaphi5dopp.vba.va.gov:7002 (Connection refused - connect(2) for "vbaphi5dopp.vba.va.gov" port 7002)```

However, I can establish TCP connection with the VVA Test environment (username is incorrect because the VVA team only shared username/password for the Dev env and not the Test):
```Savon::SOAPFault: (ns1:InvalidSecurityToken) An invalid security token was provided (An error happened processing a Username Token "{0}")```

**Comment by aroltsch** [comment]
I am able to make a successful request to VVA using: https://vbaphid521ldb.vba.va.gov:7002/VABFI/services/vva

Request:

```
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://service.bfi.va.gov/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility- 1.0.xsd">
  <env:Header>  <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
    <wsse:UsernameToken>
      <wsse:Username>EXAMPLE</wsse:Username>
      <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">TEST</wsse:Password>
    </wsse:UsernameToken>
  </wsse:Security>
</env:Header>
  <env:Body>
    <tns:DocumentList>
      <tns:claimNbr>516517680</tns:claimNbr>
    </tns:DocumentList>
  </env:Body>
</env:Envelope>
```

Response:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetDocumentListResponse xmlns="http://service.bfi.va.gov/">
      <message>No records found</message>
      <size>0</size>
    </GetDocumentListResponse>
  </soap:Body>
</soap:Envelope>
```

Note: real username and password have been removed

**Comment by aroltsch** [comment]
We test with the following claim numbers in the Development environment:
·         987987987 – Currently, this has a total of 45 documents with 13 restricted documents and 32 non-restricted documents.
·         456456456 – Currently, this has a total of 27 documents with 20 restricted documents and 7 non-restricted documents.
·         123123123 – Currently, this has a total of 7179 documents with 160 restricted documents and 7019 non-restricted documents.
 
The getDocumentList() will return all documents for you, and you need to filter restricted documents for you application.  You can filter restricted documents base on values returned for the property rstrcdDcmntIn.  For restricted, rstrcdDcmntInd will have a value of “Y” (no quotes), and for non-restricted, rstrcdDcmntInd will have a value of “N” (no quotes) or null or empty string.

**Comment by ariperez-gov** [comment]
@nikitarockz , we are blocked on this only with ATO and Implementation plan.  Should discuss, I created a bare bones implementation file. 

https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/Implementation%20Plans/VVA_eFolder_Integration.md

FYI: @nicholasholtz
