### ISSUE TITLE
Support One Touch Hearings

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7691]
We have been asked to implement a checkbox, like Jed has done in DAS, to identify a One Touch Hearing. I think we have two options:

**Option 1:** 
- Replicate what Jed implemented in DAS and add a check box to Caseflow judge check out screen for legacy cases
- Show in Case details, hearing section, that the case is a One Touch Hearing

### VACOLS logic
- The field is DECASS.DE1TOUCH, it's a checkbox 'Y' if checked 'N' or null if not checked.
- https://github.com/department-of-veterans-affairs/dsva-vacols/issues/44

## AC
- Checkbox `One Touch Initiative` exists on the `Evaluate attorney screen` of Judge checkout 
- When clicked, field DECASS.DE1TOUCH, it's a checkbox 'Y' if checked 'N' or null if not checked

### About One Touch Hearings
> The Chairman has approved implementation of the “one-touch” hearing initiative, allowing you to provide responses to appeals immediately after a hearing — if there is a clear disposition. This includes, as examples, full grants (not just partial), but also remands and denials as a matter of law (i.e., Sabonis-type denials). The attachment provides step-by-step instructions. Consult your Chief Judge if you have questions or need assistance. The project’s committee members (Chief Judges Cynthia Bruce, Anthony Scire and me (Keith Allen)) also are available if needed. The hope is this program will provide greater efficiency in our conducting of hearings, also reduce our response time and resultantly make inroads into the hearing backlog. This initiative only pertains to legacy appeals.

#### Request that Jed implemented:
> Request: A checkbox in DAS that could be check by a judge when they are checking out a completed case. The checkbox would indicate that the case was adjudicated under the "One-Touch initiative." This will allow for the tracking of the dispositions of One-Touch appeals.

#### VACOLS logic
- The field is DECASS.DE1TOUCH, it's a checkbox 'Y' if checked 'N' or null if not checked.
- https://github.com/department-of-veterans-affairs/dsva-vacols/issues/44

#### SOP
![image](https://user-images.githubusercontent.com/27704093/38635782-6c9ebd58-3d94-11e8-8256-8438851e58f9.png)

## Previous ideas:
**Option 2:**
- In Hearing Prep, give judges the option to make it a One Touch Hearing case (for legacy). that case should show up in the Assign cases part of the judge's queue so they can assign it to an attorney to draft
- Show in Case details, hearing section, that the case is a One Touch Hearing

**Comment by laurjpeterson** [comment]
Since this is stored in a DECASS table, Option 2 outlined above is moot. The DECASS row is only created when the case is assigned to the attorney. We'll have to move forward with option 1.

**Comment by laurjpeterson** [comment]
@sneha-pai - do you think you could take a look at this this week and provide feedback on where this checkbox should go on the Evaluate attorney screen?

**Comment by mdbenjam** [comment]
@laurjpeterson do we need one touch hearings in AMA?

**Comment by laurjpeterson** [comment]
@mdbenjam - Nope!

**Comment by mdbenjam** [comment]
@laurjpeterson But we'll need to store it ourselves at some point right? When we deprecate DECASS?

**Comment by mdbenjam** [comment]
Unfortunately since this is a new field in VACOLS we'll need to update FACOLS.
