### ISSUE TITLE
Post Standup Discussion: How to coordinate shared DB schema

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7708]
We've had some troubles in the past with coordinating database schema design/changes between teams. For example: https://github.com/department-of-veterans-affairs/caseflow/issues/7625

Another example is the claimant-appeal relationship. Claimants really reflect the relationship between a person and an appeal, but the Queue team assumed that the claimant represented the person appealing.

How can we better prevent these situations from happening in the future?

**Comment by pkarman** [comment]
I think we need a Schema Change Committee that needs to sign off on each PR.

**Comment by pkarman** [comment]
Proposed template for PRs that affect db/schema.rb

* [ ] Column comments updated
* [ ] #appeals-metrics notified
* [ ] Reviewed by:
  * [ ] @pkarman 
  * [ ] @aroltsch 

(list of specific folks TBD)

**Comment by pkarman** [comment]
* PR template :yes:
* Danger alert on PR for schema changes
* Remove danger alert on VACOLS change
* create #appeals-schema channel, drop PR link and summary in channel

**Comment by pkarman** [comment]
we've got processes in place we are now following.
