### ISSUE TITLE
Return all tasks accessible to the current user

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7709]
Currently we return a subset of the tasks accessible to the current user as they use queue. When they load their queue we return the tasks assigned to that individual user (and optionally role). When they load an organizational queue we return tasks assigned to that organization. When they load the case details page we load all tasks associated with that appeal. When they modify a task (mark it as complete) we reload that task.

This hodgepodge of places where we pull in the tasks creates opportunities for us to have an incomplete or incorrect list of tasks on the frontend (for example, marking a task as complete only updates the state of a single task on the frontend when in reality that action could cause a cascade of tasks being marked as complete). In order to avoid situations where task state is inaccurate, whenever we request a single task from the backend we should return all of the tasks that the current user can access.

## Acceptance criteria
* Always return all tasks current user can access (organization and individual) whenever we make requests from the queue frontend

**Comment by lowellrex** [comment]
May be related to #8095.

**Comment by lowellrex** [comment]
May be related to #8095.

**Comment by laurjpeterson** [comment]
@lowellrex - is this one done?

**Comment by lowellrex** [comment]
Yup! I think there are still some bugs around this, but it should be captured by the work in #8095.
