### ISSUE TITLE
Hearing Prep/Schedule | Claimant vs Appellant vs Veteran

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7711]
In hearing prep and hearing schedule we have logic all over the place to display appellant if it exists, otherwise display veteran. There's a method `claimant` that already built this logic in. We should use that instead.

**Comment by oscarAtNava** [comment]
Just to confirm, this claimant method is for Legacy Appeals only. AMA Appeals seem to have a Claimant class association and the logic is pretty different. This ticket will focus only on the LegacyAppeals as that is what we are currently delivering but will have to revisit for AMA.

**Comment by oscarAtNava** [comment]
@sharonwarner Could you be more specific as to where you see all this logic for appellant? I did a global search on the app folder in caseflow and only found appellant and veteran info in the vacols_record definition and that is pulled from the database through CaseHearings. Thanks.

**Comment by sharonwarner** [comment]
It's mostly in the frontend code. Here are a few examples:

https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/hearings/DailyDocket.jsx#L140
https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/hearings/HearingWorksheet.jsx#L115
https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/hearingSchedule/components/AssignHearings.jsx#L120

I'm sure there are more!
