### ISSUE TITLE
Veteran name shows differently if legacy vs. AMA 

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7716]
When searching for a Veteran ID and the Veteran has legacy and AMA tasks, the name can show differently. 

Example:
- legacy cases show as: First MI Last
- AMA cases show as: First Last

## AC
- [ ] Legacy and AMA case both show First MI Last

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | ||||||
3 | |
5 | 
8 | 
```


### Why 1?
- Could be a one line change to  the veteran model

### Why 2?
- make a single place do it, update everywhere to use it!

### Why 3?
- Uncertainty
- Possibly a lot of places to check
