### ISSUE TITLE
Hearing Prep/Schedule | Upcoming slots

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7725]
We should move the upcoming slots logic from judge.rb/hearing_docket.rb to the HearingDayRepository.

**Comment by oscarAtNava** [comment]
@sharonwarner Just want to confirm, we are referring to the following methods:

- In judge.rb the get_dockets_slots method
- In hearing_docket.rb the slots method

Thanks
