### ISSUE TITLE
Decision Review | Update styling above and below the Decision document

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#773]
As Product Owner, I would like the styling on the `Decision Review` page updated so that it is consistent with the Caseflow style guide.

# Acceptance Criteria
1. Verify that the light grey background space between Decision Review title box and the Decision Document has been removed.
2. Verify that a dark grey bar has been added below the Decision Document, so that there is a rectangular frame of even width around the entire document.

## Mockup
**_View - Decision Review - Before_**
<img width="530" alt="screen shot 2017-01-30 at 7 54 14 am" src="https://cloud.githubusercontent.com/assets/4975959/22423872/cdb58d0e-e6c1-11e6-9c2f-0ec941bec373.png">

**_View - Decision Review - After_**
<img width="565" alt="screen shot 2017-01-30 at 7 54 54 am" src="https://cloud.githubusercontent.com/assets/4975959/22423879/d5f45464-e6c1-11e6-99e6-544bdf9d421b.png">

# Related Stories
n/a

**Comment by shanear** [comment]
@lakohl this is the same style for viewing a PDF in Caseflow Certification. Additionally, @shellicious will be adding yet another PDF view in Caseflow Certification. 

Maybe this is a chance to look at styling and guidance for viewing PDFs all over the app, and how to style them?

**Comment by lakohl** [comment]
@shanear good point. I will sync with the design team on this issue on Thursday.

**Comment by lakohl** [comment]
We will use the .pdf viewer styling currently in use in Certification and Dispatch, but should remove some of the unnecessary functionalities in the future.

Currently:
<img width="956" alt="screen shot 2017-02-09 at 8 33 43 pm" src="https://cloud.githubusercontent.com/assets/4975959/22810525/4d5daf4e-ef07-11e6-8eea-bad4278a5e84.png">

**Comment by nikitarockz** [comment]
@lakohl add a mock.

**Comment by lakohl** [comment]
Closing in favor of new PDF viewer
