### ISSUE TITLE
Handle merged file numbers during BGS sync

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#7734]
Shane discovered something while investigating Intake errors in Sentry: in cases where two file numbers exist for the same veteran, they can be merged and one of the file numbers deleted.

This means that occasionally, Caseflow references to a veteran's file number become orphaned. Intake typically encounters this when syncing with BGS. See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2880 for an example. [Slack thread](https://dsva.slack.com/archives/CCB97HZJL/p1541435639012000).

As `participant_id` is an alternative veteran identifier, we can use that to look up the veteran's updated file number. We can do this as a part of handling the resulting error when no records are found in the BGS call during sync.

We can get the Veteran's ssn from the participant_id, and then the new file number with the following calls:
find_person_by_ptcpnt_id (in BGS)
fetch_file_number_by_ssn

We could update the file number, or choose to sync the end product using BGS's find_claim_detail_by_id (which shows multiple steps in the claim's history).

Please update all data for the veteran to reflect the new file number.

## Acceptance Criteria
* When `EndProductEstablishment#sync!` is called and no EPs are returned (symptomatic of merged file number), we should handle this error by using the veteran's `participant_id` to look up the correct file number and use that instead.
* The veteran's data is updated to reflect the new file number (and SSN if appropriate), throughout the Caseflow database

related: https://github.com/department-of-veterans-affairs/caseflow/issues/12166
related: https://github.com/department-of-veterans-affairs/ruby-bgs/pull/86

**Comment by leikkisa** [comment]
@msj0nes I'm going to keep this ticket open for now, especially since there's a clear idea of what to do. I haven't seen this issue come up lately, but I could see it coming up again in the future.
