### ISSUE TITLE
Investigation: break reliance on veteran file number as an immutable veteran identifier

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#7736]
in https://github.com/department-of-veterans-affairs/caseflow/issues/7734 we handle the known failure mode of a merged veteran file being deleted. Since Intake uses veteran file numbers in other tables, we need to determine how other Intake features are affected by file number references being orphaned, then figure out any system design changes necessary to account for mutable file numbers.

This issue should just be scoped to an investigation - implementation or further action items should be written into followup issues.

## Technical Notes
Tables that contain file number references are below:
* appeals
* documents
* end_product_establishments
* form8s
* higher_level_reviews
* supplemental_claims
* intakes
* ramp_elections
* ramp_refilings
* veterans

We can use `participant_id` from the `veterans` table to look up updated file numbers in BGS (and as a replacement immutable identifier for veterans in general)

More context in this Slack thread: https://dsva.slack.com/archives/C2ZAMLK88/p1541458173089000

## Acceptance Criteria
* An audit is done of Intake code to assess failure modes of orphaned file number references in the Caseflow db
* Action items are produced to account for these new failure modes
* A plan is established for removing any Intake reliance on file number as an immutable identifier

**Comment by bastosmichael** [comment]
You guys should consider using MVI in somewhat the same way the va.gov team uses on vets-api https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/mvi

**Comment by pkarman** [comment]
Example to find Veteran records with same participant_id and different file_number:
```
Veteran.select(:participant_id).group(:participant_id).having("count(*) > 1").limit(5).size
```
(just returns first 5)

**Comment by msj0nes** [comment]
Closing this investigation ticket.
