### ISSUE TITLE
Styleguide page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#774]
As a designer, I want to be able to see the the common components available to developers. I should be able to alter these styles and impact every usage of these

As a developer, I want to be able to see the proper React components and/or html/css required to create common UI components as they are designed.

## Acceptance Criteria
- When a system admin navigates to `/admin/styleguide` they should see a page with the heading "Styleguide"
- There should be a brief description of the purpose of the styleguide here. See @lakohl or @shanear for the exact copy.
- The first component documented should be the modal. There should be an example button that opens an example modal. There should also be a code snippet of how to make the associated modal.

## Mocks
@Chingujo and @KHarshawat will provide guidance on the styling of this page.

**Comment by mmlumba** [comment]
@Chingujo @KHarshawat-gov I'm ready to tackle creating the layout of the style guide. Let's sync sometime on what the style guide should look like.

**Comment by Chingujo** [comment]
@KHarshawat @mmlumba 

Sent a meeting invite for tomorrow (February 7 2016) at 10:00 am to discuss layout and other related issues.

**Comment by mmlumba** [comment]
Styleguide Mockup:
![caseflow commons example](https://cloud.githubusercontent.com/assets/4773320/22665180/c7e56988-ec81-11e6-991d-d670a27a2e96.png)

**Comment by mmlumba** [comment]
@KHarshawat @shanear Were you thinking this would be one long page controlled with anchors, or have everything split up into pages like standards.usa.gov?

**Comment by lakohl** [comment]
I would put Modals on one page and messages on another, each accessible from the left nav.

**Comment by shanear** [comment]
I'm thinking it's easiest to keep it all on one page, but I'm cool with whatever

**Comment by KHarshawat-gov** [comment]
I'm also in favor of keeping it on one page for now. If it gets too complex we can always break it out on pages later. Also based on past experience it's easier for developers to navigate a single page.

**Comment by kierachell** [comment]
Bookmarked for QA reference;
I'll let @KHarshawat and @Chingujo validate this

**Comment by kierachell** [comment]
`x` button on the modal don't work!
![screenshot_2017-02-15_21-01-50](https://cloud.githubusercontent.com/assets/18075411/23019308/ae76e996-f40f-11e6-8df2-31fb628e872d.png)

**Comment by mmlumba** [comment]
Validated by @KHarshawat-gov and sprint demo'd. Closing this ticket, and all ongoing web work for the styleguide will be tracked here: https://github.com/department-of-veterans-affairs/caseflow/issues/909

**Comment by lakohl** [comment]
@mmlumba noticed 2 little things in Sprint Demo... 
1) Now that we are using 'Close' instead of 'Go Back' in modals, I think we can get rid of the back arrows.
1) The red button text style would be 'Proceed with action' not 'Proceed with Action'.

**Comment by astewarttistatech** [comment]
So since caseflow commons isn't matching the mocks, I'm pushing this back.

**Comment by KHarshawat-gov** [comment]
@mmlumba concur with @lakohl on both of the above

**Comment by mmlumba** [comment]
@lakohl : You can view the change in demo. Go to the following and select "Launch Modal": http://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide

**Comment by lakohl** [comment]
@mmlumba I took a look at the modal in demo. Looks great!

**Comment by lakohl** [comment]
I believe in that in the Caseflow  apps if you click in the grey area outside the modal the modal closes. We should have the style guide work this way too.
