### ISSUE TITLE
Prepare application and test data for Preprod test

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#775]
We will need to set up the appropriate smoke tests and test data for the preprod smoke tests next week.

**Comment by askldjd** [comment]
Is this related to https://github.com/department-of-veterans-affairs/appeals-deployment/issues/391

**Comment by shanear** [comment]
yes, working on getting the data prepared with Jennifer Powell from VBMS. I think we have some file numbers and logins to use in the meantime

**Comment by kierachell** [comment]
Next steps:
- cross-check our VACOLS data with Test Cases: which order to use
- manually go through all the IDs/Cases: update VBMS as needed
- reset VACOLS data
- party
