### ISSUE TITLE
Create AMVETS organization

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7750]
AMVETS is an IHP-writing VSO. They have some RAMP appeals to write IHPs for, and 1 user already has the required CSEM access to Caseflow. We need to provide them with a unique link to see their RAMP appeals.

## AC
- Create AMVETS as an organization in the database

**Comment by lowellrex** [comment]
We already have a VSO organization for AMVETS (path: "/organizations/amvets") and it looks like they have 2 appeals associated with them. Unless they are having trouble accessing caseflow, they should be able to see their queue.
