### ISSUE TITLE
Intake | BGSyncError

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#7753]
Steady stream of these production errors in the last 72 hours.

```
EndProductEstablishment::BGSSyncError

PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
CONTEXT:  while updating tuple (1062,54) in relation "end_product_establishments"
: UPDATE "end_product_establishments" SET "last_synced_at" = $1 WHERE "end_product_establishments"."id" = $2
```

Likely due to the fact that all the upstream syncing is now taking longer than the default PG transaction length.

**Comment by pkarman** [comment]
may be mitigated by #7652

**Comment by pkarman** [comment]
this is still happening as of 11/13 so #7652 did not help (enough).

**Comment by kencheeto** [comment]
Blocked because we are waiting on BGS to replicate these issues. cc @mc-usds for visibility

**Comment by kencheeto** [comment]
Action item while we wait for BGS: investigate other ways to process these intakes that are faster

**Comment by pkarman** [comment]
PR #8086 should work around the slow call, and VBMS 1.6 has some improvements that we should evaluate for performance time.

**Comment by pkarman** [comment]
putting this in validation so we can monitor alerts channel and see if it gets quieter.

**Comment by steve-gov** [comment]
Dec 4: 26 `BGSyncError` alerts
Dec 10: 3 `BGSyncError` alerts

How long do you think we should monitor before passing validation?

**Comment by pkarman** [comment]
The particular error that spawned this ticket has been worked around, but the overall slow issue remains. Let's close this one. I opened #8227 to track the larger issue.
