### ISSUE TITLE
[Tech Spec] Allow attorneys and judges to edit decision issues and set dispositions

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7761]
Currently, attorneys and judges can set dispositions on request issues but have no way of editing these issues. We need to introduce decision issues to allow for that. 

### Allowed Scenarios:
1. one request issue to one decision issue
2. one request issue to many decision issues
3. one decision issue to many request issue
4. many decision issues to many request issues (maybe?)

### Assumptions:
1. There will always be at least one decision issue for each decided request issue
1. There will be no disposition on the request issue. Disposition on the request issue is a function of the decision issues.
1. Remand reasons will live within a decision issue
1. EP will be created based off the decision issues
1. Each request issue must have a decision 

### Parameter example for scenario 1:
```
"issues": [{
  "decision_issues": [ 
       { "disposition": "allowed", "description": "something", "request_issue_ids": ["1"] }
   ]
}]
```

### Parameter example for scenario 2:
```
"issues": [{
  "decision_issues": [ 
       { "disposition": "allowed", "description": "something", "request_issue_ids": ["1"] },
       { "disposition": "remanded", "description": "something", "remand_reasons": [ "code": "incorrect_notice_sent", "post_aoj": "true"  ], "request_issue_ids": ["1"] }
   ]
}]
```

### Parameter example for scenario 3:
```
"added_decision_issues": [{
  "decision_issues": [ 
       { "disposition": "allowed", "description": "something",  "request_issue_ids": ["1", "2"] }
   ]
}]
```

### Parameter example for scenario 4:
```
"added_decision_issues": [{
  "decision_issues": [ 
       { "disposition": "allowed", "description": "something",  "request_issue_ids": ["1", "2"] },
       { "disposition": "remanded", "description": "something",  "request_issue_ids": ["1", "2"],
       "remand_reasons": [ "code": "incorrect_notice_sent", "post_aoj": "true"  ] }
   ]
}]
```

### Tech notes:
1. ~Add BE validation to validate request issue disposition based on the combination of dispositions for the decision_issues~
2. Modify case_reviews_controller to accept new parameter format and hide it behind a feature flag in order not to break existing code in production

### Additional Columns and migrations:

1. Implement many-to-many relationship for decision issues and request issues: https://github.com/department-of-veterans-affairs/caseflow/issues/7884
1. Implement a migration to create a `decision_issue` for each `request_issue` that is currently in production and that has a disposition 
1. Currently, `remand_reasons` table references `request_issues`. If we start using `decision_issues`, we need to migrate `remand_reasons` to reference `decision_issues` instead. 
1. Allow null `rating_issue_reference_id` in `decisions` - **done**

**Comment by shanear** [comment]
> Add benefit_type column to the decision_issues table (clarify this?)

Yeah, there are some additional questions here. Like, can there be a decision with a benefit type different from the request? For HLRs and SCs the benefit type is specified up front.

**Comment by shanear** [comment]
> Implement a migration to create a decision_issue for each request_issue that is currently in production

I would think a request issue would not have a decision issue until it's actually been decided, meaning there should not be a decision issue for all request issues

**Comment by shanear** [comment]
> Add notes column to the decision_issues table

I would prefer to add this when it becomes needed in the UI. I think this ticket should be about setting up required structure

**Comment by pkarman** [comment]
@shanear wrote:
> I would think a request issue would not have a decision issue until it's actually been decided, meaning there should not be a decision issue for all request issues

is it fair to provision a decision issue to hold the disposition ahead of time though? I.e. it would be a placeholder for a decision that will happen eventually. The `contention_reference_id` is what `RatingIssue` will look it up by and associate it later.

**Comment by shanear** [comment]
> is it fair to provision a decision issue to hold the disposition ahead of time though? I.e. it would be a placeholder for a decision that will happen eventually. The contention_reference_id is what RatingIssue will look it up by and associate it later.

If this helps, I'm cool with this. I just don't think we should create the `decision_issue` record early without a reason to do so. I don't think holding the disposition that good of a reason, since it wouldn't have a disposition before a decision is made.
