### ISSUE TITLE
Prevent multiple users from working the same task

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7766]
In Caseflow today, it's possible that two different users could enter Case details and initiate an action from the dropdown. We need a way to prevent this because Hearing Branch Coordinators should not work the same admin action task. This functionality could be transferrable to other teams at BVA, too. 

We’re worried about the case where:
- person A enters case details
- person B enters case details
- person A takes an action
- person B takes an action

## Solution ideas

1. Caseflow can implement one or two checks so that we throw an error in this case.
    a. Check if the task is already complete - this means we cannot take an action
    b. Check if the task is on hold - this means the only action we can take is reassignment.
    - Note: If person A enters and takes an action, then when person B enters they won’t have tasks available to them. It’s only when they both enter it first and then each take an action that we run into a problem. I don’t see how we can really address that without the use of websockets or something. Which I think is over-engineering the problem.

2. My two cents: in a previous workflow implementation I worked on we had a Take action on organizational tasks for a specific user to express they were working on an item.

3. Implement individual queues - require individuals to assign themselves the task from the team queue
    - Note: For Hearing Schedule's admin actions, we aren't envisioning individual queues initially, so we'd need functionality to prevent multiple folks from working the same action.

**Comment by MeredithStewart** [comment]
@laurjpeterson -- I think we may have already implemented something for this. I think this ticket can be closed.
