### ISSUE TITLE
Edit page - removing and adding same issue

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#7772]
On the Edit page, if a user removes the issue, and then re-adds it, it is shown as ineligible because it is already in active review.  However, it's in active review from the same intake.

This should be treated more like it was removed by accident (e.g. never removed at all).

### Acceptance criteria:
- Removing and re-adding an eligible issue on the edit page remains eligible on the UI and in the backend
- An issue that is removed and re-added should not be included in the create_contentions call

**Comment by leikkisa** [comment]
Peter fixed the back-end ineligibility for this situation in https://github.com/department-of-veterans-affairs/caseflow/pull/7769.

The front end presentation still needs to be fixed, most likely in "title_of_active_review".

We also need to check that either both remove and create contention are being called, or neither of them are being called.

**Comment by pkarman** [comment]
> We also need to check that either both remove and create contention are being called, or neither of them are being called.

I think the behaviour we want is to remove/create because the CA may add comments.

**Comment by shanear** [comment]
![bug](https://user-images.githubusercontent.com/1596259/49035443-bc2e6600-f182-11e8-9ec4-a820ade08b04.gif)
Some strange behavior might have to do with this one. 

If an issue was valid at the time it was added, it should continue to be valid on the edit page.

**Comment by steve-gov** [comment]
Validated as working:

![screen](https://user-images.githubusercontent.com/25468689/49970857-7c38e400-fee1-11e8-8e45-d9f6421bea3a.gif)
