### ISSUE TITLE
Issue order in Case Details

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#7776]
@nicholasholtz and I observed an attorney who was changing issues on appeal yesterday using the functionality leveraged from the Intake team. When she added two additional VA decisions (issues) to the veteran's appeal, she was actually adding a 7th and 8th issue, but the issues showed up as issue 1 and 2 on Case Details. 

Is it possible for us to add new issues to the end of the issues list so that they reflect the order in which they are selected in the Intake flow? That was the attorney's preference.

**Comment by rkreyhsig** [comment]
We need to add created_at timestamps and order based on these per @shanear.
