### ISSUE TITLE
Change new documents icon implementation

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7777]
We currently have a feature where a new documents icon shows when new documents have been added to the eFolder since the last time the user clicked into Reader. This moves cases into the `Pending action` tab for co-located (which we will eventually remove). However, this icon also shows if the user hasn't yet clicked into Reader at all, so it's often always on. 

The goal of this feature is to catch when admin actions can be actioned on _before_ a case has finished its hold time.

When VLJ support management branch users have placed a case on hold because they have to wait for an answer/information/documents from the Veteran/appellant or their representative, they want to be notified that new documents have come into the eFolder, so they can check if those new documents are related to their admin action and they can complete it.

## AC
- For cases that are on hold only
- Retrieve document count from the date that the task status changes to `on-hold`. 
- If a new document is added to the eFolder since that time, show the New documents icon
- If a case had been put On hold, keep the case in the `On hold` tab, but show the New documents icon in the Tab as well as in the row where the case is. (instead of moving it to Pending Action)

**Comment by mdbenjam** [comment]
This should be fairly easy to do. Just looked at the code we currently use the current user to determine when the user last viewed the appeal. Instead we can just pass the in-progress status change date and use that. Should be pretty simple.

**Comment by hschallhorn** [comment]
Closed in #8908

**Comment by hschallhorn** [comment]
Closed in #8908
