### ISSUE TITLE
[Discussion] How to handle AMA appeal that comes back to the board

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7793]
The same AMA appeal can come back to the board if it was a remand, for example. Currently, we generate a task tree for an appeal. We create a root node and then the rest of the tasks inherit from the root node.

Intake creates a new root node for every time an appeal is intaked:  https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/appeal.rb#L182

When an appeal comes back to the board, we should create a new tree for the appeal. That means for validations that we might have in place (e.g, how many DispatchTasks an appeal can have) we should scope it to the root node or parent. 

Thoughts?

**Comment by mdbenjam** [comment]
Yes I agree with all of that. Scoping to the root node makes sense to me

**Comment by aroltsch** [comment]
I think we can close it. Moving forward we need to keep this in mind.
