### ISSUE TITLE
Case Details | User should not be able to edit hearing location/date

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7794]
- From the Case Details Assign Veterans modal, the user should not be able to edit the hearing date or hearing location.

**Comment by MeredithStewart** [comment]
@sharonwarner -- We also discussed today 11-13 the possibility of implementing the change hearing day as it was designed.

**Comment by sharonwarner** [comment]
Closing in favor of #7853
