### ISSUE TITLE
Start/Doc Comparison Page: Simplify instructions

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#78]
While not everyone read the instructions on how to resolve the errors immediately, those who did completely were able to take the correct steps to remedy the issues. 

Suggestions: 
- Either reduce the amount of content in the help content by eliminating the steps to open VBMS (the user usually has it open already), or 
- Consider hiding these instructions behind an action button right next to the error itself

**Comment by plusjeff** [comment]
@KHarshawat assigned for design content

**Comment by KHarshawat** [comment]
Content below. Also a mock using the new design but use it as a reference to see what the content should look like:

![01_errorpage](https://cloud.githubusercontent.com/assets/6335546/10895696/89b4879e-8183-11e5-9a62-b243ee73e454.png)

---


# Find missing documents
Caseflow could not find the documents with an **X** below, in the appellant’s eFolder. Try **looking for** the missing document in VBMS and **changing its date** to the date in the VACOLS column.  After changing the date, click the **Refresh Page** button below.

If you can’t find the document click the **This case cannot be certified** link below. If you’re having trouble, [click here for help]().

**Comment by plusjeff** [comment]
![image](https://cloud.githubusercontent.com/assets/950486/10914017/72dc7996-821e-11e5-9209-7737bf2ea249.png)

**Comment by plusjeff** [comment]
Awaiting review in #118
