### ISSUE TITLE
[Tech-Spec] Deprecating DAS

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7809]
# Deprecating DAS
Queue's DAS integration is a constant thorn in our side. Some of the problems it has caused are:
1) DAS tasks do not have unique ids
2) Our frontend code is needlessly complex, handling both Caseflow and Legacy (DAS) tasks
3) While our Task model allows multiple tasks to be assigned at once, DAS does not
4) We have had several bugs with our integration (Duplicate DECASS recrods, OMO attorney credit, etc.)

Deprecating DAS will make our code simpler, more maintainable, reduce bugs, and move us one step towards our long term goal of deprecating all of VACOLS.

# Steps to Deprecate
One of our hesitations with deprecating DAS is that we do not yet support all DAS flows in Caseflow. In fact we don't know what all the DAS flows are. We've been relying on our integration with DAS so that users could take actions in DAS if Caseflow did not support a particular user flow. Therefore deprecating the backwards compatibility comes with risk. To mitigate this risk, I believe the way forward consists of two phases:

## Prep-phase
There are three things we know we need before we try to deprecate DAS.

### OMO requests
We currently only allow OMO requests for legacy tasks. However, allowing them for Caseflow tasks should be relatively straightforward. We already record them in our `(attorney|judge)_case_reviews table`. The main change here is to use our tasks, while either still updating the location of the VACOLS record to be the OMO office, or to roll out a queue to the OMO team for them to monitor OMO requests.

### Reassignment to Attorneys
Currently Caseflow allows judges to assign cases to attorneys, and then lets attorneys assign cases back to judges. However, if the judge finds errors in the attorney's work, there is no way for the judge to assign the case back to the attorney.

This will be relatively easy to fix especially with Caseflow tasks. We simply need to add an `Assign back to attorney` action on `JudgeTasks`. This will create a new child `AttorneyTask` of the `JudgeTask` that the attorney can work again.

### Reporting
The main holdup in this transition seems to be reporting. Users of Caseflow need to know how many cases they're completing. These metrics are used by the board to determine employee productivity. Since this is such a high priority for the Board, we need to make this reporting work with Caseflow tasks. Of course we need to do this regardless of whether we deprecate DAS since AMA appeals also need metrics, and these appeals are only tracked with Caseflow tasks. With Looker we're already a good part of the way towards reporting. We simply need to create a handful of reports (Jed estimated 3-5 of the DAS reports are important).

## Change-Over Phase
Even after doing the tasks listed above in the prep-phase, a successful transition from Legacy tasks to Caseflow tasks will be gradual. There are a lot of unknown unknowns. We don't know if we're missing significant workflows for DAS users. An easy way to figure this out is to pilot using Caseflow tasks for legacy appeals for a handful of users and iterate with them as we find gaps in our implementation.

Luckily, Automatic Case Distribution (ACD) provides us an easy way to start a few users off in this pilot. By making two changes to ACD we can bypass DAS.
1) For users in the pilot, change the location of the appeal to "CASEFLOW" instead of the judge's location.
1) For users in the pilot, create a JudgeTask assigned to them.

There are a few other things we'll need to consider for this pilot.
1) Currently all JudgeTasks are sent to QR. We'll need to add logic here to send all AMA Appeals' to QR and some subset of LegacyAppeals with JudgeTasks to QR.
1) Some of the logic in the (Attorney/Judge)CaseReview models relies on whether a case is legacy. This might need some adjustment. (i.e. we don't want to change the case's location to BVA dispatch, we'll probably just want to create a dispatch task).

This step is also reversible. If the pilot is a disaster, we can turn it off, and revert to using DAS until we fix the problems uncovered.

# Summary
I believe we should tackle this problem soon. Our DAS integration is hurting our speed and credibility. Two of the three preparation tasks are needed anyway for AMA appeals (both assigning back to attorneys and reporting), so it seems like the extra lift is pretty minimal. I believe the advantage of making this conversion outweighs any upfront cost.

**Comment by laurjpeterson** [comment]
I agree wholeheartedly with the urgency. 

---
Adding @sneha-pai's [synthesis](https://docs.google.com/presentation/d/1y2qeJftWT1qMZ0D94VA1kOBFIBtisVh0FBS-9wY_sbQ/edit?usp=sharing) of why attorneys/judges are still using DAS from user research done in September 2018.

From that user feedback, I think we'd benefit from two things before deprecating DAS, for user satisfaction:
1. Looking into and if possible, improving Caseflow loading times
2. Allowing judges and attorneys to see if a case is part of a Specialty Case Team (https://github.com/department-of-veterans-affairs/caseflow/issues/5565)

Other pieces of feedback, like prior attorneys if the case was a remand, can be accessed in VACOLS. 
---
### OMO requests
- Some additional info: I learned that there is more judge/OMO employee charging back and forth that started in July. When judges assign cases to OMO, OMO may want to assign the case back to the judge, who would then send it back to OMO. We have to decide if we name these tasks, or ask users to write them in each time. 
- If we continued updating the VACOLS location to OMO, when OMO assigns the case back to the judge would we update the VACOLS location to the judge's location?
- Since OMO isn't required for AMA, I'm hesitant to prioritize a queue for them before February, especially because of the reporting requests and union notifications they'll require.

### Reassignment to Attorneys
- I think this is an extremely important reason for deprecating DAS sooner
- Does it make sense for the task to be the same? We'd likely want the two different tasks to be represented in Case timeline. For example:
    - Judge assigned case to attorney - task name?
    - Attorney drafted decision - Draft decision task
    - Attorney assigned case to judge - Sign decision task
    - Judge assigned revision to attorney - Revise decision task
- Should we abstract this to generic queue assignments - `Assign to person` instead of `Assign back to attorney`?
- During this prep time, do we have DAS records + the back and forth for reassignment in Caseflow tasks simultaneously?

### Reporting
- Would love @marvokdolor-gov's thoughts here. What are the risks of us using Looker for these reports and providing them to BVA stakeholders/users _before_ the data analysts create them themselves?

### Changeover Phase
- I like the idea to change the location to CASEFLOW. This sounds like a great plan.

**Comment by marvokdolor-gov** [comment]
Thanks Mark and LP.

The key risk is that the Board will continue to be overly dependent on us for reports that we don’t have the bandwidth to own. 

That said, I think there’s a path forward where we make a good faith effort to provide the most critical reports, in exchange for them giving us the space to focus on building crucial functionality in time for Feb. 

Unfortunately, I’ll miss the new version of the “Reporting” meeting tomorrow, W at 11am, where there’ll be more Board staff (a Chief and Jebby) present. Sunil has been leading this effort from the engineering perspective and I’ll vebsure to touch base with him.

**Comment by aroltsch** [comment]
> If we continued updating the VACOLS location to OMO, when OMO assigns the case back to the judge would we update the VACOLS location to the judge's location?
Unfortunately, if we don't have OMO queue in place, we have no way of OMO office marking Caseflow task as in-progress. The only thing they can do is to charge the appeal back to the judge in Vacols and Caseflow will have no way of tracking that.

**Comment by mdbenjam** [comment]
Hmmm @aroltsch makes a good point around needing an OMO queue. @laurjpeterson how difficult do you think this will be from a process perspective?

**Comment by laurjpeterson** [comment]
It'll be similar to our other queue rollouts. Note that OMO will _not_ have any AMA cases, only legacy. 

We'll have to do the following:
1. union notification 
1. user training and validation that our generic functionality will suffice
1. determine if Caseflow needs to provide productivity reporting, or if we can be backwards compatible with VACOLS locations for this so their VACOLS reports won't break. (we need to be able to show them who completed what tasks so their performance can be evaluated)

**Comment by mdbenjam** [comment]
Do you know anything about their workflow. Do they use VACOLS for anything besides getting what tasks they need to do?

**Comment by laurjpeterson** [comment]
Here's what we know about Outside Medical Opinion office:
- New processes for when the medical opinion comes back from the medical professional were introduced July 2018 - notes here: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/OMO_8.16.2018.md
- Processes researched late summer 2017 - https://app.mural.co/t/workqueue2001/m/workqueue2001/1504901191394/91b35b94865620ed91341045384d304c2bff2ed0

They definitely track their work using VACOLS locations, assign cases to individuals in the OMO office using VACOLS, and use VACOLS location reports to see their work. I would have to ask them if they also use VACOLS diaries.

**Comment by mdbenjam** [comment]
Gah so it looks like they use locations to communicate with VHA outside of the board? That makes it way more complex. That means we'd need a Queue for people at VHA. What about this.

Ask OMO users to use a Queue as well VACOLS for a little while. When we create an OMO request we put a task in their queue and move the case to location 20. When the OMO is complete they need to complete the OMO task in Caseflow and we'll move the location back to "CASEFLOW".

Or we could some how auto detect when they've moved the case back to the judge. Like a job that runs daily looking for OMO tasks. See when the move from location 20, back to a judge or "CASEFLOW", then we can close the OMO task.

**Comment by laurjpeterson** [comment]
- Eventually, VHA will have a queue for intaking and adjusting dispatched AMA reviews that we could potentially use for legacy cases too (if we want to go down that route).
- I like your first suggestion, Queue + VACOLS. Most admin teams are working in both right now anyway. I can plan to meet with OMO team to suggest this next week or the following and see if it could work with their processes.

**Comment by laurjpeterson** [comment]
closing in favor of this more recent tickt - https://github.com/department-of-veterans-affairs/caseflow/issues/9588
