### ISSUE TITLE
Intake | Wording changes

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7810]
Cleveland from AMO looked over some of the screens I shared for the edge cases and submitted some language suggestions (for edge case specific language _and_ other things). These are changes we decided to make.

Since we are demo'ing to AMO on Thursday, we'd like to have these done and deployed to UAT before then.

## Acceptance Criteria
The following copy changes are made:

- On the radio options under "What is the Benefit Type?"
   - Pension -> Pension & Survivor’s Benefits
   - VHA -> Veterans Health Administration
   - NCA -> National Cemetery Association
- "Did the Veteran request an informal conference?" => "Was an informal conference requested?"
- "Did the Veteran request review by the same office?" => "Was an interview by the same office requested?"
- "Did the applicant request an exemption to the date requirements?" = "Did the applicant request an extension to the date requirements?"
- In the navbar, "Add Issues" => "Add/Remove Issues"

## Mocks
![review - hlr - 110918](https://user-images.githubusercontent.com/11700545/48295335-d278ba00-e43f-11e8-8cdc-2ca41f2b46de.png)
## Notes
Background: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1023

**Comment by kencheeto** [comment]
![Screen Shot 2018-11-13 at 11.55.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9702ff932b230012942254/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a379ee0c2e54415f46be5d4a1f06a3a3dc78e2a436628f5409bcd33b5a7dc43411fabc824eb801ba72894a85b5ee9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc5af748e84d54a61b3062f43b.png)

fyi deleted this word @shanear

**Comment by kencheeto** [comment]
Curious where
> In the navbar, "Add Issues" => "Add/Remove Issues"

"navbar" is - it could either be the browser title bar:

![Screen Shot 2018-11-13 at 12.13.49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9702ff932b230012942254/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a379ed0c2a52415b47be5d4a1f06a3a3dc78e2a436628f5409bcd33b5a7dc43411fabc824eb801ba72894a85b5ee9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecc5af74fe14c53a511316bf43b.png)

or the breadcrumb:

![Screen Shot 2018-11-13 at 12.14.18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9702ff932b230012942254/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a379ed0c2a55415e46be5d4a1f06a3a3dc78e2a436628f5409bcd33b5a7dc43411fabc824eb801ba72894a85b5ee9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecc5af74fe14c56a0153f63f43b.png)

**Comment by steve-gov** [comment]
Validated.
