### ISSUE TITLE
Case Details | Sentry errors

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7834]
While testing, we got several Sentry errors from the Case Details page. We need to resolve them.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2947/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2946/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2950/

**Comment by oscarAtNava** [comment]
@MeredithStewart Jed made a change to the VACOLS DB. Please confirm users can save a video hearing next time you test in prod with them. Thanks.
