### ISSUE TITLE
Automatic case distribution rollout plan

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7838]
Related to https://github.com/department-of-veterans-affairs/caseflow/issues/5575.

1. [Backend of legacy auto-case-distribution](https://github.com/department-of-veterans-affairs/caseflow/pull/7692/files)
2. [Frontend of legacy auto-case distribution](https://github.com/department-of-veterans-affairs/caseflow/pull/7805)
3. Manual testing
    - Test 10 near simultaneous distributions to 10 different judges. They should all complete successfully.
    - Ensure that FACOLS data exists to test case distribution locally.
4. Create Auto Case Distribution Looker dashboard for monitoring and metrics
    - number of completed distributions per day
    - Mean time to completion of each distribution (created at - completed at)
    - [later] Count # of appeal ids in multiple distributions? (should always be zero)
    - [later] Mean proportion of priority non-genpop / non priority non-genpop / priority genpop / non-priority genpop cases in each distribution per day?
   - Priority pending: How many priority cases are waiting to be distributed at any given time?
   - Priority timeliness: How long does Caseflow take to distribute a new priority case?
   - Distribution diversity: Are we balancing priority cases among judges?
   - Docket efficiency: How deep in the docket does Caseflow have to look to find enough cases?
5. Pilot legacy auto-case distribution for two judges
6. Increase pilot size to ~20 judges
7. Roll out legacy auto-case distribution to all judges
~~8. Integrate RAMP cases into auto-case distribution? (needs separate spec)~~

**Comment by cmgiven** [comment]
I like the idea of doing 10 simultaneous distributions.

The looker dashboard should have some of the same metrics we used when simulating:

* Docket efficiency: How deep in the docket does Caseflow have to look to find enough cases?
* Distribution diversity: Are we balancing priority cases among judges?
* Priority timeliness: How long does Caseflow take to distribute a new priority case?
* Priority pending: How many priority cases are waiting to be distributed at any given time?

What are your thoughts on 8? Is running the round robin script a pain? My initial sense is that it's not worth doing further work as it has no real connection to how things will work after AMA day, but you know better here.

**Comment by amprokop** [comment]
Running the round robin script isn't too much of a pain, although it would be better to automate it!

The vague thought I had was that adding RAMP appeals to legacy case distribution could possibly be a  step towards adding all AMA appeals. We could just add 1 RAMP appeal from the top of that queue to each legacy case distribution, and test a bit of the logic that way.

It might be increased effort explaining/selling this to the Board, or maybe I'm overestimating how much of a halfway step it would be, though. Any thoughts?

**Comment by cmgiven** [comment]
I don't immediately see anything that advances us toward AMA case distribution. It's a single case, it uses different definitions of ready than post-2/14, etc.

**Comment by amprokop** [comment]
Got it, sounds good then 👍

**Comment by laurjpeterson** [comment]
Suggested two judges to DVC Osborne. Looking like JudgesAmy Ishizawar and Paul Sorisio will participate.

**Comment by amprokop** [comment]
Cool. Continuing with testing on this today.

**Comment by amprokop** [comment]
@cmgiven — i poked around at this quite a bit locally and wasn't able to find any problems. 🎊 I think I'm satisfied with manual testing.

**Comment by amprokop** [comment]
@cmgiven @laurjpeterson — anything on your ends that we'd need to button up before starting the pilot of this? I'm pretty satisfied. 

After thinking about it, I think we should create the Looker dashboard after the first 2 users make their first distributions, so we'll have data to view.

**Comment by laurjpeterson** [comment]
🎉 Excellent! The only thing left to do is to communicate to our two pilot judges and feature toggle. I'll let them know that they should stop requesting cases using the spreadsheet, and that they will need to assign out all of their cases in order to first see the functionality. I can send this email out today!

What is the feature toggle called?

Then, we can create the Looker dashboard. I'd like to pair with @cmgiven to create visualizations for each of these metrics. 

- Docket efficiency: How deep in the docket does Caseflow have to look to find enough cases?
- Distribution diversity: Are we balancing priority cases among judges?
- Priority timeliness: How long does Caseflow take to distribute a new priority case?
- Priority pending: How many priority cases are waiting to be distributed at any given time?

**Comment by cmgiven** [comment]
Pairing sounds great. Feature toggle is automatic_case_distribution.

**Comment by amprokop** [comment]
@laurjpeterson — the feature toggle is called `automatic_case_distribution`

**Comment by laurjpeterson** [comment]
https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1781
