### ISSUE TITLE
Determine when to switch CO hearing days to Caseflow

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#7841]
*CO Hearing Days* 
Resolution — We put this on hold. 
	* Put it off for 1 week 
	* We’ll re-evaluate
	* Potentially ask Jed 
*  Take over - put in new data model 
* We need to create the parent records? 
* Upload spreadsheet with zero RO 
* Algorithm hardcoded Wednesdays 
 
* Pros
	* bugs ironed out early
	* Doing it in Caseflow easier than VACOLS 

* Cons
	* They would lose reporting functionality 
	* Other functionality that we haven't built

**Comment by sharonwarner** [comment]
We moved the hearing days starting 1/1.
