### ISSUE TITLE
Allow Reader to load documents when VBMS uses claim number instead of SSN

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7844]
To resolve this support ticket: https://github.com/department-of-veterans-affairs/appeals-support/issues/3458

**Comment by mdbenjam** [comment]
This is an important change. I can work on it next week.

**Comment by laurjpeterson** [comment]
@pkarman do you know if any of our SSN work addressed this?

**Comment by pkarman** [comment]
looks like it was addressed in efolder https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1052
