### ISSUE TITLE
Refactor modal transition logic

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#7850]
## Context
Intake currently has a [series of modals](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intake/pages/addIssues.jsx#L168-L189) that display during the add & issues flow.

* It is hard to tell what modal displays at what time. Some logic is within the modal, some is within _other_ modals, some are from the page itself.
* As we add more modals, it is unlikely that any one person will understand all the different modal flows and how they interact with each other without having to look through all modals.

## Proposal

We have a state machine/directed graph of modals, maybe we can represent all the edges of that graph in a separate component that then handles all transition logic.

The alert switcher component would be kind of like the SwitchOnForm component, only it switches on custom functions instead.

```js
class AlertSwitcher extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      modalShown: 'AddIssuesModal'
    }
    // transition obj takes care of the logic for
    // changing between multiple alerts
    this.transitions = {
      AddIssuesModal: {
        component: AddIssuesModal,
        onNext: (modalData, cb) => {
          // the check for legacyOptIn could also be a function that lives in AlertSwitcher
          if (modalData.legacyOptIn) return updateModal('LegacyOptInModal');
          if (!modalData.legacyOptIn && state.isUntimely) return updateModal('UntimelyExemptionModal');
          if (modalData.blah) return updateModal('OtherModal');
          // callback is used to handle actions unique to the 
          // "next/submit" of the add issues button
          // in this case, adding a rated issue
          cb && cb();
        }
      }
      'LegacyOptInModal': {
        component: LegacyOptInModal,
        onNext: (modalData, cb) => {
          if (modalData.isUntimely) return updateModal('UntimelyExemptionModal');
          cb && cb();
        }
      }
      ...
    }
  }

  updateModal(modalName) => {
    this.setState({
      modalShown: modalName
    });
  }

  render() => {
    const currentAlert = this.transitions[this.state.modalShown]

    // creates the component and passes in the transition function
    return React.cloneElement(
      currentAlert.component,
      {onNext: currentAlert.onNext}
    )
  }

}
```

Then the modals themselves only have to handle cases that terminate at that specific modal (such as adding a rated issue on the AddIssuesModal).

```js
class AddIssuesModal extends React.Component {
  onAddIssue() => {
    // now only handles the case of adding the issue
    // transitioning to the modals will be handled by the parent
    // component
    this.props.addRatingRequestIssue({
      issueId: this.state.referenceId,
      ratings: this.props.intakeData.ratings,
      isRating: true,
      notes: this.state.notes
    });
    this.props.closeHandler();
  }

  render() => {
    return <Modal
      buttons={[
        {
          name: 'Cancel',
          onClick: closeHandler, // still use same close handler
        },
        {
          name: 'Add issue',
          onClick: () => {
            // passes the current state to AlertSwitcher
            // AlertSwicher handles logic to transition to other modals
            this.props.onNext(this.state, onAddIssue)
          }
        }
      ]}
    >
    ...
    </Modal>
  }
}
```

## Pros
* Consolidates all transition logic
* Opens us up to testing transitioning between modals/all the possible modal flows without having to do a full feature test for each scenario.
* Ideally this allows us to pull the modal visibility states out of the global redux store.
* Removes all the modal components from the AddIssues page
* Each modal only cares about itself.

## Cons
* AlertSwitcher could get really messy
* engineering lift not worth it unless transitions get messy
* introduces new pattern that engineers have to learn

**Comment by pkarman** [comment]
+1 I like this very much.

**Comment by leikkisa** [comment]
I like this idea!  I guess since we're not likely to add more modals it could be a lower priority tech backlog ticket, but I think it'd still be nice to have.

Just a comment that a couple of the other modals (Legacy Opt In, timeliness exemption) need to get the issue data from the first modal since it doesn't get added yet in that modal.

**Comment by jiahuang** [comment]
@leikkisa the `onNext` function gets the current modalData passed in, so for the case of the LegacyOptIn, we could grab the issue data from the AddIssueModal during the transition and pass that in as props when the LegacyOptIn is created. Currently we store the issue data in the global redux store but I don't really like that.

**Comment by laurjpeterson** [comment]
@jimruggiero tagging you in this tech debt ticket re: add/remove issues modals for future reference

**Comment by leikkisa** [comment]
@jcq Tagging you as well!

**Comment by jcq** [comment]
Big +1 from me on this, as I spent a bunch of time yesterday wrestling with trying to insert the new correction type modal into the existing flow. Under the current structure, it's not a simple prospect, and even what would be fairly straightforward refactoring is made overly complex by the reliance on redux for everything. 

I have actually already begun a bit of this refactoring, moving some stuff into the parent AddIssuesPage component, but I like this component structure better.

I would modify the original post however to say that general best practices would have the modals themselves be fairly dumb presentational components that don't need to be connected to redux. They can just return whatever data they generate in their close callback, and the modal handler can pass that along as props to the next one and/or dispatch Redux actions.
