### ISSUE TITLE
Intake | Allow withdrawing issues for HLRs and SCs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7860]
Withdrawal reasons 
	1	Death
	2	POA
	3	Veteran
	4	Moot (inexplicitly intertwined/brought in under another condition)

- EPs are canceled via withdrawals
- HLRs and SCs are always withdrawn via writing

**Comment by carolaponce** [comment]
Do we need to finish this feature for the Feb 14 launch?

**Comment by shanear** [comment]
This was completed by https://github.com/department-of-veterans-affairs/caseflow/milestone/71
