### ISSUE TITLE
Allow users to clear all tags in Reader

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#7874]
Feedback received from an attorney: 

"Is there way to delete all previous tags/tabs added in Caseflow? I have been doing it manually, but someone just asked me if I knew of a way to clear all since they had a 3000 doc claims file. If not, is that something that can be added? In VBMS we could click clear all tags- I cannot find this option in Caseflow – it would be useful, especially when a case comes back from a remand after another attorney tagged/tabbed the case."

Attorneys would like to be able to clear all tags from documents in a veteran's case folder. If the case is remanded and comes back to the board, the attorney that is working the case will see the previous tags and annotations. They would like the ability to clear the tags and add new ones for the new review.

**Comment by D-L-Ware** [comment]
Note there are policy implications here such that we likely would want to clear this functionality with Board leadership before developing.

**Comment by D-L-Ware** [comment]
Closed as part of Reader ticket clean up.
