### ISSUE TITLE
BGS Integration | Pull veteran's RO

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7881]
In AMA world, we need to know what RO a veteran is associated with so we can schedule the hearing at the correct RO. While previously the RO was saved on the appeal, AMA appeals don't have any concept of an RO. 

We might be able to pull this information from BGS. We should pull a list of ~100 legacy appeals and confirm the VACOLS ro matches the veterans' BGS RO.

If the information is accurate, we should develop an integration to pull the veteran's RO from BGS. If the information is not accurate, we need to develop a new plan.

**Comment by MeredithStewart** [comment]
end point: station of jurisdiction?

**Comment by oscarAtNava** [comment]
@MeredithStewart provided me with two Legacy Appeal file numbers. For the file number starting with 3 the BRIEFF table shows 21 rows for this veteran. The row with an active location code(36) has an RO value of RO14 (Roanoke, VA) but the station of jurisdiction returned by BGS is 335 (St Paul, MN).

For the file number starting with 6 the BRIEFF table had 6 rows for this veteran. The row with an action location code (33) has an RO value of RO91 (Buffalo Education Center, NY) whereas the station of jurisdiction returned by BGS is 310 (Philadelphia, PA).

**Comment by MeredithStewart** [comment]
From @mc-usds:  I was looking through BGS's documentation for something else and happened across this:
RORoutingService
Common Web Service

Service Description
The RO Routing Service is designed to publish regional office related oracle packages, procedures and decouple Lines of Business from oracle related packages, procedures.

Methods
•    GetRegionalOfficeByZipCode - Retrieve all the regional offices based on the zip code search criteria for each Line of Business.
I'm sorry I didn't find this before. I was thinking in terms of Veteran's RO -- i.e. doing a lookup by vet's filenumber or id.  Not looking up by their zip code.
I'm not sure what "each line of business" means. I've asked BGS and am waiting to hear back.

**Comment by MeredithStewart** [comment]
We aren't doing BGS. Closing ticket.
