### ISSUE TITLE
[BE] Create a join model so request issues and decision issues can have many-to-many relationship

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7884]
1. Create a join model RequestDecisionIssue and the associated table. 
2. Start writing to the new table for HLR and SC as well as to the `source_request_issue_id` column
3. Deploy
4. Then write a migration to migrate existing decision_issues to use the new table
5. Deploy
6. Start reading from the new table for all cases
7. Deploy
8. Remove `source_request_issue_id` from the `decision_issues`

**Comment by pkarman** [comment]
It seems important to be able to explicitly know if a `RequestIssue` is in response to a `DecisionIssue` (its "source") or vice versa. We might need additional column(s) on the join model in order to designate that relationship.
