### ISSUE TITLE
Enable admin action functionality for VLJ support + 2 chief group's attorneys

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7892]
We are rolling out admin action functionality to all VLJ support staff and attorneys from Chief Trueba and Chief Buck's groups. 

## AC
- update features.config file - https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/features-config.yml
- VLJ support staff - feature: "colocated_queue",
- attorneys - feature: "attorney_assignment_to_colocated"

### VLJ Support Staff
<img width="181" alt="screen shot 2018-11-19 at 10 21 13 am" src="https://user-images.githubusercontent.com/27704093/48716239-df866d80-ebe4-11e8-83f4-22ee519e4926.png">

### Chief Buck's group

From: Buck, Bethany <Bethany.Buck@va.gov>
Date: Friday, Nov 16, 2018, 10:47 AM
To: Donohue, Michael <Michael.Donohue@va.gov>, Adamson, Amanda <Amanda.Adamson@va.gov>, Ahlberg, Andrew <andrew.ahlberg@va.gov>, Andersen, Lauren <Lauren.Andersen@va.gov>, Auer, Marjorie <marjorie.auer@va.gov>, Barnard, Lisa <lisa.barnard@va.gov>, Bognar, Samantha <Samantha.Bognar@va.gov>, Chiappetta, Vincent C. <Vincent.Chiappetta@va.gov>, Colicelli, Marcus <Marcus.Colicelli@va.gov>, Crohe, Lisa <Lisa.Crohe@va.gov>, Daus, Haley <Haley.Daus@va.gov>, Davis, Tracy <Tracy.Davis3@va.gov>, DeChiara, Angeline <Angeline.DeChiara@va.gov>, Dodd, Ryan <Ryan.Dodd@va.gov>, DuPree, Desiree <Desiree.DuPree@va.gov>, Ebaugh, Donna D. <Donna.Ebaugh@va.gov>, Elliott, Robert A. <Robert.Elliott5@va.gov>, Feinberg, Rebecca <Rebecca.Feinberg@va.gov>, Fournier, Samantha <Samantha.Fournier@va.gov>, Fussell, John F. <john.fussell@va.gov>, Gastoukian, Kelly <Kelly.Gastoukian@va.gov>, Giaquinto, Michael <Michael.Giaquinto@va.gov>, Gielow, Kristine M. <Kristine.Gielow@va.gov>, Hanson, Tiffany <Tiffany.Hanson@va.gov>, Hartford, Marisha A. (VACO) <Marisha.Hartford@va.gov>, Hitchcock, Ian <Ian.Hitchcock@va.gov>, Hoeft, Holly <Holly.Hoeft@va.gov>, Hoover, Leigh A. <Leigh.Hoover@va.gov>, Jack, Jason <Jason.Jack@va.gov>, Jaigirdar, Binafar <Binafar.Jaigirdar@va.gov>, Jalley, Elizabeth <Elizabeth.Jalley@va.gov>, Jamison, Elizabeth G. <Elizabeth.Jamison@va.gov>, Jensen, Rachel <Rachel.Jensen4@va.gov>, Johnson, Polly <Polly.Johnson@va.gov>, Kilcoyne, Michael <michael.kilcoyne@va.gov>, KIM, ESTHER H. <ESTHER.KIM8@va.gov>, Kim, Soyeob <Soyeob.Kim@va.gov>, Kipper, Rebecca <Rebecca.Kipper@va.gov>, Lee, Caren <Caren.Lee@va.gov>, Lee, Jeanette K. <Jeanette.Lee2@va.gov>, Lewis, Brandon <Brandon.Lewis6@va.gov>, Lherault, Daniel <Daniel.Lherault@va.gov>, Lin, Mao Ching <MaoChing.Lin@va.gov>, Lindio, Alexine <Alexine.Lindio@va.gov>, Luboch, Martha <Martha.Luboch@va.gov>, Maddox, April <april.maddox@va.gov>, Mask, Brooke <Brooke.Mask@va.gov>, McPhaull, Maria <Maria.McPhaull@va.gov>, Middleton, John <John.Middleton@va.gov>, Middleton, Syesa <Syesa.Middleton@va.gov>, Mmeje, Natalya <Natalya.Mmeje@va.gov>, Moats, Jennifer <Jennifer.Moats@va.gov>, Morrad, Shabnam <Shabnam.Morrad@va.gov>, Obodo, Nnamdi <Nnamdi.Obodo@va.gov>, Ohlstein, Daniel <Daniel.Ohlstein@va.gov>, Olsen, Jeremy <Jeremy.Olsen@va.gov>, Osborne, Michael T. <MichaelT.Osborne@va.gov>, Palacios-Peters, Alexia <Alexia.PalaciosPeters@va.gov>, Price, Antonette <Antonette.Price@va.gov>, Purcell, Amanda <Amanda.Purcell@va.gov>, Purcell, Amy <Amy.Purcell@va.gov>, Rembert-Carroll, Devon <Devon.Rembert-Carroll@va.gov>, Roberson, Jonathan <Jonathan.Roberson@va.gov>, Ruiz, Kisa <Kisa.Ruiz@va.gov>, Sebstead, David <David.Sebstead@va.gov>, Shannon, Tiffani <Tiffani.Shannon@va.gov>, Singleton, Deborah W. <debra.singleton@va.gov>, Skiouris, Elena <Elena.Skiouris@va.gov>, Smith, Tanya <Tanya.Smith@va.gov>, Springer, James <James.Springer2@va.gov>, St. Laurent, Andre <Andre.St.Laurent@va.gov>, Suh, Grace <Grace.Suh@va.gov>, Talamantes, Tamyko <Tamyko.Talamantes@va.gov>, Talpins, Patricia <Patricia.Talpins@va.gov>, Taylor, Candas <Candas.Taylor@va.gov>, Trojanowski, Erin <Erin.Trojanowski@va.gov>, Turnipseed, Adriane <Adriane.Turnipseed@va.gov>, Uller, Jason <Jason.Uller@va.gov>, Unger, Julie <Julie.Unger@va.gov>, Walker, Helena <Helena.Walker@va.gov>, Warren, Ivey <Ivey.Warren@va.gov>, Watkins, Shauna M. <Shauna.Watkins@va.gov>, Wheatley, Christa <Christa.Fields@va.gov>, Whitley, Juanita <Juanita.Whitley@va.gov>, Williams, Jasmine <Jasmine.Williams@va.gov>, Williams, Lauren <Lauren.Williams12@va.gov>, Zenzano, Alexa M. <Alexa.Zenzano@va.gov>, Zimmerman, Micah <Micah.Zimmerman@va.gov>, Zizzi, Andrea <Andrea.Zizzi@va.gov>

### Chief Trueba's group
Bakke, Lila J. <Lila.Bakke@va.gov>; Ballinger, Daniel <Daniel.Ballinger2@va.gov>; Barone, Jacqueline <Jacqueline.Barone@va.gov>; Baskerville, LaRita <LaRita.Baskerville@va.gov>; Baxter, Sikenah <Sikenah.Baxter@va.gov>; Bodi, Benjamin <Benjamin.Bodi@va.gov>; Brandt, Kristin (BVA) <Kristin.Brandt1@va.gov>; Brant, Jenna <Jenna.Brant@va.gov>; Cherry, David T. <david.cherry@va.gov>; Creegan, Amanda <Amanda.Creegan@va.gov>; DeFrank, James <James.DeFrank@va.gov>; Delhauer, Sara <Sara.Delhauer@va.gov>; Doran, Margaret <Margaret.Doran@va.gov>; Duffy, Michael <Michael.Duffy@va.gov>; Fitzgerald, Trina <Trina.Fitzgerald@va.gov>; Garlick, Corey <Corey.Garlick@va.gov>; Georgiev, Katerina <Katerina.Georgiev@va.gov>; Harner, Christopher <Christopher.Harner@va.gov>; Hebert, Matthew <Matthew.Hebert3@va.gov>; Henry, Tara-Deen <Tara-Deen.Henry@va.gov>; Hoopengardner, Stephen <Stephen.Hoopengardner@va.gov>; Houbeck, Christopher <Christopher.Houbeck@va.gov>; Jones, Robert E. <robert.e.jones@va.gov>; Juliano, Janee L. <Janee.Juliano@va.gov>; Kardian, Kimberly <Kimberly.Kardian@va.gov>; Keeley, Brian <Brian.Keeley@va.gov>; Keogh, Nicholas <Nicholas.Keogh@va.gov>; Keselyak, Joseph <Joseph.Keselyak@va.gov>; Khan, Saif <Saif.Khan@va.gov>; Kilbride, Eugene (DISABLED ACCT) <Eugene.Kilbride@va.gov>; Kim, Jennifer <Jennifer.Kim8@va.gov>; Komins, Benton <Benton.Komins@va.gov>; Lee, Daniel S. (BVA) <Daniel.Lee4@va.gov>; Little, Calvin <Calvin.Little@va.gov>; Luby, Matthew <Matthew.Luby@va.gov>; Lunger, Margaret <Margaret.Lunger@va.gov>; Lynch, Kevin <Kevin.Lynch4@va.gov>; Marsh, Anthony II <Anthony.Marsh@va.gov>; Massey, Jason <Jason.Massey@va.gov>; McDermott, Kristina <Kristina.McDermott@va.gov>; McDonald, Kelly <Kelly.McDonald4@va.gov>; McDuffie, Kerstin <Kerstin.McDuffie@va.gov>; McEntee, Christopher <Christopher.McEntee@va.gov>; Michel, Riley <Riley.Michel@va.gov>; Mine, Eric <Eric.Mine@va.gov>; Mulrain, Garrett <Garrett.Mulrain@va.gov>; Murray, Jennifer <Jennifer.Murray@va.gov>; Najarian, Steven <Steven.Najarian@va.gov>; NeSmith, Curtina <Curtina.NeSmith2@va.gov>; Ong, Geoffrey <Geoffrey.Ong@va.gov>; Prinsen, Samantha <Samantha.Prinsen@va.gov>; Reed, Seth <Seth.Reed@va.gov>; Rippel, Nancy <Nancy.Rippel@va.gov>; Ronquillo, Erica <Erica.Ronquillo@va.gov>; Salazar, Max <Max.Salazar@va.gov>; Samadani, Tahirih <Tahirih.Samadani@va.gov>; Schick, Suzanne <Suzanne.Schick@va.gov>; Sellers, Sara <Sara.Sellers@va.gov>; Setter, John G. <John.Setter@va.gov>; Shannon, Gregory <Gregory.Shannon@va.gov>; Silverblatt, Lindsay <Lindsay.Silverblatt@va.gov>; Slaughter, Allison <Allison.Slaughter@va.gov>; Smith, Ravay <Ravay.Smith@va.gov>; Steele, Erika <Erika.Steele4@va.gov>; Stephens, Ryan <Ryan.Stephens2@va.gov>; Strike, Samuel <Samuel.Strike@va.gov>; Suffoletta, Mary <mary.suffoletta@va.gov>; Syed, Arif Y. <Arif.Syed@va.gov>; Tunis, Jamie L. <Jamie.Tunis@va.gov>; Umo, Idongesit <Idongesit.Umo@va.gov>; Vang, Stephanie <Stephanie.Vang@va.gov>; Wade, Jamille <Jamille.Wade@va.gov>; White, Annamaria <Annamaria.White@va.gov>; Yang, Jonathan <Jonathan.Yang@va.gov>; Yoffe, Phillip <Phillip.Yoffe@va.gov>; Zheng, Andrew <Andrew.Zheng3@va.gov>

**Comment by laurjpeterson** [comment]
@lowellrex - can you confirm that we should be using the `attorney_assignment_to_colocated` feature toggle for attorneys? i don't see it being used in the features.config file right now, for the initial 9 attorneys that were part of the pilot in september. i know that during the first week of october, you enabled all RAMP appeals to have admin actions added to them, so any attorney assigned a RAMP appeal could do so. did that affect this feature toggle at all?

cc: @marvokdolor-gov

**Comment by marvokdolor-gov** [comment]
@laurjpeterson I see it in the file with these attorneys listed: 
`users: ["bvajunger", "vacowhitan", "bvarburriesci", "vacoDavidC", "bvampeters", "vacoBametP", "vacojimerd", "bvamwulff", "vacoKominB"]`

**Comment by laurjpeterson** [comment]
ah excellent! i might have been looking at my outdated PR. nevermind, @lowellrex!

**Comment by marvokdolor-gov** [comment]
### List of all CSSIDs for Attorneys listed above
["VACOMIDDLS2", "BVAJFUSSELL", "BVAHHOEFT", "BVARKIPPER", "VACOLEWISB",
"VACOMORRAS", "VACOHANSOT", "VACOHOOVEL", "VACOLINM", "VACOJACKJ", "VACOMMEJEN",
"BVAALINDIO", "BVAKGIELOW", "BVAMMCPHAULL", "BVAMLUBOCH", "BVAESKIOURIS",
"VACOPRICEA", "VACOTALAMT", "VACODECHIA", "VACOBOGNAS", "VACOHARTFM",
"BVAJMOATS", "BVAAMADDOX", "BVAAZENZANO", "BVAJUNGER", "VACOSUHG", "VACOLEEJ5",
"VACOZIMMEM", "VACOWHITLJ", "VACOPURCEA", "VACOKIME2", "VACOMIDDLJ",
"BVAAAHLBERG", "BVASBOEHM", "BVASKIM", "BVAAPURCELL", "VACOGASTOK",
"VACODAVIST1", "VACOSHANNT", "VACOZIZZIA", "VACOJAIGIB", "BVAAADAMSON",
"BVARDODD", "BVACBATES", "BVAPHOGAN", "VACOCARROE", "VACOJENSER", "VACOELLIOR",
"VACOULLERJ", "VACOLHERAD", "VACOSTLAUA", "VACOFOURNS", "BVAMOSBORNE",
"BVAATURNIP", "BVAJOLSEN", "BVAJWILLIAMS", "VACODAUSH", "VACOWARREI",
"VACOHITCHI", "VACOLEEC1", "VACOOHLSTD", "VACOROBERJ6", "BVALEDWARDS",
"BVAMHANNAN", "BVAEJALLEY", "VACOJAMISE", "VACOTAYLOC", "VACOPALACA",
"VACORUIZR", "VACOOBODON", "VACOMASKB", "VACOSEBSTD", "BVALCROHE", "BVADEBAUGH",
"BVAJSPRINGER", "VACOJOHNSP2", "VACOWILLIL12", "VACOGIAQUM", "VACOGARLIC",
"VACOMCDERK", "VACOSTRIKS", "BVANRIPPEL", "BVAASYED", "BVAMSUFFOLE",
"BVARSTEPHENS", "VACOYOFFEP", "VACOSHANNG", "VACOCREEGA", "VACOSELLES",
"VACONESMIC", "VACODICKET", "BVACHOUBECK", "BVAJSCHROADER", "BVASHOOPEN",
"BVAKKARDIAN", "VACOFITZGT", "VACOONGG", "VACOHARNEC1", "VACOBALLID",
"VACOZHENGA3", "VACOLJBAKKE", "BVADLEE", "BVASDELHAUER", "VACOMINEE",
"VACOSCHICS", "VACOBRANDK1", "VACOSALAZM", "VACOYANGJ1", "VACOHEBERM",
"VACOKIMJ5", "BVAJTAYLOR", "BVADTCHERRY", "BVAJDEFRANK", "VACODUFFYM",
"VACOHENRYT", "VACOKEOGHN", "VACOLUBYM", "VACOSTEELE", "BVAJMURRAY",
"BVAJKESELYAK", "BVASREED", "VACOVANGS", "VACOBAXTES", "VACOMARSHA",
"VACOMCDONK4", "VACOLITTLC", "VACOMULRAG", "BVALBCRYAN", "BVAAMICHEL",
"VACOBASKEL", "BVAJTUNIS", "VACOBODIB", "VACOSETTEJ", "VACOKEELEB",
"VACOWATSOM3", "VACOKHANS", "VACOSLAUGA" "BVAJBARONE", "BVAMDORAN", "BVATSAMAD",
"BVAKGEORGIEV", "VACOSILVERL", "VACOKOMINB", "VACOUMOI", "VACOMCDUFK",
"VACOMASSEJ", "VACOSMITHR6", "VACORONQUE", "BVAREPJONES", "BVACMCENTEE",
"BVASNAJARIAN", "BVAMLUNGER", "VACOPRINSS", "VACOWADEJ"]

#### List of all CSSIDs for VLJ Support Team 

#### References:
[Appeals-Judge Mapping](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/constants/attorney_judge_teams.rb#L236)
Judges: Deborah   Singleton, Helena Walker, Lisa Barnard. Marjorie Auer, Michael Kilcoyne, Rebecca Feinberg, Tanya Smith, Vince Chiappetta
[Support ticket re: Reader Access](https://github.com/department-of-veterans-affairs/appeals-pm/issues/2032#issuecomment-403942749)

**Comment by marvokdolor-gov** [comment]
@lowellrex A quick ping on this: noticed that Koroma isn't listed in the `prod` section here:
`  {
        feature: "colocated_queue",
        users: ["bvatowens", "bvarseay"]
      }`
Is that the right place?

**Comment by lowellrex** [comment]
Mr. Koroma not being in that list only changes what webpage we show when he visits `appeals.cf.ds.va.gov`. VLJ staff who not in that list (like Koroma) see the search page, and VLJ staff who are in that list see their personalized task queues. I know Koroma visits caseflow by using a browser bookmark so this is not a huge concern.

Also, since we are rolling out queue to all VLJ support staff I've created a PR to show the personalized task to all VLJ support staff when they visit `appeals.cf.ds.va.gov` (https://github.com/department-of-veterans-affairs/caseflow/pull/7913).

**Comment by marvokdolor-gov** [comment]
I see them both in the list I have above?

**Comment by laurjpeterson** [comment]
still open because i still need to associate "vacodraytm" and "bvatbrowning" with the vlj support organization

**Comment by laurjpeterson** [comment]
Added bvatbrowning to the VLJ Support Staff organization. Still have not been able to find vacodraytm.
