### ISSUE TITLE
Including Benefit Type in Case Timeline

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#7902]
### Question
Should we start showing 'benefit type' in Case Details/Timeline?

### Path to an answer
- @allyceh to do some usability testing with Attorneys

### Current state
- Until Feb it will all be 'Compensation'

### Related Tickets
[Case Timeline #5592 ](https://github.com/department-of-veterans-affairs/caseflow/issues/5592)
[Case details #5571 ](https://github.com/department-of-veterans-affairs/caseflow/issues/5571)

**Comment by allyceh** [comment]
@marvokdolor-gov Do you have a list of options for what the benefit type could be? Aka, all possible options a user could see?

<img width="878" alt="screen shot 2018-11-19 at 12 19 46 pm" src="https://user-images.githubusercontent.com/40216950/48723737-6e9b8180-ebf5-11e8-85d4-8a1b7e8a16e8.png">
I pulled these benefit type options from Suzanne's intake designs. If you think there is anything else the user might see, add them here.

**Comment by marvokdolor-gov** [comment]
Thanks @allyceh! 
I don't have a list, but this looks like a good place to start and then get it ground-truthed by attorneys, unless there's a better way.

**Comment by laurjpeterson** [comment]
I think that's the full list of benefit types/business lines! I'm thinking that this info will make sense somewhere in Case details instead of Case timeline.

For legacy appeals, we show business line/benefit type by issue (it's called Program Area in VACOLS). i think we'd want to continue this for AMA appeals.

**Comment by allyceh** [comment]
@laurjpeterson Agreed. At the "issue level" feels like the right place for this info to sit.

**Comment by laurjpeterson** [comment]
We show benefit type for AMA issues now, so closing.
