### ISSUE TITLE
Create mail task modal routes to team based on task type

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7906]
As we [roll out access to queue to the mail team](https://github.com/department-of-veterans-affairs/caseflow/issues/7404), we need to add actions that support their workflow. Currently, clicking on the "Create mail task" task action brings up the generic "Assign to team" modal. Mail is used to creating a mail task that is routed automatically to a Board team based on the type of mail task that is being created (mail types listed in #7404), so we need to support that way of working by automatically routing the mail task to the correct team based on the type of task that is being created.

## Acceptance criteria:
* Determine the routing rules for each mail task
* Automatically route new mail tasks to the correct team based on the mail task type

## Reference - rollout progression
1. Allow mail team to assign tasks to `VLJ Support`, `AOD`, `Privacy`
2. Probably, next allow mail team to assign tasks to `Hearings`
3. Allow mail team to assign tasks to `Lit Support`

**Comment by laurjpeterson** [comment]
Field name in VACOLS: MLTYPE

### Phase 1: VLJ Support
Mail task type | Route to team
---|---
01	Change of Address | VLJ Support
05	Evidence or Argument
06	FOIA Request

08	Motion to Advance on Docket

10	Power of Attorney Related


16	Extension Request
17	Privacy Act Request
19	Privacy Complaints


24	FOIA Request & Other Actions



02	Congressional Interest
03	Controlled Correspondence
04	CUE Related
09	Motion for Reconsideration
13	Status Inquiry
18	Other Motion
25	Motion to Vacate
26	Attorney Inquiry


### Questions
07	Hearing Related
11	Professional Service Mail
12	Returned or Undeliverable Mail
14	Death Certificate
15	Appellate Group Mail
20	Intra/Inter Agency Request
21	Ebert Temporary Transfer
22	How Do I Appeal Pamphlet
23	ECA Revocation

**Comment by laurjpeterson** [comment]
Meeting with all admin branches on Monday, Dec 3, 1pm - to finalize the routing logic that we've been discussing through email
