### ISSUE TITLE
Intake | Add instructions on who to email in order to add a veteran to CorpDB

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7908]
Many non-comp business lines don't use VBA corporate DB as their primary source of truth for veteran information. This causes a problem, because all of Caseflow revolves around retrieving veteran information from BGS (and thus, VBA Corp DB).

The short term solution to that problem, is to tell users who need to add a veterans to CorpDB to email a volunteer from VBA to add that veteran.

## Acceptance Criteria
- When an intake is being processed, and the veteran is not found in BGS, the error copy should be updated to match the copy below.

## Copy

_Title:_
Veteran not found

_Body:_
Enter a valid Veteran ID or SSN and search again.

Note: If you are certain the Veteran ID or SSN is correct, the claimant may not exist in the VBA Corporate Database. If you have access, please add claimant to the Corporate Database to continue processing this intake. If you do not have access, please [email](mailto:jennifer.umberhind@va.gov) for assistance.

## Notes
The long term fix is here: https://github.com/department-of-veterans-affairs/caseflow/issues/7909

## Background
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1050

**Comment by carolaponce** [comment]
How about this copy:

Enter a valid Veteran ID or SSN and search again.

Note: If you are certain the Veteran ID or SSN is correct, the claimant may not exist in the VBA Corporate Database. Please add claimant to the Corporate Database to complete intake, if you have access. If you don’t have access them _email_ for assistance.

**Comment by kencheeto** [comment]
@carolaponce @shanear is there a group or generic email (intake-help@va.gov or something like that) we could use? would prefer to keep names/user emails out of the repo

**Comment by steve-gov** [comment]
I've tried 30 different fake SSNs and file numbers and can only trigger `veteran_not_accessible` instead of `veteran_not_found`. @jiahuang do you know of a file number that will cause `veteran_not_found` in UAT?

<img width="909" alt="screen shot 2019-01-03 at 2 53 30 pm" src="https://user-images.githubusercontent.com/25468689/50666001-affaad00-0f67-11e9-966d-7cecc133947c.png">

**Comment by steve-gov** [comment]
Shouldn't this trigger the error?

<img width="978" alt="screen shot 2019-01-07 at 4 38 46 pm" src="https://user-images.githubusercontent.com/25468689/50794967-befc9a80-129a-11e9-9999-934f17fae0a2.png">

**Comment by carolaponce** [comment]
@steve-gov Yes.  We are using the style you see as system errors.  Not user error.  I think we should have visual distinctions between the 2.  We have the inline error stye for this case.

**Comment by steve-gov** [comment]
I'm just trying to actually trigger the error that gets the new copy. @jiahuang Would you have any idea what I could put in the search box in UAT to trigger the error?

**Comment by steve-gov** [comment]
I'll just assume that this can't be triggered in UAT due to some kind of data/ environment constraints. We'll have to revalidate in prod.
