### ISSUE TITLE
Business Lines | Create missing veteran in CorpDB using MVI

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7909]
Many non-comp business lines don't use VBA corporate DB as their primary source of truth for veteran information. This causes a problem, because all of Caseflow revolves around retrieving veteran information from BGS (and thus, VBA Corp DB).

The short term solution to that problem is described here: https://github.com/department-of-veterans-affairs/caseflow/issues/7908

The long term solution to that problem is to attempt to look up the veteran via MVI, and provide a mechanism to copy that veteran's information to the corporate DB.

## Open Questions
- can there be multiple veterans for 1 SSN in MVI, do we need to build some way to disambiguate them?

## Notes
MVI is not accepting new integrations until Feb 2019. So this is blocked until then.

## Technical Notes
1. Caseflow does person search in MVI for the Veteran
2. If Veteran is not there, use addPerson to add the person to MVI.
3. If Veteran is there (or if you added in step #2), Caseflow uses MVI Proxy Add, which creates the person in MVI and in Corp and BIRLS. When BIRLS is retired, this will continue to add things to just Corp.
4. Meanwhile, if the person is in MVI but with the wrong information, the information must be corrected on the VBA side, where it will flow into MVI. (This is called a BIRLS update, though it is actually a Corp debate, b/c lol nothing matters.)

**To integrate with MVI:**

To start the integration with MVI, you'll need to submit a Service Request on ESCP (https://escp.aac.va.gov). The catch to this is that the contractor who manages these integrations changes over in mid-February, and they are not starting any new integrations before then, afaik. This is bananas, but it is what it is.

@davidsbao and @gabrielzucker have both gone through this integration. It is annoyingly difficult.

There is some work going on right now to try and make it easier, but I don't know when it will be done.

**Comment by davidsbao** [comment]
@shanear Couple of quick notes:

1) Yes, it's (unfortunately) rather possible for multiple records on MVI to share the same SSN. What you effectively do is run a person search against MVI, and it may return multiple matches back to you. The main options you have are an unattended vs. an attended search:
    - Unattended is what VA.gov uses, where it's a Veteran themselves who are logging in, and we will only communicate back to the user if they are "found in VA records" if there is a single match
    - Attended is what you may want to use here, where if multiple records are returned, then the user (I believe here being a VA employee) is able to choose which record is the correct match. You hopefully tell why we wouldn't want to allow a Veteran to do this themselves, as they would be potentially looking through the PII of others.
2) VA.gov now uses a particular feature called MVI.Orchestration, which enables the following to happen:
    - If the Veteran is not found in MVI, fallback to search against DMDC (DoD's identity store, which should be a fairly reliable record of all Veterans that separated from the ~1980's to today)
    - If the Veteran is found in DMDC, then the Veteran will then get added to MVI
3) Assuming that the Veteran is not in MVI nor DMDC, I'm assuming that there's a sort of proof has already been supplied that would allow for Caseflow to directly add such a Veteran to MVI if they are not found? I personally haven't asked the MVI team of what is necessary to directly call their Add Person route, but know that it's available for use... assuming that there's a DD214 then it seems like their military history would also need to get added to VADIR as well.

Happy to chat if you have more detailed questions on the first 2 points, don't have much more detail myself on the 3rd..

**Comment by gabrielzucker** [comment]
agree with David on all of these points fwiw
