### ISSUE TITLE
Stats | Make room for the Dispatch stats page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#791]
As a system administrator I want to be able to see all the business stats about how people are using Caseflow Dispatch.

## Acceptance Criteria
- Verify that the certification stats pages currently at `/stats/*` are moved to `/certification/stats/*` (so `/stats` should be moved to `/certification/stats`, and `/stats/daily` should be moved to `/certification/stats/daily`)
- Verify that `/dispatch/stats` displays a new stats page with a header of "Dispatch Dashboard" instead of "Certification Dashboard" (see the screenshot below to see where this is). This page will be empty until #819 is complete.
- Verify that `/stats` shows a page with links to both the Certification stats page and the Dispatch stats page. (The design of this page is not important, it should just be a simple USWDS list).

**Comment by cmgiven** [comment]
Here's the initial list. Next step is to write up the details for each.

**Tasks Identified** (blue)
All Decisions
Full Grants
Partials/Remands

**Activity** (blue)
Active Users
Tasks Started
Tasks Completed

**Completion Rate** (blue)
All Decisions
Full Grants
Partials/Remands

**Time to Claim Establishment** (green)
All Decisions (median/95th percentile)
Full Grants (median/95th percentile)
Partials/Remands (median/95th percentile)

**Cancellations** (red)
All Decisions
Full Grants
Partials/Remands

**Comment by cmgiven** [comment]
Full grant —We'd want to use  `appeal.full_grant?` for this, but that's currently subject to a problem in that it uses the status of the case to determine. This works at the moment it is being dispatched, but after a remand is worked, it will be placed in `HIS` status and be marked as a full grant. We need to replace this method to instead use a count of the issues on the case. If the number of issues where `ISSDC = '1'` is greater than 0, but the number of issues where `ISSDC = '3'` is equal to zero, it's a full grant. Similarly, we can replace the partial and remand methods; if it has both 1s and 3s it's a partial, and if it has 3s but no 1s, it's a remand.

Tasks identified — `task.created_at` within the period, where this is the first `task.created_at` with a given `task.appeal_id`.

Active users — Uniqued `task.user_id` of those tasks where `task.completed_at` is within the period. Note that this includes cancellations as well as successfully established claims.

Tasks started — `task.started_at` within the period.

Tasks completed — `task.completed_at` within the period where `task.completion_status` is equal to "completed" (0).

Completion rate — The percentage of tasks completed within the period (`task.completed_at`) where `task.completion_status` is equal to "completed" (0).

Time to claim establishment — The difference between the `FOLDER.TIOCTIME` time from VACOLS and the `task.completed_at` time in days for tasks completed within the period (`task.completed_at`) where `task.completion_status` is equal to "completed" (0).

Cancellations — `task.completed_at` within the period where `task.completion_status` is equal to "canceled" (1).

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in : UAT

Steps to Validate: 

1. Go to all of the listed links to see if their new locations have the their corresponding stat pages
2. Visit the "/stats/" page to see there is nothing there anymore. (sparking a 404?) @sharonwarner @lakohl 

Screenshots: 
<img width="1373" alt="screen shot 2017-03-14 at 9 46 46 am" src="https://cloud.githubusercontent.com/assets/23038505/23904037/dae8c336-089c-11e7-8e0c-5161d5519664.png">
<img width="1371" alt="screen shot 2017-03-14 at 9 47 29 am" src="https://cloud.githubusercontent.com/assets/23038505/23904038/db41a014-089c-11e7-9068-f950b9c74e6a.png">
<img width="1369" alt="screen shot 2017-03-14 at 9 48 18 am" src="https://cloud.githubusercontent.com/assets/23038505/23904034/d9e2aa4c-089c-11e7-87a1-600248eeb999.png">
<img width="1373" alt="screen shot 2017-03-14 at 9 48 46 am" src="https://cloud.githubusercontent.com/assets/23038505/23904035/da051172-089c-11e7-8cb9-3818af71aff3.png">
