### ISSUE TITLE
Non-ASCII characters in addresses

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#7911]
Japanese address had an invalid character, so the claim failed to establish. Note that I believe we need the addresses to match in the systems for the claim establishment to succeed.

Claim not established. System error with BGS. GUID: 283a1874-1793-43d3-bc04-7cc7cadf0e6f
An error occurred while establishing the claim: Unable to establish claim: insertBenefitClaim: AddressLine1 has invalid character(s)

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/260130/

Note - the particular intake above has resolved this by updating the Veteran's address.

This requires investigation:

* [ ] Does VBMS/BGS/CorpDB support multibyte encodings (UTF-8)?
* [ ] How do VBMS/BGS currently handle non-ASCII encodings? Transliteration?

Based on investigation, we can decide how to handle non-ASCII input.

**Comment by leikkisa** [comment]
Clarify with VBMS and VACOLS whether they support UTF-8.

**Comment by pkarman** [comment]
VACOLS does not support UTF-8.

VBMS (and assuming also CorpDB) does support UTF-8.

BGS may not (at the API level, even if CorpDB does support).

**Comment by pkarman** [comment]
See also #8643

**Comment by pkarman** [comment]
The VACOLS encoding issue is solved. I believe the only piece remaining here is verifying whether BGS supports UTF-8 and providing some work around if it does not. See the VACOLS solution in #11563 for one pattern to follow.

**Comment by leikkisa** [comment]
@msj0nes Closing this ticket since the existing issue was resolved, and if further issues come up we can create a new ticket to handle that one.
