### ISSUE TITLE
Fix 90-day evidence window task for Evidence Submission AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7916]
There are two AMA dockets that give appellants 90-days to submit evidence:
- Hearing docket - 90 days from the day of the hearing
- Evidence Submission docket - 90 days from the receipt date of the NOD

We'd like to create 90-day evidence window tasks for a few reasons:
1. Tasks populate currently active tasks in Case details and in Case timeline. With this task, users can easily see that a Veteran has a 90-day evidence window and no action can be taken until it completes
2. Veterans can choose to waive their 90-day evidence window. We can resolve this task as a way to track that they've elected to waive it
3. We can rely on the status of this task to know if a case is ready to be automatically distributed to a judge

## Notes
- This github issue only encompasses Evidence Submission docket cases. Hearing docket 90-day evidence window tasks will be created if a hearing has been held, and we have not yet implemented that functionality because AMA Hearings will not be held until ~April 2019.
- Subsequent github issues will also be created to handle the resolving of 90-day evidence window tasks if a Veteran decides to waive it, including which users have permission to act on these tasks.

## AC
- When an Evidence Submission appeal is established and a root task is created, also create a `90-day Evidence Window` task that begins with the `receipt_date` of the NOD and lasts for 90 days
- The `90-day Evidence Window` task blocks automatic case distribution
- The `90-day Evidence Window` task resolves to be closed/completed after 90 days

**Comment by laurjpeterson** [comment]
@amprokop - can i close this? do all newly established Evidence Submission appeals get this task?

**Comment by amprokop** [comment]
I reread the reqs for this — there's one piece missing — we set the timer for the task to be 90 days after the appeal is created in Caseflow, not 90 days after the receipt date. Sadly, I did not anticipate that need, and it will be some work to make it happen. 

What's the priority to make that change on your end?

**Comment by laurjpeterson** [comment]
Assuming established date is later than the receipt date, if we don't make the change then we could delay appeals from being distributed/worked/dispatched. I think it's pretty high priority for this to be accurate to meet AMA requirements. 

When do you think you'd be able to work on it / how long do you think it might take?

**Comment by lowellrex** [comment]
This work was completed by #9340.
