### ISSUE TITLE
`hearing.user` will always return nil if the judge does not have a CSS ID

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7918]
In Case Details (or in the hearings tooltip), we currently do not successfully fetch the information about hte judge that held a hearing in some cases.

Some judges in the Staff table in VACOLS do not have values for `sdomainid`(CSS ID), probably because they are no longer active judges and retired before VACOLS used CSS for authentication. See the judge with `sattyid: 017` as an example.

However, the way the hearing model is tied to the judge requires the css_id to be present:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/hearing.rb#L262

The vacols hearing row *does* have a field called `board_member` that corresponds to `sattyid` in the staff table, so we might need to use that to ensure we fetch information for judges that held hearings years ago.

See a bug report for an example: https://github.com/department-of-veterans-affairs/caseflow/issues/7915

# AC
- Fetch information for the judge that held a hearing, even if the judge does not have a CSS ID

**Comment by sharonwarner** [comment]
@amprokop 

Could you describe more where you're using this information? We use the css_id to match the judge in VACOLS to a user in our database when creating a hearing in our database. But, I believe it's only Hearing Prep that uses that functionality. 

If you need to get judge information for a VACOLS hearing, could we add another vacols_attr_accessor with the information you need?

**Comment by amprokop** [comment]
@sharonwarner - if you click into the bug report and then into the issue contained in there, it’ll have a screenshot and more details.

We’re using it in Case Search, so a user can put in a file number and look at all the appeals in Caseflow and VACOLS

**Comment by amprokop** [comment]
And ‘hearing.user’ is used in the legacy appeal serializer.

**Comment by amprokop** [comment]
Creating another vacols attr accessor is an option probably as well! Curious if @lowellrex has thoughts

**Comment by sharonwarner** [comment]
Ah, thanks! I see it now. Yes, I think adding another vacols accessor is the easiest solution. Any other solution would require database updates to either the hearing model or the user model.

**Comment by laurjpeterson** [comment]
@sharonwarner do you think this ticket is still relevant post-hearings refactoring?

**Comment by jimruggiero** [comment]
@lomaxap @pshahVA Is this ticket still relevant? See LP's comment above from May. Seems this one could be closed?

**Comment by pshahVA** [comment]
@ferristseng , do you think this may be irrelevant, I remember doing some refactor work to get all the judges from caseflow?

**Comment by ferristseng** [comment]
LP closed the related issue in February

```
See a bug report for an example: #7915
```

So I think it can be closed
