### ISSUE TITLE
Add link to correct issues (add/remove issues) from Case details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7920]
Part of [Editing AMA issues](https://github.com/department-of-veterans-affairs/caseflow/issues/5961)

When attorneys are viewing issues in Case details and they notice that the issues do not accurately reflect what the Veteran requested on their NOD, they need to add/remove issues to correct them.

The intake team has already deployed the ability to do this correcting, we just need to add a link in Case details for attorneys to do so.

Right now, only attorneys will do this editing, but it's possible other BVA users should have this permission in the future, like VLJ support, Lit Support, etc. I think we can put this behind a feature flag for now, but am open to other ideas - @mdbenjam what do you think?

## AC
- Link exists to correct issues, reading `Correct issues` per mocks
- When a user clicks the link, they navigate to the `/edit` URL for the case to add/remove issues (note: this link does not have `/queue` in it)
- When the user finishes adding/editing issues, they navigate back to the Case details page (note: this already works)

Tech notes:
1. an attorney can edit request issues before they checked out the case to the judge
2. a judge can edit a request issue before he/she finishes his/her checkout.

## Mocks
@allyceh to add

**Comment by laurjpeterson** [comment]
@mdbenjam - right now in prod, when i navigate to the caseflow intake add/remove issues link (the case details link minus `/queue` plus `/edit`, the Caseflow navigation has the Caseflow Intake logo. Is there a way to implement this with all of its functionality, but with the Caseflow "Queue" logo in the nav bar? This is so attorneys don't feel like they've left Caseflow or queue. (This might be cleanup down the line, but wanted to ask early.)

**Comment by mdbenjam** [comment]
This is probably not very straightforward, since we're within their app.
