### ISSUE TITLE
Are some commits not mentioned in the message being sent to #appeals-deployment?    

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7928]
At  3:40 am Eastern on November 19th, the #appeals-deployment message contains 

```
e07c7e5d Lowell Wood     Change display name of VLJ support team (colocated) (#7901)
```

—which is the commit that happened after `c7a9f47a0a08a72a196cdd4650020f8370fdf24e` 

Moving backwards, the last prod deployment message before that happened at 10:45 am Eastern on Nov 19th and ends with

```
d5d6a04b Anya Roltsch    Do not throw Sentry exception (#7888)
```

—which is the commit that happened directly before `c7a9f47a0a08a72a196cdd4650020f8370fdf24e`.

Why is `c7a9f47a0a08a72a196cdd4650020f8370fdf24e` missing from our deployment messages?

See https://github.com/department-of-veterans-affairs/caseflow/commits/master for the commit list.

**Comment by mdbenjam** [comment]
I think this either has been broken for a while, or was fixed and is broken again. For some reason I seem to remember that it might have to do with previous failed deployments making the next commit message incorrect. Not sure though.

**Comment by alisan16** [comment]
Closing this as it seems like it was fixed.
