### ISSUE TITLE
Add positive feedback to Attorney Evaluation Screen for AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7929]
When judges evaluate an attorney's decision, they also want to provide positive feedback for the attorney.

From Judge Vito Clementi:
> One of the things that I learned when I was studying motivational practices is that an organization’s staff will accept changes more easily if the management makes the change easy to do. Right now, all the ready to check boxes in the DAS are deficiencies. 

Updated, now that judges have finalized the additions

## Notes
- Legacy cases: we update the existing checkboxes in VACOLS
- AMA cases: we have the existing checkboxes in our DB. So, we should add these positive checkboxes to our DB and our UI

## Questions
- Should we scope this just to AMA cases, because of the complexity in some checkboxes being in VACOLS and positive checkboxes being in Caseflow? YES
- Should we ask Jed to add positive attorney feedback checkboxes to VACOLS?

## AC
- AMA appeals only to start
- Add the below positive feedback/checkboxes to the Attorney Evaluation screen, above the other check boxes.
- Add positive feedback to the backend

Heading: Identify positive feedback

- [ ] Responsive to contentions and theories
- [ ] Well-analyzed lay evidence
- [ ] Well-analyzed medical evidence
- [ ] Good hidden issue-spotting and analysis
- [ ] Concise, understandable, Veteran-centric writing
- [ ] Appropriate use of law, precedential opinion and administrative procedure
- [ ] Logically organized
- [ ] No substantive revisions
- [ ] Well proofed (no to minimal typos/grammar errors)
- [ ] Well-annotated file for VLJ review to include appropriate use of tags and comments
- [ ] Remand is concise and provides detailed, understandable directives

## Screenshots of current attorney evaluation screen checkboxes

<img width="1123" alt="Screen Shot 2019-08-15 at 5 24 12 PM" src="https://user-images.githubusercontent.com/27704093/63127862-884dd780-bf81-11e9-8ad6-eca5232bf115.png">

## Screenshot of tile of the screen

<img width="1130" alt="Screen Shot 2019-08-15 at 5 17 34 PM" src="https://user-images.githubusercontent.com/27704093/63127594-c0084f80-bf80-11e9-94cf-712915e1790c.png">

**Comment by allyceh** [comment]
Based on a conversation with @laurjpeterson and @sneha-pai , we determined this is "ready for dev" and does not require additional design investigation at this point. It would be a quick win and improvement for judges and attorneys. 

An engineer can add these checkboxes to the attorney evaluation page.

**Comment by laurjpeterson** [comment]
Hurrah! This was prioritized again by the Board! They're going to do another survey with judges to finalize the positive feedback to collect. When I hear back, I'll update the AC.

**Comment by laurjpeterson** [comment]
@carodew - We are giving judges the ability to select positive feedback on the Attorney Evaluation screen, when they check cases out to BVA dispatch. Since we already have the checkbox design, and we'd just be adding some more, I'd love to bypass a full design review if possible. I'd propose that we just add the heading "Identify positive feedback" and insert the checkboxes underneath, to the right of the other check boxes, since there is already so much white space.

@aroltsch - Check out my questions above. I don't think Foxtrot needs to implement this ticket, but would love your input on the AMA vs. Legacy cases only question.

This would be a really great quick win for the Board! It took almost a year for them to prioritize, then finalize adding positive feedback for attorneys!!

**Comment by carodew** [comment]
I'm ok without having a designer create a mock up although I'd recommend that the new options be added above or below the `Identify areas for improvement` section, rather than in a new column to the right. My hypothesis here is that it will be easier to miss if it's on the right rather than if someone is scrolling down the page. That said, I don't know how long this page already is. 

Is there a place in Caseflow demo where I could see the entire page (rather than just the detail screenshots above?). Then I could perhaps have a slightly more informed opinion.

**Comment by laurjpeterson** [comment]
Caseflow demo drill path:
- www.caseflowdemo.com
- switch user to Judge AAABSHIRE
- click Your Queue
- Review cases queue
- Click a case
- Click "Ready for dispatch"
- Follow the prompts until you get to the Evaluate Decision screen

Per discussion earlier, we should _not_ put these checkboxes on the right side. Instead they should be positioned above the Areas for improvement. Fixing AC

**Comment by laurjpeterson** [comment]
Moving to be ready for estimation.
