### ISSUE TITLE
Planning detailed training materials + planning training implementation for Compensation claims

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#7938]
After doing a feedback session with our users we identify that they always follow the steps they have been trained to do.  Creating this issue to make sure we have detailed material for training that is clear to our users and prevents intake mistakes.

[Here is a mural with all the notes from the User Feedback Session on 11/15/2018](https://app.mural.co/t/workqueue2001/m/workqueue2001/1542659894037/dc8037bf39d3216a729769437bb68fbf90f33d88)

**Comment by carolaponce** [comment]
Issue might be related
#747

**Comment by steve-gov** [comment]
Capturing in #8185.
