### ISSUE TITLE
Explore UI options to ask users to compare number of issues between form and intake

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#7939]
After doing a feedback session with our users we identify there is a lot of room for mistakes when finding and adding all previous issues. A hypothesis is asking users how many issues in intake + creating some logic to make sure there are all counted for.  This can also be solved with other ideas.  If time permits, I would like to create some design around this and test them out with users.

[Here is a mural with all the notes from the User Feedback Session on 11/15/2018](https://app.mural.co/t/workqueue2001/m/workqueue2001/1542659894037/dc8037bf39d3216a729769437bb68fbf90f33d88)

**Comment by msj0nes** [comment]
Closing this RAMP based ticket.
