### ISSUE TITLE
Verify that warmup_vacols.rb is actually necessary.

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#7947]
We've had some questions about whether VACOLS connection warmup, introduced in https://github.com/department-of-veterans-affairs/caseflow/pull/813, is necessary.

See https://github.com/department-of-veterans-affairs/appeals-deployment/issues/156#issuecomment-282084887 for some context.

At some point, we may want to try a deploy without a VACOLS connection warmup and observe if new traffic is slowed down by connection throttling.

# AC
- Run a deploy under load with VACOLS connection warmup disabled and observe if there is any effect on user traffic

**Comment by alisan16** [comment]
Closing this as it hasn't been updated in a year
