### ISSUE TITLE
Trial release notes using Headway app

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7954]
# Introduce updates/release notes using Headway app

## Our team's goals
- Better and more frequently communicate new features and our shareable roadmap to users (not just BVA stakeholders)
- Allow non-engineering Caseflow team members to push updates 
- Retain Github as the source of truth for requirements and user-facing/release notes messaging 
- Project a clear, consistent voice for user-facing messaging - this is important because multiple team members will update Headway

## Stakeholder goals
- Their employees can find what's new quickly and easily
- Their employees are not surprised

## Hypotheses
- Internal team members (support and engineering) can find value in the exact same messaging that our users and stakeholders need, per feature
- We can maintain our daily deploys while having release notes/updates

## How we want to use Headway
- **Align on user-facing messaging/style** 
   - Include a user-facing, release notes-like sentence about the feature/user story in the github issue(s) so product managers have an early draft of what to be included in release notes. (Note: these statements can be used in stakeholder-facing decks, too)
- **Use Sprint Review/Sprint Priorities meeting as an early signal to what's coming.** 
   - This will ensure stakeholders understand what's coming in, even if we don't message before a deploy 100% of the time
   - Product managers work with tech leads (or somewhere else) to see what will be deployed each day
   - Monitor the appeals-build channel.
- **Product managers update Headway for the product(s) they manage** 
- **Send email to BVA Stakeholders with the Headway link for users to access** 
    - (Stakeholders include: John, Jennifer, DVCs)
- **There will be slack integration (Maybe the product channel) to let other PM's know when an update has been added to the headway app.**

## How to write release notes - TODO
(and how it differs from or is included in epics, stories)
-Include the release notes text that is in the ticket.
-Make sure that it is clearly indicated if this feature is only available to certain roles.
-Screenshots will always help the user.

What to include:
- Features that users find valuable.

What we can exclude:
- Certain refactoring efforts or bug fixes that we thoughtfully agree users won't find value in (or might get confused with) 

## Headway features
- Insert widget into our app

## Non-Headway features
- Emailing users (or defined groups of users)when there are updates
- Showing updates depending on a group of users (e.g. judges, VSOs getting their own updates)

---
# Archive

## Idea
- Re-enable the What's New page
- Create a copy.json like file that non-engineering teammates can update whenever
- Whenever the What's New page is updated, add a notification/signal that there is new information
- When the user clicks into the What's New page, remove that notification/signal
- When a user clicks a product link, the page scrolls to that product's section

## Open Questions
- Do we want a "What's Next?" section per product?
- Could this just be an HTML page for easy upkeep?

## Prototype
<img width="765" alt="screen shot 2018-11-27 at 6 10 56 pm" src="https://user-images.githubusercontent.com/27704093/49117741-d003c600-f26f-11e8-9c05-00ab4e1f711c.png">

See `What's new / What's next` mural (link not included to avoid anonymous edits).

**Comment by sunil-sadasivan** [comment]
Any thoughts on using https://headwayapp.co/.   The main thing to make sure of is whether headwayapp.co is available on the VA network.  This could be a nice, lean way to get this in without much developer effort.

**Comment by laurjpeterson** [comment]
Thanks for sharing! A quick look - it doesn't look like the free version would allow us to group the changes by Caseflow product. We could consider having a changelog per product (Queue, Reader, Hearing Prep, Hearing Schedule, Intake, etc.), perhaps.

**Comment by pkarman** [comment]
Talked with @pshahVA about this idea. We agree getting communications about changes to Caseflow directly into users' hands is the best UX.

Open to using headwayapp.co if it will meet our needs and there are no VA obstacles. I'm not sure what "available on the VA network" means in this context @sunil-sadasivan -- do you mean that someone using Caseflow in production can also access that domain? I just confirmed I can via my GFE.

I'm not sure what is involved in the integration piece. We should be thinking about the UX first, IMO, and then pick a tool that achieves that. I am imagining some kind of "what's new" navbar dropdown that shows an alert icon whenever I have unread updates.

**Comment by pshahVA** [comment]
@sneha-pai I wanted to get design input on something like this.

**Comment by pshahVA** [comment]
I wanted to bring this thread back to life.  Would it make sense to use the trail version of this to see how it works.  I am not pointing to any particular solution, but I don't really know of any other better alternatives. I don't like the idea of custom coding as we have lots of release work to be done.

**Comment by laurjpeterson** [comment]
Agree! Let's get the trial version.

**Comment by pkarman** [comment]
Fine with me to try the trial version. What do you need from engineering? Going to unassign myself for now.

**Comment by pshahVA** [comment]
I've reached out to headway to see if we can get a trial version to try it our in production.
