### ISSUE TITLE
Case details | Redesign request issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7957]
Part of [Editing AMA issues](https://github.com/department-of-veterans-affairs/caseflow/issues/5961)

Now that we're introducing the ability to add decision issues to AMA appeals, we want to introduce a new design that will show both contested issues (request issues) from the Veteran's NOD alongside decision issues, that the attorney is deciding. 

## AC
- The banner `Issue` exists above each `request_issue`
- For each issue, we display the issue description, benefit type, diagnostic code, and note.

## Mocks
Issues: No dispositions
Latest updates: 
- Changed "contested issue" header in grey box to "issue"
- Added diagnostic code to each request issue

![image](https://user-images.githubusercontent.com/40216950/50249701-c2dc8180-03ac-11e9-9a78-37bbda72e579.png)

Issues: With dispositions
Latest updates: 
- Changed "contested issue" header in grey box to "issue"
- Added diagnostic code to each request issue
- Added link icon with copy to call out decisions that are connected to more than one request issue

![image](https://user-images.githubusercontent.com/40216950/50249751-e0115000-03ac-11e9-9b0e-270f25cbbd89.png)

Issues: Shows decision with different benefit type
Latest update: 
- Example mock that displays decision issue with different benefit type, for reference

![image](https://user-images.githubusercontent.com/40216950/50249807-08994a00-03ad-11e9-84ba-9716627fb758.png)

**Comment by allyceh** [comment]
@mdbenjam @aroltsch Re-opened, updated mocks + ACs.
