### ISSUE TITLE
Case details: Revisit "About the Appellant" section 

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#7960]
Feedback from BVA dispatch pilot: 

For RAMP cases (when the veteran is the appellant), we are displaying the veteran's name and address twice: once in the About the Veteran section and once in the About the Appellant section. It felt repetitive for BVA Dispatch users to display the veteran's name and address twice. 

Proposed solutions to streamline this in Case Details: 
Option 1 (preferred): When the veteran is the appellant and there are no additional appellants, hide the About the Appellant section from the Case Details page. When there are additional appellants, display this section with their info. 
Option 2: When the veteran is the appellant and there are no additional appellants, display some copy in the About the Appellant section that says that there are no additional appellants or "none". When there are additional appellants, display their info.

**Comment by laurjpeterson** [comment]
option 1 captured in this gh issue - https://github.com/department-of-veterans-affairs/caseflow/issues/8628

**Comment by laurjpeterson** [comment]
Closing because we've captured this in another issue.
