### ISSUE TITLE
Syncing end products if file number changes

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#7961]
A Veteran can have more than one file number. BGS has been cleaning this up, meaning that the file number we have on record might not have all of the relevant information anymore, such as end products, which breaks syncing the end products.

We can get the Veteran's ssn from the participant_id, and then the new file number with the following calls: 
find_person_by_ptcpnt_id (in BGS)
fetch_file_number_by_ssn

We could update the file number, or choose to sync the end product using BGS's find_claim_detail_by_id (which shows multiple steps in the claim's history).

**Comment by laurjpeterson** [comment]
@leikkisa is this ticket still relevant?

**Comment by pkarman** [comment]
Probably still relevant. The new `VeteranFinder` class probably will help with resolving this because it finds all incidents of a Veteran by participant_id.

**Comment by leikkisa** [comment]
Closing as dupe of https://github.com/department-of-veterans-affairs/caseflow/issues/7734
