### ISSUE TITLE
Create add decisions page with request issues + decision issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7965]
Part of [Editing AMA issues](https://github.com/department-of-veterans-affairs/caseflow/issues/5961)

After an attorney has added decision issues in the modal, we should display them back on the `Add decisions` page in the checkout flow.

## AC
- Users can see both request issues and the decision issues they are connected to in the `Add decisions` page
- All decision issues also display a disposition (allowed, remanded, etc.)
- If the user adds one decision to many request issues, display the decision under all issues to which it's added. Also display a link icon + "Added to # issues" in each instance of the decision.
- When the user tries to "Continue" without adding a decision, display an error message.
- When the benefit type on the decision issue differs from the benefit type on the request issue, display the update benefit type to the user for reference. Example: Request issue is Compensation, and user adds an Education decision issue. Display "Education" in decision issue. 
  - If the benefit type on decision issue does not differ from the benefit type on the request issue, don't don't display benefit type in the decision issue. (Note: This will be the case 99% of the time.) 

## Mocks

Latest updates: 
- Added diagnostic code field to each request and decision issue
- Added Delete button to the left of Edit button to delete the decision issue

![image](https://user-images.githubusercontent.com/40216950/50249195-50b76d00-03ab-11e9-8b96-ead49381e951.png)

**Comment by allyceh** [comment]
@mdbenjam @aroltsch Re-opened and updated AC + mock.

**Comment by aroltsch** [comment]
Opened a new ticket
