### ISSUE TITLE
Edit/remove decision issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7966]
Part of [Editing AMA issues](https://github.com/department-of-veterans-affairs/caseflow/issues/5961)

**Editing decision issues**
- As an attorney, I need the ability to **delete/remove a new decision issue** that I've added by mistake so that I can fix any accidental errors. 
- As an attorney, I need the ability to **edit a new decision issue** that I've created so that I can fix any accidental errors. 

## AC
- An `Edit` and `Delete` link is displayed next to the decision issue on the `Add decisions` page
- When the user clicks `Edit`, a modal titled `Edit decision` pops up. This modal has the same design as the `Add decision` modal. 
  - The existing decision description, disposition, and benefit is pre-populated in the `Edit decision` modal. 
  - The user can edit the description and change the disposition. 
  - When the user clicks Save, they navigate back to the `Add decisions` page and the edited decision issue displays.
- When the user clicks `Delete`, a confirmation modal pops up.
  - If the user confirms that they want to delete the decision, all of the decision issue information (description, disposition, benefit type) is cleared and removed from the Add decisions page. 
  - If the user deletes a decision issue that's connected to more than one request issue, we remove all instances of that decision that are connected to request issues. 

## Mocks

Editing decision for one issue. All other issues have decisions. 
Latest updates (reflected below): 
- Removed delete button
- Added diagnostic code field
- Revised hierarchy of fields

![image](https://user-images.githubusercontent.com/40216950/50248578-79d6fe00-03a9-11e9-85f8-ce2e06633189.png)

Editing decision for one issue. Issues that don't have decisions appear in drop down. 
Latest updates: 
- Removed delete button
- Added diagnostic code field
- Revised hierarchy of fields
- Updated copy and styling of "Do you want to add this decision to other....?" section at the bottom.

![image](https://user-images.githubusercontent.com/40216950/50248671-d5a18700-03a9-11e9-8857-aedd31547199.png)

Editing decision for 2+ issues. All other issues have decisions. 
Latest updates: 
- Removed delete button
- Added diagnostic code field
- Revised hierarchy of fields

![image](https://user-images.githubusercontent.com/40216950/50248801-39c44b00-03aa-11e9-8a89-c9f4222890de.png)

Editing decision for 2+ issues. Issues that don't have decisions appear in drop down.
Latest updates: 
- Removed delete button
- Added diagnostic code field
- Revised hierarchy of fields
- Updated copy and styling of "Do you want to add this decision to other....?" section at the bottom.

![image](https://user-images.githubusercontent.com/40216950/50248832-4cd71b00-03aa-11e9-8a18-c2e4193dd33f.png)

Modal for deleting one decision issue

![image](https://user-images.githubusercontent.com/40216950/50250011-adb42280-03ad-11e9-861a-fc507f6b85f4.png)

Modal for deleting 2+ decision issues 

![image](https://user-images.githubusercontent.com/40216950/50250028-bc9ad500-03ad-11e9-8c1f-044887a723b2.png)

**Comment by mdbenjam** [comment]
@allyceh In the future, I think it might be easier to create these updates as separate tickets. That way we keep a record of what was originally done, which I think will help other people pick up the tickets.

**Comment by allyceh** [comment]
@mdbenjam Will do!

**Comment by aroltsch** [comment]
Opened a new ticket
