### ISSUE TITLE
Reassign cases to other vlj-support staff

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7973]
When I assigned users to the VLJ support organization (`organizations/vlj-support-staff/users`), I added Rolandus and Jack to the list. However, since they are supervisors, they should not be receiving any cases during the round robin assignment. 

## AC
- Reassign cases that are currently assigned to Rolandus (bvarbranch) and Jack (bvajkenner) to other members of the VLJ support team

**Comment by lowellrex** [comment]
## Additional AC
* Allow VLJ staff to reassign tasks to members of the same team.

**Comment by lowellrex** [comment]
The additional work to allow VLJ support staff to reassign tasks to other members of the same team will be completed in #7999.
