### ISSUE TITLE
AMA Intake | Let request issues contest decision issues (as well as rating issues)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7978]
In order to chain request issues that don't have rating issues, we need decision issues to be contestable directly.

<img width="1151" alt="screen shot 2018-11-26 at 1 51 15 pm" src="https://user-images.githubusercontent.com/1596259/49037159-89d33780-f187-11e8-821b-9d1a294d145b.png">
<img width="1156" alt="screen shot 2018-11-26 at 1 51 28 pm" src="https://user-images.githubusercontent.com/1596259/49037168-8d66be80-f187-11e8-8061-d28f695dfa37.png">
<img width="1152" alt="screen shot 2018-11-26 at 1 51 34 pm" src="https://user-images.githubusercontent.com/1596259/49037171-8e97eb80-f187-11e8-9932-fc4d63c6f816.png">

## Acceptance Criteria
- When intaking or editing issues on a decision review, if there are any prior completed decision reviews with decision issues that are **not** connected to a rating issue, those issues should show up in the first modal of the Add Issues flow (the one in the presentation panel above).

- Those issues that appear on the Add Issues flow should be scoped by the selected benefit type. (i.e. if "Pension is selected as the benefit type, only prior "Pension" decision issues should show up). If the decision review is an a appeal, all benefit types should be included.

- If the decision issue was connected to a rating EP. Put the decision issue in the same list as the rest of the rating issues that are part of the rating associated with that EP.

- If the decision issue was not connected to a rating EP put them under a separate "Past decisions from [date]" section. Where [date] is the approximate decision date of the decision issue. (see https://github.com/department-of-veterans-affairs/caseflow/issues/7982)

- The copy for those issues should be as follows:
   - If there is a custom written appeals decision description, use that. If not,
      - If request issue does not have notes:
      "[Disposition] - [Request issue description]"
      - If request issue has notes:
      "[Disposition] - [Request issue description]. Notes: [Request issue notes]"

- The following existing validation patterns should apply to prior non-rating issues:
  - Multiple active issues reviewing the same non-rating decision should be ineligible (https://github.com/department-of-veterans-affairs/caseflow/issues/7291)
  - If HLR, then issues reviewing prior non-rating HLR decisions should be ineligible (https://github.com/department-of-veterans-affairs/caseflow/issues/7293)

## Technical Notes
It's also possible we want to store the decision issue of the contested rating issue if it exists. Not required, but worth considering.

requires https://github.com/department-of-veterans-affairs/caseflow/issues/7982

**Comment by jiahuang** [comment]
Also need to fix DTA supplemental claims

**Comment by jiahuang** [comment]
> completed decision reviews

Q: what's a completed decision review? Decision Review that has a cleared EP?

> Those issues that appear on the Add Issues flow should be scoped by the selected benefit type. 

Q: Do we figure out benefit type based on the disposition text?

> if the decision issue was connected to a rating EP. Put the decision issue in the same list as the rest of the rating issues that are part of the rating associated with that EP.

 Q: Wouldn't this result in two issues side by side that look really similar to the end user?

## Implementation thoughts
### Db changes
* drop dispositions from request issues. this is now handled by decision issues

### DTA errors
* add back in the on_sync for hlr creating a supp claim, but this time look at the disposition from decision issues

### DecisionReview.rb
* add `has_many :decision_issues, as: :decision_review`
* Add serialized decision issues to the UI hash

There's a few different options for surfacing decision issues on the UI. We can split up decision issues w/ associated ratings on the frontend or backend. Backend would look something like: 
* add a `def decision_issues_without_ratings` which returns list of decision_issues not associated with ratings
* add a `def serialized_decision_issues_without_ratings` which serializes `decision_issues_without_rating_issues` into a format that the UI expects for displaying ratings (needs to be keyed by decision date, which is currently end_product sync date. This might also need to be fixed)
* do a similar thing but for decision_issues_with_rating, only that just returns an array that's not keyed by date

frontend would be:
* send full array of decision issues to frontend
* frontend splits it into 2 arrays in the react store (or doesn't split it and its the responsibility of the controller to figure it out)

### Frontend
* make formatRatings in `util/issues.js` take in a new array for decision issues w/ associated ratings & format the ratings list to include decision issues
* update ui to reflect new disposition copy text

**Comment by shanear** [comment]
looks good for a nonrating issue:

```
[#<RequestIssue:0x000055c2efbe0728
  id: 1166,
  review_request_type: "SupplementalClaim",
  review_request_id: 337,
  rating_issue_reference_id: nil,
  rating_issue_profile_date: nil,
  contention_reference_id: 315577,
  description: nil,
  issue_category: nil,
  decision_date: nil,
  disposition: nil,
  end_product_establishment_id: 781,
  removed_at: nil,
  rating_issue_associated_at: nil,
  parent_request_issue_id: nil,
  notes: "",
  is_unidentified: nil,
  ineligible_due_to_id: nil,
  untimely_exemption: nil,
  untimely_exemption_notes: nil,
  ineligible_reason: nil,
  ramp_claim_id: nil,
  decision_sync_submitted_at: nil,
  decision_sync_attempted_at: nil,
  decision_sync_processed_at: nil,
  decision_sync_error: nil,
  vacols_id: nil,
  vacols_sequence_id: nil,
  created_at: Thu, 31 Jan 2019 21:43:49 UTC +00:00,
  benefit_type: "compensation",
  contested_decision_issue_id: 51,
  veteran_participant_id: "600237126",
  contested_rating_issue_diagnostic_code: nil,
  decision_review_type: "SupplementalClaim",
  decision_review_id: 337,
  contested_rating_issue_reference_id: nil,
  contested_rating_issue_profile_date: nil,
  contested_issue_description:
   "Denied: Active Duty Adjustments - test contention",
  nonrating_issue_description: nil,
  unidentified_issue_text: nil,
  contested_rating_issue_disability_code: nil,
  last_submitted_at: nil>]
```

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-01-31 13 43 57" src="https://user-images.githubusercontent.com/1596259/52087595-c09a4500-255e-11e9-8ce0-1ee600cc0dfd.png">

**Comment by shanear** [comment]
```
  contested_rating_issue_diagnostic_code: nil,
  decision_review_type: "SupplementalClaim",
  decision_review_id: 339,
  contested_rating_issue_reference_id: "123139",
  contested_rating_issue_profile_date: "2019-01-16T15:18:59-06:00",
  contested_issue_description:
   "Evaluation of PTSD, which is currently 50 percent disabling, is continued.",
  nonrating_issue_description: nil,
  unidentified_issue_text: nil,
  contested_rating_issue_disability_code: "9411",
```
Works for rating issue too, but very confused why we have `contested_rating_issue_diagnostic_code`

**Comment by shanear** [comment]
> If the decision issue was connected to a rating EP. Put the decision issue in the same list as the rest of the rating issues that are part of the rating associated with that EP.

This is not working properly. Informed @leikkisa and she's gonna fix it in a follow up PR.

**Comment by shanear** [comment]
<img width="586" alt="screenshot 2019-02-04 09 56 09" src="https://user-images.githubusercontent.com/1596259/52227041-51c13280-2863-11e9-9e38-2fb9c625026e.png">

<img width="1552" alt="screenshot 2019-02-04 09 57 09" src="https://user-images.githubusercontent.com/1596259/52227044-54238c80-2863-11e9-9dcf-e5edca4d7662.png">

```
#<RequestIssue:0x000056509ed469b8
  id: 1203,
  review_request_type: "SupplementalClaim",
  review_request_id: 352,
  rating_issue_reference_id: nil,
  rating_issue_profile_date: nil,
  contention_reference_id: 315778,
  description: nil,
  issue_category: nil,
  decision_date: nil,
  disposition: nil,
  end_product_establishment_id: 813,
  removed_at: nil,
  rating_issue_associated_at: nil,
  parent_request_issue_id: nil,
  notes: "",
  is_unidentified: nil,
  ineligible_due_to_id: nil,
  untimely_exemption: nil,
  untimely_exemption_notes: nil,
  ineligible_reason: nil,
  ramp_claim_id: nil,
  decision_sync_submitted_at: nil,
  decision_sync_attempted_at: nil,
  decision_sync_processed_at: nil,
  decision_sync_error: nil,
  vacols_id: nil,
  vacols_sequence_id: nil,
  created_at: Mon, 04 Feb 2019 17:56:31 UTC +00:00,
  benefit_type: "compensation",
  contested_decision_issue_id: 110,
  veteran_participant_id: "600247069",
  contested_rating_issue_diagnostic_code: nil,
  decision_review_type: "SupplementalClaim",
  decision_review_id: 352,
  contested_rating_issue_reference_id: nil,
  contested_rating_issue_profile_date: nil,
  contested_issue_description:
   "Denied: Service connection for back is granted with an evaluation of 30 percent effective January 1, 2017.",
  nonrating_issue_description: nil,
  unidentified_issue_text: nil,
  contested_rating_issue_disability_code: nil,
  last_submitted_at: nil>,
 #<RequestIssue:0x000056509ed465f8
  id: 1202,
  review_request_type: "SupplementalClaim",
  review_request_id: 352,
  rating_issue_reference_id: "123803",
  rating_issue_profile_date: Fri, 01 Feb 2019 05:00:00 UTC +00:00,
  contention_reference_id: nil,
  description: nil,
  issue_category: nil,
  decision_date: nil,
  disposition: nil,
  end_product_establishment_id: 812,
  removed_at: nil,
  rating_issue_associated_at: nil,
  parent_request_issue_id: nil,
  notes: "",
  is_unidentified: nil,
  ineligible_due_to_id: nil,
  untimely_exemption: nil,
  untimely_exemption_notes: nil,
  ineligible_reason: nil,
  ramp_claim_id: nil,
  decision_sync_submitted_at: nil,
  decision_sync_attempted_at: nil,
  decision_sync_processed_at: nil,
  decision_sync_error: nil,
  vacols_id: nil,
  vacols_sequence_id: nil,
  created_at: Mon, 04 Feb 2019 17:56:31 UTC +00:00,
  benefit_type: "compensation",
  contested_decision_issue_id: 117,
  veteran_participant_id: "600247069",
  contested_rating_issue_diagnostic_code: nil,
  decision_review_type: "SupplementalClaim",
  decision_review_id: 352,
  contested_rating_issue_reference_id: "123803",
  contested_rating_issue_profile_date: "2019-02-01T13:32:24-06:00",
  contested_issue_description:
   "Evaluation of Spine, which is currently 30 percent disabling, is increased to 40 percent effective December 12, 2018.",
  nonrating_issue_description: nil,
  unidentified_issue_text: nil,
  contested_rating_issue_disability_code: nil,
  last_submitted_at: nil>
```

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-02-04 13 03 38" src="https://user-images.githubusercontent.com/1596259/52237023-4e3aa500-287d-11e9-8bf1-af6cca337797.png">

Welp, i closed this one too soon. This isn't working for non comp issues

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-02-05 15 08 10" src="https://user-images.githubusercontent.com/1596259/52310338-e86f1b80-2957-11e9-9bf2-f82d58ebc5b1.png">
woohoo works
