### ISSUE TITLE
AMA Intake | Use different EP labels for Pension HLRs and SCs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7984]
Pension HLRs and SCs will need to use different labels than Compensation so they can be routed properly.

## Acceptance Criteria
- If "Pension" was selected as the benefit type for a HLR or SC intake, when the intake is completed, the EPs created should have the appropriate PMC EP codes (see the table below)
- When a request issue on an HLR or SC with the benefit type of "Pension" has a duty to assist error, the resulting EP should use the appropriate PMC EP code below.

## Notes

If it's easy, update the EP labels displayed on the confirmation pages with the labels below

| Pension EP Code | Definition  |
| ------------- | ------------- | 
 030HLRNRPMC | PMC Higher-Level Review Non-Rating |
| 030HLRRPMC | PMC Higher-Level Review Rating |
| 040BDEIMOPMC | PMC Board DTA Error - w/IMO |
| 040HDENRPMC | PMC HLR DTA Error - Non-Rating |
| 040HDERPMC | PMC HLR DTA Error - Rating |
| 040SCNRPMC | PMC Supplemental Claim Non-Rating |
| 040SCRPMC | PMC Supplemental Claim Rating |

## Background
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1032

**Comment by steve-gov** [comment]
First two codes validated (created a NR-HLR and a R-HLR for Veteran 123458314): 

<img width="434" alt="screen shot 2019-01-03 at 11 13 50 am" src="https://user-images.githubusercontent.com/25468689/50656807-3e136b00-0f49-11e9-860a-d99ddf83fa28.png">
<img width="478" alt="screen shot 2019-01-03 at 11 15 57 am" src="https://user-images.githubusercontent.com/25468689/50656808-3e136b00-0f49-11e9-9f8d-eaaf00cbf1d1.png">

**Comment by steve-gov** [comment]
Contacted Nate for help with validating `040HDERPMC` and `040HDENRPMC`. Will leave it to @shanear to validate `040BDEIMOPMC`.

**Comment by leikkisa** [comment]
040BDEIMOPMC actually has it's own ticket, so it's not part of this one.
https://github.com/department-of-veterans-affairs/caseflow/issues/6167

**Comment by steve-gov** [comment]
Otherwise validated; will close and validate 6167 when it comes up.
