### ISSUE TITLE
Non-Comp Intake | Don't create EP for non-VBMS HLRs and SCs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7985]
Compensation and Pension use VBMS to process HLRs and SCs. Other business lines do not, thus we should not create EPs for those. Instead we will use the DB objects directly in the Caseflow non-comp UI.

## Acceptance Criteria
When processing the intake of an HLR or SC, and the benefit type is not "Compensation" or "Pension":
- No rating issues should show in the first modal of the Add Issue flow. This means the first modal should only show up when there are prior completed decision issues for that benefit type (see: #7978)
- The "Establish EP" button should instead say "Establish Higher-Level Review" or "Establish Supplemental Claim" (depending on the form).
- When the "Establish [form]" button is clicked. No end products or contentions should be created.

## Technical Notes
- We may need to look at any logic for HLRs or SCs that assumes the presence of at least one `EndProductEstablishment`, as this is no longer guaranteed.

requires #7978

**Comment by steve-gov** [comment]
Bullet 1 validated for HLR and SC.

Bullet 2 validated for HLR and SC.

<img width="938" alt="screen shot 2019-01-03 at 3 46 39 pm" src="https://user-images.githubusercontent.com/25468689/50667608-015a6a80-0f6f-11e9-9a17-e4bd5873b616.png">

Bullet 3 is technical and assumed correct.
