### ISSUE TITLE
Non-comp Intake | Redirect to reviews page on complete

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7987]
Compensation and Pension use VBMS to process HLRs and SCs. Other business lines do not, thus we should not create EPs for those. Instead we will use the DB objects directly in the Caseflow non-comp UI. A full page success message is unnecessary and it's more intuitive to redirect directly to the non-comp reviews page. 

## Acceptance Criteria
- When the intake of an HLR or SC is completed, and the benefit type was not "Compensation" or "Pension", redirect to the "In Progress" tab on the reviews page described in #7990. It should have a condensed success message (see the mocks below)

## Copy
Intake Completed
[claimant name] (Veteran SSN: [veteran ssn]) [form name] has been processed.

requires #7990

**Comment by carolaponce** [comment]
Updated Mock

![confirmation to disposition](https://user-images.githubusercontent.com/11700545/49259304-b4262e80-f3ed-11e8-849f-72720b2beeb7.png)

**Comment by carolaponce** [comment]
![confirmation - disposition copy](https://user-images.githubusercontent.com/11700545/49621661-578dbb00-f97b-11e8-9a07-aaa7c599eee2.png)

**Comment by shanear** [comment]
may want to take a look at the solution here since just a link vs a redirect

**Comment by steve-gov** [comment]
Validated:

<img width="854" alt="screen shot 2019-01-23 at 4 49 06 pm" src="https://user-images.githubusercontent.com/25468689/51646900-65010380-1f2f-11e9-8f36-e97dada8030b.png">

![screencapture1](https://user-images.githubusercontent.com/25468689/51646896-62061300-1f2f-11e9-9909-0e8874b4d542.gif)
