### ISSUE TITLE
SPIKE: Can we change ROJ in VACOLS?

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#799]
Can we change the ROJ in VACOLS safely, without loosing existing data?

It seems like RO's are already doing this, so we probably should be able to.

If it's determined that we can, we should be creating a story for updating the ROJ in the case of certain special issues.

**Comment by lakohl** [comment]
@shanear from a UX perspective we def can do this. We need to figure out the technical feasibility. Assigning this to you.
