### ISSUE TITLE
Non-comp Flow | Search bar on reviews page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7991]
There is a search bar on the non-comp reviews landing page which will be used to easily locate a decision review to take action on.

Full non-comp flow: https://va-gov.invisionapp.com/share/PFPCPJ7MEGC

## Acceptance Criteria
- When a user types characters into the search bar on the non-comp reviews page, it should filter the list of review tasks based on the content in the search bar. It should show any review tasks where the claimant name or ssn contains the string of characters inside the search bar. Whitespace characters beginning or trailing the content should be ignored.
- This should work on both the "In Progress" and "Completed" tabs.

## Technical Notes
- one suggestion: we could filter by creating new searches, not filtering the current page state, as we will be adding pagination in the future and the current page state won't contain all searchable review tasks.

requires #7990
requires #7996

**Comment by carolaponce** [comment]
Updated comp
![returning disposition main copy 2](https://user-images.githubusercontent.com/11700545/49258662-1893be80-f3eb-11e8-969b-e80399e1a7df.png)

**Comment by carolaponce** [comment]
Final mock. Also deleting previous to avoid any confusion.

![returning disposition main copy 2](https://user-images.githubusercontent.com/11700545/49620833-82761000-f977-11e8-8242-3bb1bedf48a7.png)

**Comment by kencheeto** [comment]
@carolaponce this mock looks like it's for the Type filtering, not the search bar. I don't think we need a mock for the search bar specifically if we can use http://www.caseflowdemo.com/styleguide#search and assume that there is no additional styling/behavior

**Comment by kencheeto** [comment]
@carolaponce looking for a gif recorded with licecap that shows how typing affects the list items

**Comment by carolaponce** [comment]
A few extra specs:
Purpose of Search - Give users the ability to quickly search this table, using any content.  Same functionality as Reader (screenshot attached).  
Highlight is a nice to have.
<img width="1116" alt="screen shot 2018-12-17 at 12 57 08 pm" src="https://user-images.githubusercontent.com/11700545/50126799-49655780-0223-11e9-8edd-57f2d55a1e72.png">

**Comment by carolaponce** [comment]
Related: empty search message
#1101

**Comment by steve-gov** [comment]
Validated:

![screencapture](https://user-images.githubusercontent.com/25468689/50792831-4bf02580-1294-11e9-9529-ecffa6fbfadd.gif)
