### ISSUE TITLE
Non-comp Flow | Toggle sort by "Days Waiting" and "Date Completed"

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7992]
On the non comp reviews page, it's useful to be able to sort by days waiting to know which tasks are newest or oldest.

Full non-comp flow: https://va-gov.invisionapp.com/share/PFPCPJ7MEGC

## Acceptance Criteria
- For the In Progress tab, there should be a sort icon next to the "Days Waiting" column on the reviews page. When the column header is clicked, it should toggle between sorting the reviews by ascending and decending days waiting.
- Reviews on the page should be sorted in ascending order by "Days Waiting" by default (fewer days is at the top)
- For the Completed tab, there should be a sort icon next to the "Date Completed" column on the reviews page. When the column header is clicked, it should toggle between sorting the reviews by chronological order to reverse chronological order.
- Reviews on the page should be sorted in reverse chronological order by "Date Completed" by default (most recently completed at the top)

requires #7990
requires #7996

**Comment by pkarman** [comment]
covered by #8539

**Comment by steve-gov** [comment]
@pkarman In UAT default sort on both tabs is by Claimant as opposed to the order spec'ed in the acceptance criteria. Maybe a quick fix that doesn't require moving columns?

**Comment by pkarman** [comment]
Hm. The "Completed" sort should be by `completed_at` datetime. https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/decision_reviews_controller.rb#L38

Maybe it's just the visual cue that's the same (the column arrows)? Is it the actual data that is ordered by claimant name?

**Comment by pkarman** [comment]
Confirmed it is the visual cue only. PR in #8589

**Comment by pkarman** [comment]
We share code with the queue team, so the column text change needs their 👀 . I opened a PR and pinged them.

The default sort cue is totally my bad -- fixed in that same PR #8637

**Comment by pkarman** [comment]
This should be ready now.

**Comment by steve-gov** [comment]
Woo hoo!
