### ISSUE TITLE
Non-comp Flow | Decision page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7994]
For each non-comp HLR and SC, the users need a way to record the decision being made for each request issue.

Full non-comp flow: https://va-gov.invisionapp.com/share/PFPCPJ7MEGC

## Acceptance Criteria
- On the non-comp reviews page, the claimant name should be a link to the dispositions page for that review.
- The disposition page should look like the mock below, it should show each issue on the review, and have a dropdown to select the disposition, as well as a place to write an optional decision description.
- When the "Edit Issues" button is pressed, it should redirect the user to the edit issues page for that decision review.
- When "Cancel" is pressed, it should redirect the user back to the reviews landing page.
- The decision date should default to today's date.

## Notes
Disposition Options:
Granted
Denied
DTA Error
Dismissed
Withdrawn

Out of scope:
- The "Complete" button

## Technical notes

We could likely reuse some Queue components here - the mock is based on LegacySelectDispositionsView

## Copy
There are some changes to the copy in the mocks:
'Decision' at the top to 'Select Dispositions'

## Mocks
*Higher-Level Review*
![disposition main - hlr](https://user-images.githubusercontent.com/11700545/49259068-b045dc80-f3ec-11e8-8b98-f50f1ce6ee6e.png)

*Higher-Level Review, selecting disposition*
![disposition main - hlr dd](https://user-images.githubusercontent.com/1596259/49190848-11fd3c80-f342-11e8-95be-99fcf03ba3cf.png)

*Supplemental Claim*
![disposition main - sc](https://user-images.githubusercontent.com/11700545/49259067-b045dc80-f3ec-11e8-8b24-e53d755fe9f0.png)

requires #7990

**Comment by carolaponce** [comment]
Updated Mocks

![disposition main - hlr dd](https://user-images.githubusercontent.com/11700545/49258808-aa033080-f3eb-11e8-9088-fbf1dcdac667.png)
![disposition main - hlr](https://user-images.githubusercontent.com/11700545/49258815-ad96b780-f3eb-11e8-9a27-5345d1b440e4.png)
![disposition main - sc](https://user-images.githubusercontent.com/11700545/49258818-b091a800-f3eb-11e8-816a-b79b9f6e6d0e.png)

**Comment by carolaponce** [comment]
Updated mocks
Change - copy change to: Review each issue and select a disposition.
![disposition main - sc](https://user-images.githubusercontent.com/11700545/49259067-b045dc80-f3ec-11e8-8b24-e53d755fe9f0.png)
![disposition main - hlr](https://user-images.githubusercontent.com/11700545/49259068-b045dc80-f3ec-11e8-8b98-f50f1ce6ee6e.png)

**Comment by carolaponce** [comment]
@kencheeto - this is the style/component in Queue I based my designs on:
http://www.caseflowdemo.com/queue/appeals/3575931/tasks/3575931/draft_decision/dispositions

<img width="1106" alt="screen shot 2018-12-05 at 4 31 28 pm" src="https://user-images.githubusercontent.com/11700545/49553177-4d03f080-f8ab-11e8-9df1-be61c9c43c71.png">

**Comment by carolaponce** [comment]
We can change the copy to *Select Dispositions for consistency

**Comment by kencheeto** [comment]
Updated the original description with the latest mocks and copy.

**Comment by steve-gov** [comment]
Strange: I can't type in the textarea inputs at all. (Or paste in text as per the gif below.)

![screencapture1](https://user-images.githubusercontent.com/25468689/50794114-3846be00-1298-11e9-96e6-67ae47a17de4.gif)

**Comment by jiahuang** [comment]
@steve-gov both of those validation issues will be fixed once https://github.com/department-of-veterans-affairs/caseflow/pull/8571 is merged

**Comment by jiahuang** [comment]
This is ready for re-validation

**Comment by steve-gov** [comment]
Cancel button validated! But still strange behavior on textarea. When I type in it, then select a disposition, I am prohibited from modifying textarea content in any way. Tried selecting, deleting, pasting, typing, nothing works:

![screencapture1](https://user-images.githubusercontent.com/25468689/50998592-f1ee9a80-14f5-11e9-9748-5c42dd5a9316.gif)

**Comment by pkarman** [comment]
fwiw this is working for me locally. I suspect what is happening is some "hidden" element is being positioned over the textarea box and preventing mouse clicks from registering in the box. In the gif above I can see the coloration change after selecting the disposition.

@jiahuang I am happy to pitch in on this, if we can duplicate it locally.

**Comment by jiahuang** [comment]
Was able to reproduce it locally and fixed it (locally at least).

**Comment by steve-gov** [comment]
Issue still present, at least in Chrome/ Mac. Demo'ed to Jia who's taking a look.

**Comment by steve-gov** [comment]
Issue still present, will revalidate tomorrow morning.

**Comment by jiahuang** [comment]
@steve-gov UAT got deployed to today. I was able to validate

![textarea_uat](https://user-images.githubusercontent.com/577629/51283026-b17e9900-199b-11e9-8530-dce0e7a41eca.gif)

**Comment by steve-gov** [comment]
VALIDATED!
