### ISSUE TITLE
Non-comp Flow | Completed tab on reviews landing page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7996]
Non-comp users need a way to view past work.

Full non-comp flow: https://va-gov.invisionapp.com/share/PFPCPJ7MEGC

## Acceptance Criteria
- When on the non-comp reviews page, when a user clicks the "Completed" tab, it should show all completed tasks for this business line, in reverse chronological order by completion date.
- Instead of "Days Waiting" the column should be "Date Completed" which shows the date the task was completed.

## Notes
Out of Scope
- Search bar
- Toggling & filtering
- The page it takes you when you click on an item in the list. For now rows should not be clickable.

## Mocks
TBD 

requires #7990

**Comment by kencheeto** [comment]
@shanear do you have more context about how users might typically use/visit these tabs? for example, if a kind of user only ever visits the completed tab, that could be made routable (`/decision_reviews/[business-line-slug]/completed`).

One benefit of being routable is that you could ctrl-r to refresh the page, rather than reloading to the default tab then having to click over. I might be getting ahead of myself here though

**Comment by carolaponce** [comment]
Updated comp
Changing the Intake form button to a main button style.
Changing text to: Review each issue and select a disposition.
Adding - to HLR dropdown

![returning disposition main copy 2](https://user-images.githubusercontent.com/11700545/49258718-51cc2e80-f3eb-11e8-9049-65797c66ac13.png)

**Comment by carolaponce** [comment]
Hi, @kencheeto I know you are working on this + exploring the possibility of re-using Queue's code. Their styling doesn't have the gray table header.  I tweaked my design to be more consistent with theirs.
![RETURNING & DISPOSITION MAIN Copy.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b91284c50ee5a0014e9de9d/125516c66e82c728ace21e0d46dab1ae16b0ad80a1ceff05e479d9a71969145a1d2d8c0530a8c2019102580e1f165cb053181d1ba6acda6fb4bc2e75825e5aef87685676cf3d47a8b8d318bf01e8228e4f86e4ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fcb50fe4ce74d57ac133e71ab.png)

**Comment by kencheeto** [comment]
^ i don't think we have enough data to answer this question yet. I think it's OK to not have the tabs routable, though this call will be up to the engineer

**Comment by pkarman** [comment]
@jiahuang I would love your thoughts on how to make the column different for each tab. Other than that, this ticket seems complete.

**Comment by steve-gov** [comment]
Happy path validated. Days Waiting should be Days Completed but that's referenced for correction in #7992.

![screencapture3](https://user-images.githubusercontent.com/25468689/50998861-c324f400-14f6-11e9-82d3-f30753c58ca5.gif)
