### ISSUE TITLE
Decision Review | Support additional special issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#800]
As a case worker, I want to create an EP instead of being forced to cancel out for the following Special Issues:
- Foreign Issues (non Pension) 
- U.S. Territory (Philippines)
- U.S. Territory - Puerto Rico and Virgin Islands 
- U.S. Territory - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian)

## Acceptance Criteria
1. Verify that when creating the EP for Full, Partial, and Remand Grants with these Special Issues the  Station Code on the EP Creation page is changed to the appropriate VBMS Station below:
    ```
    - Foreign Issues (non Pension): Station 311 - Pittsburgh RO
    - U.S. Territory (Philippines): Station 358 - Manila RO
    - U.S. Territory - Puerto Rico and Virgin Islands: Station 355 - San Juan RO
    - U.S. Territory - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian): Station 459 - Honolulu, RO
    ```
1. Verify that for Partial Grants and Remands with these Special Issues, the VACOLS Location code is also changed to 50.
1. Verify that for Partial Grants and Remands with these Special Issues a VACOLS diary note is added saying:
    > The ARC is transferring this claim to [VACOLS RO code] for further development as it contains a [special issue] issue. EP 170 [label] has been established in VBMS station [station #] for this claim.

## Notes
- Get in touch with @cmgiven about how to add a diary note in VACOLS

**Comment by lakohl** [comment]
Foreign Issues (non Pension) - Pittsburg RO
U.S. Territory (Phillipines) - Manila RO
U.S. Territory claim - Puerto Rico and Virgin Islands - San Juan RO
U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian) Honolulu, RO

**Comment by abbyraskin** [comment]
https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Special%20Issue%20Routing%20Table.md

**Comment by lakohl** [comment]
@shanear this turned out to be more like an epic, but it's ready to go. Assigning it to you.
@nikitarockz  feel free to reword AC

**Comment by lakohl** [comment]
Diary note from: https://github.com/department-of-veterans-affairs/caseflow/issues/720

**Comment by mdbenjam** [comment]
Not going to do AC 3 on this ticket. Will wait for #720.

**Comment by kierachell** [comment]
They show up but I am not sure if fully supported yet.

**Comment by kierachell** [comment]
Not seeing `Foreign Issues (non pension)`?
Other ones seem to route appropriately
![foreignmissing](https://cloud.githubusercontent.com/assets/18075411/23085840/f83e3268-f537-11e6-885d-a748feca90ec.png)


US Territories:
![phil358](https://cloud.githubusercontent.com/assets/18075411/23085845/01472c5c-f538-11e6-80a9-9af9f3df58f5.png)

**Comment by mdbenjam** [comment]
@kierachell I talked to @lakohl about this last week and Foreign Issues (non pension) is the same issue as Foreign claim - compensation claim, dual claim appeals.

**Comment by kierachell** [comment]
Then we good 👍
