### ISSUE TITLE
Milestone Geo matching | Assign veterans | Scheduled tab hearing location

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8021]
As a hearing coordinator, I need to see the hearing location in the scheduled tab to identify the location a veteran is scheduled to. 

### Acceptance criteria
- [ ] Verify that there is a column labeled Hearing Location
- [ ] Verify that each hearing location is displayed in the following format: 
       City, State
       (Type of center) 
       Distance: # of miles

**Comment by laurjpeterson** [comment]
@Chingujo @pshahVA is this feature still relevant?

**Comment by pshahVA** [comment]
It looks like this feature is already completed.

**Comment by alisan16** [comment]
Closing this out based on @pshahVA 's comment above
