### ISSUE TITLE
Limit access to ColocatedTasks to current assignee

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8022]
If a member of the VLJ support staff navigates to the case details page for an appeal with an open `ColocatedTask` assigned to somebody else they can see actions available to them even though they are not the assignee. The offending code appears to be in [`ColocatedTask.available_actions`](https://github.com/department-of-veterans-affairs/caseflow/blob/490fd9e41c9107177ce0d29dc0bb0e39b3ac6ba5/app/models/tasks/colocated_task.rb#L44).

## Acceptance criteria
* [ ] Limit access to `ColocatedTask`s assigned to users to the current assignee
* [ ] Limit access to `ColocatedTask`s assigned to the VLJ support organization to members of the `Colocated.singleton` team

**Comment by lowellrex** [comment]
Work here relates to the effort to simplify the `Task.update_from_params` authorization logic in #8015.

**Comment by laurjpeterson** [comment]
@lowellrex - is this done?

**Comment by lowellrex** [comment]
Yup! Completed by PR #8053.
