### ISSUE TITLE
Validate users ability to create GenericTask

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8023]
Currently, the only validation we do when creating `GenericTask`s is the call to the parent of the new task's [`verify_user_access!` method](https://github.com/department-of-veterans-affairs/caseflow/blob/8da1635797809e3d25937c5a507dfe72a2140e33/app/models/tasks/generic_task.rb#L98). The fact that the current user can update the parent task ([the condition that is checked in `verify_user_access!`](https://github.com/department-of-veterans-affairs/caseflow/issues/8015)) does not necessarily indicate that the current user can create the specific child task it is attempting to create. For example, a member of the mail team will have actions available on the `RootTask` of an appeal, but they should not be able to create a new `JudgeTask` for that appeal--only `MailTask`s--but they are currently able to.

The [base `Task.create_from_params` method](https://github.com/department-of-veterans-affairs/caseflow/blob/8da1635797809e3d25937c5a507dfe72a2140e33/app/models/task.rb#L76) runs `verify_user_can_assign!` to confirm the current user can create a new task, so we could do something similar here.

## Acceptance criteria
* [ ] Validate that the user can create a GenericTask before doing so

**Comment by lowellrex** [comment]
Work here relates to the effort to simplify the `Task.update_from_params` authorization logic in #8015.

**Comment by lowellrex** [comment]
May be addressed by #8273.

**Comment by laurjpeterson** [comment]
@lowellrex - is this done?

**Comment by lowellrex** [comment]
Yup!
