### ISSUE TITLE
Decision Review | Don't allow changing Decision Type

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#803]
As a Caseworker, I don't want to be able to update the "Decision Type" on the `Decision Review` page so that I can, instead, cancel and escalate the case when the value is incorrect since the "Decision Type" value in VACOLS can not be updated.

# Acceptance Criteria
1. Verify the _"Decision Type"_ field label has been changed to "Decision Type" instead of 'Select Decision Type'.
1. Verify the _"Decision Type"_ field is not editable.
1. Verify the _"Decision Type"_ field uses the Caseflow styling for non-editable fields.

## Mockups
**_View - Decision Review Page - Decision Type with new label_**
![image](https://cloud.githubusercontent.com/assets/23063044/22869007/c49fe11c-f169-11e6-9f5a-6168f111c9d8.png)

# Related Stories
Decision Review | Special Issues | Show all issues regardless Decision Type #715

**Comment by lakohl** [comment]
@nikitarockz @shanear this is ready

**Comment by kierachell** [comment]
**PASSED**
The field is not editable in `uat`
