### ISSUE TITLE
Non-comp Flow | Save decision

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8031]
For each non-comp HLR and SC, the users need a way to record the decision being made for each request issue.

## Acceptance Criteria
- On the non-comp decision page, the "Complete" button should be disabled unless a disposition is set for each issue, and the decision date is filled in.
- When the "Complete" button is active and pressed, it should save decision issues for each decision as well as the decision date and the user who saved the decision. The review should be considered complete.
- After saving, it should redirect to the "Completed" tab of the reviews page. It should show a small confirmation message according to the mocks below.

## Copy
Decision completed
You successfully added a decision for [claimant name]'s [form name] (Veteran SSN: [veteran ssn])

## Mocks
*Decision page*
![disposition main - hlr](https://user-images.githubusercontent.com/1596259/49190856-17f31d80-f342-11e8-85e9-ee8541a8e620.png)

*Confirmation after save*
![confirmation - disposition - ftu](https://user-images.githubusercontent.com/1596259/49191538-ed569400-f344-11e8-8ccd-a46b10d3c8e5.png)

Full non-comp flow: https://va-gov.invisionapp.com/share/PFPCPJ7MEGC

requires #7994

**Comment by carolaponce** [comment]
![confirmation - disposition copy](https://user-images.githubusercontent.com/11700545/49251988-b8475180-f3d7-11e8-845c-802356792c64.png)

**Comment by carolaponce** [comment]
![disposition main - hlr](https://user-images.githubusercontent.com/11700545/49252046-da40d400-f3d7-11e8-8e4a-596b708ad994.png)

**Comment by carolaponce** [comment]
![disposition main - hlr](https://user-images.githubusercontent.com/11700545/49252397-ca75bf80-f3d8-11e8-9415-10d931e0a7ee.png)

**Comment by jiahuang** [comment]
Doh, there's a bug where upon completion the `Date Sent` field isn't populated properly. I will fix this in a subsequent PR

**Comment by steve-gov** [comment]
Seems like there are a couple ways the button-disabling can be fooled:

- I can select a disposition, then clear it, and can push the button
- I can clear the date, enter a date, clear the date, and push the button

Button should only be enabled if the date is present and each disposition is selected.

![screencapture](https://user-images.githubusercontent.com/25468689/51646645-45b5a680-1f2e-11e9-8a00-de2e1208b0a3.gif)

**Comment by steve-gov** [comment]
@carolaponce Do we have a "required" indicator at the field level that we'd like to apply here? Both the date and the disposition on each issue are required.

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-01-25 15 33 39" src="https://user-images.githubusercontent.com/1596259/51778463-a243cd80-20b6-11e9-90e8-370c3751f0e6.png">
getting an error on this page 😢 

https://appeals.cf.uat.ds.va.gov/decision_reviews/voc_rehab/tasks/66

**Comment by steve-gov** [comment]
Almost there, one last thing! If I change the decision data to anything other than the prefilled date, it still records as the prefilled date: 

![screencapture](https://user-images.githubusercontent.com/25468689/52017950-b6644200-249d-11e9-8121-5684d20c395d.gif)

**Comment by steve-gov** [comment]
Validated that I can edit and save the decision date.
