### ISSUE TITLE
Schedule AMA Veterans | Case details | Add Docket number tags

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8046]
As a hearing coordinator, when I click case details, I want to ensure that the AMA tags are there for the docket numbers.

### Acceptance Criteria
- [ ] Verify that in the Case Details snap shot area under about the case, the appropriate AMA docket label is displayed

### Mock

- https://va-gov.invisionapp.com/share/AYPASC0CDWG

### Related Issues
#7980 Epic AMA Scheduling

**Comment by Sjones352** [comment]
This has already been implemented. Closing ticket
