### ISSUE TITLE
Schedule AMA Veterans | Add AMA lane tag hover tool tips

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8047]
As a hearing coordinator, I want to be able to see a description of what the tag is so I know what the AMA lane tags refer to. 

### Acceptance Criteria
- [ ] Verify that hovering over the following lane tags render the correct tool tip: 
  - L - legacy
  - E - new evidence
  - D - direct review
  - H - hearings

### Mocks

- https://va-gov.invisionapp.com/share/AYPASC0CDWG#/333383867_2a_Docket-Locked_Hearing_Day

Schedule
<img width="995" alt="screen shot 2018-11-29 at 2 06 31 pm" src="https://user-images.githubusercontent.com/44249412/49245503-88507c00-f3e0-11e8-8af4-1319f221326a.png">
Daily Docket
<img width="285" alt="screen shot 2018-11-29 at 2 09 04 pm" src="https://user-images.githubusercontent.com/44249412/49245516-8ab2d600-f3e0-11e8-8f03-08435e8df9bb.png">

### Related Issues
#7981 AMA schedule veterans

**Comment by Chingujo** [comment]
@MeredithStewart cc: @laurenrussell 

For the hover states, we would want to show this in everyplace where we are showing the docket number correct? So in the following:

- All tabs in the schedule view since we show docket number in Scheduled, Legacy Veterans Waiting, and AMA Veterans Waiting

- Daily docket

- Case details

Is this correct?

**Comment by laurenrussell** [comment]
@Chingujo Think its already implemented in Case Details (I see it on demo). Its typical behavior, so can she follow the pattern for all tags? Here's what I'm seeing: 
<img width="922" alt="screen shot 2018-12-04 at 5 03 15 pm" src="https://user-images.githubusercontent.com/44249412/49475927-8b83a780-f7e6-11e8-89b3-8492ffdb9579.png">

**Comment by Chingujo** [comment]
O duh because Queue probably did it already thanks @laurenrussell
