### ISSUE TITLE
Rescue BGS fetch rating errors

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#8050]
## Story
If a user gets a Locked Rating or Converted or Backfilled rating error from BGS, the user can potentially get stuck in a state where they have an intake in progress, and they can't cancel it because they are stuck on the app-wide "Something went wrong" page.  This locks them out of the Intake app until the problem intake expires, after a day.

## Acceptance Criteria
- If a user tries to intake a veteran that has a Converted or Backfilled rating error, the intake gets canceled and the user is able to start a new intake
- The user does not get stuck on the "Something went wrong" page

**Comment by steve-gov** [comment]
@kencheeto Can you validate this plz?

**Comment by steve-gov** [comment]
User validated in the field, will keep an eye on it.
