### ISSUE TITLE
Planning detailed training materials + planning training implementation for Non-compensation claims

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#8061]
Since Non-comp intake + decision  flows are ready for development we can start planning for training.

Necessary artifacts:

- Prototype (Static or Interactive?) Copy - step by step on how to use the tool 
- Scenarios (All scenarios and edge cases)
- Videos
- Supportive documentation
- Types of users

**Comment by carolaponce** [comment]
Existing documentation:
https://app.mural.co/t/workqueue2001/m/workqueue2001/1538364691019/29e2e4cfa7cc8decb1d2f32df7de1796b0f53987

**Comment by steve-gov** [comment]
- Tooltips/ JS tour

**Comment by steve-gov** [comment]
Capturing in #8185.
