### ISSUE TITLE
If open mail task, prevent dispatching the appeal

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8070]
If there is an open mail task on the appeal, the appeal cannot be dispatched from the Board.

Note: Scope to AMA mail tasks in Caseflow first

## Ideas
- option 1: judges cannot send the case to BVA dispatch
- option 2: QR team/individuals cannot send the case to BVA dispatch
- option 3: BVA dispatchers cannot dispatch the case (e.g. actions column is disabled)

We either do all three options, or just option 3.

**Comment by laurjpeterson** [comment]
@allyceh - now that we have Caseflow mail tasks for AMA, we can revisit this flow. What do you think about the options above? I think I like just doing three. I think we'd need an error message or something to explain why the BVA dispatcher can't dispatch this appeal. 

I don't think this is that urgent because BVA Dispatchers will see all currently active tasks in Case Details - if there is an open mail task, they will see it, and as long as we train them specifically, could recognize that they should not dispatch the appeal. What do you think of this, until we can programmatically prevent the case from being dispatched? Should we connect with Rolandus/Will/Libby again?

**Comment by allyceh** [comment]
@laurjpeterson I agree with all three above. It would be interesting to get judge's take on this, too. 

We can connect with Rolandus/Will/Libby about tasks in Caseflow. They haven't received any training around it yet.
