### ISSUE TITLE
Hearing Schedule Flaky Tests

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8077]
Many of our hearing scheduling tests use methods from spec/fake_date_helper.rb. This is causing flakiness because we're randomly generating dates. We should update any test that uses those methods to deterministically choose dates (see #8075) as an example, and then remove this file.

**Comment by Sjones352** [comment]
Re-opening as it's on going till all these flakey tests are fixed.
