### ISSUE TITLE
Legacy Opt-in | Eligibility constraint fixes

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8081]
We missed two small but important details in the eligibility requirements for legacy opt ins. They should be fixed.

## Acceptance Criteria
- The eligibility rules for opt-in should be based on the receipt date of the form, not the current date
- If the VACOLS appeal has an SSOC date (not just an SOC date) within 60 days of the receipt date of the AMA form it should also be considered eligible.

## Notes
See https://github.com/department-of-veterans-affairs/caseflow/issues/7334 for original definition of eligible.

**Comment by kencheeto** [comment]
@shanear could you complete that first bullet? `- The eligibility rules for opt-in should be based on the receipt date of the form, not the `

**Comment by shanear** [comment]
This does not appear to be working.

When I try and opt in an issue from the VACOLS appeal (bfkey: 1032628)
![Uploading Screenshot 2019-01-22 10.40.19.png…]()

It says it's not eligible, but the ssoc3 date is within 60 days
```
irb(main):017:0> c.bfssoc3
=> Sat, 12 Jan 2019
```

UAT file number: 123458317

**Comment by shanear** [comment]
Nice investigation. I agree with you, but i think this issue is lower priority so I made another ticket for it: https://github.com/department-of-veterans-affairs/caseflow/issues/8967
