### ISSUE TITLE
AMO Questions for this week (12/6/12)

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#8090]
- Ask about SOP
- **User Testing with Intake team in Seattle** - We would like to schedule user inquiries and user testing shortly after launch.  Who is the best person to contact for this?

**Comment by shanear** [comment]
- separate call about training and the SOPs.
- circle back with Kaitlin about user testing meeting.
- circle back with Kaitlin about contesting claims

**Comment by shanear** [comment]
all action items are done. Closing
