### ISSUE TITLE
Questions page: Make all required questions required

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#81]
Lots of the questions that appear are not marked as required, but they should be. The only known optional question is field 14 for remarks (note: field 13 is required, but can have no checkboxes checked).

**Comment by plusjeff** [comment]
Also, see #81

**Comment by alex** [comment]
@plusjeff what does it mean for 13 to be required?

**Comment by plusjeff** [comment]
@alex Good question. We can leave it as is. 

There's a difference between design vs coding terminology here.

Design terminology: It is a required field. Users must answer it. Not checking a checkbox is an answer.

Coding terminology: It is not a required field. We will not check to make sure any checkboxes were checked and no `required` attributes will be used for this field.

**Comment by alex** [comment]
Yup, makes sense :-)

On Wed, Oct 28, 2015 at 3:30 PM, Jeff Maher <notifications@github.com>
wrote:

> @alex <https://github.com/alex> Good question. We can leave it as is.
>
> There's a difference between design vs coding terminology here.
>
> Design terminology: It is a required field. Users must answer it. Not
> checking a checkbox is an answer.
>
> Coding terminology: It is not a required field. We will not check to make
> sure any checkboxes were checked and no required attributes will be used
> for this field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/81#issuecomment-151965099>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by plusjeff** [comment]
Halting until #171 is merged.
