### ISSUE TITLE
Integration bug with Admin Establish Claim

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#810]
Trying to create an end product task manually on `admin/establish_claim` causes a 500 because the integration code isn't quite correct.

**Comment by astewarttistatech** [comment]
@shanear I don't know if your description is for UAT or for the Dev environment. Also I don't know if that's what should be happening or what shouldn't be happening.

**Comment by astewarttistatech** [comment]
Currently in UAT: 

A 404 error is thrown back when visiting /admin/establish_claim page for caseflow. 

<img width="1351" alt="screen shot 2017-02-02 at 6 28 17 pm" src="https://cloud.githubusercontent.com/assets/23038505/22573119/714d92e4-e975-11e6-89a8-cfe9f4b9ae51.png">

**Comment by shanear** [comment]
@astewarttistatech your screenshot shows `admin/establish-claim` not `admin/establish_claim`

**Comment by astewarttistatech** [comment]
**Failed**

@shanear Your description is still unclear, I don't know if I am supposed to be looking for that error or not. Pushing back to "Current Sprint" until description is clarified. 

Screenshots: 

<img width="1366" alt="screen shot 2017-02-03 at 11 03 55 am" src="https://cloud.githubusercontent.com/assets/23038505/22598271/dea8146e-ea00-11e6-8a5e-21fcc7c4d5b2.png">

**Comment by joofsh** [comment]
@astewarttistatech Maybe I can help.

Currently when you load that page, you see "No existing tasks". We want to verify you _can_ add a real task.

Steps:
-  Find a valid UAT vbms_id that has a decision uploaded. Can maybe ask Artem for help on a valid user in this scneario
- Enter that vbms id in the field & click create
- Verify the page reloads and you now see that task in the "Existing Tasks" list at the bottom

Ping me on slack if you have any more questions

**Comment by shanear** [comment]
@astewarttistatech Sorry, this was a quick issue to solve a minor integration issue, I will take care of validating.

**Comment by shanear** [comment]
<img width="1554" alt="screen shot 2017-02-03 at 2 27 37 pm" src="https://cloud.githubusercontent.com/assets/1596259/22605227/eff14a12-ea1c-11e6-96cb-c2d42c3a14e5.png">
Confirmed this works on preprod. Closing.
