### ISSUE TITLE
Delete hearing day | Error handling

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8109]
If a user tries to delete a VACOLS hearing day, the server will return an error. We should catch that error on the frontend and display a message that VACOLS hearing days must be deleted from VACOLS.

1) Update deleteHearingDay in DailyDocketContainer to catch errors
1) Add a prop for onErrorHearingDayDelete
1) Display an alert when onErrorHearingDayDelete is true

**Comment by laurenrussell** [comment]
<img width="898" alt="screen shot 2018-12-06 at 10 35 30 am" src="https://user-images.githubusercontent.com/44249412/49593940-c8fd4780-f942-11e8-9fb3-3d97408f3f01.png">
