### ISSUE TITLE
Decision Review | Create End Product.. | Save selected Special Issues for an unsupported Special Issue Cancellation

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#811]
As a Product Owner, I want to be able to see which special issues an appeal had when it was cancelled so that I will be able to monitor the frequency of special issues related to cancelled claims establishments.

# Acceptance Criteria
1. Verify that when a claims establishment is cancelled via the unsupported special issue screen (shown below), all checked special issues are saved to the database for that appeal.
    <img width="1554" alt="screen shot 2017-02-07 at 3 28 28 pm" src="https://cloud.githubusercontent.com/assets/1596259/22710255/9eb88738-ed4a-11e6-8ddf-e5d99727f97e.png">

1. Verify that when a special issue is checked and a user cancels the claims establishment via the "Cancel" button on the bottom of the screen (shown below), the special issues are not saved in the database.
    <img width="1554" alt="screen shot 2017-02-07 at 3 29 20 pm" src="https://cloud.githubusercontent.com/assets/1596259/22710259/a5ae7a20-ed4a-11e6-90b5-4a7567eafae5.png">

## Notes
- Since there is no way to view the values of the special issues in the DB, a developer with SSH access to AWS UAT will have to help verify this issue.

# Related Stories
Decision Review | Special Issues | Show all issues regardless Decision Type #715

**Comment by kierachell** [comment]
**PASSED** on `uat` - @mdbenjam had to make a small fix to actually unblock this - so, clearly, the SIC were being saved.
