### ISSUE TITLE
If no notes, remove Notes field when displaying AMA issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8124]
When testing AMA attorney magic with an attorney today, we saw that the Notes field of a request issue in Case Details had `""` when there were no notes on the request issue.

**Comment by aroltsch** [comment]
![image](https://user-images.githubusercontent.com/3811786/49882986-c5186c00-fdff-11e8-86a2-0295acff8c24.png)
