### ISSUE TITLE
Slot Video Hearings | Parent record association

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8126]
When testing in production, Justin scheduled a video hearing for the Baltimore RO, but the resulting child record was associated with the wrong parent record. The hearing which was scheduled for 3/22 should have been associated with parent record 609045 but was instead associated with 608204. 

We need to determine how this happened (perhaps there was a stale payload?), fix the bug if necessary, and then clean up the data in VACOLS.

**Comment by oscarAtNava** [comment]
Looking at prod the reason the child record was attached to video parent 608204 is that there was an existing ScheduleHearingTask created on November 5th for this same appeal. It may have been that task that surfaced in ClientDetails. Two questions do remain and I am currently at a loss to explain them: (1) the existing, stale, task should have a status of completed, but does not; (2) there should be a second task, created today. On the latter point the code today creates a ScheduleHearingTask any time user clicks on a veteran from the AssignHearings page. I could not find that new task.

Below is all the evidence records from the DB.

Hearing created today:

VACOLS::CaseHearing.where(hearing_pkseq: 627024)
=> #<ActiveRecord::Relation [#<VACOLS::CaseHearing hearing_pkseq: 627024, hearing_type: "V", folder_nr: "3821042", hearing_date: "2019-03-22 08:30:00", hearing_disp: nil, board_member: "332", notes1: nil, team: "D1", room: "4", rep_state: nil, mduser: "TEWILLIAMS", mdtime: "2018-10-25", reqdate: nil, clsdate: nil, recmed: nil, consent: nil, conret: nil, contapes: nil, tranreq: nil, transent: nil, wbtapes: nil, wbbackup: nil, wbsent: nil, recprob: nil, taskno: nil, adduser: "JMADIGAN", addtime: "2018-12-06", aod: nil, holddays: nil, vdkey: "608204", repname: nil, vdbvapoc: "Thomas Williams 202-632-5697", vdropoc: "CONNIE SMITH 410 230 4530 EXT 3092", canceldate: nil, addon: nil>]>

It is for veteran with appeal vacols_id of 3821042:

irb(main):006:0> LegacyAppeal.find_or_create_by_vacols_id(3821042)
=> #<LegacyAppeal id: 387223, vacols_id: "3821042", vbms_id: "27357212C", rice_compliance: false, private_attorney_or_agent: false, waiver_of_overpayment: false, pension_united_states: false, vamc: false, incarcerated_veterans: false, dic_death_or_accrued_benefits_united_states: false, vocational_rehab: false, foreign_claim_compensation_claims_dual_claims_appeals: false, manlincon_compliance: false, hearing_including_travel_board_video_conference: false, home_loan_guaranty: false, insurance: false, national_cemetery_administration: false, spina_bifida: false, radiation: false, nonrating_issue: false, us_territory_claim_philippines: false, contaminated_water_at_camp_lejeune: false, mustard_gas: false, education_gi_bill_dependents_educational_assistance_scholars: false, foreign_pension_dic_all_other_foreign_countries: false, foreign_pension_dic_mexico_central_and_south_america_caribb: false, us_territory_claim_american_samoa_guam_northern_mariana_isla: false, us_territory_claim_puerto_rico_and_virgin_islands: false, dispatched_to_station: nil, issues_pulled: nil, appeal_series_id: nil>

This appeal has only one task associated with it. The creation date for this task is November 5th.

irb(main):008:0> ScheduleHearingTask.find_by(appeal_id: 387223)
[2018-12-06 14:57:26 -0500]   ScheduleHearingTask Load (1.0ms)  SELECT  "tasks".* FROM "tasks" WHERE "tasks"."type" IN ('ScheduleHearingTask') AND "tasks"."appeal_id" = $1 LIMIT $2  [["appeal_id", 387223], ["LIMIT", 1]]
=> #<ScheduleHearingTask id: 1142, appeal_id: 387223, status: "assigned", type: "ScheduleHearingTask", action: nil, instructions: nil, assigned_to_id: 1588, assigned_by_id: 1588, assigned_at: "2018-11-05 16:41:20", started_at: nil, completed_at: nil, created_at: "2018-11-05 16:41:20", updated_at: "2018-11-05 16:41:20", appeal_type: "LegacyAppeal", placed_on_hold_at: nil, on_hold_duration: nil, assigned_to_type: "User", parent_id: 1140>

The details of the parent hearing to attach the hearing are in task business payload:

irb(main):009:0> TaskBusinessPayload.find_by(task_id: 1142)
[2018-12-06 15:00:57 -0500]   TaskBusinessPayload Load (0.5ms)  SELECT  "task_business_payloads".* FROM "task_business_payloads" WHERE "task_business_payloads"."task_id" = $1 LIMIT $2  [["task_id", 1142], ["LIMIT", 1]]
=> #<TaskBusinessPayload id: 2, task_id: 1142, description: "Create Task", values: {"regional_office_value"=>"RO13", "regional_office_label"=>"Baltimore, MD", "hearing_pkseq"=>608204, "hearing_type"=>"Video", "hearing_date"=>"2018-11-09T08:30:00.000-05:00"}>

Incorrect parent to where it was attached

irb(main):013:0> VACOLS::CaseHearing.where(hearing_pkseq: 608204)
[2018-12-06 15:23:33 -0500]   VACOLS::CaseHearing Load (75.7ms)  SELECT  "VACOLS"."HEARSCHED".* FROM "VACOLS"."HEARSCHED" WHERE "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a1 AND ROWNUM <= :a2   [["hearing_pkseq", 608204], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<VACOLS::CaseHearing hearing_pkseq: 608204, hearing_type: "C", folder_nr: "VIDEO RO13", hearing_date: "2018-11-09 08:30:00", hearing_disp: nil, board_member: "332", notes1: nil, team: "D1", room: "4", rep_state: nil, mduser: "TEWILLIAMS", mdtime: "2018-10-25", reqdate: nil, clsdate: nil, recmed: nil, consent: nil, conret: nil, contapes: nil, tranreq: nil, transent: nil, wbtapes: nil, wbbackup: nil, wbsent: nil, recprob: nil, taskno: nil, adduser: "JWAGNER", addtime: "2018-07-17", aod: nil, holddays: nil, vdkey: nil, repname: nil, vdbvapoc: "Thomas Williams 202-632-5697", vdropoc: "CONNIE SMITH 410 230 4530 EXT 3092", canceldate: nil, addon: nil>]>

Parent where it was supposed to be attached:

irb(main):010:0> VACOLS::CaseHearing.where(hearing_pkseq: 609045)
[2018-12-06 15:06:44 -0500]   VACOLS::CaseHearing Load (80.6ms)  SELECT  "VACOLS"."HEARSCHED".* FROM "VACOLS"."HEARSCHED" WHERE "VACOLS"."HEARSCHED"."HEARING_PKSEQ" = :a1 AND ROWNUM <= :a2   [["hearing_pkseq", 609045], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<VACOLS::CaseHearing hearing_pkseq: 609045, hearing_type: "C", folder_nr: "VIDEO RO13", hearing_date: "2019-03-22 08:30:00", hearing_disp: nil, board_member: "480", notes1: nil, team: "D1", room: "9", rep_state: nil, mduser: "JMADIGAN", mdtime: "2018-11-30", reqdate: nil, clsdate: nil, recmed: nil, consent: nil, conret: nil, contapes: nil, tranreq: nil, transent: nil, wbtapes: nil, wbbackup: nil, wbsent: nil, recprob: nil, taskno: nil, adduser: "JWAGNER", addtime: "2018-07-17", aod: nil, holddays: nil, vdkey: nil, repname: nil, vdbvapoc: nil, vdropoc: nil, canceldate: nil, addon: nil>]>

This parent video record has no children

irb(main):011:0> VACOLS::CaseHearing.where(vdkey: 609045)
[2018-12-06 15:07:22 -0500]   VACOLS::CaseHearing Load (80.9ms)  SELECT  "VACOLS"."HEARSCHED".* FROM "VACOLS"."HEARSCHED" WHERE "VACOLS"."HEARSCHED"."VDKEY" = :a1 AND ROWNUM <= :a2   [["vdkey", "609045"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation []>
