### ISSUE TITLE
Limit attorney's notes during checkout on FE to 350 chars 

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8128]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2709/

Screenshot:

![image](https://user-images.githubusercontent.com/3811786/50156424-cda7f100-029c-11e9-879c-97345d9c3029.png)

For legacy cases, we update Vacols DECASS table. One of the fields on that table has a length limit. 

AC:
1. On BE, when setting `decass.deatcom` limit to be no longer than 350 chars
2. On FE, limit attorney's notes during checkout to be less than 350 chars

**Comment by aroltsch** [comment]
@monfresh let's silently truncate it

**Comment by aroltsch** [comment]
![image](https://user-images.githubusercontent.com/3811786/50189534-a2042580-02f3-11e9-90bc-772980b34317.png)

**Comment by aroltsch** [comment]
Attorney final checkout screen. It appears there is already a limit to 350 chars in the notes screen so I wonder what happens there. 
![image](https://user-images.githubusercontent.com/3811786/50189635-1b9c1380-02f4-11e9-9015-5db1310d3d65.png)

**Comment by monfresh** [comment]
Yeah, I saw the character limit on that screen as well, which made me wonder if the bug was on a different screen. Do we know which user caused this exception and what they were doing before that? On login.gov, I implemented an analytics framework that allowed to see step by step what each user did on the site, which was very helpful for troubleshooting. Do we have something like that on caseflow?

**Comment by aroltsch** [comment]
Wow, this would be super useful. Unfortunately, we don't have that. It happened to 5 users. Here is an example of a text:

```
A DIC claim by the Veteran’s Spouse. The Veteran served in Thailand during the Vietnam era, and has multiple myeloma 29 years later.  While the Vet’s air base qualifies as one in Thailand to have presumed herbicide exposure (under the M21 guidelines), the nature of his duties did not have him working near the air base perimeter. it remains denied.
```

There are 349 chars here but Oracle claims there are 353 chars. 

```
ActiveRecord::ValueTooLong: OCIError: ORA-12899: value too large for column "VACOLS"."DECASS"."DEATCOM" (actual: 353, maximum: 350): UPDATE "VACOLS"."DECASS" SET "VACOLS"."DECASS"."DEPROD" = 'DEC', "VACOLS"."DECASS"."DEATCOM" = 'A DIC claim by the Veteran’s Spouse. The Veteran served in Thailand during the Vietnam era, and has multiple myeloma 29 years later.  While the Vet’s air base qualifies as one in Thailand to have presumed herbicide exposure (under the M21 guidelines), the nature of his duties did not have him working near the air base perimeter. it remains denied.', "VACOLS"."DECASS"."DEDOCID" = '02225-00000028', "VACOLS"."DECASS"."DEMDUSR" = 'VACOMULRAG', "VACOLS"."DECASS"."DERECEIVE" = '2018-12-06', "VACOLS"."DECASS"."DEMDTIM" = '2018-12-06', "VACOLS"."DECASS"."DE1TOUCH" = 'N' WHERE "VACOLS"."DECASS"."DEFOLDER" = :a1 AND "VACOLS"."DECASS"."DEADTIM" = :a2
```

Can it be that Oracle treating certain chars differently? Perhaps whitespaces? Not sure.

**Comment by monfresh** [comment]
Interesting. I can reproduce the bug by using this text in the specs. I will look into it.
