### ISSUE TITLE
Removing / Locking Hearing Day | Red checkbox

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8139]
We need to add a red checkbox to the style guide and then add it to the modals for removing a hearing day and locking a hearing day.

Mocks: https://va-gov.invisionapp.com/share/2PP8PZ4MBGV#/screens/332705683

**Comment by mdbenjam** [comment]
Can I ask why we need a red checkbox? What kind of meaning is this supposed to convey? I'm hesitant to add a new component that deviates from all our others.

**Comment by mdbenjam** [comment]
Similarly do we even need a checkbox? It seems the modal achieves the "Are you sure" result?

**Comment by Sjones352** [comment]
@sharonwarner should we close this ticket?
