### ISSUE TITLE
Feature toggle for turning Task creation on for just Full Grants (and all decisions)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#814]
As a developer, I want to be able to turn on the automated job for processing all full grant decisions while leaving partial grants & remands disabled

I'll leave the mechanism up to yall. We just need to be able to turn this on sometime on or before the weekend of Feb 24, when the full grant launch goes live.

**Comment by kierachell** [comment]
Currently there is a problem with running `CreateEstablishTaskJob` as it checks `FeatureToggle.enabled?` without passing a `user:` parameter. Which causes `FeatureToggle::UserIsRequiredError:`

**Comment by shanear** [comment]
This worked, I talked with @aroltsch about making a tweak to the feature flag functionality.
