### ISSUE TITLE
Create style guide component for wide modals

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8171]
Create wide version of a modal for the Caseflow Style Guide. 

## Mock

<img width="489" alt="screen shot 2018-12-10 at 10 10 51 am" src="https://user-images.githubusercontent.com/40216950/49741258-083dd800-fc64-11e8-9ad9-ec06f68e0eb3.png">

A wide modal is used across Intake and Attorney-Judge checkout flows. We want to standardize this modal in our style guide so that we can use this pattern again. 

To trigger Intake's version of a wide modal in demo, follow these instructions: 
Go to http://www.caseflowdemo.com/intake/finish and change the finish to /add_issues. The link becomes http://www.caseflowdemo.com/intake/add_issues. Then, click on the +add issue button.

cc: @carolaponce @sneha-pai

**Comment by msj0nes** [comment]
Closing as aged ticket. Design can reopen and reuse if needed.
