### ISSUE TITLE
Tweaks to editing issues designs 

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8175]
## Edit issues updates
Below are proposed eng tweaks to the edit AMA issues designs.

### Issues on Case Details

- [ ] Swap the order of benefit type and issue text so that benefit type comes first. 
- [ ] Increase the padding between each contested issue. Q: what is the spacing between each line? Could we try 25 px between issues? 
<img width="934" alt="screen shot 2018-12-10 at 11 49 26 am" src="https://user-images.githubusercontent.com/40216950/49747577-b439f000-fc71-11e8-93e1-7ee95224a94d.png">

### Attorney-Judge Checkout

- [ ] Make “Decision Ready for Review” sentence case. So, “Decision ready for review”
<img width="592" alt="screen shot 2018-12-10 at 11 50 10 am" src="https://user-images.githubusercontent.com/40216950/49747625-cfa4fb00-fc71-11e8-9ae5-e6fa2ed0e666.png">

- [ ] Make button text sentence case, so “Add decision”
<img width="263" alt="screen shot 2018-12-10 at 11 50 52 am" src="https://user-images.githubusercontent.com/40216950/49747646-e0ee0780-fc71-11e8-9ad8-5cf3a9daed3a.png">

- [ ] Can we decrease the padding between added decisions justttt slightly. This would conserve space if there are ten different issues, for example. Could we try 20 px?
<img width="1237" alt="screen shot 2018-12-10 at 11 51 51 am" src="https://user-images.githubusercontent.com/40216950/49747696-02e78a00-fc72-11e8-888d-84e74dd783cf.png">

### Modals

- [ ] Update text field hint to read:
  - Select disposition (sentence case)
<img width="492" alt="screen shot 2018-12-10 at 11 52 37 am" src="https://user-images.githubusercontent.com/40216950/49747780-2b6f8400-fc72-11e8-9d0a-caf367434998.png">

- [ ] Can we bump the disposition to the left a bit? (See mocks in #7965 )
<img width="1081" alt="screen shot 2018-12-10 at 11 53 33 am" src="https://user-images.githubusercontent.com/40216950/49747829-47732580-fc72-11e8-9381-42e42730082d.png">

- [ ] With small modal size, secondary CTA button is bumping into primary (Edit decision modal). I think this will be fixed with the larger modal size. 
<img width="491" alt="screen shot 2018-12-10 at 11 55 47 am" src="https://user-images.githubusercontent.com/40216950/49747993-9f119100-fc72-11e8-8347-f03d10af41a8.png">

- [ ] When I am adding decisions to the narrow modal, content is scrolling behind the modal. Can that be fixed?

### Attorney-Judge Checkout Error States

- [ ] Update error message copy to “You must add a decision before you continue.”
- [ ] When the user triggers the error, the spacing between the Add Decision button and Contested Issue below increases. Can we keep the spacing between issues as-is and decrease the length of the red bar so that it aligns with the bottom of the Add Decision button?
<img width="1183" alt="screen shot 2018-12-10 at 11 57 15 am" src="https://user-images.githubusercontent.com/40216950/49748082-ccf6d580-fc72-11e8-97e3-9853b78f94cf.png">

- [ ] We can replace program type with benefit type on the remand reasons page.
<img width="873" alt="screen shot 2018-12-10 at 11 59 00 am" src="https://user-images.githubusercontent.com/40216950/49748193-07f90900-fc73-11e8-9576-7f83ed66af18.png">

**Comment by mdbenjam** [comment]
Regarding spacing between issues, right now it's normal list styling spacing between items .5em. Does this definitely need to change? Prefer not to override styling for something as basic as list items.

> Can we decrease the padding between added decisions justttt slightly. This would conserve space if there are ten different issues, for example. Could we try 20 px?

How much of that spacing should be whitespace and how much should be the gray line?

> Can we bump the disposition to the left a bit?

This component is already pretty styled, is this styling necessary? It's not super easy to achieve, and I'm hesitant to keep adding more CSS to this component.

> With small modal size, secondary CTA button is bumping into primary (Edit decision modal). I think this will be fixed with the larger modal size.

This may not be fixed with a larger modal, but let's see if it does before investing time in it.

>  When I am adding decisions to the narrow modal, content is scrolling behind the modal. Can that be fixed?

I think a larger modal will mostly fix this.

> When the user triggers the error, the spacing between the Add Decision button and Contested Issue below increases. Can we keep the spacing between issues as-is and decrease the length of the red bar so that it aligns with the bottom of the Add Decision button?

Can we leave it as is? That extra padding comes from the USWDS error class.

**Comment by allyceh** [comment]
@mdbenjam How much of that spacing should be whitespace and how much should be the gray line?
- Let's try 1/2 of the space as the grey line. If spacing is 20 px total, then 10 px for the grey line, and 5 for padding on the top and bottom. 

For now, let's not add additional styling to our list items or the decision component, per your comments.

**Comment by aroltsch** [comment]
Will create a new ticket
