### ISSUE TITLE
When no POA for AMA case, display "none" in POA module

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8182]
Currently, we display a ":" in Caseflow when the veteran doesn't have a POA. To be more clear about this, let's display "None" when the veteran doesn't have a POA. 

<img width="955" alt="screen shot 2018-12-10 at 4 11 01 pm" src="https://user-images.githubusercontent.com/40216950/49761990-73080700-fc96-11e8-8ef6-ecbb6922c1d2.png">

**Comment by laurjpeterson** [comment]
@lowellrex - a case details tweak, maybe for next sprint.

**Comment by laurjpeterson** [comment]
Repeat of this - https://github.com/department-of-veterans-affairs/caseflow/issues/7530 - so closing
