### ISSUE TITLE
SyncIntakeJob close remand fails with "ActiveRecord::RecordInvalid: Validation failed: Isscode can't be blank"

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8189]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3071/

ramp_closed_appeal_id 76546

Work involved is:
* identify why this failure is happening
* identifying what data changes are necessary, if anything
* implement data fix, if it fits in the scope of this issue

**Comment by pkarman** [comment]
The related VACOLS issue has an existing `isscode` of "15" but it does not appear to be getting cloned into the follow up issue being created:

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/appeal_repository.rb#L475

**Comment by pkarman** [comment]
from @cmgiven ok to delete this CaseIssue.

> Go ahead and do it on my say so. It’s invalid data, and we’ve confirmed using the text of the Board decision that it does not correspond to a real issue that was adjudicated. I do not see any risk here.

**Comment by pkarman** [comment]
Issue was deleted
```
irb(main):006:0> VACOLS::CaseIssue.delete_issue!("3162806", 2)
[2019-01-07 14:18:04 -0500]   SQL (85.1ms)  DELETE FROM "VACOLS"."ISSUES" WHERE "VACOLS"."ISSUES"."ISSKEY" = :a1 AND "VACOLS"."ISSUES"."ISSSEQ" = :a2  [["isskey", "3162806"], ["issseq", 2]]
=> 1
```
