### ISSUE TITLE
Dispatch Stats | Display stats charts

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#819]
As a system administrator I want to be able to see all the business stats about how people are using Caseflow Dispatch.

## Acceptance Criteria
1. Verify that there are bar charts in the style of the certification stats page for the following categories and metrics. The bars on the chart should match the color specified below for that category.
```
Tasks Identified (blue)
All Decisions
Full Grants
Partials/Remands

Activity (blue)
Active Users
Tasks Started
Tasks Completed

Completion Rate (blue)
All Decisions
Full Grants
Partials/Remands

Time to Claim Establishment (green)
All Decisions (median/95th percentile)
Full Grants (median/95th percentile)
Partials/Remands (median/95th percentile)

Cancellations (red)
All Decisions
Full Grants
Partials/Remands
```

2. Verify that for each statistic, for each time range ("Hourly", "Daily", "Weekly", "Monthly") the charts and numbers are accurate according to the descriptions below.

**Tasks identified** — task.created_at within the period, where this is the first task.created_at with a given task.appeal_id.

**Full grant** —We'd want to use appeal.full_grant? for this, but that's currently subject to a problem in that it uses the status of the case to determine. This works at the moment it is being dispatched, but after a remand is worked, it will be placed in HIS status and be marked as a full grant. We need to replace this method to instead use a count of the issues on the case. If the number of issues where ISSDC = '1' is greater than 0, but the number of issues where ISSDC = '3' is equal to zero, it's a full grant. Similarly, we can replace the partial and remand methods; if it has both 1s and 3s it's a partial, and if it has 3s but no 1s, it's a remand.

**Active users** — Uniqued `task.user_id` of those tasks where `task.completed_at` is within the period. Note that this includes cancellations as well as successfully established claims.

**Tasks started** — `task.started_at` within the period.

**Tasks completed** — `task.completed_at` within the period where `task.completion_status` is equal to "completed" (0).

**Completion rate** — The percentage of tasks completed within the period (`task.completed_at`) where `task.completion_status` is equal to "completed" (0).

**Time to claim establishment** — The difference between the `FOLDER.TIOCTIME` time from VACOLS and the `task.completed_at` time in days for tasks completed within the period (`task.completed_at`) where `task.completion_status` is equal to "completed" (0).

**Cancellations** — `task.completed_at` within the period where `task.completion_status` is equal to "canceled" (1).

# Mockups
**_View - Stats - Certification Daily_**
![dashboard daily](https://cloud.githubusercontent.com/assets/23063044/23275159/680652c0-f9d3-11e6-9f07-e30df1c44ffd.PNG)

## Notes
- To make the VACOLS load of calculating these stats a little smaller, it might be better to start caching whether a grant is Partial Grant, Full Grant, or Remand in Caseflow.
- @cmgiven can help verify these.

**Comment by tejans24** [comment]
@cmgiven A quite a few of these stats require information from VACOLS to get the status of an appeal. Those queries might be quite expensive to fetch the data. Let's have a chat to find a bit more efficient solution for this tomorrow. 

cc @shanear

**Comment by cmgiven** [comment]
I think the notion should be that we need to cache any such fields in Caseflow. But as far as I see, there are only two: the type of decision and the outcoding date. Both are already being used in the app, just perhaps not being cached.

**Comment by cmgiven** [comment]
There's an issue here. The logic assumes that there is not more than one task per appeal, but this is not necessarily the case. If a task expires (completion status of 2), it'll be recreated.

**Comment by joofsh** [comment]
To QA: Sharon is out on vacation, ping me if you find any issues

**Comment by kierachell** [comment]
![dispatchstats](https://cloud.githubusercontent.com/assets/18075411/25099611/0d541dfe-237b-11e7-8591-38deb203d993.gif)

Why are the displayed stats not changing on clicking different time periods?

Why is **Time to Claim Establishment** in minutes?

And that last box is wonky...

**Comment by kierachell** [comment]
**PASSED**

![dispatchstats](https://cloud.githubusercontent.com/assets/18075411/25346662/30707d94-28e6-11e7-8bc1-ef3041732eba.gif)
