### ISSUE TITLE
SyncIntakeJob reclosing ramp closed appeal fails with "AppealNotValidToClose"

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8190]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3070/

ramp_closed_appeal_id is 72882

Work involved is:
* identify why this failure is happening
* identifying what data changes are necessary, if anything
* implement data fix, if it fits in the scope of this issue

**Comment by pkarman** [comment]
Findings:

* The VACOLS case has a `bfdc` value of `G` ("Advance Failure to Respond").

**Comment by pkarman** [comment]
This script should have the steps involved: https://gist.github.com/pkarman/6f3a99e2c311fb6836c50d78672f1b79

@kencheeto would appreciate your eyes on this. Perhaps we could pair on running the fix?

**Comment by kencheeto** [comment]
@pkarman I'm not seeing this fail anymore - were you able to run this script? script lgtm, happy to pair

**Comment by pkarman** [comment]
looks like the VACOLS case `bfdc` value changed to `P` in the meantime.

**Comment by kencheeto** [comment]
this is coming up in https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3134/, we can reinvestigate

**Comment by pkarman** [comment]
another one: ramp_closed_appeal_id 85892

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3134/

**Comment by pkarman** [comment]
This fixed itself (again).

`RampClosedAppeal.find(85892).reclose!` finished w/o error.

**Comment by hschallhorn** [comment]
Another one! https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5865/events/406068/

**Comment by ajspotts** [comment]
One more! https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9521
