### ISSUE TITLE
SyncReviewsJob ramp refiling processing fails with DuplicateEp

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8191]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2919/

example claimant participant id is 6875270

There is one known issue where we need to wait for the EP code to free up. We should run a query and check if there are any ramp refiling processings failing for other reason, we can check:
```ruby
RampRefiling.where({
  establishment_submitted_at: (<long time ago>...(3.days.ago)),
  establishment_processed_at: nil
})
```

**Comment by shanear** [comment]
Closing, cause we are no longer processing RAMP Refilings
