### ISSUE TITLE
[BE] Improve document count and new documents performance

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8192]
We have been seeing `Response timeout of 60000ms exceeded` errors for new_documents and document_count endpoints. 

Note: We have a nightly Reader background job that downloads VBMS documents, saves the list in the Caseflow documents table and uploads these documents to s3. This job runs for users with a Reader role only.

Improvements to the above endpoints:
1. Include AMA appeals to the Reader background job.
1. Ensure all queue users are part of the Reader background job. How can we get a list of Queue users? Can we query for users who have logged in to Caseflow for the past 2 weeks and assume these users will need documents? Can we use attorney/judge mapping table or organizations table?
1. For the `document_count` and `new_documents` endpoints, do not make calls to VBMS and instead use Caseflow `documents` table to get results. 
1. Remove any VACOLS calls from the endpoints (?).

Attention! The above approach to use a Reader job might result in outdated content - 24 hours max.

**Comment by mdbenjam** [comment]
For point 2, I think we can just look at all the users with a "Reader" role. I think all Queue users should have it.

**Comment by aroltsch** [comment]
@hschallhorn When including AMA appeals to this job, we would have to only include actively worked appeals.You can get this information by looking at the `tasks` table that have non-completed status. The logic is something like that: get all non-completed tasks assigned to a user and query associated AMA appeals. 

As I mentioned before that's where you would include this query: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/fetch_documents_for_reader_user_job.rb#L18

Then you would need to make sure this method works for AMA appeals:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/fetch_documents_for_reader_user_job.rb#L45

**Comment by aroltsch** [comment]
Will create a separate ticket for Vacols calls
