### ISSUE TITLE
Universal Case Title (additional elements)

### ISSUE THREAD

**Issue by sneha-pai** [department-of-veterans-affairs/caseflow#8199]
#8150 began the process of moving our case-related information into a new element called Universal Case Title. Upon modifying other areas of case details, a few more elements were requested to be in this title area:
- VLJ on the case
- Attorney on the case
- if the veteran is the appellant or not
- if the case is a paper case

#### Narrow Width (768px)
![universal-case-title-expanded-768](https://user-images.githubusercontent.com/31224257/49819139-a4d6a780-fd42-11e8-8493-76d0f7853f97.png)

#### Wide width (1200px)
![universal-case-title-expanded-1200](https://user-images.githubusercontent.com/31224257/49819220-dc455400-fd42-11e8-825a-aa260024a95b.png)

@lowellrex @rkreyhsig @laurjpeterson @allyceh @eric-nava please provide feedback in comments below. Feedback specifically needed on:
- Feasibility of this data being able to display in these two different widths (depending on browser width on-load)
- This element has gotten quite tall - is that a problem?
- Overall composition critique
- any alternative approaches not proposed

**Comment by lowellrex** [comment]
> * Feasibility of this data being able to display in these two different widths (depending on browser width on-load)

I personally don't know how to achieve the effect of different background colors for the first and second line of that list when we rely on the browser width to determine which elements get pushed onto the second row (and couldn't find any readily-googleable techniques to do that a few minutes of searching). So that might be tough to do (maybe @joeyyang has thoughts on how to accomplish this?). Would it be bad to have the same light grey background for both lines?

**Comment by sneha-pai** [comment]
It wouldn't be bad to have the same light grey for both lines. I can update the mock to reflect this.

**Comment by allyceh** [comment]
This looks good! A couple comments: 

- We could shorten the "The veteran is not the appellant" and "This is a paper case" to "Contested claim" and "Paper case". As I learn more about contested claims, that is the verbiage that seems to resonate most with everyone. "The veteran is not the appellant" can mean two things, 1) the claim is contested, or 2) the veteran is deceased, and a surviving spouse wants the benefits (not a contested claim). 
  - Are we looking to communicate both here, or just one of those things?
- We could consider using the same text style for both, unless there is a good reason for making one italics + one non-italics
