### ISSUE TITLE
PDF Generation: Automatically fill out 17A and 17B

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#82]
These fields are for name (17A) and title (17B). 

Sub-tasks

- [x] Investigate the legality of pre-filling this
- [ ] Remove 17A and 17B from questions page (if legally able to remove)
- [x] Pre-fill using SSOi information

**Comment by alex** [comment]
Suggestion for if we have can't legally remove them: have the fields be pre-filled out, but still editable

**Comment by gmorgana-va** [comment]
We can proceed to pre-fill the name based on the authenticated user account.  Based on conversations with @KHarshawat, the name field should continue to be visible to the user on the questions page, but not editable.  Since we are unable to pull title information via SSOi, this field should remain fillable by the user.

**Comment by alex** [comment]
Ok. Not going to actually work on this until we have SSOi in production
though.

On Tue, Nov 17, 2015 at 3:08 PM, Giuseppe Morgana <notifications@github.com>
wrote:

> Assigned #82
> <https://github.com/department-of-veterans-affairs/caseflow/issues/82> to
> @alex <https://github.com/alex>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/82#event-467142864>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
We prefill 17A with the user's name now. 17B is still empty.

**Comment by KHarshawat** [comment]
Closing this issue.
