### ISSUE TITLE
Exclude production gems by default from bundler

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#82]
Using this feature:
https://github.com/bundler/bundler-features/issues/68

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
