### ISSUE TITLE
Do not throw Sentry error when issue is not found

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8204]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2365/

![image](https://user-images.githubusercontent.com/3811786/51038058-142cfa80-1580-11e9-9b5a-c748bbd2bc96.png)

![image](https://user-images.githubusercontent.com/3811786/51038070-1ee78f80-1580-11e9-9bcd-8fbddd31cf6c.png)

**Comment by monfresh** [comment]
Would it be possible to paste the stack trace in here for those of us who don't have access to Sentry yet?
