### ISSUE TITLE
Form 8 | Incorrect Completion directions

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#821]
# Description
At the top of the `Form 8` page in the instructions, there is a statement that says click **continue** button, which does not exist.  The instructions should say click **_Preview Completed Form 8_**. 

**Environment:**
- [x] Production
- [x] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [x] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
Scenario 1 
1. Log into Certifications
1. The `Form 8` page is displayed.  Instructions at the top of the page is incorrect.

# Screen Shots
**_Scenario 1 - `ALL` Page/Endpoint Title and actions taken_**

![form8continue](https://cloud.githubusercontent.com/assets/18075411/22605377/92a528b4-ea1d-11e6-8094-0ecee84228e1.gif)

# Relate Stories/Issues

**Comment by shanear** [comment]
good catch @kierachell

**Comment by kierachell** [comment]
**PASSED** 💯 
<img width="1005" alt="screen shot 2017-03-10 at 10 36 43 pm" src="https://cloud.githubusercontent.com/assets/18075411/23820221/22dd936e-05e2-11e7-8431-5c5722e727c8.png">
