### ISSUE TITLE
Show task instructions for caseflow tasks associated with legacy appeals

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8210]
Currently [we only show the task's instructions field](https://github.com/department-of-veterans-affairs/caseflow/blob/ea7373248eac68e41b951c6ddc46a645e6050730/client/app/queue/CaseSnapshot.jsx#L159) for tasks associated with AMA appeals. This makes sense for legacy tasks associated with legacy appeals since those types of tasks will not have any instructions. However, since we now associate caseflow tasks with legacy appeals we should show the instructions field when the task has that field.

## Acceptance criteria
* [ ] Show task instructions for caseflow tasks associated with legacy appeals.

**Comment by laurjpeterson** [comment]
I think we're already doing this, so closing.
