### ISSUE TITLE
Universal case title epic

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8211]
#7903 began work on implementing a new design for a "universal case title". This epic exists to track all tasks related to completion of work on the universal case title.

## Mocks

![universal-case-title-expanded copy 3](https://user-images.githubusercontent.com/31224257/49304029-46374100-f499-11e8-8d41-77aaccf1bce2.png)

![universal-case-title-expanded copy 4](https://user-images.githubusercontent.com/31224257/49304030-46374100-f499-11e8-87a5-6a8aa004a63f.png)

![universal-case-title-expanded copy 5](https://user-images.githubusercontent.com/31224257/49304031-46374100-f499-11e8-98c7-4d44d30aa635.png)

![universal-case-title-expanded copy 6](https://user-images.githubusercontent.com/31224257/49304032-46374100-f499-11e8-9025-4bd9cf3e6597.png)

![universal-case-title-expanded copy 7](https://user-images.githubusercontent.com/31224257/49304033-46374100-f499-11e8-9b2f-3cd7292cff50.png)

![universal-case-title-expanded copy 8](https://user-images.githubusercontent.com/31224257/49304034-46cfd780-f499-11e8-94ae-f398ae8f6a88.png)

#### When document ID is added (after attorney check out to judge)
![universal-case-title-when-doc-id-is-added](https://user-images.githubusercontent.com/31224257/49303223-2bfc6380-f497-11e8-9560-798b577e6689.png)

#### Narrow Width (768px)
![universal-case-title-expanded-768](https://user-images.githubusercontent.com/31224257/49819139-a4d6a780-fd42-11e8-8493-76d0f7853f97.png)

#### Wide width (1200px)
![universal-case-title-expanded-1200](https://user-images.githubusercontent.com/31224257/49819220-dc455400-fd42-11e8-825a-aa260024a95b.png)

**Comment by hschallhorn** [comment]
Closed in #8213!
