### ISSUE TITLE
Add link/button to show/hide task instructions

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8217]
![image](https://user-images.githubusercontent.com/32683958/49831646-66e97b80-fd62-11e8-969b-0dd5f09c28cb.png)

## Acceptance criteria
* [ ] Show/hide the task instructions when clicking the "View task instructions" link for tasks in the active tasks component
* [ ] Show/hide the task instructions when clicking the "View task instructions" link for tasks in case timeline

## Non-goal
* "+ Add a new task" button will not be implemented as part of this ticket.

**Comment by rkreyhsig** [comment]
@sneha-pai @allyceh @eric-nava I don't believe we have the comment icon for the link/button yet.  We will push the functionality with just the text for now.
