### ISSUE TITLE
Group sibling ColocatedTasks in active tasks component

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8218]
![image](https://user-images.githubusercontent.com/32683958/49832380-7d90d200-fd64-11e8-8aff-2a4761457d7e.png)

## Acceptance criteria
* [ ] Group `ColocatedTask`s that were created on the same day and have the same parent task when those tasks appear in the active tasks component

## Non-goal
* Showing/hiding the task instructions when clicking the "View task instructions" link will not be implemented as part of this ticket.
* "+ Add a new task" button will not be implemented as part of this ticket.

**Comment by laurjpeterson** [comment]
@lowellrex - is this done?

**Comment by lowellrex** [comment]
> @lowellrex - is this done?

It is not yet done.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||
5 | |||||
8 | 
```

Why 3?
- Front end querying tasks from backend could be fairly tricky

Why 5?
- A lot of modification to the logic of case timeline
