### ISSUE TITLE
Display incomplete but non-actionable tasks in case timeline

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8220]
![image](https://user-images.githubusercontent.com/32683958/49833811-a31fda80-fd68-11e8-9bbd-0b7040a318e2.png)

## Acceptance criteria
* [ ] Display incomplete but non-actionable tasks in case timeline

**Comment by lowellrex** [comment]
@allyceh @eric-nava @sneha-pai Would it make sense to move the case timeline further up the page so that it is close to the task snapshot?

**Comment by eric-nava** [comment]
> @allyceh @eric-nava @sneha-pai Would it make sense to move the case timeline further up the page so that it is close to the task snapshot?

This is something Sneha and I were discussing just now. If the intention of the timeline is to provide  information that is relevant to an action that any user needs to take, then re-prioritizing it wouldn't be bad. Conversely, it is structured similarly to the snapshot, so will users understand the difference between the two components? (open question - more rhetorical for the time being)

**Comment by allyceh** [comment]
@lowellrex @eric-nava @sneha-pai I'm not opposed to changing the hierarchy! I've talked to a few attorneys/judges in the past few months who didn't even know timeline was there or didn't look for it. We had to tell them to scroll to the bottom of the page. 

For context, how many past actions are we expecting are displayed in the timeline? Do we have any prediction of what the median amount will be?

**Comment by lowellrex** [comment]
Using the 103 RAMP appeals that have already been dispatched from the Board it looks like 6 is the median number of tasks we can expect in the case timeline.

![image](https://user-images.githubusercontent.com/32683958/51121454-7f2b3b00-17e5-11e9-97c4-bba156194e17.png)

I also expect the appeals with 8 and 9 tasks may actually have 1 or 2 fewer tasks that show up in the case timeline because we don't usually display tasks in the case timeline that are assigned to organizations (I've made this correction for the appeals with 6 tasks since it was easy).

```ruby
rails c> inactive_appeals = Appeal.select { |a| !a.active? && !a.decision_date.nil? }
rails c> task_counts = inactive_appeals.map { |a| a.tasks.count }.sort
```
