### ISSUE TITLE
Connect multiple request issues to decision issues

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8221]
*"Merging" request issues one decision issue*
- As an attorney, I need the ability to add the same decision to another request issue to better reflect what the veteran is appealing. This is the scenario where two request issues align with one decision issue. 
    - Real life scenario from Rachel: I think the most common example would be psych. We get a two issue appeal - depression and PTSD, and we determine that the diagnosis is depression so we merge them.
  - Acceptance criteria: 
       - When a user adds a decision, they are only able to add the decision to request issues that don't already have a decision attached.
       - When a user adds a decision and all request issues already have decisions attached, we don't display the "issues" dropdown in the modal. 
- As an attorney, I need the ability to add more than one decision to two or more request issues. 
    - Example: The attorney adds the same decision (depression) to two request issues (depression and PTSD). They also need to add an additional decision to those issues (TDIU). 
    - Note: After the same decision has been added to multiple request issues, the attorney is unable to add decisions to individual request issues. They must add them to the group of request issues they've "merged". 

## AC
-

**Comment by mdbenjam** [comment]
Is this still relevant? I think we've implemented this right?

**Comment by aroltsch** [comment]
Yes, it is done.
