### ISSUE TITLE
Intake | Slow BGS sync

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#8227]
Follow on to #7753 

e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2935/

We periodically see time out errors executing long-running processes talking to BGS. Let's see if we can track those down and/or work around them.

**Comment by msj0nes** [comment]
Closing this ticket. Last alert reported Jan 16, 2019 1:54:20 PM EST. Reopen ticket if alert resurfaces.
