### ISSUE TITLE
[FE] Cannot read property 'isLegacyAppeal' of undefined

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8229]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3139/

**Comment by aroltsch** [comment]
Was not able to re-produce it - will wait until it happens again.

**Comment by monfresh** [comment]
I cannot reproduce this. Can you show me how? Does it depend on the case?

**Comment by aroltsch** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3457/

**Comment by aroltsch** [comment]
Has not happened for some time. Closing.
