### ISSUE TITLE
Transcription MVP decisions

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8231]
Overall Strategy based on brainstorming for 12/12/18 
* Hold off on any bulk/fancier UI for transcription -- have this in place for April 2019 hearings. 
* For mid/end of January time frame - looking to design the manual process 
* Shelly's designs for Hearing details make sense for the manual process. 
* Make sure Task model behind the scenes is developed (trees, tasks, blockers) 
* Make sure UI keeps in mind the task model, and then task model is updated to reflect UI changes, but UI doesn't run amok of the task model.

**Comment by MeredithStewart** [comment]
Followup: We will have another session for next week to determine the Task Model tree for transcription and what our UI direction is (Is it all tasks in Case Details and an org queue/individual queues)

**Comment by ShellySmithDSVA** [comment]
Mural covering our AMA AOD Manual flow 
https://app.mural.co/invitation/mural/workqueue2001/1544628544124?sender=michellesmith77044&key=e879c270-9623-4d56-93e8-01abb8d3c89e

**Comment by ShellySmithDSVA** [comment]
https://va-gov.invisionapp.com/share/F6PQEGF2BTJ#/screens
https://app.mural.co/t/workqueue2001/m/workqueue2001/1544628544124/9024a431d5b9751d3ac144203bbc0f31d45f782d

We are leaning toward a Transcription Queue idea, although that may not be MVP.

**Comment by ShellySmithDSVA** [comment]
Hearing Details Pre-MVP will be built first. This will be the Hearing Worksheet, VACOLS message, and Judge/Attorney views.

Task Flow Mural
https://app.mural.co/invitation/mural/workqueue2001/1545855493430?sender=michellesmith77044&key=17741766-fecf-4a59-8495-844088c3a6ba

Mocks here
https://va-gov.invisionapp.com/share/TKPRX5QUMRW#/338332664_Daily_Docket_W_Hearing_Details
