### ISSUE TITLE
Add "Return to attorney for corrections" option for JudgeDecisionReviewTasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8233]
After a decision has been drafted judges will occasionally return cases to attorneys to make corrections or rewrite the decision. We need to support this action in Caseflow for AMA cases. On 12 December 2018, we manually accomplished the same result by updating the judge task's type and status and the attorney task's status (see the [related slack conversation](https://dsva.slack.com/archives/C6E41RE92/p1544627868008000)). For this ticket we will implement a more robust solution explicitly creating a specific `AttorneyRewriteTask` in this scenario.

## Acceptance criteria
* [ ] Judges have an option to return a case to an attorney after that attorney has drafted a decision on the case
* [ ] Returning the case to the attorney creates a new `AttorneyRewriteTask`

**Comment by laurjpeterson** [comment]
@lowellrex, @tomas-nava - will this be implemented only for AMA cases, or both AMA and legacy? (thinking just AMA, but want to explicitly confirm.)

**Comment by lowellrex** [comment]
This will be implemented for all cases that have been kicked back to the judge from the quality review team in Caseflow. Currently the only cases we are selecting for QR in Caseflow are AMA cases, but eventually I expect it will include Legacy cases as well. This approach should support Legacy cases as well (though the case will not be reassigned in VACOLS).

**Comment by laurjpeterson** [comment]
Got it. I created another GH issue so we can return to attorney for corrections for all JudgeDecisionReviewTasks, not just ones that came back from QR - https://github.com/department-of-veterans-affairs/caseflow/issues/8763

**Comment by lowellrex** [comment]
I actually think I'm mistaken. We can already do the thing I'm describing. I didn't properly read this ticket and was thinking about a different ticket. My apologies!

**Comment by lowellrex** [comment]
To answer the original question, this ticket only addresses AMA cases. We will need to create another ticket to do the same work for Legacy cases.
