### ISSUE TITLE
Display information from previous checkouts when attorney goes through checkout for a rewrite

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8234]
#8233 allows judges to return cases to attorneys for corrections/rewrites. This ticket exists to display information from the previous attorney checkout on the final page of the checkout process when an attorney goes through the checkout process for a rewrite.

This issue was brought to light as the result of us manually returning a case to an attorney from a judge on 12 December 2018 (see the [related slack conversation](https://dsva.slack.com/archives/C6E41RE92/p1544627868008000)).

## Acceptance criteria
* [ ] Display information from previous checkouts when attorney goes through checkout for a rewrite

**Comment by laurjpeterson** [comment]
@lowellrex do you mean to pre-fill information from past checkout on the last screen? this would include:
- document ID
- assigned judge
- previous notes to judge?

**Comment by lowellrex** [comment]
Exactly

**Comment by laurjpeterson** [comment]
Excellent, thanks. @aroltsch - does it look like we can pull this one into this sprint too, or next?
