### ISSUE TITLE
Intake | Audit database columns

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8239]
`request_issues` and `decision_issues` have a lot of columns now, and as we've been developing, we've noticed that there isn't a tight definition of what they represent. Additionally, many of them may not be necessary anymore.

Prioritizing this because PA&I is going to retrieving metrics from a direct connection to our database. It needs to be intelligible and well defined.

Additionally, well defined columns will prevent confusion as we continue to build features and fix bugs

## Proposals
**request_issues**
1) __DONE__ change `review_request_type` and `review_request_id` to `decision_review_type` and `decision_review_id`. _This matches the terminology used everywhere else in Caseflow_

1) __DONE__ change from `rating_issue_profile_date` to `contested_rating_issue_profile_date` and `rating_issue_reference_id` to `contested_rating_issue_reference_id`. _This is to better match the naming of `contested_decision_issue_id`. Also adding `contested_` as a prefix better describes the relationship of the request issue to the rating issue._

1) __DONE__ change `contested_rating_issue_profile_date` from datetime to string. _This is because this field is used as an identifier to retrieve the appropriate rating from BGS. Having it as a datetime causes time zone logic to break the identifier, since it needs to be in the exact timezone it was returned in_

1) __DONE__ Add `contested_rating_issue_description`, and use that instead of `description` for the rating issue description. _The `description` column is overloaded and causes `description` to sometimes not represent the actual description. Instead, we should reserve `RequestIssue#description` for a method that combines `contested_rating_issue_decision_text` or `nonrating_description` properly._

1) __In Progress__ change `issue_category` to `nonrating_issue_category`, `decision_date` to `nonrating_decision_date`, and `description` to `nonrating_description` _This better designates that these fields are only used if the issue is a nonrating issue._
Note - we are now using decision_date for rating_issue_promulgation_dates, so we will not rename that at the moment.

1) __DONE__ Remove `disposition`. _This is tracked via `decision_issues` now. If we need request issue dispositions, we can calculate those as a function of the decision issues._

1) __DONE__ Remove `parent_request_issue_id`.  _The only place this is used is `RequestIssue.no_follow_up_issues`, which is not used. So we can delete that method too._

## decision_issues

1. __In progress__ rename `promulgation_date` to `rating_issue_promulgation_date`, and `profile_date` to `rating_issue_profile_date` _This better signifies that these fields apply to the rating issue._

1. __DONE__ Add `created_at`. _This field is on `request_issues` and even though it's not used, it can be helpful in debugging and understanding the data. So we should probably add it._

## rating_issues
__DONE__ There is still a `rating_issues` table, which is unused so we should probably remove it.

However, after finishing this audit, it's becoming clear that we would be adding `rating_issue_` as a prefix to a good number of columns on both `request_issues` and `decision_issues`. This might be a sign that we should just add the rating_issues table to store all of these values. Not sold on that idea though.

**Comment by leikkisa** [comment]
This looks good, I like the idea of cleaning them up!

Are contested_rating_issue_description and contested_rating_issue_decision_text two different fields?

It sounds like there's possibly a good case for separating rating and non-rating issues into their own separate tables, which you hinted at in the last paragraph.

**Comment by aroltsch** [comment]
@pkarman suggested to rename `request_issues.decision_date` to  `nonrating_profile_date`

**Comment by aroltsch** [comment]
I personally would prefer to use `rating_issues` table to store some of these fields if possible. It is becoming more and more complicated to understand what all these columns mean on request_issues and decision_issues.

**Comment by pkarman** [comment]
I believe `rating_issues` table is set to be dropped, since we moved to syncing upstream ratings with the `decision_issues` table instead.

I agree about knowing what columns do what. There's been a lot of cooks in this kitchen. @shanear is working on a schema audit that might help #8239

**Comment by kencheeto** [comment]
do benefit types propagate for contestable nonrating issues chosen in the first add issues modal

**Comment by pkarman** [comment]
they will need to, yes. see #8619 (which needs more details still).
