### ISSUE TITLE
Add user column to team queue table

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8241]
We want to add the user column to team queues so supervisors and team members know who is working on tasks. 

This is especially important if teams decide to have users self-assign work (like the Hearings Management Branch has suggested), or reassign work when users are out on leave. 

## AC
- User column exists on team queue, `Assigned` and `Completed` tab

#### User column on "Assigned" tab
![colocated-table-team-cases-768](https://user-images.githubusercontent.com/31224257/51272127-4337d780-1997-11e9-87ef-f900cd68ae14.png)

#### Considerations and implications:
- to add this column (and especially to suit our narrowest browser width specifications), I removed "Type" column (Original, CAVC, Reconsideration, etc). [now outdated]
   [UPDATE]:  I've reintroduced type column and omitted veteran documents column.

## Open questions [all resolved as of 01/16/19]
- is it easier to add user column to all tabs, even though the `Unassigned` tab doesn't have assigned users? 
          - Sneha: Adding this column requires sacrificing another important column that may be useful when viewing team cases. I think we should limit adding this column only to assigned and completed tabs.
- Is it okay to remove "type" column? If not, which other column would we want to remove in order to add the "assigned to" column?

**Comment by sneha-pai** [comment]
@laurjpeterson can you please have a look at the proposed mock, and questions around if we include this column, which other column do we not show?

**Comment by laurjpeterson** [comment]
thank you @sneha-pai! 

>is it easier to add user column to all tabs, even though the Unassigned tab doesn't have assigned users?
>- Sneha: Adding this column requires sacrificing another important column that may be useful when viewing team cases. I think we should limit adding this column only to assigned and completed tabs.
- Ok

>Is it okay to remove "type" column? If not, which other column would we want to remove in order to add the "assigned to" column?
- I think I'd prefer to remove the link to Reader, since users can navigate to Reader from Case Details
- Type is important for AOD, CAVC, etc. for legacy cases. 
- I'd love @MeredithStewart @Chingujo @laurenrussell 's eyes on this too, for their thoughts on this w/r/t hearing branch

**Comment by laurenrussell** [comment]
@laurjpeterson I would agree, in that Type is important to stay on track when filling the docket.

**Comment by laurjpeterson** [comment]
Note: VLJ support staff would benefit from the user column on the team queue soon as well, so they can easily know when they need to reassign cases from user to user. cc: @sneha-pai @mdbenjam
