### ISSUE TITLE
Add metric to track stale appeals

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8251]
A member of the board [recently changed their CSS ID](https://github.com/department-of-veterans-affairs/caseflow/issues/8178) which caused us to disassociate the person from tasks that were previously assigned to them. We discovered this by accident (see the previously linked ticket) but we have the ability to discover these scenarios through the power of metrics! This ticket exists to create a new query that tracks the time an appeal was most recently touched so we can see when appeals start to go stale. A quick sketch of how this query might look is below.

```sql
select
  appeal_id,
  appeal_type,
  max(updated_at) last_touch
from public.tasks
where appeal_id in (
  select
    appeal_id
  from public.tasks
  where status <> 'completed'
)
group by appeal_id,
  appeal_type
order by last_touch;
```

[Results of this query on looker](https://caseflow-looker.va.gov/sql/fjzsxysdgggygw).

I haven't actually run that query so it might not work (or be optimized at all), but the general outline is there. We will probably want to account for things like only a root task existing (we could exclude that type from the nested select statement?) and we will probably want to see which task types have actually been created (maybe a group_concat of type in the main select?), but I think this is a good jumping off point.

**Comment by hschallhorn** [comment]
@pkarman Is this still echo or is this something for delta to handle as well?

**Comment by pkarman** [comment]
delta can take. we have implemented some of this already in other ways but good to refer to this to make sure we have covered the same problem space.
