### ISSUE TITLE
Reorganize feature tests

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8257]
Following discussion in https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1083, we've decided on a few proposals:

1. Factor out feature tests into a file for each 'page'
1. Within each page feature test file, organize contexts by what tests are common to types of decision reviews and make explicit contexts for what is unique to one type of decision review

This issue is for the first pass at reorganizing feature tests into files for each page. This is intended to give just enough structure for others to easily identify where to write new tests, so do not spend time on any refactoring unnecessary to split the tests into each file (i.e. duplication at first is OK). Focus on making the file divisions clear first, and write up followup issues for significant chunks of work that you identify during this issue.

**Comment by laurjpeterson** [comment]
@pkarman can we close this one? i see ken's merged PR above
