### ISSUE TITLE
Appeal Outcoding | Poll for promulgated rating when Board Grant EPs are cleared

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8265]
The purpose of creating EPs and contentions is so we can figure out which rating issues were created as a result of which decision issues. In this story we will be retrieving the promulgated rating and matching the rating issues to their decision issues.

## Acceptance Criteria
- All board grant EPs created as part of #8263 should be continuously polled to check whether they have cleared.
- When a board grant EP has been cleared, we should then begin checking for the promulgated rating associated with that EP.
- Once the promulgated rating is found, connect each rating issue with its matching decision issue in the database. Decision issues can be matched based on contention reference id.

## Notes
- If there are any rating issues where a matching decision issue cannot be found. Do nothing for now, this will be handled in a future story.
- rating EPs when cleared don't always get ratings (we might want to add a timeout of 10 days or something), should do this work in a followup

## Technical Notes
- Most of the logic required for this story already exists, we just need to repurpose it to work with board grant EPs.

requires #8263
requires #8266

**Comment by steve-gov** [comment]
Compensation nonrating issue outcoded: https://appeals.cf.uat.ds.va.gov/queue/appeals/098cf858-9e94-4337-aa40-e3c5e0d3d457

Either the EP wasn't created or is stuck in a queue; checking to see which of these is true.

**Comment by steve-gov** [comment]
Setting up validation: passing EP `031` on file `123458318` (created as part of #8263) to AMO for rating.

**Comment by steve-gov** [comment]
Based on the investigation in #9086, EP `031` on file `123458318` (issue `600148621`) should fit the criteria for validation.

**Comment by shanear** [comment]
looks like this worked:

effectuation was processed:
```
 #<BoardGrantEffectuation:0x000055db29132e28
  id: 11,
  appeal_id: 88,
  granted_decision_issue_id: 69,
  end_product_establishment_id: 752,
  contention_reference_id: "315079",
  decision_document_id: 25,
  decision_sync_submitted_at: Wed, 30 Jan 2019 14:20:08 UTC +00:00,
  decision_sync_attempted_at: Wed, 30 Jan 2019 14:22:13 UTC +00:00,
  decision_sync_processed_at: Wed, 30 Jan 2019 14:22:18 UTC +00:00,
  decision_sync_error: nil,
  last_submitted_at: Wed, 30 Jan 2019 14:20:08 UTC +00:00>]
```

rating issue ref id was added

```
#<DecisionIssue:0x000055db28bc69d0
 id: 69,
 disposition: "allowed",
 description: "anya test",
 promulgation_date: Tue, 29 Jan 2019 14:14:52 UTC +00:00,
 profile_date: Tue, 29 Jan 2019 14:08:37 UTC +00:00,
 participant_id: "600233673",
 rating_issue_reference_id: "123318",
 decision_text:
  "Service connection for anya test is granted with an evaluation of 10 percent effective December 1, 2018.",
 decision_review_type: "Appeal",
 decision_review_id: 88,
 benefit_type: "compensation",
 end_product_last_action_date: nil,
 diagnostic_code: "5000",
 caseflow_decision_date: nil>
```
