### ISSUE TITLE
Fix decision issue attorney magic bug

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8269]
Issue editing for AMA decision issues is broken. To re-produce locally enable `ama_decision_issues` flag.

Currently, dispositions are only set for remanded issues, the rest of the issues are not even sent to the BE.

AC:
Fix AMA "new" checkout using decision issues

**Comment by monfresh** [comment]
For anyone new to the project, the following steps to reproduce might be helpful:
1. Run the app locally and go to http://localhost:3000/test/users
2. Switch to the user BVASCASPER1 (attorney with cases)
3. Click on `Your Queue`
4. Click on the first item under Case Details (http://localhost:3000/queue/appeals/e15981c8-c9c8-4b25-b3d6-f17df2e19e2b)
5. Under the `Actions` dropdown, select `Decision Ready for Review`
6. On the next page, click Continue
7. On the `Add decisions` page, click on "Add decision" for each issue, and for each one except for the last one, fill out everything with "test" in the text field, `Allowed` for the Disposition, and `Compensation` for the Benefit type.
8. For the last one, set the Disposition to Remanded
8. Click "Continue".
9. Select a reason for the Remanded disposition then click Continue
10. You should now be on the "Submit Draft Decision for Review" page
11. Click the "Back" button at the bottom of the page (not the browser back button)

Expected Result: You are back on the Add decisions page, and everything entered on Step 7 is still visible

Actual Result: Only the remanded decision has been saved

To test that all decisions have been saved after submitting the review:
1. From the "Submit Draft Decision for Review" page, enter any Document ID and choose a judge. Make a note of both the Document ID and the judge you chose as you will need them in the next steps.
2. Go to http://localhost:3000/test/users and switch to the judge you chose in step 1
3. Click on "Your Queue"
4. Click on the entry with the same Document ID you entered in Step 1

Expected Result: In the list of "Issues", all decisions, both allowed and remanded should be visible.
