### ISSUE TITLE
Remove Pending Action tab

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8277]
The current implementation of the Pending Action column is complex. Cases move to Pending Action if there are new documents, or if a case put on hold has finished their hold. 

## Proposed changes
- **For cases with new documents**
   - Change implementation to only show icon if new documents have been added since the date the case status changed to `in-progress` - https://github.com/department-of-veterans-affairs/caseflow/issues/7777
   - Keep cases with new documents in the On Hold tab
   - If cases have new documents in the On Hold tab, show new documents icon in the tab itself
   - Continue showing new documents icon next to Reader link, per case with .new documents (as is currently implemented today)

- **For cases that have finished their holds**
   - Change "New" tab to read "Assigned". Move cases to the Assigned tab
   - When cases come back from "on-hold" to "assigned" tab, their aggregate days waiting should be displayed (total days consecutively in this user's queue (including hold time). This can act as a quick cue to help users understand that these aren't freshly assigned cases. 

### Mocks for cases that have finished their holds ( in assigned tab) 
![colocated-table-your cases-overdue-tasks](https://user-images.githubusercontent.com/31224257/52253227-989b4080-28d4-11e9-9af9-9c404bcc87cc.png)

### Optional mocks for slider-style indicator of proportion of hold (in on-hold)
![colocated-table-your cases-on-hold-optional](https://user-images.githubusercontent.com/31224257/52253248-b8326900-28d4-11e9-9ea2-c03f5d2faa01.png)

**Comment by MeredithStewart** [comment]
For both Option 1 and Option 2, I think we should have an idea of what it looks like when the hold is over and what it looks like in either of those two columns. Right now I could imagine both options working, but there might be a preference based on how it would work in either of the two columns. 

Also, testing of those two options might be good -- because users might prefer the first tab to be -- all things I need to do. Or they might prefer Option 2. (I think for me, I'm leaning towards option 1).

**Comment by lowellrex** [comment]
Second @MeredithStewart on all of the above. Leaning towards option 2, but think it'd be good to get some user feedback on this as well (maybe we could interview folks after we've released option 2 just to get something out the door quicker?).

As for the rest of the plan, I think that looks great!

**Comment by joeyyang** [comment]
I don' think I know enough about the new documents case to give a good opinion, but for cases that have finished their holds, I like option 2 because it clearly divides the tasks into two categories:
- tasks you can and should do something about now
- tasks you can't do anything about now

**Comment by lowellrex** [comment]
Fix for the issue mentioned in [this comment](https://github.com/department-of-veterans-affairs/caseflow/issues/8095#issuecomment-448296003) will relate to the solution here.

**Comment by lowellrex** [comment]
If it is easy to take steps to improve the task table at the same time [as per this tech spec](https://github.com/department-of-veterans-affairs/caseflow/issues/7863) then we should do that as part of this work as well.

**Comment by hschallhorn** [comment]
Do we think users will need a visual cue to indicate that a task has finished its hold or will a 60+ days waiting value be good enough?

**Comment by laurjpeterson** [comment]
Ooh good q. Tagging @sneha-pai for her input. A while ago we toyed with an icon that kinda looked like a clock.

**Comment by hschallhorn** [comment]
Closed in #8908
