### ISSUE TITLE
[Investigation] Determine from where we can get sensitivity level for an appeal

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8279]
https://github.com/department-of-veterans-affairs/caseflow/issues/6279

**Comment by pkarman** [comment]
sensitivity level is per veteran, and we do that via BGS and current user matrix. See e.g. https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/bgs_veteran_station_user_conflict.rb
