### ISSUE TITLE
[FE] Submit Draft Decision| Back Button goes to a Blank screen

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8280]
https://github.com/department-of-veterans-affairs/appeals-support/issues/3392

**Comment by monfresh** [comment]
I cannot reproduce the issue as originally written. I tried in Chrome and Safari on macOS Mojave. What I see when I click the "Back" button at the bottom of the "Submit Draft Decision for Review" page is the "Add decisions" page with everything I had filled out still saved (assuming all dispositions are set to Allowed; I found a bug if one of the dispositions is set to Remanded). The `appeals-support` issue linked at the top of this page also suggests that this is no longer an issue. Have we gotten new reports of this bug?

**Comment by aroltsch** [comment]
@monfresh Perfect. It has been resolved. We can close it.
