### ISSUE TITLE
Appeal Outcoding | Create Board Grant tasks on outcoding for non comp issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8283]
If a board grant is made on a decision issue that is not compensation or pension, the effectuation will not be tracked as part of an EP, but as part of a Caseflow task in the non comp queue described in #7990.

requires #7990

## Acceptance Criteria
When a board appeal is outcoded, after the decision document has been uploaded in the outcoding job referenced in #8262:
- If there are any granted issues on the appeal that have a benefit type other than compensation or pension, a "Board Grant" task should be created for the appropriate business line(s) based on the benefit type(s) of the decision issue(s).
- This task should appear on the non-comp landing page referenced here: https://github.com/department-of-veterans-affairs/caseflow/issues/7990 with the same columns

## Notes
- Issues on appeals are not limited to just one benefit type, so there may need to be multiple board grant tasks for one appeal.
- The task is more accurately known as an effectuation task. That word might be helpful when naming things.
- _Out of scope:_ what happens when you click on the task. That will be handled in https://github.com/department-of-veterans-affairs/caseflow/issues/8299

## Mocks
![returning disposition main](https://user-images.githubusercontent.com/1596259/50028070-478d6100-ffa3-11e8-984e-d2f46ede9f97.png)

**Comment by jiahuang** [comment]
@steve-gov it will be easier to wait on validation for this ticket until #8299 is done

**Comment by steve-gov** [comment]
Creating validation data for this story:

Added two issues to a Board Appeal in the Direct Review docket for `123458319 ` (LOB: Category: Decision Date):
- Education: Accrued: 12/31/2018
- Loan Guaranty: Other: 11/30/2018

Created appeal: https://appeals.cf.uat.ds.va.gov/queue/appeals/79630ab6-b9dd-443c-b38b-39e49fe59843

**Comment by steve-gov** [comment]
Validated: both issues created a task in their respective LOBs.

<img width="839" alt="screen shot 2019-01-28 at 12 02 14 pm" src="https://user-images.githubusercontent.com/25468689/51862943-9fceb700-22f4-11e9-95f9-27f4487ebc02.png">

<img width="839" alt="screen shot 2019-01-28 at 12 02 33 pm" src="https://user-images.githubusercontent.com/25468689/51862954-a78e5b80-22f4-11e9-9cda-faf5d4b2315e.png">
