### ISSUE TITLE
Appeal Outcoding | Non-comp effectuation task page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8299]
If a board grant is made on a decision issue that is not compensation or pension, the effectuation will not be tracked as part of an EP, but as part of a Caseflow task in the non comp queue described in #7990. The effectuation of these granted issues will need to be recorded via this page.

requires #8283 

## Acceptance Criteria
- When a user clicks on a "Board Grant" task on the non-comp landing page, it should take them to the "effectuation" page (see the mock below)
- The page should only show granted issues for the business line the task was clicked from.
- The "Cancel" button should send the user back to the non-comp landing page.
- When on the effectuation page, if the "I certify these benefits have been effectuated" checkbox is clicked the "Confirm" button should become active.
- When the "Confirm" button is clicked. The task should be completed, which should record the time it was completed and the user who completed it. It should move the task from the "In Progress" tab to the "Completed" tab. 
- When the "Confirm" button is clicked, the user should be redirected back to the non-comp landing page.

## Mocks
![effectuation](https://user-images.githubusercontent.com/1596259/50025016-10b24d80-ff99-11e8-826a-5d961e3c5e01.png)

**Comment by kencheeto** [comment]
@shanear i added `When the "Confirm" button is clicked, the user should be redirected back to the non-comp landing page.` but lmk if that is wrong

**Comment by steve-gov** [comment]
Will validate after #8283 validates and one of its issues is outcoded as a Board Grant.

**Comment by steve-gov** [comment]
Outcoding successfully created the effectuation tasks. 
- Acceptance criteria 1, 3, and 4 validated.
- Tasks from two separate business lines appeared on the same effectuation task page. The process should have created two separate tasks/ task pages, one for each business line.
- Saving fails with the attached error.
- The failed-to-save error reads `The dispositions for this task could not be saved` but should read `The effectuation confirmation(s) for this task could not be saved`

**Comment by steve-gov** [comment]
<img width="830" alt="screen shot 2019-01-28 at 11 59 07 am" src="https://user-images.githubusercontent.com/25468689/51863218-4fa42480-22f5-11e9-9762-457d32b10598.png">

![screencapture1](https://user-images.githubusercontent.com/25468689/51863222-52067e80-22f5-11e9-9304-180af5a4df12.gif)

**Comment by steve-gov** [comment]
Awesome! Validated!

![screencapture](https://user-images.githubusercontent.com/25468689/52018263-9e40f280-249e-11e9-9550-e57039525e98.gif)
