### ISSUE TITLE
Power of Attorney is populated wrong when the veterans does not have POA representation

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#83]
We saw this during usability tests where veterans without POA representation had a value populated in the Caseflow header and in the PDF generated. Fix this.

**Comment by alex** [comment]
@plusjeff do you have an example record I can look at to see what's up in the DB?

**Comment by plusjeff** [comment]
`2765733`

**Comment by alex** [comment]
What's a BFKEY for which env?

On Thu, Oct 29, 2015 at 9:14 PM, Jeff Maher <notifications@github.com>
wrote:

> 2765733
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/83#issuecomment-152372911>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
