### ISSUE TITLE
Replace individual email address with an alias

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8316]
Currently we have a few places where we have a specific person's email address linked in the front-end. We would like to remove this (potentially by replacing with a generic email address such as intake-help@va.gov, or a form or something.

Followup on #7908

create an appropriate email alias in VA and replace the individual email address reference

**Comment by leikkisa** [comment]
Lisa says she can set up a listserv for us if we want! I sent an email to Ken, Lisa, and Jennifer (the person whose email we have) to start a conversation about moving forward on that.

**Comment by leikkisa** [comment]
We are using VACaseflowOps email for now, until we get a more permanent email.

**Comment by leikkisa** [comment]
Proposals are VACaseflowIntakeHelp or VACaseflowCorpDB (all current uses are to request an update to Corp DB). I asked Jennifer and she doesn't have any preferences or suggestions, and I don't think it matters a ton.

**Comment by leikkisa** [comment]
We're hoping for movement on this within 2 weeks, and it's gong to be VACaseflowIntake, CaseflowIntake@va.gov

**Comment by leikkisa** [comment]
This will be ready to update on Monday! Lisa, Shane, myself, Peter and Jennifer have been added to the list at the moment.

**Comment by Sjones352** [comment]
**Passes in UAT**
<img width="1123" alt="screen shot 2019-03-07 at 2 45 00 pm" src="https://user-images.githubusercontent.com/23080951/53985002-8f2a1180-40e8-11e9-94b3-ad6217161655.png">
