### ISSUE TITLE
Prevent the same legacy issue from being opted in twice

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#8317]
## Story
If a legacy issue is matched to a request issue during a decision review intake or during edit, grey it out so that it can't be connected to another request issue during the same intake.

A legacy issue can't be opted in (within the same intake) with connections to more than one request issue at a time.

## Notes
- If users tried this, we would throw an error asynchronously and this case would show in our stuck jobs queue
- Opting in closes the issue in VACOLS with a disposition of O
- Could look in the Legacy issue opt-in table to see if issues have been attempted to be opted in twice

**Comment by aroltsch** [comment]
> Could look in the Legacy issue opt-in table to see if issues have been attempted to be opted in twice

**Comment by leikkisa** [comment]
Agree, that comment doesn't quite make sense.  I think it makes sense for this ticket to focus on not selecting duplicates within one intake session, and using the data on the front end.

Preventing duplicates that are not from the same same intake session seems like a different enough issue and approach that it could be a different ticket.  I'm kind of curious to look at the data and see which situation is more prevalent.  This second situation shouldn't be too common, because once an opt-in is processed it isn't eligible to be opted-in anymore, and would get filtered out.
