### ISSUE TITLE
QR selection for AMA appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8320]
We no longer need to send all RAMP appeals to QR, and Josh decided he wants to keep the selection logic the same as legacy appeals.

## AC
- Change QR selection for AMA cases to be the `QUALITY_REVIEW_SELECTION_PROBABILITY` in `judge_case_review.rb`

**Comment by lowellrex** [comment]
Updating [`CaseReviewsController.create_quality_review_task`](https://github.com/department-of-veterans-affairs/caseflow/blob/33742a118979558e3131f2627488ec3840896fb4/app/controllers/case_reviews_controller.rb#L30) to something like the following (to mirror [what we do for legacy cases](https://github.com/department-of-veterans-affairs/caseflow/issues/6407#issuecomment-409271892)) should do the trick:

```ruby
def create_next_task(record)
  return if record.appeal.is_a?(LegacyAppeal) ||
            !record.is_a?(JudgeCaseReview) ||
            record.task.parent.is_a?(QualityReviewTask)

  root_task = record.task.root_task

  (rand(25) < 1) ? QualityReviewTask.create_from_root_task(root_task) : BvaDispatchTask.create_and_assign(root_task)
end```
