### ISSUE TITLE
Update modal copy for Special Issues not handled by AMR

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#833]
Update modal copy for Special Issues not handled by ARC.

When a user selects a Special Issue not currently supported by Caseflow Dispatch, (no matter the type of grant) verify that when they select the 'Create End Product' button, the following modal shows:

<img width="734" alt="screen shot 2017-02-06 at 4 40 28 pm" src="https://cloud.githubusercontent.com/assets/4975959/22668617/578804c6-ec8f-11e6-8431-7e8080934de0.png">

**Comment by lakohl** [comment]
@abbyraskin this modal would address Special Issues that we will cancel out of during the first month. Could you take a look at the copy?

**Comment by lakohl** [comment]
@abbyraskin assigning this to you to give another pair of eyes to copy.

**Comment by abbyraskin** [comment]
I'm struggling to think of a better word than "cancel" here...in our initial rounds of usability testing it was perceived as a bit loaded, particularly in the context of canceling a claim. 

I'm still a little concerned they won't actually realize what's going on here (i.e., they'll think they're canceling an EP, or not realize what it means to process a claim manually), but with most of these more minute details, we probably just need to get it out there and test it -- i'm fine with developing this as is for now...

**Comment by abbyraskin** [comment]
i'll try to keep my feedback less long-winded/roundabout next time :-)
