### ISSUE TITLE
Update layout for missing documents page

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#834]
As a user, when the appeal I am certifying is missing required documents, I want the information to be presented to me in a way that I can better understand what's going on and take the appropriate action.

## Acceptance Criteria
- Verify that the title of the page is "Check Documents" instead of "Find Missing Documents"
- Verify that the error alert is moved inside of the white content panel, and continues to match the USWDS alert (the mock doesn't match the style exactly)
- Verify that the table of missing documents is moved to just underneath the error alert.
- Verify that the column headings for the table are updated to "Found in VBMS?", "Document", "VACOLS date" and "VBMS date"
- Verify that for documents that are not found in VBMS, the "VBMS date" field reads "Not found" instead of "No matching document".
- Verify that there is a link "cancel this certification", that brings up the cancellation modal in accordance with the mock.

## Mock
<img width="437" alt="screen shot 2017-02-07 at 8 57 55 am" src="https://cloud.githubusercontent.com/assets/1596259/22704921/7671932c-ed37-11e6-97f5-ba10488daa8c.png">

## Notes
- @shellicious can verify any design issues or questions

**Comment by nemodjuric** [comment]
@shanear Just to confirm since it's omitted from the mock - we are keeping certification layout (Appeal type, File type and Representative)?
![caseflow certification 19](https://cloud.githubusercontent.com/assets/4960030/23073873/e02b5242-f504-11e6-886d-93728a7a7c27.png)

**Comment by nemodjuric** [comment]
![caseflow certification 20](https://cloud.githubusercontent.com/assets/4960030/23074200/1c4acb26-f506-11e6-8da2-f2e4a86bdd23.png)

**Comment by kierachell** [comment]
That face when implementation looks better than the mock 👍 
![screenshot_2017-02-25_22-34-44](https://cloud.githubusercontent.com/assets/18075411/23336866/a281a11a-fbaa-11e6-86f7-8aee5986e8a1.png)

Nitpick: _Cancel Certification_ link on bottom left should be _Cancel certification_ and **Refresh Page** should be *Refresh page**
as per:
![lara_decree](https://cloud.githubusercontent.com/assets/18075411/23336880/04442ff8-fbab-11e6-917d-f3654cf8144b.png)


@shanear and @shellicious 
Current header shows "Mismatched Documents" - should that be changed?
I see the button **Continue** in the mocks but not in AC or implementation (it has **Refresh page**).

![screenshot_2017-02-25_22-40-00](https://cloud.githubusercontent.com/assets/18075411/23336898/75ad17b8-fbab-11e6-8d8a-ea6cd3784970.png)

**Comment by shellicious** [comment]
@kierachell:

- the header should be "Check Documents", not the current "Mismatched Documents"
- the button should say "Refresh page". The "Continue" button is from wireframes of a future version of Caseflow Certification, and it doesn't yet make sense from a UX perspective to change it to "Continue" without implementing other features.

**Comment by shellicious** [comment]
and yes -- keep the Appeal type, file type, and representative in this current implementation. They will go away in a future iteration of Caseflow, but will stay today. cc @kierachell @nemodjuric

**Comment by kierachell** [comment]
**PASSED**
new issue will be created for buttons
