### ISSUE TITLE
App Canvas | Header | Add Progress Indicator

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#835]
As an RO Caseworker, I want to be able to see where I am in the process of certifying an appeal via a progress bar that shows the major steps (1. Check Documents, 2. Confirm Claim Details, 3. Sign & Certify) so that I know where I am at all times and understand how much more work I still need to do.

# Acceptance Criteria
1. Verify that the Progress Indicator has the following 3 steps (refer to ):

     > 1. Check Documents
     > 1. Confirm Claim Details
     > 1. Sign & Certify

1. Verify that the Progress Indicator is at the current step in the certification process indicated with dark grey color bar and bold type. (Refer to style guide)
1. Verify that past steps are indicated on the Progress Indicator with dark grey color and bold type. (Refer to style guide)
1. Verify that future steps are indicated on the Progress Indicator in light grey color and regular type. (Refer to style guide)
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Check Documents` page (Success and Missing).
1. Verify that when on the `Check Documents` page (Success and Missing), the Progress Indicator is set to "Check Documents" as the current step.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Claim Details` page.
1. Verify that when on the `Claim Details` page, the Progress Indicator is set to "Confirm Claim Details" as the current step.
1. Verify that there is Progress Indicator in the Header of the App Canvas on the `Sign & Certify` page.
1. Verify that when on the `Sign & Certify` page, the Progress Indicator is set to "Sign & Certify" as the current step.

## Mock(s)
![image](https://cloud.githubusercontent.com/assets/3781835/24267639/58193f70-0fe1-11e7-925e-b50f84d35fa5.png)

### Notes
Navigating back to different parts of the process using the progress bar will be implemented in another story.

# Related Stories
**_Predecessor(s)_**
New page - Sign & Certify
New page - Claim Details
Updated - Check Documents

**Comment by kierachell** [comment]
**PASSED**
looking spiffy in `uat`!
<img width="1053" alt="screen shot 2017-04-04 at 7 57 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/24684025/18276722-1971-11e7-9b49-5f1fbec57fb5.png">
<img width="1012" alt="screen shot 2017-04-04 at 7 58 00 pm" src="https://cloud.githubusercontent.com/assets/18075411/24684024/1826f882-1971-11e7-96af-4c5c68506f7c.png">
<img width="1039" alt="screen shot 2017-04-04 at 7 58 09 pm" src="https://cloud.githubusercontent.com/assets/18075411/24684026/182a11f2-1971-11e7-90d9-32045142d09a.png">
