### ISSUE TITLE
User Testing Add/Edit/Remove/Lock Hearing Day

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8359]
## Add Hearing Day 
- [x] Verify he can add a video hearing day after 4/1 -- 
- [x] Verify he can add a CO hearing after 1/1 -- 
- [x] Verify that there can select date for new hearing day  
- [x] Verify that the user can select hearing type (Video or Central) 
- [x] Verify that the user can select RO from a list of ROs that hold hearings 
- [x] Verify that an VLJ can be added from of all VLJs 
- [x] Verify that a hearing day can be created without selecting a VLJ
- [x] Verify that a room number is automatically assigned based on available room numbers 
- [x] Verify that a coordinator can select if they do not want a Board hearing room assigned 
- [x] Verify that an error is shown if there are no hearing rooms available (and no hearing room hasn't been selected) 
- [x] Verify that a coordinator can be added (free text)
- [x] Verify that the hearing day can be created without selecting a coordinator 
- [x] Verify that User can save text in the hearing day's notes field. 
- [x] Verify that there is a confirmation when the hearing day is added 
- [x] Verify that errors are shown when user does not select a required fields (date, type, RO if type is video). 
- [x] Verify that error is shown when hearing day cannot be saved  
- [ ] Verify that only hearing admin can add hearing day to schedule (not hearing coordinators). Meredith Emailed Sal 1-21-19 to confirm. 

## Edit Hearing Day 
- [x] Verify that there is a way for the user to change a VLJ for a hearing day 
- [x] Verify that there is a way for the user to leave the VLJ unassigned for a hearing day 
- [x] Verify that there is a way for the user to select the VLJ from list of VLJs to schedule 
- [x] Verify that the user can edit the room number where the hearing is held from all available rooms 
- [x] Verify that the user can leave the room number unassigned for a hearing day 
- [x] Verify that the user can double book hearing rooms 
- [x] Verify that a coordinator can be added
- [x] Verify that a coordinator doesn't have to be selected
- [x] Verify that the user can edit the notes field for that hearing day
- [x] Verify that each data element has "(Optional)" 
- [x] Verify that there is a confirmation when the action is completed
- [x] Verify that there is an error message when the action cannot be completed 
- [ ] Verify that all Hearings Management Branch users can edit these attributes of the hearing day

## Remove Hearing Day 
- [ ] Try to remove a VACOLS hearing day and see if error occurs -- although there might not be an example to test this. Ok not to test this.  ~ Meredith 
- [x] Verify that there is a warning that pops up that warns the user of the following:
Once they remove it will delete the record (copy TBD)
- [x] Verify that if there is a veteran scheduled for that day there is a validation error (copy TBD)
- [x] Verify that there is confirmation when the day is removed
- [x] Verify that only hearing admin can add hearing day to schedule (not hearing coordinators)

## Lock Hearing Day 
- [x] Verify that the user has the ability to lock the day to prevent additional Veterans from being scheduled for that day. Copy, "Lock scheduling Veterans for this day." 
- [x] Verify that the user has the ability to unlock the day to prevent additional Veterans from being scheduled for that day. Copy, "Unlock scheduling Veterans for this day." 
- [x] Verify that the hearing day locked no longer appears in the Schedule Veterans view. 
- [x] Verify that the hearing day unlocked appears in the Schedule Veterans view, if there are available slots. 

## Other 
 - [x] Test to make sure stale tasks are removed from users Individual Queues

**Comment by MeredithStewart** [comment]
Testing with Justin Madigan 
* New video hearing day appeared for 4/1/19 - for Baltimore 
* We need to show room Number # -- On daily docket -- We need to add this. -- So that it the "select room" is 
* Language on that -- "Board Hearing Room not required." -- 
* "Assign Board Hearing Room" -- have it always checked, you need to check it if you don't want a board hearing room assigned. 
* When the "edit hearing day" is selected, it should show the room number. 
* It did save 
* Central Office is always in ROOM 2 -- Needs to be assigned to ROOM two for Create Hearing Day 
* BUG: For Central Office hearing -- showed associated with the Baltimore RO, and Shows it in the Baltimore Schedule Veterans. CO shouldn't appear there. 
* Locked hearing day -- 4/1 - removed for Schedule Veterans. Unlocked the hearing day - then refreshed - and it showed up. Worked for both CO and Video. 
* Add text to indicate that it's "None" for null states in selector. 
* Removed hearing day worked -- for both CO and Video. 
* Edit hearing day - Hearing coordinator already selected is now showing up on the Edit hearing day pre-populated. 
* Wants an error for a Saturday/Sunday is selected -- but you can selected 
* TO DO: Need day of the week added to "View Hearing Schedule" in front of Date -- so that the user has a place-making to know where they are. And don't acccidently schedule the wrong day of th eweek. 
* TO DO: Show in confirmation banner shows in a Saturday/Sunday in a different color -- so that they can edit the hearing day. 
*

**Comment by MeredithStewart** [comment]
Once tickets have been completed from up above, re-test with Justin Madigan.

**Comment by MeredithStewart** [comment]
Reviewed tickets above and found two that have been completed have issues that need to be fixed. Two issues still open, couldn't test.

**Comment by sharonwarner** [comment]
Saturday/Sunday warning message was merged today. Fix for the CO hearings being assigned an RO will be merged later today.

**Comment by MeredithStewart** [comment]
Checked above fixes -- only open #8845 (error copy update) and #8368 (Null state selector).
