### ISSUE TITLE
Feature flag system for specific Regional Offices

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#836]
As a developer, I want to be able to turn on features only for users of specific ROs.

This feature is open ended and the mechanism with which we turn on and off RO's access to features can be discussed by the engineers as part of this issue.

## Notes
- This will be an internal feature and unable to be verified until we utilize it.
- Tech Talk:  @kierachell
The basis for this is what's called "A/B Testing" or "staged rollout" I remember a more-general talk about the concept, but there's also a Rails-related talk with more implementation details:
For Rails specifics - https://www.youtube.com/watch?v=5hgNaSVDkEs

**Comment by aroltsch** [comment]
Usage Examples are in README.

**Comment by kierachell** [comment]
Waiting for https://github.com/department-of-veterans-affairs/caseflow/pull/1020 to merge to validate this properly.

**Comment by kierachell** [comment]
**PASSED**
Validated on `uat`
```
irb(main):012:0> FeatureToggle.enable!(feature: :dispatch_full_grants, regional_offices: ["RO97"])
=> true
irb(main):013:0> FeatureToggle.enabled?(:dispatch_full_grants)
=> false
```
