### ISSUE TITLE
[spec] TimedTasks

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#8361]
### Goal 
Create a simple and reusable way to implement appeals processes that require periods of time to be tracked, and for appeals to be moved to the next step/have some action happen after a certain amount of time. (For example, [evidence submission windows](https://github.com/department-of-veterans-affairs/caseflow/issues/7916) and IHP periods)

We could easily make this extensible to handle all classes, but for now, let's make it usable specifically and only for Tasks,
since we want to encourage the use and evolution of the Tasks table and its subclasses.

### Implementation
 Create a TaskTimers DB table that has 
- a pointer to a task
- an expiration date
- a completed_at flag set to default nil

Create a Timer module (similar to RoundRobinAssigner) that
- Validates that the class importing the module has a "when_expired" instance method defined
- Validates that the class importing the module has a "expires_in_days" value instance method defined
- When a new instance of that class is saved to the DB, also create a new Timer instance that captures 
    - a pointer to the task
    - the expiration time

Create a HandleTimedTasks job that runs every night(?) that:
- Queries for Timers that have no date for completed at and for which the expiration date has passed
- Joins to the Tasks table
- Calls the 'when_expired' method on the task

The EvidenceSubmissionTask and the InformalHearingPresentationTask will then import the Timer module, similar to RoundRobinAssigner. They'll define their own "when_expired" and "expires_in_days" values.

**Comment by pkarman** [comment]
This sounds similar to [Asyncable](docs/asyncable-models.md). Could we maybe adapt it?

**Comment by amprokop** [comment]
Thanks for bringing this up, @pkarman!

Would love to explore that idea... a few initial thoughts.

The crucial piece we'd have to add to Asyncable is the ability to wait until X time before beginning to take action on a task.

The next piece would be, where do the fields required by Asyncable go? 🤔on a TaskTimer class? I'm a little bit hesitant to muddy the Task model as most Tasks will not require this kind of action.

Retries here are a bit less of a need, as the logic I describe here wouldn't rely on external dependencies, it's all Caseflow-internal.

On the other hand, looking into the future, I can surmise that potentially making async actions/retries tightly tied into Tasks could have great value/help to us. For example, we're trying to deal with a simultaneous issue here — we need to check if POA has changed on an appeal as some yet-to-be-determined interval, and possibly reshuffle/create new tasks if a change has been made. Without diving too much into that complex world, maybe there could be some value in easily being able to do something like — when creating a task for an appeal, set a timer to check the POA to see if it's changed every, say, 15 days. If the POA does change, make some modifications to the tasks and other models.

Looping in @lowellrex @mdbenjam here as I'm opening another can of worms with this comment.

**Comment by amprokop** [comment]
If it's easier to have this discussion with some code, I started a PR here https://github.com/department-of-veterans-affairs/caseflow/pull/8373. @pkarman feel free to comment or even push to that branch if it's easier to just make it work than to explain!

**Comment by pkarman** [comment]
I do find code easier to flesh out ideas. Take a look at #8374

**Comment by mdbenjam** [comment]
I think using Asyncable makes sense. Peter's PR is pretty great.
