### ISSUE TITLE
Add Hearing Day | Room assignment logic

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8366]
Update logic to reflect updated hearing room logic - Rooms 2 = CO hearing room, Rooms 1, 3 - 13 for Video.

**Comment by MeredithStewart** [comment]
@sharonwarner -- When a user adds a CO hearing day on a day that there is already a CO hearing room, it doesn't actually add the new hearing day to the schedule in Demo. There is also no error message telling the user that it won't be added. 

What we're looking for: If a user tries to add a CO hearing day on a day there is already one scheduled (thereby taking up room 2), the user should get an error warning and will need to unselect, "Assign Board Hearing Room." Then they would need to manually switch the room afterwards.
