### ISSUE TITLE
Add Hearing Day | CO hearings can't be assigned an RO

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8367]
For CO hearings, make sure that RO isn't associated with the hearing. In testing, a CO hearing carried the RO for the previous Video hearing day added (Baltimore). Newly created hearing day showed up in both the CO Schedule Veterans view and the Baltimore Schedule Veterans view.

**Comment by MeredithStewart** [comment]
@sharonwarner -- In testing this one in Demo, this is still not functioning as intended. Scheduling a video hearing is not showing as video - still showing as CO hearing day, but associated with an RO.

**Comment by MeredithStewart** [comment]
When we refresh the page, it changes from Central to Video.

**Comment by MeredithStewart** [comment]
tested and found this working as expected.
