### ISSUE TITLE
Edit Hearing Day | Null state

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8368]
Add text to the null state for selectors, "Please Select..."

**Comment by laurenrussell** [comment]
<img width="1062" alt="dropdown-selector" src="https://user-images.githubusercontent.com/44249412/50237834-d88d7f00-038b-11e9-9d7e-b1e2e2e943d1.png">

**Comment by Sjones352** [comment]
Ticket has already been done.

**Comment by MeredithStewart** [comment]
@Sjones352 -- I don't see this in demo or in production working. I don't see the "please select."

**Comment by Sjones352** [comment]
Interesting. Thought @oscarAtNava had already done. Re-opening it

**Comment by ferristseng** [comment]
@lomaxap this should be null room right?

**Comment by ferristseng** [comment]
We have a null constraint on the room column. Would we need to remove that constraint for this?

**Comment by lomaxap** [comment]
Ah, ok. Then yes. We should remove the constraint for this.
