### ISSUE TITLE
Add Hearing Day | Saturday & Sunday

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8369]
If a Saturday or Sunday date has been selected, we will implement a new confirmation banner to indicate this and that they may want to delete the hearing day if this was done in error.

**Comment by laurenrussell** [comment]
<img width="1440" alt="hearing-date-warning" src="https://user-images.githubusercontent.com/44249412/50237862-ed6a1280-038b-11e9-97cc-d1ee9647978f.png">
