### ISSUE TITLE
Edit Hearing Day | Initial state

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8370]
We need to show the room number, vlj, and hearing coordinator what was selected in "Add Hearing day" to show when you first get into "Edit hearing day." They all showed as not selected - even though data had already been assigned through the Add Hearing day function.

**Comment by laurenrussell** [comment]
<img width="1367" alt="vlj-daily docket" src="https://user-images.githubusercontent.com/44249412/50237901-0d013b00-038c-11e9-92d8-3cac4e934265.png">
