### ISSUE TITLE
Remove header on evaluation page in judge checkout flow

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8382]
This ticket is an offshoot of conversations happening in https://github.com/department-of-veterans-affairs/caseflow/pull/8281. 

Currently, we display our latest iteration of "Task Snapshot" at the top of the Evaluation page in the judge checkout flow. We also display the Task Snapshot on the Case Details page before the judge checks the case out to BVA Dispatch. 

We can probably pare Task Snapshot down a bit and just display the attorney's name (or, the person who the judge is evaluating) and any notes the attorney wants to share with the judge. 

Open questions: 
- Is there any other information that would be helpful for the judge to see at this point? There is some context around original Evaluation page decisions in this ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/5151#issuecomment-395145113. 

## AC
- [ ] Remove the header on evaluation page of the judge checkout flow "Currently Active tasks"
- [ ] Adjust hex color on div lines to #d6d7d9

**Comment by hschallhorn** [comment]
@carodew Digging through some old tickets. Is this still something we want to implement?

**Comment by geronimoramos** [comment]
![New.png](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/2ce3e7ab-b0cd-4dbb-9e32-a078ebaa6d45)

Do we want to remove the table and extract the bare information displayed here? Or just remove details from the table?

**Comment by hschallhorn** [comment]
![Screen Shot 2020-04-07 at 12 53 04 PM](https://user-images.githubusercontent.com/45575454/78697433-ca3fdb00-78ce-11ea-9b02-0d3e08de21df.png)
I believe this refers to the "currently active tasks" header

**Comment by geronimoramos** [comment]
Yes to removing the "Currently active tasks" header! It unnecessarily adds clutter.

Also if we could adjust the divider line colors to be consistent across the product, that would be helpful!
#d6d7d9
Gray-lighter
$color-gray-lighter

**Comment by hschallhorn** [comment]
Ensure grey divider before case timeliness is also removed

_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||||||||
2 | |
3 | 
5 | 
8 | 
```

#### Why 1?
- Delete code!!!

#### Why 2?
- Additional AC of consistent divider styling!
