### ISSUE TITLE
Stop changing JudgeTask type

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8408]
When a judge at the Board receives an appeal to make a decision on, they take a sequence of steps in order to hand the appeal off to the next person in the lifetime of an appeal. The judge is required to sign a decision on the appeal and in order to do so they always assign the appeal to an attorney on their team to draft the decision, and then sign that decision once the attorney has finished drafting it. Judges also occasionally return decisions back to the attorney that drafted it.

We currently represent this in the task model as a task that is created with the type `JudgeAssignTask` and that type [changes to `JudgeReviewTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/ffedf94503aaf3a0ee3e6fa8deda2886b392727a/app/models/tasks/judge_task.rb#L49) once the attorney has finished drafting their decision (in the language of the application, once the child `AttorneyTask` is completed).

### Currently:
```
                                   |
-------------------------------    |    -------------------------------
                                   |
       Root task                   |           Root task
                                   |
-------------------------------    |    -------------------------------
         |                         |             |
         |                         |             |
         v                         |             v
     +-------------------+         |         +-------------------+
     |                   |         |         |                   |  # Task changes type
     |  JudgeAssignTask  |         |         |  JudgeReviewTask  |  # when child attorney
     |                   |         |         |                   |  # task is completed.
     +--------+----------+         |         +--------+----------+
              |                    |                  |    ^
              |                    |                  |    |
              v                    |                  v    |
         +--------------+          |             +--------------+
         |              |          |             |              |
         | AttorneyTask |          |             | AttorneyTask |
         |              |          |             |              |
         +--------------+          |             +--------------+
                                   |
```

We change the type of the judge task so that we can display a different set of available actions to the judge in the available actions dropdown menu. This is a little artificial because the task the judge has to complete has not actually changed even though the type has (the judge still has to deliver a signed decision). I think we should change the way the application represents the different steps in the process of a judge delivering a signed decision to better match the process.

## Option 1: Use child AttorneyTask presence to determine actions

Currently we use the task type alone to determine which actions are available to the judge for a given appeal:

`JudgeAssignTask`
* Assign to attorney

`JudgeReviewTask`
* Ready for Dispatch
* (soon!) Return to attorney for corrections (or something similar)

Instead we could use the presence of a completed child attorney task to make that same determination:

No child `AttorneyTask`
* Assign to attorney

Completed child `AttorneyTask`
* Ready for Dispatch
* (soon!) Return to attorney for corrections (or something similar)

The task tree would look like the following in this case:

```
                                   |
-------------------------------    |    -------------------------------
                                   |
       Root task                   |           Root task
                                   |
-------------------------------    |    -------------------------------
         |                         |             |
         |                         |             |
         v                         |             v
     +-------------------+         |         +-------------------+
     |                   |         |         |                   |
     |     JudgeTask     |         |         |     JudgeTask     |
     |                   |         |         |                   |
     +--------+----------+         |         +--------+----------+
              |                    |                  |    ^
              |                    |                  |    |
              v                    |                  v    |
         +--------------+          |             +--------------+
         |              |          |             |              |
         | AttorneyTask |          |             | AttorneyTask |
         |              |          |             |              |
         +--------------+          |             +--------------+
                                   |
```

## Option 2: Create separate assign and review tasks

If we want to retain the distinct `JudgeAssignTask` and `JudgeReviewTask`s we could create the latter when a judge tags an attorney to draft an appeal. The available actions would remain the same as they are now (determined by the task type), but the task tree would change to look like the following:

```
------------------------------------------------------------

     Root task

------------------------------------------------------------
          |      ^             |
          |      |             |
          v      |             v
   +-------------------+   +-------------------+
   |                   |   |                   |
   |  JudgeAssignTask  |   |  JudgeReviewTask  |
   |                   |   |                   |
   +-------------------+   +-------------------+
                                  |
    # JudgeAssignTask             |
    # marked as complete          v
    # when appeal assigned     +--------------+
    # to an attorney           |              |
                               | AttorneyTask |
                               |              |
                               +--------------+
```

Curious to hear thoughts on these approaches, whether you think this is actually a problem, or if there are alternative ways to address this concern.

**Comment by amprokop** [comment]
Agreed that the inconsistency is worth addressing.

Lean towards option 2 if these are the only options on offer, but I’m wondering if longer term we should consolidate and the JudgeAssignTask should just become an OrganizationTask, while JudgeReviewTask and AttorneyReviewTasks remain separate types.

That’s just a guess, and I know the LOE might be prohibitively high to tackle right now- but I’m curious if unification of Judge/Attorney tasks with other tasks is ultimately the path we want to go down.

**Comment by lowellrex** [comment]
> I’m wondering if longer term we should consolidate and the JudgeAssignTask should just become an OrganizationTask

@amprokop I'm not sure I fully understand. Are you suggesting that we use the task tree described by approach 2 and set the assignee for the `JudgeAssignTask` to be the judge's `JudgeTeam` organization?

**Comment by aroltsch** [comment]
Leaning towards option 2 because it would be easier to introduce new logic based on the judge task type.

**Comment by laurjpeterson** [comment]
@lowellrex - Since we now have JudgeDecisionReviewTask and JudgeAssignTask, is this still relevant?

**Comment by lowellrex** [comment]
> @lowellrex - Since we now have JudgeDecisionReviewTask and JudgeAssignTask, is this still relevant?

Yes this is still relevant even though we have subclasses, since we are still doing it here: https://github.com/department-of-veterans-affairs/caseflow/blob/8d8136392d00677740ace2ad509a995d687e45f9/app/models/tasks/judge_assign_task.rb#L7

**Comment by lowellrex** [comment]
LARGE. Be on the lookout for opportunities to break this up into smaller PRs as you get into working on it.

**Comment by laurjpeterson** [comment]
Moved to ready for dev pipeline because it's been estimated.
