### ISSUE TITLE
Create Transcription task

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8420]
After a hearing has the disposition of held, it must be transcribed. For the pre-MVP for AMA appeals, there will be a Transcription Task to track the highest level of transcription activities. This will especially help for AOD AMA hearings held prior to April 1, but is not enough functionality for the Transcription team to complete their tasks overall. 

## AC
- For only AMA hearing docket appeals that have hearing dispositions of `Held`, a `TranscriptionTask` is created and assigned to the Transcription team. 
- Cases with `TranscriptionTasks` show in the Transcription team queue. 

## Open questions
- ~@MeredithStewart @sharonwarner - Do you want these Transcribe hearing tasks to be created for all AMA appeals, not just AOD, because these tasks might still be relevant beyond the pre-MVP? Please feel free to update AC as you see fit.~

**Comment by MeredithStewart** [comment]
I'm thinking it would be for all AMA hearings.

**Comment by MeredithStewart** [comment]
Let's check in on the task model structure that Sharon and Alex were working on and make sure that this doesn't conflict. Perhaps it makes sense to have something pre-MVP, but we want to make sure we've got agreement on how we're developing the trees for the task model.

**Comment by laurjpeterson** [comment]
@sharonwarner adding caseflow-hearing-schedule label for your awareness.

**Comment by sharonwarner** [comment]
Thanks @laurjpeterson! Closing because we have a duplicate ticket.
