### ISSUE TITLE
Put task creation functions inside of a transaction block

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8437]
Currently, when we create a parent task successfully but fail to create a child task for whatever reason we raise an error but persist the parent task to the database. We should not create any tasks in that lineage if we fail to create a child task. [`ColocatedTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/6bea2aab4a10d6bf3de6b4b26ab1f229c9f5637a/app/models/tasks/colocated_task.rb#L16) already puts creation attempts inside a transaction block which avoids that problem for that particular task type. We should put creation attempts for all task types in transaction blocks to avoid this problem universally (perhaps [in `Task.create_many_from_params`](https://github.com/department-of-veterans-affairs/caseflow/blob/6bea2aab4a10d6bf3de6b4b26ab1f229c9f5637a/app/models/task.rb#L82)?).

## Acceptance criteria
* [ ] If we fail to create a child task we should not create the parent task

**Comment by hschallhorn** [comment]
```
1 | |||
2 | |||||
3 | ||||
5 | 
8 |
```

May be able to drop this in to just `Task.create_many_from_params`. Should be on the lookout for other tasks that create child tasks or tasks upon closure/creation. Testing could be a bear. If the ticket turns out to be a lift, break this ticket out into individual tickets for task types.
