### ISSUE TITLE
Hide most of the Form 8 on the `certifications/XXX/new` page

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#845]
First step towards removing the form 8.

### Mock ###
![image](https://cloud.githubusercontent.com/assets/3781835/22711258/7f41247e-ed4e-11e6-99d0-a6e342ca482f.png)
- Remove questions 1-14 from the `/new` route.
- Remove question #s from the remaining questions.
- Make other updates to match the mock.
-  @shellicious says she is not wedded to the "Title of certifying official" question (17B on existing Form8) being a dropdown instead of radio buttons. Let's keep them as radio buttons for now.
- Note that the button on the bottom right will now be called "Certify Appeal"

This should be developed behind a feature flag called something like `HIDE_FORM_8`. Caseflow Certification should continue to work the same way as before unless `HIDE_FORM_8` is true.

### Context ###
We're phasing out the Form 8 in Caseflow and potentially all of BVA. We'll want to conceal most of the Form 8 from the users, while keeping the backend process intact (i.e., we'll still fetch appeal data from VACOLS, write it to the form8s table, generate a PDF with it, and upload that PDF to VBMS, the user just won't just see it).

**Comment by nikitarockz** [comment]
Duplicate - #1115
