### ISSUE TITLE
Intake | Contested Claims | Add Alert Banner and Copy 

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8451]
### Background/Context
This issue stems from a conversation @marvokdolor-gov and I had with @shanear @steve-gov about how we'll handle contested claims for AMA appeals in the short term. cc: @carolaponce . Part of broader epic #8660

### Goals
- When the Intake team sees a case with a contested claim, they will funnel cases with contested claims to a legal detailee who will be working closely with the Intake team to handle these edge cases.
- The legal detailee will ensure that the case is processed correctly and notify all parties.

## Success Criteria
N/A

## Stakeholders
N/A

### Requirements/stories
- As an Intake user, I need to know if an AMA case involves contesting claimants so that I can send it to a legal detailee to handle
- As an Intake legal detailee, I need to know if an AMA case involves contesting claimants so that I can send a notification letter to all parties that acknowledges that their case is at the BVA.

### Proposed solution
- Flag issues that are either sometimes contested claims or always contested claims at Intake
- Display an alert to communicate to Intake admin staff that a claim is either contested or might be contested
- Intake verifies claimant info on form with Dependents tab in VBMS

## Open questions
N/A

## References/Resources
N/A

### Designs and workflows
Contested Claimants - Intake UI Modifications Github Ticket [9711](https://github.com/department-of-veterans-affairs/caseflow/issues/9711)
https://app.mural.co/t/workqueue2001/m/workqueue2001/1542655242638/5629820b4b2c34a158c9dd7abb78137d0f9b8b74

**Comment by carolaponce** [comment]
@carolaponce

**Comment by carolaponce** [comment]
@carolaponce

**Comment by carolaponce** [comment]
Per our meeting - we are not making modifications to the UI at this time.  We'll wait for feedback from the attorney working with intake and gather feedback fro UI updates.

**Comment by allyceh** [comment]
This ticket is related to #8660

**Comment by laurjpeterson** [comment]
Closing in favor of #8660

**Comment by leikkisa** [comment]
@msj0nes I haven't done any work on contested claims, but as far as I know, this ticket is still relevant.

**Comment by msj0nes** [comment]
Closed. This will be addressed in new research for contest claims work.
