### ISSUE TITLE
Hearing Prep Hearing Worksheet Updates

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8475]
## User Stories 
* As a VLJ, I need to be able to determine when an appeal is an AMA appeal. 
* As a VLJ, I need to be able to take notes on AMA issues and have options only available for AMA appeals. 
* As a VLJ, I need to be able to correct issues through Intake if I find an administrative error was made. 
* As a VLJ, I need to be able to see the Case Details for each Veteran. 

## Mocks 
* For mocks see (page 3): https://va-gov.invisionapp.com/share/JMPS9DG29DA#/338987658_Worksheet_Current_Issues-Issues

## Acceptance Criteria 
- [x] Verify user has a link to the "View Case Details" for that Veteran. Verify that the button/link opens a new tab in the browser. Note: This is the same behavior as the "Review Claims Folder" button.  Verify that "View Case Details" button is implemented for both AMA and Legacy appeals. 
- [x] Verify user can see the docket number and docket type, reflecting H for AMA appeals and L for Legacy appeals. 
- [x] Verify that Procedural History is removed for AMA appeals. Note: Legacy appeals continue to have Procedural History section. 
- [x] Verify for AMA appeals, the new Issues section of the Hearings Worksheet is formatted similar to the Case Details Issues section. 
- [ ] Verify for AMA appeals, the user can select, "Correct Issues," which brings the user to a modal within Intake that allows the VLJ to correct administrative errors.  Note: URL is the same one that will be implemented on Case Details. This treatment will be a secondary button.
- [ ] Verify that after VLJ closes the "Correct Issues" modal, that the user is brought back to the Hearing Prep Hearing Worksheet. Note: While in Modal, the background will appear as if they are in Intake. 
- [x] Verify that the user can edit in-line for each AMA issue the, "Hearing Worksheet Notes," and Preliminary impressions. 
- [x] Verify that for issues on AMA appeals the user does not have the OMO option, ability to remove the issue (trash can), or the ability to add a new issue. Note: These options are retained for legacy appeals. 
- [x] Verify that for AMA appeals, the limitation does not exist of having to pull issues 30 days prior to the hearing like it does for Legacy appeals. Note: Because AMA doesn't have the same editing issues functionality, the issues section for AMA should dynamically update as changes are made to issues through Intake. It needs to function this way. We assume the 30 days in advance pulling in issues does not appeal to AMA hearing worksheets.
- [x] Verify the title is re-worded to say "Veteran/Appellant Information" above the information in both Legacy and AMA Hearing Prep views.
- [x] Verify all headings are h4 tags above the case, vet, VLJ, etc. info on both Legacy and AMA Hearing Prep views.
- [x] Verify the "Representative Org." title is changed to "Power of Attorney" in both Legacy and AMA Hearing Prep views. 
- [x] Verify the "Docket Number" title is changed to "Docket" in both Legacy and AMA Hearing Prep views. 

## Epic 
* Part of Epic #8473

**Comment by MeredithStewart** [comment]
@MeredithStewart and @ShellySmithDSVA -- Verify changes with Allyce, Lauren, Nicholas, and Chris Given on Wednesday.

**Comment by sneha-pai** [comment]
adding Mark and myself for component-building consultation: @mdbenjam @sneha-pai

**Comment by laurjpeterson** [comment]
Looks great! I agree with the user stories here.

One potential design tweak - you could change "Docket Number" to just "Docket". Queue has changed this in the queue table, because that column contains docket type + docket number. 

Also, this could be an opportunity to introduce some more contrast into the design, by bolding data titles like "Veteran name", "Veteran ID", so the worksheet is easier to read.

**Comment by MeredithStewart** [comment]
@sharonwarner -- This ticket is ready for dev. Mocks have been updated. Refer to @MeredithStewart and @ShellySmithDSVA for questions.

**Comment by sharonwarner** [comment]
Created a new issue for the 'Correct Issues' link. https://github.com/department-of-veterans-affairs/caseflow/issues/8870
