### ISSUE TITLE
Remove the PDF preview page if ENV["HIDE_FORM_8"] is true

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#848]
We're going to want to remove the following page entirely if `ENV["HIDE_FORM_8"]` is true:
![image](https://cloud.githubusercontent.com/assets/3781835/22710702/62b29628-ed4c-11e6-804c-424e14a80f8e.png)

- The user should go straight from the first form (the one that ends with "Name of Certifying Official", "Title of Certifying Official", "Date" to the "Congratulations! Your case has been certified" page.
- All of the same backend actions should still take place. Ensure that the PDF is still generated and uploaded to VBMS with all of the Form 8 info.

### Context: ###
We're deprecating the Form 8, so users won't need to see the PDF preview anymore.

**Comment by shanear** [comment]
Can I close this issue? seems not relevant

**Comment by amprokop** [comment]
yep
