### ISSUE TITLE
AMA Veterans need to be associated with an RO

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8484]
## User Stories: 

* A Hearing coordinator needs to schedule AMA Veterans for Board hearings by Regional Office and alternate locations associated with that RO. 

## Notes: 
*  VBA and the Board currently use this tool that matches a Veteran by their home address zip code to the VBA RO facility. Note that a Veteran isn't matched to an RO facility across state lines. 
* We investigated using BGS data field -- but none seem to actually be tied to the Veterans updated address. Those that contain station of jurisdiction are manually updated and often don't reflect the RO closest to the Veterans address. 
* We could also use geomatching to associate a Veteran to an RO (within state), but that seems to be less specific than the VA tool of zip codes, where the VA has determined which zip codes are associated with which RO. 

## VBA Jurisdiction Look up tool: 
http://vbacoweb03.dva.va.gov/bl/21/SOJ/default.asp?

Open Questions 
* If the VBA Jurisdiction tool can only be used manually (no API or data source), then it seems like we need someone in the Intake process checking the Veteran's address against the tool.
* Can this be done at Intake? Can this be added as part of the mail process?

**Comment by mdbenjam** [comment]
Are there any other factors that determine a user's RO? Does the RO they worked with for their initial claim matter at all?

**Comment by MeredithStewart** [comment]
@mdbenjam  -- It might matter, but in our investigation, it seemed like the RO wasn't updated automatically when a Veteran moved across the country.  

Because the ROs also change based on who is working on the processing, that is why the BGS fields aren't proving useful. When other ROs work the cases, it gets changed. We need a way to know which RO the Veteran would walk into -- and which they would be associated with for their hearing.

**Comment by MeredithStewart** [comment]
From the developer of the VBA Jurisdiction tool (Michael Van Gaalen): 

"As currently designed, the application and its database do not support an API, but that’s not to say one couldn’t be developed. Alternatively, the database tables themselves could be shared, although that could be messy and would also be snapshot in time. We don’t update the tables often, but updates do happen several times per year as new ZIP codes are assigned by USPS (happens relatively frequently) and/or as VA changes its jurisdictional boundaries (happens infrequently)."

**Comment by MeredithStewart** [comment]
@mdbenjam -- We could do geo-matching within state boundaries and we'd probably be accurate most of the time, but it wouldn't align with their zip code matching. The only thing that's the wrinkle is that a Veteran's representation/POA is likely colocated at their Regional Office. 

For alternate locations - we are clear that geomatching is the way to go - we're finding you the closest location, it's just that in today's hearing set up, ROs mean something - it's like the framework that then determines what alt hearing locations are available to you.

**Comment by MeredithStewart** [comment]
Based on conversation 1/2/18  -- We will geo-match Veterans to an RO and name that data element something like, "Hearing Regional Office."

**Comment by laurjpeterson** [comment]
Chiming in here - one of the reasons that queue could benefit from knowing the Veteran's RO under AMA is to automatically route tasks to Translation team (see: https://github.com/department-of-veterans-affairs/caseflow/issues/8226). This is primarily for appeals that originate from San Juan, Puerto Rico, and Manila, Philippines. I think we should aim for translation tasks to be completed as soon as possible, so we don't hold up attorneys when they are assigned cases to draft decisions.

The BVA intake team currently identifies cases needing translation for for legacy appeals manually during their Case Review process, which is essentially eliminated under AMA because NODs come straight to the Board and don't require activation + case review. 

I think we could use geo-matching for this as well, though we run the risk of over or under-selection. I am also open to alternative solutions for identifying cases with documents needing translation that don't rely on RO. We could brainstorm with Jennifer Jessup, Ivy Wilson, and the translation team to see if there's a way to do this without adding a manual step.

**Comment by mdbenjam** [comment]
Based on the Hearing Schedule conversation yesterday, it sounds like there isn't a great source to pull from within VA, so geo-matching feels like the right way to go for translation as well.

**Comment by mdbenjam** [comment]
Thinking more about this. @MeredithStewart, do we want to restrict the RO lookup to within the Veteran's state? I know this was mentioned originally, but I can't remember if that was in our final decision.

Are we still using the RO in VACOLS for legacy appeals? Or are we using geomatching for all appeals?

**Comment by mdbenjam** [comment]
In general I think geo matching for both legacy and AMA is good. It keep us consistent and allows us to work on a per-veteran level. I don't know what exactly the RO stored in VACOLS means. If a Veteran moves, if and when does that get updated? In terms of level of effort it's easy. If we're doing it for AMA, might as well do it for legacy.

**Comment by MeredithStewart** [comment]
Sounds good -- that's what I will pitch.  ROs are updated manually in VACOLS.

**Comment by MeredithStewart** [comment]
Update: Hearing Branch agreed that geo-matching Veterans to a Regional Office for both AMA and Legacy appeals. They also agreed that they need it to keep Veterans within State lines. They understood the limitations of geo-matching, but if a Veteran wanted to have a hearing at a different RO, they can always switch the Veteran. 

They were excited that this data point - Hearing RO - would actually improve the situation where appeals are coming in, but associated with an RO that doesn't hold Board hearings or is just associated with an RO that is working the case. Also pointed out was that this improves things for legacy paper cases coming from VHA, where it isn't associated with a VBA RO anyway.
