### ISSUE TITLE
Schedule Veterans | Veterans scheduled through VACOLS weren't showing up

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8490]
Meredith to confirm this issue.

**Comment by MeredithStewart** [comment]
I can confirm the issue for at least one Veteran. @sharonwarner -- you are correct, they are still showing up in the list of "Veterans to Schedule."

**Comment by MeredithStewart** [comment]
Last Veteran on daily docket for CO hearing on 1/23/19 shows up on docket, but is still on the list of Veterans to be scheduled.
