### ISSUE TITLE
Assign Hearings | Page load optimizations

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8498]
We need to optimize the backend calls on the assign hearings page. There are two calls, one to index_with_hearings in hearing_day_controller and the other to ready_for_hearing_schedule in appeal_controller.

We then need to determine how many veterans we could reasonably call in one page load so we can decide whether or not we need backend pagination.

**Comment by mdbenjam** [comment]
Looking in the logs

`index_with_hearings in hearing_day_controller` makes a ton of calls to the VACOLS::CaseHearing table.

`ready_for_hearing_schedule in appeal_controller` makes a ton of calls to VACOLS::CaseHearing, VACOLS::RemandReason, and VACOLS: CaseIssue.descriptions

**Comment by mdbenjam** [comment]
I think this is what made `ready_for_hearing_schedule` slow:

https://github.com/department-of-veterans-affairs/caseflow/pull/8353

**Comment by mdbenjam** [comment]
Reopening to tackle second slow endpoint. The `index_with_hearings` part.
