### ISSUE TITLE
Judges can send cases not assigned to them to BVA dispatch

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8499]
## Steps to reproduce locally
* Re-seed VACOLS and Caseflow databases
* Log in as `BVAAABSHIRE` (a judge with cases assigned to them)
* Visit a legacy appeal not assigned to the judge we are logged in as (`/queue/appeals/2096907`, for instance)
* Notice that we have the option to mark this case "Ready for Dispatch"

![image](https://user-images.githubusercontent.com/32683958/50619021-9fddc180-0ec4-11e9-9a55-26a2b42ea3c0.png)

Slack discussion where this issue was first raised: https://dsva.slack.com/archives/C54QCEHAL/p1546462248007400

**Comment by lowellrex** [comment]
Looks like a refactor we did last week (and will be pushed live in tomorrow's deploy) fixes this bug! Can be tested by running those steps to reproduce above then doing the following:
* Checking out master at the merge before this PR was committed (`git checkout d4fd3123521800a9f0203e00a622540866fc2a22`)
* Refreshing the page and observing that the actions dropdown (as well as the rest of the information about the task) still appears
* Checking out master when this PR was committed (`git checkout 0a019b10a33e06d6c8b0b3b5c0925a593bb4da2c`)
* Refreshing the page and observing that the "Currently active tasks" section is empty

![image](https://user-images.githubusercontent.com/32683958/50621301-02d65500-0ed3-11e9-8fdb-09a19b310b3d.png)

Going to leave this ticket open until we confirm that tomorrow's deploy fixes the bug.

**Comment by laurjpeterson** [comment]
@aroltsch - does this PR https://github.com/department-of-veterans-affairs/caseflow/pull/9141 fix t his ticket?

**Comment by aroltsch** [comment]
This is done.
