### ISSUE TITLE
View Hearing Schedule | Deletion/Addition success messages

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8505]
After deleting or adding a hearing day, the success messages never disappear. They should be unset on componentDidUpdate. We can copy the same logic from componentDidUpdate in hearingSchedule/containers/DailyDocketContainer.jsx.

**Comment by oscarAtNava** [comment]
@sharonwarner I cannot recreate this. The state is reset for the messages in componendDidMount since Dec 12th.
