### ISSUE TITLE
Non-Comp Intake | On confirmation page, remove copy references to EPs and contentions.

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#8511]
See https://github.com/department-of-veterans-affairs/caseflow/issues/7985

An EP is not established and a contention not created in the case of non-Compensation or non-Pension intakes. Remove references to establishing an EP or contention on the confirmation screen for noncomp intakes.

<img width="690" alt="screen shot 2019-01-03 at 3 43 31 pm" src="https://user-images.githubusercontent.com/25468689/50667745-a7a67000-0f6f-11e9-9e54-2f5ded9bc4a4.png">

**Comment by steve-gov** [comment]
@carolaponce pinging for any input you might have

**Comment by carolaponce** [comment]
The formatting looks off.  Specifically spacing and alignment.  Here's a reference for that page.  The modification we have done to this template is to have the message left aligned.
http://www.caseflowdemo.com/styleguide#messages

**Comment by kencheeto** [comment]
obsoleted by #7987
