### ISSUE TITLE
Add keyboard short-cut to add tags

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#8519]
https://github.com/department-of-veterans-affairs/appeals-support/issues/3783#event-2054949783

Users want to be able to add tags from the keyboard. I feel this is a reasonable ask and pretty simple to add.

Maybe:

alt+shift+m for medical
alt+shift+p for procedural
alt+shift+o for other

Also add these shortcuts to the list of shortcuts modal in Reader to make them more discoverable.

**Comment by sneha-pai** [comment]
I love this idea and am all for it. How may we help users understand and learn these shortcuts within the application? Do you think we could create a view of Reader keyboard shortcuts to toggle on and off as needed?

**Comment by mdbenjam** [comment]
We already have that! I'll add it to the ticket that we should add these to that list.
![screen shot 2019-01-04 at 12 59 05 pm](https://user-images.githubusercontent.com/3885236/50702983-99645c80-1020-11e9-842e-447be94eaa71.png)

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |||||
2 | |||||||
3 | 
5 | 
8 | 
```

Pressing shortcut again will toggle the tag.

#### Why 1?
- Straightforward change?
- Already have implemented keyboard shortcuts

#### Why 2?
- Unsure what requests we are currently making to edit tags. May not be as reusable as we hope (code probably hasn't been touched in 2 years)
- Never been in Reader

**Comment by Jeremy1026** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/2308626/113866543-73880e00-977b-11eb-88df-6ed9f2f82008.png">
