### ISSUE TITLE
Upgrade webpack-dev-server to mitigate vulnerability

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8531]
Github [automatically alerted us to a vulnerability](https://github.com/department-of-veterans-affairs/caseflow/network/alert/client/package.json/webpack-dev-server/open) in `webpack-dev-server` three days ago. Since this is only a dependency in our development environments it is not essential that we resolve it immediately. And since we are currently running version `^2.4.2` (and the mitigation suggested is to upgrade to `>=3.1.11`) the upgrade will include a full version release that may include breaking changes so it is probably worth making a branch with these changes that several people can test before we make the changes to master.

While doing this work investigate the feasibility of [upgrading to webpack 4](https://github.com/department-of-veterans-affairs/caseflow/issues/8253) because there are compilation benefits of doing so.

## Acceptance criteria
* [ ] There are not known vulnerabilities in the version of `webpack-dev-server` we are running.

**Comment by lowellrex** [comment]
Also see #8253

**Comment by jcq** [comment]
Closing in favor of #12704, which will include this dependency bump
