### ISSUE TITLE
Ensure team administrator Corey Benjamin is not assigned cases

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8583]
Related to #7973: Corey Benjamin (bvacbenjamin) is Deputy Chief for the VLJ Support Branch. Therefore, just like Rolandus Branch, he should be a part of these teams (e.g. VLJ Support Staff) but not be assigned cases. 
This pattern will repeat for other teams that have round-robin task assignment.

## Acceptance Criteria
- Corey Benjamin is part of the VLJ Support Staff team but cannot be assigned cases.

**Comment by lowellrex** [comment]
Added to the VLJ support staff as an admin so he won't get assigned tasks. There is a ticket to make it so existing admins can make other folks admins (#7974) that we should probably prioritize next sprint.
