### ISSUE TITLE
Manager Dashboard | Set number of Caseworkers for today

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#859]
As a Dispatch Manager, I want to be able to set the number of caseworkers available for work today, so that I can create a quota for each caseworker based on that number.

# Acceptance Criteria
1. Verify that under the Header, there is a new section with the following label (refer to mockup):

    >Enter the number of people working today
1. Verify that in this new section, there is a new field ([TotalCaseworkersToday]) with the label _"Number of people"_ (refer to mockup).  
1. Verify that in this new section, there is a new button:  **_Update_**
1. Verify that after clicking the **_Update_** button, the total # of caseworkers is updated to the new value.
1. Verify that the last value for _"Number of people"_ is always displayed.

# Mockups
**_View - Manager Dashboard page - new section_**
![image](https://cloud.githubusercontent.com/assets/23063044/22981559/b4792eee-f36a-11e6-8352-7f107f7bf64e.png)

# Related Stories
Manager Dashboard | Update copy of page header and subtext #869
Manager Dashboard | Current | Change table information and section header to "Work Assignments" #867
Manager Dashboard | Hide "Work History" section #860
Caseworker Dashboard | Show claims established in terms of today's quota #868
EP Confirmation | Show claims established in terms of today's quota #924

**Comment by nikitarockz** [comment]
Original
As a manager, I want to be able to set the number of case workers present at work today, so that I can create a quota for each caseworker based on that number.

# Acceptance Criteria
1. Verify that I can set the number of case workers working today by inputting a the number in the box and clicking the Update button.
- Verify that I can see the # of case workers I've set in the box
- Verify that I can update the # of case workers working today.


Mock:
<img width="590" alt="screen shot 2017-02-12 at 7 41 59 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867733/66d4b12e-f15b-11e6-848e-0b6915112d9e.png">

**Comment by lakohl** [comment]
@sharonwarner I discussed updating the styling of this section with Nikita this afternoon and hadn't realized you'd picked it up. (I"m sorry this keeps happening to you.) Let us know where you are at with it. If you have already built for the AC above we'll make a new ticket for these changes. If not let's use the mock/AC below.

@nikitarockz pls sign off on the new AC below. thanks.

# Acceptance Criteria
1. Verify that under the Header, there is a new section with the following label (refer to mockup):

    >Number of people working today
1. Verify that in this new section, there is a new field ([TotalCaseworkersToday]) 
1. Verify that in this new section, there is are up/down arrows to increase or decerase the number of workers 
1. Verify that after clicking the **_Update_** button, the total # of caseworkers is updated to the new value.
1. Verify that the last value for _"Number of people"_ is always displayed.
<img width="819" alt="screen shot 2017-02-16 at 8 43 50 pm" src="https://cloud.githubusercontent.com/assets/4975959/23049223/a8f0d27e-f488-11e6-8e5e-a5ce7217dddf.png">

**Comment by astewarttistatech** [comment]
Currently with the manager view toggled "enabled" when the https://certification.cf.uat.ds.va.gov/dispatch/establish-claim/ is accessed the page displayed is the "Drat!"/unauthorized page. 

Screenshot:
<img width="1348" alt="screen shot 2017-02-21 at 1 27 33 pm" src="https://cloud.githubusercontent.com/assets/23038505/23178826/d4a3f626-f839-11e6-8f7d-ddaa0bd1b75c.png">

Moving back to in progress.

**Comment by astewarttistatech** [comment]
Failed. Text field too wide. See screenshots @sharonwarner 

Environment Validated in: UAT

Steps to Recreate: 
1. Go to Dispatch and set the user as being a caseworker and a manager
2. Go to establish a claim
3. View manager dashboard
4. Validate against mocks

Screenshots: 
<img width="1178" alt="screen shot 2017-03-01 at 3 39 06 pm" src="https://cloud.githubusercontent.com/assets/23038505/23480434/e19b6992-fe95-11e6-9cfd-3000440c26ac.png">

**Comment by shanear** [comment]
@lakohl can you make sure whatever decision we make here is duplicated in the styleguide?

**Comment by KHarshawat-gov** [comment]
@astewarttistatech This is very very wrong but we're going to pass it so Shane and I can work on it next week as a case study for the style guide. We want to make sure the style guide is meeting the needs of problems like these. Would you mind creating an issue and assigning it the "Living Style Guide Version 1" milestone?

**Comment by astewarttistatech** [comment]
No prob @KHarshawat-gov
