### ISSUE TITLE
Create AMA issues component

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8591]
### Context
We'd like to componentize the way that AMA issues appear in Caseflow. Other teams can leverage the AMA issues component so that AMA issue display is standardized across Caseflow. To start, the Hearings team would like to use this component in the AMA Hearing Prep tool.

### Current state of AMA issues
<img width="1230" alt="screen shot 2019-01-09 at 2 59 11 pm" src="https://user-images.githubusercontent.com/40216950/50925047-2f342900-141f-11e9-8f1c-a61b58e29d1e.png">
<img width="921" alt="screen shot 2019-01-09 at 2 59 01 pm" src="https://user-images.githubusercontent.com/40216950/50925048-2f342900-141f-11e9-8f4b-98ceaa551ad6.png">

### Proposed mock
<img width="668" alt="screen shot 2019-01-09 at 2 44 14 pm" src="https://user-images.githubusercontent.com/40216950/50924728-69e99180-141e-11e9-86ab-24974c3a7c03.png">

### Specs
<img width="781" alt="screen shot 2019-01-09 at 3 03 33 pm" src="https://user-images.githubusercontent.com/40216950/50925249-c4372200-141f-11e9-91cb-4903e739e7cc.png">
Size 17 font. Labels are bold. "Note from NOD" is in italics.

**Comment by allyceh** [comment]
cc: @ShellySmithDSVA @MeredithStewart @laurjpeterson

**Comment by sneha-pai** [comment]
Mark's note: Can this component be broken down into subcomponents?

**Comment by laurjpeterson** [comment]
@carolaponce - for your feedback!

**Comment by tomas-nava** [comment]
MEDIUM - have to find the commonality between the existing implementations, and apply the design.

**Comment by laurjpeterson** [comment]
Re-opening because I don't think Anne's PR was able to be merged.

**Comment by laurjpeterson** [comment]
tagging @aroltsch to make sure it was merged.

**Comment by aroltsch** [comment]
It is merged and deployed. Can we have a designer validate this in Demo @laurjpeterson?

**Comment by laurjpeterson** [comment]
tagging @sneha-pai!

**Comment by aroltsch** [comment]
@laurjpeterson @sneha-pai could you close this ticket once this is validated please. Thank you both!

**Comment by laurjpeterson** [comment]
Demo may not be up to date, but I don't see this styling in demo to validate it - http://www.caseflowdemo.com/queue/appeals/d698f6c3-9a01-40d7-b76f-3d74f02800c7
<img width="1059" alt="Screen Shot 2019-06-02 at 6 55 04 PM" src="https://user-images.githubusercontent.com/27704093/58768356-07796500-8568-11e9-88af-1ff3592151e7.png">

**Comment by aroltsch** [comment]
@youngfreezyVA can you please check it out?

**Comment by laurjpeterson** [comment]
VALIDATED IN PROD WOO

**Comment by aroltsch** [comment]
YAS!
