### ISSUE TITLE
Generate page: Show a back button/link

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#86]
Right now, users are asked to use their back button. Have a button or link on the page that provides and alternate way to do this.

**Comment by paultag** [comment]
Are there pages where this was repeatedly an issue?

**Comment by paultag** [comment]
(Or rather - can we hack on the UX to remove the need for "Back"?)

**Comment by plusjeff** [comment]
Just the generate page.
