### ISSUE TITLE
Manager Dashboard | Hide "Work History" section

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#860]
As a Dispatch Manager, I would like the "Work History" section on the `Manager Dashboard` page hidden so that I only see the most important information necessary for me to manage my team.

# Acceptance Criteria
1. Verify that the "Work History" section on the `Manager Dashboard` page is no no longer visiable.  

## Mockup
**_View - Manager Dashboard page - Work History sect to be hidden_** 
    <img width="1059" alt="screen shot 2017-02-09 at 10 20 20 am" src="https://cloud.githubusercontent.com/assets/1596259/22789919/8d2d618c-eeb2-11e6-87e5-ac23861922f4.png">

## Technical Notes
- We may add this back into the manager in a different way, so it may be helpful to hang on to the code for a short time.

# Related Stories
Manager Dashboard | Update copy of page header and subtext #869
Manager Dashboard | Set number of Caseworkers for today #859
Manager Dashboard | Current | Change table information and section header to "Work Assignments" #867

**Comment by kierachell** [comment]
**PASSED**
and it's gone!
![manager](https://cloud.githubusercontent.com/assets/18075411/23186817/73b83a62-f856-11e6-82a4-37cd6a4cd9aa.png)
