### ISSUE TITLE
[Discussion] Reporting impact on application and database design

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8603]
Folks beyond the immediate Caseflow team have recently started to rely on the structure of the Caseflow application's data models in order to satisfy Board reporting requirements for AMA appeals. This has transformed the Caseflow database schema (and single-table inheritance) into an implicit external API. Prior to the introduction of this interface, the main Caseflow application had 3 well defined external interfaces: the main API consumed exclusively by our front-end web app, and the IDT and appeals status APIs.

During the course of active development on the Caseflow application, we routinely change the logic and configuration of code internal to the application. However, we take great care to ensure the external interfaces remain unaffected by the internal changes we make, and aggressively and proactively communicate when those interfaces will change. This existing practice has proved insufficient to ensure the stability of the new interface for reporting and we have struggled to maintain its reliability for our external users.

Existing measures to mitigate the impact internal changes have on reporting rely on shared institutional knowledge, and individual memory and foresight. Personally, I have failed to identify changes to our internal application that impact our reporting dependents on multiple occasions and think that it may be time to explore other solutions to the problem of our unreliable reporting interface. There are many possibilities, but I've outlined 3 below that present distinct avenues for solving this problem.

### 1. Encapsulate reporting schema in views

This approach has the benefit of allowing us to create automated tests for reporting data that external consumers rely on.

### 2. Store reporting tables into different database

Storing reporting data in a different database (on the same db server) would provide a distinct boundary between the internal and external data (which we could indicate in the application classes with a namespace, for instance). In additional to being more likely to notice this distinction in the code, we could add automated checks (Danger, CI step, etc.) to remind us when we have made changes to the external data models.

### 3. Make reporting data into immutable event log

One problem we encounter with our current approach is that the underlying data the reports rely on changes as a result not only of the changing data model structure (single-table inheritance class name changes, for example), but also of the underlying data and what that data represents. Moving toward a model where specific events trigger the entry of a record in an immutable event log could alleviate this issue.

I'm curious to hear thoughts on alternative solutions to this problem or if, perhaps, this problem is not such a great concern after all.

**Comment by pkarman** [comment]
We ended up doing 
> 2. Store reporting tables into different database

via the ETL/ODS process.
