### ISSUE TITLE
Assign cases to the correct Pamela Totten-Browning

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8605]
### Problem to be solved:
- Pamela Totten-Browning (Pamela.Totten-Browning2@va.gov) has Caseflow access. 
- [Looker](https://caseflow-looker.va.gov/looks/78) says she has 37 cases in assigned to her. 
- However, she is not able to see those cases in her Queue.

### Acceptance Criteria
- Pamela Totten-Browning has cases in her Caseflow Queue **and** she can see them.

**Comment by lowellrex** [comment]
Ms. Totten-Browning has two users and the cases were assigned to the one she was not logging in as. This has been corrected by adding the `new_pam` user to the `Colocated` organization and removing the `old_pam` (using the organizations user admin page) and by running the following commands to update the task owner to the correct user:

```ruby
rails c> old_pam = User.find_by(css_id: "bvapbrowning")
rails c> new_pam = User.find_by(css_id: "BVAPBROWNING")
rails c> Task.where(assigned_to: old_pam).count
# 39
rails c> Task.where(assigned_to: new_pam).count
# 0
rails c> Task.where(assigned_to: old_pam).each { |t| t.update!(assigned_to: new_pam) }
rails c> Task.where(assigned_to: old_pam).count
# 0
rails c> Task.where(assigned_to: new_pam).count
# 39
```

@marvokdolor-gov will confirm this fix worked with Pam and then we can close out this ticket!

**Comment by marvokdolor-gov** [comment]
Fix worked beautifully, thank you!
Closing.
