### ISSUE TITLE
Allow team admins to view and action on currently active tasks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8607]
Team admins (like branch chiefs, e.g. Rolandus) need to be able to reassign cases from one of their team members to another. So, when they click into a Case details page for a case assigned to one of their users, they need to see the currently active tasks assigned to their team/people in their team (even if it is not assigned to them) and be able to reassign them.

## AC
- When team admins view Case details page, tasks assigned to their team or people in their team populate in the Currently Active Tasks component
- Team admins can reassign tasks from one person on their team to another using the Actions drop down

## Open questions
- I don't think team admins need to be able to place the task on hold
- They likely will want to be able to complete tasks

**Comment by lowellrex** [comment]
Related to #7999

**Comment by lowellrex** [comment]
One route to explore with this ticket is determining if it would be easy to make `ColocatedTask` inherit from `GenericTask` which would give us this ability for free. I abandoned an effort to do just that two months back (#8005).

**Comment by lowellrex** [comment]
SMALL. Don't bother investigating whether we can inherit from `GenericTask`. We should be able to do this by simply using the [`task_is_assigned_to_user_within_organiztaion ?` Task method](https://github.com/department-of-veterans-affairs/caseflow/blob/11a3dd455137117df4fe05c435940e06717f786e/app/models/tasks/generic_task.rb#L33)
