### ISSUE TITLE
EP Creation: Decision Date should not be editable

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#861]
EP Creation: Do not allow user to edit decision Date on the EP Creation form.

**Comment by joofsh** [comment]
Questions for Jed
- Any sanity check on the manually entered decision date
- Use outcoding date for queries to determine recent full grants

**Comment by kierachell** [comment]
**PASSED**
![hah](https://cloud.githubusercontent.com/assets/18075411/23051453/1b1dfab2-f497-11e6-9ca3-7c13798d4d6c.png)
