### ISSUE TITLE
Appeal Intake Non-comp | On intake, create a "record request" task for non-VBMS business lines and add it to their queue

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#8612]
When the board intakes an appeal for a non-VBMS LOB, that LOB must be notified to send the relevant records to the board for review.

To facilitate this:

- Create a "record request" task
- Add the task to the LOB's intake queue
- Link the task to a "record request" confirmation page
- On the confirmation page, allow the user to confirm that they have provided the necessary records
- Once confirmed, mark the task "completed" so that it appears in the Completed tab

**Comment by steve-gov** [comment]
@carolaponce for visibility

**Comment by shanear** [comment]
dup of https://github.com/department-of-veterans-affairs/caseflow/issues/8674, closing
