### ISSUE TITLE
Story for closest_regional_office when Veteran's address (in BGS) is outside of US territories

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#8614]
#8550 finds the closest regional office for veteran within their state (or US territory). We need a workflow for handling instances when a veteran has an address in BGS that is outside of US territories (US, Puerto Rico, the Republic of the Philippines, Virgin Islands, American Somao, Guam, Marshall Islands, Micronesia, Northern Mariana Islands, and Palau). This job currently fails in that scenario.

**Comment by MeredithStewart** [comment]
Proposed Workflow: 

- For these that don't match, we would want to have the "Schedule Veteran" root task blocked and a blocking admin task, "Foreign Veteran Case." That task would be unassigned and appear in the organization queue for the Hearing Branch to deal with. They send a letter and give a Veteran 60 days to respond to say whether they cancel their hearing request or want to continue and let the Board know when they will be in the U.S.  

- To continue the flow, at that point they hear back and the Veteran will be in the US in New York on a certain time range, they will change that Veteran's Hearing Regional Office to New York. 

- Hearing Regional Office prior to this point should probably be null.

**Comment by MeredithStewart** [comment]
@Chingujo -- I think we should add the "Foreign Veteran Case" as an admin action in the list of drop down. This it could be possible to discovered later (Veteran moves abroad).
