### ISSUE TITLE
Route AMA Translation admin actions to Translation team queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8615]
For legacy cases: When attorneys identify documents needing translation, they assign a Translation admin action task to VLJ Support. VLJ Support can Send to Translation, which changes the case's location in VACOLS to 14.

We now have a Translation team queue, and would like to support Translation admin actions for AMA cases.

When VLJ Support is assigned a Translation admin action task from an attorney, they need to be able to send that task to the Translation team through Caseflow. 

Note: I personally think that we should just route translation tasks directly to the Translation team instead of going through VLJ Support, but will have to track down if we would be approved to do it.

## AC
- [x] Attorneys see Translation in their list of admin actions for AMA cases
- [x] When VLJ Support users are assigned a Translation task, they see the option to Send to Translation team in the Actions dropdown
- [x] When they send to Translation team in the dropdown, the caseflow task is assigned to the Translation team

**Comment by lowellrex** [comment]
Checked off the first acceptance criteria since attorneys can already see "Translation" in their list of admin actions for AMA cases.

![image](https://user-images.githubusercontent.com/32683958/51190094-6dae6580-18af-11e9-830c-41e918a9b7bc.png)

**Comment by lowellrex** [comment]
For the "Assign to Privacy team" action available to VLJ support staff, we enabled that option for all `ColocatedTask`s regardless of the task type (to reduce confusion about which options are available when--folks may not be aware that the type/action of task determines which options are available, and to eliminate the need to change the "action" of of a task if an attorney accidentally selects the wrong type of administrative action when they initially create it). Do we want to limit the visibility of the "Send to Translation team" option to only AMA appeals with the type/action "translation", or do we want to show this option regardless of the task's type/action?

cc @eric-nava @allyceh

**Comment by laurjpeterson** [comment]
@lowellrex 
> Just to confirm, when VLJ support staff select the "Send to Translation team" for Legacy appeals we update VACOLS location of the case to the Translation team's location. We want to continue doing that for Legacy appeals and only send AMA appeals to Translation's Queue, correct?
- Yes, I think we should continue to update the VACOLS location, 14, for legacy Translation tasks. The main reason for this is to ensure their VACOLS reports work. I would much prefer that all legacy + AMA cases can be worked in Caseflow (Translation team and individual queues) from the get go, but know that not being backwards compatible with VACOLS may open a can of worms with regard to productivity reporting. 

> Do we want to limit the visibility of the "Send to Translation team" option to only AMA appeals with the type/action "translation", or do we want to show this option regardless of the task's type/action?
- I think we should limit the Send to Translation to just Translation tasks, unlike what was decided for Privacy. This will reduce the probability that cases with tasks the Translation team cannot/should not action on are assigned to them.

**Comment by lowellrex** [comment]
Sounds good!
