### ISSUE TITLE
Appeal Intake | Set benefit type on rating issues

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#8619]
When a rating request issue is created, we need to determine whether the contested rating issue is a pension or a compensation rating issue.

## Acceptance Criteria
- When a rating request issue is created, we should record the benefit type as "pension" or "compensation" depending on whether the rating issue is a pension or compensation. 

## Technical Notes
We will need to figure out how to determine whether a rating issue is pension or compensation. There may be some helpful info in here: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1032

## Notes
Follow on to #8543 

See comment https://github.com/department-of-veterans-affairs/caseflow/pull/8577#discussion_r246584046

**Comment by pkarman** [comment]
suspect SOAP response fields: `bnftClmTc` and `isuDescr`

**Comment by pkarman** [comment]
after much email and investigation, we decided to treat any `bnftClmTc` that ends with `PMC` as a pension type.

**Comment by shanear** [comment]
confirmed our criteria is correct with AMO today 

- any rating issue decided on a PMC EP is considered a PMC issue. (Confirmed by Laila 01/31/2019)

**Comment by steve-gov** [comment]
Intook a NOD against a rated Pension issue:

<img width="219" alt="screen shot 2019-02-06 at 2 13 36 pm" src="https://user-images.githubusercontent.com/25468689/52377498-eb324500-2a19-11e9-87e9-fbd2e4072eb4.png">

Selected Direct Review docket and Pension line of business, and selected the only rated issue on the screen, the Pension issue:

<img width="516" alt="screen shot 2019-02-06 at 2 19 46 pm" src="https://user-images.githubusercontent.com/25468689/52377646-5bd96180-2a1a-11e9-93b5-ccc221059a4f.png">

This created appeal https://appeals.cf.uat.ds.va.gov/queue/appeals/74b1036e-357d-4002-a5d5-748cbd156c8a, which listed the benefit type as Compensation:

<img width="411" alt="screen shot 2019-02-06 at 2 21 38 pm" src="https://user-images.githubusercontent.com/25468689/52377723-904d1d80-2a1a-11e9-8b5c-9dcf8d228528.png">

I'm not sure that's being explicitly validated in this issue, but wanted to add it as a data point.

**Comment by steve-gov** [comment]
@pkarman Is there a way to know the `bnftClmTc` for the rated issue in my last comment -- the one with the 5004 diagnostic code?

**Comment by pkarman** [comment]
```
  @disability_codes=
   {"1131156"=>{:dgnstc_tc=>"5004", :date=>Tue, 05 Feb 2019 08:46:06 -0600}},
```

```
      :bnft_clm_tc=>"020CLMINC",
      :bnft_clm_tn=>"Claim for Increase",
```

interestingly though, under `disabilities` I see:

```
    :disabilities=>
     {:call_id=>"17",
      :jrn_dt=>Tue, 05 Feb 2019 08:46:06 -0600,
      :decn_tc=>"PENSION",
      :decn_tn=>"Pension",
      :dis_dt=>Tue, 05 Feb 2019 08:46:06 -0600,
      :prfl_dt=>Fri, 11 Jan 2019 13:12:06 -0600,
     },
```

so *somewhere* "pension" is entering into it.

**Comment by steve-gov** [comment]
Looking at the canonical list of EP codes, seems like at one point there _was_ a PMC code for Claim for Increase but that has been made redundant. It also doesn't seem like claims for increase are necessarily pension-related; in fact, most will be compensation-related. So this test data might be highlighting something of an edge case, and it may very well be coding correctly after all. Let me get another pension claim set up and run this again.

**Comment by steve-gov** [comment]
Validated multiple times for Comp issues.

New rated pension issue was promulgated. Made a board appeal against it and it coded correctly:

<img width="590" alt="screen shot 2019-02-13 at 10 05 45 am" src="https://user-images.githubusercontent.com/25468689/52733323-4bc00580-2f77-11e9-99ef-9732599e25fc.png">

<img width="568" alt="screen shot 2019-02-13 at 10 06 55 am" src="https://user-images.githubusercontent.com/25468689/52733325-4f538c80-2f77-11e9-9ecd-b3ba95e2253b.png">
