### ISSUE TITLE
Hearing Branch Admin Actions

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8622]
## User Stories 
* As a hearing coordinator, I need to be able to add a task to be completed before a Veteran can be scheduled. 

## Mocks: 
* Pages 26 - 44 here: https://va-gov.invisionapp.com/share/TUPWZLI7GBP 

## Acceptance Criteria 
* Verify that from the "Schedule Veterans" UI, the Hearing Coordinator can choose between "Schedule Veteran" and "Add Admin Action" on the Schedule Veteran task. (Page 30 & 35 of the Mocks) 
* Verify that the user can select an admin action from a list: 
    Verify power of attorney 
    Veteran is incarcerated 
    Contested Claimant issue (correct spelling error) 
    Verify address 
    Missing forms 
    FOIA/Privacy request 
    Foreign Veteran case 
    Other  
* Verify that the user can add task instructions per admin action. 
* Verify that the user can add another action and cancel that action if it is not needed. 
* Verify that the user is allowed to confirm admin actions with the copy, "Adding an admin action will move this case to your team's queue and remove it from the list of Veterans to schedule. (Page 40 of mocks) 
* Verify that the user confirm or cancel without saving admin actions.  (Page 40 of mocks) 
* Verify that the user receives a confirmation banner when the admin action has been added. Copy: "You have successfully added an Admin Action for Joe Snuffy. Joe Snuffy has been placed in your team's queue."  (Page 41 of mocks) 
* Verify that the user can add an admin action, which is blocking for the Schedule Veteran task. 
* Verify that Veterans with admin actions do not show on the list of Veterans to be scheduled (both AMA and Legacy) 
* Verify that when an admin action has been completed, the Veteran is returned to the list of Veterans to be scheduled (both AMA and Legacy) 
* Verify that when an admin action is been assigned for a Legacy appeal, that it moves out of VACOLS Location 57 (Hearing Branch) and into VACOLS Location 34 (Hearing Abeyance). 
* Verify that when an admin action has been completed for a Legacy appeal, that it moves out of VACOLS Location 34 and into Location 57. 
* Verify that when an admin action has been assigned, it appears in the Hearing Team queue. 
* Verify that when an admin action task has been placed on hold, it appears in the hold tab of that person's individual queue. 

## Related Epic 
* #8618 - EPIC | Queues and Admin Actions

**Comment by MeredithStewart** [comment]
On first question -- tagging @sharonwarner too -- I'm open to discussing using the Caseflow location. Note that there are some issues with the Caseflow location - anyone in VACOLS could mess with it and Jed confirmed he couldn't lock it down to prevent folks from moving the case in VACOLS out of the Caseflow location. 

Second question -- my understanding is that we wouldn't use the on-hold status unless it's been assigned. Tasks assigned to someone would just be assigned, the person who then is assigned the tasks would do somethign with it, then either close or put it on hold.

**Comment by mdbenjam** [comment]
Hmmm that's unfortunate that they can still modify the location. But that'll be a problem for location 34 as well right? If they move it to 57, the tasks are not necessarily completed.

So, I'm only going to show the on hold option after they've assigned to themselves.

**Comment by sharonwarner** [comment]
I'm not opposed to moving to the Caseflow location. Could we discuss this at Monday's hearing sync?

**Comment by mdbenjam** [comment]
- [ ] Verify that the user can add another action and cancel that action if it is not needed.

- [ ] Verify that the user is allowed to confirm admin actions with the copy, "Adding an admin action will move this case to your team's queue and remove it from the list of Veterans to schedule. (Page 40 of mocks)
- [ ] Verify that the user confirm or cancel without saving admin actions. (Page 40 of mocks)
- [ ] Verify that the user receives a confirmation banner when the admin action has been added. Copy: "You have successfully added an Admin Action for Joe Snuffy. Joe Snuffy has been placed in your team's queue." (Page 41 of mocks)
- [ ] Verify that Veterans with admin actions do not show on the list of Veterans to be scheduled (both AMA and Legacy)
- [ ] Verify that when an admin action is been assigned for a Legacy appeal, that it moves out of VACOLS Location 57 (Hearing Branch) and into VACOLS Location 34 (Hearing Abeyance).
- [ ] Verify that when an admin action has been completed for a Legacy appeal, that it moves out of VACOLS Location 34 and into Location 57.

Things remaining to do/verify that they work.
