### ISSUE TITLE
Individual Queues

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8623]
As a hearing coordinator, I need to be able to see all of my tasks so I can keep track of their statuses.

### Mocks
https://va-gov.invisionapp.com/share/TUPWZLI7GBP (pages 1 to 3)

### Table and page layout
- [ ] Verify the banner has an arrow next to Caseflow, that when selected has two options: 
  - Your Queue
   - Hearing Schedule 
- [x] Verify that the title of the page is "Your Queue"
- [ ] Verify that the queue table has three tabs: 
    - Assigned: Contains all of the tasks that are not on hold or just assigned
    - On hold: Contains all of the tasks that the user placed "on hold" and are awaiting further review or action
    - Completed: Contains all of the tasks the user has marked as complete 
- [x] Verify that in the upper right of the table there is a toggle called "Switch Views"
- [x] Verify that when the user clicks this toggle a dropdown appears with the following: 
      - Your Queue
      - Hearing Management Branch 
- [x] Verify that when the user clicks this link, it takes them to the organizational queue 
- [ ] Verify that there is pagination for the individual queue at the bottom of the screen
  - Verify that we are showing 10 cases per page 

### Assigned Tab 
- [x] Verify the following columns in the Assigned tab: 
     - Case details: A link to the case details in the following format Veteran First Name Last Name | Appeal ID
      - Task: The name of the task
      - Regional Office: Displays the regional office and it should be null 
      - Type: The type of the tasks with the same prioritization from Queue
      - Docket Number: Shows in the following format Docket label #
      - Days waiting: Shows the number of days passed since it was assigned 
- [ ] Verify that the task and regional office is filterable

### On Hold Tab
- [x] Verify that all of the same information in Assigned tab shows in the On Hold Tab 
- [ ] Verify that the task and regional office is filterable

### Completed tab
- [x] Verify that this tab has all of the same information from the Assigned tab 
- [ ] Verify that the task and regional office is filterable

### Related Issues
* #8618 - EPIC | Queues and Admin Actions 
* #8626 Organizational Queues

**Comment by mdbenjam** [comment]
Most of this is being built by Queue. I'll work with them to make sure things are on track. The only thing here I don't think they're going to tackle is the regional office column. I'll circle back to that.

**Comment by mdbenjam** [comment]
Remaining features already have other issues. Closing this issue so we can better track the remaining aspects:
- Filtering: https://github.com/department-of-veterans-affairs/caseflow/issues/8215
- Pagination: https://github.com/department-of-veterans-affairs/caseflow/issues/8242
- Inter-app navigation: https://github.com/department-of-veterans-affairs/caseflow/issues/7503
- Removing pending action: https://github.com/department-of-veterans-affairs/caseflow/issues/8277
