### ISSUE TITLE
Assignment of Tasks from Case Details

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#8625]
## User Stories
As a Hearings Branch user, I should be able to assign open tasks to myself when I am viewing the case details of a particular case. This will allow me to work specific cases easily.

As a Hearings Branch user, I should be able to assign open tasks to other members of my team in the case details view. This will allow me to to assign or re-route tasks easily and break up works on a case. 

## Mocks
See pages 16-22 of the following InVision file: https://va-gov.invisionapp.com/share/TUPWZLI7GBP#/screens/340231214

## Related Epic
See Epic #8618 for the other associated items with this ticket.

## Acceptance Criteria
- [x] Verify that each open task has an in line drop down that allows users the options to "Assign task to self" or "Assign task to" 
- [x] Verify that when the user selects Assign task to self the user is taken back to the Team queue and is given a confirmation message at the top of the page. 
- [x] Verify this confirmation message includes a link to the user's queue.
- [x] Verify when the user selects Assign task to a modal appears on the case details page.
- [x] Verify the Assign Task modal contains a drop down list of all Hearing team users and a field for notes.
- [x] Verify the user is brought back to the Hearing Team queue and a confirmation message is given at the top of the screen showing what what Vet and task type was assigned to what user. 

## Related Epic 
* #8618 - EPIC | Queues and Admin Actions

**Comment by mdbenjam** [comment]
Everything was completed except for the "Assign to self" action, which we're going to hold off on implementing since the "Assign to" modal defaults to yourself.
