### ISSUE TITLE
Organizational Queues

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8626]
As a hearing branch management team, I need to have a place where all of the orgs tasks are clearly visible both to assign my cases to myself and others and to keep track of them. 

### Mocks
https://va-gov.invisionapp.com/share/TUPWZLI7GBP (pages 13 to 15)

#### General page and layout
- [x] Verify that the title of the page is Hearing Management Branch Queue
- [x] Verify that there is dropdown button called Switch Views in the upper right of the table
   - Verify that clicking on this renders a dropdown with the following: 
      - Hearing Management Branch Queue
      - Your Queue
- [x] Verify that there is a Queue table with three tabs: 
 - Unassigned: All of the tasks that have yet to be assigned to a hearing team member
_Note: Please ensure that the default state of all unopened tasks are bolded and clicking them unbolds the link_
 - Assigned: All of the tasks currently assigned to an individual 
 - Completed: All tasks that are completed 
- [ ] Verify that there is pagination for the Org queue at the bottom of the screen
  - Verify that we are showing 50 cases per page 

### Unassigned
- [x] Verify the following columns are in the unassigned table in the following order: 
- Case details: A link to the case details in Veteran Last Name Last Name | Appeal ID
- Task: The task type 
- Regional Office: The RO of where the task was originated. This would be null if foreign veteran case
- Type: The same type field and prioritization in Queue showing if the case is CAVC, AOD, or other
- Days Waiting: The number of days waiting since the task was created 
- [ ] Verify that the task column and the regional office is a filterable column and when clicked a searchable filter appears

### Assigned Tab
- [x] Verify that the same information from the Unassigned appears on this page with the following exceptions: 
 - Verify that there is an Assigned to column after the Regional Office 
 - Verify that that the Days Waiting shows the number of days since assigned
- [ ] Verify that the Assigned to column is filterable and clicking on that list shows all of the hearing branch team members in the following format: 
- First Name Last Name (# assigned) 

### Completed Tab
- [x] Verify that the completed tab has all of the same information as the Unassigned tab without the days waiting
- [x] Verify cases appear same as the default as queue 

### Related Issues
* #8618 - EPIC | Queues and Admin Actions 
* #8623 Individual Queues

**Comment by mdbenjam** [comment]
Remaining features already have other issues. Closing this issue so we can better track the remaining aspects:

Filtering: #8215
Pagination: #8242
