### ISSUE TITLE
Create judge teams for former chief judges

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8629]
With the Board reorganization, chief judges are now line judges with their own attorney teams. We need to create organizations for each of these judges so we can associate their attorneys to their team.

## AC
- Organizations exist for these judges:

1. Bob Scharnberger
2. John Jones
3. Claudia Trueba
4. Keith Allen
5. Anthony Scire
6. Cynthia Bruce
7. Cherry Crawford
8. Theresa Catino
9. Bethany Buck
10. James March

**Comment by lowellrex** [comment]
Created `JudgeTeam`s for the 10 judges listed above:
```ruby
  rails c> judge_names = ["ROBERT SCHARNBERGER", "JOHN Z JONES", "CLAUDIA TRUEBA-SESSING", "Keith Allen", "Anthony Scire", "Cynthia Bruce", "Cherry Crawford", "Theresa Catino", "Bethany Buck", "James March"]
  rails c> judge_users = judge_names.map { |nm| User.where('lower(full_name) = ?', nm.downcase) }.flatten
  rails c> judge_teams = judge_users.map { |u| JudgeTeam.create_for_judge(u).tap { |team| team.update!(url: team.name.downcase) } }
```
