### ISSUE TITLE
Pull issue information from VACOLS

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#863]
Currently we're just using fake VACOLS information in #736. We need to pull in the real information.

**Comment by lakohl** [comment]
Gotcha. No a big deal, but in demo, under the Disposition it currently says 'Granted'. Turns out this is the wrong terminology. It should say 'Allowed'.

**Comment by mdbenjam** [comment]
What are the other options? Remanded? And is Denied an option?

**Comment by lakohl** [comment]
that sounds right to me. Keep in mind we are speaking now about the issues within a claim, not the appeal as a whole. @cmgiven is probably in the best position to answer your question as I don't have access to VACOLS

**Comment by cmgiven** [comment]
1 - Allowed
3 - Remanded
4 - Denied
5 - Vacated
6 - Dismissed, Other
8 - Dismissed, Death
9 - Withdrawn

Anything that's not one of those codes (i.e. is a letter, not a number) was decided in the field, and can be dropped.

**Comment by kierachell** [comment]
Need to resolve Dispatch test data problems before this can be validated

**Comment by kierachell** [comment]
**PASSED**
It's pulling something...
![dispallowed](https://cloud.githubusercontent.com/assets/18075411/23166258/ef06c38a-f80d-11e6-9d4d-ca1d1da37a23.png)
![dispallowed2](https://cloud.githubusercontent.com/assets/18075411/23166916/9741c2d2-f810-11e6-8162-f87b23398051.png)

Matches the data in VACOLS;

**Comment by lakohl** [comment]
@kierachell the decision type is missing and lines should be lighter grey (like in the tab).
The VACOLS Decision Criteria should look like this:
<img width="640" alt="screen shot 2017-02-21 at 11 05 01 am" src="https://cloud.githubusercontent.com/assets/4975959/23172968/a101a37c-f825-11e6-8d51-d33fd387fa4c.png">

**Comment by kierachell** [comment]
This issue relates to purely back-end functionality as I understand; the original issue #736 did not include the AC listed in the comment above. Probably needs to be a new issue
