### ISSUE TITLE
Individual Queues Case Details Actions

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8630]
As a hearing coordinator, I want to be able to place tasks on hold, complete them, or re-assign them to someone else from my individual queue so I can effectively close out tasks, assign them as needed in case of error or sickness, and keep track of pending tasks. 

### Mocks
https://va-gov.invisionapp.com/share/TUPWZLI7GBP#/screens/340231214 (4 to 12)

### General Page and Layout
- [x] Verify that we are adopting the most up to date Case Details page
- [x] Verify that the task shows up in the Current Tasks Section underneath the Case Details Veteran Snap Shot
- [x] Verify that the task has the following: 
 - Assigned on : Date assigned
 - Days Waiting: Number of days since assigned
- Task history: A timeline of the task 
- Assigned to: Who it is currently assigned to
- Assigned by: Who assigned it
- Task: The name of the task
- Task instructions: When clicked shows the task instructions for that task 
- Actions section 
- [ ] Verify that clicking on action has the following three options: 
- Place on hold - launches the place on hold flow
- Mark as complete - completes the task
- Re-assign - Assigns the case to someone else or release back to the organizational queue 

### Place on hold
- [x] Verify that there is a page titled and header area follows Queue on hold
- [x] Verify that there is a drop down called Select days on hold with the following options: 
- 15 days 
- 30 days
- 45 days
- Other 
  - Verify that clicking other renders another text input where a custom day can be entered
- [x] Verify that there is a Notes field where the user can type additional notes
- [x] Verify that there is a Cancel Button and a Place on Hold button on the bottom right
- [x] Verify the following confirmation when the user clicks place on hold
- Title: You have placed Veteran First Name, Last Name's [Task Name] on hold for [Number of Days]
- Body: You can find this case in the on hold tab of your queue

### Mark as Complete
- [x] Verify that when the user selects "Mark as Complete" a modal pops up with the same Title
- [x] Verify the following copy: 
- Marking this task as complete will remove this admin action from your active tasks
- [x] Verify that cancel closes the modal
- [x] Verify that Mark as Complete moves it to the completed tab of the individual queue
- [x] Verify that there is a modal 
- [x] Verify that there is a confirmation banner with the following copy:
- Title: You have successfully completed Veteran First Name, Last Name's [ task name]
- Body: You can find this case in the completed tab of your queue 

### Re-assign
- [x] Verify that clicking on the "re-assign" action renders a modal 
- [x] Verify the modal has the following options: 
- Send back to org queue
- Hearing branch team members
- [x] Notes section
- [x] Verify that there is a Confirm assignment button
 - Verify that clicking confirm routes to the correctly selected individual or queue 
- [x] Verify the following confirmation message: 

### Related Issues
* #8618 - EPIC | Queues and Admin Actions 
* #8623 Individual Queues

**Comment by MeredithStewart** [comment]
@mdbenjam -- Pending action tab is removed in our designs, it was supposed to be gone from Queue in general. Has that not happened yet?

**Comment by MeredithStewart** [comment]
For completing tasks: I don't think the original copy apply to Hearings flow. We'll need the modal body for completing tasks to be updated to copy on the designs.

**Comment by Chingujo** [comment]
@mdbenjam 

Thanks Marks =D! Some context and my thoughts below

For on hold tasks, we can adopt whatever Queue has as long as it is confirming that the task has been placed on hold and the pending action language is removed per @MeredithStewart 

For completing tasks, we were going for specificity because it was not just moving to a completed tab but back to the pool in the scheduling application.

**Comment by mdbenjam** [comment]
@laurjpeterson @eric-nava Is the pending action tab no more? Can we change the on hold success message from "When the hold has been completed, the case will be automatically moved to the Pending Action tab." to "You can find this case in the on hold tab of your queue."

**Comment by mdbenjam** [comment]
How about the success message after completing a task? Can we change it from "If you've made a mistake, please email <assigner> to manage any changes." to "You can find this case in the completed tab of your queue"?

**Comment by eric-nava** [comment]
How long do cases stay in the completed tab? I like the idea of an error prevention measure that doesn't deprecate right after the user leaves the page

**Comment by mdbenjam** [comment]
I think it's 10-15 days? @lowellrex

**Comment by lowellrex** [comment]
Correct! [14 days](https://github.com/department-of-veterans-affairs/caseflow/blob/0de085e622d707d9407732b1eb57d7c74cf08e51/app/models/task.rb#L73)

**Comment by eric-nava** [comment]
Cool - I'm in support of the change you proposed, Mark.
