### ISSUE TITLE
Prevent Double Calls to BGS

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#8631]
`Veteran.accessible?` is redundant when also calling `BGSService.fetch_veteran_info` / `Veteran.fetch_bgs_record`

**Comment by ferristseng** [comment]
Might be able to cache accessible in `BGSService.fetch_veteran_info` in the same way we cache veteran info in `BGSService.can_access?`

**Comment by pkarman** [comment]
I think this ticket is moot now. You are correct that the caching in can_access? now does this.
