### ISSUE TITLE
Add "Send to Judge for signature" action for ColocatedTasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8634]
One common admin action VLJ support staff take is sending extension request grant memos to the appellants' representatives. These memos are drafted by the VLJ support staff, sent to the judge for signature, returned to the VLJ support staff, and sent out to the representative by the VLJ support staff. The communication between VLJ support staff and judge currently happens over email but they would like to be able to send the case (and document) to the judge directly with a "send to judge for signature" task action or something similar.

## Acceptance criteria
* [ ] VLJ support staff can send tasks to the judge for `ColocatedTask`

**Comment by araposo-tistatech** [comment]
@araposo-tistatech try to get some data around how often this happens. Also, are there any other task types that require judge signatures? Is this the only team that would ever request a judge signature?
