### ISSUE TITLE
Cancel Hearing Request (before Scheduled)

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8635]
We need to add an action, perhaps at the root task of "Schedule Veteran" that allows the user to close the Schedule Veteran task when the user has opted to withdraw their hearing request - for both AMA and Legacy. 

### Acceptance Criteria
- [ ] Verify that in the "Schedule task" action modal there is an additional task called " Withdraw hearing request"
- [ ] Verify that there is a modal that confirms the withdrawal with the following copy:
   - Title: Confirm withdraw hearing
    - Body: Withdrawing this hearing request will remove this veteran from the hearing pool. 
- [ ] Verify that confirming the withdrawal renders a success message and redirects to the hearing schedule table
    - Title: You have successfully withdrawn [Veteran Name]'s hearing request
     - Body: [Veteran Name] has been removed from the hearing schedule and has been sent to the next appropriate location
- [ ] Verify that this closes the hearing schedule task and removes it from the hearing schedule pool (location 57)
- [ ] Verify that it is moved to location 55 if VSO and location 81 if no VSO
- [ ] Verify that for legacy appeals, we update BRIEFF.BFHR = ‘5’ and BRIEFF.BFHA = ‘5’ so the appeal falls off any pending hearing reports, 5 = none

### Mock
_Add Withdraw hearing request as an option in the schedule hearing task_
![add admin action task enabled dropdown](https://user-images.githubusercontent.com/23316107/52012186-eadcfb80-24a7-11e9-8d5a-12bfcca303ac.png)

_Modal confirm_
![confirm hearing withdrawal](https://user-images.githubusercontent.com/23316107/52012745-668b7800-24a9-11e9-87d9-bc7c6ce5b02b.png)

_Final cofirmation_
![scheduled veteran](https://user-images.githubusercontent.com/23316107/52012615-085e9500-24a9-11e9-8eeb-49234aa44281.png)

**Comment by mdbenjam** [comment]
@Chingujo Why do appeals go to 55 after a hearing? What subset of these VSOs count:

```
  REPRESENTATIVES = {
    "A" => { full_name: "The American Legion", short: "American Legion" },
    "B" => { full_name: "AMVETS", short: "AmVets" },
    "C" => { full_name: "American Red Cross", short: "ARC" },
    "D" => { full_name: "Disabled American Veterans", short: "DAV" },
    "E" => { full_name: "Jewish War Veterans", short: "JWV" },
    "F" => { full_name: "Military Order of the Purple Heart", short: "MOPH" },
    "G" => { full_name: "Paralyzed Veterans of America", short: "PVA" },
    "H" => { full_name: "Veterans of Foreign Wars", short: "VFW" },
    "I" => { full_name: "State Service Organization(s)", short: "State Svc Org" },
    "J" => { full_name: "Maryland Veterans Commission", short: "Md Veterans Comm" },
    "K" => { full_name: "Virginia Department of Veterans Affairs", short: "Virginia Dept of Veteran" },
    "L" => { full_name: "No Representative", short: "None" },
    "M" => { full_name: "Navy Mutual Aid Association", short: "Navy Mut Aid" },
    "N" => { full_name: "Non-Commissioned Officers Association", short: "NCOA" },
    # TODO: double check that "Other Service Organization" is the correct full name.
    # Possibly this should just be "Other"
    "O" => { full_name: "Other Service Organization", short: "Other", rep_name_in_rep_table: true },
    "P" => { full_name: "Army & Air Force Mutual Aid Assn.", short: "Army Mut Aid" },
    "Q" => { full_name: "Catholic War Veterans", short: "Catholic War Vets" },
    "R" => { full_name: "Fleet Reserve Association", short: "Fleet Reserve" },
    "S" => { full_name: "Marine Corp League", short: "Marine Corps League" },
    "T" => { full_name: "Attorney", short: "Attorney", rep_name_in_rep_table: true },
    "U" => { full_name: "Agent", short: "Agent", rep_name_in_rep_table: true },
    "V" => { full_name: "Vietnam Veterans of America", short: "VVA" },
    "W" => { full_name: "One Time Representative", short: "One Time Rep", rep_name_in_rep_table: true },
    "X" => { full_name: "American Ex-Prisoners of War", short: "EXPOW" },
    "Y" => { full_name: "Blinded Veterans Association", short: "Blinded Vet Assoc" },
    "Z" => { full_name: "National Veterans Legal Services Program", short: "NVLSP" },
    "1" => { full_name: "National Veterans Organization of America", short: "NVOA" },
    "2" => { full_name: "Wounded Warrior Project", short: "WWP" },
```

Is it only co-located VSOs? Or all of them?

**Comment by mdbenjam** [comment]
For the above question, Chris reminded me that we're going to BGS for POA, so the data will look different, but the question remains. Is this for all VSOs, or just co located VSOs?

Also do we want to redirect back to the Hearing Schedule page? Or put a link in the success message like the schedule hearing flow?
![screen shot 2019-01-31 at 6 22 38 pm](https://user-images.githubusercontent.com/3885236/52092343-3dd8b080-2585-11e9-9935-47af34940915.png)

Don't care which way, just want to be consistent.

**Comment by Chingujo** [comment]
Hi @mdbenjam!

Here is some more context

When a hearing is cancelled and the veteran has a VSO it gets sent to location 55 for an IHP (informal hearing request) for any co-located VSO. However, I will verify this during our training today with the HBM team since 55 is a general HMB location (by 11:00 am est Feb 1st).

If the veteran has no rep, then it goes to 81 case storage 

----------------

For the banner link, seen this in some designs and just a way for a user to go back with out looking for a link. Agree that it is redundant and we should keep consistent. Let's go with with the link on the hearing schedule page if you mean the carrot << back to hearing schedule in the upper left =D
