### ISSUE TITLE
Follow-up with VSO users belonging to two VSOs

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8636]
When all VSO organizations have been made and the below users have access, let's follow up with them to ensure their toggling between organizations is working as designed. 

These users belong to both Military Order of the Purple Heart(MOPH) and National Veterans Legal Services Program (NVLSP).

Name | Email | CSS ID | Station
-- | -- | -- | --
Spinnicchia, Michael | Michael.Spinnicchia@va.gov | NVLMSPIN | 372
Ivory, Alexis | Alexis.Ivory2@va.gov | NVLIVLORY | 372
Spataro, Richard | richard.spataro@va.gov | NVLRSPAT | 372

**Comment by marvokdolor-gov** [comment]
**Update 3/4**: Before reaching out to them, it looks like this issue should be closed: #9693.

**Comment by laurjpeterson** [comment]
@msj0nes - do you know the station IDs for the above users? I tried to impersonate them with Station 101 and it did not work.

**Comment by msj0nes** [comment]
@laurjpeterson added

**Comment by laurjpeterson** [comment]
I tried all three of these logins and station IDs and could not impersonate the users. Do we have the right CSS IDs and station IDs?

**Comment by araposo-tistatech** [comment]
Closing, if someone is apart of two organizations, they can switch between organizations.
