### ISSUE TITLE
Daily Docket Design Updates

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#8645]
## User Stories
As a Hearings Schedule user, I need to be able to easily print my daily docket so that I can prepare the room and judges for the cases they are hearing that day.

As a Hearings Schedule user, I need to update information for the docket all in one place to accommodate last minute changes to judges, rooms, and other items via the link to the Edit Hearing Details. 

## Mock Ups
See the following Invision link: https://va-gov.invisionapp.com/share/H3PXTJOA4DX#/340490395_Daily_Docket-NEW

![screen shot 2019-01-14 at 12 49 21 pm](https://user-images.githubusercontent.com/45463980/51132682-e73b4a80-1800-11e9-9125-56d13b3fd613.png)

## Acceptance Criteria
**Hearing Schedule View**
- [x] Verify the Regional Office drop down is added to this view
- [x] Verify Copy Requested by Appellant/Rep is and the check box is added to this view and that the information carries over to the Hearing Prep, Hearing Details, and other locations the check box is present
- [x] Verify the Edit Hearing Details link is added to this views, and opens the Hearing Details 
- [x] Verify the column order of the first list is Disposition / Transcript Requested / Hearing Details / 
- [x] Verify the column order includes Regional Office / Hearing Location / Hearing Day / Time listed in the second list
- [x] Verify the Regional Office is listed in the upper right hand corner of the page along with the Hearing Type, Room Number, etc. This information should be viewable even when no Veterans are scheduled for that day. 

## Related Ticket
See #8653 for the work related to the time selector.

**Comment by MeredithStewart** [comment]
@ShellySmithDSVA -- Add RO for video hearings to upper right corner.

**Comment by MeredithStewart** [comment]
@ShellySmithDSVA -- I removed the user story about the Judge, since we'd have to make these updates separately on the Hearing Prep daily docket page.
