### ISSUE TITLE
Business Line | Pension | Set payee code to "00" for burial and accrued pension claims

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8647]
For a particular classification of pension claims (Burial and Accrued), VBMS requires the payee code to be 00, even though the veteran is deceased. This is required to create the Burial and Accrued award, should it be granted.

### Acceptance Criteria
- [ ] If a claim review for a deceased veteran with a benefit type of "Pension" has a request issue that is a burial or accrual issue, establish the claim with a payee_code of "00", instead of the claimant's payee_code
- [ ] If there are other issues on the claim, they can get established on a separate end_product with the claimant's payee_code
- [ ] This should also be true for remand supplemental claims
- [ ] Update documentation: 

Nonrating issue categories to include:

- Burial Benefits - NSC Burial
- Burial Benefits - Plot or Interment Allowance
- Burial Benefits - Transportation Allowance
- Burial Benefits - VA Hospitalization Death

## Open questions
- Currently there are no "accrued" issue categories under Pension, just Education

## Tech notes
nonrating_issue_category is a field on the request issue
Check out `new_end_product_establishment` for adding the payee code logic
`end_product_establishment_for_issue` should be updated to look for existing end products with both the same EP code and the same payee code
See nonrating issue categories in `ISSUE_CATEGORIES.json`

**Comment by leikkisa** [comment]
Pension issue categories to include:
    "Apportionment",
    "Burial Benefits - NSC Burial",
    "Burial Benefits - Plot or Interment Allowance",
    "Burial Benefits - Transportation Allowance",
    "Burial Benefits - VA Hospitalization Death"

**Comment by leikkisa** [comment]
I tested the "00" payee_code on a deceased Veteran in UAT and was able to successfully create a claim.

We are investigating how to identify Burial ratings (Mary Kay says they can be rating issues), and which other relationship types besides dependents are eligible to be claimants, so that they are available in the list of claimants.

**Comment by leikkisa** [comment]
From Daniel McCargar:

There should be no need for Fiduciary to handle CPD Payee 00 awards.  They WILL need the ability to do CPD Payee 10 through 78.

Accrue benefit are essentially anything the Veteran claimed prior to passing away, so the rating issues can be claims for service connection, increase, etc, as well as the Pension Rating issues.  Here is what some of the backend things should look like for Accrued EPs.  Label, EP, and Code are just suggestions.   The only burial issue that could be rated is Service-Connected death.

Label | EP | Code | User Modify | PCAN | PCLR | PCHG | Propose / Auth Award | Attr1 | Attr1 Txt | Attr2 | Attr2 Txt | Attr3 | Attr3 Txt
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PMC Accrued HLR | 040 | 040PMCHLRAccrued | Yes | Yes | Yes | Yes | Yes | CLAIM_TYPE_LABEL | Death | USER_DISPLAY | Yes | Rating/Non-Rating | Non-Rating

From Ethan Parker
This is by no means fully vetted for requirements, but the following fiduciary decisions are distinct and appealable:

•             appointment of a fiduciary
•             removal of a fiduciary
•             misuse determination
•             reconsideration of a misuse determination
•             negligence determination

For Burial there are primarily the following benefits:
- Non-service connected burial allowance
- Service-Connected Burial Allowance
- Plot allowance
- Transportation Reimbursement

We also do grant headstone marker/reimbursement, but those are infrequent.

**Comment by msj0nes** [comment]
Closing ticket. Not currently prioritized.

Associated https://github.com/department-of-veterans-affairs/caseflow/issues/11997

**Comment by leikkisa** [comment]
Adding blocked because we've been specifically asked not to work on this.
