### ISSUE TITLE
Transcription Queue Pre MVP

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#8651]
## User Stories
As a Hearings Schedule user, I need to be able to successfully record a held hearing and make sure that hearing is transcribed fully and successfully.

## Mocks
https://va-gov.invisionapp.com/share/MXPXWUDKSP6

## Acceptance Criteria
- [x] Verify the task can be closed by choosing Mark as complete: Transcribed. This will close the task and release the case to judge review.
- [x] Verify the task can be closed by choosing Mark as complete: Reschedule hearing. Choosing this option will create a ScheduleHearingTask assigned to Hearings Management.

## Related Tickets
See Epic #8650 for the complete scope of work related to this ticket.
See #8655 for the full Postponement flow.

**Comment by mdbenjam** [comment]
@ShellySmithDSVA 

I didn't see copy for the "mark task as complete: transcribed" option in the mocks. How about something like this? "Mark transcription as completed and send appeal to the next team."

That's what I'm adding for now, but we can change it to whatever.

**Comment by ShellySmithDSVA** [comment]
@mdbenjam - I have added the confirmation module screen to the mocks.
