### ISSUE TITLE
Display task column in judge queue table view

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8652]
The only things that appeared in judges' queue table views prior to the quality review pilot were decisions to be signed. Now that judges can get quality review tasks we should show the task label in the queue table view to indicate what action they need to take on the appeal at a glance.

## Acceptance criteria
* [ ] Show task label in the judge queue view
* [ ] [Title case the task label](https://github.com/department-of-veterans-affairs/caseflow/issues/8652#issuecomment-453603556)

Before | After
--- | ---
![image](https://user-images.githubusercontent.com/32683958/51050422-c1af0680-159e-11e9-87e8-700cc4857c2b.png) | ![image](https://user-images.githubusercontent.com/32683958/51050723-b7413c80-159f-11e9-931c-2c9fa475309e.png)

**Comment by lowellrex** [comment]
cc @allyceh @eric-nava for thoughts on the visual appearance of this new tab (we don't have the ability to change the sort order yet, as a heads up). Maybe we should be upper-casing these strings though?

**Comment by allyceh** [comment]
Visual appearance looks good to me. Can we use title case for these strings since "type" is also using title case? Ex: "Review", and "Quality Review"
