### ISSUE TITLE
Add time selector for hearings

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8653]
## User Stories: 
* As a hearing coordinator, I will sometimes need the ability to select a time that is different than or more specific than 8:30/12:30 for video hearings or 9:00/1:00 for CO hearings. 
* As a hearing coordinator, if I will need to select a specific hearing time in half hour increment for Veterans for future Board telehearings.
* As a hearing coordinator, I may need to select a specific hearing time to accommodate the needs of alternate hearing locations. 

## Mocks: 
* Daily Docket - https://va-gov.invisionapp.com/share/H3PXTJOA4DX 
![screen shot 2019-01-14 at 1 39 14 pm](https://user-images.githubusercontent.com/45463980/51133233-6d0bc580-1802-11e9-89fb-4488b67f1524.png)
![screen shot 2019-01-14 at 1 39 27 pm](https://user-images.githubusercontent.com/45463980/51133234-6da45c00-1802-11e9-8937-a0be499866d3.png)

* Schedule Veteran modal - https://va-gov.invisionapp.com/share/K6PYN2NBTQF
![screen shot 2019-01-14 at 1 39 55 pm](https://user-images.githubusercontent.com/45463980/51133248-76952d80-1802-11e9-8faa-c11f449ba84f.png)
![screen shot 2019-01-14 at 1 40 15 pm](https://user-images.githubusercontent.com/45463980/51133249-772dc400-1802-11e9-99a9-b1e4ad1fe985.png)

* Reschedule Veteran modal  - https://va-gov.invisionapp.com/share/XUPVE1WEGTR#/339762030_Daily_Docket_Schedule_Now (page 2 for module, behavior should mimic the Schedule Veteran module)
![screen shot 2019-01-14 at 1 39 41 pm](https://user-images.githubusercontent.com/45463980/51133260-7f85ff00-1802-11e9-9213-22a5b039aa2c.png)

## Acceptance Criteria 
- [ ] Verify that a user can select "Other" radio button from time choices
- [ ] Verify that when "Other" is selected, user is presented with a drop down time selector that gives scheduling in 30 minute increments from 8:30 a.m. - 4:30 p.m.

## Related Ticket
See #8645 for the larger Daily Docket design updates.

**Comment by MeredithStewart** [comment]
Question: Will the new time selector also work/display times appropriate for the Regional Office/Judge in Hearing Prep?

**Comment by Sjones352** [comment]
@MeredithStewart I thought that the time selector is only being implemented for Hearing schedule?.

**Comment by ShellySmithDSVA** [comment]
@Sjones352 - this option and selector would be available anywhere you can schedule or re-schedule a  vet, including in the Postponement and schedule modules. We'll discuss design re: RO time / Hearing prep.
