### ISSUE TITLE
Contested Claims MVP - Research

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8660]
## Background

By Feb 14, we need a way for BVA employees to know that a case has a contested claim so that they can handle it according to BVA processes. In the short term, we are proposing that:

**Intake team**
- When the Intake team sees a case with a contested claim, they will funnel cases with contested claims to a legal detailee who will be working closely with the Intake team to handle these edge cases. 
- The legal detaillee will ensure that the case is processed correctly and notify all parties. 

**Attorneys/Hearings/BVA Dispatch**
- If a case is a contested claim and has issues that are sometimes contested or always contested, we will display a flag on the case details page so that attorneys/hearings/BVA Dispatch can proceed with the case according to their process. 

Issues to be flagged: 
Always contested claims:
- Apportionment
- Attorney fees
Maybe contested claims:
- DIC: two claims for DIC received from two or more persons
- Veteran death related e.g. funeral expenses

For more info, long term scope, and additional user stories for later enhancements, see our Mural epic (head to mural and search for `Contested Claims`).

## User Stories
(Note: I only pulled user stories from our Mural that applied to our MVP)

- As an Intake user, I need to know if an AMA case involves contesting claimants so that I can send it to a legal detailee to handle
- As an Intake legal detailee, I need to know if an AMA case involves contesting claimants so that I can send a notification letter to all parties that acknowledges that their case is at the BVA.
- As a hearing coordinator, I need to see that an appeal has a contested claimant before I schedule a hearing so that I can notify all parties and schedule the hearing and send a notification letter to all parties.
- As a BVA dispatcher,  I need to know if an appeal has a contested claimant so that I can send a decision letter to all parties. 
- As an attorney/judge, I need to know whether or not a case has a contested claim so that I can review the case and draft BVA decision letters accordingly.   
- As an attorney/judge/dispatcher/hearing coordinator, I need to see the POA for all claimants so that I can send copies of correspondence to each. 

## AC
- AMA cases only
- If an appeal has any issue with the issue category `Apportionment` or `Contested Claims (other than apportionment)`, display message per mock below in the About the Appellant section of Case Details.

## Mocks 

About the Appellant section of Case Details
![image](https://user-images.githubusercontent.com/40216950/51264532-bbe16880-1984-11e9-9cba-0836be6c1d00.png)

Case header
Display "This could be a contested claim" in the case header if the issues are flagged as contested claim issues. 
<img width="564" alt="screen shot 2019-01-22 at 3 33 13 pm" src="https://user-images.githubusercontent.com/40216950/51563869-96100400-1e5b-11e9-867b-7ac0ed90f56c.png">
Note: Today, we display "The appellant is not the veteran" in the case header if the appellant is different than the veteran, but the case is not a contested claim. Ex: the veteran is deceased, and the spouse is appealing for benefits.

**Comment by allyceh** [comment]
@marvokdolor-gov @laurjpeterson FYI

**Comment by laurjpeterson** [comment]
We can use the `Issue Category` field from Caseflow Intake to flag `Apportionment` and `Contested Claims (other than apportionment)`. So, we have the option of implementing the mocks in the top comment for these two categories only for now, or wait until we have all of them. @lowellrex @allyceh - what do you think?

<img width="715" alt="screen shot 2019-01-24 at 6 07 16 pm" src="https://user-images.githubusercontent.com/27704093/51714426-25a3e700-2003-11e9-9566-625bd31073e5.png">
<img width="734" alt="screen shot 2019-01-24 at 6 06 21 pm" src="https://user-images.githubusercontent.com/27704093/51714427-25a3e700-2003-11e9-92fa-29dcd7a44497.png">

Not sure about what other structured data is available for the other ones, because we are relying on VBMS fields for request issues:
- Attorney fees
- DIC: two claims for DIC received from two or more persons
- Veteran death related e.g. funeral expenses

**Comment by laurjpeterson** [comment]
Cool - updating AC. @lowellrex this is good to go. Likely end of the list of this sprint, into next sprint.

**Comment by laurjpeterson** [comment]
@marvokdolor-gov and I just checked Looker - there is only 1 apportionment request issue right now.

**Comment by allyceh** [comment]
@lowellrex What is the level of effort to implement this same flag for legacy cases, too? I was speaking with @MeredithStewart this morning, and the Hearing Scheduling team could benefit from having this. Just curious!

**Comment by lowellrex** [comment]
I haven't really been following this conversation. @allyceh the flag you're referring to is the "This could be a contested claim" text in the universal case title, correct? Increasing the scope of this ticket to include legacy appeals would likely double the amount of time it will take to do the work, if not increase it even more.

**Comment by laurjpeterson** [comment]
@allyceh @MeredithStewart - We'd also have to pin down the requirements to do this for legacy appeals, finding the fields and values in VACOLS that we'd need to indicate that something is (or might be) a contested claim. 

I know there is the contested claim tab in VACOLS, and there is a beautiful hot pink pop-up in VACOLS if a particular claim is contested, but I don't know specifically what we could look for in VACOLS - we'd likely need to ask Jed in the dsva-vacols repo. If we wanted to alert that something _could_ be a contested claim based on the issue on appeal, we'd need the specific `Program Area`, `Issue`, and `Levels 1-3` values that would trigger that it is a potential contested claim (this is a corollary to the Issue Category field we have in Caseflow). You/we might have some of these requirements pinned down already, but I have a hunch it would take some more investigation/requirements gathering. 

@allyceh - would you like to create another github issue to track legacy appeal contested claims work?
@MeredithStewart - how does this stack up against other priorities? (not pushing any next steps for you or anyone here, just curious)

**Comment by allyceh** [comment]
@laurjpeterson For legacy, I was thinking less along the lines of flagging contested claim info in VACOLS (we know right now that it's not very reliable), and more along the lines of just flagging issues that are on the case. Ex: If apportionment issue in VACOLS, present "flag" in Case Title and About the Appellant section. This could be a scrappy first step to alerting users that something might be a contested claim and that they have to look into it more. It's not ideal, but it feels "quicker" than other solutions. 

Per @lowellrex and from a tech perspective, it sounds like this is not simple and would double the work. Perhaps we table this solution for legacy in favor of a better, less scrappy, more long-term one? We can discuss more during queue-hearings sync on Monday.

**Comment by allyceh** [comment]
Created https://github.com/department-of-veterans-affairs/caseflow/issues/9132 for legacy contested claims. We can have convos about legacy contested claims there.

**Comment by MeredithStewart** [comment]
Priority wise -- The branch will take over scheduling and most of them have never scheduled before. It will be difficult for them to spot when they need to take extra steps -- or have someone else take those steps - to make sure they schedule the contested claimant hearing correctly. I think the legacy quick thing would be a nice quick and dirty thing that could be followed up with actual logic that we implement per the issues.

**Comment by laurjpeterson** [comment]
Still only 1 apportionment request issue, so I think implementing this can be pushed out a little while longer.

**Comment by NateMartinTista** [comment]
CASEFLOW-135
