### ISSUE TITLE
Rollout queue to BVA Dispatch team

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#8661]
## Background

On 1/10, @eric-nava and I met with the BVA Dispatch team to discuss their feedback on the BVA Dispatch pilot and feature requests they had. They want to use a queue and queue functionality rather than work their cases exclusively from the IDT and via email. 

Specifically, they requested: 

**Team View**
- "We’d want the ability to assign cases"
- "Track cases by # of days waiting in someone's queue or at BVA Dispatch"
 - "Want to see how long it’s assigned to someone"
- "Be able to assign to others and myself, especially before we roll this out to more people" 

**Send back to judge/AOD/admin teams functionality** (captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/8693)
- "Needs to send something back to the judge with regards the corrections. Receives lots of these. Judge needs to know what to do, so the notes section needs to be prominent and required."
- "Wants the decision to leave queue right after they send it to a judge so that it's off their plate."

## Proposed BVA Dispatch process (using queues and IDT together)

- User opens their BVA dispatch queue 
- User clicks on a veteran to view their Case Details in Caseflow
- User opens their IDT queue in Microsoft Word
- User clicks on the same veteran in their IDT queue to open their decision letter
- User reviews the decision letter and data in Caseflow, double checking the accuracy of the info and if there are any open mail tasks on the case that need to be resolved
  - Note: If the judge made an error (ex: orders are incorrect), user returns to their queue and sends the case back to the judge with a note about what to fix. 
    - Open question: If BVA Dispatch sends the case back to the judge for correction, would it also disappear from their IDT queue?
- User clicks "finalize dispatch" to trigger outcoding and automatic upload to VBMS. 
- User returns to their IDT/Caseflow queue and sees that the case has disappeared in both places, indicating it's complete. 
- User clicks on a new case and repeats the process

## Next steps

- Get link(s) to queues so BVA Dispatchers can start using
- Train BVA dispatch users
- Validate proposed workflow (using the IDT and queues together) and make sure we haven't overlooked anything.

**Comment by laurjpeterson** [comment]
@allyceh - I think that BVA dispatchers may already have this functionality. One way to find out would be to ask Will or Libby to click the Caseflow logo and see if they navigate to their queue of assigned cases. 

This list of assigned cases likely contains both AMA and legacy.

**Comment by lowellrex** [comment]
BVA dispatchers should have the following options available to them on the case details page:

![image](https://user-images.githubusercontent.com/32683958/51133037-dc34ea00-1801-11e9-82ea-9f7acbe0f987.png)

The "Re-assign to person" only allows us to reassign the task to somebody else on the Dispatch team, so we'll need to add an option to send the case back to the judge if the Dispatch team wants to do that. Ticketed that work as #8693, which we can adjust as we need to.

**Comment by lowellrex** [comment]
Created a ticket (#8694) to give dispathers a team queue.

**Comment by allyceh** [comment]
@laurjpeterson @lowellrex William responded to my email about seeing their queue. He says he can see the Ramp cases, but not the legacy cases assigned to him.

**Comment by laurjpeterson** [comment]
@allyceh - thanks! this means that queue is working as designed for the BVA dispatchers. right now, all teams (other than VLJ support) are only seeing/being assigned RAMP/AMA appeals.

**Comment by laurjpeterson** [comment]
@allyceh - I showed Will the BVA dispatch team queue last week (`/organizations/bva-dispatch`), and sending tasks back to judges is captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/8693. 

Do you think we can close this issue?

**Comment by allyceh** [comment]
Sounds good! Closing.
