### ISSUE TITLE
Set the receipt date of DTA EPs to the decision date of the previous review

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8677]
We are currently setting the receipt date of DTA EPs to the time the EP is created. This is incorrect, we should be setting it to the decision date of the prior decision review. (per AMO)

**Comment by kencheeto** [comment]
Likely use approx decision date of prior decision review

**Comment by leikkisa** [comment]
I am assuming that the approx decision date of any of the issues on the DTA Supplemental Claim is representative of the decision date of the review.  The end product last action date gets pulled once the end product is gets a status of CLR so that indicates that all of the issues are finished.

**Comment by shanear** [comment]
```
=> #<ActiveRecord::Associations::CollectionProxy [#<DecisionIssue id: 110, disposition: "Denied", description: "Denied: Service connection for back is granted wit...", promulgation_date: nil, profile_date: nil, participant_id: "600247069", rating_issue_reference_id: nil, decision_text: nil, decision_review_type: "HigherLevelReview", decision_review_id: 1056, benefit_type: "compensation", end_product_last_action_date: "2019-02-01", diagnostic_code: nil>]>
irb(main):032:0> HigherLevelReview.where(veteran_file_number: "700035212").first.request_issues[1].decision_issues
=> #<ActiveRecord::Associations::CollectionProxy [#<DecisionIssue id: 117, disposition: "Granted", description: "Evaluation of Spine, which is currently 30 percent...", promulgation_date: "2019-02-01 19:40:47", profile_date: "2019-02-01 19:32:24", participant_id: "600247069", rating_issue_reference_id: "123803", decision_text: "Evaluation of Spine, which is currently 30 percent...", decision_review_type: "HigherLevelReview", decision_review_id: 1056, benefit_type: "compensation", end_product_last_action_date: "2019-02-01", diagnostic_code: nil>]>
```

Looks like `end_product_last_action_date` seems to be working correctly. `promulgation_date` and `profile_date` are working for the ones that are connected to rating issues.

Still need to test that `promulgation_date` and `profile_date` get set if the EP is connected to a rating even if the contention isn't connected to a rating issue.
