### ISSUE TITLE
Daily Docket | AMA AOD functionality

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8682]
## User Stories
As a Judge, I need the ability to grant or deny AOD status for a Veteran based on evidence presented to me at a hearing. 

As a Judge, I need to make sure my ruling is recorded properly with a reason, so that this can be referenced in the future and tracked. 

As a Judge, I need to make sure my ruling is applied immediately so that it impacts the way the case is prioritized. 

## Mocks
https://va-gov.invisionapp.com/share/Y3QWT5ARMNJ

## Acceptance Criteria
- [x] Verify this functionality exists for AMA hearings only.
- [x] Verify users can select either Grant or Deny from the AOD drop down. Remove the filed option.
- [x] Verify a dropdown option is available for AOD reason. This dropdown should not be editable unless AOD is selected as Grant or Deny.
- [x] Verify when the user selects an AOD option, the AOD reason drop down is accessible. 
- [x] Verify any changes must be saved via the save button.

**Comment by ShellySmithDSVA** [comment]
Moving the original conversation link here:
https://dsva.slack.com/archives/C42P25D6H/p1547479327002000
