### ISSUE TITLE
Backfill RAMP appeal issue editing data

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8689]
Attorneys and judges could not add/edit decision issues during the RAMP appeals pilot (started Oct. 1) because attorney magic functionality was not yet ready. As a workaround, attorneys emailed a BVA representative when issues needed editing, and Caseflow kept track of these cases in a spreadsheet. These cases moved forward in the process and were dispatched from the Board because the BVA decision document was the source of truth for issues and dispositions.  

Now that we have the data model for decision issues implemented, we can go back and edit these cases so issues in Caseflow reflect the issues that the attorney and judge decided in the BVA decision. 

## AC
- Request and decision issues have been updated per spreadsheet

**Comment by laurjpeterson** [comment]
Related: https://github.com/department-of-veterans-affairs/caseflow/issues/8971

**Comment by aroltsch** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/8971#issuecomment-470308577
