### ISSUE TITLE
Manager Dashboard | Update copy of page header and subtext

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#869]
As a Dispatch Manager, I want the page header and it's subtext changed on the `Manager Dashboard` page so that they are in terms I understand and more effectively express appropriately important information.

# Acceptance Criteria
1. Verify that the `Manager Dashboard` page header and subtext has changed to the following:  (Refer to Mockup)
     **_Header_**

     > ARC Workflow

     **_Subtext_**

     > [TotalCasesCompleted] out of [TotalCaseToday] cases completed today

1. Verify that when the [TotalCasesCompleted] count changes, the header's subtext reflects this change.

## Mockups
**_View - Manager Dashboard - New Header and Subtext_**
![image](https://cloud.githubusercontent.com/assets/23063044/22982273/a9ef83ea-f36c-11e6-85b4-ce0babd5219d.png)

# Related Stories
Manager Dashboard | Update copy of page header and subtext #869
Manager Dashboard | Set number of Caseworkers for today #859
Manager Dashboard | Current | Change table information and section header to "Work Assignments" #867
Manager Dashboard | Hide "Work History" section #860

**Comment by nikitarockz** [comment]
Original
As a manager, I want the headers and copy on the dashboard page to look good and be worded in terms I understand

- Verify that the header 'ARC Workflow' displays at the top of the page. 
- Verify that '[ number] out of [number] cases completed today' displays to the right of 'ARC Workflow'.
- Verify that Enter the number of people working today displays below 'ARC Workflow'.
- Verify that the box is labeled number of people.
- Verify that the button is labeled 'Update'
- Verify that the header 'Work Assignments' displays above the table.
- Verify that the table displays the following columns: Employee Name, Cases Assigned, Cases Completed, Cases Remaining.
- Verify that when a worker completes their first establishment task their name appears in the table along with the number of cases they have been assigned and cases they have completed. and the number of cases they have remaining
- Verify that the total of each column displays in the Employee Total row.
- Verify that the employee total row is displayed at the bottom of the table in bold type.

<img width="590" alt="screen shot 2017-02-12 at 7 41 59 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867758/d88ee244-f15b-11e6-8b44-41547e1a3553.png">

**Comment by lakohl** [comment]
@mdbenjam sorry to move the pieces around while you are working on things:(  I have a slight copy update to header on this issue:

As a Dispatch Manager, I want the page header and it's subtext changed on the `Manager Dashboard` page so that they are in terms I understand and more effectively express appropriately important information.

@nikitarockz for awareness

# Acceptance Criteria
1. Verify that the `Manager Dashboard` page header and subtext has changed to the following:  (Refer to Mockup)
     **_Header_**

     > ARC Work Assignments

     **_Subtext_**

     > [TotalCasesCompleted] out of [TotalCaseToday] cases completed today

1. Verify that when the [TotalCasesCompleted] count changes, the header's subtext reflects this change.
<img width="821" alt="screen shot 2017-02-16 at 8 51 58 pm" src="https://cloud.githubusercontent.com/assets/4975959/23049411/c96a9368-f489-11e6-8967-4f0c04671c21.png">

**Comment by kierachell** [comment]
We don't exactly have workers to assign the tasks to:
thus, unable to validate in `uat`.
![noworkers](https://cloud.githubusercontent.com/assets/18075411/23187112/a7d516ac-f857-11e6-833d-6580284607af.png)

**Comment by mdbenjam** [comment]
@kierachell I think AC 2 is just referring to the '2 out of 5 cases completed today.' Can you complete one more task and see if goes to 3 out of 5?

**Comment by kierachell** [comment]
I am not seeing the following:
```
Verify that the table displays the following columns: Employee Name, Cases Assigned, Cases Completed, Cases Remaining.
Verify that when a worker completes their first establishment task their name appears in the table along with the number of cases they have been assigned and cases they have completed. and the number of cases they have remaining
Verify that the total of each column displays in the Employee Total row.
Verify that the employee total row is displayed at the bottom of the table in bold type.
```
as per @nikitarockz 
or have the AC changed?
