### ISSUE TITLE
AMA Content on VA.gov

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8690]
# Call with VA.gov 01/11/2019

## Three touch points for content review (Allyce, Beth, Jennifer):

1. Week of  Jan. 14th: Allyce to sync with Beth to review VA style guide
2. Jan. 21st - Initial review
3. Feb. 1st: Final review

### Crosslinking between new/legacy process
- [x] Action item: Appeals team will take the 1st pass on adding content to direct users to the alternative process based on date of claim decision
### Duplicate “Get Help Filing” pages for new/legacy content
**Decision:** Both pages will exist. H1s and content will be slightly modified.
### Entry Points for Decision Reviews
- [x] Action item: Mikki will create a mockup of what this looks like on our benefit hub pages. We’ll regroup when it’s ready for review.
### Terminology Collision
- [x] Action item: Internal discussion between Website and Unicorns team scheduled for 1/14.
### Design Recommendations for AMA Pages
- [x] Action item: Website team has reviewed the initial mockup. The team is working on a prototype of recommended updates based on our current design standards. We’ll regroup with Appeals once this is ready for review.
**Update**: See [this ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16220) to follow along.
### 508, Analytics, QA Needs for this work
-  [x] Action item: No hard requirements from Appeals, however, Winnie will check in with the Platform team to discuss.
**Update**: See [this ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16243) to follow along.

## Reference
VA.gov [Appeal Status EPIC](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15768).

**Comment by annienguyenUSDS** [comment]
- [ ] Website team built out [1 page prototype ](https://vagov-content-pr-229.herokuapp.com/decision-reviews/), and we met to discuss feedback on Thursday, 1/31.
- [ ] Allyce met with Beth to go over any outstanding content questions on Friday, 2/1. 
- [ ] Chris sent out latest content word documents for review to stakeholders (Board, AMO) on Monday, 2/4. 
- [ ] Waiting for stakeholder feedback by COB Wednesday, 2/6 (Hoping by end of this week, 2/8 latest)

**Comment by annienguyenUSDS** [comment]
Steve emailed stakeholders asking for addresses (https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/AMA_training/Caseflow%20Administrators.md). TBD. If they don't get addresses/fax number back, we include each benefit type: “Please refer to your decision for instructions on how to submit the form.”
