### ISSUE TITLE
Allow BVA dispatch to return cases to Judges

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8693]
Board dispatch regularly needs to send cases back to judges for corrections. This ticket exists to present them with an option--[similar to the one members of the Quality Review team have](https://github.com/department-of-veterans-affairs/caseflow/issues/7462)--to send cases back to the signing judge.

## Acceptance criteria
* [x] Board dispatchers can select an option in the task actions dropdown on the case details page to send a case back to the signing judge. This option is called "Return to judge"
* [x] Board dispatchers can write a note with instructions about the task, so judges know what they need to do with it
* [x] When this task arrives in the judges queue, the task is called "Revise decision (BVA Dispatch)"

**Comment by laurjpeterson** [comment]
With this github issue, judges will be able to distinguish these tasks from others.
https://github.com/department-of-veterans-affairs/caseflow/issues/8652

**Comment by laurjpeterson** [comment]
@allyceh - based on your work with BVA dispatchers, do you have a suggestion for what this task is called? I have "Correct decision data" but maybe it should be more broad?

**Comment by allyceh** [comment]
Assuming this task would be judge facing // appear in the judges queue, how about "Revise decision (BVA Dispatch)"? In our refreshed task naming ticket https://github.com/department-of-veterans-affairs/caseflow/issues/7508 , I proposed "Revise decision (quality review)" for when member of the QR team need judges to make a change. This task name would follow the same schema. 

For the action available to BVA Dispatch, I'm thinking "Return to judge" would be clear to them. Or, will BVA Dispatch use the "Assign to" option and include notes to the judge?

**Comment by laurjpeterson** [comment]
I love it!

**Comment by lomky** [comment]
Should this task then be able to have a corresponding Attorney subtask, or do Judges handle this directly?

**Comment by lowellrex** [comment]
MEDIUM. Make sure we have adequate test coverage here since this is a new workflow in Queue for BVA Dispatchers. Will need to create a new task class (something like `JudgeDispatchReturnTask`) a la `JudgeQualityReviewTask`.

**Comment by lowellrex** [comment]
> Should this task then be able to have a corresponding Attorney subtask, or do Judges handle this directly?

Yup! I think that makes sense!

**Comment by lomky** [comment]
A couple questions @laurjpeterson. I provided `Quality Review`'s current behavior for reference.

 - Should these `Dispatch Return` tasks end up in the judge's Review pane or their Assign pane?
   -  `Quality Review` tasks currently end up in the "Review" pane, but not the assign.
   - You can still assign them to an attorney once you go into the case.
 - If the judge creates an attorney task, what type should that attorney task be?
   - Attorney tasks created off of `Quality Review` tasks become "`Original`"

**Comment by laurjpeterson** [comment]
* Dispatch Return tasks should end up in the Review pane. Let's have them display "Revise decision (BVA Dispatch)" to the user. (The only tasks that should be in the Assign pane are `JudgeAssignTask`s
* I think the judge should be able to assign `AttorneyRewriteTask`s to attorneys. 

I haven't heard of the `Original` task type. What is that one?

**Comment by lomky** [comment]
Discussed Attorney Tasking with @laurjpeterson; we're going with a new distinct Attorney type, mirroring the new Judge type.

**Comment by lomky** [comment]
@laurjpeterson 

When the judge is finished with this task, do they need to go back through AMA checkout, or just mark the task complete?

**Comment by laurjpeterson** [comment]
Yep, it should go through the same checkout flow! Thankya

**Comment by lomky** [comment]
Main PR tests passed and m merged! A bit of follow up for more tests in #10886, and then this issue is complete.
