### ISSUE TITLE
Intake | Add limit for contention text

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8695]
There is a BGS enforced character limit for contention text of 255 characters. We need to build a way that shortens contention text of the contentions that we create if they are too long.

**Comment by pkarman** [comment]
Do we rely on this text for matching caseflow records at all?

One pattern I have seen before is to truncate text to something like 239 bytes, and save the last 16 bytes for a checksum (first part of a md5 or sha digest) of the entire untruncated text, so that matching can still work later.

**Comment by shanear** [comment]
![ss6](https://user-images.githubusercontent.com/1596259/51627237-55b19400-1ef6-11e9-8dc4-22b4e43d1d26.PNG)
boom shakalaka
