### ISSUE TITLE
Don't skip EP code 034

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8708]
We're unintentionally skipping EP code 034 for higher level reviews; looks like a typo in the list of EP codes to use.

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/higher_level_review.rb#L6

**Comment by shanear** [comment]
![034 works](https://user-images.githubusercontent.com/1596259/51355895-603eda00-1a6d-11e9-8e94-4c474e3ec2d5.PNG)
hello old friend. It's been a while
