### ISSUE TITLE
Intake | system error thrown when NilRatingProfileListError

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8710]
Currently we're seeing a "Something went wrong" when going from the review page to the add issues page of an intake for any decision review if the `NilRatingProfileListError` is thrown.

Even if there are no ratings, we should still allow a user to intake a decision review for a veteran.

Alright, so there are 4 scenarios that we need tested/covered:

### 1. has both a backfilled/converted and promulgated rating
VBMS has said that this is difficult to test because it's difficult to make a backfilled/converted rating in UAT. We are trusting them that this DOES send back ratings.

### 2. has only a backfilled/converted rating
This throws an error, but we should allow the intake to continue

### 3. has both a locked and a promulgated rating
This should return ratings as normal, now that BGS has fixed their issue. We still need to test this in UAT.

### 4.  has only a locked rating
Like with backfilled ratings, we should allow the intake to continue, just with no ratings

## Technical Notes
A UAT veteran to test this on is: 700036051

**Comment by jiahuang** [comment]
blocked on getting some more example data from bgs

**Comment by nicholasholtz** [comment]
@jiahuang are we still waiting on this example data? Who did we ask for this from?

**Comment by leikkisa** [comment]
Sally has asked for example response, haven't received a response yet, going to escalate and include Nicholas and Jia

**Comment by nicholasholtz** [comment]
Sally, could you forward me what you asked for?

**Comment by jiahuang** [comment]
I followed up on the email again. I'm trying to get sample data for a veteran that has both a backfilled rating as well as promulgated ratings.

**Comment by nicholasholtz** [comment]
Linda Ciston responded on 1/31, indicating a response would be forthcoming today or tomororow

**Comment by nicholasholtz** [comment]
Linda Ciston provided response on 2/4

**Comment by jiahuang** [comment]
Got data for #1 (has both a backfilled/converted and promulgated rating), it returns ratings. Waiting on data for #3 (has both a locked and a promulgated rating), but if it behaves the same way as #1, we will handle it correctly.

**Comment by nicholasholtz** [comment]
Colin provided sample data on 2/8

**Comment by leikkisa** [comment]
Looked at the rating that Colin added on the file number, and it's working as expected, we're getting the promulgated rating, and not the backfilled (not even with any reject reason). 

Jia noticed another "reject_reason" while digging into this - "Rating Not Promulgated on Last award".  We thought maybe that was from a backfilled rating mixed with promulgated ratings, but this confirms that it's something else.

Right now we're returning an empty array when we get that, going to ask Shane what we should be returning, I'm guessing just the promulgated ratings.

**Comment by leikkisa** [comment]
False alarm! This is working properly for "ratings" which we're using now instead of timely_ratings.

**Comment by steve-gov** [comment]
No error thrown: 

<img width="587" alt="screen shot 2019-02-15 at 2 07 12 pm" src="https://user-images.githubusercontent.com/25468689/52887008-02b0b280-312b-11e9-806a-8ff8014c7229.png">
