### ISSUE TITLE
Cache BGS end products request

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#872]
#### Part 1
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/appeal.rb#L257-L269

Within 1 request to Caseflow, we are making the same request twice to BGS. We should cache the request so it is only made once

#### Part 2
We should add a `MetricService.timer` wrapper to these requests to BGS. This will help improve prod debugging if/when issues come up

**Comment by kierachell** [comment]
**PASSED**
Tested on `uat` found only one call to:
`[certification.cf.uat.ds.va.gov] [172.30.71.242] [2017-02-27 13:14:30 -0500] [CASEFLOW1 ] get end products for vbms id: 516517680: 0.020000 0.000000 0.020000 ( 0.881628)`
