### ISSUE TITLE
Investigate distinguishing DTA errors/post-DTA EPs

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8722]
Linking old EP with new one. Is this something that exists in VBMS and/or Caseflow.
We're hoping it already exists in Caseflow. 

- [ ] MC to chat with Sally on this by 01/16/2019.

### Acceptance Criteria
- Question is answered and we know how to get DTA data.

**Comment by cmgiven** [comment]
I think we're set here.
