### ISSUE TITLE
Intake Confirmation | Improve messaging when no EP is created

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8724]
Even if all issues are ineligible and no EPs are created Caseflow:

- Says "If you need to edit this, go to VBMS claim details and click the "Edit in Caseflow" button. Which is incorrect, because there is no VBMS claim.
- Incorrectly shows a checkbox for "Informal Conference Tracked Item"

We should remove both of these items from the confirmation page in this case.

![image](https://user-images.githubusercontent.com/1596259/51197163-9af61600-18a5-11e9-93f5-bb3a4f810f56.png)

**Comment by steve-gov** [comment]
Validated: 

![screencapture](https://user-images.githubusercontent.com/25468689/51419849-86827980-1b42-11e9-9591-2b11f9d184db.gif)
