### ISSUE TITLE
Decide how to feature flag Appeal Status V3 work

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8725]
### Plan
MC to explore what is needed. This will likely be broken into sub-tickets.
- [ ] How do Caseflow feature flags work?
- [ ] Do we need to know how VA.gov feature flags work as well?
    - [ ] Either way, how would this be coordinated between the two systems, in order to turn everything on in the appropriate order?

### Notes
Caseflow has a feature toggle in UAT. So we could use that potentially.
VA.gov has feature toggles based on the environment.

### Acceptance Criteria
- We know how to turn on and off Appeal Status V3 code in production.

**Comment by mc-usds** [comment]
The feature flag will be FeatureToggle.enabled?(:api_appeal_status_v3)
Will most likely need to use at the controller level to turn on returning the new reviews in addition to legacy appeals statuses.

**Comment by cmgiven** [comment]
Closing. `api_appeal_status_v3` it is.
