### ISSUE TITLE
Add in new model to Appeal Status API for Higher Level Reviews

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8726]
This work involves creating and serializing the model.
**Goal:** completed by 01/22/2019, stretch goal 01/18/2019.

### References
- [Swagger Docs](https://app.swaggerhub.com/apis/dsva-appeals/appeals-status/2.0.0#/default/appeals)

### Acceptance Criteria
- Model is created.
- Unit tests are created.

**Comment by cmgiven** [comment]
All Supplemental Claims, both open and closed, should return a result when the Appeals Status API is queried for the Veteran's SSN. The JSON should include the following:

```
{
  "type": "higherLevelReview",
  "id": "HLR100",
  "attributes": {}
}
```

* The `type` should always be "higherLevelReview".
* The `id` should be the letters "HLR" concatenated with the higher_level_review.id
* `attributes` to be filled in by other tickets.

This functionality should be behind a feature flag.

**Comment by cmgiven** [comment]
This is done.
