### ISSUE TITLE
EP Creation | Page to add VBMS note when creating Full Grant EPs

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#873]
As a Caseworker, when an EP is created for a Full Grant with a Special Issue (currently handled in Caseflow) I would like to have a subsequent page displayed that prompts me to add a VBMS note  so that the Appeals team that will be receiving this message is warned of this new EP. This new page will appear between the EP Creation Form and the Congratulations Page.

## Acceptance Criteria
1. Verify for a full grant with a special issue where an EP can be created, that when the user clicks the **_Establish End Product_** button (and after the EP is created in VBMS), the `VBMS Note` page is displayed.
1. Verify the modal has the following Title and Subtext:
     **_Title_**
     > Add a note in VBMS

     **_Subtext_**
     > To better route this claim, please open VBMS and attach the following note to the EP you just created.

1. Verify that there is a field labeled "VBMS Note".  
1. Verify that the field "VBMS Note" contains the following pre-filled text:
     >The BVA Full Grant decision date [Decision_Date format: mm/dd/yyyy] for [Veteran FirstName] [Veteran LastName], ID # [VeteranId], was sent to the ARC but cannot be processed here, as it contains [Special Issue Category] in your jurisdiction.  Please proceed with control and implement this grant.
>
1. Verify that all Special Issues selected are listed in the VBMS Note for [Special Issue Category] separated by ",".  
1. Verify that there is a checkbox labeled "I confirm that I have created a VBMS note to help route this claim".
1. Verify that there is a button labeled _**Finish Routing Claim**_.
1. Verify that the _**Finish Routing Claim**_ button defaults as inactive.
1. Verify that the checkbox next to 'I confirm that I have created a VBMS note to help route this claim' is in active.
1. Verify that when the field _"I confirm that I have created a VBMS note to help route this claim._" has been checked, the **_Finish Routing Claim_** button becomes active (blue).
1. Verify that after clicking on the **_Finish Routing Claim_** button, the `EP Confirmation` page is displayed with the following steps checked off (refer to mockup):
     - Reviewed Decision
     - Established EP
     - Manually Added VBMS Note

## Mockups
<img width="553" alt="screen shot 2017-02-13 at 9 00 53 am" src="https://cloud.githubusercontent.com/assets/4975959/22886236/f2640928-f1ca-11e6-8090-7f403d17bd43.png">

<img width="538" alt="screen shot 2017-02-13 at 9 00 59 am" src="https://cloud.githubusercontent.com/assets/4975959/22886248/fcdd3ea6-f1ca-11e6-8850-46b07c1ffae6.png">

**_View - EP Confirmation page_** 
<img width="662" alt="screen shot 2017-02-09 at 6 17 47 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807272/2055f672-eef4-11e6-9c31-6ad5fbb8d560.png">

# Notes
- Don't worry about the progress bar in the mock.

**Comment by lakohl** [comment]
LK to provide mock

**Comment by mdbenjam** [comment]
@lakohl According to AC 5 there is a close link, but I don't see it in the mock. What does the close link do? And where is it supposed to go?

**Comment by mdbenjam** [comment]
And for AC 7, it says red. I assume that means the button should be red?

**Comment by lakohl** [comment]
Good catches @mdbenjam My apologies. This used to be a modal and now it's a page. Thus the Close link is no longer needed. Also the button should be blue in this case. I will update the AC.

**Comment by kierachell** [comment]
This currently shows up as the first step in _Establish Next Claim_ procedure, is that expected?
![vbmsnote](https://cloud.githubusercontent.com/assets/18075411/23065196/4f006bf8-f4e2-11e6-8afd-15031c53e1d2.png)

Also, you know I am going to do this; you know it:
![vbmsnotecharlim](https://cloud.githubusercontent.com/assets/18075411/23065203/5975dc30-f4e2-11e6-9b61-aa38a996061e.png)
Character limit?

**Comment by lakohl** [comment]
@kierachell @mdbenjam this step should happen after the Create EP form page and before the Congratulations page.
As for character limit, we should check what the character limit is for the Notes field in VBMS as that is where we will eventually auto-populate this note.

**Comment by kierachell** [comment]
**PASSED**

![mustardgassuccess](https://cloud.githubusercontent.com/assets/18075411/23085325/1d10727a-f535-11e6-8ea9-0b7ed0234c78.png)
![mustardgasenote](https://cloud.githubusercontent.com/assets/18075411/23085326/1d110a96-f535-11e6-95c9-4841ee38f94e.png)

**Comment by kierachell** [comment]
As I understand there is no integration for this note yet
