### ISSUE TITLE
Display task column in attorney queue table view

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8731]
Soon, we are allowing judges to send rewrite tasks back to attorneys (https://github.com/department-of-veterans-affairs/caseflow/issues/8233), we want to help them distinguish these tasks from decision drafting tasks. 

Related, for judges: https://github.com/department-of-veterans-affairs/caseflow/issues/8652

**Comment by lowellrex** [comment]
SMALL. See a similar change we made in #8944 for reference.
