### ISSUE TITLE
Unprocessable Entity after SUBMIT_REVIEW_FAIL

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8739]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3252

**Comment by jiahuang** [comment]
Looked through the kibana logs. I can see 1 request fail and then immediately the next request completing in 30s, with the difference being this in their params:

Failed request:
Parameters: {"option_selected"=>"appeal", "appeal_docket"=>"evidence_submission", "id"=>"122971", "intake"=>{}}

Successful request:
Parameters: {"option_selected"=>"appeal", "receipt_date"=>"2018-11-20", "appeal_docket"=>"evidence_submission", "id"=>"122971", "intake"=>{}}

In [`rampRefiling.js`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intake/actions/rampRefiling.js#L54-L58) we're trying to set receipt_date. My guess is that we're not setting it properly somehow..

**Comment by jiahuang** [comment]
I was able to reproduce us sending a payload without the required fields. The "continue to next step" should be grayed out until the receipt date filled out & checkbox is selected

![image](https://user-images.githubusercontent.com/577629/51285621-6917a900-19a4-11e9-8fb1-d36106cdb7f1.png)

**Comment by jiahuang** [comment]
Sentry is reporting 4xxs that aren't actual errors.

In the case of intake `SUBMIT_REVIEW_FAIL`, we handle the error in the frontend and then notify the user that the form has to be filled out. Failed logs are usually followed by a successful retry 30s later in kibana.

There are other cases of sentry logging 4xxs that may not be real errors.

On reader, seems like some metrics don't properly post https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3252/events/221015/
```
> %c Action with type "SET_OPENED_ACCORDION_SECTIONS" took 1.00 milliseconds. background: #bada55; color: #222
> POST /metrics/v1/histogram 422
```

Search on reader returns 422? Maybe when a search can't return data?
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3252/events/220356/
```
> POST /reader/appeal/3013540/claims_folder_searches 422
```

**Comment by leikkisa** [comment]
I'm closing this one - Jia submitted a fix for the specific case of that brought up this ticket. I think the issue then became about not reporting these to Sentry.  

I couldn't find this by searching in Sentry for SUBMIT_REVIEW_FAIL or scanning through the last couple of days of intake-alerts, and the link above isn't to a specific event so it goes to something else now.  If it comes up again, then we can add a ticket with a link to the actual Sentry event, that'll be easier to work with.
