### ISSUE TITLE
Intake | Copy change: Add instructions on whom to email if non-Veteran claimant is not in VBMS

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#8746]
Currently when selecting a claimant other than the Veteran in both Board reviews and HLR/SCs, the following options are present:

<img width="832" alt="screen shot 2019-01-15 at 3 51 09 pm" src="https://user-images.githubusercontent.com/25468689/51217591-9c433500-18dd-11e9-8faa-22447367573f.png">

Replace "If you do not see the claimant in the options below, add them in VBMS, then refresh this page." with "If you do not see the claimant in the options below, and you have access, please add the claimant to the Corporate Database to continue processing this intake. If you do not have access, please [email]* for assistance."

In the case that no options are present, the copy should read:

"This Veteran currently has no known relationships. If you have access, please add the claimant to the Corporate Database to continue processing this intake. If you do not have access, please [email]* for assistance."

* This builds off of off of #7908, and using the email address contained therein.

**Comment by leikkisa** [comment]
There is another ticket to get a more generic email: https://github.com/department-of-veterans-affairs/caseflow/issues/8316

**Comment by shanear** [comment]
![bug4 1](https://user-images.githubusercontent.com/1596259/51627314-97dad580-1ef6-11e9-9441-c6ba9a925f40.PNG)
not sure if this is an IE bug, but "email" looks a little off. Not sure why?

**Comment by leikkisa** [comment]
Lol, that's probably a spacing bug. Will fix!

**Comment by shanear** [comment]
<img width="1139" alt="screenshot 2019-01-23 16 55 01" src="https://user-images.githubusercontent.com/1596259/51646957-a8f40880-1f2f-11e9-861c-a230a2b51591.png">
looking good 💅
