### ISSUE TITLE
Allow judges to send admin actions to VLJ support for Legacy appeals

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8757]
#8608 enabled judges to send admin actions directly to VLJ support for AMA appeals. This ticket exists to allow judges to send admin actions to VLJ support for Legacy appeals.

## Acceptance criteria
* [ ] Judges have the option to `Add admin action` from the Case details page for Legacy appeals, currently active tasks component, Actions dropdown
* [ ] When judges click `Add admin action` for a Legacy appeal, they navigate to the add admin action page (same behavior as attorneys)
* [ ] Location code updates in VACOLS as expected.

**Comment by laurjpeterson** [comment]
@lowellrex - i think we can actually close this. i sat with a judge today (Thomas O'Shay) and he had the add admin action option!

**Comment by lowellrex** [comment]
Whoops! You're right! Good call!
