### ISSUE TITLE
Update task to_hash, reduce API calls

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#876]
Follow up to https://github.com/department-of-veterans-affairs/caseflow/pull/852/files

A few pages now still use task.to_hash which makes 2 calls to BGS. 

We should make the `to_simple_hash` the norm, and use the extended `to_hash` only on the task show page where we need the extra API calls.

**Comment by shanear** [comment]
this is related to #872

**Comment by kierachell** [comment]
Note: this required a `hotfix` for preprod testing.

**Comment by shanear** [comment]
@sharonwarner the issue is still present here:

https://github.com/department-of-veterans-affairs/caseflow/blob/34ab99ff896dd2313b4973b7ea9d1e2b5796a269/app/controllers/tasks_controller.rb#L19

is this being solved in a caching issue?

**Comment by joofsh** [comment]
Just to comment on this, this shouldn't be an issue anymore. `to_hash` was updated to be the version that does _not_ make any API calls https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L223-L231

**Comment by kierachell** [comment]
We'll see.

I finally got access to console/logs.

**Comment by kierachell** [comment]
**PASSED**
Refreshed work history, see only one call at a time.
