### ISSUE TITLE
Fix result of Cancellation page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#877]
Change language on what was formerly the EP Cancellation modal and language and styling on the page that comes after the cancel modal.

**_Currently:_**
<img width="567" alt="screen shot 2017-02-09 at 7 18 00 pm" src="https://cloud.githubusercontent.com/assets/4975959/22808899/9dbfd9f4-eefc-11e6-8732-9b6d9cf78803.png">

^^We need to adjust the copy so that it skirts the words 'cancel' and 'EP Establishment', so the user does not think that they are cancelling the EP, but rather is stopping the process of creating  a new EP... (Also they might select the Cancel option from a Route Claim page where they are not creating and EP.)

**_Change to:_**
<img width="429" alt="screen shot 2017-02-12 at 7 23 59 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867579/f2c7424e-f158-11e6-8858-ca0d6ccf1f89.png">

<img width="468" alt="screen shot 2017-02-12 at 7 24 06 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867580/f89a347e-f158-11e6-96ad-5225c931f60b.png">

Also:
Fix result of Cancellation page

After the user clicks the Stop Routing Claim button in the modal above, they are taken to the following page (see below). We need to update the copy so that it is consistent with the modal.
Also, verify that text styling is consistent with Caseflow StyleGuide.

**_Currently:_**
<img width="984" alt="screen shot 2017-02-09 at 3 57 16 pm" src="https://cloud.githubusercontent.com/assets/4975959/22808204/b7f1ad06-eef8-11e6-860f-9cd924c38f7b.png">

**_Change to:_**
<img width="691" alt="screen shot 2017-02-12 at 7 24 25 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867576/e4ef9ec8-f158-11e6-8e38-1014bc5917de.png">

**Comment by lakohl** [comment]
@abbyraskin @avrildavid @wturne would love your eyes and suggestion on the copy above.

**Comment by avrildavid** [comment]
@lakohl - a few suggestions below. Thanks for looping us in:

- Stop/End/Discontinue EP Creation Process
- Stop/End/Discontinue EP Establishment

"If you choose to discontinue the EP creation process, your work will not be saved and an EP will not be established for this claim. 

Please tell us why you would like to stop/end/discontinue this process. 

Explanation (removed "cancel" - "explanation" on its own should be self-explanatory):

**Comment by abbyraskin** [comment]
I think we should avoid the word "aborting." How about "halting"?

**Comment by lakohl** [comment]
@nikitarockz I adjusted the copy in the mocks at the top to better describe an action taken from either the Decision Review Page or the EP Creation/Route Claim page and to address scenarios when an EP may not be in the process of being created.

**Comment by kierachell** [comment]
![kavidecree](https://cloud.githubusercontent.com/assets/18075411/23051054/1c9302aa-f494-11e6-9c9c-41c08224398a.png)
# AC is not compliant!
need update from @lakohl 
![cancelclaim1](https://cloud.githubusercontent.com/assets/18075411/23051074/4ddbbef6-f494-11e6-9ecb-8c5478e220e3.png)
![cancelclaim2](https://cloud.githubusercontent.com/assets/18075411/23051086/5e9b2182-f494-11e6-99ef-c2646f7de3d0.png)

**Comment by kierachell** [comment]
![cancelclaim3](https://cloud.githubusercontent.com/assets/18075411/23051144/c37969d8-f494-11e6-987e-53443eae9f42.png)
Last page is correct by AC.

**Comment by lakohl** [comment]
@kierachell Good point about the words, probably can take out halting in a later version!

**Comment by kierachell** [comment]
**PASSED**
![epcancel](https://cloud.githubusercontent.com/assets/18075411/23085420/c1c2145e-f535-11e6-88a8-a8a24be3a801.png)
