### ISSUE TITLE
Dispatch should better handle VBMS Exception: `VBMS does not currently support claim establishment of claimants with a fiduciary. Please establish this claim in an appropriate source system.`

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#8781]
We recently are seeing an uptick in VBMS exceptions with `VBMS does not currently support claim establishment of claimants with a fiduciary. Please establish this claim in an appropriate source system.`

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3274/

We should catch these exceptions and cancel the dispatch task with a message. We can then create a Looker report to better understand these, and send ARC/VBMS a list of these tasks.

**Comment by araposo-tistatech** [comment]
We haven't seen this error in 8 months, closing as there is no need for a fix at this time.
