### ISSUE TITLE
Disposition Change Logic

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#8782]
## User Stories
As a Hearings Schedule user, I need to change hearing dispositions after an initial disposition is marked to correct mistakes or re-schedule hearings due to additional communications I receive from the Veteran. 

As a Hearings Schedule user, I need to make sure all the tasks associated with the old disposition are closed so that I can work the case properly. 

### LEGACY

**Cancelled**
- [ ] Verify that legacy cases move from VACOLS location 38 (Awaiting Video Hearing) and VACOLS Location 36 (Awaiting CO Hearing) to VACOLS Location 81 (Case Storage). If co-located VSO or DAV, then Legacy cases move to VACOLS location 55 (Veteran Service Organization).

**Postponed**
- [ ] Verify that legacy cases move from VACOLS location 38 (Awaiting Video Hearing) and VACOLS Location 36 (Awaiting CO Hearing) to VACOLS location 57 (Schedule Veteran) for postponement options: 1) "Schedule Immediately" and 2) "Send to Scheduled Veterans list."
- [ ] Verify that legacy cases move from VACOLS location 38 (Awaiting Video Hearing) and VACOLS Location 36 (Awaiting CO Hearing) to VACOLS location 34 (Hearing Abeyance) for postponement option, "Apply Admin Action."

**No Show**
- [ ] Verify that legacy cases don't move from VACOLS location 38 (Awaiting Video Hearing) and VACOLS Location 36 (Awaiting CO Hearing) when a no-show task has been added. 
- [ ] Verify that when no-show task is marked as "mark as complete: released case for review" then legacy cases move from VACOLS location 38 (Awaiting Video Hearing) and VACOLS Location 36 (Awaiting CO Hearing) to VACOLS Location 81 (Case Storage). If co-located VSO or DAV, then Legacy cases move to VACOLS location 55 (Veteran Service Organization).
- [ ] Verify that when no-show task is marked as "mark as complete and postpone," Then the legacy cases move from VACOLS location 38/36 to VACOLS location 57.  

**Held**
- [ ] Verify that legacy cases move from VACOLS location 38 (Awaiting Video Hearing) and VACOLS Location 36 (Awaiting CO Hearing) to VACOLS Location 33 (Transcription). 

**Transcription Pre-MVP**
- [ ] Verify that legacy cases move from VACOLS location 33 (Transcription) to 81 (Case Storage) if "marked as complete" is selected. If co-located VSO is DAV, then case moves to 55 (VSO). 

- [ ] Verify that legacy cases move from VACOLS location 33 (Transcription) to 57 (Hearing Branch) If "Marked as complete: Reschedule hearing" is selected.   

- [ ] Verify that legacy cases move form VACOLS location 33 (Transcription) to 34 (Hearing Abeyance) if "Mark as complete: Reschedule Hearing" is selected and then an admin action is then applied.

### LEGACY and AMA

**Cancelled**
- [ ] Verify that if hearing disposition is changed to cancelled, that previous tasks related to other dispositions are removed (Can they be deleted?) and cancelled moves AMA flow forward, and moves Legacy cases as needed.

**Postponed**
- [ ]  Verify that if hearing disposition is changed to postponement from another disposition, that previous tasks related to other dispositions are removed (Can they be deleted?) and postponement moves AMA flow forward, and moves Legacy cases as needed.

**No Show**
- [ ] Verify that if hearing disposition is changed to no show from another disposition, that previous tasks related to other dispositions are removed (Can they be deleted?) and no show moves AMA flow forward, and moves Legacy cases as needed.

**Held**
- [ ] Verify that if hearing disposition is changed to held, that previous tasks related to other dispositions are removed (Can they be deleted?) and held moves AMA flow forward, and moves Legacy cases as needed.

**Transcription Pre-MVP**
- [ ] Verify that if a hearing disposition changes that the case moves from 33 (Transcription) to the appropriate location based on disposition and removes transcription tasks. 

## Related Ticket
#8650 Hearing Disposition Epic

**Comment by MeredithStewart** [comment]
Closing this ticket because it's out of date. New ticket: #9403
