### ISSUE TITLE
Hide Hearing Worksheet link from VSOs

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8793]
VSOs are using the Case details page just like BVA employees. The Hearing Worksheet lives on the Case Details page and Reader. We've already restricted VSO access so they don't have Reader, but we also want to ensure they can't access the Hearing Worksheet from Case details.

Note: VSOs are only seeing AMA cases right now, and no AMA hearings have been held. This needs to be implemented prior to the first AMA hearing being prepared for, so we should shoot for mid-March at the latest.

## AC
- Hide Hearing Worksheet link from VSOs on Case Details

**Comment by sharonwarner** [comment]
@laurjpeterson We're also adding a Hearing Details link to the Case Details page, do you think we should restrict VSOs' access to that link as well? 

Here's that ticket for reference: https://github.com/department-of-veterans-affairs/caseflow/issues/8458

**Comment by MeredithStewart** [comment]
I think Hearing Details link should be hidden from VSOs.

**Comment by laurjpeterson** [comment]
I agree!

**Comment by lowellrex** [comment]
SMALL - don't forget tests! We should be able to take advantage of [this `userIsVsoEmployee` attribute](https://github.com/department-of-veterans-affairs/caseflow/blob/4d9fd1c2d05f62e715b9697185ca80195fa75846/app/views/queue/index.html.erb#L8) we have on the frontend.

**Comment by lowellrex** [comment]
Screenshot of what that link looks like:
![image](https://user-images.githubusercontent.com/32683958/52441501-c5c33b00-2aee-11e9-9691-8bde7637dc53.png)

**Comment by MeredithStewart** [comment]
@lowellrex @laurjpeterson -- I think an attorney that had access to the View VLJ Hearing Worksheet now no longer doesn't have access. Did we change permissions here?

**Comment by tomas-nava** [comment]
@MeredithStewart this change didn't go into production until 11:10am PT today, 2/19.
