### ISSUE TITLE
Issues with VACOLS opt ins show up as ineligible when editing

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8798]
On the Add/Remove issues page for a HLR or SC with an issue with a VACOLS opt in. It's showing that those issues are invalid, even though they are not.

![bug](https://user-images.githubusercontent.com/1596259/51354253-e1936e00-1a67-11e9-9955-4087fb8bc76c.PNG)

## Technical Notes
You can see this in UAT on:
700032765 EP 033

**Comment by pkarman** [comment]
Probably fixed by #8812

**Comment by shanear** [comment]
![ss5](https://user-images.githubusercontent.com/1596259/51626947-92c95680-1ef5-11e9-924a-d854c4ca6801.PNG)
Works! Although now the wording is a little weird. But I'll make another ticket for that.
