### ISSUE TITLE
Matching active nonrating issues shows soft deleted issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8799]
When selecting a non rating issue category, it's showing nonrating request issues that were removed from decision reviews via the Add/Remove issues page. These issues should not show up since they have been soft deleted.

![matchingsoftdeletedissues](https://user-images.githubusercontent.com/1596259/51356602-fa078680-1a6f-11e9-9b22-b8931eb381ee.PNG)

**Comment by pkarman** [comment]
consider https://github.com/jhawthorn/discard

**Comment by shanear** [comment]
not-deleted ones still showing up 
<img width="1552" alt="screenshot 2019-01-31 15 45 31" src="https://user-images.githubusercontent.com/1596259/52093211-445c2d80-256f-11e9-9aca-abca2abe95a3.png">

deleted ones not showing up
<img width="1552" alt="screenshot 2019-01-31 15 45 21" src="https://user-images.githubusercontent.com/1596259/52093212-4625f100-256f-11e9-990f-8f490d531159.png">
