### ISSUE TITLE
Have Caseflow verify Power of Attorney

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#88]
Almost every participant mentioned the Power of Attorney and it's respective Form 8 fields. Some were wondering if the POA was accurately reflected in the app. Others wanted a clearer call out about the POA and it's supporting documentation.     

Suggestions: 
- Add a check for the POA and it's supporting documents to Caseflow. 
- Make sure the POA is clearly articulated in the header section that contains information about the appeal.

**Comment by KHarshawat** [comment]
@paultag got us hooked up to BGS which contains POA data so this should help us. Likely we'll have to create a UI to do the comparison and allow the user to edit.
