### ISSUE TITLE
Change VACOLS location when assigning an existing EP

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#880]
As a case worker, when I assign an existing EP to a partial grant or remand, it should also update the VACOLS location appropriately.

## Acceptance Criteria
1. When assigning an existing EP to a partial grant or remand, verify that that appeal was moved to the appropriate location (based on the rules in https://github.com/department-of-veterans-affairs/caseflow/issues/723)

**Comment by kierachell** [comment]
Am unable to get into VACOLS to validate myself :(

**Comment by kierachell** [comment]
**PASSED**

<img width="563" alt="screen shot 2017-02-23 at 9 29 29 am" src="https://cloud.githubusercontent.com/assets/18075411/23263188/77c5e5a4-f9ab-11e6-8349-15351ab2e811.png">
Middle few Remands/Partials were assigned, locations updated it seems.
