### ISSUE TITLE
Update test data script to move partial grants and remands back to location 97 in VACOLS

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#881]

**Comment by kierachell** [comment]
connects https://github.com/department-of-veterans-affairs/appeals-qa/issues/41

**Comment by kierachell** [comment]
Blocked because `preprod` vs `uat` disparity

**Comment by kierachell** [comment]
**PASSED**
<img width="1034" alt="screen shot 2017-02-24 at 10 39 34 am" src="https://cloud.githubusercontent.com/assets/18075411/23311002/8230d3be-fa82-11e6-8106-3f72d0a579e1.png">

Created an SQL monster to do this.
