### ISSUE TITLE
Decision Review | Create End Product | Change button copy

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#882]
As a Product Owner, I would like the **_Create End Product_** button changed to **_Route Claim_** on the `Decision Review` page so that it more accurately represents the action being taken.

# Acceptance Criteria
1) Verify that the **_Create End Product_** button has been changed to **_Route Claim_**.
1) Verify that, when the appeal has multiple decisions, the **_Create End Product_** button has been changed to **_Route Claim for Decision X_**. (@lakohl to confirm)
1) Very that the blue button is less wide to accommodate a shorter CTA.

## Mockup
_**View - Decision Review page - Before**_
<img width="672" alt="screen shot 2017-02-09 at 6 35 09 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807866/3807272a-eef7-11e6-870c-98bd317cc13a.png">

**_View - Decision Review page - After_**
<img width="806" alt="screen shot 2017-02-09 at 6 44 04 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807971/c6203e52-eef7-11e6-88f2-9e3e30175999.png">

# Note
This is just for single decision.
# Related Stories
n/a

**Comment by nikitarockz** [comment]
Original
On the Decision Review page, change the button copy from 'Create End Product' to 'Route Claim'.

1) Verify that the button copy says: Route Claim.
1) Very that the blue button is less wide to accommodate a shorter CTA.


**Currently:**
<img width="672" alt="screen shot 2017-02-09 at 6 35 09 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807866/3807272a-eef7-11e6-870c-98bd317cc13a.png">

**Change to:**
<img width="806" alt="screen shot 2017-02-09 at 6 44 04 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807971/c6203e52-eef7-11e6-88f2-9e3e30175999.png">

**Comment by kierachell** [comment]
**PASSED**
lgtm
<img width="729" alt="screen shot 2017-02-14 at 21 41 25" src="https://cloud.githubusercontent.com/assets/18075411/22958612/5c8a63d6-f2fe-11e6-880e-4df33680f3ce.png">

![claimroutebutton](https://cloud.githubusercontent.com/assets/18075411/22958581/294f4734-f2fe-11e6-8517-a120d14b760f.gif)
