### ISSUE TITLE
Create Edit Hearing Details link on Daily Docket 

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#8822]
- Links to `/hearings/:hearingId/details` for AMA hearings 
- Presents message to edit in VACOLS for Legacy hearings
https://va-gov.invisionapp.com/share/TKPRX5QUMRW#/screens/338332664

**Comment by lomaxap** [comment]
This may have been completed.

**Comment by Chingujo** [comment]
@pshahVA @lomaxap 

I believe the AMA portions of this are implemented as it appears in demo. I would just check that that the link also exists fo legacy appeals and the message in page 6 of that invision is implemented, this can be closed
