### ISSUE TITLE
Spec out a way to delete erroneous appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8824]
Sometimes appeals are established in error - for example, a form is misunderstood to be an appeal when it is actually a supplemental claim. So far, we've been deleting these appeals from the prod database. We think we need a safer, more reversible way to delete these appeals.

**Comment by lowellrex** [comment]
I'd be in favor of changing the status for all open tasks for that appeal to `completed` (or `cancelled` whenever we add that status) and attaching a note in the root task (now `completed`) that indicates why the case was closed.

**Comment by laurjpeterson** [comment]
@amprokop @lowellrex - based on the withdrawing appeals discussion, it's sounding like we're going to remove all request issues on appeal and give them a status of closed/cancelled. 

at that point, we'd need to prompt the user to confirm they want to delete the appeal, and at _that_ point, i think we'd kick off the steps that lowell outlined above. 

since we have a path forward, i think i'll close this spec ticket. 

cc: @steve-gov, because he's taking on breaking down withdrawal of appeals work into smaller tasks.
