### ISSUE TITLE
Timezone bug when adding nonrating issues

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#8828]
Saw this happening on demo:
* created an intake with a nonrating issue with date 08/01/2018
* saved it, went to noncomp page
* "Prior decision date: 07/31/2018."

http://www.caseflowdemo.com/decision_reviews/voc_rehab/tasks/113

This might affect other date fields as well.

**Comment by shanear** [comment]
date looks good. Made sure to do this after 3pm PST
<img width="1552" alt="screenshot 2019-01-25 15 12 22" src="https://user-images.githubusercontent.com/1596259/51777828-b20de280-20b3-11e9-9779-5a6eacc7f34e.png">
