### ISSUE TITLE
API: All results should include an updated attribute

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8831]
Each Supplemental Claim, Higher-Level Review, and Appeal returned by the appeal status API should have an updated attribute.

```
...
"updated": "2019-01-03T09:30:15-05:00"
...
```

As with Legacy Appeals, this shows the time the data was serialized, so that cached results can display when they were retrieved.

**Comment by mc-usds** [comment]
No change needed. HLR, SC, and Appeals get this functionality from the parent serializer. They will have "updated" set to the time they were serialized.
