### ISSUE TITLE
API: SCs and HLRs should have an active attribute

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8834]
Each Supplemental Claim and Higher-Level Review returned by the appeal status API should have an active attribute.

```
...
"active": true
...
```

This reflects whether the SC or HLR is still open. For HLRs, it should remain open until all EPs, including HLR DTA Error EPs, are closed.

**Comment by mc-usds** [comment]
implemented and merged. Not sure why it didn't automatically close.
