### ISSUE TITLE
API: Appeal should have location attribute

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8836]
Each Appeal returned by the appeal status API should have a location attribute.

```
...
"location": "bva"
...
```

This will be either "aoj" or "bva", depending on who has jurisdiction of the Appeal. Most Appeals will be in "bva" jurisdiction, with the exception of decided appeals that have a pending EP created at dispatch to track their effectuation in VBMS, which would be marked as "aoj". If the appeal is closed, this should be "bva".

**Comment by mc-usds** [comment]
PR merged in
