### ISSUE TITLE
API: SCs, HLRs, and Appeals should have programArea attribute

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8837]
Each SC, HLR, and Appeal returned by the appeal status API should have a programArea attribute.

```
...
"programArea": "disability"
...
```

This reflects the claim type of the issues on the case. On SCs and HLRs this is written on the form. If, in the case of an appeal, there are issues of multiple types on appeal, the programArea should be "multiple".

**Comment by mc-usds** [comment]
done
