### ISSUE TITLE
API: All SCs, HLRs, and Appeals should have an aoj attribute

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8838]
Each SC, HLR, and Appeal returned by the appeal status API should have an aoj attribute.

```
...
"aoj": "vba"
...
```

This reflects the administration that originated the decision being reviewed. It will generally be one of "vba", "vha", or "nca". For Board-originated or other appeals, it would be "other".

**Comment by mc-usds** [comment]
For HLR and SC, can this be derived from the benefit_type with 1-7 mapping to "vba"

benefit_types
1. "compensation": 
2. "pension": 
3. "fiduciary": 
4. "insurance": 
5. "education": 
6. "voc_rehab": 
7. "loan_guaranty": 
8. "vha": 
9. "nca":

**Comment by cmgiven** [comment]
Yes, that’ll work!

**Comment by mc-usds** [comment]
PR to implement has been merged.

**Comment by cmgiven** [comment]
Reopening because this ticket also includes Appeals (SCs and HLRs are complete). Appeals are currently hardcoded to "other".
