### ISSUE TITLE
API: SC/HLR statuses

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8843]
All Supplemental Claims and Higher-Level Reviews should have a status attribute:

```
"status": {
  "type": "sc_received",
  "details": {}
}
```

This issue concerns only the `type` of the status. For each `type` that has a non-empty `details` object, there will be a separate issue.

* **Supplemental Claim**
  * If the Supplemental Claim is active, its status has the type `sc_received`.
  * If the Supplemental Claim was closed with a decision, its status has the type `sc_decision`.
  * If the Supplemental Claim was closed for any other reason, its status has the type `sc_closed`.
* **Higher-Level Review**
  * If the original HLR EP is active, the type is `hlr_received`.
  * If the original HLR EP was closed with a DTA error and there is an active HLR DTA Error EP, the type is `hlr_dta_error`.
  * If the HLR EP was closed with a decision that did not contain a DTA error, or if the HLR DTA Error EP was closed with a decision, the type is `hlr_decision`.
  * If the Higher-Level Review was closed for any other reason, its status has the type `hlr_closed`.

**Comment by mc-usds** [comment]
done
