### ISSUE TITLE
Logic for Central Office Hearings - Geomatching

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8846]
For AMA Veterans:
* The AMA law indicates that the Board will schedule Veterans for hearings at a location in which they will get a hearing the quickest. There is no longer an option for type: video, central, or travel board, as it exists in legacy. 
* All AMA Veterans are presumed to be video hearings, unless they geo-match closer to the Central Office hearing locations. 
* However, Veterans do have the option to switch from video to Central Office (or back to video at an RO). It is expected that this happens less frequently, since a Veteran would need to know this and request it, but it will not be available on forms like it was for Legacy. 

For Legacy Veterans: 
* We won't geomatch legacy Veterans to the Central Office hearing location. 
* Only those with the hearing type "central" or changed to "central" will appear in the list of Legacy Veterans to be scheduled for Central Office hearings. 
* Any changes to this logic will have to be coordinated with LRP and the Hearing Branch.

**Comment by lomaxap** [comment]
@sharonwarner @mdbenjam 

**for legacy hearings** on the assign hearings page:
1. To find hearings for all ROs besides central, match on veteran's `closest_regional_office` but exclude `VACOLS::Case`s where hearing_request_type (`bfhr`) is central (`1`)
2. To find central hearings, ignore veteran's `closest_regional_office` and only pull in `VACOLS::Case`s hearings where hearing_request_type is central
```ruby
# maybe cache these values for a day since these shouldn't change. There are 1,239 cases that match this query
legacy_central_appeal_ids = VACOLS::Case.where(bfhr: 1, bfcurloc: "CASEFLOW")
  .map { |vacols_case| LegacyAppeal.find_by(vacols_id: vacols_case.bfkey).id }.compact 

if regional_office == "C"
  legacy_appeal_tasks = incomplete_tasks
    .where("veterans.closest_regional_office = ?", regional_office)
    .where("legacy_appeals.id NOT IN (?)", legacy_central_appeal_ids)
else
  legacy_appeal_tasks = incomplete_task
    .where("legacy_appeals.id IN (?)", legacy_central_appeal_ids)
end
```
