### ISSUE TITLE
Reports of increased latency on Dispatch (starting week of Jan 13?)

### ISSUE THREAD

**Issue by lisac-usds** [department-of-veterans-affairs/caseflow#8852]
A few user reports have come in asking about Dispatch latency since the week of Jan 13.  Can we explain what might be happening in the app? Is there a way to reduce the latency?

Discussion in slack (Jan 17 in [#appeals-engineering]( https://dsva.slack.com/archives/C2ZAMLK88/p1547733458320500)).

Some notes from that thread:
- A lot of these exceptions observed in Dispatch: 
```VBMS does not currently support claim establishment of claimants with a fiduciary. Please establish this claim in an appropriate source system.```

- from Datadog I can see that our measured latency for finding claims by file number rose from about ~1.5s to ~2s starting after a big spike on Jan 14

- the other thing to check into is whether the latency is somewhere in the route between caseflow and BGS.

**Comment by kencheeto** [comment]
I've added some additional logging to see if the uncategorized latencies correspond to interactive Dispatch use, but they do not (most/all of the uncategorized metrics for `claims.find_by_vbms_file_number` going to intake jobs). I'm following up on the original issue to see if the problem still exists :(

**Comment by kencheeto** [comment]
thanks @mc-usds - sounds like a plan

**Comment by pkarman** [comment]
@mc-usds I think we can close this?

**Comment by mc-usds** [comment]
Yeah, I think so. BGS pushed out their fix.
