### ISSUE TITLE
Display data source for Veteran address in Case details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8853]
We return Veteran address from BGS for AMA and legacy appeals (https://github.com/department-of-veterans-affairs/caseflow/issues/7426). Let's display this for our users, just like we do for POA address. 

Reference: mocks for POA address data source here - https://github.com/department-of-veterans-affairs/caseflow/issues/6812

## AC
- Data source for Veteran address shown in Case details, about the Veteran section, for both legacy and AMA appeals

**Comment by allyceh** [comment]
Instructional copy proposal for About the Veteran module in Case Details: "Veteran information comes from VBMS. To update the veteran's information, please send a request to the VLJ support staff."

@laurjpeterson , is the message above accurate? I know that veteran info is pulled from BGS/Corp DB (which integrates with Vet 360), but VBMS is the system that BVA employees know and can update. It also syncs with those other systems.

**Comment by laurjpeterson** [comment]
Yep, this looks good. We ask users to "send a request to VLJ Support Staff" for POA address too right?

**Comment by allyceh** [comment]
Correct! 
<img width="926" alt="screen shot 2019-01-28 at 10 59 28 am" src="https://user-images.githubusercontent.com/40216950/51848575-d48a4080-22eb-11e9-8485-793a8cf7f791.png">

Proposed language is intended to mimic the language used in the POA section (above).

**Comment by laurjpeterson** [comment]
Cool. I think this works! @lowellrex, when @allyceh adds the mocks, it's ready for dev.

**Comment by lowellrex** [comment]
SMALL. Let's just infer the datasource based on whether the appeal is a `LegacyAppeal` (in which case the data source will be VACOLS) or an AMA `Appeal` (BGS).
