### ISSUE TITLE
Existing EP | Display claims with BGS Status of "RDC" as "Redacted" status

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#886]
As a Caseworker, I want to see claims with a BGS Status Code of "RDC" displayed as "Redacted" on the `Existing EP` page so that the Status value more accurately reflects its meaning.

# Acceptance Criteria
1. Verify that claims retrieved from BGS with a status code of "RDC" has a _"Status"_ value as "Redacted"  on the `Existing EP` page.

## Mockups
![image](https://cloud.githubusercontent.com/assets/23063044/23265206/fa94cada-f9b1-11e6-838b-92c87dda45d9.png)

## Notes
- We have some test data for this in preprod. Ask Artem.

# Related Stories
n/a

**Comment by kierachell** [comment]
no needed
