### ISSUE TITLE
Appeal Status update Swagger doc

### ISSUE THREAD

**Issue by mc-usds** [department-of-veterans-affairs/caseflow#8861]
For programArea add "fiduciary"
For events::type add "distributed_to_vlj" and "ama_remand"

**Comment by cmgiven** [comment]
We will cut the different `ama_remand` event, and just have all Board decisions use the `bva_decision` event. Note that this does not affect the `ama_remand` status.

**Comment by cmgiven** [comment]
SwaggerHub version updated. There's an open PR on vets-api that I'll leave up for a while in case Melissa identifies more missing/wrong things.
