### ISSUE TITLE
Add Veteran attributes from VBMS to Case details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8866]
When attorneys, judges, and other BVA employees are working on a Veteran's case, they want to see if the Veteran has any special circumstances or attributes, so they can incorporate them in their decision (or other work products). 
- For example, if a Veteran is incarcerated, it's helpful for members of the hearing branch to know that the Veteran may not be able to physically attend their hearing at a regional office location. 
- For example, if a Veteran was exposed to Mustard Gas, attorneys and judges need to look up previous CAVC court cases that might affect the way they decide the Veteran's case. 

VBMS contains Veteran attributes (many of them are called "flashes" in VBMS-lingo) that can help BVA users better understand the Veteran's circumstance when completing appeals processing tasks. 

Examples: 
- Incarcerated Veterans
- Mustard Gas
- More examples are listed as "special issues" in this ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/6903

Veterans could have one or many "flashes"/attributes associated with them. 

## Idea
- These Veteran attributes could live in the "About the Veteran" section of Case Details

## AC
- Veteran attributes are included in Case Details.

**Comment by laurjpeterson** [comment]
@eric-nava - can you ask sierra team to give you some sample data for "Veteran Flashes" so you know what data / fields we have at our disposal?

**Comment by sneha-pai** [comment]
[update]: 
We need to have centralized understanding of veteran flashes, with hearings team and maybe intake. 
More work to be done here 
Sneha is officially taking this over from Eric and will follow up with hearings and intake.

**Comment by laurjpeterson** [comment]
@sneha-pai - centralized understanding of Veteran flashes will start with VBMS data and VBMS fields. let's follow up with the intake team first. then, let's show the hearings team what flashes are available so they can let us know, from that list, which ones they need. the only one we know right now is incarcerated Veteran, but there could be others they need (they just don't know they exist yet).

I actually think we should ask Dustin to help us with this exhaustive list of Veteran flashes first - he has VBMS access.
