### ISSUE TITLE
Hearing Worksheet | AMA 'correct issues' link

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8870]
- [ ] Verify for AMA appeals, the user can select, "Correct Issues," which brings the user to a modal within Intake that allows the VLJ to correct administrative errors. Note: URL is the same one that will be implemented on Case Details. This treatment will be a secondary button.
- [ ] Verify that after VLJ closes the "Correct Issues" modal, that the user is brought back to the Hearing Prep Hearing Worksheet. Note: While in Modal, the background will appear as if they are in Intake.

<img width="980" alt="screen shot 2019-01-22 at 5 33 39 pm" src="https://user-images.githubusercontent.com/4306128/51569969-e42d0380-1e6b-11e9-895f-de1c2fe8c25b.png">

**Comment by laurjpeterson** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/10562
