### ISSUE TITLE
Intake | Errors with BGS relationships request can cause User to get stuck on error screen forever

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8881]
Today someone received an error when fetching the veteran relationships in UAT.

```
Legacy POA for vet not found on Corporate Database. The POA data was not stored on the Corporate Database, however, the rest of the transaction was stored on the Corporate Database
```

The bigger issue though was that she was stuck on the error page and could not cancel the intake. We need to fix this scenario.

![image 3](https://user-images.githubusercontent.com/1596259/51581978-0da35a80-1e7f-11e9-9fbb-a4b68d2e8ac8.png)

## Technical Notes
This is highly related to https://github.com/department-of-veterans-affairs/caseflow/issues/5480. I think the solution is to continue to capture specific dependency related errors instead of a global catch. If it's an issue with caseflow, we should simply fix the issue.

**Comment by nicholasholtz** [comment]
@shanear Is this still being investigated?

**Comment by shanear** [comment]
![test](https://user-images.githubusercontent.com/1596259/52092778-8f754100-256d-11e9-9333-66dc75d26c52.gif)
works 👍
