### ISSUE TITLE
Hearing Prep Worksheet > "Save to PDF" // inconsistent spacing & display bugs

### ISSUE THREAD

**Issue by joeyyang** [department-of-veterans-affairs/caseflow#8885]
As a judge, I sometimes like to print the hearing prep worksheet to take paper notes, which allows me to make eye contact with the veteran during the hearing. 

I sat in on a hearing and noticed a few print display bugs, which the judge printed from "Save to PDF" in Windows / Chrome:
- The "Current Issues" tab has inconsistent / compressed spacing
- The "Hearing Summary" section reproduces a carriage return with extra spaces in the print view, which takes up extra paper (but in this case allows the judge to take handwritten notes in the margin)

<img width="591" alt="screenshot 2019-01-23 10 25 15" src="https://user-images.githubusercontent.com/2928395/51620940-79c6a280-1f01-11e9-9ca0-39faae632af7.png">
<img width="613" alt="screenshot 2019-01-23 10 46 51" src="https://user-images.githubusercontent.com/2928395/51620941-79c6a280-1f01-11e9-9e98-8288f4a7e371.png">

**Comment by Chingujo** [comment]
@ferristseng 

Thank you so much for the awesome overview yesterday. Can you post a screenshot of the preview on this issue whenever you get the chance please?

@pshahVA was interested in seeing the view as well =D

**Comment by ferristseng** [comment]
@Chingujo @pshahVA Sure!

<img width="436" alt="Screen Shot 2019-06-28 at 11 34 36 AM" src="https://user-images.githubusercontent.com/1298274/60354713-d6d7f000-999a-11e9-9444-fa5f56b7ab4c.png">
