### ISSUE TITLE
DecisionReviewProcessJob VBMS::Requests::AssociateRatedIssues 404s

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8886]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3405/

Claim ID 70244484 is failing to associate_rating_request_issues

**Comment by leikkisa** [comment]
Does this one just need a retry since it's a 404?

**Comment by kencheeto** [comment]
it's been failing consistently, i was hoping the same

**Comment by pkarman** [comment]
That sentry url references claim id `70267000` not `70244484`.

I cannot find an End Product Establishment record with either `reference_id` in the db in any case.

**Comment by pkarman** [comment]
All our VBMS routes must be explicitly listed in the forward proxy config at https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/va-services.yml - otherwise they never make it to VBMS.

**Comment by pkarman** [comment]
Confirmed this is working now in production.
