### ISSUE TITLE
SPIKE | Investigate whether "Ready for hearing" box is being correctly checked in VACOLS on certification

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#889]
During a user interview today, a user reported that for Travel Board hearings, her team has to go to VACOLS after certifying with Caseflow and manually check the "Ready for Hearing" box, otherwise it won't ever be seen by the hearing schedulers. It was my impression that we automated this step. We should investigate if this is actually working properly, perhaps by a screenshare with a user who is certifying an appeal.

**Comment by shanear** [comment]
It does. see: https://github.com/department-of-veterans-affairs/caseflow/issues/199

**Comment by amprokop** [comment]
Yeah, I'm just wondering why two people at an RO reported today that they still do this step manually. Think this is worth a follow-up with them, @shanear? Or are you confident that this is user error.

**Comment by shanear** [comment]
We should follow up and see the error in action.

**Comment by amprokop** [comment]
Ok @shanear — we got another independent report from St. Petersburg about this today. We should put this in this sprint IMO.

**Comment by amprokop** [comment]
Here are some steps to validate this on a screenshare with a user:

1. Verify that in VACOLS, that "Travel Board" or "Video Hearing" is selected in the hearing type radio buttons section
2. Start a new certification with Caseflow (it must be a new certification, not resuming an old one)
3. Complete the certification
4. Verify that in VACOLS, the "Ready for Hearing" bug is checked.

**Comment by shanear** [comment]
@kierachell & @astewarttistatech want to take this on?

**Comment by amprokop** [comment]
We've gotten more than one report of this now.

**Comment by joofsh** [comment]
We saw this issue come up in Baltimore today during our RO visit. There were certified cases that were in limbo since they were not "ready for hearing". They may not have been Caseflow certified cases though.

**Comment by amprokop** [comment]
Thanks for the info. Yeah, I suspect this is a legit problem then. Artem or
Alexis, can you do a smoke test to verify if you can reproduce?


Background:
Caseflow is supposed to check the "Ready for Hearing" box in VACOLS if the
appellant has requested a Travel Board hearing or a video hearing. We're
hearing from users that this might not be the case.

The steps would be:
Case 1:
- Select "Travel Board" in the hearing box in VACOLS, but make sure the
"Ready for Hearing" box is not checked
- Certify the appeal with Caseflow
- Go back to VACOLS and observe -- is the "Ready for Hearing" box now
checked?

Case 2:
- Select a video hearing in the hearing box in VACOLS, but make sure the
"Ready for Hearing" box is not checked
- Certify the appeal with Caseflow
- Go back to VACOLS and observe -- is the "Ready for Hearing" box now
checked?

**Comment by kierachell** [comment]
I wouldn't even know where that box is. It never shows up in Caseflow/VBMS. And VACOLS is a database - it has no checkboxes

**Comment by amprokop** [comment]
Yep, this box should be checked programmatically, by the code. It's not
visible in the Caseflow UI and doesn't correspond to anything in VBMS.

You've probably only used the DB, but VACOLS also has a UI. @shanear, does
anyone on our team have access to the VACOLS via the interface? If not,
maybe @chinguo can get on a call with a user who is experiencing this
problem and screenshare.

**Comment by amprokop** [comment]
@kierachell , here's the line of code that should do it:
https://github.com/department-of-veterans-affairs/caseflow/blob/773f6c41fffad201597781da8f4fb6adc6fcebb3/app/services/appeal_repository.rb#L221

**Comment by amprokop** [comment]
From Jed:
```
RO Travel Boards and Video TBs both have the same BFHR which is ‘2’. So to simplify: If (BRIEFF.BFHR=2) then (BRIEFF.BFTBIND=X) once certified.
```

**Comment by kierachell** [comment]
FYI `BFHA` column has values other than 1,2,6.

**Comment by amprokop** [comment]
@Chingujo is going to follow up with a user— we *only* check the "Ready For Hearing" box if the hearing type is "Travel Board", but the user appears to be referencing BVA hearings.

**Comment by amprokop** [comment]
@Chingujo — here's the PM issue discussing this— https://github.com/department-of-veterans-affairs/appeals-pm/issues/112

Jed sez: ```the ROs don’t schedule Central Office hearings so they can’t mark those as ready. ``` which is why we don't check the "Ready For Hearing" box for BVA hearings.

**Comment by kierachell** [comment]
So, what's not working?

**Comment by Chingujo** [comment]
Good question and following up. We also have a user testing sessions tomorrow and Friday we can ask and verify. Also have a planned meeting with the specific user this coming Monday as well.

**Comment by amprokop** [comment]
Assigning this to @Chingujo—can you post an update here when you get more info from the users?

**Comment by Chingujo** [comment]
@amprokop see below from our quick sync
cc: @shellicious for context and to clarify 

Talking with New York City RO, this box should be checked ready along with video when relevant before they can be dispatched to the BVAs. Will update after more user testing.

**Comment by amprokop** [comment]
This message confuses me, I'd love a brief explainer of something that seems like it might be inconsistent. 

This message from Jed (emphasis mine):
```No need to worry about any of the other fields, the ROs don’t schedule Central Office hearings so they can’t mark those as ready. **RO Travel Boards and Video TBs both have the same BFHR which is ‘2’***. So to simplify: If (BRIEFF.BFHR=2) then (BRIEFF.BFTBIND=X) once certified.```



But in our code, `video_hearing` and `travel_board` have distinct codes. 
```
  HEARING_TYPES = {
    "1" => :central_office,
    "2" => :travel_board,
    "6" => :video_hearing
  }.freeze
```

What are "Video TBs"? Do they not fall under the category of `video_hearing`? If not, what does fall under that category? @shanear or @lakohl, might one of you know?

**Comment by Chingujo** [comment]
More context here. @shellicious and I got a full walkthrough of a certification with Caseflow from St. Petersburg where the above comments as made. We can confirm (recorded) that the "ready" box is not being automatically checked. 

The Coach was also able to confirm with her Nashville and Roanoke colleagues that this was not working on their end as well.

**Comment by kierachell** [comment]
# FIRST OF ALL:

Form 8 is not being updated properly.
![form8hearing](https://cloud.githubusercontent.com/assets/18075411/23855723/3772cc30-07cd-11e7-9c16-1997c31f7927.gif)
The checkboxes are not updating Form 8 correctly; especially if you go back and forth editing the form. Just look above.

Questions *10A* and *10B* have no effect on *Form 8* or any data in VACOLS.

# Expected behavior:

When Question *10A* checked *Yes* then VACOLS needs to be updated to display that the *Hearing Request* -> *Ready* to be checked.

**Comment by amprokop** [comment]
```
When Question 10A checked Yes then VACOLS needs to be updated to display that the Hearing Request -> Ready to be checked.
```

This might be reasonable behavior, but it's not actually the behavior we expect here :)  Our code only updates the Ready For Hearing box to "Yes" if the data we fetched from VACOLS when starting the certification indicates the type of the hearing. The selection on the Form 8 should have no effect on VACOLS.

See the instructions I posted here:
> 
> Background:
> Caseflow is supposed to check the "Ready for Hearing" box in VACOLS if the
> appellant has requested a Travel Board hearing or a video hearing. We're
> hearing from users that this might not be the case.
> 
> The steps would be:
> Case 1:
> - Select "Travel Board" in the hearing box in VACOLS, but make sure the
> "Ready for Hearing" box is not checked
> - Certify the appeal with Caseflow
> - Go back to VACOLS and observe -- is the "Ready for Hearing" box now
> checked?
> 
> Case 2:
> - Select a video hearing in the hearing box in VACOLS, but make sure the
> "Ready for Hearing" box is not checked
> - Certify the appeal with Caseflow
> - Go back to VACOLS and observe -- is the "Ready for Hearing" box now
> checked?
>

**Comment by amprokop** [comment]
cc @Chingujo

**Comment by kierachell** [comment]
Yes I ran through those cases; our code does what it does;

There's still no clarity on what it is _supposed_ to do, though. So - you guys figure it out.

**Comment by lakohl** [comment]
Looping in @shellicious who is working on designs for this

**Comment by Chingujo** [comment]
Gotcha. So the data is being pulled from VACOLs and not the form 8.  I looked over the recording again and the case the user certified through Caseflow did not update the ready box in VACOLs despite a hearing being requested. It might be helpful to look through the recording and the specific appeal in question to rule out user error?

**Comment by amprokop** [comment]
Hmm. We should be able to reproduce this given the instructions I wrote
down, right? Shouldn't have to rely on a user video. Whatcha think?

**Comment by Chingujo** [comment]
Agreed! Just for context.

The cases you have match the flow =D. 

Artem ran through them this morning and we did see an 'X' or a "yes" for the BFTBIND column when the hearing was a travel board or set to equal 2. Unfortunately, we don't know what BFTBIND column is lol T-T. Does this correspond to the "ready check box"?

**Comment by cmgiven** [comment]
See this issue for conversation with Jed: https://github.com/department-of-veterans-affairs/appeals-pm/issues/112

**Comment by amprokop** [comment]
Thanks @cmgiven! That's how I got context on this originally :)

**Comment by cmgiven** [comment]
These are the codes for BFHR:

```
1	Central Office
2	Travel Board
3	Confirmation Needed
4	Clarification Needed
5	None
```

**Comment by cmgiven** [comment]
@amprokop: Yeah, the issue is that we're using Hearing Action (BFHA) instead of Hearing Request (BFHR) to determine the kind of hearing that's been requested. Hearing Action is null until the hearing occurs.

**Comment by amprokop** [comment]
aha. good catch

**Comment by shellicious** [comment]
From the St Petersburg feedback session, we saw that RO staff mark the hearing in some way that a hearing request date is filled out in VACOLS, but they leave the "ready" checkbox blank. I'm not sure where they input the hearing request date -- I can Lync a St Petersburg Coach and find out. This might relate to the actions that @cmgiven is referring to above.

Here's what it looks like:

![screen shot 2017-03-13 at 1 50 45 pm](https://cloud.githubusercontent.com/assets/1178390/23867964/1962ea6e-07f4-11e7-920b-f1f8f9f174b9.png)

We also learned that the "ready" checkbox needs to be checked even if it's a Video hearing.

cc @amprokop

**Comment by kierachell** [comment]
**PASSED**
Now that it's fixed...
![screenshot_2017-03-16_15-13-17](https://cloud.githubusercontent.com/assets/18075411/24014443/582aad68-0a5b-11e7-8bc9-c4a15c0f50de.png)
![screenshot_2017-03-16_15-13-32](https://cloud.githubusercontent.com/assets/18075411/24014442/582457e2-0a5b-11e7-92ce-d2fe16b7531c.png)

![screenshot_2017-03-16_15-13-49](https://cloud.githubusercontent.com/assets/18075411/24014441/581ea02c-0a5b-11e7-8405-b1b0ae43a04b.png)
