### ISSUE TITLE
Remove deadline for Legacy cases

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8894]
Last year (2018), Vice Chairman Dave Spickler explained that the Board is no longer relying on deadlines for attorney performance measurement. Deadlines are not available for AMA cases, and will no longer be relied on for Legacy cases. We currently show the deadline (from DAS) in attorney queues. Let's remove them.

Note: do not implement without comms to attorneys/judges (again)

![image](https://user-images.githubusercontent.com/32683958/52443932-04f48a80-2af5-11e9-9ade-3099c2a5ca4e.png)

## AC
- Days waiting column contains only Days waiting for legacy AND AMA cases

**Comment by lowellrex** [comment]
SMALL
