### ISSUE TITLE
Disable checkout functionality for inactive Legacy appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8895]
Josh reported that he has the ability to attorney checkout a Legacy case that has already been decided - it's in location 99, history status. We should remove the ability to check cases out for inactive Legacy appeals. 

## AC
- If a Legacy appeal is in History status (field in VACOLS), the Actions dropdown and options are not visible or active

**Comment by laurjpeterson** [comment]
@cmgiven - do you think HIS status is enough to define inactive Legacy appeals?

**Comment by cmgiven** [comment]
Yeah, that makes sense to me. I think that's slightly more logical than using location 99, although the two should be equivalent.

**Comment by aroltsch** [comment]
@laurjpeterson question about this. If the appeal is in location 99, how is it showing up under attorney's queue?

**Comment by laurjpeterson** [comment]
The user is searching for the appeal, not seeing it in their queue. I think because of their attorney or judge role in VACOLS, they are seeing the Actions drop down and associated options.

**Comment by aroltsch** [comment]
@laurjpeterson we believe this is fixed.

**Comment by aroltsch** [comment]
Josh emailed back that he is no longer seeing any issues. Closing
