### ISSUE TITLE
Global footer quick fix: add space between heart and "Digital"

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#8899]
Is: Built with ♡ by theDigital Service at VA

Should be: Built with ♡ by the Digital Service at VA

**Comment by steve-gov** [comment]
<img width="305" alt="screen shot 2019-01-23 at 12 03 27 pm" src="https://user-images.githubusercontent.com/25468689/51634376-f446f080-1f08-11e9-8d82-4aeb00b3832e.png">

**Comment by alisan16** [comment]
@nanotone Fixed this! https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit/pull/59
