### ISSUE TITLE
Generate letter at end of Caseflow

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#89]
Almost every user mentioned that, while the Caseflow they tested not save them much time, if it had a feature to automatically generate a letter that could be uploaded to VBMS and sent to the Veteran upon certification, it would save them a lot of time.    

Suggestion: Add ability to generate letter, pre-populated with necessary information. Consider allowing the user to edit this letter using Microsoft Word and re-upload it to the tool. Automatically upload that page to VBMS and allow the user to print it out so they can send it to the Veteran.

**Comment by plusjeff** [comment]
To do for myself to upload the sample letter after stripping PII.

**Comment by paultag** [comment]
Ah great, thanks, yeah, was about to ask for the letter template they use

**Comment by plusjeff** [comment]
![image](https://cloud.githubusercontent.com/assets/950486/11045315/d5770d8e-86f4-11e5-83de-787d7b0fdf87.png)

**Comment by alex** [comment]
We should figure out what formats we need this in, I assume we need a PDF to upload to VBMS, do we need to give VSRs a word version as well?

**Comment by gmorgana-va** [comment]
We received confirmation that this is a standard letter and customization should be limited to the fields that can be pre-populated using system data (see Jeff's screenshot).

**Comment by alex** [comment]
Ok, I think this is ready for working on then. @KHarshawat do you have thoughts for how the flow for the letter should work? When should it be previewed, etc.

**Comment by KHarshawat** [comment]
This is currently blocked on interviewing the gentleman who dispatches letters for the RO and potentially a databass.

Some NYRO users print, mail, and upload letters themselves, while others inter-office them to a clerk who generates, prints and mails the letter. Likely what we'll want to do is ask the clerk to dispatch all the mail going forward but give him a work queue and automate the process so it's as easy as possible for him to do. (We could even consider a `print and upload all` feature or something). 

Questions about the process;
- Does the clerk edit the letters at all?
- If so, how does he know what to change?
- How many DROS mail their own letters versus hand the work off to the clerk
- What is the clerk's current workflow?

**Comment by maryannbrody** [comment]
Hi -- 

I'm happy to talk with this guy asap. @gmorgana-va or @KHarshawat -- can you connect me or get me introduced? 

Thanks! 
Mary Ann
