### ISSUE TITLE
Intake | VBMS::Requests::AssociateRatedIssues 500 error

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#8901]
`Internal Exception: org.xml.sax.SAXParseException; cvc-datatype-valid.1.2.1: '' is not a valid value for 'integer'.`

Acceptance Criteria
* Visit the UAT /jobs page
* Find the string `is not a valid value for 'integer'` on the page
* Hover over the Restart button and note the id of the job
* Click the Restart button for that job
* Wait 10 seconds and then reload the page
* Verify the job is no longer present (i.e. has successfully finished).

**Comment by pkarman** [comment]
the underlying issue is that a contention is not being created by the EndProductEstablishment, and so the `rating_issue_contention_map` is incomplete.

**Comment by pkarman** [comment]
I tried the procedure in UAT as described in Acceptance Criteria and it worked for me. Probably good for another pair of eyes on it.

**Comment by shanear** [comment]
Restarted the job in prod and... it worked 💯
