### ISSUE TITLE
EP Creation | Create End Product | Change the VACOLS ROJ value

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#892]
As a Caseworker, I would like the ROJ in VACOLS updated for Partial Grants and Remands claims with Special Issues that are _NOT_ routed to the existing ROJ so that the claim is routed to its proper destination. (Refer to [Assigning a Station and Transferring Cases](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Special%20Issue%20Routing%20Table.md) for detailed list)

# Acceptance Criteria
1. Verify that after clicking the **_Create End Product_** button for a Partial or Remand claim having the following **Educational** Special Issue, the VACOLS ROJ value is changed to either "RO91", "RO93", or "RO94" based on its current VACOLS ROJ value (_refer to the indicated Jurisdiction List for cross reference_):

| ID | Special Issue | New VACOLS ROJ |
| --- | --- | --- |
| 1 | Education - GI Bill, dependents educational assistance, scholarship, transfer of entitlement | [Education Jurisdiction List](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Education%20Jurisdiction%20List.csv) |

2. Verify that after clicking the **_Create End Product_** button for a Partial or Remand claim having one of the following **PMC** Special Issues, the VACOLS ROJ value is changed to either "RO81", "RO82", or "RO83" based on its current VACOLS ROJ value (_refer to the indicated Jurisdiction List for cross reference_):

| ID | PMC Special Issue | New VACOLS ROJ |
| --- | --- | --- |
| 1 | DIC - death, or accrued benefits - United States | [PMC Jurisdiction List](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/PMC%20Routing/PMC%20Jurisdiction%20List.csv) |
| 2 | Foreign pension, DIC - all other foreign countries | [PMC Jurisdiction List](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/PMC%20Routing/PMC%20Jurisdiction%20List.csv) |
| 3 | Pension - United States | [PMC Jurisdiction List](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/PMC%20Routing/PMC%20Jurisdiction%20List.csv) |
| 4 | Foreign pension, DIC - Mexico, Central and South American, Caribbean | RO83 |

3. Verify that after clicking the **_Create End Product_** button for a Partial Grant and Remand claim having one of the following **COWC** Special Issues, the VACOLS ROJ value is changed to either "RO84", "RO85", or "RO86" based on its current VACOLS ROJ value (_refer to the indicated Jurisdiction List for cross reference_):

| ID | Special Issue | New VACOLS ROJ |
| --- | --- | --- |
| 1 | Waiver of Overpayment | [COWC Jurisdiction List](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/COWC%20Jurisdiction%20List.csv) |

4. Verify that after clicking the **_Create End Product_** button for a Partial or Remand claim having one of the following Special Issues, the VACOLS ROJ value is set to the new VACOLS ROJ value based on the following: 

| ID | Special Issue | New VACOLS ROJ |
| --- | --- | --- |
| 1 | Contaminated Water at Camp LeJeune | RO27 - Louisville RO
| 2 | Foreign claim - compensation claims, dual claims, appeals | RO71 - Pittsburgh Foreign Cases
| 3 | Insurance | RO80 - Philadelphia Insurance Center
| 4 | Mustard Gas | RO51 - Muskogee RO
| 5 | National Cemetery Administration | RO98 - NCA
| 6 | U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian) | RO59 - Honolulu
| 7 | U.S. Territory claim - Philippines | RO58 - Manila
| 8 | U.S. Territory claim - Puerto Rico and Virgin Islands | RO55 - San Juan
| 9 | VAMC | RO99 - VHA CO

## Mockup
**_View - EP Creation page - contains the Create End Product Button_**
![image](https://cloud.githubusercontent.com/assets/23063044/21938832/01feba7a-d98b-11e6-9e86-f942bc5daf47.png)

# Related Stories
n/a

**Comment by lakohl** [comment]
@abbyraskin can you help with the criteria for this.

**Comment by nikitarockz** [comment]
@abbyraskin what does the "(when applicable)" mean?

**Comment by abbyraskin** [comment]
"When applicable" means only for claims that are _NOT_ routed to the ROJ. If they're going to the ROJ, there's no need to make a change.

This applies to level 2 and level 3 issues based on [special issue hierarchy.](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/49)

**Comment by nikitarockz** [comment]
@abbyraskin  Checkout what I created for the AC.  I copied what you had in the 2 documents and put them in excel.  Let me know if I filtered on the correct ones.  I can change the image easily if I am missing some.

**Comment by abbyraskin** [comment]
@nikitarockz I updated the master routing rules table [here](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Special%20Issue%20Routing%20Table.md).

**Comment by abbyraskin** [comment]
My understanding is that we'll want to change the ROJ even if we don't create an EP.

**Comment by lakohl** [comment]
@Abby can you take a look at the AC above? It seems like there could be scenarios where the ROJ in VACOLS might not be the home base RO. Do we still want to base assignments on the ROJ or do we want to base them on the home base RO and if its the latter, where can the devs find this info?

**Comment by abbyraskin** [comment]
Unfortunately I don't think VACOLS keeps a record of ROJ outside of whatever is currently listed on the appeal in VACOLS. @cmgiven can you confirm?

**Comment by abbyraskin** [comment]
I suppose we could figure it out based on current address, but I can't think of another way...

**Comment by cmgiven** [comment]
We could possibly determine the RO that originated the appeal in VACOLS by using the PRIORLOC table. This probably won't have 100% accuracy, though.

```sql
select
    BFKEY,
    BFREGOFF,
    LOCSTOUT as ORIG_RO

from BRIEFF

join (
    select LOCKEY,
        min(LOCDOUT) DATE_ADDED

    from PRIORLOC

    where LOCSTOUT like 'RO__'

    group by LOCKEY
) MINLOC
    on MINLOC.LOCKEY = BFKEY

join PRIORLOC
    on PRIORLOC.LOCKEY = BFKEY
    and PRIORLOC.LOCDOUT = DATE_ADDED

where BFKEY in (...)
```

**Comment by laurjpeterson** [comment]
Related issue: #799

**Comment by laurjpeterson** [comment]
Related ticket: #799 - SPIKE: Can we change ROJ in VACOLS?
