### ISSUE TITLE
Remove AMA appeal

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8921]
LRP contacted us (back in December 😬 ) that we need to remove this appeal from the Board's docket. It is supposed to be a higher level review. 

https://appeals.cf.ds.va.gov/queue/appeals/ce13edc1-288e-4979-b405-592adc7ec052

**Comment by laurjpeterson** [comment]
We need a longer term solution for this, ticketed here: https://github.com/department-of-veterans-affairs/caseflow/issues/8824

**Comment by amprokop** [comment]
Deleted this appeal.
