### ISSUE TITLE
Schedule Hearing Task | Closed tasks with no hearings

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8923]
There are appeals with no hearings that have closed ScheduleHearingTasks. We need to:

1) Determine how many appeals this affects
1) Confirm that the affected appeals are still in 57 and can be scheduled for hearings
1) Figure out why this happened
1) Fix the bug

One example is the appeal with vacols id "2862527".

**Comment by oscarAtNava** [comment]
Apologies, hit the wrong button.
