### ISSUE TITLE
Decision Review: Update copy in modal for special issues not handled by Caseflow

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#893]
When a user select a Special Issue not currently handled by Caseflow and they click the Route Claim button (formerly the Create End Product button) they are served a modal telling them that the claim cannot be processed within Caseflow. The copy and button CTA of this modal need to be updated.

# Acceptance Criteria
1. Verify that the following Title and Subtext has been changed to the following:
**_Title_**

> Special Issue not handled by Caseflow

**_Subtext_**

> You have selected the Special Issue(s) category [Special Issues] that cannot be processed in Caseflow at this time.
>
>Please select Stop Processing and proceed to process this claim manually.
1. Verify that the all Special issues selected are listed in the subtext separated by a ",".

## Mockups
**_Current Modal:_**
<img width="541" alt="screen shot 2017-02-12 at 10 40 53 pm" src="https://cloud.githubusercontent.com/assets/4975959/22870345/5ee17cea-f174-11e6-9378-d87203a6c04f.png">

**_Change to:_**
<img width="502" alt="screen shot 2017-02-12 at 10 36 04 pm" src="https://cloud.githubusercontent.com/assets/4975959/22870354/722fee1c-f174-11e6-9950-8a28a27a373f.png">

**Comment by nikitarockz** [comment]
# Closing
This is no longer needed.  Removed from milestone.
