### ISSUE TITLE
enable :vbms_forward_proxy in UAT

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#8932]
Our production env has `:vbms_forward_proxy` true but UAT has it false.

It would be useful to turn it on in UAT so we surface API errors earlier.

**Comment by shanear** [comment]
This is more of a devops task. We should create the ticket in appeals-deployment

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/appeals-deployment/issues/1932
