### ISSUE TITLE
Hide duplicate organization tasks from case timeline

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8937]
When we [added task instructions to case timeline](https://github.com/department-of-veterans-affairs/caseflow/issues/8483) we accidentally started showing organization tasks in the case timeline again (these were previously hidden by the work done in #7943). Additionally, since we've decided to [show incomplete tasks that aren't actionable](https://github.com/department-of-veterans-affairs/caseflow/issues/8220) in the task snapshot instead of the case timeline area as recently planned, we should consider moving the construction of the set of tasks to display in the case timeline back to the backend (#8483 moved that logic to the frontend).

![image](https://user-images.githubusercontent.com/32683958/51717226-170efd00-200e-11e9-9f76-4acb9d5f289f.png)

## Acceptance criteria
* [ ] Do not display duplicate tasks in case timeline

**Comment by sneha-pai** [comment]
Sneha to follow up with Mark and Lowell.
Taking this off of Eric's plate

**Comment by tomas-nava** [comment]
MEDIUM ... some combination of back- and front-end work
