### ISSUE TITLE
EP Creation | Create End Product | Add Diary Note in VACOLS for Partial and Remands w/ Special Issues

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#894]
When an EP is created in Caseflow for a Partial Grant or a Remand with a Special Issues add a Diary Note in VACOLS to help route this claim.

Once the EP has been created and the VACOLS Location has been updated

1) Verify that the following note is added to the VACOLS Diary Note field:
>The BVA Full Grant decision dated 01/01/2017 for [John Doe], ID# [123456789], was sent to the ARC but cannot be processed here, as it contains [special issue category] in your jurisdiction. Please proceed with control and implementation of this grant.

# Note
Is there a character limit in VACOLS field Diary Note?  280 character limit.

**Comment by joofsh** [comment]
"VACOLS Notes" are really 1-time flash notices, they are stored in the ASSIGN table.

**Comment by joofsh** [comment]
TSKSTAT - pending when initially created
TSKRSPN - leave blank
TSKSTAT -  P  (pending) - Verify with Jed that this is okay
TSKDTC - Days to complete - ask lara how many days
TSKTFAS -  person assigned to do work - Can we safely assign it to the RO? Is this future proof?
TSKCLASS - (Active / Closed) - Should it be active?
TSKATCD - Reference to ACTCODE table. Ask Jed which one is appropriate for dispatching an appeal back to the RO due to special issue
TSKDASSN - Date assigned (date note is created)
TSKDTC - Days to complete diary note?  - Ask lara
TSKDDUE - Due date for diary note - Ask lara,  Ask Jed what happens after due date
TSKTOWN - owner of assignment  - Verify with Jed that this is creator
TSKDCLS - Date closed - Ask lara, verify with Jed what this does
TSKADUSR - Added by -  Current user's VACOLS staff ID
TSKADTM  - Current timestamp (use Oracle)
TSKMDUSR - Ask Jed do we need to fill this with the initial user creating the note
TSKMDTM - Ask Jed if we need to set it to current timestamp on initial create

**Comment by joofsh** [comment]
@lakohl @abbyraskin @cmgiven From a product perspective, do you have any suggestions on the following:

- What should the default "days to complete" the diary note be? Existing diary notes have a default ranging between 30 - 180 days. Something on the lower end sounds best to me?

- What should the due date be? Note: this does not have any actual affect in VACOLS, other than showing up in "overdue diaries" reports. Existing diary notes range between 30-120 days.

- Diary notes get assigned to a staff member, either a specific employee or an RO. Do we know what rules we want to use for determining which RO we assign the note?

**Comment by lakohl** [comment]
My thoughts below @abbyraskin feel free to chime in

- What should the default "days to complete" the diary note be? Existing diary notes have a default ranging between 30 - 180 days. Something on the lower end sounds best to me?

>30 days?

- What should the due date be? Note: this does not have any actual affect in VACOLS, other than showing up in "overdue diaries" reports. Existing diary notes range between 30-120 days.

>30 days?

- Diary notes get assigned to a staff member, either a specific employee or an RO. Do we know what rules we want to use for determining which RO we assign the note?

> assign to the RO or to the appeals coach?

- Dairy notes have a "Code" (a category). Do we want to use an existing Code (I can get you a list if needed)? If not, Jed mentioned we can add a new category if we want.  If we did that, what would the description text be?

>Can you say more about this? and/or provide a the list of codes?

**Comment by joofsh** [comment]
Here are the current 95 diary note categories:

1A - IME Request to Dean
D - Diary
R - Remand
B - Advance on Docket (VLJ)
A - Abeyance
H - Hearing
T - Thurber
O - Outside BVA
P - Pending Outside Transfer
S - Schedule Hearing
U - Video Hearing
C - Clear & Unmistakable Error
2 - VHA
3 - AFIP
1B - IME Request to Doctor
1 - IME Request
2A - VHA Request to VA Medical Center
3A - AFIP Request 
1C - IME 60 day letter sent
2B - VHA 60 day letter sent
3B - AFIP 60 day letter sent to appellant
4 - GC Opinion
4A - GC Opinion request sent to General Counsel
4B - 60 day letter sent
E - CUE Ltr to Rep (review file?)
VA EXAM
VA HR
VA OPT
MED OPINION
PRIV MED
EVID FM VET
646 REQ
SSOC SENT
SMR'S REQ
SSA MED
CONGR LTR
GW DEV
GW EXAM
HEARING REQ HO
HEARING REQ TB
TB LETR TO VET
DRO
USASCRUR
PTSD LTR TO VET
PTSD DEV SVC DEPT
VACO EXTRA SCHEDULAR
VACO RADIATION
DTNA RAD DEV
COWC
LG APPEAL
VAMC APPEAL
VR&C APPEAL
ATTY FEES
FOLDER AT BVA
OTHER
NOD RECEIVED
SENT TO AUTHORIZATION
NOT WELL GROUNDED
REACTIVATED APPEAL
DE NOVO - LETTER
G - Records Request
X -VA Exam Requested
Z - Stay in Effect
J - 903(b) notice letter sent
I - Request for info from appellant
N - NPRC-Svc Records Request
M - CAPRI Opinion Request Only
V - FOIA Office Review by Rep
K - Federal Circuit Appeal
L - Arguments on Motion for Recon
PMC APPEAL
MAPD
DUTY TO ASSIST
Y - Request to Rebuild Records
W - ECA Revocation
SECOND APPEAL
Q - Designation of Record
FORM 9 RECEIVED
1D - IME Payment
F - CAVC 90 day letter sent
5A - OMO M&A Director's Letter
1E - IME Overdue dean solicitation letter
5B - OMO Vice Chairman's letter
5C - OMO Fax Follow up
5D - OMO Temp file order, case misplaced VAMC
5E - OMO Telephone follow up
5F - OMO rebuilt file requested
5G - OMO E-mail follow up
5 - OMO
BROKER NOTES
AGENT ORANGE PRESUMPTIVE CONDITIONS
B1 - Advance on Docket (VSO)
READY TO RATE
READY FOR REVIEW
5H - OMO VLJ Review

**Comment by abbyraskin** [comment]
I will run these questions past the ARC appeals coach. My initial thoughts:

- What should the due date be? Note: this does not have any actual affect in VACOLS, other than showing up in "overdue diaries" reports. Existing diary notes range between 30-120 days.

> Can we set it to 15 days or is the minimum 30? Review/development is supposed to be initiated within 15 days according to the VBA manual.

- Diary notes get assigned to a staff member, either a specific employee or an RO. Do we know what rules we want to use for determining which RO we assign the note?

> My understanding is that today the notes are assigned to the RO (at least initially by ARC). I can ask about this tomorrow.

- Diary notes have a "Code" (a category). Do we want to use an existing Code (I can get you a list if needed)? If not, Jed mentioned we can add a new category if we want.  If we did that, what would the description text be?

> Likely Remand but I can check on this too. I think it's set automatically today.

**Comment by cmgiven** [comment]
Yeah, we might be able to answer all of these questions if we had a screenshot of how they fill this out in VACOLS today.

**Comment by joofsh** [comment]
Below is a screenshot of adding a diary note in VACOLS:
![vacols_diary_add](https://cloud.githubusercontent.com/assets/2256237/23236799/a24f375e-f928-11e6-9156-6c4adb1ac0bd.png)

**Comment by abbyraskin** [comment]
@joofsh the claim assistant I met with yesterday said he selects "Other" as the diary note code, but I would like to check with the coach today to see if this is the preferred code (seems generic to me!).

re: days, it currently defaults to 30 days and they don't change it, so let's keep it at 30.

**Comment by joofsh** [comment]
@abbyraskin awesome abby, thanks for the info. I'll hold off merging code until I hear back from you on the diary note code

**Comment by joofsh** [comment]
@abbyraskin @lakohl The example diary note above is 251 characters. With real special issues we'll definitely break the 280 character limit for diary notes. The existing diary notes are typically very short & casual. Is there a shorter version we can use to ensure it fits?

**Comment by joofsh** [comment]
Also, is there any UI for the user to see/edit this note. Or is this note entirely created behind the scenes?

**Comment by kierachell** [comment]
**PASSED**

Validated on `uat` with 4 different cases/types/SICs.
![remandnote](https://cloud.githubusercontent.com/assets/18075411/23761726/c1c480e0-04c1-11e7-855d-c96948f0d647.gif)
