### ISSUE TITLE
Cannot read property 'requestStatus' of undefined

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#8952]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3441/

- found all user logs for the user in kibana
- intake associated with error was a RampRefiling with status canceled & cancel reason being "veteran_clarification". 

I think the error is happening here in addIssue.jsx

`const requestState = intakeData.requestStatus.completeIntake || intakeData.requestStatus.requestIssuesUpdate`

But that would mean there's no intake data which seems unlikely.

Didn't see another occurrence of this error, and user was able to process a cancelation.

**Comment by leikkisa** [comment]
I am closing this since Jia didn't see another instance of it, and this case was ultimately successful.
