### ISSUE TITLE
SwitchOnForm does not have a mapping for current form selection: 'appeal'

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#8953]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3439/

* looking at kibana logs, i think the user reloaded and was able to complete the intake.
* not sure why this happened since the switch on form does handle appeal types. https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/intake/pages/completed.jsx#L21

**Comment by jiahuang** [comment]
Another error occurred for not being able to find supplemental claim https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3867/

**Comment by jiahuang** [comment]
Error also occurred for not being able to find a hlr: 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3961/

**Comment by shanear** [comment]
We should probably check if this error still occurs

**Comment by alisan16** [comment]
Doesn't look like this error has occurred recently. Closing.
