### ISSUE TITLE
IHP-writing VSO user admins

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8959]
Make the following VSO POCs user management admins. These will be the first users that we introduce to the user management functionality for VSOs.

FIRST | LAST | MI | ORGANIZATION | TITLE | EMAIL
-- | -- | -- | -- | -- | --
Cristle | Maddox |   | American Legion (AL) | Administrative Assistant | Cristle.Maddox@va.gov
Racshell | Jones |   | American Legion (AL) | Administrative Assistant | Racshell.Jones@va.gov
Harvey | Taylor | L | American Legion (AL) | Team Trainer | Harvey.taylor2@va.gov
Clayton | Klemm | C | American Legion (AL) | Veterans Claims Specialist | w.klemm@va.gov
Larry | Blosser | L | American Legion (AL) | Veterans Claims Specialist | Larry.Blosser@va.gov
Sherry | Scott | S | American Legion (AL) | Veterans Claims Specialist | Sherry.scott3@va.gov
Eric | Taylor |   | American Red Cross (ARC) | Appeals Representative | Eric.Taylor@va.gov
Ronald | Williams | C | American Red Cross (ARC) | Appeals Representative | bvarwilliams@va.gov
Jose | Garcia | M | Catholic War Veterans (CWV) | Appeals Representative | josegarcia4@sbcglobal.net
Roy | Spicer |   | Disabled American Veterans (DAV) | DAV Representative | Roy.Spicer@va.gov
Thomas | Wendel |   | Disabled American Veterans (DAV) | DAV Representative | THOMAS.WENDEL@va.gov
Gerard | Taylor |   | Maryland Department of Veterans Affairs (MDVA) | Appeals Chief | gerard.taylor@va.gov
Arthur | Coleman III |   | Military Order of the Purple Heart (MOPH) | National Service Director | arthurcolemaniii@purpleheart.org
Britany | Thomas |   | Military Order of the Purple Heart (MOPH) | Executive Assistant | britany.thomas@va.gov
Alexis | Ivory |   | National Veterans Legal Services Program (NVLSP) | Appeals Representative | alexis@nvlsp.org
Michael | Spinnicchia |   | National Veterans Legal Services Program (NVLSP) | Appeals Representative | michaelc@nvlsp.org
Richard | Spataro |   | National Veterans Legal Services Program (NVLSP) | Appeals Representative | richard@nvlsp.org
Michelle | Ramos Domingue |   | Navy Mutual Aid Association (NMAA) | Veteran Service Program Manager | mdomingue@navymutual.org
Craig | Cressman | D | Navy Mutual Aid Association (NMAA) | Director of Education and Veteran Services | ccressman@navymutual.org
Jamie | Rudert |   | Paralyzed Veterans of America (PVA) | Associate General Counsel | JamieR@pva.org
Chance | Sizemore |   | Veterans of Foreign Wars (VFW) | Appeals Consultant | Chance.Sizemore@va.gov
Dianne | Winston |   | Veterans of Foreign Wars (VFW) | Appeals Consultant | Dianne.Winston@va.gov
George | Sheets |   | Veterans of Foreign Wars (VFW) | Appeals Consultant | George.Sheets@va.gov
Isabel | Hicks |   | Veterans of Foreign Wars (VFW) | Appeals Consultant | Isabel.Hicks@va.gov
Ivory | Hicks |   | Veterans of Foreign Wars (VFW) | Appeals Consultant | Ivory.Hicks@va.gov
Jeffrey | Wishneski | P | Veterans of Foreign Wars (VFW) | Appeals Representative | Jeffrey.Wishneski@va.gov
Larry | Arrington |   | Veterans of Foreign Wars (VFW) | Appeals Consultant | Larry.Arrington@va.gov
Sylvester | Jones | C | Veterans of Foreign Wars (VFW) | Appeals Section Supervisor | Sylvester.Jones@va.gov
Alec | Ghezzi | U | Vietnam Veterans of America (VVA) | Senior Managing Attorney (BVA) | aghezzi@vva.org
Alexandra | Rigby |   | Vietnam Veterans of America (VVA) | Appeals Representative | alexandra.rigby@va.gov
Aviana | Cooper |   | Vietnam Veterans of America (VVA) | Appeals Representative | Aviana.cooper@va.gov
Felicia | Mullaney |   | Vietnam Veterans of America (VVA) | Deputy Director | Felicia.Mullaney@va.gov
Heather | Olson |   | Vietnam Veterans of America (VVA) | Appeals Representative | heather.olson@va.gov
Joshua | Leach | D | Vietnam Veterans of America (VVA) | Appeals Representative | joshua.Leach2@va.gov
Michael | Garza |   | Vietnam Veterans of America (VVA) | Appeals Representative | michael.garza@va.gov
Mylee | Sabarre |   | Vietnam Veterans of America (VVA) | Appeals Representative | mylee.sabarre@va.gov
Alicia | Stone |   | Wounded Warrior Project (WWP) | Senior National Service Officer, Appeals | astone@woundedwarriorproject.org
Claudia | Belk | B | Blinded Veterans Association  (BVA) | Chief of Veteran Services | claudia.belk@va.gov
Patrick | Johnson | L | Blinded Veterans Association (BVA) | Appeals Officer | Patrick.johnson@va.gov
Maria | Ingegneri | J | Blinded Veterans Association (BVA) | Veteran Service Officer | maria.ingegneri@va.gov

**Comment by laurjpeterson** [comment]
@lowellrex - I've added the IHP-writing POCs. Ready wheneva.

**Comment by lowellrex** [comment]
User admins won't have any special abilities until after #8170 is completed. #8170 probably won't be completed until the end of this sprint so we'll tackle these changes next sprint if that works for you!

**Comment by laurjpeterson** [comment]
Yep, next sprint works!

**Comment by laurjpeterson** [comment]
@lowellrex - can you give me the access I need to be able to add these admins? I believe it's the same access as Marvo.

**Comment by araposo-tistatech** [comment]
@araposo-tistatech need to inquire with John & Mike if this is still the user admin list.
