### ISSUE TITLE
Add IHP tasks for all PVA cases

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8960]
PVA can submit IHPs for all docket types (unlike other IHP-writing VSOs who can only submit IHPs for Direct Review and Evidence Submission)

## AC
- IHP tasks are added for all PVA cases, regardless of docket type

**Comment by lowellrex** [comment]
Let's explore storing this information in the database. Perhaps in a dedicated `hearing_docket_ihp_writing_vsos` table where the existence of a record in that table (joining to the organizations table) indicates that the VSO writes IHPs for all dockets.

**Comment by lowellrex** [comment]
MEDIUM - Would likely need to create the IHP task in the [initial RootTask creation path](https://github.com/department-of-veterans-affairs/caseflow/blob/4d9fd1c2d05f62e715b9697185ca80195fa75846/app/models/tasks/root_task.rb#L100).

**Comment by lowellrex** [comment]
While doing the work on this, keep in mind that we will need to differentiate between "field" VSOs and IHP-writing VSOs at some point (for the work described by ticket #8961).
