### ISSUE TITLE
Research | Foreign Veteran Case

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8964]
More research needed for Veterans that live abroad (and not in the Phillippines). 

- We are thinking we'll create an automated task 
- Need to figure out flow for scheduling the Veteran 
- Perhaps an "unassigned" RO in the Schedule Veteran view 
- Perhaps this is managed in the schedule Veteran queue

**Comment by ShellySmithDSVA** [comment]
Closing this task as research is complete. See #9758 for design.
