### ISSUE TITLE
Intake VACOLS Opt-in | Error message is confusing in specific ineligibility scenario

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8967]
When trying to add a VACOLS opt in issue, I'm getting an ineligibility error in the screenshot below:
<img width="1552" alt="screenshot 2019-01-25 15 27 09" src="https://user-images.githubusercontent.com/1596259/51778314-e2ef1700-20b5-11e9-91e3-fda6549907d2.png">

However, the issue is not eligible because of this edge case:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/issue.rb#L213

The error message is misleading here. Not sure what we should have it say though.

see https://github.com/department-of-veterans-affairs/caseflow/issues/8081 for more discussion on this

**Comment by msj0nes** [comment]
Ticket closure. Not prioritized
