### ISSUE TITLE
Universal case title wrapping

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8968]
Is this wrapping as intended?

![image](https://user-images.githubusercontent.com/27704093/51779226-04f79200-20d4-11e9-88f6-1a71d735f82c.png)

**Comment by eric-nava** [comment]
Wasn't a part of the decisions in the header, but this because the VLJ support staff name is longer than expected, or because there's extra padding around the Edit decision document ID button?

**Comment by laurjpeterson** [comment]
It could also be because of the `View Failed to load docs` error, too.  Just a hunch.
