### ISSUE TITLE
Update `uncertify` and `test/setup` to handle more than one appeal

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#897]
connects [#373](https://github.com/department-of-veterans-affairs/appeals-deployment/issues/373)

In order to properly test scaled up Certification, we need to be able to handle multiple test appeals; QA repo has a list of Certifications used in `uat` which we can use for our test cases.
- [ ] Update `setup_controller` to handle different appeals
- [ ] Update `test/setup` to take a `BFKEY` as input for `uncertify`
- [ ] Validate that entered `BFKEY` is in the list provided on QA repo (to avoid messing up other data)

**Comment by amprokop** [comment]
I don't see `setup_controller`. Where does this live?
