### ISSUE TITLE
Hide case from completed tab if I have any active tasks for that case

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8973]
Currently, if I have there is a case with a task attached to it that I have completed and one that I still in progress, that case will show up twice in my queue; once in the "in progress" tab and once in the "completed" tab. This ticket exists to hide the case from the completed tab so it does not appear as if all my work for this case has been completed.

One example of this situation is if there are completed `AttorneyTasks` and current `AttorneyRewriteTasks`, the case will show up in both the _Assigned_ and _Completed_ tabs on the attorney's queue.

## To do
* [ ] Decide how we want to display cases with tasks that are both on hold and assigned to the current user. Should those show up in both tabs?

## Acceptance criteria
* [ ] Hide cases from the completed tab if there are other incomplete tasks for that case

**Comment by araposo-tistatech** [comment]
Not something we want to implement as the in progress and completed tabs relate to tasks and not the entire appeal.
