### ISSUE TITLE
Only fetch document count for appeal if we don't have it

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8981]
Currently, we fetch the document count for an appeal [every time the `AppealDocumentCount` component is loaded](https://github.com/department-of-veterans-affairs/caseflow/blob/eb1928df757dc17c689b9651285af3bbc244aaea/client/app/queue/AppealDocumentCount.jsx#L19) on the front-end. We do this because when we load the component in the queue table view we use the value that we've cached to the Caseflow database and when we load the component on the case details page we request the latest document count VBMS (which we expect to take longer to respond and therefore don't do when we load the queue table view). We can prevent some of these requests if we use the value we've cached in the redux store whenever we load the queue table view and only make the request on the case details page when the most recent value in the redux store does not come from VBMS.

## Acceptance criteria
* [ ] Fetch document count if the document count does not exist in the redux store
* [ ] Fetch document count when visiting the case details page if value in redux store does not come from VBMS
* [ ] Do not fetch document count if value in redux store comes from VBMS

**Comment by hschallhorn** [comment]
Don't think we'd need much more than a boolean in the store indicating if the store's document_count and new_documents came from VBMS. Want me to dig into this?

**Comment by lowellrex** [comment]
That approach makes sense to me! As for when we tackle this, I'll defer to @aroltsch about when to prioritize this work.
