### ISSUE TITLE
Judge Hearing Details Read Only View

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#8986]
## User Stories
As a judge or attorney, I need to be able to see the hearing details for a case, but do not need to edit or change the information. 

## Mocks
See page 34 of the following InVision
https://va-gov.invisionapp.com/share/F6PQEGF2BTJ#/342942847_HD_Judge_Read_Only_Text_Only

## Acceptance Criteria
This change eliminates the gray boxes for the judge view of Hearing Details and changes everything to a a "read only" view. 
- [ ] Verify all fields are now in "read only" mode, eliminating the nulled boxes for drop down and date information. 
- [ ] Verify all previously nulled information shows as text
- [ ] Verify check boxes and radio buttons are still displayed with information, but in nulled mode.

**Comment by laurjpeterson** [comment]
Seems like Styleguide work, doesn't need to be tied to the hearings team to do. Could potentially be beneficial if we rework Hearing Worksheets to have a read-only, print, and editable view.

**Comment by pshahVA** [comment]
@nicholer, I'm going to close this.
no user requirement and not in long term priority.
