### ISSUE TITLE
CO Updates | Update prod records

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8989]
There are several CO records created later than 1/1 that are not associated with a Caseflow hearing day. The hearing coordinator was still able to create CO rows in VACOLS and add CO hearings that way. Those few records can be found with a query like `VACOLS::CaseHearing.where(hearing_type: "C", hearing_date: later than 1/1, vdkey: nil)`. The vdkeys should be updated to the corresponding Caseflow hearing day

**Comment by oscarAtNava** [comment]
Results of query and aggregation.
hearings = VACOLS::CaseHearing.where("trunc(hearing_date) > ? and folder_nr not like 'VIDEO%' and hearing_type = 'C' and vdkey is null", "2018-12-31")

hearings.length
=> 17
hearings.group(:hearing_date).count
=>{
Thu, 10 Jan 2019 09:00:00 UTC +00:00=>3, 
Mon, 07 Jan 2019 09:00:00 UTC +00:00=>3, 
Mon, 28 Jan 2019 13:00:00 UTC +00:00=>2, 
Wed, 23 Jan 2019 13:00:00 UTC +00:00=>1, 
Mon, 07 Jan 2019 13:00:00 UTC +00:00=>1, 
Thu, 24 Jan 2019 13:00:00 UTC +00:00=>2, 
Tue, 08 Jan 2019 13:00:00 UTC +00:00=>3, 
Mon, 28 Jan 2019 09:00:00 UTC +00:00=>2
}

Hearing Days in Caseflow:
hearing_day = HearingDay.where("scheduled_for between ? and ? and request_type = 'C'", "2018-12-31", "2019-01-29")
hearing_day.select(:scheduled_for, :id)
[
#<HearingDay id: 1, scheduled_for: "2019-01-03">,
#<HearingDay id: 2, scheduled_for: "2019-01-07">, 
#<HearingDay id: 3, scheduled_for: "2019-01-08">, 
#<HearingDay id: 4, scheduled_for: "2019-01-09">, 
#<HearingDay id: 5, scheduled_for: "2019-01-10">, 
#<HearingDay id: 6, scheduled_for: "2019-01-14">, 
#<HearingDay id: 7, scheduled_for: "2019-01-15">, 
#<HearingDay id: 8, scheduled_for: "2019-01-16">, 
#<HearingDay id: 9, scheduled_for: "2019-01-22">, 
#<HearingDay id: 10, scheduled_for: "2019-01-23">, 
#<HearingDay id: 11, scheduled_for: "2019-01-24">, 
#<HearingDay id: 12, scheduled_for: "2019-01-28">,
#<HearingDay id: 13, scheduled_for: "2019-01-29">
]

**Comment by sharonwarner** [comment]
Looks good!

**Comment by oscarAtNava** [comment]
Commands executed. Closing ticket.
