### ISSUE TITLE
API: Events for SCs and HLRs

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/caseflow#8999]
Each `supplementalClaim` and `higherLevelReview` should have an array of `events`. Each event has a `type` and a `date`.

```
"events": [
  {
    "type": "sc_request",
    "date": "2019-02-19"
  },
  {
    "type": "sc_decision",
    "date": "2019-06-01"
  }
]
```

### `supplementalClaim` events

* `sc_request`: The receipt date of the Supplemental Claim.
* `sc_decision`: The date the Supplemental Claim was decided (probably the date the EP was closed).
* `sc_other_close`: If the Supplemental Claim was closed for any other reason, the date it was closed.

### `higherLevelReview` events

* `hlr_request`: The receipt date of the Higher-Level Review.
* `hlr_decision`: The date the Higher-Level Review was decided, provided there were no DTA errors.
* `hlr_dta_error`: If there were DTA errors, we instead use this event to record the date the original HLR EP was closed.
* `dta_decision`: And then we use this event to record the date the HLR DTA Error EP was closed, the date the decision was actually mailed out by VBA.
* `hlr_other_close`: If the Higher-Level Review was closed for any other reason, the date it was closed.

**Comment by mc-usds** [comment]
PR merged
