### ISSUE TITLE
Intake | Foreign Address intake issues

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9003]
AMO reporting issues intaking an appeal where the appellant has a foreign address in VBMS/ Corp. Caseflow is requiring a city/ state when none should be necessary.

Details with PII are available on request.

**Comment by leikkisa** [comment]
Confirm whether this has already been addressed since September.

**Comment by leikkisa** [comment]
There's a prod example in 1password

**Comment by jiahuang** [comment]
@shanear I can't find this example in the dsva 1pw. Is the example stored in another vault?

**Comment by steve-gov** [comment]
Documents > "EMAIL: Foreign Address Errors"

**Comment by steve-gov** [comment]
Got it, I've passed that along and will hold this open for another few days. blocked till further info.
