### ISSUE TITLE
Positioning of H badge in case search

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9015]
![image](https://user-images.githubusercontent.com/27704093/51873178-2b166f80-232a-11e9-9f48-b456f9d84a6a.png)

### AC

- [ ] adjust H badge to line up with Appeal type badge, docket no., appellant's name

**Comment by joeyyang** [comment]
How should it be positioned in this case?

**Comment by geronimoramos** [comment]
This looks fixed? ![image.png](https://images.zenhubusercontent.com/5d080bf47b35df3ba36deb06/7bf7f2dd-71ce-4923-8d62-eccf894bbec1)
from demo at least
