### ISSUE TITLE
Sort case search results

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9016]
When a BVA employee searches for Veterans, they want to easily scan through all Veterans' appeals, so they can quickly find which appeal to work on.

This is a low priority, nice to have clean up ticket.

## AC
- Case search results are sorted from newest (top) to oldest decision date (bottom). If an appeal hasn't been decided yet, that appeal should be at the top of the list

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | ||||
2 | |||||||
3 | |
5 | 
8 | 
```

Why 1?
- `order_by`

Why 2?
-  Relatively straightforward
-  Add tests

**Comment by Jeremy1026** [comment]
BEFORE|AFTER
<img width="800" alt="image" src="https://user-images.githubusercontent.com/2308626/113711933-8505e300-96b3-11eb-8042-f16e3456a942.png">
 | 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/2308626/113711899-7b7c7b00-96b3-11eb-9670-f8113f8dc318.png">
