### ISSUE TITLE
Bug | Blank issues appear on Add Issues screen, and can be selected

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9017]
Observed in UAT on file `123458316`:
1. Search for Veteran
2. Click `Add Issue`
3. First issue under "Past decisions from 11/12/2018" has no corresponding text with its radio button.
4. Select the blank issue and click `Add this issue`
5. Issue appears on the confirmation screen with no text before the `is ineligible...` copy
6. Click `Add Issue`
7. Issue is no longer selectable, text is listed as `null`

**Comment by steve-gov** [comment]
<img width="902" alt="screen shot 2019-01-28 at 3 29 56 pm" src="https://user-images.githubusercontent.com/25468689/51873487-352c7400-2312-11e9-9d5e-debefcc009fe.png">
---
<img width="727" alt="screen shot 2019-01-28 at 3 28 56 pm" src="https://user-images.githubusercontent.com/25468689/51873488-365da100-2312-11e9-948f-17443dd81b52.png">

**Comment by jiahuang** [comment]
Looked into this, the blank issue is coming from a decision issue:

```
DecisionIssue id: 4, disposition: "Granted", description: nil, promulgation_date: nil, profile_date: nil, participant_id: "600233671", rating_issue_reference_id: nil, decision_text: nil, decision_review_type: "SupplementalClaim", decision_review_id: 152, benefit_type: "compensation", end_product_last_action_date: "2018-11-12"
```

**Comment by shanear** [comment]
yeah this is due to an empty decision issue:
```
  id: 4,
  disposition: "Granted",
  description: nil,
  promulgation_date: nil,
  profile_date: nil,
  participant_id: "600233671",
  rating_issue_reference_id: nil,
  decision_text: nil,
  decision_review_type: "SupplementalClaim",
  decision_review_id: 152,
  benefit_type: "compensation",
  end_product_last_action_date: Mon, 12 Nov 2018,
  diagnostic_code: nil>,
```

This was fixed by https://github.com/department-of-veterans-affairs/caseflow/issues/8518, but there is still some corrupted data in UAT
