### ISSUE TITLE
Show canceled hearing requests in Case details

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9020]
Sometimes, Veterans choose to withdraw their AMA hearing request. 
- We think this will be operationalized by a user cancelling the `ScheduleHearingTask`. 
- We think users need to add a note when they cancel the hearing schedule task. The existing instructions field can likely be borrowed for these notes.
- We think we'd like to show the cancelled hearing schedule task in Case Timeline and in the Hearing section of Case Details.

Next step is to design what a withdrawn hearing request looks like in Case Details.

**Comment by sneha-pai** [comment]
next steps: Sneha to follow up with Shelly and Phillip on what actions have been taken here.

**Comment by laurjpeterson** [comment]
PR that adds cancel task to actions dropdown - https://github.com/department-of-veterans-affairs/caseflow/pull/9499

**Comment by ShellySmithDSVA** [comment]
Adding Meredith to this task. Is there any further work needed from our team to address this ticket?

**Comment by laurjpeterson** [comment]
Tagging folks for visibility again - @Chingujo, take a look at how Allyce designed canceled hearing requests in Case Timeline. What do you think? https://app.mural.co/t/workqueue2001/m/workqueue2001/1556035219909/9317bc82fd2cf504e3e8539a172a33750c406a0d

And @Chingujo - do you know if we already update Case Details with the canceled hearing disposition for AMA appeals?

cc: @sneha-pai
