### ISSUE TITLE
Bug: Veteran scheduled, but showing up in list to be scheduled

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9025]
Sal reported 1-28-19 that there is a Veteran that has been scheduled that is still showing up in the list of Veterans to be scheduled.  Sal emailed Veteran URL on 1-29-19.

**Comment by MeredithStewart** [comment]
@oscarAtNava -- This might have something to do with the fact that this Veteran has been postponed. I think we had a problem with the postponements and the schedule veteran tasks.   

https://appeals.cf.ds.va.gov/queue/appeals/2973495#hearings-section

**Comment by oscarAtNava** [comment]
@MeredithStewart Could you confirm for me if the Veteran has a hearing? When I query the database in production for appeal id 2973495 the only hearing I get is one of type F from 2015.

**Comment by MeredithStewart** [comment]
In the Hearings tab, we see two hearings. Hearing 1 is Central, postponed on 2/11/19. Hearing 2 is Central, Disposition = null (so, scheduled), for 3/25/19.

**Comment by oscarAtNava** [comment]
This case is in location 36 and has a hearing scheduled for March. I have asked the user to verify if the case still shows as awaiting scheduling in the Assign Hearings page. It may have been a temporal item.
