### ISSUE TITLE
Manually cancel dispatched LegacyAppeals that are still showing up in VLJ Support Staff queues

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9026]
VLJ Support Staff have been complaining for a few weeks that tasks related to dispatched appeals are still showing up in their queue table views. This ticket exists to determine why this is happening and chart a course to resolution of this issue.

Three VACOLS IDs for appeals affected by this are 3626725, 3206295, and 3576330.

## Current AC
- [ ] Identify all cases that have been dispatched but have open Caseflow tasks
- [ ] Change all open Caseflow tasks' statuses to be `completed`

## Previous Acceptance criteria
* [ ] Determine why tasks related to dispatched LegacyAppeals are still showing up in VLJ Support Staff queues
* [ ] Write tickets to address code bugs causing this issue
* [ ] Correct production data (mark tasks complete, etc.) to address the issue as needed.

**Comment by lowellrex** [comment]
The problem with one of these cases (VACOLS ID 3576330) was not that it was worked in VACOLS when it was checked out to the Caseflow location (as we first hypothesized), but rather that the `ColocatedTask` assigned to the VLJ Support Staff organization was completed when we expected the child `ColocatedTask` assigned to an individual person to have been completed. This was caused by a confluence of two major factors:

1. The application [only displaying a single task](https://github.com/department-of-veterans-affairs/caseflow/blob/b80a5838aaaf4034ab9c66eaa373e186f4ab0090/client/app/queue/TaskSnapshot.jsx#L280) in the Task Snapshot area even if there were more than one task with available actions for the appeal. This problem was addressed by a change to the code on 27 December--not deployed until 2 January--that [showed all tasks with available actions](https://github.com/department-of-veterans-affairs/caseflow/pull/8326/files#diff-c6245bd098c838610d8b6f4dbce23d56R275) in Task Snapshot instead of just one.
1. The way the application selected which single task to display was indeterminate and resulted in the `ColocatedTask` assigned to the VLJ Support Staff organization being displayed instead of the child `ColocatedTask` assigned to an individual person. As a result, VLJ support staff using Caseflow unknowingly took action on the organizationall-assigned task instead the individually-assigned task. This returned the case to the assigning attorney and allowed it to continue on to dispatch, but the individually-assigned case remained visible in their individual queues.

Factor 2 above affected 9 total appeals (1 of which was the appeal with VACOLS ID 3576330). Postgres [does not guarantee the order of results](https://www.postgresql.org/docs/current/queries-order.html) from the database and two things we did encouraged the organizationally-assigned `ColocatedTask` to sort before the individually-assigned task.

> If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on.

All of the individually-assigned `ColocatedTask`s were updated after the parent (organizationally-assigned) `ColocatedTask`s were created which may result in the task's location on disk changing (for example, when the `placed_on_hold_at` field changed from null to a datetime value or the `status` field changed string lengths). It is unlikely that the organizationally-assigned `ColocatedTask`s would have had any fields change during this time, so it is possible that this resulted in a table scan sorting the individually-assigned `ColocatedTask`s before the organizationally-assigned ones.

```ruby
rails c> orphan_task_parents = ColocatedTask.where(status: "completed", assigned_to: org).select { |t| t.children.any? { |ct| "completed" != ct.status } }
rails c> orphan_task_parents.count
# 9
rails c> orphan_task_parents.select { |t| t.children.first.updated_at > t.created_at }.count
```

### Steps to recovery
* [ ] Update the individually-assigned `ColocatedTask`s to have the same status as their parent tasks.
* [ ] Prevent this ordering bug from recurring.

**Comment by lowellrex** [comment]
The other 2 appeals (IDs 3626725 and 3206295) are active in Caseflow. @laurjpeterson can you check to see if the VLJ support staff is having trouble selecting an action for these appeals in Caseflow? Perhaps they are running into an error when we attempt to update VACOLS as a result of the action they take?

**Comment by lowellrex** [comment]
In order to update the tasks to have the same status as their parent tasks we can run the following commands:

```ruby
rails c> orphan_task_parents = ColocatedTask.where(status: "completed", assigned_to: org).select { |t| t.children.any? { |ct| "completed" != ct.status } }
rails c> orphan_task_parents.count
# 9
rails c> orphan_task_parents.map { |t| t.children.count }.uniq
# [1]
rails c> orphan_task_parents.map { |t| t.children.first.type }.uniq
# ["ColocatedTask"]
# Since each parent task only has one child we can just update the single child task.
rails c> orphan_task_parents.each { |t| t.children.first.update!(status: t.status) }
```

**Comment by laurjpeterson** [comment]
Delayed - emailed Randy to ask the above questions today.

**Comment by laurjpeterson** [comment]
Workaround for this will be to ask VLJ Support users to cancel their Legacy tasks so they are removed from their queue. This workaround would remove the need for us to spend engineers' time updating these stale appeal's statuses (to completed). However, it will affect the reporting that VLJ Support are doing (Looker report contains both legacy and AMA cases and we're relying on the "completed" status).

**Comment by lowellrex** [comment]
MEDIUM. Will need to do this manually in the database to avoid running [the `after_update` hook on `ColocatedTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/7637541741a56cf4529f62ac46b63d0595b4416a/app/models/tasks/colocated_task.rb#L7). We should only need to run this statement once because Jed updated VACOLS to no longer allow folks to charge cases with the `CASEFLOW` location to other locations in VACOLS.

**Comment by lowellrex** [comment]
Create a way to mark `ColocatedTask`s complete in Caseflow without affecting VACOLS (avoid the [`after_update` hook on `ColocatedTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/7637541741a56cf4529f62ac46b63d0595b4416a/app/models/tasks/colocated_task.rb#L7) that normally runs). Investigate if we can just change the default behaviour of marking a task complete to avoid updating the VACOLS location if the VACOLS location is not "CASEFLOW" and/or if the case has already been dispatched.

Still a MEDIUM.

* [ ] In the rails console, update the affected cases and then pass off the onus for doing any new ones to the VLJ support staff.

**Comment by lowellrex** [comment]
Updated the 6 `ColocatedTask`s that had been completed but not recognized as such in Caseflow. @laurjpeterson can we check with Randy to make sure all of these tasks have disappeared from the VLJ support staff queue?

_Record of what we did:_
```ruby
rails c> org = Colocated.singleton
# Let's search for active instead.
rails c> orphan_task_parents = ColocatedTask.includes(:children).inactive.where(assigned_to: org).select { |t| t.children.active.any? }
rails c> orphan_task_parents.count
# 6
rails c> incomplete_kids = orphan_task_parents.map { |t| t.children.active }.flatten
rails c> incomplete_kids.count
# 6

rails c> orphan_task_parents.pluck(:id)
# [1536, 1546, 1557, 1576, 1406, 1578]
rails c> incomplete_kids.pluck(:id)
# [760, 831, 734, 1177, 1407, 1179]

rails c> incomplete_kids.each { |t| t.update_columns(status: Constants.TASK_STATUSES.completed) }

# Confirm that we didn't change the VACOLS location for any of these.
rails c> first_parent = orphan_task_parents.first
rails c> first_parent.assigned_by.vacols_roles
# ["attorney"]
# This task was assigned by an attorney (as expected). If the task status update cascaded
# then the location would have been set to this attorney's CSS ID.

rails c> first_parent.appeal.location_code
# "99"
# Still in history status! Perfect!
```

**Comment by laurjpeterson** [comment]
@lowellrex - unfortunately I don't think this fixed all of the cases for Randy. I impersonated him last week, and he still had a legacy case with a task waiting 140+ days.

**Comment by lowellrex** [comment]
> @lowellrex - unfortunately I don't think this fixed all of the cases for Randy. I impersonated him last week, and he still had a legacy case with a task waiting 140+ days.

Can we get the URL of the case details page for that task so we can dig into what's happening there?
