### ISSUE TITLE
Non Comp | Process document request task flow

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9034]
This is the flow used to handle and close out tasks created in https://github.com/department-of-veterans-affairs/caseflow/issues/8674

requires https://github.com/department-of-veterans-affairs/caseflow/issues/8674

## Acceptance Criteria
When a user clicks on a Document request task in a non-comp screen,
- they should be routed to a page that looks like the mock below.
- the "Confirm" button should be disabled until the "I certify this record..." checkbox is checked
- when the "Confirm" button is clicked. The tasks should be completed and recorded. (similar toan effectuation task as described in https://github.com/department-of-veterans-affairs/caseflow/issues/8299) The user should be routed back to the non-comp in progress screen.

![non-comp_recordreq](https://user-images.githubusercontent.com/11700545/51858008-84f64580-22e8-11e9-991e-a84c8a420ccb.png)

## Copy
Title - Request to send Veteran record to the Board
Description - The Veteran/appellant has filed a Notice of Disagreement at the Board of Veterans' Appeals. In order to decide that appeal, the Board will need the complete records from [BUSINESS LINE]. Please take necessary steps to send this record to the Board.
Mail to: [ADDRESS]

[425 I St NW, Washington DC, 20001.]
^^ Place holder

**Comment by steve-gov** [comment]
Validated: 

![screencapture](https://user-images.githubusercontent.com/25468689/52018489-730ad300-249f-11e9-9dd1-6958e8a46f9c.gif)
