### ISSUE TITLE
Improve names for 3 task actions-related functions

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9055]
With the completion of PR #9014 we now have 3 functions related to task-action availability on the `Task` model named [`actions_allowable?`](https://github.com/department-of-veterans-affairs/caseflow/blob/1e3b6f2f314d299ad6672a9ad9cee87f34305981/app/models/task.rb#L59), [`actions_available?`](https://github.com/department-of-veterans-affairs/caseflow/blob/1e3b6f2f314d299ad6672a9ad9cee87f34305981/app/models/task.rb#L53), and [`available_actions`](https://github.com/department-of-veterans-affairs/caseflow/blob/1e3b6f2f314d299ad6672a9ad9cee87f34305981/app/models/task.rb#L26). It is not immediately clear at a glance how those are different and what they do. This ticket exists to clarify those functions' purpose by (at a minimum) renaming them to be clearer. If during the process of the renaming we discover that there should be an accompanying refactor, we'll consider that as well.

## Acceptance criteria
* [ ] Names for these 3 functions more clearly communicate their... function

**Comment by hschallhorn** [comment]
```
1 | ||||
2 | |||||||
3 | |
5 | 
8 |
```

Could be a larger ticket as these three functions appear in a lot of files.  Coming to a consensus on the naming may prove to be a bigger lift than a simple find and replace. Renaming may create a refactor. After a very fruitful discussion on the reasoning behind higher estimations, votes were change to address these concerns.
