### ISSUE TITLE
Case timeline displays attorney and judge tasks out of order

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9070]
<img width="776" alt="screen shot 2019-01-30 at 2 12 07 pm" src="https://user-images.githubusercontent.com/40216950/52006676-b9116800-249a-11e9-8361-bd3f44499654.png">

This is a screenshot of Case timeline from a Veteran's case. The judge and attorney tasks are out of order. The judge task should come after the attorney task, per the dates on each task.

**Comment by lowellrex** [comment]
@allyceh Can you send along the URL of this case details page so we can investigate if this is an issue localized to just this case or whether it affects all cases.

**Comment by lowellrex** [comment]
UUID for this case is `70283573-fdbc-46ca-9d9a-09d2791cf118`.
