### ISSUE TITLE
Non Comp | Quick copy change | Update record request task address copy when final address is approved

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9072]
Update the FPO copy with an actual delivery address on the page in https://github.com/department-of-veterans-affairs/caseflow/issues/9034. 

(The address is a constant: https://github.com/department-of-veterans-affairs/caseflow/pull/9067/files#diff-c8017822e4e861c98a8107fe726e3497R16)

Assigning to Carola, who can comment with the approved address when received, and then unassign for dev.

**Comment by carolaponce** [comment]
In communications with Rachel Sauter, she's confirming the correct address with an admin at the board.

**Comment by leikkisa** [comment]
@carolaponce Do we know if Rachel has confirmed the address?

**Comment by carolaponce** [comment]
Yes she did.  Finally getting back to confirm that the 425 I Street address (not the PO box) should be used for paper files. And they should be sent to the attention of Case Review and Evaluation Branch


We can change the address info to:
421 I St NW Washington, DC 20001
Attention: Case Review and Evaluation Branch

**Comment by leikkisa** [comment]
![Screen Shot 2019-06-03 at 12.15.14 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/06964c25-b240-4e12-b49a-1054a54f5a0e)
