### ISSUE TITLE
Master ticket: style guide improvements and bug fixes

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#909]
Current to-do list:
- [x] Fix modal close feature bugs
- [ ] Examine code syntax highlighter options:
* Rouge (ruby gem): http://rouge.jneen.net/
* Highlight.js (npm package): https://highlightjs.org/
- [ ] Fix sidebar navigation for current links and scroll through (possible new React component)
- [ ] Dropdown menus
- [ ] Tabs
- [ ] Progress bar
- [ ] Document viewer
- [ ] 508 compliance for each section

**Comment by shanear** [comment]
@mmlumba I'm gonna split this out into seperate tickets

**Comment by shanear** [comment]
see: https://github.com/department-of-veterans-affairs/caseflow/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Living+Styleguide+V1%22

**Comment by shanear** [comment]
All of the checkboxes have been captured as issues in the milestone! Closing this one.
