### ISSUE TITLE
AMA Intake | Any issue older than the current issue in a chain should not be selectable

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9092]
An appellant can only appeal the latest issue in a chain of decisions.

As an example, if there is a decision made on 01/01/2019 that is appealed, and that appeal results in a decision made on 02/01/2019, only the latter decision issue may be appealed.

For MVP treatment, any issue that is part of an issue chain and is older than any other issue in the chain should not be selectable. The UI should guide the user to selecting the most recent decision.

## Acceptance Criteria
- If a decision issue on the first Add Issues modal is contested by another decision issue on the first Add Issues modal, then the issue being contested should be disabled. There should be an italicized message beside the option reading "(Please select most recent decision on MM/DD/YYYY)"

## Notes
The visual treatment should match the treatment we already have for preventing duplicate selections:
<img width="591" alt="screenshot 2019-01-31 16 21 10" src="https://user-images.githubusercontent.com/1596259/52094543-64422000-2574-11e9-9e79-0c6f8e8ac3e7.png">

Related to #1094.

**Comment by steve-gov** [comment]
@shanear This is one treatment of the problem -- the "ineligible" route, which covers a number of use cases. We can also assume the appellant _intended_ to appeal the latest issue by default. I can rewrite the issue if that's preferred.

**Comment by shanear** [comment]
>  We can also assume the appellant intended to appeal the latest issue by default.

I prefer this method. Seems better (and less annoying) for vets.

**Comment by jiahuang** [comment]
Just to clarify:

**Comment by jiahuang** [comment]
Was able to verify in UAT with veteran file number 700032874
<img width="980" alt="screen shot 2019-02-21 at 9 14 13 pm" src="https://user-images.githubusercontent.com/577629/53215333-29d11d80-361e-11e9-8768-c6e7198d1014.png">
