### ISSUE TITLE
Preview Form 8 | Upload and Certify | Incorrect VBMS integration error displayed

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#910]
# Description
When an VBMS integration error is encountered during the uploading of a Form 8, the incorrect error message is displayed.  

**Current Result:**
```
172.30.66.175 - dsva [14/Feb/2017:11:49:10 -0500] "GET /metrics HTTP/1.1" 200 - 0.0155
[certification.cf.uat.ds.va.gov] [172.30.67.11] [2017-02-14 11:39:28 -0500] [CASEFLOW1 ] VBMS HTTP Error 503 (VBMS::Requests::UploadDocumentWithAssociations) <HTML><HEAD><TITLE>Weblogic Bridge Message</TITLE></HEAD> <BODY><H2>Failure of Web Server bridge:</H2><P><hr>No backend server available for connection: timed out after 10 seconds or idempotent set to OFF or method not idempotent.<hr> </BODY></HTML>

[certification.cf.uat.ds.va.gov] [172.30.67.11] [2017-02-14 11:39:28 -0500] [CASEFLOW1 ]   Rendered errors/500.html.erb within layouts/application (0.6ms)
[certification.cf.uat.ds.va.gov] [172.30.67.11] [2017-02-14 11:39:28 -0500] [CASEFLOW1 ] Completed 500 Internal Server Error in 14698ms (ActiveRecord: 1017.9ms)
[certification.cf.uat.ds.va.gov] [172.30.67.11] [2017-02-14 11:39:28 -0500] [CASEFLOW1 ] ** [Raven] Sending event 6572b8e6646a761cf70ed8617a1c25ce to Sentry
[certification.cf.uat.ds.va.gov] [172.30.67.11] [2017-02-14 11:39:28 -0500] [CASEFLOW1 ] ** [Raven] Raven HTTP Transport connecting to http://172.30.66.177:3000
[certification.cf.uat.ds.va.gov] [172.30.67.11] [2017-02-14 11:39:28 -0500] [CASEFLOW1 ] 
ActionController::RoutingError (No route matches "/certifications/2765748/confirm"):
  app/helpers/application_helper.rb:132:in `current_ga_path'
  app/views/layouts/application.html.erb:60:in `_app_views_layouts_application_html_erb___1319109353967645681_47294364382580'
  app/controllers/application_controller.rb:131:in `block (2 levels) in on_vbms_error'
  app/controllers/application_controller.rb:126:in `on_vbms_error'
  app/middleware/metrics_auth.rb:10:in `call'
```

**_Expected Results:_**  Should show the generic Caseflow Error page.
Like here:
https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/certifications/new/000ERR

**Type of Bug:**
- [ ] Performance
- [ ] Security
- [x] Functional

**Environment:**
- [ ] Production
- [x] UAT
- [ ] Demo
- [ ] Development

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [x]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Reproductive Steps
_**Scenario 1 - VBMS Integration Error**_
1. Complete Form 8.
1. Click on the Preview Completed Form 8 button.
1. Click on the Upload and Certify button. 
**Results**:  If VBMS has any kind of error, user is presented with the `404 Error` page.  
**Expected Results**:  Caseflow standard error message.

# Screen Shots
**_Scenario 1 - `UAT` 404 Page_**
<img width="1047" alt="screen shot 2017-02-14 at 11 49 17" src="https://cloud.githubusercontent.com/assets/18075411/22939748/b7c9876e-f2ad-11e6-8483-2f06cea2780d.png">

**_Scenario 1 - Correct Caseflow Error page_**

# Relate Stories/Issues
n/a
**_Support Tickets/Features/Issues_**

**Comment by kierachell** [comment]
Note, this is a more general issue than just Form 8:

<img width="928" alt="screen shot 2017-02-25 at 1 43 17 pm" src="https://cloud.githubusercontent.com/assets/18075411/23333808/679d7dac-fb60-11e6-933e-6eebb22348ed.png">


A **lot** of VBMS/VACOLS timeouts are returning generic web-browser HTTP 500 error. We need to implement some kind of _user-friendly_ handling for this (imho). Otherwise support team will not be happy.

**Comment by nemodjuric** [comment]
@kierachell 
app/helpers/application_helper.rb:132:in `current_ga_path'
Rails recognize_path was causing RoutingError inside of application_helper current_ga_path method. recognize_path was missing method parameter which would allow him to recognize 'POST' requests.

**Comment by kierachell** [comment]
**PASSED**
Validated on `uat`
![screenshot_2017-03-14_11-53-04](https://cloud.githubusercontent.com/assets/18075411/23909576/79cfd1dc-08ad-11e7-9e02-fd05c43aa821.png)
