### ISSUE TITLE
Update Hearing Coordinators list to pull from Caseflow

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#9106]
The [`User#list_hearing_coordinators`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/user.rb#L320-L324) method uses VACOLS staff records to work out the list of coordinators.

from [UserRepository](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/user_repository.rb#L71-L77)
```
    def find_all_hearing_coordinators
      coordinator_records = VACOLS::Staff.where(sdept: "HRG", sactive: "A")

      coordinator_records.select(&:sdomainid).map do |record|
        User.find_by_css_id_or_create_with_default_station_id(record.sdomainid)
      end
    end
```

I'm assuming new users will not be put in VACOLS and Caseflow in the future, so this method will need to be updated.

These users should be the same as the team members of the hearings management organization. We should verify that data is accurate and then update find_all_hearing_coordinators to return the hearings management organization team members.

**Comment by laurjpeterson** [comment]
This can be part of a larger analysis of user permissions/user configurations. 

Potentially related to #8436

**Comment by lomaxap** [comment]
@pshahVA do we know if the Staff table in VACOLS is kept up-to-date when new Hearing Coordinators join?

**Comment by pshahVA** [comment]
@lomaxap I can't find your comment anymore, did you still want me to confirm that the hearings coordinators are kept up to date in VACOLS.

**Comment by lomaxap** [comment]
@pshahVA yes, we need to know

1. Is the list of people in the Hearings Management Organization correct and up to date for the list of hearing coordinators
and
2. (which will probably be answered with 1) We found 5 css_ids (“VACOUNSELL”, “BVAFTR1”, “VACOBROWNK3", “VACOBECKLT”, “VACOJOHNST9") that are in VACOLS "hearing coordinator" staff list but not in Caseflow, can you confirm that they should not be in Caseflow?

**Comment by pshahVA** [comment]
I wonder if these are just older employees.  I asked the question to the hearings branch, but it may take some time to get an answer. It seems like unless we pragmatically keep them in sync, this can always happen.

**Comment by pshahVA** [comment]
According to the hearings branch, "We need all employee codes in CaseFlow except for BVAFTR1" I have asked them to update this via the UI.

**Comment by lomaxap** [comment]
Thanks @pshahVA ! We'll check in again before we merge this to make sure that's done.
