### ISSUE TITLE
Intake | Don't wait a day to sync nonrating decision issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9107]
Right now we are waiting a day to sync decision issues from BGS, because that's about how long it takes for the promulgated ratings to show up in the service.

However, we don't need to find any promulgated ratings for non-rating EP decision issue syncs, yet we are still waiting a day. We should not be waiting a day.

**Comment by jiahuang** [comment]
note: For non-rating, do not wait at all

**Comment by shanear** [comment]
This worked today
