### ISSUE TITLE
Decision Review | Multiple Special Issues Rules

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#911]
As a caseworker, I want to select multiple special issues and route them to a single location.

## Description

**Single Issue:**
- If a single issue level is selected, route the claim to a station with that same level (_e.g. a level 1 issue would be routed to a level 1 station_)

**Multiple Issues:**
- If a level 2 issue is selected in addition to a level 1 or a level 3 issue, route the claim to the level 2 station.
- If a level 1 and level 3 issue are selected, route to level 3.
- If two level 2 issues OR two level 3 issues are selected, route to the first issue's station alphabetically _(e.g., if Mustard Gas and Contaminated Water are selected, route to contaminated water station, Louisville)._

#### Special Issue Hierarchy
**Level 1** issues are sent to the ROJ
**Level 2** issues are sent to a specialized RO
**Level 3** are sent to a center

• Contaminated Water at Camp LeJeune **- Level 2**
• DIC - death, or accrued benefits - United States - **Level 3**
• Education - GI Bill, dependents educational assistance, scholarship, transfer of entitlement - **Level 3**
• Foreign claim - compensation claims, dual claims, appeals - **Level  2**
• Foreign pension, DIC - Mexico, Central and South American, Caribbean - **Level 3**
• Foreign pension, DIC - all other foreign countries - **Level 3**
• Hearing - including travel board & video conference - **Level 1**
• Home Loan Guarantee - **Level 3**
• Incarcerated Veterans - **Level 1**
• Insurance - **Level 3**
• Manlincon Compliance - **Level 1**
• Mustard Gas - **Level 2**
• National Cemetery Administration - **Level 3**
• Non-rating issue - **Level 1**
• Pension - United States - **Level 3**
• Private Attorney or Agent - **Level 1**
• Radiation - **Level 1**
• Rice Compliance - **Level 1**
• Spina Bifida - **Level 1** 
• U.S. Territory claim - American Samoa, Guam, Northern Mariana Islands (Rota, Saipan & Tinian) - **Level 2**
• U.S. Territory claim - Philippines - **Level 2**
• U.S. Territory claim - Puerto Rico and Virgin Islands - **Level 2**
• VAMC - **Level 3**
• Vocational Rehab - **Level 1**
• Waiver of Overpayment - **Level 3**

## Acceptance Criteria
1. Verify that users can select more than 1 special issue.
1. Verify that if any issue from level 2 is selected, the claim is routed to level 2.
1. Verify that if ≥ one level 1 and ≥ one level 3 issue are selected, the claim is routed to level 3.
1. Verify that if ≥ two level 2 issues are selected, the claim is routed to the first station listed alphabetically.
1. Verify that if ≥ two level 3 issues are selected, the claim is routed to the first station listed alphabetically.

_**Note: "routed" here means the claim follows the handling rules for that special issue.**_

# Related Stories
Decision Review | Special Issues | Show all issues regardless Decision Type | #715
Decision Review | Don't allow changing Decision Type | #803
Decision Review | Create End Product.. | Save selected Special Issues for an unsupported Special Issue Cancellation #811

**Comment by kierachell** [comment]
As I understand the behaviour below is what is expected:
![level1_3_soj](https://cloud.githubusercontent.com/assets/18075411/23085586/8aa4d42e-f536-11e6-9491-fa37e7937d8a.png)
![level1_3](https://cloud.githubusercontent.com/assets/18075411/23085587/8aa9904a-f536-11e6-8e74-865c5eee68f7.png)
Sent based on **Level 3**

HOWEVER
Based on AC, the behaviour below is **NOT** expected:
Level 2 and 3 goes based on Level 2:
![level2_3_cancel](https://cloud.githubusercontent.com/assets/18075411/23085748/56458484-f537-11e6-91c1-025f33e37804.png)
can you verify @abbyraskin ?

**Comment by kierachell** [comment]
Further investigation shows that Selecting Levels 2 and 3 defaults to Level 3 (cancel EP)
Selecting all levels defaults to Level 2.
![levels2_3](https://cloud.githubusercontent.com/assets/18075411/23086309/351980f0-f53a-11e6-9467-d45f9529ee09.png)
![levels1_2_3_to2](https://cloud.githubusercontent.com/assets/18075411/23086310/351f7690-f53a-11e6-8683-dda2ee1f6cdf.png)
![levels1_2_3](https://cloud.githubusercontent.com/assets/18075411/23086311/35237b28-f53a-11e6-9486-4626f608017e.png)

**Comment by kierachell** [comment]
can't even create a Level 2 Full Grant
![level2fullgrant](https://cloud.githubusercontent.com/assets/18075411/23194835/7e2afa8e-f87e-11e6-8904-277b3791fa23.png)
No logs on Sentry, just error.

**Comment by kierachell** [comment]
waiting for #957 to finish this

**Comment by kierachell** [comment]
**PASSED***
functionality confirmed for full grants.
