### ISSUE TITLE
Caseflow Demo | Error when selecting a task from seeded data on decision_review page

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9116]
Observed:

1. http://www.caseflowdemo.com/decision_reviews/nca
2. Click the first Bob Smith
3. `ArgumentError in DecisionReviews#show` `Showing /home/ec2-user/caseflow/app/views/decision_reviews/show.html.erb where line #11 raised:` `invalid strptime format - '%m/%d/%Y'`

Clicking a task from a user-entered intake works as expected. Probably means the dummy data is set up in a way that conflicts with recent work on dates?

**Comment by steve-gov** [comment]
Confirmed, can't reproduce.

**Comment by pkarman** [comment]
I found one. fix coming.

**Comment by pkarman** [comment]
not sure this is any easier to reproduce. I did so locally. I believe the issue is task seed data for the NCA org. In any case, the fix should also address the case where upstream provider returns a timestamp instead of a date (which can happen).

**Comment by steve-gov** [comment]
Was not able to reproduce on the caseflowdemo nca page.
