### ISSUE TITLE
Assign case to a different judge

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9117]
Attorney assigned this case to a Judge Karen Kennerly because her Judge Stacey Heneks was out on vacation. Judge Kennerly wants us to move it back to Judge Heneks.

> Her counsel turned this case in to me when she was on vacation, but since there is no acting VLJ list this month, I can’t sign it.  I don’t want the attorney to suffer since she’s already drafted it. 

## AC
- This case - 
https://appeals.cf.ds.va.gov/queue/appeals/c93693c6-f249-49c4-b57a-c1f758d2838a - is assigned to Judge Stacey Heneks for review. It should appear in Judge Heneks "Review Cases" list

**Comment by aroltsch** [comment]
Done.
