### ISSUE TITLE
Gaps: Functionality that's missing

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9126]
## Triage
* How to add admin actions when there's already child admin actions? Any way to block same admin actions from being created? Can there be duplicate admin actions? 
* Training for Hearing Prep -- probably not in person, but provide an update to VLJs when dispositions mean something.  

## Prioritized 
* 

## On Hold 
* Do we want to record the actual return dates of transcriptions? Could this be auto generated when a contractor user returns files and checks out the materials. 
 * Legacy hold opens (30/60/90) - create VACOLS diaries for those - goes with them to Case Storage. We don't think we need to do anything for this right now. 
* Should we add a field for AMA in hearing details for Hearing Notification Letter sent/uploaded to VMBS/to Contractor. What do they do for legacy? Do they want a task for each hearing scheduled to then have a new task for Send Hearing notification letter? Is there value added, or does it drag the process? Need to ask Sal/Scott.

## In Progress 
* AOD logic for hearing prep for AMA -- it's still there and doesn't do anything. Remove drop down or do something.  
* Hearing Prep dispositions -- saving this, alerts to Judges that saving dispositions now creates tasks. 

## Deployed
*

**Comment by ShellySmithDSVA** [comment]
Closing this ticket and will move this information to larger strategy/planning document.
