### ISSUE TITLE
Add better testing to React logic

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#913]
We've moved a lot of our logic into the frontend. This means we're not unit testing dispatch to the same level as we unit test our backend heavy certification. We should consider how we want to test going forward, if there is a good way (maybe Enzyme) to unit test our frontend better.

**Comment by shanear** [comment]
Files like `EstablishClaim.jsx` have a lot of untested logic. Bugs like this could have been prevented/discovered:

https://github.com/department-of-veterans-affairs/caseflow/issues/1040

**Comment by nickheiner-usds** [comment]
We have done work on this, but it's been covered by other tickets and discussions.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
