### ISSUE TITLE
Flakey Tests - Request Issues

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#9130]
these three tests randomly failed on CircleCI, but did not fail locally:

https://circleci.com/gh/department-of-veterans-affairs/caseflow/39261?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by laurjpeterson** [comment]
Closing. Tracking in flakey test running ticket here #10516
