### ISSUE TITLE
Hearing Schedule - Flakey Test

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/caseflow#9131]
Hearing Schedule Daily Docket Hearing details for AMA hearing User can update fields - spec.feature.hearing_schedule.hearing_details_spec

https://circleci.com/gh/department-of-veterans-affairs/caseflow/39158?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```Failure/Error: dropdown.sibling(".Select-menu-outer").find("div[id$='--option-#{options[:index]}']").click

Capybara::ElementNotFound:
  Unable to find css ".Select-menu-outer" that is a sibling of visible css ".dropdown-hearingCoordinatorDropdown .Select-control"
./spec/support/feature_helper.rb:18:in `click_dropdown'
./spec/feature/hearing_schedule/hearing_details_spec.rb:30:in `block (3 levels) in <top (required)>'```

**Comment by youngfreezyVA** [comment]
https://circleci.com/gh/department-of-veterans-affairs/caseflow/39158?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by lomaxap** [comment]
closing in favor of #10516
