### ISSUE TITLE
Proposal to Transition Caseflow Support Team To ServiceNow YourIT

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#9133]
This is a proposal to transition the Caseflow Support team to ServiceNow YourIT. While there is much respect for Github and its features, it is more of a developer's dream and less application support team oriented.  As our user base grows, the need to have a platform that aides in support response and helps us visualize support as a service would help gauge the support team's success. I've started crafting a few advantages and disadvantages. It has already been discussed within the support team but I would love some feedback from the rest of the Caseflow team. 

# User Advantages
- YourIT is the VA wide solution for reporting IT related issues.
- Users can follow their ticket status by visiting their ticket URL versus having to contact support.
- Many users are in need of a ticket number to provide to their management staff as proof of their report issue and possible work stoppage. YourIT not only provides a ticket number but management personnel can also follow the ticket progress by visiting the ticket URL.
- Users receive an automatic email when there is a change to their ticket status or comments added. 
- User would no longer need to report issues in two different sources. 

# Support Team Advantages
- YourIT reduces our reported issue source to phone, email and yourIT. 
- Emails can be sent by the support team within the YourIT without leaving the platform.
- The YourIT platform automatically provides user an email update on ticket when comments are documented within ticket or there has been a ticket status change.
- Reporting capabilities allow us to monitor support response times for service quality improvement
- Better visibility for top level OIT staff. We currently receive tickets through YourIT but support team does all documentation within Github. It gives the impression from the perspective of the user and other OIT units that tickets are being ignored in YourIT until they suddenly get resolved.
- Eliminating feedback would reduce majority of the duplicate tickets received from user who need a yourIT ticket for management but also uses feedback as well for faster response. [If yourIT became our main ticketing system we would have more of a presence within the platform to find newly created tickets not yet assigned by the Enterprise Service Desk]
- For every feedback received, time is spent to transfer ticket description and craft templates that make the information easier to comprehend. In YourIT the user information is pulled from the VA active directory and the user information provided in their request is available in the ticket.
- Each email received by caseflow@va.gov is a ticket to be created in github. Encouraging users to submit a ticket in yourIT versus via helps the support team spend less time on ticket creation and more time resolving issues. 
- The ability exists to add an outage alert in OIT user portal.

# Disadvantages
- Tickets are assigned to Enterprise Service Desk 'MSP' initially until assigned to Caseflow Tier 2
 >User submits ticket via https://yourit.va.gov/va
  
 >Tickets submitted are routed to a tier 1 group called 'MSP' and assessed for assignment to its respective group.

> Once assigned to Caseflow Tier 2 ticket is visible to support team.
#### Working for VACOLS support our standard process was to routinely search YourIT for keyword 'VACOLS' to search for tickets that were incorrectly routed or not yet assigned from MSP. Caseflow support does experience ticket incorrectly routed however with having four ticket sources to monitor we do not spend a lot of time in YourIT.

# What Will Happen To Feedback?

Feedback would become direction to submit a ticket via YourIT and perhaps a survey on how they like the product along with a comment box within that survey for 'feature requests'. 

# How Will PO/Engineer Reviews Work For The Support Team?

Only tickets assigned to tier 3 'PO/Engineering' will be entered in Github. It allows us to keep an active support team engineer-assigned ticket open that support can reference with child tickets to document user impact.

**Comment by msj0nes** [comment]
# Views

### Outage alerts in the self-service portal

![image](https://user-images.githubusercontent.com/41164406/52149771-de89a780-263b-11e9-93e7-8dde23a5e71f.png)

### URL to submit a ticket

https://yourit.va.gov/va

**Comment by kencheeto** [comment]
From what I can tell, looks like nothing will change from my end (I will continue to collaborate on issues here), so I've no opinion one way or another, but am supportive of what is best for you.

**Comment by laurjpeterson** [comment]
I think this is a great idea overall! The value to the support team is quite compelling. 

Do you know how long, on average, it takes for a tickets assigned to Enterprise Service Desk 'MSP' to get to Tier 2 for other products? My main concern is response time for users. If it takes days for the ticket to get to Caseflow Tier 2, I worry about our user satisfaction. 

One potential downside I see is users having to leave Caseflow to get to YourIT portal. I think we should just redirect the `Submit Feedback` links to open that YourIT page directly, if possible, instead of instructions.

**Comment by msj0nes** [comment]
[Caseflow_Support_Sustainable_Path.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/3055760/Caseflow_Support_Sustainable_Path.pdf)

**Comment by laurjpeterson** [comment]
We've done this! Closing.
