### ISSUE TITLE
Fix NaN for days on hold field in task snapshot

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9136]
@allyceh [observed a Board employee](https://dsva.slack.com/archives/C6E41RE92/p1549048268056500) encounter this error today, and writes:

> Here's what happened: 1) We went to the user's queue, 2) She clicked on a Veteran/task. 3) She opened the actions dropdown to see what options there were, 4) She clicked "Send to attorney", 5) She clicked "cancel" because she didn't want to send it to an attorney, 6) When she returned to the Task Snapshot, the task was duplicated and days on hold read "Nan".

## Acceptance criteria
* [ ] Determine how to recreate this scenario locally
* [ ] Make sure we can no longer encounter this bug

**Comment by tomas-nava** [comment]
MEDIUM? ...
- not sure how to reproduce
- not sure if "the task was duplicated" is the same bug or another bug

**Comment by hschallhorn** [comment]
Closing as we have not been able to reproduce nor have we seen this issue again in prod.

**Comment by hschallhorn** [comment]
🎉 https://dsva.slack.com/archives/C6E41RE92/p1556035834023600

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||
3 | ||||||||||
5 | 
8 | 
```
#### Why 2?
- May struggle to track down how to replicate

#### Why 3?
- Investigation and fixes for different scenarios
