### ISSUE TITLE
Timestamp in the logs does not change

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#914]

**Comment by orischwartz-gov** [comment]
The timestamp [here](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/config/initializers/logger.rb#L8) is evaluated once on startup and then never again:

```ruby
log_tags = [:host, ip, Time.now]
```

Could use a lambda or a rails built-in tag if one exists.

**Comment by aroltsch** [comment]
@orischwartz  yes, using lambda fixes the issue:
`log_tags << lambda { |req| Time.now }`
