### ISSUE TITLE
DTA Error EP needs to retain the same POA as the original EP

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9142]
When we are creating 040s from Higher Level Reviews, and that HLR has a claim level (limited) POA, then the follow up POA should have the same POA

### Validation
- Create a Higher Level Review decision review, add a rating and nonrating issue to it.
- Have someone add a limited POA to both end products on the claim.  Unfortunately, I'm not sure who does this or how this happens, maybe it can get added in VBMS or maybe Colin can help.
- Have the decisions on both issues be a DTA error (need Colin's help)
- Check that the new Supplemental Claim that gets created creates two dta end products that both have the same limited POA on them.  EndProductEstablishment will have the fields limited_poa_code and limited_poa_access populated, and VBMS should show the limited POA on the claims as well.

**Comment by leikkisa** [comment]
I created a couple of claims with a limited POA (600149269 and 600149268).  I looked at the raw end_product data from BGS and the claim data from VBMS and did not find it in either.  I am asking VBMS if they can point me to where to find it, and if they might know when it would be set besides when we establish a claim.

It appears that there is a field called powerOfAttorneyId under "Claim" for VBMS's ClaimService V5 in a document that I have, and it is surrounded by all of the other data fields that gets returned with the claim, but alas it was not in the response that I got.  My theory right now is that VBMS might still need to add this.

Other note: establishing the claim with the limited POA failed when I set the limited_poa_access to false (it gave a payee_code error which was a little misleading)

**Comment by leikkisa** [comment]
We can get it from OrgWebService.findLimitedPoasByBnftClaimIds(<list>claimId)

**Comment by leikkisa** [comment]
Validated that the VBMS service for setting limited POA is working in VBMS! BGS service does not seem to be working though, have sent them an email.  The call is succeeding, but not returning anything. I also tried another call with the same service, looking up POA by participant_id because I noticed that VBMS had one, and it also didn't return anything. So I think the whole service might not be working.

Have started working on the DTA SC part, but there's a complicated bug in creating the DTA SCs, and generally think there might need to be some refactoring there, so am going to switch gears.

**Comment by leikkisa** [comment]
Update - BGS service is working, just needed to tweak the code which I was able to do with a combo of some similar documentation from Melissa and some examples BGS sent.  Next step is to code it, but first am fixing a bug we discovered in the process.

**Comment by nicholasholtz** [comment]
@leikkisa Has this one been validated?

**Comment by pkarman** [comment]
can probably validate #9303 and this one together.

**Comment by Sjones352** [comment]
Colin Validated and It passes
<img width="462" alt="Screen Shot 2019-03-20 at 11 47 57 AM" src="https://user-images.githubusercontent.com/23080951/54698870-6c472680-4b06-11e9-9faa-85542d28f65f.png">
