### ISSUE TITLE
Add GetDispositions to envoy config

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#9148]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3561/

The GetDispositions request 404s because our envoy configuration doesn't know how to forward it. Follow the pattern in https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1920 to add it to the envoy configuration

**Comment by kencheeto** [comment]
For validation, I'll verify that no more instances of this error occur

**Comment by shanear** [comment]
This is still 404'ing in prod

**Comment by kencheeto** [comment]
Yeah, envoy configurations aren't updating in prod atm, I think it's tied to the release tooling updates recently, devops is debugging

**Comment by kencheeto** [comment]
Not seeing these in prod anymore! woot
