### ISSUE TITLE
Ramp intake failure - "Benefit Type, Payee code or EP Code is not valid."

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#9149]
Back to back instances:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/232349/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/232350/
(look at these error instances specifically; they're getting lumped into other errors by Sentry)

We're making EstablishClaim requests to VBMS that seem to fail due to an invalid benefit type code, payee code, or EP code - we should investigate which one is problematic.

**Comment by kencheeto** [comment]
source: https://dsva.slack.com/archives/CFBLH2LR4/p1549139165004900

**Comment by kencheeto** [comment]
Looking at the original issue, it seems worth testing if these values will work in UAT: https://github.com/department-of-veterans-affairs/caseflow/issues/6205

It could be something like "01" or "02" are valid but "1" and "2" are not

**Comment by kencheeto** [comment]
@leikkisa I realized that Sentry is incorrectly grouping Claimant w/Fiduciary errors with this one - here's a specific instance of this that shows the original error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/232350/

**Comment by leikkisa** [comment]
Hmmm the EndProductEstablishment for https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/232350/ is missing :-(.  Also, the Veteran doesn't have any ratings. So much data funkiness.

**Comment by kencheeto** [comment]
The error might not be related to the specific fields named, as we've seen this when another field was invalid

**Comment by leikkisa** [comment]
These are both for the same Veteran, the Veteran is currently experiencing the "multiple phone number problem". Am closing this since that is being handled in another ticket.

The first intake for this Veteran got canceled due to system_error, but the ones after that identify it as not_accessible (one says not valid), so I think this was partially due to timing with the merging of data in BGS.
