### ISSUE TITLE
AppealRepository#fetch_documents_for makes a lot of DB round-trips

### ISSUE THREAD

**Issue by orischwartz-gov** [department-of-veterans-affairs/caseflow#915]
`fetch_documents_for` calls ` Document.from_vbms_document` which calls `find_or_create_by` for every single document.

`find_or_create_by` involves a select and possibly an insert. Up 2 DB round trips per doc, which seems excessive. Could batch the operation:

1. Load all docs (with a lock if necessary but it's probably harmless to insert multiple times and ignore dupes)
2. Insert the ones that are missing in one batch.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
