### ISSUE TITLE
Consolidate Appeal Status Serializers (post-MVP)

### ISSUE THREAD

**Issue by mc-usds** [department-of-veterans-affairs/caseflow#9155]
Comment from #9153

"Only thought I have looking at this is I wonder if SC and HLR are always going to be identical. Note that the type might be optional here, provided that we are serializing a model named SupplementalClaim or HigherLevelReview. Maybe consolidating them is something to consider down the road. (Potential names: AojReviewStatusSerializer, AmaClaimStatusSerializer, ScOrHlrStatusSerializer.)"

Note: When type is not explicitly set to a value, it does not seem to be serializing the name of the model being serialized. The result is "supplementalClaims" instead of "supplementalClaim." It could be that it's getting the name of the db table???

**Comment by marvokdolor-gov** [comment]
Engineering decision: more trouble than it's worth and could make the code more difficult to grok for future folks. Closing.
