### ISSUE TITLE
Hearing Schedule Daily Docket Printable Excel Export

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9168]
## User Stories
As a Hearing Schedule user, I need to print the Daily Docket so that I can take notes and refer to the schedule for the day when I am away from my computer.

As a Hearing Schedule user, I need to print the Daily Docket so that I can see everything all on one page and see what each room and day looks like at a glance.

As a Hearing Schedule user, I need to print the Daily Docket so that I can prepare each hearing room for the judges. 

As a Judge, I need to print the Daily Docket so that I can see everything all on one page and see what each room and day looks like at a glance.

As a Judge, I need to print the Daily Docket so that I verify my hearings for each day and have an easy visual reference of what my day looks like.

As a Judge, I need to print the Daily Docket so that I can take notes and check my hearings off for the day. 

As an RO user, I need to print the Daily Docket to help prepare my locations and rooms for hearing days and make sure Veterans are properly conducted into their hearing locations.

As a VSO user, I need to print the Daily Docket so that I can see what Veterans I am representing at a glance and keep those materials with me as I conduct hearings. 

## Mocks
Hearing Management Branch/RO/VSO view: https://va-gov.invisionapp.com/share/G7QBSNQCKES#/344806083_Daily_Docket-NEW

See the attached Excel spreadsheet for template.
[Example Export for Print.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2828766/Example.Export.for.Print.xlsx)

Judge view: 
https://va-gov.invisionapp.com/share/JHRCZI2GZF8#/356094013_Daily_Docket_Saved_Changes

See the attached Excel spreadsheet for template.
[Hearing Prep Print Export.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2851859/Hearing.Prep.Print.Export.xlsx)

## Acceptance Criteria
- [ ] Verify a "Download & Print Page" button at the top of every Daily Docket page is present. When the button is pressed, the user is prompted to download an Excel Spreadsheet of the Daily Docket. 
- [ ] Verify the spreadsheet exports to a single page view
- [ ] Verify the Hearings Management Branch/RO/VSO Daily Docket exports the following fields into the spreadsheet:
 - Date
- VLJ
- Hearing Coordinator
- RO
- Hearing type (Video, CO)
- Hearing Room
- Time
- Docket #
- Veteran Name
- Representative Name
- Hearing Location
- Disposition
- Notes

- [ ] Verify the judge view of the Daily Docket exports the following fields into the spreadsheet:
 - Date
- VLJ
- Hearing Coordinator
- RO
- Hearing type (Video, CO)
- Notes
- Hearing Room
- Time
- Docket #
- Veteran Name
- Representative Name
- Hearing Location
- Disposition
- AOD Status
- Notes

## Related Tickets
#9581 Epic

**Comment by ferristseng** [comment]
@Chingujo 

Here's the PDF from the implementation I have on my branch:

[Daily Docket 2019-06-07.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/3208668/Daily.Docket.2019-06-07.pdf)

**Comment by Chingujo** [comment]
@ferristseng 

Looking over this, as long as the all the data in the original is there and it prints on one day, this would be a good first step as users don't have this feature at the moment. 

We can iteriate and improve upon as necessary with feedback since the design process is complete for this ticket. 

Thank you so much for this!

cc: @pshahVA
