### ISSUE TITLE
Create new mail task: Scroll for task type not working

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9170]
Context: Was sitting with Nina on Lit Support and noticed this bug. 

When she opened the "Create a mail task" modal, she was having trouble scrolling on her PC. She clicked the down arrow to scroll down and view more task types, but on click of the down arrow, the task type drop down closed, and she was unable to view all the task types. She kept opening the drop down and trying again, but it kept closing. 

I asked her to verify if her track pad worked for scrolling, and it did, but it was clunky. For users with PCs or mouses without a scroll, let's make sure that clicking the down arrow works for them.

**Comment by tomas-nava** [comment]
@allyceh @shanear do you know what browser(s) and platform(s) the users were using when they observed this bug?

**Comment by pkarman** [comment]
@leikkisa thinks this may be an IE issue.

**Comment by pkarman** [comment]
from #9884 (which we are closing as a duplicate)

From VBA: 

> One of our users in Portland reached out, with a questions pertaining to the Caseflow interface in VBMS. The problem issue occurred when the user went into the “Edit in Caseflow” button, and selected “Add Issue”, then “None of these match, see more options”.   When the user opened up the little drop down arrow under “Issue Category”, the little slide bar didn’t work.  The user could only find more categories by using a mouse with a wheel to scroll down.  This was discovered because the user has a special ergonomic mouse that doesn’t have one of the rollers.

**Comment by laurjpeterson** [comment]
We closed the duplicate issue #10514 because we don't officially support IE. Doing the same here.
