### ISSUE TITLE
Issue disappears after selecting disposition

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#9175]
On a local machine:

1. Switch to user "attorney with cases" BVASCASPER1
2. Go to your queue
3. Click on Bob Smith (231439628)
4. From the Actions dropdown, select "Decision Ready for Review"
5. From the Dispositions dropdown, select any disposition

Expected Result: The text in the "Issues" column does not disappear
Actual Result: the text disappears and doesn't come back unless you start over from step 4

https://cl.ly/268ca2a6c94a

**Comment by aroltsch** [comment]
@aroltsch will check if it is still an issue

**Comment by aroltsch** [comment]
This is no longer an issue. This page is not visible since we turned on the ama_decision_issues flag.
