### ISSUE TITLE
Withdrawing issue - UI modifications

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#9178]
As a user, I need to be able to withdraw an issue or entire review for a clamant/veteran.

STEPS
**Met with Rachel and gather feedback (2/4/19)**

What we need to find out:

- What are possible withdrawal reasons?
- _Mostly to change lanes_
- How do we receive these requests?
-_Request must be in writing - that is the only requirement_
- How often do these claimants/veterans withdraw a review to change lanes?
-_Don't have #s_
- How likely does the claimant/veteran withdraw one issue (or more) vs. the entire review?
-_Don't have #s_
- Do we need to confirm with Veteran first - via letter or any other means of communication before withdrawing them - or notify them after?
-_No, a letter goes out afterward_
- Is it important to capture the day it was requested or withdrawn?
-_YES_
- Please provide any examples of cases you know about

**UX Design Updates**

- [x] Present UI Modifications to allow withdrawing one issue at time in Intakes’s User flow. - Week of 2/3 - 2/7
- [x] A version of this UI should be flexible enough to turn withdraw capabilities on and off based on user level access.
- [x] Review changes with team
- [ ] Review changes with users - date TBD

**BACKGROUND INFORMATION**
Feedback from Rachel Sauter.

Sometimes veterans withdraw because they get another claim granted, and they're satisfied. Sometimes they are just tired of waiting and the stress of uncertainty. 
Sometimes their rep advises them to withdraw because they are not going to get a grant.

In AMA, they may also withdraw to switch lanes - they must do this within the one year period after the AOJ decision

Withdrawals must be in writing and must be clear as to which issues are being withdrawn. Sometimes we get statements that will say "I'm really sick of waiting and I don't want to do this anymore" or something similar. That is not a withdrawal.

The mail portal SHOULD? a specific label for withdrawals, but it still has to go to a judge, who will issue a dismissal.

**Other UX considerations**

- If user withdraws an issue by mistake, they need to intake it again.  Same for an entire review. (MVP)
- For non-comp, if withdraw is for an appeal (handled at the Board) - how would LOB know the issue was withdrawn - need a notification screen...
- How does a withdrawn issue show up in queue UI? I.e. Case detail & timeline - Review with @sneha-pai 
- Do CAs need a new template to communicate to the claimant/veteran their issues is withdrawn?
- Do we need to document withdrawing issues in va.gov? (@annienguyenUSDS )
- Include withdrawing appeals in Intake - edge case training. - @carolaponce work with @wturne

**Comment by carolaponce** [comment]
Notes & WIP
https://app.mural.co/t/workqueue2001/m/workqueue2001/1548889159757/34048ec08c834eef58e891133c852659163462d6

**Comment by carolaponce** [comment]
References:
https://github.com/department-of-veterans-affairs/caseflow/issues/8824

**Comment by carolaponce** [comment]
Aspirational edit issues:
https://va-gov.invisionapp.com/share/M5QJNX5VKJA

**Comment by carolaponce** [comment]
Updated designs @shanear

**Comment by carolaponce** [comment]
![edit issues withdraw wtih date](https://user-images.githubusercontent.com/11700545/53383278-f0edbd00-392b-11e9-8076-130fdff7604b.png)
![edit issues withdraw](https://user-images.githubusercontent.com/11700545/53383279-f0edbd00-392b-11e9-83ee-e3b622a43401.png)
![edit issues drop down](https://user-images.githubusercontent.com/11700545/53383280-f0edbd00-392b-11e9-9427-2d9c77e1a3d6.png)
![edit issues withdraw reveiw](https://user-images.githubusercontent.com/11700545/53383281-14186c80-392c-11e9-8916-2bc884c36266.png)
![edit issues new](https://user-images.githubusercontent.com/11700545/53383282-f0edbd00-392b-11e9-8f07-afa3ab4b8ac3.png)
![edit issues - withdrawn](https://user-images.githubusercontent.com/11700545/53383283-f0edbd00-392b-11e9-98f2-2915c52480ef.png)
![edit issues - withdrawn_all](https://user-images.githubusercontent.com/11700545/53383306-06fb7d80-392c-11e9-893b-0c6016d04cbc.png)

**Comment by carolaponce** [comment]
* Instead of close review - text at the bottom will be withdraw review

**Comment by carolaponce** [comment]
Issue to collect feedback on copy #9769

**Comment by carolaponce** [comment]
Click through review with AMO
https://va-gov.invisionapp.com/share/BRQUJR5J5AE#/screens

**Comment by carolaponce** [comment]
Updated designs:
Adding undu
![edit issues - withdrawn](https://user-images.githubusercontent.com/11700545/54962001-4cf23400-4f20-11e9-882c-828e5a687161.png)

**Comment by carolaponce** [comment]
Date rules: The date entered needs to be < after the receipt intake date and > before tomorrow's date.
Copy for messages:
Withdrawal incorrect date:
If the date is after today’s date -
We cannot process your request. Please select a request date prior to today’s date.
If the date is prior to the receipt date:
We cannot process your request. Please select a date after the Supplemental Claim’s receipt date.

![edit issues - withdrawn copy 6](https://user-images.githubusercontent.com/11700545/54962408-f38b0480-4f21-11e9-970b-ca9a24186eef.png)
![edit issues - withdrawn copy 7](https://user-images.githubusercontent.com/11700545/54962409-f38b0480-4f21-11e9-9d1d-b83e527caf1b.png)

**Comment by carolaponce** [comment]
In product confirmation

![confirmation](https://user-images.githubusercontent.com/11700545/54962488-4a90d980-4f22-11e9-897c-8be7c1685ea3.png)

**Comment by annienguyenUSDS** [comment]
@carolaponce regarding VA.gov, I would follow up with Chris on appeal status.

**Comment by carolaponce** [comment]
@allyceh - my notes and mocks in this issue
