### ISSUE TITLE
Update data model for closed issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9188]
On the add/remove issues screen, we "soft delete" request issues by setting their `decision_review_id` and `decision_review_type` to `nil`. We will have a variety of new use cases for closed issues with no decisions (examples: https://github.com/department-of-veterans-affairs/caseflow/issues/9179, https://github.com/department-of-veterans-affairs/caseflow/issues/8936) which will require changing the data model to support.

We can start with these soft deleted issues, since the functionality is already live, so this will be mostly a refactor.

## Acceptance Criteria
- When a request issue is removed on the Add/Remove issues screen, `decision_review_id` and `decision_review_type` should not be set to `nil`. Instead, `closed_at` should be set to the current time, and `closed_status` should be set to `removed`.
- All other parts of the app should operate the same way, meaning:
  - Closed request issues should NOT be used in calculating whether an issue is ineligible due to being a duplicate on the intake flow.
  - Closed request issues should NOT be correlated to an active contention in VBMS. If an issue is closed, it's contention should be removed if it hasn't already been removed.
  - Closed request issues should NOT receive any new decisions in Caseflow. They should not appear on any of the non-comp decision flows. They should also not appear in any of the appeals decisions flow.
  - Closed request issues should NOT appear on the add/remove issues page (unless otherwise stated in future stories)

## Notes
- Removing the last issue from a decision review is currently prevented in Caseflow, so we won't worry about the case where the last issue on a decision review is closed in this issue. That's out of scope and will be handled in a follow up issue.

## Technical Notes
- `closed_at` and `closed_status` should be added as new columns. The vision for these columns is that they would eventually be the way to identify if an issue is active or not, and would capture closure states that did not involve decisions.
- The next update we would make is to set `closed_at` and `closed_status` (to `decision_made`) when the decision issues are synced successfully, or when the decision is made in Caseflow.

**Comment by pkarman** [comment]
If `closed_status` only ever has a value of `removed` then why have that column? Does `closed_at` communicate both that it was closed and when?

**Comment by leikkisa** [comment]
Maybe it's the difference between withdrawn and deleted?

**Comment by shanear** [comment]
looks good for claim reviews. Didn't show up on the edit page and didn't block new issues. Data looks good: 

```
 #<RequestIssue:0x0000556793e530f8
  id: 1289,
  review_request_type: "SupplementalClaim",
  review_request_id: 381,
  rating_issue_reference_id: "114210",
  rating_issue_profile_date: Mon, 30 Jul 2018 04:00:00 UTC +00:00,
  contention_reference_id: 315984,
  description: nil,
  issue_category: nil,
  decision_date: nil,
  disposition: nil,
  end_product_establishment_id: 859,
  removed_at: Thu, 07 Feb 2019 23:32:17 UTC +00:00,
  rating_issue_associated_at: nil,
  parent_request_issue_id: nil,
  notes: "",
  is_unidentified: nil,
  ineligible_due_to_id: nil,
  untimely_exemption: nil,
  untimely_exemption_notes: nil,
  ineligible_reason: nil,
  ramp_claim_id: nil,
  decision_sync_submitted_at: nil,
  decision_sync_attempted_at: nil,
  decision_sync_processed_at: nil,
  decision_sync_error: nil,
  vacols_id: nil,
  vacols_sequence_id: nil,
  created_at: Thu, 07 Feb 2019 23:31:10 UTC +00:00,
  benefit_type: "compensation",
  contested_decision_issue_id: nil,
  veteran_participant_id: "600233669",
  contested_rating_issue_diagnostic_code: nil,
  decision_review_type: "SupplementalClaim",
  decision_review_id: 381,
  contested_rating_issue_reference_id: "114210",
  contested_rating_issue_profile_date: "2018-07-30T06:28:31-05:00",
  contested_issue_description: "Service connection for Back is denied.",
  nonrating_issue_description: nil,
  unidentified_issue_text: nil,
  contested_rating_issue_disability_code: "5237",
  last_submitted_at: nil,
  closed_at: Thu, 07 Feb 2019 23:32:08 UTC +00:00,
  closed_status: "removed">,
```

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-02-07 15 40 09" src="https://user-images.githubusercontent.com/1596259/52450135-a9270300-2aee-11e9-98e1-44fa8acf86c4.png">
And they are properly not showing on appeals. Nice 👍
