### ISSUE TITLE
Intake Auth | Add the current user to the organization for the LOB when the user performs an intake for the LOB's benefit type

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9189]
Currently, if a non-compensation/ non-pension Intake user has not logged in, and has not been added to a business line by a Caseflow Administrator, then that user will receive an auth fail error after performing an intake. 

Given the volume of users being onboarded and the complexity of the onboarding process, we would like to simplify things for the LOBs somewhat. We will do this by _automatically_ adding a user to the LOB's `organization` at the moment the user performs their first intake against the LOB's benefit type.

## Acceptance Criteria
1. As an Intake user, I perform an intake: I select either a HLR or SC, fill in the primary form details (including the benefit type), add issues and click the Establish button.
2. If the benefit type is not compensation and not pension, I am immediately added to the LOB `organization` indicated by the benefit type.
3. I see a message that my Intake has been successful, and a list of current tasks for that LOB.

**Comment by steve-gov** [comment]
Logged in as AG101_DSVR, I create an HLR for a Fiduciary issue. When I click Establish HLR, I get the `Drat! You aren't authorized to use this part of Caseflow yet.` screen. I also don't appear in the list of users at `/organizations/fiduciary/users`.

Very long gif to follow:

![screencapture](https://user-images.githubusercontent.com/25468689/52308172-890e0d00-2951-11e9-8570-a253f74d372d.gif)

**Comment by leikkisa** [comment]
@steve-gov Looks like it might not have been merged yet. Is it hard to try again?

![Screen Shot 2019-02-05 at 3.00.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9b7c9e7d70200133c2088/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216454f66b7191a37bf1122b4f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19141c95df242e54d52a215336be7732431.png)

**Comment by steve-gov** [comment]
Validated! Submitted HLR to Fiduciary, saw confirmation & task list, removed user from LOB in admin screen, confirmed user could not access task list, submitted SC to Fiduciary, saw confirmation & task list, confirmed user re-added to admin screen.
