### ISSUE TITLE
Intake | Update FAQ/ Help with latest Intake description and other info

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9195]
Update FAQ/ Help page with better info.

**Comment by pkarman** [comment]
@carolaponce to follow up on this.

**Comment by carolaponce** [comment]
Working with @msj0nes  to get this updated:
https://github.com/department-of-veterans-affairs/caseflow/issues/9990

**Comment by pkarman** [comment]
Will and Martina reviewing PR.

**Comment by laurjpeterson** [comment]
Closing because I reviewed the content in this ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/9990 - and prod and prod looks up to date!
