### ISSUE TITLE
Cancellation | Turn on feature flag

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#920]
As Product Owner, I would like the feature flag turned on for the new cancellation features so that the users can start using this new feature and Caseflow team starts capturing valuable information.

# Acceptance Criteria
1. Verify that the following features are active in production environment:
     
- Certification: Cancellation Modal: Ability to view instructions and report issues - [#626](https://github.com/department-of-veterans-affairs/caseflow/issues/626)
- Certification: Cancellation Modal: Cancel Certification:  Ability to submit cancellation - [#631](https://github.com/department-of-veterans-affairs/caseflow/issues/631)
- Certification: Cancellation Modal: Ability to view confirmation - [#630](https://github.com/department-of-veterans-affairs/caseflow/issues/630)
- Certification: Cancellation Modal: Add required field validation - [#629](https://github.com/department-of-veterans-affairs/caseflow/issues/629)

# Related Issues
EPIC: Certification Cancellation [#1](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1)

**Comment by kierachell** [comment]
**PASSED**
used a modal focus non-capture bug to validate
![nonadminmodal](https://cloud.githubusercontent.com/assets/18075411/23326608/5e3c5474-facd-11e6-84bc-bf71a26af913.png)

**Comment by shellicious** [comment]
@kierachell sorry for the late response, I didn't see this 'til now and have a couple nitpicks:
- There should be a question mark after "Why can't this case be certified in Caseflow"
- This wasn't in the style guide, but after a brief discussion with @KHarshawat @lakohl and @chingujo, additional lines of text next to radio buttons should be indented, so that all of the text of "VBMS and VACOLS dates didn't...." should start to the right of the radio button.

**Comment by kierachell** [comment]
@shellicious 
This will have to be a new separate issue:
- can we have up-to-date mocks for that?

**Comment by lakohl** [comment]
This is a question... is certification a proper name in the way that End Product is? and a process (thus would it be capitalized). It's a tricky one.

**Comment by shellicious** [comment]
@lakohl I'm thinking of it as a process, not the name of the app (Caseflow Certification), and therefore not a proper noun. Can check with nicholas to verify that VA folks don't proper-noun the process Certification.
