### ISSUE TITLE
API: Update status for withdrawn/closed

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#9201]
### Goal
Status should have `type` `withdrawn` or `closed` with dates for withdrawn/closed appeals.
e.g.
```
"status": {
  "type": "closed"
}
```
- [x] @cmgiven to verify the above

### Related:
- #8936 Withdrawing Appeals
- #9202 Update event for withdrawn/closed
- #8996 Events for AMA Appeals

**Comment by cmgiven** [comment]
I believe this is describing an event, not a status? Only events have dates.

**Comment by marvokdolor-gov** [comment]
Ah, thank you. Updated to remove date. Is it good to go?

**Comment by cmgiven** [comment]
Yup!
