### ISSUE TITLE
API: Update when Hearing Info is available

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#9205]
# Goal
Provide information in the API to allow us to show appellant information related to their hearing request based on Switching Dockets eligibility. 

## We want to show them information from #9157:
- date: when the hearing is scheduled for
- location: where it will be held 

### Note from @mc-usds:  
- Switching Dockets is eligible 
- Connects to #9204

### Question from @marvokdolor-gov: 
- Is this a front-end ticket since the API already contains this information see #9157?
    - No it isn't. The Goal (above) has been updated to clarify this.

## ToDo:
- [ ] Add to Appeal Status work tracker #8685

**Comment by jimruggiero** [comment]
@pshahVA Is this ticket still relevant? Seems nothing's occurred since it was opened on 2/5/19. If not, please close this one.

**Comment by pkarman** [comment]
The Appeals Status API has no product owner at present, so this and the other mentioned tickets have not been touched since DS departure. Rather than close, I suggest grouping all the Status API tickets for evaluation. The va.gov team will be key stakeholder.

**Comment by pshahVA** [comment]
@jimruggiero, I think this will provide real value as the Veteran can see his hearing status on the VA.gov page, but this may not necessarily be Tango.

**Comment by chandracarney** [comment]
Removed myself and Tango based on a conversation with Martina on Slack that Foxtrot is working on this/has it lined up and on their radar.
