### ISSUE TITLE
ScheduleHearingTask | Backfill production data

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9206]
There are a few hundred hearings docket AMA appeals in production. We need to backfill these appeals so that they have a HearingTask as a child of the CaseDistributionTask and then a ScheduleHearingTask as a child of the HearingTask.

DistributionTasks will exist in production after this ticket is completed: #9337.

Existing HoldHearingTasks and ScheduleHearingTasks should be updated such that they are children of a HearingTask which is a child of the original task's parent.

**Comment by oscarAtNava** [comment]
@sharonwarner 
Two questions:
1) Should I assign the Hearing Task to the same user as the ScheduleHearingTask?
2) What should be the status of the HearingTask? On Hold if the SHT or HHT are not completed and completed otherwise?

**Comment by sharonwarner** [comment]
@oscarAtNava 

1) The HearingTask should be assigned to Bva.singleton.
2) Yes!

**Comment by oscarAtNava** [comment]
This comment documents the state of the database prior to running the script.

### Nbr of ScheduleHearingTasks with RootTask as parent: 698
`select count(*) 
from tasks p, tasks c
where c.parent_id = p.id
and c.type = 'ScheduleHearingTask'
and p.type = 'RootTask'
and c.appeal_type = 'LegacyAppeal';`

### Nbr of ScheduledHearingTasks with HearingTask as parent: 12,536
`select count(*) 
from tasks p, tasks c
where c.parent_id = p.id
and c.type = 'ScheduleHearingTask'
and p.type = 'HearingTask'
and c.appeal_type = 'LegacyAppeal';`

### Nbr of ScheduleHearingTasks with neither RootTask or HearingTask as parent: 0
`select count(*) 
from tasks p, tasks c
where c.parent_id = p.id
and c.type = 'ScheduleHearingTask'
and p.type not IN('HearingTask', 'RootTask')
and c.appeal_type = 'LegacyAppeal';`

### Nbr of appeals that may have multiple ScheduleHearingTasks: 31
`select p.appeal_id, count(*) 
from tasks p, tasks c
where c.parent_id = p.id
and c.type = 'ScheduleHearingTask'
and p.type = 'RootTask'
and c.appeal_type = 'LegacyAppeal'
group by p.appeal_id
having count(*) > 1
order by count(*) DESC;`

<img width="134" alt="screen shot 2019-02-21 at 1 00 15 pm" src="https://user-images.githubusercontent.com/35975958/53191496-f2d91880-35d9-11e9-86e8-ac9022e65503.png">
