### ISSUE TITLE
Allow individual queue folks to place tasks on hold

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9207]
The Translation organization just got their first AMA appeal translation task assigned to them! However, the only actions they have available to them are Re-assign to person, Assign to team, or Mark task complete. We need to add the Place on hold option

## Acceptance Criteria
* [ ] Translation team individuals (and other repeatable queue individuals, like hearing branch individuals) can place tasks assigned to them on hold
* [ ] Team admins can place tasks assigned to them or to their organizations on hold
* [ ] For cases that have been placed on hold, users have all actions they had available to them when the case was in their assigned tab (in the assigned status), plus:
   - **End hold** - this (1) completes the hold task and (2) changes the task's status to "assigned" so the task appears in the user's assigned tab (instead of on hold tab)

## Screenshot from demo
<img width="1124" alt="screen shot 2019-02-20 at 4 18 22 pm" src="https://user-images.githubusercontent.com/27704093/53125144-388ad800-352b-11e9-9789-dae4217a1bac.png">

**Comment by lowellrex** [comment]
Let's try to use the [`TimeableTask` model](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/timeable_task.rb) here to accomplish this if we can.

**Comment by lowellrex** [comment]
MEDIUM.

**Comment by amprokop** [comment]
![image](https://user-images.githubusercontent.com/3781835/54153311-a4b77800-4415-11e9-90fa-77d19fbe92f0.png)
The organization view doesn't have an "on hold" tab for tasks.

**Comment by laurjpeterson** [comment]
here's the ticket to add on hold tab to team queue - https://github.com/department-of-veterans-affairs/caseflow/issues/9341

is this something that you could take on as well?

**Comment by laurjpeterson** [comment]
@lowellrex - i'm unassigning @amprokop  from this task. let's connect today or tomorrow about how we might finish this ticket this or next sprint!

**Comment by lowellrex** [comment]
Rough rollout plan:
* [ ] Create new `TimedHoldTask`
* [ ] Make sure `GenericTask`s respond properly to having a child `TimedHoldTask`
  * "Days on hold" appears correctly
  * Actions display correctly (all of the same actions as before + "Cancel timed hold")
  * Updating the parent task cancels the `TimedHoldTask` (are there any scenarios where this is not true?)
* [ ] Enable creation of `TimedHoldTask`s for `GenericTask`s
  * Continue using existing system for `ColocatedTask`s
* [ ] Move creation of new timed holds for `ColocatedTask`s to `TimedHoldTask`s
* [ ] Migrate existing `ColocatedTask`s in the database with on hold values to `TimedHoldTask`s
* [ ] Remove the vestigial `on_hold_duration` and `placed_on_hold_at` columns from the `tasks` table

**Comment by lowellrex** [comment]
MEDIUM amount of work remains.
