### ISSUE TITLE
Tasks table is missing indexes

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#9233]
There are several `.where` queries we are making on columns in the Tasks table that don't have indexes. This is causing statement timeouts in production. Examples:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/?query=is%3Aunresolved+select+%22tasks%22

**Comment by lowellrex** [comment]
Great find! I think it would make sense to add at least two (maybe three) indexes to the `tasks` table to match our most common access patterns.

1. Accessing tasks related to an appeal: The index we would need here is `appeal_type, appeal_id`
1. Accessing tasks assigned to an individual person: `assigned_to_type, assigned_to_id`
1. Accessing tasks by type and some additional information (less urgent than the others, but good to add if we aren't constrained by disk space): `type`
