### ISSUE TITLE
Configure Case Details function

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9235]
We are adding a CSEM/CSUM function called Caseflow Case Details, so users can have access to search for cases in Caseflow and view their case details. (For context, another example of a CSEM/CSUM function is `Reader` or `HearingPrep`.) They should *not* be able to access to Caseflow Reader. The primary users for this function are VBA call center/customer service folks, so they can answer Veteran questions, but there will likely be more users that eventually use this scoped down version of Caseflow.

Martina is in the process of requesting the Caseflow Case Details function - https://github.com/department-of-veterans-affairs/appeals-pm/issues/2371

## AC
We need to ensure the following criteria are met, when a user has access to Caseflow Case Details:
- User can search for cases at `/search`
- User navigates to `/search` when they click the Caseflow logo (note: this can be done by the `case_search_homepage` feature toggle if need be)
- When user clicks on docket number link, they navigate to the case details page for that case
- `Veteran documents` link does not show for these users, and users cannot access `/reader/appeal`
- Users cannot navigate to an individual or team queue

**Comment by lowellrex** [comment]
SMALL.
