### ISSUE TITLE
EP Confirmation | Show claims established in terms of today's quota

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#924]
As a Caseworker, I want to see on the `EP Confirmation` page how many claims I've established today and how many more I need to meet today's expected goal of assigned cases so that I am aware of what I have done and what still needs to be done.

# Acceptance Criteria
1. Verify that when the case assignment goal ([TotalCasesAssigned] > 0) has _**NOT**_ been met and there are cases available in the queue, the instructional subtext on the `EP Confirmation` page contains the number of cases completed and the number of cases assigned as follows (Refer to mockup): 

     > Way to go! You have completed [TotalCasesCompleted] out of the [TotalCasesAssigned] cases assigned to you today.  
     > You can now establish the next claim or go back to your Work History.

1. Verify that when the case assignment goal ([TotalCasesAssigned] > 0) has been met and there are cases available in the queue, the following instructional subtext is displayed:  

     > Way to go! You have completed all of the total cases assigned to you today. 
     > You can now establish an additional claim or go back to your work history.  

1. Verify that when when the case assignment goal ([TotalCasesAssigned] > 0) has _**NOT**_ been met  and there are no more claims available in the queue, the following instructional subtext is displayed (refer to mockup - no more claims):  

     > Way to go! You have completed [TotalCasesCompleted] out of the [TotalCasesAssigned] cases assigned to you.  
     > There are no more cases to work today.  Return to the homepage to view your Work History.  
1. Verify that when the case assignment goal ([TotalCasesAssigned] > 0) has been met and there are no more claims available in the queue, the following instructional subtext is displayed: 

     > Way to go! You have completed all of the total cases assigned to you today. 
     > There are no more cases to work today.  Return to the homepage to view your Work History.  
1. Verify that when there are no more claims to establish, the instructional subtext words **_Return to the homepage_** is a link.  
1. Verify that after clicking on the link **_Return to the homepage_**, the 'Caseworker Dashboard` page is displayed.
1. Verify that when no case assignment goal ([TotalCasesAssigned] = 0) has been set and there are cases available in the queue, the **_Establish Next Claim_** button remains enable for retrieving next available case.
1. Verify that when the case assignment goal ([TotalCasesAssigned] > 0) has been met and there are cases available in the queue, the **_Establish Next Claim_** button remains enable for retrieving next available case. 
1. Verify that after entering a value for _"Number of people"_ , clicking the **_Update_** button and the [TotalCasesAssigned] value has been updated  on the `Manager Dashboard` page, this change is reflected on the `EP Confirmation` page in the instructional and action subtext where the [TotalCasesAssigned] is referenced.

## Mockups
**_View - EP Confirmation - Instructional Subtext_**
![image](https://cloud.githubusercontent.com/assets/23063044/23038634/ba0552ae-f458-11e6-85bb-3b0245a8ef86.png)

**_View - EP Confirmation - No More Claims Available in queue_**
![image](https://cloud.githubusercontent.com/assets/23063044/23038290/7f782fea-f457-11e6-9304-521accce9734.png)

# Related Stories
Caseworker Dashboard | Show claims established in terms of today's quota #868
Manager Dashboard | Set number of Caseworkers for today #859

**Comment by kierachell** [comment]
Missing link for _Return to the homepage_.
![screenshot_2017-03-07_16-37-15](https://cloud.githubusercontent.com/assets/18075411/23679043/79dbca54-0354-11e7-8cae-a5e02a8546c9.png)

**Comment by tejans24** [comment]
I had a quick chat with Lara about when the button is actually disabled, she said: 
"Workers are allowed to work past their quota -we should not block them. The only time the button is disabled is when there are no more claims left in the overall (shared) queue"

**Comment by sharonwarner** [comment]
@lakohl Should we update the messages on the completion page? Right now, if a worker has completed more tasks than they were assigned, it says 'Way to go! You have completed 10 out of the 5 cases assigned to you today. You can now establish the next claim or go back to your work history.'

**Comment by lakohl** [comment]
@sharonwarner good call. @avrildavid do you want to take a stab at some copy for this?This is a scenario when users have completed all the cases in their individual queue but can (and may want to)  work additional cases. We should let them know they have completed all that is assigned to them for the day, but also make it clear they can continue working claims if they like.

For context, we're talking about revising the last line in this mock:
![screen shot 2017-03-08 at 8 47 34 am](https://cloud.githubusercontent.com/assets/4975959/23706435/28448090-03dc-11e7-88b0-5c71e62eed71.png)

**Comment by avrildavid** [comment]
@lakohl - 

“Way to go! You have completed all of the total cases assigned to you today. You can now go back to your work history or establish an additional claim if you’d like.”

**Comment by lakohl** [comment]
@avrildavid Thanks! Looks good. @sharonwarner you can use what Avril wrote above.

**Comment by nikitarockz** [comment]
## Acceptance Criteria Updated

@lakohl @sharonwarner @tejans24 @avrildavid   
All of you bring up a good point.  I have updated the ACs to reflect these changes.  I would like to point out that there are actually 4 scenarios:

1. Goal not met and more items in the queue.
1. Goal met and more items in the queue.
1. Goal not met and no items remaining in the queue.
1 Goal met and no items remaining in the queue.

I have created ACs to reflect each of these scenarios using a combination of the verbiage stated.  Please review ACs 1 - 4.

**Comment by astewarttistatech** [comment]
**PASSED**

Tested in: UAT

Steps to Validate: 
1. Log into Dispatch as a caseworker
2. Establish a claim 
3. Validate the messages on the success page. 

Screenshot: 
<img width="1377" alt="screen shot 2017-03-10 at 10 23 20 am" src="https://cloud.githubusercontent.com/assets/23038505/23809073/36436746-059a-11e7-942e-0645f0ac490a.png">
