### ISSUE TITLE
Non Comp Intake | Remove DTA Error as a potential disposition for supplemental claims

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9247]
"DTA Error" is a potential disposition for supplemental claims in the non-comp intake flow. It should not be, and should be removed as an option

**Comment by steve-gov** [comment]
<img width="294" alt="screen shot 2019-02-07 at 11 29 23 am" src="https://user-images.githubusercontent.com/25468689/52437396-a8c94080-2acb-11e9-8886-f20f2f5c0662.png">
