### ISSUE TITLE
Selecting National Cemetery Administration box has weird artifact

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#925]
When you select the National Cemetery Administration checkbox on the review page, there's a weird artifact in chrome where the checkbox is split between the two columns. I think this might be a Chrome bug, but worth taking a look at.

**Comment by mdbenjam** [comment]
<img width="962" alt="screen shot 2017-02-15 at 3 57 10 pm" src="https://cloud.githubusercontent.com/assets/3885236/22995164/c1821998-f397-11e6-9ed4-05c4abf94e9c.png">

**Comment by kierachell** [comment]
Looks fine now.
![siccolumnschrome](https://cloud.githubusercontent.com/assets/18075411/24215384/f9defc6a-0f0e-11e7-8791-73c694830786.gif)
