### ISSUE TITLE
Add user to translation organization

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9251]
Now that we're automatically assigning AMA translation tasks to the translation organization based on zip code (https://github.com/department-of-veterans-affairs/caseflow/issues/8615), our one Translation pilot user requested that there be another Translation user to help work AMA tasks in Caseflow.

## AC
- Add Mitch Cowan, BVAMCOWAN, mitchell.cowan@va.gov - to the Translation organization

**Comment by marvokdolor-gov** [comment]
All done. See below:
<img width="1087" alt="screen shot 2019-02-06 at 2 58 20 pm" src="https://user-images.githubusercontent.com/31679660/52369933-ba550e80-2a1f-11e9-9668-9366e549fe97.png">
