### ISSUE TITLE
Users without sensitivity access can access case details

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#9253]
Meredith was testing in production and determined that she could view a case details page of a veteran she didn't have access to. Reader denied access, and the case details page wasn't fleshed out, but we shouldn't show the case details page at all if access is denied.

We need to ensure we make at least one call to BGS when we try to load the case details page, so we can be denied access if need be.

Example in production:
https://appeals.cf.ds.va.gov/queue/appeals/2985886/

**Comment by lowellrex** [comment]
Related to #7922.

**Comment by lowellrex** [comment]
Work will be accomplished by #7922.
