### ISSUE TITLE
[Sentry] Document ID of type Draft Decision must be in one of these formats: 12345-12345678 or 12345678.123 or 12345678.1234

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9274]
Error is not caught properly. 

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3626/

**Comment by youngfreezyVA** [comment]
see conversation here: https://dsva.slack.com/archives/C6E41RE92/p1549551856113700
