### ISSUE TITLE
Daily Docket Print View

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9278]
This ticket is a design backlog ticket for creating a print view for the Hearing Prep Daily Docket in the form of an exportable Excel spreadsheet.

This should apply to the following locations:
Hearing Prep Daily Docket
Daily Docket RO View
Daily Docket VSO View

**Comment by MeredithStewart** [comment]
The team had previously done work to try to optimize the printing of the webpage, which hasn't had great success. For judges, we should think about doing some limited testing.

**Comment by ShellySmithDSVA** [comment]
Closing this Issue due to research being over.
