### ISSUE TITLE
Ensure we have an appeal when rendering the case details page

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9279]
We occasionally get [errors that indicate](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/?query=CaseDetailsView) that we have attempted to render the case details [without an appeal](https://github.com/department-of-veterans-affairs/caseflow/blob/8d8136392d00677740ace2ad509a995d687e45f9/client/app/queue/CaseDetailsView.jsx#L131) in the global redux store. We should protect against this [with the `CaseDetailsLoadingScreen` component](https://github.com/department-of-veterans-affairs/caseflow/blob/8d8136392d00677740ace2ad509a995d687e45f9/client/app/queue/QueueApp.jsx#L128) but it appears as if something is still slipping through the cracks.

## Acceptance criteria
* [ ] Discover/investigate the path that allows us to render the case details page without an appeal
* [ ] Ensure we don't render the case details page without an appeal

**Comment by leikkisa** [comment]
We are waiting to see this in action before picking it up
