### ISSUE TITLE
ProcessDecisionDocumentJob error File Number does not exist within the system

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9281]
See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3587/

Unknown whether this 500 error is our fault or not.

**Comment by shanear** [comment]
This was fixed by updating the file number

**Comment by leikkisa** [comment]
@shanear Adding a note to add the script to the rake task

**Comment by pkarman** [comment]
see #9298 for script
