### ISSUE TITLE
Update SQL query used in CreateEstablishClaimJob

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#929]
Currently the `CreateEstablishClaimJob` job uses the appeal's decision date to find new full grants. We instead want to find new full grants via the outcoding_date. This will require:
- Update reference from "decided_after" to  something "outcoding" in the Job & AppealsRepository
- Update `VACOLS::Case.amc_full_grants` SQL query to filter by dates greater than 'TIOCTIME' instead of `BFDDEC`

Ask @cmgiven or I if you have any questions

**Comment by cmgiven** [comment]
Note that the key difference here is that TIOCTIME is set once, using systime, and does not change. As a result, we no longer would need to use an approach that repeatedly scans the past, nor would we encounter cases again if BFDDEC is moved forward in time.

**Comment by shanear** [comment]
Took a look over the PR and this looks like it should be done. I'm going to move into In Validation. Correct me if I'm wrong JD

**Comment by kierachell** [comment]
**PASSED**
Well, it broke all my test setup scripts; and I got it fixed in `uat` so yeah!
