### ISSUE TITLE
Search results/case list is showing decision date, but Case Timeline is showing it has not been decided

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9294]
Case in question: https://appeals.cf.ds.va.gov/queue/appeals/3270703

![image](https://user-images.githubusercontent.com/27704093/52443050-b6de8780-2af2-11e9-98b1-e02320ff0811.png)

![image](https://user-images.githubusercontent.com/27704093/52443096-d1186580-2af2-11e9-8912-2619f11301af.png)

**Comment by lowellrex** [comment]
MEDIUM. Suggested path to work on this:

* Take a look at this particular case in the database
* Figure out why it has the decision date that it does
* Have an "a-ha!" moment about why our code doesn't handle this particular case properly
* Fix it.

**Comment by laurjpeterson** [comment]
This issue could be related - Case timeline does not show dispatched legacy appeals correctly - https://github.com/department-of-veterans-affairs/caseflow/issues/9511

**Comment by aroltsch** [comment]
@laurjpeterson so in this case the case timeline should have "Dispatched from BVA" if the case has a decision date.

**Comment by laurjpeterson** [comment]
Yep! See AC in this ticket - https://github.com/department-of-veterans-affairs/caseflow/issues/9511. I didn't realize this was a Case Timeline issue and not a Case Search results issue

**Comment by youngfreezyVA** [comment]
these are the results from the VACOLS query which confirm its a case timeline issue: https://dsva.slack.com/files/UF8J4F3C5/FGZ3VF93M/-.txt
