### ISSUE TITLE
Delete erroneously docketed post-RAMP appeal

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9301]
This case is currently listed as a RAMP appeal in Caseflow but the vet did not submit a valid RAMP Selection (NOD). 

## AC
- https://appeals.cf.ds.va.gov/queue/appeals/629846ec-83de-4c98-bea2-685ca2a63feb has been deleted

**Comment by amprokop** [comment]
done
