### ISSUE TITLE
Refactor attorney and judge flows FE

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9307]
AC: 
Get rid of `EditModalBase` and `DecisionReviewBase`

**Comment by youngfreezyVA** [comment]
I agree, I think we should also think about having all URL actions/mappings in one place, having the urls passed around in different components/places can be hard to track if we ever want to change the UI flow. so passing in `nextPage=urlMappings.flowPage.next`
