### ISSUE TITLE
Not dispatched appeals without decision issues

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9309]
Query: 
Appeal.all.each_with_object([]) { |a, r| r << {uuid: a.uuid, decision_date: a.decision_date, non_completed_tasks: a.tasks.where.not(status: "completed").map(&:type), request_issues: a.request_issues.each_with_object([]) { |i, ii| ii << { description: i.description, disposition: i.disposition}  }  }  if a.decision_date.blank? && a.tasks.where(type: "AttorneyTask", status: "completed").present? && a.decision_issues.empty? }

1. [{:uuid=>"444fc607-6406-4976-8e6b-df84006c0af5", :decision_date=>nil, :non_completed_tasks=>["BvaDispatchTask", "BvaDispatchTask", "RootTask"], :request_issues=>[{:description=>"Entitlement to special monthly compensation based on aid and attendance is denied.", :disposition=>"dismissed_death"}, {:description=>"The previous denial of service connection for sleep apnea is confirmed and continued.", :disposition=>"dismissed_death"}, {:description=>"The claim for entitlement to individual unemployability remains denied.", :disposition=>"dismissed_death"}]}, 

1. {:uuid=>"61479d9d-3f66-44c0-9ead-135944d2cac9", :decision_date=>nil, :non_completed_tasks=>["RootTask", "JudgeDecisionReviewTask"], :request_issues=>[{:description=>"Service connection for left knee condition, also claimed a bilateral knee condition to include arthritis is denied.", :disposition=>"remanded"}, {:description=>"Evaluation of sinusitis, which is currently 0 percent disabling, is continued.", :disposition=>"remanded"}, {:description=>"Evaluation of psoriasis, arms and legs, which is currently 10 percent disabling, is continued.", :disposition=>"remanded"}, {:description=>"Service connection for right knee condition to include arthritis, also claimed as bilateral knee condition to include arthritis is denied.", :disposition=>"remanded"}, {:description=>"Service connection for sleep apnea is denied.", :disposition=>"remanded"}]}, 

1. {:uuid=>"e36f4f99-5754-4e95-b7d9-bed1f969cd25", :decision_date=>nil, :non_completed_tasks=>["RootTask", "JudgeDecisionReviewTask"], :request_issues=>[{:description=>"Service connection for bilateral tinea pedis is denied.", :disposition=>"remanded"}, {:description=>"Service connection for bilateral hearing loss is denied.", :disposition=>"denied"}, {:description=>"Service connection for tinnitus is granted with an evaluation of 10 percent effective December 27, 2013.", :disposition=>"withdrawn"}, {:description=>"Service connection for posttraumatic stress disorder is denied.", :disposition=>"denied"}, {:description=>"Service connection for human papilloma virus is denied.", :disposition=>"remanded"}, {:description=>"Service connection for left eye proptosis is denied.", :disposition=>"remanded"}, {:description=>"Service connection for right eye condition due to trauma is denied.", :disposition=>"denied"}, {:description=>"Service connection for conjunctivitis left eye is denied.", :disposition=>"denied"}, {:description=>"Service connection for glaucoma is denied.", :disposition=>"remanded"}]}, 

1. {:uuid=>"74449754-1695-4bfc-bc0f-e66fd69be3a7", :decision_date=>nil, :non_completed_tasks=>["RootTask", "QualityReviewTask", "QualityReviewTask", "ColocatedTask", "ColocatedTask", "JudgeQualityReviewTask"], :request_issues=>[{:description=>"The previous denial of service connection for right lower extremity peripheral neuropathy (also claimed nerve pain of the foot) as secondary to post traumatic stress disorder is confirmed and continued.", :disposition=>"denied"}, {:description=>"The previous denial of service connection for anemia as secondary to post traumatic stress disorder is confirmed and continued.", :disposition=>"denied"}, {:description=>"The previous denial of service connection for post traumatic stress disorder is confirmed and continued.", :disposition=>"denied"}, {:description=>"The previous denial of service connection for left lower extremity peripheral neuropathy (also claimed as nerve pain of the foot) as secondary to post traumatic stress disorder is confirmed and continued.", :disposition=>"denied"}, {:description=>"The previous denial of service connection for hypercholesterolemia as secondary to post traumatic stress disorder is confirmed and continued.", :disposition=>"denied"}, {:description=>"The previous denial of service connection for diabetes mellitus type II as secondary to post traumatic stress disorder is confirmed and continued.", :disposition=>"denied"}]}, 

1. {:uuid=>"5275d287-97b3-4ff3-9151-0e08a664cda4", :decision_date=>nil, :non_completed_tasks=>["RootTask", "QualityReviewTask", "QualityReviewTask", "JudgeQualityReviewTask", "AttorneyTask"], :request_issues=>[{:description=>"Entitlement to individual unemployability is denied.", :disposition=>"allowed"}]}, 

1. {:uuid=>"629846ec-83de-4c98-bea2-685ca2a63feb", :decision_date=>nil, :non_completed_tasks=>["RootTask", "JudgeQualityReviewTask", "QualityReviewTask", "QualityReviewTask"], :request_issues=>[{:description=>"Evaluation of lumbosacral strain, which is currently 10 percent disabling, is continued.", :disposition=>"denied"}, {:description=>"Evaluation of patellofemoral pain syndrome, left knee, which is currently 10 percent disabling, is continued.", :disposition=>"denied"}]},

1. {:uuid=>"c93693c6-f249-49c4-b57a-c1f758d2838a", :decision_date=>nil, :non_completed_tasks=>["RootTask", "JudgeDecisionReviewTask"], :request_issues=>[{:description=>"Service connection for skin forearm is denied.", :disposition=>"denied"}, {:description=>"Service connection for hypotension is denied.", :disposition=>"denied"}, {:description=>"Service connection for diabetes mellitus is denied.", :disposition=>"denied"}]}]

**Comment by laurjpeterson** [comment]
Note: #6 was an erroneously docketed appeal, deleted from the DB with #9301

**Comment by laurjpeterson** [comment]
Closing because I communicated this to BVA dispatch.
