### ISSUE TITLE
Quick copy change | Update VRE long name in benefit types

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9317]
In https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/BENEFIT_TYPES.json:

`"voc_rehab": "Vocational Rehab. & Employment",`

becomes

`"voc_rehab": "Vocational Rehabilitation and Employment",`

**ETA**: In addition, please replace the string in the same manner anywhere it is stored in the DB.

**ETA**: ...in both prod and UAT.

**Comment by pkarman** [comment]
Could we also ditch the ampersand? "Vocational Rehabilitation and Employment"

**Comment by steve-gov** [comment]
Works for me!

**Comment by steve-gov** [comment]
Edited criteria to add: Please update instances of the string in the DB as well.

**Comment by kencheeto** [comment]
Going to run this bit of code in a prod rails console:
```ruby
voc_rehab = BusinessLine.find_by_url("voc_rehab")
voc_rehab.update!(name: "Vocational Rehabilitation and Employment")
```

**Comment by kencheeto** [comment]
Approved in Slack: https://dsva.slack.com/archives/C754H751T/p1550083738110500

and done! @steve-gov could you refresh the page? it should be updated now.

**Comment by steve-gov** [comment]
Edited criteria to add: Please update instances of the string in the UAT DB as well.

**Comment by kencheeto** [comment]
Updated in UAT as well!

**Comment by steve-gov** [comment]
<img width="600" alt="screen shot 2019-02-14 at 9 00 40 am" src="https://user-images.githubusercontent.com/25468689/52803496-082cd080-3037-11e9-98bf-0bb9c22c7104.png">
