### ISSUE TITLE
Create a data dictionary for Intake

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#9320]
During retro we talked about a data dictionary potentially being a useful way to describe the db schema. By explaining what each column means for each table used by Intake, we should be able to better understand and make changes to the data model later.

This data dictionary could be a markdown file in the caseflow repo.

related #9347
related #8501

**Comment by leikkisa** [comment]
I am looking in a way to start with generated files from the schema. Also, depending on the audience we may want to consider CSVs (which still look pretty good in GitHub).

**Comment by leikkisa** [comment]
We can add database comments with Rails migrations starting in v5!  I think it'd be nice if we can do it that way. Then in the future, we can encourage people to add comments right when they're adding a column (for non-obvious fields), and generate a data dictionary and a Rails ERD.

**Comment by marvokdolor-gov** [comment]
Not sure if this can be leveraged, but Teja is building a Caseflow data dictionary for the Board’s Reporting efforts: https://github.com/department-of-veterans-affairs/caseflow/issues/8501

**Comment by leikkisa** [comment]
@marvokdolor-gov Thank you! Way to make connections! I'll check in with Teja to coordinate.

**Comment by leikkisa** [comment]
Teja said it would be useful if we can help with the field descriptions that we know about.  The plan is to test out commenting the DB for tables and fields in a Rails migration, put the instructions here, and divvy up the fields we know about to add descriptions.  Going forward, we'd like to instruct future developers to do it when they are adding a table and field in the first place.  Comments can also be updated (a new one replaces the old one).

Peter has also suggested we add more relationships to the database (and I think some other things like not-null constraints would be good too). Besides enforcing data quality, both of these will help with the ability to generate updated data dictionaries and ERDs.

**Comment by leikkisa** [comment]
Here's an example of adding a comment to an existing table or column:
```
def change
    msg = 'Stores the claimant for each Decision Review, and its payee_code if required'
    change_table_comment(:claimants, msg)
    change_column_comment(:claimants, :participant_id, "The claimant's participant ID")
  end
```

Here's an example of adding one when adding the table/column/index in the first place:
```
  def change
    create_table :my_table, comment: 'A description of my_table' do |t|
      t.string :a_field, comment: 'A description of a_field'
      t.string :another_field, comment: 'A description of another_field'
    end

    add_index :my_table, :a_field,
              name: 'index_my_table_on_a_field',
              unique: true,
              comment: 'A comment for the index'
  end
```

**Comment by leikkisa** [comment]
Have shared a spreadsheet with everyone in Intake to add descriptions. Will mark when descriptions have been migrated.

**Comment by leikkisa** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/9559
