### ISSUE TITLE
Problems with very large files in Reader

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9330]
We’re experiencing a few issues  with 1000+ page documents in reader:

1. *Zooming does not preserve the current page + location.*
This is most noticeable on a very high number page such as 1000 (which will jump to page ~947), but affects all pages.

1. *When zoomed in, pressing “Add a comment” will skip to another page*
Attempting to scroll or move the comment cursor while placing will also skip to different pages and locations. Usually occurs at zoom level 1.6.
Support ticket for this one: https://github.com/department-of-veterans-affairs/appeals-support/issues/3890

1. *When zoomed in, pressing “Add a comment” will cause the pdf view to go blank*
Clicking to place the comment will not trigger a ’Place Annotation” action. Scrolling the document will typically bring the view back, but often to the wrong page and will cause the same issues as above with the view going blank again as well. Usually occurs at zoom level 1.8.
Support ticket for this one: https://github.com/department-of-veterans-affairs/appeals-support/issues/4049

1. And finally, if you are actually able to place a comment on the page you intended….
*Comment sidebar shows incorrect page number and the jump to section button does not skip to the correct page*
Hitting the jump to comment button multiple times will just back and forth between incorrect pages if zoomed in.

Notes:
1. Use https://dsvaappeals.1password.com/vaults/all/allitems/qnqd3hkjl36zh5me5sk2zm3hrq document to re-produce
2. Ask @hschallhorn for clarification.

**Comment by youngfreezyVA** [comment]
@mdbenjam  and I were able to resolve issues #1 and #2, will pick up #3 and #4 after mark gets back. branch: `PDF-Reader-Large-Files`

**Comment by aroltsch** [comment]
@youngfreezy do you think we could merge #1 and #2 if you already have a fix for it?

**Comment by aroltsch** [comment]
Work should continue on 02/18/2019 week
