### ISSUE TITLE
Do not make calls to Vacols for document count and new documents endpoints

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9331]
AC:
No Vacols calls are made for document count and new documents endpoints

**Comment by laurjpeterson** [comment]
@aroltsch is this ticket still relevant? i know we did a ton of work around the new document endpoint

**Comment by aroltsch** [comment]
I think we can close it for now. The new document endpoint was removed and the document count endpoint is working better.
