### ISSUE TITLE
Intake Admin | Report showing number of intakes each employee worked daily

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9334]
The business needs a way to see the number of intakes a CA has done on any given day. The initial idea for this is to create a report where you can type in the CSS ID for a CA, and it will show the last 60 days of successful intakes for that employee.

It will display something like this.

Intake history for SRUSSELL
< Change user

Date  |   Supplemental Claims   |  Higher Level Reviews  |   Other     |  Total
------|------------------------|------------------------|----------|-----------
02/19/2019 | 4 | 6 | 1 | __11__

We will likely iterate on the way we display data on this page, since there is some nuance to what counts as a successful intake and what doesn't for AMO.

**Comment by kencheeto** [comment]
This should be gated by the Admin Intake role.

**Comment by pkarman** [comment]
A first pass at this is available at `/intake/manager`

**Comment by steve-gov** [comment]
Searching by user doesn't seem to filter the results (user `CF_Q_283` is `TEST ONE`):

<img width="537" alt="screen shot 2019-02-20 at 12 17 49 pm" src="https://user-images.githubusercontent.com/25468689/53110740-af16de00-3509-11e9-938e-609d4f60be06.png">

**Comment by steve-gov** [comment]
Given the implied acceptance criteria, I think that getting the user search/ filtering wired up, and limiting results shown to the last 60 days, will validate this part. Couple other improvements in mind but will create specific issues for them.

**Comment by pkarman** [comment]
That particular user has zero successful intakes.
```
irb(main):001:0> u = User.find_by_css_id('CF_Q_283')
[2019-02-20 15:10:26 -0500]   User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE (LOWER(css_id)=LOWER('CF_Q_283')) LIMIT $1  [["LIMIT", 1]]
=> #<User id: 375, station_id: "101", css_id: "CF_Q_283", full_name: "Michael E Kilcoyne", email: nil, roles: nil, selected_regional_office: nil>
irb(main):002:0> Intake.user_stats(u)
[2019-02-20 15:10:34 -0500]   Intake Load (1.2ms)  SELECT intakes.*, date(completed_at) as day_completed FROM "intakes" WHERE "intakes"."user_id" = 375 AND (completed_at > '2018-12-22 23:59:59.999999') AND "intakes"."completion_status" = $1 ORDER BY day_completed  [["completion_status", "success"]]
=> []
```

I have created a PR to more clearly show when the user is found but has zero stats.

**Comment by steve-gov** [comment]
Neat-o.

<img width="892" alt="screen shot 2019-02-21 at 2 36 48 pm" src="https://user-images.githubusercontent.com/25468689/53196475-2b7eef00-35e6-11e9-85a0-bcc313cab19f.png">
