### ISSUE TITLE
Create DistributionTasks for all remaining RAMP appeals

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#9337]
We'll plan to distribute all remaining RAMP appeals through auto case distribution, rather than through the RAMP assignment script.

For all RAMP appeals that have not been assigned to judges:

- Run `set_target_decision_date!` against the appeal
- If the appeal is direct review, create a DistributionTask to mark the appeal ready for distribution
- If the appeal is evidence submission, create a DistributionTask and an EvidenceSubmissionWindowTask as a child of the DistributionTask. It's fine if we do this no matter if the appeal has already exceeded the 90 day window or not — the nightly job will just pick it up the next night and mark the task as complete (https://github.com/department-of-veterans-affairs/caseflow/issues/9339).
- Ramp appeals that were already intook will already have an IHP task—we need to ensure that we don't create duplicates. 
  - in `RootTask.create_ihp_tasks!`, before creating new InformalHearingPresentation tasks, check if one already exists for that organization and that appeal, and if so, just return the existing task.
  - Ordinarily for evidence submission appeals we would create IHP tasks *after* the evidence submission period ends. However, for the purpose of backfilling tasks for RAMP appeals, it shouldn't be a problem if the IHP task and the evidence submission task are open simultaneously — the IHP task currently never expires and it will block distribution until it is complete. 
  - Q: Are there appeals that could have multiple IHP tasks for the same organization? If so, this approach may create problems.

- If the appeal is a hearing appeal...
  - Create a HearingTask as a child of the DistributionTask and a ScheduleHearingTask as a child of the HearingTask (#9206)

**Comment by laurjpeterson** [comment]
Q: With this outline above, will the EvidenceWindowSubmissionTask's start date be the receipt date of the NOD?

**Comment by amprokop** [comment]
Yeah, I will make that change first.

**Comment by amprokop** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/9340

**Comment by cmgiven** [comment]
Ah, we will also need to run `set_target_decision_date!` against all of these.

**Comment by amprokop** [comment]
Good call.
