### ISSUE TITLE
Translation task in On Hold tab without on_hold status

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9342]
First AMA translation task! Here's what went down:
* Marvin, VLJ Support user, assigned the task to Translation team queue
* Translation team lead, Shakira, assigned task to herself from Translation team queue
* Shakira did what she needed outside of Caseflow for the Translation. She wanted to place it on hold, but didn't have that option in her Case Details dropdown
* She marked the task complete, which moved the case back to the Marvin. Shakira asked Marvin to assign the task back to her
* The case is now sitting in her On Hold tab and the Translation team's Assigned tab, but Looker says that the case only has the `viewed` status 

https://appeals.cf.ds.va.gov/queue/appeals/968a0d10-898f-4117-b5f2-20b05b640cb0

To do's:
* Understand why the case is in her On Hold column without having the on_hold status?
* We need individual Translation users (and all individual queue users) to be able to place tasks on hold - ticketed here: https://github.com/department-of-veterans-affairs/caseflow/issues/9207
* We need to distinguish Assigned and On Hold tasks in the team queue view - ticketed here: https://github.com/department-of-veterans-affairs/caseflow/issues/9341

**Comment by lowellrex** [comment]
Let's try to use the [`TimeableTask` model](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/timeable_task.rb) here to accomplish this if we can.

**Comment by laurjpeterson** [comment]
Closing because individual queue users can now place tasks on hold
