### ISSUE TITLE
Assess problematic side effects of Rake Timeout

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#936]
During some probing of how the rake timeout works, we noticed that if the Rake Timeout destroys a thread while it's in the middle of a Postgres SQL transaction, it will leave both a zombie thread and a zombie DB connection to PSQL.

This is a pretty big deal, and might be a reason to remove the rake timeout mechanism. Assess whether that is necessary, and if not, how we can avoid the problem described above.

**Comment by joofsh** [comment]
Happy to remove this, but I think this still serves a valid purpose. It's normal to have some sort of global timeout to avoid runaway threads. This may also serve a practical debugging purpose (did it help us get to the bottom of things yesterday?).  Independently, all DB/API integrations do need their own timeout (and shorter than this one).
