### ISSUE TITLE
Improve new documents icon implementation

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9361]
Problem:
Case details uses the last time the user clicked into Reader timestamp while the queue page uses the task's placed_on_hold_at date

Figure out the best way to tackle this problem implementation wise:

Idea:
Case details page:
Use appeals_controller and make a request on the appeal because task info is not needed

Queue page:
Use tasks_controller to get new_documents on per task basis

Bonus point: think of ways to improve on `cached` parameter

AC: 
Write a tech spec outlining the best solution

**Comment by hschallhorn** [comment]
So something we also need to consider is the fact that there are some queues that have an implementation of the new documents icon that are not associated with tasks that are on hold (and therefore would not use the on hold date). [Relevant slack thread](https://dsva.slack.com/archives/C6E41RE92/p1548351413362100).

**Comment by hschallhorn** [comment]
So this looks like it should be pretty simple to do.

**On BE:**
1. Add a route to new_documents for tasks.
2. Return new_docs_for_user on the task's associated appeal, passing in cached as true and the task's placed_on_hold date
3. Remove all mention of cached and place_on_hold_date from appeals_controller and passed cached as false to new_docs_for_user (as any time we're requesting new_documents on an appeal is from the case details page)

**On FE:**
1. Remove all parameters passed from the front end as cached and placed_on_hold are now handled exclusively on the back end.
2. Add newDocsForTask and associated actions/reducers

**Comment by aroltsch** [comment]
Excellent!

1. I think we should also move `number_of_documents_from_caseflow` to the `DocumentFetcher`
1. Then instead of using DocumentConcern we should create a new workflow class called `NewDocumentsForUser` that will have a few attributes: user, appeal, query_vbms (instead of cached), date_to_compare_with (instead of placed_on_hold_at - just like you suggested initially). You can create a method `process` inside
1. In the appeals_controller, you would instantiate `NewDocumentForUser.new(appeal: appeal, user: current_user, query_vbms: true, date_to_compare_with: Time.zone.at(0).process`
1. In the tasks_controller, you would instantiate `NewDocumentForUser.new(appeal: task.appeal, user: current_user, query_vbms: false, date_to_compare_with: task.placed_on_hold_at).process`

Then can you think if we can get rid of `cached` in the `document_count` endpoint?

**Comment by hschallhorn** [comment]
Adding a `document_count` endpoint for tasks would achieve the same result. We're only requesting a cached count from queue and could handle where the count comes from purely on the back end.

**Comment by aroltsch** [comment]
Hmmm, not a huge fan of adding a document count endpoint to the tasks because it doesn't rely on the tasks at all.

**Comment by hschallhorn** [comment]
@aroltsch About point two, what is the advantage of this approach over just calling a document_fetcher function from the controllers?

**Comment by hschallhorn** [comment]
also, re: moving `number_of_documents_from_caseflow` to the `DocumentFetcher`, document_fetcher queries vbms when it is created, so moving number_of_documents there would query vbms even if we have and are looking for Caseflow Documents
