### ISSUE TITLE
Intake | Enable AMA feature toggles

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9366]
These feature toggles should be enabled:

* `:intake`
* `:intakeAma`
* `:decision_reviews`

Affected file: https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/features-config.yml

**Comment by kencheeto** [comment]
We'll plan on turning these on Monday so that CAs working on Tuesday morning will see the new forms.

**Comment by leikkisa** [comment]
Noting some more relevant ones:

intake_legacy_opt_in
claims_service_v5
vbms_include_user
intake_enable_add_issues_page (no longer in use)
create_board_grant_effectuations
case_search_home_page
ama_decision_issues

**Comment by pkarman** [comment]
All of these were enabled in prod, and no reported issues.
