### ISSUE TITLE
Validate that we have timeouts for all our dependencies

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#937]
Since there is a chance for outages, hangs, or major lag time from any of our dependencies, we should have a timeout to prevent those issues from causing serious problems in Caseflow. For VBMS and BGS, these are http requests and may already be there. We just need to validate it.

For VACOLS, since it's an Oracle connection, we may need to add some sort of timeout mechanism.

- [x] BGS  https://github.com/department-of-veterans-affairs/ruby-bgs/pull/25
- [x] VBMS https://github.com/department-of-veterans-affairs/connect_vbms/pull/134
- [x] VACOLS https://github.com/department-of-veterans-affairs/caseflow/pull/965
- [x] Postgres https://github.com/department-of-veterans-affairs/caseflow/pull/1189

**Comment by kierachell** [comment]
Waiting for another outage to really validate this.

**Comment by kierachell** [comment]
**PASSED**
Validated by timing things out in UAT.
