### ISSUE TITLE
Seed data updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9375]
1) There shouldn't be any VACOLS master records for video hearings (I see one created for RO13 on 2/12).
1) The video hearing days should all be for later than 4/1.

**Comment by Sjones352** [comment]
@lomaxap adding a video hearing day for later than 4/1 for St. Petersburg, shows a blank page when you try to schedule veteran.

**Comment by MeredithStewart** [comment]
@lomaxap -- from Demo it's hard for me to tell what seed data is available now. Can you post some? 

Are there AMA Veterans to schedule for any ROs?

**Comment by MeredithStewart** [comment]
For demo: 
* Would be good to have the majority of the veteran data in demo to be the veteran only, not a separate appellant. 
* Would be good if location data could match from Case details to schedule veterans modal (they addresses right now change at each)
