### ISSUE TITLE
Include intakes that are still processing when checking in_active_review

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9376]
## Story
If an intake fails to establish on the first round, if someone tries to re-intake it while the first one is submitted but not established, they might select a duplicate issue that succeeds to establish on the first intake after a re-try.

Make these issues ineligible due to being "in_active_review".

## Acceptance criteria
An issue on an intake that has been submitted but not established is ineligible and gets the "in_active_review" message if it is selected.

## Validation
Not sure if this is possible/worth it, but this is what it would require:
- Create an Higher Level Review or Supplemental claim with a rating issue, cause an error or otherwise prevent the asynchronous processing from completing on it, at least until finished with step 2
- Create another intake for the same Veteran with the same rating issue selected, it should be marked as ineligible, and if you finish the intake (you would have to add an eligible issue), the ineligible issue should be marked as ineligible in the database

**Comment by Sjones352** [comment]
@leikkisa and @pkarman 
So I create an EP in UAT and this shows a `synced_status: "PEND"`. When I delete it and re-create an EP with same veteran file number and same rating, I see `synced_status: nil`. Not sure if this is what is supposed to happened.
<img width="1661" alt="screen shot 2019-03-08 at 12 18 36 pm" src="https://user-images.githubusercontent.com/23080951/54044201-5a779200-419c-11e9-9f01-539456ed894f.png">


**Nil Status**
<img width="1680" alt="screen shot 2019-03-08 at 12 17 31 pm" src="https://user-images.githubusercontent.com/23080951/54044141-3320c500-419c-11e9-9e9c-4b4397d93a3d.png">

**Comment by leikkisa** [comment]
@Sjones352 
Hi Sandra! So you're not deleting the End Product Establishment, you're just deleting the synced_status: "PEND" so that it's the same EPE, with a synced_status: nil.  This will cause the software to think that EPE is still in the process of being established.

Steps
1. Create an Higher Level Review or Supplemental claim with a rating issue (remember which rating issue you picked).
2. Find the End Product Establishment in the console, as you did.  Let's say the ID is 1016, you would do EndProductEstablishment.find(1016).update!(synced_status: nil)
3. Do another intake, and pick the same rating issue.  It should be red and say it's ineligible because it's already in active review.

**Comment by Sjones352** [comment]
**Currently in UAT**

<img width="1145" alt="Screen Shot 2019-03-08 at 2 51 57 PM" src="https://user-images.githubusercontent.com/23080951/54052912-a7b32e00-41b3-11e9-989e-dba318106146.png">
