### ISSUE TITLE
Should test files be .jsx instead of .js?

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#938]
All of the test files for our client javascript code are `.js` files but it seems like they use `.jsx` features. (see: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/test/containers/EstablishClaim-test.js#L26)

This confuses my text editor :smile:

Should we rename them to `.jsx` files?

**Comment by shanear** [comment]
@joofsh you may know the answer to this

**Comment by joofsh** [comment]
Imo no, but really it's a preference thing (react/webpack don't care how you end your files). Going forward all our JS code will be in react components files, so they will be a mix of JS and JSX. For me, naming the files `.jsx` improves my text editors support for JSX but worsen the JS code. 

If it improved things for the majority of people then we can change it. But I think you just need to enable JSX support on `.js` files too

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)
