### ISSUE TITLE
Decision Sync | Error is not properly getting cleared when decision sync succeeds after failing

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9381]
When a decision sync fails, and then succeeds, the error is not being cleared on the RequestIssue record. So on the case details page, it's still showing as "Decision Sync failed, support notified.", which is incorrect.

There are two ways we can solve this:
1. Don't display "Decision Sync failed, support notified." if the request issue was processed (even if there is an error).
2. Clear the error when the decision sync succeeds.

I think we probably want to do (2) since that's what all the other asyncable models do

**Comment by pkarman** [comment]
Testing notes: not real sure how to test this since it requires a failure. Maybe the /jobs page has an example we could follow, and then check via the console after it disappears from the /jobs page.

**Comment by pkarman** [comment]
zero clean up to be done in production.

```
irb(main):003:0> RequestIssue.where.not(decision_sync_processed_at: nil).where.not(decision_sync_error: nil).count
[2019-03-11 15:49:58 -0400]    (2.3ms)  SELECT COUNT(*) FROM "request_issues" WHERE ("request_issues"."decision_sync_processed_at" IS NOT NULL) AND ("request_issues"."decision_sync_error" IS NOT NULL)
=> 0
```
