### ISSUE TITLE
Allow VSO users to update TrackVeteranTask status on backend

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9389]
When a VSO user clicks into a case details page from the "All cases" tab of their VSO's organization queue, we get an `Caseflow::Error::ActionForbiddenError` (like [this one we received today](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3678/)). The user will still be able to visit the case details because [we don't care about the request's result](https://github.com/department-of-veterans-affairs/caseflow/blob/fb478a7d33a9fb14b1825ed20344804c100171b9/client/app/queue/CaseDetailsLink.jsx#L28), but we shouldn't throw raise this error in the first place. This ticket exists to address that issue.

We are raising the `Caseflow::Error::ActionForbiddenError` because we are attempting to update the status of a `TrackVeteranTask`, and since that class does not have [any available actions](https://github.com/department-of-veterans-affairs/caseflow/blob/fb478a7d33a9fb14b1825ed20344804c100171b9/app/models/tasks/track_veteran_task.rb#L2) the [`can_be_updated_by_user ?` check](https://github.com/department-of-veterans-affairs/caseflow/blob/fb478a7d33a9fb14b1825ed20344804c100171b9/app/models/task.rb#L180) fails. We should probably override that method in the `TrackVeteranTask` class to allow all members of the organization to update the status.

Alternatively, we could just always create `TrackVeteranTask`s with the status of `in_progress` instead of the default `assigned` (either in [the `RootTask` creation routine](https://github.com/department-of-veterans-affairs/caseflow/blob/6b2c20030790090b62eb0711acdfcfcf59d97820/app/models/tasks/root_task.rb#L71) or as an `after_initialize` callback on [the `TrackVeteranTask` itself](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/track_veteran_task.rb)).

## Acceptance criteria
* [ ] Allow members of VSOs to update the status of `TrackVeteranTask`s assigned to their VSO
* [ ] Do not throw `Caseflow::Error::ActionForbiddenError` when a member of a VSO visits a case details page from their team's queue

**Comment by laurjpeterson** [comment]
@lowellrex - just seeing this. I don't think we should allow VSO users to update TrackVeteran task. As I understand it, the TrackVeteran task is based on whether the VSO is the Veteran's representative as listed in BGS. I think we should keep BGS as the source of truth for whether the TrackVeteran task exists or not so we don't muddy POA data.

**Comment by lowellrex** [comment]
@laurjpeterson - Absolutely! This ticket exists purely for us to change the permissions on the backend to allow for `TrackVeteranTask`s to have their status changed from `assigned` to `in_progress` so the application does not throw the `Caseflow::Error::ActionForbiddenError` when a `VSO` employee navigates to the case details page for a case.
