### ISSUE TITLE
ACD rollout plan for February 19th

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#9392]
- Separate the feature toggle that separates creation of DistributionTasks/their children (hearing, evidence submission window) from the feature toggle that turns on ACD for a specific user. Call the first feature toggle `ama_acd_task_creation`.
- Morning of Feb 19th:
  - Turn the first feature toggle on universally
  - Backfill all RAMP tasks as shown in https://github.com/department-of-veterans-affairs/caseflow/issues/9337 
  - Turn on the second feature toggle for 3 judges that we know will need to request distributions
  - Throughout the day, observe monitoring and any errors, and turn it on for all judges at the end of the day if all problems are solved

**Comment by cmgiven** [comment]
Can we backfill this week? That would allow us to do some additional sanity checks like going into the console and firing up a DocketCoordinator to poke at.

I wonder if we actually turn it on for 1 or 2 judges this week? We could watch them do it and make sure everything goes smoothly?

**Comment by amprokop** [comment]
Good thoughts. I'll try to get a PR out today so we can backfill tomorrow possibly.
