### ISSUE TITLE
Disable RAMP intake options

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9397]
We need a feature flag that disables both RAMP elections and RAMP refilings as options in intake. All active RAMP intakes should still be okay to go through, it just prevents any new ones.

Once that feature flag `enable_ramp_intake` is created, it should be enabled only for 3 users in production: 

* AMOPLENE
* AMCJVIDR
* AMCCWUND

**Comment by leikkisa** [comment]
Before we disable the options, we should check with the business if this is based on receipt_date, or if it turns off altogether. We may want to add validation to receipt_date for these if it is receipt_date oriented instead (not sure how long it takes for things to go from mail to being intaken).

**Comment by nicholasholtz** [comment]
So, just talked with AMO - it looks like they will want the RAMP establishment functionality to be present until May 1, 2019 (and to confirm with them before it gets turned off).

- they need to continue to process existing forms that have not been processed, and to re-process some forms that were erroneously processed. So this ticket should be moved to the backlog, @shanear.

**Comment by pkarman** [comment]
Moved back to ready-for-dev as they have requested 3 users remain enabled, off for everyone else.
