### ISSUE TITLE
Change Hearing Dispositions Task

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9403]
## User Stories
As a Hearings Management branch user, I need to be able to change dispositions after the Daily Docket is locked so that the hearings can move correctly through the tasks needed to complete it.

As a Hearings Management branch administrator, I need to control when dispositions are changed after the Daily Docket is locked. This allows the cases to flow correctly through the assigned tasks and limits the amount of changes made to cases after they are locked.

As a Hearings Management branch administrator, I need to track why dispositions a being changed, investigate corrections, and make accurate updates. 

## Mocks
See the InVision links here: https://va-gov.invisionapp.com/share/CMQHR7EP3Z5

## Engineering Notes
- There's an existing ticket to create the ChangeHearingDispositionTask that should cover much of the acceptance criteria below.
- We need to add Change Disposition as an allowable action from the TranscriptionTask and the NoShowHearingTask. When the user selects that action, we should close the existing task, sibling tasks, and the parent DispositionTask and create a ChangeHearingDispositionTask off of the HearingTask.

## Acceptance Criteria
- [x] Verify the Hearings Management branch users can create a Send for hearing disposition change task under the No Show waiting period task. This creates the task in the Hearings Management queue
- [x] Verify the Transcription team can create a Send for hearing disposition change task under the Transcribe hearing task. This removes the hearing from the transcription queue and creates the task in the Hearings management queue
- [x] Verify Superusers can create the Change hearing disposition task on all tasks that remain in the Hearings Management or Transcription queues (anything with an open Hearing Task). This closes the currently open task and creates the Change hearing disposition task in the Hearings Schedule queue
- [x] Verify Change hearing disposition tasks are visible to all users in the team queue
- [x] Verify only Superusers can assign Change hearing disposition tasks to themselves
- [x] Verify the Change hearing disposition task has the option to place on hold / Assign task to (only other Superusers) / Change hearing disposition
- [x] Verify when the Change hearing disposition option is selected, a modal pops up with the option to change the hearing disposition and leave notes. The modal should also list the hearing date and the current disposition.
- [x] Verify all hearing dispositions are available in the drop down
- [x] Verify once the hearing disposition is saved the disposition is changed in the Case details and in the Daily Docket, Hearing Prep Daily Docket, and Hearing Details
- [x] Verify a Change hearing disposition task is automatically created if a hearing isn't marked with a disposition and is saved by the nightly job
- [x] Verify when the hearing disposition is left blank, it is shown as having a disposition of None in the modal
- [x] Verify when the change is confirmed, the task and notes show in the case timeline

**Comment by MeredithStewart** [comment]
Super users for this should be: Denese Flemmings (Yolanda Flemmings), Sal Ambriz, Ryan Saunders, Tamisha Gray, Lori Christian.
