### ISSUE TITLE
Intake | Prevent claimant from being the veteran if the veteran is deceased

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9417]
If a veteran is deceased, VBMS will throw an error if we try and make an EP where the claimant is the veteran. Also, this isn't really a possible scenario.

## Acceptance Criteria
- On any decision review intake, if a veteran is deceased, then "No" on "Is the claimant someone other than the Veteran" should be disabled and "Yes" should be automatically selected.

**Comment by steve-gov** [comment]
Validated:

<img width="901" alt="screen shot 2019-02-15 at 2 14 59 pm" src="https://user-images.githubusercontent.com/25468689/52887318-258f9680-312c-11e9-9821-084b0a20e2ac.png">
