### ISSUE TITLE
TabWindow component needs fullPage option

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow#944]
The `TabWindow` component by default applies a full page CSS class to tabs, causing them to extend to content borders, like so:

<img width="325" alt="screen shot 2017-02-16 at 1 04 37 pm" src="https://cloud.githubusercontent.com/assets/1053255/23036299/4b16abfc-f450-11e6-8c29-a2d5005aa954.png">

Instead, the component should apply the class when provided a flag.

**Comment by slj** [comment]
### Verification
- Select **Switch User** from main menu
- Click **Establish Claim at station 283** under Switch User
- Click **Establish Claim** under Page Links/Dispatch
- Click **Establish Next Claim** button

This should get you to the screenshot view above; the tabs should extend as far as the PDF tool below it.

**Comment by kierachell** [comment]
**PASSED**
Looks awesome, good catch 👍 
![tabcomponent](https://cloud.githubusercontent.com/assets/18075411/23168996/203b9912-f818-11e6-96be-9f63fe887722.png)
![tabcomponent2](https://cloud.githubusercontent.com/assets/18075411/23169027/3dc79454-f818-11e6-9565-08627a7eeeff.png)
