### ISSUE TITLE
AMA hearings - Need way to display which non-priority hearings should be scheduled

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9453]
For AMA hearings: The Hearing Branch will schedule all CAVC/AOD hearings automatically without any delay. For the non-priority cases, we will need to rely on the information from the Case distribution algorithm to show which hearings should be scheduled (within a timeframe). Note: this is different than legacy, which just get scheduled in docket order for any open spots. 

Option 1: Show all Veterans in the list that match to that RO, but use a visual marker to indicate that they should be scheduled (ideas: bolding the name, using a flag. Note: visual indicator could also be used for legacy within hearing docket range. 

Option 2: Show only those Veterans that are CAVC/AOD and those non-priority Veterans that should be scheduled for a hearing (within the time period). 

Option 3: Allow some sort of toggle function to switch between views - showing only those to schedule vs. entire list. Note: This could also be implemented for legacy within hearing docket range. 

Note: Option 2 would be withholding the entire list of Veterans that are AOD and match to that RO, which we expect is not preferred by the Hearing Branch.

@cmgiven -- can point us to endpoint from the distribution algorithm that can be used to calculate the AMA Hearings that need hearings. 

@MeredithStewart -- I will check with Hearing Branch to see if there's a time frame that they would like to see -- every 3 months, etc.

**Comment by cmgiven** [comment]
`DocketCoordinator.new.target_number_of_ama_hearings(1.month)`

Will give you the number of non-priority AMA hearings that should be scheduled in the next month. The notion is there could be a weekly or monthly job that asks DocketCoordinator for how many hearings to schedule, and then marks that many Veterans as being ready for a hearing (or if they've withdrawn their hearing request, marks them as ready for distribution).

**Comment by MeredithStewart** [comment]
@cmgiven -- I asked the Branch managers - and they thought 2 months would be good. They schedule 30 days out, so maybe we could give them 2 months of hearings (but from 30 days out from the date). And then every month, it would update by another month. 

March 1 -- Caseflow marks AMA hearings that need to be scheduled for April, May 
April 1 -- Caseflow marks AMA hearings that need to be scheduled for April (if any remaining), May and June 
May 1 -- Caseflow marks AMA hearings that need to be scheduled for April (if any remaining), May (if any remaining, and June and July 

Does this scheme make sense?

**Comment by cmgiven** [comment]
That makes sense.

On March 1, we should mark hearings for 3.5 months, because we should count from the AMA effective date. (This would mark ~40 hearings if we ran it today. It'll probably mark slightly more if run on March 1.)

Once marked as ready, an appeal should remain marked. So on April 1, we mark additional appeals just for the month of June, because we've already accounted for all the hearings that need to be marked through the end of May. And then on May 1, we mark additional Veterans for the month of July.

**Comment by cmgiven** [comment]
And yes, I just ran the numbers against prod. There won't be a lot, at least initially.

```
irb(main):001:0> DocketCoordinator.new.target_number_of_ama_hearings(1.month)
=> 12
```

**Comment by MeredithStewart** [comment]
@cmgiven -- before we having markings in production, can I tell them they need to schedule 12 non priority AMA appeals for hearings? Could you tell me which ones -- or if they happen to call come from like St. Petersburg? That would buy us more time before we have to get a marker in prod

**Comment by cmgiven** [comment]
Sure. Maybe we grab the number we need to schedule through the end of March, so on March 1 when we have the marking functionality, we're just marking whatever remains from that list, and however many we need to schedule for April?

**Comment by cmgiven** [comment]
```
irb(main):001:0> dc = DocketCoordinator.new
=> #<DocketCoordinator:0x0000561574391518>
irb(main):002:0> target = dc.target_number_of_ama_hearings(41.days)
=> 17
irb(main):004:0> dc.dockets[:hearing].appeals(priority: false).limit(target).map(&:id)
=> [1587, 412, 407, 1076, 324, 323, 322, 321, 320, 318, 311, 308, 306, 303, 302, 298, 358]

**Comment by MeredithStewart** [comment]
@cmgiven -- If you can give me a list of AMA appeals that should be scheduled, preferably by the RO - something that I can hand the branch and they can accomplish, that would really help out.

**Comment by cmgiven** [comment]
```ruby
RequestStore.store[:current_user] = User.system_user
dc = DocketCoordinator.new
target = dc.target_number_of_ama_hearings(71.days)
dc.dockets[:hearing].appeals(priority: false).limit(target).map do |appeal|
  {
    file_number: appeal.veteran_file_number,
    docket_number: appeal.docket_number,
    last_name: appeal.veteran.last_name,
    ro: appeal.veteran.closest_regional_office
  }
end
```

Results shared with Meredith via Lync.
