### ISSUE TITLE
Decision issues do not always save rating issue id chain

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#9465]
Right now when we create a decision issue, sometimes it has the `rating_issue_reference_id` set, and sometimes it does not. This makes it confusing from a data perspective. A decision issue without a `rating_issue_reference_id` may still be contesting a rating request issue.

An example in UAT is `RequestIssue.find(1095)` and `RequestIssue.find(1095).decision_issues` The request issue has `contention_reference_id: 314903` but the decision issue does not. 

When we create a decision issue (such as in response to a DTA error), we set the rating issue reference id: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issue.rb#L580-L590

When we create a decision issue from the UI, we do not: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/issue_updater.rb#L48-L55

1 decision issue can decide multiple request issues. Each of those request issues can have different rating issue ids. How should we handle this?

Options:
1. Remove rating issue id/profile date on a decision issue and always look up a decision issue's rating ids by the associated request issue(s)
2. Make rating issue ids a list on decision issues
3. Add a method `rating_issue_reference_ids` to decision issue that either finds the decision issue's `rating_issue_reference_id` if it is not nil or looks up rating ids from request issues

**Comment by leikkisa** [comment]
On a Decision Issue, the rating_issue_id/profile_id comes from a new rating, which is different from the original request issue's rating.  We've learned that this won't always be populated though.

**Comment by pkarman** [comment]
Are Appeal request issues decided purely in Caseflow with no end products, ever going to have ratings created as a result of their decisions? In the second example `IssueUpdater` there is a `caseflow_decision_date` which suggests to me there were no end products created and therefore no rating.

**Comment by leikkisa** [comment]
Good question! I would be curious what @shanear thoughts are.  It seems to me like ratings would still be created, it doesn't feel like we keep track of enough information to replace the Rating.  For example, if someone requests an increase, and it's granted, Caseflow keeps track that it's granted but not what the new rating % is.

We don't sync the end product (which is when we look for ratings that result from decisions). We also don't have contentions for Appeals, and we use contention_id to link them.

We might need to redefine how we identify a rating issue.  Running into this with another ticket I'm working on too.  The way I'm doing it at the moment only goes one issue back though, so if an issue goes through multiple cycles, it's categorization as a "rating" issue will inevitably get lost.

**Comment by jiahuang** [comment]
Had a chat with Shane, I was confused as to what the rating issue reference id meant for Decision issues. It's not the same as the contestable_rating_issue_reference_id for request issue, like Sally mentioned.

So there's no issue here with how we are setting this field for decision issues.
