### ISSUE TITLE
Intake | remove method

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9471]
Per this comment:

https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/concerns/issue_updater.rb#L7

we should remove the method because `ama_decision_issues` is enabled in prod:

https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/features-config.yml#L92

**Comment by Sjones352** [comment]
Looks like this issue has been resolved in this ticket https://github.com/department-of-veterans-affairs/caseflow/commit/ed479a8e11c9e7e6c36bf544aa77473958db3136

**Comment by pkarman** [comment]
nice!
