### ISSUE TITLE
UAT - Daily Docket Design Updates

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9483]
## Original Ticket
This is a testing ticket for #8645.

## What to test
This test should cover the Hearing Schedule team view of the Daily Docket. 

## Acceptance Criteria
**Hearing Schedule View**
- [x] Verify the Regional Office drop down is added to this view
- [x] Verify Copy Requested by Appellant/Rep is and the check box is added to this view and that the information carries over to the Hearing Prep, Hearing Details, and other locations the check box is present
- [x] Verify the Edit Hearing Details link is added to this views, and opens the Hearing Details 
- [x] Verify the column order of the first list is Disposition / Transcript Requested / Hearing Details / 
- [x] Verify the column order includes Regional Office / Hearing Location / Hearing Day / Time listed in the second list
- [x] Verify the Regional Office is listed in the upper right hand corner of the page along with the Hearing Type, Room Number, etc. This information should be viewable even when no Veterans are scheduled for that day. 

## Mock Ups
See the following Invision link: https://va-gov.invisionapp.com/share/H3PXTJOA4DX#/340490395_Daily_Docket-NEW

**Comment by ShellySmithDSVA** [comment]
Alice, I don't see any updates on this one. Were you able to test?

**Comment by allyceh** [comment]
Adding comments!

- Regional office drop down is present but disabled. Unable to click into it or change it. Not sure if this is an issue.
- Wasn't able to verify Edit Hearing Details opens for an AMA case-- just legacy. 
- Column order of column 1 also includes Notes field
- Regional office information is listed in the upper right corner, but field isn't always populated with a regional office. Sometimes, it's blank.

**Comment by ShellySmithDSVA** [comment]
Verified this all is complete. Will need to re-test check box continuity with more AMA cases. Closing ticket.
