### ISSUE TITLE
UAT - Remove time column for Legacy and AMA Veterans waiting to be scheduled

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9485]
## Original Ticket
See #9395

## What to test
This change appears on the Veterans to be Scheduled page under the tabs

## Acceptance Criteria
- [x] Remove the time column for the two tabs, "Legacy Veterans Waiting" and "AMA Veterans Waiting" from the Schedule Veterans interface.

**Comment by allyceh** [comment]
Confirmed: Time column is removed from "Legacy Veterans Waiting" and "AMA Veterans Waiting". Verified by sampling a few regional offices from the drop-down and a few hearing days.
