### ISSUE TITLE
UAT - Daily Docket | Header updates

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9487]
## Original Ticket
See #8742

## What to test
Any Hearing Scheduling view of the Daily Docket for any given Regional Office or hearing date

## Acceptance Criteria
- [x] Verify the Regional Office is listed at the top
- [x] Verify the Hearing Coordinator is listed at the top 
- [x] Verify the room number is listed at the top
- [x] Verify the hearing type is listed at the top
- [x] Verify the VLJ is listed at the top

## Mocks
See #8742

**Comment by allyceh** [comment]
Regional office field is listed, but blank for some: 
<img width="327" alt="screen shot 2019-02-19 at 2 50 07 pm" src="https://user-images.githubusercontent.com/40216950/53043110-c0061780-3455-11e9-956b-cbf087a576b2.png">
<img width="191" alt="screen shot 2019-02-19 at 2 52 11 pm" src="https://user-images.githubusercontent.com/40216950/53043217-00659580-3456-11e9-91d4-a03e3adc44f2.png">

**Comment by ShellySmithDSVA** [comment]
This looks to be expected but will delve further. I'll keep this ticket open and test more myself.

**Comment by ShellySmithDSVA** [comment]
This is complete and correct. Closing ticket.
