### ISSUE TITLE
UAT - Hearing Details for Legacy (go to VACOLS)

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9490]
## Original Ticket
See #8455

## What to test
Click on the Hearing Details link for any legacy case in Caseflow from the Daily Docket or Case Details page. This case must have a scheduled hearing for this to work

## Acceptance Criteria
- [ ] Verify hearing coordinators receive this error message on the hearing details pages when they select the Edit Hearing Details link for legacy cases from the Daily Docket and Case Details views.
- [ ] Verify judge/attorney users receive this error message on the hearing details pages when they select the View Hearing Details link for legacy cases from the Case Details view.

## Mocks
Page 6 of following Invision Mock-up: https://va-gov.invisionapp.com/share/TKPRX5QUMRW#/338333096_Hearing_Details_VACOLS_2

**Comment by allyceh** [comment]
Was unable to replicate this error message as a user with Hearing Coordinator or Judge/Attorney permissions in prod.

**Comment by ShellySmithDSVA** [comment]
Ok, thank you. I'll mark this for further testing

**Comment by ShellySmithDSVA** [comment]
I have verified with our user this works. Closing the ticket.
