### ISSUE TITLE
Epic - Hearing Docket View and Edit

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9500]
As a hearing admin, I need to be able to set the hearing docket date in response to changes from the Appeal Status (enter data source if wrong). This hearing docket date affects the schedulable pool of veterans. As a hearing coordinator, I need to visually see where this date is both for legacy and AMA pools for schedule veterans. 

### Issues
#9752 Display hearing docket range for legacy
#9753 Hearing Scheduel Date for AMA
#9754 Scheduling out of Docket Date Error

**Comment by Chingujo** [comment]
closing will be only one ticket

**Comment by jimruggiero** [comment]
@nicholer and @pshahVA Should this issue be closed, since all child tasks described above are closed and no work has occurred on this effort since Andrew's work last April?

**Comment by nicholer** [comment]
I'm fine with closing
