### ISSUE TITLE
Hearing Docket Date

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9502]
As a hearing coordinator, I need to able to see the hearing docket date to make sure I am not scheduling  past this date. 

### Acceptance criteria
_Select one:_

- [ ] Verify that when the hearing docket date is selected we filter this list of scheudlable veterans automatically
or 
- [ ] Verify that the visual indicator (see mocks) is updated

**Comment by lomaxap** [comment]
resolved with #9753 and #9752
