### ISSUE TITLE
Bug: AMA Veterans are matched to ROs/Alt locations, but showing up in wrong schedule Veterans list - ROs and COs

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9505]
In AMA list of Veterans to be scheduled for Central Office, three appear to match to locations other than CO, but appear in the list for CO. 

1 for St. Petersburg (Should show in St. Petersburg's list) 
1 for Mc Allen Texas (Should show in Houston's list) 
1 for Pittsburgh, PA (Should show in Pittsburgh's list)

**Comment by MeredithStewart** [comment]
@lomaxap -- seeing this weirdness pretty consistently across ROs for only the AMA Veterans Waiting tab. 

Winston-Salem list of AMA Veterans waiting has Veterans matching to Chicago, Atlanta (Decatur), El Paso, White City OR, DC, New Orleans, St. Louis, etc. 

Note: I'm not seeing it on the Legacy Veterans Waiting tab.

**Comment by ShellySmithDSVA** [comment]
Houston AMA - https://appeals.cf.ds.va.gov/hearings/schedule/assign?roValue=RO62
Central office AMA - https://appeals.cf.ds.va.gov/hearings/schedule/assign?roValue=C
Chicago AMA - https://appeals.cf.ds.va.gov/hearings/schedule/assign?roValue=RO28
