### ISSUE TITLE
Need to clean up IHP tasks for AMA hearing docket

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9512]
A lot of appeals in the AMA Hearing Docket are showing IHP tasks that won't have one unless the Veteran withdraws their hearing request. 

Talking to Lauren, seems like this needs to be cleaned up. 

Note: PVA would still do IHPs even if hearing is held, but others would only do IHPs if the hearing is withdrawn.

**Comment by laurjpeterson** [comment]
Note: PVA IHP tasks already taken care of in this closed issue, here https://github.com/department-of-veterans-affairs/caseflow/issues/8960

**Comment by lowellrex** [comment]
`InformalHearingPresentationTask.all.map(&:appeal).select { |a| a.hearing_docket? }.count` should reveal the number of IHPs that have been created for hearing docket AMA appeals. The current count is 372.

**Comment by lowellrex** [comment]
XS. Make sure @lowellrex shares the knowledge if he (me!) is the one doing this.

**Comment by lowellrex** [comment]
Also, stop creating IHP tasks for applicable VSOs [upon receipt of the Appeal](https://github.com/department-of-veterans-affairs/caseflow/blob/9b6cb90dc8d9f436b59baa1e00d504390c639722/app/models/tasks/root_task.rb#L121) at the Board (we can just remove that line of code that I added). This should already be happening [after the `EvidenceSubmissionWindowTask` is closed](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/evidence_submission_window_task.rb).
