### ISSUE TITLE
Bug: Veteran not showing up in veterans to schedule for Baltimore

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9513]
The Veteran with the VACOLS ID: 2855139 is not showing up in the Legacy Pool to be scheduled for Baltimore. /appeals/2855139

### Steps of reproduction
- [x] User searched the veteran using case search
- [x] Verified it was ready to be scheduled 
- [x] Went to hearing schedule baltimore docket
- [x] Where this veteran should be on this list is not there. The docket number is skipped over

### Priority
Not blocking scheduling as the user can do it via the case search. However, alerting that it is not showing up in the schedulable pool of veterans legacy tab for Balitmore. Should be around 22 to 24 on the current list.

**Comment by MeredithStewart** [comment]
Backstory: Veteran contacted Board to ask where they were on the schedule, Hearing coordinator looked it up, but could not find Veteran on the list of Veterans to schedule for Baltimore.

**Comment by MeredithStewart** [comment]
@Chingujo -- I think what's happening here is that this Veteran is still in the process of showing up in Caseflow. Let's have Ryan check tomorrow to see if the Veteran appears in the list of Veterans to be scheduled.

**Comment by ShellySmithDSVA** [comment]
Verified this case now shows up properly in the Veterans to be scheduled. Closing and following up with Ryan.
