### ISSUE TITLE
Intake | Refresh all AMA EP statuses on start of intake

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9519]
A common use case for cancelling an EP is to free up the issues so they can be re-intook. But because the EP sync script runs so infrequently (once per 1-2 days, per EP), it may take a while for those issues to be properly canceled.

In order to always use the up to date status for all issues when validating, we should sync all EPs for a veteran before the intake begins.

## Acceptance criteria

This one is really hard to validate because it relies a lot on timing.

One thing to try might be to cancel an EP (outside of Caseflow?), and then quickly start another intake. The "quickly" part is to beat the regular cron job that syncs EPs. Then during intake the canceled EP's code should be available to reuse.

* intake anything connected to a rating
* cancel it
* immediately try another intake that would include the same rating

**Comment by Sjones352** [comment]
@pkarman can an Ep be canceled in VBMS?

**Comment by Sjones352** [comment]
I created an Ep and Cancelled in VBMS

**Created in Caseflow**
<img width="872" alt="Screen Shot 2019-03-11 at 1 00 30 AM" src="https://user-images.githubusercontent.com/23080951/54128901-74ef7c80-43e3-11e9-83a0-592499b2077f.png">

**EP Created in VBMS**
<img width="796" alt="Screen Shot 2019-03-11 at 1 00 22 AM" src="https://user-images.githubusercontent.com/23080951/54128900-7456e600-43e3-11e9-9b1e-fe13c781aec6.png">

**Cancel in VBMS**
<img width="663" alt="Screen Shot 2019-03-11 at 12 48 24 AM" src="https://user-images.githubusercontent.com/23080951/54128841-525d6380-43e3-11e9-98d3-2dd631c769b7.png">

<img width="997" alt="Screen Shot 2019-03-11 at 1 01 51 AM" src="https://user-images.githubusercontent.com/23080951/54128860-5be6cb80-43e3-11e9-8d0e-0efb32e02de3.png">

When I create another Ep with the same rating and check VBMS, it never shows up so I believe this ticket passes and beats the  cron job that syncs EPs.
