### ISSUE TITLE
500 error when Establishing Claim 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#9533]
The problem: Dispatch users are referencing veteran record that Caseflow finds non-existent in BGS. 
Details: We use veteran.found? as prerequisite for creating veteran record which queries VetRecordService with findVeteranByFileNumber. 
Solution: findPersonBySSN in PersonWebService does find the record. One approach would be to query both services. 
We should sync with BGS to clarify inconsistencies. (@mc-usds)

See 
https://github.com/department-of-veterans-affairs/appeals-support/issues/3997
https://github.com/department-of-veterans-affairs/appeals-support/issues/4124

**Comment by mdbenjam** [comment]
Are you suggesting something more than this change? https://github.com/department-of-veterans-affairs/caseflow/pull/9176/files

**Comment by nemodjuric** [comment]
The PR above is to query BGS by both SSN and C file number, while we still query the same VetRecordService which returns no record found for both numbers. The fix suggested is to query different service to look for record. 
Also, in terms of this PR, _from my experience_ dealing with BGS, VetRecordService fineVeteranByFileNumber is both C file and S file compatible meaning BGS will always return record as long as one of these is used and record exists. Not sure if there are any examples in reference to this.

**Comment by mc-usds** [comment]
Had a chat with John at BGS regarding this issue.

BIRLS is used to verify that the person is a Veteran. The error "No BIRLS record found" means that VetRecordService.findVeteranByFileNumber could not find a BIRLS record associated with the filenumber and couldn't verify they are a veteran.

PersonWebService.findPersonBySSN does not do the veteran verification check and returns the record associated with the file number (they could be a veteran, dependent...)

One possibility is that the filenumber has changed and we are using the old one that the BIRLS record is no longer associated with.  I think the link Mark included above handles that condition.

Is the filenumber that is returned when calling findPersonBySSN the same filenumber that was used in findVeteranByFileNumber?  Also, do we know someone that has access to SHARE that can look to see if the filenumber is associated with a BIRLS record?

**Comment by nemodjuric** [comment]
Update: After speaking to @shanear we decided to talk to BGS first and see if can fix corrupt data rather than making changes in our code. @mc-usds will present the issue tomorrow (Feb 21, 2019) to BGS team.

**Comment by nemodjuric** [comment]
BGS looked into it and said that all the SSNs were associated with a dependent, not a veteran.
