### ISSUE TITLE
Move other apps to use new table component

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#9536]
With [this PR](https://github.com/department-of-veterans-affairs/caseflow/pull/9019), a new table component was created that incorporates filtering logic (and also pagination with [this PR](https://github.com/department-of-veterans-affairs/caseflow/pull/9241)). This was only originally applied to the Queue table. Now we want to use this new component in all places where `<Table/>` is being used, and remove `<Table/>`.

This includes the following apps:
- [ ] Hearing Schedule
- [ ] nonComp
- [ ] Reader

**Comment by laurjpeterson** [comment]
@lowellrex @sharonwarner - is this issue still relevant? is filtering available in hearing schedule at all?

**Comment by lowellrex** [comment]
I think we can close it out!
