### ISSUE TITLE
Rename HoldHearingTask to DispositionTask

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9538]
To better map the flow of an appeal through the appeals process, we are changing the name of the `HoldHearingTask` to `DispositionTask`. We will continue to create these tasks when a hearing is scheduled as children of the HearingTask.

For more information, see here: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Hearings/Hearing%20Schedule/Tech%20Specs/HearingTaskFlow.md 

This will require a data backfill to change HoldHearingTasks in production to DispositionTasks.

## Acceptance criteria
* [x] Start creating `DispositionTask`s instead of `HoldHearingTask`s in application code (leave the `HoldHearingTask` class around to satisfy single table inheritance until we've renamed all existing `HoldHearingTask`s).
* [x] Rename all existing `HoldHearingTask`s to `DispositionTask`
* [x] Remove `HoldHearingTask` class

**Comment by lowellrex** [comment]
MEDIUM. Manipulating live data pushes this over the edge from small.

**Comment by tomas-nava** [comment]
Closed with #9683 and #9710
