### ISSUE TITLE
Add application logic when cancelling DispositionTask

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9539]
The `DispositionTask` model (previously `HoldHearingTask`) needs to have a cancel method. This method should perform the following actions:

1) Confirm the task's associated hearing's disposition is 'canceled'. This hearing can be found through the `DispositionTasks`'s parent (a `HearingTask`) which will have a `HearingTaskAssociation`.
1) If the appeal is a legacy appeal:
    - We cancel the `DispositionTask`
    - The `HearingTask` should automatically close
    - We move the appeal to location 81 if there's no associated VSO and 55 if there is an associated VSO (we already have similar logic in the withdraw_hearing method in `ScheduleHearingTask`)
1) If the appeal is an AMA appeal:
    - We cancel the `DispositionTask`
    - The `HearingTask` should automatically close
    - If the appeal has a VSO, we create an IHP task

For more information, see here: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Hearings/Hearing%20Schedule/Tech%20Specs/HearingTaskFlow.md

## Acceptance criteria
* [ ] Add method to cancel `DispositionTask`s during job that will run every night
* [ ] Cancelling `DispositionTask`s closes parent `HearingTask` and returns `LegacyAppeal` to location 81 or 55
* [ ] Cancelling `DispositionTask`s closes parent `HearingTask` and maybe creates an IHP task

**Comment by lowellrex** [comment]
Should cancelling the `DispositionTask` cancel the associated hearing? Or should cancelling the `DispositionTask` just confirm that the hearing has already been cancelled through some other means?

**Comment by sharonwarner** [comment]
Just confirm! This method will be run in an overnight job,  but the hearing dispositions will be updated in the UI during the day.

**Comment by lowellrex** [comment]
MEDIUM. Do not have to write the cron job. But do have to write plenty of tests. Should be able to just directly inspect the value of the associated [`Hearing`'s disposition](https://github.com/department-of-veterans-affairs/caseflow/blob/a135a43b63e09536d998ea05d798ba0f9ce2ba01/db/schema.rb#L527).
