### ISSUE TITLE
Add method to mark a DispositionTask as "held"

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9540]
The `DispositionTask` model (previously `HoldHearingTask`) needs to have a held method. This method should perform the following actions:

1) Confirm the task's associated hearing's disposition is 'held'. This hearing can be found through the `DispositionTasks`'s parent (a `HearingTask`) which will have a `HearingTaskAssociation`.
1) If the appeal is a legacy appeal:
    - We complete the `DispositionTask` 
    - The `HearingTask` should automatically close
    - We move the appeal to location 33 for transcription
1) If the appeal is an AMA appeal:
    - We create a `TranscriptionTask` as a child of the `DispositionTask`
    - We create an `EvidenceWindowTask` as a child of the `DispositionTask` that expires in 90 days unless the associated hearing has marked `evidence_window_waived`

For more information, see here: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Hearings/Hearing%20Schedule/Tech%20Specs/HearingTaskFlow.md

## Acceptance criteria
* [x] Add method to mark hearings as `held` on `DispositionTask`s during job that will run every night
* [x] When a `DispositionTask` is marked `held` for a `LegacyAppeal`, complete that task, complete the parent task, and change the VACOLS location to 33
* [x] When a `DispositionTask` is marked `held` for am AMA `Appeal`, create a child `TranscriptionTask` and maybe a child `EvidenceWindowTask`

**Comment by lowellrex** [comment]
MEDIUM. Similar to #9539.
