### ISSUE TITLE
Intake | Do not allow empty file number in Veteran search

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9545]
See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3794/

## Technical Notes

Would be nice to disallow this on the client side and controller both. Saves a BGS call.

**Comment by jiahuang** [comment]
Full error message is:
BGS::ShareErrorapp/services/external_api/bgs_service.rb in block in fetch_veteran_info
errorfindVeteranByFileNumber: FileNumber is empty
