### ISSUE TITLE
AMA Intake | Better error message for non unique phone number

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9548]
The BGS error
```
NonUniqueResultException
The query on candidate type "class gov.va.vba.corporate.entities.PtcpntPhone" with filter "SELECT p from PtcpntPhone AS p WHERE p.compId.ptcpntId = :ptcpntId AND p.compId.phoneTypeNm = :phoneTypeNm AND p.compId.efctvDt IS NOT NULL AND p.endDt IS NULL" was configured to have a unique result, but more than one instance matched the query.
```

Happens because two or more Veteran records have been merged in CorpDB and now there are multiple active phone numbers.

The workaround is to log in to SHARE and update the Veteran record. See https://github.com/department-of-veterans-affairs/appeals-support/issues/4020#issuecomment-464790349

Our error message should include that helpful step.

## Technical Note

* A new method to the BGS library similar `can_access?` but that returns both a boolean and the reason.

**Comment by leikkisa** [comment]
Martina sent us a screenshot! Considering this Validated.
