### ISSUE TITLE
Intake | Set closed_at and closed_status for decided issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9556]
In order to use `closed_at` and `closed_status` as the source of truth on whether an issue is open or not, we need to set decided issues to closed.

## Acceptance Criteria
- When the decision issues are synced for a request issue on a claim review, set `closed_at` to now and `closed_status` to `decided` for all request issues with at least one decision issue.
- When an appeal is outcoded (see: `BvaDispatchTask.outcode`), all request issues with at least one decision issue should have `closed_at` set to now, and `closed_status` set to `decided`

**Comment by leikkisa** [comment]
Looks good to me! I suppose we should also backfill data as part of this ticket.

**Comment by leikkisa** [comment]
Proposed script for data migration, tested in UAT:
```
RequestIssue.joins(:request_decision_issues).where(closed_at: nil).each{ |ri| ri.update!(closed_at: ri.request_decision_issues.first.created_at, closed_status: 'decided') }
```
I started by looking at decision_sync_processed_at for the datetime but it is nil for most of them.  UAT has decision issues without request issues, but checked in prod and don't believe that is the case there.

**Comment by leikkisa** [comment]
Due to https://github.com/department-of-veterans-affairs/caseflow/issues/9767, I would like to do this migration sooner than later, even if that means we have to do it again one after Shane is done backfilling decision issue data.

**Comment by leikkisa** [comment]
I decided to go ahead and just run this.

**Comment by pkarman** [comment]
verified in production:
```
irb(main):002:0> RequestIssue.where(closed_status: "decided").count
[2019-03-11 16:00:50 -0400]    (4.8ms)  SELECT COUNT(*) FROM "request_issues" WHERE "request_issues"."closed_status" = $1  [["closed_status", "decided"]]
=> 889
```
