### ISSUE TITLE
Adjust options for schedule hearing admin actions from attorneys

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9558]
When attorneys assign `Schedule hearing` admin actions to VLJ Support, the hearing branch needs VLJ Support to confirm that a hearing actually needs to be scheduled, so they aren't assigned schedule hearing tasks that don't need to be scheduled, and therefore delay the Veteran's appeal.

Related [slack thread](https://dsva.slack.com/archives/C6E41RE92/p1550692146046300).

## AC
- When VLJ Support is assigned a Schedule hearing task, give them the following options in the Actions drop down:
   - `Hearing does not need to be scheduled, send back to attorney`
   - `Hearing does need to be scheduled, send to hearing branch`
- If user selects `Hearing does not need to be scheduled, send back to attorney`, follow current send back to attorney behavior
- If user selects `Hearing does need to be scheduled, send to hearing branch` follow current send to hearing branch behavior 

## Note
- Current send to hearing branch behavior for legacy appeals is changing VACOLS location to 57. We now know that Caseflow Hearing Schedule uses the CASEFLOW location for cases that need a hearing. I don't think we should change the behavior to changing the location to CASEFLOW right now, because I assume that there are additional things that would need to happen in order to replicate what happens during the nightly location 57 --> CASEFLOW location job so the case shows up correctly in Caseflow Hearing Schedule.

**Comment by lowellrex** [comment]
SMALL. Update [`ColocatedTask.available_actions_with_conditions()`](https://github.com/department-of-veterans-affairs/caseflow/blob/7637541741a56cf4529f62ac46b63d0595b4416a/app/models/tasks/colocated_task.rb#L52) with this new logic.

**Comment by aroltsch** [comment]
> If user selects Hearing does not need to be scheduled, send back to attorney, follow current send back to attorney behavior. 

@laurjpeterson currently, if it is a hearing schedule task, there is no option to send it back to the attorney. Do we want to add that new option?

![image](https://user-images.githubusercontent.com/3811786/54704806-dc0ede80-4b11-11e9-9f00-7d8c57505abb.png)

**Comment by aroltsch** [comment]
@youngfreezy Test scenarios that should be present in the PR in spec/feature/queue/colocated_task_queue_spec.rb:

1. When a vjj user sends a legacy case to the schedule hearing team, ensure the case location is set to “57”. Case location is saved in BRIEFF.BFCURLOC
2. When a vjj user sends a legacy case to the attorney, ensure the case is visible under attorney’s queue. Follow example here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/feature/queue/colocated_task_queue_spec.rb#L30

**Comment by youngfreezyVA** [comment]
Hi @aroltsch for #1, this is what I did to verify. is this correct? 
https://www.evernote.com/l/AM5TrrPjjLhFnpQcpsXV96aI3OQp5UhpQIQ

**Comment by aroltsch** [comment]
This is correct as well!

**Comment by laurjpeterson** [comment]
What I'm proposing in the original AC is for the following options to be available in the Actions dropdown:

Actions drop down:
- Hearing does not need to be scheduled, send back to attorney (this is what i think answers your question - yes, let's add the send back to attorney option)
- Hearing does need to be scheduled, send to hearing branch (replaces the existing "Send to hearing branch" action)
- Place hold
- Cancel task

**Comment by youngfreezyVA** [comment]
hey @lowellrex @aroltsch and I were just discussing, these two methods:
`tasks_controller.rb`
``` def update
    tasks = task.update_from_params(update_params, current_user)
    tasks.each { |t| return invalid_record_error(t) unless t.valid? }

    tasks_to_return = (queue_class.new(user: current_user).tasks + tasks).uniq

    render json: { tasks: json_tasks(tasks_to_return) }
  end```

and 
`models/tasks/colocated_task.rb`
```def location_based_on_action
    # need to add more logic to differentiate between sending back to attorney or specific location number when vlj selects "Schedule hearing, send back to attorney"
    binding.pry
    case action.to_sym
    when :translation, :schedule_hearing
      LegacyAppeal::LOCATION_CODES[action.to_sym]
    else
      assigned_by.vacols_uniq_id
    end
  end```

need to be updated in order for a vlj user to actually send back a colocated task to an attorney. right now the location is being set to `57` in `location_based_on_action`.  I will ping you on Tuesday when you're back!

**Comment by lowellrex** [comment]
Can we train folks to use the "Cancel task" option and update `ColocatedTask.location_based_on_action()` to correctly route the legacy case to the assigner when the task is cancelled?

**Comment by laurjpeterson** [comment]
@lowellrex - I think the main motivation behind the ticket was to make sure VLJ Support Staff investigated whether a hearing actually needed to be scheduled, rather than just sending everything to the hearing branch. 

I think you're right, we can accomplish this with just the Cancel task option, though we'll need to make sure our users understand it. Options are now:
- `Hearing does need to be scheduled, send to hearing branch` (replaces the existing "Send to hearing branch" action)
- `Place hold`
- `Cancel task`

(We could also add language to the Cancel task option, like "Cancel task, return case to previous owner" - is this generic enough to be used everywhere?)

I also think we may want to re-name the "Schedule hearing" task name to "Investigate potential missed hearing" or something like that, so VLJ Support Staff are motivated to confirm that a hearing needs to be scheduled.

**Comment by lowellrex** [comment]
Agree with your entire comment LP! Sounds like a good path forward.

**Comment by youngfreezyVA** [comment]
@laurjpeterson does this mean that `Assign to Privacy team1 

> @lowellrex - I think the main motivation behind the ticket was to make sure VLJ Support Staff investigated whether a hearing actually needed to be scheduled, rather than just sending everything to the hearing branch.
> 
> I think you're right, we can accomplish this with just the Cancel task option, though we'll need to make sure our users understand it. Options are now:
> 
> * `Hearing does need to be scheduled, send to hearing branch` (replaces the existing "Send to hearing branch" action)
> * `Place hold`
> * `Cancel task`
> 
> (We could also add language to the Cancel task option, like "Cancel task, return case to previous owner" - is this generic enough to be used everywhere?)
> 
> I also think we may want to re-name the "Schedule hearing" task name to "Investigate potential missed hearing" or something like that, so VLJ Support Staff are motivated to confirm that a hearing needs to be scheduled.

@laurjpeterson does this mean `Assign to Privacy Team` shouldn't be included in the options above?

**Comment by laurjpeterson** [comment]
@youngfreezyVA - i do not think Assign to Privacy Team should be there.

@lowellrex added `Assign to Privacy` to be an option for all Colocated tasks back in Oct/Nov in response to something from VLJ Support, so will ask him to explain further if he wants to keep it. 

I recognize removing `Assign to Privacy` might warrant its own separate github issue and if so, you don't need to finish it within this ticket. if it's easy to do though, great!

**Comment by lowellrex** [comment]
> so will ask him to explain further if he wants to keep it.

I think it's fine to get rid of that option for schedule hearing tasks.
