### ISSUE TITLE
Route Claim |  Display Alert Route Claim unable to create EP (Full Grants w/ Special Issue, & no RO Email)

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#957]
As a Caseworker, when I am working a case that is a Full Grant with a special issue for whom we cannot create an EP in Caseflow and we _do not_ have an email address, I would like to have message displayed so that I am aware of the situation.

# Acceptance Criteria
1. Verify that after clicking the **_Route Claim_** button on the `Decision Review` page and the case is a Full Grant with unsupported Special Issues and no RO Email available, the `Route Claim` page is displayed with the following Title, Alert message, and subtext:  (Refer to Mockup)

     **Title**

     > Route Claim

     **Alert Message**

     > This claim for Vet ID# [VeteranID] includes Special Issue(s):  [Special Issue Name] not handled by Casflow

     **Subtext**

     > You selected a Special Issue Category that cannot be processed in Caseflow at this time.
     > 
     > Please select Release Claim and proceed to process this case manually. 
1. Verify that on the `Route Claim` page when there is no RO/Center of Jurisdiction email available, the following data element is displayed (refer to mockup):

     - **I confirm that I have sent an email to route this claim.** - confirmation of email being sent.

1. Verify that the following links are available:  
     - **_Back to Decision Review_**
     - **_Cancel_**
1. Verify that the following button is available:  **_Release Claim_**
1. Verify that when "I confirm that I have sent an email to route this claim." has been checked and there is _no_ RO Email, the **_Release Claim_** button has been enabled.
1. Verify that after clicking on the **_Release Claim_** button, the `EP Confirmation` page is displayed with the following checklist items (refer to mockup):

     - Reviewed Decision
     - Processed case outside of Caseflow

1. Verify that after clicking on the **_Cancel_** link, the `Stop Processing Claim` modal is displayed.
1. Verify that after clicking on the **_Back to Decision Review_** link, the `Caseworker Dashboard` page is displayed.

## Mockups
_**View - Route Claim - Alert (no RO Email Available)**_
<img width="673" alt="route claim - alert - release claim disabled" src="https://cloud.githubusercontent.com/assets/23063044/23077543/062d6148-f513-11e6-8644-320b49a59129.png">

_**View - Route Claim - Alert (no RO Email Available) - Finish Routing Claim button enabled**_
<img width="644" alt="route claim - alert - release claim enabled" src="https://cloud.githubusercontent.com/assets/23063044/23077554/0f11783a-f513-11e6-99c7-19eb9be15ad1.png">

_**View - EP Confirmation**_
<img width="743" alt="ep confirmation" src="https://cloud.githubusercontent.com/assets/23063044/23077570/1cffd5a4-f513-11e6-8857-7d80849e0af8.png">

_**View - Stop Processing Claim**_ 
![stop processing claim](https://cloud.githubusercontent.com/assets/23063044/23077115/2eda984c-f511-11e6-80ce-6dda2238ca74.PNG)

# Related Stories
Route Claim | Display Informational Route Claim unable to create EP (Full Grants with Special Issues) #722

**Comment by kierachell** [comment]
Functionality is there but:
![95b4c708-f675-11e6-892a-c4585281b8f1](https://cloud.githubusercontent.com/assets/18075411/23333502/83790e48-fb5a-11e6-849a-ebfebf02d6de.png)

The mocks are not following the **Lara's Decree**
@nikitarockz @lakohl please confirm if the mocks are correct.

Otherwise, functionality is confirmed on `uat`

![screenshot_2017-02-25_12-59-26](https://cloud.githubusercontent.com/assets/18075411/23333490/452e9dc4-fb5a-11e6-8a8e-51f49669a610.png)
![screenshot_2017-02-25_12-58-52](https://cloud.githubusercontent.com/assets/18075411/23333491/4534bc4a-fb5a-11e6-8b79-62486f75f2ba.png)

**Comment by kierachell** [comment]
@nikitarockz
Also, need an update if the following view in **Work History** displays correct _Action_ information based on **Release Claim** use case:
![screenshot_2017-02-25_13-03-39](https://cloud.githubusercontent.com/assets/18075411/23333522/e2272efc-fb5a-11e6-96a6-2a68ef459ef6.png)

**Comment by lakohl** [comment]
The veteran's name should show as first name last name, in title case, not sentence case.

The line below the checkbox can be wider than the word 'Congratulations.'
See mock for copy:
<img width="635" alt="screen shot 2017-02-27 at 4 48 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/23381500/b076d8ae-fd0c-11e6-8708-fa15a6325c0d.png">

**Comment by kierachell** [comment]
Currently on `uat`:

<img width="1042" alt="screen shot 2017-03-06 at 10 15 13 am" src="https://cloud.githubusercontent.com/assets/18075411/23616240/2214515e-0257-11e7-8307-47b166bb4f94.png">

![screenshot_2017-03-06_10-25-37](https://cloud.githubusercontent.com/assets/18075411/23616281/493f2c36-0257-11e7-8d1f-b5258072b432.png)

**Comment by kierachell** [comment]
**PASSED**
validated on `uat`

<img width="1065" alt="screen shot 2017-03-09 at 12 20 36 pm" src="https://cloud.githubusercontent.com/assets/18075411/23762087/fc4896f6-04c2-11e7-9c74-6839c316ac6d.png">

going to make a separate *Back to Decision Review* link issue
