### ISSUE TITLE
Appeal Outcoding | Wait until the decision date to process the outcoding

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9571]
We are seeing errors come in when we process some outcodings.

See:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3803/events/250788/

The solution here is to not attempt to process the decision document until the decision date. Confirmed with Lauren and Allyce.

## Acceptance criteria

Not sure if there's a way in UAT to manually set the decision date in the future, but if it is, then the way to test this would be to verify that the decision document record has a submitted_at date value that equals the decision date.

Will need IDT help from Anya

**Comment by Sjones352** [comment]
@pkarman validating this in UAT.
I set the decision date for a future date 
<img width="1119" alt="screen shot 2019-03-08 at 12 26 34 pm" src="https://user-images.githubusercontent.com/23080951/54044944-3ddc5980-419e-11e9-890a-9369abdcea9d.png">
 
**Created Ep**
<img width="800" alt="screen shot 2019-03-08 at 12 32 39 pm" src="https://user-images.githubusercontent.com/23080951/54044979-577da100-419e-11e9-8e40-81f2bdb92097.png">

**Ep Status**
<img width="1642" alt="screen shot 2019-03-08 at 12 33 55 pm" src="https://user-images.githubusercontent.com/23080951/54045042-87c53f80-419e-11e9-8483-77a3d4462c6e.png">

Wondering how I can validate this part `verify that the decision document record has a submitted_at date value that equals the decision date`

**Comment by pkarman** [comment]
This step:
"Will need IDT help from Anya"
is the trick. We need @aroltsch to help us step the decision process through its paces so we end up with a DecisionDocument record. I believe she has done that before for Steve so you might just ask her.

**Comment by aroltsch** [comment]
From what I understand, I need to outcode the appeal with the decision date in the future.

**Comment by aroltsch** [comment]
I outcoded the appeal in UAT and set the decision date to 1.day.from_now. Here is what I did in rails console:

```
uuid = "ed984057-cc2b-473b-a6cf-76b1145667d2".upcase
a = Appeal.find_by(uuid: uuid)
a.tasks.where(type: "BvaDispatchTask").delete_all
RequestStore[:current_user] = User.last
a.request_issues.each do |r|
decision_issue = DecisionIssue.create!(disposition: "allowed", description: "anya test", benefit_type: r.benefit_type, diagnostic_code: "5000", participant_id: a.veteran.participant_id, decision_review: a)
RequestDecisionIssue.create!(decision_issue: decision_issue, request_issue: r)
end
root_task = a.tasks.find_by(type: "RootTask")
BvaDispatchTask.create_from_root_task(root_task)
u = a.reload.tasks.find_by(type: "BvaDispatchTask", assigned_to_type: "User").assigned_to
file = "1234"
citation_number = "A19000051" 
BvaDispatchTask.outcode(a.reload, { citation_number: citation_number, decision_date: 1.day.from_now, redacted_document_location: "\\\\bvacofil1.dva.va.gov\\archdata$\\arch1901\\A19000042.txt", file: file }, u)```

**Comment by Sjones352** [comment]
Created Ep in UAT
<img width="1283" alt="Screen Shot 2019-03-12 at 2 41 14 PM" src="https://user-images.githubusercontent.com/23080951/54226944-3c2fd000-44d5-11e9-983e-718db73bdf93.png">

<img width="1319" alt="Screen Shot 2019-03-12 at 2 41 03 PM" src="https://user-images.githubusercontent.com/23080951/54226942-3c2fd000-44d5-11e9-8e9b-9cb98a2722e3.png">

<img width="1680" alt="Screen Shot 2019-03-12 at 1 51 50 PM" src="https://user-images.githubusercontent.com/23080951/54226941-3c2fd000-44d5-11e9-8468-69888f83f10c.png">

Verified that  submitted_at equals decision_date
<img width="1679" alt="Screen Shot 2019-03-12 at 3 02 03 PM" src="https://user-images.githubusercontent.com/23080951/54228119-de50b780-44d7-11e9-9741-2a7553e369e0.png">



@aroltsch set the decision date to 1.day.from_now
```a.decision_documents
[2019-03-12 13:59:58 -0400]   DecisionDocument Load (0.7ms)  SELECT  "decision_documents".* FROM "decision_documents" WHERE "decision_documents"."appeal_id" = $1 LIMIT $2  [["appeal_id", 139], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy [#<DecisionDocument id: 33, appeal_id: 139, citation_number: "A19090051", decision_date: "2019-03-13", redacted_document_location: "\\\\bvacofil1.dva.va.gov\\archdata$\\arch1901\\A1900004...", created_at: "2019-03-12 17:59:51", updated_at: "2019-03-12 17:59:51", submitted_at: "2019-03-13 00:01:00", attempted_at: nil, processed_at: nil, error: nil, uploaded_to_vbms_at: nil, last_submitted_at: "2019-03-13 00:01:00">]>
