### ISSUE TITLE
Create judge teams for new judges

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9580]
There are new judges at the Board - former senior counsel and former chiefs - that need to have judge teams for them to manage and assign cases to their attorneys. 

## AC
- Judge teams are added for the following judge(s):
David Brenningmeyer (BVADBRENN)

 
~~Lauren Cryan
Cynthia Skow
William Donnelly
Evan Deichert
Michael Donohue
Claudia Trueba
Robert Scharnberger
Bethany Buck
James March
John Z. Jones
Keith Allen
Theresa Catino
Cynthia Bruce
Anthony Scire
Cherry Crawford~~

**Comment by marvokdolor-gov** [comment]
I feel like a number of these people have judge teams? e.g. Cherry Crawford: https://appeals.cf.ds.va.gov/organizations/bvaccrawfor/users
I've seen this names in tickets to add and remove attorney's in the past. 
Or am I off-base with what's needed here?

**Comment by lowellrex** [comment]
Created `JudgeTeam` for Judge Brenningmeyer. URL: `/organizations/bvadbrenn`
