### ISSUE TITLE
EPIC | Printable Views of Daily Dockets

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9581]
## User Stories
As a Hearings Branch user, I need to be able to print the daily docket so I can coordinate my hearing day away from my desk.

As a Judge, I need to print my Daily Docket so that I can make notes and see my schedule at a glance for the day. 

## Related Tickets
#9168 Printable View of Hearing Schedule Daily Docket
#9333 Printable View of Hearing Prep Daily Docket

**Comment by lomaxap** [comment]
No longer need hearing prep printable view. duplicate of #9168
