### ISSUE TITLE
Managing paper cases at the Board

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9583]
The Board needs a way to manage paper cases. These cases typically come from non-Compensation/non-VBMS business lines.

**Comment by nicholasholtz** [comment]
The Board has provided this information about their needs (high-level analysis in [brackets] where applicable):

- Add a mandatory Caseflow field for business lines to input a tracking number when marking a task as complete.
- Add a field in Caseflow where the Case Review team can verify that the file was received.
- Add an automatic notification to the business line once verification of the receipt of file is completed by the Case Review team. [it is not clear what the purpose of this is, and has not been asked for by the business lines]
- Determine how the location of the physical file be noted in Caseflow, possibly by adding a prompt in Caseflow about where to retrieve the file from. [not clear what this means; if this is about tracking a physical file in and around the Board, (a) this is a backwards-looking fix, since they should be looking for ways to manage these files without moving paper (any functionality along these lines should be quickly obsolete, and thus that is strong reason to not build such a thing); (b) it is not clear why the case would need to move around physically, at least until the file was with an attorney; regardless, there are not "locations" in Caseflow - tasks are always assigned to individuals]
- Add a prompt to Caseflow such that when a task is created for a paper case, a reminder pops up to move that paper file to the proper location for that person to complete the task. (If applicable.) [there are not "locations", so to the extent a paper file is moving, it should follow the user to which the case is assigned]
- Add a Caseflow field to input a tracking number when files are sent back via UPS/FedEx so the business line can track it.

**Comment by nicholasholtz** [comment]
See also: https://github.com/department-of-veterans-affairs/caseflow/issues/9887

**Comment by laurjpeterson** [comment]
Related: https://github.com/department-of-veterans-affairs/caseflow/issues/10872

**Comment by alisan16** [comment]
This request has come up again, this time regarding the education business line.
Notes from discussion with Mike Sanford:
> Mike is unsure this is a Caseflow problem. A lot of cases that come from various AOJs (NCA, VHA) have not been scanned into VBMS. There is a phyiscal file that needs to be worked. No way for those appeals to get into Caseflow right now. These AOJs are unable to fulfill AMA Section 5 for congressional reporting - this is past due. Research and design will hopefully start this year according to Geoffrey
