### ISSUE TITLE
Bug: video reschedule selected 12:30 pm time, shows up as 1:30 pm time on daily docket.

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9584]
Tamisha rescheduled Veteran for a legacy video hearing for 12:30 pm on 4/9/19, but it's showing up as 1:30 pm. 

Something is wrong with the time as it's working on daily docket.

Update 2/26/19 - AMA cases are showing up as having 9/1 time slots. I instructed Tamisha to schedule with a note, but issue persists.

**Comment by mdbenjam** [comment]
Want to make sure I understand all the correct values here.

Should there be any difference between AMA and Legacy?

And is it:
Video: 8:30, 12:30?
Central: 9, 1?

**Comment by mdbenjam** [comment]
And, is this is happening for all cases? Or just the one you pointed out?

**Comment by mdbenjam** [comment]
I'm seeing things like this in the fake data:
```
9:30 am ET /
8:30 am CT 
Muskogee, OK
```
Does this seem right? It should be 8:30 AM for whatever timezone the veteran is in?

**Comment by MeredithStewart** [comment]
There should be no difference between AMA and legacy for time. 

Times for video and CO above are correct.

Yes, time selected should be for Veteran’s time zone. 

We were seeing this problem for hearings postponed through the daily docket. I think it was working from the regular schedule Veterans modal.

**Comment by sharonwarner** [comment]
The AMA 9:00/1:00 bug was fixed in a separate PR.
