### ISSUE TITLE
Deprecate DAS Tech Spec

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9588]
Original tech spec : https://docs.google.com/document/d/1hPTu7ihUCVhlV44tssILLQGUhO0F6j2hJXARwAD409U/edit?ts=5c6ef86a#

Reference: https://github.com/department-of-veterans-affairs/caseflow/issues/7809

AC:
1. Understand the path forward
2. Create engineering tickets where possible

# Tech Spec

## Background

Earlier this year, VA was planning to move VACOLS to a different data center since there was no clear timeline for deprecation. In response to this, the Caseflow team gave VA a ballpark timeline of March 2020. Although BVA is optimistic about Appeals Modernization Act readiness at this point, there are some signs of skepticism about the overall project of VACOLS deprecation. Some people believe that VACOLS could be around for another ten years. 

After February 14th, the Caseflow team should begin a strategic shift towards VACOLS deprecation to ensure long-term appeals program health. This lays out some thinking about the first major phase of that process, deprecating the piece of the system attorneys and judges use to review cases (DAS, or Decision Assignment Sheet) and deprecating task management from the judge step of the process to when an appeal leaves the Board (Dispatch).

Also, Queue's DAS integration is a constant thorn in our side. Some of the problems it has caused are:

1. DAS tasks do not have unique ids
2. Our frontend code is needlessly complex, handling both Caseflow and Legacy (DAS) tasks
3. While our Task model allows multiple tasks to be assigned at once, DAS does not
4. We have had several bugs with our integration (Duplicate DECASS recrods, OMO attorney credit, etc.)

Deprecating DAS will make our code simpler, more maintainable, reduce bugs, and move us one step towards our long term goal of deprecating all of VACOLS.

## Goals
* Make substantial progress on deprecating VACOLS — deprecate DAS before the end of the contract
* Maintain judge trust in and adoption of Caseflow

## Strategy/Approach
* Communicate with users to surface concerns well in advance (think 1 month) of any deprecation that affects them.
* Make very small steps at first, as confidence and trust in the process goes, make larger steps.
* Make only reversible steps.
* Where possible, always pilot with a team first.
* Don't migrate data, divert it.

### Communicate with judges to build adoption (end of Feb)

Judge trust and adoption has been an issue in the past. Judges are a senior group at the Board, and we’ll have to get some degree of buy-in from this group to move forward. So we should communicate our plans and seek feedback early by sending an email like:

As you know, VACOLS is slated to be deprecated. This will be a gradual process.

We are planning to turn off DAS at some point in the future, although we do not have a date yet. We will ensure that you continue to have the reporting functionality you need — eventually, we will transition to other reports, but when we turn off the DAS, data will still populate these reports for legacy appeals only. What actions do you take in DAS that Caseflow doesn't support? What concerns do you have? Your comments will influence our timeline, and we will attempt to address all major use cases. Even after we turn off the DAS UI, if you find that you can't do something with Caseflow that you used to do with DAS, you can submit feedback and we will work with you to find a resolution.

Cases will still be able to be searched for and visible in VACOLS — and dispositions set in Caseflow will be contained in VACOLS.

### Close the remaining feature gap between Caseflow and DAS (excluding DAS reporting capabilities)
- [x] Reassignment from attorney to judge using Caseflow 
    - this can be accomplished by cancelling tasks. 
- [ ] Ability for judges to send legacy cases back to attorneys for re-writes
- [ ] Assignment to acting judge as judge or as attorney using Caseflow.
   - LP note: we may not need to cover this
- [ ] Reassignment from judge to IHP-writing VSO if POA changes using Caseflow. 
   - https://github.com/department-of-veterans-affairs/caseflow/issues/8336 
   - https://github.com/department-of-veterans-affairs/caseflow/issues/7784 
- [ ] Allow attorneys to view judge comments about their decisions in Caseflow
   - https://github.com/department-of-veterans-affairs/caseflow/issues/7637 

### Replicate Case Timeline (Judge/Attorney/Judge/Dispatch) for legacy appeals
- We already have this for AMA appeals
- If we go straight to Caseflow tasks and stop creating DAS records from the outset, hopefully those Caseflow tasks can populate Case Timeline for legacy appeals the way it does for AMA appeals right now. 

- Alex's idea: case timeline for legacy appeals should incorporate VACOLS locations for user clarity.
   - Query a case's locations — stitch together LOCATIONS tab and Caseflow tasks using the date in case timeline. This is important to give users a full picture so they can help us debug and have visibility.
   - E.g.
      - Case moved to VACOLS location XXX.
      - Case moved to Case Storage - Location 20 in VACOLS.
      - Judge James Ridgeway was assigned case. 12/12/2000
      - Judge assigns case to Attorney Sarah Steamboat
      - Sarah Steamboat completes OMO Request.
      - Judge approves OMO Request on 12/20/2000.
      - Case moved to VACOLS location OMO - Location 20 on 12/20/2000.
      - Case moved to location 32 on 12/20/2000.

### Turn off the DAS UI (target March-April)?
We’ll ask Jed to simply remove DAS from list of VACOLS applications, but we will leave everything else the same for now, and not make any changes on our end. Wait 2 weeks for complaints/problems. If there are none or if we're able to address all of them, continue. Otherwise, we enable DAS until we address any critical concerns.

LP note: we may want to turn of DAS _after_ the April attorney/judge performance reviews

### Divert task management for judges and attorneys from DAS to Caseflow, but backfill DAS DB records when a judge signs the case

This way, we deprecate DAS task management *without* affecting reports.

Auto-case distribution creates Caseflow JudgeTasks and changes the location to CASEFLOW instead of changing the VACOLS location when a case is assigned to a judge. 

We still query both Caseflow and VACOLS for a judge's tasks to catch cases coming back from OMO. 

The Judge/attorney loop uses the Caseflow Task model and /tasks endpoints instead of the LegacyTask model and /legacy_tasks, but we create DAS records and update VACOLS location after the judge signs a case or approves OMO requests.
- Pilot this with one judge/attorney group first.

### DAS reports are replicated in Caseflow /  Tableau.
At this point, we should be able to ensure that previous DAS and VACOLS reports are untouched but we have both legacy & AMA data in Caseflow reports.

### Create OMO team queue in Caseflow (might not need to)
"We currently only allow OMO requests for legacy tasks. However, allowing them for Caseflow tasks should be relatively straightforward. We already record them in our (attorney|judge)_case_reviews table. The main change here is to use our tasks, while either still updating the location of the VACOLS record to be the OMO office, or to roll out a queue to the OMO team for them to monitor OMO requests." (https://github.com/department-of-veterans-affairs/caseflow/issues/7809)

### Caseflow stops creating DAS records	
However, we continue updating dispositions in VACOLS on judge case review, and continues updating VACOLS location to either QR or BVA Dispatch. 

### Move QR team fully to Caseflow. 
QR tasks are created as Caseflow tasks for legacy appeals, but update VACOLS location to BVA Dispatch afterwards.

### Move BVA Dispatch team fully to Caseflow.
After QR, BVA Dispatch tasks are created as Caseflow tasks and are outcoded using Caseflow.

**Comment by laurjpeterson** [comment]
Notes:
- Could we go straight to Caseflow tasks instead of backwards compatibility with DAS until we turn off the DAS UI? Like we did for VLJ Support (Co-located) by using the CASEFLOW location in place of updating all of the VACOLS functionality
- Need to have another conversation about Acting Judges again
- Can choose a judge/attorney team where there are no Acting Judges in the meantime

**Comment by laurjpeterson** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/9930

**Comment by laurjpeterson** [comment]
Note: Talked with Jennifer White - they stopped OMO requests on 2/19/19. OGC agreed that they no longer needed to do OMO requests for legacy.

**Comment by hschallhorn** [comment]
Moving under #9930
