### ISSUE TITLE
Clean up feature toggles

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9590]
## AC:
Go through feature toggles that are enabled for all in appeals-deployment in production env and delete those in Caseflow and from appeals-deployment.

#### Done previously (thanks @Sjones352 !)
- [x] create_board_grant_effectuations
- [x] decision_reviews
- [x] judge_case_review_checkout
- [x] ama_decision_issues
- [x] case_search_home_page
- [x] intake_reserved_file_number
- [x] vbms_include_user - set to `true`
- [x] claims_service_v5 - set to `true`

#### Remove from Caseflow code and appeals deployment. 
- [x] attorney_assignment_to_colocated - remove `featureToggles` from view

#### These only need to be removed from appeals deployment:
- [x] decision_document_upload
- [x] ama_acd_tasks
- [x] idt_ama_appeals
- [x] intake_legacy_opt_in
- [x] automatic_case_distribution

## Technical notes
A minimum of 2 PRs is required (more is cool too).
Feature toggles should not be removed from appeals_deployment until the PR removing their code from Caseflow has been merged for one day.

Removing feature toggles in appeals deployment is done here:
`appeals-deployment/ansible/vars/features-config.yml`

This is not necessary for this PR, but for reference, here are instructions for checking if a feature toggle has been turned on in production for over a month:
e.g. `git blame ansible//vars/features-config.yml | grep "decision_reviews"`

**Comment by jimruggiero** [comment]
Estimated at a 3 in lieu of additional context regarding Anya's suggestion to do this in multiple PR's and not know enough about what's involved with removing these from appeals deployments.

**Comment by jimruggiero** [comment]
@Sjones352 Can you provide any additional context to finalize estimation and next steps?

**Comment by Sjones352** [comment]
@jimruggiero this may take a little while because they are multiple feature toggles and tests may need to change. I will look into it further on Monday
