### ISSUE TITLE
Remove code related to decision_document_upload feature toggle once the feature is rolled out to all users

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#9591]
Currently, there is logic in `BvaDispatchTask#outcode` and `DecisionDocument#submit_for_processing!` that doesn't upload a decision document to VBMS if the Feature Toggle `decision_document_upload` isn't enabled for the current user. Eventually, we plan on rolling this out to all users, at which point we should remove this logic.

**Comment by laurjpeterson** [comment]
Duplicate, closing.
