### ISSUE TITLE
Post-AMA Frontend technical debt

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#9592]
This is a meta ticket for frontend technical debt I believe we should work on. Would love to get people's thoughts on some of these topics.

1) CSS in the application
   - We have no real organization of our CSS. A lot is in a common file, some are in files specific to components, and some are in the component files themselves. We should standardize on an approach.
   - My preference is in-component styles.
   - There are likely lots of styles that can be removed.
2) Component clean up
   - Lots of our components are messy. They have lots of props, some are only used in 1-2 places. Some of the components need very specific css classes applied to work.
   - Components should be drop in and should just work.
   - We need to add new styling components so that developers don't have to write CSS. For example an `<IndentText>` component and a `<Note>` component that grays out text. I'd like to encapsulate our commonly used styles into components.
3) Consolidate Caseflow Frontend Toolkit.
   - About a year ago one of our developers started moving some of our components to a separate repo called caseflow-frontend-toolkit. The problem is only a small subset of components were moved over and there wasn't buy in from the team.
   - We either need to go all in on the toolkit or fold it back into Caseflow. I think if we get our components into a solid state where there isn't much churn, moving them to the toolkit is a good idea. Otherwise we need to probably just fold them back in.
4) Too much state in redux
    - When we moved to use redux we put everything in redux and left nothing in local state. I think this has made our frontend more complex than necessary.
    - I don't know that it makes sense to remove things from redux, but it might be good to set guidelines for when things should be in redux and when they should be in local state.
5) Apps are in separate router hierarchies so that moving from one app to another requires page loads.
   - Not sure if this is something we should definitely do, but I think it would be nice if all of our apps were under one react router so that moving between them was more seamless.

**Comment by Sjones352** [comment]
@mdbenjam this is really good. I totally agree with you on `CSS in the application`.  Having recently refactored the Hearing-prep print-page, I realized we had too much redundant code in this app and so I believe that having  in-component styles makes more sense. I am happy to take a lead on this one and start refactoring Hearing-prep and Schedule.
