### ISSUE TITLE
Add instructional copy to explain ineligible issues in Case Details

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9604]
## Ineligible issues
Context: We currently display ineligible issues on the Case Details page, but not during the checkout flow (need to confirm with @aroltsch ). We should include some instructional copy so that attorneys know what they are, what's going on (that Caseflow is just capturing these issues for reporting purposes), and that they don't have to action on these issues. 

## Proposed solution
- Add instructional copy to the Issues section of the Case Details page whenever there is an ineligible issue. This copy should communicate what an ineligible issue is, why we display it, and that the attorney doesn't have to decide on it.

**Comment by laurjpeterson** [comment]
@youngfreezyVA - I unassigned you from the other instructional text for auto case distribution ticket and instead assigned you to this one as a stretch goal for this sprint. I think I actually meant to pull this ticket into this sprint. Let me know if that works for you and @aroltsch!

**Comment by laurjpeterson** [comment]
Needs design and copy. Related: https://github.com/department-of-veterans-affairs/caseflow/issues/9879

**Comment by laurjpeterson** [comment]
@aroltsch - I thought we also hid ineligible issues from the Issues section of Case Details, just like we hide them from check out flows. Could you help me confirm this?

If we already do hide ineligible issues from Case Details, then we can close this ticket.

**Comment by aroltsch** [comment]
I am confused by this ticket. Is it for unidentified or ineligible request issues? I think these two "statuses" are different from each other? I think we'd still like to display an `unidentified` issue on case details so an attorney can correct this issue in the request issue edit page? Yes, ineligible request issues are hidden from Case Details.

**Comment by pkarman** [comment]
@aroltsch is correct. `unidentified` is a category like `rated` or `nonrated`

Any one of those 3 could be ineligible.

**Comment by laurjpeterson** [comment]
@aroltsch - ah, sorry for the confusion. This ticket began by being about both ineligible and unidentified. Since Peter made another ticket about unidentified issues (#10950) I transferred all the info about unidentified issues from this one to that one, but didn't update the ticket title. 

This ticket will just be about ineligible issues.

Do we already hide ineligible issues from the Issues section of Case Details, just like we hide them from check out flows?
