### ISSUE TITLE
Bug: Daily Docket allowing over-booking of rooms and lists unavailable days

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9607]
The Daily Docket is allowing Postponements and rescheduling to days that are already fully booked. 
- For ROs with 2 hearing days per date, both are listed in the postponement drop down regardless of slots left open on that day
- Postponement and rescheduling is successful and puts Veterans on the Daily Docket in excess of the available slots
- Attempting to postpone to another room/day with open slots on the same calendar date fails 
- The Schedule Veterans view is correct and removes unavailable days

See Tamisha's email screenshot for details

**Comment by MeredithStewart** [comment]
Modal for assigning Veterans hearing days should be the same in the daily docket as it does for Schedule Veterans.
