### ISSUE TITLE
Stop throwing a Caseflow::Error::ActionForbiddenError when attorneys visit ColocatedTask pages

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9613]
Because of [how we build the list of cases](https://github.com/department-of-veterans-affairs/caseflow/blob/cddcaf4f0aa1837e45a15defc31db66078027da9/app/models/queues/attorney_queue.rb#L10) in an attorney's queue, we [occasionally get `Caseflow::Error::ActionForbiddenError`s](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3678/events/251695/) when an attorney visits the case details page for a `LegacyAppeal` attached to a `ColocatedTask` they created before the assignee visits the case details page ([when that happens](https://github.com/department-of-veterans-affairs/caseflow/blob/cddcaf4f0aa1837e45a15defc31db66078027da9/client/app/queue/CaseDetailsLink.jsx#L19) the status of the `ColocatedTask` would change from `assigned` to `in_progress`). We should not attempt to change the status of these tasks when attorneys visit these tasks since they are not assigned to them as an individual.

## Acceptance criteria
* [ ] Do not attempt to change the status of a task that is not assigned to the current user.
* [ ] Do not throw a `Caseflow::Error::ActionForbiddenError` when an attorney visits the case details page for a `LegacyAppeal` attached to a `ColocatedTask` they created.

**Comment by lowellrex** [comment]
SMALL.

**Comment by lowellrex** [comment]
We say we are [PATCHing](https://github.com/department-of-veterans-affairs/caseflow/blob/da6437a15641a68fc87210de6d05b923a1b99410/client/app/queue/CaseDetailsLink.jsx#L28) but in reality I am pretty sure we are just [POSTing](https://github.com/department-of-veterans-affairs/caseflow/blob/e9885adeedb6b597bac129187f74eafe53b5565d/client/app/util/ApiUtil.js#L77)

**Comment by lowellrex** [comment]
Another example here: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/events/269892/

**Comment by lowellrex** [comment]
This ticket is only to do the quick bug fix to stop the error. The work to enable this for all queues will be continued in #9916.

**Comment by tomas-nava** [comment]
another example: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/events/270327/
