### ISSUE TITLE
Create endpoint that accepts requests to bulk assign hearings management tasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9621]
This ticket exists to create an endpoint that accepts requests for the bulk assignment of tasks assigned to the hearings management branch (more specifics around this effort in [this ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/8620#issuecomment-463414729)).

## Acceptance criteria
* [ ] Endpoint responds to requests as expected

**Comment by lowellrex** [comment]
MEDIUM. Need to implement thorough tests here as well as extensive validations.

**Comment by annekainicUSDS** [comment]
@lowellrex Looking through these tickets related to bulk assigning tasks, it looks like this ticket is for Rails work and these two (https://github.com/department-of-veterans-affairs/caseflow/issues/9620 and https://github.com/department-of-veterans-affairs/caseflow/issues/9622) are for front-end work? I think I can take on the front-end work without this work being done first, but it won't be functional and probably shouldn't be merged until it's tested end-to-end.

**Comment by lowellrex** [comment]
@annekainicUSDS I think you're totally correct! I think we could merge the work from #9620 without this backend work, but should definitely hold off on merging #9622 until this work is done.

What the structure of the data passed to this endpoint will need to be determined, and I think we can do that work in this ticket or in #9620, whichever comes first.

**Comment by annekainicUSDS** [comment]
Tentative plan is to create a new controller, something like `BulkAssignTaskModal`, to specifically handle this feature. We could use the existing task controller, but we might overload it with this bulk assignment, so probably best to create a separate controller for this.

Information we need to send from the front-end is:
1. user_id of assignee
2. `type` of `task`
3. number (integer) of tasks to assign

The controller will have to handle the logic of figuring out which tasks specifically to assign based on the number of tasks sent. The logic should be to assign oldest tasks first.

**Comment by aroltsch** [comment]
Assign tasks in bulk endpoint:
* assignee ID
* parent_id
* task type
* appeal id
