### ISSUE TITLE
Create page for creation and management of Organizations

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9626]
Caseflow has a concept of [`Organization`s](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/organization.rb) that have members with access to certain behaviours of Caseflow based on organization membership. Administrators of individual organizations have access to a user management page for their organization like the one below:

![image](https://user-images.githubusercontent.com/32683958/53273894-57bc6d80-36c3-11e9-866d-a86f2b89c76e.png)

This page works well for the administration of individual teams. However, we lack a page where a "super" admin (like @marvokdolor-gov or likely somebody at the Board in the future) can get a quick list of all teams or even create new teams. I think this page could serve two purposes:
1. A centralized place for the creation of new teams (`JudgeTeam`s and `Vso`s in particular) and the modification (changing VSO's BGS participant IDs) or deletion (when a judge leaves the Board) of existing teams.
1. A place to find links to the user administration pages for each existing team.

**Comment by pkarman** [comment]
fwiw I typically reach for https://activeadmin.info/ when I need easy CRUD on an existing app. Easy to bolt on and configure. of course the look and feel will be different, but if the user base is tiny, maybe that's a reasonable tradeoff compared to developer time.

**Comment by monfresh** [comment]
I had the opposite experience, but that was 5-6 years ago. I spent so much time trying to get it to fit my use case and ended up writing my own admin interface for [ohana-api](https://github.com/codeforamerica/ohana-api/tree/master/app/controllers/admin) and that was a much more pleasant experience and easier to maintain.
