### ISSUE TITLE
Move BGS caching into request store

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#963]
Currently BGS caching happens at the appeal level. Consider moving it to the request level.

**Comment by nickheiner-usds** [comment]
> Consider moving it to the request level.

![image](https://user-images.githubusercontent.com/25331532/32746986-604a1f9a-c885-11e7-84ca-167a6eedaab9.png)

This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)

**Comment by sharonwarner** [comment]
Closed because it seems like nobody objected when Nick said he was going to close it.
