### ISSUE TITLE
Remove "(optional)" from special issues page for legacy appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9638]
Attorneys marking special issues is a key part of our ability to deprecate VACOLS, so we think we should remove the "optional" verbiage so attorneys don't overlook this page. 

We've added some more explanatory text to the page which helps attorneys know what special issues are and when to check the boxes, so we think this is sufficient.

Please also edit the copy on the Special Issues page:

From -  
"Select the special issues that pertain to this case. Cases with special issues are routed to specific groups who are in charge of adjusting the case."

To - 
Select the special issues that pertain to this case. If none, please select "No Special Issues." Cases with special issues are routed to specific groups who are in charge of adjusting the case.

## AC

- [x]  remove "(optional)" from title of the page
- [x] update copy under the Special Issues title

**Comment by hschallhorn** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||||||||||||||
2 | 
3 | 
5 | 
8 | 
```

Simply removing text.
