### ISSUE TITLE
Intake | Differentiate Rating vs Nonrating Appeal DTA errors

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9649]
> We are seeing 47 EP040s with the claim label of "Board DTA Error" which for our workload routing 
> workload is an obsolete claim label.  The current claim label for these claims should either have the 
> claim label of "Board DTA Error Rating" or "Board DTA Error Non-Rating".

https://dsva.slack.com/archives/CFBLH2LR4/p1551187534022500

## Acceptance criteria

* When a DTA error EP 040 is created for a nonrating issue, it should be "Board DTA Error Non-Rating".
* When a DTA error EP 040 is created for a rating issue, it should be "Board DTA Error Rating".

## Technical notes

* May need to identify different EP code for nonrating error. https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/end_product.rb#L25
* The DTA error selection mapping will need updating https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/request_issue.rb#L94

**Comment by shanear** [comment]
It seems like IMO is no longer necessary. This is the full list of 040's per Jane:

## 040 Supplemental EP
Board DTA Error Non-Rating
Board DTA Error Rating
HLR DTA Error Non-Rating
HLR DTA Error Rating
PMC Board DTA Error Non-Rating
PMC Board DTA Error Rating
PMC HLR DTA Error Non-Rating
PMC HLR DTA Error Rating
PMC Supplemental Claim Non-Rating
PMC Supplemental Claim Rating
Supplemental Claim Non-Rating
Supplemental Claim Rating

**Comment by leikkisa** [comment]
Ask Nate for the actual codes

**Comment by leikkisa** [comment]
Here are the codes:
Board DTA Error Non-Rating - 040BDENR
Board DTA Error Rating - 040BDER
HLR DTA Error Non-Rating - 040HDENR
HLR DTA Error Rating - 040HDER
PMC Board DTA Error Non-Rating - 040BDENRPM
PMC Board DTA Error Rating - 040BDERPMC
PMC HLR DTA Error Non-Rating - 040HDENRPMC
PMC HLR DTA Error Rating - 040HDERPMC
PMC Supplemental Claim Non-Rating - 040SCNRPMC
PMC Supplemental Claim Rating - 040SCRPMC
Supplemental Claim Non-Rating - 040SCNR
Supplemental Claim Rating - 040SCR

**Comment by leikkisa** [comment]
@Sjones352
The codes are implemented in models/request_issue.rb, in the END_PRODUCT_CODES, and logic for them starts with the end_product_code method.

The tests for this are in spec/models/request_issue.rb for #end_product_code

**Comment by leikkisa** [comment]
#### Validation instructions
- Create an appeal with both a rating and nonrating issue, benefit type "compensation"
- Give both issues a decision of remanded, see Anya's instructions here: https://github.com/department-of-veterans-affairs/caseflow/issues/9571#issuecomment-472115838
- Check that the for the Appeal, check the end product establishments on each of the remand supplemental claims, and ensure that they have the correct codes.

**Comment by leikkisa** [comment]
This is failing for rating issues (see Appeal 151 and 152). It seems like it's because the issues are not still categorized as rating on the remand supplemental claim.  I don't know if this is specific to the way I'm doing this in UAT, but the decision issue still has the correct designation for rating?, and it gets lost on creating the remand supplemental claim.

**Comment by leikkisa** [comment]
Phew, this is validated! See EPE 1061

Here's the script that was used for creating the decisions

```uuid = "451acd34-84f8-4919-a35d-90040a0135fc".upcase
a = Appeal.find_by(uuid: uuid)
a.tasks.where(type: "BvaDispatchTask").delete_all
RequestStore[:current_user] = User.last
a.request_issues.each do |r|
decision_issue = DecisionIssue.create!(disposition: "remanded", description: r.description, benefit_type: r.benefit_type, diagnostic_code: "5000", participant_id: a.veteran.participant_id, decision_review: a, rating_issue_reference_id: r.contested_rating_issue_reference_id)
RequestDecisionIssue.create!(decision_issue: decision_issue, request_issue: r)
end
root_task = a.tasks.find_by(type: "RootTask")
BvaDispatchTask.create_from_root_task(root_task)
u = a.reload.tasks.find_by(type: "BvaDispatchTask", assigned_to_type: "User").assigned_to
file = "1234"
citation_number = "A19000105" 
BvaDispatchTask.outcode(a.reload, { citation_number: citation_number, decision_date: Time.zone.now, redacted_document_location: "\\\\bvacofil1.dva.va.gov\\archdata$\\arch1901\\A19000105.txt", file: file }, u)
```
