### ISSUE TITLE
Intake Add/ Remove Issues Page | Decision dates in modal are one day ahead of decision dates on page

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#9650]
Observed in UAT on file `123458314 `: 
1. I intake a form and land on the Add/ Remove Issues page (https://appeals.cf.uat.ds.va.gov/intake/add_issues)
2. I select a rated issue "Service connection for ptsd is granted..." under the heading `Past decisions from 07/30/2018`
3. When I add the issue, I see the line `Decision date: 07/29/2018`

This is repeatable for other file numbers and issues.

![screencapture](https://user-images.githubusercontent.com/25468689/53438657-2f7b8a00-39b5-11e9-92ae-d6397bb5e8f6.gif)

**Comment by pkarman** [comment]
this is very likely a timezone bug.

**Comment by Sjones352** [comment]
### Validation
1. On the Add/ Remove Issues page.
2. Click a `Add issue`
3. Select a rating
4. Click Add
5. Check if the decision date on the rating is the same as the the past decision date you delected.

**Comment by pkarman** [comment]
Assigning to myself to validate.

**Comment by pkarman** [comment]
Validated. Date matches 10/03/2018 on both screens.

![Screen Shot 2019-03-20 at 10 55 46 AM](https://user-images.githubusercontent.com/1205061/54699338-d22fb000-4afe-11e9-8c5c-aea9ffeed494.png)

![Screen Shot 2019-03-20 at 10 56 00 AM](https://user-images.githubusercontent.com/1205061/54699354-d8be2780-4afe-11e9-8339-a9db3d5a1885.png)
