### ISSUE TITLE
Bug: Switching a case from CO to Video

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9654]
This veteran has a hearing scheduled through Caseflow but needs to be postponed. We need to: 1) Set the scheduled hearing's disposition to 'postponed', 2) Close any existing HoldHearingTasks and HearingTasks, and 3) Move the appeal to '57'. 

From there, the AHL job should pick up the appeal, create a HearingTask and a ScheduleHearingTask, and the hearings management branch can schedule a new hearing at the requested location.

https://appeals.cf.ds.va.gov/queue/appeals/3113097

**Comment by mdbenjam** [comment]
This is completed, if there's still a problem reopen this.
