### ISSUE TITLE
Bug: Verify address task duplicating

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9656]
Sal is attempting to close a verify address task and it is duplicating the task instead of closing it. 
https://appeals.cf.ds.va.gov/queue/appeals/2707721

**Comment by mdbenjam** [comment]
@lomaxap I wonder if things are messed up with the job. This appeals has like 20 `HearingAdminActionVerifyAddressTask` tasks. Some are completed but a lot are assigned. So I'm wondering if we aren't checking if there's a task before creating a new one.

**Comment by lomaxap** [comment]
that's possible, but it should only create another task if the status is cancelled or completed.

it would also duplicate the task if he attempts to close it but the address is still not valid in VBMS. Have you checked to see if this case does actually have a valid address or zip code? Seems unlikely that he would try 20 times, but maybe? it also seems unlikely that the job ran on this veteran 20 times already.

**Comment by ShellySmithDSVA** [comment]
Sal indicated he checked the address and it is correct. He attempted to close the task and that is when it duplicated out.

**Comment by lomaxap** [comment]
want to confirm that Sal saw no duplicates until he attempted to close the task?

**Comment by mdbenjam** [comment]
In the database there are already a lot of duplicates, many of which with status assigned and many with status completed. It's possible the frontend is only rendering one of these tasks, not all of the assigned tasks. Not sure. It could be a problem in the admin action code as well.

**Comment by lomaxap** [comment]
this particular appellant is missing a country code from BGS which would cause another admin action to be created (https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/va_dot_gov_address_validator.rb#L40). We could maybe add more helpful instructions to indicate which address fields should be validated. 

i checked the created/updated timestamps for these admin actions and it looks like for every action that was updated to "complete", there is a corresponding action that was created a couple of milleseconds later, all on the 26th. There is a single admin action (the original action) that was created on the 24th. So i don't think the job is creating duplicated, but i can do a little more testing to make sure the job is pulling unique appeals.

**Comment by ShellySmithDSVA** [comment]
I'm asking Sal to confirm the Country Code for this case and will follow up.

**Comment by ShellySmithDSVA** [comment]
Confirmed this is an error. Country code ok.

**Comment by lomaxap** [comment]
ok, fyi to whoever picks this up, it looks like
`LegacyAppeal.find_by(vacols_id: 2707721).appellant[:address][:country]` is returning `nil`, so the bug may have something to do with the [address mapper](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/mappers/address_mapper.rb#L29-L41)

**Comment by oscarAtNava** [comment]
470 duplicated tasks were created during the period of March 2nd at 7 pm to March 3rd at 6 am. These dates are Saturday and Sunday. 60 other dupe tasks were created on March 5th at 5 am. There were 13 dupe tasks created for one appeal on Feb 26th and this seems to be the only one created during business hours. Does this point to the batch job generating these items? 
See this file for the raw data. Times are in UTC.

[HearingAdminTasksByAppealIdAndCreationDateHour.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2932501/HearingAdminTasksByAppealIdAndCreationDateHour.xlsx)

**Comment by lomaxap** [comment]
Yes, that sounds right to me. It sounds like the job isn't properly excluding appeals with existing VerifyAddress admin actions. [This is the SQL](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/fetch_hearing_locations_for_veterans_job.rb#L11-L27) that determines which appeals to geomatch. It _should_ be excluding all appeals that have an active `HearingAdminActionVerifyAddressTask` or `HearingAdminActionForeignVeteranCaseTask`
