### ISSUE TITLE
Hearing prep - docket starting time appears to be off for West Coast ROs

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9670]
Reference: https://github.com/department-of-veterans-affairs/appeals-support/issues/3984#issuecomment-467567699

**Comment by aroltsch** [comment]
### Investigation results: 

One of the travel board hearings in Vacols:

```
hearing_date: "2019-01-28 21:30:00"
``` 

It matches with what we show in Caseflow: 12:30 am ET / 9:30 pm PT Portland

**Comment by aroltsch** [comment]
Talked to Sharon. We are going to table this for now. Confirmed that there is no bug on our side.

**Comment by sharonwarner** [comment]
Removing travel board from hearing prep.
