### ISSUE TITLE
UI Fix: Filtering for Suggested Locations

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9674]
Filtering for the Suggested Locations under the RO has a floating ghosted box and is off to the left of the column. This should be centered under the column so that visually the functions are connected. See screenshot below. 

![screen shot 2019-02-27 at 12 07 07 pm](https://user-images.githubusercontent.com/45463980/53509827-a33b9680-3a8a-11e9-95d8-5b8cc4cf84ae.png)

**Comment by lomaxap** [comment]
will be resolved with #11285
