### ISSUE TITLE
[Sentry] Cannot read property 'taskId' of undefined

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9676]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2851/events/oldest/

**Comment by aroltsch** [comment]
This has not happened since Mar 1, 2019. Closing.

**Comment by jcq** [comment]
Reopening due to seeing it again in a Sentry alert:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7533/

**Comment by leikkisa** [comment]
These are both queue errors, so it might be easier for the Echo team, I'll tag them too.

**Comment by yoomlam** [comment]
Another one: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7850
`./app/queue/SubmitDecisionView.jsx in nextStepHook at line 114:15`

`task` is undefined:
```jsx
    const {
      task: { taskId },
      appeal: {
        issues,
        decisionIssues,
        veteranFullName,
        externalId: appealId,
        isLegacyAppeal
      },
      checkoutFlow,
      decision,
      judges
    } = this.props;
```

Either ensure `task` is defined or handle the case where `task` is not defined.

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7850

**Comment by lomky** [comment]
Estimating at a standard 3 for digging in and possibly fixing from a sentry issue.
