### ISSUE TITLE
Allow VLJ support staff admins to act on behalf of their team members (e.g. mark tasks complete)

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9677]
Currently VLJ Support staff [admins can reassign tasks](https://github.com/department-of-veterans-affairs/caseflow/blob/58e252a0409a3f7d3c9ee6af3742f773f25a2168/app/models/tasks/colocated_task.rb#L40) assigned to other members of the VLJ support staff. This ticket exists to also allow those admins to mark tasks complete.

## Acceptance criteria
* [ ] Allow VLJ support staff admins to act on behalf of their team members (e.g. mark tasks complete, cancel tasks)

**Comment by laurjpeterson** [comment]
Note: Team admins likely want the ability to do any of the same actions their team member could do - not just complete.
