### ISSUE TITLE
Intake | Improved error messaging

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9679]
When users report the "Something went wrong" error, they often take a screenshot to accompany it.

As a user, when I get the "Something went wrong" error, I would always find it helpful to know a little more detail, particularly if it is something that helps me know (a) it wasn't my fault and (b) what I might be able to do (e.g. retry in the case of a transient upstream error).

As an engineer, it would be helpful if the error message contained just enough information to help me more quickly narrow down the actual error. A unique ID (even if it was random) that was logged as well as displayed to the screen, might help me search Sentry and/or filter the AWS logs to the specific stacktrace or exception message.

## Acceptance criteria

* Every "Something went wrong" message should contain at least one more line of detail, even if it is a randomly generated UUID.

**Comment by Sjones352** [comment]
@leikkisa validated this Issue. Please refer to https://github.com/department-of-veterans-affairs/caseflow/pull/10132
<img width="744" alt="Screen Shot 2019-03-28 at 8 01 44 PM" src="https://user-images.githubusercontent.com/23080951/55200418-5e437680-5194-11e9-88f2-669fb70d9c9e.png">
