### ISSUE TITLE
Handle transaction cutoff more gracefully while deploying

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#968]
When we deploy, we're getting 5 to 6 500's due to transactions from the destroyed machine being cut off. This is throwing a PagerDuty error

<img width="731" alt="screen shot 2017-02-21 at 9 42 55 am" src="https://cloud.githubusercontent.com/assets/1596259/23169582/44c890e4-f81a-11e6-9ad1-a3cfe0cf7ecf.png">

See: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/96/

**Comment by shanear** [comment]
This might be caused by the database migration happening while the other instance is still live:
http://stackoverflow.com/questions/2783813/postgres-8-3-error-cached-plan-must-not-change-result-type

**Comment by orischwartz-gov** [comment]
Is there a reason this code needs to be in a transaction block? Couldn't we force ActiveRecord to fetch all the required fetching upfront outside the transaction block:

### Before
```ruby
 def update_from_appeal(appeal)
    update_attributes!(
      vacols_id: appeal.vacols_id,
      appellant_name: appeal.appellant_name,
...
# each invocation of `appeal.xxx` potentially lazy loads data and accesses a backend service.
   )
 end
```

### After
```ruby
 def update_from_appeal(appeal)
    assign_attributes(
      vacols_id: appeal.vacols_id,
      appellant_name: appeal.appellant_name,
... 
   )
# propagate any errors from above to address #610
  save!
 end
```

**Comment by kierachell** [comment]
**PASSED**
Ran a stress test during a deploy; did not see errors
