### ISSUE TITLE
EP Creation | Shouldn't be able to cancel during the creation of an EP

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#969]
**Description:**
Currently as a caseworker establishing an EP on the Create End Product page you can select the Establish Claim  button and while it is loading select the Cancel button and watch the Create End Product button process to the Success or Route page. 

**Environment found:** UAT
**Browser Found:**Chrome/Firefox

**Steps to Reproduce:**
1. Go to Dispatch in UAT as a caseworker
2. Establish a claim and fill out the Review Decision page (No SIC)
3. On the Establish an End Product page, select "establish claim" button 
4. While that button is loading, select cancel and watch the screen change behind the cancel modal.

**Expected Results:** I'm pretty sure, not that. 

**Screenshots:**
<img width="1286" alt="screen shot 2017-02-21 at 10 05 23 am" src="https://cloud.githubusercontent.com/assets/23038505/23170969/20f295ca-f81f-11e6-8acb-51a00aba2303.png">

**Related Issues/Stories:**
**Reported by:** Alexis Stewart

**Comment by MeredithStewart** [comment]
Closing since use of Caseflow Dispatch will be ended.
