### ISSUE TITLE
Allow VSO employees to navigate to organization queue

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9693]
Currently VSO employees are provided with the url of the organization page for the VSO they work for in order to reach the VSO's queue table view. However, when they take an action on a task or click the logo these employees are returned to their own personalized task queue with no way to navigate back to the VSO's queue table view (see [this related support ticket](https://github.com/department-of-veterans-affairs/appeals-support/issues/4228)).

This is happening because [we determine membership in VSO's](https://github.com/department-of-veterans-affairs/caseflow/blob/8d085bc17fa8bd732b1e84938b968e7e6545babd/app/models/organizations/vso.rb#L2) differently [than we do for other `Organization`s](https://github.com/department-of-veterans-affairs/caseflow/blob/8d085bc17fa8bd732b1e84938b968e7e6545babd/app/models/organization.rb#L38). Instead of using the `organizations_users` table to map users to organizations as we do for all non-VSO organizations, we make a request to BGS to confirm a user is a member of a VSO. The mapping of `organizations_users` is how we build the dropdown queue selector that appears for folks who are members of non-VSO teams, but because of how we determine VSO team membership, it does not work for VSOs.

## Acceptance criteria
* [ ] VSO employees can navigate from their personalized task queue table view to the VSO organization queue table view

**Comment by lowellrex** [comment]
In addition, the "Assign to person" action has no selectable options because we don't retain the list of members in VSOs in our database and therefore return an empty list [when we build the list of possible assignees](https://github.com/department-of-veterans-affairs/caseflow/blob/ef8465713ffe34056de42b278b6582b504fced02/app/models/task.rb#L283).

Related slack discussion: https://dsva.slack.com/archives/C6E41RE92/p1551730842083900

**Comment by laurjpeterson** [comment]
@lowellrex - should i create a separate ticket for VSOs to be able to assign tasks to individuals or is it captured here (double checking because of your above comment)?

**Comment by lowellrex** [comment]
I think it makes sense to create another ticket for that since the solution might be different. But we should link to this ticket from it in case the solution is the same.

**Comment by laurjpeterson** [comment]
Re-opened this old one: Allow VSO users to assign cases to VSO users - https://github.com/department-of-veterans-affairs/caseflow/issues/7480

**Comment by lowellrex** [comment]
One thought about how to do this is that we could cache the VSO staff-VSO organization relationship information through a (nightly?) job that adds (and deletes!) a record in the `organizations_users` table in order to but keeps all of the other checks around

**Comment by lowellrex** [comment]
Another approach we could take would be checking VSO membership on login (max once per day or something) and then running a job that clears VSO membership if somebody hasn't logged in for a month.

**Comment by lowellrex** [comment]
@laurjpeterson Could we give a member of a VSO admin privileges so that the admin can then add other members of the VSO similar to how all other organizations work? The only difference would be that we would need to manually identify that first VSO admin.

**Comment by laurjpeterson** [comment]
Yes, let’s do that. We did discuss that option a few weeks ago too. There is another gh issue to add VSO admin users, I’ve got a few ppl already listed out. I thought there were other things that needed to be done in addition to that, though, to allow assignment to individuals.

**Comment by lowellrex** [comment]
Closing this as the development work to enable the workaround mentioned above was implemented as part of #7974.
