### ISSUE TITLE
Identify Veterans who claim MST

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9696]
There is ongoing FOIA litigation concerning Veterans with claims of military sexual trauma (MST). The Board has apparently asked OIT about identifying these. 

From a conversation with OBPI, there is a data marker in VBMS that could identify these Veterans. I believe the Board asked about a checkbox, but was not involved in the conversation. If VBMS could provide a data point, Caseflow could pre-fill an identifier. 

It is unclear if the identifier for MST is specific to an issue or specific to a Veteran. 

@d-l-ware may have more information on this.

**Comment by araposo-tistatech** [comment]
Duplicate included in Epic #13423
