### ISSUE TITLE
Identify Veterans exposed to herbicides

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9697]
There is a stay concerning cases where Veterans allege herbicide exposure (the stay may be more specific than that; not certain). The Board has apparently asked OIT about identifying these. 

From a conversation with OBPI, there is a data marker in VBMS that could identify these Veterans. I believe the Board asked about a checkbox, but was not involved in the conversation. If VBMS could provide a data point, Caseflow could pre-fill an identifier. 

The herbicide identifier in VBMS is based on the assertion by the Veteran, not based on an actual finding of herbicide exposure. Also, it is unclear if that identifier is issue-based or Veteran-based.

@d-l-ware may have more information on this.

**Comment by araposo-tistatech** [comment]
@msj0nes do you think this identification should be occurring at Intake? If so, feel free to switch out the Echo label.
