### ISSUE TITLE
Identify Purple Heart recipients

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9698]
The Secretary publicly stated that VA would prioritize (AOD) cases for Veterans with Purple Hearts (https://www.usatoday.com/story/news/politics/2019/02/26/veterans-purple-heart-medals-receive-top-priority-va-claims-disability/2992536002/). The Board has apparently asked OIT about identifying these. 

From a conversation with OBPI, there is a data marker in VBMS that could identify these Veterans. I believe the Board asked about a checkbox, but was not involved in the conversation. If VBMS could provide a data point, Caseflow could pre-fill an identifier. 

@d-l-ware may have more information on this.

@cmgiven tagging because of potential for the large number of AODs to impact automatic distribution.

**Comment by geoffreystienblock** [comment]
It’s funny that you should send this. I brought up this very thing at our morning standup.


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by D-L-Ware** [comment]
Quick note.  OGC has indicated that the Chairman cannot AOD these cases sua sponte.  As such, we are waiting for a Secretary's memo indicating these need to be prioritized.  That being said, as it has been reported in the news media, I would expect the memo to be forthcoming.

**Comment by D-L-Ware** [comment]
Update: VBA is suggesting the SecVA directive applies only to initial claims.  As they are indicating they are not equipped or resourced to ID and prioritize purple heart veterans pursuing Supp Claims or HLR.  If it is only applicable to initial claims purple heart appeals would not have to be identified.  I will let you know when I know more.

**Comment by nicholasholtz** [comment]
Understood. Worth noting - there is a special issue and/or flash for these in VBMS. As such, if it were needed for SCs, HLRs, Appeals, it may be possible to pull the data in and include it in EP creation (SCs, HLRs) or Appeal creation (to make them AOD).
