### ISSUE TITLE
Caseworker | Mustard Gas SIC preselected on Review Decision page

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#970]
**Description:**

As a caseworker on Dispatch, when I access the Decision Review page, the Mustard Gas SIC is already preselected for the user. 

**Environment Found:** UAT
**Browser Found:**Chrome and FF

**Steps to Recreate:**
1. As a caseworker go to the Review Decision page on Dispatch
2. Scroll down to the SIC's to see "Mustard Gas" pre-selected. 

**Expectations:** None of the SIC should preselected (?)

**Screenshots:**
<img width="946" alt="screen shot 2017-02-21 at 9 57 14 am" src="https://cloud.githubusercontent.com/assets/23038505/23179183/0269b2f2-f83b-11e6-99d7-84f34fe12089.png">

**Associated Issues/Stories:**
**Reported by:** Alexis Stewart

**Comment by shanear** [comment]
@astewarttistatech can you verify that this isn't a test data problem? reproduce the issue with another case?

**Comment by kierachell** [comment]
It's not a test data problem.
This was fixed by a #958 
Except that PR/Issue never went through Validation (see label history and uchecked box); so it was  "implemented" but never used in code.
My fix for this is in #881 Which is being validated, waiting for deployment update.

**Comment by kierachell** [comment]
**PASSED**
SIC are properly cleared now
