### ISSUE TITLE
Explore senior counsel, deputy vice chairman, and other nuanced role scenarios

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9704]
There are a few types of positions at the Board that end up having other users do their tasks. How do we want to solve for this in Caseflow?

### Scenario 1: Deputy Vice Chairman (DVC)

*Background:*
- Deputy Vice Chairman (DVCs) have administrative assistants.
- DVCs are judges, in that they will sign cases. They have also held hearings in the past, so they specifically need to sign their hearing cases.
- DVCs do not have attorney teams like judges do. 
- Their admin assistants request cases for them and assign those cases to judges, who then assign them to their attorneys for drafting. Those attorneys then check the case back to the DVC for signing. 

*Caseflow current state:*
- In Caseflow, DVCs currently have the judge view. They don't have any attorneys on their team.
- They currently can request cases because of automatic case distribution (both legacy and AMA cases). Since they don't have judge teams, they will receive 15 cases every time they click request. 
- DVCs also might do "case management" and assign cases from judge to judge. 
   - Example: A judge goes out on leave and DVCs want to move their cases to another judge.

 ### Scenario 2: Supervisory Senior Counsel (SSC)

*Background:*
- Supervisory Senior Counsel (SSC) are paired with judges. They help manage the team of attorneys alongside judges.
- Often, judges ask SSCs to assign "genpop" cases (general population cases - basically, non-hearing request cases) to attorneys as overtime. 
   - Note: judges will also need the ability to assign cases to attorneys as overtime.

*Caseflow current state:*
- SSCs have the judge view in Caseflow. They don't have any attorneys on their team.
- SSCs are able to request cases because of automatic case distribution (both legacy and AMA cases). Since they don't have judge teams, they will receive 15 cases every time they click request. 
- DVCs also might do "case management" and assign cases from judge to judge. 

### Problem to solve
*Questions:*
- How might we enable admin assistants to request cases and assign them to judges in place of the DVCs?
- How might we enable SSCs to request cases and assign them to attorneys on their judge teams?

*Idea:*
- What if admin assistants were "team admins" for the DVC judge team queue and they could then assign cases out from that queue
- What if SSCs were "team admins" for their judge team queues and they could assign cases out from that queue
- What if admin assistants or SSCs could "impersonate" DVCs or judges?

---
### Scenario 3: Chairman, Vice Chairman
*Background:*
- The Chairman and Vice Chairman do not request cases.
- They still have to sign decisions because they have held hearings in the past. 
- Admin assistants request cases for the Chairman, have other judges/attorneys write and sign them, and prepares an Arneson letter (indicating a panel decision of 3 judges?) for the Chairman to sign. 
  - An SSC helps with the Arneson letter preparation. More research is needed.

*Current state in Caseflow:*
- Chairman and Vice Chairman - assumption that they have the judge view and can request cases
- Admin assistants - have a normal individual queue view, can't assign cases to judges/attorneys

### Problem to solve
- How might we enable admin assistants to request the Chairman and Vice Chairman's cases so they can create that Arneson letter and get their signatures (assuming outside of the IDT and Caseflow)?

*Ideas:*
- Allow admin assistants to request cases for the Chairman and Vice Chairman, so cases are not assigned to them
- Ask the Chairman and Vice Chairman to use Caseflow for their hearing cases
- Add admin assistants to Chairman and Vice Chairman "team queues" and allow them to assign cases to judges/attorneys
- Allow admin assistants to impersonate Chairman or Vice Chairman

**Comment by lowellrex** [comment]
> * What if admin assistants were "team admins" for the DVC judge team queue and they could then assign cases out from that queue
> * What if SSCs were "team admins" for their judge team queues and they could assign cases out from that queue

Strong yes to bullets 1 and 2! We already have a mechanism (`admin` column of `organizations_users` table) to implement this so it shouldn't be too troublesome to adapt to this use case. The one immediate problem we face with this approach is that we currently [expect only one admin on a judge team](https://github.com/department-of-veterans-affairs/caseflow/blob/7c77fa26805e83cdacc581a291f723ba5f378d28/app/models/organizations/judge_team.rb#L12), and for that admin to be the judge of the judge team. @tomas-nava and I discussed making a discussed the idea of adding a new `owner` column to the `organizations_users` table to differentiate normal admins with judges.

**Comment by laurjpeterson** [comment]
@lowellrex @marvokdolor-gov - FYI, the ideas I laid out above don't seem to work as is...yet!

I was trying to see if an SCC could assign/reassign cases for her judge.

I impersonated a judge, added her senior counsel (SSC) to her team, and made that SSC a team admin. The SSC shared her screen with me, and she could not navigate to her judge's queue, so could not assign her judge's cases to anyone. 

This means the idea for DVC admins to be DVC team admins in Caseflow likely won't work just yet.

**Comment by lowellrex** [comment]
> I impersonated a judge, added her senior counsel (SSC) to her team, and made that SSC a team admin. The SSC shared her screen with me, and she could not navigate to her judge's queue, so could not assign her judge's cases to anyone.
> 
> This means the idea for DVC admins to be DVC team admins in Caseflow likely won't work just yet.

Correct. We will need to do some additional development work to make this work, but it shouldn't be all that intensive.

**Comment by laurjpeterson** [comment]
Got it. Here's what I think we need from the user's perspective:

As a team admin, I can navigate to my judge's `Assign Cases` view, so I can either (1) assign cases to attorneys on my judge's team (2) reassign cases from one attorney to another on my judges team and (3) request cases on behalf of my judge.

Shall I create another gh issue for this? Or, can you let me know if this should be multiple engineering tasks?

**Comment by lowellrex** [comment]
Another github issue would be perfect! Thanks LP!

**Comment by laurjpeterson** [comment]
Closing this issue because the discussion/exploration is done. Dev work will happen here: https://github.com/department-of-veterans-affairs/caseflow/issues/10551
