### ISSUE TITLE
Telehealth investigation

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9707]
The Board has expressed interest in integrating Caseflow with the new telehealth tool that VA is developing. 

We have asked for API documentation, but I don't think it has come in yet. There are a lot of questions that should probably be asked about any effort in this regard, some tech, some policy, some process. This document has a good starting point for questions:

[20181220 - Memo - Outstanding issues concerning virtual hearing functionality.docx](https://github.com/department-of-veterans-affairs/caseflow/files/2917003/20181220.-.Memo.-.Outstanding.issues.concerning.virtual.hearing.functionality.docx)

There should also be an effort to clearly understand what the Board's ultimate vision for holding hearings is, so this tool, and any possible integration, can be evaluated alongside other possible videoconference options (including off-the-shelf tools) as to whether it satisfies that ultimate vision.

**Comment by laurjpeterson** [comment]
Closing because of our work on #11132
