### ISSUE TITLE
Contested Claimants - Intake UI Modifications

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#9711]
Contested Claimants - Intake UI Modifications.
Creating this issue to document design explorations for this feature.

**Comment by carolaponce** [comment]
https://app.mural.co/t/workqueue2001/m/workqueue2001/1542655242638/5629820b4b2c34a158c9dd7abb78137d0f9b8b74

https://github.com/department-of-veterans-affairs/caseflow/issues/9409

**Comment by leikkisa** [comment]
@jimruggiero How would you feel about closing this ticket since other follow up issues have been created? We could move the mural link.  Alternatively we could make this an epic with the related issues attached.

**Comment by msj0nes** [comment]
# Update
Closing ticket. Design MURAL added to Epic #8451
