### ISSUE TITLE
Ensure demo seed data is unique and realistic

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9719]
All Veteran file numbers should be unique to a single Veteran.
All Veteran file numbers should be searchable.

See details below.

**Comment by pkarman** [comment]
@wturne I tagged you on this ticket because it has zero requirements. If you can even remember what "realistic demo data" means, we'd be happy to add some as part of our db seeds.

**Comment by wturne** [comment]
@pkarman "Realistic Demo Data" (to me) would means data, such as the Veteran ID, associated to one Veteran.  For example, Veteran ID 963360019 is associated to Veteran Bob Smith and Veteran Jacinto A Erdman, depending on whether you click on the Legacy case or the AMA case.  
Another example would be having a Veteran listed on the Review Cases (VLJ Role) page in Queue and clicking on the Veteran's name (Everette Lowe), but not being able to search for the Veteran using the Veteran ID 473218778.  When you do a search using the Veteran ID (473218778), you get an error, *No case found for "473218778".*  I'm sure there are other examples but this is one of the big pieces.  Please let me know if you have any questions.
