### ISSUE TITLE
AMA decision issues not displaying

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9723]
A BVA Dispatcher reached out to me and said that they can't see decision issues on the RAMP case they're working. Additionally, @tomas-nava  and I saw this happen when we were speaking with an attorney who had sent the case to their judge for review. We opened the case via Case Search, and the decision issues weren't displayed on the Case Details page. This was also a RAMP case. 

We know that attorneys/judges can see request issues, but when attorneys check the case out to their judge, and judges check the case out to BVA Dispatch, the dispositions and decision text disappears. 

Here is the link to the case the BVA Dispatcher sent to me: 
https://appeals.cf.ds.va.gov/queue/appeals/ae79b19f-44e4-4b9a-8308-b7db8b5acbd6

**Comment by aroltsch** [comment]
Checked the request for both the attorney and judge and noticed no decision issues were posted

`Parameters: {"tasks"=>{"type"=>"JudgeCaseReview", "location"=>"bva_dispatch", "attorney_id"=>1520, "one_touch_initiative"=>false, "complexity"=>"medium", "quality"=>"outstanding", "factors_not_considered"=>[], "areas_for_improvement"=>[], "comment"=>"first AMA-RAMP case by associate counsel-well-analyzed, well-written", "issues"=>[]}, "task_id"=>"25024", "case_review"=>{"tasks"=>{"type"=>"JudgeCaseReview", "location"=>"bva_dispatch", "attorney_id"=>1520, "one_touch_initiative"=>false, "complexity"=>"medium", "quality"=>"outstanding", "factors_not_considered"=>[], "areas_for_improvement"=>[], "comment"=>"first AMA-RAMP case by associate counsel-well-analyzed, well-written", "issues"=>[]}}}`

and

`[appeals.cf.ds.va.gov] [0b4031d9-4d7e-42e2-8f71-6dae3589db03] [172.30.87.151] [VACOBAYLESJJ jason.bayles@va.gov] [2019-02-26 11:53:39 -0500]   Parameters: {"tasks"=>{"type"=>"AttorneyCaseReview", "work_product"=>"Decision", "document_id"=>"01668-00000117", "note"=>"This is a one issue (IR Anxiety) RAMP appeal. ", "overtime"=>false, "untimely_evidence"=>false, "reviewing_judge_id"=>878, "document_type"=>"draft_decision", "issues"=>[]}, "task_id"=>"28997", "case_review"=>{"tasks"=>{"type"=>"AttorneyCaseReview", "work_product"=>"Decision", "document_id"=>"01668-00000117", "note"=>"This is a one issue (IR Anxiety) RAMP appeal. ", "overtime"=>false, "untimely_evidence"=>false, "reviewing_judge_id"=>878, "document_type"=>"draft_decision", "issues"=>[]}}}`


Then checked request issues for this appeal. This appeal has only one request issue and it is marked as ineligible. So when attorneys and judges were going though the checkout, no request issues were returned so they could not add decision issues to these and we still let them checkout the case

**Comment by allyceh** [comment]
@aroltsch @laurjpeterson @sneha-pai : I will follow up with Libby tomorrow (since William is out of the office until the 17th) to troubleshoot at her desk. 
Things to verify with her: 
- Is there a decision letter associated with this appeal? 
- If so, what are the issues?
