### ISSUE TITLE
Tell users that document count on the queue table is approximate

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9724]
Original support ticket: 
https://github.com/department-of-veterans-affairs/appeals-support/issues/4361#issuecomment-468696492

The document count listed on the queue table is an estimate and is approximate. Document counts in Reader and in Case Details are precise. Per @lowellrex , the reason is: "We use the estimate on the queue table view  because we have to hit some dependency (VVA or VBMS by way of efolder, I think) to get the precise number. We expect those requests to take on the order of 1-2 seconds each, so we simply wouldn't load document counts for a lot of appeals if there were more than a half dozen or so appeals in a queue table, so we fall back to the estimate. And the estimate will be correct unless changes to the document counts have been made within the last day."

Proposed solution: Create some kind of messaging or tooltip to tell users that the document count on queue table is approximate.

**Comment by sneha-pai** [comment]
early riff: 
The number of documents count seen here was last retrieved from VBMS on _______ at ________ pm. To view the most up-to-date numbers, please click on an individual case.
