### ISSUE TITLE
Assign task in VSO Queue Not Working

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9725]
A DAV user cannot assign tasks to different team members via the assign task to dropdown in their Queue. 

User: Thomas Wendel (DAV) - thomas.wendel@va.gov

### Steps of reproduction
- [ ] User clicked on an appeal in queue
- [ ] Went to actions and the assign task to
- [ ] The default state of the modal was the error state (with red lines next to boxes)
- [ ] User clicked the drop down and was disabled and typing a name did not work either

**Comment by lowellrex** [comment]
Duplicated existing ticket #9693. Closing this one in favor of that ticket.
