### ISSUE TITLE
Appeals with hearings being assigned an IHP Task

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9726]
### Context

In the DAV queue, most of the cases being assigned an IHP task having a hearing. They should only be assigned when there is no hearing according to Thomas Wendel and Roy Spice at DAV. The concern is that these hearings should be sent to location 57 to to be scheduled, including AOD's that have been sitting. 

### Steps of Reproduction
- [ ] User reviews cases in the the Assigned tab on Queue
- [ ] Has an IHP despite the appeal having a hearing

### Users
Thomas Wendel (DAV) - Thomas.wendel@va.gov

### Questions
- [ ] Should I mark these IHP tasks that don't need one as complete and move them along. Will it get sent to the hearings team?
- [ ] Do these exist in the hearings locations already and the user does not have to do anything?

**Comment by lowellrex** [comment]
Closing this in favor of the existing ticket that will be completed by the end of next week. https://github.com/department-of-veterans-affairs/caseflow/issues/9512
