### ISSUE TITLE
Intake Edit | If all issues are removed on a Caseflow decision review, close associated tasks

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9730]
We need to allow users to remove entire appeals (and non-comp decision reviews), not just individual issues. To start, we will allow appeals to be removed by removing all the issues and clicking save.

## Acceptance Criteria
- On the intake edit page for an appeal or non-comp decision review, do not disable the save button when all issues are removed.
- When the save button is pressed, in addition to removing all the issues on the decision review, all open tasks on that appeal should be closed, and the appeal should be considered closed and removed.

## Notes
- We will be working on a short hand way to close the entire appeal later, instead of having to remove each individual issue
- The parallel issue for VBMS reviews is #9731

## Technical Notes
- This functionality should be enabled and disabled using a feature flag named `:remove_decision_reviews`
- Ask @lowellrex how tasks should be closed on the appeal

**Comment by jiahuang** [comment]
Talked to Lowell, open tasks should be cancelled by something like `appeal.tasks.active.update_all!(status: Constants.TASK_STATUSES.cancelled)`

Additionally, we may want to differentiate a manually closed appeal from other appeals by either:
1. add a status column in appeal that gets set to "manually removed"
2. setting the existing `establishment_error` field to be "manually removed". We could also expose this field to the UI so that the worker can put in a more detailed message.

**Comment by jiahuang** [comment]
@Sjones352 A general approach for the backend portion of this ticket would be to first write failing specs that test the following scenarios when the remove_decision_reviews flag is turned on:
* when there is an appeal intake with multiple active tasks and all request issues are removed, ensure that all active tasks are set to a canceled state
* when there is an appeal intake with multiple active tasks and not all request issues are removed, ensure that no active tasks are set to a canceled state
* when there is an appeal intake with completed tasks and all request issues are removed, ensure that completed tasks do not get set to a canceled state
* the 3 above scenarios should be tested for higher level reviews & supplemental claims

The backend portion can be implemented by:
1. Adding a `cancel_active_tasks!` method to the decision_review model. This will cancel all active tasks with the code in the prior comment.
2. Modify the `perform!` method in `RequestIssueUpdate` to run `cancel_active_tasks!` when `after_issues` is empty (which will mean that all issues will be deleted). This should run inside the transaction.

**Comment by pkarman** [comment]
Validated as part of #9733 -- the task created was closed. https://appeals.cf.uat.ds.va.gov/decision_reviews/fiduciary/tasks/1342
