### ISSUE TITLE
Intake Edit | When all issues are removed from a VBMS based decision review, close all associated EPs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9731]
We need to allow users to remove entire decision reviews, not just individual issues. To start, we will allow decision reviews to be removed by removing all the issues and clicking save.

## Acceptance Criteria
- On the intake edit page for a VBMS based decision review, do not disable the save button when all issues are removed.
- When the save button is pressed, in addition to removing all the issues on the decision review, all open EPs on that appeal should be canceled, and the appeal should be considered closed and removed.

## Notes
- We will be working on a short hand way to close the entire appeal later, instead of having to remove each individual issue
- The parallel issue for non-VBMS reviews is https://github.com/department-of-veterans-affairs/caseflow/issues/9730

## Technical Notes
- This may already work with how the code works, this may just entail enabling the feature flag.
- This functionality should be enabled and disabled using a feature flag named `:remove_decision_reviews`

**Comment by leikkisa** [comment]
This is handled here:
https://github.com/department-of-veterans-affairs/caseflow/pull/7477

It was added because when we had multiple end products on a Decision Review, even if there was a request issue still on it, all of the request issues on the other EP could be removed so it would need to get canceled.
