### ISSUE TITLE
Intake Edit | Update save warning when removing entire decision review

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9733]
Users need to be warned when they are removing an entire decision review.

## Acceptance Criteria
- On the intake edit page, when a user clicking save would remove the entire review (according to #9730 and #9731) instead of the Number of Issues Changed warning, show the appropriate warning from the mocks below based on whether the decision review is processed in Caseflow or VBMS.

## Mocks
Processed in Caseflow:
![remove_review_appeal](https://user-images.githubusercontent.com/1596259/53656296-be7fe080-3c07-11e9-8b89-df32e157cbee.png)

Processed in VBMS:
![remove_review_hlr-sc](https://user-images.githubusercontent.com/1596259/53656302-c3449480-3c07-11e9-815c-d4bf04b68156.png)

## Notes
- The copy is subject to change per @carolaponce
- This functionality should be enabled and disabled using a feature flag named `:remove_decision_reviews`

**Comment by Sjones352** [comment]
**Validations Vbms**
- Create a higher level review or supplemental claim with a benefit type of compensation/pension
- Go to the Edit page
- Remove all decision reviews
- click on save
- Modal shows message `This will remove the review and cancel all the End Products associated with it.` 

**Validations Caseflow**
- Create a higher level review or supplemental claim with a benefit type of non-comp
- Go to the Edit page
- Remove all decision reviews
- click on save
- Modal shows message `This review and all tasks associated with it will be removed.`

**Comment by pkarman** [comment]
Validated for compensation HLR:

![Screen Shot 2019-03-26 at 3 33 33 PM](https://user-images.githubusercontent.com/1205061/55031421-986a1800-4fdc-11e9-8697-f51cb764b246.png)

**Comment by pkarman** [comment]
Validated for non-comp in Caseflow:

![Screen Shot 2019-03-26 at 3 35 44 PM](https://user-images.githubusercontent.com/1205061/55031572-df580d80-4fdc-11e9-90a7-d6a50edf7e18.png)
