### ISSUE TITLE
Intake Edit | Decision review removal confirmation alert

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9734]
We need to provide confirmation when users remove decision reviews.

## Acceptance Criteria
- When an appeal removal is saved, the user should be redirect back to the case details page with an alert based on the mock below. 
- When the removal of a non-comp decision review is saved, the user should be redirected back to the appropriate business line landing page with the alert from the mock below.
- When the removal of a VBMS based decision review is saved, a confirmation page should be shown based on the mocks below.

## Mocks
Caseflow based:
![confirmation_for_queue](https://user-images.githubusercontent.com/1596259/53656533-685f6d00-3c08-11e9-9403-1e4061d2c94c.png)
Copy should be changed based on the type of decision review.

VBMS based:
![confirmaton_text02](https://user-images.githubusercontent.com/1596259/53657762-e7a27000-3c0b-11e9-81dc-1d6742231ec1.png)

## Notes
- Copy subject to change per @carolaponce 

## Technical Notes
- Ask @lowellrex and/or @laurjpeterson what the case details page for a removed appeal should look like. Will it load?
- There will likely be more variations on copy for withdraws and "stayed" reviews. Keep that in mind in the technical design

**Comment by pkarman** [comment]
See also #9888

**Comment by pkarman** [comment]
Validation requires manually toggling feature flag in UAT: `FeatureToggle.enable!(:remove_decision_reviews)`

**Comment by pkarman** [comment]
Validated non-comp:

<img width="767" alt="Screen Shot 2019-04-09 at 3 01 32 PM" src="https://user-images.githubusercontent.com/1205061/55831565-03d1e080-5ad9-11e9-8a55-57c1d2dcc7c1.png">
<img width="1085" alt="Screen Shot 2019-04-09 at 3 01 50 PM" src="https://user-images.githubusercontent.com/1205061/55831577-0df3df00-5ad9-11e9-8f3b-a78e40e82ba0.png">

Validated VBMS:

<img width="802" alt="Screen Shot 2019-04-09 at 3 05 30 PM" src="https://user-images.githubusercontent.com/1205061/55831602-1cda9180-5ad9-11e9-8ceb-3514d760ca53.png">
<img width="857" alt="Screen Shot 2019-04-09 at 3 05 42 PM" src="https://user-images.githubusercontent.com/1205061/55831613-22d07280-5ad9-11e9-9caf-48211746ba76.png">
