### ISSUE TITLE
Resolve Caseflow::Error::ClientRequestErrors from efolder

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9741]
Connects #9740.

The `new_documents` endpoint occasionally raises [`Caseflow::Error::ClientRequestError`](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3905/)s because Efolder does not have any record of a Veteran that Caseflow expects to exist.

## Acceptance criteria
* [ ] `Caseflow::Error::ClientRequestError`s from the `new_documents` endpoint are handled properly

**Comment by lowellrex** [comment]
These appear to all be for the same Veteran ID. Figure out what is going on with this case. SMALL if that holds (if they all are the same Veteran). MEDIUM if there is a more systemic problem here.

**Comment by nemodjuric** [comment]
BGS has no record for this file number. It exists in VACOLS, and it has the same C and S file number, so  we should check with BGS while there is no record for this. @mc-usds

**Comment by nemodjuric** [comment]
@mc-usds https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3905/

**Comment by nemodjuric** [comment]
@mc-usds will contact BGS about this.

**Comment by aroltsch** [comment]
@lowellrex, does this happen for new_documents endpoint only? We don't have this endpoint anymore.

**Comment by lowellrex** [comment]
> @lowellrex, does this happen for new_documents endpoint only? We don't have this endpoint anymore.

Yup! It looks like [we haven't seen this error](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/?query=ClientRequestError&statsPeriod=14d) since we got rid of this endpoint so I'm going to go ahead and close out this ticket.

**Comment by leikkisa** [comment]
I see that this is closed - I just wanted to add that we provided the Vet's personal information from VACOLS to John Dell at BGS, and they still weren't able to find a record for this Veteran.
