### ISSUE TITLE
Hearing tasks | Add labels for Case Details page

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9750]
![timeline](https://user-images.githubusercontent.com/4306128/53745604-4fa3c100-3e6d-11e9-8f40-de1c1af90304.png)

The timeline on the case details page displays the name of the task unless a label is explicitly defined. We should define labels for the tasks we've created for hearings.

**Comment by oscarAtNava** [comment]
@MeredithStewart  For Hearing and Disposition tasks, we probably do not want to repeat the word Task in the label, but by themselves the words Hearing and Disposition do not mean much. Any idea on better worded labels?

**Comment by MeredithStewart** [comment]
Here's what I'm thinking: 

For hearing task: 
Label: All hearing-related tasks 
Instructions: This task will be completed when all hearing-related tasks have been completed. 

For disposition task: 
Label: Hearing disposition to be selected 
Instructions: This task will be completed when a disposition for the hearing (Held, Canceled, No Show, Postponed) is selected.

For schedule Hearing task
Label: Schedule hearing 
Instructions: Schedule Veteran and/or appellant for Board hearing. 

For change disposition task 
Label: Change hearing disposition
Instructions: Change hearing disposition (Held, Canceled, No Show, Postponed) if it was marked in error.

**Comment by laurjpeterson** [comment]
Related to Case Timeline recommendations and redesign, plus #7508 - cc: @sneha-pai

**Comment by ferristseng** [comment]
@lomaxap @pshahVA Is the language for this still accurate?

**Comment by lomaxap** [comment]
yes. it's still accurate. Although, i'd change "Hearing disposition to be selected" to "Select hearing disposition" to be grammatically consistent with the other labels. 

and then these instructions are more descriptive:  Postpone or cancel a hearing prior to the hearing date. This task will be auto-completed after the hearing's scheduled date.

**Comment by ferristseng** [comment]
@lomax Do you think we should save those instruction values to the database, or should they act as defaults where they display if no other instructions are specified?

**Comment by lomaxap** [comment]
@ferristseng I think they should just be defaults on the front end.
