### ISSUE TITLE
Display hearing docket date in Legacy tab of Schedule Veterans

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9752]
As a hearing coordinator, I need to be able to see when I am scheduling within the docket hearing date to ensure that I maintain the integrity of docket order and ranges. 

### Acceptance Criteria 
- [ ] Verify that we are reading the hearing docket date from Appeal Status
- [ ] Verify that there is a link with the hearing docket date that updates via changes detected in appeals status 
- [ ] Verify that the line and date is displayed as in the mocks
- [ ] Verify that the line and date is displayed even when the table is filtered by suggested hearing location
- [ ] Verify that when there are no Veterans to schedule, there is the following copy and shows as in the mock: 
  - All veterans have been scheduled for this hearing month. Please check back agian tomomorrow

### Mocks  

![hearing docket date v1](https://user-images.githubusercontent.com/23316107/53748800-0f940c80-3e74-11e9-9fe8-09c24efee302.png)

_What happens when there are no more to schedule_
![Hearing docket date legacy](https://user-images.githubusercontent.com/23316107/55497005-5198a580-560e-11e9-9fe0-fa08588fad39.png)

### Related Tickets 
* #9753 - AMA Hearing schedule date 
* #9754 - Warning message

**Comment by MeredithStewart** [comment]
@cmgiven -- We need to know how to pull the Hearing Docket date as it is calculated by Appeals Status. Can you share?

**Comment by cmgiven** [comment]
```ruby
DocketSnapshot.latest.latest_docket_month
```

That'll give you a date corresponding to the first day of the month.

Note that although a new DocketSnapshot is taken every day, the `latest_docket_month` only updates once a week, corresponding to how the Board calculates it.

**Comment by cmgiven** [comment]
Also note that this is the Board's docket date. If there are adjustments, I think at one point the hearing docket date was one year after the Board's, those adjustments would still need to be made.

**Comment by MeredithStewart** [comment]
@cmgiven -- So, there isn't a separate one just for hearings?

**Comment by cmgiven** [comment]
There is not. To date, we’ve only ever described the decision docket to Veterans.

**Comment by Chingujo** [comment]
@sharonwarner @lomaxap 

Updated this to show what happens when there is no more vetreans to schedule. I put a time frame in the copy to correlate with when our job runs. Let me know if you have any copy feedback @MeredithStewart .

Also, pending any design changed per the comment in #9753 Heraring Schedule AMA Date

**Comment by MeredithStewart** [comment]
@Chingujo -- Let's change the copy to, "All Veterans have been scheduled."

**Comment by laurjpeterson** [comment]
There is no place to get the "hearing docket date", we only have the BVA docket date. Since we don't have this field, we can't display it. If hearing docket date is still being used, we suggest hearing coordinators reference that hearing docket date outside of Caseflow.
