### ISSUE TITLE
Daily Docket Range Line AMA

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#9753]
As a hearing coordinator, I need to know what dates to schedule for in the AMA Veterans tab based on the Caseflow Algorithm.

### Acceptance Criteria 
- [ ] Verify that we are dispalying the current schedule date based on the Case Distribution algorithm. 
- [ ] Verify that we show a gray HZ line with the following copy: 
 - Schedule for [date] [year]
- [ ] Verify that line updates as needed to reflect the new cases that should be scheduled by month.
- [ ] Verify that when there are no more veterans to schedule there is copy in the table with the following: 
 - All veterans have been scheduled for this hearing month. Please check back agian tomomorrow
 

### Mocks 
![hearing docket date ama](https://user-images.githubusercontent.com/23316107/53749031-83361980-3e74-11e9-8c09-7839f1c3a501.png)

_If all are scheduled_
![Hearing docket date no hearings](https://user-images.githubusercontent.com/23316107/55496795-d636f400-560d-11e9-85ea-2ca17298f310.png)

### Related Tickets 
* #9753 - Hearing schedule date 
* #9752  - Legacy hearing docket date 
* #9754 - Warning message

**Comment by cmgiven** [comment]
Priority (AOD) cases should always be ready to schedule.

For nonpriority cases, per #9453, we need to run a monthly (or weekly, or biweekly) job that calls the following:

```ruby
days_in_month = Time.days_in_month(month, year)
dc = DocketCoordinator.new
target = dc.target_number_of_ama_hearings(days_in_month)
appeals = dc.dockets[:hearing].appeals(priority: false).limit(target)
```

And then record that each appeal in `appeals` is now ready to be scheduled for a hearing. Note that `month` is the month for which we are scheduling, not the current month.

**Comment by cmgiven** [comment]
Actually, I just realized there's an issue here, which is that this will include appeals that have already been marked as ready to be scheduled, but have not yet been decided. So the same appeals will get hit multiple times. We need an offset argument.

```ruby
appeals = dc.dockets[:hearing].appeals(priority: false).limit(target).offset(offset)
```

Where offset is the index on the docket of the oldest pending appeal that has already been marked as ready.

Sorry for the additional wrinkle. Always a bit more complicated.

**Comment by Chingujo** [comment]
@lomaxap @sharonwarner 

cc: @MeredithStewart 

I updated the above mock to include what happens when there are no veterans to schedule. I know both of you are discussing an approach, however,  understand that this can be quite complex for AMA since it would require varying hearing dates across different AMA schedules. 

If after your conversation this is too dificult too implement, please comment here =D. We can do something easier and then retroactivley apply a lower effort version to the legacy so users don't have to interpert two design patterns for the same information. Thanks

**Comment by MeredithStewart** [comment]
@Chingujo -- Let's change the copy to, "All Veterans have been scheduled."
