### ISSUE TITLE
Remove Wilmington DE from Schedule Veteran Views

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9756]
Wilmington, DE Veterans are now mapped to the Philadelphia RO for hearings.  

We need to remove Wilmington, DE from the drop down of ROs in the Schedule Veterans View. 

### Related tickets
* #9755 - No Veterans to schedule error
* https://github.com/department-of-veterans-affairs/caseflow/issues/11091

**Comment by tomas-nava** [comment]
take #11421 into account
