### ISSUE TITLE
Decision Review | Decision Document | Show large Caseflow Loading indicator

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#976]
As a Product Owner, I would like to have a spinning large Caseflow loading indicator displayed while the system is loading the Decision Document(s) on the `Decision Review` page so that there is an indication that something is happening. 

# Acceptance Criteria
1. Verify that during the loading of the Decision Document on the `Decision Review` page, a spinning large Caseflow loading indicator is displayed when it is taking longer than 2 seconds.

# Mockup

<img width="664" alt="screen shot 2017-02-26 at 5 36 33 pm" src="https://cloud.githubusercontent.com/assets/4975959/23344424/25ea2d48-fc4a-11e6-80c0-48045cdd0c94.png">

# Related Stories
n/a

**Comment by nikitarockz** [comment]
@lakohl please add loading favicon.

**Comment by astewarttistatech** [comment]
wrong color @mdbenjam 

Validated in: UAT

Steps to Validate: 
1. As a caseworker, go to dispatch and start the process to establish a claim
2. As the Review Decision page loads, where the decision document is loading, the large favicon appears. 
3. Verify the favicon matches what is intended in the mocks. 

Screenshots: 
<img width="785" alt="screen shot 2017-03-09 at 9 32 38 am" src="https://cloud.githubusercontent.com/assets/23038505/23754617/9e8d28ae-04ab-11e7-82f3-79dddd49b970.png">

**Comment by mdbenjam** [comment]
@nikitarockz What color is this indicator supposed to be? If it's purple I'll need color values. I also think we should keep this consistent. The button loading symbol is always blue, and I just used the same one here.

**Comment by lakohl** [comment]
@mmlumba @Chingujo this is in the flat style guide guide, can you guys provide a color and guidance for @mdbenjam

**Comment by Chingujo** [comment]
@mdbenjam 

The loading indicator should be purple to match the color of the app. The hex value is #844E9F

**Comment by mdbenjam** [comment]
Thanks @Chingujo. Two more questions on this ticket.
1) Is the six pointed caseflow logo cool for the loading indicator. The original mock had the four pointed symbol. But we don't have a spinning version of that.
2) Should the loading indicator on buttons also be purple for dispatch pages?

**Comment by Chingujo** [comment]
Just adding what we talked about earlier on the issue @mdbenjam and @lakohl  =D

1.) Large spinner:
- [ ] 4 point logo with Purple (#844E9F) for the large indicator
- [ ] Spin opp directions as in eFolder Express 

2.) Button spinners:
- [ ] 4 point logo
- [ ] Replace the dark gray of the spinner with the dispatch color (#844E9F)

**Comment by slj** [comment]
@lakohl I'd like to revisit the loading pill specs.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: UAT

Steps to Validate:
1.As a caseworker, go to dispatch and start the process to establish a claim
2.As the Review Decision page loads, where the decision document is loading, the large favicon appears.
3.Verify the favicon matches what is intended in the mocks.

Screenshots:
<img width="541" alt="screen shot 2017-03-16 at 12 58 46 pm" src="https://cloud.githubusercontent.com/assets/23038505/24008617/7cfae206-0a48-11e7-9fa1-544f88ee4621.png">
