### ISSUE TITLE
VSO concern with Caseflow

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#9761]
### Concerns from American Legion user:

1. They cannot assign cases to users (users list is blank)  (_from Marvo: not sure they have that functionality yet_)
2. They do not have the 'Switch Views' option on the main page. (_again, I think this is simply functionality they don't have just yet_)

**Sample cases:**
- https://appeals.cf.ds.va.gov/queue/appeals/1e3a26ad-659c-4384-9a72-62ba6863f979
- https://appeals.cf.ds.va.gov/queue/appeals/242f8342-cdd0-44f3-b727-f7627d45b96a

**Comment by lowellrex** [comment]
Closing in favor of #9693.
