### ISSUE TITLE
Withdrawing issues/Removing reviews copy

### ISSUE THREAD

**Issue by carolaponce** [department-of-veterans-affairs/caseflow#9769]
Removing reviews  | Withdrawing reviews | Withdrawing issues alert messages copy.  Using this issue to collect feedback on messaging copy.
Goals:
- User understand alerts and can make a decision what they need to do next.
- Messages are consistent throughout Caseflow (voice, language, brand...etc).

**Comment by carolaponce** [comment]
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by carolaponce** [comment]
![remove_review_appeal](https://user-images.githubusercontent.com/11700545/53769295-5263dd80-3e90-11e9-8e46-ffe5cdab8799.png)

**Comment by carolaponce** [comment]
![remove_review_hlr-sc](https://user-images.githubusercontent.com/11700545/53769308-5e4f9f80-3e90-11e9-88ec-7e859b523131.png)

**Comment by carolaponce** [comment]
|Option:1          | Remove Review/appeal/intake          | 
| :------------- |:--------------------------| 
| Use-case | User removes all issues from a review or appeal (NOD) and the review/appeal gets removed from system. Information about removed issues will still be available in database, but user could not see them all based on intake data. | 
| Copy for  NOD     | Title: Remove review?  </br> Copy: This review originally had 4 issues but now it has 0. This review and all tasks associated with it will be removed.  | 
|   | ![remove_review_appeal](https://user-images.githubusercontent.com/11700545/53769295-5263dd80-3e90-11e9-8e46-ffe5cdab8799.png)  |  
|  Copy for  HLR & SC | Title: Remove review?  </br> Copy:  This review originally had 4 issues but now it has 0. This will remove the review and cancel all End Products associated with it.  |  
|    | ![remove_review_hlr-sc](https://user-images.githubusercontent.com/11700545/53769308-5e4f9f80-3e90-11e9-88ec-7e859b523131.png)   |

**Comment by carolaponce** [comment]
![edit issues withdrawn review copy 4](https://user-images.githubusercontent.com/11700545/53770598-9822a500-3e94-11e9-88ad-7f60dd28e318.png)

**Comment by carolaponce** [comment]
![withdraw option3 copy 31](https://user-images.githubusercontent.com/11700545/53770623-b12b5600-3e94-11e9-909c-e96487b81231.png)

**Comment by carolaponce** [comment]
|Option:2          |  Withdrawing issues         | 
| :------------- |:--------------------------| 
| Use-case | User receives request from veteran to withdraw issue(s) | 
| Copy     | Title: Withdraw issue?  </br> Copy: If a Veteran or Claimant has requested to withdraw this issue from their review, Caseflow will close all open task in this issue.  Please include the date the withdrawl was requested.  | 
 |    |  ![edit issues withdrawn review copy 4](https://user-images.githubusercontent.com/11700545/53770598-9822a500-3e94-11e9-88ad-7f60dd28e318.png) |

**Comment by carolaponce** [comment]
|Option:3          | Remove Review/appeal/intake          | 
| :------------- |:--------------------------| 
| Use-case | User removes all issues from a review or appeal (NOD) and the review/appeal gets removed from system. Information about removed issues will still be available in database, but user could not see them all based on intake data. | 
| Copy for  NOD     | Title: Remove review?  </br> Copy: This review originally had 4 issues but now it has 0. This review and all tasks associated with it will be removed.  | 
|   | ![remove_review_appeal](https://user-images.githubusercontent.com/11700545/53769295-5263dd80-3e90-11e9-8e46-ffe5cdab8799.png)  |  
|  Copy for  HLR & SC | Title: Remove review?  </br> Copy:  This review originally had 4 issues but now it has 0. This will remove the review and cancel all End Products associated with it.  |  
|    | ![remove_review_hlr-sc](https://user-images.githubusercontent.com/11700545/53769308-5e4f9f80-3e90-11e9-88ec-7e859b523131.png)   |

**Comment by carolaponce** [comment]
Larger exploration of these features (WIP)
https://app.mural.co/invitation/mural/workqueue2001/1548889159757?sender=caroladsva8096&key=45119eda-58e5-44f5-b46a-58cceee94985

**Comment by carolaponce** [comment]
These mocks have been updated - closing this issue

**Comment by leikkisa** [comment]
@carolaponce Did you mean to close this issue (based on that last comment?)
