### ISSUE TITLE
Performance | Daily docket load time

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9774]
The daily docket queries need to be optimized.

**Comment by mdbenjam** [comment]
Understanding where we're spending our time:

URL | Controller | Average time ms (link to New Relic)
-----|-----------|--------------------------------
`hearings/hearing_day/:id` | `Hearings::HearingDayController#show` | [9200](https://rpm.newrelic.com/accounts/1788458/applications/80608544/transactions#id=5b22436f6e74726f6c6c65722f68656172696e67732f68656172696e675f6461792f73686f77222c22225d)
`regional_offices/RO17/open_hearing_dates.json` | `RegionalOfficesController#open_hearing_dates` | [4430](https://rpm.newrelic.com/accounts/1788458/applications/80608544/transactions#id=5b22436f6e74726f6c6c65722f726567696f6e616c5f6f6666696365732f6f70656e5f68656172696e675f6461746573222c22225d)
`hearings/schedule/docket/:id` (HTML) | `Hearings::HearingDayController#index` | [1090](https://rpm.newrelic.com/accounts/1788458/applications/80608544/transactions#id=5b22436f6e74726f6c6c65722f68656172696e67732f68656172696e675f6461792f696e646578222c22225d)
`regional_offices.json` | `RegionalOfficesController#index` | [19.1](https://rpm.newrelic.com/accounts/1788458/applications/80608544/transactions#id=5b22436f6e74726f6c6c65722f726567696f6e616c5f6f6666696365732f696e646578222c22225d)

**Comment by mdbenjam** [comment]
Good news is that `HearingDayController#show` is making BGS calls, so if we can prevent those I think we can reduce load times by over half.

**Comment by mdbenjam** [comment]
I don't think there's anything we can do with this since it sounds like we need all the information on this page.
