### ISSUE TITLE
[Tech spec] Move business logic out of controllers and into specialized classes

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#9775]
**Why**: Having small controllers whose primary concern is to send data to the view has been adopted as a best practice for a long time in the Rails community. To keep controllers small, consistent, and easier to understand, business logic should live in other classes.

References:
https://thoughtbot.com/blog/skinny-controllers-skinny-models
https://www.rubytapas.com/2017/04/11/skinny-controller-domain-model-events/
https://codeclimate.com/blog/7-ways-to-decompose-fat-activerecord-models/
https://thoughtbot.com/upcase/videos/form_objects

Since the majority of our controllers render JSON data for the frontend to consume, I am proposing a consistent pattern that is easier to understand and maintain, and less prone to bugs:

1. The controller calls a specialized class that processes the business logic
2. The specialized class validates the data, performs some actions, and returns a rich object to the controller
3. The controller asks if the task was successful
4. If it is successful, then it returns a 200 response, and if necessary, data for the frontend that it can grab from the rich object
5. If it was unsuccessful, it renders errors that the view can parse and display to the user

As an example, let's look at the `CaseReviewsController#update` action which allows a user to update the Document ID associated with an Attorney Case Review:

```ruby
def update
  result = UpdateAttorneyCaseReview.new(
    id: params[:id],
    user: current_user,
    document_id: params[:document_id]
  ).call

  render json: result.to_h, status: result.success? ? :ok : :bad_request
end
```
As you can see, the controller does very little. All of the business logic is handled by the `UpdateAttorneyCaseReview` class, which looks like this:
```ruby
class UpdateAttorneyCaseReview
  include ActiveModel::Model

  validates :id, presence: true
  validate :attorney_case_review_exists
  validate :authorized_to_edit

  def initialize(id:, document_id:, user:)
    @id = id
    @document_id = document_id
    @user = user
  end

  def call
    @success = valid?

    case_review.update!(document_id: document_id) if success

    FormResponse.new(success: success, errors: [response_errors])
  end

  private

  attr_reader :id, :document_id, :user, :success
  attr_writer :document_id

  def case_review
    @case_review ||= AttorneyCaseReview.find_by(id: id)
  end

  def attorney_case_review_exists
    return if case_review

    errors.add(:attorney_case_review, "id #{id} could not be found")
  end

  def authorized_to_edit
    return unless case_review
    return if allowed_to_edit_ama_case_review?

    errors.add(:user, "not authorized to edit this document ID")
  end

  def allowed_to_edit_ama_case_review?
    AmaDocumentIdPolicy.new(user: user, case_review: case_review).editable?
  end

  def response_errors
    return if success

    {
      title: "Record is invalid",
      detail: errors.full_messages.join(", ")
    }
  end
end
```
Since there are validations to perform, we include `ActiveModel::Model` in this class so that we can use the familiar `validate` and `validates` methods, and to make it easy to package up all validation errors and send them to the controller. It also makes it easier to see all the validations in one place, and keeps all the errors formatted consistently, which reduces the chances of mistyping when spelling out various error responses in a controller that might look like this:
```ruby
def update
  return case_review_not_found_error if case_review_not_found?
  return unauthorized_user_error if not_allowed_to_edit_ama_case_review?
  ...
end

def case_review_not_found_error
  render json: {
    "errors": [
      "title": "Attorney Case Review not found",
      "detail": "Could not find an Attorney case review with that ID"
    ]
  }, status: :not_found
end

def unauthorized_user_error
  render json: {
    "errors": [
      "title": "User not authorized",
      "detail": "This user is not allowed to edit the document ID for this case review"
    ]
  }, status: :unauthorized
end
```
Three additional advantages are:
 - It makes evident validations that might otherwise be obfuscated, as I have experienced in some controllers. 
 - It speeds up the app by not relying on raising exceptions, rescuing them, then raising some other exceptions, and rescuing those. Exceptions are known to be slow in Ruby, and the Ruby Style Guide says they should not be used for control flow. 
- It eliminates the chances of introducing `DoubleRender` errors

For example, the `AppealsController#show_case_list` action looked like this:
```ruby
def show_case_list
  respond_to do |format|
    format.html { render template: "queue/index" }
    format.json do
      caseflow_veteran_id = params[:caseflow_veteran_id]
      veteran_file_number = Veteran.find(caseflow_veteran_id).file_number

      render json: {
        appeals: get_appeals_for_file_number(veteran_file_number),
        claim_reviews: ClaimReview.find_all_by_file_number(veteran_file_number).map(&:search_table_ui_hash)
        }
    end
  end
end
```
At first glance, it is not at all obvious that if there is no Veteran matching `caseflow_veteran_id`, `Veteran.find(caseflow_veteran_id).file_number` will raise `ActiveRecord::NotFound`, which will then be rescued by `ApplicationController` and will render a custom `not_found` error. It is more readable to see a regular ActiveModel validation in a class that returns a `:not_found` error without the need to raise and rescue exceptions.

Similarly, the `AppealsController#index` action resulted in a `AbstractController::DoubleRenderError` because it was calling a render within a render:
```ruby
render json: {
  appeals: get_appeals_for_file_number(veteran_file_number)
}
```
and `get_appeals_for_file_number(veteran_file_number)` had logic that, in a particular scenario, would itself also call `render json` via `file_access_prohibited_error`.

Once the data is validated, the specialized class returns an instance of the `FormResponse` class which takes a minimum of two arguments: `success` and `errors`, and an optional `extra` argument that can contain a hash of other attributes that might be useful for the controller to read. The `FormResponse` instance responds to `success?` so the controller can easily and idiomatically determine the status of the business action, and also responds to `.errors`, `.extra`, and `.to_h` to get all of the attributes in one hash: `success`, `errors`, and `extra`.

The FormResponse class looks like this:
```ruby
class FormResponse
  def initialize(success:, errors:, extra: {})
    @success = success
    @errors = errors.to_ary
    @extra = extra
  end

  attr_reader :errors, :extra

  def success?
    @success
  end

  def to_h
    { success: success, errors: errors }.merge!(extra)
  end

  private

  attr_reader :success
end
```

The reason for having a specialized `FormResponse` class is to ensure consistency. We want controllers to always be able to call `.success?` and we want the `errors` to always be an array. If the business-logic-handling class returned a plain hash or OpenStruct instead, it could lead to inconsistencies as there is no easy way to enforce attributes or types. Using a hash instead of a proper class would also be considered a code smell by the name of [Primitive Obsession](https://refactoring.guru/smells/primitive-obsession).

**Comment by lowellrex** [comment]
I'm generally wary of assuming new software design patterns and this appears to be a pretty heavyweight new pattern that has plenty of very solid benefits (taking advantage of Rails validations is particularly clever) but I'm curious if these goals can't be accomplished using the existing patterns in the application.

From a high-level this proposed approach separates the jobs we ask our controllers to do into two distinct classes of file: controllers will handle argument wrangling and response formatting, and specific classes will do the business logic and format that into a standardized format to return to the controller. Is that a correct summary?

In addition to getting the rest of the team's opinion on this proposal, I'm curious about how you imagine we can transition from the current state of our controllers to this proposed end state?
