### ISSUE TITLE
Allow the establishment of spina bifida claims

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9778]
### Story
From Jane Chi:
Currently Caseflow does not allow for the establishment of spina bifida claims for Veteran's children and grandchildren.  For children, the first child's payee code is 11 and then 12, 13, etc for each subsequent child.  For grandchildren, the payee code is also 11 but there is a running EP400 to track these claims in VBMS.  VBMS will link the spina bifida child to the Veteran.  I am aware that Caseflow non-payee 00 functionality is being worked on (for burial claims) but want to raise this issue to ensure that this functionality is also available for the spina bifida claims establishment in Caseflow.

From Colin:
CH 18 claimants (spina bifida and birth defects) are unique in that they are have completely separate records from the veteran. Meaning, they have their own eFolder and File number. Their entitlement sure is based on the veteran, but its not like other benefits where the primary beneficiary is the Veteran, and the claimant is secondary (whos claims fall into the veterans umbrella). CH 18 Claimants will still get a non payee-00 applied to their claim, like other non-veteran claims, but also get established with their own file number and record, entirely separate from the veteran. So, thinking outloud, Caseflow might have to altered to account for that. Rather than inputting the Vets FN at intake, the CH 18 Claimants info is entered at intake, for example.

**Comment by nicholasholtz** [comment]
Speculation from AMO is that this is dependent on VBMS claims service, which does not currently have the ability to create these claims. This statement deserves further investigation.

**Comment by shanear** [comment]
Less than 1000 claims per year are Spina Bifida (meaning the appeals would be less than 150)

They are not processed in VBMS-R, but are processed in VBMS-A
