### ISSUE TITLE
Hide duplicate organization tasks from Task Snapshot

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9785]
Currently we display all active tasks in the task snapshot. This results in us displaying some tasks assigned to organizations that duplicate their child tasks assigned to real people (see example below). We should hide these tasks from the task snapshot when there are no actions available for those tasks. We have [an existing ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/8937) to hide duplicate tasks from the case timeline so we can probably re-use whatever we do there in service of completing this ticket.

<img width="1003" alt="example" src="https://user-images.githubusercontent.com/32683958/53818492-24d16f80-3f36-11e9-9477-c5d47111bc6a.png">

## Acceptance criteria
* [ ] Determine what it means for a task to be a "duplicate"
* [ ] Hide duplicate tasks from the task snapshot

**Comment by tomas-nava** [comment]
SMALL (may be able to reuse work done in #8937)
