### ISSUE TITLE
Intake | DTA SC should have delayed submit_for_processing

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9794]
Supplemental claims created as the result of a DTA decision may have a decision date in the future and should have an explicit delay in their `submit_for_processing` call.

### Validation
1. Create a HLR or SC with a benefit type that is not compensation or pension
2. Add a nonrating issue
3. Go to the non-compensation page and make a decision on that issue that is a DTA error, with a decision date that is in the future (maybe just one day)
4. After the decision date comes, check that the original decision review now has a remand supplemental claim, and that the submitted_at date is the same as the decision_date

**Comment by leikkisa** [comment]
We do not allow receipt_dates in the future for Decision Reviews, and the receipt_dates are set to the decision_date, which can be in the future. This makes the specific issue above not a problem.  From what I've seen in appeals, if a decision_issue is created, the remand supplemental claim doesn't seem to be created or processed until after that date has arrived.

I need to check what happens in the case of HLRs, because technically this could cause an HLR to fail in creating the remand SC. We haven't seen this yet in prod.

I also can't find the Sentry error that instigated all of this :-/.

**Comment by Sjones352** [comment]
<img width="1386" alt="Screen Shot 2019-03-14 at 7 20 40 PM" src="https://user-images.githubusercontent.com/23080951/54398619-37178000-4691-11e9-82eb-63e16f15561f.png">
<img width="1449" alt="Screen Shot 2019-03-14 at 7 21 31 PM" src="https://user-images.githubusercontent.com/23080951/54398620-37178000-4691-11e9-966f-6dc903df537d.png">
<img width="1505" alt="Screen Shot 2019-03-14 at 7 21 48 PM" src="https://user-images.githubusercontent.com/23080951/54398621-37178000-4691-11e9-9016-e1206a059672.png">
<img width="1680" alt="Screen Shot 2019-03-14 at 7 23 11 PM" src="https://user-images.githubusercontent.com/23080951/54398622-37178000-4691-11e9-8dc5-a8743b9a0d9b.png">
<img width="1341" alt="Screen Shot 2019-03-14 at 7 23 46 PM" src="https://user-images.githubusercontent.com/23080951/54398623-37b01680-4691-11e9-8dd0-8461c4df5cf4.png">
<img width="1204" alt="Screen Shot 2019-03-14 at 7 53 56 PM" src="https://user-images.githubusercontent.com/23080951/54399076-17815700-4693-11e9-9a2e-004d5a0b3908.png">
<img width="1083" alt="Screen Shot 2019-03-14 at 7 54 37 PM" src="https://user-images.githubusercontent.com/23080951/54399077-17815700-4693-11e9-8349-b918142de81a.png">

**Comment by Sjones352** [comment]
Checked this morning and I am still getting 
`hlr.remand_supplemental_claims
[2019-03-18 11:52:44 -0400]   SupplementalClaim Load (1.2ms)  SELECT  "supplemental_claims".* FROM "supplemental_claims" WHERE "supplemental_claims"."decision_review_remanded_id" = $1 AND "supplemental_claims"."decision_review_remanded_type" = $2 LIMIT $3  [["decision_review_remanded_id", 1306], ["decision_review_remanded_type", "HigherLevelReview"], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy []`

**Comment by Sjones352** [comment]
@leikkisa this still fails in UAT. Wondering how I can validate it
` hlr.remand_supplemental_claims
[2019-03-21 16:14:29 -0400]   SupplementalClaim Load (0.6ms)  SELECT  "supplemental_claims".* FROM "supplemental_claims" WHERE "supplemental_claims"."decision_review_remanded_id" = $1 AND "supplemental_claims"."decision_review_remanded_type" = $2 LIMIT $3  [["decision_review_remanded_id", 1306], ["decision_review_remanded_type", "HigherLevelReview"], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy []>`

**Comment by leikkisa** [comment]
Oh, we are only handling the VBMS dispositions right now. I'm glad we did a processed_in_caseflow DTA.

Unfortunately, that's another issue and since the decision date is passed now, we'll have to validate this one again after that issue is fixed.

**Comment by leikkisa** [comment]
Validated that the remand SC has a delayed submit_for_processing (See SC 452), however, it is not sufficient, at least not in UAT to avoid the claim date issue.

The data value of the ClaimDateDt within the claimToEstablish did not satisfy the following condition: The ClaimDateDt value must be a valid date for a claim.
https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1451/

The claim date is: Fri, 29 Mar 2019
The Sentry date is 12:02AM On March 29th
The establishment_submitted_at is: 2019-03-29 00:02:29

So the submitted_at date is being set correctly. Perhaps the VBMS server is in a different timezone?

**Comment by pkarman** [comment]
@leikkisa is this one really ready for validation or do we still need to adjust the timing?

**Comment by leikkisa** [comment]
Considering this validated, the last instance of the invalid claim date error was one day before the fix.
