### ISSUE TITLE
Footer has scroll bar

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#980]
![screen shot 2017-02-21 at 6 08 44 pm](https://cloud.githubusercontent.com/assets/3885236/23189448/f3438296-f860-11e6-9096-70f6ab3be1ed.png)
A recent addition to the footer CSS has made the footer have a scroll bar. I think the overflow rule should be removed or modified.

**Comment by kierachell** [comment]
I was just about to create an issue for it :D

**Comment by kierachell** [comment]
**PASSED**
![footerisok](https://cloud.githubusercontent.com/assets/18075411/23226324/254bf9a6-f903-11e6-9630-8e1c2bcc91a6.png)
