### ISSUE TITLE
New documents and document count issues

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9808]
### Context
We have seen a lot of support tickets and 500 errors for these two particular endpoints. 

### Document count
Inaccuracy between VBMS and Caseflow nightly cached documents.

Solution: always query for VBMS for this endpoint. Implement batch processing to improve performance.

### New Documents
The code logic is very complex and has a lot of conditions.  We need to think of ways to simplify this approach.  

Currently, we have 4 scenarios with different conditions:

1. Case details page - does not use on_hold_at date and queries VBMS
2. On hold tab - uses on_hold_at date and does not query VBMS (queries Caseflow documents table). Note: attorney legacy appeals use colocated tasks to determine which appeals are on hold for them -  this adds even more complexity. 
3. Assign cases page - does not use on_hold_at date and does not query VBMS (queries Caseflow documents table). Judge legacy appeals do not have a task record in Caseflow -  this adds even more complexity. 
4. Unassigned tab for org queues - does not use on_hold_at date and does not query VBMS (queries Caseflow documents table).

Options:
1. Always query VBMS for all pages. Implement batch processing to improve performance. 
2. Completely get rid of this icon for now. Re-think design and whether it is even useful for users.
3. On hold tab can use the logic as the rest of the pages. Do not use placed_on_hold_at for the on hold tab. 
4. Hunter's idea: only use new documents icon for the on_hold tab and remove new documents icon from the rest of the pages. 

I am personally in favor of doing 1 and 3 for the new documents and it should simplify things a lot.

**Comment by lowellrex** [comment]
Perfectly stated summary of our current situation, @aroltsch! That's for writing this up so concisely.

My ranked preference for the 4 options you lay out are as follows:
2. **Completely get rid of this icon for now.** I'm not sure this is tenable from a product perspective but I think this approach is the most technically appetizing approach.
1. **Always query VBMS for all pages.** Responses would take longer but would be simpler technically and more precise
3. **On hold tab can use the logic as the rest of the pages.**
4. **Only use new documents for the on_hold tab.** I'm not sure I know what this approach suggests we do, so I don't know how to appropriately rank it.

**Comment by laurjpeterson** [comment]
When we rely only on Caseflow tasks for all users across legacy and AMA cases (attorneys and judges use legacy Caseflow tasks for legacy cases, whereas VLJ support users rely on Caseflow tasks for legacy cases), will the new documents icon be any easier? Because tracking tasks among the tabs is easier?

**Comment by aroltsch** [comment]
Maybe slightly easier. The problem that we are facing that we are spending a ton of time and engineering resources on this and I don't know whether this feature is even very useful to users :).

**Comment by aroltsch** [comment]
Decision made:
1. Always query VBMS for document count to avoid count inaccuracy
2. Remove new documents icon for now
