### ISSUE TITLE
Data backfill | Disposition updates

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9812]
AC: 
- [ ] Confirm that all video hearings post April 1st have HearingTaskAssociations 
- [ ] Confirm all video hearing prior to April 1st do not
- [ ] Confirm that all CO hearings with DispositionTasks have HearingTaskAssociations
- [ ] Confirm that there are no stale HearingTaskAssociations (hearings that were postponed through the Caseflow daily docket will be out of date)
- [ ] Confirm any appeal with an open HearingTask has a vacols location of 'Caseflow'
- [ ] Confirm all AMA hearings have an associated HearingTask

**Comment by oscarAtNava** [comment]
Prod Queries and Research Notes:

```
video_hearings_post_april = VACOLS::CaseHearing.where("trunc(hearing_date) > ?   
and hearing_type = 'V'and hearing_disp is null", "2019-03-31")   

video_hearings_post_april.size => 781

list_of_folder_nr = video_hearings_post_april.pluck(:folder_nr) . 
legacy_appeals = LegacyAppeal.where(vacols_id: list_of_folder_nr) . 
legacy_appeals.size => 781 . 

legacy_appeal_ids = legacy_appeals.pluck(:id) . 
hearing_tasks = HearingTask.where(appeal_id: legacy_appeal_ids) . 
hearing_tasks.size => 752  
```
29 legacy hearings with no HearingTask associated with them.
