### ISSUE TITLE
Bug: Indiana RO Not Loading Hearing Dates In Modal

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9814]
Indianapolis RO is not loading hearing days in the Schedule Veterans modal for any veterans in the schedule list. See any Veteran listed in the Legacy or AMA lists to repeat this error. Dates never load. 

https://appeals.cf.ds.va.gov/hearings/schedule/assign?roValue=RO26

**Comment by lomaxap** [comment]
Looks like a latency issue. Dropdown occasionally loaded in under 15 seconds, but Indianapolis is oddly taking longer than other ROs with the same number of upcoming hearings or more. Probably worth looking into the performance of [`open_hearing_days_with_hearings_hash`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/hearing_day.rb#L147)

**Comment by ShellySmithDSVA** [comment]
Load times verified as back to normal. Closing ticket but will re-open if same thing occurs.
