### ISSUE TITLE
Intake | Legacy opt-in modal multi-click fails to register "None of these match"

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9816]
In the Legacy issue (VACOLS) opt-in modal during intake, if you:

* click on an issue radio button
* then click change to the "None of these match" radio button
* then click Add Issue

it will fail to register the None of these match and instead apply an eligibility error based on the first selected radio button issue.

We observed this during an Intake ridealong.

**Comment by Sjones352** [comment]
@leikkisa Please provide validation instructions. @pkarman I am a little confused about this statement `then click change to the "None of these match" radio button` I thought "None of these match" is a regular button.

**Comment by leikkisa** [comment]
@Sjones352 

### Validation
- Choose a Veteran that has Vacols issues (we might need to find one or create one)
- Do an AMA intake
- Add an issue
- The modal for whether it is connected to any Vacols issues should pop up
- First select one of the VACOLS issues
- Then select "None of these match"
- Then finish the intake
- The Request Issue that was added should have nil for vacols_id in the database

**Comment by Sjones352** [comment]
Checking for a veteran with Vocals issues, If I don't find one then let's create one.

**Comment by Sjones352** [comment]
@pkarman  and @leikkisa unfortunately this fails UAT validation unless I am doing wrong.

<img width="778" alt="Screen Shot 2019-03-13 at 7 09 08 PM" src="https://user-images.githubusercontent.com/23080951/54321366-31edfe80-45c7-11e9-8d4b-69e1a5ebff19.png">
<img width="1252" alt="Screen Shot 2019-03-13 at 7 10 05 PM" src="https://user-images.githubusercontent.com/23080951/54321367-32869500-45c7-11e9-970d-95947c441e99.png">

vacols_id is not nill
<img width="1680" alt="Screen Shot 2019-03-13 at 7 33 17 PM" src="https://user-images.githubusercontent.com/23080951/54321392-51852700-45c7-11e9-8722-941b5bdf6976.png">

**Comment by pkarman** [comment]
thanks @Sjones352 -- the trick for this one is to click the "Dental" and then click "None of these match" and then the "Add this issue" button.

I validated this locally and it works, so I am going to close.
