### ISSUE TITLE
Return Locked Ratings

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9817]
### Story
A Locked Rating means the rating is being worked on. If a Veteran has a Locked Rating, and regular promulgated ratings, we'll just get the regular promulgated ratings.  If a Veteran only has a Locked Rating, we get an error, and catch it and let the Intake proceed with no ratings.

We've been told by BGS that Locked Ratings shouldn't be shown because since they are still being worked on, they are not decided and shouldn't be eligible to be intaken again at the moment.

According to Colin, the rating issues on a rating could have different decisions. Let's say 4 of them were denied and 1 of them was deferred, the deferred rating issue could cause the Rating to be locked, while the denied ratings issues would be eligible to be appealed and intaken again.

We need to clarify this with BGS.  It is possible that we will want to ask them to return Locked Ratings to us.

**Comment by pkarman** [comment]
e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3976/events/270463/

**Comment by leikkisa** [comment]
I don't believe that we will be able to get access to the ratings while they are locked anytime soon, although this might change with the API they are working on which I believe will operate at the rating issue-level.

For returning all non-locked ratings, we now have this:
```<RatingDateRange>
            <allowLockedRatings>Y</allowLockedRatings>
            <claimDate></claimDate>
            <endDate></endDate>
            <ptcpntId></ptcpntId>
            <startDate></startDate>
      </RatingDateRange>```

**Comment by Sjones352** [comment]
<img width="1671" alt="Screen Shot 2019-04-29 at 5 31 56 PM" src="https://user-images.githubusercontent.com/23080951/56928444-d3141400-6aa4-11e9-98bb-4ef4904d88d3.png">
