### ISSUE TITLE
Bug: Veteran appears in list to be scheduled, but already scheduled for hearing (duplicate task?) 

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#9834]
The Veteran below only has 1 ACT legacy appeal stream however, and he is scheduled for a hearing for 4/23/2019. However, the Veteran still appears in list of Veterans to be scheduled. 
 
https://appeals.cf.ds.va.gov/cases/190101

Need to check the status of the tasks on this case - is there a duplicate?

**Comment by MeredithStewart** [comment]
Checked with Sharon -- resolution on this one was for the Branch to "withdraw hearing" on that duplicate task. Emailed branch on 3/7/19 to take this action. Veteran should still appear on the docket for 4/23/19.
