### ISSUE TITLE
Associate rating issues not finding rating

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9837]
When we try to associate rating issues to the contentions in VBMS, we are getting the following error:

Unable to associate rated issue, rated issue does not exist.

Sentry example https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3405/events/265269/

This does not prevent the claim from establishing or the contentions from being created, or cause any major known issues, but it is used to create linkages in the data.  We believe this is a bug on the BGS side, and are awaiting a solution.

**Comment by pkarman** [comment]
BGS defect# 941039

**Comment by pkarman** [comment]
Should now be in UAT. Fix scheduled for April CI.

**Comment by pkarman** [comment]
These should appear on the /jobs page with error `#<VBMS::RatedIssueMissingError:`

**Comment by pkarman** [comment]
HLR created successfully as 6ce7c659-4c92-48f7-89a6-84010231a8d6 with no error.
