### ISSUE TITLE
Expanding eFolder Express access for private attorneys

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9838]
Creating a specific issue addressing the question of eX access exclusively, for ease in OIT tracking. This fits in with https://github.com/department-of-veterans-affairs/caseflow/issues/7774 and https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/624#issuecomment-333321781.

**Comment by nicholasholtz** [comment]
From the Board:

> Provide accredited private attorney access to Caseflow and E-folder express.
> - Limitations on access restricted to a single POA (accredited attorney) within a law firm.

**Comment by laurjpeterson** [comment]
Closing this one because we've confirmed that private attorneys can get access to eFolder Express through the CSEM process.
