### ISSUE TITLE
Remove listing VACOLS RO in "About the Veteran"

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9853]
In Case Details, we are pulling in the RO listed in VACOLS for legacy Veterans in the "About the Veteran" section. 

This is confusing for Hearing Schedule because we are geo-matching Veterans based on their address to ROs for hearings. The Hearing Branch is confused as to why there are discrepancies. Certain appeals are assigned to ROs to work special issues. VBA could also potentially move hearing cases around the country to be worked in the national work queue. 

Lower priority among other Hearing Schedule work.

## AC
- Regional Office data from VACOLS no longer appears on any Case Details page

**Comment by MeredithStewart** [comment]
@laurjpeterson -- Let me do some more research on this to make sure remove is desired by the hearing branch. They might like the fact that it shows a different location - as a trigger for them to look closer at the hearing location then they might otherwise.

**Comment by youngfreezyVA** [comment]
hi @MeredithStewart @laurjpeterson I'm not familiar with the change that needs to be made, could you provide screenshots, example user, veteran ID, and also confirm that you were able to follow up based on your above comment @MeredithStewart? thanks! cc: @aroltsch

**Comment by laurjpeterson** [comment]
![image](https://user-images.githubusercontent.com/27704093/54163547-c9b8e480-442f-11e9-9f04-b8e3cef6a6ca.png)

This is from this legacy appeal - https://appeals.cf.ds.va.gov/queue/appeals/2969703

**Comment by MeredithStewart** [comment]
@laurjpeterson -- Let's make this change! 

It's confusing for the user, especially since there's a note at the bottom that says the Veteran info is coming from VBMS.  

Let's get rid of it on Case Details. Thanks!

**Comment by laurjpeterson** [comment]
Sounds good! The dev work for this is complete, so @youngfreezyVA will merge!
