### ISSUE TITLE
BUG: Can we change San Antonio Veterans to map to Houston, TX?

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9858]
(Bug, but not a bug.) 

San Antonio issue - San Antonio Veterans are matching to Waco, TX RO correctly because Waco is closer, but San Antonio is an alt hearing location of Houston, TX.

Should we do something to map the San Antonio Veterans to Houston so these Veterans automatically show up in the Houston list of Veterans to schedule?

**Comment by MeredithStewart** [comment]
Update: We expected the San Antonio Veterans to show up under Houston over time since this change was deployed. As of 3/27/19, only 6 Veterans show up in the Houston list matched to the San Antonio, but we think a lot more to this add to this lists, but they don't seem to be moving over.

**Comment by MeredithStewart** [comment]
As of 3/29/19 -- still only 6 Veterans show up under Houston legacy list.

**Comment by ShellySmithDSVA** [comment]
Checked 4/5 - appeals still not moving over. Re-opening ticket.

**Comment by lomaxap** [comment]
Job was backed up. This should be resolved.
