### ISSUE TITLE
Intake | Move Veteran profile validation to later in the flow

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9871]
See https://dsva.slack.com/archives/C754H751T/p1552078332077900

Non-comp LOB users may not have permission to edit in VBMS but since non-comp LOB claim reviews do not spawn End Products, it does not matter. Change the veteran profile validation till later in the flow so that the LOB can be detected and the validation errors suppressed if the claim review is for non-comp.

## Acceptance criteria

Given a Veteran with missing address or other required data:

* do not show the validation errors on the Search page
* do show the validation errors on the Review page, only if the selected Benefit Type is "compensation" or "pension"

**Comment by Sjones352** [comment]
Waiting on Colin to provide me a file number with missing address.

**Comment by Sjones352** [comment]
Mohi from VBMS created for me Veteran with missing address. This passes UAT

<img width="1514" alt="Screen Shot 2019-03-26 at 11 48 44 AM" src="https://user-images.githubusercontent.com/23080951/55012322-9fcdf900-4fbd-11e9-9053-16e9f5cc0e50.png">

<img width="1651" alt="Screen Shot 2019-03-26 at 11 55 26 AM" src="https://user-images.githubusercontent.com/23080951/55012695-2da9e400-4fbe-11e9-9780-3f64b36b18df.png">
