### ISSUE TITLE
Create instructional text component

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9879]
Create a reusable component for instructional text in our style guide. 

Behavior: Default state of instructional text is collapsed with caret pointing to the right. On click of either the caret or the link, caret rotates 90 degrees clockwise, and text displays. See the "Hidden text" section of the [gov.uk](https://design-system.service.gov.uk/components/details/) style guide for clickable example. 

<img width="1070" alt="Screen Shot 2019-03-11 at 9 40 04 AM" src="https://user-images.githubusercontent.com/40216950/54128251-0b22a300-43e2-11e9-93fe-8dd85b8dc7e1.png">

I'm unable to paste the .svg file for the caret in Github, so I uploaded it to our design research repo: https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Design/Design%20Files/Icons/Caret.svg

### AC
- [ ] New component for instructional text created
- [ ]  Added to style guide
- [ ] Added to storybook

**Comment by allyceh** [comment]
@sneha-pai When you have a chance, I am wondering if you can review these specs I added to the ticket. I also provided an .svg for the caret. 

Once we're aligned, we can try to get this slotted with the Style Guide Committee.

**Comment by tomas-nava** [comment]
SMALL
