### ISSUE TITLE
Mousewheel does not scroll through searchable dropdown

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9884]
From VBA: 

> One of our users in Portland reached out, with a questions pertaining to the Caseflow interface in VBMS. The problem issue occurred when the user went into the “Edit in Caseflow” button, and selected “Add Issue”, then “None of these match, see more options”.   When the user opened up the little drop down arrow under “Issue Category”, the little slide bar didn’t work.  The user could only find more categories by using a mouse with a wheel to scroll down.  This was discovered because the user has a special ergonomic mouse that doesn’t have one of the rollers.

**Comment by allyceh** [comment]
@shanear , @marvokdolor-gov and I observed this with one of our users today, but in her Queue. We also have an open ticket for it: https://github.com/department-of-veterans-affairs/caseflow/issues/9170

Is this something where one fix could fix all instances of this? 

cc: @laurjpeterson

**Comment by pkarman** [comment]
Agreed we should be able to fix this globally via whatever react component is affected.

**Comment by pkarman** [comment]
closing as a duplicate
