### ISSUE TITLE
Route Claim | Vocational Rehab

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#989]
# Description:
As a Caseworker I have no idea where to email or send any claim with SIC _Vocational Rehab_

**Type of Bug:**
- [X] Functional

- [ ] UI

- [ ] Security

- [ ] Tech Improvement

**Severity Level:**

**`uat`**

# Reproductive Steps
**Scenario 1:**
**`uat`**

1. Start Establishing Claim

2. Review Decision and select _Vocational Rehab_ SIC

3. Click **Route Claim**

4. Observe that there is no RO Code, City, or Email

# Screen Shots
**_Scenario 1 - `uat` Route Claim_**
![vocationalrehab case conflict](https://cloud.githubusercontent.com/assets/18075411/23231644/8a4b0e6a-f916-11e6-9e63-b9fa2f1f506b.png)

# Relate Stories/Issues
**_Support Tickets/Features/Issues_**
Decision Review | Multiple Special Issues Rules - #911 
Route Claim | Display Informational Route Claim unable to create EP (Full Grants with Special Issues/RO Email) #722

**Comment by shanear** [comment]
Yeah, we probably are just missing the mapping here. Can you take a look @sharonwarner

**Comment by shanear** [comment]
This is captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/957

closing this one.
