### ISSUE TITLE
Working list of data that Caseflow caches

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9890]
We cache information from our dependencies in a variety of ways. This ticket is a working list of the various things we cache and how we do it.

## VSO's POA association with an appeal
* How do we build the cache: A nightly `UpdateAppellantRepresentationJob`
* What is the original source: BGS
* How do we store the cache: As a `TrackVeteranTask` associated with an appeal in the Caseflow postgres database.
* How long does the cache live: 1 day (or indefinitely if the appeal has been dispatched)

## Regional Office for an appeal
* How do we build the cache: Hourly `FetchHearingLocationsForVeteransJob`
* What is the original source: VA.gov
* How do we store the cache: In the `closest_regional_office` field of both `(?:legacy_)appeals` tables.
* How long does the cache live: Weekly

**Comment by amprokop** [comment]
# Documents for Reader
- How do we build the cache: Nightly FetchReaderDocumentsForUserJob
- What is the original source: VBMS
How do we store the cache: documents tables
How long does the cache live: ?

**Comment by cmgiven** [comment]
## Difficult to compute VACOLS info (AOD, DIC, etc.)

* How do we build the cache: On demand, using `cache_attribute` from our custom `CachedAttributes` module
* What is the original source: VACOLS
* How do we store the cache: Redis
* How long does the cache live: ?

**Comment by pkarman** [comment]
All these are stored in Rails cache (Redis)

## Slow upstream endpoints

* Ratings for a Veteran
* User can access Veteran

## Slow models

* Intake stats

**Comment by laurjpeterson** [comment]
Wow just discovering this ticket - this is so great!

**Comment by pkarman** [comment]
I think we met the need this issue raised with #10330
