### ISSUE TITLE
VSO Schedule - UpdateAppellantRepresentationJob

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9896]
We are using TrackVeteranTasks to determine which appeals' hearings to display for each VSO. Currently the UpdateAppellantRepresentationJob only creates TrackVeteranTasks for AMA appeals. We need to update that job to create TrackVeteranTasks for legacy appeals as well.

**Comment by mdbenjam** [comment]
Blocked on: https://github.com/department-of-veterans-affairs/caseflow/issues/10033
