### ISSUE TITLE
Refactor / Document how we're handling time

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#9901]
We currently handle time when creating hearings in a couple of different ways.

On the daily dockets ([hearing sched](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/hearingSchedule/containers/DailyDocketContainer.jsx#L176) / [hearings controller](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/hearings_controller.rb#L13)). In the [Assign Hearing modal ](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/AssignHearingModal.jsx#L267)/ [slot_new_hearing](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/repositories/hearing_repository.rb#L98) method. (any where else?)

This has introduced a number of bugs, particularly around timezone and daylight saving time shifts. We should document how a hearing's time is stored and accessed in VACOLS vs. caseflow and create a consistent method for handling both, if it doesn't exist already.

--------------

We should update the hearing model to store times as strings.

**Comment by nicholasholtz** [comment]
@sharonwarner @pshahVA 

This is an example of a docket where the times are way off. I note that this is legacy. Are these cases that were scheduled through Caseflow? Is there a way to know? 

https://appeals.cf.ds.va.gov/hearings/schedule/docket/282

(cc @lomaxap @laurjpeterson )

**Comment by nicholasholtz** [comment]
Another example - https://appeals.cf.ds.va.gov/hearings/schedule/docket/282

**Comment by sharonwarner** [comment]
@nicholasholtz anything scheduled on a caseflow hearing day (after 4/1 for video and 1/1 for co) had to have been scheduled for caseflow, so the docket you linked to above was definitely scheduled through caseflow.

**Comment by nicholasholtz** [comment]
Ah, of course. Thanks.
