### ISSUE TITLE
Look into why attorneys/judges can check out ineligible issues

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9904]
A user on the BVA Dispatch team reached out to us about this case where decision issues weren't displaying: https://appeals.cf.ds.va.gov/queue/appeals/ae79b19f-44e4-4b9a-8308-b7db8b5acbd6

After taking a closer look, @aroltsch noticed that the issue on this case was ineligible. But, the attorney was able to check the case out to their judge, and the judge was able to sign the decision and check it out to BVA Dispatch. 

Next steps: 
- Understand why the issue is ineligible (also in another appeal lane? already in another appeal stream?) @pkarman or @shanear could help us with this. 
- Prevent ineligible request issues from displaying in the IDT.
- Add validations to attorney-judge checkout so that attorneys and judges can't check out cases where all issues are ineligible. Or, prevent Caseflow from Intaking the ineligible issue so that we don't need to add these validations. 
- Determine what to communicate to the attorney and judge-- if the issue is ineligible, we won't be mailing a decision letter to the Veteran, and we need to pull it out of the BVA Dispatch queue.

**Comment by allyceh** [comment]
cc: @aroltsch @laurjpeterson @shanear @pkarman

**Comment by pkarman** [comment]
I believe @shanear is actively working on this, and some changes went out this morning in #9893

**Comment by pkarman** [comment]
See also #9875

**Comment by allyceh** [comment]
@laurjpeterson This case has been in a BVA Dispatch user's queue for 13 days. I think we should pull this case from his queue (cancel the BVA Dispatch task) since the decision letter should not go out in the mail, and the Veteran should not receive a decision. For the purpose of cleaning up this case's timeline, is there also a way to remove the judge and attorney tasks from the timeline since those never should've happened and the case shouldn't have been worked? Or for the purposes of tracking "credit" for the case, should we leave those?

Deciding if the attorney and judge actually get credit for the case is likely a business decision and out of our scope.

**Comment by laurjpeterson** [comment]
@aroltsch - could we cancel all the tasks (so they all have the "canceled" status)? BVA dispatch, attorney, and judge tasks?

As for the case timeline, I suggest we don't make any changes unless it's quite easy to append a word - something like "AttorneyTask - canceled". We'll have to design what a canceled task looks like in the Case Timeline when we have bandwidth to come back to that

**Comment by aroltsch** [comment]
I will look into it

**Comment by aroltsch** [comment]
```
a = Appeal.find_by(uuid: "ae79b19f-44e4-4b9a-8308-b7db8b5acbd6")
a.tasks.where(type: ["AttorneyTask", "JudgeDecisionReviewTask", "BvaDispatchTask"]).update_all(status: Constants.TASK_STATUSES.cancelled)
```

**Comment by laurjpeterson** [comment]
Asked Rachel (LRP) about this because I saw another Direct Review docket case for this same Veteran. Two decisions were drafted for this Veteran. One with VLJ Moshiashwili and the other VLJ Senyk. The one assigned to Moshiashwili has 2 eligible issues, and the one assigned to Senyk has 2 ineligible issues. They seem somewhat similar, but I'm not sure which are right.

<img width="927" alt="Screen Shot 2019-03-15 at 5 00 35 PM" src="https://user-images.githubusercontent.com/27704093/54461875-40adf000-4744-11e9-8fc2-3070b7d1dbdb.png">

The DVCs have to decide which case to dispatch to the Veteran (and therefore which case to remove as a duplicate). So unfortunately, I was incorrect in canceling these tasks just yet. Let's hold off on doing anything else until we hear from Rachel and the DVCs.

**Comment by allyceh** [comment]
@laurjpeterson @aroltsch A decision was made about this case. Judge Senyk's decision will be dispatched, and he was asked by the DVC to add decision issues to this case. (See email I forwarded for context around decision). 

A BVA Dispatcher (Will) reached out to me this afternoon and said that Judge Senyk reached out to him via email, and he wants the case back so that he can add the issues. However, the case isn't in Will's queue and it's assigned to National Veteran's Organization of America when the case is searched. 

Can we manually assign the case to the judge so that he can add decision issues? Is this the correction action for the judge to take?

**Comment by allyceh** [comment]
Closing this issue. 

Resolution: @aroltsch manually reassigned this case to the judge, and it's now in his queue.

**Comment by allyceh** [comment]
Closing out this issue. 

Resolution: Rachel added the issues to this case. We then manually assigned the case to Judge Senyk so that he could add the dispositions. BVA Dispatch confirmed that the case then appeared in their queue for dispatch.
