### ISSUE TITLE
Bold new tasks in all queues

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9916]
Currently, we distinguish between tasks where somebody has visited the case details page and tasks where they have not [only for members of the VLJ support staff](https://github.com/department-of-veterans-affairs/caseflow/blob/65bfc1f3a3d33ada7136bd290ce4452bd709bbd9/client/app/queue/CaseDetailsLink.jsx#L46). This ticket exists to bold/unbold links to the case details page for an appeal in the task queue for everybody. This would likely require us to change from using the `status` field of the task to something more involved (perhaps a `task_views` table linking a user to a task).

## Acceptance criteria
* [ ] Show links to all cases in bold if they have not been viewed yet by the current user

**Comment by hschallhorn** [comment]
Closed in #14277
