### ISSUE TITLE
missing appeal when rendering case details

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#9921]
[Sentry page](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4059/)

A `TypeError` was raised on a legacy appeal's case details page because the `appeal` object passed to the component was `undefined`. This has only happened once according to Sentry, so low priority.

**Comment by hschallhorn** [comment]
10mo old. Closing
