### ISSUE TITLE
Missing appeal when rendering select disposition modal

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#9924]
[Sentry page](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3823/)

A TypeError was raised when rendering a select disposition modal for a legacy appeal because the appeal object passed to the component was undefined. This has only happened twice according to Sentry, so low priority.

**Comment by hschallhorn** [comment]
Have not seen for 10 months. Closing
