### ISSUE TITLE
User is trying to edit an issue that was deleted from Vacols

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#9925]
[Sentry page](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3617/)

A user is trying to edit an issue that was deleted from VACOLS. It is possible that the user is deleting an issue from Vacols directly and then is trying to edit it in Caseflow. Think about logging we can add to track this problem. If this is exactly what happens that a user deleted it from Vacols, we should add a friendly message on that page letting user know.

**Comment by aroltsch** [comment]
It could be fixed. Last time it happened on July 17th. Keeping an eye on it.

**Comment by aroltsch** [comment]
Happened again.

**Comment by jimruggiero** [comment]
Tagging as an investigation ticket. Peter may have fixed this, but need to confirm - Sally to ping him and circle back here after.

**Comment by leikkisa** [comment]
This looks like it's fixed, no new instances since August 15th.
