### ISSUE TITLE
Add SAVE button to Hearing Prep Worksheet

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9940]
With the move from auto-save to the save button on the Hearing Prep daily docket, the DVCs think that it is important to also update the Hearing Prep worksheet with a Save button. That way users behavior is consistent and they would be less likely to close the daily docket without saving.

**Comment by laurjpeterson** [comment]
Note: We haven't gotten any user feedback having issues with saving/auto-save for the Hearing Worksheet, so we are going to close it.
