### ISSUE TITLE
Fix race condition for on_decision_issues_sync_processed

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9948]
#### Story
If two decision issues are processed at the same time, they may not kick off the on_decision_issues_sync_processed job that creates remand supplemental claims.

#### Acceptance criteria
If an end product establishment has multiple decision issues, and any of them have a disposition of remanded, creating the remand supplemental claim should be kicked off.  This should not be prevented if the decision issues are synced at the same time.

#### Technical notes
This is happening in the End Product Establishment model at decision_issues_sync_complete?

One approach could be creating the remand supplemental claim once there is a remanded decision issue, and adding to it for subsequent decision issues, instead of waiting for all decision issues to be finished processing.

**Comment by leikkisa** [comment]
I manually kicked off the one in Prod that wasn't started, the result is Supplemental Claim 1234

**Comment by leikkisa** [comment]
Script for detecting these:
```
dis=DecisionIssue.remanded.select {|di| di.request_issues.first.decision_sync_processed_at != nil && di.decision_review.remand_supplemental_claims.count == 0}
```

When I checked today there were 197.

Script for fixing them:
```
dis.each{|di| di.decision_review.create_remand_supplemental_claims!}
```

**Comment by msj0nes** [comment]
@leikkisa is this ticket ready for closure?

**Comment by GabbyTISTA** [comment]
Moved to https://vajira.max.gov/browse/CASEFLOW-1691
