### ISSUE TITLE
Cancellation | Remove old cancellation modal 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#996]
See #920 and #984 
Beside removing old code, refactor cancel_certification_modal_new into cancel_certification_modal

**Comment by astewarttistatech** [comment]
Any UI changes? @nemodjuric

**Comment by nemodjuric** [comment]
No UI changes, just removing code.

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate: 
1. Go to app/views/certifications/mismatched_documents.html.erb 
2. Validate the removal of code per #984 and the adding of new code. 

Validated locally
