### ISSUE TITLE
Bug: User unable to assign tasks to any individual on their team

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#9964]
### Description
During refresher training with AOD team, Charlene (AOD Team Lead) was unable to assign a case to anyone on her team, including herself. The error message was unreadable - see below.

Additionally, we confirmed with Nina today that she has been unable to assign cases from the Lit Support queue to users on her team. She's been trying for the past week. 

Screenshot: 

<img width="1439" alt="Screen Shot 2019-03-14 at 11 49 41 AM" src="https://user-images.githubusercontent.com/40216950/54388055-44257680-4673-11e9-8547-5fbd4d0dc2b5.png">

**Comment by lowellrex** [comment]
@marvokdolor-gov Do we know if this is still happening? I can't reproduce it locally.

**Comment by marvokdolor-gov** [comment]
@lowellrex Charlene just let me know that she is still unable to assign in Caseflow. 
Would you like me to set up time for us to screen share with her?

**Comment by lowellrex** [comment]
Was able to reproduce this error just now! Work will resume on this ticket today!
