### ISSUE TITLE
Case timeline tasks out of order

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9968]
In this screenshot, the BVADispatch tasks are ordered before the Judge and Attorney tasks, even though those were completed first. 

![image (13)](https://user-images.githubusercontent.com/27704093/54380737-9a3dee00-4662-11e9-8f10-643540ed5192.png)

## AC
- Case timeline tasks are ordered newest to oldest, top to bottom

## Resources 
Related Case Timeline cleanup ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/9070

**Comment by tomas-nava** [comment]
SMALL ... assuming the date on the tasks is easily accessible
