### ISSUE TITLE
Update Case Details to remove "View Docs" link so ROs, call center folks, don't see it

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#9969]
Remove the "View Docs" link in Case Details for Regional Offices that are accessing their view of Caseflow Hearing Schedule (CSEM function, "RO ViewHearSched") 

Note that the user is prevented from accessing reader. They get a Drat message, but it would be more ideal if the link didn't appear.

**Comment by laurjpeterson** [comment]
We also need to remove this link for folks with the Caseflow Case Details CSEM function. [Slack message](https://dsva.slack.com/archives/C6E41RE92/p1552928084167600) where this was raised.

**Comment by MeredithStewart** [comment]
@laurjpeterson -- Do you know if this was already done for VSO Views of Caseflow?

**Comment by laurjpeterson** [comment]
Yes, this is already done for VSO views.

**Comment by lomaxap** [comment]
Should also confirm that we have a caseflow-wide standard for front-end permissions.
