### ISSUE TITLE
Intake | Remove AMA feature flags

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9972]
Now that AMA is fully in effect, we should remove all the related feature flags in our code.

These include:

* [x] `intake`
* [x] `intakeAma`
* [x] `intake_legacy_opt_in`

**Comment by leikkisa** [comment]
@Sjones352 Once these are all merged, could you do another pull request to remove these from appeals_deployment?

https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/features-config.yml

**Comment by Sjones352** [comment]
Pr in appeals-deployment
https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2039
