### ISSUE TITLE
Update team assignments for Lit Support and AOD

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9975]
Charlene (AOD user) and Nina (Lit Support user) all have access to the Mail team's queue. They don't need this access, and they can be removed from the mail team's list. 

Charlene CSSID: 
Nina CDDIS:

**Comment by laurjpeterson** [comment]
I've given Nina Lit Support team admin so she can do this for Lit Support. We need to add her to be team admin for AOD and mail, too.
