### ISSUE TITLE
Intake Edit | Add select input for removing or withdrawing issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9983]
Since there are now multiple actions you can take on a request issue on the edit screen, we need to have a select box next to each issue with the options.

All withdrawal/removal mocks: https://va-gov.invisionapp.com/share/BRQUJR5J5AE#/screens/351540954

## Acceptance Criteria
- Next to each issue on the edit issues screen, there should be a select box with two options, "Withdraw issue" and "Remove issue".
- If "Remove issue" is selected, it should do the same thing as if the "Remove issue" button was clicked.
- Nothing should happen if "Withdraw issue" is selected. We will handle that in a future story

## Mocks
<img width="1223" alt="Screenshot 2019-03-14 15 27 13" src="https://user-images.githubusercontent.com/1596259/54395723-e4789c80-466d-11e9-88f3-ac38be1e0417.png">

## Notes
- This functionality should be enabled and disabled using a feature flag named `:withdraw_decision_reviews`

**Comment by Sjones352** [comment]
**Passes UAT**
<img width="1680" alt="Screen Shot 2019-03-26 at 10 37 14 AM" src="https://user-images.githubusercontent.com/23080951/55006095-8d4ec200-4fb3-11e9-8404-9275783db692.png">
<img width="1438" alt="Screen Shot 2019-03-26 at 10 37 40 AM" src="https://user-images.githubusercontent.com/23080951/55006096-8d4ec200-4fb3-11e9-8893-307f69b74bfe.png">
<img width="1457" alt="Screen Shot 2019-03-26 at 10 38 11 AM" src="https://user-images.githubusercontent.com/23080951/55006097-8d4ec200-4fb3-11e9-8b81-d06b9c024c75.png">
<img width="1456" alt="Screen Shot 2019-03-26 at 10 38 21 AM" src="https://user-images.githubusercontent.com/23080951/55006098-8de75880-4fb3-11e9-80b4-217f260a9992.png">
<img width="1338" alt="Screen Shot 2019-03-26 at 10 38 32 AM" src="https://user-images.githubusercontent.com/23080951/55006100-8de75880-4fb3-11e9-98f0-4264e2a5ba4c.png">
