### ISSUE TITLE
Intake Edit | Save withdrawn issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9985]
We need to save withdrawn issues.

All withdrawal/removal mocks: https://va-gov.invisionapp.com/share/BRQUJR5J5AE#/screens/351540954

requires #9984
requires #9730

## Acceptance Criteria
- When "Save" is pressed on the Add/Remove issues page with one or more issues pending withdraw. Those issues should be closed as withdrawn with closed_at matching the date entered in the field.
- For VBMS based decision reviews, withdrawn issues should remove the matching contention as well as the EP, if it was the last contention on the EP. This should behave exactly like a removed issue in this regard.
- If all issues are withdrawn or removed from a Caseflow task based decision review, it should close all of those tasks in the same way as https://github.com/department-of-veterans-affairs/caseflow/issues/9730  
- If the withdrawn issue was an Opt-in of a VACOLS issue, it __should not__ reopen the VACOLS issue.

## Notes
- Updates to the confirmation pages will not be handled in this story.
- Showing withdrawn issues on the edit page after they are saved are not part of this story.

## Technical Notes
- This functionality should be enabled and disabled using a feature flag named `:withdraw_decision_reviews`

**Comment by Sjones352** [comment]
**Passes Uat** 
<img width="1385" alt="Screen Shot 2019-04-11 at 1 21 49 PM" src="https://user-images.githubusercontent.com/23080951/55977501-f9405400-5c5c-11e9-923a-e1fb166bfe9e.png">
