### ISSUE TITLE
Intake Edit | Show saved withdrawn issues on the edit screen

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9986]
When the Add/Remove issues page is visited, we should show all issues that have been withdrawn for that decision review, and when they were withdrawn.

All withdrawal/removal mocks: https://va-gov.invisionapp.com/share/BRQUJR5J5AE#/screens/351540954

requires #9985 

## Acceptance Criteria
- On the Add/Remove issues page, show any issues that have been withdrawn in the past, with the date that they were removed. These should go in the "Withdrawn issues" section as shown in https://github.com/department-of-veterans-affairs/caseflow/issues/9984

## Mocks
<img width="1182" alt="Screenshot 2019-03-14 15 54 04" src="https://user-images.githubusercontent.com/1596259/54396791-6cac7100-4671-11e9-9bb9-dbeb173f235a.png">

## Notes
- Note the withdrawal date prompt should only show up if there are _Pending_ withdrawals. Issues that have been withdrawn in the past should not trigger the withdrawal date prompt to show up.

**Comment by leikkisa** [comment]
For the list bullet points I don't think we'll be able to maintain the original index numbers from when the issues were originally withdrawn (they'll change), but that shouldn't negatively impact anything.

**Comment by leikkisa** [comment]
Passes in UAT:
![Screen Shot 2019-05-01 at 5.27.13 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/6b931c73-4787-4f63-bc4e-94ac5ac774f5)
