### ISSUE TITLE
Styleguide Component | User dropdown Menu

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#999]
As a user, I want to be able to click a dropdown button that is easy to find with options that are clear to understand. 

As a developer and designer, I want clear and consistent actions to increase design and development efficiency across apps.

## Acceptance Criteria 

1. Verify that the title "User dropdown menu" appears
1. Verify that there is a horizontal line above the title
1. Verify that the "User dropdown menu" appears under the copy with the related react component 
1. Verify that the "User dropdown menu" appears on the left nav and clicking it takes you to the appropriate element 
1. Verify the the hover color is #5B616B
1. Verify that once the text field is selected, it has the default focus 

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/24341712/898a0ee0-1289-11e7-9d73-223b38c84fdc.png)

[Link to see assets in InVision Craft](https://projects.invisionapp.com/d/main#/console/10592592/225671393/inspect)

# Copy

User dropdown menu

This menu indicates which user is signed in and contains links to submit feedback, view the application’s help page, see newly launched features, and log out. Users can view their names on the navigation bar at all times and click on the dropdown icon to view further options.

# Related Stories
The hovers and clicks are similar to #1243.

**Comment by KHarshawat-gov** [comment]
![image](https://cloud.githubusercontent.com/assets/25437276/23619201/e960a146-0260-11e7-8ca6-f978c5fba6a9.png)

**Comment by mmlumba** [comment]
@gnakm Is there copy I can use for this component?

**Comment by gnakm** [comment]
This menu indicates which user is signed in and contains links to submit feedback, view the application’s help page, see newly launched features, and log out. Users can view their names on the navigation bar at all times and click on the dropdown icon to view options.

**Comment by astewarttistatech** [comment]
@mmlumba 

Current view of style guide: 

<img width="1347" alt="screen shot 2017-04-18 at 10 28 21 am" src="https://cloud.githubusercontent.com/assets/23038505/25135972/c714f7ee-2421-11e7-9002-a34003d8a4d4.png">

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in DEV
Browsers validated on: FF 

Steps to Validate: 
1. Go to the living style guide and verify that the "User Dropdown Menu" matches the mock's copy and UI. 

Screenshots: 
<img width="791" alt="screen shot 2017-04-18 at 10 32 19 am" src="https://cloud.githubusercontent.com/assets/23038505/25136390/d89366a8-2422-11e7-8447-6757892f8782.png">
<img width="776" alt="screen shot 2017-04-18 at 10 32 27 am" src="https://cloud.githubusercontent.com/assets/23038505/25136391/d8939290-2422-11e7-8c0d-558df1e8c6ac.png">
