### ISSUE TITLE
Intake Navigation | Help | Update Introduction and Frequently Asked Questions

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#9990]
As Lead Trainer, I would like to update the Intake Help Page so that the users can obtain additional detailed information on how to use this product.

### Introduction Section
1. Verify that in the "Welcome to the Intake Help Page!" section, the copy has been updated to the following:
     >  Here you will find [Training Videos]() and [Frequently Asked Questions (FAQs)]() for Intake, as well as links to the Quick Reference Guides (QRG). These items are provided to assist you as you access and use Queue. If you require further assistance after reviewing these items, please contact the Caseflow Product Support Team by using the "Send feedback" link located in the drop-down menu next to your username or the “Send feedback” link located at the bottom right-hand corner of the screen.

     > - [Intake - Compensation and Pension]()	
     > - [Intake - Non-Compensation and Pension]()	

2. Verify that in the introduction section, the text "Training Videos" is a hyperlink to the Training video section.
3. Verify that in the introduction section, the text "Frequently Asked Questions (FAQs)" is a hyperlink to the Frequently Asked Questions section.
4. Verify that the words for each available QRG is a link.
5. Verify that when each of the available QRG links are clicked, the following respective pdf is displayed in a new tab with its respective title. 
     - [Intake - Compensation and Pension???.PDF](??????)
     - [Intake - Non-Compensation and Pension???.PDF](??????)

## Mocks
**_Help Page - Introduction section requiring change_**
![image](https://user-images.githubusercontent.com/41164406/54432171-c9a23880-46fe-11e9-81bb-82b274823f11.png)

**_Help Page - Training Videos_**
![image](https://user-images.githubusercontent.com/41164406/54432240-fc4c3100-46fe-11e9-91e0-7a4b45eedf5c.png)

**_Help Page - Frequently Asked Questions_**
![image](https://user-images.githubusercontent.com/41164406/54432240-fc4c3100-46fe-11e9-91e0-7a4b45eedf5c.png)

# Related Stories

**Comment by carolaponce** [comment]
@msj0nes - I had proposed some updates to this page, please review: 
https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/AMA_training/Intake_helpPage.docx

**Comment by carolaponce** [comment]
@msj0nes  also - here is our updated training guide:
[Intake_TrainingGuide_2019.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/2979039/Intake_TrainingGuide_2019.pdf)

**Comment by laurjpeterson** [comment]
Closing because I checked in prod and it looks up to date with the docs in this ticket!
