### ISSUE TITLE
Should we create a new appeal stream for motions records in Caseflow?

### ISSUE THREAD

**Issue by allyceh** [department-of-veterans-affairs/caseflow#9993]
Creating a ticket for this open question so that we can track it and so that we can have our engineering team weigh in on technical complexity. 

We learned that Lit Support opens a new record for Motions and CAVC cases in VACOLS and they track them separate from Original cases. In Caseflow search results, Nina also mentioned that motions attorneys would like to see a list of cases that are either original, CAVC, or other motions to quickly understand the story of a claim.

Two potential approaches were discussed for tracking post-decisional motions in Caseflow: 
- Continue tracking the motion or CAVC case in the Veteran's current appeal record
- When the Veteran files a post-decisional motion, open a new, separate record to track the motion

MVP proposed approach: 
- Propose to Lit Support that we'll track CAVC cases and motions in the Veteran's current appeal. 
  - We'll add motions tasks to the Veteran's Case Timeline and change the case type to "CAVC" or "Motion for Reconsideration". 

Higher-effort proposed approach: 
- When a Motions Attorney/Lit Support receives a motion, they have the ability to open a new record OR Caseflow automatically opens a new record to track tasks related to that motion. 
- When users view all appeal streams, they will see the Original case and Motion for Reconsideration case (for example) displayed as separate items in a list. 

Open questions: 
- What is the technical complexity of opening a new appeal record when a motion task is created?
- Given the mail team context of motions, do we want to automatically create a new appeal record when they assign a motions task to Lit Support? Is there a risk that it's not actually a motion, and that we're opening records that might need to be closed due to error?

**Comment by allyceh** [comment]
cc: @laurjpeterson Our convo earlier.

**Comment by laurjpeterson** [comment]
I think we should just continue to add tasks to the same appeal in Caseflow. That is, do **not** create a new record (which I think could mean having a new docket number, etc. or defining a whole new type of record), but add tasks (e.g. Motion for Reconsideration) to the Root task for that appeal. 

This would be a change, because I think right now we close RootTasks when appeals are dispatched from the Board. (If that's the case, I wonder if we can keep them open, and use just the fact that the BVADispatchTask is complete as an indication that the appeal is complete so we can keep the RootTask open to deal with scenarios like this.)

@cmgiven - do you see any pros to Motions being their own type of record in Caseflow that I don't see?

**Comment by cmgiven** [comment]
The VACOLS approach to motions makes it difficult to understand what post-decisional motions have been filed against a particular appeal. The advantage in a VACOLS context is that it allows you to record a second decision on the reconsideration, but we potentially have a lot more flexibility in how we record decisions.

I could certainly make an argument for tracking CAVC appeals separately, as it seems analogous to Supplemental Claim/Higher-Level Review/Board Appeal. We would then track CAVC issues using the same RequestIssues/DecisionIssues framework we use for everything else.

Arguably a post-decisional motion should be considered the same way. And unlike VACOLS, we're set up to handle the linkage of the motion to the appeal by nature of how we do issue linking.

**Comment by laurjpeterson** [comment]
@cmgiven to clarify 
> Arguably a post-decisional motion should be considered the same way. And unlike VACOLS, we're set up to handle the linkage of the motion to the appeal by nature of how we do issue linking.

Post-decisional motions should be considered the same way as tracking CAVC appeals separately? So they should be their own record instead of tasks added to the previous appeal?

**Comment by cmgiven** [comment]
There are pros and cons both ways. But the argument for making it its own record is that the motion has the potential to have its own set of DecisionIssues, something that becomes more complex if it’s just a task on the original appeal.

**Comment by laurjpeterson** [comment]
Discussion 3/20:

- Decision to use a new "record" / a new "appeal" with a specific type:
   - pros: it allows us to only select issues that are being reconsidered, vacated, etc.
   - cons: story of the whole appeal process is more confusing, you have to jump through different appeals streams

- need a flow to intake issues to this Vacate record from the previously decided appeal
- Lit Support folks add issues like Caseflow Intake
- would need to make sure that issues from BVA decisions can be chosen in this intake flow

**Comment by marvokdolor-gov** [comment]
This discussion ended up getting moved back to the original ticket, see the 04/03/2019 decision [here](https://github.com/department-of-veterans-affairs/caseflow/issues/8547#issuecomment-479498749).

**Comment by allyceh** [comment]
Closing this ticket. Decisions on this are being made as part of work in #8547 .
