### ISSUE TITLE
Remove AMA case distribution flag and legacy-only distribution code

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9995]
Now that [we've rolled out AMA case distribution](https://github.com/department-of-veterans-affairs/appeals-deployment/blob/e4595d3861b179867a96b969afb960057d14e572/ansible/vars/features-config.yml#L167) to everyone we should remove the `ama_auto_case_distribution` feature flag, make that code path the default, and remove the [legacy-only case distribution code](https://github.com/department-of-veterans-affairs/caseflow/blob/100048bb0c6e59e4a9ce220a3f9eb7c4878a873f/app/models/distribution.rb#L37).

## Acceptance criteria
* [ ] Remove the `ama_auto_case_distribution` feature flag
* [ ] Remove the legacy-only case distribution code path

**Comment by aroltsch** [comment]
Completed in https://github.com/department-of-veterans-affairs/caseflow/pull/10895/files
