### ISSUE TITLE
Distribute dismissals as part of auto-case distribution

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9996]
Currently, appeals that are dismissed (for example due to withdrawal or appellant death) are distributed manually outside of the auto-case distribution mechanism. This ticket exists to incorporate the distribution of dismissals into auto-case distribution.

The work required for a dismissal is much lighter than the work required to draft a decision for an appeal that has not been dismissed, as such we should distinguish between these appeals in order to evenly distribute these appeals among judges. We could do this by effectively treating dismissals from each docket as their own docket and distribute them proportionately.

## Acceptance criteria
* [ ] Explicitly distribute dismissals evenly in the auto-case distribution process.

## Outstanding questions
* How do we indicate that an appeal has been dismissed?

**Comment by araposo-tistatech** [comment]
@araposo-tistatech ensure the above is still aligned with Board needs.
