### ISSUE TITLE
Enable hearings-only case distributions

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9998]
Currently, when a judge requests cases [we first distribute cases](https://github.com/department-of-veterans-affairs/caseflow/blob/68c31a63721ccdec7a0a3f1347ada270f8524088/app/models/concerns/ama_case_distribution.rb#L20) that are "tied to that judge" (either because that judge held the hearing or the case is AOD and has been remanded by CAVC) before distributing "genpop" cases (cases that are not tied to a specific judge). This ticket exists to separate those two pieces of logic and allow for the distribution of only "non-genpop" cases for a judge (for example, a DVC who is no longer working as a judge but is still signing decisions for hearings they heard when they were a judge).

## Acceptance criteria
* [ ] Ability to request only cases that are tied to a specific judge is allowed by the code.

**Comment by araposo-tistatech** [comment]
Closing as this is an outdated request, most recent #14538
