### ISSUE TITLE
Include hearings docket cases in auto-case distribution

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9999]
Hearings will start being held for AMA appeals in the hearings docket on April 1st, so auto-case distribution needs to distribute appeals in the hearings docket on that date as well. In order to do this we will need to build out [the `HearingRequestDocket` class](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/dockets/hearing_request_docket.rb) in the model of [the `DirectReviewDocket` class](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/dockets/direct_review_docket.rb).

For more information about when a case is eligible for distribution see [this related github discussion](https://github.com/department-of-veterans-affairs/caseflow/issues/8288).

## Acceptance criteria
* [ ] Build out the `HearingRequestDocket` class.
* [ ] Auto-case distribution distributes cases from the hearings docket.

**Comment by cmgiven** [comment]
The key differences from the parent class:

* `age_of_n_oldest_priority_appeals` should only return the age of genpop priority cases, while the parent class implementation would return the ages of any priority case.
* `distribute_appeals` needs to be implemented such that if the `genpop` argument is equal to "not_genpop", it will only distribute appeals that are tied to the `distribution.judge`. If it is equal to "only_genpop", it will distribute genpop appeals.

**Comment by laurjpeterson** [comment]
@cmgiven - @monfresh and i connected yesterday about this gh issue. he mentioned that in order to determine whether or not a judge is active, we thought we would check when they last logged in. If they haven’t logged in in the past 60 days, they would be considered inactive.

for legacy auto-case distribution, i think we determine whether a judge is active through the VACOLS staff table. 

(1) should we coalesce around one way to do it for legacy and AMA (note: i realize changing legacy should likely be a different ticket)
(2) is the 60 day number a best guess? it seems fine to me, though i could see the edge case that judges on staff could take more than 60 days for leave for certain circumstances. i wonder if we should vet this number or not

**Comment by cmgiven** [comment]
This doesn't apply to legacy case distribution. There, the case is tied to the judge, regardless of whether the judge is active or inactive, until the Veteran waives that right or is provided a hearing with a different judge.

I don't think that (2) is a problem. If a judge is taking more than 60 days of leave, I would argue that the case _should_ be assigned to a different judge who can decide it more quickly. But yes, this is just a first guess, and I think it would be a good topic to discuss with the DVCs.

**Comment by laurjpeterson** [comment]
@sharonwarner - to distribute hearings cases, for hearings that have been held, we need to wait for (1) the 90 day evidence window to be complete and (2) the transcription to be complete. could you link to the PRs where tango team implemented the transcription task functionality? i think @monfresh will need it to complete work around distributing hearing docket appeals (note: i realize this could be split out in multiple tickets if needed - moncef feel free to do so)

**Comment by cmgiven** [comment]
@laurjpeterson: I believe we don't create the DistributionTask until the evidence window and transcription are complete. That's at least how it works on the New Evidence docket. As a result, those cases don't appear as "ready" for case distribution purposes.

**Comment by laurjpeterson** [comment]
@cmgiven - amazing. thanks for reminding me of that! however, New Evidence docket wouldn't have a TranscriptionTask. do we need to add it in for these hearing docket appeals?

**Comment by cmgiven** [comment]
That's the limit of my knowledge. I think it was built out, but I defer to you, @sharonwarner!
